# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, B, K, C = "Hélène", "M. Bastide", "Karim", "Chloé"
D = [
(None, "Mardi 7 juillet, 7 h 45. Une semaine après la panne du frigo. La camionnette de Bastide se gare devant le restaurant. Il décharge, moins souriant que d'habitude.", "7월 7일 화요일 오전 7시 45분. 냉장고 고장 일주일 뒤. 바스티드의 트럭이 식당 앞에 선다. 그는 평소보다 덜 웃으며 짐을 내린다."),
(B, "Bonjour, bonjour ! Livraison Bastide, ma p'tite Hélène !", "안녕, 안녕! 바스티드 납품이에요, 우리 엘렌!"),
(H, "Bonjour, monsieur Bastide. Vous n'avez pas le sourire, ce matin.", "안녕하세요, 바스티드 씨. 오늘 아침엔 웃음이 없으시네요."),
(B, "Ben, j'ai connu mieux. Mais faut bien que j'décharge, hein ?", "글쎄, 더 좋은 날도 있었지. 그래도 짐은 내려야 하지 않겠어?"),
(K, "Bonjour, monsieur Bastide. Je prends les cagettes de tomates ?", "안녕하세요, 바스티드 씨. 토마토 상자 받을까요?"),
(B, "Oui, mon gars. Attention, elles sont lourdes. Et tièdes, avec c'te chaleur.", "그래, 젊은이. 조심해, 무거워. 이 더위에 미지근하기도 하고."),
(C, "Bonjour ! Je peux vérifier les poids avec ma tablette ?", "안녕하세요! 제 태블릿으로 무게를 확인해도 될까요?"),
(B, "Mademoiselle Chloé ! Vous faites des progrès, à c'qu'on dit.", "클로에 아가씨! 실력이 늘었다고들 하던데."),
(C, "Merci. J'ai eu un bon professeur. Il m'a appris à casser les asperges.", "고맙습니다. 좋은 선생님을 만났어요. 아스파라거스 꺾는 법을 가르쳐 주셨죠."),
(B, "Ha ha ! Sacré souvenir. Bon, allez, les carottes, les tomates, les courgettes.", "하하! 대단한 추억이네. 자, 당근, 토마토, 애호박 가져왔어."),
(H, "Je vois ça. Tout est beau. Mais vous avez un air bizarre, monsieur Bastide.", "보이네요. 다 좋아 보여요. 근데 바스티드 씨 표정이 좀 이상해요."),
(B, "Hélène... J'vais pas tourner autour du pot. J'ai une mauvaise nouvelle.", "엘렌... 돌려 말하진 않을게. 나쁜 소식이 있어."),
(H, "Allez-y. Après le mois qu'on vient de passer, rien ne m'étonne.", "말씀하세요. 이번 달 같은 한 달을 보내고 나면 뭐든 놀랍지 않아요."),
(B, "J'augmente mes prix. Pas par plaisir, tu me connais.", "가격을 올려야 해. 좋아서 하는 건 아니야, 날 알잖아."),
(H, "Vous augmentez de combien ?", "얼마나 올리시는데요?"),
(B, "Les légumes, douze pour cent. La viande, neuf. Le beurre et la crème, huit.", "채소는 12퍼센트. 고기는 9. 버터랑 크림은 8."),
(K, "Douze pour cent ! Mais ça fait beaucoup, ça !", "12퍼센트요! 엄청나잖아요, 그건!"),
(B, "J'sais, mon gars. Moi non plus, ça m'fait pas plaisir.", "알아, 젊은이. 나도 기분 좋진 않아."),
(H, "Expliquez-moi, monsieur Bastide. Pourquoi tant ?", "설명해 주세요, 바스티드 씨. 왜 그렇게 많이요?"),
(B, "D'abord, la pluie. Ce printemps, ça n'a pas arrêté. Tout un champ de courgettes noyé.", "우선 비예요. 올봄엔 그치질 않았어. 애호박 밭 하나가 통째로 물에 잠겼지."),
(B, "Pis, les sacs de grain pour mes bêtes. Ils ont monté de vingt pour cent en un an.", "그리고 가축 사료 포대. 1년 새 20퍼센트나 올랐어."),
(B, "Et le gasoil ! Mon camion fait quatre cents kilomètres par semaine pour venir ici.", "게다가 경유! 내 트럭이 이리 오려고 일주일에 400킬로미터를 달려."),
(C, "Excusez-moi, je ne comprends pas bien. « Augmenter de douze pour cent », ça veut dire quoi ?", "죄송한데 잘 이해가 안 돼요. « 12퍼센트 오른다 »는 게 무슨 뜻이에요?"),
(H, "Bonne question. Prends les carottes : elles sont à 2,50 € le kilo.", "좋은 질문이야. 당근을 봐. 킬로에 2.50유로지."),
(H, "Douze pour cent de 2,50 €, c'est 30 centimes. Le kilo passe de 2,50 à 2,80 €.", "2.50유로의 12퍼센트는 30센트야. 킬로당 2.50에서 2.80유로가 되는 거지."),
(C, "Ah, d'accord ! Une hausse de 30 centimes. Et pour les tomates ?", "아, 알겠어요! 30센트 인상이네요. 토마토는요?"),
(H, "Les tomates sont à 4 € le kilo. Douze pour cent, ça fait 48 centimes.", "토마토는 킬로에 4유로. 12퍼센트면 48센트야."),
(K, "Donc les tomates passent à 4,48 €.", "그러니까 토마토는 4.48유로가 되네요."),
(C, "Et la viande ? L'épaule de veau est à 14 € le kilo.", "고기는요? 송아지 어깨살이 킬로에 14유로예요."),
(H, "Neuf pour cent de 14, c'est 1,26 €. On passe à 15,26 €.", "14의 9퍼센트는 1.26유로야. 15.26유로가 되지."),
(B, "J'ai arrondi à 15,25 €. Cinq centimes de cadeau !", "내가 15.25유로로 맞췄지. 5센트 선물이야!"),
(H, "Merci pour les cinq centimes. Mais ça fait quand même 1,25 € de plus par kilo.", "5센트 고맙네요. 그래도 킬로당 1.25유로가 더 드는 건데요."),
(B, "C'est pas moi qui fais les prix, Hélène. C'est la vie.", "가격을 내가 정하는 게 아니야, 엘렌. 세상이 그래."),
(H, "Je ne dis pas que c'est vous. Mais calculons ce que ça représente pour nous.", "당신 탓이라는 게 아니에요. 우리한테 어떤 의미인지 계산해 봐요."),
(K, "Chaque semaine, on achète à peu près quatre cents euros de légumes.", "우린 매주 채소를 대략 400유로어치 사요."),
(H, "Six cents euros de viande, et cent cinquante de beurre et de crème.", "고기는 600유로, 버터와 크림은 150유로."),
(C, "Je calcule. Douze pour cent de 400 : c'est 48 €.", "계산할게요. 400의 12퍼센트는 48유로예요."),
(C, "Neuf pour cent de 600 : 54 €. Et huit pour cent de 150 : 12 €.", "600의 9퍼센트는 54유로. 150의 8퍼센트는 12유로고요."),
(K, "48 plus 54, 102. Plus 12 : 114 € de plus par semaine.", "48 더하기 54는 102. 12를 더하면 매주 114유로 더 나가요."),
(H, "114 fois 52, ça fait presque 5 900 € de plus par an.", "114 곱하기 52면 1년에 5,900유로 가까이 더 나가."),
(C, "Presque six mille euros ! Par an !", "거의 6천 유로요! 1년에!"),
(H, "Et le loyer augmente de 16 800 € en octobre. Donc presque 23 000 € de charges en plus.", "게다가 10월엔 임대료가 연 1만 6,800유로 오르지. 그러면 비용이 거의 2만 3천 유로 늘어."),
(B, "Le loyer aussi ? Oh, ma pauvre... J'savais pas.", "임대료도? 아이고, 가엾어라... 몰랐네."),
(H, "Delmas augmente de trente-sept pour cent. Je n'en parle pas trop, mais voilà.", "델마스 씨가 37퍼센트 올려요. 별로 말은 안 하지만, 그렇게 됐어요."),
(B, "Trente-sept ! Mon doux Seigneur... Ça va point, ça va point du tout.", "37이라니! 맙소사... 그건 안 좋아, 전혀 안 좋아."),
(H, "Alors vous comprenez que je ne peux pas accepter vos prix tels quels.", "그럼 제가 당신 가격을 그대로 받아들일 수 없다는 것도 이해하시겠죠."),
(B, "Hélène, j'ai moi-même des charges. Je peux pas travailler à perte.", "엘렌, 나도 비용이 있어. 손해 보며 일할 순 없어."),
(H, "Je sais. Je ne vous demande pas de perdre de l'argent. Je vous demande de réfléchir.", "알아요. 손해를 보시라는 게 아니에요. 다시 생각해 달라는 거예요."),
(B, "Réfléchir à quoi ? Les prix sont les prix.", "뭘 다시 생각해? 가격은 가격이야."),
(H, "Écoutez-moi. Ça fait plus de vingt ans qu'on travaille ensemble.", "들어 보세요. 우리가 함께 일한 지 20년이 넘었어요."),
(B, "Vingt ans, oui. Votre mère, elle me payait en liquide et elle me donnait toujours un café.", "20년, 그렇지. 네 어머니는 현금으로 주고 늘 커피를 한 잔 내줬어."),
(H, "Voilà. On est de la même famille, pour ainsi dire.", "그러니까요. 말하자면 우린 한 가족이에요."),
(K, "Chef, on pourrait lui proposer un engagement ferme ?", "셰프, 확정 주문 약속을 제안해 보면 어때요?"),
(B, "Un engagement ferme ? Dis voir, mon gars.", "확정 주문 약속? 말해 봐, 젊은이."),
(H, "Karim a raison. Je vous donne une commande fixe chaque lundi soir.", "카림 말이 맞아요. 매주 월요일 저녁에 고정 주문을 드릴게요."),
(H, "Vous savez à l'avance ce que vous plantez et ce que vous livrez.", "뭘 심고 뭘 가져올지 미리 아시게 되는 거죠."),
(B, "Hum. Ça m'arrangerait, c'est vrai. Moins de pertes, moins de gaspillage.", "흠. 그건 내게도 도움이 되겠네. 손실도 낭비도 줄고."),
(H, "Alors en échange, je voudrais une baisse du prix des légumes.", "그럼 그 대신 채소 가격을 내려 주셨으면 해요."),
(B, "Baisser ? Jamais ! J'peux pas baisser, j'peux juste moins augmenter.", "내려요? 절대 안 돼! 내릴 순 없고, 덜 올릴 수는 있지."),
(H, "D'accord. Moins augmenter, c'est quoi, pour vous ?", "좋아요. 덜 올린다는 게 얼마를 말씀하시죠?"),
(B, "Onze pour cent.", "11퍼센트."),
(H, "Onze, ce n'est pas assez. Dix pour cent, et c'est ferme pour six mois.", "11은 부족해요. 10퍼센트에, 6개월 동안 확정으로 해요."),
(B, "Dix pour cent... Les carottes à 2,75 € ? Ça m'fait mal au ventre.", "10퍼센트... 당근이 2.75유로? 배가 아픈데."),
(C, "Dix pour cent de 2,50 €, c'est 25 centimes. Donc 2,75 € : le calcul est juste.", "2.50유로의 10퍼센트는 25센트예요. 그러니까 2.75유로, 계산이 맞아요."),
(B, "Sacrée petite ! Elle compte plus vite que ma comptable.", "대단한 아가씨네! 우리 회계사보다 빨리 계산하는군."),
(H, "Pour la viande, neuf pour cent, ça ne passe pas.", "고기는 9퍼센트로는 안 돼요."),
(B, "Ma viande est la meilleure du quartier. Tu l'as dit toi-même.", "내 고기가 이 동네 최고야. 네가 직접 말했잖아."),
(H, "Oui, et c'est pour ça que je veux continuer. Mais Dubreuil m'a fait une offre.", "맞아요, 그래서 계속하고 싶은 거예요. 그런데 뒤브레유가 제안을 해 왔어요."),
(B, "Dubreuil ! Ce grand escogriffe ! Combien il te propose ?", "뒤브레유! 그 껑충한 작자가! 얼마를 제시했어?"),
(H, "Je n'ai pas encore le devis. Il me l'envoie cette semaine.", "아직 견적서는 없어요. 이번 주에 보낸대요."),
(B, "Alors tu bluffes, hein ? Pour me faire baisser ?", "그럼 허세인 거지? 날 깎으려고?"),
(H, "Non. Je veux comparer, c'est tout. Vous feriez la même chose à ma place.", "아니에요. 비교하고 싶을 뿐이에요. 제 입장이면 똑같이 하셨을 거예요."),
(B, "C'est vrai. J'aurais fait pareil, pardi.", "맞아. 나라도 똑같이 했겠지, 암."),
(K, "Monsieur Bastide, on ne veut pas vous quitter. On veut juste tenir.", "바스티드 씨, 우리는 당신과 헤어지고 싶지 않아요. 그저 버티고 싶을 뿐이에요."),
(B, "Tenir, hein ? Moi aussi, mon gars. Tout le monde veut tenir.", "버틴다, 응? 나도 마찬가지야, 젊은이. 모두가 버티고 싶지."),
(B, "Bon. J'vais te dire. La viande à cinq pour cent, pas plus.", "좋아. 이렇게 하지. 고기는 5퍼센트, 그 이상은 안 돼."),
(H, "Cinq pour cent de 14, ça fait 70 centimes. Donc l'épaule à 14,70 €.", "14의 5퍼센트는 70센트예요. 그러니까 어깨살은 14.70유로."),
(B, "C'est ça. Quatorze euros soixante-dix. Et je t'en garde du meilleur.", "맞아. 14유로 70. 그리고 제일 좋은 걸로 남겨 줄게."),
(H, "Pour le beurre et la crème ?", "버터와 크림은요?"),
(B, "Là, j'peux pas bouger. C'est ma cousine qui fixe, et elle est têtue. Huit pour cent.", "거긴 못 움직여. 사촌이 정하는데 고집이 세. 8퍼센트."),
(C, "Huit pour cent de 9 €, le beurre de baratte : 72 centimes. Il passe à 9,72 €.", "9유로짜리 수제 버터의 8퍼센트는 72센트. 9.72유로가 돼요."),
(H, "D'accord pour le beurre. Les œufs ?", "버터는 좋아요. 달걀은요?"),
(B, "Les œufs, je les bouge pas. Neuf euros le plateau. C'est mes poules, c'est mon prix.", "달걀은 안 건드려. 한 판에 9유로. 내 닭들이고 내 가격이야."),
(K, "Merci, monsieur Bastide. C'est déjà un geste.", "감사합니다, 바스티드 씨. 그것만으로도 성의죠."),
(H, "Refaisons le calcul. Légumes : dix pour cent de 400, c'est 40 €.", "다시 계산해 봐요. 채소는 400의 10퍼센트라 40유로."),
(C, "Viande : cinq pour cent de 600, ça fait 30 €.", "고기는 600의 5퍼센트니까 30유로예요."),
(K, "Beurre et crème, toujours 12 €. Total : 40 plus 30 plus 12. Quatre-vingt-deux euros.", "버터와 크림은 그대로 12유로. 합계는 40 더하기 30 더하기 12, 82유로."),
(H, "Quatre-vingt-deux au lieu de cent quatorze. On gagne 32 € par semaine.", "114 대신 82유로. 매주 32유로를 아끼는 거야."),
(C, "Sur l'année, ça fait 1 664 €. Ce n'est pas rien !", "1년이면 1,664유로예요. 적지 않아요!"),
(B, "Ben dis donc, tu m'as bien eu, ma p'tite Hélène.", "이런, 나를 제대로 잡았구나, 우리 엘렌."),
(H, "Vous avez bien joué aussi. Vous avez maintenu la viande et le beurre.", "당신도 잘하셨어요. 고기랑 버터는 지키셨잖아요."),
(B, "J'ai quand même cédé sur les légumes et sur la viande. J'ai l'impression de perdre.", "그래도 채소랑 고기는 양보했는걸. 지는 기분이야."),
(H, "On a tous les deux perdu un peu. C'est ça, un bon compromis.", "둘 다 조금씩 잃은 거예요. 그게 좋은 타협이죠."),
(B, "Un bon compromis, c'est quand tout le monde est mécontent, hein ?", "좋은 타협이란 모두가 불만일 때 성립하는 거지, 그렇지?"),
(K, "Ça, c'est le proverbe de Lucien, non ?", "그거 뤼시앵의 속담 아니에요?"),
(B, "Lucien ! Dis-lui bonjour de ma part. Il est où, c'matin ?", "뤼시앵! 내 안부 전해 줘. 오늘 아침엔 어디 있어?"),
(H, "Il arrive vers huit heures. Il va vous parler du temps, comme d'habitude.", "8시쯤 올 거예요. 평소처럼 날씨 얘기를 하시겠죠."),
(B, "Du temps ! Il a raison. Le vrai coupable, c'est le temps.", "날씨 얘기! 그분 말씀이 맞아. 진짜 범인은 날씨야."),
(H, "Il y a une condition, monsieur Bastide. Je compare avec Dubreuil cette semaine.", "조건이 하나 있어요, 바스티드 씨. 이번 주에 뒤브레유와 비교해 볼 거예요."),
(B, "D'accord. Mais si c'est trop près, tu m'appelles avant de décider.", "좋아. 하지만 차이가 아주 작으면 결정하기 전에 나한테 전화해."),
(H, "Promis. Et si c'est beaucoup moins cher chez lui, je vous le dirai franchement.", "약속해요. 그쪽이 훨씬 싸면 솔직하게 말씀드릴게요."),
(B, "Franchement, ça me ferait de la peine. Mais je le comprendrais.", "솔직히 서운하겠지. 그래도 이해는 할 거야."),
(C, "Monsieur Bastide, je peux vous poser une question ? Pourquoi vous ne baissez pas plus ?", "바스티드 씨, 질문 하나 드려도 돼요? 왜 더 내려 주지 않으세요?"),
(B, "Parce que mon prix, c'est le prix de la terre, de la pluie et de mon dos.", "내 가격은 땅과 비와 내 허리의 값이거든."),
(B, "Quand t'auras tes propres légumes, tu comprendras, petite.", "너도 네 채소를 키워 보면 알게 될 거야, 아가씨."),
(C, "Alors je note : « Le prix de la terre, de la pluie et du dos ».", "그럼 수첩에 적어 둘게요. « 땅과 비와 허리의 값 »."),
(B, "Ha ha ! Elle me fait rire, cette petite. Allez, je finis de décharger.", "하하! 이 아가씨 웃기네. 자, 나머지 짐 마저 내릴게."),
(K, "Je vous aide. Il reste les poireaux et les courgettes.", "도와드릴게요. 대파랑 애호박이 남았죠."),
(H, "Voici le bon de livraison. Vérifions les prix avant de signer.", "여기 납품서요. 서명하기 전에 가격부터 확인해요."),
(B, "Carottes, 2,75 €. Tomates, 4,40 €. Veau, 14,70 €. Beurre, 9,72 €.", "당근 2.75유로. 토마토 4.40유로. 송아지 14.70유로. 버터 9.72유로."),
(C, "Tomates à 4,40 €, c'est dix pour cent de 4 €. Le calcul est exact.", "토마토 4.40유로는 4유로의 10퍼센트 인상이에요. 계산이 정확해요."),
(H, "Parfait. Je signe. Mais je note la date : sept juillet, prix fermes jusqu'à fin décembre.", "좋아요. 서명할게요. 날짜를 적어 둘게요. 7월 7일, 12월 말까지 가격 확정."),
(B, "Fin décembre, d'accord. Et on se reparle à Noël, avec une bonne bouteille.", "12월 말까지, 알겠어. 그리고 크리스마스에 좋은 와인 한 병 놓고 다시 얘기하자."),
(H, "Avec plaisir. Même si c'est moi qui paierai la bouteille.", "기꺼이요. 병값은 제가 내겠지만요."),
(B, "Pardi ! Bon, j'file. Allez, bon courage, tous les trois !", "그렇고말고! 자, 난 간다. 세 사람 다 힘내!"),
(None, "La camionnette redémarre. Hélène regarde le bon signé, puis les cagettes empilées dans la cuisine.", "트럭이 다시 출발한다. 엘렌은 서명한 납품서를 보고, 주방에 쌓인 상자들을 바라본다."),
(K, "Tu as bien négocié, chef. Trente-deux euros par semaine, c'est quand même ça.", "협상 잘하셨어요, 셰프. 주 32유로, 그래도 그게 어디예요."),
(H, "C'est ça, oui. Mais ce n'est qu'un début. Il faut aussi regarder les autres coûts.", "그래, 맞아. 하지만 시작일 뿐이야. 다른 비용도 봐야 해."),
(C, "Moi, je demanderai un devis à Dubreuil dès aujourd'hui, si vous voulez.", "원하시면 저는 오늘부터 뒤브레유 견적을 요청할게요."),
(H, "Fais-le, Chloé. Demande aussi les prix du poisson et des fruits.", "그렇게 해, 클로에. 생선과 과일 가격도 물어봐."),
(K, "Et la carte, chef ? Les prix vont devoir bouger, non ?", "그럼 메뉴판은요, 셰프? 가격을 조정해야 하지 않나요?"),
(H, "Pas tout de suite. On en reparle au bilan du mois, tous ensemble.", "당장은 아니야. 이달 결산 때 다 같이 다시 얘기하자."),
]

VOCAB = [
("A2", "Livraison / livrer", "납품 / 배달하다", "« Livraison Bastide ! » 하루 일과의 시작. un bon de livraison = 납품서."),
("A2", "Des carottes, des tomates, des courgettes", "당근, 토마토, 애호박", "채소 이름. 가격 단위는 le kilo: « 2,50 € le kilo »."),
("A2", "Un kilo / une cagette", "1킬로 / 과일·채소 상자", "« Les cagettes de tomates. » 시장·납품에서 쓰는 어휘."),
("A2", "Ça fait combien ?", "얼마예요?", "합계·차액을 묻는 가장 일상적인 형태. « Ça fait 114 € de plus. »"),
("A2", "Le prix / cher", "가격 / 비싼", "« Ça fait beaucoup. » = 양이 많다·부담이 크다."),
("A2", "Une commande", "주문", "« Une commande fixe chaque lundi. » 정해진 주문."),
("A2", "Ça m'arrangerait.", "그게 더 편하겠어요.", "arranger = 편의를 주다. 조건법으로 완곡하게. ↔ 정중: Cela me conviendrait."),
("A2", "Je signe ici.", "여기 서명해요.", "bon de livraison 에 서명. 납품 확인."),
("B1", "Augmenter de 12 % / une hausse", "12퍼센트 오르다 / 인상", "augmenter de + 퍼센트(올린 폭). « Le kilo passe de 2,50 à 2,80 €. » 의 passer de A à B 도 함께."),
("B1", "Baisser / une baisse", "내리다 / 인하", "« Baisser ? Jamais ! » 반대말은 augmenter. diminuer 도 같은 뜻."),
("B1", "Tourner autour du pot", "빙빙 돌려 말하다", "[구어] J'vais pas tourner autour du pot. ↔ 정중: Je vais être direct. 본론부터 말할 때."),
("B1", "Un devis", "견적서", "« Il me l'envoie cette semaine. » 가격을 비교하기 위한 서류."),
("B1", "Arrondir", "반올림하다 / 딱 떨어지게 하다", "« J'ai arrondi à 15,25 €. » 소수 단위를 정리."),
("B1", "Charges", "비용(고정비)", "임대료·전기료 같은 고정비. « 23 000 € de charges en plus. »"),
("B2", "Travailler à perte", "손해 보며 일하다", "à perte = 손해를 입으며. « Je peux pas travailler à perte. » 장사하는 사람의 단골 문장."),
("B2", "Un engagement ferme", "확정 약속", "계약·주문에서 뒤집을 수 없는 약속. « prix fermes jusqu'à fin décembre » = 가격 확정."),
("B2", "Un compromis", "타협", "« Un bon compromis, c'est quand tout le monde est mécontent. » 협상 마무리 표현."),
("B2", "Tu m'as bien eu.", "한 방 먹었네.", "[구어] 협상이나 장난에서 상대가 한 수 위일 때. ↔ 정중: Vous avez bien négocié. 웃으며 패배를 인정하는 말."),
("B2", "Ça fait mal au ventre.", "속이 쓰려요.", "[구어] 가격이 아파서 마음이 괴롭다는 과장 표현. ↔ 정중: Cela me coûte beaucoup."),
("C1", "Ça va point.", "안 좋아요 (시골 구어).", "[구어] 시골 억양의 부정 « ne ... point ». 표준: Ça ne va pas du tout. 바스티드의 말투로만 이해."),
("C1", "Sacré(e) + 명사", "대단한 ~", "« Sacrée petite ! » 놀라움·감탄. 감정은 맥락(긍정·부정)에서 결정."),
("C1", "Pardi !", "그렇고말고!", "[구어] 시골·옛 느낌의 맞장구. 현대 표준: Bien sûr ! / Évidemment !"),
]

GRAM = [
("B1", "퍼센트 표현 — augmenter de, passer de A à B, pour cent", "« Douze pour cent de 2,50 €, c'est 30 centimes. » « Le kilo passe de 2,50 à 2,80 €. » « Augmenter de douze pour cent. » de 는 폭, à 는 도달 값."),
("B1", "증감 동사 — augmenter, baisser, monter, diminuer", "« J'augmente mes prix. » « Baisser ? Jamais ! » « Ils ont monté de vingt pour cent. » 가격이 주어면 상승·하락 동사를 직접 쓴다."),
("B2", "조건법 — 완곡한 요청과 가정", "« Vous feriez la même chose à ma place. » « Ça m'arrangerait. » « J'aurais fait pareil. » 협상에서 공격성을 낮추는 도구."),
("B1", "비교급 — plus / moins / aussi, au lieu de", "« Moins augmenter. » « Quatre-vingt-deux au lieu de cent quatorze. » « Un peu moins cher. » 가격 비교에는 au lieu de 도 유용."),
("B1", "원인 표현 — à cause de, parce que, d'abord ... pis ...", "« D'abord, la pluie. Pis, les sacs de grain. Et le gasoil ! » 이유를 나열하는 방식. pis = puis 의 구어."),
("B2", "협상 문형 — proposer, en échange, à condition que", "« En échange, je voudrais une baisse. » « Il y a une condition. » « Je vous donne une commande fixe. » 주고받기를 분명히."),
("A2", "구어 축약 — j'sais, c'te, pis, j'file", "« J'sais pas. » « C'te chaleur. » « Pis, les sacs de grain. » « J'file. » 시골 억양의 구어를 이해하고 표준형으로 복원."),
]

READ = [
("퍼센트 읽기 — douze pour cent", "« douze pour cent » = [duz pur sɑ̃]. douze 의 z 는 pour 앞에서 소리 난다. « neuf pour cent » 의 neuf 는 f 가 [nœf]. « dix pour cent » 의 dix 는 [dis]."),
("소수점 가격 — 2,50 €", "« deux euros cinquante » 처럼 읽는다. « deux virgule cinquante euros » 도 가능하지만 가게에서는 쓰지 않는다. « quatorze euros soixante-dix » = 14,70 €."),
("바스티드의 억양 — 생략 읽기", "« J'vais pas tourner autour du pot. » « Ça m'fait pas plaisir. » 처럼 je, ne, e 를 거의 삼킨다. « c'te chaleur », « pis » 는 느슨하게, 말끝을 길게 끌어도 좋다."),
("리에종 — cent_euros, vingt_ans", "« douze ans » 는 [duzɑ̃]. « cent euros » 의 t 는 읽지 않는다 (cent 앞이 단수라 리에종 없음). « trois cents euros » 처럼 복수 s 가 있을 때만 [z] 로 이어진다."),
("호흡 구간 — 계산 설명", "« Douze pour cent de 2,50 €, / c'est 30 centimes. / Le kilo passe de 2,50 / à 2,80 €. » 숫자 덩어리 사이에서 쉬며 읽어 계산이 선명하게 들리게 한다."),
("억양 — 협상의 단호함과 완곡함", "« Dix pour cent, / et c'est ferme / pour six mois. » 는 끝을 내려 단호하게. « Vous feriez la même chose à ma place. » 는 끝을 부드럽게 올려 공감한다."),
]

CULTURE = [
("납품업자와의 « fidélité » — 20년의 관계", "프랑스 비스트로는 한 납품업자와 오래 거래하며 단골 가격과 신뢰를 쌓는다. 가격 협상은 결례가 아니라 거래의 일부로, 견적(devis) 비교를 솔직하게 알리는 것이 예의다. 이 화에서 Hélène은 Dubreuil과 비교하겠다고 먼저 밝힌다."),
("농산물 가격과 기후·사료·유가", "봄철 비, 사료 가격, 경유 가격은 곧바로 납품가에 반영된다. 시장에서 팔리는 채소는 일 단위로 가격이 변하지만, 식당과는 «prix fermes» 처럼 기간 약속으로 변동을 줄이는 경우가 많다."),
]

META = dict(part=2, ep=18, part_label="제2부 Premières fissures · 여름", title_fr="Les prix flambent", title_ko="치솟는 가격",
 place="Le Comptoir de Marthe, 7월 7일 화요일 오전 7시 45분 (납품 수령, 주방 입구)", chars="Hélène Marchand (42, 주인 셰프) · M. Bastide (채소·고기 납품업자) · Karim Haddad (27, 부주방장) · Chloé Dubois (23, 견습 서버)", wine="납품가 인상(채소 +12%, 고기 +9%, 버터 +8%)과 협상 끝의 일부 양보",
 focus="퍼센트·증감 표현(augmenter de, passer de A à B), 협상 문형, 조건법 완곡 표현", levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제19화 « Une critique assassine » : 7월 9일 목요일, 후기 사이트에 별 2개짜리 혹평이 올라온다")
