# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, K, C = "Hélène", "Julien", "Karim", "Chloé"
D = [
(None, "Lundi 13 juillet, 9 h 15. Le restaurant est fermé. Hélène fait ses comptes dans la salle. Karim arrive, sans sa veste de cuisine, et reste debout près de la porte.", "7월 13일 월요일 오전 9시 15분. 식당은 휴무다. 엘렌이 홀에서 장부를 정리하고 있다. 카림이 조리복 없이 들어와 문 옆에 서 있다."),
(H, "Karim ? On est lundi. Tu n'as pas un jour de repos, toi ?", "카림? 월요일이잖아. 너 쉬는 날 아니야?"),
(K, "Si, mais je voulais te parler. Seul à seule.", "맞는데, 할 말이 있어서요. 둘이서만."),
(H, "Ça a l'air sérieux. Assieds-toi. Un café ?", "심각해 보이네. 앉아. 커피 줄까?"),
(K, "Non, merci. J'ai déjà pris mes deux cafés ce matin.", "아뇨, 괜찮아요. 오늘 아침에 벌써 두 잔 마셨어요."),
(H, "Deux cafés avant dix heures. Alors c'est vraiment grave.", "열 시 전에 커피를 두 잔이나. 그럼 정말 큰일이네."),
(K, "Hélène, j'ai reçu une proposition. Une proposition de travail.", "엘렌, 제안을 하나 받았어요. 일자리 제안이요."),
(H, "Une proposition de qui ?", "누구한테서?"),
(K, "De la Maison Perrault. À Lyon. Un restaurant avec une étoile.", "메종 페로예요. 리옹에 있는, 별 하나짜리 식당이요."),
(H, "Je connais la Maison Perrault. Le chef, c'est Thierry Perrault.", "메종 페로 알아. 셰프가 티에리 페로지."),
(K, "Oui. Il m'a vu à un concours il y a deux ans. Il a gardé mon contact.", "네. 2년 전 대회에서 저를 봤고 연락처를 보관하고 있었대요."),
(H, "Et il te propose quoi, exactement ?", "그래서 정확히 뭘 제안했는데?"),
(K, "Sous-chef. Il cherche quelqu'un à partir de septembre.", "부주방장이요. 9월부터 일할 사람을 찾는대요."),
(H, "Sous-chef. Comme ici.", "부주방장. 여기랑 같네."),
(K, "Oui, mais dans une brigade de douze personnes. Avec une étoile.", "네, 근데 열두 명 규모의 팀이에요. 별도 있고요."),
(H, "Je sais ce que c'est, Karim. J'ai travaillé dans une maison comme ça.", "나도 알아, 카림. 그런 곳에서 일해 봤으니까."),
(K, "C'est justement pour ça que j'ai peur de t'en parler.", "그래서 더 말하기가 겁났어요."),
(H, "Et tu as répondu quoi ?", "그래서 뭐라고 답했어?"),
(K, "J'ai dit que j'allais réfléchir. Mais en fait, j'ai déjà décidé.", "생각해 보겠다고 했어요. 근데 사실 이미 마음은 정했어요."),
(None, "Un silence. Hélène pose son stylo, regarde par la fenêtre, puis revient vers Karim.", "침묵이 흐른다. 엘렌은 펜을 내려놓고 창밖을 보다가 다시 카림을 본다."),
(H, "Tu pars. C'est ça que tu me dis.", "너 가는구나. 지금 그 말을 하는 거네."),
(K, "Oui. Je suis désolé. Je sais que le moment est mauvais.", "네. 죄송해요. 지금이 안 좋은 때라는 거 알아요."),
(H, "Mauvais ? Le loyer monte, le frigo est mort, un client nous détruit sur Internet.", "안 좋은 정도가 아니지. 임대료는 오르고, 냉장고는 죽었고, 손님은 인터넷에서 우릴 깎아내리는데."),
(K, "Je sais. Je ne pars pas à cause de ça, je te le jure.", "알아요. 그것 때문에 가는 게 아니에요, 맹세해요."),
(H, "Alors pourquoi maintenant ?", "그럼 왜 하필 지금이야?"),
(K, "Parce que c'est maintenant qu'on me le propose. Ça n'arrive pas deux fois.", "지금 제안이 왔으니까요. 이런 기회는 두 번 오지 않아요."),
(H, "Je regrette que tu me l'annonces comme ça, un lundi matin.", "월요일 아침에 이렇게 불쑥 말하는 게 서운하다."),
(K, "Je comprends. Mais je préférais te le dire avant l'équipe.", "이해해요. 그래도 팀보다 먼저 말씀드리고 싶었어요."),
(H, "C'est vrai que c'est correct de ta part. Je te remercie.", "그건 네가 예의 바르게 한 거지. 고맙다."),
(K, "Hélène, tu m'as tout appris ici. Je ne veux pas partir fâché.", "엘렌, 여기서 모든 걸 배웠어요. 화난 채로 떠나고 싶지 않아요."),
(H, "Je ne suis pas fâchée. Je suis... déçue, c'est différent.", "화난 건 아니야. 실망한 거야, 다르지."),
(K, "Je préfère que tu sois en colère, honnêtement. C'est moins triste.", "솔직히 화내시는 게 나아요. 덜 슬프니까요."),
(H, "Eh bien, je suis un peu en colère aussi. Tu es content ?", "그럼 조금은 화도 나네. 만족해?"),
(K, "Un peu, oui. Ça veut dire que ça compte.", "조금은요. 그만큼 중요하단 뜻이니까요."),
(H, "Tu pars quand ? Le 1er septembre, c'est ça ?", "언제 가는데? 9월 1일이지?"),
(K, "Je peux finir le 31 juillet. Après, je prends deux semaines pour déménager.", "7월 31일까지 일할 수 있어요. 그 뒤 2주 동안 이사하고요."),
(H, "Dix-huit jours. Il faut que je trouve quelqu'un en dix-huit jours.", "18일. 18일 안에 사람을 구해야 하네."),
(K, "Je peux t'aider. Il y a Sofiane, de mon école. Il cherche un poste.", "도울게요. 제 요리학교 선배 소피안이 있는데 자리를 찾고 있어요."),
(H, "Un ancien de ton école. On verra. Je ne promets rien.", "네 학교 선배라. 보자. 약속은 못 해."),
(H, "Dis-moi une chose. Si je t'avais augmenté, tu serais resté ?", "하나만 말해 줘. 내가 월급을 올려 줬다면 남았을까?"),
(K, "Non. Ce n'est pas une question d'argent. J'ai besoin d'apprendre autre chose.", "아니요. 돈 문제가 아니에요. 다른 걸 배워야 해요."),
(H, "Apprendre quoi ?", "뭘 배운다는 거야?"),
(K, "La rigueur d'une grande brigade. Et à diriger douze personnes, un jour.", "큰 팀의 엄격함이요. 그리고 언젠가 열두 명을 이끄는 법도요."),
(H, "Un jour, tu auras ton propre restaurant.", "언젠가 네 식당을 갖게 될 거야."),
(K, "Peut-être. Mais d'abord, je dois partir pour apprendre.", "어쩌면요. 하지만 먼저 배우러 떠나야 해요."),
(None, "La porte s'ouvre : Julien entre, un sac de croissants à la main, et s'arrête net en voyant leurs visages.", "문이 열리고 줄리앙이 크루아상 봉지를 들고 들어오다가 두 사람의 표정을 보고 멈춘다."),
(J, "Houla. Quelqu'un est mort ? Ou c'est juste le loyer qui monte encore ?", "어이쿠. 누가 죽었어? 아니면 또 임대료 얘기야?"),
(H, "Personne n'est mort. Karim s'en va à Lyon.", "아무도 안 죽었어. 카림이 리옹으로 가."),
(J, "Quoi ? Mais tu es sérieux ? Tu nous quittes ?", "뭐? 진심이야? 우릴 떠나?"),
(K, "Oui, fin juillet. Une étoile, à la Maison Perrault.", "네, 7월 말에요. 메종 페로의 별 하나짜리 식당이에요."),
(J, "Une étoile ! Je suis content pour toi. Et je suis triste pour nous.", "별이라니! 널 위해서는 기뻐. 그리고 우리를 위해서는 슬프고."),
(H, "Voilà, c'est exactement ça.", "그래, 딱 그 마음이야."),
(J, "Je regrette que tu partes, mais je comprends que tu partes.", "네가 떠나는 건 아쉽지만 가는 건 이해해."),
(K, "Merci, Julien. J'avais peur que vous me preniez pour un traître.", "고마워요, 줄리앙. 배신자 취급할까 봐 걱정했거든요."),
(H, "Un traître, jamais. Un cuisinier qui avance, c'est normal.", "배신자라니, 절대. 요리사가 앞으로 나아가는 건 당연한 거야."),
(None, "Mardi 14 juillet, mercredi 15, jeudi 16... les jours passent. Karim forme Moussa à la sauce, prépare des fiches, laisse ses recettes sur le tableau.", "7월 14일 화요일, 15일 수요일, 16일 목요일... 하루하루가 간다. 카림은 무사에게 소스를 가르치고 레시피 카드를 만들고 칠판에 정리해 둔다."),
(None, "Jeudi 30 juillet, 23 h. Dernier service de Karim demain, mais ce soir c'est le dîner d'adieu. Hélène a fermé les rideaux. Une longue table est dressée au milieu de la salle.", "7월 30일 목요일 밤 11시. 카림의 마지막 근무는 내일이지만 오늘 밤은 송별 식사다. 엘렌이 커튼을 닫았다. 홀 한가운데에 긴 테이블이 차려져 있다."),
(C, "Alors, Hélène, qu'est-ce qu'on mange ce soir ? Ça sent incroyable.", "그래서 엘렌, 오늘 밤은 뭘 먹어요? 냄새가 엄청나요."),
(H, "La blanquette de ma mère. Celle que Karim préfère.", "우리 엄마의 블랑케트. 카림이 제일 좋아하는 거."),
(K, "Tu t'en souviens ! Je l'avais dit une seule fois, en avril.", "기억하시네요! 4월에 딱 한 번 말했는데."),
(H, "Je me souviens de tout, Karim. C'est mon problème.", "난 다 기억해, 카림. 그게 내 문제야."),
(J, "Allez, tout le monde s'assoit. Je sers le Brouilly.", "자, 다들 앉아. 브루이 따를게."),
(C, "Je m'assois à côté de Karim. C'est ma dernière occasion de poser des questions.", "저는 카림 옆에 앉을래요. 질문할 마지막 기회니까요."),
(K, "Tu m'as posé deux cents questions en trois mois, Chloé.", "클로에, 석 달 동안 나한테 이백 개는 물었어."),
(C, "Et tu as répondu à toutes. Je suis triste que tu partes.", "그리고 전부 대답해 줬어요. 선배가 떠나서 슬퍼요."),
(J, "Tiens, Chloé, tu viens d'utiliser le subjonctif ! Bravo.", "어, 클로에, 방금 접속법 썼네! 잘했어."),
(C, "Le quoi ? Ah oui, « que tu partes ». C'est le subjonctif ?", "뭐요? 아, « que tu partes » 요. 그게 접속법이에요?"),
(H, "Oui. Après « je suis triste que », « je regrette que », on met le subjonctif.", "응. « je suis triste que », « je regrette que » 뒤에는 접속법을 써."),
(C, "Je note. « Je regrette que tu partes. » C'est joli et triste à la fois.", "적을게요. « Je regrette que tu partes. » 예쁜데 슬프네요."),
(K, "Moi, je ne peux pas dire « je regrette que je parte ». Alors je dis : je suis désolé de partir.", "나는 « je regrette que je parte » 라고는 못 해. 그래서 « je suis désolé de partir » 라고 하지."),
(C, "Pourquoi pas pareil ?", "왜 똑같이 안 써요?"),
(H, "Parce que le sujet est le même. Même personne, on prend l'infinitif.", "주어가 같기 때문이야. 같은 사람이면 부정사를 써."),
(C, "Je comprends. Je suis contente de venir, mais je suis contente que tu viennes.", "알겠어요. 제가 와서 기쁘다는 « de venir », 선배가 와서 기쁘다는 « que tu viennes » 군요."),
(J, "Voilà. Tu es prête pour l'examen.", "그래. 시험 준비 끝났네."),
(C, "Karim, tu as peur ? Moi, j'aurais peur, à ta place.", "카림, 무서워요? 저라면 선배 입장에서 무서울 거예요."),
(K, "Un peu. Une nouvelle ville, une nouvelle équipe. Je ne connais personne.", "조금요. 새 도시, 새 팀. 아는 사람이 아무도 없어요."),
(J, "Tu connais Lyon, au moins ?", "리옹은 알긴 알아?"),
(K, "Je connais la gare et un bouchon lyonnais. C'est tout.", "역이랑 리옹식 선술집 하나는 알아요. 그게 다예요."),
(None, "Hélène sert la blanquette. Pendant quelques minutes, on n'entend que les fourchettes. Puis Julien se lève, verre en main.", "엘렌이 블랑케트를 담는다. 몇 분 동안은 포크 소리만 들린다. 이윽고 줄리앙이 잔을 들고 일어난다."),
(J, "Mesdames, messieurs, un peu de silence. Je serai bref, pour une fois.", "신사 숙녀 여러분, 조용히 해 주세요. 이번만은 짧게 할게요."),
(H, "Toi, bref ? Là, je ne te crois pas.", "네가 짧게? 그건 못 믿겠다."),
(J, "Karim, quand tu es arrivé, tu ne disais pas un mot avant onze heures.", "카림, 네가 처음 왔을 땐 11시 전에는 한마디도 안 했어."),
(K, "C'est toujours vrai. Je parle plus, mais seulement après le café.", "지금도 그래요. 더 말하게 되긴 했지만 커피 마신 다음에만요."),
(J, "Eh bien, tu as appris à nous faire rire, et à faire de la sauce poivre vert.", "그런데 너는 우리를 웃기는 법도, 그린 페퍼 소스 만드는 법도 익혔지."),
(J, "Ça va nous manquer. Tu vas nous manquer. À Karim !", "그게 그리울 거야. 네가 그리울 거야. 카림을 위하여!"),
(C, "À Karim ! Bonne continuation !", "카림을 위하여! 앞길 응원해요!"),
(H, "À Karim. Et à toutes les grandes cuisines où tu travailleras.", "카림을 위하여. 그리고 네가 일하게 될 모든 훌륭한 주방들을 위하여."),
(K, "Merci. Merci à tous. Je n'ai pas préparé de discours.", "고맙습니다. 모두에게 고마워요. 연설은 준비 못 했어요."),
(H, "Tant mieux. Les discours préparés sonnent faux.", "다행이네. 준비한 연설은 가짜 같거든."),
(K, "Alors voilà : ici, j'ai appris le métier. Mais aussi à être patient.", "그럼 이렇게 말할게요. 여기서 일을 배웠어요. 그리고 인내도요."),
(K, "Je n'oublierai jamais le jour où tu m'as dit : « Recommence ».", "« 다시 해 »라고 하셨던 날을 절대 못 잊을 거예요."),
(H, "J'ai dit ça souvent ?", "내가 그 말을 자주 했나?"),
(K, "Trois fois par jour. Et à chaque fois, tu avais raison.", "하루 세 번요. 그리고 매번 맞는 말씀이셨어요."),
(J, "Il faut que je note ça. Hélène avait raison, trois fois par jour.", "적어 둬야겠다. 엘렌이 맞았다, 하루 세 번."),
(H, "Julien, ne pousse pas.", "줄리앙, 선 넘지 마."),
(None, "Chloé sort une carte de son sac. Elle l'a décorée avec des dessins de légumes et des petites phrases en français.", "클로에가 가방에서 카드를 꺼낸다. 채소 그림과 프랑스어 짧은 문장들로 꾸민 카드다."),
(C, "J'ai fait une carte. Tout le monde a signé, même Moussa et M. Lucien.", "카드를 만들었어요. 무사와 뤼시앵 씨까지 모두 서명했어요."),
(K, "Lucien a signé ? Qu'est-ce qu'il a écrit ?", "뤼시앵 씨가 서명하셨어요? 뭐라고 쓰셨죠?"),
(C, "Je lis : « Un bon cuisinier ne reste jamais assis. Reviens nous voir. »", "읽을게요. « 좋은 요리사는 한자리에 앉아 있지 않는다. 꼭 다시 보러 와. »"),
(K, "Ça, c'est du Lucien. Je vais pleurer.", "정말 뤼시앵 씨다운 말이네요. 눈물 날 것 같아요."),
(J, "Pleure, pleure. Tu seras dans une brigade de douze, plus personne ne te dira ça.", "울어, 울어. 열두 명 팀에 가면 아무도 그런 말 안 해 줄 테니까."),
(H, "Karim, j'ai quelque chose pour toi aussi.", "카림, 나도 너한테 줄 게 있어."),
(None, "Elle lui tend un petit paquet enveloppé dans un torchon. À l'intérieur, un vieux couteau d'office au manche usé.", "그녀가 행주에 싼 작은 꾸러미를 내민다. 안에는 손잡이가 닳은 오래된 과도가 들어 있다."),
(K, "Ce n'est pas... Hélène, ce n'est pas ton couteau de stage ?", "이거... 엘렌, 이거 설마 연수 때 쓰던 칼이에요?"),
(H, "Si. Il m'a suivie dans six cuisines. Je veux qu'il continue à voyager.", "맞아. 여섯 군데 주방을 같이 다녔어. 이 칼이 계속 여행했으면 해."),
(K, "Je ne peux pas accepter. Il est trop précieux.", "받을 수 없어요. 너무 소중한 거예요."),
(H, "Tu peux, et tu dois. Il faut que quelqu'un s'en serve.", "받을 수 있고, 받아야 해. 누군가는 써야 하니까."),
(K, "Je... merci. Je ne sais pas quoi dire.", "저... 고마워요. 무슨 말을 해야 할지 모르겠어요."),
(C, "Dis « merci, Hélène », c'est déjà beaucoup.", "« 고마워요, 엘렌 » 이라고만 해도 충분해요."),
(K, "Merci, Hélène. Pour tout. Pour la confiance aussi.", "고마워요, 엘렌. 모든 것에요. 믿어 주신 것까지."),
(H, "Je regrette que tu partes. Mais je suis fière que tu partes.", "네가 가는 건 아쉽지만, 네가 가는 게 자랑스러워."),
(K, "Les deux en même temps, ça existe ?", "둘이 동시에 가능해요?"),
(H, "Tous les parents le savent. Et tous les patrons aussi.", "모든 부모가 알아. 모든 사장도 그렇고."),
(J, "Bon, avant qu'on pleure tous dans la blanquette, on fait un dernier toast.", "블랑케트에 다 같이 울음을 떨구기 전에 마지막 건배 하자."),
(C, "Pour dire au revoir, on dit quoi ? « Adieu » ?", "작별 인사로는 뭐라고 해요? « Adieu » 인가요?"),
(J, "Surtout pas ! « Adieu », c'est pour toujours. Karim ne meurt pas.", "절대 아니야! « Adieu » 는 영영 안 볼 때 쓰는 말이야. 카림이 죽는 건 아니잖아."),
(H, "On dit « à bientôt », « à la prochaine », ou « bonne route ».", "« à bientôt », « à la prochaine », 아니면 « bonne route » 라고 해."),
(K, "Et « on reste en contact », ça marche toujours.", "그리고 « on reste en contact » 는 언제나 통하죠."),
(C, "« On reste en contact ». « Prends soin de toi. » Je note tout.", "« On reste en contact ». « Prends soin de toi ». 다 적을게요."),
(J, "Ajoute « ne te perds pas dans Lyon ». C'est une grande ville.", "« 리옹에서 길 잃지 마 » 도 추가해. 큰 도시거든."),
(K, "Je ne me perdrai pas. Le chemin de la gare, je le connais.", "안 잃을 거예요. 역으로 가는 길은 아니까요."),
(None, "Minuit passé. Les assiettes sont vides. Karim se lève et fait le tour de la table, serre chacun dans ses bras.", "자정이 지났다. 접시가 비었다. 카림이 일어나 테이블을 돌며 한 사람씩 안아 준다."),
(K, "Moussa dort déjà dans son coin. Dites-lui bonne chance demain.", "무사는 벌써 구석에서 자고 있네요. 내일 행운을 빈다고 전해 주세요."),
(H, "On lui dira. Demain, tu fais le service normal, n'est-ce pas ?", "전할게. 내일은 평소처럼 서비스하는 거지?"),
(K, "Évidemment. Jusqu'à la dernière assiette.", "당연하죠. 마지막 접시까지요."),
(H, "Alors rentre dormir. Il faut que tu sois en forme.", "그럼 들어가서 자. 컨디션 좋아야 하니까."),
(K, "Bonne nuit à tous. Et merci encore pour ce dîner.", "다들 안녕히 주무세요. 오늘 식사 다시 한번 고마워요."),
(J, "Bonne nuit, chef. Dors bien, tu as une grosse journée.", "잘 자, 셰프. 푹 자, 내일 큰 날이잖아."),
(H, "À demain, Karim. Et ne regrette rien.", "내일 보자, 카림. 그리고 아무것도 후회하지 마."),
]

VOCAB = [
("A2", "Tu vas nous manquer.", "네가 우리에게 그리울 거야.", "manquer 구문에서 주어는 그리운 사람. « Tu vas nous manquer. » = 우리가 너를 그리워할 거야."),
("A2", "À bientôt / à la prochaine", "곧 봐요 / 다음에 봐요", "작별 인사. « Adieu » 는 영영 이별일 때 쓰므로 일상에서 피한다."),
("A2", "Bonne continuation !", "앞날에 행운을!", "새 출발하는 사람에게 건네는 정중한 작별 인사. ↔ 구어: Bonne chance !"),
("A2", "Bonne route !", "잘 가요!", "여행·이사 가는 사람에게. « Bonne route, Karim. »"),
("A2", "Un dîner d'adieu", "송별 저녁 식사", "« C'est le dîner d'adieu. » adieu 는 이 구문에서는 명사."),
("A2", "Prends soin de toi.", "몸 잘 챙겨.", "tu 로 말하는 사람에게. vous 는 « Prenez soin de vous ». 작별 때 흔히 한다."),
("A2", "On reste en contact.", "연락하고 지내자.", "[구어] ↔ 정중: Nous resterons en relation."),
("A2", "Pleurer", "울다", "« Je vais pleurer. » 눈물을 흘리다. 감동·슬픔 모두에 쓴다."),
("B1", "Une proposition de travail", "일자리 제안", "« J'ai reçu une proposition. » 직장·계약 제안은 offre 보다 구어에서 proposition 이 자연스럽다."),
("B1", "Je regrette que + 접속법", "~라서 아쉽다", "« Je regrette que tu partes. » regretter que 뒤에는 접속법. 주어가 같으면 de + 부정사: « Je regrette de partir. »"),
("B1", "Je suis content(e) que + 접속법", "~라서 기쁘다", "« Je suis content que tu viennes. » 감정 동사 뒤 접속법. 주어가 같으면 « Je suis content de venir. »"),
("B1", "Il faut que + 접속법", "~해야 한다", "« Il faut que je trouve quelqu'un. » 가장 자주 쓰는 접속법 구문."),
("B1", "Je ne pars pas à cause de ça.", "그것 때문에 가는 게 아니에요.", "à cause de + 명사 / ça. 원인을 부정할 때. 긍정이면 grâce à (덕분에)."),
("B1", "Prendre quelqu'un pour un traître", "누군가를 배신자 취급하다", "« Vous me preniez pour un traître. » prendre A pour B = A를 B로 여기다. 접속법 « que vous me preniez »."),
("B1", "Houla !", "어이쿠!", "[구어] 놀람·난감함. ↔ 정중: Oh, mon Dieu."),
("B2", "Seul à seul", "단둘이", "« Je voulais te parler seul à seul. » 둘만의 대화. 관용: en tête-à-tête."),
("B2", "Une brigade (de cuisine)", "주방 팀", "주방 직원 조직. brigade de douze = 열두 명 규모. chef, sous-chef, commis 등으로 구성."),
("B2", "Ne pas pousser", "선을 넘지 않다", "[구어] « Julien, ne pousse pas. » = 너무 나가지 마. ↔ 정중: N'exagère pas."),
("B2", "Tant mieux !", "다행이네!", "상황이 좋은 쪽일 때. 반대는 tant pis (어쩔 수 없지)."),
("C1", "Sonner faux", "가식 같다, 어색하다", "« Les discours préparés sonnent faux. » 음이 틀리다 → 말이 진심같지 않다."),
("C1", "Un couteau d'office", "과도", "껍질 깎기·세밀 작업용 작은 칼. 요리사의 개인 칼은 보통 손에 익고 감정이 담긴다."),
]

GRAM = [
("B1", "접속법 현재 — je regrette que tu partes", "« Je regrette que tu partes. » « Je suis triste que tu partes. » « Je suis contente que tu viennes. » 감정(후회·슬픔·기쁨) 뒤 que 절은 접속법. 형태: ils 현재형 어간 + -e, -es, -e, -ions, -iez, -ent (partir → parte). 불규칙 être→sois, avoir→aie, aller→aille, faire→fasse."),
("B1", "주어가 같으면 de + 부정사", "« Je suis désolé de partir. » « Je suis contente de venir. » 주어가 같으면 접속법이 아니라 de + 부정사: × Je regrette que je parte → ○ Je regrette de partir. 주어가 다르면 que + 접속법."),
("B1", "il faut que + 접속법 — 필요", "« Il faut que je trouve quelqu'un. » « Il faut que tu sois en forme. » « Il faut que quelqu'un s'en serve. » 필요·의무는 il faut que 로. 부정사: Il faut trouver quelqu'un (주어 일반)."),
("B2", "시간 표현으로 점프하기", "« Mardi 14 juillet, mercredi 15... » « Jeudi 30 juillet, 23 h. » 지문에서 날짜·요일·시각을 쓸 때 요일 + 날짜 + 월 순. « Demain », « dans dix-huit jours », « fin juillet »."),
("B2", "vouloir/préférer que + 접속법 — 바람", "« Je préfère que tu sois en colère. » « Je veux qu'il continue à voyager. » vouloir que, préférer que 뒤에도 접속법. « Je voulais te le dire avant l'équipe »."),
("B2", "감정 표현 — déçu, fier, triste, content", "« Je suis déçue. » « Je suis fière que tu partes. » « Je suis triste pour nous. » 감정 형용사 + de/que/pour. 두 감정이 공존할 땐 « Les deux en même temps »."),
("C1", "명령형 + 대명사 — fais-le, dis-lui", "« Dites-lui bonne chance demain. » « Dis merci, Hélène. » 긍정 명령은 동사-대명사 하이픈 순서(dis-le, dis-lui). 부정은 « Ne lui dis pas ». 접속법의 il faut que 와 번갈아 연습할 것."),
]

READ = [
("접속법 낭독 — que tu partes / que tu viennes", "« Je regrette / que tu partes. » 는 que 앞에서 짧게 쉬고 partes 에서 목소리가 가라앉는다. « Je suis contente / que tu viennes. » 는 viennes 를 밝게. 감정 동사 뒤 쉼이 접속법 리듬이다."),
("리에종 — tu_as / vous_avez / ils_ont", "« Tu as tout appris. » 의 tu_as 는 /ty.a/ 로 이어 읽는다. « Vous avez signé ? » 는 /vu.za.ve.si.ɲe/. 이어 읽는 s·z 소리를 놓치지 말 것."),
("r — regretter / partir / Perrault", "« regretter » 의 두 r 은 목 뒤에서 가볍게 긁는다. « Maison Perrault » 의 Perrault 는 /pe.ʁo/ 로 t 가 소리 나지 않는다. 지명·인명은 철자를 보고 읽기보다 소리를 외워 둔다."),
("억양 — 감정이 흔들리는 대사", "« Tu pars. C'est ça que tu me dis. » 는 첫 문장은 하강, 둘째 문장은 낮게 천천히. « Je regrette que tu partes. Mais je suis fière que tu partes. » 는 두 번째 문장을 부드럽게 올렸다 내린다."),
("호흡 구간 — 건배사", "« Ça va nous manquer. / Tu vas nous manquer. / À Karim ! » 세 구간. « Bonne continuation ! » 은 /bɔn.kɔ̃.ti.nɥa.sjɔ̃/ 로 비음을 분명히 한다."),
("비음 — Lyon / continuation / bonne nuit", "« Lyon » 은 /ljɔ̃/. « continuation » 의 on 은 /ɔ̃/, an 은 /ɑ̃/ 로 구별. « Bonne nuit » 의 bonne 은 비음이 아니라 /bɔn/. 비음과 비비음의 차이를 의식한다."),
("작별 인사 억양", "« À bientôt ! » 는 끝을 올려 가볍게. « Adieu » 와 « Au revoir » 의 무게 차이가 억양에도 나온다. « Ne regrette rien. » 은 낮고 느리게, 엘렌의 단호한 애정을 담아 읽는다."),
]

CULTURE = [
("프랑스 주방의 이직 문화 — brigade 과 étoile", "프랑스 요리계는 별(étoile)이 붙은 식당에서 경력을 쌓고 떠나는 것을 자연스럽게 여긴다. 부주방장이 더 큰 brigade 로 옮기는 것은 배신이 아니라 성장으로 본다. 주인은 서운함을 숨기지 않되 떠나는 사람의 앞날을 축복하는 것이 예의다."),
("Adieu 와 au revoir — 작별 인사의 온도", "« Adieu » 는 본래 « à Dieu (신께 맡긴다) » 에서 온 말로, 다시 못 볼 때 쓰는 무거운 작별이다. 일상에서는 « à bientôt », « à la prochaine », « bonne continuation », « prends soin de toi » 를 쓴다. 이사·이직하는 동료에게는 « on reste en contact » 가 가장 흔한 마무리다."),
]

META = dict(part=2, ep=20, part_label="제2부 Premières fissures · 여름", title_fr="Le départ de Karim", title_ko="카림의 이직",
 place="Le Comptoir de Marthe, 7월 13일 월요일 오전 9시 15분 / 7월 30일 목요일 밤 11시 ~ 자정 넘어",
 chars="Hélène Marchand (주인 셰프) · Karim Haddad (부주방장) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버)",
 wine="리옹의 미슐랭 1스타 «Maison Perrault» 제안, 7월 13일 통보에서 30일 송별 식사까지.",
 focus="접속법 입문(regretter que, être content que, il faut que), 작별 표현, 감정 표현",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제21화 « Moins de couverts » : 송별 전, 7월 20일 월요일 오전. 텅 빈 홀과 매출 분석 회의(카림도 아직 근무 중).")
