# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, R = "Hélène", "Julien", "Chloé", "M. Roussel"
D = [
(None, "Mardi 28 juillet, 13 h 20. Le service de midi est calme. Un homme d'une cinquantaine d'années entre, un papier à la main. Il ne sourit pas.", "7월 28일 화요일 오후 1시 20분. 점심 영업은 한산하다. 쉰 살쯤 된 남자가 종이 한 장을 손에 들고 들어온다. 웃지 않는다."),
(C, "Bonjour monsieur. Vous avez réservé ?", "안녕하세요, 손님. 예약하셨나요?"),
(R, "Non. Je ne viens pas pour déjeuner. Je voudrais parler au responsable.", "아니요. 점심 먹으러 온 게 아닙니다. 책임자와 이야기하고 싶습니다."),
(C, "Bien sûr. Je vais chercher notre responsable de salle. Un instant.", "물론입니다. 홀 매니저를 불러 오겠습니다. 잠시만요."),
(C, "Julien, un monsieur te demande. Il a l'air fâché.", "쥘리앵, 어떤 손님이 찾으세요. 화나 보여요."),
(J, "D'accord. Reste près de moi, tu vas voir comment on fait.", "알았어. 내 옆에 있어. 어떻게 하는지 보게 될 거야."),
(J, "Bonjour monsieur. Julien Benali, je suis le responsable de salle. Je vous écoute.", "안녕하세요, 손님. 홀 매니저 쥘리앵 브날리입니다. 말씀하세요."),
(R, "Samedi soir, nous avons dîné chez vous, ma femme et moi.", "토요일 저녁에 아내와 제가 여기서 식사했습니다."),
(R, "Le lendemain, ma femme a été très malade. Vomissements, fièvre, toute la nuit.", "다음 날 아내가 많이 아팠습니다. 구토에 열, 밤새도록요."),
(J, "Je suis vraiment désolé de l'apprendre. Comment va-t-elle aujourd'hui ?", "그 말씀을 들으니 정말 죄송합니다. 부인께서는 오늘 어떠십니까?"),
(R, "Mieux, mais elle est restée deux jours au lit. Le médecin parle d'une intoxication alimentaire.", "나아졌지만 이틀 동안 누워 있었습니다. 의사는 식중독이라고 하더군요."),
(R, "Elle a mangé un œuf mayonnaise chez vous. Moi, j'ai pris la terrine.", "아내는 여기서 달걀 마요네즈를 먹었어요. 저는 테린을 먹었고요."),
(J, "Je comprends votre inquiétude. Voulez-vous vous asseoir un instant ?", "걱정되시는 마음 이해합니다. 잠시 앉으시겠어요?"),
(R, "Non, merci. Je préfère rester debout. Je veux des explications.", "아니요, 괜찮습니다. 서 있겠습니다. 설명을 듣고 싶습니다."),
(J, "Bien sûr. Je vais chercher la cheffe. C'est elle qui pourra vous répondre.", "물론입니다. 셰프를 모시고 오겠습니다. 그분이 답해 드릴 수 있습니다."),
(None, "Julien passe en cuisine. Hélène essuie ses mains, le visage fermé.", "쥘리앵이 주방으로 간다. 엘렌이 손을 닦는데 표정이 굳어 있다."),
(J, "Hélène, un client dit que sa femme a été malade après samedi soir.", "엘렌, 손님이 토요일 저녁 이후 부인이 아팠다고 해요."),
(H, "Malade comment ? Elle a mangé quoi ?", "어떻게 아팠대? 뭘 먹었고?"),
(J, "Un œuf mayonnaise. Il parle d'intoxication alimentaire et il est très énervé.", "달걀 마요네즈래요. 식중독이라는 말을 하고 있고 아주 화가 나 있어요."),
(H, "Mon œuf mayonnaise ? Mais on en a vendu quinze samedi...", "내 달걀 마요네즈? 토요일에 열다섯 개나 팔았는데..."),
(J, "Je sais. Mais pour l'instant, on l'écoute, on ne se défend pas.", "알아요. 하지만 지금은 일단 듣는 거예요, 변명하는 게 아니라."),
(H, "Tu as raison. Je viens. Chloé, reste en salle.", "맞아. 갈게. 클로에는 홀에 있어."),
(C, "D'accord. Mais je peux regarder, pour apprendre ?", "알겠어요. 그래도 배우려고 지켜봐도 돼요?"),
(J, "De loin, oui. Et sans rien dire, d'accord ?", "멀리서라면 돼. 그리고 아무 말도 하지 말고, 알겠지?"),
(H, "Bonjour monsieur. Hélène Marchand, la cheffe. Mon collègue m'a tout expliqué.", "안녕하세요. 셰프 엘렌 마르샹입니다. 동료에게 모두 들었습니다."),
(R, "Madame, ma femme a failli aller à l'hôpital. Vous vous rendez compte ?", "셰프님, 제 아내는 하마터면 병원에 갈 뻔했습니다. 아시겠어요?"),
(H, "Je suis sincèrement désolée. Quel jour, exactement, a-t-elle été malade ?", "진심으로 죄송합니다. 정확히 언제부터 아프셨습니까?"),
(R, "Dimanche, vers trois heures du matin. Donc dix heures après le dîner.", "일요일 새벽 세 시쯤입니다. 그러니까 저녁 식사 열 시간 뒤요."),
(H, "Et vous, monsieur, vous n'avez rien eu ?", "그럼 손님은 괜찮으셨나요? 아무 증상이 없으셨습니까?"),
(R, "Non, rien. Mais ça ne prouve rien. Je n'avais pas pris d'œuf.", "네, 아무 증상 없었습니다. 하지만 그게 아무것도 증명하진 않죠. 저는 달걀을 안 먹었으니까요."),
(H, "Je comprends. Vous avez vu un médecin ?", "이해합니다. 병원에서 진료는 받으셨나요?"),
(R, "Oui, dimanche après-midi. Voici le certificat médical.", "네, 일요일 오후에요. 여기 진단서입니다."),
(H, "Puis-je le lire ? Je ne le garde pas, je regarde seulement.", "읽어 봐도 될까요? 가져가진 않고 보기만 하겠습니다."),
(R, "Bien sûr. Il dit « gastro-entérite, probablement d'origine alimentaire ». « Probablement ».", "물론이죠. « 급성 위장염, 식품 유래 가능성 높음 » 이라고 적혀 있습니다. « 가능성 » 이요."),
(H, "Oui, le médecin dit « probablement ». Il ne peut pas être certain.", "네, 의사 선생님도 « 가능성 » 이라고 하셨네요. 확신할 수는 없는 거죠."),
(R, "Vous essayez de dire que ce n'est pas chez vous ?", "그러니까 여기서 생긴 게 아니라는 말씀을 하시려는 겁니까?"),
(H, "Non, monsieur. Je dis seulement que je veux comprendre avant de répondre.", "아닙니다. 답하기 전에 먼저 이해하고 싶다는 뜻입니다."),
(R, "Comprendre quoi ? Elle a mangé chez vous, elle a été malade. C'est simple.", "뭘 이해해요? 여기서 먹었고 아팠습니다. 간단하잖아요."),
(H, "Je vous entends. Votre inquiétude est légitime, et je la prends au sérieux.", "말씀 듣고 있습니다. 걱정하시는 게 당연하고, 저는 진지하게 받아들입니다."),
(J, "Madame Roussel avait réservé samedi à vingt heures, c'est bien ça ?", "루셀 부인은 토요일 여덟 시에 예약하셨죠, 맞나요?"),
(R, "Oui, table douze, près de la fenêtre. Nous sommes clients depuis deux ans.", "네, 12번 테이블, 창가요. 우리는 이 년 전부터 단골입니다."),
(H, "Depuis deux ans... Alors vous savez que ça n'est jamais arrivé ici.", "이 년이면... 이런 일이 여기서 한 번도 없었다는 걸 아시겠네요."),
(R, "Justement, c'est pour ça que je suis si surpris. Et déçu.", "그래서 더 놀랍고, 실망했습니다."),
(H, "Je comprends. Je vais être honnête avec vous. Samedi, nous avons servi quinze œufs mayonnaise.", "이해합니다. 솔직하게 말씀드릴게요. 토요일에 달걀 마요네즈를 열다섯 개 냈습니다."),
(H, "Personne d'autre ne s'est plaint. Mais cela ne veut pas dire que vous avez tort.", "다른 분은 불편을 말씀하지 않으셨어요. 하지만 그렇다고 손님이 틀렸다는 뜻은 아닙니다."),
(R, "Alors vous admettez que votre mayonnaise est peut-être en cause ?", "그럼 마요네즈가 원인일 수도 있다는 걸 인정하시는 겁니까?"),
(H, "Je n'admets rien, et je ne nie rien. Je dis que je vais vérifier.", "인정도 부인도 하지 않습니다. 확인해 보겠다는 말씀입니다."),
(R, "Vérifier quoi ? Vous allez vous contrôler vous-même ?", "뭘 확인해요? 스스로 점검하시겠다고요?"),
(H, "Mes œufs viennent d'un fournisseur de confiance, et je garde les bons de livraison.", "달걀은 믿을 수 있는 납품업자에게서 오고, 납품서도 보관합니다."),
(H, "Et mes relevés de température du frigo sont notés chaque matin.", "냉장고 온도 기록도 매일 아침 적어 둡니다."),
(R, "Écoutez, je ne suis pas ici pour une leçon. Je veux un remboursement.", "저는 설명을 들으러 온 게 아닙니다. 환불을 원합니다."),
(H, "Combien avez-vous payé, samedi ?", "토요일에 얼마를 내셨나요?"),
(R, "Cent dix-huit euros. Et je veux aussi une compensation pour le préjudice.", "118유로입니다. 그리고 피해에 대한 보상도 원합니다."),
(J, "Monsieur, pourriez-vous préciser ce que vous appelez « préjudice » ?", "손님, « 피해 » 라고 하신 게 구체적으로 무엇인지 말씀해 주시겠어요?"),
(R, "Ma femme a perdu deux jours de travail. Elle est infirmière libérale.", "아내가 이틀 동안 일을 못 했습니다. 개인 간호사로 일하거든요."),
(H, "Je vois. Je suis désolée pour elle, vraiment.", "그렇군요. 부인께 정말 죄송합니다."),
(R, "Je me réserve le droit de demander réparation, si vous refusez de coopérer.", "협조를 거부하시면 손해배상을 청구할 권리를 유보하겠습니다."),
(H, "Je ne refuse pas de coopérer, monsieur. Je vous propose quelque chose.", "협조를 거부하는 게 아닙니다. 제안을 하나 드리겠습니다."),
(H, "Je vous rembourse le dîner de samedi en totalité, cent dix-huit euros.", "토요일 저녁 식사 값 118유로를 전액 환불해 드리겠습니다."),
(H, "C'est un geste commercial. Cela ne veut pas dire que je reconnais une faute.", "영업상의 호의입니다. 제가 잘못을 인정한다는 뜻은 아닙니다."),
(R, "Un geste commercial... Et pour le reste ? Le jour de travail perdu ?", "영업상의 호의라... 그럼 나머지는요? 못 한 근무일은요?"),
(H, "Pour cela, il faudrait des preuves plus précises. Je ne peux pas vous promettre davantage.", "그 부분은 더 정확한 증거가 필요합니다. 그 이상은 약속드릴 수 없습니다."),
(R, "Vous avez une assurance, j'imagine ? Une assurance responsabilité civile ?", "보험은 들어 두셨겠죠? 배상책임보험요?"),
(H, "Oui, nous sommes assurés. Si vous le souhaitez, je vous donne les coordonnées de l'assureur.", "네, 보험에 가입돼 있습니다. 원하시면 보험사 연락처를 드리겠습니다."),
(R, "Je vais y réfléchir. Je ne dis pas non, mais je ne dis pas oui.", "생각해 보겠습니다. 안 한다는 건 아니지만 한다고도 안 했습니다."),
(H, "C'est votre droit. Julien, tu peux préparer un reçu de remboursement ?", "손님의 권리입니다. 쥘리앵, 환불 영수증 준비해 줄래?"),
(J, "Oui. Monsieur, je note votre nom et votre adresse sur le reçu. Votre carte, c'était laquelle ?", "네. 손님, 영수증에 성함과 주소를 적겠습니다. 카드는 어느 걸 쓰셨죠?"),
(R, "Une Visa. Je l'ai avec moi, mais le ticket est à la maison.", "비자 카드요. 지금 가지고 있는데 영수증은 집에 있습니다."),
(J, "Ce n'est pas grave. Je retrouve la transaction avec la date et l'heure.", "괜찮습니다. 날짜와 시간으로 결제 내역을 찾을 수 있습니다."),
(None, "Julien va à la caisse. Chloé le suit des yeux, sans bouger.", "쥘리앵이 계산대로 간다. 클로에는 움직이지 않고 눈으로 그를 따라간다."),
(R, "Madame, est-ce que vous cuisinez vous-même la mayonnaise ?", "셰프님, 마요네즈는 직접 만드십니까?"),
(H, "Oui, tous les matins, avec des œufs frais et de l'huile de tournesol.", "네, 매일 아침 신선한 달걀과 해바라기유로 만듭니다."),
(R, "Et vous ne pensez pas qu'il faudrait utiliser des œufs pasteurisés ?", "살균 달걀을 쓰는 게 좋다고 생각하지 않으십니까?"),
(H, "Vous posez une bonne question. Je vais y réfléchir sérieusement.", "좋은 질문이십니다. 진지하게 생각해 보겠습니다."),
(R, "Je ne veux pas que ça arrive à quelqu'un d'autre, vous comprenez ?", "다른 사람에게도 이런 일이 생기는 건 원치 않습니다. 이해하시죠?"),
(H, "Je comprends parfaitement, et je vous remercie de me le dire en face.", "충분히 이해하고, 면전에서 말씀해 주셔서 감사합니다."),
(R, "Beaucoup de gens écrivent sur Internet sans venir. Moi, je préfère parler.", "많은 사람은 오지도 않고 인터넷에 글을 씁니다. 저는 직접 말하는 쪽이 낫습니다."),
(J, "Voilà, monsieur. Le remboursement de cent dix-huit euros est fait sur votre carte.", "자, 손님. 118유로가 카드로 환불 처리되었습니다."),
(J, "Vous le verrez sous trois à cinq jours ouvrés. Voici votre reçu signé.", "영업일 기준 3~5일 안에 확인하실 수 있습니다. 서명된 영수증입니다."),
(R, "Merci. Pour être honnête, je pensais que vous alliez me traiter de menteur.", "솔직히 거짓말쟁이 취급을 하실 줄 알았습니다."),
(H, "Pourquoi je ferais ça ? Vous n'avez aucune raison de mentir.", "제가 왜 그러겠습니까? 거짓말하실 이유가 없으시잖아요."),
(R, "Certains clients essayent de profiter de la situation, vous savez.", "상황을 이용하려는 손님도 있잖습니까."),
(H, "Peut-être. Mais je préfère croire les gens, jusqu'à preuve du contraire.", "그럴 수도요. 하지만 반대 증거가 나올 때까지는 사람을 믿는 쪽을 택합니다."),
(R, "Bon. Je vais voir comment va ma femme et je reviendrai vers vous.", "그럼 아내 상태를 보고 다시 연락드리겠습니다."),
(H, "Très bien. Et si vous voulez, offrez-lui une invitation pour deux, quand elle ira mieux.", "좋습니다. 원하시면 부인이 나아지신 뒤에 두 분을 초대하겠습니다."),
(R, "Je ne sais pas si elle voudra revenir. Je lui poserai la question.", "아내가 다시 오고 싶어 할지 모르겠습니다. 물어보겠습니다."),
(H, "Bien sûr. L'invitation reste valable jusqu'à la fin de l'année.", "물론입니다. 초대장은 올해 말까지 유효합니다."),
(R, "Au revoir. Merci de m'avoir écouté.", "안녕히 계세요. 들어 주셔서 감사합니다."),
(H, "Au revoir, monsieur. Prenez soin de votre épouse.", "안녕히 가세요. 부인 잘 보살펴 드리세요."),
(None, "La porte se ferme. Hélène reste immobile un moment, puis s'appuie sur le comptoir.", "문이 닫힌다. 엘렌은 잠시 가만히 서 있다가 카운터에 몸을 기댄다."),
(H, "Ouf... Je suis épuisée. Vingt ans que je cuisine, ça ne m'est jamais arrivé.", "휴... 지쳤어. 요리한 지 20년인데 이런 일은 처음이야."),
(J, "Tu as très bien géré. Calme, polie, et tu ne t'es pas énervée.", "아주 잘 처리했어요. 침착하고 정중했고, 화내지도 않았어요."),
(H, "Je n'étais pas calme dedans. J'avais mal au ventre, moi aussi.", "속은 안 침착했어. 나도 배가 아팠어."),
(C, "Je peux te poser une question ? Tu as vraiment tout remboursé sans prouver qui avait tort ?", "질문 하나 해도 돼요? 누가 잘못했는지 증명도 안 했는데 전부 환불해 줬어요?"),
(J, "Oui. Parce qu'un client fâché qui revient vaut mieux qu'un procès perdu.", "응. 화난 손님이 다시 오는 게 소송에서 지는 것보다 낫거든."),
(H, "Pas de procès, Julien. Ne dis pas ça. On n'en est pas là.", "소송 얘기는 하지 마, 쥘리앵. 거기까진 가지 않았어."),
(J, "Pardon. Je voulais dire : mieux vaut un client calmé qu'un client furieux.", "미안해요. 화난 손님보다 마음이 풀린 손님이 낫다는 뜻이었어요."),
(C, "C'est quoi la différence entre « un remboursement » et « un geste commercial » ?", "« remboursement » 과 « geste commercial » 은 뭐가 달라요?"),
(J, "Un remboursement, on rend l'argent parce qu'il y a un problème prouvé.", "remboursement 은 문제가 입증돼서 돈을 돌려주는 거야."),
(J, "Un geste commercial, c'est un cadeau du commerçant, sans reconnaître de faute.", "geste commercial 은 가게가 잘못을 인정하지 않고 주는 호의야."),
(C, "Ah, d'accord. Donc Hélène a dit les deux en même temps.", "아, 알겠어요. 그럼 엘렌은 둘을 동시에 말한 거네요."),
(H, "Plus ou moins. Dans la tête du client, c'est un remboursement. Dans la mienne, un geste.", "얼추 그래. 손님 입장에선 환불이고 내 입장에선 호의야."),
(J, "Et tu as bien fait de noter « sans reconnaissance de faute » sur le reçu.", "그리고 영수증에 « 과실 인정 아님 » 이라고 적은 건 잘한 거예요."),
(H, "Ça, c'est un réflexe de ma mère. Elle disait : « Un papier protège toujours. »", "그건 우리 엄마 버릇이야. 엄마는 « 종이 한 장이 늘 지켜 준다 » 고 했어."),
(J, "Qu'est-ce que tu vas faire pour les œufs ?", "달걀은 어떻게 할 거예요?"),
(H, "Je vais regarder mes relevés de température, ceux de samedi, et appeler M. Bastide.", "토요일 온도 기록을 확인하고 바스티드 씨에게 전화해 볼게."),
(H, "Et je vais réfléchir aux œufs pasteurisés pour la mayonnaise.", "그리고 마요네즈에 살균 달걀을 쓰는 것도 생각해 볼 거야."),
(J, "Ça te coûterait plus cher, non ?", "비용이 더 들지 않을까요?"),
(H, "Un peu. Mais c'est moins cher que de perdre un client, ou deux.", "조금은. 그래도 손님을 한두 명 잃는 것보다는 싸."),
(C, "Moi, samedi, j'ai servi la table douze. Je me souviens de madame Roussel.", "저 토요일에 12번 테이블 서빙했어요. 루셀 부인이 기억나요."),
(H, "Ah oui ? Raconte. Elle avait l'air comment ?", "그래? 말해 봐. 어땠어?"),
(C, "Fatiguée. Elle a dit en arrivant qu'elle avait mal à la tête depuis le matin.", "피곤해 보였어요. 도착하자마자 아침부터 머리가 아프다고 했어요."),
(H, "Quoi ? Tu es sûre ? Pourquoi tu ne l'as pas dit tout à l'heure ?", "뭐? 확실해? 아까는 왜 말 안 했어?"),
(C, "Parce que Julien m'a dit de ne rien dire. Et je n'étais pas sûre que c'était important.", "쥘리앵이 아무 말도 하지 말라고 했거든요. 그리고 중요한지 확신이 없었고요."),
(J, "C'était important, Chloé. Mais je t'avais demandé de te taire, donc c'est ma faute.", "중요한 거였어, 클로에. 하지만 내가 입을 다물라고 했으니 내 잘못이야."),
(H, "Ce n'est pas une preuve, mais c'est un détail utile. Écris-le sur un papier, avec la date.", "증거는 아니지만 쓸모 있는 정보야. 날짜와 함께 종이에 적어 둬."),
(C, "Tout de suite. J'écris : « samedi 25, table douze, madame fatiguée à l'arrivée ».", "바로 할게요. « 25일 토요일, 12번 테이블, 부인이 도착 때부터 피곤해 보임 » 이렇게요."),
(H, "Parfait. Et on garde ça dans le classeur, avec le reçu et les bons de livraison.", "좋아. 그리고 그걸 영수증, 납품서랑 같이 서류철에 넣어 두자."),
(J, "Dis, Hélène. Tu penses qu'il va écrire un avis sur Internet ?", "있잖아요, 엘렌. 그분이 인터넷에 후기를 쓸까요?"),
(H, "Je ne sais pas. Il avait l'air plus inquiet que vindicatif, non ?", "모르겠어. 복수심보다는 걱정이 더 커 보이지 않았어?"),
(J, "Oui, je pense. Quelqu'un de vindicatif ne serait pas venu en personne.", "맞아요. 복수심이 있는 사람이라면 직접 오지 않았겠죠."),
(H, "Bon. On remet les tabliers et on termine le service. Il y a des clients qui attendent.", "자. 앞치마 다시 두르고 서비스를 끝내자. 기다리는 손님들이 있어."),
(C, "Moi, j'ai compris une chose : l'écoute, c'est la moitié du travail.", "저는 하나 알았어요. 듣는 게 일의 절반이라는 거요."),
(J, "Plus que la moitié, Chloé. Allez, table quatre te réclame un pichet.", "절반 이상이야, 클로에. 자, 4번 테이블에서 피처 달라셔."),
]

VOCAB = [
("A2", "Je vous écoute.", "말씀하세요 / 듣고 있습니다.", "손님이 불만이나 요청을 말하기 전에 서비스 직원이 던지는 첫마디. ↔ [구어] Alors, qu'est-ce qui se passe ?"),
("A2", "Je suis vraiment désolé(e).", "정말 죄송합니다.", "사과의 기본형. 남성은 désolé, 여성은 désolée(발음은 같음)."),
("A2", "Un reçu", "영수증", "« Voici votre reçu signé. » ticket = 계산대 영수증, reçu = 환불·수령 증빙, facture = 세금계산서·청구서."),
("A2", "Être malade", "아프다", "« Ma femme a été très malade. » avoir mal à + 신체 부위와 구분: avoir mal au ventre (배가 아프다)."),
("B1", "Une intoxication alimentaire", "식중독", "« Le médecin parle d'une intoxication alimentaire. » 의학 진단 표현. 구어로는 « Elle a mal digéré. » 정도로 약하게 말하기도 한다."),
("B1", "Un certificat médical", "진단서", "« Voici le certificat médical. » 의사가 발급한 증명 문서. 법적 절차의 기본 자료."),
("B1", "Un geste commercial", "영업상의 호의 (보상성 서비스)", "가게가 잘못을 인정하지 않고 주는 환불·할인·선물. « Cela ne veut pas dire que je reconnais une faute. »"),
("B1", "Un remboursement / rembourser", "환불 / 환불하다", "« Je vous rembourse le dîner en totalité. » en totalité = 전액. 부분 환불은 un remboursement partiel."),
("B1", "Je prends votre inquiétude au sérieux.", "걱정하시는 것을 진지하게 받아들입니다.", "공감 표현. prendre au sérieux = 진지하게 받아들이다. ↔ [구어] Je prends ça très au sérieux."),
("B1", "Un client fâché", "화난 손님", "fâché(e) = 화가 난. se fâcher = 화를 내다. énervé 는 구어적, furieux 는 더 강함."),
("B2", "Une assurance responsabilité civile", "배상책임보험", "« Oui, nous sommes assurés. » 사업자가 타인에게 입힌 손해를 보상하는 보험. 입문 단계에서는 « assurance RC » 로 줄여 말하기도 한다."),
("B2", "Se réserver le droit de + 부정사", "~할 권리를 유보하다", "« Je me réserve le droit de demander réparation. » 법적 뉘앙스가 있는 격식 표현. 협박성 문장으로 자주 쓰이므로 응대 시 침착하게 받는다."),
("B2", "Un préjudice / demander réparation", "피해 / 배상을 요구하다", "« Il parle de préjudice. » 금전적·정신적 손해. réparation = 손해에 대한 배상."),
("B2", "Sans reconnaissance de faute", "과실 인정 없이", "환불·합의서에 적는 문구. 사과는 하되 책임 인정과 구분하는 장치."),
("B2", "Jusqu'à preuve du contraire", "반대 증거가 나올 때까지는", "« Je préfère croire les gens, jusqu'à preuve du contraire. » 추정 원칙을 표현."),
("B2", "Il est plus inquiet que vindicatif.", "그는 복수심보다 걱정이 크다.", "plus… que… 로 두 성질을 비교. vindicatif = 복수심 강한. 유사 구어: rancunier(앙심 품은)."),
("C1", "Un papier protège toujours.", "종이 한 장이 늘 지켜 준다.", "격언식 표현. 기록을 남기면 분쟁 때 도움이 된다는 뜻. [구어] Les écrits restent. 의 가벼운 변형."),
("C1", "On n'en est pas là.", "아직 거기까지는 아니다 / 그 정도는 아니다.", "[구어] 과열된 상황에서 선을 긋는 표현. ↔ 정중: Nous n'en sommes pas à ce stade."),
("B1", "Je reviendrai vers vous.", "다시 연락드리겠습니다.", "고객 응대 상투어. revenir vers qqn = 다시 연락하다. 미래형 revenir → je reviendrai."),
("B1", "J'ai failli + 부정사", "하마터면 ~할 뻔했다", "« Ma femme a failli aller à l'hôpital. » 완료되지 않은 가능성 표현. 한국어 ~할 뻔했다."),
]

GRAM = [
("B1", "사과와 보상의 흐름 — 4단계 응대", "Julien의 원칙(écouter, s'excuser, proposer, remercier)이 이 화에서 그대로 구현된다. « Je vous écoute. » → « Je suis sincèrement désolée. » → « Je vous rembourse le dîner. » → « Merci de m'avoir écouté. » 사과 표현은 désolé(e) / Je m'excuse / Toutes mes excuses 순으로 강도가 올라간다."),
("B2", "조건법으로 완곡하게 말하기", "« Pourriez-vous préciser ce que vous appelez « préjudice » ? » / « Il faudrait des preuves plus précises. » / « Ça te coûterait plus cher ? » 조건법은 요청·거절·가정을 부드럽게 만든다. 거절은 « Je ne peux pas » 보다 « Il faudrait… » 처럼 조건을 제시하는 편이 낫다."),
("B2", "접속법 입문: je ne veux pas que + 접속법", "« Je ne veux pas que ça arrive à quelqu'un d'autre. » vouloir que 뒤에는 접속법(arrive). 주어가 같으면 부정사(Je ne veux pas arriver), 다르면 que + 접속법. « Il faut que je vérifie. » 도 같은 틀."),
("B1", "복합과거 vs 현재: 사건 서술과 현재 상태", "« Ma femme a été très malade. » (사건, 복합과거) / « Elle est restée deux jours au lit. » / « Elle va mieux aujourd'hui. » (현재). 의학적 경과는 복합과거로 순서를, 지금 상태는 현재로 말한다."),
("B2", "수동·간접 표현으로 책임 피하기", "« Un remboursement est fait sur votre carte. » / « Cela ne veut pas dire que… » 주체를 숨기는 수동·비인칭은 격식·법적 뉘앙스를 준다. 구어에서는 « On vous rembourse » 로 풀어 쓴다."),
("A2", "의문문 세 가지 형태 복습", "« Elle avait l'air comment ? » (구어: 의문사 뒤) / « Quel jour a-t-elle été malade ? » (도치) / « Vous avez vu un médecin ? » (억양). 손님 앞에서는 도치나 est-ce que, 동료 사이에서는 억양형을 쓴다."),
("B1", "전치사 + 부정사: avant de, sans, après avoir", "« Avant de répondre » / « sans reconnaître de faute » / « Merci de m'avoir écouté. » avant de + 부정사, sans + 부정사, merci de + 부정사(과거 avoir + 과거분사). 한 문장 안에 시간 순서를 압축한다."),
]

READ = [
("리에종 — vous_êtes, c'est_une", "« Vous_êtes sûre ? » 에서 vous 의 s 가 [z] 로 이어진다. « C'est_un geste commercial. » 의 c'est_un [쎄튼]. 반대로 « Un_homme » 는 연음하지만 « et un homme » 의 et 뒤는 연음하지 않는다."),
("호흡 구간 — 사과와 공감", "« Je suis sincèrement désolée. / Quel jour, exactement, / a-t-elle été malade ? » 사과 문장은 천천히 끊고 감정을 실어 낭독. « Je comprends / votre inquiétude, / et je la prends au sérieux. »"),
("억양 — 분노와 침착", "손님 R의 « Vous vous rendez compte ? » 는 끝을 높이면서 화를 표현. Hélène의 응답 « Je vous entends. » 는 낮고 평평하게 이어 가며 안정감을 준다. 같은 문장도 억양에 따라 공격이 되거나 위로가 된다."),
("비음 — certificat médical, intoxication", "« intoxication » 의 -in- [ɛ̃], -tion [시옹]. « certificat » 의 -cat 에서 마지막 t 는 발음한다. « gastro-entérite » 는 gastro / en-té-rite 로 끊어 읽는다."),
("r 소리 — remboursement, préjudice", "« rembourser » 는 첫 r 과 -ser 가 이어지며 rem-bour-ser. « préjudice » 의 pré 에서 r 은 약하게. 한국어 ㄹ 로 굴리지 말고 목 안쪽에서 낸다."),
("u / ou / eu — vous, une, veux", "« vous » [vu] ↔ « une » [yn] 구분. « Je ne veux pas que ça arrive » 의 veux [vø] 는 입술을 둥글게. 세 소리를 번갈아 낭독: vous / vue / veux."),
("축약 — j'sais pas, t'es sûre", "구어 « Tu es sûre ? » 는 [튀 쒸르] 가 아니라 [티 쒸르]에 가깝게 [ty]가 약해진다. « Je ne sais pas » → « J'sais pas » [셰빠]. 손님 앞에서는 완전한 형태, 동료끼리는 축약."),
]

CULTURE = [
("프랑스의 식당 불만 처리 — 환불과 geste commercial", "프랑스 식당에서는 불만이 있을 때 먼저 직원이 사과하고, 책임자가 나와 해결책을 제안하는 것이 관례다. 잘못을 인정하지 않고도 « geste commercial » (디저트·음료 서비스, 부분 환불, 초대권)을 주는 경우가 많다. 법적 분쟁으로 번지기 전에 대화로 푸는 것이 비용도 적게 든다는 인식이 있다."),
("의사 진단서와 보험", "손님이 몸이 아팠다고 주장할 때 진단서(certificat médical)를 가져오기도 한다. 식당은 보통 assurance responsabilité civile(배상책임보험)에 가입해 있어 필요하면 보험사에 알린다. 이 화에서 Hélène은 기록을 남기고 사과하는 선에서 대응하며, 더 큰 절차는 말하지 않는다."),
]

META = dict(part=2, ep=23, part_label="제2부 Premières fissures · 여름", title_fr="Un vrai mécontentement", title_ko="진짜 불만",
 place="Le Comptoir de Marthe · 7월 28일 화요일 점심(오후 1시 20분경), 홀과 계산대 앞",
 chars="Hélène Marchand (주인 겸 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · M. Roussel (손님, 토요일 저녁 식사 후 부인이 아팠다고 주장)",
 wine="토요일 저녁에 달걀 마요네즈를 먹은 부인이 식중독 증상을 보였다는 손님 M. Roussel의 항의와 환불 요구. Hélène은 사과하되 과실은 인정하지 않고 118유로를 geste commercial로 환불한다.",
 focus="사과·보상 표현, 조건법의 완곡함, je ne veux pas que + 접속법, 법적 표현 입문(geste commercial, préjudice, assurance)",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제24화 « L'influenceuse » : 8월 4일 화요일, Julien이 인스타그램 인플루언서 Inès Marceau를 초대하자고 제안한다.")
