# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, V, M = "Hélène", "Julien", "Victor", "Mme Vasseur"
D = [
(None, "Jeudi 6 août, 10 h 30. En face, les passants ralentissent devant L'Atelier de Victor. Hélène finit l'ardoise ; Julien regarde par la vitre.", "8월 6일 목요일 오전 10시 30분. 맞은편 '라틀리에 드 빅토르' 앞에서 행인들이 걸음을 늦춘다. 엘렌은 칠판을 마저 쓰고, 줄리앙은 유리창 너머를 본다."),
(J, "Regarde, ils ont encore changé la vitrine. Il y a des plantes partout.", "봐, 쟤네 쇼윈도를 또 바꿨어. 사방에 화분이야."),
(H, "Je n'ai pas le temps de regarder. Je finis l'ardoise.", "쳐다볼 시간 없어. 칠판 마저 쓰고 있잖아."),
(J, "Hier à midi, il y avait quatorze personnes qui attendaient dehors.", "어제 점심에 바깥에서 기다리는 사람이 열네 명이었어."),
(H, "Quatorze ? Et nous, on a fait combien de couverts, hier ?", "열네 명? 그럼 우린 어제 몇 명 받았지?"),
(J, "Trente-cinq. Pour un mercredi d'août, ce n'est pas si mal.", "서른다섯. 8월 수요일치고는 나쁘지 않아."),
(H, "Ce n'est pas bien non plus. Et leurs prix, tu les as lus ?", "좋지도 않아. 그 집 가격은 봤어?"),
(J, "Oui, sur le trottoir. Leur plat du jour est à 14 €.", "응, 인도에서. 오늘의 요리가 14유로야."),
(H, "Quatorze ! Le nôtre est à 16. Et leur steak ?", "14유로! 우리는 16인데. 스테이크는?"),
(J, "18 €. Le nôtre est à 21. C'est environ quinze pour cent moins cher.", "18유로. 우리는 21이고. 대충 15퍼센트 싼 거지."),
(H, "Moins cher, moins cher... Avec quelle viande, à ce prix-là ?", "싸다, 싸다... 그 가격에 대체 무슨 고기를 쓰는데?"),
(J, "Je ne sais pas. Mais leurs assiettes sont plus jolies que les nôtres, avoue-le.", "몰라. 근데 접시는 우리 것보다 더 예뻐, 인정해."),
(H, "Plus jolies, peut-être. Meilleures, sûrement pas.", "더 예쁠 순 있겠지. 더 맛있다? 절대 아니야."),
(J, "Tu n'y as jamais goûté.", "먹어 본 적도 없잖아."),
(H, "Pas besoin. Une assiette carrée avec trois fleurs, c'est de la déco, pas de la cuisine.", "필요 없어. 네모 접시에 꽃 세 송이면 장식이지 요리가 아니야."),
(J, "Hélène, avoue : tu es jalouse.", "엘렌, 인정해. 너 질투하는 거야."),
(H, "Moi ? Pas du tout. Je suis... agacée.", "내가? 전혀. 난... 짜증 난 거야."),
(J, "C'est la même chose avec un autre mot.", "다른 단어를 썼을 뿐 똑같은 말이야."),
(H, "Non. Être jaloux, c'est vouloir ce que l'autre a. Moi, je veux que mes clients restent.", "아니야. 질투는 남이 가진 걸 갖고 싶은 거지. 난 우리 손님이 남아 주길 바라는 거야."),
(J, "Ils vont là-bas parce que c'est nouveau. Dans un mois, ils reviendront.", "새로우니까 거기 가는 거야. 한 달 뒤엔 돌아올 거야."),
(H, "Tu en es sûr ? Ça fait six semaines qu'ils ont ouvert, et la file ne diminue pas.", "확실해? 개업한 지 6주인데 줄은 안 줄어드는데."),
(J, "Non, je ne suis sûr de rien. Je dis ça pour te rassurer.", "아니, 확실한 건 없어. 널 안심시키려고 하는 말이야."),
(H, "Merci, c'est gentil. Ça ne marche pas, mais c'est gentil.", "고마워, 친절하네. 효과는 없지만 친절하긴 해."),
(None, "12 h 15. Mme Vasseur entre, son mari Henri derrière elle. C'est jeudi : la table 7 les attend.", "12시 15분. 바쉬르 부인이 남편 앙리를 뒤에 달고 들어온다. 목요일이라 7번 테이블이 그들을 기다리고 있다."),
(J, "Bonjour, madame Vasseur. Bonjour, monsieur Henri. Votre table est prête.", "안녕하세요, 바쉬르 부인. 안녕하세요, 앙리 씨. 자리 준비돼 있습니다."),
(M, "Merci, Julien. Il fait une chaleur de four ici. Vous n'avez pas de ventilateur ?", "고마워요, 줄리앙. 여기 오븐처럼 덥네요. 선풍기는 없어요?"),
(J, "Si, madame. Je l'allume tout de suite, près de votre fenêtre.", "있어요, 부인. 바로 창가 쪽으로 틀어 드릴게요."),
(M, "Bien. Et ne me donnez pas la carte, je connais mon menu par cœur.", "좋아요. 메뉴판은 주지 말아요, 내 메뉴는 외우고 있으니까."),
(H, "Bonjour, madame Vasseur. Un steak-frites, comme d'habitude ?", "안녕하세요, 바쉬르 부인. 스테이크 프리트, 늘 드시던 걸로요?"),
(M, "Comme d'habitude, hélas. Mon mari, lui, a essayé autre chose cette semaine.", "늘 그렇죠, 안타깝게도. 남편은 이번 주에 다른 걸 먹어 봤지만."),
(H, "Ah bon ? Ici, vous voulez dire ?", "어머, 그래요? 여기서 말씀이세요?"),
(M, "Non, en face. Mardi soir, nous y sommes allés pour voir.", "아니, 맞은편에서요. 화요일 저녁에 구경 삼아 갔어요."),
(H, "Ah. Et alors ? C'était comment ?", "아. 그래서요? 어땠어요?"),
(M, "C'était le restaurant le plus bruyant que j'aie jamais vu. La musique, mon Dieu !", "내가 본 중에 제일 시끄러운 식당이었어요. 음악이, 세상에!"),
(J, "Et le service, madame ? Il était bien ?", "서비스는요, 부인? 괜찮았어요?"),
(M, "Le serveur m'a dit « tu », à moi. Je pourrais être sa grand-mère !", "웨이터가 나한테 반말을 하더라니까요. 내가 걔 할머니뻘인데!"),
(H, "Quel manque de respect ! Et la cuisine ?", "너무 예의 없네요! 요리는요?"),
(M, "Henri a pris un burger. Un burger ! Après trente ans de steak-frites !", "앙리는 버거를 시켰어요. 버거를! 30년을 스테이크 프리트만 먹던 사람이!"),
(J, "Et il l'a aimé, monsieur Henri ?", "맛있게 드셨어요, 앙리 씨?"),
(M, "Il dit que non. Mais il a tout mangé, et je ne lui ai pas parlé pendant une heure.", "아니라고 하는데, 싹 다 먹었어요. 난 한 시간 동안 말을 안 했죠."),
(H, "Une heure de silence. Il a dû comprendre la leçon.", "한 시간 침묵이라니. 교훈은 확실히 얻으셨겠네요."),
(M, "Je vais être honnête avec vous, Hélène. Le dessert, par contre, était le plus beau de ma vie.", "솔직히 말할게요, 엘렌. 그래도 디저트는 내 평생 본 중에 제일 예뻤어요."),
(H, "Ah. Le plus beau de votre vie, vraiment ?", "아. 평생 중에 제일 예뻤다고요, 정말요?"),
(M, "Oui. Mais le plus bon, c'est votre mousse au chocolat. Ne faites pas cette tête.", "네. 하지만 제일 맛있는 건 당신네 초콜릿 무스예요. 그런 얼굴 하지 말아요."),
(H, "Je ne fais aucune tête, madame Vasseur. Je prépare votre steak.", "아무 얼굴도 안 했어요, 바쉬르 부인. 스테이크 준비하러 갑니다."),
(None, "Hélène disparaît en cuisine. Julien apporte l'eau et revient vers le bar, un sourire en coin.", "엘렌은 주방으로 사라진다. 줄리앙은 물을 가져다 놓고 입가에 미소를 띤 채 바로 돌아온다."),
(J, "Henri avait un burger devant lui ? Je ne le crois pas.", "앙리 씨 앞에 버거가 있었다고요? 믿기지가 않네요."),
(M, "Parlez plus bas. Il va m'entendre et il va se vexer.", "목소리 낮춰요. 들으면 남편이 기분 상해요."),
(J, "Pardon, madame. Je ne dirai rien, promis.", "죄송해요, 부인. 아무 말 안 할게요, 약속해요."),
(M, "Merci. Apportez-moi du pain : le vôtre est toujours meilleur que le leur.", "고마워요. 빵 좀 갖다 줘요. 당신네 빵이 늘 그 집 것보다 맛있어요."),
(J, "Tout de suite, madame. Et c'est vous qui le dites, pas moi.", "바로 가져올게요, 부인. 그리고 그 말씀은 제가 아니라 부인이 하신 겁니다."),
(None, "15 h 10. Le service est terminé. On frappe à la porte vitrée : un homme élégant tient une boîte en carton.", "오후 3시 10분. 서비스가 끝났다. 유리문을 누가 두드린다. 말쑥한 남자가 종이 상자를 들고 서 있다."),
(V, "Bonjour ! Excusez-moi, je ne vous dérange pas ? Victor Lambert, de l'autre côté de la rue.", "안녕하세요! 실례합니다, 방해 안 되죠? 길 건너편의 빅토르 랑베르입니다."),
(J, "Entrez, entrez. Hélène, c'est ton voisin !", "들어오세요. 엘렌, 네 이웃이야!"),
(H, "Je vois. Bonjour, monsieur Lambert. Vous cherchez quelque chose ?", "알아봤어. 안녕하세요, 랑베르 씨. 뭐 찾으시는 게 있나요?"),
(V, "Je voulais me présenter. Et vous apporter des financiers : j'en ai fait trop ce matin.", "인사드리려고요. 그리고 피낭시에를 가져왔어요. 오늘 아침에 너무 많이 구웠거든요."),
(H, "Des financiers. C'est très aimable. Julien, tu les poses sur le bar.", "피낭시에라. 정말 친절하시네요. 줄리앙, 바에 놔 줘."),
(V, "Je vous en prie. En fait, je suis un peu gêné : je viens aussi pour vous demander un service.", "별말씀을요. 사실 좀 민망한데, 부탁드릴 것도 있어서 왔어요."),
(H, "Ah, voilà. Je m'en doutais. Quel service ?", "아, 그럼 그렇지. 그럴 줄 알았어요. 무슨 부탁이죠?"),
(V, "Mon livreur est en retard. Vous n'auriez pas deux kilos de beurre à me dépanner ?", "제 배달 기사가 늦어서요. 혹시 버터 2킬로만 빌려주실 수 있을까요?"),
(J, "Du beurre ! Il est vraiment culotté, celui-là.", "버터라니! 이 양반 정말 뻔뻔한데."),
(V, "Je sais, je sais. C'est un peu fort, le jour de la première semaine de vacances.", "알아요, 알아. 좀 너무하긴 하죠, 휴가철 첫 주에."),
(H, "Pourquoi vous ne l'achetez pas au supermarché, comme tout le monde ?", "다른 사람들처럼 마트에서 사시지 그래요?"),
(V, "Parce que le vôtre, madame Marchand, est le meilleur du quartier. Tout le monde le dit.", "마르샹 씨네 버터가 동네에서 제일 좋으니까요. 다들 그렇게 말해요."),
(H, "Tout le monde ? Qui, tout le monde ?", "다들요? 누가요?"),
(V, "Votre fournisseur, M. Bastide. Il m'a dit que votre cuisine était la plus honnête de Paris.", "납품업자 바스티드 씨요. 파리에서 가장 정직한 주방이라고 하더군요."),
(H, "M. Bastide parle beaucoup. Et il vend à tout le monde, apparemment.", "바스티드 씨는 말이 많죠. 그리고 아무한테나 파는 모양이고요."),
(V, "Il vend à ceux qui paient vite. Moi, je paie vite.", "빨리 값을 치르는 사람에게 파는 거죠. 저는 빨리 내요."),
(J, "Ça, c'est un bon argument.", "그건 좋은 논거네요."),
(H, "Julien, tais-toi. Monsieur Lambert, vous cuisinez depuis longtemps ?", "줄리앙, 조용히 해. 랑베르 씨, 요리하신 지는 오래됐나요?"),
(V, "Vingt ans. J'ai commencé ici, d'ailleurs, comme plongeur, l'été de mes dix-neuf ans.", "20년이요. 사실 여기서 시작했어요. 열아홉 살 여름에 설거지 담당으로요."),
(H, "Ici ? Chez nous ? Personne ne m'en a parlé.", "여기서요? 우리 가게에서? 아무도 말 안 해 줬는데요."),
(V, "Votre mère m'a embauché pour un mois. Elle m'a appris à éplucher les carottes sans les gâcher.", "어머님이 한 달 일하라고 고용하셨어요. 당근을 낭비 없이 깎는 법을 가르쳐 주셨죠."),
(J, "Marthe t'a appris ça ? Alors, c'est presque de la famille.", "마르트가 가르쳤다고요? 그럼 거의 가족이네요."),
(H, "Ne dis pas de bêtises, Julien. Une carotte, ça ne fait pas une famille.", "바보 같은 소리 마, 줄리앙. 당근 하나로 가족이 되진 않아."),
(V, "Elle disait toujours : « Le beurre, ça ne ment pas. » Je me suis souvenu de cette phrase en ouvrant.", "어머님은 늘 말씀하셨죠. '버터는 거짓말을 안 한다.' 가게를 열 때 그 말이 떠올랐어요."),
(H, "Ma mère disait ça à tout le monde. C'était sa façon de parler de la vie.", "엄마는 누구한테나 그렇게 말했어요. 인생을 이야기하는 엄마만의 방식이었죠."),
(V, "Alors, vous me prêtez un peu de vie, et deux kilos de beurre ?", "그럼 삶 한 조각이랑 버터 2킬로, 빌려주시겠어요?"),
(H, "Hmm. Julien, va chercher le beurre à la chambre froide. Un paquet de deux kilos.", "흠. 줄리앙, 냉장실에서 버터 가져와. 2킬로짜리 한 덩이."),
(J, "Tu lui donnes vraiment du beurre ? À lui ?", "진짜로 버터를 주려고? 저 사람한테?"),
(H, "Un voisin ne manque pas de beurre. Va.", "이웃이 버터가 없는 건 안 되지. 가."),
(V, "Merci beaucoup. Je vous le rends demain matin, à la première heure, promis.", "정말 감사합니다. 내일 아침 제일 먼저 돌려 드릴게요, 약속해요."),
(H, "Pas de problème. Mais vous le rendez au même prix que le mien, hein ?", "문제없어요. 하지만 제 버터 값과 똑같이 돌려주셔야 해요, 아시죠?"),
(V, "Bien sûr. Dites, on pourrait se tutoyer, non ? On est voisins, après tout.", "물론이죠. 저기, 말 놓으면 안 될까요? 어쨌든 이웃이잖아요."),
(H, "Pas encore. Rendez-moi d'abord le beurre, on verra ensuite.", "아직은요. 먼저 버터부터 돌려주세요, 그 다음에 보죠."),
(V, "D'accord, je prends ça comme un « peut-être ». C'est déjà mieux qu'un « non ».", "알겠어요, '어쩌면'으로 받아들일게요. '아니요'보단 낫네요."),
(H, "Prenez-le comme vous voulez. Mais ne volez pas mes clients.", "마음대로 받아들이세요. 대신 우리 손님은 뺏어 가지 마시고요."),
(V, "Je ne vole personne. Les clients ne sont à personne : ils vont où ils se sentent bien.", "누구도 뺏지 않아요. 손님은 누구의 것도 아니고, 편한 곳으로 가는 거죠."),
(H, "Ils vont aussi où c'est moins cher, malheureusement.", "안타깝지만 더 싼 곳으로도 가죠."),
(V, "Oui, mais on ne peut pas rester moins cher longtemps. Mes marges sont minuscules, vous savez.", "맞아요, 근데 오래 싸게 팔 순 없어요. 제 마진은 정말 얼마 안 되거든요."),
(H, "Pourquoi vous me dites ça ? Vous êtes en train de me rassurer ?", "왜 그런 얘길 저한테 하죠? 지금 절 안심시키는 거예요?"),
(V, "Un peu. Et peut-être que je vous respecte plus que vous ne le croyez.", "조금은요. 그리고 어쩌면 제가 생각보다 더 존경하고 있는지도 몰라요."),
(J, "Voilà le beurre, monsieur Lambert. Deux kilos, bien emballés.", "버터 여기 있습니다, 랑베르 씨. 2킬로, 잘 포장했어요."),
(V, "Merci, Julien. Je vous laisse les financiers, ils sont meilleurs frais.", "고마워요, 줄리앙. 피낭시에는 두고 갑니다, 갓 만든 게 더 맛있으니까요."),
(H, "On les mangera. Au revoir, monsieur Lambert.", "먹을게요. 안녕히 가세요, 랑베르 씨."),
(V, "À demain, madame Marchand. Et dites bonjour à votre père de ma part.", "내일 뵙겠습니다, 마르샹 씨. 아버님께도 안부 전해 주세요."),
(None, "Victor sort avec son beurre. Hélène et Julien le regardent traverser la rue.", "빅토르가 버터를 들고 나간다. 엘렌과 줄리앙이 그가 길을 건너는 모습을 지켜본다."),
(J, "Il est charmant, quand même. Insupportable, mais charmant.", "그래도 매력은 있네. 참을 수 없지만 매력적이야."),
(H, "C'est ça le problème. Il est sympa, il connaît mon père, il a connu ma mère.", "그게 문제야. 사람이 좋고, 아버지를 알고, 엄마도 알았어."),
(J, "Et il a de meilleurs prix que nous.", "게다가 우리보다 가격이 좋고."),
(H, "Merci de me le rappeler. Le plus dangereux, c'est le concurrent qu'on aime bien.", "상기시켜 줘서 고맙네. 제일 위험한 건 호감 가는 경쟁자야."),
(J, "Alors, on fait quoi ? On baisse les prix ?", "그럼 어쩔까? 가격을 내릴까?"),
(H, "Non. Avec le loyer à 5 200 €, on ne peut pas. On ne fait pas la même guerre que lui.", "아니. 월세가 5,200유로인데 못 해. 우린 쟤랑 같은 싸움을 하는 게 아니야."),
(J, "Quelle guerre alors ? Tu me fais peur quand tu dis ça.", "그럼 무슨 싸움이야? 그렇게 말하니까 무서운데."),
(H, "Celle de la qualité. Ce qui est fait maison, ça se goûte, et ça ne se copie pas.", "품질의 싸움. 집에서 정성껏 만든 건 맛이 나고, 베낄 수가 없어."),
(J, "D'accord, mais il faut que les gens le sachent.", "좋아, 근데 사람들이 그걸 알아야지."),
(H, "Tu as raison. Donne-moi la craie. On va réécrire l'ardoise.", "맞아. 분필 줘. 칠판을 다시 쓰자."),
(J, "Qu'est-ce que tu écris ?", "뭐라고 쓸 거야?"),
(H, "« Ici, tout est fait maison. Depuis trente-cinq ans. » Point.", "'여기는 전부 수제입니다. 35년째.' 끝."),
(J, "C'est simple et c'est vrai. J'aime bien.", "간단하고 사실이야. 마음에 들어."),
(H, "Et demain, tu vas goûter le steak de Victor. Tu me diras la vérité.", "그리고 내일 빅토르네 스테이크 먹어 봐. 진실을 말해 줘."),
(J, "Moi ? Tu veux que j'aille chez l'ennemi ?", "나? 적진에 가란 말이야?"),
(H, "Ce n'est pas un ennemi. C'est un voisin avec mon beurre. Et il faut que je sache.", "적이 아니야. 내 버터를 가진 이웃이지. 그리고 난 알아야 해."),
(J, "D'accord, j'irai. Mais c'est toi qui paies l'addition.", "알았어, 갈게. 대신 계산은 네가 하는 거야."),
(H, "Ça marche. Et prends le burger, pour le goût d'Henri.", "좋아. 그리고 앙리 씨 입맛을 알게 버거를 시켜 봐."),
(J, "Je prends le burger. Et un financier pour le dessert, tant qu'on y est.", "버거 먹을게. 이왕 가는 김에 디저트로 피낭시에도."),
(H, "Ils sont sur le bar. Goûte-en un maintenant, dis-moi s'ils sont bons.", "바에 있잖아. 지금 하나 먹어 보고 맛있는지 말해 줘."),
(J, "Hmm... Ils sont excellents. Je suis désolé.", "음... 아주 맛있어. 미안해."),
(H, "Ne sois pas désolé. Mange le deuxième, et le troisième.", "미안해하지 마. 두 번째도, 세 번째도 먹어."),
(J, "Tu en veux un ?", "너도 하나 먹을래?"),
(H, "Un seul. Pour la science.", "하나만. 학술적 목적으로."),
(J, "Alors ?", "어때?"),
(H, "Bon. Ils sont meilleurs que les miens. Mais ne le répète à personne.", "음. 내 것보다 맛있네. 하지만 아무한테도 말하지 마."),
(J, "Ma bouche est fermée. À clé.", "내 입은 닫혔어. 자물쇠로."),
(H, "Allez, on se remet au travail. Ce soir, on sert le meilleur steak du quartier.", "자, 일하러 돌아가자. 오늘 저녁엔 동네 최고의 스테이크를 내는 거야."),
]

VOCAB = [
("A2", "Un voisin / en face", "이웃 / 맞은편", "« Victor Lambert, de l'autre côté de la rue. » « Le voisin d'en face. » 위치를 말할 때 en face (de) 를 자주 쓴다."),
("A2", "Moins cher / plus joli", "더 싸다 / 더 예쁘다", "« C'est quinze pour cent moins cher. » « Leurs assiettes sont plus jolies que les nôtres. » 형용사 앞에 plus / moins 를 붙인다."),
("A2", "Il fait une chaleur de four.", "오븐처럼 덥다", "[구어] 더위 과장 표현. ↔ 정중: Il fait très chaud ici."),
("A2", "Apporter / rendre", "가져다주다 / 돌려주다", "« Je vous apporte des financiers. » « Je vous le rends demain matin. » 이웃 간 물건 주고받기."),
("A2", "Un service", "부탁, 도움", "« Je viens aussi pour vous demander un service. » faire un service à qqn = 도와주다."),
("A2", "Du beurre / deux kilos de beurre", "버터 / 버터 2킬로", "부분관사 du 와 수량 표현 de. « Deux kilos de beurre. »"),
("B1", "Dépanner qqn", "급한 걸 빌려주어 도와주다", "[구어] « Vous n'auriez pas du beurre à me dépanner ? » ↔ 정중: Pourriez-vous me prêter du beurre ?"),
("B1", "Être agacé / être jaloux", "짜증 나다 / 질투하다", "« Je suis agacée. » vs « Tu es jalouse. » jaloux 는 남의 것을 탐내는 감정, agacé 는 신경 쓰이는 감정."),
("B1", "Le plus beau / le meilleur", "가장 예쁜 / 가장 좋은", "최상급: « le plus beau de ma vie », « le meilleur du quartier ». bon 의 비교급·최상급은 meilleur(e)."),
("B1", "Culotté", "뻔뻔한", "[구어] « Il est vraiment culotté, celui-là. » ↔ 정중: Il a beaucoup d'audace. 미워하기보다 놀라워하는 어조."),
("B1", "Un concurrent", "경쟁자", "« Le plus dangereux, c'est le concurrent qu'on aime bien. » concurrence = 경쟁."),
("B1", "Baisser les prix", "가격을 내리다", "« On baisse les prix ? » ↔ 반대는 augmenter les prix."),
("B1", "Fait maison", "수제의", "식당 표기: « Ici, tout est fait maison. » 가공품을 쓰지 않았다는 뜻."),
("B1", "Une marge", "마진", "« Mes marges sont minuscules. » 판매가에서 원가를 뺀 이익."),
("B1", "Dire « tu » à qqn", "~에게 반말(tu)하다", "« Le serveur m'a dit « tu ». » 손님에게 tu 는 무례하게 느껴질 수 있다."),
("B2", "Vexé / se vexer", "기분이 상한 / 기분 상하다", "« Il va m'entendre et il va se vexer. » 자존심이 다친 상태."),
("B2", "En avoir pour son argent", "돈값을 하다", "가격 대비 만족할 때. 가격 경쟁 이야기에서 자주 쓰는 표현."),
("B2", "Je m'en doutais.", "그럴 줄 알았어요.", "[구어] « Ah, voilà. Je m'en doutais. » ↔ 정중: Je m'y attendais."),
("B2", "Ça ne se copie pas.", "그건 베낄 수 없다", "대명동사 수동 의미. « Ce qui est fait maison, ça se goûte, et ça ne se copie pas. » 'se + 동사'로 일반적 성질을 말한다."),
("B2", "Le plus dangereux, c'est...", "가장 위험한 건 ~이다", "강조 구문 c'est ... qui/que. « Le plus dangereux, c'est le concurrent qu'on aime bien. »"),
("B2", "Un manque de respect", "무례, 예의 없음", "« Quel manque de respect ! » 반대는 avoir du respect pour qqn."),
("C1", "Faire la même guerre", "같은 전쟁을 치르다", "비유 표현. « On ne fait pas la même guerre que lui. » 같은 방식으로 경쟁하지 않겠다는 뜻."),
("C1", "Pour la science", "학술적 목적으로 (장난스럽게)", "[구어] 호기심으로 뭔가 하는 걸 정당화하는 농담. « Un seul. Pour la science. »"),
]

GRAM = [
("A2", "비교급: plus / moins / aussi ... que", "« Leurs assiettes sont plus jolies que les nôtres. » « C'est moins cher. » 형용사 앞에 plus, moins, aussi를 두고 비교 대상은 que 뒤에. « Il est aussi sympa que son père. » 처럼 같은 정도도 나타낸다."),
("A2", "비교급의 예외: meilleur / mieux", "bon 의 비교급은 plus bon이 아니라 meilleur: « Ils sont meilleurs que les miens. » 부사 bien 은 mieux: « Il cuisine mieux que moi. » 최상급은 le meilleur, le mieux."),
("B1", "최상급: le / la / les plus + 형용사", "« C'est le restaurant le plus bruyant que j'aie jamais vu. » « Le dessert le plus beau de ma vie. » 정관사 + plus + 형용사 뒤에 de 장소/범위가 온다. « Le meilleur du quartier. »"),
("B1", "비교를 이끄는 절: que 뒤 생략", "« C'est environ quinze pour cent moins cher. » 비교 대상은 문맥상 생략할 수 있다. 구어에서는 « Moins cher, moins cher... » 처럼 반복해 비꼬기도 한다."),
("B2", "질투·짜증 표현: être jaloux de / ça m'agace que + 접속법", "« Tu es jalouse. » « Je suis agacée. » 감정을 말하는 구문 « Ça m'agace qu'il soit si sympa. » 에서는 접속법을 쓴다. 필요를 말하는 « Il faut que je sache. » 도 접속법."),
("B2", "대명동사의 일반적 의미: ça se goûte, ça ne se copie pas", "« Ce qui est fait maison, ça se goûte, et ça ne se copie pas. » 대명동사가 수동·일반 진리를 나타내는 형태. « Ça se voit. » « Ça ne se fait pas. » 도 같다."),
("B2", "조건 가정과 청유: on pourrait + 부정사", "« On pourrait se tutoyer, non ? » 조건법으로 부드러운 제안. « Vous n'auriez pas du beurre ? » 도 조건법을 통한 정중한 부탁."),
]

READ = [
("리에종 — ils sont_excellents", "« Ils sont_excellents. » 는 sont 의 t 와 excellents 를 이어 [sɔ̃t‿ɛksɛlɑ̃] 처럼 읽는다. « Un_ami », « C'est_une bonne idée » 도 한정사·être 뒤 리에종은 필수. 반대로 « Et / aussi » 처럼 et 뒤에서는 리에종을 하지 않는다."),
("비교급 발음 — plus / moins", "« C'est plus joli. » 의 plus 는 [ply] (s 묵음), « Il y a plus_agacé que moi » 처럼 모음 앞에서는 [plyz]. « Moins cher » 는 [mwɛ̃ ʃɛʁ] 로 s 를 발음하지 않는다. 비교급을 끊지 않고 한 덩어리로 읽자."),
("u / ou — jaloux, culotté, bruyant", "« Tu es jaloux. » 의 tu [ty] 와 jaloux [ʒalu] 의 ou [u] 를 대비해 읽는다. « Il est culotté. » 의 u 도 입술을 둥글게 모아 [y]. « Tout le monde » 의 ou 는 입을 둥글게 한 [u]."),
("r — le meilleur du quartier", "« Le meilleur du quartier. » 에서 meilleur [mɛjœʁ], quartier [kaʁtje] 의 r 은 목구멍 안쪽에서 약하게 마찰시킨다. 문장 끝 r 을 세게 굴리지 말고 가볍게 떨어뜨리는 연습."),
("호흡 구간 — 긴 문장 끊기", "« Le plus dangereux, / c'est le concurrent / qu'on aime bien. » 처럼 3덩어리로 끊는다. « Je suis un peu gêné : / je viens aussi / pour vous demander un service. » 도 쉼표·콜론에서 숨을 쉬고 억양을 올렸다 내린다."),
("억양 — 놀람과 비꼼", "« Quatorze ? » 는 끝을 올리고, « Quatorze ! » 는 놀라서 힘을 준다. « Moins cher, moins cher... » 는 낮은 목소리로 비꼬듯 천천히. 같은 단어도 억양 하나로 감정이 달라진다."),
]

CULTURE = [
("동네 경쟁과 이웃의 예절", "프랑스 비스트로 거리에서는 신규 식당이 문을 열면 이웃에게 인사하러 가는 경우가 많다. 경쟁자이면서도 버터나 소금이 떨어지면 서로 빌려주는 일이 흔하다. 다만 tu/vous 는 아직 정해지지 않은 거리감의 상징이라, 엘렌처럼 « Pas encore » 라고 하는 것도 자연스럽다."),
("저렴한 비스트로와 인스타 감성", "2020년대 파리에는 접시 모양과 사진발을 앞세운 젊은 식당이 늘었다. 가격은 15% 정도 낮아도 마진이 얇아 오래 가지 못하는 곳이 많다. « fait maison » 표시는 법으로 정해진 라벨이라, 손님에게 신뢰를 주는 방법이다."),
]

META = dict(part=2, ep=25, part_label="제2부 Premières fissures · 여름", title_fr="Victor, le voisin d'en face", title_ko="맞은편 이웃, 빅토르",
 place="Le Comptoir de Marthe, 8월 6일 목요일 (오전 10시 30분 ~ 오후 3시 넘어)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Victor Lambert (맞은편 L'Atelier de Victor 주인) · Mme Vasseur (단골)",
 wine="맞은편에 생긴 인기 식당과 그 주인의 방문. 질투와 존경 사이에서 엘렌이 비교를 통해 자기 가게의 강점을 다시 찾는다.",
 focus="비교급·최상급(plus/moins/aussi, le plus/le meilleur), 질투·짜증 표현, 정중한 부탁(조건법), 대명동사의 일반적 의미",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제26화 « Nerfs à vif » : 8월 8일 토요일, 과로와 더위 속에서 주방과 홀의 신경이 날카로워지고 말다툼이 터진다.")
