# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, S = "Hélène", "Julien", "Chloé", "Sofiane"
D = [
(None, "Samedi 8 août, 11 h 20. Trente-quatre degrés dehors, plus de quarante en cuisine. La porte de la salle est fermée. Hélène et Sofiane préparent le service.", "8월 8일 토요일 오전 11시 20분. 바깥은 34도, 주방은 40도가 넘는다. 홀로 통하는 문은 닫혀 있다. 엘렌과 소피안이 서비스를 준비한다."),
(S, "Chef, je coupe les oignons en brunoise ou en lamelles ?", "셰프, 양파는 브뤼누아즈로 썰까요, 얇게 저며 썰까요?"),
(H, "Je te l'ai dit trois fois. Brunoise, Sofiane.", "벌써 세 번 말했잖아. 브뤼누아즈야, 소피안."),
(S, "Pardon. Je croyais que c'était pour la soupe.", "죄송해요. 수프용인 줄 알았어요."),
(H, "Il n'y a pas de soupe en août ! Regarde la fiche, putain.", "8월에 무슨 수프야! 작업 카드 좀 봐, 젠장."),
(S, "Excuse-moi, je me suis trompé. Je recommence tout de suite.", "미안해요, 제가 착각했어요. 바로 다시 할게요."),
(H, "Ne t'excuse pas, dépêche-toi. On ouvre dans quarante minutes.", "사과하지 말고 서둘러. 40분 뒤에 열어."),
(S, "Oui, chef. Tu as dormi, cette nuit ? Tu as l'air fatiguée.", "네, 셰프. 간밤에 좀 주무셨어요? 피곤해 보여요."),
(H, "Quatre heures. Et ne me fais pas la conversation, je suis à cran.", "네 시간. 그리고 말 걸지 마, 신경이 곤두서 있으니까."),
(S, "Compris. Je me tais.", "알겠습니다. 입 다물게요."),
(H, "Bordel, où est le beurre ? Qui a touché au beurre ?", "빌어먹을, 버터 어디 갔어? 누가 버터를 만졌어?"),
(S, "C'est moi, chef. Je l'ai sorti du frigo pour qu'il ramollisse.", "저예요, 셰프. 부드러워지라고 냉장고에서 꺼냈어요."),
(H, "Il fait quarante degrés ! Il va fondre, tu ne le vois pas ?", "40도라고! 녹을 텐데, 안 보여?"),
(S, "Si, si, je le remets. Je ne m'en suis pas rendu compte.", "네, 네, 도로 넣을게요. 미처 생각을 못 했어요."),
(None, "11 h 50. Julien entre en cuisine, un cahier de réservations à la main.", "11시 50분. 줄리앙이 예약 장부를 들고 주방으로 들어온다."),
(J, "Bonjour tout le monde. Il y a quarante-deux couverts réservés, dont deux tables de huit.", "다들 안녕. 예약이 42명이고, 그중 8인석이 두 테이블이야."),
(H, "Deux tables de huit ? Un samedi d'août, sans Karim ? Tu me fais marcher.", "8인석이 두 개? 8월 토요일에, 카림도 없이? 나 놀리는 거지."),
(J, "Non, c'est vrai. Je ne pouvais pas dire non, ce sont des habitués.", "아니, 진짜야. 단골이라 거절할 수가 없었어."),
(H, "Tu aurais pu m'en parler avant d'accepter.", "받기 전에 나한테 말했어야지."),
(J, "Je t'ai envoyé un message hier soir. Tu ne l'as pas lu.", "어젯밤에 메시지 보냈어. 넌 안 읽었고."),
(H, "J'étais en train de faire la comptabilité jusqu'à minuit, moi !", "난 자정까지 장부 정리하고 있었다고!"),
(J, "Ce n'est pas ma faute si tu ne dors jamais.", "네가 잠을 안 자는 게 내 잘못은 아니잖아."),
(H, "Je n'ai pas dit que c'était ta faute. Laisse tomber.", "네 잘못이라고 안 했어. 그만두자."),
(None, "12 h 05. Chloé arrive en courant, essoufflée, son tablier à moitié noué.", "12시 5분. 클로에가 숨을 헐떡이며 뛰어 들어온다. 앞치마는 반쯤만 묶여 있다."),
(C, "Pardon, pardon ! Le métro est tombé en panne à Parmentier.", "죄송해요, 죄송해요! 파르망티에 역에서 지하철이 고장 났어요."),
(J, "Encore ? Ton métro tombe en panne tous les samedis, c'est étonnant.", "또? 네 지하철은 토요일마다 고장 나네, 신기하다."),
(C, "Tu ne me crois pas ? Je te jure que c'est vrai.", "안 믿는 거야? 진짜라고 맹세할게."),
(J, "Je ne dis pas que tu mens. Je dis que ça fait la troisième fois.", "거짓말한다는 게 아니야. 이번이 세 번째라는 거지."),
(C, "Je ne peux pas réparer le métro, moi ! Je me lève à six heures pour être là !", "내가 지하철을 고칠 순 없잖아! 여기 오려고 6시에 일어난다고!"),
(H, "Ça suffit, vous deux. On ouvre dans trois minutes. Chloé, va mettre ton tablier.", "그만해, 둘 다. 3분 뒤에 열어. 클로에, 앞치마나 제대로 둘러."),
(None, "13 h 10. Le coup de feu. Les bons de commande s'accumulent sur le rail ; la chaleur est étouffante.", "오후 1시 10분. 점심 피크. 주문서가 레일에 쌓이고 열기는 숨이 막힌다."),
(H, "Table 12 : deux blanquettes, un cabillaud. Départ dans deux minutes !", "12번 테이블, 블랑케트 둘, 대구 하나. 2분 뒤 출발!"),
(S, "Oui, chef. Deux blanquettes, un cabillaud, table 12.", "네, 셰프. 블랑케트 둘, 대구 하나, 12번 테이블."),
(C, "Chef, la 21 a demandé du pain. Et la 8 voudrait l'addition.", "셰프, 21번이 빵을 더 달래요. 8번은 계산서를 원하고요."),
(H, "Ce n'est pas à moi que tu dis ça, c'est à Julien ! Je suis en train de cuisiner.", "그건 나한테 말할 게 아니라 줄리앙한테 할 말이야! 난 요리 중이잖아."),
(C, "Pardon. Je me suis trompée de personne.", "죄송해요. 말할 사람을 헷갈렸어요."),
(H, "Chaud devant ! Sofiane, la sauce, la sauce !", "뜨거워요, 앞 조심! 소피안, 소스, 소스!"),
(S, "Je la fais, je la fais ! Elle est prête dans une minute.", "하고 있어요, 하고 있어요! 1분이면 돼요."),
(H, "Une minute ? C'est une éternité ! Merde, elle va brûler !", "1분? 영원이잖아! 젠장, 타겠어!"),
(S, "Je suis désolé, chef. Je ne suis pas assez rapide.", "죄송해요, 셰프. 제가 충분히 빠르지 못해서요."),
(H, "Arrête de t'excuser tout le temps ! Remue et regarde ce que tu fais !", "계속 사과하지 마! 젓고, 지금 뭘 하는지 똑바로 봐!"),
(J, "Table 12, c'est parti ? Le monsieur est pressé, il a un train.", "12번 나가요? 손님이 기차 시간이 있어서 급해하세요."),
(H, "Deux minutes, j'ai dit ! Ne reviens pas me le demander toutes les trente secondes !", "2분이라고 했잖아! 30초마다 와서 묻지 마!"),
(J, "Ne crie pas sur moi, je fais mon travail, moi aussi.", "나한테 소리 지르지 마. 나도 내 일을 하는 거야."),
(H, "Alors fais ton travail et laisse-moi faire le mien. Table 12, départ !", "그럼 네 일 하고 내 일은 나한테 맡겨. 12번, 출발!"),
(S, "Deux blanquettes, un cabillaud, prêts ! Je les passe à Chloé ?", "블랑케트 둘, 대구 하나 준비됐어요! 클로에한테 넘길까요?"),
(H, "Oui. Mais goûte la sauce avant. Toujours goûter, Sofiane, toujours.", "응. 근데 그 전에 소스 맛부터 봐. 항상 맛을 봐, 소피안, 항상."),
(S, "Elle est bonne, chef. Un peu trop salée, peut-être ?", "맛있어요, 셰프. 약간 짤 수도 있겠네요?"),
(H, "Tu as raison. Rajoute un peu de crème, vite. Bien vu.", "맞아. 크림 조금 더 넣어, 빨리. 잘 봤어."),
(None, "Les assiettes sortent. Chloé les prend et disparaît en salle.", "접시들이 나온다. 클로에가 받아서 홀로 사라진다."),
(None, "13 h 25. Chloé revient en cuisine, le visage défait. Julien la suit.", "오후 1시 25분. 클로에가 얼굴이 굳은 채 주방으로 돌아온다. 줄리앙이 따라온다."),
(J, "Putain, Chloé, c'était la 12 pas la 21 ! Le monsieur a reçu le cabillaud de la dame !", "젠장, 클로에, 12번이었지 21번이 아니라고! 남자 손님한테 부인 대구가 갔잖아!"),
(C, "J'ai lu le bon trop vite, je me suis trompée. Ça arrive à tout le monde !", "주문서를 너무 빨리 읽었어요, 착각했어요. 누구나 그럴 수 있잖아!"),
(J, "Ça arrive à tout le monde, mais pas trois fois dans la même semaine.", "누구나 그렇긴 한데, 한 주에 세 번은 아니지."),
(C, "Tu me le reproches devant tout le monde ? Merci, c'est sympa.", "다들 있는 앞에서 나무라는 거야? 고마워, 참 다정하네."),
(J, "Je ne te reproche rien, je te dis ce qui s'est passé.", "나무라는 게 아니야, 있었던 일을 말하는 거지."),
(H, "Stop ! Toi, Julien, tu retournes en salle. Et toi, Chloé, tu respires.", "그만! 줄리앙 너는 홀로 돌아가. 클로에 너는 숨 좀 쉬어."),
(J, "Je vais lui expliquer, au monsieur. Il faut que je me calme d'abord.", "손님한테 설명 드려야지. 먼저 진정부터 해야겠어."),
(None, "Julien se redresse, sourit, pousse la porte. Sa voix change immédiatement.", "줄리앙이 자세를 바로 하고 미소를 지으며 문을 민다. 목소리가 곧바로 바뀐다."),
(J, "Monsieur, toutes mes excuses, une erreur de service. Votre plat arrive tout de suite.", "손님, 서비스 착오로 정말 죄송합니다. 요리가 곧 나옵니다."),
(None, "La porte se referme. Dans la cuisine, Chloé s'essuie les yeux avec son tablier.", "문이 닫힌다. 주방에서 클로에가 앞치마로 눈가를 훔친다."),
(C, "J'en ai ras-le-bol. Tout le monde me crie dessus, ici.", "이제 지쳤어요. 여기서는 다들 저한테 소리를 질러요."),
(H, "Personne ne te crie dessus. On est tous sous pression, c'est tout.", "아무도 너한테 소리 안 질러. 다들 압박받고 있는 것뿐이야."),
(C, "Toi, tu m'as crié dessus mardi, pour les verres. Je m'en souviens très bien.", "엘렌은 화요일에 유리잔 때문에 소리 질렀잖아요. 똑똑히 기억해요."),
(H, "C'était pour le verre cassé. Ce n'est pas pareil, Chloé.", "그건 깨진 잔 때문이었어. 같은 얘기가 아니야, 클로에."),
(C, "Pour moi, c'est pareil. Pardon, je suis fatiguée, moi aussi.", "저한테는 같아요. 죄송해요, 저도 피곤해서요."),
(H, "Retourne en salle. On en reparle après le service.", "홀로 돌아가. 서비스 끝나고 얘기하자."),
(None, "15 h 20. Le dernier client est parti. Les quatre se retrouvent dans l'arrière-cuisine, épuisés.", "오후 3시 20분. 마지막 손님이 갔다. 네 사람이 녹초가 되어 안쪽 주방에 모인다."),
(J, "Bon. Il faut qu'on se parle. On ne peut pas continuer comme ça.", "자. 우리 얘기 좀 해야 해. 이렇게 계속할 순 없어."),
(H, "Parle. Je t'écoute. Mais fais vite, j'ai les courses à faire.", "말해. 듣고 있어. 대신 빨리 해, 장 봐야 하니까."),
(J, "Voilà : ce midi, tu as crié sur Sofiane, sur moi, sur tout le monde.", "그러니까, 오늘 점심에 넌 소피안한테, 나한테, 모두한테 소리 질렀어."),
(H, "Je n'ai pas crié sur tout le monde. J'ai donné des ordres, fort.", "모두한테 소리 지르진 않았어. 크게 지시했을 뿐이야."),
(J, "Quand on dit « putain » à un stagiaire, ce n'est pas un ordre.", "수습한테 '젠장'이라고 하면 그건 지시가 아니지."),
(S, "Moi, ça va, chef. Je suis habitué, dans les cuisines, c'est normal.", "전 괜찮아요, 셰프. 주방에선 익숙해서 평범한 일이에요."),
(J, "Ce n'est pas parce que c'est normal que c'est bien, Sofiane.", "평범하다고 해서 좋은 건 아니야, 소피안."),
(H, "Ah, parce que maintenant, c'est moi le problème ?", "아, 이제는 내가 문제라는 거야?"),
(J, "Je n'ai pas dit ça. Mais tu t'énerves pour un rien depuis deux semaines.", "그런 말 아니야. 하지만 2주 전부터 별일 아닌 걸로 짜증을 내잖아."),
(H, "Pour un rien ? Karim est parti, le loyer monte, l'autre en face me prend mes clients !", "별일 아니라고? 카림은 떠났고, 월세는 오르고, 맞은편 가게는 손님을 뺏어 가는데!"),
(J, "Et ce n'est pas ma faute, ni celle de Chloé, ni celle de Sofiane.", "그리고 그건 내 잘못도, 클로에 잘못도, 소피안 잘못도 아니야."),
(H, "Je n'ai jamais dit que c'était votre faute !", "너희 잘못이라고 한 적 없어!"),
(C, "Pourtant, tu nous traites comme si on était responsables de tout.", "근데 우리가 전부 책임져야 하는 사람처럼 대하잖아."),
(H, "C'est faux. C'est faux et c'est injuste.", "그건 틀렸어. 틀렸고 부당해."),
(C, "Alors pourquoi je pleure dans la cuisine à chaque service ?", "그럼 왜 저는 서비스 때마다 주방에서 울고 있죠?"),
(H, "Parce que tu es sensible. Je ne peux pas faire du travail avec des gens qui pleurent.", "네가 예민하니까. 난 울어 대는 사람들이랑 일을 못 해."),
(J, "Hélène ! Tu dépasses la limite.", "엘렌! 선을 넘고 있어."),
(H, "Quoi ? Je dis la vérité. C'est trop chiant, ce genre de réflexion tous les jours.", "뭐? 사실을 말하는 거야. 이런 지적 매일 듣는 것도 너무 짜증 나."),
(J, "Tu entends ce que tu dis ? Tu t'entends parler ?", "네가 하는 말 들려? 네 말투가 들려?"),
(None, "Un silence lourd. On entend seulement le ventilateur et l'eau qui coule dans l'évier.", "무거운 침묵. 선풍기 소리와 싱크대에서 물 흐르는 소리만 들린다."),
(H, "...", "..."),
(H, "Merde. Je suis con. Je viens de dire une chose horrible, Chloé. Pardon.", "젠장. 내가 바보 같네. 끔찍한 말을 했어, 클로에. 미안해."),
(C, "Tu étais en colère. Mais ça fait mal quand même.", "화가 났던 거 알아요. 그래도 아파요."),
(H, "Je sais. Je ne le pensais pas. Je ne le pense pas du tout.", "알아. 진심이 아니었어. 전혀 그렇게 생각 안 해."),
(C, "Tu pleurais aussi, toi, au début ? Dans ta première cuisine ?", "엘렌도 처음엔 울었어요? 첫 주방에서?"),
(H, "Tous les jours pendant six mois. Dans la chambre froide, pour qu'on ne me voie pas.", "6개월 동안 매일. 아무도 못 보게 냉장실에서."),
(S, "Moi aussi, chef. À Lyon. J'ai pleuré dans un sac de farine.", "저도 그랬어요, 셰프. 리옹에서요. 밀가루 포대 안에서 울었어요."),
(J, "Un sac de farine ! Ça, c'est professionnel.", "밀가루 포대라니! 그건 프로답네."),
(C, "Arrête, tu vas me faire rire alors que je veux rester fâchée.", "그만해요, 화난 채로 있고 싶은데 웃기잖아요."),
(J, "Désolé. Moi aussi, j'ai été trop dur avec toi ce midi. Pardon.", "미안. 나도 오늘 점심에 너한테 너무 심하게 했어. 미안해."),
(C, "Pardon accepté. Mais pour le métro, je te jure que c'était vrai.", "받아들일게요. 근데 지하철 얘기는 진짜 맹세해요."),
(H, "Chloé, une chose : malgré l'erreur, tu as bien travaillé en salle aujourd'hui.", "클로에, 하나만. 실수는 있었지만 오늘 홀에서 일 잘했어."),
(C, "Vraiment ? Tu me dis ça pour me consoler.", "정말요? 날 위로하려고 하는 말이죠."),
(H, "Non. Je ne console jamais personne. Demande à Julien.", "아니. 난 누구도 위로 안 해. 줄리앙한테 물어봐."),
(J, "C'est vrai. Elle n'a jamais consolé personne en trois ans.", "맞아. 3년 동안 누굴 위로한 적이 없어."),
(J, "Je te crois. Je vais regarder l'appli du métro pour vérifier. Pour rigoler.", "믿어. 지하철 앱으로 확인해 볼게. 장난으로."),
(H, "Bon. On s'est dit des choses. Maintenant, on arrête de se disputer.", "자. 할 말은 다 했고. 이제 그만 싸우자."),
(J, "D'accord, mais il y a un vrai problème. On est six jours sur sept, sans Karim.", "좋아, 근데 진짜 문제가 있어. 카림 없이 일주일에 6일을 일하잖아."),
(H, "Je sais. Je ne m'en sors pas. J'ai peur de tout lâcher.", "알아. 감당이 안 돼. 다 놓아 버릴까 봐 겁나."),
(J, "Alors il faut qu'on s'organise autrement. Je peux faire la plonge un soir.", "그럼 다르게 짜야 해. 하루 저녁은 내가 설거지를 할게."),
(C, "Moi, je peux venir plus tôt le matin, pour la mise en place des desserts.", "저는 아침에 더 일찍 와서 디저트 준비를 할 수 있어요."),
(S, "Et moi, je peux rester jusqu'à la fermeture, chef. Je n'ai pas peur du travail.", "저는 마감까지 남을 수 있어요, 셰프. 일은 겁 안 나요."),
(H, "Vous êtes gentils. Je ne le mérite pas, mais merci.", "너희 정말 착하다. 내가 받을 자격은 없지만 고마워."),
(J, "Tu le mérites. Tu es dure, mais tu es juste, la plupart du temps.", "받을 자격 있어. 엄격하지만 대부분 공정해."),
(H, "La plupart du temps. Merci pour la nuance.", "대부분이라. 단서 달아 줘서 고맙네."),
(C, "On commence par quoi ? J'ai encore deux heures avant le service du soir.", "뭐부터 할까요? 저녁 서비스까지 아직 두 시간 있어요."),
(H, "Par manger quelque chose. Personne n'a mangé depuis ce matin, non ?", "뭐라도 먹는 거부터. 아침 이후로 아무도 안 먹었지?"),
(S, "Moi, j'ai mangé un morceau de pain à dix heures.", "저는 10시에 빵 한 조각 먹었어요."),
(H, "Un morceau de pain. Il y a des restes de blanquette. On se fait chauffer ça.", "빵 한 조각이라. 블랑케트 남은 게 있어. 그거 데워 먹자."),
(J, "Moi, je mets la table. Au fond de la salle, loin de la vitre.", "내가 상 차릴게. 홀 안쪽, 유리창에서 먼 데로."),
(C, "Et moi, je m'occupe du pain et de l'eau fraîche. Avec des glaçons !", "저는 빵이랑 시원한 물 챙길게요. 얼음 넣어서요!"),
(H, "Bonne idée. Autre chose : mon père m'a appelée ce matin, avant le service.", "좋은 생각이야. 또 하나. 아버지가 오늘 아침 서비스 전에 전화하셨어."),
(J, "Lucien ? Qu'est-ce qu'il voulait à sept heures du matin ?", "루시앙? 아침 7시에 무슨 일이래?"),
(H, "Il a dit qu'il avait une méthode pour nous. Il passera mardi matin à neuf heures.", "우리를 위한 방법이 있다고 하셨어. 화요일 아침 9시에 오실 거야."),
(J, "Une méthode ? Je suis curieux. Et un peu inquiet, aussi.", "방법이라고? 궁금하네. 약간 걱정도 되고."),
(H, "Moi aussi. Mais ce soir, on ne parle pas de ça. Ce soir, on respire et on cuisine.", "나도. 하지만 오늘 저녁엔 그 얘긴 안 해. 오늘 저녁은 숨 쉬고 요리하는 거야."),
(C, "Et on ne se crie plus dessus ?", "그리고 소리 안 지르는 거죠?"),
(H, "On essaie. Et si je crie, tu as le droit de me dire : « Chef, on respire. »", "노력해 볼게. 내가 소리 지르면 '셰프, 숨 쉬세요.' 하고 말해도 돼."),
(C, "D'accord. Je le note. Dans mon carnet de vocabulaire, à la page « nerfs à vif ».", "좋아요. 적어 둘게요. 제 어휘 수첩의 '신경이 곤두서다' 페이지에요."),
(J, "Alors ajoute aussi : « Se calmer, s'excuser, se réconcilier. »", "그럼 이것도 추가해: '진정하다, 사과하다, 화해하다.'"),
(S, "Et « sac de farine ».", "그리고 '밀가루 포대'도요."),
(H, "Et « chaud devant ». Allez, tout le monde à table. J'ai faim.", "그리고 '뜨거워요, 앞 조심'도. 자, 다들 식탁으로. 배고프다."),
]

VOCAB = [
("A2", "Se dépêcher", "서두르다", "대명동사. « Dépêche-toi, on ouvre dans quarante minutes. » 명령형은 dépêche-toi / dépêchez-vous."),
("A2", "Se tromper (de)", "착각하다, 잘못 알다", "« Je me suis trompé. » « Je me suis trompée de personne. » 여성은 과거분사에 e 를 붙인다."),
("A2", "S'excuser / Pardon", "사과하다 / 죄송합니다", "« Excuse-moi, chef. » « Je suis désolé. » 가까운 사이에서는 pardon 도 자연스럽다."),
("A2", "Fatigué / à cran", "피곤한 / 신경이 곤두선", "[구어] « Tu as l'air fatiguée. » « Je suis à cran. » à cran = 신경이 곤두선. ↔ 정중: Je suis très tendue."),
("B1", "C'est de ta faute / Ce n'est pas ma faute", "네 잘못이야 / 내 잘못이 아니야", "비난과 변명. « Ce n'est pas ma faute si tu ne dors jamais. » 변명할 때는 Je n'y suis pour rien 도 쓴다."),
("B1", "Reprocher qqch à qqn", "~를 나무라다, 탓하다", "« Tu me le reproches devant tout le monde ? » « Je ne te reproche rien. »"),
("B1", "Avoir ras-le-bol / J'en ai ras-le-bol", "진절머리 나다", "[구어] « J'en ai ras-le-bol. » ↔ 정중: Je n'en peux plus. 가까운 사이에서 쓰는 표현."),
("B1", "Chaud devant !", "뜨거워요, 앞 조심!", "[구어] 주방 용어. 뜨거운 것을 들고 지나갈 때 외친다. ↔ 정중: Attention, c'est chaud."),
("B1", "Un coup de feu", "점심·저녁 피크 시간", "주방에서 주문이 몰리는 시간. « Le coup de feu » 는 8화에서 이미 나왔다."),
("B1", "Être sous pression", "압박을 받다", "« On est tous sous pression. » pression = 압력, 스트레스."),
("B1", "S'en sortir", "헤쳐 나가다, 감당하다", "« Je ne m'en sors pas. » 일·돈·상황이 버거울 때."),
("B2", "Putain / Merde / Bordel", "젠장 / 빌어먹을 / 망할", "[속어] 놀람·분노를 터뜨리는 감탄사. « Regarde la fiche, putain. » « Merde, elle va brûler ! » 쓸 수 있음: 가까운 주방 동료·가족 사이에서 혼잣말이나 상황에 대한 욕 / 금지: 손님 앞, 상사·외부인 앞, 특정 사람을 향한 모욕. 줄리앙이 홀 문을 열자마자 말투가 바뀌는 것이 모범."),
("B2", "Chiant", "짜증 나는, 귀찮은", "[속어] « C'est trop chiant, ce genre de réflexion. » 사람이 아니라 상황·일에 쓴다. 쓸 수 있음: 주방·가족 사이 / 금지: 손님·외부인 앞, 사람을 직접 향한 모욕."),
("B2", "Être con / C'est con", "바보 같다 / 한심하다", "[속어] « Merde. Je suis con. » 자기 자신을 탓할 때나 « C'est con. » 처럼 상황에 쓰는 것은 가볍지만, 남에게 « Tu es con » 은 모욕이다. 쓸 수 있음: 자책할 때, 친한 사이 / 금지: 상대를 직접 지칭하거나 손님·외부인 앞."),
("B2", "Être à fleur de peau / à vif", "신경이 곤두서 있다", "제목 « Nerfs à vif » 와 같은 계열. « Les nerfs à vif » = 날카로워진 신경."),
("B2", "Dépasser la limite", "선을 넘다", "« Tu dépasses la limite. » 말·행동이 용납 범위를 벗어났을 때."),
("B2", "S'énerver pour un rien", "별것 아닌 일로 화내다", "« Tu t'énerves pour un rien depuis deux semaines. » pour un rien = 사소한 일로."),
("B2", "Se réconcilier", "화해하다", "« Se calmer, s'excuser, se réconcilier. » 싸운 뒤의 순서를 나타내는 대명동사 세 개."),
("B2", "Ça fait mal quand même.", "그래도 아프네요.", "[구어] quand même = 그래도. ↔ 정중: Cela me blesse néanmoins."),
("B2", "Tu me fais marcher.", "나 놀리는 거지.", "[구어] faire marcher qqn = 속이다, 놀리다. ↔ 정중: Vous plaisantez."),
("C1", "Laisser tomber", "그만두다, 신경 쓰지 않다", "[구어] « Laisse tomber. » 말다툼을 접을 때. ↔ 정중: N'en parlons plus."),
("C1", "Je ne m'en suis pas rendu compte.", "미처 몰랐다", "se rendre compte (de) + qqch. « Il va fondre, tu ne le vois pas ? » 에 대한 변명. 복합과거 대명동사의 일치에 주의."),
]

GRAM = [
("B1", "비난과 변명 — c'est de ta faute / je n'y suis pour rien", "« Ce n'est pas ma faute si tu ne dors jamais. » « Je n'ai jamais dit que c'était votre faute ! » faute 를 중심으로 비난·부인. 비난은 « Tu me le reproches », 반박은 « C'est faux et c'est injuste. »"),
("A2", "대명동사 현재: se dépêcher, se calmer, se tromper", "« Dépêche-toi. » « Il faut que je me calme. » 대명동사는 주어에 맞춰 me, te, se, nous, vous, se 를 쓴다. 명령형 긍정은 동사 뒤에 -toi / -vous, 부정은 « Ne t'excuse pas. » 처럼 앞에 둔다."),
("B1", "대명동사 복합과거: je me suis trompé(e)", "« Je me suis trompé. » « Je me suis trompée de personne. » 조동사는 être, 과거분사가 주어(여성이면 e)와 일치한다. 부정: « Je ne m'en suis pas rendu compte. » (en, me 가 être 앞)."),
("B2", "상호 대명동사: se disputer, se parler, se réconcilier", "« Il faut qu'on se parle. » « On arrête de se disputer. » « On ne se tutoie plus ? » 서로 ~한다는 뜻의 상호 대명동사. 복수 주어(on 포함)에서 쓴다."),
("B1", "il faut que + 접속법", "« Il faut qu'on se parle. » « Il faut que je me calme d'abord. » « Il faut qu'on s'organise autrement. » 필요·의무를 말할 때 il faut que 뒤에 접속법 현재. 구어에서는 on 이 nous 를 대신한다."),
("B2", "비난 vs 설명: je ne te reproche rien / je te dis ce qui s'est passé", "« Je ne te reproche rien, je te dis ce qui s'est passé. » 부정 뒤 대조 구조. 감정이 격해질 때는 « Tu m'accuses ? » « Tu dépasses la limite. » 로 한계를 표현."),
("B2", "pour un rien / depuis deux semaines", "« Tu t'énerves pour un rien depuis deux semaines. » depuis + 기간은 지금도 계속되는 상태를 나타낸다. « Ça fait la troisième fois. » 처럼 횟수 강조는 ça fait."),
]

READ = [
("억양 — 분노에서 침묵으로", "« Bordel, où est le beurre ? » 는 시작을 높고 빠르게, 끝을 짧게 끊는다. 반대로 « Merde. Je suis con. » 는 낮고 느리게. 같은 속어도 억양에 따라 화냄·자책이 갈리므로 두 번 연습해 보자."),
("모음 u — tu, plus, brunoise", "« Tu t'énerves. » « Brunoise » 의 u 는 입술을 둥글게 모은 [y]. « Tout le monde » 의 ou [u] 와 구별: tu / tout. « Dépêche-toi » 의 -toi 는 [twa]."),
("리에종 — Ça arrive à tout_le monde", "« Ça arrive à / tout le monde. » 는 tout 와 le 사이 리에종이 없다. 반대로 « Ils_ont tout mangé » 에서 Ils_ont 은 [z] 리에종 필수. 감정이 올라갈수록 리에종이 빠지기 쉬우니 주의."),
("호흡 구간 — 길게 따지는 문장", "« Karim est parti, / le loyer monte, / l'autre en face / me prend mes clients ! » 처럼 4덩어리로 끊되 끝으로 갈수록 목소리를 키운다. « Je ne te reproche rien, / je te dis ce qui s'est passé. » 는 쉼표에서 숨을 쉰다."),
("비음 — pardon, tomber, ça fait mal", "« Pardon » [paʁdɔ̃], « Laisse tomber » [tɔ̃be], « maintenant » [mɛ̃tnɑ̃]. 비음 뒤 n/m 을 발음하지 않는다. 화낼 때도 비음은 코로 빠져나가야 알아듣는다."),
("목소리 전환 — 주방과 홀", "줄리앙이 주방에서는 « Putain, Chloé, c'était la 12 ! » 라고 말하다가 문을 열면 « Monsieur, toutes mes excuses, une erreur de service. » 로 바꾼다. 같은 사람이 두 가지 톤으로 읽는 연습을 하면 vous 와 tu 의 거리감이 몸에 밴다."),
]

CULTURE = [
("주방의 말투와 홀의 말투", "프랑스 레스토랑 주방에서는 sacré, merde, putain 같은 말이 압박 속 감탄사처럼 자주 오간다. 그러나 이것은 같은 팀 안에서만 허용되는 일종의 속 언어다. 손님이 듣는 곳에서는 절대 쓰지 않고, 특정인을 모욕하는 것도 직업 윤리상 금기다. 최근에는 « brigade » 의 고함 문화를 줄이려는 흐름도 있다."),
("brigade 와 « chef »", "프랑스 주방은 brigade 라는 군대식 위계를 이어받아, 부하는 셰프를 « Chef » 로 부르고 지시에는 « Oui, chef » 로 답한다. 주문을 복창하는 습관도 여기서 왔다. 그러나 가족 비스트로에서는 tu 와 이름을 쓰는 경우가 많아, 이 화처럼 위계와 친밀함이 뒤섞인다."),
]

META = dict(part=2, ep=26, part_label="제2부 Premières fissures · 여름", title_fr="Nerfs à vif", title_ko="곤두선 신경",
 place="Le Comptoir de Marthe, 8월 8일 토요일 (오전 11시 20분 ~ 오후 3시 넘어, 주방과 안쪽 주방)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · Sofiane (단기 주방 보조)",
 wine="더위와 과로, 카림의 빈자리 속에서 터진 점심 직후의 말다툼과 화해. 주방 구어와 속어의 사용 범위를 배운다.",
 focus="비난·변명 표현, 대명동사(현재·복합과거·상호), il faut que + 접속법, 주방 속어와 손님 앞 말투의 구분",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제27화 « La méthode de Lucien » : 8월 11일 화요일 아침, 루시앙이 옛 방식을 들고 찾아온다.")
