# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, C = "Hélène", "Lucien", "Julien", "Chloé"
D = [
(None, "Mardi 11 août, 9 h. Le Comptoir n'est pas encore ouvert. Lucien entre avec un sac de pêches ; Hélène, les yeux cernés, finit d'écrire l'ardoise.", "8월 11일 화요일 오전 9시. 아직 문을 열지 않은 코ントワール. 루시앙이 복숭아 자루를 들고 들어온다. 엘렌은 눈 밑이 거뭇한 채 칠판을 마저 쓴다."),
(L, "Bonjour, ma fille. Tiens, des pêches. Je les ai achetées au marché d'Aligre.", "안녕, 우리 딸. 자, 복숭아야. 알리그르 시장에서 샀다."),
(H, "Merci, Papa. Tu es là tôt. Tu avais dit neuf heures, non ?", "고마워요, 아빠. 일찍 오셨네요. 9시라고 하셨죠?"),
(L, "Je suis là à neuf heures pile. C'est toi qui es en retard sur ta vie.", "9시 정각에 왔다. 네가 인생에서 늦은 거지."),
(H, "Très drôle. Tu as bien dormi ?", "정말 웃겨요. 잘 주무셨어요?"),
(L, "Non. J'ai repensé à tout ça toute la nuit. À 1993, surtout.", "아니. 밤새 이 생각을 했어. 특히 1993년 일을."),
(H, "1993 ? Papa, on est en 2026. Qu'est-ce que 1993 a à voir avec nous ?", "1993년이요? 아빠, 지금은 2026년이에요. 1993년이 우리랑 무슨 상관이에요?"),
(L, "Tu verras. Julien, Chloé, venez vous asseoir un instant, s'il vous plaît.", "곧 알게 된다. 줄리앙, 클로에, 잠깐 와서 앉아 줄래."),
(J, "Bonjour, Lucien. On a un conseil de famille ?", "안녕하세요, 루시앙. 가족회의라도 하나요?"),
(L, "Un conseil du Comptoir. Chloé, tu as ton petit carnet ? Parfait, écris.", "코ントワール 회의지. 클로에, 작은 수첩 있지? 좋아, 적어라."),
(C, "J'écris. Mais je ne suis pas sûre de tout comprendre.", "적을게요. 근데 다 이해할지는 모르겠어요."),
(L, "Hélène m'a dit que ça a bardé samedi, en cuisine.", "토요일에 주방에서 한바탕했다고 엘렌이 말하더라."),
(J, "Ça a bardé, oui. On s'est disputés, puis on s'est excusés.", "한바탕했죠. 싸우고, 그다음에 사과했어요."),
(L, "C'est bien. Mais moi, je vais vous raconter comment on faisait avant.", "좋구나. 그런데 난 예전에 우리가 어떻게 했는지 이야기해 주마."),
(H, "Papa, on n'est plus en 1990. Il y a Internet, les réseaux, les avis en ligne.", "아빠, 지금은 1990년이 아니에요. 인터넷이 있고, SNS가 있고, 온라인 후기가 있어요."),
(L, "Justement. Ça, c'est nouveau. Mais les gens, eux, n'ont pas changé.", "그러니까. 그건 새로운 거지. 하지만 사람들은 바뀌지 않았어."),
(L, "Quand j'avais quarante ans, on n'avait pas de téléphone portable.", "내가 마흔 살 때는 휴대폰이 없었다."),
(C, "Pas de portable ? Mais comment on réservait ?", "휴대폰이 없다고요? 그럼 예약은 어떻게 했어요?"),
(L, "Par téléphone fixe ! Ta tante Marthe, je veux dire ta grand-mère, notait tout sur un grand registre.", "집 전화로! 네 할머니 마르트가 큰 장부에 전부 적었지."),
(H, "Chloé n'est pas ma fille, Papa. Elle n'a pas de grand-mère ici.", "클로에는 제 딸이 아니에요, 아빠. 여기엔 할머니 없어요."),
(L, "Ah oui, pardon. Je me mélange. Marthe, donc, notait tout sur un registre.", "아 맞다, 미안. 헷갈렸네. 아무튼 마르트가 장부에 전부 적었지."),
(J, "Et elle connaissait tous les clients ?", "그럼 마르트는 단골을 다 알고 있었나요?"),
(L, "Tous ! Elle savait leurs prénoms, leurs plats préférés, leurs soucis.", "전부! 이름도, 좋아하는 요리도, 걱정거리도 알았지."),
(L, "Chaque matin, je me levais à cinq heures pour aller au marché.", "매일 아침 나는 5시에 일어나 시장에 갔다."),
(L, "Je choisissais les légumes moi-même, je discutais avec les paysans.", "채소는 내가 직접 고르고, 농부들과 이야기를 나눴지."),
(H, "Je fais ça aussi, avec Bastide.", "저도 바스티드 씨랑 그렇게 해요."),
(L, "Bastide livre. Moi, je serrais les mains. Ce n'est pas pareil.", "바스티드는 배달하지. 난 악수를 했어. 그건 달라."),
(H, "Tu veux dire que je ne serre pas assez de mains ?", "제가 악수를 충분히 안 한다는 말씀이세요?"),
(L, "Je veux dire que tu restes trop en cuisine. Tes clients ne te connaissent plus.", "네가 주방에만 너무 오래 있다는 말이다. 손님들이 널 더는 모르잖니."),
(H, "J'ai un restaurant à faire tourner. Je n'ai pas le temps de papoter.", "저는 식당을 돌려야 해요. 수다 떨 시간이 없어요."),
(L, "Quand ta mère et moi avons ouvert en 1991, on n'avait pas le temps non plus.", "네 엄마와 내가 1991년에 문을 열었을 때도 시간이 없었다."),
(L, "Mais chaque service, elle sortait en salle trois fois. Trois fois, tu entends ?", "그래도 서비스마다 마르트는 홀에 세 번 나왔다. 세 번이야, 알겠니?"),
(C, "Pour dire quoi ?", "뭘 말하러요?"),
(L, "Bonjour. Ça va ? Ça vous plaît ? Et elle repartait. Rien de plus.", "안녕하세요. 잘 지내세요? 입맛에 맞으세요? 그러고 돌아갔지. 그게 다야."),
(J, "Trois phrases. Je les connais, ces trois phrases.", "문장 세 개. 그 세 문장은 저도 알아요."),
(L, "Oui, c'est toi qui les dis, depuis le premier jour. Elles sont à la maison.", "그래, 첫날부터 네가 하는 말이지. 그 말들은 이 집 거란다."),
(H, "D'accord, mais 1993, alors ? Tu m'as dit que 1993 était important.", "좋아요, 그럼 1993년은요? 1993년이 중요하다고 하셨잖아요."),
(L, "En 1993, il y a eu la crise. Nous avons perdu un tiers de nos clients en six mois.", "1993년에 불황이 왔다. 6개월 만에 손님의 3분의 1을 잃었지."),
(H, "Un tiers ? Tu ne me l'avais jamais dit.", "3분의 1이요? 한 번도 말씀 안 하셨잖아요."),
(L, "Tu avais quinze ans. On ne parle pas d'argent devant les enfants.", "너는 열다섯 살이었어. 아이들 앞에서 돈 얘기는 안 하는 법이지."),
(L, "Un soir, ta mère s'est assise dans la salle vide et elle a pleuré.", "어느 날 저녁 네 엄마가 빈 홀에 앉아서 울었다."),
(H, "Maman a pleuré ? Je n'ai jamais vu Maman pleurer.", "엄마가 울었다고요? 엄마 우는 걸 본 적이 없는데요."),
(L, "Une seule fois. Ensuite, elle a essuyé ses larmes et elle a dit : « Bon. On fait quoi ? »", "딱 한 번. 그러고는 눈물을 닦고 말했지. '자. 우리 뭘 하지?'"),
(C, "Et vous avez fait quoi ?", "그래서 뭘 하셨어요?"),
(L, "Nous avons d'abord réduit la carte. Un plat du jour, un seul, que ta mère adorait.", "먼저 메뉴를 줄였어. 오늘의 요리 하나, 네 엄마가 좋아하는 걸로."),
(J, "Un seul plat ? Et les clients n'ont pas protesté ?", "요리 하나요? 손님들이 항의하지 않았나요?"),
(L, "Au début, si. Puis ils ont compris : c'était toujours bon et toujours frais.", "처음엔 했지. 그러다 이해했어. 항상 맛있고 항상 신선했거든."),
(L, "Ensuite, on a invité les habitués à manger avec nous, le mardi soir.", "그다음엔 화요일 저녁에 단골들을 우리와 함께 식사하자고 초대했다."),
(H, "À manger avec vous ? Gratuitement ?", "같이 식사하자고요? 공짜로요?"),
(L, "Non, à prix fixe, mais très bas. Une grande table, une soupe, un rôti, un fromage.", "아니, 아주 싼 정액으로. 큰 식탁에 수프, 로스트, 치즈."),
(L, "Tout le monde parlait à tout le monde. Ça s'appelait « la tablée du mardi ».", "모두가 모두와 이야기했지. '화요일의 큰 식탁'이라고 불렀단다."),
(J, "Et ça a marché ?", "그래서 효과가 있었어요?"),
(L, "Au bout de six mois, la salle était pleine, même en semaine.", "6개월쯤 지나자 평일에도 홀이 가득 찼다."),
(L, "Les gens ne venaient pas seulement pour manger. Ils venaient pour être attendus.", "사람들은 먹으려고만 온 게 아니라 기다려 주는 사람이 있어서 왔어."),
(H, "Pour être attendus... Joli. Mais aujourd'hui, c'est différent, Papa.", "기다려 주는 사람이 있어서... 예쁜 말이네요. 하지만 지금은 달라요, 아빠."),
(L, "Qu'est-ce qui est différent ? Les gens ont toujours faim et ils sont toujours seuls.", "뭐가 다르니? 사람들은 여전히 배고프고 여전히 외롭다."),
(H, "Ils ont Instagram. Ils vont chez Victor pour la photo, pas pour être attendus.", "인스타그램이 있잖아요. 빅토르네엔 사진 때문에 가지, 기다려 주는 사람 때문에 가는 게 아니에요."),
(L, "Beaucoup, oui. Pas tous. Madame Vasseur n'y va pas pour la photo, elle.", "많이는 그렇지. 전부는 아니야. 바쉬르 부인은 사진 찍으러 가지 않는다."),
(J, "Elle y est allée mardi dernier, quand même. Pour surveiller, elle a dit.", "그래도 지난 화요일엔 갔었는데요. 감시하러 갔다고 하셨지만."),
(L, "Et elle est revenue ici le jeudi. Tu vois ? C'est ça, ma méthode.", "그리고 목요일에 다시 여기로 왔지. 봐라, 그게 내 방법이다."),
(H, "Ta méthode, c'est quoi, exactement ? Dis-moi en trois points.", "아빠의 방법이 정확히 뭐예요? 세 가지로 말해 보세요."),
(L, "Premièrement : on mange ensemble avant le service. Toute l'équipe, à la même table.", "첫째, 서비스 전에 다 같이 먹는다. 팀 전원이 같은 식탁에서."),
(C, "Le repas du personnel ? On le fait déjà, parfois.", "직원 식사요? 가끔 하긴 하는데요."),
(L, "Parfois, ce n'est pas assez. À mon époque, on mangeait à onze heures, chaque jour.", "가끔으론 부족해. 내 시절엔 매일 11시에 먹었다."),
(L, "Personne ne criait la bouche pleine. Ventre affamé n'a point d'oreilles, comme on dit.", "입에 음식 넣고 소리 지르는 사람은 없었지. 배고픈 배는 귀가 없다고들 하잖니."),
(J, "Il a raison. Samedi, on n'avait pas mangé depuis le matin.", "맞는 말씀이에요. 토요일에 우린 아침부터 아무것도 안 먹었어요."),
(H, "D'accord, point numéro un. Mais à onze heures, j'ai ma mise en place.", "좋아요, 첫 번째 항목. 그런데 11시엔 준비 작업이 있어요."),
(L, "Tu feras ta mise en place à dix heures. Tu es la patronne, tu t'organises.", "준비는 10시에 하면 돼. 네가 주인이니 알아서 짜렴."),
(H, "Deuxièmement ?", "두 번째는요?"),
(L, "Deuxièmement : tu sors en salle, trois fois par service. Comme ta mère.", "둘째, 서비스마다 홀에 세 번 나가라. 네 엄마처럼."),
(H, "Trois fois ? Avec le coup de feu ?", "세 번이요? 피크 시간에요?"),
(L, "Au début, une seule. Puis deux. Puis trois. Petit à petit, l'oiseau fait son nid.", "처음엔 한 번. 그다음 두 번. 그다음 세 번. 티끌 모아 태산이다."),
(J, "Je pourrais te dire quand sortir. Je te fais un signe quand une table est contente.", "언제 나가면 좋은지 내가 알려 줄게. 만족한 테이블이 있으면 신호할게."),
(H, "Un signe ? Quel signe ?", "신호요? 무슨 신호?"),
(J, "Je touche mon oreille. Facile, non ?", "내 귀를 만질게. 간단하죠?"),
(C, "Et si c'est mécontent, tu touches quoi ?", "그럼 불만이면 뭘 만져요?"),
(J, "Mon nez. Mais on ne va pas en avoir besoin, normalement.", "코. 하지만 보통은 필요 없을 거야."),
(L, "Troisièmement : je reviens m'asseoir au bar, le soir, comme avant.", "셋째, 저녁엔 예전처럼 내가 바에 앉으러 돌아온다."),
(H, "Papa, tu es à la retraite. Tu es censé te reposer.", "아빠, 은퇴하셨잖아요. 쉬셔야 해요."),
(L, "Je me suis reposé pendant trois ans, et je m'ennuie à mourir.", "3년 동안 쉬었더니 심심해 죽겠다."),
(L, "Au bar, je dirai bonsoir aux habitués. Je ne cuisine pas, je ne sers pas. J'écoute.", "바에서 단골들에게 인사할 거야. 요리도, 서빙도 안 하고, 들을 뿐이지."),
(H, "Tu vas critiquer mes plats à chaque service.", "아빠는 서비스마다 제 요리를 평하실 거잖아요."),
(L, "Peut-être un peu. Mais gentiment. Je n'ai jamais critiqué méchamment, moi.", "조금은. 하지만 다정하게. 난 못되게 평한 적은 없다."),
(J, "Lucien, il y a une chose que vous n'avez pas dite : le prix. Ça coûte combien, tout ça ?", "루시앙, 말씀 안 하신 게 있어요. 비용이요. 이 모든 게 얼마나 드는데요?"),
(L, "Presque rien. Un repas de personnel, c'est de la bouffe qu'on aurait jetée de toute façon.", "거의 안 든다. 직원 식사는 어차피 버렸을 음식이야."),
(H, "C'est vrai que les restes, on les jette trop souvent.", "맞아요, 남은 음식을 너무 자주 버리긴 해요."),
(C, "Et la tablée du mardi ? On pourrait l'essayer ?", "그리고 화요일 큰 식탁은요? 해 볼 수 있을까요?"),
(H, "Une table d'hôtes, ici ? Avec trente couverts ? Tu rêves.", "여기서 테이블 도트라고? 30명 규모로? 꿈꾸는 거야."),
(L, "Pas trente. Douze, la première fois. Autour de la grande table, au fond.", "30명은 아니고 처음엔 열두 명. 안쪽 큰 식탁에 둘러앉아서."),
(J, "Le mardi soir, on a peu de monde de toute façon. Ça ne coûtera pas grand-chose d'essayer.", "화요일 저녁은 어차피 손님이 적어요. 해 봐도 별로 손해는 없겠죠."),
(H, "Un seul plat, un seul prix. Dix-neuf euros, vin compris ?", "요리 하나에 가격도 하나. 와인 포함 19유로?"),
(L, "Vingt-deux, plutôt. Tes clients paieront pour être bien, pas pour être pas chers.", "22유로가 낫겠다. 네 손님들은 싼 데가 아니라 편한 데에 돈을 낸다."),
(H, "Hmm. Tu crois vraiment que ça peut marcher ?", "흠. 정말 통할 거라고 생각하세요?"),
(L, "Je ne le crois pas. Je le sais. Je l'ai vu marcher.", "생각하는 게 아니라 안다. 내가 성공하는 걸 봤으니까."),
(H, "Mais tu ne comprends pas, Papa. J'ai peur, moi.", "하지만 아빠는 이해 못 해요. 전 무서워요."),
(L, "De quoi ?", "뭐가?"),
(H, "De tout perdre. Du loyer. De Victor. De ne plus y arriver.", "전부 잃을까 봐요. 월세가요. 빅토르가요. 더 이상 못 해낼까 봐요."),
(L, "Moi aussi, j'avais peur en 1993. Ta mère me disait : « On a peur ensemble, c'est moins lourd. »", "나도 1993년에는 무서웠다. 네 엄마가 말했지. '같이 무서워하면 덜 무겁다.'"),
(H, "Elle disait ça ?", "엄마가 그렇게 말했어요?"),
(L, "Tout le temps. Elle disait aussi : « À chaque jour suffit sa peine. »", "항상. 이런 말도 했다. '하루의 괴로움은 그날로 족하다.'"),
(C, "C'est très beau. Je peux l'écrire dans mon carnet ?", "정말 멋진 말이에요. 제 수첩에 써도 돼요?"),
(L, "Écris-le, ma petite. Et lis-le quand tu es fatiguée.", "써라, 꼬마야. 그리고 피곤할 땐 읽어."),
(H, "D'accord, Papa. On essaie. Pendant deux semaines, pas plus.", "알겠어요, 아빠. 해 봐요. 2주만, 그 이상은 안 돼요."),
(L, "Deux semaines, c'est parfait. Et si ça ne marche pas, tu me renvoies à ma retraite.", "2주면 좋다. 그리고 안 되면 날 은퇴 생활로 돌려보내렴."),
(J, "Alors, on commence aujourd'hui ? Le repas du personnel à onze heures ?", "그럼 오늘부터 시작해요? 직원 식사는 11시에?"),
(H, "À onze heures. Mais c'est moi qui choisis le menu.", "11시에요. 하지만 메뉴는 제가 고를 거예요."),
(L, "Bien sûr. Et moi, je mets la table. Chloé, tu m'aides ?", "물론이지. 나는 상을 차리마. 클로에, 도와줄래?"),
(C, "Avec plaisir. Et je note : repas du personnel, trois sorties en salle, tablée du mardi.", "기꺼이요. 적어 둘게요. 직원 식사, 홀 세 번 나가기, 화요일 큰 식탁."),
(L, "Parfait. Et je note, moi, que ma fille m'a dit oui.", "좋다. 그리고 난 딸이 승낙했다고 적어 두마."),
(H, "J'ai dit « on essaie ». Ce n'est pas la même chose.", "'해 본다'고 했어요. 같은 말이 아니에요."),
(L, "Chez les Marchand, « on essaie », ça veut dire « oui ». Depuis toujours.", "마르샹 집안에서 '해 본다'는 '좋다'는 뜻이란다. 예전부터."),
(H, "Hmm. Et ces pêches, tu les as achetées pour qui ?", "흠. 그 복숭아는 누구 주려고 사셨어요?"),
(L, "Pour tout le monde. On en fera une tarte pour le repas de midi.", "모두를 위해서지. 점심 식사에 타르트를 만들자."),
(H, "Une tarte aux pêches ? Marthe en faisait une, avec un peu de thym.", "복숭아 타르트요? 엄마가 타임을 조금 넣어서 만드셨죠."),
(L, "Avec du thym et un peu de miel. Tu t'en souviens ?", "타임이랑 꿀을 조금 넣었지. 기억하니?"),
(H, "Je m'en souviens comme si c'était hier. On en mangeait chaque été.", "어제 일처럼 기억나요. 여름마다 먹었잖아요."),
(J, "Alors, pas de temps à perdre. Où sont les pêches ?", "그럼 시간 낭비할 틈 없죠. 복숭아 어디 있어요?"),
(L, "Dans le sac, mon garçon. Et lave-toi les mains d'abord.", "자루 안에 있다, 젊은이. 손부터 씻고."),
(C, "Je prends le thym dans le jardin de la terrasse. Il en reste un peu.", "테라스 화분에서 타임을 따 올게요. 조금 남아 있어요."),
(H, "Allez, au travail. Et Papa... merci d'être venu.", "자, 일해요. 그리고 아빠... 와 주셔서 고마워요."),
(L, "De rien, ma fille. C'est ma maison aussi.", "별말을. 이 집은 내 집이기도 하니까."),
]

VOCAB = [
("A2", "Avant / à l'époque", "예전에 / 그 시절에", "과거 회상의 신호. « À mon époque, on mangeait à onze heures. » imparfait와 같이 쓴다."),
("A2", "Se lever / se reposer", "일어나다 / 쉬다", "« Je me levais à cinq heures. » « Je me suis reposé pendant trois ans. » 대명동사 과거형."),
("A2", "Le marché / un paysan", "시장 / 농부", "« Je discutais avec les paysans. » 알리그르 시장은 파리 12구의 유명한 시장."),
("A2", "Tout le monde / chaque matin", "모두 / 매일 아침", "« Tout le monde parlait à tout le monde. » chaque + 단수 명사."),
("A2", "Un conseil de famille", "가족회의", "« On a un conseil de famille ? » 집안 중요 사안을 놓고 모여 의논하는 자리."),
("B1", "Il y a eu la crise.", "불황이 있었다", "passé composé로 일회적 사건을 말한다. « En 1993, il y a eu la crise. » 반대로 배경은 imparfait."),
("B1", "Réduire la carte", "메뉴를 줄이다", "22화의 주제. « Nous avons d'abord réduit la carte. » ↔ 반대: élargir la carte."),
("B1", "Le repas du personnel", "직원 식사", "영업 전 팀이 함께 먹는 식사. 한 식탁에서 먹으면 팀워크가 좋아진다고 여겨진다."),
("B1", "Au bout de six mois", "6개월쯤 지나서", "기간이 끝나는 시점. « Au bout de six mois, la salle était pleine. »"),
("B1", "Petit à petit, l'oiseau fait son nid.", "티끌 모아 태산", "속담. « Au début, une seule. Puis deux. Puis trois. Petit à petit... »"),
("B1", "Ventre affamé n'a point d'oreilles.", "굶주린 배는 귀가 없다", "속담. 배고픈 사람은 남의 말을 듣지 않는다는 뜻. 옛 문어체 'point' 를 써서 어르신들 말투를 나타낸다."),
("B1", "À chaque jour suffit sa peine.", "하루의 괴로움은 그날로 족하다", "속담. 마태복음에서 온 표현. 내일 걱정을 미리 하지 말라는 뜻."),
("B2", "Ça a bardé.", "분위기가 험악했다", "[구어] barder = 험악해지다. « Ça a bardé samedi. » ↔ 정중: Il y a eu une dispute sérieuse."),
("B2", "Être censé + 부정사", "~하게 되어 있다", "« Tu es censé te reposer. » 규칙·기대를 나타낸다. censé 는 항상 être 와 쓴다."),
("B2", "Papoter", "수다 떨다", "[구어] « Je n'ai pas le temps de papoter. » ↔ 정중: Je n'ai pas le temps de bavarder."),
("B2", "S'ennuyer à mourir", "심심해 죽겠다", "[구어] à mourir 는 과장. « Je m'ennuie à mourir. » ↔ 정중: Je m'ennuie beaucoup."),
("B2", "Une table d'hôtes", "(공동 식탁이 있는) 정식 식사", "한 식탁에서 정해진 메뉴로 함께 먹는 형식. « La tablée du mardi » 와 같은 계열."),
("B2", "À prix fixe", "정액 가격으로", "메뉴 가격을 고정한 방식. « Une grande table, un seul prix. »"),
("B2", "Être attendu", "기다림을 받다", "추상적 의미. « Ils venaient pour être attendus. » 단골이 환영받는 느낌."),
("B2", "Je m'en souviens comme si c'était hier.", "어제 일처럼 기억나요", "관용 표현. 과거 회상의 마무리에 자주 쓴다."),
("C1", "Avoir à voir avec", "~와 관련이 있다", "« Qu'est-ce que 1993 a à voir avec nous ? » 부정·의문에서 자주 쓴다."),
("C1", "Faire tourner un restaurant", "식당을 굴리다", "« J'ai un restaurant à faire tourner. » tourner = 잘 돌아가다."),
("C1", "Pas la même chose", "같은 일이 아니다", "« « On essaie », ce n'est pas la même chose. » 말의 뉘앙스를 따질 때."),
]

GRAM = [
("B1", "imparfait — 습관·배경 묘사", "« Je me levais à cinq heures. » « Marthe notait tout sur un registre. » « On mangeait à onze heures. » 과거에 반복되던 일과 상태는 imparfait 로 말한다. 신호 표현: avant, à l'époque, chaque matin, tout le temps."),
("B1", "passé composé — 일회적 사건", "« En 1993, il y a eu la crise. » « Nous avons perdu un tiers de nos clients. » « Elle a essuyé ses larmes et elle a dit... » 시작과 끝이 있는 단발 사건은 passé composé. 신호: un soir, une seule fois, ensuite."),
("B2", "imparfait vs passé composé — 한 문장 안에서", "« Quand j'avais quarante ans, on n'avait pas de portable. » 배경은 imparfait. « Un soir, ta mère s'est assise dans la salle vide et elle a pleuré. » 사건은 passé composé. 이야기의 틀은 imparfait, 줄거리는 passé composé."),
("B1", "대명동사의 복합과거", "« Elle s'est assise dans la salle vide. » « Je me suis reposé pendant trois ans. » être 로 활용하고 주어에 따라 과거분사가 일치한다. 여성: s'est assise, 남성: s'est assis."),
("B2", "비교·대조 — Bastide livre, moi je serrais les mains", "« Bastide livre. Moi, je serrais les mains. » 강세형 대명사(moi, toi)로 대조한다. 시제 차이(현재/imparfait)가 시대 차이를 보여 준다."),
("B2", "순서 표현 — premièrement / ensuite / puis", "« Premièrement : on mange ensemble. » « Deuxièmement : tu sors en salle. » « Ensuite, on a invité les habitués. » 계획·회상 모두에서 단계를 나눌 때 쓴다."),
("B2", "être censé / avoir beau / de toute façon", "« Tu es censé te reposer. » « De toute façon, on a peu de monde. » 구어에서 말을 정리할 때 자주 쓰는 부사구."),
]

READ = [
("리에종 — il y_a eu / ils_avaient", "« En 1993, / il y_a eu la crise. » y 와 a 사이를 이어 [i li ja y]. « Ils_avaient peur. » 의 [z] 연결도 놓치지 말자. 과거형 문장은 이야기 속도가 느리니 리에종이 부드럽게 이어져야 한다."),
("imparfait 어미 — -ait", "« Je me levais, / elle notait, / on mangeait » 에서 -ais, -ait, -aient 는 모두 [ɛ]. 어미를 길게 늘이지 말고 짧게 끝낸다. [œ] 가 아니라 [ɛ] 임에 주의."),
("비음 — marchand, temps, ensemble", "« Marchand » [maʁʃɑ̃], « temps » [tɑ̃], « ensemble » [ɑ̃sɑ̃bl]. 입을 크게 벌려 코로 소리를 내는 [ɑ̃]. « Ma fille » 와 « Mon fils » 의 비음 차이도 연습."),
("r — frère·frais·Marthe", "« Marthe » [maʁt], « frais » [fʁɛ], « crise » [kʁiz]. 목젖 근처에서 가볍게 마찰시키는 r. 자음 뒤에 오는 r (cr, fr) 도 놓치지 않고."),
("호흡 구간 — 회상 문장", "« Quand j'avais quarante ans, / on n'avait pas de téléphone portable. » 처럼 쉼표에서 숨을 쉰다. « Un soir, / ta mère s'est assise / dans la salle vide / et elle a pleuré. » 는 4덩어리로, 마지막에서 천천히."),
("억양 — 속담 낭독", "« Petit à petit, / l'oiseau fait son nid. » 는 두 박자로 끊고 끝을 내린다. « Ventre affamé / n'a point d'oreilles. » 도 같다. 속담은 리듬이 있어 외우기 쉽다."),
]

CULTURE = [
("1990년대 파리 비스트로의 방식", "휴대폰과 예약 앱이 없던 시절 비스트로는 전화 예약을 큰 장부에 적고, 주인이 단골의 이름과 취향을 외우는 것이 곧 서비스였다. 주인이 시장에 가서 악수하며 재료를 고르고, 하루 한 가지 plat du jour 를 내는 방식은 지금도 « bistrot de quartier » 의 이상으로 남아 있다."),
("직원 식사와 큰 식탁 문화", "프랑스 레스토랑에서는 영업 전 « repas du personnel » 를 팀이 함께 먹는 전통이 있다. 지방 여관의 « table d'hôtes » 는 낯선 사람들이 한 식탁에서 같은 메뉴로 식사하는 형식으로, 대화를 곁들이는 환대의 상징이다."),
]

META = dict(part=2, ep=27, part_label="제2부 Premières fissures · 여름", title_fr="La méthode de Lucien", title_ko="루시앙의 방식",
 place="Le Comptoir de Marthe, 8월 11일 화요일 (오전 9시, 영업 전)",
 chars="Lucien Marchand (창업자, 아버지) · Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버)",
 wine="1993년 불황을 넘긴 옛 방식(직원 식사, 홀에 나가기, 화요일 큰 식탁)을 아버지가 제안하고 엘렌이 2주 시험을 받아들인다.",
 focus="imparfait(습관·배경)와 passé composé(사건)의 대비, 과거 회상 표현, 속담, 단계 표현(premièrement…)",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제28화 « Soirée privée » : 8월 12일 수요일, 은퇴 파티 단체 예약 견적을 두고 협의가 시작된다.")
