# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, R = "Hélène", "Julien", "Chloé", "M. Roussel"
D = [
(None, "Mercredi 12 août, 15 h 30. Le service du midi est fini. À la table douze, M. Roussel, un client habitué, attend avec un café. Hélène et Julien s'assoient en face de lui.", "8월 12일 수요일 오후 3시 30분. 점심 서비스는 끝났다. 12번 테이블에서 단골손님 루셀 씨가 커피를 앞에 두고 기다린다. 엘렌과 쥘리앵이 맞은편에 앉는다."),
(R, "Merci de me recevoir entre deux services, madame Marchand.", "두 서비스 사이에 시간을 내 주셔서 감사합니다, 마르샹 씨."),
(H, "Je vous en prie. Julien m'a dit que vous aviez un projet.", "별말씀을요. 쥘리앵한테 계획이 있으시다고 들었어요."),
(R, "Oui. Mon collègue Gérard part à la retraite fin août. Trente-huit ans dans mon imprimerie !", "네. 동료 제라르가 8월 말에 은퇴해요. 우리 인쇄소에서 38년을 일했죠!"),
(J, "Gérard ? Le monsieur à la barbe blanche, qui prend toujours la blanquette ?", "제라르요? 흰 수염 기르시고 늘 블랑케트 드시는 분이요?"),
(R, "Lui-même ! Il vient ici tous les mercredis depuis l'époque de votre mère.", "바로 그분이에요! 어머님 때부터 수요일마다 여기 오셨죠."),
(H, "Je me souviens de lui. Il discutait de la sauce pendant des heures avec ma mère.", "기억나요. 어머니랑 소스 얘기를 몇 시간씩 하셨어요."),
(R, "C'est ça ! Alors voilà : je voudrais organiser sa fête de départ chez vous.", "맞아요! 그래서 말인데, 송별 파티를 이 가게에서 열고 싶습니다."),
(H, "Quand ça, et pour combien de personnes ?", "언제, 그리고 몇 분이에요?"),
(R, "Un samedi soir. Le 22 août, si c'est possible. On sera trente : famille, collègues, quelques clients.", "토요일 저녁이요. 가능하면 8월 22일. 서른 명이에요. 가족, 동료, 몇몇 거래처 분들."),
(J, "Je regarde le planning... Le 22, on n'a rien de réservé. Mais trente, c'est toute la salle.", "일정 볼게요... 22일은 예약이 없어요. 하지만 서른 명이면 홀 전체예요."),
(H, "Il faudrait privatiser le restaurant, monsieur Roussel.", "가게를 통째로 빌리셔야 해요, 루셀 씨."),
(R, "Privatiser ? Expliquez-moi, je ne connais pas bien ce mot.", "프리바티제요? 설명해 주세요, 그 말은 잘 몰라서요."),
(H, "On ferme au public. La salle est à vous seuls pour toute la soirée.", "일반 손님은 받지 않아요. 저녁 내내 홀이 선생님 일행만의 공간이 돼요."),
(R, "C'est exactement ce que je veux. Pourriez-vous me faire un devis ?", "제가 딱 원하던 겁니다. 견적서를 만들어 주실 수 있나요?"),
(H, "J'ai déjà préparé une proposition. Julien, tu l'as ?", "제안서를 이미 준비했어요. 쥘리앵, 갖고 있지?"),
(J, "La voici. Un menu en quatre temps, avec le café.", "여기 있어요. 커피까지 포함해서 네 코스 메뉴예요."),
(J, "D'abord l'apéritif : des gougères et des rillettes de sardine.", "먼저 아페리티프로 구제르와 정어리 리예트가 나가요."),
(H, "Ensuite une entrée de saison : tomates anciennes et fromage de chèvre frais.", "그다음은 제철 전채로 토마토 품종 모듬과 신선한 염소 치즈예요."),
(H, "Pour le plat, deux choix : la blanquette de veau ou le cabillaud rôti.", "메인은 두 가지 중 고르시면 돼요. 블랑케트 드 보 아니면 대구 구이."),
(R, "La blanquette ! La recette de Marthe, non ?", "블랑케트! 마르트 님 레시피 맞죠?"),
(H, "Oui, exactement la même. Et en dessert, une mousse au chocolat ou une crème brûlée.", "네, 똑같은 방식이에요. 디저트는 초콜릿 무스나 크렘 브륄레고요."),
(R, "Ça donne envie. Et le prix, à peu près ?", "군침이 도네요. 가격은 대략 어떻게 되죠?"),
(H, "55 € par personne, apéritif et café compris. Boissons en supplément.", "한 분당 55유로예요. 아페리티프와 커피 포함이고, 음료는 별도예요."),
(R, "Cinquante-cinq euros... Ça fait combien pour trente ?", "55유로... 서른 명이면 얼마죠?"),
(J, "Je calcule. Trente fois cinquante, ça fait 1 500. Et trente fois cinq, 150.", "계산해 볼게요. 30 곱하기 50은 1,500. 30 곱하기 5는 150."),
(J, "Donc 1 650 €, pour le menu seulement.", "그러니까 메뉴만 1,650유로예요."),
(R, "1 650 €. Et le vin, c'est en plus ?", "1,650유로. 와인은 따로고요?"),
(H, "Oui. Je vous propose un Sancerre blanc à 32 € la bouteille et un Brouilly à 28 €.", "네. 상세르 화이트는 한 병에 32유로, 브루이는 28유로로 제안드려요."),
(R, "Combien de bouteilles faut-il compter, selon vous ?", "몇 병이나 잡아야 할까요?"),
(H, "En général, une bouteille pour trois personnes. Donc dix : cinq blanc, cinq rouge.", "보통 세 명당 한 병이에요. 그러니 열 병, 화이트 다섯 병에 레드 다섯 병."),
(J, "Cinq fois 32, ça fait 160. Cinq fois 28, 140. Donc 300 € de vin.", "5 곱하기 32는 160. 5 곱하기 28은 140. 그러니 와인이 300유로예요."),
(R, "Et pour porter un toast à Gérard ?", "제라르를 위해 건배할 때는요?"),
(H, "Du crémant. Quatre bouteilles à 20 €, soit 80 €.", "크레망이요. 20유로짜리 네 병이면 80유로예요."),
(J, "Alors, en tout : 1 650 plus 300 plus 80. Ça fait 2 030 €.", "그러면 전부 1,650 더하기 300 더하기 80, 2,030유로예요."),
(R, "2 030 €... C'est un peu plus que mon budget.", "2,030유로... 제 예산보다 조금 많네요."),
(H, "Vous aviez prévu combien ?", "얼마를 생각하셨어요?"),
(R, "Environ 1 800 €. Et, franchement, j'ai regardé ailleurs.", "1,800유로쯤요. 솔직히 다른 곳도 알아봤어요."),
(R, "L'Atelier de Victor, en face, me propose 47 € par personne.", "맞은편 아틀리에 드 빅토르는 한 명당 47유로를 제안했어요."),
(None, "Julien serre les lèvres. Hélène reste calme, mais elle pose son stylo.", "쥘리앵이 입술을 꾹 다문다. 엘렌은 침착하지만 펜을 내려놓는다."),
(H, "47 €, c'est son droit. Mais qu'est-ce que ce menu comprend ?", "47유로, 그건 그쪽 자유죠. 그런데 그 메뉴에 뭐가 포함되죠?"),
(R, "Une entrée, un plat, un dessert. Pas d'apéritif, pas de café, un seul choix de plat.", "전채, 메인, 디저트요. 아페리티프도 커피도 없고 메인은 한 가지뿐이에요."),
(H, "Alors comparons. Chez nous, l'apéritif, le café et le choix du plat sont inclus.", "그럼 비교해 봐요. 저희는 아페리티프, 커피, 메인 선택이 다 포함돼요."),
(R, "C'est vrai. Mais 8 € de différence par personne, ça fait quand même 240 €.", "맞아요. 그래도 한 명당 8유로 차이면 합쳐서 240유로예요."),
(J, "Exactement 240 €. Vous calculez vite, monsieur Roussel.", "정확히 240유로네요. 계산이 빠르시네요, 루셀 씨."),
(R, "Je suis imprimeur : les chiffres, c'est mon métier.", "인쇄업자라서요. 숫자가 제 일이죠."),
(R, "Pourriez-vous faire un geste sur le prix ?", "가격에서 조금 배려해 주실 수 있을까요?"),
(H, "Sur le menu, non. Je cuisine tout moi-même, avec des produits frais.", "메뉴 값은 안 돼요. 저는 신선한 재료로 전부 직접 요리하거든요."),
(H, "Mais je peux faire un geste ailleurs. Laissez-moi réfléchir une minute.", "하지만 다른 데서 배려는 할 수 있어요. 잠깐만 생각해 볼게요."),
(J, "Pendant ce temps, vous reprendrez un café, monsieur Roussel ?", "그동안 커피 한 잔 더 드시겠어요, 루셀 씨?"),
(R, "Volontiers. Votre café est meilleur que celui de l'imprimerie !", "좋죠. 여기 커피가 우리 인쇄소 커피보다 낫네요!"),
(H, "Voilà ma proposition : le crémant, je vous l'offre. Les 80 €, je les enlève.", "제 제안은 이래요. 크레망은 제가 낼게요. 80유로는 빼 드릴게요."),
(R, "Vraiment ? Pour le toast de Gérard ?", "정말요? 제라르 건배용으로요?"),
(H, "Pour Gérard. Il mange notre blanquette depuis vingt ans. C'est la moindre des choses.", "제라르 씨를 위해서요. 20년 동안 우리 블랑케트를 드셨잖아요. 당연한 도리죠."),
(J, "Ça nous fait un nouveau total : 1 650 plus 300, donc 1 950 €.", "그러면 새 합계는 1,650 더하기 300, 1,950유로예요."),
(R, "1 950 €... On se rapproche de mon budget. J'accepte, mais à une condition.", "1,950유로... 예산에 가까워졌네요. 받아들이겠습니다, 한 가지 조건으로요."),
(H, "Laquelle ?", "어떤 조건이요?"),
(R, "Il faut que Gérard ne sache rien. C'est une surprise.", "제라르가 아무것도 몰라야 해요. 깜짝 파티거든요."),
(J, "Pas de problème, on a l'habitude des surprises. Il arrivera à quelle heure ?", "문제없어요, 깜짝 파티는 익숙해요. 그분은 몇 시에 도착하시나요?"),
(R, "À 20 heures. Les invités arrivent à 19 h 30 et se cachent derrière le bar.", "8시에요. 손님들은 7시 반에 와서 바 뒤에 숨어 있을 거예요."),
(H, "Derrière le bar ? Trente personnes ? Il vaut mieux les cacher dans la salle du fond.", "바 뒤에요? 서른 명이? 안쪽 홀에 숨기는 게 낫겠어요."),
(R, "Bonne idée. Et un détail : je voudrais passer des photos sur un mur.", "좋은 생각이에요. 그리고 하나 더, 벽에 사진을 틀고 싶어요."),
(H, "C'est possible, à condition que vous apportiez votre propre projecteur.", "가능해요. 프로젝터를 직접 가져오신다는 조건으로요."),
(R, "Pas de souci, j'en ai un à l'imprimerie. On installera tout l'après-midi.", "문제없어요, 인쇄소에 하나 있어요. 오후 내내 설치할게요."),
(J, "L'après-midi, c'est difficile. On installe les tables à 17 heures, pas avant.", "오후는 곤란해요. 테이블 세팅이 5시라서 그 전엔 안 돼요."),
(R, "D'accord, 17 h 30 alors. Pour le reste, qu'est-ce que vous me demandez ?", "알겠어요, 그럼 5시 반으로요. 나머지는 뭐가 필요하세요?"),
(H, "Trois choses. D'abord un acompte de trente pour cent sur le menu.", "세 가지예요. 먼저 메뉴 금액의 30퍼센트 선금이요."),
(J, "Trente pour cent de 1 650, ça fait 495 €.", "1,650유로의 30퍼센트는 495유로예요."),
(R, "495 €, et le reste ? Le solde, c'est pour quand ?", "495유로, 나머지는요? 잔금은 언제죠?"),
(J, "Le solde, c'est le soir même, à la fin du repas : 1 455 €.", "잔금은 당일 저녁, 식사가 끝날 때예요. 1,455유로요."),
(R, "1 950 moins 495... oui, 1 455. Le compte est bon. Et la deuxième chose ?", "1,950 빼기 495... 네, 1,455. 계산 맞네요. 두 번째는요?"),
(H, "Le nombre définitif de convives. Je veux le savoir au plus tard mardi 18.", "최종 인원이요. 늦어도 18일 화요일까지 알아야 해요."),
(R, "Mais s'il y a deux personnes de plus ? Ou deux de moins ?", "그런데 두 명이 늘거나 줄면요?"),
(H, "Deux de plus, c'est possible : 55 € chacun. Deux de moins, je facture quand même.", "두 명 늘어나는 건 괜찮아요, 한 명당 55유로. 줄어도 그만큼은 청구해요."),
(R, "Hmm. C'est normal, vous achetez les produits d'avance.", "음. 맞는 말씀이에요, 재료를 미리 사시니까요."),
(H, "Exactement. Troisième chose : les choix de plats et les allergies, pour mardi aussi.", "맞아요. 세 번째는 메인 선택과 알레르기인데, 이것도 화요일까지요."),
(R, "Il y a une personne végétarienne, et un collègue qui ne mange pas de gluten.", "채식하는 분이 한 명 있고, 글루텐을 못 드시는 동료가 있어요."),
(H, "Je ferai des légumes rôtis pour la première, et un dessert sans farine pour le second.", "한 분께는 구운 채소를, 다른 분께는 밀가루 없는 디저트를 준비할게요."),
(R, "Et pour Gérard, la blanquette, bien sûr. Il ne mangera rien d'autre.", "그리고 제라르는 당연히 블랑케트예요. 다른 건 안 먹을 거예요."),
(J, "On lui servira une double portion. C'est un grand jour pour lui.", "두 배로 담아 드릴게요. 그분께는 특별한 날이니까요."),
(R, "À quelle heure doit-on partir ? Les imprimeurs adorent faire la fête tard.", "몇 시까지 있어야 하죠? 인쇄 쪽 사람들은 늦게까지 노는 걸 좋아해서요."),
(H, "Jusqu'à minuit, pas plus. Le personnel doit encore ranger après.", "자정까지만요. 직원들이 그 뒤에 정리도 해야 하거든요."),
(R, "Minuit, c'est parfait. Alors, j'ai bien tout compris. Je signe ?", "자정이면 좋아요. 그럼 제가 다 이해한 것 같은데, 서명할까요?"),
(J, "Je vous envoie le devis ce soir par mail. Vous le signez, vous le renvoyez avec l'acompte.", "오늘 저녁 메일로 견적서를 보낼게요. 서명하셔서 선금과 함께 돌려보내 주세요."),
(R, "Entendu. Je vous le renvoie demain matin. Et merci, madame Marchand, pour le crémant.", "알겠습니다. 내일 아침에 돌려보낼게요. 크레망 감사합니다, 마르샹 씨."),
(H, "C'est un plaisir. Dites bonjour à Gérard de ma part... sans lui dire pourquoi !", "제가 기쁜걸요. 제라르 씨께 안부 전해 주세요. 이유는 말하지 말고요!"),
(R, "Promis. À bientôt, et à samedi 22 !", "약속해요. 곧 뵙겠습니다, 22일 토요일에 봬요!"),
(None, "M. Roussel sort. Hélène se laisse tomber sur une chaise et souffle. Chloé arrive de la cuisine avec un plateau de verres.", "루셀 씨가 나간다. 엘렌이 의자에 털썩 앉아 숨을 내쉰다. 클로에가 유리잔 쟁반을 들고 주방에서 나온다."),
(C, "Alors ? J'ai entendu des chiffres. Vous avez signé quelque chose ?", "어땠어요? 숫자 얘기가 들리던데요. 뭔가 계약하셨어요?"),
(J, "Presque. Trente couverts, le samedi 22, une fête de départ à la retraite.", "거의요. 22일 토요일, 서른 명, 은퇴 기념 파티야."),
(C, "Trente ! Toute la salle ! Et il faudra servir trente personnes en même temps ?", "서른 명이요! 홀이 꽉 차네요! 서른 명을 동시에 서빙해야 해요?"),
(H, "Oui. Et c'est ça qui m'inquiète. Sans Karim, je suis seule à la cuisine.", "응. 그게 걱정이야. 카림이 없으니 주방에 나 혼자잖아."),
(J, "Tu auras Sofiane. Il peut venir le 22, je l'ai déjà appelé.", "소피안이 있잖아. 22일에 올 수 있대, 내가 벌써 전화해 봤어."),
(H, "Tu l'as appelé avant même de savoir si le client signait ?", "고객이 서명할지도 모르는데 벌써 전화했다고?"),
(J, "Je connais M. Roussel. Quand il dit « j'aimerais », il veut déjà signer.", "루셀 씨를 알잖아. « 하고 싶은데요 »라고 말하면 이미 서명할 마음이야."),
(C, "Moi, je peux faire le service. Mais à trois dans la salle, ça va être juste.", "저는 서빙할 수 있어요. 하지만 홀에 세 명이면 빠듯할 거예요."),
(J, "Je chercherai une extra. Une étudiante de ton école, peut-être ?", "임시 서버를 구해 볼게. 네 학교 학생 중에서 어때?"),
(C, "Je connais quelqu'un de très sérieux. Je lui écris ce soir.", "아주 성실한 사람을 알아요. 오늘 저녁에 연락해 볼게요."),
(H, "Bon. Faisons le calcul de ce qu'il nous reste, après tous les frais.", "자. 모든 비용을 빼고 우리한테 뭐가 남는지 계산해 보자."),
(H, "Les courses : environ 500 €. Le vin que j'achète : 150 €. L'extra et Sofiane : 200 €.", "장보기 약 500유로. 내가 사는 와인 150유로. 임시 서버와 소피안 200유로."),
(J, "500 plus 150 plus 200, ça fait 850. Donc 1 950 moins 850 : il reste 1 100 €.", "500 더하기 150 더하기 200은 850. 그럼 1,950 빼기 850, 1,100유로가 남아."),
(C, "1 100 € pour une soirée ! C'est beaucoup, non ?", "하룻밤에 1,100유로요! 많은 거 아니에요?"),
(H, "Un samedi d'août normal, on fait trente-six couverts à 27 €. Ça fait 972 €.", "평범한 8월 토요일엔 36명에 27유로씩이야. 그러면 972유로지."),
(J, "Donc la soirée privée rapporte presque le double. Et sans stress de réservations.", "그러니까 프라이빗 행사가 거의 두 배를 벌어 줘. 예약 스트레스도 없고."),
(H, "Le double du chiffre, oui. Mais pas du travail. Tu veux voir la liste ?", "매출은 두 배지, 일은 그렇지 않아. 목록 볼래?"),
(J, "Je te fais confiance. Et puis 1 100 €, ça aide un peu pour le loyer d'octobre.", "널 믿어. 그리고 1,100유로면 10월 임대료에 조금은 도움이 되잖아."),
(H, "Le loyer d'octobre, c'est 1 400 € de plus chaque mois. Une soirée, ça ne suffit pas.", "10월 임대료는 매달 1,400유로가 더 나가. 하룻밤으론 부족해."),
(J, "Non, mais des soirées comme ça, on peut en vendre d'autres.", "그렇긴 한데, 이런 행사는 더 팔 수 있어."),
(H, "Tu penses à des mariages ? Des baptêmes ? Des anniversaires de bureau ?", "결혼식? 세례식? 회사 생일 파티?"),
(J, "Pourquoi pas ? On a trente places, une cuisine, et la blanquette de Marthe.", "안 될 것 없지. 서른 자리, 주방, 그리고 마르트 님의 블랑케트가 있잖아."),
(C, "Moi, je peux faire une petite brochure avec les photos de la salle !", "저는 홀 사진으로 작은 브로슈어를 만들 수 있어요!"),
(H, "Pas si vite. D'abord, réussissons le 22. Après, on verra.", "너무 서두르지 마. 먼저 22일을 성공시키자. 그다음에 보자."),
(J, "Tu me dis toujours ça, et tu as toujours une idée derrière la tête.", "항상 그렇게 말하면서 속으론 늘 구상이 있지."),
(H, "Possible. Écris le devis proprement, Julien. Total en gras, conditions en dessous.", "그럴지도. 견적서는 깔끔하게 써, 쥘리앵. 합계는 굵게, 조건은 아래에."),
(J, "Je le rédige ce soir : menu, prix, acompte, date limite, et heures de la soirée.", "오늘 저녁에 쓸게요. 메뉴, 가격, 선금, 마감일, 행사 시간까지."),
(C, "Je peux relire ? Je veux apprendre à écrire un devis.", "제가 읽어 봐도 돼요? 견적서 쓰는 법을 배우고 싶어요."),
(H, "Bonne idée. Un jour, tu auras ton propre restaurant. Autant savoir faire des devis.", "좋은 생각이야. 언젠가 네 식당을 열 테니 견적서쯤은 쓸 줄 알아야지."),
(C, "Mon propre restaurant ! Il faudra d'abord que je goûte la blanquette de Marthe.", "내 식당이라니! 그 전에 마르트 님의 블랑케트부터 맛봐야겠네요."),
(H, "Tu l'as déjà goûtée. Au mois de mai, tu en as repris deux fois.", "이미 먹어 봤잖아. 5월에 두 번이나 더 먹었는데."),
(C, "C'était si bon que j'ai oublié le goût. Il faut que je recommence.", "너무 맛있어서 맛을 잊어버렸어요. 다시 먹어 봐야 해요."),
(J, "Dans ce cas, samedi 22, à la fin du service, il restera sûrement une assiette.", "그렇다면 22일 토요일 서비스가 끝날 때 접시 하나쯤은 분명 남겠네."),
(H, "On verra. Maintenant, tout le monde au travail. Il y a le service du soir à préparer.", "두고 보자. 이제 다들 일하러 가. 저녁 서비스 준비해야 해."),
(C, "Oui, Chef ! Et vive Gérard et sa double portion !", "네, 셰프! 제라르 씨와 그분의 두 배 접시 만세!"),
]

VOCAB = [
("A2", "Un devis", "견적서", "« Pourriez-vous me faire un devis ? » 서비스 가격을 미리 적어 주는 문서. 서명하면 계약이 된다."),
("A2", "Compris / en supplément", "포함 / 추가", "« Apéritif et café compris. Boissons en supplément. » 가격 설명의 기본 표현. ↔ non compris, en plus."),
("A2", "Un acompte / le solde", "선금 / 잔금", "« Un acompte de trente pour cent. » « Le solde, c'est le soir même. » 행사 예약 때 두 단어가 짝으로 나온다."),
("A2", "Le compte est bon.", "계산이 맞아요.", "[구어] 금액이 정확할 때. ↔ 정중: Les chiffres sont exacts."),
("B1", "Privatiser (un restaurant)", "가게를 통째로 빌리다", "« Il faudrait privatiser le restaurant. » 일반 손님 없이 한 단체만 쓰는 것. 명사: la privatisation."),
("B1", "Un couvert", "식사 인원 한 명(1인분 세팅)", "« Trente couverts, c'est toute la salle. » 숫자로 손님 수를 셀 때. 같은 표현이 1부에서도 나왔다."),
("B1", "Faire un geste", "성의를 보이다, 조금 양보하다", "« Pourriez-vous faire un geste sur le prix ? » ↔ 정중: Pourriez-vous m'accorder une remise ? 부탁과 양보를 모두 부드럽게 한다."),
("B1", "Je vous l'offre.", "제가 대접할게요.", "« Le crémant, je vous l'offre. » 목적어 대명사 le + vous 의 어순 연습. 선물하듯 가격에서 빼 줄 때."),
("B1", "C'est la moindre des choses.", "당연한 도리예요.", "« Il mange notre blanquette depuis vingt ans. C'est la moindre des choses. » 상대의 감사를 가볍게 받을 때도 쓴다."),
("B1", "Au plus tard / au moins", "늦어도 / 적어도", "« Je veux le savoir au plus tard mardi 18. » 마감일을 말할 때."),
("B1", "Un convive", "(식사 자리의) 참석자", "« Le nombre définitif de convives. » 행사·연회에서 손님을 가리키는 격식 있는 단어."),
("B1", "On a l'habitude de...", "~에 익숙하다", "« On a l'habitude des surprises. » 숙련된 모습을 보여 줄 때."),
("B2", "À condition que + 접속법", "~라는 조건으로", "« C'est possible, à condition que vous apportiez votre propre projecteur. » 접속법 apportiez 에 주의. 비슷한 표현: pourvu que."),
("B2", "Il faut que + 접속법", "~해야 한다", "« Il faut que Gérard ne sache rien. » « Il faut que je recommence. » 의무·필요. savoir→sache, faire→fasse."),
("B2", "Je facture quand même.", "그래도 청구합니다.", "[구어] « Deux de moins, je facture quand même. » ↔ 정중: Le montant reste dû. 취소·인원 감소 조건을 말할 때."),
("B2", "Il reste... / ce qu'il nous reste", "남는 것", "« Ce qu'il nous reste, après tous les frais. » 비용을 빼고 남는 순수익을 말할 때. un reste de..."),
("B2", "Se rapprocher de", "~에 가까워지다", "« On se rapproche de mon budget. » 협상에서 서로의 입장이 좁혀질 때."),
("B2", "Serrer les lèvres", "입술을 꽉 다물다", "지문 표현. 불쾌감을 참을 때. 말은 안 하지만 표정으로 드러나는 장면."),
("B2", "Avoir une idée derrière la tête", "속으로 계획이 있다", "« Tu as toujours une idée derrière la tête. » ↔ 정중: Tu as toujours un projet en tête."),
("C1", "Facturer / une facture", "청구하다 / 청구서", "devis 에 서명하면 facture 가 따라온다. « Je facture » 는 금액을 청구한다는 뜻."),
("C1", "Autant + 부정사", "~하는 편이 낫다", "« Autant savoir faire des devis. » 어차피 해야 한다면 하는 게 낫다는 뉘앙스. 구어에서 자주 쓴다."),
]

GRAM = [
("A2", "가격·합계 말하기 — 곱셈과 덧셈", "« Trente fois cinquante, ça fait 1 500. » « 1 950 moins 495, 1 455. » fois(곱), plus(합), moins(차). 결과는 « ça fait » 나 « donc ». 한 번에 안 되면 쪼개서 계산한다."),
("A2", "인원·단가 — par personne", "« 55 € par personne. » « Une bouteille pour trois personnes. » par 는 '당', pour 는 '~를 위해/기준'. 단가 × 인원이 총액이 된다."),
("B1", "조건법 — 정중한 부탁과 제안", "« Pourriez-vous me faire un devis ? » « Il faudrait privatiser. » « Je voudrais organiser... » 조건법은 부탁·제안을 부드럽게 만든다. 손님 앞에서는 vous + 조건법이 기본이다."),
("B1", "직접·간접 목적어 대명사 — le/la/les + vous/lui", "« Le crémant, je vous l'offre. » « Je vous l'envoie ce soir. » « Dites bonjour à Gérard de ma part. » 어순은 주어 + 간접(vous) + 직접(l') + 동사. 둘 다 있으면 vous l' 순서다."),
("B2", "접속법 입문 — il faut que / à condition que", "« Il faut que Gérard ne sache rien. » « À condition que vous apportiez votre projecteur. » « Il faut que je recommence. » 접속법 현재: ils 형 어간 + -e, -es, -e, -ions, -iez, -ent. 불규칙: savoir→sache, faire→fasse, aller→aille."),
("B2", "조건 표현 — au plus tard / quand même / sauf si", "« Au plus tard mardi 18. » « Je facture quand même. » 마감과 예외를 정하는 표현은 계약 대화의 핵심이다. 같은 의미의 정중한 서면 표현: dernier délai, néanmoins."),
("B2", "비교 — plus que / un peu plus que / presque le double", "« C'est un peu plus que mon budget. » « Ça rapporte presque le double. » 비교는 plus/moins + 형용사 + que. 배수는 le double, le triple, la moitié."),
]

READ = [
("숫자 읽기 — 견적서 금액", "« 1 650 € » 는 mille six cent cinquante euros, « 1 950 € » 는 mille neuf cent cinquante euros. « 2 030 € » 는 deux mille trente euros. mille 뒤에서 숨을 한 번 쉬고 읽는다: mille / six cent cinquante. € 는 euros 로 읽고 s 는 연음 때만 소리가 난다 (cinq_euros)."),
("리에종 — vous_avez, quatre_ou_cinq", "« Vous avez prévu combien ? » 는 /vu.za.ve/ 로 s 가 z 로 이어진다. « Cinq_euros » 에서 q 는 /k/ 가 아니라 /sɛ̃k.ø.ʁo/ 로 읽는다. 장사 대화에서 자주 나오는 « trois_euros » 도 연음."),
("호흡 구간 — 긴 조건 문장", "« C'est possible, / à condition que vous apportiez / votre propre projecteur. » 쉼표에서 한 번, 조건절 앞에서 한 번 끊는다. « Le solde, / c'est le soir même, / à la fin du repas. » 도 세 구간."),
("r — Brouilly, crémant, projecteur", "프랑스어 r 은 목 안쪽에서 나는 /ʁ/. « crémant » /kʁe.mɑ̃/, « projecteur » /pʁɔ.ʒɛk.tœʁ/. 단어 끝 -eur 의 r 은 약하게 닿기만 한다. « Brouilly » 의 ou 는 /u/, ill 은 /j/ 로 /bʁu.ji/."),
("비음 — blanquette, cent, combien", "« blanquette » 의 an 은 /ɑ̃/, « combien » 의 om 은 /ɔ̃/, ien 은 /jɛ̃/. « Combien de personnes ? » 는 /kɔ̃.bjɛ̃.də.pɛʁ.sɔn/ 로 비음이 번갈아 나온다. 입을 벌려 비음을 또렷이 낸다."),
("억양 — 협상의 정중함", "« Pourriez-vous faire un geste sur le prix ? » 는 끝을 올리되 공손하게 부드럽게. « Sur le menu, non. » 는 내려서 단호하게. 같은 non 도 억양이 다르면 거절이 부드러워진다."),
]

CULTURE = [
("프랑스의 소규모 연회 — privatisation 과 devis", "프랑스 비스트로는 단체 손님을 받을 때 devis(견적서)를 서면으로 보내고, 서명과 acompte(선금)를 받고 나서 날짜를 확정한다. 인원 변동 마감일과 취소 조건이 서면에 들어가는 이유는 식재료를 미리 사기 때문이다. 이 장면의 « acompte 30 % » 는 흔한 관행이다."),
("은퇴 파티 — le pot de départ", "프랑스에서는 동료가 은퇴하거나 직장을 옮기면 « pot de départ » 를 연다. 회사에서 간단히 하기도 하지만, 오래 일한 사람에게는 식당에서 정식 만찬을 열기도 한다. 깜짝 파티(surprise-party)에서는 주인공 몰래 모두 먼저 도착해 숨는 것이 재미다."),
]

META = dict(part=2, ep=28, part_label="제2부 Premières fissures · 여름", title_fr="Soirée privée", title_ko="프라이빗 파티",
 place="Le Comptoir de Marthe, 8월 12일 수요일 오후 3시 30분 (점심과 저녁 서비스 사이)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · M. Roussel (인쇄소 사장, 단골손님) · Chloé Dubois (견습 서버)",
 wine="은퇴 파티 단체 예약 견적 협상. 30명 × 55 € = 1 650 € + 와인 300 € (크레망 80 €는 엘렌이 서비스) = 1 950 €.",
 focus="견적·가격 제시, 조건 협의, 조건법, 접속법 입문(il faut que, à condition que), 대명사 어순",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제29화 « Le doute de Julien » : 8월 18일 화요일. 파티를 일주일 앞두고, 줄리앙이 받은 뜻밖의 이직 제안이 팀에 그림자를 드리운다.")
