# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, C = "Hélène", "Lucien", "Julien", "Chloé"
D = [
(None, "Mardi 18 août, 8 h 10. La salle est vide. Julien, assis au comptoir, fixe son téléphone sans toucher à son café. La porte s'ouvre : c'est Lucien, avec son journal.", "8월 18일 화요일 오전 8시 10분. 홀은 비어 있다. 쥘리앵이 바에 앉아 커피엔 손도 안 대고 전화기만 쳐다본다. 문이 열리고 신문을 든 뤼시앵이 들어온다."),
(L, "Bonjour, mon garçon. Tu as la tête de quelqu'un qui a mal dormi.", "안녕, 젊은이. 잠을 설친 사람 얼굴이구나."),
(J, "Bonjour, Lucien. Un peu, oui. Je vous... je te sers un café ?", "안녕하세요, 뤼시앵. 조금요. 커피 드릴까요?"),
(L, "Volontiers. Mais d'abord, pose ton téléphone. Il ne va pas s'envoler.", "그러지. 그런데 먼저 전화기부터 내려놔. 날아가진 않을 테니."),
(J, "Pardon. J'attends un message. Enfin, non, j'attends pas vraiment.", "죄송해요. 메시지를 기다리고 있어서요. 아니, 실은 기다리는 건 아니고요."),
(L, "Quand on attend un message sans l'attendre, c'est un message très important.", "기다리지 않으면서 기다리는 메시지라면 아주 중요한 메시지지."),
(J, "Ha ! Vous avez... tu as toujours une phrase pour tout.", "하! 뤼시앵은 뭐든 한마디 하시네요."),
(L, "Je suis vieux, j'ai eu le temps d'en collectionner. Alors, qu'est-ce qui t'arrive ?", "늙었으니 모을 시간이 있었지. 그래서 무슨 일이냐?"),
(J, "Je peux vous parler en confiance ? Vous ne le répétez pas à Hélène ?", "믿고 말씀드려도 돼요? 엘렌한테는 말씀 안 하실 거죠?"),
(L, "Je suis son père, pas son espion. Mais je ne te promets rien sur le fond.", "나는 엘렌의 아버지지 첩자가 아니야. 하지만 내용에 대해선 약속 못 한다."),
(J, "C'est honnête. Voilà : j'ai reçu une proposition de travail.", "솔직하시네요. 사실은 일자리 제안을 받았어요."),
(L, "Une proposition ? Dans quel restaurant ?", "제안이라고? 어느 식당에서?"),
(J, "Chez Armand, dans le huitième. Une grande brasserie, soixante couverts le midi.", "8구에 있는 셰 아르망이요. 점심 60석짜리 큰 브라스리예요."),
(L, "Je connais, c'est près des Champs-Élysées. Armand Belloc, un homme sérieux. Et ils veulent quoi ?", "알지, 샹젤리제 근처. 아르망 벨록, 진지한 사람이야. 그래서 뭘 원하는데?"),
(J, "Un directeur de salle. Avec une équipe de dix personnes, et mille euros de plus par mois.", "홀 총괄이요. 팀원 열 명에 월급이 1,000유로 더 많고요."),
(L, "Mille euros ! Eh bien, mon garçon, c'est une jolie somme.", "1,000유로라니! 이런, 큰 금액이구나."),
(J, "Oui, c'est ça le problème. Elle est trop jolie.", "네, 그게 문제예요. 너무 큰 금액이라서요."),
(L, "Comment a-t-il fait pour te trouver ? On ne trouve pas un bon directeur de salle sous un caillou.", "그 사람은 어떻게 널 찾았지? 좋은 홀 총괄이 돌 밑에 있는 것도 아닌데."),
(J, "Il était déjà venu ici. Il y a deux semaines, un mardi midi. Il avait pris la table quatre, seul.", "여기 와 본 적이 있어요. 2주 전 화요일 점심에요. 혼자 4번 테이블에 앉았죠."),
(J, "J'avais remarqué qu'il regardait tout : les assiettes, mes gestes, même la façon d'accueillir.", "그가 전부 지켜보는 걸 눈치챘어요. 접시, 제 몸짓, 손님 맞는 방식까지요."),
(L, "Tu as cru que c'était un critique gastronomique ?", "미식 평론가인 줄 알았니?"),
(J, "Oui ! J'avais même mis un gâteau en plus sur sa table. Et il m'a laissé sa carte.", "네! 디저트까지 하나 더 놓았어요. 그랬더니 명함을 남기고 갔죠."),
(L, "Ha ha ! Tu as payé son dessert, et il t'offre un poste. C'est du bon commerce.", "하하! 네가 디저트를 내고 그가 일자리를 주는 거네. 좋은 장사야."),
(J, "Il m'a rappelé la semaine dernière. Il veut une réponse avant le 15 septembre.", "지난주에 다시 전화했어요. 9월 15일 전에 답을 달래요."),
(L, "Et à partir de quand tu commencerais ?", "그리고 언제부터 시작하는 거니?"),
(J, "Le 1er octobre. Pile le jour où le loyer d'Hélène augmente.", "10월 1일요. 하필 엘렌네 임대료가 오르는 날이에요."),
(L, "Hum. Le hasard aime les ironies.", "흠. 우연은 반어를 좋아하지."),
(J, "J'ai honte, Lucien. J'ai pensé tout de suite à l'argent, avant de penser à elle.", "부끄러워요, 뤼시앵. 엘렌보다 돈 생각이 먼저 났어요."),
(L, "Il n'y a pas de honte à avoir envie de gagner mieux sa vie. Tu as trente-trois ans.", "돈을 더 벌고 싶어 하는 건 부끄러운 게 아니야. 서른셋이잖니."),
(J, "Je voudrais acheter un appartement un jour. Ici, je n'y arriverai jamais.", "언젠가 집을 사고 싶어요. 여기서는 절대 못 사겠죠."),
(L, "Je vais te raconter une histoire. En 1991, un restaurateur de Lyon m'avait proposé de devenir chef chez lui.", "이야기 하나 해 주마. 1991년에 리옹의 식당 주인이 자기 집 주방장이 되라고 제안했었지."),
(J, "Vous... Tu as failli partir ?", "가실 뻔하셨어요?"),
(L, "J'avais reçu la lettre un lundi. Je n'avais rien dit à Marthe pendant trois semaines.", "편지를 월요일에 받았어. 3주 동안 마르트에게 한마디도 안 했지."),
(J, "Et elle l'a découvert comment ?", "그걸 마르트 님이 어떻게 알았어요?"),
(L, "Elle avait trouvé la lettre dans ma veste, en faisant la lessive. Elle ne s'est pas fâchée.", "빨래하다가 내 외투에서 편지를 찾았지. 화내진 않았어."),
(L, "Elle m'a dit : « Si tu veux partir, pars. Mais dis-le-moi en face. »", "그러더구나. « 가고 싶으면 가요. 하지만 내 앞에서 말해요. »"),
(J, "Et vous êtes resté.", "그리고 남으셨군요."),
(L, "Oui, mais pas par obligation. Parce qu'en la regardant, j'avais compris ce que je voulais vraiment.", "그래, 하지만 의무 때문은 아니었어. 그녀를 보며 내가 정말 원하는 걸 알게 됐거든."),
(L, "Retiens ça : parle à Hélène avant qu'elle l'apprenne autrement.", "이것만 기억해라. 엘렌이 다른 경로로 알기 전에 직접 얘기해."),
(J, "Je sais. Mais avec le loyer, la banque, la salle à moitié vide... Je lui ajoute un souci de plus.", "알아요. 하지만 임대료에 은행에 텅 빈 홀까지... 걱정을 하나 더 얹는 거잖아요."),
(L, "Un souci qu'on cache grossit. Un souci qu'on partage rapetisse. C'est un proverbe de ma façon.", "숨긴 걱정은 커지고 나눈 걱정은 작아진다. 내가 만든 속담이야."),
(J, "Et si je doute encore le 15 septembre ?", "9월 15일에도 여전히 망설이면요?"),
(L, "Alors décide quand même. Un mauvais choix vaut mieux qu'un doute éternel.", "그래도 결정해라. 나쁜 선택이 끝없는 의심보다 낫다."),
(J, "Facile à dire. Toi, tu as choisi le bon.", "말은 쉽죠. 뤼시앵은 좋은 쪽을 고르셨잖아요."),
(None, "On entend la clé dans la porte. Chloé entre, un sac de cours sur l'épaule, et s'arrête en les voyant.", "문에서 열쇠 소리가 난다. 가방을 멘 클로에가 들어와 둘을 보고 멈춰 선다."),
(C, "Bonjour ! Oh... vous avez l'air de parler de quelque chose de sérieux.", "안녕하세요! 어... 뭔가 진지한 얘기 중인 것 같네요."),
(J, "Mais non, mais non. On parlait de la météo.", "아니야, 아니야. 날씨 얘기 중이었어."),
(L, "Un peu de météo, un peu de poésie. Va te changer, Chloé.", "날씨 얘기랑 시 얘기를 조금 했지. 옷 갈아입고 오렴, 클로에."),
(None, "Chloé hésite, puis part vers les vestiaires. Lucien se lève avec son journal.", "클로에는 머뭇거리다가 탈의실로 간다. 뤼시앵이 신문을 들고 일어선다."),
(L, "Je vais voir Hélène en cuisine. Je ne dirai rien. Mais ne tarde pas trop, Julien.", "주방에 엘렌 보러 간다. 아무 말도 안 할 거야. 하지만 너무 미루지 마라, 쥘리앵."),
(J, "Merci, Lucien. Je lui parlerai avant la fin du service. Promis.", "고마워요, 뤼시앵. 서비스 끝나기 전에 말씀드릴게요. 약속해요."),
(None, "11 h 45. Chloé installe les couverts. Julien répond au téléphone derrière le bar, à voix basse.", "오전 11시 45분. 클로에가 수저를 놓는다. 쥘리앵은 바 뒤에서 낮은 목소리로 통화한다."),
(J, "Oui, monsieur Belloc... Non, je n'ai pas encore décidé. J'ai besoin de quelques jours.", "네, 벨록 씨... 아니요, 아직 결정 못 했어요. 며칠이 필요합니다."),
(J, "Bien sûr, je comprends. Merci d'être patient. Au revoir.", "물론 이해합니다. 기다려 주셔서 감사해요. 안녕히 계세요."),
(C, "C'était Chez Armand, non ? Je suis désolée, je n'écoutais pas, mais j'ai entendu le nom.", "셰 아르망이죠? 죄송해요, 엿들은 건 아닌데 이름이 들렸어요."),
(J, "Tu n'as rien entendu, Chloé. Compris ?", "넌 아무것도 못 들었어, 클로에. 알았지?"),
(C, "Bien sûr. Mais je ne suis pas idiote. Ils t'ont proposé un travail ?", "물론이죠. 하지만 저 바보 아니에요. 일자리를 제안했어요?"),
(J, "Oui. Un poste de directeur de salle, dans le huitième. Mille euros de plus.", "응. 8구에서 홀 총괄 자리야. 1,000유로 더 받고."),
(C, "Mille euros ! Moi, je dirais oui tout de suite.", "1,000유로요! 저라면 바로 하겠다고 할 거예요."),
(J, "Merci, ça m'aide beaucoup.", "고마워, 정말 도움이 되네."),
(C, "Non, attends, je ne voulais pas dire ça. Je veux dire... si tu pars, je reste avec qui ?", "아니, 잠깐만요, 그런 뜻이 아니라... 선배가 가면 전 누구랑 있어요?"),
(J, "Avec Hélène. Et avec une nouvelle équipe, peut-être.", "엘렌이랑. 그리고 아마 새 팀원들이랑."),
(C, "C'est toi qui m'as appris à tenir un plateau. Même à sourire quand un client crie.", "쟁반 드는 법도 선배가 가르쳐 줬어요. 손님이 소리쳐도 웃는 법까지요."),
(J, "Tu t'étais déjà bien débrouillée toute seule.", "넌 혼자서도 이미 잘하고 있었어."),
(C, "Menteur. En avril, j'avais renversé un pichet sur les genoux d'un monsieur.", "거짓말쟁이. 4월에 아저씨 무릎에 피처를 엎었잖아요."),
(J, "Et il m'avait demandé ton numéro pour t'engager chez lui ! Il avait beaucoup ri.", "그 손님이 널 자기 가게에 데려가려고 번호를 물었지! 엄청 웃으셨어."),
(C, "Quand même. Réfléchis bien. Et ne pars pas sans me dire au revoir.", "그래도요. 잘 생각해 보세요. 그리고 인사도 없이 가진 마세요."),
(J, "Je ne suis pas encore parti, Chloé. Allez, retourne à tes verres. Les clients arrivent dans dix minutes.", "아직 안 갔어, 클로에. 자, 잔 닦으러 가. 손님이 10분 후면 와."),
(None, "15 h 20. Le dernier client du déjeuner est parti. Hélène sort de la cuisine en s'essuyant les mains. Julien l'attend près de la table sept.", "오후 3시 20분. 점심 마지막 손님이 갔다. 엘렌이 손을 닦으며 주방에서 나온다. 쥘리앵이 7번 테이블 곁에서 기다린다."),
(H, "Mon père m'a dit que tu voulais me parler. Il avait l'air d'un homme qui garde un secret.", "아버지가 너 나한테 할 말 있다고 하시더라. 비밀 지키는 사람 표정이던데."),
(J, "Assieds-toi, Hélène. C'est un peu long à expliquer.", "앉아, 엘렌. 설명이 좀 길어."),
(H, "Tu me fais peur. Quelqu'un est malade ? Tu es malade ?", "무섭게 왜 이래. 누가 아파? 너 아픈 거야?"),
(J, "Non, personne n'est malade. J'ai reçu une offre d'emploi. Chez Armand, dans le huitième.", "아니, 아픈 사람 없어. 일자리 제안을 받았어. 8구의 셰 아르망에서."),
(None, "Hélène ne répond pas tout de suite. Elle regarde ses mains, puis la fenêtre.", "엘렌은 바로 대답하지 않는다. 자기 손을 보다가 창밖을 본다."),
(H, "Chez Armand. Je vois. C'est une belle maison.", "셰 아르망. 그렇구나. 좋은 가게지."),
(J, "Ils me proposent le poste de directeur de salle, avec dix personnes à gérer.", "홀 총괄 자리를 제안했어. 열 명을 관리하는 거고."),
(H, "Et combien ?", "그래서 얼마인데?"),
(J, "Mille euros de plus par mois. Je suis désolé de te le dire comme ça.", "한 달에 1,000유로 더. 이렇게 말해서 미안해."),
(H, "Ne sois pas désolé. Tu n'as rien fait de mal.", "미안해하지 마. 넌 잘못한 거 없어."),
(H, "C'est moi qui ne peux pas te payer ça. Même en rêve.", "그만큼 못 주는 건 나야. 꿈에서라도 못 줘."),
(J, "Je ne te demande pas de me payer plus. Je voulais que tu l'apprennes par moi.", "더 달라는 얘기 아니야. 네가 나한테서 직접 듣게 하고 싶었어."),
(H, "Merci. Ça compte beaucoup. Depuis quand tu le sais ?", "고마워. 그게 큰 의미가 있어. 언제부터 알고 있었어?"),
(J, "Depuis jeudi dernier. J'ai attendu parce que je ne voulais pas t'ajouter un souci.", "지난 목요일부터. 걱정을 더하기 싫어서 기다렸어."),
(H, "Et mon père, il le savait ?", "아버지는 알고 계셨어?"),
(J, "Je lui en ai parlé ce matin. Il m'a conseillé de te le dire aujourd'hui.", "오늘 아침에 말씀드렸어. 오늘 너한테 말하라고 조언하셨고."),
(H, "Il aurait pu me le dire lui-même, ce vieux renard.", "직접 말해 주실 수도 있었는데, 그 능구렁이."),
(J, "Il a refusé. Il m'a répondu qu'il n'était pas ton espion.", "거절하셨어. 자기는 네 첩자가 아니라고 하시더라."),
(H, "Un souci de plus, ça ne change plus grand-chose. J'en ai déjà tellement.", "걱정 하나 더 느는 건 이제 별로 달라질 게 없어. 이미 너무 많거든."),
(J, "Justement. Je me sens comme un rat qui quitte le bateau, tu comprends ?", "그러니까요. 나는 침몰하는 배를 버리는 쥐 같은 기분이야, 알겠어?"),
(H, "Non. Un rat qui quitte le bateau, c'est quelqu'un qui n'avait pas de loyauté. Toi, tu en as trop.", "아니. 배를 버리는 쥐는 의리 없는 사람이야. 넌 의리가 너무 많아."),
(J, "C'est gentil. Mais je ne sais toujours pas quoi faire.", "고마워. 하지만 여전히 어떻게 해야 할지 모르겠어."),
(H, "Quand dois-tu répondre ?", "언제까지 답해야 해?"),
(J, "Avant le 15 septembre. Il voudrait que je commence le 1er octobre.", "9월 15일 전에. 10월 1일에 시작하길 원해."),
(H, "Le 15 septembre. C'est dans quatre semaines. Tu as le temps de réfléchir.", "9월 15일. 4주 뒤네. 생각할 시간은 있어."),
(J, "Et toi, que ferais-tu à ma place ?", "너라면 내 입장에서 어떻게 하겠어?"),
(H, "Je n'ai pas le droit de répondre. Je serais juge et partie.", "내가 대답할 자격은 없어. 심판이면서 당사자가 되잖아."),
(J, "Dis-moi quand même ce que tu ressens.", "그래도 네 기분은 말해 줘."),
(H, "Franchement ? J'ai envie de te supplier de rester. Et en même temps, je trouve ça injuste.", "솔직히? 남아 달라고 빌고 싶어. 동시에 그게 불공평하다는 생각도 들어."),
(J, "Injuste pour qui ?", "누구한테 불공평해?"),
(H, "Pour toi. Tu es le meilleur directeur de salle que j'aie jamais vu. Tu mérites plus que mon petit bistrot.", "너한테. 네가 내가 본 최고의 홀 매니저야. 내 작은 비스트로보다 더 받을 자격이 있어."),
(J, "Ton petit bistrot, c'est aussi ma maison depuis trois ans.", "네 작은 비스트로는 3년 동안 내 집이기도 했어."),
(H, "Je sais. Et c'est pour ça que ça me fait mal.", "알아. 그래서 마음이 아픈 거야."),
(J, "Ce n'est pas seulement l'argent, tu sais. J'aimerais avoir quelque chose à moi, un jour.", "돈만의 문제는 아니야. 언젠가 내 것이라 부를 수 있는 걸 갖고 싶어."),
(H, "Quelque chose à toi ? Un restaurant ?", "네 것이라니? 식당 말이야?"),
(J, "Je ne sais pas. Un projet, une part, quelque chose. Chez Armand, je resterai toujours un salarié.", "모르겠어. 프로젝트나 지분이나 뭐든. 셰 아르망에서는 계속 직원일 거야."),
(H, "Hum. Je prends note de ça. Ce n'est pas ce que j'avais en tête.", "흠. 그건 메모해 둘게. 내가 생각하던 바가 아니었어."),
(J, "Ne prends rien en note ! Ça m'a échappé.", "메모하지 마! 말이 튀어나온 거야."),
(H, "Trop tard. Tu viens de m'ouvrir une porte.", "너무 늦었어. 방금 나한테 문을 열어 줬는걸."),
(None, "Le téléphone de Julien vibre sur la table. Le nom « Armand » s'affiche. Les deux le regardent.", "쥘리앵의 전화기가 테이블 위에서 진동한다. « 아르망 »이라는 이름이 뜬다. 두 사람이 그것을 쳐다본다."),
(H, "Réponds. Je ne vais pas te manger.", "받아. 잡아먹지 않을 테니까."),
(J, "Non. Pas maintenant. Pas devant toi.", "아니. 지금은 아니야. 네 앞에서는 안 돼."),
(H, "Alors laisse sonner. Mais tu devras le rappeler.", "그럼 울리게 둬. 하지만 다시 전화는 해야 해."),
(J, "Je sais. Je lui dirai que j'ai besoin d'un peu plus de temps.", "알아. 시간이 조금 더 필요하다고 말할 거야."),
(H, "Fais ce qu'il faut. Mais promets-moi une chose.", "필요한 대로 해. 대신 한 가지만 약속해 줘."),
(J, "Laquelle ?", "뭔데?"),
(H, "Quoi que tu décides, dis-le-moi en face. Comme aujourd'hui.", "뭘 결정하든 내 앞에서 말해 줘. 오늘처럼."),
(J, "Promis. En face, jamais par SMS.", "약속해. 얼굴 보고 할게, 절대 문자로는 안 해."),
(H, "Et maintenant, retournons au travail. Il y a six couverts pour le dîner à préparer.", "자, 이제 일하러 가자. 저녁 6명 예약을 준비해야 해."),
(J, "Six couverts. Un mardi d'août. Tu vois pourquoi je doute ?", "6명이라니. 8월 화요일에. 내가 왜 흔들리는지 알겠지?"),
(H, "Je vois. Mais six couverts avec toi valent mieux que soixante sans moi.", "알겠어. 하지만 너랑 있는 6명이 나 없이 60명 있는 것보다 나아."),
(J, "Tu dis ça pour me faire rester.", "나 붙잡으려고 하는 말이지."),
(H, "Non. Je te le dis parce que je le pense. Ça ne veut pas dire que tu dois rester.", "아니. 진짜로 그렇게 생각해서 하는 말이야. 그렇다고 네가 남아야 한다는 뜻은 아니야."),
(None, "Julien se lève, remet le téléphone dans sa poche. Il ne l'a pas rappelé. Chloé, au fond de la salle, fait semblant de ranger des serviettes.", "쥘리앵이 일어나 전화기를 주머니에 넣는다. 아직 다시 걸지 않았다. 홀 끝에서 클로에가 냅킨을 정리하는 척한다."),
(C, "Julien ? La table douze demande l'addition. Tu viens ?", "줄리앙? 12번 테이블이 계산서를 달래요. 올래요?"),
(J, "J'arrive. Hélène... merci de ne pas m'avoir jeté dehors.", "갈게. 엘렌... 날 쫓아내지 않아 줘서 고마워."),
(H, "Va vite. Et Julien ? Un mille euros, ça se négocie aussi, tu sais.", "빨리 가. 그리고 쥘리앵? 1,000유로도 협상할 수 있다는 거 알지."),
(J, "Négocier avec toi ? Tu n'as pas les moyens, Hélène.", "너랑 협상을 한다고? 네겐 그럴 여력이 없잖아, 엘렌."),
(H, "Pas aujourd'hui. Pas encore.", "오늘은 아니지. 아직은."),
(None, "Julien sourit à moitié, sans répondre. Il disparaît vers la table douze. Hélène reste seule, les yeux sur la table sept.", "쥘리앵은 반쯤 웃고는 대답하지 않는다. 12번 테이블 쪽으로 사라진다. 엘렌은 혼자 남아 7번 테이블을 바라본다."),
]

VOCAB = [
("A2", "Une proposition de travail", "일자리 제안", "« J'ai reçu une proposition de travail. » 구인이 아니라 스카우트 제안. 비슷한 표현: une offre d'emploi."),
("A2", "Avoir mal dormi", "잠을 설치다", "« Tu as la tête de quelqu'un qui a mal dormi. » 아침 얼굴을 묘사하는 구어."),
("A2", "Mille euros de plus par mois", "한 달에 1,000유로 더", "« De plus » 는 '더 많은'. 급여 비교 때 흔히 쓴다. « Moins de... » 는 반대."),
("A2", "Promis !", "약속해!", "[구어] 짧게 약속할 때. ↔ 정중: Je vous le promets."),
("B1", "Parler en confiance", "믿고 말하다", "« Je peux vous parler en confiance ? » 비밀을 털어놓기 전에 쓰는 말. 비슷한: entre nous."),
("B1", "Un directeur de salle", "홀 총괄(매니저)", "레스토랑에서 서비스 팀 전체를 책임지는 직책. Julien의 직함인 « responsable de salle » 와 거의 같다."),
("B1", "Pile le jour où...", "하필 ~하는 날에", "[구어] « Pile le jour où le loyer d'Hélène augmente. » pile 은 '정확히'. ↔ 정중: Précisément le jour où..."),
("B1", "Laisser sonner", "(전화가) 울리게 두다", "« Alors laisse sonner. » 받지 않기로 할 때. ↔ décrocher(받다), raccrocher(끊다)."),
("B1", "Un souci de plus", "걱정 하나 더", "« Je lui ajoute un souci de plus. » 걱정이 쌓이는 상황. 같은 구조: une tasse de plus, un jour de plus."),
("B1", "Dire en face", "면전에서 말하다", "« Dis-le-moi en face. » 뒤에서 몰래가 아니라 직접 말하라는 뜻. ↔ dans le dos(뒤에서)."),
("B2", "Le plus-que-parfait", "대과거 (avoir/être 의 반과거 + 과거분사)", "« Il avait pris la table quatre. » « Je n'avais rien dit à Marthe. » 과거의 어느 시점보다 먼저 일어난 일을 말할 때."),
("B2", "Juge et partie", "심판이자 당사자", "« Je serais juge et partie. » 이해관계가 걸려 있어 공정하게 판단할 수 없다는 법률 기원의 표현."),
("B2", "Un rat qui quitte le bateau", "침몰하는 배를 버리는 쥐", "위기에서 먼저 도망치는 사람을 가리키는 비유. « Je me sens comme un rat qui quitte le bateau. »"),
("B2", "Quoi que tu décides", "네가 무엇을 결정하든", "« Quoi que tu décides, dis-le-moi en face. » quoi que + 접속법. « quoique » (비록 ~일지라도)와 헷갈리지 말 것."),
("B2", "Ça m'a échappé.", "저도 모르게 말이 나왔어요.", "[구어] 비밀이나 속마음이 입 밖으로 나왔을 때. ↔ 정중: Je n'aurais pas dû le dire."),
("B2", "Prendre en note / noter", "메모해 두다", "« Je prends note de ça. » 상대의 말을 마음에 새기겠다는 뜻. 업무 대화에서 자주 쓴다."),
("B2", "Garder un secret", "비밀을 지키다", "« Il avait l'air d'un homme qui garde un secret. » 표정으로 비밀을 알아챌 때."),
("B2", "Se débrouiller", "알아서 잘 해내다", "« Tu t'étais déjà bien débrouillée toute seule. » 칭찬으로 자주 쓴다. 구어에서 « Débrouille-toi ! » 는 '알아서 해'."),
("B2", "Failli + 부정사", "하마터면 ~할 뻔하다", "« Tu as failli partir ? » faillir 는 보통 passé composé 로 쓴다. 이루어지지 않은 일에 쓴다."),
("C1", "Ouvrir une porte", "문을 열어 주다 (가능성을 보이다)", "« Tu viens de m'ouvrir une porte. » 비유적으로 새로운 가능성을 제시한다는 뜻."),
("C1", "Le hasard aime les ironies.", "우연은 반어를 좋아한다.", "Lucien 스타일의 경구. 우연히 겹친 사건을 인생의 아이러니로 말한다."),
("C1", "Un souci qu'on cache grossit.", "숨긴 걱정은 커진다.", "Lucien 의 즉흥 속담. 구문: 관계대명사 qu' 로 souci 를 꾸미는 짧은 격언 형태."),
]

GRAM = [
("B1", "제안·권유 — dis, parle, réponds (명령형)", "« Parle à Hélène avant qu'elle l'apprenne. » « Réponds. » « Laisse sonner. » 명령형은 tu 활용에서 -er 동사 끝의 s 를 뗀다. 대명사 붙은 명령: « Dis-le-moi en face. »"),
("B1", "대명사 en / y 의 감각 — j'en ai tellement", "« J'en ai déjà tellement. » en 은 앞서 말한 '걱정(soucis)' 을 대신한다. « Tu y penses ? » 의 y 는 '그 일에'. 명사를 반복하지 않고 감정을 압축한다."),
("B2", "대과거 — 먼저 일어난 일 말하기", "« Il avait pris la table quatre, seul. » « Je n'avais rien dit à Marthe pendant trois semaines. » avoir/être 반과거 + 과거분사. 과거의 한 지점(지난 화요일, 1991년)보다 앞선 일에 쓴다."),
("B2", "시간 표현 — depuis, il y a, dans, avant", "« Depuis jeudi dernier. » « Il y a deux semaines. » « C'est dans quatre semaines. » « Avant le 15 septembre. » depuis=계속, il y a=과거 시점, dans=미래 시점, avant=마감."),
("B2", "접속법 입문 — quoi que / avant que / je voudrais que", "« Quoi que tu décides... » « Parle-lui avant qu'elle l'apprenne. » « Il voudrait que je commence le 1er octobre. » 접속법은 불확실·바람·시간 전의 사건에 쓴다."),
("B2", "조건법 — 상상 속의 입장", "« Que ferais-tu à ma place ? » « Je serais juge et partie. » 조건법은 실제가 아닌 가정에서의 행동과 판단을 묻고 답한다. « Moi, je dirais oui. »"),
("C1", "설득과 완곡한 반박 — 양보 구문", "« Ça ne veut pas dire que tu dois rester. » « Pas aujourd'hui. Pas encore. » 압박하지 않으면서 입장을 밝히는 방식. ne pas dire que + 직설법/접속법 구분은 의견의 확신 정도에 따른다."),
]

READ = [
("리에종 — c'est_un, ils_ont, vous_avez", "« C'est un poste de directeur de salle. » 는 /sɛ.tœ̃.pɔst.../ 로 t 가 이어진다. « Vous avez... tu as... » 는 /vu.za.ve/. 이 화에서 Julien 이 말을 바꾸는 순간(vous → tu)을 통해 정중함과 친밀함의 차이를 들어 본다."),
("대과거의 소리 — j'avais, il avait", "« Il avait pris la table quatre. » /i.la.ve.pʁi/. avait 의 t 는 읽지 않고 /a.vɛ/. « Je n'avais rien dit » /ʒə.na.vɛ.ʁjɛ̃.di/ 는 ne 가 약해져 한 호흡으로 이어진다."),
("호흡 구간 — 회상의 서사", "« J'avais reçu la lettre / un lundi. / Je n'avais rien dit à Marthe / pendant trois semaines. » 두 문장으로 나누어 두 번째 문장에서 속도를 늦추면 고백의 톤이 산다."),
("비음 — mille euros, quand, envie", "« mille » /mil/, « quand » /kɑ̃/, « envie » /ɑ̃.vi/, « combien » /kɔ̃.bjɛ̃/. 숫자·시기 표현이 많은 화이므로 비음 /ɑ̃, ɔ̃, ɛ̃/ 를 구분하는 연습에 좋다."),
("억양 — 말 못 한 감정", "« Ne sois pas désolé. Tu n'as rien fait de mal. » 는 낮고 부드럽게, 끝에서 숨을 조금 더한다. « Pas aujourd'hui. Pas encore. » 는 두 번 다 끝을 내려 단호함과 여운을 함께 남긴다."),
("u / ou — mois, mille, jour", "« jour » 의 ou 는 /u/, « juste » 의 u 는 /y/. « Il y a deux semaines » 의 deux /dø/. 입술 모양을 바꾸면 의미가 달라진다 (rue / roue)."),
]

CULTURE = [
("프랑스의 스카우트 문화 — chasseur de têtes 와 bouche-à-oreille", "프랑스 외식업에서는 홀 매니저·주방 간부를 업계 내 입소문(bouche-à-oreille)과 직접 방문으로 구한다. 사장이 손님인 척 와서 서비스를 보고 명함을 건네는 일이 흔하다. 급여 협상은 월급(brut/net)과 근무 시간표, 휴일(주 2일 휴무) 조건이 함께 논의된다."),
("직원과 오너의 신뢰 — dire en face", "프랑스 직장 문화에서는 이직 의사를 문자나 메일이 아니라 « en face » 로 직접 알리는 것이 예의로 여겨진다. 특히 가족 같은 소규모 가게에서는 신뢰가 가장 큰 자산이다. 이 장면에서 Julien 이 Hélène 에게 직접 말하는 것이 바로 그 문화를 보여 준다."),
]

META = dict(part=2, ep=29, part_label="제2부 Premières fissures · 여름", title_fr="Le doute de Julien", title_ko="줄리앙의 망설임",
 place="Le Comptoir de Marthe, 8월 18일 화요일 (오전 8시 10분 ~ 오후 3시 반 이후)",
 chars="Julien Benali (홀 매니저) · Lucien Marchand (아버지) · Hélène Marchand (주인 셰프) · Chloé Dubois (견습 서버)",
 wine="8구 « Chez Armand » 의 홀 총괄 제안(월 +1 000 €, 10월 1일 시작, 9월 15일까지 답변). 줄리앙의 고민.",
 focus="대과거, 제안·설득, 시간 표현(depuis / il y a / dans / avant), quoi que + 접속법, 감정 털어놓기",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제30화 « Dernier service d'août » : 8월 29일 토요일 밤. 여름의 마지막 서비스와 결산, 그리고 은행에서 온 연락.")
