# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, C = "Hélène", "Lucien", "Julien", "Chloé"
D = [
(None, "Samedi 29 août, 17 h 45. Dernier service du mois. Hélène écrit le menu du soir sur l'ardoise. Julien compte les couverts à la caisse. Chloé plie des serviettes en lisant son carnet.", "8월 29일 토요일 오후 5시 45분. 8월의 마지막 서비스다. 엘렌이 칠판에 저녁 메뉴를 쓴다. 쥘리앵은 계산대에서 예약을 센다. 클로에는 수첩을 읽으며 냅킨을 접는다."),
(J, "Hélène, ce soir, on a quarante-six réservations. C'est le plus gros chiffre depuis juillet.", "엘렌, 오늘 저녁 예약이 46명이야. 7월 이후 가장 많아."),
(H, "Quarante-six ! Et sans la fête de Roussel. Ça fait plaisir.", "46명이라니! 루셀 씨 파티도 없이. 기쁘네."),
(C, "Le dernier samedi d'août. Les Parisiens rentrent de vacances, non ?", "8월의 마지막 토요일이잖아요. 파리 사람들이 휴가에서 돌아오는 거죠?"),
(J, "Exactement. Dans une semaine, tout Paris sera de retour. On appelle ça la rentrée.", "맞아. 일주일 뒤면 파리가 모두 돌아와. 그게 라랑트레, 새 학기 시즌이지."),
(H, "On verra si la rentrée nous apporte des clients, ou seulement des factures.", "라랑트레가 손님을 데려올지 청구서만 데려올지 두고 보자."),
(C, "Pardon, Hélène, ça veut dire quoi « nous apporter des factures » ?", "죄송한데 엘렌, « 청구서를 가져온다 »는 게 무슨 뜻이에요?"),
(H, "Ça veut dire que septembre arrive avec tout ce qu'on doit payer.", "9월이 우리가 내야 할 것들을 전부 들고 온다는 뜻이야."),
(C, "J'ai compris. Je le note dans mon carnet, avec « la rentrée ».", "알겠어요. 수첩에 « 라랑트레 »랑 같이 적어 둘게요."),
(J, "Montre-moi ton carnet. Tu as écrit combien de mots depuis avril ?", "수첩 좀 보여 줘. 4월부터 몇 단어나 적었어?"),
(C, "J'en suis à trois cent douze. Dont vingt-trois ce mois-ci.", "312개째예요. 그중 23개가 이번 달 거예요."),
(J, "Trois cent douze mots ! Tu parles mieux que certains clients.", "312단어라니! 어떤 손님들보다 말을 잘하네."),
(H, "Tu parles surtout plus que certains clients.", "손님들보다 더 많이 말하는 거겠지."),
(C, "Ha ha ! Hélène plaisante. Ça veut dire qu'elle est de bonne humeur.", "하하! 엘렌이 농담하시네. 기분이 좋다는 뜻이에요."),
(H, "Un peu. Sofiane est là ?", "조금. 소피안은 왔어?"),
(J, "Oui, il prépare les légumes. C'est son dernier soir, il reprend ses cours lundi.", "응, 채소 손질하고 있어. 오늘이 마지막 밤이야. 월요일에 수업 재개한대."),
(H, "Dommage. Il a bien travaillé. Tu lui diras que la porte est ouverte.", "아쉽네. 일을 잘했어. 문은 열려 있다고 말해 줘."),
(None, "Par la vitrine, on voit la terrasse de l'Atelier de Victor, pleine de lumières et de monde. Julien soupire.", "유리창 너머로 불빛과 사람으로 가득한 아틀리에 드 빅토르의 테라스가 보인다. 쥘리앵이 한숨을 쉰다."),
(J, "Regarde-moi ça. Ils ont déjà douze tables de pleines à dix-huit heures.", "저것 좀 봐. 6시에 벌써 열두 테이블이 찼어."),
(H, "Ne regarde pas. Regarde ta salle. Tu as vu la table sept ?", "보지 마. 네 홀을 봐. 7번 테이블 봤어?"),
(J, "Réservée au nom de Vasseur. Elle revient jeudi, mais Henri a téléphoné pour la réserver déjà ce soir.", "바쉐 이름으로 예약됐어. 목요일에 돌아오시지만 앙리 씨가 오늘 저녁부터 미리 잡아 달라고 전화했어."),
(H, "Ce soir ? Ils sont rentrés de Bretagne avant la date ?", "오늘 저녁에? 브르타뉴에서 예정보다 일찍 돌아왔어?"),
(J, "Ils sont rentrés hier. Mme Vasseur dit que la mer lui a donné faim.", "어제 돌아오셨어. 바쉐 부인은 바다 때문에 배가 고파졌다고 하시더라."),
(None, "20 h 15. La salle est presque pleine. Lucien est arrivé, il s'est installé au bout du bar avec un verre de Brouilly.", "저녁 8시 15분. 홀이 거의 찼다. 뤼시앵이 도착해 바 끝에 브루이 한 잔을 두고 앉았다."),
(L, "Julien, un conseil d'ancien : quand la salle est pleine, souris deux fois plus.", "쥘리앵, 선배의 조언이다. 홀이 가득 차면 두 배로 웃어라."),
(J, "Je souris déjà trois fois plus, Lucien. Le sourire est ma spécialité.", "벌써 세 배로 웃고 있어요, 뤼시앵. 미소는 제 전문이죠."),
(L, "Alors souris à la table douze, ils t'attendent depuis cinq minutes.", "그럼 12번 테이블에 웃어 줘라. 5분째 기다리고 있어."),
(None, "Julien se précipite. À la table sept, Mme Vasseur s'assoit enfin, avec Henri et un pot de confiture neuf.", "쥘리앵이 서둘러 간다. 7번 테이블에는 바쉐 부인이 앙리 씨와 새 잼 병을 들고 마침내 앉는다."),
(C, "Bonsoir, madame Vasseur. Vous avez l'air reposée !", "안녕하세요, 바쉐 부인. 푹 쉬신 얼굴이세요!"),
(None, "Mme Vasseur répond avec un sourire qui n'est pas son sourire habituel. Chloé le note mentalement.", "바쉐 부인이 평소와 다른 미소로 대답한다. 클로에는 그것을 마음속에 적어 둔다."),
(C, "Chef, la table sept est installée. Mme Vasseur a dit : « La salle a l'air plus calme qu'avant. »", "셰프, 7번 테이블 자리 잡으셨어요. 바쉐 부인이 « 홀이 전보다 조용해 보이네 »라고 하셨어요."),
(H, "Calme. C'est son mot pour dire « vide ». Merci, Chloé.", "조용하다. « 텅 비었다 »를 돌려 말하는 거지. 고마워, 클로에."),
(None, "21 h 30. Au passe, Hélène dresse deux blanquettes. Julien vient chercher les assiettes.", "밤 9시 30분. 주방 패스대에서 엘렌이 블랑케트 두 접시를 담는다. 쥘리앵이 접시를 가지러 온다."),
(J, "Table neuf, c'est un couple de Lyon. Ils étaient là en juin, ils sont revenus exprès.", "9번 테이블은 리옹에서 온 커플이야. 6월에 왔었는데 일부러 다시 왔대."),
(H, "Revenus exprès ? De Lyon ?", "일부러 다시 왔다고? 리옹에서?"),
(J, "Ils passent par Paris. Ils ont dit qu'ils n'avaient jamais retrouvé cette blanquette ailleurs.", "파리를 지나는 길이래. 이 블랑케트를 다른 데선 못 찾았다고 하더라."),
(H, "Hum. Ça fait plaisir. Dis-leur merci de ma part.", "흠. 기쁘네. 내 대신 고맙다고 전해 줘."),
(J, "Et un autre détail : il y a un nouvel avis sur Avis Gourmand. Quatre étoiles.", "그리고 하나 더, 아비 구르망에 새 후기가 올라왔어. 별 네 개야."),
(H, "Pas foodie75, j'espère ?", "푸디75는 아니겠지?"),
(J, "Non. Quelqu'un qui s'appelle « Marie_goûteuse ». Elle écrit : « Cuisine sincère, service chaleureux. »", "아니. « 마리_맛보는사람 »이라는 사람이야. « 진심 어린 요리, 따뜻한 서비스 »라고 썼어."),
(H, "Cuisine sincère... Je prends. Allez, il y a des assiettes qui refroidissent.", "진심 어린 요리라... 고맙게 받을게. 자, 접시 식는다."),
(None, "22 h 40. Les derniers clients partent. Chloé tire les rideaux. Julien tourne le panneau « Fermé ».", "밤 10시 40분. 마지막 손님들이 떠난다. 클로에가 커튼을 친다. 쥘리앵이 « 영업 종료 » 팻말을 돌린다."),
(J, "Voilà, le dernier client d'août est parti. Je ferme à clé.", "자, 8월의 마지막 손님이 갔어. 문 잠글게."),
(H, "Merci. Asseyez-vous tous les trois. J'ai envie de faire le bilan du mois avant de rentrer.", "고마워. 셋 다 앉아. 퇴근 전에 이번 달 결산을 하고 싶어."),
(L, "Je suis déjà assis, moi. Je suis le public.", "난 이미 앉아 있다. 관객이거든."),
(H, "Papa, tu es le conseil d'administration. Julien, les chiffres du soir.", "아빠는 이사회예요. 쥘리앵, 오늘 저녁 숫자."),
(J, "Ce soir, cinquante-deux couverts. À 27 € de moyenne, ça fait 1 404 €.", "오늘 저녁 52명. 평균 27유로로 1,404유로야."),
(C, "Cinquante-deux fois vingt-sept... mille quatre cent quatre. Oui, c'est ça.", "52 곱하기 27... 1,404. 맞아요."),
(H, "Bien. Et le mois ?", "좋아. 그럼 이번 달은?"),
(J, "Au total, environ quinze cents couverts. Trente-quatre le midi, trente-sept le soir, en moyenne.", "합쳐서 약 1,500명이야. 평균 점심 34명, 저녁 37명."),
(J, "Chiffre d'affaires du mois : 40 257 €, avec la soirée Roussel.", "이번 달 매출은 40,257유로야, 루셀 씨 파티 포함해서."),
(H, "L'an dernier, en août, on avait fait 57 000 €. Donc nous sommes environ trente pour cent en dessous.", "작년 8월엔 57,000유로였어. 그러니까 약 30퍼센트 아래야."),
(C, "Trente pour cent... C'est beaucoup, non ?", "30퍼센트... 많은 거죠?"),
(H, "C'est beaucoup. Mais le plus grave, c'est le reste. Julien ?", "많지. 하지만 더 심각한 건 나머지야. 쥘리앵?"),
(J, "Les dépenses du mois : 41 800 €. Loyer, salaires, fournisseurs, énergie, tout.", "이번 달 지출은 41,800유로. 임대료, 급여, 납품, 에너지, 전부."),
(C, "41 800 moins 40 257... ça fait 1 543. Nous avons perdu 1 543 € en août ?", "41,800 빼기 40,257... 1,543. 8월에 1,543유로를 손해 본 거예요?"),
(H, "Oui. Pas une catastrophe encore. Mais en octobre, le loyer passera à 5 200 €.", "응. 아직 재앙은 아니야. 하지만 10월엔 임대료가 5,200유로가 돼."),
(J, "Soit 1 400 € de plus chaque mois. Avec les mêmes chiffres, on perdrait presque 3 000 €.", "달마다 1,400유로가 더 나가지. 같은 매출이면 거의 3,000유로 손해야."),
(C, "Mille cinq cent quarante-trois plus mille quatre cents... deux mille neuf cent quarante-trois.", "1,543 더하기 1,400... 2,943이에요."),
(H, "Voilà. Presque trois mille euros de trou par mois si rien ne change.", "그래. 아무것도 안 바뀌면 달마다 거의 3천 유로 구멍이야."),
(L, "Pour résumer : on est entre le marteau et l'enclume.", "요약하자면, 우린 망치와 모루 사이에 있다."),
(C, "Le marteau, c'est le loyer. Et l'enclume ?", "망치는 임대료잖아요. 모루는요?"),
(L, "Le manque de clients. Les deux frappent en même temps.", "손님 부족이지. 둘이 동시에 때리고 있어."),
(H, "Merci pour l'image, Papa. Je me sens bien mieux.", "비유 고마워요, 아빠. 한결 기분이 좋아졌네요."),
(L, "Je ne dis pas ça pour te décourager. Je dis qu'il faut regarder la vérité en face.", "낙심시키려는 게 아니야. 진실을 똑바로 보아야 한다는 거지."),
(H, "Je sais. D'ailleurs, j'ai agi.", "알아요. 사실 이미 움직였어요."),
(J, "Agi comment ? Tu ne m'as rien dit.", "어떻게? 나한테 아무 말도 없었잖아."),
(H, "Jeudi, j'ai appelé la banque. J'ai demandé à voir la responsable des crédits professionnels.", "목요일에 은행에 전화했어. 사업자 대출 담당자를 만나고 싶다고 했지."),
(C, "Une banque ! Pour quoi faire ?", "은행이요! 뭘 하려고요?"),
(H, "Pour savoir ce qui est possible. Une aide de trésorerie, un étalement, je ne sais pas encore.", "가능한 게 뭔지 알아보려고. 운영자금 지원이든, 상환 분할이든, 아직 몰라."),
(L, "Tu as une date ?", "날짜는 잡았니?"),
(H, "Pas encore. Mme Garnier, la responsable, devait me rappeler pour fixer un rendez-vous.", "아직. 담당자인 가르니에 부인이 일정을 잡으려고 전화를 주기로 했어."),
(J, "Mme Garnier ? Je crois que c'est la dame qui a financé le salon de coiffure à côté.", "가르니에 부인? 옆 미용실 자금을 대 준 그분일 거야."),
(H, "Possible. Je ne la connais pas. Je lui ai laissé un message.", "그럴지도. 나는 모르는 분이야. 메시지를 남겼어."),
(C, "Moi, je ne comprends pas tout. Mais c'est bien d'essayer, non ?", "저는 다 이해하진 못해요. 하지만 시도해 보는 건 좋은 거 아니에요?"),
(H, "On ne sait jamais. Il se peut que la banque dise oui. Il se peut aussi qu'elle dise non.", "모르는 일이지. 은행이 승낙할 수도 있고 거절할 수도 있어."),
(J, "Et dans ce cas-là, tu feras quoi ?", "그럼 거절당하면 어떻게 할 거야?"),
(H, "Je ne sais pas, Julien. Honnêtement, je préfère ne pas y penser ce soir.", "모르겠어, 쥘리앵. 솔직히 오늘 저녁엔 생각하고 싶지 않아."),
(L, "Un jour à la fois. C'est la meilleure méthode contre l'angoisse.", "하루씩. 불안에는 그게 제일 좋은 방법이야."),
(J, "Hélène, je voulais te dire quelque chose. Pour Armand.", "엘렌, 할 말이 있어. 아르망 건에 대해서."),
(H, "Je t'écoute. Mais tu n'es pas obligé de le faire ce soir.", "듣고 있어. 하지만 오늘 밤에 꼭 말할 필요는 없어."),
(J, "Je voulais juste dire ceci : je ne répondrai pas avant ton rendez-vous à la banque.", "이 말만 하고 싶었어. 은행 약속 전에는 답하지 않을 거야."),
(H, "Pourquoi ? Ce n'est pas lié.", "왜? 연관된 일이 아니잖아."),
(J, "Si, un peu. Je voudrais savoir où va le bateau avant de décider d'y rester.", "조금은 연관돼 있어. 이 배가 어디로 가는지 알고 나서 남을지 결정하고 싶어."),
(H, "C'est honnête. Et c'est ton droit. Je ne te demande rien.", "정직한 말이야. 네 권리이기도 하고. 나는 아무것도 요구하지 않아."),
(C, "Moi, je suis déjà sûre d'une chose : ce mois d'août, c'était dur, mais on était ensemble.", "저는 확실한 게 하나 있어요. 이번 8월은 힘들었지만 우리가 함께였어요."),
(L, "Bien dit, la petite. Résumons l'été : on a perdu Karim, gagné Sofiane pour un mois.", "잘 말했다, 얘야. 여름을 정리해 보자. 카림을 잃고 한 달간 소피안을 얻었지."),
(J, "On a eu un frigo en panne, un avis cassant, une enseigne en face, et un grand repas pour Gérard.", "냉장고가 고장 났고, 혹평 후기가 있었고, 맞은편엔 새 가게가 생겼고, 제라르 씨를 위한 큰 만찬이 있었지."),
(H, "Au final, un été dur. Mais on a tenu. Et ça, je ne l'oublierai pas.", "결국 힘든 여름이었어. 하지만 버텼지. 그건 잊지 않을 거야."),
(J, "Une bonne nouvelle quand même : la réparation du frigo est réglée.", "그래도 좋은 소식이 있어. 냉장고 수리비는 정리됐어."),
(H, "Réglée, oui. Les 1 450 € sont partis de la trésorerie, et elle est maigre.", "정리됐지. 1,450유로는 운영 자금에서 나갔고, 그 자금은 얼마 안 남았어."),
(J, "Et Victor ? Tu crois qu'il va tenir, avec ses prix cassés ?", "빅토르는? 그렇게 싼 가격으로 버틸 것 같아?"),
(H, "Il a ouvert fort. On verra s'il est encore là en hiver.", "개업은 화려했지. 겨울에도 있을지는 두고 보자."),
(L, "Ce n'est pas le vent qui fait la tempête, c'est le marin qui n'a pas appris à naviguer.", "폭풍을 만드는 건 바람이 아니라 항해를 배우지 못한 선원이다."),
(H, "Papa, tu as vraiment un proverbe pour tout, hein ?", "아빠, 정말 모든 것에 속담이 있네요?"),
(L, "Pas pour le loyer. J'y travaille encore.", "임대료에는 없다. 아직 만드는 중이야."),
(C, "Gérard, il a pleuré, hein ? Quand il a vu les photos sur le mur ?", "제라르 씨는 우셨죠? 벽에 사진 나왔을 때요?"),
(J, "Il a pleuré, il a ri, il a repris de la blanquette. C'était une belle soirée.", "울다가 웃다가 블랑케트를 더 드셨지. 멋진 밤이었어."),
(H, "Et M. Roussel m'a téléphoné cette semaine. Il a recommandé la salle à un collègue pour un mariage.", "그리고 루셀 씨가 이번 주에 전화했어. 동료에게 결혼식 장소로 우리 가게를 추천했대."),
(J, "Un mariage ! Tu vois, une soirée en amène une autre.", "결혼식이라니! 봐, 파티 하나가 다른 파티를 불러오잖아."),
(H, "Ne t'emballe pas. C'est seulement une idée pour l'instant.", "너무 들뜨지 마. 아직 아이디어일 뿐이야."),
(L, "Il se pourrait que ce soit le début de quelque chose. On ne sait jamais.", "뭔가의 시작일지도 모르지. 알 수 없는 일이야."),
(H, "Il se pourrait. Bon. Il est tard. Chloé, tu rentres comment ?", "그럴지도요. 자, 늦었어. 클로에, 어떻게 갈래?"),
(C, "Le métro de minuit. Mais je ne suis pas pressée. J'ai envie de rester encore un peu.", "자정 지하철이요. 하지만 급하진 않아요. 조금 더 있고 싶어요."),
(J, "Et l'école ? Tu reprends les cours lundi ?", "학교는? 월요일부터 수업 다시 시작하지?"),
(C, "Oui, comme avant : l'école le lundi et le jeudi, ici tout le reste.", "네, 전과 같아요. 월요일과 목요일은 학교, 나머지는 여기예요."),
(H, "Bonne nouvelle. J'aurai besoin de toi en septembre.", "좋은 소식이네. 9월엔 네가 필요할 거야."),
(None, "23 h 35. Le téléphone d'Hélène vibre dans sa poche. Elle le sort, lit l'écran, fronce les sourcils.", "밤 11시 35분. 엘렌의 전화기가 주머니에서 진동한다. 꺼내서 화면을 읽고 눈살을 찌푸린다."),
(J, "C'est qui ? À cette heure-ci ?", "누구야? 이 시간에?"),
(H, "Un mail. De la banque. Mme Garnier m'a écrit.", "메일이야. 은행에서. 가르니에 부인이 보냈어."),
(L, "À minuit moins vingt ? Elle est du genre à travailler tard.", "밤 12시 20분 전에? 늦게까지 일하는 사람이군."),
(H, "« Madame Marchand, suite à votre message, je vous propose un rendez-vous. »", "« 마르샹 씨, 메시지 잘 받았습니다. 면담 일정을 제안드립니다. »"),
(C, "Quand ? Quand, Hélène ?", "언제요? 언제예요, 엘렌?"),
(H, "« Jeudi 3 septembre, à 10 heures. Merci d'apporter votre bail et vos bilans. »", "« 9월 3일 목요일 오전 10시. 임대차 계약서와 결산서를 가져오시기 바랍니다. »"),
(J, "Jeudi 3 septembre. C'est la semaine prochaine. Le premier jeudi du mois.", "9월 3일 목요일. 다음 주야. 이달의 첫째 목요일이네."),
(H, "Oui. Dans cinq jours. Je n'avais pas imaginé que ça irait si vite.", "응. 닷새 뒤야. 이렇게 빨리 될 줄은 몰랐어."),
(L, "Je viens avec toi. Je connais les banquiers, j'ai une tête qui rassure.", "내가 같이 가마. 은행원들을 알고, 내 얼굴은 믿음직하거든."),
(H, "Non, Papa. Cette fois, je veux y aller seule.", "아니에요, 아빠. 이번엔 혼자 가고 싶어요."),
(L, "Comme tu veux. Mais je t'attendrai devant la banque, avec un croissant.", "좋을 대로. 하지만 은행 앞에서 크루아상 들고 기다리마."),
(C, "Moi, je peux préparer les dossiers. Je classe très bien les papiers.", "저는 서류를 준비할 수 있어요. 서류 정리는 정말 잘해요."),
(J, "Et moi, je sors les relevés bancaires et le bail dès lundi. Il y a aussi le bilan du trimestre.", "나는 월요일부터 은행 거래 내역이랑 계약서를 뽑을게. 분기 결산서도 있고."),
(H, "Merci, vous deux. Je vais avoir besoin de tout ça.", "고마워, 둘 다. 그게 전부 필요할 거야."),
(J, "Tu es nerveuse ?", "긴장돼?"),
(H, "Un peu. Je ne sais pas ce que Mme Garnier va dire. Je ne sais même pas ce que je vais demander.", "조금. 가르니에 부인이 뭐라고 할지 몰라. 내가 뭘 요청할지도 정확히 모르겠어."),
(L, "Tu demanderas ce dont tu as besoin. Le reste, on verra jeudi.", "필요한 걸 요청하면 된다. 나머지는 목요일에 보자."),
(H, "On verra. Bon, il est tard, tout le monde à la maison. Moi, je ferme.", "두고 보죠. 자, 늦었으니 다들 집에 가. 나는 문 닫을게."),
(C, "Bonne nuit, Chef. À mardi !", "안녕히 주무세요, 셰프. 화요일에 봬요!"),
(None, "Les autres sortent. Hélène éteint la salle, mais s'arrête devant l'ardoise. Elle prend l'éponge et efface le mot « Août », puis écrit « Septembre » à la craie.", "다른 사람들이 나간다. 엘렌은 홀 불을 끄다 칠판 앞에서 멈춘다. 스펀지로 « 8월 » 글자를 지우고 분필로 « 9월 »이라고 쓴다."),
(H, "Septembre. Jeudi, dix heures. On y va.", "9월. 목요일 10시. 가 보자."),
]

VOCAB = [
("A2", "Le dernier service", "마지막 서비스", "« Le dernier service du mois. » 하루나 한 달의 마지막 영업 시간을 가리킨다."),
("A2", "Au total / en moyenne", "합쳐서 / 평균", "« Au total, environ quinze cents couverts. » « 27 € de moyenne. » 숫자를 요약할 때."),
("A2", "Un avis", "후기, 의견", "« Un nouvel avis. Quatre étoiles. » 온라인 후기의 기본 단어. donner son avis = 의견을 말하다."),
("A2", "À mardi !", "화요일에 봬요!", "[구어] 다음 만날 요일을 넣은 퇴근 인사. ↔ 정중: Nous nous reverrons mardi."),
("B1", "Le chiffre d'affaires", "매출", "« Chiffre d'affaires du mois : 40 257 €. » 줄여서 le CA. 손익은 résultat 라고 한다."),
("B1", "Les dépenses / perdre de l'argent", "지출 / 손해를 보다", "« Nous avons perdu 1 543 € en août. » perdre 는 단순히 '잃다'가 아니라 손해를 본다는 뜻으로도 쓴다."),
("B1", "Faire le bilan", "결산하다, 점검하다", "« Faire le bilan du mois. » 숫자뿐 아니라 감정·사건의 정리에도 쓴다."),
("B1", "Un trou", "구멍, 적자", "[구어] « Presque trois mille euros de trou par mois. » ↔ 정중: un déficit. 일상에서 돈이 비는 것을 부르는 말."),
("B1", "Avoir l'air + 형용사", "~해 보이다", "« Vous avez l'air reposée ! » « Tu as l'air fatiguée. » 형용사는 주어와 성·수를 일치시킨다."),
("B1", "Revenir exprès", "일부러 다시 오다", "« Ils sont revenus exprès. » exprès 는 '일부러'. 우연히는 par hasard."),
("B1", "Un rendez-vous", "약속, 면담", "« Fixer un rendez-vous. » « Jeudi 3 septembre, à 10 heures. » 날짜 앞의 요일에는 관사를 붙이지 않는다."),
("B2", "Pour résumer / au final", "요약하자면 / 결국", "« Pour résumer : on est entre le marteau et l'enclume. » « Au final, un été dur. » 결산 대사의 핵심 연결어. 같은 계열: en bref, somme toute."),
("B2", "Entre le marteau et l'enclume", "진퇴양난, 망치와 모루 사이", "두 힘 사이에 끼어 빠져나가기 어려운 상태. 임대료와 손님 부족이 동시에 누르는 상황."),
("B2", "Il se peut que + 접속법", "~일 수도 있다", "« Il se peut que la banque dise oui. » 접속법 dise. 비슷한 표현: Il se pourrait que, Il est possible que."),
("B2", "Ne t'emballe pas.", "너무 들뜨지 마.", "[구어] 흥분해서 앞서 나가는 상대를 말릴 때. ↔ 정중: Ne vous précipitez pas."),
("B2", "Un étalement", "(상환의) 분할·연기", "« Une aide de trésorerie, un étalement. » 갚아야 할 돈을 나누어 내는 방식. 금융 용어."),
("B2", "Être maigre / la trésorerie", "빈약하다 / 운영 자금", "« Les 1 450 € sont partis de la trésorerie, et elle est maigre. » la trésorerie 는 당장 쓸 수 있는 현금. maigre 는 얇은 자금."),
("B2", "Fixer un rendez-vous", "약속을 정하다", "« Pour fixer un rendez-vous. » fixer 는 날짜·시간을 정한다는 뜻. 반대: annuler, reporter."),
("C1", "Un conseil d'administration", "이사회", "농담으로 쓴 « Tu es le conseil d'administration. » 회사 임원진을 가리키는 공식 용어. 가족 대화에서는 익살."),
("C1", "Regarder la vérité en face", "진실을 똑바로 보다", "« Il faut regarder la vérité en face. » 피하고 싶은 현실을 인정하라는 표현. ↔ fermer les yeux."),
("C1", "Une aide de trésorerie", "운영자금 지원", "« Une aide de trésorerie » 은 단기 현금 흐름 문제를 위한 자금이다. 은행 상담에서 자주 쓰는 용어."),
]

GRAM = [
("A2", "숫자와 계산 — plus, moins, fois", "« 41 800 moins 40 257... ça fait 1 543. » « 1 543 plus 1 400, deux mille neuf cent quarante-trois. » 가장 간단한 문장으로 숫자를 말하는 연습. 계산은 « ça fait » 로 마무리한다."),
("B1", "비교와 퍼센트 — en dessous / au-dessus", "« Nous sommes environ trente pour cent en dessous. » « Soit 1 400 € de plus chaque mois. » 비교에는 en dessous de(아래), au-dessus de(위), soit(즉)."),
("B1", "요약 연결어 — pour résumer, au final, en bref", "« Pour résumer : on est entre le marteau et l'enclume. » « Au final, un été dur. » 요약 단어로 긴 이야기를 한 문장에 담는다. 결산 장면의 기본."),
("B2", "접속법 — il se peut que / il se pourrait que", "« Il se peut que la banque dise oui. » « Il se pourrait que ce soit le début de quelque chose. » 불확실성은 접속법. dise(dire), soit(être). 확실하면 직설법: « Je suis sûre qu'elle dira oui. »"),
("B2", "불확실성 표현 — je ne sais pas, peut-être, on verra", "« On ne sait jamais. » « On verra jeudi. » « Je ne sais même pas ce que je vais demander. » 확신이 없을 때의 완충 표현. 단정을 피해 감정을 지킨다."),
("B2", "미래 의도 — aller + 부정사 / futur simple", "« Ce que je vais demander. » « Tu demanderas ce dont tu as besoin. » « Je t'attendrai devant la banque. » 가까운 미래는 aller, 약속·예측은 단순미래."),
("C1", "관계대명사 dont — ce dont tu as besoin", "« Ce dont tu as besoin » 는 avoir besoin de 의 de 가 dont 으로 바뀐 것. « Tu demanderas ce dont tu as besoin. » 앞선 선행사 ce 와 함께 쓰이는 고급 구문."),
]

READ = [
("숫자 읽기 — 결산 금액", "« 40 257 € » 는 quarante mille deux cent cinquante-sept euros. « 41 800 € » 는 quarante et un mille huit cents euros. « 1 543 € » 는 mille cinq cent quarante-trois euros. mille 와 cent 사이에서 짧게 숨을 쉬고, 끝의 euros 는 연음 s 없이 /ø.ʁo/."),
("리에종 — c'est_un, en_août, mille_euros", "« Le dernier samedi d'août » /dɛʁ.nje.sam.di.du/. « Mille euros » /mil.ø.ʁo/ 에서 l 이 이어진다. « C'est un trou » 는 /sɛ.tœ̃.tʁu/ 로 t 를 이어 읽는다."),
("호흡 구간 — 결산 문장", "« Au final, / un été dur. / Mais on a tenu. / Et ça, / je ne l'oublierai pas. » 짧게 끊어 읽으면 담담한 결산의 톤이 산다. 마지막 문장은 속도를 늦추고 끝을 내린다."),
("억양 — 불안한 침묵", "« Je ne sais pas, Julien. Honnêtement, je préfère ne pas y penser ce soir. » 는 느리게 낮은 목소리로. « Quand ? Quand, Hélène ? » 는 클로에의 조급함을 끝을 높여서 표현한다."),
("비음 — environ, quinze cents, Garnier", "« environ » /ɑ̃.vi.ʁɔ̃/ 은 비음이 두 번, « cents » 는 /sɑ̃/. « Garnier » 는 /ɡaʁ.nje/. 비음과 일반 모음을 구별해서 읽는다."),
("r — septembre, rendez-vous, rentrée", "« septembre » /sɛp.tɑ̃bʁ/, « rendez-vous » /ʁɑ̃.de.vu/, « rentrée » /ʁɑ̃.tʁe/. 단어 안에서 r 이 혀뿌리로 내는 소리임을 의식한다. 어두 r 은 가볍게 긁는 소리."),
]

CULTURE = [
("la rentrée — 프랑스의 9월", "프랑스에서는 7~8월 바캉스 후 9월 첫째 주를 « la rentrée » 라고 부른다. 학교·직장·정치가 일제히 다시 시작하고, 식당도 단골이 돌아오며 한 해의 분위기가 바뀐다. 소규모 상인에게 la rentrée 는 희망이자 청구서의 시즌이다."),
("은행 면담 — le rendez-vous avec le banquier", "프랑스에서 자영업자가 대출이나 지원을 상담할 때는 은행의 « chargé d'affaires professionnelles » 와 정식 약속(rendez-vous)을 잡는다. 임대차 계약서(bail), 최근 결산서(bilan), 통장 거래 내역을 가져가는 것이 일반적이다. 결과를 확신할 수 없으므로 준비와 기다림이 따른다."),
]

META = dict(part=2, ep=30, part_label="제2부 Premières fissures · 여름", title_fr="Dernier service d'août", title_ko="8월의 마지막 서비스",
 place="Le Comptoir de Marthe, 8월 29일 토요일 저녁 (오후 5시 45분 ~ 밤 12시 무렵)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · Lucien Marchand (아버지)",
 wine="여름 결산(8월 매출 40 257 €, 지출 41 800 €)과 은행 약속(9월 3일 목요일 오전 10시)의 확정.",
 focus="요약·결산 표현, 퍼센트·비교, 불확실성(il se peut que), 접속법, 클리프행어",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제3부 제31화 « Rendez-vous à la banque » : 9월 3일 목요일 오전 10시, 엘렌은 은행 담당자 가르니에 부인 앞에 선다.")
