# -*- coding: utf-8 -*-
G, L, A, P, K, V, D_ = "Gaston", "Léa", "Antoine", "Mme Pichon", "Karim", "La marchande", "M. Delaunay"
D = [
(None, "Samedi 6 décembre, 16 h. Le marché de Noël de Montmartre déploie ses chalets de bois sous des guirlandes de lumières blanches. L'air sent le vin chaud, la cannelle, les marrons grillés et la barbe à papa. Léa et Antoine, emmitouflés dans des écharpes, avancent lentement parmi la foule.", "12월 6일 토요일 오후 4시. 몽마르트르 크리스마스 마켓이 하얀 전구 줄 아래 나무 오두막들을 펼쳐 놓았다. 공기에는 뱅쇼, 계피, 군밤, 솜사탕 냄새가 가득하다. 목도리를 두른 레아와 앙투안이 인파 사이를 천천히 걷는다."),
(L, "Je n'avais jamais vu autant de monde ici. Il y a des familles, des touristes, des bébés en combinaison de ski.", "여기서 이렇게 많은 사람은 처음 봐. 가족, 관광객, 스키복 입은 아기들도 있네."),
(A, "C'est le premier samedi de décembre. Tout Paris sort ses écharpes et son pouvoir d'achat.", "12월 첫 토요일이잖아. 파리 사람들이 다 목도리와 구매력을 꺼내는 날이야."),
(L, "Et nous, on cherche quoi, exactement ? Un cadeau pour Gaston ?", "그럼 우린 정확히 뭘 찾는 거야? 가스통의 선물?"),
(A, "Pour Gaston, pour Madame Pichon, pour Karim, pour Hugo, pour Margaux, pour ton père, pour ma mère... enfin, pour la tombe de ma mère. Une petite branche de houx.", "가스통, 피숑 부인, 카림, 위고, 마르고, 네 아버지, 우리 어머니... 아니, 어머니 묘에 놓을 호랑가시나무 가지까지."),
(L, "(prend son bras) La liste est longue.", "(그의 팔을 잡으며) 목록이 길다."),
(A, "J'ai toujours préféré offrir que recevoir. C'est un défaut. Ou une qualité. Je n'ai jamais su.", "난 늘 받기보다 주는 게 좋았어. 단점일 수도 있고 장점일 수도 있고, 모르겠어."),
(None, "Ils s'arrêtent devant un chalet tenu par une femme aux joues rouges, en bonnet de laine. Sur les étagères, des boules de Noël en verre soufflé, des santons de Provence, des boîtes à musique et des petites bouteilles en bois sculpté.", "두 사람이 털모자를 쓰고 뺨이 붉은 여인이 지키는 오두막 앞에 멈춘다. 선반에는 불어서 만든 유리 크리스마스 볼, 프로방스 산통 인형, 오르골, 조각된 작은 나무 병이 놓여 있다."),
(L, "(prend une petite bouteille en bois) Regarde. Elle est minuscule, mais le travail est incroyable. Il y a même un bouchon.", "(작은 나무 병을 집으며) 봐. 아주 작은데 솜씨가 놀라워. 마개까지 있어."),
(V, "Bonjour, madame. C'est du hêtre sculpté à la main, par mon mari, dans le Jura. Il en fait vingt par semaine.", "안녕하세요, 부인. 쥐라에서 남편이 손으로 조각한 너도밤나무예요. 일주일에 스무 개를 만들죠."),
(L, "Combien ?", "얼마예요?"),
(V, "Vingt-quatre euros pièce.", "하나에 24유로예요."),
(L, "(à Antoine, à voix basse) C'est cher, non ?", "(앙투안에게 작은 소리로) 비싸지 않아?"),
(A, "(à voix basse) C'est cher pour un objet. Pas cher pour un travail de deux heures.", "(작은 소리로) 물건으로는 비싸. 두 시간 작업으로는 비싸지 않고."),
(L, "(à la marchande) Si j'en prenais cinq, vous pourriez me faire un prix ?", "(판매원에게) 다섯 개를 사면 가격을 좀 깎아 주실 수 있나요?"),
(V, "Cinq ? Pour cinq, je pourrais faire cent dix euros. Un petit geste de Noël.", "다섯 개요? 다섯 개면 110유로에 해 드릴 수 있어요. 크리스마스 선물로요."),
(L, "Cent euros, et je les prends tous les cinq, avec un emballage cadeau.", "100유로에 다섯 개 다 살게요, 선물 포장 포함해서."),
(V, "(rit) Vous marchandez bien, vous. Cent cinq. Et je vous fais l'emballage.", "(웃으며) 흥정을 잘하시네. 105유로. 포장은 해 드릴게요."),
(L, "Cent deux, et je vous dis que vos bouteilles sont les plus belles du marché.", "102유로로 하고, 가장 예쁜 병이라고 말해 드릴게요."),
(V, "(éclate de rire) Cent trois, et on n'en parle plus.", "(웃음을 터뜨리며) 103유로, 그리고 더 이상 얘기하지 않기."),
(L, "Marché conclu.", "거래 성사."),
(A, "(à voix basse) Tu viens d'économiser vingt-sept euros en deux minutes.", "(작은 소리로) 이 분 만에 27유로를 아꼈네."),
(L, "(à voix basse) Il faut bien que mon futur métier de commerçante serve à quelque chose.", "(작은 소리로) 내 미래 상인 직업이 어딘가 쓸모가 있어야지."),
(V, "(enveloppant les petites bouteilles) Commerçante ? Vous avez un commerce ?", "(작은 병들을 포장하며) 상인이세요? 가게가 있어요?"),
(L, "Pas encore. J'espère reprendre une boutique de vin, ici, dans le quartier.", "아직은 아니에요. 이 동네에서 와인 가게를 이어받기를 바라고 있어요."),
(V, "Une cave ? À Montmartre ? Pas La Cave des Abbesses, au moins ?", "와인 가게요? 몽마르트르에서요? 설마 라 카브 데 자베스는 아니죠?"),
(L, "(étonnée) Si. Comment le savez-vous ?", "(놀라며) 맞아요. 어떻게 아세요?"),
(V, "Tout le quartier le sait. Monsieur Gaston a vendu son vin à ma grand-mère, puis à ma mère, puis à moi. Quand j'ai appris qu'il voulait vendre à une chaîne, j'ai failli pleurer.", "동네 사람이 다 알아요. 가스통 씨가 제 할머니에게, 어머니에게, 그리고 저에게 와인을 팔았어요. 체인점에 판다고 들었을 때 울 뻔했죠."),
(A, "Tout le quartier le sait ?", "동네 사람이 다 안다고요?"),
(V, "Les bruits courent, monsieur. Surtout quand ce sont des mauvaises nouvelles.", "소문은 퍼지죠, 선생님. 특히 나쁜 소식은."),
(L, "Merci. Vous nous donnez du courage.", "고마워요. 용기를 주시네요."),
(V, "Alors ne me remerciez pas. Faites en sorte que ça marche. (Elle leur tend le paquet.) Joyeux Noël.", "그럼 고마워하지 말고 잘되게 만들어 주세요. (꾸러미를 건네며) 메리 크리스마스."),
(None, "Ils s'éloignent, le paquet sous le bras. À quelques stands de là, ils aperçoivent une silhouette familière, une veste de velours, un chapeau de feutre, plantée devant un étal de vin chaud. Gaston, un gobelet fumant à la main, discute avec Madame Pichon et Karim.", "꾸러미를 겨드랑이에 끼고 멀어진다. 몇 부스 떨어진 곳에서 낯익은 실루엣이 보인다. 벨벳 재킷에 중절모를 쓴 사람이 뱅쇼 가판대 앞에 서 있다. 가스통이 김 나는 컵을 들고 피숑 부인, 카림과 이야기하고 있다."),
(G, "Les voilà, mes deux conspirateurs ! Venez goûter ce vin chaud. Il est détestable.", "여기 내 두 공모자들이 왔군! 와서 이 뱅쇼 좀 마셔 봐. 형편없어."),
(L, "Gaston, pourquoi tu en bois, alors ?", "가스통, 그런데 왜 마시는 거예요?"),
(G, "Par solidarité envers la tradition. Un vin chaud est toujours détestable. C'est ce qui fait son charme.", "전통에 대한 연대 때문이지. 뱅쇼는 늘 형편없어. 그게 매력이야."),
(P, "Il est trop sucré. Et la cannelle a un goût de savon.", "너무 달아. 그리고 계피에서 비누 맛이 나."),
(K, "Moi, je le trouve bon.", "전 맛있는데요."),
(P, "Toi, tu trouves tout bon quand il y a de l'alcool dedans.", "너는 알코올만 들어 있으면 다 맛있다고 하지."),
(K, "Madame Pichon, vous me jugez durement.", "피숑 부인, 저를 가혹하게 평가하시네요."),
(P, "Je te juge précisément.", "정확하게 평가하는 거야."),
(A, "(sourit) Vous pouvez en faire un meilleur, de ce vin chaud, Gaston ?", "(미소 지으며) 더 좋은 뱅쇼를 만들 수 있어요, 가스통?"),
(G, "Évidemment. Il faut un vin rouge jeune, un Gamay, sans tanins. De l'orange, du clou de girofle, de l'anis étoilé, et une pointe de miel plutôt que du sucre. Et surtout, ne jamais le faire bouillir.", "물론이지. 탄닌 없는 어린 레드 와인, 가메가 필요해. 오렌지, 정향, 팔각, 설탕 대신 꿀 약간. 그리고 무엇보다 절대 끓이지 말 것."),
(L, "Tu me l'écris ? J'ai une idée. Une petite carte à glisser dans chaque bouteille de Morgon vendue pendant les fêtes : « Recette du vin chaud de La Cave des Abbesses ».", "적어 줄래요? 아이디어가 있어요. 연휴 동안 팔리는 모르공마다 넣을 작은 카드요. '라 카브 데 자베스의 뱅쇼 레시피'."),
(G, "Une carte de recette. J'adore. On pourra la faire imprimer sur du papier kraft.", "레시피 카드라. 마음에 들어. 크라프트지에 인쇄하면 되겠다."),
(K, "Avec un petit dessin d'étoile de mer.", "작은 불가사리 그림도 넣고요."),
(P, "Pourquoi d'étoile de mer ?", "왜 불가사리죠?"),
(K, "Parce que l'anis étoilé ressemble à une étoile de mer. Je suis ingénieur, j'observe les formes.", "팔각이 불가사리처럼 생겨서요. 전 엔지니어라 형태를 관찰해요."),
(L, "Il a raison. Je le fais.", "맞아요. 그릴게요."),
(None, "Un homme élégant en manteau gris, une écharpe de cachemire autour du cou, s'approche d'eux avec un sourire poli. Il tient à la main un gobelet de vin chaud, qu'il n'a visiblement pas touché.", "회색 코트에 캐시미어 목도리를 두른 우아한 남자가 정중한 미소로 다가온다. 손에는 뱅쇼 컵을 들었지만 분명히 입을 대지 않았다."),
(D_, "Monsieur Roussel ? Bonjour. Étienne Delaunay, de « Maison Vinum ». Nous nous sommes rencontrés en septembre, à votre boutique.", "루셀 씨? 안녕하세요. '메종 비눔'의 앙투안 들로네입니다. 9월에 가게에서 만났죠."),
(G, "(se raidit, son sourire s'efface) Monsieur Delaunay. Le hasard est surprenant.", "(굳으며 미소가 사라진다) 들로네 씨. 우연이 놀랍군요."),
(D_, "Je profitais du marché de Noël, comme tout le monde. Et je suis tombé sur vous. Heureuse coïncidence, car je voulais vous parler.", "저도 다른 사람들처럼 크리스마스 마켓을 즐기러 왔어요. 그러다 당신을 만났네요. 마침 얘기하고 싶었는데 반가운 우연이군요."),
(G, "Je vous écoute.", "듣겠습니다."),
(D_, "Ma direction a étudié votre demande de prolongation du délai de réponse. Nous pouvons l'accorder jusqu'au trente et un janvier. Mais avec deux conditions.", "본사에서 답변 기한 연장 요청을 검토했습니다. 1월 31일까지는 허락할 수 있어요. 하지만 두 가지 조건이 있습니다."),
(G, "Lesquelles ?", "어떤 조건입니까?"),
(D_, "Premièrement, une indemnité d'immobilisation de cinq mille euros, qui nous serait acquise si vous ne signez pas avec nous. Deuxièmement, une révision du prix à la baisse : cent soixante mille euros au lieu de cent quatre-vingt mille.", "첫째, 5천 유로의 계약 보류 보상금이고 우리와 서명하지 않으면 귀속됩니다. 둘째, 가격 조정입니다. 18만 유로가 아니라 16만 유로예요."),
(L, "(intervient, glaciale) Pourquoi cette baisse ?", "(싸늘하게 끼어들며) 왜 가격을 내리죠?"),
(D_, "Mademoiselle ? Je ne crois pas avoir le plaisir...", "아가씨? 인사를 나눴던 기억이 없는데요..."),
(L, "Léa Fontaine. Une amie de Monsieur Roussel. Pouvez-vous répondre à ma question ?", "레아 퐁텐입니다. 루셀 씨의 친구예요. 제 질문에 답해 주시겠어요?"),
(D_, "(un temps) Le marché évolue. Les boutiques indépendantes perdent de la valeur chaque année. Nous préférons être prudents.", "(잠시 후) 시장은 변하고 있습니다. 독립 상점의 가치는 해마다 떨어지죠. 신중하게 하고 싶습니다."),
(L, "Prudents, ou opportunistes ?", "신중한 건가요, 기회주의적인 건가요?"),
(D_, "(froidement) Je dirais réalistes.", "(차갑게) 현실적이라고 하겠습니다."),
(A, "Monsieur Delaunay, nous reprendrons cette conversation dans le cadre de la négociation, au moment opportun. Pour l'instant, Monsieur Roussel profite du marché de Noël.", "들로네 씨, 협상 틀 안에서 적절한 때에 이 얘기를 다시 하죠. 지금은 루셀 씨가 크리스마스 마켓을 즐기고 있습니다."),
(D_, "(hausse un sourcil) Vous êtes... ?", "(눈썹을 올리며) 당신은...?"),
(A, "Antoine Delcourt. Professeur d'histoire, et futur repreneur de La Cave des Abbesses.", "앙투안 델쿠르입니다. 역사 교사이고 라 카브 데 자베스의 미래 인수자죠."),
(D_, "(un silence) Ah. Je vois. Alors c'est donc cela, la « prolongation ». Vous cherchez des repreneurs.", "(침묵) 아. 알겠네요. 그러니까 그게 '연장'의 이유군요. 인수자를 찾으신 거고."),
(G, "Je cherche surtout le temps de réfléchir, monsieur Delaunay. À mon âge, ce n'est pas un luxe.", "저는 무엇보다 생각할 시간을 찾는 겁니다, 들로네 씨. 제 나이엔 사치가 아니죠."),
(D_, "Je comprends. Dans ce cas, nous attendrons jusqu'au trente et un janvier. Mais le prix baissera. C'est la loi du marché.", "이해합니다. 그렇다면 1월 31일까지 기다리죠. 하지만 가격은 내려갈 겁니다. 시장의 법칙이에요."),
(P, "(s'avance, d'une voix tremblante mais ferme) Monsieur, la loi du marché ne vaut que pour ceux qui n'ont jamais bu un verre de vin avec le propriétaire.", "(떨리지만 단호한 목소리로 나서며) 선생님, 시장의 법칙은 주인과 와인 한 잔을 나눠 본 적 없는 사람에게만 유효해요."),
(D_, "Madame ?", "부인?"),
(P, "Madame Pichon. Cliente depuis mille neuf cent quatre-vingt-dix. J'ai acheté ma première bouteille ici le quinze juillet de cette année-là. Chez vous, ce serait un numéro de carte de fidélité.", "피숑 부인이에요. 1990년부터 손님이죠. 그해 7월 15일에 여기서 첫 병을 샀어요. 당신네 가게에서는 멤버십 카드 번호가 되겠죠."),
(D_, "(embarrassé) Je n'ai aucun mépris pour ceux qui...", "(난처해하며) 저는 누구도 경멸하지 않아요..."),
(P, "Évidemment que non. Le mépris est une passion. Vous, vous n'avez que des tableaux Excel.", "물론이죠. 경멸은 열정이에요. 당신에겐 엑셀 표뿐이잖아요."),
(K, "(retient un rire) Madame Pichon, vous êtes magnifique.", "(웃음을 참으며) 피숑 부인, 멋지세요."),
(D_, "(se redresse) Messieurs, mesdames. Je ne suis pas venu pour me disputer. Le trente et un janvier à minuit : date butoir. Je vous souhaite un excellent Noël.", "(몸을 곧게 펴며) 여러분. 다투러 온 게 아닙니다. 1월 31일 자정이 마감일이에요. 즐거운 크리스마스 보내세요."),
(None, "Il s'éloigne, impeccable, le gobelet de vin chaud toujours intact à la main. Un silence frémissant plane sur le petit groupe. Puis Madame Pichon éclate de rire, aussitôt suivie de tous les autres.", "그가 흠잡을 데 없는 모습으로 손에 뱅쇼 컵을 그대로 든 채 멀어진다. 작은 무리에 떨리는 침묵이 감돈다. 그러다 피숑 부인이 웃음을 터뜨리고 모두가 따라 웃는다."),
(P, "Un tableau Excel ! J'en suis très fière.", "엑셀 표라니! 정말 자랑스러워."),
(G, "Madame Pichon, vous m'avez ému. Et fait économiser vingt mille euros.", "피숑 부인, 감동했어요. 그리고 2만 유로를 아끼게 해 주셨어요."),
(P, "Comment ça ?", "무슨 말이니?"),
(G, "Il a baissé le prix de vingt mille euros par réflexe. Et vous venez de lui faire honte. Il remontera le prix lundi, vous verrez.", "그가 반사적으로 2만 유로를 내렸어요. 부인이 그에게 창피를 줬죠. 월요일에 가격을 올릴 거예요, 보세요."),
(A, "Tu crois ?", "그렇게 생각해?"),
(G, "J'ai trente-cinq ans de négociations dans les pattes, mon garçon. La honte est une monnaie très efficace.", "35년 협상 경력이 있어, 얘야. 창피는 아주 효과적인 화폐야."),
(L, "Gaston, c'est machiavélique.", "가스통, 마키아벨리 같아요."),
(G, "C'est commerçant. Je te l'avais dit.", "장사꾼의 방식이야. 말했잖아."),
(None, "La nuit commence à tomber. Dans les chalets du marché, les guirlandes s'allument une à une. Un orgue de Barbarie joue « Les Feuilles mortes » quelque part, un peu faux, avec beaucoup de cœur.", "밤이 내리기 시작한다. 시장 오두막들의 전구 줄이 하나둘 켜진다. 어딘가에서 손풍금이 '고엽'을 연주한다. 약간 음정이 틀리지만 마음은 가득 담겨 있다."),
(K, "Bon. Maintenant que nous avons humilié un cadre de Maison Vinum, je propose qu'on aille manger une raclette.", "자. 메종 비눔 간부를 망신 줬으니 라클레트를 먹으러 가자고 제안해요."),
(P, "Une raclette ? À dix-sept heures ?", "라클레트라고? 오후 5시에?"),
(K, "À Montmartre, en décembre, il est toujours l'heure d'une raclette.", "몽마르트르의 12월에는 늘 라클레트 먹을 시간이에요."),
(G, "(prend le bras de madame Pichon) Allons-y. J'invite. Un vieux caviste doit bien sacrifier un peu de dignité pour une raclette.", "(피숑 부인의 팔을 잡으며) 가자. 내가 낼게. 늙은 와인 상인은 라클레트를 위해 약간의 체면쯤은 버려야지."),
(None, "Ils s'éloignent tous les trois, bras dessus bras dessous. Léa et Antoine restent un moment, face aux lumières du marché.", "세 사람이 팔짱을 끼고 멀어진다. 레아와 앙투안이 시장의 불빛을 바라보며 잠시 남는다."),
(L, "Tu as entendu ? Cent soixante mille, puis peut-être cent quatre-vingt. Il y a vingt mille euros d'écart.", "들었어? 16만, 그리고 어쩌면 18만. 2만 유로 차이야."),
(A, "Vingt mille euros, c'est trois mois de travail pour un professeur. Mais c'est aussi la différence entre un prêt accordé et un prêt refusé.", "2만 유로는 교사에게 석 달 치 일이야. 하지만 대출이 승인되느냐 거절되느냐의 차이이기도 해."),
(L, "Notre rendez-vous à la banque, c'est jeudi.", "은행 약속이 목요일이야."),
(A, "Jeudi onze, dix heures. Madame Aubry, chargée d'affaires professionnelles. Margaux m'a dit qu'elle était redoutable.", "11일 목요일 10시. 직장인 창업 상담 담당 오브리 부인. 마르고가 무서운 사람이라고 했어."),
(L, "On sera prêts.", "준비돼 있을 거야."),
(A, "On sera prêts. (Il lui prend la main.) Mais pour l'instant, on est à un marché de Noël, dans le froid, sous des guirlandes.", "준비돼 있을 거야. (그녀의 손을 잡으며) 하지만 지금은 추운 크리스마스 마켓에서 전구 줄 아래 있어."),
(L, "(sourit) Et ça sent le vin chaud.", "(미소 지으며) 그리고 뱅쇼 냄새가 나."),
(A, "Détestable, selon Gaston.", "가스통 말로는 형편없는."),
(L, "Détestable et charmant. Comme tout ce qui compte.", "형편없고 매력적이지. 중요한 건 다 그래."),
(L, "Au fait, Noël. Ma mère veut absolument qu'on passe le vingt-quatre chez ton père. Elle dit que les deux familles doivent se rencontrer.", "그런데 크리스마스 말이야. 엄마가 24일을 꼭 네 아버지 집에서 보내자고 하셔. 두 집안이 만나야 한다고."),
(A, "Les deux familles dans la même cuisine ? Avec mon père et le tien ?", "두 집안이 같은 부엌에서? 우리 아버지랑 네 아버지랑?"),
(L, "Mon père a dit : « Je viendrai si on me promet qu'il y aura du vin et peu de discours. »", "아빠가 이렇게 말씀하셨어. '와인이 있고 연설이 적다고 약속하면 가겠다.'"),
(A, "Il sera servi. Le vin sera abondant, les discours courts. Mon père est un homme de peu de mots.", "그렇게 될 거야. 와인은 넉넉하고 연설은 짧을 거야. 우리 아버지는 말이 적은 분이니까."),
(L, "Les deux pères face à face. On pourrait vendre des billets.", "두 아버지가 마주 앉다니. 표를 팔 수도 있겠어."),
(A, "Je mettrai Margaux en arbitre.", "마르고를 심판으로 세울게."),
(L, "Parfait. Et Hugo à la guitare, pour détendre l'atmosphère.", "좋아. 그리고 위고가 기타로 분위기를 풀어 주고."),
(None, "Elle se serre contre lui. Au-dessus d'eux, une petite étoile en papier doré tourne lentement au vent, accrochée à la façade d'un chalet.", "그녀가 그에게 몸을 기댄다. 그들 위로 오두막 외벽에 매달린 금색 종이 별이 바람에 천천히 돈다."),
]
VOCAB = [
("A2","un marché de Noël / un chalet","크리스마스 마켓 / 오두막 가판","« un chalet tenu par une femme »"),
("A2","du vin chaud / la cannelle / le miel","뱅쇼 / 계피 / 꿀","크리스마스 마켓의 음료·향신료"),
("A2","une guirlande / une boule de Noël","전구 줄 / 크리스마스 볼","장식"),
("A2","un cadeau / un emballage cadeau","선물 / 선물 포장","« avec un emballage cadeau »"),
("B1","marchander / un prix","흥정하다 / 가격","« Vous marchandez bien, vous. »"),
("B1","un santon / un orgue de Barbarie","산통(프로방스 소인형) / 손풍금","크리스마스 마켓의 공예품과 소리"),
("B1","un clou de girofle / l'anis étoilé","정향 / 팔각","뱅쇼 재료"),
("B1","un gobelet / un étal","컵 / 가판대","« un étal de vin chaud »"),
("B2","un petit geste (de Noël)","작은 호의(할인)","« Je pourrais faire cent dix euros. Un petit geste. »"),
("B2","une indemnité d'immobilisation","계약 보류 보상금","거래를 묶어 두는 대가"),
("B2","un chargé d'affaires professionnelles","기업 고객 담당자","은행의 직위"),
("B2","un repreneur","인수자","« futur repreneur de La Cave des Abbesses »"),
("B2","une date butoir","마감일","« date butoir : le trente et un janvier »"),
("B2","opportuniste / prudent / réaliste","기회주의적인 / 신중한 / 현실적인","협상 상대의 성격을 말하는 어휘"),
("B2","humilier / faire honte","망신 주다 / 창피 주다","« Vous venez de lui faire honte. »"),
("B2","une raclette","라클레트(녹인 치즈 요리)","겨울 대표 음식"),
("C1","un petit geste commercial","소소한 상업적 호의","할인 협상에서의 표현"),
("C1","à la baisse / à la hausse","하향 / 상향","« une révision du prix à la baisse »"),
("C1","avoir trente-cinq ans de négociations dans les pattes","35년 협상 경력이 있다","dans les pattes: 구어적 '경력이 몸에 배어'"),
("C1","La honte est une monnaie très efficace.","창피는 아주 효과적인 화폐다.","가스통의 경구"),
("C1","Le mépris est une passion.","경멸은 열정이다.","피숑 부인의 일침"),
("C1","un tableau Excel","엑셀 표","냉소적 비유"),
("C1","la loi du marché","시장의 법칙","경제 논증의 상투어"),
("C1","par solidarité envers la tradition","전통에 대한 연대로","유머러스한 정당화"),
]
GRAM = [
("B1","si + 반과거 + 조건법: Si j'en prenais cinq, vous pourriez…",
 "« Si j'en prenais cinq, vous pourriez me faire un prix ? » 가정과 요청의 완곡한 결합. 협상에서 조건을 제안하는 정형 구문."),
("B2","Faites en sorte que + 접속법 / Il faut que ça marche",
 "« Faites en sorte que ça marche. » faire en sorte que + 접속법 = ~하도록 힘쓰다. 29화 « je ferai en sorte que » 복습. 명령법과 접속법의 결합."),
("B2","조건 표현: dans le cadre de / au moment opportun",
 "« Dans le cadre de la négociation, au moment opportun. » 격식 있는 협상 어휘. 전치사구가 문장의 틀을 정리해 준다."),
("B2","의문과 반문: « Prudents, ou opportunistes ? »",
 "짧은 이항 질문으로 상대의 의도를 찌르는 수사적 의문. 구어에서는 억양만으로도 충분하다."),
("B2","근접과거와 최근 사실: Vous venez de lui faire honte.",
 "« Vous venez de lui faire honte. » venir de + inf. = 방금 ~했다. 사건의 직후를 말할 때."),
("C1","대명사 y와 en의 결합: Il y en a vingt mille",
 "« Il y a vingt mille euros d'écart. » 비인칭 il y a 구문과 수량. « J'en ai marre. » 등 en의 관용 표현."),
("C1","c'est ce qui fait son charme / c'est ce que",
 "« C'est ce qui fait son charme. » ce qui + 동사: 주어 관계대명사절. « C'est ce que je voulais dire. » 강조 분열문."),
("C1","대조 공식: X est détestable. C'est ce qui fait son charme.",
 "부정적 형용사로 시작해 반전의 칭찬으로 끝내는 프랑스식 역설. 가스통의 말버릇이며 이야기 곳곳에서 반복된다."),
]
CULTURE = [
("프랑스의 크리스마스 마켓과 vin chaud",
 "12월의 프랑스 도시에는 마르셰 드 노엘이 열려 뱅쇼(vin chaud), 군밤, 라클레트, 수공예 장식을 판다. 뱅쇼는 레드 와인에 오렌지·정향·계피·팔각을 넣어 데운 겨울 음료이며 끓이지 않는 것이 요령이다."),
("프랑스의 협상 문화: marchander",
 "프랑스 시장의 수공예품 가판에서는 흥정(marchander)이 가능하지만 상점에서는 보통 정가다. 'un petit geste'(작은 호의)라 부르는 소소한 할인이나 서비스가 대화로 오가는 경우가 많다."),
("Maison Vinum의 압박 전술",
 "소규모 상점을 인수하려는 체인은 가격 인하와 기한 압박(indemnité d'immobilisation)으로 협상한다. 상인의 정서적 가치를 모르는 '엑셀 표의 논리'와 지역 상인의 신뢰는 이 이야기의 대비 주제다."),
]
META = dict(part=4, ep=37, part_label="제4부 그랑 크뤼 · Grand cru", title_fr="Marché de Noël", title_ko="크리스마스 마켓",
 place="몽마르트르 크리스마스 마켓 · 12월 6일 토요일 오후 4시",
 chars="Léa · Antoine · Gaston · Mme Pichon · Karim · La marchande · M. Delaunay (메종 비눔 대표)",
 wine="Vin chaud (뱅쇼) · Morgon",
 focus="흥정·협상 표현, 조건·완곡 어법, 경제 어휘, 경구와 역설, faire en sorte que",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제38화 « Reprendre la cave » : 가스통의 가게에서 열린 첫 번째 실무 회의. 마르고와 카림이 숫자를 파고들고 가스통은 35년의 장부를 꺼낸다.")
