# -*- coding: utf-8 -*-
G, L, A, P, K, M = "Gaston", "Léa", "Antoine", "Mme Pichon", "Karim", "Margaux"
D = [
(None, "Lundi 8 décembre, 19 h. La Cave des Abbesses, rideau baissé. Sur le comptoir, quatre grands registres reliés de toile, une calculatrice à manivelle, un ordinateur portable, des sandwiches et du thé. Au mur, un tableau blanc que Karim a apporté. Autour du comptoir : Gaston, Madame Pichon, Karim, Léa, Antoine, et Margaux, arrivée de Nantes par le train de dix-sept heures, en tailleur gris et lunettes d'écaille.", "12월 8일 월요일 저녁 7시. 라 카브 데 자베스, 셔터가 내려져 있다. 카운터 위에는 천으로 장정된 큰 장부 네 권, 수동 계산기, 노트북, 샌드위치와 차가 있다. 벽에는 카림이 가져온 화이트보드. 카운터 둘레에 가스통, 피숑 부인, 카림, 레아, 앙투안, 그리고 17시 열차로 낭트에서 온 회색 투피스에 대모 안경을 쓴 마르고가 있다."),
(M, "Bon. Avant de commencer, je pose les règles. Un : tout ce qui se dit ici est confidentiel. Deux : personne ne ment, même par politesse. Trois : on ne s'offusque pas des chiffres.", "자. 시작하기 전에 규칙을 정할게요. 하나, 여기서 오가는 얘기는 기밀이에요. 둘, 예의상이라도 거짓말하지 않기. 셋, 숫자 앞에서 기분 상하지 않기."),
(G, "Mademoiselle Delcourt, vous êtes sévère.", "델쿠르 양, 엄격하시네요."),
(M, "Je suis avocate, monsieur Roussel. Et la sévérité est la seule forme de politesse que les banques respectent.", "전 변호사예요, 루셀 씨. 그리고 엄격함은 은행이 존중하는 유일한 예의죠."),
(P, "Elle me plaît, cette petite.", "이 아가씨 마음에 드네."),
(M, "Merci, madame. Alors, monsieur Roussel : nous devons examiner les comptes des trois dernières années. Où sont-ils ?", "감사합니다, 부인. 그럼 루셀 씨, 최근 삼 년 치 장부를 검토해야 해요. 어디 있죠?"),
(G, "(pose les registres sur le comptoir, avec solennité) Ici.", "(엄숙하게 장부들을 카운터에 올려놓으며) 여기."),
(K, "(regarde, effaré) Ce sont... des cahiers ?", "(질겁하며 바라보며) 이건... 공책이에요?"),
(G, "Des registres comptables. J'écris tout à la main depuis mille neuf cent quatre-vingt-dix.", "회계 장부야. 1990년부터 전부 손으로 쓰고 있어."),
(K, "Gaston, je pense que nous avons un problème méthodologique.", "가스통, 방법론적인 문제가 있는 것 같아요."),
(G, "Quel problème ? Mes chiffres sont justes.", "무슨 문제? 내 숫자는 정확해."),
(K, "Je n'en doute pas. Mais je vais devoir les recopier un par un dans un tableur. Ça va me prendre dix heures.", "의심하지 않아요. 하지만 하나하나 표 계산 프로그램에 옮겨야 해요. 열 시간쯤 걸리겠어요."),
(G, "Prends ton temps. Moi, j'ai trente-cinq ans.", "천천히 해. 난 35년이 있잖아."),
(M, "Karim, tu t'en occupes ce soir. En attendant, résumons ce que nous savons. Monsieur Roussel, quel est le chiffre d'affaires de l'année dernière ?", "카림, 오늘 밤 맡아 줘. 그동안 아는 걸 정리하죠. 루셀 씨, 작년 매출이 얼마죠?"),
(G, "Deux cent douze mille euros.", "21만 2천 유로."),
(M, "Hors taxe ?", "세금 제외인가요?"),
(G, "Hors taxe.", "세금 제외예요."),
(M, "La marge brute ?", "매출총이익은요?"),
(G, "Trente-huit pour cent, en moyenne. Plus sur les vins de petits producteurs, moins sur les grands crus et le champagne.", "평균 38퍼센트야. 소규모 생산자 와인은 더 높고 그랑 크뤼와 샴페인은 낮고."),
(K, "(écrit au tableau) Deux cent douze mille, marge de trente-huit pour cent. Ça fait quatre-vingt mille cinq cent soixante.", "(칠판에 쓰며) 21만 2천에 마진 38퍼센트. 8만 560이에요."),
(M, "Charges fixes ?", "고정비는요?"),
(G, "Le loyer : mille huit cent cinquante euros par mois. L'électricité, l'assurance, l'expert-comptable : environ huit mille par an. Les cotisations sociales... (il hésite).", "임대료는 월 1,850유로. 전기, 보험, 회계사 비용은 연 약 8천. 사회보험료는... (망설인다)."),
(M, "Oui ?", "네?"),
(G, "Je me suis versé un salaire de quatorze mille euros l'année dernière.", "작년에 내 월급으로 1만 4천 유로를 가져갔어."),
(L, "(surprise) Quatorze mille euros ? Pour un an de travail ?", "(놀라며) 1만 4천 유로요? 일 년 일하고요?"),
(G, "Je n'avais pas besoin de plus.", "더 필요 없었어."),
(A, "Gaston. Un an à travailler soixante heures par semaine pour quatorze mille euros, ce n'est pas un salaire, c'est un sacrifice.", "가스통. 주당 60시간씩 일 년 일하고 1만 4천 유로는 월급이 아니라 희생이에요."),
(G, "C'est ma façon de faire.", "내 방식이야."),
(M, "(prend des notes) Ce qui signifie que la rentabilité réelle de la boutique est plus élevée qu'il n'y paraît, si on la gérait avec un salaire normal. Mais aussi que le niveau de vie du gérant précédent était artificiellement bas.", "(메모하며) 즉 정상 급여로 운영한다면 가게의 실제 수익성은 보이는 것보다 높다는 뜻이에요. 하지만 전임 경영자의 생활 수준이 인위적으로 낮았다는 뜻이기도 하고요."),
(L, "Ce qui veut dire que nous devrons nous payer plus que lui.", "그 말은 우리가 가스통보다 월급을 더 가져가야 한다는 거네요."),
(M, "Ce qui veut dire que le projet doit générer assez pour payer deux salaires décents. Sinon, il n'est pas viable.", "프로젝트가 괜찮은 월급 두 개를 낼 만큼 벌어야 한다는 뜻이죠. 아니면 지속 가능하지 않아요."),
(K, "(lève la main) Une question. La valeur du stock ?", "(손을 들며) 질문이에요. 재고의 가치는요?"),
(G, "Environ soixante et un mille euros. Je l'ai évaluée en octobre.", "약 6만 1천 유로예요. 10월에 평가했어."),
(K, "À quel prix ? Achat ou vente ?", "어떤 가격으로요? 매입가요 아니면 판매가요?"),
(G, "Prix d'achat.", "매입가야."),
(M, "Hum. Il y a une chose que je voudrais comprendre. Combien de bouteilles vendez-vous par an, en moyenne ?", "흠. 이해하고 싶은 게 하나 있어요. 평균적으로 일 년에 몇 병을 파세요?"),
(G, "Environ dix mille. Un peu plus, certaines années.", "대략 1만 병. 어떤 해엔 조금 더 팔고."),
(M, "Et le stock moyen en cave ?", "그리고 지하실의 평균 재고는요?"),
(G, "Environ trois mille bouteilles. Dont quatre cents « particulières ».", "약 3천 병. 그중 400병은 '특별한' 병이야."),
(M, "« Particulières » ? C'est-à-dire ?", "'특별한'이라니, 무슨 뜻이죠?"),
(G, "Des vieux millésimes. Des bouteilles que je garde pour des occasions que je n'ai jamais trouvées.", "오래된 빈티지들이야. 한 번도 찾지 못한 기회를 위해 보관하는 병들."),
(A, "Combien d'années, ces vieux millésimes ?", "얼마나 오래된 빈티지예요?"),
(G, "Trente, quarante ans, pour certaines. J'en ai de mille neuf cent soixante-quatorze. J'en ai de mille neuf cent soixante-dix.", "어떤 건 삼사십 년 됐어. 1974년산도 있고 1970년산도 있어."),
(P, "(les yeux ronds) Gaston ! Tu as du Saint-Émilion de mille neuf cent soixante-quatorze ?", "(눈이 휘둥그레져) 가스통! 1974년산 생테밀리옹이 있어?"),
(G, "Une caisse de douze. Je l'avais mise de côté pour votre anniversaire, madame Pichon.", "열두 병 한 상자요. 부인 생신 때를 위해 따로 챙겨 뒀어요."),
(P, "(très émue) Mon anniversaire, c'est en mars.", "(깊이 감동하여) 내 생일은 3월이야."),
(G, "Je n'ai pas dit lequel.", "어느 해인지는 말 안 했어요."),
(M, "(frappe le comptoir du plat de la main) Messieurs, mesdames, revenons au sujet. Ces quatre cents bouteilles, sont-elles inscrites au stock, à leur valeur d'achat ?", "(손바닥으로 카운터를 치며) 여러분, 주제로 돌아와요. 그 400병은 매입가로 재고에 기재돼 있나요?"),
(G, "À leur valeur d'achat, oui. Une moyenne de vingt euros la bouteille.", "매입가로요. 평균 병당 20유로."),
(K, "Vingt euros ? Sur un marché de vins de collection, certaines de ces bouteilles valent dix fois plus.", "20유로요? 수집가용 와인 시장에서는 그중 일부가 열 배는 나가요."),
(G, "Possible.", "그럴 수도."),
(K, "(tapote sur son ordinateur) J'ai fait une recherche rapide sur les prix de vente aux enchères : un Pomerol de mille neuf cent soixante-dix, bien conservé, peut valoir quatre cents euros. Un Hermitage de mille neuf cent soixante-dix-huit, trois cents.", "(노트북을 두드리며) 경매 낙찰가를 빠르게 검색했어요. 보관 상태가 좋은 1970년산 포므롤은 400유로, 1978년산 에르미타주는 300유로까지 해요."),
(M, "Donc si, en moyenne, vos quatre cents bouteilles valent cent euros chacune sur le marché, cela fait quarante mille euros de réserve, contre huit mille au bilan.", "그러니까 그 400병이 평균 병당 100유로라면 시장 가치 4만 유로인데 장부에는 8천 유로네요."),
(G, "(abasourdi) Quarante mille euros ?", "(어안이 벙벙하여) 4만 유로요?"),
(M, "C'est une hypothèse. Mais il est probable que la vraie valeur soit proche de cette estimation. Il faudra faire expertiser tout ça.", "가정이에요. 하지만 실제 가치가 이 추정치에 가까울 가능성이 높아요. 전부 감정받아야 해요."),
(L, "(à Gaston) Tu es assis sur un trésor depuis trente-cinq ans.", "(가스통에게) 35년 동안 보물 위에 앉아 있었네요."),
(G, "Je ne le savais pas. Je pensais seulement que c'étaient de belles bouteilles.", "몰랐어. 그냥 예쁜 병이라고만 생각했지."),
(A, "C'est tout de même un peu fou. Un caviste qui ne connaît pas la valeur de son stock.", "그래도 좀 미친 일이야. 자기 재고 가치를 모르는 와인 상인이라니."),
(G, "Antoine, je connais la valeur des bouteilles. Je ne connais pas leur prix. Il y a une différence.", "앙투안, 난 병의 가치를 알아. 가격은 몰라. 차이가 있지."),
(M, "(sourit) C'est la plus belle réponse qu'on m'ait faite dans un audit comptable.", "(미소 지으며) 회계 감사에서 들은 가장 아름다운 대답이네요."),
(K, "Alors, ça change quoi, pour la banque ?", "그럼 은행에는 어떤 변화가 있어요?"),
(M, "Beaucoup de choses. Si on peut démontrer que le fonds de commerce, avec le stock réévalué, vaut deux cent vingt mille euros plutôt que cent soixante mille, le rapport apport/emprunt devient beaucoup plus favorable.", "많은 게 달라져요. 재고를 재평가한 영업권이 16만이 아닌 22만 유로임을 입증하면 자기 자본 대비 대출 비율이 훨씬 유리해져요."),
(A, "Mais Maison Vinum a baissé le prix à cent soixante mille.", "하지만 메종 비눔이 가격을 16만으로 내렸잖아."),
(M, "Parce qu'ils ne connaissent pas la valeur réelle du stock. Ou qu'ils feignent de l'ignorer. Quoi qu'il en soit, ce n'est pas notre problème : nous, nous n'achetons pas à Vinum, nous achetons à monsieur Roussel.", "그들은 재고의 실제 가치를 모르니까요. 또는 모르는 척하거나. 어쨌든 우리 문제는 아니에요. 우리는 비눔에서 사는 게 아니라 루셀 씨에게서 사니까."),
(G, "(redresse la tête) Et à quel prix m'achetez-vous ?", "(고개를 들며) 그럼 얼마에 사실 건가요?"),
(M, "Cela dépend de vous. Les services du notaire proposent une évaluation à cent quatre-vingt mille. Mais c'est à vous de décider si vous voulez le vendre plus cher à des étrangers ou moins cher à des amis.", "당신에게 달렸어요. 공증인은 18만 유로로 평가해요. 하지만 낯선 사람에게 더 비싸게 팔지, 친구에게 더 싸게 팔지는 당신이 결정할 몫이에요."),
(G, "(regarde Léa et Antoine, longuement) Je vous le vends au prix de cent quatre-vingt mille. Pas un euro de moins. Pas un euro de plus.", "(레아와 앙투안을 오래 바라보며) 18만 유로에 팔겠다. 1유로도 덜 받지 않고 1유로도 더 받지 않을 거다."),
(L, "Gaston, c'est la valeur du notaire. Ce n'est pas une faveur.", "가스통, 그건 공증인의 평가액이에요. 호의가 아니에요."),
(G, "Ce n'est pas une faveur, c'est une règle. Je ne vends pas ma boutique à perte. Mais je ne la vends pas non plus en faisant payer l'amitié.", "호의가 아니라 원칙이야. 손해 보고 파는 게 아니야. 그렇다고 우정에 값을 매겨 파는 것도 아니고."),
(P, "Voilà. C'est exactement ce que j'aurais dit.", "그래. 내가 하려던 말이야."),
(M, "Très bien. Je rédige donc un avant-contrat sur cette base. Reste à régler le bail commercial. Monsieur Roussel, avez-vous le contrat de bail ?", "좋아요. 그럼 이 가격으로 가계약서를 작성할게요. 상업 임대차 계약이 남았네요. 루셀 씨, 임대 계약서가 있나요?"),
(G, "Dans le tiroir du bureau, derrière. Un bail trois-six-neuf.", "뒤편 사무실 서랍에 있어. 3-6-9 임대차야."),
(A, "Trois-six-neuf ?", "3-6-9요?"),
(M, "C'est la durée classique d'un bail commercial en France : neuf ans, avec une possibilité de résiliation pour le locataire à la fin de chaque période de trois ans.", "프랑스 상업 임대차의 표준 기간이에요. 9년이고 세입자는 3년마다 해지할 수 있어요."),
(K, "Et notre bail, il se termine quand ?", "우리 계약은 언제 끝나요?"),
(G, "Dans dix-huit mois. Mais le propriétaire est un vieil ami, il m'a dit qu'il le renouvellerait si je lui faisais une jolie vitrine.", "18개월 뒤야. 하지만 집주인이 오랜 친구인데 예쁜 진열창을 만들어 주면 갱신해 주겠다고 했어."),
(L, "Une jolie vitrine ? Voilà qui tombe bien : je suis graphiste.", "예쁜 진열창이라고요? 마침 잘됐네요. 제가 디자이너예요."),
(G, "(sourit) Je crois que j'ai perdu mon temps, pendant trente-cinq ans, à chercher de l'aide. Elle était à deux rues.", "(미소 지으며) 35년 동안 도움을 찾느라 시간을 낭비한 것 같아. 두 골목 떨어진 곳에 있었는데."),
(M, "Bon. Récapitulons. Un : un fonds de commerce à cent quatre-vingt mille. Deux : un stock à réévaluer. Trois : un bail à renouveler. Quatre : un prêt bancaire à obtenir, de cent trente mille euros, plus ou moins.", "자, 정리하죠. 하나, 18만 유로 영업권. 둘, 재평가할 재고. 셋, 갱신할 임대차. 넷, 약 13만 유로 은행 대출을 받아야 하고요."),
(A, "Et le rendez-vous est jeudi, à dix heures.", "그리고 약속은 목요일 10시야."),
(M, "Jeudi, dix heures, avec madame Aubry. Je vais vous préparer. Léa, tu t'occupes des supports visuels. Antoine, tu prépares l'argumentaire sur l'expertise œnologique. Karim, tu finis le tableur ce soir.", "목요일 10시, 오브리 부인과. 준비시켜 줄게요. 레아, 시각 자료를 맡아. 앙투안, 와인 전문성에 대한 논거를 준비해. 카림, 오늘 밤에 표 계산을 끝내."),
(None, "Quelques heures plus tard. La boutique est presque vide. Karim dort sur le comptoir, la tête sur un registre ouvert, un doigt encore posé sur une colonne de chiffres. Margaux, assise dans un coin, annote un dossier à la lueur d'une lampe. Léa et Antoine, côte à côte sur un tabouret, se tiennent la main.", "몇 시간 뒤. 가게는 거의 비었다. 카림이 펼쳐진 장부에 머리를 대고 한 손가락을 숫자 열 위에 얹은 채 카운터에서 잠들어 있다. 마르고가 구석에 앉아 램프 불빛으로 서류에 주석을 단다. 레아와 앙투안이 스툴에 나란히 앉아 손을 잡고 있다."),
(G, "(depuis l'arrière-boutique, chuchotant) Léa. Antoine. Venez voir quelque chose.", "(창고에서 속삭이며) 레아. 앙투안. 와서 뭘 좀 봐."),
(None, "Ils le suivent dans l'arrière-boutique. Gaston soulève une trappe. Un escalier de pierre descend dans la cave, éclairée par une ampoule nue.", "그들이 그를 따라 창고로 들어간다. 가스통이 뚜껑 문을 올린다. 맨 전구가 비추는 돌계단이 지하실로 내려간다."),
(G, "Vous n'êtes jamais descendus. Venez.", "너희는 한 번도 안 내려가 봤지. 와."),
(L, "(émerveillée en descendant) Oh. C'est...", "(내려가며 경탄하여) 오. 이건..."),
(A, "Une cathédrale de bouteilles.", "병들의 대성당이네."),
(None, "Dans la pénombre fraîche, des centaines de bouteilles couchées, sur des étagères de pierre, couvertes d'une fine poussière. L'air a une odeur de terre, de pierre humide et de très vieux vin.", "서늘한 어둠 속에서 돌 선반 위에 눕힌 수백 병이 고운 먼지를 쓰고 있다. 공기에서는 흙, 젖은 돌, 아주 오래된 와인의 냄새가 난다."),
(G, "Voilà. Voilà ma vie.", "자. 이게 내 삶이야."),
(L, "(touche une bouteille) Elle est tiède.", "(병 하나를 만지며) 미지근해."),
(G, "Douze degrés, toute l'année. Comme les crayères de Reims. La pierre fait le travail.", "일 년 내내 12도야. 랭스의 크레예르처럼. 돌이 일을 하지."),
(A, "(à voix basse) Gaston, je comprends maintenant pourquoi tu ne voulais pas vendre à une chaîne.", "(작은 소리로) 가스통, 왜 체인점에 팔고 싶지 않았는지 이제 알겠어."),
(G, "Une chaîne n'aurait pas compris. Elle aurait fait un inventaire, une vente à prix cassé. Eux, ils auraient vendu mes souvenirs à des collectionneurs de Hong Kong.", "체인은 이해하지 못했을 거야. 재고 조사를 하고 헐값에 팔았겠지. 내 추억을 홍콩 수집가들에게 팔았을 거야."),
(L, "Nous, on ne le fera pas.", "우리는 그러지 않을 거예요."),
(G, "Je le sais. C'est pour ça que je vous ai fait descendre.", "알아. 그래서 너희를 내려오게 한 거야."),
(None, "Il s'approche d'une étagère, retire délicatement une bouteille couchée, la lève à la lumière. L'étiquette est jaunie, à moitié effacée.", "그가 선반으로 다가가 눕힌 병 하나를 조심스럽게 빼서 불빛에 비춘다. 라벨은 누렇게 바랬고 반쯤 지워졌다."),
(G, "Mille neuf cent quatre-vingt-dix. Mon premier millésime en tant que caviste. Celui de mon année d'ouverture. Je n'ai jamais voulu le vendre.", "1990년. 와인 상인으로서의 첫 빈티지야. 개업한 해의 와인이지. 한 번도 팔고 싶지 않았어."),
(A, "Qu'est-ce que c'est ?", "뭐예요?"),
(G, "Un Morgon. Évidemment.", "모르공이지. 당연히."),
(L, "(sourit, ému) Évidemment.", "(감동하여 미소 지으며) 당연하죠."),
(G, "Je le garde pour le jour de la signature. Le jour où vous recevrez les clés. Vous l'ouvrirez ici, sur le comptoir, devant tout le monde.", "서명하는 날을 위해 간직할게. 너희가 열쇠를 받는 날. 여기 카운터에서 모두가 보는 앞에서 따라."),
(A, "Tu ne l'ouvres pas avec nous ?", "우리와 함께 열지 않을 거야?"),
(G, "Si. Mais ce sera à vous de choisir quand. Je ne veux plus décider du moment à la place de personne.", "열 거야. 하지만 언제인지는 너희가 정해. 더는 누구를 대신해 때를 정하고 싶지 않아."),
(L, "(un souffle) Merci, Gaston.", "(숨을 내쉬며) 고마워요, 가스통."),
(G, "Remontons. J'ai froid aux genoux, et Madame Pichon va s'inquiéter si on disparaît trop longtemps dans ma cave.", "올라가자. 무릎이 시리고 우리가 지하실에서 너무 오래 사라지면 피숑 부인이 걱정할 거야."),
]
VOCAB = [
("A2","un registre / une calculatrice / un tableau blanc","장부 / 계산기 / 화이트보드","회의 소품"),
("A2","un sandwich / un thé / une lampe","샌드위치 / 차 / 램프","저녁 회의의 풍경"),
("A2","un escalier de pierre / une cave","돌계단 / 지하실","« une cathédrale de bouteilles »"),
("B1","un tailleur / des lunettes d'écaille","투피스 / 대모 안경","마르고의 외모"),
("B1","confidentiel / s'offusquer","기밀의 / 불쾌해하다","« On ne s'offusque pas des chiffres. »"),
("B1","recopier / un tableur","옮겨 쓰다 / 표 계산 프로그램","« recopier dans un tableur »"),
("B1","la marge brute / le chiffre d'affaires","매출총이익 / 매출","« trente-huit pour cent »"),
("B1","un loyer / une charge fixe","임대료 / 고정비","« Charges fixes ? »"),
("B2","la rentabilité / viable","수익성 / 지속 가능한","« Il n'est pas viable. »"),
("B2","un vin de collection / une vente aux enchères","수집용 와인 / 경매","« les prix de vente aux enchères »"),
("B2","un bail commercial 3-6-9","3-6-9 상업 임대차","9년, 3년마다 해지 가능"),
("B2","un avant-contrat","가계약서","« un avant-contrat sur cette base »"),
("B2","un audit comptable","회계 감사","« dans un audit comptable »"),
("B2","expertiser / une expertise","감정하다 / 감정","« Il faudra faire expertiser tout ça. »"),
("B2","un argumentaire","논거 자료","« l'argumentaire sur l'expertise œnologique »"),
("B2","feindre / ignorer","~인 척하다 / 모르다","« ou qu'ils feignent de l'ignorer »"),
("C1","vendre à perte / à prix cassé","손해 보고 팔다 / 헐값에 팔다","« Je ne vends pas ma boutique à perte. »"),
("C1","une cathédrale de bouteilles","병들의 대성당","시적 표현"),
("C1","faire payer l'amitié","우정에 값을 매기다","가스통의 원칙"),
("C1","être assis sur un trésor","보물 위에 앉아 있다","모르고 가진 가치를 가리키는 표현"),
("C1","au bilan","결산서에","« huit mille au bilan »"),
("C1","Je connais la valeur, pas le prix.","가치는 알지만 가격은 모른다.","가스통의 명언"),
("C1","avoir froid aux genoux","무릎이 시리다","노령의 약점을 유머로"),
("C1","une trappe","뚜껑 문","지하실 입구"),
]
GRAM = [
("B1","양화·확률 표현: il est probable que / il est possible que",
 "« Il est probable que la vraie valeur soit proche de cette estimation. » probable que + 직설법/접속법(부정·의문은 접속법). possible que + 접속법. 확률의 정도를 표현."),
("B2","가능성의 여러 층위: peut-être / il se peut que / sans doute / sûrement",
 "« Possible. » « Peut-être. » « Sans doute. » « Il se peut que… » 확신의 정도를 조정하는 부사·구문. 협상·논증에 필수."),
("B2","quoi qu'il en soit / en tout cas / de toute façon",
 "« Quoi qu'il en soit, ce n'est pas notre problème. » quoi qu'il en soit = 어쨌든. 논점을 정리하고 결론으로 가는 접속어."),
("B2","c'est-à-dire / à savoir / autrement dit",
 "« Particulières ? C'est-à-dire ? » « Autrement dit, ... » 설명을 요구하거나 바꾸어 말할 때."),
("B2","명령법과 역할 분담: Tu t'occupes de / Tu prépares",
 "« Léa, tu t'occupes des supports visuels. » 현재형이 명령 역할. 팀 업무 분장에서 자주 쓰는 구어체."),
("C1","si / à condition que / pourvu que (복습)",
 "« Il m'a dit qu'il le renouvellerait si je lui faisais une jolie vitrine. » 간접화법 + 조건법 + si 반과거."),
("C1","대명사 en의 수량: J'en ai de 1974 / J'en ai de 1970",
 "« J'en ai de mille neuf cent soixante-quatorze. » en + 동사 + de + 명사(수식어). 한정 수식어가 있을 때 en은 부분을 가리키고 de를 쓴다."),
("C1","수사법: litote와 완곡",
 "« Je n'ai pas dit lequel. » « Ce n'est pas une faveur, c'est une règle. » 부정으로 긍정을 말하는 완서법과 대조. 문어체의 품격을 낳는 장치."),
]
CULTURE = [
("프랑스 상업 임대차 3-6-9",
 "bail commercial 3-6-9는 9년 계약이지만 세입자가 3년마다 해지할 수 있는 프랑스 특유의 상업 임대차다. 가게를 인수할 때 임대차 승계·갱신 조건이 영업권 가치에 큰 영향을 준다."),
("재고의 숨은 가치",
 "와인 가게는 오래된 빈티지 재고를 매입가 그대로 장부에 두는 경우가 많다. 경매 시장에서는 보관 상태가 좋은 빈티지가 몇 배로 거래되기도 해 영업권 평가에 큰 영향을 준다. 재평가는 전문 감정사(expert)가 맡는다."),
("프랑스의 변호사와 기업 인수",
 "영업권 양도(cession de fonds de commerce)에는 변호사 또는 공증인이 개입한다. 가계약(avant-contrat), 임대차 승계, 대출 보증이 한 묶음으로 진행되며 마르고의 직업이 이야기에서 중요한 역할을 한다."),
]
META = dict(part=4, ep=38, part_label="제4부 그랑 크뤼 · Grand cru", title_fr="Reprendre la cave", title_ko="와인 가게를 이어받다",
 place="La Cave des Abbesses (영업 후) · 12월 8일 월요일 19시",
 chars="Léa · Antoine · Gaston · Mme Pichon · Karim · Margaux",
 wine="Morgon 1990 (가스통의 개업 빈티지) · 오래된 1970~78년 보르도·론 재고",
 focus="경영 어휘, 가능성·확률 표현, quoi qu'il en soit, 연결어, 협상의 완서법",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제39화 « Rendez-vous à la banque » : 12월 11일 목요일 10시. 오브리 부인 앞에서 준비한 모든 숫자를 설명해야 한다. 은행의 격식 어법과 예상치 못한 거절.")
