# -*- coding: utf-8 -*-
L, A, M, B = "Léa", "Antoine", "Margaux", "Mme Aubry"
D = [
(None, "Jeudi 11 décembre, 9 h 50. Agence du Crédit Montmartrois, boulevard de Clichy. Un hall de marbre gris, des fauteuils en cuir, une hôtesse qui parle à voix basse. Léa, Antoine et Margaux, assis côte à côte sur un canapé, tiennent chacun un classeur identique, relié de ruban noir.", "12월 11일 목요일 오전 9시 50분. 클리시 대로의 크레디 몽마르트루아 지점. 회색 대리석 홀, 가죽 의자, 낮은 목소리로 말하는 안내원. 레아, 앙투안, 마르고가 소파에 나란히 앉아 각자 검은 리본으로 묶은 똑같은 바인더를 들고 있다."),
(L, "(à voix basse) J'ai les mains moites.", "(작은 소리로) 손에 땀이 나."),
(M, "(à voix basse) Respire. Elle ne te mangera pas. Elle ne mange que les dossiers mal préparés.", "(작은 소리로) 숨 쉬어. 널 먹지는 않아. 준비 안 된 서류만 먹지."),
(A, "(à voix basse) C'est rassurant, comme tout ce que dit ma sœur.", "(작은 소리로) 우리 누나가 하는 말이 다 그렇듯 안심되네."),
(M, "(à voix basse) Rappelez-vous : vous êtes calmes, précis, concis. Vous répondez à la question posée, pas à celle que vous aimeriez qu'on vous pose.", "(작은 소리로) 기억해. 침착하고 정확하고 간결하게. 던져진 질문에 대답하는 거지 자기가 받고 싶은 질문에 대답하는 게 아니야."),
(None, "Une porte s'ouvre. Une femme d'une cinquantaine d'années, tailleur anthracite, cheveux argentés coupés court, avance d'un pas régulier. Elle tient un dossier sous le bras.", "문이 열린다. 오십 안팎의 여성이 짙은 회색 투피스에 은빛 짧은 머리로 규칙적인 걸음으로 걸어온다. 겨드랑이에 서류를 끼고 있다."),
(B, "Madame Fontaine, monsieur Delcourt, maître Delcourt. Bonjour. Camille Aubry. Si vous voulez bien me suivre.", "퐁텐 씨, 델쿠르 씨, 델쿠르 변호사님. 안녕하세요. 카미유 오브리입니다. 따라와 주시겠어요?"),
(None, "Elle les conduit dans un bureau vitré. Une table ovale, trois chaises, un tableau abstrait au mur. Elle s'assoit, ouvre le dossier, chausse des lunettes fines.", "그녀가 유리로 된 사무실로 안내한다. 타원형 탁자, 의자 세 개, 벽에 걸린 추상화. 그녀가 앉아 서류를 열고 가는 안경을 쓴다."),
(B, "Alors. Si j'ai bien compris, vous souhaitez emprunter cent trente mille euros pour reprendre le fonds de commerce d'une boutique de vin située dans le dix-huitième arrondissement.", "자. 제가 제대로 이해했다면 18구에 있는 와인 가게의 영업권을 인수하기 위해 13만 유로를 대출받고 싶으시군요."),
(L, "C'est exact, madame.", "맞습니다, 부인."),
(B, "Pouvez-vous me présenter votre projet en cinq minutes ?", "프로젝트를 오 분 안에 설명해 주시겠어요?"),
(L, "Bien sûr. La Cave des Abbesses existe depuis trente-cinq ans, dans la rue des Abbesses, à Montmartre. Elle réalise deux cent douze mille euros de chiffre d'affaires, avec une marge brute de trente-huit pour cent. Son propriétaire, Monsieur Gaston Roussel, prend sa retraite et n'a pas de successeur.", "물론입니다. 라 카브 데 자베스는 몽마르트르 아베스 거리에서 35년 동안 존재했습니다. 매출은 21만 2천 유로이고 총이익률은 38퍼센트입니다. 소유주 가스통 루셀 씨가 은퇴하는데 후계자가 없습니다."),
(B, "Et vous proposez de le remplacer, tous les deux. Quelle est votre expérience commerciale ?", "그래서 두 분이 그를 대체하겠다는 거군요. 상업 경험은 어떻게 되시나요?"),
(A, "Mon expérience est limitée, madame. Je suis professeur d'histoire. Mais je suis fils de vigneron : j'ai participé aux vendanges pendant douze ans, je connais la production du vin de l'intérieur.", "제 경험은 제한적입니다, 부인. 저는 역사 교사입니다. 하지만 와인 농부의 아들로 12년 동안 수확에 참여해 와인 생산을 안에서 알고 있습니다."),
(B, "Les vendanges ne sont pas la gestion d'un point de vente.", "수확이 매장 운영은 아니죠."),
(A, "Vous avez raison. C'est pourquoi nous avons constitué une équipe : Maître Margaux Delcourt pour le juridique, Monsieur Karim Haddad pour l'analyse financière et la logistique, et Monsieur Gaston Roussel, qui restera conseiller pendant au moins deux ans.", "맞습니다. 그래서 팀을 꾸렸습니다. 법률은 마르고 델쿠르 변호사, 재무 분석과 물류는 카림 하다드 씨, 그리고 최소 이 년은 고문으로 남을 가스통 루셀 씨입니다."),
(B, "(note) Et vous, madame Fontaine ?", "(메모하며) 퐁텐 씨는요?"),
(L, "Je suis graphiste indépendante depuis six ans. J'ai géré mon propre budget, mes propres factures, et mes propres clients. J'ai aussi créé des identités visuelles pour des commerces et des marques de produits alimentaires.", "6년째 독립 그래픽 디자이너입니다. 제 예산, 청구서, 고객을 직접 관리했습니다. 또한 상점과 식품 브랜드의 비주얼 아이덴티티를 만들었습니다."),
(B, "Vos revenus sont irréguliers, d'après votre déclaration d'impôts.", "세금 신고서를 보면 수입이 불규칙하네요."),
(L, "C'est exact. Mais depuis novembre, je suis également directrice artistique associée à temps partiel, en CDI, au sein de la maison Lacoste & Fils, à Bordeaux. Voici la lettre d'embauche.", "맞습니다. 하지만 11월부터는 보르도의 라코스트 앤 필스 사에서 비상근 공동 아트 디렉터로 무기 계약을 맺었습니다. 채용 서한입니다."),
(B, "(lit la lettre, hoche la tête) Soixante pour cent. Un salaire de trente et un mille deux cents euros bruts annuels. C'est un élément solide.", "(편지를 읽고 고개를 끄덕이며) 60퍼센트. 연 세전 3만 1천 2백 유로. 단단한 요소네요."),
(M, "Madame Aubry, si je puis me permettre : cet emploi stable renforce considérablement la capacité de remboursement de la co-emprunteuse.", "오브리 부인, 말씀드려도 된다면 이 안정적인 일자리가 공동 차주의 상환 능력을 크게 강화해요."),
(B, "Je l'ai noté, maître. Passons à l'apport personnel : quarante mille euros ?", "적어 뒀어요, 변호사님. 자기 자본으로 넘어가죠. 4만 유로인가요?"),
(A, "Vingt mille de mon côté, issus de mes économies et de la vente d'un terrain familial. Vingt mille du côté de Madame Fontaine, qui provient de son épargne.", "제 쪽은 2만으로 저축과 가족 토지 매각에서 나왔습니다. 퐁텐 씨 쪽 2만은 저축에서 나왔고요."),
(B, "Et un prêt familial de dix mille euros ?", "그리고 1만 유로 가족 대출이요?"),
(M, "De ma part et de celle des parents de Madame Fontaine, à parts égales. Un contrat de prêt entre particuliers a été rédigé et enregistré.", "저와 퐁텐 씨 부모님이 반씩 부담합니다. 개인 간 대여 계약서를 작성해 등록했습니다."),
(B, "(continue d'écrire) Très bien. Passons au plan de financement. Pouvez-vous m'expliquer comment vous comptez rembourser ?", "(계속 적으며) 좋아요. 자금 조달 계획으로 넘어갈게요. 어떻게 상환할 계획인지 설명해 주시겠어요?"),
(L, "Le prêt de cent trente mille euros, sur sept ans, au taux de trois virgule huit pour cent, représente une mensualité d'environ mille huit cent euros. Notre prévision de résultat, avec un chiffre d'affaires de deux cent quarante mille euros la première année, permet de dégager une capacité d'autofinancement de quatre-vingt mille euros.", "13만 유로를 7년 동안 3.8퍼센트 금리로 빌리면 월 상환액이 약 1,800유로입니다. 첫해 매출 24만 유로 예상으로는 8만 유로의 자체 조달 능력이 생깁니다."),
(B, "Deux cent quarante mille. Soit une progression de treize pour cent par rapport à l'an dernier. Sur quoi vous fondez-vous ?", "24만이면 작년보다 13퍼센트 증가인데요. 근거가 뭔가요?"),
(A, "Sur trois leviers. Un : la vente en ligne, que la boutique ne pratique pas actuellement. Deux : un atelier de création d'étiquettes pour les petits vignerons, qui générera un revenu complémentaire. Trois : des dégustations payantes, une fois par mois, avec des producteurs invités.", "세 가지 지렛대입니다. 첫째, 현재 가게에서 하지 않는 온라인 판매. 둘째, 소규모 농가를 위한 라벨 제작 공방으로 추가 수익을 냅니다. 셋째, 월 1회 생산자를 초대한 유료 시음회입니다."),
(B, "Des hypothèses. Je préférerais des certitudes.", "가정이군요. 저는 확신을 선호하는데요."),
(M, "Madame, en matière de création d'entreprise, les certitudes n'existent pas. Il existe des hypothèses raisonnées, étayées par des données. Ce dossier en contient cinquante-trois.", "부인, 창업에서 확신은 존재하지 않아요. 데이터로 뒷받침된 합리적 가정이 있을 뿐이죠. 이 서류에는 쉰세 개가 담겨 있어요."),
(B, "(un léger sourire) Vous avez du répondant, maître.", "(가벼운 미소) 변호사님은 응수가 좋으시네요."),
(M, "C'est mon métier.", "제 직업이에요."),
(B, "Parlons de la boutique elle-même. Que pensez-vous de la concurrence ? Il y a, dans un rayon de huit cents mètres, cinq autres cavistes.", "가게 자체 얘기를 하죠. 경쟁은 어떻게 보세요? 반경 800미터 안에 와인 가게가 다섯 곳 더 있어요."),
(L, "Quatre, si on ne compte pas Maison Vinum, qui est un supermarché déguisé. Mais aucun n'offre ce que nous proposons : une identité forte, un conseil humain et une vraie histoire.", "메종 비눔을 빼면 네 곳입니다. 변장한 슈퍼마켓이니까요. 하지만 우리가 제안하는 것을 제공하는 곳은 없습니다. 강한 정체성, 인간적인 조언, 그리고 진짜 이야기요."),
(B, "Une histoire. C'est un argument commercial ?", "이야기라. 그게 상업적 논거인가요?"),
(A, "C'est le seul argument durable, madame. Un vin se copie. Une histoire, non.", "유일하게 지속되는 논거입니다, 부인. 와인은 모방할 수 있지만 이야기는 모방할 수 없어요."),
(B, "Intéressant. Et quelle est la vôtre ?", "흥미롭네요. 그럼 당신들의 이야기는 뭔가요?"),
(L, "Nous nous sommes rencontrés dans cette boutique, un soir de mars, en voulant acheter la même bouteille.", "저희는 3월 어느 저녁 같은 병을 사려다가 이 가게에서 만났습니다."),
(B, "(lève un sourcil) Vous plaisantez ?", "(눈썹을 올리며) 농담이시죠?"),
(A, "Non, madame. C'est une bouteille de Morgon. La dernière en rayon.", "아닙니다, 부인. 모르공 한 병이었어요. 선반의 마지막 병."),
(B, "(une pause, un léger sourire) Je ne note pas ça dans le dossier. Mais je le retiens.", "(잠시 멈추고 가벼운 미소) 서류에는 적지 않겠어요. 하지만 기억해 둘게요."),
(B, "Passons aux travaux. Vous prévoyez trente mille euros de travaux d'aménagement. Est-ce suffisant ?", "공사로 넘어가죠. 3만 유로의 인테리어 공사를 예상하셨네요. 충분한가요?"),
(M, "Nous avons obtenu trois devis auprès d'artisans du quartier. Le plus bas est à vingt-six mille euros, avec une marge de sécurité de quinze pour cent.", "동네 장인 세 곳에서 견적을 받았어요. 가장 낮은 건 2만 6천 유로이고 15퍼센트의 안전 마진을 뒀어요."),
(B, "Des artisans du quartier. J'apprécie. Ils connaissent les contraintes des bâtiments anciens.", "동네 장인들이라. 좋네요. 오래된 건물의 제약을 알 테니까요."),
(L, "Et ils sont prêts à être payés en bouteilles pour une partie du montant.", "그리고 금액의 일부는 와인으로 받아도 된다고 하세요."),
(B, "(une seconde de silence, puis un rire bref) En bouteilles. Bien sûr.", "(잠시 침묵한 뒤 짧은 웃음) 와인으로요. 물론이죠."),
(B, "Dernière question. Si, dans six mois, les ventes sont inférieures de vingt pour cent à vos prévisions, que faites-vous ?", "마지막 질문이에요. 육 개월 뒤 매출이 예상보다 20퍼센트 낮다면 어떻게 하실 건가요?"),
(A, "Nous réduisons le stock des références lentes, nous renégocions les loyers des étagères avec les producteurs, et nous lançons les dégustations payantes plus tôt que prévu.", "회전이 느린 품목의 재고를 줄이고 생산자와 진열대 비용을 재협상하고 유료 시음회를 계획보다 일찍 시작합니다."),
(L, "Et si ce n'est pas suffisant, je prends des contrats supplémentaires en design. J'ai déjà des clients qui m'ont dit oui.", "그래도 부족하면 디자인 계약을 추가로 합니다. 이미 승낙한 고객들이 있어요."),
(B, "(note, hoche la tête) Un plan B, un plan C. Vous avez anticipé. Bien.", "(메모하며 고개를 끄덕이고) 플랜 B, 플랜 C라. 예상해 두셨군요. 좋아요."),
(B, "Soit. Parlons du risque. La boutique est située dans un quartier touristique. Quelle part de votre clientèle est composée d'habitués ?", "알겠어요. 위험 얘기를 하죠. 가게는 관광지에 있어요. 고객 중 단골 비중이 얼마죠?"),
(A, "Environ soixante-dix pour cent. Madame Pichon, par exemple, est cliente depuis trente-cinq ans.", "약 70퍼센트입니다. 예를 들어 피숑 부인은 35년째 단골이에요."),
(B, "Et que se passera-t-il le jour où madame Pichon cessera de venir ?", "그리고 피숑 부인이 오지 않게 되는 날엔 어떻게 되나요?"),
(L, "(un petit rire gêné) Madame Aubry, Madame Pichon a soixante-quinze ans et une santé de fer. Elle viendra encore dans vingt ans, et elle fera la leçon à nos futurs enfants.", "(곤란한 작은 웃음) 오브리 부인, 피숑 부인은 75세에 강철 같은 건강이세요. 이십 년 뒤에도 오실 거고 우리 미래 아이들에게도 잔소리하실 거예요."),
(B, "(note) « Vos futurs enfants. » C'est un élément de stabilité familiale. Il est pris en compte.", "(메모하며) '미래의 아이들'. 가정 안정의 요소군요. 고려할게요."),
(A, "(rougit légèrement) Euh...", "(약간 얼굴을 붉히며) 어..."),
(M, "(souriant) Madame Aubry plaisante, Antoine. Détends-toi.", "(미소 지으며) 오브리 부인이 농담하신 거야, 앙투안. 긴장 풀어."),
(B, "Je ne plaisante jamais, maître. Mais je note tout. Reprenons. La question que je me pose, c'est celle de la garantie.", "농담 안 해요, 변호사님. 하지만 모든 걸 적어요. 다시 보죠. 제가 생각하는 질문은 담보예요."),
(L, "La garantie ?", "담보요?"),
(B, "Oui. Un prêt de cent trente mille euros à de jeunes entrepreneurs sans expérience commerciale, dans un secteur concurrentiel, est un risque pour ma banque. Pour l'accorder, je dois proposer à mon comité une garantie solide.", "네. 상업 경험이 없는 젊은 창업자들에게 경쟁이 치열한 업종에서 13만 유로를 빌려주는 건 우리 은행에 위험이에요. 승인하려면 위원회에 확실한 담보를 제시해야 해요."),
(M, "Nous avons un nantissement sur le fonds de commerce lui-même, et une assurance emprunteur incluant décès et invalidité.", "영업권 자체에 대한 질권, 그리고 사망·장해를 포함한 차주 보험이 있어요."),
(B, "C'est un début. Mais insuffisant. Les fonds de commerce ne valent que ce que valent leurs exploitants. Je dois demander une caution personnelle à hauteur de cinquante pour cent du capital emprunté, soit soixante-cinq mille euros.", "시작은 됐어요. 하지만 충분하지 않아요. 영업권은 운영자만큼의 가치만 가져요. 대출 원금의 50퍼센트, 즉 6만 5천 유로에 해당하는 개인 보증을 요구해야 해요."),
(A, "Une caution personnelle de soixante-cinq mille euros.", "6만 5천 유로의 개인 보증."),
(B, "Exactement. Une personne s'engage à rembourser à votre place en cas de défaillance. Idéalement, un proche avec un patrimoine immobilier ou foncier.", "맞아요. 불이행 시 대신 갚겠다고 약속하는 사람이에요. 이상적으로는 부동산이나 토지 자산이 있는 가까운 사람이에요."),
(L, "(un silence, puis, d'une voix posée) Nous n'avons pas, ni l'un ni l'autre, de patrimoine de cet ordre.", "(침묵 뒤 차분한 목소리로) 우리 둘 다 그만한 자산은 없습니다."),
(B, "Et les familles ?", "그럼 가족들은요?"),
(A, "(un temps) Mon père possède un domaine viticole de quinze hectares, dans la Loire. Mais ce domaine est en train d'être transmis. Et il...", "(잠시 후) 아버지가 루아르에 15헥타르의 포도 농장을 가지고 있습니다. 하지만 지금 승계 중이고 그는..."),
(M, "Antoine. Ne t'avance pas. On ne sollicite pas papa avant d'en avoir discuté.", "앙투안. 앞서 나가지 마. 의논하기 전에 아빠에게 요청하지 말자."),
(B, "Je comprends. Je ne vous demande pas de me donner une réponse aujourd'hui. Je vous demande de revenir avec une caution, ou avec une alternative, avant le vingt janvier.", "이해합니다. 오늘 답을 달라는 게 아니에요. 1월 20일 전에 보증인 또는 대안을 가지고 다시 오시길 요청해요."),
(L, "Et en attendant ?", "그동안은요?"),
(B, "En attendant, je soumets un accord de principe au comité sous réserve d'une garantie complémentaire. C'est la limite de ce que je peux faire.", "그동안 보완 담보를 조건으로 한 원칙적 동의서를 위원회에 제출할게요. 제가 할 수 있는 한계예요."),
(M, "Un accord de principe sous réserve. C'est déjà un progrès.", "조건부 원칙적 동의군요. 이미 진전이에요."),
(B, "Je suis une banquière, maître, pas une marchande de rêves. Mais je dois vous dire une chose, en toute franchise.", "저는 은행원이지 꿈을 파는 사람이 아니에요, 변호사님. 하지만 솔직히 말씀드려야 할 게 있어요."),
(A, "Je vous écoute.", "듣겠습니다."),
(B, "Votre dossier est le meilleur que j'aie reçu cette année. Je dis bien le meilleur. Il est rigoureux, honnête, et il contient une vision. Je ne vois pas souvent de vision dans les dossiers. Je vois des tableaux.", "당신들의 서류는 올해 제가 받은 것 중 최고예요. 최고라고 확실히 말해요. 엄밀하고 정직하며 비전이 있어요. 서류에서 비전을 보는 일은 흔치 않아요. 보통은 표만 보죠."),
(L, "(émue) Merci, madame.", "(감동하여) 감사합니다, 부인."),
(B, "Ne me remerciez pas. Revenez avec une caution. Et si vous ne la trouvez pas, venez quand même me le dire : je chercherai avec vous une autre formule.", "고마워하지 마세요. 보증인을 가지고 오세요. 못 찾으셔도 와서 말해 주세요. 함께 다른 방식을 찾아볼게요."),
(None, "Elle se lève, leur tend la main à tour de rôle. Sa poignée de main est ferme, brève, sincère.", "그녀가 일어나 한 명씩 악수를 청한다. 악수는 단호하고 짧고 진실하다."),
(M, "Madame Aubry, merci pour votre franchise.", "오브리 부인, 솔직함에 감사드려요."),
(B, "C'est la seule forme de politesse que je pratique. Au revoir, madame, messieurs.", "제가 하는 유일한 예의예요. 안녕히 가세요, 여러분."),
(None, "Dehors, sur le boulevard de Clichy. Une pluie fine tombe. Les trois partenaires restent un moment immobiles devant la porte de la banque, chacun avec son classeur sous le bras.", "밖은 클리시 대로. 가랑비가 내린다. 세 동료가 각자 바인더를 겨드랑이에 끼고 은행 문 앞에서 한동안 가만히 서 있다."),
(L, "Le meilleur dossier de l'année. Et un refus.", "올해 최고의 서류. 그리고 거절."),
(M, "Pas un refus. Un « oui, si ». Il faut apprendre à lire les banquiers. « Oui, si » veut dire « oui », à condition que vous soyez gentils.", "거절이 아니야. '예, 단 조건이 있다'야. 은행원 읽는 법을 배워야 해. '예, 단'은 '예'라는 뜻인데 너희가 말을 잘 들으면이라는 조건이 붙은 거야."),
(A, "Soixante-cinq mille euros de caution. Nous n'avons personne.", "6만 5천 유로 보증. 우리에겐 아무도 없어."),
(M, "Nous avons papa.", "아빠가 있잖아."),
(A, "Non. Papa a déjà beaucoup donné. Il transmet le domaine, il ne va pas en plus l'hypothéquer pour une boutique de vin à Montmartre.", "아니. 아빠는 이미 많이 주셨어. 농장을 물려주시는데 몽마르트르 와인 가게를 위해 담보로 걸지는 않으실 거야."),
(M, "Tu en es sûr ?", "확신해?"),
(A, "Je le connais, Margaux. Il a le sens de l'honneur. Il ne demandera rien. Et je ne lui demanderai rien.", "아빠를 알아, 마르고. 명예심이 있는 분이야. 아무것도 요구하지 않으실 거고 나도 부탁하지 않을 거야."),
(M, "Alors tu es plus bête que je ne le pensais.", "그럼 내 생각보다 더 멍청하네."),
(A, "Margaux !", "마르고!"),
(M, "Je plaisante. À moitié. (Elle ouvre son parapluie.) Écoute. Je ne te dis pas de demander à papa. Je te dis qu'il faut lui parler. Il y a une grande différence entre « demander » et « parler ».", "농담이야. 반쯤은. (우산을 펴며) 들어. 아빠께 부탁하라는 게 아니야. 이야기하라는 거지. '부탁하다'와 '이야기하다'는 크게 달라."),
(L, "(prend la main d'Antoine) Je crois qu'elle a raison.", "(앙투안의 손을 잡으며) 마르고 말이 맞는 것 같아."),
(A, "Noël approche. On sera tous chez lui, le vingt-quatre.", "크리스마스가 다가와. 24일에 다 같이 아버지 집에 있을 거야."),
(M, "Voilà. L'occasion idéale. On ne parle pas d'argent à table. On parle de vin. Et l'argent suit.", "바로 그거야. 이상적인 기회지. 식탁에서 돈 얘기는 안 해. 와인 얘기를 하지. 그러면 돈은 따라와."),
(L, "Tu parles comme une vigneronne.", "포도 농부처럼 말하네."),
(M, "Je suis la fille d'un vigneron. Je suis juste montée dans un tailleur.", "난 와인 농부의 딸이야. 투피스를 입고 올라왔을 뿐이지."),
(None, "Elle part vers le métro, d'un pas décidé. Antoine et Léa la regardent s'éloigner, sous la pluie fine, leur classeur toujours sous le bras.", "그녀가 단호한 걸음으로 지하철로 향한다. 앙투안과 레아가 바인더를 낀 채 가랑비 속에서 멀어지는 그녀를 바라본다."),
(L, "Tu crois qu'on y arrivera ?", "우리가 해낼 수 있을까?"),
(A, "Je ne sais pas. Mais je sais que c'est le meilleur dossier de l'année.", "모르겠어. 하지만 올해 최고의 서류라는 건 알아."),
(L, "(rit) Ça ne paie pas le loyer.", "(웃으며) 그건 월세를 안 내 줘."),
(A, "Non. Mais ça fait plaisir.", "아니. 하지만 기분은 좋아."),
(L, "Alors on va chez Gaston lui raconter ça ?", "그럼 가스통에게 가서 이야기해 줄까?"),
(A, "Et lui demander des conseils pour parler à mon père.", "그리고 우리 아버지께 말씀드릴 조언도 구하고."),
(L, "Il aura une métaphore pour ça.", "그분은 그에 맞는 은유가 있을 거야."),
]
VOCAB = [
("A2","un hall / un fauteuil / un canapé","홀 / 안락의자 / 소파","은행 대기실"),
("A2","un bureau vitré / une table ovale","유리 사무실 / 타원 탁자","면담 공간"),
("A2","un classeur / un ruban","바인더 / 리본","서류 소품"),
("B1","un prêt / un emprunt / emprunter","대출 / 차입 / 빌리다","« emprunter cent trente mille euros »"),
("B1","la mensualité / le taux","월 상환액 / 금리","« une mensualité d'environ mille huit cent euros »"),
("B1","un apport personnel / une épargne","자기 자본 / 저축","« quarante mille euros d'apport »"),
("B1","les revenus / une déclaration d'impôts","소득 / 세금 신고서","수입 증명 서류"),
("B1","un comité / un accord de principe","위원회 / 원칙적 동의","« un accord de principe sous réserve »"),
("B2","un co-emprunteur / la capacité de remboursement","공동 차주 / 상환 능력","대출 심사의 핵심"),
("B2","le plan de financement / la capacité d'autofinancement","자금 조달 계획 / 자체 조달 능력","재무 분석 용어"),
("B2","un nantissement / une assurance emprunteur","질권 설정 / 차주 보험","담보·보험"),
("B2","une caution personnelle / se porter caution","개인 보증 / 보증을 서다","« une caution personnelle de soixante-cinq mille euros »"),
("B2","hypothéquer / un patrimoine","저당 잡히다 / 자산","« Il ne va pas en plus l'hypothéquer. »"),
("B2","une défaillance / à hauteur de","불이행 / ~만큼","« à hauteur de cinquante pour cent »"),
("B2","un levier / étayer","지렛대 / 뒷받침하다","« des hypothèses étayées par des données »"),
("B2","la franchise / en toute franchise","솔직함 / 솔직히","« en toute franchise »"),
("C1","avoir du répondant","응수가 좋다, 재력이 있다","« Vous avez du répondant, maître. » 이중 의미"),
("C1","une marchande de rêves","꿈을 파는 사람","« Je suis une banquière, pas une marchande de rêves. »"),
("C1","oui, si","예, 단(조건부 승낙)","은행 용어의 은유"),
("C1","une santé de fer","강철 같은 건강","« une santé de fer »"),
("C1","d'un pas décidé","단호한 걸음으로","마르고의 행동 묘사"),
("C1","une poignée de main ferme, brève, sincère","단호하고 짧고 진실한 악수","정서적 정보를 담은 묘사"),
("C1","soit. / Soit un progrès de treize pour cent.","좋아요. / 즉 13퍼센트 증가","soit = 즉/좋아요(양보)"),
("C1","le meilleur que j'aie reçu","내가 받은 것 중 최고","최상급 + 접속법 과거"),
]
GRAM = [
("B1","금융 구문: Soit + 수치 / Soit une progression de…",
 "« Deux cent quarante mille. Soit une progression de treize pour cent. » soit = 즉. 숫자를 요약·환산할 때 쓰는 연결 표현. « Soit. » 단독으로는 '좋아요'."),
("B2","접속법: sous réserve que / à condition que",
 "« À condition que vous soyez gentils. » « Sous réserve que vous trouviez une caution. » 조건 접속사 + 접속법. 36화 복습."),
("B2","최상급 + que + 접속법 과거 (복습)",
 "« Le meilleur dossier que j'aie reçu cette année. » 17화·22화·28화·36화에서 이어진 문형. 이제 자연스럽게 말해 볼 것."),
("B2","직설법 미래 + 조건법: Elle viendra encore dans vingt ans",
 "« Elle viendra encore dans vingt ans, et elle fera la leçon… » 현실적 확신에는 단순미래, 가정에는 조건법. 레아의 대답은 미래로 낙관을 표현."),
("B2","Il faut que + 접속법: Il faut lui parler / Il faut apprendre à…",
 "« Il faut lui parler. » « Il faut apprendre à lire les banquiers. » il faut + 부정사(일반적 필요), il faut que + 접속법(특정 주어 필요)."),
("C1","대조: ne pas A, mais B / ce n'est pas A, c'est B",
 "« Pas un refus. Un « oui, si ». » « Je ne vous demande pas… je vous demande… » 부정 + 정정 구문. 협상 어법에서 자주 쓰인다."),
("C1","의문의 반어: Et que se passera-t-il le jour où… ?",
 "« Et que se passera-t-il le jour où madame Pichon cessera de venir ? » que se passer-t-il = 무슨 일이 일어날까. 도치 의문 + 미래. 은행원의 전형적 반문."),
("C1","직접 인용과 격식: Madame, monsieur, maître",
 "« Madame Fontaine, monsieur Delcourt, maître Delcourt. » 호칭 순서와 직위 호칭. 변호사는 'maître'로 부르는 것이 프랑스 격식이다."),
]
CULTURE = [
("프랑스의 소규모 창업 대출",
 "은행은 영업권 담보(nantissement), 차주 보험, 개인 보증(caution)을 요구한다. 공공기관 Bpifrance가 보증을 제공하는 경우도 있다. 'accord de principe'는 최종 승인 전의 예비 동의서다."),
("프랑스의 호칭: Maître",
 "변호사는 법정이나 사무실에서 'Maître'로 부른다. 'Maître Delcourt'라는 호칭은 마르고의 전문성을 존중하는 격식 표현이다."),
("« oui, si »",
 "프랑스 금융계에서 'oui, si…'는 조건부 승낙을 말하는 은어다. 완전한 거절이 아니라 협상의 열린 문이라는 뜻이다."),
]
META = dict(part=4, ep=39, part_label="제4부 그랑 크뤼 · Grand cru", title_fr="Rendez-vous à la banque", title_ko="은행 면담",
 place="크레디 몽마르트루아(Crédit Montmartrois) 클리시 대로 지점 · 12월 11일 목요일 오전 10시",
 chars="Léa · Antoine · Margaux · Mme Aubry (은행 담당자)",
 wine="(와인 없음) 은행 면담",
 focus="금융·대출 어휘, 격식 어법, 접속법(à condition que), 협상 대화의 구조",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제40화 « Noël en Loire » : 12월 24일 소뮈르 근교의 농가. 두 집안의 부모가 한 부엌에 모이고, 앙투안은 아버지께 보증 이야기를 꺼내야 한다.")
