# -*- coding: utf-8 -*-
L, A, R, J, T, M = "Léa", "Antoine", "Gérard", "Julien", "La lettre d'Anne", "Margaux"
D = [
(None, "Samedi 3 janvier, 10 h. Une brume épaisse recouvre les vignes de Saint-Cyr-en-Bourg. Léa et Antoine, venus passer le week-end à la ferme, suivent Gérard le long d'un chemin de terre gelée. Gérard porte sous le bras une grande clé de fer, noire de rouille. Devant eux, une porte de bois, enfoncée dans la roche blanche d'un coteau : l'entrée du caveau familial.", "1월 3일 토요일 오전 10시. 짙은 안개가 생시르앙부르의 포도밭을 덮고 있다. 농가에서 주말을 보내러 온 레아와 앙투안이 얼어붙은 흙길을 따라 제라르를 따라간다. 제라르는 녹슬어 까만 큰 철제 열쇠를 팔에 끼고 있다. 그들 앞에는 언덕의 흰 바위에 파묻힌 나무 문이 있다. 가족 저장고의 입구다."),
(R, "Mon grand-père a creusé cette cave en mille neuf cent vingt, avec une pioche, une lampe à huile et beaucoup d'obstination. C'est la plus ancienne partie du domaine.", "내 할아버지가 1920년에 곡괭이와 기름 등잔과 많은 고집으로 이 지하 저장고를 파셨어. 농장에서 가장 오래된 부분이지."),
(A, "Je n'y suis pas entré depuis des années. Papa ne me laissait pas y descendre seul, quand j'étais petit.", "몇 년 동안 들어가 본 적이 없어요. 어릴 때 아빠가 혼자 내려가지 못하게 하셨죠."),
(R, "C'était dangereux : l'escalier est glissant. Mais aussi... il y a des choses ici que je ne voulais pas que tu voies trop tôt.", "위험했으니까. 계단이 미끄럽거든. 하지만 또... 네가 너무 일찍 보지 않았으면 하는 것들이 여기 있어."),
(L, "(prudemment) Des choses ?", "(조심스럽게) 어떤 것들이요?"),
(R, "Vous verrez. Venez.", "보게 될 거야. 오세요."),
(None, "Il tourne la clé dans la serrure. Un grincement de métal. La porte s'ouvre sur un escalier de pierre qui plonge dans l'obscurité. L'air qui monte est frais, humide, chargé d'une odeur de terre, de pierre et de champignon. Gérard allume une lampe torche.", "그가 열쇠를 자물쇠에 돌린다. 쇠 삐걱이는 소리. 문이 열리자 어둠 속으로 이어지는 돌계단이 나타난다. 올라오는 공기는 서늘하고 축축하며 흙, 돌, 버섯 냄새를 머금었다. 제라르가 손전등을 켠다."),
(R, "Attention aux marches. Tenez la rampe.", "계단 조심하세요. 난간을 잡아요."),
(None, "Ils descendent à pas lents. L'escalier débouche dans une salle voûtée, taillée dans le tuffeau : de grandes arches, des niches creusées dans la pierre, des bouteilles couchées par centaines, couvertes d'une fine pellicule de poussière blanche. Au fond, une table de bois sombre et deux fauteuils en osier.", "그들이 천천히 내려간다. 계단은 튀포를 깎아 만든 아치형 방으로 이어진다. 커다란 아치, 돌에 판 벽감, 고운 흰 먼지를 덮은 수백 병의 눕힌 병들. 안쪽에는 어두운 나무 탁자와 고리버들 안락의자 두 개."),
(L, "(à voix basse) C'est... somptueux.", "(작은 소리로) 이건... 화려해요."),
(R, "Mon père venait ici chaque dimanche matin. Mon grand-père aussi. Moi, je viens, en secret, quand j'ai besoin de réfléchir. Ma femme y chantait, parce que l'écho donnait de la profondeur à sa voix.", "아버지가 일요일 아침마다 오셨어. 할아버지도. 나는 생각이 필요할 때 몰래 와. 아내는 여기서 노래했지. 메아리가 목소리에 깊이를 주었거든."),
(A, "(il touche la pierre) Maman chantait ici ?", "(돌을 만지며) 엄마가 여기서 노래하셨어요?"),
(R, "Souvent. Surtout pendant sa dernière année. Elle disait qu'elle voulait laisser un peu de sa voix dans la pierre.", "자주. 특히 마지막 해에. 자기 목소리를 조금 돌에 남기고 싶다고 하셨어."),
(L, "(à voix basse) Elle l'a fait.", "(작은 소리로) 그렇게 하셨네요."),
(None, "Gérard s'approche d'une niche creusée dans le mur du fond. Il en retire une boîte en bois de merisier, sombre, polie par les années, de la taille d'une boîte à chaussures. Il la pose sur la table avec précaution.", "제라르가 안쪽 벽의 벽감으로 다가가 해묵어 반질한 짙은 벚나무 상자를 꺼낸다. 신발 상자만 한 크기다. 그가 조심스럽게 상자를 탁자 위에 놓는다."),
(R, "Voilà ce que je voulais te montrer, Antoine.", "이게 네게 보여 주고 싶었던 거야, 앙투안."),
(A, "(la voix tendue) Qu'est-ce que c'est ?", "(긴장된 목소리로) 뭐예요?"),
(R, "La boîte de ta mère. Elle l'a préparée pendant les six derniers mois de sa vie. Elle m'a fait promettre de ne l'ouvrir qu'au bon moment, et de ne la remettre à ses enfants que quand ils en auraient besoin.", "네 엄마의 상자야. 마지막 육 개월 동안 준비했어. 알맞은 때가 되어서야 열고 아이들에게는 필요할 때에만 건네 달라고 약속시켰지."),
(A, "(un souffle) Margaux ?", "(숨을 내쉬며) 마르고는요?"),
(R, "Ta sœur a reçu la sienne le jour où elle a prêté serment d'avocate. Pour toi, je n'ai pas su... Je n'ai jamais su quel était le bon moment. Chaque année, je me disais : « Il n'est pas prêt. » Puis je me suis rendu compte que c'était moi qui n'étais pas prêt.", "네 누나는 변호사 선서를 하던 날 받았어. 너에게는... 언제가 알맞은 때인지 한 번도 몰랐어. 해마다 '아직 준비 안 됐어'라고 했지. 그러다가 준비가 안 된 건 나라는 걸 깨달았다."),
(A, "(très ému) Papa...", "(깊이 감동하여) 아빠..."),
(R, "Ce matin, je sais. Tu as décidé de ta vie. Tu as trouvé ta place, ta façon de revenir et de partir. Tu es prêt.", "오늘 아침엔 알겠다. 넌 네 삶을 결정했어. 네 자리와 돌아오고 떠나는 방식을 찾았지. 넌 준비됐다."),
(None, "Il ouvre le couvercle. À l'intérieur, une enveloppe cachetée de cire rouge, un petit carnet de cuir bleu, une photographie, une boucle de cheveux noués d'un ruban, et un tout petit sachet de lavande séchée.", "그가 뚜껑을 연다. 안에는 붉은 밀랍으로 봉한 봉투, 푸른 가죽 수첩, 사진 한 장, 리본으로 묶은 머리카락 한 타래, 말린 라벤더가 든 아주 작은 주머니가 있다."),
(A, "(la voix cassée) Je ne sais pas si je peux...", "(목소리가 갈라지며) 할 수 있을지 모르겠어요..."),
(L, "(lui prend la main) Je suis là.", "(그의 손을 잡으며) 내가 여기 있어."),
(R, "Prends l'enveloppe. Elle est pour toi. Moi, je monte. Il y a des choses qu'un fils lit sans son père. Et je dois aller voir si Julien a allumé le poêle.", "봉투를 받아라. 네 거다. 난 올라갈게. 아들이 아버지 없이 읽어야 하는 것들이 있다. 쥘리앵이 난로를 켰는지도 봐야 하고."),
(A, "Papa, reste.", "아빠, 남으세요."),
(R, "(après un silence) Je reste. Mais je ne regarde pas. Je regarde la pierre.", "(침묵 뒤) 남을게. 하지만 보지 않을 거다. 돌을 볼게."),
(None, "Il s'assoit sur un des fauteuils, le dos tourné, le regard fixé sur un arc de pierre. Antoine prend l'enveloppe, brise le sceau de cire d'un geste hésitant, déplie une feuille jaunie, écrite d'une main fine et penchée.", "그가 안락의자에 앉아 등을 돌리고 돌 아치를 응시한다. 앙투안이 봉투를 집어 머뭇거리는 몸짓으로 밀랍 봉인을 깨고 가늘고 기울어진 글씨로 쓴 누렇게 바랜 종이를 편다."),
(T, "« Mon petit Antoine, si tu lis ces lignes, c'est que tu as grandi, et que ton père, ce vieil entêté, s'est enfin décidé à t'ouvrir ma boîte. »", "'사랑하는 앙투안, 이 글을 읽는다면 네가 자랐다는 거고 고집 센 네 아버지가 마침내 내 상자를 열어 주기로 결심했다는 뜻이겠지.'"),
(T, "« Je t'écris le seize mars. Tu as treize ans. Tu dors à l'étage. Je t'entends respirer à travers le plancher. Je n'ai pas le droit de dire que j'ai peur, mais j'ai peur, tu sais. Pas de mourir. De te laisser. »", "'3월 16일에 쓴다. 넌 열세 살이야. 위층에서 자고 있어. 마룻바닥 너머로 네 숨소리가 들려. 무섭다고 말할 권리는 없지만 무서워. 죽는 게 아니라 너를 두고 가는 게.'"),
(A, "(la voix brisée) Maman...", "(목소리가 갈라지며) 엄마..."),
(T, "« Voici ce que je veux que tu saches. Ton père est un homme de peu de mots, mais il t'aime comme on aime une vigne : en silence, avec des mains abîmées, en espérant que les raisins soient bons. »", "'네가 알았으면 하는 건 이거야. 네 아버지는 말이 적지만 포도나무를 사랑하듯 너를 사랑해. 말없이 거친 손으로, 포도가 잘 열리기를 바라며.'"),
(T, "« Je ne sais pas qui tu seras. Peut-être vigneron. Peut-être professeur, ou voyageur, ou menteur professionnel. Ce que je souhaite, c'est que tu choisisses une vie qui te rende vivant. Pas une vie qui rende fier ton père, ni ta mère. Une vie qui te rende vivant. »", "'네가 누가 될지 몰라. 포도 농부일 수도, 교사일 수도, 여행자나 직업적 거짓말쟁이일 수도 있겠지. 내가 바라는 건 널 살아 있게 하는 삶을 고르는 거야. 아버지나 어머니를 자랑스럽게 하는 삶이 아니라 널 살아 있게 하는 삶을.'"),
(A, "(des larmes silencieuses coulent) Elle me l'avait dit. Elle me l'avait dit à l'hôpital. « Fais ce qui te rend vivant. »", "(말없는 눈물이 흐르며) 엄마가 말씀하셨어요. 병원에서요. '널 살아 있게 하는 걸 해라.'"),
(T, "« Si tu as trouvé quelqu'un à aimer, dis-le-lui. Ne garde pas les mots. J'ai passé trop de temps à les garder, et maintenant, je n'ai plus que du papier pour les dire. »", "'사랑하는 사람을 만났다면 말해 줘. 말을 간직하지 마. 난 말을 간직하느라 너무 많은 시간을 보냈고 이제는 그것을 전할 종이만 남았어.'"),
(L, "(à voix basse, les larmes aux yeux) Gaston dit la même chose.", "(작은 소리로 눈물이 고여) 가스통도 같은 말을 해."),
(T, "« Dans la boîte, tu trouveras ma boucle de cheveux, une photo de nous quatre à la vendange de mille neuf cent quatre-vingt-seize, ma recette de clafoutis aux cerises (la meilleure), et un petit carnet où j'ai noté, pendant dix ans, les mots que tu disais quand tu étais petit. »", "'상자에는 내 머리카락 한 타래, 1996년 수확 때 우리 네 식구 사진, 내 체리 클라푸티 레시피(최고지), 그리고 네가 어렸을 때 한 말들을 십 년 동안 적은 작은 수첩이 있어.'"),
(T, "« Je t'aime. Je t'aimerai toujours, sous une forme ou sous une autre, sous la pierre, dans la vigne, dans ton sourire. Sois heureux. Ta maman, Anne. »", "'사랑해. 돌 아래에서든 포도밭에서든 네 미소 속에서든 어떤 모습으로든 영원히 사랑할게. 행복해라. 엄마, 안.'"),
(None, "Un long silence. Antoine relève la tête. Gérard n'a pas bougé, mais ses épaules tremblent. Léa, immobile, serre la main d'Antoine. Les larmes coulent sur son visage sans qu'elle fasse le moindre bruit.", "긴 침묵. 앙투안이 고개를 든다. 제라르는 움직이지 않았지만 어깨가 떨린다. 레아가 꼼짝 않고 앙투안의 손을 쥔다. 그녀의 얼굴에 소리 없이 눈물이 흐른다."),
(A, "(d'une voix très basse) Papa.", "(아주 낮은 목소리로) 아빠."),
(R, "(sans se retourner) Oui.", "(돌아보지 않고) 응."),
(A, "Elle dit que tu es un homme de peu de mots.", "엄마가 아빠는 말이 적은 분이라고 하셨어요."),
(R, "(un petit rire étranglé) Elle avait raison. Comme toujours.", "(목이 멘 작은 웃음) 맞았지. 늘 그랬듯이."),
(A, "Elle dit que tu m'aimes comme on aime une vigne.", "엄마가 아빠가 날 포도나무를 사랑하듯 사랑한다고 하셨어요."),
(R, "(un long silence) Les vignes, ça ne répond pas. On les aime quand même. C'est ça, la différence entre aimer et posséder.", "(긴 침묵) 포도나무는 대답이 없지. 그래도 사랑한다. 그게 사랑하는 것과 소유하는 것의 차이다."),
(L, "(les yeux brillants) Gérard, c'est la plus belle phrase que j'aie entendue sur l'amour.", "(눈을 반짝이며) 제라르 씨, 제가 사랑에 대해 들은 가장 아름다운 말이에요."),
(R, "(se retourne enfin, les yeux rouges, un faible sourire) Ne le dites à personne. J'ai une réputation de taciturne.", "(마침내 돌아서며 빨개진 눈과 약한 미소로) 아무에게도 말하지 마세요. 과묵하다는 평판이 있으니까."),
(None, "Il se lève lentement, vient poser une main sur l'épaule de son fils. Il regarde la boîte ouverte, la photo, la boucle de cheveux, le sachet de lavande.", "그가 천천히 일어나 아들의 어깨에 손을 얹는다. 열린 상자, 사진, 머리카락, 라벤더 주머니를 바라본다."),
(R, "Je n'ai pas osé l'ouvrir depuis quinze ans. Je pensais que je ne supporterais pas de voir son écriture.", "십오 년 동안 열 엄두를 못 냈어. 그 사람 글씨를 보는 걸 견디지 못할 줄 알았지."),
(A, "Tu veux la regarder, la photo ?", "사진을 보시겠어요?"),
(R, "(un temps) Oui.", "(잠시 후) 응."),
(None, "Antoine prend la photo, la tend à son père. Une photographie en couleurs un peu passées : une famille souriante dans une vigne, par un jour d'automne. Gérard, jeune, la barbe noire, tient un panier de raisins. Une petite fille blonde rit sur ses épaules. Un petit garçon aux joues sales brandit une grappe. À côté d'eux, une jeune femme aux cheveux bruns relevés regarde l'objectif avec un sourire radieux.", "앙투안이 사진을 집어 아버지에게 건넨다. 색이 약간 바랜 컬러 사진이다. 가을날 포도밭에서 웃는 가족. 검은 수염의 젊은 제라르가 포도 바구니를 들고 있다. 어깨 위에서 금발 소녀가 웃고 있다. 볼에 흙이 묻은 사내아이가 포도송이를 치켜들고 있다. 그 곁에 갈색 머리를 올린 젊은 여자가 환한 미소로 카메라를 바라본다."),
(R, "(la voix altérée) C'est le dernier automne où nous étions tous les quatre.", "(떨리는 목소리로) 우리 네 식구가 함께한 마지막 가을이야."),
(L, "Antoine. Tu as ses yeux.", "앙투안. 어머니 눈을 닮았어."),
(A, "(regarde la photo, ému) Et ses oreilles. Margaux dit toujours que j'ai les mêmes oreilles.", "(사진을 보며 감동하여) 귀도요. 마르고가 항상 내 귀가 똑같다고 해요."),
(R, "(sourit) C'est vrai. Tu as aussi son rire.", "(미소 지으며) 맞아. 웃음도 닮았어."),
(None, "Le téléphone d'Antoine vibre dans sa poche : « Margaux ». Il décroche, met le haut-parleur.", "앙투안의 주머니에서 전화기가 진동한다. '마르고'. 그가 받아 스피커폰으로 놓는다."),
(M, "Alors ? Papa t'a donné la boîte ?", "그래서? 아빠가 상자를 주셨어?"),
(A, "Comment le sais-tu ?", "어떻게 알아?"),
(M, "Papa m'a prévenue hier soir. Il m'a demandé si c'était une bonne idée.", "아빠가 어젯밤 내게 알려 주셨어. 좋은 생각인지 물으셨어."),
(A, "Tu avais lu la tienne ?", "넌 네 것을 읽었어?"),
(M, "Le jour de mon serment. Elle m'écrivait : « Sois dure mais juste. » Je crois que j'ai pris la moitié à la lettre.", "선서하던 날. '엄하되 공정해라'라고 쓰셨어. 반은 문자 그대로 받아들인 것 같아."),
(A, "Laquelle ? La dure ou la juste ?", "어느 쪽? 엄한 쪽, 공정한 쪽?"),
(M, "(rit) Ça dépend des jours.", "(웃으며) 날마다 달라."),
(A, "Elle m'a parlé de papa. Elle dit qu'il m'aime comme on aime une vigne.", "엄마가 아빠 얘기를 하셨어. 날 포도나무처럼 사랑한다고."),
(M, "À moi, elle a écrit qu'il m'aimait comme un cep taillé : on me cassait pour me faire fleurir.", "내게는 가지치기한 그루터기처럼 사랑한다고 쓰셨어. 꽃피우려고 날 꺾는다고."),
(A, "(rit à travers ses larmes) Maman avait de l'humour.", "(눈물 사이로 웃으며) 엄마는 유머가 있으셨어."),
(M, "Elle avait trop de génie. Je vous embrasse tous. À bientôt, petit frère.", "너무 천재셨지. 모두에게 안부 전해 줘. 곧 보자, 동생."),
(None, "À ce moment, des pas résonnent dans l'escalier. Julien apparaît, essoufflé, un manteau sur le bras.", "그 순간 계단에서 발소리가 울린다. 쥘리앵이 숨을 헐떡이며 코트를 팔에 걸치고 나타난다."),
(J, "Excusez-moi de vous déranger. Gérard, le notaire vient d'appeler. Il demande si on peut avancer la signature chez lui au vendredi trente janvier, à dix heures.", "방해해서 죄송해요. 제라르 씨, 공증인이 방금 전화했어요. 서명을 1월 30일 금요일 10시로 앞당길 수 있냐고 묻네요."),
(R, "Le trente ? C'est tôt. Antoine, il te faut combien de temps pour tout préparer ?", "30일이라고? 이르구나. 앙투안, 모든 걸 준비하려면 시간이 얼마나 필요하니?"),
(A, "(il replie doucement la lettre) Le trente me va. La caution est déjà signée. Le bail est renouvelé. Le prêt est accordé.", "(그가 편지를 부드럽게 접으며) 30일이면 괜찮아요. 보증은 이미 서명했고 임대차는 갱신됐고 대출은 승인됐어요."),
(L, "Et Gaston est prêt. Il l'a dit à tout le monde au réveillon.", "그리고 가스통도 준비됐어요. 송년 파티 때 모두에게 말했죠."),
(J, "Alors c'est décidé. Trente janvier. Je préviens le notaire.", "그럼 정해졌네요. 1월 30일. 공증인에게 알릴게요."),
(R, "Julien. Tu es au courant de ce que contient cette boîte ?", "쥘리앵. 이 상자에 뭐가 들었는지 알고 있었니?"),
(J, "(regarde la boîte, comprend) Non, Gérard. Mais je vois que c'est un moment qui compte. Je peux remonter.", "(상자를 보고 이해하며) 아니요, 제라르 씨. 하지만 의미 있는 순간이라는 건 알겠어요. 올라갈게요."),
(R, "Reste. Tu fais partie de cette famille, toi aussi. Tu es le fils du voisin qui est venu manger à notre table depuis ses douze ans.", "남아라. 너도 이 가족의 일원이야. 열두 살 때부터 우리 식탁에서 밥을 먹은 이웃집 아들이잖아."),
(J, "(touché) Merci, Gérard.", "(감동하여) 감사합니다, 제라르 씨."),
(None, "Il s'assoit à côté d'eux. Léa sort de son sac un petit carnet de croquis et un crayon. Elle s'installe sur le bord de la table, les yeux fixés sur la boîte ouverte.", "그가 그들 곁에 앉는다. 레아가 가방에서 작은 스케치북과 연필을 꺼낸다. 열린 상자를 응시하며 탁자 가장자리에 자리를 잡는다."),
(A, "Qu'est-ce que tu fais ?", "뭐 해?"),
(L, "Je dessine. Les lignes de la boîte. La photo. Les mains de ton père. Je ne veux pas oublier ce moment.", "그림을 그려. 상자의 선, 사진, 네 아버지의 손. 이 순간을 잊고 싶지 않아."),
(R, "(la regarde faire, ému) Vous dessinez ma main ?", "(그녀가 그리는 모습을 보며 감동하여) 내 손을 그리나요?"),
(L, "Oui, monsieur. Si vous me le permettez.", "네, 선생님. 허락하신다면요."),
(R, "(étend la main sur la table, la paume vers le haut) Dessinez-la bien. Elle a tenu une grande partie de ma vie.", "(손을 탁자 위에 펴며 손바닥을 위로) 잘 그려요. 내 삶의 큰 부분을 쥐어 온 손이니."),
(L, "(commence à dessiner) Elle porte l'histoire de la vigne. Ça se voit dans les ongles, dans les cals, dans les plis des articulations.", "(그리기 시작하며) 포도나무의 역사를 품고 있어요. 손톱, 굳은살, 관절 주름에 보여요."),
(A, "(à voix basse, à Léa) Tu pourrais dessiner l'étiquette du Clos des Roches à partir de ça.", "(레아에게 작은 소리로) 이걸 바탕으로 클로 데 로슈 라벨을 그릴 수도 있겠어."),
(L, "(sans lever les yeux) J'y pense depuis cinq minutes. Une main ouverte, une grappe dans la paume. En dessous : « Delcourt & Barbier. Depuis cent ans. »", "(눈을 들지 않고) 오 분째 생각하고 있어. 펼친 손, 손바닥에 포도송이. 아래에는 '델쿠르 앤 바르비에. 백 년 전부터.'"),
(J, "(un souffle) C'est magnifique.", "(숨을 내쉬며) 멋져요."),
(R, "(après un temps) Elle a le sens du terroir, cette petite.", "(잠시 후) 이 아가씨는 테루아르 감각이 있구나."),
(A, "(sourit) Elle a le sens de tout, papa.", "(미소 지으며) 모든 감각이 있어요, 아빠."),
(R, "Je le sais. C'est ce qui me rassure.", "알아. 그게 내게 안심을 준다."),
(R, "Léa, votre père, quel homme est-il ?", "레아, 아버님은 어떤 분이세요?"),
(L, "Un ingénieur silencieux. Il a longtemps cru que les sentiments étaient des erreurs de calcul.", "말없는 엔지니어예요. 오랫동안 감정이 계산 오류라고 믿으셨죠."),
(R, "Et maintenant ?", "그럼 지금은요?"),
(L, "Il a ri à Noël, devant vous. Je crois que vous avez fait un miracle.", "크리스마스에 선생님 앞에서 웃으셨어요. 기적을 일으키신 것 같아요."),
(R, "Je n'ai rien fait. J'ai servi du Muscadet.", "나는 아무것도 안 했어요. 뮈스카데를 따랐을 뿐이죠."),
(L, "Alors c'est le Muscadet qui a fait le miracle.", "그럼 뮈스카데가 기적을 일으킨 거네요."),
(R, "Le vin est un bon intermédiaire. Il parle quand les hommes se taisent.", "와인은 좋은 중재자예요. 사람들이 입을 다물 때 말을 하죠."),
(A, "Papa, tu es un poète sans le savoir.", "아빠는 모르는 시인이에요."),
(None, "Dans la cave, le silence est plein. Les bouteilles dorment. La lampe torche jette une lumière blanche sur la pierre. Léa dessine. Au-dessus d'eux, quelque part, une cloche sonne onze heures.", "저장고 안에는 침묵이 가득하다. 병들이 잠들어 있다. 손전등이 돌 위에 하얀 빛을 던진다. 레아가 그림을 그린다. 그들 위 어딘가에서 종이 11시를 알린다."),
(A, "Papa. Je voudrais ouvrir une bouteille. Ici. Maintenant.", "아빠. 병 하나를 열고 싶어요. 여기서. 지금."),
(R, "Laquelle ?", "어느 병?"),
(A, "Une de celles de maman. Une de celles qu'elle a choisies.", "엄마가 고른 병 중 하나요."),
(R, "(se lève, s'approche d'une niche, retire une bouteille du fond) Mille neuf cent quatre-vingt-seize. Un Saumur-Champigny. Elle l'avait mise de côté pour « le jour où ils se parleront enfin ».", "(일어나 벽감으로 가서 안쪽 병 하나를 꺼내며) 1996년. 소뮈르샹피니야. '둘이 마침내 대화하는 날'을 위해 따로 챙겨 뒀지."),
(A, "(un sourire tremblant) Elle ne manquait pas d'humour.", "(떨리는 미소로) 유머가 없는 분은 아니었네요."),
(R, "Elle en avait trop. C'était son plus grand défaut.", "너무 많았지. 가장 큰 단점이었어."),
(None, "Il tend la bouteille à Antoine, qui l'ouvre avec le tire-bouchon posé sur la table. Le bouchon cède avec un soupir. Une odeur de fruits noirs, de tabac, de cuir, d'humus monte dans l'air de la cave.", "그가 병을 앙투안에게 건네자 앙투안이 탁자 위 코르크 따개로 연다. 코르크가 한숨 같은 소리를 내며 빠진다. 검은 과일, 담배, 가죽, 부식토 향이 지하실 공기 속으로 번진다."),
(L, "(inspire) Il est vivant.", "(숨을 들이쉬며) 살아 있어요."),
(A, "Il a trente ans. Et il est vivant.", "삼십 년이 됐는데 살아 있어."),
(R, "(sert quatre verres) Aux absents. Et aux présents.", "(잔 네 개를 따르며) 부재자를 위해. 그리고 현존자를 위해."),
(J, "Aux absents. Et aux présents.", "부재자를 위해. 그리고 현존자를 위해."),
(L, "(prend son verre) À Anne.", "(잔을 들며) 안을 위해."),
(A, "(lève son verre vers la voûte, vers la pierre) À maman.", "(잔을 아치와 돌 쪽으로 들며) 엄마를 위해."),
(None, "Ils boivent en silence. Au-dessus d'eux, dans la ferme, le poêle ronronne. Sous la terre, dans le caveau familial, quatre personnes, une bouteille ouverte, une boîte de souvenirs, et une dernière note de musique qui semble flotter dans l'air, comme l'écho d'une voix qu'on aurait gardée dans la pierre.", "그들이 말없이 마신다. 위 농가에서는 난로가 가르랑거린다. 땅 아래 가족 저장고에서 네 사람, 열린 병 하나, 추억 상자, 그리고 돌 속에 간직된 목소리의 메아리처럼 공기 중에 떠다니는 마지막 음 하나."),
]
VOCAB = [
("A2","une clé / une serrure / une porte de bois","열쇠 / 자물쇠 / 나무 문","저장고 입구 묘사"),
("A2","un escalier / une rampe","계단 / 난간","« Tenez la rampe. »"),
("A2","une photographie / un carnet / un sachet","사진 / 수첩 / 작은 주머니","상자 속 물건"),
("B1","le caveau familial / une niche","가족 저장고 / 벽감","« une niche creusée dans le mur »"),
("B1","grincer / un grincement","삐걱거리다 / 삐걱거림","« Un grincement de métal. »"),
("B1","une pioche / une lampe à huile","곡괭이 / 기름 등잔","할아버지의 도구"),
("B1","une boucle de cheveux / une enveloppe cachetée","머리카락 한 타래 / 봉한 봉투","유품"),
("B1","cacheter / un sceau de cire","봉하다 / 밀랍 봉인","« briser le sceau de cire »"),
("B2","une salle voûtée / le tuffeau","아치형 방 / 튀포","루아르 석회암 지하 저장고"),
("B2","une lampe torche / un plancher","손전등 / 마룻바닥","장면 소품"),
("B2","hériter / un héritage / la transmission","물려받다 / 유산 / 전승","상속 어휘"),
("B2","un entêté / têtu","고집쟁이 / 고집 센","« ce vieil entêté »"),
("B2","altéré / étranglé","떨리는 / 목이 멘","목소리 상태 묘사"),
("B2","les cals / les articulations","굳은살 / 관절","레아의 스케치 포인트"),
("B2","un menteur professionnel","직업적 거짓말쟁이","어머니 편지의 유머"),
("B2","taciturne / une réputation","과묵한 / 평판","« J'ai une réputation de taciturne. »"),
("C1","aimer comme on aime une vigne","포도나무를 사랑하듯 사랑하다","« en silence, avec des mains abîmées »"),
("C1","la différence entre aimer et posséder","사랑하는 것과 소유하는 것의 차이","제라르의 말"),
("C1","laisser un peu de sa voix dans la pierre","목소리를 조금 돌에 남기다","시적 표현"),
("C1","une vie qui te rende vivant","널 살아 있게 하는 삶","접속법(rende)이 쓰인 선호 관계절"),
("C1","Ne garde pas les mots.","말을 간직하지 마라.","가스통의 교훈과 일치"),
("C1","l'écho d'une voix gardée dans la pierre","돌에 간직된 목소리의 메아리","마지막 문장의 은유"),
("C1","le sens du terroir","테루아르 감각","27화 복습"),
("C1","une famille souriante","웃는 가족","사진 묘사 형용사"),
]
GRAM = [
("B1","현재와 과거의 교차: 편지의 시제",
 "« Je t'écris le seize mars. Tu as treize ans. Tu dors à l'étage. » 편지에서 어머니는 현재형으로 쓴다. 읽는 시점은 미래이므로 « Si tu lis ces lignes » 라는 조건절."),
("B2","접속법의 선호 관계절: une vie qui te rende vivant",
 "« Ce que je souhaite, c'est que tu choisisses une vie qui te rende vivant. » 희망을 나타내는 관계절의 접속법. 일반적인 사실이면 직설법 « une vie qui te rend vivant »."),
("B2","c'est que + 접속법/직설법: Ce que je souhaite, c'est que…",
 "« Ce que je souhaite, c'est que tu choisisses. » 분열문에서 소망의 접속법. 평서문은 « C'est que tu es heureux. » 직설법."),
("B2","최상급 + que + 접속법 과거 (복습)",
 "« C'est la plus belle phrase que j'aie entendue sur l'amour. » 시리즈 반복 문형."),
("B2","조건법 과거: Je pensais que je ne supporterais pas…",
 "« Je pensais que je ne supporterais pas de voir son écriture. » 과거 시점의 미래 = 조건법 현재. 간접화법에서의 미래 조건법."),
("C1","대명사 전치: Elle l'avait mise de côté pour « le jour où ils se parleront »",
 "« Elle l'avait mise de côté. » 직접목적어 l'(la bouteille)가 앞에 올 때 과거분사 일치(mise). le jour où + 미래: 미래의 시점 표현."),
("C1","si 조건과 일반 진리: si tu lis ces lignes, c'est que…",
 "« Si tu lis ces lignes, c'est que tu as grandi. » si + 현재, c'est que + 추론. 편지 서두에서 자주 쓰는 문형."),
("C1","수동태와 상황의 묘사: une boîte polie par les années",
 "« Une boîte polie par les années. » 과거분사 + par + 행위자. 형용사적 수동. 묘사의 품격을 높이는 문학적 장치."),
]
CULTURE = [
("루아르 지방의 튀포 저장고와 가족 유산",
 "루아르의 와인 농가는 튀포(tuffeau) 언덕에 판 지하 저장고(caveau)를 대대로 쓴다. 여기에 가족의 와인, 편지, 기록이 보관되는 경우가 있어 'transmission'(전승)의 중요한 상징이다."),
("마지막 편지: lettre testamentaire",
 "프랑스 문학과 일상에서 사후에 전달되는 편지는 깊은 감정의 매개다. 앙투안 어머니의 편지는 문어체 서한의 형식과 감정을 담고 있다."),
("가족 사진과 포도 수확",
 "수확철 가족 사진은 프랑스 농가의 대표적인 기억이다. 사진 속 아이들이 어깨 위에서 웃는 모습은 세대 계승의 시각적 증거이다."),
]
META = dict(part=4, ep=42, part_label="제4부 그랑 크뤼 · Grand cru", title_fr="Le caveau du père", title_ko="아버지의 저장고",
 place="생시르앙부르 델쿠르 농가의 지하 저장고(caveau) · 1월 3일 토요일 오전 10시",
 chars="Léa · Antoine · Gérard · Julien · La lettre d'Anne (어머니의 편지)",
 wine="Saumur-Champigny 1996 (어머니가 따로 챙겨 둔 병)",
 focus="상속·유산 어휘, 편지 문체, 접속법 관계절, 감정이 담긴 문어체",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제43화 « Chez le notaire » : 1월 30일 공증인 사무실. 영업권 양도 계약서 낭독과 법률 문체, 그리고 서명 뒤에 열린 한 병.")
