# -*- coding: utf-8 -*-
L, A, G, M, B, V, T, R, D_, J = "Léa", "Antoine", "Gaston", "Margaux", "Mme Aubry", "Mme Vasseur", "M. Tran", "Gérard", "M. Delaunay", "Julien"
D = [
(None, "Vendredi 27 février, 19 h. La veille de l'ouverture officielle, Léa et Antoine ont convié les amis et les clients fidèles à une soirée privée. La nouvelle enseigne vert bouteille, éclairée par deux petites lanternes de laiton, brille sur la devanture. À l'intérieur, la cave est pleine de monde, de rires, de verres qui tintent. Sur le comptoir de zinc, des assiettes de rillettes, de fromages de chèvre et de saucisson. Gaston, en costume de velours bleu nuit, la boutonnière ornée d'un brin de lavande, se tient près de l'entrée.", "2월 27일 금요일 오후 7시. 정식 개점 전날 레아와 앙투안이 친구들과 단골들을 초대해 비공개 파티를 연다. 두 개의 작은 황동 등이 비추는 새 병 녹색 간판이 정면에서 빛난다. 안은 사람들, 웃음소리, 부딪치는 잔으로 가득하다. 아연 카운터에는 리예트, 염소 치즈, 소시송 접시. 남색 벨벳 정장에 라벤더 한 가지를 꽂은 가스통이 입구 가까이 서 있다."),
(V, "Gaston ! Je n'en reviens pas : la devanture est magnifique. On dirait une photographie d'un autre siècle.", "가스통! 믿을 수가 없어요. 정면이 근사해요. 다른 세기의 사진 같아요."),
(G, "Madame Vasseur. Vous êtes ma cliente depuis trente ans, vous avez le droit de dire la vérité : est-ce que ça fait trop neuf ?", "바세르 부인. 삼십 년 단골이시니 진실을 말할 권리가 있어요. 너무 새것 같아 보이나요?"),
(V, "Trop neuf ? Mon cher, c'est le bon vieux lieu avec un sourire de plus. Rien de plus, rien de moins.", "너무 새것이냐고요? 친애하는 가스통, 좋은 옛 장소에 미소 하나가 더해진 거죠. 그 이상도 이하도 아니에요."),
(G, "Voilà ce que j'appelle une critique constructive.", "그게 바로 건설적인 비평이죠."),
(T, "(entre, souriant) Bonsoir, Gaston. J'ai fermé mon restaurant plus tôt pour venir. Mon chef de cuisine m'a traité de traître.", "(미소 지으며 들어와) 안녕하세요, 가스통. 오려고 식당을 일찍 닫았어요. 주방장이 저보고 배신자래요."),
(G, "Monsieur Tran, un client fidèle, c'est un homme qui trahit ses obligations pour ses plaisirs.", "트란 씨, 충성스러운 손님이란 쾌락을 위해 의무를 저버리는 사람이죠."),
(T, "Je préfère dire : un homme qui sait distinguer l'essentiel de l'accessoire.", "필수와 부수를 구별할 줄 아는 사람이라고 하고 싶네요."),
(L, "(s'approche, un plateau à la main) Monsieur Tran, madame Vasseur, une rillette de canard, un fromage de chèvre frais ?", "(쟁반을 들고 다가가며) 트란 씨, 바세르 부인, 오리 리예트나 신선한 염소 치즈 드실래요?"),
(T, "Avec plaisir. Et ce vin, c'est un Bourgueil ?", "기꺼이요. 이 와인은 부르괴유인가요?"),
(L, "Oui, de Didier Marchais. Il vient demain avec sa vendange de quatre-vingt-dix.", "네, 디디에 마르셰의 것이에요. 내일 1990년 수확을 들고 올 거예요."),
(V, "Sa vendange de quatre-vingt-dix ? Mais c'est l'année de l'ouverture de la cave !", "1990년 수확이요? 이 가게가 문을 연 해인데!"),
(L, "C'est ce qu'on a découvert. Un hasard qui ne doit rien au hasard.", "저희도 그렇게 알게 됐어요. 우연이 아닌 우연이죠."),
(T, "Vous parlez comme Gaston.", "가스통처럼 말하네요."),
(L, "C'est la contagion du métier.", "직업 감염이에요."),
(None, "La porte s'ouvre une nouvelle fois. Gérard, le père d'Antoine, en veste de tweed, entre avec Julien, chargés d'une caisse de vin. Derrière eux, Madame Aubry, élégante dans un manteau gris perle, un petit sac de cuir à la main.", "문이 다시 열린다. 앙투안의 아버지 제라르가 트위드 재킷을 입고 줄리앙과 함께 와인 상자를 들고 들어온다. 뒤에는 진주빛 회색 코트를 입은 오브리 부인이 작은 가죽 가방을 들고 우아하게 따라온다."),
(R, "Voilà, voilà ! La cave de Saumur est arrivée à Paris. Douze bouteilles de Saumur-Champigny, du domaine familial.", "자, 보세요! 소뮈르의 와인이 파리에 도착했습니다. 가문 와이너리의 소뮈르샹피니 열두 병입니다."),
(A, "Papa ! Tu aurais dû nous prévenir, je serais venu t'aider.", "아빠! 알려 주셨으면 도와드리러 갔을 텐데요."),
(R, "Je ne voulais pas gâcher la surprise. Un père qui arrive les mains pleines, c'est un père fier.", "깜짝 선물을 망치고 싶지 않았다. 손에 가득 들고 오는 아버지는 자랑스러운 아버지란다."),
(B, "(à Léa) Mademoiselle Fontaine, bonsoir. La banque est représentée par une cliente enthousiaste, ce soir.", "(레아에게) 퐁텐 양, 안녕하세요. 오늘 밤 은행은 열광적인 고객 한 사람이 대표합니다."),
(L, "Madame Aubry, vous êtes la bienvenue. J'espère que nous ne vous décevrons pas.", "오브리 부인, 환영합니다. 실망시켜 드리지 않기를 바라요."),
(B, "Mademoiselle, un banquier ne déçoit jamais ; c'est son client qui peut le décevoir. Et jusqu'ici, vous me comblez.", "아가씨, 은행가는 절대 실망하지 않아요. 고객이 실망시키는 거죠. 그리고 지금까지 당신들은 저를 충족시켜 주고 있어요."),
(M, "(se glisse à côté) Madame Aubry, je vous présente le toast que Gaston prépare depuis deux semaines. Il refuse de me le montrer.", "(옆으로 다가와) 오브리 부인, 가스통이 이 주 동안 준비한 건배사예요. 저에게도 보여 주기를 거부했어요."),
(B, "Les grands orateurs ne répètent pas devant un notaire.", "위대한 연설가는 공증인 앞에서 연습하지 않죠."),
(M, "Je suis avocate, pas notaire.", "전 변호사예요, 공증인이 아니라."),
(B, "Pardon. Dans ma génération, on confond encore les deux professions avec indulgence.", "죄송해요. 제 세대에서는 아직 두 직업을 관대하게 혼동하죠."),
(None, "Cependant, une silhouette se glisse dans l'embrasure de la porte : M. Delaunay, en manteau noir, tenant un long paquet enveloppé de papier de soie. Un silence se propage. Gaston se tourne lentement.", "그때 문틈으로 한 실루엣이 스며든다. 검은 코트를 입고 얇은 포장지에 싼 긴 꾸러미를 든 들로네다. 침묵이 퍼진다. 가스통이 천천히 돌아본다."),
(D_, "Monsieur Roussel. Madame Fontaine. Monsieur Delcourt. Je ne m'attendais pas à ce que la porte soit ouverte.", "루셀 씨. 퐁텐 씨. 델쿠르 씨. 문이 열려 있을 줄은 몰랐습니다."),
(G, "Elle est toujours ouverte, Étienne. C'est le principe d'une cave.", "항상 열려 있어요, 에티엔. 가게의 원칙이지."),
(D_, "(après un temps) Je ne viens pas pour m'excuser. Je viens pour apporter ceci, en reconnaissance de la belle manière dont vous avez conduit cette affaire.", "(잠시 뒤) 사과하러 온 게 아닙니다. 이 일을 아름답게 이끌어 주신 데 대한 인정의 표시로 이걸 가져왔습니다."),
(None, "Il tend le paquet à Léa. Elle l'ouvre : un magnum de champagne, étiquette dorée. Un Krug 1996.", "그가 꾸러미를 레아에게 건넨다. 그녀가 열자 금빛 라벨의 샴페인 매그넘 한 병이 나온다. 크뤼그 1996이다."),
(L, "Monsieur Delaunay... c'est un cadeau extraordinaire.", "들로네 씨... 엄청난 선물이에요."),
(D_, "Un concurrent bien élevé offre toujours le champagne à ceux qui l'ont battu. Ce n'est pas une règle, c'est une tradition.", "교양 있는 경쟁자는 자기를 이긴 사람에게 항상 샴페인을 선물하죠. 규칙이 아니라 전통입니다."),
(G, "(tend la main) Étienne. Restez, je vous prie. Il serait absurde d'ouvrir un Krug sans l'homme qui l'a apporté.", "(손을 내밀며) 에티엔. 부디 있어 주세요. 가져온 사람 없이 크뤼그를 따는 건 어불성설이죠."),
(D_, "(hésite, puis serre la main) Je reste. Un seul verre.", "(망설이다 악수하며) 있겠습니다. 한 잔만."),
(None, "Un murmure de soulagement parcourt la salle. Julien tape discrètement dans le dos de son frère.", "안도의 웅성거림이 방 안을 지나간다. 줄리앙이 형의 등을 슬며시 두드린다."),
(J, "Mon frère, tu viens d'assister à un traité de paix.", "형, 평화 조약을 직접 목격했네."),
(A, "J'ai surtout vu un grand cru s'ouvrir avant d'être bu.", "나는 마시기도 전에 열리는 그랑 크뤼를 본 것 같아."),
(None, "Quelques minutes plus tard, tous les invités sont rassemblés au centre de la cave. Antoine fait tinter un verre avec une cuillère. Le silence tombe.", "몇 분 뒤 모든 손님이 가게 중앙에 모인다. 앙투안이 숟가락으로 잔을 두드린다. 침묵이 내린다."),
(A, "Mesdames et messieurs, chers amis. Avant d'ouvrir le Krug de monsieur Delaunay, nous avons une demande à formuler.", "신사 숙녀 여러분, 친구 여러분. 들로네 씨의 크뤼그를 따기 전에 한 가지 부탁이 있습니다."),
(L, "Nous demandons à Gaston de nous dire quelques mots. Les derniers mots qu'il prononcera comme propriétaire de cette cave.", "가스통에게 몇 말씀을 청합니다. 이 가게의 주인으로서 하는 마지막 말씀이 될 거예요."),
(G, "(se redresse, pose son verre) On m'a dit que les discours doivent être courts. Je promets d'être bref. Pour moi.", "(몸을 일으켜 잔을 내려놓으며) 연설은 짧아야 한다고 들었지. 약속하죠, 짧게 하겠소. 내 기준으로는."),
(None, "Rires attendris. Gaston sort de sa poche un petit carnet, l'ouvre, puis le referme avec un sourire.", "정다운 웃음. 가스통이 주머니에서 작은 수첩을 꺼내 펼쳤다가 미소를 지으며 닫는다."),
(G, "J'avais préparé quelques notes. Je viens de comprendre que je n'en ai pas besoin. Ce que je veux dire, je le sais depuis trente-cinq ans.", "메모를 준비했는데 필요 없다는 걸 방금 깨달았어요. 하고 싶은 말은 삼십오 년 전부터 알고 있었소."),
(G, "Je me souviens du jour où j'ai ouvert cette porte pour la première fois. C'était en mille neuf cent quatre-vingt-dix. Il pleuvait. J'avais trente-trois ans, un prêt à rembourser, et trois cents bouteilles sur des étagères branlantes.", "처음 이 문을 열던 날을 기억합니다. 1990년이었고 비가 왔죠. 서른세 살에 갚아야 할 대출과 흔들리는 선반 위 삼백 병이 전부였소."),
(G, "Je me souviens de mon premier client : un facteur, qui m'a acheté une bouteille de Beaujolais et qui m'a dit : « Vous ne tiendrez pas six mois. » Il avait tort de quelques décennies.", "첫 손님도 기억합니다. 우체부였는데 보졸레 한 병을 사며 이렇게 말했죠. '6개월도 못 버티겠소.' 그는 몇십 년쯤 틀렸소."),
(G, "Je me souviens de ceux qui sont venus, et de ceux qui ne sont jamais repartis. De ceux qui ont pleuré dans mon arrière-boutique, de ceux qui y ont ri, et de ceux qui y ont demandé leur femme en mariage, au milieu des caisses.", "찾아온 이들과 영영 떠나지 않은 이들도 기억합니다. 내 안쪽 창고에서 울던 이들, 웃던 이들, 상자들 사이에서 아내에게 청혼한 이들."),
(V, "(essuie une larme, à voix basse) Mon mari, par exemple.", "(눈물을 닦으며 작게) 우리 남편이 그랬죠."),
(G, "Je me souviens, madame Vasseur. Il avait apporté lui-même la bague, cachée dans une bouteille de Sauternes vide.", "기억합니다, 바세르 부인. 반지를 직접 빈 소테른 병 속에 숨겨 왔었죠."),
(G, "Voilà ce qu'est une cave : pas un magasin, pas un commerce, pas un lieu de transaction. Un lieu de mémoire où le temps s'arrête dans les bouteilles pour mieux s'écouler dans les hommes.", "가게란 이런 곳입니다. 상점이 아니고 장사가 아니고 거래의 장소가 아니죠. 병 속에서 시간이 멈추어 사람들 안에서 더 잘 흐르게 하는 기억의 장소요."),
(G, "On m'a souvent demandé pourquoi je ne me lassais pas de ce métier. La réponse est simple : on ne se lasse pas de ce qui nous rend meilleurs que nous ne sommes.", "왜 이 일에 질리지 않느냐고 자주 물으셨죠. 답은 간단하오. 우리를 있는 그대로보다 더 낫게 만드는 것에는 질리지 않는 법이오."),
(G, "Ce soir, je passe le témoin. Pas à des inconnus, pas à des repreneurs, mais à deux personnes que j'ai vues se rencontrer, ici même, devant la dernière bouteille de Morgon.", "오늘 밤 저는 바통을 넘깁니다. 낯선 이들에게도 인수자들에게도 아니라, 바로 여기서 마지막 모르공 병 앞에서 만나는 걸 본 두 사람에게."),
(G, "Je les ai observés : elle, orgueilleuse comme un vin trop jeune ; lui, timide comme un grand cru qui n'ose pas encore s'ouvrir. Ni l'un ni l'autre ne voulait céder la bouteille. Et c'est précisément pour cela que j'ai su qu'ils s'aimeraient.", "지켜봤죠. 그녀는 너무 어린 와인처럼 도도하고 그는 아직 열릴 용기가 없는 그랑 크뤼처럼 수줍었소. 둘 다 병을 양보하려 하지 않았고 바로 그래서 사랑하게 될 줄 알았지."),
(L, "(à voix basse, riant malgré elle) Il le savait depuis le début ?", "(작게 웃음을 참으며) 처음부터 알고 계셨던 거야?"),
(A, "(à voix basse) Je commence à le soupçonner depuis octobre.", "(작게) 10월부터 의심하기 시작했어요."),
(G, "Ils m'ont demandé ce soir un toast. Voici mon vœu, le seul : que cette cave reste ouverte aux faibles comme aux forts, aux riches comme aux pauvres, aux savants comme aux ignorants. Qu'on y serve toujours le vin avec le sourire, et le sourire avec le vin.", "오늘 밤 건배사를 청하셨소. 제 소원은 하나요. 이 가게가 약한 이에게도 강한 이에게도, 부유한 이에게도 가난한 이에게도, 아는 이에게도 모르는 이에게도 열려 있기를. 거기서 늘 미소와 함께 와인을, 와인과 함께 미소를 내놓기를."),
(G, "Qu'on y apprenne, comme j'y ai appris, qu'un vin ne vaut rien s'il n'est pas partagé. Qu'on y découvre que le temps n'est pas notre ennemi, mais notre complice. Et qu'on y comprenne que l'amour, comme le vin, ne se force pas : il se garde, il se guette, il se mérite.", "여기서 제가 배웠듯이 나누지 않는 와인은 아무 가치도 없음을 배우기를. 시간이 적이 아니라 공범임을 발견하기를. 그리고 사랑은 와인처럼 강요할 수 없고 간직하고 기다리고 얻어 내는 것임을 이해하기를."),
(G, "(il lève son verre) À Léa et à Antoine, qui ne s'appellent pas encore par un nom commun, mais qui, j'en suis certain, finiront par en avoir un.", "(잔을 들며) 레아와 앙투안을 위하여. 아직 공동의 이름으로 불리진 않지만 언젠가 그렇게 될 것을 나는 확신하오."),
(G, "À La Cave des Abbesses, qui n'a pas de propriétaire, mais des gardiens. À ceux qui sont partis, à ceux qui sont restés, à ceux qui viendront. Et à la vie, qui, comme un grand vin, ne livre son secret qu'à ceux qui ont la patience de l'attendre.", "주인이 아니라 수호자들이 있는 라 카브 데 자베스를 위하여. 떠난 이들, 남은 이들, 올 이들을 위하여. 그리고 위대한 와인처럼 기다릴 인내를 가진 이에게만 비밀을 내주는 삶을 위하여."),
(None, "Un silence ému, puis des applaudissements qui montent, qui roulent, qui emplissent la cave. Madame Vasseur pleure ouvertement. Monsieur Tran applaudit debout. Étienne Delaunay, au fond, frappe lentement dans ses mains. Gérard essuie ses lunettes.", "감동의 침묵 뒤에 박수가 솟고 구르고 가게를 채운다. 바세르 부인은 드러내 놓고 운다. 트란 씨는 서서 박수 친다. 안쪽의 에티엔 들로네가 천천히 손뼉을 친다. 제라르는 안경을 닦는다."),
(R, "(à Antoine) Mon fils, ton grand-père aurait aimé cet homme.", "(앙투안에게) 아들아, 네 할아버지가 이 사람을 좋아하셨을 거다."),
(A, "(la gorge nouée) Moi aussi, je l'aime.", "(목이 메어) 나도 이분이 좋아요."),
(L, "(s'approche de Gaston et l'embrasse sur les deux joues) Gaston, vous avez dit des choses que je n'oublierai jamais.", "(가스통에게 다가가 양 볼에 입을 맞추며) 가스통, 평생 잊지 못할 말씀을 해 주셨어요."),
(G, "(ému) Je n'ai fait que mon devoir, petite. Je suis un vieux marchand de vin qui a eu la chance de rencontrer de bons clients.", "(감동하여) 내 의무를 다했을 뿐이야, 아가. 좋은 손님들을 만난 행운을 누린 늙은 와인 상인이니까."),
(B, "(s'avance) Monsieur Roussel, au nom de la banque et en mon nom propre : c'était un très beau discours. J'ai rarement vu une transmission aussi réussie.", "(앞으로 나서며) 루셀 씨, 은행을 대표하고 제 이름으로 말씀드립니다. 아주 아름다운 연설이었어요. 이렇게 성공적인 승계는 드물게 봤어요."),
(G, "Merci, madame. La banque a le cœur plus grand que je ne le croyais.", "고맙습니다, 부인. 은행 마음이 생각보다 크군요."),
(B, "Nous avons le cœur discret. Ce qui n'est pas la même chose que le cœur petit.", "우리 마음은 조용한 것이지 작은 게 아니에요. 둘은 다르죠."),
(J, "(tend à Antoine le Krug) Frérot, à toi l'honneur.", "(앙투안에게 크뤼그를 건네며) 형, 영광은 형 몫이야."),
(A, "Non. Cet honneur revient à celui qui a fait l'offre. Monsieur Delaunay ?", "아니. 이 영광은 선물한 분께 돌아가요. 들로네 씨?"),
(D_, "(surpris) Moi ? Vous me confiez le magnum ?", "(놀라서) 제게요? 매그넘을 맡기시는 겁니까?"),
(A, "Vous l'avez apporté. Il est naturel que vous le déboucliez, comme on rend un honneur à son hôte.", "가져오신 분이시니 따는 것도 당연히 당신 몫입니다. 손님에게 경의를 돌려드리듯이요."),
(D_, "(prend la bouteille, sourit pour la première fois) Voilà une façon élégante de vaincre un adversaire : en l'invitant à gagner un peu.", "(병을 받아 처음으로 미소 지으며) 적수를 이기는 우아한 방법이군요. 조금 이기게 초대하는 것."),
(None, "Il fait sauter le bouchon avec un « pop » solennel. Les flûtes se remplissent d'or pétillant. Les convives lèvent leurs verres vers le plafond bas de la cave.", "그가 장엄한 '퐁' 소리와 함께 마개를 따낸다. 플루트 잔이 반짝이는 금빛으로 채워진다. 손님들이 가게의 낮은 천장을 향해 잔을 든다."),
(T, "À la cave !", "가게를 위하여!"),
(V, "À Gaston !", "가스통을 위하여!"),
(R, "À la jeunesse !", "젊음을 위하여!"),
(B, "À la transmission !", "승계를 위하여!"),
(D_, "(à voix basse, à Gaston) À la loyauté. J'avais oublié qu'elle existait.", "(가스통에게 작게) 신의를 위하여. 존재한다는 걸 잊고 있었군요."),
(G, "(à voix basse) On ne l'oublie pas, Étienne. On l'égare. Et parfois, on la retrouve dans une cave.", "(작게) 잊는 게 아니라 잃어버리는 거요, 에티엔. 그리고 때로는 지하 저장고에서 되찾기도 하지."),
(None, "Plus tard dans la soirée. Les invités se dispersent par petits groupes. Dans un coin, Gérard et Gaston, deux verres de Saumur-Champigny à la main, parlent du temps passé. Léa et Antoine, assis sur les marches de l'escalier de la cave, regardent la salle animée.", "그날 밤 늦게. 손님들이 삼삼오오 흩어진다. 한쪽 구석에서 제라르와 가스통이 소뮈르샹피니 잔을 들고 지난 시간을 이야기한다. 레아와 앙투안은 지하 저장고 계단에 앉아 활기찬 가게를 바라본다."),
(R, "Monsieur Roussel, permettez-moi de vous dire une chose que je n'ai pas osé dire à votre table à Noël.", "루셀 씨, 크리스마스 식탁에서 감히 하지 못한 말씀을 드려도 될까요."),
(G, "Dites, Gérard. Entre vignerons, on se parle franchement.", "말씀하세요, 제라르. 포도밭 사람들끼리는 솔직하게 말하죠."),
(R, "Quand mon fils m'a annoncé qu'il quittait sa vie d'enseignant pour devenir caviste, j'ai eu peur. Une peur de père.", "아들이 교사 생활을 접고 와인 상인이 되겠다고 했을 때 겁이 났습니다. 아버지의 두려움이었죠."),
(G, "Et maintenant ?", "그럼 지금은요?"),
(R, "Maintenant, je vois la façon dont vous le regardez, dont il vous regarde. Je comprends qu'il ne quitte rien : il hérite d'une autre famille.", "지금은 당신이 그를 보는 모습, 그가 당신을 보는 모습을 보고 있습니다. 아들은 무언가를 떠나는 게 아니라 또 다른 가족을 물려받는 거라는 걸 알겠어요."),
(G, "Vous me faites un grand honneur, Gérard.", "큰 영광입니다, 제라르."),
(R, "Je ne fais que dire la vérité. À mon âge, on n'a plus le temps de faire autre chose.", "진실을 말할 뿐입니다. 제 나이에는 다른 걸 할 시간이 없죠."),
(G, "Alors trinquons à la vérité, qui est toujours un peu rude, comme un jeune Saumur.", "그럼 진실을 위해 건배합시다. 어린 소뮈르처럼 늘 약간 거칠긴 하지만."),
(R, "Et qui s'améliore avec les années, comme un vieux Saumur.", "그리고 오래된 소뮈르처럼 세월이 지나며 좋아지죠."),
(G, "(rit) Voilà un viticulteur qui sait finir une phrase.", "(웃으며) 문장을 마무리할 줄 아는 포도 재배자로군."),
(R, "C'est notre seul talent, à nous les gens de la terre.", "우리 흙의 사람들의 유일한 재능이죠."),
(G, "Non. Vous avez aussi celui d'élever de bons fils.", "아니, 훌륭한 아들을 키우는 재능도 있지요."),
(L, "Tu as entendu ce qu'il a dit sur nous ?", "가스통이 우리에 대해 한 말 들었어요?"),
(A, "« Elle, orgueilleuse comme un vin trop jeune. Lui, timide comme un grand cru qui n'ose pas s'ouvrir. » C'est assez juste.", "'그녀는 너무 어린 와인처럼 도도하고 그는 열릴 용기가 없는 그랑 크뤼처럼 수줍다.' 꽤 정확해요."),
(L, "Il manquait une phrase : « Ils se sont ouverts ensemble. »", "한 문장이 빠졌어요. '그들은 함께 열렸다.'"),
(A, "Je la lui suggérerai. Pour le discours de demain.", "그분께 제안해 볼게요. 내일 연설을 위해서요."),
(L, "Demain, il ne parlera pas. Demain, c'est nous qui parlons.", "내일은 그분이 말씀 안 하세요. 내일은 우리가 말하는 날이에요."),
(A, "Alors il va falloir apprendre à rivaliser avec Gaston.", "그럼 가스통과 겨루는 법을 배워야겠네요."),
(L, "Impossible. On peut seulement essayer d'être à la hauteur.", "불가능해요. 그 수준에 걸맞게 노력할 수 있을 뿐이죠."),
(A, "Je n'ai pas peur de demain. J'ai peur de l'après-demain, quand il faudra faire vivre cette cave sans Gaston.", "내일은 안 무서워요. 모레가 무서워요. 가스통 없이 이 가게를 살려야 할 때가."),
(L, "Il sera là. À dix heures, il viendra voir si on s'occupe bien de sa cave.", "그분은 계실 거예요. 열 시에 가게를 잘 돌보는지 보러 오실 테니까요."),
(A, "Et s'il trouve qu'on s'en occupe mal ?", "만약 잘못 돌본다고 하시면요?"),
(L, "Alors il nous le dira avec élégance, et on s'améliorera.", "그럼 우아하게 말씀하실 테고 우리는 나아질 거예요."),
(A, "Tu sais que tu es la personne la moins inquiète que je connaisse ?", "내가 아는 가장 걱정 없는 사람이 당신이라는 거 알아요?"),
(L, "Je suis inquiète tout le temps. Mais je le cache en préparant des listes.", "항상 걱정해요. 다만 목록을 만들면서 숨기죠."),
(A, "Ça explique les trois cent soixante-huit descriptions.", "삼백육십팔 개 설명이 설명되네요."),
(L, "(rit) Voilà. Tu as percé mon mystère.", "(웃으며) 맞아요. 내 비밀을 간파했네요."),
(A, "Et toi, tu as percé le mien.", "그리고 당신은 내 비밀을 간파했죠."),
(L, "Lequel ?", "어떤 거요?"),
(A, "Que je n'ose rien dire sans que tu m'en donnes la permission.", "당신이 허락하지 않으면 아무 말도 못 한다는 것."),
]
VOCAB = [
("A2","les invités / un client fidèle","손님들 / 단골","파티 어휘"),
("A2","tinter / un verre","잘랑거리다 / 잔","« les verres tintent »"),
("A2","un cadeau / offrir","선물 / 선물하다","들로네의 크뤼그"),
("B1","la devanture / l'enseigne","가게 정면 / 간판","새 간판"),
("B1","un facteur","우체부","첫 손님의 직업"),
("B1","une transmission / le témoin","전승 / 바통","« passer le témoin »"),
("B1","un toast / porter un toast","건배사 / 건배하다","연설 장르"),
("B2","un orateur / un discours","연설가 / 연설","« Les grands orateurs ne répètent pas devant un notaire. »"),
("B2","se lasser de","~에 질리다","« on ne se lasse pas de ce qui… »"),
("B2","une critique constructive","건설적 비평","직업적 표현"),
("B2","combler / décevoir","충족시키다 / 실망시키다","« Vous me comblez. »"),
("B2","égarer / guetter / mériter","잃어버리다 / 기다리다 / 얻을 자격이 있다","« il se garde, il se guette, il se mérite »"),
("B2","déboucher / un magnum","마개를 따다 / 매그넘(1.5L)","샴페인 개봉"),
("B2","branlant","흔들리는","« étagères branlantes »"),
("C1","je passe le témoin","나는 바통을 넘긴다","연설의 핵심 동사구"),
("C1","un lieu de mémoire","기억의 장소","피에르 노라의 용어에서 유래"),
("C1","le temps s'arrête dans les bouteilles pour mieux s'écouler dans les hommes","병에서 멈춘 시간이 사람 속에서 더 잘 흐른다","대구와 역설"),
("C1","un concurrent bien élevé","교양 있는 경쟁자","« bien élevé » = 예의 바른"),
("C1","vaincre un adversaire en l'invitant à gagner un peu","상대를 조금 이기게 초대하여 이기다","역설 문장"),
("C1","avoir le cœur discret","마음이 조용하다","오브리 부인의 위트"),
("C1","on ne l'oublie pas, on l'égare","잊는 게 아니라 잃어버리는 것","ne… pas… mais 정정 구조"),
("C1","à la hauteur","수준에 걸맞은","« être à la hauteur »"),
]
GRAM = [
("A2","기본 인사와 건배 표현: À la cave ! À Gaston !",
 "À + 대상 = ~를 위하여. 건배 표현은 간결하게 쓴다. « À la santé de… » 도 가능."),
("B1","대과거와 복합과거 구분: j'avais préparé / j'ai compris",
 "« J'avais préparé quelques notes. Je viens de comprendre… » 대과거(plus-que-parfait)는 과거의 더 이전 사건. venir de + 부정사는 근접 과거."),
("B1","이중 부정과 강조: ni l'un ni l'autre",
 "« Ni l'un ni l'autre ne voulait céder la bouteille. » ni… ni… + 동사는 ne만 쓰고 pas는 쓰지 않는다. 주어에 올 때 동사는 보통 단수/복수 모두 가능."),
("B2","접속법 기원: Que cette cave reste ouverte",
 "« Que cette cave reste ouverte… Qu'on y serve toujours le vin avec le sourire. » Que + 접속법 = 소원·기원. 연설과 축사에 흔하다."),
("B2","수사법 — 아나포라(anaphore)",
 "« Je me souviens… Je me souviens… » 같은 문두 반복은 리듬을 만들고 감정을 고조시킨다. 가스통의 연설 핵심 기법."),
("B2","대명사 동사의 수동·일반 의미: il se garde, il se guette, il se mérite",
 "« L'amour… ne se force pas : il se garde, il se guette, il se mérite. » 재귀 대명사 동사가 일반적 진리를 표현하는 수동 의미를 가진다."),
("C1","병렬·대구(antithèse, parallélisme): aux faibles comme aux forts",
 "« aux faibles comme aux forts, aux riches comme aux pauvres, aux savants comme aux ignorants » 대립어를 병렬시켜 포용의 이미지를 만든다."),
("C1","관계절 + 접속법: celui qui a fait l'offre / quelqu'un qui sache",
 "« Il est naturel que vous le débouchiez. » 감정·평가 표현(il est naturel que) 뒤 접속법. « Il serait absurde d'ouvrir… sans l'homme qui l'a apporté. » 조건법 + 관계절."),
]
CULTURE = [
("프랑스의 건배(toast)와 연설 전통",
 "프랑스에서는 공적 모임에서 주최자나 연장자가 건배사를 한다. 문장은 일화, 인용, 은유, 감사 순으로 구성되며 마지막은 À… 로 맺는다. 가스통의 연설은 이 전통의 모범이다."),
("크뤼그(Krug)와 샴페인 선물 문화",
 "크뤼그는 최고급 샴페인 하우스로 매우 고가이다. 경쟁자가 샴페인을 선물하는 것은 존경과 화해의 표시이다. 매그넘(1.5L)은 축하 자리의 상징이다."),
("lieu de mémoire — 기억의 장소",
 "역사학자 피에르 노라가 제시한 개념으로 공동체의 기억이 응축된 장소를 뜻한다. 가스통은 와인 가게를 단순한 상점이 아닌 기억의 장소로 정의한다."),
]
META = dict(part=4, ep=46, part_label="제4부 그랑 크뤼 · Grand cru", title_fr="Le toast de Gaston", title_ko="가스통의 건배사",
 place="라 카브 데 자베스 · 2월 27일 금요일 오후 7시 (개점 전야 파티)",
 chars="Léa · Antoine · Gaston · Margaux · Mme Aubry · Mme Vasseur · M. Tran · Gérard · Julien · M. Delaunay",
 wine="Krug 1996 magnum · Bourgueil (Marchais) · Saumur-Champigny (Gérard)",
 focus="연설 문체, 아나포라·대구·역설, 접속법 기원, 고급 관용구",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제47화 « Inauguration » : 2월 28일 토요일, 새 간판 아래 문을 여는 날. 다인 대화, 환영 인사, 예기치 않은 손님들.")
