# -*- coding: utf-8 -*-
L, A, G, K, F, E, N, J, V, Q = "Léa", "Antoine", "Gaston", "M. Lebrun", "Mme Garnier", "Aya", "Kenji", "Didier Marchais", "Mme Marchais", "Mme Vasseur"
M, JU, CL = "Margaux", "Julien", "Une cliente"
D = [
(None, "Samedi 28 février, 9 h 30. Un ciel clair, un soleil timide, un froid vif. Sur la devanture vert bouteille de la rue des Abbesses, la nouvelle enseigne dorée brille : « LA CAVE DES ABBESSES — Léa Fontaine & Antoine Delcourt, depuis 1990 ». À l'intérieur, Léa polit une dernière fois le zinc, Antoine range des verres sur l'étagère du haut. On entend un air de jazz lointain.", "2월 28일 토요일 오전 9시 30분. 맑은 하늘, 수줍은 햇살, 차가운 공기. 아베스 거리의 병 녹색 정면에 새 금빛 간판이 빛난다. '라 카브 데 자베스 — 레아 퐁텐 & 앙투안 델쿠르, 1990년부터.' 안에서 레아가 마지막으로 아연 카운터를 닦고 앙투안이 맨 위 선반에 잔을 정리한다. 멀리서 재즈 선율이 들린다."),
(A, "Il reste vingt-huit minutes. Je ne sais plus si j'ai trop chaud ou trop froid.", "28분 남았어요. 너무 더운지 너무 추운지도 모르겠어요."),
(L, "C'est la peur, ça. Elle donne les deux sensations en même temps.", "그건 두려움이에요. 두 감각을 동시에 줘요."),
(A, "Tu as déjà ouvert un commerce ?", "가게를 열어 본 적 있어요?"),
(L, "Non. Mais j'ai déjà présenté un projet à cinquante personnes en costume. C'est la même nausée.", "아니요. 하지만 정장 입은 오십 명 앞에서 프로젝트를 발표해 본 적은 있죠. 구역질이 똑같아요."),
(A, "Et comment tu la fais passer ?", "그건 어떻게 가라앉혀요?"),
(L, "Je me répète : « Je sais exactement de quoi je parle. » Et je souris. Le sourire finit par convaincre le cerveau.", "'나는 내가 무슨 얘기를 하는지 정확히 안다'고 되뇌어요. 그리고 웃어요. 미소가 결국 뇌를 설득하거든요."),
(None, "On frappe doucement à la vitre. Gaston, en manteau de laine camel et chapeau, tient une baguette et un sac de papier. Il est dix heures moins vingt-cinq.", "유리를 가만히 두드린다. 낙타색 울 코트와 모자 차림의 가스통이 바게트와 종이봉투를 들고 있다. 10시 25분 전이다."),
(G, "Je ne suis pas là en avance, je suis là à l'heure d'un autre temps.", "내가 일찍 온 게 아니라 다른 시간의 정시에 온 거야."),
(L, "Entrez, Gaston. Vous êtes chez vous.", "들어오세요, 가스통. 댁이시잖아요."),
(G, "Je suis chez vous. Nuance importante. (Il entre.) Je vous ai apporté un petit déjeuner : croissants, baguette, et cette confiture de figues de ma voisine.", "자네들 집이지. 중요한 뉘앙스야. (들어간다) 아침 식사를 가져왔네. 크루아상, 바게트, 이웃집 무화과 잼."),
(A, "Vous êtes un homme prévoyant.", "배려 깊은 분이시네요."),
(G, "Je suis un homme qui a déjà vu un jour d'ouverture. Personne ne mange. Tout le monde a l'estomac noué.", "개점 날을 본 사람이야. 아무도 안 먹어. 다들 속이 막히지."),
(L, "(prend un croissant) Alors je serai la première à vous contredire.", "(크루아상을 집으며) 그럼 제가 처음으로 반박할게요."),
(None, "Gaston s'avance jusqu'à la porte, la regarde longuement, puis sort de sa poche un petit objet enveloppé dans un mouchoir : une clochette de laiton, usée, qu'il tient comme une relique.", "가스통이 문 앞까지 걸어가 오래 바라보고 주머니에서 손수건에 싼 작은 물건을 꺼낸다. 닳은 황동 방울이다. 그는 유물처럼 들고 있다."),
(G, "Voilà. La clochette de la porte. Elle est là depuis le premier jour. Je l'avais ôtée avant les travaux pour qu'elle ne soit pas abîmée.", "자, 문의 방울이야. 첫날부터 있었지. 공사 전에 상하지 않게 떼어 두었어."),
(L, "Gaston... Vous voulez qu'on la remette ?", "가스통... 다시 달아도 될까요?"),
(G, "Je veux que ce soit vous qui le fassiez. C'est le dernier geste de transmission.", "자네들이 달았으면 하네. 승계의 마지막 몸짓이지."),
(A, "(prend la clochette, monte sur l'escabeau, l'accroche au-dessus de la porte) Voilà. Elle tinte.", "(방울을 받아 발판 위에 올라 문 위에 건다) 자, 울려요."),
(None, "Un petit « tintement » clair résonne. Tous se taisent, un instant. Gaston essuie ses lunettes.", "작고 맑은 '딸랑' 소리가 울린다. 모두 잠시 침묵한다. 가스통이 안경을 닦는다."),
(G, "C'est le même son. Trente-cinq ans, et c'est le même son.", "같은 소리야. 삼십오 년이 지났는데 같은 소리야."),
(None, "Dix heures pile. Léa retourne la pancarte « Fermé » sur « Ouvert ». Elle ouvre la porte. Une petite foule attend déjà dehors, emmitouflée : madame Vasseur, monsieur Tran, un jeune couple de Japonais, et un vieux monsieur en casquette de facteur.", "정각 10시. 레아가 '닫힘' 팻말을 '영업 중'으로 뒤집고 문을 연다. 밖에는 벌써 작은 무리가 두툼하게 껴입고 기다린다. 바세르 부인, 트란 씨, 일본인 젊은 부부, 그리고 우체부 모자를 쓴 노신사."),
(L, "Bonjour, bonjour ! Soyez les bienvenus à La Cave des Abbesses.", "안녕하세요, 안녕하세요! 라 카브 데 자베스에 오신 것을 환영합니다."),
(K, "(ôte sa casquette) Mademoiselle, je suis le premier ?", "(모자를 벗으며) 아가씨, 내가 첫 손님인가요?"),
(L, "Vous êtes le premier de la journée, monsieur.", "오늘의 첫 손님이세요, 선생님."),
(K, "Alors c'est un grand jour pour moi aussi. Il y a trente-cinq ans, j'ai été le premier client de monsieur Roussel. Je lui avais dit qu'il ne tiendrait pas six mois.", "그렇다면 저에게도 큰 날이군요. 35년 전 저는 루셀 씨의 첫 손님이었어요. 6개월도 못 버틸 거라고 말했죠."),
(G, "(s'avance, souriant) Lebrun ! C'est toi ! Tu as vieilli.", "(미소 지으며 다가와) 르브룅! 자네군! 늙었구먼."),
(K, "Toi aussi. Mais la cave, elle, a rajeuni. Je suis venu me faire pardonner : il me faut une bouteille de Beaujolais.", "자네도 그래. 하지만 가게는 젊어졌군. 용서를 구하러 왔네. 보졸레 한 병이 필요해."),
(G, "Le Morgon est en tête de carte, juste à côté de la caisse.", "모르공은 리스트 맨 앞, 계산대 바로 옆에 있네."),
(K, "(lit l'étiquette) « Le vin qui nous a réunis. » C'est joli. Et vrai ?", "(라벨을 읽으며) '우리를 이어 준 와인.' 예쁘군. 사실인가요?"),
(L, "Absolument vrai, monsieur. Antoine et moi, nous avons voulu la même bouteille un soir d'octobre.", "전적으로 사실이에요, 선생님. 앙투안과 저는 10월 어느 저녁 같은 병을 원했거든요."),
(K, "Et lequel de vous deux l'a emportée ?", "그래서 둘 중 누가 가져갔나요?"),
(A, "Aucun. Nous l'avons bue ensemble.", "아무도요. 함께 마셨어요."),
(K, "Alors c'est une très bonne histoire. Je prends deux bouteilles.", "그럼 아주 좋은 이야기군요. 두 병 주세요."),
(None, "La cave se remplit peu à peu. Antoine sert un verre de blanc au jeune couple de Japonais, qui parle un français hésitant.", "가게가 차츰 찬다. 앙투안이 일본인 젊은 부부에게 화이트 한 잔을 따른다. 부부는 더듬거리는 프랑스어로 말한다."),
(E, "Bonjour... Nous sommes en voyage de noces. Nous cherchons un vin pour le dîner.", "안녕하세요... 저희는 신혼여행 중이에요. 저녁에 마실 와인을 찾고 있어요."),
(A, "Félicitations ! Vous aimez le vin rouge ou le vin blanc ?", "축하해요! 레드 와인이 좋으세요, 화이트가 좋으세요?"),
(N, "Nous aimons les deux. Mais ce soir, quelque chose de romantique.", "둘 다 좋아해요. 하지만 오늘 밤은 로맨틱한 걸로요."),
(A, "Alors je vous conseille un Bourgueil. Rond, tendre, avec de la douceur. Il se boit comme une promesse.", "그럼 부르괴유를 추천합니다. 둥글고 부드럽고 달콤함이 있어요. 약속처럼 마시죠."),
(E, "Une promesse ? C'est poétique.", "약속이요? 시적이네요."),
(A, "On dit ça, ici, quand le vin est bon.", "여기선 와인이 좋을 때 그렇게 말해요."),
(L, "(s'approche) Et pour le dîner, je vous recommande le petit restaurant de monsieur Tran, juste en face. Dites-lui que vous venez de notre part.", "(다가와) 저녁 식사는 바로 맞은편 트란 씨의 작은 식당을 추천해요. 우리 소개로 왔다고 하세요."),
(N, "Merci beaucoup ! Vous êtes très gentils.", "정말 고맙습니다! 정말 친절하시네요."),
(None, "On sonne encore à la porte. Une femme d'une quarantaine d'années, tailleur gris, appareil photo en bandoulière, un carnet à la main.", "또 문의 종이 울린다. 회색 투피스에 카메라를 어깨에 메고 수첩을 든 사십 대 여성이다."),
(F, "Bonjour. Isabelle Garnier, journaliste à La Gazette du Dix-Huitième. J'ai rendez-vous avec les nouveaux propriétaires.", "안녕하세요. 이자벨 가르니에, 〈18구 신문〉 기자입니다. 새 주인들과 약속이 있어요."),
(L, "C'est moi, madame Garnier. Entrez. Voici Antoine Delcourt, mon associé.", "저예요, 가르니에 부인. 들어오세요. 제 동업자 앙투안 델쿠르예요."),
(F, "Enchantée. Vous pouvez me raconter la genèse du projet ? J'ai lu que vous vous étiez rencontrés ici même.", "반갑습니다. 프로젝트의 시초를 들려주실 수 있나요? 두 분이 바로 이곳에서 만났다고 읽었어요."),
(L, "En effet. C'était un soir d'octobre, devant la dernière bouteille de Morgon de la cave.", "맞아요. 10월 어느 저녁, 가게의 마지막 모르공 병 앞에서였죠."),
(A, "Nous nous sommes disputés poliment, puis nous nous sommes aimés bruyamment.", "정중하게 다투다가 요란하게 사랑하게 됐어요."),
(F, "(écrit) « Disputés poliment, aimés bruyamment. » Je vais garder la formule.", "(쓰며) '정중하게 다투고 요란하게 사랑하다.' 이 표현 기억해 둘게요."),
(L, "Antoine, tu me fais passer pour une personne bruyante.", "앙투안, 날 시끄러운 사람으로 만드네요."),
(A, "Je parlais de moi.", "나 자신 얘기였어요."),
(F, "Et comment ont réagi les anciens clients à l'annonce du changement de propriétaires ?", "그럼 이전 단골들은 주인이 바뀐다는 소식에 어떻게 반응했나요?"),
(G, "(de loin, avec un sourire) Ils ont d'abord pleuré, puis ils ont goûté, et maintenant ils réclament leur rond de table.", "(멀리서 미소 지으며) 처음엔 울다가 맛을 보고 지금은 자기 자리를 달라고 하죠."),
(F, "Monsieur Roussel, pourriez-vous nous dire en quelques mots ce qui fait, selon vous, l'âme d'une cave ?", "루셀 씨, 한마디로 가게의 영혼이 무엇이라고 보십니까?"),
(G, "L'âme d'une cave ? C'est qu'on y entre pour acheter une bouteille et qu'on en ressort avec une histoire.", "가게의 영혼이요? 병 하나 사러 들어가서 이야기 하나를 안고 나오는 것이오."),
(F, "(sourit) Je mettrai ça en gros titre.", "(미소 지으며) 그걸 큰 제목으로 쓰겠어요."),
(None, "Midi. Margaux entre, essoufflée, brandissant une enveloppe. Julien, qui s'est improvisé caissier, la salue d'un geste.", "정오. 마르고가 숨을 헐떡이며 봉투를 흔들면서 들어온다. 즉석 계산원이 된 줄리앙이 손짓으로 인사한다."),
(M, "Voilà le Kbis, tout neuf, avec vos deux noms dessus. Vous êtes officiellement une entreprise.", "새 사업자 등록 증명서예요. 두 분 이름이 찍혀 있죠. 이제 공식적으로 회사예요."),
(L, "(prend le papier, le lit lentement) « Léa Fontaine et Antoine Delcourt, cogérants. » C'est étrange de se voir écrit.", "(서류를 받아 천천히 읽으며) '레아 퐁텐과 앙투안 델쿠르, 공동 대표.' 우리 이름을 쓰인 걸 보는 게 이상하네요."),
(A, "C'est surtout étrange de se voir cogérants. Je pensais être un homme de chiffres et de cartes.", "공동 대표라는 게 특히 이상해요. 난 숫자와 지도의 사람이라고 생각했거든요."),
(M, "Les cartes de vin sont des cartes aussi.", "와인 리스트도 지도죠."),
(JU, "(à la caisse) Un client vient de me demander si on faisait des remises pour les étudiants. Que dois-je répondre ?", "(계산대에서) 방금 손님이 학생 할인이 있냐고 물었어요. 뭐라고 답할까요?"),
(L, "Dix pour cent sur présentation de la carte, le mardi.", "카드를 제시하면 화요일에 10퍼센트요."),
(JU, "Et si c'est un étudiant en œnologie ?", "와인학 전공생이면요?"),
(L, "Quinze pour cent, à condition qu'il explique son vin au client suivant.", "다음 손님에게 와인을 설명해 준다는 조건으로 15퍼센트요."),
(JU, "Tu es une redoutable gestionnaire.", "넌 무서운 경영자야."),
(L, "Je suis une apprentie qui improvise avec méthode.", "방법을 갖고 즉흥하는 견습생이에요."),
(None, "Une femme en tailleur beige se plaint à voix haute devant un étalage, une bouteille à la main.", "베이지색 투피스를 입은 여자가 진열대 앞에서 병을 든 채 큰 소리로 불평한다."),
(CL, "(furieuse, de loin) Monsieur, ce vin est bouchonné ! Je le sens d'ici !", "(멀리서 화를 내며) 선생님, 이 와인은 코르크 냄새가 나요! 여기서도 느껴져요!"),
(A, "(vient poliment) Permettez-moi d'y goûter, madame. Je ne voudrais pas vous vendre un défaut.", "(정중하게 다가가) 맛을 봐도 될까요, 부인. 결함 있는 와인을 팔고 싶지 않습니다."),
(CL, "Vous allez voir : il sent le carton mouillé.", "보세요. 젖은 상자 냄새가 나요."),
(A, "(goûte, hoche la tête) Vous avez raison. Il est bouchonné. Je vous le remplace avec mes excuses, et je vous offre un verre.", "(맛보고 고개를 끄덕이며) 맞습니다. 코르크 냄새가 나네요. 사과드리며 교환해 드리고 한 잔 대접하겠습니다."),
(CL, "(s'adoucit) C'est beaucoup plus que ce que j'espérais.", "(누그러지며) 기대한 것보다 훨씬 많군요."),
(A, "Dans une cave, la réclamation est un cadeau. Elle nous apprend à mieux servir.", "가게에서 항의는 선물이에요. 더 잘 대접하는 법을 알려 주니까요."),
(JU, "(à Léa, bas) Il faut que je te dise : j'ai déjà vendu quarante-deux bouteilles. Je commence à me prendre pour un marchand.", "(레아에게 작게) 말해 줄 게 있어. 벌써 마흔두 병을 팔았어. 내가 상인인 줄 알기 시작했어."),
(L, "Garde ça pour la caisse. Pour le reste, tu es un professeur, et tu le resteras.", "그건 계산대에서만 간직해. 나머지에서는 넌 교사고, 앞으로도 교사일 거야."),
(None, "Les heures s'écoulent. Le magasin ne désemplit pas. Léa et Antoine, un tablier bleu autour de la taille, ne s'arrêtent presque plus. Vers dix-sept heures, une camionnette se gare devant la porte.", "시간이 흐른다. 가게는 줄곧 붐빈다. 파란 앞치마를 두른 레아와 앙투안은 거의 쉬지 못한다. 오후 5시쯤 승합차가 문 앞에 선다."),
(J, "(entre, une caisse dans les bras) Me voici, avec ma femme et mes vieilles bouteilles !", "(상자를 안고 들어오며) 접니다, 아내와 오래된 병들을 데리고요!"),
(V, "Bonsoir à tous. Didier a insisté pour qu'on parte à l'aube. Nous avons fait la route en écoutant France Musique.", "다들 안녕하세요. 디디에가 새벽에 출발하자고 고집했어요. 프랑스 뮈지크를 들으며 달려왔죠."),
(L, "Madame Marchais, enchantée ! Je suis Léa.", "마르셰 부인, 반가워요! 레아예요."),
(V, "Didier m'a beaucoup parlé de vous. Il dit que vous avez le palais d'une vieille âme.", "디디에가 말씀 많이 했어요. 당신에게 늙은 영혼의 미각이 있다고 하더군요."),
(L, "Je ne sais pas si c'est un compliment.", "칭찬인지 모르겠어요."),
(J, "C'en est un, croyez-moi. Dans notre langage, « vieille âme » veut dire qu'on comprend le temps.", "칭찬 맞아요, 믿어요. 우리 말로 '늙은 영혼'은 시간을 이해한다는 뜻이거든요."),
(None, "Didier pose la caisse sur le zinc, en sort deux bouteilles poussiéreuses, étiquette jaunie : « Bourgueil 1990 — Domaine Marchais ».", "디디에가 카운터에 상자를 올려놓고 먼지 쌓인 병 두 개를 꺼낸다. 누렇게 바랜 라벨에 '부르괴유 1990 — 마르셰 도멘'이라 쓰여 있다."),
(J, "Voici mes deux dernières bouteilles de quatre-vingt-dix. Gaston, je pense que ce soir est l'occasion.", "1990년의 마지막 두 병이에요. 가스통, 오늘 밤이 그 기회라고 생각해요."),
(G, "(prend une bouteille avec révérence) Didier. Elle est intacte ?", "(경건하게 병을 들며) 디디에. 온전한가?"),
(J, "Bouchon impeccable, niveau haut. Je les ai gardées à quatorze degrés depuis trente-cinq ans.", "마개 완벽, 용량 높음. 35년 동안 14도로 보관했어요."),
(A, "Quatorze degrés constants ? Vous êtes un obsessionnel.", "14도 일정하게요? 강박증이시네요."),
(J, "C'est l'un des deux ingrédients du bon vin : l'obsession et la patience.", "좋은 와인의 두 재료 중 하나가 강박과 인내죠."),
(L, "Et l'autre ?", "다른 하나는요?"),
(J, "L'amour du raisin. Mais ça, on ne peut pas le conserver à quatorze degrés. Il vous brûle toute l'année.", "포도에 대한 사랑이죠. 하지만 그건 14도로 보관할 수 없어요. 일 년 내내 타오르거든요."),
(None, "Antoine ouvre la première bouteille avec un tire-bouchon à deux lames. Le bouchon vient, intact, sans résistance. Il verse un fond de vin dans un verre : une robe rubis légèrement tuilée.", "앙투안이 양날 코르크 따개로 첫 병을 연다. 마개가 저항 없이 온전하게 올라온다. 잔에 소량 따르자 약간 벽돌빛이 도는 루비색이 나타난다."),
(A, "(sent le verre, ferme les yeux) Du cuir, de la truffe, de la mûre sèche... C'est stupéfiant.", "(잔의 향을 맡고 눈을 감으며) 가죽, 송로, 말린 블랙베리... 놀랍네요."),
(G, "Donne-moi ce verre.", "그 잔을 줘."),
(None, "Gaston respire longuement, boit une gorgée, puis ferme les yeux. Un long silence dans la cave.", "가스통이 길게 숨을 쉬고 한 모금 마시고 눈을 감는다. 가게에 긴 침묵이 흐른다."),
(G, "Voilà... C'est le goût de mon premier jour. La même terre, la même pluie, la même année.", "이거야... 내 첫날의 맛이야. 같은 땅, 같은 비, 같은 해."),
(L, "(à voix basse, à Antoine) On devrait lui dire merci en le laissant seul avec ce verre.", "(앙투안에게 작게) 이 잔과 함께 혼자 있게 두는 걸로 감사를 표해야 할 것 같아요."),
(A, "(à voix basse) Dans une minute. Il faut qu'il finisse sa phrase.", "(작게) 일 분만요. 문장을 끝내야 하니까요."),
(G, "(ouvre les yeux) Mes enfants. Cette cave a trente-cinq ans, et elle vient de renaître. Je suis le seul à pouvoir en témoigner.", "(눈을 뜨며) 얘들아. 이 가게는 서른다섯 살이고 방금 다시 태어났어. 증언할 수 있는 건 나뿐이야."),
(Q, "(à voix haute) Alors témoignez, Gaston ! Nous sommes tous là pour entendre.", "(큰 소리로) 그럼 증언해 주세요, 가스통! 우리 모두 듣고 있어요."),
(G, "Je témoigne que le vin était meilleur que prévu, et que la cave est plus belle que je ne l'espérais.", "와인이 예상보다 좋았고 가게가 바랐던 것보다 아름답다는 걸 증언하겠소."),
(None, "Rires et applaudissements. On fait circuler la bouteille. Chacun reçoit un fond de verre, une gorgée d'histoire. La nuit tombe doucement sur la rue des Abbesses.", "웃음과 박수. 병이 돌아간다. 모두 잔 바닥을 받는다. 역사의 한 모금이다. 아베스 거리에 밤이 부드럽게 내린다."),
(L, "(à Antoine) Regarde-les tous. Ce sont des gens qui boivent du vin en pensant à autre chose. C'est ça, une cave réussie.", "(앙투안에게) 다들 봐요. 다른 생각을 하며 와인을 마시는 사람들이에요. 그게 성공한 가게죠."),
(A, "À quoi tu penses, toi, en ce moment ?", "당신은 지금 무슨 생각을 해요?"),
(L, "À ce que serait cette soirée si on avait cédé la bouteille de Morgon, il y a un an.", "일 년 전 우리가 모르공 병을 양보했다면 오늘 저녁이 어땠을지요."),
(A, "On ne l'aurait pas bue, on n'aurait pas parlé, on ne serait pas là.", "마시지 못했을 테고 말도 못 했을 테고 여기 없었겠죠."),
(L, "Alors merci à notre entêtement.", "그럼 우리의 고집에 감사해요."),
(A, "Il faudra l'ériger en vertu. Tous nos enfants devront l'avoir.", "그걸 미덕으로 삼아야겠어요. 우리 아이들 모두 그걸 가져야 해요."),
(L, "(le regarde, étonnée) Nos enfants ?", "(놀라서 그를 보며) 우리 아이들이요?"),
(A, "(rougit) C'était une façon de parler.", "(얼굴을 붉히며) 말이 그렇다는 거예요."),
(L, "(sourit, lui prend la main) Dis-moi plutôt si c'était une façon de dire.", "(미소 지으며 그의 손을 잡고) 말이 그렇다는 건지 말하려던 건지 말해 봐요."),
(A, "(un temps) Je te le dirai demain. Après la fermeture.", "(잠시 뒤) 내일 말할게요. 문을 닫은 뒤에."),
(None, "La clochette tinte. Une nouvelle cliente entre. Léa lâche doucement la main d'Antoine et se tourne vers la porte, le sourire aux lèvres.", "방울이 울린다. 새 손님이 들어온다. 레아가 앙투안의 손을 가만히 놓고 입가에 미소를 띤 채 문 쪽으로 돌아선다."),
(L, "Bonsoir ! Soyez la bienvenue à La Cave des Abbesses.", "안녕하세요! 라 카브 데 자베스에 오신 것을 환영합니다."),
]
VOCAB = [
("A2","ouvert / fermé / une pancarte","열린 / 닫힌 / 팻말","개점 장면의 기본 어휘"),
("A2","bienvenue / soyez les bienvenus","환영 / 환영합니다","환영 인사"),
("A2","un petit déjeuner / une baguette / une confiture","아침 식사 / 바게트 / 잼","가스통의 선물"),
("A2","un voyage de noces","신혼여행","일본인 부부의 소개"),
("B1","la clochette / tinter","작은 방울 / 울리다","« Elle tinte. »"),
("B1","une casquette / un facteur","모자 / 우체부","르브룅의 외양"),
("B1","la genèse du projet","프로젝트의 시초","기자의 질문"),
("B1","une journaliste / un gros titre","기자 / 큰 제목","« Je mettrai ça en gros titre. »"),
("B1","conseiller / recommander","조언하다 / 추천하다","접객 어휘"),
("B2","avoir l'estomac noué","속이 막히다(긴장하다)","« Tout le monde a l'estomac noué. »"),
("B2","réclamer son rond de table","자기 자리를 요구하다","단골의 지정석을 뜻하는 관용구"),
("B2","un tire-bouchon à deux lames","양날 코르크 따개","와인 도구"),
("B2","une robe rubis tuilée","벽돌빛이 도는 루비색","숙성 와인 색 표현"),
("B2","du cuir, de la truffe, de la mûre sèche","가죽, 송로, 말린 블랙베리","숙성 향"),
("B2","pardonner / se faire pardonner","용서하다 / 용서를 구하다","르브룅의 표현"),
("B2","stupéfiant / impeccable / intact","놀라운 / 흠잡을 데 없는 / 온전한","형용사 모음"),
("B2","un obsessionnel","강박증 환자","익살스러운 표현"),
("C1","je suis là à l'heure d'un autre temps","나는 다른 시간의 정시에 온다","가스통의 말놀이"),
("C1","se disputer poliment, s'aimer bruyamment","정중히 다투고 요란히 사랑하다","대구와 부사 대비"),
("C1","l'âme d'une cave","가게의 영혼","« on y entre pour acheter une bouteille et on en ressort avec une histoire »"),
("C1","une vieille âme","늙은 영혼","시간을 이해하는 사람"),
("C1","ériger en vertu","미덕으로 삼다","ériger = 세우다"),
("C1","témoigner","증언하다","가스통의 마지막 증언"),
("C1","une façon de parler / une façon de dire","말버릇 / 하고 싶은 말","레아의 미묘한 되받음"),
]
GRAM = [
("A2","환영 인사: Soyez les bienvenus / Bienvenue",
 "« Soyez les bienvenus à La Cave des Abbesses. » être의 명령형 soyez + bienvenu(e)(s). 일상에서는 간단히 Bienvenue !"),
("B1","전치사 chez / depuis / il y a",
 "« Il y a trente-cinq ans, j'ai été le premier client. » il y a + 기간 = ~전에. « depuis 1990 » 간판: 1990년부터 지속."),
("B1","재귀 대명사 동사의 복합과거: nous nous sommes disputés",
 "« Nous nous sommes disputés poliment, puis nous nous sommes aimés bruyamment. » 재귀동사 복합과거는 être + 과거분사, 직접목적어가 주어와 같으면 성수 일치."),
("B2","가정: si on avait cédé… on ne l'aurait pas bue",
 "« Si on avait cédé la bouteille… on ne l'aurait pas bue. » si + 대과거 → 조건법 과거. 과거에 일어나지 않은 일의 가정."),
("B2","접속법: il faut que / insister pour que",
 "« Il faut qu'il finisse sa phrase. » « Didier a insisté pour qu'on parte à l'aube. » il faut que, insister pour que + 접속법."),
("B2","의문 대명사: lequel de vous deux",
 "« Lequel de vous deux l'a emportée ? » lequel/laquelle/lesquels/lesquelles = 둘 이상 중 어느 것(누구). 전치사와 결합하면 auquel, duquel 등으로 변한다."),
("C1","완곡한 되받음: Dis-moi plutôt si c'était une façon de dire",
 "« C'était une façon de parler. » / « Dis-moi plutôt si c'était une façon de dire. » une façon de parler = 말이 그렇다는 것, une façon de dire = 진심을 담은 표현. 의미를 비트는 미묘한 대화."),
("C1","역설적 정의: on y entre pour… et on en ressort avec…",
 "« On y entre pour acheter une bouteille et on en ressort avec une histoire. » y/en 대명사 대구. 대비를 통해 장소의 정체성을 정의하는 격언체."),
]
CULTURE = [
("가게 문의 방울(clochette)과 개점 의례",
 "작은 가게의 문 방울은 손님의 입장을 알리는 오래된 장치이다. 가스통이 방울을 다시 다는 것은 가게의 기억과 정체성을 새 주인에게 넘기는 상징적인 의례이다."),
("프랑스의 지역 신문과 소상인",
 "프랑스에서는 〈La Gazette〉 같은 지역 신문이 새 가게의 개점을 크게 다룬다. 기자는 가게의 역사와 인물을 소개해 지역 공동체의 일원으로 인정하는 역할을 한다."),
("숙성 와인의 서빙",
 "30년 이상 된 와인은 코르크가 쉽게 부서지므로 양날 코르크 따개(à lames)를 쓴다. 침전물이 있으면 디캔팅하기도 하지만 오래된 와인은 산소 접촉으로 향이 빨리 사라지므로 즉시 마신다."),
]
META = dict(part=4, ep=47, part_label="제4부 그랑 크뤼 · Grand cru", title_fr="Inauguration", title_ko="개점식",
 place="라 카브 데 자베스, 아베스 거리 · 2월 28일 토요일 오전 9시 30분",
 chars="Léa · Antoine · Gaston · M. Lebrun (첫 손님) · Mme Garnier (기자) · Aya & Kenji (신혼부부) · Didier Marchais · Mme Marchais · Mme Vasseur",
 wine="Morgon · Bourgueil · Bourgueil 1990 (Domaine Marchais)",
 focus="환영 인사, 다인 대화, 인터뷰 구문, 가정(si + 대과거), 말놀이",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제48화 « Une dernière bouteille » : 개점 다음 날 문을 닫은 뒤, 1화의 마지막 모르공 한 병이 되돌아온다. 수미상관의 청혼, 그리고 총정리.")
