# -*- coding: utf-8 -*-
L, A, G, M, J, V, R, T, K = "Léa", "Antoine", "Gaston", "Margaux", "Julien", "Mme Vasseur", "Gérard", "M. Tran", "M. Lebrun"
D = [
(None, "Dimanche 1er mars, 18 h 45. Il a plu toute la journée. La Cave des Abbesses ferme dans trois quarts d'heure, et pour la première fois depuis l'ouverture, elle est presque vide. Léa est sortie quelques minutes plus tôt, un parapluie à la main, après un coup de téléphone mystérieux de Gaston : « Passe à la boulangerie, j'ai oublié le pain. » Antoine, seul derrière le zinc, fait semblant de ranger des verres. Sur l'étagère du bas, une unique bouteille de Morgon.", "3월 1일 일요일 오후 6시 45분. 하루 종일 비가 왔다. 라 카브 데 자베스는 45분 뒤에 문을 닫고 개점 이후 처음으로 거의 비어 있다. 레아는 가스통의 수상한 전화 '빵집에 들러 줘, 빵을 깜빡했어' 뒤 몇 분 전에 우산을 들고 나갔다. 앙투안은 카운터 뒤에서 혼자 잔을 정리하는 척한다. 아래 선반에는 모르공 한 병이 놓여 있다."),
(A, "(pour lui-même) Allez, Antoine. Respire. Tu as fait des cours devant trente élèves de terminale. Tu peux parler devant une bouteille.", "(혼잣말로) 자, 앙투안. 숨 쉬어. 고3 서른 명 앞에서 수업도 했잖아. 병 앞에서 말하는 건 할 수 있어."),
(G, "(sort de l'arrière-boutique en chaussons, un tablier sur les épaules) Tu parles à la bouteille ou à toi-même ?", "(슬리퍼 차림으로 앞치마를 어깨에 걸치고 안쪽 창고에서 나오며) 병한테 말하는 거냐, 자기한테 말하는 거냐?"),
(A, "Gaston ! Vous m'avez fait peur. Vous n'étiez pas censé être là avant dix-huit heures cinquante.", "가스통! 놀랐어요. 18시 50분 전엔 계시면 안 되잖아요."),
(G, "Je suis un homme ponctuel. J'arrive toujours cinq minutes avant le début d'une scène.", "난 시간을 지키는 사람이야. 장면이 시작되기 5분 전에 항상 도착하지."),
(A, "Vous avez bien préparé la scène ?", "장면 준비는 잘 하셨어요?"),
(G, "J'ai appelé Léa pour l'éloigner du magasin. J'ai bloqué le trottoir devant la boulangerie avec un faux livreur. J'ai mis le jazz en sourdine. Je crois que j'ai oublié de mettre mon chapeau.", "레아를 가게에서 떼어 놓으려고 전화했지. 빵집 앞 보도를 가짜 배달부로 막아 놨고 재즈를 작게 틀었어. 모자를 안 썼다는 걸 이제 깨달았네."),
(A, "Elle va se douter de quelque chose.", "눈치채겠어요."),
(G, "Elle se doute de tout depuis toujours. C'est ce qui fait son charme. Mais ce soir, elle fera semblant de ne se douter de rien.", "그 아이는 늘 모든 걸 눈치채지. 그게 매력이야. 하지만 오늘 밤엔 아무것도 모르는 척할 거야."),
(A, "(sort de sa poche un petit écrin de velours bleu, puis le range) Je me demande si elle va dire oui.", "(주머니에서 푸른 벨벳 반지 케이스를 꺼냈다가 다시 넣으며) 그녀가 좋다고 할까요."),
(G, "Petit, je te le dis comme je dirais à mon fils, si j'en avais un : on ne demande jamais à une femme intelligente de dire oui. On lui offre la possibilité de le dire.", "얘야, 아들이 있었다면 해 줬을 말이야. 똑똑한 여자에게 좋다고 말해 달라고 요구하는 게 아니야. 말할 수 있는 가능성을 주는 거지."),
(A, "C'est la plus belle phrase que vous m'ayez dite.", "지금까지 해 주신 말씀 중 가장 아름다운 문장이에요."),
(G, "Je les garde pour les grandes occasions. Allons, assieds-toi, tiens-toi droit, et prends l'air d'un homme qui range tranquillement ses étagères.", "큰 날을 위해 아껴 두는 문장이지. 자, 앉아서 허리 펴고 평온하게 선반을 정리하는 사람 같은 표정을 지어."),
(None, "Gaston s'éclipse derrière le rideau de l'arrière-boutique. Antoine saisit un torchon et frotte vigoureusement un comptoir déjà immaculé. La clochette tinte. Léa entre, un sac de papier à la main, trempée jusqu'aux cheveux.", "가스통이 안쪽 창고 커튼 뒤로 사라진다. 앙투안이 행주를 잡고 이미 깨끗한 카운터를 열심히 닦는다. 방울이 울린다. 레아가 종이봉투를 들고 머리까지 흠뻑 젖어 들어온다."),
(L, "Bonsoir ! Il pleut depuis ce matin, c'est insupportable.", "안녕! 아침부터 비가 와서 견딜 수가 없어."),
(A, "(surpris par cette phrase, il sourit) Ah, c'est Paris en mars !", "(그 문장에 놀라 미소 지으며) 아, 3월의 파리죠!"),
(L, "(s'arrête, le regarde) Antoine, tu viens de dire exactement la phrase de Gaston, le premier soir.", "(멈춰서 그를 보며) 앙투안, 방금 첫날 저녁 가스통의 문장을 그대로 말했어요."),
(A, "Vraiment ? Je n'avais pas fait attention.", "정말요? 의식하지 못했어요."),
(L, "(pose le sac, plisse les yeux) Tu mens très mal.", "(봉투를 내려놓고 눈을 가늘게 뜨며) 거짓말이 정말 서툴러요."),
(A, "J'ai appris à mentir devant des classes de lycéens ; ça ne marche pas avec les femmes qui ont des yeux.", "고등학생 반 앞에서 거짓말을 배웠는데 눈이 있는 여자한테는 안 통해요."),
(L, "Qu'est-ce que vous manigancez, Gaston et toi ?", "당신과 가스통이 뭘 꾸미고 있어요?"),
(A, "Rien du tout. Je range les verres. Tu vois ? (Il lève un verre.)", "아무것도 없어요. 잔을 정리하고 있죠. 보여요? (잔을 든다)"),
(L, "Antoine, le verre est à l'envers.", "앙투안, 잔이 거꾸로예요."),
(A, "(le retourne, rougit) Mince.", "(돌려놓고 얼굴을 붉히며) 이런."),
(L, "(se détend, rit) D'accord. Je fais semblant de ne rien voir. Dis-moi plutôt ce qu'on a vendu aujourd'hui.", "(긴장을 풀고 웃으며) 좋아요. 아무것도 못 본 척해 줄게요. 오늘 뭘 팔았는지나 말해 줘요."),
(A, "Vingt-trois bouteilles. Beaucoup de Bourgueil. Et un client qui a posé trente-sept questions sur les sulfites.", "스물세 병. 부르괴유가 많았고 아황산염에 서른일곱 가지 질문을 한 손님이 있었어요."),
(L, "Tu as répondu à toutes ?", "전부 대답했어요?"),
(A, "À trente-six. La trente-septième, c'était : « Pourquoi y a-t-il des questions ? »", "서른여섯 개요. 서른일곱 번째는 '왜 질문이 존재하죠?'였어요."),
(L, "Cet homme a l'étoffe d'un philosophe.", "철학자의 소질이 있는 사람이네요."),
(None, "Léa s'approche de l'étagère du bas pour y déposer un carton, puis s'arrête net. Elle vient de voir la bouteille. Son visage change.", "레아가 상자를 놓으려고 아래 선반에 다가갔다가 딱 멈춘다. 병을 본 것이다. 표정이 바뀐다."),
(L, "(lentement) C'est un Morgon.", "(천천히) 모르공이네요."),
(A, "Oui.", "네."),
(L, "Le dernier de l'étagère.", "선반의 마지막 병이에요."),
(A, "Il semblerait.", "그런 것 같아요."),
(L, "(se tourne vers lui, les yeux brillants) Antoine Delcourt. Tu as monté tout ça ?", "(그를 향해 돌아서며 눈이 반짝인다) 앙투안 델쿠르. 이걸 다 꾸민 거예요?"),
(A, "J'avoue tout. Avec la complicité d'un vieux marchand de vin.", "다 실토할게요. 늙은 와인 상인의 공모로요."),
(G, "(de derrière le rideau, d'une voix étouffée) Je n'ai rien dit !", "(커튼 뒤에서 낮은 목소리로) 난 아무 말도 안 했어!"),
(L, "(rit) Gaston, vous pouvez sortir. Vous respirez trop fort.", "(웃으며) 가스통, 나오셔도 돼요. 숨소리가 너무 커요."),
(G, "(apparaît, penaud) Je respire à mon âge. C'est un acte de bravoure.", "(머쓱하게 나타나며) 이 나이에 숨 쉬는 건 용기 있는 행동이야."),
(A, "(à Gaston) Merci, mais laissez-nous un moment.", "(가스통에게) 고맙지만 잠시만 둘이 있게 해 주세요."),
(G, "Je ne bouge pas. J'ai trente-cinq ans de métier ; je sais disparaître sans quitter la pièce.", "움직이지 않을 거야. 삼십오 년 일했으니 방을 나가지 않고도 사라질 줄 알아."),
(None, "Il se glisse derrière le comptoir, s'assoit sur son vieux tabouret, et prend un air absorbé par la contemplation de l'étagère de rouges. Léa et Antoine échangent un sourire.", "그가 카운터 뒤로 미끄러져 들어가 낡은 의자에 앉아 붉은 와인 선반을 응시하는 데 몰두한 표정을 짓는다. 레아와 앙투안이 미소를 나눈다."),
(L, "Bon. Revenons à notre bouteille.", "자. 우리 병으로 돌아가요."),
(A, "Revenons-y.", "돌아가죠."),
(L, "(tend la main vers le Morgon) Je la prends.", "(모르공을 향해 손을 뻗으며) 내가 가질게요."),
(A, "(tend la main au même instant) Oh, pardon ! Excusez-moi, je ne vous avais pas vue.", "(같은 순간 손을 뻗으며) 아, 죄송합니다! 실례했어요, 못 봤네요."),
(None, "Leurs mains se rencontrent autour du goulot. Un long moment, ni l'un ni l'autre ne bouge. Entre leurs doigts, la bouteille semble suspendue dans l'air.", "두 손이 병목 둘레에서 만난다. 오래도록 누구도 움직이지 않는다. 손가락 사이에서 병이 공중에 걸린 듯하다."),
(L, "Vous vouliez cette bouteille, vous aussi ?", "당신도 이 병을 원했나요?"),
(A, "Eh bien... oui. C'est la dernière, n'est-ce pas ?", "글쎄요... 네. 마지막 병이죠?"),
(L, "C'est la dernière. Alors qui la prend ?", "마지막 병이에요. 그럼 누가 가질까요?"),
(A, "Je ne sais pas. Je viens chercher mon Morgon du vendredi. Comme d'habitude.", "모르겠어요. 금요일 모르공을 가지러 왔죠. 평소처럼."),
(L, "Mais on est dimanche.", "근데 일요일이에요."),
(A, "Alors c'est mon Morgon du dimanche.", "그럼 일요일의 모르공이죠."),
(L, "Vous n'avez pas honte de tricher sur le calendrier ?", "달력을 속이는 게 부끄럽지 않으세요?"),
(A, "Pas du tout. Dans cette cave, on triche volontiers avec le temps. Gaston m'a appris.", "전혀요. 이 가게에서는 기꺼이 시간을 속이죠. 가스통이 가르쳐 줬어요."),
(L, "(rit) Vous êtes impossible.", "(웃으며) 정말 못 말려요."),
(A, "Vous aussi.", "당신도요."),
(L, "J'en ai vraiment besoin ce soir, pourtant.", "그래도 오늘 밤엔 정말 필요한데요."),
(A, "Pourquoi ? Une pendaison de crémaillère ?", "왜요? 집들이라도 있나요?"),
(L, "Non. Un événement beaucoup plus important.", "아니요. 훨씬 중요한 일이에요."),
(A, "(sa voix tremble un peu) Quel événement ?", "(목소리가 살짝 떨리며) 어떤 일인데요?"),
(L, "Je ne sais pas encore. Mon associé m'a dit qu'il avait quelque chose à me demander. Il ne me l'a pas dit, mais je le sais.", "아직 모르겠어요. 동업자가 내게 물어볼 게 있다고 했는데 말은 안 했지만 알아요."),
(A, "(retire sa main du goulot, la glisse dans sa poche) Léa...", "(병목에서 손을 빼 주머니에 넣으며) 레아..."),
(L, "Oui ?", "네?"),
(A, "Je vais te lire quelque chose. Je l'ai écrit sur une fiche de cours, parce que sinon, je perds mes moyens.", "읽어 줄 게 있어요. 안 그러면 당황하니까 수업 카드에 써 뒀어요."),
(L, "Tu as écrit sur une fiche de cours ?", "수업 카드에 썼다고요?"),
(A, "(sort une fiche bristol, la déplie) Ne te moque pas.", "(두꺼운 카드를 꺼내 펼치며) 놀리지 말아요."),
(L, "Je ne me moque pas. J'ai les yeux qui brillent. C'est différent.", "놀리지 않아요. 눈이 반짝이는 거예요. 달라요."),
(A, "(lit, la voix un peu rauque) « Léa. Il y a un an, nous voulions la même bouteille. Nous l'avons partagée. Depuis, nous avons tout partagé : des soirées, des silences, des vins, des peurs, des rêves, une cave. »", "(약간 쉰 목소리로 읽는다) '레아. 일 년 전 우리는 같은 병을 원했습니다. 우리는 그것을 나눠 마셨죠. 그 뒤로 우리는 모든 것을 나눴어요. 저녁, 침묵, 와인, 두려움, 꿈, 그리고 가게까지.'"),
(L, "(à voix basse) Antoine...", "(낮은 목소리로) 앙투안..."),
(A, "« Je ne sais pas ce que l'avenir réserve. Je sais seulement qu'il y a des vins qu'on garde pour des jours qu'on n'a pas encore vécus. Toi, tu es mon vin de garde. »", "'미래가 무엇을 가져올지 모릅니다. 아직 살지 않은 날을 위해 보관하는 와인이 있다는 것만 알아요. 당신은 나의 보관용 와인입니다.'"),
(L, "(ravale un sanglot) Continue.", "(울음을 삼키며) 계속해요."),
(A, "« Alors voici ma question. Veux-tu que nous continuions à tout partager, jusqu'à la dernière bouteille ? »", "'그래서 질문이 있습니다. 마지막 병까지 계속 모든 것을 나누지 않겠어요?'"),
(None, "Il replie la fiche, la pose sur le comptoir. Puis il saisit la bouteille de Morgon : à son goulot, un ruban de soie bleue tient une bague discrète, un fin anneau d'or avec un petit saphir.", "그가 카드를 접어 카운터에 놓는다. 이어 모르공 병을 잡는다. 병목에는 푸른 비단 리본이 작은 사파이어가 박힌 가는 금반지를 묶고 있다."),
(L, "(porte la main à la bouche) Antoine... la bague est sur la bouteille.", "(손으로 입을 가리며) 앙투안... 반지가 병에 달려 있어요."),
(A, "Madame Vasseur m'a raconté l'histoire de son mari et du Sauternes vide. J'ai trouvé l'idée délicieuse. Mais il me fallait un vin plein. Un vin qu'on boit ensuite.", "바세르 부인이 남편과 빈 소테른 병 이야기를 들려줬어요. 아주 멋진 생각이었죠. 하지만 난 가득 찬 와인이 필요했어요. 나중에 마실 수 있는."),
(L, "(sourit à travers ses larmes) Tu as pensé à tout.", "(눈물 사이로 웃으며) 모든 걸 생각해 뒀네요."),
(A, "Pas à la réponse.", "답은 생각 못 했어요."),
(L, "(prend la bague, la regarde longuement) Tu sais ce que je pensais, quand on s'est connus ?", "(반지를 들고 오래 바라보며) 우리가 만났을 때 내가 뭘 생각했는지 알아요?"),
(A, "Dis-moi.", "말해 봐요."),
(L, "Je pensais : voilà un homme qui n'ose pas prendre la dernière bouteille. Il est donc capable de renoncer à quelque chose qu'il aime. Et un homme capable de renoncer est un homme capable d'aimer.", "이렇게 생각했어요. 마지막 병을 가져가지 못하는 남자가 있구나. 좋아하는 것을 포기할 수 있는 사람이구나. 포기할 수 있는 남자는 사랑할 수 있는 남자라고요."),
(A, "(la gorge nouée) Je ne m'en étais jamais rendu compte.", "(목이 메어) 한 번도 몰랐어요."),
(L, "Moi si. Depuis le début.", "난 알았어요. 처음부터."),
(A, "Alors... ta réponse ?", "그럼... 대답은요?"),
(L, "Antoine Delcourt. Oui. Mille fois oui. Oui jusqu'à la dernière bouteille, et même après.", "앙투안 델쿠르. 네. 천 번이라도 네. 마지막 병까지, 그 뒤에도요."),
(None, "Il lui passe la bague au doigt. Elle lui tombe dans les bras. Dans l'arrière-boutique, un hurlement de joie étouffé : Julien et Margaux, qui se cachaient derrière les caisses, font irruption, suivis de madame Vasseur, de Gérard, de monsieur Tran et même du facteur Lebrun.", "그가 그녀의 손가락에 반지를 끼운다. 그녀가 그의 품에 안긴다. 안쪽 창고에서 억눌린 환호가 터진다. 상자 뒤에 숨어 있던 줄리앙과 마르고가 뛰쳐나오고 바세르 부인, 제라르, 트란 씨, 심지어 우체부 르브룅까지 따라 나온다."),
(J, "Il a dit oui ! Elle a dit oui ! Je gagne le pari !", "그녀가 좋다고 했어! 내가 내기에서 이겼어!"),
(M, "Julien, tu avais parié sur « dix minutes ». Il lui a fallu quinze.", "줄리앙, '십 분'에 걸었잖아. 십오 분 걸렸어."),
(J, "Une marge d'erreur de cinq minutes, c'est largement acceptable pour un historien.", "역사학자라면 오 분 오차는 충분히 허용 범위야."),
(V, "(essuie ses larmes) Mes enfants, mes chers enfants. Je vous ai vus entrer dans cette cave comme deux inconnus, et je vous vois en sortir comme deux fiancés.", "(눈물을 닦으며) 얘들아, 사랑하는 얘들아. 처음에 낯선 두 사람으로 들어오던 걸 봤는데 이제는 약혼자 둘로 나가는 걸 보네."),
(G, "(s'avance, le visage ruisselant mais digne) Mes enfants. J'ai un dernier devoir de patron à accomplir.", "(얼굴은 젖었으나 위엄 있게 다가오며) 얘들아. 주인으로서 마지막 의무가 하나 남았어."),
(L, "Lequel, Gaston ?", "무슨 의무요, 가스통?"),
(G, "Ouvrir cette bouteille. Parce qu'un Morgon qui porte une bague, il ne faut pas le laisser vieillir.", "이 병을 여는 것. 반지를 단 모르공은 늙게 두면 안 되니까."),
(None, "Il prend le tire-bouchon et ouvre la bouteille avec délicatesse. Le bouchon sort avec un « pop » discret. Il verse lentement dans neuf verres. Un rouge profond, aux reflets violets, qui sent la cerise noire et les pivoines.", "그가 코르크 따개를 조심스럽게 들어 병을 연다. 마개가 작은 '퐁' 소리와 함께 나온다. 아홉 잔에 천천히 따른다. 보랏빛이 도는 짙은 붉은색, 검은 체리와 작약의 향이 난다."),
(G, "(il lève son verre) À l'amour, qui est le seul vin que l'on ne boit jamais seul.", "(잔을 들며) 사랑을 위하여. 혼자서는 결코 마시지 않는 유일한 와인."),
(A, "(lève son verre) À Gaston, qui nous a donné la cave, la clochette, et la dernière bouteille.", "(잔을 들며) 가게와 방울과 마지막 병을 우리에게 준 가스통을 위하여."),
(L, "À nos parents, qui nous ont appris à aimer le vin sans savoir qu'ils nous apprenaient à nous aimer.", "와인을 사랑하는 법을 가르치며 우리가 서로 사랑하는 법을 가르친 줄 몰랐던 부모님을 위하여."),
(R, "(ému) À mon fils, et à la fille que je n'avais pas encore.", "(감동하여) 내 아들과 아직 갖지 못했던 딸을 위하여."),
(J, "À moi, qui gagne un pari et gagne une belle-sœur.", "내기에 이기고 형수까지 얻은 나를 위하여."),
(M, "À la rédaction des statuts de mariage. Il y en a un sérieux à prévoir.", "혼인 계약서 작성을 위하여. 진지하게 준비할 게 있어요."),
(V, "À l'amour, qui est toujours le meilleur investissement.", "언제나 최고의 투자인 사랑을 위하여."),
(T, "À la table que j'ai réservée pour le dîner de fiançailles, mercredi, chez moi.", "수요일 우리 식당에서 약혼 저녁 식사를 위해 예약해 둔 식탁을 위하여."),
(K, "Et à la vieille clochette, qui a sonné pour tout ça.", "그리고 이 모든 것을 위해 울린 낡은 방울을 위하여."),
(G, "(la voix brisée, mais souriante) Allons, buvons avant que cette bouteille ne devienne une larme.", "(목이 메었지만 미소 지으며) 자, 이 병이 눈물이 되기 전에 마십시다."),
(None, "Les verres tintent. Dehors, la pluie cesse. Les derniers nuages se déchirent sur la butte Montmartre, et un arc-en-ciel fragile se dessine au-dessus de la rue des Abbesses.", "잔이 부딪친다. 밖에서는 비가 그친다. 마지막 구름이 몽마르트르 언덕 위에서 찢어지고 아베스 거리 위로 연약한 무지개가 그려진다."),
(L, "(à voix basse, à Antoine) Regarde, l'arc-en-ciel.", "(앙투안에게 작게) 봐요, 무지개."),
(A, "(à voix basse) On pourrait croire qu'il est là pour nous.", "(작게) 우리를 위해 나타났다고 믿을 수도 있겠어요."),
(L, "Ne le dis pas à Gaston, il va prétendre l'avoir commandé.", "가스통에게 말하지 마요. 자기가 주문했다고 우길 테니까."),
(G, "(de loin, avec un clin d'œil) Je l'ai entendu. Et je l'ai commandé.", "(멀리서 윙크하며) 들었어. 그리고 내가 주문했어."),
]
VOCAB = [
("A2","fermer / ouvrir / un soir","닫다 / 열다 / 저녁","가게 기본 어휘"),
("A2","la pluie / il pleut","비 / 비가 온다","첫 만남과 같은 날씨"),
("A2","la boulangerie / le pain","빵집 / 빵","레아가 보내진 이유"),
("A2","une bague / un anneau d'or","반지 / 금반지","청혼 소품"),
("B1","manigancer / complicité","꾸미다 / 공모","« Qu'est-ce que vous manigancez ? »"),
("B1","un écrin de velours","벨벳 반지 케이스","« un petit écrin de velours bleu »"),
("B1","se douter de","~을 눈치채다","« Elle se doute de tout. »"),
("B1","un goulot / un ruban de soie","병목 / 비단 리본","청혼 장면의 소품"),
("B1","un pari / parier","내기 / 내기하다","줄리앙의 내기"),
("B2","en sourdine","작게(소리를 낮추어)","« mettre le jazz en sourdine »"),
("B2","penaud","머쓱한","« penaud, il apparaît »"),
("B2","un vin de garde","보관용 와인","« Tu es mon vin de garde. »"),
("B2","perdre ses moyens","당황하다","« sinon, je perds mes moyens »"),
("B2","ravaler un sanglot","울음을 삼키다","감정 묘사"),
("B2","faire irruption","불쑥 나타나다","« font irruption »"),
("B2","un écrin / un saphir","케이스 / 사파이어","반지 묘사"),
("C1","on ne demande jamais à une femme intelligente de dire oui","똑똑한 여자에게 좋다고 말해 달라 요구하지 않는다","가스통의 마지막 지혜"),
("C1","il y a des vins qu'on garde pour des jours qu'on n'a pas encore vécus","아직 살지 않은 날을 위해 보관하는 와인이 있다","청혼문의 핵심"),
("C1","un homme capable de renoncer est capable d'aimer","포기할 수 있는 남자는 사랑할 수 있다","수미상관: 1화의 양보와 연결"),
("C1","un acte de bravoure","용기 있는 행동","익살스러운 과장"),
("C1","une marge d'erreur largement acceptable","충분히 허용되는 오차","줄리앙의 농담"),
("C1","à l'amour, le seul vin que l'on ne boit jamais seul","사랑을 위하여, 혼자 마시지 않는 유일한 와인","마지막 건배사"),
("C1","jusqu'à la dernière bouteille, et même après","마지막 병까지, 그 뒤에도","레아의 대답"),
("C1","faire semblant de","~인 척하다","« Elle fera semblant de ne se douter de rien. »"),
]
GRAM = [
("A2","수미상관: 반복되는 문장 — Il pleut depuis ce matin",
 "1화의 « Il pleut depuis ce matin, c'est insupportable. »를 48화에서 레아가 다시 말한다. depuis + 시점 = ~이래 계속. 같은 문형의 반복이 구조적 호응을 만든다."),
("B1","전치사 jusqu'à / depuis",
 "« jusqu'à la dernière bouteille » 끝 시점까지. « Depuis, nous avons tout partagé. » 그 뒤로. 두 전치사가 이야기의 시작과 끝을 묶는다."),
("B1","직접 목적어 대명사와 부정사: Je le sais / Je ne m'en étais jamais rendu compte",
 "« Il ne me l'a pas dit, mais je le sais. » le가 문장 전체를 대신한다. se rendre compte de → en 대명사로 « Je ne m'en étais pas rendu compte » 대과거."),
("B2","접속법 + 부정 선행사: Il me fallait un vin plein",
 "« Il me fallait un vin plein. Un vin qu'on boit ensuite. » il me faut + 명사. 반과거 il me fallait로 계획의 이유를 설명한다. 관계절 직설법."),
("B2","조건법: Je ne voudrais pas vous la prendre / J'ai trouvé l'idée délicieuse",
 "1화의 « Je ne voudrais pas vous la prendre. »처럼 정중한 조건법. 48화의 청혼은 이를 되울린다."),
("B2","사역 및 인칭 대명사: Il lui passe la bague au doigt",
 "« Il lui passe la bague au doigt. » 신체 부위에는 소유 형용사 대신 정관사를 쓴다: la bague au doigt. 간접 목적어 lui가 소유자를 표시."),
("C1","수사법: 전환적 격언(chiasme)",
 "« Un homme capable de renoncer est un homme capable d'aimer. » 동일 구조의 반복과 은유로 사랑을 정의한다. 가스통의 « On ne demande jamais à une femme intelligente de dire oui. On lui offre la possibilité de le dire. » 도 같은 계열."),
("C1","과거 완료 + 현재 비교: Je ne sais pas ce que l'avenir réserve",
 "« Je ne sais pas ce que l'avenir réserve. Je sais seulement que… » 미지의 가능성에 대한 겸손한 고백. 간접 의문절과 que절의 대비."),
]
CULTURE = [
("프랑스의 청혼 문화",
 "프랑스에서 청혼(demande en mariage)은 반지, 건배, 가족·친구의 몰래 참석 등으로 연출되곤 한다. 보통 사파이어나 다이아몬드 반지를 건네며 Veux-tu m'épouser ?라고 묻는다. 이 에피소드에서는 와인 병을 매개로 한다."),
("수미상관(inclusio)과 프랑스 서사",
 "이야기의 처음과 끝을 같은 장면으로 맺는 구조. 1화 «Une dernière bouteille»의 만남이 48화의 청혼으로 되돌아온다. 같은 대사(« Il pleut depuis ce matin… »)와 동작(두 손이 같은 병으로 향함)이 감정을 증폭시킨다."),
("48화 총정리 — 한 해의 포도주",
 "봄(1부 첫 잔) 두 사람은 모르공 한 병 앞에서 만났고, 여름(2부 여름의 포도)에는 서로를 알아 갔으며, 가을(3부 늦수확)에는 시련을 지났고, 겨울(4부 그랑 크뤼)에는 가게를 물려받아 약혼했다. 가스통은 이야기의 포도밭지기였다."),
]
META = dict(part=4, ep=48, part_label="제4부 그랑 크뤼 · Grand cru", title_fr="Une dernière bouteille", title_ko="마지막 한 병",
 place="라 카브 데 자베스, 아베스 거리 · 3월 1일 일요일 오후 6시 45분",
 chars="Léa · Antoine · Gaston · Margaux · Julien · Mme Vasseur · Gérard · M. Tran · M. Lebrun",
 wine="Morgon (마지막 병) · 반지를 맨 병",
 focus="수미상관, 1화 대사의 반복, 청혼의 수사, 격언과 수사법 총정리",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="완결 · 이야기는 여기서 끝나지만 « La Cave des Abbesses »의 문은 계속 열려 있습니다. 감사합니다 — Merci d'avoir lu !")
