# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, A, M = "Hélène", "Julien", "Me Aubry", "Mme Lemaire"
D = [
(None, "Jeudi 12 novembre, 8 h 50. Tribunal de commerce de Paris, île de la Cité. Dans le hall, Hélène porte son seul blazer. Me Aubry range un dossier. Julien arrive en courant, cravate de travers.", "11월 12일 목요일 오전 8시 50분. 파리 상사법원, 시테섬. 로비에서 엘렌은 하나뿐인 블레이저를 입고 있다. 오브리 변호사가 서류를 정리한다. 줄리앙이 넥타이가 비뚤어진 채 뛰어 들어온다."),
(J, "Pardon, pardon ! Le métro est en panne à Châtelet. Je suis en retard ?", "미안, 미안! 샤틀레에서 지하철이 고장 났어. 나 늦었어?"),
(H, "Non, t'as dix minutes. Mais... tu t'es mis en cravate ?", "아니, 10분 남았어. 근데... 너 넥타이까지 맸어?"),
(J, "C'est un tribunal, Hélène. Je veux pas avoir l'air d'un type qui vient contester une amende.", "법원이잖아, 엘렌. 주차 딱지 이의 신청하러 온 사람처럼 보이긴 싫어."),
(H, "Personne va te regarder, Julien. C'est moi qui passe devant le juge.", "아무도 널 안 봐, 줄리앙. 판사 앞에 서는 건 나야."),
(J, "Justement. Tu trembles. C'est le froid ou la trouille ?", "그러니까 말이야. 너 떨고 있어. 추워서야, 겁나서야?"),
(H, "Les deux. J'ai pas dormi. Putain, un tribunal... j'ai l'impression d'avoir fait une bêtise.", "둘 다. 한숨도 못 잤어. 젠장, 법원이라니... 무슨 잘못이라도 저지른 기분이야."),
(A, "Bonjour, madame Marchand. Vous n'avez rien fait de mal. Vous demandez une protection, c'est tout.", "안녕하세요, 마르샹 씨. 잘못하신 건 없습니다. 보호를 요청하시는 것, 그뿐이에요."),
(H, "Bonjour, maître. Pardon, je pensais à voix haute.", "안녕하세요, 변호사님. 죄송해요, 혼잣말을 했네요."),
(A, "Ne vous excusez pas. Tout le monde ressent ça, ici, la première fois.", "사과하실 것 없어요. 여기서는 누구나 처음엔 그렇게 느낍니다."),
(J, "Bonjour, maître. Julien Benali, directeur de salle. Je suis là pour soutenir la patronne.", "안녕하세요, 변호사님. 홀 매니저 줄리앙 베날리입니다. 사장님 응원하러 왔어요."),
(A, "Enchanté. Mais l'audience se tient à huis clos. Vous attendrez dans le couloir.", "반갑습니다. 다만 심리는 비공개로 열립니다. 복도에서 기다려 주세요."),
(J, "À huis clos ? Comme dans les films de gangsters ?", "비공개요? 갱스터 영화처럼요?"),
(A, "Pas du tout. C'est juste plus discret. Les affaires d'une entreprise ne regardent pas la rue.", "전혀요. 그냥 더 조용히 하는 거예요. 기업의 사정을 길거리에 알릴 이유는 없으니까요."),
(J, "Ah, d'accord. Donc personne verra Hélène pleurer.", "아, 그렇구나. 그럼 엘렌이 우는 건 아무도 못 보겠네요."),
(H, "Je pleurerai pas. Enfin... j'espère.", "안 울 거야. 아니... 안 울었으면 좋겠다."),
(J, "Si tu pleures, j'ai un mouchoir. Il est propre, je te jure.", "울면 손수건 있어. 깨끗해, 맹세해."),
(A, "Je vous explique en deux minutes ce qui va se passer. Vous êtes prête ?", "앞으로 어떻게 진행되는지 2분 안에 설명드릴게요. 준비되셨어요?"),
(H, "Oui. Parlez-moi comme à une enfant de dix ans, s'il vous plaît.", "네. 열 살짜리한테 말하듯이 설명해 주세요."),
(A, "D'accord. Premièrement, les juges ne sont pas des magistrats de carrière. Ce sont des commerçants élus par leurs pairs.", "좋아요. 첫째, 판사들은 직업 법관이 아닙니다. 동료 상인들이 뽑은 상인들이에요."),
(J, "Des commerçants ? Donc des gens comme nous ?", "상인이요? 그럼 우리 같은 사람들이에요?"),
(A, "Exactement. Ils savent ce que c'est, un loyer, un fournisseur, un bilan.", "맞습니다. 임대료, 납품업체, 결산서가 뭔지 아는 사람들이에요."),
(H, "C'est rassurant. Un peu.", "좀 안심되네요. 조금은."),
(A, "Deuxièmement, le procureur sera peut-être là. Il veille à l'intérêt général. Ce n'est pas votre adversaire.", "둘째, 검사가 올 수도 있습니다. 공익을 지키는 사람이지, 당신의 적이 아니에요."),
(H, "Et moi, je dis quoi ?", "그리고 저는 뭐라고 말하죠?"),
(A, "Vous répondez simplement. La vérité, avec vos mots de cheffe. Pas de grandes phrases.", "간단히 답하세요. 진실을, 셰프의 말투로. 거창한 문장은 필요 없어요."),
(H, "Et si je bloque ?", "말이 막히면요?"),
(A, "Je suis à côté de vous. Je complète. Vous n'êtes pas seule.", "제가 옆에 있습니다. 제가 보충할게요. 혼자가 아닙니다."),
(H, "Vous, vous êtes calme comme un lac, hein.", "변호사님은 호수처럼 차분하시네요."),
(J, "Tu veux un café avant ? Il y a un distributeur au fond.", "들어가기 전에 커피 마실래? 저 안쪽에 자판기 있어."),
(H, "J'ai l'estomac noué. Je pourrais rien avaler.", "속이 꽉 막혀서 아무것도 못 삼키겠어."),
(A, "Un thé, plutôt. Le café, ça énerve. Je vous en rapporte un.", "차가 낫겠어요. 커피는 신경을 곤두서게 하거든요. 제가 가져다드릴게요."),
(A, "Dix-huit ans de métier. Mais mon premier jour, j'ai perdu mes notes dans l'escalier.", "경력 18년이에요. 그래도 첫날엔 계단에서 메모를 잃어버렸답니다."),
(J, "Ha ! Ça me rassure aussi, ça.", "하! 그 얘기도 안심이 되네요."),
(H, "Julien, une question. Tu m'as jamais dit pour Armand. Tu as vraiment dit non ?", "줄리앙, 하나 물어볼게. 아르망 건은 한 번도 말 안 했잖아. 정말 거절한 거야?"),
(J, "J'ai dit non à Armand fin octobre. Mille euros de plus, mais je quitte pas un bateau qui tangue.", "10월 말에 아르망한테 거절했어. 천 유로를 더 준다지만, 흔들리는 배를 버리고 가진 않아."),
(H, "T'es bête. Merci. Voilà, je pleure déjà, avant le juge.", "바보. 고마워. 봐, 판사 앞에도 가기 전에 벌써 울잖아."),
(None, "9 h 30. Chambre du conseil. Le président et deux juges consulaires écoutent. Une greffière note. Julien reste dehors.", "9시 30분. 비공개 심리실. 재판장과 상사법원 판사 두 명이 듣고 있다. 서기관이 기록한다. 줄리앙은 밖에 남는다."),
(A, "Monsieur le président, ma cliente demande l'ouverture d'une procédure de sauvegarde. Elle va s'expliquer.", "재판장님, 의뢰인은 회생(소생) 절차 개시를 신청합니다. 직접 설명드리겠습니다."),
(A, "Madame Marchand, le président vous invite à présenter l'entreprise en quelques mots.", "마르샹 씨, 재판장님이 회사를 몇 마디로 소개해 달라고 하십니다."),
(H, "Monsieur le président, je dirige un restaurant rue Saint-Maur. C'était celui de ma mère, depuis trente-cinq ans.", "재판장님, 저는 생모르 거리에서 식당을 운영합니다. 35년 전부터 어머니의 가게였습니다."),
(H, "Début octobre, le loyer est passé de 3 800 à 5 200 euros par mois.", "10월 초에 임대료가 월 3,800유로에서 5,200유로로 올랐습니다."),
(H, "Et nous avons moins de clients depuis l'été. La banque a refusé de nous prêter.", "그리고 여름부터 손님이 줄었습니다. 은행은 대출을 거절했고요."),
(A, "Il demande si vous êtes en cessation des paiements. Laissez-moi répondre.", "지급정지 상태인지 묻고 계세요. 제가 답하겠습니다."),
(H, "Pardon... en quoi ?", "네? 무슨... 상태요?"),
(A, "Monsieur le président, elle ne l'est pas. Elle paie encore ses salaires et ses fournisseurs du jour.", "재판장님, 그렇지 않습니다. 직원 급여와 당일 납품 대금은 아직 지급하고 있습니다."),
(A, "Mais seule, elle ne peut plus surmonter ses difficultés. C'est exactement le cas prévu pour une sauvegarde.", "다만 혼자서는 어려움을 극복할 수 없습니다. 바로 회생 절차가 예정한 경우입니다."),
(A, "Le procureur demande si vous comptez vendre le fonds de commerce.", "검사가 영업권을 팔 생각이 있는지 묻습니다."),
(H, "Non. On m'a proposé de racheter, j'ai refusé. Je veux garder le restaurant, c'est tout.", "아니요. 인수 제안이 있었지만 거절했습니다. 저는 가게를 지키고 싶을 뿐입니다."),
(A, "Elle a un plan. Elle prépare un financement participatif et un nouvel accord avec ses producteurs.", "계획도 있습니다. 크라우드펀딩과 생산자들과의 새 협약을 준비하고 있어요."),
(A, "Merci, madame. Le président met l'affaire en délibéré. Le jugement sera prononcé à 11 h 30.", "감사합니다. 재판장님이 사건을 선고 대기로 두셨어요. 판결은 11시 30분에 선고됩니다."),
(H, "C'est fini ? Déjà ? J'ai parlé cinq minutes !", "끝났어요? 벌써요? 5분밖에 말 안 했는데!"),
(A, "Sept, exactement. Et vous avez très bien parlé. Venez, on sort.", "정확히 7분이었어요. 아주 잘 말씀하셨고요. 나가시죠."),
(J, "Alors ? Alors ? Ils t'ont mangée ?", "어떻게 됐어? 잡아먹혔어?"),
(H, "Non. Mais j'ai rien compris à un mot : « cessation des paiements ». Ça veut dire quoi ?", "아니. 근데 한 단어도 이해를 못 했어. « 지급정지 »가 무슨 뜻이야?"),
(A, "En clair : on ne peut plus payer ce qu'on doit tout de suite, avec l'argent qu'on a.", "쉽게 말하면, 가진 돈으로는 당장 갚아야 할 빚을 더 못 갚는 상태예요."),
(A, "Si c'est le cas, on demande un redressement. Vous, vous êtes avant. Vous prévenez le problème.", "그 상태라면 회생(기업 재건) 절차를 신청합니다. 당신은 그 전 단계예요. 문제를 미리 막는 거죠."),
(J, "Donc c'est un peu comme aller chez le médecin avant d'être malade ?", "그럼 아프기 전에 병원 가는 것 같은 거예요?"),
(A, "C'est très bien dit. Je vais vous voler l'image pour mes prochains clients.", "아주 좋은 비유네요. 다음 의뢰인들한테 그 표현을 훔쳐 써야겠어요."),
(H, "Et concrètement, si le tribunal dit oui, qu'est-ce qui change lundi matin ?", "그럼 구체적으로, 법원이 승인하면 월요일 아침에 뭐가 달라져요?"),
(A, "Première chose : on gèle vos dettes. Tout ce que vous deviez avant le jugement, personne ne peut vous le réclamer.", "첫째, 빚이 동결됩니다. 판결 이전에 갚아야 했던 돈은 누구도 지금 요구할 수 없어요."),
(H, "Même Delmas ? Même l'URSSAF ?", "델마스 씨도요? 사회보험 기관(URSSAF)도요?"),
(A, "Même eux. On appelle ça l'arrêt des poursuites. Plus de huissier, plus de saisie.", "그분들도요. '추심 중지'라고 부릅니다. 집행관도, 압류도 더는 없어요."),
(J, "Waouh. Et la banque, elle peut bloquer ton compte ?", "와우. 은행이 네 계좌를 막을 수도 있어?"),
(A, "Pour les anciennes dettes, non. Mais attention, il y a une règle importante.", "예전 빚 때문이라면 안 됩니다. 하지만 중요한 규칙이 하나 있어요."),
(A, "Il faut que vous payiez toutes les nouvelles factures à l'échéance. Loyer, salaires, fournisseurs : tout, à la date.", "새로 생기는 청구서는 전부 기한에 맞춰 내셔야 합니다. 임대료, 급여, 납품 대금, 전부 날짜대로요."),
(H, "Même le loyer de décembre ?", "12월 임대료도요?"),
(A, "Surtout le loyer de décembre. Si vous le ratez, la protection saute, et Delmas peut agir.", "12월 임대료가 특히 그래요. 그걸 놓치면 보호가 풀리고 델마스 씨가 행동에 나설 수 있어요."),
(H, "D'accord. Je le noterai en rouge dans mon agenda.", "알겠어요. 수첩에 빨간색으로 적어 둘게요."),
(H, "Et qui dirige le restaurant ? Moi ou un étranger ?", "그리고 식당은 누가 운영해요? 저예요, 아니면 낯선 사람이에요?"),
(A, "Vous. Vous gardez les clés, la caisse et la carte. En sauvegarde, c'est le patron qui commande.", "당신이요. 열쇠도, 금고도, 메뉴도 그대로 가집니다. 회생 절차에서는 사장이 계속 지휘해요."),
(J, "Et si le tribunal dit oui, qui nous surveille ?", "그리고 법원이 승인하면, 누가 우리를 감시해요?"),
(A, "Personne ne vous surveille. On vous accompagne. Il y aura un juge-commissaire et un mandataire judiciaire.", "아무도 감시하지 않아요. 곁에서 함께하는 겁니다. 감독 판사와 법원 지정 관재인이 붙습니다."),
(H, "Le mandataire, c'est le bourreau ?", "관재인이라는 사람, 사형 집행인 같은 건 아니죠?"),
(A, "Non, c'est plutôt l'arbitre. Il vérifie les dettes et représente tous vos créanciers à la fois.", "아니요, 심판에 가깝습니다. 빚을 검증하고 채권자 전체를 한꺼번에 대표해요."),
(A, "Vos créanciers ont deux mois pour déclarer leurs créances. Lui, il fait la liste officielle.", "채권자들은 두 달 안에 채권을 신고해야 합니다. 관재인이 공식 목록을 만들어요."),
(J, "Et ça dure combien de temps, tout ça ?", "그리고 이게 다 얼마나 걸려요?"),
(A, "La période d'observation dure six mois. On peut la renouveler, mais on espère ne pas en avoir besoin.", "관찰 기간은 6개월입니다. 연장할 수 있지만 그럴 필요가 없길 바라요."),
(H, "Et à la fin, il se passe quoi ?", "그럼 끝에는 어떻게 되는데요?"),
(A, "Le tribunal juge votre plan de remboursement. S'il le trouve sérieux, il l'adopte, pour huit ans par exemple.", "법원이 상환 계획을 심사합니다. 진지하다고 판단하면 채택하죠. 예를 들어 8년으로요."),
(A, "Et si un créancier refuse, le tribunal peut lui imposer des délais. C'est la force de la sauvegarde.", "채권자가 거부해도 법원이 기한을 강제할 수 있어요. 그게 회생 절차의 힘이에요."),
(H, "Donc personne peut dire non pour de bon ?", "그럼 아무도 끝까지 안 된다고 못 하는 거예요?"),
(A, "Pas complètement. Mais il faut un plan réaliste. Un plan qu'on peut vraiment tenir.", "완전히는 아니에요. 하지만 현실적인 계획이 있어야 합니다. 진짜로 지킬 수 있는 계획이요."),
(H, "Un plan réaliste. Ça, je sais faire. C'est comme une recette : tout doit tenir ensemble.", "현실적인 계획. 그건 제가 할 줄 알아요. 레시피랑 같죠. 모든 게 서로 맞물려야 하니까."),
(J, "Et si le juge dit non aujourd'hui ?", "그리고 판사가 오늘 안 된다고 하면요?"),
(A, "Je ne le crois pas. Votre dossier est propre. Mais je ne promets jamais rien avant le jugement.", "그렇게 보진 않아요. 서류가 깔끔하니까요. 하지만 판결 전에는 절대 장담하지 않아요."),
(None, "11 h 30. Salle d'audience publique. Peu de monde. Hélène s'assoit entre Me Aubry et Julien, mains jointes. Le président lit le jugement.", "11시 30분. 공개 법정. 사람은 많지 않다. 엘렌은 오브리 변호사와 줄리앙 사이에 앉아 두 손을 모으고 있다. 재판장이 판결을 읽는다."),
(None, "« Le tribunal ouvre une procédure de sauvegarde à l'égard de la société... fixe la période d'observation à six mois... »", "« 법원은 해당 회사에 대하여 회생 절차를 개시하고... 관찰 기간을 6개월로 정한다... »"),
(H, "Maître, il a dit oui ? Je n'ai pas bien entendu.", "변호사님, 승인한다고 했어요? 잘 못 들었어요."),
(A, "Il a dit oui. Écoutez bien la suite, je vous traduis en même temps.", "승인했습니다. 뒷부분을 잘 들으세요. 제가 동시에 풀어 드릴게요."),
(J, "Six mois, c'est long ou court ?", "6개월이면 긴 거예요, 짧은 거예요?"),
(A, "Pour reconstruire un restaurant, c'est court. Mais c'est assez pour un plan sérieux.", "식당을 재건하기엔 짧아요. 하지만 진지한 계획을 세우기엔 충분합니다."),
(None, "« ...désigne Madame Lemaire en qualité de mandataire judiciaire... »", "« ...르메르 부인을 법원 지정 관재인으로 선임한다... »"),
(A, "Là, il nomme votre mandataire. Elle est dans la salle, tout à gauche, celle avec le tailleur gris.", "지금 담당 관재인을 지명한 겁니다. 법정 맨 왼쪽, 회색 정장 입은 분이에요."),
(H, "Elle a l'air sévère.", "무서워 보이는데요."),
(A, "Elle a l'air concentrée. Nuance. Allons la saluer.", "집중한 얼굴이에요. 느낌이 달라요. 가서 인사하죠."),
(M, "Madame Marchand ? Françoise Lemaire, mandataire judiciaire. Enchantée.", "마르샹 씨? 프랑수아즈 르메르, 법원 지정 관재인입니다. 반갑습니다."),
(M, "Je ne suis pas là pour vous couler, madame. Mon travail, c'est que chacun récupère ce qui lui est dû.", "당신을 무너뜨리려고 있는 게 아닙니다. 제 일은 모두가 받을 돈을 받도록 하는 거예요."),
(M, "Et si possible, que l'entreprise survive. C'est le meilleur moyen d'être payé.", "가능하면 회사가 살아남도록요. 그게 돈을 돌려받는 가장 좋은 방법이니까요."),
(H, "C'est aussi mon avis. Qu'est-ce que vous attendez de moi ?", "저도 같은 생각입니다. 저한테 뭘 원하시죠?"),
(M, "Trois choses. La liste complète de vos dettes, vos bilans des trois dernières années, et un compte bancaire dédié.", "세 가지입니다. 빚 전체 목록, 최근 3년 결산서, 그리고 전용 은행 계좌요."),
(H, "J'ai tout ça dans un classeur. Je suis une fille organisée.", "그건 다 바인더에 있어요. 제가 정리는 잘하거든요."),
(M, "Je m'en doutais. Je viendrai lundi à votre restaurant, vers quatorze heures.", "그럴 줄 알았어요. 월요일 오후 2시쯤 식당으로 찾아가겠습니다."),
(M, "Le lundi, vous êtes fermés, n'est-ce pas ? Je convoque vos principaux créanciers à ce moment-là.", "월요일은 휴무시죠? 그때 주요 채권자들을 소집하겠습니다."),
(H, "Vous voulez les réunir chez moi ? Tous ?", "저희 가게에서 한꺼번에 만나게 하겠다고요? 전부요?"),
(M, "Les principaux, oui. Le propriétaire, un fournisseur, les organismes... C'est plus simple pour tout le monde.", "주요한 분들만요. 건물주, 납품업체 하나, 관련 기관들... 모두에게 그게 더 간단합니다."),
(A, "Madame Lemaire va leur présenter votre proposition. Nous allons la préparer ensemble ce week-end.", "르메르 관재인이 여러분의 제안을 채권자들에게 설명할 겁니다. 이번 주말에 같이 준비하죠."),
(H, "Une proposition... il faut que je trouve des chiffres. Combien de temps je demande, sur quelle somme ?", "제안... 숫자를 찾아야 하는군요. 얼마의 기간을 요청하고, 어느 금액으로요?"),
(A, "Dimanche, chez moi, avec tous vos papiers. On écrira un calendrier sur huit ans.", "일요일에 제 사무실에서 서류 전부 가지고 봅시다. 8년짜리 상환 일정을 쓸 거예요."),
(M, "À lundi, madame Marchand. Respirez. Les six premiers mois sont les plus durs.", "월요일에 뵙겠습니다. 숨 쉬세요. 처음 6개월이 제일 힘들어요."),
(None, "Dehors, sur le quai. Le soleil perce enfin les nuages. Hélène s'appuie à la rambarde.", "밖 강변길. 마침내 해가 구름을 뚫는다. 엘렌이 난간에 기댄다."),
(H, "Six mois. J'ai six mois pour sauver la maison de ma mère.", "6개월. 엄마의 집을 구하는 데 6개월이 있어."),
(J, "Putain, Hélène, on a gagné !", "젠장, 엘렌, 우리가 이겼어!"),
(A, "Doucement. Ce n'est pas une victoire, c'est une chance. Le plan reste à écrire.", "진정하세요. 승리가 아니라 기회예요. 계획은 아직 써야 하고요."),
(H, "Une chance, c'est déjà beaucoup. Hier soir, j'avais l'impression de tomber dans le vide.", "기회라면 그것만으로도 충분해요. 어제 저녁엔 허공으로 떨어지는 기분이었거든요."),
(H, "Maître, je vous dois combien pour aujourd'hui ?", "변호사님, 오늘 건은 얼마를 드려야 하죠?"),
(A, "On parlera honoraires dimanche. Je suis raisonnable. Alors rentrez déjeuner. Mangez quelque chose de chaud.", "보수 얘기는 일요일에 해요. 부담스럽지 않게 할게요. 그럼 점심 드시러 가세요. 따뜻한 걸 드세요."),
(J, "Ça tombe bien, c'est notre métier. Lucien a appelé quatre fois. Il tient la boutique.", "잘됐네요, 그게 우리 직업이잖아요. 뤼시앙이 네 번이나 전화했어. 가게를 보고 있대."),
(H, "Quatre fois ! Appelle-le, dis-lui que c'est oui. Et que je rentre.", "네 번이나! 전화해서 승인이라고 전해 줘. 그리고 나 돌아간다고."),
(J, "Je le fais en marchant. Tu veux que je lui dise autre chose ?", "걸으면서 할게. 다른 말도 전할까?"),
(H, "Dis-lui... dis-lui que le plat du jour sera la blanquette de maman.", "전해 줘... 오늘의 요리는 엄마의 블랑케트라고."),
(A, "Madame Marchand, une dernière chose. Gardez tous vos papiers de ces six mois, même les petits tickets.", "마르샹 씨, 마지막으로 하나만요. 앞으로 6개월 동안의 서류는 영수증 한 장까지 전부 보관하세요."),
(H, "Même les petits tickets. Promis. Merci, maître. Merci pour tout.", "영수증 한 장까지요. 약속할게요. 감사합니다, 변호사님. 모든 것에 감사드려요."),
(A, "C'est mon métier. À dimanche. Et dormez cette nuit, c'est un ordre.", "제 일이니까요. 일요일에 봅시다. 그리고 오늘 밤은 주무세요, 명령입니다."),
(J, "Alors, patronne ? On rentre. On a un service à assurer, et une blanquette à réussir.", "자, 사장님? 돌아가자. 치러야 할 서비스도 있고, 성공시킬 블랑케트도 있잖아."),
(H, "On rentre. Six mois, Julien. Ça commence maintenant.", "돌아가자. 6개월이야, 줄리앙. 지금부터 시작이야."),
]

VOCAB = [
("A2", "Vous attendrez dans le couloir.", "복도에서 기다리실 겁니다(기다려 주세요).", "미래형을 정중한 지시로 씀. 구어에서는 « Attendez dans le couloir, s'il vous plaît » 보다 부드럽게 들린다."),
("B1", "à huis clos", "비공개로", "« l'audience se tient à huis clos ». 법정·회의가 방청 없이 열릴 때. 반대는 « en audience publique »."),
("B1", "avoir la trouille", "겁나다, 무섭다", "[구어] « C'est le froid ou la trouille ? » ↔ 정중: « Avez-vous peur ? / Vous appréhendez ? ». 친구 사이에서만."),
("B1", "penser à voix haute", "혼잣말로 생각을 입 밖에 내다", "« Pardon, je pensais à voix haute. » 실수로 속마음이 나왔을 때의 사과."),
("B1", "tanguer", "(배가) 흔들리다", "« je quitte pas un bateau qui tangue ». 위기에 처한 회사를 배에 비유. 비유 표현 « tant que le navire flotte »와 같은 계열."),
("B1", "se tenir (audience)", "열리다, 진행되다", "« L'audience se tient à huis clos. » 회의·재판이 열리는 장소와 방식을 말할 때."),
("B2", "une procédure de sauvegarde", "회생(소생) 절차", "경영이 어려워지기 전에 법원의 보호를 받는 제도. 지급정지 이전 단계라 « redressement judiciaire »(법정 관리·재건), « liquidation »(청산)와 구별."),
("B2", "la période d'observation", "관찰 기간", "« six mois ». 이 동안 사장이 경영을 계속하고 상환 계획을 준비. 연장 가능."),
("B2", "un mandataire judiciaire", "법원 지정 관재인(채권자 대표)", "채권을 확인하고 채권자 전체를 대표. 경영은 하지 않는다. « C'est plutôt l'arbitre. »"),
("B2", "la cessation des paiements", "지급정지", "가진 현금으로 당장 갚아야 할 빚을 못 갚는 상태. « En clair : on ne peut plus payer ce qu'on doit. »"),
("B2", "mettre en délibéré", "선고를 미루고 합의·심리에 들어가다", "« met l'affaire en délibéré ». 판결 날짜를 따로 정할 때 쓴다."),
("B2", "l'arrêt des poursuites", "추심 중지(채권 행사 동결)", "« on gèle vos dettes ». 개시 전 빚은 요구할 수 없다. 구어: « geler ». 정중: « suspendre les poursuites »."),
("B2", "déclarer ses créances", "채권을 신고하다", "채권자는 두 달 안에 관재인에게 받을 돈을 신고. « une créance » = 받을 돈, « un créancier » = 채권자."),
("B2", "à l'échéance", "기한(만기)에 맞춰", "« Il faut que vous payiez à l'échéance. » 새 청구서는 날짜대로 내야 보호가 유지된다."),
("B2", "un juge consulaire", "상사법원 판사(상인 출신 선출직)", "직업 법관이 아니라 상인들이 뽑은 상인. « des commerçants élus par leurs pairs »."),
("B2", "le procureur", "검사", "« Il veille à l'intérêt général. » 개인이나 회사의 적이 아니라 공익의 대표."),
("C1", "En clair, …", "쉽게 말해서, …", "[구어] 어려운 용어를 풀어 줄 때. ↔ 정중: « Autrement dit, … / Pour le dire simplement, … »."),
("C1", "le fonds de commerce", "영업권(가게의 영업 자산 일체)", "상호·단골·임차권 등을 포함. 인수 제안(Faure)은 « racheter le fonds »."),
("C1", "le passif / l'actif", "부채 / 자산", "« passif exigible » = 지금 갚아야 하는 부채. 서류에서는 자주 나오고 말로는 « ce qu'on doit / ce qu'on a »."),
("C1", "un huissier / une saisie", "집행관 / 압류", "« Plus d'huissier, plus de saisie. » 빚을 강제로 받아내는 사람과 수단."),
("C1", "ne pas être là pour couler quelqu'un", "누군가를 침몰시키려는 게 아니다", "« Je ne suis pas là pour vous couler. » 배 비유(couler = 가라앉히다). 신뢰를 주는 전문가의 말."),
("C1", "un plan réaliste / tenir un plan", "현실적인 계획 / 계획을 지키다", "« Un plan qu'on peut vraiment tenir. » 채택의 핵심 조건. « tenir » = 약속·계획을 이행하다."),
("C1", "imposer des délais", "(채권자에게) 기한 유예를 강제하다", "« le tribunal peut lui imposer des délais ». 회생 절차의 강점: 반대하는 채권자에게도 분할 상환을 적용."),
("C1", "garder les clés", "경영권을 유지하다", "« Vous gardez les clés. » 열쇠를 갖는다 = 계속 사장으로 경영. 회생과 청산의 큰 차이."),
]

GRAM = [
("B1", "미래형으로 하는 절차 안내: « Vous attendrez », « Je viendrai lundi »", "변호사와 관재인은 앞으로 일어날 절차를 미래형으로 안내합니다. « Vous attendrez dans le couloir. » « Je viendrai lundi à votre restaurant. » 지시와 예고를 부드럽게 만드는 효과가 있고, 명령형보다 정중합니다. 지금 곧 할 일은 근접미래 « je vais vous expliquer » 와 구분하세요."),
("B2", "풀어 말하기(reformulation) 표현: « En clair », « Là, il nomme… », « Ça veut dire que… »", "법률 용어를 쉽게 풀 때 쓰는 연결 표현입니다. « En clair : on ne peut plus payer ce qu'on doit. » « Là, il nomme votre mandataire. » 먼저 용어를 말하고 « ça veut dire / en clair / autrement dit » 로 일상어로 바꾸는 순서입니다. 의뢰인은 « Ça veut dire quoi ? » 로 요청."),
("B2", "수동태와 비인칭 수동: « Les dettes sont gelées », « Le jugement sera prononcé »", "공식적인 사실은 행위자를 숨기고 수동으로 말합니다. « Le jugement sera prononcé à 11 h 30. » 구어에서는 « on » 으로 바꾸기도 합니다: « On gèle vos dettes. » 문어 ↔ 구어: « Les dettes sont gelées » ↔ « on gèle vos dettes »."),
("B2", "il faut que + 접속법: « Il faut que vous payiez… »", "의무를 말할 때 « il faut que » 뒤에는 접속법 현재가 옵니다. « Il faut que vous payiez toutes les nouvelles factures à l'échéance. » « Il faut que je trouve des chiffres. » payer → que vous payiez, trouver → que je trouve."),
("B2", "대조 강조 구문: « Ce n'est pas A, c'est B »", "오해를 바로잡을 때 쓰는 균형 잡힌 구문입니다. « Ce n'est pas une victoire, c'est une chance. » « Vous n'êtes pas une criminelle. » 문장을 짧게 둘로 나눠 말하는 구어 리듬에도 잘 맞습니다."),
("B1", "구어 부정 ne 생략과 강조: « Personne va te regarder », « Je pleurerai pas »", "구어에서는 ne 를 생략합니다. « Personne va te regarder. » « Je veux pas avoir l'air… » « Tu m'as jamais dit pour Armand. » 그러나 법원·변호사 장면(정중한 구어)에서는 ne 를 살립니다: « Elle ne l'est pas. » « Je ne suis pas là pour vous couler. »"),
("B2", "대명사 en으로 반복 줄이기: « Je m'en doutais », « Je vous en rapporte un »", "« Je m'en doutais. » 는 « de cela » 를 en 으로 받은 것입니다. « J'ai tout ça dans un classeur. » « Je vous en rapporte un. » 장소·사람이 아닌 'de + 명사'는 en, 'à + 명사'는 y 로 받는다는 규칙을 기억하세요."),
]

READ = [
("huis clos — /ɥi klo/", "« à huis clos » 의 huis 는 [위이] 처럼 빠르게 /ɥi/ 로 읽고, clos 의 s 는 소리 나지 않습니다. 따라서 « l'audience se tient / à huis clos. » 처럼 호흡을 끊어 읽으면 자연스럽습니다."),
("엘리종과 리에종 — Ils sont élus", "« des commerçants élus par leurs pairs » 에서 leurs pairs 사이 [z] 리에종은 없지만, « Ils sont_élus » 처럼 sont 의 t 가 다음 모음과 이어집니다. « Ce sont des commerçants / élus par leurs pairs. » 로 호흡을 나누세요."),
("비음 — cessation des paiements", "« cessation des paiements » 의 -tion 은 [sjɔ̃], paiements 의 -ents 는 [mɑ̃]. 두 비음을 구분해 « la cessation / des paiements » 처럼 짧게 끊어 읽습니다."),
("r 소리 — procureur, tribunal", "« Le procureur veille à l'intérêt général. » 에서 r 은 목구멍 안쪽에서 가볍게 굴립니다. « procureur » 의 두 r 모두 약하게, 마지막 -eur 은 입을 둥글게 하세요."),
("긴 문장의 호흡 구간", "« Première chose : / on gèle vos dettes. » « Tout ce que vous deviez avant le jugement, / personne ne peut vous le réclamer. » 콜론과 쉼표에서 숨을 쉬고, 문장 끝은 내려가는 억양입니다."),
("의문문 억양 — Et moi, je dis quoi ?", "« Et moi, / je dis quoi ? » 는 첫 구간을 올리고 둘째 구간 끝을 내립니다(의문사 의문문). « Ça veut dire quoi ? » 도 마지막 quoi 에서 내려갑니다."),
("판결문 낭독의 톤", "« Le tribunal ouvre une procédure de sauvegarde / à l'égard de la société... » 판결문은 일정한 속도와 낮은 톤으로 낭독합니다. 이어서 변호사의 풀이는 일상 속도로 바꾸어, 두 톤의 차이를 소리 내어 연습하세요."),
]

CULTURE = [
("Le tribunal de commerce — 상인이 상인을 재판한다", "프랑스의 상사법원(tribunal de commerce)은 직업 법관이 아니라 상인·기업인이 선거로 뽑은 '판사(juge consulaire)'가 맡는 독특한 법원입니다. 기업의 곤경을 현장에서 아는 사람들이 판단한다는 전통(중세 상인 재판소에서 유래)입니다. 심리는 비공개(huis clos) 이고 판결 선고만 공개로 합니다. 이 극에서 오브리 변호사가 '우리 같은 사람들'이라고 설명하는 이유입니다."),
("La procédure de sauvegarde — 지급정지 전의 보호막", "2005년 도입된 sauvegarde 는 지급정지 이전에 신청하는 절차로, 사장이 경영권을 유지한 채 6개월 관찰 기간 동안 빚을 동결하고 상환 계획을 짭니다. 계획이 채택되면 최장 10년까지 분할 상환이 가능합니다. redressement(지급정지 이후)나 liquidation(청산)보다 훨씬 앞 단계이며, '아프기 전에 병원에 간다'는 비유가 적절합니다."),
]

META = dict(part=4, ep=46, part_label="제4부 La reconstruction · 늦가을·겨울", title_fr="Le tribunal de commerce", title_ko="상사법원",
 place="파리 상사법원(시테섬), 11월 12일 목요일 오전 8시 50분 ~ 낮 12시 무렵",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Me Aubry (변호사) · Mme Lemaire (법원 지정 관재인)",
 wine="회생(sauvegarde) 절차 개시 판결: 관찰 기간 6개월, 빚 동결, 관재인 르메르 부인 선임.",
 focus="법원 절차를 쉬운 말로 풀어 말하기(en clair), 미래형 안내, 수동태, il faut que + 접속법, 전문 어휘",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제47화 « Les créanciers » : 11월 16일 월요일 휴무일 오후, 관재인 르메르 부인이 채권자들을 한자리에 모으고 엘렌은 8년 상환안을 설명한다.")
