# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, B, D_, M = "Hélène", "M. Bastide", "M. Delmas", "Mme Lemaire"
D = [
(None, "Lundi 16 novembre, 13 h 45. Le restaurant est fermé. Hélène a poussé quatre tables ensemble : carafe d'eau, tasses, calculatrice. Mme Lemaire pose une pile de dossiers au bout de la table.", "11월 16일 월요일 오후 1시 45분. 식당은 휴무다. 엘렌이 테이블 네 개를 붙여 놓았다. 물병, 커피잔, 계산기. 르메르 관재인이 테이블 끝에 서류 더미를 올려 놓는다."),
(M, "Bonjour, madame Marchand. Vous avez bien rangé la salle. Je vous rappelle les règles de cette réunion.", "안녕하세요, 마르샹 씨. 홀을 잘 정리하셨네요. 이 회의의 규칙을 다시 알려 드릴게요."),
(H, "Je vous écoute. J'ai même fait du café, au cas où.", "듣고 있어요. 혹시 몰라서 커피도 내려 놨어요."),
(M, "Parfait. Je suis neutre. Je ne défends ni vous ni eux. Je fais en sorte qu'on se comprenne.", "좋아요. 저는 중립입니다. 당신 편도 그들 편도 아니에요. 서로 이해하도록 돕는 겁니다."),
(M, "Chacun parle à son tour. Personne ne signe aujourd'hui. Les accords seront confirmés par écrit.", "각자 차례대로 말합니다. 오늘 서명하는 사람은 없어요. 합의는 서면으로 확정됩니다."),
(H, "Donc aujourd'hui, on discute seulement.", "그러니까 오늘은 논의만 하는 거군요."),
(M, "Oui. Et vous exposez votre proposition, chiffres à l'appui. Vous les avez ?", "네. 그리고 숫자를 근거로 제안을 설명하시는 거예요. 준비되셨죠?"),
(H, "J'ai passé deux nuits dessus. Un tableau, un graphique, et même un plan B.", "이틀 밤을 새웠어요. 표 하나, 그래프 하나, 심지어 플랜 B까지요."),
(M, "Gardez le plan B pour vous. Si un créancier le voit, il se méfie du plan A.", "플랜 B는 혼자만 갖고 계세요. 채권자가 보면 플랜 A를 의심하거든요."),
(H, "Compris. Le plan B reste dans ma poche.", "알겠어요. 플랜 B는 주머니에 넣어 둘게요."),
(M, "Rappelez-moi le total. Je veux l'entendre de votre bouche avant qu'ils arrivent.", "총액을 다시 말씀해 주세요. 그들이 오기 전에 직접 듣고 싶어요."),
(H, "92 000 euros, exactement. J'ai vérifié ligne par ligne.", "정확히 92,000유로예요. 한 줄 한 줄 확인했어요."),
(M, "Détaillez-moi ça.", "세부 내역을 말씀해 주세요."),
(H, "Le loyer d'abord : 15 600 €. Octobre et novembre, ça fait 10 400, plus 5 200 de charges et de taxe foncière.", "먼저 임대료요. 15,600유로. 10월과 11월분이 10,400, 거기에 관리비와 재산세 5,200이 더해져요."),
(M, "Et ensuite ?", "그다음은요?"),
(H, "Les fournisseurs : 4 200 pour Bastide, et 13 200 pour les autres. Le boucher, le poissonnier, la cave.", "납품업체요. 바스티드 씨에게 4,200, 나머지에 13,200이에요. 정육점, 생선 가게, 와인 업체."),
(H, "Puis l'URSSAF, 22 000. Les impôts, 19 000. Et les équipementiers, 18 000.", "그리고 사회보험(URSSAF) 22,000. 세금 19,000. 설비업체 18,000이에요."),
(M, "Faisons l'addition ensemble. 15 600 plus 4 200, ça fait combien ?", "같이 더해 봅시다. 15,600 더하기 4,200은 얼마죠?"),
(H, "19 800. Plus 13 200, 33 000. Plus 22 000, 55 000. Plus 19 000, 74 000. Plus 18 000 : 92 000.", "19,800. 13,200을 더하면 33,000. 22,000 더하면 55,000. 19,000 더하면 74,000. 18,000 더하면 92,000."),
(M, "Le compte est bon. C'est rare, un dirigeant qui arrive avec une addition juste.", "계산이 맞네요. 정확한 합계를 들고 오는 경영자는 드물어요."),
(H, "En cuisine, si on se trompe d'un gramme, le plat est raté. Les chiffres, c'est pareil.", "주방에서는 1그램만 틀려도 요리를 망쳐요. 숫자도 마찬가지고요."),
(None, "14 h pile. M. Bastide entre avec une cagette de poireaux. M. Delmas le suit, un dossier en cuir sous le bras.", "정각 2시. 바스티드 씨가 대파 한 상자를 들고 들어온다. 델마스 씨가 가죽 서류철을 끼고 뒤따른다."),
(B, "Bonjour, bonjour ! Je suis pas en retard ? J'ai garé la camionnette sur le trottoir. C'est interdit, mais bon.", "안녕하세요, 안녕하세요! 늦지 않았죠? 트럭을 인도에 세웠어요. 금지지만, 뭐 어쩌겠어요."),
(H, "Bonjour, monsieur Bastide. Vous êtes pile à l'heure.", "안녕하세요, 바스티드 씨. 딱 맞춰 오셨어요."),
(B, "Je vous ai apporté des poireaux. C'est pas pour vous acheter, hein. C'est parce qu'ils sont beaux.", "대파를 가져왔어요. 환심 사려는 게 아니에요, 알죠? 예뻐서 가져온 거예요."),
(H, "Je les prends avec plaisir. Et merci d'être venu.", "기쁘게 받을게요. 와 주셔서 감사해요."),
(D_, "Bonjour, madame, monsieur. Édouard Delmas. Madame Lemaire, nous nous sommes parlé au téléphone.", "안녕하십니까, 여러분. 에두아르 델마스입니다. 르메르 관재인님, 전화로 통화했었지요."),
(M, "Monsieur Delmas, bienvenue. Installez-vous. Un café ?", "델마스 씨, 어서 오세요. 앉으세요. 커피 드릴까요?"),
(D_, "Volontiers, merci. Noir, sans sucre.", "고맙습니다, 마시죠. 블랙으로, 설탕 없이요."),
(H, "Bonjour, monsieur Delmas. Merci d'avoir fait le déplacement.", "안녕하세요, 델마스 씨. 직접 와 주셔서 감사합니다."),
(D_, "C'est bien naturel, madame. C'est mon immeuble, après tout.", "당연한 일입니다. 어쨌든 제 건물이니까요."),
(B, "Moi, je prendrais bien un verre de rouge, mais je conduis.", "저는 레드와인 한 잔 하고 싶은데, 운전을 해야 하네요."),
(H, "Le vin attendra la fin de la réunion, monsieur Bastide.", "와인은 회의가 끝날 때까지 기다려야죠, 바스티드 씨."),
(M, "Bien. Je rappelle le cadre : le tribunal a ouvert une sauvegarde jeudi. Mon rôle est de recueillir vos positions.", "좋습니다. 틀을 다시 말씀드리죠. 법원이 목요일에 회생 절차를 개시했습니다. 제 역할은 여러분의 입장을 듣는 거예요."),
(M, "Madame Marchand présente sa proposition. Ensuite, chacun répond. Madame ?", "마르샹 씨가 제안을 설명하시고, 그다음 각자 답합니다. 시작하시죠."),
(H, "Merci. Je serai directe. Je dois 92 000 euros à une quinzaine de créanciers, dont vous deux.", "감사합니다. 솔직하게 말씀드릴게요. 저는 두 분을 포함해 열댓 곳의 채권자에게 92,000유로를 빚지고 있습니다."),
(H, "Je ne peux pas tout rembourser demain. Mais je peux tout rembourser, si on me laisse du temps.", "내일 당장 전부 갚을 수는 없어요. 하지만 시간을 주신다면 전부 갚을 수 있습니다."),
(B, "Du temps, c'est combien ? Parce que moi, mes carottes, elles ont pas le temps.", "시간이라면 얼마나요? 제 당근은 기다려 주지 않거든요."),
(H, "Huit ans. Avec une première année de pause.", "8년입니다. 첫 1년은 쉬어 가고요."),
(B, "Huit ans ! Pardon, j'ai bien entendu ?", "8년이라고요! 죄송한데, 제대로 들은 건가요?"),
(M, "Laissez-la finir, monsieur Bastide. Vous poserez vos questions après.", "끝까지 들으세요, 바스티드 씨. 질문은 그다음에 하시고요."),
(H, "Calculons ensemble. 92 000 divisé par 8, ça fait 11 500 par an. Mais ce n'est pas ce que je propose.", "같이 계산해 보죠. 92,000을 8로 나누면 1년에 11,500이에요. 하지만 제가 제안하는 건 그게 아닙니다."),
(H, "Pourquoi ? Parce que la première année, je dois reconstruire. Chantier, trésorerie, nouvelle carte.", "왜냐고요? 첫해에는 가게를 다시 세워야 하니까요. 공사, 운영 자금, 새 메뉴."),
(H, "D'abord, monsieur Delmas : 15 600 €, en douze mensualités de 1 300 €.", "먼저 델마스 씨 몫이요. 15,600유로를 12개월 동안 매달 1,300유로씩."),
(D_, "Je note. Et le loyer courant, vous en parlez comment ?", "적어 두죠. 그럼 현재 임대료는 어떻게 하실 건가요?"),
(H, "J'y viens. Je finis d'abord avec les autres créanciers, si vous permettez.", "곧 말씀드리겠습니다. 허락하시면 다른 채권자들 얘기를 먼저 끝낼게요."),
(H, "Pour tous les autres : 76 400 €. Année un, rien. Puis un palier chaque année, qui monte doucement.", "나머지 전체는 76,400유로예요. 첫해는 없음. 그다음부터 해마다 한 단계씩 천천히 올라갑니다."),
(H, "Année deux, 8 000. Année trois, 9 000. Année quatre, 10 000. Année cinq, 11 000.", "2년 차 8,000. 3년 차 9,000. 4년 차 10,000. 5년 차 11,000."),
(H, "Année six, 12 000. Année sept, 13 000. Et année huit, 13 400.", "6년 차 12,000. 7년 차 13,000. 그리고 8년 차 13,400."),
(M, "Je vérifie. 8, 9, 10, 11, 12, 13 : ça fait 63 000. Plus 13 400 : 76 400. C'est exact.", "확인해 볼게요. 8, 9, 10, 11, 12, 13을 더하면 63,000. 여기에 13,400을 더하면 76,400. 정확합니다."),
(M, "Et 15 600 plus 76 400, ça fait bien 92 000. Le total est respecté.", "그리고 15,600에 76,400을 더하면 정확히 92,000이네요. 총액이 맞습니다."),
(B, "Et moi, avec mes 4 200, je touche quoi, madame la mandataire ?", "그럼 저는 4,200유로 중에서 얼마를 받습니까, 관재인님?"),
(M, "Votre part représente environ 5,5 % de la somme. Donc à peu près 440 € la deuxième année.", "당신 몫은 전체의 약 5.5퍼센트예요. 그러니까 2년 차에 대략 440유로입니다."),
(B, "440 ! Pour des légumes que j'ai arrachés il y a six mois !", "440이라니! 6개월 전에 뽑은 채소 값인데!"),
(H, "Je sais, monsieur Bastide. Vous m'avez fait confiance. Je vous le dois.", "알아요, 바스티드 씨. 저를 믿어 주셨죠. 갚아야 할 빚이에요."),
(B, "Huit ans... à la fin, je serai à la retraite. Et mes poules aussi !", "8년이라... 끝날 땐 저도 은퇴할 거예요. 제 닭들도요!"),
(H, "Je comprends. Laissez-moi une semaine pour vous faire une autre proposition. Rien que pour vous.", "이해해요. 일주일만 주세요. 바스티드 씨에게만 드리는 다른 제안을 준비할게요."),
(M, "C'est possible. Un créancier peut toujours accepter un calendrier plus court, s'il est écrit et déclaré.", "가능합니다. 채권자는 더 짧은 일정에 합의할 수 있어요. 서면으로 작성해 신고하면요."),
(B, "Une autre proposition ? D'accord. Mais si c'est encore « patience », je me fâche.", "다른 제안이요? 좋아요. 하지만 또 « 참고 기다려 달라 » 면 화낼 겁니다."),
(H, "Promis. Ce ne sera pas « patience ». Ce sera un vrai calendrier.", "약속할게요. « 기다려 달라 » 가 아닐 거예요. 진짜 일정표일 거예요."),
(D_, "Madame Marchand, parlons du loyer. Vous demandez quoi, exactement ?", "마르샹 씨, 임대료 얘기를 하죠. 정확히 뭘 요청하십니까?"),
(H, "Un geste. Revenir à 4 400 € pendant un an, le temps de remonter.", "배려 한 번이요. 1년만 4,400유로로 돌아가 주세요. 다시 일어설 때까지만요."),
(D_, "Je regrette, c'est non. Le loyer est à 5 200 € depuis le 1er octobre. Je ne le changerai pas.", "유감이지만 안 됩니다. 임대료는 10월 1일부터 5,200유로예요. 바꾸지 않을 겁니다."),
(H, "Mais c'est 37 % d'augmentation, monsieur ! Vous vous en rendez compte ?", "하지만 37퍼센트 인상이에요, 선생님! 실감하세요?"),
(D_, "Je m'en rends compte, madame. Les loyers de la rue ont monté. Je suis au prix du marché.", "실감합니다. 이 거리의 임대료가 올랐어요. 저는 시세에 맞췄을 뿐입니다."),
(H, "Le quartier a changé, peut-être. Mes clients, eux, n'ont pas changé.", "동네는 변했을지 몰라도 제 손님들은 그대로예요."),
(D_, "Possible. Mais j'ai des obligations, moi aussi. Mon fils veut que je mette de l'ordre dans notre patrimoine.", "그럴 수 있죠. 하지만 저도 의무가 있습니다. 아들이 우리 자산을 정리하길 원해요."),
(M, "Monsieur Delmas, un point de droit. Pour les loyers d'avant le jugement, vous ne pouvez pas demander la résiliation du bail.", "델마스 씨, 법적으로 하나만요. 판결 이전 임대료 때문에 임대차 해지를 요구하실 수는 없습니다."),
(D_, "Je le sais, madame. Je ne cherche pas à mettre madame Marchand dehors. Je cherche à être payé.", "알고 있습니다. 마르샹 씨를 내쫓으려는 게 아니에요. 돈을 받으려는 겁니다."),
(M, "Alors voyons comment. Les 15 600 € sur douze mois, vous acceptez ?", "그럼 방법을 봅시다. 15,600유로를 12개월에 나누는 건 수락하십니까?"),
(D_, "J'accepte douze mois. Pas treize. À partir de janvier, 1 300 € par mois.", "12개월은 수락합니다. 13개월은 안 돼요. 1월부터 매달 1,300유로."),
(H, "Janvier à décembre. D'accord. Et le loyer courant, c'est promis.", "1월부터 12월까지. 좋습니다. 그리고 현재 임대료는 약속드릴게요."),
(D_, "Le 1er décembre, 5 200 €. Pas le 2. Pas le 5. Le 1er.", "12월 1일에 5,200유로. 2일도, 5일도 안 됩니다. 1일입니다."),
(H, "Le 1er. Je mets une alarme rouge sur mon téléphone.", "1일이요. 휴대폰에 빨간 알람을 걸어 둘게요."),
(D_, "Je ne peux pas faire plus, madame. Ce n'est pas personnel.", "더는 못 합니다. 개인적인 감정은 아니에요."),
(H, "Pour moi, si. Ma mère a payé ce loyer pendant trente ans.", "저한테는 개인적인 일이에요. 어머니가 30년 동안 이 임대료를 내셨어요."),
(D_, "Je m'en souviens. Elle faisait la meilleure blanquette du onzième. J'y déjeunais le jeudi, avec mon père.", "기억합니다. 11구에서 제일 맛있는 블랑케트를 하셨죠. 아버지와 목요일마다 점심을 먹었어요."),
(D_, "C'est pour ça que je suis venu en personne. Mais les chiffres sont les chiffres.", "그래서 직접 온 겁니다. 하지만 숫자는 숫자예요."),
(H, "Je comprends. Et moi, je tiendrai mes chiffres aussi.", "이해합니다. 저도 제 숫자를 지키겠습니다."),
(M, "Passons aux autres. J'ai les réponses écrites de l'URSSAF et du service des impôts.", "다른 채권자들로 넘어갑시다. URSSAF와 세무서의 서면 답변이 있어요."),
(M, "Les deux acceptent le principe d'un étalement sur huit ans. Aucun n'abandonne un seul euro.", "두 곳 모두 8년 분할 원칙은 받아들입니다. 하지만 단 1유로도 탕감하지 않아요."),
(H, "Pas un euro. D'accord. Je ne demandais pas de cadeau.", "1유로도요. 알겠어요. 선물을 바란 건 아니었어요."),
(M, "Pour les équipementiers : le fabricant du four demande des intérêts. Les autres disent oui, sans intérêts.", "설비업체는, 오븐 제조사가 이자를 요구합니다. 나머지는 이자 없이 동의했어요."),
(H, "Je suis prête à en discuter. Mais je ne signerai pas n'importe quoi.", "논의할 준비는 돼 있어요. 하지만 아무거나 서명하진 않을 겁니다."),
(B, "Et si vous payez pas, la deuxième année ? On fait quoi, nous ?", "그런데 2년 차에 못 내면요? 우리는 어떻게 하죠?"),
(M, "Bonne question. Si le plan n'est pas respecté, le tribunal peut le résoudre. Et alors, la liquidation menace.", "좋은 질문입니다. 계획을 지키지 않으면 법원이 계획을 취소할 수 있어요. 그러면 청산이 닥칩니다."),
(B, "Donc madame Marchand a intérêt à payer.", "그러니 마르샹 씨는 꼭 내야겠네요."),
(M, "Et vous avez intérêt à ce qu'elle réussisse. C'est tout l'enjeu.", "그리고 당신도 그녀가 성공하는 편이 이득이죠. 그게 핵심이에요."),
(H, "Je ne promets que ce que je peux tenir. C'est pour ça que les paliers montent doucement.", "저는 지킬 수 있는 것만 약속해요. 그래서 단계가 천천히 오르는 거예요."),
(H, "Je préfère 8 000 que je paie, que 12 000 que je rate.", "못 내는 12,000보다 꼭 내는 8,000이 낫습니다."),
(B, "Madame Marchand, je suis un paysan, mais je sais lire les chiffres. Vos 8 000, ça fait combien par mois ?", "마르샹 씨, 저는 농부지만 숫자는 읽을 줄 압니다. 그 8,000이면 한 달에 얼마죠?"),
(H, "8 000 divisé par douze : environ 667 € par mois. Et en année huit, 13 400 divisé par douze, ça fait environ 1 117.", "8,000을 12로 나누면 한 달에 약 667유로예요. 그리고 8년 차에는 13,400을 12로 나누면 약 1,117유로입니다."),
(D_, "Le loyer, 5 200 €, plus mes 1 300. Ça vous fait 6 500 € par mois en 2027.", "임대료 5,200유로에 제 몫 1,300을 더하면 2027년에는 매달 6,500유로가 됩니다."),
(H, "C'est ça. 6 500 € par mois pour vous. C'est lourd, mais je le sais.", "맞아요. 매달 6,500유로. 무겁지만 알고 있어요."),
(M, "Vos recettes actuelles permettent-elles de tenir ? Trente couverts le midi, vingt-huit le soir ?", "현재 매출로 버틸 수 있을까요? 점심 30명, 저녁 28명인데요."),
(H, "Pas avec ces chiffres. Mais jeudi, on lance un financement participatif : 40 000 € demandés.", "이 숫자로는 안 되죠. 하지만 목요일에 크라우드펀딩을 시작해요. 40,000유로를 요청합니다."),
(H, "On ferme trois semaines pour les travaux, du 22 novembre au 14 décembre. Puis on rouvre avec une carte de saison.", "공사 때문에 11월 22일부터 12월 14일까지 3주 문을 닫아요. 그리고 제철 메뉴로 다시 엽니다."),
(B, "Trois semaines fermés ? Et mes livraisons ?", "3주나 닫는다고요? 제 납품은요?"),
(H, "Rien à livrer pendant la fermeture. Mais je recommande dès la réouverture, c'est promis.", "휴업 중에는 납품할 게 없어요. 하지만 재개점하자마자 다시 주문할게요, 약속합니다."),
(B, "Bah, tant pis. Je dirai à mes poules de pondre d'avance.", "뭐, 어쩔 수 없죠. 닭들한테 미리 알 낳으라고 해야겠네요."),
(M, "Récapitulons pour le procès-verbal. Monsieur Delmas : douze mensualités de 1 300 €, loyer inchangé.", "회의록을 위해 정리하죠. 델마스 씨는 12개월 분할 1,300유로씩, 임대료는 그대로입니다."),
(M, "Monsieur Bastide : plan général, avec une contre-proposition à venir. URSSAF et impôts : accord de principe.", "바스티드 씨는 전체 계획에 더해 곧 역제안이 나옵니다. URSSAF와 세무서는 원칙적 동의입니다."),
(D_, "Je confirme. Ma lettre partira cette semaine.", "확인합니다. 제 서한은 이번 주에 보내겠습니다."),
(B, "Moi aussi, je confirme. Mais j'attends votre proposition, Hélène. Une semaine.", "저도 확인합니다. 하지만 당신의 제안을 기다리겠어요, 엘렌. 일주일요."),
(H, "Vendredi. Je vous appelle vendredi.", "금요일에요. 금요일에 전화드릴게요."),
(M, "Prochaines étapes : vos créanciers déclarent leurs créances avant la mi-janvier. Le tribunal examinera le plan en mai.", "다음 단계입니다. 채권자들은 1월 중순 전에 채권을 신고합니다. 법원은 5월에 계획을 심사해요."),
(H, "Le 12 mai, la fin de la période d'observation. Ça me laisse six mois pour prouver que ça marche.", "5월 12일이 관찰 기간이 끝나는 날이죠. 잘 돌아간다는 걸 증명할 시간이 6개월 있는 거예요."),
(D_, "Madame Marchand, je dois y aller. J'ai un rendez-vous à seize heures. Merci pour le café.", "마르샹 씨, 가 봐야겠습니다. 4시에 약속이 있어서요. 커피 감사합니다."),
(H, "Merci d'être venu en personne, monsieur Delmas. Je l'ai remarqué.", "직접 와 주셔서 감사합니다, 델마스 씨. 알아봤어요."),
(D_, "Bon courage, madame. Sincèrement.", "힘내세요, 마르샹 씨. 진심입니다."),
(None, "M. Delmas sort. Bastide reste un moment près de la porte, son sac sur l'épaule.", "델마스 씨가 나간다. 바스티드 씨는 어깨에 가방을 멘 채 잠시 문 옆에 머문다."),
(B, "Il est dur, le proprio. Mais il a bien mangé chez Marthe, ça, il l'a pas oublié.", "집주인 참 매정하네요. 그래도 마르트네 집에서 잘 먹었던 건 잊지 않았나 봐요."),
(H, "Oui. Mais ça ne baisse pas le loyer.", "네. 그래도 임대료는 안 내려가요."),
(B, "Non. Mais ça compte, un homme qui s'en souvient.", "그렇죠. 하지만 기억하는 사람이라는 게 의미는 있어요."),
(B, "Bon, je file. Pour vendredi, j'ai une idée. Pas que pour vous : pour moi aussi.", "자, 저는 가 볼게요. 금요일 건은 생각이 하나 있어요. 당신만을 위한 게 아니라 저를 위한 것이기도 해요."),
(H, "Une idée ? Racontez-moi.", "생각이요? 얘기해 주세요."),
(B, "Pas aujourd'hui. J'ai des copains producteurs, c'est tout ce que je dis. À vendredi, ma p'tite Hélène.", "오늘은 안 돼요. 생산자 친구들이 있다, 그것만 말해 둘게요. 금요일에 봐요, 우리 엘렌."),
(H, "À vendredi, monsieur Bastide. Et merci pour les poireaux.", "금요일에 뵐게요, 바스티드 씨. 대파 고마워요."),
(None, "La porte se referme. Mme Lemaire range ses dossiers. Hélène souffle enfin.", "문이 닫힌다. 르메르 관재인이 서류를 정리한다. 엘렌이 마침내 숨을 내쉰다."),
(M, "Vous avez bien tenu, madame Marchand. Un seul créancier n'a pas bougé, et c'était le plus attendu.", "잘 버티셨어요, 마르샹 씨. 움직이지 않은 채권자는 한 명뿐이었고, 그게 가장 예상된 사람이었죠."),
(H, "Delmas. Il n'a pas bougé d'un millimètre sur le loyer.", "델마스 씨요. 임대료에 대해서는 1밀리미터도 안 움직였어요."),
(M, "Mais il a accepté douze mois. Je craignais six.", "하지만 12개월은 받아들였죠. 저는 6개월일까 봐 걱정했어요."),
(H, "Alors... putain, enfin quelque chose qui avance. Pardon, madame.", "그럼... 젠장, 드디어 뭔가 앞으로 나가네요. 죄송해요, 관재인님."),
(M, "Aucun problème. J'en entends d'autres. À bientôt, madame Marchand.", "괜찮습니다. 더한 말도 듣는걸요. 곧 다시 뵙겠습니다, 마르샹 씨."),
]

VOCAB = [
("A2", "Installez-vous.", "앉으세요(편히 자리 잡으세요).", "손님·방문객에게 정중하게. 구어 ↔ 정중: « Assieds-toi » ↔ « Installez-vous, je vous en prie »."),
("B1", "pile à l'heure", "정각에", "[구어] « Vous êtes pile à l'heure. » ↔ 정중: « Vous êtes ponctuel. » pile = 딱, 정확히."),
("B1", "faire le déplacement", "직접 오다(수고를 들여 이동하다)", "« Merci d'avoir fait le déplacement. » 상대가 직접 와 준 데 감사할 때."),
("B1", "au cas où", "혹시 몰라서", "« J'ai fait du café, au cas où. » 뒤에 명사나 절 없이 단독으로 쓸 수 있다."),
("B1", "un geste", "배려, 양보(상대를 위한 성의 표시)", "« Je demande un geste. » 임대료·가격 협상에서 '한 번 봐주기'. 완곡하고 존중하는 표현."),
("B1", "chacun à son tour", "각자 차례대로", "« Chacun parle à son tour. » 회의 규칙을 알릴 때."),
("B2", "un créancier / une créance", "채권자 / 채권(받을 돈)", "« Je dois 92 000 euros à une quinzaine de créanciers. » 반대는 un débiteur(채무자)."),
("B2", "une mensualité", "월 분할금", "« douze mensualités de 1 300 € ». 매달 내는 일정 금액."),
("B2", "un étalement / étaler", "분할(기간을 늘려 나눔)", "« un étalement sur huit ans ». 빚을 여러 해에 나누어 갚다."),
("B2", "un accord de principe", "원칙적 동의", "세부는 아직 정하지 않았지만 큰 틀에는 동의. « URSSAF et impôts : accord de principe. »"),
("B2", "abandonner une créance", "채권을 포기(탕감)하다", "« Aucun n'abandonne un seul euro. » 빚 일부를 깎아 주는 것."),
("B2", "le loyer courant", "현재 임대료(당월·앞으로 내는 임대료)", "« Et le loyer courant ? » 과거 연체분(arriéré)과 구별."),
("B2", "un palier", "단계(계단식 구간)", "« un palier chaque année, qui monte doucement ». 금액을 단계별로 올리는 방식."),
("B2", "recueillir les positions", "입장을 청취하다", "« Mon rôle est de recueillir vos positions. » 중립적 중재자의 말. ↔ 일상: « écouter ce que chacun pense »."),
("B2", "Le compte est bon.", "계산이 맞다.", "« Le compte est bon. C'est rare… » 계산이 정확하다는 뜻. 유사: « Ça tombe juste. »"),
("C1", "la résiliation du bail", "임대차 해지", "« vous ne pouvez pas demander la résiliation du bail ». 법적으로 보호 개시 전 연체로는 해지 불가."),
("C1", "résoudre un plan", "계획을 취소(해제)하다", "« le tribunal peut le résoudre ». 계획을 어기면 법원이 효력을 없앨 수 있고 청산 위험이 생긴다."),
("C1", "une contre-proposition", "역제안", "« une contre-proposition à venir ». 상대 제안에 대한 수정안."),
("C1", "Les chiffres sont les chiffres.", "숫자는 숫자다(협상의 여지가 없다).", "냉정한 마무리 표현. 개인 감정과 거리를 둘 때. « Ce n'est pas personnel. »과 함께 쓴다."),
("C1", "Je ne cherche pas à…, je cherche à…", "…하려는 게 아니라 …하려는 것이다", "« Je ne cherche pas à mettre madame Marchand dehors. Je cherche à être payé. » 의도를 대비해 분명히 할 때."),
("C1", "tenir ses chiffres / tenir un engagement", "수치(약속)를 지키다", "« Je tiendrai mes chiffres aussi. » tenir = 이행하다. 약속·계획·예산에 쓴다."),
("C1", "avoir intérêt à", "…하는 편이 이득이다", "« Elle a intérêt à payer. » 경고·조언 양쪽에 쓰인다. 구어 ↔ 정중: « Il vaut mieux que… »."),
("C1", "une quinzaine de", "열다섯 정도의", "« une quinzaine de créanciers ». -aine 은 대략의 수를 뜻함: une dizaine, une vingtaine, une trentaine."),
("C1", "mettre de l'ordre dans le patrimoine", "자산을 정리하다", "« Mon fils veut que je mette de l'ordre dans notre patrimoine. » 상속·재산 정리의 완곡한 표현. 접속법 « que je mette »."),
]

GRAM = [
("B2", "숫자·퍼센트·나눗셈을 말로 풀기", "계산은 이렇게 읽습니다. « 92 000 divisé par 8, ça fait 11 500 par an. » « 15 600 plus 4 200, ça fait combien ? » « 37 % d'augmentation », « environ 5,5 % ». 'A plus B', 'A moins B', 'A fois B', 'A divisé par B, ça fait C'. 어림은 « environ », « à peu près », « un peu plus de »."),
("B2", "si + 현재, 현재/미래: 조건 약속", "« Je peux tout rembourser, si on me laisse du temps. » « Si le plan n'est pas respecté, le tribunal peut le résoudre. » si 절은 현재형, 주절은 현재·미래·명령형. 가정의 반대형인 « si + 반과거, 조건법 » 과 구분하세요."),
("B2", "대비 구문: « Je ne cherche pas à A, je cherche à B »", "의도를 분명히 할 때 쓰는 두 문장 구조입니다. « Je ne cherche pas à mettre madame Marchand dehors. Je cherche à être payé. » « Ce n'est pas personnel. » 부정 → 긍정 순서로 짧게 끊어 말하면 구어 리듬이 살아납니다."),
("B2", "이중 대명사: « Je vous le dois », « Laissez-moi une semaine »", "« Je vous le dois. » 는 vous(상대에게) + le(그 빚을). « Je m'en rends compte », « Je m'en souviens » 처럼 se rendre compte de / se souvenir de 는 en 으로 받습니다. 순서는 me/te/nous/vous → le/la/les → lui/leur → y → en."),
("B1", "미래형·현재형으로 하는 약속", "« Je tiendrai mes chiffres. » « Je vous appelle vendredi. » 구어에서는 가까운 미래를 현재형으로 말해도 약속이 됩니다. « Ma lettre partira cette semaine. » 는 미래형으로 격식을 더합니다."),
("C1", "완곡한 거절과 단호한 마무리", "« Je regrette, c'est non. » « Je ne peux pas faire plus. » « Ce n'est pas personnel. » 먼저 유감(je regrette)을 말한 뒤 결론을 짧게 붙입니다. 반대로 단호한 표현은 반복으로: « Pas le 2. Pas le 5. Le 1er. »"),
("C1", "접속법: « Mon fils veut que je mette… »", "vouloir que, il faut que, avoir peur que 다음에는 접속법. « Mon fils veut que je mette de l'ordre dans notre patrimoine. » mettre → que je mette. 같은 주어이면 부정사: « Je veux mettre de l'ordre. »"),
]

READ = [
("큰 수 읽기 — 92 000 / 15 600 / 1 300", "« 92 000 € » 는 quatre-vingt-douze mille euros, « 15 600 € » 는 quinze mille six cents euros, « 1 300 € » 는 mille trois cents euros. mille 는 복수 -s 가 없고, cent 은 뒤에 숫자가 없으면 cents. 천 단위에서 호흡을 한 번 쉽니다: « quatre-vingt-douze mille / euros ». "),
("퍼센트와 소수 — 37 % / 5,5 %", "« 37 % » 는 trente-sept pour cent, « 5,5 % » 는 cinq virgule cinq pour cent. 소수점은 쉼표(virgule)로 읽고 그 앞에서 짧게 쉬어 줍니다."),
("나열 억양 — Année deux, 8 000.", "« Année deux, / 8 000. Année trois, / 9 000. Année quatre, / 10 000. » 목록의 중간 항목은 끝을 올려 '아직 계속된다' 를 표시하고, 마지막 « Et année huit, / 13 400. » 에서 내립니다."),
("리에종 — huit ans / douze mois", "« Huit ans » 는 huit 의 t 가 이미 발음되어 [ɥi‿tɑ̃] 처럼 이어집니다. « douze mois » 의 z 는 [duz mwa] 로 소리가 이어지며 « pas treize » 와 대비하세요. « J'accepte / douze mois. / Pas treize. » "),
("단호한 문장의 속도와 휴지", "« Le 1er décembre, / 5 200 €. / Pas le 2. / Pas le 5. / Le 1er. » 짧게 끊어서 같은 억양으로 반복하고, 마지막 « Le 1er. » 에서 가장 낮게 내려갑니다. 델마스의 위엄이 느껴지도록 천천히."),
("r 소리 — créancier, mandataire", "« créancier » 의 첫 r 은 크레-앙-시에 앞에서 가볍게. « mandataire » 의 마지막 -aire 는 [mɑ̃datɛʁ]. « Un créancier / peut toujours accepter / un calendrier plus court. » 로 호흡 구간을 나누세요."),
("정중한 반론의 톤", "« Je regrette, / c'est non. » « Je ne peux pas faire plus, madame. / Ce n'est pas personnel. » 목소리를 높이지 않고 낮고 평평하게 말하는 것이 정중한 단호함입니다. 반대로 엘렌의 « Pour moi, si. » 는 살짝 힘을 줍니다."),
]

CULTURE = [
("채권자와의 협의 — 누구도 공짜로 깎아 주지 않는다", "프랑스 회생 절차(sauvegarde)에서는 관재인(mandataire)이 채권자들의 입장을 듣고 상환 계획안을 다듬습니다. 세무서와 사회보험(URSSAF)은 분할(étalement)은 받아도 원금 탕감(abandon de créance)은 거의 하지 않는 것이 보통입니다. 반면 소규모 납품업자는 오래된 관계 때문에 더 유연한 합의를 해 주기도 합니다."),
("Le bail commercial 3-6-9 — 상가 임대차의 규칙", "프랑스 상가 임대차(bail commercial)는 보통 9년이며 임차인이 3년마다 해지할 수 있다는 의미로 '3-6-9' 라고 부릅니다. 임대료 인상은 일정 기준에 따라 이루어지지만, 회생 절차가 열리면 임대인은 개시 전 임대료 연체만으로는 계약을 해지할 수 없습니다. 대신 개시 후의 임대료는 날짜대로 내야 합니다. 델마스 씨가 « Le 1er. » 라고 강조한 이유입니다."),
]

META = dict(part=4, ep=47, part_label="제4부 La reconstruction · 늦가을·겨울", title_fr="Les créanciers", title_ko="채권자들",
 place="Le Comptoir de Marthe, 11월 16일 월요일(휴무일) 오후 1시 45분 ~ 3시 30분 무렵",
 chars="Hélène Marchand (주인 셰프) · Mme Lemaire (법원 지정 관재인) · M. Delmas (건물주) · M. Bastide (납품업자)",
 wine="채무 92 000 € = 델마스 15 600 €(12개월 분할, 월 1 300 €) + 나머지 76 400 €(8년, 1년 거치 후 단계 상승).",
 focus="협상·양보 표현, 숫자와 퍼센트 읽기, si 조건, 대비 구문(Je ne cherche pas à…), 완곡한 거절",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제48화 « Le financement participatif » : 11월 19일 목요일, 엘렌은 카메라 앞에 서서 40 000 € 크라우드펀딩 호소 영상을 찍는다.")
