# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, L = "Hélène", "Julien", "Chloé", "Lucien"
D = [
(None, "Jeudi 19 novembre, 15 h 10. La salle est vide après le déjeuner. Un trépied, une lumière ronde, le comptoir en arrière-plan. Chloé règle son téléphone. Julien tient des fiches. Lucien s'est installé au bar. Hélène, en veste de cuisine repassée, se tient raide.", "11월 19일 목요일 오후 3시 10분. 점심 뒤라 홀이 텅 비어 있다. 삼각대, 동그란 조명, 배경에는 카운터. 클로에가 휴대폰을 맞춘다. 줄리앙은 카드를 들고 있다. 뤼시앙은 바에 자리 잡았다. 다림질한 조리복을 입은 엘렌은 뻣뻣하게 서 있다."),
(C, "Bon, le téléphone est calé. La lumière, ça va ? Dis-moi si tu es éblouie.", "자, 휴대폰 고정했어요. 조명은 괜찮아요? 눈부시면 말해 줘요."),
(H, "Je suis éblouie. Et je transpire. Je déteste les caméras.", "눈부셔. 그리고 땀나. 난 카메라가 싫어."),
(J, "Tu détestes les caméras, mais tu cuisines devant quarante clients tous les soirs.", "카메라는 싫다면서, 매일 저녁 손님 마흔 명 앞에서 요리하잖아."),
(H, "Les clients regardent mon assiette. Pas ma tête.", "손님들은 내 접시를 보지, 내 얼굴을 보지 않아."),
(L, "Moi, je regarde ta tête, ma fille. Elle est très bien. Tu as le nez de ta mère.", "난 네 얼굴을 보는데, 얘야. 아주 좋아. 네 엄마 코를 닮았구나."),
(H, "Papa, s'il te plaît. Pas aujourd'hui.", "아빠, 제발요. 오늘은 안 돼요."),
(L, "Bon, bon. Je me tais. Je suis un mur.", "알았다, 알았어. 입 다물게. 난 벽이야."),
(J, "Reprenons les chiffres, que tout le monde les ait en tête. On demande 40 000 €, en trente jours.", "숫자를 다시 정리하자, 다들 머릿속에 있게. 30일 동안 40,000유로를 요청해."),
(C, "Et c'est « tout ou rien », c'est ça ? Si on n'atteint pas 40 000, on ne reçoit rien ?", "그리고 « 전부 아니면 전무 » 방식이죠? 40,000을 못 채우면 한 푼도 못 받는 거고요?"),
(J, "Exact. Les gens sont remboursés. Ça les rassure, mais ça nous met la pression.", "맞아. 후원자들은 환불받아. 그들은 안심하지만 우리는 압박을 받지."),
(H, "Et la plateforme prend combien ?", "그리고 플랫폼은 얼마를 떼 가?"),
(J, "Sept pour cent : cinq pour la plateforme, deux pour le paiement en ligne.", "7퍼센트야. 플랫폼 5, 온라인 결제 2."),
(C, "Sept pour cent de 40 000, ça fait 2 800. Donc il nous reste 37 200.", "40,000의 7퍼센트면 2,800이니까 우리 손에는 37,200이 남아요."),
(H, "37 200. Les travaux, la remise aux normes, un peu de trésorerie. Ça tient.", "37,200. 공사, 기준 맞추기, 약간의 운영 자금. 맞아떨어지네."),
(J, "Et les contreparties. À 20 € : ton nom à la craie sur l'ardoise.", "그리고 보상이야. 20유로면 칠판에 분필로 이름을 써 줘."),
(C, "À 50 € : un bon pour un repas, d'une valeur de 60 €. À 150 € : un dîner pour deux, avec le vin.", "50유로면 60유로 상당의 식사권. 150유로면 와인 포함 2인 저녁 식사요."),
(L, "Et à 500 € : une tablée pour huit, avec le vieux Lucien qui raconte ses histoires.", "그리고 500유로면 여덟 명 단체석, 늙은 뤼시앙이 옛날이야기를 해 주고."),
(H, "Papa, c'est pas dans le programme.", "아빠, 그건 계획에 없어요."),
(L, "Maintenant, si. Tu verras, ce sera la contrepartie la plus demandée.", "이제 있다. 두고 봐라, 가장 인기 있는 보상이 될 거야."),
(J, "Ha ! Il n'a pas tort. Les gens adorent les anecdotes. On le note.", "하! 틀린 말은 아니야. 사람들은 일화를 좋아하거든. 적어 두자."),
(C, "Hélène, tu as appris ton texte ?", "엘렌, 대본 외웠어요?"),
(H, "J'ai écrit un discours. Deux pages. Je le sais presque par cœur.", "연설문을 썼어. 두 쪽. 거의 다 외웠어."),
(J, "Deux pages ? Une vidéo de financement participatif, ça dure deux minutes. Trois, maximum.", "두 쪽이라고? 크라우드펀딩 영상은 2분이야. 길어야 3분."),
(H, "Alors je coupe. Je commence par « Chers amis »...", "그럼 줄일게. « 친애하는 여러분 » 으로 시작하고..."),
(J, "Pas « Chers amis ». Tu n'es pas ministre.", "« 친애하는 여러분 » 은 안 돼. 장관이 아니잖아."),
(C, "Prise un. Moteur... ça tourne !", "첫 번째 테이크. 레디... 돌아가요!"),
(H, "Chers amis, je me permets de vous écrire pour solliciter votre soutien financier dans une période de difficulté.", "친애하는 여러분, 어려운 시기에 재정적 지원을 부탁드리고자 감히 글을 올립니다."),
(C, "Coupez ! Hélène, on dirait une lettre de la banque.", "컷! 엘렌, 은행 편지 같아요."),
(J, "Moi, j'ai failli m'endormir. Et j'étais debout.", "난 졸 뻔했어. 서 있는데도."),
(H, "C'est pas drôle. Je fais ce que je peux.", "웃기지 않아. 난 최선을 다하고 있어."),
(L, "Ma fille, quand tu parlais aux clients en cuisine, tu parlais comment ?", "얘야, 주방에서 손님들한테 말할 때는 어떻게 말했니?"),
(H, "Normalement. Avec des gestes, des blagues.", "평범하게요. 손짓도 하고 농담도 하고."),
(L, "Alors fais pareil. Imagine que Mme Vasseur est assise devant toi.", "그럼 똑같이 해. 바쉐 부인이 네 앞에 앉아 있다고 상상해 봐."),
(H, "Mme Vasseur me dirait de parler plus fort et de sourire. D'accord.", "바쉐 부인이라면 더 크게 말하고 웃으라고 하겠죠. 알았어요."),
(J, "Autre truc. Pose-leur des questions. Une question, ça réveille. Les gens répondent dans leur tête.", "다른 요령. 질문을 던져. 질문은 사람을 깨워. 사람들이 속으로 대답하거든."),
(C, "Comme : « Vous vous souvenez de votre premier repas ici ? »", "예를 들면, « 여기서 처음 먹은 식사를 기억하세요? » 같은 거요."),
(J, "Voilà. Ça crée un lien.", "그거야. 유대감이 생기지."),
(H, "Une question rhétorique, quoi.", "수사 질문이란 거네."),
(C, "Une quoi ? Attends, je le note dans mon carnet. Comment ça s'écrit ?", "뭐라고요? 잠깐, 수첩에 적을게요. 어떻게 쓰죠?"),
(H, "Rhé-to-ri-que. C'est une question où on n'attend pas de réponse. On la pose pour faire réfléchir.", "r-h-é-t-o-r-i-q-u-e. 답을 기대하지 않는 질문이야. 생각하게 만들려고 던지는 거지."),
(C, "Noté. Prise deux. Ça tourne.", "적었어요. 두 번째 테이크. 돌아가요."),
(H, "Bonjour. Je m'appelle Hélène. Je suis cheffe. Euh... je suis cheffe... et... je ne sais plus.", "안녕하세요. 저는 엘렌입니다. 셰프예요. 어... 셰프고... 그리고... 모르겠어요."),
(C, "Coupez. On respire. Cinq secondes de silence.", "컷. 숨 쉬어요. 5초간 침묵."),
(H, "Putain, je suis nulle.", "젠장, 난 형편없어."),
(L, "Tu n'es pas nulle. Tu es émue. C'est différent.", "형편없는 게 아니야. 감동해서 그런 거지. 달라."),
(J, "Il a raison. Une cheffe émue, ça touche plus qu'une cheffe parfaite.", "맞아. 감정이 북받친 셰프가 완벽한 셰프보다 더 마음을 울려."),
(H, "Tu dis ça pour me rassurer.", "날 안심시키려고 하는 말이지."),
(J, "Je dis ça parce que c'est vrai. Prise trois, Chloé.", "사실이라서 하는 말이야. 세 번째 테이크, 클로에."),
(C, "Prise trois. Ça tourne.", "세 번째 테이크. 돌아가요."),
(H, "Vous savez ce que c'est, un comptoir ? C'est l'endroit où on s'accoude. Où on parle. Où on se sent chez soi.", "카운터가 뭔지 아세요? 팔꿈치를 괴는 곳이죠. 이야기하는 곳. 내 집처럼 느끼는 곳."),
(C, "C'était bien ! Mais il y a un bruit de machine à café.", "좋았어요! 근데 커피 머신 소리가 나요."),
(L, "Pardon, c'est moi. J'avais soif.", "미안, 나다. 목이 말라서."),
(J, "Lucien ! Tu t'assois au fond. En silence.", "뤼시앙! 안쪽에 앉아 계세요. 조용히."),
(L, "Un café, c'est un droit de l'homme, mon garçon.", "커피는 인간의 권리란다, 젊은이."),
(H, "Un mur avec une machine à café, c'est nouveau.", "커피 머신 달린 벽이라니, 처음 보네."),
(C, "Prise quatre. Cette fois, tout le monde se tait. Ça tourne.", "네 번째 테이크. 이번엔 모두 조용히. 돌아가요."),
(H, "Vous savez ce que c'est, un comptoir ? C'est l'endroit où on s'accoude, où on parle, où on se sent chez soi.", "카운터가 뭔지 아세요? 팔꿈치를 괴고, 이야기하고, 내 집처럼 느끼는 곳이에요."),
(H, "Le nôtre a trente-cinq ans. Ma mère, Marthe, l'a ouvert avec mon père en 1991.", "우리 카운터는 35년 됐어요. 어머니 마르트가 아버지와 함께 1991년에 열었죠."),
(C, "Coupez ! Super, on a le début. Ton visage est parfait.", "컷! 좋아요, 도입부는 건졌어요. 표정이 완벽해요."),
(H, "Aujourd'hui, il est en danger. Je ne vais pas vous mentir : le loyer a explosé, les clients sont moins nombreux, on a des dettes.", "오늘 이 카운터는 위기에 처했습니다. 거짓말하진 않을게요. 임대료가 폭등했고, 손님은 줄었고, 빚이 있습니다."),
(H, "Mais un tribunal nous protège six mois. On a un plan. On va tout rembourser, mais on a besoin de vous.", "하지만 법원이 6개월 동안 우리를 보호해 줍니다. 계획도 있어요. 전부 갚을 거예요. 다만 여러분이 필요합니다."),
(J, "Coupez ! Excellent. Mais « tribunal », ça peut faire peur. Tu peux dire « procédure de protection » ?", "컷! 훌륭해. 근데 « 법원 » 은 무섭게 들릴 수 있어. « 보호 절차 » 라고 하면 어때?"),
(H, "Je préfère la vérité. Je dis « sauvegarde ». Les gens comprennent mieux qu'on ne croit.", "난 진실이 좋아. « 회생(소생) 절차 » 라고 말할래. 사람들은 생각보다 잘 이해해."),
(J, "D'accord. C'est ton histoire, c'est toi qui décides.", "알았어. 네 이야기니까 네가 결정해."),
(C, "Prise cinq. Ça tourne.", "다섯 번째 테이크. 돌아가요."),
(H, "Qu'est-ce qu'on perd quand un comptoir disparaît ? Une adresse. Un plat. Un voisin qui vous dit bonjour.", "카운터가 사라지면 우리는 무엇을 잃을까요? 주소 하나. 요리 하나. 인사해 주던 이웃 한 사람."),
(L, "C'est beau, ça...", "아름답구나, 그건..."),
(C, "Chut, Lucien ! On est en prise !", "쉿, 뤼시앙! 촬영 중이에요!"),
(L, "Pardon, pardon.", "미안, 미안."),
(H, "Alors voilà ce que je vous demande. 40 000 euros, en trente jours.", "그래서 여러분께 부탁드립니다. 30일 동안 40,000유로."),
(H, "Avec ça, on rénove la cuisine, on remet la salle en état, et on rouvre le 15 décembre.", "그 돈으로 주방을 고치고, 홀을 정비하고, 12월 15일에 다시 엽니다."),
(H, "En échange, votre nom à la craie sur notre ardoise. Un repas offert. Une soirée avec nous.", "그 대신 우리 칠판에 여러분 이름을 분필로 쓰고, 식사 한 번, 저희와의 저녁 한 번을 드립니다."),
(H, "Et surtout, vous aurez sauvé un petit bout de Paris. Vous voyez ce que je veux dire ?", "무엇보다 파리의 작은 한 조각을 지켜 낸 거예요. 무슨 말인지 아시겠죠?"),
(J, "Coupez ! C'est ça. C'est exactement ça. Chloé, tu as le son ?", "컷! 바로 그거야. 정확히 그거야. 클로에, 소리 괜찮아?"),
(C, "Le son est propre. L'image aussi. Et on a une larme à la fin.", "소리 깨끗해요. 화면도요. 그리고 마지막에 눈물 한 방울이 나왔어요."),
(H, "Une larme ? Efface-la !", "눈물? 지워 줘!"),
(J, "Surtout pas. C'est ce qui rend la vidéo vraie.", "절대 안 돼. 그게 영상을 진짜로 만드는 거야."),
(H, "Bon. Dernière chose : la fin. Comment je termine ?", "좋아. 마지막으로, 끝맺음. 어떻게 끝낼까?"),
(J, "Une phrase courte. Directe. Pas un discours. Quelque chose qu'on a envie de répéter.", "짧은 문장. 직설적으로. 연설 말고. 따라 하고 싶어지는 말로."),
(H, "« Alors, vous venez nous donner un coup de main ? » Ça va ?", "« 그래서, 와서 우리를 도와주시겠어요? » 이거 괜찮아?"),
(C, "Parfait ! Juste un peu plus de sourire.", "완벽해요! 웃음만 조금 더요."),
(H, "Je souris ! Tu ne vois pas que je souris ?", "웃고 있잖아! 웃는 거 안 보여?"),
(C, "Ça ressemble à une grimace. Pense à... une tarte Tatin !", "찡그린 얼굴 같아요. 생각해 봐요... 타르트 타탱!"),
(H, "Une tarte Tatin ? Ha ! D'accord, voilà, c'est mieux.", "타르트 타탱? 하! 알겠어, 이제 좀 낫지."),
(C, "Prise six. Ça tourne.", "여섯 번째 테이크. 돌아가요."),
(H, "Alors, vous venez nous donner un coup de main ? Cliquez sur le lien, partagez la vidéo, parlez-en à vos voisins.", "그래서, 와서 도와주시겠어요? 링크를 누르고, 영상을 공유하고, 이웃에게 알려 주세요."),
(H, "Le Comptoir de Marthe a besoin de vous. Et nous, on a hâte de vous recevoir. Merci.", "르 콩투아르 드 마르트에는 여러분이 필요합니다. 저희는 여러분을 모실 날이 기다려져요. 감사합니다."),
(C, "Coupez ! C'est dans la boîte !", "컷! 촬영 끝났어요!"),
(J, "Bravo ! Applaudissements pour la patronne !", "브라보! 사장님께 박수!"),
(L, "Bravo, ma fille. Ta mère aurait pleuré. Et ensuite, elle t'aurait dit : « Redresse-toi. »", "잘했다, 얘야. 네 엄마는 울었을 거야. 그러고는 « 허리 펴라 » 했겠지."),
(H, "Papa ! Elle ne m'a jamais dit ça.", "아빠! 엄마가 저한테 그런 말 한 적 없어요."),
(L, "Elle me le disait à moi. Ça revient au même.", "나한테 그랬지. 마찬가지잖니."),
(J, "Allez, on monte la vidéo ce soir et on lance la page à dix-huit heures.", "자, 오늘 저녁에 영상을 편집하고 6시에 페이지를 열자."),
(C, "Je m'en occupe. Sous-titres, musique, tout. Vous allez voir.", "제가 할게요. 자막, 음악, 전부요. 기대하세요."),
(H, "Merci, Chloé. Tu as mis le paquet pour ce projet.", "고마워, 클로에. 이 프로젝트에 정말 공을 들였구나."),
(C, "C'est aussi mon restaurant, Hélène. Enfin... un peu.", "저한테도 이 식당은 우리 가게예요, 엘렌. 음... 조금은요."),
(None, "Même jour, 22 h 40. La page est en ligne depuis 18 h. Dans la cuisine éclairée, Julien rafraîchit l'écran de l'ordinateur. Hélène regarde par-dessus son épaule, sans oser respirer.", "같은 날 밤 10시 40분. 6시부터 페이지가 열려 있다. 불이 켜진 주방에서 줄리앙이 컴퓨터 화면을 새로고침한다. 엘렌은 숨도 못 쉬고 어깨 너머로 본다."),
(J, "Hélène... Viens voir. Ne t'assois pas, viens voir.", "엘렌... 와서 봐. 앉지 말고 와서 봐."),
(H, "Dis-moi. Dis-moi tout de suite, je ne peux pas attendre.", "말해 줘. 바로 말해 줘, 기다릴 수 없어."),
(J, "3 200 euros. En quatre heures et demie.", "3,200유로. 네 시간 반 만에."),
(H, "3 200... Tu es sûr ? Montre-moi.", "3,200... 확실해? 보여 줘."),
(C, "Quatre-vingts contributeurs. 40 € de moyenne. Je viens de refaire le calcul trois fois.", "후원자 80명, 평균 40유로예요. 방금 세 번이나 다시 계산했어요."),
(H, "Quatre-vingts personnes... qui ne me connaissent pas, pour certaines.", "80명... 그중 몇 명은 나를 모르는 사람들인데."),
(J, "Et ça fait huit pour cent de l'objectif, le premier soir. Il en reste 36 800, sur vingt-neuf jours.", "그리고 첫날 저녁에 목표의 8퍼센트야. 남은 건 36,800이고 29일이 남았어."),
(C, "Soit environ 1 270 € par jour. C'est jouable. Il faut juste que la vidéo circule.", "하루에 약 1,270유로예요. 해 볼 만해요. 영상만 퍼지면 돼요."),
(H, "Vingt-neuf jours... Ça me paraît à la fois très long et très court.", "29일... 엄청 길면서도 엄청 짧게 느껴져."),
(H, "Je relaie tout demain, sur toutes les pages. Tu m'apprendras ?", "내일 모든 페이지에 다 공유할게. 방법 가르쳐 줄래?"),
(C, "Évidemment. C'est comme un mot de vocabulaire : on répète, et ça rentre.", "물론이죠. 어휘 하나 외우는 것과 같아요. 반복하면 들어와요."),
(J, "Regarde les commentaires. Le premier est de... Mme Vasseur !", "댓글 봐. 첫 번째가... 바쉐 부인이야!"),
(H, "Mme Vasseur ? Elle sait cliquer sur un lien ?", "바쉐 부인이? 링크를 누를 줄 아신다고?"),
(C, "C'est sa petite-fille qui l'a aidée. Elle a donné 100 €. Écoutez : « Ma table sept m'attend. »", "손녀가 도와줬대요. 100유로를 보내셨어요. 들어 보세요. « 제 7번 테이블이 기다리고 있어요. »"),
(H, "Putain... « Ma table sept m'attend. » Elle va me faire pleurer, celle-là.", "젠장... « 제 7번 테이블이 기다리고 있어요. » 이분 때문에 울겠어."),
(J, "Il y en a plein d'autres. Tiens : « Je viens depuis 2004. » « Pour les blanquettes de Marthe. »", "다른 것도 많아. 봐: « 2004년부터 다녔어요. » « 마르트의 블랑케트를 위해서. »"),
(H, "Je vais tous les lire. Chacun. Je veux écrire leurs noms moi-même, à la craie.", "전부 읽을 거야. 하나하나. 이름도 내가 직접 분필로 쓰고 싶어."),
(J, "Tous les matins, avant le service ?", "매일 아침, 영업 전에?"),
(H, "Tous les matins. Un nom, un merci. C'est la moindre des choses.", "매일 아침. 이름 하나에 감사 하나. 그 정도는 해야지."),
(L, "Je veux écrire le premier nom moi-même. Vasseur, avec deux s.", "첫 이름은 내가 직접 쓰고 싶구나. 바쉐, s가 두 개."),
(H, "D'accord, Papa. Le premier nom, c'est pour toi.", "알았어요, 아빠. 첫 이름은 아빠 몫이에요."),
(C, "Je vous prépare une feuille avec tous les contributeurs, par ordre d'arrivée.", "도착한 순서대로 모든 후원자 명단을 정리해 올게요."),
(H, "Merci. Trente jours, hein ? Et on y arrive.", "고마워. 30일, 그치? 그리고 해낼 거야."),
(L, "Une hirondelle ne fait pas le printemps, ma fille. Mais celle-là lui ressemble.", "제비 한 마리가 봄을 만들지는 못한단다, 얘야. 하지만 이 제비는 봄을 닮았구나."),
]

VOCAB = [
("A2", "Je déteste les caméras.", "나는 카메라가 싫다.", "[구어] 취향 표현. détester = 몹시 싫어하다. ↔ 정중: « Je n'aime pas être filmée. »"),
("B1", "caler (le téléphone)", "고정하다, 안정되게 놓다", "« Le téléphone est calé. » 촬영 전 장비를 안정시킬 때. 일상: « caler une table » (흔들리지 않게 괴다)."),
("B1", "être ému(e) / émue", "감동하다, 마음이 북받치다", "« Tu n'es pas nulle. Tu es émue. » 감정 때문에 말이 막힐 때."),
("B1", "donner un coup de main", "도와주다", "[구어] « Vous venez nous donner un coup de main ? » ↔ 정중: « Vous nous apporterez votre aide ? »"),
("B1", "avoir hâte de", "…가 몹시 기다려지다", "« Nous, on a hâte de vous recevoir. » 뒤에는 동사원형."),
("B1", "mettre le paquet", "전력을 쏟다, 공을 들이다", "[구어] « Tu as mis le paquet pour ce projet. » ↔ 정중: « Tu t'es énormément investie. »"),
("B2", "le financement participatif", "크라우드펀딩", "« Une vidéo de financement participatif. » 일반인의 소액 후원으로 자금을 모음. 구어: « une cagnotte »."),
("B2", "tout ou rien", "전부 아니면 전무(목표 미달 시 환불)", "« C'est tout ou rien, c'est ça ? » 목표 금액을 못 채우면 후원금은 환불된다."),
("B2", "une contrepartie", "보상(후원에 대한 답례)", "« les contreparties » : 이름, 식사권, 저녁 초대 등. 단어 구성: contre + partie."),
("B2", "un contributeur / une contributrice", "후원자", "« Quatre-vingts contributeurs. » 구어: « un donateur » 와 달리 보상을 받는 후원자를 뜻함."),
("B2", "une commission", "수수료", "« Sept pour cent : cinq pour la plateforme, deux pour le paiement en ligne. » 수수료율은 « pour cent »로 읽는다."),
("B2", "une question rhétorique", "수사 질문", "« Une question où on n'attend pas de réponse. » 청중을 생각하게 만드는 화법. « Vous savez ce que c'est, un comptoir ? »"),
("B2", "mettre la pression", "압박을 가하다", "[구어] « Ça nous met la pression. » ↔ 정중: « Cela nous met sous tension. » pression 은 구어에서 매우 자주."),
("B2", "ça tient (le budget tient)", "맞아떨어진다, 버틴다", "[구어] « 37 200. Ça tient. » 계산·계획이 앞뒤가 맞을 때."),
("B2", "relayer / partager", "공유하다, 퍼뜨리다", "« Je relaie tout demain. » « Partagez la vidéo. » SNS 용어. relayer = 다른 사람이 올린 걸 다시 전하다."),
("B2", "être éblouie", "눈이 부시다", "« Dis-moi si tu es éblouie. » éblouir = 눈부시게 하다, 감탄시키다. 조명·햇빛 상황."),
("C1", "solliciter un soutien", "지원을 요청하다(공식)", "« je me permets de vous écrire pour solliciter votre soutien » 편지체 문어. 영상에서는 « donner un coup de main » 처럼 구어로."),
("C1", "Je ne vais pas vous mentir.", "솔직히 말씀드리겠습니다.", "솔직함을 앞세워 신뢰를 얻는 표현. 호소 영상에서 효과적. ↔ 같은 뜻: « Je vais être honnête avec vous. »"),
("C1", "C'est dans la boîte.", "촬영이 끝났다(성공적으로 찍었다).", "[구어] 영화·영상 현장 표현. « Coupez ! C'est dans la boîte ! » 일이 잘 끝났을 때도 비유로."),
("C1", "une prise", "(촬영의) 테이크", "« Prise un », « prise six ». 촬영 시도 횟수. « Ça tourne » = 촬영 시작. « Coupez » = 컷."),
("C1", "toucher quelqu'un", "마음을 울리다", "« Une cheffe émue, ça touche plus qu'une cheffe parfaite. » toucher = 물리적 접촉뿐 아니라 감동시키다."),
("C1", "mettre en danger", "위험에 빠뜨리다", "« Aujourd'hui, il est en danger. » 사람·가게가 위협받는 상황. 수동: « être en danger »."),
("C1", "Une hirondelle ne fait pas le printemps.", "제비 한 마리가 봄을 만들진 않는다(한 번의 좋은 징조로 판단 말라).", "속담. 뤼시앙은 « Mais celle-là lui ressemble » 로 비튼다. 희망을 담은 반전."),
("C1", "la moindre des choses", "최소한의 도리", "« C'est la moindre des choses. » 감사를 표하는 건 당연하다는 의미. 겸손과 예의의 표현."),
]

GRAM = [
("B2", "수사 질문과 청중 호명", "« Vous savez ce que c'est, un comptoir ? » « Qu'est-ce qu'on perd quand un comptoir disparaît ? » 답을 기대하지 않고 던지는 질문입니다. 의문사 의문문은 구어에서 « Qu'est-ce que… » 형태가 많고, 질문 뒤에 짧은 문장 세 개를 병렬: « Une adresse. Un plat. Un voisin qui vous dit bonjour. »"),
("B2", "전위(dislocation)와 강조", "구어 연설에서는 주제를 앞이나 뒤로 빼서 강조합니다. « Vous savez ce que c'est, un comptoir ? » (주제를 뒤로) « Le nôtre a trente-cinq ans. » « Ce comptoir, il est en danger. » 쉼표 하나로 청중의 주의를 끕니다."),
("B2", "명령형과 대명사", "호소의 마무리는 명령형입니다. « Cliquez sur le lien, partagez la vidéo, parlez-en à vos voisins. » 긍정 명령에서는 대명사가 동사 뒤: « parlez-en », « Dis-moi ». 부정 명령에서는 앞: « Ne t'assois pas ». « Efface-la ! » « Surtout pas. »"),
("B2", "si + 반과거, 조건법 / 조건법 과거 가정", "« Ta mère aurait pleuré. Et ensuite, elle t'aurait dit… » 는 과거에 일어났을 법한 일을 상상하는 조건법 과거. « Mme Vasseur me dirait de parler plus fort » 는 현재의 가정(조건법 현재). 같은 구조로 « Si c'était ton café qui fermait ? » 도 가능합니다."),
("B1", "비교의 정도: plus … que, moins, aussi", "« Une cheffe émue touche plus qu'une cheffe parfaite. » « Les clients sont moins nombreux. » « C'est aussi mon restaurant. » 비교급은 구어에서 매우 자주 씁니다. 수치 비교: « huit pour cent de l'objectif »."),
("C1", "접속법: il faut que, pour que", "« Il faut juste que la vidéo circule. » « Que tout le monde les ait en tête. » circuler → que la vidéo circule, avoir → qu'ils aient / que tout le monde les ait. 목적: « pour que les gens comprennent »."),
("B2", "퍼센트·평균·나눗셈", "« Sept pour cent de 40 000, ça fait 2 800. » « 40 € de moyenne. » « Il en reste 36 800, sur vingt-neuf jours, soit environ 1 270 € par jour. » 'soit' 는 '즉, 다시 말해'. 계산 흐름을 « Donc … Soit … » 로 연결합니다."),
]

READ = [
("수사 질문의 억양 — Vous savez ce que c'est, un comptoir ?", "« Vous savez ce que c'est, / un comptoir ? » 첫 구간은 끝을 올리지 않고 평평하게, 마지막 « un comptoir ? » 에서 올렸다 내립니다. 청중이 대답하지 않는 질문이므로 끝에 잠깐 쉬고 다음 문장으로 넘어가세요."),
("3박자 나열 — Une adresse. Un plat. Un voisin.", "« Une adresse. / Un plat. / Un voisin qui vous dit bonjour. » 셋째 항목이 가장 길고 마지막입니다. 앞의 둘은 끝을 약간 올려 '아직 더 있다'를, 셋째 끝은 내려 '끝' 을 표시합니다."),
("감정의 휴지 — Euh... je suis cheffe...", "« Bonjour. / Je m'appelle Hélène. / Je suis cheffe. » 처럼 짧게 끊고, 말이 막힌 « Euh... » 에서는 실제로 1~2초 쉽니다. 낭독 때 이 침묵을 지키는 것이 연기의 핵심입니다."),
("숫자 읽기 — 40 000 / 37 200 / 36 800", "« 40 000 € » quarante mille euros, « 37 200 € » trente-sept mille deux cents euros, « 36 800 € » trente-six mille huit cents euros. « 7 % » sept pour cent. mille 는 불변, cent 은 뒤에 수가 오면 -s 가 없습니다: deux cents / deux cent un."),
("리에종 — trente-cinq_ans / quatre-vingts_personnes", "« Le nôtre a trente-cinq_ans. » 에서 cinq 의 q 가 발음되어 [sɛ̃k‿ɑ̃] 처럼 이어집니다. « Quatre-vingts_personnes » 의 s 는 [z] 로 이어지지 않고 « quatre-vingts / personnes » 로 끊어 읽는 편이 자연스럽습니다."),
("마무리 문장의 힘 — Alors, vous venez nous donner un coup de main ?", "« Alors, / vous venez / nous donner / un coup de main ? » 짧은 구간 4개로 끊고, 마지막 질문에서 미소를 담아 올립니다. 카메라 앞에서는 문장 끝을 올리면 친근하고, 내리면 단호하게 들립니다."),
("구어 축약 — c'est pas / t'as / j'sais", "« Papa, c'est pas dans le programme. » « Tu ne vois pas que je souris ? » 의 ne 는 연설에서는 살려도, 대화에서는 « c'est pas » 처럼 빠집니다. 영상(연설)과 평소 대화에서 말의 격식 차이를 비교하며 읽어 보세요."),
]

CULTURE = [
("Le financement participatif — 작은 후원이 모여 가게를 살린다", "프랑스에서는 Ulule, KissKissBankBank 같은 플랫폼에서 소상공인과 식당이 보상형 크라우드펀딩(don avec contrepartie)을 많이 합니다. 목표액을 못 채우면 후원금을 돌려주는 '전부 아니면 전무(tout ou rien)' 방식이 흔하고, 수수료는 플랫폼과 결제 대행사 몫으로 나갑니다. 후원자에게는 식사권, 이름 게재, 비공개 저녁 같은 보상이 주어집니다."),
("Le café du coin — 동네 가게는 공동의 자산", "프랑스 사람들에게 단골 카페·비스트로는 단순한 가게가 아니라 마을의 공용 거실에 가깝습니다. '카운터(comptoir)에 팔꿈치를 괴는 습관(s'accouder au comptoir)'이 사람 사이를 잇습니다. 그래서 가게가 위기에 처하면 이웃들이 후원과 입소문으로 나서는 일이 드물지 않습니다. 바쉐 부인의 댓글 « Ma table sept m'attend. » 이 그 정서를 보여 줍니다."),
]

META = dict(part=4, ep=48, part_label="제4부 La reconstruction · 늦가을·겨울", title_fr="Le financement participatif", title_ko="크라우드펀딩",
 place="Le Comptoir de Marthe, 11월 19일 목요일 오후 3시 10분(촬영) ~ 밤 10시 40분(첫날 집계)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · Lucien Marchand (아버지)",
 wine="크라우드펀딩 호소 영상 촬영: 목표 40 000 €, 30일, 수수료 7 %(실수령 37 200 €), 첫날 3 200 € 모금.",
 focus="카메라 앞 구어체 호소, 수사 질문, 전위·강조, 명령형+대명사, 퍼센트·평균 계산",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제49화 « Le retour de Karim » : 11월 23일 월요일, 리옹에서 석 달 만에 돌아온 카림이 주방 문 앞에 선다.")
