# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, K = "Hélène", "Julien", "Karim"
D = [
(None, "Lundi 23 novembre, 10 h. Le restaurant est fermé depuis hier. Hélène vide les placards de la cuisine. On frappe à la porte de service.", "11월 23일 월요일 오전 10시. 식당은 어제부터 문을 닫았다. 엘렌이 주방 수납장을 비우고 있는데 후문에서 노크 소리가 난다."),
(K, "Hélène ? C'est moi. Ouvre, s'il te plaît.", "엘렌? 나야. 문 좀 열어 줘."),
(H, "Karim ? Qu'est-ce que tu fais là ?", "카림? 여기서 뭐 해?"),
(K, "Je passais dans le coin. Enfin, non. Je suis venu exprès.", "근처 지나가다가... 아니, 아니야. 일부러 왔어."),
(H, "Tu es venu de Lyon, un lundi matin, exprès ?", "리옹에서, 월요일 아침에, 일부러?"),
(K, "Le train de six heures. J'avais peur de changer d'avis.", "6시 기차 타고. 마음이 바뀔까 봐 겁났거든."),
(H, "Entre. Et ferme la porte, il y a un courant d'air.", "들어와. 그리고 문 닫아, 외풍 들어오잖아."),
(K, "Tu as tout vidé, dis donc. Même les étagères.", "와, 다 비웠네. 선반까지."),
(H, "Les travaux commencent demain. M. Lopes arrive à huit heures.", "공사가 내일 시작이야. 로페스 씨가 8시에 와."),
(K, "Je sais. J'ai vu ta vidéo sur la page de financement.", "알아. 후원 페이지에서 네 영상 봤어."),
(H, "Ah. Tu l'as vue. Quelle horreur, je suis ridicule là-dedans.", "아, 봤구나. 끔찍해, 거기서 나 우스꽝스럽잖아."),
(K, "Pas du tout. Tu es touchante. J'ai même donné cinquante euros.", "전혀. 뭉클하던데. 나 50유로도 냈어."),
(H, "C'était toi, « K. H. de Lyon » ? Je me demandais.", "그게 너였어? « 리옹의 K. H. » 가? 궁금했는데."),
(K, "Oui. Je voulais que tu saches que je pensais à vous.", "응. 내가 너희를 생각하고 있다는 걸 네가 알았으면 했어."),
(H, "Tu pensais à nous, mais tu n'as pas appelé. Pas une fois.", "우리를 생각했다면서 전화는 안 했네. 한 번도."),
(K, "Je sais. J'ai honte. C'est pour ça que je suis là.", "알아. 창피해. 그래서 온 거야."),
(H, "Assieds-toi. Un café ? C'est tout ce qu'il me reste de la machine.", "앉아. 커피? 커피 머신에서 남은 건 그것뿐이야."),
(K, "Avec plaisir. Mais je voulais d'abord te dire quelque chose.", "고맙지. 근데 먼저 할 말이 있어."),
(H, "Vas-y. Je te préviens, je suis encore en colère.", "해 봐. 미리 말해 두는데, 나 아직 화났어."),
(K, "Je regrette que je sois parti comme ça, en plein été.", "그렇게, 한여름에 떠나 버린 거 후회해."),
(H, "Un 31 juillet. Et en septembre, l'inspection, la fermeture. J'ai tout pris toute seule.", "7월 31일에. 그리고 9월엔 검사에 폐쇄까지. 나 혼자 다 맞았어."),
(K, "Je l'ai su par Chloé. Elle m'écrivait de temps en temps.", "클로에한테 들었어. 가끔 나한테 문자했거든."),
(H, "Chloé t'écrivait ? Elle ne m'a rien dit, celle-là.", "클로에가 너한테 연락했다고? 나한텐 한마디도 안 했는데."),
(K, "Elle voulait pas que tu t'énerves. Elle disait : « Laisse-lui du temps ».", "네가 화낼까 봐서. « 시간을 좀 줘 » 라고 했어."),
(H, "Elle a eu raison. Bon, continue.", "그 애 말이 맞았네. 자, 계속해."),
(K, "À Lyon, on m'avait promis la cuisine de mes rêves. Une étoile, une grande brigade.", "리옹에선 꿈의 주방을 약속받았어. 별 하나, 큰 브리가드."),
(H, "Et alors ? Ce n'était pas la cuisine de tes rêves ?", "그래서? 꿈의 주방이 아니었어?"),
(K, "C'était une cuisine où on crie. Le chef hurlait pendant tout le service.", "소리 지르는 주방이었어. 셰프가 서비스 내내 고함을 쳤어."),
(H, "Moi aussi, je crie, des fois.", "나도 가끔 소리 지르잖아."),
(K, "Pas comme ça. Toi, tu cries, et ensuite tu me fais un café. Lui, jamais.", "그렇게는 아니지. 넌 소리 지르고 나서 커피를 타 주잖아. 그 사람은 절대 안 그래."),
(H, "Ha. Merci pour le compliment, je crois.", "하. 칭찬으로 들을게, 아마도."),
(K, "Une brigade qui crie, ce n'est pas pour moi. J'ai mis trois mois à le comprendre.", "소리 지르는 브리가드는 나랑 안 맞아. 그걸 깨닫는 데 석 달 걸렸어."),
(H, "Trois mois ! Moi, je te l'aurais dit en trois jours.", "석 달이나! 난 사흘이면 말해 줬을 텐데."),
(K, "Tu me l'aurais dit, et je ne t'aurais pas écoutée. J'étais trop fier.", "말해 줬어도 난 안 들었을 거야. 너무 잘난 척했거든."),
(H, "Ça, c'est vrai. Tu étais insupportable avec ton étoile.", "그건 맞아. 별 하나 가지고 아주 못 봐 줄 정도였지."),
(K, "Je sais. Et je veux pas que tu croies que je reviens parce que j'ai échoué.", "알아. 그리고 내가 실패해서 돌아온다고 생각하진 않았으면 해."),
(H, "Mais c'est un peu pour ça, non ?", "근데 조금은 그 때문이잖아, 아니야?"),
(K, "Un peu. Mais surtout parce que ma vraie cuisine, c'est ici.", "조금은. 하지만 무엇보다 내 진짜 주방은 여기라서."),
(H, "Ici ? Avec un four qui chauffe mal et un plafond qui fuit ?", "여기? 열 안 오르는 오븐에 천장은 새는 이곳이?"),
(K, "Avec ta blanquette. Avec ce vieux comptoir. Avec vous.", "네 블랑케트랑, 이 낡은 카운터랑, 너희랑."),
(H, "Arrête, tu vas me faire pleurer. Pas avant midi, Karim.", "그만해, 울겠다. 점심 전엔 안 돼, 카림."),
(None, "Julien entre par la salle avec des cartons. Il s'arrête net.", "줄리앙이 홀 쪽에서 상자를 들고 들어오다가 딱 멈춘다."),
(J, "Karim ?! Putain, enfin ! On ne t'attendait plus.", "카림?! 아, 젠장, 드디어! 이제 안 올 줄 알았어."),
(K, "Salut, Julien. Moi non plus, je ne m'attendais pas à être là.", "안녕, 줄리앙. 나도 내가 여기 있을 줄은 몰랐어."),
(J, "Hélène, tu l'as laissé entrer ? Comme ça, sans rien dire ?", "엘렌, 들여보냈어? 아무 말도 없이 그냥?"),
(H, "Il a insisté. Et il a apporté le train de six heures.", "고집을 부리더라. 6시 기차까지 끌고 왔고."),
(J, "Ha ha. Alors, tu lui as pardonné, oui ou non ?", "하하. 그래서, 용서했어 안 했어?"),
(H, "Je réfléchis. Il m'a dit « je regrette », c'est un début.", "생각 중이야. « 후회해 » 라고 했으니 시작은 한 거지."),
(K, "Je peux dire plus. Hélène, pardonne-moi, s'il te plaît.", "더 말할 수 있어. 엘렌, 용서해 줘, 부탁이야."),
(H, "Pardonner, c'est facile à dire. Il faut que tu me prouves quelque chose.", "용서는 말로 하긴 쉽지. 네가 뭔가를 증명해야 해."),
(K, "Dis-moi quoi. Je ferai tout ce qu'il faut.", "뭔지 말해. 필요한 건 뭐든 할게."),
(H, "D'abord, il faut que tu saches où on en est. Julien, explique-lui.", "먼저, 우리가 어떤 상황인지 알아야 해. 줄리앙, 설명해 줘."),
(J, "Bon. Le tribunal a ouvert la sauvegarde le douze. Six mois d'observation.", "자. 법원이 12일에 회생 절차를 열었어. 관찰 기간 6개월."),
(K, "Chloé me l'a dit. La dette, c'est combien exactement ?", "클로에가 말해 줬어. 빚이 정확히 얼마야?"),
(J, "Quatre-vingt-douze mille euros. On a un plan de remboursement sur huit ans.", "9만 2천 유로. 8년짜리 상환 계획이 있어."),
(K, "Huit ans. Et les créanciers ont accepté ?", "8년. 채권자들이 받아들였어?"),
(J, "Delmas, Bastide, les impôts. Ils ont signé, à condition qu'on tienne le plan.", "델마, 바스티드, 세무서까지. 계획을 지키는 조건으로 서명했어."),
(H, "Donc je te le dis franchement : je ne peux pas te payer comme Lyon.", "그러니 솔직히 말할게. 리옹만큼은 못 줘."),
(K, "Je m'en fiche, de l'argent. Combien tu peux me proposer ?", "돈은 상관없어. 얼마나 줄 수 있는데?"),
(H, "Ton salaire d'avant, pas un euro de plus. Au moins jusqu'à l'été.", "예전 월급 그대로, 1유로도 더는 안 돼. 적어도 여름까진."),
(K, "D'accord. Et je ne veux aucune prime avant que tu aies fini de rembourser.", "알았어. 그리고 네가 빚을 다 갚기 전까진 상여금도 필요 없어."),
(J, "Attends, Karim. Tu as un logement ? Tu reviens vivre à Paris ?", "잠깐, 카림. 지낼 곳은 있어? 파리로 다시 와서 살아?"),
(K, "J'ai gardé mon studio à Ménilmontant. Un copain le sous-loue jusqu'en décembre.", "메닐몽탕 원룸을 갖고 있었어. 친구가 12월까지 전대해서 쓰고 있고."),
(J, "Pratique. Tu avais tout prévu, en fait.", "편리하네. 사실 다 계획해 둔 거네."),
(K, "Non. J'avais tout espéré. Ce n'est pas pareil.", "아니. 다 바랐던 거지. 그건 달라."),
(H, "Belle réponse. Mais j'ai encore une question. Pourquoi maintenant ?", "좋은 대답이야. 근데 질문이 하나 더 있어. 왜 지금이야?"),
(K, "Parce que j'ai vu ta vidéo. Tu disais : « Ce restaurant, c'est ma famille ».", "네 영상을 봤으니까. 네가 « 이 식당은 내 가족이에요 » 라고 했잖아."),
(H, "J'ai dit ça ? Je me suis trompée de texte, sûrement.", "내가 그런 말을 했어? 대본을 잘못 읽었나 보네."),
(K, "Non. Tu le pensais. Et moi, j'avais quitté ma famille.", "아니, 진심이었잖아. 그리고 난 내 가족을 떠난 거였고."),
(H, "Ce qui m'a fait mal, c'est que tu partes sans te retourner.", "내가 아팠던 건 네가 뒤도 안 돌아보고 떠났다는 거야."),
(K, "J'avais peur que tu me dises non si je restais pour t'en parler.", "남아서 얘기하면 네가 안 된다고 할까 봐 무서웠어."),
(H, "Peut-être. Mais j'aurais préféré que tu me le dises en face.", "그랬을지도 모르지. 하지만 얼굴 보고 말해 줬으면 좋았을 거야."),
(K, "Tu as raison. La prochaine fois, je te le dis en face. Promis.", "네 말이 맞아. 다음엔 얼굴 보고 말할게. 약속해."),
(H, "Il n'y aura pas de prochaine fois. Sinon, je te mets à la plonge.", "다음은 없어. 안 그러면 설거지 보낼 거야."),
(J, "Elle plaisante. Enfin, je crois.", "농담이야. 아니, 그럴걸."),
(H, "Pas du tout. Moussa serait ravi de passer le relais.", "전혀. 무사는 교대하면 기뻐할걸."),
(K, "Je ferai la plonge un mois s'il le faut. Mais j'ai mieux : mes couteaux.", "필요하면 한 달 설거지도 할게. 근데 더 좋은 게 있어. 내 칼들."),
(K, "Et un carnet d'idées pour l'hiver. Je l'ai rempli dans le train.", "그리고 겨울 메뉴 아이디어 수첩. 기차에서 채웠어."),
(H, "Tu as pris tes couteaux avant même de me demander ?", "나한테 묻기도 전에 칼부터 챙겼다고?"),
(K, "Oui. Un peu culotté, je sais. Mais j'espérais.", "응. 좀 뻔뻔했지, 알아. 그래도 기대했거든."),
(J, "Culotté, mais efficace. J'aime bien.", "뻔뻔하지만 효과적이야. 마음에 드는데."),
(H, "Montre-moi ce carnet. Des plats de saison ?", "그 수첩 보여 줘. 제철 요리야?"),
(K, "Oui. Une soupe à l'oignon revue, un pot-au-feu de canard, un chou farci.", "응. 새로 손본 양파 수프, 오리 포토푀, 양배추 속채우기."),
(H, "Un chou farci ? Maman le faisait le dimanche, tu sais.", "양배추 속채우기? 엄마가 일요일마다 해 주셨는데."),
(K, "Je ne savais pas. Le hasard est drôle, non ?", "몰랐어. 우연이 재밌네, 그치?"),
(H, "Très. Bon. Mets ton tablier.", "아주. 자. 앞치마 매."),
(K, "Maintenant ? Je pensais que tu voulais du temps pour réfléchir.", "지금? 네가 생각할 시간이 필요한 줄 알았는데."),
(H, "Le temps, on n'en a pas. Il faut que la cuisine soit vide avant demain.", "시간은 없어. 내일 전에 주방을 다 비워야 해."),
(K, "Ça veut dire que tu me reprends ?", "그 말은 나를 다시 받아 준다는 거야?"),
(H, "Ça veut dire que je te pardonne, bêtement, parce que j'ai besoin de toi.", "바보같이 널 용서한다는 거야, 네가 필요하니까."),
(H, "Voilà. Je l'ai dit. Putain, ça fait du bien !", "자, 말했다. 아, 젠장, 속이 시원하네!"),
(J, "Enfin ! Avec Chloé et Moussa, on est de nouveau toute l'équipe.", "드디어! 클로에랑 무사까지, 다시 팀이 다 모였네."),
(K, "Et Chloé, elle sait que je viens ?", "클로에는 내가 오는 거 알아?"),
(J, "Non. Elle est à l'école aujourd'hui. Je lui envoie un message ?", "아니. 오늘은 학교에 있어. 문자 보낼까?"),
(H, "Non. On lui fait la surprise demain. Elle a besoin de bonnes nouvelles.", "아니. 내일 깜짝 선물로 하자. 그 애한텐 좋은 소식이 필요해."),
(K, "Elle va me frapper.", "날 때리겠다."),
(J, "Elle va d'abord pleurer. Ensuite, elle va te frapper.", "먼저 울 거야. 그다음에 때리겠지."),
(None, "Karim aperçoit un vieux tablier accroché à la patère, près de la porte.", "카림이 문 옆 옷걸이에 걸린 낡은 앞치마를 발견한다."),
(K, "Mon tablier. Il est toujours là.", "내 앞치마. 아직 여기 있네."),
(H, "Je n'ai pas eu le courage de le jeter. Ni de le donner à Sofiane.", "버릴 용기가 없었어. 소피안에게 줄 용기도."),
(K, "Alors tu y croyais, quand même. Que je reviendrais.", "그럼 믿긴 했네. 내가 돌아올 거라고."),
(H, "Non. Je me disais juste : « C'est dommage de jeter un tablier propre ».", "아니. 그냥 « 깨끗한 앞치마를 버리긴 아깝지 » 라고 생각했을 뿐이야."),
(J, "Menteuse. Elle l'a lavé en septembre. Je l'ai vue.", "거짓말쟁이. 9월에 빨았어. 내가 봤거든."),
(H, "Julien ! Il suffit que tu parles pour que je regrette de t'avoir embauché.", "줄리앙! 네가 입만 열면 고용한 걸 후회하게 된다니까."),
(J, "Je me tais. Je porte les cartons. Karim, tu m'aides ?", "입 다물게. 상자나 옮길래. 카림, 도와줄래?"),
(K, "Bien sûr. Hélène, avant de commencer, je voulais te dire merci.", "물론이지. 엘렌, 시작하기 전에 고맙다고 하고 싶었어."),
(H, "Merci pour quoi ? Je ne t'ai encore rien donné.", "뭐가 고마워? 아직 아무것도 안 줬는데."),
(K, "Pour la porte. Tu aurais pu ne pas ouvrir.", "문 열어 준 거. 안 열 수도 있었잖아."),
(H, "Je n'allais pas laisser mon sous-chef dehors sous la pluie. Il pleut ?", "내 부주방장을 빗속에 세워 둘 순 없지. 비 와?"),
(K, "Un peu. Je suis trempé.", "조금. 흠뻑 젖었어."),
(H, "Ça te fera les pieds. Allez, au boulot.", "그것 참 쌤통이다. 자, 일하자."),
(K, "Oui, chef. Je commence par quoi ?", "네, 셰프. 뭐부터 할까?"),
(H, "Par le garde-manger. Jette tout ce qui est périmé.", "식료품 창고부터. 유통기한 지난 건 전부 버려."),
(K, "Il y a encore de la farine de 2019 ici. Tu m'expliques ?", "여기 2019년 밀가루가 아직 있어. 설명해 줄래?"),
(H, "C'est Papa. Il garde tout. « On ne sait jamais », qu'il dit.", "아빠야. 다 갖고 있어. « 모르는 일이잖아 » 하시면서."),
(J, "Et il a raison une fois sur dix. Parfois.", "그리고 열 번에 한 번은 맞아. 가끔."),
(H, "Un jour, il gardera même nos dettes. Au cas où.", "언젠가는 우리 빚까지 보관하실걸. 혹시 모르니까."),
(K, "Il va être content de me revoir ?", "나 다시 보면 좋아하실까?"),
(H, "Il va te faire la morale pendant une heure. Prépare-toi.", "한 시간 동안 훈계하실 거야. 각오해."),
(J, "Avec un proverbe, j'imagine. « Mieux vaut tard que jamais », tu verras.", "속담이랑 같이 하겠지. « 늦더라도 안 하는 것보단 낫다 », 두고 봐."),
(H, "Bon, allez, au boulot, tous les deux. Je veux que ce soit fini ce soir.", "자, 둘 다 일하자. 오늘 저녁까진 끝났으면 좋겠어."),
(K, "Ce soir ? On n'est que trois pour toute la cuisine !", "오늘 저녁? 주방 전체를 셋이서 하는데!"),
(H, "Oui. Mais on est trois qui se parlent de nouveau. Ça change tout.", "응. 하지만 다시 말을 하는 셋이야. 그게 다 바꿔."),
]

VOCAB = [
("A2", "Je suis venu exprès.", "일부러 왔어.", "exprès = 일부러. « Je suis venu exprès pour te voir. » 부사라 변하지 않음."),
("B1", "J'ai honte.", "창피해 / 부끄러워.", "avoir honte (de qqch). 사과의 첫 단계로 자주 씀. « J'ai honte de ce que j'ai fait. »"),
("B1", "Je regrette que je sois parti comme ça.", "그렇게 떠난 게 후회돼.", "regretter que + 접속법. 주어가 같아도 que 구문 가능하나 « Je regrette d'être parti » 가 더 간단. ↔ 정중: Je déplore mon départ précipité."),
("B1", "J'ai mis trois mois à le comprendre.", "그걸 깨닫는 데 석 달 걸렸어.", "mettre + 시간 + à + 부정사 = ~하는 데 시간이 걸리다."),
("B1", "Pardonne-moi, s'il te plaît.", "용서해 줘, 부탁이야.", "pardonner à qqn / pardonner qqch. 명령형 + 대명사: pardonne-moi."),
("B1", "Tu es touchante.", "뭉클하게 만들어 / 감동적이야.", "touchant(e) = 마음을 움직이는. 칭찬으로 쓰임."),
("B1", "Elle a eu raison.", "그 애 말이 맞았어.", "avoir raison ↔ avoir tort."),
("B2", "Je m'en fiche, de l'argent.", "돈은 상관없어.", "[구어] s'en ficher de qqch. 구어에서는 대상을 문장 끝으로 빼서 강조(dislocation). ↔ 정중: L'argent m'est indifférent."),
("B2", "Il faut que tu me prouves quelque chose.", "네가 뭔가를 증명해야 해.", "il faut que + 접속법(prouves). 의무·필요 표현의 핵심 문형."),
("B2", "à condition qu'on tienne le plan", "계획을 지킨다는 조건으로", "à condition que + 접속법. 같은 주어면 à condition de + 부정사."),
("B2", "Il suffit que tu parles pour que je regrette.", "네가 입만 열면 후회하게 돼.", "il suffit que + 접속법, pour que + 접속법. 유머러스한 과장에 어울림."),
("B2", "Ça te fera les pieds.", "쌤통이다 / 좀 당해 봐.", "[구어] 가벼운 놀림. ↔ 정중: C'est bien fait pour vous. 가까운 사이에서만."),
("B2", "Quel culot ! / Un peu culotté", "뻔뻔한 / 대담한", "[구어] culotté(e) = 뻔뻔하지만 용기 있는. ↔ 정중: audacieux, effronté."),
("B2", "sans te retourner", "뒤도 돌아보지 않고", "se retourner = 뒤돌아보다. 미련 없이 떠나는 것을 비유."),
("B2", "mettre à la plonge", "설거지 보내다", "la plonge = 주방 설거지 구역/일. 주방 은어이자 가벼운 위협."),
("B2", "sous-louer", "전대하다", "sous-louer un studio = 임차한 집을 다시 세놓다. un sous-locataire."),
("C1", "Putain, enfin !", "아, 젠장, 드디어!", "[속어] 안도·기쁨의 감탄. 쓸 수 있음: 가까운 주방 동료·친구 사이 / 금지: 손님·상사·외부인 앞. ↔ 정중: Enfin, quel soulagement !"),
("C1", "Putain, ça fait du bien !", "아, 속이 다 시원하네!", "[속어] ça fait du bien = 속이 후련하다. 쓸 수 있음: 가까운 동료 사이 / 금지: 손님·외부인 앞. ↔ 정중: Cela fait vraiment du bien."),
("C1", "On ne t'attendait plus.", "이제 안 올 줄 알았어.", "ne ... plus + 반과거: 기대를 접었던 상태. 재회의 놀라움 표현."),
("C1", "Tu as de la suite dans les idées.", "한번 마음먹으면 끝까지 가네.", "avoir de la suite dans les idées = 집념이 있다. 칭찬과 놀림 사이."),
("C1", "Mieux vaut tard que jamais.", "늦더라도 안 하는 것보단 낫다.", "속담. Lucien이 즐겨 쓰는 종류의 관용구. 지각·뒤늦은 사과에 어울림."),
("C1", "Je te pardonne, bêtement.", "바보같이 널 용서해.", "adverbe + 용서: 이성보다 감정이 앞섰음을 자조적으로 표현."),
("C1", "passer le relais", "바통을 넘기다", "relais = 릴레이. 업무를 다른 사람에게 인계하다. Moussa에게 설거지를 넘기는 장난에 사용."),
]

GRAM = [
("B1", "regretter que + 접속법 (사과)", "« Je regrette que je sois parti comme ça. » 감정(후회·유감) 뒤의 que 절은 접속법: sois(être). 구어에서는 같은 주어면 « Je regrette d'être parti » 처럼 부정사로 줄여도 된다. 사과 문장 틀: Je regrette que / Je suis désolé que / Pardonne-moi d'avoir + 과거분사."),
("B2", "il faut que + 접속법", "« Il faut que tu me prouves quelque chose. » « Il faut que la cuisine soit vide avant demain. » prouver → prouves, être → soit. 필요·의무를 말할 때 가장 자주 쓰는 접속법 문형. 규칙 -er 동사는 현재형과 같고 être/avoir/aller/faire는 불규칙(sois, aies, aille, fasse)."),
("B2", "vouloir / préférer que + 접속법", "« Je voulais que tu saches. » « J'aurais préféré que tu me le dises en face. » 주어가 다르면 que + 접속법, 같으면 부정사(Je voulais te dire...). 구어에서는 과거 이야기에도 반과거 접속법 대신 현재 접속법(saches, dises)을 쓴다."),
("B2", "조건·목적 접속사 + 접속법", "« à condition qu'on tienne le plan », « avant que tu aies fini de rembourser », « pour que je regrette ». à condition que / avant que / pour que / bien que / jusqu'à ce que 뒤에는 항상 접속법. avant que 뒤에서는 ne 를 넣지 않는 구어가 일반적."),
("B1", "감정 전달: avoir peur que / ce qui m'a fait mal, c'est que", "« J'avais peur que tu me dises non. » « Ce qui m'a fait mal, c'est que tu partes sans te retourner. » 감정 동사 + que + 접속법. 강조 구문 « ce qui ..., c'est que ... » 로 아픈 지점을 정확히 짚는다. 용서 과정: 인정 → 이유 → 감정 → 조건."),
("B2", "ne ... plus / 반과거와 조건법 과거의 대비", "« On ne t'attendait plus. » (반과거: 기대를 접은 상태) / « Moi, je te l'aurais dit en trois jours. » (조건법 과거: 실제로는 안 한 일에 대한 가정). 사과·원망 장면에서 « j'aurais dû, j'aurais préféré » 가 자주 나온다."),
("B2", "구어체 강조: 대상 후치(dislocation)", "« Je m'en fiche, de l'argent. » « Il a insisté, lui. » 대상을 문장 끝에 두고 대명사를 앞에 쓰는 구어 어순. ↔ 정중: L'argent m'est indifférent."),
]

READ = [
("리에종 연결 — il_a_insisté", "« Il a insisté. » 는 [i-la-ɛ̃-sis-te] 로 이어 읽는다. Il a 에서 l 이 a 와 붙고, 비음 in 은 코를 울린다. 같은 방식으로 « C'est un début » 의 t'un."),
("접속법 문장의 호흡 — Il faut que", "« Il faut que tu me prouves / quelque chose. » 는 que 뒤에서 숨을 쉬지 말고 tu me prouves 까지 한 덩어리로 읽고, quelque chose 앞에서만 가볍게 끊는다. que 의 e 는 약하게."),
("u 와 ou — Pardonne-moi / tout", "« Pardonne-moi, s'il te plaît. » 에서 moi 는 [mwa], « tout » 는 [tu]. 입술을 둥글게 한 u [y] (tu, plus, prouves) 와 ou [u] (tout, pour) 를 구분해서 소리 내 보자."),
("안도의 감탄 억양 — Putain, enfin !", "« Putain, / enfin ! » 은 Putain 을 길게 끌며 올렸다가 enfin 에서 툭 내려 놓는다. 가슴을 열고 숨을 내쉬는 느낌. 가까운 사이에서만 쓰는 표현임을 기억하고 장면의 웃음을 살려 읽는다."),
("r 소리 — regrette / remboursé", "« Je regrette que je sois parti. » 에서 regrette 의 r 은 목 안쪽에서 가볍게 긁는 소리. 첫 r 은 부드럽게, 두 번째 r(grette)은 gr 로 묶어 한 번에 읽는다."),
("억양과 질문 — Ça veut dire que tu me reprends ?", "« Ça veut dire / que tu me reprends ? » 는 중간에서 한 번 끊고 문장 끝을 올려 확인 질문으로. 주저하는 카림의 마음을 목소리의 떨림으로 표현해 보자."),
]

CULTURE = [
("한 번 떠난 직원을 다시 받아 주기 — 프랑스 주방의 불문율", "미슐랭 스타 식당의 브리가드 문화는 엄격하고 위계적이어서 소리를 지르는 주방이 아직도 있다. 그래서 가족 같은 소규모 비스트로로 돌아오는 요리사도 드물지 않다. 프랑스 주방에서는 « le chef qui pardonne » 를 약함이 아니라 신뢰의 표시로 보기도 한다. 용서의 말보다 « 다시 앞치마를 매라 » 는 행동이 더 큰 신호다."),
("프랑스어의 사과 단계", "Pardon(가벼운 실수) < Excuse-moi(조금 무거운 사과) < Je suis désolé(진심) < Je regrette que ... / Pardonne-moi(관계가 걸린 사과). 가까운 사이에서는 « Je m'en veux » (스스로를 탓하다) 도 많이 쓴다."),
]

META = dict(part=4, ep=49, part_label="제4부 La reconstruction · 늦가을·겨울", title_fr="Le retour de Karim", title_ko="카림의 귀환",
 place="Le Comptoir de Marthe, 주방, 11월 23일 월요일 오전 10시경 (휴업 이틀째, 공사 전날)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Karim Haddad (부주방장, 리옹에서 복귀)",
 wine="리옹에서 석 달을 보낸 카림이 일부러 새벽 기차를 타고 돌아와 사과하고, 엘렌이 조건부로 그를 받아 주는 재회.",
 focus="사과·용서 표현, 접속법(regretter que, il faut que, à condition que, avant que, pour que), 안도의 감탄(putain, enfin !)",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제50화 « Les producteurs répondent » : 11월 26일 목요일, 바스티드가 노르망디와 부르고뉴의 소규모 생산자 네 명을 데리고 와서 연대 계약을 제안한다.")
