# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, V = "Hélène", "Julien", "Chloé", "Mme Vasseur"
D = [
(None, "Mardi 15 décembre, 10 h 30. Dans une heure et demie, le Comptoir rouvre. Julien dispose les couverts, Chloé frotte le comptoir, Hélène revient de la cuisine, les mains moites.", "12월 15일 화요일 오전 10시 30분. 한 시간 반 뒤면 콤투아르가 다시 문을 연다. 쥘리앵은 식기를 놓고, 클로에는 카운터를 닦고, 엘렌은 땀 찬 손으로 주방에서 나온다."),
(H, "Putain, ça y est. Dans une heure et demie, on rouvre. Je n'arrive pas à le croire.", "젠장, 드디어 왔네. 한 시간 반 뒤에 문을 열어. 믿기지가 않아."),
(J, "Respire, chef. Tu as déjà fait ça des milliers de fois.", "숨 쉬어, 셰프. 이런 건 수천 번 해 봤잖아."),
(H, "Pas comme ça. Pas après trois mois de fermeture, pas avec mille deux cent trente-sept personnes qui nous regardent.", "이렇게는 아니지. 석 달 동안 닫았다가, 천이백삼십칠 명이 지켜보는데 이러는 건 처음이야."),
(C, "Moi aussi, j'ai l'estomac noué. J'ai essayé de manger un croissant et je n'ai pas pu.", "저도 속이 꼬였어요. 크루아상 먹어 보려 했는데 못 먹었어요."),
(J, "Ne vous inquiétez pas, mesdames. La peur avant le service, c'est le signe qu'on y tient.", "걱정 마세요, 숙녀분들. 영업 전의 두려움은 마음을 쓰고 있다는 증거예요."),
(H, "Ça, c'est de Papa, non ? Ou de Maman ?", "그건 아빠 말이야, 아니야? 엄마 말인가?"),
(J, "C'est de moi. Je suis plus philosophe que tu ne crois.", "내 말이야. 내가 생각보다 철학자거든."),
(C, "Julien, c'est vrai qu'on dit « bienvenue » ou « bon retour » aux premiers clients ?", "쥘리앵, 첫 손님들한테는 « 환영합니다 »랑 « 다시 오셨군요 » 중에 뭐라고 하는 게 맞아요?"),
(J, "Ça dépend. Un inconnu, c'est « Bienvenue au Comptoir ». Un habitué, c'est « Content de vous revoir ».", "상황에 따라 달라. 처음 온 손님은 « 콤투아르에 오신 걸 환영합니다 ». 단골은 « 다시 뵈어 반갑습니다 »."),
(C, "Et pour Mme Vasseur ? Elle va sûrement venir à midi.", "그럼 바쉐 부인은요? 분명 정오에 오실 텐데."),
(J, "Pour elle, on dit : « Madame Vasseur, votre table vous attend. » Et on sourit, mais pas trop.", "그분께는 이렇게 말해. « 바쉐 부인, 자리가 기다리고 있었어요. » 그리고 웃되, 너무 크게는 말고."),
(C, "Pas trop ? Pourquoi ?", "너무 크게는 안 된다고요? 왜요?"),
(J, "Parce que si on sourit trop, elle dit qu'on ne la prend pas au sérieux.", "너무 웃으면 자기를 진지하게 안 본다고 하시거든."),
(H, "Il a raison. Dix ans que je la connais, c'est la règle numéro un.", "맞아. 십 년을 알고 지냈지만 그게 제일 중요한 규칙이야."),
(None, "Hélène se plante devant l'ardoise toute neuve. Elle relit chaque ligne, en silence. En haut, la phrase tracée par Chloé : « Merci à vous 1 237 ».", "엘렌이 새 칠판 앞에 선다. 말없이 한 줄 한 줄 다시 읽는다. 맨 위에는 클로에가 쓴 문장 « 감사합니다 1 237 »."),
(H, "Chloé, tu as fait une faute à « poireaux ». Il y a un x à la fin, pas un s.", "클로에, « 대파 » 철자 틀렸어. 끝에는 s가 아니라 x야."),
(C, "Oh non ! Je corrige tout de suite. Pardon, j'ai écrit trop vite.", "아, 안 돼요! 바로 고칠게요. 죄송해요, 너무 빨리 썼어요."),
(J, "Ne t'excuse pas, c'est normal. Même moi, je me trompe sur « cabillaud ».", "사과하지 마, 당연한 거야. 나도 « 대구 » 철자는 틀려."),
(H, "Toi, tu te trompes sur tout. Allez, on se met en place. Il est onze heures.", "넌 다 틀리잖아. 자, 자리 잡자. 열한 시야."),
(C, "Je prends la salle de gauche, et Julien celle de droite. Et la terrasse ?", "저는 왼쪽 홀을, 쥘리앵은 오른쪽을 맡고요. 테라스는요?"),
(J, "Fermée, il fait six degrés. Les courageux iront à l'intérieur.", "닫아 둬, 6도야. 용감한 분들은 안으로 들어오시겠지."),
(H, "Karim est prêt, la soupe gratine, la blanquette frémit. Moussa a lavé les verres trois fois.", "카림 준비됐고, 수프는 그라탱 중이고, 블랑케트는 끓고 있어. 무사는 잔을 세 번 씻었고."),
(J, "Trois fois ! Les verres sont tellement propres qu'ils ont l'air invisibles.", "세 번이나! 잔이 너무 깨끗해서 안 보일 지경이야."),
(C, "Chef, je peux m'entraîner à lire l'ardoise à voix haute ? Pour les clients qui demandent.", "셰프님, 칠판을 소리 내어 읽는 연습을 해도 될까요? 손님이 물어보실 때를 대비해서요."),
(H, "Vas-y. Commence par l'entrée, et fais-nous saliver.", "해 봐. 앙트레부터 시작해서 군침 돌게 해 봐."),
(C, "Notre soupe à l'oignon gratinée : un bouillon de bœuf cuit six heures, et une croûte de comté bien dorée.", "저희 양파 그라탱 수프는 여섯 시간 끓인 소고기 육수에 노릇하게 구운 콩테 껍질을 얹었습니다."),
(J, "Pas mal du tout. Ajoute « fumante », ça donne envie. Et dis « notre blanquette, selon la recette de Marthe ».", "나쁘지 않아. « 김이 모락모락 나는 »을 붙여, 군침이 돌거든. 그리고 « 마르트의 레시피를 따른 블랑케트 »라고 말해."),
(C, "Notre blanquette, fidèle à la recette de Marthe, avec un riz pilaf bien blanc. Comme ça ?", "저희 블랑케트는 마르트 님의 레시피에 충실하며 새하얀 필라프를 곁들입니다. 이렇게요?"),
(H, "Parfait. Tu parles de notre mère à toutes comme si tu l'avais connue.", "완벽해. 우리 모두의 어머니를 직접 아는 것처럼 말하네."),
(None, "11 h 50. Hélène prend son souffle, se plante derrière la porte. Dehors, une dizaine de personnes attendent sous la bruine.", "오전 11시 50분. 엘렌이 숨을 고르고 문 뒤에 선다. 밖에서는 열 명쯤이 이슬비 속에서 기다리고 있다."),
(H, "Il y a déjà du monde. Julien, ils sont là depuis combien de temps ?", "벌써 사람들이 있네. 쥘리앵, 얼마나 기다린 거야?"),
(J, "Depuis onze heures vingt. Un couple m'a dit : « On voulait être les premiers. »", "열한 시 이십 분부터요. 한 부부가 이러더군. « 첫 손님이 되고 싶었어요. »"),
(H, "Putain. Je vais pleurer avant même d'ouvrir.", "젠장. 문도 열기 전에 울 것 같아."),
(C, "Chef, pas de larmes. Julien nous a dit : on sourit, mais pas trop.", "셰프님, 눈물은 안 돼요. 쥘리앵이 말했잖아요. 웃되 너무 크게는 말라고."),
(H, "Tu as raison. Bon. Julien, c'est toi qui ouvres.", "맞아. 좋아. 쥘리앵, 네가 열어."),
(J, "Moi ? C'est ton restaurant, Hélène. C'est toi qui devrais tourner la clé.", "나? 네 가게잖아, 엘렌. 열쇠는 네가 돌려야지."),
(H, "Non. Toi, tu as la voix de l'accueil. Moi, je serai en cuisine, à écouter.", "아니. 넌 맞이하는 목소리를 가졌잖아. 난 주방에서 귀 기울일게."),
(J, "D'accord. Mais toi, tu ne bouges pas d'ici avant que je dise « Bienvenue ». Promis ?", "알았어. 하지만 내가 « 환영합니다 »라고 말하기 전에는 여기서 움직이지 마. 약속?"),
(H, "Promis. Allez, ouvre.", "약속. 자, 열어."),
(None, "Julien tourne la clé. La porte s'ouvre sur le froid et sur les premières voix.", "쥘리앵이 열쇠를 돌린다. 문이 열리며 찬 공기와 첫 목소리들이 들어온다."),
(J, "Bonjour, mesdames et messieurs ! Bienvenue au Comptoir de Marthe. Entrez, entrez, il fait chaud ici.", "안녕하세요, 신사 숙녀 여러분! 콤투아르 드 마르트에 오신 걸 환영합니다. 들어오세요, 안은 따뜻해요."),
(C, "Bonjour, madame. Un couvert ou deux ? Par ici, je vous prie.", "안녕하세요, 부인. 한 분이세요, 두 분이세요? 이쪽으로 모실게요."),
(J, "Une table pour quatre ? Bien sûr. La douze, près du radiateur.", "네 분이요? 물론이죠. 12번, 라디에이터 옆입니다."),
(H, "Ça entre bien. Chloé, tu me dis dès que les premiers bons arrivent. Je suis au passe.", "잘 들어오네. 클로에, 첫 주문서 들어오면 바로 말해. 나 패스에 있을게."),
(C, "Oui, chef. Déjà une table de deux : deux soupes à l'oignon, une blanquette, un cabillaud.", "네, 셰프님. 벌써 두 분 테이블이에요. 양파 수프 둘, 블랑케트 하나, 대구 하나."),
(H, "Deux soupes, une blanquette, un cabillaud. Je répète pour confirmer. Karim, tu as entendu ?", "수프 둘, 블랑케트 하나, 대구 하나. 확인하려고 다시 말할게. 카림, 들었어?"),
(None, "Voix de Karim, depuis la cuisine : « Entendu, chef ! Deux oignons, une blanquette, un cabillaud ! »", "주방에서 카림의 목소리가 들린다. « 알겠습니다, 셰프! 양파 둘, 블랑케트 하나, 대구 하나! »"),
(J, "Hélène, un monsieur à la table trois voudrait savoir si le menu change souvent.", "엘렌, 3번 테이블 신사분이 메뉴가 자주 바뀌는지 물으세요."),
(H, "Dis-lui qu'on suit les saisons. Pas de tomates en hiver, pas de poires en juillet.", "계절을 따라간다고 말해 줘. 겨울에 토마토 없고 칠월에 배 없다고."),
(J, "Très bien. Il sourit, il est content. C'est un bon début.", "좋아요. 웃으시네, 만족하셨어. 좋은 출발이야."),
(None, "12 h 10. La salle est presque à moitié pleine. Les premiers plats partent. Le bruit des couverts monte.", "낮 12시 10분. 홀이 거의 절반 찼다. 첫 요리가 나간다. 식기 소리가 커진다."),
(C, "Chef, la soupe de la table deux revient ! La dame dit qu'elle est trop chaude.", "셰프님, 2번 테이블 수프가 돌아왔어요! 부인이 너무 뜨겁다고 하세요."),
(H, "Trop chaude ? C'est une soupe à l'oignon gratinée, elle est faite pour être chaude.", "너무 뜨겁다고? 양파 그라탱 수프는 뜨거우라고 만든 건데."),
(J, "Elle ne se plaint pas, elle demande si elle peut attendre cinq minutes avant de la manger.", "불평하는 게 아니라 오 분 기다렸다 먹어도 되냐고 물으시는 거예요."),
(H, "Évidemment. Dis-lui de prendre son temps. Une soupe patiente, ça se déguste.", "물론이지. 천천히 드시라고 해. 기다릴 줄 아는 수프가 맛있는 법이야."),
(C, "Hélène... je crois que j'ai oublié de noter la boisson de la table six.", "엘렌... 6번 테이블 음료 적는 걸 깜빡한 것 같아요."),
(H, "Respire, Chloé. Va demander. On ne tue personne pour une carafe d'eau.", "숨 쉬어, 클로에. 가서 물어봐. 물 한 병 때문에 사람 안 죽어."),
(C, "Merci. Excusez-moi, monsieur, vous prendrez de l'eau plate ou gazeuse ?", "고마워요. 실례합니다, 손님, 물은 일반으로 드릴까요, 탄산으로 드릴까요?"),
(J, "Bravo, Chloé. Tu rattrapes le coup avec le sourire. C'est ça, le métier.", "잘했어, 클로에. 웃으면서 수습하는 거야. 그게 이 일이야."),
(H, "Julien, ça sent le brûlé ou c'est mon imagination ?", "쥘리앵, 탄 냄새 나는 것 같아, 아니면 내 착각이야?"),
(J, "Ton imagination. C'est le pain grillé de la table huit. Il est juste doré.", "네 착각이야. 8번 테이블의 구운 빵 냄새야. 그냥 노릇한 거야."),
(H, "Merci. Je suis à cran. Je vois des fantômes dans la fumée.", "고마워. 신경이 곤두서 있어. 연기 속에서 유령이 보여."),
(None, "12 h 25. La porte s'ouvre sur Mme Vasseur, un manteau bleu nuit, son sac à main, Henri derrière elle. La salle semble retenir son souffle.", "낮 12시 25분. 문이 열리고 바쉐 부인이 짙은 파란 코트와 핸드백을 들고 들어온다. 뒤에 앙리가 있다. 홀이 숨을 죽이는 듯하다."),
(J, "Madame Vasseur ! Votre table vous attend. Donnez-moi votre manteau, je vous prie.", "바쉐 부인! 자리가 기다리고 있었어요. 코트를 제게 주세요."),
(V, "Mon manteau, je le garde, Julien. Il fait encore un peu frais, ici.", "코트는 내가 입고 있을게요, 쥘리앵. 여기는 아직 좀 서늘해요."),
(J, "Je monte le chauffage tout de suite. La sept, comme promis.", "바로 난방을 올릴게요. 약속대로 7번입니다."),
(V, "Je vois... La même table, la même chaise. Mais le coussin a changé, non ?", "보여요... 같은 테이블, 같은 의자. 그런데 쿠션이 바뀌었네요, 아닌가요?"),
(J, "C'est Hélène qui l'a choisi. Un coussin bleu, comme votre manteau.", "엘렌이 고른 거예요. 부인 코트처럼 파란 쿠션이에요."),
(V, "Elle a bon goût. Henri, assieds-toi, ne reste pas planté là comme un piquet.", "취향이 좋네요. 앙리, 앉아요, 장대처럼 서 있지 말고."),
(None, "Hélène sort de la cuisine, essuie ses mains sur son tablier. Mme Vasseur la regarde longuement, sans un mot.", "엘렌이 주방에서 나와 앞치마에 손을 닦는다. 바쉐 부인이 아무 말 없이 한참 그녀를 바라본다."),
(H, "Madame Vasseur... Je suis tellement contente de vous revoir ici.", "바쉐 부인... 여기서 다시 뵙게 되어 정말 기뻐요."),
(V, "Moi aussi, mon enfant. Je n'ai pas dormi de la nuit. Henri vous le dira.", "나도 그래요, 얘야. 밤새 한숨도 못 잤어요. 앙리가 말해 줄 거예요."),
(H, "Vous n'avez pas dormi ? À cause de moi ?", "잠을 못 주무셨다고요? 저 때문에요?"),
(V, "À cause de vous, à cause de ce qu'on est devenus. J'avais peur que ce ne soit plus pareil.", "당신 때문에, 우리가 어떻게 되었는지 때문에. 예전 같지 않을까 봐 무서웠어요."),
(H, "Moi aussi, j'avais peur. Ce matin, mes mains tremblaient sur les couteaux.", "저도 무서웠어요. 오늘 아침엔 칼 쥔 손이 떨렸어요."),
(V, "Alors on est deux. Maintenant, apportez-moi cette soupe, avant que je change d'avis.", "그럼 우리 둘이네요. 이제 그 수프를 가져와요, 마음이 바뀌기 전에."),
(H, "Tout de suite. Julien, une soupe à l'oignon, table sept, la plus belle de la cuisine.", "바로 갈게요. 쥘리앵, 7번 테이블에 양파 수프, 주방에서 제일 예쁜 걸로."),
(J, "Je file. Henri, un verre de Brouilly pour vous, comme avant ?", "다녀올게요. 앙리 씨, 예전처럼 브루이 한 잔 하시겠어요?"),
(None, "12 h 45. La salle est pleine. Hélène revient au passe, le front perlé de sueur. Chloé court entre les tables.", "낮 12시 45분. 홀이 가득 찼다. 엘렌이 이마에 땀방울이 맺힌 채 패스로 돌아온다. 클로에는 테이블 사이를 뛰어다닌다."),
(C, "Chef, tout est complet. On a même quatre personnes qui attendent dehors, debout.", "셰프님, 만석이에요. 밖에서 선 채로 기다리시는 분들도 네 명이나 있어요."),
(H, "Quatre ? Dis-leur que le café sera pour la maison, s'ils patientent.", "네 명이나? 기다려 주시면 커피는 서비스라고 전해."),
(C, "Ils ont déjà dit oui. Ils ont même demandé s'ils pouvaient prendre une photo de l'ardoise.", "벌써 좋다고 하셨어요. 칠판 사진 찍어도 되냐고까지 물으셨고요."),
(H, "Qu'ils la prennent. Il n'y a rien de plus beau qu'une ardoise pleine.", "찍으시라고 해. 가득 찬 칠판보다 예쁜 건 없어."),
(J, "Hélène, l'incident. La blanquette de la table neuf est un peu froide.", "엘렌, 문제가 하나 생겼어요. 9번 테이블 블랑케트가 좀 식었어요."),
(H, "Froide ? Elle est sortie à la bonne température. Elle a attendu au passe.", "식었다고? 적정 온도로 나갔는데. 패스에서 기다린 거야."),
(J, "Peut-être. Je l'ai portée avec Chloé en trente secondes, mais la porte était ouverte.", "그럴 수도 있죠. 클로에랑 삼십 초 안에 가져갔는데 문이 열려 있었어요."),
(H, "Rapporte-la. Je la remets au chaud et j'en sers une neuve. On ne discute pas.", "도로 가져와. 따뜻하게 두고 새 걸 서빙할게. 말다툼은 없어."),
(J, "Je m'en occupe. Et je dis au monsieur que c'est offert.", "제가 처리할게요. 그리고 손님께 서비스라고 말씀드릴게요."),
(H, "Pas besoin de l'offrir. On l'excuse et on la remplace. Ce n'est pas un drame.", "서비스까진 필요 없어. 사과하고 교체하면 돼. 비극은 아니잖아."),
(J, "Tu es plus calme que ce matin. Tu respires bien, maintenant.", "아침보다 훨씬 침착하네. 이제 숨을 잘 쉬고 있어."),
(H, "J'ai arrêté de réfléchir. J'agis. C'est le seul moyen.", "생각하는 걸 그만뒀어. 행동하는 거지. 그게 유일한 방법이야."),
(None, "13 h 30. Le rush passe. Dans la salle, les conversations sont plus calmes. Hélène sort enfin au bout de la salle.", "오후 1시 30분. 가장 바쁜 시간이 지나간다. 홀의 대화가 잔잔해진다. 엘렌이 드디어 홀 끝으로 나온다."),
(V, "Hélène ! Venez ici, deux minutes. Henri, laisse-nous.", "엘렌! 이리 와요, 이 분만. 앙리, 자리 좀 비켜 줘요."),
(H, "Oui, madame. Alors, ce déjeuner ? Dites-moi tout, sans pitié.", "네, 부인. 점심은 어떠셨어요? 사정 봐주지 말고 다 말씀해 주세요."),
(V, "La soupe, parfaite. Le fromage plus fin que vendredi, c'est mieux. La blanquette, je n'ai pas de mot.", "수프는 완벽해요. 치즈도 금요일보다 얇아서 나아요. 블랑케트는 할 말이 없어요."),
(H, "Pas de mot ? C'est bon ou mauvais ?", "할 말이 없다고요? 좋다는 거예요, 나쁘다는 거예요?"),
(V, "C'est celle de Marthe, mon enfant. Exactement celle de Marthe. J'ai fermé les yeux, et elle était là.", "마르트의 것이에요, 얘야. 정확히 마르트의 맛이에요. 눈을 감았더니 그분이 거기 있었어요."),
(H, "Merci, madame Vasseur. Vous ne savez pas ce que ça me fait de l'entendre.", "고마워요, 바쉐 부인. 그 말을 듣는 게 저한테 어떤 건지 모르실 거예요."),
(V, "Si, je le sais. J'ai perdu un mari pendant deux jours, la semaine dernière, à la mairie. Je comprends.", "알아요. 지난주에 시청에서 남편을 이틀이나 잃어버렸으니까. 이해해요."),
(H, "Vous avez perdu Henri ? Mais il est là !", "앙리 씨를 잃어버리셨다고요? 하지만 저기 계시잖아요!"),
(V, "Il s'était juste assis à la mauvaise salle d'attente. Je plaisante, Hélène. Souriez un peu.", "그냥 대기실을 잘못 앉았던 거예요. 농담이에요, 엘렌. 좀 웃어요."),
(H, "Vous m'avez fait peur. Aujourd'hui, mes nerfs sont en mille morceaux.", "깜짝 놀랐잖아요. 오늘은 신경이 산산조각이에요."),
(V, "Alors un conseil. Ce soir, quand tout sera fini, asseyez-vous cinq minutes, seule, dans la salle vide.", "그럼 조언 하나. 오늘 저녁 다 끝나면 텅 빈 홀에 혼자 오 분만 앉아 있어요."),
(H, "Pourquoi cinq minutes ?", "왜 오 분이에요?"),
(V, "Pour écouter la maison. Elle vous dira merci. Les maisons aussi, ça parle.", "집의 소리를 들으려고요. 집이 고맙다고 말해 줄 거예요. 집도 말을 해요."),
(H, "Je le ferai. Promis. Vous prendrez un café, un dessert ?", "그렇게 할게요. 약속해요. 커피나 디저트 드시겠어요?"),
(V, "Une tarte Tatin, bien sûr. Et un café. Pas de sucre, il faut garder la ligne.", "타르트 타탱 당연히요. 그리고 커피. 설탕은 빼고요, 몸매 관리를 해야죠."),
(None, "14 h 15. La salle se vide doucement. Chloé dessert une table, Julien compte la caisse. Hélène s'appuie au chambranle, épuisée.", "오후 2시 15분. 홀이 서서히 비어 간다. 클로에는 테이블을 치우고, 쥘리앵은 계산대를 센다. 엘렌은 지쳐서 문틀에 기댄다."),
(J, "Alors, chef. Bilan du premier service ? Trente-huit couverts. Aucune annulation.", "그럼 셰프. 첫 서비스 결산은? 서른여덟 명. 취소는 없었어."),
(H, "Trente-huit. En comptant les quatre qui ont attendu debout ?", "서른여덟. 서서 기다린 네 명도 포함해서?"),
(J, "En les comptant. Et deux ont réservé pour jeudi soir, avant même de payer.", "포함해서야. 그리고 두 분은 계산도 하기 전에 목요일 저녁을 예약했어."),
(C, "Chef, une dame m'a dit en payant qu'elle avait donné vingt euros pour la réouverture.", "셰프님, 어떤 부인이 계산하시면서 재개점을 위해 이십 유로를 기부했다고 하셨어요."),
(H, "Elle s'appelle comment ? On a son nom sur la liste des mille deux cent trente-sept.", "이름이 뭐래? 천이백삼십칠 명 명단에 이름이 있을 텐데."),
(C, "Josette. Elle a dit qu'elle n'a pas d'argent, mais qu'elle voulait un bout du Comptoir.", "조제트라고 하세요. 돈은 많지 않지만 콤투아르의 한 조각을 갖고 싶었대요."),
(H, "Un bout du Comptoir. Dis-lui qu'elle a gagné un coin d'ardoise et un dessert offert, la prochaine fois.", "콤투아르의 한 조각이라. 칠판 한 귀퉁이와 다음에 올 때 디저트 서비스를 얻었다고 전해."),
(J, "Je m'en occupe. Elle est encore dans l'entrée, je vais la rattraper avant qu'elle ne parte.", "제가 처리할게요. 아직 입구에 계시니 가시기 전에 붙잡을게요."),
(C, "Je viens avec toi. Je veux voir sa tête quand tu lui annonces la nouvelle.", "저도 같이 갈게요. 소식을 전할 때 얼굴이 어떨지 보고 싶어요."),
(C, "Moi, j'ai fait une erreur, une seule : la boisson de la table six. Mais je l'ai réparée.", "저는 실수 하나만 했어요, 6번 음료. 하지만 수습했어요."),
(H, "Tu l'as réparée avec le sourire. Tu es devenue une vraie professionnelle, Chloé.", "웃으면서 수습했잖아. 진짜 프로가 됐어, 클로에."),
(C, "Vraiment ? Vous le pensez, ou vous êtes fatiguée ?", "정말요? 진심이세요, 아니면 피곤해서 하시는 말씀이세요?"),
(H, "Les deux. Dans les deux cas, c'est vrai.", "둘 다야. 어느 쪽이든 사실이야."),
(J, "Putain, on y est arrivés. Je n'y croyais qu'à moitié, ce matin.", "젠장, 우리가 해냈어. 아침엔 반쯤만 믿었는데."),
(H, "Moi, je n'y croyais pas du tout. Mais vous, vous y croyiez pour deux.", "나는 전혀 안 믿었어. 그래도 너희가 둘이 믿어 줬어."),
(None, "Karim sort de la cuisine, torchon sur l'épaule, un grand sourire fatigué. Il applaudit en silence.", "카림이 어깨에 행주를 걸치고 지친 미소를 지으며 주방에서 나온다. 소리 없이 박수를 친다."),
(J, "Regarde-le. L'homme qui n'a pas parlé de la matinée, et qui parle maintenant avec ses mains.", "저 사람 좀 봐. 아침 내내 말 한마디 안 하더니 지금은 손으로 말하네."),
(H, "Karim, viens. Qu'est-ce que tu veux dire ?", "카림, 이리 와. 하고 싶은 말이 뭐야?"),
(C, "Il dit « merci chef », avec les mains. Je crois.", "손으로 « 고맙습니다 셰프 »라고 하는 것 같아요."),
(H, "Merci à toi aussi, Karim. Sans toi, je n'aurais pas tenu.", "너도 고마워, 카림. 네가 없었으면 난 버티지 못했을 거야."),
(J, "Allez, un dernier tour de salle ? Les tables sont vides, mais l'ardoise est toujours pleine.", "자, 홀 한 바퀴 더 돌까? 테이블은 비었지만 칠판은 여전히 가득해."),
(H, "Pas tout de suite. Je m'assois d'abord. Madame Vasseur m'a donné un devoir.", "지금은 말고. 먼저 앉을게. 바쉐 부인이 숙제를 내 주셨거든."),
(None, "Hélène s'assoit à la table sept, face à la fenêtre. Julien éteint une lampe sur deux. Un silence doux tombe sur la salle.", "엘렌이 창을 마주한 7번 테이블에 앉는다. 쥘리앵이 등을 하나 걸러 끈다. 부드러운 침묵이 홀에 내린다."),
(H, "Enfin. On est rentrés. Merci, la maison.", "마침내. 우리가 돌아왔어. 고마워, 우리 집."),
]

VOCAB = [
("A2", "Bienvenue au Comptoir.", "콤투아르에 오신 걸 환영합니다.", "첫 손님을 맞이하는 기본 인사. 단골에게는 « Content de vous revoir. », 오랜만이면 « Bon retour parmi nous. »"),
("A2", "Content(e) de vous revoir.", "다시 뵙게 되어 반갑습니다.", "« Content de vous revoir. » 남성은 content, 여성은 contente. vous 를 쓰면 정중하고, 친구에게는 « Content de te revoir. »"),
("B1", "J'ai l'estomac noué.", "속이 꼬인 듯 불안하다.", "[구어] « J'ai l'estomac noué. » 긴장해서 식욕이 없을 때. ↔ 정중: Je suis très anxieuse."),
("B1", "Être à cran", "신경이 곤두서 있다", "[구어] « Je suis à cran. » 극도로 긴장해 작은 일에도 예민한 상태. ↔ 정중: Je suis très tendue."),
("B1", "Être prêt(e) / se mettre en place", "준비되다 / 자리를 잡다", "« Allez, on se met en place. » 영업 전에 각자 위치에 서는 주방·홀 표현. 대명동사."),
("B1", "Rattraper le coup", "상황을 수습하다", "[구어] « Tu rattrapes le coup avec le sourire. » 실수를 만회할 때. ↔ 정중: Vous avez bien réparé l'erreur."),
("B1", "Un habitué / un inconnu", "단골 / 낯선 사람", "« Un habitué, c'est « Content de vous revoir ». » 손님 유형에 따라 인사가 달라진다."),
("B2", "J'ai peur que ce ne soit plus pareil.", "예전 같지 않을까 봐 무섭다.", "« J'avais peur que ce ne soit plus pareil. » avoir peur que + 접속법. 부정의 ne 는 문어적 허사(ne explétif)."),
("B2", "Ça entre bien.", "(손님이) 잘 들어온다.", "[구어] « Ça entre bien. » 식당에서 손님·주문이 순조롭게 들어오는 상황. ↔ 정중: L'affluence est bonne."),
("B2", "Un coup de feu", "가장 바쁜 시간대", "« Le rush passe. » 홀·주방이 최고로 바쁜 시간. le coup de feu 와 le rush 는 같은 의미."),
("B2", "Je plaisante, souriez un peu.", "농담이에요, 좀 웃어요.", "« Je plaisante, Hélène. Souriez un peu. » 농담이 무거워졌을 때의 수습 표현. 비슷한 표현: Je rigole."),
("B2", "Dresser / desservir une table", "상을 차리다 / 상을 치우다", "« Chloé dessert une table. » desservir 는 상을 치우는 동작. 반의어는 dresser, mettre le couvert."),
("B2", "Garder la ligne", "몸매를 유지하다", "[구어] « Il faut garder la ligne. » 다이어트를 가볍게 말하는 표현. ↔ 정중: Surveiller son poids."),
("B2", "Planté(e) comme un piquet", "말뚝처럼 우두커니 서 있는", "[구어] « Ne reste pas planté là comme un piquet. » 아무것도 안 하고 서 있는 사람에게. ↔ 정중: Ne restez pas immobile."),
("B2", "À cause de vous / grâce à vous", "당신 때문에 / 당신 덕분에", "« À cause de vous, je n'ai pas dormi. » à cause de 는 부정적 이유, grâce à 는 긍정적. 감정의 방향을 구분한다."),
("C1", "Retenir son souffle", "숨을 죽이다", "« La salle semble retenir son souffle. » 긴장의 순간을 묘사하는 관용 표현. 안도하면 respirer, souffler."),
("C1", "Je n'y croyais qu'à moitié.", "반쯤만 믿었다.", "« Je n'y croyais qu'à moitié, ce matin. » ne ... que 구문이 '~뿐'을 만들어 확신이 약했음을 표현."),
("C1", "Croire pour deux", "둘 몫으로 믿어 주다", "« Vous y croyiez pour deux. » 한 사람이 지친 만큼 다른 사람이 더 믿어 준다는 연대의 표현."),
("C1", "Avoir les mains qui tremblent", "손이 떨리다", "« Mes mains tremblaient sur les couteaux. » 긴장의 신체 증상. 비슷한 표현: avoir la gorge nouée."),
("C1", "Ça m'a fait un bien fou.", "정말 큰 위로가 됐다.", "[구어] bien fou = 엄청나게 좋다. ↔ 정중: Cela m'a beaucoup soulagée. 안도와 기쁨을 함께 담을 때."),
("C1", "Avoir le front perlé de sueur", "이마에 땀방울이 맺히다", "« Le front perlé de sueur. » 땀이 이슬처럼 맺힌 모습을 묘사하는 문어적 표현. 긴장·노동을 암시."),
("C1", "Écouter la maison", "집의 소리를 듣다", "« Pour écouter la maison. Elle vous dira merci. » 장소에 마음을 건네는 시적 표현. 의인화로 감정을 정리한다."),
]

GRAM = [
("A2", "환영과 안부 — Bienvenue / Content de vous revoir", "« Bienvenue au Comptoir de Marthe. » « Content de vous revoir. » 첫 방문과 재방문의 인사를 구분한다. « Par ici, je vous prie. » 처럼 안내 표현도 정중한 vous."),
("B1", "근접미래·단순미래 — Je monte le chauffage / Elle vous dira merci.", "« Je monte le chauffage tout de suite. » « Elle vous dira merci. » 즉각 행동은 현재형으로, 예측과 약속은 단순미래(dira)로 말한다."),
("B1", "감정의 부사 — tellement, trop, un peu", "« Tellement propres qu'ils ont l'air invisibles. » « Trop chaude. » « Un peu froide. » 정도 부사로 불만과 놀람을 완화하거나 강조한다."),
("B2", "avoir peur que + 접속법 — J'avais peur que ce ne soit plus pareil.", "« J'avais peur que ce ne soit plus pareil. » 두려움·희망의 표현 뒤에는 접속법(soit). 두려움이 실현되지 않았을 때 ne 를 붙이는 문어체 습관."),
("B2", "대명사 y / en — J'y croyais, J'en ai marre", "« Je n'y croyais qu'à moitié. » « Vous y croyiez pour deux. » y 는 croire à ~ 를 받는다. 구어에서 자주 쓴다."),
("B2", "명령형과 부정 명령 — Respire, Ne t'excuse pas", "« Respire, chef. » « Ne t'excuse pas, c'est normal. » 부정 명령은 ne ... pas 사이에 대명사. tu 형에서 -er 동사는 s 를 뺀다."),
("C1", "대과거 — Je n'ai pas dormi / elle s'était assise", "« Il s'était juste assis à la mauvaise salle d'attente. » 과거보다 앞선 일은 plus-que-parfait. 농담과 회상을 섞을 때 자주 쓴다."),
("C1", "조건과 추측 — Sans toi, je n'aurais pas tenu.", "« Sans toi, je n'aurais pas tenu. » sans + 명사 + 조건법 과거로 '~가 없었다면 버티지 못했을 것'. 감사의 가장 강한 표현."),
]

READ = [
("리에종 — vous_attend, c'est_un, mille_deux", "« Votre table vous attend » /vɔtʁ.tabl.vu.za.tɑ̃/ 에서 s 가 z 로 이어진다. « C'est un bon début » /sɛ.tœ̃.bɔ̃.de.by/ 의 t. « mille deux cent » 의 l 은 이어 읽지 않는다."),
("억양 — 안도와 긴장", "« Putain, ça y est. » 는 숨을 내쉬듯 낮게 시작해 끝에서 약간 올린다. « Trente-huit couverts ? » 는 놀람으로 끝을 올리고, « C'est bon. » 은 내려서 안정감을 만든다."),
("비음 — content, attendre, bonjour", "« content » /kɔ̃.tɑ̃/ 은 ɔ̃ 과 ɑ̃ 이 한 단어에 있다. « attendent » /a.tɑ̃d/. « bonjour » /bɔ̃.ʒuʁ/ 의 ɔ̃ 은 코로 부드럽게 빠진다."),
("r — revoir, respirer, rouvrir", "« rouvrir » /ʁu.vʁiʁ/ 은 어두 r 과 어말 r 이 둘 다 있는 제목. 어두는 가볍게, 어말은 거의 들릴 듯 말 듯 약하게. « revoir » /ʁə.vwaʁ/."),
("호흡 구간 — 환영 인사", "« Bonjour, / mesdames et messieurs ! / Bienvenue / au Comptoir de Marthe. / Entrez, entrez, / il fait chaud ici. » 인사는 끊어서 천천히 읽어 따뜻한 느낌을 낸다."),
("u 와 ou — tout de suite, doucement", "« tout » /tu/ 와 « de suite » /də.sɥit/ 의 ɥi 를 구분한다. « doucement » /dus.mɑ̃/ 의 ou 는 입술을 모으고 뒤쪽에서 낸다."),
("긴 문장 — 숨 쉬는 위치", "« Je n'ai pas dormi de la nuit, / à cause de vous, / à cause de ce qu'on est devenus. » 쉼표마다 숨을 끊으면 감정이 쌓이는 느낌이 산다."),
]

CULTURE = [
("재개점 첫날 — la réouverture", "프랑스의 소규모 식당이 오래 쉬었다가 다시 문을 여는 날은 단골과 이웃이 가장 먼저 찾아와 가게의 생존을 함께 확인하는 날이다. 칠판에 후원자 수를 적고, 첫 손님에게 커피를 서비스하는 일은 흔하다. 첫날의 잔잔한 성공은 그 뒤의 신뢰를 결정한다."),
("서버의 환영 인사 — l'accueil", "프랑스 식당의 서버는 « Bonjour, bienvenue » 로 시작해 손님에게 먼저 인사하는 것이 예의다. 코트를 받고, 자리로 안내하고, 단골의 취향을 기억하는 것이 서비스의 기본이며, 과도한 미소보다 진심 어린 존중이 중요하다."),
]

META = dict(part=4, ep=54, part_label="제4부 La reconstruction · 늦가을·겨울", title_fr="Rouvrir", title_ko="다시 문을 열다",
 place="Le Comptoir de Marthe, 12월 15일 화요일 점심 (오전 10시 30분 ~ 오후 2시 15분)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · Mme Vasseur (단골 손님)",
 wine="재개점 첫날 점심. 오픈 직전의 긴장, 첫 손님, 바쉐 부인의 7번석 복귀, 서른여덟 명의 서비스와 안도.",
 focus="환영 인사, 긴장·안도 표현, avoir peur que + 접속법, 대명사 y/en, 조건법 과거",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제55화 « Victor frappe à la porte » : 12월 17일 목요일, 맞은편 식당 주인 빅토르가 공동 구매와 행사 협력을 제안하러 온다.")
