# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, V = "Hélène", "Lucien", "Julien", "Victor"
D = [
(None, "Jeudi 17 décembre, 15 h 10. Le service de midi est fini, la salle sent encore la peinture fraîche. Sur l'ardoise : « Merci à vous 1 237. » Hélène vérifie des bons de livraison au comptoir, Lucien boit son café, Julien essuie des verres.", "12월 17일 목요일 오후 3시 10분. 점심 영업은 끝났지만 홀에는 아직 새 페인트 냄새가 난다. 칠판에는 « 후원해 주신 1,237분께 감사드립니다. » 엘렌은 카운터에서 납품서를 확인하고, 뤼시앵은 커피를 마시고, 쥘리앵은 잔을 닦는다."),
(J, "Mme Vasseur est repartie ravie. Elle a dit que la peinture était « acceptable ».", "바세르 부인은 아주 만족해서 돌아가셨어. 페인트가 \"봐줄 만하다\"고 하시더라."),
(H, "« Acceptable » ? Chez elle, c'est une médaille d'or.", "\"봐줄 만하다\"? 그분한테는 금메달이나 마찬가지지."),
(L, "Trente ans à la table sept, elle a le droit d'être difficile. L'essentiel, c'est qu'elle soit revenue.", "7번 테이블에서 30년이면 까다로울 자격이 있지. 중요한 건 돌아왔다는 거야."),
(H, "Jeudi, steak-frites, Henri qui dit rien. On dirait que rien n'a changé.", "목요일, 스테이크 프리트, 말 한마디 없는 앙리. 아무것도 안 변한 것 같네."),
(J, "Sauf le plafond. Et le chiffre sur l'ardoise : mille deux cent trente-sept.", "천장만 빼고. 그리고 칠판의 숫자도. 1,237."),
(L, "Mille deux cent trente-sept personnes ont mis la main au portefeuille pour nous. On n'oublie pas ça.", "1,237명이 우리를 위해 지갑을 열었어. 그건 잊으면 안 돼."),
(H, "Je l'oublie pas, Papa. Je le relis chaque matin en écrivant le menu.", "안 잊어요, 아빠. 매일 아침 메뉴 쓸 때 다시 읽는걸요."),
(None, "On frappe à la vitrine. Dehors, un homme en manteau sombre tient une bouteille et fait un petit signe de la main.", "유리문을 두드리는 소리. 밖에서 어두운 코트를 입은 남자가 병을 들고 작게 손짓한다."),
(J, "Euh... Hélène ? Quelqu'un frappe à la porte. Et je crois que tu le connais.", "음... 엘렌? 누가 문을 두드리는데. 아는 사람일 것 같아."),
(H, "On est fermés jusqu'à dix-neuf heures. Il sait lire, non ?", "저녁 7시까지 휴업이야. 글자는 읽을 줄 알겠지?"),
(J, "C'est Victor Lambert. Avec une bouteille et un grand sourire.", "빅토르 랑베르야. 병 하나랑 함박웃음을 들고."),
(L, "Un voisin qui arrive avec un cadeau, méfie-toi. Souviens-toi du cheval de Troie.", "선물 들고 오는 이웃은 조심해라. 트로이의 목마를 떠올려 봐."),
(H, "Papa, ici c'est la rue Saint-Maur, pas Troie. Julien, ouvre-lui.", "아빠, 여긴 트로이가 아니라 생모르 거리예요. 쥘리앵, 열어 줘."),
(J, "Bonjour, monsieur Lambert. Entrez, vous allez prendre froid.", "안녕하세요, 랑베르 씨. 들어오세요, 감기 걸리겠어요."),
(V, "Merci, Julien. Bonjour, Lucien. Bonjour, Hélène. Je vous dérange en plein creux de l'après-midi, je sais.", "고마워요, 쥘리앵. 안녕하세요, 뤼시앵. 안녕하세요, 엘렌. 한창 쉬는 오후 시간에 방해하는 거 알아요."),
(H, "Un peu, oui. Livreurs, factures, peinture qui sèche... Vous avez cinq minutes, pas plus.", "조금요. 배달, 청구서, 마르는 페인트... 5분이에요, 그 이상은 안 돼요."),
(V, "Cinq minutes me suffiront. Tenez, c'est pour la réouverture : un savagnin du Jura.", "5분이면 충분해요. 자, 재개점 선물이에요. 쥐라 지방 사바냥이에요."),
(H, "C'est gentil. Mais je ne sais pas encore ce que vous voulez en échange.", "고마워요. 그런데 그 대가로 뭘 원하시는지 아직 모르겠네요."),
(V, "Rien. Enfin, si : cinq minutes. Mais la bouteille est gratuite, je vous le jure.", "아무것도요. 아니, 있긴 하네요. 5분. 그래도 병은 공짜예요, 맹세해요."),
(L, "Au moins, il est honnête. Posez ça sur le comptoir, jeune homme. Un café ?", "적어도 정직하군. 그건 카운터에 올려놓게, 젊은이. 커피 한잔?"),
(None, "Lucien sert une tasse à Victor, qui reste debout près de la porte, son manteau toujours sur les épaules.", "뤼시앵이 빅토르에게 잔을 건넨다. 빅토르는 코트를 걸친 채 문 가까이에 서 있다."),
(V, "Avec plaisir. C'est toujours la même machine ? Elle date de Marthe, non ?", "고맙습니다. 아직 그 기계예요? 마르트 때부터 있던 거죠?"),
(L, "Mêmes tuyaux, même mauvais caractère. Comme ma fille.", "같은 배관, 같은 고약한 성질. 내 딸처럼."),
(H, "Papa !", "아빠!"),
(V, "Je le prends comme un compliment. Elle est belle, votre salle. Plus claire, plus calme.", "칭찬으로 받아들일게요. 홀이 예쁘네요. 더 밝고 더 차분해졌어요."),
(H, "Elle n'a jamais été aussi propre. Avant, les murs jaunes faisaient cuisine de grand-mère.", "이렇게 깨끗한 적이 없었죠. 예전엔 노란 벽 때문에 할머니 부엌 같았거든요."),
(V, "Et ce chêne, derrière l'ardoise ? Il est magnifique.", "그리고 칠판 뒤의 저 참나무는요? 정말 근사해요."),
(J, "C'est monsieur Lopes qui l'a posé, la veille de la réouverture. Il a travaillé jusqu'à minuit.", "로페스 씨가 재개점 전날 달았어요. 자정까지 일했죠."),
(V, "Beau travail. Et ce chiffre, en bas : « 1 237 ». Ce sont les gens qui vous ont aidés ?", "훌륭한 솜씨네요. 그리고 아래쪽 이 숫자, « 1,237 ». 도와준 분들 수예요?"),
(H, "Oui. Chaque nom est sur une liste, sous la caisse. Je les connais presque tous.", "네. 이름은 하나하나 계산대 밑 명단에 있어요. 거의 다 기억해요."),
(V, "Alors vous ne trouverez pas le mien. J'ai donné quarante euros, en cochant « anonyme ».", "그럼 제 이름은 못 찾으실 거예요. 40유로를 냈는데 \"익명\"에 체크했거든요."),
(H, "Vous avez... Pardon ? Vous avez participé à la collecte ?", "당신이... 뭐라고요? 모금에 참여했다고요?"),
(L, "Ça alors. Un concurrent qui finance la concurrence.", "이런. 경쟁자가 경쟁자 돈을 대 주다니."),
(V, "Ce n'est pas de la charité, Lucien. C'est de l'intérêt bien compris. Je vais vous expliquer.", "자선이 아니에요, 뤼시앵. 현명한 이해타산이죠. 설명해 드릴게요."),
(H, "J'écoute. Mais vous restez debout : vous avez dit cinq minutes.", "들을게요. 하지만 서 계세요. 5분이라고 하셨잖아요."),
(V, "Parfait. J'ai deux propositions. La première, ce sont des achats groupés.", "좋아요. 제안이 두 가지 있어요. 첫째는 공동 구매예요."),
(H, "Des achats groupés ? Avec vous ? Pour quoi faire ?", "공동 구매요? 당신이랑요? 뭘 위해서요?"),
(V, "Pour le beurre, les œufs, la farine et l'huile. J'ai appelé Bastide hier.", "버터, 달걀, 밀가루, 기름이요. 어제 바스티드에게 전화했어요."),
(H, "Vous avez appelé Bastide sans me prévenir ?", "나한테 말도 없이 바스티드한테 전화했다고요?"),
(V, "Exprès. Je voulais savoir si c'était possible avant de vous embêter.", "일부러요. 귀찮게 해 드리기 전에 가능한 일인지 먼저 알고 싶었어요."),
(J, "Et il a dit quoi, Bastide ? D'habitude, il en dit beaucoup.", "바스티드가 뭐래요? 평소엔 말이 많은 분인데."),
(V, "Que les producteurs pourraient livrer davantage, si on commandait à deux.", "우리가 둘이 같이 주문하면 생산자들이 더 많이 납품할 수 있을 거라고요."),
(H, "Mes producteurs. Ceux du contrat de novembre. Ils ont signé avec moi, pas avec vous.", "내 생산자들이에요. 11월 계약을 맺은 분들이죠. 나랑 서명했지, 당신이랑 한 게 아니에요."),
(V, "Je sais. Je ne veux rien leur prendre. Je veux ajouter mes volumes aux vôtres.", "알아요. 그분들에게서 뭘 뺏으려는 게 아니에요. 제 물량을 당신 물량에 더하려는 거예요."),
(V, "Je prends cent vingt kilos de beurre par mois. Vous, quarante, c'est ça ?", "저는 한 달에 버터를 120킬로 써요. 당신은 40킬로, 맞죠?"),
(H, "À peu près. Vous êtes bien renseigné.", "대충요. 정보가 빠르시네요."),
(V, "À cent soixante kilos, le producteur descend de onze euros à neuf euros soixante le kilo.", "160킬로가 되면 생산자가 킬로당 11유로에서 9유로 60센트로 내려요."),
(J, "Un euro quarante de moins au kilo. Sur quarante kilos, ça fait cinquante-six euros par mois.", "킬로당 1유로 40센트 싸지네. 40킬로면 한 달에 56유로야."),
(L, "Cinquante-six euros ! Pour ça, on vend son âme ?", "56유로! 그걸로 영혼을 팔아?"),
(J, "Ça fait quand même six cent soixante-douze euros par an, Lucien. Rien que pour le beurre.", "그래도 1년이면 672유로예요, 뤼시앵. 버터만 해서."),
(H, "Et avec les œufs, la farine, l'huile ? Ça fait combien en tout ?", "달걀, 밀가루, 기름까지 하면요? 전부 얼마죠?"),
(V, "Pour vous, entre mille et mille deux cents euros par an. Pour moi, bien plus. Je ne vais pas mentir.", "당신은 1년에 1,000에서 1,200유로쯤. 저는 훨씬 더 많고요. 거짓말은 안 할게요."),
(H, "Voilà. Vous gagnez plus que moi. C'est ça, votre « intérêt bien compris ».", "그렇군요. 당신이 나보다 더 벌어요. 그게 당신의 \"현명한 이해타산\"이네요."),
(V, "Oui. Je gagne plus que vous, et vous gagnez quand même. C'est du donnant-donnant.", "맞아요. 저는 당신보다 더 벌고, 당신도 어쨌든 벌어요. 주고받기죠."),
(H, "Et mes producteurs ? Si vous tirez les prix vers le bas, ils vont me le reprocher.", "내 생산자들은요? 당신이 가격을 끌어내리면 나를 원망할 텐데요."),
(V, "Ils vendront plus. Ils perdent un peu au kilo, mais ils gagnent cent vingt kilos par mois.", "더 많이 팔게 돼요. 킬로당은 조금 손해지만 한 달에 120킬로를 더 팔잖아요."),
(H, "C'est le raisonnement de quelqu'un qui n'a jamais eu un producteur furieux au téléphone.", "화난 생산자와 전화해 본 적 없는 사람의 논리네요."),
(V, "Détrompez-vous. Mon ancien fournisseur m'a lâché en pleine saison. J'ai compris la leçon.", "오해예요. 예전 납품업자가 한창 성수기에 저를 버렸어요. 교훈은 얻었죠."),
(L, "Remarquez, ne pas mettre tous ses œufs dans le même panier, ça se défend.", "하긴, 달걀을 한 바구니에 다 담지 말라는 말도 일리는 있지."),
(V, "C'est mon argument, Lucien. Là, vous auriez deux paniers, et moi aussi.", "제 논리가 그거예요, 뤼시앵. 그러면 당신도 바구니가 둘, 저도 둘이죠."),
(H, "Mes conditions, alors. Ce sont les producteurs qui décident. Pas vous, pas moi.", "그럼 내 조건이에요. 결정은 생산자들이 해요. 당신도 나도 아니고요."),
(V, "D'accord. S'ils veulent me rencontrer, j'irai avec vous à la ferme.", "좋아요. 그분들이 저를 만나고 싶어 하면 같이 농장에 갈게요."),
(H, "Et chacun paie sa facture à soixante jours. Pas de mélange des comptes.", "그리고 각자 자기 청구서를 60일 안에 내요. 장부를 섞지 않는 거예요."),
(V, "Chacun ses comptes. Je signe pour douze mois, comme vous.", "각자 장부는 각자. 저도 당신처럼 12개월로 서명할게요."),
(H, "Je n'ai pas dit oui. J'ai dit : mes conditions.", "승낙한 게 아니에요. 내 조건이라고 했을 뿐이죠."),
(V, "Je traduis : « peut-être », très poliment.", "통역하면, 아주 정중한 \"어쩌면\"이네요."),
(J, "Chez Hélène, un « peut-être » poli, c'est un oui qui n'ose pas encore.", "엘렌한테 정중한 \"어쩌면\"은 아직 용기를 못 낸 \"좋아요\"예요."),
(H, "Et la deuxième proposition ? Je sens qu'elle est pire.", "두 번째 제안은요? 더 나쁠 것 같은 예감이 드는데."),
(V, "Elle est plus fragile. Je voudrais une soirée à deux, un samedi de février.", "더 조심스러운 제안이에요. 2월의 어느 토요일에 둘이 함께하는 저녁이요."),
(V, "Un dîner croisé : apéritif et entrée chez moi, le plat chez vous, le dessert chez moi.", "교차 만찬이에요. 식전주와 앙트레는 우리 집, 메인은 당신 집, 디저트는 다시 우리 집."),
(H, "Le plat principal chez moi... Vous me donnez le beau rôle. Pourquoi ?", "메인 요리가 우리 쪽이라... 나한테 좋은 역할을 주네요. 왜죠?"),
(V, "Parce que votre blanquette est la meilleure du quartier. Tout le monde le sait.", "당신의 블랑케트가 동네 최고니까요. 모두 알아요."),
(H, "Ne me flattez pas. Ça marche rarement.", "아첨하지 마세요. 잘 안 통해요."),
(V, "Je ne flatte pas, je constate. Mon plat du jour est moins bon que le vôtre, mais il coûte moins cher.", "아첨이 아니라 사실을 말하는 거예요. 제 오늘의 요리는 당신 것보다 맛은 덜하지만 값은 싸죠."),
(J, "Quarante convives à quarante-huit euros, tout compris : ça fait mille neuf cent vingt euros à partager.", "손님 40명에 인당 48유로, 전부 포함이면 1,920유로를 나누게 되네요."),
(V, "Voilà. Mille neuf cent vingt euros en deux, et surtout deux salles pleines en février.", "맞아요. 1,920유로를 둘이 나누고, 무엇보다 2월에 홀 두 곳이 가득 차죠."),
(L, "Février, c'est le mois creux. Sur ce point, il a raison.", "2월은 한산한 달이지. 그 점은 이 친구 말이 맞아."),
(H, "Et mes habitués chez vous ? Ils verront vos prix, plus bas que les miens, et ils ne reviendront plus.", "내 단골들이 당신 가게에 가면요? 나보다 싼 가격을 보고 다시는 안 올 텐데요."),
(V, "Ou ils verront que votre assiette est plus généreuse que la mienne, et ils reviendront chez vous.", "아니면 당신 접시가 제 것보다 푸짐하다는 걸 보고 당신한테 다시 올 거예요."),
(V, "Les gens comparent, Hélène. Mais ils n'ont qu'un ventre, ils ne dînent pas deux fois.", "사람들은 비교하죠, 엘렌. 하지만 배는 하나라서 저녁을 두 번 먹지는 않아요."),
(H, "Pourquoi maintenant ? Pourquoi pas en septembre, quand on était à terre ?", "왜 하필 지금이죠? 우리가 바닥에 있던 9월은 왜 아니었고요?"),
(V, "En septembre, vous aviez fermé. Ma salle était pleine, et la rue était morte.", "9월엔 문을 닫으셨죠. 제 홀은 찼는데 거리는 죽어 있었어요."),
(V, "Je n'aimais pas ça. Un restaurant tout seul dans une rue vide, ça tient mal.", "그게 싫었어요. 텅 빈 거리에 식당 하나만 있으면 버티기 힘들어요."),
(J, "Une rue qui vit attire du monde. Il n'a pas tort, Hélène.", "활기 있는 거리는 사람을 끌죠. 틀린 말은 아니야, 엘렌."),
(H, "Ça, c'est le côté calcul. Et le côté sincère ? Il y en a un, non ?", "그건 계산 쪽이고요. 진심 쪽은요? 있긴 하죠, 안 그래요?"),
(V, "Oui. À dix-neuf ans, votre mère m'a pris comme plongeur. Un mois d'été.", "있어요. 열아홉 살 때 어머님이 저를 설거지 담당으로 써 주셨어요. 여름 한 달 동안이요."),
(V, "Je cassais trois assiettes par jour. Elle me répétait toujours la même phrase.", "저는 하루에 접시를 세 개씩 깼어요. 어머님은 늘 같은 말씀을 하셨죠."),
(L, "« On ne cuisine pas contre quelqu'un, on cuisine pour quelqu'un. » Je l'entends encore.", "\"누구에 맞서 요리하는 게 아니야, 누군가를 위해 요리하는 거지.\" 지금도 들리는구먼."),
(H, "Elle me l'a dite aussi. J'avais dix ans, je pleurais parce qu'une copine avait gagné le concours de gâteaux.", "나한테도 하셨어요. 열 살 때, 친구가 케이크 대회에서 이겼다고 울었거든요."),
(L, "Elle la disait à tout le monde. Même au facteur.", "누구한테나 했지. 우체부한테도."),
(V, "Vous voyez : je n'ai rien inventé. J'ai juste mis vingt ans à comprendre.", "보세요, 제가 지어낸 게 아니에요. 이해하는 데 20년 걸렸을 뿐이죠."),
(H, "Ne jouez pas la carte de ma mère, Victor. C'est déloyal.", "우리 엄마 카드를 쓰지 마세요, 빅토르. 비겁해요."),
(V, "Vous avez raison, pardon. Je retire. Gardez le calcul, oubliez Marthe.", "맞아요, 죄송해요. 취소할게요. 계산은 남기고 마르트는 잊으세요."),
(H, "Non, je ne l'oublie pas. Je dis juste que ça ne suffit pas pour signer.", "아니요, 잊지 않아요. 서명하기엔 그걸로 부족하다는 말이에요."),
(L, "Voilà ma fille. Il a plaidé, elle a pesé. Maintenant elle va trancher.", "그게 내 딸이지. 저쪽은 변론했고 이쪽은 저울질했어. 이제 결정할 차례야."),
(H, "Achats groupés : trois mois d'essai, pas douze. Beurre et farine d'abord, à condition que les producteurs soient d'accord.", "공동 구매는 석 달 시험이에요, 열두 달 말고. 버터와 밀가루부터, 생산자들이 동의한다는 조건으로."),
(V, "Trois mois, ça me va. Et les producteurs, vous les appelez ou je les appelle ?", "석 달이면 좋아요. 생산자들한테는 당신이 전화해요, 제가 할까요?"),
(H, "Je les appelle. Ce sont mes producteurs, j'ai promis de ne rien décider sans eux.", "내가 해요. 내 생산자들이고, 그분들 없이는 아무것도 결정하지 않겠다고 약속했으니까."),
(V, "Très bien. Et le dîner croisé ?", "좋아요. 교차 만찬은요?"),
(H, "Je ne réponds pas aujourd'hui. Je veux d'abord voir les chiffres de janvier.", "오늘은 대답 안 해요. 먼저 1월 숫자를 보고 싶어요."),
(J, "Réponse après le Nouvel An. C'est raisonnable, non ?", "새해 지나고 대답한다. 합리적이잖아요?"),
(V, "C'est même plus que je n'espérais. Merci de m'avoir écouté.", "기대한 것보다 더 좋은데요. 들어 주셔서 감사합니다."),
(V, "Bon, je ne vous embête plus. Vous avez du travail, je file.", "자, 더는 귀찮게 안 할게요. 일 많으실 텐데 가 보겠습니다."),
(H, "Assieds-toi cinq minutes. Ton café va refroidir.", "5분만 앉아. 커피 식겠다."),
(None, "Silence. Victor, la tasse à la main, regarde Hélène. Julien et Lucien ne bougent plus.", "침묵. 빅토르가 잔을 든 채 엘렌을 바라본다. 쥘리앵과 뤼시앵은 꼼짝도 하지 않는다."),
(V, "Pardon ? Vous venez de dire « assieds-toi » ?", "네? 방금 \"앉아\"라고 하셨어요?"),
(H, "J'ai dit quoi ? Non. Enfin... oui. C'est sorti tout seul.", "내가 뭐라고 했죠? 아니에요. 어... 맞아요. 저절로 나왔어요."),
(J, "Elle a dit « assieds-toi ». Lucien, tu as entendu ? Trois témoins.", "\"앉아\"라고 했어요. 뤼시앵, 들었죠? 증인이 셋이에요."),
(L, "Parfaitement entendu. Ma fille, c'est un tournant historique.", "똑똑히 들었지. 얘야, 역사적인 전환점이구나."),
(H, "Ne faites pas les malins, tous les deux. C'est la fatigue. Trois jours de réouverture.", "둘 다 잘난 척하지 마. 피곤해서 그래. 재개점 사흘째라고."),
(V, "Je prends la fatigue comme excuse. Mais si ça vous va, on pourrait continuer comme ça.", "피곤 탓으로 해 두죠. 그래도 괜찮으시면 이대로 계속해도 좋겠는데요."),
(H, "Ne pousse pas... Ne poussez pas. Enfin, on verra. On y va doucement.", "밀어붙이지 마... 밀어붙이지 마세요. 어쨌든 두고 봐요. 천천히 가요."),
(V, "Doucement, c'est un très bon rythme. Je m'assieds.", "천천히가 아주 좋은 속도예요. 앉을게요."),
(H, "Et je garde la bouteille. Mais ça ne veut rien dire, tu entends ?", "그리고 병은 내가 받을게요. 하지만 아무 의미 없어, 알겠어?"),
(V, "Parfaitement. Deux fois « tu » en une minute. Je le note dans mon carnet.", "물론이죠. 1분에 \"너\"를 두 번. 수첩에 적어 둘게요."),
(L, "À la bonne heure ! Julien, un second café. Et pour le savagnin, ce soir, après le service.", "잘됐군! 쥘리앵, 커피 한 잔 더. 그리고 사바냥은 오늘 밤 영업 끝나고."),
(V, "Alors c'est moi qui vous fais un coup de main demain. Je vous envoie mon pâtissier pour la Tatin.", "그럼 내일은 제가 도와드릴게요. 우리 파티셰를 보내서 타탱을 같이 만들게요."),
(H, "Ne marche pas sur mes plates-bandes, Victor. La Tatin, c'est moi.", "내 영역을 침범하지 마, 빅토르. 타탱은 내 거야."),
(None, "Victor boit son café, serre la main de Lucien, salue Julien et sort dans la rue froide.", "빅토르는 커피를 마시고 뤼시앵과 악수한 뒤 쥘리앵에게 인사하고 차가운 거리로 나간다."),
(J, "Il est parti. Alors, tu lui fais confiance ?", "갔네. 그래서 그 사람 믿어?"),
(H, "Je lui fais confiance pour le beurre. Pour le reste, on verra. C'est un début.", "버터는 믿어. 나머지는 두고 봐야지. 시작이긴 해."),
(L, "Qui sème la méfiance récolte la solitude, ma fille. Mais qui ne se méfie pas récolte des ennuis.", "의심을 뿌리면 외로움을 거두는 법이다, 얘야. 그래도 의심 없으면 골치만 거두지."),
(L, "Je suis là pour ça. Et Marthe, elle, aurait déjà mis le couvert pour lui.", "그러라고 내가 있는 거지. 그리고 마르트라면 벌써 저 친구 몫의 식탁을 차렸을 게다."),
(H, "Elle aurait dit : « Retournez travailler. »", "엄마라면 이렇게 말했겠죠. \"가서 일들 해.\""),
]

VOCAB = [
("A2", "Un café ?", "커피 한잔?", "카페를 권할 때의 가장 짧은 문형. 손님·이웃 어디서나 쓴다. 대답은 « Avec plaisir. »"),
("B1", "frapper à la porte", "문을 두드리다", "« Quelqu'un frappe à la porte. » 노크는 frapper, 초인종은 sonner. 가게 문이 닫힌 시간에 오는 방문자의 전형적 장면."),
("B1", "un cadeau / ne pas mettre tous ses œufs dans le même panier", "선물 / 달걀을 한 바구니에 담지 마라(위험 분산)", "Lucien의 « ne pas mettre tous ses œufs dans le même panier, ça se défend » 처럼 속담은 문장 안에서 주어 자리에 그대로 둔다. 납품처 분산을 말할 때도 쓴다."),
("B1", "un coup de main", "도움의 손길", "[구어] « Je vous fais un coup de main. » ↔ 정중: « Je peux vous aider. » 가볍게 돕겠다는 말."),
("B1", "tutoyer / se tutoyer", "말을 놓다 / 서로 말을 놓다", "« On pourrait continuer comme ça. » 식으로 돌려 제안하는 경우가 많다. 상대가 먼저 말을 놓을 때까지 vous를 유지하는 것이 예의."),
("B1", "chacun ses comptes", "각자 자기 장부", "« Chacun ses comptes. » 돈은 섞지 않는다는 뜻. 동업·공동 구매의 기본 규칙."),
("B2", "des achats groupés", "공동 구매", "« des achats groupés » 여러 업체가 물량을 합쳐 단가를 낮추는 것. 반대로 가격 인하는 « tirer les prix vers le bas »."),
("B2", "à condition que + 접속법", "~라는 조건으로", "« à condition que les producteurs soient d'accord » 뒤에는 접속법. 같은 틀: pourvu que, à moins que."),
("B2", "mettre la main au portefeuille", "지갑을 열다(돈을 내다)", "« Mille deux cent trente-sept personnes ont mis la main au portefeuille. » 기부·후원의 완곡한 표현."),
("B2", "l'intérêt bien compris", "현명한 이해타산", "« Ce n'est pas de la charité, c'est de l'intérêt bien compris. » 이타적으로 보이지만 결국 자기에게도 이익이라는 뜻. 비즈니스 협상에서 솔직함을 연출하는 표현."),
("B2", "c'est du donnant-donnant", "주고받기다, 서로 이득이다", "[구어] « C'est du donnant-donnant. » ↔ 정중: « C'est un échange équitable. » 한쪽만 이득 보는 거래가 아니라는 말."),
("B2", "tirer les prix vers le bas", "가격을 끌어내리다", "« Si vous tirez les prix vers le bas, ils vont me le reprocher. » 큰 구매자가 납품가를 압박하는 상황."),
("B2", "se méfier de", "~를 경계하다", "« Méfie-toi. » 명령형은 se méfier 의 tu 형. 속담형: « Qui sème la méfiance récolte la solitude. »"),
("B2", "avoir le beau rôle", "좋은 역할을 맡다, 유리한 입장이다", "« Vous me donnez le beau rôle. » 겉으로 선심을 쓰는 사람의 속셈을 짚을 때 쓴다."),
("B2", "faire confiance à qqn pour qqch", "~에 관해서는 믿다", "« Je lui fais confiance pour le beurre. » 부분적 신뢰를 정중하게 한정하는 표현."),
("C1", "marcher sur les plates-bandes de qqn", "남의 영역을 침범하다", "[구어] « Ne marche pas sur mes plates-bandes. » ↔ 정중: « Ne vous mêlez pas de mon domaine. » 주방 영역 다툼에서 장난스럽게도 쓴다."),
("C1", "mettre du temps à + 부정사", "~하는 데 시간이 걸리다", "« J'ai juste mis vingt ans à comprendre. » 늦은 깨달음을 담담히 말할 때."),
("C1", "jouer la carte de qqn / de qqch", "~라는 카드를 꺼내다", "« Ne jouez pas la carte de ma mère. » 감정·인연을 협상에 이용한다는 비난."),
("C1", "déloyal", "비겁한, 불공정한", "« C'est déloyal. » 공정하지 못한 수단을 쓴 상대를 단호하게 비난하되 감정적 폭언은 아님."),
("C1", "plaider / peser / trancher", "변론하다 / 저울질하다 / 결정하다", "Lucien의 « Il a plaidé, elle a pesé. Maintenant elle va trancher. » 법정 비유로 협상 구도를 요약."),
("C1", "À la bonne heure !", "잘됐군! 훌륭하다!", "[구어] 약간 예스러운 감탄. ↔ 정중: « Très bien. » 나이 든 화자(Lucien)다운 어투."),
("C1", "un tournant historique", "역사적인 전환점", "« Ma fille, c'est un tournant historique. » 사소한 일(말을 놓음)을 과장해 놀리는 반어."),
("C1", "mettre le couvert pour qqn", "~의 식탁을 차리다(환대하다)", "« Marthe aurait déjà mis le couvert pour lui. » 조건법 과거 서술: 환대의 은유."),
("C1", "ça ne suffit pas pour signer", "서명하기엔 그것만으론 부족하다", "감정(마르트의 추억)과 계약(서명)을 분리하는 Hélène의 논리. « pour + 부정사 » 목적절."),
]

GRAM = [
("B1", "비교급·최상급 — plus / moins / aussi ... que", "Victor와 Hélène의 가게는 끊임없이 비교된다. « Mon plat du jour est moins bon que le vôtre, mais il coûte moins cher. » « votre assiette est plus généreuse que la mienne ». « Elle est plus claire, plus calme. » 우등비교 plus, 열등비교 moins, 동등비교 aussi 뒤에는 que 로 비교 대상을 잇는다. « Elle n'a jamais été aussi propre. » 처럼 부정문 속 aussi 는 최상급에 가까운 강조. bon 의 우등비교는 meilleur 이고 « la meilleure du quartier » 처럼 정관사를 붙이면 최상급이 된다."),
("B2", "조건의 접속법 — à condition que", "« à condition que les producteurs soient d'accord » 는 조건을 달면서 접속법을 요구한다. 뒤에 직설법 미래를 쓰고 싶으면 « à condition de + 부정사 » 또는 « si ». Hélène의 \"조건부 승낙\"이 문법에도 그대로 드러난다. 같은 문장에서 « trois mois d'essai, pas douze » 처럼 수량을 대비시켜 조건을 명확히 한다."),
("B1", "중복 대명사·강조 — c'est moi qui / c'est ... que", "« Alors c'est moi qui vous fais un coup de main demain. » 처럼 c'est ... qui 로 주어를 강조한다. 행동 주체가 누구인지 분명히 해야 하는 협상 장면에서 유용하다. « Elle me l'a dite aussi. » 의 me l'(간접·직접 목적 대명사) 순서도 확인: me → le/la/les."),
("B2", "양보·대조 — quand même / mais / sauf", "« Je gagne plus que vous, et vous gagnez quand même. » quand même 는 \"그래도 어쨌든\"의 양보. « Ça fait quand même six cent soixante-douze euros par an. » 처럼 앞 발언(56유로는 적다)에 반박하는 데 쓴다. mais 와 함께 « Ils perdent un peu au kilo, mais ils gagnent cent vingt kilos. » 식으로 이득과 손실을 대비."),
("B2", "tu / vous 전환 — 한 문장 안에서의 실수", "Hélène의 « Assieds-toi cinq minutes. » 와 « Ne pousse pas... Ne poussez pas. » 를 비교. 말을 놓는 전환은 보통 선언(« Si on se tutoyait ? »)이 아니라 이렇게 우연히 시작된다. 상대가 « Pardon ? Vous venez de dire « assieds-toi » ? » 처럼 확인하며 분위기를 가볍게 만드는 것도 관례."),
("B2", "조건법 과거(가정) — aurait + 과거분사", "« Marthe aurait déjà mis le couvert pour lui. » « Elle aurait dit : Retournez travailler. » 과거에 일어나지 않은 일을 추측할 때 조건법 과거. 형태는 avoir/être 조건법 + 과거분사. 고인(故人)의 반응을 상상하는 말투에 자주 쓴다."),
("B1", "수치 계산을 말로 풀기", "« Un euro quarante de moins au kilo. Sur quarante kilos, ça fait cinquante-six euros par mois. » « de moins » 로 차액을, « sur + 수량 » 으로 기준 수량을, « ça fait + 금액 » 으로 합계를 말한다. « par mois / par an » 으로 기간을 환산하는 것이 낭독의 요령."),
]

READ = [
("연음 — c'est un_intérêt", "« Ce n'est pas de la charité, c'est de l'intérêt bien compris. » 에서 c'est de_l'intérêt 의 de l' 와 intérêt 의 모음이 매끄럽게 이어진다. « l'intérêt » 의 tér 에 약한 강세. 한 호흡: Ce n'est pas de la charité, / c'est de l'intérêt bien compris."),
("r 소리 — rue, rien, très", "« Rien. Enfin, si : cinq minutes. » 의 rien 은 목구멍 안쪽에서 약하게 긁는 r 로 시작한다. « la rue Saint-Maur, pas Troie » 에서 rue 의 r 과 u(입술을 둥글게, 혀는 e 자리)를 천천히 연습한다."),
("비음 — un / on / an", "« Un voisin qui arrive avec un cadeau » 에서 un voisin 의 un[œ̃] 과 cadeau 앞 un 을 비교. « Mille deux cent trente-sept » 의 cent[sɑ̃], « on » 이 들어간 « mon / on / bon » 은 입술을 둥글게 모은 비음. 숫자 낭독 때 비음이 흐려지지 않게 한다."),
("숫자 낭독 — 1,237 / 672 / 1,920", "« mille deux cent trente-sept » (천 이백삼십칠) 에서 mille 는 복수 s 가 없고, 끝 t 는 읽는다. « six cent soixante-douze euros » 는 six cent / soixante-douze / euros 로 끊어 읽고 douze_euros 사이는 z 소리로 연음. « mille neuf cent vingt euros » 의 vingt_euros 도 t 연음."),
("억양 — 확인의 질문", "« Pardon ? Vous venez de dire « assieds-toi » ? » 처럼 확인 질문은 끝을 올린다. 한 호흡: Pardon ? / Vous venez de dire / « assieds-toi » ? 놀람은 « assieds-toi » 를 천천히, 올려서."),
("엘리종 — l'ardoise, j'ai, qu'on", "« Je l'oublie pas, Papa. » 에서 je l'oublie 는 [ʒəlubli]. ne 가 생략된 구어이므로 « Je ne l'oublie pas » 와 비교하면 소리가 짧아진다. « C'est sorti tout seul. » 의 c'est_sorti 도 리듬을 끊지 않고 이어 읽는다."),
("속담 낭독 — 박자를 두는 법", "« On ne cuisine pas contre quelqu'un, / on cuisine pour quelqu'un. » 처럼 대구가 있는 문장은 쉼표 앞에서 숨을 짧게 쉬고, contre 와 pour 에 강세를 둔다. 인용구 앞뒤는 약간 느려진다."),
]

CULTURE = [
("경쟁자와의 공동 구매(achats groupés)와 동업 문화", "프랑스 비스트로 업계에서는 이웃 식당끼리 버터·밀가루·와인을 합쳐 사는 일이 드물지 않다. 생산자에게도 정기적·대량 구매가 안정적 수입이 되기 때문이다. 단, 가게마다 취향이 달라 \"생산자는 생산자가 고른다\"는 암묵적 존중이 필요하다. 이 화에서 Hélène이 \"생산자들이 결정한다\"를 조건으로 내세우는 이유다."),
("« Dîner croisé » 와 거리 단위 이벤트", "한 구역의 식당이 코스를 나눠 맡는 \"교차 만찬\" 형식은 겨울 비수기(1~2월)에 유용한 마케팅이다. 손님은 한 번의 저녁에 두 가게를 경험하고, 가게는 손님을 공유한다. 프랑스에서는 이런 협력을 \"coopétition\"(경쟁+협력)이라 부르기도 한다."),
]

META = dict(part=4, ep=55, part_label="제4부 La reconstruction · 늦가을·겨울", title_fr="Victor frappe à la porte", title_ko="빅토르가 문을 두드리다",
 place="Le Comptoir de Marthe · 12월 17일(목) 오후 3시 10분, 점심 영업 후 휴식 시간",
 chars="Hélène Marchand (주인 셰프) · Lucien Marchand (아버지) · Julien Benali (홀 매니저) · Victor Lambert (맞은편 L'Atelier de Victor 사장)",
 wine="맞은편 경쟁자가 공동 구매와 합동 만찬을 제안한다 — 진심과 계산 사이의 협상",
 focus="비교급·최상급, à condition que + 접속법, 조건·양보 표현, tu/vous 전환의 순간",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제56화 « Le soir des critiques » : 토요일 저녁, 일간지 기자와 까다로운 비평가가 같은 시각에 예약해 나타난다.")
