# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, K, C = "Hélène", "Julien", "Karim", "Chloé"
D = [
(None, "Mardi 22 décembre, 10 h 15. Dans la cuisine, Karim épluche des oignons pour la soupe. Hélène goûte un bouillon. Chloé entre avec son carnet, Julien derrière elle, l'air grave.", "12월 22일 화요일 오전 10시 15분. 주방에서 카림이 수프용 양파를 까고 있고, 엘렌은 육수를 맛본다. 클로에가 수첩을 들고 들어오고, 쥘리앵이 심각한 얼굴로 뒤따른다."),
(K, "Bon, j'ai reçu un message ce matin. D'un ancien collègue de chez Perrault, à Lyon.", "있잖아, 오늘 아침에 메시지를 받았어. 리옹 페로 레스토랑 시절 옛 동료한테."),
(H, "Karim, ce n'est pas l'heure des confidences. L'oignon nous fait déjà assez pleurer.", "카림, 속 얘기 할 시간이 아니야. 양파만으로도 눈물이 충분하다고."),
(K, "Écoute-moi. Il paraît que les gens du Guide Lacroix seraient dans le onzième cette semaine.", "들어 봐. 라크루아 가이드 사람들이 이번 주에 11구에 있을 거래."),
(C, "Le Guide Lacroix ? Celui avec les petites fourchettes ?", "라크루아 가이드요? 작은 포크 표시 있는 그거요?"),
(K, "Oui. Les inspecteurs sont anonymes. Ils réservent sous un faux nom et ils paient leur addition.", "응. 심사관들은 익명이야. 가명으로 예약하고 계산도 자기들이 해."),
(J, "On raconte même qu'ils viennent deux fois, à des jours différents, pour comparer.", "심지어 날을 달리해서 두 번 와서 비교한다고들 해."),
(H, "On raconte, on raconte. C'est une rumeur. Je n'ai pas de temps pour les rumeurs.", "그렇대, 그렇대. 소문이야. 소문에 쓸 시간 없어."),
(K, "Mon collègue est sûr de lui. Ils sont venus chez Perrault un mardi, et personne ne les a vus.", "그 친구는 확신하더라. 페로에도 화요일에 왔는데 아무도 못 알아봤대."),
(H, "Un mardi, comme aujourd'hui. Merveilleux. Et qu'est-ce que tu veux que j'y fasse ?", "화요일이라, 오늘처럼. 근사하네. 그래서 나더러 어쩌라는 거야?"),
(K, "Rien. Je dis juste qu'on devrait faire un petit effort. Ajouter un truc spécial, peut-être.", "아무것도. 그냥 우리가 조금 신경 써야 한다는 거지. 특별한 걸 하나 더하든가."),
(H, "Pas de truc spécial. On est un bistrot, pas un palace. Pas de truffe, Karim.", "특별한 건 없어. 우린 비스트로지 호텔이 아니야. 송로버섯은 안 돼, 카림."),
(K, "Je n'ai rien dit pour la truffe !", "송로버섯 얘기는 안 했잖아!"),
(C, "Hier, il a quand même demandé à Bastide s'il en avait. Je l'ai entendu.", "어제 바스티드 씨한테 있느냐고 물어봤잖아요. 제가 들었어요."),
(K, "Bon, d'accord. Une petite truffe. Une toute petite.", "알았어, 알았어. 작은 송로버섯. 아주 작은 걸로."),
(H, "Non. Si le Guide vient, il viendra voir ce qu'on fait tous les jours. Pas ce qu'on fait pour lui.", "안 돼. 가이드가 오면 우리가 매일 하는 걸 보러 오는 거야. 자기를 위해 하는 걸 보러 오는 게 아니라."),
(J, "Elle a raison. Et puis, on ne sait même pas à quoi il ressemble.", "맞는 말이야. 게다가 어떻게 생긴 사람인지도 모르잖아."),
(C, "Alors comment on reconnaît un inspecteur ?", "그럼 심사관은 어떻게 알아봐요?"),
(J, "On ne le reconnaît pas, justement. Il faut servir tout le monde comme si c'était lui.", "그게 포인트야, 알아볼 수 없어. 모든 손님을 그 사람인 것처럼 대해야 해."),
(C, "Même Mme Vasseur ?", "바세르 부인도요?"),
(J, "Mme Vasseur ? Elle, on la reconnaîtrait à la voix. Elle n'a jamais été discrète.", "바세르 부인? 목소리로 바로 알아보겠지. 조용했던 적이 없으니까."),
(H, "Bon, briefing. Pain, eau, nappes, rien de nouveau. Julien, tu fais le tour de la salle à dix-huit heures.", "자, 브리핑. 빵, 물, 식탁보, 새로운 건 없어. 쥘리앵, 6시에 홀 한 바퀴 돌아."),
(J, "Ce sera fait. Tout sera nickel, mais comme tous les jours.", "그럴게. 전부 깔끔하게 해 놓을게, 평소랑 똑같이."),
(H, "Voilà. Répétez avec moi : comme tous les jours.", "그래. 나랑 같이 말해 봐. 평소처럼."),
(C, "Comme tous les jours.", "평소처럼."),
(K, "Comme tous les jours... mais avec un peu plus de beurre.", "평소처럼... 하지만 버터를 조금 더 넣고."),
(H, "Karim !", "카림!"),
(None, "19 h 05. La salle se remplit. À la table douze, un homme seul, la cinquantaine, costume gris. À la trois, une dame âgée avec un grand sac. À la six, un jeune couple qui photographie la nappe.", "저녁 7시 5분. 홀이 차기 시작한다. 12번 테이블에는 50대 정장 차림 남자 혼자, 3번에는 큰 가방을 든 연세 있는 여자, 6번에는 식탁보를 사진 찍는 젊은 커플."),
(C, "Julien, j'ai trois personnes bizarres. Je ne dis pas que ce sont des inspecteurs, mais...", "쥘리앵, 이상한 사람이 셋이에요. 심사관이라는 건 아니지만..."),
(J, "Ne dis pas « bizarres ». Dis « intéressantes ». Lesquelles ?", "\"이상한\"이라고 하지 말고 \"흥미로운\"이라고 해. 누구누구야?"),
(C, "Le monsieur du douze : seul, costume gris, lunettes. Il a demandé de l'eau du robinet.", "12번 남자요. 혼자고, 회색 정장에 안경. 수돗물을 달래요."),
(J, "Ça, c'est un inspecteur ou un radin. Les deux se ressemblent beaucoup.", "그건 심사관이거나 구두쇠야. 둘이 꽤 닮았거든."),
(C, "La dame du trois : soixante-dix ans peut-être. Elle a posé trois questions sur la carte avant de s'asseoir.", "3번 할머니요. 일흔쯤 되셨을까요. 앉기도 전에 메뉴에 대해 세 가지를 물으셨어요."),
(J, "Une cliente curieuse, il y en a. Et la troisième ?", "호기심 많은 손님은 있기 마련이야. 세 번째는?"),
(C, "Le couple du six. Ils photographient tout, même le pain.", "6번 커플이요. 빵까지 전부 사진을 찍어요."),
(J, "Ça, c'est des touristes. Ou des influenceurs. Les inspecteurs, eux, ne photographient jamais : trop voyant.", "그건 관광객이거나 인플루언서겠지. 심사관은 절대 사진 안 찍어. 너무 눈에 띄거든."),
(C, "Et si c'était justement pour qu'on ne les soupçonne pas ?", "만약 의심받지 않으려고 일부러 그러는 거라면요?"),
(J, "Chloé, tu lis trop de polars. Allez, souris et prends les commandes.", "클로에, 넌 추리소설을 너무 많이 읽어. 자, 웃고 주문 받아."),
(None, "Quinze minutes plus tard, Chloé revient en cuisine avec les bons.", "15분 뒤, 클로에가 주문서를 들고 주방으로 돌아온다."),
(C, "Table douze : soupe à l'oignon, puis la blanquette Marthe. Il a demandé si le veau était français.", "12번: 양파 수프, 그다음 블랑케트 마르트. 송아지가 프랑스산이냐고 물었어요."),
(H, "Il vient de Bourgogne. Tu lui dis exactement ça, sans en rajouter.", "부르고뉴산이야. 딱 그렇게만 말해, 덧붙이지 말고."),
(C, "Il a aussi voulu savoir si le pain était fait ici.", "빵도 여기서 만드는지 알고 싶어 했어요."),
(K, "Ça, c'est une question d'inspecteur. Ou de boulanger frustré.", "그건 심사관의 질문이야. 아니면 한 맺힌 제빵사의 질문이거나."),
(H, "Karim, la soupe du douze : gratinée, pas brûlée. Pas de surprise.", "카림, 12번 수프는 그라탱은 하되 태우지 마. 놀랄 일 없게."),
(K, "Reçu. Je la fais comme pour moi, c'est-à-dire très bien.", "알겠어. 나 먹을 것처럼 만들게, 그러니까 아주 잘."),
(H, "Tu la fais comme pour tout le monde. C'est plus sûr.", "모든 손님한테 하듯이 만들어. 그게 더 안전해."),
(C, "Table trois : la dame prend une petite portion de poule au pot, puis la Tatin. Elle dit qu'elle a « peu d'appétit ».", "3번: 할머니가 풀레 오 포 작은 양, 그다음 타탱이요. \"식욕이 별로 없다\"고 하세요."),
(H, "Peu d'appétit et beaucoup de curiosité. Note-le dans ton carnet, tiens.", "식욕은 적고 호기심은 많네. 그건 수첩에 적어 둬."),
(J, "Table douze : il a goûté la soupe. Il n'a rien dit, il a juste reposé sa cuillère.", "12번은 수프를 맛봤어. 아무 말 없이 숟가락을 내려놓았을 뿐이야."),
(H, "Reposé comment ? Doucement ? Brusquement ?", "어떻게 내려놨는데? 천천히? 거칠게?"),
(J, "Doucement. Comme quelqu'un qui réfléchit.", "천천히. 생각에 잠긴 사람처럼."),
(K, "Quelqu'un qui réfléchit, c'est mauvais signe. Un client content, il dit hum !", "생각에 잠긴 건 나쁜 신호야. 만족한 손님은 \"음!\" 하거든."),
(C, "Moi, il m'a dit que le pain était « honnête ». C'est bien ?", "저한테는 빵이 \"정직하다\"고 하던데요. 좋은 건가요?"),
(J, "« Honnête », en français, ça veut souvent dire « sans plus ».", "프랑스어에서 \"정직하다\"는 흔히 \"그저 그렇다\"는 뜻이야."),
(C, "Ah bon ? Je croyais que c'était un compliment.", "그래요? 칭찬인 줄 알았는데."),
(J, "C'est un petit compliment. Comme « pas mal » qui veut dire « bien », ou « pas terrible » qui veut dire « mauvais ».", "작은 칭찬이지. \"나쁘지 않다\"가 \"좋다\"이고 \"별로다\"가 \"나쁘다\"인 것처럼."),
(C, "Donc « ce n'est pas mauvais », ça veut dire « c'est bon » ?", "그럼 \"나쁘지 않다\"는 \"좋다\"는 뜻이에요?"),
(J, "Pas exactement. « Ce n'est pas mauvais », ça veut plutôt dire « c'est moyen ». Tout dépend du ton.", "정확히는 아니야. \"나쁘진 않다\"는 오히려 \"보통이다\"야. 전부 어조에 달렸지."),
(H, "Et « ce n'est pas désagréable » ?", "그럼 \"불쾌하지 않다\"는?"),
(J, "Ça, c'est un oui qui hésite.", "그건 망설이는 \"좋다\"야."),
(K, "Je déteste ce pays. Personne ne dit jamais ce qu'il pense.", "난 이 나라가 싫어. 아무도 생각하는 걸 말하지 않아."),
(H, "C'est pour ça qu'on a des critiques. Pour décoder.", "그래서 비평가가 있는 거야. 해독하라고."),
(None, "20 h 25. Chloé apporte la blanquette à la table douze. Elle trébuche légèrement : une goutte de sauce tombe sur la nappe. Julien arrive aussitôt avec une nappe propre. Un peu plus tard, Chloé revient en cuisine, blême.", "8시 25분. 클로에가 12번에 블랑케트를 가져가다 살짝 비틀거려 소스 한 방울이 식탁보에 떨어진다. 쥘리앵이 곧바로 새 식탁보를 들고 온다. 잠시 뒤 클로에가 하얗게 질린 얼굴로 주방에 돌아온다."),
(C, "J'ai taché sa nappe. J'ai renversé de la sauce devant l'inspecteur. Je suis finie.", "식탁보에 얼룩을 냈어요. 심사관 앞에서 소스를 쏟았다고요. 전 끝났어요."),
(H, "Calme-toi. Qu'est-ce que tu as fait, ensuite ?", "진정해. 그다음에 어떻게 했어?"),
(C, "Je me suis excusée. Une seule fois, comme dit Julien. Il m'a répondu : « Ça arrive, même dans les meilleures maisons. »", "한 번만 사과했어요, 쥘리앵이 말한 대로요. 그분이 \"일어나는 일이오, 최고의 가게에서도\" 하셨어요."),
(K, "« Même dans les meilleures maisons ». Il a dit ça ? Alors on en est une, des meilleures maisons.", "\"최고의 가게에서도\"라고 했다고? 그럼 우리도 최고의 가게라는 거네."),
(J, "Ou alors c'est une façon polie de dire que la maison a encore des progrès à faire.", "아니면 이 가게가 아직 발전할 여지가 있다는 걸 정중하게 말한 걸 수도 있고."),
(H, "Merci, Julien. Très encourageant.", "고마워, 쥘리앵. 아주 힘이 나네."),
(J, "Je décode, c'est tout. Mon métier, c'est de lire entre les lignes.", "해석하는 것뿐이야. 행간을 읽는 게 내 일이니까."),
(H, "Ton métier, c'est de ne pas me donner d'ulcère.", "네 일은 내가 위궤양에 안 걸리게 하는 거야."),
(J, "La dame du trois m'a demandé si elle pouvait visiter la cuisine.", "3번 할머니가 주방을 구경할 수 있느냐고 물으셨어."),
(H, "Et tu as répondu quoi ?", "그래서 뭐라고 했어?"),
(J, "Que ce serait malheureusement difficile ce soir. Que nous la recevrions volontiers un autre jour.", "오늘 밤은 아쉽게도 어렵겠다고. 다른 날 기꺼이 모시겠다고 했지."),
(H, "Joli. « Malheureusement difficile », ça veut dire « non » dans toutes les langues.", "근사하네. \"아쉽게도 어렵다\"는 어느 나라 말로든 \"안 돼요\"야."),
(K, "Elle est peut-être gentille. Elle a juste envie de voir où on cuisine.", "그냥 친절한 분일 수도 있어. 어디서 요리하는지 보고 싶은 거겠지."),
(C, "Avec un grand sac et trois questions sur la carte ? Moi, je dis suspecte.", "큰 가방에 메뉴 질문 세 개요? 저는 수상하다고 봐요."),
(J, "Tu le dis trop vite. On a trois suspects et zéro preuve.", "너무 성급해. 용의자는 셋인데 증거는 하나도 없잖아."),
(H, "Alors personne ne change rien. La douze, la trois, la six : pareil pour tous.", "그럼 아무도 아무것도 바꾸지 마. 12번, 3번, 6번 모두 똑같이."),
(None, "21 h 20. Le service se calme. Karim dresse les desserts. Hélène s'essuie les mains.", "9시 20분. 영업이 잠잠해진다. 카림이 디저트를 담고, 엘렌은 손을 닦는다."),
(K, "Si ça se trouve, c'est le couple du six. Ils ont tout photographié, même la cuillère.", "어쩌면 6번 커플일지도 몰라. 숟가락까지 전부 찍었잖아."),
(J, "Je leur ai demandé d'éviter le flash. Poliment : « Si je puis me permettre, le flash dérange un peu les voisins. »", "플래시는 피해 달라고 정중히 부탁했어. \"외람되지만 플래시가 옆 손님께 조금 방해가 됩니다\" 하고."),
(C, "Et ils ont dit quoi ?", "그래서 뭐래요?"),
(J, "Qu'ils tenaient un blog. « Miam Paris ». Quatre abonnés.", "블로그를 한대. \"냠 파리\". 구독자 네 명."),
(C, "Quatre ?", "네 명이요?"),
(J, "Dont leur mère. Ce ne sont pas des inspecteurs, à moins qu'ils soient très forts.", "엄마 포함해서. 아주 대단한 연기자가 아니라면 심사관은 아니야."),
(H, "Julien, ne rends pas la soirée plus dure qu'elle ne l'est.", "쥘리앵, 저녁을 지금보다 더 힘들게 만들지 마."),
(J, "Je fais de l'humour pour calmer tout le monde. C'est ma technique.", "다들 진정시키려고 농담하는 거야. 내 기술이지."),
(H, "Ta technique marche mal. Karim, la Tatin du douze ?", "네 기술은 잘 안 먹혀. 카림, 12번 타탱은?"),
(K, "Hélène, j'ai un doute. Le caramel est trop foncé.", "엘렌, 불안해. 캐러멜이 너무 짙어."),
(H, "Fais voir. Il est foncé, pas brûlé. C'est la Tatin de Marthe : elle aimait le caramel presque amer.", "봐 봐. 짙을 뿐 태운 건 아냐. 마르트의 타탱이잖아, 엄마는 거의 쌉싸름한 캐러멜을 좋아했어."),
(K, "Et si le monsieur n'aime pas l'amer ?", "그 손님이 쌉싸름한 걸 싫어하면요?"),
(H, "Alors il n'aime pas la Tatin de Marthe. Il en a le droit. Envoie.", "그럼 마르트의 타탱이 취향이 아닌 거지. 그럴 권리는 있어. 내보내."),
(None, "22 h 05. La salle se vide. Chloé revient du douze avec un billet plié et l'addition réglée.", "10시 5분. 홀이 비어 간다. 클로에가 접힌 지폐와 계산이 끝난 영수증을 들고 12번에서 돌아온다."),
(C, "Le douze a payé. En espèces.", "12번 손님이 계산했어요. 현금으로요."),
(J, "En espèces ? Intéressant. Pas de nom, pas de trace.", "현금이라고? 흥미롭네. 이름도 흔적도 안 남지."),
(K, "C'est ce que font les inspecteurs. Mon collègue l'a dit.", "심사관들이 그렇게 한대. 내 동료가 말했어."),
(H, "Ou ce que font les gens qui n'aiment pas les cartes. Papa, par exemple.", "아니면 카드 싫어하는 사람들이 하는 짓이지. 아빠처럼."),
(C, "Il m'a demandé une facture détaillée. Sans nom de société.", "상세 영수증을 달래요. 회사 이름은 없이요."),
(J, "Détaillée, pour quoi faire ? Comparer plat par plat ?", "상세하게, 뭐 하려고? 요리마다 비교하려고?"),
(H, "Ou pour une note de frais. Ou pour son comptable. Ou pour son plaisir.", "아니면 비용 처리용이거나. 회계사한테 줄 수도 있고. 아니면 그냥 재미로."),
(C, "Et en partant, il a ajouté : « Dites à la cheffe que la sauce était juste. »", "그리고 나가면서 이렇게 덧붙였어요. \"주방장에게 소스가 딱 맞았다고 전해 주시오.\""),
(H, "« Juste » ? Juste comment ? Juste bien ? Juste assez ? Juste ce qu'il faut ?", "\"딱 맞다\"? 어떻게 딱? 정말 좋다는 거야? 그저 적당하다는 거야? 필요한 만큼이라는 거야?"),
(J, "Chez un client normal, c'est un compliment. Chez un inspecteur, c'est un verdict codé.", "보통 손님한테는 칭찬이고, 심사관한테는 암호로 된 판결이지."),
(K, "Ou c'est un monsieur qui a bien mangé et qui voulait être aimable.", "아니면 잘 먹고 상냥하게 굴고 싶었던 아저씨일 수도 있고."),
(H, "On ne saura pas. C'est exactement le problème.", "알 수 없을 거야. 바로 그게 문제지."),
(None, "22 h 20. La dame du trois règle par carte. Julien lit le nom sur le reçu et fronce les sourcils.", "10시 20분. 3번 할머니가 카드로 계산한다. 쥘리앵이 영수증의 이름을 읽고 눈살을 찌푸린다."),
(J, "La dame du trois a payé par carte, au nom de « Lacombe ». Elle avait réservé sous « Durand ».", "3번 할머니가 \"라콩브\"라는 이름의 카드로 계산했어. 예약은 \"뒤랑\"으로 했는데."),
(H, "Un nom d'emprunt ? Ou une dame qui réserve au nom de son mari ?", "가명이라고? 아니면 남편 이름으로 예약하는 분이거나?"),
(C, "Elle a laissé deux euros de pourboire et un sourire poli. Ça ne prouve rien.", "팁은 2유로를 두고 정중한 미소를 지었어요. 아무것도 증명하지 않죠."),
(K, "Et le couple du six a demandé une facture au nom d'une société de communication.", "그리고 6번 커플은 홍보 회사 이름으로 영수증을 달라고 했어."),
(J, "Récapitulons. Un monsieur qui paie en espèces. Une dame avec deux noms. Un couple avec une société.", "정리해 보자. 현금으로 내는 남자. 이름이 둘인 할머니. 회사가 있는 커플."),
(C, "Trois suspects. Zéro preuve.", "용의자 셋. 증거 제로."),
(H, "Trois clients. Point. On les a servis pareil, c'est tout ce que je sais.", "손님 셋. 그게 다야. 똑같이 서빙했다는 것, 내가 아는 건 그게 전부야."),
(K, "Et si c'était un quatrième ? Quelqu'un qu'on n'a même pas remarqué ?", "네 번째 사람이면요? 우리가 눈치채지도 못한 누군가라면?"),
(J, "Alors il aura bien mangé sans qu'on s'en aperçoive. C'est le but, non ?", "그럼 우리가 모르는 사이에 잘 먹고 간 거지. 그게 목적이잖아?"),
(H, "Le but, c'était de cuisiner comme d'habitude. On l'a fait jusqu'à la dernière assiette.", "목적은 평소처럼 요리하는 거였어. 마지막 접시까지 해냈고."),
(C, "Hélène... j'ai trouvé quelque chose sous l'assiette du douze. Une serviette pliée en triangle et un billet de cinq euros.", "엘렌... 12번 접시 밑에서 뭘 발견했어요. 삼각형으로 접힌 냅킨과 5유로 지폐요."),
(J, "Cinq euros sur trente-neuf. Ni généreux ni radin. Neutre. Très neutre.", "39유로에 5유로라. 후하지도 인색하지도 않아. 중립적이야. 아주 중립적."),
(K, "Neutre comme un inspecteur. Tu vois bien.", "심사관처럼 중립적이잖아. 봐."),
(H, "Neutre comme un client qui laisse cinq euros. Rangez tout. Demain, on recommence.", "5유로 두고 간 손님처럼 중립적인 거지. 다 정리해. 내일 또 시작이야."),
(J, "Et si c'est demain qu'il vient ?", "내일 오는 거면?"),
(H, "Alors il aura la même soupe, la même sauce, le même sourire.", "그럼 똑같은 수프, 똑같은 소스, 똑같은 미소를 받겠지."),
(C, "Même avec les taches sur les nappes ?", "식탁보 얼룩까지요?"),
(H, "Surtout avec les taches. Une maison sans taches, c'est une maison qui n'a pas servi.", "특히 얼룩까지. 얼룩 없는 가게는 손님을 받지 않은 가게야."),(K, "Ben, moi, j'astique quand même le comptoir. Au cas où.", "그래도 저는 카운터를 닦아 둘게요. 혹시 모르니까."),
(J, "Au cas où, oui. Moi, je ferme la caisse. Bonne nuit, chef.", "혹시 모르니까, 그래. 난 계산대 마감할게. 잘 자요, 셰프."),
]

VOCAB = [
("A2", "Respire. / Souris.", "숨 쉬어. / 웃어.", "긴장한 동료에게 건네는 짧은 명령형. « Souris et prends les commandes. » 손님 앞에서의 기본 태도."),
("B1", "une rumeur / on raconte que", "소문 / ~라고들 한다", "« On raconte même qu'ils viennent deux fois. » 출처 불명의 정보를 전할 때. 비슷한 표현: il paraît que, on dit que."),
("B1", "nickel", "아주 깔끔한", "[구어] « Tout sera nickel. » ↔ 정중: « Tout sera impeccable. » 청결 점검의 구어."),
("B1", "pareil", "똑같은", "« pareil pour tous » 모두를 똑같이 대한다는 뜻. 구어에서 « c'est pareil » 는 \"마찬가지다\"."),
("B1", "trébucher", "비틀거리다, 발이 걸리다", "« Elle trébuche légèrement. » 서빙 중 실수 상황. 함께 쓰는 동사: renverser (엎지르다), tacher (얼룩지게 하다)."),
("B1", "un faux nom", "가명", "« Ils réservent sous un faux nom. » 같은 뜻: un nom d'emprunt (좀 더 문어적)."),
("B2", "paraître / Il paraîtrait que", "~라는 듯하다 / ~라던데", "« Il paraît que les gens du Guide seraient dans le onzième. » 소문은 조건법으로 확실성을 낮춘다."),
("B2", "lire entre les lignes", "행간을 읽다", "« Mon métier, c'est de lire entre les lignes. » 말 속의 속뜻을 파악함."),
("B2", "décoder", "해독하다", "« C'est pour ça qu'on a des critiques. Pour décoder. » 직설을 피하는 프랑스식 표현을 풀어 읽는다."),
("B2", "sans plus", "그저 그렇다, 특별할 것 없다", "« Honnête, ça veut souvent dire sans plus. » 칭찬처럼 들리지만 평범하다는 완곡한 평가."),
("B2", "radin", "구두쇠의", "[구어] « Un inspecteur ou un radin. » ↔ 정중: « économe » / « regardant ». 친근한 놀림. 손님 앞에서는 금지."),
("B2", "un nom d'emprunt", "가명(빌린 이름)", "« Un nom d'emprunt ? Ou une dame qui réserve au nom de son mari ? » 신분을 숨기는 이름."),
("B2", "une note de frais", "경비 정산서", "« Ou pour une note de frais. » 회사 비용으로 처리하기 위한 서류."),
("B2", "Si je puis me permettre,", "외람되지만,", "« Si je puis me permettre, le flash dérange un peu les voisins. » 손님에게 지적할 때 앞에 붙이는 정중 완충구. ↔ 구어: « Excusez-moi, mais... »"),
("B2", "ce serait malheureusement difficile", "아쉽게도 어려울 것 같습니다", "« Que ce serait malheureusement difficile ce soir. » 조건법과 malheureusement 로 \"안 돼요\"를 부드럽게."),
("B2", "à moins que + 접속법", "~가 아닌 한", "« à moins qu'ils soient très forts » 예외를 덧붙이는 접속사. 뒤에 접속법."),
("C1", "mettre les petits plats dans les grands", "정성을 다해 잔치를 차리다", "[구어] Hélène의 방침은 그 반대다: 가이드가 와도 « pas de truc spécial ». 평소와 다르게 힘을 주는 것에 대한 속담."),
("C1", "passer sous les radars", "눈에 띄지 않고 지나가다", "[구어] ↔ 정중: « passer inaperçu ». 익명 심사관이 우리 눈을 피해 방문한다는 뉘앙스."),
("C1", "un verdict codé", "암호로 된 판결", "« Chez un inspecteur, c'est un verdict codé. » 평범한 말에 심사 결과가 숨어 있다는 말. 완곡 표현 해독의 핵심."),
("C1", "une façon polie de dire que...", "~라고 정중하게 말하는 방식", "« C'est une façon polie de dire que la maison a encore des progrès à faire. » 칭찬의 뒷면을 읽는 틀."),
("C1", "Ça arrive, même dans les meilleures maisons.", "최고의 가게에서도 있는 일이오", "격려이기도 하고 지적이기도 한 이중 의미. 완곡한 위로의 전형적 관용구."),
("C1", "ne pas être discret", "조용하지 않다, 눈에 띄다", "« Elle n'a jamais été discrète. » 바세르 부인을 가리키는 장난기 있는 표현."),
("C1", "avoir un doute", "의구심이 들다", "« Hélène, j'ai un doute. Le caramel est trop foncé. » 요리에서의 불안. 정중한 주방 보고."),
("C1", "ça ne prouve rien", "아무것도 증명하지 않는다", "« Ça ne prouve rien. » 단서가 모호할 때 결론을 막는 신중한 표현."),
]

GRAM = [
("B2", "완곡어법(litote)과 어조 — pas mal, honnête, sans plus", "프랑스어에서는 부정문으로 긍정을 약하게 말하는 litote가 흔하다. « pas mal » = 꽤 좋다, « pas terrible » = 별로다, « ce n'est pas mauvais » = 보통이다, « ce n'est pas désagréable » = 망설이는 긍정. Julien이 Chloé에게 풀어 주는 장면: « ‹ Honnête ›, en français, ça veut souvent dire ‹ sans plus ›. » 의미는 억양과 표정에 달려 있다."),
("B2", "소문과 추측의 조건법 — il paraîtrait que, seraient", "« Il paraît que les gens du Guide Lacroix seraient dans le onzième cette semaine. » 조건법은 확인되지 않은 정보를 전달할 때 쓴다(기사 문체에도 많다). « On raconte même qu'ils viennent deux fois » 는 직설법이라 조금 더 확신한다. 유사 표현: il se dit que, d'après ce qu'on m'a dit."),
("B2", "접속법 — il se pourrait que, à moins que, sans que", "« à moins qu'ils soient très forts » (예외 조건), « sans qu'on s'en aperçoive » (~하지 못하는 사이에), « bien que » 도 접속법을 요구한다. 대비: « Alors il aura bien mangé sans qu'on s'en aperçoive. » 에서 미래완료와 접속법이 함께 나온다. 추측의 il se pourrait que + 접속법도 같은 계열."),
("B2", "정중한 완충구 — si je puis me permettre, volontiers", "손님을 정정하거나 거절할 때: « Si je puis me permettre, le flash dérange un peu les voisins. » « Que ce serait malheureusement difficile ce soir. Que nous la recevrions volontiers un autre jour. » 조건법 + malheureusement/volontiers + 대안 제시로 \"안 됩니다\"를 부드럽게 한다."),
("B1", "가정 — Et si c'était..., si ça se trouve", "« Et si c'était justement pour qu'on ne les soupçonne pas ? » si + 반과거로 가정을 던진다. « Si ça se trouve, c'est le couple du six. » 구어의 si ça se trouve 는 \"어쩌면, 알고 보면\". 가능성 열어 두기의 기본 틀."),
("B2", "간접화법의 연속 — 조건법과 대과거", "« Il a ajouté : ... » 처럼 직접인용과 « Qu'ils tenaient un blog » 처럼 간접화법 요약이 섞여 쓰인다. 전달 동사가 과거면 시제가 한 단계 뒤로 간다: « Elle avait réservé sous Durand. » (대과거) 앞 화의 간접화법과 비교해 보자."),
("B2", "정관사 강조와 부정 — ni ... ni, ne ... rien", "« Ni généreux ni radin. Neutre. » 처럼 ni ... ni 는 양쪽 모두를 부정하는 중립적 평가. « Il n'a rien dit » 도 같은 체계. 평가를 유보하는 표현으로 활용한다."),
]

READ = [
("억양 — 의심을 담은 질문", "« Alors comment on reconnaît un inspecteur ? » 는 comment 에서 올라가 inspecteur 에서 끝을 올린다. 불안한 문장일수록 문장 끝이 가볍게 떨린다. 한 호흡: Alors / comment on reconnaît / un inspecteur ?"),
("litote 의 어조 — « pas mal » 의 두 얼굴", "« pas mal » 은 올려서 읽으면 \"꽤 좋다\", 평평하게 읽으면 \"그저 그렇다\". « Honnête » 는 h 가 묵음이라 on-nête [ɔnɛt], 두 번째 음절을 길게 끌면 \"sans plus\" 의 느낌이 난다. 연습: « Le pain ? / Honnête... »"),
("리에종 — trois_inspecteurs, pas_un", "« Trois suspects. » 의 trois 는 s 앞이라 연음 없음, 그러나 « trois_inspecteurs » 라면 z 연음. « pas_un cadeau » 는 [pazœ̃]. 모음 앞에서만 연음된다는 원칙을 확인."),
("숫자 낭독 — trente-neuf euros / cinq euros", "« Cinq euros sur trente-neuf. » 에서 cinq 의 q 는 읽고(cinq euros 는 [sɛ̃kœʀo]), trente-neuf 는 neuf 가 모음 앞이 아니면 f 를 읽는다. « trente-neuf euros » 는 neuf_euros 가 [nœvœʀo] 로 f→v 연음이 일어난다."),
("속삭임과 낮은 소리 — 소문의 억양", "« Il paraît que / les gens du Guide Lacroix / seraient dans le onzième. » 처럼 소문을 말할 때는 조금 낮고 빠르게, 그리고 seraient 에서 약간 멈춘다. 의심과 호기심이 섞인 낭독이 된다."),
("r 소리 — rumeur, rien, preuve", "« Une rumeur » 의 r 두 개는 목구멍 안쪽에서 가볍게. « Trois suspects. Zéro preuve. » 에서 preuve 의 eu[ø] 는 입술을 둥글게. 짧은 문장 둘을 같은 박자로 대구처럼 읽는다."),
("엘리종과 구어 축약 — j'ai, c'est, qu'on", "« Je n'ai rien dit pour la truffe ! » 는 구어에서 « J'ai rien dit pour la truffe ! » 처럼 ne 가 빠진다. « J'ai un doute » 는 [ʒeœ̃dut]. qu'on, c'est, j'ai 같은 엘리종은 소리가 이어져야 자연스럽다."),
]

CULTURE = [
("익명 미식 가이드와 « inspecteur »", "프랑스의 미식 가이드는 심사관(inspecteur)의 익명성을 원칙으로 한다. 심사관은 가명으로 예약하고 자기 돈으로 계산하며, 같은 식당을 여러 번 찾는다. 식당이 눈치채도 모른 척 평소처럼 서비스하는 것이 불문율이다. 이 화에서 Hélène이 \"특별한 걸 하지 마\"라고 하는 이유가 여기에 있다."),
("프랑스식 완곡어법 — litote 의 문화", "프랑스에서는 직설적 비난을 피하고 \"pas mal\", \"honnête\", \"ça peut aller\" 같은 약한 표현에 감정을 싣는다. 칭찬도 비판도 어조와 표정으로 해독해야 한다. 학습자는 \"Je vous remercie, c'était très bien\" 같은 정중한 인사도 반쯤 의례적인 말로 받아들이는 것이 좋다."),
]

META = dict(part=4, ep=57, part_label="제4부 La reconstruction · 늦가을·겨울", title_fr="Le guide passe", title_ko="가이드가 지나가다",
 place="Le Comptoir de Marthe · 12월 22일(화) 오전 10시 15분~밤 10시 30분",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Karim Haddad (부주방장) · Chloé Dubois (견습 서버)",
 wine="익명 미식 가이드 심사관이 다녀갔을지도 모르는 화요일 — 아무도 확신하지 못한다",
 focus="완곡 표현과 litote, 소문의 조건법, 접속법(à moins que, sans que), 정중한 완충구",
 levelmix="A2 5% / B1 20% / B2 40% / C1 35% 목표",
 next="제58화 « Réveillon au Comptoir » : 12월 31일 만석 60명, 건배와 덕담, 크라우드펀딩 최종 모금액이 발표되는 송년 밤.")
