# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, G = "Hélène", "Lucien", "Mme Garnier"
D = [
(None, "Jeudi 3 septembre, 9 h 40. Devant l'agence du Crédit Parisien, boulevard Voltaire. Hélène porte un tailleur, son dossier sous le bras. Lucien l'attend sur le trottoir avec un sac de croissants.", "9월 3일 목요일 오전 9시 40분. 볼테르 대로의 크레디 파리지앵 지점 앞. 엘렌은 정장 차림으로 서류철을 끼고 있다. 뤼시앵이 크루아상 봉지를 들고 인도에서 기다린다."),
(L, "Te voilà. J'ai pris deux croissants, un pour toi, un pour moi.", "왔구나. 크루아상 두 개 샀다. 하나는 네 거, 하나는 내 거."),
(H, "Papa ! Tu es là depuis quand ?", "아빠! 언제부터 와 계셨어요?"),
(L, "Depuis neuf heures. Je voulais voir à quoi ressemble l'endroit.", "9시부터. 어떤 곳인지 보고 싶어서."),
(H, "Ça ressemble à une banque. Du verre, du gris, des plantes en plastique.", "은행처럼 생겼죠. 유리, 회색, 플라스틱 화분."),
(L, "Rien que de les voir, j'ai mal au ventre.", "보기만 해도 배가 아프다."),
(H, "Mange ton croissant. Moi, je n'ai rien avalé depuis hier soir.", "크루아상 드세요. 난 어제 저녁부터 아무것도 못 삼켰어요."),
(L, "Tu as tes papiers ? Le bail, les bilans, les chiffres ?", "서류는 챙겼니? 계약서, 결산서, 숫자들?"),
(H, "Tout est là. J'ai vérifié trois fois. Julien a même mis des intercalaires de couleur.", "다 있어요. 세 번 확인했어요. 쥘리앵이 색깔 구분 용지까지 끼워 줬고요."),
(L, "Un bon dossier, c'est la moitié du travail. L'autre moitié, c'est le sourire.", "좋은 서류가 일의 절반이다. 나머지 절반은 미소지."),
(H, "Je ne sais pas si j'en ai un en réserve.", "나한테 그게 남아 있는지 모르겠네요."),
(L, "Alors prends le mien. Allez, courage, ma fille. Je suis là.", "그럼 내 걸 가져가. 자, 힘내라, 얘야. 내가 여기 있으마."),
(H, "Merci, Papa. Si je ne ressors pas dans une heure, envoie Julien me chercher.", "고마워요, 아빠. 한 시간 안에 안 나오면 쥘리앵을 보내서 데려가 줘요."),
(None, "10 heures. Un petit bureau vitré au premier étage. Mme Garnier, la quarantaine, tailleur sombre, ouvre un dossier sans sourire. Hélène s'assoit au bord de la chaise.", "10시. 2층의 작은 유리 사무실. 40대의 가르니에 부인이 어두운 정장 차림으로 웃음기 없이 서류를 펼친다. 엘렌은 의자 끝에 걸터앉는다."),
(G, "Bonjour, madame Marchand. Installez-vous, je vous en prie.", "안녕하세요, 마르샹 씨. 앉으세요."),
(H, "Bonjour, madame. Merci de me recevoir aussi vite.", "안녕하세요, 부인. 이렇게 빨리 만나 주셔서 감사합니다."),
(G, "C'est normal. Vous avez demandé un entretien, voici l'entretien. Je vous écoute.", "당연한 일이에요. 면담을 요청하셨으니 이렇게 합니다. 말씀하세요."),
(H, "Voilà. Je dirige Le Comptoir de Marthe, rue Saint-Maur, depuis trois ans.", "네. 저는 3년 전부터 생모르 거리에서 르 퐁투아르 드 마르트를 운영하고 있습니다."),
(G, "Un restaurant familial, si je lis bien votre dossier. Ouvert en 1991.", "서류를 제대로 읽었다면 가족 식당이군요. 1991년에 문을 열었고요."),
(H, "Par mes parents. Ma mère est décédée il y a trois ans. J'ai repris la maison.", "부모님이 여셨어요. 어머니가 3년 전에 돌아가셨고, 제가 가게를 이어받았습니다."),
(G, "Toutes mes condoléances. Et avant cela, vous travailliez où ?", "삼가 조의를 표합니다. 그전에는 어디서 일하셨죠?"),
(H, "Seconde de cuisine dans un restaurant étoilé, pendant dix ans.", "별을 받은 레스토랑에서 10년간 부주방장으로 일했습니다."),
(G, "Bien. Vous avez apporté les documents que j'ai demandés ?", "좋습니다. 요청드린 서류는 가져오셨나요?"),
(H, "Oui. Le bail commercial, les douze derniers bilans mensuels, les ventes mois par mois, et le plan de financement.", "네. 상업 임대차 계약서, 최근 12개월 월별 결산, 월별 매출, 그리고 차입 계획서입니다."),
(G, "Merci. Laissez-moi quelques minutes.", "감사합니다. 잠시 시간을 주세요."),
(None, "Silence. Mme Garnier tourne les pages, s'arrête, relit une ligne. Hélène regarde l'horloge, puis ses mains.", "침묵. 가르니에 부인이 페이지를 넘기다 멈추고 한 줄을 다시 읽는다. 엘렌은 시계를 보다가 자기 손을 본다."),
(G, "Votre demande porte sur soixante mille euros, sur huit ans. C'est bien cela ?", "요청하신 금액은 6만 유로, 8년 상환이지요. 맞습니까?"),
(H, "C'est cela. 60 000 €, remboursables en huit ans.", "맞습니다. 6만 유로, 8년 상환입니다."),
(G, "Expliquez-moi à quoi cet argent servirait, précisément.", "이 돈이 정확히 어디에 쓰일지 설명해 주세요."),
(H, "Trois choses. D'abord, 36 000 € pour renforcer la trésorerie.", "세 가지예요. 먼저 운영 자금 보강에 3만 6천 유로."),
(H, "Ensuite, 14 000 € de matériel. Certains appareils ont vingt ans.", "다음으로 장비에 1만 4천 유로. 어떤 기계는 20년 됐어요."),
(H, "Enfin, 10 000 € pour la carte et la communication. On a un nouveau concurrent en face.", "마지막으로 메뉴와 홍보에 1만 유로. 맞은편에 새 경쟁 업소가 생겼거든요."),
(G, "Trente-six mille euros de trésorerie, c'est plus de la moitié du prêt. Ce n'est pas un investissement.", "운영 자금 3만 6천 유로면 대출의 절반이 넘습니다. 투자가 아니지요."),
(H, "Non. C'est un coussin. Je veux payer le loyer et les fournisseurs sans trembler.", "아니죠. 방석 같은 거예요. 임대료와 납품 대금을 떨지 않고 내고 싶어요."),
(G, "Je comprends. Mais pour une banque, un coussin sans projet est difficile à défendre.", "이해합니다. 하지만 은행 입장에서 계획 없는 방석은 옹호하기 어렵습니다."),
(H, "Alors disons que c'est un pont. Entre un été difficile et la reprise d'automne.", "그럼 다리라고 하죠. 힘든 여름과 가을의 회복 사이를 잇는 다리요."),
(G, "Parlons chiffres. Votre chiffre d'affaires sur douze mois : environ 598 000 €. Exact ?", "숫자 얘기를 합시다. 12개월 매출은 약 59만 8천 유로. 맞습니까?"),
(H, "Exact. Mais le printemps était bien meilleur que l'été.", "맞아요. 하지만 봄이 여름보다 훨씬 좋았습니다."),
(G, "Je vois ça. Mars, avril, mai, très bons. Juillet et août, en baisse d'environ trente pour cent.", "그렇군요. 3, 4, 5월은 아주 좋고, 7, 8월은 약 30퍼센트 하락했네요."),
(H, "Oui. Les Parisiens étaient partis, et mon concurrent a ouvert fin juin.", "네. 파리 사람들이 휴가를 떠났고, 경쟁 업소가 6월 말에 문을 열었어요."),
(G, "Et votre loyer ? Le bail indique 3 800 € par mois.", "임대료는요? 계약서에는 월 3,800유로로 되어 있는데요."),
(H, "Jusqu'à fin septembre. À partir du 1er octobre, il passe à 5 200 €.", "9월 말까지는요. 10월 1일부터 5,200유로가 됩니다."),
(G, "Soit environ trente-sept pour cent de plus. C'est considérable.", "약 37퍼센트 오르는 셈이네요. 상당합니다."),
(H, "Je sais. Le propriétaire n'a rien voulu négocier.", "알아요. 건물주가 협상에 전혀 응하지 않았어요."),
(G, "Alors voici ce qui m'inquiète. Avec ce loyer, vos charges fixes explosent.", "그럼 제가 걱정하는 점은 이겁니다. 이 임대료면 고정비가 폭증합니다."),
(H, "Avec les ventes d'août, il manquerait 2 943 € par mois. Je l'ai calculé trois fois.", "8월 매출 기준이면 매달 2,943유로가 모자라요. 세 번 계산했어요."),
(G, "Et la mensualité du prêt s'ajouterait. Environ 760 € par mois, à un taux proche de cinq pour cent.", "거기에 대출 월 상환액이 더해집니다. 금리 5퍼센트 안팎이면 월 약 760유로예요."),
(H, "Je sais. C'est pourquoi mon plan prévoit une hausse du chiffre d'affaires.", "압니다. 그래서 제 계획서에 매출 증가를 넣었습니다."),
(G, "De combien ?", "얼마나요?"),
(H, "Quinze pour cent d'ici décembre.", "12월까지 15퍼센트요."),
(G, "Sur quelle base ? Un prévisionnel n'est pas un engagement des clients.", "무슨 근거로요? 예상 매출은 손님들의 약속이 아닙니다."),
(H, "Sur des faits. J'ai trois leviers, et ils sont déjà en place.", "사실에 근거해서요. 지렛대가 세 개 있고 이미 가동 중입니다."),
(G, "Je vous écoute.", "들어 보겠습니다."),
(H, "Un : la tablée du mardi. Douze couverts à 22 €, et la table est pleine depuis trois semaines.", "하나, 화요일 단체 식탁. 12명에 22유로인데 3주째 만석이에요."),
(H, "Deux : une carte plus courte, avec un plat de la semaine. On gaspille moins.", "둘, 메뉴를 줄이고 주간 요리를 둔 것. 버리는 게 줄었어요."),
(H, "Trois : les soirées privées. Celle du 22 août a rapporté environ 1 100 €.", "셋, 단체 행사. 8월 22일 행사로 약 1,100유로를 남겼어요."),
(G, "Une soirée n'est pas une tendance, madame.", "행사 한 번이 추세는 아닙니다, 부인."),
(H, "Deux autres demandes sont arrivées depuis. Et on a eu 46 réservations le 29 août.", "그 뒤로 두 건이 더 들어왔어요. 그리고 8월 29일엔 예약이 46명이었고요."),
(G, "Ce sont des chiffres de samedi.", "토요일 숫자일 뿐이죠."),
(H, "Et les avis remontent. Quatre étoiles ce mois-ci, sur un site gourmand.", "후기도 오르고 있어요. 이번 달엔 미식 사이트에서 별 네 개를 받았습니다."),
(G, "Les avis en ligne ne remboursent pas un emprunt.", "온라인 후기가 대출을 갚아 주진 않습니다."),
(H, "Non. Mais ils remplissent les tables.", "그렇죠. 하지만 테이블은 채워 줍니다."),
(None, "Mme Garnier note quelque chose. Peut-être un demi-sourire, vite effacé. Elle tourne une page couverte de colonnes.", "가르니에 부인이 무언가를 적는다. 반쯤 웃은 듯했으나 금세 사라진다. 그녀는 숫자 열로 빽빽한 페이지를 넘긴다."),
(G, "Regardons votre trésorerie. Sur les six derniers mois, le solde est négatif presque chaque mois.", "운영 자금을 봅시다. 최근 6개월은 거의 매달 잔액이 마이너스네요."),
(H, "Le frigo est tombé en panne en juin. Ça a coûté 1 450 €.", "6월에 냉장고가 고장 났어요. 1,450유로가 들었죠."),
(G, "Je ne parle pas d'un seul mois, madame. Je parle de six.", "한 달 얘기가 아니에요, 부인. 여섯 달 얘기입니다."),
(H, "Oui. Je ne vais pas vous dire le contraire.", "네. 반대로 말씀드리진 않겠습니다."),
(G, "Merci de votre franchise. Elle est appréciable.", "솔직하게 말씀해 주셔서 감사합니다. 높이 평가합니다."),
(G, "Quel est votre seuil de rentabilité, avec le nouveau loyer ?", "새 임대료 기준으로 손익분기점은 얼마입니까?"),
(H, "Environ 44 000 € de ventes par mois, mensualité du prêt comprise.", "대출 상환액까지 포함해 월 매출 약 4만 4천 유로입니다."),
(G, "Et en août, vous étiez à 40 257 €.", "그런데 8월은 40,257유로였지요."),
(H, "C'est vrai. Il me manque donc 4 000 € par mois. D'où mon objectif de quinze pour cent.", "맞아요. 그러니 월 4천 유로가 모자랍니다. 그래서 15퍼센트가 목표예요."),
(G, "Votre coût matière ? Votre masse salariale ?", "식재료 원가율은요? 인건비 비중은요?"),
(H, "Coût matière : vingt-neuf pour cent. Salaires : trente-huit pour cent, avec trois salariés et une apprentie.", "원가율은 29퍼센트, 인건비는 38퍼센트예요. 직원 세 명과 견습생 한 명이고요."),
(G, "Vingt-neuf, c'est bas pour un restaurant. C'est un point positif.", "29퍼센트는 식당치고 낮네요. 긍정적인 점입니다."),
(H, "On fait tout maison. On ne jette presque rien.", "전부 직접 만들어요. 거의 버리는 게 없고요."),
(G, "Avez-vous d'autres crédits en cours ?", "진행 중인 다른 대출이 있습니까?"),
(H, "Aucun crédit. Juste les fournisseurs, qu'on paie à trente jours.", "대출은 없습니다. 납품업자에게 30일 후 결제하는 것뿐이에요."),
(G, "Le montant dû aux fournisseurs, aujourd'hui ?", "현재 납품업자에게 갚을 금액은요?"),
(H, "Environ 14 000 €. Dont 4 200 € à mon maraîcher, qui attend depuis deux mois.", "약 1만 4천 유로예요. 그중 4,200유로는 채소 납품업자에게 두 달째 기다리게 하고 있고요."),
(G, "Deux mois de retard ? Ce n'est pas anodin.", "두 달 지연이요? 가볍게 볼 일이 아니군요."),
(H, "C'est un ami. Il a de la patience. Mais je ne veux pas en abuser.", "친구예요. 참을성이 많죠. 하지만 그걸 악용하고 싶진 않아요."),
(G, "Passons aux garanties. Que pouvez-vous mettre en face ?", "담보로 넘어갑시다. 무엇을 내걸 수 있습니까?"),
(H, "Le fonds de commerce, bien sûr. Et ma caution personnelle.", "물론 영업권이죠. 그리고 제 개인 보증도요."),
(G, "Jusqu'à quel montant ?", "얼마까지입니까?"),
(H, "Vingt mille euros. C'est tout ce que j'ai de côté.", "2만 유로요. 제가 모아 둔 전부예요."),
(G, "Vingt mille sur soixante mille. Êtes-vous propriétaire de votre logement ?", "6만 중에 2만이군요. 거주하시는 집은 본인 소유입니까?"),
(H, "Non, je suis locataire. Je n'ai pas de patrimoine immobilier.", "아니요, 세입자입니다. 부동산 자산은 없어요."),
(G, "Pas d'autre garant ? Un proche, un membre de la famille ?", "다른 보증인은요? 가까운 분이나 가족은?"),
(H, "Mon père est retraité. Je ne veux pas l'engager.", "아버지는 은퇴하셨어요. 아버지를 끌어들이고 싶지 않습니다."),
(G, "C'est votre choix. Mais la banque est exigeante sur ce point.", "그건 본인 선택입니다. 하지만 은행은 이 점에 엄격합니다."),
(H, "Madame, puis-je vous dire une chose qui n'est pas dans le dossier ?", "부인, 서류에 없는 말씀을 하나 드려도 될까요?"),
(G, "Je vous en prie. Mais soyez brève.", "그러세요. 다만 짧게 부탁합니다."),
(H, "Dans ce quartier, on sert les mêmes gens depuis trente-cinq ans. Une dame est assise à la même table depuis trente ans.", "이 동네에서는 35년째 같은 분들을 모십니다. 한 부인은 30년째 같은 테이블에 앉으세요."),
(H, "Ils ne viennent pas pour un menu. Ils viennent parce que c'est chez eux.", "그분들은 메뉴 때문에 오는 게 아니에요. 자기 집 같아서 오는 거죠."),
(G, "Je comprends l'attachement. Mais je dois décider sur des chiffres, pas sur des souvenirs.", "애착은 이해합니다. 하지만 저는 추억이 아니라 숫자로 결정해야 합니다."),
(H, "Alors regardez les chiffres du deuxième onglet : les ventes du mardi soir ont doublé en trois semaines.", "그럼 두 번째 탭의 숫자를 보세요. 화요일 저녁 매출이 3주 만에 두 배가 됐습니다."),
(G, "Je les ai vus. Ils sont encourageants, mais récents.", "봤습니다. 고무적이지만 아직 얼마 안 된 수치예요."),
(H, "Récents, mais réels. Je ne vous demande pas de croire. Je vous demande de regarder.", "최근 것이지만 실제입니다. 믿어 달라는 게 아니라 봐 달라는 겁니다."),
(G, "C'est ce que je fais, madame Marchand. C'est mon métier.", "그렇게 하고 있습니다, 마르샹 씨. 그게 제 일이에요."),
(G, "Dernière question. Si le crédit était accordé, que feriez-vous la première semaine ?", "마지막 질문입니다. 대출이 승인되면 첫 주에 무엇을 하시겠어요?"),
(H, "Je paierais mon maraîcher. Puis je ferais réviser le four. Et je dormirais une nuit entière.", "채소 납품업자에게 먼저 갚을 거예요. 그다음 오븐을 점검하고요. 그리고 하룻밤 푹 잘 겁니다."),
(G, "Ce dernier point n'est pas dans votre plan de financement.", "마지막 항목은 차입 계획서에 없네요."),
(H, "Il devrait y être. C'est le plus important.", "있어야죠. 가장 중요한 건데요."),
(None, "Cette fois, Mme Garnier sourit pour de bon, une seconde. Puis elle referme le dossier et se redresse.", "이번에는 가르니에 부인이 정말로 잠깐 미소를 짓는다. 그러고는 서류철을 덮고 몸을 곧게 편다."),
(G, "Je transmets votre dossier au comité de crédit. Vous aurez une réponse sous huit jours.", "서류를 여신위원회에 넘기겠습니다. 일주일 안에 답을 드리겠습니다."),
(H, "Vous pouvez déjà me dire ce que vous en pensez ?", "벌써 어떻게 생각하시는지 말씀해 주실 수 있나요?"),
(G, "Non, pas aujourd'hui. Mais je serai honnête : le contexte est difficile.", "아니요, 오늘은 안 됩니다. 다만 솔직히 말씀드리면 상황이 어렵습니다."),
(H, "Je m'en doutais. Merci de me le dire.", "짐작했어요. 말씀해 주셔서 감사합니다."),
(G, "Si vous avez de nouveaux éléments, envoyez-les-moi avant lundi.", "새로운 자료가 있으면 월요일 전에 보내 주세요."),
(H, "Je vous enverrai les chiffres de la semaine, mardi soir compris.", "화요일 저녁 분까지 포함해 이번 주 숫자를 보내 드리겠습니다."),
(G, "Très bien. Bonne journée, madame Marchand.", "좋습니다. 좋은 하루 보내세요, 마르샹 씨."),
(H, "Merci de m'avoir écoutée, madame. Bonne journée.", "들어 주셔서 감사합니다, 부인. 좋은 하루 보내세요."),
(None, "11 h 25. Hélène sort de l'agence, pâle. Lucien est assis sur un banc, deux croissants encore intacts sur les genoux.", "11시 25분. 엘렌이 창백한 얼굴로 지점에서 나온다. 뤼시앵은 벤치에 앉아 있고 무릎 위의 크루아상 두 개는 손도 안 댄 채다."),
(L, "Alors ? Comment ça s'est passé ?", "그래서? 어떻게 됐니?"),
(H, "Elle a dit huit jours.", "일주일이래요."),
(L, "Ça veut dire quoi, huit jours ? Oui ? Non ?", "일주일이 무슨 뜻이냐? 된다는 거냐, 안 된다는 거냐?"),
(H, "Ça veut dire que j'attends. Comme d'habitude.", "기다리라는 뜻이죠. 늘 그렇듯이."),
(L, "Elle était aimable, au moins ?", "그래도 친절하긴 했니?"),
(H, "Polie. Pas aimable. Ce n'est pas pareil.", "예의는 바르죠. 친절한 건 아니고요. 달라요."),
(L, "Je t'avais dit que j'avais une tête qui rassure.", "내가 믿음직한 얼굴이라고 했잖니."),
(H, "Papa, tu aurais fait fuir son chef de service. Mais merci d'avoir attendu.", "아빠였으면 그분 상사까지 도망갔을 거예요. 그래도 기다려 줘서 고마워요."),
(L, "Viens, je t'offre un café. Les croissants sont froids, tant pis.", "가자, 커피 사 주마. 크루아상은 식었지만 어쩔 수 없지."),
(H, "Un café, oui. Et ensuite on rentre. On a vingt-deux couverts ce midi.", "커피는 좋아요. 그다음엔 돌아가요. 오늘 점심 22명이에요."),
(L, "Jeudi. Donc table sept. Henri et sa femme, avec le steak-frites.", "목요일이니 7번 테이블이구나. 앙리 부부, 스테이크 프리트."),
(H, "Huit jours, Papa. Ça va être très long.", "일주일이라니, 아빠. 아주 길겠어요."),
]

VOCAB = [
("A2", "Installez-vous, je vous en prie.", "앉으세요. / 편히 계세요.", "« Installez-vous, je vous en prie. » 손님·방문객을 정중히 맞는 말. 나이 많은 사람에게도 안전하게 쓴다."),
("A2", "Courage !", "힘내!", "« Allez, courage, ma fille. » 짧은 격려. 정중하게는 « Bon courage. » 라고 한다."),
("A2", "Sous huit jours", "일주일 안에", "« Une réponse sous huit jours. » huit jours 는 '일주일'을 뜻하는 관용 표현이다. 2주는 quinze jours."),
("B1", "Un entretien / un rendez-vous", "면담 / 약속", "« Vous avez demandé un entretien. » 공식적인 면담은 entretien, 일반 약속은 rendez-vous."),
("B1", "Un bail commercial", "상업 임대차 계약", "« Le bail commercial. » 가게 임대차 계약서. 주택은 bail d'habitation."),
("B1", "Les charges fixes", "고정비", "« Vos charges fixes explosent. » 매출과 상관없이 나가는 비용: 임대료, 급여 등. ↔ les coûts variables."),
("B1", "Un fournisseur", "납품업자, 공급업체", "« Payer les fournisseurs sans trembler. » 식당은 fournisseur 에게 보통 30일 후 결제한다."),
("B1", "Rembourser / remboursable", "갚다 / 상환 가능한", "« Remboursables en huit ans. » 돈을 빌렸으면 rembourser. 환불도 같은 단어."),
("B1", "Un concurrent", "경쟁자", "« Un nouveau concurrent en face. » 가게 맞은편 경쟁 식당을 가리킨다."),
("B2", "Une mensualité", "월 상환액", "« Environ 760 € par mois. La mensualité du prêt. » 대출 원리금을 매달 갚는 금액."),
("B2", "Le taux d'intérêt", "금리", "« À un taux proche de cinq pour cent. » taux 는 비율. 숫자는 « cinq pour cent » 로 읽는다."),
("B2", "Un plan de financement", "차입·자금 조달 계획서", "« Le plan de financement. » 대출을 어디에 쓰고 어떻게 갚을지 정리한 서류."),
("B2", "La trésorerie", "운영 자금, 현금 흐름", "« Renforcer la trésorerie. » 당장 쓸 수 있는 현금. « Le solde est négatif » = 잔액이 마이너스."),
("B2", "Le seuil de rentabilité", "손익분기점", "« Quel est votre seuil de rentabilité ? » 적자를 면하기 위한 최소 매출."),
("B2", "Le fonds de commerce", "영업권(가게의 상업적 가치)", "« Le fonds de commerce, bien sûr. » 단골·상호·위치 등을 합친 가게의 가치. 담보로 쓸 수 있다."),
("B2", "Une caution personnelle", "개인 보증", "« Ma caution personnelle. » 법인이 갚지 못하면 개인이 대신 갚겠다는 약속. se porter caution = 보증을 서다."),
("B2", "Un prévisionnel", "예상 실적, 전망", "« Un prévisionnel n'est pas un engagement des clients. » 계획·예측 수치를 말한다."),
("B2", "Le coût matière", "식재료 원가", "« Coût matière : vingt-neuf pour cent. » 매출 대비 재료비 비율. 식당 경영의 핵심 지표."),
("B2", "Je m'en doutais.", "짐작했어요.", "[구어] 나쁜 소식을 듣고도 담담하게 받아들일 때. ↔ 정중: Je m'y attendais."),
("C1", "Un comité de crédit", "여신위원회", "« Je transmets votre dossier au comité de crédit. » 대출 승인 여부를 정하는 은행 내부 심사 기구."),
("C1", "Une garantie", "담보, 보증", "« Passons aux garanties. » 은행이 돈을 떼이지 않기 위해 요구하는 담보·보증 전반."),
("C1", "Décider sur des chiffres, pas sur des souvenirs", "추억이 아닌 숫자로 결정하다", "정중하지만 냉정한 거절의 방패. 감정에 호소하는 상대에게 쓰는 말. sur + 근거."),
("C1", "Un coussin / un pont", "방석 / 다리 (비유)", "« C'est un coussin. » « C'est un pont. » 대출 자금을 비유로 설명할 때. 비유는 설득을 돕지만 은행은 '계획'을 원한다."),
("C1", "Ce n'est pas anodin.", "가볍게 볼 일이 아니다.", "« Deux mois de retard ? Ce n'est pas anodin. » 부정문으로 심각함을 에둘러 표현한다."),
]

GRAM = [
("B1", "정중한 요청 — je vous en prie, laissez-moi, envoyez-les-moi", "« Installez-vous, je vous en prie. » « Laissez-moi quelques minutes. » « Envoyez-les-moi avant lundi. » 명령형은 vous 와 함께 쓰면 정중한 요청이 된다. 대명사가 둘이면 « envoyez-les-moi » 처럼 직접목적 les 가 먼저, 간접 moi 가 뒤에 온다."),
("B2", "조건법 — 가정 속 계획", "« Si le crédit était accordé, que feriez-vous la première semaine ? » « Je paierais mon maraîcher. Puis je ferais réviser le four. » si + 반과거, 조건법 현재. 은행원이 가상 상황을 묻고 Hélène이 조건법으로 답하는 전형적인 문형."),
("B2", "수치 표현 — 퍼센트, soit, 비교", "« Soit environ trente-sept pour cent de plus. » « Quinze pour cent d'ici décembre. » « Vingt mille sur soixante mille. » soit 는 '즉, 다시 말해', sur 는 '~ 중에'. 숫자를 요약하는 격식 있는 구어."),
("B2", "정중한 구어 — 이유·결론 연결어", "« C'est pourquoi mon plan prévoit une hausse. » « D'où mon objectif de quinze pour cent. » « Alors voici ce qui m'inquiète. » 문어체까지 가지 않고 이유·결과를 이어 주는 말. 은행 같은 격식 있는 자리에서 자주 쓴다."),
("B2", "의문과 반박 — 완곡한 지적", "« Un prévisionnel n'est pas un engagement des clients. » « Une soirée n'est pas une tendance. » « Les avis en ligne ne remboursent pas un emprunt. » 상대의 주장을 정중하게 반박하는 'A n'est pas B' 구조. 짧을수록 냉정하게 들린다."),
("C1", "한정과 강조 — rien que, tout ce que", "« Rien que de les voir, j'ai mal au ventre. » « C'est tout ce que j'ai de côté. » « Je n'ai pas de patrimoine immobilier. » rien que + 동사원형은 '~하기만 해도'. tout ce que + 직설법은 '내가 가진 전부'."),
("C1", "설득의 구조 — 양보와 반박", "« Récents, mais réels. Je ne vous demande pas de croire. Je vous demande de regarder. » 부정 → 긍정의 대구(對句)로 설득한다. « Elle était aimable ? — Polie. Pas aimable. Ce n'est pas pareil. » 같은 단문 정정도 효과적."),
]

READ = [
("숫자 읽기 — 대출 금액", "« 60 000 € » 는 soixante mille euros, « 36 000 € » 는 trente-six mille euros, « 5 200 € » 는 cinq mille deux cents euros. « 760 € » 는 sept cent soixante euros. 숫자 뒤 euros 앞에서 리에종: « mille_euros » /mil.ø.ʁo/. 퍼센트는 « cinq pour cent » 로 읽는다."),
("리에종 — vous_en_prie, c'est_un", "« Installez-vous, / je vous_en prie. » /ʒə.vu.zɑ̃.pʁi/ 에서 vous 의 s 가 en 으로 이어진다. « C'est_un coussin » /sɛ.tœ̃.ku.sɛ̃/ 도 t 를 이어 읽는다."),
("호흡 구간 — 은행 설명", "« Un : / la tablée du mardi. / Douze couverts à vingt-deux euros, / et la table est pleine / depuis trois semaines. » 항목을 나열할 때는 숫자 뒤에서 끊고 조금 낮춰 읽으면 자신감 있게 들린다."),
("억양 — 냉정한 은행원 vs 긴장한 고객", "Mme Garnier 는 끝을 내리며 평탄하게: « Je vous écoute. » Hélène 은 끝을 올려 불안을 보인다: « Vous pouvez déjà me dire ce que vous en pensez ? » 같은 의문문도 인물의 성격에 따라 억양이 달라진다."),
("비음 — environ, engagement, intérêt", "« environ » /ɑ̃.vi.ʁɔ̃/, « engagement » /ɑ̃.ɡaʒ.mɑ̃/, « intérêt » /ɛ̃.te.ʁɛ/. 비음은 코로 소리를 낸다. an/en 과 in 의 차이를 입 모양으로 구분해 읽는다."),
("r — remboursement, trésorerie", "« remboursement » /ʁɑ̃.buʁ.sə.mɑ̃/, « trésorerie » /tʁe.zɔ.ʁə.ʁi/. r 이 연달아 나오는 단어는 혀뿌리를 부드럽게 쓰고 속도를 올리지 않는다."),
("마지막 대사 — 한숨 섞인 느린 호흡", "« Huit jours, / Papa. / Ça va être très long. » 쉼을 길게 두고 마지막 단어 « long » 에서 목소리를 낮추면 피곤과 불안이 함께 담긴다."),
]

CULTURE = [
("프랑스의 대출 상담 — le chargé d'affaires et le comité de crédit", "소상공인이 은행에서 사업 대출을 받으려면 담당 여신 직원(chargé d'affaires professionnelles)과 면담한 뒤 서류가 은행 내부의 comité de crédit 에 넘어간다. 서류는 보통 임대차 계약서(bail), 최근 결산서(bilan), 월별 매출, 차입 계획서(plan de financement)로 이루어진다. 담당자가 결정을 알려 주는 것이 아니라 위원회가 정하므로 면담 직후에는 대개 '검토 후 회신'으로 끝난다."),
("개인 보증 — la caution personnelle", "프랑스 소규모 식당 주인은 대출을 받을 때 가게 자산(fonds de commerce)과 함께 개인 보증(caution personnelle)을 요구받는 일이 많다. 사업이 실패하면 가족의 재산까지 영향을 받을 수 있어서, 가족을 보증인으로 세우는 일은 쉽게 결정하지 않는다. Hélène 이 아버지를 끌어들이지 않으려는 이유가 여기에 있다."),
]

META = dict(part=3, ep=31, part_label="제3부 Au bord du gouffre · 가을", title_fr="Rendez-vous à la banque", title_ko="은행 면담",
 place="크레디 파리지앵 지점(볼테르 대로), 9월 3일 목요일 오전 9시 40분 ~ 11시 25분",
 chars="Hélène Marchand (주인 셰프) · Mme Garnier (은행 여신 담당) · Lucien Marchand (아버지)",
 wine="6만 유로(8년) 대출 상담: 자료 제출, 임대료 5 200 € 인상과 6개월 적자 추궁, 개인 보증 2만 유로 제시, 일주일 내 회신.",
 focus="금융 어휘(mensualité, taux, caution, trésorerie), 격식 있는 정중한 구어, 조건법, 설득과 반박",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제32화 « Le refus » : 9월 10일 목요일, 가르니에 부인의 전화가 걸려 온다. 엘렌은 답을 듣고 말을 잃는다.")
