# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, G = "Hélène", "Lucien", "Julien", "Mme Garnier"
D = [
(None, "Jeudi 10 septembre, 10 h 05. Le restaurant est encore vide. Hélène épluche des carottes sans les regarder. Son téléphone est posé sur le plan de travail, écran allumé. Julien et Lucien l'observent depuis le passe.", "9월 10일 목요일 오전 10시 5분. 식당은 아직 비어 있다. 엘렌은 당근을 쳐다보지도 않고 깎는다. 전화기는 조리대 위에 화면이 켜진 채 놓여 있다. 쥘리앵과 뤼시앵이 패스대 너머로 그녀를 지켜본다."),
(J, "Ça fait une heure que tu épluches la même carotte.", "한 시간째 같은 당근만 깎고 있네."),
(H, "C'est pas la même. C'est la douzième.", "같은 거 아니야. 열두 번째야."),
(L, "Le délai de huit jours se termine demain. Elle va peut-être appeler aujourd'hui.", "일주일 기한이 내일 끝난다. 오늘 전화할 수도 있지."),
(H, "Ou demain. Ou jamais. Les banques, ça adore faire attendre.", "아니면 내일. 아니면 영영. 은행은 기다리게 하는 걸 좋아하잖아요."),
(J, "Tu veux un café ? Je parie que t'as rien mangé.", "커피 줄까? 아무것도 안 먹었을 것 같은데."),
(H, "J'peux rien avaler. J'ai l'estomac noué.", "아무것도 못 삼켜. 속이 꽉 막혔어."),
(L, "Un morceau de pain, au moins. On ne pense pas bien le ventre vide.", "빵 한 조각이라도. 배가 비면 생각이 제대로 안 된다."),
(H, "Je pense à rien, Papa. Justement.", "난 아무 생각도 안 해요, 아빠. 그게 문제죠."),
(J, "Menteuse. Tu penses à tout. Ça se voit à ta mâchoire.", "거짓말. 온갖 생각을 하고 있잖아. 턱에 다 보여."),
(H, "Quelle mâchoire ?", "무슨 턱?"),
(J, "Celle que tu serres quand t'es inquiète. Elle est carrée depuis ce matin.", "걱정될 때 꽉 무는 턱 말이야. 아침부터 각져 있어."),
(L, "Elle tient ça de sa mère. Marthe serrait les dents, et pas seulement devant les banquiers.", "엄마를 닮았지. 마르트도 이를 앙다물었어, 은행원 앞에서만이 아니라."),
(H, "Merci. Ça aide énormément.", "고마워요. 정말 큰 도움이 되네요."),
(J, "Table sept ce midi : Henri a rappelé. Steak-frites, comme tous les jeudis.", "오늘 점심 7번 테이블은 앙리 씨가 다시 전화했어. 목요일마다 먹는 스테이크 프리트."),
(H, "Je le ferai. Je suis encore capable de cuire un steak.", "해 드릴게. 스테이크 하나는 아직 구울 수 있으니까."),
(J, "Il y a un proverbe sur les banques ?", "은행에 관한 속담도 있어요?"),
(L, "On ne prête qu'aux riches. Mais je ne le dis pas.", "부자에게만 빌려준다지. 하지만 난 그 말 안 한다."),
(H, "Tu viens de le dire.", "방금 하셨잖아요."),
(L, "Ah. Zut.", "아. 이런."),
(None, "10 h 20. Le téléphone vibre sur le plan de travail. À l'écran : « Crédit Parisien ». Trois paires d'yeux se figent. Hélène essuie ses mains sur son tablier, très lentement.", "10시 20분. 전화기가 조리대 위에서 진동한다. 화면에는 « 크레디 파리지앵 ». 세 쌍의 눈이 얼어붙는다. 엘렌은 앞치마에 아주 천천히 손을 닦는다."),
(J, "C'est elle.", "그 사람이야."),
(H, "Je sais. Bougez pas. Parlez pas.", "알아. 움직이지 마. 말하지도 말고."),
(L, "Décroche, enfin !", "받아라, 어서!"),
(H, "Allô ? Oui, bonjour, madame Garnier. Oui, je vous écoute.", "여보세요? 네, 안녕하세요, 가르니에 부인. 네, 말씀하세요."),
(G, "Bonjour, madame Marchand. Je vous appelle au sujet de votre demande de prêt. Avez-vous quelques minutes ?", "안녕하세요, 마르샹 씨. 대출 신청 건으로 전화드렸습니다. 잠시 시간 괜찮으십니까?"),
(H, "Bien sûr. Excusez-moi, je suis en cuisine, je vous mets sur haut-parleur. J'ai les mains pleines.", "물론이죠. 죄송하지만 주방이라서 스피커폰으로 돌릴게요. 손이 다 차 있어서요."),
(G, "Comme vous voulez. Je vous rappelle que l'information est confidentielle.", "원하시는 대로 하세요. 다만 이 정보는 기밀임을 알려 드립니다."),
(H, "Mon père et mon collègue sont là. Je n'ai rien à cacher.", "아버지와 동료가 여기 있어요. 숨길 건 없습니다."),
(G, "Très bien. Alors voilà. Le comité de crédit s'est réuni hier soir.", "좋습니다. 그럼 말씀드리지요. 여신위원회가 어제 저녁에 열렸습니다."),
(G, "J'ai le regret de vous informer que votre demande n'a pas été acceptée.", "유감스럽게도 신청이 승인되지 않았음을 알려 드립니다."),
(H, "Pas acceptée.", "승인되지 않았다고요."),
(G, "Je suis désolée, madame. Je tenais à vous l'annoncer moi-même, avant le courrier.", "죄송합니다. 우편이 가기 전에 제가 직접 알려 드리고 싶었습니다."),
(H, "Je vous en remercie. Pouvez-vous m'expliquer pourquoi ?", "감사합니다. 이유를 설명해 주시겠어요?"),
(G, "Trois raisons principales. Premièrement, la trésorerie est négative depuis six mois.", "주된 이유는 세 가지입니다. 첫째, 최근 6개월간 현금 흐름이 마이너스입니다."),
(G, "Deuxièmement, avec un loyer à 5 200 €, votre capacité de remboursement est jugée insuffisante.", "둘째, 임대료가 5,200유로가 되면 상환 능력이 부족하다고 판단됩니다."),
(G, "Troisièmement, les garanties proposées ont été estimées trop faibles par rapport au montant demandé.", "셋째, 제시하신 담보가 요청 금액에 비해 너무 약하다고 평가되었습니다."),
(H, "Vingt mille euros de caution pour soixante mille de prêt. Je comprends.", "보증 2만 유로에 대출 6만 유로. 이해합니다."),
(H, "Et si j'apportais un garant supplémentaire ? Ou si je baissais le montant ?", "보증인을 한 명 더 세우면요? 아니면 금액을 낮추면요?"),
(G, "Le comité pourrait réexaminer un dossier modifié. Mais je ne vous promets rien, madame.", "수정된 서류라면 위원회가 다시 검토할 수는 있습니다. 하지만 약속은 드릴 수 없습니다."),
(H, "Combien de temps faudrait-il pour ça ?", "그러려면 시간이 얼마나 걸립니까?"),
(G, "Comptez un mois, au minimum.", "최소 한 달은 잡으셔야 합니다."),
(H, "Un mois. Je vois. Merci d'avoir appelé vous-même.", "한 달이요. 알겠습니다. 직접 전화해 주셔서 감사합니다."),
(G, "C'est la moindre des choses. Un courrier électronique avec les motifs détaillés vous sera envoyé cet après-midi. Je vous souhaite bon courage.", "당연한 도리입니다. 자세한 사유를 담은 이메일이 오늘 오후에 발송될 겁니다. 힘내시길 바랍니다."),
(H, "Merci. Au revoir, madame.", "감사합니다. 안녕히 계세요, 부인."),
(None, "Elle raccroche. Pendant cinq secondes, on n'entend que le ronron du frigo. Hélène pose le couteau, regarde ses mains, puis le mur. Ses jambes ne la portent presque plus.", "그녀가 전화를 끊는다. 5초 동안 냉장고의 웅웅거리는 소리뿐이다. 엘렌은 칼을 내려놓고 자기 손을 보다가 벽을 본다. 다리가 거의 버텨 주지 않는다."),
(H, "Refusée.", "거절당했어."),
(J, "Hélène...", "엘렌..."),
(H, "Non. Dis rien. Pas tout de suite.", "아니. 아무 말도 하지 마. 지금은 안 돼."),
(L, "Ma fille...", "얘야..."),
(H, "Toi non plus, Papa.", "아빠도요."),
(H, "J'ai les jambes en coton. J'ai l'impression d'avoir pris un coup de poing dans le ventre.", "다리에 힘이 하나도 없어. 배를 주먹으로 한 대 맞은 기분이야."),
(J, "Assieds-toi. Allez, assieds-toi sur la caisse.", "앉아. 자, 저 상자 위에 앉아."),
(L, "Bois. De l'eau, pas du vin. Bois.", "마셔라. 와인 말고 물. 마셔."),
(H, "J'ai la gorge serrée. J'peux pas.", "목이 메어서 못 마셔요."),
(None, "Hélène s'assoit sur une caisse de légumes, le verre tremble dans sa main. Puis, d'un coup, elle le pose si fort que l'eau déborde.", "엘렌은 채소 상자 위에 앉는다. 컵이 손에서 떨린다. 그러다 갑자기 컵을 쾅 내려놓아 물이 넘친다."),
(H, "Putain. Putain de merde ! Trois ans que je me tue ici !", "젠장. 빌어먹을! 3년이야, 여기서 죽도록 일한 게!"),
(J, "Je sais.", "알아."),
(H, "Tu sais rien ! Toi, tu peux partir demain chez Armand, mille euros de plus !", "넌 몰라! 넌 내일 아르망한테 가면 되잖아, 천 유로 더 받고!"),
(J, "...", "..."),
(H, "Pardon. Pardon, Julien. Je voulais pas dire ça.", "미안. 미안, 쥘리앵. 그런 뜻이 아니었어."),
(J, "C'est rien. Moi aussi, à ta place, je cognerais sur quelqu'un. Prends ton temps.", "괜찮아. 나라도 네 입장이면 누구한테든 퍼부었을 거야. 천천히 해."),
(L, "C'est la banque la coupable, pas Julien. Ces gens-là te prêtent un parapluie quand il fait beau.", "잘못은 은행에 있지 쥘리앵에게 있지 않다. 그 작자들은 날씨 좋을 때만 우산을 빌려주지."),
(H, "Et ils le reprennent dès qu'il pleut. Je la connais, Papa.", "비가 오자마자 도로 가져가고요. 알아요, 아빠."),
(L, "Je te l'avais dit : laisse-moi venir avec toi.", "내가 말했지. 같이 가게 해 달라고."),
(H, "Ne commence pas.", "시작하지 마세요."),
(L, "Un homme de mon âge, avec des cheveux blancs, ça impressionne un comité.", "내 나이에 백발이면 위원회도 인상을 받았을 게다."),
(H, "Un comité ? Papa, ça se joue sur des chiffres ! Pas sur des cheveux blancs.", "위원회요? 아빠, 이건 숫자로 하는 거예요! 백발이 아니라."),
(L, "Au moins, j'aurais défendu le dossier.", "적어도 내가 서류를 변호했을 거야."),
(H, "Tu aurais fait quoi ? Raconté 1991 ?", "뭘 하셨을 건데요? 1991년 얘기를 하셨겠죠?"),
(L, "J'aurais raconté 1991, oui ! Et alors ?", "그래, 1991년 얘기를 했겠지! 그게 어때서?"),
(J, "Stop, vous deux. S'il vous plaît. C'est pas le moment.", "그만, 두 분 다. 제발요. 지금은 때가 아니에요."),
(H, "Pardon, Papa. Je suis à cran.", "죄송해요, 아빠. 신경이 곤두서 있어서."),
(J, "Il y a d'autres banques. Le Crédit Mutuel, la Banque Populaire, Bpifrance...", "다른 은행도 있어. 크레디 뮈튀엘, 방크 포퓔레르, 비피프랑스..."),
(H, "Elles verront les mêmes chiffres. Le même loyer. La même trésorerie.", "똑같은 숫자를 볼 거야. 똑같은 임대료, 똑같은 현금 흐름."),
(J, "Peut-être pas les mêmes garanties.", "담보는 같지 않을 수도 있잖아."),
(H, "J'en ai pas d'autres. J'ai plus rien, Julien. J'ai déjà tout mis.", "다른 건 없어. 더 가진 게 없어, 쥘리앵. 이미 전부 넣었어."),
(L, "Moi, j'ai quelque chose.", "나한텐 있다."),
(H, "Non.", "안 돼요."),
(L, "Tu ne sais même pas ce que je vais dire.", "내가 무슨 말을 할지 알지도 못하면서."),
(H, "Si. Et c'est non. Pas ton argent, Papa. Pas maintenant.", "알아요. 그리고 안 돼요. 아빠 돈은 안 돼요. 지금은요."),
(L, "Pas maintenant. Bon. Je note : « pas maintenant ».", "지금은 안 된다. 좋아. « 지금은 »이라고 적어 두마."),
(J, "Il est onze heures. On ouvre à midi. Je peux appeler les réservations pour annuler ?", "11시야. 12시에 열어. 예약 손님들에게 전화해서 취소할까?"),
(H, "Annuler ? Jamais. Les gens ont réservé. On ouvre.", "취소요? 절대 안 돼. 손님들이 예약했잖아. 열어."),
(J, "T'es sûre ? Tu tiens debout ?", "확실해? 서 있을 수 있겠어?"),
(H, "J'ai appris à cuisiner debout. Alors oui.", "서서 요리하는 법부터 배웠어. 그러니까 응."),
(H, "Allez, au boulot. Julien, la table sept. Papa, tu surveilles le pain.", "자, 일하자. 쥘리앵, 7번 테이블. 아빠는 빵 좀 봐 주세요."),
(None, "15 h 10. Le dernier client est parti. Hélène est assise au bar devant son ordinateur. Julien essuie des verres. Lucien, sur la banquette, fait semblant de lire le journal.", "오후 3시 10분. 마지막 손님이 떠났다. 엘렌은 바에 앉아 노트북 앞에 있다. 쥘리앵은 잔을 닦는다. 뤼시앵은 긴 의자에서 신문을 읽는 척한다."),
(H, "Le mail est arrivé.", "메일이 왔어."),
(J, "Lis-le. Ou laisse, si tu préfères.", "읽어 봐. 싫으면 말고."),
(H, "« Madame, nous avons le regret de vous informer que votre demande n'a pas été retenue. »", "« 마르샹 귀하, 귀하의 신청이 채택되지 않았음을 유감스럽게 알려 드립니다. »"),
(H, "« Les flux de trésorerie sont négatifs. La capacité de remboursement est insuffisante. Les garanties sont limitées. »", "« 현금 흐름이 마이너스입니다. 상환 능력이 부족합니다. 담보가 제한적입니다. »"),
(J, "Les mêmes mots qu'au téléphone.", "전화로 들은 말 그대로네."),
(H, "Et puis : « Nous vous prions d'agréer, madame, l'expression de nos salutations distinguées. »", "그리고 « 귀하께 깊은 경의를 표합니다. »래."),
(H, "Quatre lignes. Ils m'ont enterrée en quatre lignes, et ils me prient d'agréer.", "네 줄이야. 네 줄로 날 묻어 놓고는 예를 갖추라네."),
(L, "Ça ne mange pas de pain, ces formules.", "그런 상투적 인사는 돈 안 드니까."),
(H, "Ça mange le mien, de pain. Cinq mille deux cents euros par mois, à partir du 1er octobre.", "내 빵은 먹어 치우죠. 10월 1일부터 한 달에 5,200유로요."),
(J, "Hélène, il faut que je te dise quelque chose.", "엘렌, 할 말이 있어."),
(H, "Armand.", "아르망."),
(J, "Oui. Tout à l'heure, entre deux services, je l'ai appelé.", "응. 아까 두 서비스 사이에 전화했어."),
(H, "Tu pars.", "떠나는구나."),
(J, "Non. Écoute-moi jusqu'au bout. Je lui ai demandé du temps.", "아니. 끝까지 들어. 시간을 달라고 했어."),
(H, "Combien de temps ?", "얼마나?"),
(J, "Jusqu'au 31 octobre. Il a accepté. Au départ, je devais répondre le 15.", "10월 31일까지. 승낙했어. 원래는 15일까지 답해야 했거든."),
(H, "Et pourquoi tu fais ça ?", "왜 그런 걸 하는 거야?"),
(J, "Parce que je peux pas dire oui. Et je peux pas dire non non plus, pas aujourd'hui.", "난 예라고 못 하니까. 오늘은 아니요라고도 못 하겠고."),
(H, "Tu hésites.", "망설이는구나."),
(J, "Oui. Je préfère te le dire en face que te mentir. Mais je suis encore là, et je compte rester jusqu'au 31 octobre au moins.", "응. 속이는 것보다 얼굴 보고 말하는 게 낫지. 하지만 난 아직 여기 있고, 적어도 10월 31일까지는 있을 생각이야."),
(H, "Merci de me le dire en face. Ça me fait mal, mais merci.", "얼굴 보고 말해 줘서 고마워. 아프지만 고마워."),
(L, "Il a raison de demander du temps. À sa place, j'aurais fait pareil.", "시간을 달라는 건 옳다. 내가 그 자리였어도 그랬을 거야."),
(H, "Papa !", "아빠!"),
(L, "Quoi ? Je dis la vérité. Il y a une différence entre trahir et réfléchir.", "왜? 사실을 말하는 거야. 배신하는 것과 고민하는 것은 다르다."),
(H, "La banque a dit non. Ils ont dit qu'ils pourraient reconsidérer un dossier modifié.", "은행은 안 된다고 했어. 수정된 서류라면 재검토할 수 있다고 했고."),
(J, "Donc ce n'est pas totalement fermé.", "그럼 완전히 닫힌 건 아니네."),
(H, "C'est une porte entrouverte avec un videur derrière.", "문지기가 서 있는, 살짝 열린 문이지."),
(L, "Ça reste une porte.", "그래도 문은 문이다."),
(None, "Hélène se lève, va jusqu'à l'ardoise. Elle prend la craie, regarde le plat de la semaine, puis la repose. Ses épaules tombent, puis se redressent.", "엘렌이 일어나 칠판 쪽으로 간다. 분필을 집어 주간 요리를 보다가 도로 내려놓는다. 어깨가 처졌다가 다시 펴진다."),
(H, "Ce soir, on ouvre à sept heures. Il y a vingt-huit couverts de réservés.", "오늘 저녁은 7시에 열어. 예약이 28명이야."),
(J, "Je m'en occupe. Tu veux que je t'aide à écrire le menu ?", "내가 맡을게. 메뉴 쓰는 것 도와줄까?"),
(H, "Non. Je l'écris. Les mains savent quoi faire, même quand la tête ne sait plus.", "아니. 내가 쓸게. 머리가 멍해도 손은 뭘 해야 할지 알아."),
(L, "Marthe disait ça aussi. Les mains d'abord.", "마르트도 그렇게 말했지. 손이 먼저라고."),
(H, "Ils ont dit non, Papa. Mais pas moi. Pas encore.", "그들은 안 된다고 했어요, 아빠. 하지만 나는 아니에요. 아직은."),
(L, "Voilà ma fille.", "그래, 내 딸이다."),
(H, "Ne me fais pas pleurer devant le personnel.", "직원 앞에서 울리지 마세요."),
(J, "Je suis le personnel. Je peux détourner la tête.", "내가 직원이잖아. 고개 돌려 줄 수 있어."),
(H, "Ça m'arrangerait.", "그럼 좋겠네."),
]

VOCAB = [
("A2", "Au boulot !", "자, 일하자!", "[구어] « Allez, au boulot. » 일을 시작하자고 독려할 때. ↔ 정중: Reprenons le travail."),
("A2", "Ça ne mange pas de pain.", "돈이 들지 않는다, 밑져야 본전이다.", "« Ça ne mange pas de pain, ces formules. » 비용이나 손해가 없는 행동을 가리키는 관용 표현. Hélène 은 '내 빵(생계)은 먹는다' 고 비튼다."),
("A2", "Prends ton temps.", "천천히 해.", "« C'est rien. Prends ton temps. » 상대가 마음을 추스를 시간을 줄 때. ↔ 정중: Prenez le temps qu'il vous faut."),
("B1", "Avoir l'estomac noué", "속이 꽉 막히다, 긴장돼 입맛이 없다", "« J'ai l'estomac noué. » 걱정과 긴장 때문에 아무것도 못 먹을 때. avoir la gorge serrée = 목이 메다."),
("B1", "Décrocher / raccrocher", "전화를 받다 / 끊다", "« Décroche, enfin ! » « Elle raccroche. » 전화기를 든다/내려놓는다는 어원."),
("B1", "Être à cran", "신경이 곤두서 있다", "[구어] « Pardon, Papa. Je suis à cran. » ↔ 정중: Je suis très tendue."),
("B1", "Mettre sur haut-parleur", "스피커폰으로 돌리다", "« Je vous mets sur haut-parleur. » 전화 중에 다른 사람이 함께 들을 수 있게 할 때. 통화 상대에게 알리는 것이 예의."),
("B1", "Il est onze heures. On ouvre à midi.", "11시야. 12시에 열어.", "시간 표현. 정오는 midi, 자정은 minuit. « à midi » 는 12시 정각에."),
("B2", "J'ai le regret de vous informer que...", "~임을 유감스럽게 알려 드립니다", "« J'ai le regret de vous informer que votre demande n'a pas été acceptée. » 공식 거절·나쁜 소식의 정형 문구. 수동태가 자주 붙는다."),
("B2", "La capacité de remboursement", "상환 능력", "« Votre capacité de remboursement est jugée insuffisante. » 소득에서 대출 원리금을 갚을 수 있는지를 나타내는 은행 용어."),
("B2", "Un motif", "사유, 이유", "« Les motifs détaillés. » 공문에서 '이유' 는 raison 보다 motif. refuser pour un motif valable."),
("B2", "Réexaminer / reconsidérer un dossier", "서류를 재검토하다", "« Le comité pourrait réexaminer un dossier modifié. » 이미 결정된 사항을 다시 보는 것. ↔ clore un dossier."),
("B2", "C'est la moindre des choses.", "그건 당연한 도리입니다.", "감사에 대한 겸손한 응답. « Merci d'avoir appelé. — C'est la moindre des choses. » ↔ 구어: De rien."),
("B2", "On ne prête qu'aux riches.", "부자에게만 빌려준다 (속담)", "이미 가진 사람만 더 얻는다는 뜻. 은행이 부자에게만 대출한다는 비판으로 자주 쓴다."),
("B2", "Une porte entrouverte", "반쯤 열린 문 (여지)", "« C'est une porte entrouverte avec un videur derrière. » 완전한 거절은 아니지만 쉽지 않은 가능성을 비유."),
("B2", "Avoir les jambes en coton", "다리에 힘이 풀리다", "« J'ai les jambes en coton. » 충격이나 공포로 휘청거릴 때. 반대로 '다리가 무쇠' 는 없다."),
("B2", "Prendre un coup de poing dans le ventre", "배를 주먹으로 얻어맞은 기분이다", "« J'ai l'impression d'avoir pris un coup de poing dans le ventre. » 충격적인 소식에 대한 비유. 실제 아픔을 말하는 건 아니다."),
("C1", "Putain de merde !", "젠장, 빌어먹을!", "[속어] 분노·절망의 감탄. ↔ 정중: Quelle catastrophe ! 쓸 수 있음: 가까운 가족·주방 동료 사이 / 금지: 손님·상사·외부인 앞(전화 상대 포함)."),
("C1", "Se tuer à la tâche", "죽도록 일하다", "« Trois ans que je me tue ici ! » 비슷한 말: se crever au travail [구어]. ↔ 정중: travailler sans relâche."),
("C1", "Cogner sur quelqu'un", "누군가에게 분풀이하다", "[구어] « Je cognerais sur quelqu'un. » 문자 그대로 '때리다' 에서 온 말이지만 말로 퍼붓는 것도 가리킨다. ↔ 정중: s'en prendre à quelqu'un."),
("C1", "Trahir ou réfléchir", "배신하다 / 숙고하다", "« Il y a une différence entre trahir et réfléchir. » 대조를 이용한 짧은 변호 문장. 병렬 구조가 기억에 남는다."),
("C1", "Les flux de trésorerie", "현금 흐름", "« Les flux de trésorerie sont négatifs. » 일정 기간 들어오고 나간 돈의 흐름. 줄여서 cash-flow."),
("C1", "Nous vous prions d'agréer...", "깊은 경의를 표합니다 (편지 맺음)", "« Nous vous prions d'agréer, madame, l'expression de nos salutations distinguées. » 프랑스 공문서 맺음말의 정형. 실제 내용과 상관없이 붙는 격식."),
]

GRAM = [
("B2", "수동태 — 공식 통보의 문체", "« Votre demande n'a pas été acceptée. » « La capacité de remboursement est jugée insuffisante. » « Les garanties ont été estimées trop faibles. » « Un courrier vous sera envoyé. » être + 과거분사. 행위자를 숨겨 거절을 부드럽고 비인격적으로 만든다. 구어에서는 on 을 쓴다: « On a refusé mon dossier. »"),
("B2", "순서 연결어 — premièrement, deuxièmement, troisièmement", "« Premièrement, la trésorerie est négative. Deuxièmement, ... Troisièmement, ... » 사유를 나열할 때의 정형. 구어에서는 d'abord / ensuite / enfin."),
("B2", "조건법 — 가능성과 약속의 거부", "« Si j'apportais un garant supplémentaire ? » « Le comité pourrait réexaminer un dossier modifié. » « Je ne vous promets rien. » si + 반과거, 조건법. pourrait 는 가능성은 있되 보장은 없다는 뉘앙스."),
("B2", "대명동사와 감정 서술 — avoir + 신체 + 상태", "« J'ai l'estomac noué. » « J'ai la gorge serrée. » « J'ai les jambes en coton. » « Je suis à cran. » 감정을 신체 감각으로 말하는 구어. avoir + 정관사 + 신체 부위 + 형용사."),
("B2", "구어 부정과 축약 — ne 생략, j'peux, t'es", "« C'est pas la même. » « J'peux rien avaler. » « T'es sûre ? » « Tu sais rien ! » 흥분하거나 가까운 사이일수록 ne 가 사라지고 je 가 축약된다. 같은 사람도 은행원 앞에서는 « Je ne peux rien avaler » 처럼 정중해진다."),
("C1", "접속법 — il faut que, je tenais à", "« Hélène, il faut que je te dise quelque chose. » il faut que + 접속법(dise). « Je tenais à vous l'annoncer moi-même » 는 tenir à + 부정사로 '꼭 ~하고 싶었다' 는 의지."),
("C1", "과거 반사실 — j'aurais fait pareil", "« À sa place, j'aurais fait pareil. » « J'aurais raconté 1991, oui ! » « Tu aurais fait quoi ? » 조건법 과거는 '그랬더라면' 이라는 비현실적 과거. 비난·후회·변호에 자주 나온다."),
]

READ = [
("숫자 읽기 — 5 200 €와 날짜", "« 5 200 € » cinq mille deux cents euros. « 1er octobre » le premier octobre. « 31 octobre » le trente et un octobre. 날짜와 금액을 또박또박 읽는다: « Cinq mille deux cents euros par mois, / à partir du premier octobre. »"),
("리에종 — vous_informer, c'est_elle", "« J'ai le regret de vous_informer » /ʒe.lə.ʁə.ɡʁɛ.də.vu.zɛ̃.fɔʁ.me/ 에서 vous 의 s 가 informer 로 이어진다. « C'est_elle. » /sɛ.tɛl/ 은 t 가 이어진다. 구어에서는 짧게 한 숨에 읽는다."),
("호흡 구간 — 소식을 전하는 문장", "« J'ai le regret de vous informer / que votre demande / n'a pas été acceptée. » 마지막 구간 앞에서 숨을 멈추고 천천히 내리면 나쁜 소식의 무게가 전해진다. Hélène 의 « Pas acceptée. » 는 숨을 삼킨 듯 짧게."),
("억양 — 화가 폭발하는 대사", "« Putain. Putain de merde ! Trois ans que je me tue ici ! » 는 첫 « Putain » 을 낮고 느리게, 두 번째를 올려 폭발하듯 읽는다. 곧이어 « Pardon. Pardon, Julien. » 은 목소리를 급히 낮춘다."),
("비음 — comment, rien, entrouverte", "« comment » /kɔ.mɑ̃/, « rien » /ʁjɛ̃/, « entrouverte » /ɑ̃.tʁu.vɛʁt/. « Tu sais rien ! » /ty.sɛ.ʁjɛ̃/ 의 마지막 비음 /ɛ̃/ 을 코로 길게 내면 짜증이 실린다."),
("u와 ou — dessus, dessous", "« refusée » /ʁə.fy.ze/ 의 u 는 입술을 둥글게 모아 /y/, « ouvre » /uvʁ/ 는 /u/. « Tu sais rien » 의 tu 와 « on ouvre » 의 ou 를 나란히 연습한다."),
("속도 변화 — 구어의 축약", "« J'peux rien avaler. » /ʒpø.ʁjɛ̃.a.va.le/ 처럼 구어에서는 e 가 탈락해 한 숨에 읽힌다. « T'es sûre ? Tu tiens debout ? » 도 빠르게. 다만 은행 전화 속 Mme Garnier 대사는 모두 또박또박."),
]

CULTURE = [
("프랑스의 나쁜 소식 전달 — 전화와 서면", "프랑스 은행은 대출을 거절할 때 담당자가 전화로 먼저 알린 뒤 공식 서면(courrier ou courriel)으로 사유를 적어 보내는 경우가 많다. 서면은 « Nous avons le regret de vous informer... » 로 시작하고 « Nous vous prions d'agréer... » 로 끝나는 정형 문구를 쓴다. 감정이 실리지 않은 이 문체 때문에 받는 사람은 더 냉정하게 느낀다."),
("속담과 가족 — 말로 하는 위로", "Lucien 은 위기마다 속담으로 가족을 위로하지만 이번에는 « On ne prête qu'aux riches » 를 말해 버리고 곧바로 후회한다. 프랑스어에는 돈·빵·날씨를 소재로 한 속담이 많고, 가족 대화에서 분위기를 풀거나 때로는 실수가 되기도 한다."),
]

META = dict(part=3, ep=32, part_label="제3부 Au bord du gouffre · 가을", title_fr="Le refus", title_ko="거절",
 place="Le Comptoir de Marthe 주방과 홀, 9월 10일 목요일 오전 10시 ~ 오후 3시 반",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Lucien Marchand (아버지) · Mme Garnier (은행 여신 담당, 전화 속 목소리)",
 wine="은행의 대출 거절(현금 흐름 적자·임대료 인상·담보 부족)과 그에 대한 엘렌·쥘리앵·뤼시앵의 반응, 쥘리앵은 아르망에게 10월 31일까지 답변 기한을 연장받음.",
 focus="수동태(공식 통보), 감정 서술(신체 표현), 조건법 과거, 거친 구어와 사과",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제33화 « L'inspection » : 9월 15일 화요일, 불시에 찾아온 위생 검사관이 주방 구석구석을 들여다본다.")
