# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, M = "Hélène", "Julien", "Chloé", "Insp. Morel"
D = [
(None, "Mardi 15 septembre, 10 h 40. Hélène et Chloé préparent le service du midi. Julien dresse les tables. Un homme d'une cinquantaine d'années entre, une sacoche à l'épaule et une carte tricolore à la main.", "9월 15일 화요일 오전 10시 40분. 엘렌과 클로에가 점심 서비스를 준비한다. 쥘리앵은 테이블을 세팅한다. 50대쯤의 남자가 어깨에 가방을 메고 삼색 띠의 신분증을 손에 든 채 들어온다."),
(J, "Bonjour, monsieur. On n'ouvre qu'à midi, mais vous pouvez réserver.", "안녕하세요, 손님. 12시에 열지만 예약은 하실 수 있습니다."),
(M, "Bonjour. Je ne viens pas déjeuner. Inspecteur Morel, Direction départementale de la protection des populations.", "안녕하세요. 식사하러 온 게 아닙니다. 도 주민보호국의 모렐 검사관입니다."),
(M, "Voici ma carte professionnelle. Je souhaite parler à la responsable.", "제 직무 신분증입니다. 책임자와 이야기하고 싶습니다."),
(J, "La responsable... Un instant, monsieur. Hélène !", "책임자요... 잠시만요, 선생님. 엘렌!"),
(H, "Quoi ? Je suis dans la sauce !", "뭐야? 소스 만들고 있는데!"),
(J, "Viens. C'est important.", "와 봐. 중요한 일이야."),
(H, "Bonjour, monsieur. Hélène Marchand, la propriétaire. Qu'est-ce que je peux faire pour vous ?", "안녕하세요. 주인인 엘렌 마르샹입니다. 무엇을 도와드릴까요?"),
(M, "Madame Marchand, je suis inspecteur sanitaire. Je procède à un contrôle inopiné de votre établissement.", "마르샹 씨, 저는 위생 검사관입니다. 이 업소에 대해 불시 점검을 실시합니다."),
(H, "Un contrôle ? Maintenant ? On sert dans une heure et demie.", "점검이요? 지금요? 한 시간 반 뒤에 영업인데요."),
(M, "C'est justement le principe d'un contrôle inopiné. Il ne se prévient pas.", "그게 바로 불시 점검의 원칙입니다. 미리 알리지 않죠."),
(H, "Je comprends. Mais pourquoi nous ? On n'a jamais eu de problème.", "알겠습니다. 그런데 왜 저희죠? 문제가 있었던 적이 없는데요."),
(M, "Nous avons reçu un signalement. Je ne peux pas vous en dire plus.", "신고가 접수됐습니다. 더는 말씀드릴 수 없습니다."),
(H, "Un signalement de qui ?", "누가 신고했는데요?"),
(M, "Je ne le sais pas moi-même, madame. Et même si je le savais, je ne vous le dirais pas.", "저도 모릅니다. 알더라도 말씀드리지 않을 겁니다."),
(J, "Génial. Quelqu'un nous balance, et on ne sait même pas qui.", "대단하네. 누가 우리를 찔렀는데 누군지도 모르다니."),
(H, "Julien, pas maintenant. Monsieur Morel, faites votre travail. Qu'est-ce que vous voulez voir ?", "쥘리앵, 지금은 안 돼. 모렐 씨, 일을 하세요. 뭘 보고 싶으세요?"),
(M, "La cuisine d'abord. Puis la réserve, les chambres froides, la salle et les sanitaires.", "먼저 주방. 그다음 저장실, 냉장실, 홀과 화장실입니다."),
(M, "Je vous demande de ne rien déplacer et de me laisser circuler librement.", "아무것도 옮기지 마시고 자유롭게 다니게 해 주십시오."),
(H, "Faites. Chloé, lave-toi les mains. Monsieur passe en cuisine.", "하세요. 클로에, 손 씻어. 검사관님이 주방에 들어가신다."),
(C, "Oui, Chef. Bonjour, monsieur.", "네, 셰프. 안녕하세요, 검사관님."),
(None, "Morel enfile une blouse blanche et une charlotte, sort un thermomètre à sonde et une tablette. Il commence par la chambre froide, sans un mot.", "모렐은 흰 가운과 위생모를 쓰고 탐침 온도계와 태블릿을 꺼낸다. 그는 말없이 냉장실부터 시작한다."),
(M, "L'affichage indique 3 degrés. Ma sonde donne 3,4. C'est conforme.", "표시창은 3도, 제 탐침은 3.4도입니다. 기준에 맞습니다."),
(H, "On la surveille deux fois par jour, matin et soir.", "하루 두 번, 아침저녁으로 확인합니다."),
(M, "Justement. Je voudrais voir votre cahier de relevés de température.", "그렇다면 온도 기록 노트를 보고 싶습니다."),
(H, "Il est accroché près de la porte. Chloé, passe-le-moi.", "문 옆에 걸려 있어요. 클로에, 이리 줘."),
(C, "Voilà, Chef. Voilà, monsieur.", "여기요, 셰프. 여기 있습니다, 검사관님."),
(M, "Merci. Les relevés sont réguliers jusqu'au 29 juin.", "감사합니다. 6월 29일까지는 기록이 규칙적이군요."),
(H, "Et après ?", "그 뒤는요?"),
(M, "Rien du 30 juin au 3 juillet. Quatre jours sans aucune ligne.", "6월 30일부터 7월 3일까지는 없습니다. 나흘 동안 한 줄도 없어요."),
(H, "Le 30 juin, c'était la panne. Il faisait 38 degrés dehors, la chambre froide est tombée.", "6월 30일은 고장 났던 날이에요. 밖이 38도였고 냉장실이 멈췄죠."),
(M, "Je comprends la panique. Mais c'est justement quand le froid lâche qu'il faut tout noter.", "당황은 이해합니다. 하지만 냉장이 멈췄을 때야말로 전부 기록해야 합니다."),
(H, "On avait quatre-vingts kilos de viande à sauver. On n'a pas pensé au cahier.", "구해야 할 고기가 80킬로였어요. 노트 생각은 못 했습니다."),
(M, "Je vous crois. Mais sans trace écrite, je ne peux pas prouver que la chaîne du froid a été respectée.", "믿습니다. 하지만 서면 기록이 없으면 저온 유통이 지켜졌다고 증명할 수 없습니다."),
(H, "On a jeté tout ce qui était douteux. J'ai la facture du réparateur, si ça peut aider.", "의심스러운 건 전부 버렸습니다. 도움이 되면 수리업체 청구서도 있어요."),
(M, "Gardez-la, elle servira. Je note l'absence de relevés. Passons aux produits.", "보관하세요, 쓸모가 있을 겁니다. 기록 누락은 적어 두겠습니다. 식재료로 넘어가죠."),
(M, "Passons aux produits. Je prends quelques barquettes au hasard.", "식재료를 보겠습니다. 용기 몇 개를 무작위로 집겠습니다."),
(H, "Prenez ce que vous voulez. Tout est fait maison.", "원하는 걸 집으세요. 전부 직접 만든 겁니다."),
(M, "Ces barquettes : quelle est la date de fabrication ?", "이 용기들은 제조일이 언제입니까?"),
(H, "Hier soir. Le velouté, c'est moi qui l'ai fait.", "어제 저녁입니다. 수프는 제가 직접 만들었어요."),
(M, "Aucune étiquette. Ni date de production, ni DLC. Qui étiquette, ici ?", "라벨이 없습니다. 제조일도 소비기한도요. 여기선 누가 라벨을 붙입니까?"),
(C, "C'est moi, normalement, monsieur. Mais ce matin, je...", "원래는 저예요, 검사관님. 그런데 오늘 아침엔 제가..."),
(H, "C'est ma responsabilité, pas la sienne. Je suis la cheffe, je signe tout.", "그건 제 책임이지 이 애 책임이 아닙니다. 제가 셰프이고 모든 것에 서명하니까요."),
(M, "Je retiens que l'étiquetage est incomplet. Il faut que chaque préparation porte une date limite de consommation.", "라벨 표기가 불완전한 것으로 적습니다. 모든 조리 식품에 소비기한이 표시되어야 합니다."),
(H, "Compris. Ce sera fait avant midi.", "알겠습니다. 정오 전에 하겠습니다."),
(M, "Montrez-moi maintenant la réserve sèche.", "이제 건식 저장실을 보여 주세요."),
(None, "Dans la réserve, sacs de farine, riz, pâtes. Morel braque une lampe derrière les sacs du fond, s'accroupit, reste immobile.", "저장실에는 밀가루, 쌀, 파스타 자루가 있다. 모렐이 안쪽 자루 뒤에 손전등을 비추고 쪼그려 앉아 가만히 있다."),
(M, "Madame Marchand, venez voir.", "마르샹 씨, 와서 보세요."),
(H, "Qu'est-ce que c'est ?", "뭔가요?"),
(M, "Des déjections de rongeurs. Il y en a une dizaine, derrière le sac de farine.", "설치류 배설물입니다. 밀가루 자루 뒤에 열 개 정도 있습니다."),
(H, "C'est pas possible. On a mis des pièges en juin.", "말도 안 돼요. 6월에 덫을 놨는데."),
(M, "Je ne peux pas dire si ce sont des souris ou des rats. Mais ils sont passés par là, récemment.", "쥐인지 생쥐인지는 말할 수 없습니다. 하지만 최근에 지나갔습니다."),
(C, "Oh non... Hélène, je suis désolée, je n'ai jamais regardé derrière les sacs.", "아니... 엘렌, 죄송해요. 자루 뒤는 한 번도 안 봤어요."),
(H, "Ce n'est pas ta faute, Chloé. Ça fait des semaines que j'aurais dû regarder.", "네 잘못 아니야, 클로에. 몇 주 전에 내가 봤어야 했어."),
(M, "Je note : présence de traces de rongeurs en réserve sèche. C'est un point critique.", "적습니다. 건식 저장실에 설치류 흔적이 있음. 중대 항목입니다."),
(H, "Critique, ça veut dire quoi, pour nous ?", "중대하다는 게 저희에게는 무슨 뜻인가요?"),
(M, "Que je dois le signaler en priorité dans mon rapport. Je regrette que vous l'appreniez ainsi.", "보고서에서 우선적으로 보고해야 한다는 뜻입니다. 이런 식으로 알게 되셔서 유감입니다."),
(H, "Je préfère l'apprendre que l'ignorer.", "모르고 지내는 것보다는 알게 되는 편이 낫습니다."),
(M, "C'est une bonne réaction. Passons au lavabo.", "좋은 반응입니다. 손 씻는 세면대를 봅시다."),
(M, "Pas de savon. Pas de papier. Pour un lavabo réservé au lavage des mains, c'est un manquement.", "비누가 없습니다. 종이도 없고요. 손 씻는 전용 세면대로서는 미비입니다."),
(C, "Le savon, c'est moi. Je l'ai fini hier soir, et j'ai oublié d'en racheter.", "비누는 저예요. 어제 저녁에 다 썼는데 사 놓는 걸 잊었어요."),
(H, "Chloé, on en parlera après. Monsieur, c'est un oubli, pas une habitude.", "클로에, 나중에 얘기하자. 검사관님, 이건 습관이 아니라 깜빡한 겁니다."),
(M, "Je note l'oubli. Mais un oubli suffit à contaminer une cuisine.", "깜빡한 것으로 적겠습니다. 하지만 깜빡 하나로도 주방은 오염될 수 있습니다."),
(M, "Je tiens à dire que la cuisine est propre. Les plans de travail sont en ordre, la plonge est bien tenue.", "주방은 깨끗하고 조리대는 정돈되어 있고 설거지장도 잘 관리되어 있다는 점은 말씀드리겠습니다."),
(H, "Merci. C'est quand même quelque chose.", "감사합니다. 그래도 의미는 있네요."),
(M, "Cela ne compense pas le reste, madame. Ce sont des points positifs, pas des excuses.", "그것이 나머지를 상쇄하진 않습니다. 긍정적 요소지 면죄부는 아닙니다."),
(H, "Je n'ai jamais voulu des excuses. Je veux savoir ce que je dois faire.", "면죄부를 원한 적은 없습니다. 제가 뭘 해야 하는지 알고 싶어요."),
(M, "Je vais visiter la salle et les toilettes, puis je rédigerai mon rapport.", "홀과 화장실을 본 다음 보고서를 작성하겠습니다."),
(J, "Par ici, monsieur. La salle est au fond du couloir.", "이쪽입니다, 검사관님. 홀은 복도 끝에 있습니다."),
(None, "Julien guide l'inspecteur. Hélène et Chloé restent seules en cuisine, sans oser se regarder. Dix minutes passent. Morel revient, tablette à la main.", "쥘리앵이 검사관을 안내한다. 엘렌과 클로에는 서로 쳐다보지 못한 채 주방에 남는다. 10분이 흐른다. 모렐이 태블릿을 들고 돌아온다."),
(M, "La salle est conforme. Les sanitaires sont corrects. Je clos mon contrôle.", "홀은 기준에 맞습니다. 화장실도 양호합니다. 점검을 마칩니다."),
(M, "Je vous résume les écarts constatés. Un : traces de rongeurs en réserve sèche.", "발견된 미비 사항을 요약합니다. 하나, 건식 저장실의 설치류 흔적."),
(M, "Deux : absence de relevés de température du 30 juin au 3 juillet.", "둘, 6월 30일부터 7월 3일까지 온도 기록 부재."),
(M, "Trois : préparations sans date limite de consommation. Quatre : lavabo sans savon ni papier.", "셋, 소비기한이 없는 조리 식품. 넷, 비누와 종이가 없는 세면대."),
(H, "Quatre points. Et la suite ?", "네 가지군요. 그다음은요?"),
(M, "Mon rapport sera transmis à la préfecture. C'est elle qui décide des suites.", "제 보고서는 도청에 전달됩니다. 후속 조치는 도청이 결정합니다."),
(H, "Quelles suites, concrètement ?", "구체적으로 어떤 조치죠?"),
(M, "Je ne peux pas me prononcer. Cela peut aller d'un simple avertissement à des mesures plus lourdes.", "제가 말할 수 없습니다. 단순 경고부터 더 무거운 조치까지 가능합니다."),
(H, "Plus lourdes comment ?", "더 무거운 조치가 뭔데요?"),
(M, "Je ne peux pas en dire plus aujourd'hui. Vous recevrez un courrier dans quelques jours.", "오늘은 더 말씀드릴 수 없습니다. 며칠 안에 공문을 받으실 겁니다."),
(H, "Et si je corrige tout dès aujourd'hui ?", "오늘부터 전부 시정하면요?"),
(M, "Il faudra le prouver. Je vous conseille de faire intervenir un professionnel contre les nuisibles.", "그것을 증명해야 합니다. 해충 방제 전문업체를 부르시길 권합니다."),
(M, "Et gardez toutes les factures. Que vous puissiez montrer vos efforts, c'est important.", "그리고 청구서를 전부 보관하세요. 노력을 보여 줄 수 있다는 게 중요합니다."),
(H, "J'appelle quelqu'un dès que vous serez parti.", "검사관님이 가시자마자 전화하겠습니다."),
(M, "Voici un exemplaire du procès-verbal de la visite. Je vous demande de signer ici.", "점검 확인서 한 부입니다. 여기에 서명해 주십시오."),
(H, "Je signe où ?", "어디에 서명하죠?"),
(M, "En bas, à gauche. Votre signature n'est pas un aveu. Elle atteste que vous avez reçu le document.", "왼쪽 아래입니다. 서명은 자백이 아니라 문서를 받았음을 확인하는 겁니다."),
(H, "Voilà. Au revoir, monsieur.", "했습니다. 안녕히 가세요."),
(M, "Au revoir, madame. Bon courage, sincèrement.", "안녕히 계세요. 진심으로 힘내시길 바랍니다."),
(None, "La porte se referme. Pendant dix secondes, plus personne ne parle. Puis Hélène s'appuie des deux mains sur le plan de travail.", "문이 닫힌다. 10초 동안 아무도 말하지 않는다. 그러더니 엘렌이 두 손으로 조리대를 짚는다."),
(H, "Putain. Des rats. Des putains de rats dans ma réserve !", "젠장. 쥐라니. 우리 저장실에 빌어먹을 쥐라니!"),
(J, "Des souris, peut-être.", "생쥐일 수도 있어."),
(H, "Rats, souris, je m'en fous ! C'est le mot qui compte, Julien. Le mot « rongeurs » dans un rapport officiel !", "쥐든 생쥐든 상관없어! 중요한 건 그 단어야, 쥘리앵. 공식 보고서에 적힌 « 설치류 »라는 말!"),
(J, "Calme-toi. Respire.", "진정해. 숨 쉬어."),
(H, "Je me calmerai quand ce sera fini. Chloé, viens là.", "끝나면 진정할게. 클로에, 이리 와."),
(C, "Chef, je suis vraiment, vraiment désolée. Pour le savon, pour les étiquettes...", "셰프, 정말 정말 죄송해요. 비누도, 라벨도..."),
(H, "Écoute-moi. C'est moi qui t'ai mal formée. Je t'ai dit « fais vite », jamais « fais bien ».", "들어 봐. 널 제대로 가르치지 못한 건 나야. 늘 « 빨리 해 »라고만 했지 « 잘 해 »라고는 안 했어."),
(C, "Vous m'avez appris beaucoup de choses, Chef.", "많은 걸 가르쳐 주셨어요, 셰프."),
(H, "Pas les bonnes, apparemment. Mais ça va changer. Aujourd'hui.", "제대로 된 건 아닌 모양이야. 하지만 바뀔 거야. 오늘부터."),
(J, "Qu'est-ce qu'on fait, concrètement ? Je prends des notes.", "구체적으로 뭘 해? 내가 적을게."),
(H, "Un : j'appelle une entreprise de dératisation, tout de suite.", "하나, 지금 당장 방제업체에 전화한다."),
(H, "Deux : Chloé, tu étiquettes chaque barquette avant midi, avec date et DLC.", "둘, 클로에, 정오 전에 모든 용기에 날짜와 소비기한 라벨을 붙여."),
(H, "Trois : Julien, tu cours acheter du savon, du papier, des pièges, tout ce qu'on trouve.", "셋, 쥘리앵, 비누, 종이, 덫, 구할 수 있는 건 다 사 와."),
(J, "Je pars. Et le cahier de températures ?", "다녀올게. 온도 기록 노트는?"),
(H, "Quatre : on le remplit trois fois par jour. À partir de maintenant. Et je le signe moi-même.", "넷, 하루 세 번 적는다. 지금부터. 그리고 내가 직접 서명한다."),
(C, "Je m'en occupe. Promis.", "제가 맡을게요. 약속해요."),
(H, "Non, je m'en occupe. Toi, tu fais les étiquettes. Compris ?", "아니, 내가 맡아. 넌 라벨을 붙여. 알겠어?"),
(C, "Compris, Chef.", "알겠습니다, 셰프."),
(J, "Pourvu que ça en reste là.", "여기서 끝나기만을 바랄 뿐이야."),
(H, "Que ça en reste là ? Il a dit « mesures plus lourdes ». Il ne parlait pas d'un avertissement.", "여기서 끝난다고? 그는 « 더 무거운 조치 »라고 했어. 경고 얘기가 아니었어."),
(J, "Il n'a pas dit lesquelles.", "어떤 조치인지는 말 안 했잖아."),
(H, "Parce qu'il sait. Ou parce qu'il nous laisse imaginer. Les deux sont pires.", "알기 때문이거나 우리가 상상하게 놔둔 거겠지. 둘 다 더 나빠."),
(J, "Tu penses que c'est quelqu'un qui nous a dénoncés ?", "누가 우리를 신고했다고 생각해?"),
(H, "Un signalement, c'est ce qu'il a dit. Peu importe qui.", "신고라고 했어. 누구든 상관없어."),
(J, "Ça m'importe, moi. Si c'était...", "난 중요해. 만약 그게..."),
(H, "Arrête. Je ne veux pas de soupçons dans ma cuisine. On travaille, c'est tout.", "그만해. 내 주방에서 의심은 사절이야. 일이나 하자."),
(J, "D'accord. Mais ça m'embête.", "알았어. 그래도 마음에 걸려."),
(H, "À moi aussi. Mais ce qui m'embête le plus, c'est qu'il ait vu juste.", "나도 그래. 하지만 가장 걸리는 건 그가 정확히 봤다는 거야."),
(C, "Ils ont raison pour les souris ?", "쥐 얘기는 맞는 거죠?"),
(H, "Ils ont raison pour tout. C'est ça, le pire.", "전부 맞아. 그게 가장 나빠."),
(J, "Allez, je file. Cinq minutes.", "자, 다녀올게. 5분이면 돼."),
(H, "Prends ton temps. Mais reviens avant midi.", "천천히 다녀와. 그래도 정오 전엔 돌아와."),
(C, "Chef... on ouvre quand même à midi ?", "셰프... 그래도 정오에 열죠?"),
(H, "On ouvre. Tant que personne ne nous dit de fermer, on ouvre.", "연다. 누가 닫으라고 하기 전까지는 연다."),
(None, "Julien sort en courant. Chloé commence à écrire les dates à la main, les doigts un peu tremblants. Hélène sort son téléphone et cherche un numéro.", "쥘리앵이 뛰어나간다. 클로에는 약간 떨리는 손으로 날짜를 적기 시작한다. 엘렌은 전화기를 꺼내 번호를 찾는다."),
(H, "Allô ? Oui, bonjour. Vous faites de la dératisation en urgence ?", "여보세요? 네, 안녕하세요. 긴급 방제도 하십니까?"),
]

VOCAB = [
("A2", "Un contrôle", "점검, 검사", "« Un contrôle inopiné. » 위생·세무·교통 등 각종 점검. contrôler = 점검하다."),
("A2", "Je signe où ?", "어디에 서명해요?", "« Je signe où ? — En bas, à gauche. » 서류 장면의 기본 질문. signer 는 서명하다."),
("B1", "Un signalement", "(익명) 신고, 제보", "« Nous avons reçu un signalement. » 제3자의 신고를 뜻하는 공적 단어. dénonciation 은 비난이 담긴 말이라 일상에서는 signalement 를 쓴다."),
("B1", "Inopiné", "불시의", "« Un contrôle inopiné. » 예고 없이 갑자기. 반대는 annoncé, prévu."),
("B1", "Un relevé de température", "온도 기록", "« Le cahier de relevés de température. » relever 는 '측정해서 기록하다'. 위생 점검에서 가장 먼저 보는 서류."),
("B1", "Une barquette", "(식품) 용기, 트레이", "« Ces barquettes de velouté. » 플라스틱·알루미늄 포장 용기."),
("B1", "Un lavabo / se laver les mains", "세면대 / 손을 씻다", "« Le lavabo réservé au lavage des mains. » 주방에서는 손 씻는 세면대와 설거지 싱크가 따로 있어야 한다."),
("B2", "La DLC (date limite de consommation)", "소비기한", "« Ni date de production, ni DLC. » 이 날짜 이후에는 먹으면 안 된다. 품질 유지 기한은 DDM(date de durabilité minimale)."),
("B2", "La chaîne du froid", "저온 유통(콜드체인)", "« Je ne peux pas prouver que la chaîne du froid a été respectée. » 식품을 생산부터 식탁까지 일정 저온으로 유지하는 것."),
("B2", "La traçabilité / une trace écrite", "추적 가능성 / 서면 기록", "« Sans trace écrite, je ne peux pas prouver... » 위생 행정의 핵심은 '기록이 있어야 한다' 는 것."),
("B2", "Un manquement", "의무 위반, 미비", "« C'est un manquement. » 규정을 어긴 사항. 형사 사건에서 쓰는 infraction 보다 약하다."),
("B2", "Constater un écart", "미비·불일치를 확인하다", "« Je vous résume les écarts constatés. » écart 는 기준과의 차이. 행정 보고서의 정형어."),
("B2", "Rédiger un rapport / un procès-verbal", "보고서·확인서를 작성하다", "« Je rédigerai mon rapport. » « Un exemplaire du procès-verbal. » 공무원이 현장에서 작성하는 공식 문서."),
("B2", "Se prononcer", "견해를 밝히다, 판단을 내리다", "« Je ne peux pas me prononcer. » 결정권이 없는 사람이 판단을 유보할 때의 정중한 거절."),
("B2", "Dératisation / nuisibles", "쥐 방제 / 해충", "« Une entreprise de dératisation. » « Un professionnel contre les nuisibles. » 쥐·바퀴벌레 등의 방제 서비스."),
("B2", "Pourvu que + 접속법", "~하기만을 바란다", "« Pourvu que ça en reste là. » 간절한 소망. 불안과 희망이 섞인 구어 표현."),
("C1", "Un point critique", "중대 항목", "« C'est un point critique. » 식품 안전에서 즉시 시정이 필요한 위험 요소. 단순 미비(manquement)보다 무겁다."),
("C1", "Inopiné vs. inattendu", "불시의 vs. 뜻밖의", "inopiné 는 예고 없이 닥친 일(점검·방문). inattendu 는 기대하지 않았던 결과나 사람. « Une visite inopinée. »"),
("C1", "Une mise en demeure", "최고, 시정 통지", "공문에서 정해진 기한 안에 의무를 이행하라고 요구하는 통지. 이 화에서는 « un simple avertissement » 로 에둘러 말한다."),
("C1", "Dénoncer / balancer", "고발하다 / 찌르다", "[속어] « Quelqu'un nous balance. » ↔ 정중: signaler, dénoncer. 쓸 수 있음: 가까운 직원 사이 / 금지: 손님·공무원 앞."),
("C1", "Un aveu", "자백", "« Votre signature n'est pas un aveu. » aveu 는 잘못을 인정하는 말. 서명은 수령 확인일 뿐이라는 설명."),
("C1", "Voir juste", "정확히 보다", "« Il ait vu juste. » voir juste = 판단이 정확하다. 쓰라린 사실을 인정할 때 쓴다."),
("C1", "Putain de ...", "빌어먹을 ~", "[속어] « Des putains de rats ! » 분노를 강조하는 접두 표현. ↔ 정중: ces maudits rats. 쓸 수 있음: 가까운 주방 동료 사이 / 금지: 손님·상사·검사관 앞."),
]

GRAM = [
("B2", "접속법 — il faut que, je regrette que", "« Il faut que chaque préparation porte une date limite. » « Je regrette que vous l'appreniez ainsi. » « Que vous puissiez montrer vos efforts, c'est important. » il faut que / regretter que / que 주어절 뒤에는 접속법. porte, apprenne → appreniez, puissiez."),
("B2", "접속법 — pourvu que, avant que, c'est qu'il ait", "« Pourvu que ça en reste là. » « Ce qui m'embête, c'est qu'il ait vu juste. » 소망(pourvu que)과 감정·평가(ce qui m'embête, c'est que)도 접속법. 접속법 과거 « ait vu » 는 이미 일어난 일에 대한 감정."),
("B2", "행정 어휘의 수동태·비인칭", "« Mon rapport sera transmis à la préfecture. » « Il faudra le prouver. » « Vous recevrez un courrier. » 미래·수동으로 비인격적인 어조를 만든다. Morel 은 감정을 싣지 않기 위해 이 문형을 쓴다."),
("B2", "제한 표현 — ni ... ni, ne ... aucun", "« Ni date de production, ni DLC. » « Aucune étiquette. » « Rien du 30 juin au 3 juillet. » 없음을 강조하는 부정. 보고서 문체에서 사실을 짧게 말할 때 쓴다."),
("B2", "조건 — si + 현재, 미래 / 가능성", "« Et si je corrige tout dès aujourd'hui ? — Il faudra le prouver. » si + 현재, 단순미래/현재는 가능성 있는 조건. 은행 장면의 si + 반과거와 대비된다(31·32화)."),
("C1", "명령과 요구의 정중한 구조", "« Je vous demande de ne rien déplacer. » « Je vous conseille de faire intervenir un professionnel. » « Gardez toutes les factures. » demander / conseiller + de + 부정사. 공무원이 명령을 부드러운 요청으로 바꿀 때의 정형."),
("C1", "구어 — ne 생략, faut que, on 으로 전환", "« C'est pas possible. » « On a mis des pièges. » « Tu cours acheter du savon. » 같은 Hélène 도 Morel 앞에서는 « Je ne peux pas vous dire » 식의 vous, 직원 앞에서는 « Rats, souris, je m'en fous ! » 로 완전히 바뀐다. 상대에 따른 어체 전환."),
]

READ = [
("숫자와 날짜 — 6월 30일부터 7월 3일까지", "« Du trente juin / au trois juillet. » 날짜 사이에 짧은 호흡을 둔다. « 38 degrés » trente-huit degrés, « 3,4 » trois virgule quatre. « quatre-vingts kilos » 의 s 는 뒤에 단어가 오지 않으면 발음하지 않는다."),
("리에종 — c'est_un, quand_il, les_étiquettes", "« C'est_un point critique. » /sɛ.tœ̃.pwɛ̃.kʁi.tik/. « Les_étiquettes » 는 /le.ze.ti.kɛt/ 처럼 s 가 z 로 이어진다. Morel 의 대사는 모든 리에종을 정확히 한다."),
("호흡 구간 — 요약 보고", "« Un : / traces de rongeurs / en réserve sèche. / Deux : / absence de relevés / du trente juin au trois juillet. » 번호 뒤에 쉼을 두고 항목은 한 호흡에 읽는다. 감정 없는 낮은 톤을 유지한다."),
("억양 — 담담한 Morel, 폭발하는 Hélène", "Morel 은 « Je ne peux pas en dire plus aujourd'hui. » 를 끝을 내려 평탄하게. Hélène 은 « Rats, souris, je m'en fous ! » 를 급하게 올렸다 끊어 읽는다. 같은 장면에서 두 톤이 대비된다."),
("비음 — inopiné, rongeurs, constaté", "« inopiné » /i.nɔ.pi.ne/, « rongeurs » /ʁɔ̃.ʒœʁ/, « constaté » /kɔ̃s.ta.te/. 비음 /ɔ̃/ 은 입술을 둥글게 하고 코로 길게 낸다. 한국어 '옹' 에 가깝다."),
("r — régulier, rapport, rats", "« régulier » /ʁe.ɡy.lje/, « rapport » /ʁa.pɔʁ/, « rats » /ʁa/. 어두의 r 을 목구멍에서 부드럽게 긁는다. 분노 대사에서는 r 을 약간 세게 굴린다."),
("억양의 변화 — 사과하는 클로에", "« Chef, je suis vraiment, vraiment désolée. » 는 두 번째 vraiment 에서 목소리를 낮추고 약간 떨듯이 읽는다. 사과는 속도가 느릴수록 진심이 전해진다."),
]

CULTURE = [
("프랑스의 위생 점검 — DDPP와 불시 방문", "프랑스에서는 도(département) 단위의 소비자 보호·식품 안전 기관(DDPP, 현 DDETSPP)의 검사관이 식당을 불시에 점검한다. 온도 기록, 라벨(DLC), 설치류·해충 관리, 손 씻는 시설 등을 보고 결과를 도 지사(préfet)에게 보고하며, 지사가 조치를 정한다. 신고(signalement)는 소비자·직원·이웃 누구나 할 수 있고 출처는 검사관도 밝히지 않는다."),
("DLC와 DDM — 날짜 표시", "프랑스 식품에는 두 가지 날짜가 있다. DLC(date limite de consommation)는 '이 날짜 이후엔 먹지 말라' 는 안전 기한이고, DDM(date de durabilité minimale)은 '이 날짜까지 맛이 최고' 라는 품질 기한이다. 식당에서 직접 만든 수프·테린 같은 조리 식품에는 제조일과 DLC 를 붙이는 것이 기본이다."),
]

META = dict(part=3, ep=33, part_label="제3부 Au bord du gouffre · 가을", title_fr="L'inspection", title_ko="위생 검사",
 place="Le Comptoir de Marthe 주방·저장실·홀, 9월 15일 화요일 오전 10시 40분 ~ 정오 전",
 chars="Hélène Marchand (주인 셰프) · Insp. Morel (DDPP 검사관) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버)",
 wine="DDPP 검사관의 불시 점검: 건식 저장실의 설치류 흔적, 6월 30일~7월 3일 온도 기록 누락, 소비기한 라벨 미표기, 손 씻는 세면대의 비누 부족.",
 focus="행정·위생 규정 어휘, 접속법(il faut que, regretter que, pourvu que), 정중한 vous와 거친 구어의 전환",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제34화 « Fermeture administrative » : 9월 18일 금요일, 도청 공문이 도착한다. 정문에 붙은 종이 한 장이 가게를 멈춰 세운다.")
