# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, C = "Hélène", "Lucien", "Julien", "Chloé"
D = [
(None, "Vendredi 18 septembre, 10 h 50. Trois jours après l'inspection. Hélène prépare le service quand un agent de la préfecture entre, pose une enveloppe sur le comptoir et colle une feuille sur la porte.", "9월 18일 금요일 오전 10시 50분. 검사 사흘 뒤다. 엘렌이 영업 준비를 하는데 도청 직원이 들어와 계산대에 봉투를 놓고, 문에 종이 한 장을 붙인다."),
(J, "Hélène, il fait quoi, le monsieur ? Il colle un truc sur notre porte !", "엘렌, 저 사람 뭐 하는 거야? 우리 문에 뭘 붙이고 있어!"),
(H, "Je sais pas. Je vais voir. Reste ici, Julien.", "몰라. 가 볼게. 쥘리앵, 넌 여기 있어."),
(J, "Il t'a laissé une enveloppe. Elle est sur le comptoir.", "봉투 하나 두고 갔어. 계산대 위에 있어."),
(H, "Je l'ouvre. Mon Dieu, c'est le cachet de la préfecture.", "열어 볼게. 세상에, 도청 직인이야."),
(J, "Lis-la à voix haute. Je préfère savoir tout de suite.", "소리 내서 읽어 줘. 바로 알고 싶어."),
(H, "« Le préfet de police ordonne la fermeture administrative de l'établissement. »", "« 경찰청장은 해당 영업장의 행정 폐쇄를 명한다. »"),
(H, "« Durée : quinze jours, du dix-huit septembre au deux octobre. »", "« 기간: 15일, 9월 18일부터 10월 2일까지. »"),
(J, "Quinze jours. Putain. Quinze jours, Hélène.", "15일. 젠장. 15일이라고, 엘렌."),
(H, "Attends, il y a une dernière ligne. « Effet immédiat. »", "잠깐, 마지막 줄이 있어. « 즉시 효력. »"),
(J, "Immédiat ? Mais on a quarante couverts réservés ce midi !", "즉시라고? 오늘 점심 예약이 40명인데!"),
(H, "C'est écrit comme ça, Julien. Aujourd'hui, c'est fini.", "그렇게 쓰여 있어, 쥘리앵. 오늘부로 끝이야."),
(J, "Pas de service ce midi, pas de service ce soir ?", "점심도 저녁도 영업 못 한다는 거야?"),
(H, "Ni ce midi, ni ce soir, ni demain. Rien pendant quinze jours.", "점심도, 저녁도, 내일도 안 돼. 15일 동안 아무것도."),
(J, "C'est pas possible. On n'a pas fait une faute si grave que ça.", "말도 안 돼. 우리가 그렇게 큰 잘못을 한 건 아니잖아."),
(H, "Les rats, les températures, les étiquettes. Pour eux, c'est assez grave.", "쥐, 온도 기록, 라벨. 저쪽엔 그걸로 충분히 심각한 거야."),
(J, "Les rats, on n'en a jamais vu un seul dans la salle !", "쥐는 홀에서 한 마리도 본 적 없다고!"),
(H, "Dans le stock sec, Julien. Il a trouvé des traces dans le stock sec.", "건식 창고였어, 쥘리앵. 건식 창고에서 흔적을 찾았잖아."),
(J, "Oui, je sais. Mais de là à fermer tout le restaurant...", "응, 알아. 그래도 가게 전체를 닫는 건..."),
(H, "Ça s'appelle une fermeture administrative. On n'a pas le choix.", "그게 행정 폐쇄라는 거야. 선택권이 없어."),
(None, "Chloé arrive avec son sac, un grand sourire aux lèvres. Elle s'arrête devant la porte et lit l'affiche.", "클로에가 가방을 메고 환한 얼굴로 들어온다. 문 앞에서 멈춰 공고문을 읽는다."),
(C, "Bonjour ! Euh... pourquoi il y a une affiche sur la porte ?", "안녕하세요! 어... 문에 왜 공고문이 붙어 있어요?"),
(H, "Entre, Chloé. On a une mauvaise nouvelle.", "들어와, 클로에. 안 좋은 소식이 있어."),
(C, "C'est quoi, « fermeture administrative » ? Je connais pas ce mot.", "« 행정 폐쇄 »가 뭐예요? 처음 듣는 말인데요."),
(J, "C'est quand l'État te ferme ton restaurant. De force.", "나라가 식당 문을 닫게 하는 거야. 강제로."),
(C, "De force ? Mais pourquoi ? On a fait quoi de mal ?", "강제로요? 왜요? 우리가 뭘 잘못했는데요?"),
(H, "L'inspection de mardi. Le rapport est arrivé, et le préfet a décidé.", "화요일 검사 말이야. 보고서가 와서 경찰청장이 결정했어."),
(C, "Pour combien de temps ? Dites-moi que c'est pas long.", "얼마 동안이에요? 길지 않다고 말해 주세요."),
(H, "Quinze jours. Jusqu'au vendredi deux octobre.", "15일. 10월 2일 금요일까지."),
(C, "Quinze jours sans travailler... Et nos clients de ce midi ?", "15일을 일을 못 한다니... 오늘 점심 손님들은요?"),
(J, "Je dois les appeler. Tous. Un par un.", "내가 전화해야 해. 전부. 한 명씩."),
(H, "Je t'aide. On se partage la liste, d'accord ?", "내가 도울게. 명단을 나눠서 하자, 알았지?"),
(J, "D'accord. Mais qu'est-ce que je leur dis, franchement ?", "알았어. 근데 솔직히 뭐라고 말해?"),
(H, "La vérité, en trois phrases. On ferme, on est désolés, on vous rappelle.", "진실을 세 문장으로. 문을 닫는다, 죄송하다, 다시 연락드린다."),
(C, "Je peux les appeler aussi. Je suis nulle au téléphone, mais je veux aider.", "저도 전화할게요. 전화는 서툴지만 돕고 싶어요."),
(H, "Merci, Chloé. Prends la liste du midi. Les noms en haut.", "고마워, 클로에. 점심 명단을 가져가. 위에 있는 이름들."),
(C, "Vous êtes sûrs qu'on peut pas faire appel ?", "이의 신청은 정말 못 하는 거예요?"),
(H, "On peut faire un recours, mais ça prend des semaines. Et ça coûte cher.", "이의 제기는 할 수 있지만 몇 주 걸려. 돈도 많이 들고."),
(J, "Et pendant ce temps, la porte reste fermée.", "그동안 문은 계속 닫혀 있고."),
(H, "Voilà. Mieux vaut réparer vite que se battre longtemps.", "그래. 오래 싸우느니 빨리 고치는 게 낫지."),
(None, "Les téléphones sonnent. Chloé raccroche, Julien note, Hélène relit l'arrêté. À midi dix, la porte s'ouvre : Lucien entre, essoufflé.", "전화가 울린다. 클로에는 끊고, 쥘리앵은 적고, 엘렌은 공문을 다시 읽는다. 12시 10분, 문이 열리고 뤼시앵이 숨을 헐떡이며 들어온다."),
(L, "Hélène ! Je viens de lire la porte. C'est quoi, cette histoire ?", "엘렌! 방금 문에 붙은 걸 읽었다. 이게 무슨 일이냐?"),
(H, "Papa. Assieds-toi. Je vais t'expliquer.", "아빠. 앉으세요. 설명할게요."),
(L, "Je veux pas m'asseoir. Je veux comprendre. Un arrêté préfectoral ?", "앉기 싫다. 이해하고 싶어. 도청 명령이라고?"),
(H, "Fermeture de quinze jours, à cause des problèmes de l'inspection.", "검사에서 나온 문제 때문에 15일 폐쇄예요."),
(L, "Trente-cinq ans que je suis dans cette maison. Jamais, tu entends ? Jamais !", "이 집에 35년이야. 한 번도, 듣고 있니? 한 번도 없었어!"),
(H, "Papa, je sais. Crie pas, s'il te plaît.", "아빠, 알아요. 소리 지르지 마세요, 제발."),
(L, "Je crie pas. Enfin, si, un peu. Sous ta mère, ça serait pas arrivé.", "안 질러. 아니, 좀 지르는 거지. 네 엄마 때라면 이런 일 없었어."),
(H, "Voilà. On y est. Sous Maman, tout était parfait, c'est ça ?", "그래요, 또 그 얘기네요. 엄마 때는 다 완벽했다는 거죠?"),
(J, "Lucien, Hélène, s'il vous plaît. Pas devant Chloé.", "뤼시앵, 엘렌, 제발요. 클로에 앞에서는 그만하세요."),
(L, "Tu as raison, Julien. Pardon, ma fille. Je suis pas en colère contre toi.", "네 말이 맞다, 쥘리앵. 미안하다, 얘야. 너한테 화난 게 아니야."),
(H, "Contre qui, alors ? Contre les rats ? Contre le préfet ?", "그럼 누구한테요? 쥐한테요? 경찰청장한테요?"),
(L, "Contre moi, peut-être. Quand j'ai tenu cette maison, je regardais tout.", "어쩌면 나한테겠지. 내가 이 집을 지킬 땐 모든 걸 살폈거든."),
(H, "Papa, c'est moi qui suis responsable. C'est ma cuisine, mon stock.", "아빠, 책임은 저한테 있어요. 제 주방, 제 창고예요."),
(J, "On est tous responsables. On travaille tous ici.", "우리 모두 책임이 있어. 여기서 다 같이 일하잖아."),
(C, "Moi, c'est moi qui ferme le stock sec le soir. Désolée, Hélène.", "저녁에 건식 창고 잠그는 건 저예요. 죄송해요, 엘렌."),
(H, "Non, Chloé. Ça n'a rien à voir avec toi. Les traces étaient anciennes.", "아니야, 클로에. 너랑 상관없어. 흔적은 오래된 거였어."),
(L, "Bon. Qu'est-ce qu'il faut faire pour rouvrir ? Dis-moi les conditions.", "자, 다시 열려면 뭘 해야 하냐? 조건을 말해 봐라."),
(H, "Il y a trois choses. Je te les lis, c'est écrit en bas.", "세 가지예요. 아래에 쓰여 있으니 읽어 드릴게요."),
(H, "« Un : traitement par une entreprise de dératisation agréée. »", "« 하나, 공인 방제업체의 쥐 방제 시공. »"),
(H, "« Deux : un registre de températures, tenu chaque jour. »", "« 둘, 매일 기록하는 온도 관리 대장. »"),
(H, "« Trois : une contre-visite, avec avis favorable de l'inspecteur. »", "« 셋, 재검사와 검사관의 적합 의견. »"),
(J, "Une contre-visite, c'est une deuxième inspection, c'est ça ?", "재검사는 두 번째 검사라는 뜻이지?"),
(H, "Oui. Il revient vérifier qu'on a tout corrigé. Si c'est bon, on rouvre.", "응. 검사관이 다시 와서 다 고쳤는지 확인해. 괜찮으면 다시 열어."),
(C, "Et s'il trouve encore un problème ?", "그때 또 문제를 찾으면요?"),
(H, "Alors on reste fermés. Et on recommence. Voilà pourquoi je veux tout faire bien.", "그럼 계속 닫혀 있고 다시 해야지. 그래서 전부 제대로 하려는 거야."),
(L, "La dératisation, tu connais une entreprise sérieuse ?", "방제업체는 믿을 만한 데를 아니?"),
(H, "J'ai appelé « Net 75 » hier. Ils passent lundi pour le devis.", "어제 « 넷 75 »에 전화했어요. 월요일에 견적 보러 와요."),
(J, "Le devis, c'est combien, à peu près ?", "견적은 대략 얼마야?"),
(H, "Avec le traitement, le registre et les petites réparations, environ deux mille trois cents euros.", "시공이랑 대장, 소소한 수리까지 해서 대략 2천3백 유로."),
(L, "Deux mille trois cents ! Et tu les as, ces deux mille trois cents ?", "2천3백이라고! 그 돈이 있긴 하냐?"),
(H, "Pas vraiment. Mais je les trouverai. Je trouve toujours.", "별로요. 하지만 마련할 거예요. 항상 마련했잖아요."),
(L, "Je peux t'avancer la somme. C'est pas un problème.", "내가 먼저 내 줄 수 있다. 문제없어."),
(H, "Merci, Papa. Mais laisse-moi essayer seule d'abord.", "고마워요, 아빠. 그래도 먼저 혼자 해 볼게요."),
(L, "Toujours aussi têtue. Tu tiens ça de ta mère.", "여전히 고집불통이구나. 네 엄마를 닮았어."),
(H, "Et de toi, Papa. Ne l'oublie pas.", "아빠도 닮았어요. 잊지 마세요."),
(J, "Vous deux, vous êtes pareils. Bon, moi je rappelle les clients.", "두 분은 똑같아요. 자, 전 손님들한테 다시 전화할게요."),
(C, "J'ai fini ma liste. Neuf personnes. Elles étaient très gentilles.", "제 명단은 끝났어요. 아홉 명이요. 다들 아주 친절했어요."),
(J, "Gentilles comment ? Dis-moi, ça me remonte le moral.", "어떻게 친절했는데? 말해 줘, 기운이 나게."),
(C, "Une dame m'a dit : « Ce n'est pas grave, je reviendrai à la réouverture. »", "한 부인이 그러셨어요. « 괜찮아요, 재개점하면 다시 올게요. »"),
(J, "Tu vois, Hélène ? Les clients sont avec nous.", "봤지, 엘렌? 손님들은 우리 편이야."),
(H, "Oui. C'est la seule bonne nouvelle de la journée.", "응. 오늘 유일한 좋은 소식이네."),
(L, "Et Mme Vasseur ? Elle devait venir ce midi, non ?", "그럼 바쇠르 부인은? 오늘 점심에 오기로 했잖니?"),
(J, "Elle a réservé la sept pour treize heures. J'ai pas encore osé l'appeler.", "7번 자리 1시에 예약했어요. 아직 전화할 엄두를 못 냈어요."),
(H, "Je l'appelle. C'est à moi de le faire.", "내가 할게. 내가 해야 할 일이야."),
(None, "Hélène sort son téléphone, respire profondément, compose le numéro. On entend une voix âgée et ferme à l'autre bout.", "엘렌이 전화기를 꺼내 깊게 숨을 쉬고 번호를 누른다. 저편에서 나이 든 단호한 목소리가 들린다."),
(H, "Madame Vasseur ? C'est Hélène, du Comptoir. Je dois vous prévenir.", "바쇠르 부인? 콩투아르의 엘렌이에요. 말씀드릴 게 있어요."),
(H, "On est fermés pendant quinze jours. Oui, c'est officiel. Je suis désolée.", "저희가 15일간 문을 닫아요. 네, 공식이에요. 죄송해요."),
(H, "Non, madame, vous n'y êtes pour rien. Non, ne venez pas ce midi.", "아니에요, 부인 잘못이 아니에요. 아니요, 오늘 점심에는 오지 마세요."),
(H, "Je vous promets que votre table sera là en octobre. Merci, madame.", "10월에는 부인 자리가 꼭 있을 거라고 약속드려요. 감사합니다, 부인."),
(J, "Alors ? Qu'est-ce qu'elle a dit ?", "그래서? 뭐라셔?"),
(H, "Elle a dit : « Ils ne vous auront pas, ma petite. » Puis elle a raccroché.", "이러셨어. « 그 사람들이 널 쓰러뜨리지 못할 거야, 아가. » 그리고 끊으셨어."),
(L, "Cette femme a plus de caractère que tout un régiment.", "그 부인은 연대 하나보다 기개가 세구나."),
(C, "Moi, je l'adore. Elle me fait peur, mais je l'adore.", "저는 그분이 좋아요. 무섭지만 좋아요."),
(C, "Et sur Internet ? Les gens vont l'apprendre aussi ?", "인터넷은요? 사람들도 알게 되겠죠?"),
(J, "C'est déjà fait. Quelqu'un a posté une photo de l'affiche. Regarde.", "이미 알려졌어. 누가 공고문 사진을 올렸어. 봐."),
(H, "Ne réponds pas aux commentaires. On fera un message simple, nous.", "댓글엔 답하지 마. 우리가 짧은 안내문을 올리자."),
(J, "« Fermeture exceptionnelle jusqu'au 3 octobre. » Ça te va ?", "« 10월 3일까지 임시 휴업합니다. » 이거 괜찮아?"),
(H, "Ajoute : « Merci de votre compréhension. » Et rien d'autre.", "« 이해해 주셔서 감사합니다. »를 덧붙여. 그 외엔 아무것도 쓰지 마."),
(C, "Et nos salaires, pendant ces quinze jours ? Pardon de demander.", "그럼 이 15일 동안 월급은요? 여쭤봐서 죄송해요."),
(H, "C'est normal de demander. Je vous en parle lundi, avec les chiffres.", "물어보는 게 당연해. 월요일에 숫자랑 같이 얘기할게."),
(J, "Lundi, c'est loin. Mais d'accord, on t'attend.", "월요일은 멀지만 알았어, 기다릴게."),
(J, "Bon. Maintenant, qu'est-ce qu'on fait de tout ce qu'on a en cuisine ?", "자, 그럼 주방에 있는 재료는 어떻게 하지?"),
(H, "Bonne question. Le poisson, la viande, les produits frais. Tout ça va se perdre.", "좋은 질문이야. 생선, 고기, 신선 식품. 전부 상할 텐데."),
(C, "On peut les donner ? À une association, peut-être ?", "기부하면 안 될까요? 어떤 단체에 말이에요."),
(H, "Bonne idée, Chloé. Il y a un restaurant du cœur près de la place de la Bastille.", "좋은 생각이야, 클로에. 바스티유 광장 근처에 무료 급식소가 있어."),
(J, "Je m'en occupe. Je connais le responsable, un gars sympa.", "내가 맡을게. 책임자를 알아, 좋은 사람이야."),
(H, "Merci. On garde seulement ce qui se conserve. Le reste, on le donne.", "고마워. 보존되는 것만 남기고 나머지는 기부하자."),
(L, "Tu fais bien. Jeter de la nourriture, ça m'a toujours fendu le cœur.", "잘하는 거다. 음식을 버리는 건 늘 마음이 아팠어."),
(H, "Je sais, Papa. Maman disait la même chose.", "알아요, 아빠. 엄마도 같은 말을 하셨죠."),
(L, "Elle disait : « Le gaspillage, c'est un péché. » Et elle avait raison.", "엄마는 이랬지. « 낭비는 죄야. » 맞는 말이었어."),
(None, "Un silence. Julien regarde l'affiche à travers la vitre, puis la salle vide, les tables prêtes pour un service qui n'aura pas lieu.", "침묵이 흐른다. 쥘리앵은 유리 너머 공고문을, 이어 텅 빈 홀을 본다. 열리지 못할 영업을 위해 차려진 테이블들."),
(J, "Les tables sont déjà dressées. C'est bête, mais ça me serre la gorge.", "테이블이 벌써 차려져 있네. 바보 같지만 목이 메어."),
(H, "Laisse-les comme ça. Dans quinze jours, on reprend exactement où on s'est arrêtés.", "그대로 둬. 15일 뒤에 멈춘 자리에서 그대로 다시 시작하자."),
(C, "Vous croyez qu'on va y arriver ? Dites la vérité.", "우리가 해낼 수 있을 거라고 생각하세요? 솔직히 말해 주세요."),
(H, "La vérité, Chloé ? Je sais pas. Mais je vais tout faire pour.", "솔직히, 클로에? 모르겠어. 하지만 그러려고 전부 할 거야."),
(L, "Voilà une réponse honnête. Ça me suffit.", "정직한 대답이구나. 나는 그거면 된다."),
(J, "Alors on commence demain ? Pour la dératisation et le registre ?", "그럼 내일부터 시작할까? 방제랑 대장 말이야."),
(H, "Demain, on nettoie tout. Du sol au plafond, chaque recoin du stock sec.", "내일은 전부 청소해. 바닥부터 천장까지, 건식 창고 구석구석."),
(C, "Je serai là à huit heures, avec des gants et des seaux.", "8시에 장갑이랑 양동이 들고 올게요."),
(J, "Moi aussi. Et j'apporte le café, il va nous en falloir beaucoup.", "나도 올게. 커피는 내가 가져올게, 많이 필요할 테니까."),
(L, "Et moi, je viens aussi. Je suis peut-être vieux, mais je sais encore frotter.", "나도 오마. 늙었어도 아직 문지를 줄은 안다."),
(H, "Papa, tu n'as pas besoin de...", "아빠, 그러실 필요는..."),
(L, "Hélène. Je suis venu tous les matins depuis trois ans. Je viendrai demain aussi.", "엘렌. 난 3년 동안 매일 아침 왔다. 내일도 올 거다."),
(H, "D'accord. Merci, Papa. Merci à tous.", "알겠어요. 고마워요, 아빠. 모두에게 고마워요."),
(None, "Hélène prend un feutre blanc, s'approche de l'ardoise. Elle efface « Vendredi 18 » et écrit seulement : « Fermé. On revient le 3 octobre. »", "엘렌이 하얀 펠트펜을 들고 칠판으로 간다. « 18일 금요일 »을 지우고 이렇게만 쓴다. « 휴업 중. 10월 3일에 다시 뵙겠습니다. »"),
]

VOCAB = [
("A2", "Fermé / fermer", "닫힌 / 닫다", "« Fermé. On revient le 3 octobre. » 문에 붙이는 가장 기본 표현. 반대는 ouvert / ouvrir."),
("A2", "Quinze jours", "보름, 15일", "« Quinze jours, du dix-huit septembre au deux octobre. » 프랑스어는 '두 주'를 quinze jours 라고 한다. une quinzaine 도 같은 뜻."),
("A2", "Un client / une cliente", "손님", "« Les clients sont avec nous. » 식당 직원이 가장 먼저 배우는 단어. 단골은 un habitué."),
("A2", "Désolé(e)", "죄송한, 미안한", "« Je suis désolée. » « On est désolés. » 사과의 기본 형용사. 주어의 성·수에 맞춰 e, s 를 붙인다(발음은 같다)."),
("B1", "Un arrêté", "(행정) 명령, 고시", "« Un arrêté préfectoral. » 도지사나 시장이 내리는 행정 명령. 법(loi)보다 작지만 효력은 즉시 생긴다."),
("B1", "Une fermeture administrative", "행정 폐쇄, 영업정지", "« Fermeture de quinze jours. » 위생·안전 위반에 대해 행정 기관이 내리는 강제 휴업. 형사 처벌이 아니라 행정 처분이다."),
("B1", "Un effet immédiat", "즉시 효력", "« Effet immédiat. » 공문에 적히면 통보받는 순간부터 시행된다는 뜻."),
("B1", "Un devis", "견적서", "« Ils passent lundi pour le devis. » 공사나 시공 전 받는 가격 제안. 서명하면 계약이 된다."),
("B1", "Faire appel / un recours", "이의를 제기하다 / 이의 신청", "« On peut faire un recours, mais ça prend des semaines. » faire appel 은 법원 판결, un recours 는 행정 결정에 불복할 때."),
("B1", "Être responsable de", "~에 책임이 있다", "« C'est moi qui suis responsable. » 책임을 지겠다고 나설 때의 표현. 잘못은 faute, 탓하다는 reprocher."),
("B2", "Une dératisation", "쥐 방제", "« Une entreprise de dératisation agréée. » 해충 방제는 la désinsectisation, 둘을 합쳐 « 3D » (dératisation, désinsectisation, désinfection)라고 부르기도 한다."),
("B2", "Un registre de températures", "온도 관리 대장", "« Un registre tenu chaque jour. » 냉장·냉동 온도를 매일 적는 위생 기록. tenir un registre = 대장을 쓰다."),
("B2", "Une contre-visite", "재검사", "« Une contre-visite, avec avis favorable. » 시정 후 확인을 위해 다시 오는 검사. 결과는 favorable / défavorable."),
("B2", "Ça me serre la gorge.", "목이 메어요.", "[구어] 감정이 북받쳐 말이 안 나올 때. ↔ 정중: Je suis très ému."),
("B2", "Ça m'a fendu le cœur.", "가슴이 찢어졌어요.", "« Jeter de la nourriture, ça m'a toujours fendu le cœur. » 깊은 연민이나 슬픔. fendre = 쪼개다."),
("B2", "Mieux vaut A que B", "B하느니 A가 낫다", "« Mieux vaut réparer vite que se battre longtemps. » 두 선택지의 우열을 단정 지을 때. 주어 없이 짧게 쓴다."),
("C1", "Sous + 사람 (시기)", "~가 이끌던 때에", "« Sous ta mère, ça serait pas arrivé. » sous Napoléon, sous Maman 처럼 누군가의 지휘·통치 시기를 가리킨다."),
("C1", "Ils ne vous auront pas.", "그들이 널 꺾지 못할 거다.", "Mme Vasseur 의 격려. avoir quelqu'un = 속이다·이기다(구어). 상대를 응원하는 단호한 말."),
("C1", "Un régiment", "연대, 대군", "« Plus de caractère que tout un régiment. » 사람 수가 많은 것에 빗대 한 사람의 기개를 과장하는 표현."),
("C1", "Putain / Merde", "젠장", "[속어] « Quinze jours. Putain. » 쓸 수 있음: 가까운 직원·가족 사이 / 금지: 손님·상사·외부인 앞. 충격 앞의 짧은 탄식."),
("B1", "Se partager la liste", "명단을 나눠 맡다", "« On se partage la liste, d'accord ? » 대명동사 se partager 는 서로 나누어 갖는다는 뜻. 일을 분담할 때."),
("B1", "Prévenir quelqu'un", "~에게 미리 알리다", "« Je dois vous prévenir. » 나쁜 소식을 먼저 알릴 때. avertir 보다 일상적."),
]

GRAM = [
("A2", "근접 미래·명령형 — Reste, Entre, Assieds-toi", "« Reste ici, Julien. » « Entre, Chloé. » « Assieds-toi. » tu 에 대한 명령형은 -er 동사의 s 를 뺀다(tu restes → reste). 부정 명령은 « Crie pas », 구어에서는 ne 를 뺀다."),
("B1", "공문 낭독 구조 — 명사 중심의 간결문", "« Durée : quinze jours. » « Effet immédiat. » 공문은 동사 없이 명사 구문을 많이 쓴다. 낭독 후에는 곧바로 동사 중심의 구어 « C'est écrit comme ça. » 로 풀어 말한다."),
("B1", "의무·필요 — il faut / devoir", "« Qu'est-ce qu'il faut faire pour rouvrir ? » « Je dois les appeler. » il faut 는 일반적 필요, devoir 는 주어의 의무. 부정 « il ne faut pas » 는 금지."),
("B2", "수동 표현 — être + 과거분사 / 대명동사", "« Elle est sur le comptoir. » « Ça s'appelle une fermeture administrative. » « Ça se conserve. » 대명동사는 수동 의미를 낸다. 구어에서는 être + 과거분사(« c'est écrit comme ça ») 도 흔하다."),
("B2", "조건법 — 가정 속 과거 (ça serait pas arrivé)", "« Sous ta mère, ça serait pas arrivé. » 과거 사실에 반하는 가정은 원래 conditionnel passé(ça ne serait pas arrivé) 지만, 구어는 단순 조건법과 ne 생략으로 말한다. 한탄·비난에 자주 쓰인다."),
("B2", "pas de + 명사 (부정 관사)", "« Pas de service ce midi, pas de service ce soir ? » 부정 뒤의 du, de la, un 은 de 로 바뀐다. 구어의 생략문에서도 같다. « Je n'ai pas de temps. »"),
("C1", "책임 없음 — n'y être pour rien / ne rien avoir à voir", "« Vous n'y êtes pour rien. » « Ça n'a rien à voir avec toi. » 상대의 책임을 덜어 줄 때 쓰는 두 표현. y 는 앞 상황을 받는 대명사. « Je n'y suis pour rien » 는 ‘내 탓이 아니다’."),
]

READ = [
("공문 낭독 — 단호한 끊기", "« Durée : / quinze jours, / du dix-huit septembre / au deux octobre. » 숫자 앞에서 짧게 쉬고, 날짜는 같은 높이로 평평하게 읽는다. 마지막 « Effet immédiat. » 은 가장 낮고 느리게."),
("리에종 — quinze_jours, c'est_écrit", "« quinze jours » /kɛ̃z.ʒuʁ/ 에서 z 를 유지하고, « c'est écrit » 는 /sɛ.te.kʁi/ 로 t 를 이어서 읽는다. « les_affiches » 는 레-자피슈 로 s 를 z 로."),
("비음 — préfet, conditions, immédiat", "« préfet » /pʁe.fɛ/ 는 비음이 없고, « conditions » /kɔ̃.di.sjɔ̃/ 에는 두 번. « Effet immédiat » /e.fɛ.i.me.dja/ 는 모음이 연달아 이어진다. 입 모양을 바꾸지 않는다."),
("r — arrêté, registre, responsable", "« arrêté » /a.ʁe.te/, « registre » /ʁə.ʒistʁ/, « responsable » /ʁɛs.pɔ̃.sabl/. 어두 r 은 혀뿌리 긁는 소리, 어중 r 은 부드럽게 지나간다."),
("억양 — 충격과 항의", "« Quinze jours. Putain. Quinze jours, Hélène. » 는 같은 말을 세 번 반복하며 점점 낮아지는 억양. « Immédiat ? Mais on a quarante couverts ! » 는 끝을 높이고 속도를 올린다."),
("호흡 구간 — 전화 속 말하기", "« Madame Vasseur ? / C'est Hélène, du Comptoir. / Je dois vous prévenir. » 는 질문 끝을 올린 뒤 낮고 천천히 이어서 나쁜 소식 전달의 톤을 만든다."),
]

CULTURE = [
("la fermeture administrative — 위생 위반과 영업정지", "프랑스에서는 위생 위반이 심각하면 도지사(파리는 경찰청장)가 영업을 일정 기간 중단시킬 수 있다. 검사는 DDPP 가 맡고, 시정 후 재검사에서 적합 판정을 받아야 다시 열 수 있다. 공고문을 문에 게시하는 것이 원칙이라 손님 모두가 사정을 알게 된다."),
("restos du cœur — 식재료 기부", "남는 식재료를 비영리 단체에 기부하는 것은 프랑스에서 흔한 관행이며, 대형 마트와 식당은 법으로 음식물 폐기를 줄이도록 권장된다. « Le gaspillage, c'est un péché. » 는 세대를 넘어 전해지는 요리사들의 말이다."),
]

META = dict(part=3, ep=34, part_label="제3부 Au bord du gouffre · 가을", title_fr="Fermeture administrative", title_ko="행정 폐쇄",
 place="Le Comptoir de Marthe, 9월 18일 금요일 오전 10시 50분 ~ 오후 (영업 개시 직전)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · Lucien Marchand (아버지)",
 wine="9월 15일 검사 사흘 뒤 도착한 15일간(9/18~10/2) 행정 폐쇄 명령. 재개점 조건은 방제 시공·온도 대장·재검사, 필요 비용 약 2 300 €.",
 focus="행정 공문 낭독 후 구어 반응, 법률·위생 어휘(arrêté, contre-visite), 의무·필요 표현, 수동·대명동사, 충격 앞의 속어",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제35화 « Les adieux au personnel » : 9월 21일 월요일, 엘렌은 직원들에게 휴직(chômage partiel)을 알린다.")
