# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J = "Hélène", "Lucien", "Julien"
D = [
(None, "Dimanche 27 septembre, 15 h. Le Comptoir est fermé depuis neuf jours. Les chaises sont sur les tables. Hélène, seule au comptoir, compare des factures sous une petite lampe.", "9월 27일 일요일 오후 3시. 콩투아르는 문을 닫은 지 아흐레째다. 의자들이 테이블 위에 올려져 있다. 엘렌은 홀로 카운터에서 작은 램프 아래 청구서들을 맞춰 보고 있다."),
(L, "Tu ne réponds pas au téléphone. Alors, je suis venu.", "전화를 안 받으니까 내가 왔다."),
(H, "Papa ? On est dimanche. Il y a un panneau sur la porte, tu l'as vu ?", "아빠? 일요일이잖아요. 문에 안내문 붙은 거 봤어요?"),
(L, "J'ai les yeux fatigués, pas aveugles. Et j'ai toujours ma clé.", "눈이 피곤한 거지 먼 건 아니다. 그리고 내 열쇠도 아직 있고."),
(H, "Je sais bien. Qu'est-ce qui se passe ?", "알아요. 무슨 일이에요?"),
(L, "Il se passe que ma fille ne dort plus. C'est Julien qui me l'a dit.", "내 딸이 잠을 못 잔다는 일이지. 쥘리앵이 말해 줬다."),
(H, "Julien parle trop.", "쥘리앵은 말이 너무 많아."),
(L, "Julien s'inquiète, c'est différent. Assieds-toi : j'ai convoqué un conseil de famille.", "쥘리앵은 걱정하는 거고, 그건 다르지. 앉아라. 가족회의를 소집했다."),
(H, "Un conseil de famille ? On est deux, Papa.", "가족회의요? 우리 둘뿐이잖아요, 아빠."),
(L, "On sera trois dans un quart d'heure. Julien nous rejoint.", "십오 분 있으면 셋이 된다. 쥘리앵이 합류해."),
(H, "Tu l'as fait venir un dimanche ? Il est au chômage partiel, il a le droit de se reposer.", "일요일에 불러냈어요? 그 애도 휴직 중이라 쉴 권리가 있어요."),
(L, "Il a dit oui avant la fin de ma phrase. Voilà un homme loyal.", "내 말이 끝나기도 전에 좋다고 하더라. 의리 있는 사내지."),
(H, "Bon. Je te préviens : pas de café. Plus de livraison, plus rien.", "알았어요. 미리 말해 두는데 커피는 없어요. 납품도 끊겼고 아무것도 없어요."),
(L, "J'ai pensé à tout. Regarde, un thermos.", "다 생각해 뒀지. 봐라, 보온병."),
(H, "Tu es venu avec un thermos et un dossier. Ça sent la mauvaise nouvelle.", "보온병에 서류철까지 들고 왔네요. 나쁜 소식 냄새가 나는데요."),
(L, "Au contraire. Ouvre-le. Non, pas encore, laisse-moi parler.", "반대로 좋은 소식이다. 열어 봐라. 아니, 아직 말고, 내가 먼저 말하마."),
(H, "Je t'écoute, mais je te préviens, je suis crevée.", "듣고 있어요. 근데 미리 말하는데, 나 완전 녹초예요."),
(L, "Je vais être clair. J'ai quarante mille euros de côté.", "분명히 말하마. 나한테 모아 둔 돈이 사만 유로 있다."),
(H, "Quoi ?", "뭐라고요?"),
(L, "Quarante mille. Sur un livret, depuis vingt ans. Un peu à ta mère, un peu à moi.", "사만이다. 이십 년 전부터 통장에 넣어 뒀어. 네 엄마 몫도 좀, 내 몫도 좀."),
(H, "Papa, c'est ta retraite !", "아빠, 그건 아빠 노후 자금이잖아요!"),
(L, "Ma retraite, c'est ma pension, et elle me suffit. Ça, c'est de l'argent qui dort.", "내 노후는 연금으로 충분하다. 이건 잠자는 돈이야."),
(H, "Qui dort pour une bonne raison. Pour que tu ne manques de rien.", "그럴 만한 이유가 있어서 자고 있는 거죠. 아빠가 아쉬운 게 없게 하려고."),
(L, "Je ne manque de rien. Sauf de voir ma fille sourire.", "난 아쉬운 게 없다. 내 딸이 웃는 모습만 빼고."),
(H, "Ne commence pas avec les phrases de théâtre.", "연극 대사 같은 말은 시작하지 마세요."),
(L, "Ce n'est pas du théâtre. C'est un chèque. Enfin, presque.", "연극이 아니다. 수표지. 뭐, 거의."),
(H, "Non.", "싫어요."),
(L, "Tu ne m'as même pas laissé finir.", "끝까지 말도 못 하게 하는구나."),
(H, "Je n'ai pas besoin. Non, c'est non, Papa.", "필요 없어요. 싫다면 싫은 거예요, 아빠."),
(L, "Tu es têtue comme ta mère. Elle aussi, elle disait non avant de comprendre la question.", "네 엄마만큼 고집불통이구나. 그 사람도 질문을 이해하기도 전에 싫다고 했지."),
(H, "Et elle avait raison, souvent.", "그리고 엄마는 대체로 옳았고요."),
(L, "Souvent. Pas toujours. Ouvre ce dossier, s'il te plaît.", "대체로지, 항상은 아니고. 이 서류철을 열어 봐 줘, 제발."),
(None, "Hélène ouvre la chemise. Elle en sort un relevé de livret et un document du notaire.", "엘렌이 서류철을 연다. 통장 내역서와 공증인의 서류 한 장이 나온다."),
(H, "Qu'est-ce que c'est que ça ? « Garantie hypothécaire » ? Papa, c'est quoi, ce papier ?", "이게 뭐예요? « 저당 설정 » ? 아빠, 이 서류 뭐예요?"),
(L, "C'est mon appartement. Je l'ai payé en mille neuf cent quatre-vingt-quatorze, il est à moi.", "내 아파트다. 1994년에 다 갚았고, 내 거야."),
(H, "Tu veux hypothéquer ton appartement ? Mais tu as perdu la tête !", "아파트를 담보로 잡히겠다고요? 제정신이에요?"),
(L, "Madame Garnier a refusé pour trois raisons. La troisième, c'était le manque de garanties.", "가르니에 부인은 이유 세 가지로 거절했지. 세 번째가 담보 부족이었고."),
(H, "Ah, tu as retenu ça aussi.", "아, 그것까지 기억하고 있었네요."),
(L, "Je retiens tout ce qui fait mal. Eh bien, la garantie, c'est moi.", "아픈 건 다 기억한단다. 그러니 담보는 나다."),
(H, "Hors de question. Si ça tournait mal, tu perdrais ton toit.", "말도 안 돼요. 만약 일이 잘못되면 아빠는 집을 잃어요."),
(L, "Et alors ? J'aurais une chambre à l'étage, au-dessus de la cuisine.", "그래서? 부엌 위층에 방 하나 있으면 되지."),
(H, "Ce n'est pas drôle, Papa.", "웃을 일이 아니에요, 아빠."),
(L, "Je ne plaisante qu'à moitié. Ça m'amuserait de vivre au-dessus d'un restaurant, tu sais.", "반만 농담이다. 식당 위에서 사는 것도 재밌을 것 같거든."),
(None, "La porte s'ouvre. Julien entre, un sac de croissants à la main.", "문이 열리고 쥘리앵이 크루아상 봉지를 들고 들어온다."),
(J, "Je ne suis pas en retard ? Bonjour, les Marchand. J'ai apporté de quoi tenir.", "늦은 건 아니죠? 안녕하세요, 마르샹 부녀. 버틸 만한 걸 사 왔어요."),
(H, "Toi, tu es un traître.", "너는 배신자야."),
(J, "Je suis un ami. Ce n'est pas la même chose. Qu'est-ce que j'ai manqué ?", "난 친구지. 그건 달라. 내가 뭘 놓쳤어요?"),
(L, "Je viens de proposer quarante mille euros et mon appartement. Ta patronne a dit non.", "내가 방금 사만 유로랑 내 아파트를 내놨다. 네 사장님이 싫다더라."),
(J, "Ah. Donc on est au deuxième acte.", "아. 그럼 2막이군요."),
(H, "Il n'y a pas de deuxième acte. Il y a un père qui veut se ruiner pour moi.", "2막 같은 건 없어. 나 때문에 파산하려는 아버지가 있을 뿐이야."),
(J, "Hélène, laisse-le au moins aller au bout de son idée.", "엘렌, 적어도 끝까지 아이디어를 말하게는 해 줘."),
(H, "Toi aussi, tu en es ? Vous avez préparé ça ensemble ?", "너도 한패야? 둘이 같이 짠 거야?"),
(J, "Pas du tout. Il m'a seulement dit : « Viens, on va parler d'argent. » J'ai pris des croissants.", "전혀요. 그냥 « 오게, 돈 얘기를 하자 » 라고만 하셨어요. 그래서 크루아상을 샀죠."),
(L, "Voilà : ce garçon a du flair.", "이거 봐라. 이 친구 눈치가 있어."),
(H, "Bon. Julien, tu as le dossier de la banque sous les yeux. Donne-moi ton avis.", "좋아. 쥘리앵, 은행 서류가 눈앞에 있잖아. 네 의견을 말해 봐."),
(J, "Mme Garnier a donné trois raisons. Pas une seule. On est d'accord ?", "가르니에 부인은 이유를 세 가지 댔어요. 하나가 아니라. 맞죠?"),
(H, "Oui. Les pertes des six derniers mois, le loyer qui monte, et le manque de garanties.", "응. 지난 육 개월 적자, 오르는 임대료, 그리고 담보 부족."),
(J, "Alors même avec l'appartement, il en reste deux. Le déficit et le loyer.", "그럼 아파트를 걸어도 둘이 남죠. 적자랑 임대료."),
(L, "On en règle une, c'est déjà ça.", "하나라도 해결하면 그만큼 나은 거지."),
(J, "Sauf que la banque jugera l'ensemble. Elle ne note pas chaque raison séparément.", "하지만 은행은 전체를 보고 판단해요. 이유를 하나씩 따로 점수 매기지 않아요."),
(H, "Merci, Julien. Tu vois, Papa ? Même ton complice est d'accord avec moi.", "고마워, 쥘리앵. 보세요, 아빠? 공범마저 내 말이 맞대잖아요."),
(L, "Je n'ai pas fini. Si j'avais su, j'aurais mis cet argent dans la cuisine il y a deux ans.", "아직 안 끝났다. 알았더라면 이 돈을 이 년 전에 주방에 넣었을 거다."),
(H, "Comment ça, si tu avais su ?", "알았더라면이라니, 무슨 말이에요?"),
(L, "Je veux dire : si j'avais compris que ça allait si mal, j'aurais agi plus tôt.", "내 말은, 이렇게 나빠지는 걸 알았더라면 더 일찍 움직였을 거란 얘기다."),
(H, "Tu n'aurais rien pu faire. C'est moi qui aurais dû tout surveiller.", "아빠가 할 수 있는 건 없었어요. 전부 살폈어야 하는 건 나였죠."),
(J, "Ne commence pas à tout prendre sur toi. Moi aussi, j'aurais dû relire le registre.", "혼자 다 짊어지려 하지 마. 나도 장부를 다시 읽어 봤어야 했어."),
(H, "Quel registre ? Celui des températures ?", "무슨 장부? 온도 기록부 말이야?"),
(J, "Oui. Si j'avais vérifié chaque soir, l'inspecteur n'aurait rien trouvé de ce côté-là.", "응. 내가 매일 저녁 확인했다면, 검사관이 그쪽에서는 아무것도 못 찾았을 거야."),
(H, "Arrête, Julien. Tu n'es pas responsable de la chambre froide.", "그만해, 쥘리앵. 냉장실은 네 책임이 아니야."),
(L, "Personne n'est coupable, voilà ce que j'essaie de dire. On regarde devant.", "아무도 죄인이 아니다. 내가 하려던 말이 그거야. 앞을 보자."),
(H, "Devant, il y a trois choses. Le loyer de cinq mille deux cents, tombé le cinq octobre.", "앞에는 세 가지가 있어요. 10월 5일에 내야 할 5천2백 유로 임대료."),
(J, "Les travaux du contrôle, deux mille trois cents euros, c'est ça ?", "재검사 대비 공사비, 이천삼백 유로, 맞죠?"),
(H, "Voilà. Et il y a tous ceux à qui on doit de l'argent. Bastide, les assurances, les impôts.", "그래. 그리고 우리가 돈을 갚아야 하는 모든 사람들이 있고. 바스티드, 보험, 세금."),
(L, "Commençons par les travaux. Sans eux, pas de réouverture.", "공사부터 시작하자. 그게 없으면 재개점도 없다."),
(H, "Je sais. J'ai trouvé une entreprise de dératisation. Ils veulent un acompte demain.", "알아요. 방제 업체를 찾았어요. 내일 선금을 달래요."),
(J, "Combien ?", "얼마요?"),
(H, "Mille cent. Et le reste à la fin du chantier.", "천백 유로. 나머지는 공사 끝나고요."),
(L, "Tu as mille cent euros ?", "천백 유로가 있니?"),
(H, "Pas sans toucher à ce qu'il me reste pour les salaires.", "직원 급여로 남겨 둔 걸 건드리지 않고는 없어요."),
(L, "Alors prends-les chez moi. Voilà qui est réglé.", "그럼 내 걸 가져가라. 그러면 해결이지."),
(H, "Papa...", "아빠..."),
(L, "Ne dis pas non tout de suite. Réfléchis une seconde. Une seule.", "바로 싫다고 하지 마라. 일 초만 생각해 봐. 딱 일 초."),
(None, "Un silence. Hélène se frotte les yeux. Dehors, une camionnette passe dans la rue Saint-Maur.", "침묵. 엘렌이 눈을 비빈다. 밖에서는 생모르 거리를 트럭 한 대가 지나간다."),
(H, "Bordel, c'est dur de dire non à toi.", "젠장, 아빠한테 싫다고 하는 거 정말 어렵네요."),
(J, "Alors ne dis pas non. Dis « peut-être ».", "그럼 싫다고 하지 마. « 어쩌면 » 이라고 해."),
(H, "Un « peut-être » pour les travaux. Rien d'autre.", "공사비에 한해 « 어쩌면 » 요. 다른 건 안 돼요."),
(L, "C'est un début. Les grandes choses commencent par un « peut-être ».", "시작이구나. 큰일은 « 어쩌면 » 으로 시작하는 법이지."),
(H, "Et l'appartement ? Jamais. Tu peux le graver sur la pierre.", "그럼 아파트는요? 절대 안 돼요. 돌에 새겨 두세요."),
(L, "Pourquoi, au juste ? Dis-moi la vraie raison.", "대체 왜지? 진짜 이유를 말해 봐라."),
(H, "Parce que si on perd, tu perds tout. Et moi, je ne me le pardonnerais pas.", "만약 우리가 지면 아빠가 전부 잃으니까요. 그럼 난 나 자신을 용서 못 해요."),
(L, "Et si on gagne ?", "이기면?"),
(H, "On ne gagne pas, Papa. Pas avec ces chiffres.", "이기지 못해요, 아빠. 이 숫자로는요."),
(J, "Les chiffres, ça se redresse. Les gens reviennent quand la porte rouvre.", "숫자는 회복될 수 있어요. 문이 다시 열리면 사람들은 돌아와요."),
(H, "Ou pas.", "아닐 수도 있고."),
(J, "Ou pas. Mais on le saura seulement en essayant.", "아닐 수도 있죠. 하지만 해 봐야 알 수 있어요."),
(H, "Bon, ça suffit, vous deux. J'aimerais comprendre ce que tu veux vraiment, Papa.", "자, 둘 다 그만해요. 아빠가 진짜 원하는 게 뭔지 알고 싶어요."),
(L, "Je veux que tu te battes sans te noyer. Voilà tout.", "네가 물에 빠지지 않고 싸우길 바란다. 그게 전부야."),
(H, "Et moi, je veux que tu gardes ton toit et ton livret. Voilà tout aussi.", "그리고 난 아빠가 집과 통장을 지키길 바라요. 그게 전부예요."),
(J, "Vous êtes pareils. Vraiment. Vous voulez la même chose, mais chacun de son côté.", "두 분은 똑같아요. 정말로. 같은 걸 원하면서 각자 따로 있네요."),
(L, "Ta mère aurait tranché en deux minutes. Elle aurait pris l'argent et aurait dit merci.", "네 엄마라면 이 분 만에 결정했을 거다. 돈을 받고 고맙다고 했겠지."),
(H, "Justement non. Maman n'aurait jamais mis ton toit en jeu. Tu le sais très bien.", "바로 그 반대예요. 엄마는 아빠의 집을 절대 걸지 않았을 거예요. 아시잖아요."),
(L, "Peut-être. Elle aurait préféré que je garde la mienne, c'est vrai.", "그럴지도. 내 집을 지키라고 했겠지, 그건 맞다."),
(H, "Alors, on est d'accord.", "그럼 합의한 거네요."),
(L, "Sur l'appartement, d'accord. Mais pas sur le reste. Écoute-moi bien.", "아파트에 대해선 동의한다. 하지만 나머지는 아니야. 잘 들어라."),
(H, "J'écoute.", "듣고 있어요."),
(L, "Je te prête les deux mille trois cents euros pour les travaux. Pas un don, un prêt.", "공사비 이천삼백 유로를 빌려주마. 선물이 아니라 대출이다."),
(H, "Un prêt avec un papier signé. Intérêts : zéro. Mais un papier.", "서명한 서류가 있는 대출로요. 이자는 없고요. 하지만 서류는 있어야 해요."),
(L, "Un papier chez le notaire, si tu veux. Je ne suis pas contre.", "공증인에게 가서 작성해도 좋다. 반대 안 한다."),
(J, "Un simple papier suffit. Une reconnaissance de dette, daté et signé par vous deux.", "간단한 서류면 돼요. 차용증을 날짜 쓰고 두 분이 서명하는 거죠."),
(H, "Tu es sûr que tu veux faire ça, Papa ? Tu n'es pas obligé.", "정말 그렇게 하고 싶어요, 아빠? 안 그러셔도 돼요."),
(L, "Obligé, non. Mais si je ne le faisais pas, je ne me le pardonnerais pas non plus.", "의무는 아니지. 하지만 안 하면 나도 나 자신을 용서 못 한다."),
(H, "On se ressemble plus que je ne le croyais.", "우리, 내 생각보다 닮았네요."),
(L, "Je te l'ai toujours dit. Quarante ans que je te le dis.", "늘 말했잖니. 사십 년 동안 말했다."),
(J, "Bon. Deux mille trois cents euros. On rouvre quand, à votre avis ?", "자. 이천삼백 유로예요. 언제 다시 열 수 있을까요?"),
(H, "Si les travaux se font cette semaine, le contrôle aura lieu avant la fin du mois.", "공사를 이번 주에 하면, 재검사는 이달 안에 받을 수 있을 거야."),
(J, "Si tout va bien, on rouvre samedi trois octobre. Je note la date.", "다 잘되면 10월 3일 토요일에 다시 엽니다. 날짜 적어 둘게요."),
(L, "Je viendrai ce matin-là avec une bouteille de Sancerre.", "그날 아침에 상세르 한 병 들고 오마."),
(H, "À neuf heures du matin ? Tu es incorrigible.", "아침 아홉 시에요? 못 말려요, 정말."),
(L, "On ne boit pas, on trinque. Il y a une différence.", "마시는 게 아니라 건배하는 거다. 차이가 있지."),
(J, "Je prends mon croissant. Quelqu'un en veut un ? Hélène ?", "전 크루아상 먹을게요. 드실 분? 엘렌?"),
(H, "Donne. Je n'ai rien mangé depuis hier soir.", "줘. 어제 저녁부터 아무것도 안 먹었어."),
(L, "Tu vois ? Un conseil de famille, ça ne sert pas qu'à parler d'argent.", "봤지? 가족회의가 돈 얘기만 하려는 게 아니다."),
(None, "Lucien verse le café du thermos dans trois verres. Hélène mord dans le croissant et ferme les yeux un instant.", "뤼시앵이 보온병의 커피를 잔 세 개에 따른다. 엘렌이 크루아상을 베어 물고 잠시 눈을 감는다."),
(H, "Merci, Papa. Pour l'offre. Même si je dis non à presque tout.", "고마워요, 아빠. 제안해 줘서. 거의 다 싫다고 했지만요."),
(L, "Presque, c'est déjà beaucoup. À la prochaine réunion, j'aurai de nouveaux arguments.", "거의라는 말도 이미 대단하다. 다음 회의 때는 새 논거를 가져오마."),
]

VOCAB = [
("A2", "Un conseil de famille", "가족회의", "« J'ai convoqué un conseil de famille. » 가족이 모여 중요한 일을 의논하는 모임. 원래는 법적 후견 회의를 가리키지만 일상에서는 약간 익살스러운 말투."),
("A2", "Un livret", "예금 통장", "« Sur un livret, depuis vingt ans. » 프랑스 서민의 대표적 저축 상품(livret A 등). « argent de côté » 는 따로 모아 둔 돈."),
("A2", "Un thermos", "보온병", "« Regarde, un thermos. » 커피나 차를 담는 보온병. 일요일 아침 가족 모임에 어울리는 소품."),
("B1", "Mettre de l'argent de côté", "돈을 모아 두다", "« J'ai quarante mille euros de côté. » de côté 는 따로 둠을 뜻한다. ↔ dépenser(쓰다), dilapider(탕진하다)."),
("B1", "Un acompte", "선금, 계약금", "« Ils veulent un acompte demain. » 공사·예약에서 먼저 치르는 일부 대금. 나머지는 « le solde » 또는 « le reste »."),
("B1", "Une reconnaissance de dette", "차용증", "« Une reconnaissance de dette, datée et signée par vous deux. » 가족 사이 돈거래도 차용증을 쓰면 오해를 막는다. 공증은 선택 사항."),
("B1", "Têtu(e) comme une mule", "노새처럼 고집 센", "« Tu es têtue comme ta mère. » 고집을 놀릴 때. 변형: têtu comme une mule. 칭찬과 비난이 섞인 애정 어린 말."),
("B1", "Être crevé(e)", "녹초가 되다", "« Je suis crevée. » [구어] 아주 피곤하다. ↔ 정중: Je suis épuisée / très fatiguée. 가까운 사이에서만."),
("B1", "Un prêt / un don", "대출 / 증여", "« Pas un don, un prêt. » prêter 는 빌려주다, donner 는 거저 주다. 가족 사이에서는 이 구분이 감정을 지켜 준다."),
("B2", "Hypothéquer", "저당 잡히다, 담보로 걸다", "« Tu veux hypothéquer ton appartement ? » une hypothèque 는 부동산 담보권. 담보가 되면 채무를 못 갚을 때 집을 잃을 수 있다."),
("B2", "Une garantie", "담보, 보증", "« Le manque de garanties. » 은행이 상환을 확신하려고 요구하는 안전장치(부동산·보증인). 개인 보증은 « une caution »."),
("B2", "Le chômage partiel", "일시 휴직(부분 실업 급여)", "« Il est au chômage partiel. » 경영난으로 영업을 쉴 때 국가가 급여 일부를 보전하는 제도. 직원 신분은 유지."),
("B2", "Avoir du flair", "눈치·감이 있다", "« Ce garçon a du flair. » 원래는 개의 후각. 상황을 직감적으로 알아채는 능력을 칭찬한다."),
("B2", "Hors de question", "절대 안 된다", "« Hors de question. » 협상의 여지가 없을 때. ↔ pourquoi pas(안 될 것 없지)."),
("B2", "Aller au bout de son idée", "생각을 끝까지 밀고 가다", "« Laisse-le au moins aller au bout de son idée. » 말 중간을 끊지 말고 끝까지 듣게 해 달라는 청."),
("B2", "Prendre tout sur soi", "혼자 다 짊어지다", "« Ne commence pas à tout prendre sur toi. » 책임감 강한 사람을 말릴 때. 변형: porter le chapeau(대신 책임지다)."),
("B2", "Un registre de températures", "온도 기록부", "« Moi aussi, j'aurais dû relire le registre. » 식품 위생법에 따라 냉장 설비의 온도를 매일 적는 장부."),
("B2", "Trancher", "단호히 결정하다", "« Ta mère aurait tranché en deux minutes. » 망설임 없이 양자택일을 정리하는 것. trancher 는 원래 '자르다'."),
("C1", "Se ruiner pour quelqu'un", "누구 때문에 파산하다", "« Un père qui veut se ruiner pour moi. » 사랑하는 이를 위해 재산을 다 쓰는 상황. 과장과 애정을 함께 담는다."),
("C1", "Ça sent la mauvaise nouvelle.", "나쁜 소식 냄새가 난다", "« Ça sent la mauvaise nouvelle. » sentir 는 '~할 조짐이다'. 변형: ça sent le roussi(일이 틀어질 조짐)."),
("C1", "Une phrase de théâtre", "연극 대사 같은 말", "« Ne commence pas avec les phrases de théâtre. » 지나치게 극적인 말을 비꼴 때. 부녀 사이에서만 가능한 놀림."),
("C1", "Une dératisation", "쥐 방제", "« Une entreprise de dératisation. » rat(쥐) + dé-. 건물 방제는 « la lutte contre les nuisibles » 라고도 한다."),
("C1", "Ça me ferait plaisir / Ça m'amuserait", "~하면 좋겠다/재미있겠다 (조건법)", "« Ça m'amuserait de vivre au-dessus d'un restaurant. » 조건법은 부드러운 가정과 완곡을 만든다."),
("C1", "Les grandes choses commencent par un « peut-être »", "큰일은 « 어쩌면 » 에서 시작한다", "« Les grandes choses commencent par un peut-être. » 격언풍 말. 설득의 첫 문을 연 사람이 하는 말이다."),
]

GRAM = [
("B2", "조건법 과거 — si + 대과거, 조건법 과거", "« Si j'avais su, j'aurais mis cet argent dans la cuisine. » « Si j'avais vérifié chaque soir, l'inspecteur n'aurait rien trouvé. » 과거에 이루어지지 않은 일의 가정과 결과. si 절은 plus-que-parfait, 주절은 conditionnel passé(aurais + 과거분사)."),
("B2", "조건법 과거의 후회 — j'aurais dû + 부정사", "« Moi aussi, j'aurais dû relire le registre. » « C'est moi qui aurais dû tout surveiller. » devoir 의 조건법 과거는 '~했어야 했다'. 후회·자책의 대표형. 상대에게는 « Tu aurais dû m'en parler. » 로 아쉬움을 전할 수 있다."),
("B2", "과거에 대한 추측 — aurait + 과거분사", "« Ta mère aurait tranché en deux minutes. » « Maman n'aurait jamais mis ton toit en jeu. » 이미 세상을 떠난 사람이 만약 있었다면 어떻게 했을지를 말할 때도 조건법 과거. 단정은 하지 않으면서 의견을 전한다."),
("B2", "접속법 — vouloir que, j'aimerais comprendre", "« Je veux que tu te battes sans te noyer. » « Je veux que tu gardes ton toit. » 의지·소망은 que + 접속법(batte, garde). 주어가 같으면 부정사: « J'aimerais comprendre. »"),
("B1", "대립과 양보 — sauf que, même si, mais pas sur", "« Sauf que la banque jugera l'ensemble. » « Sur l'appartement, d'accord. Mais pas sur le reste. » 동의와 반대를 한 문장에 담는 연결어. 협상에서 부분 양보를 정확히 표시한다."),
("B1", "강조 구문 — c'est moi qui / ce garçon", "« C'est moi qui aurais dû tout surveiller. » « C'est Julien qui me l'a dit. » c'est + 강조어 + qui 는 책임·주체를 분명히 한다. 구어에서 자주 쓴다."),
("B2", "인용에 가까운 가정 — et si + 직설법", "« Et si on gagne ? » « Et si la banque avait dit oui ? » et si 는 가능성을 던지는 질문. 현재·미래는 직설법, 과거는 대과거. 반론과 희망을 동시에 담는다."),
]

READ = [
("리에종 — j'ai_eu, j'aurais_agi", "« J'aurais agi plus tôt » /ʒɔ.ʁɛ.a.ʒi.ply.to/ 에서 aurais 와 agi 가 이어진다. « Si j'avais su » 는 /si.ʒa.vɛ.sy/. 조건법 과거는 'j'aurais + 과거분사' 덩어리를 한 호흡으로 읽는다."),
("호흡 구간 — 후회의 문장", "« Si j'avais su, / j'aurais mis cet argent / dans la cuisine / il y a deux ans. » 가정절 뒤에서 짧게 쉬고 결과절을 한 번에 읽는다. 끝은 약간 내려서 쓸쓸함을 낸다."),
("억양 — 거절과 설득", "« Non. » 은 짧고 내린다. « Réfléchis une seconde. Une seule. » 는 « seconde » 에서 올렸다가 « seule » 에서 내려 부탁과 압박을 함께 낸다."),
("비음 — appartement, garantie, prêt", "« appartement » /a.paʁ.tə.mɑ̃/ 은 끝의 비음 /ɑ̃/. « un prêt » 의 /œ̃/ 과 /ɛ/ 를 구분한다. « quarante mille » 는 /ka.ʁɑ̃t.mil/ 에서 앞의 비음이 길다."),
("r — dératisation, hypothéquer, travaux", "« dératisation » /de.ʁa.ti.za.sjɔ̃/, « hypothéquer » /i.pɔ.te.ke/ (h 는 소리 없음), « travaux » /tʁa.vo/. r 은 혀뿌리로 부드럽게. h 는 묵음이므로 « l'hypothèque » 로 엘리종한다."),
("숫자 읽기 — 금액과 연도", "« 40 000 € » quarante mille euros. « 2 300 € » deux mille trois cents euros. « 5 200 € » cinq mille deux cents euros. « 1 994 » 연도는 mille neuf cent quatre-vingt-quatorze 로. 금액은 낭독 전체에서 단어로 통일했다."),
("말투 — 가족 사이의 농담", "« Je ne plaisante qu'à moitié. » 는 웃음기를 섞어 가볍게 시작해 끝을 내린다. « Ce n'est pas drôle, Papa. » 는 낮고 단호하게. 같은 가족회의 안에서 농담과 진심의 톤을 오간다."),
]

CULTURE = [
("가족 간 돈 문제 — le prêt familial", "프랑스에서는 부모와 자녀 사이의 금전 거래도 « reconnaissance de dette » (차용증)를 써 두는 경우가 많다. 증여와 대출을 구분하고 상속 시 분쟁을 막기 위해서다. 정이 깊을수록 서류를 가볍게 여기지 않는 것이 예의라는 감각이 있다."),
("la garantie hypothécaire — 담보와 연대 보증", "프랑스 은행은 소규모 사업자 대출에 개인 부동산 담보(hypothèque)나 보증인(caution)을 요구하곤 한다. 가족이 보증을 서면 사업이 실패할 때 가족의 집까지 위험해진다. 그래서 « ne mets pas ton toit en jeu » 라는 조언이 흔하다."),
]

META = dict(part=3, ep=37, part_label="제3부 Au bord du gouffre · 가을", title_fr="Conseil de famille", title_ko="가족회의",
 place="Le Comptoir de Marthe (휴업 중 · 홀), 9월 27일 일요일 오후 3시 무렵",
 chars="Hélène Marchand (주인 셰프) · Lucien Marchand (아버지) · Julien Benali (홀 매니저)",
 wine="영업정지 중인 일요일 오후, 뤼시앵이 저축 4만 유로와 자기 아파트 담보를 제안하지만 엘렌은 거절하고, 공사비 2,300 €만 차용증을 쓰고 빌리기로 한다.",
 focus="조건법 과거(si + 대과거 / aurais dû), 후회·가정, 접속법(vouloir que), 대립·양보 연결어, 가족 간 금전 어휘",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제38화 « L'offre de rachat » : 10월 6일 화요일, 재개점 사흘 뒤 외식 체인 대표 포르가 카운터에 앉아 가게를 사겠다고 말한다.")
