# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J = "Hélène", "Lucien", "Julien"
D = [
(None, "Mardi 20 octobre, 15 h 20. Le service de midi est fini, la salle est vide, plus un client. Hélène, très pâle, compte les tickets au bar. Julien essuie des verres. La porte s'ouvre : Lucien entre sans son bonjour habituel.", "10월 20일 화요일 오후 3시 20분. 점심 영업이 끝나 홀은 텅 비었고 손님은 한 명도 없다. 몹시 창백한 엘렌이 바에서 주문서를 센다. 쥘리앵은 잔을 닦고 있다. 문이 열리고 뤼시앵이 평소의 인사도 없이 들어선다."),
(L, "Hélène. Julien m'a appelé à dix heures et demie.", "엘렌. 쥘리앵이 10시 반에 나한테 전화했다."),
(H, "(sans lever la tête) Julien parle trop.", "(고개도 들지 않고) 쥘리앵은 말이 너무 많아."),
(J, "Tu t'es assise par terre dans la chambre froide, Hélène. C'est Moussa qui t'a trouvée.", "엘렌, 넌 냉장실 바닥에 주저앉았어. 널 발견한 건 무사야."),
(H, "Je me suis baissée pour ramasser un couteau. C'est tout.", "칼을 줍느라 몸을 숙였던 것뿐이야. 그게 다야."),
(J, "Tu étais blanche comme un linge. Dix minutes, t'as pas pu te relever.", "얼굴이 시트처럼 하얬어. 십 분 동안이나 못 일어났고."),
(H, "J'avais la tête qui tournait, c'est tout. J'ai pas déjeuné. Ça arrive à tout le monde.", "머리가 좀 어지러웠던 것뿐이야. 점심을 안 먹었거든. 누구에게나 있는 일이야."),
(L, "Pas déjeuné, pas dormi, pas dîné hier soir non plus. Je me trompe ?", "점심도 안 먹고, 잠도 못 자고, 어제 저녁도 안 먹었지. 내 말이 틀렸니?"),
(H, "Tu me fais surveiller par Julien, maintenant ? Putain, Julien !", "이제 쥘리앵한테 날 감시시키는 거야? 젠장, 쥘리앵!"),
(J, "Excuse-moi, mais j'ai eu peur. J'allais pas attendre que tu tombes devant les clients.", "미안한데 무서웠어. 손님들 앞에서 쓰러질 때까지 기다릴 순 없잖아."),
(H, "Je ne suis pas tombée ! Arrête d'exagérer !", "쓰러지지 않았어! 과장하지 마!"),
(L, "Ça suffit. Écoute-moi, Hélène. Il faut que tu vendes à Faure.", "그만해라. 내 말 들어, 엘렌. 포르한테 팔아야 한다."),
(H, "Quoi ?", "뭐?"),
(L, "Tu as bien entendu. Tu l'appelles, tu signes, et tu te soignes.", "제대로 들었다. 전화해서 서명하고, 몸을 돌봐."),
(H, "Je me soigne de quoi ? Je suis fatiguée, c'est tout !", "무슨 병을 치료해? 피곤한 것뿐이야!"),
(J, "Lucien, peut-être qu'on pourrait en parler plus calmement —", "뤼시앵, 좀 더 차분히 얘기해 볼 수도 —"),
(L, "Toi, laisse-nous.", "너는 우리끼리 있게 해 줘."),
(H, "Julien, descends à la cave. C'est entre lui et moi.", "쥘리앵, 지하 저장실로 내려가. 이건 아빠랑 나 사이의 일이야."),
(J, "J'aime pas vous laisser seuls quand vous êtes comme ça.", "두 분이 이럴 때 둘만 두는 건 싫은데."),
(H, "Julien ! Dehors ! Maintenant !", "쥘리앵! 나가! 지금 당장!"),
(J, "D'accord, d'accord. Je suis en bas. Si ça devient trop —", "알았어, 알았어. 아래에 있을게. 너무 심해지면 —"),
(L, "Ça ne deviendra pas trop. Va.", "너무 심해지진 않아. 가거라."),
(None, "Julien disparaît dans l'escalier de la cave. Le silence tombe. Hélène pose enfin les tickets.", "쥘리앵이 지하 계단으로 사라진다. 침묵이 내려앉는다. 엘렌이 마침내 주문서를 내려놓는다."),
(L, "Cent quatre-vingt mille euros. Tu paies Delmas, tu paies Bastide, tu respires.", "18만 유로다. 델마에게 내고, 바스티드에게 내고, 숨통이 트이는 거야."),
(H, "Et le nom ? Tu en fais quoi, du nom ? Treize autres brasseries avec le même nom sur la porte ?", "이름은? 이름은 어떡하고? 문 앞에 같은 이름이 붙은 브라스리가 열세 곳이 더 생기는데?"),
(L, "Le nom, ce n'est pas ta mère. Ta mère est morte, Hélène.", "이름이 네 엄마는 아니다. 네 엄마는 죽었어, 엘렌."),
(H, "Ne dis pas ça —", "그런 말 하지 마 —"),
(L, "Elle est morte depuis trois ans, et toi, tu t'obstines à mourir à sa place !", "삼 년 전에 죽었어. 그런데 너는 그 사람 대신 죽겠다고 고집을 부리는구나!"),
(H, "Répète. Répète, si t'as le courage !", "다시 말해 봐. 용기가 있으면 다시 말해 보라고!"),
(L, "Je le répète ! Tu t'obstines à mourir à sa place !", "다시 말하마! 넌 그 사람 대신 죽겠다고 고집 부리고 있어!"),
(H, "T'as pas le droit ! T'as pas le droit de me dire ça, toi, justement toi !", "그럴 권리 없어! 나한테 그런 말 할 권리 없어, 아빠가, 하필 아빠가!"),
(L, "Et pourquoi pas moi ? Je suis ton père !", "왜 하필 내가 안 되는데? 내가 네 아버지다!"),
(H, "Parce que toi, t'étais pas là, putain ! Quand elle était malade, t'étais pas là !", "아빠는 거기 없었으니까, 젠장! 엄마가 아팠을 때 아빠는 없었어!"),
(L, "Pas là ? J'étais ici tous les jours ! Je tenais la maison !", "없었다고? 난 매일 여기 있었다! 가게를 지켰어!"),
(H, "Voilà ! Tu tenais la maison ! Pas sa main !", "바로 그거야! 아빠는 가게를 지켰지, 엄마 손을 잡지 않았어!"),
(L, "Tu ne sais pas de quoi tu parles —", "네가 무슨 소리를 하는지 모르는구나 —"),
(H, "Si, je sais ! J'ai vu ! Un mardi de chimio, tu faisais l'inventaire des vins !", "알아! 내가 봤어! 항암 치료받는 화요일에 아빠는 와인 재고를 세고 있었어!"),
(L, "Il fallait bien payer l'hôpital ! Quelqu'un devait payer l'hôpital !", "병원비를 내야 했잖아! 누군가는 병원비를 내야 했어!"),
(H, "Elle voulait te voir ! Pas un bilan, pas un grand livre de comptes ! Elle voulait te voir !", "엄마는 아빠를 보고 싶어 했어! 결산서도, 장부도 아니고! 아빠를 보고 싶어 했다고!"),
(L, "Elle me voyait tous les soirs !", "매일 저녁 나를 봤다!"),
(H, "Vingt minutes ! Tu rentrais à minuit, elle dormait, tu repartais à sept heures !", "이십 분! 아빠는 자정에 들어왔고 엄마는 자고 있었고, 일곱 시에 또 나갔어!"),
(L, "Et toi, alors ? Toi, tu étais où ?", "그럼 너는? 너는 어디 있었는데?"),
(H, "Moi ? Je travaillais !", "나? 일하고 있었지!"),
(L, "Tu venais le dimanche ! Deux heures ! Les yeux sur ton téléphone !", "넌 일요일에 왔다! 두 시간! 눈은 전화기에 둔 채로!"),
(H, "Je faisais soixante-dix heures par semaine ! J'avais un chef qui me laissait pas respirer !", "난 주 칠십 시간을 일했어! 숨도 못 쉬게 하는 셰프 밑에 있었다고!"),
(L, "Toujours une bonne excuse, hein ?", "늘 그럴듯한 핑계가 있지, 응?"),
(H, "C'est pas une excuse, c'est — merde ! Tu sais très bien ce que c'était !", "핑계가 아니야, 그건 — 젠장! 그게 어땠는지 아빠도 잘 알잖아!"),
(L, "Non. Moi, je sais que le dernier soir, c'est moi qui lui ai tenu la main.", "아니. 나는 마지막 날 밤에 내가 그 사람 손을 잡았다는 것만 안다."),
(H, "...", "..."),
(L, "Tu es arrivée à six heures du matin. Elle était déjà partie.", "너는 새벽 여섯 시에 도착했다. 엄마는 이미 떠난 뒤였어."),
(H, "Parce que j'étais coincée dans un train en grève, Papa ! Tu le sais ! Tu l'as toujours su !", "파업 중인 열차에 갇혀 있었으니까, 아빠! 알잖아! 늘 알고 있었잖아!"),
(L, "Tu aurais dû partir plus tôt.", "더 일찍 출발했어야지."),
(H, "Il aurait fallu que tu m'appelles plus tôt, putain ! Il aurait fallu que tu me dises qu'elle allait mourir !", "아빠가 더 일찍 전화했어야지, 젠장! 엄마가 죽어 간다고 나한테 말했어야지!"),
(L, "Elle ne voulait pas que je t'inquiète !", "네가 걱정할까 봐 엄마가 원하지 않았어!"),
(H, "Et tu l'as écoutée ! Évidemment ! Tu l'écoutais toujours, sauf quand il fallait la regarder !", "그래서 그 말을 들었군! 당연하지! 아빠는 늘 엄마 말을 들었지, 엄마를 쳐다봐야 할 때만 빼고!"),
(L, "Tu es injuste.", "넌 부당하다."),
(H, "Et toi, tu fuis ! Tu fuis depuis trois ans !", "그럼 아빠는 도망치고 있어! 삼 년째 도망치고 있다고!"),
(L, "Moi, je fuis ? Je viens ici tous les matins à huit heures —", "내가 도망친다고? 난 매일 아침 여덟 시에 여기 오는데 —"),
(H, "Pour t'asseoir au bout du comptoir et critiquer ma sauce !", "카운터 끝에 앉아서 내 소스에 트집 잡으려고!"),
(L, "Pour la voir ! Pour voir sa maison ! Tu crois que c'est facile ? Tu crois que ça me plaît ?", "그 사람을 보려고! 그 사람 가게를 보려고! 쉬운 일 같으냐? 내가 좋아서 그러는 줄 아니?"),
(H, "Alors pourquoi tu viens ?", "그럼 왜 오는데?"),
(L, "Parce que je n'ai nulle part où aller, bordel !", "갈 데가 어디에도 없으니까, 빌어먹을!"),
(None, "Un long silence. Dans la cave, on entend un verre se poser. Lucien s'appuie au zinc, la voix soudain cassée.", "긴 침묵. 지하에서 잔 놓는 소리가 들린다. 뤼시앵이 카운터에 기대고, 목소리가 갑자기 갈라진다."),
(L, "Chaque matin, je pousse cette porte. Et chaque matin, ça me tue. Ses murs sont là. Elle, non.", "매일 아침 이 문을 밀어. 그리고 매일 아침 그게 날 죽인다. 벽은 여기 있는데 그 사람은 없어."),
(H, "Papa...", "아빠..."),
(L, "Non. Laisse-moi finir, pour une fois. Je ne veux pas que tu fasses pareil.", "아니. 이번엔 끝까지 말하게 해 다오. 네가 똑같이 되는 건 싫다."),
(L, "Je ne veux pas te voir mourir dans ces murs. J'ai déjà perdu ta mère. Je ne perdrai pas ma fille.", "이 벽 안에서 네가 죽어 가는 걸 보고 싶지 않아. 네 엄마는 이미 잃었다. 딸까지 잃을 순 없다."),
(H, "Je ne vais pas mourir ! Je suis fatiguée !", "죽지 않아요! 피곤한 것뿐이야!"),
(L, "Elle aussi, elle disait ça. « Je suis fatiguée. » Pendant un an, elle a dit ça.", "그 사람도 그렇게 말했다. « 피곤해요. » 일 년 내내 그렇게 말했어."),
(H, "Je ne suis pas maman !", "나는 엄마가 아니야!"),
(L, "Non. Tu es têtue comme elle ET comme moi !", "아니. 넌 그 사람만큼, 나만큼 고집불통이다!"),
(H, "Tu veux que je vende pour que, toi, tu arrêtes d'avoir peur. Admets-le !", "아빠가 무서워하지 않으려고 내가 팔길 바라는 거잖아. 인정해!"),
(L, "Oui ! Oui, j'ai peur ! Et alors ? C'est interdit, d'avoir peur ?", "그래! 그래, 무섭다! 그래서? 무서워하면 안 되냐?"),
(H, "Arrête de me dire quoi faire ! J'ai quarante-deux ans, merde !", "나한테 이래라저래라 하지 마! 나 마흔두 살이야, 젠장!"),
(L, "Et tu te comportes comme une gamine qui refuse d'écouter !", "그런데 넌 말 안 듣는 어린애처럼 굴고 있어!"),
(H, "Une gamine qui tient ce restaurant debout depuis trois ans, toute seule !", "삼 년 동안 혼자서 이 식당을 세워 온 어린애겠지!"),
(L, "Pas toute seule ! J'étais là, tous les matins !", "혼자가 아니지! 난 매일 아침 여기 있었다!"),
(H, "Pour critiquer ! Pas pour éplucher une seule carotte !", "트집 잡으러! 당근 하나 까 준 적 없잖아!"),
(L, "Parce que tu ne me laisses rien faire ! Tu ne laisses jamais personne t'aider !", "네가 아무것도 못 하게 하니까! 넌 누구도 널 돕게 두지 않아!"),
(H, "Bordel, mais c'est pas vrai —", "빌어먹을, 그건 사실이 아니 —"),
(L, "Si ! C'est vrai ! Regarde ta main : elle tremble !", "사실이다! 네 손을 봐라, 떨고 있어!"),
(H, "(cachant sa main) Elle tremble de rage !", "(손을 감추며) 화나서 떠는 거야!"),
(L, "Elle tremble parce que tu es à bout ! Reconnais-le, une fois dans ta vie !", "한계에 와서 떠는 거다! 평생 한 번이라도 인정해라!"),
(H, "À bout ? Je ne suis pas à bout ! C'est toi qui es à bout, Papa !", "한계? 한계 아니거든! 한계인 건 아빠잖아!"),
(L, "Répète ça ! Répète !", "다시 말해 봐라! 다시!"),
(H, "Tu as très bien entendu !", "잘 들었잖아요!"),
(L, "Si ta mère te voyait —", "네 엄마가 널 봤다면 —"),
(H, "Ne mêle pas maman à ça !", "엄마를 끌어들이지 마!"),
(L, "Elle serait furieuse de te voir dans cet état !", "그 사람이 지금 네 모습을 봤다면 화가 났을 거다!"),
(H, "Elle serait furieuse contre toi aussi ! Elle t'aurait dit de lâcher ta caisse et de la regarder, elle !", "엄마는 아빠한테도 화냈을 거야! 계산대에서 손 떼고 자기를 보라고 말했겠지!"),
(L, "Elle ne m'a jamais rien dit de pareil —", "그 사람은 나한테 그런 말을 한 적이 없다 —"),
(H, "Parce que tu ne l'écoutais pas ! Tu ne m'écoutes pas non plus !", "아빠가 듣지 않았으니까! 나한테도 안 듣잖아!"),
(L, "J'ai écouté toute ma vie ! Toute ma vie, j'ai écouté les deux femmes de cette maison !", "평생 들었다! 평생 이 집의 두 여자 말을 들어 왔어!"),
(H, "Et tu n'as rien entendu !", "그런데 아무것도 못 들었지!"),
(L, "...", "..."),
(H, "Tu m'as entendue, là ? Tu m'entends, maintenant ?", "지금은 들려? 지금 내 말이 들리냐고?"),
(L, "Je t'entends très bien. Je ne suis pas sourd. Je suis vieux, c'est différent.", "아주 잘 들린다. 귀먹은 게 아니야. 늙은 거지, 그건 다르다."),
(H, "Alors écoute : je ne vends pas. Pas à Faure. Pas à personne. Pas aujourd'hui.", "그럼 들어요. 난 안 팔아. 포르한테도, 누구한테도. 오늘은 안 팔아."),
(L, "Tu es folle.", "넌 제정신이 아니다."),
(H, "Possible. Mais c'est ma folie, pas la tienne.", "그럴지도. 하지만 그건 내 광기지 아빠 광기가 아니야."),
(L, "Très bien. Alors ne compte pas sur moi pour t'aider à te noyer.", "좋다. 그럼 네가 빠져 죽는 걸 돕는 데 날 기대하지 마라."),
(H, "Je n'ai jamais compté sur toi, Papa. Jamais. C'est ça, le problème.", "아빠한테 기댄 적 한 번도 없어. 한 번도. 그게 문제지."),
(L, "(un temps) ...Tu viens de dire quelque chose que je n'oublierai pas.", "(한참 뒤) ...너는 방금 내가 잊지 못할 말을 했다."),
(H, "Moi non plus, j'oublierai pas ce que tu m'as dit, crois-moi.", "나도 아빠가 한 말 안 잊어요, 믿어요."),
(L, "Bien. Alors c'est tout dit.", "좋다. 그럼 할 말은 다 했구나."),
(H, "Sors.", "나가요."),
(L, "Pardon ?", "뭐라고?"),
(H, "Sors d'ici. Je ne veux plus te voir. Pas ce soir.", "여기서 나가. 보고 싶지 않아. 오늘 밤은."),
(L, "Je suis chez moi ici. C'est moi qui ai ouvert cette porte avec ta mère.", "여기는 내 집이다. 네 엄마와 이 문을 연 건 나야."),
(H, "Alors c'est moi qui sors. Je ne peux plus respirer, là.", "그럼 내가 나갈게. 이제 숨을 못 쉬겠어."),
(L, "Non. Reste. Je pars.", "아니. 있어라. 내가 가마."),
(L, "Mais ne viens pas me dire dans six mois que je ne t'avais pas prévenue.", "그리고 육 개월 뒤에 내가 경고 안 했다고는 하지 마라."),
(H, "Je ne dirai rien. Je ne te dirai plus rien.", "아무 말도 안 할 거예요. 이제 아빠한테 아무 말도 안 해요."),
(None, "Lucien prend son manteau sur le dossier de la chaise, lentement. À la porte, il s'arrête sans se retourner. Puis la porte claque. L'horloge au-dessus du bar tictaque.", "뤼시앵이 의자 등받이에서 천천히 외투를 집는다. 문 앞에서 돌아보지 않은 채 멈춰 선다. 이윽고 문이 쾅 닫힌다. 바 위의 시계가 똑딱거린다."),
(H, "...", "..."),
(J, "(de l'escalier, à mi-voix) Hélène ? J'ai entendu la porte.", "(계단에서 낮은 목소리로) 엘렌? 문 소리가 들렸어."),
(H, "Il est parti.", "아빠 갔어."),
(J, "J'ai tout entendu. Pardon. La cave est juste en dessous.", "다 들었어. 미안해. 저장실이 바로 아래라서."),
(H, "Alors tu sais tout. Bravo.", "그럼 다 알겠네. 잘됐다."),
(J, "Je sais que vous vous aimez comme des fous, et que vous êtes nuls pour le dire.", "두 분이 미친 듯이 서로를 사랑하면서 그 말을 하는 데는 젬병이라는 건 알아."),
(H, "Ne me parle pas de ça. Pas maintenant.", "그 얘기는 하지 마. 지금은 아니야."),
(J, "Je te parle pas. Je pose un verre d'eau, et un bout de pain. Tu bois, et tu manges.", "얘기하는 게 아니야. 물 한 잔이랑 빵 한 조각 놓는 거야. 마시고 먹어."),
(H, "J'ai pas faim.", "배 안 고파."),
(J, "Je sais. Mange quand même.", "알아. 그래도 먹어."),
(None, "Hélène prend le verre à deux mains. Elle ne boit pas. Dehors, la pluie commence à tomber sur la rue Saint-Maur.", "엘렌이 두 손으로 잔을 든다. 마시지는 않는다. 밖에서는 생모르 거리에 비가 내리기 시작한다."),
]

VOCAB = [
("A2", "Sors.", "나가.", "sortir 의 명령형. 짧고 단호한 화난 명령. ↔ 정중: Veuillez sortir. 가족 싸움 외에는 금지."),
("A2", "Laisse-moi finir.", "끝까지 말하게 해 줘.", "말 끊는 상대에게. laisser + 대명사 + 부정사. ↔ 정중: Permettez-moi d'achever."),
("B1", "Ça suffit.", "그만해.", "분노가 쌓였을 때의 경고. 직역 « 충분하다 ». ↔ 정중: Je vous prie de cesser."),
("B1", "Tu es injuste.", "넌 부당해.", "상대의 비난에 대한 반박. injuste ↔ juste."),
("B1", "tenir la maison", "집(가게)을 지키다", "« Tu tenais la maison ! Pas sa main ! » 여기서 maison 은 가게. 말장난처럼 tenir 의 대상이 갈린다."),
("B1", "à bout", "한계에 이른", "« Tu es à bout. » être à bout (de forces) = 기력이 다했다."),
("B2", "s'obstiner à + 부정사", "~하겠다고 고집을 부리다", "« Tu t'obstines à mourir à sa place ! » 부정적 뉘앙스의 고집."),
("B2", "J'ai pas le droit / T'as pas le droit", "그럴 권리 없어", "[구어] ne 생략 + 축약. ↔ 정중: Vous n'avez pas le droit de me dire cela."),
("B2", "se noyer", "물에 빠지다/침몰하다", "« t'aider à te noyer » 비유적으로 파산·몰락."),
("B2", "gamine", "어린애", "[구어] 소녀·어린 여자아이를 일컫는 말. 성인에게 쓰면 도발적이다. 쓸 수 있음: 가족 싸움 / 금지: 손님·직원 앞에서 성인에게."),
("B1", "Tu fuis.", "넌 도망치고 있어.", "fuir = 도망치다. « Tu fuis depuis trois ans ! » depuis + 기간으로 지속된 상태를 비난."),
("B2", "mêler quelqu'un à quelque chose", "~를 ~에 끌어들이다", "« Ne mêle pas maman à ça ! » 명령 부정형. 가족 싸움에서 고인을 방패로 쓰지 말라는 뜻."),
("B1", "compter sur quelqu'un", "~를 믿고 기대다", "« Je n'ai jamais compté sur toi. » ne ... jamais 와 함께 쓰면 서운함이 강해진다."),
("B2", "dans un train en grève", "파업 중인 열차에서", "grève = 파업. 프랑스 일상에서 흔한 사정. en grève = 파업 중."),
("C1", "Il aurait fallu que tu m'appelles plus tôt.", "더 일찍 전화했어야지.", "조건법 과거 + 접속법. il aurait fallu que + 접속법 현재(appelles)로 후회·비난을 말한다. 일상 구어에서도 흔하다."),
("B2", "Tu aurais dû partir plus tôt.", "더 일찍 출발했어야지.", "devoir 조건법 과거 = 했어야 했다. 비난 어조."),
("B2", "Si ta mère te voyait —", "네 엄마가 널 봤다면 —", "si + 반과거 / 조건법 현재. 말을 끊어 흐리는 방식(—)이 감정적이다."),
("C1", "mourir à la place de quelqu'un", "~대신 죽다", "« Tu t'obstines à mourir à sa place. » 상대를 도발하는 가장 날 선 문장."),
("B1", "Putain.", "젠장.", "[속어] 분노·절망. 쓸 수 있음: 가까운 가족·주방 동료 사이의 격한 순간 / 금지: 손님·상사·외부인 앞."),
("A2", "Merde.", "젠장.", "[속어] 좌절·분노. 쓸 수 있음: 가족·가까운 동료 사이 / 금지: 손님·상사·외부인 앞."),
("B2", "Bordel.", "빌어먹을.", "[속어] 짜증·분노. 쓸 수 있음: 가족·주방 안 격한 순간 / 금지: 손님·외부인 앞, 공식 자리."),
("C1", "T'as pas le courage ?", "용기 없어?", "[구어] 도발. ↔ 정중: Vous n'en avez pas le courage ? 가족 싸움에서 상대를 밀어붙일 때."),
("C1", "Je hurle !", "소리 지르는 거야!", "hurler = 고함치다. « Je ne ris pas, je hurle. » 반박하는 구어 구조(ne A pas, B)."),
("C1", "comme des fous", "미친 듯이", "[구어] « vous vous aimez comme des fous » 강한 정도를 나타낸다. ↔ 정중: passionnément."),
]

GRAM = [
("C1", "il aurait fallu que + 접속법 — 후회와 비난", "« Il aurait fallu que tu m'appelles plus tôt. » 과거 일에 대한 비난은 il aurait fallu que + 접속법 현재. 같은 뜻으로 « Tu aurais dû m'appeler. » 도 쓴다."),
("C1", "조건법 과거 — 하지 못한 일", "« Elle t'aurait dit de lâcher ta caisse. » « Tu aurais dû partir plus tôt. » 조건법 과거 = avoir 조건법 + 과거분사. 사실이 아니었던 일의 가정."),
("B2", "접속법 — je ne veux pas que ...", "« Je ne veux pas que tu fasses pareil. » « Elle ne voulait pas que je t'inquiète. » vouloir que 뒤에는 접속법. fasses, inquiète."),
("B2", "말 끊기와 말줄임 (dash, ...)", "« Tu ne sais pas de quoi tu parles — » « Si ta mère te voyait — » 말이 끊기는 지점(—)에서 상대가 끼어든다. 낭독할 때는 숨을 멈추고 즉시 다음 화자가 들어간다."),
("B1", "ne 생략과 축약 — 격한 구어", "« T'as pas le droit ! » « J'ai pas faim. » « C'est pas une excuse. » ne 를 지우고 tu → t' 로 줄인다. ↔ 정중: Vous n'avez pas le droit."),
("B2", "강조: toi, moi 의 대조", "« Toi, t'étais pas là ! » « Et toi, tu fuis ! » 주어를 강세형 대명사로 앞에 내세워 비난·대조한다."),
("B2", "수동·피동적 표현 — 불가항력", "« J'étais coincée dans un train en grève. » être coincé = 꼼짝 못 하다. 수동 의미의 상태 표현으로 변명·사정을 설명한다."),
]

READ = [
("고함과 속삭임의 대비", "« Ça suffit ! » 는 s 를 강하게, 끝을 짧게 끊는다. 반대로 « J'ai déjà perdu ta mère. Je ne perdrai pas ma fille. » 는 속삭이듯 낮추고 두 문장 사이에 한 박자 쉰다. 같은 장면에서도 음량으로 감정을 전한다."),
("말 끊기 — 대시(—) 읽기", "« Tu ne sais pas de quoi tu parles — / Si, je sais ! » 처럼 — 에서는 앞 화자가 말을 끝까지 내지 않고 급히 멈춘다. 뒤 화자는 숨을 쉬지 않고 바로 들어간다. 두 사람의 읽기를 겹치듯 이어 붙인다."),
("속어 억양 — putain, bordel, merde", "« Putain ! » 의 pu 는 짧고 강하게, 마지막 in 은 코로 울리며 끊는다. « Bordel » 은 bor / del 로 두 박자. « Merde » 의 r 은 목 안쪽에서 낸다. 속어도 정확하게 발음해야 장면의 힘이 산다."),
("리에종 — il_aurait_fallu, c'est_ça", "« Il aurait fallu que tu m'appelles. » 는 il_aurait / fallu 로 이어 읽는다. « C'est ça, le problème. » 은 c'es_ta, le problème. 감정이 격해져도 리에종은 흐트러지지 않게."),
("비음 — sans, quand, tant", "« Quand elle était malade » 의 quand 은 [kɑ̃], malade 의 l 도 분명히. « J'ai tout entendu. Pardon. » 에서 pardon 의 on 은 코로 울려 낮은 소리로 끝낸다."),
("긴 침묵 — 말줄임표 읽기", "« ... » 한 줄은 한 박자 이상 비운다. 소리 내지 않고 숨을 들이쉬는 소리만 넣는다. « Papa... » 는 모음 a 를 늘리지 않고 속으로 삼킨다."),
("호흡 구간 — 감정이 실린 긴 문장", "« Chaque matin, / je pousse cette porte. / Et chaque matin, / ça me tue. » 쉼표마다 반 박자씩 쉬고 마지막 tue 에서 소리를 끊는다. 눈물을 참는 호흡이다."),
]

CULTURE = [
("프랑스 가족 싸움과 tutoiement", "프랑스에서는 가족끼리 싸울 때도 서로 tu 를 쓰며 강한 말도 거리낌 없이 쏟아낸다. 그러나 서로를 부르는 호칭(« Papa »)이 남는 한 관계는 이어진다. 싸운 뒤 침묵하는 시간이 화해의 전제가 되곤 한다."),
("가족 식당의 세대 갈등", "프랑스의 가족 경영 비스트로는 창업자가 은퇴한 뒤에도 매일 들러 자리를 지키는 경우가 많다. 돈과 감정이 한 공간에 얽혀 있어 인수 제안 같은 사건이 오래된 상처를 건드리기 쉽다."),
]

META = dict(part=3, ep=42, part_label="제3부 Au bord du gouffre · 가을", title_fr="La grande dispute", title_ko="대(大)다툼",
 place="Le Comptoir de Marthe, 10월 20일 화요일 오후 3시 20분 (점심 영업 끝난 빈 홀)",
 chars="Hélène Marchand (주인 셰프) · Lucien Marchand (아버지) · Julien Benali (홀 매니저)",
 wine="냉장실에서 휘청인 엘렌에게 뤼시앵이 « 팔아라 » 하고 몰아붙이면서, 마르트의 투병 때 쌓인 묵은 감정이 터진다.",
 focus="비난·화해의 구어, 조건법 과거와 il aurait fallu que + 접속법, 말 끊기, 속어 분석",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제43화 « Le carnet de Marthe » : 10월 22일 목요일, 뤼시앵이 낡은 공구함에서 무언가를 들고 나타난다.")
