# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, C = "Hélène", "Lucien", "Julien", "Chloé"
D = [
(None, "Mardi 3 novembre, 9 h. Le restaurant n'est pas encore ouvert. Hélène a demandé à tout le monde d'être là. Sur le comptoir : son téléphone, le carnet de Marthe et une tasse de café refroidie.", "11월 3일 화요일 오전 9시. 식당은 아직 열리지 않았다. 엘렌이 모두에게 와 달라고 했다. 카운터 위에는 그녀의 휴대폰, 마르트의 노트, 식어 버린 커피잔이 놓여 있다."),
(J, "On est tous là, Hélène. Lucien, Chloé, moi. Moussa lave déjà les casseroles.", "다 모였어, 엘렌. 뤼시앵, 클로에, 나. 무사는 벌써 냄비를 닦고 있고."),
(H, "Merci d'être venus tôt. Asseyez-vous, s'il vous plaît.", "일찍 와 줘서 고마워. 앉아 줘."),
(C, "Tu as l'air très sérieuse. Il y a une mauvaise nouvelle ?", "아주 심각해 보여요. 나쁜 소식이에요?"),
(H, "Non. Pas une mauvaise nouvelle. Une décision.", "아니. 나쁜 소식이 아니야. 결정이야."),
(L, "Tu as dormi, au moins ?", "잠은 좀 잤니?"),
(H, "Quatre heures. Mais c'est la première fois depuis un mois que je dors sans peur.", "네 시간. 하지만 한 달 만에 처음으로 겁 없이 잤어."),
(J, "Alors c'est bon signe. Qu'est-ce que tu vas faire ?", "그럼 좋은 징조네. 어떻게 할 거야?"),
(H, "Je vais d'abord téléphoner à M. Faure. Je veux que vous écoutiez.", "먼저 포르 씨에게 전화할 거야. 너희가 들었으면 해."),
(C, "Nous écouter ? Mais c'est une conversation privée, non ?", "저희가 듣는다고요? 사적인 통화 아닌가요?"),
(H, "Plus rien n'est privé ici. J'ai trop gardé les choses pour moi.", "여기엔 이제 사적인 게 없어. 나는 너무 많은 걸 혼자 삼켰어."),
(L, "Prends ton temps, ma grande. Nous, on ne bouge pas.", "천천히 해라, 우리 딸. 우리는 꼼짝 않고 있으마."),
(None, "Hélène prend son téléphone, respire une fois, appuie sur un numéro. Le silence est total dans la salle.", "엘렌이 휴대폰을 들고 숨을 한 번 쉰 뒤 번호를 누른다. 홀에 정적이 흐른다."),
(H, "Monsieur Faure ? Bonjour, Hélène Marchand, du Comptoir de Marthe.", "포르 씨? 안녕하세요, 르 콩투아르 드 마르트의 엘렌 마르샹입니다."),
(J, "(à voix basse) Elle l'appelle vraiment. Je n'ose pas respirer.", "(작게) 진짜 전화하네. 숨도 못 쉬겠어."),
(L, "(à voix basse) Chut, Julien.", "(작게) 쉿, 쥘리앵."),
(H, "Oui, j'ai bien reçu votre offre. Cent quatre-vingt mille euros, le nom gardé.", "네, 제안은 잘 받았습니다. 18만 유로에 이름도 유지한다고요."),
(H, "Je vous remercie. C'est une proposition honorable, je ne dis pas le contraire.", "감사합니다. 존중할 만한 제안이라는 건 부정하지 않아요."),
(C, "(à voix basse) Honorable ? Elle va dire oui ?", "(작게) 존중할 만하다고? 승낙하려는 걸까?"),
(J, "(à voix basse) Attends la suite.", "(작게) 다음 말을 기다려."),
(H, "Mais ma réponse est non. Je ne vendrai pas.", "하지만 제 대답은 아니오입니다. 팔지 않겠습니다."),
(H, "Non, ce n'est pas une question d'argent. Je comprends vos arguments.", "아니요, 돈 문제가 아닙니다. 말씀하신 논리는 이해해요."),
(H, "Mais je ne veux pas être « chef consultant » dans la cuisine de ma mère.", "하지만 어머니의 주방에서 '컨설턴트 셰프'가 되고 싶지는 않습니다."),
(H, "Je suis cheffe. Je décide du menu, du beurre, de la température de la crème.", "저는 셰프예요. 메뉴, 버터, 크림 온도는 제가 정합니다."),
(H, "Oui, je sais, la procédure est risquée. Je la tenterai quand même.", "네, 절차가 위험하다는 건 압니다. 그래도 해 보겠습니다."),
(H, "Non, ne me proposez pas plus. Ma décision est prise, monsieur Faure.", "아니요, 더 올리지 마세요. 결정은 끝났습니다, 포르 씨."),
(H, "Je vous souhaite beaucoup de réussite. Au revoir, monsieur.", "큰 성공을 빕니다. 안녕히 계세요."),
(None, "Elle raccroche. Un silence de trois secondes. Puis Chloé laisse échapper un petit cri de joie qu'elle étouffe aussitôt avec les deux mains.", "엘렌이 전화를 끊는다. 3초의 침묵. 이어 클로에가 작은 환호성을 내뱉고는 두 손으로 얼른 입을 막는다."),
(C, "Pardon ! Pardon, c'est sorti tout seul.", "죄송해요! 저도 모르게 나왔어요."),
(J, "Ben alors, Hélène, tu as dit non à cent quatre-vingt mille euros !", "와, 엘렌. 18만 유로를 거절했네!"),
(H, "J'ai dit non à cent quatre-vingt mille euros. Oui, j'en ai la nausée.", "18만 유로를 거절했어. 응, 속이 울렁거려."),
(L, "Un tiens vaut mieux que deux tu l'auras, dit-on.", "한 손의 새가 숲 속 두 마리보다 낫다고들 하지."),
(H, "Je sais, Papa. Mais mon « tiens » à moi, c'est ça.", "알아, 아빠. 하지만 내 '한 손의 새'는 바로 이거야."),
(None, "Elle pose la main sur le carnet. Lucien baisse les yeux, ému.", "엘렌이 노트 위에 손을 얹는다. 뤼시앵이 감정이 북받쳐 눈을 내린다."),
(H, "Maman l'a écrit noir sur blanc : « Ne vendez pas au premier qui sourit. »", "엄마가 분명히 썼잖아. « 처음 웃어 주는 사람에게 팔지 마세요. »"),
(J, "M. Faure sourit beaucoup, il est vrai.", "포르 씨가 많이 웃긴 하죠."),
(H, "Il sourit très bien. Mais ce n'est pas lui qui a épluché les carottes avec Maman.", "아주 잘 웃죠. 하지만 엄마와 같이 당근 껍질을 벗긴 사람은 아니니까."),
(L, "Tu as raison. Un groupe ne sait pas faire la blanquette de ta mère.", "맞다. 그룹이 네 엄마의 블랑케트를 만들 줄은 모르지."),
(C, "Hélène, et maintenant ? On fait quoi pour les dettes, pour l'argent ?", "엘렌, 이제 어떻게 해요? 빚, 돈은요?"),
(H, "Maintenant, j'appelle Maître Aubry. Et c'est à elle de jouer.", "이제 오브리 변호사에게 전화해. 그다음은 변호사님 차례야."),
(H, "Je lui dis de déposer la demande de sauvegarde demain matin.", "내일 아침 보호 절차 신청을 제출하라고 말할 거야."),
(J, "La sauvegarde ? Explique-nous. On n'a pas tout compris.", "보호 절차? 설명해 줘. 우리는 다 이해 못 했어."),
(H, "Une seconde. Je téléphone, et je vous explique après.", "잠깐만. 전화부터 하고 설명할게."),
(None, "Elle compose le numéro du cabinet. Cette fois, elle parle plus fort, avec une voix posée.", "엘렌이 사무실 번호를 누른다. 이번에는 차분한 목소리로 더 또렷하게 말한다."),
(H, "Maître Aubry ? Hélène Marchand. Ma réponse est oui.", "오브리 변호사님? 엘렌 마르샹입니다. 제 답은 예스예요."),
(H, "Oui, la sauvegarde. Vous pouvez déposer la requête demain, mercredi quatre.", "네, 보호 절차요. 내일 수요일 4일에 신청서를 내셔도 됩니다."),
(H, "J'ai tous les documents. Le Kbis est arrivé hier soir, le prévisionnel est fini.", "서류는 다 있어요. Kbis는 어제 저녁에 도착했고 예측 자료도 끝냈습니다."),
(H, "Oui. Et j'ai dit non à Faure, il y a cinq minutes. Il n'y a plus de retour en arrière.", "네. 그리고 오 분 전에 포르 씨에게 거절했어요. 이제 되돌릴 수 없습니다."),
(H, "L'audience, jeudi douze. Je serai là, avec mon père. Merci, maître.", "심리는 12일 목요일이죠. 아버지와 함께 가겠습니다. 감사합니다, 변호사님."),
(None, "Elle raccroche. Cette fois, personne n'ose crier. Julien se lève et applaudit doucement.", "엘렌이 전화를 끊는다. 이번에는 아무도 소리를 지르지 못한다. 쥘리앵이 일어나 조용히 박수를 친다."),
(J, "Bravo, patronne. Franchement, bravo.", "잘했어요, 사장님. 정말로 잘했어요."),
(H, "Ne m'applaudis pas, Julien. J'ai peur, moi aussi.", "박수치지 마, 쥘리앵. 나도 무서워."),
(J, "Justement. Le courage, c'est d'avoir peur et d'y aller quand même.", "그러니까요. 용기란 무서워도 그냥 가 보는 거죠."),
(H, "Écoutez-moi tous. Je vais vous expliquer ce que je viens de décider.", "모두 들어 줘. 방금 내가 결정한 것을 설명할게."),
(H, "La sauvegarde, c'est une procédure qui protège le restaurant devant le tribunal.", "보호 절차는 법원 앞에서 식당을 보호해 주는 절차야."),
(H, "Pendant six mois, les anciennes dettes sont gelées. Personne ne peut nous saisir.", "6개월 동안 예전 빚은 동결돼. 아무도 우리를 압류할 수 없어."),
(H, "Un mandataire, nommé par le tribunal, vérifie nos comptes avec nous.", "법원이 임명한 마당테르가 우리와 함께 장부를 확인해."),
(H, "Et à la fin, on propose un plan : on rembourse tout, sur plusieurs années.", "그리고 끝에는 계획을 제안해. 몇 년에 걸쳐 전부 갚는 거지."),
(C, "Donc on ne ferme pas ? On ne ferme pas le Comptoir ?", "그럼 문 안 닫는 거죠? 콩투아르는 안 닫는 거죠?"),
(H, "On ne ferme pas. Pas si on tient, tous ensemble.", "안 닫아. 우리가 다 같이 버티면."),
(J, "Et nos salaires ? C'est la question que je dois poser, désolé.", "그럼 우리 월급은? 내가 꼭 물어봐야 하는 질문이라 미안해."),
(H, "Les salaires sont payés comme avant, le jour prévu. C'est la loi, et c'est ma règle.", "월급은 예전처럼 정해진 날에 나가. 법이기도 하고 내 원칙이기도 해."),
(J, "D'accord. Et le chômage partiel, ça continue ?", "알겠어. 그럼 일시 휴직은 계속돼?"),
(H, "Plus maintenant. Le restaurant a rouvert le trois octobre, on travaille à plein temps.", "이제는 아니야. 식당이 10월 3일에 재개했으니 전일제로 일해."),
(C, "Alors, concrètement, qu'est-ce que tu attends de nous ?", "그럼 구체적으로 저희에게 뭘 기대하세요?"),
(H, "Trois choses. D'abord, de la vérité : je vous dirai tout, vous me direz tout.", "세 가지야. 첫째, 진실. 나는 전부 말하고 너희도 전부 말해 줘."),
(H, "Ensuite, un point chaque lundi matin, avec les chiffres de la semaine.", "둘째, 월요일 아침마다 한 주의 숫자로 점검 회의를 해."),
(H, "Et enfin, je veux qu'on reste un peu fous. Un restaurant sans folie, c'est une cantine.", "마지막으로, 우리가 조금은 미쳐 있었으면 해. 광기 없는 식당은 구내식당이야."),
(L, "Bien dit. Il faut que la joie reste dans la cuisine.", "잘 말했다. 주방에 즐거움이 남아 있어야지."),
(H, "Justement, Papa. J'ai une chose à te demander.", "그러니 말인데, 아빠. 부탁이 하나 있어."),
(L, "Tout ce que tu veux. Demande.", "원하는 건 뭐든. 말해 봐라."),
(H, "Je ne veux pas ton argent. Ni ton appartement. Je l'ai dit, c'est non.", "아빠 돈은 필요 없어. 아파트도. 이미 말했듯이 안 돼."),
(L, "Hélène, je pourrais pourtant...", "엘렌, 그래도 내가..."),
(H, "Laisse-moi finir. Si j'avais accepté ton argent, je me serais sentie redevable à vie.", "끝까지 들어 줘. 아빠 돈을 받았다면 평생 빚진 기분이었을 거야."),
(H, "Mais je veux autre chose. Je veux que tu reviennes chaque matin, comme avant.", "대신 다른 걸 원해. 예전처럼 매일 아침 와 주면 좋겠어."),
(L, "Comme avant ? Avec mes conseils idiots ?", "예전처럼? 내 쓸데없는 조언과 함께?"),
(H, "Avec tes conseils, tes proverbes, ton café. Et ton nez dans mes sauces.", "조언도, 속담도, 커피도. 그리고 내 소스에 코를 들이미는 것도."),
(L, "Je ne suis pas un homme d'affaires, mais ça, ça me tente.", "나는 사업가는 아니지만 그건 마음에 드는구나."),
(H, "Et mardi soir, la tablée, c'est toi qui l'animes. Avec les douze couverts à vingt-deux euros.", "그리고 화요일 저녁 식탁은 아빠가 맡아. 12명에 22 유로짜리로."),
(L, "Moi ? Je fais le maître de cérémonie ?", "내가? 사회자를 맡는다고?"),
(H, "Tu racontes l'histoire du Comptoir. Les clients adorent ça.", "가게 이야기를 들려줘. 손님들이 좋아해."),
(L, "Alors là, j'ai de quoi faire. Je suis un livre ouvert, ou plutôt, un vieux journal.", "그거라면 얼마든지 있지. 나는 펼쳐진 책, 아니 오래된 신문이다."),
(C, "Hélène, je peux dire quelque chose ?", "엘렌, 한마디 해도 돼요?"),
(H, "Vas-y, Chloé. Tu l'as bien mérité.", "해 봐, 클로에. 그럴 자격 충분해."),
(C, "Le dossier que je t'avais montré, avec les producteurs, la carte courte...", "제가 보여 드렸던 자료요. 생산자 직거래, 짧은 메뉴..."),
(H, "Je l'ai relu trois fois ce week-end. Tu avais raison sur presque tout.", "주말에 세 번 다시 읽었어. 거의 다 네 말이 맞았어."),
(C, "Vraiment ? Tu dis ça pour me faire plaisir ?", "정말요? 기분 좋으라고 하시는 말씀이죠?"),
(H, "Non. Si je t'avais écoutée plus tôt, on aurait gagné un mois.", "아니야. 너 말을 더 일찍 들었다면 한 달은 벌었을 거야."),
(H, "Alors on commence : tu appelles M. Bastide cet après-midi, pour parler des petits producteurs.", "그럼 시작하자. 오늘 오후 바스티드 씨한테 전화해서 소규모 생산자 이야기를 해 줘."),
(C, "Moi ? J'appelle M. Bastide ? D'accord !", "제가요? 제가 바스티드 씨에게 전화해요? 알겠어요!"),
(J, "Et moi, patronne ? Je suis là pour quoi ?", "그럼 저는요, 사장님? 저는 뭘 하죠?"),
(H, "Toi, tu es le seul qui n'a pas posé la question que j'attendais.", "너는 내가 기다리던 질문을 하지 않은 유일한 사람이야."),
(J, "Laquelle ? Armand ?", "어떤 질문? 아르망 말이에요?"),
(H, "Oui. Armand Belloc. Ta réponse était pour la fin octobre, non ?", "응. 아르망 벨로크. 대답 기한이 10월 말이었지?"),
(J, "J'ai dit non à Armand vendredi. Je lui ai écrit un mail très poli.", "금요일에 아르망에게 거절했어요. 아주 정중하게 메일을 썼죠."),
(L, "Un mail poli. Et un salaire de mille euros de plus qui part en fumée.", "정중한 메일이라. 그리고 천 유로 더 받을 월급은 연기처럼 사라졌고."),
(J, "Lucien, j'ai trente-trois ans. L'argent, ça revient. Une équipe comme ça, jamais.", "뤼시앵, 저는 서른세 살이에요. 돈은 다시 와요. 이런 팀은 두 번 다시 없죠."),
(H, "Julien... je ne sais pas quoi dire. Merci. Vraiment merci.", "쥘리앵... 뭐라고 해야 할지 모르겠어. 고마워. 정말 고마워."),
(J, "Dis simplement que mon sourire vaut cent mille euros.", "그냥 내 미소가 10만 유로 값어치라고만 말해 줘."),
(H, "Il vaut au moins cent cinquante mille.", "적어도 15만 유로는 되지."),
(C, "Moi, si j'étais à la place de M. Faure, je serais jalouse de notre équipe.", "제가 포르 씨라면 우리 팀이 부러울 거예요."),
(J, "Si M. Faure nous avait vus tout à l'heure, il aurait compris qu'on ne s'achète pas.", "포르 씨가 아까 우리를 봤다면 우리는 살 수 없다는 걸 알았을 거예요."),
(L, "Si je vous écoute, je vais pleurer encore. Je n'en peux plus de pleurer cette semaine.", "너희 말을 들으면 또 울겠다. 이번 주엔 우는 데 질렸는데."),
(H, "Pleure, Papa. Ça fait du bien. Mais ensuite, au travail.", "울어, 아빠. 기분이 좋아져. 하지만 그다음엔 일해야지."),
(H, "Il est neuf heures quarante. Le service commence dans deux heures vingt.", "9시 40분이야. 영업 시작까지 2시간 20분 남았어."),
(J, "Je mets les tables. Chloé, tu viens m'aider ?", "나는 테이블 세팅할게. 클로에, 와서 도와줄래?"),
(C, "Oui ! Et je note dans mon carnet : « courage, honorable, rembourser ».", "네! 그리고 수첩에 적을게요. « 용기, 존중할 만한, 상환하다. »"),
(H, "Écris aussi « sauvegarde ». Tu vas l'entendre souvent.", "« 보호 절차 »도 써. 앞으로 자주 듣게 될 거야."),
(L, "Hélène, regarde l'ardoise. Elle est encore vide, ce matin.", "엘렌, 칠판을 봐라. 오늘 아침엔 아직 비어 있구나."),
(H, "Je sais. Je l'écris maintenant. Passe-moi la craie, Papa.", "알아. 지금 쓸 거야. 분필 좀 줘, 아빠."),
(L, "Tiens. Qu'est-ce que tu mets ?", "자. 뭐라고 쓸 거니?"),
(H, "Plat du jour : blanquette de Marthe, hors du feu. Et en dessous, une phrase.", "오늘의 요리: 마르트의 블랑케트, 불을 끄고. 그리고 그 아래에 한 문장."),
(J, "Quelle phrase ? On est tous curieux.", "무슨 문장요? 다들 궁금해요."),
(None, "Hélène écrit en lettres rondes, en bas de l'ardoise : « Aujourd'hui, on reste. » Tout le monde sourit. Dans la cuisine, Moussa entend et fait claquer deux casseroles en signe de joie.", "엘렌이 칠판 맨 아래에 둥근 글씨로 « 오늘, 우리는 남는다. »라고 쓴다. 모두가 미소 짓는다. 주방에서 이를 들은 무사가 기쁨의 표시로 냄비 두 개를 부딪친다."),
(L, "Aujourd'hui, on reste. Voilà un joli mot de patronne.", "오늘, 우리는 남는다. 사장다운 멋진 말이구나."),
(H, "C'est tout ce que je sais promettre, Papa. Un jour à la fois.", "내가 약속할 수 있는 건 그게 전부야, 아빠. 하루씩."),
(L, "Un jour à la fois. C'est comme ça qu'on a fait en 1991. Et regarde où on en est.", "하루씩. 1991년에도 그렇게 했지. 지금 어디까지 왔는지 봐라."),
(H, "On est au Comptoir de Marthe. Et on y reste. Allez, tout le monde en cuisine !", "콩투아르 드 마르트에 있지. 그리고 여기 남을 거야. 자, 모두 주방으로!"),
]

VOCAB = [
("A2", "Une décision / décider", "결정 / 결정하다", "« Une décision, pas une mauvaise nouvelle. » « Ma décision est prise. » prendre une décision = 결정을 내리다."),
("A2", "Refuser / dire non", "거절하다", "« J'ai dit non à cent quatre-vingt mille euros. » refuser 보다 dire non 이 구어에서 직접적이고 강하다."),
("A2", "Rester", "남다, 머무르다", "« Aujourd'hui, on reste. » 장소에 계속 있다는 뜻과 '그만두지 않는다'는 의지를 함께 담았다."),
("A2", "Écouter / une voix", "듣다 / 목소리", "« Je veux que vous écoutiez. » « Une voix posée. » voix basse = 작은 소리, voix haute = 큰 소리."),
("B1", "Une proposition honorable", "존중할 만한 제안", "« C'est une proposition honorable. » 수락하지 않더라도 상대를 존중한다는 정중한 거절의 완충어."),
("B1", "Raccrocher", "전화를 끊다", "« Elle raccroche. » 반대는 décrocher(받다). 구어: je te raccroche au nez = 일방적으로 끊다."),
("B1", "Applaudir / Bravo !", "박수치다 / 잘했어!", "« Bravo, patronne. » 격려할 때 간단히. 진지할 때는 félicitations."),
("B1", "Noir sur blanc", "분명하게 글로", "« Elle l'a écrit noir sur blanc. » 검은 글씨, 흰 종이에서 나온 표현. 반박할 수 없는 증거를 뜻한다."),
("B1", "Un point chaque lundi", "월요일마다 점검 회의", "« Un point chaque lundi matin. » faire un point = 상황을 정리·점검하다. 업무 회의에서 자주 쓴다."),
("B1", "Les salaires sont payés", "월급이 지급된다", "수동태. « Les salaires sont payés comme avant. » 급여는 지급일을 지켜 준다는 말로 직원을 안심시킨다."),
("B2", "Avoir la nausée", "구역질 나다, 울렁거리다", "« Oui, j'en ai la nausée. » 큰 결정 뒤의 긴장을 몸으로 표현하는 구어. 비슷: avoir un nœud à l'estomac."),
("B2", "Un tiens vaut mieux que deux tu l'auras.", "손 안의 새가 낫다.", "속담. 확실한 것이 불확실한 약속보다 낫다. Lucien이 Faure의 제안 앞에서 인용하고 Hélène이 '내 tiens 는 이것'이라고 받는다."),
("B2", "Être redevable (à vie)", "(평생) 빚진 기분이다", "« Je me serais sentie redevable à vie. » 돈 이야기가 아니라 마음의 빚. 조건법 과거와 함께 쓴다."),
("B2", "Il faut que + 접속법", "~해야 한다", "« Il faut que la joie reste dans la cuisine. » reste 는 rester 의 접속법. 원칙·바람을 말할 때."),
("B2", "S'acheter / ne pas s'acheter", "(돈으로) 살 수 있다", "« On ne s'achète pas. » 대명동사의 수동적 의미: 우리는 팔리는 존재가 아니다. 자존심을 표현하는 말."),
("B2", "En fumée", "연기처럼 (사라져)", "« Un salaire qui part en fumée. » partir en fumée = 헛되이 사라지다. 같은 계열: tomber à l'eau."),
("B2", "Un livre ouvert", "솔직한 사람", "« Je suis un livre ouvert, ou plutôt un vieux journal. » 숨기는 것이 없는 사람. 말장난으로 비틀어 쓴다."),
("C1", "Laisse-moi finir.", "끝까지 말하게 해 줘.", "[구어] 말이 끊길 때 가볍게 제지. ↔ 정중: Permettez-moi de terminer."),
("C1", "Reculer / un retour en arrière", "되돌아가다 / 뒤로 물러서기", "« Il n'y a plus de retour en arrière. » 결정이 돌이킬 수 없음을 말한다. revenir sur sa décision 도 같은 뜻."),
("C1", "Avoir de quoi faire", "할 이야기가 많다, 거리가 충분하다", "[구어] « J'ai de quoi faire. » ↔ 정중: J'ai suffisamment de matière. 부정적이면 '할 일이 태산'이라는 뜻도."),
("C1", "Un maître de cérémonie", "사회자, 의식 진행자", "« Je fais le maître de cérémonie ? » 행사에서 순서를 이끄는 사람. 약간 익살스럽게."),
("C1", "À plein temps", "전일제로", "« On travaille à plein temps. » ↔ à temps partiel. 일시 휴직(chômage partiel)과 대비되는 표현."),
]

GRAM = [
("B2", "가정문 종합 — si + 직설법 / 반과거 / 대과거", "« Si j'avais accepté ton argent, je me serais sentie redevable. » (불가능한 과거: si + 대과거, 조건법 과거) / « Si j'étais à la place de M. Faure, je serais jalouse. » (현재 가정: si + 반과거, 조건법 현재) / « Si M. Faure nous avait vus, il aurait compris. » 세 가지 가정을 장면의 감정으로 구분해 연습."),
("B2", "의지 표현 — vouloir que + 접속법", "« Je veux que vous écoutiez. » « Je veux que tu reviennes chaque matin. » « Je veux qu'on reste un peu fous. » 의지·희망에는 vouloir que + 접속법. 주어가 같으면 vouloir + 부정사: « Je veux rester. »"),
("B1", "결정 표현 — décider de, ma décision est prise", "« Ma décision est prise. » « Il n'y a plus de retour en arrière. » « J'ai décidé de dire non. » 결정에는 단호한 문장과 짧은 끝맺음. 단호함은 문장을 짧게 끊는 것에서 나온다."),
("B2", "조건법 현재 — 가능성과 완곡", "« Je pourrais pourtant... » « Il vaut au moins cent cinquante mille. » 완곡하게 의견을 말하거나 거절할 때 조건법. je voudrais, je pourrais, ça me plairait."),
("B1", "전화 대화 — 한쪽만 들리는 문장", "« Oui, j'ai bien reçu votre offre. » « Non, ce n'est pas une question d'argent. » 상대 말이 들리지 않아도 oui/non + 이유 순서로 짧게 이어 간다. 정중한 vous 유지."),
("B2", "수동태와 대명동사 수동 — se + 동사", "« Les salaires sont payés comme avant. » « Un groupe ne s'achète pas. » 일반 규칙은 être + 과거분사, 일반적 진리는 대명동사로 표현할 수 있다."),
("B1", "일정 표현 — 요일·날짜·시각", "« Mercredi quatre. » « Jeudi douze. » « Il est neuf heures quarante. » « Le service commence dans deux heures vingt. » dans + 시간 = ~후에. 요일 앞에는 관사 없음."),
]

READ = [
("결의의 억양 — 짧게 끊어 내리기", "« Ma réponse est non. / Je ne vendrai pas. » 두 문장을 각각 내려서 마무리한다. 말끝이 올라가면 망설임이 된다. non 에서 입술을 단단히 다문다."),
("리에종 — un_euro, cent_quatre-vingt_mille", "« cent quatre-vingt mille euros » /sɑ̃.katʁ.vɛ̃.mil ø.ʁo/. mille 와 euros 사이에서 l 을 이어 /mi.lø.ʁo/ 처럼 부드럽게 연결한다. « J'ai dit non à cent... » 은 non 과 à 사이를 끊어 읽는다."),
("호흡 구간 — 약속 세 가지", "« D'abord, / de la vérité. // Ensuite, / un point chaque lundi. // Et enfin, / je veux qu'on reste un peu fous. » 순서어 뒤에 짧게 쉬고 마지막 문장은 속도를 늦춘다."),
("r — remercier, rester, rembourser", "« Je vous remercie » /ʒə vu ʁə.mɛʁ.si/, « rester » /ʁɛs.te/, « rembourser » /ʁɑ̃.buʁ.se/. 어두의 r 은 목 안쪽을 가볍게 긁는 소리. 모음 사이 r 은 짧게."),
("u와 ou — courage, plus, tout", "« courage » /ku.ʁaʒ/ 의 ou 는 /u/, « plus » /ply/ 의 u 는 /y/. « Le courage, c'est d'avoir peur et d'y aller quand même » 를 읽으며 두 소리를 구별한다."),
("속삭임과 큰 목소리", "« (à voix basse) Elle l'appelle vraiment. » 는 소리를 낮추되 발음은 또렷하게. « Plat du jour : blanquette de Marthe » 는 칠판을 읽는 목소리로 크고 느리게. 지문 뒤에 목소리 크기가 달라진다."),
]

CULTURE = [
("프랑스어의 속담 — un tiens vaut mieux que deux tu l'auras", "'지금 가진 것 하나가 나중에 약속된 둘보다 낫다'는 뜻의 속담으로 라 퐁텐 시대부터 쓰인다. tiens(가진 것)와 tu l'auras(너는 그것을 갖게 될 것이다)를 명사처럼 쓰는 말놀이가 재미있다. 연장자가 안전한 길을 권할 때 흔히 인용한다."),
("프랑스의 일상 결정 — dire non poliment", "프랑스어에서 거절은 감사와 존중이 먼저 오고 non 이 나중에 온다. « C'est une proposition honorable, mais... » 처럼 상대의 품위를 지켜 준 다음 « ma réponse est non » 으로 마무리한다. 짧고 분명하게 말하는 것도 예의로 여긴다."),
]

META = dict(part=3, ep=45, part_label="제3부 Au bord du gouffre · 가을", title_fr="La décision d'Hélène", title_ko="엘렌의 결정",
 place="Le Comptoir de Marthe, 11월 3일 화요일 오전 9시 (개점 전, 직원 모임)",
 chars="Hélène Marchand (주인 셰프) · Lucien Marchand (아버지) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버)",
 wine="Faure의 인수 제안 거절, 오브리 변호사에게 보호 절차 신청 지시, 직원·아버지에게 선언.",
 focus="결정·의지 표현, 가정문 종합(si + 대과거), vouloir que + 접속법, 완곡한 거절",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제4부 제46화 « Le tribunal de commerce » : 11월 12일 목요일, 파리 상사법원에서 엘렌의 보호 절차 개시 심리가 열린다.")
