# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, K = "Hélène", "Julien", "Chloé", "Karim"
D = [
(None, "Mardi 16 mars, 9 h 30. Le Comptoir n'ouvre qu'à midi, mais le téléphone sonne déjà. Julien, à la caisse, fait défiler les messages avec un air fatigué.", "3월 16일 화요일 오전 9시 30분. 콩투아르는 정오에야 문을 열지만 전화는 벌써 울린다. 쥘리앵이 계산대에서 지친 얼굴로 메시지를 넘겨 본다."),
(J, "Hélène, regarde ça. Quarante et un messages depuis hier soir. Quarante et un !", "엘렌, 이것 좀 봐. 어젯밤부터 메시지가 마흔한 개야. 마흔한 개!"),
(H, "Des réservations ? Déjà ? On est mardi matin.", "예약이야? 벌써? 아직 화요일 아침인데."),
(J, "Oui. Et le carnet est plein jusqu'au six avril. Complet, midi et soir.", "응. 장부가 4월 6일까지 꽉 찼어. 점심도 저녁도 만석이야."),
(H, "Trois semaines complètes ? Sans un seul trou ?", "3주가 통째로 찼다고? 빈자리가 하나도 없어?"),
(J, "Un seul : jeudi prochain à quatorze heures. Et je parie que ça part avant ce soir.", "하나 있어. 다음 주 목요일 오후 2시. 그것도 오늘 저녁 전에 나갈걸."),
(H, "C'est une bonne nouvelle, non ? Tu as l'air d'avoir perdu un parent.", "좋은 소식 아냐? 넌 가족이라도 잃은 얼굴이네."),
(J, "Non, c'est génial. Mais ça me fait un peu peur, tu vois.", "아니, 근사하지. 근데 좀 무섭기도 해, 알잖아."),
(H, "Peur de quoi ? Les gens viennent, c'est ce qu'on voulait.", "뭐가 무서운데? 손님이 오잖아, 우리가 바라던 거고."),
(J, "Peur qu'on ne tienne pas le rythme. Regarde les chiffres de mars.", "우리가 이 속도를 못 버틸까 봐. 3월 숫자 좀 봐."),
(H, "Trente-et-un mille quatre cents euros au quinze ? Déjà ?", "15일까지 3만 1천 4백 유로라고? 벌써?"),
(J, "Au rythme actuel, on finit mars à soixante-deux mille. C'est un record.", "지금 속도면 3월은 6만 2천으로 끝나. 신기록이야."),
(H, "Un record, oui. Mais je n'ai pas dormi plus de six heures depuis dix jours.", "신기록은 맞지. 근데 열흘째 여섯 시간 넘게 잔 적이 없어."),
(J, "Tu vois ? C'est ça, l'envers du décor. Le succès, ça se paye.", "봤지? 이게 겉으로 안 보이는 뒷면이야. 성공에는 대가가 따라."),
(H, "On en reparle tout à l'heure, avec l'équipe. Où est Karim ?", "이따가 팀이랑 같이 얘기하자. 카림은 어디 있어?"),
(J, "En cuisine depuis sept heures. Il n'a rien dit, il n'a même pas pris son café.", "7시부터 주방에 있어. 아무 말도 안 했고 커피도 안 마셨어."),
(H, "Ça, c'est pas bon signe. D'habitude, il râle avant de commencer.", "그건 안 좋은 신호네. 보통은 시작 전에 투덜대는데."),
(None, "Hélène pousse la porte de la cuisine. Karim est penché sur un plan de travail, un couteau à la main, l'œil vide.", "엘렌이 주방 문을 민다. 카림이 손에 칼을 든 채 멍한 눈으로 조리대 위로 몸을 숙이고 있다."),
(H, "Karim, ça va ? Tu coupes ces échalotes depuis dix minutes.", "카림, 괜찮아? 그 샬롯을 10분째 썰고 있잖아."),
(K, "Ah, Hélène. Pardon. J'ai la tête ailleurs.", "아, 엘렌. 미안. 정신이 딴 데 가 있었어."),
(H, "Tu as dormi cette nuit ? Dis-moi la vérité.", "어젯밤에 잤어? 사실대로 말해 봐."),
(K, "Quatre heures. Je suis rentré à une heure et demie, et j'ai fait les commandes.", "네 시간. 새벽 1시 반에 들어와서 주문서를 썼어."),
(H, "Les commandes, le lundi soir, c'est ton jour de repos, Karim !", "월요일 밤에 주문서라니, 그게 네 쉬는 날이잖아, 카림!"),
(K, "Je sais. Mais comme on a trop de monde, je suis obligé de tout anticiper.", "알아. 근데 손님이 너무 많으니까 전부 미리 챙길 수밖에 없어."),
(H, "Tu vas craquer, à ce rythme-là. Bois un café, assieds-toi cinq minutes.", "이 속도면 너 쓰러져. 커피 마시고 5분만 앉아."),
(K, "Pas le temps. J'ai quatre-vingts couverts à préparer pour midi et le soir.", "시간 없어. 점심이랑 저녁까지 80인분을 준비해야 해."),
(H, "Quatre-vingts ? On en faisait cinquante en décembre.", "80이라고? 12월에는 50인분이었는데."),
(K, "Eh oui. Et Chloé est arrivée à huit heures avec une tête de zombie.", "그러게요. 그리고 클로에는 8시에 좀비 같은 얼굴로 왔어."),
(C, "Bonjour tout le monde. Je suis là, je suis vivante. Presque.", "다들 안녕하세요. 저 왔어요, 살아 있어요. 거의요."),
(H, "Chloé, tu es toute pâle. Qu'est-ce qui t'arrive ?", "클로에, 얼굴이 하얗네. 무슨 일 있어?"),
(C, "J'ai un contrôle de pâtisserie jeudi. J'ai révisé jusqu'à deux heures du matin.", "목요일에 제과 시험이 있어서요. 새벽 2시까지 복습했어요."),
(H, "Et demain, tu travailles ici toute la journée, évidemment.", "그리고 내일은 당연히 하루 종일 여기서 일하지."),
(C, "Oui, mais ce n'est pas un problème. J'ai l'habitude d'être crevée.", "네, 그래도 문제없어요. 피곤한 건 익숙해요."),
(K, "Ne dis pas ça. C'est justement le problème, que tu y sois habituée.", "그렇게 말하지 마. 네가 그게 익숙하다는 게 바로 문제야."),
(C, "Ben quoi ? Il y a plein de clients, c'est bien, non ?", "아니 왜요? 손님이 많은 건 좋은 거잖아요?"),
(H, "C'est bien, oui. Mais tu es à bout, et Karim aussi. Ça se voit.", "좋은 일이지. 근데 너도 카림도 한계야. 눈에 보여."),
(J, "Hélène, les premiers clients arrivent dans une heure. On fait quoi ?", "엘렌, 첫 손님이 한 시간 뒤에 와. 어떻게 할까?"),
(H, "On assure le service d'abord. Après, on prend une décision.", "일단 서비스를 해내자. 결정은 그다음이야."),
(K, "Une décision sur quoi ? Tu veux fermer la porte aux clients ?", "무슨 결정이야? 손님을 돌려보내자는 거야?"),
(H, "Je ne sais pas encore. Va te laver les mains, on commence.", "아직 모르겠어. 가서 손 씻어, 시작하자."),
(None, "12 h 40. Le coup de feu. La salle est pleine, les tickets s'accumulent sur le rail. Chloé passe avec trois assiettes.", "12시 40분. 가장 바쁜 시간이다. 홀은 가득 찼고 주문서가 레일에 쌓인다. 클로에가 접시 세 개를 들고 지나간다."),
(C, "Table neuf, deux steaks-frites et un velouté ! Ça sort ?", "9번 테이블, 스테이크 프리트 둘에 벨루테 하나요! 나와요?"),
(K, "Deux minutes ! Les frites, c'est pas encore prêt !", "2분만! 감자튀김이 아직 안 됐어!"),
(C, "Ils attendent depuis vingt minutes, Karim. Ils sont énervés.", "20분째 기다리세요, 카림. 화가 나셨어요."),
(K, "Vingt minutes ? Mais le ticket est arrivé il y a dix minutes !", "20분? 주문서는 10분 전에 들어왔는데!"),
(J, "Non, Karim, c'est moi qui l'ai mis en retard. Il était coincé sous le plateau.", "아냐, 카림, 내가 늦게 넣었어. 쟁반 밑에 끼어 있었거든."),
(K, "Putain, Julien ! Tu pouvais pas le dire plus tôt ?", "젠장, 쥘리앵! 좀 더 일찍 말할 수 없었어?"),
(J, "Je viens de le voir. Désolé, vraiment, c'est ma faute.", "방금 봤어. 정말 미안, 내 잘못이야."),
(H, "Stop. Tout le monde se calme. On respire, et on repart.", "그만. 다들 진정해. 숨 쉬고 다시 가자."),
(K, "Je suis calme. Je suis juste épuisé, c'est tout.", "나 침착해. 그냥 너무 지쳤을 뿐이야."),
(H, "Je sais. Donne-moi ton plat : je termine les frites pendant que tu dresses.", "알아. 접시 이리 줘, 네가 담는 동안 내가 감자튀김 마무리할게."),
(K, "Merci. Excuse-moi pour le gros mot, je ne voulais pas t'agresser.", "고마워. 욕해서 미안, 공격하려던 건 아니었어."),
(H, "C'est rien. On en a tous marre, ces jours-ci. Dresse, vite.", "괜찮아. 요즘 다들 지쳤잖아. 빨리 담아."),
(K, "Table neuf, c'est parti ! Deux steaks, un velouté, et des frites toutes chaudes.", "9번 테이블, 나갑니다! 스테이크 둘, 벨루테 하나, 따끈한 감자튀김."),
(C, "Je les prends. Je leur dis que c'est la faute du chef, ça te va ?", "제가 가져갈게요. 셰프 탓이라고 말해도 돼요?"),
(K, "Dis-leur que c'est la faute du record. Ça, c'est vrai et ça fait plaisir.", "신기록 탓이라고 해. 그건 사실이고 기분도 좋잖아."),
(H, "Bien joué. Chloé, sourire, dos droit, et tu respires en marchant.", "잘했어. 클로에, 미소, 허리 펴고, 걸으면서 숨 쉬어."),
(C, "Oui, chef. Je respire, je souris, je ne fais tomber aucun verre.", "네, 셰프. 숨 쉬고, 웃고, 잔은 하나도 안 떨어뜨릴게요."),
(None, "13 h 15. Chloé revient à la plonge en courant. Elle s'arrête net devant Hélène, le souffle court.", "13시 15분. 클로에가 뛰어서 설거지 쪽으로 돌아온다. 그녀는 숨을 몰아쉬며 엘렌 앞에서 딱 멈춘다."),
(C, "Chef, une cliente se plaint. Elle dit qu'on l'a oubliée trente-cinq minutes.", "셰프, 손님 한 분이 불평하세요. 35분 동안 잊혀졌다고 하세요."),
(H, "Trente-cinq minutes ? Quelle table ?", "35분? 어느 테이블이야?"),
(C, "La douze. Julien est parti la voir, mais elle veut parler à la patronne.", "12번이요. 쥘리앵이 가 봤는데 사장님과 얘기하고 싶으시대요."),
(H, "Je viens. Karim, tu tiens la cuisine deux minutes, d'accord ?", "내가 갈게. 카림, 2분만 주방 맡아 줄 수 있지?"),
(K, "Vas-y. De toute façon, j'ai pas le choix.", "가요. 어차피 내가 선택권이 없잖아."),
(H, "Bonjour, madame. Je suis la responsable. Je suis navrée pour l'attente.", "안녕하세요, 부인. 제가 책임자입니다. 오래 기다리시게 해서 죄송합니다."),
(H, "Voilà, madame. Le dessert est pour nous, avec toutes nos excuses.", "여기 있습니다, 부인. 디저트는 저희가 드리겠습니다, 진심으로 사과드립니다."),
(J, "Merci, Hélène. J'étais en train de perdre pied.", "고마워, 엘렌. 나 정신을 못 차리고 있었어."),
(H, "On en parle après le service. Tiens le coup jusqu'à quatorze heures trente.", "서비스 끝나고 얘기하자. 2시 반까지만 버텨."),
(J, "Je tiendrai. Mais je te préviens : j'ai les jambes en coton.", "버틸게. 근데 미리 말해 두는데, 다리에 힘이 하나도 없어."),
(None, "15 h 10. La salle est vide. Les quatre sont assis autour d'une table, l'air épuisé. Hélène pose une carafe d'eau et une pile de papiers.", "15시 10분. 홀이 비었다. 네 사람이 지친 얼굴로 한 테이블에 둘러앉는다. 엘렌이 물병과 서류 더미를 내려놓는다."),
(H, "Bon. Je vous ai fait venir parce qu'on doit parler franchement.", "자, 솔직하게 얘기해야 해서 모이라고 했어."),
(C, "C'est à cause de la dame de tout à l'heure ? Je suis désolée.", "아까 그 부인 때문인가요? 죄송해요."),
(H, "Non, Chloé. Ce n'est la faute de personne. C'est la faute des chiffres.", "아냐, 클로에. 누구 잘못도 아니야. 숫자 탓이지."),
(K, "Des chiffres ? On a un record de ventes, Hélène. Je croyais que c'était bien.", "숫자? 매출 신기록이잖아, 엘렌. 나는 좋은 일인 줄 알았는데."),
(H, "C'est bien. Mais on est quatre pour servir quatre-vingts personnes. C'est trop.", "좋은 일이지. 근데 우리 넷이 80명을 대접하고 있어. 너무 많아."),
(J, "Résultat : les plats sortent en retard, donc les clients râlent, donc on stresse.", "결과적으로 요리는 늦게 나가고, 손님들은 투덜대고, 그래서 우리는 스트레스를 받아."),
(K, "Et du coup, on fait des erreurs. Ce midi, c'était moi, la prochaine fois ce sera toi.", "그러다 실수가 나오고. 오늘 점심은 나였고, 다음에는 너일 거야."),
(C, "Moi, je me trompe de table depuis lundi. Et j'oublie tout, même mon propre nom.", "저는 월요일부터 테이블을 계속 헷갈려요. 제 이름도 잊어버릴 지경이에요."),
(H, "Voilà. Si on continue comme ça, quelqu'un va se blesser ou démissionner.", "그래서야. 이렇게 계속하면 누군가 다치거나 그만두게 돼."),
(J, "Alors qu'est-ce qu'on fait ? On refuse des clients ?", "그럼 어떻게 해? 손님을 거절해?"),
(H, "Pas tout à fait. J'ai trois idées. Je vous les donne, vous me dites ce que vous en pensez.", "꼭 그렇진 않아. 아이디어가 세 개 있어. 말해 줄 테니 어떻게 생각하는지 얘기해 줘."),
(K, "Je t'écoute. Dis-moi que l'une d'elles, c'est dormir.", "듣고 있어. 그중 하나가 자는 거라고 해 줘."),
(H, "Un : on limite les réservations à soixante-dix couverts par service.", "하나, 서비스당 예약을 70명으로 제한한다."),
(J, "Soixante-dix ? Mais on perd dix clients à chaque fois.", "70명? 그러면 매번 손님 열 명을 놓치는데."),
(H, "On les perd, oui. Mais on les sert mieux. Deux : on ferme le dimanche soir et le lundi.", "놓치지, 맞아. 대신 더 잘 대접하는 거야. 둘, 일요일 저녁과 월요일은 완전히 쉰다."),
(K, "Le lundi, je suis chez moi, normalement. Sauf que je travaille quand même.", "월요일엔 원래 집에 있어야 하는데. 그래도 일을 하긴 하지."),
(H, "Justement. À partir de maintenant, personne ne touche aux commandes le lundi, c'est interdit.", "그러니까. 이제부터 월요일에 주문서 건드리는 건 아무도 안 돼, 금지야."),
(C, "Et la troisième idée ? Elle a l'air plus grave.", "세 번째 아이디어는요? 더 심각한 것 같은데."),
(H, "Trois : on embauche. Un commis en cuisine et un serveur ou une serveuse en salle.", "셋, 사람을 뽑는다. 주방 보조 한 명, 홀 서버 한 명."),
(J, "Enfin ! J'en parle depuis janvier, et personne ne m'écoutait.", "드디어! 1월부터 말했는데 아무도 안 들어 줬잖아."),
(H, "Je t'ai entendu, Julien. J'avais peur de ne pas pouvoir payer deux salaires de plus.", "들었어, 쥘리앵. 월급 둘을 더 감당 못 할까 봐 겁났던 거야."),
(K, "Et maintenant, tu peux ? Tu as fait le calcul ?", "그럼 지금은 돼? 계산해 봤어?"),
(H, "J'ai fait le calcul hier soir à minuit, d'où ma tête. Oui, on peut.", "어젯밤 자정에 계산했어, 내 얼굴이 이런 이유야. 응, 돼."),
(H, "Avec ce mois de mars, la trésorerie respire enfin. Et on rembourse déjà plus vite que prévu.", "이번 3월 덕분에 자금이 마침내 숨통이 트였어. 상환도 예정보다 빨라."),
(J, "Ça représente combien, deux salaires de plus ?", "월급 둘이 더 들면 얼마나 되는 거야?"),
(H, "Environ quatre mille euros par mois, charges comprises.", "사회보험 포함해서 한 달에 4천 유로쯤이야."),
(K, "Quatre mille ! Ça fait mal. Tu es sûre de toi ?", "4천이라니! 부담이 큰데. 확신해?"),
(H, "Oui. Un cuisinier qui craque coûte plus cher qu'un cuisinier de plus.", "응. 쓰러지는 요리사는 요리사 한 명 더 쓰는 것보다 비싸게 먹혀."),
(J, "Ça, c'est une vraie phrase de patronne. Je la note.", "그건 진짜 사장님다운 말이네. 적어 둘게."),
(C, "Alors je peux continuer mon alternance sans mourir de fatigue ?", "그럼 저는 피곤해 죽지 않고 견습을 계속할 수 있는 거예요?"),
(H, "Tu peux. Et j'ai même autre chose à te dire, mais ce sera pour plus tard.", "그럼. 그리고 따로 할 말이 더 있는데, 그건 나중에."),
(C, "Une bonne chose ou une mauvaise chose ? Dis-moi au moins ça.", "좋은 일이에요, 나쁜 일이에요? 그것만이라도 알려 주세요."),
(H, "Une bonne chose. Mais ne change pas de sujet : on prépare les annonces.", "좋은 일이야. 근데 화제 돌리지 마, 공고부터 준비하자."),
(J, "On met les annonces en ligne ce soir, et on reçoit les candidats mardi prochain.", "오늘 저녁 공고를 올리고 다음 주 화요일에 지원자를 만나자."),
(H, "Mardi vingt-trois, l'après-midi, entre deux services. Je mène les entretiens.", "23일 화요일 오후, 두 서비스 사이에. 면접은 내가 진행할게."),
(C, "Moi aussi, je peux venir ? Je veux voir comment ça se passe.", "저도 가도 돼요? 어떻게 진행되는지 보고 싶어요."),
(H, "Tu viendras. Un jour, c'est toi qui recruteras des apprentis.", "와도 돼. 언젠가는 네가 견습생을 뽑게 될 거야."),
(K, "Je peux écrire l'annonce pour le commis. Je sais ce qu'il faut chercher.", "내가 주방 보조 공고를 쓸게. 어떤 사람이 필요한지 아니까."),
(J, "Et moi, celle pour le serveur. Mon vieux plan : un sourire, une bonne mémoire, et des chaussures confortables.", "나는 서버 공고. 내 오랜 공식은 미소, 좋은 기억력, 편한 신발이야."),
(C, "Ajoute « un bon sens de l'humour ». Avec nous, il en faut.", "« 유머 감각 좋음 »도 넣어요. 우리랑 일하려면 필요하니까요."),
(H, "Ajoute aussi « capable de dire non ». Parce qu'on ne sait pas dire non, ici.", "« 거절할 줄 아는 사람 »도 넣어. 여기선 아무도 거절을 못 하니까."),
(K, "Ça, c'est vrai. On est trop gentils avec les clients et trop durs avec nous-mêmes.", "그건 맞아. 우린 손님한테는 너무 상냥하고 우리한테는 너무 가혹해."),
(H, "Voilà la phrase du jour. Julien, note-la sur l'ardoise de demain.", "오늘의 한마디네. 쥘리앵, 내일 칠판에 적어 놔."),
(J, "Sur l'ardoise des clients ? Ils vont se demander qui a écrit ça.", "손님용 칠판에? 누가 썼는지 궁금해하겠다."),
(H, "Non, sur le petit tableau de la cuisine. Celui que personne ne regarde jamais.", "아니, 주방의 작은 칠판에. 아무도 안 보는 그거."),
(K, "Je le regarde, moi. Enfin, quand j'ai le temps. C'est-à-dire jamais.", "나는 봐. 아니, 시간이 있을 때는. 그러니까 한 번도 없다는 거지."),
(C, "Bon, alors je propose un pacte. Tout le monde dort huit heures cette nuit.", "그럼 제가 협정을 제안할게요. 오늘 밤 다들 여덟 시간 자기."),
(H, "Pacte accepté. Et demain, ce sera mercredi : je ferme à vingt-deux heures pile.", "협정 받아들여. 그리고 내일은 수요일이니까 밤 10시 정각에 닫을 거야."),
(J, "Vingt-deux heures pile ? Tu ne vas pas rester jusqu'à minuit pour les comptes ?", "10시 정각? 너 자정까지 남아서 장부 정리하지 않을 거야?"),
(H, "Non. Les comptes attendront jeudi matin. Je le jure devant l'ardoise.", "안 해. 장부는 목요일 아침까지 기다릴 거야. 칠판 앞에서 맹세해."),
(K, "Alors on a tous un deal. Et moi, je vais enfin boire mon café.", "그럼 우리 모두 합의했네. 나는 드디어 커피를 마실 거고."),
(C, "Tu en veux deux ? Je t'en apporte deux, si tu me promets de sourire.", "두 잔 드실래요? 웃어 주신다고 약속하면 두 잔 가져다 드릴게요."),
(K, "Un seul sourire, ça va ? Je suis encore fatigué.", "미소는 한 번만 해도 돼? 아직 피곤하거든."),
(H, "Va pour un sourire. Allez, vingt minutes de pause, puis on prépare le soir.", "한 번이면 인정. 자, 20분 쉬고 저녁 준비하자."),
(J, "Et pour moi, un café et un croissant. J'ai le droit, je suis en pause.", "나는 커피랑 크루아상. 쉬는 시간이니까 먹어도 되지."),
(None, "Les quatre se lèvent lentement. Chloé court vers la machine à café. Pour la première fois depuis longtemps, la salle semble respirer.", "네 사람이 천천히 일어난다. 클로에가 커피 머신 쪽으로 뛰어간다. 오랜만에 홀이 숨을 쉬는 것 같다."),
]

VOCAB = [
("A2", "Je n'ai pas dormi plus de six heures.", "여섯 시간 넘게 못 잤어요.", "ne ... pas plus de + 수량 = 최대치. 일상에서 피곤함을 숫자로 말하는 가장 쉬운 방법."),
("A2", "Le carnet est plein jusqu'au six avril.", "장부가 4월 6일까지 찼어요.", "plein = 꽉 참, complet = 만석. 예약 상황 보고에 자주 쓰는 말."),
("A2", "Je tiendrai.", "버틸게요.", "tenir le coup(버티다)의 간단형. Je tiens ! = 아직 괜찮아."),
("A2", "Je suis désolé, c'est ma faute.", "미안해요, 제 잘못이에요.", "c'est ma faute / c'est la faute de ... 책임의 소재를 말할 때."),
("A2", "Va te laver les mains, on commence.", "손 씻고 와, 시작하자.", "명령형 + 대명동사(se laver). 주방의 짧은 지시."),
("B1", "J'ai une tête de zombie.", "좀비 같은 얼굴이에요.", "avoir une tête de ... + 명사 = ~같은 얼굴. 피곤·아픔 묘사. [구어] ↔ 정중: Je suis très fatigué."),
("B1", "à cause de / grâce à", "~ 때문에(나쁜 이유) / ~ 덕분에(좋은 이유)", "대화의 « C'est à cause de la dame ? » 에서 부정적 원인. « grâce à ce mois de mars » 는 긍정적 원인."),
("B1", "du coup / résultat / donc", "그래서 / 결과적으로 / 따라서", "[구어] du coup 이 가장 흔함. ↔ 정중: par conséquent. 인과 사슬 « les plats sortent en retard, donc les clients râlent, donc on stresse » 에서 반복."),
("B1", "J'ai les jambes en coton.", "다리에 힘이 풀렸어요.", "en coton = 솜 같은. 극도의 피로나 긴장 후 다리가 후들거릴 때."),
("B1", "tenir le rythme", "속도를 따라가다", "일의 페이스를 유지하다. Julien의 « Peur qu'on ne tienne pas le rythme ». ne 생략 구어에선 qu'on tienne pas."),
("B1", "On assure le service d'abord.", "일단 서비스는 해냅시다.", "assurer = 맡아서 해내다. 주방·홀의 현장어."),
("B2", "l'envers du décor", "무대 뒷면, 겉에 안 보이는 이면", "화려한 성공의 이면. « Le succès, ça se paye. » 와 함께 쓰이는 관용적 표현."),
("B2", "Tu vas craquer.", "너 무너질 거야.", "craquer = (정신적으로) 한계에 달하다. [구어] ↔ 정중: Vous allez être à bout de forces."),
("B2", "être à bout", "한계에 이르다", "à bout (de forces/de nerfs). « Tu es à bout, et Karim aussi. » 피로·신경 모두에 사용."),
("B2", "perdre pied", "정신을 못 차리다, 따라가지 못하다", "원래는 바닥에 발이 닿지 않는 것. 업무량에 압도될 때 사용."),
("B2", "J'ai fait le calcul à minuit.", "자정에 계산해 봤어요.", "faire le calcul = 따져 보다. 결정 전에 수치를 확인했다는 뉘앙스."),
("B2", "la trésorerie respire", "자금 사정이 숨통이 트이다", "trésorerie(현금흐름) + respirer 의 비유. 재정적 안도 표현."),
("B2", "On rembourse plus vite que prévu.", "예정보다 빨리 갚고 있어요.", "plus ... que prévu = 예상보다. 비교 + 과거분사."),
("C1", "Le succès, ça se paye.", "성공에는 대가가 따른다.", "se payer = 값이 치러지다(수동 의미의 대명동사). 격언처럼 쓰는 일상 표현."),
("C1", "Putain, Julien ! Tu pouvais pas le dire plus tôt ?", "젠장, 쥘리앵! 더 일찍 말할 수 없었어?", "[속어] putain 은 분노·피로의 감탄. 쓸 수 있음: 가까운 주방 동료 사이 / 금지: 손님·상사·외부인 앞. 뒤에 바로 사과하는 Karim 처럼 수습하는 것이 예의."),
("C1", "capable de dire non", "거절할 줄 아는", "capable de + 부정사. 채용 공고 문구로 재활용: « On ne sait pas dire non, ici. »"),
("B1", "Complet, midi et soir.", "점심도 저녁도 만석.", "complet = (식당·호텔) 만석. 구어에선 on est complet 이라고도 함."),
]

GRAM = [
("B1", "원인·결과 연결어 — à cause de / grâce à / donc / du coup / résultat", "« C'est à cause de la dame de tout à l'heure ? » (부정적 원인) / « Avec ce mois de mars, la trésorerie respire » (원인 + 결과). « Les plats sortent en retard, donc les clients râlent, donc on stresse. » 처럼 donc 를 연쇄해 인과를 이어 갈 수 있다. 구어에서는 « du coup » 가 가장 자주 쓰이며 « Et du coup, on fait des erreurs. » 처럼 문두에서 결과를 이끈다."),
("B1", "부정 표현 ne ... pas plus de, ne ... même pas", "« Je n'ai pas dormi plus de six heures. » 는 상한선을, « Il n'a même pas pris son café. » 는 기대에 못 미치는 극단을 보여 준다. 구어에서는 ne 를 생략해 « J'ai pas dormi plus de six heures » 처럼도 말한다."),
("B2", "비교의 plus ... que prévu / plus vite que", "« On rembourse déjà plus vite que prévu. » 형용사·부사 + que + 과거분사는 '예상·계획보다'의 표현. « On en faisait cinquante en décembre » 처럼 en 으로 수량을 받는 구문도 같이 익힌다."),
("B2", "접속법 ne tienne pas — peur que + 접속법", "« Peur qu'on ne tienne pas le rythme. » peur que 뒤는 접속법이다. 구어에서는 ne 를 생략하고 « qu'on tienne pas » 로 말한다. 정중체 ↔ 구어: « Je crains que nous ne tenions pas... » ↔ « J'ai peur qu'on tienne pas... »"),
("B1", "대명동사 명령형 — Va te laver les mains", "« Va te laver les mains, on commence. » 긍정 명령에서는 « lave-toi », 연속 동작에서는 « Va te laver ». 주방·홀의 짧은 지시는 대명동사 + 인칭대명사 위치를 자연스럽게 익히는 데 좋다."),
("B2", "수 표현과 비율 — soixante-dix, quatre-vingts", "« On limite les réservations à soixante-dix couverts. » « J'ai quatre-vingts couverts à préparer. » 70(soixante-dix), 80(quatre-vingts)은 프랑스 프랑스어 특유의 20진법이다. 끝의 s 는 quatre-vingts 에서만 붙고 뒤에 수가 오면 탈락(quatre-vingt-un)."),
("B1", "tu + 현재 / 반문 — Tu pouvais pas ... ?", "« Tu pouvais pas le dire plus tôt ? » 는 불평을 담은 과거 반문. 반과거(imparfait) 의문은 '그럴 수 있었잖아?' 라는 비난의 뉘앙스. 정중 ↔ « Auriez-vous pu me le dire plus tôt ? »"),
]

READ = [
("리에종 — il_y_a / vingt_et_un", "« Quarante et un messages. » 에서 et 은 리에종이 없다. 반면 « C'est un record » 의 c'est_un 은 [쎄땡] 처럼 이어 읽는다. 연습: « Il y a / quarante et un / messages. »"),
("비음 — cinquante, quatre-vingts, tout le monde", "« On en faisait cinquante en décembre. » 의 -ante [ɑ̃t], en [ɑ̃], -cembre [sɑ̃bʀ] 세 번 반복되는 비음을 입 안에서 코로 울리게. « quatre-vingts » 의 -vingts [vɛ̃] 는 비음 [ɛ̃] 이다."),
("r 발음 — records, retard, respire", "« Le succès, / ça se paye. » « La trésorerie respire enfin. » r 이 연속되는 문장은 목 뒤를 가볍게 긁는 소리로. 힘을 빼야 호흡이 이어진다."),
("호흡 구간 — 인과 사슬", "« Résultat : / les plats sortent en retard, / donc les clients râlent, / donc on stresse. » 쉼표마다 짧게 숨을 끊어 점점 빨라지는 느낌을 살린다."),
("억양 — 확인 의문문", "« Tu es toute pâle. Qu'est-ce qui t'arrive ? » 앞 문장은 내려가고 뒤 의문은 올라간다. « Trente-cinq minutes ? » 는 놀람으로 끝을 한 번 확 올린다."),
("u / ou — dormi, dessous, tout", "« Tout le monde dort huit heures. » ou [u] 는 입술을 동그랗게, u [y] 는 더 앞으로 모은다. « tu / tout », « dessus / dessous » 를 연습."),
("강세와 감정 — Putain, Julien !", "분노와 피로가 섞인 한 마디는 첫 음절에 힘을 주되 곧바로 « Désolé » 로 낮춰 수습하는 억양 차이를 연습한다."),
]

CULTURE = [
("Le « coup de feu » et la fatigue des brigades", "프랑스 식당에서는 점심·저녁 가장 바쁜 시간을 coup de feu 라고 부른다. 직원 과로는 업계의 오랜 문제여서, 월요일 완전 휴무나 예약 제한(couverts 상한)을 두는 가게가 늘고 있다. « Je ferme à vingt-deux heures pile » 처럼 '정각' 마감을 선언하는 것도 하나의 문화적 결정이다."),
("Les avis des clients et le carnet de réservations", "인기 식당은 몇 주 전부터 예약이 차기도 한다. 예약 장부(carnet de réservations)는 가게의 심장이라 여겨지며, '3주 뒤까지 만석(complet)'은 성공의 지표이면서 직원들에게는 압박의 원인이 된다."),
]

META = dict(part=5, ep=61, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="Le succès et ses revers", title_ko="성공의 이면",
 place="Le Comptoir de Marthe — 3월 16일(화) 오전 9시 30분~오후 3시 반, 주방·홀",
 chars="Hélène Marchand (주인 셰프, 과로) · Julien Benali (홀 매니저) · Chloé Dubois (견습, 시험 준비로 탈진) · Karim Haddad (부주방장, 탈진)",
 wine="예약이 4월 6일까지 만석, 3월 매출 사상 최고, 그 이면의 과로와 채용 결정",
 focus="원인·결과 연결어(à cause de, grâce à, donc, du coup), 피로 표현(à bout, craquer, perdre pied), 비교 plus ... que prévu",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제62화 « Recruter » : 3월 23일, 서버와 요리 보조를 뽑기 위한 면접. 질문과 선택의 하루.")
