# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, K, MD = "Hélène", "Julien", "Karim", "Mme Delorme"
D = [
(None, "Jeudi 1er avril, 10 h. La salle du Comptoir est impeccable. Hélène lisse une nappe qui n'a aucun pli, pendant que Julien vérifie la table du fond.", "4월 1일 목요일 오전 10시. 콩투아르의 홀은 흠잡을 데 없다. 엘렌은 주름 하나 없는 식탁보를 매만지고, 쥘리앵은 안쪽 테이블을 점검한다."),
(J, "Hélène, tu as déjà changé trois fois cette nappe. Elle est parfaite.", "엘렌, 그 식탁보 벌써 세 번째 갈았어. 완벽해."),
(H, "Je sais. Mais Mme Delorme dirige un quatre étoiles. Elle verra tout.", "알아. 그래도 델롬 부인은 4성급 호텔 지배인이야. 다 볼 거야."),
(J, "Tu as peur d'elle ?", "그분이 무서워?"),
(H, "Non. J'ai peur de me tromper. Un contrat comme ça, ça change tout.", "아니. 실수할까 봐 무서운 거야. 이런 계약은 모든 걸 바꿔."),
(J, "Rappelle-toi : elle est venue deux fois dîner ici en février, incognito.", "기억해 봐. 그분은 2월에 신분을 숨기고 두 번이나 여기서 식사했어."),
(H, "Elle n'était pas incognito du tout. Elle a pris des notes sur la serviette.", "전혀 숨기지 않았어. 냅킨에 메모했거든."),
(J, "Ça veut dire qu'elle est sérieuse. Et qu'on lui a plu.", "진지하다는 뜻이지. 그리고 우리가 마음에 들었다는 뜻이고."),
(H, "Ou qu'elle cherche un moyen de baisser ses coûts. On verra.", "아니면 비용을 줄일 방법을 찾는 거거나. 두고 보자."),
(J, "Mets-toi tranquille. Je prends la porte, tu restes au bar.", "진정해. 내가 문을 맡을게, 넌 바에 있어."),
(None, "10 h 05. Une berline grise se gare devant le Comptoir. Une femme élégante, tailleur bleu nuit, en descend avec un dossier sous le bras.", "10시 5분. 회색 세단이 콩투아르 앞에 선다. 감색 정장을 입은 우아한 여성이 서류철을 끼고 내린다."),
(J, "Madame Delorme ? Bonjour, bienvenue au Comptoir de Marthe.", "델롬 부인이세요? 안녕하세요, 르 콩투아르 드 마르트에 오신 것을 환영합니다."),
(MD, "Bonjour, monsieur. Vous êtes monsieur Benali, je suppose. Ponctuel, comme on me l'a dit.", "안녕하세요. 베날리 씨시죠. 들은 대로 시간을 잘 지키시네요."),
(J, "On essaie. Madame Marchand vous attend. Par ici, je vous en prie.", "노력합니다. 마르샹 사장님이 기다리십니다. 이쪽으로 오세요."),
(H, "Madame Delorme, merci d'être venue. J'espère que le trajet n'a pas été trop long.", "델롬 부인, 와 주셔서 감사합니다. 오시는 길이 너무 멀지 않았길 바랍니다."),
(MD, "Quarante minutes depuis le Grand Parisien. Pas trop long, mais les embouteillages sont affreux.", "그랑 파리지앵에서 40분 걸렸어요. 길진 않았지만 교통 체증이 끔찍하네요."),
(H, "Un café ? Un thé ? Ou un verre d'eau ?", "커피 드릴까요? 차? 아니면 물 한 잔?"),
(MD, "Un café serré, sans sucre. Et un peu de franchise, si vous voulez bien.", "설탕 없는 진한 커피요. 그리고 괜찮으시다면 솔직함도 조금."),
(H, "La franchise, on en a ici. C'est la qualité première de la maison.", "솔직함은 이 집에 많아요. 저희 집의 제1 장점이죠."),
(MD, "Tant mieux. Je vais donc être directe : je ne perds jamais de temps.", "다행이네요. 그럼 단도직입적으로 말할게요. 저는 시간을 낭비하지 않아요."),
(MD, "Le Grand Parisien a cent quarante-deux chambres, quatre salons et deux banquets par semaine.", "그랑 파리지앵은 객실이 142개, 연회장이 4개, 매주 연회가 두 건 있어요."),
(H, "C'est beaucoup plus gros que nous. Je ne sais pas si nous sommes à la hauteur.", "저희보다 훨씬 큰 곳이에요. 저희가 그 수준이 되는지 모르겠네요."),
(MD, "Je ne cherche pas la grandeur. Je cherche la sincérité. Mes chefs sont bons, mais froids.", "저는 규모를 찾는 게 아니에요. 진정성을 찾죠. 우리 셰프들은 실력은 좋지만 차가워요."),
(H, "Froids ? C'est un reproche ?", "차갑다고요? 책망인가요?"),
(MD, "C'est une observation. Mes clients d'entreprise veulent désormais une cuisine qui ait une âme.", "관찰이에요. 법인 고객들이 이제는 영혼이 있는 요리를 원해요."),
(J, "Une âme... voilà une qualité qui ne s'achète pas.", "영혼이라... 돈으로 살 수 없는 품질이네요."),
(MD, "Justement. Vous l'avez, c'est pourquoi je suis ici. Parlons concret.", "그래서 제가 온 거예요. 구체적으로 이야기하죠."),
(H, "Je vous écoute. Asseyez-vous, je vous en prie, vous serez mieux.", "듣겠습니다. 앉으세요, 그게 편하실 거예요."),
(None, "Ils s'installent à la table du fond. Mme Delorme ouvre son dossier et sort une feuille avec un tableau.", "그들이 안쪽 테이블에 앉는다. 델롬 부인이 서류철을 열어 표가 그려진 종이를 꺼낸다."),
(MD, "Voici ma proposition. Deux événements par mois, au sein de nos salons, à partir de la mi-avril.", "제 제안입니다. 4월 중순부터 매달 두 건, 저희 연회장에서 하는 행사예요."),
(H, "Deux par mois. Quel type d'événements ?", "달에 두 건이군요. 어떤 종류의 행사인가요?"),
(MD, "Dîners d'entreprise, remises de prix, quelques mariages. Entre quatre-vingts et cent cinquante convives.", "기업 만찬, 시상식, 결혼식 몇 건. 하객은 80명에서 150명 사이예요."),
(J, "Cent cinquante ! Notre salle en fait trente-huit avec la terrasse.", "150명이라니! 저희 홀은 테라스까지 합쳐도 38석인데요."),
(MD, "Vous cuisinerez dans nos cuisines, avec vos équipes. Nous fournissons la salle, la vaisselle et le personnel de service.", "저희 주방에서 여러분의 팀과 요리하시면 돼요. 연회장, 식기, 서비스 인력은 저희가 제공합니다."),
(H, "Donc le Grand Parisien assure le matériel, et nous assurons le menu et la brigade ?", "그러니까 그랑 파리지앵이 설비를 맡고 저희는 메뉴와 팀을 맡는 거군요?"),
(MD, "Exactement. Et je vous propose soixante-deux euros par personne, avec un minimum de cent convives.", "정확해요. 그리고 1인당 62유로, 최소 100명을 제안합니다."),
(H, "Soixante-deux euros pour un menu complet, vin non compris ?", "와인 불포함 풀코스가 62유로인가요?"),
(MD, "Entrée, plat, dessert, café. Les vins, nous les facturons à part.", "전채, 메인, 디저트, 커피요. 와인은 따로 청구합니다."),
(H, "Madame, je vais vous être franche à mon tour. Soixante-deux euros, c'est trop bas.", "부인, 저도 솔직하게 말할게요. 62유로는 너무 낮아요."),
(MD, "Je m'en doutais. Dites-moi pourquoi.", "그럴 줄 알았어요. 이유를 말씀해 주세요."),
(H, "Nous travaillons avec des producteurs, du fait-maison, des produits de saison. Ça coûte cher.", "저희는 생산자와 직거래하고 직접 만들고 제철 재료를 써요. 비용이 많이 듭니다."),
(H, "À soixante-deux euros, il me reste dix-huit euros de marge par convive, avant les salaires.", "62유로면 인건비 전에 한 사람당 마진이 18유로 남아요."),
(MD, "Dix-huit euros de marge brute ? C'est correct pour un banquet, non ?", "총마진 18유로요? 연회치고는 괜찮지 않아요?"),
(H, "C'est correct pour un traiteur industriel. Pas pour nous, qui cuisinons à la main.", "산업형 케이터링에는 괜찮죠. 손으로 요리하는 저희에겐 아니에요."),
(J, "Nous demandons soixante-quinze euros par personne.", "저희는 1인당 75유로를 요청합니다."),
(MD, "Soixante-quinze ? C'est excessif. Mes clients paient quatre-vingts euros chez mon concurrent.", "75요? 과하네요. 제 고객들은 경쟁사에서 80유로를 내요."),
(H, "Chez votre concurrent, ils mangent un plat de traiteur. Chez nous, ils goûtent une blanquette de Marthe.", "경쟁사에서는 케이터링 요리를 먹죠. 저희한테서는 마르트의 블랑케트를 맛보고요."),
(MD, "Vous êtes forte en négociation. Coupons la poire en deux : soixante-huit euros.", "협상을 잘하시네요. 중간에서 만나죠. 68유로."),
(H, "Soixante-huit euros, d'accord. Mais pas cent convives minimum, c'est trop pour nos équipes.", "68유로, 좋아요. 하지만 최소 100명은 저희 팀에 너무 많아요."),
(MD, "Alors quel minimum proposez-vous ?", "그럼 최소 인원은 얼마를 제안하시나요?"),
(H, "Soixante convives. En dessous, je ne couvre pas mes frais fixes.", "60명이요. 그 밑이면 고정비를 못 메워요."),
(MD, "Soixante, c'est trop peu pour mobiliser une salle de deux cents places. Disons quatre-vingts.", "60명은 200석 홀을 쓰기엔 너무 적어요. 80명으로 하죠."),
(H, "Quatre-vingts. Ça fait cinq mille quatre cent quarante euros au minimum par événement.", "80명이면 행사 한 건당 최소 5,440유로가 되네요."),
(MD, "Vous calculez vite. Oui, soixante-huit fois quatre-vingts.", "계산이 빠르시네요. 네, 68 곱하기 80이에요."),
(J, "Donc, deux événements par mois, au minimum dix mille huit cent quatre-vingts euros.", "그러니까 한 달 두 건이면 최소 1만 880유로예요."),
(MD, "Si les événements ont lieu, bien sûr. Je ne peux pas vous garantir un nombre de mariages.", "행사가 열린다면 말이죠. 결혼식 건수까지 보장할 수는 없어요."),
(H, "Alors je veux une clause : si vous annulez à moins de quinze jours, vous payez le minimum.", "그럼 조항이 하나 필요해요. 15일 이내에 취소하시면 최소 금액을 내시는 조건이에요."),
(MD, "Quinze jours ? Disons dix jours, et l'annulation pour cas de force majeure reste libre.", "15일이요? 10일로 하고, 불가항력 취소는 자유로 하죠."),
(H, "Dix jours, sauf grève ou fermeture administrative. Je suis d'accord.", "10일로 하되, 파업이나 행정 폐쇄는 예외로 하죠. 동의합니다."),
(MD, "Fermeture administrative ? Voilà un mot que je préfère ne pas voir dans vos locaux.", "행정 폐쇄요? 그 말은 귀사 가게에서 다시 듣고 싶지 않군요."),
(H, "Nous avons déjà donné, madame. Cette fois, c'est la version propre.", "저희는 이미 겪었죠, 부인. 이번에는 깨끗한 버전이에요."),
(MD, "J'ai vu votre dossier. L'inspection de septembre, vous l'avez corrigée. C'est ce qui m'a rassurée.", "서류를 봤어요. 9월 검사 문제는 시정하셨더군요. 그게 저를 안심시켰어요."),
(None, "Mme Delorme fait glisser une page vers Hélène. En haut, en gras : « Conditions de paiement ».", "델롬 부인이 종이 한 장을 엘렌 쪽으로 밀어 준다. 위쪽에 굵은 글씨로 « 지불 조건 »이라고 적혀 있다."),
(MD, "Acompte de trente pour cent à la signature, le solde sous trente jours après l'événement.", "서명 시 30% 계약금, 잔금은 행사 후 30일 이내입니다."),
(H, "Trente jours, c'est long pour une petite entreprise. Quinze jours, ça se fait ?", "30일은 작은 업체에게는 길어요. 15일은 안 될까요?"),
(MD, "Vingt et un jours. Je ne descendrai pas plus bas.", "21일로 하죠. 그보다 줄일 수는 없어요."),
(H, "Vingt et un jours. Très bien, ça passe.", "21일. 좋아요, 받아들이죠."),
(J, "Et les extras en salle ? Qui les recrute ?", "연회장의 추가 인력은 누가 구하나요?"),
(MD, "Mon maître d'hôtel, Vincent. Six à huit personnes, formées chez nous.", "저희 마이트르 도텔 뱅상이요. 6명에서 8명, 자체 교육을 받은 인력이에요."),
(J, "Je voudrais les briefer avant chaque événement. Le service doit parler un seul langage.", "각 행사 전에 제가 브리핑하고 싶어요. 서비스는 하나의 언어로 말해야 하니까요."),
(MD, "Excellente idée. Vincent sera ravi de travailler avec un professionnel comme vous.", "훌륭한 생각이에요. 뱅상이 당신 같은 전문가와 일하게 되어 기뻐할 거예요."),
(H, "Pour les menus, qui décide ? Vous ou moi ?", "메뉴는 누가 정하죠? 부인인가요, 저인가요?"),
(MD, "Vous proposez, le client choisit, je valide. Nous gérons aussi les régimes particuliers.", "제안은 귀하가, 선택은 고객이, 승인은 제가 해요. 특별 식단도 같이 다룹니다."),
(H, "Végétarien, halal, sans gluten ? Il faut me prévenir au moins une semaine avant.", "채식, 할랄, 글루텐프리요? 최소 일주일 전에는 알려 주셔야 해요."),
(MD, "Une semaine, entendu. Et la confirmation du nombre de convives, quarante-huit heures avant.", "일주일, 알겠어요. 인원 확정은 48시간 전에 합니다."),
(H, "Quarante-huit heures, ce n'est pas assez pour commander les produits frais.", "48시간으로는 신선 재료를 주문하기에 부족해요."),
(MD, "Alors soixante-douze heures. Mais le jour même, un écart de dix pour cent reste toléré.", "그럼 72시간으로 하죠. 그래도 당일 10% 오차는 허용돼요."),
(H, "Dix pour cent sur quatre-vingts convives, ça fait huit personnes. Je tiens le coup.", "80명에서 10%면 8명이네요. 감당할 수 있어요."),
(None, "Un bruit de pas dans l'escalier. Karim entre, un plateau de petites assiettes entre les mains, le tablier propre.", "계단에서 발소리가 난다. 카림이 작은 접시들을 얹은 쟁반을 들고 깨끗한 앞치마 차림으로 들어온다."),
(K, "Bonjour, madame. Excusez-moi, je vous apporte une dégustation, si vous avez cinq minutes.", "안녕하세요, 부인. 죄송하지만 시식을 가져왔어요. 5분 괜찮으세요?"),
(MD, "Cinq minutes, oui. Vous êtes le sous-chef, je suppose ?", "5분은 괜찮아요. 부주방장이시죠?"),
(K, "Oui, Karim Haddad. Voici la version banquet de notre blanquette, en bouchée de veau.", "네, 카림 하다드입니다. 저희 블랑케트의 연회용 버전, 송아지 한입 요리예요."),
(MD, "En bouchée... pour un cocktail dînatoire ?", "한입 크기로요... 칵테일 디너용인가요?"),
(K, "Pour un cocktail ou pour une entrée de banquet, au choix. Et voici un velouté de petits pois en verrine.", "칵테일용이든 연회 전채든 선택하시면 돼요. 그리고 이건 완두콩 벨루테 베린이에요."),
(None, "Mme Delorme goûte lentement, sans rien dire. Puis elle repose la cuillère avec précision.", "델롬 부인이 아무 말 없이 천천히 맛을 본다. 그리고 숟가락을 정확하게 내려놓는다."),
(MD, "La sauce est longue en bouche, le veau fond. C'est du travail de fond, ça.", "소스가 입안에서 길게 이어지고 송아지가 녹네요. 공을 들인 요리예요."),
(K, "Merci, madame. Il y a quatre heures de cuisson pour le veau, et la crème arrive tout à la fin.", "감사합니다. 송아지는 4시간 조리하고 크림은 맨 마지막에 넣어요."),
(MD, "Vous seriez prêt à faire cette qualité pour cent vingt personnes ?", "이 품질을 120명분으로도 하실 수 있겠어요?"),
(K, "Pour cent vingt, oui. Mais il me faut un four de plus et deux commis supplémentaires.", "120명이면 가능해요. 대신 오븐이 하나 더 있고 보조가 둘 더 필요해요."),
(MD, "Nos cuisines ont six fours et douze commis. Vous serez servi.", "저희 주방에는 오븐 여섯 대와 보조 열두 명이 있어요. 부족하지 않을 겁니다."),
(H, "Et le matériel de transport ? Nous prépareons une partie ici ?", "운반 장비는요? 일부는 여기서 준비하나요?"),
(MD, "Tout sur place, dans nos cuisines. Pas de transport, pas de rupture de chaîne du froid.", "전부 저희 주방에서 해요. 운반도 없고 냉장 유통 단절도 없죠."),
(H, "Parfait. Pour la première date, vous aviez parlé du vingt-quatre avril.", "좋아요. 첫 일정으로 4월 24일을 말씀하셨죠."),
(MD, "Samedi vingt-quatre avril, cent vingt convives, un dîner de gala pour une entreprise pharmaceutique.", "4월 24일 토요일, 120명, 제약회사 갈라 디너예요."),
(J, "Cent vingt fois soixante-huit euros... Huit mille cent soixante euros pour une soirée.", "120 곱하기 68유로... 한 저녁에 8,160유로야."),
(H, "Julien, ne dis pas les chiffres à voix haute, ça porte malheur.", "쥘리앵, 숫자를 소리 내어 말하지 마, 불길해."),
(MD, "Superstitieuse ? Moi aussi. Je ne passe jamais sous une échelle.", "미신을 믿으세요? 저도 그래요. 사다리 밑은 절대 안 지나가죠."),
(H, "Un point m'inquiète : le samedi, nous avons aussi notre service du soir ici.", "걱정되는 점이 하나 있어요. 토요일에는 여기 저녁 서비스도 있어요."),
(MD, "Alors fermons le Comptoir ce soir-là. Je le compenserai si vous le souhaitez.", "그럼 그날 저녁은 콩투아르를 닫으세요. 원하시면 제가 보상하죠."),
(H, "Fermer un samedi soir ? Non. Je ne veux pas perdre mes habitués.", "토요일 저녁에 문을 닫는다고요? 아뇨. 단골을 잃고 싶지 않아요."),
(MD, "Dans ce cas, l'événement a lieu un lundi ou un dimanche. Je m'adapte.", "그럼 행사는 월요일이나 일요일에 해요. 제가 맞출게요."),
(H, "Pour le vingt-quatre, je demande à Karim de tenir le Comptoir avec Chloé et Malik.", "24일에는 카림이 클로에와 말릭과 함께 콩투아르를 맡도록 할게요."),
(K, "Moi ? Je ne vais pas à l'hôtel avec vous ?", "저요? 호텔에 같이 안 가나요?"),
(H, "Non. Moi, je prends Julien et Léna pour la salle. Toi, tu es mon chef ici.", "아니. 나는 쥘리앵과 레나를 홀에 데려가. 넌 여기서 내 셰프야."),
(K, "D'accord. Mais je veux que tout soit écrit dans le contrat avant qu'on commence.", "알았어요. 하지만 시작 전에 전부 계약서에 쓰여 있기를 바라요."),
(MD, "Il a raison. Je vous envoie le projet de contrat lundi par courriel.", "맞는 말이에요. 월요일에 계약서 초안을 이메일로 보낼게요."),
(H, "Je le ferai relire par mon expert-comptable et mon avocat avant de signer.", "서명하기 전에 회계사와 변호사에게 검토를 맡길게요."),
(MD, "Évidemment. Un contrat qu'on ne relit pas est un contrat qu'on regrette.", "당연하죠. 안 읽은 계약서는 후회하는 계약서예요."),
(H, "Alors, nous nous retrouvons jeudi huit avril pour la signature ?", "그럼 4월 8일 목요일에 서명하러 만날까요?"),
(MD, "Jeudi huit avril, dix heures, au Grand Parisien. Je vous offrirai le déjeuner.", "4월 8일 목요일 오전 10시, 그랑 파리지앵에서요. 점심은 제가 대접할게요."),
(H, "Avec plaisir. Je n'ai pas encore vu votre cuisine.", "기꺼이요. 아직 호텔 주방은 못 봤어요."),
(MD, "Vous la verrez. Et vous verrez aussi mon chef, qui rêve de vous rencontrer depuis dix jours.", "보시게 될 거예요. 열흘 전부터 당신을 만나고 싶어 하는 제 셰프도요."),
(None, "Elle se lève, serre la main d'Hélène, puis celle de Julien. Elle jette un dernier regard à la salle.", "그녀가 일어나 엘렌과 악수하고 쥘리앵과도 악수한다. 마지막으로 홀을 한 번 둘러본다."),
(MD, "Madame Marchand, votre mère aurait été fière de cette maison.", "마르샹 사장님, 어머님이 이 가게를 자랑스러워하셨을 거예요."),
(H, "Vous avez connu Marthe ?", "마르트를 아셨어요?"),
(MD, "J'ai mangé ici en mille neuf cent quatre-vingt-quinze. Un steak-frites, et elle m'avait servi elle-même.", "1995년에 여기서 먹었어요. 스테이크 프리트였고 그분이 직접 서빙해 주셨죠."),
(H, "Elle ne servait jamais. Elle devait vous aimer.", "엄마는 서빙을 잘 안 했는데. 부인이 마음에 드셨나 봐요."),
(MD, "Ou elle avait pitié d'une étudiante affamée. À jeudi, madame.", "아니면 배고픈 대학생이 불쌍했는지도요. 목요일에 뵙겠습니다."),
(J, "Alors ? Tu es contente ? Tu as le visage de quelqu'un qui vient de gagner au loto.", "그래서? 만족해? 복권이라도 당첨된 사람 얼굴이야."),
(H, "Ni contente ni triste. Je suis sonnée. Dis-moi ce qu'on vient de faire.", "만족도 슬픔도 아니야. 멍해. 우리가 방금 뭘 한 건지 말해 줘."),
(K, "On vient de signer pour devenir un petit traiteur d'hôtel, voilà ce qu'on a fait.", "우리는 호텔의 작은 케이터링 업체가 되기로 한 거예요, 그게 우리가 한 일이죠."),
(H, "Non, Karim. On vient de trouver un moyen de rembourser la dette plus vite, sans changer le Comptoir.", "아냐, 카림. 콩투아르를 바꾸지 않고 빚을 더 빨리 갚을 방법을 찾은 거야."),
]

VOCAB = [
("A2", "Bienvenue au Comptoir de Marthe.", "르 콩투아르 드 마르트에 오신 것을 환영합니다.", "손님·거래처를 맞이하는 정중한 인사. bienvenue à/au + 장소."),
("A2", "Un café serré, sans sucre.", "설탕 없는 진한 커피요.", "café serré = 에스프레소보다 진한 커피, sans sucre = 설탕 없이. 주문 표현."),
("A2", "Asseyez-vous, je vous en prie.", "앉으세요.", "vous 명령형 + je vous en prie(별말씀을/ 어서요). 비즈니스 환대."),
("A2", "soixante-huit euros par personne", "1인당 68유로", "par personne = 1인당. 숫자 읽기: soixante-huit(68)."),
("A2", "Deux événements par mois.", "한 달에 행사 두 건입니다.", "par + 기간 = ~당. 빈도 표현."),
("B1", "un devis / un projet de contrat", "견적서 / 계약서 초안", "devis 는 견적, projet de contrat 는 초안. 서명 전 단계."),
("B1", "un acompte de trente pour cent", "30% 계약금", "acompte = 계약금, solde = 잔금. à la signature = 서명 시."),
("B1", "un minimum de quatre-vingts convives", "최소 80명의 손님", "convive = 연회 참석자. minimum de + 수량. 협상의 핵심 조건."),
("B1", "tout compris / vin non compris", "전부 포함 / 와인 불포함", "compris = 포함된. 가격 협상에서 항상 확인할 표현."),
("B1", "un cocktail dînatoire", "칵테일 디너(핑거푸드 위주 만찬)", "서서 먹는 연회 형식. 한입 요리를 bouchée 라 한다."),
("B2", "assurer le matériel / le service", "설비·서비스를 책임지고 맡다", "assurer = 책임지고 제공하다. 호텔은 la salle, la vaisselle, le personnel 을 담당."),
("B2", "couper la poire en deux", "절충하다, 중간에서 만나다", "관용구. 협상에서 양쪽이 반씩 양보할 때. « Coupons la poire en deux : soixante-huit euros. »"),
("B2", "la marge brute", "총마진", "매출에서 재료비를 뺀 이익. « dix-huit euros de marge par convive »."),
("B2", "une clause d'annulation", "취소 조항", "annuler, annulation pour cas de force majeure(불가항력 취소). 계약서의 핵심 조항."),
("B2", "les frais fixes", "고정비", "임대료·인건비 등 매출과 무관한 비용. « Je ne couvre pas mes frais fixes. »"),
("B2", "un maître d'hôtel / un extra", "홀 총괄자 / 임시 서비스 인력", "호텔·연회의 서비스 책임자와 단기 보조 인력. « Six à huit personnes, formées chez nous. »"),
("B2", "un régime particulier", "특별 식단", "végétarien, halal, sans gluten 등. prévenir au moins une semaine avant."),
("B2", "la chaîne du froid", "냉장·냉동 유통 체계", "식품 안전 용어. « pas de rupture de chaîne du froid » = 냉장 유통이 끊기지 않음."),
("C1", "Ça porte malheur.", "재수가 없어요, 불길해요.", "[구어] 숫자를 소리 내어 말하는 미신. ↔ 정중: C'est de mauvais augure."),
("C1", "Je suis sonnée.", "멍해요, 충격받았어요.", "[구어] sonné(e) = 한 방 맞아 정신없는. ↔ 정중: Je suis encore sous le choc."),
("C1", "C'est du travail de fond.", "공을 들인 작업이에요.", "travail de fond = 근본부터 쌓은 작업, 서두르지 않은 깊이 있는 작업. 요리·비즈니스 칭찬에 쓰임."),
("C1", "Nous avons déjà donné.", "저희는 이미 겪을 만큼 겪었어요.", "[구어] 관용구: 더 이상 그런 일은 사양이라는 뜻. 폐쇄 명령 이야기에 대한 농담."),
("B1", "Un contrat qu'on ne relit pas est un contrat qu'on regrette.", "읽지 않은 계약서는 후회하는 계약서다.", "관계절 qu'on ne relit pas. 속담처럼 쓸 수 있는 말."),
]

GRAM = [
("B1", "숫자·가격·퍼센트 읽기", "« soixante-huit euros par personne », « quatre-vingts convives », « trente pour cent », « vingt et un jours ». 70~99는 20진법(soixante-dix, quatre-vingts). 곱셈 « soixante-huit fois quatre-vingts » 처럼 fois 를 쓰면 계산을 바로 말할 수 있다."),
("B2", "조건 협상의 접속사 — à condition que, sauf, dans ce cas", "« Dix jours, sauf grève ou fermeture administrative. » « Dans ce cas, l'événement a lieu un lundi. » sauf + 명사, à condition que + 접속법 형태로 조건을 정리한다. 협상에서는 « Si vous annulez à moins de dix jours, vous payez le minimum » 처럼 si + 현재 + 현재(또는 미래) 가 가장 자주 쓰인다."),
("B2", "제안과 양보 — Disons / Coupons la poire en deux", "« Disons quatre-vingts. » « Coupons la poire en deux. » 구어에서 합의점을 제시할 때 disons + 수치, 명령형 1인칭 복수(coupons)를 쓴다. 양보할 때는 « d'accord, mais » 구조가 흔하다."),
("B2", "비교·반대 — Ce n'est pas la grandeur, c'est la sincérité", "« Je ne cherche pas la grandeur. Je cherche la sincérité. » ne ... pas A, mais B 를 두 문장으로 나눠 말한 것. 협상에서 입장을 선명하게 대비시킬 때 쓰는 화법."),
("B1", "미래 단순 — Je vous enverrai / Vous la verrez", "« Je vous envoie le projet de contrat lundi. » (현재로 가까운 미래) / « Vous la verrez. » (미래 단순) / « Je vous offrirai le déjeuner. » 약속·계획에는 미래 단순과 현재가 같이 쓰인다."),
("B2", "접속법 — que tout soit écrit / avant qu'on commence", "« Je veux que tout soit écrit dans le contrat avant qu'on commence. » vouloir que, avant que 는 접속법을 취한다. 계약 협상에서 요구를 선명하게 말하는 구문."),
("B1", "수동적 의미의 ça se + 동사", "« Quinze jours, ça se fait ? » ça se fait = 그런 게 가능한가요? 구어에서 일반적인 가능·관행을 묻는다. « Ça ne se fait pas » 는 예의에 어긋난다는 뜻."),
]

READ = [
("숫자 읽기 — 가격과 인원", "« Soixante-huit euros / par personne, / avec un minimum / de quatre-vingts convives. » 숫자 앞뒤에 호흡을 두고 소리 내어 천천히. soixante-huit [swa sɑ̃t ɥit], quatre-vingts [katʁə vɛ̃]."),
("리에종 — vous_avez / trente_et_un", "« Vous avez cent quarante-deux chambres. » vous_avez [vu za ve]. « un événement » 는 un_événement [œ̃ ne vɛn mɑ̃] 처럼 n 을 이어 읽는다. cent_vingt 는 리에종 없음: [sɑ̃ vɛ̃]."),
("비음 — convive, minimum, banquet", "« Un minimum de quatre-vingts convives. » minimum [mi ni mɔm], convive [kɔ̃ viv], banquet [bɑ̃ kɛ]. 세 비음 [ɔ̃][ɑ̃][ɛ̃] 를 구분해서 연습."),
("협상의 억양 — 놀람과 거절", "« Soixante-quinze ? C'est excessif. » 앞의 수치는 올리고 뒤는 내려 단호하게. 반면 « D'accord, mais pas cent » 는 mais 에서 억양을 낮춰 가볍게."),
("r 발음 — directe, rembourser, relire", "« Je serai directe. » « Un contrat qu'on ne relit pas est un contrat qu'on regrette. » r 이 세 번 이상 반복되는 문장. 어깨에 힘을 빼고 목 안쪽에서."),
("호흡 구간 — 지불 조건", "« Acompte de trente pour cent / à la signature, / le solde / sous trente jours / après l'événement. » 긴 조건문은 의미 단위마다 끊어 읽는다."),
("u / ou — vous / tout / pour", "« Vous voulez tout pour tout le monde. » ou [u] 를 입술 모아 정확히. « tu / tout » « vu / vous » 최소 대립쌍 연습."),
]

CULTURE = [
("Le banquet d'hôtel et la cuisine de traiteur", "프랑스 4성급 호텔은 객실 외에 salon de réception 을 갖추고 기업 만찬·결혼식 같은 banquet 으로 수익을 낸다. 외부 레스토랑과의 제휴는 유행이다. 가격은 1인당(par personne)·최소 인원(minimum de convives)·취소 조항(clause d'annulation)으로 협상하며, 와인은 보통 따로 청구한다."),
("Le contrat : lire avant de signer", "프랑스 상거래에서는 서명 전에 projet de contrat 를 보내 변호사(avocat)·회계사(expert-comptable)가 검토하는 것이 일반적이다. 계약금(acompte)·잔금(solde) 비율, 지불 기한(보통 30일, 소기업은 짧게 협상), 취소 조항이 핵심이다."),
]

META = dict(part=5, ep=63, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="L'offre de l'hôtel", title_ko="호텔의 제안",
 place="Le Comptoir de Marthe — 4월 1일(목) 오전 10시, 홀 안쪽 테이블",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Karim Haddad (부주방장) · Mme Delorme (호텔 Le Grand Parisien 지배인, 50대)",
 wine="호텔 케이터링 계약 협상: 연 월 2회 연회·인당 68 €·최소 80명",
 focus="호텔 서비스 어휘(banquet, convives, acompte, clause d'annulation), 조건 협상 화법, 가격·퍼센트 읽기",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제64화 « Banquet au Grand Hôtel » : 4월 24일, 호텔에서 120명 연회를 격식 있게 치르는 날.")
