# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, L = "Hélène", "Julien", "Chloé", "Lucien"
D = [
(None, "Mardi 4 mai, 9 h 15. Avant l'ouverture. Julien entre dans le Comptoir avec deux croissants et un air mystérieux. Hélène écrit le menu du jour sur l'ardoise.", "5월 4일 화요일 오전 9시 15분. 오픈 전. 쥘리앵이 크루아상 두 개를 들고 수상쩍은 표정으로 콩투아르에 들어선다. 엘렌은 칠판에 오늘의 메뉴를 쓰고 있다."),
(J, "Hélène, j'ai une nouvelle. Une grosse. Tu es assise ?", "엘렌, 소식이 있어. 큰 거야. 앉아 있어?"),
(H, "Je suis debout, la craie à la main. Dis-moi vite, j'ai la Tatin à surveiller.", "서 있어, 분필 들고. 빨리 말해, 타탱도 봐야 하니까."),
(J, "M. Arnoux prend sa retraite. Sa boulangerie, juste à côté, ferme le trente et un mai.", "아르누 씨가 은퇴하신대. 바로 옆 빵집이 5월 31일에 문을 닫아."),
(H, "Ah, c'est dommage. Son pain aux noix, je vais le regretter.", "아, 아쉽네. 호두빵이 그리울 거야."),
(J, "Attends, c'est pas fini. Il cherche quelqu'un pour reprendre le bail.", "잠깐, 끝이 아니야. 임대차를 이어받을 사람을 찾고 있대."),
(H, "Le bail ? Pourquoi tu me dis ça ? Je fais du pain, moi ?", "임대차? 왜 그 얘길 나한테 해? 내가 빵을 만들어?"),
(J, "Non, mais si on prenait le local, on pourrait y mettre vingt places en plus.", "아니, 하지만 우리가 그 가게를 얻으면 자리를 스무 개 더 만들 수 있어."),
(H, "Vingt places en plus... Julien, tu as pris un café trop fort ce matin.", "자리가 스무 개 더... 쥘리앵, 오늘 아침 커피가 너무 진했나 보다."),
(J, "Je suis sérieux. Regarde, le mur du fond est mitoyen. On pourrait l'ouvrir.", "진심이야. 봐, 안쪽 벽이 맞닿아 있잖아. 뚫을 수 있어."),
(H, "Ouvrir un mur. Comme ça, un mardi matin. Et la structure de l'immeuble ?", "벽을 뚫는다고. 이렇게 화요일 아침에 불쑥. 건물 구조는?"),
(J, "M. Arnoux dit que c'est une cloison, pas un mur porteur. On peut visiter ce midi.", "아르누 씨 말로는 칸막이지 내력벽이 아니래. 오늘 점심에 볼 수 있어."),
(H, "Ce midi, c'est le coup de feu. Non. Cet après-midi, à quinze heures.", "점심엔 피크 타임이야. 안 돼. 오늘 오후 3시에."),
(J, "Parfait. Je lui téléphone. Tu vas voir, tu vas adorer.", "좋아. 전화할게. 두고 봐, 마음에 들 거야."),
(H, "Je n'ai pas dit que j'allais adorer. J'ai dit que j'allais regarder.", "마음에 든다고 한 게 아니야. 보러 간다고 했지."),
(None, "Quinze heures. Dans l'ancienne boulangerie, vide et poussiéreuse. Il reste un four à pain et un comptoir en zinc. Chloé mesure les murs avec un mètre ruban.", "오후 3시. 먼지가 쌓인 텅 빈 옛 빵집. 빵 굽는 화덕과 아연 카운터가 남아 있다. 클로에가 줄자로 벽을 재고 있다."),
(C, "Quarante-cinq mètres carrés, hauteur sous plafond trois mètres vingt. C'est beau, non ?", "45제곱미터에 천장 높이가 3미터 20이에요. 예쁘죠, 안 그래요?"),
(H, "Beau, mais froid. Il y a des fissures là-haut. Et ce sol, il est en mauvais état.", "예쁘지만 썰렁해. 저 위에 금이 갔고, 바닥은 상태가 안 좋아."),
(J, "Ça se refait. Un sol, une peinture, deux grandes fenêtres, et on retrouve l'âme du lieu.", "고치면 되지. 바닥, 페인트, 큰 창 두 개면 이곳의 분위기가 살아나."),
(C, "J'ai posé la question à M. Arnoux. Il demande trente mille euros pour reprendre le bail.", "아르누 씨한테 물어봤어요. 임대차를 넘겨받는 값으로 3만 유로를 원하세요."),
(H, "Trente mille euros pour reprendre un bail ! Et le loyer ?", "임대차 하나 넘겨받는 데 3만 유로라니! 월세는요?"),
(C, "Deux mille quatre cents euros par mois. Le propriétaire est M. Delmas, comme le nôtre.", "한 달에 2,400유로예요. 건물주는 우리 가게랑 같은 델마 씨고요."),
(H, "Delmas. Évidemment. Il fait toujours le tour de ses affaires.", "델마, 당연하지. 그분은 항상 자기 소유를 챙기니까."),
(J, "Il est plus aimable qu'avant, tu as remarqué ? Depuis qu'on a payé tous les arriérés.", "예전보다 상냥해졌지, 알아챘어? 밀린 월세를 다 낸 뒤로."),
(H, "Il est aimable parce qu'on paie. Ça ne veut pas dire qu'il nous fera des cadeaux.", "우리가 내니까 상냥한 거야. 선물을 주겠다는 뜻은 아니지."),
(C, "Pardon, que veut dire « les arriérés » ? C'est un mot que je n'ai jamais noté.", "죄송한데 « les arriérés »가 무슨 뜻이에요? 수첩에 적은 적 없는 단어예요."),
(H, "Ce sont les sommes qu'on devait et qu'on n'avait pas payées. Écris-le, ça te servira.", "내야 하는데 못 냈던 돈이야. 적어 둬, 도움이 될 거야."),
(J, "Il m'a dit qu'il était d'accord pour un nouveau bail de neuf ans. Si on se décide avant le quinze mai.", "나한테 9년짜리 새 임대차에 동의한다고 했어. 5월 15일 전에 결정하면."),
(H, "Avant le quinze. Donc dans onze jours. On nous met la pression.", "15일 전이면 11일 남았네. 압박하는군."),
(J, "Pas la pression, une occasion. Ça n'arrive pas deux fois dans une vie, un local collé à ton restaurant.", "압박이 아니라 기회야. 가게에 바로 붙은 점포는 평생 두 번 오지 않아."),
(C, "Je peux vous montrer un tableau ? J'ai passé la nuit sur un calcul. Je l'ai imprimé.", "표 하나 보여 드려도 될까요? 밤새 계산을 했어요. 인쇄해 왔어요."),
(H, "Tu as passé la nuit là-dessus ? Chloé, tu devrais dormir.", "그걸로 밤을 새웠다고? 클로에, 좀 자야지."),
(C, "Un peu. Mais regardez. Vingt places de plus, deux services, six jours par semaine.", "조금요. 하지만 보세요. 자리 스무 개 추가, 서비스 두 번, 주 6일이에요."),
(H, "Continue. À quel taux de remplissage ?", "계속해 봐. 좌석 점유율은 얼마로?"),
(C, "Soixante-dix pour cent, ce qui est prudent. Cela donne seize mille euros de chiffre d'affaires par mois.", "70퍼센트로, 보수적인 수치예요. 그러면 매출이 한 달에 1만 6천 유로예요."),
(J, "Seize mille ! C'est plus que le loyer des deux locaux réunis, multiplié par trois.", "1만 6천! 두 가게 월세를 합친 것의 몇 배인데."),
(H, "Calme-toi. Chiffre d'affaires, ce n'est pas bénéfice. Chloé, la suite.", "진정해. 매출은 이익이 아니야. 클로에, 다음."),
(C, "Moins le loyer, le personnel, les produits et les charges, il reste quinze cents euros par mois.", "월세, 인건비, 식재료, 각종 비용을 빼면 한 달에 1,500유로가 남아요."),
(H, "Quinze cents euros. Et l'investissement total ?", "1,500유로. 총 투자금은?"),
(C, "Cent vingt mille. Trente pour le bail, soixante pour les travaux, vingt pour le matériel, dix de réserve.", "12만 유로요. 임대권 3만, 공사 6만, 설비 2만, 예비비 1만이에요."),
(H, "Cent vingt mille. Et on rembourse combien par mois, sur huit ans ?", "12만 유로. 그럼 8년이면 매달 얼마씩 갚는데?"),
(C, "Environ mille quatre cents euros, avec les intérêts. Donc il reste cent euros.", "이자 포함 약 1,400유로예요. 그러니까 100유로가 남죠."),
(J, "Cent euros ! C'est peu, mais c'est positif. Et on aura vingt places en plus pour toujours.", "100유로라니! 적지만 플러스잖아. 그리고 자리 스무 개는 영원히 우리 거고."),
(H, "Cent euros par mois, Julien, pour un risque de cent vingt mille. Tu appelles ça positif ?", "쥘리앵, 한 달에 100유로를 얻자고 12만 유로 위험을 지는 거야. 그걸 플러스라고 해?"),
(J, "Je dis qu'on pourrait mieux faire. Avec un brunch tous les jours, ça monterait à trois mille.", "더 잘할 수 있다는 말이야. 매일 브런치를 하면 3천 유로까지 오를 수 있어."),
(H, "On pourrait. On pourrait aussi tout perdre. Je préfère regarder les deux côtés.", "그럴 수도 있지. 전부 잃을 수도 있고. 양쪽 다 보는 게 좋아."),
(None, "Dix-sept heures. Lucien arrive au Comptoir, Hélène lui a téléphoné. Il s'installe au bar, un verre de Brouilly à la main, et écoute le résumé de l'affaire.", "오후 5시. 엘렌이 전화한 뤼시앵이 콩투아르에 도착한다. 그는 브루이 한 잔을 들고 바에 앉아 사연을 듣는다."),
(L, "Une boulangerie, à côté ? Et cent vingt mille euros ? Eh bien, ma fille, tu as de l'appétit.", "옆집 빵집에, 12만 유로? 허, 우리 딸 식욕이 대단하구나."),
(H, "C'est Julien qui a de l'appétit, Papa. Moi, je regarde. Je fais mes comptes.", "식욕이 있는 건 쥘리앵이에요, 아빠. 저는 보기만 해요. 계산 중이고요."),
(L, "Ta mère disait toujours : « Les yeux plus gros que le ventre, ça finit mal. »", "네 엄마가 늘 말했지. « 눈이 배보다 크면 끝이 안 좋다. »"),
(J, "Lucien, vous me connaissez. Je ne suis pas fou. L'occasion est là, c'est tout.", "뤼시앵, 저를 아시잖아요. 저 미치지 않았어요. 기회가 왔을 뿐이에요."),
(L, "Je te connais, justement. Un garçon qui rêve en grand, c'est bien. Mais pas avec l'argent des autres.", "그래서 하는 말이다. 크게 꿈꾸는 청년은 좋지. 하지만 남의 돈으로는 안 돼."),
(H, "Papa, ce n'est pas l'argent des autres. Si on emprunte, c'est moi qui signe.", "아빠, 남의 돈이 아니에요. 대출을 받으면 서명하는 건 저예요."),
(L, "C'est pire. Si tu signes et si ça rate, c'est toi qui paies. Et c'est moi qui regarde.", "더 나쁘지. 네가 서명했는데 잘못되면 갚는 건 너고, 지켜보는 건 나야."),
(L, "Quand j'ai ouvert, en quatre-vingt-onze, j'avais trente places et trois dettes. J'en dormais mal.", "91년에 문을 열 때 나는 자리 서른 개와 빚 세 개가 있었다. 잠을 설쳤지."),
(J, "Et pourtant vous avez tenu trente-cinq ans. Alors le risque, ça paie parfois, non ?", "그래도 35년을 버티셨잖아요. 그러니 위험이 보답할 때도 있죠, 안 그래요?"),
(L, "Ça paie quand on ne met pas tous ses œufs dans le même panier, mon garçon.", "모든 달걀을 한 바구니에 담지 않을 때 보답하는 거란다."),
(H, "Mais ici, c'est exactement ça. Tous nos œufs sont dans le même panier : le Comptoir.", "하지만 지금이 바로 그렇잖아요. 우리 달걀은 전부 콩투아르라는 한 바구니에 있어요."),
(L, "Alors ne fais pas tomber le panier, ma fille. Voilà tout mon conseil.", "그럼 바구니를 떨어뜨리지 마라, 얘야. 내 조언은 그게 전부다."),
(C, "Monsieur Lucien, et si ça réussit ? Si ça marchait, vous seriez content ?", "뤼시앵 씨, 만약 성공하면요? 잘되면 기쁘시겠어요?"),
(L, "Si ça marchait, je serais le plus heureux des hommes. Mais l'espoir n'est pas un plan, ma petite.", "잘된다면 세상에서 제일 행복하겠지. 하지만 희망은 계획이 아니란다, 얘야."),
(H, "Il a raison. À supposer que tout aille bien, il faut quand même un plan pour le pire.", "아빠 말이 맞아. 모든 게 잘 돌아간다 쳐도, 최악을 대비한 계획은 필요해."),
(J, "Alors faisons-le, ce plan. Si les clients ne viennent pas, qu'est-ce qu'on fait ?", "그럼 그 계획을 세우자. 손님이 안 오면 어떻게 하지?"),
(H, "On ferme les vingt places et on garde un loyer de deux mille quatre cents euros. Voilà ce qu'on fait.", "스무 석을 닫고 월세 2,400유로를 계속 내는 거지. 그게 우리가 하는 일이야."),
(L, "Et si l'un de vous tombe malade ? Ou si un Atelier de Victor numéro deux ouvre en face ?", "너희 중 누가 아프기라도 하면? 아니면 빅토르 가게 2호점이 맞은편에 열리면?"),
(C, "Victor ne peut pas ouvrir en face : il est déjà en face. Mais il pourrait s'agrandir, lui aussi.", "빅토르 씨는 맞은편에 또 열 수 없어요. 이미 맞은편이니까요. 하지만 그분도 확장할 수 있겠죠."),
(L, "Tu vois, Hélène ? La petite pense comme un banquier. Elle me plaît.", "보이냐, 엘렌? 이 아이는 은행원처럼 생각하는구나. 마음에 든다."),
(C, "Merci, monsieur Lucien. Mais un banquier dirait peut-être non.", "고맙습니다, 뤼시앵 씨. 하지만 은행원이라면 안 된다고 할지도 몰라요."),
(H, "Un banquier dirait peut-être oui, justement. Mme Garnier m'a déjà fait comprendre qu'elle serait contente de nous aider.", "은행원은 오히려 된다고 할지도 몰라. 가르니에 부인이 도와주고 싶다는 뜻을 이미 내비쳤거든."),
(J, "Tu vois ! Les banques nous aiment, maintenant. Il y a un an, elles nous auraient refusé le crédit.", "봤지! 이제 은행이 우릴 좋아해. 1년 전에는 대출을 거절했을 텐데."),
(H, "Il y a un an, on aurait dû mourir de faim. On ne l'a pas fait, c'est tout.", "1년 전에 우린 굶어 죽었어야 했는지도 몰라. 안 죽었을 뿐이지."),
(L, "Tout de même. Si ta mère avait écouté son cœur, elle aurait acheté la boulangerie en mille neuf cent quatre-vingt-dix-huit.", "그래도 말이야. 네 엄마가 마음 가는 대로 했다면 1998년에 그 빵집을 샀을 거다."),
(H, "Maman voulait acheter la boulangerie ? Je ne le savais pas.", "엄마가 빵집을 사고 싶어 하셨다고요? 몰랐어요."),
(L, "Elle en rêvait. Elle voulait y faire un salon de thé. Je lui ai dit non, trop risqué.", "꿈꾸셨지. 거기다 티살롱을 열고 싶어 했어. 나는 너무 위험하다고 말렸단다."),
(J, "Ah ! Voilà qui change tout. Lucien, vous lui avez dit non, et vous le regrettez ?", "아! 이건 이야기가 달라지는데요. 뤼시앵, 안 된다고 하셨고 그걸 후회하세요?"),
(L, "Je ne regrette pas. Mais parfois, je me demande ce qui se serait passé si je l'avais écoutée.", "후회는 안 해. 하지만 가끔 그때 아내 말을 들었다면 어땠을까 생각한다."),
(H, "Si tu l'avais écoutée, on aurait été deux fois plus fatigués, voilà tout.", "그 말을 들으셨다면 우린 두 배 더 지쳤겠죠, 그뿐이에요."),
(L, "Peut-être. Mais deux fois plus fiers. Moi, je ne tranche pas, ma fille. C'est ton affaire.", "그럴지도. 하지만 두 배 더 자랑스러웠겠지. 나는 결론 안 내련다, 얘야. 네 일이니까."),
(None, "Dix-huit heures trente. Lucien est reparti. Julien, Hélène et Chloé s'assoient autour d'une table, avec le tableau de Chloé et trois cafés.", "저녁 6시 30분. 뤼시앵은 떠났다. 쥘리앵, 엘렌, 클로에가 클로에의 표와 커피 세 잔을 두고 테이블에 둘러앉는다."),
(C, "Je peux ajouter quelque chose ? J'ai une autre idée, moins chère.", "하나 덧붙여도 될까요? 돈이 덜 드는 다른 아이디어가 있어요."),
(H, "Une idée moins chère. Chloé, tu es ma préférée ce soir.", "돈이 덜 드는 아이디어라니. 클로에, 오늘 밤은 네가 최고야."),
(C, "Si on louait seulement la moitié du local ? Vingt-deux mètres carrés, dix places, un petit four.", "가게의 절반만 빌리면요? 22제곱미터에 열 석, 작은 오븐 하나요."),
(J, "Dix places au lieu de vingt. Ça divise l'investissement par deux, mais la rentabilité aussi.", "스무 석 대신 열 석이라. 투자금은 반으로 줄지만 수익성도 반이 돼."),
(C, "Pas forcément : le loyer baisse davantage. Il passerait à mille deux cents euros.", "꼭 그렇진 않아요. 월세가 더 많이 내려가요. 1,200유로가 될 거예요."),
(H, "Mais M. Arnoux veut vendre le bail en entier. Il ne le coupera pas en deux.", "하지만 아르누 씨는 임대권을 통째로 팔고 싶어 해. 둘로 나누진 않을 거야."),
(J, "Il le coupera si on lui offre la même somme. Je l'ai senti, ce matin, quand je lui ai parlé.", "같은 금액을 주면 나눌 거야. 오늘 아침에 얘기하면서 느꼈어."),
(H, "Tu l'as senti ? Julien, on signe des baux avec des feelings, maintenant ?", "느꼈다고? 쥘리앵, 이제 직감으로 임대 계약을 해?"),
(J, "Non, avec des chiffres. Mais les chiffres, ça se négocie. Les feelings, parfois, aussi.", "아니, 숫자로 해. 하지만 숫자도 협상할 수 있어. 때로는 감도 그렇고."),
(H, "Bon. Écoutez-moi tous les deux. Je vais être honnête.", "좋아. 둘 다 내 말 들어 봐. 솔직하게 말할게."),
(H, "Hier, on était en dette de cinquante-huit mille euros. On remboursait plus vite que prévu.", "어제까지 우린 5만 8천 유로의 빚이 있었어. 예상보다 빨리 갚고 있었지."),
(H, "Si je signe pour cent vingt mille, je recommence à zéro. Et je ne dors plus pendant huit ans.", "12만 유로에 서명하면 다시 처음부터야. 그러면 8년 동안 잠을 못 자."),
(J, "Mais si tu ne signes pas, tu te demanderas toute ta vie ce qui se serait passé.", "하지만 서명하지 않으면 평생 어떻게 됐을지 궁금할 거야."),
(H, "Peut-être. Mais on peut aussi vivre avec un regret. Ce n'est pas un drame, un regret.", "그럴지도. 하지만 후회와 함께 살 수도 있어. 후회는 비극이 아니야."),
(C, "Alors vous dites non ? Même à la moitié du local ?", "그럼 안 하시는 거예요? 가게 절반이라도요?"),
(H, "Je dis : pas comme ça. Pas cent vingt mille. Pas cette année.", "이렇게는 안 한다는 거야. 12만 유로는 안 돼. 올해는 아니고."),
(J, "Et si M. Arnoux accepte une solution intermédiaire ? Un contrat à l'essai, un an seulement ?", "아르누 씨가 중간 방안을 받아들이면? 1년짜리 시험 계약 같은 거요."),
(H, "Un an d'essai pour un bail commercial, ce n'est pas la loi. Mais je vais demander à Me Aubry.", "상업 임대에 1년 시험이란 법에 없어. 하지만 오브리 변호사님께 물어볼게."),
(C, "Vraiment ? Vous demandez, alors ? Donc c'est un peu oui ?", "정말요? 물어보신다고요? 그럼 조금은 긍정인가요?"),
(H, "Ça veut dire : je ne ferme pas la porte avant d'avoir vu l'autre côté du mur.", "벽 반대편을 보기 전에는 문을 닫지 않겠다는 뜻이야."),
(J, "Ça me va. Je prends « je ne ferme pas la porte » comme une victoire.", "난 괜찮아. « 문을 닫지 않는다 »를 승리로 칠게."),
(H, "Prends-le comme tu veux. Mais rien ne se signe avant le quinze, et pas sans mon accord.", "마음대로 생각해. 하지만 15일 전엔 아무것도 서명 안 하고, 내 동의 없이도 안 돼."),
(J, "C'est promis. Et si tu dis non, je ne bouderai pas plus d'une semaine.", "약속할게. 네가 안 된다고 해도 일주일 넘게 삐치진 않을게."),
(C, "Une semaine ? Avec toi, Julien, ce sera plutôt une journée.", "일주일이요? 쥘리앵은 그냥 하루면 풀릴 걸요."),
(H, "Vous êtes impossibles tous les deux. Chloé, tu as encore ton tableau ?", "둘 다 못 말려. 클로에, 표 아직 갖고 있어?"),
(C, "Oui, voilà. Avec trois scénarios : optimiste, réaliste, et catastrophe.", "네, 여기요. 낙관적, 현실적, 최악의 세 가지 시나리오가 있어요."),
(H, "Catastrophe, ça me plaît. Je commence par celui-là.", "최악이라, 마음에 드네. 그것부터 볼게."),
(J, "Évidemment. Elle commence toujours par la fin du film.", "역시 그렇지. 넌 항상 영화의 결말부터 봐."),
(C, "Et dans le scénario catastrophe, je propose de ne pas gaspiller les ressources. Un café par jour, pas plus.", "그리고 최악의 시나리오에서는 자원을 낭비하지 말자고 제안해요. 커피는 하루 한 잔, 그 이상은 안 돼요."),
(J, "Là, je ne signe pas. Un seul café, c'est vraiment la catastrophe.", "그건 서명 못 해. 커피 한 잔이라니, 그야말로 재앙이야."),
(H, "C'est pour ça que je ne me suis pas encore perdue. Allez, au travail, il est presque dix-neuf heures.", "그래서 아직 길을 잃지 않았지. 자, 일하자, 벌써 7시야."),
(None, "Dix-neuf heures quinze. La salle se remplit. Hélène, seule devant l'ardoise, regarde un instant le mur qui la sépare de l'ancienne boulangerie.", "저녁 7시 15분. 홀이 차기 시작한다. 혼자 칠판 앞에 선 엘렌이 옛 빵집과 자신을 가르는 벽을 잠시 바라본다."),
(J, "Tu penses toujours au mur ? Dis-moi à quoi tu penses.", "아직도 벽 생각해? 뭘 생각하는지 말해 봐."),
(H, "Je pense que si je dis oui, ce sera pour de bonnes raisons. Pas par peur de rater quelque chose.", "내가 된다고 하면 그건 좋은 이유 때문이어야 해. 뭔가를 놓칠까 봐 두려워서가 아니라."),
(J, "Alors prends ton temps. Mais demain, tu regardes le tableau avec Me Aubry, d'accord ?", "그럼 시간을 가져. 하지만 내일은 오브리 변호사랑 표를 같이 봐, 알았지?"),
(H, "D'accord. Et toi, demain, tu me prépares une autre idée. Plus petite. Plus à la mesure de nos épaules.", "알았어. 그럼 너는 내일 다른 아이디어를 준비해. 더 작고, 우리 어깨에 맞는 걸로."),
(J, "Une idée à la mesure de nos épaules... J'ai déjà quelque chose, en fait. Mais pas ce soir.", "우리 어깨에 맞는 아이디어라... 사실 이미 하나 있어. 하지만 오늘 밤은 아니야."),
(H, "Pourquoi pas ce soir ? Tu me fais peur.", "왜 오늘 밤은 안 돼? 무섭게 왜 이래."),
(J, "Parce qu'il faut du temps. Disons mardi prochain, après le service. Je t'invite à dîner.", "시간이 필요해서. 다음 주 화요일 서비스 끝나고 어때? 내가 저녁 살게."),
(H, "Tu m'invites ici, dans mon restaurant ? C'est Chloé qui nous servira ?", "내 가게에서 나를 초대한다고? 클로에가 서빙해 주는 거야?"),
(L, "Je ne suis pas invité ? Moi qui t'ai donné le conseil du panier ?", "나는 초대 안 받았니? 바구니 조언을 해 준 내가?"),
(J, "Vous êtes toujours invité, Lucien. Mais mardi, je dois parler à Hélène en tête à tête.", "뤼시앵은 언제나 초대받으셨어요. 하지만 화요일엔 엘렌과 단둘이 얘기해야 해요."),
(L, "En tête à tête ! Hum. Ça sent le mariage ou la faillite. Dans les deux cas, je viens.", "단둘이라! 흠, 결혼 아니면 파산 냄새가 나는구나. 어느 쪽이든 나는 간다."),
(H, "Papa ! Ça sent surtout la bonne bouffe. Allez, viens, je te sers un dernier verre.", "아빠! 무엇보다 맛있는 음식 냄새죠. 자, 오세요, 마지막 잔 하나 따라 드릴게요."),
(C, "Avec plaisir. Je vous mets à la table sept, celle de Mme Vasseur. Elle porte chance.", "기꺼이요. 바쉐 부인 자리인 7번 테이블로 모실게요. 행운을 가져다주거든요."),
(H, "Ne lui dis surtout pas. Elle nous réclamera des droits d'auteur.", "그분껜 절대 말하지 마. 저작권료를 달라고 하실 테니까."),
]

VOCAB = [
("A2", "Une occasion", "기회", "« Pas la pression, une occasion. » 좋은 기회. 중고 물건이라는 뜻도 있으니 문맥으로 구분. 이 화에서는 기회."),
("A2", "Un loyer", "월세", "« Deux mille quatre cents euros par mois. » le loyer 는 임대료. 숫자는 낭독하기 쉽게 단어로."),
("A2", "Mesurer", "재다", "« Chloé mesure les murs. » 길이·넓이를 재는 동사. un mètre ruban 은 줄자."),
("A2", "Une place", "좌석, 자리", "« Vingt places en plus. » 식당에서는 좌석 수를 가리킨다. 호텔·극장에서도 같다."),
("B1", "Un investissement", "투자", "« Et l'investissement total ? » 돈을 미래 이익을 위해 쓰는 것. investir 의 명사형."),
("B1", "Un risque", "위험", "« Pour un risque de cent vingt mille. » prendre un risque 는 위험을 감수한다. 반대: la sécurité."),
("B1", "Un taux de remplissage", "좌석 점유율", "« À quel taux de remplissage ? » 식당·호텔에서 채워진 자리의 비율. 70 % 는 soixante-dix pour cent."),
("B1", "Rembourser", "상환하다, 갚다", "« On rembourse combien par mois ? » 빌린 돈을 갚는다. un remboursement 은 상환."),
("B1", "Prudent(e)", "신중한, 보수적인", "« Soixante-dix pour cent, ce qui est prudent. » 위험을 피하는 태도나 보수적 추정."),
("B1", "Le chiffre d'affaires", "매출", "« Chiffre d'affaires, ce n'est pas bénéfice. » 매출(CA)과 이익(bénéfice)은 다르다. 경영의 기본 구분."),
("B2", "La rentabilité", "수익성", "« Ça divise l'investissement par deux, mais la rentabilité aussi. » 투자한 돈에 비해 얼마나 이익이 나는지를 뜻한다."),
("B2", "Un bail commercial", "상업 임대차", "« Un bail de neuf ans. » 프랑스 상점의 임대차는 흔히 3-6-9 형태. reprendre un bail 은 임대권을 이어받는 것."),
("B2", "Avoir les yeux plus gros que le ventre", "욕심이 능력보다 크다", "« Il ne faut pas avoir les yeux plus gros que le ventre. » 음식뿐 아니라 일에서도 과욕을 경계할 때. ↔ 정중: Ne pas voir trop grand."),
("B2", "Une cloison", "칸막이 벽", "« Une cloison, pas un mur porteur. » 건물을 지탱하지 않는 벽. le mur porteur 는 내력벽."),
("B2", "À supposer que + 접속법", "~라고 가정하면", "« À supposer que tout aille bien. » 가정을 세울 때의 격식 표현. aille(aller)는 접속법."),
("B2", "Trancher", "결단을 내리다", "« Moi, je ne tranche pas. » 선택지 중에서 결정한다는 뜻. 칼로 자르는 동사에서 나왔다."),
("B2", "Mettre la pression", "압박하다", "« On nous met la pression. » [구어] 상대에게 서두르라고 압력을 넣는다. ↔ 정중: On nous presse de décider."),
("C1", "Ça ne se fait pas deux fois dans une vie", "평생 두 번은 없는 일", "« Ça n'arrive pas deux fois dans une vie. » 기회를 강조하는 과장 표현. 설득용 구어."),
("C1", "Le plan de secours", "비상 계획", "« Un plan pour le pire. » plan B 라고도 한다. 위험 관리의 핵심 표현."),
("C1", "L'espoir n'est pas un plan", "희망은 계획이 아니다", "« Mais l'espoir n'est pas un plan, ma petite. » 의욕만으로는 안 된다는 속담 같은 표현. 경영 충고에 자주 쓰인다."),
("C1", "À la mesure de nos épaules", "우리 능력에 맞는", "« Une idée à la mesure de nos épaules. » 직역은 '어깨 치수에 맞는'. 자기 힘으로 감당할 수 있는 규모."),
("C1", "Un scénario catastrophe", "최악의 시나리오", "« Optimiste, réaliste, et catastrophe. » 최악의 경우를 가정한 계획. 투자 검토의 필수 항목."),
("C1", "Ce n'est pas un drame", "비극은 아니다", "« Ce n'est pas un drame, un regret. » 걱정을 덜어 주는 말. 구어에서는 C'est pas la fin du monde."),
]

GRAM = [
("B1", "si + 현재, 현재/미래 — 현실적 가정", "« Si on emprunte, c'est moi qui signe. » « Si tu signes et si ça rate, c'est toi qui paies. » 실현 가능한 가정은 si + 현재형, 결과는 현재·미래. « si » 뒤에 미래형은 쓰지 않는다."),
("B2", "si + 반과거, 조건법 현재 — 가정", "« Si on prenait le local, on pourrait y mettre vingt places. » « Si ça marchait, je serais le plus heureux des hommes. » 현재에 반대되거나 가능성이 낮은 가정. si 절은 반과거, 결과는 조건법 현재."),
("B2", "si + 대과거, 조건법 과거 — 지난 일 가정", "« Si ta mère avait écouté son cœur, elle aurait acheté la boulangerie. » 지나간 일의 가정. si + 대과거 + 조건법 과거(aurait + 과거분사). 후회와 상상을 말할 때 쓴다."),
("B2", "à supposer que + 접속법", "« À supposer que tout aille bien, il faut quand même un plan pour le pire. » 가정을 세울 때 접속법. « Je suppose que » + 직설법과 구별한다."),
("B2", "비교 구문 — plus que, moins de, davantage", "« C'est plus que le loyer. » « Le loyer baisse davantage. » « Ça divise l'investissement par deux. » 배수와 분수 표현: diviser par deux, multiplier par trois."),
("C1", "Et si ~ ? — 제안과 반문", "« Et si ça réussit ? » « Et si M. Arnoux accepte ? » 문두의 et si 는 가정과 제안을 동시에 던진다. 뒤에는 직설법 현재나 반과거가 온다."),
("C1", "pour + 명사 / de peur de + 부정사", "« Pas par peur de rater quelque chose. » 이유를 말할 때 par peur de + 부정사. 긍정 이유는 pour de bonnes raisons. 감정과 이유를 구분하는 표현."),
]

READ = [
("리에종 — cent_vingt, vingt_places, un_an", "« Vingt places » 는 /vɛ̃.plas/ 로 t 를 발음하지 않지만, « vingt euros » 는 /vɛ̃.t‿ø.ʁo/ 로 t 가 이어진다. « un an » /œ̃.nɑ̃/ 은 n 이 이어지는 엘리종 연습."),
("숫자 읽기 — 금액", "« 120 000 € » cent vingt mille euros, « 30 000 € » trente mille euros, « 2 400 € » deux mille quatre cents euros. mille 는 복수형이 없고, cent 는 뒤에 숫자가 오면 s 가 사라진다는 점도 확인."),
("호흡 구간 — 가정 문장", "« Si ça marchait, / je serais le plus heureux des hommes. / Mais l'espoir n'est pas un plan. » 가정절 뒤에서 짧게 쉬고, 결과절은 흐르듯이. 마지막 문장은 단호하게 끝을 내린다."),
("억양 — 의문과 망설임", "« Et si ça réussit ? » 는 끝을 올리고, « Je ne ferme pas la porte. » 는 낮고 단단하게 내린다. 같은 사람이 망설일 때와 결심할 때의 억양 차이를 비교한다."),
("비음 — rembourser, investissement, intérêts", "« rembourser » /ʁɑ̃.bu.ʁse/, « investissement » /ɛ̃.vɛs.tis.mɑ̃/, « intérêts » /ɛ̃.te.ʁɛ/. /ɑ̃/, /ɛ̃/, /ɔ̃/ 을 구별해 읽는다. 어말의 -ment 는 /mɑ̃/."),
("r — risque, rentabilité, rembourser", "r 이 어두에 오는 « risque » /ʁisk/, « rentabilité » /ʁɑ̃.ta.bi.li.te/. 혀뿌리로 가볍게 긁는 소리를 낸다. « prudent » /pʁy.dɑ̃/ 에서 r 이 자음 뒤에 올 때도 연습한다."),
]

CULTURE = [
("droit au bail — 상업 임대권의 양도", "프랑스에서 상점 임차인은 임대차를 이어받을 사람에게 '임대권(droit au bail)'을 팔 수 있고, 위치가 좋은 곳은 큰돈이 오간다. 이때 건물주의 동의와 새 계약 조건이 중요하다. 가게를 넓힐 때 옆 점포를 임대하는 방식은 파리 식당가에서 흔하다."),
("대출과 개인 보증 — 위험을 말하는 법", "소규모 식당의 대출은 사업주 개인의 보증을 요구하는 경우가 많다. 그래서 확장을 이야기할 때 가장 먼저 나오는 말은 '최악의 경우'다. 프랑스어에서는 si + 조건법으로 위험을 상상하고, 시나리오를 낙관·현실·최악 세 가지로 나누어 보는 것이 관례다."),
]

META = dict(part=5, ep=65, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="La tentation de s'agrandir", title_ko="확장의 유혹",
 place="콩투아르와 옆 옛 빵집 (5월 4일 화요일, 오전 9시 15분 ~ 저녁 7시 15분)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · Lucien Marchand (아버지)",
 wine="옆 빵집 임대로 20석 확장 투자(12만 유로) 검토, 위험과 수익성, 엘렌의 보류",
 focus="투자·위험 어휘, si 가정문 3종, à supposer que, 비교와 배수",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제66화 « Julien, associé » : 5월 11일 화요일, 쥘리앵이 준비한 다른 제안. 지분 20%, 계약 이야기.")
