# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, A, L = "Hélène", "Julien", "Me Aubry", "Lucien"
D = [
(None, "Mardi 11 mai, 22 h 45. Le dernier client est parti. Sur la table sept, deux assiettes de blanquette, une bouteille de Brouilly et une chandelle. Hélène et Julien dînent enfin.", "5월 11일 화요일 밤 10시 45분. 마지막 손님이 떠났다. 7번 테이블 위에 블랑케트 두 접시, 브루이 한 병, 촛불 하나. 엘렌과 쥘리앵이 마침내 저녁을 먹는다."),
(H, "Bon. On est seuls, on a mangé, et tu m'as fait attendre une semaine. Parle.", "자, 우리 둘뿐이고 밥도 먹었고, 넌 일주일이나 날 기다리게 했어. 말해 봐."),
(J, "D'accord. Mais promets-moi de m'écouter jusqu'au bout, sans m'interrompre.", "알았어. 하지만 끝까지 끊지 않고 들어 주겠다고 약속해."),
(H, "Je te le promets. Je ne promets pas de ne pas faire la tête.", "약속할게. 인상을 안 쓴다는 약속은 못 하지만."),
(J, "Voilà. Il y a un an, Armand m'a proposé un poste avec mille euros de plus par mois.", "자. 1년 전에 아르망이 월급 1,000유로를 더 주는 자리를 제안했지."),
(H, "Je m'en souviens. Tu as dit non fin octobre. Et je ne t'ai jamais bien remercié.", "기억해. 10월 말에 거절했잖아. 그런데 제대로 고맙다고 한 적이 없네."),
(J, "Ce n'est pas pour ça que je t'en parle. C'est pour te dire pourquoi j'ai dit non.", "그래서 꺼낸 얘기가 아니야. 내가 왜 거절했는지 말하려는 거야."),
(J, "J'ai dit non parce que ici, je me sens chez moi. Et parce que je veux construire quelque chose.", "여기가 내 집 같아서 거절했어. 그리고 뭔가를 만들고 싶으니까."),
(H, "Construire quoi, Julien ? Tu as déjà ta salle, ton équipe, tes habitués.", "뭘 만든다는 거야, 쥘리앵? 이미 홀도, 팀도, 단골도 있잖아."),
(J, "Mais rien de tout ça n'est à moi. Si demain tu vends, je n'ai plus rien.", "하지만 그중 어느 것도 내 것이 아니야. 내일 네가 팔면 난 아무것도 없어."),
(H, "Je ne vends pas. Tu le sais bien. Depuis le non à Faure, je ne vends plus.", "난 안 팔아. 알잖아. 포르에게 거절한 뒤로 팔 생각 없어."),
(J, "Je le sais. Et c'est justement pour ça que je te demande autre chose.", "알아. 바로 그래서 다른 걸 부탁하려는 거야."),
(H, "Quoi ? Une augmentation ? Parce que si c'est ça, on en parle lundi.", "뭔데? 월급 인상? 그거라면 월요일에 얘기하자."),
(J, "Non. Je veux devenir associé. Je veux des parts dans le Comptoir.", "아니. 동업자가 되고 싶어. 콩투아르의 지분을 갖고 싶어."),
(None, "Silence. Hélène pose sa fourchette. Dehors, un bus passe, et la chandelle vacille.", "침묵. 엘렌이 포크를 내려놓는다. 밖으로 버스가 지나가고 촛불이 흔들린다."),
(H, "Des parts. Dans le Comptoir. Dans la maison de Maman.", "지분이라니. 콩투아르의. 엄마의 집의."),
(J, "Pas dans la maison de Marthe. Dans la société. Le nom, la cuisine, c'est toi. Je le sais.", "마르트의 집이 아니라 회사의 지분이야. 이름도 요리도 네 거야. 알고 있어."),
(H, "Tu proposes combien ? Vingt, trente, cinquante pour cent ?", "얼마를 제안하는데? 20, 30, 50퍼센트?"),
(J, "Vingt pour cent. Pas plus. Tu gardes quatre-vingts, tu gardes le dernier mot.", "20퍼센트. 그 이상은 아니야. 80퍼센트는 네가 갖고 최종 결정권도 네가 가져."),
(H, "Et tu paies avec quoi ? Ce n'est pas un croissant, vingt pour cent d'une société.", "무엇으로 값을 치를 건데? 회사 지분 20퍼센트는 크루아상이 아니야."),
(J, "J'ai quelques économies. Et je peux m'engager à payer le reste sur trois ans.", "모아 둔 돈이 조금 있어. 나머지는 3년에 걸쳐 내겠다고 약속할 수 있어."),
(H, "Tu as demandé à un comptable ? Combien vaut la société, selon toi ?", "회계사한테 물어봤어? 네 생각엔 회사 가치가 얼마야?"),
(J, "J'ai vu M. Girard, ton expert-comptable. Il estime les parts à quatre-vingt-dix mille euros, dettes déduites.", "네 회계사 지라르 씨를 만났어. 부채를 뺀 지분 가치를 9만 유로로 보더라."),
(H, "Tu es allé voir M. Girard dans mon dos ?", "내 뒤에서 지라르 씨를 만났다고?"),
(J, "Non, devant toi : je lui ai dit que je venais te parler. Il m'a demandé de ne rien te cacher.", "아니, 네 앞에서야. 너한테 얘기하러 간다고 말했어. 아무것도 숨기지 말라고 하더라."),
(H, "Il a bien fait. Quatre-vingt-dix mille, vingt pour cent, ça fait dix-huit mille euros.", "잘했네. 9만 유로의 20퍼센트면 1만 8천 유로야."),
(J, "Dix-huit mille. J'en ai six mille. Je rembourse le reste par mensualités, cinq cents euros pendant deux ans.", "1만 8천이야. 6천은 있어. 나머지는 2년 동안 매달 500유로씩 갚을게."),
(H, "Cinq cents euros par mois, sur ton salaire. Tu te rends compte de ce que ça représente ?", "월급에서 매달 500유로야. 그게 무슨 뜻인지 알아?"),
(J, "Je m'en rends compte. Je ne ferai pas de folies cet été. Et je mangerai ici, c'est gratuit.", "알아. 이번 여름엔 흥청망청 안 쓸게. 그리고 여기서 먹으면 공짜잖아."),
(H, "Ha ! Tu es culotté. Mais je ne te dis pas non, je te préviens.", "하! 뻔뻔하네. 하지만 안 된다고 하진 않을 거야, 미리 말해 둬."),
(J, "Tu ne dis pas oui non plus. Je lis ton visage, tu sais. Il est très compliqué.", "그렇다고 된다고도 안 했어. 네 얼굴을 읽는다고. 아주 복잡하네."),
(H, "Il est compliqué parce que je suis heureuse et terrifiée en même temps.", "행복하면서 동시에 겁이 나서 복잡한 거야."),
(J, "Terrifiée de quoi ? De moi ?", "뭐가 겁나? 나?"),
(H, "De moi, Julien. Pendant trois ans, j'ai tout décidé seule. Je ne sais plus partager.", "나 자신이야, 쥘리앵. 3년 동안 혼자 다 결정했어. 나눌 줄 몰라."),
(J, "Alors on apprendra. Je ne veux pas te prendre ta place. Je veux porter une partie du sac.", "그럼 배우면 되지. 네 자리를 뺏고 싶은 게 아니야. 짐의 일부를 같이 지고 싶을 뿐이야."),
(H, "Une partie du sac... Tu sais que si on perd, tu perds aussi tes dix-huit mille euros ?", "짐의 일부라... 우리가 지면 네 1만 8천 유로도 잃는다는 거 알지?"),
(J, "Si on perd, je perds mon argent. Si on gagne, je gagne avec toi. C'est le principe.", "지면 내 돈을 잃고, 이기면 너랑 함께 얻어. 그게 원칙이지."),
(H, "Et si on se dispute ? Une vraie dispute, pas une dispute de salle.", "그리고 우리가 싸우면? 홀에서 하는 싸움이 아니라 진짜 싸움이라면."),
(J, "On a déjà eu des disputes. On a toujours fini par remettre la nappe.", "싸운 적 있잖아. 그래도 결국 식탁보를 다시 깔았어."),
(H, "Tu es désarmant. Écoute. Je n'ai pas besoin de réfléchir longtemps pour savoir.", "너 정말 무장 해제시키는 사람이네. 들어. 오래 생각하지 않아도 알아."),
(H, "Je sais que Maman t'aimait beaucoup. Elle t'aurait dit oui avant même que tu finisses ta phrase.", "엄마가 널 무척 좋아하셨어. 네 말이 끝나기도 전에 된다고 하셨을 거야."),
(J, "Elle ne m'a jamais connu, Hélène. Elle est morte avant que j'arrive.", "엘렌, 어머니는 나를 만난 적이 없어. 내가 오기 전에 돌아가셨잖아."),
(H, "C'est vrai. Mais elle t'aurait aimé. Elle aimait les gens qui restent.", "맞아. 하지만 널 좋아하셨을 거야. 남아 주는 사람을 좋아하셨으니까."),
(J, "Alors, c'est oui ?", "그럼, 된다는 거야?"),
(H, "C'est : voyons les papiers. Jeudi, on va chez Me Aubry. Je veux que tout soit écrit, clair, propre.", "서류부터 보자는 거야. 목요일에 오브리 변호사님께 가. 모든 게 문서로 분명하고 깔끔하길 원해."),
(J, "Jeudi. Parfait. Je n'ai jamais autant aimé le mot « notaire » de ma vie.", "목요일. 완벽해. 평생 이렇게 « 공증인 »이란 단어가 좋았던 적이 없어."),
(H, "Ce n'est pas un notaire, c'est un avocat. Tu devrais apprendre, si tu veux être associé.", "공증인이 아니라 변호사야. 동업자가 되려면 배워 둬."),
(None, "Samedi 15 mai, 11 h. Cabinet de Me Aubry, rue de Turbigo. Hélène et Julien sont assis devant un bureau en chêne. Un dossier bleu est posé entre eux.", "5월 15일 토요일 오전 11시. 튀르비고 가의 오브리 변호사 사무실. 엘렌과 쥘리앵이 참나무 책상 앞에 앉아 있다. 두 사람 사이에 파란 서류철이 놓여 있다."),
(A, "Bonjour, madame Marchand, bonjour, monsieur Benali. Merci d'être venus un samedi.", "안녕하세요, 마르샹 부인, 베날리 씨. 토요일에 와 주셔서 감사합니다."),
(H, "C'est nous qui vous remercions, maître. Vous nous recevez bien tôt pour un samedi.", "저희가 감사드립니다, 변호사님. 토요일치고 일찍 맞아 주시네요."),
(A, "Mon agenda est plein en semaine. Alors, entrons dans le vif du sujet : la cession de parts.", "평일은 일정이 가득 차 있어서요. 그럼 본론인 지분 양도로 들어가죠."),
(A, "Madame Marchand cède à monsieur Benali vingt pour cent des parts de la société, soit deux cents parts.", "마르샹 부인이 베날리 씨에게 회사 지분의 20퍼센트, 즉 200주를 양도합니다."),
(J, "Deux cents parts sur mille. Et le prix, c'est bien dix-huit mille euros ?", "1,000주 중 200주군요. 그리고 가격은 정말 1만 8천 유로인가요?"),
(A, "Dix-huit mille euros, dont six mille à la signature et douze mille en vingt-quatre mensualités.", "1만 8천 유로입니다. 서명 때 6천 유로, 나머지 1만 2천 유로는 24개월 분할이에요."),
(H, "Maître, si Julien ne paie pas une mensualité, qu'est-ce qui se passe ?", "변호사님, 쥘리앵이 분할금을 한 번 못 내면 어떻게 되나요?"),
(A, "Il y a un délai de trente jours. Passé ce délai, vous pouvez suspendre ses droits de vote.", "30일의 유예 기간이 있습니다. 그 기간이 지나면 의결권을 정지시킬 수 있어요."),
(J, "Mes droits de vote, mais pas mes dividendes ?", "의결권만 정지되고 배당은 그대로인가요?"),
(A, "Vos dividendes seraient mis en réserve jusqu'à régularisation. C'est une clause classique, monsieur.", "배당금은 정상화될 때까지 유보됩니다. 일반적인 조항이에요."),
(H, "Parlons de la gestion. Je reste gérante, seule. Julien est associé, pas cogérant.", "경영 얘기를 하죠. 저는 단독 대표로 남습니다. 쥘리앵은 동업자이지 공동 대표가 아니에요."),
(A, "C'est ce que prévoit le projet. Madame Marchand gère. Monsieur Benali dirige la salle.", "초안이 그렇게 돼 있습니다. 마르샹 부인이 경영하고 베날리 씨가 홀을 총괄하시죠."),
(A, "Toutefois, trois décisions nécessitent son accord : une vente du fonds, un emprunt supérieur à cinquante mille euros, ou une nouvelle association.", "다만 세 가지 결정에는 베날리 씨의 동의가 필요합니다. 영업권 매각, 5만 유로 초과 대출, 새 동업자의 영입이죠."),
(J, "Donc, par exemple, si Hélène voulait emprunter cent vingt mille euros pour agrandir...", "그러니까 예를 들어 엘렌이 확장하려고 12만 유로를 빌리려면..."),
(A, "Il faudrait votre signature, oui. Vous auriez un droit de veto sur ce type de décision.", "베날리 씨의 서명이 필요합니다. 그런 결정에는 거부권을 갖게 되시는 셈이죠."),
(H, "Voilà pourquoi j'ai refusé la boulangerie : je ne voulais pas qu'on se dispute dès le premier mois.", "그래서 빵집을 거절한 거야. 첫 달부터 싸우고 싶지 않았거든."),
(J, "Hélène, ça aurait été un bon test. Mais tu as bien fait, je crois.", "엘렌, 좋은 시험이 됐을 거야. 하지만 네가 잘 결정한 것 같아."),
(A, "J'ajoute deux clauses. Un : le droit de préemption. Si l'un de vous veut vendre ses parts, l'autre est prioritaire.", "조항 두 개를 덧붙입니다. 첫째, 우선매수권입니다. 한쪽이 지분을 팔고 싶으면 다른 쪽이 우선권을 갖습니다."),
(A, "Deux : la clause de sortie. Si monsieur Benali quitte l'entreprise, madame Marchand rachète ses parts au prix du moment.", "둘째, 퇴출 조항입니다. 베날리 씨가 회사를 떠나면 마르샹 부인이 그 시점의 가격으로 지분을 되사게 됩니다."),
(J, "Au prix du moment. Donc si le Comptoir vaut davantage, je récupère davantage.", "그 시점의 가격이라. 그럼 콩투아르 가치가 오르면 제가 돌려받는 돈도 늘어나겠네요."),
(A, "Exactement. C'est la logique d'un associé : vous partagez le risque et la valeur créée.", "정확합니다. 동업자의 논리죠. 위험과 만들어 낸 가치를 함께 나눕니다."),
(H, "Et la non-concurrence ? Je ne voudrais pas retrouver Julien à l'Atelier de Victor.", "경업 금지는요? 빅토르의 아틀리에에서 쥘리앵을 만나고 싶진 않아서요."),
(J, "Hélène ! Moi, chez Victor ? Je préférerais faire la plonge ici toute ma vie.", "엘렌! 내가 빅토르네에? 평생 여기서 설거지하는 게 낫지."),
(A, "Le projet prévoit deux ans et cinq kilomètres. C'est raisonnable pour un restaurant parisien.", "초안에는 2년, 반경 5킬로미터로 되어 있습니다. 파리 식당으로서는 합리적인 수준이에요."),
(J, "Deux ans, cinq kilomètres. Ça me va. Je ne compte pas partir de toute façon.", "2년에 5킬로미터요. 좋습니다. 어차피 떠날 생각이 없어요."),
(A, "Dernier point, plus personnel. Si l'un des deux meurt, que deviennent les parts ?", "마지막으로 조금 개인적인 문제입니다. 두 분 중 한 명이 사망하면 지분은 어떻게 되나요?"),
(H, "Maître... Vous posez ça avec un tel calme que ça glace.", "변호사님... 너무 담담하게 물으셔서 소름이 돋네요."),
(A, "Je pose la question parce que c'est mon métier. Les contrats protègent aussi les familles.", "그게 제 직업이라서 묻는 겁니다. 계약은 가족도 보호하니까요."),
(J, "Dans ce cas, je veux que mes parts reviennent à Hélène. Qu'elles restent dans la maison.", "그럴 경우 제 지분은 엘렌에게 돌아가길 원합니다. 가게 안에 남아야죠."),
(H, "Julien... Moi aussi, je veux qu'elles restent dans la maison. Mettons-le par écrit.", "쥘리앵... 나도 가게 안에 남기를 바라. 문서로 남기자."),
(A, "Bien. Je rédige un avenant sur ce point. Vous aurez le texte définitif lundi.", "알겠습니다. 이 점에 대해 부속 합의서를 작성하죠. 최종 문서는 월요일에 드리겠습니다."),
(H, "Maître, un dernier mot. Est-ce que je peux garder le nom, Le Comptoir de Marthe, à vie ?", "변호사님, 마지막으로 하나만요. 콩투아르 드 마르트라는 이름을 평생 지킬 수 있을까요?"),
(A, "Le nom est un actif de la société, mais une clause peut l'interdire à toute modification sans votre accord.", "이름은 회사의 자산이지만, 조항으로 귀하의 동의 없는 변경을 금지할 수 있습니다."),
(J, "Et j'insiste pour que cette clause soit écrite en gras. Je ne toucherai jamais au nom.", "그 조항은 굵은 글씨로 적어 달라고 요청합니다. 저는 절대 이름을 건드리지 않을 거예요."),
(A, "Je le note. Lundi, vous signez. D'ici là, relisez tout. Un contrat se lit à tête reposée.", "적어 두겠습니다. 월요일에 서명하시죠. 그때까지 전부 다시 읽어 보세요. 계약은 차분한 머리로 읽는 법입니다."),
(None, "Lundi 17 mai, 17 h. Le Comptoir est fermé. Lucien est assis au bar. Hélène et Julien reviennent du cabinet, un document paraphé dans la main.", "5월 17일 월요일 오후 5시. 콩투아르는 휴무다. 뤼시앵이 바에 앉아 있다. 엘렌과 쥘리앵이 서명한 문서를 손에 들고 사무실에서 돌아온다."),
(L, "Alors ? Vous avez signé, oui ou non ? J'ai attendu trois heures avec un seul verre.", "그래서? 서명했니, 안 했니? 한 잔만 놓고 세 시간 기다렸다."),
(H, "On a signé, Papa. Julien est associé à vingt pour cent.", "서명했어요, 아빠. 쥘리앵이 20퍼센트 동업자예요."),
(J, "Lucien, je vous promets de ne pas changer le menu de la blanquette. Jamais.", "뤼시앵, 블랑케트 메뉴는 바꾸지 않겠다고 약속드려요. 절대로."),
(L, "Je n'ai pas peur du menu, mon garçon. J'ai peur que tu ne te reposes jamais.", "메뉴는 걱정 안 한다, 젊은이. 네가 쉬질 못할까 봐 걱정이지."),
(J, "Associé ou pas, je suis comme ça. Je ferme la salle, je ferme les comptes, je ferme les yeux.", "동업자든 아니든 난 이런 사람이에요. 홀을 닫고 장부를 닫고 눈을 감죠."),
(L, "Je vais vous dire une chose, tous les deux. Marthe et moi, on a eu cette discussion en quatre-vingt-onze.", "너희 둘에게 한마디 하마. 마르트와 나는 91년에 이런 대화를 나눴단다."),
(H, "Quelle discussion, Papa ? Vous n'aviez pas d'associé.", "무슨 대화요, 아빠? 두 분은 동업자가 없었잖아요."),
(L, "Non, mais on s'est promis de ne jamais faire passer l'argent avant l'amitié. Gardez ça.", "없었지. 하지만 우리는 돈을 우정보다 앞세우지 않기로 약속했다. 그걸 간직해라."),
(J, "Je le garderai, Lucien. Je le garde déjà, je crois.", "간직하겠습니다, 뤼시앵. 이미 간직하고 있는 것 같아요."),
(H, "Alors on va boire à ça. Papa, sors les verres, je descends une bouteille de la cave.", "그럼 그걸 위해 한잔하죠. 아빠, 잔을 꺼내세요, 제가 지하 창고에서 한 병 가져올게요."),
(L, "Pas n'importe laquelle. Prends le Sancerre de quatre-vingt-quinze, celui de ta mère.", "아무 거나 말고, 95년산 상세르를 가져오너라. 네 엄마 것 말이다."),
(H, "Le Sancerre de Maman ? Tu es sûr ? On gardait cette bouteille pour une grande occasion.", "엄마의 상세르요? 확실해요? 큰 날을 위해 아껴 둔 병이잖아요."),
(L, "C'est une grande occasion. Un associé, ça ne s'invente pas tous les jours.", "큰 날이다. 동업자가 매일 생기는 건 아니니까."),
(None, "Quelques minutes plus tard. Trois verres de Sancerre sont alignés sur le comptoir. Julien prend l'ardoise et, avec une craie, écrit une ligne en bas.", "몇 분 뒤. 상세르 석 잔이 카운터 위에 나란히 놓였다. 쥘리앵이 칠판을 집어 분필로 맨 아래에 한 줄을 쓴다."),
(J, "Regarde, Hélène. J'ai écrit : « Hélène et Julien vous souhaitent un bon appétit. »", "봐, 엘렌. 이렇게 썼어. « 엘렌과 쥘리앵이 맛있게 드시길 바랍니다. »"),
(H, "Efface-moi ça, et écris plutôt : « Marthe, Hélène et Julien. » Dans cet ordre.", "그건 지우고 이렇게 써. « 마르트, 엘렌, 쥘리앵. » 이 순서로."),
(J, "Dans cet ordre. D'accord. Je te fais confiance. À Marthe.", "그 순서대로. 알았어. 널 믿어. 마르트를 위하여."),
(L, "À Marthe. Et à vous deux, vous qui l'avez ramenée dans cette salle.", "마르트를 위하여. 그리고 마르트를 이 홀로 다시 데려온 너희 둘을 위하여."),
(H, "Et à toi, Papa, qui nous as appris à ne jamais lâcher.", "그리고 우리에게 절대 포기하지 않는 법을 가르쳐 주신 아빠를 위하여."),
]

VOCAB = [
("A2", "Un associé", "동업자", "« Je veux devenir associé. » 회사에 지분을 갖고 함께 운영하는 사람. 직원(un employé)과 구분된다."),
("A2", "Signer", "서명하다", "« Lundi, vous signez. » une signature 는 서명. 서류 아래쪽에 하는 서명과 이니셜(parapher)을 구분."),
("A2", "Un contrat", "계약", "« Un contrat se lit à tête reposée. » 계약서를 읽을 때의 신중함을 말하는 속담 같은 표현."),
("A2", "Une économie", "저축", "« J'ai quelques économies. » 복수로 쓰면 모아 둔 돈. faire des économies 는 절약하다."),
("B1", "Une part", "지분, 몫", "« Vingt pour cent des parts. » 회사 자본의 한 몫. 상업 회사에서는 les parts sociales 라고 한다."),
("B1", "Une mensualité", "월 상환금", "« En vingt-quatre mensualités. » 매달 나누어 내는 금액. 대출·할부의 기본 어휘."),
("B1", "Un dividende", "배당금", "« Mes dividendes ? » 회사 이익 중 주주나 사원에게 나누어 주는 몫."),
("B1", "Rédiger", "작성하다", "« Je rédige un avenant. » 문서를 쓰는 격식 동사. 구어에서는 écrire."),
("B1", "Un droit de vote", "의결권", "« Suspendre ses droits de vote. » 회사 결정에 참여하는 권리. droit de veto 는 거부권."),
("B1", "Cacher", "숨기다", "« Il m'a demandé de ne rien te cacher. » ne rien cacher 는 아무것도 숨기지 않다. 투명성을 약속할 때."),
("B2", "Céder des parts", "지분을 양도하다", "« Madame Marchand cède vingt pour cent. » céder 는 권리·재산을 넘긴다. une cession 은 양도."),
("B2", "Un droit de préemption", "우선매수권", "« Le droit de préemption. » 팔려는 사람의 지분을 다른 쪽이 먼저 살 권리."),
("B2", "Une clause de sortie", "퇴출(탈퇴) 조항", "« La clause de sortie. » 동업자가 떠날 때 지분을 어떻게 처리하는지를 정한 조항."),
("B2", "La non-concurrence", "경업 금지", "« Deux ans et cinq kilomètres. » 계약 종료 뒤 일정 기간·지역에서 경쟁 사업을 하지 않기로 한 약정."),
("B2", "Un avenant", "계약 변경서, 부속 합의", "« Je rédige un avenant sur ce point. » 이미 있는 계약을 고치거나 보완하는 문서."),
("B2", "Être culotté(e)", "뻔뻔하다, 배짱 있다", "« Tu es culotté. » [구어] 대담하거나 염치없다는 뜻. 반쯤 감탄할 때도 쓴다. ↔ 정중: Vous avez de l'audace."),
("B2", "Dans mon dos", "내 뒤에서, 몰래", "« Dans mon dos ? » 직역은 '등 뒤에서'. 당사자 모르게 일을 꾸미는 느낌."),
("C1", "Paraphé(e)", "(약식) 서명한", "« Un document paraphé. » 서류 각 쪽에 이니셜로 서명하는 것. parapher 와 signer 는 다르다."),
("C1", "Entrer dans le vif du sujet", "핵심으로 들어가다", "« Entrons dans le vif du sujet. » 서론을 줄이고 본론으로. 격식 있는 대화·회의에서."),
("C1", "À tête reposée", "차분한 머리로", "« Un contrat se lit à tête reposée. » 급하지 않게 냉정하게 판단한다는 뜻. ↔ à chaud."),
("C1", "Porter une partie du sac", "짐의 일부를 지다", "« Je veux porter une partie du sac. » 책임을 나눈다는 은유적 구어 표현."),
("C1", "Ça ne s'invente pas", "지어낼 수 없는 일이다", "« Un associé, ça ne s'invente pas tous les jours. » 좀처럼 일어나지 않는 귀한 일이란 뜻의 구어 표현."),
("C1", "Faire passer A avant B", "B보다 A를 우선하다", "« Faire passer l'argent avant l'amitié. » 우선순위를 말하는 관용 구문. ne jamais 와 함께 쓰면 신념을 나타낸다."),
("C1", "Avoir un droit de veto", "거부권을 갖다", "« Vous auriez un droit de veto. » 결정을 막을 수 있는 권리. 소수 지분자 보호 조항에서 자주 쓰인다."),
]

GRAM = [
("A2", "미래 약속 — je te promets de + 부정사", "« Je te le promets. » « Je vous promets de ne pas changer le menu. » promettre de + 부정사는 약속의 기본 문형. 부정은 de ne pas + 부정사."),
("B1", "조건과 결과 — si + 현재, 현재/미래", "« Si on perd, je perds mon argent. Si on gagne, je gagne avec toi. » « Si l'un de vous veut vendre, l'autre est prioritaire. » 실현 가능한 가정을 말할 때 쓰는 가장 기본적인 문형."),
("B2", "조건법 과거 — elle t'aurait dit oui", "« Elle t'aurait dit oui avant même que tu finisses ta phrase. » « Elle t'aurait aimé. » 과거의 가정 결과를 말하는 aurait + 과거분사. 지금 없는 사람을 향한 그리움도 이 형태로 표현한다."),
("B2", "수동·비인칭 — il faudrait, il est prévu", "« Il faudrait votre signature. » « Le projet prévoit deux ans. » 계약 대화는 il faut 의 조건법으로 정중하게 요구한다. 단정하지 않고 부드럽게 알리는 방식이다."),
("B2", "pour que + 접속법 / j'insiste pour que", "« J'insiste pour que cette clause soit écrite en gras. » 목적·요구는 pour que + 접속법(soit). « Je veux que tout soit écrit. » 도 같은 접속법."),
("C1", "절대 부정 — ne… jamais / jamais… ne", "« Je ne toucherai jamais au nom. » « Jamais on ne… » ne jamais 는 동사를 사이에 둔다. 강한 약속·맹세에 쓰며 감정이 담긴다."),
("C1", "대명사 en / y — j'en ai six mille", "« J'en ai six mille. » en 은 de + 명사를 대신하는 대명사로 수량 뒤에 쓴다. « Je m'en rends compte. » « J'y pense. » 처럼 동사 구문에 맞는 대명사를 고른다."),
]

READ = [
("억양 — 감정과 격식의 전환", "« Des parts. / Dans le Comptoir. / Dans la maison de Maman. » 는 한 구절씩 끊어 낮게 읽으며 충격을 표현한다. 변호사의 « Bien. Je rédige un avenant. » 는 평탄하고 정확하게."),
("숫자 읽기 — 지분과 금액", "« 18 000 € » dix-huit mille euros, « 6 000 € » six mille euros, « 12 000 € » douze mille euros, « 500 € » cinq cents euros. « 20 % » 는 vingt pour cent. 퍼센트는 pour cent 두 단어로 읽는다."),
("리에종 — vingt_ans, cinq_cents_euros, c'est_un", "« Cinq cents euros » /sɛ̃.sɑ̃.z‿ø.ʁo/ 에서 cents 의 s 가 z 로 이어진다. « vingt-quatre mensualités » 에서는 vingt 의 t 가 발음된다. « Un associé » /œ̃.na.sɔ.sje/."),
("호흡 구간 — 계약 조항 낭독", "« Madame Marchand cède / à monsieur Benali / vingt pour cent des parts / de la société. » 의미 단위로 끊어 읽으면 긴 조항도 숨이 막히지 않는다. 마지막 구절에서 내린다."),
("u/ou — vous, nous, tout, du", "« Vous signez » 의 ou /u/ 는 입술을 둥글게 하고, « du, tu » 의 u /y/ 는 더 좁게 내민다. « Lundi, vous signez. » 로 ou/u 대비를 연습한다."),
("r — partager, risque, associé, gérante", "« partager » /paʁ.ta.ʒe/, « gérante » /ʒe.ʁɑ̃t/, « associé » 에서는 r 이 없다. 마지막 r 은 가볍게 낸다."),
("비음 — cinquante, vingt, dividende", "« vingt » /vɛ̃/, « cinquante » /sɛ̃.kɑ̃t/, « dividende » /di.vi.dɑ̃d/. 비음 모음은 뒤의 n 을 발음하지 않고 코로 공기를 보낸다."),
]

CULTURE = [
("SARL와 지분 — 프랑스의 소규모 식당 사업 구조", "프랑스의 가족 식당은 흔히 SARL(유한책임회사) 형태이고, 소유는 지분(parts sociales)으로 나뉜다. 직원이 20퍼센트 같은 소수 지분을 사서 동업자가 되는 일은 관례이며, 이때 변호사가 양도 계약과 주주 간 약정(pacte d'associés)을 작성한다."),
("계약서를 대하는 태도 — la confiance et l'écrit", "프랑스에서는 신뢰가 있어도 중요한 약속은 문서로 남긴다. « Les paroles s'envolent, les écrits restent. »(말은 날아가고 글은 남는다)라는 속담처럼, 가까운 사이일수록 분명히 적어 두는 것이 우정을 지키는 방법으로 여겨진다."),
]

META = dict(part=5, ep=66, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="Julien, associé", title_ko="쥘리앵, 동업자",
 place="콩투아르 7번 테이블(5월 11일 화 밤) · 오브리 변호사 사무실(5월 15일 토) · 콩투아르(5월 17일 월 오후)",
 chars="Hélène Marchand (주인 셰프, 지분 80%) · Julien Benali (홀 매니저, 지분 20%) · Me Aubry (변호사) · Lucien Marchand (아버지)",
 wine="쥘리앵이 지분 20%(1만 8천 유로)를 사 동업자가 되는 과정. 감정과 계약 조항이 함께 오가는 격식 대화.",
 focus="지분·계약 어휘, 약속 표현, si 문장과 조건법 과거, pour que+접속법, 격식 대화",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제67화 « Un client célèbre » : 5월 18일 화요일, 유명 배우가 조용히 예약 없이 찾아온다. 프라이버시를 지키는 완곡한 응대.")
