# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, F = "Hélène", "Lucien", "Julien", "Dr Fabre"
D = [
(None, "Mardi 8 juin, 11 h 20. Au Comptoir, on prépare le déjeuner. Lucien, assis à la table du fond, écosse des petits pois. Hélène goûte le velouté. Julien dresse les tables.", "6월 8일 화요일 오전 11시 20분. 점심 준비 중인 콩투아르. 뤼시앵은 안쪽 테이블에 앉아 완두콩을 까고 있다. 엘렌은 벨루테를 맛보고, 쥘리앵은 테이블을 차린다."),
(L, "Regarde-moi ces petits pois, Hélène. Mieux que ça, tu meurs.", "엘렌, 이 완두콩 좀 봐라. 이보다 좋을 순 없다."),
(H, "Papa, ils viennent de chez Bastide. Ils sont toujours beaux.", "아빠, 바스티드네 거잖아요. 늘 좋죠."),
(L, "Ils sont beaux parce que c'est moi qui les écosse.", "내가 까니까 좋은 거지."),
(J, "Lucien, t'en as écossé deux kilos. Tu veux qu'on te fasse un contrat ?", "뤼시앵, 벌써 2킬로나 깠어. 계약서라도 써 줄까?"),
(L, "Un contrat ? J'ai été patron pendant trente-cinq ans. Je ne signe plus rien.", "계약서? 내가 35년을 사장 했어. 이제 아무 데도 서명 안 해."),
(H, "Papa, t'es tout pâle. Ça va ?", "아빠, 얼굴이 하얘요. 괜찮아요?"),
(L, "Ça va, ça va. J'ai juste chaud. Il fait lourd ce matin.", "괜찮아, 괜찮아. 좀 덥네. 오늘 아침 날씨가 후텁지근하구나."),
(J, "Il fait vingt-deux degrés. C'est pas la canicule, quand même.", "22도야. 아무리 그래도 폭염은 아니지."),
(L, "Alors c'est l'âge qui chauffe, mon petit.", "그럼 나이가 열을 내는 거겠지, 얘야."),
(H, "T'as mangé quelque chose, ce matin ?", "오늘 아침에 뭐 좀 먹었어요?"),
(L, "Un café et une demi-tartine. Un vrai repas de roi.", "커피랑 빵 반 쪽. 임금님 식사지."),
(H, "Un repas de moineau, oui. Je te sers un verre d'eau.", "참새 식사겠죠. 물 한 잔 따라 줄게요."),
(L, "Je suis juste un peu essoufflé. J'ai le cœur qui bat vite. Ça me prend depuis quelques jours.", "그냥 숨이 좀 차서. 심장이 빨리 뛰네. 며칠 전부터 이래."),
(H, "Quelques jours ? Depuis quand, exactement ?", "며칠이요? 정확히 언제부터요?"),
(L, "Depuis dimanche. Ou jeudi, je sais plus. C'est rien, des palpitations.", "일요일부터. 아니면 목요일. 잘 모르겠다. 별거 아냐, 두근거리는 거지."),
(H, "Des palpitations ! Et tu m'as rien dit ? T'as vu un médecin ?", "두근거림이라고요! 말도 안 했어요? 병원은 갔어요?"),
(L, "Pour quoi faire ? Un médecin, ça te trouve toujours quelque chose.", "뭐하러? 의사는 어떻게든 뭔가를 찾아내는 법이다."),
(H, "Papa !", "아빠!"),
(L, "Attends... Oh là là. Ça tourne, Hélène. J'ai la tête qui...", "잠깐... 아이고. 빙글빙글 도는구나, 엘렌. 머리가..."),
(None, "Lucien s'affaisse sur la banquette. La cuillère tombe par terre.", "뤼시앵이 긴 의자 위로 쓰러진다. 숟가락이 바닥에 떨어진다."),
(H, "Papa ! Papa, tu m'entends ? Julien !", "아빠! 아빠, 내 말 들려요? 쥘리앵!"),
(J, "J'arrive ! Il respire ? Mets-le sur le côté !", "갈게! 숨은 쉬어? 옆으로 눕혀!"),
(H, "Il respire, il respire ! Il a les yeux fermés. Papa, réponds-moi !", "숨 쉬어, 숨 쉬어! 눈을 감고 있어. 아빠, 대답해요!"),
(J, "Je prends son pouls... Putain, il est complètement irrégulier.", "맥을 짚어 볼게... 젠장, 맥이 완전히 불규칙해."),
(H, "Appelle le quinze ! Vite !", "15번에 전화해! 빨리!"),
(J, "Allô, le quinze ? Un homme de soixante-douze ans vient de faire un malaise.", "여보세요, 15번이죠? 일흔두 살 남성이 방금 쓰러졌습니다."),
(J, "Il a perdu connaissance. Il respire, mais son pouls est irrégulier.", "의식을 잃었어요. 숨은 쉬는데 맥이 불규칙합니다."),
(H, "Dis-leur de se dépêcher ! Dis-leur que c'est mon père !", "서두르라고 말해! 우리 아빠라고 말해!"),
(J, "Rue Saint-Maur, dans le onzième, au Comptoir de Marthe. Oui, je reste en ligne.", "11구 생모르 가, 콩투아르 드 마르트예요. 네, 끊지 않고 있겠습니다."),
(L, "Qu'est-ce qui se passe ? Pourquoi je suis par terre ?", "무슨 일이냐? 내가 왜 바닥에 있지?"),
(H, "Bouge pas, Papa. Les secours arrivent. Respire doucement.", "움직이지 마요, 아빠. 구급대가 오고 있어요. 천천히 숨 쉬어요."),
(L, "Pas de bruit... Les clients vont arriver...", "소란 피우지 마라... 손님들이 곧 올 텐데..."),
(J, "Y a pas de clients, Lucien. Tais-toi et respire.", "손님은 아직 없어, 뤼시앵. 말하지 말고 숨이나 쉬어."),
(None, "Dix minutes plus tard, le SAMU emmène Lucien sur un brancard. Hélène enfile sa veste.", "10분 뒤, 응급의료팀이 뤼시앵을 들것에 실어 간다. 엘렌이 재킷을 입는다."),
(H, "Je pars avec lui. Je peux pas le laisser tout seul.", "아빠랑 같이 갈게. 혼자 둘 순 없어."),
(J, "Vas-y. Je m'occupe du service, et Karim tient la cuisine. Je t'apporte ton sac après.", "가. 홀은 내가 맡고, 주방은 카림이 맡을게. 네 가방은 이따 가져다줄게."),
(H, "Ne ferme pas le restaurant. Papa détesterait ça.", "가게 문은 닫지 마. 아빠가 제일 싫어할 거야."),
(None, "Quinze heures dix, couloir des urgences. Hélène est assise, les mains serrées. Julien arrive avec un sac.", "오후 3시 10분, 응급실 복도. 엘렌이 두 손을 꼭 쥐고 앉아 있다. 쥘리앵이 가방을 들고 온다."),
(J, "Voilà ton sac, ton chargeur et un sandwich. Mange.", "여기 가방, 충전기, 그리고 샌드위치. 먹어."),
(H, "J'ai pas faim.", "배 안 고파."),
(J, "Je t'ai pas demandé si t'avais faim. Mange.", "배고프냐고 안 물었어. 먹으라고."),
(H, "Et le service ? Ça s'est bien passé ?", "서비스는? 잘 끝났어?"),
(J, "Quarante couverts, personne a rien remarqué. Karim a assuré. Chloé a pleuré dans la chambre froide, et après elle a servi comme une pro.", "마흔 명 받았고, 아무도 눈치 못 챘어. 카림이 잘 해냈고, 클로에는 냉장실에서 울다가 그다음엔 프로처럼 서빙했어."),
(H, "Ça fait quatre heures qu'on attend. Personne me dit rien.", "네 시간째 기다리는데 아무도 말을 안 해 줘."),
(J, "Ils font des examens. Ça prend du temps, c'est normal.", "검사 중이잖아. 시간이 걸리는 게 당연해."),
(H, "Et si c'était grave ? J'aurais dû m'en rendre compte !", "심각한 거면 어떡해? 내가 알아챘어야 했는데!"),
(J, "Arrête. T'es pas médecin. Et lui t'a rien dit, tu l'as dit toi-même.", "그만해. 넌 의사가 아니잖아. 아저씨가 너한테 말을 안 한 거고, 네가 직접 그랬잖아."),
(H, "Il m'a caché ça pendant des jours. Je vais l'étrangler.", "며칠이나 숨겼어. 목을 조를 거야."),
(J, "Ça, c'est bon signe. T'es en colère, donc tu vas mieux.", "그거 좋은 신호야. 화가 난다는 건 괜찮아지고 있다는 거지."),
(H, "Très drôle.", "아주 웃기네."),
(F, "Madame Marchand ? Docteur Fabre, je suis cardiologue. Vous êtes la fille de monsieur Marchand ?", "마르샹 씨? 심장내과 의사 파브르입니다. 마르샹 선생님의 따님이시죠?"),
(H, "Oui. Comment va-t-il ? Dites-moi franchement.", "네. 아버지는 어떠세요? 솔직하게 말씀해 주세요."),
(F, "Il est stable. Je tiens à vous rassurer tout de suite : il n'y a pas de danger immédiat.", "안정적입니다. 먼저 안심시켜 드리고 싶은데, 당장의 위험은 없습니다."),
(H, "Ce n'est pas un infarctus ?", "심근경색은 아닌가요?"),
(F, "Non. L'électrocardiogramme et la prise de sang sont clairs : le cœur n'est pas abîmé.", "아닙니다. 심전도와 혈액검사 결과가 분명해요. 심장 자체는 손상되지 않았습니다."),
(F, "Mais il a un trouble du rythme. Ça s'appelle une fibrillation auriculaire.", "다만 부정맥이 있습니다. 심방세동이라고 부릅니다."),
(H, "Ça veut dire quoi, en français normal ?", "쉬운 말로 하면 무슨 뜻이에요?"),
(F, "Le cœur bat trop vite et de façon désordonnée. Parfois le sang circule mal, et on fait un malaise.", "심장이 너무 빠르고 불규칙하게 뜁니다. 가끔 피가 잘 돌지 않아서 쓰러지기도 하죠."),
(J, "Et ça se soigne ?", "치료는 되나요?"),
(F, "Très bien, oui. On va le mettre sous traitement : un médicament pour ralentir le cœur, et un anticoagulant.", "네, 잘 됩니다. 약물 치료를 할 겁니다. 심장을 늦추는 약과 항응고제요."),
(H, "Un anticoagulant ? C'est pour éviter les caillots ?", "항응고제요? 혈전을 막으려는 건가요?"),
(F, "Exactement, vous avez bien compris. Ça réduit le risque d'AVC.", "맞습니다, 잘 이해하셨어요. 뇌졸중 위험을 줄여 줍니다."),
(H, "Il faudra l'opérer ?", "수술해야 하나요?"),
(F, "Pas pour l'instant. Si le traitement ne suffit pas, on pourra faire une cardioversion : un petit choc électrique, sous anesthésie légère.", "지금은 아닙니다. 약으로 충분하지 않으면 전기충격 치료, 즉 심율동전환을 할 수 있습니다. 가벼운 마취를 하고요."),
(H, "Un choc électrique... sur mon père ?", "전기충격이라니... 우리 아빠한테요?"),
(F, "Je comprends votre inquiétude. C'est court et très courant. Ne vous alarmez pas d'avance.", "걱정되시는 거 이해합니다. 짧고 아주 흔한 시술이에요. 미리 겁먹지 마세요."),
(H, "Il va rester combien de temps ici ?", "아버지는 여기 얼마나 계셔야 하죠?"),
(F, "On le garde en observation cinq ou six jours, en cardiologie, sous scope.", "닷새나 엿새쯤 심장내과에서 모니터를 달고 경과를 지켜볼 겁니다."),
(J, "Le scope, c'est la machine avec les petits bips ?", "모니터라면, 삑삑 소리 나는 그 기계요?"),
(F, "Oui, elle surveille son rythme jour et nuit. Un bip régulier, c'est une bonne nouvelle.", "네, 밤낮으로 심장 박동을 지켜봅니다. 삑 소리가 규칙적이면 좋은 소식이죠."),
(H, "Il avait des palpitations depuis plusieurs jours. Il m'a rien dit.", "며칠 전부터 두근거렸대요. 저한테는 아무 말도 안 했고요."),
(F, "C'est très fréquent. Les patients minimisent. Il a eu de la chance d'être entouré.", "아주 흔합니다. 환자들은 대수롭지 않게 넘기거든요. 곁에 사람이 있어서 운이 좋으셨어요."),
(H, "Il travaille encore tous les jours au restaurant. Moi aussi, d'ailleurs.", "아빠는 지금도 매일 가게에 나와요. 사실 저도 그렇고요."),
(F, "Alors il faudra lever le pied. Tous les deux, peut-être.", "그럼 속도를 늦추셔야겠네요. 어쩌면 두 분 다요."),
(J, "On peut le voir ?", "뵐 수 있나요?"),
(F, "Il vient de se réveiller. Cinq minutes, pas plus. Il est fatigué, mais il pose déjà beaucoup de questions.", "방금 깼습니다. 5분만요. 피곤해하시지만 벌써 질문이 많으세요."),
(H, "Ça, c'est bon signe.", "그건 좋은 신호네요."),
(F, "Oui. Il m'a demandé s'il avait droit à un verre de Brouilly le soir.", "네. 저녁에 브루이 한 잔 해도 되냐고 물으셨어요."),
(H, "Alors c'est bien mon père.", "그럼 우리 아빠가 맞네요."),
(F, "Allez-y. Il est entre de bonnes mains, je vous le promets.", "가 보세요. 믿을 만한 손에 있으니 걱정 마세요, 약속드립니다."),
(H, "Merci, docteur. Merci beaucoup.", "감사합니다, 선생님. 정말 감사합니다."),
(None, "Chambre 412, service de cardiologie. Lucien est allongé, relié à un scope. Les bips sont réguliers.", "심장내과 412호 병실. 뤼시앵이 모니터에 연결된 채 누워 있다. 삑 소리가 규칙적이다."),
(L, "Ah, voilà ma fille et mon deuxième fils.", "아, 내 딸과 둘째 아들이 왔구나."),
(J, "Salut, Lucien. Tu nous as fait une sacrée peur.", "안녕, 뤼시앵. 정말 간 떨어지는 줄 알았어."),
(L, "Moi aussi, tu sais. J'ai cru que j'allais finir au Père-Lachaise avant le dessert.", "나도 그랬어. 디저트도 먹기 전에 페르라셰즈에 가는 줄 알았다."),
(H, "Ne plaisante pas avec ça, Papa. S'il te plaît.", "그런 걸로 농담하지 마요, 아빠. 제발요."),
(L, "Pardon, ma grande. C'est ma façon d'avoir moins peur.", "미안하다, 얘야. 이게 내가 덜 무서워하는 방법이야."),
(H, "Pourquoi tu m'as rien dit pour les palpitations ?", "두근거린다는 얘기를 왜 안 했어요?"),
(L, "Parce que je savais que tu ferais cette tête-là.", "네가 그런 얼굴을 할 줄 알았으니까."),
(H, "Quelle tête ?", "무슨 얼굴이요?"),
(L, "Celle de ta mère, quand elle s'inquiétait pour moi.", "네 엄마가 나 때문에 걱정할 때 짓던 얼굴 말이다."),
(H, "J'ai eu tellement peur, Papa. J'ai cru que...", "너무 무서웠어요, 아빠. 난 또..."),
(L, "Viens là. Je suis là, tu vois ? Un vieux cœur, ça se répare. Pas la peine de pleurer.", "이리 와. 나 여기 있잖니. 늙은 심장도 고치면 돼. 울 필요 없다."),
(H, "Je pleure pas. J'ai un cil dans l'œil.", "안 울어요. 속눈썹이 눈에 들어갔어요."),
(J, "Un cil dans les deux yeux, alors.", "그럼 두 눈 다 들어갔나 보네."),
(L, "Les Marchand pleurent comme ils cuisinent : sans en parler.", "마르샹 집안 사람들은 요리하는 것처럼 울지. 말없이."),
(H, "Le docteur dit qu'il faut lever le pied. Toi, et moi aussi.", "의사 선생님이 속도를 늦추래요. 아빠도, 저도요."),
(L, "Le docteur a raison. À quelque chose malheur est bon : au moins, je me repose.", "의사 말이 맞다. 불행도 쓸모가 있는 법이지. 적어도 쉬게 되잖니."),
(J, "Toi, te reposer ? Je demande à voir.", "네가 쉰다고? 두고 봐야 알겠는데."),
(L, "Chassez le naturel, il revient au galop. Dès demain, je veux mon journal et mon café.", "타고난 성격은 쫓아내도 말 타고 돌아오는 법. 내일부터 신문이랑 커피를 달라고 할 거다."),
(H, "Pas de café fort. Et pas de Brouilly avant l'accord du docteur.", "진한 커피는 안 돼요. 의사 선생님 허락 전엔 브루이도 안 되고요."),
(L, "Alors c'est la prison.", "그럼 감옥이구나."),
(J, "C'est l'hôpital, Lucien. Les prisonniers ont droit à une promenade, au moins.", "병원이야, 뤼시앵. 죄수도 산책은 시켜 주잖아."),
(L, "Et le service ? Les tables du déjeuner ?", "그런데 서비스는? 점심 손님들은?"),
(J, "Tout s'est bien passé. Karim a assuré, Chloé aussi.", "다 잘 끝났어. 카림도 클로에도 잘했어."),
(L, "Et la blanquette ?", "블랑케트는?"),
(H, "Elle était parfaite. Personne n'a su que tu étais ici.", "완벽했어요. 아빠가 여기 있는 줄 아무도 몰랐어요."),
(L, "Tu mens mal, ma fille. Il y a eu des questions, forcément.", "거짓말이 서툴구나, 얘야. 틀림없이 누가 물었겠지."),
(J, "Mme Vasseur a téléphoné. Elle te fait dire de ne pas faire le malin.", "바세르 부인이 전화했어. 잘난 척하지 말라고 전해 달래."),
(L, "Cette vieille chipie ! Elle m'enterre, et moi je suis encore là.", "그 심술쟁이 할망구! 나를 묻어 버리려 하는데 난 아직 여기 있다."),
(H, "Je reste ici cette nuit. Je dormirai dans le fauteuil.", "오늘 밤은 여기 있을게요. 의자에서 잘 거예요."),
(L, "Non. Tu rentres dormir dans un vrai lit. Demain, il y a le service.", "안 된다. 집에 가서 제대로 된 침대에서 자거라. 내일 서비스가 있잖니."),
(H, "Mais Papa...", "하지만 아빠..."),
(L, "Pas de mais. Un chef qui n'a pas dormi, ça sale la soupe.", "'하지만'은 없다. 잠 못 잔 요리사는 수프에 소금을 쏟기 마련이야."),
(J, "Il a raison. Je te ramène, et je reviens demain avec des vêtements propres pour lui.", "아저씨 말이 맞아. 내가 데려다줄게, 내일 아저씨 갈아입을 옷 가지고 다시 올게."),
(L, "Hélène, écoute-moi. J'ai eu le temps de réfléchir, avec tous ces fils partout.", "엘렌, 들어 봐라. 온몸에 선을 붙이고 누워 있는 동안 생각할 시간이 있었어."),
(H, "Réfléchir à quoi ?", "무슨 생각이요?"),
(L, "À ta mère. Et à son carnet. Samedi, apporte-le-moi.", "네 엄마 생각. 그리고 그 노트 생각. 토요일에 그걸 가져다주렴."),
(H, "Le carnet de Maman ? Pourquoi ?", "엄마 노트요? 왜요?"),
(L, "J'ai des choses à te dire que je n'ai jamais su dire. Pas ce soir, je suis trop fatigué.", "한 번도 제대로 말하지 못한 얘기를 해 주고 싶다. 오늘 밤은 너무 피곤하구나."),
(H, "D'accord, Papa. Samedi, je te l'apporte.", "알겠어요, 아빠. 토요일에 가져올게요."),
(J, "L'heure des visites est terminée. L'infirmière nous regarde de travers.", "면회 시간이 끝났어. 간호사가 우리를 곁눈질로 보고 있네."),
(H, "Dors bien, Papa. Je t'appelle demain matin.", "푹 자요, 아빠. 내일 아침에 전화할게요."),
(L, "Et dis à Karim de ne pas trop saler. Je le saurai.", "그리고 카림한테 소금 너무 치지 말라고 전해라. 난 알 수 있으니까."),
]

VOCAB = [
("A2", "Il fait lourd ce matin.", "오늘 아침은 후텁지근하다.", "날씨가 무겁고 습할 때. Lucien이 어지러움 직전에 둘러댄 말. 〈Il fait chaud〉보다 습한 느낌."),
("A2", "Mange. / Respire doucement.", "먹어. / 천천히 숨 쉬어.", "명령형 tu. 위급 상황에서 가까운 사람에게 짧게 지시한다. Julien은 샌드위치 앞에서도 〈Mange.〉 한 마디."),
("B1", "faire un malaise", "(갑자기) 몸이 안 좋아 쓰러지다", "〈Un homme vient de faire un malaise.〉 신고 전화의 정석. 〈perdre connaissance〉(의식을 잃다)와 같이 쓴다."),
("B1", "le pouls", "맥박", "〈Je prends son pouls.〉 — 맥을 짚다. 〈Son pouls est irrégulier.〉 처럼 형용사와 함께."),
("B1", "les palpitations", "두근거림, 심계항진", "〈J'ai le cœur qui bat vite.〉 〈des palpitations〉 증상을 말할 때. 의사에게 말할 때는 후자가 정확하다."),
("B1", "Appelle le quinze !", "15번(SAMU)에 전화해!", "프랑스의 응급의료 번호는 15(SAMU), 소방 18, 통합 112. 〈Allô, le quinze ?〉 로 시작한다."),
("B1", "[구어] Je t'ai pas demandé si t'avais faim.", "배고프냐고 안 물었어.", "ne 생략 + t'as 축약. ↔ 정중: 〈Je ne vous ai pas demandé si vous aviez faim.〉"),
("B2", "perdre connaissance / reprendre connaissance", "의식을 잃다 / 되찾다", "〈Il a perdu connaissance.〉 신고·진료에서 자주 쓰는 표현. 구어에서는 〈tomber dans les pommes〉(기절하다)도 쓴다."),
("B2", "les urgences / le SAMU / un brancard", "응급실 / 응급의료팀 / 들것", "〈Le SAMU emmène Lucien sur un brancard.〉 〈aux urgences〉 처럼 복수형 정관사. 〈SAMU〉 는 '사뮈'로 읽는다."),
("B2", "un électrocardiogramme (un ECG) / une prise de sang", "심전도 / 채혈", "〈L'électrocardiogramme et la prise de sang sont clairs.〉 의사가 검사 결과를 설명할 때. 〈faire une prise de sang〉."),
("B2", "un infarctus / un AVC", "심근경색 / 뇌졸중", "〈Ce n'est pas un infarctus ?〉 가족이 가장 먼저 묻는 질문. AVC 는 〈accident vasculaire cérébral〉 약어(아-베-세)."),
("B2", "un trouble du rythme / une fibrillation auriculaire", "부정맥 / 심방세동", "〈Il a un trouble du rythme.〉 의사가 정확한 용어를 말하면 Hélène처럼 〈en français normal ?〉 로 풀어 달라고 요청해도 된다."),
("B2", "un anticoagulant / sous traitement", "항응고제 / 치료 중인", "〈On va le mettre sous traitement.〉 〈mettre quelqu'un sous traitement〉 = 약물 치료를 시작하다."),
("B2", "garder en observation / sous scope", "경과 관찰을 위해 입원시키다 / 모니터를 달고", "〈On le garde en observation cinq ou six jours.〉 scope 는 심전도 모니터의 구어 줄임말."),
("B2", "Il n'y a pas de danger immédiat.", "당장의 위험은 없습니다.", "의사가 가족을 안심시킬 때의 정중한 표현. 〈Il est stable〉 〈Il est hors de danger〉 와 세트로 기억."),
("B2", "[구어] Dites-moi franchement. / Ça veut dire quoi, en français normal ?", "솔직히 말해 주세요. / 쉬운 말로 하면 무슨 뜻이에요?", "전문 용어를 풀어 달라고 할 때. 뒤의 문장은 구어이며 ↔ 정중: 〈Pouvez-vous m'expliquer en termes simples ?〉"),
("B2", "Je comprends votre inquiétude.", "걱정되시는 마음 이해합니다.", "의사 vous 위로 표현. 이어서 〈Ne vous alarmez pas d'avance.〉 (미리 겁먹지 마세요)."),
("C1", "Il est entre de bonnes mains.", "믿을 만한 손에 맡겨져 있습니다.", "직역은 '좋은 손들 사이에'. 의료진이 가족을 안심시키는 관용 표현. 〈Je vous le promets〉 로 힘을 싣는다."),
("C1", "lever le pied", "속도를 늦추다, 쉬엄쉬엄 하다", "〈Il faudra lever le pied. Tous les deux, peut-être.〉 원래는 액셀에서 발을 떼다. 과로한 사람에게 하는 조언."),
("C1", "À quelque chose malheur est bon.", "불행도 쓸모가 있다 (새옹지마)", "속담. Lucien이 병상에서 자신을 위로하는 말. 문어체 어순 그대로 굳은 형태라 〈malheur est bon〉 의 어순을 바꾸지 않는다."),
("C1", "Chassez le naturel, il revient au galop.", "타고난 성격은 쫓아내도 곧 돌아온다", "속담. 쉬라는 말에 '내일부터 신문과 커피' 라고 답하는 Lucien의 고집. 명령형 vous 형태 그대로 굳은 속담이다."),
("C1", "[구어] Un chef qui n'a pas dormi, ça sale la soupe.", "잠 못 잔 요리사는 수프에 소금을 쏟는다", "요리사 은어에 가까운 농담(과하게 간을 한다는 뜻). 〈ça + 동사〉 로 일반론을 말하는 구어 구문. ↔ 정중: 〈Un chef fatigué commet des erreurs.〉"),
("C1", "[구어] Je demande à voir.", "두고 봐야 알겠는데 (믿기지 않는데)", "상대의 말을 믿지 못할 때 쓰는 빈정거림. Julien이 〈Toi, te reposer ?〉 뒤에 붙인다. ↔ 정중: 〈J'en doute.〉"),
("C1", "[구어] Elle m'enterre, et moi je suis encore là.", "그 사람은 나를 묻으려 하는데 난 아직 여기 있다", "〈enterrer〉 는 '매장하다' 이지만 '죽었다고 단정하다' 의 비유로도 쓴다. 〈Cette vieille chipie !〉 는 애정 섞인 험담이므로 가까운 사이에서만."),
("C1", "[속어] Putain, il est complètement irrégulier.", "젠장, 완전히 불규칙해.", "놀라움과 공포를 터뜨리는 감탄사. 쓸 수 있음: 가까운 직원·가족 사이의 위급 상황 / 금지: 손님·의료진·외부인 앞."),
]

GRAM = [
("B1", "명령형 tu — 짧게 끊는 위급 지시", "〈Mets-le sur le côté !〉 〈Appelle le quinze !〉 〈Bouge pas.〉 〈Mange.〉 긍정 명령형에서는 대명사가 동사 뒤에 붙는다(〈Mets-le〉, 〈Apporte-le-moi〉). 부정이면 〈Ne bouge pas〉 / 구어 〈Bouge pas〉 로 ne 가 빠진다."),
("B2", "venir de + 부정사 (근접 과거)", "〈Un homme vient de faire un malaise.〉 〈Il vient de se réveiller.〉 방금 일어난 일을 말한다. 응급 신고와 상태 설명에서 필수 표현."),
("B2", "조건법 과거 — 자책과 후회", "〈Et si c'était grave ? J'aurais dû m'en rendre compte !〉 〈devoir〉 의 조건법 과거(〈j'aurais dû〉)는 '했어야 했는데' 라는 후회를 말한다. 〈Si c'était grave〉 처럼 si 뒤에는 반과거를 쓰고 조건법은 쓰지 않는다."),
("B2", "vous 존댓말의 의료 설명 — 완곡과 안심", "〈Je tiens à vous rassurer.〉 〈Je comprends votre inquiétude.〉 〈Ne vous alarmez pas d'avance.〉 〈Il est entre de bonnes mains.〉 의사는 사실(〈Il est stable〉)을 먼저, 감정 배려(〈je comprends〉)를 뒤따르게 말한다."),
("B2", "과거에서 본 미래 — savais que tu ferais", "〈Parce que je savais que tu ferais cette tête-là.〉 주절이 반과거(〈savais〉)이면 종속절의 미래는 조건법(〈ferais〉)으로 맞춘다. 〈Je pensais qu'il viendrait.〉 도 같은 구조."),
("C1", "ça + 동사 — 일반론의 구어", "〈Un médecin, ça te trouve toujours quelque chose.〉 〈Un vieux cœur, ça se répare.〉 〈Un chef qui n'a pas dormi, ça sale la soupe.〉 주제어를 앞에 꺼내고 〈ça〉 로 받아 일반 법칙처럼 말한다. 정중체로는 〈Un médecin trouve toujours…〉."),
("C1", "속담 활용 — 어순을 고정한 채 상황에 끼워 넣기", "〈À quelque chose malheur est bon.〉 〈Chassez le naturel, il revient au galop.〉 속담은 형태를 바꾸지 않고 앞뒤에 〈au moins〉, 〈Dès demain,…〉 같은 구어 해설을 붙인다."),
]

READ = [
("리에종 — il_a_perdu_connaissance", "〈Il a perdu connaissance.〉 / 〈Il a eu de la chance d'être entouré.〉 〈il_a〉 에서 [ilа] 로 이어 읽는다. 〈perdu connaissance〉 에서는 u와 c 사이를 끊지 않고 〈pɛrdy-kɔnɛsɑ̃s〉 처럼 한 호흡으로 붙인다."),
("비음 — Ça tourne, mon père", "〈Ça tourne, Hélène. J'ai la tête qui…〉 ‘tourne’ 의 ou 는 [u] 로 입술을 동그랗게. 〈le cœur bat vite〉 의 〈cœur〉 는 [kœːʁ] 로 입을 앞으로 모은다. 〈anticoagulant〉 은 an-ti-co-a-gu-lant 5음절로 또박또박."),
("의사 vous 억양 — 안심시키는 내림조", "〈Il est stable. / Je tiens à vous rassurer tout de suite : / il n'y a pas de danger immédiat.〉 문장 끝은 부드럽게 내리고, 〈:〉 뒤에서 한 호흡 쉰다. 불안한 질문(〈Ce n'est pas un infarctus ?〉)은 끝을 올린다."),
("숨 가쁜 구어 — 끊어 읽는 위급 장면", "〈Il respire, / il respire ! / Il a les yeux fermés. / Papa, / réponds-moi !〉 쉼표마다 짧게 끊고 점점 높이를 올린다. 〈Papa ! Papa, tu m'entends ?〉 는 두 번째 〈Papa〉 가 더 낮고 떨리게."),
("신고 전화 낭독 — 숫자와 정보 순서", "〈Allô, / le quinze ? / Un homme de soixante-douze ans / vient de faire un malaise.〉 〈soixante-douze〉 는 [swasɑ̃t-duːz] 로 읽는다. 장소는 〈Rue Saint-Maur, / dans le onzième,〉 처럼 작은 단위에서 큰 단위로, 일정한 속도로."),
("농담의 속도 — Lucien의 속담", "〈À quelque chose malheur est bon.〉 / 〈Chassez le naturel, / il revient au galop.〉 속담은 가볍게 던지듯, 끝 〈galop〉 에서 살짝 웃음을 담는다. 〈Père-Lachaise〉 는 [pɛʁ laʃɛːz] 로 〈ch〉 가 [ʃ]."),
("우는 목소리 — 문장 끝 흐리기", "〈J'ai eu tellement peur, Papa. J'ai cru que…〉 마지막 〈que…〉 에서 목소리를 낮추고 문장을 끝맺지 않는다. 말줄임 뒤에 한 박자 쉬면 감정이 살아난다."),
]

CULTURE = [
("15번과 SAMU — 프랑스의 응급 호출", "프랑스에서는 응급 의료 상황에 15번(SAMU), 소방 18번, 유럽 공통 112번을 누른다. 15번은 의사 ‘조정관’이 전화로 상태를 묻고 구급차나 의료팀 파견을 결정한다. 이 화의 Julien처럼 나이, 증상, 위치, 의식 여부를 차분히 말하는 것이 핵심이며 ‘끊지 말고 대기’ 하라는 안내를 따른다."),
("의사 vous와 가족의 tu — 병원의 두 언어", "병원에서 의료진과 가족은 서로 vous 를 쓰고, 설명은 사실 → 안심 → 다음 단계 순서로 진행된다. 환자 가족 사이에서는 tu 와 농담이 오가며 긴장을 푼다. 이 화에서 Lucien은 심전도 모니터 곁에서도 브루이 와인과 속담을 놓지 않는다."),
]

META = dict(part=5, ep=70, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="Lucien à l'hôpital", title_ko="병원에 간 뤼시앵",
 place="파리 11구 Le Comptoir de Marthe → 병원 응급실·심장내과 412호 · 6월 8일 화요일, 오전 11시 20분~저녁",
 chars="Hélène Marchand (주인 겸 셰프) · Lucien Marchand (아버지, 72세) · Julien Benali (홀 매니저) · Dr Fabre (심장내과 의사)",
 wine="점심 준비 중 쓰러진 Lucien. 응급실의 불안과 위로, 심방세동 진단, 병상에서 Marthe의 노트를 부탁한다",
 focus="병원·의료 어휘(malaise, pouls, ECG, fibrillation, anticoagulant), 불안과 위로 표현(Je comprends votre inquiétude), 명령형 tu, venir de + 부정사, 속담",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제71화 « Transmission » : 토요일, 병상의 Lucien이 Marthe의 노트와 가게의 의미를 차분히 이야기한다")
