# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, C = "Hélène", "Lucien", "Chloé"
D = [
(None, "Samedi 12 juin, 15 h 30. Chambre 412. Lucien est assis dans son lit, deux oreillers dans le dos. Par la fenêtre, on voit un marronnier. Hélène entre avec un sac en tissu.", "6월 12일 토요일 오후 3시 30분. 412호 병실. 뤼시앵이 베개 두 개에 등을 기대고 침대에 앉아 있다. 창밖으로 마로니에 나무가 보인다. 엘렌이 천 가방을 들고 들어온다."),
(H, "Salut, Papa. T'as meilleure mine que mardi.", "안녕, 아빠. 화요일보다 안색이 훨씬 좋네요."),
(L, "Je mange de la purée tous les jours. Ça rend rose.", "매일 퓌레만 먹으니까. 혈색이 도는 거지."),
(H, "Le docteur Fabre est passé ?", "파브르 선생님 다녀가셨어요?"),
(L, "Ce matin. Le rythme est redevenu normal, grâce aux cachets. Je sors mercredi.", "오늘 아침에. 약 덕분에 맥박이 정상으로 돌아왔대. 수요일에 나간다."),
(H, "Mercredi ? Sérieux ? Tu me l'as pas dit au téléphone.", "수요일이요? 정말요? 전화로는 말 안 했잖아요."),
(L, "Je voulais te faire une surprise. Tu vois, je sais encore en faire.", "깜짝 놀라게 해 주려고. 봐라, 나도 아직 깜짝 선물 할 줄 안다."),
(H, "Toi, tu fais surtout des frayeurs.", "아빠는 주로 가슴 철렁하게 하잖아요."),
(L, "C'est pareil, dans le fond. Allez, assieds-toi. Tu l'as apporté ?", "결국 비슷한 거지. 자, 앉아라. 가져왔니?"),
(H, "Il est là. Je l'ai enveloppé dans un torchon, comme un pain.", "여기 있어요. 빵처럼 행주에 싸서 가져왔어요."),
(L, "Comme un pain... Ta mère aurait ri. Donne-le-moi.", "빵처럼... 네 엄마가 웃었겠구나. 이리 주렴."),
(None, "Hélène sort un carnet à couverture de toile, très usé. Lucien le prend à deux mains, sans l'ouvrir.", "엘렌이 천 표지가 닳은 노트를 꺼낸다. 뤼시앵이 열지 않은 채 두 손으로 받아 든다."),
(L, "Il est plus léger que dans mon souvenir.", "기억 속보다 가볍구나."),
(H, "Il sent encore la vanille, non ?", "아직 바닐라 향이 나죠?"),
(L, "La vanille, le beurre noisette, et la fumée de la cuisine. Il sent la maison.", "바닐라, 헤이즐넛 버터, 그리고 주방 연기. 집 냄새가 나는구나."),
(H, "Papa, pourquoi il était dans ta boîte à outils ? Je t'ai jamais posé la question.", "아빠, 이게 왜 공구함에 있었어요? 한 번도 물어본 적이 없네요."),
(L, "Parce que j'étais lâche, ma grande. Après sa mort, je l'ai caché là.", "내가 겁쟁이였으니까, 얘야. 네 엄마가 떠난 뒤에 거기 숨겨 놨지."),
(L, "Je n'arrivais pas à l'ouvrir. Pas une page, pendant des années.", "열어 볼 수가 없었어. 몇 년 동안 한 쪽도 못 읽었다."),
(H, "Et maintenant ? Tu veux l'ouvrir ?", "지금은요? 열어 보고 싶어요?"),
(L, "Pas encore. D'abord, je voudrais te raconter. Tu m'écoutes ?", "아직은 아니다. 먼저 너한테 얘기해 주고 싶구나. 들어 주겠니?"),
(H, "Je suis là, Papa. J'ai deux heures avant le service.", "여기 있어요, 아빠. 서비스 전까지 두 시간 있어요."),
(L, "Alors voilà. Au printemps quatre-vingt-onze, on n'avait pas un sou.", "자, 그러니까. 91년 봄에, 우리는 땡전 한 푼 없었다."),
(L, "On a repris un vieux café, rue Saint-Maur. Le plafond fuyait, la cuisinière aussi.", "생모르 가의 낡은 카페를 인수했지. 천장도 새고 조리대도 샜어."),
(H, "Maman me disait que le four chauffait que d'un côté.", "엄마가 그러셨어요. 오븐이 한쪽만 뜨거웠다고."),
(L, "D'un côté seulement ! Elle tournait les plats toutes les dix minutes.", "한쪽만! 그래서 10분마다 접시를 돌렸지."),
(L, "Et le soir, après le service, elle s'asseyait au comptoir avec un crayon.", "그리고 저녁에 영업이 끝나면 카운터에 앉아서 연필을 들었어."),
(H, "Un crayon ? Pas un stylo ?", "연필이요? 볼펜이 아니고요?"),
(L, "Toujours un crayon. Elle disait : un crayon, ça se corrige.", "늘 연필이었다. 이렇게 말했지. 연필은 고칠 수 있다고."),
(H, "Ça lui ressemble tellement.", "엄마답네요."),
(L, "Elle notait tout. Les temps de cuisson, les couleurs, le prix des carottes.", "엄마는 모든 걸 적었어. 조리 시간, 색깔, 당근 값까지."),
(L, "Et les clients aussi. Qui aimait quoi, qui détestait quoi, qui fêtait quoi.", "손님들도 적었지. 누가 뭘 좋아하고, 뭘 싫어하고, 뭘 기념하러 오는지."),
(H, "Même les anniversaires ?", "생일까지요?"),
(L, "Les anniversaires, les chagrins, le prénom des enfants. Elle n'oubliait personne.", "생일, 슬픈 일, 아이들 이름. 아무도 잊지 않았어."),
(H, "Et ton premier client, tu t'en souviens ?", "그럼 첫 손님은 기억해요?"),
(L, "Un facteur ! Il a commandé un œuf mayonnaise et un verre de rouge.", "우체부였지! 삶은 달걀 마요네즈랑 레드와인 한 잔을 시켰어."),
(H, "Et il a payé ?", "계산은 했어요?"),
(L, "Non, il avait oublié son portefeuille. Il est revenu le lendemain avec trois collègues.", "아니, 지갑을 두고 왔더라. 다음 날 동료 셋을 데리고 다시 왔지."),
(H, "Ha ! Ça, c'est dans le carnet ?", "하! 그것도 노트에 있어요?"),
(L, "Page deux. Elle a écrit : « Le facteur. Toujours une table pour lui. »", "두 번째 쪽에. 이렇게 썼더구나. '우체부. 그 사람 자리는 늘 남겨 둘 것.'"),
(H, "Papa, t'as dit que t'avais jamais lu une page.", "아빠, 한 쪽도 안 읽었다면서요."),
(L, "Je n'ai pas besoin de le lire. Je l'ai vu s'écrire, soir après soir.", "읽을 필요 없다. 밤마다 쓰이는 걸 내 눈으로 봤으니까."),
(H, "D'accord. Mais c'est un livre de recettes, ce carnet ?", "알겠어요. 그런데 이 노트는 요리책이에요?"),
(L, "Non. Enfin, pas seulement. Les recettes, tu les connais déjà.", "아니. 글쎄, 꼭 그것만은 아니지. 요리법은 네가 이미 알잖니."),
(H, "Pas toutes. Pas comme elle les faisait.", "전부는 아니에요. 엄마가 하던 대로는 아니고요."),
(L, "Justement. Elle ne mesurait presque jamais. Elle disait : une noix de beurre, un peu de patience.", "바로 그거다. 엄마는 거의 재지 않았어. 버터 한 덩이, 인내심 조금이라고 했지."),
(L, "Une recette, c'est des grammes. Ce carnet, c'est une façon de regarder les gens.", "요리법은 그램 수고, 이 노트는 사람들을 바라보는 방식이다."),
(H, "Regarder les gens ? Comment ça ?", "사람을 바라보는 방식이요? 무슨 뜻이에요?"),
(L, "Elle regardait comment ils mangeaient. Et elle ajustait le plat, le sel, le pain.", "엄마는 사람들이 먹는 모습을 봤어. 그리고 요리와 간, 빵을 거기에 맞췄지."),
(L, "Un client triste, une soupe plus chaude. Un client pressé, une assiette plus simple.", "슬픈 손님에게는 더 따뜻한 수프를. 바쁜 손님에게는 더 간단한 접시를."),
(H, "C'est ce qu'elle appelait « cuisiner pour quelqu'un » ?", "그게 엄마가 말하던 '누군가를 위해 요리하기'예요?"),
(L, "Oui. Elle disait : cuisiner, c'est parler à quelqu'un qu'on aime, sans faire de bruit.", "그렇다. 이렇게 말했어. 요리란 사랑하는 사람에게 소리 없이 말을 거는 거라고."),
(H, "Sans faire de bruit... Je vais le noter.", "소리 없이... 적어 둬야겠어요."),
(L, "Au crayon, alors.", "그럼 연필로 적으렴."),
(H, "Au crayon, Papa.", "연필로 쓸게요, 아빠."),
(None, "Un infirmier passe la tête, vérifie le scope et repart. Lucien attend qu'il sorte.", "간호사가 고개를 들이밀고 모니터를 확인한 뒤 나간다. 뤼시앵은 그가 나갈 때까지 기다린다."),
(L, "Hélène, je dois te dire autre chose. Tu avais raison, l'autre jour.", "엘렌, 하나 더 말할 게 있다. 지난번에 네 말이 맞았어."),
(H, "Papa, on en a déjà parlé. On s'est tout dit.", "아빠, 그 얘긴 이미 했잖아요. 서로 다 말했고요."),
(L, "Pas tout. Laisse-moi finir. Quand ta mère était malade, j'étais derrière les fourneaux.", "다는 아니지. 끝까지 말하게 해 다오. 네 엄마가 아팠을 때 난 주방에 있었다."),
(L, "Je me disais : si je tiens la maison, tout ira bien. C'était faux.", "가게만 지키면 다 잘될 거라고 생각했어. 틀린 생각이었다."),
(H, "Elle t'a jamais reproché ça.", "엄마는 한 번도 아빠를 탓한 적 없어요."),
(L, "Si, une fois. Elle m'a dit : « Tu sais nous nourrir, Lucien. Mais tu sais pas nous parler. »", "한 번 그랬다. '당신은 우리를 먹일 줄은 알아, 뤼시앵. 하지만 우리에게 말할 줄은 몰라.' 하더구나."),
(H, "Et aujourd'hui, tu me parles.", "그런데 오늘은 나한테 말하고 있네요."),
(L, "Un petit malaise de rien du tout, et me voilà bavard. Je suis devenu une vraie pie.", "별것 아닌 어지럼증 한 번에 말이 많아졌지. 완전히 수다쟁이 까치가 됐구나."),
(H, "Reste une pie, alors. J'aime bien t'écouter.", "그럼 계속 까치로 있어요. 아빠 얘기 듣는 거 좋아요."),
(None, "On frappe doucement. Chloé entre, un petit pot de confiture à la main.", "누가 조용히 노크한다. 클로에가 작은 잼 병을 들고 들어온다."),
(C, "Bonjour... Je dérange ? Je peux repasser.", "안녕하세요... 방해돼요? 다시 올 수도 있어요."),
(L, "Entre, Chloé ! Tu ne déranges jamais. Qu'est-ce que tu m'apportes ?", "들어오렴, 클로에! 방해될 리가 없지. 뭘 가져왔니?"),
(C, "De la confiture de rhubarbe. C'est Mme Vasseur qui l'envoie.", "대황 잼이에요. 바세르 부인이 보내셨어요."),
(C, "Elle a dit : « Pour qu'il n'oublie pas le goût d'une vraie confiture. »", "이렇게 말씀하셨어요. '진짜 잼 맛을 잊지 않게 하라'고요."),
(L, "Cette vieille chipie ! Elle me gâte, en fait.", "그 심술쟁이 할망구! 알고 보면 나를 애지중지한다니까."),
(H, "Elle a pleuré au téléphone, Papa. Mais elle te dira que non.", "전화로 우셨어요, 아빠. 하지만 아니라고 하실 거예요."),
(C, "Moi, j'ai pas pleuré. Enfin, un peu. Dans la chambre froide.", "저는 안 울었어요. 아, 조금 울었네요. 냉장실에서요."),
(L, "Julien m'a raconté. Et ensuite tu as servi comme une grande.", "쥘리앵이 말해 줬다. 그러고 나서 어른처럼 서빙했다고."),
(C, "Ben, il fallait bien. Le service, ça n'attend pas.", "그야 해야죠. 서비스는 기다려 주지 않으니까요."),
(L, "Tu as raison. Dis-moi, qu'est-ce que tu as dans la poche, là ?", "맞는 말이다. 그런데 주머니에 든 게 뭐니?"),
(C, "Mon carnet. Je l'emmène partout, même à l'hôpital.", "제 수첩이요. 어디든 들고 다녀요, 병원에도요."),
(L, "Montre-le-moi. Hélène, regarde : voilà l'héritière.", "보여 다오. 엘렌, 봐라. 여기 후계자가 있구나."),
(H, "Papa, elle écrit des mots, pas des recettes.", "아빠, 클로에는 단어를 적지 요리법을 적는 게 아니에요."),
(L, "C'est la même chose. Elle note les mots des gens. Ta mère notait les gens.", "같은 거다. 이 아이는 사람들의 말을 적고, 네 엄마는 사람들을 적었지."),
(C, "Moi, j'ai noté « raccrocher son tablier » la semaine dernière.", "저는 지난주에 '앞치마를 걸다', 즉 은퇴한다는 표현을 적었어요."),
(L, "Ah oui ? Et qui t'a appris ça ?", "그래? 누가 가르쳐 줬니?"),
(C, "Toi. Tu l'as dit à Karim, un matin. Tu disais que tu y pensais.", "아저씨요. 어느 날 아침 카림한테 하셨어요. 생각 중이라고 하셨죠."),
(L, "Oh, ces jeunes oreilles ! On ne peut rien leur cacher.", "아이고, 젊은 귀들이란! 아무것도 숨길 수가 없구나."),
(H, "Tu y penses vraiment, Papa ?", "정말 생각 중이에요, 아빠?"),
(L, "Plus que ça. Mais pas aujourd'hui. Je te dirai quand je sortirai.", "그 이상이지. 하지만 오늘은 아니다. 퇴원하면 말해 주마."),
(H, "Pas de décision avant d'avoir bien dormi. C'est un ordre du docteur.", "푹 자기 전에는 아무 결정도 안 돼요. 의사 선생님 명령이에요."),
(L, "Un ordre de fille, plutôt. Bon, d'accord.", "딸의 명령 같은데. 좋다, 알겠다."),
(L, "Chloé, tu sais ce que c'est, un restaurant ?", "클로에, 식당이 뭔지 아니?"),
(C, "Euh... un endroit où on mange ? Où on travaille ?", "음... 밥 먹는 곳? 일하는 곳?"),
(L, "C'est un peu comme un pain. Ça se partage, et ça se transmet.", "빵과 조금 비슷하단다. 나누고, 물려주는 거야."),
(L, "On n'en est jamais propriétaire. On le garde pour ceux qui viennent après.", "그 누구도 진짜 주인이 되지 못해. 뒤에 오는 사람들을 위해 지키는 거지."),
(C, "Pour ceux qui viennent après... Ça me plaît, ça.", "뒤에 오는 사람들을 위해서... 그 말 마음에 들어요."),
(L, "Alors garde ça en tête, petite. C'est tout le métier.", "그럼 그걸 마음에 새겨 두렴. 그게 이 일의 전부다."),
(L, "Hélène, ouvre le carnet. Tout à la fin.", "엘렌, 노트를 열어 봐라. 맨 끝쪽을."),
(None, "Hélène feuillette jusqu'aux dernières pages. Il y en a beaucoup de blanches.", "엘렌이 마지막 쪽까지 넘긴다. 하얀 쪽이 아주 많다."),
(H, "Elles sont vides. Il y en a plus de trente.", "비어 있어요. 서른 쪽도 넘게요."),
(L, "Je sais. Elle a laissé la fin vide. Elle savait pour qui.", "알고 있다. 엄마는 끝부분을 비워 뒀지. 누구를 위한 건지 알았던 거야."),
(H, "Papa, je peux pas écrire à côté de Maman.", "아빠, 엄마 글씨 옆에 제가 쓸 순 없어요."),
(L, "Si. Tu dois. Un carnet, ça ne s'hérite pas. Ça se continue.", "쓸 수 있다. 써야 해. 노트는 물려받는 게 아니라 이어 가는 거다."),
(C, "Moi, je peux regarder ? Juste la couverture ?", "저도 봐도 돼요? 표지만요?"),
(H, "Viens. Tiens-le avec précaution, il est fragile.", "와 봐. 조심해서 들어, 약하니까."),
(C, "C'est... c'est tout petit. Je croyais que ça serait énorme.", "이게... 정말 작네요. 엄청 두꺼울 줄 알았는데."),
(L, "Les plus grandes choses tiennent dans une poche. Les grandes cuisines aussi.", "가장 큰 건 주머니에도 들어간단다. 훌륭한 주방도 그렇지."),
(H, "Et la dernière phrase du carnet ? Celle que tu connais par cœur ?", "그럼 아빠가 외우고 있는 이 노트의 마지막 문장은요?"),
(L, "Je l'ai jamais lue, je te dis. Mais je sais ce qu'elle dirait.", "읽은 적 없다니까. 하지만 엄마가 뭐라고 쓸지는 알지."),
(L, "Elle dirait : « Continuez sans moi, mais gardez le goût. »", "'나 없이도 계속해라, 다만 맛은 지켜라.' 하고 썼을 거다."),
(H, "Garder le goût... pas la recette ?", "맛을 지키라고요... 요리법이 아니라요?"),
(L, "Non. Change les recettes. Mets du neuf. Mais que ça goûte la maison.", "그래. 요리법은 바꿔라. 새것을 넣어. 하지만 집 맛은 나야 해."),
(H, "Compris. Du neuf, mais avec le goût d'avant.", "알겠어요. 새로운 것, 하지만 옛 맛이 나는 것."),
(C, "C'est joli, ça. Je peux le noter ?", "그 말 예쁘네요. 적어도 돼요?"),
(L, "Note, note. Écris même mon nom à côté, ça portera chance.", "적어라, 적어. 내 이름도 옆에 써 둬라, 행운이 따를 테니."),
(C, "Ça y est. Page trois cent quarante-sept.", "다 썼어요. 347쪽이에요."),
(L, "Trois cent quarante-sept ! Tu as plus de pages que Marthe, alors.", "347쪽! 그럼 마르트보다 쪽수가 많구나."),
(None, "Lucien bâille. Ses paupières sont lourdes. Hélène remonte la couverture.", "뤼시앵이 하품을 한다. 눈꺼풀이 무겁다. 엘렌이 이불을 끌어올려 준다."),
(L, "Je crois que je vais fermer les yeux cinq minutes.", "5분만 눈을 감아야겠구나."),
(H, "Dors, Papa. On reste un peu.", "주무세요, 아빠. 우리 조금 더 있을게요."),
(L, "Hélène... Merci d'être venue avec le carnet.", "엘렌... 노트를 가져와 줘서 고맙다."),
(H, "C'est moi qui te remercie. De me l'avoir raconté.", "제가 고맙죠. 이야기해 주셔서."),
(L, "Ta mère serait fière de toi. Je te le dis, tu entends ? Je te le dis.", "네 엄마는 네가 자랑스러울 거다. 내가 말해 두마, 들리니? 내가 말한다."),
(H, "Je t'entends, Papa. Je t'ai bien entendu.", "들려요, 아빠. 똑똑히 들었어요."),
(None, "Quelques minutes plus tard, Lucien dort. Hélène sort un crayon de son sac.", "몇 분 뒤, 뤼시앵이 잠든다. 엘렌이 가방에서 연필을 꺼낸다."),
(C, "Tu vas écrire maintenant ? Là, tout de suite ?", "지금 쓰시게요? 바로 여기서요?"),
(H, "Juste une ligne. La première page blanche. Au crayon.", "한 줄만요. 첫 번째 하얀 쪽에. 연필로."),
(C, "Qu'est-ce que tu mets ?", "뭐라고 쓰실 건데요?"),
(H, "« Samedi douze juin. Papa m'a raconté Maman. » C'est tout.", "'6월 12일 토요일. 아빠가 엄마 이야기를 해 주셨다.' 그게 다야."),
(C, "C'est parfait. Et c'est au crayon.", "완벽해요. 그리고 연필이네요."),
(H, "Oui. Ça se corrige. Mais celle-là, je ne la corrigerai pas.", "맞아. 고칠 수 있지. 하지만 이 문장은 고치지 않을 거야."),
]

VOCAB = [
("A2", "Je sors mercredi.", "수요일에 퇴원해(나가).", "현재형으로 가까운 미래의 계획을 말한다. 〈Je sors〉 는 sortir 의 je 형태. 병원·학교 등 〈나가다〉 에 두루 쓰인다."),
("A2", "Dors, Papa. / Entre, Chloé !", "주무세요, 아빠. / 들어와, 클로에!", "명령형 tu. dormir→〈dors〉, entrer→〈entre〉(-er 동사는 s 가 빠진다). 가까운 사이의 부드러운 명령."),
("B1", "[구어] Je voulais te faire une surprise.", "깜짝 놀라게 해 주려고 했어.", "〈faire une surprise à quelqu'un〉. 구어에서는 이어서 〈Tu vois, je sais encore en faire.〉 처럼 en 으로 받는다. ↔ 정중: 〈Je souhaitais vous réserver une surprise.〉"),
("B1", "J'ai deux heures avant le service.", "서비스 전까지 두 시간 있어요.", "〈avoir + 시간 + avant〉. 식당 종사자가 일정을 말할 때 자주 쓰는 구문."),
("B1", "un crayon / un stylo", "연필 / 볼펜", "〈Un crayon, ça se corrige.〉 Marthe의 가르침. 연필은 지우고 고칠 수 있는 도구라는 상징."),
("B1", "[구어] Bah, il fallait bien.", "그야 해야 했잖아.", "〈il faut〉 의 반과거 〈il fallait〉. 〈bien〉 이 붙어 '어쩔 수 없었다' 는 뉘앙스. ↔ 정중: 〈C'était nécessaire.〉"),
("B2", "On n'avait pas un sou.", "땡전 한 푼 없었다.", "〈ne pas avoir un sou〉 = 돈이 한 푼도 없다. 〈sou〉 는 옛 화폐 단위. 구어에서는 ne 를 생략해 〈On avait pas un sou.〉"),
("B2", "Le plafond fuyait, la cuisinière aussi.", "천장도 새고 조리대도 샜다.", "〈fuir〉 의 반과거로 과거의 상태를 묘사한다. 같은 동사를 생략하고 〈…, X aussi〉 로 이어 쓰는 구어 구문."),
("B2", "caler le dos / deux oreillers", "등을 받치다 / 베개 두 개", "〈Il est assis, deux oreillers dans le dos.〉 지문에서 쓰인 묘사 표현. 〈caler〉 는 '고정시키다, 받치다'."),
("B2", "ajuster le plat, le sel, le pain", "요리·간·빵을 손님에게 맞추다", "〈Elle ajustait…〉 반과거는 반복된 습관. Marthe가 손님을 보고 요리를 조정했다는 회상의 핵심 동사."),
("B2", "se souvenir de / s'en souvenir", "기억하다", "〈Tu t'en souviens ?〉 〈Je me souviens de…〉 대명동사. 〈en〉 으로 앞 내용을 받는다."),
("B2", "en avoir besoin / Je n'ai pas besoin de le lire.", "그럴 필요가 없다", "〈avoir besoin de + 부정사〉. 부정은 〈pas besoin de〉. 구어에서는 〈Pas besoin !〉 만으로 쓰기도 한다."),
("B2", "Cuisiner, c'est parler à quelqu'un qu'on aime, sans faire de bruit.", "요리란 사랑하는 사람에게 소리 없이 말을 거는 일이다", "Marthe의 말. 〈C'est + 동사원형〉 정의문 + 관계절 〈qu'on aime〉. 〈sans faire de bruit〉(sans + 부정사)로 조용한 정을 표현."),
("B2", "Un client triste, une soupe plus chaude.", "슬픈 손님에게는 더 따뜻한 수프", "동사를 생략한 병렬 구문. 회상 독백에서 리듬을 만들 때 쓰는 구어 기법. 〈A client B, un plat C〉."),
("B2", "Il sent la maison. / Il sent la vanille.", "집 냄새가 난다. / 바닐라 향이 난다.", "〈sentir + 명사〉 = ~의 냄새가 난다. 〈sentir bon / sentir mauvais〉 도 같이."),
("C1", "tenir la maison / être derrière les fourneaux", "가게(집)를 지키다 / 주방에서 일하다", "〈J'étais derrière les fourneaux.〉 주방에서 일하는 요리사를 가리키는 관용 표현. 가정에서는 〈tenir la maison〉."),
("C1", "[구어] Un petit malaise de rien du tout.", "별것 아닌 어지럼증", "〈de rien du tout〉 = 정말 하찮은. 병이나 사건을 축소해 말하는 구어. ↔ 정중: 〈un léger malaise sans gravité〉."),
("C1", "devenir une vraie pie", "수다쟁이가 되다", "〈pie〉(까치)는 말 많은 사람의 비유. 〈bavard comme une pie〉 가 원래 형태. 가까운 사이에서의 애정 섞인 농담."),
("C1", "raccrocher son tablier", "앞치마를 걸다 — 은퇴하다", "요리사·장인의 은퇴 관용구. 〈raccrocher les gants〉(권투)처럼 직업 도구를 건다는 이미지. Chloé의 수첩 속 새 표현으로 74화의 복선."),
("C1", "Un carnet, ça ne s'hérite pas. Ça se continue.", "노트는 물려받는 게 아니라 이어 가는 것이다", "〈ça se + 동사〉 구어 일반론(수동 의미의 대명동사). 〈hériter〉 의 대명동사 용법은 일반적이지 않으나 말의 힘으로 쓰인 의도적 표현."),
("C1", "Continuez sans moi, mais gardez le goût.", "나 없이도 계속하되 맛은 지켜라", "Lucien이 짐작해 말하는 Marthe의 유언. 〈Garder le goût〉 = 요리법이 아니라 정신을 지킨다는 뜻. 〈sans moi〉 로 부재를 부드럽게 말한다."),
("C1", "[구어] Cette vieille chipie ! Elle me gâte, en fait.", "그 심술쟁이 할망구! 알고 보면 나를 애지중지한다니까", "〈chipie〉 는 심술궂은 여자에 대한 애정 섞인 험담. 〈gâter quelqu'un〉 = 응석을 받아 주다. 쓸 수 있음: 가까운 사이 / 금지: 당사자 앞이나 손님 앞."),
("C1", "Les plus grandes choses tiennent dans une poche.", "가장 큰 것은 주머니에도 들어간다", "최상급 〈les plus grandes〉 + 일반론. 작은 노트에 담긴 큰 의미를 말하는 Lucien의 격언풍 문장."),
("C1", "Il sent la maison, comme un pain.", "빵처럼, 집 냄새가 난다", "비유 〈comme un pain〉(행주에 싼 빵처럼)로 노트를 소중히 다룬 감정을 요약한다. 회상 독백에서 감각(냄새·촉감)을 쓰는 방법."),
]

GRAM = [
("B2", "반과거 — 회상의 습관과 배경", "〈Le plafond fuyait.〉 〈Elle notait tout.〉 〈Elle regardait comment ils mangeaient.〉 〈Elle ne mesurait presque jamais.〉 과거의 배경과 반복되는 습관은 imparfait. 한 번의 사건은 passé composé 〈Elle m'a dit : …〉 〈On a repris un vieux café.〉"),
("B2", "대과거 — 더 이전의 일", "〈Il avait oublié son portefeuille.〉 이미 지나간 시점보다 앞서 일어난 일은 plus-que-parfait. 같은 문장의 주절은 passé composé 〈Il est revenu le lendemain.〉"),
("B2", "동사 생략 병렬 — 리듬 있는 구어", "〈Un client triste, une soupe plus chaude. Un client pressé, une assiette plus simple.〉 동사를 빼고 두 요소를 나란히 놓으면 짧고 힘 있는 독백 리듬이 된다. 회상을 말할 때 효과적."),
("B2", "ne ... presque jamais / pas du tout / toujours", "〈Elle ne mesurait presque jamais.〉 〈Toujours un crayon, jamais un stylo.〉 빈도 부사의 위치와 구어 생략. 〈presque〉 는 〈ne … jamais〉 안쪽에 들어간다."),
("C1", "ça se + 동사 — 일반 법칙", "〈Un crayon, ça se corrige.〉 〈Ça se partage, et ça se transmet.〉 〈Ça se continue.〉 수동 의미의 대명동사에 〈ça〉 를 주어로 써서 격언처럼 말한다. 정중체로는 〈On peut le corriger.〉"),
("B2", "관계대명사 qu'on aime, dont — 정의하기", "〈Cuisiner, c'est parler à quelqu'un qu'on aime.〉 〈Je sais ce qu'elle dirait.〉 〈C'est ce qu'elle appelait « cuisiner pour quelqu'un ».〉 〈ce qui / ce que〉 는 '~하는 것'. 정의문과 설명에서 반복된다."),
("C1", "조건법 — 짐작하는 죽은 사람의 말", "〈Elle dirait : « Continuez sans moi. »〉 〈Ta mère serait fière de toi.〉 조건법 현재로 '아마 ~했을 것이다' 라는 추정을 부드럽게 말한다. 〈Ta mère aurait ri.〉 는 조건법 과거로 가정된 과거의 반응."),
]

READ = [
("저음의 속도 — 병상 독백은 천천히", "〈Alors voilà. / Au printemps quatre-vingt-onze, / on n'avait pas un sou.〉 〈Alors voilà〉 뒤에서 한 호흡 쉬고, 연도는 천천히. 〈quatre-vingt-onze〉 는 [katʁəvɛ̃ɔ̃z] 로 이어 읽는다."),
("리에종 — un_œuf, un_homme, ils_étaient", "〈un œuf mayonnaise〉 [œ̃nœf] 〈Il a commandé un_œuf mayonnaise et un_verre de rouge.〉 〈verre de rouge〉 에서 〈de〉 는 약하게 [də]. 〈un facteur〉 의 〈un〉 은 비음 [œ̃]."),
("ou, u, eu — 따뜻한 모음", "〈Il sent la vanille, le beurre noisette〉 〈beurre〉 의 eu 는 입술을 둥글게 [œ]. 〈poche〉 〈tourner〉 〈toujours〉 의 ou [u]와 〈plus〉 〈dur〉 의 u [y]를 구분해 읽는다."),
("문장 쪼개기 — 조용한 구어 독백", "〈Elle notait tout. / Les temps de cuisson, / les couleurs, / le prix des carottes.〉 쉼표마다 짧게 끊고 억양은 올리지 않고 평평하게. 열거의 마지막만 살짝 내린다."),
("인용문 낭독 — « » 의 톤", "〈Elle a dit : / « Pour qu'il n'oublie pas / le goût d'une vraie confiture. »〉 인용 직전 〈:〉 에서 한 박자 쉬고, 인용 부분은 인물(Mme Vasseur)의 단호한 목소리로 바꾼다."),
("감정이 가라앉는 문장 끝", "〈Ta mère serait fière de toi. / Je te le dis, / tu entends ? / Je te le dis.〉 반복하는 〈Je te le dis〉 는 두 번째가 더 낮고 느리게. 〈fière〉 의 f-i-e-r 는 [fjɛːʁ] 로 r 을 목 안쪽에서 부드럽게."),
("마지막 연필 대사", "〈Oui. / Ça se corrige. / Mais celle-là, / je ne la corrigerai pas.〉 〈celle-là〉 앞뒤 휴지를 길게 두고, 〈pas〉 에 가볍게 힘을 준다. 구어에서는 〈je la corrigerai pas〉 로 ne 가 빠진다."),
]

CULTURE = [
("Le carnet — 프랑스 가정 요리의 손글씨 노트", "프랑스의 많은 가정에는 어머니나 할머니가 대를 이어 쓴 손글씨 요리 노트(cahier de recettes)가 있다. 정확한 그램 수보다 〈une noix de beurre〉(버터 한 덩이), 〈à l'œil〉(눈대중으로) 같은 감각 표현이 많고, 여백에는 가족의 일상이 적히기도 한다. 이 화의 노트가 요리책이 아니라 ‘사람을 바라보는 방식’ 이라는 Lucien의 말은 그런 전통을 반영한다."),
("병실의 시간 — 면회와 가족", "프랑스의 병원은 보통 오후에 면회 시간이 길게 열려 있고, 환자는 가족과 함께 식사 후 조용히 시간을 보낸다. 간호사가 방에 들어와 모니터를 확인하는 일도 흔하다. 이 화처럼 병상에서 오래 묵은 가족 이야기를 꺼내는 일이 드물지 않으며, 짧은 문장과 조용한 구어체가 어울린다."),
]

META = dict(part=5, ep=71, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="Transmission", title_ko="전수",
 place="병원 심장내과 412호 병실 · 6월 12일 토요일, 오후 3시 30분",
 chars="Lucien Marchand (72세, 입원 중) · Hélène Marchand (딸, 주인 겸 셰프) · Chloé Dubois (견습 서버)",
 wine="병상에서 Lucien이 Marthe의 노트와 가게의 의미를 차분히 들려주고, 빈 쪽을 이어 쓰라고 건넨다",
 focus="회상 서사(반과거·대과거), 차분한 구어 독백, 동사 생략 병렬, ça se + 동사 일반론, 조건법 추정, 전수의 관용 표현",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제72화 « Le courrier du guide » : 토요일 아침, 가이드 Lacroix의 편지가 도착하고 모두의 기쁨이 폭발한다")
