# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, C = "Hélène", "Lucien", "Julien", "Chloé"
D = [
(None, "Samedi 19 juin, 9 h 40. Hélène écrit le menu sur l'ardoise. Chloé plie des serviettes. La porte s'ouvre : Lucien entre, une canne à la main, un petit sac de pharmacie sous le bras.", "6월 19일 토요일 오전 9시 40분. 엘렌이 칠판에 메뉴를 쓰고, 클로에는 냅킨을 접는다. 문이 열리고 뤼시앵이 지팡이를 짚고, 약국 봉투를 옆구리에 끼고 들어온다."),
(H, "Papa ?! Qu'est-ce que tu fais là ?", "아빠?! 여기서 뭐 하세요?"),
(L, "Bonjour, ma fille. Moi aussi, je suis content de te voir.", "안녕, 얘야. 나도 너를 봐서 반갑다."),
(H, "T'es sorti mercredi ! Le docteur a dit : repos complet !", "수요일에 퇴원했잖아요! 선생님이 완전히 쉬라고 하셨어요!"),
(L, "Je me suis reposé trois jours. J'en ai le dos tout mou.", "사흘이나 쉬었다. 등이 흐물흐물해졌어."),
(C, "Lucien ! T'es là ! Enfin, je veux dire... tu vas bien !", "뤼시앵! 오셨네요! 아니, 그러니까... 건강하시네요!"),
(L, "Je vais très bien, Chloé. Mauvaise herbe ne meurt jamais.", "아주 잘 있다, 클로에. 잡초는 절대 죽지 않는 법이거든."),
(H, "Qui t'a amené ? T'as pas le droit de conduire.", "누가 데려다줬어요? 운전은 못 하시잖아요."),
(L, "Un taxi. Un jeune homme charmant. Il m'a même ouvert la porte.", "택시였다. 아주 친절한 청년이었지. 문도 열어 줬어."),
(H, "Papa, on s'était mis d'accord. Tu viens quand je t'invite.", "아빠, 우리 합의했잖아요. 제가 부를 때 오기로."),
(L, "Je me suis mis d'accord avec moi-même : une demi-heure, pas plus. Je regarde et je m'en vais.", "나 자신과 합의했다. 30분만, 그 이상은 안 돼. 보기만 하고 간다."),
(C, "C'est quoi, le petit sac ? Des médicaments ?", "그 작은 봉투는 뭐예요? 약이에요?"),
(L, "Mon pilulier. Lundi, mardi, mercredi... Cinq cachets par jour, tu te rends compte ?", "내 약통이다. 월, 화, 수... 하루에 다섯 알이야. 말이 되니?"),
(H, "Tu les as pris, ce matin ?", "오늘 아침에 먹었어요?"),
(L, "Tous. Même celui qui sent le poisson.", "전부 다. 생선 냄새 나는 것까지."),
(H, "Bon. Assieds-toi sur la banquette, loin de la porte. Chloé, un verre d'eau.", "좋아요. 문에서 먼 긴 의자에 앉으세요. 클로에, 물 한 잔 줘."),
(C, "Tout de suite ! Sans sel, hein ?", "바로요! 소금은 안 넣죠?"),
(L, "Ha ha ! Elle a de l'humour, cette petite.", "하하! 이 아이 유머가 있구나."),
(H, "Une demi-heure. Et tu ne touches à rien.", "30분이에요. 그리고 아무것도 만지지 마세요."),
(L, "Je lis ton ardoise, c'est tout. Velouté de petits pois... Qui les a écossés ?", "칠판만 읽을게. 완두콩 벨루테라... 누가 깠니?"),
(H, "Karim. Il a promis qu'ils seraient aussi beaux que les tiens.", "카림이요. 아빠 것만큼 예쁠 거라고 약속했어요."),
(L, "Impossible. Mais il peut essayer.", "불가능하지. 하지만 해 볼 수는 있겠지."),
(None, "La porte s'ouvre à nouveau. Julien entre, une pile de courrier dans les bras.", "문이 다시 열리고, 쥘리앵이 우편물 더미를 안고 들어온다."),
(J, "Salut tout le monde ! Tiens, Lucien ! Tu es évadé de l'hôpital ?", "다들 안녕! 어, 뤼시앵! 병원 탈출했어?"),
(L, "Je suis en permission, mon petit. Comme un soldat.", "휴가 나온 거란다, 얘야. 군인처럼."),
(J, "Une permission qui dure combien de temps ?", "그 휴가는 얼마나 되는데?"),
(H, "Une demi-heure. Elle est déjà à moitié finie.", "30분이에요. 벌써 반쯤 지났고요."),
(J, "Bon. Le courrier. Une facture d'électricité, des pubs, un truc de la mairie...", "자, 우편물. 전기 요금 고지서, 광고, 구청에서 온 거..."),
(J, "Et ça. Regardez-moi cette enveloppe.", "그리고 이거. 이 봉투 좀 봐."),
(None, "Il pose une grande enveloppe crème sur le comptoir. Dessus, en relief : « Guide Lacroix ».", "그가 크림색 큰 봉투를 카운터에 올려놓는다. 위에 도드라진 글씨로 '기드 라크루아'라고 적혀 있다."),
(C, "Le Guide Lacroix ? Celui du monsieur de la table douze ?", "기드 라크루아요? 12번 테이블 그 손님의 가이드요?"),
(J, "Le monsieur seul, avec la blanquette et son petit carnet. Je savais qu'il avait une tête de critique.", "블랑케트를 먹던 혼자 온 손님, 그리고 작은 수첩. 평론가 얼굴이라고 생각했다니까."),
(L, "Tu n'as rien su du tout, Julien. Tu as juste été gentil avec tout le monde.", "넌 아무것도 몰랐어, 쥘리앵. 그냥 모두에게 친절했던 거지."),
(J, "C'est ma méthode. Elle marche à tous les coups.", "그게 내 방식이야. 매번 통하거든."),
(H, "Je... je l'ouvre pas. Ouvre-la, toi, Julien.", "나... 난 안 열 거야. 쥘리앵, 네가 열어."),
(J, "Moi ? Jamais de la vie. C'est ton nom sur l'enveloppe.", "나? 절대 안 돼. 봉투에 적힌 건 네 이름이잖아."),
(C, "Allez, Hélène ! Je vais mourir si tu l'ouvres pas !", "열어 봐요, 엘렌! 안 열면 저 죽어요!"),
(L, "Donne-la-moi. Non, rends-la-moi... Ouvre-la, ma fille. Je suis trop vieux pour attendre.", "내게 다오. 아니, 다시 줘... 열어 봐라, 얘야. 기다리기엔 내가 너무 늙었다."),
(H, "D'accord. D'accord. Respirez tous.", "알았어요. 알았어. 다들 숨 쉬세요."),
(None, "Hélène déchire le papier. Elle déplie une lettre sur papier épais. Silence total.", "엘렌이 봉투를 뜯어 두꺼운 종이의 편지를 펼친다. 완전한 침묵."),
(H, "« Madame Marchand, c'est avec grand plaisir que nous vous informons... »", "'마르샹 씨, 알려 드리게 되어 큰 기쁨입니다...'"),
(H, "« ... que le Comptoir de Marthe est distingué de deux fourchettes dans notre édition de l'an prochain. »", "'...콩투아르 드 마르트가 내년 판에서 포크 두 개로 선정되었음을.'"),
(C, "Deux... deux fourchettes ?", "두... 두 개요?"),
(H, "Attends. Il y a une suite. « Notre jury a aussi décidé de vous décerner... »", "잠깐. 뒤에 더 있어. '심사위원단은 또한 귀하께 다음을 수여하기로 결정했습니다...'"),
(H, "« ... le prix de la Reconstruction de l'année. »", "'...올해의 재건상을.'"),
(None, "Un instant de silence. Puis Chloé pousse un cri. Julien lâche le courrier.", "잠시 침묵. 그다음 클로에가 비명을 지른다. 쥘리앵은 우편물을 떨어뜨린다."),
(C, "AAAH ! C'est pas vrai ! C'est pas vrai !", "아아아! 말도 안 돼! 말도 안 돼!"),
(J, "Deux fourchettes ! Deux ! Sur trois ! Dis-moi que je rêve !", "포크 두 개! 두 개라고! 세 개 중에! 꿈 아니라고 말해 줘!"),
(H, "Je... je sais pas. Relis-la, toi. Mes yeux voient flou.", "나... 모르겠어. 네가 다시 읽어 봐. 눈이 흐려서 안 보여."),
(J, "Donne ! « Deux fourchettes. Prix de la Reconstruction de l'année. » C'est écrit noir sur blanc !", "줘 봐! '포크 두 개. 올해의 재건상.' 까만 글씨로 하얗게 적혀 있어!"),
(C, "Pince-moi ! Pince-moi, Julien ! Je sens plus mes jambes !", "꼬집어 줘요! 쥘리앵, 꼬집어 줘요! 다리 감각이 없어요!"),
(J, "Aïe ! Pas si fort, c'était une façon de parler !", "아야! 그렇게 세게 말고, 말이 그렇다는 거였지!"),
(None, "Karim apparaît à la porte de la cuisine, un torchon à l'épaule. Il comprend en voyant leurs visages.", "카림이 어깨에 행주를 걸치고 주방 문에 나타난다. 그들의 얼굴을 보고 상황을 알아차린다."),
(H, "Karim ! Deux fourchettes ! On a deux fourchettes !", "카림! 포크 두 개야! 우리 포크 두 개래!"),
(J, "Il a lâché sa casserole, il a lâché sa casserole ! Oh, la tête !", "냄비를 떨어뜨렸어, 냄비를 떨어뜨렸다고! 아, 저 표정!"),
(C, "Karim pleure ! Karim, le monsieur sans émotions, il pleure !", "카림이 울어요! 감정 없는 카림이 울어요!"),
(H, "Putain... Putain, on l'a fait. On l'a vraiment fait.", "젠장... 젠장, 해냈어. 우리가 진짜 해냈어."),
(J, "Après tout ce qu'on a traversé ! La fermeture, les dettes, le tribunal...", "그 모든 일을 겪고 나서! 폐쇄, 빚, 법원까지..."),
(C, "J'en ai la chair de poule ! Regardez mes bras !", "소름이 돋았어요! 제 팔 좀 보세요!"),
(H, "Et personne nous a lâchés. Personne. Même quand c'était foutu.", "아무도 우리를 버리지 않았어. 아무도. 다 끝난 것 같을 때조차."),
(J, "On est tous là. Tous. Même le petit nouveau qui épluche les patates.", "우리 모두 여기 있어. 전부. 감자 깎는 신입까지."),
(L, "...", "..."),
(C, "Lucien ? Lucien, ça va ? T'es tout pâle !", "뤼시앵? 괜찮으세요? 얼굴이 하얘요!"),
(J, "Assieds-toi, assieds-toi ! Hélène, son cœur !", "앉아, 앉아! 엘렌, 아저씨 심장!"),
(H, "Papa ! Papa, réponds ! Je jure que je t'emmène aux urgences !", "아빠! 아빠, 대답해요! 맹세코 응급실로 데려갈 거예요!"),
(L, "Du calme, du calme. Ce n'est pas mon cœur. C'est de la joie.", "진정해라, 진정해. 심장이 아니야. 기쁨이란다."),
(L, "Je n'ai plus de mots. Deux fourchettes... Marthe, tu entends ça ?", "말이 안 나오는구나. 포크 두 개라니... 마르트, 듣고 있소?"),
(H, "Papa...", "아빠..."),
(L, "Trente-cinq ans, Hélène. Trente-cinq ans, et jamais une seule. Elle disait : les récompenses, c'est pour ceux qui ont le temps.", "35년이다, 엘렌. 35년 동안 하나도 없었어. 네 엄마는 이렇게 말했지. 상은 시간이 남는 사람들 몫이라고."),
(H, "Maman n'a jamais eu le temps.", "엄마는 한 번도 시간이 없었죠."),
(L, "Mais toi, tu as pris le temps. Tu as pris le risque. Tu as tout porté sur ton dos.", "하지만 너는 시간을 냈어. 위험을 감수했지. 모든 걸 등에 지고 갔다."),
(None, "Hélène s'agenouille devant son père et le serre contre elle. Julien et Chloé s'essuient les yeux.", "엘렌이 아버지 앞에 무릎을 꿇고 끌어안는다. 쥘리앵과 클로에가 눈가를 훔친다."),
(H, "On l'a porté à plusieurs, Papa. Pas seule. Jamais seule.", "여럿이 함께 졌어요, 아빠. 혼자가 아니었어요. 절대 혼자가 아니었어요."),
(J, "Bon. Moi je craque. J'ai plus de mouchoirs, qui m'en prête ?", "자, 나는 무너졌다. 손수건이 없는데 누가 빌려줄래?"),
(C, "Tiens. Mais c'est une serviette, je viens de la plier.", "여기요. 근데 이거 방금 접은 냅킨이에요."),
(J, "Peu importe. Je la prends. Je paierai la lessive.", "상관없어. 쓸게. 세탁비는 내가 낼게."),
(L, "Lis-nous la fin de la lettre, Hélène. Il doit y avoir autre chose.", "편지 끝을 읽어 다오, 엘렌. 뭔가 더 있을 게다."),
(H, "Oui. « Notre inspecteur a dîné chez vous le vingt-deux décembre, table douze. »", "네. '저희 조사관이 12월 22일 12번 테이블에서 식사했습니다.'"),
(H, "« Il est revenu deux fois, sans se présenter, en février et en avril. »", "'신분을 밝히지 않고 2월과 4월에 두 번 다시 방문했습니다.'"),
(J, "En février ! Le monsieur à la veste bleue qui a pris l'île flottante !", "2월에! 파란 재킷 입고 일 플로탕트 시킨 손님이네!"),
(C, "Et en avril, la dame avec les lunettes. Elle a pris une photo de son verre !", "4월에는 안경 쓴 여자분이요. 자기 와인잔 사진을 찍었잖아요!"),
(H, "Je me souviens pas. Je cuisinais, je regardais pas la salle.", "기억 안 나. 요리하느라 홀을 보지 않았어."),
(J, "C'est la preuve qu'on cuisine bien : on ne triche pas, même quand on ne sait pas qu'on est jugé.", "그게 우리가 요리를 잘한다는 증거야. 심사받는 줄 모를 때도 속임수가 없었다는 거니까."),
(H, "« Nous saluons une cuisine sincère, généreuse et fidèle à son histoire. »", "'진솔하고 넉넉하며 자기 역사에 충실한 요리에 경의를 표합니다.'"),
(L, "Fidèle à son histoire. Voilà. C'est exactement ça.", "자기 역사에 충실한. 그거다. 정확히 그거야."),
(H, "« La remise du prix aura lieu le quatorze septembre, à Paris. »", "'시상식은 9월 14일 파리에서 열립니다.'"),
(C, "On va aller à une vraie cérémonie ? Avec des robes ?", "진짜 시상식에 가는 거예요? 드레스 입고요?"),
(J, "Avec des robes, des costumes et des petits fours. Je commande un smoking dès ce soir.", "드레스에 정장에 작은 카나페까지. 오늘 저녁부터 턱시도 주문할 거야."),
(H, "Julien, on a un service dans deux heures. Un service. Tu te souviens ?", "쥘리앵, 두 시간 뒤에 서비스가 있어. 서비스. 기억나?"),
(J, "Pardon. Oui. Bien sûr. Je redescends sur terre. Pas tout de suite, mais bientôt.", "미안. 그래, 물론이지. 현실로 돌아올게. 당장은 아니고 곧."),
(C, "Moi, je suis sur un nuage. Je crois que je vais flotter jusqu'à midi.", "저는 구름 위에 있어요. 정오까지 둥둥 떠다닐 것 같아요."),
(L, "Le mot est « aux anges », Chloé. On dit : je suis aux anges.", "그 말은 '천사들 곁에'란다, 클로에. '나는 지금 천국에 있다'고 하지."),
(C, "Je suis aux anges ! Je le note tout de suite !", "저는 천국에 있어요! 바로 적어야지!"),
(None, "Chloé sort son carnet et écrit à toute vitesse. Un téléphone sonne dans le bureau.", "클로에가 수첩을 꺼내 아주 빠르게 받아 적는다. 사무실에서 전화가 울린다."),
(J, "Je réponds. C'est peut-être déjà Bastide qui a flairé quelque chose.", "내가 받을게. 벌써 바스티드가 냄새를 맡았을지도 몰라."),
(H, "Attends. On le dit à qui, et quand ? La lettre dit qu'on peut l'annoncer ?", "잠깐. 누구에게 언제 알려야 해? 편지에는 발표해도 된다고 적혀 있어?"),
(J, "Laisse-moi lire. « Le guide paraîtra le premier septembre. Vous pouvez annoncer votre distinction dès réception. »", "읽어 볼게. '가이드는 9월 1일에 나옵니다. 수령 즉시 선정 사실을 알리셔도 좋습니다.'"),
(H, "D'accord. Alors on commence par ceux qui nous ont portés.", "좋아. 그럼 우리를 떠받쳐 준 사람들부터 알리자."),
(C, "Mme Vasseur ! Elle fête ses quatre-vingts ans mardi, ça lui fera un cadeau !", "바세르 부인! 화요일이 80세 생신인데 선물이 되겠네요!"),
(L, "Mme Vasseur, Bastide, les producteurs, Victor aussi. Tous ceux qui ont tendu la main.", "바세르 부인, 바스티드, 생산자들, 빅토르도. 손을 내밀어 준 모든 사람들이지."),
(H, "Victor ? Papa, il nous a fait concurrence tout l'été.", "빅토르요? 아빠, 그 사람은 여름 내내 우리 경쟁자였잖아요."),
(L, "Il t'a aussi proposé de t'aider cet hiver. Un ennemi qui tend la main, c'est un ami en retard.", "겨울에는 널 도우려고도 했다. 손을 내미는 적은 조금 늦은 친구란다."),
(H, "Un ami en retard... Bon, d'accord. Je lui apporte une bouteille.", "조금 늦은 친구라... 알았어요. 와인 한 병 갖다줄게요."),
(J, "Une bouteille de Brouilly ? Pour ne pas se tromper ?", "브루이 한 병? 실패 안 하려면?"),
(L, "Du Brouilly, oui. Et une pour moi, si le docteur ne regarde pas.", "브루이 맞다. 그리고 의사 모르게 내 것도 한 병."),
(H, "Une seule gorgée, Papa. Le docteur l'a dit : une gorgée pour fêter ça.", "한 모금만이에요, 아빠. 선생님이 그러셨어요. 축하용으로 한 모금."),
(L, "Une gorgée ! Quelle tyrannie. Mais pour deux fourchettes, j'accepte.", "한 모금이라니! 폭정이로군. 하지만 포크 두 개를 위해서라면 받아들이지."),
(J, "Bon. Moi, je propose qu'on monte la formule. Vingt-quatre euros le midi, au lieu de vingt-deux.", "자, 내 제안인데 포뮬 가격을 올리자. 점심 22유로 말고 24유로로."),
(H, "Non. On ne touche pas aux prix.", "안 돼. 가격은 건드리지 않아."),
(J, "Même pas deux euros ? Allez, juste pour l'effet « deux fourchettes » !", "2유로도 안 돼? 그냥 '포크 두 개' 효과로!"),
(H, "Non. Les gens qui nous ont soutenus ne paieront pas plus parce qu'on a gagné un prix.", "안 돼. 우리를 응원해 준 사람들이 상을 받았다고 더 내게 하진 않아."),
(L, "C'est ça, la fidélité à son histoire. Bien dit, ma fille.", "그게 바로 자기 역사에 충실하다는 거다. 잘 말했다, 얘야."),
(J, "Bon, bon, c'est noté. Je lâche l'affaire, chef.", "알았어, 알았어, 접수. 포기할게요, 셰프."),
(H, "Chloé, prends une craie. Tu écris la nouvelle sur l'ardoise, sous la phrase de Marthe.", "클로에, 분필 들어. 칠판에 소식을 써. 마르트의 문장 아래에."),
(C, "Moi ? Mais c'est ta place, l'ardoise !", "저요? 하지만 칠판은 엘렌의 자리잖아요!"),
(H, "Plus aujourd'hui. Écris, la future sous-gérante. Fais-moi plaisir.", "오늘은 아니야. 써, 미래의 부매니저. 부탁이야."),
(C, "Alors... « Deux fourchettes. Merci à vous. » C'est bien comme ça ?", "그럼... '포크 두 개. 감사합니다.' 이렇게 하면 돼요?"),
(L, "Parfait. Court, simple, vrai. Comme la cuisine de Marthe.", "완벽하구나. 짧고, 단순하고, 진실되지. 마르트의 요리처럼."),
(None, "Karim sort enfin de la cuisine, les yeux rouges, et lève le poing. Tout le monde éclate de rire.", "카림이 마침내 눈이 빨개진 채 주방에서 나와 주먹을 치켜든다. 모두가 웃음을 터뜨린다."),
(H, "Karim, retourne à tes fourneaux ! On ouvre dans deux heures.", "카림, 화덕으로 돌아가! 두 시간 뒤에 열어."),
(J, "Il dit qu'il a tout compris, mais qu'il ne peut pas parler. Il a la gorge nouée.", "다 이해했는데 말을 못 한대. 목이 메었다네."),
(L, "Allez. Ma permission est terminée. Julien, appelle-moi un taxi.", "자. 내 휴가는 끝났다. 쥘리앵, 택시 불러 다오."),
(H, "Pas de taxi. Je te ramène moi-même, après le service.", "택시는 안 돼요. 서비스 끝나고 제가 직접 모셔다드릴게요."),
(L, "Tu ne peux pas. Tu as des clients, des fourchettes à honorer.", "넌 못 간다. 손님이 있고, 지켜야 할 포크가 있지."),
(J, "Je le raccompagne, moi. Chloé gère la salle une demi-heure, elle est prête.", "내가 모셔다드릴게. 클로에가 30분은 홀을 볼 수 있어. 준비됐으니까."),
(C, "Oui ! Je suis prête ! Enfin, un peu. Enfin... aux anges, mais prête !", "네! 준비됐어요! 아니, 조금요. 아니... 천국에 있지만 준비됐어요!"),
(None, "Le téléphone sonne de nouveau, insistant. Hélène regarde l'ardoise, puis la photo de Marthe au-dessus de la caisse.", "전화가 다시 끈질기게 울린다. 엘렌이 칠판을 보고, 계산대 위 마르트의 사진을 바라본다."),
(H, "Allô ? Le Comptoir de Marthe, bonjour. Oui... oui, c'est bien ici.", "여보세요? 콩투아르 드 마르트입니다. 네... 네, 맞아요 여기예요."),
(H, "Pour ce soir ? Je regarde... Oui. Pour combien de personnes ?", "오늘 저녁이요? 확인해 볼게요... 네. 몇 분이세요?"),
(H, "Six personnes, à vingt heures. Avec plaisir. On vous attend.", "여섯 분, 8시요. 기꺼이요. 기다리고 있겠습니다."),
]

VOCAB = [
("A2", "Merci à vous. / Bonjour, ma fille.", "여러분께 감사합니다. / 안녕, 얘야.", "칠판 문구 〈Merci à vous〉 와 Lucien의 호칭 〈ma fille〉. 짧고 따뜻한 인사·감사 표현."),
("B1", "[구어] Qu'est-ce que tu fais là ?", "여기서 뭐 하는 거야?", "예상 못 한 곳에서 누구를 만났을 때. ↔ 정중: 〈Que faites-vous ici ?〉"),
("B1", "[구어] Je te jure que...", "맹세코 ...", "〈Je jure que je t'emmène aux urgences !〉 과장된 협박. 가까운 사이 구어. ↔ 정중: 〈Je vous assure que…〉"),
("B1", "Pince-moi !", "나 좀 꼬집어 줘! (꿈 아니지?)", "믿기지 않는 기쁨에. 〈Dis-moi que je rêve !〉 와 함께 쓴다. 〈Aïe !〉 는 아플 때."),
("B1", "C'est pas vrai ! / C'est dingue !", "말도 안 돼! / 미쳤다!", "놀람과 기쁨의 구어 감탄. ne 생략. ↔ 정중: 〈C'est incroyable.〉"),
("B1", "[구어] Je lâche l'affaire.", "포기할게 / 그만할게", "〈lâcher l'affaire〉 = 그 일에서 손을 떼다. Julien의 가격 인상 제안 철회. ↔ 정중: 〈J'abandonne cette idée.〉"),
("B2", "Je n'en reviens pas. / Je suis aux anges.", "믿기지 않아요. / 너무 행복해요.", "〈être aux anges〉 = 천국에 있는 듯 행복하다. Lucien이 Chloé에게 가르쳐 준 표현. 〈sur un nuage〉 도 같은 계열."),
("B2", "avoir la chair de poule", "소름이 돋다", "〈J'en ai la chair de poule !〉 감동과 공포 둘 다에 쓴다. 팔을 가리키며 말하는 몸짓과 함께."),
("B2", "avoir la gorge nouée", "목이 메다", "〈Il a la gorge nouée.〉 감정이 북받쳐 말이 안 나올 때. 〈avoir un nœud dans la gorge〉 도 같은 뜻."),
("B2", "décerner un prix / être distingué de deux fourchettes", "상을 수여하다 / 포크 두 개로 선정되다", "〈Notre jury a décidé de vous décerner…〉 공식 편지의 정중한 문어체. Hélène이 낭독한 뒤 구어로 반응한다."),
("B2", "écrit noir sur blanc", "분명히 문서로 적힌", "〈C'est écrit noir sur blanc !〉 증거가 분명할 때. 문어·구어 모두 자연스러운 관용구."),
("B2", "la remise du prix", "시상식, 수상", "〈La remise du prix aura lieu le quatorze septembre.〉 〈remettre un prix〉 의 명사형. 미래형 〈aura lieu〉 로 일정을 알린다."),
("B2", "Après tout ce qu'on a traversé !", "우리가 겪은 모든 일을 생각하면!", "〈traverser〉 는 '건너다' 에서 '(시련을) 겪다' 로. 결과가 나온 뒤 지난 어려움을 돌아보는 표현."),
("B2", "[속어] Putain, on l'a fait.", "젠장, 해냈어.", "기쁨의 감탄으로 쓰인 〈putain〉. 쓸 수 있음: 가까운 직원·가족 사이 / 금지: 손님·심사위원·외부인 앞. 4부 이후 안도의 〈putain〉 과 같은 용법."),
("B2", "[구어] Elle a de l'humour, cette petite.", "이 아이 유머가 있네.", "〈cette petite〉 를 뒤로 보낸 구어 도치(문장 끝 강조). ↔ 정중: 〈Cette jeune fille a de l'humour.〉"),
("C1", "Mauvaise herbe ne meurt jamais.", "잡초는 절대 죽지 않는다", "속담 〈Mauvaise herbe croît toujours〉 의 변형. 고집 센 사람의 건재를 자랑스럽게 말한다. 관사 없이 쓰는 속담 어순에 주의."),
("C1", "Un ennemi qui tend la main, c'est un ami en retard.", "손을 내미는 적은 조금 늦은 친구다", "Lucien의 즉흥 격언. 〈tendre la main〉 = 화해·도움의 손을 내밀다. 〈Victor〉 에 대한 시선 변화를 담는다."),
("C1", "Lâcher la casserole / Il a lâché sa casserole.", "냄비를 떨어뜨리다 (놀라서 손을 놓다)", "〈lâcher〉 는 '놓다, 떨어뜨리다'. 놀람의 몸짓을 서술할 때. 비유적 〈lâcher quelqu'un〉(버리다)과 구별: 〈Personne nous a lâchés.〉"),
("C1", "Une cuisine sincère, généreuse et fidèle à son histoire.", "진솔하고 넉넉하며 자기 역사에 충실한 요리", "비평문의 전형적인 형용사 삼중 나열. 〈fidèle à + 명사〉 = ~에 충실한. Lucien이 되풀이하며 의미를 확인한다."),
("C1", "Les récompenses, c'est pour ceux qui ont le temps.", "상은 시간이 남는 사람들 몫이다", "〈C'est pour + 사람〉 구어 구문. Marthe의 겸손한 철학을 Lucien이 인용한다."),
("C1", "Je redescends sur terre.", "현실로 돌아온다", "기쁨에 들뜬 뒤 정신을 차릴 때. 〈être sur un nuage〉(구름 위에 있다)의 반대 이미지. Julien이 두 번 연속 쓰는 비유."),
("C1", "porter sur son dos / On l'a porté à plusieurs.", "등에 짊어지다 / 여럿이 함께 짊어졌다", "책임·부담의 은유. 〈à plusieurs〉 = 여럿이서. 승리의 순간 혼자가 아님을 말하는 Hélène의 핵심 대사."),
("B2", "Fais-moi plaisir.", "부탁이야 (내 기쁨을 위해 해 줘)", "〈faire plaisir à quelqu'un〉 의 명령형. 부드러운 지시를 부탁으로 바꾼다. Hélène이 Chloé에게 칠판을 맡기며 한 말. 〈Ça fait plaisir.〉 는 '기쁘네'."),
]

GRAM = [
("B2", "감탄문 — 구어 감탄의 도구상자", "〈C'est pas vrai !〉 〈Je n'en reviens pas !〉 〈Quelle tyrannie !〉 〈Oh, la tête !〉 〈Qu'est-ce qu'elle est belle !〉. 감탄은 〈quel + 명사〉, 〈que/qu'est-ce que + 문장〉, 〈C'est + 형용사〉, 짧은 독립 명사구 〈La tête !〉 등으로 만든다. 구어에서는 ne 를 생략한다."),
("B2", "수여·결과 발표의 문어 → 구어로 낮추기", "〈Notre jury a décidé de vous décerner le prix.〉 (문어) → 〈Ils nous donnent un prix !〉 (구어). 공식 편지는 낭독하고 곧바로 〈Deux fourchettes ! Dis-moi que je rêve !〉 처럼 구어로 반응하는 대비가 이 화의 리듬."),
("B2", "명령형 + 대명사 — 두 개의 대명사", "〈Donne-la-moi.〉 〈Rends-la-moi.〉 〈Ouvre-la.〉 〈Laisse-moi lire.〉 긍정 명령에서는 직접목적어(la) → 간접목적어(moi) 순으로 동사 뒤에 하이픈으로 붙인다. 부정은 〈Ne me la donne pas.〉"),
("B2", "조건법 — 과거에서의 약속·미래", "〈Il a promis qu'ils seraient aussi beaux que les tiens.〉 〈Je savais qu'il avait une tête de critique.〉 주절이 과거이면 종속절의 미래는 조건법 현재로 바뀐다. 〈Elle a dit qu'elle viendrait.〉"),
("C1", "le + 형용사화 표현 / 강조 후치 — cette petite", "〈Elle a de l'humour, cette petite.〉 〈Il est tout pâle, Lucien.〉 〈Elle est déjà à moitié finie, ma permission.〉 주어를 대명사로 먼저 말하고 구체적 명사를 뒤에 덧붙이는 구어 어순. 감정을 강조한다."),
("B2", "시간 부사 — dès, tout de suite, pas tout de suite", "〈Dès ce soir〉 〈Tout de suite !〉 〈Pas tout de suite, mais bientôt.〉 〈Dès réception.〉 시점의 즉시성을 조절한다. 편지 문어에서는 〈dès réception〉, 구어에서는 〈tout de suite〉."),
("C1", "enchaînement de 감정 + 몸 — 신체 표현으로 감정 말하기", "〈J'ai la chair de poule.〉 〈Il a la gorge nouée.〉 〈Je sens plus mes jambes.〉 〈Mes yeux voient flou.〉 감정을 신체 증상으로 묘사한다. 〈avoir + 신체 부위 + 상태〉 구문이 반복된다."),
]

READ = [
("감탄의 억양 — C'est pas vrai !", "〈AAAH ! / C'est pas vrai ! / C'est pas vrai !〉 첫 〈C'est pas vrai〉 는 높게, 두 번째는 더 높게 시작해 끝을 내린다. 〈pas〉 가 가장 길고 강하다. 〈AAAH〉 는 입을 크게 벌려 길게."),
("공식 편지 낭독 — 쉼표와 호흡", "〈Madame Marchand, / c'est avec grand plaisir / que nous vous informons… / que le Comptoir de Marthe / est distingué / de deux fourchettes.〉 문어체는 천천히, 쉼표마다 호흡. 〈deux fourchettes〉 는 [dø fuʁʃɛt] 로 ‘fourchette’ 의 ou 는 [u]."),
("리에종 — tout_à l'heure, c'est_écrit", "〈C'est_écrit noir sur blanc !〉 〈Il a_été〉 〈Ils_ont gagné〉 모음 앞에서 s, t 를 이어 읽는다. 〈noir sur blanc〉 는 [nwaʁ syʁ blɑ̃] 로 r 을 목 안쪽에서."),
("숫자·날짜 — vingt-deux décembre, quatorze septembre", "〈le vingt-deux décembre〉 [lə vɛ̃t dø desɑ̃bʁ] 〈le quatorze septembre〉 [lə katɔʁz sɛptɑ̃bʁ]. 날짜는 〈le + 숫자 + 월〉 의 리듬으로, 숫자 뒤에서 한 박자 쉰다. 〈trente-cinq ans〉 도 연습."),
("울먹이는 대사 — 문장 끝 흐리기와 반복", "〈Trente-cinq ans, Hélène. / Trente-cinq ans, / et jamais une seule.〉 반복은 두 번째가 더 낮고 느리게. 〈jamais une seule〉 앞에서 숨을 들이마시고 끝은 소리를 줄인다."),
("자음 충돌 — Je n'en reviens pas", "〈Je n'en reviens pas !〉 구어에서 〈J'en reviens pas〉 [ʒɑ̃ ʁəvjɛ̃ pa]. 비음 〈en〉 [ɑ̃] 과 〈viens〉 [vjɛ̃] 의 비음을 구분해서 읽는다. 〈aux anges〉 [o zɑ̃ːʒ] 는 s가 z로 이어진다."),
("웃음과 눈물 사이 — 속도 조절", "〈Pardon. Oui. Bien sûr. Je redescends sur terre. Pas tout de suite, mais bientôt.〉 짧은 문장을 점점 느리게. ‘Pas tout de suite’ 에서 웃음을 담고, ‘mais bientôt’ 에서 가볍게 올린다."),
]

CULTURE = [
("가이드와 ‘포크’ 평가 — 익명 심사의 세계", "프랑스에는 미슐랭 외에도 고미요 등 여러 미식 가이드가 있고, 심사원은 대개 신분을 밝히지 않고 여러 번 익명으로 식사한 뒤 평가를 정한다. 이 이야기의 ‘Guide Lacroix’ 는 가상의 가이드로, 별 대신 포크(fourchette)를 쓰며 세 개가 최고다. 식당 주인은 평소 평범한 손님 중 누가 심사원인지 알 수 없으므로, 늘 같은 수준으로 요리하는 것이 유일한 방법이다."),
("프랑스식 기쁨과 눈물 — ‘être aux anges’", "프랑스인은 큰 기쁨 앞에서 소리를 지르고 껴안고, 거침없이 울기도 한다. 직장 동료나 가족 사이에서는 〈Putain〉 같은 속어도 기쁨의 감탄사가 될 수 있지만 손님·외부인 앞에서는 쓰지 않는다. 이 화에서 클로에는 새 표현 ‘être aux anges’ 를 수첩에 적는데, 이렇게 감정의 순간에 만난 어휘가 가장 오래 기억에 남는다."),
]

META = dict(part=5, ep=72, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="Le courrier du guide", title_ko="가이드의 편지",
 place="파리 11구 Le Comptoir de Marthe 홀 · 6월 19일 토요일, 오전 9시 40분",
 chars="Hélène Marchand (주인 겸 셰프) · Lucien Marchand (아버지, 퇴원 3일째) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버)",
 wine="Guide Lacroix의 등기 편지: 포크 두 개와 올해의 재건상 — 기쁨과 눈물의 폭발",
 focus="기쁨·감정 폭발·감탄 표현(C'est pas vrai ! Je suis aux anges), 신체로 말하는 감정, 편지 낭독→구어 반응, 명령형+대명사, 조건법 약속, 관용구",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제73화 « Mme Vasseur fête ses quatre-vingts ans » : 화요일 저녁, 바세르 부인의 80세 생일 잔치와 축사, 회고")
