# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, L, J, V = "Hélène", "Lucien", "Julien", "Mme Vasseur"
D = [
(None, "Mardi 22 juin, dix-huit heures trente. Le Comptoir est fermé au public. Les tables forment une seule grande tablée. Julien accroche une guirlande.", "6월 22일 화요일, 오후 6시 30분. 콩투아르는 일반 손님에게 닫혀 있다. 테이블들이 하나의 긴 식탁으로 이어져 있다. 줄리앙이 꽃줄을 단다."),
(J, "Hélène, la guirlande, elle est droite ?", "엘렌, 꽃줄 똑바로 걸렸어요?"),
(H, "Elle penche à gauche. Un peu plus haut... Voilà.", "왼쪽으로 기울었어. 조금만 더 위로... 됐어."),
(J, "Quatre-vingts ans, ça se fête. Même si la fêtée râle.", "여든 살이면 축하해야죠. 주인공이 투덜대도요."),
(H, "Elle a râlé trois semaines. « Pas de fête, pas de gâteau, pas de chichis. »", "삼 주 내내 투덜댔지. 「잔치도 케이크도 호들갑도 싫어」라고."),
(J, "Et elle a demandé l'heure, le menu et la liste des invités.", "그러면서 시간이랑 메뉴랑 초대 손님 명단은 다 물어봤죠."),
(H, "C'est sa façon de dire oui.", "그게 그분이 승낙하는 방식이니까."),
(J, "Vous avez fait quoi, pour le dessert ?", "디저트는 뭘로 하셨어요?"),
(H, "Une tarte à la rhubarbe. Avec sa confiture, celle de l'année dernière.", "대황 타르트. 작년에 그분이 주신 잼으로."),
(J, "Ah, c'est malin. Elle ne pourra pas critiquer sa propre confiture.", "아, 영리하네요. 자기 잼은 타박 못 하겠어요."),
(H, "Elle trouvera quelque chose. Elle trouve toujours.", "뭔가 찾아낼 거야. 늘 찾아내니까."),
(L, "Bonsoir, bonsoir ! Je suis là, avec le discours !", "안녕, 안녕! 연설문 들고 왔다!"),
(H, "Papa, tu devais te reposer jusqu'à sept heures.", "아빠, 일곱 시까지 쉬기로 하셨잖아요."),
(L, "Je me suis reposé. Dix minutes, dans le taxi. Le médecin sera content.", "쉬었다. 택시에서 십 분. 의사도 좋아하겠지."),
(J, "Monsieur Lucien, asseyez-vous. Je vous apporte un verre d'eau.", "뤼시앵 씨, 앉으세요. 물 한 잔 가져올게요."),
(L, "De l'eau ? Pour un anniversaire ? Mon cardiologue n'a pas dit « pas de vin ». Il a dit « peu ».", "물이라니, 생일잔치에? 심장 의사가 「와인 금지」라고는 안 했어. 「조금만」이라고 했지."),
(H, "Un verre. Un seul. Je compte.", "한 잔. 딱 한 잔이에요. 제가 셀 거예요."),
(L, "Tu comptes comme ta mère. Elle comptait aussi, et je trichais.", "네 엄마처럼 세는구나. 엄마도 셌고, 난 속였지."),
(J, "Chut, la voilà ! Elle est en avance de cinq minutes.", "쉿, 오셨어요! 오 분 일찍 오셨네요."),
(None, "Madame Vasseur entre, chapeau bleu, robe du dimanche, un petit sac à la main. Elle s'arrête sur le seuil.", "바세르 부인이 파란 모자에 나들이 원피스 차림으로, 작은 가방을 들고 들어온다. 문턱에서 멈춰 선다."),
(V, "Bonsoir. Il y a une guirlande. Je n'avais pas dit de guirlande.", "안녕하세요. 꽃줄이 있네. 꽃줄은 말한 적이 없는데."),
(J, "Bonsoir, madame Vasseur. Joyeux anniversaire, avec deux jours de retard !", "안녕하세요, 바세르 부인. 이틀 늦었지만 생일 축하드려요!"),
(V, "Deux jours de retard, c'est déjà trop. À mon âge, on compte les jours.", "이틀 늦은 것도 너무 늦은 거예요. 이 나이엔 하루하루를 세거든."),
(H, "Bonsoir, madame Vasseur. Joyeux anniversaire. Vous êtes très élégante.", "안녕하세요, 바세르 부인. 생일 축하드려요. 아주 우아하세요."),
(V, "Élégante ? Je suis une vieille dame. Mais le chapeau est neuf, ça, c'est vrai.", "우아? 난 늙은 할머니예요. 그래도 모자가 새것인 건 맞네."),
(L, "Madame Vasseur, vous ne les faites pas du tout, vos quatre-vingts ans.", "바세르 부인, 여든으로는 전혀 안 보이십니다."),
(V, "Lucien, vous mentez mal. Vous avez toujours menti mal.", "뤼시앵, 거짓말 참 못하시네. 늘 그랬어요."),
(L, "Je ne mens jamais devant une dame. Je flatte. C'est différent.", "숙녀 앞에서 거짓말은 안 합니다. 아부하는 거죠. 다릅니다."),
(V, "Même chose. Où est ma table ? Où est la sept ?", "그게 그거예요. 내 자리가 어디죠? 7번이 어디 있어요?"),
(H, "Elle est au milieu de la tablée. Vous êtes la reine de la soirée.", "긴 식탁 한가운데 있어요. 오늘 저녁의 여왕이시니까요."),
(V, "Au milieu ? Tout le monde va me regarder manger. Je déteste ça.", "한가운데? 다들 내가 먹는 걸 쳐다보겠네. 질색인데."),
(J, "Alors on regardera les assiettes, pas vous. Promis.", "그럼 부인 말고 접시를 볼게요. 약속해요."),
(V, "Ah. Ils sont déjà tous là ? Je ne vois que des visages connus.", "아. 벌써 다들 와 있나? 아는 얼굴들뿐이네."),
(None, "Autour de la table : des habitués, M. Bastide, Victor, Chloé et Karim en tablier. À la place voisine de la sept, un verre vide.", "식탁 둘레에는 단골들, 바스티드 씨, 빅토르, 앞치마 차림의 클로에와 카림이 있다. 7번 옆자리에는 빈 잔이 하나 놓여 있다."),
(V, "Qui a posé ce verre ?", "누가 저 잔을 놓았어요?"),
(H, "C'est pour Henri. On l'a toujours fait, le jeudi. Je me suis dit...", "앙리 씨 몫이에요. 목요일마다 늘 그랬죠. 그래서 제 생각에..."),
(V, "Vous vous êtes dit quoi, ma petite ?", "무슨 생각을 했다는 거예요, 아가씨?"),
(H, "Qu'il serait venu. Et qu'il aurait commandé son steak bien cuit.", "그분도 오셨을 거라고요. 바싹 익힌 스테이크를 주문하셨겠죠."),
(V, "Et qu'il se serait plaint de la sauce. Comme moi. Merci, Hélène.", "그리고 소스 타박을 했겠지. 나처럼. 고마워요, 엘렌."),
(J, "Madame, on vous sert un kir ? Un petit. Un tout petit.", "부인, 키르 한 잔 드릴까요? 작은 걸로요. 아주 작은 걸로."),
(V, "Mon médecin dit non. Mais mon médecin n'a que quarante ans.", "의사는 안 된다고 하지. 그런데 우리 의사는 마흔 살밖에 안 됐어요."),
(L, "Quarante ans ! Un enfant. Servez le kir, Julien, je prends la responsabilité.", "마흔! 애송이지. 키르 내오게, 줄리앙. 내가 책임지겠네."),
(V, "Cette blanquette, c'est bien celle de Marthe. La viande est tendre. La sauce manque d'un peu de citron. Mais c'est bon.", "이 블랑케트, 마르트 방식 맞네. 고기는 부드럽고. 소스에 레몬이 조금 부족해. 그래도 맛있어요."),
(H, "Merci, madame. Je note le citron.", "감사합니다, 부인. 레몬은 적어 둘게요."),
(V, "Vous notez toujours. Marthe, elle, se vexait d'abord, et notait après.", "엘렌은 늘 적네. 마르트는 먼저 토라지고 나서 적었는데."),
(J, "Mesdames, messieurs, un instant ! Je voudrais dire deux mots.", "신사 숙녀 여러분, 잠깐만요! 한마디 하고 싶습니다."),
(V, "Deux mots. Pas plus. Je vous surveille, Julien.", "딱 두 마디예요. 더는 안 돼요. 지켜보고 있어요, 줄리앙."),
(J, "Alors voilà. Madame Vasseur, vous avez quatre-vingts ans depuis dimanche.", "자, 그럼요. 바세르 부인, 일요일부터 여든이 되셨습니다."),
(V, "Je sais, merci. Je suis là quand même.", "알아요, 고마워요. 그래도 아직 여기 있잖아요."),
(J, "Oui. Et c'est ça, le plus beau cadeau. Vous êtes là.", "네. 그게 가장 큰 선물이에요. 여기 계시다는 것."),
(H, "Bravo, Julien. Continue, ça démarre bien.", "잘한다, 줄리앙. 계속해, 시작이 좋아."),
(J, "Ça fait presque dix ans que je vous sers. Vous m'avez jamais dit merci.", "거의 십 년째 부인을 모셨죠. 한 번도 고맙다고 안 하셨어요."),
(V, "Et vous, vous m'avez jamais servie à l'heure, jeune homme.", "당신은 한 번도 제시간에 내오지 않았고요, 젊은이."),
(L, "Ha ! Touché, Julien ! Un point pour la dame !", "하! 한 방 먹었네, 줄리앙! 부인이 한 점 땄군!"),
(J, "J'accepte. Alors voilà. Chez nous, on dit : « Mme Vasseur, c'est le thermomètre. »", "인정합니다. 그러니까요. 저희끼리는 「바세르 부인은 온도계」라고 해요."),
(V, "Le thermomètre ? Je suis malade, maintenant ?", "온도계? 이젠 내가 환자예요?"),
(J, "Non, madame ! Si vous êtes contente, la soirée est bonne. Si vous râlez, on corrige.", "아니에요! 부인이 만족하시면 오늘 영업은 좋은 거고, 투덜대시면 고치는 거죠."),
(H, "C'est vrai. Vingt ans de critiques, vingt ans de progrès.", "맞아요. 이십 년 비평, 이십 년 발전이죠."),
(J, "Alors voilà. À madame Vasseur, notre meilleure critique !", "그러니까요. 우리 최고의 비평가, 바세르 부인을 위해!"),
(H, "À toi, Papa. Fais court. S'il te plaît. Je te le demande gentiment.", "아빠 차례예요. 짧게 하세요. 제발요. 좋게 부탁드리는 거예요."),
(L, "Court ? Je suis un orateur, ma fille. Un orateur ne fait pas court.", "짧게? 난 연설가다, 얘야. 연설가는 짧게 안 한다."),
(J, "Monsieur Lucien, trois minutes. Je chronomètre.", "뤼시앵 씨, 삼 분입니다. 제가 잴게요."),
(L, "Alors voilà. Madame Vasseur... Jeanne. Je peux dire Jeanne, ce soir ?", "자, 그럼. 바세르 부인... 잔. 오늘 밤만 잔이라 불러도 되겠소?"),
(V, "Ce soir seulement. Et sans en faire une habitude.", "오늘 밤만이에요. 버릇 들이지는 말고."),
(L, "Merci, Jeanne. Alors voilà. Je vous ai connue en 1996.", "고맙소, 잔. 그러니까요. 나는 1996년에 당신을 알게 됐지."),
(V, "Pas 1996. 1997. Au mois de mars. Il pleuvait.", "1996년이 아니에요. 1997년. 3월. 비가 왔고."),
(L, "Elle se souvient de tout. Elle se souvient de la pluie !", "모든 걸 기억하는군. 비 오던 날까지!"),
(H, "Papa, tu perds du temps. Va au cœur.", "아빠, 시간 끌잖아요. 핵심으로 가세요."),
(L, "J'y vais. Alors voilà. Un jour de mars, Marthe m'a dit : « Cette dame, elle reviendra. »", "가요. 그러니까요. 어느 3월 날, 마르트가 말했소. 「저 부인, 다시 올 거야.」"),
(V, "Elle m'avait trouvée trop bavarde, ce jour-là, je crois.", "내가 그날 말이 너무 많다고 생각했던 것 같은데."),
(L, "Non. Elle a dit : « Elle aime la table, pas seulement la cuisine. »", "아니오. 이렇게 말했지. 「저 사람은 음식만이 아니라 식탁을 좋아해.」"),
(J, "C'est joli. Je n'avais jamais entendu cette phrase.", "예쁜 말이네요. 처음 들어요."),
(L, "Elle disait : « Une bonne cliente, c'est une table qui revient. »", "아내는 이렇게 말했지. 「좋은 손님은 다시 오는 식탁이야.」"),
(V, "Marthe disait beaucoup de choses. Elle ne gardait pas ses opinions.", "마르트는 말이 많았죠. 의견을 속에 담아 두지 않았어요."),
(L, "Comme vous, Jeanne. Vous êtes sœurs de caractère. Voilà ma conclusion.", "당신처럼 말이오, 잔. 성격이 자매 같았지. 이게 내 결론이오."),
(H, "Ta conclusion ? Mais tu n'as pas fait la moitié du discours !", "결론이라니요? 연설 반도 안 하셨잖아요!"),
(L, "Le reste, c'est du gras. Un bon discours, c'est comme une bonne sauce : on réduit.", "나머진 군더더기다. 좋은 연설은 좋은 소스와 같아서, 졸이는 거지."),
(J, "Cinquante secondes ! Record battu, monsieur Lucien.", "오십 초! 신기록이에요, 뤼시앵 씨."),
(L, "Je lève mon verre. À Jeanne Vasseur, qui a dû nous supporter longtemps.", "건배합시다. 오래도록 우릴 참아 주신 잔 바세르를 위해."),
(V, "Tout le monde boit, personne ne contredit. Ça me vexe un peu.", "다들 마시기만 하고 아무도 반박을 안 하네. 좀 서운한데."),
(H, "Alors je vais contredire. Vous n'avez pas « supporté ». Vous avez porté la maison.", "그럼 제가 반박할게요. 부인은 우릴 「참아 준」 게 아니에요. 이 가게를 떠받쳐 주셨죠."),
(V, "Ah. Là, vous exagérez, ma petite.", "아. 그건 과장이네요, 아가씨."),
(H, "Alors voilà. Il y a trois ans, je reprenais le Comptoir et je ne savais pas faire.", "그러니까요. 삼 년 전 제가 콩투아르를 이어받았을 땐 아무것도 몰랐어요."),
(V, "Vous saviez cuisiner. Vous ne saviez pas sourire. Ce n'est pas pareil.", "요리는 할 줄 알았지. 웃을 줄을 몰랐고. 그건 다른 문제죠."),
(H, "Et vous m'avez dit, le premier jeudi : « Cette soupe est trop salée. »", "그리고 첫 번째 목요일에 말씀하셨죠. 「이 수프는 너무 짜요.」"),
(V, "Elle l'était. Tout le monde n'a pas le courage de le dire.", "정말 짰으니까요. 누구나 그걸 말할 용기가 있는 건 아니죠."),
(H, "Personne ne l'avait dit. J'étais furieuse. Puis j'ai goûté. Vous aviez raison.", "아무도 말 안 했어요. 화가 났죠. 그리고 맛을 봤어요. 부인 말씀이 맞았어요."),
(L, "Voilà pourquoi je dis : les critiques, c'est le sel de la vie.", "그래서 내가 말하지. 비판은 인생의 소금이라고."),
(H, "Papa, le sel, justement, on y revient. Bref. Madame Vasseur...", "아빠, 소금 얘기로 돌아오지 마세요. 어쨌든, 바세르 부인..."),
(H, "Quand le Comptoir a failli fermer, vous avez fait signer deux cent quatorze personnes.", "콩투아르가 문을 닫을 뻔했을 때, 부인은 이백십사 명에게 서명을 받아 주셨어요."),
(V, "Deux cent quatorze. Et trois qui ont refusé. Je les ai notés.", "이백십사 명. 거절한 사람은 셋이었고요. 적어 뒀죠."),
(J, "Elle a même fait signer le facteur. Il a signé deux fois.", "우체부한테까지 서명을 받았어요. 두 번 서명했죠."),
(H, "Alors voilà. Merci, madame Vasseur. Merci pour la soupe, et pour le reste.", "그러니까요. 고맙습니다, 바세르 부인. 수프도, 나머지 모든 것도요."),
(V, "Ne pleurez pas dans la blanquette, ça va la rendre trop salée.", "블랑케트에 울지 말아요, 너무 짜지니까."),
(H, "Je ne pleure pas. C'est le citron, madame. Il en manquait.", "안 울어요. 레몬 때문이에요, 부인. 모자랐거든요."),
(J, "Madame Vasseur, on a une surprise. Hélène, tu l'apportes ?", "바세르 부인, 깜짝 선물이 있어요. 엘렌, 가져올래요?"),
(None, "Hélène revient avec un paquet de papier kraft. Dedans, une serviette de table bleue, brodée d'un « V » à la main.", "엘렌이 크라프트 포장지로 싼 꾸러미를 들고 돌아온다. 안에는 손으로 「V」가 수놓인 파란 냅킨이 들어 있다."),
(V, "Une serviette bleue. La bleue. Où l'avez-vous trouvée ?", "파란 냅킨. 그 파란 냅킨이네. 어디서 찾았어요?"),
(H, "Dans le tiroir du bas. Marthe avait gardé les vieilles. Chloé a brodé le « V ».", "아래 서랍에서요. 마르트가 예전 것들을 간직해 뒀어요. 「V」는 클로에가 수놓았고요."),
(V, "Elle brode mal, la petite. Le « V » penche. J'adore.", "그 아가씨 수는 영 서투르네. 「V」가 기울었어. 마음에 들어요."),
(L, "Il penche comme la guirlande. C'est de famille, ici.", "꽃줄처럼 기울었군. 여긴 집안 내력이야."),
(J, "Et ce n'est pas tout, madame. Regardez la table sept.", "그리고 다가 아니에요, 부인. 7번 테이블을 보세요."),
(None, "Sur la nappe, une petite plaque en laiton : « Table 7 — Madame Vasseur. Réservée depuis toujours. »", "식탁보 위에 작은 황동 명패가 있다. 「7번 테이블 — 바세르 부인. 영원히 예약됨.」"),
(V, "« Depuis toujours ». C'est exagéré. Mais je le garde. Je ne dis rien.", "「영원히」라니, 과장이네. 그래도 받아 두죠. 아무 말 안 할게요."),
(H, "Vous ne dites rien ? Pour la première fois en vingt ans ?", "아무 말도 안 한다고요? 이십 년 만에 처음으로요?"),
(V, "Je dis une chose. Alors voilà. Je n'aime pas les discours. Mais j'en ai un.", "한 가지만 말하죠. 자, 그럼요. 연설은 질색이에요. 그래도 하나 준비했어요."),
(V, "Premièrement, je ne suis pas vieille. Je suis ancienne. Ce n'est pas pareil.", "첫째, 난 늙은 게 아니에요. 오래된 거지. 같은 게 아니라고요."),
(J, "Ancienne ! Comme une belle commode.", "오래된 사람이라! 멋진 서랍장처럼요."),
(V, "Comme une commode, oui. Mais avec de la voix.", "서랍장처럼, 그래요. 목소리가 있는 서랍장."),
(V, "Deuxièmement, merci à tous. Je ne le dirai pas deux fois, alors écoutez.", "둘째, 모두에게 고마워요. 두 번은 안 말할 테니 잘 들어요."),
(L, "On écoute, Jeanne. On écoute de toutes nos oreilles.", "듣고 있소, 잔. 온 귀를 기울이고 있지."),
(V, "Troisièmement. Henri est parti il y a six ans. Je croyais que la vie s'arrêtait.", "셋째. 앙리는 육 년 전에 떠났어요. 삶이 멈추는 줄 알았죠."),
(V, "Alors je suis venue ici, le jeudi. Pour ne pas rester seule avec le silence.", "그래서 목요일마다 여기 왔어요. 침묵과 단둘이 있지 않으려고."),
(H, "On ne l'a jamais su, madame. Vous ne l'avez jamais dit.", "저흰 몰랐어요, 부인. 한 번도 말씀 안 하셨잖아요."),
(V, "Je râlais, pour qu'on me parle. Vous me répondiez. Ça m'a sauvée, mes enfants.", "투덜댔던 건 말을 걸어 주길 바라서였어요. 당신들은 대꾸해 줬고. 그게 날 살렸어요, 얘들아."),
(J, "Madame... on n'a rien fait de spécial. On vous a juste écoutée.", "부인... 저흰 특별한 건 안 했어요. 그냥 들어 드렸을 뿐이에요."),
(V, "Justement. C'est le plus rare. Alors voilà, ma petite blanquette de conclusion.", "그게 바로 가장 드문 거예요. 그러니까요, 이게 내 조촐한 마무리 소스예요."),
(V, "Gardez le Comptoir. Gardez les tables. Gardez les râleurs. Ce sont vos meilleurs clients.", "콩투아르를 지키세요. 식탁들도, 투덜이들도요. 그들이 가장 좋은 손님이니까."),
(L, "Bravo ! Standing ovation ! Enfin, assise, pour mon cœur.", "브라보! 기립 박수! 아니, 내 심장 때문에 앉아서."),
(H, "Maintenant, madame, le dessert. Et pas de remarque sur la confiture.", "이제 디저트예요, 부인. 잼에 대한 지적은 사절이고요."),
(V, "Ma confiture est parfaite. C'est la tarte qui sera à juger.", "내 잼은 완벽해요. 심사받을 건 타르트지."),
(None, "Julien éteint les lumières. Sur la tarte, un « 8 » et un « 0 » en bougies chiffres. Tout le monde chante.", "줄리앙이 불을 끈다. 타르트 위에는 숫자 양초 「8」과 「0」이 꽂혀 있다. 모두가 노래한다."),
(V, "Quatre-vingts bougies, ça aurait mis le feu à la maison. Bonne idée, les chiffres.", "초 여든 개를 꽂았으면 집에 불이 났겠네. 숫자 초는 좋은 생각이에요."),
(H, "Soufflez, madame. Et faites un vœu.", "불어 보세요, 부인. 소원도 빌고요."),
(V, "Mon vœu... Que le Comptoir ait encore quatre-vingts ans. Allez, je souffle.", "내 소원은... 콩투아르가 앞으로 팔십 년을 더 가는 것. 자, 불어요."),
(L, "Quatre-vingts ans de plus ! Elle ne manque pas d'ambition. À la tienne, Jeanne !", "팔십 년을 더라! 야심도 대단하군. 건배, 잔!"),
]

VOCAB = [
("A2", "Joyeux anniversaire !", "생일 축하해요!", "생일 인사. 늦은 축하는 « avec deux jours de retard »처럼 덧붙인다. « Joyeux anniversaire, avec deux jours de retard ! »"),
("A2", "Vous êtes très élégante.", "아주 우아하세요.", "여성 손님께 칭찬. élégant(남) / élégante(여) 발음은 같다. 칭찬에는 « Merci, c'est gentil »로 받는다."),
("A2", "Asseyez-vous.", "앉으세요.", "s'asseoir의 vous 명령형. tu 명령형은 « Assieds-toi ». « Monsieur Lucien, asseyez-vous. »"),
("A2", "Pas de chichis.", "호들갑은 필요 없어요.", "[구어] 격식·호들갑을 거절할 때. ↔ 정중: Sans façon / Pas de cérémonie. « Pas de fête, pas de gâteau, pas de chichis. »"),
("A2", "Je compte les jours.", "하루하루를 세어요.", "compter = 세다 / 헤아리다. 나이 많음에 대한 푸념. « À mon âge, on compte les jours. »"),
("A2", "une guirlande", "꽃줄, 장식 줄", "파티 장식. 칭찬이나 농담에서 « elle penche »(기울었다)와 함께 쓰인다."),
("A2", "Je ne dirai pas deux fois.", "두 번은 말하지 않을 거예요.", "미래형 부정. 연설 도입의 힘주기. « Je ne le dirai pas deux fois, alors écoutez. »"),
("A2", "une serviette de table", "(식탁용) 냅킨", "serviette은 수건 / 냅킨 / 서류가방 모두 가능. 식탁용은 serviette de table 또는 serviette en tissu(천)."),
("B1", "Alors voilà.", "자, 그러니까요.", "[구어] 연설·설명을 시작하거나 매듭지을 때 쓰는 담화표지. ↔ 정중: Je voudrais dire ceci. 짧게 끊고 시작하는 리듬을 만든다."),
("B1", "dire deux mots", "한마디 하다", "연설 도입의 겸손한 관용구. « Je voudrais dire deux mots. » 실제로는 길어지기 십상이라는 농담이 따른다."),
("B1", "râler", "투덜대다", "[구어] ↔ 정중: se plaindre. « Même si la fêtée râle. » 가까운 사이에서만, 애정 섞인 놀림으로 쓰임."),
("B1", "Touché !", "한 방 먹었네!", "펜싱에서 온 말. 상대의 반격에 인정할 때. « Ha ! Touché, Julien ! Un point pour la dame ! »"),
("B1", "fêter / la fêtée", "축하하다 / 축하받는 사람", "fêter quelque chose = ~을 기념하다. « Quatre-vingts ans, ça se fête. » 대명동사의 수동적 용법(ça se fête = 축하받을 만하다)."),
("B1", "faire court", "짧게 하다", "연설·글 길이를 말할 때. « Fais court. » ↔ faire long. 구어로 « Sois bref »보다 자연스럽다."),
("B1", "Je prends la responsabilité.", "내가 책임질게요.", "prendre la responsabilité de + 명사/부정사. 가볍게는 « C'est moi qui assume »."),
("B2", "en faire une habitude", "그걸 버릇으로 만들다", "en faire un/une + 명사 = ~로 삼다. 부정: n'en faites pas une habitude. « Ce soir seulement. Et sans en faire une habitude. »"),
("B2", "aller au cœur du sujet", "핵심으로 가다", "« Va au cœur. » 군더더기를 걷어내고 요점을 말할 때. 비슷한 표현: aller droit au but."),
("B2", "C'est le sel de la vie.", "그게 인생의 소금이지.", "비판·반대·다양성이 삶을 맛나게 한다는 관용적 비유. Lucien의 말장난(소금/짠 수프)과 이어진다."),
("B2", "un discours, c'est comme une sauce : on réduit.", "연설은 소스 같아서 졸이는 거다.", "réduire = (소스를) 졸이다 / 줄이다. 요리 은유로 연설을 줄이자는 농담."),
("B2", "porter la maison", "가게를 떠받치다", "porter = 짊어지다, 지탱하다. « Vous avez porté la maison. » supporter(참아 주다)와의 말장난을 정정하는 칭찬."),
("B2", "se vexer", "기분이 상하다, 토라지다", "« Elle se vexait d'abord, et notait après. » vexer(상하게 하다)의 대명동사. 반응이 빠르고 자존심이 걸릴 때."),
("C1", "ancienne, pas vieille", "오래된 사람이지 늙은 게 아니다", "vieux는 나이·낡음을 직접 가리켜 불쾌할 수 있다. ancien은 « 오래 이어진 »이라는 긍정적 어감. 자존심 있는 자기 소개."),
("C1", "Standing ovation", "기립 박수", "영어에서 들어온 말. 프랑스어로는 une ovation debout. 여기서는 « assise, pour mon cœur »로 농담화."),
("C1", "ne pas manquer d'ambition", "야심이 대단하다 (반어)", "ne pas manquer de + 명사 = ~이 부족하지 않다. 놀라움·비꼬는 칭찬. « Elle ne manque pas d'ambition. »"),
]

GRAM = [
("A2", "축하·덕담 표현", "« Joyeux anniversaire », « Bravo », « À la tienne ! », « À madame Vasseur, notre meilleure critique ! »처럼 건배는 « à + 사람 »이 기본이다. 상대가 한 명이면 « À la tienne ! » (복수 « À la vôtre ! »). 덕담은 « Que + 접속법 »으로도 한다: « Que le Comptoir ait encore quatre-vingts ans »."),
("B1", "축사의 구조 : Alors voilà…", "짧은 문장을 계단처럼 쌓는다. 도입 « Alors voilà. », 전개 « Premièrement… Deuxièmement… Troisièmement. », 매듭 « Voilà ma conclusion. ». 한 문장이 길어지면 숨 쉴 곳에서 끊는다: « Je râlais, / pour qu'on me parle. »"),
("B1", "대과거와 조건법 과거로 상상하기", "죽은 이를 떠올릴 때: « Il serait venu. Il aurait commandé son steak bien cuit. » 조건법 과거 = 일어나지 않은 일에 대한 가정. « Il se serait plaint de la sauce »는 대명동사 복합형(se serait + 과거분사)."),
("B2", "비교의 comme / 은유", "« Un bon discours, c'est comme une sauce : on réduit. », « Le thermomètre », « Comme une belle commode ». comme는 문장 앞에서 « ~처럼 »을 이끌고, 은유는 직접 « c'est le sel de la vie »처럼 말한다."),
("B2", "pour que + 접속법", "« Je râlais pour qu'on me parle. » 목적의 pour que 뒤에는 접속법: parle, vienne, soit. 주어가 같으면 pour + 부정사(pour parler)를 쓴다. « Pour ne pas rester seule avec le silence »."),
("B2", "대명동사의 수동 의미", "« Ça se fête », « Ça se dit », « Ça se voit ». 사람 주어 없이 « 그런 일은 ~된다 »를 말한다. « Quatre-vingts ans, ça se fête. » 회고·덕담 장면에서 일반 진리를 말할 때 자주 쓰인다."),
("C1", "ne pas + 부정사 / 부정 + manquer de", "« Elle ne manque pas d'ambition »(= 야심이 넘친다)처럼 부정으로 긍정을 강조하는 완서법(litote). « Ce n'est pas mauvais »가 « 꽤 괜찮다 »가 되는 것과 같은 원리."),
]

READ = [
("호흡 구간 — 축사 « Alors voilà »", "축사는 한 문장씩 끊어 읽는다: « Alors voilà. / Madame Vasseur, / vous avez quatre-vingts ans / depuis dimanche. » « voilà »에서 한 번 쉬고, 이름 뒤에서 또 쉰다. 청중의 웃음이나 박수를 기다리는 시간도 호흡의 일부."),
("리에종 — quatre-vingts_ans / très_élégante", "« quatre-vingts ans »에서 vingts의 s는 [z]로 이어진다: [katʁ-və̃-z-ɑ̃]. « Vous êtes très_élégante »도 très 뒤에서 [z]. 단, « vingt-quatre »의 t는 읽는다. 숫자의 연음은 입에 익을 때까지 반복."),
("억양 — 아부와 반박", "« Vous ne les faites pas du tout, / vos quatre-vingts ans. » 칭찬은 끝을 올리며 부드럽게. 반대로 Mme Vasseur의 « Lucien, vous mentez mal. »은 평평하게 내려 단정한다. 같은 문장도 올림·내림에 따라 농담이 된다."),
("비음 — enfants, ancienne, quatre-vingts", "« mes enfants » [mɛ-z-ɑ̃-fɑ̃], « ancienne » [ɑ̃-sjɛn], « quatre-vingts » [katʁ-və̃]. an/en [ɑ̃]과 in/ain [ɛ̃]의 차이에 집중하되 끝에 n 소리를 붙이지 않는다. « ancienne »는 비음 뒤 ienne에서 [n]이 나는 예외."),
("건배 — À la tienne !", "« À la tienne ! » [a la tjɛn]. 잔을 들고 눈을 마주치며 짧고 힘 있게. 마시기 전에 상대 눈을 보는 것이 예의. « À Jeanne Vasseur, / qui a dû nous supporter longtemps. » 처럼 건배사는 À로 시작해 마지막 단어에 힘을 준다."),
("r 연속 — critique, Vasseur, merci", "« notre meilleure critique », « merci », « râler ». r가 연속될 때는 목 뒤를 가볍게 긁고 흘린다. « Merci pour la soupe, / et pour le reste. » 에서 r를 약하게 이어 부드럽게 읽자."),
("억양 — 감정이 올라올 때", "Hélène의 « Je ne pleure pas. / C'est le citron, madame. » 는 목소리가 낮아지고 속도가 느려진다. 짧게 끊고 마지막 음절을 가볍게 내려 보자. 감정을 누르는 문장은 일부러 천천히."),
]

CULTURE = [
("Les quatre-vingts ans — 프랑스의 나이 축하", "프랑스에서는 60, 70, 80세 같은 « 둥근 생일 »을 크게 축하한다. 숫자 모양 초(bougies chiffres)를 쓰는 것도 흔하다. 노년의 연설은 유머와 겸손이 섞이는 것이 미덕이고, 주인공이 « 호들갑은 싫다 »라고 하면서도 모든 걸 챙겨 묻는 것이 전형적인 프랑스식 애정 표현이다."),
("La serviette brodée — 식탁 위의 개인 물건", "단골에게 전용 냅킨이나 이니셜 수를 남겨 두는 풍습은 오래된 동네 비스트로의 정(情)이다. 이름 새긴 명패(plaque)나 고정 자리는 « 이 집의 일부 »라는 인정의 표시다. 이 화에서 파란 냅킨은 1부 10화에 이어지는 작은 복선의 회수다."),
]

META = dict(part=5, ep=73, part_label="제5부 Le Comptoir de Marthe · 이듬해 봄·여름", title_fr="Mme Vasseur fête ses quatre-vingts ans", title_ko="바세르 부인의 여든 번째 생일",
 place="파리 11구 Le Comptoir de Marthe · 6월 22일 화요일 저녁 6시 30분경(비공개 생일 잔치)",
 chars="Mme Vasseur (80세, 7번 창가석 단골) · Hélène Marchand (주인 셰프) · Lucien Marchand (아버지, 퇴원 후) · Julien Benali (홀 매니저, 동업자) · 청중: Chloé, Karim, Bastide, Victor 등(대사 없음)",
 wine="덕담·축사·회고: 단골 할머니의 80세 생일 잔치",
 focus="축하·건배 표현, 축사 구조(Alors voilà…), 조건법 과거 가정, 은유와 관용구, 감정을 누르는 구어",
 levelmix="A2 5% / B1 15% / B2 40% / C1 40% 목표",
 next="제74화 « Lucien raccroche son tablier » : 퇴원한 뤼시앵이 짧은 연설로 은퇴를 선언하고 앞치마를 건다")
