# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA = "Inès", "Mathieu"
MR, CH, LF, YK = "Martine", "Chazal", "Fontanel", "Kerbrat"
PR, JF, MO = "Pradier", "Josiane", "Momo"

META = {
    "part": 2, "ep": 16,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Prise de fonctions",
    "title_ko": "취임",
    "place": "파리–생테티엔 TGV · 생테티엔 샤토크뢰역 · Verdier Industries 본사 · 생테티엔 공장 · 자카르 지구 이네스의 새 아파트 / 9월 초, 부임 첫날(월요일)",
    "chars": "이네스, 마티외, 마르틴 로슈(CEO 비서·30년 근속), 로베르 샤잘(생테티엔 공장장), 로르 퐁타넬(홍보 이사), 얀 케르브라(R&D 책임자), 실뱅 프라디에(회계팀장), 조지안 파브르(CSE 서기·노조 대표), 모하메드 '모모' 벨카셈(40년 근속 숙련공)",
    "work": "Verdier Industries 부임 첫날 — 임원 회의 첫 인사, 결산 서류 인수, 연차보고서 주석에만 적힌 폴란드 공장 리스 보증 6,000만 유로(부외 부채) 발견, 이사회에 투명하게 공개할지 결정",
    "life": "기차 안에서 잡은 손과 « on se vouvoie », 이삿짐 상자 위의 피자, 새 집을 탐색하는 피가로, 마티외의 파리 원룸 정리 결정",
    "focus": "격식 있는 부임 인사·자기소개, 재무제표 어휘(bilan, compte de résultat, annexe, hors bilan), vous/tu 전환과 호칭, 부정 선행사 뒤 접속법, quand bien même + 조건법, sans que / avant que + 접속법, je ne crois pas que + 접속법 과거",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제17화 Le conseil d'administration — 첫 이사회, 숨은 부채 공개에 격노하는 위베르 베르디에와 침착한 펀드, 그리고 회의 중 서로를 'vous'라고 부르기로 한 두 사람의 약속.",
}

D = [
# ---------- 1. Ouverture : le TGV de Saint-Étienne ----------
(None, "Un lundi de début septembre, 7 h 50. TGV Paris–Saint-Étienne. Inès relit le rapport annuel de Verdier Industries, couvert de Post-it. À ses pieds, Figaro gronde dans sa caisse de transport. Sous la tablette, Mathieu lui tient la main.",
       "9월 초의 어느 월요일, 오전 7시 50분. 파리발 생테티엔행 TGV. 이네스는 포스트잇으로 뒤덮인 Verdier Industries 연차보고서를 다시 읽고 있다. 발치에서는 피가로가 이동장 안에서 으르렁거린다. 접이식 테이블 아래에서 마티외가 그녀의 손을 잡고 있다."),
(MA, "Tu en es à quelle page ?", "몇 페이지까지 읽었어?"),
(I, "La fin du rapport de gestion. Trente pages de bonnes nouvelles pour un groupe qui a perdu quarante-deux millions l'an dernier. C'est presque un exploit littéraire.",
    "경영 보고서 끝부분. 작년에 4,200만 유로를 잃은 그룹이 좋은 소식만 30페이지야. 거의 문학적 업적이지."),
(MA, "Moi, j'ai relu mon discours onze fois. Je commence par « Mesdames, messieurs » ou par « Bonjour à tous » ?", "난 연설문을 열한 번 다시 읽었어. '신사 숙녀 여러분'으로 시작할까, '여러분 안녕하세요'로 시작할까?"),
(I, "« Bonjour à tous », et tu enchaînes vite. Et surtout, pas de blague sur la cocotte-minute. Ils les ont toutes entendues.", "'여러분 안녕하세요', 그리고 바로 이어 가. 그리고 무엇보다 압력솥 농담은 금지. 그 사람들은 그런 농담 다 들어 봤어."),
(MA, "Même celle sur la pression qui monte ?", "압력이 올라간다는 것도?"),
(I, "Surtout celle-là.", "특히 그거."),
(None, "Figaro pousse un long miaulement. De l'autre côté du couloir, une dame lève les yeux de son journal.", "피가로가 길게 운다. 통로 건너편의 한 부인이 신문에서 눈을 든다."),
(MA, "Il proteste depuis la gare de Lyon. Tu crois qu'il a compris qu'il déménageait ?", "리옹역에서부터 항의 중이네. 이사 가는 거 알아챈 걸까?"),
(I, "Il comprend tout. Il m'a regardée faire les cartons pendant trois semaines avec un mépris total. Pour lui, Saint-Étienne, c'est l'exil.",
    "다 알아. 3주 동안 내가 짐 싸는 걸 완전히 경멸하는 눈으로 지켜봤어. 걔한테 생테티엔은 유배지야."),
(MA, "Pour moi aussi, un peu. Deux appartements, deux villes, un train le vendredi soir, un autre le lundi matin... Tu crois qu'on va tenir ?",
     "나한테도 좀 그래. 아파트 두 개, 도시 두 개, 금요일 저녁 기차, 월요일 아침 기차... 우리 버틸 수 있을까?"),
(I, "On tiendra. Et le week-end, à Paris, mon appartement d'Oberkampf reste à nous.", "버틸 거야. 그리고 주말에 파리에선 내 오베르캉프 집이 우리 거잖아."),
(MA, "« À nous »... J'aime bien quand tu dis ça.", "'우리 거'라... 네가 그렇게 말하는 거 좋다."),
(I, "Ne t'emballe pas, c'est l'émotion du petit matin.", "흥분하지 마. 이른 아침이라 감상적인 거야."),
(None, "« Mesdames et messieurs, dans quelques minutes, notre train arrivera en gare de Saint-Étienne-Châteaucreux, son terminus. » Leurs mains se serrent un peu plus fort.",
       "'승객 여러분, 잠시 후 이 열차는 종착역인 생테티엔 샤토크뢰역에 도착합니다.' 맞잡은 두 손에 조금 더 힘이 들어간다."),
(MA, "Dernière minute de liberté. Après, je serai « monsieur le directeur général ».", "자유의 마지막 1분. 그다음부턴 난 '대표이사님'이야."),
(I, "Et moi, « madame la directrice financière ». Bon. Lâche ma main, Mathieu. À partir de maintenant, on se vouvoie.",
    "그리고 난 '재무 담당 이사님'이고. 자. 손 놔, 마티외. 지금부터 우린 서로 존댓말 쓰는 거야."),
(MA, "Très bien, madame Marchetti. Après vous... et n'oubliez pas votre chat.", "알겠습니다, 마르케티 이사님. 먼저 내리시죠... 고양이 잊지 마시고요."),

# ---------- 2. Le siège : premier jour ----------
(None, "9 h 30. Le siège de Verdier Industries, un bâtiment de brique de 1910 accolé à l'usine historique. Dans le hall, un vélo noir de 1874 et une cocotte rouge sous vitrine. Une femme aux cheveux gris les attend, un dossier serré contre elle.",
       "오전 9시 30분. 옛 공장에 붙어 있는 1910년 벽돌 건물, Verdier Industries 본사. 로비에는 1874년산 검은 자전거와 유리 진열장 속 빨간 압력솥이 있다. 머리가 희끗한 여성이 서류철을 꼭 끌어안고 두 사람을 기다린다."),
(MR, "Monsieur Kessler, madame Marchetti, bienvenue chez Verdier. Martine Roche, assistante de la direction générale depuis trente ans. J'ai connu cinq directeurs généraux ; j'espère que vous serez le dernier... pour longtemps, je veux dire.",
     "케슬레르 대표님, 마르케티 이사님, 베르디에에 오신 걸 환영합니다. 30년째 대표이사 비서를 맡고 있는 마르틴 로슈입니다. 대표이사를 다섯 분 모셨는데, 대표님이 마지막이시길 바랍니다... 오래오래 계시라는 뜻이에요."),
(MA, "Enchanté, madame Roche. On m'a dit que vous étiez la mémoire de cette maison. J'aurai besoin de vous plus que de n'importe quel tableau de bord.",
     "반갑습니다, 로슈 씨. 이 회사의 살아 있는 기억이시라고 들었습니다. 어떤 대시보드보다 로슈 씨가 더 필요할 겁니다."),
(MR, "Appelez-moi Martine, tout le monde le fait. Et pour le chat, j'ai prévu une petite pièce tranquille à côté de mon bureau. Il y a même un coussin.",
     "마르틴이라고 부르세요. 다들 그래요. 그리고 고양이를 위해 제 사무실 옆에 조용한 작은 방을 마련해 뒀어요. 방석도 있어요."),
(I, "Vous êtes une magicienne, Martine. Je vous préviens, il n'aime personne.", "마법사시네요, 마르틴. 미리 말씀드리는데, 걔는 아무도 안 좋아해요."),
(MR, "Il n'a pas encore rencontré les Stéphanois. Tenez, voici le tout premier vélo Verdier, de 1874. Et là, la première Stéphanoise, sortie de l'usine en 1962. Toute la France a cuisiné avec elle.",
     "아직 생테티엔 사람들을 못 만나 봐서 그래요. 자, 이게 1874년 베르디에의 첫 자전거예요. 그리고 저건 1962년 공장에서 나온 첫 '스테파누아즈'고요. 온 프랑스가 이걸로 요리했죠."),
(MA, "Ma grand-mère en a une, à Colmar. Elle refuse d'en changer depuis cinquante ans.", "콜마르에 계신 저희 할머니도 하나 갖고 계세요. 50년째 바꾸기를 거부하시죠."),
(MR, "Elle a bon goût. Votre comité de direction vous attend en salle Fauriel. Ils sont... curieux.", "안목이 좋으시네요. 경영위원회가 포리엘 회의실에서 기다리고 있어요. 다들... 궁금해하세요."),
(I, "Curieux ou inquiets ?", "궁금해하는 거예요, 불안해하는 거예요?"),
(MR, "Disons qu'ici, quand un nouveau patron arrive de Paris, on se demande d'abord combien de temps il restera. Ensuite, ce qu'il va fermer.",
     "이렇게 말해 두죠. 여기선 새 사장이 파리에서 오면 먼저 얼마나 오래 있을지 궁금해해요. 그다음엔 뭘 닫을지요."),
(None, "Salle Fauriel. Une longue table, une dizaine de directeurs. Mathieu reste debout.", "포리엘 회의실. 긴 테이블에 이사 열 명 남짓. 마티외는 선 채로 있다."),
(MA, "Bonjour à tous. Je suis Mathieu Kessler. J'ai trente-trois ans, je suis alsacien, ingénieur de formation, et jusqu'au mois de juin, j'étais consultant. Je sais ce que vous pensez : encore un consultant parisien qui vient nous expliquer notre métier.",
     "여러분, 안녕하십니까. 마티외 케슬레르입니다. 서른세 살, 알자스 출신이고 엔지니어 교육을 받았으며 지난 6월까지 컨설턴트였습니다. 무슨 생각을 하실지 압니다. 또 파리 컨설턴트가 와서 우리 일을 설명하려 드는구나, 하시겠죠."),
(MA, "Je ne vais pas vous l'expliquer. Je vais vous demander de me l'apprendre. Cette maison fabrique des cocottes depuis plus de soixante ans ; moi, je n'en ai jamais fabriqué une seule. En revanche, je sais qu'une entreprise qui perd de l'argent trois années de suite ne se redresse pas sans la vérité. Je vous demande donc une seule chose : dites-moi ce qui ne va pas, même si cela doit me déplaire.",
     "설명하지 않겠습니다. 가르쳐 달라고 부탁드리겠습니다. 이 회사는 60년 넘게 압력솥을 만들어 왔지만, 저는 단 하나도 만들어 본 적이 없습니다. 대신 3년 연속 적자인 회사는 진실 없이는 다시 일어서지 못한다는 것은 압니다. 그래서 딱 한 가지만 부탁드립니다. 제 마음에 들지 않더라도, 무엇이 잘못되고 있는지 말씀해 주십시오."),
(I, "Bonjour. Inès Marchetti, directrice financière. Je suis marseillaise, ce qui, je le sais, n'arrange rien les soirs de match ici. Mon métier, ce sont les chiffres. Je vais vous en demander beaucoup, et vite. Je ne cherche pas de coupables ; je cherche des chiffres justes.",
    "안녕하세요. 재무 담당 이사 이네스 마르케티입니다. 마르세유 출신인데, 여기서 경기 있는 날 저녁엔 그게 도움이 안 된다는 것도 압니다. 제 일은 숫자입니다. 많은 숫자를, 빨리 요청드릴 겁니다. 범인을 찾는 게 아닙니다. 정확한 숫자를 찾는 겁니다."),
(CH, "Robert Chazal, directeur de l'usine de Saint-Étienne. Trente-six ans dans le groupe. Monsieur Kessler, vous êtes le quatrième directeur général en dix ans. Les trois premiers nous ont tous demandé la vérité. Ensuite, ils ont fait des présentations.",
     "생테티엔 공장장 로베르 샤잘입니다. 그룹에서 36년 일했습니다. 케슬레르 대표님, 대표님은 10년 사이 네 번째 대표이사입니다. 앞의 세 분도 모두 진실을 요구했죠. 그러고 나서는 프레젠테이션을 했고요."),
(MA, "Alors jugez-moi sur la suite, monsieur Chazal, pas sur la présentation. Vous me faites visiter l'usine cet après-midi ?", "그럼 프레젠테이션 말고 그다음을 보고 판단해 주십시오, 샤잘 공장장님. 오늘 오후에 공장을 보여 주시겠습니까?"),
(CH, "Quinze heures trente. Prévoyez des chaussures de sécurité. Les gens du siège viennent souvent en mocassins.", "3시 30분입니다. 안전화를 준비하세요. 본사 사람들은 대개 로퍼를 신고 오거든요."),
(LF, "Laure Fontanel, communication. Monsieur Kessler, la presse locale demande une interview cette semaine. Je propose un communiqué très court aujourd'hui, et pas d'entretien avant un mois.",
     "홍보 담당 로르 퐁타넬입니다. 케슬레르 대표님, 지역 언론이 이번 주에 인터뷰를 요청하고 있습니다. 오늘은 아주 짧은 보도자료만 내고, 한 달 동안은 인터뷰를 하지 않을 것을 제안드립니다."),
(MA, "D'accord pour le communiqué. Pas de grandes promesses, pas de chiffres. Je ne veux pas annoncer ce que je ne connais pas encore.", "보도자료는 좋습니다. 거창한 약속도, 숫자도 넣지 마세요. 아직 모르는 걸 발표하고 싶지 않습니다."),
(YK, "Yann Kerbrat, recherche et développement. Je serai bref : nous avons des projets dans les tiroirs. Certains depuis longtemps. Le jour où vous voudrez les voir, mon bureau est au deuxième étage.",
     "연구개발 담당 얀 케르브라입니다. 짧게 말씀드리죠. 서랍 속에 잠든 프로젝트들이 있습니다. 오래된 것도 있고요. 보고 싶으실 때 오세요. 제 사무실은 3층입니다."),
(MA, "Je viendrai, monsieur Kerbrat. Des tiroirs pleins, c'est rarement une mauvaise nouvelle.", "가겠습니다, 케르브라 이사님. 서랍이 꽉 차 있다는 건 대개 나쁜 소식이 아니죠."),
(I, "D'ici vendredi, j'aimerais voir chaque directeur pour parler de son budget. Martine, pourriez-vous organiser des créneaux de quarante-cinq minutes ?",
    "금요일까지 각 이사님과 예산 얘기를 나누고 싶습니다. 마르틴, 45분씩 시간을 잡아 주시겠어요?"),
(MR, "C'est déjà fait, madame Marchetti. Ils sont dans votre agenda depuis vendredi dernier.", "이미 해 뒀습니다, 마르케티 이사님. 지난 금요일부터 이사님 일정표에 들어가 있어요."),
(I, "... Vous avez vraiment trente ans d'avance sur moi.", "...정말 저보다 30년 앞서 계시네요."),
(None, "11 h 45. Dans le couloir, un homme d'une cinquantaine d'années, lunettes au bout du nez, attend Inès avec trois classeurs.", "오전 11시 45분. 복도에서 코끝에 안경을 걸친 50대 남자가 바인더 세 권을 들고 이네스를 기다리고 있다."),
(PR, "Madame Marchetti ? Sylvain Pradier, chef comptable. Voici le dossier de clôture de l'exercice : le bilan, le compte de résultat, l'annexe et le rapport du commissaire aux comptes.",
     "마르케티 이사님? 회계팀장 실뱅 프라디에입니다. 결산 서류입니다. 재무상태표, 손익계산서, 주석, 그리고 감사인 보고서요."),
(I, "Merci, monsieur Pradier. Les comptes ont été certifiés sans réserve, si je ne me trompe pas ?", "고맙습니다, 프라디에 팀장님. 제가 알기로 재무제표는 적정 의견을 받았죠?"),
(PR, "Sans réserve, oui. Le commissaire aux comptes a simplement ajouté une observation sur la continuité d'exploitation, à cause des pertes.", "네, 적정 의견입니다. 감사인이 적자 때문에 계속기업 가정에 관한 강조 사항을 하나 덧붙였을 뿐입니다."),
(I, "Une observation sur la continuité d'exploitation... Et vous appelez ça « simplement » ?", "계속기업에 관한 강조 사항이라... 그걸 '~뿐'이라고 하시는 거예요?"),
(PR, "Ici, on finit par s'habituer à tout, madame.", "여기선 결국 다 익숙해지게 됩니다, 이사님."),
(I, "Pas moi. Je vais tout lire cet après-midi, annexe comprise. Restez joignable, s'il vous plaît.", "전 아니에요. 오늘 오후에 주석까지 전부 읽을 겁니다. 연락 닿는 곳에 계셔 주세요."),
(MR, "Le déjeuner est à la cantine, avec les équipes. C'est une habitude de la maison ; je me suis permis de la garder.", "점심은 구내식당에서 직원들과 함께입니다. 회사의 오랜 관습이라 그대로 유지했어요."),
(MA, "Vous avez bien fait, Martine. Madame Marchetti, vous venez ? ... Ah. Elle a déjà ouvert le premier classeur.", "잘하셨어요, 마르틴. 마르케티 이사님, 가시죠? ...아. 벌써 첫 번째 바인더를 펼쳤네요."),

# ---------- 3. Analyse : la note 31 ----------
(None, "14 h 20. Bureau de la directrice financière. Les cartons de l'ancien occupant s'entassent dans un coin. Sur la table, l'annexe est ouverte ; trois Post-it jaunes, un rouge.",
       "오후 2시 20분. 재무 담당 이사실. 전임자의 상자들이 한쪽 구석에 쌓여 있다. 테이블 위에 주석이 펼쳐져 있고, 노란 포스트잇 세 장과 빨간 포스트잇 한 장이 붙어 있다."),
(I, "Entrez, monsieur Pradier, asseyez-vous. Note 31 de l'annexe, page 84 : « Engagements hors bilan donnés ». Expliquez-moi cette ligne.",
    "들어와 앉으세요, 프라디에 팀장님. 주석 31번, 84페이지. '제공한 부외 약정'. 이 줄을 설명해 주세요."),
(PR, "C'est une garantie de la maison mère. Verdier Industries garantit les loyers de crédit-bail de notre filiale polonaise, Verdier Polska, à Wrocław. Pour la nouvelle halle et les deux lignes de production.",
     "모회사 보증입니다. Verdier Industries가 브로츠와프에 있는 폴란드 자회사 Verdier Polska의 리스료를 보증하고 있습니다. 새 공장동과 생산 라인 두 개에 대한 겁니다."),
(I, "Montant ?", "금액은요?"),
(PR, "Soixante millions d'euros, sur dix ans. Le contrat a été signé il y a deux ans.", "6,000만 유로, 10년 계약입니다. 2년 전에 서명됐습니다."),
(I, "Soixante millions qui ne figurent ni au bilan ni dans aucune présentation au conseil que j'aie lue. Pourquoi ?", "6,000만 유로가 재무상태표에도, 제가 읽은 이사회 보고 자료 어디에도 없네요. 왜죠?"),
(PR, "Parce qu'une garantie n'est pas une dette, madame. Tant qu'elle n'est pas appelée, elle reste hors bilan. Juridiquement, tout est en règle : chaque année, le conseil donne au directeur général une autorisation globale pour les cautions et garanties.",
     "보증은 부채가 아니니까요, 이사님. 이행 청구가 들어오지 않는 한 부외로 남습니다. 법적으로는 모두 적법합니다. 이사회가 매년 대표이사에게 보증에 대한 포괄 승인을 해 주거든요."),
(I, "Avec quel plafond ?", "한도는 얼마죠?"),
(PR, "Soixante-quinze millions.", "7,500만 유로입니다."),
(I, "Donc on a utilisé quatre-vingts pour cent du plafond en une seule signature, sans que personne en parle au conseil. Qui a préparé le dossier ?",
    "그러니까 서명 한 번으로 한도의 80%를 썼는데, 이사회에선 아무도 그 얘기를 안 했군요. 누가 그 서류를 준비했죠?"),
(PR, "L'ancien directeur financier. Il l'a mentionné dans l'annexe, comme la loi l'exige. Il disait que c'était « un détail technique ».", "전임 재무이사입니다. 법이 요구하는 대로 주석에 기재했습니다. 그분은 '기술적인 세부 사항'이라고 했고요."),
(I, "Un détail technique de soixante millions. Et dans quels cas la garantie peut-elle être appelée ?", "6,000만 유로짜리 기술적 세부 사항이라. 그럼 어떤 경우에 보증 이행이 청구될 수 있죠?"),
(PR, "Si Verdier Polska ne paie pas deux échéances consécutives. Ou... en cas de changement de contrôle de la filiale.", "Verdier Polska가 리스료를 두 번 연속 못 내면요. 아니면... 자회사의 지배권이 바뀌는 경우요."),
(I, "Autrement dit, en cas de vente. Et Verdier Polska paie ses loyers à l'heure ?", "다시 말해 매각하는 경우군요. Verdier Polska는 리스료를 제때 내고 있나요?"),
(PR, "En général, oui. Mais en juillet, l'échéance a été réglée avec dix-neuf jours de retard. Leur principal client allemand a réduit ses commandes.", "대체로는요. 그런데 7월분은 19일 늦게 냈습니다. 주요 독일 고객이 주문을 줄였거든요."),
(I, "Merci, monsieur Pradier. Pas un mot à qui que ce soit pour l'instant, s'il vous plaît. Et prenez rendez-vous avec le commissaire aux comptes cette semaine.",
    "고맙습니다, 프라디에 팀장님. 당분간은 누구에게도 한마디도 하지 말아 주세요. 그리고 이번 주에 감사인과 약속을 잡아 주세요."),
(None, "Pradier sort. Inès décroche le téléphone interne.", "프라디에가 나간다. 이네스가 내선 전화를 든다."),
(I, "Monsieur Kessler ? Pourriez-vous passer à mon bureau ? ... Oui, maintenant. Il vaudrait mieux.", "케슬레르 대표님? 제 사무실에 잠깐 오실 수 있을까요? ...네, 지금요. 그게 좋겠습니다."),
(MA, "Porte fermée, donc je peux te tutoyer. Qu'est-ce qui se passe ? Tu as ta tête des mauvais jours.", "문 닫았으니 말 놓을게. 무슨 일이야? 기분 안 좋은 날 표정인데."),
(I, "J'ai trouvé un cadavre dans le placard. Soixante millions de garantie sur l'usine polonaise, rangés dans une note de l'annexe. Si la garantie est appelée, notre dette nette passe de trois cent dix à trois cent soixante-dix millions.",
    "숨겨진 시체를 찾았어. 폴란드 공장에 대한 6,000만 유로 보증이 주석 하나에 들어가 있었어. 보증 이행이 청구되면 순부채가 3억 1천만에서 3억 7천만 유로가 돼."),
(MA, "Presque vingt pour cent de plus... Appelée dans quels cas ?", "거의 20% 증가네... 어떤 경우에 청구되는데?"),
(I, "Si Wrocław rate deux loyers de suite, ou si on vend la filiale. Ils ont déjà payé en retard en juillet. Et si Arcane pousse à vendre la Pologne, comme je le crains, la garantie tombe le jour de la vente.",
    "브로츠와프가 리스료를 연속 두 번 못 내거나, 우리가 자회사를 팔면. 7월에 벌써 연체했어. 그리고 내가 걱정하는 대로 아르칸이 폴란드를 팔자고 밀어붙이면, 매각하는 날 보증이 떨어져."),
(MA, "Donc vendre Wrocław pourrait nous coûter soixante millions au lieu de nous en rapporter. Bon. Il faudra le dire au conseil, évidemment. Mais peut-être pas tout de suite.",
     "그러니까 브로츠와프를 팔면 돈이 들어오는 대신 6,000만 유로가 나갈 수도 있다는 거네. 좋아. 이사회에 말해야지, 당연히. 그런데 당장은 아닐 수도 있어."),
(I, "Pas tout de suite ? Le conseil se réunit dans trois semaines.", "당장은 아니라고? 이사회가 3주 뒤야."),
(MA, "Justement. Si on arrive au premier conseil avec une bombe et sans solution, on passe pour des amateurs. Je préférerais qu'on présente la garantie dans notre plan à cent jours, avec une stratégie pour la Pologne.",
     "바로 그거야. 첫 이사회에 해결책 없이 폭탄만 들고 가면 아마추어처럼 보일 거야. 보증 건은 100일 계획 때 폴란드 전략과 함께 내놓는 게 낫겠어."),
(I, "Dans cent jours ? Mathieu, quand bien même on aurait la meilleure stratégie du monde, chaque jour de silence ferait de nous des complices.",
    "100일 뒤에? 마티외, 설령 세상에서 제일 좋은 전략을 갖고 있다 해도, 침묵하는 하루하루가 우리를 공범으로 만들 거야."),
(MA, "Complices, c'est fort. Ce n'est pas nous qui avons signé.", "공범은 너무 센 말이야. 서명한 건 우리가 아니잖아."),
(I, "Non. Mais à partir d'aujourd'hui, c'est nous qui savons. ... Tu te souviens de ce que mon père m'a dit ? « Les chiffres étaient là, et je ne les ai pas lus. » Moi, je les ai lus. Je ne ferai pas semblant du contraire.",
    "맞아. 하지만 오늘부터 알고 있는 건 우리야. ...우리 아빠가 했던 말 기억나? '숫자는 거기 있었는데, 난 읽지 않았다.' 난 읽었어. 안 읽은 척은 안 할 거야."),
(MA, "... Je sais. Et je sais aussi que mon premier réflexe, c'est de repousser le conflit. Tu as le droit de me le dire.", "...알아. 그리고 내 첫 반사 작용이 갈등을 미루는 거라는 것도 알아. 그렇다고 말해도 돼."),
(I, "Je te le dis. Gentiment, mais je te le dis.", "말할게. 부드럽게, 하지만 분명히."),
(MA, "Alors faisons les choses dans l'ordre. Quel est le vrai problème ? Ce n'est pas seulement la garantie. C'est qu'un engagement de soixante millions a pu être signé sans que le conseil en débatte vraiment. Si on se tait, on reproduit exactement la même chose.",
     "그럼 순서대로 하자. 진짜 문제는 무엇인가? 보증 자체만이 아니야. 이사회가 제대로 논의하지도 않은 채 6,000만 유로짜리 약정이 서명될 수 있었다는 거야. 우리가 입을 다물면 똑같은 일을 되풀이하는 거고."),
(I, "Voilà. Tu as raison sur un point, cela dit : il nous faut des pistes, pas seulement une bombe. On en reparle après l'usine. Et mets tes chaussures de sécurité, monsieur le directeur général.",
    "바로 그거야. 그래도 네 말에도 일리는 있어. 폭탄만 말고 해결 방향도 있어야 해. 공장 다녀와서 다시 얘기하자. 그리고 안전화 신어, 대표이사님."),

# ---------- 4. Terrain : l'usine ----------
(None, "15 h 30. L'usine de Saint-Étienne. Le bruit des presses, l'odeur du métal chaud. Robert Chazal les attend avec une femme aux cheveux courts, un badge CSE autour du cou.",
       "오후 3시 30분. 생테티엔 공장. 프레스 기계 소리, 달군 금속 냄새. 로베르 샤잘이 목에 CSE 배지를 건 짧은 머리의 여성과 함께 두 사람을 기다리고 있다."),
(CH, "Des chaussures de sécurité. Je retire ce que j'ai dit ce matin. Voici Josiane Fabre, secrétaire du CSE. Elle a tenu à être là.", "안전화를 신으셨군요. 아침에 한 말은 취소하죠. CSE 서기 조지안 파브르입니다. 꼭 와야겠다고 하더군요."),
(JF, "Bonjour. Je ne vais pas vous faire de discours de bienvenue. Les gars veulent savoir une seule chose : vous êtes venus pour fermer quoi ?", "안녕하세요. 환영사는 생략하죠. 직원들이 알고 싶은 건 딱 하나예요. 뭘 닫으러 오셨어요?"),
(MA, "Je suis venu pour comprendre, madame Fabre. Je ne fermerai rien que je ne comprenne pas. Et je ne vous promettrai rien que je ne puisse tenir.",
     "이해하러 왔습니다, 파브르 씨. 이해하지 못한 건 아무것도 닫지 않을 겁니다. 그리고 지킬 수 없는 건 아무것도 약속하지 않겠습니다."),
(JF, "C'est joliment dit. Le dernier disait à peu près la même chose, avec une cravate en plus.", "말씀은 예쁘네요. 지난번 분도 거의 같은 말을 했어요. 넥타이만 하나 더 맸을 뿐."),
(I, "Alors jugez-nous sur les actes, madame Fabre. Ce que nous saurons, vous le saurez dès que la loi et le conseil nous permettront de le dire. Pas six mois après.",
    "그럼 행동으로 판단해 주세요, 파브르 씨. 저희가 아는 건 법과 이사회가 허락하는 즉시 여러분도 알게 될 겁니다. 여섯 달 뒤가 아니라요."),
(JF, "On verra. Ici, en général, on apprend les nouvelles par la presse. Ou par la Pologne.", "두고 보죠. 여기선 보통 소식을 신문으로 들어요. 아니면 폴란드를 통해서요."),
(MA, "Par la Pologne ? C'est-à-dire ?", "폴란드를 통해서요? 무슨 뜻이죠?"),
(JF, "Demandez à Momo. Momo ! Viens dire bonjour au nouveau patron.", "모모한테 물어보세요. 모모! 와서 새 사장님한테 인사해."),
(None, "Un homme d'une soixantaine d'années, moustache blanche, s'essuie les mains et s'approche de la ligne où défilent les cocottes rouges.", "흰 콧수염을 기른 예순 줄의 남자가 손을 닦으며 빨간 압력솥이 줄지어 지나가는 라인 쪽으로 다가온다."),
(MO, "Mohamed Belkacem. Tout le monde dit Momo. Quarante ans sur cette ligne, monsieur. Je montais des Stéphanoise avant que vous soyez né.", "모하메드 벨카셈입니다. 다들 모모라고 불러요. 이 라인에서 40년이에요, 사장님. 사장님이 태어나기 전부터 스테파누아즈를 조립했죠."),
(MA, "Alors vous allez pouvoir m'apprendre. Montrez-moi comment on en monte une.", "그럼 저를 가르쳐 주실 수 있겠네요. 하나 조립하는 걸 보여 주세요."),
(MO, "Regardez. La cuve, le couvercle, le joint. Et ça, c'est le cœur : la soupape. Si elle est mal réglée, la cocotte siffle trop tôt... ou pire, elle ne siffle pas du tout.",
     "보세요. 솥 몸체, 뚜껑, 패킹. 그리고 이게 심장이에요. 압력 밸브. 이게 잘못 조정되면 솥이 너무 일찍 김을 뿜거나... 더 나쁘면 아예 안 뿜어요."),
(I, "Et chaque soupape est contrôlée ?", "밸브는 하나하나 검사하나요?"),
(MO, "Une par une, madame. Sous pression, à la main. Les machines, elles ne sentent pas quand quelque chose cloche. Moi, je le sens.", "하나하나요, 이사님. 압력을 걸고, 손으로요. 기계는 뭔가 이상할 때 그걸 못 느껴요. 전 느끼죠."),
(MA, "Madame Fabre parlait de la Pologne. Qu'est-ce qu'elle voulait dire ?", "파브르 씨가 폴란드 얘기를 하셨는데요. 무슨 뜻이었죠?"),
(MO, "Il y a deux ans, on attendait deux lignes neuves, ici. On nous les avait promises. Et puis un matin, on a vu les plans partir pour Wrocław. Là-bas, ils ont la halle neuve et les machines neuves. Nous, on a gardé celles de 1988.",
     "2년 전에 여기 새 라인 두 개가 들어오기로 돼 있었어요. 약속까지 받았죠. 그런데 어느 날 아침 설계도가 브로츠와프로 가는 걸 봤어요. 거긴 새 공장동에 새 기계가 있죠. 우린 1988년 기계를 그대로 쓰고요."),
(CH, "Momo exagère un peu. Mais un peu seulement. La décision a été prise au siège, sans nous consulter.", "모모가 좀 과장하는 거예요. 그래도 아주 조금만요. 결정은 본사에서 우리와 상의 없이 내려졌어요."),
(I, "La halle neuve de Wrocław... Elle a été financée par crédit-bail, n'est-ce pas, monsieur Chazal ?", "브로츠와프의 새 공장동이라... 리스로 자금을 조달했죠, 샤잘 공장장님?"),
(CH, "Je ne sais pas comment elle a été financée, madame. À l'usine, on ne nous montre que les factures d'électricité.", "어떻게 조달했는지는 모릅니다, 이사님. 공장에는 전기 요금 고지서만 보여 주거든요."),
(None, "Inès et Mathieu échangent un bref regard. Josiane l'a remarqué.", "이네스와 마티외가 짧게 눈빛을 주고받는다. 조지안이 그걸 알아챈다."),
(JF, "Vous voyez ? Vous savez déjà quelque chose que nous ne savons pas. Ça commence bien.", "보세요. 벌써 우리가 모르는 걸 알고 계시잖아요. 시작이 좋네요."),
(MA, "Vous avez raison de le relever, madame Fabre. Je ne peux pas tout vous dire aujourd'hui. Mais je vous donne ma parole que vous ne l'apprendrez pas par la presse.",
     "잘 짚으셨습니다, 파브르 씨. 오늘 전부 말씀드릴 순 없습니다. 하지만 신문으로 알게 되시는 일은 없을 거라고 약속드립니다."),
(JF, "Votre parole... Je la note. Je note tout, monsieur Kessler. C'est mon métier.", "약속이라... 적어 두죠. 전 다 적어요, 케슬레르 대표님. 그게 제 일이에요."),
(MO, "Monsieur le directeur, si vous voulez vraiment comprendre cette usine, revenez une nuit. C'est avec l'équipe de nuit qu'on voit tout.", "대표님, 이 공장을 정말 이해하고 싶으시면 밤에 다시 오세요. 야간조랑 있어야 다 보이거든요."),
(MA, "Je reviendrai, Momo. C'est promis.", "다시 올게요, 모모. 약속해요."),
(MO, "Tout le monde le promet.", "다들 그렇게 약속하죠."),
(MA, "Oui, mais moi, j'ai acheté les chaussures.", "네, 하지만 전 안전화까지 샀잖아요."),

# ---------- 5. Décision : le premier point ----------
(None, "18 h 30. Bureau du directeur général. Par la fenêtre, les toits de l'usine et, au loin, les crassiers. Autour de la table : Inès, Sylvain Pradier, Laure Fontanel, et Martine, qui prend des notes.",
       "오후 6시 30분. 대표이사실. 창밖으로 공장 지붕들과 멀리 광산 폐석 더미가 보인다. 테이블에는 이네스, 실뱅 프라디에, 로르 퐁타넬, 그리고 메모를 하는 마르틴이 앉아 있다."),
(MA, "Merci d'être restés. Madame Marchetti a découvert cet après-midi un engagement important. Je lui laisse la parole.", "남아 주셔서 감사합니다. 마르케티 이사님이 오늘 오후 중요한 약정을 하나 발견했습니다. 이사님께 발언을 넘기겠습니다."),
(I, "Merci, monsieur Kessler. Il y a deux ans, Verdier Industries a garanti le crédit-bail de sa filiale polonaise pour soixante millions d'euros. L'engagement figure dans l'annexe des comptes, note 31, mais il n'a jamais été présenté au conseil en tant que tel.",
    "감사합니다, 케슬레르 대표님. 2년 전 Verdier Industries는 폴란드 자회사의 리스에 6,000만 유로 보증을 섰습니다. 이 약정은 재무제표 주석 31번에 기재돼 있지만, 이사회에 그 자체로 보고된 적은 한 번도 없습니다."),
(I, "Pour vous donner un ordre de grandeur : notre dette nette est de trois cent dix millions, notre perte de l'an dernier, de quarante-deux. Si la garantie était appelée, la dette passerait à trois cent soixante-dix millions. Et elle devient exigible en cas de vente de la filiale.",
    "규모를 말씀드리면, 우리 순부채는 3억 1천만 유로, 작년 손실은 4,200만 유로입니다. 보증 이행이 청구되면 부채는 3억 7천만 유로가 됩니다. 그리고 자회사를 매각하면 즉시 이행 의무가 생깁니다."),
(LF, "Soixante millions... Et vous voulez l'annoncer au conseil dans trois semaines ? Pardonnez-moi, mais si l'information sort, la presse titrera « Dette cachée chez Verdier ». Les salariés vont paniquer.",
     "6,000만 유로라... 그걸 3주 뒤 이사회에서 발표하시겠다고요? 죄송하지만 정보가 새면 언론은 '베르디에의 숨은 부채'라고 제목을 뽑을 거예요. 직원들이 공황에 빠질 겁니다."),
(MA, "Que proposez-vous, madame Fontanel ?", "어떻게 하자는 겁니까, 퐁타넬 이사님?"),
(LF, "D'attendre d'avoir une solution. On présente le problème et la réponse le même jour. C'est la règle de base de la communication de crise.", "해결책이 나올 때까지 기다리자는 겁니다. 문제와 답을 같은 날 내놓는 거죠. 위기 커뮤니케이션의 기본 원칙이에요."),
(PR, "Et sur le plan juridique, rien ne nous oblige à aller plus loin. Tout est publié dans l'annexe. Le commissaire aux comptes n'a rien relevé.", "그리고 법적으로는 더 나아갈 의무가 없습니다. 모두 주석에 공시돼 있어요. 감사인도 아무것도 지적하지 않았고요."),
(I, "Publié, monsieur Pradier, mais pas lu. Une information qu'on range page quatre-vingt-quatre en espérant que personne ne la trouve, ce n'est pas de la transparence. C'est du camouflage, même s'il est légal.",
    "공시는 됐죠, 프라디에 팀장님. 하지만 읽히진 않았어요. 아무도 못 찾길 바라며 84페이지에 넣어 둔 정보는 투명성이 아닙니다. 합법이긴 해도 위장이에요."),
(PR, "Je n'ai jamais cherché à cacher quoi que ce soit, madame.", "저는 무엇 하나 숨기려 한 적 없습니다, 이사님."),
(I, "Je le sais, et je ne vous accuse pas. Mais le conseil, lui, se demandera qui savait, et depuis quand. À partir de ce soir, la réponse, c'est nous.",
    "압니다. 팀장님을 탓하는 게 아니에요. 하지만 이사회는 누가 언제부터 알았는지 물을 겁니다. 오늘 저녁부터 그 답은 우리예요."),
(MA, "Martine, vous étiez là il y a deux ans. Comment cette garantie a-t-elle été signée ?", "마르틴, 2년 전에도 계셨죠. 이 보증은 어떻게 서명됐습니까?"),
(MR, "Un vendredi soir d'août, monsieur. Monsieur Hubert était en vacances, comme chaque année à cette période. L'ancien directeur financier m'a demandé de préparer le parapheur. J'avais trouvé ça curieux, un vendredi d'août.",
     "8월의 어느 금요일 저녁이었어요, 대표님. 위베르 회장님은 매년 그맘때처럼 휴가 중이셨고요. 전임 재무이사가 결재 서류철을 준비해 달라고 했어요. 8월 금요일에 그런 걸 하다니 이상하다고 생각했죠."),
(MA, "Monsieur Verdier était-il au courant ?", "베르디에 회장님은 알고 계셨습니까?"),
(MR, "Il a reçu les comptes, comme tous les administrateurs. Mais je ne crois pas qu'il ait lu l'annexe. Monsieur Hubert lit les chiffres de production, pas les notes en petits caractères.",
     "다른 이사들처럼 재무제표는 받으셨죠. 하지만 주석까지 읽으셨을 거라곤 생각하지 않아요. 위베르 회장님은 생산 수치는 읽으셔도 작은 글씨로 된 주석은 안 읽으세요."),
(LF, "Raison de plus pour ne pas lui jeter ça au visage dès le premier conseil ! Il va le prendre comme une attaque contre sa famille.", "그러니 더더욱 첫 이사회부터 그걸 면전에 던지면 안 되죠! 가문에 대한 공격으로 받아들이실 거예요."),
(MA, "C'est possible. Mais imaginez qu'il l'apprenne dans six mois, par un banquier ou par le fonds. Il ne se demandera plus si l'ancienne équipe a caché quelque chose. Il se demandera pourquoi la nouvelle l'a caché.",
     "그럴 수도 있습니다. 하지만 6개월 뒤에 은행가나 펀드를 통해 알게 되신다고 상상해 보세요. 그땐 전 경영진이 뭘 숨겼는지가 아니라, 왜 새 경영진이 그걸 숨겼는지를 물으실 겁니다."),
(LF, "... Vu comme ça.", "...그렇게 보면 그렇네요."),
(I, "Et il y a une autre raison. Arcane proposera probablement de vendre l'usine polonaise. Si le conseil vote une cession sans connaître la garantie, il prendra sa décision sur des bases fausses. Nous ne pouvons pas le laisser voter à l'aveugle.",
    "그리고 이유가 하나 더 있습니다. 아르칸은 아마 폴란드 공장 매각을 제안할 겁니다. 이사회가 보증을 모른 채 매각을 표결하면 잘못된 전제 위에서 결정하게 됩니다. 이사회가 눈을 가린 채 표결하게 둘 수는 없습니다."),
(PR, "C'est vrai. Je n'avais pas vu la clause de changement de contrôle sous cet angle.", "맞습니다. 지배권 변경 조항을 그런 각도에서 보지 못했네요."),
(MA, "Bien. Je résume. La question n'est pas de savoir si nous parlons, mais comment. Qui décide ? Le conseil. Notre travail, c'est de lui donner une information complète, à tous les administrateurs en même temps : la famille comme le fonds.",
     "좋습니다. 정리하죠. 문제는 말할지 말지가 아니라 어떻게 말하느냐입니다. 누가 결정하는가? 이사회입니다. 우리 일은 이사회에 완전한 정보를, 모든 이사에게 동시에 주는 겁니다. 가문이든 펀드든 똑같이요."),
(LF, "Et la solution que je demandais ?", "그럼 제가 요구한 해결책은요?"),
(I, "Nous n'aurons pas de solution définitive dans trois semaines, mais nous aurons des pistes. Un : renégocier avec le crédit-bailleur pour supprimer la clause de changement de contrôle. Deux : un suivi mensuel de la trésorerie de Verdier Polska. Trois : une nouvelle règle, tout engagement hors bilan de plus de cinq millions sera présenté au conseil.",
    "3주 안에 확정된 해결책은 없겠지만 방향은 있을 겁니다. 하나, 리스사와 재협상해 지배권 변경 조항을 없앤다. 둘, Verdier Polska의 자금 상황을 매달 점검한다. 셋, 새 규칙으로 500만 유로가 넘는 부외 약정은 모두 이사회에 보고한다."),
(LF, "Là, au moins, j'ai une histoire à raconter. Bon... Je prépare des éléments de langage au cas où l'information sortirait. Mais rien ne part à l'extérieur avant le conseil.",
     "그럼 적어도 할 이야기는 생기네요. 좋아요... 정보가 샐 경우에 대비해 대응 문구를 준비하겠습니다. 하지만 이사회 전엔 아무것도 외부로 나가지 않습니다."),
(MA, "C'est exactement ça. Monsieur Pradier, j'aimerais que vous rencontriez le commissaire aux comptes avec madame Marchetti cette semaine, et que nous ayons son avis par écrit.",
     "바로 그겁니다. 프라디에 팀장님, 이번 주에 마르케티 이사님과 함께 감사인을 만나 그 의견을 서면으로 받아 주셨으면 합니다."),
(PR, "Ce sera fait, monsieur.", "그렇게 하겠습니다, 대표님."),
(MA, "Martine, inscrivez le sujet en premier point de l'ordre du jour. La note partira avec le dossier du conseil, à tous les administrateurs, le même jour, à la même heure.",
     "마르틴, 이 안건을 의제 첫 번째 항목으로 올려 주세요. 보고서는 이사회 자료와 함께 모든 이사에게 같은 날, 같은 시각에 보냅니다."),
(MR, "En premier point... Monsieur Hubert n'aime pas les surprises en premier point.", "첫 번째 항목으로요... 위베르 회장님은 첫 번째 항목에서 놀라는 걸 싫어하세요."),
(MA, "Je sais. Mais il aimerait encore moins les découvrir en dernier.", "압니다. 하지만 마지막에 알게 되시는 건 더 싫어하실 겁니다."),
(MR, "... Vous savez, monsieur Kessler, en trente ans, c'est la première fois que je vois un directeur général commencer par une mauvaise nouvelle. D'habitude, ils la gardent pour la fin de leur mandat.",
     "...있잖아요, 케슬레르 대표님. 30년 동안 대표이사가 나쁜 소식으로 시작하는 건 처음 봐요. 보통은 임기 말까지 아껴 두거든요."),
(I, "Il faut un début à tout, Martine. Monsieur Kessler, je vous envoie le projet de note demain à huit heures.", "뭐든 처음이 있는 법이죠, 마르틴. 케슬레르 대표님, 보고서 초안은 내일 8시에 보내 드리겠습니다."),

# ---------- 6. Le soir : quartier Jacquard ----------
(None, "22 h. Quartier Jacquard. L'appartement d'Inès : des cartons partout, un matelas gonflable, pas une chaise. Ils mangent une pizza assis sur deux cartons marqués « LIVRES ». Figaro inspecte chaque pièce, la queue dressée.",
       "밤 10시. 자카르 지구. 이네스의 아파트에는 상자들이 사방에 있고, 에어 매트리스 하나뿐 의자는 하나도 없다. 두 사람은 '책'이라고 적힌 상자 두 개에 앉아 피자를 먹는다. 피가로가 꼬리를 세우고 방마다 살펴본다."),
(MA, "Bon. Porte fermée, rideaux tirés... Je peux enfin te tutoyer. Tu sais que j'ai failli t'appeler « Inès » trois fois devant Chazal ?", "자. 문 닫았고, 커튼 쳤고... 드디어 말 놓을 수 있다. 샤잘 앞에서 너를 '이네스'라고 부를 뻔한 게 세 번이었던 거 알아?"),
(I, "Je sais. La troisième fois, tu as dit « In... madame Marchetti ». J'ai cru que Josiane allait le noter dans son carnet.", "알아. 세 번째엔 '이네... 마르케티 이사님'이라고 했잖아. 조지안이 수첩에 적는 줄 알았어."),
(MA, "Elle note tout. C'est son métier, apparemment.", "그분은 다 적는대. 그게 직업이라나 봐."),
(I, "Regarde Figaro. Il fait le tour du propriétaire. Il a déjà choisi son carton préféré.", "피가로 좀 봐. 집 구석구석 둘러보고 있어. 벌써 제일 좋아하는 상자를 골랐네."),
(MA, "Celui où il est écrit « VAISSELLE — FRAGILE ». Évidemment.", "'그릇 — 깨지기 쉬움'이라고 적힌 거. 당연하지."),
(None, "Figaro saute hors du carton, puis sur les genoux de Mathieu, et s'y installe en ronronnant.", "피가로가 상자에서 뛰쳐나와 마티외의 무릎 위로 올라가더니, 가르랑거리며 자리를 잡는다."),
(I, "Le traître. Il ne fait ça avec personne, tu sais.", "배신자. 쟤 아무한테도 저러지 않아, 알지?"),
(MA, "Il a compris que j'allais rester dans les parages. D'ailleurs, j'ai pris une décision dans le train, ce matin. Je rends mon studio de la rue Raymond-Losserand.",
     "내가 근처에 계속 있을 거란 걸 알아챈 거지. 그러고 보니 오늘 아침 기차에서 결심한 게 있어. 레몽로스랑 거리 원룸 뺄 거야."),
(I, "Ton studio ? Celui des onze visites et des deux plaques ? Tu l'adorais.", "네 원룸? 열한 번 집 보고 구한, 화구 두 개짜리? 그렇게 좋아했잖아."),
(MA, "Je l'adorais. Mais payer un loyer à Paris pour y dormir deux nuits par mois, ça n'a aucun sens. Je donne mon préavis demain : un mois, puisque Paris est en zone tendue.",
     "좋아했지. 그런데 한 달에 이틀 자려고 파리에 월세를 내는 건 말이 안 돼. 내일 해지 통보할 거야. 파리는 주택 수요 과열 지역이라 한 달이면 돼."),
(I, "Et le week-end, à Paris, tu dormiras où ?", "그럼 주말에 파리에선 어디서 잘 건데?"),
(MA, "Je pensais... chez une Marseillaise d'Oberkampf qui a un chat grincheux. Si elle veut bien de moi.", "생각해 봤는데... 성질 고약한 고양이를 키우는 오베르캉프의 마르세유 여자네 집에서. 날 받아 준다면."),
(I, "Elle veut bien. À condition que tu fasses la vaisselle et que tu supportes l'OM à la télé.", "받아 줄 거야. 설거지하고, 텔레비전으로 마르세유 경기 보는 걸 견딘다는 조건으로."),
(MA, "La vaisselle, oui. L'OM, on négociera. ... Tu sais, aujourd'hui, j'ai eu peur. Pas devant le comité. Quand tu m'as répondu « Pas tout de suite ? », je me suis entendu parler comme quelqu'un qui fuit.",
     "설거지는 좋아. 마르세유는 협상하자. ...있잖아, 오늘 무서웠어. 경영위원회 앞에서가 아니라. 네가 '당장은 아니라고?' 하고 되물었을 때, 내가 도망치는 사람처럼 말하고 있는 게 들렸어."),
(I, "Mais tu ne t'es pas enfui. Tu as mis le sujet en premier point. Martine en avait presque les larmes aux yeux.", "그래도 도망치지 않았잖아. 그 안건을 첫 번째 항목에 올렸어. 마르틴은 거의 눈물이 글썽했다고."),
(MA, "Martine a trente ans de directeurs derrière elle. Si on veut qu'elle nous croie, il faudra tenir parole. Avec Josiane aussi. Et avec Momo.", "마르틴은 대표이사를 30년이나 겪어 봤어. 그분이 우릴 믿게 하려면 약속을 지켜야 해. 조지안한테도. 모모한테도."),
(None, "Mathieu sort le vieux marqueur vert de sa poche et écrit trois lignes sur le carton posé entre eux.", "마티외가 주머니에서 낡은 초록 마커를 꺼내 둘 사이에 놓인 상자 위에 세 줄을 쓴다."),
(I, "Le marqueur vert, sur mes cartons ? Tu oses.", "초록 마커를, 내 상자에? 감히."),
(MA, "Quel est le vrai problème ? Une garantie que personne n'a voulu voir. Qui décide ? Le conseil, dans trois semaines. Et... que fait-on lundi ?",
     "진짜 문제는 무엇인가? 아무도 보려 하지 않았던 보증. 누가 결정하는가? 3주 뒤의 이사회. 그리고... 월요일엔 뭘 하지?"),
(I, "On dit la vérité au conseil. Et on écrit la note de façon qu'Hubert Verdier ne puisse pas la lire en diagonale.", "이사회에 진실을 말하는 거지. 그리고 위베르 베르디에가 대충 훑어 읽을 수 없게 보고서를 쓰는 거야."),
(MA, "Alors je rentre chez moi. Si le directeur général sort de chez la directrice financière à sept heures du matin, tout Saint-Étienne le saura avant le conseil.",
     "그럼 난 집에 갈게. 대표이사가 아침 7시에 재무 담당 이사 집에서 나오면, 이사회 전에 생테티엔 전체가 알게 될 거야."),
(I, "Tu as raison... Bonne nuit, monsieur Kessler. ... Reste encore cinq minutes, Strasbourg. Figaro dort sur toi.", "네 말이 맞아... 안녕히 주무세요, 케슬레르 대표님. ...5분만 더 있어, 스트라스부르. 피가로가 네 위에서 자잖아."),
]

VOCAB = [
("B2", "prendre ses fonctions / une prise de fonctions", "취임하다, 업무를 시작하다 / 취임", "le jour de sa prise de fonctions = 취임 첫날. entrer en fonctions도 같은 뜻."),
("B2", "le comité de direction (codir)", "경영위원회, 임원 회의", "각 부문 이사들이 모이는 경영진 회의. 이사회(conseil d'administration)와 구분."),
("B1", "une caisse de transport", "(반려동물) 이동장", "기차에서 작은 반려동물은 이동장에 넣으면 소액 요금으로 동반할 수 있다."),
("B2", "enchaîner", "(말·동작을) 바로 이어 가다", "Dis « Bonjour à tous » et enchaîne vite. enchaîner les réunions = 회의를 연달아 하다."),
("B2", "Ne t'emballe pas.", "흥분하지 마, 너무 앞서가지 마", "s'emballer = (말이) 날뛰다 → 감정이 앞서다. (1화 복습)"),
("B2", "se redresser / le redressement", "(기업이) 다시 일어서다 / 회생", "une entreprise qui ne se redresse pas. redressement judiciaire = 법정 회생 절차."),
("B2", "le bilan / le compte de résultat / l'annexe", "재무상태표 / 손익계산서 / 주석", "프랑스 연간 재무제표(comptes annuels)의 세 부분. 결산은 la clôture de l'exercice."),
("B2", "le commissaire aux comptes (CAC)", "법정 감사인", "certifier les comptes sans réserve = 적정 의견으로 재무제표를 인증하다."),
("C1", "la continuité d'exploitation", "계속기업(가정)", "회사가 앞으로도 영업을 이어 갈 수 있는지. 의문이 있으면 감사인이 observation을 붙인다."),
("B2", "un engagement hors bilan", "부외 약정, 장부 외 의무", "보증·담보·리스 약정처럼 재무상태표에는 없고 주석에만 적히는 약정."),
("B2", "une garantie (de maison mère) / appeler une garantie", "(모회사) 보증 / 보증 이행을 청구하다", "la garantie est appelée = 채권자가 보증인에게 대신 갚으라고 요구하다."),
("B2", "le crédit-bail / un crédit-bailleur", "리스(금융리스) / 리스 회사", "설비·건물을 빌려 쓰며 리스료(loyer)를 내다가 만기에 살 수 있는 계약. leasing."),
("C1", "une clause de changement de contrôle", "지배권 변경 조항", "회사·자회사의 주인이 바뀌면 계약 해지나 즉시 상환이 발동되는 조항."),
("B2", "exigible", "(채무가) 즉시 갚아야 하는, 청구 가능한", "La garantie devient exigible en cas de vente. exiger(요구하다)에서 파생."),
("B2", "la dette nette", "순부채", "금융 부채에서 보유 현금을 뺀 금액. 3억 1천만 → 3억 7천만 유로."),
("B2", "une autorisation globale / un plafond", "포괄 승인 / 한도", "이사회가 정한 plafond 안에서는 대표이사가 매번 승인 없이 보증할 수 있다."),
("C1", "un cadavre dans le placard", "숨겨진 비리·약점", "직역 '벽장 속 시체'. 인수·취임 뒤 드러나는 감춰진 문제를 가리키는 관용구."),
("B2", "quelque chose cloche", "뭔가 이상하다, 잘못됐다", "구어. Il y a quelque chose qui cloche dans ces chiffres."),
("B2", "les éléments de langage", "(공식) 대응 문구, 메시지 가이드", "위기 때 대변인·임원이 똑같이 쓰도록 미리 정해 두는 표현들."),
("B2", "à l'aveugle", "눈을 가린 채, 정보 없이", "voter / décider à l'aveugle. 블라인드 테스트는 un test à l'aveugle."),
("C1", "un parapheur", "결재 서류철", "서명할 서류를 끼워 대표에게 올리는 칸막이 서류철. 프랑스 사무실의 상징적 물건."),
("B2", "donner sa parole / tenir parole", "약속하다 / 약속을 지키다", "Je vous donne ma parole. ↔ manquer à sa parole(약속을 어기다)."),
("B1", "faire le tour du propriétaire", "(새 집·장소를) 한 바퀴 둘러보다", "원래는 집주인이 손님에게 집을 구경시켜 주는 것. 고양이에게도 농담으로 씀."),
("B2", "dans les parages", "근처에, 주변에", "Je vais rester dans les parages. 구어적이지만 격식 자리에서도 무난하다."),
("B2", "lire en diagonale", "대충 훑어 읽다", "직역 '대각선으로 읽다'. ↔ lire attentivement, éplucher un dossier."),
]

GRAM = [
("B2", "격식 있는 부임 인사와 발언 넘기기",
 "« Bonjour à tous. Je suis Mathieu Kessler. J'ai trente-trois ans, je suis alsacien, ingénieur de formation... » « Je vous demande donc une seule chose : dites-moi ce qui ne va pas. » « Je lui laisse la parole. » « Merci d'être restés. » 부임 인사는 이름·배경 → 상대의 예상을 먼저 말하기(Je sais ce que vous pensez) → 요청 한 가지의 순서가 효과적이다. 회의 진행에서는 laisser / donner la parole à qn(발언을 넘기다), Merci de + 부정사 과거(Merci d'être venus)가 기본 표현이다."),
("B2", "vous/tu 전환과 직함 호칭",
 "« À partir de maintenant, on se vouvoie. » « Très bien, madame Marchetti. » « Porte fermée, donc je peux te tutoyer. » « Bonne nuit, monsieur Kessler. ... Reste encore cinq minutes, Strasbourg. » se vouvoyer / se tutoyer는 '서로 vous / tu로 부르다'. 직장에서는 madame / monsieur + 성, 또는 monsieur le directeur général처럼 직함 앞에 정관사를 붙인다. 같은 사람에게 문장마다 호칭이 바뀌는 것 자체가 관계의 거리를 보여 주는 장치다."),
("B2", "부정 선행사 뒤 관계절의 접속법: rien que je ne comprenne pas",
 "« Je ne fermerai rien que je ne comprenne pas. » « Je ne vous promettrai rien que je ne puisse tenir. » « aucune présentation au conseil que j'aie lue » 선행사가 rien, personne, aucun 등 부정이거나 존재가 불확실하면 관계절에 접속법을 쓴다. 직설법(que je comprends)을 쓰면 '실제로 이해한 것'이 있다는 전제가 되어 뜻이 달라진다. 격식 있는 약속·단언에서 자주 쓰는 B2~C1 구문이다."),
("C1", "quand bien même + 조건법 / même si + 직설법",
 "« Quand bien même on aurait la meilleure stratégie du monde, chaque jour de silence ferait de nous des complices. » « C'est du camouflage, même s'il est légal. » quand bien même(설령 ~할지라도)는 가정적 양보로, 주절과 종속절 모두 조건법을 쓴다. 회화에서는 même si + 반과거(Même si on avait la meilleure stratégie...)가 더 흔하다. même si 뒤에는 조건법이 오지 않는다는 점에 주의."),
("B2", "sans que / avant que + 접속법",
 "« un engagement de soixante millions a pu être signé sans que le conseil en débatte vraiment » « sans que personne en parle au conseil » « Je montais des Stéphanoise avant que vous soyez né. » sans que와 avant que 뒤에는 항상 접속법. 문어에서는 허사 ne를 넣기도 한다(avant que vous ne soyez né). 또 sans que 뒤에서는 personne / rien을 ne 없이 쓴다(sans que personne en parle)."),
("B2", "je ne crois pas que + 접속법 과거",
 "« Je ne crois pas qu'il ait lu l'annexe. » croire / penser가 긍정이면 직설법(Je crois qu'il a lu), 부정·의문이면 의심이 생기므로 접속법을 쓴다. 이미 끝난 일에 대한 의심은 접속법 과거(avoir / être의 접속법 + 과거분사): qu'il ait lu, qu'elle soit partie."),
("B2", "조건법: 가정의 결과와 완곡한 의견",
 "« Si la garantie était appelée, la dette passerait à trois cent soixante-dix millions. » « Je préférerais qu'on présente la garantie dans notre plan à cent jours. » « Il vaudrait mieux. » « au cas où l'information sortirait » si + 반과거 → 조건법 현재로 수치 시나리오를 제시한다. au cas où 뒤에는 조건법이 온다(접속법 아님). je préférerais / il vaudrait mieux는 의견을 부드럽게 내는 경영 회의의 단골 표현이다."),
("B2", "재무 보고의 문장: ne... ni... ni / ne... que / passer de... à",
 "« Soixante millions qui ne figurent ni au bilan ni dans aucune présentation au conseil. » « À l'usine, on ne nous montre que les factures d'électricité. » « notre dette nette passe de trois cent dix à trois cent soixante-dix millions » 두 가지를 동시에 부정할 때는 ne... ni... ni, 제한할 때는 ne... que. 수치 변화는 passer de A à B(1화·2화 복습). figurer dans / au bilan(~에 기재되다)도 재무 문서의 기본 동사다."),
]

CULTURE = [
("프랑스 기업의 연간 재무제표와 '부외 약정'",
 "프랑스 기업의 연간 재무제표(comptes annuels)는 재무상태표(bilan), 손익계산서(compte de résultat), 주석(annexe)의 세 부분으로 이루어진다. 일정 규모 이상의 회사는 법정 감사인(commissaire aux comptes)이 재무제표를 인증하는데, 적정 의견(certification sans réserve)을 내면서도 계속기업 가정에 대한 불확실성처럼 독자가 꼭 알아야 할 사항을 따로 강조할 수 있다. 보증·담보 제공·리스 약정 같은 부외 약정(engagements hors bilan)은 재무상태표에는 나타나지 않고 주석에만 기재되기 때문에, 법적으로는 공시되었어도 실제로는 잘 읽히지 않는 경우가 많다."),
("PDG, DG, 이사회 의장 — 그리고 보증의 승인",
 "프랑스 주식회사(SA)의 이사회형 구조에서는 이사회 의장(président du conseil d'administration)과 대표이사(directeur général)를 한 사람이 겸할 수도 있고(이때 PDG, président-directeur général), 둘로 나눌 수도 있다. Verdier처럼 창업 가문이 의장을 맡고 외부 경영인이 대표이사를 맡는 분리형이 흔하다. 회사가 제3자를 위해 서는 보증(cautions, avals et garanties)은 원칙적으로 이사회 승인이 필요하지만, 상법은 이사회가 대표이사에게 한도(plafond)를 정해 1년 단위로 포괄 승인을 줄 수 있도록 하고 있다. 이 제도 덕분에 큰 보증이 이사회에서 따로 논의되지 않고 지나가는 일이 생기기도 한다."),
("생테티엔과 프랑스의 압력솥",
 "생테티엔은 19세기부터 탄광과 무기·자전거·리본 산업으로 성장한 공업 도시다. 무기와 자전거, 두툼한 우편 판매 카탈로그로 유명했던 Manufrance가 이 도시의 상징이었고, 도시 곳곳에 보이는 검은 언덕 crassiers는 옛 탄광의 폐석 더미다. 옛 국립 무기 공장 터에는 지금 디자인 센터(Cité du design)가 들어서 있다. 압력솥은 전후 프랑스 가정에 빠르게 보급되어, 1950년대에 나온 국산 압력솥 상표 « Cocotte-Minute »가 아예 압력솥을 가리키는 일반 명사처럼 쓰일 정도다. 극 중 « La Stéphanoise »는 이런 '국민 가전'을 모델로 한 가상의 제품이다."),
]
