# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H = "Inès", "Mathieu", "Hélène"
HU, AU, CL, MR, MO = "Hubert", "Aubry", "Claire", "Martine", "Momo"

META = {
    "part": 2, "ep": 17,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Le conseil d'administration",
    "title_ko": "이사회",
    "place": "생테티엔 자카르 지구 이네스 아파트 · Verdier Industries 본사 이사회실 · 생테티엔 공장 옛 작업장 · 시청 근처 마티외 아파트 / 9월 말, 어느 목요일 하루",
    "chars": "이네스, 마티외, 엘렌(신임 사외이사), 위베르 베르디에(이사회 의장), 프레데리크 오브리(아르칸 캐피털 파트너), 클레르 베르디에(위베르의 조카, 이사), 마르틴 로슈(CEO 비서), 모모(숙련공)",
    "work": "첫 이사회 — 폴란드 브로츠와프 공장 리스 보증 6,000만 유로 공개, 창업 가문(생테티엔 축소 반대)과 펀드(브로츠와프 매각 요구)의 대립, 사외이사 선임, 100일 전략 계획 결의",
    "life": "넥타이를 매 주며 하는 아침 리허설, 따로 출근하기, 회의 중의 vous, 엘렌의 경고, 비밀 연애의 규칙 정하기",
    "focus": "회의 진행·발언권 표현(ordre du jour, quorum, suspension de séance, mettre aux voix), 격식체 호칭, 접속법(souhaiter que, il faut que, à condition que, sans que), 조건법 과거, 양보 표현, 재무·지배구조 어휘(hors bilan, cession-bail, se porter garant)",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제18화 Les cent premiers jours — 로안 출장 중의 화요일 밤 영상통화, 100일 계획과 영업이사 교체, 그리고 주말 없는 연애.",
}

D = [
# ---------- 1. Ouverture : la cravate ----------
(None, "Un jeudi de fin septembre, 7 h. Saint-Étienne, quartier Jacquard. L'appartement d'Inès est encore plein de cartons ; Figaro dort sur une pile de dossiers. Devant le miroir, Mathieu se bat avec sa cravate.",
       "9월 말의 어느 목요일, 오전 7시. 생테티엔 자카르 지구. 이네스의 아파트는 아직 상자투성이고, 피가로는 서류 더미 위에서 자고 있다. 거울 앞에서 마티외가 넥타이와 씨름하고 있다."),
(MA, "Je n'y arrive pas. Cette cravate me déteste. Elle est comme ton chat.", "안 돼. 이 넥타이가 날 싫어해. 네 고양이처럼."),
(I, "Viens ici. Lève le menton. Un CEO qui ne sait pas faire son nœud de cravate, on aura tout vu.", "이리 와. 턱 들어. 넥타이도 못 매는 CEO라니, 별꼴을 다 보네."),
(MA, "À Strasbourg, je n'en portais jamais. Sur les chantiers, personne ne regardait mon cou.", "스트라스부르에선 한 번도 안 맸어. 현장에선 아무도 내 목을 안 봤거든."),
(I, "Aujourd'hui, sept administrateurs vont le regarder. Répète ton introduction pendant que je serre.", "오늘은 이사 일곱 명이 볼 거야. 내가 조이는 동안 첫인사 연습해 봐."),
(MA, "« Monsieur le président, mesdames et messieurs les administrateurs, permettez-moi tout d'abord de vous remercier pour la confiance que vous nous avez accordée, et de... »",
     "'의장님, 그리고 이사 여러분, 먼저 저희에게 보내 주신 신뢰에 감사드리며, 아울러...'"),
(I, "Trop long. Hubert Verdier aura décroché au bout de dix secondes. Va droit au but.", "너무 길어. 위베르 베르디에는 10초 만에 딴생각할 거야. 바로 본론으로 가."),
(MA, "D'accord. « Monsieur le président, je serai bref : la situation est plus grave que prévu, et je souhaite que vous l'appreniez de notre bouche. » C'est mieux ?",
     "알았어. '의장님, 짧게 말씀드리겠습니다. 상황은 예상보다 심각하고, 저는 여러분이 그 사실을 저희 입으로 직접 들으시길 바랍니다.' 이게 나아?"),
(I, "Beaucoup mieux. Ensuite, tu me passes la parole pour la garantie. Je ne veux pas que ce soit toi qui annonces les soixante millions.", "훨씬 나아. 그다음에 보증 건은 나한테 발언권을 넘겨. 6,000만 유로를 네가 발표하는 건 싫어."),
(MA, "Pourquoi ? Je suis le directeur général, c'est mon rôle.", "왜? 내가 대표이사잖아. 그게 내 역할인데."),
(I, "Parce que les chiffres, c'est moi. Et si Hubert doit crier sur quelqu'un, je préfère que ce soit sur la CFO. Toi, tu auras besoin de lui pendant des années.",
    "숫자는 내 담당이니까. 그리고 위베르가 누군가한테 소리를 질러야 한다면 CFO한테 지르는 게 나아. 넌 앞으로 몇 년 동안 그 사람이 필요할 거야."),
(None, "Elle termine le nœud, recule d'un pas et l'observe.", "그녀가 매듭을 마무리하고 한 걸음 물러나 그를 살펴본다."),
(I, "Voilà. Présentable. Presque crédible.", "됐다. 봐줄 만해. 거의 믿음직스러워."),
(MA, "Merci, madame la directrice financière. On y va ensemble ? Ma voiture est garée en bas.", "고맙습니다, 재무이사님. 같이 갈까? 차 아래에 세워 뒀어."),
(I, "Non. On a dit qu'on arrivait séparément. Toi, tu prends le tram de sept heures et demie. Moi, j'arrive à huit heures et quart, avec mes dossiers et une tête de femme qui a passé la nuit sur ses tableaux.",
    "안 돼. 따로 출근하기로 했잖아. 넌 7시 반 트램 타. 난 8시 15분에 갈게. 서류 들고, 밤새 엑셀만 본 여자 얼굴로."),
(MA, "Et si quelqu'un me voit sortir de ton immeuble ?", "누가 내가 너희 건물에서 나오는 걸 보면?"),
(I, "Alors tu étais passé chercher les comptes annuels. Tiens, prends-les. Et file, Strasbourg.", "그럼 연간 재무제표 가지러 들렀던 거야. 자, 이거 가져가. 그리고 얼른 가, 스트라스부르."),

# ---------- 2. Le conseil : la séance du matin ----------
(None, "8 h 40. Siège de Verdier Industries, salle du conseil. Aux murs, les portraits de cinq générations de Verdier ; dans une vitrine, le premier vélo de 1874. Martine Roche dispose les dossiers autour de la table.",
       "오전 8시 40분. Verdier Industries 본사 이사회실. 벽에는 베르디에 가문 5대의 초상화가, 진열장에는 1874년의 첫 자전거가 있다. 마르틴 로슈가 테이블에 서류를 놓고 있다."),
(MR, "Bonjour, monsieur Kessler. Vous êtes en avance. Votre prédécesseur arrivait toujours le dernier, et toujours essoufflé.", "안녕하세요, 케슬레르 대표님. 일찍 오셨네요. 전임자분은 늘 맨 마지막에, 늘 숨을 헐떡이며 오셨는데."),
(MA, "Bonjour, Martine. Madame Marchetti est arrivée ?", "안녕하세요, 마르틴. 마르케티 이사님은 오셨나요?"),
(MR, "Pas encore. Voulez-vous que je l'appelle ?", "아직요. 전화해 드릴까요?"),
(MA, "Non, non, inutile. Elle sera là à l'heure.", "아뇨, 괜찮아요. 제시간에 올 겁니다."),
(None, "9 h. Tout le monde est assis. Hubert Verdier, soixante-huit ans, préside. À sa droite, sa nièce Claire ; en face, Frédéric Aubry et un autre associé d'Arcane. Inès est à côté de Mathieu, à distance raisonnable.",
       "오전 9시. 모두 자리에 앉았다. 68세의 위베르 베르디에가 의장석에 있다. 오른쪽엔 조카 클레르, 맞은편엔 프레데리크 오브리와 아르칸의 다른 파트너. 이네스는 마티외 옆에, 적당한 거리를 두고 앉아 있다."),
(HU, "Bonjour à tous. Il est neuf heures, la séance est ouverte. Le conseil compte sept sièges, dont six pourvus ; les six administrateurs sont présents, le quorum est donc atteint. Madame Roche tiendra le procès-verbal.",
     "안녕하십니까. 9시입니다. 회의를 시작하겠습니다. 이사회 정원은 일곱 석이고 그중 여섯 석이 채워져 있습니다. 이사 여섯 분이 모두 출석하셨으니 정족수는 충족됐습니다. 의사록은 로슈 씨가 작성합니다."),
(HU, "L'ordre du jour comporte cinq points : l'approbation du procès-verbal de juin, la cooptation d'une administratrice indépendante, la présentation de la nouvelle direction, la situation financière, et les questions diverses.",
     "안건은 다섯 가지입니다. 6월 의사록 승인, 사외이사 선임, 신임 경영진 소개, 재무 현황, 그리고 기타 사항입니다."),
(AU, "Monsieur le président, je demande qu'on inscrive un point supplémentaire : l'avenir du site de Wrocław.", "의장님, 안건 하나를 추가해 주실 것을 요청합니다. 브로츠와프 공장의 향후 방향입니다."),
(HU, "Nous en parlerons dans les questions diverses, monsieur Aubry. Ce n'est pas à Arcane de fixer l'ordre du jour de cette maison.", "그건 기타 사항에서 다루겠습니다, 오브리 씨. 이 회사의 안건을 정하는 건 아르칸이 아닙니다."),
(CL, "Mon oncle, si vous me permettez... Le sujet viendra sur la table de toute façon. Autant l'inscrire clairement ; cela nous évitera d'en parler tout l'après-midi dans les couloirs.",
     "삼촌, 실례지만... 그 문제는 어차피 나올 거예요. 차라리 분명히 안건에 올리죠. 그래야 오후 내내 복도에서 수군거리지 않을 테니까요."),
(HU, "... Soit. Point six : Wrocław. Premier point, le procès-verbal de juin. Des observations ? Aucune. Il est approuvé.", "...좋습니다. 6번 안건, 브로츠와프. 1번 안건, 6월 의사록. 의견 있으십니까? 없군요. 승인됐습니다."),
(HU, "Deuxième point : la cooptation de madame Hélène Vasseur au siège laissé vacant en juin, sous réserve de ratification par la prochaine assemblée générale. Qui est pour ? ... Unanimité. Madame Roche, faites entrer madame Vasseur, je vous prie.",
     "2번 안건. 6월에 공석이 된 자리에 엘렌 바쇠르 씨를 선임하는 건이며, 다음 주주총회의 추인을 조건으로 합니다. 찬성하시는 분? ...만장일치입니다. 로슈 씨, 바쇠르 씨를 모셔 주세요."),
(None, "Hélène entre, salue l'assemblée d'un signe de tête et prend place au bout de la table. Elle ne regarde ni Inès ni Mathieu.", "엘렌이 들어와 고개 숙여 인사하고 테이블 끝에 앉는다. 이네스도 마티외도 쳐다보지 않는다."),
(H, "Merci, monsieur le président. Un mot seulement : être indépendante, cela veut dire que je ne serai l'alliée de personne. Ni de la famille, ni du fonds... ni de la direction générale.",
    "감사합니다, 의장님. 한 말씀만 드리겠습니다. 독립적이라는 건 제가 누구의 편도 아니라는 뜻입니다. 가문의 편도, 펀드의 편도... 경영진의 편도 아닙니다."),
(HU, "Voilà qui a le mérite d'être clair. Troisième point. Monsieur Kessler, vous avez la parole.", "명쾌해서 좋군요. 3번 안건. 케슬레르 대표, 말씀하세요."),
(MA, "Monsieur le président, mesdames et messieurs, je serai bref : la situation est plus grave que prévu, et je souhaite que vous l'appreniez de notre bouche plutôt que de celle d'un auditeur. Madame Marchetti va vous présenter les chiffres.",
     "의장님, 그리고 이사 여러분, 짧게 말씀드리겠습니다. 상황은 예상보다 심각하며, 저는 여러분께서 그 사실을 감사인이 아닌 저희 입으로 직접 들으시길 바랍니다. 마르케티 이사가 수치를 보고드리겠습니다."),
(I, "Merci, monsieur Kessler. Vous connaissez les chiffres publiés : sept cent quatre-vingts millions d'euros de chiffre d'affaires, quarante-deux millions de perte nette, trois cent dix millions de dette nette. Ce que vous ne connaissez peut-être pas, c'est la note trente et un de l'annexe des comptes.",
    "감사합니다, 케슬레르 대표님. 공시된 수치는 아실 겁니다. 매출 7억 8천만 유로, 순손실 4,200만 유로, 순부채 3억 1천만 유로. 여러분이 모르실 수도 있는 것은 재무제표 주석 31번입니다."),
(AU, "La note trente et un. Les engagements hors bilan.", "주석 31번. 부외 약정이군요."),
(I, "Exactement. Il y a deux ans, notre filiale Verdier Polska a pris en crédit-bail, pour dix ans, une nouvelle halle et deux lignes de production à Wrocław. Verdier Industries s'est portée garante de tous les loyers jusqu'au terme du contrat. Montant de la garantie : soixante millions d'euros.",
    "그렇습니다. 2년 전 자회사 Verdier Polska가 브로츠와프의 새 공장동과 생산 라인 두 개를 10년 리스로 들였습니다. Verdier Industries는 계약 만료까지의 리스료 전액을 보증했습니다. 보증 금액은 6,000만 유로입니다."),
(HU, "Soixante millions ? Hors bilan ? Qu'est-ce que c'est que cette histoire ?", "6,000만이요? 부외라고요? 이게 대체 무슨 소립니까?"),
(I, "Si notre filiale polonaise cesse de payer son loyer, c'est la maison mère qui paie. Autrement dit, notre exposition réelle n'est pas de trois cent dix millions, mais de trois cent soixante-dix.",
    "폴란드 자회사가 임대료를 못 내면 모회사가 냅니다. 다시 말해 저희의 실제 위험 노출액은 3억 1천만이 아니라 3억 7천만 유로입니다."),
(HU, "C'est inadmissible ! Jamais une chose pareille n'a été présentée à ce conseil ! Je veux savoir qui a signé ça.", "용납할 수 없습니다! 이런 건 이사회에 한 번도 보고된 적이 없어요! 누가 서명했는지 알아야겠습니다."),
(I, "L'ancien directeur financier, monsieur le président. Mais le conseil l'y avait autorisé. Procès-verbal du 14 mars, il y a deux ans : « Le conseil autorise la direction à consentir les garanties usuelles liées au projet de Wrocław. » La garantie a été signée en août, pendant vos vacances. La signature en bas de la page est la vôtre.",
    "전임 재무이사입니다, 의장님. 하지만 이사회가 그에게 권한을 줬습니다. 2년 전 3월 14일 의사록입니다. '이사회는 경영진이 브로츠와프 프로젝트와 관련된 통상적 보증을 제공하는 것을 승인한다.' 보증서는 그해 8월, 의장님 휴가 중에 서명됐습니다. 그 페이지 아래 서명은 의장님 것입니다."),
(None, "Silence. Hubert Verdier retire lentement ses lunettes.", "정적. 위베르 베르디에가 천천히 안경을 벗는다."),
(HU, "« Les garanties usuelles »... Personne ne m'a jamais dit qu'elles se montaient à soixante millions.", "'통상적 보증'이라... 그게 6,000만에 이른다고 말해 준 사람은 아무도 없었습니다."),
(AU, "Pour être tout à fait honnête, nous l'avions repérée dans les comptes de l'an dernier. Nous pensions que tout le monde avait lu la note trente et un.",
     "솔직히 말씀드리면, 저희는 작년 재무제표에서 그걸 발견했습니다. 다들 주석 31번을 읽은 줄 알았죠."),
(CL, "Visiblement, non. Et c'est bien là le problème, Frédéric : si vous le saviez, pourquoi ne pas l'avoir dit ?", "보시다시피 아니었죠. 바로 그게 문제예요, 프레데리크. 알고 계셨다면 왜 말하지 않으셨어요?"),
(AU, "Parce que personne ne me l'a demandé. Je vous concède que ce n'est pas glorieux. Mais restons dans le présent : cette garantie est une raison de plus de céder Wrocław, et vite, avant qu'elle ne devienne un vrai problème.",
     "아무도 묻지 않았으니까요. 자랑스러운 일이 아니라는 건 인정합니다. 하지만 현재에 집중합시다. 이 보증은 브로츠와프를 매각해야 할 이유 하나를 더해 줍니다. 그것도 빨리, 진짜 문제가 되기 전에요."),
(HU, "Céder Wrocław, puis réduire Saint-Étienne, puis vendre la marque au plus offrant ! Je la connais, votre feuille de route, monsieur Aubry.", "브로츠와프를 팔고, 그다음엔 생테티엔을 줄이고, 그다음엔 브랜드를 최고가에 팔아넘기겠죠! 당신의 로드맵은 다 압니다, 오브리 씨."),
(AU, "Ma feuille de route s'appelle la survie, monsieur le président. Trois ans de pertes : à ce rythme, il n'y aura bientôt plus rien à transmettre à votre famille.", "제 로드맵의 이름은 생존입니다, 의장님. 3년 연속 적자예요. 이대로 가면 머지않아 가문에 물려줄 게 아무것도 남지 않을 겁니다."),
(MA, "Si vous me permettez, messieurs : la direction n'est ici ni pour vendre Wrocław, ni pour défendre le statu quo. Elle est ici pour que vous décidiez en connaissance de cause.", "실례지만 말씀드리겠습니다. 경영진은 브로츠와프를 팔려고 온 것도, 현상 유지를 옹호하려고 온 것도 아닙니다. 여러분이 충분히 알고 결정하시도록 하려고 이 자리에 있습니다."),
(H, "Monsieur le président, puis-je proposer une suspension de séance d'une demi-heure ? Il me semble que la direction a besoin de préparer une réponse. Et que nous avons tous besoin d'un café.",
    "의장님, 30분간 정회를 제안해도 될까요? 경영진이 답변을 준비할 시간이 필요해 보입니다. 그리고 우리 모두 커피가 필요한 것 같고요."),
(HU, "... Accordé. La séance est suspendue. Nous reprendrons à dix heures et demie.", "...받아들이겠습니다. 정회합니다. 10시 반에 속개하겠습니다."),

# ---------- 3. Analyse : le bureau du directeur général ----------
(None, "10 h. Le bureau du directeur général, porte fermée. Par la fenêtre, on aperçoit les toits de l'usine.", "오전 10시. 대표이사실, 문이 닫혀 있다. 창밖으로 공장 지붕들이 보인다."),
(MA, "Bon. Ça s'est passé exactement comme prévu. C'est-à-dire mal.", "자. 정확히 예상대로 흘러갔네. 그러니까, 나쁘게."),
(I, "Pas si mal. Hubert est furieux, mais il est surtout furieux contre lui-même. C'est plus utile que s'il l'était contre nous.", "그렇게 나쁘진 않아. 위베르는 화가 났지만, 무엇보다 자기 자신한테 화가 난 거야. 우리한테 화난 것보단 그게 더 쓸모 있어."),
(MA, "Et Aubry ? Il le savait depuis trois ans, et il n'a même pas bronché.", "오브리는? 3년 전부터 알고 있었으면서 눈 하나 깜짝 안 했어."),
(I, "Il ne bronche pas parce que ça l'arrange. Plus la situation paraît grave, plus sa solution paraît évidente : vendre Wrocław.", "그게 자기한테 유리하니까 꿈쩍도 안 하는 거야. 상황이 심각해 보일수록 그의 해법이 당연해 보이거든. 브로츠와프 매각."),
(MA, "Alors parlons-en franchement. Toi, en tant que CFO, tu vendrais ?", "그럼 솔직하게 얘기해 보자. 넌 CFO로서 팔겠어?"),
(I, "Je ne sais pas encore. Wrocław, c'est deux cent dix millions de production par an et sept pour cent de marge opérationnelle. C'est le seul site du groupe qui gagne de l'argent.",
    "아직 모르겠어. 브로츠와프는 연간 생산액 2억 1천만 유로에 영업이익률 7%야. 그룹에서 유일하게 돈을 버는 공장이지."),
(MA, "Donc on vendrait le seul morceau qui marche pour boucher les trous de ceux qui perdent. C'est absurde.", "그러니까 잘되는 유일한 조각을 팔아서 적자 나는 곳들 구멍을 메우겠다는 거네. 말도 안 돼."),
(I, "Pas forcément. Aubry estime qu'on en tirerait quatre-vingt-quinze millions. Avec ça, notre dette baisse de près d'un tiers, et les banques nous laissent respirer.",
    "꼭 그렇진 않아. 오브리는 9,500만 유로는 받을 수 있다고 봐. 그 돈이면 부채가 3분의 1 가까이 줄고 은행들도 숨 쉴 틈을 줄 거야."),
(MA, "Et dans deux ans ? On fabriquera nos cafetières et nos blenders où ? À Saint-Étienne, avec des coûts deux fois plus élevés ?", "그럼 2년 뒤엔? 커피메이커랑 블렌더는 어디서 만들어? 비용이 두 배인 생테티엔에서?"),
(I, "Je n'ai pas dit que j'étais pour. J'ai dit que le calcul se défend. Mais il y a un piège que personne n'a vu : la garantie. Si on vend la filiale, le bail continue, et la garantie aussi.", "찬성한다고 안 했어. 계산상으론 말이 된다고 했지. 그런데 아무도 못 본 함정이 있어. 보증이야. 자회사를 팔아도 임대차 계약은 계속되고, 보증도 그대로야."),
(MA, "Donc, à moins que le crédit-bailleur polonais n'accepte de nous libérer, on resterait garants des loyers d'une usine qui ne nous appartiendrait plus ?", "그러니까 폴란드 리스사가 우릴 풀어 주지 않는 한, 더 이상 우리 것도 아닌 공장의 임대료를 계속 보증하게 된다는 거야?"),
(I, "Exactement. Quatre-vingt-quinze millions encaissés, et soixante millions de risque toujours sur le dos.", "바로 그거야. 9,500만은 받고, 6,000만짜리 위험은 계속 떠안는 거지."),
(I, "Et un acheteur sérieux le saura. Soit il négociera le prix à la baisse, soit il exigera qu'on garde la garantie. Dans les deux cas, ces quatre-vingt-quinze millions sont un mirage.",
    "그리고 제대로 된 인수자라면 그걸 알 거야. 가격을 깎든지, 아니면 우리가 보증을 계속 지라고 요구하겠지. 어느 쪽이든 그 9,500만은 신기루야."),
(MA, "Il faudrait que la foncière accepte de transférer la garantie sur l'acheteur. C'est faisable ?", "부동산 회사가 보증을 인수자 쪽으로 넘기는 데 동의해야겠네. 그게 가능해?"),
(I, "Faisable, oui, à condition que l'acheteur soit plus solide que nous. Ce qui, vu nos comptes, n'est pas très difficile.", "가능은 하지. 인수자가 우리보다 탄탄하다는 조건이라면. 우리 재무 상태를 보면 그리 어려운 조건도 아니고."),
(None, "On frappe. Martine entre avec un plateau.", "노크 소리. 마르틴이 쟁반을 들고 들어온다."),
(MR, "Pardon de vous déranger. Un café pour vous, monsieur Kessler. Votre cravate est très bien nouée, aujourd'hui ; votre prédécesseur n'y est jamais arrivé. Et un thé pour vous, madame Marchetti : sans sucre, si je ne me trompe pas ?", "방해해서 죄송합니다. 케슬레르 대표님은 커피요. 오늘 넥타이가 아주 잘 매여 있네요. 전임자분은 한 번도 제대로 못 매셨는데. 그리고 마르케티 이사님은 차요. 설탕 없이, 맞죠?"),
(I, "Parfait, merci, Martine. Monsieur Kessler, vous disiez, au sujet de Saint-Étienne... ?", "완벽해요, 고마워요, 마르틴. 케슬레르 대표님, 생테티엔에 대해 말씀하시던 중이었죠...?"),
(MA, "Oui. Je disais, madame Marchetti, que nous ne pouvons pas promettre au président que rien n'y bougera.", "네. 마르케티 이사님, 의장님께 그곳은 아무것도 바뀌지 않을 거라고 약속할 수는 없다고 말하던 참이었습니다."),
(None, "Elle sort et referme doucement la porte. Un silence.", "그녀가 나가 조용히 문을 닫는다. 잠깐의 정적."),
(MA, "Tu crois qu'elle... ?", "설마 저분이...?"),
(I, "Je crois qu'elle travaille ici depuis trente ans et qu'elle voit tout. Continuons. Ta position sur Saint-Étienne ?", "30년 동안 여기서 일하면서 모든 걸 보는 분이라고 생각해. 계속하자. 생테티엔에 대한 네 입장은?"),
(MA, "Rien n'est tabou, mais rien ne se décide aujourd'hui. Je refuse de tailler dans une usine que j'ai visitée une seule fois.", "금기는 없지만, 오늘 결정되는 것도 없어. 딱 한 번 가 본 공장을 잘라 내는 건 거부해."),
(I, "Tu ne pourras pas reporter éternellement, Mathieu. Le conseil attend une réponse.", "영원히 미룰 순 없어, 마티외. 이사회는 답을 기다리고 있어."),
(MA, "Il n'aura pas une réponse. Il aura une méthode : cent jours, et un plan complet avec tous les scénarios. Vendre Wrocław ou la garder, réduire Saint-Étienne ou non. Tout chiffré, tout comparé.",
     "답이 아니라 방법을 주는 거야. 100일, 그리고 모든 시나리오를 담은 완전한 계획. 브로츠와프를 팔지 지킬지, 생테티엔을 줄일지 말지. 전부 숫자로, 전부 비교해서."),
(I, "Cent jours... Aubry en voudra moins. Et Hubert voudra la promesse que Saint-Étienne ne sera pas touchée.", "100일이라... 오브리는 더 짧게 원할 거야. 그리고 위베르는 생테티엔은 건드리지 않겠다는 약속을 원할 거고."),
(MA, "Et nous ne la donnerons ni à l'un ni à l'autre. Si nous promettons quelque chose aujourd'hui, nous serons l'otage de quelqu'un demain.", "그리고 우린 둘 중 누구에게도 약속하지 않을 거야. 오늘 뭔가를 약속하면 내일은 누군가의 인질이 돼."),
(I, "D'accord. Mais à une condition : pendant ces cent jours, je négocie avec le crédit-bailleur polonais. Si on doit vendre un jour, je veux que la garantie soit réglée avant.",
    "좋아. 대신 조건이 하나 있어. 그 100일 동안 내가 폴란드 리스사와 협상할게. 언젠가 팔아야 한다면, 그 전에 보증 문제는 정리돼 있어야 해."),
(MA, "Accordé. Et j'ajoute un comité stratégique pour suivre le plan, présidé par l'administratrice indépendante.", "좋아. 그리고 계획을 점검할 전략위원회를 하나 추가하자. 위원장은 사외이사로."),
(I, "Hélène ? Ils vont dire que c'est notre ancienne patronne.", "엘렌? 우리 예전 상사라고들 할 거야."),
(MA, "Justement. C'est la seule personne autour de cette table qui n'a rien à y gagner.", "바로 그래서야. 그 테이블에서 얻을 게 아무것도 없는 유일한 사람이니까."),
(H, "Je vous entends depuis le couloir, tous les deux. Baissez d'un ton. Et pour mémoire, je ne suis plus votre patronne : je suis votre administratrice. C'est pire.",
    "복도에서 둘 목소리가 다 들려. 목소리 좀 낮춰. 그리고 참고로, 난 이제 너희 상사가 아니야. 너희 회사 이사지. 그게 더 무서운 거야."),

# ---------- 4. Terrain : l'ancien atelier ----------
(None, "12 h 30. Pause déjeuner. Hubert Verdier a tenu à emmener la direction à l'usine, de l'autre côté de la rue. L'ancien atelier n° 1 est devenu une petite salle d'exposition : un vélo de 1874 et une rangée d'autocuiseurs de toutes les époques.",
       "오후 12시 30분. 점심시간. 위베르 베르디에가 굳이 경영진을 길 건너 공장으로 데려왔다. 옛 1번 작업장은 작은 전시실이 되었다. 1874년의 자전거, 그리고 시대별 압력솥이 줄지어 있다."),
(HU, "Mon arrière-grand-père a fabriqué ce vélo ici même. Et celle-ci, c'est la première Stéphanoise, en 1962. Mon père l'a présentée au Salon des arts ménagers, à Paris. Elle a sauvé l'entreprise.",
     "제 증조부께서 바로 여기서 이 자전거를 만드셨습니다. 그리고 이건 1962년의 첫 스테파누아즈예요. 아버지가 파리 가정용품 박람회에서 선보이셨죠. 이게 회사를 살렸습니다."),
(MA, "Monsieur Verdier, je tenais à vous dire... Je comprends que vous ayez été choqué, ce matin.", "베르디에 의장님, 꼭 드리고 싶은 말씀이 있었습니다... 오늘 아침 충격을 받으신 것, 이해합니다."),
(HU, "Choqué ? Non, monsieur Kessler. Humilié. J'ai signé un papier sans le lire. Mon père ne l'aurait jamais fait.", "충격이요? 아니요, 케슬레르 대표. 굴욕이었습니다. 읽지도 않고 서류에 서명했어요. 제 아버지라면 절대 그러지 않으셨을 겁니다."),
(I, "Monsieur le président, la plupart des administrateurs auraient signé ce procès-verbal. La formule avait été rédigée pour être signée sans être lue.", "의장님, 대부분의 이사들도 그 의사록에 서명했을 겁니다. 그 문구는 읽히지 않고 서명되도록 쓰인 것이었으니까요."),
(HU, "C'est aimable à vous, madame. Mais je ne suis pas la plupart des administrateurs. Je suis un Verdier.", "친절한 말씀이군요, 마르케티 이사. 하지만 저는 대부분의 이사가 아닙니다. 저는 베르디에입니다."),
(None, "Un homme en bleu de travail traverse l'atelier, une soupape à la main. C'est Momo.", "작업복 차림의 남자가 밸브 하나를 들고 작업장을 가로지른다. 모모다."),
(MO, "Monsieur Hubert ! Ça faisait longtemps qu'on ne vous avait pas vu à l'atelier.", "위베르 사장님! 작업장에서 뵌 지 정말 오래됐네요."),
(HU, "Momo ! Toujours là ? Tu devais partir à la retraite il y a deux ans, il me semble.", "모모! 아직 있었나? 2년 전에 은퇴하기로 하지 않았던가."),
(MO, "Et qui montrerait les soupapes aux jeunes ? Bonjour, monsieur le directeur. Bonjour, madame. Alors, cette réunion ? À l'atelier, on dit que le fonds veut tout vendre.",
     "그럼 젊은 애들한테 밸브는 누가 가르치고요? 안녕하세요, 대표님. 안녕하세요, 이사님. 그래서 그 회의는 어떻게 돼 가요? 작업장에선 펀드가 다 팔아 치우려 한다던데."),
(MA, "On dit beaucoup de choses, Momo. Aujourd'hui, on ne vend rien et on ne ferme rien. Je vous le dis à vous comme je le dirai au conseil cet après-midi.", "말은 많죠, 모모 씨. 오늘은 아무것도 팔지 않고, 아무것도 닫지 않습니다. 오후에 이사회에서 할 말을 지금 모모 씨께도 똑같이 드리는 겁니다."),
(MO, "Vous, je vous crois. Mais vous comprendrez qu'on attende de voir. Ici, on a vu passer quatre directeurs généraux en dix ans.", "대표님 말은 믿어요. 하지만 저희가 두고 보겠다는 건 이해하시겠죠. 여기선 10년 동안 대표이사가 넷이나 지나갔거든요."),
(None, "Momo s'éloigne. Claire Verdier entre à son tour dans l'atelier.", "모모가 멀어진다. 이번엔 클레르 베르디에가 작업장으로 들어온다."),
(CL, "Mon oncle, Geneviève vous cherche pour le déjeuner. Elle veut vous parler avant la reprise.", "삼촌, 즈느비에브 고모가 점심 드시자고 찾으세요. 속개 전에 할 얘기가 있으시대요."),
(HU, "Ma sœur veut toujours me parler avant que je dise une bêtise. Excusez-moi.", "누이는 늘 내가 실언하기 전에 얘기를 하고 싶어 하지. 실례하겠습니다."),
(CL, "Je voulais vous voir seuls une minute. Mon oncle n'est pas votre ennemi. Il a peur d'être le Verdier qui aura perdu Verdier.", "두 분만 잠깐 뵙고 싶었어요. 삼촌은 두 분의 적이 아니에요. 베르디에를 잃은 베르디에가 될까 봐 두려운 거예요."),
(MA, "Et vous, madame Verdier, de quoi avez-vous peur ?", "그럼 클레르 이사님은 뭐가 두려우세요?"),
(CL, "Que la famille préfère couler avec le bateau plutôt que de changer de cap. Je soutiendrai une réforme, même douloureuse. Mais il faut qu'elle soit présentée de façon que mon oncle puisse la voter sans se renier.",
     "가문이 항로를 바꾸느니 차라리 배와 함께 가라앉는 쪽을 택할까 봐요. 저는 개혁을 지지할 거예요, 고통스럽더라도요. 하지만 삼촌이 자기 자신을 부정하지 않고도 찬성표를 던질 수 있게 제시돼야 해요."),
(I, "Autrement dit, il faut lui laisser une porte de sortie honorable.", "다시 말해, 명예로운 출구를 남겨 드려야 한다는 거군요."),
(CL, "Exactement. Et il faut qu'Aubry ait l'impression d'avoir obtenu quelque chose. Sinon, il bloquera tout.", "바로 그거예요. 그리고 오브리도 뭔가를 얻었다고 느껴야 해요. 그렇지 않으면 전부 막아 버릴 거예요."),
(MA, "Un délai de cent jours pour un plan complet, scénario de cession compris. Qu'en pensez-vous ?", "매각 시나리오를 포함한 완전한 계획을 100일 안에. 어떻게 생각하세요?"),
(CL, "Cent jours... Mon oncle trouvera que c'est long pour avoir des réponses, et Aubry, que c'est long pour vendre. C'est sans doute le bon chiffre.", "100일이라... 삼촌은 답을 듣기엔 길다고 하실 거고, 오브리는 팔기엔 길다고 하겠죠. 아마 딱 맞는 숫자일 거예요."),
(None, "Dans la cour, Frédéric Aubry termine un appel. Il raccroche en voyant passer Inès.", "마당에서 프레데리크 오브리가 통화를 마치고 있다. 이네스가 지나가는 걸 보자 전화를 끊는다."),
(AU, "Madame Marchetti, un mot. Votre présentation de ce matin était excellente. Brutale, mais excellente.", "마르케티 이사, 잠깐만요. 오늘 아침 발표 훌륭했습니다. 가차 없었지만, 훌륭했어요."),
(I, "Merci. Je préfère la brutalité aux mauvaises surprises.", "감사합니다. 저는 불쾌한 깜짝 소식보다는 가차 없는 쪽이 낫다고 봅니다."),
(AU, "Moi aussi. C'est pour cela que je vous ai recrutée. Ne laissez pas Saint-Étienne rendre vos chiffres sentimentaux. Ni vos jugements, d'ailleurs.", "저도요. 그래서 당신을 영입한 겁니다. 생테티엔이 당신의 숫자를 감상적으로 만들게 두지 마세요. 판단도 마찬가지고요."),
(I, "Mes jugements restent les miens, monsieur Aubry.", "제 판단은 제 것입니다, 오브리 씨."),
(AU, "Je n'en doute pas. Monsieur Kessler et vous formez une belle équipe, d'ailleurs. Très... soudée.", "의심하지 않습니다. 그나저나 케슬레르 대표와 당신은 좋은 팀이더군요. 아주... 끈끈하고요."),
(I, "Nous avons travaillé neuf mois ensemble chez Vasseur. C'est d'ailleurs pour cela que vous nous avez choisis, il me semble.", "바쇠르에서 아홉 달을 함께 일했으니까요. 바로 그래서 저희 둘을 고르신 걸로 아는데요."),

# ---------- 5. Décision : la séance de l'après-midi ----------
(None, "14 h. Reprise de la séance. Hubert Verdier semble plus calme ; sa sœur Geneviève, assise à sa gauche, lui a visiblement parlé.", "오후 2시. 회의 속개. 위베르 베르디에는 한결 차분해 보인다. 왼쪽에 앉은 누이 즈느비에브가 그와 이야기를 나눈 게 분명하다."),
(HU, "La séance reprend. Avant d'aborder le point six, monsieur Kessler souhaite faire une proposition. Je vous écoute.", "회의를 속개합니다. 6번 안건으로 넘어가기 전에 케슬레르 대표가 제안을 하고 싶어 합니다. 말씀하세요."),
(MA, "Merci, monsieur le président. Ce matin, deux visions se sont exprimées. Celle du fonds : céder Wrocław et réduire les coûts à Saint-Étienne. Celle de la famille : ne toucher ni à l'un ni à l'autre. Je ne crois pas qu'aucune des deux soit la bonne aujourd'hui, parce que personne autour de cette table n'a encore les chiffres complets.",
     "감사합니다, 의장님. 오늘 오전 두 가지 시각이 나왔습니다. 펀드의 시각은 브로츠와프를 매각하고 생테티엔의 비용을 줄이자는 것, 가문의 시각은 둘 다 건드리지 말자는 것입니다. 저는 오늘 시점에서 둘 중 어느 쪽도 정답이라고 생각하지 않습니다. 이 자리의 누구도 아직 완전한 수치를 갖고 있지 않기 때문입니다."),
(AU, "Nous les avons, les chiffres. Trois ans de pertes, c'est un chiffre assez complet.", "수치는 있습니다. 3년 연속 적자, 그거면 꽤 완전한 수치죠."),
(MA, "C'est un résultat, monsieur Aubry, pas un diagnostic. Je propose que la direction générale présente au conseil, d'ici cent jours, un plan stratégique complet. Tous les scénarios y figureront, y compris la cession de Wrocław.",
     "그건 결과지 진단이 아닙니다, 오브리 씨. 경영진이 100일 안에 이사회에 완전한 전략 계획을 제출할 것을 제안합니다. 브로츠와프 매각을 포함해 모든 시나리오를 담겠습니다."),
(HU, "Y compris la cession ? Vous voulez dire que vous l'envisagez ?", "매각까지 포함해서요? 그걸 검토하겠다는 말입니까?"),
(MA, "Je dis que je n'exclus rien, monsieur le président. Si je vous promettais aujourd'hui que Saint-Étienne ne bougera pas, je vous mentirais. Et dans un an, vous m'en voudriez.",
     "아무것도 배제하지 않겠다는 말씀입니다, 의장님. 오늘 생테티엔은 그대로일 거라고 약속드린다면 그건 거짓말일 겁니다. 그리고 1년 뒤 의장님은 저를 원망하실 겁니다."),
(HU, "Hm. Au moins, vous ne me flattez pas.", "흠. 적어도 아첨은 안 하는군요."),
(MA, "Je n'en ai ni l'intention ni le talent, monsieur le président. Madame Marchetti, je vous en prie.", "그럴 생각도, 재주도 없습니다, 의장님. 마르케티 이사, 말씀하시죠."),
(I, "La direction financière prend trois engagements. Premièrement : un inventaire complet de nos engagements hors bilan, vérifié par les commissaires aux comptes, sous trente jours. Plus jamais de note trente et un.",
    "재무 부문은 세 가지를 약속드립니다. 첫째, 모든 부외 약정을 전수 조사해 30일 안에 회계감사인의 검증을 받겠습니다. 다시는 주석 31번 같은 일이 없을 것입니다."),
(I, "Deuxièmement : j'ouvre dès la semaine prochaine une négociation avec le crédit-bailleur polonais. Tant que la garantie n'aura pas été levée ou transférée, toute cession de Wrocław nous laisserait le risque sans l'usine.",
    "둘째, 다음 주부터 폴란드 리스사와 협상을 시작하겠습니다. 보증이 해제되거나 이전되지 않는 한, 브로츠와프를 어떻게 매각하든 우리에겐 공장 없이 위험만 남게 됩니다."),
(AU, "Je ne l'avais pas envisagé sous cet angle, mais... vous avez raison. Un acheteur s'en servirait pour faire baisser le prix.", "그런 각도로는 생각해 보지 못했지만... 당신 말이 맞습니다. 인수자는 그걸 빌미로 가격을 깎으려 하겠죠."),
(I, "Troisièmement : un tableau de trésorerie mensuel, transmis à chaque administrateur. Vous saurez ce que nous savons, au moment où nous le saurons.", "셋째, 매달 자금 현황표를 모든 이사께 보내 드리겠습니다. 저희가 아는 것을, 저희가 아는 그 시점에 여러분도 아시게 될 겁니다."),
(AU, "Cent jours, c'est long. Le fonds a des comptes à rendre à ses propres investisseurs.", "100일은 깁니다. 펀드도 자기 투자자들에게 보고할 의무가 있어요."),
(I, "Monsieur Aubry, vos investisseurs pourront recevoir le même tableau que vous, chaque mois. Ils verront que rien ne dort dans cette maison.", "오브리 씨, 귀사 투자자들도 매달 같은 현황표를 받아 보실 수 있습니다. 이 회사에서 잠자는 건 아무것도 없다는 걸 보시게 될 겁니다."),
(H, "Monsieur Aubry, si vous permettez : cent jours pour un plan, c'est court. Une cession décidée trop vite, avec soixante millions de garantie dans la nature, serait bien plus longue à réparer.",
    "오브리 씨, 실례지만 계획 하나에 100일은 짧은 겁니다. 6,000만 유로의 보증을 허공에 띄워 둔 채 서둘러 매각을 결정하면, 수습하는 데 훨씬 오래 걸릴 겁니다."),
(AU, "... Je ne m'opposerai pas au délai, à une condition : que le scénario de cession soit étudié sérieusement, avec une banque d'affaires, et non comme un épouvantail.",
     "...기한에 반대하지는 않겠습니다. 단, 조건이 있습니다. 매각 시나리오를 허수아비로 세워 두지 말고, 투자은행과 함께 진지하게 검토할 것."),
(MA, "Accepté. Il sera chiffré avec le même sérieux que les autres. Vous avez ma parole.", "받아들이겠습니다. 다른 시나리오와 똑같이 진지하게 수치화하겠습니다. 약속드립니다."),
(HU, "Et moi, monsieur Kessler ? Qu'est-ce que j'obtiens, dans tout ça ?", "그럼 나는요, 케슬레르 대표? 이 모든 것에서 내가 얻는 건 뭡니까?"),
(MA, "La vérité avant tout le monde, monsieur le président. Et l'assurance qu'aucune décision ne sera prise sur Saint-Étienne sans que je sois allé parler moi-même à ceux qui y travaillent.",
     "누구보다 먼저 진실을 아시게 됩니다, 의장님. 그리고 제가 직접 그곳에서 일하는 사람들과 이야기하기 전에는 생테티엔에 관한 어떤 결정도 내려지지 않을 것이라는 확약을 드립니다."),
(CL, "Mon oncle, c'est plus que ce que les directeurs précédents vous ont jamais offert.", "삼촌, 이건 전임 대표들이 지금까지 삼촌께 내놓았던 것보다 더 많은 거예요."),
(HU, "... Je n'aime pas ça. Mais je reconnais que c'est honnête. Madame Vasseur, vous qui êtes indépendante, qu'en pensez-vous ?", "...마음에 들진 않습니다. 하지만 정직하다는 건 인정하죠. 바쇠르 이사, 독립적인 입장에서 어떻게 생각하십니까?"),
(H, "Je pense que si ce conseil se divise aujourd'hui, ni la famille ni le fonds n'y gagneront. Je propose d'y ajouter un comité stratégique de trois membres — un représentant de chaque actionnaire principal, et moi-même à la présidence — qui suivra le plan chaque mois.",
    "오늘 이 이사회가 갈라진다면 가문도 펀드도 얻는 게 없을 것이라고 봅니다. 여기에 3인 전략위원회를 추가할 것을 제안합니다. 주요 주주 측 대표 한 명씩, 그리고 위원장은 제가 맡아 매달 계획을 점검하는 위원회입니다."),
(AU, "Une administratrice qui a formé la direction générale, à la tête du comité... C'est original, comme indépendance.", "경영진을 길러 낸 이사가 위원장이라... 독립성치고는 독특하군요."),
(H, "C'est précisément pour cela que je serai plus exigeante avec eux qu'avec quiconque, monsieur Aubry. Ils le savent.", "바로 그래서 저는 누구보다 그들에게 엄격할 겁니다, 오브리 씨. 그들도 알고 있어요."),
(I, "Nous le savons. Malheureusement.", "알고 있습니다. 불행히도요."),
(HU, "Bien. Je mets aux voix la résolution suivante : la direction générale présentera un plan stratégique complet d'ici cent jours, soit au plus tard début janvier ; un comité stratégique est créé sous la présidence de madame Vasseur. Qui est pour ?",
     "좋습니다. 다음 결의안을 표결에 부치겠습니다. 경영진은 100일 안에, 늦어도 1월 초까지 완전한 전략 계획을 제출한다. 바쇠르 이사를 위원장으로 하는 전략위원회를 설치한다. 찬성하시는 분?"),
(None, "Six mains se lèvent, dont celle d'Hubert, après une seconde d'hésitation.", "여섯 명이 손을 든다. 잠시 망설이던 위베르의 손도 그중 하나다."),
(HU, "Six voix pour. Qui s'abstient ? ... Ma sœur. Une abstention. La résolution est adoptée. Le point six est renvoyé au plan des cent jours. Des questions diverses ? Aucune. Il est dix-sept heures dix : la séance est levée.",
     "찬성 여섯. 기권하시는 분? ...누이로군요. 기권 하나. 결의안은 가결됐습니다. 6번 안건은 100일 계획으로 넘깁니다. 기타 사항 있으십니까? 없군요. 오후 5시 10분, 회의를 마치겠습니다."),
(HU, "Monsieur Kessler, madame Marchetti... Ne me décevez pas. Je n'ai plus l'âge des mauvaises surprises.", "케슬레르 대표, 마르케티 이사... 날 실망시키지 마세요. 이제 불쾌한 깜짝 소식을 견딜 나이는 지났습니다."),
(MA, "Nous ferons tout pour, monsieur le président.", "최선을 다하겠습니다, 의장님."),
(I, "Et si nous devions vous décevoir, vous seriez le premier informé. C'est une promesse.", "그리고 만약 실망시켜 드리게 된다면, 의장님이 가장 먼저 아시게 될 겁니다. 약속드립니다."),

# ---------- 6. Le soir : les règles ----------
(None, "17 h 30. Le couloir se vide. Hélène retient Inès et Mathieu et ferme la porte d'un petit bureau.", "오후 5시 30분. 복도가 비어 간다. 엘렌이 이네스와 마티외를 붙잡아 작은 사무실 문을 닫는다."),
(H, "Félicitations. Pour un premier conseil, vous vous en êtes bien sortis. Hubert vous déteste un peu moins qu'à neuf heures, et Aubry vous respecte un peu plus.", "축하해. 첫 이사회치고는 잘 해냈어. 위베르는 아침 9시보다 너희를 조금 덜 싫어하고, 오브리는 조금 더 존중하게 됐어."),
(MA, "Merci, Hélène. Sans ta suspension de séance, on ne s'en serait pas tirés.", "고마워요, 엘렌. 엘렌이 정회를 제안하지 않았으면 못 빠져나왔을 거예요."),
(H, "Une dernière chose. Je ne sais rien, et je ne veux rien savoir. Mais soyez prudents.", "마지막으로 하나. 난 아무것도 몰라. 그리고 아무것도 알고 싶지 않아. 하지만 조심해."),
(I, "Hélène, je ne vois pas de quoi tu...", "엘렌, 무슨 말인지 모르겠는데..."),
(H, "Inès. Ce matin, Mathieu avait une cravate parfaitement nouée. En neuf mois chez moi, je ne l'ai jamais vu réussir un nœud. Et je ne suis pas la seule à l'avoir remarqué. Dans un conseil, chacun cherche la faiblesse de l'autre. Ne leur en offrez pas.",
    "이네스. 오늘 아침 마티외 넥타이가 완벽하게 매여 있더라. 우리 회사에서 아홉 달 동안 저 사람이 매듭 하나 제대로 매는 걸 본 적이 없어. 그리고 그걸 눈치챈 사람이 나만은 아니야. 이사회에선 다들 상대의 약점을 찾아. 그들에게 약점을 내주지 마."),
(None, "Elle prend son manteau et sort sans attendre de réponse.", "그녀는 대답을 기다리지 않고 외투를 챙겨 나간다."),
(MA, "Elle sait.", "알고 있어."),
(I, "Elle a toujours su. Depuis Nice, probablement. Ou depuis le toit.", "처음부터 알았어. 아마 니스 때부터. 아니면 옥상 때부터."),
(None, "21 h. L'appartement de Mathieu, près de l'hôtel de ville. Inès est venue à pied, par un détour. Sur la table, deux assiettes de pâtes.", "밤 9시. 시청 근처 마티외의 아파트. 이네스는 일부러 돌아서 걸어왔다. 식탁 위에 파스타 두 접시."),
(I, "Je me suis sentie ridicule, à faire un détour de dix minutes pour venir dîner chez toi.", "너희 집에 저녁 먹으러 오면서 10분이나 돌아오다니, 내가 우습게 느껴졌어."),
(MA, "Ridicule, mais prudente. Comme l'a demandé Hélène.", "우스워도 신중한 거지. 엘렌이 부탁한 대로."),
(I, "Alors fixons les règles. Au bureau : vous, « madame Marchetti », « monsieur Kessler ». Jamais de café à deux. On arrive et on repart séparément.", "그럼 규칙을 정하자. 회사에선 vous, '마르케티 이사님', '케슬레르 대표님'. 단둘이 커피는 절대 금지. 출근도 퇴근도 따로."),
(MA, "Et en ville, on ne se tient pas la main. Ni place Jean-Jaurès, ni le samedi au marché.", "그리고 시내에선 손 안 잡기. 장조레스 광장에서도, 토요일 장터에서도."),
(I, "Et si un jour ça se sait, ce sera nous qui le dirons. Pas quelqu'un d'autre. Promis ?", "그리고 언젠가 알려지게 되면, 우리가 직접 말하는 거야. 다른 누가 아니라. 약속해?"),
(MA, "Promis. Tu sais ce qui m'a le plus coûté, aujourd'hui ? Dire « madame Marchetti » quand tu as cloué le bec à Aubry avec sa note trente et un. J'avais envie d'applaudir.",
     "약속해. 오늘 제일 힘들었던 게 뭔지 알아? 네가 주석 31번으로 오브리 입을 막아 버렸을 때 '마르케티 이사님'이라고 불러야 했던 거. 박수 치고 싶었어."),
(I, "Tu as bien fait de te retenir. Et toi, quand tu as dit à Hubert « je vous mentirais »... j'étais fière de toi, Strasbourg.", "참길 잘했어. 그리고 네가 위베르한테 '거짓말이 될 겁니다'라고 했을 때... 네가 자랑스러웠어, 스트라스부르."),
(MA, "Passe-moi le marqueur vert. Quel est le vrai problème ?", "초록 마커 좀 줘. 진짜 문제는 무엇인가?"),
(I, "Que la famille a peur de perdre son nom, et le fonds, son argent. Qui décide ? Sept personnes autour d'une table, qui ne se font pas confiance.", "가문은 이름을 잃을까 봐, 펀드는 돈을 잃을까 봐 두려워한다는 것. 누가 결정하는가? 서로 믿지 않는 일곱 사람이 한 테이블에서."),
(MA, "Et nous deux au milieu, obligés de nous cacher. ... Que fait-on lundi ?", "그리고 그 한가운데에서 숨어 지내야 하는 우리 둘. ...월요일엔 뭘 하지?"),
(I, "Lundi, les cent jours commencent. Toi, tu pars une semaine à Roanne voir l'usine. Moi, j'appelle les Polonais.", "월요일엔 100일이 시작돼. 넌 일주일 동안 로안 공장에 가고. 난 폴란드 사람들한테 전화하고."),
(MA, "Une semaine à Roanne... sans toi.", "로안에서 일주일... 너 없이."),
(I, "On s'appellera le soir, en vidéo. Et tu mettras une cravate, que je voie si tu as fait des progrès.", "저녁마다 영상통화하자. 그리고 넥타이 매고 있어. 실력이 늘었는지 보게."),
]

VOCAB = [
("B2", "l'ordre du jour", "(회의의) 안건, 의사일정", "inscrire un point à l'ordre du jour = 안건에 올리다. L'ordre du jour comporte cinq points."),
("B2", "le quorum (est atteint)", "의사정족수(가 충족되다)", "프랑스 주식회사(SA) 이사회는 이사 과반 출석이 정족수. Le quorum n'est pas atteint = 정족수 미달."),
("B2", "le procès-verbal (PV)", "의사록", "tenir / approuver / signer le procès-verbal. 구어로는 « le PV ». 교통 위반 딱지도 PV라고 한다."),
("C1", "coopter / la cooptation", "(결원 이사를) 선임하다 / 이사회 선임", "이사회가 공석을 직접 채우고 다음 주주총회에서 추인(ratification)받는 절차."),
("B2", "un(e) administrateur(-trice) / un siège vacant", "이사 / 공석", "au siège laissé vacant = 비어 있던 자리에. pourvoir un siège = 자리를 채우다."),
("C1", "les engagements hors bilan", "부외 약정(대차대조표 밖의 의무)", "보증·리스·담보 등 재무제표 본문엔 없고 주석(annexe)에만 나오는 의무."),
("C1", "le crédit-bail", "리스(금융 리스)", "설비·건물을 사지 않고 리스 회사에서 빌려 쓰다가 만기에 살 수 있는 금융 기법. prendre en crédit-bail. 영어 leasing."),
("B2", "se porter garant(e) de qc", "~을 보증하다, ~의 보증인이 되다", "La société s'est portée garante de tous les loyers. 일상에서 집을 빌릴 때 부모가 garant가 되기도 한다."),
("B2", "la maison mère / une filiale", "모회사 / 자회사", "C'est la maison mère qui paie. filiale à 100 % = 완전 자회사."),
("B2", "céder (un actif) / une cession", "(자산을) 매각하다, 양도하다 / 매각", "vendre보다 법률·재무적인 말. la cession de Wrocław. ↔ une acquisition."),
("B2", "une suspension de séance", "정회", "La séance est suspendue / reprend / est levée = 정회 / 속개 / 폐회."),
("B2", "mettre aux voix / s'abstenir", "표결에 부치다 / 기권하다", "Qui est pour ? Qui est contre ? Qui s'abstient ? = 의결 3단계 질문. 명사 une abstention."),
("B2", "renvoyer (un point) à", "(안건을) ~로 넘기다, 미루다", "Le point six est renvoyé au plan des cent jours. 법원에서 사건을 이송할 때도 쓴다."),
("B2", "la feuille de route", "로드맵, 실행 계획", "직역 '도로 일지'. 정치·경영에서 단계별 계획을 가리킨다."),
("C1", "ne pas broncher", "눈 하나 깜짝하지 않다, 꿈쩍도 않다", "Il n'a même pas bronché. 주로 부정문으로 쓴다. sans broncher = 군말 없이."),
("C1", "un épouvantail", "허수아비, 겁주기용 핑계", "원래 '새 쫓는 허수아비'. 진지하게 검토하지 않고 겁만 주려고 세우는 안을 비유한다."),
("B2", "le commissaire aux comptes", "(법정) 회계감사인", "프랑스 법정 감사인. CAC로 줄여 쓴다. 일정 규모 이상 기업은 선임 의무."),
("B2", "laisser une porte de sortie (à qn)", "(누구에게) 출구를 남겨 주다", "협상에서 상대가 체면을 지키며 물러설 길을 열어 주는 것."),
("C1", "se renier", "자기 자신(의 신념)을 부정하다", "voter sans se renier = 자기 소신을 저버리지 않고 찬성하다. renier qn = ~와 의절하다."),
("C1", "être l'otage de qn", "~의 인질이 되다, ~에게 발목 잡히다", "Si nous promettons quelque chose aujourd'hui, nous serons l'otage de quelqu'un demain."),
("B2", "aller droit au but", "곧장 본론으로 들어가다", "Va droit au but. 반대는 tourner autour du pot(빙빙 돌려 말하다)."),
("B2", "On aura tout vu !", "별꼴을 다 보네!", "어이없는 일을 보고 하는 감탄. 전미래로 '이제 볼 건 다 봤다'는 뉘앙스."),
("B1", "nouer une cravate / un nœud", "넥타이를 매다 / 매듭", "faire son nœud de cravate. Ta cravate est bien nouée."),
("B2", "clouer le bec à qn", "~의 입을 다물게 하다, 말문을 막다", "구어. bec = 부리. Elle lui a cloué le bec avec un seul chiffre."),
("B2", "baisser d'un ton", "목소리(어조)를 낮추다", "Baissez d'un ton ! = 좀 조용히 해! 비유적으로 '흥분을 가라앉히다'."),
]

GRAM = [
("B2", "회의 진행의 격식 표현",
 "개회: « La séance est ouverte. » « Le quorum est donc atteint. » 안건: « L'ordre du jour comporte cinq points. » « Je demande qu'on inscrive un point supplémentaire. » 발언권: « Vous avez la parole. » « Si vous me permettez... » « puis-je proposer une suspension de séance ? » 의결: « Je mets aux voix la résolution suivante. » « Qui est pour ? Qui s'abstient ? » « La résolution est adoptée. » 폐회: « La séance est levée. » 의장은 비인칭·수동 표현(est approuvé, est renvoyé)을 즐겨 써서 개인감정을 지운다."),
("B2", "souhaiter que / vouloir que / préférer que + 접속법",
 "« je souhaite que vous l'appreniez de notre bouche » « Je ne veux pas que ce soit toi qui annonces les soixante millions. » « je préfère que ce soit sur la CFO » « je veux que la garantie soit réglée avant » 바람·의지·선호 동사 뒤 que절은 접속법이다. 주어가 같으면 부정사로: Je souhaite parler(내가 말하고 싶다) vs Je souhaite que vous parliez(당신이 말하길 바란다). ce soit toi qui annonces처럼 강조 구문 안에서도 동사는 강조된 주어(toi)에 맞춘다."),
("B2", "il faut que + 접속법과 de façon que",
 "« Il faudrait que la foncière accepte de transférer la garantie. » « il faut qu'elle soit présentée de façon que mon oncle puisse la voter » « il faut qu'Aubry ait l'impression d'avoir obtenu quelque chose » il faut que(현재)·il faudrait que(조건법, 완곡)는 모두 접속법을 요구한다. 목적·방식의 de façon que / de manière que도 결과를 '의도'할 때는 접속법(puisse)이다. avoir → ait, être → soit, pouvoir → puisse의 불규칙형을 익혀 두자."),
("B2", "조건의 접속사: à condition que / à moins que (ne) / sans que",
 "« à condition que l'acheteur soit plus solide que nous » « à moins que le crédit-bailleur polonais n'accepte de nous libérer, on resterait garants » « sans que je sois allé parler moi-même à ceux qui y travaillent » 모두 접속법을 쓴다. à moins que 뒤의 ne는 부정이 아닌 허사 ne(ne explétif)로, 격식체에서 쓰고 회화에선 생략 가능하다. sans que + 접속법 과거(sois allé)는 '먼저 ~하지 않은 채로'라는 선후 관계를 나타낸다. 같은 구조: « avant qu'elle ne devienne un vrai problème »."),
("B2", "조건법 과거: 하지 않은 일과 비난",
 "« Mon père ne l'aurait jamais fait. » « la plupart des administrateurs auraient signé ce procès-verbal » « Sans ta suspension de séance, on ne s'en serait pas tirés. » 조건법 과거(avoir/être 조건법 + 과거분사)는 과거에 일어나지 않은 가정을 말한다. sans + 명사가 si 절(si tu n'avais pas proposé...)을 대신할 수 있다. 비난은 부정사 과거로도 표현한다: « pourquoi ne pas l'avoir dit ? »(왜 말하지 않았나요?)."),
("B2", "si + 반과거 → 조건법 vs si + 현재 → 미래",
 "« Si je vous promettais aujourd'hui que Saint-Étienne ne bougera pas, je vous mentirais. Et dans un an, vous m'en voudriez. » (일부러 하지 않을 가정 → 반과거 + 조건법) / « Si nous promettons quelque chose aujourd'hui, nous serons l'otage de quelqu'un demain. » (실제로 있을 수 있는 경우 → 현재 + 미래) 같은 '약속'이라도 화자가 그 가능성을 얼마나 현실적으로 보는지에 따라 시제가 달라진다. en vouloir à qn = ~를 원망하다."),
("B2", "양보와 부분 인정: concéder, ne pas dire que, mais",
 "« Je vous concède que ce n'est pas glorieux. Mais restons dans le présent. » « Je n'ai pas dit que j'étais pour. J'ai dit que le calcul se défend. » « Je n'aime pas ça. Mais je reconnais que c'est honnête. » « Je soutiendrai une réforme, même douloureuse. » « Pas forcément. » 상대 논거 일부를 인정(concéder, reconnaître)한 뒤 mais로 자기 주장을 이어 가는 것이 격식 있는 반박의 기본 틀이다. même + 형용사는 bien qu'elle soit douloureuse를 짧게 줄인 표현이다."),
("B1", "호칭과 vous/tu: 직함 + 성, 그리고 사적인 tu",
 "공적인 자리: « Monsieur le président », « madame la directrice financière », « Merci, monsieur Kessler. » « madame Marchetti » 직함 호칭에는 정관사(le président)를 쓰고, 성 앞의 monsieur/madame은 문장 중간에서 소문자로 쓴다. 이 화의 두 사람은 비서 앞에서 « Monsieur Kessler, vous disiez... ? »처럼 일부러 vous를 쓰고, 둘만 남으면 « Tu crois qu'elle... ? »로 돌아간다. 같은 사람에게도 '누가 듣고 있는가'에 따라 말투가 바뀌는 것이 프랑스 직장 언어의 특징이다."),
]

CULTURE = [
("프랑스 주식회사(SA)의 이사회",
 "프랑스 주식회사(société anonyme)의 이사회(conseil d'administration)는 3명 이상 18명 이하의 이사로 구성되며, 이사 과반이 출석해야 의결할 수 있다(quorum). 결의는 출석 이사 과반수로 하고, 정관에 달리 정하지 않으면 가부동수일 때 의장이 결정권을 가진다. 많은 기업이 이사회 의장(président du conseil)과 대표이사(directeur général)를 분리한다. 사임 등으로 이사 자리가 비면 이사회가 새 이사를 임시로 선임(cooptation)하고, 다음 주주총회에서 추인을 받는다. 회의 내용은 의사록(procès-verbal)으로 남기고 의장과 이사 한 명이 서명한다."),
("부외 약정과 세일 앤드 리스백",
 "프랑스 일반회계기준(PCG)을 따르는 비상장 기업은 리스 계약을 대차대조표에 부채로 올리지 않고, 보증·리스 등 '부외 약정(engagements hors bilan)'을 재무제표 주석(annexe)에 기재한다. 상장 그룹이 적용하는 국제회계기준(IFRS 16)은 2019년부터 대부분의 리스를 부채로 인식하게 한 것과 대조적이다. 세일 앤드 리스백(cession-bail)은 공장이나 사옥을 팔아 현금을 마련한 뒤 다시 빌려 쓰는 방식으로, 단기 유동성에는 도움이 되지만 장기 임대료 부담과 보증 의무를 남긴다. 또한 프랑스 상법상 주식회사가 제3자를 위해 보증(cautions, avals et garanties)을 제공하려면 이사회의 승인을 받아야 한다."),
("살롱 데 자르 메나제와 프랑스의 압력솥",
 "'가정용품 박람회(Salon des arts ménagers)'는 1923년에 시작해 1980년대 초까지 파리에서 열린 대규모 전시회로, 냉장고·세탁기·압력솥 같은 신제품이 '현대적인 가정'의 상징으로 소개되던 무대였다. 1950~60년대 프랑스에서 압력솥은 빠르고 경제적인 요리 도구로 폭발적으로 보급되었고, 이 시기 한 제조사의 제품 이름이었던 cocotte-minute는 오늘날 압력솥을 뜻하는 일반 명사처럼 쓰인다. 공식적인 일반 명칭은 autocuiseur이다. 이 화의 가상 상품 « La Stéphanoise »(1962년)는 이런 시대 분위기를 배경으로 한다."),
]
