# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, S, MR = "Inès", "Mathieu", "Sofia", "Martine"
DE, PO, LT, HV, AB = "Delmas", "Ponsard", "Ludovic", "Hubert", "Aurélie"

META = {
    "part": 2, "ep": 18,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Les cent premiers jours",
    "title_ko": "첫 100일",
    "place": "생테티엔 자쿠아르 지구 이네스 아파트 · 로안역 근처 호텔(영상통화) · Verdier Industries 생테티엔 본사 · 로안 공장 · 필라 산 크레 드 라 페르드리 / 10월 중순~11월 초 (100일 계획 12~31일째)",
    "chars": "이네스(CFO), 마티외(CEO), 소피아(바쇠르 애널리스트, 영상통화), 마르틴 로슈(CEO 비서), 레지스 델마스(영업이사), 디디에 퐁사르(로안 공장장), 뤼도비크 테시에(로안 정비 기술자), 위베르 베르디에(이사회 의장, 전화), 오렐리 베송(대형 거래처 책임자 → 영업이사)",
    "work": "100일 계획 수립 — 임원 24명 인터뷰, 우선순위 세 가지(현금·제품·사람), 늘 부풀려진 영업 예측과 2위 고객 Domélia의 3,800만 유로 품목 철수 은폐, 생산성은 높지만 설비가 낡은 로안 공장, 영업이사 해임과 내부 승진",
    "life": "주말 없는 연애와 밤 11시의 영상통화, 피가로의 키보드 사건, 3주 만에 맞은 일요일의 필라 산 산책",
    "focus": "계획·우선순위 표현, 전미래(futur antérieur), 조건법 과거(비난·후회), 양보(avoir beau, quand bien même, ce n'est pas parce que), 접속법, 인사·해고 어휘, 회의 중 vous / 둘만의 tu",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제19화 Trésorerie à sec — 새벽 5시의 현금흐름표, 6주 뒤 바닥나는 현금, 은행과의 대출 약정 협상, 그리고 아르칸 쪽에서 나타난 낯익은 얼굴.",
}

D = [
# ---------- 1. Ouverture : l'appel vidéo ----------
(None, "Un mardi de la mi-octobre, 22 h 40. Jour 12 des cent jours. Inès, en pyjama dans son appartement du quartier Jacquard, à Saint-Étienne, un bol de céréales à la main. À l'écran, Mathieu, dans une chambre d'hôtel près de la gare de Roanne.",
       "10월 중순의 어느 화요일, 밤 10시 40분. 100일 중 12일째. 이네스는 생테티엔 자쿠아르 지구의 아파트에서 잠옷 차림으로 시리얼 그릇을 들고 있다. 화면 속에는 로안역 근처 호텔 방의 마티외."),
(MA, "Tu m'entends ? L'image est figée... Ah, voilà. Tu manges des céréales à onze heures du soir, toi ?", "내 말 들려? 화면이 멈췄네... 아, 됐다. 밤 11시에 시리얼 먹는 거야?"),
(I, "C'est mon dîner. Et toi, c'est quoi, ce triangle en plastique à côté de ton ordinateur ?", "이게 내 저녁이야. 너는? 노트북 옆에 있는 그 플라스틱 삼각형은 뭐야?"),
(MA, "Un sandwich de la gare. Thon-mayonnaise, à consommer avant demain. La grande vie des directeurs généraux.", "역에서 산 샌드위치. 참치마요, 유통기한 내일까지. 대표이사의 화려한 삶이지."),
(I, "Tu as une tête de déterré. Tu as dormi combien d'heures depuis lundi ?", "너 몰골이 말이 아니야. 월요일부터 몇 시간 잤어?"),
(MA, "Je ne compte plus. Et toi, ces cernes, c'est un nouveau maquillage ?", "이제 안 세. 그러는 넌? 그 다크서클, 새로 한 화장이야?"),
(I, "Merci, ça fait toujours plaisir. Allez, raconte-moi ta journée à Roanne avant que je m'endorme sur mon clavier.", "고마워, 들을 때마다 기분 좋네. 자, 내가 키보드 위에서 잠들기 전에 로안에서 보낸 하루 얘기해 줘."),
(MA, "Ce matin, Ponsard, le directeur de l'usine, m'a présenté à l'atelier. Un ouvrier a lâché : « Encore un Parisien. » J'ai répondu : « Non, Strasbourgeois. »",
     "오늘 아침에 공장장 퐁사르가 날 작업장에 소개했어. 그런데 한 작업자가 툭 던지는 거야. '또 파리 사람이군.' 그래서 내가 '아뇨, 스트라스부르 사람입니다' 했지."),
(I, "Et qu'est-ce qu'il a dit ?", "그랬더니 뭐래?"),
(MA, "Il m'a regardé de haut en bas : « Ah, c'est pire. Il va nous mettre de la choucroute à la cantine. » Tout l'atelier a éclaté de rire.", "날 위아래로 훑어보더니 '아, 그게 더 나쁘네. 구내식당에 슈크루트 나오게 생겼어.' 작업장 전체가 빵 터졌어."),
(I, "Ha ! Je l'adore déjà, cet homme. Il faut le nommer au comité de direction.", "하! 벌써 그 사람이 좋아졌어. 경영위원회에 앉혀야겠다."),
(MA, "À ton tour. Fais-moi rire, j'en ai besoin.", "네 차례야. 나 좀 웃겨 줘. 웃을 일이 필요해."),
(I, "Figaro a marché sur mon clavier pendant que j'écrivais à Martine. Elle a reçu « ffffffffff » de la part de la directrice financière. Réponse, deux minutes plus tard : « Bien reçu, Madame. Je transmets. »",
    "마르틴한테 메일 쓰는 동안 피가로가 키보드 위를 걸어갔어. 마르틴은 재무 책임자한테서 'ffffffffff'를 받은 거지. 2분 뒤 답장. '잘 받았습니다, 이사님. 전달하겠습니다.'"),
(MA, "« Je transmets » ! À qui ? Martine est géniale. Trente ans de maison, plus rien ne l'étonne.", "'전달하겠습니다'래! 누구한테? 마르틴은 천재야. 30년을 근무했으니 이제 놀랄 일이 없는 거지."),
(I, "Bon, côté sérieux : Sofia nous appelle demain pour les données commerciales. Et Delmas a encore annulé son entretien. Deux fois en une semaine.", "자, 진지한 얘기. 소피아가 내일 영업 데이터 때문에 전화할 거야. 그리고 델마스가 또 면담을 취소했어. 일주일에 두 번이야."),
(MA, "Je m'en occupe demain. ... Inès, ça fait douze jours qu'on ne se voit qu'en réunion, à se dire « vous ». Un dimanche, bientôt, on aura une vraie journée à nous. C'est promis.",
     "내일 내가 처리할게. ...이네스, 열이틀째 회의에서만 보면서 서로 '당신'이라고 부르고 있잖아. 곧 일요일 하루는 온전히 우리 둘만의 날을 만들 거야. 약속해."),
(None, "Elle pose la main sur l'écran. Il fait de même. Figaro passe entre elle et la caméra, la queue en l'air.", "그녀가 화면에 손을 댄다. 그도 똑같이 한다. 피가로가 꼬리를 치켜든 채 그녀와 카메라 사이를 지나간다."),

# ---------- 2. Le siège : entretiens ----------
(None, "Mercredi, 9 h 30. Siège de Verdier Industries, à Saint-Étienne. Bureau du directeur général. Au mur, un calendrier sur lequel Martine Roche barre chaque jour au feutre rouge.",
       "수요일 오전 9시 30분. 생테티엔의 Verdier Industries 본사. 대표이사 집무실. 벽에는 마르틴 로슈가 하루하루 빨간 펜으로 지워 가는 달력이 걸려 있다."),
(MR, "Bonjour, Monsieur Kessler. Votre café, sans sucre. Et votre programme : il vous reste sept entretiens sur les vingt-quatre membres de l'encadrement supérieur.", "안녕하세요, 케슬레르 대표님. 설탕 없는 커피입니다. 그리고 일정이요. 고위 관리자 스물네 명 중 일곱 명의 면담이 남았습니다."),
(MA, "Merci, Martine. Qui est-ce qu'il me manque ?", "고마워요, 마르틴. 누가 남았죠?"),
(MR, "Surtout M. Delmas, le directeur commercial. Il a annulé deux fois. Il dit qu'il est chez les clients.", "무엇보다 영업이사 델마스 씨요. 두 번 취소했어요. 거래처에 나가 있다고 하더군요."),
(MA, "Il est vraiment chez les clients ?", "정말 거래처에 있는 건가요?"),
(MR, "D'après son agenda, oui. D'après sa voiture, qui n'a pas quitté le parking depuis lundi... je ne saurais pas vous dire.", "일정표로는 그렇습니다. 월요일부터 주차장을 떠나지 않은 그분 차로 보면... 글쎄요, 뭐라 말씀드리기 어렵네요."),
(MA, "Vous êtes redoutable, Martine. Vous le connaissez depuis longtemps ?", "무서운 분이시네요, 마르틴. 그분을 오래 아셨어요?"),
(MR, "Vingt-six ans. C'est M. Hubert qui l'a fait entrer. Pendant longtemps, on disait qu'il était son dauphin. Et puis M. Hubert a nommé quelqu'un d'autre à la direction générale, et M. Delmas ne l'a jamais digéré.",
     "26년이요. 위베르 회장님이 데려오신 분이에요. 오랫동안 다들 그분을 후계자로 봤죠. 그런데 회장님이 대표이사 자리에 다른 사람을 앉히셨고, 델마스 씨는 그걸 끝내 받아들이지 못했어요."),
(MA, "Je vois. Pouvez-vous le prévenir que je l'attends à onze heures ? Ce n'est pas une proposition.", "알겠습니다. 11시에 기다리겠다고 전해 주시겠어요? 제안이 아니라고요."),
(MR, "Ce sera fait. Ah, et Madame Marchetti vous demande cinq minutes. Elle est à côté, en visioconférence avec Paris.", "그렇게 하겠습니다. 아, 그리고 마르케티 이사님이 5분만 시간을 내 달라고 하십니다. 옆방에서 파리와 화상회의 중이세요."),
(None, "Bureau de la directrice financière. Sur l'écran, Sofia, depuis les locaux de Vasseur & Associés.", "재무 책임자 사무실. 화면에는 바쇠르 & 어소시에이츠 사무실에 있는 소피아."),
(S, "Bonjour, Monsieur le directeur général ! Pardon... bonjour, Mathieu. J'ai encore du mal avec vos nouveaux titres.", "안녕하세요, 대표이사님! 아, 죄송... 안녕하세요, 마티외. 두 분 새 직함이 아직 입에 안 붙네요."),
(MA, "Bonjour, Sofia. Comment va Paris ?", "안녕, 소피아. 파리는 어때?"),
(S, "Paris va bien, Vasseur va bien, et Hélène m'a demandé de vous rappeler que notre mission d'appui a été approuvée par votre conseil. Six semaines, à prix d'ami, mais tout est dans les règles.",
    "파리도 잘 있고 바쇠르도 잘 있어요. 그리고 엘렌이 우리 지원 미션이 두 분 회사 이사회 승인을 받았다는 걸 꼭 상기시켜 드리래요. 6주, 우정 가격이지만 전부 규정대로예요."),
(I, "Elle a raison d'insister. Hélène siège à notre conseil : un contrat avec son cabinet, c'est une convention réglementée. Elle a dû s'abstenir lors du vote, et les commissaires aux comptes en seront informés.",
    "엘렌이 강조할 만해. 엘렌은 우리 이사회 이사잖아. 그 사람 회사와 맺는 계약은 '규제 대상 거래'야. 엘렌은 표결에서 기권해야 했고, 회계감사인에게도 보고될 거야."),
(S, "Donc je suis une convention réglementée. C'est la chose la plus chic qu'on m'ait jamais dite.", "그러니까 제가 규제 대상 거래라는 거네요. 지금까지 들은 말 중에 제일 세련된 말이에요."),
(I, "Sofia, concentre-toi. Tu as reçu les extractions du système commercial ?", "소피아, 집중해. 영업 시스템에서 뽑은 데이터는 받았어?"),
(S, "Cinq ans de commandes, de factures et de prévisions de ventes, client par client. Il me faut quelques jours. Mais je vois déjà quelque chose de bizarre dans les prévisions.", "5년 치 주문, 송장, 판매 예측, 거래처별로요. 며칠 필요해요. 그런데 예측 쪽에서 벌써 뭔가 이상한 게 보여요."),
(MA, "Bizarre comment ?", "어떻게 이상한데?"),
(S, "Trop belles. Je vous en dirai plus vendredi. Et Inès... tu as l'air épuisée.", "너무 예뻐요. 금요일에 더 말씀드릴게요. 그리고 이네스... 엄청 지쳐 보여요."),
(I, "Merci, tout le monde me le dit aujourd'hui. À vendredi.", "고마워, 오늘 다들 그 말을 하네. 금요일에 봐."),
(None, "11 h. Régis Delmas, cinquante-sept ans, costume impeccable, entre et s'assoit sans attendre qu'on l'y invite.", "오전 11시. 57세의 레지스 델마스가 흠잡을 데 없는 정장 차림으로 들어와 권하기도 전에 자리에 앉는다."),
(DE, "Monsieur Kessler, Madame Marchetti. Désolé pour les reports, j'étais sur la route. Le commerce, ça ne se fait pas dans un bureau.", "케슬레르 대표님, 마르케티 이사님. 일정이 미뤄져서 죄송합니다. 출장 중이었어요. 영업은 사무실에서 하는 게 아니니까요."),
(MA, "Je comprends. Merci d'être venu. Je pose les mêmes questions à tous les directeurs. D'après vous, quel est le vrai problème de Verdier ?", "이해합니다. 와 주셔서 감사합니다. 모든 임원께 같은 질문을 드리고 있어요. 베르디에의 진짜 문제는 뭐라고 보십니까?"),
(DE, "La concurrence chinoise, et la grande distribution qui nous étrangle sur les prix. Le produit est bon, l'équipe commerciale aussi. Il faut simplement baisser les coûts à l'usine.",
     "중국과의 경쟁, 그리고 가격으로 우리 목을 죄는 대형 유통업체죠. 제품도 좋고 영업팀도 좋습니다. 공장 원가만 낮추면 됩니다."),
(I, "Pourtant, la part de marché de « La Stéphanoise » est passée de trente-quatre à vingt-six pour cent en cinq ans. Et les Chinois ne vendent presque pas d'autocuiseurs en France.",
    "그런데 '라 스테파누아즈'의 시장점유율은 5년 만에 34%에서 26%로 떨어졌습니다. 그리고 중국 업체들은 프랑스에서 압력솥을 거의 팔지 않고요."),
(DE, "Madame Marchetti, avec tout le respect que je vous dois, vous regardez des tableaux. Moi, je connais les acheteurs par leur prénom.", "마르케티 이사님, 실례지만 이사님은 표를 보시죠. 저는 바이어들 이름을 다 압니다."),
(I, "Justement. Vos prévisions pour le quatrième trimestre sont conformes au budget, alors que les ventes du troisième sont inférieures de huit pour cent. Sur quoi reposent-elles ?",
    "바로 그 점입니다. 3분기 매출이 예산보다 8% 낮은데, 4분기 예측은 예산과 똑같습니다. 무엇을 근거로 한 예측입니까?"),
(DE, "Sur l'expérience. Le quatrième trimestre, c'est Noël. Les gens offrent des cafetières et des blenders. Ça rattrape toujours.", "경험이죠. 4분기는 크리스마스예요. 사람들이 커피메이커랑 블렌더를 선물하죠. 늘 따라잡습니다."),
(MA, "Et nos principaux clients ? Domélia, par exemple : soixante-deux millions de chiffre d'affaires, notre deuxième client. Comment va la relation ?", "주요 거래처는요? 예를 들어 Domélia. 매출 6,200만 유로로 우리 2위 고객이죠. 관계는 어떻습니까?"),
(DE, "Excellente. J'ai déjeuné avec leur directeur des achats il y a un mois. Aucun souci de ce côté-là.", "아주 좋습니다. 한 달 전에 그쪽 구매이사와 점심을 했어요. 그쪽은 전혀 문제없습니다."),
(MA, "Très bien. Je vous demande une chose : d'ici mardi, un point écrit sur nos dix premiers clients. Volumes, risques, tout.", "좋습니다. 한 가지 부탁드리죠. 화요일까지 상위 10개 거래처에 대한 서면 보고를 주십시오. 물량, 위험 요소, 전부요."),
(DE, "Vous l'aurez. Mais je vous préviens, Monsieur Kessler : cette maison a vu passer beaucoup de directeurs généraux. Les commerciaux, eux, restent.", "받으실 겁니다. 하지만 미리 말씀드리죠, 케슬레르 대표님. 이 회사는 대표이사를 많이도 거쳐 왔습니다. 영업맨들은 남고요."),

# ---------- 3. Analyse : les trois priorités ----------
(None, "Vendredi, 19 h. Jour 15. Bureau de la directrice financière. Le siège s'est vidé. Sofia partage son écran depuis Paris ; Mathieu est assis sur le coin du bureau d'Inès.",
       "금요일 저녁 7시. 15일째. 재무 책임자 사무실. 본사는 텅 비었다. 소피아가 파리에서 화면을 공유하고, 마티외는 이네스 책상 모서리에 걸터앉아 있다."),
(S, "Bon. Premier graphique : les prévisions de M. Delmas comparées aux ventes réelles, trimestre par trimestre, sur trois ans.", "자. 첫 번째 그래프예요. 델마스 씨의 예측과 실제 매출을 3년 동안 분기별로 비교한 거예요."),
(MA, "La ligne rouge est toujours au-dessus de la bleue.", "빨간 선이 항상 파란 선 위에 있네."),
(S, "Douze trimestres sur douze. En moyenne, il surestime de onze pour cent. Et à chaque fois, la même explication : « Ça rattrapera à Noël. »", "열두 분기 중 열두 분기 전부요. 평균 11%를 과대 예측해요. 그리고 매번 같은 설명이죠. '크리스마스에 따라잡을 겁니다.'"),
(I, "Et l'usine produit sur la base de ces prévisions. Donc on fabrique trop, on stocke trop, et le cash dort dans les entrepôts. Voilà une partie de notre problème de stocks.", "그리고 공장은 그 예측을 바탕으로 생산하지. 그러니까 너무 많이 만들고, 너무 많이 쌓아 두고, 현금은 창고에서 잠자는 거야. 우리 재고 문제의 한 원인이 이거네."),
(S, "Deuxième graphique, le plus intéressant. Les commandes de Domélia pour le premier trimestre de l'année prochaine. Blenders et cafetières.", "두 번째 그래프가 제일 흥미로워요. 내년 1분기 Domélia의 주문이에요. 블렌더와 커피메이커."),
(MA, "Il n'y a rien. C'est un bug ?", "아무것도 없잖아. 오류야?"),
(S, "C'est ce que j'ai cru. Alors j'ai regardé leurs commandes informatisées : depuis juillet, Domélia a retiré toutes nos références de blenders et de cafetières à partir de janvier. Seuls les autocuiseurs restent.",
    "저도 그런 줄 알았어요. 그래서 전자 주문 내역을 봤죠. 7월부터 Domélia가 1월 이후 우리 블렌더와 커피메이커 품목을 전부 뺐어요. 압력솥만 남아요."),
(I, "Un déréférencement. Ça représente combien ?", "입점 철수네. 규모가 얼마야?"),
(S, "Trente-huit millions de chiffre d'affaires par an, sur les soixante-deux.", "6,200만 중에 연 매출 3,800만 유로요."),
(I, "Avec notre marge sur coûts variables, ça fait onze millions de marge en moins. Chaque année. Et il nous a dit « aucun souci » en nous regardant dans les yeux.", "우리 공헌이익률로 따지면 매년 1,100만 유로의 이익이 사라지는 거야. 그런데 그 사람은 우리 눈을 똑바로 보면서 '전혀 문제없다'고 했어."),
(MA, "Attends. Il ne le savait peut-être pas. Les systèmes, les acheteurs... ce n'est pas forcément lui.", "잠깐. 몰랐을 수도 있어. 시스템이나 바이어 쪽 일이고... 꼭 그 사람 탓은 아닐 수도 있잖아."),
(I, "Mathieu. Un directeur commercial qui ignore depuis trois mois que son deuxième client arrête deux gammes, c'est soit un incompétent, soit un menteur. Dans les deux cas, il doit partir.",
    "마티외. 2위 고객이 두 제품군을 끊는다는 걸 석 달 동안 모르는 영업이사라면, 무능하거나 거짓말쟁이야. 어느 쪽이든 나가야 해."),
(S, "Euh, je suis toujours là, hein. Je peux couper ma caméra, si vous voulez.", "어, 저 아직 여기 있어요. 원하시면 카메라 끌게요."),
(I, "Reste, Sofia. On a besoin de toi pour la suite.", "있어, 소피아. 다음 얘기에 네가 필요해."),
(MA, "Je ne dis pas qu'il doit rester. Je dis qu'on ne licencie pas quelqu'un qui a vingt-six ans de maison sur la base d'un graphique. Il faut des faits, et il faut l'entendre.",
     "남아야 한다는 게 아니야. 26년 근무한 사람을 그래프 하나로 해고하지는 않는다는 거지. 사실이 필요하고, 그 사람 말도 들어야 해."),
(I, "Tu aurais attendu combien de temps, toi ? Trois mois de plus, pendant que Roanne fabrique peut-être des blenders que personne n'achètera ?", "넌 얼마나 기다렸을 건데? 로안 공장에서 아무도 안 살 블렌더를 만들고 있을지도 모르는데, 석 달 더?"),
(MA, "Je n'attends pas. Lundi, je retourne à Roanne avec toi : si l'usine a reçu des consignes, quelqu'un le saura. Et si c'est confirmé, je m'en charge moi-même.", "기다리는 게 아니야. 월요일에 너랑 로안에 다시 가자. 공장이 지시를 받았다면 누군가는 알 거야. 그리고 확인되면 내가 직접 처리할게."),
(I, "Tu t'en charges, vraiment ? Toi qui détestes les conflits ?", "네가 직접 한다고? 갈등이라면 질색하는 네가?"),
(MA, "Justement. C'est mon travail maintenant, pas le tien. Et ce n'est pas parce que je déteste les conflits que je vais les fuir.", "그러니까 하는 거야. 이제 그건 내 일이지 네 일이 아니야. 그리고 갈등을 싫어한다고 해서 도망칠 생각은 없어."),
(S, "Bon... pendant que vous faites la paix, je vous rappelle la question de départ : votre plan des cent jours. Le conseil attend trois priorités, pas trente.", "저기... 두 분이 화해하시는 동안 원래 질문을 다시 말씀드릴게요. 100일 계획이요. 이사회는 우선순위 서른 개가 아니라 세 개를 기다려요."),
(MA, "Elle a raison. Passe-moi le marqueur vert.", "소피아 말이 맞아. 초록 마커 좀 줘."),
(None, "Mathieu écrit trois mots sur le tableau blanc : TRÉSORERIE — PRODUIT — GENS.", "마티외가 화이트보드에 세 단어를 쓴다. 현금 — 제품 — 사람."),
(MA, "Première priorité : la trésorerie. Sans cash, il n'y a ni deuxième ni troisième priorité.", "첫 번째 우선순위는 현금이야. 현금이 없으면 두 번째도 세 번째도 없어."),
(I, "Enfin une phrase de PDG que je signe des deux mains. D'ici cent jours, nous aurons réduit les stocks de vingt millions et renégocié nos délais de paiement.", "드디어 내가 두 손 들고 찬성할 대표이사다운 문장이 나왔네. 100일 안에 재고를 2,000만 유로 줄이고 결제 조건을 재협상해 놓을 거야."),
(MA, "Deuxième : le produit. Nous avons mille deux cents références au catalogue, et vingt pour cent d'entre elles font quatre-vingt-cinq pour cent des ventes. D'ici la fin du plan, nous aurons décidé quelles gammes nous gardons.",
     "두 번째는 제품. 카탈로그에 품목이 1,200개인데, 그중 20%가 매출의 85%를 차지해. 계획 기간이 끝날 때까지 어떤 제품군을 남길지 결정해 둘 거야."),
(I, "Et la troisième ?", "그럼 세 번째는?"),
(MA, "Les gens. Une équipe de direction en qui on a confiance, et des usines qui savent pourquoi on fait tout ça. Quand on aura nommé les bonnes personnes aux bons postes, le reste ira plus vite.",
     "사람. 믿을 수 있는 경영진, 그리고 우리가 왜 이 모든 걸 하는지 아는 공장들. 맞는 사람을 맞는 자리에 앉히고 나면 나머지는 더 빨리 진행될 거야."),
(S, "Trésorerie, produit, gens. Je vous mets ça dans une diapo pour le conseil. Et j'écris « futur antérieur » dans le titre, pour faire plaisir à Hélène.", "현금, 제품, 사람. 이사회용 슬라이드에 넣어 드릴게요. 엘렌 좋아하시라고 제목에 '전미래'라고도 쓸게요."),
(I, "Merci, Sofia. Va te reposer, il est presque vingt heures un vendredi.", "고마워, 소피아. 가서 쉬어. 금요일 저녁 8시가 다 됐어."),
(S, "Vous aussi. Et pour info : vous vous disputez exactement comme à Vasseur. Il y a des choses qui ne changent pas. Bisous !", "두 분도요. 그리고 참고로, 두 분 싸우는 거 바쇠르 때랑 똑같아요. 안 변하는 것도 있네요. 안녕!"),
(None, "Sofia se déconnecte. On frappe. Martine passe la tête par la porte, son manteau sur le bras.", "소피아가 연결을 끊는다. 노크 소리. 마르틴이 외투를 팔에 걸친 채 문틈으로 고개를 내민다."),
(MR, "Je m'en vais, Madame Marchetti, Monsieur Kessler. N'oubliez pas d'éteindre la lumière. Et ne restez pas trop tard... tous les deux.", "저 퇴근합니다, 마르케티 이사님, 케슬레르 대표님. 불 끄는 것 잊지 마시고요. 너무 늦게까지 계시지 마세요... 두 분 다."),

# ---------- 4. Terrain : l'usine de Roanne ----------
(None, "Lundi, 7 h 30. Jour 18. Usine Verdier de Roanne : neuf cents salariés, des blenders, des robots de cuisine et des cafetières. Dans l'atelier d'emboutissage, le bruit des presses fait vibrer le sol.",
       "월요일 오전 7시 30분. 18일째. 베르디에 로안 공장. 직원 900명, 블렌더·푸드프로세서·커피메이커를 만든다. 프레스 작업장에서는 프레스 소리에 바닥이 울린다."),
(PO, "Bienvenue, Madame Marchetti. Monsieur Kessler, vous revenez déjà ? Vous allez finir par aimer Roanne.", "어서 오세요, 마르케티 이사님. 케슬레르 대표님, 벌써 또 오셨어요? 이러다 로안을 좋아하시겠네요."),
(MA, "C'est déjà fait, Monsieur Ponsard. Madame Marchetti voulait voir de ses propres yeux ce dont je lui ai parlé.", "벌써 좋아졌습니다, 퐁사르 공장장님. 마르케티 이사님이 제가 말씀드린 걸 직접 보고 싶어 하셔서요."),
(I, "On m'a dit que Roanne était l'usine la plus productive du groupe. C'est vrai ?", "로안이 그룹에서 생산성이 가장 높은 공장이라고 들었어요. 사실인가요?"),
(PO, "Les chiffres sont là. Notre taux de rendement synthétique est à quatre-vingt-un pour cent ; la moyenne du groupe tourne autour de soixante-cinq. Mes gars sont bons.", "숫자가 말해 줍니다. 저희 설비종합효율이 81%예요. 그룹 평균은 65% 안팎이고요. 우리 직원들이 잘하죠."),
(I, "Impressionnant. Et ces machines, elles ont quel âge ?", "인상적이네요. 그런데 이 기계들은 몇 년이나 됐어요?"),
(PO, "Vingt-sept ans en moyenne. Celle-ci, la presse numéro quatorze, date de 1986. Son fabricant a fait faillite en 2003.", "평균 27년이요. 이 14번 프레스는 1986년에 만든 거예요. 제조사는 2003년에 파산했고요."),
(MA, "Et quand elle tombe en panne, vous faites comment, sans pièces de rechange ?", "그럼 고장 나면 어떻게 하세요? 예비 부품도 없을 텐데."),
(PO, "On appelle Ludovic. Ludo ! Viens voir, la direction est là.", "뤼도비크를 부르죠. 뤼도! 이리 와 봐, 경영진 오셨어."),
(LT, "Bonjour. Ludovic Teyssier, maintenance, trente-quatre ans de maison. Ne vous inquiétez pas pour la quatorze : les pièces, je les fabrique moi-même, au tour, dans mon atelier.", "안녕하세요. 정비 담당 뤼도비크 테시에, 34년째 근무 중입니다. 14번은 걱정 마세요. 부품은 제 작업실에서 선반으로 직접 깎아 만듭니다."),
(I, "Vous fabriquez vous-même les pièces d'une presse de 1986 ?", "1986년식 프레스 부품을 직접 만드신다고요?"),
(LT, "Il faut bien. Les plans n'existent plus, alors je les ai dans la tête. Et dans un vieux cahier.", "그래야죠. 도면이 없어졌으니 제 머릿속에 있어요. 그리고 낡은 공책 한 권에요."),
(MA, "Combien êtes-vous à savoir faire ça ?", "그걸 할 줄 아는 분이 몇 명이나 되나요?"),
(LT, "Cinq, dans l'équipe. Mais trois partent à la retraite d'ici deux ans. Moi le premier, en avril.", "팀에 다섯 명이요. 그런데 셋이 2년 안에 은퇴해요. 제가 제일 먼저, 4월에요."),
(I, "Autrement dit, la productivité de Roanne repose sur cinq personnes et un cahier.", "그러니까 로안의 생산성은 다섯 사람과 공책 한 권에 달려 있는 거군요."),
(PO, "Vous résumez bien, Madame. On demande des investissements depuis dix ans. Il faudrait vingt-quatre millions sur trois ans pour moderniser les lignes. Chaque fois, on nous a répondu : « L'an prochain. »",
     "정확히 요약하셨습니다, 이사님. 10년째 투자를 요청하고 있어요. 라인을 현대화하려면 3년간 2,400만 유로가 필요합니다. 그때마다 돌아온 답은 '내년에'였죠."),
(I, "Vingt-quatre millions que nous n'avons pas aujourd'hui. Mais que nous perdrons de toute façon si les lignes s'arrêtent.", "지금 우리에겐 없는 2,400만 유로네요. 하지만 라인이 멈추면 어차피 잃게 될 돈이기도 하고요."),
(MA, "Monsieur Teyssier, d'ici avril, pourriez-vous former deux jeunes et faire numériser ce cahier ? Je veux que ce savoir reste dans l'usine quand vous en partirez.", "테시에 씨, 4월까지 젊은 직원 둘을 가르치고 그 공책을 디지털화해 주실 수 있을까요? 떠나신 뒤에도 그 노하우가 공장에 남았으면 합니다."),
(LT, "Ça, Monsieur le directeur, c'est la première fois qu'on me le demande. Avec plaisir.", "대표님, 그런 부탁은 처음 받아 봅니다. 기꺼이 하죠."),
(None, "Plus tard, dans le bureau vitré de Didier Ponsard, au-dessus de l'atelier.", "잠시 뒤, 작업장 위층에 있는 디디에 퐁사르의 유리 사무실."),
(MA, "Monsieur Ponsard, une question précise. Vos plannings de production de janvier, pour les blenders et les cafetières, ils ressemblent à quoi ?", "퐁사르 공장장님, 구체적으로 하나 여쭙겠습니다. 1월 블렌더와 커피메이커 생산 계획은 어떻게 되어 있습니까?"),
(PO, "En forte baisse. On a réduit les cadences prévues dès la mi-juillet. Domélia arrête ces deux gammes au 1er janvier, vous le savez bien.", "크게 줄었습니다. 7월 중순부터 계획 생산 속도를 낮췄어요. Domélia가 1월 1일부로 그 두 제품군을 끊잖아요. 잘 아시면서."),
(I, "Qui vous l'a dit ?", "누가 그렇게 말해 줬죠?"),
(PO, "Mme Besson, la responsable des grands comptes. Elle a écrit à M. Delmas le 12 juillet, avec moi en copie et la lettre de Domélia en pièce jointe. Tenez, je l'ai gardé.", "대형 거래처 책임자인 베송 씨요. 7월 12일에 델마스 씨에게 메일을 보냈는데, 저를 참조에 넣고 Domélia의 공문을 첨부했어요. 여기요, 보관해 뒀습니다."),
(MA, "Et qu'a répondu M. Delmas ?", "델마스 씨는 뭐라고 답했습니까?"),
(PO, "« Je gère. Pas de vagues avant l'arrivée de la nouvelle direction. » C'est écrit là, noir sur blanc. Moi, je pensais que vous étiez au courant.", "'내가 처리한다. 새 경영진 오기 전까지 일 만들지 말 것.' 여기 분명히 적혀 있어요. 저는 두 분이 알고 계신 줄 알았습니다."),
(MA, "Nous le sommes, maintenant. Merci, Monsieur Ponsard. Pouvez-vous me transférer ce mail ?", "이제 알게 됐습니다. 감사합니다, 퐁사르 공장장님. 그 메일을 저한테 전달해 주시겠어요?"),

# ---------- 5. Décision : le directeur commercial ----------
(None, "Mardi, 8 h 15. Jour 19. Bureau du directeur général. Inès entre et ferme la porte derrière elle.", "화요일 오전 8시 15분. 19일째. 대표이사 집무실. 이네스가 들어와 등 뒤로 문을 닫는다."),
(I, "Tu es sûr de vouloir le faire seul ? Je peux rester.", "정말 혼자 할 거야? 내가 있어도 돼."),
(MA, "Non. Si tu es là, il dira que c'est la directrice financière qui a sorti sa calculatrice. C'est ma décision ; il faut qu'il l'entende de ma bouche.", "아니. 네가 있으면 재무 책임자가 계산기 두드려서 한 일이라고 할 거야. 내 결정이니까 내 입으로 듣게 해야 해."),
(I, "Tu as relu la note de la DRH ? Convocation à un entretien préalable, dispense d'activité rémunérée, et pas un mot de trop.", "인사이사 메모 다시 읽었어? 사전 면담 소환, 유급 업무 면제, 그리고 쓸데없는 말은 한마디도 하지 말 것."),
(MA, "Trois fois. Je n'ai pas fermé l'œil de la nuit, mais je l'ai relue trois fois.", "세 번. 밤새 한숨도 못 잤지만 세 번 읽었어."),
(I, "Ça va aller. Tu as raison de le faire, et tu vas bien le faire.", "괜찮을 거야. 넌 옳은 일을 하는 거고, 잘 해낼 거야."),
(None, "8 h 30. Inès est repartie. Régis Delmas entre, un dossier sous le bras.", "8시 30분. 이네스는 돌아갔다. 레지스 델마스가 서류철을 옆구리에 끼고 들어온다."),
(DE, "Voici le point que vous m'avez demandé. Dix clients, tout est sous contrôle.", "요청하신 보고서입니다. 거래처 열 곳, 전부 관리되고 있습니다."),
(MA, "Merci. Je ne vois pas Domélia dans la colonne des risques.", "고맙습니다. 위험 항목에 Domélia가 안 보이는군요."),
(DE, "Parce qu'il n'y a pas de risque.", "위험이 없으니까요."),
(MA, "Monsieur Delmas, j'ai lu le mail de Mme Besson du 12 juillet, et la lettre de Domélia qui y était jointe. J'ai aussi lu votre réponse : « Pas de vagues avant l'arrivée de la nouvelle direction. »",
     "델마스 씨, 7월 12일 베송 씨의 메일과 거기 첨부된 Domélia의 공문을 읽었습니다. 당신의 답장도 읽었고요. '새 경영진 오기 전까지 일 만들지 말 것.'"),
(DE, "... Je comptais vous en parler. Je voulais d'abord renégocier avec eux. Si j'avais réussi, vous n'auriez jamais eu à vous en inquiéter.", "...말씀드리려고 했습니다. 먼저 그쪽과 재협상을 하고 싶었어요. 성공했다면 대표님은 그걸로 걱정하실 일이 아예 없었을 겁니다."),
(MA, "Vous auriez dû m'en informer le premier jour. Vous l'avez omis dans votre note de passation, et il y a six jours, vous m'avez dit en face que la relation était excellente.", "첫날 저한테 알렸어야 했습니다. 인수인계 메모에서도 빠뜨렸고, 엿새 전에는 제 앞에서 관계가 아주 좋다고 하셨죠."),
(DE, "Vous me faites un procès pour un mail ? Après vingt-six ans ?", "메일 하나로 저를 재판하시는 겁니까? 26년을 일했는데?"),
(MA, "Ce n'est pas un procès. Vous avez beau avoir vingt-six ans de maison, je ne peux pas travailler avec un directeur commercial qui me cache une perte de trente-huit millions. J'ai décidé de vous relever de vos fonctions.",
     "재판이 아닙니다. 26년을 근무하셨다 해도, 3,800만 유로의 손실을 저한테 숨기는 영업이사와는 일할 수 없습니다. 당신을 직무에서 해임하기로 결정했습니다."),
(DE, "Vous n'avez pas le droit. Hubert ne laissera jamais faire ça.", "그럴 권한 없으십니다. 위베르 회장님이 절대 가만두지 않을 거예요."),
(MA, "Le conseil m'a confié la direction générale, et la composition de mon équipe en fait partie. Vous recevrez aujourd'hui une convocation à un entretien préalable. D'ici là, vous êtes dispensé d'activité, et votre salaire est maintenu.",
     "이사회가 제게 회사 경영을 맡겼고, 제 팀을 꾸리는 것도 거기 포함됩니다. 오늘 사전 면담 소환장을 받으실 겁니다. 그때까지 업무에서 면제되고 급여는 그대로 지급됩니다."),
(DE, "Et si je refuse de partir ?", "제가 나가길 거부하면요?"),
(MA, "La procédure suivra son cours, dans le respect du droit et de vos années ici. Je préférerais que nous trouvions ensemble une sortie digne. Pour vous comme pour la maison.", "절차는 법과 당신이 이곳에서 보낸 세월을 존중하며 그대로 진행될 겁니다. 함께 품위 있는 퇴장 방법을 찾았으면 합니다. 당신을 위해서도, 회사를 위해서도요."),
(DE, "Une sortie digne... Vous verrez, Kessler. Vous ne tiendrez pas cent jours.", "품위 있는 퇴장이라... 두고 보세요, 케슬레르. 당신은 100일도 못 버틸 겁니다."),
(None, "Il sort sans refermer la porte. Dix minutes plus tard, Martine passe la tête : « M. Hubert Verdier, pour vous. Il n'a pas l'air content. »", "그는 문도 닫지 않고 나간다. 10분 뒤 마르틴이 고개를 내민다. '위베르 베르디에 회장님 전화입니다. 기분이 좋아 보이지 않으세요.'"),
(HV, "Kessler ? Qu'est-ce que c'est que cette histoire ? Régis est dans la maison depuis vingt-six ans, c'est moi qui l'ai recruté !", "케슬레르? 이게 다 무슨 일이오? 레지스는 26년이나 이 회사에 있었소. 내가 뽑은 사람이란 말이오!"),
(MA, "Je sais, Monsieur le président. Je vous ai envoyé ce matin le mail du 12 juillet. L'avez-vous lu ?", "압니다, 회장님. 오늘 아침 7월 12일자 메일을 보내 드렸습니다. 읽어 보셨습니까?"),
(HV, "... Je l'ai lu. Il aurait dû en parler, c'est vrai. Mais le renvoyer comme un malpropre...", "...읽었소. 그 사람이 말했어야 했던 건 맞아요. 하지만 그렇게 내쫓듯이 보내다니..."),
(MA, "Il ne part pas comme un malpropre. Il part avec ses droits, et avec mon respect pour ce qu'il a fait pendant vingt-six ans. Mais sans ma confiance.", "내쫓는 게 아닙니다. 그는 자기 권리와, 26년 동안 해 온 일에 대한 제 존중을 안고 떠납니다. 다만 제 신뢰는 없이요."),
(HV, "Quand bien même il aurait commis une faute, vous auriez pu m'en parler avant.", "설령 그가 잘못을 했다 해도, 먼저 나한테 얘기할 수는 있었잖소."),
(MA, "Sur ce point, vous avez raison, et la prochaine fois, je vous en parlerai avant d'agir. Mais la décision, elle, ne change pas. Elle relève de la direction générale.", "그 점은 회장님 말씀이 옳습니다. 다음에는 행동하기 전에 말씀드리겠습니다. 하지만 결정 자체는 바뀌지 않습니다. 그건 대표이사의 권한입니다."),
(HV, "... Mon père disait qu'un patron se reconnaît au premier homme qu'il renvoie. Nous verrons quel patron vous êtes. Au revoir, Kessler.", "...내 아버지는 사장이란 처음 내보내는 사람을 보면 알 수 있다고 하셨소. 당신이 어떤 사장인지 두고 봅시다. 끊겠소, 케슬레르."),
(None, "11 h. Aurélie Besson, quarante-deux ans, responsable des grands comptes, s'assoit en face de Mathieu et d'Inès. Elle serre son carnet contre elle.", "오전 11시. 42세의 대형 거래처 책임자 오렐리 베송이 마티외와 이네스 맞은편에 앉는다. 수첩을 꼭 끌어안고 있다."),
(AB, "Vous vouliez me voir ? Si c'est au sujet du mail de juillet, je sais que j'aurais dû alerter plus haut, mais...", "저를 찾으셨다고요? 7월 메일 때문이라면, 더 윗선에 알렸어야 했다는 건 알지만..."),
(I, "Madame Besson, vous avez été la seule à alerter. Vous avez vu le risque, vous l'avez chiffré, et vous avez prévenu l'usine. C'est exactement ce que nous attendons d'une directrice commerciale.", "베송 씨, 경고를 한 사람은 당신뿐이었어요. 위험을 봤고, 수치로 계산했고, 공장에 알렸죠. 그게 바로 우리가 영업이사에게 기대하는 일이에요."),
(AB, "D'une... directrice commerciale ?", "영업... 이사요?"),
(MA, "Madame Marchetti et moi en avons parlé. À compter d'aujourd'hui, vous êtes nommée directrice commerciale du groupe. Première mission : d'ici trente jours, vous aurez rencontré Domélia et vous nous aurez dit ce qu'on peut sauver.",
     "마르케티 이사와 제가 이야기를 나눴습니다. 오늘부로 당신을 그룹 영업이사로 임명합니다. 첫 임무는 30일 안에 Domélia를 만나고, 무엇을 살릴 수 있는지 저희에게 보고하는 겁니다."),
(AB, "J'accepte. Et j'ai déjà une piste : Domélia n'arrête pas nos blenders parce qu'ils sont mauvais, mais parce qu'on ne les a pas renouvelés depuis huit ans. Quand nous aurons un vrai nouveau produit, ils reviendront.",
     "수락하겠습니다. 그리고 벌써 실마리가 하나 있어요. Domélia가 우리 블렌더를 끊는 건 제품이 나빠서가 아니라 8년 동안 한 번도 새로 내놓지 않았기 때문이에요. 제대로 된 신제품이 나오면 다시 돌아올 겁니다."),

# ---------- 6. Dimanche : le mont Pilat ----------
(None, "Dimanche, 15 h. Jour 31, après trois semaines sans un seul week-end. Le crêt de la Perdrix, dans le massif du Pilat, à quarante minutes de Saint-Étienne. Le vent est froid, les hêtres sont roux. Personne à l'horizon.",
       "일요일 오후 3시. 31일째, 주말 하나 없이 보낸 3주 끝. 생테티엔에서 40분 거리, 필라 산지의 크레 드 라 페르드리. 바람은 차고 너도밤나무는 붉게 물들었다. 사방에 아무도 없다."),
(I, "Regarde, Mathieu ! Là-bas, tout au fond... ce sont les Alpes ?", "봐, 마티외! 저기 저 끝에... 저게 알프스야?"),
(MA, "Le mont Blanc, même. On ne le voit que par temps clair. On a de la chance.", "몽블랑이야. 날이 맑을 때만 보여. 우리 운이 좋네."),
(I, "Ça fait trois semaines que je ne vois que des tableurs et le parking du siège. J'avais oublié que le ciel existait.", "3주 동안 엑셀이랑 본사 주차장만 봤어. 하늘이 있다는 것도 잊고 있었어."),
(MA, "Ici, personne ne nous connaît. Je peux te prendre la main sans que Martine le note dans un registre.", "여기선 아무도 우릴 몰라. 마르틴이 장부에 적을 걱정 없이 네 손을 잡을 수 있어."),
(I, "Martine sait sûrement déjà tout. Elle a une tête à tout savoir.", "마르틴은 분명 이미 다 알 거야. 모든 걸 아는 얼굴이잖아."),
(None, "Il lui prend la main. Ils marchent entre les chirats, ces grands éboulis de granit couverts de mousse.", "그가 그녀의 손을 잡는다. 둘은 이끼 낀 화강암 바위들이 무너져 쌓인 '시라' 사이를 걷는다."),
(MA, "Mardi dernier, quand Delmas est sorti de mon bureau, j'ai eu les mains qui tremblaient pendant une heure. Je ne te l'ai pas dit.", "지난번 화요일에 델마스가 내 방에서 나간 뒤로 한 시간 동안 손이 떨렸어. 너한테 말 안 했지만."),
(I, "Je l'ai vu. Tu as tenu ton stylo à l'envers pendant toute la réunion avec Aurélie.", "봤어. 오렐리랑 회의하는 내내 펜을 거꾸로 들고 있었잖아."),
(MA, "Sérieusement ?! ... Quand j'étais petit, chez mes parents, chaque dispute finissait par quelqu'un qui claquait la porte. Renvoyer quelqu'un, pour moi, ça y ressemble un peu.", "진짜?! ...어릴 때 우리 집에선 싸움이 날 때마다 누군가 문을 쾅 닫고 나가는 걸로 끝났어. 나한텐 누군가를 내보내는 게 그거랑 좀 비슷해."),
(I, "Sauf que cette fois, c'est toi qui as choisi. Et tu l'as fait avec respect. Même Hubert ne t'a pas désavoué.", "그런데 이번엔 네가 선택한 거야. 그리고 존중을 갖춰서 했어. 위베르조차 너를 문제 삼지 않았잖아."),
(MA, "« Un patron se reconnaît au premier homme qu'il renvoie. » Cette phrase me suit depuis deux semaines.", "'사장이란 처음 내보내는 사람을 보면 알 수 있다.' 그 말이 2주째 머릿속을 떠나지 않아."),
(I, "Alors je vais te dire à quoi je t'ai reconnu, moi : tu as demandé à un mécanicien de soixante ans de transmettre son cahier. Personne n'y avait jamais pensé.", "그럼 내가 널 뭘 보고 알아봤는지 말해 줄게. 넌 예순 살 정비공한테 그 공책을 물려 달라고 부탁했어. 아무도 그런 생각을 못 했어."),
(MA, "Tu vois que tu sais être tendre, Marchetti. Il suffit de te faire grimper à mille quatre cents mètres.", "거봐, 너도 다정할 줄 알잖아, 마르케티. 해발 1,400미터까지 올라오게 하기만 하면 되네."),
(I, "Ne t'y habitue pas, Strasbourg. Lundi, je redeviens la directrice financière glaciale.", "익숙해지지 마, 스트라스부르. 월요일이면 다시 냉정한 재무 책임자로 돌아가니까."),
(MA, "Dans cent jours, on aura présenté le plan au conseil. Et moi, je t'aurai emmenée quelque part un week-end entier. Promis.", "100일 뒤면 우린 이사회에 계획을 발표했을 거야. 그리고 난 널 데리고 주말 내내 어딘가에 다녀왔을 거고. 약속해."),
(I, "Un week-end entier ? Tu es sûr de savoir encore ce que c'est ?", "주말 내내? 그게 뭔지 아직 기억은 나?"),
(None, "Le soleil baisse. Ils s'assoient sur un rocher. Le téléphone d'Inès vibre ; elle le regarde et fronce les sourcils.", "해가 기운다. 둘은 바위에 걸터앉는다. 이네스의 휴대폰이 진동한다. 화면을 보던 그녀가 미간을 찌푸린다."),
(MA, "Non. Range ce téléphone. C'est dimanche.", "안 돼. 휴대폰 집어넣어. 일요일이잖아."),
(I, "Pardon. Une alerte de la banque : le règlement de Domélia pour septembre n'est toujours pas arrivé. Et avec tout ce qu'on sait maintenant...", "미안. 은행 알림이야. Domélia의 9월분 대금이 아직도 안 들어왔어. 지금 우리가 아는 걸 다 생각하면..."),
(MA, "Bon. Je pose la question, puisque tu y penses déjà. Que fait-on lundi ?", "좋아. 어차피 벌써 그 생각 하고 있으니까 내가 물을게. 월요일엔 뭘 하지?"),
(I, "Lundi, je refais tout le prévisionnel de trésorerie, semaine par semaine. Les chiffres de Domélia changent tout, et j'ai un très mauvais pressentiment.", "월요일엔 현금흐름 전망을 주 단위로 전부 다시 짤 거야. Domélia 숫자 때문에 모든 게 달라져. 그리고 느낌이 아주 안 좋아."),
(MA, "Alors ce soir, plus un mot sur les chiffres. On redescend, je te fais une flammekueche, et tu dors huit heures. Lundi, on affrontera ton pressentiment ensemble.", "그럼 오늘 밤엔 숫자 얘기 금지. 내려가서 내가 플람퀴슈 만들어 줄게. 그리고 넌 여덟 시간 자는 거야. 그 불길한 느낌은 월요일에 같이 맞서자."),
(None, "En bas, dans la vallée, les lumières de Saint-Étienne s'allument une à une.", "아래 골짜기에서 생테티엔의 불빛이 하나둘 켜진다."),
]

VOCAB = [
("B1", "L'image est figée.", "화면이 멈췄다", "영상통화 필수 표현. figer = 굳게 하다. Tu es coupé(e) = 끊겼어 / Je ne t'entends plus."),
("B2", "avoir une tête de déterré", "몰골이 말이 아니다, 죽을상이다", "구어. 직역 '무덤에서 파낸 사람의 얼굴'. avoir une sale tête, avoir les traits tirés도 비슷."),
("B1", "les cernes (m.)", "다크서클", "avoir des cernes. 피로를 말할 때 tête de déterré와 짝으로 자주 씀."),
("B2", "le plan des cent jours", "(취임 후) 100일 계획", "les cent premiers jours. 신임 경영자·정치인이 첫 석 달 남짓 동안 실행할 우선 과제."),
("B2", "l'encadrement supérieur", "고위 관리자층", "cadres supérieurs 전체. l'encadrement intermédiaire(중간 관리자층)와 구분."),
("B2", "le dauphin", "후계자, 황태자", "원래 프랑스 왕세자 칭호. 기업·정당에서 '유력 후계자'라는 뜻으로 즐겨 씀."),
("B2", "ne pas digérer qc", "~을 받아들이지 못하다, 앙금이 남다", "구어. digérer = 소화하다. Il n'a jamais digéré cette nomination."),
("C1", "une convention réglementée", "규제 대상 거래(관계자 거래)", "회사와 이사·대주주 사이의 계약. 이사회 사전 승인, 이해관계 이사는 표결 불참, 회계감사인 보고."),
("B2", "s'abstenir (lors d'un vote)", "(표결에서) 기권하다", "명사 l'abstention. 선거에서는 '투표 불참'이라는 뜻도 됨."),
("B2", "le commissaire aux comptes", "(법정) 회계감사인", "약어 CAC. 회사의 재무제표를 인증하는 외부 감사인."),
("B2", "les prévisions de ventes / surestimer", "판매 예측 / 과대평가하다", "↔ sous-estimer. Il surestime de onze pour cent en moyenne."),
("B2", "une part de marché", "시장점유율", "gagner / perdre des parts de marché. 복수형을 자주 씀."),
("B2", "un déréférencement", "(유통업체의) 입점 철수, 품목 제외", "déréférencer un produit ↔ référencer(입점시키다). 제조업체에는 큰 타격."),
("C1", "la marge sur coûts variables", "공헌이익(률)", "매출에서 변동비만 뺀 이익. 매출 감소가 이익에 미치는 영향을 계산할 때 씀."),
("B2", "signer qc des deux mains", "~에 전적으로 찬성하다", "구어. 두 손으로 서명할 만큼 동의한다는 뜻. J'approuve à cent pour cent."),
("B2", "le taux de rendement synthétique (TRS)", "설비종합효율(OEE)", "가동률 × 성능 × 양품률. 공장 생산성을 비교하는 대표 지표."),
("B2", "les cadences (f. pl.)", "생산 속도, 작업 속도", "augmenter / réduire les cadences. 노사 협상에서도 자주 등장."),
("B2", "noir sur blanc", "(글로) 분명히, 명백하게", "C'est écrit noir sur blanc. 서면으로 증거가 남아 있다는 뉘앙스."),
("B2", "une note de passation", "인수인계 메모", "la passation de pouvoir(권한 이양). 전임자가 후임에게 넘기는 문서."),
("C1", "relever qn de ses fonctions", "~을 직무에서 해임하다", "격식 표현. démettre qn de ses fonctions도 같은 뜻. 직접적인 licencier보다 완곡."),
("B2", "un entretien préalable (au licenciement)", "(해고 전) 사전 면담", "프랑스 노동법상 필수 절차. être convoqué(e) à un entretien préalable."),
("B2", "être dispensé(e) d'activité", "업무에서 면제되다", "dispense d'activité rémunérée = 급여를 받으며 출근하지 않는 상태."),
("C1", "renvoyer qn comme un malpropre", "~을 내쫓듯 해고하다", "직역 '더러운 사람처럼 내보내다'. 예의 없이 쫓아낼 때의 관용 표현."),
("B2", "à compter de", "~부터, ~부로", "à compter d'aujourd'hui = 오늘부로. 인사 발령·계약 문서에 쓰는 격식 표현."),
]

GRAM = [
("B2", "전미래(futur antérieur) ①: d'ici + 기한",
 "« D'ici cent jours, nous aurons réduit les stocks de vingt millions et renégocié nos délais de paiement. » « D'ici la fin du plan, nous aurons décidé quelles gammes nous gardons. » « d'ici trente jours, vous aurez rencontré Domélia et vous nous aurez dit ce qu'on peut sauver » 형태는 avoir/être의 단순미래 + 과거분사. 미래의 어느 시점에 '이미 끝나 있을' 일을 말한다. 계획서·목표 설정에 딱 맞는 시제라서 100일 계획 같은 문서에서 자주 쓴다."),
("B2", "전미래 ②: quand / dès que / une fois que + 전미래",
 "« Quand on aura nommé les bonnes personnes aux bons postes, le reste ira plus vite. » 두 미래 사건 가운데 먼저 끝나는 쪽을 전미래로, 뒤따르는 쪽을 단순미래로 쓴다. 한국어로는 '~하고 나면'. 비교: « Quand nous aurons un vrai nouveau produit, ils reviendront. »(동시적이면 단순미래). 연인의 약속에도 쓴다: « Dans cent jours, on aura présenté le plan au conseil. Et moi, je t'aurai emmenée quelque part. »(목적어 te가 앞에 있어 과거분사 일치 emmenée)."),
("B2", "우선순위·계획을 말하는 표현",
 "« Première priorité : la trésorerie. » « Deuxième : le produit. » « Sans cash, il n'y a ni deuxième ni troisième priorité. » « Le conseil attend trois priorités, pas trente. » 발표에서는 동사 없이 서수 + 명사만으로 짧게 끊어 말한다. 그 밖에 en priorité(우선적으로), avant toute chose(무엇보다 먼저), passer avant(~보다 앞서다), à compter d'aujourd'hui(오늘부로)도 함께 익히자. ni... ni...는 '~도 ~도 아니다'로, 부정의 ne와 함께 쓴다."),
("B2", "조건법 과거: 비난·후회·놓친 가능성",
 "« Vous auriez dû m'en informer le premier jour. »(비난) « Je sais que j'aurais dû alerter plus haut. »(후회) « Vous auriez pu m'en parler avant. »(아쉬움) « Si j'avais réussi, vous n'auriez jamais eu à vous en inquiéter. »(si + 대과거 → 조건법 과거) devoir의 조건법 과거는 '~했어야 했다', pouvoir는 '~할 수도 있었다'. 질문으로 바꾸면 상대를 몰아붙이는 효과가 난다: « Tu aurais attendu combien de temps, toi ? »"),
("C1", "양보 표현: avoir beau / quand bien même / ce n'est pas parce que... que",
 "« Vous avez beau avoir vingt-six ans de maison, je ne peux pas travailler avec... »(avoir beau + 부정사 = 아무리 ~해도) « Quand bien même il aurait commis une faute, vous auriez pu m'en parler avant. »(quand bien même + 조건법 = 설령 ~라 해도) « Ce n'est pas parce que je déteste les conflits que je vais les fuir. »(~라고 해서 ~하는 것은 아니다) 세 표현 모두 '인정하지만 결론은 바뀌지 않는다'는 논리를 만든다. 문어·협상에서 특히 유용하다."),
("B2", "접속법: 의지·필요·선호, 그리고 avant que / sans que",
 "« Je veux que ce savoir reste dans l'usine. » « il faut qu'il l'entende de ma bouche » « Je préférerais que nous trouvions ensemble une sortie digne. » « avant que je m'endorme sur mon clavier » « sans que Martine le note dans un registre » vouloir que, il faut que, préférer que 뒤와 avant que, sans que 뒤에는 접속법. 주어가 같으면 부정사로: Je veux rester. / sans le noter. 조건법 je préférerais로 요구를 부드럽게 만드는 점에도 주목."),
("B2", "대명사 en: de를 요구하는 동사와 함께",
 "« Je m'en charge moi-même. »(se charger de) « Vous auriez dû m'en informer. »(informer qn de qc) « vous n'auriez jamais eu à vous en inquiéter »(s'inquiéter de) « je vous en parlerai avant d'agir »(parler de) « Je vous en dirai plus vendredi. » de + 사물·내용은 en으로 받는다. 대명사 순서는 me/te/vous → en: m'en, vous en. 복합시제에서는 en이 조동사 앞에 온다."),
("B2", "회의의 vous, 둘만의 tu: 호칭 전략",
 "제3자 앞에서는 « Madame Marchetti et moi en avons parlé. » « Monsieur Kessler, Madame Marchetti » 처럼 직함·성과 vous를 쓰고, 둘만 있을 때는 « Tu es sûr de vouloir le faire seul ? » « Ne t'y habitue pas, Strasbourg. »처럼 tu와 애칭을 쓴다. 소피아의 « Monsieur le directeur général ! Pardon... bonjour, Mathieu. »는 직함과 이름 사이에서 흔들리는 순간이다. 성으로만 부르는 « Kessler »(델마스·위베르)는 동등하거나 위에서 내려다보는 느낌을 주어, 갈등 장면에서 적대감을 드러낸다."),
]

CULTURE = [
("'첫 100일'이라는 관습",
 "'100일'이라는 표현은 1815년 엘바 섬을 탈출한 나폴레옹이 파리로 돌아와 워털루 패전 뒤 다시 퇴위하기까지의 약 100일(les Cent-Jours)에서 나왔다. 20세기에는 1933년 미국 루스벨트 대통령이 취임 직후 100일 동안 대규모 개혁 법안을 몰아서 통과시키면서 '새 지도자의 첫 100일'을 평가하는 관행이 생겼다. 오늘날 프랑스 기업에서도 새 대표이사나 임원이 부임하면 진단·경청·우선순위 설정·첫 인사 결정을 담은 plan des 100 jours를 이사회에 제시하는 경우가 많다."),
("프랑스에서 임원(간부 직원)을 해고하는 절차",
 "영업이사처럼 근로계약을 맺은 간부(cadre)는 대표이사(mandataire social)와 달리 노동법의 보호를 받는다. 해고하려면 '실질적이고 중대한 사유(cause réelle et sérieuse)'가 있어야 하고, 먼저 사전 면담(entretien préalable)에 소환해야 한다. 면담은 소환장을 받은 뒤 최소 5영업일이 지나야 열 수 있고, 해고 통지서는 면담 후 최소 2영업일 뒤에 사유를 적어 보낸다. 간부는 보통 3개월의 예고 기간(préavis)이 있는데, 회사가 근무를 면제하면 그 기간의 급여는 그대로 지급한다. 실무에서는 소송을 피하려고 합의 퇴직이나 화해 합의(transaction)로 마무리하는 경우가 많다."),
("로안과 필라 산",
 "로안(Roanne)은 루아르 강변의 도시로 오랫동안 섬유·직물 산업과 군수 공장으로 성장했으며, 트루아그로(Troisgros) 가문의 레스토랑 덕분에 미식 도시로도 이름이 높다. 생테티엔 남쪽의 필라 산지는 1974년 지역자연공원(Parc naturel régional du Pilat)으로 지정되었고, 최고봉 크레 드 라 페르드리(약 1,430m) 주변에는 '시라(chirats)'라고 부르는 화강암 바위 무더기가 펼쳐져 있다. 날이 맑으면 정상 부근에서 론 계곡 너머로 알프스와 몽블랑까지 보여, 생테티엔과 리옹 시민들이 주말 산책·하이킹을 즐기는 곳이다."),
]
