# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA = "Inès", "Mathieu"
JF, AG, KA, MR = "Josiane", "Agathe", "Kader", "Martine"
MO, CO, DY = "Momo", "Coralie", "Dylan"

META = {
    "part": 2, "ep": 20,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Le CSE ne signe pas",
    "title_ko": "CSE는 서명하지 않는다",
    "place": "생테티엔 자카르(Jacquard) 지구 이네스의 아파트 · Verdier Industries 본사 · CSE 회의실 · 생테티엔 공장 조립 작업장 휴게실 / 2월, 화요일~목요일",
    "chars": "이네스, 마티외, 아가트 르누아르(인사 총괄 DRH), 조지안 파브르(중앙 CSE 서기·중앙 노조 대표), 카데르 망수리(CSE 위원·다른 노조), 마르틴 로슈(CEO 비서), 모모 벨카셈(숙련공), 코랄리(프레스 작업자), 딜랑(젊은 설비 조정공)",
    "work": "구조조정안(프랑스 사업장 250개 일자리 감축)을 둘러싼 CSE 정보·협의 절차와 노조 협상 — PSE냐 집단 합의 해지(RCC)냐, 자발적 퇴직·전보·재교육·정년 전 퇴직, 그리고 결렬",
    "life": "아침 식탁의 첫 큰 말다툼(400명 vs 150명), 따로 출근하는 두 사람, 눈 내리는 밤의 사과와 화해, 새로 정한 '두 사람의 규칙'",
    "focus": "노동법·노사 관계 어휘(CSE, PSE, plan social, RCC, rupture conventionnelle, accord majoritaire, critères d'ordre), 양보·반박 표현(certes, pourtant, en revanche, il n'empêche que, quand bien même, avoir beau), quel que soit, 사과와 화해 표현(en vouloir à, je n'aurais pas dû), 회의록 문체",
    "levelmix": "B1 15% · B2 55% · C1 30%",
    "next": "제21화 Saint-Étienne — 토요일 장 조레스 광장 장터에서 CEO를 알아보는 동네 사람들, 모모의 야간 근무 초대, 그리고 10년 동안 무시당한 현장의 개선안.",
}

D = [
# ---------- 1. Ouverture : la dispute du petit-déjeuner ----------
(None, "Un mardi de février, 6 h 40. Saint-Étienne, quartier Jacquard. Il tombe de la neige fondue. Dans la cuisine d'Inès, Mathieu fait griller du pain ; Figaro surveille le beurre. Sur la table : « Projet de réorganisation — CSE extraordinaire, 14 h ».",
       "2월의 어느 화요일, 오전 6시 40분. 생테티엔 자카르 지구. 진눈깨비가 내린다. 이네스의 부엌에서 마티외가 빵을 굽고, 피가로는 버터를 감시한다. 식탁 위에는 '구조조정안 — 임시 CSE, 14시'라고 적힌 서류."),
(MA, "Tu as dormi, au moins ? Tu t'es relevée trois fois cette nuit.", "잠은 좀 잤어? 밤새 세 번이나 일어났잖아."),
(I, "Deux fois. La troisième, c'était Figaro qui voulait sortir sur le balcon. J'ai refait les calculs : quatre cents postes, c'est le minimum.",
    "두 번. 세 번째는 피가로가 발코니에 나가고 싶어 한 거야. 계산을 다시 해 봤어. 400개 일자리, 그게 최소야."),
(MA, "Inès, on en a parlé hier soir. Cent cinquante. Pas un de plus tant qu'on n'a pas actionné les autres leviers : les achats, la qualité, l'énergie.",
     "이네스, 어젯밤에 얘기했잖아. 150개. 다른 수단들을 먼저 쓰기 전까진 한 명도 더는 안 돼. 구매, 품질, 에너지 말이야."),
(I, "Les autres leviers, c'est dans dix-huit mois. La Banque Rhodanienne, c'est tous les mois. Quarante-deux millions de pertes l'an dernier, Mathieu. Cent cinquante postes, ça fait à peine huit millions d'économies par an.",
    "다른 수단들은 18개월 뒤에나 효과가 나. 방크 로다니엔은 매달 보고를 받고. 작년 손실이 4,200만 유로야, 마티외. 일자리 150개면 연간 절감액이 겨우 800만 유로라고."),
(MA, "Et quatre cents départs, ça coûte combien avant de rapporter quoi que ce soit ? Trente-quatre millions, d'après ton propre tableau. En cash. Qu'on n'a pas.",
     "그럼 400명을 내보내는 데는 한 푼이라도 돌아오기 전에 얼마가 드는데? 네 표에 따르면 3,400만 유로야. 현금으로. 우리한텐 없는 돈이지."),
(I, "On les emprunte, on les étale. En dix-huit mois, c'est remboursé. Si on coupe trop peu aujourd'hui, on refera un plan dans deux ans, et il sera pire.",
    "빌려서 나눠 쓰면 돼. 18개월이면 회수돼. 오늘 너무 적게 자르면 2년 뒤에 또 계획을 세워야 하고, 그땐 더 끔찍할 거야."),
(MA, "Ou alors on casse l'usine pour sauver un tableur. Quatre cents familles, Inès. À Saint-Étienne, tout le monde connaît quelqu'un chez Verdier.",
     "아니면 엑셀 한 장 살리려고 공장을 부수는 거지. 400가구야, 이네스. 생테티엔에선 누구나 베르디에에 아는 사람이 한 명은 있어."),
(I, "Tu crois que je ne le sais pas ? Mais toi, tu as besoin qu'on t'aime. Un CEO n'est pas payé pour être aimé, Mathieu.",
    "내가 그걸 모를 것 같아? 그런데 넌 사랑받아야 직성이 풀리지. CEO는 사랑받으라고 월급 받는 사람이 아니야, 마티외."),
(MA, "Et toi, depuis la faillite de ton père, tu ne vois plus que des chiffres. Les gens, chez toi, ce sont des lignes de coûts.",
     "그리고 넌 아버지 회사가 파산한 뒤로 숫자밖에 안 보이지. 너한테 사람은 비용 항목 한 줄일 뿐이야."),
(None, "Silence. Inès pose sa tasse, très lentement.", "정적. 이네스가 아주 천천히 잔을 내려놓는다."),
(I, "... Tu n'as pas le droit de parler de mon père. Pas pour gagner une dispute sur un plan social.", "...우리 아빠 얘기를 꺼낼 자격은 너한테 없어. 감원 계획 말다툼에서 이기려고 그러는 건 더더욱."),
(MA, "Inès, je ne voulais pas...", "이네스, 그럴 생각은 아니었..."),
(I, "Si. Tu le voulais. Pars le premier ; de toute façon, on ne doit pas arriver ensemble.", "아니, 그럴 생각이었어. 먼저 가. 어차피 같이 출근하면 안 되잖아."),
(MA, "Très bien. Je passe chez moi me changer.", "알았어. 집에 들러서 옷 갈아입고 갈게."),
(I, "C'est ça. À neuf heures, monsieur Kessler. Ne soyez pas en retard.", "그래. 9시에 봬요, 케슬레르 대표님. 늦지 마세요."),
(None, "La porte claque. Figaro regarde Inès, puis la porte, puis le beurre.", "문이 쾅 닫힌다. 피가로가 이네스를 보고, 문을 보고, 다시 버터를 본다."),
(I, "Ne me regarde pas comme ça, toi. Ce n'est vraiment pas le moment.", "너까지 그런 눈으로 보지 마. 지금은 정말 아니야."),

# ---------- 2. Réunion : le CSE extraordinaire ----------
(None, "8 h 50. Siège de Verdier Industries, bureau du directeur général. Agathe Lenoir, la DRH, a étalé les documents de la consultation. Martine Roche apporte le café sans un mot : elle a senti l'orage.",
       "오전 8시 50분. 베르디에 앵뒤스트리 본사 대표이사실. 인사 총괄(DRH) 아가트 르누아르가 협의 자료를 펼쳐 놓았다. 마르틴 로슈가 말없이 커피를 가져온다. 폭풍을 감지한 것이다."),
(AG, "Bonjour à tous les deux. La note d'information doit être remise aux élus avant la séance. Il me manque un chiffre : le nombre de postes supprimés.",
     "두 분 다 안녕하세요. 정보 문서는 회의 전에 위원들에게 전달돼야 해요. 숫자 하나가 비어 있어요. 감축할 일자리 수요."),
(MA, "Deux cent cinquante, sur les sites français : cent soixante à Saint-Étienne, cinquante à Roanne, quarante dans les fonctions support. Les départs volontaires d'abord.",
     "250개입니다. 프랑스 사업장 기준으로 생테티엔 160, 로안 50, 지원 부서 40. 자발적 퇴직이 우선입니다."),
(I, "C'est votre décision, monsieur Kessler. Pour mémoire, la direction financière recommandait quatre cents.", "대표님의 결정이시죠, 케슬레르 대표님. 참고로, 재무 부문은 400을 권고했습니다."),
(AG, "Je le note... Deux cent cinquante licenciements envisagés, c'est pile le seuil : la consultation pourra durer quatre mois au lieu de trois. Vous ne voulez pas descendre à deux cent quarante-neuf ?",
     "적어 둘게요... 해고 예정 250명이면 딱 기준선이에요. 협의 기간이 석 달이 아니라 넉 달까지 갈 수 있어요. 249명으로 낮추고 싶진 않으세요?"),
(MA, "Non, madame Lenoir. Je ne joue pas avec les seuils. Si on commence par une astuce, on perd la confiance avant d'avoir ouvert la bouche.",
     "아니요, 르누아르 이사님. 기준선 가지고 장난치지 않겠습니다. 꼼수로 시작하면 입을 열기도 전에 신뢰를 잃어요."),
(I, "Sur ce point, je suis d'accord avec monsieur Kessler.", "그 점에 대해서는 케슬레르 대표님과 같은 의견입니다."),
(AG, "Bien. Alors un conseil : Josiane Fabre a lu nos comptes avant nous. Ne lui dites rien que vous ne puissiez prouver.",
     "좋아요. 그럼 조언 하나 드리죠. 조지안 파브르는 우리보다 먼저 우리 장부를 읽은 사람이에요. 증명할 수 없는 말은 하나도 하지 마세요."),
(None, "14 h. Salle du CSE central, au rez-de-chaussée. D'un côté, les élus du personnel, dont Josiane Fabre, secrétaire du CSE et déléguée syndicale centrale, et Kader Mansouri, élu d'une autre organisation syndicale. De l'autre, la direction. Comme le veut la loi, c'est Mathieu qui préside.",
       "오후 2시. 1층 중앙 CSE 회의실. 한쪽에는 직원 대표 위원들 — CSE 서기이자 중앙 노조 대표인 조지안 파브르, 다른 노조 소속 위원 카데르 망수리 등. 맞은편에는 경영진. 법에 따라 회의는 마티외가 주재한다."),
(MA, "Mesdames, messieurs, merci d'être présents. L'ordre du jour, que nous avons fixé avec madame Fabre, comporte un seul point : l'ouverture de la procédure d'information et de consultation sur le projet de réorganisation.",
     "여러분, 참석해 주셔서 감사합니다. 파브르 서기님과 함께 정한 안건은 하나입니다. 구조조정안에 관한 정보 제공 및 협의 절차의 개시입니다."),
(JF, "« Fixé ensemble », c'est vite dit. Vous nous avez envoyé un titre, monsieur Kessler. Le document, on l'a reçu il y a deux heures. Quatre-vingts pages.",
     "'함께 정했다'는 건 말이 쉽죠. 대표님은 제목만 보내셨어요. 문서는 두 시간 전에 받았고요. 80페이지짜리를요."),
(MA, "Vous avez raison, c'était trop tard. Cela ne se reproduira pas. Madame Marchetti va d'abord présenter la situation financière.",
     "맞습니다. 너무 늦었습니다. 다시는 그런 일 없을 겁니다. 먼저 마르케티 재무이사가 재무 상황을 설명하겠습니다."),
(I, "Merci. Verdier a perdu de l'argent trois années de suite : quarante-deux millions d'euros l'an dernier. L'endettement net atteint trois cent dix millions. Sans réorganisation, la trésorerie ne tiendra pas au-delà de l'été.",
    "감사합니다. 베르디에는 3년 연속 적자를 냈습니다. 작년에는 4,200만 유로입니다. 순부채는 3억 1천만 유로에 이릅니다. 구조조정이 없으면 현금은 여름을 넘기지 못합니다."),
(JF, "Certes, les pertes sont réelles. Pourtant, il y a quatre ans, l'ancien directeur général est parti avec deux millions d'indemnités. Ce n'est pas l'atelier qui a creusé le trou, madame Marchetti.",
     "물론 손실은 사실이죠. 그런데 4년 전, 전임 대표이사는 퇴직금 200만 유로를 챙겨 떠났어요. 구멍을 판 건 작업장이 아니에요, 마르케티 이사님."),
(I, "Je ne le conteste pas, et je ne défendrai jamais les décisions de mes prédécesseurs. En revanche, c'est à nous de payer leurs factures, et nous ne choisissons pas la date d'échéance.",
    "그 점은 반박하지 않겠습니다. 전임자들의 결정을 변호할 생각도 전혀 없습니다. 다만 그들이 남긴 청구서를 갚는 건 저희 몫이고, 만기일은 저희가 고를 수 없습니다."),
(KA, "Combien de postes, concrètement ? Les gars, en bas, ils veulent un chiffre, pas des graphiques.", "구체적으로 몇 자리입니까? 아래 현장 사람들은 그래프가 아니라 숫자를 원해요."),
(MA, "Deux cent cinquante postes supprimés sur les sites français, sur dix-huit mois. Cent soixante à Saint-Étienne, cinquante à Roanne, quarante dans les fonctions support.",
     "18개월에 걸쳐 프랑스 사업장에서 250개 일자리를 줄입니다. 생테티엔 160, 로안 50, 지원 부서 40입니다."),
(None, "Murmures autour de la table. Quelqu'un repousse sa chaise.", "테이블 주위가 웅성거린다. 누군가 의자를 뒤로 민다."),
(JF, "Deux cent cinquante. Et vous appelez ça un « projet de réorganisation ». Dites « plan social », monsieur Kessler, ce sera plus honnête.",
     "250명. 그걸 '구조조정안'이라고 부르시네요. '감원 계획'이라고 하세요, 대표님. 그게 더 정직하죠."),
(MA, "Juridiquement, c'est un plan de sauvegarde de l'emploi, un PSE, et je ne cache pas le mot. Mais nous voulons d'abord des départs volontaires, avant tout licenciement contraint.",
     "법적으로는 고용보호계획, 즉 PSE입니다. 그 단어를 숨기지 않겠습니다. 하지만 강제 해고에 앞서 자발적 퇴직을 먼저 받으려 합니다."),
(JF, "« D'abord. » Et ensuite ? Quand bien même vous trouveriez cent volontaires, il en manquerait cent cinquante. Ceux-là, vous les licencierez.",
     "'먼저'라. 그다음은요? 설령 자원자 100명을 찾는다 해도 150명이 모자라요. 그 사람들은 해고하시겠죠."),
(MA, "S'il le faut, oui. Je ne vous mentirai pas là-dessus.", "필요하다면, 네. 그 점에 대해 거짓말은 하지 않겠습니다."),
(KA, "Au moins, il est franc. L'ancien nous jurait qu'il n'y aurait rien, et trois mois après...", "적어도 솔직하긴 하네요. 전임자는 아무 일도 없을 거라고 맹세하더니 석 달 뒤에..."),
(JF, "La franchise, ça ne paie pas un loyer, Kader. Pourquoi pas une rupture conventionnelle collective ? Aucun licenciement, uniquement des volontaires. La loi le permet depuis 2017.",
     "솔직함으로 월세를 낼 순 없어, 카데르. 왜 집단 합의 해지(RCC)는 안 되죠? 해고는 없고 자원자만 받는 거요. 2017년부터 법으로 가능하잖아요."),
(I, "Parce qu'une RCC ne fonctionne que s'il y a assez de volontaires. Et elle exige un accord majoritaire : sans votre signature, elle n'existe pas.",
    "RCC는 자원자가 충분할 때만 작동하니까요. 그리고 과반 노조 협약이 필요합니다. 여러분의 서명이 없으면 존재할 수 없죠."),
(JF, "Justement. Notre signature, il faudra la mériter. Ce qu'on veut : zéro licenciement sec, un vrai plan de formation, et un engagement écrit sur l'avenir de l'usine de Saint-Étienne.",
     "바로 그거예요. 우리 서명은 그만한 자격이 있어야 받을 수 있어요. 우리 요구는 이겁니다. 강제 해고 제로, 제대로 된 교육 계획, 그리고 생테티엔 공장의 미래에 대한 서면 약속."),
(I, "Un engagement d'investissement, aujourd'hui, je ne peux pas le financer. Je refuse de signer une promesse que je sais ne pas pouvoir tenir.",
    "투자 약속은 지금으로선 재원을 마련할 수 없습니다. 지킬 수 없다는 걸 알면서 약속에 서명하지는 않겠습니다."),
(JF, "Alors nous, on ne signera rien. Et pour commencer, les élus votent le recours à un expert-comptable, comme la loi nous y autorise. À la charge de l'employeur, bien sûr.",
     "그럼 우리도 아무것도 서명하지 않아요. 우선 위원들은 법이 허용하는 대로 회계 전문가 선임을 의결합니다. 비용은 물론 회사 부담이고요."),
(AG, "C'est votre droit, madame Fabre. La direction mettra tous les documents à sa disposition.", "그건 위원회의 권리죠, 파브르 서기님. 경영진은 모든 자료를 전문가에게 제공하겠습니다."),
(JF, "Et notez bien ceci au procès-verbal : le CSE ne signe pas, monsieur Kessler. Le CSE rend un avis. Et s'il fallait le rendre aujourd'hui, il serait défavorable.",
     "그리고 이건 회의록에 꼭 적어 두세요. CSE는 서명하지 않습니다, 대표님. CSE는 의견을 낼 뿐이에요. 그리고 오늘 의견을 내야 한다면, 그건 반대 의견일 겁니다."),
(MA, "Nous en prenons acte. Je vous propose une première séance de négociation avec les délégués syndicaux jeudi. D'ici là, nous irons dans les ateliers.",
     "확인했습니다. 목요일에 노조 대표들과 첫 협상 회의를 제안합니다. 그때까지 저희는 작업장에 가 보겠습니다."),
(JF, "Dans les ateliers ? Allez-y. Mais allez-y sans cravate, et écoutez plus que vous ne parlez.", "작업장이요? 가 보세요. 단, 넥타이는 풀고 가세요. 그리고 말하는 것보다 더 많이 들으세요."),
(MA, "Sans cravate. C'est promis. La séance est levée.", "넥타이 없이. 약속하죠. 회의를 마칩니다."),

# ---------- 3. Analyse : trois colonnes ----------
(None, "18 h 30. Bureau de Mathieu. Sur le tableau blanc, Agathe a tracé trois colonnes : « PSE », « RCC », « Autres ». Dehors, la nuit tombe sur les toits de la ville.",
       "오후 6시 30분. 마티외의 사무실. 아가트가 화이트보드에 세 칸을 그렸다. 'PSE', 'RCC', '기타'. 밖에는 도시의 지붕 위로 밤이 내려앉는다."),
(AG, "Récapitulons. Option un : le PSE classique. Volontaires d'abord, licenciements ensuite si nécessaire, selon les critères d'ordre : ancienneté, charges de famille, âge, handicap.",
     "정리해 보죠. 첫째, 전형적인 PSE. 자원자를 먼저 받고, 필요하면 해고합니다. 해고 순서 기준에 따라서요. 근속 연수, 부양가족, 나이, 장애."),
(I, "C'est la seule option dont nous maîtrisons le calendrier. Quatre mois de consultation au maximum, puis la validation ou l'homologation par la DREETS.",
    "일정을 우리가 통제할 수 있는 유일한 선택지예요. 협의는 최대 넉 달, 그다음 DREETS의 승인이나 인가."),
(MA, "Et quatre mois de guerre dans les ateliers. Avec une usine en grève, je ne suis pas sûr qu'on économise grand-chose.",
     "그리고 작업장에선 넉 달 동안 전쟁이지. 공장이 파업하면 뭘 아끼는 건지 잘 모르겠어."),
(AG, "Option deux : la RCC que propose madame Fabre. Aucun licenciement, une image bien meilleure. Mais il faut un accord majoritaire, et les volontaires coûtent cher : on paie au-delà des indemnités légales pour qu'ils partent.",
     "둘째, 파브르 서기가 제안한 RCC. 해고가 없고 이미지도 훨씬 낫죠. 하지만 과반 협약이 필요하고, 자원자는 비싸요. 떠나게 하려면 법정 퇴직금보다 더 줘야 하니까요."),
(I, "Combien de plus ?", "얼마나 더요?"),
(AG, "Sur les derniers dossiers que j'ai vus dans la région, entre quinze et vingt-cinq mois de salaire par départ, selon l'ancienneté.",
     "제가 이 지역에서 최근에 본 사례들로는, 근속 연수에 따라 1인당 15개월에서 25개월치 급여예요."),
(I, "Deux cent cinquante départs, plus la formation et l'accompagnement : on dépasse les vingt millions. Ma première estimation était de vingt et un. Nous n'avons pas cet argent, et la Banque Rhodanienne le sait.",
    "250명 퇴직에 교육과 지원 비용까지 더하면 2천만 유로가 넘어요. 제 첫 추정치가 2,100만이었어요. 우리한텐 그 돈이 없고, 방크 로다니엔도 그걸 알아요."),
(MA, "Et un licenciement, ça ne coûte rien, peut-être ? Les indemnités, le congé de reclassement, les avocats quand ça finit aux prud'hommes...",
     "그럼 해고는 공짜야? 퇴직금, 재취업 휴가, 노동법원까지 가면 변호사 비용까지..."),
(AG, "Monsieur Kessler a raison sur un point : au-delà de mille salariés, le congé de reclassement est obligatoire. Et il faudra signer une convention de revitalisation du bassin d'emploi avec la préfecture.",
     "케슬레르 대표님 말씀이 한 가지는 맞아요. 직원 1,000명 이상이면 재취업 휴가는 의무예요. 그리고 도청과 지역 고용권 재활성화 협약도 맺어야 하고요."),
(I, "Je ne dis pas que le PSE est gratuit. Je dis qu'il est prévisible. Une RCC sans volontaires, c'est un trou dans le budget et six mois de perdus.",
    "PSE가 공짜라는 게 아니에요. 예측 가능하다는 거죠. 자원자 없는 RCC는 예산에 구멍 나고 6개월을 날리는 거예요."),
(MA, "Et si on en avait, des volontaires ? Tu ne sais pas combien de gens ont envie de partir. Moi non plus. Personne ne le leur a jamais demandé.",
     "자원자가 있다면? 떠나고 싶은 사람이 몇 명인지 넌 몰라. 나도 몰라. 아무도 그들에게 물어본 적이 없으니까."),
(AG, "Il reste la troisième colonne. Les « autres ».", "세 번째 칸이 남았어요. '기타'요."),
(MA, "Justement. Un : les mobilités vers Roanne. Le directeur du site cherche trente techniciens de maintenance depuis un an.",
     "바로 그거예요. 하나, 로안으로의 전보. 그곳 공장장이 1년째 정비 기술자 30명을 구하고 있어요."),
(I, "Roanne est à quatre-vingts kilomètres. Tu demandes à des gens de faire deux heures de route par jour, en hiver ?",
    "로안은 80킬로미터 떨어져 있어. 겨울에 하루 두 시간씩 운전하라고 할 거야?"),
(MA, "Je le propose, je ne l'impose pas. Avec une prime de mobilité et un covoiturage organisé. Deux : la formation. Nos futurs produits connectés demanderont des compétences en électronique qu'on n'a pas.",
     "제안하는 거지, 강요하는 게 아니야. 이동 수당이랑 회사가 조직하는 카풀까지 해서. 둘, 교육. 앞으로 나올 커넥티드 제품엔 우리에게 없는 전자 기술이 필요해."),
(I, "Former quelqu'un pendant un an, c'est le payer un an sans qu'il produise. Tu déplaces le coût, tu ne le supprimes pas.",
    "누군가를 1년 동안 교육한다는 건, 생산도 안 하는 사람에게 1년치 급여를 주는 거야. 넌 비용을 옮기는 거지, 없애는 게 아니야."),
(MA, "Je l'investis. Nuance.", "투자하는 거지. 미묘한 차이야."),
(I, "La nuance, la banque ne la finance pas.", "그 미묘한 차이에 은행은 돈을 안 빌려줘."),
(AG, "Et les ruptures conventionnelles individuelles ? Certains salariés en demandent déjà.", "그럼 개별 합의 해지는요? 벌써 요청하는 직원들도 있어요."),
(I, "Quelques-unes, oui. Mais si on en signe des dizaines pour éviter le PSE, l'administration y verra un contournement. Je ne veux pas courir ce risque.",
    "몇 건은 괜찮아요. 하지만 PSE를 피하려고 수십 건을 체결하면 당국은 그걸 법 회피로 볼 거예요. 그런 위험은 지고 싶지 않아요."),
(AG, "Vous avez raison, la DREETS regarde ça de très près. Bon, je vous laisse. Je crois que vous avez... des choses à finir sans moi.",
     "맞아요, DREETS는 그걸 아주 꼼꼼히 봐요. 자, 저는 이만 가 볼게요. 두 분은... 저 없이 마무리할 일이 있으신 것 같네요."),
(None, "Elle sort. Martine entre avec deux tisanes, les pose sur le bureau et s'arrête sur le seuil.", "아가트가 나간다. 마르틴이 허브차 두 잔을 들고 들어와 책상에 놓고는 문턱에서 멈춰 선다."),
(MR, "En 1996, il y a eu un plan social ici. J'étais là depuis un an. Trois cents personnes. Presque trente ans après, à la cantine, on parle encore de ceux qui l'ont signé.",
     "1996년에 여기서 감원 계획이 있었어요. 제가 입사한 지 1년 됐을 때였죠. 300명이었어요. 30년 가까이 지났는데도 구내식당에선 아직 그걸 서명한 사람들 얘기를 해요."),
(MA, "Et qu'est-ce qu'on dit d'eux, Martine ?", "그 사람들에 대해 뭐라고들 하나요, 마르틴?"),
(MR, "Pas qu'ils ont supprimé des postes. Qu'ils ne sont jamais descendus dans l'atelier. Bonne soirée, monsieur Kessler. Madame Marchetti.",
     "일자리를 없앴다는 얘기가 아니에요. 한 번도 작업장에 내려오지 않았다는 얘기죠. 좋은 저녁 되세요, 케슬레르 대표님. 마르케티 이사님."),
(None, "La porte se referme. Ils sont seuls. Ils se tutoient, mais la voix reste froide.", "문이 닫힌다. 둘만 남았다. 서로 말을 놓지만 목소리는 여전히 차갑다."),
(I, "Tu as entendu. Descendre dans l'atelier. C'est ton terrain, ça, pas le mien.", "들었지. 작업장에 내려가라. 그건 네 영역이지, 내 영역이 아니야."),
(MA, "Ce sera le nôtre. Je veux que tu viennes demain matin. Avec ton tableur, si tu veux, mais tu écoutes avant de compter.",
     "우리 영역이 될 거야. 내일 아침에 같이 갔으면 해. 원하면 엑셀도 들고 와. 대신 계산하기 전에 먼저 들어."),
(I, "J'ai beau compter dans tous les sens, il manque de l'argent. Ça ne changera pas parce qu'on boit un café à la machine avec l'équipe du matin.",
    "아무리 이리저리 계산해 봐도 돈이 모자라. 아침 근무조랑 자판기 커피 한 잔 마신다고 그게 바뀌진 않아."),
(MA, "Peut-être. Mais tant qu'on n'y est pas allés, tu ne peux pas savoir si ton chiffre est juste. Et moi non plus pour le mien.",
     "그럴지도. 하지만 가 보기 전까진 네 숫자가 맞는지 넌 알 수 없어. 내 숫자도 마찬가지고."),
(I, "... D'accord. Cinq heures quarante-cinq, à la relève. Mais j'y vais de mon côté.", "...좋아. 5시 45분, 근무 교대 시간. 하지만 난 따로 갈 거야."),
(MA, "Évidemment. Chacun de son côté.", "물론이지. 각자 따로."),

# ---------- 4. Terrain : la salle de pause ----------
(None, "Mercredi, 5 h 45. Usine de Saint-Étienne, salle de pause de l'atelier d'assemblage. Néons, distributeur de café, odeur de métal chaud. L'équipe de nuit croise l'équipe du matin. Mathieu est en pull ; Inès arrive cinq minutes après lui.",
       "수요일 오전 5시 45분. 생테티엔 공장 조립 작업장 휴게실. 형광등, 커피 자판기, 뜨거운 금속 냄새. 야간조와 아침조가 교대한다. 마티외는 스웨터 차림이고, 이네스는 그보다 5분 늦게 도착한다."),
(MO, "Tiens, le patron. Sans cravate, en plus. Josiane vous a briefé, on dirait.", "어라, 사장님이네. 넥타이도 안 매고. 조지안한테 한 수 배우셨나 보네요."),
(MA, "Elle m'a conseillé d'écouter plus que je ne parle. Je commence maintenant. Bonjour, Momo.", "말하는 것보다 더 많이 들으라고 하더군요. 지금부터 시작합니다. 안녕하세요, 모모."),
(MO, "Bonjour, monsieur Kessler. Bonjour, madame. Un café ? Il est mauvais, mais il est chaud. Comme la maison, quoi.",
     "안녕하세요, 케슬레르 대표님. 안녕하세요, 이사님. 커피 한잔하실래요? 맛은 없지만 뜨거워요. 우리 회사처럼요."),
(I, "Volontiers. Je vous l'offre... Ah, la machine ne prend que les pièces.", "좋아요. 제가 살게요... 아, 자판기가 동전만 받네요."),
(CO, "Laissez, j'ai de la monnaie. Coralie, presses et emboutissage, neuf ans chez Verdier. C'est vous qui voulez supprimer deux cent cinquante postes ?",
     "놔두세요, 저한테 잔돈 있어요. 코랄리예요. 프레스·성형 작업, 베르디에에서 9년째고요. 일자리 250개를 없애려는 게 당신들이에요?"),
(I, "C'est nous qui devons sauver l'entreprise, madame. Et oui, le projet prévoit deux cent cinquante postes. Je préfère vous le dire en face.",
    "회사를 살려야 하는 게 저희예요. 그리고 네, 계획안에는 250개 일자리가 들어 있어요. 면전에서 말씀드리는 게 낫다고 생각해요."),
(CO, "Au moins, vous le dites. Moi, j'ai deux enfants, je les élève seule, et j'habite à Firminy. Roanne, avec ma vieille voiture, c'est impossible.",
     "적어도 말은 해 주시네요. 저는 혼자 애 둘을 키우고 피르미니에 살아요. 제 낡은 차로 로안은 불가능해요."),
(MA, "Personne ne vous obligera à aller à Roanne. La mobilité sera proposée, pas imposée.", "아무도 로안에 가라고 강요하지 않을 겁니다. 전보는 제안이지 강제가 아니에요."),
(CO, "« Proposée »... Et si je refuse, je suis la première sur la liste ?", "'제안'이라... 그럼 거절하면 제가 명단 맨 위에 오르는 건가요?"),
(I, "Non. La loi fixe des critères d'ordre, et la situation des parents isolés en fait partie. Elle compte en votre faveur, pas contre vous.",
    "아니요. 법이 해고 순서 기준을 정해 두었고, 한부모 가정의 상황도 그 기준에 들어가요. 불리하게가 아니라 유리하게 작용하죠."),
(CO, "Vous connaissez le Code du travail, vous. Josiane aussi. Mais à la fin, c'est quand même nous qui avons peur.", "이사님은 노동법을 잘 아시네요. 조지안도요. 그래도 결국 무서운 건 우리예요."),
(DY, "Moi, je n'ai pas peur. Dylan, vingt-quatre ans, régleur. Si vous me proposez un départ volontaire correct, je pars demain.",
     "전 안 무서워요. 딜랑, 스물네 살, 설비 조정공이에요. 괜찮은 자발적 퇴직 조건을 주시면 내일이라도 나갈게요."),
(MA, "Vraiment ? Pour faire quoi ?", "정말요? 나가서 뭘 하려고요?"),
(DY, "Ouvrir un atelier de réparation de vélos avec mon cousin. Ça vous fait rire ? Verdier, au départ, c'était des vélos.", "사촌이랑 자전거 수리점을 차리려고요. 웃기세요? 베르디에도 원래 자전거 회사였잖아요."),
(MA, "Ça ne me fait pas rire du tout. 1874. La boucle est bouclée.", "전혀 안 웃깁니다. 1874년. 한 바퀴 돌아 제자리로 온 셈이네요."),
(MO, "Il n'est pas le seul, vous savez. Sur ma ligne, on est une bonne dizaine à avoir plus de cinquante-huit ans. Le dos, les genoux... Si on nous proposait un vrai départ de fin de carrière, beaucoup partiraient la tête haute.",
     "저 친구만 그런 게 아니에요. 제 라인에만 쉰여덟 살 넘은 사람이 족히 열 명은 돼요. 허리, 무릎... 제대로 된 정년 전 퇴직을 제안하면 다들 떳떳하게 나갈 거예요."),
(I, "Une dizaine sur une seule ligne ? Et sur toute l'usine ?", "라인 하나에만 열 명이요? 공장 전체로는요?"),
(MO, "Demandez à la DRH, elle a les listes. Mais je dirais plus de cent cinquante.", "인사 총괄한테 물어보세요. 명단은 그쪽에 있으니까. 하지만 제 생각엔 150명은 넘을걸요."),
(I, "Plus de cent cinquante... Avec les jeunes comme Dylan, les volontaires pourraient être bien plus nombreux que ce que nous avions prévu.",
    "150명 이상이라... 딜랑 같은 젊은 사람들까지 합치면 자원자가 저희 예상보다 훨씬 많을 수도 있겠네요."),
(MO, "Personne ne nous l'a jamais demandé, madame. Ni l'ancien patron, ni celui d'avant. On remplit des fiches, on ne nous pose pas de questions.",
     "아무도 우리한테 물어본 적이 없어요, 이사님. 전임 사장도, 그 전 사장도요. 우린 서류만 채우지, 질문은 받아 본 적이 없어요."),
(MA, "Et vous, Momo ? Vous partiriez ?", "모모는요? 떠나시겠어요?"),
(MO, "Moi ? Quarante ans de maison. Je partirai quand La Stéphanoise sera sauvée. Pas avant. Vous ne vous débarrasserez pas de moi comme ça.",
     "저요? 40년 근속이에요. 라 스테파누아즈가 살아나면 그때 떠날 겁니다. 그 전엔 안 가요. 그렇게 쉽게 절 떼어 내진 못하실걸요."),
(None, "Josiane Fabre entre, sa blouse sur le bras. Elle s'arrête en les voyant.", "조지안 파브르가 작업복을 팔에 걸치고 들어온다. 그들을 보고 걸음을 멈춘다."),
(JF, "Tiens. La direction à la relève de six heures. Ça, je ne l'avais pas vu depuis... jamais, en fait.", "어머. 경영진이 6시 교대 시간에 다 오시고. 이런 건... 사실 한 번도 본 적이 없네요."),
(MA, "Vous nous avez dit d'écouter. Nous écoutons.", "들으라고 하셨잖아요. 듣고 있습니다."),
(JF, "Bien. Mais n'allez pas croire que trois cafés suffiront. Jeudi, on veut des garanties écrites.", "좋아요. 하지만 커피 세 잔으로 될 거라고 생각하진 마세요. 목요일엔 서면 보장을 원해요."),

# ---------- 5. Décision : la négociation ----------
(None, "Jeudi, 9 h. Salle de réunion du siège. Première séance de négociation avec les délégués syndicaux. Agathe Lenoir distribue un nouveau document : « Mesures d'accompagnement — version 2 ».",
       "목요일 오전 9시. 본사 회의실. 노조 대표들과의 첫 협상 회의. 아가트 르누아르가 새 문서를 나눠 준다. '지원 조치 — 2차안'."),
(MA, "Madame Fabre, monsieur Mansouri, avant de commencer : mardi, vous nous avez dit d'aller écouter. Nous l'avons fait. Ce document en tient compte.",
     "파브르 서기님, 망수리 위원님, 시작하기 전에 한 말씀 드리겠습니다. 화요일에 가서 들으라고 하셨죠. 그렇게 했습니다. 이 문서는 그 내용을 반영했습니다."),
(JF, "On verra. Présentez.", "두고 보죠. 설명하세요."),
(I, "Premier point : une période de volontariat de six mois, pendant laquelle il n'y aura aucun licenciement contraint. Les départs volontaires seront accompagnés d'indemnités supra-légales : en moyenne dix-huit mois de salaire.",
    "첫째, 6개월간의 자원 기간을 두고, 그동안 강제 해고는 일절 없습니다. 자발적 퇴직자에게는 법정 기준을 넘는 퇴직금을 지급합니다. 평균 18개월치 급여입니다."),
(KA, "Dix-huit mois en moyenne... C'est plus que ce que la plupart des boîtes du coin ont donné.", "평균 18개월이라... 이 동네 회사들 대부분이 준 것보다 많네요."),
(I, "Deuxième point : un dispositif de fin de carrière pour les salariés de cinquante-huit ans et plus. Ils quittent l'entreprise et perçoivent soixante-dix pour cent de leur salaire jusqu'à leur retraite à taux plein.",
    "둘째, 58세 이상 직원을 위한 정년 전 퇴직 제도입니다. 회사를 떠나 연금을 전액 받을 수 있는 나이가 될 때까지 급여의 70%를 받습니다."),
(JF, "Et qui paie ? Pas l'État, j'espère. Les préretraites publiques, ça fait longtemps qu'il n'y en a presque plus.", "누가 내죠? 국가는 아니길 바라요. 공적 조기 퇴직 제도는 거의 사라진 지 오래니까요."),
(I, "L'entreprise. Intégralement. C'est la mesure la plus chère du plan, et c'est moi qui l'ai chiffrée.", "회사가 냅니다. 전액이요. 이 계획에서 가장 비싼 조치이고, 비용은 제가 직접 산정했습니다."),
(MA, "Troisième point : la mobilité vers Roanne, uniquement sur la base du volontariat, avec une prime de cinq mille euros et un covoiturage financé par l'entreprise. Quatrième point : un congé de reclassement de douze mois, et une aide de quinze mille euros pour ceux qui créent leur entreprise.",
     "셋째, 로안으로의 전보는 오직 자원에 한하며, 5,000유로의 수당과 회사가 비용을 대는 카풀을 제공합니다. 넷째, 12개월의 재취업 휴가, 그리고 창업하는 직원에게 15,000유로를 지원합니다."),
(KA, "Le petit régleur, avec ses vélos, il va être content.", "자전거 얘기하던 그 젊은 조정공이 좋아하겠네요."),
(JF, "Je reconnais que c'est mieux. Beaucoup mieux que mardi. Il n'empêche que deux cent cinquante postes restent deux cent cinquante postes.",
     "나아진 건 인정해요. 화요일보다 훨씬 낫죠. 그래도 250개 일자리는 여전히 250개 일자리예요."),
(MA, "Ce chiffre est un plafond, pas un objectif. Si les volontaires sont assez nombreux, il n'y aura pas un seul licenciement sec.",
     "그 숫자는 상한선이지 목표가 아닙니다. 자원자가 충분하면 강제 해고는 단 한 건도 없을 겁니다."),
(JF, "« Si. » Moi, je veux ça noir sur blanc : zéro licenciement contraint, quelle que soit l'issue du volontariat.", "'~하면'이라. 전 그걸 문서로 받고 싶어요. 자원 결과가 어떻든 강제 해고 제로."),
(I, "Madame Fabre, je ne peux pas l'écrire. Si seulement quatre-vingts personnes se portent volontaires, l'entreprise ne sera pas sauvée.",
    "파브르 서기님, 그건 쓸 수 없습니다. 자원자가 80명뿐이라면 회사는 살아남지 못합니다."),
(JF, "Et si l'usine ferme dans trois ans, vos dix-huit mois de salaire ne serviront plus à grand-chose. D'où notre deuxième demande : un engagement de maintien du site de Saint-Étienne. Cinq ans.",
     "그리고 3년 뒤에 공장이 문을 닫으면, 18개월치 급여도 별 의미가 없어지죠. 그래서 두 번째 요구가 있는 거예요. 생테티엔 사업장 존치 약속. 5년."),
(MA, "Cet engagement, je le souhaite autant que vous. Mais je ne peux pas le prendre sans le conseil d'administration. Et vous savez qui siège au conseil.",
     "그 약속은 저도 서기님만큼 원합니다. 하지만 이사회 없이 제가 할 수는 없습니다. 이사회에 누가 앉아 있는지 아시잖아요."),
(JF, "Les Verdier et le fonds. Les uns ne veulent toucher à rien, les autres veulent tout vendre. Et c'est nous qui sommes au milieu.",
     "베르디에 가문과 펀드죠. 한쪽은 아무것도 건드리지 않으려 하고, 다른 쪽은 다 팔려고 하고. 그리고 그 사이에 낀 게 우리예요."),
(KA, "Josiane... Ce qui est sur la table, c'est quand même du concret. Chez nous, certains seraient prêts à discuter.", "조지안... 그래도 지금 테이블에 오른 건 구체적인 내용이야. 우리 쪽엔 논의해 볼 만하다는 사람들도 있어."),
(JF, "Discute, Kader. Avec ton syndicat et l'autre, vous faites cinquante-quatre pour cent. Vous pouvez signer sans nous. La loi le permet.",
     "논의해, 카데르. 너희 노조랑 다른 노조를 합치면 54퍼센트잖아. 우리 없이도 서명할 수 있어. 법이 허용하니까."),
(AG, "C'est exact : un accord est valable s'il est signé par des syndicats représentant plus de cinquante pour cent des suffrages exprimés en faveur des organisations représentatives aux dernières élections.",
     "맞습니다. 지난 선거에서 대표성 있는 노조들이 얻은 유효표의 50퍼센트 이상을 대표하는 노조들이 서명하면 협약은 유효합니다."),
(MA, "Juridiquement, oui. Mais je ne signerai pas un accord sans le premier syndicat de cette usine. Ce serait une victoire sur le papier et une défaite dans les ateliers.",
     "법적으로는 그렇습니다. 하지만 이 공장의 제1노조 없이 협약에 서명하지는 않겠습니다. 서류상의 승리이자 작업장에서의 패배가 될 테니까요."),
(None, "Inès tourne la tête vers lui. Un instant, elle semble vouloir le contredire. Elle se tait.", "이네스가 그를 향해 고개를 돌린다. 잠깐, 반박하고 싶은 듯 보인다. 그러나 입을 다문다."),
(I, "La direction est unanime sur ce point, madame Fabre. Nous voulons votre signature, pas seulement une majorité.", "이 점에 대해 경영진의 의견은 일치합니다, 파브르 서기님. 저희는 과반수만이 아니라 서기님의 서명을 원합니다."),
(JF, "Alors gagnez-la. Vous êtes moins mauvais que les autres, je vous l'accorde. Mais quand bien même vous seriez des saints, je ne signerais pas sans garantie sur le site.",
     "그럼 얻어 내세요. 다른 사람들보단 덜 나쁘다는 건 인정하죠. 하지만 설령 두 분이 성인군자라 해도, 사업장에 대한 보장 없이는 서명하지 않을 거예요."),
(MA, "Je vous propose ceci : je présente la demande de maintien du site au conseil d'administration avant notre prochaine séance. Je ne vous promets pas le résultat. Je vous promets de me battre.",
     "이렇게 제안하겠습니다. 다음 회의 전에 사업장 존치 요구를 이사회에 올리겠습니다. 결과는 약속드릴 수 없습니다. 싸우겠다는 것만은 약속드립니다."),
(JF, "Se battre, tout le monde le promet. On jugera sur pièces.", "싸우겠다는 약속은 누구나 하죠. 결과를 보고 판단하겠어요."),
(KA, "Et en attendant ? En bas, les gens attendent une réponse.", "그동안은요? 아래 현장에선 다들 답을 기다리고 있어요."),
(JF, "En attendant, il y aura un débrayage d'une heure demain à quatorze heures. Pour que le conseil comprenne que ce n'est pas qu'une affaire de tableurs.",
     "그동안은 내일 오후 2시에 한 시간 작업 중단을 할 거예요. 이게 엑셀만의 문제가 아니라는 걸 이사회가 알 수 있게요."),
(MA, "C'est votre droit, et je le respecte. Je demande seulement que la sécurité des lignes soit assurée.", "그건 여러분의 권리이고, 존중합니다. 다만 라인의 안전은 확보해 주시길 부탁드립니다."),
(JF, "Elle le sera. Nous sommes des professionnels, monsieur Kessler. Nous aussi.", "그럴 겁니다. 우리도 전문가예요, 대표님. 우리도요."),
(MA, "Je propose donc de suspendre la séance. Reprise jeudi prochain, neuf heures. Madame Fabre, monsieur Mansouri, merci. Nous ne sommes pas d'accord, mais nous nous sommes parlé.",
     "그럼 회의를 정회할 것을 제안합니다. 다음 주 목요일 9시에 재개하죠. 파브르 서기님, 망수리 위원님, 감사합니다. 합의는 못 했지만, 서로 대화는 했습니다."),
(JF, "Une dernière chose. Votre directrice financière ne vous a pas contredit, tout à l'heure. Elle en avait envie, pourtant. Ça se voyait. Parlez-vous, tous les deux.",
     "마지막으로 하나만요. 아까 재무이사님이 대표님 말에 반박하지 않으셨죠. 그러고 싶어 하셨는데. 다 보이던데요. 두 분, 대화 좀 하세요."),
(None, "Elle sort. Inès range ses papiers sans lever les yeux.", "조지안이 나간다. 이네스는 눈을 들지 않은 채 서류를 정리한다."),

# ---------- 6. Le soir : la porte ----------
(None, "Le soir même, 22 h 30. Appartement d'Inès. Elle mange des pâtes froides devant son ordinateur ; Figaro dort sur la « version 2 ». On frappe à la porte.",
       "그날 밤 10시 30분. 이네스의 아파트. 그녀는 컴퓨터 앞에서 식은 파스타를 먹고 있고, 피가로는 '2차안' 위에서 자고 있다. 누군가 문을 두드린다."),
(MA, "C'est moi. Je sais qu'il est tard. Je peux entrer, ou je parle à travers la porte ?", "나야. 늦은 거 알아. 들어가도 돼, 아니면 문 너머로 말할까?"),
(None, "Elle ouvre. Il a de la neige sur les épaules et une bouteille de côtes-du-forez à la main.", "그녀가 문을 연다. 그의 어깨엔 눈이 쌓여 있고, 손에는 코트 뒤 포레 와인 한 병이 들려 있다."),
(I, "Tu es venu à pied depuis le centre, sous la neige ? Tu es complètement fou.", "시내에서 눈 맞으면서 걸어온 거야? 너 완전히 미쳤구나."),
(MA, "Vingt minutes. J'ai eu le temps de répéter. ... Inès, ce que j'ai dit mardi sur ton père, c'était injuste et méchant. Je savais que ça te ferait mal, et je l'ai dit quand même. Je n'aurais jamais dû. Pardon.",
     "20분. 연습할 시간은 충분했어. ...이네스, 화요일에 너희 아버지에 대해 한 말은 부당하고 못된 말이었어. 네가 상처받을 걸 알면서도 했어. 절대 하지 말았어야 했어. 미안해."),
(I, "Tu m'as fait plus mal que Josiane en deux séances.", "조지안이 회의 두 번 동안 준 것보다 네가 더 아프게 했어."),
(MA, "Je sais. Tu m'en veux encore ?", "알아. 아직도 나한테 화났어?"),
(I, "Un peu. Moins depuis que tu as de la neige sur les épaules. ... Moi aussi, j'ai été injuste. « Tu as besoin qu'on t'aime »... Ce n'était pas un argument, c'était une attaque.",
    "조금. 어깨에 눈 쌓인 걸 보고 나서는 덜해. ...나도 부당했어. '넌 사랑받아야 직성이 풀리지'... 그건 논거가 아니라 공격이었어."),
(MA, "C'était un peu vrai, pourtant.", "그래도 조금은 맞는 말이었어."),
(I, "Et ce que tu as dit sur les chiffres, c'était un peu vrai aussi. Hier matin, devant la machine à café, j'ai compris que mon tableau n'avait jamais demandé à Momo s'il voulait partir.",
    "그리고 네가 숫자에 대해 한 말도 조금은 맞았어. 어제 아침 커피 자판기 앞에서 깨달았어. 내 표는 한 번도 모모에게 떠나고 싶냐고 물어본 적이 없더라."),
(MA, "Et moi, aujourd'hui, j'ai compris que sans ton tableau, mes belles promesses ne tiendraient pas un mois devant la banque. Sur la RCC, tu avais raison : sans chiffres, c'est un pari.",
     "그리고 난 오늘 깨달았어. 네 표가 없으면 내 그럴듯한 약속들은 은행 앞에서 한 달도 못 버틴다는 걸. RCC에 대해선 네가 옳았어. 숫자 없이는 도박이야."),
(I, "Tu sais ce qui m'a fait le plus peur, cette semaine ? Pas le CSE. C'est qu'on ramène la réunion à la maison, et la dispute au bureau.",
    "이번 주에 제일 무서웠던 게 뭔지 알아? CSE가 아니야. 우리가 회의를 집으로 가져오고, 싸움을 회사로 가져가는 거였어."),
(MA, "Justement, j'y ai pensé en marchant. On ne peut pas se disputer comme un couple au bureau, ni comme des dirigeants à la maison.",
     "그래서 걸어오면서 생각했어. 회사에서 연인처럼 싸워서도 안 되고, 집에서 경영자처럼 싸워서도 안 된다고."),
(I, "C'est joli. Tu l'as préparée pendant les vingt minutes ?", "멋진 말이네. 20분 동안 준비한 거야?"),
(MA, "Pendant dix-neuf. La dernière minute, je cherchais ton code d'entrée.", "19분 동안. 마지막 1분은 너희 집 현관 비밀번호 찾느라."),
(I, "Alors, règle numéro un : au bureau, on se dispute sur les chiffres, jamais sur nous. Et ici, personne ne parle de nos pères pour gagner.",
    "그럼 규칙 1번. 회사에서는 숫자로 싸우고, 절대 우리 얘기로는 안 싸워. 그리고 여기선 이기려고 서로의 아버지 얘기를 꺼내지 않기."),
(MA, "Règle numéro deux : pas de PSE après vingt-deux heures. Sauf une exception.", "규칙 2번. 밤 10시 이후엔 PSE 금지. 예외 하나만 빼고."),
(None, "Il sort de sa poche le vieux marqueur vert et écrit sur le dos d'une enveloppe.", "그가 주머니에서 낡은 초록 마커를 꺼내 봉투 뒷면에 적는다."),
(I, "Quel est le vrai problème ? Ce n'est ni deux cent cinquante, ni quatre cents, ni cent cinquante. C'est qu'on ne sait pas combien de gens veulent partir, ni ce que l'usine sait faire mieux que nous.",
    "진짜 문제는 무엇인가? 250도, 400도, 150도 아니야. 몇 명이 떠나고 싶어 하는지, 그리고 공장이 우리보다 뭘 더 잘 아는지 모른다는 거야."),
(MA, "Qui décide ? Josiane pour la signature, le conseil pour le site. Et l'usine, qu'on n'a jamais consultée sur ses propres idées. Que fait-on lundi ?",
     "누가 결정하는가? 서명은 조지안이, 사업장은 이사회가. 그리고 자기 아이디어에 대해 한 번도 의견을 들어 본 적 없는 공장. 월요일엔 뭘 하지?"),
(I, "Lundi, on fait ce que personne n'a fait en dix ans : on demande à l'usine. Mais samedi d'abord, tu m'emmènes au marché de la place Jean-Jaurès. Comme des Stéphanois.",
    "월요일엔 10년 동안 아무도 안 한 걸 하는 거야. 공장에 물어보는 거. 하지만 그 전에 토요일엔 장 조레스 광장 장터에 데려가 줘. 생테티엔 사람들처럼."),
(MA, "Comme des Stéphanois. Et si quelqu'un reconnaît son directeur général entre les poireaux et le saucisson ?", "생테티엔 사람들처럼. 그런데 누가 대파랑 소시송 사이에서 자기 회사 대표를 알아보면?"),
(I, "Tu diras bonjour, Strasbourg. Et tu écouteras plus que tu ne parles.", "인사하면 되지, 스트라스부르. 그리고 말하는 것보다 더 많이 듣고."),
]

VOCAB = [
("B2", "présider (la séance) / le, la secrétaire du CSE", "(회의를) 주재하다 / CSE 서기", "CSE는 사용자(또는 그 대리인)가 주재하고, 서기는 위원 중에서 선출된다. 안건(ordre du jour)은 의장과 서기가 함께 정한다."),
("C1", "un plan de sauvegarde de l'emploi (PSE)", "고용보호계획(PSE)", "50인 이상 기업이 30일 안에 10명 이상을 경제적 사유로 해고하려 할 때 의무적으로 마련하는 계획. 재배치·교육·지원 조치를 담아야 한다."),
("B2", "un plan social", "감원 계획, 구조조정", "PSE의 옛 이름이자 일상·언론 표현. 노조가 « Dites plan social »이라며 완곡어를 거부할 때처럼 감정이 실린다."),
("C1", "une rupture conventionnelle collective (RCC)", "집단 합의 해지(RCC)", "2017년 도입. 과반 노조 협약이 필요하고 자원자만 떠나며, 해고는 금지된다. DREETS의 승인을 받아야 한다."),
("B2", "une rupture conventionnelle (individuelle)", "(개별) 합의 해지", "사용자와 직원이 합의해 근로계약을 끝내는 제도. 직원은 실업수당을 받을 수 있다. 집단 해고를 피하려는 남용은 감시 대상."),
("B2", "un licenciement sec / contraint", "강제 해고(보상·대안 없는 해고)", "sec = 마른, 건조한 → '완충 없는'. ↔ un départ volontaire(자발적 퇴직)."),
("B2", "un départ volontaire / se porter volontaire", "자발적 퇴직 / 자원하다", "un plan de départs volontaires(PDV)는 PSE 안에 들어가기도 한다."),
("B2", "un(e) délégué(e) syndical(e)", "노조 대표(사업장 단위)", "협약에 서명하는 사람. CSE 위원(élu)과 역할이 다르다. délégué(e) syndical(e) central(e) = 다사업장 기업의 중앙 대표."),
("C1", "un accord majoritaire", "과반 노조 협약", "지난 직원 선거에서 대표성 있는 노조가 얻은 유효표의 50% 초과를 대표하는 노조들이 서명해야 유효."),
("B2", "rendre un avis (favorable / défavorable)", "(찬성·반대) 의견을 내다", "CSE는 협약에 '서명'하지 않고 '의견'을 낸다. 의견이 반대여도 절차는 진행될 수 있다."),
("C1", "l'information-consultation", "정보 제공 및 협의 절차", "사용자가 CSE에 자료를 제공하고 의견을 구하는 법정 절차. PSE는 해고 규모에 따라 2~4개월."),
("C1", "recourir à un expert-comptable", "회계 전문가를 선임하다", "PSE 협의 때 CSE는 회계 전문가를 지정할 수 있고, 비용은 사용자가 부담한다. recourir à qc = ~에 의지하다."),
("B2", "le reclassement / le congé de reclassement", "재배치·재취업 / 재취업 휴가", "해고 전 내부 재배치를 찾을 의무(obligation de reclassement). 1,000인 이상 기업은 재취업 휴가 제안이 의무."),
("C1", "les critères d'ordre (des licenciements)", "해고 순서 기준", "부양가족(특히 한부모), 근속 연수, 재취업이 어려운 사정(나이·장애), 직무 역량 등."),
("C1", "des indemnités supra-légales", "법정 기준을 넘는 퇴직금", "supra- = '~을 넘는'. ↔ l'indemnité légale de licenciement(법정 해고 수당)."),
("C1", "la DREETS (valider / homologuer)", "지역 노동 행정청 (승인하다 / 인가하다)", "협약에 근거한 PSE는 '승인(validation)', 사용자 단독 문서는 '인가(homologation)'를 받는다."),
("C1", "la revitalisation du bassin d'emploi", "지역 고용권 재활성화", "1,000인 이상 기업이 대량 해고로 지역 고용에 타격을 주면 국가(도청)와 협약을 맺고 재원을 대야 한다."),
("B2", "un débrayage / débrayer", "(짧은) 작업 중단, 부분 파업", "원래 '클러치를 떼다'. 한두 시간 일을 멈추는 파업 형태."),
("B2", "un dispositif de fin de carrière", "정년 전 퇴직 제도", "회사가 비용을 대고 고령 직원이 연금 수령 전까지 급여 일부를 받으며 떠나는 제도. préretraite라고도 한다."),
("B2", "juger sur pièces", "결과(증거)를 보고 판단하다", "pièces = 증빙 서류. 약속보다 실제 결과로 평가하겠다는 말."),
("B2", "Il n'empêche que...", "그렇다 해도 ~인 건 마찬가지다", "상대 말을 인정한 뒤 반박할 때. 직설법이 뒤따른다. N'empêche que...(구어)."),
("B2", "en vouloir à qn", "~에게 화가 나 있다, 원망하다", "Tu m'en veux encore ? 대답: Je ne t'en veux plus(이제 화 안 났어)."),
("B1", "la relève", "(근무) 교대, 교대조", "à la relève de six heures. prendre la relève = 뒤를 이어받다."),
("B1", "avoir de la monnaie", "잔돈이 있다", "monnaie = 잔돈, 동전. Vous avez la monnaie de vingt euros ? (20유로 바꿔 줄 수 있어요?)"),
("B2", "partir la tête haute", "떳떳하게 떠나다", "직역 '머리를 높이 든 채'. ↔ partir la tête basse(고개 숙이고 떠나다)."),
]

GRAM = [
("B2", "양보 ①: certes... pourtant / je reconnais que... il n'empêche que (복습·심화)",
 "« Certes, les pertes sont réelles. Pourtant, il y a quatre ans, l'ancien directeur général est parti avec deux millions d'indemnités. » « Je reconnais que c'est mieux. [...] Il n'empêche que deux cent cinquante postes restent deux cent cinquante postes. » 상대 논거를 먼저 인정(certes, je reconnais que, je vous l'accorde)한 뒤 반박하는 2단계 구조다. pourtant은 '그런데도'라는 의외성을, il n'empêche que는 '그렇다 해도 사실은 변하지 않는다'는 단호함을 더한다. 둘 다 뒤에 직설법."),
("C1", "quand bien même + 조건법: '설령 ~라 해도'",
 "« Quand bien même vous trouveriez cent volontaires, il en manquerait cent cinquante. » « Quand bien même vous seriez des saints, je ne signerais pas sans garantie sur le site. » même si보다 훨씬 강하고 격식 있는 양보 가정이다. même si 뒤에는 반과거(même si vous trouviez...)를 쓰지만, quand bien même 뒤에는 조건법을 쓰고 주절도 조건법이다. 협상·논쟁에서 '최선의 경우를 가정해도 결론은 같다'고 못 박을 때 쓴다."),
("B2", "대립과 양보의 구분: en revanche / pourtant / alors que",
 "« Je ne le conteste pas [...]. En revanche, c'est à nous de payer leurs factures. » « Elle en avait envie, pourtant. » en revanche(반면에)는 두 사실을 나란히 대조할 뿐 모순이 아니다. pourtant(그런데도)은 앞 내용에서 기대되는 결과와 반대일 때 쓴다. 문장 끝에 놓인 pourtant(« C'était un peu vrai, pourtant. »)은 구어에서 '그래도 말이야'라는 부드러운 반박이 된다."),
("B2", "avoir beau + 부정사: '아무리 ~해도'",
 "« J'ai beau compter dans tous les sens, il manque de l'argent. » avoir beau는 노력이 결과를 바꾸지 못함을 나타낸다. 주절에는 그 '바뀌지 않는 결과'가 온다. 시제는 avoir에 붙인다: J'avais beau lui expliquer, il ne comprenait pas. bien que + 접속법(J'ai beau compter = Bien que je compte...)보다 구어적이고 감정이 실린다."),
("B2", "정중한 반박의 단계: 인정 → 거절 → 대안",
 "인정: « Je ne le conteste pas. » « Vous avez raison, c'était trop tard. » « Je vous l'accorde. » 거절: « Je ne peux pas l'écrire. » « Je refuse de signer une promesse que je sais ne pas pouvoir tenir. » 대안: « Je vous propose ceci : ... » « Je ne vous promets pas le résultat. Je vous promets de me battre. » 노사 협상에서는 상대를 먼저 인정해야 거절이 받아들여진다. refuser de + 부정사, proposer qc à qn 구조에 주의."),
("C1", "quel(le)(s) que soit + 명사: '~가 어떻든'",
 "« zéro licenciement contraint, quelle que soit l'issue du volontariat » quel que는 뒤 명사(issue, 여성 단수)에 성·수를 일치시키고 동사 être는 접속법(soit/soient)으로 쓴다: quels que soient les résultats. 붙여 쓰는 quelque(약간의, 아무리)와 혼동하지 말 것. 계약서·협약문에서 '어떤 경우에도'라는 보장을 표현하는 전형적 문구다."),
("B2", "사과와 화해: en vouloir à / 조건법 과거 / 비교의 허사 ne",
 "« Je n'aurais jamais dû. Pardon. » 조건법 과거 devoir는 '하지 말았어야 했다'는 후회. « Tu m'en veux encore ? » en vouloir à qn(원망하다)의 en은 고정된 일부라 생략할 수 없다. « Tu écouteras plus que tu ne parles. » 우월 비교 뒤 종속절의 ne는 부정이 아닌 허사(ne explétif)로, 격식 있는 문어·연설에서 쓰인다(1화 복습)."),
("B2", "회의록·노사 회의의 격식 문체",
 "« Notez bien ceci au procès-verbal. » « Nous en prenons acte. » « La séance est levée. » « Je propose donc de suspendre la séance. Reprise jeudi prochain, neuf heures. » prendre acte de qc는 '공식적으로 확인하다(동의는 아님)'라는 뜻이라 갈등 상황에서 유용하다. lever la séance(회의를 마치다)와 suspendre la séance(정회하다)를 구분하자. 명사만으로 된 문장(Reprise jeudi)은 회의 공지의 전형이다."),
]

CULTURE = [
("CSE와 노조: '서명'과 '의견'은 다르다",
 "프랑스에서 직원 11명 이상 기업은 직원 대표 기구인 CSE(comité social et économique)를 두며, 50명 이상이면 경제·조직 문제에 대해 정보를 받고 의견(avis)을 낼 권한을 가진다. CSE는 사용자가 주재하고 위원 중에서 서기를 뽑는다. 그러나 단체 협약에 '서명'하는 것은 CSE가 아니라 대표성 있는 노동조합의 노조 대표(délégué syndical)다. 협약이 유효하려면 직원 선거 1차 투표에서 대표성 있는 노조들이 얻은 유효표의 50%를 넘게 대표하는 노조들이 서명해야 한다(과반 원칙). 그래서 제1노조라도 과반이 안 되면 다른 노조들끼리 서명할 수 있지만, 현장의 정당성 문제는 남는다."),
("PSE, RCC, 합의 해지: 프랑스식 구조조정의 세 갈래",
 "직원 50명 이상 기업이 30일 안에 10명 이상을 경제적 사유로 해고하려면 고용보호계획(PSE)을 세워야 한다. CSE와의 협의 기간은 해고 규모에 따라 2~4개월(250명 이상이면 4개월)이며, 노조와의 과반 협약으로 만든 PSE는 지역 노동 행정청(DREETS)의 승인(validation)을, 사용자 단독 문서는 인가(homologation)를 받아야 한다. 1,000명 이상 기업은 재취업 휴가 제안과 지역 고용 재활성화 의무도 진다. 2017년 노동법 개정으로 도입된 집단 합의 해지(RCC)는 해고 없이 자원자만 떠나는 방식으로 과반 협약이 필수다. 개별 합의 해지(rupture conventionnelle)는 원래 개인 간 합의 제도라, 집단 해고 절차를 피하려고 대량으로 쓰면 행정 당국이 문제 삼을 수 있다."),
("파업권과 débrayage",
 "프랑스에서 파업권은 1946년 헌법 전문에 명시된 헌법상의 권리다. 민간 기업 직원은 사전 예고 없이 파업할 수 있고(공공 서비스는 원칙적으로 5일 전 예고 필요), 파업 시간만큼 임금은 지급되지 않는다. 한두 시간만 일을 멈추는 débrayage는 협상 중에 노조가 의지를 보여 주는 대표적 수단이다. 파업 중에도 설비와 인원의 안전은 지켜야 한다는 것이 노사 모두의 상식으로 통한다."),
]
