# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA = "Inès", "Mathieu"
MO, CH, MR, DE, DY = "Momo", "Chazal", "Martine", "Dédé", "Dylan"
ZO, NA, BI, IL = "Zohra", "Nawel", "Bilal", "Ilyes"

META = {
    "part": 2, "ep": 21,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Saint-Étienne",
    "title_ko": "생테티엔",
    "place": "생테티엔 장조레스 광장 장터 · Verdier Industries 본사 · 생테티엔 공장 3번 라인(야간조) · 타랑테즈 지구 모모의 집 · 자카르 지구 이네스의 아파트 / 3월 초, 토요일~수요일",
    "chars": "이네스, 마티외, 모하메드 '모모' 벨카셈(야간조 반장·40년 근속), 로베르 샤잘(생테티엔 공장장), 마르틴 로슈(CEO 비서), 데데(장터 치즈 상인), 딜랑(젊은 설비 조정공), 조라(모모의 아내), 나왈(모모의 딸·간호사), 빌랄(모모의 아들·정비 기술자), 일리에스(모모의 손자)",
    "work": "생테티엔 공장 3번 라인 « La Stéphanoise » — 불량률 평균 6%(주간조 7%·야간조 4%), 연 1,500만 유로의 품질 실패 비용, 압력솥 밸브 공정의 숨은 노하우, 10년 동안 무시된 현장 개선안 47건(불량 40% 감소 가능)",
    "life": "토요일 장터와 생테티엔 축구(les Verts) 이야기, 공장 야간 근무와 새벽 1시의 민트차, 노동자 가족의 쿠스쿠스 저녁과 불안, 늦은 밤 이네스 집에서 털어놓는 감동",
    "focus": "현장 구어체(ne 생략·전위 구문), 존중·공손 표현(sauf votre respect, c'est un honneur), 반과거 회상, si + 대과거 → 조건법 과거, 접속법(sans que, sous réserve que, 최상급 + que), 사역 faire, 기간 표현(ça fait... que, depuis, en), 품질·생산 어휘",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제22화 Le produit de la dernière chance — 이네스의 32번째 생일 아침의 비밀 선물, 그리고 1,500만 유로가 드는 신제품 « Stéphanoise 2 »를 둘러싼 CEO와 CFO의 대립.",
}

D = [
# ---------- 1. Ouverture : le marché de la place Jean-Jaurès ----------
(None, "Un samedi matin, début mars. Place Jean-Jaurès, à Saint-Étienne. Sous un ciel bas, les étals du marché entourent le kiosque à musique. Inès et Mathieu s'arrêtent devant un stand de fromages.",
       "3월 초의 어느 토요일 아침. 생테티엔 장조레스 광장. 낮게 깔린 하늘 아래 장터 좌판들이 음악당을 둘러싸고 있다. 이네스와 마티외가 치즈 좌판 앞에 멈춰 선다."),
(DE, "Bonjour, messieurs-dames, qu'est-ce que je vous sers ? ... Attendez, vous, je vous connais. Vous êtes le nouveau patron de chez Verdier ! Je vous ai vu dans le journal.",
     "안녕하세요, 손님들, 뭘 드릴까요? ...잠깐만, 당신, 내가 아는 얼굴인데. 베르디에 새 사장님이잖아요! 신문에서 봤어요."),
(MA, "Coupable. Mathieu Kessler. Je ne pensais pas qu'on me reconnaîtrait jusqu'au rayon fromages.", "인정합니다. 마티외 케슬레르예요. 치즈 좌판에서까지 알아보실 줄은 몰랐네요."),
(DE, "Ici, Verdier, c'est la famille. Mon père y a fait trente-deux ans, et ma sœur y est encore, à l'emballage. Alors je vous le dis gentiment : faites pas de bêtises, hein.",
     "여기선 베르디에가 곧 가족이에요. 우리 아버지가 거기서 32년을 일했고, 누나는 아직도 포장부에 있어요. 그러니까 좋게 말할 때 들어요. 사고 치지 마요, 네?"),
(MA, "Je ferai de mon mieux, promis. En attendant, qu'est-ce que vous conseillez à un Alsacien qui découvre la Loire ?", "최선을 다할게요, 약속해요. 그건 그렇고, 루아르 지방을 처음 알아 가는 알자스 사람한테 뭘 추천하시겠어요?"),
(DE, "Une fourme de Montbrison, pour commencer. Douce, crémeuse, rien à voir avec les bleus qui piquent. Et ce soir, il y a match au Chaudron. Vous êtes pour les Verts, j'espère ?",
     "우선 몽브리종 푸름이죠. 순하고 크리미해서, 톡 쏘는 블루치즈랑은 전혀 달라요. 그리고 오늘 저녁에 쇼드롱에서 경기가 있어요. 당연히 레 베르 응원하시죠?"),
(MA, "Je suis plutôt Racing de Strasbourg, depuis tout petit... mais je suis prêt à me convertir.", "전 어릴 때부터 스트라스부르 라싱 팬인데... 개종할 준비는 돼 있어요."),
(DE, "On ne se convertit pas, ici, monsieur. On naît vert, foi de Gaga ! Mais pour un patron qui fait son marché, on fera une exception. Et madame, elle est pour qui ?",
     "여기선 개종 같은 거 없어요, 손님. 초록으로 태어나는 거지. 생테티엔 토박이로서 맹세해요! 그래도 장 보러 나온 사장님이니 예외로 쳐 드리죠. 그리고 이쪽 부인은 누구 응원해요?"),
(I, "L'OM. Depuis toujours, et pour toujours.", "마르세유요. 예전부터, 그리고 앞으로도 쭉."),
(DE, "Marseille ! Oh, la pauvre... Bon, je vous sers quand même, mais je ne vous fais pas de prix. Vous êtes ensemble, tous les deux ?",
     "마르세유라니! 아이고, 저런... 뭐, 그래도 팔긴 팔지만 깎아 주진 않을 거예요. 두 분, 같이 사는 사이예요?"),
(MA, "Non, non : collègues. Madame est notre directrice financière. Elle surveille même mes dépenses de fromage.", "아뇨, 아니에요. 동료예요. 이분은 저희 재무이사예요. 제 치즈 값까지 감시하죠."),
(I, "Surtout le fromage. Deux cents grammes, pas plus, monsieur Kessler.", "특히 치즈요. 200그램, 그 이상은 안 돼요, 케슬레르 대표님."),
(None, "Derrière eux, un homme aux cheveux blancs, un filet de poireaux à la main, s'approche en souriant. C'est Mohamed Belkacem, dit Momo.",
       "그들 뒤로 흰머리의 남자가 대파가 든 망을 들고 웃으며 다가온다. 모모라고 불리는 모하메드 벨카셈이다."),
(MO, "Bonjour, patron. Bonjour, madame. L'usine de jour, vous l'avez vue : les cafés, les réunions, les discours. Venez voir l'usine de nuit. Lundi, vingt et une heures, ligne trois. Sans cravate.",
     "안녕하세요, 사장님. 안녕하세요, 이사님. 낮의 공장은 보셨죠. 커피, 회의, 연설. 이제 밤의 공장을 보러 오세요. 월요일 밤 9시, 3번 라인. 넥타이는 빼고요."),
(MA, "Lundi soir, ligne trois. Avec plaisir, Momo. J'apporte quelque chose ?", "월요일 밤, 3번 라인. 기꺼이 가죠, 모모. 뭘 가져갈까요?"),
(MO, "Vos oreilles. Et des chaussures de sécurité.", "귀요. 그리고 안전화."),
(I, "Ouvrez-les en grand, monsieur Kessler. À la machine à café, l'autre jour, Momo ne répétait jamais deux fois.", "귀를 활짝 여세요, 케슬레르 대표님. 지난번 커피 자판기 앞에서도 모모는 같은 말을 두 번 하지 않았어요."),

# ---------- 2. Le problème : la non-qualité ----------
(None, "Lundi, 8 h. Siège de Verdier Industries, cinquième étage. Martine Roche pose sur le bureau de Mathieu un café et la presse locale.",
       "월요일 오전 8시. 베르디에 앵뒤스트리 본사 5층. 마르틴 로슈가 마티외의 책상 위에 커피와 지역 신문을 내려놓는다."),
(MR, "Bonjour, monsieur Kessler. Votre café, et la mauvaise nouvelle du jour : « Verdier : le dialogue social au point mort ». Page trois, avec une photo de Josiane Fabre qui ne sourit pas.",
     "안녕하세요, 대표님. 커피 여기 있고요, 오늘의 나쁜 소식이에요. '베르디에, 노사 대화 교착 상태'. 3면에, 웃지 않는 조지안 파브르 사진까지 실렸어요."),
(MA, "Merci, Martine. Elle ne sourit jamais sur les photos, si ?", "고마워요, 마르틴. 그분은 사진에서 원래 안 웃지 않아요?"),
(MR, "Une fois. Il y a vingt ans, le jour où la direction a renoncé à fermer l'atelier d'emboutissage. Et on dit dans les couloirs que vous étiez au marché samedi, et que Momo vous a invité à la ligne trois.",
     "딱 한 번이요. 20년 전, 경영진이 프레스 성형 작업장 폐쇄를 포기한 날이요. 그리고 복도에선 대표님이 토요일에 장터에 계셨고, 모모가 3번 라인에 초대했다는 말이 돌아요."),
(MA, "À Saint-Étienne, les nouvelles vont plus vite que les TGV.", "생테티엔에선 소문이 TGV보다 빠르네요."),
(MR, "Plus vite que les mails de la direction, en tout cas. Momo est un monsieur. S'il vous invite quelque part, allez-y. Madame Marchetti et monsieur Chazal vous attendent dans la petite salle.",
     "적어도 경영진 이메일보다는 빠르죠. 모모는 신사예요. 그 사람이 어딘가로 초대하면 가세요. 마르케티 이사님과 샤잘 공장장님이 작은 회의실에서 기다리고 계세요."),
(None, "8 h 30. Petite salle de réunion. Robert Chazal, le directeur de l'usine, a apporté un épais dossier. Inès a déjà ouvert son ordinateur.",
       "오전 8시 30분. 작은 회의실. 공장장 로베르 샤잘이 두꺼운 서류철을 가져왔다. 이네스는 이미 노트북을 열어 두었다."),
(MA, "Bonjour à tous. Je serai bref : la négociation avec le CSE reprend jeudi, à neuf heures. Josiane Fabre nous a dit une chose qui m'est restée : « Avant de supprimer des postes, prouvez-nous que vous avez cherché l'argent ailleurs. »",
     "안녕하세요. 짧게 하겠습니다. CSE와의 협상이 목요일 9시에 재개됩니다. 조지안 파브르가 한 말이 계속 머리에 남아 있어요. '일자리를 없애기 전에, 돈을 다른 데서 찾아봤다는 걸 증명하세요.'"),
(I, "Sur la méthode, elle n'a pas tort, même si je maintiens mon analyse. Monsieur Chazal, vous avez les données de qualité que je vous ai demandées ?",
    "방법론으로는 틀린 말이 아니에요. 제 분석은 그대로 유지하지만요. 샤잘 공장장님, 요청드린 품질 데이터 가져오셨나요?"),
(CH, "Les voilà, madame Marchetti. Je vous préviens, ce n'est pas joli. Sur la ligne trois, celle de La Stéphanoise, notre taux de rebut moyen est de six pour cent.",
     "여기 있습니다, 마르케티 이사님. 미리 말씀드리지만 보기 좋진 않습니다. 3번 라인, 그러니까 라 스테파누아즈 라인의 평균 불량률이 6%입니다."),
(MA, "Six pour cent, sur combien de pièces ?", "6%라면, 몇 개 중에서요?"),
(CH, "Trois mille six cents cocottes par jour, en trois équipes. Donc plus de deux cents cocottes par jour qu'il faut retoucher ou jeter. Et le problème vient presque toujours du même endroit : le module soupape, sur le couvercle.",
     "하루 3,600대, 3교대로요. 그러니까 하루에 200대 넘게 손보거나 버려야 한다는 겁니다. 그리고 문제는 거의 항상 같은 데서 나옵니다. 뚜껑에 달린 밸브 모듈이요."),
(I, "Et en euros ? Rebuts, retouches, retours sous garantie, tout compris.", "유로로는요? 폐기, 재작업, 보증 반품까지 전부 포함해서요."),
(CH, "Pour toute l'usine, le coût de la non-qualité tourne autour de quinze millions d'euros par an.", "공장 전체로 보면 품질 실패 비용이 연간 1,500만 유로 안팎입니다."),
(I, "Quinze millions... Nous avons perdu quarante-deux millions l'an dernier. C'est plus d'un tiers de nos pertes.", "1,500만이라... 작년에 우리가 4,200만 유로를 잃었어요. 손실의 3분의 1이 넘네요."),
(CH, "Le couvercle est embouti, on y sertit la soupape, et on teste toute la cocotte sous pression en fin de ligne. Si la soupape fuit, c'est le couvercle entier qui part au rebut ou en retouche.",
     "뚜껑을 프레스로 성형하고, 거기에 밸브를 압착해 끼운 다음, 라인 끝에서 압력솥 전체를 압력 시험합니다. 밸브가 새면 뚜껑 전체가 폐기되거나 재작업으로 갑니다."),
(MA, "Autrement dit, une pièce de quelques euros peut envoyer tout un couvercle à la poubelle.", "다시 말해, 몇 유로짜리 부품 하나 때문에 뚜껑 전체가 쓰레기통으로 갈 수 있다는 거군요."),
(I, "Vous ne testez qu'à la fin ? Pourquoi pas avant le sertissage ?", "끝에서만 시험한다고요? 왜 압착 전에 하지 않죠?"),
(CH, "Parce qu'il faudrait un banc d'essai au milieu de la ligne, et que la ligne a été dessinée comme ça il y a trente ans. Il y a toujours eu d'autres priorités.",
     "라인 중간에 시험대가 있어야 하는데, 라인이 30년 전에 그렇게 설계됐거든요. 늘 다른 우선순위가 있었고요."),
(MA, "Vos chiffres sont-ils les mêmes pour les trois équipes ?", "그 수치가 세 교대조 모두 같습니까?"),
(CH, "... Non. C'est curieux, d'ailleurs. Les deux équipes de jour sont à sept pour cent. L'équipe de nuit est à quatre.",
     "...아니요. 그러고 보니 이상하네요. 주간 두 조는 7%입니다. 야간조는 4%고요."),
(I, "Presque deux fois moins de défauts la nuit ? Il y a moins de volume ?", "밤에는 불량이 거의 절반이라고요? 생산량이 적은가요?"),
(CH, "Même volume : douze cents cocottes par poste. L'équipe de nuit, c'est celle de Momo Belkacem. Quarante ans de maison. Un excellent ouvrier... mais il a des idées sur tout, et il ne respecte pas toujours les procédures.",
     "생산량은 같습니다. 교대당 1,200대요. 야간조는 모모 벨카셈의 조입니다. 40년 근속이죠. 훌륭한 작업자예요... 다만 모든 일에 자기 생각이 있고, 절차를 늘 지키진 않아요."),
(I, "« Des idées sur tout »... Dans un rapport de consultant, on appellerait ça de l'initiative.", "'모든 일에 자기 생각이 있다'라... 컨설팅 보고서였다면 그걸 주도성이라고 불렀을 텐데요."),
(MA, "Quelles procédures ne respecte-t-il pas ?", "어떤 절차를 안 지키나요?"),
(CH, "Il fait chauffer les presses vingt minutes avant de lancer la production, alors que la consigne, c'est dix. Et il a bricolé quelque chose dans un coin de l'atelier. Je ferme les yeux, tant que ses chiffres sont bons.",
     "생산을 시작하기 전에 프레스를 20분 동안 예열해요. 지침은 10분인데요. 그리고 작업장 구석에 뭔가를 직접 만들어 놨어요. 수치가 좋으니까 눈감아 주고 있습니다."),
(I, "Monsieur Chazal, sauf votre respect, on ne ferme pas les yeux sur quelque chose qui divise presque les défauts par deux. On le mesure.",
    "샤잘 공장장님, 실례지만, 불량을 거의 절반으로 줄이는 일에 눈을 감아선 안 됩니다. 측정해야죠."),
(CH, "Vous avez raison, madame. Mais avec les plans d'économies successifs, mes ingénieurs méthodes sont passés de douze à trois. On éteint les incendies ; on n'a plus le temps d'améliorer.",
     "옳은 말씀입니다, 이사님. 하지만 연이은 비용 절감 계획 때문에 생산기술 엔지니어가 열두 명에서 세 명으로 줄었어요. 불 끄기 바쁘지, 개선할 시간은 없습니다."),
(MA, "Alors on va prendre le temps. Ce soir, je vais à l'équipe de nuit. Seul : si le directeur général arrive avec le directeur de l'usine, personne ne parlera.",
     "그럼 시간을 내 봅시다. 오늘 밤 야간조에 가 보겠습니다. 혼자서요. 대표가 공장장이랑 같이 나타나면 아무도 말을 안 할 테니까요."),
(I, "Et moi, je veux le coût de chaque retouche, atelier par atelier, d'ici ce soir. Si on parle de quinze millions, je veux savoir où ils sont.",
    "그리고 저는 오늘 저녁까지 작업장별 재작업 비용을 전부 받고 싶어요. 1,500만 유로라면, 그게 어디에 있는지 알아야겠어요."),
(CH, "Vous l'aurez, madame Marchetti. Et monsieur Kessler... prenez des bouchons d'oreilles. La nuit, les presses font plus de bruit qu'on ne croit.",
     "받으실 겁니다, 마르케티 이사님. 그리고 케슬레르 대표님... 귀마개 챙기세요. 밤엔 프레스 소리가 생각보다 크거든요."),
(I, "Et prenez des notes, monsieur Kessler. Des chiffres, de préférence.", "그리고 메모하세요, 케슬레르 대표님. 가급적이면 숫자로요."),

# ---------- 3. Analyse : le jour et la nuit ----------
(None, "Le même jour, 18 h 30. Bureau d'Inès, porte fermée. Sur l'écran, un tableau couvert de chiffres rouges.",
       "같은 날 저녁 6시 30분. 문이 닫힌 이네스의 사무실. 화면에는 빨간 숫자로 가득한 표가 떠 있다."),
(MA, "Alors, ces quinze millions ? Tu les as trouvés ?", "그래서, 그 1,500만 유로는? 찾았어?"),
(I, "Chazal m'a envoyé le détail. Sur les quinze millions de non-qualité, la ligne trois en représente six à elle seule. Les neuf autres sont éparpillés dans les autres ateliers.",
    "샤잘이 세부 내역을 보냈어. 품질 실패 비용 1,500만 유로 중에 3번 라인 하나가 600만이야. 나머지 900만은 다른 작업장들에 흩어져 있고."),
(MA, "Six millions sur une seule ligne, et presque tout vient de la soupape. Notre fuite à nous, elle est là.", "라인 하나에 600만, 그리고 거의 다 밸브에서 나와. 우리 회사의 '새는 곳'이 바로 거기네."),
(I, "Très drôle. Mais ça ne change rien à l'équation : dans dix jours, on envoie le reporting mensuel à la Banque Rhodanienne, et Marc-Antoine Serre n'a aucun sens de l'humour.",
    "아주 재밌네. 그래도 방정식은 안 바뀌어. 열흘 뒤에 Banque Rhodanienne에 월간 보고서를 보내야 하는데, 마르크앙투안 세르는 유머 감각이 전혀 없거든."),
(MA, "Regarde plutôt l'écart entre le jour et la nuit. Sept pour cent contre quatre. Si les équipes de jour travaillaient comme celle de Momo, on serait à combien ?",
     "그보다 낮과 밤의 차이를 봐. 7% 대 4%. 주간조가 모모네 조처럼 일하면 얼마가 될까?"),
(I, "Toute la ligne passerait de six à quatre pour cent. Un tiers de défauts en moins, donc... à peu près deux millions d'économies par an.",
    "라인 전체가 6%에서 4%로 내려가겠지. 불량이 3분의 1 줄어드니까... 연간 대략 200만 유로 절감."),
(MA, "Deux millions, sans toucher à un seul emploi. Juste en copiant ce qui marche déjà.", "200만 유로, 일자리 하나 건드리지 않고. 이미 잘 되고 있는 걸 따라 하기만 해도."),
(I, "C'est bien, Mathieu. Mais ce n'est pas suffisant. Entre mes quatre cents postes et tes cent cinquante, il y a deux cent cinquante personnes. Au coût complet de quarante-huit mille euros par an, ça fait douze millions.",
    "좋아, 마티외. 그런데 충분하진 않아. 내 400개 일자리와 네 150개 사이엔 250명이 있어. 1인당 연간 총인건비 4만 8천 유로로 치면 1,200만 유로야."),
(MA, "Je sais compter, Inès. Ce qui m'intéresse, c'est autre chose : une équipe fait presque deux fois moins de défauts que les autres depuis des années, sans que personne se demande pourquoi.",
     "나도 계산할 줄 알아, 이네스. 내가 궁금한 건 다른 거야. 한 조가 몇 년째 다른 조보다 불량을 거의 절반만 내는데, 아무도 왜 그런지 묻지 않았다는 거."),
(I, "Chazal te l'a dit : ses ingénieurs méthodes sont passés de douze à trois. Personne n'a le temps.", "샤잘이 말했잖아. 생산기술 엔지니어가 열두 명에서 세 명으로 줄었다고. 아무도 시간이 없는 거야."),
(MA, "Alors le voilà, le vrai coût. On a supprimé ceux qui améliorent, et maintenant on paie la non-qualité. Et la solution qu'on propose, c'est de supprimer encore des gens.",
     "그럼 그게 진짜 비용이야. 개선하는 사람들을 없앴고, 이제 그 대가로 품질 실패 비용을 치르고 있어. 그런데 우리가 내놓는 해법은 또 사람을 없애는 거고."),
(I, "Ce n'est pas « la solution qu'on propose ». C'est ce que la banque, Arcane et nos comptes nous imposent. Je n'aime pas ça plus que toi.",
    "그건 '우리가 내놓는 해법'이 아니야. 은행이랑 아르칸이랑 우리 장부가 강요하는 거지. 나도 너만큼 싫어."),
(MA, "Je ne dis pas que tu aimes ça. Je dis qu'on ne peut pas signer un plan social sans être allés voir ce qui se passe la nuit.", "네가 좋아한다는 게 아니야. 밤에 무슨 일이 벌어지는지 보지도 않고 구조조정 계획에 서명할 순 없다는 거야."),
(I, "Et moi, je dis que l'émotion ne fait pas un business plan.", "그리고 난 감정으로 사업 계획을 짤 순 없다는 거고."),
(MA, "Et un tableur ne fait pas une usine.", "그리고 엑셀로 공장을 돌릴 수도 없지."),
(None, "Un silence. Puis Inès sourit malgré elle.", "침묵. 그러다 이네스가 저도 모르게 미소 짓는다."),
(I, "On s'était promis de se disputer sur les chiffres, jamais sur nous. Règle numéro un.", "숫자로만 싸우고 우리 얘기로는 절대 안 싸우기로 약속했잖아. 규칙 1번."),
(MA, "Mais on se dispute sur les chiffres. C'est un désaccord entre la direction générale et la direction financière. Dans une entreprise, c'est même plutôt sain.",
     "숫자로 싸우고 있잖아. 대표이사와 재무이사 사이의 이견이야. 회사에선 오히려 건전한 일이지."),
(I, "Dans ce cas, la direction financière propose un compromis : tu vas voir la nuit, tu me rapportes des chiffres, et je les mets dans le modèle. Pas des histoires : des chiffres.",
    "그렇다면 재무 부문이 타협안을 내지. 넌 밤의 공장을 보러 가고, 숫자를 가져와. 그럼 내가 그걸 모델에 넣을게. 이야기 말고, 숫자로."),
(MA, "Des chiffres et des histoires. Les deux vont ensemble, tu verras.", "숫자와 이야기. 둘은 같이 가. 두고 봐."),
(None, "On frappe. Martine entre avec une boîte d'archives. Ils s'écartent instinctivement l'un de l'autre.", "노크 소리. 마르틴이 기록 상자를 들고 들어온다. 두 사람이 본능적으로 서로에게서 떨어진다."),
(MR, "Excusez-moi. Madame Marchetti, vous m'aviez demandé les anciens dossiers qualité de l'usine. Je les ai retrouvés à la cave.", "실례합니다. 마르케티 이사님, 공장의 옛 품질 자료를 요청하셨죠. 지하 창고에서 찾아왔어요."),
(I, "Merci, Martine, vous êtes une magicienne. Monsieur Kessler et moi étions justement en train de... comparer nos méthodes.", "고마워요, 마르틴, 마법사시네요. 케슬레르 대표님과 저는 마침... 서로의 방법론을 비교하던 중이었어요."),
(MR, "Je vois ça. Il y a dix ans, un directeur d'usine avait lancé des « cercles qualité ». Une fois par mois, les ouvriers proposaient des améliorations. Et puis il est parti, et les cercles sont partis avec lui.",
     "그런 것 같네요. 10년 전에 한 공장장이 '품질 분임조'를 만들었어요. 한 달에 한 번 작업자들이 개선안을 냈죠. 그런데 그분이 떠나자 분임조도 같이 사라졌어요."),
(MA, "Et les propositions, qu'est-ce qu'elles sont devenues ?", "그럼 그 제안들은 어떻게 됐나요?"),
(MR, "Ça, monsieur Kessler, il faudra le demander à Momo. Demandez-lui ce qu'est devenu son classeur bleu. Bonne soirée à vous deux.",
     "그건 모모한테 물어보셔야 해요, 대표님. 그 사람의 파란 바인더가 어떻게 됐는지 물어보세요. 두 분 모두 좋은 저녁 되세요."),
(I, "« Bonne soirée à vous deux »... Tu crois qu'elle sait ?", "'두 분 모두 좋은 저녁'이라... 저분이 알고 있는 것 같아?"),
(MA, "Martine sait tout. Elle était là avant nous, elle sera là après nous. Mais elle ne dira rien.", "마르틴은 다 알아. 우리보다 먼저 여기 있었고, 우리가 떠난 뒤에도 있을 사람이야. 하지만 아무 말도 안 할 거야."),
(I, "Un classeur bleu... Tu me raconteras. Et mets un pull : la nuit, dans les ateliers, il fait cru.", "파란 바인더라... 나중에 얘기해 줘. 그리고 스웨터 입어. 밤에 작업장은 으슬으슬하대."),
(MA, "« Il fait cru » ? Tu parles déjà comme le fromager du marché.", "'으슬으슬하다'? 벌써 장터 치즈 아저씨처럼 말하네."),
(I, "Je m'adapte, c'est mon métier. Allez, file. Et Mathieu... écoute-les vraiment.", "적응하는 게 내 일이야. 자, 어서 가. 그리고 마티외... 그분들 말 진짜로 들어."),
(MA, "Promis. Et toi, ne reste pas trop tard avec tes tableaux rouges.", "약속할게. 그리고 넌 빨간 표 붙들고 너무 늦게까지 있지 마."),

# ---------- 4. Terrain : la nuit sur la ligne trois ----------
(None, "Lundi, 21 h. Usine de Saint-Étienne, ligne trois. Le battement des presses, l'odeur d'huile chaude. Momo, en bleu de travail, attend Mathieu à l'entrée de l'atelier.",
       "월요일 밤 9시. 생테티엔 공장 3번 라인. 프레스가 쿵쿵 울리고 뜨거운 기름 냄새가 난다. 작업복 차림의 모모가 작업장 입구에서 마티외를 기다리고 있다."),
(MO, "Vingt et une heures pile. C'est bien, vous êtes à l'heure. Mettez ce casque antibruit et suivez-moi. Ici, on se tutoie tous, sauf avec le patron. Vous, on verra.",
     "9시 정각. 좋아요, 제시간에 오셨네. 이 방음 귀마개 쓰고 따라오세요. 여기선 다들 반말해요. 사장님만 빼고. 사장님은 두고 봐야죠."),
(MA, "Vouvoyez-moi tant que vous voudrez, Momo, mais montrez-moi tout.", "존댓말은 원하는 만큼 하세요, 모모. 대신 전부 보여 주세요."),
(MO, "D'abord, les presses. On les fait tourner à vide vingt minutes. La consigne dit dix. Mais la tôle, elle n'aime pas le froid. Une presse froide, ça vous donne un couvercle qui n'est pas tout à fait rond.",
     "먼저 프레스요. 20분 동안 빈 상태로 돌려요. 지침엔 10분이라고 돼 있죠. 그런데 철판은 추운 걸 싫어해요. 차가운 프레스로 찍으면 뚜껑이 완전히 둥글게 안 나와요."),
(MA, "Et ça, c'est écrit quelque part ?", "그건 어디 적혀 있나요?"),
(MO, "C'est écrit là-dedans. Et dans la tête des anciens. Le papier, lui, il dit dix minutes. ... Dylan, viens dire bonsoir ! Le patron est venu voir comment on bosse.", "여기 안에 적혀 있죠. 그리고 고참들 머릿속에. 종이에는 10분이라고 쓰여 있고요. ...딜랑, 와서 인사드려! 사장님이 우리 일하는 거 보러 오셨어."),
(DY, "Bonsoir, monsieur. On s'est vus à la machine à café. Euh... vous venez nous compter ?", "안녕하세요, 대표님. 커피 자판기 앞에서 뵀었죠. 어... 저희 머릿수 세러 오신 거예요?"),
(MA, "Non, Dylan. Je viens apprendre. Ça fait combien de temps que vous êtes sur cette ligne ?", "아니요, 딜랑. 배우러 왔어요. 이 라인에서 일한 지 얼마나 됐어요?"),
(DY, "Trois ans. Momo m'a tout appris. Avant, je ne savais même pas ce que c'était, une soupape.", "3년이요. 모모가 다 가르쳐 줬어요. 전엔 밸브가 뭔지도 몰랐어요."),
(MO, "Justement, la soupape. C'est là que tout se joue. Un ressort, un poids, un petit trou. Ressort trop dur, la pression monte trop. Trop mou, ça siffle tout le temps et la cliente croit que sa cocotte est cassée.",
     "그러니까 밸브요. 승부는 거기서 나요. 스프링 하나, 추 하나, 작은 구멍 하나. 스프링이 너무 세면 압력이 너무 올라가요. 너무 약하면 계속 칙칙거려서 손님은 압력솥이 고장 난 줄 알죠."),
(MA, "Et la machine ne règle pas ça toute seule ?", "그건 기계가 알아서 조절하지 않나요?"),
(MO, "La machine règle à peu près. Moi, je finis à l'oreille. Écoutez... Celle-là chante juste. Celle-ci... elle chante faux.", "기계는 대충 맞춰요. 마무리는 제가 귀로 하고요. 들어 보세요... 이건 음이 맞아요. 이건... 음이 틀렸네요."),
(MA, "Honnêtement, je n'entends aucune différence.", "솔직히 전혀 차이를 모르겠어요."),
(MO, "Normal. Il m'a fallu dix ans. Dylan l'entend déjà, lui. Hein, Dylan ?", "당연하죠. 전 10년 걸렸어요. 딜랑은 벌써 들어요. 그렇지, 딜랑?"),
(DY, "Un peu, chef. Celle de droite, elle siffle un poil trop aigu.", "조금은요, 반장님. 오른쪽 거가 살짝 너무 높게 울려요."),
(MA, "Et ce petit banc, avec le manomètre ? Il n'est pas sur les plans de la ligne.", "그리고 압력계가 달린 이 작은 시험대는요? 라인 도면엔 없던데요."),
(MO, "Ça ? Un vieux compresseur, un manomètre et deux tuyaux. Je l'ai monté moi-même. On teste chaque soupape avant de la sertir sur le couvercle. Et on sertit dans l'autre sens : d'abord le joint, ensuite le corps. Si elle est mauvaise, on jette un ressort à trois euros, pas un couvercle entier.",
     "이거요? 낡은 컴프레서 하나, 압력계 하나, 호스 두 개. 제가 직접 만들었어요. 밸브를 뚜껑에 압착하기 전에 하나하나 시험해요. 그리고 압착 순서를 반대로 해요. 먼저 패킹, 그다음 몸체. 불량이면 뚜껑 전체가 아니라 3유로짜리 스프링 하나만 버리면 되죠."),
(MA, "Voilà vos quatre pour cent. Les équipes de jour n'ont pas le droit de faire pareil ?", "그게 4%의 비결이군요. 주간조는 똑같이 하면 안 되나요?"),
(MO, "Les équipes de jour ont la procédure, et la procédure dit : on teste à la fin. Moi, je me suis fait sortir deux fois du bureau du chef à cause de ce banc. Alors je le garde la nuit, quand les costumes dorment. Sauf votre respect.",
     "주간조한텐 절차가 있고, 절차엔 끝에서 시험하라고 돼 있죠. 전 이 시험대 때문에 두 번이나 상사 사무실에서 쫓겨났어요. 그래서 밤에, 양복쟁이들이 잘 때만 쓰는 거예요. 실례되는 말이지만요."),
(MA, "Il n'y a pas d'offense. Un vrai banc, aux normes, ça coûterait combien ?", "실례될 거 없어요. 규격에 맞는 제대로 된 시험대는 얼마나 할까요?"),
(MO, "Il en faudrait deux pour toute la ligne. Quarante mille euros pièce, à peu près. Le mien, il m'a coûté des pièces de récupération et quelques samedis.", "라인 전체에 두 대는 있어야 해요. 한 대에 4만 유로쯤. 제 건 고물 부품이랑 토요일 몇 번 들었죠."),
(None, "1 h du matin. Pause. Dans un coin de l'atelier, Momo sert du thé à la menthe d'un vieux thermos.", "새벽 1시. 휴식 시간. 작업장 한쪽 구석에서 모모가 낡은 보온병에 든 민트차를 따른다."),
(MO, "Quand j'étais petit, mon père descendait au puits Couriot. Il rentrait noir de charbon, il ne parlait pas. Il disait juste : « Toi, tu feras un métier propre. » Quand je suis entré chez Verdier, on était plus de trois mille rien qu'ici. Le chef d'atelier connaissait le prénom de tout le monde. Quand on avait une idée, on la lui disait à la cantine, et le lundi, on essayait.",
     "어릴 때 아버지는 쿠리오 탄광 갱도로 내려가셨어요. 석탄 때문에 새까매져서 돌아오셨고, 말씀이 없으셨죠. 그냥 이렇게만 하셨어요. '넌 깨끗한 일을 해라.' 제가 베르디에에 들어왔을 땐 여기만 3천 명이 넘었어요. 작업반장은 모든 사람 이름을 알았죠. 아이디어가 생기면 구내식당에서 말했고, 월요일엔 해 봤어요."),
(MA, "Et aujourd'hui ?", "그럼 지금은요?"),
(MO, "Aujourd'hui, on a des formulaires. Et les formulaires, ça finit dans les tiroirs. ... Bon. Mercredi, vous venez manger à la maison ? Zohra fait un couscous. Elle veut voir à quoi ressemble un patron qui vient la nuit.",
     "지금은 서식이 있죠. 그리고 서식은 서랍 속에서 끝나요. ...자. 수요일에 저희 집에 식사하러 오실래요? 조라가 쿠스쿠스를 해요. 밤에 공장에 오는 사장이 어떻게 생겼는지 보고 싶대요."),
(MA, "Ce serait un honneur, Momo. Mercredi, je serai là.", "영광이죠, 모모. 수요일에 꼭 갈게요."),
(MO, "Vingt heures. Et ne venez pas avec des fleurs : venez avec de l'appétit.", "저녁 8시요. 꽃은 가져오지 말고, 식욕을 가져오세요."),

# ---------- 5. Décision : le couscous et le classeur bleu ----------
(None, "Mercredi, 20 h. Quartier de Tarentaize, quatrième étage sans ascenseur. Une grande table, une nappe brodée, une odeur de cumin et de légumes mijotés.",
       "수요일 저녁 8시. 타랑테즈 지구, 엘리베이터 없는 5층. 큰 식탁, 수놓은 식탁보, 쿠민과 뭉근히 끓인 채소 냄새."),
(ZO, "Entrez, entrez, monsieur Kessler ! Donnez-moi votre manteau. Vous avez monté les quatre étages à pied ? Asseyez-vous, vous devez mourir de faim.",
     "들어오세요, 어서요, 케슬레르 대표님! 외투 이리 주세요. 계단을 걸어서 올라오셨어요? 앉으세요, 배고파 죽겠죠."),
(MA, "Bonsoir, madame Belkacem. Merci de me recevoir chez vous, c'est un vrai honneur. Momo m'a interdit les fleurs, alors j'ai fait un kouglof. Une recette de ma grand-mère.",
     "안녕하세요, 벨카셈 부인. 댁에 초대해 주셔서 감사합니다. 정말 영광이에요. 모모가 꽃은 안 된다고 해서 쿠겔호프를 구워 왔어요. 저희 할머니 레시피예요."),
(MO, "Zohra, laisse-le respirer. Monsieur Kessler, ma fille Nawel, infirmière au CHU. Mon fils Bilal, technicien de maintenance chez nous, de jour. Et mon petit-fils Ilyes, le fils de Nawel.",
     "조라, 숨 좀 쉬게 놔둬. 케슬레르 대표님, 제 딸 나왈이에요. 대학병원 간호사고요. 제 아들 빌랄, 우리 공장 정비 기술자예요. 주간조고요. 그리고 손자 일리에스, 나왈 아들이에요."),
(IL, "C'est vrai que vous êtes le chef de mon papi ? Vous êtes pour les Verts ?", "진짜 우리 할아버지 대장이에요? 레 베르 응원해요?"),
(MA, "Depuis samedi, oui. Ton grand-père et le fromager du marché ne m'ont pas laissé le choix.", "토요일부터는 그래. 너희 할아버지랑 장터 치즈 아저씨가 선택권을 안 주더라."),
(IL, "Alors vous êtes des nôtres.", "그럼 우리 편이네요."),
(ZO, "Servez-vous, servez-vous. Semoule, légumes, pois chiches, bouillon... Ne soyez pas timide : chez nous, une assiette vide, c'est que la cuisinière a raté quelque chose.",
     "드세요, 어서 드세요. 세몰리나, 채소, 병아리콩, 국물... 사양하지 마세요. 우리 집에선 접시가 비어 있으면 요리한 사람이 뭔가 잘못한 거예요."),
(MA, "Alors je vais faire très attention à ce qu'elle reste pleine. C'est délicieux, madame.", "그럼 접시가 비지 않게 아주 조심할게요. 정말 맛있어요, 부인."),
(NA, "Monsieur Kessler, je vais être directe, c'est mon métier qui veut ça. Vous allez supprimer combien de postes ?", "케슬레르 대표님, 직설적으로 여쭐게요. 제 직업이 그래서요. 일자리를 몇 개나 없애실 거예요?"),
(MA, "C'est une question légitime, Nawel. Je ne vous donnerai pas un chiffre ce soir, mais je ne vous mentirai pas non plus. Ce que je veux, c'est en supprimer le moins possible, et d'abord par des départs volontaires.",
     "정당한 질문이에요, 나왈. 오늘 밤 숫자를 드리진 않겠지만, 거짓말도 하지 않을게요. 제가 원하는 건 가능한 한 적게 줄이는 것, 그리고 먼저 자발적 퇴직으로 하는 거예요."),
(BI, "Tous les patrons disent ça. J'ai vu deux plans sociaux depuis que je suis entré. À chaque fois, on nous a dit « le moins possible ». À chaque fois, des collègues sont partis. Et il faut que vous l'entendiez, papa ne vous le dira pas : ma femme attend notre deuxième enfant, on vient d'acheter, avec un crédit sur vingt ans. Si je perds ma place, on fait comment ?",
     "사장들은 다 그렇게 말해요. 전 입사하고 구조조정을 두 번 봤어요. 매번 '가능한 한 적게'라고 했죠. 그리고 매번 동료들이 떠났어요. 그리고 이건 들으셔야 해요. 아버지는 말 안 하실 테니까요. 제 아내가 둘째를 가졌고, 20년 대출로 막 집을 샀어요. 제가 일자리를 잃으면 어떻게 하죠?"),
(MA, "Je comprends, Bilal. Et je préfère l'entendre ici, à cette table, que dans un tract.", "이해해요, 빌랄. 그리고 전단지에서보다 여기, 이 식탁에서 듣는 게 나아요."),
(NA, "Le pire, c'est de ne pas savoir. Papa ne dort plus, même les jours où il ne travaille pas.", "제일 힘든 건 모른다는 거예요. 아빠는 일 안 하는 날에도 잠을 못 주무세요."),
(MA, "Je vous promets une chose, Nawel : vous ne l'apprendrez pas par le journal. Les salariés sauront avant la presse, et Momo avant tout le monde.", "한 가지는 약속할게요, 나왈. 신문으로 알게 되시는 일은 없을 거예요. 직원들이 언론보다 먼저 알게 될 거고, 모모는 누구보다 먼저 알게 될 거예요."),
(MO, "Ça suffit. Monsieur Kessler n'est pas venu se faire juger. Mais puisqu'on parle franchement... Bilal, va me chercher le classeur. Le bleu, dans le placard.",
     "그만해. 케슬레르 대표님은 심판받으러 오신 게 아니야. 그래도 솔직하게 말하는 김에... 빌랄, 그 바인더 좀 가져와라. 파란 거, 벽장 안에."),
(None, "Bilal revient avec un gros classeur bleu, usé aux coins. Momo le pose à côté du plat de couscous.", "빌랄이 모서리가 닳은 두꺼운 파란 바인더를 들고 돌아온다. 모모가 그것을 쿠스쿠스 접시 옆에 내려놓는다."),
(MO, "Quarante-sept fiches d'amélioration, écrites par l'équipe de nuit en dix ans. Chacune envoyée à la direction. Lisez les réponses.", "개선 제안서 마흔일곱 장. 야간조가 10년 동안 쓴 거예요. 한 장 한 장 다 경영진에 보냈어요. 답장을 읽어 보세요."),
(MA, "« Pas prioritaire. » « Pas de budget cette année. » « À revoir l'an prochain. » ... Et la fiche douze : « Tester la soupape avant sertissage, inverser l'ordre de sertissage. Avec les fiches sept et vingt-trois, réduction estimée des défauts de l'usine : quarante pour cent. »",
     "'우선순위 아님.' '올해 예산 없음.' '내년에 재검토.' ...그리고 12번 제안서. '압착 전 밸브 시험, 압착 순서 반대로. 7번·23번 제안과 함께 시행 시 공장 불량 예상 감소율: 40%.'"),
(MO, "La douze, je l'ai envoyée trois fois. À trois directeurs différents. La première fois, Bilal était encore au lycée.", "12번은 세 번이나 보냈어요. 서로 다른 공장장 세 명한테요. 처음 보냈을 땐 빌랄이 아직 고등학생이었죠."),
(MA, "Dix ans... Si on vous avait écoutés à l'époque, l'entreprise aurait économisé des dizaines de millions. Et on n'en serait peut-être pas à parler de plan social.",
     "10년이라니... 그때 여러분 말을 들었다면 회사는 수천만 유로를 아꼈을 거예요. 그리고 지금 구조조정 얘기까지 하고 있진 않았을지도 모르죠."),
(NA, "Alors pourquoi personne ne les a écoutés ?", "그럼 왜 아무도 안 들은 거예요?"),
(MO, "Parce qu'un ouvrier qui a une idée, ça dérange. Les chefs changent tous les trois ans. Les idées des ouvriers, elles, elles restent dans le classeur.",
     "아이디어가 있는 노동자는 불편하거든. 상사들은 3년마다 바뀌고. 노동자들 아이디어는 바인더 속에 그대로 남는 거지."),
(BI, "Et vous, monsieur Kessler, la vraie question, c'est pas combien vous allez en supprimer. C'est : qu'est-ce qu'on va fabriquer, demain ?",
     "그리고 대표님, 진짜 질문은 몇 명을 줄이느냐가 아니에요. 우린 내일 뭘 만들게 되느냐예요."),
(MA, "Vous avez raison, Bilal. Momo, je ne vais pas vous faire de promesse en l'air. Mais je vous propose quelque chose : demain matin, la négociation reprend avec le CSE. Venez avec ce classeur, et présentez-le vous-même.",
     "맞는 말이에요, 빌랄. 모모, 빈말은 하지 않을게요. 대신 제안 하나 할게요. 내일 아침 CSE와 협상이 재개돼요. 이 바인더를 들고 와서 직접 발표해 주세요."),
(MO, "Moi, devant la direction et devant Josiane ? Je suis ouvrier, pas orateur. ... Et si je viens, j'ai trois conditions. Un : c'est l'équipe qui présente, pas un consultant qui recopie nos idées avec des couleurs. Deux : aucun nom de mon équipe sur une liste à cause d'une fiche. Trois : si ça marche, ce sont les nôtres qui forment les équipes de jour.",
     "제가요, 경영진이랑 조지안 앞에서요? 전 노동자지 연설가가 아니에요. ...그리고 간다면, 조건이 세 개 있어요. 첫째, 발표는 우리 조가 해요. 우리 아이디어를 색깔만 입혀 베끼는 컨설턴트 말고요. 둘째, 제안서 때문에 우리 조 사람 이름이 명단에 오르는 일은 없어야 해요. 셋째, 효과가 있으면 주간조 교육은 우리 사람들이 해요."),
(MA, "Accordé, accordé et accordé. Et j'en ajoute une : on installe les deux vrais bancs d'essai sur la ligne trois. Sous réserve que ma directrice financière trouve l'argent.",
     "수락, 수락, 그리고 수락. 그리고 하나 더할게요. 3번 라인에 제대로 된 시험대 두 대를 설치합니다. 재무이사가 돈을 찾아낸다는 조건으로요."),
(ZO, "Elle le trouvera ?", "그분이 찾아낼까요?"),
(MA, "Elle trouve toujours. Parfois, elle me fait souffrir avant, mais elle trouve.", "늘 찾아내요. 가끔 그 전에 절 엄청 괴롭히지만, 결국 찾아내요."),
(ZO, "Hmm. Vous parlez d'elle comme mon Momo parle de moi. Vous êtes marié, monsieur Kessler ?", "흠. 우리 모모가 제 얘기 할 때랑 똑같은 말투로 그분 얘기를 하시네요. 결혼하셨어요, 대표님?"),
(MA, "Euh... non. Pas marié.", "어... 아니요. 결혼은 안 했어요."),
(ZO, "Mais il y a quelqu'un. Ça se voit, vous savez. Une femme sait ces choses-là. Allez, reprenez du couscous, et après, thé et cornes de gazelle.",
     "그래도 누가 있네요. 다 보여요. 여자는 그런 걸 알아요. 자, 쿠스쿠스 더 드세요. 그다음엔 차랑 코른 드 가젤이에요."),

# ---------- 6. Le soir : quartier Jacquard ----------
(None, "23 h 30. Quartier Jacquard. Mathieu frappe deux petits coups à la porte d'Inès. Elle ouvre, en pull, Figaro dans les bras.",
       "밤 11시 30분. 자카르 지구. 마티외가 이네스의 집 문을 두 번 가볍게 두드린다. 스웨터 차림의 이네스가 피가로를 안고 문을 연다."),
(I, "Tu sens le cumin et le thé à la menthe. Alors, ce dîner ?", "쿠민이랑 민트차 냄새가 나. 그래서, 저녁은 어땠어?"),
(MA, "Inès... Je n'avais pas mangé à une table comme ça depuis Colmar. Trois générations, tout le monde qui parle en même temps, et une grand-mère qui te ressert trois fois sans demander.",
     "이네스... 콜마르 이후로 그런 식탁에서 밥을 먹어 본 적이 없었어. 3대가 같이 앉아서 다들 한꺼번에 말하고, 묻지도 않고 세 번이나 더 덜어 주는 할머니까지."),
(I, "Tu es ému, Strasbourg.", "감동받았구나, 스트라스부르."),
(MA, "Un peu. Le fils m'a dit des choses dures. Il avait raison de les dire. Sa femme attend un deuxième enfant, ils viennent d'acheter... Ce n'est pas une ligne dans ton tableau, c'est une cuisine avec des dessins d'enfant sur le frigo.",
     "조금. 아들이 나한테 아픈 말을 했어. 그렇게 말할 만했어. 아내가 둘째를 가졌고, 막 집을 샀대... 그건 네 표의 한 줄이 아니라, 냉장고에 아이 그림이 붙은 부엌이야."),
(I, "Je sais que ce n'est pas une ligne. C'est pour ça que je dors mal, moi aussi. Raconte. Le banc, la nuit, le classeur ?", "한 줄이 아니라는 거 알아. 그래서 나도 잠을 잘 못 자는 거고. 얘기해 봐. 시험대, 야간조, 바인더."),
(MA, "Quarante-sept fiches en dix ans, toutes refusées ou oubliées. Avec le banc d'essai, l'ordre de sertissage, la chauffe des presses et la formation au tarage, ils estiment qu'on peut baisser les défauts de l'usine de quarante pour cent.",
     "10년 동안 제안서 마흔일곱 장, 전부 거절되거나 잊혔어. 시험대, 압착 순서, 프레스 예열, 밸브 조정 교육까지 하면 공장 불량을 40% 줄일 수 있다고 봐."),
(I, "Attends... Quarante pour cent de quinze millions : six millions par an. Au coût complet de quarante-huit mille euros, six millions, c'est l'équivalent de cent vingt-cinq postes.",
    "잠깐... 1,500만의 40%면 연간 600만 유로. 1인당 총인건비 4만 8천 유로로 치면, 600만은 일자리 125개에 해당해."),
(MA, "Cent vingt-cinq. La moitié de l'écart entre toi et moi.", "125개. 너랑 나 사이 차이의 딱 절반이네."),
(I, "Si — et je dis bien si — les chiffres de Momo tiennent sur la ligne, je retire mes quatre cents. Et on peut viser cent cinquante, presque uniquement en volontaires. Je ne te le promets pas : je te promets de refaire le calcul honnêtement.",
    "만약에, 정말 만약에 모모의 숫자가 라인에서 그대로 나오면, 내 400은 철회할게. 그리고 거의 전부 자원자로 150을 목표로 할 수 있어. 약속은 못 해. 대신 정직하게 다시 계산하겠다는 건 약속해."),
(MA, "C'est tout ce que je demande. Il faut deux bancs d'essai : quatre-vingt mille euros.", "내가 바라는 건 그게 다야. 시험대 두 대가 필요해. 8만 유로."),
(I, "Quatre-vingt mille euros pour six millions par an ? C'est le meilleur investissement que j'aie vu depuis que je suis arrivée ici. Je les trouve demain matin.",
    "연 600만 유로를 위해 8만 유로? 여기 온 뒤로 본 것 중에 최고의 투자야. 내일 아침에 찾아낼게."),
(MA, "Zohra m'a demandé si j'étais marié. J'ai dit non. Elle a dit : « Mais il y a quelqu'un, ça se voit. »", "조라가 결혼했냐고 물었어. 아니라고 했지. 그랬더니 '그래도 누가 있네요, 다 보여요'래."),
(I, "Et tu as répondu quoi ?", "그래서 뭐라고 했어?"),
(MA, "Rien. Qu'est-ce que je pouvais dire ? Que c'est compliqué ? J'ai repris du couscous. Mais j'ai pensé à toi toute la soirée.", "아무 말도. 뭐라고 하겠어? 복잡하다고? 쿠스쿠스를 더 먹었어. 그런데 저녁 내내 네 생각을 했어."),
(I, "Ce n'est pas compliqué, tu sais. C'est secret. Nuance.", "복잡한 거 아니야. 비밀일 뿐이지. 차이가 있어."),
(None, "Il sort de sa poche le vieux marqueur vert et écrit au dos d'une enveloppe, sous les calculs d'Inès.", "그가 주머니에서 낡은 초록 마커를 꺼내 봉투 뒷면, 이네스의 계산 아래에 적는다."),
(MA, "Quel est le vrai problème ? Ce n'est pas le nombre de postes. C'est que, depuis dix ans, on n'écoute pas ceux qui savent.", "진짜 문제는 무엇인가? 일자리 숫자가 아니야. 10년 동안 아는 사람들의 말을 듣지 않았다는 거야."),
(I, "Qui décide ? Nous, au final. Mais demain, c'est Momo qui parle le premier. Et que fait-on lundi ?", "누가 결정하는가? 결국엔 우리지. 하지만 내일은 모모가 먼저 말해. 그럼 월요일엔 뭘 하지?"),
(MA, "Lundi, c'est trop loin. Demain, neuf heures, on retourne à la table du CSE avec le classeur bleu. Et ce soir... je peux rester ?", "월요일은 너무 멀어. 내일 9시에 파란 바인더를 들고 CSE 테이블로 돌아가는 거야. 그리고 오늘 밤은... 있어도 돼?"),
(I, "Figaro t'a déjà gardé ta place. ... Qui t'écrit à minuit, d'ailleurs ? Ton téléphone n'arrête pas de vibrer.", "피가로가 벌써 네 자리 맡아 놨어. ...그런데 자정에 누가 문자를 해? 휴대폰이 계속 진동하잖아."),
(MA, "Personne. Un fournisseur. Allez, viens, il est tard.", "아무도 아니야. 거래처야. 자, 들어가자, 늦었어."),
(None, "Sur l'écran, avant qu'il le retourne : un message de Lucas, depuis Marseille. « Pour le stylo, c'est bon. Elle se doute de rien ? »",
       "그가 휴대폰을 뒤집기 전, 화면에 마르세유의 뤼카가 보낸 메시지가 보인다. '만년필 준비 끝. 누나는 눈치 못 챘지?'"),
]

VOCAB = [
("B2", "Coupable.", "(농담조) 인정합니다, 맞아요", "plaider coupable(유죄를 인정하다)에서 온 익살스러운 대답. 정체를 들켰을 때 « Coupable ! »"),
("B1", "les Verts / le Chaudron", "AS 생테티엔의 애칭 / 홈구장 조프루아기샤르의 별명", "초록 유니폼에서 온 이름. « Allez les Verts ! »가 응원 구호. le chaudron = 가마솥(열기)."),
("B2", "un Gaga / foi de Gaga", "생테티엔 토박이 / 생테티엔 사람으로서 맹세코", "le gaga는 생테티엔 지역 사투리 이름이기도 하다. foi de + 명사 = '~의 명예를 걸고'(foi de Marseillaise)."),
("B2", "faire un prix (à qn)", "(누구에게) 값을 깎아 주다", "Je ne vous fais pas de prix. 시장·흥정에서. faire une fleur(호의를 베풀다)와 비슷한 상황."),
("B1", "Il fait cru.", "(습하고) 으슬으슬 춥다", "리옹·생테티엔 등 동남부 지방에서 흔한 표현. 기온보다 '뼛속까지 스미는 습한 추위'."),
("B2", "être au point mort", "교착 상태다, 진전이 없다", "원래 기어의 '중립'. Les négociations sont au point mort. ↔ redémarrer, débloquer."),
("B2", "le taux de rebut / mettre au rebut", "불량률(폐기율) / 폐기 처분하다", "rebut = 쓸모없어 버리는 것. partir au rebut / en retouche(재작업으로 가다)."),
("C1", "le coût de la non-qualité", "품질 실패 비용", "폐기·재작업·보증 반품·고객 이탈 등 품질 문제로 생기는 모든 비용. 제조업 핵심 지표."),
("B2", "un retour sous garantie", "보증 기간 내 반품(AS 반품)", "être sous garantie = 보증 기간 중이다. la garantie légale de conformité는 법정 2년."),
("B2", "sertir / le sertissage", "(금속 부품을) 압착해 끼우다 / 압착 공정", "보석 세팅(sertir un diamant)에도 쓰는 말. inverser l'ordre de sertissage."),
("B2", "une soupape / le tarage", "밸브 / (스프링·밸브의) 압력 조정", "tarer un ressort = 스프링의 세기를 맞추다. La soupape siffle = 밸브에서 김이 빠지며 소리 나다."),
("B2", "un banc d'essai", "시험대, 테스트 벤치", "비유적으로 '시험 무대'. servir de banc d'essai à une idée."),
("B2", "fermer les yeux sur qc", "~을 눈감아 주다", "알면서 모른 척하다. ↔ ne rien laisser passer."),
("B2", "éteindre les incendies", "(급한) 불을 끄다", "급한 문제 처리에만 매달리는 상황. jouer les pompiers도 같은 뜻."),
("C1", "un ingénieur méthodes", "생산기술(공정) 엔지니어", "공정·작업 방법을 설계·개선하는 직무. le service méthodes."),
("C1", "le coût complet (d'un poste)", "(일자리 하나의) 총인건비", "급여 + 사회보장 분담금 등을 모두 포함한 비용. coût chargé라고도 한다."),
("B1", "un casque antibruit / des chaussures de sécurité", "방음 귀마개(헤드폰형) / 안전화", "공장 방문의 기본 보호 장비(EPI: équipement de protection individuelle)."),
("B2", "chanter juste / chanter faux", "음정이 맞다 / 음정이 틀리다", "모모는 밸브 소리에 비유. avoir l'oreille = 귀가 밝다."),
("B2", "bricoler / des pièces de récupération", "(손수) 뚝딱 만들다, 손보다 / 재활용 부품, 고물 부품", "le bricolage = DIY. de la récup' (구어 축약)."),
("B2", "Sauf votre respect", "외람되지만, 실례지만", "윗사람에게 반대 의견이나 거친 말을 꺼낼 때 앞이나 뒤에 붙이는 공손한 완충 표현."),
("B2", "être des nôtres", "우리 편이다, 우리 일행이다", "Vous serez des nôtres ce soir ? = 오늘 저녁 함께하시겠어요?"),
("B2", "une promesse en l'air", "빈말, 지키지 못할 약속", "en l'air = 근거 없이. parler en l'air."),
("B2", "sous réserve que + 접속법 / sous réserve de + 명사", "~라는 조건으로", "계약·협상 문체. sous réserve que ma directrice financière trouve l'argent."),
("B1", "reprendre de qc / resservir qn", "(음식을) 더 먹다 / 더 덜어 주다", "Reprenez du couscous ! Je vous ressers ? 프랑스 가정 식사의 필수 표현."),
]

GRAM = [
("B2", "반과거 회상: 습관·배경 vs 복합과거",
 "« Quand j'étais petit, mon père descendait au puits Couriot. Il rentrait noir de charbon, il ne parlait pas. » « Quand on avait une idée, on la lui disait à la cantine, et le lundi, on essayait. » 과거에 반복되던 습관과 배경은 반과거로 그린다. 반면 한 번 일어난 사건은 복합과거: « Je l'ai monté moi-même. » « La douze, je l'ai envoyée trois fois. » (횟수가 정해지면 반복이라도 복합과거.) 회상 이야기에서 반과거가 '그 시절의 풍경', 복합과거가 '줄거리'를 맡는다."),
("B2", "si + 대과거 → 조건법 과거 / 조건법 현재 (비현실 가정)",
 "« Si on vous avait écoutés à l'époque, l'entreprise aurait économisé des dizaines de millions. Et on n'en serait peut-être pas à parler de plan social. » 과거 사실에 반대되는 가정은 si + 대과거. 결과가 과거면 조건법 과거(aurait économisé), 결과가 지금까지 이어지면 조건법 현재(on n'en serait pas)를 쓴다. 후회·비판에 자주 쓰이는 혼합 구문이다."),
("B2", "현장 구어체: ne 생략·전위·ça",
 "« faites pas de bêtises » « c'est pas combien vous allez en supprimer » → 구어에서는 부정의 ne가 자주 빠진다. 전위(dislocation): « La tôle, elle n'aime pas le froid. » « Le papier, lui, il dit dix minutes. » « Les idées des ouvriers, elles, elles restent dans le classeur. » 주제를 먼저 내세우고 대명사로 다시 받는 것은 말하기의 대표적 특징이다. 사람에게도 ça를 쓴다: « un ouvrier qui a une idée, ça dérange. »"),
("B2", "존중·공손 표현",
 "« Merci de me recevoir chez vous, c'est un vrai honneur. » « Ce serait un honneur, Momo. »(조건법으로 더 정중하게) « Monsieur Chazal, sauf votre respect, on ne ferme pas les yeux... » « Il n'y a pas d'offense. » 상대의 직함·성(monsieur Chazal, madame Belkacem)을 부르며 말하고, 반대 의견 앞에 sauf votre respect, je vous l'accorde 같은 완충어를 둔다. 노동자에게도 vous를 유지하는 마티외의 말투 자체가 존중의 표현이다."),
("B2", "접속법: sans que / sous réserve que / il faut que / 최상급 + que",
 "« sans que personne se demande pourquoi » « Sous réserve que ma directrice financière trouve l'argent. » « Et il faut que vous l'entendiez, papa ne vous le dira pas » « C'est le meilleur investissement que j'aie vu. » sans que, sous réserve que, il faut que 뒤에는 접속법. 최상급(le meilleur, le seul, le premier) 뒤의 관계절에서도 주관적 평가를 나타낼 때 접속법을 쓴다(que j'aie vu). sans que 뒤의 허사 ne는 문어에서 붙이기도 하지만 personne와 함께라면 생략하는 것이 바르다."),
("B2", "사역 faire + 부정사",
 "« Il fait chauffer les presses vingt minutes. » « On les fait tourner à vide. » « Parfois, elle me fait souffrir avant, mais elle trouve. » « je me suis fait sortir deux fois du bureau du chef » faire + 부정사 = '~하게 하다'. 대명사 목적어는 faire 앞에 온다(on les fait tourner). se faire + 부정사는 '(불쾌한 일을) 당하다'라는 수동의 의미: se faire sortir(쫓겨나다), se faire juger(심판받다)."),
("B1", "기간 표현: ça fait... que / depuis / en / il y a",
 "« Ça fait combien de temps que vous êtes sur cette ligne ? » « une équipe fait deux fois moins de défauts depuis des années » « Quarante-sept fiches [...] en dix ans » « Il y a dix ans, un directeur d'usine avait lancé des cercles qualité. » ça fait + 기간 + que와 depuis는 '지금까지 계속', en + 기간은 '걸린 시간·기간 안에', il y a + 기간은 '~ 전에'(과거 시점)."),
("B2", "제한·강조: rien que / ne... que / le moins possible",
 "« on était plus de trois mille rien qu'ici » « Vous ne testez qu'à la fin ? » « en supprimer le moins possible » rien que = '~만 해도'(놀라움을 담은 강조), ne... que = '~만, ~밖에'(제한). le moins possible / le plus possible은 '가능한 한 적게/많이'. 여기서 en은 앞의 postes를 받는다(en supprimer = 일자리를 줄이다)."),
]

CULTURE = [
("생테티엔: 탄광과 공장의 도시",
 "생테티엔은 19세기부터 석탄 탄광, 무기 제조, 리본 직조, 자전거 산업으로 성장한 프랑스의 대표적 공업 도시다. 무기·자전거 통신판매로 유명했던 Manufrance는 프랑스 최초의 자전거 브랜드 중 하나(Hirondelle)를 만들었다. 마지막 탄광들이 문을 닫은 뒤 옛 쿠리오 갱(puits Couriot)은 탄광 박물관이 되었다. 탄광과 공장에는 이탈리아·폴란드·북아프리카 등지에서 온 이주 노동자가 많았고, 쿠스쿠스가 프랑스인이 가장 좋아하는 요리 중 하나로 꼽히는 것도 이런 이주의 역사와 무관하지 않다. 토박이를 Gagas, 지역 말씨를 le gaga라고 부르며, 장조레스 광장의 장터는 도심의 대표적인 시장이다."),
("AS 생테티엔과 « les Verts »",
 "AS 생테티엔(ASSE)은 프랑스 리그 우승 10회를 기록한 명문 구단으로, 초록 유니폼 때문에 « les Verts »라고 불린다. 홈구장 스타드 조프루아기샤르는 뜨거운 응원 열기 때문에 « le Chaudron »(가마솥)이라는 별명을 가졌다. 1976년 글래스고에서 열린 유럽 챔피언스컵 결승에서 바이에른 뮌헨에 0:1로 졌는데, 슛이 당시 각진 골대(poteaux carrés)에 맞아 나온 일화는 지금도 전설처럼 회자된다. 인근 리옹(OL)과의 경기는 '론알프 더비'로 불리는 라이벌전이다."),
("프랑스의 야간 근무와 교대제",
 "프랑스 노동법은 원칙적으로 21시부터 6시 사이의 노동을 야간 노동으로 보며, 단체협약으로 자정~5시를 포함한 9시간 구간을 달리 정할 수 있다. 야간 노동은 예외적이어야 하고 경제·사회적 필요로 정당화되어야 하며, 야간 노동자에게는 보상 휴식(repos compensateur)이 의무이고 임금 가산은 협약에 따라 정해진다. 건강 검진 등 의료 관리도 강화된다. 제조업에서는 하루를 세 조가 8시간씩 나누는 3교대(les trois-huit)가 흔하며, 같은 라인이라도 교대조마다 작업 습관이 달라 품질 차이가 생기는 일이 많다."),
]
