# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H = "Inès", "Mathieu", "Hélène"
SA, LA, MR, RC = "Samia", "Laure", "Martine", "Robert"
MO, JF, HV, AU, CL = "Momo", "Josiane", "Hubert", "Aubry", "Claire"

META = {
    "part": 2, "ep": 23,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Rançongiciel",
    "title_ko": "랜섬웨어",
    "place": "생테티엔 자쿠아르 지구 이네스의 아파트 · Verdier Industries 본사 위기 대응실 · 생테티엔 공장 « La Stéphanoise » 작업장 / 5월, 금요일 밤부터 월요일 밤까지 72시간",
    "chars": "이네스, 마티외, 사미아 아다드(정보보안 책임자), 로르 퐁타넬(홍보 이사), 마르틴 로슈(CEO 비서), 로베르 샤잘(생테티엔 공장장), 모하메드 '모모' 벨카셈(숙련공), 조지안 파브르(노조 대표·CSE 서기), 위베르 베르디에(이사회 의장), 프레데리크 오브리(아르칸 캐피털), 클레르 베르디에(이사), 엘렌 바쇠르(사외이사)",
    "work": "랜섬웨어 공격 — 세 공장 시스템 암호화와 몸값 800만 유로 요구, 지불 거부, ANSSI 신고·고소·CNIL 통지, 오프라인 백업으로 복구, 종이로 이어 간 생산, 직원·은행·이사회와의 위기 커뮤니케이션",
    "life": "파리행 주말 가방을 풀고 따로 출근하기, 72시간 동안 서로 먹이고 재우기, 소파에서 잠든 마티외와 담요 한 장",
    "focus": "위기 커뮤니케이션 어휘, 사이버 보안 기본 어휘(chiffrer, sauvegarde, fuite de données), 명령법과 대명사 위치, que + 접속법(3인칭 명령), 부정 표현(aucun, personne, ni), 전미래, 긴박한 구어체(생략·전위)",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제24화 Négocier avec Shenzhen — 시차 때문에 새벽 3시에 깬 선전의 호텔 방, 그리고 홍다 일렉트릭 장웨이와의 단가·품질 협상.",
}

D = [
# ---------- 1. Ouverture : vendredi soir ----------
(None, "Un vendredi de mai, 22 h 50. Saint-Étienne, quartier Jacquard, l'appartement d'Inès. Une valise ouverte pour le week-end à Paris. Figaro dort sur le pull de Mathieu.",
       "5월의 어느 금요일 밤 10시 50분. 생테티엔 자쿠아르 지구, 이네스의 아파트. 파리에서 보낼 주말을 위해 열어 둔 여행 가방. 피가로가 마티외의 스웨터 위에서 자고 있다."),
(I, "Figaro s'est installé sur ton pull. Tu peux lui dire adieu pour le week-end.", "피가로가 네 스웨터에 자리 잡았어. 주말 동안은 작별 인사해."),
(MA, "Il a enfin choisi son camp. Des mois de négociations, et voilà le résultat.", "드디어 내 편을 골랐네. 몇 달간 협상한 끝에 이런 성과라니."),
(I, "Le TGV est à sept heures douze. Si tu rates celui-là, je pars sans toi.", "TGV는 7시 12분이야. 그거 놓치면 너 두고 간다."),
(MA, "Je ne rate jamais un train. Je rate seulement les chats qui essaient de me mordre.", "난 기차는 절대 안 놓쳐. 날 물려고 하는 고양이만 놓치지."),
(None, "23 h 05. Le téléphone de Mathieu vibre. À l'écran : « Samia Haddad — Sécurité informatique ».", "밤 11시 5분. 마티외의 휴대폰이 진동한다. 화면에는 '사미아 아다드 — 정보보안'."),
(MA, "Samia ? À cette heure-ci... Allô ? Oui, je vous écoute.", "사미아? 이 시간에... 여보세요? 네, 말씀하세요."),
(SA, "Monsieur Kessler, pardon de vous déranger. Nous subissons une attaque. Un rançongiciel. Tous les écrans des trois usines affichent le même message.",
     "케슬레르 대표님, 늦게 죄송합니다. 공격을 받고 있습니다. 랜섬웨어예요. 세 공장의 모든 화면에 같은 메시지가 떠 있습니다."),
(MA, "Quel message ? Lisez-le-moi.", "무슨 메시지요? 읽어 주세요."),
(SA, "« Vos fichiers ont été chiffrés. » Ils exigent huit millions d'euros en bitcoins, sous soixante-douze heures. Sinon, ils publient des données qu'ils disent avoir volées. La double extorsion classique.",
     "'당신의 파일은 암호화되었다.' 72시간 안에 비트코인으로 800만 유로를 요구합니다. 안 그러면 훔쳤다는 데이터를 공개하겠다고요. 전형적인 이중 갈취예요."),
(MA, "Huit millions... Qu'est-ce que vous avez déjà fait ?", "800만... 지금까지 어떤 조치를 하셨죠?"),
(SA, "J'ai fait couper les connexions à Internet et isoler les sites les uns des autres. Surtout, que personne n'éteigne les machines ni ne touche à rien : on a besoin des traces. Il faut que vous veniez au siège.",
     "인터넷 연결을 끊고 사업장끼리도 서로 격리하게 했습니다. 무엇보다 아무도 기계를 끄거나 손대지 않게 해야 해요. 흔적이 필요하거든요. 본사로 와 주셔야겠습니다."),
(MA, "J'arrive dans vingt minutes. Je préviens moi-même Madame Marchetti.", "20분 안에 가겠습니다. 마르케티 이사님께는 제가 직접 알리죠."),
(None, "Il raccroche. Inès est déjà en train de mettre ses chaussures.", "그가 전화를 끊는다. 이네스는 벌써 신발을 신고 있다."),
(I, "« Je préviens moi-même Madame Marchetti. » Elle est prévenue, Madame Marchetti. Huit millions ?", "'마르케티 이사님께는 제가 직접 알리죠.' 마르케티 이사님은 이미 알고 계십니다. 800만이라고?"),
(MA, "Huit millions, soixante-douze heures, trois usines à l'arrêt. On part séparément ?", "800만, 72시간, 공장 세 곳 정지. 따로 나가?"),
(I, "Évidemment. Toi d'abord, moi dans dix minutes. Je défais la valise : Paris attendra.", "당연하지. 너 먼저, 난 10분 뒤에. 가방은 풀게. 파리는 기다려 주겠지."),
(MA, "Prends un pull, alors. Les nuits de crise sont toujours plus froides qu'on ne croit.", "그럼 스웨터 챙겨. 위기의 밤은 늘 생각보다 추워."),

# ---------- 2. La nuit au siège ----------
(None, "23 h 40. Siège de Verdier Industries. La salle du conseil est devenue salle de crise. Sur les écrans, un message rouge. Samia et deux techniciens travaillent sur des ordinateurs portables jamais branchés au réseau.",
       "밤 11시 40분. Verdier Industries 본사. 이사회 회의실이 위기 대응실로 바뀌었다. 화면마다 빨간 메시지. 사미아와 기술자 두 명이 회사 네트워크에 한 번도 연결된 적 없는 노트북으로 작업하고 있다."),
(MA, "Samia, faites-nous un point. Ce qu'on sait, et ce qu'on ne sait pas.", "사미아, 상황 정리 부탁해요. 아는 것과 모르는 것."),
(SA, "Ce qu'on sait : vers vingt-deux heures, un logiciel malveillant s'est déclenché en même temps sur la plupart de nos serveurs. L'ERP, le système de production, la messagerie, les dossiers partagés : tout est chiffré.",
     "아는 것: 밤 10시쯤 악성 프로그램이 대부분의 서버에서 동시에 실행됐습니다. ERP, 생산 시스템, 메일, 공유 폴더까지 전부 암호화됐어요."),
(I, "Les trois usines ?", "공장 세 곳 다요?"),
(SA, "Saint-Étienne, Roanne et Wrocław. Les machines elles-mêmes fonctionnent, mais plus personne ne peut lancer un ordre de fabrication, imprimer une étiquette ou éditer un bon de livraison.",
     "생테티엔, 로안, 브로츠와프 전부요. 기계 자체는 돌아가지만, 이제 아무도 작업 지시를 내리거나 라벨을 출력하거나 납품서를 발행할 수 없습니다."),
(MA, "Et ce qu'on ne sait pas ?", "그럼 모르는 것은요?"),
(SA, "Par où ils sont entrés, depuis quand ils sont là, et ce qu'ils ont réellement emporté. Ces groupes restent parfois des semaines dans un réseau avant de frapper.",
     "어디로 들어왔는지, 언제부터 있었는지, 실제로 무엇을 가져갔는지요. 이런 조직은 공격하기 전에 몇 주씩 네트워크 안에 머물기도 합니다."),
(I, "Et les sauvegardes ?", "백업은요?"),
(SA, "Les sauvegardes en ligne ont été effacées. Mais nous avons les copies hors ligne, déconnectées du réseau chaque nuit. La dernière date de jeudi, deux heures du matin. Elles sont intactes, je viens de vérifier.",
     "온라인 백업은 지워졌습니다. 하지만 매일 밤 네트워크에서 분리해 두는 오프라인 사본이 있어요. 마지막 사본은 목요일 새벽 2시 것이고, 손상되지 않았습니다. 방금 확인했어요."),
(I, "Les copies hors ligne... celles que vous m'avez fait financer cet hiver en me disant que c'était une assurance ?", "오프라인 사본이라... 이번 겨울에 보험 같은 거라면서 저한테 예산 받아 간 그거요?"),
(SA, "Celles-là. Je ne pensais pas avoir raison aussi vite.", "바로 그거요. 제가 이렇게 빨리 옳았다는 게 증명될 줄은 몰랐네요."),
(MA, "Donc on peut tout reconstruire sans eux ?", "그럼 저들 없이 전부 복구할 수 있다는 거죠?"),
(SA, "Oui, mais pas en appuyant sur un bouton. Il faut d'abord comprendre l'attaque, sinon on restaure des systèmes encore infectés et on recommence dans une semaine. Je compte quatre à cinq jours.",
     "네, 하지만 버튼 하나로 되는 일은 아닙니다. 먼저 공격을 이해해야 해요. 안 그러면 아직 감염된 시스템을 복원했다가 일주일 뒤에 처음부터 다시 하게 됩니다. 4~5일로 봅니다."),
(MA, "Qui doit être prévenu, et quand ?", "누구에게, 언제 알려야 하죠?"),
(SA, "L'ANSSI, cette nuit : je les ai déjà alertés, ils peuvent nous orienter vers des prestataires qualifiés. Notre assureur, qui a une équipe de réponse à incident. Et il faut porter plainte.",
     "ANSSI는 오늘 밤에요. 이미 알렸고, 자격을 갖춘 대응 업체를 안내해 줄 수 있습니다. 그리고 사고 대응팀이 있는 보험사. 또 고소를 해야 합니다."),
(I, "La plainte, c'est urgent pour une autre raison : notre police cyber ne joue que si on porte plainte dans les soixante-douze heures. Je m'en occupe à la première heure.",
    "고소는 다른 이유로도 급해요. 우리 사이버 보험은 72시간 안에 고소해야만 보장돼요. 제가 아침 일찍 처리하겠습니다."),
(SA, "Et s'ils ont vraiment volé des données personnelles — des fiches de paie, des dossiers du personnel —, la CNIL doit être notifiée dans les soixante-douze heures, elle aussi.",
     "그리고 정말로 개인정보를 훔쳤다면, 급여명세서나 인사 파일 같은 거요, CNIL에도 72시간 안에 통지해야 합니다."),
(MA, "Soixante-douze heures pour les pirates, pour l'assureur, pour la CNIL... Tout le monde s'est donné le mot.", "해커도 72시간, 보험사도, CNIL도 72시간... 다들 짜기라도 한 것 같네요."),
(None, "Laure Fontanel entre, un manteau jeté sur un pyjama, son ordinateur personnel sous le bras.", "로르 퐁타넬이 잠옷 위에 코트를 걸친 채 개인 노트북을 옆구리에 끼고 들어온다."),
(LA, "Pardon pour la tenue, on m'a tirée du lit. Mon ordinateur personnel fonctionne, c'est déjà ça. Qui est au courant à l'extérieur ?",
     "옷차림 죄송해요, 자다가 끌려 나왔어요. 개인 노트북은 되니까 그나마 다행이죠. 외부에선 누가 알고 있나요?"),
(MA, "Personne, pour l'instant. Mais à six heures, l'équipe du matin arrive à Saint-Étienne et trouve des écrans rouges.", "아직은 아무도요. 하지만 6시에 생테티엔에 아침 근무조가 와서 빨간 화면을 보게 될 겁니다."),
(LA, "Alors il faut leur parler avant qu'ils ne parlent entre eux. Sans messagerie, on fait comment ? Des SMS ?", "그럼 직원들끼리 이야기하기 전에 우리가 먼저 말해야 해요. 메일 없이 어떻게 하죠? 문자로요?"),
(I, "Les numéros de portable sont dans le logiciel des ressources humaines... chiffré, j'imagine.", "휴대폰 번호는 인사 시스템에 있는데... 암호화됐겠죠."),
(SA, "Chiffré, oui.", "암호화됐습니다."),
(None, "0 h 30. Martine Roche arrive avec un thermos et un carton.", "새벽 0시 30분. 마르틴 로슈가 보온병과 상자 하나를 들고 도착한다."),
(MR, "Bonsoir tout le monde. Du café. Et ceci : l'annuaire interne, version papier. Je le mets à jour à la main tous les ans depuis vingt ans. Personne ne m'a jamais dit merci.",
     "다들 안녕하세요. 커피예요. 그리고 이거, 사내 전화번호부 종이판이에요. 20년째 매년 손으로 업데이트하고 있죠. 고맙다는 말은 아무도 안 했지만요."),
(MA, "Martine, je vous dis merci. Officiellement, et devant témoins.", "마르틴, 제가 고맙다고 말씀드릴게요. 공식적으로, 증인들 앞에서."),
(LA, "Parfait. Je propose un message court aux chefs d'équipe, par téléphone, avant six heures, et une affiche à l'entrée des usines. Et rien à la presse tant qu'on ne sait pas ce qui a fui.",
     "완벽해요. 6시 전에 조장들에게 전화로 짧은 메시지를 전하고, 공장 입구에 공지를 붙이죠. 그리고 무엇이 유출됐는지 알기 전까지 언론에는 아무 말도 하지 않고요."),
(I, "Et si la presse l'apprend avant nous ? Trois usines, quatre mille deux cents personnes : ça ne tiendra pas jusqu'à lundi.", "언론이 우리보다 먼저 알면요? 공장 세 곳에 4,200명이에요. 월요일까지 못 버텨요."),
(LA, "Vous avez raison. Je prépare une déclaration d'attente : on confirme l'incident, on dit ce qu'on fait, et on ne promet rien qu'on ne puisse tenir. Surtout pas « aucune donnée n'a été volée ».",
     "맞는 말씀이에요. 대기 성명을 준비할게요. 사고를 확인하고, 무엇을 하고 있는지 말하고, 지킬 수 없는 건 아무것도 약속하지 않는 거죠. 특히 '도난된 데이터는 없다'는 절대 안 돼요."),
(MA, "Faites ça. Robert, vous m'entendez ? Vos équipes peuvent produire sans le système ?", "그렇게 하세요. 로베르, 들리세요? 공장 팀이 시스템 없이 생산할 수 있겠어요?"),
(RC, "Produire, oui. Savoir quoi produire, c'est une autre histoire. Mais j'ai une idée. Elle a soixante et un ans et elle s'appelle Momo.",
     "생산은 할 수 있죠. 뭘 생산할지 아는 건 또 다른 문제고요. 그런데 생각이 하나 있어요. 그 생각은 예순한 살이고 이름은 모모예요."),
(MA, "Appelez-le. Rendez-vous à l'usine à six heures.", "그분께 전화하세요. 6시에 공장에서 봅시다."),

# ---------- 3. Analyse : payer ou non ----------
(None, "Samedi, 4 h du matin. Bureau du directeur général, porte fermée. Dans la salle d'à côté, on entend les techniciens taper sur leurs claviers.",
       "토요일 새벽 4시. 대표이사실, 문은 닫혀 있다. 옆방에서 기술자들이 자판을 두드리는 소리가 들린다."),
(I, "Tu as mangé quelque chose depuis hier soir ? Non. Tiens. Le distributeur ne prend plus les cartes, mais il prend encore les pièces.", "어젯밤부터 뭐 좀 먹었어? 안 먹었지. 자. 자판기가 카드는 안 받는데 동전은 아직 받더라."),
(MA, "Même le distributeur fonctionne en mode dégradé... Merci. Inès, il faut qu'on parle des huit millions.", "자판기까지 비상 모드네... 고마워. 이네스, 800만 이야기를 해야 해."),
(I, "On ne paie pas.", "안 내."),
(MA, "Je sais. Mais je veux qu'on ait fait le raisonnement jusqu'au bout. Au conseil, Aubry posera la question, et il voudra des chiffres, pas des principes.", "알아. 그래도 끝까지 따져 봤으면 해. 이사회에서 오브리가 물어볼 거고, 원칙이 아니라 숫자를 원할 거야."),
(I, "Alors voilà les chiffres. Verdier fait environ deux millions de chiffre d'affaires par jour. Si on produit sur papier à soixante pour cent, on perd à peu près huit cent mille euros de ventes par jour, dont une partie se rattrapera.",
    "그럼 숫자 말해 줄게. Verdier는 하루 매출이 약 200만 유로야. 종이로 60% 생산하면 하루에 대략 80만 유로어치 매출을 잃고, 그중 일부는 나중에 만회돼."),
(MA, "Sur cinq jours ?", "5일이면?"),
(I, "Tout compris — ventes perdues, experts, heures supplémentaires, transports en urgence —, l'attaque nous coûtera autour de cinq millions. L'assurance en couvre trois, à condition qu'on ait porté plainte à temps.",
    "전부 합쳐서, 놓친 매출, 전문가 비용, 초과 근무, 긴급 운송까지, 이번 공격 비용은 500만 유로 안팎이야. 제때 고소만 하면 보험이 그중 300만을 보장해."),
(MA, "Deux millions nets, contre huit. Le calcul est vite fait.", "순비용 200만 대 800만. 계산은 금방 끝나네."),
(I, "Et même si on payait, on devrait quand même tout restaurer. Une clé de déchiffrement, ce n'est pas une baguette magique : Samia dit qu'elles sont lentes, parfois incomplètes. On paierait huit millions pour gagner peut-être un jour.",
    "게다가 돈을 내더라도 어차피 전부 복원해야 해. 복호화 키는 요술 지팡이가 아니야. 사미아 말로는 느리고 가끔 불완전하대. 800만을 내고 기껏해야 하루를 버는 거지."),
(MA, "Et les données ? S'ils publient les fiches de paie, les arrêts maladie, les adresses de quatre mille deux cents personnes... Ces gens ne nous ont rien demandé.",
     "데이터는? 저들이 4,200명의 급여명세서, 병가 기록, 주소를 공개하면... 그 사람들은 우리한테 아무것도 부탁한 적 없잖아."),
(I, "Payer ne les empêchera pas de publier. On aurait la parole de criminels, c'est tout. Et on finirait sur la liste de ceux qui paient, ceux qu'on attaque une deuxième fois.",
    "돈을 낸다고 공개를 막을 수 있는 것도 아니야. 범죄자의 약속을 얻을 뿐이지. 그리고 돈 내는 회사 명단에 오르겠지. 두 번째로 공격당하는 회사들 말이야."),
(MA, "Je ne dis pas qu'il faut payer. Je dis que je comprends ceux qui paient. Quand on regarde un écran rouge à minuit, on comprend beaucoup de choses.",
     "돈을 내야 한다는 게 아니야. 돈 내는 사람들이 이해된다는 거지. 자정에 빨간 화면을 보고 있으면 많은 게 이해돼."),
(I, "Moi aussi. Mais si on paie, on finance la prochaine attaque, peut-être contre un hôpital. Et huit millions, c'est plus de la moitié de ce que Yann demandait pour la Stéphanoise 2. Je préfère les mettre dans une cocotte que dans la poche de bandits.",
    "나도 그래. 하지만 돈을 내면 다음 공격 자금을 대 주는 거야. 어쩌면 병원을 노리는 공격일 수도 있고. 그리고 800만이면 얀이 스테파누아즈 2에 달라던 돈의 절반이 넘어. 그 돈은 도둑들 주머니보다 압력솥에 넣고 싶어."),
(MA, "D'accord. Décision : on ne paie pas, on ne négocie pas. Mais on ne ment à personne non plus.", "좋아. 결정: 돈은 안 내고, 협상도 안 해. 하지만 누구에게도 거짓말은 안 해."),
(I, "Ça, c'est le terrain de Laure. Et le mien, pour la banque.", "그건 로르의 영역이고. 은행 쪽은 내 영역이야."),
(MA, "La banque ? Un samedi ?", "은행? 토요일에?"),
(I, "Notre accord avec la Banque Rhodanienne nous oblige à signaler tout événement significatif. Si Marc-Antoine Serre l'apprend par le journal avant de l'entendre de ma bouche, on perd en une matinée trois mois de confiance.",
    "방크 로다니엔과의 약정상 중대한 사건은 전부 알려야 해. 마르크앙투안 세르가 내 입으로 듣기 전에 신문으로 알게 되면, 석 달 동안 쌓은 신뢰를 오전 한나절에 잃는 거야."),
(MA, "Appelle-le à neuf heures. Et ensuite, tu dors deux heures.", "9시에 전화해. 그다음엔 두 시간 자고."),
(I, "Je dormirai quand Samia aura relancé l'ERP.", "사미아가 ERP를 다시 돌리고 나면 잘게."),
(MA, "Inès. Tu m'as souvent reproché de retarder les décisions. Toi, ton défaut, c'est de ne rien lâcher à personne. Samia tient la salle de crise, Laure la communication. Laisse-les faire leur métier.",
     "이네스. 넌 내가 결정을 미룬다고 자주 탓했지. 네 약점은 아무것도 남에게 맡기지 않는 거야. 사미아가 위기 대응실을, 로르가 커뮤니케이션을 맡고 있어. 그 사람들이 자기 일을 하게 둬."),
(I, "... Deux heures. Pas une minute de plus. Et toi ?", "...두 시간. 1분도 더는 안 돼. 너는?"),
(MA, "Moi, à six heures, je suis à l'usine. Les gens doivent voir le patron quand ça va mal, pas seulement quand il coupe un ruban.", "난 6시에 공장에 가. 직원들은 일이 잘못될 때 사장을 봐야 해. 테이프 커팅할 때만 말고."),
(None, "On frappe. Samia et Laure entrent. Inès recule d'un pas ; Mathieu se redresse.", "노크 소리. 사미아와 로르가 들어온다. 이네스는 한 걸음 물러서고, 마티외는 자세를 고친다."),
(SA, "Du nouveau. Il y a bien eu des transferts sortants anormaux mardi et mercredi, depuis un serveur des ressources humaines. On ne sait pas encore ce qu'il contenait exactement.",
     "새로운 소식입니다. 화요일과 수요일에 인사팀 서버에서 비정상적인 외부 전송이 실제로 있었어요. 그 서버에 정확히 뭐가 있었는지는 아직 모릅니다."),
(MA, "Donc des données ont probablement fui. Madame Marchetti, la notification à la CNIL ?", "그러니까 데이터가 유출됐을 가능성이 크군요. 마르케티 이사님, CNIL 통지는요?"),
(I, "Je la lance avec le juriste dès ce matin, Monsieur Kessler. Nous la compléterons au fur et à mesure de l'enquête.", "오늘 아침 법무 담당과 바로 진행하겠습니다, 케슬레르 대표님. 조사가 진행되는 대로 보완하겠습니다."),
(LA, "Alors on change de message. On ne dit plus « nous vérifions » : on dit aux salariés que leurs données ont peut-être été copiées, et on leur explique quoi faire. Se méfier des faux mails, de l'hameçonnage, des faux appels de la banque...",
     "그럼 메시지를 바꿔야죠. '확인 중입니다'가 아니라, 직원들에게 데이터가 복사됐을 수 있다고 말하고 어떻게 해야 하는지 설명해야 해요. 가짜 메일, 피싱, 은행을 사칭한 전화를 조심하라고요..."),
(MA, "Dites-le tel quel. Je préfère qu'on nous reproche d'avoir été trop francs que trop prudents.", "그대로 말하세요. 너무 조심했다는 비난보다 너무 솔직했다는 비난을 듣는 게 낫습니다."),
(LA, "Et à l'extérieur, une seule voix. Si un journaliste appelle un chef d'atelier, il répond : « Adressez-vous à la direction de la communication. » Rien d'autre.",
     "그리고 외부에는 한 목소리로만. 기자가 작업장 반장에게 전화하면 '홍보실에 문의하세요'라고만 답하는 거예요. 그 이상은 없어요."),
(SA, "Dernière chose : les pirates ont laissé une adresse pour « discuter ». Personne ne leur écrit. Personne. Pas même pour gagner du temps.", "마지막으로, 해커들이 '대화'하자며 연락처를 남겼어요. 아무도 답장하지 마세요. 아무도요. 시간을 벌려는 목적이라도요."),
(MA, "Personne ne leur écrira. Vous avez ma parole, et celle de Madame Marchetti.", "아무도 답하지 않을 겁니다. 제가 약속하죠. 마르케티 이사님도요."),

# ---------- 4. Terrain : l'usine sur papier ----------
(None, "Samedi, 6 h. Usine de Saint-Étienne, atelier « La Stéphanoise ». Sur chaque écran, une feuille scotchée : « NE PAS ÉTEINDRE — NE PAS TOUCHER ». Des tableaux blancs ont été sortis des bureaux.",
       "토요일 오전 6시. 생테티엔 공장, '라 스테파누아즈' 작업장. 화면마다 '끄지 마시오 — 손대지 마시오'라고 쓴 종이가 테이프로 붙어 있다. 사무실에서 화이트보드들을 꺼내 왔다."),
(RC, "Monsieur Kessler. Toute l'équipe du matin est là. Je leur ai dit ce qu'on savait, c'est-à-dire pas grand-chose.", "케슬레르 대표님. 아침 근무조 전원 나왔습니다. 아는 걸 말해 줬어요. 그러니까 별로 없다는 거죠."),
(MA, "C'est déjà honnête. Comment on produit, sans ordres de fabrication ?", "그것만으로도 정직한 거죠. 작업 지시 없이 어떻게 생산하죠?"),
(MO, "Comme avant, patron. Jusqu'en 1998, il n'y avait pas un ordinateur dans cet atelier. On avait les fiches cartonnées, le planning au tableau, et la mémoire.",
     "옛날처럼요, 사장님. 1998년까지 이 작업장엔 컴퓨터가 한 대도 없었어요. 카드 장부, 칠판에 쓴 계획표, 그리고 기억력이 있었죠."),
(MA, "Et ce matin, la mémoire, c'est vous.", "그리고 오늘 아침엔 그 기억력이 바로 모모 씨군요."),
(MO, "Moi et trois ou quatre anciens. Les commandes de la semaine, Robert les avait imprimées jeudi pour sa réunion. Une chance.", "저랑 고참 서너 명이요. 이번 주 주문은 로베르가 목요일 회의 때문에 출력해 뒀어요. 운이 좋았죠."),
(RC, "Je les imprime toujours. Les jeunes cadres se moquaient de moi. Ce matin, ils ne se moquent plus.", "난 항상 출력해요. 젊은 관리자들이 날 놀렸죠. 오늘 아침엔 아무도 안 놀리네요."),
(MA, "Combien pouvez-vous sortir, à la main ?", "수작업으로 얼마나 만들 수 있어요?"),
(MO, "Six cocottes sur dix, à peu près. Ce ne sont pas les mains qui manquent, c'est le papier : chaque série, chaque contrôle, il faut tout noter. Et après, quelqu'un devra tout ressaisir.",
     "열 개 중 여섯 개쯤요. 부족한 건 손이 아니라 종이예요. 생산 묶음마다, 검사마다 전부 적어야 하거든요. 그리고 나중에 누군가 그걸 전부 다시 입력해야 하고요."),
(MA, "On s'en occupera quand le système reviendra. Pour l'instant, produisez, et notez tout.", "시스템이 돌아오면 그때 처리하죠. 지금은 생산하고, 전부 기록해 주세요."),
(None, "Josiane Fabre traverse l'atelier, son badge du CSE autour du cou.", "조지안 파브르가 CSE 배지를 목에 건 채 작업장을 가로질러 온다."),
(JF, "Monsieur le directeur général. Les salariés veulent savoir une chose : est-ce que leurs fiches de paie vont se retrouver sur Internet ?", "대표님. 직원들이 알고 싶은 건 하나예요. 자기들 급여명세서가 인터넷에 돌아다니게 되느냐는 거죠."),
(MA, "Je ne peux pas vous dire non, Madame Fabre. Des données ont peut-être été copiées. Nous le saurons dans les jours qui viennent, et vous le saurez en même temps que nous.",
     "아니라고 말씀드릴 수 없습니다, 파브르 씨. 데이터가 복사됐을 수 있습니다. 며칠 안에 알게 될 거고, 우리가 아는 순간 여러분도 알게 될 겁니다."),
(JF, "C'est la première fois qu'un patron me répond « je ne sais pas » sans tourner autour du pot.", "사장이 빙빙 돌리지 않고 '모른다'고 대답한 건 처음이네요."),
(MA, "C'est la vérité. Et je voudrais que le CSE soit associé à l'information des salariés. Une réunion extraordinaire lundi, si vous êtes d'accord.", "그게 사실이니까요. 그리고 직원들에게 알리는 일에 CSE가 함께해 주셨으면 합니다. 동의하신다면 월요일에 임시 회의를 하죠."),
(JF, "D'accord. Pour une fois, on est du même côté de la barricade. Mais ne vous y habituez pas.", "좋아요. 이번만큼은 같은 편이네요. 하지만 익숙해지진 마세요."),
(None, "10 h. Un magasinier apporte une caisse presque vide. Momo fronce les sourcils.", "오전 10시. 자재 담당이 거의 빈 상자를 가져온다. 모모가 미간을 찌푸린다."),
(MO, "Robert ! Les ressorts de soupape. Le camion du fournisseur est bloqué : leurs bons de livraison passent par notre système. Il nous en reste pour deux heures.",
     "로베르! 밸브 스프링이 떨어져 가. 공급업체 트럭이 묶였어. 납품서가 우리 시스템을 거치거든. 두 시간 치밖에 안 남았어."),
(RC, "On a un lot de l'autre référence, au magasin. Celui de la cocotte de huit litres. C'est presque la même.", "창고에 다른 품번 묶음이 있어. 8리터 압력솥용. 거의 같은 거야."),
(MO, "Presque... Je fais un essai sur vingt pièces. Si ça siffle à la bonne pression, on passe.", "거의라... 스무 개로 시험해 볼게. 제 압력에서 김이 빠지면 그걸로 가자."),
(None, "Vingt minutes plus tard, Momo hoche la tête, écrit quelques lignes sur une feuille volante, la glisse dans une pochette plastique et la pose sur la pile de papiers, au coin de l'établi.",
       "20분 뒤, 모모가 고개를 끄덕이고 낱장 종이에 몇 줄을 적어 비닐 파일에 끼운 다음, 작업대 구석의 종이 더미 위에 올려놓는다."),
(MO, "Vingt sur vingt. Je l'ai noté. D'habitude, il faut la signature du service qualité dans le système. Aujourd'hui, la qualité, c'est moi et ma feuille.",
     "스무 개 다 통과. 적어 뒀어요. 보통은 시스템에서 품질팀 서명이 필요한데, 오늘은 품질팀이 저랑 이 종이예요."),
(MA, "Momo, vous venez de sauver la journée.", "모모 씨, 오늘 하루를 구하셨네요."),
(MO, "Pas moi, patron. Le papier. Le papier, ça ne se pirate pas.", "제가 아니라 종이가요, 사장님. 종이는 해킹이 안 되거든요."),
(None, "11 h. Sur le parking, Mathieu appelle Inès.", "오전 11시. 주차장에서 마티외가 이네스에게 전화한다."),
(MA, "Tu as dormi ?", "잤어?"),
(I, "Une heure et demie. Serre a été parfait : il veut un point chaque soir, rien de plus. Et l'usine ?", "한 시간 반. 세르는 완벽했어. 매일 저녁 보고만 받겠대, 그 이상은 없고. 공장은?"),
(MA, "Six cocottes sur dix, des tableaux blancs partout, et un homme de soixante et un ans qui fait tourner l'atelier avec un crayon. J'aurais voulu que tu voies ça.",
     "열 개 중 여섯 개, 사방에 화이트보드, 그리고 연필 한 자루로 작업장을 돌리는 예순한 살 아저씨. 네가 이걸 봤으면 좋았을 텐데."),
(I, "Tu me raconteras ce soir. Et mange quelque chose, toi aussi. Je ne veux pas d'un directeur général qui s'évanouit devant le CSE.", "오늘 밤에 얘기해 줘. 그리고 너도 뭐 좀 먹어. CSE 앞에서 쓰러지는 대표이사는 사양이야."),
(MA, "Momo m'a déjà donné la moitié de son sandwich. Il dit que je suis trop maigre pour un patron.", "모모 씨가 벌써 샌드위치 반쪽을 줬어. 사장치고 너무 말랐대."),

# ---------- 5. Décision : le conseil et l'atelier ----------
(None, "Dimanche, 18 h. Salle du conseil. Samia a installé un ordinateur neuf, jamais connecté au réseau de l'entreprise. Conseil d'administration extraordinaire en visioconférence.",
       "일요일 오후 6시. 이사회 회의실. 사미아가 회사 네트워크에 한 번도 연결된 적 없는 새 컴퓨터를 설치했다. 화상으로 임시 이사회가 열린다."),
(HV, "Monsieur Kessler, depuis votre appel de vendredi soir, je n'ai pas fermé l'œil. Où en sommes-nous ?", "케슬레르 대표, 금요일 밤 전화 이후로 한숨도 못 잤소. 지금 어디까지 왔소?"),
(MA, "Monsieur le président, je vous propose trois points : la situation, la décision que nous vous demandons de soutenir, et la communication. Samia Haddad commence.",
     "의장님, 세 가지를 말씀드리겠습니다. 현재 상황, 지지를 부탁드릴 결정, 그리고 커뮤니케이션입니다. 사미아 아다드가 먼저 보고하겠습니다."),
(SA, "Les sauvegardes hors ligne sont intactes. La reconstruction a commencé cette nuit avec l'équipe de l'assureur, en suivant les recommandations de l'ANSSI. Saint-Étienne et Roanne produisent sur papier à environ soixante pour cent ; Wrocław redémarre demain matin.",
     "오프라인 백업은 온전합니다. 어젯밤부터 ANSSI의 권고에 따라 보험사 대응팀과 함께 재구축을 시작했습니다. 생테티엔과 로안은 종이로 약 60% 생산 중이고, 브로츠와프는 내일 아침 재가동합니다."),
(AU, "Et la rançon ? Huit millions, c'est beaucoup d'argent, mais une semaine d'arrêt aussi. Le calcul mérite au moins d'être fait.", "몸값은요? 800만이면 큰돈이지만, 일주일 가동 중단도 큰돈이죠. 적어도 계산은 해 볼 만합니다."),
(I, "Il a été fait, Monsieur Aubry. L'attaque nous coûtera environ cinq millions, dont trois couverts par l'assurance : la plainte a été déposée samedi matin. Payer coûterait huit millions de plus, sans aucune garantie que la clé fonctionne, ni que les données ne soient pas publiées.",
    "계산해 봤습니다, 오브리 씨. 이번 공격 비용은 약 500만 유로이고, 그중 300만은 보험으로 보장됩니다. 고소는 토요일 아침에 접수했습니다. 몸값을 내면 800만이 추가로 들지만, 키가 작동한다는 보장도, 데이터가 공개되지 않는다는 보장도 전혀 없습니다."),
(AU, "Sans garantie, certes. Mais certains de mes confrères ont payé et ont redémarré en quarante-huit heures.", "보장이 없긴 하죠. 하지만 제 동료들 중엔 돈을 내고 48시간 만에 재가동한 곳도 있습니다."),
(I, "D'autres ont payé et ont été attaqués de nouveau six mois plus tard. Et nous restaurerions de toute façon : nous ne pouvons pas faire tourner des usines sur des systèmes que des criminels connaissent mieux que nous.",
    "돈을 내고 여섯 달 뒤에 또 공격당한 곳도 있습니다. 그리고 어차피 복원은 해야 합니다. 범죄자들이 우리보다 더 잘 아는 시스템으로 공장을 돌릴 수는 없으니까요."),
(HV, "Pour une fois, je suis d'accord avec la direction. Chez les Verdier, on n'a jamais payé de rançon à personne, et ce n'est pas moi qui vais commencer.",
     "이번만큼은 경영진과 같은 의견이오. 베르디에 집안은 누구에게도 몸값을 낸 적이 없소. 내가 그 첫 사람이 될 생각은 없소."),
(CL, "Moi, je voudrais surtout parler des salariés. Qu'est-ce qu'on leur dit, demain matin ?", "저는 무엇보다 직원들 이야기를 하고 싶어요. 내일 아침 직원들에게 뭐라고 말하죠?"),
(MA, "La vérité, Madame Verdier. Que leurs données ont peut-être été copiées, que la CNIL a été notifiée, et que nous informerons personnellement chaque personne concernée dès que nous saurons quels fichiers ont été touchés.",
     "사실 그대로입니다, 베르디에 이사님. 데이터가 복사됐을 수 있다는 것, CNIL에 통지했다는 것, 그리고 어떤 파일이 피해를 입었는지 아는 즉시 해당되는 분들께 개별적으로 알리겠다는 것입니다."),
(LA, "Nous avons ouvert une ligne téléphonique dédiée, et les affiches sont prêtes pour les trois sites, en français et en polonais. Le CSE de Saint-Étienne se réunit demain en séance extraordinaire.",
     "전용 전화 상담 창구를 열었고, 세 사업장에 붙일 프랑스어·폴란드어 공지도 준비됐습니다. 생테티엔 CSE는 내일 임시 회의를 엽니다."),
(H, "Puis-je ajouter un mot ? J'ai accompagné trois crises de ce genre chez des clients. Celles qui ont mal tourné n'étaient pas les plus graves : c'étaient celles où la direction avait promis trop tôt. Ne donnez jamais une date que vous n'êtes pas sûrs de tenir.",
    "한마디 보태도 될까요? 고객사에서 이런 위기를 세 번 함께 겪었어요. 일이 꼬인 건 가장 심각한 경우가 아니었어요. 경영진이 너무 일찍 약속한 경우였죠. 지킬 자신이 없는 날짜는 절대 말하지 마세요."),
(MA, "C'est noté. Samia, quand pouvez-vous raisonnablement promettre un retour à la normale ?", "명심하겠습니다. 사미아, 정상화는 언제쯤으로 무리 없이 약속할 수 있나요?"),
(SA, "Raisonnablement ? Mardi soir pour l'essentiel. Mais je préférerais qu'on dise « dans le courant de la semaine ».", "무리 없이요? 핵심 시스템은 화요일 저녁이요. 하지만 '이번 주 중'이라고 말하는 편이 좋겠습니다."),
(MA, "Alors on dira « dans le courant de la semaine ». Et si c'est mardi, tant mieux.", "그럼 '이번 주 중'이라고 하죠. 화요일에 되면 더 좋고요."),
(AU, "Une question pour Madame Marchetti. La banque est informée ?", "마르케티 이사께 질문 하나. 은행은 알고 있습니까?"),
(I, "Depuis samedi neuf heures. Monsieur Serre reçoit un point chaque soir. Il m'a dit, je cite : « Je préfère un mauvais chiffre aujourd'hui qu'une surprise dans un mois. »",
    "토요일 9시부터요. 세르 씨는 매일 저녁 보고를 받습니다. 그분 말을 그대로 옮기면 '한 달 뒤의 깜짝 소식보다 오늘의 나쁜 숫자가 낫다'고 하셨습니다."),
(AU, "Bien. Je n'aurais pas mieux fait.", "좋습니다. 저라도 그보다 잘하진 못했을 겁니다."),
(HV, "Passons au vote. Le conseil soutient-il la décision de la direction de ne pas payer la rançon ?", "표결에 부칩시다. 이사회는 몸값을 내지 않겠다는 경영진의 결정을 지지합니까?"),
(CL, "Pour.", "찬성."),
(H, "Pour.", "찬성."),
(AU, "Pour. Mais je veux un audit complet de notre sécurité informatique d'ici l'été. Ce genre de chose ne doit pas se reproduire.", "찬성. 하지만 여름까지 정보보안 전면 감사를 원합니다. 이런 일이 되풀이되면 안 됩니다."),
(I, "Il est déjà budgété, Monsieur Aubry. Samia me l'a demandé il y a deux heures.", "이미 예산에 넣었습니다, 오브리 씨. 사미아가 두 시간 전에 요청했거든요."),
(None, "Lundi, 7 h 30. Devant l'atelier de Saint-Étienne, trois cents salariés. Mathieu est debout sur une palette, sans micro.", "월요일 오전 7시 30분. 생테티엔 작업장 앞, 직원 300명. 마티외가 마이크 없이 팔레트 위에 서 있다."),
(MA, "Bonjour à tous. Je serai bref, et je ne vous cacherai rien. Vendredi soir, notre entreprise a été attaquée. On nous demande huit millions d'euros. Nous ne les paierons pas. Si vos données ont été touchées, vous serez prévenus personnellement. D'ici là, ne cliquez sur aucun lien suspect, ne donnez jamais vos coordonnées bancaires au téléphone, et appelez la ligne affichée à l'entrée au moindre doute.",
     "안녕하십니까. 짧게, 아무것도 숨기지 않고 말씀드리겠습니다. 금요일 밤 우리 회사가 공격을 받았습니다. 800만 유로를 요구받았습니다. 우리는 내지 않을 겁니다. 여러분의 데이터가 피해를 입었다면 개별적으로 알려 드리겠습니다. 그때까지는 의심스러운 링크는 절대 누르지 마시고, 전화로 은행 정보를 알려 주지 마시고, 조금이라도 의심되면 입구에 붙은 번호로 전화하십시오."),
(JF, "Et nos emplois, Monsieur Kessler ?", "그럼 우리 일자리는요, 케슬레르 대표님?"),
(MA, "Ce week-end, vous avez sorti six cocottes sur dix avec des crayons et des tableaux blancs. Ce ne sont pas des pirates qui vont fermer une usine pareille. Merci à vous. Et merci à Momo, qui nous a rappelé comment on travaillait avant les écrans.",
     "이번 주말 여러분은 연필과 화이트보드로 열 개 중 여섯 개를 만들어 냈습니다. 해커 따위가 이런 공장을 문 닫게 할 수는 없습니다. 감사합니다. 그리고 화면 이전에 어떻게 일했는지 일깨워 준 모모 씨에게도 감사드립니다."),
(None, "Applaudissements. Momo soulève sa casquette.", "박수가 터진다. 모모가 모자를 들어 올린다."),
(MO, "Avant les écrans, on avait aussi des moustaches. Ça, je ne vous le recommande pas !", "화면 이전엔 다들 콧수염도 길렀죠. 그건 권하지 않습니다!"),
(RC, "Vous avez gagné quelque chose ce matin, Monsieur Kessler. Ne le perdez pas.", "대표님, 오늘 아침 뭔가를 얻으셨어요. 잃지 마십시오."),
(LA, "Le message est en ligne depuis dix heures. La presse locale le reprend tel quel. Pour une fois, pas de « selon nos informations ».", "메시지는 10시부터 공개됐습니다. 지역 언론이 그대로 받아쓰고 있어요. 이번만큼은 '취재에 따르면'이 없네요."),
(MA, "Parfait. Maintenant, on tient jusqu'à mardi.", "완벽해요. 이제 화요일까지 버팁시다."),

# ---------- 6. Soixante-douze heures ----------
(None, "Lundi, 23 h. Soixante-douze heures après l'appel de Samia. Le siège est presque vide. Inès entre dans le bureau du directeur général avec deux tasses fumantes.",
       "월요일 밤 11시. 사미아의 전화로부터 72시간. 본사는 거의 비어 있다. 이네스가 김이 나는 머그잔 두 개를 들고 대표이사실로 들어온다."),
(I, "Samia vient d'écrire : l'ERP de Saint-Étienne est revenu, propre. Roanne et Wrocław demain. Mardi soir, tout tournera.", "사미아가 방금 문자 보냈어. 생테티엔 ERP가 깨끗한 상태로 돌아왔대. 로안이랑 브로츠와프는 내일. 화요일 저녁이면 전부 돌아갈 거야."),
(MA, "Quatre jours. Elle avait dit quatre à cinq. Il faudra lui offrir quelque chose... une statue, au moins.", "4일. 4~5일이라고 했었지. 뭔가 선물해야겠어... 동상 정도는."),
(I, "Une hausse de budget suffira. C'est moins encombrant.", "예산 증액이면 충분해. 자리도 덜 차지하고."),
(MA, "Toujours CFO, même à minuit.", "자정에도 여전히 CFO네."),
(I, "Toujours. Martine a compté : près de trois mille feuilles à ressaisir. Elle a déjà rangé les cartons par atelier.", "언제나. 마르틴이 세어 봤는데, 다시 입력할 종이가 3,000장 가까이 된대. 벌써 작업장별로 상자에 정리해 놨어."),
(MA, "Trois mille... Les feuilles de Momo doivent en faire la moitié. Il ne s'est pas assis de tout le week-end.", "3,000장이라... 모모 씨 종이만 해도 절반은 되겠다. 주말 내내 한 번도 안 앉았어."),
(I, "Toi non plus. Assieds-toi. Verveine. Pas de café après vingt-deux heures : ordre de la direction financière.", "너도 마찬가지야. 앉아. 버베나 차야. 밤 10시 이후 커피 금지, 재무 부문 지시야."),
(None, "Il s'assoit sur le vieux canapé en cuir. Elle s'assoit à côté de lui ; au bout d'un moment, sa tête trouve son épaule.", "그가 낡은 가죽 소파에 앉는다. 그녀가 옆에 앉는다. 잠시 뒤, 그녀의 머리가 그의 어깨에 기댄다."),
(MA, "Tu sais ce qui était le plus bizarre, vendredi ? Dire « je préviens Madame Marchetti » pendant que tu me tendais déjà mes chaussures.", "금요일에 제일 이상했던 게 뭔지 알아? 네가 벌써 내 신발을 건네주고 있는데 '마르케티 이사님께 알리죠'라고 말한 거."),
(I, "J'ai trouvé ça très professionnel. Un peu ridicule, mais très professionnel.", "아주 프로다웠어. 좀 우스웠지만, 아주 프로다웠어."),
(MA, "Allez. Les trois questions. Quel est le vrai problème ?", "자. 세 가지 질문. 진짜 문제는 무엇인가?"),
(I, "Ce n'était pas les pirates. C'était qu'on avait oublié que cette entreprise sait marcher sans écrans. Momo, les feuilles imprimées de Robert, l'annuaire de Martine...", "해커가 아니었어. 이 회사가 화면 없이도 돌아갈 줄 안다는 걸 우리가 잊고 있었다는 거지. 모모, 로베르가 출력해 둔 종이, 마르틴의 전화번호부..."),
(MA, "Qui décide ?", "누가 결정하는가?"),
(I, "Nous deux. Et cette fois, tu n'as rien retardé, Monsieur Kessler. Tu as décidé à quatre heures du matin, avec des madeleines du distributeur.", "우리 둘. 그리고 이번엔 아무것도 미루지 않았어요, 케슬레르 대표님. 새벽 4시에 자판기 마들렌을 먹으면서 결정했지."),
(MA, "Et... que fait-on lundi ? Enfin, lundi prochain.", "그리고... 월요일엔 뭘 하지? 그러니까, 다음 주 월요일."),
(I, "Lundi prochain, on s'envole pour Shenzhen. Hongda Electric : les prix et la qualité des composants à renégocier. Zhang Wei nous attend mardi.", "다음 주 월요일엔 선전행 비행기를 타. 홍다 일렉트릭, 부품 단가랑 품질 재협상. 장웨이가 화요일에 기다리고 있어."),
(MA, "Shenzhen... Douze heures d'avion, six heures de décalage. On dormira dans l'avion.", "선전이라... 비행기로 열두 시간, 시차 여섯 시간. 비행기에서 자면 되겠네."),
(I, "Toi, tu dors maintenant. Ça fait dix minutes que tu fermes les yeux en croyant que je ne vois rien.", "넌 지금 자. 10분째 눈 감고 있으면서 내가 모르는 줄 알지."),
(None, "Il ne répond pas. Il s'est endormi au milieu d'une phrase, la tête contre l'accoudoir. Inès prend le plaid plié sur le fauteuil et le couvre doucement.",
       "그는 대답하지 않는다. 말하다 말고 팔걸이에 머리를 기댄 채 잠들었다. 이네스는 안락의자 위에 개어 둔 담요를 가져와 그를 살며시 덮어 준다."),
(I, "Rue Raymond-Losserand, c'était une seule couverture pour deux, devant Les Parapluies de Cherbourg. Ce soir, c'est mon tour de te couvrir.", "레몽로스랑 거리에선 '쉘부르의 우산'을 보면서 담요 하나를 둘이 덮었지. 오늘 밤엔 내가 널 덮어 줄 차례야."),
(MA, "Mm... Tu restes ?", "음... 갈 거야?"),
(I, "Je reste. Dors, Strasbourg. Lundi, on part pour Shenzhen.", "안 가. 자, 스트라스부르. 월요일엔 선전으로 떠나."),
(None, "Elle éteint la lampe du bureau. Son téléphone reste allumé sur ses genoux, au cas où.", "그녀가 책상 스탠드를 끈다. 혹시 몰라, 그녀의 무릎 위 휴대폰은 켜 둔 채로."),
]

VOCAB = [
("B2", "un rançongiciel", "랜섬웨어", "공식 권장어. 일상·언론에서는 ransomware도 흔하다. rançon(몸값) + logiciel(소프트웨어)."),
("B2", "exiger une rançon", "몸값을 요구하다", "Ils exigent huit millions. payer / refuser de payer la rançon. prendre en otage(인질로 잡다)와 함께 쓰임."),
("B2", "chiffrer / déchiffrer", "암호화하다 / 복호화하다", "Vos fichiers ont été chiffrés. une clé de déchiffrement(복호화 키). chiffrer은 '금액을 산정하다'라는 뜻도 있다."),
("C1", "la double extorsion", "이중 갈취", "데이터를 암호화하고, 동시에 훔친 데이터 공개를 협박하는 수법. extorquer = 갈취하다."),
("B2", "une sauvegarde (hors ligne)", "(오프라인) 백업", "sauvegarder = 저장·백업하다. hors ligne ↔ en ligne. 네트워크와 분리된 사본이 랜섬웨어 대응의 핵심."),
("B2", "un logiciel malveillant", "악성 프로그램", "malveillant = 악의적인. 구어로 un malware, un virus."),
("B2", "en mode dégradé", "비상(축소) 운영 모드로", "시스템 일부가 멈춘 상태로 핵심 기능만 유지하는 것. 병원·공장·철도에서 자주 쓰는 표현."),
("B2", "porter plainte", "고소하다, 고발하다", "porter plainte contre X(성명불상자를 상대로). déposer une plainte = 고소장을 접수하다."),
("C1", "notifier (qc à qn) / une notification", "(공식적으로) 통지하다 / 통지", "la CNIL doit être notifiée. 법적 의무 통지를 말할 때. prévenir·informer보다 격식."),
("B2", "une fuite de données / fuir", "데이터 유출 / 새어 나가다", "Des données ont probablement fui. 기밀이 '새다'에도 쓴다: L'information a fuité(구어)."),
("C1", "une déclaration d'attente", "(위기 초기의) 대기 성명", "사실 확인 전, 사고를 인정하고 조치 중임을 알리는 짧은 공식 입장. 영어 holding statement."),
("B2", "l'hameçonnage", "피싱", "hameçon(낚싯바늘)에서 온 공식 권장어. 일상에서는 le phishing이 더 흔하다."),
("B1", "se donner le mot", "(여럿이) 미리 짜다, 입을 맞추다", "Tout le monde s'est donné le mot. 우연히 같은 일이 겹칠 때 농담으로도 씀."),
("B2", "un ordre de fabrication", "작업(생산) 지시서", "lancer un ordre de fabrication. 공장 ERP·MES의 기본 단위."),
("B2", "un bon de livraison", "납품서, 배송 전표", "éditer / signer un bon de livraison. bon de commande(주문서)와 구분."),
("B2", "ressaisir", "(데이터를) 다시 입력하다", "saisir = 입력하다. la ressaisie des feuilles papier. '다시 붙잡다'라는 뜻도 있다(se ressaisir = 정신을 차리다)."),
("B2", "au fur et à mesure (de qc)", "(~이 진행되는) 대로, 차차", "au fur et à mesure de l'enquête. 진행과 함께 조금씩 이뤄지는 일."),
("B2", "un événement significatif", "중대한 사건", "대출 약정·공시 문서 용어. 은행이나 투자자에게 알려야 하는 사건."),
("B2", "tourner autour du pot", "말을 빙빙 돌리다", "직역 '냄비 주위를 돌다'. Ne tourne pas autour du pot ! = 본론만 말해!"),
("B2", "être du même côté de la barricade", "같은 편에 서다", "barricade = 바리케이드. 노사·정치 대립을 떠올리게 하는 표현. ↔ de l'autre côté de la barricade."),
("B2", "tel quel / telle quelle", "그대로, 손대지 않고", "Dites-le tel quel. La presse le reprend tel quel. 수식하는 명사에 성·수 일치."),
("B2", "dans le courant de la semaine", "이번 주 중에", "날짜를 확정하지 않는 신중한 시간 표현. dans le courant du mois / de l'année."),
("B2", "un ressort / une soupape", "스프링 / 밸브", "압력솥(une cocotte, un autocuiseur)의 안전 장치. La soupape siffle = 밸브에서 김이 빠지며 소리가 나다."),
("B2", "couper le ruban", "(준공식에서) 테이프를 끊다", "inaugurer의 구어적 표현. 사장이 좋은 날에만 나타나는 것을 비꼴 때."),
("B1", "une verveine", "버베나 차(허브티)", "프랑스에서 저녁에 즐겨 마시는 허브티. une tisane, une infusion."),
]

GRAM = [
("B2", "명령법과 대명사의 위치",
 "« Lisez-le-moi. » « Appelez-le. » « Dites-le tel quel. » « Laisse-les faire leur métier. » « Assieds-toi. » 긍정 명령에서는 대명사가 동사 뒤에 하이픈으로 붙고, 직접목적(le, la, les)이 간접목적(moi, lui, nous) 앞에 온다(Lisez-le-moi). me/te는 강세형 moi/toi로 바뀐다(Assieds-toi). 부정 명령에서는 평서문 순서로 돌아간다: Ne me le lisez pas. « Ne vous y habituez pas. »"),
("B2", "부정 명령과 위기 지침: ne... aucun / ne... jamais",
 "« ne cliquez sur aucun lien suspect, ne donnez jamais vos coordonnées bancaires au téléphone » 지침·안내문은 명령법 2인칭 복수가 기본이다. aucun(e)은 명사 앞에 붙어 '단 하나도 ~ 않다'를 강조하며 항상 단수로 쓴다. 같은 의미로 « Surtout pas « aucune donnée n'a été volée » »처럼 aucun이 주어가 되면 ne만 동사 앞에 남는다."),
("B2", "que + 접속법: 3인칭에 대한 명령·지시",
 "« Surtout, que personne n'éteigne les machines ni ne touche à rien. » 명령법에는 3인칭이 없으므로 'que + 접속법'으로 제3자에게 지시를 내린다(Qu'il entre ! = 들어오라고 해!). ni를 이용해 두 동사를 함께 부정할 수 있다: ne... ni ne... 이때 pas는 쓰지 않는다."),
("B2", "personne / rien이 주어·목적어일 때",
 "« Personne ne leur écrit. Personne. » « Personne ne leur écrira. » « on ne promet rien qu'on ne puisse tenir » 주어 personne 뒤에는 ne만 쓰고 pas는 쓰지 않는다. 단독으로 « Personne. »처럼 대답할 수도 있다. rien 뒤의 관계절은 '그런 것은 없다'는 부정의 뜻이므로 접속법(puisse)을 쓴다."),
("B2", "avant que (ne) + 접속법 / tant que + 직설법",
 "« il faut leur parler avant qu'ils ne parlent entre eux » « rien à la presse tant qu'on ne sait pas ce qui a fui » avant que 뒤에는 접속법을 쓰며, 격식체에서는 의미 없는 허사 ne(ne explétif)를 붙이기도 한다. 반면 tant que(~하는 한, ~하는 동안)는 사실을 나타내므로 직설법을 쓴다."),
("B2", "전미래(futur antérieur): 미래의 한 시점보다 먼저 끝날 일",
 "« Je dormirai quand Samia aura relancé l'ERP. » « Mardi soir, tout tournera. » quand 뒤에서 미래에 먼저 완료될 일을 말할 때는 avoir/être의 단순미래 + 과거분사(aura relancé)를 쓴다. 한국어로는 '~하고 나면'에 해당한다. 비교: « Je veux qu'on ait fait le raisonnement jusqu'au bout. »는 접속법 과거로, 의지 동사 뒤에서 '완료된 상태'를 요구한다."),
("C1", "조건법 과거와 préférer que + 접속법",
 "« J'aurais voulu que tu voies ça. » « Je n'aurais pas mieux fait. » « Je préfère qu'on nous reproche d'avoir été trop francs que trop prudents. » « je préférerais qu'on dise « dans le courant de la semaine » » 조건법 과거 j'aurais voulu que + 접속법은 이루어지지 않은 바람을, je n'aurais pas mieux fait는 '나라도 그 이상은 못 했을 것'이라는 인정을 나타낸다. préférer que 뒤에는 접속법, 주어가 같으면 부정사 과거(d'avoir été)를 쓴다."),
("B2", "긴박한 구어체: 생략·나열·전위",
 "« Huit millions, soixante-douze heures, trois usines à l'arrêt. » « Les trois usines ? » « Produire, oui. Savoir quoi produire, c'est une autre histoire. » « La plainte, c'est urgent pour une autre raison. » 위기 상황에서는 동사를 빼고 명사만 나열하거나, 화제를 문장 앞으로 빼고(dislocation) c'est로 다시 받는다. 핵심어가 먼저 나오므로 짧고 빠르게 정보를 전달할 수 있다."),
]

CULTURE = [
("ANSSI와 '몸값은 내지 않는다'는 원칙",
 "ANSSI(Agence nationale de la sécurité des systèmes d'information, 국가정보시스템보안청)는 총리실 산하의 국가 사이버 보안 기관으로, 그 안의 CERT-FR이 사고 신고를 받고 대응을 돕는다. 중소기업과 개인은 공공 플랫폼 cybermalveillance.gouv.fr을 통해 도움을 받을 수 있다. 프랑스 정부와 ANSSI는 몸값을 지불하지 말 것을 일관되게 권고한다. 복호화가 보장되지 않고, 범죄 조직의 다음 공격 자금이 되며, '돈을 내는 회사'로 다시 표적이 될 수 있기 때문이다. 2021~2022년 닥스, 코르베유에손 등의 병원이 랜섬웨어 공격을 받고도 몸값을 내지 않은 채 종이 기록으로 진료를 이어 간 사례가 널리 알려졌다."),
("세 개의 '72시간'",
 "EU 일반개인정보보호규정(RGPD/GDPR) 제33조에 따라, 개인정보 침해가 발생하면 기업은 원칙적으로 이를 안 때부터 72시간 안에 감독기관에 통지해야 한다. 프랑스의 감독기관은 CNIL(국가정보자유위원회)이며, 위험이 큰 경우 당사자에게도 알려야 한다. 또 2023년 시행된 내무부 관련 법(LOPMI)에 따라, 사이버 공격 피해를 보험으로 보상받으려면 공격을 안 뒤 72시간 안에 고소해야 한다. 그래서 프랑스 기업의 랜섬웨어 대응 매뉴얼에는 '72시간'이 여러 번 등장한다."),
("종이로 돌아가는 공장: mode dégradé",
 "프랑스의 공장·병원·철도 등은 정보 시스템이 멈췄을 때 핵심 업무만 유지하는 '비상 운영 모드(mode dégradé)' 절차를 갖추도록 권장된다. 실제 랜섬웨어 피해 기업들도 종이 작업지시서, 화이트보드 계획표, 출력해 둔 주문 목록으로 생산을 이어 간 경우가 많다. 다만 위기가 끝나면 종이 기록을 모두 시스템에 다시 입력(ressaisie)해야 하며, 이 과정에서 기록 누락이 생기지 않도록 관리하는 것이 품질·추적성(traçabilité)의 중요한 과제로 꼽힌다."),
]
