# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, B = "Inès", "Mathieu", "Hélène", "Baptiste"
AU, CV, HV, MR = "Aubry", "Claire", "Hubert", "Martine"
JF, MO = "Josiane", "Momo"

META = {
    "part": 2, "ep": 25,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Le fonds ne lâche pas",
    "title_ko": "펀드는 물러서지 않는다",
    "place": "생테티엔 자쿠아르 지구 이네스 아파트 · Verdier Industries 본사 대표이사실 · 생테티엔 공장 출퇴근 기록기 앞 · 본사 이사회실 / 9월(취임 1년째), 화요일~목요일",
    "chars": "이네스(CFO), 마티외(CEO), 엘렌 바쇠르(사외이사), 바티스트 모렐(아르칸 캐피털·이사회 참관인), 프레데리크 오브리(아르칸 파트너), 위베르 베르디에(이사회 의장), 클레르 베르디에(이사·보상위원장), 마르틴 로슈(CEO 비서), 조지안 파브르(노조 대표·CSE 서기), 모모 벨카셈(숙련공)",
    "work": "아르칸의 결의안 — 브로츠와프 공장을 체코 그룹 코반트에 9,500만 유로에 매각 + 생테티엔 600명 감원. 숨은 조건(리스 보증 6,000만 유로, 5년 공급계약)을 파헤친 반대 계획(감원 없이 연 3,100만 유로 절감)과 이사회 표결",
    "life": "익명 이메일로 날아든 둘의 사진, 바티스트의 은근한 협박, 이사회에 관계를 스스로 신고하기, 공개 뒤의 해방감과 두려움, 처음으로 '커플로서' 나누는 미래 이야기",
    "focus": "압박·반론 표현, 접속법 심화(bien que, à moins que + 허사 ne, pour que, sans que, avant que, douter que), 양보 부정관계사(d'où qu'il vienne, quoi qu'il arrive), 조건법 과거·전미래, mieux vaut / il vaut mieux que, 회의 중 vous와 사적인 tu",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제26화 Rappel produit — 일요일 아침 뉴스: « La Stéphanoise » 밸브 결함으로 화상 사고 3건, 12만 대 리콜과 TV 앞에서의 공개 사과.",
}

D = [
# ---------- 1. Ouverture : le message ----------
(None, "Un mardi de septembre, 6 h 50. Saint-Étienne, quartier Jacquard. Dans la cuisine d'Inès, la cafetière italienne siffle. Figaro dort sur la chaise de Mathieu.",
       "9월의 어느 화요일, 오전 6시 50분. 생테티엔 자쿠아르 지구. 이네스의 부엌에서 모카포트가 쉭쉭 소리를 낸다. 피가로는 마티외의 의자 위에서 자고 있다."),
(MA, "Ton café sent le brûlé. Tu as encore oublié la cafetière sur le feu ?", "커피에서 탄 냄새가 나. 모카포트를 또 불 위에 잊어버렸어?"),
(I, "Je ne l'ai pas oubliée, je l'ai perdue de vue. Je relisais la note pour le conseil de jeudi.", "잊은 게 아니라 잠깐 놓친 거야. 목요일 이사회용 메모를 다시 읽고 있었어."),
(MA, "À sept heures moins dix ? Viens t'asseoir. Figaro m'a même laissé une moitié de chaise.", "7시 10분 전에? 와서 앉아. 피가로가 의자 반쪽은 남겨 줬어."),
(I, "Figaro te laisse tout. Moi, il me laisse ses poils sur mon tailleur.", "피가로는 너한텐 다 양보하지. 나한텐 정장에 털만 남기고."),
(None, "Sur la table, leurs deux téléphones vibrent au même moment.", "식탁 위에서 두 사람의 휴대폰이 동시에 진동한다."),
(MA, "Le même message, à la même seconde. Ça, ce n'est jamais bon signe.", "같은 메시지가 같은 순간에. 그건 절대 좋은 신호가 아니야."),
(I, "Expéditeur inconnu. Objet : « Gouvernance ». Et une pièce jointe...", "발신자 불명. 제목은 '지배구조'. 그리고 첨부 파일이..."),
(None, "Une photo : tous les deux, main dans la main, samedi soir, près de la place Jean-Jaurès. En dessous, une seule ligne : « Le conseil d'administration est-il au courant ? Un ami qui vous veut du bien. »",
       "사진 한 장. 토요일 저녁 장조레스 광장 근처에서 손을 잡고 있는 두 사람. 아래에는 단 한 줄. '이사회는 알고 있습니까? 당신들이 잘되길 바라는 친구가.'"),
(MA, "C'est nous, en sortant du cinéma. On s'est tenu la main dix secondes, pas plus !", "우리잖아, 영화관에서 나오던 길. 손잡은 건 10초밖에 안 됐는데!"),
(I, "Dix secondes, ça suffit pour un téléobjectif. Regarde l'angle : c'était pris d'une voiture, de l'autre côté de la place. Quelqu'un nous suivait.",
    "망원렌즈엔 10초면 충분해. 각도를 봐. 광장 건너편 차 안에서 찍은 거야. 누가 우릴 따라다녔어."),
(MA, "« Un ami qui vous veut du bien »... On se croirait dans un vieux film en noir et blanc.", "'당신들이 잘되길 바라는 친구'라... 옛날 흑백 영화 속에 들어온 것 같네."),
(I, "Le Corbeau, de Clouzot. Sauf que ce corbeau-là a une adresse jetable, un très bon appareil photo, et il sait que le conseil se réunit jeudi.",
    "클루조의 『까마귀』지. 다만 이 까마귀는 일회용 주소에 아주 좋은 카메라를 갖고 있고, 이사회가 목요일이라는 것도 알아."),
(MA, "Et Arcane vient nous voir ce matin à dix heures. Tu penses à la même personne que moi ?", "그리고 아르칸이 오늘 아침 10시에 우릴 만나러 오지. 너도 나랑 같은 사람 생각하고 있어?"),
(I, "Je pense à quelqu'un qui m'a dit « le monde est petit » avec un sourire de requin. Mais je n'ai aucune preuve.", "'세상 참 좁네요'라고 상어 같은 미소로 말하던 누군가를 생각하고 있지. 하지만 증거는 하나도 없어."),
(MA, "Alors on ne décide rien sous le coup de la colère. On écoute Arcane, et ce soir, on en reparle à tête reposée.", "그럼 홧김에 아무것도 결정하지 말자. 아르칸 얘기를 듣고, 오늘 저녁에 차분하게 다시 얘기해."),
(I, "Tu es en train de repousser la décision, Mathieu. Je te connais. ... Bon. On part séparément, comme d'habitude. Et ne me souris pas devant Martine.",
    "너 결정을 미루고 있는 거야, 마티외. 난 너를 알아. ...좋아. 늘 그렇듯 따로 나가자. 그리고 마르틴 앞에서 나한테 웃지 마."),
(MA, "Promis. Je ferai ma tête de directeur général très sérieux.", "약속할게. 아주 진지한 대표이사 표정을 하고 있을게."),

# ---------- 2. Arcane au siège ----------
(None, "10 h. Siège de Verdier Industries, bureau du directeur général.", "오전 10시. Verdier Industries 본사, 대표이사실."),
(MR, "Monsieur Kessler, M. Aubry est en bas, avec M. Morel. Ils demandent que Mme Marchetti soit présente. Et ils ont refusé le café.",
     "케슬레르 대표님, 오브리 씨가 모렐 씨와 함께 아래층에 와 계세요. 마르케티 이사님도 함께해 달라고 하시네요. 그리고 커피는 사양하셨어요."),
(MA, "Refuser le café de Martine Roche... Ils ne viennent pas en amis. Faites-les monter, s'il vous plaît, et prévenez Mme Marchetti.",
     "마르틴 로슈의 커피를 사양하다니... 친구로 온 건 아니군요. 올라오시라고 해 주세요. 그리고 마르케티 이사님께도 알려 주시고요."),
(MR, "C'est déjà fait. Elle arrive avec trois classeurs. En trente ans, j'ai appris à mesurer les réunions difficiles au nombre de classeurs.",
     "벌써 했어요. 이사님은 바인더 세 개를 들고 오시는 중이에요. 30년 동안 어려운 회의는 바인더 개수로 가늠하는 법을 배웠죠."),
(AU, "Monsieur Kessler, madame Marchetti. Je serai bref : jeudi, Arcane présentera au conseil une résolution en deux points. Baptiste, je vous en prie.",
     "케슬레르 대표, 마르케티 이사. 짧게 말하죠. 목요일에 아르칸은 이사회에 두 가지 항목의 결의안을 제출합니다. 바티스트, 설명하세요."),
(B, "Premier point : la cession de l'usine de Wrocław. Nous avons une offre ferme du groupe tchèque Kovant : quatre-vingt-quinze millions d'euros. Second point : six cents suppressions de postes à Saint-Étienne.",
    "첫째, 브로츠와프 공장 매각입니다. 체코 그룹 코반트로부터 9,500만 유로의 확정 제안을 받았습니다. 둘째, 생테티엔에서 600개 일자리 감축입니다."),
(MA, "Six cents ? Monsieur Morel, nous négocions en ce moment avec le CSE un plan de cent cinquante départs, essentiellement volontaires. Vous le savez.",
     "600명이요? 모렐 씨, 지금 우리는 CSE와 자발적 퇴직 중심으로 150명 감축안을 협상하고 있습니다. 알고 계시잖아요."),
(B, "Nous le savons, et c'est insuffisant. Six cents postes en moins, c'est trente-six millions d'économies par an. Avec cent cinquante, vous restez au milieu du gué.",
    "알고 있고, 그걸로는 부족합니다. 600명을 줄이면 연간 3,600만 유로가 절감됩니다. 150명으로는 강 한복판에서 멈춰 서는 셈이죠."),
(I, "Et le coût ? Six cents départs contraints, c'est au minimum cinquante-quatre millions d'indemnités et de mesures d'accompagnement. Sans compter les grèves.",
    "그럼 비용은요? 강제 퇴직 600명이면 해고 수당과 지원 조치에만 최소 5,400만 유로입니다. 파업은 빼고도요."),
(AU, "Nous avons fait les calculs, madame. Avec la cession, la dette nette passerait de deux cent quatre-vingt-douze millions à moins de deux cents. C'est ce que les banques attendent.",
     "계산은 해 봤습니다. 매각하면 순부채가 2억 9,200만 유로에서 2억 유로 아래로 내려갑니다. 은행들이 기다리는 게 그거예요."),
(I, "Les banques attendent un plan crédible, monsieur Aubry. Vendre au rabais notre usine la plus rentable n'en est pas un.", "은행들이 기다리는 건 믿을 만한 계획입니다, 오브리 씨. 우리에게 가장 수익성 좋은 공장을 헐값에 파는 건 그런 계획이 아니고요."),
(B, "La plus rentable ? Allons, Inès... pardon, madame Marchetti. Wrocław fabrique des grille-pain d'entrée de gamme.", "가장 수익성이 좋다고요? 이런, 이네스... 실례, 마르케티 이사님. 브로츠와프는 보급형 토스터를 만드는 곳인데요."),
(I, "Des grille-pain qui dégagent neuf pour cent de marge d'EBITDA, monsieur Morel. Le meilleur taux du groupe. Kovant vous propose cinq fois l'EBITDA : c'est le prix d'une usine en difficulté, pas d'une usine en bonne santé.",
    "EBITDA 마진 9%를 내는 토스터죠, 모렐 씨. 그룹 최고 수준입니다. 코반트는 EBITDA의 5배를 제시했어요. 그건 건강한 공장이 아니라 어려운 공장에 매기는 값입니다."),
(AU, "C'est le prix du marché. Personne d'autre ne s'est manifesté.", "그게 시장 가격입니다. 다른 누구도 나서지 않았어요."),
(MA, "Parce que personne d'autre n'a été sollicité. Vous avez négocié avec Kovant sans que la direction générale en soit informée.", "다른 누구에게도 제안하지 않았으니까요. 경영진이 전혀 모르는 사이에 코반트와 협상하셨잖습니까."),
(AU, "Arcane détient quarante pour cent du capital. Nous avons le droit d'explorer des options.", "아르칸은 지분 40%를 갖고 있습니다. 우리에겐 여러 선택지를 검토할 권리가 있어요."),
(MA, "Explorer, oui. Négocier dans le dos de la direction, c'est autre chose. Je le dirai jeudi au conseil.", "검토하는 건 좋습니다. 경영진 몰래 협상하는 건 다른 문제죠. 목요일 이사회에서 그렇게 말하겠습니다."),
(B, "Vous direz beaucoup de choses jeudi, j'imagine. La transparence est une valeur de cette maison, n'est-ce pas ?", "목요일엔 하실 말씀이 많겠군요. 투명성은 이 회사의 가치잖아요, 그렇죠?"),
(I, "Où voulez-vous en venir, monsieur Morel ?", "무슨 말씀을 하시려는 거죠, 모렐 씨?"),
(B, "Nulle part. Je dis simplement que la gouvernance, c'est important. Un conseil doit pouvoir se fier entièrement à ses dirigeants. À tous ses dirigeants.",
    "아무 말도요. 그저 지배구조가 중요하다는 거죠. 이사회는 경영진을 전적으로 믿을 수 있어야 하니까요. 경영진 모두를요."),
(None, "Un silence. Inès et Mathieu évitent de se regarder.", "정적. 이네스와 마티외는 서로를 쳐다보지 않으려 한다."),
(AU, "Baptiste, restons sur les chiffres. Monsieur Kessler, vous avez jusqu'à jeudi pour réfléchir. Mais Arcane ne retirera pas sa résolution.", "바티스트, 숫자 얘기만 합시다. 케슬레르 대표, 목요일까지 생각해 보세요. 하지만 아르칸은 결의안을 철회하지 않습니다."),
(MA, "Et la direction présentera la sienne. Martine va vous raccompagner.", "그리고 경영진은 경영진의 안을 내놓을 겁니다. 마르틴이 배웅해 드릴 거예요."),
(None, "Dans le couloir, Baptiste s'attarde devant l'ascenseur. Inès le rattrape.", "복도에서 바티스트가 엘리베이터 앞에 머뭇거리고 있다. 이네스가 그를 따라잡는다."),
(I, "Baptiste. Deux minutes. Sans les « madame Marchetti ».", "바티스트. 2분만. '마르케티 이사님'은 빼고."),
(B, "Avec plaisir. Ça me rappelle le bon vieux temps, chez Hélène. Tu tutoyais tout le monde.", "기꺼이. 엘렌네 회사 시절이 생각나네. 넌 모두한테 반말했잖아."),
(I, "Le message de ce matin, avec la photo. C'est toi ?", "오늘 아침 그 메시지, 사진 붙은 거. 너야?"),
(B, "Quelle photo ? Je ne vois pas de quoi tu parles. Mais si tu as reçu quelque chose qui t'inquiète, c'est peut-être qu'il y a de quoi s'inquiéter.",
    "무슨 사진? 무슨 얘긴지 모르겠는데. 하지만 뭔가 걱정되는 걸 받았다면, 걱정할 만한 이유가 있는 거겠지."),
(I, "Tu nous menaces ?", "우릴 협박하는 거야?"),
(B, "Moi ? Je m'inquiète pour toi. Imagine que le conseil apprenne que sa CFO valide les notes de frais de quelqu'un de... très proche. Bien que je n'aie rien contre l'amour, je doute que Hubert Verdier soit aussi moderne que moi.",
    "내가? 난 네가 걱정될 뿐이야. 이사회가 자기네 CFO가... 아주 가까운 사람의 경비 정산을 승인한다는 걸 알게 된다고 상상해 봐. 난 사랑에 반대할 생각은 없지만, 위베르 베르디에가 나만큼 현대적일지는 모르겠네."),
(I, "Et si Arcane obtenait son vote, ce petit souci disparaîtrait, c'est ça ?", "그리고 아르칸이 원하는 표결을 얻으면 그 작은 걱정거리는 사라지는 거고, 그런 거지?"),
(B, "Je n'ai jamais dit ça. Je dis seulement qu'à moins que la direction ne devienne plus raisonnable, jeudi risque d'être une longue journée. Bonne journée, Inès.",
    "그런 말 한 적 없어. 다만 경영진이 좀 더 합리적으로 나오지 않는 한, 목요일은 긴 하루가 될 수도 있다는 거지. 좋은 하루 보내, 이네스."),
(None, "Les portes de l'ascenseur se referment.", "엘리베이터 문이 닫힌다."),
(I, "... Un sourire de requin. Je ne m'étais pas trompée.", "...상어 같은 미소. 내가 틀리지 않았어."),

# ---------- 3. Analyse : les chiffres et la photo ----------
(None, "21 h. Bureau du directeur général. Les couloirs sont vides. Sur le tableau blanc, deux colonnes : « Arcane » et « Nous ». Le vieux marqueur vert est posé sur la table.",
       "밤 9시. 대표이사실. 복도는 텅 비어 있다. 화이트보드에 두 개의 칸: '아르칸'과 '우리'. 낡은 초록 마커가 테이블 위에 놓여 있다."),
(MA, "Les chiffres d'abord, le reste après. Qu'est-ce qu'Arcane cherche vraiment ?", "숫자 먼저, 나머지는 나중에. 아르칸이 진짜 원하는 게 뭘까?"),
(I, "Sortir. Ils ne gardent jamais une entreprise plus de cinq ans. Ils veulent une dette plus faible et une histoire simple à raconter aux acheteurs.", "빠져나가는 거. 그 사람들은 어떤 회사도 5년 넘게 안 갖고 있어. 부채는 줄이고, 인수자들한테 들려줄 단순한 이야기를 원하는 거야."),
(MA, "Et l'histoire simple, c'est : on vend la Pologne, on coupe à Saint-Étienne, la marge monte.", "그 단순한 이야기란 이거지. 폴란드를 팔고, 생테티엔을 자르고, 마진이 오른다."),
(I, "Sur le papier. Sauf que la garantie de soixante millions sur le bail de Wrocław reste chez nous tant que le bailleur ne nous libère pas. Et Kovant refuse de la reprendre.",
    "서류상으로는. 그런데 브로츠와프 리스 계약에 걸린 6,000만 유로 보증은 임대인이 풀어 주지 않는 한 우리한테 남아. 그리고 코반트는 그걸 떠안지 않겠대."),
(MA, "La fameuse garantie qu'on a découverte le premier jour, cachée dans une note annexe...", "우리가 첫날 발견한 그 유명한 보증이네. 주석에 숨어 있던..."),
(I, "Celle-là. Et Kovant exige un contrat d'approvisionnement de cinq ans : on leur rachèterait nos propres grille-pain douze pour cent plus cher. Sur cinq ans, environ quarante millions.",
    "바로 그거. 게다가 코반트는 5년짜리 공급 계약을 요구해. 우리가 만든 토스터를 12% 더 비싸게 되사게 되는 거지. 5년이면 약 4,000만 유로야."),
(MA, "Autrement dit, on vend la vache et on lui rachète le lait au prix fort.", "다시 말해, 소를 팔고 그 소의 우유를 비싼 값에 되사는 거네."),
(I, "Exactement. Le gain de la cession fond comme neige au soleil. Et les six cents postes : trente-six millions d'économies, cinquante-quatre millions de coût, et une grève assurée en pleine prévente de la Stéphanoise 2.",
    "정확해. 매각 이익은 햇볕 아래 눈처럼 녹아 버려. 그리고 600명 감원은 절감 3,600만, 비용 5,400만, 게다가 « 스테파누아즈 2 » 사전 판매 한가운데서 파업은 확정이고."),
(MA, "Redis-moi notre plan à nous. Je veux pouvoir le présenter jeudi sans regarder mes notes.", "우리 계획 다시 말해 줘. 목요일에 메모 안 보고 발표할 수 있게."),
(I, "Cent cinquante départs volontaires : neuf millions par an. Les idées des ouvriers sur le processus, quarante pour cent de défauts en moins : neuf millions. Les sept pour cent obtenus à Shenzhen : huit millions. Les frais généraux : cinq millions. Total : trente et un millions par an, sans licenciement contraint.",
    "자발적 퇴직 150명으로 연 900만. 공정에 대한 노동자들의 아이디어로 불량 40% 감소, 900만. 선전에서 따낸 7% 인하로 800만. 일반 관리비 500만. 합계 연 3,100만 유로, 강제 해고 없이."),
(MA, "Trente et un contre trente-six. Cinq millions d'écart, et six cents familles. Je sais ce que je défendrai.", "3,100만 대 3,600만. 차이는 500만, 그리고 600가구. 내가 뭘 지킬지는 알겠어."),
(I, "Sur les chiffres, on est d'accord. Le problème, ce n'est pas les chiffres, Mathieu. C'est la photo.", "숫자에선 우리 의견이 같아. 문제는 숫자가 아니야, 마티외. 사진이지."),
(MA, "Baptiste bluffe peut-être. S'il diffuse cette photo, c'est lui qui passera pour un maître chanteur. On pourrait attendre de voir s'il ose.",
     "바티스트가 허세를 부리는 걸 수도 있어. 그 사진을 퍼뜨리면 공갈범으로 보이는 건 그 사람이야. 감히 그럴지 지켜볼 수도 있잖아."),
(I, "Attendre. Évidemment. Et jeudi, en plein débat sur Wrocław, il pose une question innocente sur « l'indépendance de la direction financière », et tout le conseil se tourne vers moi.",
    "기다리자고. 역시. 그러다 목요일에 브로츠와프 토론 한복판에서 그가 '재무 부문의 독립성'에 대해 순진한 척 질문을 던지면, 이사회 전체가 나를 쳐다보겠지."),
(I, "Pas vers nous, Mathieu. Vers moi. Ce n'est pas toi qu'on soupçonnera d'avoir eu son poste grâce à l'autre. Je refuse que mes chiffres valent moins parce que je suis avec toi.",
    "우리가 아니라 나를, 마티외. 상대 덕분에 자리를 얻었다고 의심받을 사람은 네가 아니야. 내가 너와 사귄다는 이유로 내 숫자가 덜 믿음직해지는 건 용납 못 해."),
(MA, "Alors qu'est-ce que tu proposes ? Que l'un de nous démissionne ?", "그럼 뭘 제안하는데? 우리 중 하나가 사표를 내자고?"),
(I, "Personne ne démissionne. Mais je refuse qu'on vive avec un couteau sous la gorge jusqu'à l'assemblée générale.", "아무도 사표 안 내. 하지만 주주총회 때까지 목에 칼이 들어온 채로 지내는 건 거부할 거야."),
(None, "La tablette sonne. Appel vidéo : Hélène Vasseur.", "태블릿이 울린다. 영상통화, 엘렌 바쇠르다."),
(H, "Bonsoir, vous deux. Martine m'a dit que vous étiez encore au bureau, avec « la tête des mauvais jours ». Racontez.", "둘 다 안녕. 마르틴이 그러는데 아직 사무실에 있다며, '안 좋은 날 표정'을 하고. 얘기해 봐."),
(H, "Je vois. Je vous avais dit que je ne voulais rien savoir... Visiblement, je ne suis plus la seule à savoir. Et Arcane a parlé de « gouvernance », je suppose ?",
    "그렇구나. 내가 아무것도 알고 싶지 않다고 했었지... 보아하니 이제 아는 사람이 나만은 아니네. 그리고 아르칸이 '지배구조' 얘기를 했겠지?"),
(MA, "Mot pour mot. Hélène, qu'est-ce que vous feriez à notre place ?", "토씨 하나 안 틀리고요. 엘렌, 저희 입장이라면 어떻게 하시겠어요?"),
(H, "Je ne suis pas à votre place, je suis administratrice. Alors voici l'avis de l'administratrice : un secret qu'on révèle soi-même devient une information. Un secret qu'on vous arrache devient un scandale.",
    "난 너희 입장이 아니라 이사야. 그러니 이사로서 의견을 말할게. 스스로 밝힌 비밀은 정보가 되고, 남에게 빼앗긴 비밀은 스캔들이 돼."),
(I, "Donc on le dit nous-mêmes, au conseil. Avant Baptiste.", "그러니까 우리가 직접 이사회에 말하라는 거죠. 바티스트보다 먼저."),
(H, "Article neuf de la charte de déontologie : tout dirigeant déclare au conseil toute situation de conflit d'intérêts, même potentiel. Vous auriez dû le faire il y a un an. Mais mieux vaut tard que jamais, et mieux vaut jeudi qu'après une fuite.",
    "윤리강령 제9조. 모든 경영진은 잠재적인 것까지 포함해 모든 이해충돌 상황을 이사회에 신고한다. 1년 전에 했어야 했어. 하지만 늦더라도 안 하는 것보단 낫고, 유출된 뒤보단 목요일이 나아."),
(MA, "Et si le conseil décide que l'un de nous doit partir ?", "그런데 이사회가 우리 중 하나는 떠나야 한다고 결정하면요?"),
(H, "Alors vous partirez debout. Mais je ne crois pas qu'il le décide, à moins que vous ne lui donniez une raison de douter de vos chiffres. Écrivez ce soir une déclaration au président. Courte, factuelle, sans adjectifs.",
    "그럼 당당하게 떠나면 돼. 하지만 이사회가 그렇게 결정할 것 같진 않아. 너희가 숫자를 의심할 이유를 주지 않는 한은. 오늘 밤 의장 앞으로 신고서를 써. 짧게, 사실만, 형용사 없이."),
(I, "Sans adjectifs. Ça, je sais faire.", "형용사 없이. 그건 제 특기예요."),
(H, "Je sais. Et Mathieu... cette fois, ne repoussez pas la décision. Bonne nuit.", "알지. 그리고 마티외... 이번엔 결정을 미루지 마. 잘 자."),
(None, "L'écran devient noir. Mathieu prend le marqueur vert.", "화면이 꺼진다. 마티외가 초록 마커를 집어 든다."),
(MA, "Quel est le vrai problème ? Ce n'est pas la photo. C'est qu'on a laissé à Baptiste un secret à utiliser.", "진짜 문제는 무엇인가? 사진이 아니야. 바티스트한테 써먹을 비밀을 남겨 둔 거지."),
(I, "Qui décide ? Le conseil. Pas Baptiste. Et quoi qu'il arrive jeudi, on sort de cette salle ensemble.", "누가 결정하는가? 이사회. 바티스트가 아니라. 그리고 목요일에 무슨 일이 생기든, 우린 그 방을 함께 나오는 거야."),
(MA, "Ensemble. On écrit la déclaration maintenant. Et demain à l'aube, on va à l'usine : si le chiffre de six cents circule déjà, je veux que Josiane l'entende de ma bouche.",
     "함께. 지금 신고서를 쓰자. 그리고 내일 새벽엔 공장에 가. 600이라는 숫자가 벌써 돌고 있다면, 조지안이 내 입으로 듣게 하고 싶어."),

# ---------- 4. Terrain : la pointeuse ----------
(None, "Mercredi, 6 h 45. Usine de Saint-Étienne, changement d'équipe. Devant la pointeuse, un attroupement. Josiane Fabre brandit son téléphone.",
       "수요일 오전 6시 45분. 생테티엔 공장, 교대 시간. 출퇴근 기록기 앞에 사람들이 모여 있다. 조지안 파브르가 휴대폰을 흔들고 있다."),
(JF, "Ah, voilà la direction. Vous tombez bien. Depuis cinq heures du matin, ça tourne sur tous les téléphones : « Six cents postes supprimés à Saint-Étienne ». C'est vrai ou pas ?",
     "아, 경영진이 오셨네. 마침 잘 오셨어요. 새벽 5시부터 모든 휴대폰에 돌고 있어요. '생테티엔 일자리 600개 감축'. 사실이에요, 아니에요?"),
(MA, "Bonjour, madame Fabre. Ce n'est pas le plan de la direction. C'est la proposition d'un actionnaire, qui sera examinée demain au conseil. Je m'y opposerai.",
     "안녕하세요, 파브르 씨. 그건 경영진의 계획이 아닙니다. 한 주주의 제안이고, 내일 이사회에서 검토됩니다. 저는 반대할 겁니다."),
(JF, "Un actionnaire. Arcane, quoi. Et ça devrait me rassurer ? C'est eux qui vous ont mis là.", "한 주주라. 아르칸이라는 거잖아요. 그 말에 제가 안심해야 해요? 대표님을 그 자리에 앉힌 게 그 사람들인데."),
(MA, "C'est eux qui m'ont nommé, oui. Ce n'est pas pour autant que je travaille pour eux. Je travaille pour l'entreprise.", "저를 임명한 건 그들이 맞습니다. 그렇다고 제가 그들을 위해 일하는 건 아닙니다. 저는 회사를 위해 일합니다."),
(JF, "Joli. Je l'écrirai sur une banderole. Et comment ça a fuité ? Vous l'apprenez hier, et ce matin c'est partout.", "멋진 말이네요. 현수막에 써 드리죠. 그런데 어떻게 샌 거예요? 어제 아셨다는데 오늘 아침엔 온 사방에 퍼졌잖아요."),
(I, "Nous ne savons pas qui l'a fait fuiter, madame Fabre. Mais ce n'est pas un hasard si ça sort la veille du conseil. Quelqu'un veut que vous ayez peur, pour que la direction négocie sous pression.",
    "누가 흘렸는지는 모릅니다, 파브르 씨. 하지만 이사회 전날 터진 게 우연은 아니에요. 누군가 여러분이 겁먹기를 바라는 거예요. 경영진이 압박 속에서 협상하게 하려고요."),
(JF, "Eh bien, c'est réussi. J'ai quarante gars qui veulent débrayer à dix heures.", "그렇다면 성공했네요. 10시에 작업을 멈추겠다는 사람이 마흔 명이에요."),
(MA, "Je ne vous demande pas de me croire sur parole. Je vous demande vingt-quatre heures. Demain soir, après le conseil, je viens vous dire ici même ce qui a été voté.",
     "제 말만 믿어 달라는 게 아닙니다. 24시간만 주십시오. 내일 저녁, 이사회가 끝나면 바로 여기 와서 무엇이 의결됐는지 말씀드리겠습니다."),
(JF, "Ici, devant la pointeuse ?", "여기, 출퇴근 기록기 앞에서요?"),
(MA, "Ici. À vingt heures, à la relève de l'équipe de nuit. Devant tout le monde.", "여기서요. 저녁 8시, 야간조 교대 시간에. 모두가 보는 앞에서."),
(JF, "... Vingt-quatre heures. Pas une de plus. Et si vous ne venez pas, je n'empêcherai personne de débrayer.", "...24시간. 단 1시간도 더는 안 돼요. 그리고 안 오시면 작업 중단하겠다는 사람 아무도 안 말릴 거예요."),
(I, "Il viendra. Je... la direction s'y engage.", "올 거예요. 제가... 경영진이 약속드립니다."),
(None, "Josiane s'éloigne. Momo s'approche en s'essuyant les mains sur un chiffon.", "조지안이 멀어진다. 모모가 걸레에 손을 닦으며 다가온다."),
(MO, "Bonjour, patron. Bonjour, madame Marchetti. Elle aboie, la Josiane, mais si elle vous donne vingt-quatre heures, c'est qu'elle vous fait confiance. Un peu.",
     "안녕하세요, 사장님. 안녕하세요, 마르케티 이사님. 조지안이 짖긴 해도 24시간을 줬다는 건 믿는다는 거예요. 조금은요."),
(MA, "Merci, Momo. Et la ligne de la Stéphanoise ?", "고마워요, 모모. 스테파누아즈 라인은 어때요?"),
(MO, "Elle tourne. Avec nos idées de l'an dernier, on a quarante pour cent de rebuts en moins. Les gars sont fiers. Ce serait dommage de leur dire merci avec une lettre de licenciement.",
     "잘 돌아가요. 작년에 낸 우리 아이디어 덕분에 불량품이 40% 줄었어요. 다들 자랑스러워해요. 그런데 고맙다는 인사를 해고 통지서로 받는다면 안타까운 일이죠."),
(MA, "Il n'y aura pas de lettre pour ça. Pas tant que je serai là.", "그런 통지서는 없을 겁니다. 제가 있는 한은요."),
(MO, "Patron... je peux vous dire un truc ? Entre nous.", "사장님... 한 가지 말씀드려도 될까요? 우리끼리만."),
(MA, "Bien sûr, Momo.", "물론이죠, 모모."),
(MO, "Samedi soir, ma femme sortait du cinéma, place Jean-Jaurès. Elle vous a vus. Vous deux.", "토요일 저녁에 제 아내가 장조레스 광장 영화관에서 나오는 길이었어요. 두 분을 봤대요. 두 분 다."),
(None, "Inès se fige. Mathieu garde son calme.", "이네스가 얼어붙는다. 마티외는 침착함을 유지한다."),
(I, "Ah. Et... qu'est-ce qu'elle a dit, votre femme ?", "아. 그래서... 부인께서 뭐라고 하셨어요?"),
(MO, "Elle a dit : « Enfin un patron qui a un cœur. » Et puis que madame Marchetti était bien trop bien pour lui. Pardon, patron, c'est elle qui l'a dit.",
     "'드디어 심장이 있는 사장이 왔네'라고 했죠. 그리고 마르케티 이사님이 사장님한텐 너무 아깝다고요. 죄송해요, 사장님. 아내가 한 말이에요."),
(MA, "Votre femme a un excellent jugement, Momo.", "부인께서 안목이 아주 훌륭하시네요, 모모."),
(MO, "Chez nous, on ne fait pas d'histoires avec ça. Mais les gens parlent. Si vous avez un secret, il vaut mieux que vous le disiez avant que les autres le disent pour vous.",
     "우리 동네에선 그런 걸로 문제 삼진 않아요. 하지만 사람들은 말을 하죠. 비밀이 있으면 남들이 대신 말하기 전에 직접 말하는 게 나아요."),
(I, "C'est exactement le conseil qu'on nous a donné hier soir.", "어젯밤에 저희가 들은 조언이 바로 그거예요."),
(MO, "Alors c'était un bon conseil. Allez, je retourne à mes soupapes. Elles, au moins, elles ne parlent pas.", "그럼 좋은 조언이었네요. 자, 전 밸브한테 돌아갑니다. 걔들은 적어도 말은 안 하거든요."),

# ---------- 5. Le conseil d'administration ----------
(None, "Jeudi, 14 h. Salle du conseil, au dernier étage du siège. Au mur, le portrait du fondateur à côté d'une bicyclette de 1874. Neuf administrateurs autour de la table ; Baptiste est assis en retrait, comme censeur d'Arcane.",
       "목요일 오후 2시. 본사 꼭대기 층 이사회실. 벽에는 창업자의 초상화와 1874년산 자전거가 나란히 걸려 있다. 이사 아홉 명이 테이블에 둘러앉아 있고, 바티스트는 아르칸 측 참관인으로 뒤쪽에 앉아 있다."),
(HV, "La séance est ouverte. Avant l'ordre du jour, le directeur général m'a demandé la parole pour une déclaration. J'ai reçu votre lettre hier soir, monsieur Kessler. Je l'ai relue deux fois.",
     "회의를 시작하겠습니다. 안건에 앞서 대표이사가 신고할 사항이 있다며 발언을 요청했습니다. 어젯밤 편지는 받았습니다, 케슬레르 대표. 두 번 읽었어요."),
(MA, "Merci, monsieur le président. Madame Marchetti et moi souhaitons informer le conseil d'une situation personnelle, conformément à l'article neuf de la charte de déontologie.",
     "감사합니다, 의장님. 마르케티 이사와 저는 윤리강령 제9조에 따라 개인적인 상황 하나를 이사회에 알려 드리고자 합니다."),
(I, "Monsieur Kessler et moi avons une relation personnelle. Nous nous connaissions avant Verdier, et elle a commencé juste avant notre nomination. Nous ne l'avons pas déclarée jusqu'ici. C'était une erreur, et nous la corrigeons aujourd'hui.",
    "케슬레르 대표와 저는 개인적인 관계에 있습니다. Verdier에 오기 전부터 알던 사이이고, 이 관계는 저희가 임명되기 직전에 시작됐습니다. 지금까지 신고하지 않았습니다. 그건 잘못이었고, 오늘 바로잡습니다."),
(MA, "Nous ne demandons aucune indulgence. Nous demandons au conseil de fixer les règles qu'il jugera nécessaires, pour que personne ne puisse douter de l'indépendance de la direction financière.",
     "관용을 구하지 않겠습니다. 재무 부문의 독립성을 아무도 의심할 수 없도록, 이사회가 필요하다고 판단하는 규칙을 정해 주시기를 요청드립니다."),
(None, "Un murmure fait le tour de la table. Hubert Verdier retire ses lunettes.", "웅성거림이 테이블을 한 바퀴 돈다. 위베르 베르디에가 안경을 벗는다."),
(HV, "Eh bien. En quarante-cinq ans dans cette maison, j'ai entendu beaucoup de déclarations. Celle-là, jamais. Je ne vous cache pas que ça ne me plaît pas.",
     "허 참. 이 회사에서 45년 동안 많은 신고를 들어 봤지만, 이런 건 처음입니다. 마음에 들지 않는다는 걸 숨기진 않겠어요."),
(AU, "Je suis surpris, moi aussi. Monsieur Morel, vous qui avez travaillé avec eux chez Vasseur... vous étiez au courant ?", "저도 놀랐습니다. 모렐 씨, 바쇠르에서 이 두 사람과 함께 일했었죠... 알고 있었습니까?"),
(B, "Absolument pas. Mais puisque le sujet est sur la table, permettez-moi une question : comment le conseil pourrait-il se fier aux chiffres que nous allons examiner, sachant qu'ils sont préparés par la compagne du directeur général ?",
    "전혀요. 하지만 이 얘기가 나온 김에 질문 하나 드리죠. 곧 검토할 숫자들이 대표이사의 연인이 준비한 것이라는 걸 알면서, 이사회가 그 숫자를 어떻게 믿을 수 있겠습니까?"),
(I, "Ils sont préparés par la direction financière, monsieur Morel, et certifiés par les commissaires aux comptes. Posez toutes les questions que vous voulez : chaque chiffre est vérifiable.",
    "그 숫자는 재무 부문이 준비하고 회계감사인이 인증한 겁니다, 모렐 씨. 원하시는 질문은 다 하세요. 모든 숫자는 검증 가능합니다."),
(CV, "Si vous permettez, monsieur le président.", "괜찮으시다면, 의장님."),
(HV, "Claire, je t'en prie.", "클레르, 말해 보렴."),
(CV, "Je veux que ceci figure au procès-verbal. Avant-hier, plusieurs administrateurs ont reçu une photo anonyme de nos deux dirigeants. Moi aussi.",
     "이 말은 회의록에 남겨 주셨으면 합니다. 그저께 여러 이사가 우리 두 경영진의 익명 사진을 받았습니다. 저도 받았고요."),
(None, "Silence. Aubry jette un regard à Baptiste, qui feuillette son dossier.", "정적. 오브리가 바티스트를 힐끗 쳐다보고, 바티스트는 서류를 넘긴다."),
(CV, "Ce procédé est indigne de cette maison, d'où qu'il vienne. Madame Marchetti et monsieur Kessler, eux, ont choisi de nous le dire en face. Ça s'appelle de l'intégrité, et je ne vois pas pourquoi on les en punirait.",
     "그런 수법은 어디서 나왔든 이 회사에 걸맞지 않습니다. 반면 마르케티 이사와 케슬레르 대표는 우리 앞에서 직접 말하기로 했죠. 그걸 청렴이라고 부릅니다. 그 일로 두 사람을 벌할 이유는 없다고 봅니다."),
(AU, "Je tiens à préciser qu'Arcane n'a rien à voir avec cette photo.", "아르칸은 그 사진과 아무 관련이 없다는 점을 분명히 해 두겠습니다."),
(CV, "Je n'ai accusé personne, Frédéric. Concrètement, je propose trois mesures. Un : la rémunération, les objectifs et l'évaluation de la directrice financière seront fixés par le comité des rémunérations, que je préside, et non par le directeur général.",
     "아무도 비난하지 않았어요, 프레데리크. 구체적으로 세 가지 조치를 제안합니다. 하나, 재무이사의 보수와 목표, 평가는 대표이사가 아니라 제가 위원장인 보상위원회가 정합니다."),
(H, "Deux : le comité d'audit, que je préside, aura un accès direct à la directrice financière. Et les notes de frais du directeur général seront validées par moi, et non par elle.",
    "둘, 제가 위원장인 감사위원회는 재무이사와 직접 소통합니다. 그리고 대표이사의 경비 정산은 재무이사가 아니라 제가 승인합니다."),
(CV, "Trois : la situation est inscrite au registre des conflits d'intérêts, et les intéressés informeront le président de tout changement. Le reste ne regarde qu'eux.",
     "셋, 이 상황을 이해충돌 대장에 기재하고, 당사자들은 변동이 있으면 의장에게 알립니다. 그 밖의 일은 두 사람의 문제입니다."),
(HV, "Hm. Et le jour où ils se disputeront ? On aura une direction générale en guerre.", "흠. 그럼 둘이 싸우는 날엔? 경영진이 전쟁을 벌이겠군."),
(MA, "Monsieur le président, nous nous disputons déjà : sur les stocks, sur le plan social, sur les investissements. Madame Marchetti ne m'a jamais rien accordé parce que je le lui demandais. Ce serait plutôt l'inverse.",
     "의장님, 저희는 이미 다툽니다. 재고로, 구조조정안으로, 투자로요. 마르케티 이사는 제가 부탁했다는 이유로 뭔가를 들어준 적이 한 번도 없습니다. 오히려 그 반대에 가깝죠."),
(None, "Quelques sourires autour de la table. Même Hubert.", "테이블 여기저기서 미소가 번진다. 위베르조차."),
(HV, "Ça, je veux bien le croire. Je l'ai vue vous contredire en pleine séance. ... Je mets aux voix les trois mesures. Huit voix pour, une abstention : adoptées. Passons à la résolution d'Arcane.",
     "그건 믿을 만하군요. 회의 중에 대표에게 반박하는 걸 본 적이 있으니까. ...세 가지 조치를 표결에 부칩니다. 찬성 8, 기권 1, 가결. 아르칸의 결의안으로 넘어갑시다."),
(B, "Tout a été dit mardi à la direction : la cession de Wrocław à Kovant pour quatre-vingt-quinze millions, et six cents suppressions de postes à Saint-Étienne, soit trente-six millions d'économies par an.",
    "화요일에 경영진에게 다 말씀드렸습니다. 브로츠와프를 코반트에 9,500만 유로에 매각, 그리고 생테티엔 600명 감축, 즉 연 3,600만 유로 절감입니다."),
(I, "Avec votre permission, monsieur le président, trois chiffres que la résolution oublie. La garantie de soixante millions sur le bail de Wrocław, que Kovant refuse de reprendre. Un contrat d'approvisionnement à douze pour cent au-dessus de nos coûts : quarante millions sur cinq ans. Et cinquante-quatre millions de coût social.",
    "의장님, 허락해 주신다면 결의안이 빠뜨린 숫자 세 가지를 말씀드리겠습니다. 코반트가 떠안기를 거부한 브로츠와프 리스 보증 6,000만 유로. 원가보다 12% 비싼 공급 계약, 5년간 4,000만 유로. 그리고 사회적 비용 5,400만 유로입니다."),
(MA, "En face, notre plan : trente et un millions d'économies par an, sans licenciement contraint, et l'usine la plus rentable du groupe reste chez nous. Le dossier complet est dans vos classeurs.",
     "반면 저희 계획은 강제 해고 없이 연 3,100만 유로를 절감하고, 그룹에서 가장 수익성 높은 공장을 지킵니다. 자세한 자료는 바인더에 있습니다."),
(B, "Bien que ces chiffres soient séduisants, je me permets d'insister : ils n'engagent que ceux qui les ont préparés.", "그 숫자들이 매력적이긴 합니다만, 다시 한번 강조하겠습니다. 그 숫자는 준비한 사람들에게만 책임이 있는 겁니다."),
(HV, "Monsieur Morel, ces chiffres engagent la direction de cette entreprise. Et la direction vient de nous prouver qu'elle ne cache rien. Je n'en dirais pas autant de tout le monde autour de cette table.",
     "모렐 씨, 그 숫자는 이 회사 경영진이 책임지는 겁니다. 그리고 경영진은 방금 아무것도 숨기지 않는다는 걸 증명했어요. 이 테이블에 앉은 모두에 대해 그렇게 말할 수는 없겠지만."),
(HV, "Je mets la résolution aux voix. ... Trois voix pour, six contre : elle est rejetée. Le conseil demande à la direction un plan de désendettement complet pour le 15 décembre.",
     "결의안을 표결에 부칩니다. ...찬성 3, 반대 6, 부결입니다. 이사회는 경영진에게 12월 15일까지 종합적인 부채 감축 계획을 요구합니다."),
(AU, "Arcane prend acte. Mais je vous préviens, monsieur Kessler : un fonds ne lâche jamais. Nous reviendrons avec d'autres options.", "아르칸은 결과를 받아들입니다. 하지만 경고해 두죠, 케슬레르 대표. 펀드는 절대 물러서지 않습니다. 다른 선택지를 들고 다시 오겠습니다."),
(MA, "Et nous serons là pour en discuter, monsieur Aubry. Avec des chiffres.", "그때도 저희는 논의하러 이 자리에 있을 겁니다, 오브리 씨. 숫자를 들고요."),
(None, "La séance est levée. Dans le couloir, Claire Verdier arrête Inès.", "회의가 끝난다. 복도에서 클레르 베르디에가 이네스를 붙잡는다."),
(CV, "Pour ce que ça vaut : mes parents se sont rencontrés à l'atelier de montage de la Stéphanoise, en 1971. Mon oncle l'a oublié. Moi pas.", "별것 아닐지 모르지만, 우리 부모님은 1971년에 스테파누아즈 조립 작업장에서 만나셨어요. 삼촌은 잊으셨지만 저는 안 잊었죠."),
(I, "Merci, madame Verdier. Vraiment.", "감사합니다, 베르디에 이사님. 정말로요."),
(CV, "Ne me remerciez pas. Préparez-moi plutôt un plan de désendettement qui tienne debout, pour le 15 décembre.", "고마워할 것 없어요. 그보다 12월 15일까지 제대로 된 부채 감축 계획이나 준비해 주세요."),

# ---------- 6. Le soir : un avenir à deux ----------
(None, "22 h 30. Appartement d'Inès. Mathieu revient de l'usine. Inès est assise par terre, contre le canapé, Figaro sur les genoux.",
       "밤 10시 30분. 이네스의 아파트. 마티외가 공장에서 돌아온다. 이네스는 소파에 기대 바닥에 앉아 있고, 무릎 위엔 피가로가 있다."),
(I, "Alors, la pointeuse ?", "그래서, 출퇴근 기록기 앞은?"),
(MA, "J'ai annoncé le vote devant deux cents personnes. Josiane n'a pas souri, mais personne n'a débrayé. Chez elle, c'est presque une déclaration d'amitié.",
     "200명 앞에서 표결 결과를 발표했어. 조지안은 웃지 않았지만 아무도 작업을 멈추지 않았어. 조지안 기준으론 거의 우정 고백이지."),
(I, "Tu te rends compte ? Ce matin, on était un secret. Ce soir, on est une ligne dans un registre des conflits d'intérêts.", "실감 나? 오늘 아침까지 우린 비밀이었는데, 오늘 밤엔 이해충돌 대장의 한 줄이 됐어."),
(MA, "La ligne la plus romantique de l'histoire du droit des sociétés. ... Comment tu te sens ?", "회사법 역사상 가장 로맨틱한 한 줄이지. ...기분은 어때?"),
(I, "Légère. Et morte de peur. Les deux en même temps. Demain, tout le siège le saura.", "가벼워. 그리고 무서워 죽겠어. 둘 다 동시에. 내일이면 본사 전체가 알게 될 거야."),
(MA, "Martine le savait avant nous, à mon avis. Tu sais ce qui m'a le plus frappé ? Quand tu as dit « une relation personnelle » devant le conseil. C'est la première fois que je t'entendais parler de nous devant d'autres gens.",
     "내 생각엔 마르틴은 우리보다 먼저 알았어. 오늘 뭐가 제일 인상 깊었는지 알아? 네가 이사회 앞에서 '개인적인 관계'라고 말했을 때. 다른 사람들 앞에서 네가 '우리'에 대해 말하는 걸 처음 들었어."),
(I, "Pas très romantique, « une relation personnelle ».", "'개인적인 관계'라니, 별로 로맨틱하진 않지."),
(MA, "Pour une déclaration sans adjectifs, c'était parfait.", "형용사 없는 신고서치곤 완벽했어."),
(I, "Mathieu... maintenant qu'on n'a plus besoin de se cacher, qu'est-ce qu'on fait, nous ? Pas Verdier. Nous.", "마티외... 이제 숨을 필요가 없으니, 우리는 뭘 하지? Verdier 말고. 우리."),
(MA, "Tu veux parler d'avenir ? Toi, qui planifies la trésorerie à treize semaines et ta vie à trois jours ?", "미래 얘기를 하고 싶다고? 자금 계획은 13주 앞까지 세우면서 인생 계획은 사흘 앞까지만 세우는 네가?"),
(I, "Justement. Pour une fois, j'aimerais un prévisionnel un peu plus long.", "그러니까. 이번만큼은 좀 더 긴 전망을 세워 보고 싶어."),
(MA, "Alors je commence. D'abord, un seul appartement au lieu de deux, ici ou chez moi. Figaro tranchera. Un jour, une maison avec un jardin, pas loin d'une piscine pour toi et d'un parc pour moi.",
     "그럼 내가 먼저. 우선 집 두 개 대신 하나로. 여기든 우리 집이든, 피가로가 정하겠지. 언젠가는 정원 딸린 집. 너를 위한 수영장, 나를 위한 공원이 멀지 않은 곳에."),
(I, "Et après Verdier ? On ne dirigera pas cette maison toute notre vie.", "그럼 Verdier 이후엔? 평생 이 회사를 경영하진 않을 거잖아."),
(MA, "Après Verdier... je ne sais pas encore. Quelque chose qu'on construirait à deux. Mais d'abord, il faut que je le dise à ma grand-mère avant qu'elle l'apprenne par quelqu'un d'autre. Elle ne me le pardonnerait pas.",
     "Verdier 이후라... 아직 모르겠어. 우리 둘이 함께 만드는 무언가. 그런데 그 전에 할머니가 다른 사람한테 듣기 전에 내가 먼저 말씀드려야 해. 안 그러면 날 용서 안 하실 거야."),
(I, "Et moi à ma mère. Elle va dire qu'elle le savait depuis Marseille. ... Elle le savait depuis Marseille.", "그럼 난 엄마한테. 마르세유 때부터 알았다고 하시겠지. ...실제로 마르세유 때부터 아셨고."),
(None, "Mathieu s'assoit à côté d'elle. Figaro change aussitôt de genoux.", "마티외가 그녀 옆에 앉는다. 피가로가 곧바로 그의 무릎으로 옮겨 간다."),
(MA, "Inès, il y a une chose que je voudrais te redire, depuis Shenzhen...", "이네스, 선전 이후로 다시 말하고 싶은 게 하나 있는데..."),
(I, "Chut. Pas à Saint-Étienne. Tu as promis : à Paris. ... Pose plutôt ta dernière question, Strasbourg.", "쉿. 생테티엔에선 안 돼. 약속했잖아, 파리에서라고. ...그보다 마지막 질문이나 해, 스트라스부르."),
(MA, "D'accord. Que fait-on lundi ?", "알았어. 월요일엔 뭘 하지?"),
(I, "Lundi, on arrive ensemble au bureau, par la même rue. Et on dit bonjour à Martine en souriant. D'ici là, on éteint les téléphones tout le week-end.",
    "월요일엔 같은 길로 함께 출근하는 거야. 그리고 웃으면서 마르틴한테 인사하고. 그때까지 주말 내내 휴대폰은 꺼 두는 거고."),
(MA, "Tous les téléphones. Promis. Pas de conseil, pas d'Arcane, pas de Baptiste. Juste nous trois, avec Figaro.", "휴대폰 전부. 약속해. 이사회도, 아르칸도, 바티스트도 없이. 피가로까지 우리 셋만."),
(None, "Dimanche, 7 h 12. Sur la table de nuit, le téléphone d'Inès est éteint. Celui de Mathieu, qu'il a oublié d'éteindre, se met à vibrer. À l'écran : « Laure Fontanel — URGENT ».",
       "일요일 오전 7시 12분. 침대 옆 탁자 위, 이네스의 휴대폰은 꺼져 있다. 깜빡 잊고 끄지 않은 마티외의 휴대폰이 진동하기 시작한다. 화면에는 '로르 퐁타넬 — 긴급'."),
]

VOCAB = [
("B2", "un corbeau / une lettre anonyme", "익명 투서꾼 / 익명 편지", "클루조의 영화 『Le Corbeau』(1943)에서 유래. « Un ami qui vous veut du bien »은 익명 투서의 전형적인 서명."),
("B1", "un téléobjectif", "망원렌즈", "objectif = 렌즈. 파파라치·몰래 찍은 사진 이야기에 자주 등장."),
("B2", "sous le coup de la colère", "홧김에, 화가 난 김에", "sous le coup de + 감정 = ~에 휩싸인 상태로. sous le coup de l'émotion."),
("B2", "à tête reposée", "차분하게, 머리를 식힌 뒤", "On en reparle à tête reposée. 중요한 결정을 하루 미룰 때 쓰는 표현."),
("B2", "la cession (d'une usine, d'une filiale)", "(공장·자회사의) 매각, 양도", "céder une usine. 법률·M&A 문서에서는 vente보다 cession을 주로 쓴다."),
("B2", "une offre ferme", "확정 제안, 구속력 있는 제안", "↔ une offre indicative(비구속 제안). M&A 협상 단계 구분의 핵심 어휘."),
("C1", "rester au milieu du gué", "일을 하다 말다, 어중간한 데서 멈추다", "gué = 강의 얕은 여울. 개혁을 반쯤 하다 멈췄다고 비판할 때."),
("B2", "la marge d'EBITDA (l'EBE)", "EBITDA 마진(상각 전 영업이익률)", "프랑스 회계 용어는 EBE(excédent brut d'exploitation). 매각가는 흔히 EBITDA의 몇 배(un multiple)로 표현."),
("B2", "se manifester", "나서다, 의사를 밝히다", "Personne d'autre ne s'est manifesté. 입찰자·후보자·증인이 나타날 때."),
("C1", "dans le dos de qn", "~ 몰래, ~를 따돌리고", "négocier / agir dans le dos de la direction. 신뢰를 깨는 행동을 비판할 때."),
("B2", "Où voulez-vous en venir ?", "무슨 말씀을 하시려는 거죠?", "en venir à = (결국) ~에 이르다. 상대의 숨은 의도를 캐물을 때. 반말: Où tu veux en venir ?"),
("B2", "se fier à qn / qc", "~를 믿다, 신뢰하다", "faire confiance à와 비슷하지만 더 격식. On ne peut pas se fier à ces chiffres."),
("B2", "un maître chanteur / le chantage", "공갈범 / 공갈, 협박", "faire du chantage à qn. chanter(노래하다)와 같은 어원의 비유적 표현."),
("C1", "avoir le couteau sous la gorge", "목에 칼이 들어오다, 궁지에 몰리다", "강요된 상황에서 결정해야 할 때. On ne négocie pas le couteau sous la gorge."),
("B2", "fondre comme neige au soleil", "햇볕 아래 눈처럼 녹아 버리다", "돈·이익·저축이 순식간에 사라질 때 쓰는 관용구."),
("B2", "la charte de déontologie", "윤리강령", "déontologie = 직업 윤리. 이사회 운영규정(règlement intérieur)과 함께 지배구조 문서의 기본."),
("B1", "Mieux vaut tard que jamais.", "늦더라도 안 하는 것보단 낫다", "mieux vaut A que B 구조. 엘렌은 이를 비틀어 « mieux vaut jeudi qu'après une fuite »라고 함."),
("B2", "faire fuiter (une information)", "(정보를) 흘리다, 유출하다", "fuiter = 새어 나가다. 명사 une fuite. La nouvelle a fuité dans la presse."),
("B2", "débrayer / un débrayage", "(잠시) 작업을 중단하다 / 짧은 파업", "원래 '클러치를 떼다'라는 뜻. 몇 시간 단위의 짧은 작업 중단을 가리킨다."),
("B1", "la pointeuse", "출퇴근 기록기", "pointer = 출퇴근을 찍다. 공장에서는 모두가 모이는 상징적인 장소."),
("C1", "un censeur", "(이사회의) 참관인, 옵서버", "의결권 없이 이사회에 참석하는 자리. 정관(statuts)으로 둘 수 있으며 펀드가 자주 활용한다."),
("B2", "figurer au procès-verbal", "회의록에 기재되다", "le procès-verbal(PV) = 회의록. Je veux que ceci figure au PV."),
("B2", "prendre acte (de qc)", "(~을) 공식적으로 확인하다, 받아들이다", "동의는 아니지만 결과를 인정한다는 격식 표현. Le conseil prend acte de votre déclaration."),
("B2", "Ça ne regarde que nous / qu'eux.", "그건 우리(그들)만의 일이다", "regarder = ~와 관계되다. Ça ne te regarde pas ! = 네가 상관할 일 아니야!"),
("B2", "un prévisionnel", "(재무) 전망, 예측 계획", "un prévisionnel de trésorerie = 자금 수지 전망. 이네스는 이를 연애에 빗대어 씀."),
]

GRAM = [
("B2", "접속법 ①: bien que / à moins que (+ 허사 ne)",
 "« Bien que je n'aie rien contre l'amour, je doute que Hubert Verdier soit aussi moderne que moi. » « Bien que ces chiffres soient séduisants, je me permets d'insister. » bien que(~이긴 하지만) 뒤에는 늘 접속법. « à moins que la direction ne devienne plus raisonnable » « à moins que vous ne lui donniez une raison de douter » à moins que(~하지 않는 한) 뒤의 ne는 부정이 아닌 '허사 ne(ne explétif)'로, 격식체에서 붙이며 의미는 바뀌지 않는다. avant que, de crainte que 뒤에도 쓸 수 있다."),
("B2", "접속법 ②: 목적·시간·부대상황 — pour que, avant que, sans que",
 "« pour que personne ne puisse douter de l'indépendance de la direction financière » « pour que la direction négocie sous pression » « avant que les autres le disent pour vous » « avant qu'elle l'apprenne par quelqu'un d'autre » « Vous avez négocié avec Kovant sans que la direction générale en soit informée. » 주어가 같으면 부정사로 바꾼다: pour réfléchir, avant de partir, sans prévenir. sans que는 '~가 모르는 사이에, ~하지 않은 채'라는 비판적 뉘앙스를 만들기 좋다."),
("B2", "접속법 ③: 의지·거부·의심 뒤",
 "« Quelqu'un veut que vous ayez peur. » « Je refuse que mes chiffres valent moins... » « je refuse qu'on vive avec un couteau sous la gorge » « je doute que Hubert Verdier soit aussi moderne » « Je veux que ceci figure au procès-verbal. » vouloir / refuser / douter 뒤 que절은 접속법. 의견 동사의 부정도 접속법: « je ne crois pas qu'il le décide »(긍정 je crois qu'il le décidera는 직설법). 엘렌의 문장에서 이 대비를 확인할 수 있다."),
("C1", "양보의 부정관계사: d'où que / quoi que / qui que + 접속법",
 "« Ce procédé est indigne de cette maison, d'où qu'il vienne. »(어디서 나왔든) « quoi qu'il arrive jeudi, on sort de cette salle ensemble »(무슨 일이 일어나든). 'X가 무엇이든/누구든/어디서든'이라는 양보를 나타내며 항상 접속법을 쓴다. qui que vous soyez(당신이 누구든), où que tu ailles(네가 어디 가든). quoi que(무엇이든)와 quoique(비록 ~지만)는 철자와 뜻이 다르니 주의."),
("B2", "압박과 반론의 표현",
 "압박: « Où voulez-vous en venir ? » « Je me permets d'insister » « jeudi risque d'être une longue journée » « Je n'ai jamais dit ça. » 반론: « Avec votre permission, trois chiffres que la résolution oublie. » « Ce n'est pas pour autant que je travaille pour eux. »(그렇다고 해서 ~인 것은 아니다) « Explorer, oui. Négocier dans le dos de la direction, c'est autre chose. »(A는 인정, B는 별개 — 양보 후 반박의 전형). 바티스트처럼 조건법·암시로 위협하는 화법과, 이네스처럼 숫자로 정면 반박하는 화법을 비교해 보자."),
("B2", "조건법 과거와 전미래: 후회와 결과의 시점",
 "« Vous auriez dû le faire il y a un an. »(조건법 과거 = 하지 않은 일에 대한 비판·후회) / « on leur rachèterait nos propres grille-pain »(조건법 현재 = 매각한다면 생길 일) / « Je n'en dirais pas autant de tout le monde »(완곡한 단언). 반면 « vous partirez debout »는 단순미래, « Quand je serai installé... » 같은 전미래(futur antérieur)는 '미래의 한 시점 이전에 완료될 일'을 말한다: Quand le conseil aura voté, je viendrai vous voir."),
("B2", "mieux vaut A que B / il vaut mieux que + 접속법",
 "« Mieux vaut tard que jamais, et mieux vaut jeudi qu'après une fuite. » 관사 없이 문두에 오는 mieux vaut는 속담·격언 같은 간결한 문체다. 절이 이어지면 il vaut mieux que + 접속법: « il vaut mieux que vous le disiez avant que les autres le disent pour vous. » 부정사로도 가능: Il vaut mieux le dire soi-même."),
("B2", "공적인 vous와 사적인 tu의 경계",
 "« Allons, Inès... pardon, madame Marchetti. »(바티스트의 의도적 '실수') « Baptiste. Deux minutes. Sans les « madame Marchetti ». »(tu로 넘어가자는 신호) « Il viendra. Je... la direction s'y engage. »(사적인 '나'를 공적인 '경영진'으로 고쳐 말함) 이사회에서는 끝까지 « Monsieur Kessler et moi », « Madame Marchetti ne m'a jamais rien accordé »처럼 3인칭·성+직함을 쓴다. 관계를 공개해도 회의석상의 격식은 유지된다는 점이 핵심이다."),
]

CULTURE = [
("『까마귀(Le Corbeau)』와 익명 투서",
 "앙리조르주 클루조 감독의 영화 『Le Corbeau』(1943)는 '까마귀'라고 서명된 익명 편지들이 작은 마을을 의심과 증오로 몰아넣는 이야기다. 이 영화 이후 프랑스어에서 corbeau는 '익명 투서꾼'을 뜻하는 일상어가 되었고, 언론은 지금도 익명 협박 편지 사건을 « l'affaire du corbeau »라고 부른다. « Un ami qui vous veut du bien »(당신이 잘되길 바라는 친구가)은 익명 편지의 상투적인 서명으로, 반어적으로 '악의적인 고자질'을 가리키는 농담으로도 쓰인다."),
("프랑스 기업의 이사회와 이해충돌 관리",
 "이사회를 둔 주식회사(SA à conseil d'administration)는 보통 이사회 운영규정이나 윤리강령에 '이해충돌 상황이 생기면 이사회에 신고하고 관련 심의·표결에서 빠진다'는 원칙을 둔다. 상장사들이 참고하는 AFEP-MEDEF 기업지배구조 규약도 같은 원칙을 권고한다. 감사위원회·보상위원회 같은 전문 위원회는 독립 이사가 이끄는 경우가 많고, 정관에 따라 의결권 없는 참관인(censeur)을 둘 수도 있어 투자 펀드가 이 자리를 활용하곤 한다. 친밀한 관계 자체가 위법은 아니며, 중요한 것은 보수·평가·지출 승인 같은 결정 라인을 분리하는 것이다."),
("직장 내 연애와 사생활 보호",
 "프랑스 민법 제9조는 '모든 사람은 사생활을 존중받을 권리가 있다'고 규정하고, 노동법(Code du travail L1121-1)은 업무상 정당하고 비례적인 경우가 아니면 회사가 직원의 개인적 자유를 제한할 수 없다고 정한다. 그래서 프랑스 기업은 사내 연애 자체를 금지하기 어렵고, 대신 상하관계나 이해충돌이 생기는 경우에만 신고·보직 조정을 요구하는 식으로 관리한다. 연애 사실을 몰래 촬영해 퍼뜨리는 행위는 오히려 사생활 침해로 문제가 될 수 있다."),
]
