# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H = "Inès", "Mathieu", "Hélène"
L, RC, Y, SH, MO, MR = "Laure", "Robert", "Yann", "Samia", "Momo", "Martine"
NP, AU2 = "Peyron", "Aurélie"
CV, HV, AU, G, OD = "Claire", "Hubert", "Aubry", "Garrigue", "Mamie"

META = {
    "part": 2, "ep": 26,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Rappel produit",
    "title_ko": "제품 리콜",
    "place": "생테티엔 자쿠아르 지구 이네스의 아파트 · Verdier Industries 본사 위기 대응실·R&D 실험실 · 피르미니 페롱 부인 댁 · 리옹 방송국 스튜디오 · 시청 근처 마티외의 아파트 / 10월, 일요일~화요일",
    "chars": "이네스, 마티외, 엘렌, 로르 퐁타넬(홍보 이사), 로베르 샤잘(공장장), 이얀 케르브라(R&D 책임자), 사미아 아다드(정보보안 책임자), 모모 벨카셈(숙련공), 마르틴 로슈(대표 비서), 니콜 페롱(피해 고객), 오렐리(페롱 부인의 딸), 위베르·클레르 베르디에, 프레데리크 오브리, 엘리즈 가리그(TV 기자), 오딜 할머니",
    "work": "« La Stéphanoise » 밸브 결함으로 화상 사고 3건 — 출하 중단, 원인 조사(5월 랜섬웨어 때 종이에 적은 부품 대체 기록이 시스템에 다시 입력되지 않음), 12만 대 리콜(600만 유로), TV 생방송 공개 사과",
    "life": "일요일 아침 라디오 뉴스와 망친 스크램블드에그, 피해 고객 댁 방문, 콜마르 오딜 할머니의 응원 전화와 이네스와의 첫 통화",
    "focus": "사과·책임 표현, 수동태(être + p.p. + par, 조건법 과거 수동), 수동의 대안(on, se faire, 대명동사), 언론 어휘·조건법(전언), ne... que, 시간 접속사(tant que, dès que, chaque fois que), en vouloir à qn de + 부정사 과거",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제27화 Racheter l'allemand — 스트라스부르에서 슈투트가르트로 가는 차 안, 후계자 없는 독일 주방가전 회사 하우스만 인수 검토, 그리고 돌아오는 길 콜마르 오딜 할머니 댁의 타르트 플랑베.",
}

D = [
# ---------- 1. Ouverture : la radio du dimanche ----------
(None, "Un dimanche d'octobre, 8 h. Saint-Étienne, quartier Jacquard. Dans la cuisine d'Inès, Mathieu prépare des œufs brouillés ; Figaro surveille la poêle. La radio est allumée.",
       "10월의 어느 일요일 오전 8시. 생테티엔 자쿠아르 지구. 이네스의 부엌에서 마티외가 스크램블드에그를 만들고, 피가로는 프라이팬을 감시하고 있다. 라디오가 켜져 있다."),
(MA, "Figaro, recule. Ce sont mes œufs, pas les tiens. Inès, il me regarde comme si j'étais un intrus.", "피가로, 물러서. 이건 내 달걀이야, 네 거 아니고. 이네스, 얘가 날 침입자 보듯 쳐다봐."),
(I, "Tu es un intrus. Seulement, depuis le conseil du mois dernier, tu es un intrus officiel, inscrit au registre des conflits d'intérêts.", "넌 침입자 맞아. 다만 지난달 이사회 이후로는 이해충돌 대장에 등록된 공식 침입자지."),
(MA, "« Relation personnelle déclarée conformément à la charte de déontologie. » Le plus beau poème qu'on m'ait jamais écrit.", "'윤리 강령에 따라 신고된 개인적 관계.' 내가 받아 본 시 중에 제일 아름다운 시야."),
(I, "Chut ! Écoute la radio... Ils ont dit « Verdier ».", "쉿! 라디오 들어 봐... '베르디에'라고 했어."),
(None, "« ... Une habitante de Firminy, dans la Loire, a été brûlée à la main jeudi soir par le jet de vapeur de son autocuiseur. Selon nos informations, deux autres accidents similaires auraient eu lieu à Lyon et à Clermont-Ferrand. Tous impliqueraient le même modèle : La Stéphanoise, de Verdier Industries. »",
       "'...루아르 도 피르미니의 한 주민이 목요일 저녁 압력솥에서 뿜어져 나온 증기에 손을 데었습니다. 본사 취재에 따르면 리옹과 클레르몽페랑에서도 비슷한 사고가 두 건 더 있었던 것으로 알려졌습니다. 모두 같은 모델, 베르디에 앵뒤스트리의 라 스테파누아즈와 관련된 것으로 보입니다.'"),
(MA, "Trois accidents ? Et on l'apprend par la radio, un dimanche matin ?", "사고가 세 건? 그런데 우리가 그걸 일요일 아침에 라디오로 알게 된다고?"),
(I, "« Selon nos informations »... Ça veut dire qu'un journaliste a eu l'information avant nous. Ce n'est pas normal.", "'본사 취재에 따르면'... 기자가 우리보다 먼저 정보를 얻었다는 뜻이야. 이건 정상이 아니야."),
(MA, "C'est Laure. ... Oui, Laure, on vient d'entendre. ... Combien d'appels ? ... D'accord. Cellule de crise au siège à onze heures. Prévenez Robert et Yann.",
     "로르야. ...네, 로르, 방금 들었어요. ...전화가 몇 통이나요? ...알겠어요. 11시에 본사에서 위기 대응 회의. 로베르랑 이얀한테 알려 주세요."),
(I, "Martine m'écrit aussi : « J'arrive au bureau. J'ai prévenu tout le monde. Je me doutais que vous seriez ensemble, alors je n'appelle qu'un numéro. »",
    "마르틴도 문자했어. '사무실로 가는 중이에요. 다들 연락해 뒀어요. 두 분이 함께 계실 것 같아서 한 번호로만 연락드려요.'"),
(MA, "Trente ans de maison, et elle a toujours un coup d'avance sur nous.", "30년 근속에, 여전히 우리보다 한 수 앞서 있네."),
(I, "Mathieu, la Stéphanoise... C'est le produit que tout le monde a chez soi. Ma mère en a une à Marseille.", "마티외, 스테파누아즈는... 모든 집에 다 있는 제품이야. 우리 엄마도 마르세유에 하나 있어."),
(MA, "Et ma grand-mère fait sa soupe dedans depuis cinquante ans. Elle doit déjà être au courant, elle écoute la radio dès six heures.", "그리고 우리 할머니는 50년째 거기다 수프를 끓이셔. 벌써 아셨을 거야, 아침 6시부터 라디오를 들으시거든."),
(I, "Alors, on fait quoi ? On attend d'en savoir plus, ou on bloque tout de suite les expéditions ?", "그래서 어떻게 해? 더 알아볼 때까지 기다려, 아니면 지금 바로 출하를 막아?"),
(MA, "On bloque. Si on attend d'être sûrs, il y aura peut-être un quatrième accident pendant qu'on vérifie.", "막아. 확실해질 때까지 기다리면, 우리가 확인하는 동안 네 번째 사고가 날 수도 있어."),
(I, "Ça va coûter cher. Mais je suis d'accord. Je prends la voiture. Tu finis tes œufs ?", "돈이 많이 들 거야. 그래도 동의해. 차 가져갈게. 달걀은 마저 먹을 거야?"),
(MA, "Mes œufs, Figaro s'en est occupé. On y va.", "내 달걀은 피가로가 처리했어. 가자."),

# ---------- 2. Cellule de crise ----------
(None, "11 h. Siège de Verdier Industries, salle du conseil transformée en cellule de crise. Martine a apporté du café et un tableau blanc. Autour de la table : Laure Fontanel, Robert Chazal, Yann Kerbrat.",
       "오전 11시. Verdier Industries 본사, 위기 대응실로 바뀐 이사회실. 마르틴이 커피와 화이트보드를 가져다 놓았다. 테이블에는 로르 퐁타넬, 로베르 샤잘, 이얀 케르브라가 앉아 있다."),
(MA, "Merci d'être venus un dimanche. Nous allons travailler dans l'ordre : d'abord les faits, ensuite les clients, ensuite la presse. Laure, que savons-nous ?",
     "일요일에 나와 주셔서 감사합니다. 순서대로 하겠습니다. 먼저 사실, 그다음 고객, 그다음 언론. 로르, 우리가 아는 게 뭐죠?"),
(L, "Trois accidents en dix jours. Jeudi soir à Firminy, une dame de soixante-huit ans, Mme Peyron : brûlures au deuxième degré à la main et à l'avant-bras. Elle est sortie du CHU hier.",
    "열흘 동안 사고 세 건입니다. 목요일 저녁 피르미니에서 68세 페롱 부인이 손과 팔뚝에 2도 화상을 입었습니다. 어제 대학병원에서 퇴원했고요."),
(I, "Et les deux autres ?", "나머지 두 건은요?"),
(L, "Un homme de trente-quatre ans brûlé à la main à Lyon, une étudiante brûlée au poignet à Clermont. Soignés aux urgences, et rentrés chez eux le soir même.",
    "리옹에서 34세 남성이 손에, 클레르몽에서 여대생이 손목에 화상을 입었습니다. 응급실에서 치료받고 그날 저녁 귀가했어요."),
(MA, "Et pourquoi apprenons-nous tout cela par la radio ?", "그런데 왜 우리가 이 모든 걸 라디오로 알게 된 거죠?"),
(L, "La fille de Mme Peyron a publié des photos de la brûlure vendredi soir. Elles ont été partagées des milliers de fois, et un quotidien régional a fait le lien avec les deux autres cas.",
    "페롱 부인의 딸이 금요일 저녁 화상 사진을 올렸습니다. 수천 번 공유됐고, 한 지역 일간지가 나머지 두 건과 연결 지었어요."),
(I, "Les deux autres cas étaient connus chez nous ?", "나머지 두 건은 우리 쪽에서도 알고 있었나요?"),
(MR, "J'ai vérifié ce matin avec le service client, madame Marchetti. Deux réclamations sont arrivées en septembre. Elles ont été classées « mauvaise utilisation ». Personne ne les a remontées.",
     "오늘 아침 고객 서비스팀에 확인했습니다, 마르케티 이사님. 9월에 불만 접수가 두 건 들어왔어요. '사용자 부주의'로 분류됐고요. 아무도 위로 보고하지 않았습니다."),
(MA, "Classées « mauvaise utilisation »... Par qui ?", "'사용자 부주의'로 분류됐다니... 누가요?"),
(MR, "Par le logiciel, monsieur Kessler. Quand le client ne coche pas la case « défaut constaté », la réclamation part dans la mauvaise file. C'est comme ça depuis des années.",
     "소프트웨어가요, 케슬레르 대표님. 고객이 '결함 확인' 칸에 체크하지 않으면 불만 접수가 엉뚱한 대기열로 가요. 몇 년째 그래 왔어요."),
(I, "Donc deux clients brûlés ont été rangés dans une case. Il faudra corriger ça, mais pas ce matin. Yann, que dit la technique ?", "그러니까 화상 입은 고객 두 명이 칸 하나에 정리돼 버린 거군요. 고쳐야겠지만, 오늘 아침 일은 아니에요. 이얀, 기술적으로는요?"),
(Y, "Les trois décrivent la même chose : à la décompression, quand on tourne le sélecteur, un jet de vapeur sort violemment sur le côté au lieu de monter droit. Ça fait penser à la soupape de fonctionnement.",
    "세 사람 모두 같은 걸 묘사합니다. 감압할 때 선택 다이얼을 돌리면, 증기가 위로 곧게 올라가지 않고 옆으로 세차게 뿜어져 나온다고요. 작동 밸브가 의심됩니다."),
(MA, "Expliquez-moi comme si j'étais un client. Comment ça marche, une soupape ?", "제가 고객이라고 생각하고 설명해 주세요. 밸브는 어떻게 작동하죠?"),
(Y, "Elle laisse échapper la vapeur dès que la pression dépasse zéro virgule huit bar. Si elle s'ouvre trop tard, la pression monte plus haut que prévu, et la vapeur sort d'un coup, beaucoup plus fort.",
    "압력이 0.8바를 넘는 순간 증기를 빼 줍니다. 너무 늦게 열리면 압력이 예정보다 높이 올라가고, 증기가 한꺼번에 훨씬 세게 나오죠."),
(RC, "Avant de parler de défaut, je veux voir les autocuiseurs. Ça fait plus de soixante ans qu'on fait la Stéphanoise. Mes gars ne vont pas se faire accuser sans preuve.",
     "결함 얘기를 하기 전에 압력솥부터 보고 싶습니다. 스테파누아즈를 만든 지 60년이 넘었어요. 우리 사람들이 증거도 없이 비난받게 둘 순 없습니다."),
(MA, "Personne n'accuse vos équipes, Robert. Mais tant qu'on ne sait pas, on protège les clients. À partir de maintenant, plus aucune Stéphanoise ne sort de l'usine ni des entrepôts.",
     "아무도 당신 팀을 비난하지 않아요, 로베르. 하지만 모르는 동안에는 고객을 보호해야 합니다. 지금부터 스테파누아즈는 한 대도 공장과 창고 밖으로 나가지 않습니다."),
(RC, "Bloquer les expéditions ? On a quarante mille Stéphanoise entre nos entrepôts et les magasins !", "출하를 막는다고요? 창고랑 매장에 스테파누아즈가 4만 대나 있어요!"),
(I, "Je sais, monsieur Chazal. Je préfère quarante mille autocuiseurs bloqués à un quatrième accident. Yann, les trois appareils accidentés ont-ils un point commun ?",
    "압니다, 샤잘 공장장님. 네 번째 사고보다는 압력솥 4만 대가 묶이는 게 낫습니다. 이얀, 사고 난 세 대에 공통점이 있나요?"),
(Y, "D'après les numéros de lot, les trois ont été fabriqués ici, à Saint-Étienne, sur la ligne six litres, entre juin et septembre. Mais pas dans les mêmes semaines. C'est bizarre.",
    "로트 번호로 보면 세 대 모두 여기 생테티엔의 6리터 라인에서 6월에서 9월 사이에 만들어졌습니다. 그런데 같은 주가 아니에요. 이상합니다."),
(L, "J'ai déjà quarante demandes de journalistes. Il faut un communiqué avant midi. J'ai préparé une proposition : « Verdier Industries regrette les désagréments signalés par certains utilisateurs... »",
    "벌써 기자 요청이 40건입니다. 정오 전에 보도자료가 필요해요. 초안을 준비했습니다. 'Verdier Industries는 일부 사용자가 신고한 불편 사항에 유감을 표하며...'"),
(MA, "Les désagréments ? Laure, une femme de soixante-huit ans a la main brûlée. Ce n'est pas un désagrément.", "불편 사항이요? 로르, 68세 여성이 손에 화상을 입었어요. 그건 불편 사항이 아닙니다."),
(L, "Je sais, monsieur Kessler. Mais nos avocats m'ont demandé de ne rien reconnaître tant que l'expertise n'a pas été faite.", "압니다, 대표님. 하지만 변호사들이 감정이 끝날 때까지 아무것도 인정하지 말라고 했어요."),
(I, "On peut ne pas tout savoir et quand même dire la vérité. On écrit ce qui est établi, et seulement ce qui est établi : trois accidents, un modèle, des ventes suspendues.",
    "모든 걸 알지 못해도 진실은 말할 수 있어요. 확인된 것만, 확인된 것만 씁니다. 사고 세 건, 모델 하나, 판매 중단."),
(MA, "Et une consigne claire pour les clients : si votre Stéphanoise a été fabriquée depuis juin, ne l'utilisez plus en attendant nos instructions. Avec un numéro vert.",
     "그리고 고객에게 분명한 지침을. 6월 이후 제조된 스테파누아즈라면 저희 안내가 있을 때까지 사용을 중단해 달라고요. 무료 전화번호와 함께."),
(I, "Et il faut déclarer le problème aux autorités aujourd'hui, sur RappelConso et auprès de la DGCCRF. Si nous attendons lundi, on dira que nous avons caché quelque chose.",
    "그리고 오늘 당국에 신고해야 합니다. RappelConso와 소비자보호국에요. 월요일까지 기다리면 우리가 뭔가 숨겼다는 말이 나올 거예요."),
(L, "Si on déclare aujourd'hui, ça devient officiel. Ce sera dans tous les journaux demain matin.", "오늘 신고하면 공식화됩니다. 내일 아침 모든 신문에 실릴 거예요."),
(MA, "Ce sera dans les journaux de toute façon. La seule question, c'est de savoir si c'est nous qui l'annonçons, ou si on nous l'annonce.", "어차피 신문엔 실려요. 유일한 문제는 우리가 발표하느냐, 아니면 남이 우리에게 알려 주느냐입니다."),
(I, "Je m'occupe aussi du centre d'appels : notre prestataire peut ouvrir une ligne en quatre heures. Je l'appelle dès la fin de la réunion.", "콜센터도 제가 맡겠습니다. 협력 업체가 네 시간 안에 회선을 열 수 있어요. 회의 끝나자마자 전화하겠습니다."),
(Y, "Je fais venir les trois appareils au labo, et je teste dès ce soir des soupapes prises au hasard dans le stock.", "사고 난 세 대를 실험실로 가져오고, 오늘 저녁부터 재고에서 무작위로 뽑은 밸브를 시험하겠습니다."),
(MA, "Parfait. Martine, trouvez-moi le numéro de Mme Peyron. Je voudrais aller la voir. Pas pour la presse, sans caméra. Pour m'excuser.", "좋습니다. 마르틴, 페롱 부인 연락처를 찾아 주세요. 찾아뵙고 싶습니다. 언론용이 아니라, 카메라 없이. 사과하러요."),

# ---------- 3. Analyse : la feuille de Momo ----------
(None, "Lundi, 18 h. Laboratoire de R&D. Sur l'établi, une rangée de soupapes démontées. Yann a les traits tirés.", "월요일 오후 6시. R&D 실험실. 작업대 위에 분해된 밸브가 한 줄로 놓여 있다. 이얀은 초췌한 얼굴이다."),
(Y, "J'ai démonté les trois appareils accidentés et testé deux cents soupapes du stock. Normalement, elles s'ouvrent à zéro virgule huit bar. Les trois soupapes accidentées s'ouvrent à un virgule un. Et dans le stock, j'en ai trouvé quatorze comme elles.",
    "사고 난 세 대를 분해하고 재고 밸브 200개를 시험했습니다. 정상이라면 0.8바에서 열려요. 사고 난 세 개는 1.1바에서 열립니다. 그리고 재고에서도 그런 게 14개 나왔어요."),
(MA, "Un virgule un au lieu de zéro virgule huit. Ça paraît peu.", "0.8 대신 1.1이라. 별 차이 아닌 것 같은데요."),
(Y, "C'est presque quarante pour cent de pression en plus. La soupape de sécurité ne se déclenche qu'à un virgule six, donc l'appareil n'explose pas. Mais à la décompression, le jet est beaucoup plus violent. Et ces dix-sept soupapes ont un point commun : un ressort de la mauvaise référence. Celui de la cocotte de huit litres.",
    "압력이 40% 가까이 더 높은 겁니다. 안전밸브는 1.6바에서야 작동하니 기기가 터지지는 않아요. 하지만 감압할 때 증기가 훨씬 세게 나옵니다. 그리고 이 밸브 17개에는 공통점이 있어요. 품번이 틀린 스프링, 8리터 압력솥용 스프링입니다."),
(I, "Le ressort de huit litres... dans une six litres ? Et le contrôle final ? Il aurait dû le voir.", "8리터용 스프링이... 6리터에? 그럼 최종 검사는요? 그걸 잡아냈어야죠."),
(Y, "Le contrôle vérifie que la soupape est réglée selon la consigne enregistrée dans le système pour la six litres. Avec un ressort plus dur, ce réglage-là donne une soupape trop dure. Mais la consigne était respectée, donc le contrôle disait : conforme.",
    "검사는 밸브가 시스템에 등록된 6리터용 기준값대로 조정됐는지 확인합니다. 더 단단한 스프링에 그 조정값을 쓰면 밸브가 너무 뻑뻑해지죠. 하지만 기준값은 지켜졌으니까 검사 결과는 '적합'이었던 겁니다."),
(MA, "Un contrôle qui vérifie qu'on obéit, pas qu'on a raison... Mais comment un ressort de huit litres arrive-t-il sur la ligne de la six litres ?", "지시를 따랐는지만 확인하고, 옳은지는 확인하지 않는 검사라... 그런데 8리터용 스프링이 어떻게 6리터 라인에 들어간 거죠?"),
(SH, "C'est là que j'interviens. J'ai remonté l'historique des stocks. Tout commence en mai, pendant le week-end de l'attaque.", "여기서 제가 나설 차례네요. 재고 이력을 거슬러 올라가 봤습니다. 모든 건 5월, 해킹 공격이 있던 주말에 시작돼요."),
(I, "Quand le camion de ressorts était bloqué... Momo avait pris l'autre référence au magasin.", "스프링 트럭이 묶였을 때... 모모 씨가 창고에서 다른 품번을 가져왔었죠."),
(SH, "Exactement. Ensuite, Martine et les équipes ont ressaisi les trois mille feuilles. Les sorties de stock ont été saisies telles quelles : ressorts de huit litres consommés sur la ligne six litres. Le système en a conclu que les deux références étaient interchangeables. Depuis, chaque fois que le ressort de six litres manquait, il a servi des ressorts de huit litres à la ligne. Automatiquement.",
    "맞습니다. 그 뒤 마르틴과 팀들이 종이 3,000장을 다시 입력했죠. 출고 기록이 적힌 그대로 입력됐어요. '8리터용 스프링, 6리터 라인에서 소비.' 시스템은 두 품번이 서로 대체 가능하다고 결론 내렸습니다. 그 뒤로 6리터용 스프링이 모자랄 때마다 8리터용 스프링을 라인에 공급했어요. 자동으로요."),
(None, "On frappe. Momo entre, une pochette plastique à la main, suivi de Robert Chazal.", "노크 소리. 모모가 비닐 파일을 손에 들고 들어오고, 로베르 샤잘이 뒤따른다."),
(MO, "Monsieur Kessler, je crois que c'est ça que vous cherchez. Ma feuille du samedi. Je l'ai retrouvée cet après-midi, au fond du tiroir de l'établi.", "케슬레르 대표님, 찾으시는 게 이거 같습니다. 그 토요일의 제 종이요. 오늘 오후에 작업대 서랍 맨 안쪽에서 찾았어요."),
(RC, "Lisez la dernière ligne : « Ressort réf. huit litres sur six litres : ce week-end seulement. Banc de tarage réglé à la main, un quart de tour en moins. Validation qualité à faire dans le système. »",
     "마지막 줄을 읽어 보세요. '8리터용 스프링을 6리터에 사용: 이번 주말에 한함. 조정 벤치 수동 조정, 4분의 1바퀴 덜. 시스템에서 품질 승인 필요.'"),
(MO, "Le samedi, j'ai réglé le banc pour chaque pièce. Vingt sur vingt. Mais la validation, personne ne l'a faite. Ma feuille n'était pas dans les cartons de Martine : elle était restée dans sa pochette, au coin de l'établi.",
    "그 토요일엔 제가 부품마다 벤치를 조정했어요. 스무 개 다 통과. 그런데 승인은 아무도 안 했어요. 제 종이는 마르틴의 상자에 없었어요. 비닐 파일에 든 채 작업대 구석에 남아 있었죠."),
(RC, "Et moi, je ne l'ai pas cherchée. Après l'attaque, tout le monde était soulagé. On est passés à autre chose.", "그리고 저는 그걸 찾지 않았습니다. 공격이 끝나고 다들 안도했죠. 다른 일로 넘어갔어요."),
(MA, "Donc le système a retenu la moitié de l'histoire : la substitution, sans la limite ni le réglage...", "그러니까 시스템은 이야기의 절반만 기억한 거군요. 대체 사실만, 기한도 조정값도 없이..."),
(I, "... et pendant quatre mois, à chaque rupture de ressorts de six litres, la ligne a monté des ressorts de huit litres avec le mauvais réglage. Ça colle avec les numéros de lot des trois accidents.",
    "...그리고 넉 달 동안 6리터용 스프링 재고가 떨어질 때마다 라인은 잘못된 조정값으로 8리터용 스프링을 조립했어요. 사고 세 건의 로트 번호와 딱 맞아떨어지네요."),
(MO, "Quarante ans que je fais des soupapes, monsieur Kessler. Et c'est ma feuille qui a brûlé cette dame.", "40년 동안 밸브를 만들었습니다, 대표님. 그런데 그 부인을 다치게 한 게 제 종이라니요."),
(MA, "Non, Momo. Votre feuille était juste, et ce samedi-là, vos soupapes étaient bonnes. Ce qui a failli, c'est notre procédure de reprise. Et cette procédure, c'est la direction qui l'a validée. C'est-à-dire moi.",
     "아닙니다, 모모 씨. 당신 종이는 정확했고, 그 토요일의 밸브는 정상이었어요. 실패한 건 우리의 복구 절차입니다. 그리고 그 절차를 승인한 건 경영진, 즉 저예요."),
(I, "Et moi. Nous avons vérifié que les machines redémarraient et que les cartons étaient ressaisis. Nous n'avons jamais demandé : « Qu'est-ce qui n'est pas dans les cartons ? »",
    "그리고 저도요. 우리는 기계가 다시 돌아가는지, 상자 속 종이가 다시 입력됐는지만 확인했어요. '상자에 없는 건 뭔가?'라고는 한 번도 묻지 않았죠."),
(None, "Momo et Robert sortent. Inès et Mathieu restent seuls devant le tableau blanc.", "모모와 로베르가 나간다. 이네스와 마티외만 화이트보드 앞에 남는다."),
(I, "Bon. Les chiffres. Les lots où le système a servi des ressorts de huit litres : quatre-vingt-seize mille appareils, entre juin et fin septembre. Échange de la soupape, transport, centre d'appels : environ trente-cinq euros par appareil. Un peu plus de trois millions trois.",
    "자. 숫자. 시스템이 8리터용 스프링을 공급한 로트는 6월부터 9월 말까지 9만 6천 대야. 밸브 교체, 운송, 콜센터까지 대당 약 35유로. 330만 유로 조금 넘어."),
(MA, "Et les semaines de mai, pendant la ressaisie ? La traçabilité des ressorts y est incomplète. Si on ajoute ces lots-là, avec une marge de sécurité, Yann arrive à cent vingt mille.",
     "그럼 5월, 재입력하던 몇 주는? 그때는 스프링 추적이 불완전해. 그 로트들을 더하고 안전 여유를 두면 이얀 계산으로 12만 대야."),
(I, "Cent vingt mille, c'est quatre millions deux. Plus la communication et l'indemnisation des victimes : environ six millions. L'assurance en couvre deux. Quatre millions sortent de notre trésorerie, à trois semaines du rapport mensuel à la banque.",
    "12만 대면 420만 유로. 거기에 홍보비와 피해자 보상을 더하면 약 600만 유로. 보험이 200만을 커버해. 400만 유로가 우리 현금에서 나가는 거야. 은행 월간 보고 3주 전에."),
(MA, "Tu proposes de te limiter aux quatre-vingt-seize mille ?", "9만 6천 대로 한정하자는 거야?"),
(I, "Je pose la question, c'est mon métier. Vingt-quatre mille appareils de plus, c'est huit cent quarante mille euros pour des lots qui sont probablement bons.", "질문을 던지는 거야, 그게 내 일이니까. 2만 4천 대를 더하면, 아마 멀쩡할 로트에 84만 유로를 쓰는 거야."),
(MA, "Probablement. Et si l'un d'eux brûle quelqu'un, on fera un deuxième rappel. Un deuxième rappel, personne ne le pardonne. Le premier, peut-être.", "아마도겠지. 그중 하나라도 누군가를 다치게 하면 두 번째 리콜을 해야 해. 두 번째 리콜은 아무도 용서하지 않아. 첫 번째는 어쩌면 용서해 줄지 몰라도."),
(I, "... Tu as raison. Et ce n'est même pas un argument sentimental : un deuxième rappel nous coûterait dix fois plus cher en confiance. Cent vingt mille. Je défendrai le chiffre devant le conseil.",
    "...네 말이 맞아. 감상적인 논리도 아니야. 두 번째 리콜은 신뢰 면에서 열 배는 더 비쌀 테니까. 12만 대. 이사회에서 그 숫자를 내가 변호할게."),
(MA, "Merci. Maintenant, la partie difficile. Laure veut un communiqué écrit et une porte-parole. Moi, je veux aller à la télévision demain soir, et m'excuser moi-même.",
     "고마워. 이제 어려운 부분. 로르는 서면 보도자료와 대변인을 원해. 난 내일 저녁 TV에 나가서 직접 사과하고 싶어."),
(I, "Les avocats vont détester. Un patron qui dit « c'est notre faute » en direct, c'est leur cauchemar.", "변호사들이 질색할 거야. 사장이 생방송에서 '저희 잘못입니다'라고 말하는 건 그들의 악몽이거든."),
(MA, "Je ne dirai pas « c'est la faute de Momo », ni « c'est la faute des pirates ». Je dirai que nous avons failli, et ce que nous faisons pour réparer.", "'모모 탓이다'라고도, '해커 탓이다'라고도 하지 않을 거야. 우리가 실패했다고, 그리고 바로잡기 위해 무엇을 하는지 말할 거야."),
(I, "Alors pèse chaque mot. « Nous assumons » plutôt que « nous sommes coupables » : l'enquête n'est pas finie. Et donne des chiffres, les gens croient les chiffres. Passe-moi ton marqueur vert.",
    "그럼 단어 하나하나를 잘 골라. '유죄입니다'보다는 '책임지겠습니다'. 조사가 안 끝났으니까. 그리고 숫자를 말해. 사람들은 숫자를 믿어. 네 초록 마커 좀 줘."),
(MA, "Tu me prends mon marqueur, maintenant ? ... Quel est le vrai problème ? Ce n'est pas un ressort. C'est une feuille de papier que personne n'a relue.", "이젠 내 마커까지 가져가? ...진짜 문제는 무엇인가? 스프링이 아니야. 아무도 다시 읽지 않은 종이 한 장이야."),

# ---------- 4. Terrain : chez Mme Peyron ----------
(None, "Mardi, 10 h. Firminy, à une dizaine de kilomètres de Saint-Étienne. Un petit pavillon dans une rue calme. Aurélie, la fille de Nicole Peyron, ouvre la porte, les bras croisés.",
       "화요일 오전 10시. 생테티엔에서 10킬로미터쯤 떨어진 피르미니. 조용한 거리의 작은 단독주택. 니콜 페롱의 딸 오렐리가 팔짱을 낀 채 문을 연다."),
(AU2, "Vous êtes le patron ? Je vous préviens : si vous venez pour faire signer quelque chose à ma mère, vous pouvez repartir tout de suite.", "사장님이세요? 미리 말씀드리는데, 엄마한테 뭘 서명시키러 오신 거면 지금 바로 돌아가셔도 돼요."),
(MA, "Je ne viens rien faire signer, madame. Je suis Mathieu Kessler, et voici Inès Marchetti, notre directrice financière. Nous sommes venus présenter nos excuses à votre mère. En personne.",
     "서명받으러 온 게 아닙니다. 마티외 케슬레르이고, 이쪽은 저희 재무 책임자 이네스 마르케티입니다. 어머님께 사과드리러 왔습니다. 직접요."),
(NP, "Laisse-les entrer, Aurélie. On ne laisse pas les gens sur le pas de la porte.", "들어오시게 해, 오렐리. 사람을 문간에 세워 두는 법이 아니야."),
(MA, "Madame Peyron, comment allez-vous ? Et votre main ?", "페롱 부인, 좀 어떠세요? 손은요?"),
(NP, "Ça tire, surtout la nuit. Le médecin dit que ça cicatrisera, mais il faudra des soins pendant plusieurs semaines. Une brûlure comme ça, ça ne s'oublie pas. Heureusement, j'ai tout de suite mis le bras sous l'eau froide.",
    "당겨요, 특히 밤에. 의사 말로는 아물긴 하는데 몇 주는 치료를 받아야 한대요. 이런 화상은 잊히지 않죠. 다행히 곧바로 팔을 찬물에 댔어요."),
(I, "Vous avez eu les bons réflexes. Que s'est-il passé exactement, si vous voulez bien nous le raconter ?", "올바르게 대처하셨어요. 괜찮으시다면, 정확히 어떻게 된 건지 말씀해 주시겠어요?"),
(NP, "Jeudi soir, je faisais une soupe, comme chaque jeudi. J'ai tourné le bouton pour faire baisser la pression, comme d'habitude, et la vapeur est partie sur le côté, d'un coup, directement sur ma main. Je n'ai rien pu faire.",
    "목요일 저녁, 목요일마다 그렇듯 수프를 끓이고 있었어요. 평소처럼 압력을 빼려고 다이얼을 돌렸는데, 증기가 갑자기 옆으로 뿜어져 나와 곧장 손에 닿았어요. 손쓸 틈이 없었죠."),
(MA, "Vous n'avez commis aucune erreur, madame. Le défaut a été identifié hier soir par nos équipes : la soupape de votre autocuiseur a été mal montée à l'usine. C'est notre faute, pas la vôtre.",
     "부인께서는 아무 잘못도 하지 않으셨습니다. 어젯밤 저희 팀이 결함을 확인했습니다. 압력솥 밸브가 공장에서 잘못 조립됐어요. 저희 잘못이지, 부인 잘못이 아닙니다."),
(AU2, "Ah, ça change ! Vendredi, votre service client a écrit à ma mère que l'appareil avait sans doute été mal utilisé.", "어머, 말이 달라졌네요! 금요일에 고객 서비스팀은 엄마가 기기를 잘못 쓴 것 같다고 써 보냈거든요."),
(I, "C'est vrai, et c'est inacceptable. Ce message n'aurait jamais dû vous être envoyé. Je vous présente nos excuses pour cela aussi.", "맞습니다. 그리고 용납할 수 없는 일이에요. 그 메시지는 절대 보내져서는 안 됐습니다. 그 점에 대해서도 사과드립니다."),
(NP, "Vous savez, mon mari, Roger, a travaillé trente-deux ans chez Verdier, à l'emboutissage. J'ai eu ma première Stéphanoise pour mon mariage. Quand elle a rendu l'âme cet été, j'en ai racheté une, évidemment. Une Verdier.",
    "있잖아요, 우리 남편 로제가 베르디에에서 32년을 일했어요. 프레스 작업장에서요. 첫 스테파누아즈는 결혼할 때 받았죠. 그게 올여름 수명을 다해서 새로 하나 샀어요. 당연히 베르디에 걸로요."),
(MA, "Et c'est celle-là qui vous a brûlée. Je comprends que vous vous sentiez trahie.", "그런데 바로 그게 부인을 다치게 했군요. 배신감을 느끼시는 게 당연합니다."),
(NP, "Trahie, non. Déçue. Roger disait toujours : « Chez Verdier, on ne laisse pas partir une pièce dont on n'est pas fier. »", "배신감은 아니고요. 실망이죠. 로제가 늘 그랬어요. '베르디에에선 자랑스럽지 않은 부품은 내보내지 않는다.'"),
(MA, "Il avait raison. Et cette fois, nous avons laissé partir des pièces dont nous ne pouvons pas être fiers. Cent vingt mille appareils vont être rappelés. Nous l'annoncerons ce soir.",
     "그분 말씀이 옳았습니다. 그리고 이번엔 저희가 자랑스러울 수 없는 부품을 내보냈어요. 압력솥 12만 대를 리콜합니다. 오늘 저녁에 발표할 겁니다."),
(AU2, "Et ma mère, dans tout ça ? L'infirmière qui passe tous les deux jours, l'aide à domicile qu'il faut payer ? On va devoir prendre un avocat ?", "그럼 이 와중에 우리 엄마는요? 이틀마다 오는 간호사, 돈을 내야 하는 가사 도우미는요? 변호사를 선임해야 하나요?"),
(I, "Vous en avez le droit, et je ne vous le déconseille pas. Mais vous n'aurez pas à attendre la fin d'une procédure. Tous les frais liés à l'accident seront pris en charge dès maintenant, sur simple présentation des factures. Voici mon numéro direct.",
    "그럴 권리가 있으시고, 말리지도 않겠습니다. 하지만 소송이 끝날 때까지 기다리실 필요는 없어요. 사고와 관련된 모든 비용은 영수증만 보여 주시면 지금부터 바로 부담하겠습니다. 이건 제 직통 번호예요."),
(AU2, "Votre numéro direct ? La directrice financière ? ... Vous êtes sérieuse ?", "직통 번호요? 재무 책임자가요? ...진심이세요?"),
(I, "Tout à fait. Si quelqu'un chez nous vous fait attendre, vous m'appelez. Moi, je ne vous ferai pas attendre.", "물론이죠. 저희 쪽 누구라도 기다리게 하면 저한테 전화하세요. 저는 기다리게 하지 않을 거예요."),
(NP, "Monsieur Kessler, je vais vous dire une chose. Ce soir, à la télévision, ne vous cachez pas derrière des mots compliqués. Les gens d'ici ne vous en voudront pas d'avoir fait une erreur. Ils vous en voudront d'avoir menti.",
    "케슬레르 씨, 한 가지만 말할게요. 오늘 저녁 TV에서 어려운 말 뒤에 숨지 마세요. 이 동네 사람들은 실수했다고 원망하지 않아요. 거짓말을 했다면 원망하겠죠."),
(MA, "Je vous le promets, madame. Pas de mots compliqués.", "약속드립니다, 부인. 어려운 말은 하지 않겠습니다."),
(NP, "Et ma cocotte ? Je ne vais quand même pas faire ma soupe dans une casserole, comme une débutante !", "그런데 내 압력솥은요? 설마 초보자처럼 냄비에 수프를 끓이라는 건 아니겠죠!"),
(MA, "Vous recevrez une Stéphanoise neuve, vérifiée à la main. Je demanderai à Momo Belkacem de la contrôler lui-même. Il a peut-être connu votre mari.", "손으로 검사한 새 스테파누아즈를 보내 드리겠습니다. 모모 벨카셈 씨에게 직접 검사해 달라고 부탁할게요. 어쩌면 남편분을 아셨을지도 몰라요."),
(NP, "Momo ! Le petit Mohamed ? C'est Roger qui l'a formé, quand il est arrivé à l'usine ! Dites-lui que Nicole l'embrasse.", "모모! 꼬마 모하메드요? 그 애가 공장에 처음 왔을 때 가르친 게 로제예요! 니콜이 안부 전한다고 해 주세요."),
(None, "Sur le seuil, Aurélie retient Inès un instant.", "문간에서 오렐리가 잠깐 이네스를 붙잡는다."),
(AU2, "Je ne voulais pas être désagréable. J'ai juste eu très peur pour elle.", "무례하게 굴려던 건 아니에요. 그냥 엄마 때문에 너무 무서웠어요."),
(I, "Vous n'avez pas à vous excuser. À votre place, j'aurais fait exactement pareil.", "사과하실 필요 없어요. 제가 그 입장이었어도 똑같이 했을 거예요."),

# ---------- 5. Décision : le conseil et le plateau télé ----------
(None, "Mardi, 13 h. Conseil d'administration extraordinaire en visioconférence. À l'écran : Hubert et Claire Verdier, Frédéric Aubry, Hélène Vasseur.",
       "화요일 오후 1시. 화상으로 열린 임시 이사회. 화면에 위베르와 클레르 베르디에, 프레데리크 오브리, 엘렌 바쇠르가 보인다."),
(HV, "Bien. Séance extraordinaire, un seul point : la Stéphanoise. Monsieur Kessler, je vous écoute. Et j'espère que vous avez une bonne explication.", "좋습니다. 임시 회의, 안건은 하나. 스테파누아즈. 케슬레르 대표, 말씀하시죠. 그럴듯한 설명이 있길 바랍니다."),
(MA, "Je n'ai pas d'excuse, monsieur le président, mais j'ai une explication. Pendant la cyberattaque de mai, une pièce a été remplacée par une autre, avec un réglage adapté, et tout a été noté sur papier. Cette feuille n'a jamais été ressaisie. Le système n'a retenu que la substitution. Cent vingt mille appareils sont concernés.",
     "변명은 없습니다, 의장님. 하지만 설명은 있습니다. 5월 사이버 공격 때 부품 하나를 다른 부품으로 대체하고 조정값도 맞췄으며, 모든 걸 종이에 기록했습니다. 그 종이가 시스템에 다시 입력되지 않았습니다. 시스템은 대체 사실만 기억했고요. 해당 기기는 12만 대입니다."),
(HV, "Plus de soixante ans sans un seul rappel. Soixante ans ! Et il a fallu que ça arrive maintenant.", "60년 넘게 리콜 한 번 없었는데. 60년이요! 그런데 하필 지금 이런 일이."),
(AU, "Restons calmes. Monsieur Kessler, la cause, c'est la cyberattaque. Dans notre communication, ne pourrions-nous pas insister là-dessus ? Nous sommes victimes, nous aussi.",
     "진정합시다. 케슬레르 대표, 원인은 사이버 공격이잖아요. 홍보에서 그 점을 강조하면 안 될까요? 우리도 피해자니까요."),
(MA, "Les pirates nous ont pris nos ordinateurs pendant quatre jours, monsieur Aubry. Ils ne nous ont pas pris notre responsabilité. Si nous accusons l'attaque, nous aurons l'air de chercher une excuse.",
     "해커들은 나흘 동안 우리 컴퓨터를 가져갔을 뿐입니다, 오브리 씨. 우리의 책임까지 가져가진 않았어요. 공격을 탓하면 핑계를 찾는 것처럼 보일 겁니다."),
(I, "Et ce serait faux. La substitution a été faite correctement, sur papier, avec le bon réglage. C'est notre procédure de reprise qui ne l'a pas reprise dans le système. Ce sont nos procédures, pas celles des pirates.",
    "게다가 사실도 아닙니다. 대체 작업은 종이 위에서, 올바른 조정값으로 제대로 이뤄졌습니다. 그걸 시스템에 반영하지 못한 건 우리의 복구 절차예요. 해커의 절차가 아니라 우리 절차입니다."),
(AU, "Combien ?", "얼마죠?"),
(I, "Six millions d'euros au total. L'assurance en couvre deux. L'impact net sur la trésorerie est de quatre millions, étalé sur trois mois. J'appellerai la Banque Rhodanienne dès demain matin, avant qu'elle ne l'apprenne par la presse.",
    "총 600만 유로입니다. 보험이 200만을 부담합니다. 현금에 미치는 순영향은 400만 유로이고, 석 달에 걸쳐 나갑니다. 은행이 언론으로 알기 전에, 내일 아침 바로 방크 로다니엔에 전화하겠습니다."),
(CV, "Et les précommandes de la Stéphanoise 2 ? Les clients vont avoir peur de la marque.", "스테파누아즈 2 사전 주문은요? 고객들이 브랜드 자체를 겁낼 텐데요."),
(I, "C'est un risque, madame Verdier. Mais un rappel bien géré peut renforcer la confiance. Un rappel caché, lui, la détruit pour des années.", "위험한 건 맞습니다, 베르디에 이사님. 하지만 잘 관리된 리콜은 오히려 신뢰를 키울 수 있습니다. 숨긴 리콜은 신뢰를 몇 년 동안 무너뜨리고요."),
(H, "J'ajoute une chose, en tant qu'administratrice indépendante. Le comité d'audit devra revoir la procédure de reprise après sinistre. Et la façon dont deux réclamations de clients brûlés ont pu être classées sans suite.",
    "사외이사로서 한 가지 덧붙이겠습니다. 감사위원회는 재해 복구 절차를 재검토해야 합니다. 그리고 화상 입은 고객의 불만 두 건이 어떻게 그냥 종결 처리될 수 있었는지도요."),
(MA, "C'est engagé. À partir d'aujourd'hui, toute réclamation qui mentionne une brûlure ou une blessure arrive sur mon bureau dans les vingt-quatre heures.", "이미 착수했습니다. 오늘부터 화상이나 부상이 언급된 모든 불만은 24시간 안에 제 책상에 올라옵니다."),
(HV, "Hm. Je mets aux voix le rappel de cent vingt mille appareils et le budget de six millions. ... Adopté. Monsieur Kessler, ce soir, à la télévision, ne nous faites pas honte.",
     "흠. 12만 대 리콜과 600만 유로 예산을 표결에 부치겠습니다. ...가결. 케슬레르 대표, 오늘 저녁 TV에서 우리 얼굴에 먹칠하지 마세요."),
(None, "Mardi, 20 h 12. Studio régional d'une chaîne nationale, à Lyon, en duplex avec Paris. Mathieu est face à la caméra. Hors champ, Inès et Laure regardent l'écran de contrôle.",
       "화요일 저녁 8시 12분. 리옹에 있는 전국 방송사의 지역 스튜디오, 파리와 이원 생중계. 마티외가 카메라 앞에 앉아 있다. 화면 밖에서 이네스와 로르가 모니터를 지켜본다."),
(G, "Monsieur Kessler, bonsoir. Trois personnes brûlées, cent vingt mille autocuiseurs rappelés. Que s'est-il passé ?", "케슬레르 대표님, 안녕하세요. 화상 피해자 세 명, 리콜되는 압력솥 12만 대. 무슨 일이 있었던 겁니까?"),
(MA, "Bonsoir. D'abord, je veux m'adresser aux trois personnes qui ont été blessées, et à leurs familles : je vous présente mes excuses, au nom de Verdier Industries. Ce qui vous est arrivé n'aurait jamais dû arriver.",
     "안녕하십니까. 먼저 다치신 세 분과 그 가족분들께 말씀드리고 싶습니다. Verdier Industries를 대표해 사과드립니다. 여러분께 일어난 일은 절대 일어나서는 안 되는 일이었습니다."),
(G, "Des excuses, c'est bien. Mais concrètement, quel est le défaut ?", "사과는 좋습니다. 하지만 구체적으로, 결함이 뭡니까?"),
(MA, "Sur certains autocuiseurs, un ressort de la soupape n'était pas le bon, et le réglage n'a pas été adapté. La soupape s'ouvre donc trop tard : la pression monte plus haut que prévu, et la vapeur sort trop fort à la décompression. Le défaut a été identifié par nos équipes lundi soir.",
     "일부 압력솥에서 밸브 스프링이 맞는 부품이 아니었고, 조정값도 그에 맞춰지지 않았습니다. 그래서 밸브가 너무 늦게 열립니다. 압력이 예정보다 높이 올라가고, 감압할 때 증기가 너무 세게 나오는 겁니다. 결함은 월요일 저녁 저희 팀이 확인했습니다."),
(G, "Selon nos informations, ce défaut serait lié à la cyberattaque dont votre groupe a été victime en mai. Vous êtes donc vous-mêmes des victimes ?", "저희 취재에 따르면 이 결함은 5월에 귀사가 당한 사이버 공격과 관련이 있다고 하던데요. 그렇다면 귀사도 피해자인 셈인가요?"),
(MA, "Non, madame. Pendant l'attaque, nos ouvriers ont continué à produire sur papier, et ils ont bien travaillé. C'est nous, la direction, qui n'avons pas vérifié que tout avait été ressaisi ensuite. La responsabilité est la nôtre, et je l'assume.",
     "아닙니다. 공격 기간에 저희 노동자들은 종이로 생산을 계속했고, 일을 잘 해냈습니다. 그 뒤 모든 것이 다시 입력됐는지 확인하지 않은 건 저희 경영진입니다. 책임은 저희에게 있고, 제가 지겠습니다."),
(G, "Deux clients s'étaient plaints dès septembre. Leurs réclamations ont été classées sans suite. Vous le saviez ?", "고객 두 명이 이미 9월에 불만을 제기했습니다. 그런데 그 불만은 종결 처리됐죠. 알고 계셨습니까?"),
(MA, "Je ne le savais pas, et c'est bien le problème. Ces réclamations auraient dû être transmises à la direction. Elles ne l'ont pas été. Nous avons changé cette règle aujourd'hui même.",
     "몰랐습니다. 그리고 그게 바로 문제입니다. 그 불만은 경영진에게 전달됐어야 했어요. 그러지 않았습니다. 바로 오늘 그 규칙을 바꿨습니다."),
(G, "Que doivent faire, ce soir, les personnes qui possèdent une Stéphanoise ?", "오늘 밤 스테파누아즈를 가진 분들은 어떻게 해야 합니까?"),
(MA, "Regarder le numéro de lot, gravé sous la poignée. La liste des lots concernés est sur notre site et sur RappelConso. Si votre appareil en fait partie, ne l'utilisez plus, et appelez notre numéro vert : nous remplaçons la soupape gratuitement, ou nous remboursons l'appareil. C'est le client qui choisit.",
     "손잡이 아래 새겨진 로트 번호를 확인해 주십시오. 해당 로트 목록은 저희 웹사이트와 RappelConso에 있습니다. 해당된다면 사용을 중단하시고 무료 전화로 연락 주십시오. 밸브를 무상으로 교체해 드리거나 제품값을 환불해 드립니다. 선택은 고객께서 하십니다."),
(G, "Et les autres Stéphanoise, sont-elles sûres ?", "다른 스테파누아즈는 안전합니까?"),
(MA, "Oui. Les autres lots ont été testés au laboratoire ces deux derniers jours. Ils sont conformes. J'en ai une dans ma cuisine, et ma grand-mère aussi.", "네. 다른 로트들은 지난 이틀간 실험실에서 시험했습니다. 적합 판정을 받았습니다. 제 부엌에도 하나 있고, 제 할머니 댁에도 있습니다."),
(G, "Dernière question. Ce rappel va coûter cher, à un groupe qui perd déjà de l'argent. Craignez-vous pour l'avenir de Verdier ?", "마지막 질문입니다. 이미 적자인 그룹에 이번 리콜은 큰 비용이 될 텐데요. 베르디에의 미래가 걱정되십니까?"),
(MA, "Il coûtera six millions d'euros. C'est beaucoup. Mais ce qui coûterait le plus cher, ce serait de perdre la confiance de ceux qui font leur soupe avec nos autocuiseurs depuis soixante ans. Ça, nous ne pouvons pas nous le permettre.",
     "600만 유로가 듭니다. 큰돈이죠. 하지만 가장 비싼 대가는, 60년 동안 저희 압력솥으로 수프를 끓여 온 분들의 신뢰를 잃는 것입니다. 그것만은 감당할 수 없습니다."),
(L, "Vous n'avez pas lu une seule ligne de mes éléments de langage. Et pourtant, c'est la meilleure interview de crise que j'aie vue en vingt ans.", "제가 드린 메시지 가이드는 한 줄도 안 읽으셨네요. 그런데도 20년 동안 본 위기 인터뷰 중 최고였어요."),
(I, "« J'assume », trois chiffres, une consigne. Pas un mot compliqué. Mme Peyron sera contente.", "'책임지겠습니다', 숫자 세 개, 지침 하나. 어려운 말은 하나도 없었어요. 페롱 부인이 좋아하시겠네요."),
(MA, "J'ai les mains qui tremblent, madame Marchetti. Vous ne le direz à personne ?", "손이 떨리네요, 마르케티 이사님. 아무한테도 말 안 하실 거죠?"),

# ---------- 6. Le soir : l'appel de Colmar ----------
(None, "Mardi, 22 h 30. L'appartement de Mathieu, près de l'hôtel de ville. Inès a enlevé ses chaussures ; Mathieu réchauffe une soupe. Son téléphone sonne : « Mamie ».",
       "화요일 밤 10시 30분. 시청 근처 마티외의 아파트. 이네스는 신발을 벗었고, 마티외는 수프를 데우고 있다. 그의 휴대폰이 울린다. 화면엔 '할머니'."),
(MA, "C'est ma grand-mère. À cette heure-ci... Elle ne se couche jamais après le journal. Allô, Mamie ?", "할머니야. 이 시간에... 뉴스 끝나면 바로 주무시는 분인데. 여보세요, 할머니?"),
(OD, "Mathieu ! Je t'ai vu à la télévision. Tu avais mis la cravate bleue que je t'ai offerte, c'est bien. Mais tu as maigri.", "마티외! 텔레비전에서 봤다. 내가 사 준 파란 넥타이 맸더구나, 잘했어. 그런데 살이 빠졌어."),
(MA, "Je n'ai pas maigri, Mamie, c'est la caméra. Tu as entendu ce que j'ai dit ?", "살 안 빠졌어요, 할머니, 카메라 때문이에요. 제가 한 말 들으셨어요?"),
(OD, "Tout. Et j'ai pensé à ton grand-père. Il disait toujours à ses élèves : « Faute avouée est à moitié pardonnée. » Ce soir, tu as fait la moitié du chemin. L'autre moitié, c'est de réparer.",
     "전부. 그리고 네 할아버지 생각이 났단다. 학생들한테 늘 그러셨지. '잘못을 인정하면 반은 용서받은 것이다.' 오늘 밤 넌 길의 절반을 간 거야. 나머지 절반은 바로잡는 거고."),
(MA, "C'est exactement ce qu'on va faire. Cent vingt mille soupapes à changer. Je vais en rêver la nuit.", "바로 그걸 할 거예요. 바꿔야 할 밸브가 12만 개예요. 꿈에 나올 것 같아요."),
(OD, "Tu en rêveras, mais tu dormiras. Tu manges, au moins ? ... Elle est là, n'est-ce pas ? Ta demoiselle. Tu m'en as parlé la semaine dernière, et je l'entends rire.",
     "꿈에 나와도 잠은 잘 거다. 밥은 먹고 다니니? ...그 아가씨 거기 있지, 그렇지? 지난주에 네가 얘기한 아가씨. 웃음소리가 들리는구나."),
(MA, "Mamie... Oui, elle est là. Inès, ma grand-mère voudrait te parler. Je t'avais prévenue : elle n'abandonne jamais.", "할머니... 네, 여기 있어요. 이네스, 할머니가 너랑 얘기하고 싶으시대. 내가 말했지, 절대 포기 안 하시는 분이라고."),
(I, "Bonsoir, madame. Je suis... Inès. Mathieu m'a beaucoup parlé de vous. Et de vos bretzels du dimanche.", "안녕하세요, 할머님. 저는... 이네스예요. 마티외한테 얘기 많이 들었어요. 일요일마다 만드시는 브레첼 얘기도요."),
(OD, "Bonsoir, mademoiselle. Moi aussi, il m'a parlé de vous. Il dit que vous êtes plus forte que lui en calcul, et qu'il a peur de vous en réunion.", "안녕하세요, 아가씨. 저도 아가씨 얘기 들었어요. 셈은 자기보다 훨씬 잘하고, 회의 때는 아가씨가 무섭다고 하더군요."),
(I, "Il exagère. Un peu.", "과장이에요. 조금은요."),
(OD, "J'espère bien que non. Écoutez-moi, mademoiselle. Ce garçon, quand il a mal, il ne le dit pas. Il range, il fait la cuisine, il pose des questions aux autres. Mais lui, il ne se plaint jamais. Depuis qu'il est tout petit.",
     "아니길 바라요. 내 말 들어 봐요, 아가씨. 이 아이는 아파도 말을 안 해요. 정리하고, 요리하고, 남들한테 질문을 하죠. 그런데 자기는 절대 불평을 안 해요. 아주 어릴 때부터요."),
(I, "Je sais. Ce soir, il m'a avoué que ses mains tremblaient. Je crois que c'est la première fois.", "알아요. 오늘 저녁에 손이 떨린다고 털어놨어요. 처음 있는 일 같아요."),
(OD, "Alors il vous fait confiance. Prenez soin de lui, mademoiselle. Moi, je suis loin, et je suis vieille.", "그럼 아가씨를 믿는 거예요. 그 아이를 잘 돌봐 줘요, 아가씨. 나는 멀리 있고, 늙었으니까."),
(I, "Je vous le promets, madame. Et lui aussi prend soin de moi, vous savez. Ce soir, il me fait même la soupe.", "약속드릴게요, 할머님. 그리고 마티외도 저를 잘 챙겨 줘요. 오늘 밤엔 수프까지 끓여 주고 있어요."),
(OD, "Avec ma recette, j'espère ! Il paraît que vous partez en Allemagne à la fin du mois prochain. Colmar est sur la route. Je vous ferai une tarte flambée. Je ne vous le demande pas : je vous attends.",
     "내 레시피로 끓였길 바라요! 다음 달 말에 독일에 간다면서요. 콜마르가 가는 길에 있잖아요. 타르트 플랑베를 만들어 줄게요. 부탁하는 게 아니에요. 기다리겠다는 거예요."),
(I, "Alors nous viendrons. Je vous repasse votre petit-fils. Bonne nuit, madame.", "그럼 갈게요. 손자분 바꿔 드릴게요. 안녕히 주무세요, 할머님."),
(None, "Mathieu raccroche quelques minutes plus tard. Inès le regarde, les yeux brillants.", "몇 분 뒤 마티외가 전화를 끊는다. 이네스가 반짝이는 눈으로 그를 바라본다."),
(MA, "Qu'est-ce qu'elle t'a dit ? Tu as une drôle de tête.", "할머니가 뭐라고 하셨어? 표정이 이상한데."),
(I, "Que tu ne te plains jamais. Et que je dois prendre soin de toi. Je crois que j'ai été présentée à la famille, Strasbourg.", "넌 절대 불평하지 않는대. 그리고 내가 너를 잘 돌봐야 한대. 나 방금 가족한테 소개된 것 같아, 스트라스부르."),
(MA, "Par téléphone, à dix heures et demie du soir, après un rappel produit. C'est très Kessler... Bon. Que fait-on lundi ?", "전화로, 밤 10시 반에, 제품 리콜 직후에. 아주 케슬레르 집안답네... 자. 월요일엔 뭘 하지?"),
(I, "Lundi, les premières soupapes sont échangées, et j'appelle chaque victime moi-même. Fin novembre, Stuttgart : une entreprise allemande sans héritier, Hausmann. Et au retour... une tarte flambée à Colmar.",
    "월요일엔 첫 밸브 교체가 시작되고, 내가 피해자 한 분 한 분께 직접 전화할 거야. 11월 말엔 슈투트가르트. 후계자 없는 독일 회사, 하우스만. 그리고 돌아오는 길엔... 콜마르에서 타르트 플랑베."),
]

VOCAB = [
("B2", "un rappel (de produit) / rappeler un produit", "(제품) 리콜 / 제품을 회수하다", "procéder au rappel de 120 000 appareils. 공식 사이트 RappelConso. 일상어 rappeler(다시 전화하다)와 구분."),
("B2", "bloquer / suspendre les expéditions", "출하를 막다 / 중단하다", "원인을 모를 때 먼저 하는 조치. les ventes suspendues(판매 중단)."),
("B2", "un numéro de lot / la traçabilité", "로트 번호 / 추적 가능성", "어느 날, 어느 라인, 어떤 부품으로 만들었는지 거슬러 찾을 수 있는 능력. tracer = 추적하다."),
("B2", "classer (une réclamation) sans suite", "(불만·사건을) 종결 처리하다", "원래 검찰이 사건을 불기소 처분할 때 쓰는 법률 표현. classement sans suite."),
("B2", "remonter une information", "(정보를) 위로 보고하다", "Personne ne les a remontées. 현장 → 경영진 방향. 반대는 descendre l'information."),
("B1", "un numéro vert", "무료 전화번호", "프랑스의 080으로 시작하는 수신자 부담 번호. 리콜·고객 상담의 필수 요소."),
("B2", "présenter ses excuses (à qn)", "(~에게) 사과드리다", "s'excuser보다 격식 있는 공식 사과. Je vous présente nos excuses. ↔ 기업식 회피 표현 « regretter les désagréments »."),
("C1", "les éléments de langage", "(홍보용) 메시지 가이드, 정해진 답변 문구", "홍보팀이 준비한 핵심 문장 모음. 정치·기업 커뮤니케이션 용어로, 비꼬는 뉘앙스로도 씀."),
("B2", "interchangeable", "서로 바꿔 쓸 수 있는, 호환되는", "deux références interchangeables. 품번(une référence)은 부품의 코드 번호."),
("B2", "une rupture (de stock)", "재고 소진, 품절", "être en rupture de stock = 품절이다. 연애의 rupture(결별)와 같은 단어."),
("C1", "faillir", "(의무·기능을) 다하지 못하다, 실패하다", "Ce qui a failli, c'est notre procédure. 문어적. 일상에서는 j'ai failli tomber(넘어질 뻔했다)처럼 '~할 뻔하다'로 더 자주 쓴다."),
("C1", "la reprise après sinistre", "재해 복구", "le plan de reprise d'activité(PRA). 사이버 공격·화재 뒤 업무를 되살리는 절차."),
("B2", "être conforme (à) / la consigne", "(~에) 적합하다 / 지시값, 지침", "contrôle conforme = 검사 적합. la consigne de réglage(조정 지시값), donner une consigne aux clients."),
("C1", "le banc de tarage", "(밸브) 조정·검정 벤치", "tarer = 영점을 맞추다, 조정하다. 압력솥 밸브가 정해진 압력에서 열리도록 맞추는 장치."),
("B2", "rendre l'âme", "(물건이) 수명을 다하다, 고장 나 버리다", "원래 '숨을 거두다'. 가전·자동차에 유머러스하게 쓴다. Ma cocotte a rendu l'âme."),
("B2", "en vouloir à qn (de + inf.)", "(~한 것으로) ~을 원망하다", "Ils ne vous en voudront pas d'avoir fait une erreur. 사과할 때 Ne m'en veux pas(나한테 화내지 마)."),
("B2", "prendre en charge (des frais)", "(비용을) 부담하다", "Tous les frais seront pris en charge. 보험·회사가 비용을 떠맡을 때. la prise en charge."),
("B1", "laisser qn sur le pas de la porte", "~을 문간에 세워 두다", "le pas de la porte = 문지방, 문간. 들어오라고 하지 않는 무례함."),
("B1", "Ça tire. / cicatriser", "(상처가) 당기다 / 아물다", "피부가 당기는 통증. la cicatrice = 흉터. La brûlure cicatrisera."),
("C1", "Faute avouée est à moitié pardonnée.", "잘못을 인정하면 반은 용서받은 것이다", "프랑스 속담. 관사 없이 쓰는 속담 특유의 문체에 주목."),
("B2", "en duplex / en direct", "이원 생중계로 / 생방송으로", "두 장소를 연결해 방송하는 것이 duplex. ↔ en différé(녹화 방송)."),
("C1", "hors champ", "화면 밖에서, 프레임 밖에", "영화·방송 용어. champ = 카메라가 담는 범위."),
("B1", "avoir une drôle de tête", "표정이 이상하다", "drôle de + 명사 = 이상한 ~. une drôle d'idée. tête = 얼굴 표정(구어)."),
("B2", "avoir les traits tirés", "초췌하다, 얼굴이 핼쑥하다", "les traits = 이목구비. 피로로 얼굴이 당겨 보이는 모습."),
]

GRAM = [
("B2", "수동태 ①: être + 과거분사 (+ par)",
 "« Le défaut a été identifié par nos équipes lundi soir. » « Elles ont été classées « mauvaise utilisation ». » « Cent vingt mille appareils vont être rappelés. » 시제는 être가 담당하고(a été, vont être, seront), 과거분사는 주어에 성·수 일치한다(elles ont été classées). 행위자는 par로 나타내는데, 리콜·사고 발표에서는 행위자를 일부러 생략해 사실만 전하는 경우가 많다. 반대로 Mathieu는 « par nos équipes »를 넣어 '우리가 찾아냈다'는 책임감을 보여 준다."),
("B2", "수동태 ②: 조건법 과거 수동 — 했어야 했는데 하지 않은 일",
 "« Ce message n'aurait jamais dû vous être envoyé. » « Ces réclamations auraient dû être transmises à la direction. Elles ne l'ont pas été. » devoir의 조건법 과거(aurait dû) + 수동 부정사(être envoyé)로 '보내져서는 안 됐다 / 전달됐어야 했다'는 공식 사과의 핵심 구조를 만든다. 뒤 문장의 l'는 앞의 transmises를 받는 중성대명사다."),
("B2", "수동의 대안: on, se faire + 부정사, 대명동사 수동",
 "« si c'est nous qui l'annonçons, ou si on nous l'annonce » « Mes gars ne vont pas se faire accuser sans preuve. » « Une brûlure comme ça, ça ne s'oublie pas. » 회화에서는 수동태 대신 on을 자주 쓴다. se faire + 부정사는 주어가 (대개 불쾌한) 일을 '당하는' 느낌, 대명동사 수동(s'oublier, se vendre)은 일반적 사실을 말할 때 쓴다."),
("B2", "사과와 책임의 표현 단계",
 "회피: « Verdier regrette les désagréments signalés... » 인정: « C'est notre faute, pas la vôtre. » « La responsabilité est la nôtre, et je l'assume. » 사과: « Je vous présente mes excuses, au nom de Verdier Industries. » 약속: « Je vous le promets, madame. » regretter + 명사는 책임 주체가 흐릿하고, présenter ses excuses + assumer는 주체를 분명히 한다. 법적 조사 중에는 « nous sommes coupables »보다 « nous assumons »을 고르는 것이 이 화의 논점이다."),
("B2", "조건법: 언론의 전언(확인되지 않은 정보)",
 "« deux autres accidents similaires auraient eu lieu à Lyon » « Tous impliqueraient le même modèle » « ce défaut serait lié à la cyberattaque » 기자는 확인되지 않은 정보를 조건법(현재·과거)으로 전한다. '~라고 한다, ~인 것으로 알려졌다'. 이 조건법은 가정의 의미가 아니므로 si 절이 필요 없다. 뉴스 청취의 필수 문법."),
("B2", "ne... que: '~만, ~에서야'",
 "« La soupape de sécurité ne se déclenche qu'à un virgule six. » « je n'appelle qu'un numéro » « Le système n'a retenu que la substitution. » ne... que는 부정이 아니라 한정(seulement)이다. que는 한정하고 싶은 말 바로 앞에 둔다. 복합시제에서는 que가 과거분사 뒤로 간다(n'a retenu que...)."),
("B2", "시간 접속사: tant que / dès que / chaque fois que",
 "« tant que l'expertise n'a pas été faite » « tant qu'on ne sait pas, on protège les clients » « dès que la pression dépasse zéro virgule huit bar » « chaque fois que le ressort de six litres manquait » 모두 직설법을 쓴다(avant que와 달리 접속법이 아님). tant que = ~하는 동안(~하지 않는 한), dès que = ~하자마자, chaque fois que = ~할 때마다(과거 반복이면 반과거)."),
("B2", "en vouloir à qn de + 부정사 과거",
 "« Les gens d'ici ne vous en voudront pas d'avoir fait une erreur. Ils vous en voudront d'avoir menti. » en vouloir à qn(~을 원망하다)의 이유는 de + 부정사로 붙이고, 그 행위가 먼저 일어난 일이면 부정사 과거(avoir + p.p.)를 쓴다. 같은 구조: Je vous remercie d'être venus. Je m'excuse de vous avoir fait attendre."),
]

CULTURE = [
("프랑스의 제품 리콜 제도와 RappelConso",
 "프랑스 소비법(Code de la consommation)은 생산자와 유통업자에게 안전하지 않은 제품을 알게 되면 즉시 행정 당국에 신고하고, 필요하면 회수·리콜하도록 의무를 지운다. 2021년 4월부터 정부가 운영하는 공공 사이트 RappelConso에 모든 소비재 리콜을 한곳에 공개하고 있으며, 소비자보호 당국(DGCCRF)이 감독한다. 리콜 공지에는 보통 제품명, 로트 번호, 위험 내용, 소비자가 해야 할 행동(사용 중단, 교환·환불 방법)이 들어간다."),
("압력솥의 나라 프랑스, 그리고 화상 응급처치",
 "압력솥의 원리는 17세기 프랑스 물리학자 드니 파팽(Denis Papin)의 '증기 찜통(digesteur)'까지 거슬러 올라간다. 20세기 중반 가정용 압력솥이 대중화되면서 프랑스 가정의 필수품이 되었고, 한 제조사의 상표명 « Cocotte-Minute »는 일반명사처럼 쓰인다. 화상을 입었을 때 프랑스에서 흔히 가르치는 응급처치는 '15의 법칙(règle des 3 × 15)', 즉 약 15°C의 물을 15cm 거리에서 15분 동안 흘려 주는 것이다. 심한 화상이면 응급 의료 번호 15(SAMU)에 전화한다."),
("« Mademoiselle »와 프랑스식 사과",
 "프랑스에서는 2012년 정부 지침으로 행정 서류에서 « Mademoiselle » 칸이 없어지고 여성은 결혼 여부와 관계없이 « Madame »으로 통일되었다. 일상에서도 젊은 세대는 거의 쓰지 않지만, 오딜 할머니 같은 노년 세대는 여전히 젊은 여성을 다정하게 « mademoiselle »라고 부르곤 한다. 할머니가 인용한 속담 « Faute avouée est à moitié pardonnée »는 위기 커뮤니케이션에서도 자주 인용되며, 프랑스 기업의 공식 사과는 « regretter »(유감)에 그치는 경우가 많아 CEO의 직접 사과는 큰 인상을 남긴다."),
]
