# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, S = "Inès", "Mathieu", "Hélène", "Sofia"
AU, B, MR = "Aubry", "Baptiste", "Martine"
CH, JF, MO = "Chazal", "Josiane", "Momo"

META = {
    "part": 2, "ep": 29,
    "part_label": "제2부 · 경영자 Aux commandes",
    "title_fr": "Désaccord",
    "title_ko": "불화",
    "place": "11구 오베르캉프 이네스의 아파트 · 8구 오슈 거리 호텔 바 · 생테티엔 Verdier 본사 회의실·이사회실 · 생테티엔 공장 · 샤토크뢰역 / 3월, 토요일부터 다음 주 토요일까지",
    "chars": "이네스, 마티외, 프레데리크 오브리(아르칸 캐피털 파트너), 바티스트 모렐(아르칸), 엘렌 바쇠르(사외이사), 마르틴 로슈(CEO 비서), 로베르 샤잘(공장장), 조지안 파브르(노조 대표·CSE 서기), 모모 벨카셈(숙련공), 소피아 베날리",
    "work": "독일 가전 대기업 Sternfeld의 Verdier 인수 제안(기업가치 5억 2천만 유로, 생테티엔 존치 2년 약속) — 오브리가 마티외에게만 몰래 제안한 매각 보너스 200만 유로와 그룹 경영위원회 자리, 매각 vs 독자 회생 노선 충돌",
    "life": "파리의 토요일 아침과 '우리 집', 6일간의 침묵, 바티스트를 통해 알게 된 비밀, vous로 시작해 tu로 무너지는 다툼, 결별, 파리로 돌아온 이네스와 소피아",
    "focus": "비난·변명·후회 표현(reprocher, s'en vouloir, je comptais te le dire), 접속법 과거(je regrette que tu ne m'aies pas dit), 조건법 과거(tu aurais dû), 격식체 vous와 tu의 전환, M&A·지배구조 어휘(valeur d'entreprise, data room, prime de cession, saisir le conseil)",
    "levelmix": "B1 15% · B2 60% · C1 25%",
    "next": "제30화 L'assemblée générale — 주주총회 날 아침, 엘렌이 이네스에게 전하는 한 문장: 마티외가 매각 제안을 거절했다는 것.",
}

D = [
# ---------- 1. Ouverture : samedi à Oberkampf ----------
(None, "Un samedi de mars, 8 h 30. Oberkampf, l'appartement parisien d'Inès. La pluie tape sur les vitres. Sur l'étagère trône la Stéphanoise de 1962, cadeau de Momo.",
       "3월의 어느 토요일, 오전 8시 30분. 오베르캉프, 이네스의 파리 아파트. 빗방울이 유리창을 두드린다. 선반 위에는 모모가 선물한 1962년산 스테파누아즈가 자리 잡고 있다."),
(MA, "Ne bouge pas. Figaro vient de s'endormir sur mes genoux. Si je me lève, il me griffe. Donc c'est toi qui fais le café.",
     "움직이지 마. 피가로가 방금 내 무릎에서 잠들었어. 내가 일어나면 할퀼 거야. 그러니까 커피는 네가 내려."),
(I, "Du chantage au chat, maintenant. Bon, je fais le café, mais tu feras les tartines.", "이젠 고양이를 볼모로 협박까지 하네. 좋아, 커피는 내가 내릴게. 대신 타르틴은 네가 만들어."),
(MA, "Marché conclu. Tu te rends compte ? Il y a dix jours, on signait avec les banques et avec le syndicat. Et ce matin, je n'ai rien à faire. Rien du tout.",
     "좋아. 실감 나? 열흘 전엔 은행이랑, 노조랑 서명하고 있었는데. 오늘 아침엔 할 일이 하나도 없어. 정말 하나도."),
(I, "Profites-en. L'assemblée générale est en juin, et je n'ai pas fini le rapport financier. Lundi, je retourne à mes tableaux.",
    "즐겨 둬. 주주총회가 6월인데 난 재무 보고서를 아직 못 끝냈어. 월요일엔 다시 내 표들한테 돌아가야 해."),
(MA, "Figaro regarde la cocotte de Momo comme un ennemi personnel. Tu as bien fait de la rapporter ici.",
     "피가로가 모모의 압력솥을 개인적인 원수 보듯 하네. 여기로 가져오길 잘했어."),
(I, "Elle est mieux ici qu'à Saint-Étienne. Là-bas, c'est le bureau, même la nuit. Ici, c'est chez nous.", "생테티엔보다 여기가 낫지. 거긴 밤에도 사무실이야. 여기가 우리 집이고."),
(MA, "« Chez nous »... Tu l'as dit. Je t'ai entendue, je ne suis pas sourd.", "'우리 집'이라... 방금 그렇게 말했지. 들었어, 나 귀 안 먹었어."),
(I, "Doucement, Strasbourg. Tu n'as toujours pas de clé.", "진정해, 스트라스부르. 너 아직 열쇠도 없어."),
(None, "Le téléphone de Mathieu vibre. Il lit le message, et son sourire disparaît.", "마티외의 휴대폰이 진동한다. 메시지를 읽는 그의 얼굴에서 미소가 사라진다."),
(MA, "C'est Aubry. Il est à Paris et veut prendre un café avec moi ce matin. Seul. Il écrit : « Rien d'urgent. »",
     "오브리야. 파리에 와 있는데 오늘 아침에 나랑 커피 한잔하재. 단둘이. '급한 건 아니다'래."),
(I, "Quand Aubry écrit « rien d'urgent », c'est toujours urgent. Vas-y. Moi, je file à Aligre : Jojo m'a gardé des rougets.",
    "오브리가 '급한 거 아니다'라고 쓰면 늘 급한 거야. 가 봐. 난 알리그르 시장에 갈게. 조조 아저씨가 노랑촉수를 남겨 뒀대."),
(None, "10 h. Le bar d'un grand hôtel de l'avenue Hoche. Frédéric Aubry attend devant deux expressos.", "오전 10시. 오슈 거리의 한 고급 호텔 바. 프레데리크 오브리가 에스프레소 두 잔을 앞에 두고 기다리고 있다."),
(AU, "Je vais droit au but, Mathieu. Sternfeld, le groupe munichois, veut racheter Verdier. Cent pour cent du capital, pour une valeur d'entreprise de cinq cent vingt millions d'euros, dette comprise.",
     "단도직입적으로 말하죠, 마티외. 뮌헨의 Sternfeld 그룹이 Verdier를 사겠답니다. 지분 100%, 부채 포함 기업가치 5억 2천만 유로로요."),
(MA, "Maintenant ? Dix jours après l'accord avec les banques ?", "지금요? 은행과 합의한 지 열흘 만에요?"),
(AU, "Justement : grâce à vous, Verdier est redevenue vendable. Pour Arcane, c'est la sortie idéale. Et pour vous, Sternfeld prévoit une prime de cession de deux millions d'euros et un siège à son comité exécutif. Mais si vous recommandez la vente, la famille suivra. Sinon, rien ne se fera.",
     "바로 그래서죠. 당신 덕분에 Verdier가 다시 팔릴 만한 회사가 됐어요. 아르칸으로선 이상적인 투자 회수 기회고요. 그리고 당신에겐 Sternfeld가 매각 보너스 200만 유로와 그룹 경영위원회 자리를 준비하고 있습니다. 다만 당신이 매각을 권고해야 가문이 따라옵니다. 아니면 아무것도 성사되지 않아요."),
(MA, "Vous me proposez de l'argent pour que je recommande la vente de l'entreprise que je dirige ?", "제가 경영하는 회사의 매각을 권고하라고 돈을 제안하시는 겁니까?"),
(AU, "Je vous propose un avenir. Réfléchissez. Une dernière chose : tout ceci reste entre nous. Y compris vis-à-vis de madame Marchetti. Avec votre... situation, vous comprendrez que je préfère être prudent.",
     "저는 미래를 제안하는 겁니다. 생각해 보세요. 마지막으로, 이 일은 우리끼리만 아는 겁니다. 마르케티 씨에게도요. 두 분의... 사정을 생각하면, 제가 조심하고 싶어 하는 걸 이해하시겠죠."),

# ---------- 2. Le comité de direction ----------
(None, "Le soir même, Oberkampf. Mathieu est revenu avec des croissants et un bouquet de mimosa.", "그날 저녁, 오베르캉프. 마티외는 크루아상과 미모사 꽃다발을 들고 돌아왔다."),
(I, "Du mimosa et des croissants... Ça cache quelque chose. Qu'est-ce qu'il voulait, Aubry ?", "미모사에 크루아상이라... 뭔가 숨기는 거 같은데. 오브리는 뭘 원했어?"),
(MA, "Rien de spécial. Le calendrier de l'assemblée, deux ou trois idées à lui. Je t'en parlerai quand j'y verrai plus clair.",
     "별거 아니야. 주주총회 일정이랑, 자기 생각 두세 가지. 좀 더 정리되면 얘기해 줄게."),
(I, "Des idées à lui ? Méfie-toi. Les idées d'Aubry finissent toujours en tableau de cession.", "자기 생각? 조심해. 오브리 생각은 늘 매각 일정표로 끝나."),
(MA, "Je me méfie. Promis.", "조심할게. 약속해."),
(I, "Bien. Parce que si un jour Aubry te parle de vendre, je veux être la première au courant. Pas la deuxième.", "좋아. 언젠가 오브리가 너한테 매각 얘기를 꺼내면, 난 그걸 제일 먼저 알고 싶으니까. 두 번째가 아니라."),
(None, "Lundi, 9 h. Saint-Étienne, siège de Verdier Industries. Comité de direction. Autour de la table : Inès, Mathieu, Robert Chazal, et Martine Roche qui prend des notes.",
       "월요일 오전 9시. 생테티엔, Verdier Industries 본사. 경영위원회. 테이블에는 이네스, 마티외, 로베르 샤잘, 그리고 회의록을 적는 마르틴 로슈."),
(MA, "Bonjour à tous. Un seul point à l'ordre du jour : la présentation à l'assemblée générale. Madame Marchetti, vous avez la parole.",
     "모두 안녕하십니까. 안건은 하나입니다. 주주총회 발표입니다. 마르케티 이사님, 말씀하십시오."),
(I, "Merci, monsieur Kessler. Bonne nouvelle d'abord : au quatrième trimestre, le résultat d'exploitation est positif, pour la première fois depuis trois ans.",
    "감사합니다, 케슬레르 대표님. 좋은 소식부터 드리겠습니다. 4분기 영업이익이 3년 만에 처음으로 흑자를 기록했습니다."),
(CH, "Enfin ! Les gars de la ligne vont être contents. Ils ont mérité de l'entendre.", "드디어! 라인 사람들이 좋아하겠네요. 그 말을 들을 자격이 있죠."),
(MA, "Et la trésorerie, madame Marchetti ?", "현금 사정은요, 마르케티 이사님?"),
(I, "Stable. Pour la première fois, nous n'avons pas eu besoin de tirer sur nos lignes de crédit pendant l'hiver.", "안정적입니다. 처음으로 겨울 동안 신용 한도를 끌어 쓸 필요가 없었습니다."),
(I, "Ils l'entendront. Ensuite, les précommandes de la Stéphanoise 2 dépassent déjà trente mille unités. Et grâce au rééchelonnement, nous n'avons plus d'échéance bancaire importante avant trois ans.",
    "듣게 될 겁니다. 다음으로, 스테파누아즈 2 사전 주문이 벌써 3만 대를 넘었습니다. 그리고 채무 재조정 덕분에 앞으로 3년간 큰 은행 만기가 없습니다."),
(I, "Je propose donc de présenter un plan d'indépendance : une marge d'exploitation de cinq pour cent dans trois ans, sans nouvel actionnaire, avec Saint-Étienne et Roanne au cœur du projet.",
    "따라서 독자 회생 계획을 발표할 것을 제안합니다. 새 주주 없이 3년 뒤 영업이익률 5%, 그리고 생테티엔과 로안 공장을 계획의 중심에 둡니다."),
(MA, "Merci. Une question, pour l'exercice : et si un industriel nous faisait une offre ? Un grand groupe, avec des moyens que nous n'avons pas ?",
     "감사합니다. 연습 삼아 질문 하나 하죠. 만약 어느 제조 대기업이 우리에게 인수 제안을 한다면요? 우리에겐 없는 자금력을 가진 대형 그룹이요."),
(None, "Un silence. Martine lève les yeux de son carnet.", "정적. 마르틴이 수첩에서 눈을 든다."),
(I, "Nous la refuserions. Vendre maintenant, ce serait vendre au plus bas, au moment précis où le redressement commence à payer. Ce serait offrir deux ans de travail à l'acheteur.",
    "거절하겠죠. 지금 판다는 건 최저가에 판다는 겁니다. 회생이 막 결실을 맺기 시작하는 바로 그 순간에요. 2년간의 노력을 인수자에게 바치는 셈입니다."),
(MA, "Ou bien ce serait garantir l'avenir des usines avec quelqu'un qui peut investir. Nous avons un produit qui marche, un seul. Si la Stéphanoise 2 rate son lancement, nous n'avons pas de deuxième chance.",
     "아니면 투자할 능력이 있는 쪽과 함께 공장들의 미래를 보장하는 일일 수도 있죠. 우리에겐 잘되는 제품이 하나 있습니다. 딱 하나요. 스테파누아즈 2 출시가 실패하면 두 번째 기회는 없습니다."),
(I, "C'est pour ça que mon plan prévoit une réserve de trésorerie de quarante millions. J'ai testé trois scénarios, dont un très pessimiste. Il tient dans les trois.",
    "그래서 제 계획엔 4천만 유로의 현금 예비금이 들어 있습니다. 매우 비관적인 것을 포함해 시나리오 세 가지를 시험했습니다. 세 경우 모두 버팁니다."),
(CH, "Pardon, monsieur Kessler, mais pourquoi cette question ? Il y a quelque chose qu'on devrait savoir ?", "실례지만 케슬레르 대표님, 왜 그런 질문을 하시죠? 저희가 알아야 할 뭔가가 있습니까?"),
(MA, "Non, Robert. C'est le rôle d'un CEO de se poser toutes les questions, même celles qui fâchent.", "아니요, 로베르. 모든 질문을 던져 보는 게 CEO의 역할입니다. 불편한 질문까지도요."),
(CH, "Bien sûr. Mais à l'atelier, les gens ont l'oreille fine. Une question pareille, ça devient vite une rumeur.", "물론이죠. 하지만 작업장 사람들은 귀가 밝습니다. 그런 질문은 금세 소문이 돼요."),
(I, "Alors je vous réponds avec la même franchise : un acheteur ne paie jamais pour l'avenir qu'il nous retire. Je maintiens ma proposition.",
    "그럼 저도 같은 솔직함으로 답하겠습니다. 인수자는 우리에게서 빼앗아 가는 미래의 값을 절대 치르지 않습니다. 제 제안을 유지합니다."),
(MA, "Bien. Nous validons la structure de la présentation. Merci à tous.", "좋습니다. 발표 구성은 승인하겠습니다. 모두 수고하셨습니다."),
(None, "Les autres sortent. Martine reste, son carnet contre la poitrine, et ferme la porte.", "다른 사람들이 나간다. 마르틴은 수첩을 가슴에 안은 채 남아 문을 닫는다."),
(MR, "Monsieur Kessler, monsieur Aubry a rappelé deux fois ce matin. Et un monsieur de Munich aussi. Il parlait très bien français, avec un accent bavarois.",
     "대표님, 오브리 씨가 오늘 아침에 두 번 전화하셨어요. 그리고 뮌헨에서 어떤 분도요. 프랑스어를 아주 잘하시던데, 바이에른 억양이 있었어요."),
(MA, "Merci, Martine. Ne notez rien de ces appels, s'il vous plaît.", "고마워요, 마르틴. 그 전화들은 아무 데도 적지 말아 주세요."),
(MR, "Je ne note jamais ce qui compte vraiment. En trente ans, j'ai vu passer trois projets de vente dans cette maison. Aucun n'est entré par la porte principale.",
     "정말 중요한 건 원래 안 적어요. 30년 동안 이 회사에서 매각 계획을 세 번 봤죠. 정문으로 들어온 건 하나도 없었어요."),
(MA, "Et comment ça s'est terminé ?", "그래서 어떻게 끝났어요?"),
(MR, "Mal, à chaque fois. Pas à cause de la vente. À cause de ceux qui l'avaient apprise par la porte de derrière. Bonne journée, monsieur Kessler.",
     "매번 나쁘게요. 매각 때문이 아니라, 그걸 뒷문으로 알게 된 사람들 때문에요. 좋은 하루 보내세요, 대표님."),
(None, "Mathieu reste seul. Il sort de sa poche son vieux marqueur vert, le fait tourner entre ses doigts, puis le range sans rien écrire.",
       "마티외가 혼자 남는다. 주머니에서 낡은 초록 마커를 꺼내 손가락 사이로 돌리다가, 아무것도 쓰지 않고 다시 집어넣는다."),
(MA, "« Quand j'y verrai plus clair »... Bravo, Mathieu. Très courageux.", "'좀 더 정리되면'이라... 잘한다, 마티외. 아주 용감하네."),
(MA, "Martine, pouvez-vous me trouver tout ce qui a été publié sur Sternfeld ces cinq dernières années ? Discrètement.",
     "마르틴, 지난 5년간 Sternfeld에 대해 나온 자료를 전부 찾아 줄 수 있어요? 조용히요."),
(MR, "Discrètement, c'est mon deuxième prénom. Mais permettez-moi un conseil de vieille secrétaire : ne laissez pas madame Marchetti l'apprendre par quelqu'un d'autre.",
     "조용히는 제 중간 이름이에요. 하지만 늙은 비서로서 한마디만 드릴게요. 마르케티 이사님이 다른 사람한테서 듣게 하지는 마세요."),
(MA, "Je lui dirai, Martine. Ce soir.", "말할 거예요, 마르틴. 오늘 밤에."),

# ---------- 3. Analyse : le reporting d'Arcane ----------
(None, "Mercredi, 14 h. Bureau de la directrice financière. Mathieu est à Roanne pour la journée. Baptiste Morel est venu de Paris pour le reporting mensuel d'Arcane.",
       "수요일 오후 2시. 재무 책임자 사무실. 마티외는 하루 종일 로안 공장에 가 있다. 바티스트 모렐이 아르칸의 월간 보고를 받으러 파리에서 왔다."),
(B, "Inès, toujours aussi rayonnante. Saint-Étienne te réussit.", "이네스, 여전히 빛나네. 생테티엔이 너한테 잘 맞나 봐."),
(I, "Ici, c'est « madame Marchetti », Baptiste. Nous ne sommes plus chez Hélène. Vous avez vingt minutes.", "여기선 '마르케티 이사'예요, 바티스트. 우린 더 이상 엘렌네 회사에 있지 않아요. 20분 드리죠."),
(B, "Comme vous voudrez, madame Marchetti. Vos chiffres du trimestre sont bons, je le reconnais. Mais votre plan d'indépendance suppose que tout se passe bien pendant trois ans. Pas de nouveau rappel, pas de cyberattaque, pas de hausse des taux.",
    "원하시는 대로 하죠, 마르케티 이사님. 분기 숫자는 좋네요, 인정합니다. 하지만 독자 회생 계획은 3년 동안 모든 게 잘 풀린다는 가정 위에 서 있어요. 리콜도 다시 없고, 사이버 공격도 없고, 금리 인상도 없고."),
(I, "Faux. J'ai intégré un scénario de crise : un deuxième rappel et une baisse des ventes de quinze pour cent la même année. La réserve de quarante millions couvre les deux.",
    "틀렸어요. 위기 시나리오를 넣었어요. 같은 해에 두 번째 리콜과 판매 15% 감소. 4천만 유로 예비금이 둘 다 감당합니다."),
(B, "Et la Stéphanoise 2 ? Trente mille précommandes, c'est joli. Mais votre point mort est à combien ?", "스테파누아즈 2는요? 사전 주문 3만 대, 보기 좋네요. 그런데 손익분기점이 몇 대죠?"),
(I, "Quatre-vingt-cinq mille unités la première année. Nous y serons à l'automne, si le rythme se maintient.", "첫해 8만 5천 대요. 지금 속도가 유지되면 가을에 도달합니다."),
(B, "Sur le papier. Mais un fonds ne vit pas sur le papier. Arcane est entré au capital il y a six ans. Nos investisseurs attendent leur argent.",
    "서류상으로는요. 하지만 펀드는 서류로 먹고살지 않아요. 아르칸이 지분을 사들인 지 6년이 됐어요. 우리 투자자들은 돈을 기다리고 있고요."),
(I, "Alors qu'Arcane vende ses parts. Personne n'oblige l'entreprise entière à être vendue pour que votre fonds puisse sortir.", "그럼 아르칸이 자기 지분을 팔면 되죠. 당신네 펀드가 빠져나가려고 회사 전체가 팔려야 할 이유는 없어요."),
(B, "Qui voudrait quarante pour cent d'une entreprise familiale, avec Hubert Verdier à la table ? Non, il faut un industriel. D'ailleurs, il me manque vos prévisions de trésorerie détaillées sur cinq ans. Pour la data room.",
    "위베르 베르디에가 테이블에 앉아 있는 가족기업 지분 40%를 누가 원하겠어요? 아니요, 제조 기업이 필요해요. 그러고 보니 5년 치 상세 현금흐름 전망이 빠졌네요. 데이터룸에 올릴 거요."),
(I, "Quelle data room ?", "무슨 데이터룸이요?"),
(B, "Celle de Sternfeld, voyons. Leurs équipes commencent l'audit la semaine prochaine. Mathieu ne vous a rien dit ? ... Ah. Je suis désolé, je pensais que vous partagiez tout.",
    "Sternfeld 거요, 당연히. 다음 주에 그쪽 팀이 실사를 시작해요. 마티외가 아무 말도 안 했어요? ...아. 미안해요, 두 분은 뭐든 공유하는 줄 알았거든요."),
(None, "Inès ne bouge pas. Seule sa main se crispe sur son stylo.", "이네스는 꼼짝하지 않는다. 펜을 쥔 손에만 힘이 들어간다."),
(I, "Continuez, puisque vous avez commencé. Quelles sont les conditions ?", "시작했으니 계속하시죠. 조건이 뭐죠?"),
(B, "Cinq cent vingt millions, dette comprise. Sternfeld garde Saint-Étienne au moins deux ans. Et Mathieu a une belle prime de cession, deux millions, plus un siège à leur comité exécutif. À sa place, moi aussi, je serais discret.",
    "부채 포함 5억 2천만 유로. Sternfeld는 생테티엔을 최소 2년 유지하고요. 그리고 마티외에겐 두둑한 매각 보너스가 있어요. 200만 유로에 그룹 경영위원회 자리까지. 내가 그 사람이라도 입을 다물었을 거예요."),
(I, "Merci pour l'information, monsieur Morel. Vous aurez mes prévisions quand le conseil d'administration m'aura demandé de vous les donner. Pas avant. Au revoir.",
    "정보 고마워요, 모렐 씨. 이사회가 넘겨주라고 하면 그때 전망치를 드리죠. 그전엔 안 됩니다. 안녕히 가세요."),
(B, "Comme vous voudrez. Pour ce que ça vaut, Inès... Je ne pensais pas qu'il vous le cacherait.", "원하시는 대로. 이런 말이 무슨 소용이겠냐마는, 이네스... 그가 당신한테 숨길 줄은 몰랐어요."),
(I, "Si, vous le pensiez. C'est même pour ça que vous êtes venu en personne.", "아니, 알았잖아요. 그래서 직접 온 거고요."),
(None, "Baptiste sorti, Inès compose le numéro d'Hélène Vasseur.", "바티스트가 나가자, 이네스는 엘렌 바쇠르의 번호를 누른다."),
(H, "Inès ? Tu as une voix étrange. Qu'est-ce qui se passe ?", "이네스? 목소리가 이상하네. 무슨 일이야?"),
(I, "Hélène, je vous appelle en tant qu'administratrice indépendante. Le conseil a-t-il été informé d'une offre de Sternfeld sur Verdier ?",
    "엘렌, 사외이사님께 전화드리는 거예요. 이사회가 Sternfeld의 Verdier 인수 제안에 대해 보고받았나요?"),
(H, "Une offre ? Absolument pas. Si Aubry négocie une cession dans le dos du conseil, c'est un problème de gouvernance. Et une prime promise au CEO, c'est un conflit d'intérêts qui doit être déclaré.",
    "인수 제안? 전혀. 오브리가 이사회 몰래 매각을 협상하고 있다면 그건 지배구조 문제야. 그리고 CEO에게 약속된 보너스는 반드시 신고해야 하는 이해충돌이고."),
(I, "Mathieu le sait depuis samedi. Cinq jours. Il ne m'a rien dit.", "마티외는 토요일부터 알고 있었어요. 닷새째예요. 저한테 아무 말도 안 했어요."),
(H, "... Je vois. Inès, écoute-moi. Baptiste ne t'a pas dit ça par gentillesse. Avant de juger Mathieu, parle-lui.", "...그렇구나. 이네스, 내 말 들어. 바티스트가 친절해서 그 얘길 한 게 아니야. 마티외를 판단하기 전에 먼저 그 사람과 얘기해."),
(I, "Je sais très bien pourquoi Baptiste me l'a dit. Ce qui me fait mal, c'est que Mathieu, lui, ne me l'ait pas dit.", "바티스트가 왜 그 얘길 했는지는 잘 알아요. 제가 아픈 건, 마티외는 말하지 않았다는 거예요."),
(H, "Et l'offre elle-même ? Mets ton cœur de côté une minute et parle-moi comme à une administratrice.", "그럼 제안 자체는? 잠깐 마음은 내려놓고 이사에게 말하듯 말해 봐."),
(I, "Cinq cent vingt millions moins trois cent dix de dette nette : il reste deux cent dix millions pour les actionnaires. Avec notre plan, l'entreprise en vaudra le double dans trois ans. Sternfeld achète au plus bas.",
    "5억 2천만에서 순부채 3억 1천만을 빼면 주주에게 2억 1천만이 남아요. 우리 계획대로라면 3년 뒤 회사 가치는 그 두 배가 돼요. Sternfeld는 바닥에서 사는 거예요."),
(H, "Et l'accord que Mathieu a signé avec les syndicats ? Cinq ans de maintien du site de Saint-Étienne ?", "마티외가 노조와 서명한 합의는? 생테티엔 공장 5년 존치 말이야."),
(I, "Sternfeld ne s'engage que sur deux ans. Il a serré la main de Josiane Fabre pour cinq, Hélène. Il y a dix jours.", "Sternfeld는 2년만 약속해요. 마티외는 조지안 파브르와 5년을 걸고 악수했어요, 엘렌. 열흘 전에요."),
(H, "Alors c'est exactement ce que tu dois lui demander. Ce soir. Et pas en tant que CFO.", "그럼 바로 그걸 그 사람한테 물어봐야지. 오늘 밤. 그리고 CFO로서가 아니라."),
(None, "21 h. L'appartement d'Inès, quartier Jacquard. Mathieu rentre de Roanne, la cravate défaite. Elle a mis deux assiettes sur la table.",
       "밤 9시. 자카르 지구의 이네스 아파트. 마티외가 넥타이를 풀어 헤친 채 로안에서 돌아온다. 그녀는 식탁에 접시 두 개를 놓아 두었다."),
(I, "Tu as l'air fatigué. Tu as quelque chose à me dire ?", "피곤해 보이네. 나한테 할 말 있어?"),
(MA, "... Non. Juste que je suis crevé. Les presses de Roanne ont encore lâché deux fois aujourd'hui.", "...아니. 그냥 녹초가 됐어. 로안 프레스기가 오늘 또 두 번이나 멈췄어."),
(I, "D'accord. Bonne nuit, Mathieu.", "그래. 잘 자, 마티외."),

# ---------- 4. Terrain : l'usine ----------
(None, "Jeudi, 7 h. Usine de Saint-Étienne, atelier des soupapes. Inès et Mathieu sont venus pour la visite trimestrielle. Ils ne se sont presque pas parlé depuis la veille.",
       "목요일 오전 7시. 생테티엔 공장 밸브 작업장. 이네스와 마티외가 분기 현장 방문을 왔다. 둘은 어젯밤부터 거의 말을 하지 않았다."),
(CH, "Monsieur Kessler, madame Marchetti, je vous préviens : l'ambiance est électrique ce matin. Une rumeur court depuis hier soir.",
     "대표님, 이사님, 미리 말씀드리죠. 오늘 아침 분위기가 험악합니다. 어젯밤부터 소문이 돌고 있어요."),
(MA, "Quelle rumeur ?", "무슨 소문이요?"),
(JF, "Que des Allemands vont visiter l'usine la semaine prochaine. Avec des blouses blanches et des calculettes. Bonjour, monsieur le directeur général.",
     "다음 주에 독일 사람들이 공장을 둘러보러 온다는 소문이요. 흰 가운에 계산기를 들고요. 안녕하세요, 대표님."),
(MA, "Bonjour, madame Fabre. Je comprends votre inquiétude. Aucune décision n'a été prise.", "안녕하세요, 파브르 씨. 걱정하시는 거 이해합니다. 아무것도 결정되지 않았습니다."),
(JF, "Ce n'est pas ce que je vous demande. Je vous demande s'il y a un projet de vente. Oui ou non ?", "제가 묻는 건 그게 아니에요. 매각 계획이 있느냐고 묻는 거예요. 예스예요, 노예요?"),
(None, "Mathieu hésite. Les ouvriers ont arrêté leurs machines. Inès fait un pas en avant.", "마티외가 머뭇거린다. 노동자들이 기계를 멈췄다. 이네스가 한 걸음 앞으로 나선다."),
(I, "Madame Fabre, il y a une offre d'un groupe industriel. Elle n'a été ni acceptée ni présentée au conseil d'administration. C'est tout ce que je peux vous dire aujourd'hui, et c'est la vérité.",
    "파브르 씨, 한 제조 그룹의 인수 제안이 있습니다. 수락되지도, 이사회에 상정되지도 않았습니다. 오늘 말씀드릴 수 있는 건 이게 전부이고, 이건 사실입니다."),
(None, "Mathieu se tourne vers elle, livide.", "마티외가 창백한 얼굴로 그녀를 돌아본다."),
(JF, "Merci, madame Marchetti. Au moins, vous, vous répondez aux questions. Et notre accord, monsieur Kessler ? Cinq ans pour Saint-Étienne. Il vaudra quoi, si la boîte est vendue ?",
     "고마워요, 마르케티 이사님. 적어도 이사님은 질문에 대답은 하시네요. 그럼 우리 합의는요, 케슬레르 대표님? 생테티엔 5년. 회사가 팔리면 그게 무슨 가치가 있죠?"),
(MA, "Un accord signé engage l'entreprise, madame Fabre. Un acheteur le reprend avec tout le reste.", "서명된 합의는 회사를 구속합니다, 파브르 씨. 인수자는 다른 모든 것과 함께 그것도 승계합니다."),
(JF, "Un acheteur peut aussi le dénoncer, je connais le Code du travail par cœur. Si vous voulez qu'on vous croie encore, il faudra que le CSE soit consulté avant toute décision. Pas après.",
     "인수자는 그걸 파기할 수도 있죠. 노동법은 제가 다 외우고 있어요. 앞으로도 저희가 대표님을 믿길 원하시면, 어떤 결정이든 내리기 전에 CSE와 협의해야 해요. 후가 아니라요."),
(MA, "Vous avez ma parole. Le CSE sera consulté avant toute décision.", "약속드립니다. 어떤 결정이든 그 전에 CSE와 협의하겠습니다."),
(JF, "Votre parole... Il y a dix jours, elle valait cinq ans. Aujourd'hui, je ne sais plus. Les gars, au travail.", "대표님 약속이라... 열흘 전엔 그게 5년짜리였죠. 오늘은 모르겠네요. 자, 다들 일하세요."),
(None, "Les machines redémarrent. Momo s'approche, essuyant ses mains sur son bleu de travail.", "기계들이 다시 돌아간다. 모모가 작업복에 손을 닦으며 다가온다."),
(MO, "Patron, vous permettez qu'un vieux vous dise un truc ?", "사장님, 늙은이가 한마디 해도 될까요?"),
(MA, "Toujours, Momo.", "언제든지요, 모모."),
(MO, "En quarante ans, j'ai connu quatre patrons. On peut tout encaisser ici : les crises, les plans sociaux, les Chinois. Mais le jour où on nous cache quelque chose, on comprend que c'est déjà décidé.",
     "40년 동안 사장 넷을 겪었어요. 여기선 뭐든 버틸 수 있어요. 위기도, 구조조정도, 중국 사람들도. 그런데 뭔가를 숨기는 날이면, 이미 결정이 났구나 하고 알게 되죠."),
(MA, "Rien n'est décidé, Momo. Je vous le jure.", "아무것도 결정되지 않았어요, 모모. 맹세해요."),
(MO, "Alors il ne fallait pas le cacher. Ce n'est pas à moi qu'il faut dire ça, c'est à elle.", "그럼 숨기지 말았어야죠. 그 말은 나한테 할 게 아니라, 저분한테 해야죠."),
(None, "Momo désigne Inès d'un mouvement du menton, puis retourne à sa machine.", "모모는 턱짓으로 이네스를 가리키고는 자기 기계로 돌아간다."),
(None, "Le parking de l'usine, sous une pluie fine. Ils marchent vers la voiture.", "가랑비가 내리는 공장 주차장. 두 사람이 차를 향해 걷는다."),
(MA, "Depuis quand tu sais ?", "언제부터 알았어?"),
(I, "Depuis hier, quatorze heures. Par Baptiste. Il m'a demandé des chiffres pour la data room de Sternfeld.", "어제 오후 2시부터. 바티스트한테서. Sternfeld 데이터룸에 올릴 숫자를 달라더라."),
(MA, "Hier ? Et hier soir, à table, tu n'as rien dit ?", "어제? 그런데 어젯밤 식탁에서 아무 말도 안 했어?"),
(I, "Je t'ai posé une question, hier soir. Tu as répondu que les presses de Roanne étaient en panne.", "어젯밤에 내가 질문을 했지. 넌 로안 프레스기가 고장 났다고 대답했어."),
(MA, "Inès, il faut qu'on parle.", "이네스, 우리 얘기 좀 해야 해."),
(I, "Pas ici. Demain, après la visio avec Aubry. J'ai demandé à Hélène d'y assister.", "여기선 안 돼. 내일, 오브리와 화상회의 끝나고. 엘렌한테도 참석해 달라고 했어."),
(MA, "Tu as appelé Hélène ? Sans m'en parler ?", "엘렌한테 전화했어? 나한테 말도 없이?"),
(I, "Oui. Ça fait quoi, de l'apprendre par quelqu'un d'autre ?", "응. 다른 사람한테서 듣는 기분이 어때?"),
(MA, "... Je l'ai mérité, celle-là.", "...그건 내가 당해도 싸지."),

# ---------- 5. Décision : la visio, puis la dispute ----------
(None, "Vendredi, 17 h. Salle du conseil. Sur l'écran, Frédéric Aubry et Baptiste Morel depuis Paris ; Hélène Vasseur depuis son bureau. Inès et Mathieu sont assis côte à côte, à un mètre l'un de l'autre. Martine range des dossiers au fond de la salle.",
       "금요일 오후 5시. 이사회실. 화면에는 파리에 있는 프레데리크 오브리와 바티스트 모렐, 그리고 자기 사무실의 엘렌 바쇠르. 이네스와 마티외는 1미터쯤 떨어져 나란히 앉아 있다. 마르틴은 방 뒤편에서 서류를 정리하고 있다."),
(AU, "Je vois que madame Marchetti est au courant. Tant mieux, ça nous fera gagner du temps. Monsieur Kessler, je vous avais demandé de la discrétion, pas le silence. Enfin, passons.",
     "마르케티 씨도 알고 계신 모양이군요. 잘됐네요, 시간이 절약되겠어요. 케슬레르 씨, 제가 부탁한 건 신중함이었지 침묵은 아니었는데요. 뭐, 넘어갑시다."),
(MA, "Vous m'avez demandé exactement le silence, monsieur Aubry. Je n'aurais pas dû l'accepter.", "오브리 씨가 부탁하신 건 정확히 침묵이었습니다. 제가 그걸 받아들이지 말았어야 했습니다."),
(H, "Avant d'aller plus loin, une remarque d'administratrice. Une offre portant sur cent pour cent du capital doit être présentée au conseil. Et toute prime promise au directeur général doit être déclarée. Aujourd'hui, ni l'un ni l'autre n'a été fait.",
    "더 나아가기 전에 사외이사로서 한마디 하겠습니다. 지분 100%에 대한 제안은 이사회에 상정되어야 합니다. 그리고 대표이사에게 약속된 모든 보너스는 신고되어야 하고요. 현재 둘 다 이루어지지 않았습니다."),
(AU, "Ce sera fait, Hélène. C'est précisément l'objet de cette réunion. Les chiffres sont simples : Sternfeld offre cinq cent vingt millions d'euros de valeur d'entreprise. Ils investiraient quatre-vingts millions dans la Stéphanoise 2 et la distribueraient dans quarante pays. Saint-Étienne serait maintenu deux ans.",
    "그렇게 될 겁니다, 엘렌. 바로 그게 이 회의의 목적이에요. 숫자는 간단합니다. Sternfeld는 기업가치 5억 2천만 유로를 제시합니다. 스테파누아즈 2에 8천만 유로를 투자하고 40개국에 유통할 계획입니다. 생테티엔은 2년간 유지되고요."),
(I, "Deux ans, alors que l'accord signé avec les syndicats en prévoit cinq. Et une valorisation calculée sur nos pires années, juste avant que le redressement apparaisse dans les comptes.",
    "2년이요. 노조와 서명한 합의는 5년인데요. 그리고 가치 평가는 회생이 장부에 드러나기 직전, 우리의 최악의 해들을 기준으로 계산됐습니다."),
(AU, "Madame Marchetti, votre plan est séduisant. Mais un plan à trois ans, c'est une promesse. Une offre ferme, c'est de l'argent.", "마르케티 씨, 당신 계획은 매력적이에요. 하지만 3년짜리 계획은 약속이죠. 확정 제안은 돈이고요."),
(I, "Elle n'est pas ferme, monsieur Aubry : elle est indicative, et soumise à un audit que personne n'a autorisé. Par ailleurs, un dirigeant qui touche deux millions en cas de vente ne peut pas recommander cette vente en toute objectivité.",
    "확정 제안이 아닙니다, 오브리 씨. 구속력 없는 의향 제안이고, 아무도 승인하지 않은 실사를 조건으로 하고 있습니다. 게다가 매각 시 200만 유로를 받는 경영자는 그 매각을 객관적으로 권고할 수 없습니다."),
(None, "Un silence. Mathieu fixe la table.", "정적. 마티외는 테이블만 바라본다."),
(MA, "Madame Marchetti a raison sur ce point. Si je fais une recommandation, je renoncerai à cette prime avant de la faire. Je l'écrirai noir sur blanc au conseil.",
     "그 점은 마르케티 이사님 말이 맞습니다. 제가 권고를 하게 된다면, 그 전에 보너스를 포기하겠습니다. 이사회에 서면으로 분명히 밝히겠습니다."),
(AU, "Comme vous voudrez. Mais j'ai besoin de savoir si mon CEO soutient l'opération. Le conseil se réunira mardi. Votre recommandation, monsieur Kessler : lundi.",
     "원하시는 대로. 하지만 저는 우리 CEO가 이 거래를 지지하는지 알아야 합니다. 이사회는 화요일에 열립니다. 케슬레르 씨, 당신의 권고는 월요일까지."),
(MA, "Vous l'aurez lundi.", "월요일에 드리겠습니다."),
(None, "L'écran devient noir. Martine continue de ranger ses dossiers, très lentement.", "화면이 꺼진다. 마르틴은 아주 천천히 서류 정리를 계속한다."),
(I, "Monsieur Kessler, puisque nous sommes entre dirigeants : depuis quand connaissez-vous cette offre, exactement ?", "케슬레르 대표님, 경영자끼리니까 여쭙겠습니다. 정확히 언제부터 이 제안을 알고 계셨습니까?"),
(MA, "Depuis samedi, madame Marchetti. Vous le savez très bien.", "토요일부터입니다, 마르케티 이사님. 잘 알고 계시잖아요."),
(I, "Samedi. Le jour où vous êtes rentré avec du mimosa en disant : « Rien de spécial. » Vous avez eu six jours, monsieur Kessler. Un comité de direction, cinq dîners, une question directe.",
    "토요일. 미모사를 들고 와서 '별거 아니야'라고 하신 날이죠. 대표님에겐 엿새가 있었습니다. 경영위원회 한 번, 저녁 식사 다섯 번, 직접적인 질문 한 번."),
(MA, "Et vous, vous avez appris la nouvelle mercredi et vous avez attendu jeudi pour l'annoncer devant Josiane Fabre et quarante ouvriers. Sans m'en dire un mot.",
     "그리고 이사님은 수요일에 그 소식을 듣고 목요일까지 기다렸다가 조지안 파브르와 노동자 마흔 명 앞에서 발표하셨죠. 저한테는 한마디도 없이요."),
(I, "J'ai répondu à une salariée qui demandait la vérité. Vous, vous ne pouviez pas la dire.", "진실을 묻는 직원에게 대답했을 뿐입니다. 대표님은 그걸 말하지 못하셨고요."),
(None, "Martine prend ses dossiers, sort sans un mot et ferme doucement la porte derrière elle.", "마르틴이 서류를 챙겨 말없이 나가며 뒤로 문을 조용히 닫는다."),
(I, "Maintenant qu'on est seuls, c'est toi qui vas m'écouter. Je ne te reproche pas d'avoir écouté Aubry. Je te reproche de m'avoir regardée dans les yeux mercredi soir et de m'avoir parlé de tes presses.",
    "이제 우리 둘뿐이니까, 네가 내 말을 들어. 오브리 말을 들은 걸 탓하는 게 아니야. 수요일 밤에 내 눈을 똑바로 보면서 프레스기 얘기나 한 걸 탓하는 거야."),
(MA, "Je ne t'ai pas menti ! Je n'avais rien décidé. Je voulais savoir ce que j'en pensais, moi, avant que tu aies la réponse. Chez nous, tu as toujours la réponse avant que j'aie fini ma question.",
     "거짓말한 거 아니야! 아무것도 결정 안 했어. 네가 답을 내놓기 전에, 내가 어떻게 생각하는지 알고 싶었어. 우리 사이엔 늘 내가 질문을 끝내기도 전에 네가 답을 갖고 있잖아."),
(I, "Donc c'est ma faute ? Parce que je réfléchis trop vite, tu as le droit de me cacher la vente de l'entreprise que je dirige avec toi ?",
    "그러니까 내 탓이라는 거야? 내가 너무 빨리 생각한다는 이유로, 너랑 같이 경영하는 회사의 매각을 숨겨도 된다는 거야?"),
(MA, "Ce n'est pas ma boîte, ni la tienne. Ce sont quatre mille deux cents personnes. Sternfeld peut investir quatre-vingts millions. Nous, on a un seul produit, une réserve de quarante millions et beaucoup d'espoir. Tu ne t'es jamais demandé si ton plan tiendrait sans miracle ?",
     "이건 내 회사도, 네 회사도 아니야. 4,200명이야. Sternfeld는 8천만 유로를 투자할 수 있어. 우리한텐 제품 하나, 예비금 4천만 유로, 그리고 희망이 잔뜩 있을 뿐이야. 네 계획이 기적 없이도 버틸지 한 번도 의심해 본 적 없어?"),
(I, "Tous les jours ! C'est mon métier. Et toi, tu as serré la main de Josiane pour cinq ans. Tu étais prêt à lui en reprendre trois ?",
    "매일 해! 그게 내 일이야. 그리고 너, 조지안이랑 5년을 걸고 악수했잖아. 그중 3년을 도로 뺏을 생각이었어?"),
(MA, "Je n'étais prêt à rien ! J'hésitais. J'ai le droit d'hésiter, non ?", "아무것도 할 생각 없었어! 망설였을 뿐이야. 망설일 권리도 없어?"),
(I, "Pas avec deux millions dans la balance. Tu sais comment on appelle un CEO qui hésite en silence avec une prime pareille sur la table ?",
    "저울에 200만 유로가 올라가 있으면 안 되지. 그런 보너스를 테이블에 올려놓고 말없이 망설이는 CEO를 뭐라고 부르는지 알아?"),
(MA, "Ne dis pas ça. Tu me connais. Tu crois vraiment que c'est pour l'argent ?", "그런 말 하지 마. 너 나 알잖아. 정말 돈 때문이라고 생각해?"),
(I, "Je ne sais plus ce que je crois. C'est ça, le problème. À seize ans, j'ai trouvé une lettre de la banque dans un tiroir. Mon père savait depuis des mois, et il n'avait rien dit. Je me suis juré que personne ne me referait jamais ça.",
    "이젠 내가 뭘 믿는지 모르겠어. 그게 문제야. 열여섯 살 때 서랍에서 은행 편지를 발견했어. 아빠는 몇 달 전부터 알고 있었는데 아무 말도 안 했지. 그때 맹세했어. 다시는 아무도 나한테 그러지 못하게 하겠다고."),
(MA, "Je ne suis pas ton père, Inès.", "난 너희 아버지가 아니야, 이네스."),
(I, "Non. Lui, au moins, il se taisait parce qu'il avait peur pour nous. Toi, tu t'es tu parce que tu avais peur de moi.", "아니지. 아빠는 적어도 우리가 걱정돼서 입을 다물었어. 넌 내가 무서워서 입을 다문 거고."),
(MA, "... Oui. J'avais peur de cette conversation. Exactement celle-ci. Chez moi, quand on se disputait, à la fin, quelqu'un partait.",
     "...그래. 이 대화가 무서웠어. 바로 이 대화가. 우리 집에선 싸우고 나면 결국 누군가가 떠났거든."),
(I, "Et tu as cru qu'en te taisant, personne ne partirait ? Je regrette que tu ne m'aies pas fait confiance. Et je regrette encore plus de ne plus pouvoir te faire confiance, moi. Je ne peux pas être ta directrice financière le jour et me demander la nuit ce que tu me caches. Je rentre à Paris ce soir. On arrête, Mathieu.",
    "그래서 입 다물고 있으면 아무도 안 떠날 줄 알았어? 네가 나를 믿지 않았다는 게 유감이야. 그리고 이젠 내가 너를 믿을 수 없다는 게 더 유감이고. 낮엔 네 재무 책임자로 일하고, 밤엔 네가 나한테 뭘 숨기는지 궁금해할 순 없어. 오늘 밤 파리로 돌아갈게. 우리 그만하자, 마티외."),
(MA, "Inès, attends. Lundi, je dois donner une réponse à Aubry. Dis-moi au moins ce que tu ferais, toi.", "이네스, 기다려. 월요일에 오브리한테 답을 줘야 해. 적어도 너라면 어떻게 할지 말해 줘."),
(I, "Non. Pour une fois, c'est toi qui décides. Seul. C'est bien ce que tu voulais, non ?", "아니. 이번만큼은 네가 결정해. 혼자서. 그게 네가 원하던 거잖아, 아니야?"),

# ---------- 6. Clôture : Paris, sans réponse ----------
(None, "Samedi, 13 h. Oberkampf. Les volets sont à moitié fermés. Figaro est couché sur le pull que Mathieu a oublié. On sonne : c'est Sofia, avec deux sacs de courses.",
       "토요일 오후 1시. 오베르캉프. 덧창이 반쯤 닫혀 있다. 피가로는 마티외가 두고 간 스웨터 위에 누워 있다. 초인종이 울린다. 장바구니 두 개를 든 소피아다."),
(S, "Bon. J'ai des falafels, du chocolat noir à quatre-vingts pour cent et un mauvais film. Tu veux parler ou tu veux manger ?",
    "자. 팔라펠이랑 카카오 80% 다크 초콜릿이랑 형편없는 영화 하나 가져왔어. 얘기하고 싶어, 아니면 먹고 싶어?"),
(I, "Ni l'un ni l'autre. Comment tu as su ?", "둘 다 아니야. 어떻게 알았어?"),
(S, "Tu m'as envoyé un texto à minuit : « C'est fini. » Sans emoji. Chez toi, c'est un appel au secours.", "자정에 문자 보냈잖아. '끝났어.' 이모티콘도 없이. 너한텐 그게 구조 요청이야."),
(I, "Il a eu une offre pour vendre la boîte, avec deux millions pour lui. Il me l'a cachée six jours. Je l'ai appris par Baptiste.", "회사를 팔라는 제안을 받았어. 자기 몫으로 200만 유로가 걸린. 그걸 엿새 동안 숨겼어. 난 바티스트한테서 들었고."),
(S, "Par Baptiste ? Aïe. Ça, c'est le pire scénario du tableur. Il a accepté ?", "바티스트한테서? 아이고. 그건 엑셀 최악의 시나리오네. 그래서 수락했어?"),
(I, "Non. Il a hésité. Il dit qu'il voulait réfléchir sans moi. Que j'ai toujours la réponse avant qu'il ait fini sa question.", "아니. 망설였어. 나 없이 생각해 보고 싶었대. 자기가 질문을 끝내기도 전에 내가 늘 답을 갖고 있다나."),
(S, "Tu veux que je te dise qu'il est un monstre, ou tu veux que je te dise ce que je pense ?", "그 사람이 괴물이라고 말해 줄까, 아니면 내 생각을 말해 줄까?"),
(I, "... Ce que tu penses. Mais doucement.", "...네 생각. 그런데 살살."),
(S, "Il a eu tort de se taire, ça, c'est clair. Mais je t'ai vue en réunion, Inès. Quand tu as raison, tu ne laisses pas beaucoup de place aux autres pour avoir peur.",
    "입 다문 건 그 사람 잘못이야, 그건 분명해. 그런데 난 회의에서 널 봤어, 이네스. 네가 옳을 때, 넌 다른 사람들한테 두려워할 틈을 별로 안 줘."),
(I, "Donc je suis coupable de penser vite, c'est ça ?", "그러니까 내가 생각이 빠른 게 죄라는 거야?"),
(S, "Non. Tu es coupable d'être Inès Marchetti. Lui, il est coupable d'être un Alsacien qui a peur des disputes. Ça fait deux coupables, pas un traître.",
    "아니. 네 죄는 이네스 마르케티라는 거야. 그 사람 죄는 싸움을 무서워하는 알자스 사람이라는 거고. 그러니까 죄인이 둘이지, 배신자는 없어."),
(I, "Il devait me dire quelque chose à Paris, tu sais. Depuis Shenzhen. Je suis à Paris, Sofia. Et lui, il n'est pas là.", "그 사람, 파리에서 나한테 해 줄 말이 있었어. 선전 이후로. 난 지금 파리에 있어, 소피아. 그런데 그 사람은 여기 없어."),
(S, "Tu l'aimes ?", "그 사람 사랑해?"),
(I, "Ce n'est pas la question.", "그게 문제가 아니야."),
(S, "C'est la seule question que vous n'écrivez jamais au tableau, tous les deux.", "그게 너희 둘이 화이트보드에 절대 안 쓰는 유일한 질문이지."),
(None, "Le téléphone d'Inès vibre sur la table. Une photo : le tableau blanc du bureau de Mathieu, à Saint-Étienne. Trois questions, au marqueur vert. Sous les deux premières, des réponses. Sous la troisième, rien.",
       "탁자 위에서 이네스의 휴대폰이 진동한다. 사진 한 장. 생테티엔 마티외 사무실의 화이트보드. 초록 마커로 쓴 세 가지 질문. 앞의 두 질문 아래엔 답이 적혀 있다. 세 번째 아래엔 아무것도 없다."),
(S, "« Quel est le vrai problème ? Moi. » « Qui décide ? Moi, seul. » Et la troisième... Il te pose la question, Inès.", "'진짜 문제는 무엇인가? 나.' '누가 결정하는가? 나, 혼자서.' 그리고 세 번째는... 너한테 묻는 거야, 이네스."),
(I, "Je sais lire, Sofia.", "나도 읽을 줄 알아, 소피아."),
(S, "Tu ne réponds pas ?", "답 안 해?"),
(I, "Pas aujourd'hui. Pour une fois, Sofia, je n'ai pas la réponse.", "오늘은 안 해. 이번만큼은, 소피아, 나한테 답이 없어."),
(None, "Inès retourne le téléphone, écran contre la table. Figaro saute sur le canapé et se colle contre elle.", "이네스가 휴대폰을 화면이 탁자에 닿도록 뒤집어 놓는다. 피가로가 소파로 뛰어올라 그녀에게 몸을 붙인다."),
(None, "Le même soir, Saint-Étienne. Le siège est vide. Dans son bureau, Mathieu fait face au tableau blanc, le marqueur vert à la main.",
       "같은 날 저녁, 생테티엔. 본사는 텅 비어 있다. 사무실에서 마티외가 초록 마커를 손에 쥔 채 화이트보드를 마주하고 있다."),
(MA, "Que fait-on lundi ?", "월요일엔 뭘 하지?"),
(None, "Personne ne répond. Le téléphone reste muet. Le marqueur ne touche pas le tableau.", "아무도 대답하지 않는다. 전화기는 조용하다. 마커는 화이트보드에 닿지 않는다."),
]

VOCAB = [
("B2", "une valeur d'entreprise", "기업가치(EV)", "주식가치 + 순부채. « cinq cent vingt millions, dette comprise » → 주주 몫(valeur des fonds propres)은 520 − 310 = 2억 1천만."),
("B2", "une prime de cession", "매각 보너스", "회사가 팔릴 때 경영진에게 주는 성과 보상. 경영자의 이해충돌 문제가 생기므로 이사회에 신고해야 한다."),
("C1", "une data room", "데이터룸(실사 자료실)", "인수 후보가 실사(audit)를 위해 열람하는 자료 저장소. 프랑스어로 salle des données라고도 함."),
("B2", "la sortie (d'un fonds)", "(펀드의) 투자 회수, 엑시트", "Pour Arcane, c'est la sortie idéale. 사모펀드는 보통 수년 뒤 지분을 팔아 수익을 실현한다."),
("C1", "une offre indicative / une offre ferme", "구속력 없는 의향 제안 / 확정 제안", "indicative는 실사 결과에 따라 바뀔 수 있는 제안, ferme는 법적 구속력이 있는 제안."),
("B2", "dette comprise", "부채 포함", "charges comprises처럼 compris가 뒤에서 명사를 수식. ↔ hors dette."),
("B2", "vendre au plus bas", "바닥에서 팔다", "가치가 가장 낮을 때 판다는 뜻. ↔ vendre au plus haut. acheter au plus bas."),
("C1", "dans le dos de qn", "~ 몰래, ~의 등 뒤에서", "négocier dans le dos du conseil. agir dans le dos de qn = 뒤통수를 치다."),
("B2", "saisir le conseil / présenter au conseil", "이사회에 안건을 올리다", "saisir = (기관에) 회부하다. saisir la justice = 소송을 제기하다."),
("C1", "dénoncer un accord", "(협약을) 파기·해지 통보하다", "노동법 용어. dénoncer에는 '고발하다'라는 뜻도 있으니 문맥 주의."),
("B2", "informer et consulter le CSE", "CSE에 정보 제공·협의하다", "회사 구조에 영향을 주는 결정 전 거쳐야 하는 절차. la procédure d'information-consultation."),
("B2", "aller droit au but", "단도직입적으로 말하다", "Je vais droit au but. 협상·회의의 첫마디로 자주 씀."),
("B2", "dans la balance", "저울에 올라가 있는, 판단에 영향을 주는", "avec deux millions dans la balance. peser dans la balance = 결정에 영향을 주다."),
("B1", "Rien de spécial.", "별거 아니야.", "가장 흔한 얼버무림 표현. 이번 화에서는 거짓 아닌 거짓의 시작."),
("B2", "y voir plus clair", "상황이 더 분명해지다", "Je t'en parlerai quand j'y verrai plus clair. 결정을 미루는 전형적 표현."),
("B2", "reprocher qc à qn", "~을 이유로 ~을 비난하다·탓하다", "Je te reproche de m'avoir regardée dans les yeux... 명사 un reproche."),
("B2", "Ce n'est pas ce que je vous demande.", "제가 묻는 건 그게 아니에요.", "질문을 피하는 답변을 되받아칠 때. 회의·인터뷰에서 매우 유용."),
("B1", "être crevé(e)", "녹초가 되다", "구어. être épuisé(e)보다 훨씬 일상적. Je suis crevé."),
("B2", "une rumeur court", "소문이 돌다", "courir = (소문이) 퍼지다. Le bruit court que... 도 같은 뜻."),
("B2", "encaisser (un coup)", "(타격을) 견디다, 받아들이다", "원래는 '현금을 수령하다'. 구어로 '버티다'. On peut tout encaisser ici."),
("B2", "avoir la parole de qn / donner sa parole", "~의 약속을 받다 / 맹세하다", "Vous avez ma parole. tenir parole = 약속을 지키다."),
("B1", "un appel au secours", "구조 요청", "비유적으로 '도와 달라는 신호'. au secours ! = 살려 줘!"),
("B2", "On arrête.", "(우리) 그만하자.", "관계를 끝낼 때 쓰는 담담하고 직접적인 표현. rompre보다 구어적."),
("B1", "du chantage", "협박, 공갈", "faire du chantage à qn. 이번 화에선 농담으로 « du chantage au chat »."),
]

GRAM = [
("C1", "접속법 과거: 감정 표현 + 이미 일어난 일",
 "« Je regrette que tu ne m'aies pas fait confiance. » « Ce qui me fait mal, c'est que Mathieu, lui, ne me l'ait pas dit. » 감정(regretter, être triste, avoir mal...) 뒤의 que절이 주절보다 앞선 사건을 가리키면 접속법 과거(avoir/être의 접속법 + 과거분사)를 쓴다. 주어가 같으면 de + 부정사 과거: « Je regrette encore plus de ne plus pouvoir te faire confiance »(현재), je regrette d'avoir dit ça(과거)."),
("B2", "avant que + 접속법 (과거 포함)",
 "« avant que tu aies la réponse » « tu as toujours la réponse avant que j'aie fini ma question » « juste avant que le redressement apparaisse dans les comptes » avant que는 늘 접속법. '내가 질문을 끝마치기 전'처럼 완료된 동작을 강조하면 접속법 과거(j'aie fini)를 쓴다. 주어가 같으면 avant de + 부정사."),
("B2", "조건법 과거: 후회와 비난",
 "« Je n'aurais pas dû l'accepter. »(후회) « À sa place, moi aussi, je serais discret. »(조건법 현재, 가정) 과거에 하지 않은 일을 탓할 때 tu aurais dû + 부정사(~했어야 했다), 내가 했어야 할 일을 후회할 때 je n'aurais pas dû + 부정사. 오브리의 « je vous avais demandé de la discrétion, pas le silence »는 대과거로 '그전에 이미 요청했다'는 시간 순서를 표시한다."),
("B2", "비난·변명의 표현 구조",
 "비난: « Je te reproche de m'avoir regardée dans les yeux... » reprocher à qn de + 부정사 과거. « Ça fait quoi, de l'apprendre par quelqu'un d'autre ? »(되갚는 반문). 변명: « Je ne t'ai pas menti ! Je n'avais rien décidé. » « J'ai le droit d'hésiter, non ? » 반박: « Donc c'est ma faute ? » 부정문 + 대과거(je n'avais rien décidé)는 '그 시점에 이미'라는 변명의 논리를 만든다."),
("B2", "vous → tu: 격식에서 감정으로",
 "« Monsieur Kessler, puisque nous sommes entre dirigeants... » « Depuis samedi, madame Marchetti. » 마르틴이 나가 문이 닫히는 순간 « Non. Maintenant, c'est toi qui vas m'écouter. »로 바뀐다. 2부 내내 회의 중 vous는 관계를 숨기는 장치였지만, 이 장면에서는 거리를 두는 무기가 된다. 같은 사람에게 쓰는 vous도 '공적 존중'과 '차가운 거리' 두 가지 의미를 가질 수 있다."),
("B2", "강조 구문 c'est... qui / ce qui... c'est",
 "« Maintenant, c'est toi qui vas m'écouter. » « Pour une fois, c'est toi qui décides. » « Ce qui me fait mal, c'est que... » c'est toi qui 뒤의 동사는 toi에 일치(c'est toi qui décides). ce qui... c'est que 뒤에는 감정의 내용이므로 접속법이 오기도 한다(ne me l'ait pas dit)."),
("B2", "ne... ni... ni / ni l'un ni l'autre",
 "« Elle n'a été ni acceptée ni présentée au conseil d'administration. » « Aujourd'hui, ni l'un ni l'autre n'a été fait. » « Ni l'un ni l'autre. » « Ce n'est pas ma boîte, ni la tienne. » 두 가지를 모두 부정할 때 ne... ni... ni를 쓴다. 주어로 쓰인 ni l'un ni l'autre는 단수·복수 동사 모두 가능하다. 단독 대답으로도 자주 쓰인다."),
("C1", "중립 대명사 en과 y의 관용적 용법",
 "« Je t'en parlerai quand j'y verrai plus clair. » « Profites-en. » « Je voulais savoir ce que j'en pensais, moi. » en은 de + 내용(parler de, penser de, profiter de)을, y는 상황 전체를 막연히 가리킨다(y voir clair). 명령형에서는 profite → profites-en처럼 -s가 되살아난다(발음 연음)."),
]

CULTURE = [
("기업 매각과 CSE의 정보 제공·협의 절차",
 "프랑스에서는 직원 50명 이상 기업의 경우, 회사의 경제·법적 조직에 영향을 주는 계획(매각, 인수합병 등)에 대해 경영진이 결정을 내리기 전에 사회경제위원회(CSE)에 정보를 제공하고 의견을 들어야 한다(information-consultation). CSE의 의견은 구속력이 없지만, 이 절차를 건너뛰면 노동법 위반(délit d'entrave)이 될 수 있다. 또 회사가 매각되어도 단체협약과 근로계약은 원칙적으로 새 사용자에게 승계되지만, 새 사용자는 일정 절차를 거쳐 기존 협약을 파기·재협상할 수 있다. 조지안이 '사후가 아니라 사전에'를 강조하는 이유다."),
("사모펀드의 엑시트와 경영진 인센티브",
 "사모펀드(fonds de capital-investissement)는 보통 기업 지분을 4~7년 정도 보유한 뒤 산업 기업(acquéreur industriel)이나 다른 펀드에 팔아 수익을 실현한다. 이때 경영진이 매각에 협조하도록 보너스나 지분 형태의 보상(management package)을 주는 일이 흔한데, 경영진이 회사와 다른 주주의 이익보다 자신의 보상을 우선할 위험이 있어 이사회에 투명하게 공개하는 것이 좋은 지배구조의 기본이다. 가족 주주와 펀드가 공동으로 소유한 비상장 기업에서는 매각 여부를 두고 이해관계가 크게 엇갈리기 쉽다."),
("tu와 vous, 감정의 온도계",
 "프랑스어에서 vous는 존중과 격식의 표시이지만, 이미 tu를 쓰던 사이에서 갑자기 vous로 돌아가는 것은 분명한 거리 두기, 때로는 분노의 신호다. 반대로 언쟁 중 vous를 고수하던 사람이 tu로 미끄러지면 공적인 가면이 벗겨졌다는 뜻이 된다. 프랑스 영화와 소설에서는 이 전환이 관계의 변화를 보여 주는 장치로 자주 쓰이며, 직장에서는 사적인 관계를 감추기 위해 공개 석상에서만 vous를 쓰는 커플도 드물지 않다."),
]
