# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H = "Inès", "Mathieu", "Hélène"
AR, NA, TH, VI = "Arnaud", "Nadia", "Thomas", "Vial"

META = {
    "part": 1, "ep": 3,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "Pénurie de puces",
    "title_ko": "반도체 부족",
    "place": "파리 리옹역 · 리옹행 TGV · Vasseur & Associés · 리옹 베니시외 로다니스 본사·공장 · 비외리옹 생장 거리 부숑 / 10월 말~11월 중순",
    "chars": "이네스, 마티외, 엘렌(전화), 필리프 아르노(로다니스 대표), 나디아 페랑(생산 책임자), 토마 그랑주(설계 엔지니어), 세르주 비알(구매 이사)",
    "work": "자동차 전자 모듈 업체 로다니스 에키프망 — 대만 단일 공급처 반도체 의존, 재고 5일, 공장 주 3일 가동 중단, 독일 완성차 브레너의 일 15만 유로 위약금 위협",
    "life": "리옹행 TGV 마주 보는 4인석의 브레첼과 커피, 서로의 가족 이야기, 리옹 부숑 저녁, 막차 TGV에서 마티외 어깨에 기대 잠든 이네스",
    "focus": "기차 어휘, 원인·결과 연결어(à cause de, grâce à, en raison de, donc, c'est pourquoi, si bien que, puisque), 일정·기한 표현(d'ici, au plus tard, dès, à partir de), si + 대과거 → 조건법 과거, 수동태 맛보기",
    "levelmix": "B1 45% · B2 50% · C1 5%",
    "next": "제4화 Zéro gaspillage — 새 팀원 소피아의 합류, 그리고 매일 멀쩡한 음식을 버리는 슈퍼마켓 체인.",
}

D = [
# ---------- 1. Ouverture : le TGV ----------
(None, "Un lundi de fin octobre, 7 h 20. Gare de Lyon, à Paris. Sous le grand tableau des départs, Mathieu cherche Inès du regard, un sac en papier à la main.",
       "10월 말의 어느 월요일 오전 7시 20분. 파리 리옹역. 커다란 출발 안내판 아래에서 마티외가 종이봉투를 손에 들고 이네스를 찾는다."),
(I, "Strasbourg ! Par ici ! Voie K, voiture 14. Et j'ai pris les cafés.", "스트라스부르! 여기야! K 승강장, 14호차. 커피도 샀어."),
(MA, "Tu as acheté les cafés ? Alors ma dette est annulée ?", "네가 커피를 샀다고? 그럼 내 빚은 없어진 거야?"),
(I, "Pas du tout. Un café que je paie moi-même ne compte pas. Ta dette, elle, court toujours.", "전혀. 내 돈으로 산 커피는 안 쳐. 네 빚은 여전히 유효해."),
(MA, "Je m'en doutais. Moi, j'ai apporté des bretzels, d'une boulangerie alsacienne près de la gare de l'Est. Des vrais, avec du gros sel.",
     "그럴 줄 알았어. 난 동역 근처 알자스 빵집에서 브레첼을 사 왔어. 굵은소금 뿌린 진짜배기로."),
(None, "Dans la voiture 14. Inès a réservé un carré : quatre places face à face, autour d'une table.", "14호차 안. 이네스는 테이블을 사이에 두고 네 자리가 마주 보는 4인석을 예약해 두었다."),
(MA, "Un carré, avec une table ! Je comprends pourquoi tu voulais choisir les places.", "테이블 있는 4인석이라니! 왜 네가 자리를 고르고 싶어 했는지 알겠다."),
(I, "Deux heures de train, c'est deux heures de travail. On étale les dossiers, et personne ne nous dérange. ... Mmm, il est bon, ton bretzel.",
    "기차 두 시간이면 일 두 시간이야. 서류를 펼쳐 놓으면 아무도 방해 안 해. ...음, 네 브레첼 맛있다."),
(MA, "C'est la recette de chez nous. Ma grand-mère en fait tous les dimanches, à Colmar. Elle a quatre-vingt-deux ans et elle pétrit encore la pâte à la main.",
     "우리 고향 레시피야. 할머니가 콜마르에서 일요일마다 만드셔. 여든두 살인데 아직도 손으로 반죽을 치대셔."),
(I, "Mamie Odile, c'est ça ? Tu l'appelles souvent, je t'entends au bureau. « Oui Mamie, je mange bien, Mamie. »", "오딜 할머니 맞지? 자주 통화하잖아. 사무실에서 다 들려. '네 할머니, 잘 먹고 있어요, 할머니.'"),
(MA, "Tu m'espionnes ? Elle s'inquiète, c'est tout. Pour elle, Paris est une ville dangereuse où personne ne mange de légumes.", "나 감시하는 거야? 걱정하시는 것뿐이야. 할머니한테 파리는 아무도 채소를 안 먹는 위험한 도시거든."),
(I, "Elle n'a pas complètement tort. Ma mère pense la même chose de toute la France au nord d'Avignon.", "완전히 틀린 말은 아니네. 우리 엄마는 아비뇽 북쪽 프랑스 전체를 그렇게 생각하셔."),
(MA, "Et ton père ? Le fan de Mozart ?", "아버지는? 모차르트 팬이시라던?"),
(I, "Lui, il m'appelle le dimanche, avec Les Noces de Figaro à fond derrière. Il croit que je ne remarque pas qu'il chante en même temps.",
    "아빠는 일요일마다 전화하시는데, 뒤에서 「피가로의 결혼」을 크게 틀어 놓으셔. 같이 따라 부르는 걸 내가 모르는 줄 아셔."),
(MA, "C'est donc pour ça que ton chat s'appelle Figaro... Et toi, tu chantes aussi ?", "그래서 네 고양이 이름이 피가로구나... 너도 노래해?"),
(I, "Jamais devant témoin. Bon, assez parlé de nos familles : sors ton ordinateur. On arrive à Lyon dans deux heures, et je veux qu'on connaisse le dossier par cœur.",
    "증인 앞에선 절대 안 해. 자, 가족 얘기는 그만. 노트북 꺼내. 두 시간 뒤면 리옹이고, 그 전에 사건 자료를 줄줄 외워야 해."),
(None, "Annonce : « Mesdames et messieurs, en raison d'un incident technique, notre train circulera avec un retard d'environ trente minutes. »",
       "안내 방송: '승객 여러분, 기술적 문제로 인해 본 열차는 약 30분 지연 운행하겠습니다.'"),
(MA, "En raison d'un incident technique... Ça commence bien. Même les trains manquent de pièces, aujourd'hui.", "기술적 문제로 인해라... 시작 좋네. 오늘은 기차까지 부품이 모자라나 봐."),

# ---------- 2. Briefing et client ----------
(H, "(au téléphone) Inès ? Mets le haut-parleur pour Mathieu. Bon : Rhodanis Équipements, à Vénissieux. Mille cent salariés, des modules électroniques pour les sièges et les phares de voitures.",
    "(전화로) 이네스? 마티외도 듣게 스피커폰으로 해. 자, 베니시외의 로다니스 에키프망. 직원 1,100명, 자동차 좌석과 헤드라이트용 전자 모듈을 만들어."),
(I, "On a lu le dossier, Hélène. Leur usine s'arrête trois jours par semaine à cause de la pénurie de puces, c'est bien ça ?", "자료 읽었어요, 엘렌. 반도체 부족 때문에 공장이 일주일에 사흘씩 멈춘다는 거죠?"),
(H, "Depuis cinq semaines. Et leur plus gros client, le constructeur allemand Brenner, menace de leur facturer des pénalités de retard : cent cinquante mille euros par jour.",
    "5주째야. 그리고 최대 고객인 독일 완성차 업체 브레너가 지연 위약금을 물리겠다고 위협하고 있어. 하루 15만 유로."),
(MA, "Par jour ? Mais ça peut tuer une entreprise de cette taille en quelques mois.", "하루에요? 그 정도 규모 회사면 몇 달 만에 망할 수도 있겠는데요."),
(H, "C'est pourquoi Philippe Arnaud, le PDG, nous a appelés vendredi soir. Il veut un plan d'action dans trois semaines au plus tard. Bonne chance, et rapportez-moi des pralines roses.",
    "그래서 대표 필리프 아르노가 금요일 저녁에 우리한테 전화한 거야. 늦어도 3주 안에 실행 계획을 원해. 행운을 빌어. 그리고 분홍 프랄린 사 와."),
(None, "10 h 30. Vénissieux, dans la banlieue sud-est de Lyon. Le siège de Rhodanis est un bâtiment de verre à côté de l'usine. Philippe Arnaud, la cinquantaine, les reçoit avec Nadia Ferrand, directrice de la production.",
       "오전 10시 30분. 리옹 남동부 교외 베니시외. 로다니스 본사는 공장 옆 유리 건물이다. 50대의 필리프 아르노가 생산 책임자 나디아 페랑과 함께 두 사람을 맞는다."),
(AR, "Bienvenue à Vénissieux. Désolé, l'ambiance n'est pas à la fête. Aujourd'hui, c'est un jour d'arrêt : les lignes ne tournent pas.", "베니시외에 오신 걸 환영합니다. 분위기가 밝지 않아 죄송해요. 오늘은 가동 중단일이라 라인이 돌지 않습니다."),
(I, "Bonjour monsieur Arnaud, bonjour madame Ferrand. Merci de nous recevoir malgré la situation. Pouvez-vous nous expliquer comment vous en êtes arrivés là ?",
    "안녕하세요, 아르노 대표님, 페랑 이사님. 이런 상황에서도 맞아 주셔서 감사합니다. 어쩌다 여기까지 오게 됐는지 설명해 주시겠어요?"),
(AR, "Tout dépend d'une seule puce, un microcontrôleur, qu'on appelle chez nous la MC-40. Il y en a une dans chacun de nos modules. Sans elle, le module ne sert à rien.",
     "모든 게 칩 하나에 달려 있어요. 마이크로컨트롤러인데, 우리끼리는 MC-40이라고 부르죠. 모듈마다 하나씩 들어갑니다. 그게 없으면 모듈은 쓸모가 없어요."),
(MA, "Et vous l'achetez où, cette puce ?", "그 칩은 어디서 사세요?"),
(NA, "Chez un seul fournisseur, à Taïwan. Pendant dix ans, il nous a livrés toutes les semaines, sans jamais un problème.", "대만의 공급업체 한 곳에서요. 10년 동안 매주 납품했고, 문제가 한 번도 없었어요."),
(I, "Qu'est-ce qui a changé ?", "무엇이 바뀌었나요?"),
(NA, "La demande mondiale a explosé, et il a donné la priorité à des clients plus gros que nous. Le délai de livraison est passé de douze semaines à presque un an.",
     "전 세계 수요가 폭발했고, 그 업체는 우리보다 큰 고객들을 우선했어요. 납기가 12주에서 거의 1년으로 늘었죠."),
(MA, "Presque un an ! Et combien de puces vous faut-il par jour ?", "거의 1년이요! 하루에 칩이 몇 개나 필요하세요?"),
(NA, "Douze mille, une par module. Avant la crise, nous avions cinq jours de stock. C'est notre règle : le juste-à-temps, le moins de stock possible.",
     "1만 2천 개요. 모듈 하나에 하나씩. 위기 전엔 재고가 5일 치였어요. 그게 우리 원칙이에요. 저스트인타임, 재고는 최소한으로."),
(I, "Cinq jours... Donc au premier retard de livraison, la ligne s'arrête.", "5일이라... 그러니까 납품이 한 번만 늦어도 라인이 멈추는 거네요."),
(NA, "Exactement. Maintenant, on reçoit des livraisons partielles, au compte-gouttes, si bien qu'on produit deux jours et qu'on s'arrête trois.",
     "맞아요. 지금은 찔끔찔끔 부분 납품을 받아요. 그래서 이틀 생산하고 사흘 멈추는 거죠."),
(MA, "Et vos ouvriers, pendant les jours d'arrêt ?", "가동 중단일에 작업자분들은요?"),
(NA, "Ils sont au chômage partiel. Ils sont inquiets, et je les comprends. Certains travaillent ici depuis vingt-cinq ans.", "부분 실업 상태예요. 다들 불안해하고, 저도 이해해요. 여기서 25년째 일하는 사람들도 있거든요."),
(I, "Combien vous coûte une journée d'arrêt, monsieur Arnaud ?", "가동 중단 하루에 비용이 얼마나 드나요, 대표님?"),
(AR, "Environ quatre cent mille euros de marge perdue. Et si Brenner applique ses pénalités, il faudra ajouter cent cinquante mille euros par jour de retard.",
     "놓치는 마진이 40만 유로쯤 됩니다. 브레너가 위약금을 적용하면 지연 하루마다 15만 유로를 더해야 하고요."),
(MA, "Brenner représente quelle part de votre chiffre d'affaires ?", "브레너가 매출에서 차지하는 비중은요?"),
(AR, "Quarante-cinq pour cent, sur trois cent dix millions d'euros. Si on les perd, on ferme. C'est aussi simple que ça.", "3억 1천만 유로 중 45%요. 그들을 잃으면 문 닫습니다. 그만큼 단순해요."),
(I, "À partir de quand les pénalités s'appliqueront-elles ?", "위약금은 언제부터 적용되나요?"),
(AR, "Leur directeur des achats m'a donné jusqu'au quinze décembre. Si nos livraisons ne sont pas revenues à la normale d'ici là, ils appliquent le contrat.",
     "그쪽 구매 이사가 12월 15일까지 시간을 줬어요. 그때까지 납품이 정상으로 돌아오지 않으면 계약대로 하겠답니다."),
(MA, "Ça nous laisse un peu moins de deux mois. Avez-vous cherché d'autres fournisseurs ?", "두 달이 좀 안 남았네요. 다른 공급업체는 알아보셨나요?"),
(AR, "Mon directeur des achats, Serge Vial, dit qu'il n'existe pas d'alternative au même prix. Et changer de puce dans l'automobile, ce sont des mois de tests.",
     "우리 구매 이사 세르주 비알 말로는 같은 가격의 대안이 없답니다. 게다가 자동차 업계에서 칩을 바꾸려면 몇 달씩 시험을 거쳐야 하고요."),
(I, "Au même prix... D'accord. Nous aurons besoin de vos données d'achats, de stocks et de production sur deux ans.", "같은 가격이라... 알겠습니다. 2년 치 구매·재고·생산 데이터가 필요합니다."),
(NA, "Je vous les envoie ce soir. Et venez voir l'usine jeudi, quand les lignes tourneront. On ne comprend rien à une usine à l'arrêt.", "오늘 저녁에 보내 드릴게요. 그리고 라인이 도는 목요일에 공장을 보러 오세요. 멈춘 공장으론 아무것도 알 수 없어요."),
(MA, "Avec plaisir. Jeudi, à quelle heure ?", "좋습니다. 목요일 몇 시에요?"),
(NA, "L'équipe du matin commence à cinq heures. Mais je ne suis pas sadique : venez à huit heures.", "오전조는 5시에 시작해요. 하지만 제가 그렇게 가혹하진 않으니 8시에 오세요."),

# ---------- 3. Analyse ----------
(None, "Mercredi, 20 h. Vasseur & Associés, salle « Monceau ». Mathieu dessine un schéma au marqueur vert ; Inès a trois tableurs ouverts.",
       "수요일 저녁 8시. 바쇠르 & 어소시에이츠, '몽소' 회의실. 마티외는 초록 마커로 도식을 그리고, 이네스는 스프레드시트 세 개를 열어 두었다."),
(I, "Bon, j'ai les chiffres de Nadia. Premier constat : un seul fournisseur pour une puce dont dépend cent pour cent de leur production.", "자, 나디아가 보낸 숫자 받았어. 첫 번째 결론: 생산의 100%가 달린 칩을 공급업체 한 곳에만 의존해."),
(MA, "Le fameux « single sourcing ». Tant que tout va bien, c'est moins cher. Le jour où ça casse, tout casse.", "그 유명한 '단일 소싱'이네. 다 잘 굴러갈 땐 더 싸지. 한번 끊기면 전부 끊기고."),
(I, "Et à cause du juste-à-temps, ils n'avaient aucune réserve. Cinq jours de stock, c'est un parachute en papier.", "그리고 저스트인타임 때문에 비축분이 하나도 없었어. 재고 5일이면 종이 낙하산이야."),
(MA, "Alors, ta solution ?", "그래서, 네 해법은?"),
(I, "Un stock de sécurité : trois mois de puces critiques. J'ai fait le calcul. Trois mois de production, c'est à peu près sept cent vingt mille puces.",
    "안전재고. 핵심 칩 3개월 치. 계산해 봤어. 3개월 생산분이면 대략 72만 개야."),
(MA, "À quatre euros la puce... presque trois millions d'euros immobilisés. Arnaud va s'étrangler.", "칩 하나에 4유로면... 300만 유로 가까이 묶이는 거네. 아르노 숨넘어가겠다."),
(I, "Attends la suite. Le stock, il faut le financer et le stocker : ça coûte environ dix pour cent par an. Donc trois cent mille euros par an.",
    "끝까지 들어 봐. 재고는 자금도 대야 하고 보관도 해야 해. 1년에 10% 정도 들지. 그러니까 연 30만 유로."),
(MA, "Trois cent mille euros...", "30만 유로라..."),
(I, "Soit deux jours de pénalités Brenner. Deux jours ! Et ils viennent de perdre quinze jours de production en cinq semaines. À quatre cent mille euros la journée, ça fait six millions.",
    "브레너 위약금 이틀 치야. 겨우 이틀! 그런데 그 회사는 5주 동안 생산일 15일을 날렸어. 하루 40만 유로면 600만 유로야."),
(MA, "D'accord, tes chiffres sont convaincants. Mais il y a un problème : où vont-ils trouver sept cent vingt mille puces aujourd'hui ? Personne n'en a.",
     "좋아, 네 숫자는 설득력 있어. 그런데 문제가 하나 있어. 지금 72만 개를 어디서 구해? 아무도 없는데."),
(I, "... Il faut les commander maintenant, pour l'année prochaine.", "...지금 주문해야지, 내년 걸로."),
(MA, "Pour l'année prochaine. Mais la crise, c'est maintenant. Ton stock les protège de la prochaine pénurie, pas de celle-ci.", "내년 거. 하지만 위기는 지금이야. 네 재고는 다음 부족 사태는 막아 줘도 이번 건 못 막아."),
(I, "Et toi, tu proposes quoi ? Tu vas fabriquer des puces dans ta cuisine à deux plaques ?", "그럼 넌 뭘 제안하는데? 화구 두 개짜리 네 부엌에서 칩이라도 만들 거야?"),
(MA, "Presque. Je propose de regarder du côté de la conception. Est-ce qu'une autre puce pourrait faire le même travail ? Une puce européenne, par exemple ?",
     "비슷해. 설계 쪽을 보자는 거야. 다른 칩이 같은 일을 할 수 있지 않을까? 예를 들어 유럽산 칩이라든가?"),
(I, "Arnaud l'a dit : changer de puce dans l'automobile, ce sont des mois de tests. Le constructeur doit tout valider.", "아르노가 말했잖아. 자동차 업계에서 칩을 바꾸려면 몇 달씩 시험해야 한다고. 완성차 업체가 다 승인해야 해."),
(MA, "Des mois, oui. C'est pourquoi il aurait fallu commencer hier. Mais si on ne commence jamais, ils dépendront de Taïwan pour toujours.",
     "몇 달 걸리지. 그러니까 어제 시작했어야 했던 거고. 하지만 영영 시작 안 하면 평생 대만에 매달리게 돼."),
(I, "Tu raisonnes comme un ingénieur. Moi, je raisonne avec une date : le quinze décembre. Ta puce européenne, elle sera prête en juin, peut-être.",
    "넌 엔지니어처럼 생각해. 난 날짜로 생각해. 12월 15일. 네 유럽산 칩은 잘해야 6월에나 준비될 거야."),
(MA, "Et ton stock, il ne sera jamais prêt, puisqu'il n'y a pas de puces à acheter !", "네 재고는 영영 준비 안 될 거고! 살 칩이 없으니까!"),
(None, "Un silence. Inès pose son stylo.", "침묵. 이네스가 펜을 내려놓는다."),
(I, "... Tu as haussé le ton, Strasbourg. C'est la première fois.", "...언성 높였네, 스트라스부르. 처음이야."),
(MA, "Pardon. Je déteste les conflits, et pourtant je viens d'en créer un.", "미안. 난 갈등이 정말 싫은데, 방금 내가 하나 만들었네."),
(I, "Ce n'est pas un conflit, c'est un débat. Et franchement, tu n'as pas tort : mon stock ne règle pas l'urgence.", "갈등이 아니라 토론이야. 그리고 솔직히 네 말이 틀리진 않아. 내 재고로는 급한 불을 못 꺼."),
(MA, "Et ma puce non plus, si elle n'existe que dans ma tête. Donc on a deux moitiés de solution.", "내 칩도 마찬가지지, 머릿속에만 있다면. 그러니까 우린 해법을 반쪽씩 가진 거야."),
(I, "Deux moitiés qui font une solution, à condition qu'une alternative existe déjà quelque part. Tu as remarqué quelque chose dans les données d'achats ?",
    "어딘가에 대안이 이미 있다면 반쪽 두 개가 하나의 해법이 되지. 구매 데이터에서 뭐 눈치챈 거 없어?"),
(MA, "Quoi donc ?", "뭔데?"),
(I, "Il y a un an, ils ont commandé cinq cents puces à un fabricant de Dresde, Elbtron. Une seule commande. Et puis plus rien.", "1년 전에 드레스덴의 엘브트론이라는 제조사에 칩 500개를 주문했어. 딱 한 번. 그 뒤론 아무것도 없어."),
(MA, "Cinq cents puces... C'est exactement la quantité qu'on commande pour faire des tests !", "500개라... 딱 시험용으로 주문하는 양이잖아!"),
(I, "Donc quelqu'un, chez Rhodanis, a testé une alternative. Et quelqu'un d'autre a tout arrêté.", "그러니까 로다니스의 누군가가 대안을 시험했다는 거지. 그리고 다른 누군가가 전부 멈췄고."),
(MA, "Voilà notre vraie question. Pas « combien de stock ? », mais « pourquoi ont-ils arrêté ? »", "그게 우리의 진짜 질문이야. '재고를 얼마나?'가 아니라 '왜 멈췄나?'"),
(I, "Jeudi, on va le découvrir. Tu interroges les ingénieurs, moi je m'occupe des achats.", "목요일에 알아내자. 넌 엔지니어들한테 묻고, 난 구매팀을 맡을게."),
(MA, "Marché conclu. Et pardon encore pour tout à l'heure.", "좋아, 그렇게 하자. 그리고 아까 일은 다시 한번 미안해."),

# ---------- 4. Terrain : l'usine ----------
(None, "Jeudi, 8 h. L'usine de Vénissieux. Bruit des machines, odeur de soudure. Aujourd'hui, les lignes tournent.",
       "목요일 오전 8시. 베니시외 공장. 기계 소리, 납땜 냄새. 오늘은 라인이 돌아간다."),
(NA, "Voici la ligne trois, celle des modules de phares. Chaque carte électronique passe par la pose des composants, la soudure, puis les tests.",
     "여기가 3번 라인, 헤드라이트 모듈 라인이에요. 전자 기판마다 부품 장착, 납땜, 그다음 테스트를 거쳐요."),
(MA, "Et la MC-40, elle est posée à quel moment ?", "MC-40은 언제 장착되나요?"),
(NA, "Tout au début. Regardez ce bac : c'est tout notre stock de MC-40. De quoi travailler jusqu'à demain midi.", "맨 처음에요. 이 통 좀 보세요. 이게 MC-40 재고 전부예요. 내일 정오까지 작업할 분량이죠."),
(I, "Jusqu'à demain midi... Et ensuite ?", "내일 정오까지라... 그다음엔요?"),
(NA, "Ensuite, on attend le camion. S'il arrive lundi, on redémarre lundi. Sinon, on renvoie tout le monde à la maison.", "그다음엔 트럭을 기다리죠. 월요일에 오면 월요일에 재가동하고, 안 오면 모두 집으로 돌려보내요."),
(MA, "Madame Ferrand, il y a un an, Rhodanis a commandé cinq cents puces chez Elbtron, à Dresde. Vous savez pourquoi ?", "페랑 이사님, 1년 전에 로다니스가 드레스덴의 엘브트론에서 칩 500개를 주문했어요. 이유를 아세요?"),
(NA, "Elbtron ? ... Ah oui. C'était un projet de l'équipe d'ingénierie. Allez voir Thomas Grange, au bureau d'études. Il vous expliquera mieux que moi.",
     "엘브트론이요? ...아, 네. 엔지니어링 팀 프로젝트였어요. 설계실의 토마 그랑주를 찾아가 보세요. 저보다 잘 설명해 줄 거예요."),
(None, "Le bureau d'études, au premier étage. Des cartes électroniques sur toutes les tables. Thomas Grange, la trentaine, lève la tête de son écran.",
       "2층의 설계실. 책상마다 전자 기판이 놓여 있다. 30대의 토마 그랑주가 모니터에서 고개를 든다."),
(TH, "Elbtron ? Vous avez retrouvé ça ? C'était mon projet. Mon projet mort, plutôt.", "엘브트론이요? 그걸 찾아내셨어요? 제 프로젝트였어요. 아니, 죽은 프로젝트죠."),
(MA, "Racontez-nous. Pourquoi avez-vous testé une autre puce ?", "얘기해 주세요. 왜 다른 칩을 시험하셨죠?"),
(TH, "Parce que je trouvais dangereux de dépendre d'un seul fournisseur à l'autre bout du monde. Alors on a adapté la carte pour qu'elle accepte la puce d'Elbtron. Six mois de travail.",
     "지구 반대편 공급업체 한 곳에 의존하는 게 위험하다고 생각했거든요. 그래서 엘브트론 칩이 들어가도록 기판을 고쳤어요. 6개월 걸렸죠."),
(I, "Et les tests ?", "시험 결과는요?"),
(TH, "Tous réussis. Température, vibrations, durée de vie... Et Brenner a validé la nouvelle version. Le dossier est complet. Tout est prêt.",
     "전부 통과했어요. 온도, 진동, 수명... 그리고 브레너가 새 버전을 승인했어요. 서류도 다 갖춰져 있어요. 모든 게 준비돼 있죠."),
(MA, "Attendez. Vous voulez dire qu'une puce de remplacement, validée par le client, existe depuis un an ?", "잠깐만요. 고객이 승인한 대체 칩이 1년 전부터 있었다는 말씀이세요?"),
(TH, "Depuis un an pile. Elle dort dans ce tiroir.", "딱 1년 됐어요. 이 서랍 속에서 잠자고 있죠."),
(I, "Alors pourquoi ne l'utilisez-vous pas ?", "그럼 왜 안 쓰시는 거죠?"),
(TH, "Parce que les achats ont refusé. La puce d'Elbtron coûte quatre euros trente-deux au lieu de quatre euros. Huit pour cent plus cher. Serge Vial a dit non.",
     "구매팀이 거부했으니까요. 엘브트론 칩은 4유로가 아니라 4유로 32센트예요. 8% 더 비싸죠. 세르주 비알이 안 된다고 했어요."),
(None, "Dix minutes plus tard, dans le bureau de Serge Vial, directeur des achats.", "10분 뒤, 구매 이사 세르주 비알의 사무실."),
(VI, "Oui, j'ai refusé. Et je referais la même chose. Mon objectif, c'est de baisser le prix unitaire des composants. C'est là-dessus que je suis évalué.",
     "네, 제가 거부했어요. 다시 그 상황이 와도 똑같이 할 겁니다. 제 목표는 부품 단가를 낮추는 거예요. 저는 그걸로 평가받습니다."),
(I, "Votre prime dépend du prix unitaire ?", "성과급이 단가에 달려 있나요?"),
(VI, "Comme celle de toute mon équipe. Si j'achète huit pour cent plus cher, je rate mon objectif. Personne ne m'a jamais demandé de payer pour une assurance.",
     "우리 팀 전원이 그래요. 8% 비싸게 사면 목표를 못 채워요. 보험료를 내라고 한 사람은 아무도 없었어요."),
(MA, "Mais aujourd'hui, l'usine s'arrête trois jours par semaine. Ça, ça n'apparaît pas dans vos objectifs ?", "하지만 지금 공장이 일주일에 사흘씩 멈춰요. 그건 목표에 안 나타나나요?"),
(VI, "Non. Les arrêts de production, c'est le budget de Nadia, pas le mien. ... Je sais ce que vous pensez. Mais ce sont les règles.", "안 나타나요. 생산 중단은 나디아 예산이지 제 예산이 아니에요. ...무슨 생각 하시는지 알아요. 하지만 그게 규칙이에요."),
(I, "Trente-deux centimes par puce... Pour économiser trente-deux centimes, ils ont perdu six millions.", "칩 하나에 32센트... 32센트 아끼려다 600만 유로를 날렸어."),
(MA, "Et ce n'est même pas la faute de Vial. Il fait exactement ce qu'on lui demande. Ce sont ses objectifs qui sont mal conçus.", "그것도 비알 탓이 아니야. 시키는 대로 정확히 하고 있을 뿐이지. 잘못 설계된 건 그의 목표야."),
(I, "Comme les primes chez Fauvel. Tu ne trouves pas que les entreprises se ressemblent toutes un peu ?", "포벨의 성과급처럼. 회사들이 다 조금씩 닮은 것 같지 않아?"),
(MA, "Toutes. On mesure une chose, et on s'étonne que les gens optimisent cette chose-là. Bon, on a notre histoire.", "전부 그래. 하나만 측정해 놓고, 사람들이 그것만 최적화한다고 놀라지. 자, 우리 스토리가 나왔다."),

# ---------- 5. Recommandations ----------
(None, "Deux semaines plus tard. Salle de réunion de Rhodanis. Philippe Arnaud, Nadia Ferrand, Serge Vial et Thomas Grange sont autour de la table.",
       "2주 뒤. 로다니스 회의실. 필리프 아르노, 나디아 페랑, 세르주 비알, 토마 그랑주가 테이블에 둘러앉아 있다."),
(AR, "Allez-y. Je vous préviens, je ne dors plus depuis une semaine. J'espère que vous avez de bonnes nouvelles.", "시작하시죠. 미리 말해 두는데, 일주일째 잠을 못 잤어요. 좋은 소식이길 바랍니다."),
(I, "Nous en avons, monsieur Arnaud. Et nous commencerons par la meilleure : la solution existe déjà chez vous, dans un tiroir du bureau d'études.",
    "있습니다, 대표님. 가장 좋은 소식부터 말씀드리죠. 해법은 이미 회사 안에, 설계실 서랍 속에 있습니다."),
(AR, "Dans un tiroir ? Qu'est-ce que ça veut dire ?", "서랍 속이요? 그게 무슨 뜻이죠?"),
(MA, "Il y a un an, l'équipe de Thomas Grange a adapté vos cartes à une puce européenne, celle d'Elbtron, à Dresde. Tous les tests ont été réussis, et Brenner l'a validée.",
     "1년 전에 토마 그랑주 팀이 기판을 드레스덴 엘브트론의 유럽산 칩에 맞게 고쳤습니다. 모든 시험을 통과했고 브레너도 승인했습니다."),
(AR, "Thomas ? C'est vrai ? Pourquoi est-ce que je ne le savais pas ?", "토마? 정말이야? 왜 난 몰랐지?"),
(TH, "Je l'ai écrit dans un rapport, monsieur Arnaud. Mais le projet a été arrêté avant d'arriver jusqu'à vous.", "보고서에 썼습니다, 대표님. 하지만 대표님께 올라가기 전에 프로젝트가 중단됐어요."),
(VI, "Arrêté par moi, je l'assume. La puce était huit pour cent plus chère. J'ai appliqué les objectifs qu'on m'avait fixés.", "제가 중단시켰고, 그 책임은 지겠습니다. 칩이 8% 더 비쌌어요. 저는 주어진 목표대로 했을 뿐입니다."),
(I, "Et c'est justement le cœur du problème. Monsieur Vial a fait son travail. Mais ses objectifs ne mesurent que le prix unitaire, jamais le coût d'une rupture.",
    "바로 그게 문제의 핵심입니다. 비알 이사님은 맡은 일을 하셨어요. 하지만 그 목표는 단가만 측정하고, 공급 차질의 비용은 전혀 측정하지 않습니다."),
(MA, "Pour économiser trente-deux centimes par puce, Rhodanis a déjà perdu plus de six millions d'euros depuis le début de la crise.", "칩 하나에 32센트를 아끼려다, 로다니스는 위기가 시작된 뒤 이미 600만 유로 넘게 잃었습니다."),
(AR, "Six millions... Bon. Qu'est-ce que vous proposez ?", "600만이라... 좋아요. 무엇을 제안하시죠?"),
(I, "Cinq mesures. La première, la plus urgente : le double sourcing. Nous avons appelé Elbtron. Ils peuvent livrer quatre mille puces par jour dès la mi-novembre, et sept mille à partir de début décembre.",
    "다섯 가지 조치입니다. 첫째, 가장 시급한 이중 소싱입니다. 엘브트론에 전화해 봤습니다. 11월 중순부터 하루 4천 개, 12월 초부터는 7천 개를 납품할 수 있답니다."),
(NA, "Sept mille, plus les livraisons de Taïwan... Ça nous ramène à cinq jours sur cinq !", "7천 개에 대만 납품분까지 더하면... 다시 주 5일 가동이에요!"),
(MA, "Avant le quinze décembre, oui. À long terme, nous recommandons de garder les deux fournisseurs : soixante pour cent pour Taïwan, quarante pour Elbtron. Le surcoût est d'environ trois cent cinquante mille euros par an.",
     "네, 12월 15일 전에요. 장기적으로는 두 공급업체를 모두 유지하길 권합니다. 대만 60%, 엘브트론 40%. 추가 비용은 연 35만 유로 정도입니다."),
(VI, "Trois cent cinquante mille euros ! Mon budget va exploser.", "35만 유로라니! 제 예산이 터지겠네요."),
(I, "Votre budget, oui. Celui de l'entreprise, non : c'est moins qu'une journée d'arrêt. Ce qui nous amène à la deuxième mesure : un stock stratégique de trois mois sur les puces critiques, constitué progressivement d'ici juin.",
    "이사님 예산은 그렇죠. 하지만 회사 예산은 아닙니다. 가동 중단 하루치보다 적으니까요. 그래서 두 번째 조치입니다. 핵심 칩 3개월 치 전략 재고를 내년 6월까지 단계적으로 쌓는 것입니다."),
(AR, "Trois mois de stock ? Nous avons toujours travaillé en juste-à-temps.", "재고 3개월 치요? 우린 늘 저스트인타임으로 해 왔는데요."),
(I, "Le juste-à-temps marche très bien... tant que rien ne manque. Ce stock immobilisera environ trois millions d'euros et coûtera trois cent mille euros par an. Soit deux jours de pénalités Brenner.",
    "저스트인타임은 아주 잘 돌아갑니다... 아무것도 모자라지 않는 동안은요. 이 재고에 300만 유로 정도가 묶이고, 연간 비용은 30만 유로입니다. 브레너 위약금 이틀 치죠."),
(AR, "Vu comme ça... Troisièmement ?", "그렇게 보면... 세 번째는요?"),
(MA, "Les objectifs des achats. Nous proposons d'évaluer l'équipe de monsieur Vial sur le coût total : le prix, mais aussi le stock, la fiabilité du fournisseur et le risque d'arrêt.",
     "구매 목표입니다. 비알 이사님 팀을 총비용으로 평가하자고 제안합니다. 가격뿐 아니라 재고, 공급업체의 신뢰도, 가동 중단 위험까지요."),
(VI, "Ça veut dire que je ne serai plus puni si j'achète plus cher pour être plus sûr ?", "그러니까 더 안전하려고 비싸게 사도 이제 불이익을 안 받는다는 건가요?"),
(MA, "Exactement. Vous serez récompensé si l'usine ne s'arrête pas.", "정확합니다. 공장이 멈추지 않으면 보상을 받으시게 됩니다."),
(VI, "... Si on m'avait fixé cet objectif-là il y a un an, j'aurais signé avec Elbtron le jour même.", "...1년 전에 그런 목표를 줬다면 그날 바로 엘브트론과 계약했을 겁니다."),
(I, "Quatrièmement : une cellule de crise « approvisionnement », chaque lundi à huit heures. Achats, production, bureau d'études, autour de la même table. Trente minutes, pas plus.",
    "넷째, 매주 월요일 8시에 '조달' 위기 대응반을 엽니다. 구매, 생산, 설계실이 한 테이블에 앉는 거죠. 30분, 그 이상은 안 합니다."),
(NA, "Enfin ! Aujourd'hui, j'apprends les retards de livraison quand le camion n'arrive pas.", "드디어! 지금은 트럭이 안 와야 납품 지연을 알게 되거든요."),
(MA, "Et cinquièmement, Brenner. Monsieur Arnaud, nous vous conseillons d'appeler leur directeur des achats cette semaine, avec un plan daté : premières puces Elbtron à la mi-novembre, retour à la normale début décembre, livraisons complètes avant le quinze.",
     "다섯째, 브레너입니다. 대표님, 이번 주에 그쪽 구매 이사에게 날짜가 박힌 계획을 들고 전화하시길 권합니다. 11월 중순 엘브트론 첫 칩 입고, 12월 초 정상화, 15일 전 완전 납품."),
(AR, "Et je lui demande de renoncer aux pénalités ?", "그리고 위약금을 포기해 달라고 하라고요?"),
(I, "Vous lui proposez un échange : un point hebdomadaire et une transparence totale sur vos stocks. En contrepartie, il suspend les pénalités tant que le plan est respecté. Un constructeur préfère un fournisseur fiable à une indemnité.",
    "맞교환을 제안하시는 겁니다. 매주 진행 상황 공유와 재고의 완전한 투명성이요. 그 대가로 계획이 지켜지는 동안은 위약금을 유예하는 거죠. 완성차 업체는 배상금보다 믿을 수 있는 공급업체를 원합니다."),
(AR, "Thomas, combien de temps pour lancer la production avec la puce d'Elbtron ?", "토마, 엘브트론 칩으로 생산을 시작하려면 얼마나 걸리나?"),
(TH, "Les cartes sont prêtes, les machines aussi. Il me faut une semaine pour former les équipes.", "기판도 기계도 준비돼 있습니다. 팀 교육에 일주일이면 됩니다."),
(AR, "Alors c'est décidé, on lance tout dès lundi. Serge, vous appelez Dresde cet après-midi. Moi, j'appelle Brenner. ... Merci à vous deux. Vous venez de me rendre le sommeil.",
     "그럼 결정했습니다. 월요일부터 전부 시작합시다. 세르주, 오늘 오후에 드레스덴에 전화해요. 나는 브레너에 전화하죠. ...두 분 고맙습니다. 덕분에 잠을 되찾았어요."),

# ---------- 6. Le soir : le bouchon et le dernier TGV ----------
(None, "Le soir même, 19 h. Un bouchon lyonnais rue Saint-Jean, dans le Vieux Lyon. Nappes à carreaux rouges et blancs, saucissons au plafond, pots de côtes-du-rhône sur les tables.",
       "그날 저녁 7시. 비외리옹 생장 거리의 리옹식 부숑. 빨간 체크무늬 식탁보, 천장에 매달린 소시송, 테이블마다 놓인 코트뒤론 포 와인병."),
(MA, "Des nappes à carreaux, des saucissons au plafond... C'est ça, un bouchon ?", "체크무늬 식탁보에 천장엔 소시송이라... 이게 부숑이야?"),
(I, "C'est ça. Ici, on ne vient pas pour la salade. Je te conseille la quenelle de brochet, sauce Nantua. Ou l'andouillette, si tu es courageux.",
    "그래. 여긴 샐러드 먹으러 오는 데가 아니야. 낭튀아 소스 곁들인 강꼬치고기 크넬 추천해. 용기가 있으면 앙두예트도 좋고."),
(MA, "Je suis alsacien, l'andouillette ne me fait pas peur. Mais je vais prendre la quenelle. Et toi ?", "난 알자스 사람이야. 앙두예트 안 무서워. 그래도 크넬로 할게. 넌?"),
(I, "Le saucisson brioché, et un pot de côtes-du-rhône pour deux. On fête une victoire, ce soir.", "소시송 브리오셰, 그리고 코트뒤론 한 병 나눠 마시자. 오늘 밤은 승리를 축하하는 거야."),
(MA, "Une victoire en deux moitiés. Ton stock et ma puce.", "반쪽짜리 두 개로 된 승리지. 네 재고와 내 칩."),
(I, "Et le tiroir de Thomas. Avoue que sans lui, on serait encore en train de se disputer.", "그리고 토마의 서랍. 그게 없었으면 우린 아직도 싸우고 있었을 거야, 인정해."),
(MA, "On ne se disputait pas. On débattait. C'est toi qui l'as dit.", "우린 싸운 게 아니야. 토론한 거지. 네가 그렇게 말했잖아."),
(I, "Je retire. Tu es pénible quand tu as de la mémoire. ... Tu sais, quand tu as haussé le ton mercredi, en fait, ça m'a plu.", "취소. 기억력 좋을 때 넌 피곤해. ...있잖아, 수요일에 네가 언성 높였을 때, 사실 좋았어."),
(MA, "Que je crie ?", "내가 소리 지른 게?"),
(I, "Que tu ne me laisses pas gagner. Les gens me laissent souvent gagner, parce que je parle fort et vite. Toi, non.", "네가 나한테 져 주지 않은 게. 사람들은 보통 나한테 져 줘. 내가 크고 빠르게 말하니까. 넌 안 그랬어."),
(MA, "Mon grand-père disait : « Si tu es toujours d'accord avec quelqu'un, l'un de vous deux ne sert à rien. »", "우리 할아버지가 그러셨어. '누군가와 늘 의견이 같다면, 둘 중 하나는 쓸모가 없는 거다.'"),
(I, "Il me plaît de plus en plus, ton grand-père. Bon, on paie, sinon on rate le dernier TGV.", "너희 할아버지 점점 더 마음에 든다. 자, 계산하자. 안 그러면 막차 TGV 놓쳐."),
(None, "21 h. Le dernier TGV pour Paris quitte la gare de la Part-Dieu. La voiture est presque vide. Cette fois, ils sont assis côte à côte.",
       "밤 9시. 파리행 막차 TGV가 파르디외역을 떠난다. 객차는 거의 비어 있다. 이번에는 둘이 나란히 앉았다."),
(MA, "Alors, Marchetti, avant que tu t'endormes : que fait-on lundi ?", "자, 마르케티, 너 잠들기 전에. 월요일엔 뭘 하지?"),
(I, "Lundi... Hélène m'a envoyé un message. Une chaîne de supermarchés qui jette beaucoup trop de nourriture. Et une nouvelle analyste dans l'équipe : Sofia.",
    "월요일엔... 엘렌이 문자 보냈어. 음식을 너무 많이 버리는 슈퍼마켓 체인이래. 그리고 팀에 새 애널리스트가 와. 소피아."),
(MA, "Une troisième personne dans notre binôme ? Ça va changer nos habitudes.", "우리 2인조에 세 번째 사람이라고? 습관이 좀 바뀌겠네."),
(I, "Il paraît qu'elle parle beaucoup. Tu ne seras plus le seul à poser des questions... Mais ce soir, je ne réponds plus à rien. Je ferme les yeux deux minutes.",
    "말이 엄청 많대. 이제 질문하는 사람이 너 혼자가 아니겠네... 그런데 오늘 밤엔 더 이상 아무 대답도 안 할 거야. 2분만 눈 감을게."),
(MA, "Deux minutes. Je te réveille à Paris.", "2분. 파리에서 깨워 줄게."),
(None, "Quelques minutes plus tard, la tête d'Inès glisse doucement sur l'épaule de Mathieu. Elle dort.", "몇 분 뒤, 이네스의 머리가 천천히 마티외의 어깨 위로 미끄러진다. 잠이 들었다."),
(MA, "Inès ? ... Bon. Deux minutes, elle a dit.", "이네스? ...그래. 2분이라고 했지."),
(I, "Mmm... Strasbourg... tu me dois toujours un café...", "음... 스트라스부르... 너 아직 커피 빚졌어..."),
(MA, "Je sais. Dors.", "알아. 자."),
(None, "Mathieu ne bouge plus. Jusqu'à Paris, il regarde par la fenêtre les lumières des villages défiler dans la nuit.", "마티외는 꼼짝하지 않는다. 파리에 닿을 때까지, 그는 창밖으로 밤의 마을 불빛들이 스쳐 지나가는 것을 바라본다."),
]

VOCAB = [
("B1", "une voiture / un carré (dans le train)", "(기차의) 객차 / 마주 보는 4인석", "TGV에서 객차는 wagon보다 voiture가 공식 표현. voiture 14. carré = 테이블을 사이에 둔 4인석."),
("B1", "la voie", "(역의) 승강장 번호, 선로", "Le train part voie K. 파리 리옹역은 숫자와 알파벳 승강장이 함께 있음. quai(플랫폼)와 함께 기억."),
("B2", "en raison de", "~로 인해, ~ 때문에", "à cause de의 격식 버전. 안내 방송·공문의 단골. en raison d'un incident technique."),
("B2", "une pénurie", "(물자) 부족, 품귀", "pénurie de puces / de main-d'œuvre. manque보다 심각하고 구조적인 부족."),
("B2", "une puce (électronique)", "반도체 칩", "puce는 원래 '벼룩'. 작아서 붙은 이름. 반도체 산업 전체는 les semi-conducteurs."),
("B2", "le juste-à-temps", "저스트인타임(적시 생산)", "재고를 최소화해 필요한 때 필요한 만큼만 조달하는 방식. travailler en juste-à-temps."),
("B2", "le double sourcing", "이중 소싱(공급처 이원화)", "↔ single sourcing(단일 소싱). 프랑스 기업에서도 영어 용어를 그대로 씀. multisourcing도 가능."),
("B2", "des pénalités de retard", "지연 위약금", "facturer / appliquer des pénalités. 계약서의 지연 배상 조항."),
("B1", "le délai de livraison", "납기, 배송 기간", "Le délai est passé de douze semaines à presque un an. respecter les délais = 기한을 지키다."),
("B2", "au compte-gouttes", "찔끔찔끔, 조금씩", "compte-gouttes = 스포이트. livrer / recevoir au compte-gouttes."),
("B2", "le chômage partiel", "부분 실업(일시 휴업 지원 제도)", "공식 명칭은 activité partielle. 회사가 일감이 없을 때 국가 지원으로 임금 일부를 보전."),
("B1", "au plus tard", "늦어도", "dans trois semaines au plus tard. ↔ au plus tôt(빨라도)."),
("B2", "immobiliser (de l'argent)", "(자금을) 묶어 두다", "재고·설비에 자금이 묶여 다른 데 쓸 수 없는 상태. trois millions d'euros immobilisés."),
("B2", "s'étrangler", "(놀라서) 숨넘어가다", "원뜻은 '목이 메다'. 터무니없는 숫자를 들었을 때. Il va s'étrangler en voyant la facture."),
("B2", "hausser le ton", "언성을 높이다", "ton = 어조. baisser le ton(목소리를 낮추다)."),
("B2", "le bureau d'études", "설계실, 엔지니어링 부서", "제조업에서 제품 설계·개발을 맡는 부서. 연구소(laboratoire de R&D)와 구분."),
("B2", "valider", "승인하다, 인증하다", "Brenner a validé la nouvelle version. 자동차 업계에서는 homologuer(형식 승인하다)도 씀."),
("C1", "assumer (une décision)", "(결정의) 책임을 지다", "Je l'assume. 영어 assume(가정하다)과 뜻이 다른 '가짜 친구'. 떳떳이 인정한다는 뉘앙스."),
("B2", "une cellule de crise", "위기 대응반", "기업·정부의 비상 대책팀. mettre en place une cellule de crise."),
("B2", "en contrepartie", "그 대가로, 대신", "협상의 핵심 표현. Nous vous offrons X ; en contrepartie, vous suspendez Y."),
("B1", "Marché conclu !", "좋아, 그렇게 하자!", "직역 '거래 성사'. 일상에서 제안을 받아들일 때 가볍게 씀."),
("B2", "une dette qui court (toujours)", "(빚이) 여전히 유효하다", "courir = 계속 진행되다. Le délai court toujours. Ta dette, elle, court toujours."),
("B1", "un bouchon lyonnais", "부숑(리옹 전통 식당)", "리옹식 가정 요리를 내는 작은 식당. bouchon은 '교통 체증'이라는 뜻도 있음."),
("B1", "un pot (lyonnais)", "포(리옹식 와인병, 46cl)", "바닥이 두꺼운 리옹 특유의 와인병. un pot de côtes-du-rhône."),
("B1", "une quenelle de brochet", "강꼬치고기 크넬", "생선살 반죽을 빚어 익힌 리옹 명물. 보통 가재 소스(sauce Nantua)와 함께."),
]

GRAM = [
("B1", "원인 표현: à cause de / grâce à / en raison de / puisque",
 "« Leur usine s'arrête trois jours par semaine à cause de la pénurie de puces. » « À cause du juste-à-temps, ils n'avaient aucune réserve. » à cause de는 보통 나쁜 결과의 원인, grâce à는 좋은 결과의 원인(Grâce à Thomas, l'usine redémarre)에 쓴다. 안내 방송의 « en raison d'un incident technique »은 격식체. 뒤에 절이 올 때는 parce que나, 상대도 아는 이유를 댈 때 puisque를 쓴다: « Il ne sera jamais prêt, puisqu'il n'y a pas de puces à acheter ! »"),
("B1", "결과 표현: donc / c'est pourquoi / si bien que",
 "« Cinq jours... Donc au premier retard de livraison, la ligne s'arrête. » « C'est pourquoi Philippe Arnaud, le PDG, nous a appelés vendredi soir. » « On reçoit des livraisons partielles, au compte-gouttes, si bien qu'on produit deux jours et qu'on s'arrête trois. » donc는 문장 안 어디에나 오는 가장 기본적인 결과 표현, c'est pourquoi는 문장 맨 앞에서 '그래서 ~한 것이다', si bien que는 '그 결과 ~하게 되다'로 직설법을 쓴다."),
("B1", "일정·기한 표현: d'ici / au plus tard / dès / à partir de / jusqu'à",
 "« Il veut un plan d'action dans trois semaines au plus tard. » « Si nos livraisons ne sont pas revenues à la normale d'ici là... » « Ils peuvent livrer quatre mille puces par jour dès la mi-novembre, et sept mille à partir de début décembre. » « De quoi travailler jusqu'à demain midi. » d'ici는 '지금부터 ~까지(기한)', dès는 '~부터 곧바로'(즉시성 강조), à partir de는 중립적인 '~부터', jusqu'à는 '~까지(계속)'."),
("B2", "si + 대과거 → 조건법 과거: 과거 사실의 반대",
 "« Si on m'avait fixé cet objectif-là il y a un an, j'aurais signé avec Elbtron le jour même. » 실제로 일어나지 않은 과거를 가정할 때 si절에 대과거(avais fixé), 주절에 조건법 과거(aurais signé)를 쓴다. 비알의 후회를 담은 문장이다. 비난할 때는 il aurait fallu(~했어야 했다)를 쓴다: « Il aurait fallu commencer hier. »"),
("B2", "수동태 맛보기: être + 과거분사 (+ par)",
 "« Le projet a été arrêté avant d'arriver jusqu'à vous. » « Arrêté par moi, je l'assume. » « C'est là-dessus que je suis évalué. » « Une puce de remplacement, validée par le client... » 행위자보다 결과를 강조할 때 수동태를 쓴다. 과거분사는 주어에 성·수 일치한다(validée ← la puce). 행위자는 par로 나타내며, 비알처럼 « par moi »를 덧붙이면 책임을 스스로 인정하는 효과가 있다."),
("B1", "avant de + 부정사 / avant que + 접속법",
 "« Le projet a été arrêté avant d'arriver jusqu'à vous. »(주어가 같음 → avant de + 부정사) « Avant que tu t'endormes : que fait-on lundi ? »(주어가 다름 → avant que + 접속법). 접속법 s'endormes는 현재형 s'endors와 형태가 다르다는 점에 주의하자. 문어에서는 avant que tu ne t'endormes처럼 허사 ne를 넣기도 한다."),
("B2", "전위(앞으로 빼기) 구문: 명사 + 대명사로 강조",
 "« Ta dette, elle, court toujours. » « Et la MC-40, elle est posée à quel moment ? » « Le stock, il faut le financer et le stocker. » « Et ton stock, il ne sera jamais prêt ! » 구어에서는 주제를 문장 앞에 내세우고 대명사(elle, il, le)로 다시 받는다. 대화의 초점을 바꾸거나 대비할 때(ton stock ↔ ma puce) 아주 자주 쓰인다."),
("B1", "tant que: ~하는 동안은, ~하는 한",
 "« Tant que tout va bien, c'est moins cher. » « Le juste-à-temps marche très bien... tant que rien ne manque. » « Il suspend les pénalités tant que le plan est respecté. » tant que는 조건이 유지되는 동안만 결과가 성립함을 나타낸다. 미래의 일이라도 현재형을 쓰는 것이 자연스럽다. 1화의 « Tant que tu me devras un café »처럼 미래형도 가능하다."),
]

CULTURE = [
("TGV와 프랑스의 기차 여행",
 "1981년 파리–리옹 구간에서 처음 운행을 시작한 TGV(train à grande vitesse)는 프랑스 고속철도의 상징이다. 파리 리옹역(gare de Lyon)에서 리옹 파르디외역까지는 약 2시간이 걸려, 비즈니스 출장객은 당일치기로 많이 이용한다. 좌석 중 테이블을 사이에 두고 넷이 마주 보는 자리를 carré라고 부르며, 출장 중 회의 장소로 인기가 있다. 열차 칸은 voiture, 승강장 번호는 voie로 표시된다."),
("자동차 반도체 대란과 저스트인타임의 한계",
 "2020~2023년 코로나19 이후 전자기기 수요가 폭증하고, 감산했던 자동차 업계의 주문이 한꺼번에 몰리면서 차량용 반도체가 심각하게 부족해졌다. 유럽의 많은 자동차 공장과 부품 업체가 생산을 멈추거나 줄였다. 재고를 최소화하는 저스트인타임 방식과 아시아 소수 업체에 대한 의존이 위험 요인으로 지적되었고, 기업들은 공급처 다변화와 전략 재고를 늘리기 시작했다. EU도 2023년 역내 반도체 생산을 늘리기 위한 '유럽 반도체법(European Chips Act)'을 채택했다."),
("리옹의 부숑(bouchon lyonnais)",
 "리옹은 '미식의 수도'로 불린다. 부숑은 체크무늬 식탁보와 소박한 분위기 속에서 리옹 전통 요리를 내는 작은 식당으로, 19~20세기 리옹의 여성 요리사들(les mères lyonnaises)의 가정식 전통을 잇는다. 대표 메뉴는 크넬(quenelle), 앙두예트(andouillette), 소시송 브리오셰(saucisson brioché), 생마르슬랭 치즈, 프랄린 타르트 등이다. 와인은 46cl짜리 두꺼운 바닥의 병 pot에 담겨 나오는데, 보졸레나 코트뒤론이 흔하다."),
]
