# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, SO = "Inès", "Mathieu", "Hélène", "Sofia"
J, MO, LA, K = "Jojo", "Moreau", "Lacour", "Karim"

META = {
    "part": 1, "ep": 4,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "Zéro gaspillage",
    "title_ko": "식품 폐기 제로",
    "place": "12구 알리그르 시장 · Vasseur & Associés · 이브리쉬르센 프리마베르 본사 · 크레테유 매장 · 생마르탱 운하 와인 바 / 10월 말~11월 초",
    "chars": "이네스, 마티외, 엘렌, 소피아 베날리(신입 애널리스트), 조조(시장 생선 장수), 실비 모로(프리마베르 대표), 드니 라쿠르(운영 이사), 카림(크레테유 매장 신선식품 매대 책임자)",
    "work": "슈퍼마켓 체인 프리마베르 — 신선식품 폐기 연 4,500만 유로(매출의 3%), 낭비방지법상 기부 협약 미흡, SNS 영상으로 번진 평판 위기",
    "life": "토요일 알리그르 시장 장보기(생선 고르는 법·흥정), 새 동료 소피아의 합류, 퇴근 후 셋의 아페로와 소피아의 돌직구 질문",
    "focus": "시장 어휘·수량 표현, 의무 표현(devoir, il faut, être obligé de), 법·규정 어휘(la loi oblige, il est interdit de, avoir le droit de), DLC/DDM, ce dont, 조건법 과거",
    "levelmix": "B1 45% · B2 50% · C1 5%",
    "next": "제5화 Retards en cascade — 니스의 지역 항공사, 하루 종일 꼬리를 무는 연쇄 지연, 그리고 공항에 발이 묶인 밤.",
}

D = [
# ---------- 1. Ouverture : le marché d'Aligre ----------
(None, "Samedi, 9 h 30. Le marché d'Aligre, dans le 12e. Les marchands crient leurs prix entre les étals. Mathieu porte un grand cabas encore vide.",
       "토요일 오전 9시 30분. 12구 알리그르 시장. 좌판 사이로 상인들이 값을 외친다. 마티외는 아직 텅 빈 커다란 장바구니를 들고 있다."),
(MA, "Inès ? Qu'est-ce que tu fais là ? Je croyais que le samedi matin, tu dormais.", "이네스? 여기서 뭐 해? 토요일 아침엔 자는 줄 알았는데."),
(I, "Le dimanche, je nage ; le samedi, je fais mon marché. Aligre, c'est mon marché depuis six ans. Et toi, tu as traversé tout Paris pour des poireaux ?",
    "일요일엔 수영하고, 토요일엔 장을 봐. 알리그르는 6년째 내 단골 시장이야. 그런데 넌 대파 사러 파리를 가로질러 온 거야?"),
(MA, "J'ai enfin une vraie cuisine, avec deux plaques ! Il faut que je la remplisse. On m'a dit que c'était le marché le moins cher de Paris.",
     "드디어 화구 두 개짜리 진짜 부엌이 생겼잖아! 채워 넣어야지. 여기가 파리에서 제일 싼 시장이라던데."),
(I, "On t'a bien renseigné. Viens, je vais t'apprendre à choisir un poisson. À Marseille, on apprend ça avant de savoir lire.",
    "제대로 들었네. 이리 와, 생선 고르는 법 가르쳐 줄게. 마르세유에선 글 읽기 전에 그것부터 배워."),
(J, "Ah, voilà ma Marseillaise ! Qu'est-ce que je te mets aujourd'hui ?", "아, 우리 마르세유 아가씨 왔네! 오늘은 뭘 줄까?"),
(I, "Attends, Jojo, je donne un cours à mon collègue. Regarde, Strasbourg : l'œil doit être bombé et brillant. S'il est creux ou gris, le poisson n'est plus frais.",
    "잠깐만요, 조조. 동료한테 수업 중이에요. 봐, 스트라스부르. 눈은 볼록하고 반짝여야 해. 움푹하거나 뿌옇다면 신선하지 않은 거야."),
(MA, "D'accord. Et ensuite ?", "알겠어. 그다음은?"),
(I, "Tu regardes les ouïes : elles doivent être rouge vif. Et la chair doit être ferme. Si ton doigt laisse une marque, tu passes ton chemin.",
    "아가미를 봐. 선홍색이어야 해. 그리고 살은 탱탱해야 해. 손가락 자국이 남으면 그냥 지나가."),
(J, "Elle a raison. Un poisson frais, ça sent la mer, pas le poisson. Ces daurades sont arrivées ce matin de Bretagne : vingt-deux euros le kilo.",
    "아가씨 말이 맞아요. 신선한 생선은 비린내가 아니라 바다 냄새가 나요. 이 도미들은 오늘 아침 브르타뉴에서 왔어요. 킬로에 22유로."),
(MA, "Il m'en faudrait deux. Une pour ce soir, une pour demain.", "두 마리 주세요. 하나는 오늘 저녁, 하나는 내일 거로요."),
(J, "Elles font à peu près quatre cents grammes chacune. Ça fait dix-sept euros soixante... Allez, quinze euros tout rond, et je vous les vide.",
    "한 마리에 400그램쯤 나가요. 17유로 60센트인데... 에이, 딱 15유로만 내요. 손질도 해 드릴게."),
(MA, "Merci beaucoup ! C'est gentil.", "정말 감사합니다! 친절하시네요."),
(I, "Ne le remercie pas trop, il fait ça à tout le monde vers midi. À la fin du marché, Jojo brade ou donne ce qui reste. Il ne jette jamais rien.",
    "너무 고마워하지 마. 정오쯤엔 누구한테나 그래. 장이 파할 무렵이면 조조는 남은 걸 싸게 팔거나 나눠 줘. 절대 버리는 법이 없어."),
(None, "Un peu plus tard, devant un étal de légumes. Le cabas de Mathieu est plein.", "잠시 뒤, 채소 좌판 앞. 마티외의 장바구니가 가득 찼다."),
(MA, "Un kilo de pommes de terre, une botte de radis, une livre de champignons... Pour te remercier, je t'offre un café ?",
     "감자 1킬로, 래디시 한 단, 버섯 500그램... 고마우니까 커피 한잔 살까?"),
(I, "Tu essaies de payer tes dettes entre deux daurades ? Pas question. Tu me dois un vrai café et un vrai croissant. Et repose-toi : lundi, nouveau client et nouvelle collègue.",
    "도미 두 마리 사이에서 빚을 갚으시겠다? 어림없지. 넌 나한테 제대로 된 커피 한 잔이랑 크루아상 하나를 빚졌어. 그리고 푹 쉬어. 월요일엔 새 고객이랑 새 동료가 와."),

# ---------- 2. Briefing et client ----------
(None, "Lundi, 9 h. Vasseur & Associés, salle « Monceau ». Une jeune femme aux cheveux bouclés attend déjà, son ordinateur ouvert devant elle.",
       "월요일 오전 9시. 바쇠르 & 어소시에이츠, '몽소' 회의실. 곱슬머리의 젊은 여성이 노트북을 펼쳐 놓고 벌써 기다리고 있다."),
(H, "Bonjour à tous les deux. Je vous présente Sofia Benali, notre nouvelle analyste. Elle arrive de Lille, et elle fait parler les données mieux que personne.",
    "둘 다 안녕. 새 애널리스트 소피아 베날리를 소개할게. 릴에서 왔고, 누구보다 데이터를 잘 말하게 만드는 사람이야."),
(SO, "Bonjour ! Enfin, salut : ici, on se tutoie, c'est ça ? Hélène m'a beaucoup parlé de vous. C'est vous, les deux qui vont dans les usines à quatre heures du matin ?",
     "안녕하세요! 아니, 안녕. 여기선 말 놓는 거 맞죠? 엘렌이 두 분 얘기를 많이 했어요. 새벽 4시에 공장에 가는 그 두 사람이죠?"),
(MA, "Quatre heures et demie, et c'était une boulangerie. Bienvenue, Sofia ! Moi, c'est Mathieu. Je suis presque nouveau aussi : j'arrive de Strasbourg.",
     "4시 반이었고, 빵집이었어. 환영해, 소피아! 난 마티외야. 나도 거의 신입이야. 스트라스부르에서 왔거든."),
(I, "Et moi, Inès. Bienvenue. Tu verras, ici, on travaille beaucoup, mais on apprend vite. Tu connais un peu la grande distribution ?",
    "난 이네스. 환영해. 여기선 일은 많지만 빨리 배우게 될 거야. 대형 유통 쪽은 좀 알아?"),
(SO, "Un peu, grâce à mon stage. Et ma grand-mère fait toutes ses courses chez Primavert, à Roubaix. Elle connaît toutes les promotions par cœur.",
     "인턴십 덕분에 조금요. 그리고 우리 할머니가 루베에 있는 프리마베르에서 장을 다 보세요. 할인 행사를 전부 외우고 계시죠."),
(H, "Ça tombe bien. Inès, tu leur présentes le dossier ?", "마침 잘됐네. 이네스, 사건 설명 좀 해 줄래?"),
(I, "Avec plaisir. Primavert : cent quatre-vingts supermarchés en Île-de-France et dans le Nord, un milliard et demi d'euros de chiffre d'affaires. Une chaîne régionale qui résiste aux géants.",
    "기꺼이요. 프리마베르는 일드프랑스와 북부 지역에 슈퍼마켓 180곳, 매출 15억 유로. 대형 유통 공룡들 사이에서 버티는 지역 체인이야."),
(MA, "Et qui a un problème, sinon nous ne serions pas là.", "그리고 문제가 있겠지. 아니면 우리가 여기 없을 테니까."),
(I, "Le gaspillage. Chaque année, Primavert jette des produits frais pour trois pour cent de son chiffre d'affaires.", "식품 폐기야. 프리마베르는 해마다 매출의 3%에 해당하는 신선식품을 버려."),
(SO, "Trois pour cent d'un milliard et demi... Ça fait quarante-cinq millions d'euros à la poubelle !", "15억의 3%면... 4,500만 유로가 쓰레기통으로 가는 거네요!"),
(MA, "Tu calcules plus vite que ton ordinateur, toi.", "너 컴퓨터보다 계산이 빠르구나."),
(I, "Et il y a pire. Il y a un mois, une vidéo a circulé sur les réseaux sociaux : des bennes pleines de yaourts et de salades derrière un magasin Primavert de Roubaix. Deux millions de vues.",
    "더 심각한 게 있어. 한 달 전에 SNS에 영상 하나가 돌았어. 루베의 프리마베르 매장 뒤에 요구르트랑 샐러드가 가득 찬 쓰레기 컨테이너. 조회수 200만."),
(SO, "Oh non... C'est peut-être le magasin de ma grand-mère !", "아, 안 돼... 우리 할머니 가게일지도 몰라요!"),
(I, "Depuis, les journalistes demandent si Primavert respecte la loi anti-gaspillage. La présidente, Sylvie Moreau, nous attend à onze heures, à leur siège d'Ivry.",
    "그 뒤로 기자들이 프리마베르가 낭비방지법을 지키는지 묻고 있어. 대표 실비 모로가 11시에 이브리 본사에서 기다려."),
(MA, "Alors on emmène Sofia. Autant voir un vrai client dès le premier jour, non ?",
     "그럼 소피아도 데려가자. 첫날부터 진짜 고객을 보는 게 낫잖아, 안 그래?"),
(None, "11 h. Siège de Primavert, à Ivry-sur-Seine. Sylvie Moreau, la cinquantaine, est accompagnée de Denis Lacour, directeur des opérations.",
       "오전 11시. 이브리쉬르센의 프리마베르 본사. 50대의 실비 모로 옆에 운영 이사 드니 라쿠르가 앉아 있다."),
(MO, "Merci d'être venus si vite. Je vais être franche : cette vidéo nous a fait très mal. Nos clients nous écrivent, et certains maires aussi.",
     "이렇게 빨리 와 주셔서 감사합니다. 솔직히 말씀드리죠. 그 영상으로 큰 타격을 입었어요. 고객들이 항의 편지를 보내고, 시장(市長)들까지 연락해 와요."),
(I, "Bonjour madame Moreau, bonjour monsieur Lacour. Nous l'avons vue. Mais avant de parler d'image, parlons de chiffres : que jetez-vous, exactement ?",
    "안녕하세요, 모로 대표님, 라쿠르 이사님. 저희도 봤습니다. 하지만 이미지 얘기 전에 숫자부터 보죠. 정확히 무엇을 버리시나요?"),
(LA, "Surtout du frais : fruits et légumes, produits laitiers, viande, plats préparés. Dès qu'un produit arrive à sa date, nous devons le retirer du rayon.",
     "주로 신선식품이에요. 과일·채소, 유제품, 고기, 즉석식품. 제품이 날짜에 다다르면 매대에서 빼야 하니까요."),
(MA, "Et une fois retiré, que devient-il ?", "그럼 빼낸 제품은 어떻게 되나요?"),
(LA, "Une partie part aux associations. Le reste va à la benne, puis dans une usine de méthanisation.", "일부는 자선단체로 가요. 나머지는 컨테이너에 버려지고, 그다음 메탄화 시설로 가죠."),
(I, "Depuis 2016, la loi oblige tout supermarché de plus de quatre cents mètres carrés à proposer une convention de don à une association. Combien de vos magasins en ont une ?",
    "2016년부터 법은 면적 400제곱미터가 넘는 모든 슈퍼마켓에 자선단체와 기부 협약을 제안하도록 의무화하고 있습니다. 매장 중 몇 곳이 협약을 맺었나요?"),
(LA, "Tous nos magasins sont concernés. Mais seuls soixante-deux ont une convention active. Ailleurs, nous n'avons pas trouvé de partenaire, ou les associations ne passent pas.",
     "우리 매장은 전부 해당돼요. 하지만 실제로 협약이 작동하는 곳은 62곳뿐이에요. 다른 곳은 파트너를 못 찾았거나, 단체가 수거하러 오지 않아요."),
(MA, "Soixante-deux sur cent quatre-vingts... À peine plus d'un tiers.", "180곳 중 62곳이면... 겨우 3분의 1 남짓이네요."),
(MO, "Je sais, ce n'est pas suffisant. Nous risquons une amende, mais surtout notre réputation. Primavert est une enseigne de proximité : les gens nous font confiance.",
     "알아요, 충분하지 않죠. 벌금도 문제지만 무엇보다 평판이 걸려 있어요. 프리마베르는 동네 슈퍼예요. 사람들이 우리를 믿어 준다고요."),
(SO, "Excusez-moi... Les commandes de produits frais, elles sont faites par chaque magasin ou par le siège ?", "실례지만... 신선식품 발주는 매장마다 하나요, 본사에서 하나요?"),
(LA, "Par le siège, automatiquement. Notre logiciel prend les ventes moyennes de l'enseigne et les adapte à la taille de chaque magasin. Ça marche depuis quinze ans.",
     "본사에서 자동으로요. 우리 소프트웨어가 체인 전체의 평균 판매량을 가져와 매장 크기에 맞춰 조정하죠. 15년째 잘 돌아가고 있어요."),
(I, "En quinze ans, vos clients ont un peu changé, non ?", "15년이면 고객들도 좀 바뀌지 않았을까요?"),
(LA, "Un yaourt reste un yaourt, madame.", "요구르트는 요구르트예요."),
(MA, "Sans doute. Mais celui qui l'achète n'est plus le même. Pourrions-nous avoir vos ventes et vos pertes par produit, par magasin et par jour, sur deux ans ? Avec les dates des produits jetés.",
     "그렇겠죠. 하지만 그걸 사는 사람은 예전과 다릅니다. 2년 치 판매량과 손실을 제품별·매장별·일별로 받을 수 있을까요? 버린 제품의 날짜 정보까지요."),
(MO, "Vous aurez tout demain matin. Mais il me faut un plan dans un mois : mon conseil d'administration se réunit le quinze.",
     "내일 아침에 다 드릴게요. 하지만 한 달 안에 계획이 필요해요. 15일에 이사회가 열려요."),

# ---------- 3. Analyse ----------
(None, "Mercredi, 18 h. Salle « Monceau ». Sofia a projeté sur le mur des graphiques de toutes les couleurs.", "수요일 저녁 6시. '몽소' 회의실. 소피아가 벽에 온갖 색깔의 그래프를 띄워 놓았다."),
(SO, "Bon. J'ai passé deux jours et une nuit dans leurs données. J'ai trois choses à vous montrer.", "자. 이틀 낮 하룻밤을 그쪽 데이터에 파묻혀 있었어요. 보여 드릴 게 세 가지예요."),
(MA, "Une nuit ? Hélène va croire qu'on t'exploite déjà. Vas-y, on t'écoute.", "하룻밤? 엘렌이 우리가 벌써 널 혹사시킨다고 생각하겠다. 말해 봐, 듣고 있어."),
(SO, "Un : le logiciel commande presque la même chose partout. Le magasin de Créteil et celui du quinzième ont la même surface, donc ils reçoivent les mêmes produits frais. Mais à Créteil, il y a l'université et beaucoup de retraités qui vivent seuls. Dans le quinzième, ce sont surtout des familles.",
     "하나. 소프트웨어가 어디에나 거의 똑같이 발주해요. 크레테유 매장과 15구 매장은 면적이 같아서 같은 신선식품을 받아요. 그런데 크레테유엔 대학이 있고 혼자 사는 은퇴자가 많아요. 15구는 주로 가족 단위고요."),
(I, "Donc Créteil reçoit des packs familiaux qu'il ne vend pas, et le quinzième en manque.", "그러니까 크레테유는 팔리지도 않는 가족용 묶음을 받고, 15구는 그게 모자라는 거네."),
(SO, "Exactement. Et c'est pareil dans tout le réseau : dans quarante pour cent des magasins, les commandes de frais dépassent les ventes de plus de quinze pour cent.",
     "바로 그거예요. 그리고 체인 전체가 마찬가지예요. 매장의 40%에서 신선식품 발주량이 판매량을 15% 넘게 초과해요."),
(MA, "Quinze pour cent de trop, tous les jours... Ça explique une bonne partie des quarante-cinq millions.", "매일 15%씩 넘친다면... 4,500만 유로의 상당 부분이 설명되네."),
(SO, "Deux : regardez ce camembert. Dix-huit pour cent des produits jetés n'ont pas de DLC, mais une DDM.", "둘. 이 원그래프 보세요. 버려진 제품의 18%는 DLC가 아니라 DDM이 붙은 제품이에요."),
(MA, "Attends. DLC, DDM... Je confonds toujours les deux. Quelqu'un m'explique ?", "잠깐. DLC, DDM... 난 늘 둘을 헷갈려. 누가 설명 좀 해 줄래?"),
(I, "La DLC, c'est la date limite de consommation : « à consommer jusqu'au ». Après cette date, le produit peut être dangereux ; on n'a plus le droit de le vendre, ni de le donner.",
    "DLC는 소비기한이야. '~까지 섭취'. 이 날짜가 지나면 위험할 수 있어서 팔 수도, 기부할 수도 없어."),
(SO, "Et la DDM, c'est la date de durabilité minimale : « à consommer de préférence avant ». Après, le produit perd un peu de goût, mais on peut le manger sans risque. Le café, les biscuits, les pâtes, les jus...",
     "DDM은 품질유지기한이에요. '~ 이전에 섭취 권장'. 그 뒤엔 맛이 조금 떨어지지만 먹어도 위험하지 않아요. 커피, 비스킷, 파스타, 주스 같은 거요."),
(MA, "Donc on peut encore les vendre ?", "그럼 아직 팔 수 있다는 거야?"),
(I, "Oui, c'est légal, et surtout, on peut les donner. Mais je parie que chez Primavert, la règle interne dit : « date dépassée, produit jeté ».",
    "응, 합법이야. 그리고 무엇보다 기부할 수 있지. 그런데 장담하는데 프리마베르 내부 규정엔 '날짜 지나면 폐기'라고 돼 있을걸."),
(SO, "Gagné. Mot pour mot. C'est écrit dans le manuel des magasins.", "맞혔어요. 토씨 하나 안 틀리고요. 매장 매뉴얼에 그렇게 쓰여 있어요."),
(I, "Dix-huit pour cent de quarante-cinq millions... ça fait environ huit millions d'euros de produits parfaitement mangeables. Jetés à cause d'une règle mal écrite.",
    "4,500만의 18%면... 멀쩡히 먹을 수 있는 제품이 약 800만 유로어치야. 잘못 쓰인 규정 하나 때문에 버려지는 거지."),
(SO, "Et trois, le plus bizarre : les rabais. Moins de cinq pour cent des produits jetés ont eu une étiquette de réduction avant. Et ça, mes données ne disent pas pourquoi.",
     "그리고 셋, 제일 이상한 거요. 할인이에요. 버려진 제품 중 그 전에 할인 스티커가 붙었던 건 5%도 안 돼요. 그런데 그 이유는 데이터가 말해 주지 않아요."),
(MA, "Bizarre, en effet. Partout ailleurs, on voit des étiquettes jaunes « moins trente pour cent » le soir.", "정말 이상하네. 다른 데선 저녁마다 노란 '30% 할인' 스티커가 보이잖아."),
(I, "Pour moi, la solution est claire : on remplace leur logiciel par un modèle de prévision magasin par magasin. Sofia dit qu'elle peut faire un prototype en une semaine.",
    "내가 보기엔 답이 분명해. 그 소프트웨어를 매장별 수요 예측 모델로 바꾸는 거야. 소피아가 시제품은 일주일이면 만들 수 있대."),
(MA, "Une semaine, c'est impressionnant. Mais doucement. L'algorithme, c'est bien, mais si les magasins ne font presque jamais de rabais, il y a une raison. Il faut la comprendre avant de proposer quoi que ce soit.",
     "일주일이라니 대단하다. 그래도 천천히. 알고리즘도 좋지만, 매장들이 할인을 거의 안 한다면 이유가 있을 거야. 뭘 제안하든 그 이유부터 이해해야 해."),
(I, "La raison, c'est sûrement qu'ils n'ont pas le temps. Mathieu, quarante-cinq millions ! Il faut attaquer la cause principale, et la cause principale, ce sont les commandes.",
    "이유야 분명 시간이 없어서겠지. 마티외, 4,500만 유로야! 주원인을 공략해야 하고, 주원인은 발주야."),
(MA, "Peut-être. Mais souviens-toi de Youssef, chez Lebrun. Les chiffres disaient « trop de pain », et c'est lui qui nous a expliqué pourquoi.",
     "그럴지도. 그런데 르브룅의 유세프 기억나? 숫자는 '빵이 너무 많다'고만 했고, 왜 그런지 설명해 준 건 그 사람이었어."),
(I, "Je m'en souviens. Mais là, il s'agit de cent quatre-vingts magasins, pas d'une boulangerie. On ne peut pas interroger tout le monde.",
    "기억하지. 그런데 이번엔 빵집 하나가 아니라 매장 180곳이야. 모두를 인터뷰할 수는 없어."),
(MA, "Pas tout le monde. Un magasin, un matin. Créteil, puisqu'il jette plus que les autres.", "모두는 아니고. 매장 한 곳, 아침 한 번. 크레테유. 다른 데보다 더 많이 버리니까."),
(I, "Laisse-moi deviner : à six heures du matin, comme d'habitude ?", "맞혀 볼게. 늘 그렇듯 새벽 6시에?"),
(SO, "Euh... vous vous disputez toujours comme ça, tous les deux ?", "어... 두 분은 늘 이렇게 싸워요?"),
(I, "On ne se dispute pas, on débat. Ce n'est pas pareil.", "싸우는 게 아니라 토론하는 거야. 그건 다르지."),
(MA, "Elle a raison. Quand on se dispute, c'est elle qui gagne. Quand on débat... c'est elle qui gagne aussi.", "이네스 말이 맞아. 싸우면 이네스가 이겨. 토론하면... 그때도 이네스가 이기고."),
(I, "Très drôle. Bon, avant d'y aller, je veux être sûre de la partie juridique. Je ne veux aucune mauvaise surprise devant le conseil. Qu'est-ce que Primavert est obligé de faire, exactement ?",
    "참 재밌네. 자, 가기 전에 법적인 부분을 확실히 하고 싶어. 이사회 앞에서 뒤통수 맞기 싫거든. 프리마베르가 정확히 뭘 해야 할 의무가 있지?"),
(SO, "J'ai vérifié. Ils doivent proposer une convention de don à une association habilitée. Et il leur est interdit de rendre des invendus encore consommables impropres à la consommation, par exemple avec de l'eau de Javel.",
     "확인해 봤어요. 인가받은 단체에 기부 협약을 제안해야 해요. 그리고 아직 먹을 수 있는 재고를 못 먹게 만드는 건 금지예요. 예를 들어 락스를 붓는 것 같은 거요."),
(MA, "De l'eau de Javel sur de la nourriture ? Ça se faisait vraiment ?", "음식에 락스를? 그런 일이 정말 있었어?"),
(I, "Dans certains magasins, oui, avant la loi. Aujourd'hui, c'est puni d'une amende. Bon, c'est décidé : Créteil, vendredi, à l'arrivée des livraisons. Sofia, tu viens avec nous. Rendez-vous à six heures.",
    "법이 생기기 전엔 일부 매장에서 그랬어. 지금은 벌금형이야. 좋아, 결정했어. 금요일, 배송이 들어오는 시간에 크레테유로 가자. 소피아, 너도 같이 가. 6시에 만나."),

# ---------- 4. Terrain : le magasin de Créteil ----------
(None, "Vendredi, 6 h. Magasin Primavert de Créteil. Le rideau de fer est encore baissé. Dans la réserve, les palettes de produits frais arrivent l'une après l'autre.",
       "금요일 새벽 6시. 프리마베르 크레테유 매장. 셔터는 아직 내려져 있다. 창고에는 신선식품 팔레트가 줄줄이 들어온다."),
(K, "Bonjour ! Karim, chef du rayon frais. C'est vous, les consultants ? Je vous préviens, ici, ça va vite : à huit heures et demie, tout doit être en rayon.",
    "안녕하세요! 신선식품 매대 책임자 카림입니다. 컨설턴트분들이시죠? 미리 말씀드리는데, 여긴 빨리 돌아가요. 8시 반까지 전부 매대에 진열돼 있어야 하거든요."),
(I, "Bonjour Karim. Nous ne voulons surtout pas vous ralentir. On peut vous suivre pendant la mise en rayon ?", "안녕하세요, 카림 씨. 절대 방해하지 않을게요. 진열하시는 동안 따라다녀도 될까요?"),
(K, "Suivez-moi. Tous les matins, on commence par le retrait : on vérifie les dates, et tout ce qui arrive à sa date sort du rayon.",
    "따라오세요. 매일 아침 회수부터 시작해요. 날짜를 확인하고, 날짜에 다다른 건 전부 매대에서 빼요."),
(MA, "Et ça représente combien, chaque matin ?", "그게 매일 아침 얼마나 되나요?"),
(K, "En moyenne, quatre-vingts kilos. Regardez ce chariot : yaourts, salades en sachet, jambon, poulet... On retire tout à J-2, c'est la procédure du siège. Et tout ça part à la benne.",
    "평균 80킬로요. 이 카트 보세요. 요구르트, 봉지 샐러드, 햄, 닭고기... 날짜 이틀 전에 전부 빼요. 본사 절차예요. 그리고 이게 다 컨테이너로 가요."),
(SO, "À J-2 ? Mais ces yaourts aux fruits ont encore deux jours de DLC !", "이틀 전에요? 이 과일 요구르트는 소비기한이 아직 이틀이나 남았는데요!"),
(I, "Justement, pendant ces deux jours, vous pourriez les vendre moins cher. Pourquoi vous ne mettez pas d'étiquettes de réduction ?",
    "바로 그거예요. 그 이틀 동안 싸게 팔 수 있잖아요. 왜 할인 스티커를 안 붙이세요?"),
(K, "Parce que je n'ai pas le droit ! Ici, seul le directeur du magasin peut baisser un prix. Il doit faire une demande au siège, et le siège doit la valider dans le système.",
    "그럴 권한이 없으니까요! 여기선 점장만 가격을 내릴 수 있어요. 점장이 본사에 요청하고, 본사가 시스템에서 승인해야 하죠."),
(MA, "Et la validation prend combien de temps ?", "그 승인은 얼마나 걸리나요?"),
(K, "Deux jours, parfois trois. Quand la réponse arrive, le produit est déjà périmé. Alors on a arrêté de demander.", "이틀, 가끔은 사흘이요. 답이 올 때쯤이면 제품은 이미 기한이 지났죠. 그래서 이젠 요청도 안 해요."),
(I, "Voilà ton mystère, Sofia : moins de cinq pour cent de rabais, parce que personne n'a le droit d'en faire.", "소피아, 네 미스터리가 풀렸네. 할인이 5%도 안 되는 건 아무도 할인할 권한이 없어서야."),
(MA, "Donc vous êtes obligés de jeter des produits que vous auriez pu vendre.", "그러니까 팔 수도 있었던 제품을 어쩔 수 없이 버리시는 거군요."),
(K, "Exactement. Dans mon ancien magasin, chez un concurrent, j'avais une étiqueteuse : moins trente pour cent à J-2, moins cinquante à J-1. On vendait presque tout.",
    "그렇죠. 예전에 경쟁사 매장에 있을 땐 가격 라벨기가 있었어요. 이틀 전엔 30%, 하루 전엔 50% 할인. 거의 다 팔았죠."),
(I, "Et les associations ? Créteil a bien une convention de don, non ?", "자선단체는요? 크레테유는 기부 협약이 있잖아요?"),
(K, "Oui, avec une épicerie solidaire. Mais ils passent seulement le mardi et le vendredi, et ils ne prennent que des produits qui ont encore au moins deux jours. Le reste de la semaine, je n'ai pas le choix.",
    "네, 연대 식료품점이랑요. 그런데 화요일과 금요일에만 오고, 날짜가 최소 이틀은 남은 제품만 가져가요. 나머지 요일엔 저도 어쩔 수가 없어요."),
(MA, "Et les commandes ? Vous recevez ce dont vous avez besoin ?", "발주는요? 필요한 만큼 받으시나요?"),
(K, "On reçoit ce que le siège décide. Regardez : trente packs familiaux de yaourts, alors que nos clients prennent des petits pots. Et jamais assez de plats préparés le week-end. Je l'ai signalé dix fois.",
    "본사가 정한 대로 받아요. 보세요, 가족용 요구르트 묶음이 서른 개예요. 우리 손님들은 낱개 작은 컵을 사 가는데. 그리고 주말엔 즉석식품이 늘 모자라요. 열 번은 보고했어요."),
(I, "Karim, si vous étiez directeur de Primavert pendant une journée, que feriez-vous en premier ?", "카림 씨, 하루 동안 프리마베르 대표가 된다면 제일 먼저 뭘 하시겠어요?"),
(K, "Je donnerais une étiqueteuse à chaque chef de rayon. Donnez-moi le droit de baisser les prix sur mon rayon, et je divise mes pertes par deux.",
    "매대 책임자마다 라벨기를 하나씩 줄 거예요. 제 매대에서 가격을 내릴 권한만 주세요. 그럼 손실을 반으로 줄일게요."),
(MA, "Vous savez que cette phrase va finir dans notre présentation ?", "그 말이 저희 발표 자료에 들어갈 거라는 거 아시죠?"),
(I, "Et cette fois, je vous promets que quelqu'un au siège va vous répondre.", "그리고 이번엔 본사의 누군가가 꼭 답을 할 거라고 약속드릴게요."),
(None, "8 h 30. Le magasin ouvre. Sofia est partie chercher des cafés. Sur le parking, Inès regarde la benne d'un air sombre.",
       "오전 8시 30분. 매장이 문을 연다. 소피아는 커피를 사러 갔다. 주차장에서 이네스가 어두운 얼굴로 컨테이너를 바라본다."),
(I, "Quatre-vingts kilos par jour, pour un seul magasin... Et moi qui voulais tout régler avec un algorithme.", "매장 하나에서 하루에 80킬로라니... 그런데 난 알고리즘 하나로 다 해결하려고 했지."),
(MA, "On aura besoin de l'algorithme aussi. Mais sans l'étiqueteuse de Karim, il ne servirait pas à grand-chose.", "알고리즘도 필요할 거야. 하지만 카림의 라벨기가 없으면 별 소용이 없겠지."),
(I, "D'accord, Strasbourg, tu as gagné celle-là. Mais pas un mot à Sofia : elle croit que je gagne toujours.", "알았어, 스트라스부르. 이번 판은 네가 이겼어. 그런데 소피아한텐 한마디도 하지 마. 내가 늘 이기는 줄 아니까."),
(MA, "Promis. Mais tu sais, perdre une fois de temps en temps, ça ne te va pas si mal.", "약속할게. 그런데 있잖아, 가끔 한 번씩 지는 것도 너한테 그렇게 안 어울리진 않아."),

# ---------- 5. Recommandations ----------
(None, "Trois semaines plus tard. Siège de Primavert, à Ivry. Autour de la table : Sylvie Moreau, Denis Lacour et Hélène Vasseur. Sofia s'occupe de l'ordinateur.",
       "3주 뒤. 이브리의 프리마베르 본사. 테이블에 실비 모로, 드니 라쿠르, 엘렌 바쇠르가 둘러앉아 있다. 소피아가 노트북을 맡았다."),
(I, "Madame Moreau, monsieur Lacour, nous allons commencer par un chiffre : quarante-cinq millions d'euros. C'est ce que Primavert jette chaque année. C'est le double de votre bénéfice net.",
    "모로 대표님, 라쿠르 이사님, 숫자 하나로 시작하겠습니다. 4,500만 유로. 프리마베르가 해마다 버리는 금액입니다. 순이익의 두 배죠."),
(MO, "Le double... Dit comme ça, c'est brutal.", "두 배라니... 그렇게 말하니 충격적이네요."),
(MA, "Mais ce n'est pas une fatalité. Nous avons trouvé trois causes, et aucune n'est la faute des employés des magasins.", "하지만 어쩔 수 없는 운명은 아닙니다. 원인을 세 가지 찾았는데, 어느 것도 매장 직원들 잘못이 아닙니다."),
(I, "Première cause : les commandes. Votre logiciel envoie presque les mêmes produits partout. Dans quarante pour cent de vos magasins, les commandes de frais dépassent les ventes de plus de quinze pour cent.",
    "첫 번째 원인은 발주입니다. 소프트웨어가 거의 같은 제품을 모든 매장에 보냅니다. 매장의 40%에서 신선식품 발주량이 판매량을 15% 넘게 초과합니다."),
(LA, "Le logiciel tient compte de la taille de chaque magasin !", "소프트웨어는 매장마다 크기를 고려합니다!"),
(MA, "De la taille, oui, mais pas des clients. Créteil reçoit des packs familiaux pour des étudiants et des retraités qui vivent seuls. Résultat : ils finissent à la benne.",
     "크기는 고려하죠. 하지만 고객은 고려하지 않습니다. 크레테유는 혼자 사는 학생과 은퇴자들을 위해 가족용 묶음을 받습니다. 결과는 컨테이너행이고요."),
(I, "D'où notre première recommandation : des commandes calculées magasin par magasin, à partir de leurs propres ventes. Sofia a construit un modèle et l'a testé sur l'historique de vingt magasins : les pertes de frais baisseraient de trente-cinq pour cent.",
    "그래서 첫 번째 권고는 매장별 자체 판매 데이터에 근거한 발주입니다. 소피아가 모델을 만들어 매장 20곳의 과거 데이터로 시험해 봤습니다. 신선식품 손실이 35% 줄어들 것으로 나옵니다."),
(LA, "Sur le papier. Et qui va le faire tourner, votre modèle ? Mon équipe informatique est déjà débordée.", "서류상으로는 그렇겠죠. 그 모델은 누가 돌립니까? 우리 IT팀은 이미 일에 치여 있어요."),
(SO, "Il ne remplace pas votre logiciel, il corrige seulement les quantités. Il faut environ deux semaines pour le brancher.", "기존 소프트웨어를 대체하는 게 아니라 수량만 보정해요. 연결하는 데 2주 정도면 돼요."),
(MA, "Deuxième cause, et c'est la plus surprenante : vos chefs de rayon n'ont pas le droit de baisser un prix. Une demande de rabais met deux à trois jours à être validée. Résultat : moins de cinq pour cent des produits jetés ont été soldés avant.",
     "두 번째 원인이 가장 놀랍습니다. 매대 책임자들에게 가격을 내릴 권한이 없습니다. 할인 요청 하나가 승인되는 데 2~3일이 걸립니다. 그래서 버려진 제품 중 사전에 할인된 건 5%도 안 됩니다."),
(MO, "C'est vrai, Denis ?", "사실이에요, 드니?"),
(LA, "C'est une règle de sécurité. Si chaque employé peut baisser les prix, il y aura des abus. Des fraudes, même.", "안전 규칙입니다. 직원마다 가격을 내릴 수 있으면 남용이 생길 겁니다. 부정행위까지도요."),
(MA, "Nous y avons pensé. Nous ne proposons pas de laisser chacun faire ce qu'il veut, mais d'appliquer des règles fixes : moins trente pour cent à J-2, moins cinquante à J-1, seulement sur le frais, avec une étiqueteuse reliée aux caisses. Chaque réduction est enregistrée.",
     "그 점도 고려했습니다. 각자 마음대로 하게 두자는 게 아니라, 정해진 규칙을 적용하자는 겁니다. 이틀 전 30%, 하루 전 50%, 신선식품에만, 계산대와 연결된 라벨기로요. 할인은 하나하나 기록됩니다."),
(I, "Vous gardez le contrôle, et vos magasins gagnent du temps. À Créteil, Karim nous a dit : « Donnez-moi le droit de baisser les prix, et je divise mes pertes par deux. »",
    "통제권은 그대로 유지하시고, 매장은 시간을 벌게 됩니다. 크레테유의 카림 씨가 이렇게 말했습니다. '가격을 내릴 권한만 주세요. 그럼 손실을 반으로 줄일게요.'"),
(LA, "Karim... Il m'a écrit dix fois à ce sujet. Je n'ai jamais répondu, je l'avoue.", "카림이라... 그 문제로 저한테 열 번은 메일을 썼죠. 한 번도 답을 안 했어요, 인정합니다."),
(MO, "Mais ces produits soldés ne vont-ils pas remplacer des ventes au prix normal ?", "그런데 할인 제품이 정상가 판매를 잠식하지 않을까요?"),
(I, "Un peu, sans doute. Mais aujourd'hui, ces produits ne vous rapportent rien : ils vous coûtent même la benne. Vendus à moitié prix, ils rapportent toujours plus que jetés.",
    "조금은 그렇겠죠. 하지만 지금 그 제품들은 한 푼도 벌어 주지 못합니다. 오히려 폐기 비용까지 듭니다. 반값에 팔아도 버리는 것보다는 언제나 낫습니다."),
(MA, "Troisième cause : la règle « date dépassée, produit jeté ». Dix-huit pour cent de vos pertes sont des produits avec une DDM, pas une DLC. Ils sont parfaitement mangeables. Cela représente environ huit millions d'euros par an.",
     "세 번째 원인은 '날짜 지나면 폐기'라는 규정입니다. 손실의 18%가 DLC가 아닌 DDM 제품입니다. 충분히 먹을 수 있는 것들이죠. 연간 약 800만 유로에 해당합니다."),
(MO, "Huit millions de produits que quelqu'un aurait pu manger...", "누군가 먹을 수 있었던 800만 유로어치 제품이라니..."),
(I, "C'est pourquoi nous recommandons une convention de don dans les cent quatre-vingts magasins d'ici six mois, avec des banques alimentaires et des épiceries solidaires, et des passages au moins quatre jours par semaine. Les produits dont la DDM est dépassée seront donnés, ou vendus dans un petit rayon « Encore bon ».",
    "그래서 6개월 안에 매장 180곳 모두가 푸드뱅크·연대 식료품점과 기부 협약을 맺고, 최소 주 4일 수거하도록 권고합니다. DDM이 지난 제품은 기부하거나 '아직 맛있어요' 소형 코너에서 판매합니다."),
(SO, "Nous avons aussi interrogé trois cents clients dans cinq magasins : plus de la moitié confondent la DLC et la DDM. Nous proposons des affiches simples pour leur expliquer la différence.",
     "매장 다섯 곳에서 고객 300명에게도 물어봤어요. 절반 이상이 DLC와 DDM을 헷갈려요. 차이를 설명하는 간단한 안내문을 제안해요."),
(MO, "Ça, c'est une histoire que je peux raconter aux journalistes. Bien mieux qu'un communiqué d'excuses.", "그거라면 기자들한테 들려줄 수 있는 이야기네요. 사과문보다 훨씬 낫죠."),
(LA, "Et combien va coûter tout ça ?", "그런데 이게 다 얼마나 듭니까?"),
(I, "Les étiqueteuses, le modèle et la logistique des dons : environ trois millions d'euros la première année. En face, nous visons des pertes ramenées de trois à un virgule huit pour cent du chiffre d'affaires en dix-huit mois. Soit dix-huit millions d'euros d'économies par an.",
    "라벨기, 모델, 기부 물류까지 첫해에 약 300만 유로입니다. 반면 18개월 안에 손실을 매출의 3%에서 1.8%로 낮추는 게 목표입니다. 연간 1,800만 유로 절감이죠."),
(MO, "Et si ça ne marche pas ?", "만약 효과가 없으면요?"),
(MA, "Alors on le saura vite. Nous proposons un pilote de trois mois dans vingt magasins, en commençant par Créteil. Si les résultats sont là, on l'étend à tout le réseau.",
     "그럼 금방 알게 될 겁니다. 크레테유를 시작으로 매장 20곳에서 3개월 시범 운영을 제안합니다. 성과가 나오면 전체 매장으로 확대하고요."),
(LA, "Vingt magasins, trois mois... D'accord. Mais je veux un rapport chaque semaine.", "20곳, 3개월이라... 좋습니다. 대신 매주 보고서를 받고 싶어요."),
(I, "Sofia s'en occupera. Chaque lundi matin, un tableau de bord dans votre boîte mail. Elle le fera mieux que moi.", "소피아가 맡을 겁니다. 매주 월요일 아침 대시보드가 메일함에 도착할 거예요. 저보다 잘할 거고요."),
(MO, "Alors c'est décidé. Je présenterai le plan au conseil le quinze. Et Denis, appelez Karim : je veux que ce soit lui qui forme les chefs de rayon du pilote.",
     "그럼 결정됐어요. 15일 이사회에 이 계획을 올리겠어요. 그리고 드니, 카림한테 전화해요. 시범 매장 매대 책임자 교육은 그 사람이 맡았으면 해요."),
(H, "Bravo à tous les trois. Et Sofia, pour un premier dossier, ce n'est pas mal du tout.", "셋 다 잘했어. 그리고 소피아, 첫 사건치고 아주 훌륭했어."),

# ---------- 6. Le soir : l'apéro ----------
(None, "Le soir même, 19 h. Un bar à vin au bord du canal Saint-Martin. Sur la table : trois verres et une planche de charcuterie et de fromages.",
       "그날 저녁 7시. 생마르탱 운하 옆 와인 바. 테이블 위엔 잔 세 개와 샤퀴트리·치즈 플레이트."),
(MA, "À notre premier dossier à trois ! Et à Karim, le héros de l'étiqueteuse !", "셋이 함께한 첫 사건을 위하여! 그리고 라벨기의 영웅 카림을 위하여!"),
(I, "À Sofia aussi. Sans ton camembert des DDM, on n'aurait jamais trouvé les huit millions.", "소피아를 위해서도. 네 DDM 원그래프가 없었으면 800만 유로는 절대 못 찾았을 거야."),
(SO, "Arrêtez, je vais rougir. Bon, c'est toujours comme ça chez Vasseur ? Des réveils à cinq heures et des apéros au bord du canal ?",
     "그만하세요, 얼굴 빨개지겠어요. 그런데 바쇠르에선 늘 이래요? 새벽 5시 기상에 운하 옆 아페로?"),
(I, "Toujours. Sauf quand on mange des pizzas froides au bureau à vingt-deux heures.", "늘. 밤 10시에 사무실에서 식은 피자 먹는 날만 빼고."),
(MA, "Bon, je vais chercher une autre planche. Il ne faut pas gaspiller, mais il ne faut pas mourir de faim non plus.", "자, 플레이트 하나 더 가져올게. 낭비하면 안 되지만 굶어 죽어서도 안 되니까."),
(None, "Mathieu se lève et va au comptoir. Sofia se penche vers Inès, les yeux brillants.", "마티외가 일어나 카운터로 간다. 소피아가 눈을 반짝이며 이네스 쪽으로 몸을 기울인다."),
(SO, "Dis-moi... Vous êtes ensemble, tous les deux ?", "있잖아요... 두 사람, 사귀어요?"),
(I, "Quoi ? Non ! Pas du tout. On est collègues. Binôme. C'est tout.", "뭐? 아니야! 전혀. 우린 동료야. 파트너. 그게 다야."),
(SO, "Ah bon ? Parce que vendredi, quand je suis revenue avec les cafés, sur le parking de Créteil, il te regardait comme Karim regarde une étiqueteuse.",
     "그래요? 금요일에 크레테유 주차장으로 커피 들고 돌아왔을 때, 마티외가 언니를 카림이 라벨기 보듯이 보던데요."),
(I, "N'importe quoi. Il regardait la benne, comme tout le monde.", "말도 안 돼. 다들 그랬듯이 컨테이너를 보고 있었던 거야."),
(SO, "Tu es toute rouge, Inès.", "얼굴 새빨개졌어요, 이네스."),
(I, "C'est le vin.", "와인 때문이야."),
(SO, "Tu en as bu un demi-verre. D'accord, d'accord, je ne dis plus rien. Mais je suis analyste : j'observe les données.", "반 잔 마셨잖아요. 알았어요, 알았어. 더는 말 안 할게요. 그래도 난 애널리스트라 데이터를 관찰하거든요."),
(None, "Mathieu revient avec une planche pleine.", "마티외가 가득 찬 플레이트를 들고 돌아온다."),
(MA, "Qu'est-ce que j'ai raté ? Vous avez l'air de comploter.", "내가 뭘 놓쳤어? 둘이 뭔가 꾸미는 얼굴인데."),
(SO, "Rien ! On parlait de dates limites. De ce qui se garde... et de ce qui ne se garde pas.", "아무것도요! 유통기한 얘기 중이었어요. 오래 가는 것과... 오래 못 가는 것에 대해서요."),
(I, "Sofia... Bon, Strasbourg, sors ton marqueur vert. Sofia ne connaît pas encore les trois questions.", "소피아... 자, 스트라스부르, 초록 마커 꺼내. 소피아는 아직 세 가지 질문을 몰라."),
(None, "Mathieu écrit sur une serviette en papier avec son vieux marqueur vert.", "마티외가 낡은 초록 마커로 종이 냅킨에 적는다."),
(MA, "Mon grand-père disait : « Quel est le vrai problème ? Qui décide ? Que fait-on lundi ? » Chez Primavert, le vrai problème, c'était des règles qui empêchaient les gens de bien faire.",
     "우리 할아버지가 그러셨지. '진짜 문제는 무엇인가? 누가 결정하는가? 월요일엔 무엇을 하는가?' 프리마베르의 진짜 문제는 사람들이 제대로 일하지 못하게 막는 규칙이었어."),
(SO, "J'adore. Alors, que fait-on lundi ? Moi, je branche le modèle sur les vingt magasins pilotes.", "너무 좋아요. 그럼 월요일엔 뭘 하죠? 저는 시범 매장 20곳에 모델을 연결하고요."),
(I, "Et nous, on s'envole pour Nice. Hélène vient de m'écrire : une compagnie aérienne régionale dont les avions ne sont jamais à l'heure.",
    "우리는 니스로 날아가. 엘렌이 방금 문자 보냈어. 비행기가 한 번도 제시간에 뜨지 않는 지역 항공사래."),
(MA, "Des avions en retard... Je prendrai un bon livre. Et cette fois, Inès, c'est moi qui choisis les places.", "지연되는 비행기라... 좋은 책 한 권 챙겨야겠네. 그리고 이번엔, 이네스, 자리는 내가 고를 거야."),
(I, "Les places, on en reparlera. En attendant, je te rappelle que tu me dois toujours un café.", "자리는 나중에 다시 얘기하자. 그 전에, 너 아직 나한테 커피 한 잔 빚진 거 잊지 마."),
]

VOCAB = [
("B1", "faire son marché", "(시장에서) 장을 보다", "faire les courses(장보기 일반)보다 '시장에서 신선식품을 사다'의 뉘앙스. Le samedi, je fais mon marché."),
("B1", "un étal", "(시장의) 좌판, 진열대", "복수 étals. 생선·고기·채소 상인의 판매대. un étal de légumes."),
("B1", "Qu'est-ce que je vous mets ?", "뭘 드릴까요?", "시장 상인의 단골 표현. 단골에게는 Qu'est-ce que je te mets ? 직역은 '무엇을 (봉지에) 넣어 드릴까요'."),
("B1", "une livre (de)", "500그램", "시장에서 흔히 쓰는 옛 단위. une livre de champignons. 여성명사 livre(파운드)와 남성명사 livre(책)를 구분."),
("B1", "une botte (de radis)", "(채소의) 단", "une botte de radis / de persil. 신발 '부츠'와 같은 단어."),
("B1", "tout rond", "딱 떨어지게, 우수리 없이", "quinze euros tout rond = 딱 15유로. 상인이 끝자리를 깎아 줄 때."),
("B2", "vider un poisson", "생선 내장을 손질하다", "vider = 비우다. Je vous les vide ? 생선가게에서 손질을 부탁할 때 쓰는 말."),
("B2", "passer son chemin", "그냥 지나가다, 상관하지 않다", "Si ton doigt laisse une marque, tu passes ton chemin. 거래나 제안을 포기할 때도 씀."),
("B2", "brader", "헐값에 팔다, 떨이로 팔다", "명사 braderie(벼룩시장, 할인 장터). 릴의 Grande Braderie가 유명."),
("B1", "la grande distribution", "대형 유통(업)", "슈퍼마켓·하이퍼마켓 체인을 통틀어 이르는 말. travailler dans la grande distribution."),
("B1", "une enseigne", "(유통) 체인, 상호", "원래 '간판'. 소매업에서는 브랜드·체인 자체를 가리킨다. une enseigne de proximité(동네 체인)."),
("B2", "le gaspillage alimentaire", "음식물 낭비, 식품 폐기", "gaspiller = 낭비하다. la lutte contre le gaspillage alimentaire. zéro gaspillage."),
("B2", "une benne", "대형 쓰레기 컨테이너", "매장 뒤에 있는 대형 수거함. partir à la benne = 버려지다(구어)."),
("B2", "une convention de don", "기부 협약", "매장과 자선단체가 맺는 공식 협약. signer / proposer une convention."),
("B2", "une association habilitée", "인가받은 단체", "habiliter = 권한을 부여하다. 식품 기부를 받을 자격을 갖춘 단체."),
("B1", "la DLC / la DDM", "소비기한 / 품질유지기한", "date limite de consommation(« à consommer jusqu'au ») vs date de durabilité minimale(« à consommer de préférence avant »)."),
("B1", "périmé, -e", "기한이 지난", "유통기한·서류 모두에 사용. un passeport périmé(만료된 여권)."),
("B2", "impropre à la consommation", "섭취에 부적합한", "법률 문서 표현. rendre un produit impropre à la consommation = 못 먹게 만들다."),
("B2", "la mise en rayon", "(상품) 진열 작업", "rayon = 매대·코너. le rayon frais(신선식품 코너), en rayon(진열된)."),
("B2", "à J-2 / à J-1", "D-2 / D-1에", "J = jour. 날짜·마감 기준 역산. Le jour J = 디데이."),
("B2", "une étiqueteuse", "가격 라벨기", "étiquette(라벨·딱지) + -euse(기계). une étiquette de réduction(할인 스티커)."),
("B1", "Ça tombe bien.", "마침 잘됐다", "타이밍이 딱 맞을 때. ↔ Ça tombe mal.(하필 이럴 때)"),
("B2", "mot pour mot", "한 글자도 틀리지 않고", "인용·추측이 정확히 맞았을 때. répéter mot pour mot."),
("C1", "ce n'est pas une fatalité", "피할 수 없는 운명은 아니다", "fatalité = 숙명. 문제 제기 후 해결 가능성을 열 때 쓰는 연설·발표 단골 표현."),
("B2", "un tableau de bord", "대시보드, 계기판", "경영 지표를 한눈에 보는 보고서. 자동차 계기판에서 유래."),
]

GRAM = [
("B1", "의무 표현 ①: devoir / il faut / être obligé de",
 "« Nous devons le retirer du rayon. » « Il faut attaquer la cause principale. » « Vous êtes obligés de jeter des produits... » devoir + 부정사는 가장 일반적인 의무, il faut + 부정사는 주어 없이 '~해야 한다'(일반적 필요), être obligé de는 '어쩔 수 없이 ~하다'라는 강제의 뉘앙스가 강하다. 주어를 밝히려면 il faut que + 접속법: « Il faut que je la remplisse. »"),
("B2", "의무 표현 ②: 법·규정의 문장",
 "« La loi oblige tout supermarché de plus de quatre cents mètres carrés à proposer une convention de don. » obliger qn à + 부정사(누구에게 ~할 의무를 지우다)와 être obligé de의 전치사 차이(à / de)에 주의. 금지는 il est interdit de + 부정사: « Il leur est interdit de rendre des invendus impropres à la consommation. » 권한은 avoir le droit de: « Je n'ai pas le droit ! » « On n'a plus le droit de le vendre. »"),
("B1", "수량 표현: 단위, 단가, 분수",
 "« Un kilo de pommes de terre, une botte de radis, une livre de champignons. » 수량 명사 뒤에는 관사 없이 de. 단가는 정관사: « vingt-deux euros le kilo ». 분수와 비율: « À peine plus d'un tiers. » « Plus de la moitié confondent la DLC et la DDM. »(la moitié 뒤에 복수 명사가 생략되면 동사는 복수로 일치) « trois pour cent de son chiffre d'affaires »."),
("B1", "대명사 en: 수량과 함께",
 "« Il m'en faudrait deux. » « Combien de vos magasins en ont une ? » « Le quinzième en manque. »(manquer de qc → en) « Personne n'a le droit d'en faire. » en은 de + 명사, 또는 수량 표현과 함께 쓰인 명사를 받는다. 수사(deux, une)는 동사 뒤에 그대로 남는다."),
("B2", "ce que / ce dont: 동사의 구조에 따라",
 "« Vous recevez ce dont vous avez besoin ? » « On reçoit ce que le siège décide. » « Ce qui reste, Jojo le brade. » 관계절 안의 동사가 직접목적어를 가지면 ce que, 주어가 필요하면 ce qui, de를 요구하면(avoir besoin de, parler de) ce dont을 쓴다."),
("B2", "조건법 과거: 놓친 가능성과 아쉬움",
 "« Vous êtes obligés de jeter des produits que vous auriez pu vendre. » « Huit millions de produits que quelqu'un aurait pu manger... » « Sans ton camembert, on n'aurait jamais trouvé les huit millions. » pouvoir의 조건법 과거(aurait pu + 부정사)는 '~할 수도 있었는데'라는 놓친 가능성을 말한다. sans + 명사는 si 절(si tu n'avais pas fait...)을 대신한다."),
("B2", "제한 표현: seul / ne... que / seulement",
 "« Seul le directeur du magasin peut baisser un prix. » « Seuls soixante-deux ont une convention active. » « Ils ne prennent que des produits qui ont encore au moins deux jours. » « Ils passent seulement le mardi et le vendredi. » 문두의 seul은 명사와 성·수가 일치한다(seul le directeur, seuls soixante-deux). ne... que는 제한하는 말 바로 앞에 que를 둔다."),
("B2", "사역 구문 faire + 부정사",
 "« Elle fait parler les données mieux que personne. » « Qui va le faire tourner, votre modèle ? » faire + 부정사는 '~하게 만들다'. 목적어가 명사면 부정사 뒤에(faire parler les données), 대명사면 faire 앞에 온다(le faire tourner). 비즈니스에서 faire tourner(가동하다), faire passer(전달하다)는 매우 자주 쓰인다."),
]

CULTURE = [
("프랑스의 식품 폐기 방지법",
 "프랑스는 2016년 2월 '식품 낭비 방지법'(발의자 이름을 따 loi Garot라고 부름)을 제정했다. 판매 면적 400㎡가 넘는 식품 소매점은 인가받은 자선단체에 기부 협약을 제안해야 하고, 아직 먹을 수 있는 재고를 락스 등으로 일부러 못 먹게 만드는 행위는 금지되며 벌금이 부과된다. 법은 예방 → 기부·가공 → 동물 사료 → 퇴비·에너지화(메탄화) 순서의 우선순위를 제시했고, 이후 법 개정으로 의무 대상이 단체 급식과 식품 산업 등으로 넓어졌다."),
("DLC와 DDM 구별하기",
 "포장 식품의 날짜 표시는 두 가지다. DLC(« à consommer jusqu'au... »)는 고기·생선·신선 유제품처럼 상하기 쉬운 식품에 붙으며, 날짜가 지나면 판매도 기부도 할 수 없다. DDM(« à consommer de préférence avant... », 예전 명칭 DLUO)은 커피·파스타·비스킷 같은 식품에 붙으며, 날짜가 지나도 맛과 질감이 조금 떨어질 뿐 판매와 기부가 가능하다. 프랑스 가정의 음식물 낭비 상당 부분이 이 두 날짜를 혼동하는 데서 생긴다고 알려져 있어, 유통업체와 정부가 소비자 안내를 강화하고 있다."),
("알리그르 시장과 파리의 마르셰",
 "12구의 알리그르 시장(marché d'Aligre)은 파리에서 물가가 싸기로 손꼽히는 시장으로, 월요일을 제외한 매일 오전 노천 좌판이 열리고 옆에는 18세기에 기원을 둔 실내 시장 marché Beauvau가 있다. 파리의 시장 상인들은 단골에게 tu로 말을 걸고 큰 소리로 값을 외치며, 장이 파할 무렵(la fin du marché)에는 남은 물건을 싸게 넘기는 경우가 많다. 생선은 눈이 볼록하고 맑은지, 아가미가 선홍색인지, 살이 탄력 있는지를 보고 고르며, 손질(vider, écailler)을 부탁하면 대개 무료로 해 준다."),
]
