# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, S = "Inès", "Mathieu", "Sofia"
DE, EB, PT = "Delorme", "Élodie", "Patrice"
AN, PA = "Annonce", "Passagère"

META = {
    "part": 1, "ep": 5,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "Retards en cascade",
    "title_ko": "연쇄 지연",
    "place": "오를리 공항 탑승구 · 니스 공항 아쥐레아 본사 · Vasseur & Associés · 아쥐레아 운항통제센터 · 니스 앙글레 산책로 / 11월~12월 초, 약 3주간",
    "chars": "이네스, 마티외, 소피아, 마르크 들로름(아쥐레아 대표), 엘로디 브룅(운항통제센터장), 파트리스(승무원 스케줄 담당), 승객, 공항 안내 방송",
    "work": "니스의 지역 항공사 아쥐레아 — 정시 운항률 61%, 하루 종일 이어지는 연쇄 지연, 예비기 매각, 수익 관리 부재, 3년 연속 적자",
    "life": "오를리 공항에서 1시간 지연된 비행기, 관제사 파업으로 니스에 발이 묶인 밤, 앙글레 산책로에서 나눈 첫 속 깊은 대화",
    "focus": "공항·비행 어휘, 시간·지연 표현(être en retard, avoir du retard, être annulé), 그래프 묘사, plus... plus..., 반과거와 복합과거의 서술, 대과거",
    "levelmix": "B1 45% · B2 50% · C1 5%",
    "next": "제6화 Brûler du cash — 매달 120만 유로를 태우는 핀테크 스타트업, 그리고 마티외의 원룸 집들이.",
}

D = [
# ---------- 1. Ouverture : la porte d'embarquement ----------
(None, "Un lundi de novembre, 7 h 35. Aéroport d'Orly, porte 32. Les passagers du vol Azuréa pour Nice attendent, valise à la main. Inès et Mathieu sont assis près de la baie vitrée.",
       "11월의 어느 월요일, 오전 7시 35분. 오를리 공항 32번 탑승구. 아쥐레아 니스행 승객들이 가방을 든 채 기다리고 있다. 이네스와 마티외는 통유리창 옆에 앉아 있다."),
(AN, "Mesdames et messieurs, Azuréa vous informe que le vol ZR 412 à destination de Nice partira avec un retard estimé à une heure. Nous vous prions de nous excuser pour ce désagrément.",
     "승객 여러분, 아쥐레아에서 알려 드립니다. 니스행 ZR 412편은 약 1시간 지연 출발할 예정입니다. 불편을 드려 죄송합니다."),
(PA, "Encore ! La semaine dernière, c'était deux heures. Cette compagnie, c'est une catastrophe.", "또야! 지난주엔 두 시간이었는데. 이 항공사는 정말 최악이야."),
(MA, "Une heure de retard... et c'est notre client. On commence bien.", "1시간 지연이라... 그것도 우리 고객사가. 시작 한번 좋네."),
(I, "Au contraire, c'est parfait : c'est notre première observation de terrain. Note l'heure, Strasbourg. Départ prévu à 7 h 40, estimé à 8 h 40.",
    "오히려 완벽해. 첫 번째 현장 관찰이잖아. 시간 적어 둬, 스트라스부르. 출발 예정 7시 40분, 예상 8시 40분."),
(MA, "Noté. Excusez-moi, madame, vous prenez souvent cette ligne ?", "적었어. 실례지만, 이 노선 자주 타세요?"),
(PA, "Toutes les semaines, pour mon travail. Avant, je prenais le train. L'avion était censé être plus rapide... Tu parles !", "매주요, 일 때문에. 예전엔 기차를 탔어요. 비행기가 더 빠를 거라고 했는데... 퍽이나요!"),
(MA, "Et les retards, c'est surtout le matin ?", "지연은 주로 아침에 있나요?"),
(PA, "Le matin, ça va encore. Le soir, c'est pire : le dernier vol pour Paris a souvent deux ou trois heures de retard. Une fois, il a même été annulé.",
     "아침엔 그나마 나아요. 저녁이 더 심해요. 파리행 마지막 비행기는 툭하면 두세 시간씩 늦어요. 한 번은 아예 취소되기도 했고요."),
(I, "Merci, madame. Vous venez de nous donner notre première hypothèse.", "감사합니다. 덕분에 첫 번째 가설이 생겼어요."),
(None, "La passagère s'éloigne en haussant les épaules.", "승객은 어깨를 으쓱하며 멀어진다."),
(MA, "Bon, une heure à tuer. Je vais chercher des cafés. Ça compte pour ma dette ?", "자, 한 시간이나 때워야 하네. 커피 사 올게. 이거 내 빚으로 쳐 줘?"),
(I, "Un café d'aéroport à quatre euros cinquante dans un gobelet en carton ? Certainement pas. Ta dette mérite mieux que ça.", "종이컵에 담긴 4유로 50센트짜리 공항 커피로? 어림없지. 네 빚은 그보다 나은 대접을 받아야 해."),
(MA, "Tu es dure en affaires. Et si j'ajoute un croissant ?", "협상에 정말 짜다. 크루아상을 얹으면?"),
(I, "Tu me dois déjà un croissant. Celui-là, tu me l'offres en plus, par pure gentillesse.", "크루아상은 이미 하나 빚졌잖아. 이건 순전히 친절로 덤으로 사 주는 거야."),
(MA, "Par pure gentillesse... D'accord. Et toi, pendant ce temps, tu relis le dossier Azuréa pour la dixième fois ?", "순전히 친절로라... 알았어. 그동안 넌 아쥐레아 자료를 열 번째 읽는 거고?"),
(I, "La onzième. Quatorze avions, soixante et un pour cent de ponctualité, trois ans de pertes. Je veux arriver à Nice en sachant déjà tout.",
    "열한 번째. 항공기 14대, 정시 운항률 61%, 3년 연속 적자. 니스에 도착할 때 이미 다 알고 있고 싶어."),

# ---------- 2. Briefing et client ----------
(None, "11 h 45. Siège d'Azuréa, au bord des pistes de l'aéroport de Nice. Par la fenêtre, un avion décolle au-dessus de la mer.",
       "오전 11시 45분. 니스 공항 활주로 옆 아쥐레아 본사. 창밖으로 비행기 한 대가 바다 위로 이륙한다."),
(DE, "Madame Marchetti, monsieur Kessler, bienvenue ! Vous êtes venus avec notre vol de 7 h 40, je crois ?", "마르케티 씨, 케슬레르 씨, 어서 오세요! 저희 7시 40분 비행기로 오셨죠?"),
(I, "Avec celui de 7 h 40, oui. Nous avons atterri à 10 h 25, avec une heure et cinq minutes de retard.", "네, 7시 40분 편으로요. 1시간 5분 늦게, 10시 25분에 착륙했습니다."),
(DE, "Aïe. Je vois que l'audit a déjà commencé. Je vous présente Élodie Brun, qui dirige notre centre de contrôle des opérations.", "아이고. 감사가 벌써 시작됐군요. 운항통제센터를 이끄는 엘로디 브룅을 소개합니다."),
(EB, "Bonjour. Si vous voulez savoir pourquoi votre avion était en retard, c'est à moi qu'il faut le demander. Je l'ai suivi minute par minute.",
     "안녕하세요. 비행기가 왜 늦었는지 알고 싶으시면 저한테 물어보셔야 해요. 제가 분 단위로 지켜봤거든요."),
(MA, "Justement : pourquoi ?", "그럼 바로 여쭤볼게요. 왜죠?"),
(EB, "L'avion a passé la nuit à Orly. Mais hier soir, son équipage a atterri avec deux heures de retard. Avec le temps de repos obligatoire, il ne pouvait pas repartir avant 8 h 30.",
     "비행기는 오를리에서 밤을 보냈어요. 그런데 어젯밤 그 승무원들이 두 시간 늦게 착륙했죠. 의무 휴식 시간 때문에 8시 30분 전에는 다시 출발할 수 없었어요."),
(I, "Donc le retard d'hier soir a provoqué le retard de ce matin.", "그러니까 어젯밤 지연이 오늘 아침 지연을 낳은 거군요."),
(EB, "Exactement. Chez nous, les retards ne disparaissent jamais. Ils se transmettent d'un vol à l'autre, comme un virus.", "바로 그거예요. 우리 회사에선 지연이 절대 사라지지 않아요. 바이러스처럼 이 비행에서 저 비행으로 옮겨 가죠."),
(DE, "Élodie dramatise un peu. Mais oui, nous avons un problème de ponctualité. Soixante et un pour cent de nos vols partent à l'heure, c'est-à-dire avec moins de quinze minutes de retard. Nos concurrents sont autour de soixante-dix-huit.",
     "엘로디가 좀 과장하는 거예요. 하지만 네, 정시성에 문제가 있습니다. 우리 항공편의 61%가 정시에, 즉 15분 미만 지연으로 출발합니다. 경쟁사들은 78% 안팎이고요."),
(MA, "Et cela vous coûte cher ?", "그게 비용이 많이 드나요?"),
(DE, "Très cher. L'an dernier, nous avons fait deux cent quarante millions d'euros de chiffre d'affaires et nous avons perdu dix-huit millions. C'est notre troisième année de pertes.",
     "아주 많이요. 작년 매출이 2억 4,000만 유로였는데 1,800만 유로 손실을 봤어요. 3년째 적자입니다."),
(I, "Comment votre activité est-elle organisée ?", "사업은 어떻게 구성되어 있나요?"),
(DE, "Quatorze avions : quatre Airbus pour la ligne de Paris, dix ATR pour la Corse, Lyon, Bordeaux et Genève. Environ quatre-vingts vols par jour et deux millions de passagers par an.",
     "항공기 14대입니다. 파리 노선에 에어버스 4대, 코르시카·리옹·보르도·제네바에 ATR 10대. 하루 약 80편, 연간 승객 200만 명이에요."),
(MA, "Selon vous, monsieur Delorme, d'où viennent ces retards ?", "들로름 대표님 생각엔 이 지연들이 어디서 온다고 보세요?"),
(DE, "De partout, sauf de chez nous ! Le contrôle aérien, la météo, les grèves, la saturation d'Orly... Nous sommes une petite compagnie : nous subissons.",
     "우리 빼고 사방에서요! 항공 관제, 날씨, 파업, 오를리 포화... 우린 작은 항공사예요. 당할 수밖에 없죠."),
(None, "Élodie Brun secoue la tête.", "엘로디 브룅이 고개를 젓는다."),
(I, "Madame Brun, vous n'avez pas l'air d'accord. Nous aimerions entendre votre point de vue.", "브룅 센터장님, 동의하지 않으시는 것 같네요. 센터장님 의견을 듣고 싶습니다."),
(EB, "D'après nos propres codes de retard, les causes extérieures représentent environ un tiers des minutes perdues. Près de la moitié, ce sont des retards en cascade : un avion part en retard parce que le vol précédent est arrivé en retard. Le reste, ce sont des problèmes d'escale.",
     "우리 지연 코드를 보면 외부 원인은 손실된 시간의 약 3분의 1이에요. 거의 절반은 연쇄 지연이죠. 앞 비행편이 늦게 도착해서 다음 비행기가 늦게 출발하는 거요. 나머지는 지상 조업 문제고요."),
(MA, "Des problèmes d'escale, c'est-à-dire ?", "지상 조업 문제라면 어떤 거죠?"),
(EB, "L'embarquement, les bagages, le nettoyage. Avec seulement vingt-cinq minutes entre l'arrivée et le départ, la moindre valise oubliée devient un retard.",
     "탑승, 수하물, 기내 청소요. 도착과 출발 사이가 25분밖에 안 되니까, 가방 하나만 잊혀도 지연이 돼요."),
(I, "Vingt-cinq minutes au sol, c'est très court, non ?", "지상 체류 25분이면 아주 짧은 거 아닌가요?"),
(DE, "C'est le standard des compagnies low cost. Un avion gagne de l'argent quand il vole, pas quand il attend sur un parking.", "저가 항공사들의 기준이에요. 비행기는 날 때 돈을 벌지, 주기장에서 기다릴 때 버는 게 아니니까요."),
(MA, "Et quand un avion tombe en panne ? Vous avez un avion de réserve ?", "그럼 비행기가 고장 나면요? 예비기는 있나요?"),
(DE, "Nous en avions un. Il y a deux ans, nous l'avons vendu sept millions d'euros. Un avion qui reste au sol en attendant une panne, c'était un luxe que nous ne pouvions plus nous offrir.",
     "있었죠. 2년 전에 700만 유로에 팔았습니다. 고장을 기다리며 땅에 서 있는 비행기는 더 이상 감당할 수 없는 사치였어요."),
(I, "Une dernière question, sur les prix. Comment fixez-vous vos tarifs ?", "마지막으로 가격에 대해 여쭤볼게요. 요금은 어떻게 정하시나요?"),
(DE, "Nous avons une grille par saison, établie en janvier. C'est simple et lisible pour nos clients.", "1월에 정하는 시즌별 요금표가 있어요. 고객들에게 단순하고 알기 쉽죠."),
(I, "Donc un billet pour le 15 août coûte le même prix, qu'on l'achète six mois avant ou la veille ?", "그러니까 8월 15일 항공권은 6개월 전에 사든 전날 사든 가격이 같다는 거죠?"),
(DE, "À peu près, oui. Pourquoi ? C'est un problème ?", "대체로 그렇죠. 왜요? 그게 문제인가요?"),
(MA, "C'est peut-être une partie de la réponse. Pourriez-vous nous envoyer vos données de vols sur deux ans ? Horaires prévus, horaires réels, causes de retard, remplissage et prix.",
     "그게 답의 일부일 수도 있습니다. 2년 치 운항 데이터를 보내 주시겠어요? 예정 시각, 실제 시각, 지연 원인, 탑승률, 가격까지요."),
(EB, "Je vous prépare tout ça ce soir. Mais je vous préviens : ça fait cent mille lignes.", "오늘 밤에 다 준비해 드릴게요. 그런데 미리 말씀드리면 10만 줄이에요."),
(I, "Parfait. Nous avons au bureau quelqu'un qui adore les fichiers de cent mille lignes.", "완벽해요. 사무실에 10만 줄짜리 파일을 아주 좋아하는 사람이 있거든요."),

# ---------- 3. Analyse ----------
(None, "Mercredi, 15 h. Vasseur & Associés, salle « Monceau ». Sofia a projeté un graphique sur l'écran.", "수요일 오후 3시. 바쇠르 & 어소시에이츠 '몽소' 회의실. 소피아가 화면에 그래프를 띄워 놓았다."),
(S, "Accrochez-vous. J'ai nettoyé les cent mille lignes d'Élodie Brun. Cette courbe, c'est le taux de ponctualité heure par heure.", "꽉 잡으세요. 엘로디 브룅의 10만 줄을 정리했어요. 이 곡선이 시간대별 정시 운항률이에요."),
(I, "Elle commence très haut et elle descend toute la journée.", "아주 높게 시작해서 하루 종일 내려가네."),
(S, "Voilà. À sept heures, quatre-vingt-huit pour cent des vols partent à l'heure. À midi, on tombe à soixante-quatre. Et après dix-huit heures, la courbe chute : trente-huit pour cent seulement.",
    "그렇죠. 7시엔 88%가 정시 출발해요. 정오엔 64%로 떨어지고요. 그리고 오후 6시 이후엔 곡선이 급락해요. 겨우 38%예요."),
(MA, "Plus la journée avance, plus le retard s'accumule. C'est bien une cascade.", "하루가 지날수록 지연이 더 쌓이는구나. 정말 연쇄 지연이네."),
(S, "Exactement. En moyenne, le premier vol de la journée part avec huit minutes de retard. Au sixième vol, l'avion en a quarante-sept. Il ne rattrape jamais son retard.",
    "맞아요. 평균적으로 하루 첫 편은 8분 늦게 출발해요. 여섯 번째 편이 되면 47분 늦고요. 지연을 절대 만회하지 못해요."),
(I, "Forcément, avec vingt-cinq minutes au sol, il n'y a aucune marge pour rattraper quoi que ce soit.", "당연하지. 지상 체류가 25분이면 뭘 만회할 여유가 전혀 없어."),
(MA, "Et derrière la moyenne de soixante et un pour cent, Sofia, qu'est-ce qui se cache ?", "소피아, 61%라는 평균 뒤에는 또 뭐가 숨어 있어?"),
(S, "De grosses différences entre les lignes. La Corse, c'est la pire : du vent, de petits aéroports. Paris, c'est moyen. Genève, presque parfait.", "노선 간 차이가 커요. 코르시카가 최악이에요. 바람도 세고 공항도 작고요. 파리는 중간, 제네바는 거의 완벽해요."),
(I, "Et la partie que j'attendais : les prix. Qu'est-ce que tu as trouvé ?", "이제 내가 기다리던 부분, 가격. 뭘 찾았어?"),
(S, "Quelque chose de bizarre. En août, le taux de remplissage est de quatre-vingt-quatorze pour cent, mais le billet moyen coûte quatre-vingt-neuf euros. Chez les concurrents, cent trente-cinq. Et en novembre, les avions sont à moitié vides.",
    "좀 이상한 거요. 8월엔 탑승률이 94%인데 평균 항공권 가격이 89유로예요. 경쟁사는 135유로고요. 그리고 11월엔 비행기가 반쯤 비어 있어요."),
(I, "Je le savais. Ils vendent leurs billets d'été en février au prix de l'hiver. Tout part en quelques semaines, et ensuite ils refusent des clients prêts à payer le double.",
    "그럴 줄 알았어. 여름 항공권을 2월에 겨울 가격으로 파는 거야. 몇 주 만에 다 팔리고, 그다음엔 두 배를 낼 준비가 된 손님들을 돌려보내는 거지."),
(MA, "Le double, vraiment ?", "두 배? 정말?"),
(I, "Bien sûr. Quelqu'un qui doit aller à Paris le 14 août pour un enterrement paiera deux cents euros sans discuter. Avec une vraie gestion des recettes, Azuréa pourrait gagner six pour cent de chiffre d'affaires.",
    "당연하지. 장례식 때문에 8월 14일에 파리에 가야 하는 사람은 군말 없이 200유로를 낼 거야. 제대로 된 수익 관리만 하면 아쥐레아는 매출을 6% 늘릴 수 있어."),
(MA, "Six pour cent de deux cent quarante millions... ça fait à peu près quatorze millions.", "2억 4,000만의 6%면... 대략 1,400만이네."),
(I, "Quatorze millions quatre cent mille. Presque toute la perte. Voilà notre solution.", "1,440만. 손실을 거의 다 메워. 이게 우리 해결책이야."),
(MA, "Attends. Tu veux vendre plus cher des billets pour des avions qui arrivent en retard ? Les clients vont exploser.", "잠깐. 늦게 도착하는 비행기 표를 더 비싸게 팔겠다고? 손님들이 폭발할 거야."),
(I, "Ils explosent déjà. Au moins, l'entreprise survivra.", "이미 폭발하고 있어. 적어도 회사는 살아남겠지."),
(MA, "Non. Si on ne règle pas les retards, les clients partiront chez les concurrents ou reprendront le train. Le problème numéro un, c'est la ponctualité.",
     "아니야. 지연을 해결하지 않으면 손님들은 경쟁사로 가거나 다시 기차를 탈 거야. 1순위 문제는 정시성이야."),
(I, "Et pour la ponctualité, tu proposes quoi ? Allonger les escales ? Chaque minute au sol, ce sont des vols en moins, donc des recettes en moins.", "그럼 정시성을 위해 뭘 제안하는데? 지상 체류를 늘려? 땅에 있는 1분 1분이 비행편 감소고, 그건 곧 수입 감소야."),
(MA, "Peut-être deux vols de moins par jour. Mais des avions à l'heure, des équipages reposés, des passagers qui reviennent.", "하루에 두 편쯤 줄겠지. 대신 제시간에 뜨는 비행기, 푹 쉰 승무원, 다시 돌아오는 승객이 생겨."),
(I, "« Peut-être », « des passagers qui reviennent »... Tu me donnes des intentions, Strasbourg. Moi, je te donne quatorze millions.", "'아마', '돌아오는 승객'... 넌 나한테 의도를 주고 있어, 스트라스부르. 난 너한테 1,400만을 주고 있고."),
(MA, "Et moi, je te pose une question : quel est le vrai problème ? Le prix ou le retard ?", "그럼 난 질문 하나 할게. 진짜 문제는 뭐야? 가격이야, 지연이야?"),
(I, "... Les deux. Ne m'oblige pas à choisir.", "...둘 다. 고르라고 하지 마."),
(S, "Euh... je peux dire quelque chose ? Vous vous disputez comme un vieux couple.", "저기... 한마디 해도 돼요? 두 분 꼭 오래된 부부처럼 싸우시네요."),
(I, "Sofia !", "소피아!"),
(S, "Pardon, pardon ! J'ai encore une info. Ce qui fait le plus mal, ce ne sont pas les petits retards, ce sont les annulations. Quand un avion tombe en panne, quatre ou cinq vols sautent dans la journée.",
    "죄송, 죄송해요! 정보가 하나 더 있어요. 제일 아픈 건 작은 지연이 아니라 결항이에요. 비행기 한 대가 고장 나면 그날 네다섯 편이 날아가요."),
(I, "Parce qu'il n'y a plus d'avion de réserve. Delorme l'a vendu sept millions. Sur le papier, c'était une économie raisonnable.", "예비기가 없으니까. 들로름이 700만에 팔았지. 서류상으론 합리적인 절감이었어."),
(MA, "Sur le papier. Je voudrais voir ce que ça donne dans la réalité. On retourne à Nice, au centre de contrôle des opérations.", "서류상으론. 현실에선 어떤지 보고 싶어. 니스 운항통제센터로 다시 가자."),
(I, "Lundi, six heures du matin, pour la première vague de départs. Je veux voir la cascade commencer.", "월요일 새벽 6시, 첫 출발 물결에 맞춰서. 연쇄 지연이 시작되는 걸 보고 싶어."),
(S, "Six heures ? Amusez-vous bien, tous les deux. Moi, je garde le bureau... et vos secrets.", "6시요? 두 분 재밌게 다녀오세요. 저는 사무실이랑... 두 분 비밀을 지키고 있을게요."),

# ---------- 4. Terrain : le centre de contrôle ----------
(None, "Lundi suivant, 5 h 45. Centre de contrôle des opérations d'Azuréa, aéroport de Nice. Des écrans partout, des téléphones qui sonnent déjà. Dehors, il fait encore nuit.",
       "다음 주 월요일, 새벽 5시 45분. 니스 공항 아쥐레아 운항통제센터. 사방에 모니터, 벌써 울리는 전화들. 밖은 아직 깜깜하다."),
(EB, "Bienvenue dans la tour de contrôle des retards. Ici, on suit les quatorze avions et tous les équipages, jour et nuit. Entre six et sept heures, c'est la première vague : treize avions décollent. Si elle part à l'heure, la journée a une chance.",
     "지연의 관제탑에 오신 걸 환영해요. 여기서 밤낮으로 14대의 비행기와 모든 승무원을 지켜봐요. 6시에서 7시 사이가 첫 물결이에요. 13대가 이륙하죠. 첫 물결이 제시간에 뜨면 그날은 가망이 있어요."),
(PT, "Élodie, problème sur le F-HAZC à Bastia. Fuite hydraulique. Le mécanicien annonce deux heures minimum.", "엘로디, 바스티아의 F-HAZC에 문제가 생겼어요. 유압 누유요. 정비사가 최소 두 시간이래요."),
(EB, "Et voilà. Patrice, qu'est-ce qu'on fait ?", "자, 시작이네. 파트리스, 어떻게 할까?"),
(PT, "Pas d'avion de réserve, donc pas le choix : on annule le Bastia–Nice de 6 h 50 et le retour. Et on décale tout le reste de la journée de cet avion.",
     "예비기가 없으니 선택지가 없죠. 6시 50분 바스티아–니스 편과 돌아오는 편을 취소하고, 그 비행기의 나머지 일정을 전부 뒤로 미뤄요."),
(I, "Combien de passagers sont concernés ?", "승객이 몇 명이나 영향을 받죠?"),
(PT, "Cent trente-huit sur les deux vols annulés. Et les retards de l'après-midi, on les découvrira ce soir.", "취소된 두 편에 138명이요. 오후 지연은 저녁이 되면 알게 되겠죠."),
(MA, "Patrice, vous gérez les équipages, c'est ça ? Comment ça se passe pour eux, une journée comme celle-ci ?", "파트리스 씨, 승무원 관리를 맡고 계시죠? 오늘 같은 날이면 승무원들은 어떻게 되나요?"),
(PT, "Mal. Les plannings sont faits au plus juste. Si un vol prend deux heures de retard, l'équipage dépasse son temps de service maximum. Il faut trouver un autre équipage, et on n'en a pas.",
     "안 좋죠. 스케줄이 빠듯하게 짜여 있어요. 비행 하나가 두 시간 늦어지면 승무원이 최대 근무 시간을 넘겨요. 다른 승무원을 구해야 하는데 없어요."),
(MA, "Donc un retard d'avion devient un problème d'équipage, et ce problème d'équipage crée un nouveau retard.", "그러니까 비행기 지연이 승무원 문제가 되고, 그 승무원 문제가 또 새로운 지연을 만드는군요."),
(PT, "C'est ça. Le soir, quand le dernier Paris part avec trois heures de retard, c'est souvent un équipage qu'on attend. Pas un avion.", "그렇죠. 저녁에 마지막 파리행이 세 시간 늦게 출발할 때, 기다리는 건 대개 비행기가 아니라 승무원이에요."),
(I, "Madame Brun, ces deux vols annulés, combien vont-ils vous coûter ?", "브룅 센터장님, 취소된 두 편은 비용이 얼마나 들까요?"),
(EB, "Les passagers ont droit à l'indemnité européenne : deux cent cinquante euros chacun sur ces distances, plus les repas et les nouveaux billets. Une panne technique, ce n'est pas une circonstance extraordinaire. C'est nous qui payons.",
     "승객들은 유럽 보상금을 받을 권리가 있어요. 이 거리면 1인당 250유로, 거기에 식사와 새 항공권까지요. 기술적 고장은 특별한 사정이 아니에요. 우리가 내야 하죠."),
(I, "Et où apparaissent ces indemnités dans vos comptes ? Nous ne les avons pas trouvées dans les données.", "그 보상금은 회계 장부 어디에 나오나요? 데이터에선 못 찾았거든요."),
(EB, "Dans le budget du service client, mélangées avec le reste. Personne ne les regarde. Personne, sauf moi : depuis la vente de l'avion de réserve, je tiens un tableau. Chaque annulation pour panne, chaque indemnité.",
     "고객 서비스 예산 안에 다른 것들과 섞여 있어요. 아무도 안 봐요. 저만 빼고요. 예비기를 판 뒤로 제가 표를 하나 만들고 있어요. 고장으로 인한 결항 하나하나, 보상금 하나하나요."),
(None, "Elle tourne son écran vers eux.", "그녀가 모니터를 두 사람 쪽으로 돌린다."),
(I, "... Vingt et un millions d'euros d'indemnités en deux ans ?", "...2년 동안 보상금이 2,100만 유로요?"),
(EB, "Pour les vols annulés ou retardés de plus de trois heures faute d'avion de remplacement. Vingt et un millions.", "대체할 비행기가 없어서 취소되거나 세 시간 넘게 지연된 비행편들 때문이에요. 2,100만 유로."),
(MA, "Ils ont vendu l'avion sept millions... et ça leur a coûté trois fois plus.", "비행기를 700만에 팔았는데... 그 세 배를 치른 셈이네요."),
(I, "Sans compter les clients perdus. Pourquoi n'avez-vous rien dit à Delorme ?", "잃어버린 고객은 빼고도요. 왜 들로름 대표에게 아무 말 안 하셨어요?"),
(EB, "J'ai essayé, il y a un an. On m'a répondu que l'exploitation devait faire des économies, pas des tableaux.", "1년 전에 해 봤어요. 운항 부서는 표가 아니라 절감을 해야 한다는 답이 돌아왔죠."),
(MA, "Eh bien, votre tableau va devenir la page trois de notre présentation. Avec votre accord, bien sûr.", "그렇다면 센터장님 표가 저희 발표의 3쪽이 될 겁니다. 물론 동의해 주신다면요."),
(EB, "Avec plaisir. Ça fait deux ans que j'attends que quelqu'un le regarde.", "기꺼이요. 누군가 그걸 봐 주길 2년째 기다렸어요."),
(None, "7 h 30. Sur la terrasse de l'aéroport, le soleil se lève sur la baie des Anges.", "오전 7시 30분. 공항 테라스. 앙주 만 위로 해가 떠오른다."),
(I, "Bon. Tu avais raison. La ponctualité d'abord.", "좋아. 네 말이 맞았어. 정시성이 먼저야."),
(MA, "Et toi aussi. Sans tes quatorze millions, ils ne pourront jamais payer un avion de réserve. On présente les deux.", "너도 맞았어. 네 1,400만이 없으면 예비기 비용을 절대 못 대. 둘 다 발표하자."),
(I, "Ensemble, alors. Mais la page trois, c'est moi qui la présente. J'adore annoncer les mauvaises nouvelles avec des chiffres.", "그럼 같이. 대신 3쪽은 내가 발표할 거야. 나쁜 소식을 숫자로 전하는 거 정말 좋아하거든."),
(MA, "Je sais. C'est ce qui me fait un peu peur chez toi.", "알아. 그게 너한테서 내가 좀 무서워하는 부분이야."),

# ---------- 5. Recommandations ----------
(None, "Trois semaines après la première visite, un jeudi, 14 h. Salle du comité de direction d'Azuréa. Marc Delorme, Élodie Brun et trois directeurs écoutent.",
       "첫 방문 3주 뒤 어느 목요일, 오후 2시. 아쥐레아 경영위원회 회의실. 마르크 들로름, 엘로디 브룅, 그리고 임원 세 명이 듣고 있다."),
(I, "Monsieur Delorme, nous allons commencer par un graphique que vous connaissez mal : la ponctualité d'Azuréa, heure par heure.", "들로름 대표님, 대표님이 잘 모르시는 그래프 하나로 시작하겠습니다. 아쥐레아의 시간대별 정시 운항률입니다."),
(MA, "À sept heures du matin, vous êtes une excellente compagnie : quatre-vingt-huit pour cent de vols à l'heure. Ensuite, la courbe baisse sans arrêt. Après dix-huit heures, vous tombez à trente-huit pour cent.",
     "아침 7시의 아쥐레아는 훌륭한 항공사입니다. 88%가 정시 운항이죠. 그 뒤로 곡선은 쉬지 않고 내려갑니다. 오후 6시 이후에는 38%까지 떨어집니다."),
(DE, "C'est le contrôle aérien. Le soir, le ciel est saturé.", "항공 관제 탓이에요. 저녁엔 하늘이 포화 상태니까요."),
(MA, "En partie. Mais regardez la deuxième courbe, le retard moyen par rotation : huit minutes au premier vol, quarante-sept au sixième. Le retard ne vient pas du ciel. Il s'accumule au sol, d'un vol à l'autre.",
     "일부는 그렇습니다. 하지만 두 번째 곡선, 운항 회차별 평균 지연을 보십시오. 첫 편 8분, 여섯 번째 편 47분입니다. 지연은 하늘에서 오는 게 아닙니다. 땅에서, 한 편에서 다음 편으로 쌓이는 겁니다."),
(I, "Votre problème n'est pas une série d'accidents. C'est un système trop tendu : vingt-cinq minutes d'escale, aucun avion de réserve, des équipages sans marge.",
    "대표님의 문제는 우연한 사고의 연속이 아닙니다. 너무 팽팽한 시스템입니다. 25분의 지상 체류, 예비기 0대, 여유 없는 승무원 스케줄이죠."),
(DE, "Trop tendu ? Nous avons simplement optimisé.", "너무 팽팽하다고요? 우린 최적화를 했을 뿐이에요."),
(I, "Alors parlons de l'optimisation la plus importante de ces dernières années : la vente de l'avion de réserve. Page trois.", "그럼 최근 몇 년 동안 가장 중요했던 최적화 이야기를 해 보죠. 예비기 매각입니다. 3쪽입니다."),
(DE, "Sept millions d'euros. Une très bonne opération.", "700만 유로. 아주 좋은 거래였죠."),
(I, "Depuis cette vente, Azuréa a payé vingt et un millions d'euros d'indemnités pour des vols annulés ou retardés de plus de trois heures, faute d'avion de remplacement. Trois fois le prix de vente.",
    "그 매각 이후 아쥐레아는 대체기가 없어 취소되거나 세 시간 넘게 지연된 항공편에 대해 2,100만 유로의 보상금을 지급했습니다. 매각 대금의 세 배입니다."),
(DE, "Vingt et un millions ? D'où sort ce chiffre ?", "2,100만이요? 그 숫자는 어디서 나온 거예요?"),
(EB, "De mon tableau, Marc. Celui que je t'ai montré il y a un an.", "제 표에서요, 마르크. 1년 전에 보여 줬던 그 표요."),
(None, "Un long silence. Delorme fixe l'écran.", "긴 침묵. 들로름이 화면을 뚫어지게 본다."),
(DE, "... Continuez.", "...계속하세요."),
(MA, "Nous avons quatre recommandations. Premièrement, desserrer le programme : quinze minutes de marge avant chaque premier vol du matin, et des escales de trente-cinq minutes au lieu de vingt-cinq sur la ligne de Paris.",
     "권고안은 네 가지입니다. 첫째, 운항 일정에 숨통을 틔웁니다. 아침 첫 편마다 15분의 여유를 두고, 파리 노선의 지상 체류를 25분에서 35분으로 늘립니다."),
(DE, "Dix minutes de plus à chaque escale ? Je vais perdre des vols !", "체류마다 10분씩 더요? 비행편이 줄어들 텐데요!"),
(MA, "Deux par jour, sur quatre-vingts. Nous avons choisi les deux vols de milieu de journée les moins remplis. Cela représente environ trois millions de recettes en moins par an.",
     "80편 중 하루 두 편입니다. 탑승률이 가장 낮은 한낮 비행 두 편을 골랐습니다. 연간 약 300만 유로의 수입 감소입니다."),
(DE, "Trois millions de moins, alors que j'en perds déjà dix-huit ?", "이미 1,800만을 잃고 있는데 300만을 더 줄이라고요?"),
(I, "Attendez la suite. Deuxièmement, louer un avion de réserve basé à Nice. Le leasing coûte environ trois millions et demi par an. Les indemnités, elles, vous coûtent dix millions et demi par an.",
    "다음을 들어 보십시오. 둘째, 니스에 둘 예비기를 임차합니다. 리스 비용은 연간 약 350만 유로입니다. 반면 보상금은 연간 1,050만 유로가 듭니다."),
(DE, "Louer au lieu d'acheter... Bon. Et troisièmement ?", "사는 대신 빌린다라... 좋아요. 셋째는요?"),
(I, "La gestion des recettes. Aujourd'hui, vous vendez vos billets d'août au prix de novembre. Avec des prix qui évoluent selon la demande et la date d'achat, nous estimons le gain à six pour cent du chiffre d'affaires, soit environ quatorze millions par an.",
    "수익 관리입니다. 지금은 8월 항공권을 11월 가격에 파십니다. 수요와 구매 시점에 따라 가격이 움직이게 하면 매출의 6%, 즉 연간 약 1,400만 유로의 이익이 날 것으로 추정합니다."),
(DE, "Augmenter les prix ? Nos clients corses vont hurler. Et la région aussi.", "가격을 올린다고요? 코르시카 고객들이 아우성칠 거예요. 지역 정부도요."),
(I, "Les tarifs résidents pour la Corse sont réglementés : nous n'y touchons pas. Nous parlons des vols de loisirs en haute saison et des réservations de dernière minute.",
    "코르시카 주민 요금은 규제 대상이라 건드리지 않습니다. 성수기 여행 수요와 막판 예약 이야기입니다."),
(EB, "Et des billets à trente-neuf euros en novembre pour remplir les avions vides. Ça, nos clients vont adorer.", "그리고 빈 비행기를 채우려고 11월에 39유로짜리 표도 팔고요. 그건 고객들이 아주 좋아할 거예요."),
(MA, "Quatrièmement, les équipages. Patrice nous l'a montré : le soir, c'est souvent un équipage qu'on attend, pas un avion. Nous proposons deux équipages de réserve, un à Nice et un à Orly, et des plannings construits avec de la marge.",
     "넷째, 승무원입니다. 파트리스 씨가 보여 줬듯이 저녁에 기다리는 건 대개 비행기가 아니라 승무원입니다. 니스와 오를리에 예비 승무원 한 조씩 두고, 여유를 둔 스케줄을 짤 것을 제안합니다."),
(DE, "Et le total de tout ça ? Soyez précis.", "그래서 다 합치면요? 정확하게 말해 주세요."),
(I, "Gestion des recettes : plus quatorze millions. Indemnités évitées : environ plus huit. Avion et équipages de réserve : moins cinq et demi. Vols supprimés : moins trois. Soit à peu près treize millions et demi de mieux dès la première année.",
    "수익 관리 플러스 1,400만. 피하게 될 보상금 약 플러스 800만. 예비기와 예비 승무원 마이너스 550만. 줄어드는 비행편 마이너스 300만. 첫해부터 약 1,350만 유로가 개선됩니다."),
(DE, "Donc je perds encore quatre millions et demi.", "그럼 여전히 450만을 잃는다는 거군요."),
(MA, "La première année, oui. Mais notre objectif, c'est quatre-vingts pour cent de ponctualité en douze mois. Des avions à l'heure, ce sont des clients qui reviennent. Nous visons l'équilibre dès la deuxième année.",
     "첫해에는 그렇습니다. 하지만 저희 목표는 12개월 안에 정시 운항률 80%입니다. 제시간에 뜨는 비행기는 돌아오는 고객을 뜻합니다. 2년 차에는 손익분기를 목표로 합니다."),
(DE, "... Élodie, tu peux tenir quatre-vingts pour cent ?", "...엘로디, 80% 지킬 수 있어?"),
(EB, "Avec un avion de réserve et des équipages qui dorment ? Oui. Je m'y engage.", "예비기와 잠을 자는 승무원이 있다면? 네. 약속할게요."),
(DE, "Alors on y va. Élodie pilote le plan de ponctualité, et on lance la gestion des recettes sur la ligne de Paris dès le printemps. Madame Marchetti, monsieur Kessler, merci. Et pardon pour votre premier vol.",
     "그럼 갑시다. 엘로디가 정시성 계획을 이끌고, 수익 관리는 봄부터 파리 노선에서 시작합니다. 마르케티 씨, 케슬레르 씨, 감사합니다. 그리고 첫 비행은 미안했어요."),

# ---------- 6. Le soir : la Promenade des Anglais ----------
(None, "Le soir même, 19 h 10. Aéroport de Nice, terminal 2. Sur le panneau des départs, une colonne rouge : « ANNULÉ ».", "그날 저녁 7시 10분. 니스 공항 2터미널. 출발 안내판에 빨간 글자가 줄지어 있다. '결항'."),
(AN, "En raison d'un mouvement social du contrôle aérien, tous les vols à destination de Paris sont annulés ce soir. Les passagers sont invités à se présenter au comptoir de leur compagnie.",
     "항공 관제 파업으로 오늘 저녁 파리행 모든 항공편이 결항되었습니다. 승객 여러분께서는 해당 항공사 카운터로 와 주시기 바랍니다."),
(MA, "Tous annulés... Et plus de TGV ce soir, le dernier est parti à seize heures. On est coincés.", "전부 결항이라니... 오늘 밤엔 TGV도 없어. 마지막 열차가 4시에 떠났어. 꼼짝없이 갇혔네."),
(I, "Au moins, cette fois, Azuréa ne paiera pas d'indemnités : une grève du contrôle aérien, c'est une circonstance extraordinaire. Mais elle nous doit l'hôtel et le dîner. Pardon, je calcule. Ça me calme. Déformation professionnelle.",
    "적어도 이번엔 아쥐레아가 보상금을 안 내도 돼. 관제 파업은 특별한 사정이니까. 그래도 호텔이랑 저녁은 책임져야 해. 미안, 또 계산하네. 이러면 마음이 진정돼. 직업병이야."),
(None, "21 h 30. Ils marchent sur la Promenade des Anglais. La mer est noire, les galets roulent sous les vagues. Ils s'assoient sur deux chaises bleues, face à la baie.",
       "밤 9시 30분. 두 사람은 앙글레 산책로를 걷는다. 바다는 검고, 파도 아래 조약돌이 구른다. 두 사람은 만을 마주한 파란 의자 두 개에 앉는다."),
(MA, "Tout à l'heure, tu as dit que les calculs te calmaient. Ce n'était pas une blague, hein ?", "아까 계산하면 마음이 진정된다고 했잖아. 농담 아니었지?"),
(I, "Non. Tu veux savoir pourquoi j'ai choisi la finance ? Je ne l'ai jamais raconté à personne au bureau.", "응. 내가 왜 재무를 택했는지 알고 싶어? 회사에선 아무한테도 얘기한 적 없어."),
(MA, "Je t'écoute. Prends ton temps.", "듣고 있어. 천천히 해."),
(I, "Mon père avait une petite entreprise de transport maritime, à Marseille. Quand j'étais petite, je l'accompagnais au port le samedi. Il connaissait tous les marins, et il chantait du Mozart en faisant ses comptes.",
    "아빠는 마르세유에서 작은 해운 회사를 했어. 어릴 때 토요일마다 아빠를 따라 항구에 갔지. 아빠는 선원들을 다 알았고, 장부를 정리하면서 모차르트를 불렀어."),
(MA, "Ça a l'air d'être un beau souvenir.", "좋은 추억 같네."),
(I, "C'en est un. Et puis, quand j'avais seize ans, l'entreprise a fait faillite. Je me souviens d'une nuit : mon père était assis dans la cuisine avec ses classeurs, et il répétait : « Les chiffres étaient là, et je ne les ai pas lus. »",
    "맞아. 그런데 내가 열여섯 살 때 회사가 파산했어. 어느 밤이 기억나. 아빠가 서류철을 펴 놓고 부엌에 앉아서 계속 되뇌었어. '숫자는 거기 있었는데, 내가 읽지 않았어.'"),
(MA, "Et toi, tu t'es promis de les lire.", "그리고 넌 그 숫자들을 읽겠다고 다짐했구나."),
(I, "Je voulais comprendre les chiffres qui avaient fait tomber mon père. C'est tout. ... À ton tour. Tu parles toujours de ton grand-père, jamais de tes parents.",
    "아빠를 무너뜨린 숫자를 이해하고 싶었어. 그게 다야. ...이제 네 차례야. 넌 늘 할아버지 얘기만 하고, 부모님 얘기는 한 번도 안 해."),
(MA, "Tu as remarqué ça... Mes parents ont divorcé quand j'avais dix ans. À la maison, ça criait tout le temps. Alors on m'envoyait chez mes grands-parents, à Colmar : d'abord le week-end, puis presque tout le temps.",
     "그걸 눈치챘구나... 부모님은 내가 열 살 때 이혼하셨어. 집에선 늘 고함이 오갔지. 그래서 콜마르의 조부모님 댁에 보내졌어. 처음엔 주말에만, 나중엔 거의 늘."),
(I, "Et aujourd'hui, ils sont où, tes parents ?", "지금 부모님은 어디 계셔?"),
(MA, "Ma mère s'est remariée à Montréal ; elle m'appelle à Noël et pour mon anniversaire. Mon père vit à Strasbourg, on se voit deux fois par an et on parle de la météo. C'est mon grand-père qui m'attendait à la sortie de l'école.",
     "엄마는 몬트리올에서 재혼하셨어. 크리스마스랑 내 생일에 전화하셔. 아빠는 스트라스부르에 사시는데, 1년에 두 번 만나서 날씨 얘기를 해. 학교 앞에서 날 기다려 준 건 할아버지였어."),
(I, "C'est pour ça que tu fuis les conflits. Quand tu étais petit, un conflit, ça voulait dire perdre quelqu'un.", "그래서 넌 갈등을 피하는구나. 어릴 때 갈등은 누군가를 잃는다는 뜻이었으니까."),
(MA, "... Personne ne me l'avait jamais dit comme ça. Tu lis les gens aussi bien que les comptes, Marchetti. Et tu as raison. Merci.", "...아무도 나한테 그렇게 말해 준 적 없어. 넌 장부만큼 사람도 잘 읽는구나, 마르케티. 그리고 네 말이 맞아. 고마워."),
(None, "Ils restent longtemps sans parler, puis ils rentrent à l'hôtel. Troisième étage, chambres 312 et 314. Ils s'arrêtent entre les deux portes.",
       "둘은 한참 말없이 앉아 있다가 호텔로 돌아간다. 3층, 312호와 314호. 두 사람은 두 문 사이에 멈춰 선다."),
(MA, "Bon... Trois cent douze. C'est moi.", "자... 312호. 내 방이야."),
(I, "Trois cent quatorze. C'est moi.", "314호. 내 방."),
(MA, "Inès, je... Non, rien. Que fait-on lundi ?", "이네스, 나... 아니, 아무것도. 월요일엔 뭘 하지?"),
(I, "Lundi, une fintech de Station F qui brûle plus d'un million par mois. Et samedi, ta crémaillère. Bonne nuit... Mathieu.",
    "월요일엔 매달 100만 유로 넘게 태우는 스타시옹 F의 핀테크. 그리고 토요일엔 네 집들이. 잘 자... 마티외."),
(None, "Elle n'a pas dit « Strasbourg ». Les deux portes se ferment. De chaque côté du mur, personne n'éteint la lumière tout de suite.",
       "그녀는 '스트라스부르'라고 부르지 않았다. 두 문이 닫힌다. 벽 양쪽에서, 아무도 곧바로 불을 끄지 않는다."),
]

VOCAB = [
("B1", "avoir du retard / être en retard", "지연되다 / 늦다", "avoir une heure de retard(1시간 늦다). 사람·교통수단 모두. ↔ être à l'heure, être en avance."),
("B1", "être annulé", "취소되다, 결항되다", "Le vol est annulé. 명사 une annulation(결항, 취소)."),
("B1", "la porte d'embarquement", "탑승구", "embarquer(탑승하다) ↔ débarquer. une carte d'embarquement = 탑승권."),
("B2", "Nous vous prions de nous excuser pour ce désagrément.", "불편을 드려 죄송합니다", "공항·역 안내 방송의 정형 문구. désagrément = 불편, 언짢은 일."),
("B2", "Tu parles !", "퍽이나! 그럴 리가!", "구어. 상대 말이나 기대를 비꼬아 부정할 때. '말은 잘하네'의 뉘앙스."),
("B2", "être dur(e) en affaires", "협상에서 깐깐하다", "흥정·거래에서 쉽게 양보하지 않는 사람에게. Tu es dure en affaires !"),
("B1", "le taux de ponctualité", "정시 운항률", "항공업에서는 보통 15분 미만 지연을 '정시'로 본다. partir à l'heure."),
("B2", "en cascade", "연쇄적으로", "des retards en cascade = 연쇄 지연. des faillites en cascade(연쇄 파산)."),
("B2", "une escale / une rotation", "지상 체류(경유) / 왕복 운항 회차", "temps d'escale = 도착에서 다음 출발까지의 시간. rotation = 한 비행기의 운항 1회분."),
("B2", "subir", "(피해를) 당하다, 감수하다", "Nous subissons. 능동적으로 대처하지 못하고 외부 요인에 끌려가는 상황."),
("B1", "un avion de réserve", "예비기", "고장·지연 시 투입하는 대체 항공기. un équipage de réserve = 예비 승무원 조."),
("B1", "tomber en panne", "고장 나다", "자동차·기계·비행기 모두. La voiture est tombée en panne."),
("B2", "le taux de remplissage", "탑승률, 좌석 점유율", "remplir(채우다)에서. 호텔의 taux d'occupation(객실 가동률)과 비교."),
("B2", "la gestion des recettes", "수익 관리(레비뉴 매니지먼트)", "수요·시점에 따라 가격을 조정하는 기법. 업계에서는 영어 revenue management, yield management도 씀."),
("B2", "rattraper son retard", "지연을 만회하다", "rattraper = 따라잡다. 공부·업무 진도에도 씀: rattraper les cours."),
("B1", "Accrochez-vous !", "꽉 잡으세요! 각오하세요!", "s'accrocher = 매달리다. 놀라운 소식이나 어려운 일을 앞두고."),
("B2", "au plus juste", "빠듯하게, 여유 없이", "calculer / planifier au plus juste. 비용 절감의 이면을 표현할 때."),
("B2", "le temps de service / le temps de repos", "근무 시간 / 휴식 시간", "항공 승무원은 법으로 최대 근무 시간과 최소 휴식 시간이 정해져 있다."),
("B2", "une indemnité", "보상금, 배상금", "indemniser qn = ~에게 보상하다. avoir droit à une indemnité = 보상을 받을 권리가 있다."),
("C1", "une circonstance extraordinaire", "특별한 사정(불가항력에 가까운 사유)", "EU 항공 승객 규정의 법률 용어. 관제 파업·악천후 등은 해당, 일반적인 기술 고장은 해당하지 않음."),
("B2", "faute de + 명사", "~이 없어서", "faute d'avion de remplacement. faute de temps(시간이 없어서). 관사 없이 쓰는 경우가 많다."),
("B2", "un mouvement social", "파업, 노동 쟁의", "grève를 완곡하게 이르는 공식 표현. 교통 안내 방송에 자주 나온다."),
("B1", "être coincé(e)", "(어딘가에) 갇히다, 발이 묶이다", "구어. être coincé à l'aéroport / dans les bouchons."),
("B2", "faire faillite", "파산하다", "명사 une faillite. déposer le bilan(파산 신청하다)도 함께 기억."),
("C1", "une déformation professionnelle", "직업병(직업적 습관)", "일의 사고방식이 일상에 배어 나오는 것. 실제 질병인 maladie professionnelle과 구분."),
]

GRAM = [
("B1", "être en retard / avoir du retard / prendre du retard",
 "« Le vol ZR 412 partira avec un retard estimé à une heure. » « Le dernier vol pour Paris a souvent deux ou trois heures de retard. » « Si un vol prend deux heures de retard... » être en retard는 '늦은 상태'(Je suis en retard), avoir + 시간 + de retard는 '얼마나 늦었는지', prendre du retard는 '지연이 생기다'라는 변화를 나타낸다. 반대말은 être à l'heure(정시), être en avance(이르다)."),
("B1", "plus... plus... : 비례 비교",
 "« Plus la journée avance, plus le retard s'accumule. » 'A할수록 더 B하다'는 plus + 절, plus + 절로 표현한다. 두 절 사이에 que나 접속사는 없다. moins... moins..., plus... moins...도 가능: Plus on attend, moins on a de marge."),
("B2", "그래프 묘사하기: 시작, 하락, 급락, 수치",
 "« Elle commence très haut et elle descend toute la journée. » « À midi, on tombe à soixante-quatre. » « Après dix-huit heures, la courbe chute. » « Ensuite, la courbe baisse sans arrêt. » 완만한 하락은 baisser·descendre, 급격한 하락은 chuter, 도달 값은 tomber à / atteindre. 상승은 monter·augmenter·grimper, 정체는 stagner·se stabiliser. 시간은 à + 시각, après + 시각으로 붙인다."),
("B2", "반과거와 복합과거: 배경과 사건",
 "« Quand j'étais petite, je l'accompagnais au port le samedi. Il connaissait tous les marins. » (반과거: 반복된 습관·배경) / « Et puis, quand j'avais seize ans, l'entreprise a fait faillite. » (복합과거: 한 번 일어난 사건). 마티외의 « Mes parents ont divorcé quand j'avais dix ans. À la maison, ça criait tout le temps. »도 같은 구조다. 회상 서술에서 '무대'는 반과거, '사건'은 복합과거로 칠한다."),
("B2", "대과거(plus-que-parfait): 과거보다 더 앞선 과거",
 "« Je voulais comprendre les chiffres qui avaient fait tomber mon père. » « Personne ne me l'avait jamais dit comme ça. » avoir/être의 반과거 + 과거분사. '이해하고 싶었던' 시점보다 아버지를 무너뜨린 일이 더 먼저 일어났기 때문에 대과거를 쓴다. 이야기 속 과거 시점을 기준으로 그 이전을 가리킬 때 쓴다."),
("B2", "시간 표현: il y a / depuis / ça fait... que / en / dans",
 "« Il y a deux ans, nous l'avons vendu. »(il y a = ~전에, 완료된 사건) « Depuis cette vente, Azuréa a payé vingt et un millions. »(depuis = ~이래로, 지금까지 계속) « Ça fait deux ans que j'attends que quelqu'un le regarde. »(ça fait + 기간 + que + 현재 = ~째 ~하고 있다) « quatre-vingts pour cent de ponctualité en douze mois »(en = 걸리는 기간). 미래 시점은 dans: dans deux ans."),
("B2", "안내 방송·공식 문체: en raison de, être + 과거분사",
 "« En raison d'un mouvement social du contrôle aérien, tous les vols à destination de Paris sont annulés ce soir. » « Les passagers sont invités à se présenter au comptoir. » 원인은 à cause de 대신 격식체 en raison de, 결과는 être + 과거분사(수동·상태)로 행위자를 감춘다. 명령 대신 être invité à + 부정사로 정중하게 지시하는 것도 공식 문체의 특징이다."),
("B1", "부정 표현: ne... jamais / ne... plus / personne ne / sauf",
 "« Chez nous, les retards ne disparaissent jamais. » « Un luxe que nous ne pouvions plus nous offrir. » « Personne ne les regarde. Personne, sauf moi. » personne가 주어일 때는 personne ne + 동사 순서이고 pas를 쓰지 않는다. sauf(~을 빼고)로 예외를 덧붙이면 강조 효과가 크다."),
]

CULTURE = [
("EU 항공 승객 권리 규정(규정 261/2004)",
 "EU 규정 261/2004에 따라 결항이나 도착 기준 3시간 이상 지연 시 승객은 거리별로 250유로(1,500km 이하), 400유로, 600유로의 보상을 받을 수 있다. 다만 관제 파업, 악천후, 보안 문제 같은 '특별한 사정(circonstances extraordinaires)'은 보상 대상에서 제외된다. 일반적인 기술 고장은 특별한 사정으로 인정되지 않는 것이 원칙이다. 보상과 별개로, 항공사는 이유와 관계없이 식사·숙박 등 '지원 의무'를 진다."),
("프랑스의 관제 파업과 DGAC",
 "프랑스는 유럽에서 항공 관제사 파업이 잦은 나라로 꼽힌다. 파업이 예고되면 민간항공총국(DGAC)이 항공사들에게 특정 공항의 운항 편수를 줄이도록 요청하고, 항공사는 어떤 편을 취소할지 정한다. 프랑스 영공을 지나는 다른 유럽 노선까지 영향을 받기 때문에 파업 하루가 유럽 전체의 연쇄 지연으로 이어지기도 한다. 안내 방송에서는 grève 대신 mouvement social이라는 완곡한 표현을 자주 쓴다."),
("니스와 앙글레 산책로",
 "Promenade des Anglais(영국인의 산책로)는 니스의 앙주 만(Baie des Anges)을 따라 이어지는 해안 산책로로, 공항 근처부터 구시가지 쪽까지 약 7km에 이른다. 19세기 초 겨울 휴양을 온 영국인 거주자들이 처음 길을 조성한 데서 이름이 붙었다. 해변은 모래가 아니라 조약돌(galets)이고, 산책로를 따라 놓인 파란 의자(chaises bleues)는 니스의 상징이 되었다."),
]
