# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, SO = "Inès", "Mathieu", "Hélène", "Sofia"
PH, LA, RO, CL, ME = "Mme Petit", "Dr Laval", "Royer", "Claire", "Mercier"

META = {
    "part": 1, "ep": 8,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "Le brevet tombe",
    "title_ko": "특허가 끝나는 날",
    "place": "11구 오베르캉프 약국·이네스의 아파트 · Vasseur & Associés(영상통화) · 에브리 Laboratoires Vernier 본사·연구소 / 11월, 약 2주간",
    "chars": "이네스, 마티외, 엘렌, 소피아, 프티 약사, 베네딕트 라발 박사(베르니에 대표), 파트리크 루아예(재무 이사), 클레르 뒤발(텐시올 LP 프로젝트 책임자), 토마 메르시에(영업 이사)",
    "work": "중견 제약사 Laboratoires Vernier — 매출의 40%를 차지하는 고혈압 치료제 텐시올의 특허 만료(18개월 뒤)와 제네릭 공세, 예산 삭감으로 멈춰 선 1일 1회 신제형",
    "life": "이네스의 독감, 약국에서 약 사기, 수프 배달, 처음으로 낯선 사람에게 다가온 피가로, 마르세유식 파스타 저녁과 가족 저녁 초대",
    "focus": "건강·약국 어휘, si + 현재/미래, 미래 계획(futur proche·futur simple, quand + 미래), 조건법 가정, être censé, alors que, 제약 업계 어휘",
    "levelmix": "B1 45% · B2 50% · C1 5%",
    "next": "제9화 L'usine du fils — 마르세유의 가족 통조림 회사, 은퇴를 거부하는 아버지와 두 자녀, 그리고 이네스 가족과의 저녁.",
}

D = [
# ---------- 1. Ouverture : la pharmacie ----------
(None, "Un mardi de novembre, 8 h 15. Une pharmacie de la rue Oberkampf, dans le 11e. Sur le téléphone de Mathieu, un message : « Grippe. 39 de fièvre. Pas de bureau aujourd'hui. Ne viens pas. — I. »",
       "11월의 어느 화요일, 오전 8시 15분. 11구 오베르캉프 거리의 약국. 마티외의 휴대폰에 메시지가 와 있다. '독감. 열 39도. 오늘 출근 못 해. 오지 마. — I.'"),
(PH, "Bonjour monsieur, je peux vous aider ?", "안녕하세요, 손님. 도와드릴까요?"),
(MA, "Bonjour madame. C'est pour une amie... enfin, une collègue. Elle a trente-neuf de fièvre, elle a mal à la gorge et elle tousse depuis samedi.",
     "안녕하세요. 친구... 아니, 동료 때문에 왔어요. 열이 39도이고, 목이 아프고, 토요일부터 기침을 해요."),
(PH, "Elle a des courbatures ? Elle a mal partout, elle se sent très fatiguée ?", "몸살 기운도 있나요? 온몸이 쑤시고 많이 피곤해하나요?"),
(MA, "D'après son message, elle a l'impression qu'un camion lui est passé dessus.", "메시지를 보면 트럭에 깔린 기분이라던데요."),
(PH, "Ça ressemble beaucoup à la grippe, il y en a partout en ce moment. Du paracétamol, un gramme toutes les six heures, pas plus de trois grammes par jour. Et beaucoup d'eau.",
     "독감 같네요. 요즘 사방에 돌고 있어요. 파라세타몰을 6시간마다 1그램씩, 하루 3그램을 넘지 않게요. 그리고 물을 많이 마시고요."),
(MA, "Pas d'antibiotiques ?", "항생제는 안 되나요?"),
(PH, "Surtout pas. C'est un virus, les antibiotiques ne servent à rien contre la grippe. Si la fièvre dure plus de trois jours ou si elle a du mal à respirer, elle doit consulter un médecin.",
     "절대 안 돼요. 바이러스라서 항생제는 독감에 아무 소용이 없어요. 열이 사흘 넘게 가거나 숨쉬기 힘들어하면 꼭 의사한테 진찰받아야 해요."),
(MA, "D'accord. Je vais prendre aussi des pastilles pour la gorge, au miel si vous en avez.", "알겠습니다. 목캔디도 살게요. 꿀맛이 있으면 그걸로요."),
(PH, "Voilà. Et pour le paracétamol, je vous mets le générique ? C'est la même molécule, et c'est moins cher.", "여기 있어요. 그리고 파라세타몰은 제네릭으로 드릴까요? 성분은 같고 더 싸요."),
(MA, "Le générique, très bien. Merci beaucoup, madame, vous êtes de bon conseil.", "제네릭 좋아요. 정말 감사합니다. 조언 고마워요."),
(None, "8 h 40. Un vieil immeuble de la rue Oberkampf, troisième étage. Inès ouvre la porte, enroulée dans un plaid, le nez rouge.",
       "오전 8시 40분. 오베르캉프 거리의 오래된 건물 4층(프랑스식 3층). 이네스가 담요를 두르고 빨개진 코로 문을 연다."),
(I, "Strasbourg ?! Qu'est-ce que tu fais là ? Je t'ai écrit de ne pas venir !", "스트라스부르?! 여기서 뭐 해? 오지 말라고 썼잖아!"),
(MA, "Je l'ai lu trop tard. Paracétamol, pastilles, et une soupe de légumes du traiteur d'en bas. Retourne te coucher.",
     "너무 늦게 읽었어. 파라세타몰, 목캔디, 그리고 아래층 반찬 가게에서 산 채소 수프. 다시 가서 누워."),
(I, "Tu ne vas pas entrer, il y a du désordre partout... Et Figaro déteste les inconnus. Il va te griffer.", "들어오면 안 돼, 집이 엉망이야... 그리고 피가로는 낯선 사람을 싫어해. 할퀼 거야."),
(None, "Un gros chat gris s'approche lentement, renifle les chaussures de Mathieu, puis se frotte contre ses jambes.", "커다란 회색 고양이가 천천히 다가와 마티외의 신발 냄새를 맡더니 그의 다리에 몸을 비빈다."),
(MA, "Il a l'air de me détester... avec beaucoup d'affection.", "날 싫어하는 것 같네... 아주 다정하게."),
(I, "C'est impossible. Il n'a jamais fait ça, même pas avec ma mère. Bon... merci. Vraiment. À neuf heures et demie, Hélène a un nouveau dossier pour nous. Je me connecterai en visio.",
    "말도 안 돼. 저런 적 한 번도 없어. 우리 엄마한테도. 음... 고마워. 진심으로. 9시 반에 엘렌이 새 사건을 준대. 나는 영상통화로 들어갈게."),

# ---------- 2. Briefing et client ----------
(None, "9 h 30. Vasseur & Associés, salle « Monceau ». Hélène, Mathieu et Sofia autour de la table. Sur l'écran, Inès, emmitouflée dans son plaid.",
       "오전 9시 30분. 바쇠르 & 어소시에이츠, '몽소' 회의실. 엘렌, 마티외, 소피아가 테이블에 둘러앉아 있다. 화면 속에는 담요를 칭칭 두른 이네스."),
(H, "Inès, tu as une tête épouvantable. Tu es sûre que tu veux suivre la réunion ?", "이네스, 얼굴이 말이 아니네. 정말 회의 들을 거야?"),
(I, "Sûre. Si je reste au lit sans rien faire, je vais devenir folle. Vas-y, Hélène.", "확실해. 아무것도 안 하고 누워 있으면 미쳐 버릴 거야. 시작해, 엘렌."),
(SO, "Regarde, Mathieu : elle a même mis un pull... par-dessus son pyjama.", "봐, 마티외. 잠옷 위에... 스웨터까지 입었어."),
(H, "Notre nouveau client : les Laboratoires Vernier, à Évry. Un laboratoire pharmaceutique de taille moyenne, deux mille trois cents salariés, six cent vingt millions d'euros de chiffre d'affaires.",
    "새 고객은 에브리에 있는 베르니에 제약이야. 중견 제약사고, 직원 2,300명, 매출 6억 2,000만 유로."),
(MA, "Et quel est leur problème ?", "문제가 뭔데요?"),
(H, "Un médicament contre l'hypertension, le Tensiol. Il représente quarante pour cent de leurs ventes. Et son brevet tombe dans dix-huit mois.",
    "고혈압 치료제 텐시올. 매출의 40%를 차지해. 그리고 그 특허가 18개월 뒤에 만료돼."),
(I, "Aïe. Dès que le brevet expire, les génériques arrivent... et les prix s'effondrent.", "아야. 특허가 끝나자마자 제네릭이 들어오고... 가격이 폭락하지."),
(MA, "Les ventes baissent de combien, en général ?", "보통 판매가 얼마나 줄어?"),
(I, "Ça dépend du médicament. Mais en France, avec la substitution en pharmacie, une perte de soixante-dix pour cent dès la première année, c'est classique.",
    "약마다 달라. 그런데 프랑스에선 약국에서 제네릭으로 바꿔 주니까, 첫해에 70% 감소는 흔한 일이야."),
(H, "C'est exactement l'estimation de leur directeur financier. La PDG, le docteur Bénédicte Laval, vous attend à quatorze heures. Mathieu, Sofia, vous y allez. Inès, tu suis de chez toi.",
    "그쪽 재무 이사 추정치가 딱 그거야. 대표 베네딕트 라발 박사가 오후 2시에 기다려. 마티외, 소피아, 너희가 가. 이네스는 집에서 따라오고."),
(MA, "C'est drôle : ce matin, à la pharmacie, j'ai pris le générique sans réfléchir. Je n'avais jamais pensé à ceux qui vendent l'original.",
     "재밌네요. 오늘 아침 약국에서 아무 생각 없이 제네릭을 샀거든요. 오리지널을 파는 사람들 생각은 해 본 적이 없었어요."),
(H, "Tu étais à la pharmacie ce matin, toi ? Tiens donc.", "너 오늘 아침에 약국에 갔었어? 거참."),
(SO, "Ah bon ? Et c'était pour qui, ces médicaments ?", "아 그래? 그 약은 누구 주려고?"),
(MA, "Pour... quelqu'un qui tousse. Bon, on y va, Sofia ? Le RER D jusqu'à Évry, c'est toute une aventure.", "음... 기침하는 누군가. 자, 갈까, 소피아? 에브리까지 RER D 타는 건 그야말로 모험이라고."),
(None, "14 h. Le siège des Laboratoires Vernier, à Évry. Un grand bâtiment de verre. Le docteur Bénédicte Laval, ancienne cardiologue, les reçoit avec son directeur financier. Inès est sur l'ordinateur de Sofia.",
       "오후 2시. 에브리의 베르니에 제약 본사. 커다란 유리 건물. 심장내과 의사 출신인 베네딕트 라발 박사가 재무 이사와 함께 그들을 맞는다. 이네스는 소피아의 노트북 화면 속에 있다."),
(LA, "Bonjour, et bienvenue. Vous êtes trois, je vois, dont une sur un écran.", "안녕하세요, 환영합니다. 세 분이시네요. 한 분은 화면 속에 계시고요."),
(MA, "Bonjour docteur Laval. Notre collègue Inès Marchetti a la grippe. Elle a tenu à suivre la réunion à distance, si vous le permettez.",
     "안녕하세요, 라발 박사님. 저희 동료 이네스 마르케티가 독감에 걸렸습니다. 허락해 주신다면 원격으로 회의에 참여하겠다고 고집해서요."),
(LA, "Je le permets. Mais en tant que médecin, je vous prescris du repos, madame Marchetti. C'est une ordonnance.", "허락하죠. 하지만 의사로서 처방합니다, 마르케티 씨. 휴식하세요. 이건 처방전이에요."),
(I, "Promis, docteur. Juste après la réunion.", "약속할게요, 박사님. 회의 끝나자마자요."),
(LA, "Je vous présente Patrick Royer, notre directeur administratif et financier. Patrick, vous commencez ?", "저희 재무·관리 이사 파트리크 루아예를 소개합니다. 파트리크, 시작하시겠어요?"),
(RO, "Volontiers. Le Tensiol nous rapporte deux cent quarante-huit millions d'euros par an. Dans dix-huit mois, les génériques arrivent. Si nous ne faisons rien, nous perdrons près de cent soixante-quinze millions de chiffre d'affaires en un an.",
     "기꺼이요. 텐시올은 연간 2억 4,800만 유로를 벌어들입니다. 18개월 뒤면 제네릭이 들어옵니다. 아무것도 하지 않으면 1년 만에 매출 1억 7,500만 유로 가까이를 잃게 됩니다."),
(I, "Et votre marge opérationnelle, aujourd'hui ?", "현재 영업이익률은 어떻게 되나요?"),
(RO, "Douze pour cent, soit environ soixante-quinze millions. Vous voyez le problème : sans le Tensiol, nous passerons dans le rouge.",
     "12%, 그러니까 약 7,500만 유로입니다. 문제가 보이시죠. 텐시올이 없으면 적자로 돌아섭니다."),
(MA, "Qu'avez-vous déjà fait pour préparer cette échéance ?", "이 시점에 대비해서 이미 어떤 조치를 하셨나요?"),
(RO, "Nous avons réduit les coûts. L'an dernier, j'ai proposé une baisse de quinze pour cent du budget de recherche. Le conseil l'a acceptée.",
     "비용을 줄였습니다. 작년에 제가 연구 예산을 15% 줄이자고 제안했고, 이사회가 받아들였죠."),
(I, "Excusez-moi... vous avez réduit la recherche alors que votre principal produit va perdre sa protection ?", "실례지만... 주력 제품이 보호를 잃게 되는 상황에서 연구를 줄이셨다고요?"),
(RO, "Nous avons arrêté les projets les moins prometteurs. Nous ne pouvons pas financer tout et n'importe quoi.", "가장 가능성이 낮은 프로젝트들을 멈춘 겁니다. 아무거나 다 돈을 댈 수는 없으니까요."),
(LA, "Patrick a fait son travail : protéger les comptes. Mais je ne veux pas une entreprise qui survit, je veux une entreprise qui a un avenir. Le conseil d'administration se réunit dans quinze jours. Je veux lui présenter un plan.",
     "파트리크는 자기 일을 한 거예요. 회계를 지키는 일이요. 하지만 저는 겨우 살아남는 회사가 아니라 미래가 있는 회사를 원해요. 이사회가 2주 뒤에 열립니다. 거기에 계획을 내놓고 싶어요."),
(MA, "Quinze jours, c'est noté. Nous aurons besoin de vos chiffres par produit, et surtout de la liste de tous vos projets de recherche, y compris ceux qui ont été arrêtés.",
     "2주, 알겠습니다. 제품별 수치가 필요하고, 무엇보다 연구 프로젝트 전체 목록이 필요합니다. 중단된 것까지 포함해서요."),
(RO, "Ceux qui ont été arrêtés ? Ils ne servent plus à rien.", "중단된 것까지요? 그건 이제 아무 쓸모가 없는데요."),
(LA, "Donnez-leur tout, Patrick. Et vous, madame Marchetti : maintenant, au lit !", "전부 드리세요, 파트리크. 그리고 마르케티 씨, 이제 침대로 가세요!"),

# ---------- 3. Analyse ----------
(None, "Jeudi, 19 h. Vasseur & Associés. Mathieu et Sofia, entourés de documents. Sur l'écran, Inès, un thermomètre à côté de son ordinateur.",
       "목요일 저녁 7시. 바쇠르 & 어소시에이츠. 서류에 둘러싸인 마티외와 소피아. 화면 속 이네스의 노트북 옆에는 체온계가 놓여 있다."),
(MA, "Alors, comment tu te sens ce soir ?", "그래서, 오늘 저녁엔 좀 어때?"),
(I, "Trente-huit. C'est presque une bonne nouvelle. J'ai lu tous les fichiers que Sofia m'a envoyés. Tous.", "38도. 거의 좋은 소식이지. 소피아가 보내 준 파일 다 읽었어. 전부."),
(SO, "Tu étais censée te reposer !", "너 쉬기로 했잖아!"),
(I, "Je me suis reposée... en lisant. Bon. Le constat est simple : après le Tensiol, il n'y a rien. Parmi les projets en cours, le prochain médicament ne sera pas sur le marché avant cinq ou six ans.",
    "쉬었어... 읽으면서. 자. 진단은 간단해. 텐시올 다음엔 아무것도 없어. 진행 중인 프로젝트 중에서 다음 약은 5~6년 안에는 시장에 안 나와."),
(MA, "Donc un trou de cinq ans. Comment on le comble ?", "그러니까 5년의 공백이네. 그걸 어떻게 메우지?"),
(I, "Si on ne trouve pas de nouveaux revenus, il faudra baisser les coûts de vingt pour cent. Ça veut dire des suppressions de postes.", "새 수입원을 못 찾으면 비용을 20% 줄여야 할 거야. 그건 인력 감축을 뜻하지."),
(MA, "Attends. Royer a déjà coupé dans la recherche. Si on coupe encore, ils n'auront plus rien à vendre dans dix ans.", "잠깐. 루아예가 이미 연구비를 깎았어. 또 깎으면 10년 뒤엔 팔 게 하나도 없을 거야."),
(I, "Et si on ne coupe pas, ils n'existeront plus dans trois ans ! Tu veux protéger l'avenir ou les comptes ?", "그리고 안 깎으면 3년 뒤엔 회사가 없을 거야! 미래를 지키고 싶은 거야, 회계를 지키고 싶은 거야?"),
(MA, "Tu m'as déjà posé ce genre de question, à propos de croissants. Je réponds pareil : les deux.", "전에도 크루아상 얘기하면서 그런 질문 했었지. 대답은 똑같아. 둘 다."),
(I, "Tu es agaçant quand tu as raison sur la forme et tort sur le fond.", "넌 말은 맞는데 내용은 틀릴 때 정말 짜증 나."),
(SO, "Euh... pendant que vous vous disputez, j'ai trouvé quelque chose. Je partage mon écran ?", "어... 둘이 싸우는 동안 내가 뭘 좀 찾았어. 화면 공유할까?"),
(MA, "Vas-y, montre-nous.", "그래, 보여 줘."),
(SO, "Dans la liste des projets arrêtés, il y en a un qui s'appelle VR-212. Budget gelé depuis huit mois. Description : « Tensiol LP ».",
     "중단된 프로젝트 목록에 VR-212라는 게 있어. 8개월 전부터 예산 동결. 설명: '텐시올 LP'."),
(MA, "LP ? Ça veut dire quoi ?", "LP? 그게 무슨 뜻이야?"),
(I, "Libération prolongée. Le médicament se diffuse lentement dans le corps. Le Tensiol se prend deux fois par jour, non ?", "서방형(徐放型)이야. 약이 몸속에서 천천히 퍼지는 거지. 텐시올은 하루에 두 번 먹는 약이지?"),
(SO, "Exactement, matin et soir. Une version LP, ce serait un seul comprimé par jour.", "맞아, 아침저녁으로. LP 버전이면 하루에 한 알이 되겠지."),
(MA, "Et ils l'ont arrêtée ? Juste avant la chute du brevet ? Ça n'a aucun sens.", "그런데 그걸 멈췄다고? 특허 만료 직전에? 말이 안 되잖아."),
(I, "Sauf si le projet était mauvais. Vérifions avant de nous enthousiasmer. Sofia, il en était où ?", "프로젝트가 별로였다면 얘기가 다르지. 들뜨기 전에 확인부터 하자. 소피아, 어디까지 진행됐었어?"),
(SO, "D'après le document, en phase trois, la dernière étape des essais cliniques. Neuf cents patients sur mille deux cents déjà traités.", "문서에 따르면 임상시험 마지막 단계인 3상이야. 환자 1,200명 중 900명이 이미 투약을 받았어."),
(I, "Neuf cents sur mille deux cents... Ils étaient aux trois quarts du chemin !", "1,200명 중 900명... 4분의 3까지 와 있었잖아!"),
(MA, "Si ce projet est sérieux, ça change tout. Un nouveau produit, protégé par un nouveau brevet, qui remplace le Tensiol avant l'arrivée des génériques.",
     "이 프로젝트가 진짜라면 모든 게 달라져. 새 특허로 보호받는 새 제품이 제네릭이 들어오기 전에 텐시올을 대체하는 거야."),
(I, "À condition d'arriver à temps. Une demande d'autorisation, c'est environ un an d'examen. Si les essais finissent dans six mois, on arrive à dix-huit mois. Pile au moment où le brevet tombe. C'est serré.",
    "제때 도착한다면 말이지. 허가 신청은 심사가 1년쯤 걸려. 시험이 6개월 뒤에 끝나면 18개월이 돼. 딱 특허가 끝나는 시점이야. 빠듯해."),
(MA, "Serré, mais possible. Demain, je vais au laboratoire d'Évry. Je veux parler aux chercheurs qui travaillaient sur ce projet.", "빠듯하지만 가능해. 내일 에브리 연구소에 갈게. 이 프로젝트를 하던 연구원들과 얘기하고 싶어."),
(I, "Je viens avec vous.", "나도 같이 갈래."),
(MA, "Non. Tu as trente-huit de fièvre. Sofia et moi, on s'en occupe.", "안 돼. 너 열이 38도야. 소피아랑 내가 맡을게."),
(I, "Mathieu, je ne peux pas rester là à regarder le plafond pendant que vous...", "마티외, 너희가 일하는 동안 여기서 천장만 쳐다보고 있을 순 없어..."),
(MA, "Inès. Pour une fois, laisse-nous faire. Tu nous as donné la bonne question. On va te rapporter les réponses.", "이네스. 이번 한 번만 우리한테 맡겨. 네가 제대로 된 질문을 줬잖아. 답은 우리가 가져올게."),
(I, "... D'accord. Mais tu m'appelles dès que tu sors du labo. Dès que tu sors.", "...알았어. 대신 연구소에서 나오자마자 전화해. 나오자마자."),
(SO, "Vous savez que vous êtes mignons, tous les deux ?", "둘이 귀여운 거 알아?"),
(I, "Sofia, je coupe ma caméra. Bonne nuit !", "소피아, 나 카메라 끈다. 잘 자!"),

# ---------- 4. Terrain : le laboratoire ----------
(None, "Vendredi, 10 h. Le centre de recherche des Laboratoires Vernier, à Évry. Blouses blanches, paillasses, odeur de produits chimiques. Une femme d'une quarantaine d'années les attend.",
       "금요일 오전 10시. 에브리의 베르니에 제약 연구센터. 흰 가운, 실험대, 화학 약품 냄새. 마흔 살쯤 된 여성이 그들을 기다리고 있다."),
(CL, "Bonjour. Claire Duval. J'étais cheffe de projet sur le Tensiol LP. Enfin, je le suis toujours... mais je n'ai plus de projet.", "안녕하세요. 클레르 뒤발입니다. 텐시올 LP 프로젝트 책임자였어요. 아니, 지금도 그렇긴 한데... 프로젝트가 없어요."),
(MA, "Bonjour Claire. Merci de nous recevoir. Pouvez-vous nous expliquer où en était le projet quand il a été arrêté ?", "안녕하세요, 클레르 씨. 맞아 주셔서 감사합니다. 중단될 때 프로젝트가 어디까지 와 있었는지 설명해 주시겠어요?"),
(CL, "Presque au bout. La formulation est prête depuis deux ans : un seul comprimé le matin, et le médicament agit pendant vingt-quatre heures. Les premiers résultats de la phase trois étaient très bons.",
     "거의 끝에요. 제형은 2년 전부터 준비돼 있었어요. 아침에 한 알만 먹으면 약효가 24시간 가요. 3상 초기 결과도 아주 좋았고요."),
(MA, "Alors pourquoi l'avoir arrêté ?", "그런데 왜 멈춘 거죠?"),
(CL, "Le budget de recherche a baissé de quinze pour cent. Il fallait couper quelque part. Le Tensiol LP coûtait cher, et la direction financière a jugé que ce n'était « qu'une variante d'un vieux produit ».",
     "연구 예산이 15% 줄었어요. 어딘가는 잘라야 했죠. 텐시올 LP는 돈이 많이 들었고, 재무 부서는 그게 '오래된 제품의 변형일 뿐'이라고 판단했어요."),
(MA, "Ce n'est pas votre avis, j'imagine.", "선생님 생각은 다르시겠죠."),
(CL, "Pas du tout. Regardez ce graphique. Un patient hypertendu sur trois oublie régulièrement le comprimé du soir. L'hypertension ne fait pas mal : les gens ne sentent rien, alors ils oublient.",
     "전혀 아니죠. 이 그래프를 보세요. 고혈압 환자 세 명 중 한 명은 저녁 약을 자주 잊어요. 고혈압은 아프지 않거든요. 아무것도 느끼지 못하니 잊어버리는 거죠."),
(MA, "Et un patient qui oublie son traitement...", "그럼 치료를 빼먹는 환자는..."),
(CL, "... risque un AVC ou un infarctus. Avec un seul comprimé par jour, l'observance s'améliore nettement. Ce n'est pas une variante, c'est un vrai progrès pour les patients.",
     "...뇌졸중이나 심근경색 위험이 생기죠. 하루 한 알이면 복약 순응도가 확실히 좋아져요. 변형이 아니라 환자들에게 진짜 진보예요."),
(MA, "Combien faudrait-il pour terminer les essais ?", "시험을 끝내려면 얼마가 필요할까요?"),
(CL, "Trente millions d'euros et six mois. Les patients sont déjà recrutés dans nos centres, les médecins attendent. Si on relance le projet ce mois-ci, nous aurons les résultats au printemps.",
     "3,000만 유로와 6개월이요. 환자들은 이미 저희 시험 기관에 모집돼 있고, 의사들도 기다리고 있어요. 이번 달에 재개하면 봄에 결과가 나와요."),
(MA, "Et si on attend encore ?", "더 기다리면요?"),
(CL, "Si on attend trois mois de plus, les centres partiront sur d'autres études et il faudra tout recommencer. Ce serait trop tard pour le brevet.", "석 달만 더 기다리면 기관들이 다른 연구로 넘어가고, 처음부터 다시 해야 해요. 특허 시한에는 너무 늦죠."),
(MA, "Est-ce que les commerciaux connaissent ce projet ?", "영업팀도 이 프로젝트를 알고 있나요?"),
(CL, "Demandez à Thomas Mercier, le directeur commercial. Son bureau est au bout du couloir.", "영업 이사 토마 메르시에한테 물어보세요. 복도 끝이 그분 사무실이에요."),
(None, "Un peu plus tard, à l'étage commercial. Thomas Mercier, la cinquantaine, raccroche son téléphone.", "잠시 뒤, 영업부 층. 50대의 토마 메르시에가 전화를 끊는다."),
(ME, "Le Tensiol LP ? Bien sûr que je le connais ! Les cardiologues me le réclament depuis deux ans. Ils me demandent : « Quand est-ce que vous sortez enfin le comprimé unique ? »",
     "텐시올 LP요? 당연히 알죠! 심장내과 의사들이 2년째 그걸 달라고 해요. '그 한 알짜리는 대체 언제 나와요?'라고요."),
(MA, "Vous en avez parlé à la direction ?", "경영진에게 그 얘기를 하셨나요?"),
(ME, "À chaque comité. On m'a répondu que c'était « un sujet de recherche, pas de vente ». Chez nous, la recherche et le commercial ne se parlent pas beaucoup.",
     "회의 때마다요. 그랬더니 '그건 연구 문제지 영업 문제가 아니다'라는 답이 왔어요. 우리 회사는 연구 부서와 영업 부서가 대화를 별로 안 해요."),
(MA, "Et quand les génériques arriveront, que va-t-il se passer ?", "그럼 제네릭이 들어오면 어떻게 될까요?"),
(ME, "Les pharmaciens remplaceront le Tensiol par le générique, c'est presque automatique. Mes visiteurs médicaux le savent. Certains cherchent déjà un autre emploi.",
     "약사들이 텐시올을 제네릭으로 바꿔 주겠죠. 거의 자동이에요. 저희 영업 담당자들도 알아요. 벌써 다른 일자리를 찾는 사람도 있어요."),
(SO, "Merci, monsieur Mercier. Vous venez de confirmer notre intuition.", "감사합니다, 메르시에 이사님. 덕분에 저희 직감이 맞다는 걸 확인했습니다."),
(None, "Sur le parking, Mathieu appelle Inès en visio. Le soleil de novembre est bas.", "주차장에서 마티외가 이네스에게 영상통화를 건다. 11월의 해가 낮게 걸려 있다."),
(MA, "Inès ? Le projet est sérieux. La formulation est prête : trente millions et six mois pour finir. Et les cardiologues le réclament depuis deux ans.",
     "이네스? 프로젝트 진짜야. 제형은 준비돼 있어. 끝내는 데 3,000만 유로와 6개월. 그리고 심장내과 의사들이 2년째 그걸 원하고 있어."),
(I, "Je le savais ! ... Enfin, je l'espérais. Tu as des chiffres sur l'observance ?", "내 그럴 줄 알았어! ...아니, 그러길 바랐어. 복약 순응도 수치는 있어?"),
(SO, "Un patient sur trois oublie le comprimé du soir. Claire nous envoie l'étude ce soir.", "환자 세 명 중 한 명이 저녁 약을 잊어. 클레르 씨가 오늘 저녁에 연구 자료를 보내 줄 거야."),
(I, "Alors on tient notre histoire. Merci, tous les deux. Et toi, Strasbourg, tu as fait du très bon travail sans moi. Ne t'y habitue pas.",
    "그럼 스토리가 잡혔네. 둘 다 고마워. 그리고 스트라스부르, 나 없이도 아주 잘했어. 익숙해지진 마."),

# ---------- 5. Recommandations ----------
(None, "Dix jours plus tard. Siège des Laboratoires Vernier, salle du comité de direction. Inès, guérie, se tient près de l'écran. Autour de la table : Bénédicte Laval, Patrick Royer, Claire Duval et Thomas Mercier.",
       "열흘 뒤. 베르니에 제약 본사 경영위원회 회의실. 다 나은 이네스가 화면 옆에 서 있다. 테이블에는 베네딕트 라발, 파트리크 루아예, 클레르 뒤발, 토마 메르시에."),
(LA, "Madame Marchetti, en chair et en os ! Vous avez suivi mon ordonnance, je vois.", "마르케티 씨, 직접 오셨군요! 제 처방대로 하셨나 보네요."),
(I, "À la lettre, docteur. Enfin... presque. Nous allons commencer par une phrase : votre plus grand risque n'est pas le générique du Tensiol. C'est le projet que vous avez arrêté.",
    "글자 그대로요, 박사님. 음... 거의요. 한 문장으로 시작하겠습니다. 가장 큰 위험은 텐시올 제네릭이 아닙니다. 중단하신 프로젝트입니다."),
(RO, "Le Tensiol LP ? Nous avons déjà discuté de ce dossier...", "텐시올 LP요? 그 건은 이미 논의했는데요..."),
(MA, "Permettez-nous de le présenter autrement. Aujourd'hui, un patient sur trois oublie le comprimé du soir. Le Tensiol LP, c'est un seul comprimé par jour. Pour les médecins, c'est un progrès réel, pas une variante.",
     "다른 방식으로 말씀드리겠습니다. 현재 환자 세 명 중 한 명이 저녁 약을 잊습니다. 텐시올 LP는 하루 한 알입니다. 의사들에게 이건 변형이 아니라 실질적인 진보입니다."),
(CL, "Et les essais sont aux trois quarts terminés : neuf cents patients sur mille deux cents.", "그리고 시험은 4분의 3이 끝났습니다. 환자 1,200명 중 900명이요."),
(I, "Notre première recommandation : relancer le Tensiol LP immédiatement. Trente millions d'euros, six mois d'essais, puis environ un an d'examen pour l'autorisation de mise sur le marché.",
    "첫 번째 권고는 텐시올 LP를 즉시 재개하는 것입니다. 3,000만 유로, 6개월의 시험, 그리고 시판 허가 심사에 약 1년입니다."),
(LA, "Ce qui nous amène à...", "그러면..."),
(I, "Dix-huit mois. Le moment exact où le brevet tombe. Si vous relancez le projet ce mois-ci, le Tensiol LP pourra arriver en pharmacie en même temps que les génériques. Si vous attendez, il arrivera trop tard.",
    "18개월입니다. 정확히 특허가 만료되는 시점이죠. 이번 달에 재개하시면 텐시올 LP는 제네릭과 동시에 약국에 들어갈 수 있습니다. 기다리시면 너무 늦게 도착할 겁니다."),
(RO, "Et s'il n'obtient pas l'autorisation ? Nous aurons dépensé trente millions pour rien.", "허가를 못 받으면요? 3,000만 유로를 헛되이 쓰게 되는 겁니다."),
(MA, "C'est un risque. Mais les résultats intermédiaires sont bons, et la molécule est connue depuis quinze ans. Le risque de ne rien faire est bien plus grand : cent soixante-quinze millions de chiffre d'affaires en moins.",
     "위험은 있습니다. 하지만 중간 결과가 좋고, 성분은 15년 전부터 알려진 것입니다. 아무것도 하지 않는 위험이 훨씬 큽니다. 매출 1억 7,500만 유로 감소니까요."),
(LA, "Continuez.", "계속하세요."),
(I, "Deuxièmement : ne pas laisser tout le marché du générique aux autres. Le jour où le brevet tombe, vous lancez votre propre générique du Tensiol, avec un partenaire de distribution. C'est ce qu'on appelle un générique autorisé.",
    "둘째, 제네릭 시장을 전부 남에게 내주지 않는 것입니다. 특허가 끝나는 날, 유통 파트너와 함께 자체 텐시올 제네릭을 출시합니다. 이른바 '공인 제네릭'입니다."),
(ME, "Nous ferions concurrence à notre propre produit ?", "우리 제품과 우리가 경쟁하게 되는 건가요?"),
(I, "Les génériques arriveront de toute façon. Si un patient doit passer au générique, autant que ce soit le vôtre.", "제네릭은 어차피 들어옵니다. 환자가 제네릭으로 넘어가야 한다면, 기왕이면 그게 귀사 제품인 게 낫죠."),
(RO, "Et combien cela rapporterait-il, tout ça ?", "그래서 이걸 다 하면 얼마나 벌어들이죠?"),
(I, "Selon nos calculs, dans deux ans : quatre-vingt-dix millions pour le Tensiol LP, quarante pour le Tensiol classique et trente-cinq pour le générique. Au total, cent soixante-cinq millions. Vous garderiez les deux tiers des revenus actuels du Tensiol, au lieu de moins d'un tiers.",
    "저희 계산으로는 2년 뒤 텐시올 LP 9,000만, 기존 텐시올 4,000만, 제네릭 3,500만 유로입니다. 합계 1억 6,500만 유로. 지금 텐시올 수입의 3분의 1도 안 남는 대신 3분의 2를 지키시게 됩니다."),
(LA, "Les deux tiers... Ce n'est plus la même histoire.", "3분의 2라... 완전히 다른 이야기네요."),
(MA, "Troisièmement, les coûts. Monsieur Royer a raison sur un point : il faut faire des économies. Mais pas dans la recherche. Nous avons identifié trente-cinq millions d'économies sur deux ans : les achats, le regroupement de deux lignes de conditionnement, et moins de marketing pour le Tensiol classique.",
     "셋째, 비용입니다. 루아예 이사님 말씀이 한 가지는 맞습니다. 절감은 해야 합니다. 하지만 연구에서는 아닙니다. 2년간 3,500만 유로를 절감할 곳을 찾았습니다. 구매, 포장 라인 두 개 통합, 그리고 기존 텐시올 마케팅 축소입니다."),
(RO, "Trente-cinq millions... Ça financerait le Tensiol LP.", "3,500만이라... 그거면 텐시올 LP 비용이 나오겠군요."),
(MA, "Exactement. Et il resterait cinq millions de marge de sécurité.", "바로 그겁니다. 그리고 500만 유로의 안전 여유분이 남습니다."),
(LA, "Et après le Tensiol LP ? Je ne veux pas me retrouver dans la même situation dans dix ans.", "그럼 텐시올 LP 다음은요? 10년 뒤에 똑같은 상황에 처하고 싶지 않아요."),
(I, "C'est notre quatrième recommandation : diversifier le portefeuille. Vous avez une vraie expertise en cardiologie. Nous proposons d'acheter les licences de deux molécules développées par des biotechs, et de créer un comité commun entre la recherche et le commercial.",
    "그게 네 번째 권고입니다. 포트폴리오 다각화요. 귀사는 심장 분야에 확실한 전문성이 있습니다. 바이오텍이 개발한 분자 두 개의 라이선스를 사들이고, 연구와 영업의 공동 위원회를 만들 것을 제안합니다."),
(ME, "Un comité où on se parle ? Enfin !", "서로 대화하는 위원회요? 드디어!"),
(CL, "J'y serai, Thomas. Avec mes trente millions, j'espère.", "저도 들어갈게요, 토마. 제 3,000만 유로를 들고요, 바라건대."),
(RO, "Je reste prudent. Si les résultats des essais sont mauvais au printemps, que fait-on ?", "저는 여전히 신중합니다. 봄에 시험 결과가 나쁘면 어떻게 하죠?"),
(MA, "C'est pour ça que nous proposons un point d'étape dans trois mois, avec un critère d'arrêt clair. Si les données ne sont pas bonnes, vous arrêterez avant d'avoir tout dépensé.",
     "그래서 석 달 뒤에 중간 점검을 하고, 명확한 중단 기준을 두자고 제안하는 겁니다. 데이터가 좋지 않으면 돈을 다 쓰기 전에 멈추시면 됩니다."),
(RO, "Un critère d'arrêt, écrit noir sur blanc ? Là, je peux signer.", "중단 기준을 문서로 분명히요? 그렇다면 서명할 수 있습니다."),
(LA, "Alors c'est décidé. Je présenterai ce plan au conseil jeudi, et je le défendrai. Claire, vous relancez les centres d'essai dès lundi. Patrick, vous trouvez les trente-cinq millions. Thomas, vous préparez les cardiologues.",
     "그럼 결정됐습니다. 목요일 이사회에 이 계획을 내놓고 제가 직접 지키겠어요. 클레르, 월요일부터 시험 기관들을 다시 가동하세요. 파트리크는 3,500만 유로를 찾아 주시고요. 토마는 심장내과 의사들을 준비시키세요."),
(CL, "Dès lundi. Merci, docteur.", "월요일부터요. 감사합니다, 박사님."),
(LA, "Remerciez plutôt vos consultants. Et vous, madame Marchetti, l'année prochaine, faites-vous vacciner contre la grippe. C'est une autre ordonnance.",
     "차라리 컨설턴트들에게 고마워하세요. 그리고 마르케티 씨, 내년엔 독감 예방접종 하세요. 이것도 처방이에요."),

# ---------- 6. Le soir : chez Inès ----------
(None, "Samedi soir, 20 h. Chez Inès, à Oberkampf. Une odeur d'ail et de tomate. Mathieu est assis sur le canapé ; Figaro l'observe depuis le haut de la bibliothèque.",
       "토요일 저녁 8시. 오베르캉프의 이네스 집. 마늘과 토마토 냄새. 마티외는 소파에 앉아 있고, 피가로가 책장 위에서 그를 지켜본다."),
(I, "Ce soir, c'est moi qui cuisine. Pour te remercier de la soupe, des pastilles, et de tout le reste.", "오늘 밤엔 내가 요리해. 수프랑 목캔디랑, 그 밖의 모든 것에 대한 보답으로."),
(MA, "Tu n'étais pas obligée. Qu'est-ce que tu prépares ?", "안 그래도 되는데. 뭐 만들어?"),
(I, "Des pâtes à la marseillaise : tomates, ail, anchois et quelques câpres. Ce n'est pas une bouillabaisse, mais c'est la recette de ma mère.",
    "마르세유식 파스타. 토마토, 마늘, 안초비, 케이퍼 조금. 부야베스는 아니지만 우리 엄마 레시피야."),
(MA, "Ça sent le Sud. Tu es complètement guérie, alors ?", "남프랑스 냄새가 나네. 그럼 완전히 나은 거야?"),
(I, "Complètement. Je dois t'avouer une chose : quand vous étiez au labo sans moi, j'ai détesté ça. Je ne supporte pas de ne pas être là.",
    "완전히. 하나 고백할게. 너희가 나 없이 연구소에 갔을 때 정말 싫었어. 내가 그 자리에 없는 걸 못 견디겠더라."),
(MA, "Je sais, on l'a tous remarqué. Mais tu sais quoi ? Toute la semaine, à chaque décision, je me demandais : « Qu'est-ce qu'Inès dirait ? »",
     "알아, 다들 눈치챘어. 그런데 그거 알아? 일주일 내내 뭘 결정할 때마다 생각했어. '이네스라면 뭐라고 할까?'"),
(I, "Et qu'est-ce que je disais ?", "그래서 내가 뭐라고 했는데?"),
(MA, "« Montre-moi les chiffres, Strasbourg. » Toujours la même chose.", "'숫자 보여 줘, 스트라스부르.' 맨날 똑같은 말."),
(I, "Ça me ressemble. Et moi, dans mon lit, je me disais : « Il va trouver ce que je n'aurais jamais vu dans un tableur. » Et tu l'as trouvé.",
    "나답네. 그리고 나는 침대에 누워서 생각했어. '저 사람은 내가 엑셀에서는 절대 못 봤을 걸 찾아낼 거야.' 그리고 넌 찾아냈지."),
(None, "Figaro saute de la bibliothèque, atterrit sur les genoux de Mathieu, tourne deux fois sur lui-même et s'installe en ronronnant.",
       "피가로가 책장에서 뛰어내려 마티외의 무릎에 내려앉더니, 제자리에서 두 바퀴 돌고 가르랑거리며 자리를 잡는다."),
(MA, "Euh... Inès ? Ton chat est sur moi. Je ne bouge plus, c'est ça ?", "어... 이네스? 네 고양이가 내 위에 있어. 이제 꼼짝하지 말라는 거지?"),
(I, "Figaro ne fait jamais ça. Jamais. Il a griffé mon frère, il a mordu le plombier...", "피가로는 절대 이런 짓 안 해. 절대. 내 동생을 할퀴었고, 배관공을 물었고..."),
(MA, "Il a peut-être compris que je n'étais plus un inconnu.", "내가 더는 낯선 사람이 아니라는 걸 알았나 보지."),
(I, "Ou il sent l'odeur des anchois. Tiens, goûte. Et dis-moi la vérité.", "아니면 안초비 냄새를 맡았거나. 자, 먹어 봐. 그리고 솔직하게 말해."),
(MA, "... C'est délicieux. Vraiment. Tu me dois la recette.", "...맛있다. 진짜로. 레시피는 빚진 거야."),
(I, "Ah non. Ici, les dettes vont dans l'autre sens. Tu me dois toujours un café et un croissant. Les médicaments, ça ne compte pas.",
    "어림없어. 여기선 빚이 반대 방향이야. 넌 아직 커피 한 잔이랑 크루아상 하나 빚졌어. 약은 안 쳐."),
(MA, "Évidemment. Bon, et lundi ? Que fait-on lundi ?", "당연하지. 자, 그럼 월요일은? 월요일엔 뭘 하지?"),
(I, "Lundi, Hélène nous envoie à Marseille. Une conserverie familiale à l'Estaque : soupe de poisson, tapenade, un père, deux enfants et une grosse dispute.",
    "월요일엔 엘렌이 우릴 마르세유로 보내. 레스타크의 가족 통조림 회사야. 생선 수프, 타프나드, 아버지 하나, 자식 둘, 그리고 큰 싸움."),
(MA, "Marseille... Chez toi.", "마르세유라... 너희 동네네."),
(I, "Justement. Si on est encore là-bas jeudi soir, tu viendras dîner chez mes parents. Mon père voudra te poser des questions. Beaucoup de questions.",
    "바로 그거야. 목요일 저녁까지 거기 있으면 우리 부모님 댁에 저녁 먹으러 와. 아빠가 너한테 물어보고 싶은 게 있을 거야. 아주 많이."),
(MA, "Si ton père ressemble à Figaro, je survivrai. Je viendrai.", "너희 아버지가 피가로를 닮으셨다면 난 살아남을 거야. 갈게."),
]

VOCAB = [
("B1", "avoir (39) de fièvre", "열이 (39도) 있다", "숫자 뒤의 degrés는 보통 생략. Elle a trente-neuf de fièvre. avoir de la température라고도 함."),
("B1", "avoir mal à la gorge / partout", "목이 아프다 / 온몸이 아프다", "avoir mal à + 정관사 + 신체 부위. avoir mal à la tête(머리), au ventre(배)."),
("B1", "les courbatures", "근육통, 몸살 기운", "주로 복수. 독감 증상이나 운동 뒤 뻐근함. Je suis plein(e) de courbatures."),
("B1", "tousser / la toux", "기침하다 / 기침", "Elle tousse depuis samedi. un sirop contre la toux(기침 시럽)."),
("B1", "une pastille (pour la gorge)", "(목에 좋은) 캔디, 트로키", "pastilles au miel(꿀 캔디). 약국에서 처방 없이 살 수 있다."),
("B2", "consulter (un médecin)", "(의사에게) 진찰받다", "목적어 없이 Il faut consulter.만으로도 '병원에 가 봐야 한다'는 뜻."),
("B1", "une ordonnance", "처방전", "sans ordonnance = 처방전 없이. 라발 박사의 C'est une ordonnance.는 '이건 명령이에요'라는 말장난."),
("B1", "un (médicament) générique", "제네릭(복제약)", "특허가 끝난 오리지널(princeps)과 같은 성분의 약. Je vous mets le générique ?"),
("B2", "le brevet tombe / expire", "특허가 만료되다", "tomber dans le domaine public(공공 영역이 되다). 업계에서는 la chute du brevet이라고도 한다."),
("B1", "en visio", "영상통화로", "visioconférence의 구어 축약. se connecter en visio, faire une visio."),
("B2", "emmitouflé(e)", "(따뜻하게) 꽁꽁 싸맨", "emmitouflée dans un plaid. 추운 날·감기 걸린 사람 묘사에 자주 씀."),
("B2", "passer dans le rouge", "적자로 돌아서다", "être dans le rouge = 적자 상태다 ↔ revenir dans le vert."),
("B2", "une échéance", "기한, 만기(가 닥치는 시점)", "préparer une échéance. 대출 만기·선거 일정에도 씀. à brève échéance(머지않아)."),
("B2", "tout et n'importe quoi", "아무거나 다", "부정적 뉘앙스. On ne peut pas financer tout et n'importe quoi."),
("B2", "la libération prolongée (LP)", "서방형, 지속 방출형", "약 상자에 LP로 표기. 하루 한 번 복용 제형이 많다."),
("B2", "un essai clinique / la phase trois", "임상시험 / 3상", "être en phase trois. 대규모 환자를 대상으로 하는 마지막 단계."),
("B2", "l'observance", "복약 순응도", "환자가 처방대로 약을 먹는 정도. 의료·제약 분야의 핵심 용어."),
("C1", "l'autorisation de mise sur le marché (AMM)", "시판 허가", "의약품 판매를 위한 당국 허가. obtenir l'AMM."),
("B1", "C'est serré.", "빠듯하다, 아슬아슬하다", "시간·예산·점수 차이에 모두 사용. Le calendrier est serré."),
("B2", "réclamer", "(강하게) 요구하다, 달라고 하다", "Les cardiologues le réclament. demander보다 강한 말."),
("B2", "un point d'étape / un critère d'arrêt", "중간 점검 / 중단 기준", "프로젝트 관리 용어. faire un point d'étape tous les trois mois."),
("B1", "noir sur blanc", "문서로 분명히", "écrit noir sur blanc = 명확하게 글로 적힌. 약속을 확실히 하고 싶을 때."),
("B1", "en chair et en os", "직접, 실물로", "직역 '살과 뼈로'. 화면이 아니라 직접 나타났을 때 농담처럼 씀."),
("B1", "Ne t'y habitue pas.", "익숙해지지 마.", "s'habituer à qc → y. 칭찬 뒤에 덧붙이는 장난스러운 말."),
]

GRAM = [
("B1", "건강 표현: avoir mal à / avoir du mal à / avoir l'impression que",
 "« Elle a mal à la gorge. » « Elle a mal partout. » « Si elle a du mal à respirer... » avoir mal à + 신체 부위는 '~가 아프다', avoir du mal à + 부정사는 '~하기 힘들다'로 전혀 다른 뜻이다. « Elle a l'impression qu'un camion lui est passé dessus. »처럼 avoir l'impression que + 직설법으로 몸 상태를 생생하게 묘사할 수 있다."),
("B1", "si + 현재 → 미래 / 의무 / 명령",
 "« Si nous ne faisons rien, nous perdrons près de cent soixante-quinze millions. » « Si on relance le projet ce mois-ci, nous aurons les résultats au printemps. » « Si la fièvre dure plus de trois jours, elle doit consulter un médecin. » 실현 가능한 조건은 si + 현재, 주절은 미래·현재(devoir)·명령문이 올 수 있다. si 뒤에는 절대 미래형을 쓰지 않는다."),
("B1", "가까운 미래 vs 단순미래, quand + 미래",
 "« Je vais devenir folle. »(곧 닥칠 일, aller + 부정사) / « Je me connecterai en visio. » « Je présenterai ce plan au conseil jeudi. »(계획·약속, 단순미래). 미래의 시점을 나타내는 quand 뒤에는 한국어와 달리 미래형을 쓴다: « Quand les génériques arriveront, que va-t-il se passer ? »"),
("B2", "조건법 현재: 발표에서의 가정과 정중한 추정",
 "« Une version LP, ce serait un seul comprimé par jour. » « Nous ferions concurrence à notre propre produit ? » « Combien cela rapporterait-il ? » « Vous garderiez les deux tiers des revenus. » 아직 결정되지 않은 안을 검토할 때 조건법을 쓰면 '만약 그렇게 한다면'이라는 가정이 자연스럽게 깔린다. 권고안 발표의 핵심 시제다."),
("B2", "être censé + 부정사: ~하기로 되어 있다",
 "« Tu étais censée te reposer ! » 원래 해야 할 일·기대되는 일을 말하며, 반과거로 쓰면 '그래야 했는데 안 했다'는 비난·놀림이 된다. 주어에 성·수 일치: Inès → censée. 비슷한 표현: être supposé + 부정사."),
("B2", "alors que: 대립과 모순 지적",
 "« Vous avez réduit la recherche alors que votre principal produit va perdre sa protection ? » alors que는 '~인데도, ~하는 반면'이라는 대립을 나타내며 직설법을 쓴다. 고객의 결정에 담긴 모순을 정중하지만 날카롭게 지적할 때 유용하다. 시간 의미(~하는 동안)로도 쓰이므로 문맥으로 구별한다."),
("B2", "pourquoi + 부정사 과거 / avant de + 부정사 과거",
 "« Alors pourquoi l'avoir arrêté ? » « Vous arrêterez avant d'avoir tout dépensé. » 주어를 밝히지 않고 질문하거나 순서를 말할 때 avoir/être + 과거분사의 부정사 과거를 쓴다. 목적어 대명사(l')는 avoir 앞에 온다. Vérifions avant de nous enthousiasmer.처럼 대명동사는 대명사도 주어에 맞춘다."),
("C1", "autant + 부정사 / autant que + 접속법: 기왕이면 ~하는 게 낫다",
 "« Si un patient doit passer au générique, autant que ce soit le vôtre. » autant que ce soit...는 '어차피 그렇게 된다면 차라리 ~인 편이 낫다'는 뜻으로, que 뒤에 접속법(soit)이 온다. 더 간단히 autant + 부정사: Il pleut, autant rester à la maison(비 오는데 차라리 집에 있자)."),
]

CULTURE = [
("프랑스 약국(pharmacie)",
 "녹색 십자 간판의 프랑스 약국은 약사의 상담 기능이 강해서, 가벼운 증상은 먼저 약사에게 묻는 경우가 많다. 프랑스에서는 처방 없이 사는 일반의약품도 원칙적으로 약국에서만 판매할 수 있다(약사 독점). 해열진통제 파라세타몰은 '국민 상비약'으로 통하며, 일요일·야간에는 당번 약국(pharmacie de garde)이 문을 연다. 독감 예방접종도 약국에서 받을 수 있다."),
("제네릭 의약품과 대체 조제",
 "프랑스 약사는 의사가 '대체 불가(non substituable)'라고 따로 적지 않는 한, 처방된 오리지널 약(princeps)을 같은 성분의 제네릭으로 바꿔 줄 수 있다(droit de substitution). 의료보험도 제네릭 사용을 강하게 유도해서, 의학적 이유 없이 제네릭을 거부하면 환자 부담이 커질 수 있다. 그래서 특허가 끝나면 오리지널 약의 판매가 짧은 기간에 크게 줄어든다."),
("특허 절벽(patent cliff)과 제약사의 대응",
 "의약품 특허는 출원일로부터 20년이지만 개발·허가에 오랜 시간이 걸려 실제 독점 판매 기간은 그보다 훨씬 짧다. 유럽에서는 보충보호증명서(CCP/SPC)로 최대 5년까지 보호를 늘릴 수 있다. 특허 만료를 앞둔 제약사는 복용이 편한 신제형(서방형 등) 개발, 자체 또는 제휴사를 통한 '공인 제네릭' 출시, 외부 바이오텍의 신약 후보 라이선스 도입 등으로 매출 급감에 대비한다."),
]
