# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, S = "Inès", "Mathieu", "Hélène", "Sofia"
LF, BI, PM, LE, V = "Lefort", "Biro", "Ménard", "Léa", "Vendeuse"

META = {
    "part": 1, "ep": 10,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "Papier ou pixels",
    "title_ko": "종이냐 픽셀이냐",
    "place": "5구 퐁투아즈 수영장 · 몽주 거리 빵집 · Vasseur & Associés · 2구 레오뮈르 거리 Le Courrier de Paris 본사·편집국 · 11구 오베르캉프 카페 / 어느 일요일부터 약 3주간",
    "chars": "이네스, 마티외, 엘렌, 소피아, 마리안 르포르(편집국장), 스테판 비로(대표이사), 폴 메나르(탐사 기자), 레아 퐁텐(웹 기자), 빵집 점원",
    "work": "일간지 Le Courrier de Paris(1898년 창간) — 종이 판매 매년 −12%, 디지털 구독자 6만 명, 구독 전환율 0.8%, 무료 기사 85%, 클릭 수로 기자를 평가하는 시스템",
    "life": "마티외의 첫 일요일 수영(수영복 규정 소동과 완패), 크루아상 빚 청산, 일요일 저녁 카페에서 함께 신문 읽고 토론하기, 소피아의 귀띔",
    "focus": "수영장·빵집 어휘, 미디어·구독 어휘, 의견·반박 표현(à mon avis, je ne suis pas d'accord, certes... mais), 의견 동사 부정 + 접속법, 사역 faire, 이중 대명사, 비율 표현",
    "levelmix": "B1 45% · B2 50% · C1 5%",
    "next": "제11화 Deux cultures, une entreprise — 스타트업을 인수한 엔지니어링 그룹의 문화 충돌, 그리고 커피 머신 앞에서 바티스트가 꺼낸 저녁 초대.",
}

D = [
# ---------- 1. Ouverture : la piscine ----------
(None, "Dimanche, 8 h. Piscine Pontoise, dans le 5e. Sous la verrière Art déco, Inès enchaîne les longueurs. Un coup de sifflet : le maître-nageur montre Mathieu du doigt, au bord du bassin.",
       "일요일 오전 8시. 5구 퐁투아즈 수영장. 아르데코 양식의 유리 지붕 아래서 이네스가 쉬지 않고 레인을 왕복한다. 호루라기 소리. 안전요원이 풀 가장자리에 선 마티외를 손가락으로 가리킨다."),
(I, "Bonjour, Strasbourg ! Tu es venu, finalement. Mais le maître-nageur te siffle : le short de bain est interdit ici.", "안녕, 스트라스부르! 결국 왔구나. 그런데 안전요원이 너한테 호루라기 부는 거야. 여기선 반바지 수영복 금지거든."),
(MA, "Interdit ? C'est un maillot de bain tout à fait normal !", "금지라고? 완전히 평범한 수영복인데!"),
(I, "Pas en France. Dans les piscines publiques, c'est slip ou boxer de bain, pour l'hygiène. Il y a un distributeur à l'entrée. Et n'oublie pas le bonnet.",
    "프랑스에선 아니야. 공공 수영장에선 삼각이나 사각 수영복만 돼. 위생 때문이지. 입구에 자판기가 있어. 그리고 수영모 잊지 마."),
(None, "Dix minutes plus tard, Mathieu revient en boxer bleu marine et bonnet blanc. Inès retient un fou rire.", "10분 뒤, 마티외가 남색 사각 수영복에 흰 수영모를 쓰고 돌아온다. 이네스는 터지는 웃음을 참는다."),
(MA, "Pas un mot. Bon, on fait une course ? Deux longueurs, en crawl.", "한마디도 하지 마. 자, 시합할까? 두 바퀴, 자유형으로."),
(I, "Tu es sûr ? Je nage tous les dimanches depuis l'âge de huit ans. À Marseille, on apprend à nager avant de savoir marcher.", "진심이야? 난 여덟 살 때부터 일요일마다 수영했어. 마르세유에선 걷기도 전에 수영부터 배운다고."),
(MA, "Moi, je cours tous les matins au parc Montsouris. J'ai du souffle.", "난 매일 아침 몽수리 공원을 달려. 폐활량은 자신 있어."),
(I, "Courir et nager, ce n'est pas la même chose. Allez, à trois. Un, deux, trois !", "달리기랑 수영은 달라. 자, 셋 하면 출발. 하나, 둘, 셋!"),
(None, "Inès touche le mur avec une longueur d'avance. Mathieu arrive enfin et s'accroche au bord, à bout de souffle.", "이네스가 한 바퀴나 앞서 벽을 짚는다. 마티외는 한참 뒤에 도착해 가장자리에 매달려 숨을 헐떡인다."),
(MA, "Tu... tu n'as même pas l'air fatiguée. C'est humiliant.", "너... 너 하나도 안 지쳐 보여. 굴욕적이네."),
(I, "Tu n'as pas mal nagé, pour un Alsacien. Mais tu lèves trop la tête pour respirer. Je te montrerai.", "알자스 사람치고 나쁘지 않았어. 그런데 숨 쉴 때 고개를 너무 들어. 내가 가르쳐 줄게."),
(None, "9 h 30. Une boulangerie de la rue Monge. Ils ont encore les cheveux mouillés.", "오전 9시 30분. 몽주 거리의 한 빵집. 둘 다 아직 머리가 젖어 있다."),
(MA, "Bonjour madame. Un croissant et un pain au chocolat, s'il vous plaît.", "안녕하세요. 크루아상 하나랑 팽오쇼콜라 하나 주세요."),
(V, "Voilà, monsieur. Ça fait deux euros soixante.", "여기 있습니다, 손님. 2유로 60센트입니다."),
(MA, "Tiens, Inès. Je paie enfin ma dette : un croissant. Et le pain au chocolat, ce sont les intérêts.", "자, 이네스. 드디어 빚을 갚는다. 크루아상 하나. 그리고 팽오쇼콜라는 이자야."),
(I, "Des intérêts ? Tu as des remords, Strasbourg ? Merci. Dette croissant : remboursée.", "이자까지? 양심에 찔리나 봐, 스트라스부르? 고마워. 크루아상 빚: 상환 완료."),
(MA, "Enfin ! Je me sens plus léger.", "드디어! 몸이 가벼워진 느낌이야."),
(I, "Ne te réjouis pas trop vite. Le café, tu me le dois toujours.", "너무 좋아하지 마. 커피는 아직 빚진 거야."),
(MA, "Le café, ce sera pour plus tard. Il me faut bien une dette, sinon tu arrêteras de m'appeler Strasbourg.", "커피는 나중에. 빚 하나쯤은 남겨 둬야지. 안 그러면 네가 나를 스트라스부르라고 안 부를 테니까."),
(I, "Tu as tout compris. Oh, regarde le kiosque : Le Courrier de Paris. Ce n'est pas notre client de demain ?", "제대로 알았네. 어, 저 가판대 봐. Le Courrier de Paris. 내일 우리 고객 아니야?"),

# ---------- 2. Briefing et client ----------
(None, "Lundi, 9 h. Vasseur & Associés, salle « Monceau ».", "월요일 오전 9시. 바쇠르 & 어소시에이츠, '몽소' 회의실."),
(H, "Notre client de la semaine : Le Courrier de Paris. Un quotidien fondé en 1898. Il a survécu à deux guerres mondiales, mais il pourrait ne pas survivre à Internet.",
    "이번 주 고객은 Le Courrier de Paris야. 1898년에 창간된 일간지지. 세계대전을 두 번이나 견뎠지만, 인터넷은 견디지 못할 수도 있어."),
(S, "J'ai déjà regardé les chiffres publics. Les ventes papier baissent de douze pour cent par an, et ils n'ont que soixante mille abonnés numériques.",
    "공개된 수치는 벌써 봤어요. 종이 신문 판매가 매년 12%씩 줄고, 디지털 구독자는 6만 명뿐이에요."),
(MA, "Moins douze pour cent par an... En cinq ans, ils perdent presque la moitié de leurs lecteurs papier.", "매년 12% 감소라... 5년이면 종이 독자의 거의 절반을 잃는 거네."),
(I, "Qui nous a appelés ? La rédaction ou la direction ?", "누가 우리한테 연락했어요? 편집국이에요, 경영진이에요?"),
(H, "Les deux, et c'est bien le problème. Marianne Lefort, la directrice de la rédaction, et Stéphane Biro, le directeur général. Ils ne sont d'accord sur rien, sauf sur une chose : il faut changer.",
    "둘 다. 그게 바로 문제야. 편집국장 마리안 르포르, 그리고 대표이사 스테판 비로. 둘은 아무것도 합의를 못 해. 딱 하나, 바뀌어야 한다는 것만 빼고."),
(S, "Moi, je lis Le Courrier tous les matins... sur mon téléphone. Gratuitement. Je ne me suis jamais abonnée.", "저 Le Courrier 매일 아침 읽어요... 휴대폰으로요. 공짜로. 구독은 한 번도 안 했어요."),
(H, "Voilà ta première observation de terrain, Sofia. Rendez-vous à onze heures, rue Réaumur.", "그게 네 첫 현장 관찰이야, 소피아. 11시에 레오뮈르 거리에서 만나."),
(None, "11 h. Rue Réaumur, dans le 2e. Dans le hall du Courrier de Paris, des unes encadrées racontent plus d'un siècle d'histoire.",
       "오전 11시. 2구 레오뮈르 거리. Le Courrier de Paris 로비에는 액자에 걸린 1면들이 한 세기가 넘는 역사를 들려준다."),
(LF, "Bienvenue. Vous voyez ces unes ? Le procès Dreyfus, la Libération, mai 68. Ce journal a plus de cent vingt-cinq ans.", "어서 오세요. 이 1면들 보이세요? 드레퓌스 재판, 파리 해방, 68년 5월. 이 신문은 125년이 넘었어요."),
(BI, "Et quatre millions d'euros de pertes cette année. Bonjour, Stéphane Biro, directeur général.", "그리고 올해 적자가 400만 유로죠. 안녕하세요, 대표이사 스테판 비로입니다."),
(I, "Bonjour madame Lefort, monsieur Biro. Pouvez-vous nous présenter la situation en quelques chiffres ?", "안녕하세요, 르포르 국장님, 비로 대표님. 몇 가지 숫자로 상황을 설명해 주시겠어요?"),
(BI, "Chiffre d'affaires : quarante-huit millions d'euros. Soixante-dix pour cent viennent encore du papier, ventes et publicité. Et le papier baisse de douze pour cent par an.",
     "매출은 4,800만 유로입니다. 70%가 아직 종이 신문에서 나와요. 판매와 광고죠. 그런데 종이는 매년 12%씩 줄어요."),
(MA, "Et le numérique ?", "디지털은요?"),
(BI, "Soixante mille abonnés, à sept euros par mois en moyenne, à cause des promotions. Cela fait environ cinq millions par an. Plus trois millions de publicité sur le site.",
     "구독자 6만 명, 할인 때문에 평균 월 7유로예요. 연간 약 500만 유로죠. 거기에 사이트 광고가 300만 유로고요."),
(I, "Le papier perd donc environ quatre millions de recettes par an. Pour rester à l'équilibre, le numérique devrait gagner au moins autant chaque année.",
    "그러면 종이 쪽 수입이 매년 약 400만 유로씩 줄어드는 거네요. 현상 유지만 하려 해도 디지털이 매년 최소한 그만큼은 벌어야 하고요."),
(BI, "Exactement. Ma solution est simple : on met tout le site derrière un mur payant. Plus un seul article gratuit.", "바로 그겁니다. 제 해법은 간단해요. 사이트 전체를 유료 장벽 뒤로 넣는 거죠. 무료 기사는 단 하나도 없이."),
(LF, "Et on disparaît du débat public. Si plus personne ne nous lit, à quoi sert un journal ? Je ne suis pas d'accord, Stéphane, et tu le sais.",
     "그러면 우린 공론장에서 사라져요. 아무도 우릴 안 읽으면 신문이 무슨 소용이죠? 난 동의 못 해요, 스테판. 당신도 알잖아요."),
(BI, "Marianne, un journal en faillite ne sert à rien non plus.", "마리안, 파산한 신문도 아무 소용 없어요."),
(MA, "Si je comprends bien, vous êtes d'accord sur le diagnostic, mais pas sur le remède.", "제가 제대로 이해했다면, 진단에는 동의하시지만 처방에는 동의하지 않으시는군요."),
(LF, "Certes. Mais c'est moi qui dirige la rédaction, et mes journalistes sont épuisés. Je ne leur imposerai pas un mur payant sans leur avis.",
     "그렇죠. 하지만 편집국을 이끄는 건 저예요. 그리고 우리 기자들은 지쳐 있어요. 그들 의견도 듣지 않고 유료 장벽을 강요하진 않을 거예요."),
(S, "Combien d'articles publiez-vous par jour sur le site, et quelle part est gratuite ?", "사이트에 하루 몇 개의 기사를 올리시고, 그중 무료는 얼마나 되나요?"),
(LF, "Environ cent quarante par jour. Quatre-vingt-cinq pour cent sont gratuits.", "하루 140개쯤이요. 85%가 무료예요."),
(I, "Pourrions-nous avoir vos données d'audience et d'abonnement, article par article, sur deux ans ?", "기사별 열람과 구독 데이터를 2년치 받아 볼 수 있을까요?"),
(BI, "Bien sûr. Nous mesurons tout : clics, temps de lecture, abonnements.", "물론이죠. 우린 전부 측정해요. 클릭, 읽은 시간, 구독까지."),
(S, "Et les newsletters ? Vous en avez combien ?", "뉴스레터는요? 몇 개나 있나요?"),
(LF, "Une seule, le matin : « Le Réveil du Courrier ». Cent vingt mille inscrits. C'est mon bébé.", "아침에 하나뿐이에요. '르 레베이 뒤 쿠리에'. 구독 신청자 12만 명. 제 자식 같은 거죠."),
(MA, "Nous aimerions aussi passer une soirée à la rédaction. Au moment du bouclage.", "편집국에서 저녁 시간을 보내 보고 싶습니다. 마감 시간에요."),
(LF, "Au bouclage ? À vingt-deux heures, c'est la guerre, vous savez. ... Venez jeudi. Vous verrez à quoi ressemble un vrai journal.", "마감 때요? 밤 10시면 전쟁터예요. ...목요일에 오세요. 진짜 신문사가 어떤지 보게 될 거예요."),
(BI, "Et vous verrez notre écran des clics. C'est mon outil préféré.", "그리고 저희 클릭 수 화면도 보실 거예요. 제가 제일 아끼는 도구죠."),
(LF, "Son outil préféré. Mon cauchemar.", "저 사람이 제일 아끼는 도구. 제 악몽이죠."),
(I, "Merci à tous les deux. Nous reviendrons vers vous dans deux semaines, avec des recommandations précises.", "두 분 모두 감사합니다. 2주 뒤에 구체적인 권고안을 가지고 다시 찾아뵙겠습니다."),

# ---------- 3. Analyse ----------
(None, "Mercredi, 18 h. Salle « Monceau ». Sofia projette ses graphiques au mur. Le vieux marqueur vert de Mathieu traîne sur la table.",
       "수요일 저녁 6시. '몽소' 회의실. 소피아가 벽에 그래프를 띄운다. 마티외의 낡은 초록 마커가 테이블 위에 굴러다닌다."),
(S, "J'ai analysé deux ans de données. Premier résultat : sept cent cinquante mille lecteurs viennent sur le site au moins une fois par semaine. Mais seulement zéro virgule huit pour cent s'abonnent dans l'année.",
    "2년치 데이터를 분석했어요. 첫 번째 결과. 일주일에 한 번 이상 사이트에 오는 독자가 75만 명이에요. 그런데 1년 안에 구독하는 사람은 0.8%뿐이에요."),
(I, "Zéro virgule huit ! Ils donnent tout gratuitement, alors pourquoi payer ? À mon avis, Biro a raison : il faut fermer le site, et vite.",
    "0.8%라니! 전부 공짜로 주는데 왜 돈을 내겠어? 내 생각엔 비로 말이 맞아. 사이트를 닫아야 해, 그것도 빨리."),
(MA, "Je ne suis pas d'accord. Si on ferme tout du jour au lendemain, l'audience s'effondre, la publicité aussi, et la rédaction se révolte.",
     "난 동의 못 해. 하루아침에 다 닫으면 독자도 무너지고, 광고도 무너지고, 편집국은 들고일어날 거야."),
(I, "Certes, l'audience va baisser. Mais l'audience gratuite ne paie pas les salaires. Trois millions de publicité contre cinq millions d'abonnements : fais le calcul.",
    "물론 독자는 줄겠지. 하지만 무료 독자가 월급을 주진 않아. 광고 300만 대 구독 500만, 계산해 봐."),
(MA, "Je l'ai fait. Mais le lecteur gratuit d'aujourd'hui, c'est peut-être l'abonné de demain. Si on lui ferme la porte, il ne la poussera jamais.",
     "해 봤어. 그런데 오늘의 무료 독자가 내일의 구독자일 수도 있어. 문을 닫아 버리면 그 사람은 절대 문을 밀고 들어오지 않아."),
(S, "Attendez, avant de vous disputer, regardez le deuxième résultat. Il va peut-être vous mettre d'accord.", "잠깐만요, 싸우기 전에 두 번째 결과부터 보세요. 두 분 의견이 맞춰질지도 몰라요."),
(I, "Vas-y, Sofia. On t'écoute.", "말해 봐, 소피아. 듣고 있어."),
(S, "Les inscrits à la newsletter du matin s'abonnent cinq fois plus que les autres lecteurs : quatre pour cent, contre zéro virgule huit. Et quarante-cinq pour cent l'ouvrent chaque jour. Dans le secteur, la moyenne tourne plutôt autour de vingt.",
    "아침 뉴스레터 구독 신청자들은 다른 독자보다 다섯 배 많이 유료 구독을 해요. 4% 대 0.8%. 그리고 45%가 매일 열어 봐요. 업계 평균은 20% 안팎이고요."),
(MA, "Voilà ! La newsletter, c'est la porte d'entrée. On crée une habitude, et ensuite on demande de payer.", "거봐! 뉴스레터가 입구야. 습관을 먼저 만들고, 그다음에 돈을 내 달라고 하는 거지."),
(I, "D'accord, c'est intéressant. Mais je ne pense pas qu'une newsletter suffise à sauver un journal.", "좋아, 흥미롭네. 하지만 뉴스레터 하나로 신문사를 살릴 수 있다고는 생각 안 해."),
(S, "Troisième résultat, le plus fou. Les brèves, les « cinq choses à savoir », les classements... tout ça fait soixante pour cent des clics. Et presque zéro abonnement.",
    "세 번째 결과가 제일 놀라워요. 단신, '알아야 할 다섯 가지', 순위 기사... 이런 게 클릭의 60%를 차지해요. 그런데 구독은 거의 0이에요."),
(MA, "Et qu'est-ce qui fait s'abonner les gens, alors ?", "그럼 사람들을 구독하게 만드는 건 뭔데?"),
(S, "Les enquêtes locales. Elles représentent cinq pour cent des articles, mais quarante pour cent des nouveaux abonnements.", "지역 탐사보도요. 기사의 5%밖에 안 되는데, 신규 구독의 40%를 만들어요."),
(I, "Cinq pour cent des articles, quarante pour cent des abonnements... C'est notre histoire.", "기사의 5%가 구독의 40%라... 이게 우리 스토리야."),
(MA, "Donc le journal court après les clics avec des articles qui ne rapportent rien, et il n'a plus de temps pour ceux qui rapportent.", "그러니까 이 신문은 돈 안 되는 기사로 클릭을 쫓아다니느라, 돈 되는 기사에 쓸 시간이 없는 거네."),
(I, "Bon, je l'admets : je ne crois pas qu'un mur payant total soit la seule réponse. Mais je maintiens qu'il faut un mur.", "좋아, 인정할게. 전면 유료화가 유일한 답이라고는 생각하지 않아. 그래도 장벽은 있어야 한다는 입장은 그대로야."),
(MA, "Je te propose un compromis : un mur « au compteur ». Trois articles gratuits par mois, ensuite on paie. Et les newsletters restent gratuites, avec une simple inscription.",
     "타협안을 하나 낼게. '미터제' 장벽. 한 달에 무료 기사 세 개, 그다음부터는 유료. 뉴스레터는 간단한 가입만 하면 계속 무료로."),
(I, "Trois ? Pourquoi pas cinq, ou zéro ? Ton chiffre sort d'où ?", "세 개? 왜 다섯 개나 0개가 아니고? 그 숫자 어디서 나온 거야?"),
(MA, "D'un chapeau, je l'avoue. Sofia, tu peux simuler plusieurs scénarios ?", "솔직히 말하면 그냥 지어낸 거야. 소피아, 시나리오 몇 개 시뮬레이션해 줄 수 있어?"),
(S, "Déjà fait ! Avec trois articles gratuits, le site perd environ un tiers de son audience, donc à peu près un million d'euros de publicité. Mais le taux de conversion devrait doubler.",
    "벌써 했죠! 무료 기사 세 개면 사이트 방문자가 3분의 1쯤 줄어요. 광고로 치면 약 100만 유로죠. 하지만 전환율은 두 배가 될 거예요."),
(I, "Un million de publicité en moins... Un abonné rapporte quatre-vingt-quatre euros par an, donc dix mille abonnés, huit cent quarante mille euros. Il faut un peu moins de douze mille abonnés de plus pour compenser. C'est jouable.",
    "광고 100만 유로 감소라... 구독자 한 명이 연 84유로니까, 1만 명이면 84만 유로. 그걸 메우려면 구독자가 1만 2천 명 조금 못 되게 더 필요해. 해 볼 만하네."),
(MA, "Tu vois ? Tu n'as pas tort, je n'ai pas tort. On avance.", "봐? 너도 틀리지 않았고, 나도 틀리지 않았어. 진도가 나가잖아."),
(I, "Ne prends pas cet air satisfait. Je n'ai jamais dit que tu avais raison.", "그렇게 만족스러운 표정 짓지 마. 네가 옳다고 한 적은 없어."),
(S, "Vous savez que vous vous disputez comme un vieux couple, tous les deux ?", "두 분, 꼭 오래된 부부처럼 싸우는 거 알아요?"),
(I, "Sofia !", "소피아!"),
(MA, "On ne se dispute pas, on débat. Nuance.", "싸우는 게 아니라 토론하는 거야. 차이가 있어."),
(S, "Bien sûr. Mes parents, à Lille, débattent exactement comme ça depuis trente ans.", "그럼요. 릴에 계신 우리 부모님도 30년째 딱 그렇게 토론하세요."),
(MA, "Bon. Il reste une question : pourquoi une rédaction qui a ces chiffres continue-t-elle à courir après les clics ?", "자. 질문이 하나 남았어. 이런 숫자를 가진 편집국이 왜 계속 클릭을 쫓는 걸까?"),
(I, "Peut-être que personne ne les a jamais regardés. Ou que quelqu'un n'a pas intérêt à les regarder.", "아무도 이 숫자를 들여다본 적이 없을지도 몰라. 아니면 누군가는 들여다보지 않는 게 이득이거나."),
(MA, "Ou que les journalistes sont jugés sur autre chose. Jeudi soir, au bouclage, on leur posera la question.", "아니면 기자들이 다른 걸로 평가받고 있거나. 목요일 밤 마감 때 직접 물어보자."),

# ---------- 4. Terrain : le bouclage ----------
(None, "Jeudi, 21 h 40. La rédaction du Courrier de Paris. Des téléphones qui sonnent, des cartons de pizza, et au mur un écran géant qui affiche en direct les articles les plus cliqués.",
       "목요일 밤 9시 40분. Le Courrier de Paris 편집국. 울려 대는 전화, 피자 상자, 그리고 벽에는 가장 많이 클릭된 기사를 실시간으로 보여 주는 대형 화면."),
(LF, "Bienvenue au bouclage. Dans vingt minutes, la une part à l'imprimerie. Ne gênez personne et ne touchez à rien.", "마감에 오신 걸 환영해요. 20분 뒤면 1면이 인쇄소로 넘어가요. 아무도 방해하지 말고, 아무것도 건드리지 마세요."),
(MA, "Bonsoir. Vous écrivez quoi, en ce moment ?", "안녕하세요. 지금 뭘 쓰고 계세요?"),
(LE, "Mon sixième article de la journée : « Les dix boulangeries où manger le meilleur croissant de Paris ». Regardez, il monte déjà sur l'écran.",
     "오늘 여섯 번째 기사요. '파리 최고의 크루아상을 먹을 수 있는 빵집 10곳'. 보세요, 벌써 화면에서 순위가 올라가요."),
(I, "Un classement de croissants... Mathieu, prends des notes, ça peut servir. Et cet écran, il sert à quoi exactement ?", "크루아상 순위라... 마티외, 메모해 둬. 쓸모 있을지도 몰라. 그런데 저 화면은 정확히 뭐에 쓰는 거예요?"),
(LE, "À nous classer, nous. Chaque lundi, la direction envoie le top dix des journalistes par nombre de pages vues. Et nos primes de fin d'année en dépendent.",
     "우리를 줄 세우는 데요. 매주 월요일 경영진이 페이지뷰 기준 기자 상위 10명을 보내요. 연말 성과급도 거기에 달려 있고요."),
(MA, "Depuis quand ?", "언제부터요?"),
(LE, "Depuis deux ans. Depuis l'arrivée de Stéphane Biro.", "2년 전부터요. 스테판 비로가 온 뒤로요."),
(PM, "Et depuis deux ans, je suis dernier du classement. Paul Ménard, trente ans de maison. Bonsoir.", "그리고 2년째 제가 꼴찌죠. 폴 메나르, 이 회사에서 30년 일했습니다. 안녕하세요."),
(I, "Dernier ? Pourquoi ?", "꼴찌요? 왜요?"),
(PM, "Parce que je fais des enquêtes. Ma dernière, sur les logements insalubres du 18e, m'a pris trois mois. Vingt mille clics. Léa en fait autant en deux heures avec un croissant.",
     "탐사보도를 하니까요. 지난번 18구 불량 주택 기사는 석 달이 걸렸어요. 클릭은 2만. 레아는 크루아상 하나로 두 시간 만에 그만큼 해내죠."),
(LE, "Merci, Paul...", "고마워요, 폴..."),
(PM, "Ce n'est pas un reproche, Léa. C'est le système.", "널 탓하는 게 아니야, 레아. 시스템이 그런 거지."),
(MA, "Monsieur Ménard, la direction pense que les journalistes sont contre le mur payant. C'est vrai ?", "메나르 씨, 경영진은 기자들이 유료 장벽에 반대한다고 생각하던데요. 사실인가요?"),
(PM, "Contre le payant ? Mais on le réclame depuis des années ! Ce qu'on refuse, c'est d'être jugés au clic. On ne fait pas le même métier qu'un site de recettes.",
     "유료화에 반대한다고요? 우린 몇 년째 그걸 요구하고 있어요! 우리가 거부하는 건 클릭 수로 평가받는 거예요. 우린 요리 레시피 사이트랑 같은 일을 하는 게 아니라고요."),
(LE, "Moi, je suis entrée ici pour faire du journalisme, pas pour écrire des titres racoleurs. Si ça continue, je pars.", "저는 저널리즘을 하러 여기 들어왔지, 낚시성 제목을 쓰러 온 게 아니에요. 계속 이러면 그만둘 거예요."),
(I, "Donc vous n'êtes pas contre le payant. Vous êtes contre le compteur de clics.", "그러니까 유료화에 반대하는 게 아니군요. 클릭 계수기에 반대하시는 거죠."),
(PM, "Exactement. Si un lecteur paie pour nous lire, je veux savoir ce qu'il veut lire. Pas ce sur quoi il clique par hasard dans le métro.", "바로 그거예요. 독자가 돈을 내고 우릴 읽는다면, 난 그가 뭘 읽고 싶어 하는지 알고 싶어요. 지하철에서 우연히 누르는 거 말고요."),
(MA, "Votre enquête sur les logements, elle a apporté combien d'abonnés ?", "그 주택 기사로 구독자는 몇 명이나 늘었나요?"),
(PM, "Aucune idée. Personne ne mesure ça, ici.", "전혀 모르죠. 여기선 아무도 그런 걸 안 재요."),
(I, "Nous, si. Sofia m'a envoyé les chiffres... Neuf cents abonnements dans la semaine de publication. C'est l'article le plus rentable de l'année.", "저희는 재요. 소피아가 숫자를 보내 줬어요... 기사가 나간 주에 구독 900건. 올해 가장 돈이 된 기사예요."),
(PM, "Neuf cents ? ... Et je suis dernier du classement.", "900건이요? ...그런데 내가 꼴찌라니."),
(LF, "Paul ! Vingt-deux heures ! Ta légende de photo pour la une !", "폴! 밤 10시야! 1면 사진 설명 빨리!"),
(PM, "J'arrive, Marianne ! ... Vous savez, j'ai une autre enquête dans mon tiroir. Un fournisseur d'électricité qui se dit « cent pour cent vert ». Je n'y crois pas une seconde. Mais il me faudrait trois mois, et personne ne me les donne.",
     "가요, 마리안! ...그거 아세요? 서랍 속에 다른 탐사 기사가 하나 있어요. 자기네가 '100% 친환경'이라고 떠드는 전력 공급사요. 난 그 말을 1초도 안 믿어요. 그런데 석 달이 필요하고, 아무도 그 시간을 안 줘요."),
(MA, "Gardez-la précieusement. Nous en reparlerons.", "그 기사 소중히 간직하세요. 다시 이야기하게 될 겁니다."),
(None, "22 h 05. Marianne Lefort valide la une. Quelque part en banlieue, les rotatives démarrent.", "밤 10시 5분. 마리안 르포르가 1면을 확정한다. 교외 어딘가에서 윤전기가 돌기 시작한다."),
(LF, "Alors, vous avez vu un vrai journal ?", "자, 진짜 신문사를 보셨나요?"),
(I, "Nous avons surtout vu un écran qui mesure la mauvaise chose.", "무엇보다 엉뚱한 걸 재는 화면을 봤습니다."),
(MA, "Le vrai problème, ce n'est pas le papier contre les pixels, madame Lefort. C'est ce que vous mesurez.", "진짜 문제는 종이 대 픽셀이 아닙니다, 르포르 국장님. 무엇을 측정하느냐입니다."),

# ---------- 5. Recommandations ----------
(None, "Deux semaines plus tard. Salle du conseil du Courrier de Paris. Marianne Lefort et Stéphane Biro sont assis côte à côte, sans se regarder. Hélène est au fond de la salle.",
       "2주 뒤. Le Courrier de Paris 이사회실. 마리안 르포르와 스테판 비로가 나란히 앉아 있지만 서로 쳐다보지 않는다. 엘렌은 방 뒤편에 있다."),
(I, "Madame Lefort, monsieur Biro, une phrase pour commencer : votre problème n'est pas le papier contre les pixels. Vous donnez gratuitement ce qui a le plus de valeur, et vous récompensez ce qui n'en a pas.",
    "르포르 국장님, 비로 대표님, 한 문장으로 시작하겠습니다. 문제는 종이 대 픽셀이 아닙니다. 가장 가치 있는 것은 공짜로 주고, 가치 없는 것에 보상을 하고 계십니다."),
(BI, "C'est une jolie formule. J'aimerais des chiffres.", "멋진 문장이네요. 숫자를 보고 싶군요."),
(S, "Les voici. Les brèves font soixante pour cent des clics et presque aucun abonnement. Les enquêtes locales, cinq pour cent des articles, apportent quarante pour cent des nouveaux abonnés. L'enquête de Paul Ménard sur le 18e : neuf cents abonnements en une semaine.",
    "여기 있습니다. 단신은 클릭의 60%를 차지하지만 구독은 거의 없습니다. 기사의 5%인 지역 탐사보도가 신규 구독자의 40%를 데려옵니다. 폴 메나르 기자의 18구 기사는 일주일에 900건을 만들었습니다."),
(BI, "Neuf cents pour un seul article ? Je ne le savais pas.", "기사 하나로 900건이요? 몰랐네요."),
(LF, "Moi, je m'en doutais. Mais personne ne voulait m'écouter.", "저는 짐작하고 있었어요. 다만 아무도 내 말을 들으려 하지 않았죠."),
(MA, "Notre première recommandation : un mur payant au compteur. Trois articles gratuits par mois, puis l'abonnement. Les newsletters restent gratuites, avec inscription.",
     "첫 번째 권고는 미터제 유료 장벽입니다. 한 달에 무료 기사 세 개, 그다음은 구독. 뉴스레터는 가입만 하면 계속 무료입니다."),
(BI, "Pourquoi pas tout payant, tout de suite ? C'est plus simple.", "왜 당장 전면 유료화를 안 하죠? 그게 더 간단한데요."),
(MA, "C'est plus simple, certes, mais c'est plus risqué. Avec le tout payant, vous perdriez presque toute votre audience, donc presque toute votre publicité, et vous n'auriez plus de lecteurs à convertir.",
     "더 간단한 건 맞습니다. 하지만 더 위험합니다. 전면 유료화를 하면 독자를 거의 다 잃고, 그러면 광고도 거의 다 잃고, 구독으로 전환할 독자도 남지 않습니다."),
(BI, "Et avec votre compteur ?", "당신들 미터제로는요?"),
(I, "Vous perdez environ un tiers de l'audience, soit un million d'euros de publicité. Pour le compenser, il faut un peu moins de douze mille abonnés supplémentaires. Avec un taux de conversion qui double, c'est l'affaire de quelques mois.",
    "독자의 약 3분의 1, 즉 광고 100만 유로를 잃습니다. 이를 메우려면 추가 구독자가 1만 2천 명 조금 못 되게 필요합니다. 전환율이 두 배가 되면 몇 달이면 되는 일입니다."),
(BI, "Hm. Admettons. Ensuite ?", "흠. 그렇다고 칩시다. 그다음은요?"),
(I, "Deuxièmement, les newsletters. Vous en avez une, vous en aurez six : Paris, politique, économie, culture, sport, et « l'enquête du dimanche ». Objectif : passer de cent vingt mille à trois cent mille inscrits en deux ans.",
    "둘째, 뉴스레터입니다. 지금 하나지만 여섯 개로 늘립니다. 파리, 정치, 경제, 문화, 스포츠, 그리고 '일요일의 탐사보도'. 목표는 2년 안에 구독 신청자를 12만 명에서 30만 명으로 늘리는 것입니다."),
(LF, "Six newsletters ? Avec quels journalistes ? Ils n'ont déjà plus le temps de respirer.", "뉴스레터 여섯 개요? 어떤 기자들로요? 이미 숨 쉴 시간도 없는데요."),
(MA, "C'est justement notre troisième recommandation. Aujourd'hui, une grande partie de la rédaction réécrit des brèves que tout le monde publie. On en divise le nombre par deux, et on crée une cellule d'enquête locale de six journalistes.",
     "그게 바로 세 번째 권고입니다. 지금은 편집국의 상당수가 모두가 내는 단신을 다시 쓰고 있습니다. 단신 수를 절반으로 줄이고, 기자 여섯 명으로 지역 탐사보도팀을 만듭니다."),
(BI, "Six journalistes de plus ? Avec quatre millions de pertes ?", "기자를 여섯 명이나 더요? 400만 유로 적자인데?"),
(MA, "Pas un de plus. Ce sont des postes déplacés, pas des postes créés. La masse salariale ne bouge pas.", "한 명도 더 뽑지 않습니다. 새 자리를 만드는 게 아니라 자리를 옮기는 겁니다. 인건비 총액은 그대로입니다."),
(LF, "Une cellule d'enquête... Ça fait vingt ans que j'en rêve.", "탐사보도팀이라... 20년 동안 꿈꿔 온 거예요."),
(I, "Quatrièmement, et c'est le point le plus sensible : l'évaluation des journalistes. Nous recommandons de supprimer le classement aux pages vues et de le remplacer par la contribution aux abonnements, le temps de lecture et la fidélité des lecteurs.",
    "넷째, 가장 민감한 부분입니다. 기자 평가입니다. 페이지뷰 순위를 없애고, 구독 기여도, 읽은 시간, 독자 충성도로 대체하기를 권합니다."),
(BI, "L'écran, c'est moi qui l'ai installé. Vous me dites que je me suis trompé ?", "그 화면, 제가 설치한 거예요. 제가 틀렸다는 말인가요?"),
(I, "Non. Vous avez eu raison de vouloir mesurer, monsieur Biro. Mais vous mesuriez le mauvais indicateur. Il est vrai que les clics sont faciles à compter ; cependant, ce ne sont pas eux qui paient.",
    "아닙니다. 측정하려 하신 건 옳았습니다, 비로 대표님. 다만 잘못된 지표를 재셨던 겁니다. 클릭은 세기 쉬운 게 사실입니다. 하지만 돈을 내는 건 클릭이 아닙니다."),
(BI, "... Certes. Je l'admets.", "...그렇군요. 인정합니다."),
(MA, "Enfin, le papier. Les ventes du week-end ne baissent que de trois pour cent par an, contre quinze en semaine. Nous proposons de renforcer l'édition du week-end, plus épaisse, avec les grandes enquêtes, et d'alléger la semaine.",
     "마지막으로 종이 신문입니다. 주말판 판매는 매년 3%밖에 줄지 않지만 평일판은 15% 줄고 있습니다. 주말판을 더 두툼하게, 대형 탐사보도를 담아 강화하고, 평일판은 가볍게 하기를 제안합니다."),
(LF, "Alléger la semaine... Vous voulez la mort du papier ?", "평일판을 가볍게 하자니... 종이 신문을 죽이고 싶은 건가요?"),
(MA, "Au contraire, madame Lefort. Nous voulons mettre le papier là où les lecteurs le veulent encore : le samedi matin, quand ils ont le temps de lire. Dans deux ans, vous déciderez du reste avec des chiffres.",
     "그 반대입니다, 르포르 국장님. 독자들이 아직 종이를 원하는 곳에 종이를 두자는 겁니다. 읽을 시간이 있는 토요일 아침에요. 나머지는 2년 뒤에 숫자를 보고 결정하시면 됩니다."),
(BI, "Et au bout du compte, où arrive-t-on ?", "그래서 결국 어디에 도달하죠?"),
(I, "Cent cinquante mille abonnés numériques dans trois ans, et le retour à l'équilibre à la même échéance. Mais une condition : que la rédaction et la direction présentent ce plan ensemble.",
    "3년 뒤 디지털 구독자 15만 명, 같은 시점에 흑자 전환입니다. 단, 조건이 하나 있습니다. 편집국과 경영진이 이 계획을 함께 발표하셔야 합니다."),
(MA, "Une dernière question, alors : qui décide ?", "그럼 마지막 질문 하나. 누가 결정하죠?"),
(BI, "Le conseil de surveillance vote le budget le quinze. Marianne... on y va ensemble ?", "감독이사회가 15일에 예산을 의결해요. 마리안... 같이 가겠어요?"),
(LF, "Pour une fois, Stéphane, nous serons d'accord devant le conseil. Et ce soir, j'appelle Paul Ménard : son enquête sur l'électricité « cent pour cent verte », il a trois mois.",
     "이번만은 우리가 이사회 앞에서 한목소리를 내겠네요, 스테판. 그리고 오늘 밤 폴 메나르한테 전화할 거예요. '100% 친환경' 전기에 관한 그 탐사 기사, 석 달 주겠다고요."),
(H, "Je crois que mes consultants ont réconcilié le papier et les pixels. Ce n'était pas dans la mission, mais je prends.", "제 컨설턴트들이 종이와 픽셀을 화해시킨 것 같군요. 미션에는 없던 일이지만, 받아들이죠."),

# ---------- 6. Le soir : le café ----------
(None, "Dimanche suivant, 18 h. Un café de la rue Oberkampf. Sur la table, deux thés et l'édition du week-end du Courrier de Paris, partagée en deux.",
       "다음 일요일 저녁 6시. 오베르캉프 거리의 한 카페. 테이블 위에 차 두 잔, 그리고 반으로 나눠 든 Le Courrier de Paris 주말판."),
(MA, "Écoute ça : « Paris doit interdire les voitures dans tout le centre d'ici cinq ans. » Enfin quelqu'un de raisonnable.", "이거 들어 봐. '파리는 5년 안에 도심 전체에서 자동차를 금지해야 한다.' 드디어 합리적인 사람이 나왔네."),
(I, "Raisonnable ? Je ne suis pas du tout d'accord. Et les artisans, les livreurs, les gens qui viennent de banlieue ?", "합리적이라고? 난 전혀 동의 못 해. 장인들, 배달원들, 교외에서 오는 사람들은?"),
(MA, "Certes, ce n'est pas simple, mais il y a des solutions : des bus, des parkings aux portes de Paris, des vélos-cargos...", "물론 간단하진 않지. 하지만 해법이 있어. 버스, 파리 외곽 관문의 주차장, 화물 자전거..."),
(I, "Un plombier en vélo-cargo avec tous ses outils ? Tu vis dans un monde idéal, Strasbourg.", "공구를 다 싣고 화물 자전거 타는 배관공? 너 이상 세계에 사는구나, 스트라스부르."),
(MA, "À Strasbourg, justement, ça marche très bien. Et toi, qu'est-ce que tu lis ?", "바로 그 스트라스부르에선 아주 잘 돌아가거든. 넌 뭐 읽어?"),
(I, "Un article sur l'encadrement des loyers. D'après l'auteur, ça décourage les propriétaires de louer.", "임대료 상한제에 관한 기사. 필자에 따르면 그게 집주인들이 세를 놓지 않게 만든대."),
(MA, "Après onze visites et trente personnes dans l'escalier, je peux te dire que l'encadrement, j'y suis plutôt favorable.", "집 열한 곳 보고 계단에 서른 명 줄 선 걸 겪어 본 사람으로서 말하는데, 상한제라면 난 찬성하는 편이야."),
(I, "Je ne dis pas le contraire. Je dis que le vrai problème, c'est qu'on ne construit pas assez de logements.", "반대한다는 게 아니야. 진짜 문제는 집을 충분히 짓지 않는다는 거라고."),
(MA, "Là-dessus, on est d'accord. Pour une fois.", "그건 동의해. 이번만은."),
(I, "Tu sais quoi ? J'aime bien me disputer avec toi. On ne s'ennuie jamais.", "그거 알아? 난 너랑 말다툼하는 게 좋아. 절대 지루하지 않거든."),
(MA, "Moi aussi. Mais ne le dis pas à Sofia, elle va encore parler de vieux couple.", "나도. 그런데 소피아한테는 말하지 마. 또 오래된 부부 얘기할 테니까."),
(None, "La porte s'ouvre. Sofia entre, l'écharpe jusqu'au nez.", "문이 열린다. 목도리를 코까지 두른 소피아가 들어온다."),
(S, "Je le savais ! Je passais dans la rue et j'ai reconnu ton écharpe rouge, Inès. Vous lisez le journal ensemble le dimanche, maintenant ? Mathieu, tu me prends un chocolat chaud au comptoir ?",
    "그럴 줄 알았어요! 길을 지나가다 이네스 언니 빨간 목도리를 알아봤죠. 이제 일요일마다 같이 신문 읽어요? 마티외, 카운터에서 핫초코 하나 시켜 줄래요?"),
(None, "Mathieu se lève. Sofia se penche aussitôt vers Inès.", "마티외가 일어난다. 소피아가 곧바로 이네스 쪽으로 몸을 기울인다."),
(S, "Petite info, entre nous : demain, Baptiste va t'inviter à dîner. Je l'ai entendu au téléphone vendredi : « Lundi, je tente ma chance avec Marchetti. »",
    "우리끼리 하는 얘긴데요. 내일 바티스트가 언니한테 저녁을 청할 거예요. 금요일에 통화하는 걸 들었어요. '월요일에 마르케티한테 한번 찔러 볼 거야.'"),
(I, "Baptiste ? Moi ? C'est absurde... Chut, il revient.", "바티스트가? 나한테? 말도 안 돼... 쉿, 온다."),
(MA, "Un chocolat chaud pour Sofia. Vous parliez de quoi ?", "소피아 핫초코 나왔습니다. 무슨 얘기 하고 있었어?"),
(S, "De rien ! Du Courrier, de la météo... Oh, déjà dix-huit heures trente ? Je le bois en vitesse et je file. Bon dimanche, les amoureux du journal !",
    "아무것도 아니에요! 신문 얘기, 날씨 얘기... 어, 벌써 6시 반이에요? 후딱 마시고 갈게요. 좋은 일요일 보내요, 신문 커플!"),
(I, "Bon. Que fait-on lundi, Strasbourg ?", "자. 월요일엔 뭘 하지, 스트라스부르?"),
(MA, "C'est moi qui pose cette question, d'habitude... Lundi, Hélène nous envoie chez un groupe d'ingénierie qui a racheté une start-up bordelaise. En six mois, trente pour cent des développeurs sont partis.",
     "그 질문은 보통 내가 하는데... 월요일엔 엘렌이 우리를 엔지니어링 그룹에 보내. 보르도 스타트업을 인수했는데, 여섯 달 만에 개발자 30%가 떠났대."),
(I, "Deux entreprises, deux cultures... Lundi s'annonce compliqué.", "두 회사, 두 문화라... 월요일은 복잡할 것 같네."),
]

VOCAB = [
("B1", "faire des longueurs", "(수영장에서) 레인을 왕복하다", "une longueur = 수영장 한 길이. enchaîner les longueurs = 쉬지 않고 왕복하다. avoir une longueur d'avance = 한발 앞서다(비유)."),
("B1", "le bonnet de bain", "수영모", "프랑스 공공 수영장은 대부분 수영모 착용 의무. maillot de bain(수영복), lunettes de natation(물안경)."),
("B1", "le maître-nageur", "(수영장) 안전요원, 수영 강사", "정식 명칭 maître-nageur sauveteur(MNS). 규정 위반 시 호루라기를 분다(siffler)."),
("B1", "être à bout de souffle", "숨이 턱에 차다, 녹초가 되다", "à bout de = ~이 다하다. être à bout de nerfs(신경이 곤두서다). 고다르 영화 제목이기도 하다."),
("B2", "avoir des remords", "양심의 가책을 느끼다, 뉘우치다", "복수형으로 자주 씀. Tu as des remords ? 농담으로 '찔리나 봐?'의 뜻."),
("B1", "Ne te réjouis pas trop vite.", "너무 일찍 좋아하지 마.", "se réjouir de qc = ~을 기뻐하다. Je me réjouis de vous voir(격식: 뵙게 되어 기쁩니다)."),
("B1", "un quotidien", "일간지", "hebdomadaire(주간지), mensuel(월간지). la presse quotidienne régionale(PQR, 지역 일간지)."),
("B2", "la rédaction", "편집국, 편집진", "기자 전체 또는 그 공간. directeur/directrice de la rédaction = 편집국장. rédiger(작성하다)와 같은 어원."),
("B1", "la une", "(신문) 1면", "faire la une = 1면을 장식하다. à la une = 1면에, 주요 뉴스로. 복수 les unes."),
("B2", "le bouclage", "(신문·잡지) 마감", "boucler = 버클을 채우다 → 원고를 확정해 넘기다. boucler un dossier(일을 마무리하다)."),
("B2", "un mur payant (au compteur)", "(미터제) 유료 장벽", "영어 paywall. au compteur = 계량기처럼 일정 수만큼 무료 후 유료. tout payant = 전면 유료."),
("B1", "s'abonner / un abonnement", "구독하다 / 구독", "s'abonner à un journal. un abonné = 구독자. se désabonner = 구독을 해지하다."),
("B2", "le taux de conversion", "전환율", "방문자·무료 독자가 유료 고객으로 바뀌는 비율. le taux d'ouverture(뉴스레터 열람률)도 함께."),
("B2", "les pages vues", "페이지뷰", "온라인 매체의 대표 지표. 기자를 pages vues로 평가하는 것이 이 화의 핵심 갈등."),
("B2", "une brève", "단신", "짧은 뉴스 기사. une dépêche(통신사 기사)를 짧게 고쳐 쓴 것이 많다."),
("B2", "une enquête", "탐사보도, 조사", "journalisme d'enquête = 탐사 저널리즘. 경찰 수사, 설문 조사의 뜻도 있다."),
("B2", "un titre racoleur", "낚시성 제목", "racoler = 호객하다. 클릭을 유도하는 자극적 제목. 영어 clickbait에 해당."),
("B2", "trente ans de maison", "한 회사에서 30년 근무", "maison = 회사(구어). Il a vingt ans de maison. 오래 일한 사람에 대한 존중이 담긴 표현."),
("B2", "sortir d'un chapeau", "근거 없이 툭 튀어나오다", "마술사가 모자에서 토끼를 꺼내는 이미지. Ton chiffre sort d'où ? — D'un chapeau."),
("B2", "C'est jouable.", "해 볼 만하다, 가능하다", "구어. jouer(놀다, 경기하다)에서. ↔ Ce n'est pas jouable(무리야)."),
("B2", "se douter de qc", "~을 짐작하다", "Je m'en doutais. = 그럴 줄 알았어. douter de(의심하다)와 뜻이 반대처럼 보이니 주의."),
("B2", "la masse salariale", "인건비 총액", "기업의 급여 총액(사회보장 분담금 포함). La masse salariale ne bouge pas."),
("B2", "l'encadrement des loyers", "임대료 상한제", "파리 등 일부 도시에서 시행. encadrer = 테두리를 치다 → 규제하다."),
("C1", "tenter sa chance (avec qn)", "(누구에게) 한번 대시해 보다", "원래 '운을 시험해 보다'. 연애 맥락에서는 '고백·데이트 신청을 시도하다'."),
]

GRAM = [
("B1", "의견 말하기: à mon avis / je pense que / d'après",
 "« À mon avis, Biro a raison. » « D'après l'auteur, ça décourage les propriétaires de louer. » à mon avis, selon moi, pour moi는 문장 앞에 붙여 자기 의견임을 밝힌다. d'après + 사람·출처는 '~에 따르면'으로 남의 의견을 전할 때 쓴다. « Je n'ai jamais dit que tu avais raison »처럼 avoir raison / avoir tort(옳다/틀리다)는 être가 아니라 avoir와 함께 쓴다."),
("B1", "반대와 부분 동의: je ne suis pas d'accord / je ne dis pas le contraire / tu n'as pas tort",
 "« Je ne suis pas d'accord. » « Je ne suis pas du tout d'accord. »(강한 반대) « Je ne dis pas le contraire. Je dis que... »(상대 말을 인정하면서 초점을 옮김) « Tu n'as pas tort, je n'ai pas tort. »(이중부정으로 부드러운 인정) « Là-dessus, on est d'accord. »(그 점에선 동의). 토론에서 전면 반대와 부분 동의를 구별해 쓰면 훨씬 자연스럽다."),
("B2", "양보·반박: certes..., mais / il est vrai que..., cependant",
 "« Certes, l'audience va baisser. Mais l'audience gratuite ne paie pas les salaires. » « C'est plus simple, certes, mais c'est plus risqué. » « Il est vrai que les clics sont faciles à compter ; cependant, ce ne sont pas eux qui paient. » 상대 논점을 먼저 인정(certes, il est vrai que)한 뒤 mais / cependant / pourtant으로 반박하는 2단 구조. 회의와 글쓰기에서 가장 많이 쓰는 논증 틀이다."),
("B2", "의견 동사의 부정·의문 + 접속법",
 "« Je ne pense pas qu'une newsletter suffise à sauver un journal. » « Je ne crois pas qu'un mur payant total soit la seule réponse. » penser, croire는 긍정문에서는 직설법(Je pense que c'est vrai)을 쓰지만, 부정문·의문문에서는 확신이 약해지므로 접속법(suffise, soit)을 쓴다. 9화의 il faut que, vouloir que에 이어 접속법의 두 번째 용법."),
("B2", "사역 faire + 부정사",
 "« Qu'est-ce qui fait s'abonner les gens ? » « des titres qui font cliquer » « Vous venez de nous faire gagner une semaine »(2화 복습). faire + 부정사는 '~하게 만들다'. 대명동사는 se를 그대로 둔다(faire s'abonner). 부정사의 주어는 부정사 뒤에 온다(fait s'abonner les gens)."),
("B2", "이중 대명사와 전위(dislocation)",
 "« Le café, tu me le dois toujours. » « Gardez-la précieusement. » « Si on lui ferme la porte, il ne la poussera jamais. » 간접목적(me, te, lui)과 직접목적(le, la)이 함께 오면 me/te + le/la, le/la + lui 순서. 구어에서는 « Le café, ... »처럼 명사를 문장 앞으로 빼고 대명사로 다시 받는 전위 구문이 매우 흔하다(« L'encadrement, j'y suis favorable »)."),
("B1", "부정 질문에 답하는 si / 강세형 대명사",
 "« Personne ne mesure ça, ici. — Nous, si. » « Tu n'avais pas mieux à faire ? — Si... »(2화 복습) 부정문에 반대로 답할 때는 oui가 아니라 si. 강세형 대명사(moi, toi, nous)는 대조를 강조한다: « Moi, je cours tous les matins », « Moi, je m'en doutais »."),
("B1", "비율·배수 표현",
 "« Cinq pour cent des articles, mais quarante pour cent des nouveaux abonnements. » « Ils s'abonnent cinq fois plus que les autres. » « Le site perd environ un tiers de son audience. » « On en divise le nombre par deux. » 분수는 la moitié(1/2), un tiers(1/3), un quart(1/4). 배수는 deux fois plus / cinq fois moins, 감소는 diviser par deux(절반으로 줄이다), 증가는 doubler / tripler."),
]

CULTURE = [
("파리 공공 수영장 이용법과 퐁투아즈 수영장",
 "프랑스 공공 수영장은 위생 규정상 남성의 반바지형 수영복(short de bain)을 대부분 금지하고 몸에 붙는 삼각(slip)이나 사각(boxer) 수영복을 요구한다. 수영모도 의무인 곳이 많아 입구에 자판기가 있는 경우가 흔하다. 5구의 퐁투아즈 수영장은 1930년대에 지어진 아르데코 양식 실내 수영장으로, 유리 지붕 아래 수영장을 둘러싼 층별 회랑에 탈의실(cabines)이 줄지어 있는 모습으로 유명하다."),
("프랑스 신문 산업과 디지털 전환",
 "프랑스 종이 신문은 수십 년째 판매가 줄고 있고, 신문 가판대(kiosque)도 계속 사라지고 있다. 정부는 언론 다원주의를 지키기 위해 aides à la presse(언론 지원금)를 운영하며, 신문·온라인 언론에는 2.1%의 초경감 부가가치세가 적용된다. 2010년대 이후 주요 일간지들은 일정 수의 무료 기사 뒤에 결제를 요구하는 미터제나 핵심 기사만 유료로 두는 프리미엄 모델로 전환했고, 뉴스레터와 탐사보도가 구독자 확보의 핵심 수단으로 꼽힌다."),
("편집국의 하루와 기자의 권리",
 "일간지 편집국은 오후 편집회의(conférence de rédaction)에서 1면(la une)을 정하고, 밤의 마감(bouclage) 뒤 인쇄소의 윤전기(rotatives)가 돌아간다. 프랑스 기자는 직업 윤리를 정한 1971년 뮌헨 헌장(Charte de Munich)을 기준으로 삼는 경우가 많고, 노동법상 '양심 조항(clause de conscience)'에 따라 매체의 성격이나 논조가 크게 바뀌면 퇴직 수당을 받고 스스로 회사를 떠날 수 있다. 기자 평가를 클릭 수에 묶는 것은 이런 직업 문화와 자주 충돌한다."),
]
