# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, S = "Inès", "Mathieu", "Hélène", "Sofia"
V, K, P, ME = "Voix", "Kevin", "Pichon", "Mélanie"
F, CL, DE = "Franck", "Cliente", "Delattre"

META = {
    "part": 1, "ep": 12,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "Le client qui part",
    "title_ko": "떠나는 고객",
    "place": "Vasseur & Associés · 생드니 옹데아 본사 · 아미앵 콜센터 · 14구 레몽로스랑 거리 원룸 / 약 2주간",
    "chars": "이네스, 마티외, 엘렌, 소피아, 로랑 피숑(옹데아 고객경험 이사), 카트린 들라트르(옹데아 재무 이사), 멜라니(아미앵 콜센터 상담원), 프랑크(슈퍼바이저), 케빈(상담원), 고객, 자동응답 음성",
    "work": "통신사 옹데아 — 가입자 900만, 월 해지율 2.1%(업계 평균의 두 배), 1차 해결률 48%, '통화 시간 6분' 평가 기준, 요금제 37개",
    "life": "둘 다 같은 통신사 인터넷이 끊겨 함께 고객센터에 전화하기(40분 대기, 자동응답 미로), 마티외 원룸에서의 마감 작업과 담요 아래 옛 프랑스 영화",
    "focus": "전화·고객 응대 표현, KPI·지표와 비율 설명, 조건법 과거 pouvoir, même si + 반과거, imaginons que / avant que + 접속법, dont, personne ne",
    "levelmix": "B1 45% · B2 50% · C1 5%",
    "next": "제13화 Bureaux vides — 라 데팡스의 텅 빈 오피스 타워, 그리고 센 강변의 밤.",
}

D = [
# ---------- 1. Ouverture : le service client ----------
(None, "Lundi, 8 h 40. Vasseur & Associés, la petite cuisine du quatrième étage. Inès entre, l'air furieux, son ordinateur sous le bras.",
       "월요일 오전 8시 40분. 바쇠르 & 어소시에이츠, 4층의 작은 탕비실. 이네스가 노트북을 옆구리에 끼고 화난 얼굴로 들어온다."),
(MA, "Bonjour ! Tu as une vraie tête de lundi, toi. Mauvais week-end ?", "안녕! 완전 월요일 얼굴이네. 주말 안 좋았어?"),
(I, "Plus d'internet depuis samedi soir. Ni box, ni télé, rien. J'ai dû finir mes slides dans un café d'Oberkampf, avec le wifi du bar.",
    "토요일 밤부터 인터넷이 안 돼. 공유기도, TV도, 아무것도. 오베르캉프의 카페에서 그 집 와이파이로 슬라이드를 마무리해야 했어."),
(MA, "Attends... Tu es chez quel opérateur ?", "잠깐... 너 어느 통신사야?"),
(I, "Ondéa. Pourquoi ?", "옹데아. 왜?"),
(MA, "Moi aussi ! Ma box clignote en rouge depuis samedi. Je croyais que c'était mon immeuble.", "나도야! 내 공유기도 토요일부터 빨간 불이 깜빡여. 우리 건물 문제인 줄 알았어."),
(I, "Bon. On appelle ensemble, sur haut-parleur. À deux, on aura peut-être plus de chance.", "좋아. 같이 스피커폰으로 전화하자. 둘이면 운이 좀 더 좋을지도 몰라."),
(V, "Bienvenue chez Ondéa. Pour découvrir nos nouvelles offres, tapez 1. Pour une question de facturation, tapez 2. Pour signaler une panne, tapez 3.",
    "옹데아에 오신 것을 환영합니다. 새 상품 안내는 1번, 요금 문의는 2번, 고장 신고는 3번을 눌러 주십시오."),
(MA, "Trois, c'est une panne. Vas-y.", "3번, 고장이야. 눌러."),
(V, "Vous avez tapé 3. Pour une panne de mobile, tapez 1. Pour une panne de box internet, tapez 2. Pour revenir au menu principal, tapez étoile.",
    "3번을 누르셨습니다. 휴대폰 고장은 1번, 인터넷 공유기 고장은 2번, 처음 메뉴로 돌아가시려면 별표를 눌러 주십시오."),
(I, "Deux... Allez, allez, allez.", "2번... 제발, 제발, 제발."),
(V, "Tous nos conseillers sont actuellement en ligne. Votre temps d'attente est estimé à... plus de... vingt... minutes. Merci de patienter.",
    "현재 모든 상담원이 통화 중입니다. 예상 대기 시간은... 20... 분... 이상입니다. 잠시만 기다려 주십시오."),
(None, "Une musique d'attente. Quarante minutes plus tard, Mathieu en est à son troisième café ; Inès tape du pied.",
       "대기 음악이 흐른다. 40분 뒤, 마티외는 세 번째 커피를 마시는 중이고 이네스는 발을 동동 구른다."),
(K, "Ondéa, bonjour, Kevin à votre écoute. Que puis-je faire pour vous ?", "옹데아입니다, 안녕하세요, 상담원 케빈입니다. 무엇을 도와드릴까요?"),
(I, "Enfin ! Bonjour. Notre box ne fonctionne plus depuis samedi. Enfin, nos deux box : nous avons deux contrats différents.",
    "드디어! 안녕하세요. 공유기가 토요일부터 작동을 안 해요. 아니, 공유기 두 대요. 계약이 두 건이거든요."),
(K, "Ah, deux contrats, ça fait deux dossiers : il faudra rappeler pour le deuxième. Et les pannes de box, c'est le service technique. Je vous transfère, ne quittez pas...",
    "아, 계약 두 건이면 접수도 두 건이라 두 번째는 다시 전화하셔야 해요. 그리고 공유기 고장은 기술 지원팀 담당이에요. 연결해 드릴게요, 끊지 말고 기다려 주세요..."),
(None, "Bip. Bip. Bip. La communication est coupée.", "뚜. 뚜. 뚜. 전화가 끊긴다."),
(MA, "Il a raccroché ? Quarante minutes d'attente pour être transférés dans le vide !", "끊은 거야? 40분 기다렸는데 허공으로 연결되다니!"),

# ---------- 2. Briefing et client ----------
(None, "Hélène passe la tête par la porte de la cuisine, un dossier à la main.", "엘렌이 서류철을 들고 탕비실 문으로 고개를 들이민다."),
(H, "Vous êtes en ligne avec Ondéa ? Quelle coïncidence. Salle Monceau dans cinq minutes : Ondéa, c'est notre nouveau client.",
    "옹데아랑 통화 중이야? 이런 우연이. 5분 뒤에 '몽소' 회의실로 와. 옹데아가 우리 새 고객이야."),
(I, "Tu plaisantes ? J'ai deux ou trois choses à leur dire, à notre nouveau client.", "농담이죠? 우리 새 고객한테 할 말이 좀 많은데요."),
(H, "Parfait, tu as déjà préparé ton premier entretien. Ondéa : neuf millions d'abonnés, mobile et internet. Et chaque mois, deux virgule un pour cent d'entre eux résilient leur contrat.",
    "잘됐네, 첫 인터뷰 준비는 벌써 끝났구나. 옹데아는 가입자 900만 명, 휴대폰과 인터넷 사업을 해. 그리고 매달 그중 2.1%가 계약을 해지해."),
(MA, "Deux virgule un pour cent par mois, c'est beaucoup ?", "한 달에 2.1%면 많은 거예요?"),
(H, "C'est le double de la moyenne du secteur. Et recruter un nouveau client coûte environ cinq fois plus cher que d'en garder un.",
    "업계 평균의 두 배야. 그리고 새 고객을 데려오는 데는 기존 고객을 지키는 것보다 다섯 배쯤 돈이 들어."),
(I, "Sur neuf millions d'abonnés, ça fait cent quatre-vingt-neuf mille départs par mois. Sur un an, presque un quart des clients !",
    "가입자 900만 명이면 한 달에 18만 9천 명이 떠나는 거네요. 1년이면 고객의 거의 4분의 1이에요!"),
(H, "Exactement. Le directeur de l'expérience client, Laurent Pichon, vous attend à onze heures à leur siège, à Saint-Denis. Sofia vous accompagne pour les données.",
    "바로 그거야. 고객경험 이사 로랑 피숑이 11시에 생드니 본사에서 기다려. 데이터 때문에 소피아도 같이 가."),
(MA, "On lui raconte notre conversation avec Kevin ?", "케빈이랑 통화한 얘기를 해 드릴까요?"),
(H, "Racontez-la-lui en premier. Un consultant qui est aussi un client mécontent, ça vaut toutes les études de marché.",
    "제일 먼저 해. 불만 고객이기도 한 컨설턴트라니, 어떤 시장 조사보다 값진 거야."),
(I, "Au fait, Strasbourg : trois cafés pendant l'attente, et pas un seul pour moi. Je note.", "그건 그렇고, 스트라스부르. 기다리는 동안 커피 세 잔, 나한텐 한 잔도 없었지. 적어 둘게."),
(MA, "Je te dois toujours ce café, je sais. Je te l'offrirai au bon moment.", "그 커피 아직 빚진 거 알아. 적당한 때에 살게."),
(None, "11 h. Siège d'Ondéa, à Saint-Denis. Un bureau vitré au dixième étage. Laurent Pichon, la quarantaine, a deux téléphones sur son bureau qui ne s'arrêtent pas de vibrer.",
       "오전 11시. 생드니의 옹데아 본사. 10층의 유리 벽 사무실. 40대의 로랑 피숑 책상 위에서 휴대폰 두 대가 쉴 새 없이 진동한다."),
(P, "Bonjour, merci d'être venus. Je vais être direct : nos clients partent, et je ne sais pas exactement pourquoi. J'ai des hypothèses, mais pas de certitudes.",
    "안녕하세요, 와 주셔서 감사합니다. 단도직입적으로 말하죠. 고객들이 떠나고 있는데, 정확한 이유를 모르겠어요. 가설은 있지만 확신은 없습니다."),
(I, "Bonjour monsieur Pichon. D'abord, une petite confession : mon collègue et moi sommes clients d'Ondéa. Et depuis samedi, nous n'avons plus internet.",
    "안녕하세요, 피숑 이사님. 먼저 작은 고백 하나 할게요. 저와 제 동료는 옹데아 고객입니다. 그리고 토요일부터 인터넷이 안 됩니다."),
(P, "Ah... Je suis désolé. Vous avez appelé le service client ?", "아... 죄송합니다. 고객센터에 전화해 보셨나요?"),
(MA, "Quarante minutes d'attente, un transfert, puis plus rien. La communication a été coupée.", "40분 대기, 연결 한 번, 그러고는 끝이었어요. 전화가 끊겼거든요."),
(P, "Vous avez donc vu le problème en direct. Donnez-moi vos numéros de contrat, je fais suivre vos dossiers personnellement.",
    "그럼 문제를 생생하게 보신 거네요. 계약 번호를 주세요. 제가 직접 챙기겠습니다."),
(S, "Monsieur Pichon, quels indicateurs suivez-vous aujourd'hui pour le service client ?", "피숑 이사님, 지금 고객센터는 어떤 지표를 관리하고 계세요?"),
(P, "Le taux de décroché, la durée moyenne de traitement des appels, et la satisfaction juste après l'appel. Tous nos tableaux de bord sont au vert, sauf un : la résiliation.",
    "응답률, 평균 통화 처리 시간, 그리고 통화 직후 만족도요. 대시보드는 전부 초록불입니다. 딱 하나, 해지만 빼고요."),
(I, "Tout est au vert, et les clients partent quand même. Intéressant. Que disent-ils au moment de résilier ?", "다 초록불인데 고객은 그래도 떠난다. 흥미롭네요. 해지할 때 고객들이 뭐라고 하나요?"),
(P, "Dans notre questionnaire de départ, soixante pour cent répondent « le prix ». Les opérateurs à bas coût proposent des box à quinze euros par mois ; notre revenu moyen par abonné est de trente-deux euros. Notre direction financière veut donc lancer une offre de fidélité : moins vingt pour cent pour les clients qui menacent de partir.",
    "해지 설문에서 60%가 '가격'이라고 답합니다. 저가 통신사들은 인터넷을 월 15유로에 팔고, 저희 가입자당 평균 매출은 32유로예요. 그래서 재무팀은 충성 고객 할인을 내놓고 싶어 합니다. 떠나겠다고 하는 고객에게 20% 할인이요."),
(I, "Moins vingt pour cent pour tous ceux qui menacent ? Ça peut coûter très cher. Et ça apprend aux clients à menacer.", "떠나겠다는 사람 모두에게 20% 할인이요? 비용이 엄청날 수 있어요. 게다가 고객들에게 협박하는 법을 가르치는 셈이고요."),
(P, "Je suis assez d'accord. Mais je dois présenter un plan au comité exécutif dans trois semaines, et je n'ai rien de mieux.",
    "저도 꽤 동의합니다. 그런데 3주 뒤 경영위원회에 계획을 내야 하는데, 더 나은 안이 없어요."),
(MA, "Combien de forfaits différents proposez-vous aujourd'hui ?", "현재 요금제는 몇 종류나 있나요?"),
(P, "Entre le mobile, internet, les options et les anciennes offres qu'on ne vend plus... trente-sept.", "휴대폰, 인터넷, 부가 서비스, 이제 안 파는 옛날 상품까지 합치면... 37개요."),
(S, "Pourriez-vous nous envoyer les données des appels et des résiliations sur douze mois ? Avec un identifiant client anonymisé, pour croiser les deux.",
    "12개월치 통화 데이터와 해지 데이터를 보내 주실 수 있을까요? 둘을 교차 분석할 수 있게 익명화된 고객 ID를 붙여서요."),
(P, "Vous aurez tout d'ici jeudi.", "목요일까지 전부 드리겠습니다."),
(I, "Nous voudrions aussi passer une journée dans un centre d'appels, pour écouter de vrais appels avec les conseillers.", "콜센터에서 하루를 보내고 싶습니다. 상담원들과 함께 실제 통화를 들어 보려고요."),
(P, "Allez à Amiens, c'est notre plus grand centre : quatre cent cinquante conseillers. Je préviens la direction du site.", "아미앵으로 가세요. 상담원 450명, 우리 최대 센터입니다. 현장 책임자에게 말해 두죠."),
(MA, "Merci. Une dernière question : qui décide des règles du service client, chez vous ?", "감사합니다. 마지막 질문입니다. 회사에서 고객센터 운영 규칙은 누가 정하나요?"),
(P, "Sur le papier, c'est moi. En pratique, la direction financière fixe les budgets... et les objectifs des centres d'appels viennent de là.",
    "서류상으로는 저죠. 실제로는 재무팀이 예산을 정하고... 콜센터 목표도 거기서 내려옵니다."),

# ---------- 3. Analyse ----------
(None, "Jeudi, 19 h. Vasseur & Associés. Sofia a branché son ordinateur sur le grand écran de la salle Monceau.", "목요일 저녁 7시. 바쇠르 & 어소시에이츠. 소피아가 노트북을 '몽소' 회의실 대형 화면에 연결했다."),
(S, "Bon, j'ai croisé les appels et les résiliations des douze derniers mois. Accrochez-vous.", "자, 최근 12개월 통화랑 해지 데이터를 교차 분석했어요. 마음 단단히 먹으세요."),
(I, "Vas-y. Je suis prête à tout, sauf à rentrer chez moi sans internet.", "말해 봐. 뭐든 각오돼 있어. 인터넷 없는 집에 돌아가는 것만 빼고."),
(S, "Soixante-dix pour cent des clients qui résilient ont contacté le service client au moins trois fois dans les trois mois précédents.",
    "해지한 고객의 70%가 해지 전 3개월 동안 고객센터에 최소 세 번 연락했어요."),
(MA, "Soixante-dix pour cent... Donc ils ne partent pas sur un coup de tête. Ils essaient d'abord de rester.", "70%라... 그러니까 홧김에 떠나는 게 아니네. 먼저 남으려고 애를 쓰는 거야."),
(I, "Ou ils appellent pour négocier le prix, et ils partent quand on refuse. Pichon l'a dit : soixante pour cent citent le prix.", "아니면 가격을 깎으려고 전화했다가 거절당하면 떠나는 거지. 피숑이 말했잖아, 60%가 가격을 꼽는다고."),
(S, "J'ai regardé le motif des appels. Le prix, c'est seulement quinze pour cent. Le reste, ce sont des pannes, des factures incompréhensibles, des déménagements mal gérés.",
    "통화 사유를 봤는데, 가격은 15%뿐이에요. 나머지는 고장, 이해 안 되는 요금 청구서, 엉망으로 처리된 이사 건이에요."),
(MA, "Et le taux de résolution au premier appel ?", "그럼 1차 해결률은?"),
(S, "Quarante-huit pour cent. Moins d'un appel sur deux règle le problème.", "48%요. 통화 두 번 중 한 번도 문제를 해결하지 못해요."),
(I, "D'accord, mais le prix pèse quand même. Les concurrents sont à quinze euros !", "알았어, 그래도 가격은 무시 못 해. 경쟁사는 15유로라고!"),
(MA, "Bien sûr que le prix compte. Mais quand tu rappelles pour la troisième fois et que tu attends quarante minutes, tu commences à regarder les prix des autres. Le prix, c'est la goutte d'eau qui fait déborder le vase.",
     "당연히 가격도 중요하지. 하지만 세 번째로 전화해서 40분을 기다리면 다른 회사 가격을 보기 시작하잖아. 가격은 컵을 넘치게 하는 마지막 한 방울이야."),
(I, "Jolie image. Mais une image, ce n'est pas une preuve, Strasbourg.", "멋진 비유네. 하지만 비유는 증거가 아니야, 스트라스부르."),
(S, "J'ai peut-être la preuve. Les clients dont le problème est réglé au premier appel résilient à zéro virgule huit pour cent par mois. Ceux qui ont appelé trois fois ou plus : sept pour cent.",
    "증거가 있을지도 몰라요. 첫 통화에서 문제가 해결된 고객은 월 해지율이 0.8%예요. 세 번 이상 전화한 고객은 7%고요."),
(I, "Presque neuf fois plus... Bon. Un point pour toi.", "거의 아홉 배라니... 좋아. 이번엔 네가 1점."),
(MA, "Un point pour Sofia, surtout.", "1점은 소피아 거지."),
(S, "Je prends ! Je les collectionne.", "받을게요! 모으는 중이거든요."),
(I, "Reste l'offre de fidélité de la direction financière. Moins vingt pour cent, c'est six euros quarante par client et par mois. Si un million de clients la demandent, ça coûte soixante-dix-sept millions d'euros par an.",
    "남은 건 재무팀의 충성 고객 할인이야. 20% 할인이면 고객 한 명당 매달 6유로 40센트야. 100만 명이 요구하면 연간 7,700만 유로가 들어."),
(MA, "Pour garder des clients qui partiront quand même à la prochaine panne.", "다음 고장 때 어차피 떠날 고객을 붙잡으려고 말이지."),
(I, "Exactement. On achète du temps, pas de la fidélité. Mais il faut chiffrer l'autre solution, sinon la direction financière ne nous écoutera pas.",
    "바로 그거야. 충성도가 아니라 시간을 사는 거지. 하지만 대안도 숫자로 보여 줘야 해. 안 그러면 재무팀은 우리 말을 안 들을 거야."),
(MA, "Combien vaut un dixième de point de résiliation, en clients ?", "해지율 0.1%포인트가 고객 수로는 얼마나 돼?"),
(I, "Neuf mille clients par mois. Donc si on passe de deux virgule un à un virgule quatre pour cent, on garde soixante-trois mille clients de plus chaque mois. À trente-deux euros, ça fait deux millions de chiffre d'affaires mensuel en plus, et ça s'additionne mois après mois.",
    "한 달에 9천 명. 그러니까 2.1%에서 1.4%로 낮추면 매달 6만 3천 명을 더 지키는 거야. 32유로씩이면 월 매출이 200만 유로 늘고, 그게 달마다 쌓여."),
(MA, "Et au bout d'un an ?", "그럼 1년 뒤엔?"),
(I, "Environ sept cent cinquante mille clients en plus, s'ils restent. Vingt-quatre millions d'euros de chiffre d'affaires par mois. Là, on parle la langue d'un directeur financier.",
    "그 고객들이 남는다면 약 75만 명이 더 있는 거지. 월 매출로 2,400만 유로. 이 정도면 재무 이사의 언어로 말하는 거야."),
(MA, "Reste la vraie question : pourquoi les conseillers ne règlent-ils pas les problèmes au premier appel ?", "진짜 질문이 남았어. 상담원들은 왜 첫 통화에서 문제를 해결하지 못할까?"),
(I, "Formation insuffisante, je suppose. Ou recrutement trop rapide. Dans les centres d'appels, le turnover est énorme.", "교육이 부족해서겠지. 아니면 채용을 너무 서둘렀거나. 콜센터는 이직률이 엄청나잖아."),
(MA, "Peut-être. Mais je n'aime pas juger des gens qu'on n'a jamais écoutés. Souviens-toi de Youssef, à la boulangerie.", "그럴 수도. 하지만 한 번도 이야기를 들어 보지 않은 사람들을 판단하긴 싫어. 빵집의 유세프를 기억해."),
(I, "Autre piste : la gamme. Trente-sept forfaits, dont onze anciennes offres qu'on ne vend plus. Et d'après Sofia, quarante pour cent des appels concernent la facture.",
    "다른 단서도 있어. 상품 구성이야. 요금제 37개, 그중 11개는 이제 팔지도 않는 옛날 상품이야. 그리고 소피아 말로는 통화의 40%가 요금 청구서 문의래."),
(MA, "Pas étonnant. Tu comprends ta facture Ondéa, toi ?", "놀랍지도 않네. 넌 옹데아 청구서 이해돼?"),
(I, "Non. Et je fais de la finance depuis six ans. C'est dire.", "아니. 재무 일을 6년이나 했는데도. 말 다 했지."),
(MA, "Alors, Amiens, lundi ? Il y a un train à sept heures, gare du Nord.", "그럼 월요일에 아미앵 갈까? 북역에서 7시 기차가 있어."),
(S, "Vous voulez que je vienne aussi ? ... Non, je reste ici avec mes données. Vous deux, vous travaillez mieux... en tête-à-tête.",
    "저도 같이 갈까요? ...아니에요, 전 여기 남아서 데이터 볼게요. 두 분은... 둘이서 일할 때 더 잘하시잖아요."),

# ---------- 4. Terrain : le centre d'appels ----------
(None, "Lundi, 9 h. Le centre d'appels d'Ondéa à Amiens. Un immense plateau, des rangées de bureaux, des écrans partout et un bruit continu de voix.",
       "월요일 오전 9시. 아미앵의 옹데아 콜센터. 거대한 상담실, 줄지어 늘어선 책상, 사방의 모니터, 끊이지 않는 목소리."),
(F, "Bienvenue sur le plateau ! Franck, superviseur. Je vous installe à côté de Mélanie, une de nos meilleures conseillères. Chacun aura un casque d'écoute.",
    "상담실에 오신 걸 환영합니다! 슈퍼바이저 프랑크예요. 우리 최고의 상담원 중 한 명인 멜라니 옆에 자리를 마련해 드릴게요. 한 분씩 청취용 헤드셋을 드립니다."),
(ME, "Bonjour ! Vous entendez tout, mais vous ne parlez pas, d'accord ? Le client ne sait pas que vous êtes là. Attention, ça sonne.",
     "안녕하세요! 다 들리지만 말씀은 하시면 안 돼요, 아셨죠? 고객은 두 분이 있는 걸 몰라요. 자, 전화 와요."),
(CL, "Bonjour, c'est la troisième fois que j'appelle ! Ma facture est de cinquante-huit euros au lieu de trente-cinq, et personne ne m'explique pourquoi.",
     "안녕하세요, 이번이 세 번째 전화예요! 요금이 35유로가 아니라 58유로가 나왔는데, 아무도 이유를 설명해 주지 않아요."),
(ME, "Je comprends tout à fait, madame, je regarde tout de suite... Je vois : une option télé a été ajoutée par erreur le mois dernier. Je transmets une demande de remboursement au service facturation.",
     "충분히 이해합니다, 고객님. 바로 확인해 볼게요... 아, 지난달에 TV 부가 서비스가 실수로 추가됐네요. 청구팀에 환불 요청을 전달하겠습니다."),
(CL, "Encore « transmettre » ? On m'a déjà dit ça deux fois ! Vous ne pouvez pas me rembourser, tout simplement ?", "또 '전달'이요? 벌써 두 번이나 그 말을 들었어요! 그냥 환불해 주시면 안 돼요?"),
(ME, "Je suis vraiment désolée, madame, je n'ai pas l'autorisation pour ce montant. Le service facturation vous rappellera sous dix jours. Je vous souhaite une bonne journée.",
     "정말 죄송합니다, 고객님. 이 금액은 제게 권한이 없어요. 청구팀에서 열흘 안에 다시 연락드릴 거예요. 좋은 하루 보내세요."),
(None, "Mélanie raccroche et soupire. Sur son écran, un compteur rouge affiche 6:42.", "멜라니가 전화를 끊고 한숨을 쉰다. 화면에 빨간 숫자로 6:42가 떠 있다."),
(MA, "Vous auriez pu la rembourser vous-même ?", "직접 환불해 드릴 수도 있었나요?"),
(ME, "Techniquement, oui, en deux clics. Mais au-dessus de dix euros, il faut l'accord d'un superviseur. Et ça prend du temps.", "기술적으로는요, 클릭 두 번이면 돼요. 그런데 10유로가 넘으면 슈퍼바이저 승인이 필요해요. 그러면 시간이 걸리죠."),
(I, "Et ce compteur rouge, c'est quoi ?", "그 빨간 숫자는 뭐예요?"),
(ME, "Ma durée d'appel. L'objectif, c'est six minutes en moyenne, maximum. Au-dessus, mon nom passe en rouge sur le tableau de l'équipe.",
     "제 통화 시간이에요. 목표는 평균 6분 이하예요. 넘으면 팀 현황판에서 제 이름이 빨간색으로 바뀌어요."),
(MA, "Et si vous dépassez souvent ?", "자주 넘으면요?"),
(ME, "Pas de prime à la fin du mois. Et Franck vient me voir. Il est gentil, Franck, mais il a ses objectifs, lui aussi.", "월말 수당이 없어요. 그리고 프랑크가 찾아오죠. 프랑크는 좋은 사람이지만, 그 사람도 목표가 있으니까요."),
(I, "Donc, quand un problème est compliqué, vous avez intérêt à transférer l'appel, ou à promettre un rappel ?", "그러니까 문제가 복잡하면 통화를 다른 데로 넘기거나 다시 연락하겠다고 약속하는 게 유리하겠네요?"),
(ME, "Je ne devrais pas vous le dire... mais oui. Tout le monde fait ça. Un transfert, c'est un appel court. Le problème part dans un autre service, et le client rappelle trois jours plus tard, encore plus énervé.",
     "이런 말 하면 안 되는데... 네. 다들 그래요. 연결만 해 주면 통화가 짧아지니까요. 문제는 다른 부서로 넘어가고, 고객은 사흘 뒤 더 화가 나서 다시 전화하죠."),
(MA, "Et quand il rappelle, ça compte comme un nouvel appel. Avec une nouvelle durée bien courte.", "그리고 다시 전화하면 새 통화로 집계되겠네요. 또 아주 짧은 통화 시간으로요."),
(ME, "Exactement. Sur nos tableaux, tout est vert. Pour le client, tout est rouge.", "바로 그거예요. 우리 현황판에선 전부 초록불이에요. 고객에게는 전부 빨간불이고요."),
(F, "Mélanie, douze appels en attente ! On accélère, s'il te plaît.", "멜라니, 대기 통화 열두 건이야! 속도 좀 내 줘."),
(I, "Une dernière question, Mélanie. Imaginons que vous soyez directrice du service client demain. Vous commencez par quoi ?", "마지막 질문이에요, 멜라니 씨. 내일 멜라니 씨가 고객센터 책임자가 된다고 해 봐요. 무엇부터 하시겠어요?"),
(ME, "Je donnerais aux conseillers le droit de régler les problèmes, jusqu'à cinquante euros, sans demander à personne. Et on nous jugerait sur les problèmes résolus, pas sur les minutes.",
     "상담원들에게 문제를 해결할 권한을 주겠어요. 50유로까지는 아무한테도 묻지 않고요. 그리고 우리를 몇 분 통화했는지가 아니라 몇 건을 해결했는지로 평가하겠죠."),
(MA, "Vous savez que vous venez de résumer notre mission en deux phrases ?", "방금 저희 프로젝트를 두 문장으로 요약하신 거 아세요?"),
(ME, "Alors dites-le à Paris. Ici, on le répète depuis des années, mais personne ne nous écoute.", "그럼 파리에 말해 주세요. 여기선 몇 년째 그 말을 하는데 아무도 안 들어 줘요."),
(None, "Le soir, dans le train du retour. Par la fenêtre, la campagne picarde défile, plate et grise.", "저녁, 돌아오는 기차 안. 창밖으로 평평하고 잿빛인 피카르디 들판이 스쳐 간다."),
(I, "Six minutes. Tout le service client tourne autour de six minutes. Et ceux qui ont fixé cet objectif n'ont sans doute jamais mis les pieds à Amiens.",
    "6분. 고객센터 전체가 6분을 중심으로 돌아가. 그 목표를 정한 사람들은 아마 아미앵에 발도 들여 본 적 없을 거야."),
(MA, "Tu te souviens de ta théorie de jeudi ? « Formation insuffisante. »", "목요일에 네가 세운 이론 기억나? '교육 부족.'"),
(I, "Oui, oui, tu avais raison. Mélanie est parfaitement formée : c'est le système qui l'empêche de bien travailler. Et ne fais pas cette tête-là, Strasbourg.",
    "그래, 그래, 네 말이 맞았어. 멜라니는 완벽하게 교육받았어. 제대로 일하지 못하게 막는 건 시스템이야. 그리고 그런 표정 짓지 마, 스트라스부르."),
(MA, "Quelle tête ? Je savoure, c'est tout.", "무슨 표정? 그냥 음미하는 중이야."),

# ---------- 5. Recommandations ----------
(None, "Dix jours plus tard. Siège d'Ondéa, salle du comité exécutif. Laurent Pichon, la directrice financière Catherine Delattre, et Sofia au fond de la salle avec son ordinateur.",
       "열흘 뒤. 옹데아 본사 경영위원회 회의실. 로랑 피숑, 재무 이사 카트린 들라트르, 그리고 노트북을 든 소피아가 방 뒤편에 있다."),
(I, "Monsieur Pichon, madame Delattre, merci. Une phrase pour commencer : vos clients ne partent pas parce qu'Ondéa est trop chère. Ils partent parce qu'ils ont appelé trois fois sans obtenir de solution.",
    "피숑 이사님, 들라트르 이사님, 감사합니다. 한 문장으로 시작하겠습니다. 고객들은 옹데아가 비싸서 떠나는 게 아닙니다. 세 번이나 전화했는데 해결책을 얻지 못해서 떠납니다."),
(DE, "Nos questionnaires de départ disent le contraire. Le prix arrive en premier, à soixante pour cent.", "해지 설문은 반대로 말하는데요. 가격이 60%로 1위예요."),
(MA, "C'est la réponse qu'ils donnent au moment de partir. Mais regardez leur parcours : soixante-dix pour cent des clients qui résilient ont contacté le service client au moins trois fois dans les trois mois précédents.",
     "떠나는 순간에 하는 대답이죠. 하지만 그들이 거쳐 온 과정을 보십시오. 해지 고객의 70%가 해지 전 3개월 동안 고객센터에 최소 세 번 연락했습니다."),
(I, "Et voici le chiffre clé : un client dont le problème est réglé au premier appel résilie à zéro virgule huit pour cent par mois. Après trois appels ou plus, c'est sept pour cent.",
    "그리고 핵심 수치는 이겁니다. 첫 통화에서 문제가 해결된 고객의 월 해지율은 0.8%입니다. 세 번 이상 전화한 고객은 7%입니다."),
(P, "Presque neuf fois plus... Et notre taux de résolution au premier appel est de quarante-huit pour cent.", "거의 아홉 배군요... 그리고 우리 1차 해결률은 48%고요."),
(MA, "Oui. Et ce n'est pas la faute des conseillers. À Amiens, nous avons écouté des appels pendant une journée. Les conseillers sont évalués sur la durée moyenne de traitement : six minutes maximum. Alors, quand un problème est compliqué, ils transfèrent ou promettent un rappel. Une conseillère, Mélanie, nous l'a expliqué très simplement.",
     "네. 그리고 그건 상담원 탓이 아닙니다. 아미앵에서 하루 동안 통화를 들었습니다. 상담원들은 평균 처리 시간, 즉 최대 6분으로 평가받습니다. 그래서 문제가 복잡하면 다른 부서로 넘기거나 다시 연락하겠다고 약속합니다. 멜라니라는 상담원이 아주 간단하게 설명해 주더군요."),
(DE, "La durée des appels, c'est notre premier poste de coût. Si les appels durent plus longtemps, il faudra embaucher plus de conseillers.", "통화 시간은 우리의 가장 큰 비용 항목이에요. 통화가 길어지면 상담원을 더 뽑아야 할 거예요."),
(I, "À court terme, c'est vrai, madame Delattre. Mais aujourd'hui, un même problème génère trois appels courts au lieu d'un appel un peu plus long. Au total, vous payez plus de minutes, pas moins.",
    "단기적으로는 맞습니다, 들라트르 이사님. 하지만 지금은 같은 문제 하나가 조금 긴 통화 한 번 대신 짧은 통화 세 번을 만들어 냅니다. 결국 통화 시간을 덜이 아니라 더 많이 쓰고 계신 겁니다."),
(DE, "Vous avez chiffré ça ?", "그걸 수치로 계산해 보셨나요?"),
(S, "Oui, madame. Pour les clients qui ont appelé trois fois ou plus, le temps total par problème est de vingt et une minutes en moyenne. Un appel bien traité dure entre dix et douze minutes.",
    "네, 이사님. 세 번 이상 전화한 고객의 경우 문제 하나당 총 통화 시간이 평균 21분입니다. 제대로 처리된 통화는 10분에서 12분 걸립니다."),
(DE, "Hm. Continuez.", "흠. 계속하세요."),
(I, "Nous avons quatre recommandations. Premièrement, changer d'indicateur principal : les conseillers et les centres seront évalués sur le taux de résolution au premier appel, et non plus sur la durée. Objectif : passer de quarante-huit à soixante-dix pour cent en dix-huit mois.",
    "권고안은 네 가지입니다. 첫째, 핵심 지표를 바꿉니다. 상담원과 센터를 이제 통화 시간이 아니라 1차 해결률로 평가합니다. 목표는 18개월 안에 48%에서 70%로 올리는 것입니다."),
(P, "Les primes des conseillers aussi ?", "상담원 수당도요?"),
(MA, "Les primes aussi. Sinon, rien ne changera. Deuxièmement : donner du pouvoir aux conseillers. Aujourd'hui, au-dessus de dix euros, il faut l'accord d'un superviseur. Nous proposons qu'un conseiller puisse accorder seul un geste commercial jusqu'à cinquante euros.",
     "수당도요. 그러지 않으면 아무것도 바뀌지 않습니다. 둘째, 상담원에게 권한을 줍니다. 지금은 10유로가 넘으면 슈퍼바이저 승인이 필요합니다. 상담원이 50유로까지는 혼자서 보상을 해 줄 수 있게 하자고 제안합니다."),
(DE, "Cinquante euros ? Sur des millions d'appels ? Vous imaginez les abus ?", "50유로요? 수백만 건의 통화에서요? 남용될 게 상상이 안 되세요?"),
(MA, "Nous l'avons simulé avec Sofia. Même si dix pour cent des conseillers en abusaient, le coût resterait très inférieur à celui de l'offre à moins vingt pour cent. Et un contrôle a posteriori suffit pour repérer les abus.",
     "소피아와 시뮬레이션해 봤습니다. 상담원의 10%가 남용한다 해도 비용은 20% 할인안보다 훨씬 적습니다. 그리고 남용을 잡아내는 데는 사후 점검이면 충분합니다."),
(I, "Justement, parlons de cette offre. Moins vingt pour cent, c'est six euros quarante par client et par mois. Si un million de clients la demandent, cela coûte soixante-dix-sept millions d'euros par an. Pour retenir des clients qui partiront à la prochaine panne.",
    "마침 그 할인안 이야기를 하죠. 20% 할인은 고객 한 명당 매달 6유로 40센트입니다. 100만 명이 요구하면 연간 7,700만 유로가 듭니다. 다음 고장 때 떠날 고객을 붙잡으려고요."),
(DE, "Je reconnais que le chiffre fait réfléchir.", "그 숫자는 생각해 볼 만하다는 걸 인정하죠."),
(I, "Troisièmement : simplifier la gamme. Vous avez trente-sept forfaits, dont onze que vous ne vendez plus. Nous proposons d'en garder huit, et de faire basculer progressivement les anciens clients, sans hausse de prix.",
    "셋째, 상품 구성을 단순화합니다. 요금제가 37개인데, 그중 11개는 이제 팔지도 않습니다. 8개만 남기고, 기존 고객은 요금 인상 없이 단계적으로 옮기자고 제안합니다."),
(P, "Sans hausse de prix ? Certains anciens forfaits sont plus rentables que les nouveaux...", "요금 인상 없이요? 옛날 요금제 중 몇 개는 새 요금제보다 수익성이 좋은데요..."),
(I, "Certains, oui. Mais quarante pour cent des appels concernent la facture. Une gamme simple, c'est moins d'appels, moins d'erreurs, et des clients qui comprennent ce qu'ils paient.",
    "몇 개는 그렇죠. 하지만 통화의 40%가 요금 청구서 문의입니다. 상품이 단순하면 통화도 줄고, 오류도 줄고, 고객은 자기가 뭘 내는지 이해하게 됩니다."),
(MA, "Quatrièmement : arrêter d'attendre que les clients appellent pour partir. Sofia a construit un modèle qui repère les clients à risque : plusieurs appels en un mois, une panne non résolue, une fin d'engagement proche.",
     "넷째, 고객이 떠나겠다고 전화할 때까지 기다리지 않는 겁니다. 소피아가 해지 위험 고객을 찾아내는 모델을 만들었습니다. 한 달에 여러 번 전화, 해결 안 된 고장, 곧 끝나는 약정 기간 같은 신호로요."),
(S, "Le modèle identifie environ cent vingt mille clients à risque chaque mois. On les appelle avant qu'ils ne résilient, avec un vrai conseiller et une vraie solution.",
    "이 모델은 매달 약 12만 명의 위험 고객을 찾아냅니다. 그들이 해지하기 전에 저희가 먼저 연락하는 겁니다. 진짜 상담원과 진짜 해결책을 가지고요."),
(P, "Combien tout cela peut-il nous rapporter ?", "이 모든 게 우리에게 얼마나 이익이 될까요?"),
(I, "Notre objectif : faire passer le taux de résiliation de deux virgule un à un virgule quatre pour cent en dix-huit mois. Cela fait soixante-trois mille clients gardés chaque mois. Au bout d'un an, environ vingt-quatre millions d'euros de chiffre d'affaires mensuel en plus.",
    "목표는 18개월 안에 해지율을 2.1%에서 1.4%로 낮추는 것입니다. 매달 6만 3천 명의 고객을 지키는 셈입니다. 1년 뒤에는 월 매출이 약 2,400만 유로 늘어납니다."),
(DE, "Si vos hypothèses sont justes.", "당신들 가설이 맞다면요."),
(MA, "C'est pour ça que nous proposons de commencer par un test : le centre d'Amiens pendant trois mois, avec les nouveaux indicateurs et les nouveaux pouvoirs. Si la résolution au premier appel ne monte pas, on arrête.",
     "그래서 시범 운영부터 하자고 제안하는 겁니다. 아미앵 센터에서 3개월 동안 새 지표와 새 권한으로요. 1차 해결률이 오르지 않으면 중단합니다."),
(DE, "Un test limité, avec un budget limité... Ça, je peux le défendre devant le comité.", "범위도 예산도 제한된 시범 운영이라... 그거라면 위원회 앞에서 지지할 수 있어요."),
(P, "Alors c'est décidé : on commence par Amiens, et je présente le plan complet au comité exécutif lundi. Il me faut votre rapport écrit avant. Et madame Marchetti... votre box, elle marche ?",
    "그럼 결정됐습니다. 아미앵부터 시작하고, 월요일 경영위원회에 전체 계획을 올리겠습니다. 그 전에 서면 보고서가 필요합니다. 그리고 마르케티 씨... 공유기는 이제 되나요?"),
(I, "Celle de Mathieu est revenue en deux jours. La mienne, non : la fibre de mon immeuble a été arrachée par des travaux dans la rue. Un technicien doit passer dans dix jours. Je suis votre cliente la plus patiente.",
    "마티외 건 이틀 만에 돌아왔어요. 제 건 아니에요. 길거리 공사 때문에 우리 건물 광케이블이 뜯겨 나갔대요. 기사님이 열흘 뒤에 오신대요. 제가 이사님 고객 중에 제일 참을성 있는 고객일 거예요."),

# ---------- 6. Le soir : le studio ----------
(None, "Vendredi, 19 h. Le studio de Mathieu, rue Raymond-Losserand. Inès arrive avec son ordinateur et une bouteille de vin.",
       "금요일 저녁 7시. 레몽로스랑 거리의 마티외 원룸. 이네스가 노트북과 와인 한 병을 들고 도착한다."),
(MA, "Entre. Bienvenue dans le seul endroit du 14e où une box Ondéa fonctionne.", "들어와. 14구에서 옹데아 공유기가 작동하는 유일한 곳에 온 걸 환영해."),
(I, "Merci de m'accueillir. Pichon veut le rapport lundi à huit heures, et chez moi, c'est toujours le désert numérique.", "받아 줘서 고마워. 피숑은 월요일 8시까지 보고서를 원하는데, 우리 집은 여전히 디지털 사막이야."),
(MA, "Installe-toi à la table. J'ai fait une tarte à l'oignon, la recette de Mamie Odile. On mange, et on finit le rapport.", "식탁에 자리 잡아. 양파 타르트 만들었어, 오딜 할머니 레시피야. 먹고 나서 보고서 끝내자."),
(I, "Une tarte à l'oignon, un vendredi soir, avec un rapport à finir... Tu sais recevoir, Strasbourg.", "금요일 밤에, 끝내야 할 보고서랑 양파 타르트라... 손님 대접할 줄 아네, 스트라스부르."),
(I, "Page quarante-deux : « Le taux de résolution au premier appel devient l'indicateur principal. » Ça te va ?", "42쪽. '1차 해결률을 핵심 지표로 삼는다.' 이거 괜찮아?"),
(MA, "Parfait. Et mets la phrase de Mélanie à la fin : « Sur nos tableaux, tout est vert. Pour le client, tout est rouge. »", "완벽해. 그리고 마지막에 멜라니의 말을 넣자. '우리 현황판에선 전부 초록불. 고객에게는 전부 빨간불.'"),
(I, "C'est fait. On envoie ?", "넣었어. 보낼까?"),
(MA, "On envoie. ... Voilà : envoyé à vingt-trois heures quatorze. Ton dernier métro passe dans vingt minutes.", "보내자. ...됐다. 밤 11시 14분에 전송 완료. 네 막차가 20분 뒤에 와."),
(I, "Vingt minutes... J'ai encore un peu de temps. Qu'est-ce que tu regardais, avant que j'arrive ?", "20분이라... 아직 시간 좀 있네. 나 오기 전에 뭐 보고 있었어?"),
(MA, "Un vieux film que ma grand-mère adore : Les Parapluies de Cherbourg. Tu connais ?", "할머니가 정말 좋아하시는 옛날 영화. '쉘부르의 우산'. 알아?"),
(I, "Tout le monde le connaît. Ils chantent pendant tout le film, et ça finit mal. Mets-le. Je reste dix minutes.", "모르는 사람이 어딨어. 영화 내내 노래하고, 결말이 슬프지. 틀어 봐. 10분만 있을게."),
(None, "Une heure plus tard. Le dernier métro est passé depuis longtemps. Ils sont sur le canapé, sous la même couverture ; leurs mains se sont trouvées. À l'écran, une station-service sous la neige.",
       "한 시간 뒤. 막차는 이미 오래전에 떠났다. 두 사람은 소파에서 담요 하나를 함께 덮고 있다. 두 손이 어느새 맞잡혀 있다. 화면에는 눈 내리는 주유소."),
(I, "Je déteste cette fin. Ils s'aimaient, et ils ont laissé la vie décider à leur place.", "이 결말 정말 싫어. 서로 사랑했는데, 삶이 대신 결정하게 내버려 뒀잖아."),
(MA, "Peut-être qu'ils avaient peur. Ou qu'ils attendaient le bon moment.", "어쩌면 두려웠던 거겠지. 아니면 적당한 때를 기다렸거나."),
(I, "Mathieu... C'est une mauvaise idée, nous deux. On travaille ensemble.", "마티외... 우리 둘, 좋은 생각이 아니야. 우린 같이 일하잖아."),
(MA, "Je sais.", "알아."),
(None, "Mais il ne lâche pas sa main. Elle non plus.", "하지만 그는 그녀의 손을 놓지 않는다. 그녀도 마찬가지다."),
(I, "C'est tout ? Toi qui as toujours trois questions ?", "그게 다야? 늘 질문 세 개를 달고 다니는 사람이?"),
(MA, "J'en ai une, ce soir. Que fait-on lundi ?", "오늘 밤엔 하나만 있어. 월요일엔 뭘 하지?"),
(I, "Lundi, Pichon lit notre rapport, et Hélène nous donne un nouveau dossier. Elle m'a écrit tout à l'heure : une foncière avec six tours de bureaux à La Défense, presque un tiers vides.",
    "월요일엔 피숑이 우리 보고서를 읽고, 엘렌이 새 사건을 줄 거야. 아까 문자가 왔어. 라 데팡스에 오피스 타워 여섯 개를 가진 부동산 회사인데, 거의 3분의 1이 비어 있대."),
(MA, "Des bureaux vides... Et ce soir ? Le dernier métro est parti depuis longtemps.", "텅 빈 사무실이라... 그럼 오늘 밤은? 막차는 한참 전에 떠났는데."),
(I, "Je vais appeler un taxi. ... Dans cinq minutes. Ne bouge pas, Strasbourg.", "택시 부를게. ...5분 뒤에. 움직이지 마, 스트라스부르."),
(None, "Le film est fini depuis longtemps. Le menu du DVD tourne en boucle. Ni l'un ni l'autre ne bouge.", "영화는 끝난 지 오래다. DVD 메뉴 화면이 계속 반복된다. 두 사람 중 누구도 움직이지 않는다."),
]

VOCAB = [
("B1", "un opérateur (télécom)", "통신사", "Tu es chez quel opérateur ? = 어느 통신사 써? 'chez + 회사'로 가입처를 말한다."),
("B1", "la box (internet)", "인터넷 공유기(모뎀)", "프랑스에서 인터넷·TV·전화를 묶은 단말기를 그냥 la box라고 부른다. Ma box clignote en rouge."),
("B1", "tapez 1 / tapez étoile", "1번을 누르세요 / 별표를 누르세요", "자동응답(ARS) 표현. 우물 정(#)은 dièse. Pour revenir au menu principal, tapez étoile."),
("B1", "Merci de patienter.", "잠시 기다려 주십시오", "patienter = 참고 기다리다. 전화·창구 안내의 정형 표현. Veuillez patienter도 같은 뜻."),
("B1", "Ne quittez pas.", "끊지 말고 기다려 주세요", "전화를 연결·보류할 때. 직역 '떠나지 마세요'. Je vous transfère, ne quittez pas."),
("B1", "raccrocher / décrocher", "전화를 끊다 / 받다", "수화기를 '걸다/내리다'에서 온 말. Il a raccroché ! 응답률은 le taux de décroché."),
("B1", "transférer un appel", "통화를 (다른 부서로) 연결하다", "un transfert = 연결, 이관. 콜센터에선 해결 대신 떠넘기는 것을 뜻하기도 한다."),
("B2", "résilier un contrat / la résiliation", "계약을 해지하다 / 해지", "통신·보험·임대 계약에 쓴다. 해지율 = le taux de résiliation(영어 churn)."),
("B1", "un abonné / un abonnement", "가입자 / 가입, 구독", "neuf millions d'abonnés. s'abonner à = ~에 가입하다."),
("B2", "le revenu moyen par abonné", "가입자당 평균 매출(ARPU)", "통신업 핵심 지표. Notre revenu moyen par abonné est de trente-deux euros."),
("B2", "le taux de résolution au premier appel", "1차 해결률(FCR)", "고객 문의가 첫 통화에서 해결되는 비율. Moins d'un appel sur deux règle le problème."),
("B2", "la durée moyenne de traitement (DMT)", "평균 처리 시간", "콜센터 효율 지표. 지나치게 짧게 관리하면 '떠넘기기'를 부른다."),
("B2", "un tableau de bord / être au vert", "대시보드 / (지표가) 양호하다", "신호등 색으로 상태를 말한다. passer au rouge = 경고 상태가 되다."),
("B1", "un forfait", "요금제, 정액제", "un forfait mobile. 스키장 리프트권, 여행 패키지도 forfait."),
("B2", "un geste commercial", "(고객 불만에 대한) 보상, 서비스 할인", "faire un geste commercial = 금액 일부를 깎아 주거나 환불해 주다."),
("B2", "une fin d'engagement", "약정 기간 만료", "s'engager sur 12 mois = 12개월 약정하다. sans engagement = 무약정."),
("B2", "la goutte d'eau qui fait déborder le vase", "결정타, 마지막 한 방울", "쌓인 불만 끝에 마지막 사건이 폭발을 부를 때. 직역 '꽃병을 넘치게 하는 물방울'."),
("B2", "croiser des données", "데이터를 교차 분석하다", "두 자료를 공통 키(고객 ID)로 맞대어 보는 것. croiser les appels et les résiliations."),
("B1", "un plateau (d'appels) / un casque", "(콜센터) 상담실 / 헤드셋", "plateau = 넓게 트인 작업 공간. 방송 스튜디오도 plateau."),
("B2", "avoir intérêt à + 부정사", "~하는 편이 이득이다", "Vous avez intérêt à transférer l'appel. 경고로도: T'as intérêt à venir ! (꼭 와야 할걸!)"),
("C1", "a posteriori", "사후에, 사후적으로", "라틴어 유래. un contrôle a posteriori = 사후 점검. ↔ a priori(사전에)."),
("B1", "Accrochez-vous !", "마음 단단히 먹으세요!", "s'accrocher = 꽉 붙잡다. 놀랄 소식을 전하기 전에 쓰는 구어."),
("B2", "C'est dire.", "말 다 했지", "앞의 말이 얼마나 심한 상황인지 보여 줄 때. Je fais de la finance depuis six ans. C'est dire."),
("B2", "sur un coup de tête", "홧김에, 충동적으로", "Ils ne partent pas sur un coup de tête. 깊이 생각하지 않은 결정."),
("B1", "le dernier métro", "막차(지하철)", "파리 메트로는 보통 새벽 1시 전후, 금·토는 더 늦게까지. 트뤼포 영화 제목이기도 하다."),
]

GRAM = [
("B1", "전화 표현: 명령형과 정형 문구",
 "« Merci de patienter. » « Je vous transfère, ne quittez pas... » « Pour revenir au menu principal, tapez étoile. » 자동응답과 상담원은 명령형(tapez, ne quittez pas)이나 merci de + 부정사(정중한 명령)를 쓴다. 상담원의 첫인사 « Kevin à votre écoute. Que puis-je faire pour vous ? »에서는 주어-동사 도치(puis-je)로 격식을 갖춘다. 전화 끊기는 raccrocher, 받기는 décrocher."),
("B1", "비율·수치 설명: pour cent, le double, un sur deux, ça fait",
 "« C'est le double de la moyenne du secteur. » « Moins d'un appel sur deux règle le problème. » « Presque neuf fois plus... » « Sur neuf millions d'abonnés, ça fait cent quatre-vingt-neuf mille départs par mois. » 소수점은 virgule로 읽는다(deux virgule un pour cent). 계산 결과는 ça fait / cela fait로 말하고, '~명 중 ~명'은 un sur deux처럼 sur를 쓴다."),
("B2", "고객 응대의 공손 표현",
 "« Je comprends tout à fait, madame, je regarde tout de suite. » « Je suis vraiment désolée, je n'ai pas l'autorisation pour ce montant. » « Je vous souhaite une bonne journée. » 공감(je comprends) → 행동(je regarde) → 사과와 한계 설명(je suis désolée, je n'ai pas...) → 마무리 인사의 순서가 프랑스 콜센터의 기본 화법이다. 하지만 이 장면은 공손한 말만으로는 문제가 해결되지 않는다는 걸 보여 준다."),
("B2", "조건법 과거 pouvoir: '~할 수도 있었다'",
 "« Vous auriez pu la rembourser vous-même ? » avoir의 조건법(auriez) + pu는 '(실제로는 안 했지만) ~할 수 있었다'는 가능성이나 가벼운 비난을 나타낸다. Tu aurais pu m'appeler ! (전화라도 하지 그랬어!) devoir도 같은 구조: Je n'aurais pas dû le dire(말하지 말았어야 했는데). 멜라니의 « Je ne devrais pas vous le dire »는 조건법 현재로 '말하면 안 되는데'라는 뜻이다."),
("B2", "même si + 반과거 → 조건법 현재 (양보 가정)",
 "« Même si dix pour cent des conseillers en abusaient, le coût resterait très inférieur. » même si는 '설령 ~하더라도'. 가능성이 낮은 가정이면 si와 똑같이 반과거 + 조건법을 쓴다. 상대의 반론(Vous imaginez les abus ?)을 인정하면서도 결론을 지키는 협상 화법이다. 멜라니의 « Je donnerais... Et on nous jugerait... »도 가정에 대한 조건법 답변이다."),
("B2", "imaginons que / avant que + 접속법",
 "« Imaginons que vous soyez directrice du service client demain. » « On les appelle avant qu'ils ne résilient. » 가정을 제시하는 imaginons que, supposons que와 시간 접속사 avant que 뒤에는 접속법을 쓴다(vous soyez). avant que 뒤의 ne는 부정의 뜻이 없는 허사 ne로, 격식체에서 붙인다. résilient은 직설법과 접속법 형태가 같다. 반면 après que 뒤에는 직설법을 쓴다."),
("B2", "관계대명사 dont: '그중', '~의'",
 "« Trente-sept forfaits, dont onze anciennes offres qu'on ne vend plus. » « Un client dont le problème est réglé au premier appel... » 숫자·명사 뒤의 dont은 '그중 ~'이라는 뜻으로 부분을 꺼낸다(dont onze). 두 번째 문장의 dont은 de를 포함한 관계대명사로 le problème du client = le problème dont...의 구조다. 보고서·발표에서 매우 자주 쓴다."),
("B1", "주어 자리의 부정어: personne ne / rien ne",
 "« Personne ne m'explique pourquoi. » « Personne ne nous écoute. » « Sinon, rien ne changera. » personne, rien이 주어일 때는 문장 맨 앞에 오고 동사 앞에 ne만 붙인다(pas 없음). 목적어일 때와 비교: Je ne vois personne / Je ne comprends rien. 복합과거에서도 주어 자리는 그대로: Personne n'a appelé."),
]

CULTURE = [
("프랑스 통신 시장과 'la box'",
 "프랑스 가정의 인터넷은 대부분 인터넷·TV·유선전화를 묶은 '트리플 플레이' 상품으로, 공유기를 흔히 la box라고 부른다. 주요 통신사는 네 곳 정도로 과점 구조이며, 2010년대 초 저가 사업자가 이동통신 시장에 진입하면서 요금이 크게 내려가는 가격 경쟁이 벌어졌다. 이후 통신사들은 가격만으로 차별화하기 어려워져 고객 서비스와 해지율 관리가 핵심 과제가 되었다. 대도시에서는 광섬유(la fibre) 보급이 빠르게 확대되었다."),
("해지와 약정에 관한 소비자 보호",
 "프랑스 통신 계약은 무약정(sans engagement) 상품이 흔하고, 약정이 있더라도 법으로 고객을 보호한다. 2008년 샤텔 법(loi Chatel)은 해지 요청을 원칙적으로 10일 안에 처리하도록 하고, 24개월 약정이라도 12개월이 지나면 남은 기간 요금의 4분의 1만 내고 해지할 수 있게 했다. 또 고객센터 대기 시간에 요금을 물리는 관행도 제한했다. 2023년부터는 온라인으로 가입한 계약을 몇 번의 클릭만으로 해지할 수 있어야 한다는 규정(résiliation en trois clics)이 시행되었다."),
("콜센터와 지방 고용",
 "프랑스의 대형 콜센터는 임대료와 인건비가 파리보다 낮은 지방 도시, 특히 오드프랑스(Hauts-de-France) 지역에 많이 자리 잡아 중요한 일자리가 되었다. 동시에 많은 기업이 같은 프랑스어권인 모로코·튀니지 등 북아프리카로 상담 업무를 해외 이전(délocalisation)하기도 했다. 콜센터는 이직률이 높은 직종으로 알려져 있으며, 통화 시간 같은 생산성 지표 위주의 관리가 상담원의 스트레스와 고객 불만을 함께 키운다는 비판이 꾸준히 제기되어 왔다."),
]
