# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, B, S = "Inès", "Mathieu", "Hélène", "Baptiste", "Sofia"
C, P, Y = "Carré", "Perrin", "Yannick"

META = {
    "part": 1, "ep": 14,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "Retours gratuits",
    "title_ko": "무료 반품",
    "place": "Vasseur & Associés · 2구 상티에 거리 모데오 본사 · 마른라발레 반품 물류창고 · 사무실 건물 옥상 테라스 / 약 3주간",
    "chars": "이네스, 마티외, 엘렌, 소피아, 바티스트, 쥘리앵 카레(모데오 창업자·대표), 델핀 페랭(재무이사), 야니크 르 고프(반품 물류센터장)",
    "work": "온라인 패션몰 모데오 — 반품률 42%, 무료 반품 비용 연 4,500만 유로, 순손실 800만 유로, 여러 사이즈를 주문하고 돌려보내는 '사이즈 브래킷'",
    "life": "사내 연애 규정을 몰래 읽다 소피아에게 들킴, 이네스의 매니저 승진과 바티스트의 분노, 옥상 테라스에서 미뤄 둔 결론",
    "focus": "수동태 입문(être + 과거분사, par), 규정·의무 어휘, 비율·분수 표현, 비용 절감 논의, plus... plus 구문",
    "levelmix": "B1 40% · B2 50% · C1 10%",
    "next": "제15화 L'offre du client — 그린워싱 스캔들에 휩싸인 에너지 기업, 그리고 두 사람의 운명을 바꿀 뜻밖의 제안.",
}

D = [
# ---------- 1. Ouverture : l'article 7 ----------
(None, "Lundi, 7 h 50. Vasseur & Associés. Le bureau est encore vide. Sur l'écran d'Inès : « Guide du collaborateur — Article 7 : relations personnelles au travail ».",
       "월요일 오전 7시 50분. 바쇠르 & 어소시에이츠. 사무실은 아직 비어 있다. 이네스의 화면에는 '직원 안내서 — 제7조: 직장 내 개인적 관계'."),
(I, "« Tout collaborateur engagé dans une relation personnelle avec un autre collaborateur est tenu d'en informer les ressources humaines... »",
    "'다른 직원과 개인적 관계를 맺고 있는 모든 직원은 이를 인사부에 알려야 한다...'"),
(S, "Coucou ! Tu es déjà là ? J'ai apporté des pains au chocolat pour toute l'équipe... Attends. Qu'est-ce que tu lis ?",
    "안녕! 벌써 와 있어? 팀 전체 먹으라고 팽오쇼콜라 사 왔는데... 잠깐. 뭐 읽고 있어?"),
(I, "Rien. Un document RH. C'est pour une mission.", "아무것도 아냐. 인사 자료야. 미션 때문에."),
(None, "Sofia se penche par-dessus son épaule.", "소피아가 이네스의 어깨 너머로 몸을 숙인다."),
(S, "« Article 7 : relations personnelles au travail »... Ah, je le savais ! Je le savais depuis notre premier apéro !",
    "'제7조: 직장 내 개인적 관계'... 아, 내 그럴 줄 알았어! 우리 첫 아페로 때부터 알았다니까!"),
(I, "Tu ne sais rien du tout. Et baisse la voix, s'il te plaît.", "넌 아무것도 몰라. 그리고 목소리 좀 낮춰 줘."),
(S, "Il n'y a personne, il est huit heures moins dix. Alors ? Depuis la semaine dernière, vous ne vous regardez plus dans les yeux, tous les deux.",
    "아무도 없어, 8시 10분 전인데. 그래서? 지난주부터 너희 둘, 서로 눈도 안 마주치잖아."),
(I, "Il ne s'est rien passé. Presque rien. C'est justement ça, le problème.", "아무 일도 없었어. 거의 아무 일도. 바로 그게 문제야."),
(S, "« Presque rien »... Ne botte pas en touche. Et pourquoi tu lis le règlement, alors ?", "'거의 아무 일도'라... 말 돌리지 마. 그럼 규정은 왜 읽는 건데?"),
(I, "Parce que je suis comme ça. Avant de faire une bêtise, je lis les conditions générales. Écoute : « Aucune relation n'est autorisée entre deux personnes ayant un lien hiérarchique au sein d'une même équipe. »",
    "내가 원래 그래. 바보 같은 짓을 하기 전에 약관부터 읽거든. 들어 봐. '같은 팀 안에서 상하 관계에 있는 두 사람 사이의 어떠한 관계도 허용되지 않는다.'"),
(S, "Mais vous n'avez pas de lien hiérarchique, Mathieu et toi. Vous êtes binômes.", "그런데 너랑 마티외는 상하 관계가 아니잖아. 파트너지."),
(I, "Pour l'instant. Si je suis nommée manager, Mathieu sera dans mon équipe.", "지금은. 내가 매니저로 임명되면 마티외는 내 팀원이 돼."),
(S, "Ah... Oui, ça complique les choses. Mais tu n'es pas encore nommée.", "아... 그래, 그럼 일이 복잡해지네. 그래도 아직 임명된 건 아니잖아."),
(None, "La porte de l'ascenseur s'ouvre. Mathieu entre, deux gobelets à la main. Inès ferme son ordinateur d'un coup sec.",
       "엘리베이터 문이 열린다. 마티외가 컵 두 개를 들고 들어온다. 이네스가 노트북을 탁 닫는다."),
(MA, "Bonjour ! Sofia, tu es déjà là ? Désolé, je n'ai pris que deux cafés.", "안녕! 소피아, 벌써 왔어? 미안, 커피를 두 잔만 샀어."),
(I, "Si c'est pour rembourser ta dette, ça ne compte pas. Un gobelet en carton, ce n'est pas un vrai café.", "빚 갚으려는 거라면 안 쳐 줘. 종이컵은 진짜 커피가 아니야."),
(MA, "Je sais, je sais. Le café que je te dois, ce sera un vrai, en terrasse. Celui-ci, c'est juste pour dire bonjour. Au fait, Hélène nous attend à neuf heures. Nouveau client.",
     "알아, 알아. 내가 빚진 커피는 테라스에서 마시는 진짜 커피일 거야. 이건 그냥 인사로 사 온 거고. 그건 그렇고, 엘렌이 9시에 기다린대. 새 고객이야."),

# ---------- 2. Briefing et client ----------
(None, "9 h. Salle « Monceau ». Hélène, Inès, Mathieu et Sofia. Baptiste passe la tête par la porte, un dossier sous le bras.",
       "오전 9시. '몽소' 회의실. 엘렌, 이네스, 마티외, 소피아. 바티스트가 서류철을 옆구리에 끼고 문으로 고개를 들이민다."),
(B, "Bonne chance pour ta dernière épreuve, Inès. Moi, j'ai fini la mienne vendredi. Mon client a signé pour deux ans.",
    "마지막 시험 잘 치러, 이네스. 난 금요일에 끝냈어. 내 고객이 2년 계약에 서명했거든."),
(I, "Bravo, Baptiste. Ferme la porte en sortant, s'il te plaît.", "축하해, 바티스트. 나가면서 문 좀 닫아 줘."),
(H, "Bon. Vous le savez : c'est la dernière mission avant ma décision pour le poste de manager. Inès, je vais t'observer, mais ne change rien. Le client : Modéo.",
    "자. 다들 알다시피 매니저 자리를 결정하기 전 마지막 미션이야. 이네스, 널 지켜보겠지만 아무것도 바꾸지 마. 고객은 모데오야."),
(MA, "Modéo, le site de vêtements en ligne ? On voit leurs publicités dans tout le métro.", "모데오면 그 온라인 옷 쇼핑몰이요? 지하철 곳곳에 광고가 있던데요."),
(H, "Celui-là. Trois cents millions d'euros de chiffre d'affaires, vingt pour cent de croissance par an... et des pertes. Leur promesse depuis le début : livraison et retours gratuits.",
    "바로 거기. 매출 3억 유로, 연 20% 성장... 그리고 적자. 처음부터 내건 약속이 무료 배송, 무료 반품이야."),
(I, "Laisse-moi deviner : les retours leur coûtent une fortune.", "맞혀 볼게요. 반품 비용이 어마어마하죠."),
(H, "Quarante-deux pour cent des articles vendus reviennent à l'entrepôt. Le fondateur, Julien Carré, vous reçoit à onze heures, rue du Sentier. Sofia, tu prépares les données.",
    "판매된 상품의 42%가 창고로 돌아와. 창업자 쥘리앵 카레가 11시에 상티에 거리에서 만나 줄 거야. 소피아, 데이터 준비해."),
(None, "11 h. Siège de Modéo, dans le 2e arrondissement, l'ancien quartier du textile. Des portants de vêtements partout, des écrans aux murs.",
       "오전 11시. 옛 섬유 거리인 2구의 모데오 본사. 사방에 옷걸이 행거, 벽에는 화면들."),
(C, "Bonjour, entrez ! Julien Carré. Pardon pour le désordre, on prépare une séance photo. Je vous présente Delphine Perrin, notre directrice financière.",
    "안녕하세요, 들어오세요! 쥘리앵 카레입니다. 어수선해서 죄송해요, 촬영 준비 중이라서요. 우리 재무이사 델핀 페랭을 소개합니다."),
(P, "Bonjour. Je vous préviens : je regarde nos comptes tous les mois, et nous sommes dans le rouge depuis deux ans.", "안녕하세요. 미리 말씀드리죠. 저는 매달 회계를 들여다보는데, 2년째 적자예요."),
(I, "Bonjour madame Perrin, bonjour monsieur Carré. Pouvez-vous nous présenter la situation en quelques chiffres ?", "안녕하세요, 페랭 이사님, 카레 대표님. 상황을 몇 가지 숫자로 설명해 주시겠어요?"),
(P, "L'an dernier, nos clients ont commandé pour cinq cent vingt millions d'euros. Nous en avons remboursé deux cent vingt. Il reste trois cents millions de chiffre d'affaires, et un résultat net de moins huit millions.",
    "작년에 고객들이 5억 2천만 유로어치를 주문했어요. 그중 2억 2천만 유로를 환불했고요. 남은 매출이 3억 유로, 순이익은 마이너스 800만 유로예요."),
(MA, "Deux cent vingt millions remboursés... Combien de colis vous sont retournés chaque année ?", "2억 2천만 유로를 환불했다니... 매년 몇 개의 소포가 반품되나요?"),
(P, "Deux millions et demi. Et chaque retour nous coûte en moyenne douze euros : six euros cinquante de transport et cinq euros cinquante de traitement à l'entrepôt.",
    "250만 개요. 그리고 반품 하나에 평균 12유로가 들어요. 운송비 6유로 50센트, 창고 처리비 5유로 50센트요."),
(I, "Douze euros fois deux millions et demi, ça fait trente millions par an, rien que pour la logistique inverse.", "12유로 곱하기 250만이면, 역물류에만 연간 3천만 유로네요."),
(C, "Je sais, je sais. Mais les retours gratuits, c'est l'ADN de Modéo. Quand j'ai lancé le site, il y a dix ans, personne n'osait acheter un pantalon sans l'essayer. Les retours gratuits ont tout changé.",
    "알아요, 알아요. 하지만 무료 반품은 모데오의 DNA예요. 10년 전 사이트를 열었을 때, 입어 보지 않고 바지를 사려는 사람은 아무도 없었어요. 무료 반품이 모든 걸 바꿨죠."),
(MA, "Vous aviez raison à l'époque. La question, c'est de savoir si c'est toujours vrai aujourd'hui.", "그때는 옳으셨어요. 문제는 그게 오늘날에도 여전히 맞느냐는 거죠."),
(C, "Bien sûr que c'est vrai ! Tous nos concurrents proposent les retours gratuits. Si on fait marche arrière, nos clients partent chez eux dès demain.",
    "당연히 맞죠! 경쟁사들도 전부 무료 반품을 해요. 우리가 물러서면 고객들은 당장 내일 그쪽으로 가 버릴 거예요."),
(I, "Peut-être. Mais aujourd'hui, plus vous grandissez, plus vous perdez d'argent.", "그럴 수도 있죠. 하지만 지금은 성장할수록 돈을 더 잃고 계세요."),
(C, "Ça, c'est le discours de Delphine.", "그건 델핀이 늘 하는 소리고요."),
(P, "C'est le discours du compte de résultat, Julien.", "손익계산서가 하는 소리예요, 쥘리앵."),
(MA, "Savez-vous pourquoi vos clients renvoient leurs articles ?", "고객들이 왜 상품을 돌려보내는지 아세요?"),
(C, "Ils cochent une case quand ils font le retour : taille, couleur, qualité... Mais honnêtement, personne n'a jamais vraiment analysé ces données.",
    "반품할 때 칸에 체크해요. 사이즈, 색상, 품질... 그런데 솔직히 그 데이터를 제대로 분석한 사람은 아무도 없어요."),
(I, "Et que deviennent les articles retournés ?", "반품된 상품은 어떻게 되나요?"),
(P, "La plupart sont remis en vente. Mais environ un sur cinq ne peut pas être revendu : abîmé, taché, sans étiquette. On n'a plus le droit de les détruire depuis la loi anti-gaspillage, alors ils s'entassent.",
    "대부분은 다시 판매해요. 그런데 다섯 개 중 하나 정도는 다시 팔 수 없어요. 망가졌거나, 얼룩이 있거나, 라벨이 없거나. 낭비방지법 이후로는 폐기할 수도 없으니 계속 쌓여만 가죠."),
(MA, "Un sur cinq... Ça représente combien ?", "다섯 개 중 하나라... 금액으로는 얼마나 되나요?"),
(P, "Environ quinze millions d'euros par an de marchandise invendable. Avec la logistique, les retours nous coûtent donc quarante-cinq millions.",
    "팔 수 없는 상품이 연간 1,500만 유로 정도예요. 물류비까지 합치면 반품에 4,500만 유로가 드는 셈이죠."),
(I, "Quarante-cinq millions de coûts, pour un résultat de moins huit. Au moins, le problème est clair.", "비용 4,500만 유로에 순이익 마이너스 800만. 적어도 문제는 분명하네요."),
(C, "Je ne veux pas qu'on punisse nos clients. Ce sont des étudiants, des jeunes parents, des gens qui n'ont pas le temps d'aller en boutique. Ils nous font confiance.",
    "우리 고객들을 벌주는 건 원치 않아요. 학생들, 젊은 부모들, 매장에 갈 시간이 없는 사람들이에요. 우릴 믿어 주는 사람들이라고요."),
(MA, "Personne ne parle de punir. Nous voulons d'abord comprendre. Pouvons-nous visiter votre entrepôt ?", "아무도 벌주자는 얘긴 안 했습니다. 먼저 이해하고 싶을 뿐이에요. 창고를 방문해도 될까요?"),
(C, "Marne-la-Vallée, quand vous voulez. Demandez Yannick, c'est lui qui gère les retours. Il vous dira ce qu'il pense de mes retours gratuits.",
    "마른라발레요, 언제든지요. 야니크를 찾으세요. 반품 담당이에요. 그 친구가 제 무료 반품에 대해 어떻게 생각하는지 말해 줄 거예요."),

# ---------- 3. Analyse ----------
(None, "Mercredi, 19 h. Salle « Monceau ». Sofia projette ses graphiques. Mathieu fait tourner son vieux marqueur vert entre ses doigts.",
       "수요일 저녁 7시. '몽소' 회의실. 소피아가 그래프를 띄운다. 마티외는 낡은 초록 마커를 손가락 사이로 돌리고 있다."),
(S, "Alors. J'ai analysé un an de retours, deux millions et demi de colis. Premier motif de retour : la taille. Cinquante-huit pour cent.",
    "자. 1년 치 반품, 소포 250만 개를 분석했어. 반품 사유 1위는 사이즈. 58%."),
(I, "Cinquante-huit ! Et ensuite ?", "58%라니! 그다음은?"),
(S, "« Ne correspond pas à la photo » : dix-sept pour cent. « Changement d'avis » : douze. Les articles défectueux, seulement cinq pour cent. Le reste, c'est divers.",
    "'사진과 다름' 17%. '마음이 바뀜' 12%. 불량품은 겨우 5%. 나머지는 기타야."),
(MA, "Donc les produits sont bons. C'est l'information qui est mauvaise : les clients ne savent pas quelle taille choisir.", "그러니까 제품은 괜찮은 거네. 문제는 정보야. 고객들이 어떤 사이즈를 골라야 할지 모르는 거지."),
(S, "Attendez, ce n'est pas fini. Le plus intéressant : cinq pour cent des clients font trente pour cent des retours.", "잠깐, 아직 안 끝났어. 제일 흥미로운 건, 고객의 5%가 반품의 30%를 차지한다는 거야."),
(I, "Cinq pour cent ? Montre-moi ça... Il y a des clients qui renvoient presque tout ce qu'ils commandent ?", "5%? 보여 줘... 주문한 걸 거의 다 돌려보내는 고객들이 있다고?"),
(S, "Certains renvoient quatre-vingt-dix pour cent de leurs commandes. Une cliente a commandé trois cents articles l'an dernier. Elle en a gardé onze.",
    "어떤 고객은 주문의 90%를 돌려보내. 한 고객은 작년에 300개를 주문했어. 그중 11개만 가졌고."),
(MA, "Onze sur trois cents... Elle utilise Modéo comme une cabine d'essayage.", "300개 중 11개라... 모데오를 피팅룸처럼 쓰는 거네."),
(I, "Une cabine d'essayage gratuite, payée par Modéo. Bon, la solution est évidente : on supprime les retours gratuits. Trois euros quatre-vingt-dix par retour, pour tout le monde.",
    "모데오가 비용을 대는 무료 피팅룸이지. 좋아, 해결책은 뻔해. 무료 반품을 없애는 거야. 반품 한 건에 3유로 90센트, 모두에게."),
(MA, "Pour tout le monde ? Même pour les quatre-vingt-quinze pour cent qui se comportent normalement ?", "모두에게? 정상적으로 이용하는 95%한테도?"),
(I, "Tu as entendu Perrin : moins huit millions. On n'a pas le temps de ménager la chèvre et le chou.", "페랭 말 들었잖아. 마이너스 800만이야. 양쪽 비위 다 맞출 시간 없어."),
(MA, "Et tu as entendu Carré : si les retours deviennent payants, ses clients partent. Le manque à gagner pourrait être plus grand que les économies.",
     "너도 카레 말 들었잖아. 반품이 유료가 되면 고객들이 떠난다고. 놓치는 매출이 절감액보다 클 수도 있어."),
(I, "Tu n'en sais rien. C'est une intuition, pas un chiffre.", "그건 모르는 거지. 그건 감이지, 숫자가 아니야."),
(MA, "Alors cherchons le chiffre. Sofia, qu'est-ce qui se passe quand une enseigne rend les retours payants ?", "그럼 숫자를 찾아보자. 소피아, 업체가 반품을 유료로 바꾸면 어떻게 돼?"),
(S, "D'après les études du secteur, elle perd en général une partie de ses clients occasionnels. Les clients fidèles, eux, restent presque tous.",
    "업계 연구에 따르면 보통 가끔 사는 고객 일부를 잃어. 충성 고객들은 거의 다 남고."),
(I, "Tu vois ? Les fidèles restent.", "봤지? 충성 고객은 남는다잖아."),
(MA, "Les fidèles, oui. Mais les nouveaux clients ne viennent plus. Pour une entreprise qui grandit de vingt pour cent par an, c'est grave. Pourquoi faire payer tout le monde pour cinq pour cent ?",
     "충성 고객은 그렇지. 하지만 새 고객이 안 와. 연 20%씩 크는 회사한테 그건 심각해. 5% 때문에 왜 모두한테 돈을 받아?"),
(I, "Parce que c'est simple, et que le simple, ça marche. Toi, tu veux le beurre et l'argent du beurre : des économies, sans perdre un seul client.",
    "간단하니까. 그리고 간단한 게 통하니까. 넌 두 마리 토끼를 다 잡고 싶은 거야. 고객은 하나도 안 잃고 비용은 줄이고."),
(MA, "Non. Je veux faire payer ceux qui coûtent cher, pas les autres. Ce n'est pas pareil.", "아니. 비용을 많이 만드는 사람한테만 돈을 받자는 거야. 그건 다른 얘기야."),
(S, "Bon... Je vais chercher des sandwichs. Essayez de ne pas vous entretuer pendant mon absence.", "음... 샌드위치 사 올게. 나 없는 동안 서로 죽이지는 마."),
(None, "Sofia sort. Un silence. Inès pose son stylo.", "소피아가 나간다. 침묵. 이네스가 펜을 내려놓는다."),
(I, "Pardon. Je suis un peu tendue en ce moment.", "미안. 요즘 좀 예민해."),
(MA, "À cause du poste de manager ?", "매니저 자리 때문에?"),
(I, "Entre autres.", "그것도 있고."),
(MA, "Et à cause de l'autre soir, sur les quais ?", "그리고 그날 밤, 강변에서의 일 때문에?"),
(I, "Mathieu. Pas ici. Pas maintenant.", "마티외. 여기선 안 돼. 지금은 안 돼."),
(MA, "D'accord. Alors parlons de la taille. Pourquoi les clients se trompent-ils autant ?", "알았어. 그럼 사이즈 얘기를 하자. 고객들은 왜 그렇게 많이 틀릴까?"),
(I, "Modéo vend quarante marques, et chacune a son propre guide des tailles. Un M chez l'une, c'est un S chez l'autre.", "모데오는 브랜드 40개를 팔아. 그리고 브랜드마다 사이즈표가 달라. 어떤 데선 M인 게 다른 데선 S야."),
(MA, "Donc le client ne fait pas confiance au guide... et il commande deux ou trois tailles pour être sûr ?", "그러니까 고객은 사이즈표를 못 믿고... 확실히 하려고 두세 사이즈를 주문한다?"),
(I, "C'est une hypothèse. On ne la trouvera pas dans les tableaux : il faut ouvrir les colis. Marne-la-Vallée, vendredi ?", "그건 가설이야. 표에서는 못 찾아. 소포를 열어 봐야 해. 마른라발레, 금요일?"),
(MA, "Vendredi. Et cette fois, c'est moi qui choisis les places dans le RER.", "금요일. 그리고 이번엔 RER 자리는 내가 고를 거야."),

# ---------- 4. Terrain : l'entrepôt ----------
(None, "Vendredi, 8 h. Entrepôt Modéo, à Marne-la-Vallée. Un hangar immense. Sur les tapis roulants, des centaines de colis ouverts.",
       "금요일 오전 8시. 마른라발레의 모데오 창고. 거대한 창고. 컨베이어 벨트 위에 열린 소포 수백 개."),
(Y, "Bienvenue au royaume des retours ! Yannick Le Goff, responsable du site. Mettez ces gilets jaunes, c'est obligatoire.", "반품 왕국에 오신 걸 환영합니다! 이 센터 책임자 야니크 르 고프입니다. 이 노란 조끼 입으세요, 의무예요."),
(MA, "Bonjour Yannick. Merci de nous recevoir. Combien de colis recevez-vous par jour ?", "안녕하세요, 야니크 씨. 맞아 주셔서 감사합니다. 하루에 소포를 몇 개나 받으세요?"),
(Y, "Entre huit et dix mille. Après Noël et pendant les soldes, le double. Chaque colis est ouvert, chaque article est contrôlé, plié, remis sous plastique et réétiqueté.",
    "8천에서 1만 개요. 크리스마스 이후와 세일 기간엔 두 배고요. 소포 하나하나 열고, 상품 하나하나 검수하고, 개고, 다시 비닐에 넣고, 라벨을 새로 붙여요."),
(I, "Combien de temps faut-il pour qu'un article retourné soit remis en vente ?", "반품된 상품이 다시 판매되기까지 얼마나 걸리나요?"),
(Y, "Neuf jours en moyenne. Et en mode, neuf jours, c'est long. Une robe d'été, quand elle revient en septembre, ça ne se vend plus au prix normal.",
    "평균 9일이요. 그런데 패션에서 9일은 길어요. 여름 원피스가 9월에 돌아오면 이제 정가로는 안 팔려요."),
(MA, "Et les articles qui ne peuvent pas être revendus ?", "다시 팔 수 없는 상품들은요?"),
(Y, "Venez voir. Ici, du maquillage sur un col. Là, une robe qui sent le parfum et la cigarette : elle a été portée pour une soirée, puis renvoyée. Et celle-ci... l'étiquette a été recousue.",
    "와서 보세요. 여기, 깃에 화장품이 묻었죠. 저기, 향수랑 담배 냄새가 나는 원피스. 파티 한 번 입고 돌려보낸 거예요. 그리고 이건... 라벨을 다시 꿰매 붙였네요."),
(I, "Recousue ? Des gens portent les vêtements une soirée et les renvoient ?", "다시 꿰맸다고요? 사람들이 옷을 하룻밤 입고 돌려보낸다고요?"),
(Y, "Une minorité. Mais assez pour remplir ce bac tous les jours.", "소수죠. 그래도 매일 이 통을 채울 만큼은 돼요."),
(MA, "Et la taille ? D'après les données, cinquante-huit pour cent des retours sont liés à la taille.", "사이즈는요? 데이터에 따르면 반품의 58%가 사이즈 때문이던데요."),
(Y, "Ah, la taille... Regardez ce colis. Même robe, même couleur. En 36, en 38 et en 40. La cliente a gardé le 38 et nous a renvoyé les deux autres.",
    "아, 사이즈라... 이 소포 보세요. 같은 원피스, 같은 색. 36, 38, 40. 고객은 38을 갖고 나머지 둘을 돌려보냈어요."),
(I, "C'est un cas isolé ?", "드문 경우인가요?"),
(Y, "Isolé ? Entre nous, on appelle ça « la cabine d'essayage à domicile ». Je dirais qu'une commande sur trois contient le même article en plusieurs tailles.",
    "드물다고요? 우리끼리는 '집 안의 피팅룸'이라고 불러요. 주문 세 건 중 하나는 같은 상품을 여러 사이즈로 담고 있을걸요."),
(MA, "Ils savent d'avance qu'ils vont renvoyer, alors. Mais pourquoi plusieurs tailles, à votre avis ?", "그럼 미리 반품할 걸 알고 있는 거네요. 그런데 왜 여러 사이즈를 주문할까요?"),
(Y, "Parce que nos tailles ne veulent rien dire ! Cette marque-là taille petit, celle-ci taille grand. Et sur les photos, le mannequin mesure un mètre quatre-vingts et porte du 34. Personne ne ressemble à ça.",
    "우리 사이즈가 아무 의미가 없으니까요! 저 브랜드는 작게 나오고, 이 브랜드는 크게 나와요. 게다가 사진 속 모델은 키가 180에 34 사이즈를 입어요. 그렇게 생긴 사람은 아무도 없죠."),
(I, "Et personne au siège ne vous a jamais demandé votre avis ?", "본사에서 아무도 의견을 물어본 적 없나요?"),
(Y, "Je leur envoie un rapport chaque mois. Je ne suis pas sûr qu'il soit lu. Bon, je vous laisse, un camion arrive.", "매달 보고서를 보내요. 읽히는지는 잘 모르겠지만요. 자, 전 가 볼게요. 트럭이 들어와서요."),
(None, "Yannick s'éloigne. Le téléphone d'Inès vibre : un message de Sofia.", "야니크가 멀어진다. 이네스의 휴대폰이 진동한다. 소피아의 메시지다."),
(I, "Sofia a vérifié : trente et un pour cent des commandes contiennent le même article en au moins deux tailles. Une sur trois, comme disait Yannick.",
    "소피아가 확인했대. 주문의 31%에 같은 상품이 최소 두 사이즈로 들어 있대. 야니크 말대로 세 건 중 하나야."),
(MA, "Donc ces clients-là ne sont pas des tricheurs. Ils ont peur de se tromper de taille.", "그러니까 그 고객들은 사기꾼이 아니야. 사이즈를 잘못 고를까 봐 겁이 나는 거지."),
(I, "D'accord. Je l'admets : j'ai fait fausse route. Si on fait payer les retours à tout le monde, on punit des gens qui ont juste besoin d'un bon guide des tailles.",
    "알았어. 인정할게. 내가 방향을 잘못 잡았어. 모두에게 반품비를 받으면, 좋은 사이즈표가 필요할 뿐인 사람들을 벌주는 셈이야."),
(MA, "Et les cinq pour cent ? La cliente aux trois cents articles ?", "그럼 5%는? 300개 주문한 그 고객은?"),
(I, "Elle, elle paiera. Pour elle, ce n'est pas un problème de taille, c'est une habitude.", "그 사람은 내야지. 그 사람한텐 사이즈 문제가 아니라 습관이니까."),
(MA, "Tu vois qu'on finit toujours par être d'accord.", "거봐, 우린 결국 늘 의견이 같아지잖아."),
(I, "Tu veux dire qu'on finit toujours par être d'accord avec moi.", "결국 늘 내 의견에 맞춰진다는 뜻이겠지."),
(MA, "Si ça te fait plaisir. Allez, le RER nous attend. Et je garde la place côté fenêtre.", "그게 좋다면 그렇다 치자. 자, RER이 기다려. 그리고 창가 자리는 내 거야."),

# ---------- 5. Recommandations ----------
(None, "Deux semaines plus tard. Siège de Modéo. Julien Carré et Delphine Perrin. Au fond de la salle, Hélène Vasseur prend des notes.",
       "2주 뒤. 모데오 본사. 쥘리앵 카레와 델핀 페랭. 방 뒤편에서 엘렌 바쇠르가 메모를 하고 있다."),
(I, "Monsieur Carré, madame Perrin, nous allons commencer par une bonne nouvelle : vos clients ne sont pas le problème. Le problème, c'est l'information qui leur est donnée.",
    "카레 대표님, 페랭 이사님, 좋은 소식부터 말씀드리겠습니다. 고객이 문제가 아닙니다. 문제는 고객에게 주어지는 정보입니다."),
(C, "Je vous l'avais dit ! Mes clients ne sont pas des tricheurs.", "제가 말했잖아요! 우리 고객들은 사기꾼이 아니라고요."),
(MA, "La grande majorité, non. Cinquante-huit pour cent des retours sont causés par la taille, et une commande sur trois contient le même article en plusieurs tailles. Ce comportement est encouragé par votre site lui-même : « Commandez, essayez, renvoyez. »",
     "대다수는 아니죠. 반품의 58%는 사이즈 때문이고, 주문 세 건 중 하나는 같은 상품을 여러 사이즈로 담고 있습니다. 이런 행동은 바로 귀사의 사이트가 부추기고 있습니다. '주문하고, 입어 보고, 돌려보내세요.'"),
(C, "C'est notre slogan...", "그건 우리 슬로건인데..."),
(I, "Et il a été très efficace pour faire grandir Modéo. Mais aujourd'hui, il vous coûte quarante-cinq millions d'euros par an. Nous avons quatre recommandations.",
    "그리고 모데오를 키우는 데 아주 효과적이었죠. 하지만 지금은 연간 4,500만 유로의 비용을 치르게 합니다. 저희 권고는 네 가지입니다."),
(MA, "Premièrement, un outil de recommandation de taille. Le client indique sa taille, son poids et une marque qu'il connaît bien. L'outil lui propose la bonne taille, marque par marque.",
     "첫째, 사이즈 추천 도구입니다. 고객이 키와 몸무게, 잘 아는 브랜드 하나를 입력하면 도구가 브랜드별로 맞는 사이즈를 제안합니다."),
(P, "Combien de retours peut-on éviter avec ça ?", "그걸로 반품을 얼마나 줄일 수 있죠?"),
(MA, "Avec une hypothèse prudente, un quart des retours liés à la taille. Votre taux de retour passerait de quarante-deux à trente-six pour cent en dix-huit mois.",
     "보수적으로 가정해도 사이즈 관련 반품의 4분의 1입니다. 반품률이 18개월 안에 42%에서 36%로 떨어질 겁니다."),
(C, "Six points de moins... Ce n'est pas énorme.", "6%포인트 감소라... 대단하진 않네요."),
(P, "Julien, six points, c'est plus de trois cent cinquante mille colis en moins par an.", "쥘리앵, 6%포인트면 1년에 소포가 35만 개 넘게 줄어드는 거예요."),
(I, "Deuxièmement, les photos et les descriptions. Chaque article sera photographié sur deux mannequins de morphologies différentes, et ses mesures réelles seront indiquées en centimètres. Les avis des clients sur la taille seront affichés sur chaque fiche produit.",
    "둘째, 사진과 상품 설명입니다. 모든 상품은 체형이 다른 모델 두 명에게 입혀 촬영하고, 실제 치수를 센티미터로 표기합니다. 사이즈에 관한 고객 후기도 상품 페이지마다 게시합니다."),
(MA, "Et votre équipe photo passera une journée par mois à l'entrepôt, avec Yannick. C'est là-bas que les erreurs sont vues en premier.", "그리고 촬영팀은 한 달에 하루 창고에서 야니크 씨와 함께 보냅니다. 문제가 가장 먼저 눈에 띄는 곳이 거기니까요."),
(C, "Yannick... Il m'envoie un rapport tous les mois. Je l'avoue, je ne le lis pas toujours.", "야니크라... 매달 보고서를 보내 주죠. 솔직히 늘 읽지는 않아요."),
(I, "Nous l'avons lu. Il est excellent. Vous devriez l'inviter à votre comité de direction.", "저희는 읽었습니다. 훌륭합니다. 경영위원회에 초대하셔야 할 겁니다."),
(MA, "Troisièmement, et c'est le point le plus délicat : les frais de retour.", "셋째, 가장 민감한 부분입니다. 반품비입니다."),
(I, "Les retours resteront gratuits pour quatre-vingt-quinze pour cent de vos clients. Mais pour ceux qui renvoient plus de soixante-dix pour cent de ce qu'ils commandent sur douze mois, trois euros quatre-vingt-dix seront facturés par retour.",
    "고객의 95%에게는 반품이 계속 무료입니다. 하지만 12개월 동안 주문한 것의 70% 넘게 돌려보내는 고객에게는 반품 한 건당 3유로 90센트를 청구합니다."),
(C, "Faire payer nos clients ? Jamais. Ce serait la fin de notre promesse !", "고객에게 돈을 받는다고요? 절대 안 돼요. 그건 우리 약속의 끝이에요!"),
(MA, "Ces clients représentent cinq pour cent de votre clientèle et trente pour cent de vos retours. L'une d'elles a commandé trois cents articles l'an dernier. Elle en a gardé onze.",
     "그 고객들은 전체 고객의 5%지만 반품의 30%를 차지합니다. 그중 한 분은 작년에 300개를 주문해서 11개만 가졌습니다."),
(C, "Onze ? ... Ce n'est pas possible.", "11개요? ...말도 안 돼요."),
(P, "C'est possible, Julien. J'ai vérifié moi-même : rien qu'en frais de retour, elle nous a coûté plus de mille euros.", "말이 돼요, 쥘리앵. 제가 직접 확인했어요. 반품비만으로 그 고객 한 명에게 천 유로 넘게 들었어요."),
(I, "Ces clients seront prévenus à l'avance, par un message personnel. Ils pourront choisir : changer leurs habitudes, ou payer. Dans les deux cas, Modéo y gagne.",
    "이 고객들에게는 개인 메시지로 미리 알립니다. 습관을 바꾸든지, 비용을 내든지 선택할 수 있습니다. 어느 쪽이든 모데오에는 이득입니다."),
(C, "Et s'ils partent chez les concurrents ?", "그런데 그 사람들이 경쟁사로 가 버리면요?"),
(MA, "Alors ce seront vos concurrents qui paieront leurs retours.", "그럼 경쟁사들이 그 사람들의 반품비를 내게 되겠죠."),
(None, "Au fond de la salle, Hélène cache un sourire derrière son carnet.", "방 뒤편에서 엘렌이 수첩 뒤로 미소를 감춘다."),
(P, "Et la quatrième recommandation ? Nos articles invendables ?", "네 번째 권고는요? 팔 수 없는 상품들은요?"),
(I, "Les quinze millions d'euros de marchandise qui s'entassent. La moitié peut être nettoyée, réparée et revendue à prix réduit dans un espace « Seconde Vie » sur votre site. Le reste sera donné à des associations ou recyclé, comme le prévoit la loi.",
    "쌓여 있는 1,500만 유로어치 상품입니다. 절반은 세탁·수선해서 사이트 안의 '세컨드 라이프' 코너에서 할인 판매할 수 있습니다. 나머지는 법이 정한 대로 자선단체에 기부하거나 재활용합니다."),
(C, "Une boutique de seconde main... Ça, nos clients vont adorer.", "중고 매장이라... 그건 고객들이 정말 좋아하겠네요."),
(P, "Au total, ça donne quoi ?", "다 합치면 얼마나 되죠?"),
(I, "Environ dix-huit millions d'euros d'économies par an. Vous pouvez passer d'une perte de huit millions à un bénéfice de dix millions en deux ans.",
    "연간 약 1,800만 유로 절감입니다. 2년 안에 800만 유로 적자에서 1,000만 유로 흑자로 돌아설 수 있습니다."),
(MA, "Et vos clients fidèles garderont leurs retours gratuits. Votre promesse ne disparaît pas, monsieur Carré : elle devient tenable.", "그리고 충성 고객들은 무료 반품을 계속 누립니다. 대표님의 약속은 사라지지 않습니다. 지킬 수 있는 약속이 되는 겁니다."),
(C, "... Bon. On teste les frais de retour pendant trois mois, sur ces cinq pour cent. Si on perd trop de clients, on arrête. Delphine, tu suis ça avec eux ?",
    "...좋아요. 그 5%를 대상으로 석 달 동안 반품비를 시험해 봅시다. 고객을 너무 많이 잃으면 중단하고요. 델핀, 이분들과 같이 챙겨 줄래요?"),

# ---------- 6. Le soir : la promotion et le toit ----------
(None, "Le vendredi suivant, 18 h. Bureau d'Hélène. Inès entre et ferme la porte derrière elle.", "다음 주 금요일 저녁 6시. 엘렌의 사무실. 이네스가 들어와 뒤로 문을 닫는다."),
(H, "Assieds-toi. Carré m'a appelée ce matin : l'outil de taille est lancé, et Yannick a été invité au comité de direction. Bref, j'ai pris ma décision. Félicitations, Inès. Tu es nommée manager à partir du premier du mois.",
    "앉아. 오늘 아침 카레가 전화했어. 사이즈 도구가 출시됐고, 야니크는 경영위원회에 초대받았대. 아무튼, 결정했어. 축하해, 이네스. 다음 달 1일부로 매니저로 임명이야."),
(I, "Je... Merci, Hélène. Vraiment. Je ne sais pas quoi dire.", "저... 감사해요, 엘렌. 정말로요. 무슨 말을 해야 할지 모르겠어요."),
(H, "Pour une fois. Ton équipe : Mathieu et Sofia. Un conseil : apprends à déléguer, tu ne peux plus tout faire toute seule. Et Inès... j'ai des yeux. Le règlement intérieur, tu le connais, je suppose ?",
    "웬일로. 네 팀은 마티외와 소피아야. 조언 하나. 위임하는 법을 배워. 이제 혼자 다 할 순 없어. 그리고 이네스... 나도 눈이 있어. 사내 규정은 알고 있겠지?"),
(I, "... Par cœur. Article 7.", "...외우고 있어요. 제7조."),
(None, "Dans le couloir, Baptiste attend, les bras croisés. Mathieu sort de la salle « Monceau » au même moment.", "복도에서 바티스트가 팔짱을 끼고 기다리고 있다. 마침 마티외가 '몽소' 회의실에서 나온다."),
(B, "Félicitations, madame la manager. Six ans de travail, et c'est la protégée d'Hélène qui gagne. Quelle surprise.", "축하해, 매니저님. 6년을 일했는데 엘렌이 아끼는 사람이 이기네. 이거 참 놀랍군."),
(MA, "Elle a gagné parce qu'elle était la meilleure, Baptiste. Tu le sais très bien.", "이네스가 이긴 건 제일 잘했기 때문이야, 바티스트. 너도 잘 알잖아."),
(B, "Garde tes leçons pour toi. De toute façon, je ne vais pas rester ici à applaudir. On m'a déjà fait des propositions, et pas dans le conseil : chez ceux qui achètent les entreprises. On se reverra peut-être... mais pas du même côté de la table.",
    "훈계는 넣어 둬. 어차피 여기 남아서 박수나 칠 생각은 없어. 벌써 제안도 받았고. 컨설팅 쪽이 아니라, 회사를 사들이는 쪽에서. 언젠가 다시 보겠지... 하지만 같은 편에 앉아 있진 않을 거야."),
(None, "20 h. La petite terrasse sur le toit de l'immeuble. Paris s'allume, la tour Eiffel au loin.", "저녁 8시. 건물 옥상의 작은 테라스. 파리에 불이 켜지고, 멀리 에펠탑이 보인다."),
(MA, "Il va vraiment claquer la porte, tu crois ?", "저 사람 정말 회사를 박차고 나갈까?"),
(I, "Baptiste menace de partir depuis trois ans. Mais cette fois, il avait l'air sérieux. Il m'a regardée comme si je lui avais volé quelque chose.",
    "바티스트는 3년째 나간다고 협박만 했어. 그런데 이번엔 진지해 보였어. 내가 자기 걸 훔치기라도 한 것처럼 날 보더라."),
(MA, "Tu n'as rien volé. Félicitations, chef.", "넌 아무것도 안 훔쳤어. 축하해, 대장."),
(I, "Ne m'appelle pas chef. ... Tu es dans mon équipe maintenant, tu sais. Toi et Sofia.", "대장이라고 부르지 마. ...이제 너 내 팀이야, 알지? 너랑 소피아."),
(MA, "Je sais. J'ai lu l'article 7, moi aussi. Deux fois.", "알아. 나도 제7조 읽었어. 두 번."),
(I, "Alors tu sais. Si on commence quelque chose, l'un de nous devra changer d'équipe.", "그럼 알겠네. 우리가 뭔가를 시작하면, 둘 중 하나는 팀을 옮겨야 해."),
(MA, "Et ce ne sera pas toi : tu viens d'être nommée.", "그리고 그게 너일 순 없지. 이제 막 임명됐으니까."),
(I, "Et moi, je ne veux pas perdre mon meilleur binôme. Ni... le reste. Je ne sais pas, Mathieu. On en reparle plus tard, d'accord ?",
    "그리고 난 최고의 파트너를 잃고 싶지 않아. 그리고... 나머지도. 모르겠어, 마티외. 나중에 다시 얘기하자, 응?"),
(MA, "Tu dis toujours ça. ... Bon. Revenons à ce qu'on sait faire. Quel est le vrai problème ? Et qui décide ?", "넌 늘 그렇게 말하지. ...좋아. 우리가 잘하는 걸로 돌아가자. 진짜 문제는 뭐지? 그리고 누가 결정하지?"),
(I, "Le vrai problème, c'est un article de règlement. Et c'est nous qui déciderons. Mais pas ce soir.", "진짜 문제는 규정 한 조항이야. 그리고 결정은 우리가 해. 하지만 오늘 밤은 아니야."),
(MA, "Pas ce soir. Alors, dernière question : que fait-on lundi ?", "오늘 밤은 아니고. 그럼 마지막 질문. 월요일엔 뭘 하지?"),
(I, "Lundi, on travaille. Hélène a reçu un appel d'un fournisseur d'énergie. De l'électricité « cent pour cent verte », paraît-il. Elle a un mauvais pressentiment.",
    "월요일엔 일하지. 엘렌이 어느 에너지 공급사한테서 전화를 받았대. '100% 친환경' 전기라나 봐. 엘렌은 예감이 안 좋대."),
(MA, "Alors lundi, je t'apporte un café. Pas celui que je te dois : celui-là, je le garde pour une grande occasion.", "그럼 월요일에 커피 한 잔 갖다줄게. 내가 빚진 커피는 아니고. 그건 특별한 날을 위해 아껴 둘 거야."),
]

VOCAB = [
("B2", "être tenu(e) de + 부정사", "~할 의무가 있다", "규정·계약서의 전형적 표현. Tout collaborateur est tenu d'en informer les RH. = doit."),
("B2", "un lien hiérarchique", "상하(지휘) 관계", "hiérarchie(위계)에서. avoir un lien hiérarchique avec qn. 사내 연애 규정의 핵심어."),
("B1", "Je le savais !", "내 그럴 줄 알았어!", "le = 앞의 내용 전체. 짐작이 맞았을 때 반쯤 신나서 하는 말. J'en étais sûr(e) !"),
("B2", "botter en touche", "(곤란한 질문을) 피하다, 말을 돌리다", "럭비에서 공을 경기장 밖(touche)으로 차내는 데서. Ne botte pas en touche !"),
("B1", "un colis", "소포, 택배 상자", "envoyer / recevoir / renvoyer un colis. 반품 물류의 기본 단위."),
("B1", "rembourser / un remboursement", "환불하다 / 환불", "빚을 갚다는 뜻도 있음: rembourser une dette(커피 빚!)."),
("B2", "être dans le rouge", "적자이다", "↔ être dans le vert / revenir à l'équilibre. 장부의 빨간 숫자에서."),
("B2", "la logistique inverse", "역물류(반품 물류)", "소비자 → 판매자로 되돌아오는 흐름. 영어 reverse logistics."),
("B2", "faire marche arrière", "물러서다, 철회하다", "원래 '후진하다'. 결정·정책을 되돌릴 때. Le gouvernement a fait marche arrière."),
("B2", "s'entasser", "(물건이) 쌓이다", "tas(더미)에서. Les articles invendables s'entassent dans l'entrepôt."),
("B2", "invendable", "팔 수 없는", "vendre + -able. invendu(팔리지 않은)와 구분: 안 팔린 것 vs 팔 수 없는 것."),
("C1", "ménager la chèvre et le chou", "양쪽 비위를 다 맞추다", "염소와 양배추를 함께 지키는 난제에서. 갈등 조정 상황의 관용구."),
("C1", "vouloir le beurre et l'argent du beurre", "두 마리 토끼를 다 잡으려 하다", "버터도 갖고 버터 판 돈도 갖겠다는 것. 2화 '버터 값'의 메아리."),
("B2", "un manque à gagner", "놓친 수익, 기회 손실", "실제 손실이 아니라 '벌 수 있었는데 못 번 돈'. 비용 절감 논의의 필수 어휘."),
("B1", "une cabine d'essayage", "탈의실, 피팅룸", "essayer(입어 보다)에서. la cabine d'essayage à domicile = 집을 피팅룸처럼 쓰는 것."),
("B1", "un guide des tailles", "사이즈표", "온라인 쇼핑 필수 페이지. Quelle taille faites-vous ? = 사이즈가 어떻게 되세요?"),
("B2", "tailler petit / tailler grand", "(옷이) 작게 / 크게 나오다", "Cette marque taille petit : prenez une taille au-dessus. 쇼핑 후기의 단골 표현."),
("B2", "faire fausse route", "방향을 잘못 잡다, 헛짚다", "직역 '잘못된 길로 가다'. J'ai fait fausse route. 잘못을 인정하는 깔끔한 표현."),
("B1", "le taux de retour", "반품률", "taux = 비율. taux de chômage, taux d'intérêt. passer de 42 à 36 %."),
("B2", "facturer qc (à qn)", "(누구에게) ~을 청구하다", "facture(청구서)에서. Des frais seront facturés par retour."),
("B2", "la seconde main", "중고", "un vêtement de seconde main. 프랑스 패션 업계에서 빠르게 크는 시장. d'occasion과 같은 뜻."),
("B2", "tenable", "지킬 수 있는, 유지 가능한", "tenir(지키다) + -able. une promesse tenable ↔ intenable(견딜 수 없는)."),
("B1", "être nommé(e) + 직위", "~로 임명되다", "Tu es nommée manager. nomination(임명). 승진은 une promotion."),
("B1", "déléguer", "(업무를) 맡기다, 위임하다", "Apprends à déléguer. 완벽주의자 이네스의 숙제. délégation(위임)."),
("B2", "claquer la porte", "(화가 나서) 박차고 나가다, 그만두다", "직역 '문을 쾅 닫다'. 회사·조직을 떠나는 것에 비유적으로 씀."),
]

GRAM = [
("B1", "수동태 현재: être + 과거분사",
 "« Chaque colis est ouvert, chaque article est contrôlé, plié... » « Cinquante-huit pour cent des retours sont causés par la taille. » 수동태는 être를 시제에 맞춰 변화시키고 과거분사를 주어의 성·수에 일치시킨다(retours → causés, la taille → 여성이면 -e). 물류·공정 설명처럼 '누가'보다 '무엇이 어떻게 처리되는지'가 중요할 때 자연스럽다."),
("B2", "수동태의 시제: 복합과거·미래",
 "« Elle a été portée pour une soirée, puis renvoyée. » « L'étiquette a été recousue. » « Chaque article sera photographié... ses mesures réelles seront indiquées en centimètres. » 복합과거는 avoir été + p.p., 미래는 serai/seras/sera + p.p. 권고안 발표에서는 미래 수동태가 '앞으로 이렇게 바뀔 것'을 객관적으로 제시하는 효과를 낸다."),
("B2", "행위자 par와 생략, 그리고 on 능동문",
 "« Ce comportement est encouragé par votre site lui-même. »에서 par는 행위자를 밝힌다. 행위자가 뻔하거나 중요하지 않으면 생략한다: « C'est là-bas que les erreurs sont vues en premier. » 회화에서는 on 능동문이 더 흔하다: « On n'a plus le droit de les détruire » (= ils ne peuvent plus être détruits). 수동태는 접속법과도 결합한다: « Je ne suis pas sûr qu'il soit lu. »"),
("B2", "대명동사의 수동적 의미: se vendre",
 "« Une robe d'été, quand elle revient en septembre, ça ne se vend plus au prix normal. » 주어가 사물일 때 대명동사가 수동의 뜻을 갖는다(= n'est plus vendue). 일반적 사실을 말할 때 쓴다: Ça se porte avec une ceinture. Ce mot ne s'écrit pas comme ça."),
("B2", "규정 문체: 의무와 금지",
 "« Tout collaborateur ... est tenu d'en informer les ressources humaines. » « Aucune relation n'est autorisée entre deux personnes ayant un lien hiérarchique... » être tenu de(의무), aucun(e)... ne + être autorisé(e)(금지), 현재분사 ayant(= qui ont)은 규정·법률 문체의 특징이다. 회화에서는 devoir의 미래형으로 바꿔 말한다: « l'un de nous devra changer d'équipe. » / « comme le prévoit la loi »."),
("B1", "비율과 분수 표현",
 "« un sur cinq ne peut pas être revendu » « une commande sur trois » « cinq pour cent des clients font trente pour cent des retours » « Six points de moins ». A sur B = B개 중 A개. 퍼센트끼리의 차이는 points(%포인트)로 말한다: de quarante-deux à trente-six pour cent = 6 points. un quart(4분의 1), la moitié(절반)도 함께 익히자."),
("B2", "plus... plus: 비례 비교",
 "« Plus vous grandissez, plus vous perdez d'argent. » 'Plus A, plus B'는 '~할수록 더 ~하다'. 관사·que 없이 두 절을 나란히 놓는다. 반대 방향은 moins: Plus on attend, moins on a de choix. 두 번째 절에서 도치하지 않는다는 점에 주의."),
("B2", "venir de + 부정사 (최근 과거)와 수동",
 "« Tu viens d'être nommée. » venir de + 부정사는 '막 ~했다'. 수동 부정사(être + p.p.)와 결합하면 '막 ~되었다'. 비교: « Tu es nommée manager »(현재 수동: 임명 사실의 선언) / « Yannick a été invité au comité de direction »(완료된 사건)."),
]

CULTURE = [
("온라인 구매 철회권(droit de rétractation)",
 "프랑스 소비법(Code de la consommation)은 온라인 등 원격 구매에 대해 소비자가 상품을 받은 날부터 14일 안에 이유 없이 계약을 철회할 수 있도록 보장한다. 판매자는 철회 통지를 받은 뒤 14일 안에 환불해야 한다. 다만 반품 배송비는 판매자가 부담하기로 했거나 미리 고지하지 않은 경우가 아니면 원칙적으로 소비자 몫이다. 즉 '무료 반품'은 법적 의무가 아니라 기업의 상업적 선택이며, 그래서 최근 일부 온라인 패션 업체들이 반품비를 다시 받기 시작했다."),
("프랑스의 사내 연애와 사생활 보호",
 "프랑스에서 사생활은 민법 제9조로 보호되며, 노동법(L1121-1조)은 직원의 권리를 제한하려면 업무의 성격상 정당하고 목적에 비례해야 한다고 정한다. 그래서 사내 연애 자체를 전면 금지하는 규정은 인정되기 어렵다. 대신 많은 기업이 이해충돌 방지를 위해 관계를 알리게 하거나, 상하 관계에 있는 두 사람의 보고 라인을 바꾸는 방식으로 대응한다. 극 중 '제7조'도 이런 관행을 바탕으로 한 설정이다."),
("컨설팅 회사의 직급과 '매니저'",
 "전략 컨설팅 회사의 직급은 보통 애널리스트(analyste) → 컨설턴트 → 시니어 컨설턴트 → 매니저 → 시니어 매니저(또는 디렉터) → 파트너(associé) 순이다. 매니저는 처음으로 프로젝트 전체와 팀원을 책임지고 고객과의 일상적 관계를 맡는 자리라, 실무자에서 관리자로 넘어가는 큰 관문으로 여겨진다. 정해진 기간 안에 승진하지 못하면 회사를 떠나는 'up or out' 문화도 업계에 널리 퍼져 있다."),
]
