# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, S = "Inès", "Mathieu", "Hélène", "Sofia"
AU, DU, K, V = "Aubry", "Duval", "Karine", "Vidal"

META = {
    "part": 1, "ep": 15,
    "part_label": "제1부 · 컨설턴트 Les consultants",
    "title_fr": "L'offre du client",
    "title_ko": "고객의 제안",
    "place": "14구 레몽로스랑 거리 원룸 · Vasseur & Associés · 오스테를리츠역 근처 엘리오르 에네르지 본사 · 오를레앙 고객센터 · 몽소 공원 / 6월, 약 4주간",
    "chars": "이네스, 마티외, 엘렌, 소피아, 프레데리크 오브리(아르칸 캐피털 파트너·엘리오르 이사회 의장), 클레르 뒤발(엘리오르 대표 직무대행), 카린 르무안(고객 상담원), 파트리크 비달(CSE 위원)",
    "work": "재생에너지 공급사 엘리오르 에네르지 — '100% 친환경' 광고의 그린워싱 스캔들, CEO·CFO 사임, 30일 안에 위기 대응·신뢰 회복 계획",
    "life": "새벽 6시의 전화, 매니저와 팀원이 된 두 사람의 어색함, 몽소 공원의 첫 키스, 아홉 달 만에 갚은 커피 한 잔",
    "focus": "위기 커뮤니케이션 어휘, 제안·협상·결정 표현, 접속법(avant que, pour que, à condition que, bien que), 조건법(전언·가정), ce qui... c'est 강조, 비율·배수 표현, 1부 마무리",
    "levelmix": "B1 40% · B2 50% · C1 10%",
    "next": "제2부 제16화 Prise de fonctions — 생테티엔 Verdier Industries 첫 출근, 회계 감사에서 드러난 숨은 부채, 그리고 파리와 생테티엔을 오가는 두 집 살림의 시작.",
}

D = [
# ---------- 1. Ouverture : le réveil ----------
(None, "Un mardi de juin, 6 h 10. Rue Raymond-Losserand. Le téléphone de Mathieu vibre sur la table de nuit. Il décroche, les yeux encore fermés.",
       "6월의 어느 화요일, 오전 6시 10분. 레몽로스랑 거리. 마티외의 휴대폰이 침대 옆 탁자 위에서 진동한다. 그는 아직 눈을 감은 채 전화를 받는다."),
(MA, "Allô... ? Inès ? Il est six heures... Quelqu'un est mort ?", "여보세요...? 이네스? 지금 6시야... 누가 죽었어?"),
(I, "Pas encore. Mais une entreprise est en train de mourir. Ouvre Le Courrier de Paris, tout de suite.", "아직은. 그런데 회사 하나가 죽어 가고 있어. 《쿠리에 드 파리》 열어 봐, 지금 당장."),
(MA, "Le Courrier ? Notre ancien client ? Attends, je te mets sur haut-parleur... Voilà : « Hélior Énergie : le mensonge du 100 % vert ».",
     "《쿠리에》? 우리 예전 고객? 잠깐, 스피커폰으로 돌릴게... 여기 있다. '엘리오르 에네르지: 100% 친환경의 거짓말'."),
(I, "Lis la suite. C'est leur nouvelle cellule d'investigation. Six mois d'enquête. Tu te souviens ? C'était notre recommandation.",
    "계속 읽어 봐. 거기 새 탐사보도팀이 쓴 거야. 여섯 달 취재. 기억나? 그거 우리 권고안이었잖아."),
(MA, "« Selon nos informations, plus d'un tiers de l'électricité vendue par Hélior provient de centrales à gaz. » Aïe. Et leurs affiches partout dans le métro : « 100 % vert, 100 % d'ici ».",
     "'본지 취재에 따르면 엘리오르가 판매한 전력의 3분의 1 이상이 가스 발전소에서 나온다.' 아이고. 그런데 지하철 곳곳에 붙은 그 회사 광고는 '100% 친환경, 100% 국산'이잖아."),
(I, "Exactement. Et ce n'est pas tout : le PDG et le directeur financier ont démissionné cette nuit. Communiqué à deux heures du matin.",
    "바로 그거야. 그게 다가 아니야. 대표이사랑 재무이사가 간밤에 사임했어. 새벽 2시에 보도자료가 나왔어."),
(MA, "Un communiqué à deux heures du matin, ce n'est jamais bon signe. Mais pourquoi tu m'appelles, moi, à six heures ?",
     "새벽 2시 보도자료는 절대 좋은 신호가 아니지. 그런데 왜 나한테 6시에 전화한 거야?"),
(I, "Parce que Hélène vient de m'écrire. Depuis ce matin, Hélior est notre client. Réunion à huit heures.", "엘렌이 방금 문자를 보냈거든. 오늘 아침부터 엘리오르가 우리 고객이야. 8시에 회의."),
(MA, "À huit heures ? Je n'ai même pas couru. Et je n'ai pas de café.", "8시에? 아직 달리기도 안 했는데. 커피도 없고."),
(I, "Moi non plus. D'ailleurs, je te rappelle que tu m'en dois toujours un. Depuis le premier jour.", "나도 없어. 그러고 보니 다시 말하는데, 너 나한테 아직 커피 한 잔 빚졌어. 첫날부터."),
(MA, "Je sais, je sais. Tu me le rappelles une fois par semaine.", "알아, 알아. 일주일에 한 번씩 말하잖아."),
(I, "Une fois par jour, depuis que je suis ta manager. C'est un avantage de la fonction.", "내가 네 매니저가 된 뒤로는 하루에 한 번이지. 직책의 특권이야."),
(MA, "Bien, madame la manager. Je prends une douche et j'arrive. Et Inès... tu as dormi, toi ?", "알겠습니다, 매니저님. 샤워하고 갈게. 그리고 이네스... 너는 잠은 잤어?"),
(I, "Pas beaucoup. Je pensais à... d'autres choses. Allez, dépêche-toi, Strasbourg.", "별로. 다른... 생각을 하느라. 자, 서둘러, 스트라스부르."),
(None, "Elle raccroche. Mathieu reste assis sur son lit, le téléphone à la main.", "그녀가 전화를 끊는다. 마티외는 휴대폰을 손에 든 채 침대에 앉아 있다."),
(MA, "« D'autres choses »... Moi aussi, Inès. Moi aussi.", "'다른 생각'이라... 나도 그래, 이네스. 나도."),

# ---------- 2. Briefing et client ----------
(None, "8 h. Vasseur & Associés, salle « Monceau ». Sur l'écran, l'article du Courrier de Paris.", "오전 8시. 바쇠르 & 어소시에이츠, '몽소' 회의실. 화면에 《쿠리에 드 파리》 기사가 떠 있다."),
(H, "Merci d'être là si tôt. La situation en deux minutes. Hélior Énergie : fournisseur d'électricité renouvelable, deux mille huit cents salariés, un million deux cent mille clients particuliers.",
    "이렇게 일찍 와 줘서 고마워. 2분 만에 상황을 정리할게. 엘리오르 에네르지. 재생에너지 전력 공급사, 직원 2,800명, 개인 고객 120만 명."),
(S, "Et depuis ce matin, le mot « Hélior » est partout sur les réseaux sociaux. Avec « menteurs » et « greenwashing » juste à côté.",
    "그리고 오늘 아침부터 SNS가 '엘리오르'라는 단어로 도배됐어요. 바로 옆에 '거짓말쟁이'랑 '그린워싱'이 붙어서요."),
(H, "Le président du conseil d'administration m'a appelée à minuit. Il s'appelle Frédéric Aubry. Il est associé chez Arcane Capital, le principal actionnaire.",
    "이사회 의장이 자정에 전화했어. 이름은 프레데리크 오브리. 최대 주주인 아르칸 캐피털의 파트너야."),
(I, "Arcane Capital... C'est un fonds plutôt dur, non ? On dit qu'ils ne gardent jamais une entreprise plus de cinq ans.", "아르칸 캐피털이라... 꽤 냉정한 펀드잖아요? 어떤 회사도 5년 넘게 안 갖고 있는다던데요."),
(H, "On dit beaucoup de choses. Aubry est exigeant, mais il est intelligent. Il veut un plan de crise et de reconquête de la confiance dans trente jours.",
    "말은 많지. 오브리는 까다롭지만 똑똑해. 30일 안에 위기 대응과 신뢰 회복 계획을 원해."),
(MA, "Trente jours pour réparer une réputation ? C'est très court.", "평판을 고치는 데 30일이요? 아주 짧네요."),
(H, "C'est pour ça qu'il vous veut, vous. Inès, tu diriges la mission. Mathieu et Sofia, vous êtes dans ton équipe.", "그래서 너희를 원하는 거야. 이네스, 네가 미션을 이끌어. 마티외와 소피아는 네 팀이고."),
(S, "Parfait. L'équipe de rêve... au complet.", "완벽해요. 드림팀... 총출동이네요."),
(H, "Rendez-vous à dix heures au siège d'Hélior, près de la gare d'Austerlitz. Et pas un mot à la presse. Si un journaliste vous appelle, vous ne savez rien.",
    "10시에 오스테를리츠역 근처 엘리오르 본사에서 만나. 그리고 언론엔 한마디도 하지 마. 기자가 전화하면 아무것도 모르는 거야."),
(None, "10 h. Siège d'Hélior Énergie, dernier étage. En bas, des caméras de télévision. Frédéric Aubry, la cinquantaine, costume sombre, les attend debout près de la fenêtre.",
       "오전 10시. 엘리오르 에네르지 본사 꼭대기 층. 건물 아래엔 방송 카메라들. 50대에 짙은 정장 차림의 프레데리크 오브리가 창가에 선 채 그들을 기다리고 있다."),
(AU, "Madame Marchetti, monsieur Kessler, et madame... ?", "마르케티 씨, 케슬레르 씨, 그리고... ?"),
(S, "Benali. Sofia Benali, analyste.", "베날리입니다. 애널리스트 소피아 베날리예요."),
(AU, "Asseyez-vous. Je vais être direct, je n'ai pas le temps d'être poli. Depuis hier soir, nous recevons cinq fois plus d'appels que d'habitude, et neuf clients sur dix appellent pour résilier.",
     "앉으세요. 단도직입적으로 말하죠. 예의 차릴 시간이 없어서요. 어젯밤부터 평소보다 다섯 배 많은 전화가 오고, 열 명 중 아홉 명은 해지하려고 전화합니다."),
(I, "Monsieur Aubry, avant de parler de la crise, nous avons besoin des faits. Ce que dit l'article est-il vrai ?", "오브리 의장님, 위기 얘기를 하기 전에 사실부터 알아야 합니다. 기사 내용이 사실입니까?"),
(AU, "En partie. Juridiquement, Hélior ne ment pas. Chaque mégawattheure vendu est couvert par une garantie d'origine renouvelable. C'est parfaitement légal.",
     "일부는요. 법적으로 엘리오르는 거짓말을 하지 않았어요. 판매한 모든 메가와트시는 재생에너지 원산지 보증서로 뒷받침됩니다. 완전히 합법이에요."),
(MA, "Une garantie d'origine, c'est un certificat qui prouve qu'une certaine quantité d'électricité verte a été produite quelque part en Europe, c'est ça ?",
     "원산지 보증서라는 건 일정량의 녹색 전력이 유럽 어딘가에서 생산됐다는 걸 증명하는 인증서, 맞죠?"),
(AU, "Exactement. On peut l'acheter séparément de l'électricité elle-même. Tout le monde le fait.", "정확합니다. 전기 자체와 따로 살 수 있어요. 다들 그렇게 해요."),
(I, "Mais vos publicités disaient « 100 % d'ici » : une électricité produite dans vos parcs éoliens et solaires, en France. Ce n'est pas la même promesse.",
    "하지만 광고에선 '100% 국산', 즉 프랑스에 있는 귀사의 풍력·태양광 단지에서 생산한 전기라고 했죠. 그건 같은 약속이 아닙니다."),
(AU, "... Non. Ce n'est pas la même promesse. C'est bien pour ça que deux personnes ont démissionné cette nuit.", "...아니죠. 같은 약속이 아닙니다. 그래서 간밤에 두 사람이 사임한 거고요."),
(MA, "Qui a décidé de cette campagne ?", "그 광고 캠페인은 누가 결정했나요?"),
(AU, "L'ancien PDG et la direction marketing. Le conseil a validé le budget : six millions d'euros. Je ne vais pas vous dire que je n'étais pas au courant. J'ai regardé les chiffres de croissance, pas le texte des affiches.",
     "전 대표이사와 마케팅 본부요. 이사회는 예산 600만 유로를 승인했고요. 몰랐다고는 말하지 않겠습니다. 저는 성장 수치만 봤지, 광고 문구는 안 봤어요."),
(I, "Merci pour votre franchise. Quels sont les risques, aujourd'hui ?", "솔직하게 말씀해 주셔서 감사합니다. 지금 위험 요소는 무엇입니까?"),
(AU, "Trois. Les clients qui partent. L'enquête de la répression des fraudes, ouverte ce matin. Et les salariés : ils ont honte de leur entreprise. Ça, c'est le plus dangereux.",
     "세 가지요. 떠나는 고객들. 오늘 아침 시작된 소비자보호 당국의 조사. 그리고 직원들. 자기 회사를 부끄러워해요. 그게 가장 위험하죠."),
(MA, "Vous pensez que les salariés ne savaient rien ?", "직원들은 아무것도 몰랐다고 생각하세요?"),
(AU, "Je l'espère. Sinon, la question devient : pourquoi personne n'a rien dit ?", "그러길 바랍니다. 아니라면 질문은 이렇게 바뀌겠죠. 왜 아무도 아무 말을 안 했을까?"),
(S, "Il nous faudrait la production de vos parcs heure par heure, et tous les contrats d'achat d'électricité. Sur trois ans.", "귀사 발전 단지의 시간대별 생산량과 전력 구매 계약서 전부가 필요해요. 3년 치요."),
(AU, "Heure par heure ? Vous allez y passer des nuits.", "시간대별로요? 밤을 새우셔야 할 텐데요."),
(S, "J'adore les nuits avec des tableurs. Enfin... professionnellement.", "저 엑셀이랑 보내는 밤 정말 좋아해요. 아니... 업무적으로요."),
(I, "Nous voudrions aussi rencontrer le service client et les représentants du personnel. Sans la direction dans la pièce.", "고객 서비스팀과 직원 대표들도 만나고 싶습니다. 경영진이 없는 자리에서요."),
(AU, "Accordé. Notre centre de relation client est à Orléans. Je préviens Claire Duval, la directrice des opérations. Elle assure l'intérim de la direction générale.",
     "허락하죠. 고객센터는 오를레앙에 있어요. 운영 본부장 클레르 뒤발에게 말해 두겠습니다. 지금 대표 직무를 대행하고 있어요."),
(AU, "Une dernière chose. Je ne veux pas une belle présentation. Je veux un plan que je puisse défendre devant les clients, les salariés et l'État. Dans trente jours.",
     "마지막으로 하나. 멋진 발표는 필요 없습니다. 고객, 직원, 그리고 정부 앞에서 제가 변호할 수 있는 계획을 원해요. 30일 안에."),

# ---------- 3. Analyse ----------
(None, "Dix jours plus tard, jeudi, 22 h. Les bureaux sont vides, sauf la salle « Monceau ». Sofia a projeté un graphique couvert de courbes.",
       "열흘 뒤, 목요일 밤 10시. 사무실은 텅 비었고 '몽소' 회의실만 불이 켜져 있다. 소피아가 곡선으로 가득한 그래프를 띄워 놓았다."),
(S, "Bon. J'ai tout croisé : la production des parcs Hélior, heure par heure, et la consommation des clients. Regardez la courbe bleue.", "자. 다 교차 분석했어요. 엘리오르 발전 단지의 시간대별 생산량이랑 고객 소비량이요. 파란 곡선을 보세요."),
(MA, "La bleue, c'est la consommation ? Elle monte le soir et en hiver. Logique : chauffage, cuisine, télé.", "파란 게 소비량이야? 저녁이랑 겨울에 올라가네. 당연하지. 난방, 요리, TV."),
(S, "Et la verte, c'est ce que produisent leurs éoliennes et leurs panneaux solaires. À midi en été, ça va. Mais un soir de janvier sans vent...",
    "초록색은 풍력 발전기랑 태양광 패널이 생산하는 양이에요. 여름 한낮엔 괜찮아요. 그런데 바람 없는 1월 저녁엔..."),
(I, "... il n'y a presque plus rien. Alors, d'où vient l'électricité, à ce moment-là ?", "...거의 아무것도 없네. 그럼 그때 전기는 어디서 오는 거야?"),
(S, "D'un contrat avec une centrale à gaz dans le nord de la France. Sur l'année, les parcs Hélior couvrent quarante pour cent de la consommation, d'autres producteurs renouvelables vingt-cinq pour cent, et le gaz... trente-cinq pour cent.",
    "북프랑스의 가스 발전소와 맺은 계약에서요. 1년으로 보면 엘리오르 단지가 소비량의 40%, 다른 재생에너지 생산자가 25%, 그리고 가스가... 35%를 채워요."),
(MA, "Trente-cinq pour cent. Donc l'article a raison : plus d'un tiers.", "35%. 그러니까 기사가 맞네. 3분의 1 이상."),
(I, "Et pour couvrir ces trente-cinq pour cent, ils achètent des garanties d'origine. Je les ai trouvées dans les comptes : surtout de l'hydraulique norvégien, à moins d'un euro le mégawattheure.",
    "그리고 그 35%를 덮으려고 원산지 보증서를 사. 회계 장부에서 찾았어. 주로 노르웨이 수력 발전분이고, 메가와트시당 1유로도 안 돼."),
(MA, "Moins d'un euro ? Et l'offre « 100 % verte », ils la vendent combien de plus que la concurrence ?", "1유로도 안 된다고? 그럼 '100% 친환경' 상품은 경쟁사보다 얼마나 더 비싸게 팔아?"),
(I, "Huit pour cent plus cher. En gros, les clients ont payé un supplément pour une promesse qui ne coûtait presque rien à Hélior.", "8% 더 비싸. 간단히 말해서, 고객들은 엘리오르한테 거의 돈이 들지 않는 약속에 웃돈을 낸 거야."),
(S, "Aïe. Si les journalistes trouvent ça, c'est le deuxième article.", "아이고. 기자들이 이걸 찾아내면 두 번째 기사 나오는 거예요."),
(I, "Ils le trouveront. Donc il faut le dire avant eux. Ma position est simple : on publie tout. Les trente-cinq pour cent, les certificats, les prix. Transparence totale, tout de suite.",
    "찾아낼 거야. 그러니까 그들보다 먼저 말해야 해. 내 입장은 간단해. 전부 공개하는 거야. 35%, 보증서, 가격까지. 완전한 투명성, 지금 당장."),
(MA, "Tout de suite, sans plan ? Tu imagines la réaction ? Ils ont déjà perdu trente et un mille clients en dix jours.", "지금 당장, 계획도 없이? 반응이 어떨지 상상돼? 벌써 열흘 만에 고객 3만 1천 명을 잃었어."),
(I, "Et s'ils se taisent, ils en perdront trois fois plus quand le reste sortira. On ne reconstruit pas la confiance avec des demi-vérités.", "입 다물고 있으면 나머지가 터질 때 세 배는 더 잃을 거야. 반쪽짜리 진실로는 신뢰를 다시 쌓을 수 없어."),
(MA, "Je suis d'accord sur la vérité. Pas sur la méthode. Si tu publies « trente-cinq pour cent de gaz » sans dire ce qu'on va faire, ce sont les deux mille huit cents salariés qui vont payer pour la décision de deux personnes.",
     "진실엔 동의해. 방법엔 동의 안 해. 앞으로 뭘 할지 말하지 않고 '가스 35%'만 공개하면, 두 사람이 내린 결정의 대가를 직원 2,800명이 치르게 될 거야."),
(I, "Tu veux protéger tout le monde, comme toujours. Parfois, il faut accepter que ça fasse mal.", "넌 늘 그렇듯 모두를 지키고 싶어 하지. 때로는 아픈 걸 받아들여야 해."),
(MA, "Et toi, tu veux toujours avoir raison tout de suite. Parfois, il faut attendre que le patient soit prêt avant d'opérer.", "그리고 넌 늘 당장 옳고 싶어 하지. 때로는 환자가 준비될 때까지 기다렸다가 수술해야 해."),
(S, "Euh... Je vais chercher des sandwichs. Vous voulez quelque chose ? Non ? Parfait. Je prends mon temps.", "어... 저 샌드위치 사 올게요. 뭐 필요한 거 있어요? 없어요? 좋아요. 천천히 다녀올게요."),
(I, "Excuse-moi. Je suis fatiguée. Et depuis le toit... on ne se parle plus vraiment, toi et moi.", "미안해. 피곤해서 그래. 그리고 옥상에서 그 일 이후로... 우리 제대로 얘기를 안 하잖아."),
(MA, "On se parle tous les jours. De garanties d'origine.", "매일 얘기하잖아. 원산지 보증서에 대해서."),
(I, "C'est exactement ce que je veux dire.", "내 말이 바로 그거야."),
(MA, "Je sais. Mais tu es ma manager, maintenant. Et le règlement, je l'ai lu, moi aussi.", "알아. 그런데 이제 넌 내 매니저야. 그리고 규정은 나도 읽었어."),
(I, "... Bon. On verra ça après la mission. Pour l'instant, on a un client. Qu'est-ce que tu proposes ?", "...그래. 그건 미션 끝나고 생각하자. 지금은 고객이 있으니까. 넌 뭘 제안해?"),
(MA, "Pas une demi-vérité : toute la vérité, mais le même jour qu'un plan. On dit « voilà ce qui est faux » et, dans la même phrase, « voilà ce qu'on fait pour que ça devienne vrai ».",
     "반쪽짜리 진실이 아니라, 진실 전부. 다만 계획과 같은 날에. '이게 거짓이었습니다'라고 말하면서, 같은 문장 안에서 '이걸 사실로 만들기 위해 이렇게 하겠습니다'라고 말하는 거야."),
(I, "... D'accord. La vérité et le plan, ensemble. Ça, je peux le défendre.", "...좋아. 진실과 계획을 함께. 그거라면 나도 변호할 수 있어."),
(MA, "Alors posons les trois questions. Passe-moi mon marqueur vert.", "그럼 세 가지 질문을 던져 보자. 내 초록 마커 좀 줘."),
(MA, "Quel est le vrai problème ? Ce n'est pas le gaz. Bien que ce soit spectaculaire, toutes les entreprises d'énergie achètent du gaz en hiver. Le vrai problème, c'est la promesse.",
     "진짜 문제는 무엇인가? 가스가 아니야. 자극적이긴 해도, 모든 에너지 회사가 겨울엔 가스 전력을 사. 진짜 문제는 약속이야."),
(I, "Qui décide ? Normalement, le PDG. Mais il est parti. Donc, pour l'instant, Aubry et le conseil.", "누가 결정하는가? 원래는 대표이사지. 그런데 떠났어. 그러니까 지금은 오브리와 이사회."),
(MA, "Et une chose me gêne. Une entreprise de deux mille huit cents personnes, avec des centaines d'ingénieurs... Personne n'a vu que la promesse était fausse ?",
     "그리고 마음에 걸리는 게 하나 있어. 직원 2,800명에 엔지니어가 수백 명인 회사인데... 그 약속이 거짓이라는 걸 아무도 못 봤다고?"),
(I, "Ou alors tout le monde l'a vu, et personne n'a pu le dire.", "아니면 모두가 봤는데 아무도 말할 수 없었거나."),
(MA, "C'est ce qu'on va vérifier à Orléans.", "그걸 오를레앙에서 확인해 보자."),

# ---------- 4. Terrain : Orléans ----------
(None, "Le mardi suivant, 9 h. Centre de relation client d'Hélior, à Orléans. Un grand plateau, deux cents postes. Les téléphones sonnent sans arrêt.",
       "다음 주 화요일 오전 9시. 오를레앙의 엘리오르 고객센터. 넓은 사무 공간에 자리가 200개. 전화벨이 쉴 새 없이 울린다."),
(K, "Bonjour ! Karine Lemoine, conseillère depuis douze ans. On m'a dit de vous montrer « la réalité ». Mettez le casque... Tenez, en voilà un.",
    "안녕하세요! 12년째 상담원으로 일하는 카린 르무안이에요. 두 분께 '현실'을 보여 드리라고 하더군요. 헤드셋 쓰세요... 자, 전화 하나 왔네요."),
(K, "Hélior Énergie, Karine, bonjour... Oui, madame, je comprends... Non, la résiliation est gratuite... Oui, je suis désolée, vraiment. Au revoir, madame.",
    "엘리오르 에네르지 카린입니다, 안녕하세요... 네, 고객님, 이해합니다... 아니요, 해지는 무료예요... 네, 정말 죄송합니다. 안녕히 계세요, 고객님."),
(I, "Elle est partie ?", "해지했나요?"),
(K, "Comme la plupart. Elle m'a dit : « Je payais plus cher pour être honnête avec mes enfants. » Ça fait mal.", "대부분처럼요. 그분이 그러더라고요. '아이들한테 떳떳하려고 돈을 더 냈던 건데.' 마음이 아프죠."),
(MA, "Vous recevez combien d'appels comme ça, par jour ?", "이런 전화가 하루에 몇 통이나 와요?"),
(K, "Avant le scandale, six mille appels par jour pour tout le centre. Maintenant, trente mille. On fait des heures supplémentaires, et on se fait insulter.",
    "스캔들 전엔 센터 전체로 하루 6천 통이었어요. 지금은 3만 통이에요. 초과 근무를 하면서 욕까지 먹고 있죠."),
(I, "Et avant l'article, les clients posaient déjà des questions sur l'origine de l'électricité ?", "그럼 기사 나오기 전에도 고객들이 전기의 출처에 대해 물어봤나요?"),
(K, "Tout le temps ! « C'est vraiment vert, la nuit ? » « Vos éoliennes, elles tournent quand il n'y a pas de vent ? » Et nous, on avait un script.",
    "늘 물어봤죠! '밤에도 정말 친환경이에요?' '바람 없을 때도 풍력 발전기가 돌아가요?' 그리고 저희한텐 스크립트가 있었어요."),
(MA, "Un script ? Vous pouvez nous le montrer ?", "스크립트요? 보여 주실 수 있어요?"),
(K, "Le voilà. Ligne quatre : « Rassurez le client : notre électricité est garantie cent pour cent verte. » On devait lire ça. Même quand on savait que ce n'était pas tout à fait vrai.",
    "여기요. 네 번째 줄. '고객을 안심시키세요. 저희 전기는 100% 친환경으로 보증됩니다.' 이걸 읽어야 했어요. 완전히 사실이 아니라는 걸 알 때도요."),
(I, "Vous le saviez ?", "알고 계셨어요?"),
(K, "Ici, tout le monde se doutait de quelque chose. Mais allez plutôt voir Patrick, en salle de pause. Lui, il sait des choses.", "여기선 다들 뭔가 눈치채고 있었어요. 그런데 휴게실에 있는 파트리크한테 가 보세요. 그 사람은 뭘 좀 알아요."),
(V, "Patrick Vidal, élu au CSE. Ancien technicien de maintenance éolienne. Je vous préviens : en général, les consultants, ça annonce des licenciements.",
    "CSE 위원 파트리크 비달입니다. 풍력 발전기 정비 기술자 출신이고요. 미리 말해 두죠. 보통 컨설턴트가 오면 해고가 따라오더군요."),
(MA, "Pas cette fois, monsieur Vidal. Nous sommes là pour comprendre ce qui s'est passé. Est-ce que vous saviez ?", "이번엔 아닙니다, 비달 씨. 무슨 일이 있었는지 이해하러 왔습니다. 알고 계셨나요?"),
(V, "Si je savais ? J'ai passé vingt ans sur les éoliennes. Je sais combien elles produisent, et je sais combien on vend. Il y a trois ans, j'ai fait le calcul et j'ai écrit une note.",
    "알았냐고요? 20년을 풍력 발전기 위에서 보냈어요. 그게 얼마나 생산하는지, 우리가 얼마나 파는지 알죠. 3년 전에 계산해서 보고서를 썼어요."),
(I, "Une note ? À qui l'avez-vous envoyée ?", "보고서요? 누구에게 보내셨어요?"),
(V, "À mon chef, qui l'a envoyée à son chef, et ensuite... plus rien. Le silence. On m'a juste dit : « Ce n'est pas ton sujet, Patrick. »",
    "제 상사한테요. 상사가 자기 상사한테 보냈고, 그다음엔... 아무것도 없었어요. 침묵. 그냥 이런 말만 들었죠. '그건 네 소관이 아니야, 파트리크.'"),
(MA, "Il n'y avait pas de dispositif d'alerte interne ? La loi l'impose dans les entreprises de plus de cinquante salariés.", "내부 신고 제도는 없었나요? 직원 50명이 넘는 회사엔 법으로 의무인데요."),
(V, "Sur le papier, si. Une adresse mail. Elle arrivait directement chez le directeur juridique... qui travaillait pour le PDG. Vous auriez écrit, vous ?",
    "서류상으론 있었죠. 이메일 주소 하나. 그게 곧장 법무이사한테 갔어요... 대표이사 밑에서 일하는 사람한테요. 당신이라면 썼겠어요?"),
(I, "Non. Probablement pas.", "아니요. 아마 안 썼겠죠."),
(V, "Voilà. Ici, on aime cette boîte. Beaucoup d'entre nous sont venus pour l'écologie, pas pour le salaire. Et aujourd'hui, nos enfants nous demandent si on travaille pour des menteurs.",
    "그렇죠. 여기 사람들은 이 회사를 좋아해요. 많은 사람이 월급이 아니라 환경 때문에 왔어요. 그런데 지금은 아이들이 우리한테 거짓말쟁이들 밑에서 일하냐고 물어요."),
(MA, "Monsieur Vidal, si vous pouviez dire une seule chose au conseil d'administration, ce serait quoi ?", "비달 씨, 이사회에 딱 한 가지만 말할 수 있다면 뭘 말하시겠어요?"),
(V, "Qu'ils nous écoutent avant que ça explose, la prochaine fois. Pas après.", "다음번엔 터지기 전에 우리 말을 들으라고요. 터진 다음이 아니라."),
(None, "Dans le train du retour. Les champs de la Beauce défilent derrière la vitre.", "돌아오는 기차 안. 창밖으로 보스 평야의 밭들이 지나간다."),
(I, "Une note il y a trois ans. Une adresse mail chez le juriste du patron. Ce n'est pas un problème de communication, c'est un problème de gouvernance.",
    "3년 전의 보고서. 사장 측 법무 담당자한테 가는 이메일 주소. 이건 소통 문제가 아니라 지배구조 문제야."),
(MA, "Tout le monde savait, et personne ne pouvait le dire. Comme Youssef avec ses fournées... Mais cette fois, c'est nous qui allons le dire pour eux.",
     "모두가 알았는데 아무도 말할 수 없었어. 빵 굽는 횟수 얘기를 하던 유세프처럼... 하지만 이번엔 우리가 그들 대신 말할 거야."),

# ---------- 5. Recommandations ----------
(None, "Vingt-huit jours après l'article, un vendredi, 14 h. Siège d'Hélior, salle du conseil. Frédéric Aubry préside ; Claire Duval est à sa droite. Hélène est assise au fond de la salle.",
       "기사가 나온 지 28일째 되는 금요일 오후 2시. 엘리오르 본사 이사회실. 프레데리크 오브리가 의장석에 앉아 있고, 오른쪽에 클레르 뒤발이 있다. 엘렌은 방 뒤편에 앉아 있다."),
(AU, "Madame Marchetti, vous avez la parole. Vous avez vingt minutes. Et deux jours d'avance sur le délai, je le note.", "마르케티 씨, 말씀하세요. 20분 드리겠습니다. 그리고 기한보다 이틀 빠르군요. 기억해 두죠."),
(I, "Merci, monsieur le président. Nous commencerons par une phrase : Hélior n'a pas un problème d'électricité. Hélior a un problème de promesse.",
    "감사합니다, 의장님. 한 문장으로 시작하겠습니다. 엘리오르의 문제는 전기가 아닙니다. 엘리오르의 문제는 약속입니다."),
(MA, "Aujourd'hui, l'électricité de vos clients est verte à soixante-cinq pour cent : quarante pour cent viennent de vos propres parcs, vingt-cinq pour cent d'autres producteurs renouvelables. Les trente-cinq pour cent restants viennent du gaz, couverts par des garanties d'origine.",
     "현재 고객들에게 공급되는 전기는 65%가 녹색 전력입니다. 40%는 자체 발전 단지에서, 25%는 다른 재생에너지 생산자에게서 옵니다. 나머지 35%는 가스이고, 원산지 보증서로 덮여 있습니다."),
(I, "Ces garanties vous ont coûté moins d'un euro le mégawattheure. Vos clients, eux, ont payé huit pour cent de plus pour l'offre « 100 % verte ». C'est ce chiffre-là que la presse publiera ensuite.",
    "그 보증서는 메가와트시당 1유로도 들지 않았습니다. 반면 고객들은 '100% 친환경' 상품에 8%를 더 냈습니다. 언론이 다음에 공개할 숫자가 바로 이것입니다."),
(AU, "Vous êtes sûre qu'elle le trouvera ?", "언론이 그걸 찾아낼 거라고 확신합니까?"),
(I, "Nous l'avons trouvé en dix jours. Le Courrier de Paris a enquêté pendant six mois.", "저희는 열흘 만에 찾았습니다. 《쿠리에 드 파리》는 여섯 달 동안 취재했고요."),
(MA, "Notre première recommandation est donc de dire toute la vérité, avant qu'on la découvre à votre place. Un message public d'excuses, signé par la directrice générale par intérim, et une campagne de correction sur les mêmes supports que la publicité.",
     "그래서 첫 번째 권고는 남이 대신 밝혀내기 전에 진실을 전부 말하는 것입니다. 대표 직무대행이 서명한 공개 사과문, 그리고 광고와 같은 매체를 통한 정정 캠페인입니다."),
(DU, "Des excuses publiques ? Nos avocats disent qu'on reconnaîtrait ainsi notre responsabilité devant la répression des fraudes.", "공개 사과요? 변호사들 말로는 그러면 소비자보호 당국 앞에서 우리 책임을 인정하는 셈이 된답니다."),
(I, "Vous la reconnaîtrez de toute façon. Pour une pratique commerciale trompeuse sur l'environnement, l'amende peut atteindre quatre-vingts pour cent du coût de la campagne, soit jusqu'à quatre millions huit cent mille euros. C'est grave, mais ce n'est pas ce qui tuera Hélior. Ce qui tuera Hélior, c'est le silence.",
    "어차피 인정하시게 될 겁니다. 환경 관련 기만적 상업 관행에는 캠페인 비용의 최대 80%, 즉 최대 480만 유로까지 벌금이 나올 수 있습니다. 심각하지만, 그게 엘리오르를 죽이지는 않습니다. 엘리오르를 죽이는 건 침묵입니다."),
(MA, "Deuxièmement, un audit indépendant de toute la chaîne d'approvisionnement, publié dans quatre-vingt-dix jours. Et chaque mois, sur la facture, la part réelle de renouvelable : soixante-cinq pour cent aujourd'hui.",
     "둘째, 전체 공급망에 대한 독립 감사를 실시하고 90일 안에 공개합니다. 그리고 매달 요금 고지서에 실제 재생에너지 비율을 표시합니다. 현재는 65%입니다."),
(I, "Troisièmement, un plan pour que ce chiffre devienne vrai : quatre-vingts pour cent dans deux ans, cent pour cent dans trois ans. Trois nouveaux contrats d'achat avec des producteurs éoliens et solaires français, et un nouveau parc solaire. Investissement total : deux cent quarante millions d'euros.",
    "셋째, 그 숫자를 사실로 만들기 위한 계획입니다. 2년 뒤 80%, 3년 뒤 100%. 프랑스 풍력·태양광 생산자들과 새 전력 구매 계약 3건, 그리고 새 태양광 단지 1곳. 총 투자액은 2억 4천만 유로입니다."),
(AU, "Deux cent quarante millions. Et vous les trouvez où ?", "2억 4천만이라. 그 돈은 어디서 구합니까?"),
(I, "Cent soixante millions en obligations vertes : les investisseurs en veulent, à condition que l'audit soit irréprochable. Et quatre-vingts millions en suspendant le dividende pendant deux ans.",
    "1억 6천만은 녹색 채권으로요. 감사 결과가 흠잡을 데 없다면 투자자들이 원할 겁니다. 그리고 8천만은 2년간 배당을 중단해서 마련합니다."),
(AU, "Le dividende d'Arcane, vous voulez dire.", "아르칸의 배당 말이군요."),
(I, "Oui, monsieur Aubry. Le vôtre.", "네, 오브리 의장님. 의장님의 배당입니다."),
(None, "Silence dans la salle. Au fond, Hélène baisse les yeux pour cacher un sourire.", "회의실에 정적이 흐른다. 뒤편의 엘렌이 미소를 감추려고 눈을 내리깐다."),
(AU, "Vous savez que mes associés vont hurler ?", "제 동업자들이 펄펄 뛸 거라는 건 아시죠?"),
(I, "Je sais. Mais une entreprise qui a perdu la confiance de ses clients ne vaut plus grand-chose à la revente. Avec ce plan, Arcane touche moins pendant deux ans, et possède une entreprise qui vaut plus dans cinq.",
    "압니다. 하지만 고객의 신뢰를 잃은 회사는 되팔 때 별 가치가 없습니다. 이 계획대로라면 아르칸은 2년 동안 덜 받지만, 5년 뒤엔 더 가치 있는 회사를 갖게 됩니다."),
(AU, "... Admettons. Et les clients qui sont restés ?", "...그렇다고 칩시다. 남아 있는 고객들은요?"),
(MA, "Quatrièmement : un geste commercial. Trente euros déduits de la prochaine facture de chaque client. Environ trente-cinq millions d'euros.", "넷째, 고객 보상입니다. 모든 고객의 다음 요금에서 30유로를 차감합니다. 약 3,500만 유로입니다."),
(DU, "Trente-cinq millions ! C'est énorme.", "3,500만이요! 엄청난 금액이에요."),
(I, "C'est moins que ce que coûtent les départs. Au rythme actuel, vous perdrez cent cinquante mille clients d'ici la fin de l'année. Chacun vous rapporte environ cent vingt euros de marge par an. Faites le calcul sur trois ans.",
    "고객 이탈 비용보다는 적습니다. 지금 속도라면 연말까지 고객 15만 명을 잃습니다. 고객 한 명당 연간 마진이 약 120유로입니다. 3년으로 계산해 보십시오."),
(MA, "La dernière recommandation est la plus importante. À Orléans, un technicien a écrit une note sur ce problème il y a trois ans. Elle n'est jamais arrivée jusqu'à vous.",
     "마지막 권고가 가장 중요합니다. 오를레앙의 한 기술자가 3년 전에 이 문제에 대한 보고서를 썼습니다. 그 보고서는 끝내 의장님께 닿지 못했습니다."),
(AU, "Trois ans ? ... Qui ?", "3년이요? ...누굽니까?"),
(MA, "Ce n'est pas la question, monsieur le président. La question, c'est pourquoi elle n'est pas arrivée. Nous recommandons un vrai canal d'alerte, indépendant de la direction, qui rende compte directement au comité d'audit. Et chaque trimestre, le conseil rencontre des salariés du terrain, sans leurs managers.",
     "그게 문제가 아닙니다, 의장님. 문제는 왜 닿지 못했느냐입니다. 경영진과 독립적이고 감사위원회에 직접 보고하는 진짜 신고 채널을 권고합니다. 그리고 분기마다 이사회가 관리자 없이 현장 직원들을 만나야 합니다."),
(AU, "... Bien que ce plan me coûte cher, je le trouve juste. Je mets au vote.", "...이 계획이 제게 비싸게 먹히긴 하지만 정당하다고 봅니다. 표결에 부치겠습니다."),
(AU, "Adopté à l'unanimité. Madame Duval, le message d'excuses part lundi. Madame Vasseur, vos consultants ne font pas de cadeaux.", "만장일치로 가결됐습니다. 뒤발 대표대행, 사과문은 월요일에 나갑니다. 바쇠르 대표님, 당신네 컨설턴트들은 봐주는 게 없군요."),
(H, "C'est pour ça que vous les avez appelés, Frédéric.", "그래서 그 둘을 부르신 거잖아요, 프레데리크."),
(AU, "Madame Marchetti, monsieur Kessler, restez une minute. Arcane détient aussi Verdier Industries, à Saint-Étienne. Fondée en 1874, quatre mille deux cents salariés, de l'électroménager et des petits équipements. Le groupe perd de l'argent depuis trois ans.",
     "마르케티 씨, 케슬레르 씨, 잠깐 남아 주세요. 아르칸은 생테티엔의 베르디에 앵뒤스트리도 갖고 있습니다. 1874년 창업, 직원 4,200명, 가전과 소형 설비를 만드는 회사죠. 그 그룹이 3년째 적자입니다."),
(I, "Nous connaissons le nom. Mais nous sommes consultants, monsieur Aubry. Nous n'avons jamais dirigé une entreprise.", "이름은 압니다. 하지만 저희는 컨설턴트입니다, 오브리 의장님. 회사를 경영해 본 적이 없어요."),
(AU, "Vous venez de diriger celle-ci pendant un mois, avec mon chéquier. Il me faut un CEO et une CFO. Vous, monsieur Kessler, à la direction générale ; vous, madame Marchetti, aux finances. J'ai d'autres candidats, dont un de chez vous, d'ailleurs. Mais je vous veux, tous les deux. Hélène est au courant. Réponse lundi.",
     "방금 한 달 동안 제 수표책을 들고 이 회사를 경영하셨잖아요. CEO와 CFO가 필요합니다. 케슬레르 씨는 대표이사로, 마르케티 씨는 재무 책임자로. 다른 후보들도 있어요. 그러고 보니 그중 하나는 당신네 회사 사람이죠. 하지만 저는 두 분을 원합니다, 두 분 다. 엘렌도 알고 있어요. 월요일에 답을 주세요."),

# ---------- 6. Le soir : le parc Monceau ----------
(None, "Le soir même, 20 h 30. Parc Monceau. La lumière de juin s'attarde sur la pelouse et sur la colonnade du petit lac. Ils marchent depuis un moment sans parler.",
       "그날 저녁 8시 30분. 몽소 공원. 6월의 햇빛이 잔디밭과 작은 연못가의 열주 위에 머물러 있다. 두 사람은 한참 동안 말없이 걷고 있다."),
(MA, "CEO. Moi. Il y a neuf mois, j'arrivais de Strasbourg avec une valise et un marqueur vert.", "CEO. 내가. 아홉 달 전만 해도 가방 하나랑 초록 마커 하나 들고 스트라스부르에서 올라왔는데."),
(I, "Et moi, je voulais tellement le poste de manager. Je l'ai depuis un mois à peine... et on me propose déjà de partir.", "그리고 난 매니저 자리를 그렇게 원했지. 겨우 한 달 됐는데... 벌써 떠나라는 제안을 받네."),
(MA, "Partir, ça veut dire quitter Hélène. Elle nous a tout appris.", "떠난다는 건 엘렌을 떠난다는 거야. 우리한테 모든 걸 가르쳐 준 사람인데."),
(I, "Elle m'a envoyé un message tout à l'heure. Regarde.", "아까 엘렌이 문자를 보냈어. 봐."),
(None, "Sur l'écran : « Je suis fière de vous. Ne dites pas non par loyauté envers moi. Ce serait la seule mauvaise raison. H. »",
       "화면에는 이렇게 적혀 있다. '너희가 자랑스러워. 나에 대한 의리 때문에 거절하지는 마. 그게 유일하게 나쁜 이유일 테니까. H.'"),
(MA, "Elle nous connaît trop bien... Et Saint-Étienne ? Tu y es déjà allée ?", "우릴 너무 잘 아네... 그런데 생테티엔은? 가 본 적 있어?"),
(I, "Une fois, pour un match. L'OM a perdu. Je n'en garde pas un très bon souvenir.", "한 번, 축구 보러. 마르세유가 졌어. 좋은 기억은 아니야."),
(MA, "Quatre mille deux cents personnes, trois ans de pertes... J'ai peur, Inès. Pas des usines. J'ai peur de me tromper devant tout le monde.", "4,200명, 3년 연속 적자... 무서워, 이네스. 공장이 무서운 게 아니야. 모두가 보는 앞에서 틀릴까 봐 무서워."),
(I, "Moi aussi, j'ai peur. Mais ce n'est pas l'usine qui me fait le plus peur.", "나도 무서워. 그런데 나를 제일 무섭게 하는 건 공장이 아니야."),
(MA, "Alors c'est quoi ?", "그럼 뭔데?"),
(I, "C'est nous. Un CEO et une CFO qui... Tu sais ce qu'on dirait, dans un rapport de gouvernance : conflit d'intérêts. Si on accepte, on ne pourra plus jamais... nous deux.",
    "우리야. CEO와 CFO가... 지배구조 보고서에 뭐라고 쓰일지 알잖아. 이해 충돌. 우리가 수락하면, 다시는... 우리 둘은 안 돼."),
(MA, "Tu connais ma première question. Quel est le vrai problème ?", "내 첫 번째 질문 알지. 진짜 문제는 무엇인가?"),
(I, "Mathieu, ne me fais pas le coup des trois questions maintenant.", "마티외, 지금 세 가지 질문 같은 거 하지 마."),
(MA, "Si. Le vrai problème, ce n'est pas Saint-Étienne, ni Aubry, ni le règlement. Le vrai problème, c'est que depuis la Seine, je n'arrive plus à penser à autre chose qu'à toi.",
     "할 거야. 진짜 문제는 생테티엔도, 오브리도, 규정도 아니야. 진짜 문제는 센 강변에서 그날 이후로 너 말고는 다른 생각을 할 수가 없다는 거야."),
(None, "Il s'approche. Elle ne recule pas. Il l'embrasse, longtemps, près de la colonnade.", "그가 다가간다. 그녀는 물러서지 않는다. 열주 옆에서, 그가 그녀에게 오래 입을 맞춘다."),
(I, "... Enfin. Il t'a fallu neuf mois, Strasbourg.", "...드디어. 아홉 달이나 걸렸네, 스트라스부르."),
(MA, "Je suis alsacien : on prend le temps de bien faire les choses. ... Attends. Ne bouge pas.", "난 알자스 사람이야. 일을 제대로 하려면 시간이 걸리지. ...잠깐. 움직이지 마."),
(None, "Il part en courant vers les grilles dorées du parc. Cinq minutes plus tard, il revient, essoufflé, deux gobelets fumants à la main.",
       "그가 공원의 금빛 철문 쪽으로 달려 나간다. 5분 뒤, 숨을 헐떡이며 김이 나는 종이컵 두 개를 들고 돌아온다."),
(MA, "Le Petit Monceau. Rachid allait fermer. Un grand crème pour toi, comme d'habitude. Ma dette est payée.", "르 프티 몽소. 라시드가 막 문 닫으려던 참이었어. 너한텐 늘 마시던 그랑 크렘. 이제 빚 갚았다."),
(I, "Neuf mois de retard... mais il est encore chaud. Maintenant, tu ne me dois plus rien.", "아홉 달이나 늦었지만... 아직 따뜻하네. 이제 넌 나한테 빚진 게 하나도 없어."),
(MA, "Si. Une réponse.", "아니, 있어. 대답 하나."),
(I, "Plus de dette, alors plus de « Strasbourg »... Mathieu. Que fait-on lundi ?", "빚이 없으니 이제 '스트라스부르'도 끝이네... 마티외. 월요일엔 뭘 하지?"),
(MA, "Lundi, on dit oui.", "월요일엔, 예스라고 하는 거야."),
]

VOCAB = [
("B1", "mettre (qn) sur haut-parleur", "스피커폰으로 돌리다", "Je te mets sur haut-parleur. 회의 중 통화를 함께 들을 때도 씀."),
("B1", "un communiqué (de presse)", "(언론) 보도자료, 공식 발표문", "publier / diffuser un communiqué. 위기 때 기업이 처음 내놓는 공식 입장."),
("B1", "démissionner", "사임하다, 사직하다", "명사 la démission. ↔ être licencié(해고되다). Le PDG a démissionné cette nuit."),
("B2", "le greenwashing / l'écoblanchiment", "그린워싱(위장 환경주의)", "공식 프랑스어 권장어는 écoblanchiment이지만 일상·언론에서는 greenwashing이 훨씬 흔하다."),
("C1", "la reconquête de la confiance", "신뢰 회복(되찾기)", "reconquérir = 다시 정복하다. 위기 관리 문서의 단골 표현. regagner la confiance도 같은 뜻."),
("B2", "résilier (un contrat) / la résiliation", "(계약을) 해지하다 / 해지", "통신·전기·보험 계약에 쓰는 법률 용어. annuler(취소하다)와 구분."),
("B2", "une garantie d'origine", "(재생에너지) 원산지 보증서", "1 MWh 단위로 발행되는 전자 인증서. 전기와 따로 거래될 수 있다."),
("B1", "un mégawattheure (MWh)", "메가와트시", "전력량 단위. 1 MWh = 1,000 kWh. 가정의 연간 소비는 몇 MWh 수준."),
("B2", "la répression des fraudes", "소비자보호·부정행위 단속 당국", "정식 명칭은 DGCCRF. 구어로 « les fraudes »라고도 함."),
("B2", "une pratique commerciale trompeuse", "기만적 상업 관행", "소비자법 용어. 허위·과장 광고가 대표적. tromper = 속이다."),
("B2", "assurer l'intérim / par intérim", "직무를 대행하다 / 직무대행의", "la directrice générale par intérim. 정식 후임이 정해질 때까지 맡는 자리."),
("B2", "se douter de qc", "~을 눈치채다, 짐작하다", "douter de(의심하다)와 반대 느낌. Tout le monde se doutait de quelque chose."),
("B2", "un(e) élu(e) au CSE", "사회경제위원회(CSE) 위원", "CSE = comité social et économique. 직원 11명 이상 기업의 직원 대표 기구."),
("B2", "un dispositif / canal d'alerte", "(내부) 신고 제도·채널", "lanceur d'alerte = 내부 고발자. 50인 이상 기업은 내부 신고 절차가 의무."),
("B1", "avoir la parole", "발언권을 갖다", "Vous avez la parole. 회의 진행 표현. prendre / donner / couper la parole."),
("B2", "suspendre le dividende", "배당을 중단하다", "verser un dividende(배당을 지급하다). 주주가 단기 이익을 포기하는 결정."),
("B2", "une obligation verte", "녹색 채권", "환경 프로젝트에만 쓰기로 약속하고 발행하는 채권. green bond."),
("B2", "un geste commercial", "(고객) 보상, 서비스 차원의 혜택", "불만 고객에게 주는 할인·환불·선물. faire un geste commercial."),
("B2", "Admettons.", "그렇다고 치죠.", "admettre = 인정하다. 상대 주장을 일단 받아들이고 다음 단계로 넘어갈 때."),
("B2", "mettre au vote / adopté à l'unanimité", "표결에 부치다 / 만장일치로 가결된", "회의·이사회 결정 표현. à la majorité(과반수로)."),
("B2", "ne pas faire de cadeaux", "봐주는 게 없다", "구어. 협상·스포츠에서 상대에게 조금도 양보하지 않을 때."),
("B1", "être au courant (de qc)", "(~을) 알고 있다", "Je n'étais pas au courant. Tiens-moi au courant ! = 상황 알려 줘!"),
("B2", "faire le coup de (qc) à qn", "(늘 쓰는 수법)을 누구에게 쓰다", "Ne me fais pas le coup des trois questions. 상대의 상투적 행동을 놀릴 때."),
("B1", "essoufflé, -e", "숨이 찬, 헐떡이는", "souffle = 숨. 비유적으로 '동력을 잃은'(une économie essoufflée)."),
]

GRAM = [
("B2", "접속법 ①: avant que / pour que / à condition que",
 "« Qu'ils nous écoutent avant que ça explose. » « dire toute la vérité, avant qu'on la découvre à votre place » « voilà ce qu'on fait pour que ça devienne vrai » « les investisseurs en veulent, à condition que l'audit soit irréprochable » 시간(avant que), 목적(pour que), 조건(à condition que)을 나타내는 접속사 뒤에는 접속법을 쓴다. 주어가 같으면 avant de / pour + 부정사로 바꾼다: avant d'opérer, pour réparer. 반대로 après que 뒤에는 원칙적으로 직설법을 쓴다는 점도 기억하자."),
("B2", "접속법 ②: bien que (양보)",
 "« Bien que ce soit spectaculaire, toutes les entreprises d'énergie achètent du gaz en hiver. » « Bien que ce plan me coûte cher, je le trouve juste. » bien que(~이긴 하지만)는 항상 접속법을 요구한다. 회화에서는 même si + 직설법(Même si c'est spectaculaire...)이 더 흔하다. 같은 뜻이지만 접속법 여부가 다르니 주의."),
("B2", "접속법 ③: 감정·필요·관계절",
 "« Parfois, il faut accepter que ça fasse mal. » « il faut attendre que le patient soit prêt » « Je veux un plan que je puisse défendre. » il faut que, accepter que, attendre que 뒤에는 접속법. 또 '조건을 만족하는 무언가를 찾을 때' 관계절에도 접속법을 쓴다(un plan que je puisse défendre = 내가 변호할 수 있을 만한 계획). 이미 존재하는 것이면 직설법: le plan que vous avez présenté."),
("B2", "조건법: 전언·추측과 가정",
 "« Nos avocats disent qu'on reconnaîtrait ainsi notre responsabilité. » « Tu sais ce qu'on dirait, dans un rapport de gouvernance. » « Ce serait la seule mauvaise raison. » 조건법은 '그렇게 한다면 ~하게 될 것'이라는 숨은 가정을 담는다. 과거의 비현실은 조건법 과거: « Vous auriez écrit, vous ? »(당신이었다면 썼겠어요?). 언론에서는 확인되지 않은 정보를 전할 때도 조건법을 쓴다(Le PDG aurait démissionné)."),
("B2", "강조 구문 ce qui / ce que... c'est",
 "« Ce qui tuera Hélior, c'est le silence. » « C'est exactement ce que je veux dire. » « Ce n'est pas l'usine qui me fait le plus peur. » 핵심 정보를 문장 끝에 두어 긴장감을 만드는 구문이다. 주어 역할이면 ce qui, 목적어 역할이면 ce que. 발표에서 결론을 강조할 때 매우 효과적이다(ep02의 c'est... qui 구문 복습)."),
("B1", "부정 표현의 결합: ne... plus rien / plus jamais / personne... rien",
 "« Maintenant, tu ne me dois plus rien. » « on ne pourra plus jamais... nous deux » « pourquoi personne n'a rien dit ? » « et ensuite... plus rien. » 부정어는 두 개를 겹쳐 쓸 수 있고 순서는 plus → jamais → rien/personne이 일반적이다. 이때도 의미는 이중 부정(긍정)이 아니라 강한 부정이다. 구어에서는 ne를 생략하고 plus rien만 단독으로 쓰기도 한다."),
("B1", "비율·배수·분수 표현",
 "« verte à soixante-cinq pour cent » « neuf clients sur dix » « plus d'un tiers » « cinq fois plus d'appels que d'habitude » « ils en perdront trois fois plus » 비율은 à + %, '열 명 중 아홉'은 sur, 배수는 X fois plus (de)를 쓴다. 분수: la moitié(1/2), un tiers(1/3), un quart(1/4). 퍼센트는 항상 남성 단수 취급이지만 뒤 명사에 동사를 맞추는 경우가 많다(Quarante pour cent des clients sont partis)."),
("B2", "제안·협상·결정의 표현",
 "제안: « Notre première recommandation est de... » « Nous recommandons un vrai canal d'alerte. » « Il me faut un CEO et une CFO. » 조건과 양보: « à condition que... » « Admettons. » 결정: « Accordé. » « Je mets au vote. » « Adopté à l'unanimité. » 기한: « Réponse lundi. » 회의 문장은 명사구만으로도 충분히 격식 있게 들린다는 점에 주목하자."),
]

CULTURE = [
("프랑스의 그린워싱 규제와 원산지 보증서",
 "프랑스는 2021년 기후·회복력법(loi Climat et résilience)으로 환경 관련 허위·과장 광고에 대한 제재를 강화했다. 기만적 상업 관행으로 인정되면 벌금이 해당 광고·캠페인 비용의 최대 80%까지 높아질 수 있고, 조사는 소비자보호 당국(DGCCRF)이 맡는다. 전력 시장에서는 재생에너지 1 MWh마다 발행되는 원산지 보증서(garantie d'origine)를 전기와 따로 사서 '녹색 전력' 상품을 만들 수 있는데, 실제 전력의 출처와 다르다는 비판 때문에 환경청(ADEME)은 더 엄격한 기준의 녹색 전력 라벨 VertVolt를 만들었다."),
("내부 고발자(lanceur d'alerte) 보호",
 "프랑스는 2016년 사팽 2법(loi Sapin II)으로 직원 50명 이상 기업에 내부 신고 절차를 의무화했고, 2022년 와세르만법(loi Waserman)으로 보호를 강화했다. 이제 내부 고발자는 회사 내부 채널을 거치지 않고 관계 당국에 바로 신고할 수 있으며, 보복 조치로부터 보호받는다. 신고 채널이 형식적으로만 존재하고 경영진에게 바로 연결되는 경우, 직원들이 사용하지 않는다는 점이 기업 지배구조의 고전적인 문제로 꼽힌다."),
("몽소 공원과 생테티엔",
 "몽소 공원(parc Monceau)은 18세기 말 샤르트르 공작이 만든 정원으로, 고대 유적을 흉내 낸 열주(colonnade)가 둘러싼 타원형 연못, 입구의 원형 건물(rotonde) 등이 있는 낭만적인 공원이다. 모네가 이곳을 여러 번 그렸고, 금빛 장식 철문으로도 유명하다. 2부의 무대인 생테티엔(Saint-Étienne)은 루아르 지방의 옛 공업 도시로 탄광·무기·자전거·리본 산업으로 성장했으며, 2010년 유네스코 디자인 창의도시로 지정되었다. 축구팀 AS 생테티엔과 마르세유(OM)의 경기는 프랑스 축구의 전통적인 라이벌전 중 하나다."),
]
