# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
G, L, A = "Gaston", "Léa", "Antoine"
D = [
(None, "Vendredi, 18 h 45, fin mars. Il a plu toute la journée. À Montmartre, La Cave des Abbesses ferme dans trois quarts d'heure. Léa pousse la porte.", "3월 말 금요일, 오후 6시 45분. 하루 종일 비가 내렸다. 몽마르트르의 '라 카브 데 자베스'는 45분 뒤에 문을 닫는다. 레아가 문을 민다."),
(G, "Bonsoir, mademoiselle ! Entrez, entrez, le trottoir est glissant ce soir.", "안녕하세요, 아가씨! 들어오세요, 들어오세요. 오늘 저녁엔 보도가 미끄러워요."),
(L, "Bonsoir, monsieur. Merci ! Il pleut depuis ce matin, c'est insupportable.", "안녕하세요, 아저씨. 감사합니다! 아침부터 비가 와서 정말 못 견디겠어요."),
(G, "Ah, c'est Paris en mars ! Vous cherchez quelque chose de précis ?", "아, 3월의 파리가 다 그렇죠! 특별히 찾으시는 게 있나요?"),
(L, "Oui, une bouteille de vin rouge. C'est pour un dîner chez une amie, ce soir.", "네, 레드 와인 한 병이요. 오늘 저녁 친구네 집 저녁 식사에 가져갈 거예요."),
(G, "Très bien. Vous préférez un vin léger ou plutôt un vin puissant ?", "좋아요. 가벼운 와인이 좋으세요, 아니면 묵직한 와인이 좋으세요?"),
(L, "Honnêtement, je n'y connais rien. Je sais seulement que je n'aime pas le vin qui pique la gorge.", "솔직히 저는 아무것도 몰라요. 목을 따갑게 하는 와인이 싫다는 것만 알아요."),
(G, "Alors vous êtes au bon endroit ! Je vous conseille un Morgon : fruité, souple, parfait pour un dîner entre amis.", "그럼 제대로 찾아오셨네요! 모르공을 추천합니다. 과일 향이 나고 부드러워서 친구들과의 저녁 식사에 딱이에요."),
(G, "Attendez, il m'en reste une seule bouteille, là, sur l'étagère du bas.", "잠깐만요, 딱 한 병 남았어요. 저기 아래 선반에 있어요."),
(L, "Parfait, je la prends !", "좋아요, 그걸로 할게요!"),
(None, "Elle tend la main vers la bouteille. Au même moment, une autre main arrive.", "그녀가 병을 향해 손을 뻗는다. 바로 그 순간, 다른 손이 닿는다."),
(A, "Oh, pardon ! Excusez-moi, je ne vous avais pas vue.", "아, 죄송합니다! 실례했어요, 못 봤네요."),
(L, "Non, c'est moi, pardon. Vous vouliez cette bouteille, vous aussi ?", "아니에요, 제가 죄송해요. 당신도 이 병을 원하셨어요?"),
(A, "Eh bien... oui. C'est la dernière, n'est-ce pas ?", "음... 네. 마지막 병이죠, 그렇죠?"),
(G, "Ah, Antoine ! Je savais que tu passerais avant la fermeture.", "아, 앙투안! 문 닫기 전에 들를 줄 알았어."),
(A, "Bonsoir, Gaston. Je viens chercher mon Morgon du vendredi, comme d'habitude.", "안녕, 가스통. 늘 그렇듯 금요일 모르공을 가지러 왔어."),
(L, "Comme d'habitude ? Vous venez ici tous les vendredis ?", "늘 그렇듯이요? 매주 금요일마다 여기 오세요?"),
(A, "Presque tous, oui. C'est devenu un petit rituel après le travail.", "거의 매주요, 네. 퇴근 후의 작은 의식이 됐어요."),
(L, "Je comprends. Alors la bouteille est à vous. Je ne voudrais pas vous la prendre.", "이해해요. 그럼 그 병은 당신 거예요. 당신 것을 뺏고 싶지 않아요."),
(A, "Non, non, je vous en prie. Vous étiez là avant moi.", "아니에요, 아니에요, 그러지 마세요. 저보다 먼저 와 계셨잖아요."),
(L, "Pas du tout ! Nos mains sont arrivées exactement en même temps.", "전혀요! 우리 손이 정확히 동시에 닿았는걸요."),
(A, "C'est vrai. On dirait une scène de film.", "맞아요. 영화의 한 장면 같네요."),
(G, "Un film très ennuyeux, alors, parce que personne ne veut gagner !", "그럼 아주 지루한 영화겠네요. 아무도 이기려고 하지 않으니까!"),
(L, "Mais j'en ai vraiment besoin ce soir. Mon amie a emménagé la semaine dernière, c'est sa pendaison de crémaillère.", "하지만 오늘 밤엔 정말 필요해요. 친구가 지난주에 이사해서 오늘이 집들이예요."),
(A, "Ah, dans ce cas, c'est plus important que mon petit rituel. Prenez-la.", "아, 그렇다면 제 작은 의식보다 더 중요하네요. 가져가세요."),
(L, "Vous êtes sûr ? Vous avez l'air déçu.", "확실해요? 실망한 표정이신데요."),
(A, "Un peu, je l'avoue. Ce vin me rappelle la maison de mon enfance. Mais ce n'est pas grave.", "조금요, 인정할게요. 이 와인은 어린 시절 집을 떠올리게 하거든요. 하지만 괜찮아요."),
(L, "La maison de votre enfance ? Vous venez du Beaujolais ?", "어린 시절의 집이요? 보졸레 출신이세요?"),
(A, "Pas du tout. Je viens de la Loire, près de Saumur. Mais mon père adore le Morgon, et il en servait tous les dimanches.", "전혀요. 루아르 지방, 소뮈르 근처 출신이에요. 하지만 아버지가 모르공을 무척 좋아하셔서 일요일마다 내놓으셨어요."),
(L, "C'est charmant. Moi, je suis de Lyon, donc presque voisine du Beaujolais, et pourtant je ne connais rien au vin. C'est ridicule, non ?", "멋지네요. 저는 리옹 출신이라 보졸레와 거의 이웃인데도 와인은 하나도 몰라요. 우습죠?"),
(A, "Pas du tout. On peut habiter à côté d'un vignoble sans jamais y entrer.", "전혀요. 포도밭 바로 옆에 살면서도 한 번도 들어가 보지 않을 수 있죠."),
(G, "Deux provinciaux perdus à Paris, une seule bouteille... Si ce n'est pas le destin !", "파리에서 길 잃은 두 지방 사람, 그리고 단 한 병... 이게 운명이 아니면 뭐겠어요!"),
(L, "Vous exagérez, monsieur. Au fait, je m'appelle Léa. Léa Fontaine.", "과장이 심하세요, 아저씨. 참, 저는 레아예요. 레아 퐁텐."),
(A, "Enchanté, Léa. Antoine Delcourt.", "반가워요, 레아. 앙투안 델쿠르예요."),
(G, "Et moi, Gaston Roussel, propriétaire de cette humble maison depuis trente-quatre ans.", "그리고 저는 가스통 루셀, 이 소박한 가게의 주인이고 34년째 하고 있습니다."),
(L, "Enchantée à tous les deux. Vous travaillez dans le quartier, Antoine ?", "두 분 다 반갑습니다. 앙투안, 이 동네에서 일하세요?"),
(A, "Oui, je suis professeur d'histoire dans un lycée du neuvième arrondissement. Et vous ?", "네, 9구의 한 고등학교에서 역사를 가르쳐요. 당신은요?"),
(L, "Je suis graphiste. Je travaille à la maison, donc je sors surtout le soir pour ne pas devenir folle.", "저는 그래픽 디자이너예요. 집에서 일해서, 미치지 않으려고 주로 저녁에 외출해요."),
(A, "Je vous comprends. Mes élèves me rendent fou, mais au moins, je vois du monde.", "이해해요. 학생들 때문에 미칠 지경이지만, 그래도 사람은 만나니까요."),
(L, "Ils sont si terribles que ça ?", "그렇게까지 끔찍해요?"),
(A, "Non, pas vraiment. Aujourd'hui, un élève m'a demandé si j'avais connu Napoléon.", "아뇨, 그렇진 않아요. 오늘은 한 학생이 제가 나폴레옹을 만난 적이 있냐고 물었어요."),
(L, "Et vous avez répondu quoi ?", "뭐라고 대답하셨어요?"),
(A, "Que j'étais trop jeune pour Napoléon, mais que j'avais très bien connu Louis XIV.", "나폴레옹은 제가 너무 어려서 못 만났지만, 루이 14세는 아주 잘 알았다고요."),
(G, "Ha ! Ce garçon a de l'humour, mademoiselle. C'est rare chez les professeurs.", "하! 이 친구 유머가 있죠, 아가씨. 선생님들 중엔 드문 일이에요."),
(L, "Bon, revenons à notre problème. Gaston, vous n'auriez pas une autre bouteille pour Antoine ?", "자, 우리 문제로 돌아가죠. 가스통, 앙투안에게 줄 다른 병은 없나요?"),
(G, "Si, bien sûr ! J'ai mieux : un Saumur-Champigny, d'un petit vigneron que je ne vends qu'à mes meilleurs clients.", "있고말고요! 더 좋은 게 있어요. 소뮈르샹피니인데, 최고의 단골에게만 파는 작은 와인 농가 거예요."),
(A, "Un Saumur-Champigny ? Mais c'est presque chez moi ! Quel vigneron ?", "소뮈르샹피니요? 거의 우리 고향 와인인데요! 어느 농가죠?"),
(G, "Le domaine des Roches Blanches, à Dampierre-sur-Loire. Tu connais ?", "담피에르쉬르루아르에 있는 '도멘 데 로슈 블랑슈'야. 알아?"),
(A, "Les Roches Blanches ? Le fils du vigneron était dans ma classe au collège ! Quelle coïncidence !", "로슈 블랑슈요? 그 와인 농가 아들이 중학교 때 우리 반이었어요! 이런 우연이!"),
(G, "Vous voyez, Léa, ce n'est pas moi qui exagère : c'est le destin qui travaille trop.", "보세요, 레아 씨. 과장하는 건 제가 아니라 운명이 너무 열심히 일하는 거예요."),
(L, "D'accord, je vous crois, monsieur Gaston. Alors je prends le Morgon.", "알겠어요, 믿을게요, 가스통 씨. 그럼 모르공은 제가 가져갈게요."),
(A, "Et moi, je prends le Saumur-Champigny, avec plaisir.", "그럼 저는 소뮈르샹피니로 할게요, 기꺼이."),
(L, "Combien coûte le Morgon, s'il vous plaît ?", "모르공은 얼마예요?"),
(G, "Quatorze euros cinquante. Un prix d'ami, parce que vous avez un sourire sympathique.", "14유로 50센트요. 친구 가격이에요, 미소가 호감이 가니까요."),
(L, "Merci ! C'est parfait, mon budget est de quinze euros.", "감사해요! 딱 좋네요, 제 예산이 15유로거든요."),
(A, "Et le Saumur-Champigny, Gaston ?", "소뮈르샹피니는 얼마야, 가스통?"),
(G, "Dix-huit euros. Pour toi, ce sera seize, mais ne le dis à personne.", "18유로. 너한테는 16유로로 해 줄게, 하지만 아무한테도 말하지 마."),
(A, "Marché conclu. Tu es un vrai ami.", "거래 성사. 넌 진짜 친구야."),
(G, "Léa, vous payez par carte ou en espèces ?", "레아 씨, 카드로 계산하실래요, 현금으로 하실래요?"),
(L, "Par carte, si c'est possible.", "가능하면 카드로요."),
(G, "Bien sûr. Tenez, tapez votre code ici... Et voilà ! Je vous fais un paquet cadeau ?", "물론이죠. 자, 여기에 비밀번호를 눌러 주세요... 자, 됐습니다! 선물 포장해 드릴까요?"),
(L, "Oui, ce serait très gentil. C'est un cadeau pour mon amie, après tout.", "네, 그래 주시면 정말 고맙겠어요. 어쨌든 친구에게 주는 선물이니까요."),
(None, "Gaston emporte la bouteille dans l'arrière-boutique. Léa et Antoine restent seuls.", "가스통이 병을 들고 안쪽 창고로 간다. 레아와 앙투안만 남는다."),
(A, "Votre amie a de la chance : le Morgon, c'est un excellent choix pour une soirée.", "친구분은 운이 좋네요. 모르공은 저녁 모임에 아주 좋은 선택이에요."),
(L, "J'espère. Mais j'ai un petit problème : on va me demander pourquoi j'ai choisi ce vin, et je n'aurai rien à dire.", "그러길 바라요. 그런데 작은 문제가 있어요. 왜 이 와인을 골랐냐고 물을 텐데, 저는 할 말이 없을 거예요."),
(A, "Vous pouvez dire que c'est un vin à la fois simple et complexe. Ça marche toujours.", "단순하면서 동시에 복합적인 와인이라고 말하면 돼요. 항상 통하는 말이에요."),
(L, "Mais ça ne veut rien dire !", "하지만 그건 아무 의미도 없잖아요!"),
(A, "C'est vrai. Alors je vais vous aider un peu. Vous aimez les fruits rouges ?", "맞아요. 그럼 제가 조금 도와줄게요. 붉은 과일 좋아하세요?"),
(L, "J'adore les cerises et les fraises, surtout en été.", "체리랑 딸기를 정말 좋아해요, 특히 여름에요."),
(A, "Alors vous allez les retrouver dans le Morgon : des arômes de cerise noire, parfois de kirsch, avec une petite pointe de poivre.", "그럼 모르공에서 그 향을 다시 만나게 될 거예요. 검은 체리 향, 가끔은 키르슈 향, 그리고 후추의 은은한 끝맛이 있어요."),
(L, "Du poivre dans le vin ? Vous plaisantez ?", "와인에 후추요? 농담이시죠?"),
(A, "Pas du tout. C'est ce qu'on appelle une note épicée. On la sent surtout au nez, avant de goûter.", "아니에요. 그걸 스파이시 노트라고 해요. 마시기 전에 코로 주로 느끼죠."),
(L, "Et dans la bouche, qu'est-ce que je dois sentir ?", "그럼 입 안에서는 뭘 느껴야 하죠?"),
(A, "Des tanins souples, c'est-à-dire que ça ne « gratte » pas la langue. C'est exactement ce que vous aimez : un vin qui ne pique pas.", "부드러운 탄닌이요. 혀를 '긁지' 않는다는 뜻이죠. 바로 당신이 좋아하는 와인이에요. 따갑지 않은 와인."),
(L, "Vous avez bonne mémoire : vous m'écoutiez !", "기억력이 좋으시네요. 제 말을 듣고 계셨군요!"),
(A, "J'écoute toujours quand on parle de vin. C'est une déformation professionnelle... enfin, presque : je suis prof d'histoire, pas sommelier.", "와인 이야기가 나오면 늘 귀를 기울여요. 직업병이죠... 아니, 거의요. 전 역사 교사지 소믈리에가 아니니까요."),
(L, "Votre père serait fier de vous.", "아버님이 자랑스러워하시겠어요."),
(A, "Il serait surtout surpris que je sois resté à Paris. Il rêve toujours que je reprenne le domaine.", "오히려 제가 파리에 남아 있다는 사실에 놀라실 거예요. 여전히 제가 농장을 물려받기를 꿈꾸시거든요."),
(L, "Et vous, vous en avez envie ?", "당신은요, 그러고 싶으세요?"),
(A, "Je ne sais pas encore. Disons que c'est une question que je repousse depuis des années.", "아직 모르겠어요. 몇 년째 미루고 있는 문제라고 해 둘게요."),
(L, "Je connais ça. Moi aussi, j'ai des décisions que je fais semblant d'oublier.", "그 마음 알아요. 저도 잊은 척하고 있는 결정이 있거든요."),
(A, "Ah oui ? Lesquelles, si ce n'est pas indiscret ?", "아, 그래요? 실례가 안 된다면 어떤 건가요?"),
(L, "Ce serait trop long pour un vendredi soir, et mon amie m'attend. Une prochaine fois, peut-être.", "금요일 저녁에 얘기하기엔 너무 길어요. 친구도 기다리고 있고요. 다음 기회에요, 아마도."),
(G, "Et voilà, mademoiselle, un paquet digne d'un grand cru !", "자, 아가씨, 그랑 크뤼에 걸맞은 포장입니다!"),
(L, "C'est magnifique, merci beaucoup, Gaston.", "정말 멋져요, 정말 고맙습니다, 가스통."),
(G, "Ce n'est rien. Dites-moi, vous êtes libre jeudi prochain, vers dix-huit heures ?", "별것 아니에요. 말해 봐요, 다음 주 목요일 6시쯤 시간 있으세요?"),
(L, "Pourquoi cette question ? Je crois que oui.", "왜 그런 걸 물으세요? 아마 있을 거예요."),
(G, "Je fais une petite dégustation tous les jeudis. C'est gratuit, et on y apprend à ne plus dire « simple et complexe » à tort et à travers.", "저는 목요일마다 작은 시음회를 열어요. 무료이고, '단순하면서 복합적'이라는 말을 아무 데나 쓰지 않는 법을 배울 수 있죠."),
(L, "Vous avez tout entendu !", "다 들으셨군요!"),
(G, "Dans ma boutique, les murs ont des oreilles, et les bouteilles aussi.", "우리 가게에서는 벽에도 귀가 있고, 병들도 마찬가지예요."),
(A, "Je serai là, comme tous les jeudis. Enfin... si vous voulez venir, bien sûr.", "저도 있을 거예요, 매주 목요일처럼요. 음... 오고 싶으시다면요, 물론."),
(L, "Pourquoi pas ? Je ne promets rien, mais je viendrai peut-être.", "안 될 거 있나요? 약속은 못 하지만, 올지도 몰라요."),
(A, "C'est déjà beaucoup. Je vous raccompagne à la porte ? Il y a encore des flaques partout.", "그것만으로도 대단한 거예요. 문까지 바래다 드릴까요? 아직 곳곳에 물웅덩이가 있어요."),
(L, "Merci, mais je me débrouille. Je suis lyonnaise, j'ai l'habitude de la pluie.", "고맙지만 혼자 갈 수 있어요. 저는 리옹 사람이라 비에 익숙해요."),
(A, "Alors bonne soirée, Léa. Et dites à votre amie que le Morgon, ça se boit entre amis, pas entre experts.", "그럼 즐거운 저녁 보내요, 레아. 그리고 친구분께 전해 줘요. 모르공은 전문가들끼리가 아니라 친구들끼리 마시는 거라고."),
(L, "Je n'y manquerai pas. Bonne soirée, Antoine. Au revoir, Gaston !", "꼭 전할게요. 즐거운 저녁 보내요, 앙투안. 안녕히 계세요, 가스통!"),
(G, "Au revoir, mademoiselle Léa. À jeudi, peut-être !", "안녕히 가세요, 레아 양. 목요일에 봐요, 아마도요!"),
(None, "La clochette de la porte tinte. Léa sort sous la pluie fine.", "문의 작은 종이 울린다. 레아가 가랑비 속으로 나간다."),
(A, "Elle ne reviendra pas, tu crois ?", "그녀는 다시 안 올 것 같지?"),
(G, "Je connais les gens qui disent « peut-être » avec ce sourire-là. Ils reviennent toujours.", "저런 미소로 '아마도'라고 말하는 사람들을 나는 알아. 늘 돌아오지."),
(A, "Tu es incorrigible. Tu as tout arrangé depuis le début, avoue !", "넌 못 말려. 처음부터 다 짜 놓은 거지, 자백해!"),
(G, "Moi ? Jamais ! Le destin n'a pas besoin d'un vieux caviste. Il a juste besoin d'une dernière bouteille.", "내가? 절대 아니지! 운명은 늙은 와인 상인 따윈 필요 없어. 마지막 한 병이면 충분하지."),
(A, "Alors la prochaine fois, garde-moi deux bouteilles. Une pour moi, une pour... une amie.", "그럼 다음엔 두 병을 남겨 줘. 하나는 내 거, 하나는... 친구 거."),
(G, "Je les garde déjà, mon garçon. Je les garde déjà.", "벌써 남겨 놓고 있어, 얘야. 벌써 남겨 놓고 있다니까."),
]

VOCAB = [
("A2","comme d'habitude","늘 그렇듯, 평소처럼","습관적 행동을 가리킬 때. « Je viens chercher mon Morgon du vendredi, comme d'habitude. »"),
("A2","Je vous en prie","별말씀을요 / 그러세요","양보·사양할 때 쓰는 정중한 표현. « Non, non, je vous en prie. »"),
("A2","ce n'est pas grave","괜찮아요, 별일 아니에요","가벼운 실망·사과에 대한 응답"),
("A2","un paquet cadeau","선물 포장","가게에서 « Je vous fais un paquet cadeau ? » 는 정해진 서비스 문구"),
("A2","Marché conclu.","거래 성사","가격 합의 후 쓰는 구어 표현"),
("B1","glissant(e)","미끄러운","un trottoir glissant (미끄러운 보도). 비 오는 날 필수 어휘"),
("B1","je n'y connais rien","나는 그것에 대해 전혀 모른다","s'y connaître en / connaître quelque chose à…: 분야 지식을 말함. 대화에서는 « je ne connais rien au vin » 도 사용"),
("B1","piquer la gorge","목을 따갑게 하다","와인·술의 자극적인 느낌을 표현"),
("B1","fruité / souple","과일 향이 나는 / 부드러운","와인 평가의 기본 형용사. souple = 탄닌이 거칠지 않음"),
("B1","On dirait + 명사","~ 같네요","« On dirait une scène de film. » 비유·인상을 말할 때"),
("B1","un prix d'ami","친구 가격(특별 할인가)","친한 사이에 깎아 주는 가격"),
("B1","se débrouiller","알아서 해내다, 잘 헤쳐 나가다","« Je me débrouille. » = 혼자 할 수 있어요 (도움 사양)"),
("B1","rendre + 형용사","~하게 만들다","« Mes élèves me rendent fou. » 학생들이 나를 미치게 한다"),
("B2","insupportable","견딜 수 없는","날씨·소음·사람에게 모두 사용 가능한 강한 부정 표현"),
("B2","emménager / pendaison de crémaillère","이사 들어오다 / 집들이","crémaillère는 벽난로의 갈고리에서 온 말. 집들이 파티를 가리킴"),
("B2","avouer","고백하다, 인정하다","« Un peu, je l'avoue. » 삽입절처럼 문장 끝에 붙여 쓰기도 함"),
("B2","un vignoble / un vigneron","포도밭(지역) / 와인 생산자","vigne(포도나무) → vigneron(재배·양조인), domaine(와인 농장)"),
("B2","provincial(e)","지방 출신(의)","파리 기준으로 '지방'. 약간의 농담·평가가 섞일 수 있음"),
("B2","un tanin / une note épicée / un arôme","탄닌 / 스파이시 노트 / 향","시음 기본 용어. tanin souple = 부드러운 탄닌"),
("B2","repousser une décision","결정을 미루다","« une question que je repousse depuis des années »"),
("B2","faire semblant de + 동사원형","~하는 척하다","« Je fais semblant d'oublier. »"),
("B2","un caviste","와인 가게 주인(판매인)","와인숍 운영자를 가리키는 일반 명사. sommelier(레스토랑 와인 서비스 담당)와 구분"),
("C1","Si ce n'est pas le destin !","이게 운명이 아니면 뭐란 말인가!","« Si ce n'est pas… ! » 반어적 강조 구문 (= 틀림없이 ~다)"),
("C1","une déformation professionnelle","직업병(직업 때문에 몸에 밴 습관)","일상 대화에서 자주 쓰이는 관용 표현"),
("C1","à tort et à travers","아무렇게나, 함부로","« dire quelque chose à tort et à travers » = 무분별하게 말하다"),
("C1","Les murs ont des oreilles.","벽에도 귀가 있다 (낮말은 새가 듣고 밤말은 쥐가 듣는다)","속담. 가스통이 농담으로 응용"),
("C1","digne de + 명사","~에 걸맞은, ~할 만한","« un paquet digne d'un grand cru » 격식·유머 모두 가능"),
("C1","incorrigible","(고칠 수 없을 만큼) 못 말리는","애정 섞인 핀잔으로 사용"),
]

GRAM = [
("A2","depuis + 현재형: 지속 기간·시작 시점",
 "« Il pleut depuis ce matin. » 지금도 계속되는 상태·행동은 현재형 + depuis(~이래로)를 쓴다. « Je repousse cette question depuis des années. » 도 같은 구조로, 한국어로는 '~해 왔다'로 옮긴다."),
("A2","être / avoir / vouloir 와 정중한 조건법",
 "« Je ne voudrais pas vous la prendre. » (직설법 je ne veux pas보다 완곡) / « Vous n'auriez pas une autre bouteille ? » (조건법으로 부탁을 부드럽게) / « Ce serait très gentil. » 조건법 현재는 요청·사양을 정중하게 만드는 가장 쉬운 도구다."),
("B1","대명사 en · y · 직접목적 le/la",
 "« Je la prends » (la = la bouteille), « il m'en reste une seule » (en = 수량의 대상), « il en servait tous les dimanches », « j'en ai besoin » (avoir besoin de → en), « je n'y connais rien » (y = 그 분야에). 명사를 반복하지 않고 대명사로 받는 것이 구어체의 핵심."),
("B1","imparfait 와 passé composé의 구분",
 "상태·배경·반복은 imparfait: « Vous étiez là avant moi », « il en servait tous les dimanches », « j'étais trop jeune ». 완결된 사건은 passé composé: « Mon amie a emménagé la semaine dernière », « Nos mains sont arrivées en même temps », « Un élève m'a demandé… »."),
("B1","미래 속 과거(futur dans le passé): 과거 동사 + 조건법",
 "« Je savais que tu passerais avant la fermeture. » 주절이 과거(savais)면 종속절의 '앞으로의 일'은 조건법 현재(passerais)로 표현한다. 간접화법에도 자주 등장: « Un élève m'a demandé si j'avais connu Napoléon » (대과거)."),
("B1","의문문의 세 가지 형태와 tu/vous",
 "억양만 올리기: « Vous venez ici tous les vendredis ? » / est-ce que: « Est-ce que vous travaillez ici ? » / 부가의문: « C'est la dernière, n'est-ce pas ? ». 손님·낯선 사람에게는 vous, 오랜 친구 사이(앙투안↔가스통)는 tu를 쓴다. 레아는 두 사람 모두에게 vous를 사용하고 있다는 점에 주목."),
("B2","부정어 조합과 ne … que",
 "ne … rien: « je n'y connais rien », « je n'aurai rien à dire » / sans jamais + 동사원형: « sans jamais y entrer » / ne … que (= 오직): « que je ne vends qu'à mes meilleurs clients ». 부정 형태이지만 뜻은 한정(~에게만)이므로 주의."),
("C1","감정·판단 표현 뒤의 접속법(과거)",
 "« Il serait surtout surpris que je sois resté à Paris. » surpris que + 접속법. 일어난 사실에 대한 감정(놀람, 유감, 기쁨)을 말할 때는 접속법을 쓰며, 이미 끝난 일은 접속법 과거(sois resté)를 사용한다. 뒤의 « Il rêve que je reprenne le domaine » 도 바람·꿈을 나타내는 동사 뒤 접속법 현재(reprenne)."),
]

CULTURE = [
("모르공(Morgon)과 보졸레 크뤼",
 "보졸레(Beaujolais)에는 10개의 '크뤼'(Morgon, Fleurie, Moulin-à-Vent 등)가 있다. 모르공은 가메(Gamay) 품종으로 만들며 보통 보졸레 누보보다 구조감이 있고 몇 년 숙성도 가능하다. 가격은 대체로 15유로 안팎이라 '친구들과 함께 마시는 와인'으로 인기가 높다."),
("vous 와 tu, 그리고 호칭",
 "프랑스어 대화에서 첫 만남은 거의 항상 vous로 시작한다. 이야기가 진전되며 tu로 바꾸는 시점은 두 사람의 관계 변화를 보여 주는 신호이므로, 앞으로의 화에서 중요한 장치로 활용된다 (4화에서 전환)."),
("la pendaison de crémaillère(집들이)",
 "새집으로 이사한 뒤 친구들을 초대해 여는 파티. 보통 손님이 와인이나 작은 선물을 들고 간다. 그래서 레아가 와인을 사러 온 상황이 자연스럽다."),
("가게의 목요일 시음회(dégustation)",
 "프랑스의 동네 와인숍(cave)은 단골 관리와 교육을 위해 정기 시음회를 여는 경우가 많다. 이 시음회는 앞으로 7화의 무대이자 두 사람이 다시 만나는 장치가 된다."),
]

META = dict(part=1, ep=1, part_label="제1부 첫 잔 · Premier verre", title_fr="Une dernière bouteille", title_ko="마지막 한 병",
 place="파리 18구 몽마르트르, 와인숍 La Cave des Abbesses · 3월 말 금요일 18시 45분",
 chars="Léa Fontaine (레아, 31세, 그래픽 디자이너) · Antoine Delcourt (앙투안, 34세, 역사 교사) · Gaston Roussel (가스통, 가게 주인)",
 wine="Morgon (보졸레 크뤼) 과 Saumur-Champigny (루아르)",
 focus="인사·자기소개, 주문과 가격, tu/vous, 복합과거와 반과거의 구분, en/y, 조건법 정중 표현",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제2화 « Le conseil de Gaston » : 목요일 시음회에 레아가 정말 나타날까? 가스통은 두 사람에게 서로 다른 와인을 권한다.")
