# -*- coding: utf-8 -*-
G, L, A = "Gaston", "Léa", "Antoine"
D = [
(None, "Jeudi suivant, 18 h 10. Gaston aligne des verres sur le comptoir. Antoine, déjà là, regarde sa montre pour la troisième fois quand la porte s'ouvre.", "다음 주 목요일 오후 6시 10분. 가스통이 카운터에 와인 잔을 나란히 놓고 있다. 먼저 와 있던 앙투안이 세 번째로 시계를 보는 순간 문이 열린다."),
(G, "Tiens, tiens ! Mademoiselle Léa ! Vous êtes venue !", "이런, 이런! 레아 양! 와 주셨군요!"),
(L, "Bonsoir, Gaston. Bonsoir, Antoine. Je suis un peu en retard, excusez-moi.", "안녕하세요, 가스통. 안녕하세요, 앙투안. 조금 늦었어요, 죄송해요."),
(A, "Bonsoir, Léa. Vous n'êtes pas en retard : la dégustation commence à dix-huit heures quinze.", "안녕하세요, 레아. 늦지 않으셨어요. 시음회는 6시 15분에 시작해요."),
(G, "Antoine regarde sa montre depuis une demi-heure, mademoiselle.", "앙투안은 삼십 분 전부터 시계를 보고 있었답니다, 아가씨."),
(A, "Gaston, s'il te plaît !", "가스통, 제발!"),
(L, "(rit) Ne vous inquiétez pas, Antoine. Je tiens toujours mes promesses, même les promesses incertaines.", "(웃으며) 걱정 마세요, 앙투안. 저는 약속은 지켜요, 불확실한 약속이라도요."),
(G, "Alors, racontez-nous : le Morgon, ça s'est bien passé, vendredi dernier ?", "그럼 얘기해 줘요. 지난 금요일에 모르공은 어땠어요?"),
(L, "Très bien ! J'ai dit à mes amis que c'était un vin à la fois simple et complexe.", "아주 좋았어요! 친구들한테 단순하면서 동시에 복합적인 와인이라고 말했거든요."),
(A, "Et personne ne vous a demandé ce que cela voulait dire ?", "그럼 아무도 그게 무슨 뜻이냐고 묻지 않았어요?"),
(L, "Si ! Le mari de mon amie, Mehdi, adore le vin. Il a répondu : « Exactement ! C'est la bonne description. »", "물어봤죠! 친구 남편 메흐디는 와인을 아주 좋아해요. 그가 대답했어요. '맞아요! 정확한 표현이에요.'"),
(G, "Vous voyez ? Les experts se trompent souvent. Il suffit de parler avec assurance.", "보세요? 전문가들도 자주 착각해요. 자신 있게 말하기만 하면 되죠."),
(L, "Et nous avons tout bu avant minuit. La bouteille était vide à onze heures.", "그리고 자정 전에 다 마셨어요. 병은 11시에 이미 비었어요."),
(G, "Bon, passons aux choses sérieuses. Avant de goûter, j'ai besoin de connaître vos goûts.", "자, 이제 본론으로 들어가죠. 시음하기 전에 두 사람의 취향을 알아야 해요."),
(L, "Mes goûts ? Je n'ai pas de goûts de connaisseuse, vous savez.", "제 취향이요? 전 애호가 취향 같은 건 없어요."),
(G, "Je ne parle pas de vin. Je parle de nourriture. Qu'est-ce que vous mangez le soir ?", "와인 얘기가 아니에요. 음식 얘기죠. 저녁엔 뭘 드세요?"),
(L, "Euh... Beaucoup de pâtes, de la salade, des légumes quand j'ai le courage d'aller au marché.", "음... 파스타를 많이 먹고, 샐러드, 그리고 시장에 갈 용기가 있을 땐 채소요."),
(G, "Et du fromage ?", "치즈는요?"),
(L, "J'adore le fromage ! Surtout le chèvre, avec un peu de miel.", "치즈는 정말 좋아해요! 특히 염소 치즈, 꿀을 살짝 곁들여서요."),
(A, "Bon choix. Moi, je mange du fromage tous les jours, même le dimanche.", "좋은 선택이에요. 저는 날마다 치즈를 먹어요, 일요일에도요."),
(L, "Le dimanche, c'est un jour comme les autres, non ?", "일요일도 다른 날과 똑같은 날 아닌가요?"),
(A, "Pas chez moi. Le dimanche, mon père sortait toujours une vieille bouteille et un camembert fermier.", "우리 집에선 아니었어요. 일요일마다 아버지가 오래된 와인 한 병과 농가 카망베르를 꺼내셨죠."),
(G, "Et vous, Léa, vous buvez du café le soir ?", "레아 양은 저녁에 커피 마셔요?"),
(L, "Jamais ! Je ne bois pas de café après seize heures, sinon je ne dors pas.", "절대 안 마셔요! 오후 4시 이후엔 커피를 안 마셔요, 안 그러면 잠을 못 자거든요."),
(A, "Moi, c'est le contraire : je bois du café même à minuit, et je dors comme un bébé.", "저는 정반대예요. 자정에도 커피를 마시는데 아기처럼 자요."),
(G, "Vous voyez, il n'y a pas deux personnes identiques. C'est pour ça qu'il n'y a pas un seul vin pour tout le monde.", "보세요, 똑같은 사람은 둘도 없어요. 그래서 모두에게 맞는 와인 하나는 없는 거죠."),
(L, "Des goûts et des couleurs, on ne discute pas, comme on dit.", "취향 문제는 논쟁하는 게 아니라고들 하잖아요."),
(G, "Exactement. Mais ce soir, nous allons discuter quand même. Voici trois verres.", "맞아요. 하지만 오늘 저녁엔 그래도 한번 논쟁해 봅시다. 자, 잔 세 개입니다."),
(G, "Le premier, c'est un Muscadet sur lie : un vin blanc de la Loire, très frais, parfait avec les fruits de mer.", "첫 번째는 뮈스카데 쉬르 리입니다. 루아르의 화이트 와인인데 아주 상큼해서 해산물과 완벽하게 어울려요."),
(A, "Les huîtres, surtout. Chez nous, on en mange à Noël avec un Muscadet.", "특히 굴이요. 우리 집에선 크리스마스에 뮈스카데랑 굴을 먹어요."),
(L, "Je n'ai jamais mangé d'huîtres. Elles me font un peu peur.", "저는 굴을 한 번도 먹어 본 적이 없어요. 좀 무서워요."),
(A, "C'est normal, elles ont l'air bizarres. Mais ce n'est pas aussi terrible que ça en a l'air.", "당연해요, 생긴 게 이상하니까요. 하지만 보기만큼 끔찍하진 않아요."),
(G, "Goûtez, mademoiselle. Sentez d'abord, puis buvez une petite gorgée.", "맛보세요, 아가씨. 먼저 향을 맡고, 그다음 한 모금 마셔 보세요."),
(L, "Hmm. Ça sent le citron et peut-être... la pomme verte ?", "음. 레몬 향이 나고, 어쩌면... 풋사과 향도 나요?"),
(G, "Bravo ! Vous avez le nez d'une professionnelle.", "브라보! 전문가 같은 코를 가지셨네요."),
(L, "Je trouve que c'est très frais. C'est léger, et j'ai envie d'en reprendre.", "아주 상큼하다고 느껴요. 가볍고 한 모금 더 마시고 싶어요."),
(A, "À mon avis, c'est un peu trop acide, mais c'est le caractère du Muscadet.", "제 생각엔 산도가 좀 강한데, 그게 뮈스카데의 특징이죠."),
(L, "Trop acide ? Pour moi, c'est justement ce qui est agréable !", "너무 시다고요? 저는 오히려 그게 좋은걸요!"),
(G, "Voilà une première divergence. Passons au deuxième verre : un Chinon, un vin rouge de chez Antoine.", "첫 번째 의견 차이가 나왔네요. 두 번째 잔으로 갑시다. 시농, 앙투안의 고향 레드 와인이에요."),
(A, "Du Chinon ! Cabernet franc, n'est-ce pas ? C'est le vin de mon enfance, avec le Morgon.", "시농이군요! 카베르네 프랑이죠? 모르공과 함께 제 어린 시절의 와인이에요."),
(G, "Exact. Un vin rouge léger, avec des arômes de framboise et de poivron vert.", "맞아. 라즈베리와 풋고추 향이 나는 가벼운 레드 와인이야."),
(L, "Du poivron vert dans un vin ? Après le poivre, voilà le poivron !", "와인에 피망이요? 후추 다음엔 피망이라니!"),
(A, "Vous vous souvenez du poivre ? Vous avez bonne mémoire, vous aussi.", "후추를 기억하세요? 당신도 기억력이 좋으시네요."),
(L, "Je me souviens de tout ce qui est étrange. C'est un défaut.", "이상한 건 다 기억해요. 단점이죠."),
(A, "C'est surtout une qualité, croyez-moi.", "그건 무엇보다 장점이에요, 믿어 보세요."),
(G, "Goûtez, tous les deux. Ensuite, vous me direz ce que vous en pensez.", "둘 다 맛보세요. 그다음 어떻게 생각하는지 말해 줘요."),
(A, "Ah... Chez moi. C'est exactement ça. Un peu de fraîcheur, des fruits rouges, et une petite note de terre après.", "아... 우리 집 맛이야. 바로 이거예요. 약간의 신선함, 붉은 과일, 그리고 끝에 흙 내음이 살짝 나요."),
(L, "Moi, je le trouve un peu... triste. Il manque quelque chose.", "저는 좀... 쓸쓸하게 느껴져요. 뭔가 부족해요."),
(A, "Triste ? Le Chinon n'est jamais triste ! Il est mélancolique, c'est différent.", "쓸쓸하다고요? 시농은 절대 쓸쓸하지 않아요! 우수에 젖었다고 해야죠, 다르잖아요."),
(G, "Ha ! Un vin mélancolique : voilà un descriptif que je n'ai jamais lu sur une étiquette.", "하! 우수에 젖은 와인이라니, 라벨에서 한 번도 읽어 본 적 없는 표현이네요."),
(L, "Je préfère le premier. Le Muscadet est plus vivant, plus gai.", "저는 첫 번째가 더 좋아요. 뮈스카데가 더 생동감 있고 더 밝아요."),
(A, "Et moi, je préfère le Chinon. Il a plus de profondeur.", "저는 시농이 더 좋아요. 더 깊이가 있어요."),
(G, "Chacun voit midi à sa porte. Maintenant, le troisième verre : un Saint-Joseph, de la vallée du Rhône. Un vin rouge plus puissant.", "각자 자기 기준대로 보는 법이지. 이제 세 번째 잔입니다. 론 계곡의 생조제프, 더 묵직한 레드 와인이에요."),
(L, "Plus puissant ? C'est-à-dire ?", "더 묵직하다고요? 무슨 뜻이죠?"),
(A, "Ça veut dire qu'il a plus de corps, plus de force en bouche. On le sent presque dans la gorge.", "몸체가 더 크고 입 안에서 더 힘이 느껴진다는 뜻이에요. 목에서까지 느껴지죠."),
(L, "Comme un vin qui pique, alors ?", "그럼 따가운 와인 같은 건가요?"),
(A, "Non, pas du tout. Un vin qui pique est un vin mal fait. Un vin puissant est un vin qui a du caractère.", "아뇨, 전혀요. 따가운 와인은 잘못 만든 와인이고, 묵직한 와인은 개성이 있는 와인이에요."),
(G, "Antoine a raison. Allez-y, sentez-le d'abord.", "앙투안 말이 맞아요. 먼저 향부터 맡아 보세요."),
(L, "Ça sent... la confiture de mûres, et un peu la fumée. Comme un feu de cheminée.", "음... 블랙베리 잼 냄새랑 연기 냄새가 조금 나요. 벽난로 불 같아요."),
(G, "Magnifique ! C'est exactement ce qu'on appelle des notes fumées. Vous progressez vite.", "훌륭해요! 바로 스모키 노트라고 하는 거예요. 금방 느시네요."),
(L, "Et en bouche... c'est plus rond que le Chinon, plus chaud. Je l'aime bien, finalement.", "입 안에서는... 시농보다 더 둥글고 더 따뜻해요. 결국 이건 마음에 들어요."),
(A, "Moi aussi, je l'aime bien. C'est un bon compromis.", "저도 마음에 들어요. 좋은 절충안이에요."),
(G, "Alors, faisons le bilan. Antoine, quel est ton préféré ?", "그럼 정리해 보자. 앙투안, 네 최고는 뭐야?"),
(A, "Le Chinon, sans hésiter. Parce qu'il me rappelle la maison, mais aussi parce qu'il est élégant.", "망설임 없이 시농이에요. 집을 떠올리게 하기도 하고, 우아하기도 해서요."),
(G, "Et vous, Léa ?", "레아 양은요?"),
(L, "Le Muscadet. Ça me surprend moi-même : je pensais que j'aimais le vin rouge.", "뮈스카데요. 저 자신도 놀랐어요. 제가 레드 와인을 좋아하는 줄 알았거든요."),
(A, "Vous pensiez ça parce que vous n'aviez jamais essayé autre chose.", "다른 걸 한 번도 안 마셔 봐서 그렇게 생각하셨던 거죠."),
(L, "Peut-être. En fait, je n'ai jamais choisi de vin moi-même avant vendredi dernier.", "그럴지도요. 사실 지난 금요일 전까지는 제가 직접 와인을 골라 본 적이 없어요."),
(G, "Alors vous êtes en train de découvrir un monde entier. J'adore voir ça.", "그럼 한 세계를 통째로 발견하는 중이군요. 그런 모습 보는 게 참 좋아요."),
(L, "Je dois avouer que c'est agréable. J'ai l'impression d'apprendre une nouvelle langue.", "인정해야겠어요, 기분이 좋아요. 새로운 언어를 배우는 기분이에요."),
(A, "C'est exactement ça. Le vin est une langue, avec sa grammaire et son vocabulaire.", "정확히 그거예요. 와인은 하나의 언어고 문법과 어휘가 있어요."),
(G, "Et comme toutes les langues, il faut la pratiquer pour la parler. Voilà pourquoi je vous propose quelque chose.", "그리고 모든 언어가 그렇듯 말하려면 연습해야 해요. 그래서 제안할 게 있어요."),
(L, "Je sens le piège.", "함정의 냄새가 나는데요."),
(G, "Aucun piège ! Samedi après-midi, je fais un duel : un vin rouge contre un vin blanc. Vous deux, chacun défend son camp.", "함정은 없어요! 토요일 오후에 대결을 열 거예요. 레드 와인 대 화이트 와인. 두 사람이 각자 자기 진영을 지키는 거죠."),
(A, "Moi, je défends le rouge, évidemment.", "저는 당연히 레드 쪽을 지키죠."),
(L, "Et moi, le blanc. Mais attention : je suis une novice, vous allez gagner trop facilement.", "그럼 저는 화이트요. 하지만 조심하세요. 저는 초보라서 너무 쉽게 이기실 거예요."),
(A, "On verra. Il ne faut jamais sous-estimer un débutant motivé.", "두고 봐야죠. 의욕 있는 초보자를 절대 과소평가하면 안 되니까요."),
(G, "Je note : « Léa, camp blanc ; Antoine, camp rouge. » Moi, je suis neutre comme la Suisse.", "적어 둘게요. '레아, 화이트 진영. 앙투안, 레드 진영.' 저는 스위스처럼 중립이에요."),
(A, "Neutre, toi ? Tu as déjà choisi ton camp depuis trente ans.", "중립이라고, 네가? 삼십 년 전부터 이미 편을 정했잖아."),
(G, "Mon camp, c'est celui de la bouteille qui se vend. (Il sourit.) Allez, buvons un dernier verre ensemble.", "내 편은 팔리는 병 편이지. (미소 지으며) 자, 마지막으로 다 같이 한 잔 합시다."),
(L, "À notre première vraie dégustation !", "우리의 첫 번째 진짜 시음을 위해!"),
(A, "À la bonne santé de notre novice !", "우리 초보 시음가의 건강을 위해!"),
(G, "Et à la mélancolie du Chinon, que personne ne comprendra jamais !", "그리고 아무도 이해하지 못할 시농의 우수를 위해!"),
(L, "Antoine, vous avez vraiment l'air vexé.", "앙투안, 정말 기분이 상한 것 같아요."),
(A, "Pas du tout. Je réfléchis à mes arguments pour samedi.", "전혀요. 토요일을 위한 논거를 생각하고 있어요."),
(L, "Vous avez deux jours pour les préparer. Moi, je n'ai besoin que d'un verre de Muscadet.", "준비할 시간이 이틀이에요. 저는 뮈스카데 한 잔이면 충분하고요."),
(G, "Elle est dangereuse, cette novice. Antoine, fais attention.", "이 초보, 위험한데. 앙투안, 조심해."),
(A, "Je fais toujours attention, Gaston. C'est mon métier : je regarde le passé pour éviter les erreurs.", "난 항상 조심해, 가스통. 그게 내 직업이야. 과거를 보면서 실수를 피하려는 거지."),
(L, "Et vous les évitez, vos erreurs ?", "그래서 실수는 피하고 계세요?"),
(A, "Rarement. Mais j'apprends à les aimer.", "드물게요. 하지만 그것들을 좋아하는 법을 배우는 중이에요."),
(G, "Voilà ! La philosophie du vigneron : on apprend de chaque millésime, même les mauvais.", "바로 그거야! 포도 재배자의 철학이지. 나쁜 빈티지에서도 배우는 거야."),
(L, "Bon, il est dix-neuf heures. Je dois rentrer travailler, hélas.", "음, 벌써 7시네요. 아쉽지만 일하러 돌아가야 해요."),
(A, "Vous habitez loin d'ici ?", "여기서 멀리 사세요?"),
(L, "Pas trop. À dix minutes à pied, je crois. Mais je suis très mauvaise pour estimer les distances.", "그리 멀지 않아요. 걸어서 십 분쯤일걸요. 하지만 거리를 가늠하는 건 정말 못해요."),
(G, "Mademoiselle, à samedi donc ?", "아가씨, 그럼 토요일에 봅니까?"),
(L, "À samedi. Je viendrai, cette fois, c'est promis. Même sans parapluie !", "토요일에요. 이번엔 꼭 올게요, 약속해요. 우산이 없어도요!"),
(A, "Ce n'était pas une promesse incertaine, finalement.", "결국 불확실한 약속이 아니었네요."),
(L, "Non, finalement non. À samedi, Antoine. Au revoir, Gaston.", "네, 결국은 아니었어요. 토요일에 봐요, 앙투안. 안녕히 계세요, 가스통."),
(None, "Elle sort. Antoine reste immobile, un verre à la main.", "그녀가 나간다. 앙투안은 손에 잔을 든 채 꼼짝 않고 서 있다."),
(G, "Tu peux respirer, mon garçon. Elle est partie.", "숨 쉬어도 돼, 얘야. 갔어."),
(A, "Je respire très bien, merci.", "아주 잘 쉬고 있어, 고마워."),
(G, "Vraiment ? Alors pourquoi tu tiens ton verre à l'envers ?", "정말? 그럼 왜 잔을 거꾸로 들고 있는데?"),
]

VOCAB = [
("A2","être en retard","늦다","« Je suis un peu en retard. » ↔ être à l'heure(정시에 도착하다), être en avance(일찍 도착하다)"),
("A2","tenir une promesse","약속을 지키다","tenir (지키다) + 약속·말. « Je tiens toujours mes promesses. »"),
("A2","du / de la / des (부분관사)","어느 정도의 양(셀 수 없는 것)","« Je mange du fromage, de la salade, des légumes. » 음식·음료의 '일부'를 가리킬 때"),
("A2","un goût / des goûts","맛, 취향","« Des goûts et des couleurs, on ne discute pas. » 복수형은 '취향'"),
("A2","je préfère A à B","나는 B보다 A를 선호한다","« Je préfère le premier. »"),
("A2","Il y a un piège / Je sens le piège","함정이 있다 / 함정의 냄새가 나다","sentir (냄새 맡다·느끼다)를 비유적으로 사용"),
("A2","À la bonne santé de…","~의 건강을 위해 (건배)","건배 문구. « À notre première vraie dégustation ! » 처럼 목적어를 바꿔 쓴다"),
("B1","Je trouve que… / À mon avis… / Pour moi…","나는 ~라고 생각한다","의견 표현 3종 세트. 뒤에 직설법이 온다"),
("B1","sentir + 향 (ça sent le citron)","~ 냄새가 나다","« Ça sent le citron. » (정관사 + 명사). 비인칭 ça + sentir"),
("B1","en reprendre","한 번 더 마시다·먹다","« J'ai envie d'en reprendre. » en = 그 음료의 추가분"),
("B1","être en train de + 동사원형","~하는 중이다","« Vous êtes en train de découvrir un monde entier. »"),
("B1","faire le bilan","결산하다, 정리해 보다","시음 후 정리, 하루 정리 등에 사용"),
("B1","comme on dit","사람들이 말하듯","속담·관용구를 인용할 때 붙이는 표현"),
("B2","acide / frais / vif / rond / corsé","산도가 높은 / 상큼한 / 활기찬 / 둥글고 부드러운 / 바디감 있는","와인 맛 표현. rond = 날카롭지 않고 균형 잡힘, corsé = 몸체가 큼"),
("B2","puissant(e) / avoir du corps","강한, 묵직한 / 바디감이 있다","« Un vin puissant est un vin qui a du caractère. »"),
("B2","un arôme de… / une note fumée","~의 향 / 스모키한 노트","« des arômes de framboise et de poivron vert », « des notes fumées »"),
("B2","une divergence","의견 차이","« Voilà une première divergence. » 점잖게 의견 충돌을 말할 때"),
("B2","un compromis","절충안","« C'est un bon compromis. »"),
("B2","sous-estimer / un débutant","과소평가하다 / 초보자","« Il ne faut jamais sous-estimer un débutant motivé. »"),
("B2","vexé(e)","기분이 상한, 자존심이 상한","« Vous avez l'air vexé. » 가볍게 놀릴 때 자주 사용"),
("C1","Chacun voit midi à sa porte.","각자 자기 입장에서 본다(자기 기준으로 판단한다)","속담. 문자 그대로는 '각자 자기 문 앞에서 정오를 본다'"),
("C1","Des goûts et des couleurs, on ne discute pas.","취향은 논쟁할 대상이 아니다","프랑스에서 가장 흔한 속담 중 하나. 취향 차이를 인정할 때"),
("C1","neutre comme la Suisse","스위스처럼 중립인","비교 관용구. 정치적 중립국 스위스에서 온 표현"),
("C1","un millésime","빈티지, 포도 수확 연도","와인의 생산연도. « On apprend de chaque millésime. »"),
("C1","avoir le nez d'un professionnel","전문가 같은 후각을 갖다","nez = 향을 잘 맡는 능력. 와인 평가에 쓰는 칭찬"),
]

GRAM = [
("A2","부분관사 du / de la / de l' / des",
 "셀 수 없는 것(음식·음료·감정)의 '일부'를 말할 때: « Je mange du fromage », « Je bois du café », « Beaucoup de pâtes, de la salade, des légumes ». 부정문과 양 부사 뒤에서는 de로 바뀐다: « Je ne bois pas de café après seize heures », « beaucoup de pâtes ». 반대로 좋아하는 것·일반 개념은 정관사: « J'adore le fromage »."),
("A2","aimer · adorer · préférer · détester",
 "좋아함의 정도를 나타내는 동사. 정관사와 함께 일반 개념을 말한다: « J'adore le fromage », « Je préfère le premier ». 비교: « Je préfère A à B » (B보다 A). 동사 뒤에 동사원형이 오면 « J'aime boire du café »."),
("B1","의견 표현과 직설법 vs 접속법",
 "« Je trouve que c'est très frais. », « À mon avis, c'est un peu trop acide. », « Pour moi, c'est justement ce qui est agréable ! » 모두 뒤에 직설법. 단 부정·의문에서 의견 동사는 접속법이 올 수 있다(상급): « Je ne pense pas que ce soit trop acide »."),
("B1","비교급·최상급 plus / moins / aussi … que",
 "« Le Muscadet est plus vivant, plus gai. », « C'est plus rond que le Chinon, plus chaud. », « Ce n'est pas aussi terrible que ça en a l'air. » plus de / moins de + 명사: « Il a plus de profondeur », « plus de corps »."),
("B1","대명동사와 현재진행",
 "« Vous vous souvenez du poivre ? » (se souvenir de), « Je me souviens de tout ce qui est étrange. » 대명사 재귀 어순은 주어 + 재귀대명사 + 동사. 진행 표현: « Vous êtes en train de découvrir un monde entier. »"),
("B2","조건 없는 단순 명령·권유: 명령법과 il faut",
 "« Goûtez, mademoiselle. Sentez d'abord, puis buvez une petite gorgée. » (vous 명령법) / « Il ne faut jamais sous-estimer un débutant motivé. » (il faut의 부정: ~해서는 안 된다) / « Il faut la pratiquer pour la parler. » (필요)."),
("B2","직접·간접 목적어 대명사와 en의 결합",
 "« J'ai envie d'en reprendre. » (en = 그 와인의 추가분), « Je vous réserve les deux plus belles places. » (vous = 간접목적어), « Je ne l'oublie pas. » (l' = 직접목적어). 대명사는 변하는 동사 바로 앞에, 부정문에서는 ne와 동사 사이에 놓인다."),
("C1","si의 용법 확장: 대답의 « Si ! »",
 "« Et personne ne vous a demandé ce que cela voulait dire ? — Si ! » 부정 의문문에 긍정으로 반박할 때는 oui가 아니라 si를 쓴다. 대화에서 자주 나오는 함정이므로 주의."),
]

CULTURE = [
("뮈스카데·시농·생조제프",
 "뮈스카데(Muscadet)는 루아르 하구 지방의 드라이 화이트로, 굴·해산물과 잘 어울린다. 시농(Chinon)은 카베르네 프랑으로 만든 가벼운 루아르 레드. 생조제프(Saint-Joseph)는 론 북부의 시라 품종 레드로 향신료·훈연 향이 특징이다."),
("«Sur lie» 란?",
 "발효가 끝난 뒤 효모 찌꺼기(lie) 위에서 숙성시킨 와인에 붙는 표기. 입 안에서 부드럽고 약간 빵 같은 풍미를 더한다. 뮈스카데 쉬르 리가 대표적이다."),
("프랑스의 와인숍 시음회",
 "무료 시음회는 단골을 만드는 가장 흔한 방법이다. 시음 순서는 보통 화이트·가벼운 레드·묵직한 레드 순이며, 먼저 향(nez)을 맡고 한 모금 머금어 입 안(bouche)과 끝맛(finale)을 확인한다."),
]

META = dict(part=1, ep=2, part_label="제1부 첫 잔 · Premier verre", title_fr="Le conseil de Gaston", title_ko="가스통의 조언",
 place="파리 몽마르트르, La Cave des Abbesses · 4월 초 목요일 18시 10분 (목요일 시음회)",
 chars="Léa Fontaine (레아) · Antoine Delcourt (앙투안) · Gaston Roussel (가스통)",
 wine="Muscadet sur lie (루아르 화이트), Chinon (루아르 레드), Saint-Joseph (론 레드)",
 focus="부분관사, aimer/préférer, 의견 표현(je trouve que…), 비교급, 대명동사, 와인 맛 어휘 입문",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제3화 « Rouge ou blanc ? » : 토요일 오후, 가스통이 준비한 ‘레드 대 화이트’ 대결. 레아가 처음으로 자신의 취향을 정하는 순간.")
