# -*- coding: utf-8 -*-
G, L, A, P = "Gaston", "Léa", "Antoine", "Mme Pichon"
D = [
(None, "Samedi, 15 h 30. La boutique est pleine de monde. Sur le comptoir, deux bouteilles enveloppées de papier kraft, marquées « A » et « B ». Léa arrive, un peu essoufflée.", "토요일 오후 3시 30분. 가게는 사람들로 가득하다. 카운터 위에는 크라프트지에 싸인 병 두 개가 놓여 있고 'A'와 'B'가 적혀 있다. 레아가 조금 숨을 헐떡이며 도착한다."),
(G, "Ah, voilà notre championne du vin blanc ! Entrez, vous êtes juste à l'heure.", "아, 우리 화이트 와인 챔피언이 오셨군! 들어오세요, 딱 맞춰 오셨어요."),
(L, "Bonjour, Gaston. Il y a énormément de monde ! Je ne savais pas que les dégustations avaient autant de succès.", "안녕하세요, 가스통. 사람이 정말 많네요! 시음회가 이렇게 인기가 있는 줄 몰랐어요."),
(G, "Le samedi, c'est le grand rendez-vous. Madame Pichon, je vous présente Léa, la nouvelle recrue.", "토요일이 큰 모임이죠. 피숑 부인, 새로 오신 레아 양을 소개할게요."),
(P, "Enchantée, ma petite. Gaston m'a parlé de vous : « une jeune femme qui n'y connaît rien mais qui a le nez ».", "반가워요, 아가씨. 가스통이 당신 얘기를 했어요. '아무것도 모르지만 코는 좋은 젊은 아가씨'라고."),
(L, "Il a dit ça ? C'est à moitié flatteur et à moitié insultant.", "그렇게 말했어요? 반은 칭찬이고 반은 모욕이네요."),
(P, "C'est exactement le style de Gaston.", "딱 가스통 스타일이죠."),
(A, "Bonjour, Léa. Je suis content que vous soyez venue.", "안녕하세요, 레아. 와 주셔서 기뻐요."),
(L, "Bonjour, Antoine. Je l'ai promis, non ? Alors, vous êtes prêt à perdre ?", "안녕하세요, 앙투안. 제가 약속했잖아요? 그래서 질 준비는 되셨어요?"),
(A, "Je suis prêt à gagner, plutôt. Je défends le rouge, je vous le rappelle.", "이길 준비가 되어 있다고 해야죠. 저는 레드를 맡았다는 걸 상기시켜 드릴게요."),
(G, "Silence, s'il vous plaît ! Voici les règles du duel. Chaque camp a deux minutes pour défendre sa couleur.", "조용히 해 주세요! 대결 규칙을 설명하겠습니다. 각 진영은 자기 색깔을 변호할 시간이 2분씩 있습니다."),
(G, "Ensuite, tout le monde goûte les deux vins, et vous votez avec un bouchon dans l'un des deux bocaux.", "그다음 모두가 두 와인을 맛보고, 두 개의 유리병 중 하나에 코르크 마개를 넣어 투표합니다."),
(P, "Et si c'est l'égalité, Gaston ?", "만약 동점이면요, 가스통?"),
(G, "Dans ce cas, c'est vous qui décidez, madame Pichon. Vous êtes la sagesse de cette boutique.", "그럴 땐 피숑 부인이 결정하세요. 이 가게의 지혜이시니까요."),
(P, "Hmm. Je suis surtout la plus ancienne cliente, c'est différent.", "흠. 저는 그냥 제일 오래된 단골일 뿐이에요, 그건 달라요."),
(G, "Léa, vous commencez. Vous défendez le vin blanc. La parole est à vous.", "레아 양, 먼저 시작하세요. 화이트 와인을 변호하세요. 발언권은 당신에게 있습니다."),
(L, "Euh... Bonjour à tous. Je ne suis pas une experte, je dois le dire d'emblée.", "음... 여러분 안녕하세요. 저는 전문가가 아니라는 걸 먼저 말씀드려야겠어요."),
(L, "Mais je crois que le vin blanc est le plus accessible. Il est frais, il est léger, il est joyeux.", "하지만 화이트 와인이 가장 접근하기 쉽다고 생각해요. 상큼하고, 가볍고, 즐거워요."),
(L, "Un vin blanc, c'est comme une journée de printemps : une belle lumière, une bonne humeur, et pas de prise de tête.", "화이트 와인은 봄날 같아요. 아름다운 빛, 좋은 기분, 그리고 머리 아플 일이 없죠."),
(P, "Une prise de tête ? Dans un verre de vin ?", "머리 아플 일이요? 와인 잔 속에서요?"),
(L, "Oui, madame. Le rouge, parfois, on dirait qu'il faut passer un examen avant de le boire.", "네, 부인. 레드 와인은 가끔 마시기 전에 시험을 봐야 할 것 같아요."),
(A, "Un examen ? Mais le rouge, c'est une conversation, pas un examen !", "시험이라니요? 레드 와인은 시험이 아니라 대화예요!"),
(G, "Antoine, ce n'est pas encore ton tour. Léa, continuez.", "앙투안, 아직 네 차례 아니야. 레아 양, 계속하세요."),
(L, "Merci. Un vin blanc se boit à l'apéritif, avec les amis, au soleil, sur une terrasse. Un vin rouge se boit... sérieusement.", "감사해요. 화이트 와인은 아페리티프로, 친구들과, 햇볕 아래 테라스에서 마시죠. 레드 와인은... 진지하게 마시고요."),
(L, "Voilà mon argument : le blanc, c'est la liberté. Merci.", "그게 제 논거예요. 화이트는 자유예요. 감사합니다."),
(None, "Applaudissements. Madame Pichon applaudit plus fort que les autres.", "박수가 터진다. 피숑 부인이 누구보다 크게 박수를 친다."),
(G, "Très bien ! Antoine, à toi. Deux minutes, pas une de plus.", "아주 좋아요! 앙투안, 네 차례야. 2분, 1초도 더 안 돼."),
(A, "Mesdames, messieurs, je suis professeur d'histoire, alors je commence par l'histoire.", "신사 숙녀 여러분, 저는 역사 교사라서 역사부터 시작하겠습니다."),
(A, "Le vin rouge existe depuis plus de deux mille ans en France. Les Romains en buvaient déjà. Les moines l'ont perfectionné.", "레드 와인은 프랑스에 이천 년도 넘게 존재해 왔습니다. 로마인들도 이미 마셨죠. 수도사들이 그걸 완성했고요."),
(A, "Un vin rouge, ce n'est pas seulement une boisson, c'est un voyage dans le temps, dans la terre et dans l'âme.", "레드 와인은 단순한 음료가 아니라 시간과 땅과 영혼 속으로 떠나는 여행입니다."),
(L, "(à voix basse) Il a préparé ça pendant deux jours, c'est évident.", "(작은 목소리로) 이틀 동안 준비한 게 분명해요."),
(P, "Chut, ma petite. C'est beau, ce qu'il dit.", "쉿, 아가씨. 저 사람 말이 참 아름다워요."),
(A, "Le rouge a des tanins, de la structure, de la profondeur. Il évolue dans le verre, il change à chaque minute.", "레드는 탄닌과 구조와 깊이를 가지고 있습니다. 잔 속에서 변하고, 매 분 달라집니다."),
(A, "Un vin blanc, c'est agréable. Un vin rouge, c'est inoubliable. Voilà ma conclusion. Merci.", "화이트는 즐겁습니다. 레드는 잊을 수 없습니다. 이것이 제 결론입니다. 감사합니다."),
(None, "Nouveaux applaudissements. Gaston lève les bras pour demander le silence.", "다시 박수가 터진다. 가스통이 두 팔을 들어 조용히 해 달라고 한다."),
(G, "Bravo à tous les deux ! Passons à la dégustation. Voici le vin A, puis le vin B. Léa, Antoine, vous êtes les premiers servis.", "두 사람 모두 브라보! 시음으로 넘어갑시다. 와인 A, 그다음 와인 B입니다. 레아, 앙투안, 두 사람이 먼저 받으세요."),
(L, "Je tiens le verre comme ça, n'est-ce pas ?", "잔을 이렇게 들면 되죠, 그렇죠?"),
(G, "Non, non, non ! Pas par le bol. Tenez-le par le pied, sinon vous réchauffez le vin avec votre main.", "아니, 아니, 아니에요! 잔 몸통을 잡으면 안 돼요. 다리를 잡으세요, 안 그러면 손의 열로 와인이 데워져요."),
(L, "Le pied ? On dirait qu'on parle d'un animal.", "다리요? 무슨 동물 얘기하는 것 같네요."),
(A, "C'est la tige, en français correct. Mais tout le monde dit « le pied ».", "정확한 프랑스어로는 줄기(tige)예요. 하지만 다들 '다리'라고 해요."),
(L, "Donc je tiens le verre par le pied, et je fais tourner le vin, comme dans les films ?", "그럼 잔을 다리로 잡고, 영화처럼 와인을 돌리면 되나요?"),
(G, "Exactement. Doucement, par petits cercles.", "정확해요. 천천히, 작은 원을 그리며요."),
(None, "Léa fait tourner son verre un peu trop vigoureusement. Le vin déborde et éclabousse la manche d'Antoine.", "레아가 잔을 너무 세게 돌린다. 와인이 넘쳐 앙투안의 소매에 튄다."),
(L, "Oh non ! Je suis vraiment désolée, Antoine ! Votre chemise !", "아, 안 돼! 정말 죄송해요, 앙투안! 셔츠가!"),
(A, "Ce n'est pas grave. C'est du blanc, ça ne tache presque pas. Si c'était du rouge, ce serait une catastrophe.", "괜찮아요. 화이트라서 거의 얼룩이 안 져요. 레드였으면 재앙이었겠죠."),
(P, "Un point pour le blanc, alors ! Il tache moins.", "그럼 화이트가 1점이네요! 얼룩이 덜 지니까."),
(A, "Madame Pichon, vous êtes impitoyable.", "피숑 부인, 너무 가차 없으세요."),
(L, "Je suis tellement gênée. Je fais toujours des choses pareilles.", "너무 창피해요. 전 늘 이런 일을 해요."),
(A, "Léa, ce n'est vraiment rien. Buvez, goûtez, ne pensez plus à ma manche.", "레아, 정말 아무것도 아니에요. 마시고 맛보세요, 제 소매는 잊으세요."),
(L, "D'accord. (Elle goûte le vin A.) Oh. C'est très fin. C'est sec, minéral, un peu salé ?", "알겠어요. (그녀가 와인 A를 맛본다.) 아. 아주 섬세해요. 드라이하고 미네랄 느낌이 있고 약간 짭짤한가요?"),
(G, "Bravo ! Ça, c'est un Chablis premier cru. Le sol de calcaire donne cette minéralité.", "브라보! 그건 샤블리 프르미에 크뤼예요. 석회질 토양이 그런 미네랄 풍미를 줍니다."),
(A, "Moi, je trouve qu'il est un peu trop sec. Je préfère les vins plus ronds.", "저는 좀 너무 드라이하다고 생각해요. 더 둥글고 부드러운 와인이 좋아요."),
(L, "Ronds ? Les vins ont des formes, maintenant ?", "둥글다고요? 이제 와인에 모양까지 있어요?"),
(A, "C'est une façon de parler. Un vin rond, c'est un vin doux, sans angles, sans agressivité.", "표현일 뿐이에요. 둥근 와인은 부드럽고 각이 없고 공격적이지 않은 와인이에요."),
(L, "Alors le Chablis est un vin carré ?", "그럼 샤블리는 네모난 와인인가요?"),
(A, "Disons qu'il est droit, vif et précis. Pas carré.", "곧고 활기차고 정확하다고 해 두죠. 네모는 아니에요."),
(P, "C'est charmant, ces deux-là. Ils se chamaillent déjà comme un vieux couple.", "이 둘 참 귀엽네. 벌써 오래된 부부처럼 티격태격하네."),
(G, "Maintenant, le vin B. Léa, vous aimez les cerises, vous m'avez dit. Alors sentez celui-là.", "이제 와인 B예요. 레아 양, 체리를 좋아한다고 했죠. 그럼 이걸 맡아 보세요."),
(L, "Ça sent la cerise, oui. Et une odeur de sous-bois, comme après la pluie.", "체리 향이 나네요, 네. 그리고 비 온 뒤 같은 숲속 땅 냄새도 나요."),
(A, "Un pinot noir de Bourgogne. Des Hautes-Côtes de Nuits, je crois.", "부르고뉴의 피노 누아예요. 오트 코트 드 뉘일 것 같아요."),
(G, "Antoine, je ne t'ai pas encore donné la réponse !", "앙투안, 아직 정답을 알려 주지도 않았는데!"),
(A, "Le nez ne ment pas. Léa, goûtez.", "코는 거짓말을 안 해요. 레아, 맛보세요."),
(L, "(Elle goûte.) Oh... C'est tendre. C'est comme... un pull en laine doux, un jour d'hiver.", "(맛본다.) 아... 부드러워요. 겨울날 입는 보드라운 털 스웨터 같아요."),
(A, "Un pull en laine doux. C'est la plus belle description d'un pinot noir que j'aie jamais entendue.", "보드라운 털 스웨터. 제가 들어 본 피노 누아에 대한 가장 아름다운 묘사예요."),
(L, "Vraiment ? Je pensais que vous alliez vous moquer de moi.", "정말요? 놀릴 줄 알았어요."),
(A, "Je ne me moque jamais de quelqu'un qui trouve les bons mots.", "좋은 말을 찾아내는 사람은 절대 놀리지 않아요."),
(L, "Alors je dois vous avouer quelque chose, Antoine.", "그럼 앙투안, 고백할 게 하나 있어요."),
(A, "Je vous écoute.", "듣고 있어요."),
(L, "Quand j'étais petite, à Lyon, mon père buvait du vin tous les soirs. Il ne nous laissait jamais goûter.", "어릴 때 리옹에서 아버지가 매일 저녁 와인을 드셨어요. 우리에게는 절대 맛보게 하지 않으셨죠."),
(L, "Je crois qu'il avait peur qu'on ne comprenne pas, qu'on gâche quelque chose de précieux.", "아마 우리가 이해하지 못하고 소중한 걸 망칠까 봐 걱정하셨던 것 같아요."),
(L, "Du coup, j'ai grandi avec l'idée que le vin était réservé aux gens qui savent. Et moi, je ne sais rien.", "그래서 와인은 아는 사람들만의 것이라는 생각을 하며 자랐어요. 그런데 저는 아무것도 모르고요."),
(A, "Ignorer n'est pas une faute, Léa. C'est un début.", "모르는 건 잘못이 아니에요, 레아. 시작일 뿐이에요."),
(L, "Vous dites ça pour être gentil.", "친절하게 보이려고 그렇게 말씀하시는 거죠."),
(A, "Non. Je le dis parce que c'est vrai. Personne ne naît connaisseur. Moi-même, j'ai bu mon premier verre à douze ans, et j'ai trouvé ça horrible.", "아니에요. 사실이라서 말하는 거예요. 누구도 애호가로 태어나지 않아요. 저조차 열두 살에 첫 잔을 마셨는데 끔찍하다고 느꼈어요."),
(L, "Horrible ? Vous, le fils de vigneron ?", "끔찍했다고요? 와인 농가 아들인 당신이요?"),
(A, "C'était un vin rouge très tannique, très âpre. J'ai craché dans l'évier. Mon père ne m'a jamais pardonné.", "아주 떫고 거친 레드 와인이었어요. 싱크대에 뱉었죠. 아버지는 그걸 절대 용서하지 않으셨어요."),
(L, "(rit) Je ne savais pas que vous aviez commencé comme ça.", "(웃으며) 그렇게 시작하셨는지 몰랐어요."),
(A, "Il n'y a pas de honte à commencer par un échec. Moi, c'est avec un échec que j'ai appris à aimer le vin.", "실패로 시작하는 건 부끄러운 일이 아니에요. 저는 실패를 통해 와인을 좋아하게 됐어요."),
(G, "Hé, vous deux, les confidences, c'est pour après ! On vote !", "이봐요 두 분, 속마음 얘기는 나중에! 투표합시다!"),
(None, "Les clients déposent leurs bouchons dans les bocaux. Gaston compte à voix haute.", "손님들이 병에 코르크 마개를 넣는다. 가스통이 소리 내어 센다."),
(G, "Voilà. Pour le blanc : douze bouchons. Pour le rouge : douze bouchons. Égalité parfaite !", "자, 화이트가 열두 표. 레드가 열두 표. 완벽한 동점이에요!"),
(P, "Évidemment. Deux bons orateurs, deux bons vins.", "당연하죠. 훌륭한 연설가 둘에 훌륭한 와인 둘이니."),
(G, "Madame Pichon, à vous de trancher.", "피숑 부인, 판결을 내려 주세요."),
(P, "Je vote pour... les deux. Le blanc le matin, le rouge le soir. Et les deux jeunes gens ensemble, quand l'heure sera venue.", "저는... 둘 다에 투표해요. 아침엔 화이트, 저녁엔 레드. 그리고 두 젊은이는 때가 되면 함께."),
(L, "Madame Pichon, vous êtes incorrigible !", "피숑 부인, 못 말리세요!"),
(P, "À mon âge, on a le droit de dire ce qu'on pense. C'est le seul avantage de la vieillesse.", "제 나이엔 생각한 걸 말할 권리가 있어요. 나이 듦의 유일한 장점이죠."),
(G, "Bon, personne n'a gagné, donc tout le monde a gagné. C'est la tradition de la maison.", "좋아요, 아무도 이기지 못했으니 모두가 이긴 거예요. 우리 가게의 전통이죠."),
(A, "Je préfère les traditions où je perds moins que ça.", "저는 제가 이렇게까지 안 지는 전통이 더 좋긴 하네요."),
(L, "Vous n'avez pas perdu, Antoine. Moi non plus. On a juste... fait un match nul.", "지지 않았어요, 앙투안. 저도 안 졌고요. 그냥... 무승부를 한 거죠."),
(A, "Un match nul entre un rouge et un blanc, c'est presque un rosé.", "레드와 화이트의 무승부라면 거의 로제죠."),
(L, "Un rosé ! Voilà une couleur que personne n'a défendue.", "로제! 아무도 변호하지 않은 색깔이네요."),
(G, "Ah non, pas de rosé dans ma boutique avant le mois de mai. C'est la règle numéro un.", "아니, 5월 전에는 우리 가게에 로제는 없어요. 제1 규칙이에요."),
(A, "Il y a donc des règles, ici ? Je croyais que tu faisais tout au hasard.", "여기 규칙이 있었어? 난 네가 다 아무렇게나 하는 줄 알았는데."),
(G, "Au hasard ? J'ai trente-quatre ans de métier, mon garçon. Chaque hasard est calculé.", "아무렇게나라니? 나는 34년 경력이야, 얘야. 모든 우연은 계산된 거지."),
(L, "Il est tard, je crois. Les gens commencent à partir.", "시간이 늦었나 봐요. 사람들이 가기 시작해요."),
(A, "Léa, si vous voulez... il y a un petit café pas loin. Je peux vous offrir un vrai café, sans vin.", "레아, 괜찮으시다면... 가까이에 작은 카페가 있어요. 와인 없는 진짜 커피를 대접할 수 있어요."),
(L, "Un café à seize heures trente ? Je ne bois pas de café après seize heures, vous vous souvenez ?", "오후 4시 30분에 커피요? 저는 4시 이후엔 커피를 안 마셔요, 기억하시죠?"),
(A, "Alors un chocolat chaud ?", "그럼 핫초콜릿은요?"),
(L, "Je dois rentrer. J'ai un projet à finir. Mais... une prochaine fois, peut-être.", "돌아가야 해요. 마무리할 프로젝트가 있어서요. 하지만... 다음에요, 아마도."),
(G, "« Peut-être », encore ! Elle dit toujours « peut-être », celle-là.", "'아마도', 또! 이 아가씨는 항상 '아마도'라고 하네."),
(L, "Parce que « peut-être » est la réponse la plus honnête que je connaisse.", "'아마도'가 내가 아는 가장 솔직한 대답이니까요."),
(A, "Alors j'attendrai un « peut-être » plus précis.", "그럼 더 정확한 '아마도'를 기다릴게요."),
(L, "Au revoir, Antoine. Au revoir, madame Pichon. Au revoir, Gaston.", "안녕히 가세요, 앙투안. 안녕히 계세요, 피숑 부인. 안녕히 계세요, 가스통."),
(P, "Au revoir, ma petite. À jeudi, n'est-ce pas ?", "잘 가요, 아가씨. 목요일에 보죠, 그렇죠?"),
(L, "À jeudi, madame. Cette fois, ce sera un « oui ».", "목요일에 뵐게요, 부인. 이번엔 '네'일 거예요."),
]

VOCAB = [
("A2","être prêt(e) à + 동사원형","~할 준비가 되다","« Vous êtes prêt à perdre ? » / 형용사는 주어의 성·수에 일치"),
("A2","enveloppé(e) / un papier kraft","포장된 / 크라프트지","과거분사가 형용사처럼 쓰임: « deux bouteilles enveloppées »"),
("A2","désolé(e) / ce n'est pas grave","죄송한 / 괜찮아요","사과와 응답의 기본 세트"),
("A2","c'est du blanc / c'est du rouge","화이트(레드) 와인이에요","와인 종류에 부분관사: « C'est du blanc, ça ne tache presque pas. »"),
("A2","goûter / sentir","맛보다 / 냄새 맡다","시음의 기본 동사 두 개. « Goûtez, sentez d'abord. »"),
("B1","la parole est à vous","발언권은 당신에게 있다","회의·토론에서 발언 순서를 넘길 때"),
("B1","une prise de tête","골치 아픈 일, 머리 쓰는 일","구어. « pas de prise de tête » = 복잡하게 굴지 마"),
("B1","d'emblée","처음부터, 즉각적으로","« Je dois le dire d'emblée. » 문어에서도 쓰임"),
("B1","tenir le verre par le pied","잔을 다리(스템)로 잡다","시음 매너. 정확한 용어는 la tige, 일상에서는 le pied"),
("B1","se chamailler","티격태격하다","« Ils se chamaillent comme un vieux couple. » 귀여운 말다툼"),
("B1","un match nul","무승부","스포츠 외에도 비유로 사용"),
("B1","trancher","결정하다, 판가름하다","« À vous de trancher. » 의견이 갈릴 때 결정을 맡기는 표현"),
("B2","accessible / léger / joyeux","접근하기 쉬운 / 가벼운 / 즐거운","화이트 와인을 홍보할 때 쓴 형용사. 성수 변화에 주의"),
("B2","minéral(e) / sec / sèche / vif / vive","미네랄 느낌의 / 드라이한 / 활기찬","와인 형용사의 여성형: sec→sèche, vif→vive, doux→douce, frais→fraîche"),
("B2","rond / tendre / tannique / âpre","둥근 / 부드러운 / 떫은 / 거친","레드 와인의 질감 표현. âpre = 입 안이 거칠고 수렴되는 느낌"),
("B2","un sous-bois / un sol de calcaire","숲속 땅 / 석회질 토양","향과 테루아 설명에 자주 나오는 표현"),
("B2","éclabousser / tacher","(액체를) 튀기다 / 얼룩지게 하다","« Le vin éclabousse la manche. » / « Ça ne tache presque pas. »"),
("B2","gêné(e)","난처한, 어색한","« Je suis tellement gênée. » 부끄러움·민망함"),
("B2","se moquer de","놀리다, 조롱하다","« Je ne me moque jamais de quelqu'un qui trouve les bons mots. »"),
("B2","un orateur / une oratrice","연설가","토론·연설에서 쓰는 명사. 여성형은 -trice"),
("C1","C'est la plus belle description… que j'aie jamais entendue.","내가 들어 본 가장 아름다운 묘사다","최상급 + que + 접속법 (경험·한정 표현). 상급 문법 포인트"),
("C1","Il n'y a pas de honte à…","~하는 건 부끄러운 일이 아니다","위로할 때 쓰는 격조 있는 표현"),
("C1","tous les deux (둘 다) / les deux jeunes gens","두 사람 모두 / 두 젊은이","jeunes gens (남녀 모두 가리킴) 은 문어체·약간 구식"),
("C1","à mon âge, on a le droit de…","내 나이엔 ~할 권리가 있다","나이 든 인물이 쓰는 관용적 어조"),
]

GRAM = [
("A2","형용사의 성·수 일치",
 "프랑스어 형용사는 명사의 성과 수에 맞춰 변한다: un vin blanc / une bouteille blanche / des vins blancs; « un vin sec / une cuvée sèche », « vif / vive », « doux / douce », « frais / fraîche ». 과거분사도 형용사처럼 일치한다: « deux bouteilles enveloppées »."),
("A2","형용사의 위치",
 "대부분 명사 뒤: un vin rouge, un vin minéral. 짧고 흔한 형용사(BAGS: Beauté·Âge·Grandeur·Santé)는 앞: « une belle lumière », « un bon vin », « un petit café ». 앞뒤 위치에 따라 뜻이 바뀌는 형용사도 있다(상급)."),
("A2","지시형용사 ce / cet / cette / ces",
 "« Ce vin », « cet arôme » (모음 앞 남성), « cette bouteille », « ces deux-là ». 가까운 대상을 가리킬 때 사용하며 -ci / -là를 붙여 구분할 수 있다."),
("B1","c'est vs il est",
 "« C'est du blanc » / « C'est très fin » / « C'est comme un pull en laine » : c'est + 관사·명사 또는 평가. « Il est frais, il est léger » : 앞에 나온 특정 명사(vin)를 받아 형용사로 설명. 일반 평가는 c'est, 특정 대상 서술은 il/elle est."),
("B1","대명동사의 상호적 의미",
 "« Ils se chamaillent » (서로 다툰다), « Ils se disputent », « On se retrouve ». 주어가 복수일 때 se가 '서로'의 의미를 가질 수 있다."),
("B2","접속법: 감정·평가 뒤 / 최상급 뒤",
 "« Je suis content que vous soyez venue. » (감정 + que + 접속법) / « la plus belle description que j'aie jamais entendue » (최상급 + que + 접속법 과거). 현재 접속법 être: sois, sois, soit, soyons, soyez, soient."),
("B2","조건법 + 과거 조건 문장",
 "« Si c'était du rouge, ce serait une catastrophe. » si + 반과거 → 조건법 현재(현재 사실의 반대). « Si je savais, je vous le dirais. » 가정의 기본 틀."),
("C1","강조 구문과 구어 어순",
 "« Voilà mon argument : le blanc, c'est la liberté. » / « Un vin blanc, c'est comme une journée de printemps. » c'est를 사용해 주제를 먼저 놓고 설명하는 구어 강조 구조. 전통 문어 어순과 비교하며 익히면 좋다."),
]

CULTURE = [
("Chablis와 부르고뉴 피노 누아",
 "샤블리(Chablis)는 부르고뉴 최북단의 샤르도네 화이트로, 키메리지안 석회질 토양 덕에 미네랄 풍미가 두드러진다. Hautes-Côtes de Nuits의 피노 누아는 체리·숲속 향과 부드러운 질감이 특징이다."),
("잔 잡는 법과 시음 매너",
 "잔은 몸통이 아니라 다리(tige)를 잡아 와인 온도를 유지한다. 흔히 « faire tourner le vin » 은 향을 열기 위한 동작이며, 잔의 1/3 이하로만 따라야 넘치지 않는다."),
("프랑스의 '로제 시즌'",
 "프랑스에서 로제(rosé)는 5~9월의 와인이다. 가스통의 '5월 전엔 로제 없음'은 농담이지만 실제로 로제 판매는 날씨가 풀리는 봄에 시작된다."),
]

META = dict(part=1, ep=3, part_label="제1부 첫 잔 · Premier verre", title_fr="Rouge ou blanc ?", title_ko="레드냐 화이트냐",
 place="La Cave des Abbesses · 4월 초 토요일 15시 30분 (레드 대 화이트 대결)",
 chars="Léa · Antoine · Gaston · Mme Pichon (피숑 부인, 70대 단골)",
 wine="Chablis premier cru (부르고뉴 화이트) · Hautes-Côtes de Nuits (피노 누아 레드)",
 focus="형용사 일치와 위치, 지시형용사, c'est vs il est, 와인 질감 어휘, 접속법 입문",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제4화 « Un petit budget » : 지갑이 가벼운 두 사람. 가격 이야기 끝에 같은 동네에 산다는 걸 알게 되고, 존댓말이 반말로 바뀐다.")
