# -*- coding: utf-8 -*-
G, L, A = "Gaston", "Léa", "Antoine"
D = [
(None, "Jeudi, 18 h. La boutique est calme. Gaston prépare la dégustation du soir. Antoine pose sur le comptoir une bouteille de Saumur-Champigny. Léa, arrivée la première, l'observe avec curiosité.", "목요일 오후 6시. 가게는 한산하다. 가스통이 저녁 시음회를 준비한다. 앙투안이 카운터에 소뮈르샹피니 한 병을 올려놓는다. 가장 먼저 도착한 레아가 호기심 어린 눈으로 그것을 살핀다."),
(L, "Salut, Antoine ! Tu es déjà là ?", "안녕, 앙투안! 벌써 와 있었어?"),
(A, "Salut, Léa. Oui, j'ai fini les cours plus tôt aujourd'hui. Les élèves sont partis en sortie scolaire.", "안녕, 레아. 응, 오늘은 수업이 일찍 끝났어. 학생들이 현장 학습을 갔거든."),
(L, "Et tu as apporté une bouteille ?", "그래서 와인 한 병 가져왔어?"),
(A, "Oui. C'est le Saumur-Champigny des Roches Blanches. Celui que Gaston m'a vendu il y a trois semaines.", "응. 로슈 블랑슈의 소뮈르샹피니야. 3주 전에 가스통이 나한테 팔았던 거."),
(L, "Je peux la regarder ? J'ai toujours été attirée par les étiquettes. C'est mon métier, après tout.", "봐도 돼? 난 늘 라벨에 끌렸어. 어쨌든 내 직업이니까."),
(A, "Bien sûr. Tiens. Tu sais lire une étiquette de vin ?", "물론이지. 자. 와인 라벨 읽을 줄 알아?"),
(L, "Je sais lire une étiquette. Mais je ne sais pas la comprendre. Ce n'est pas pareil.", "라벨을 읽을 줄은 알아. 하지만 이해는 못 해. 그건 달라."),
(A, "Alors on va commencer par le commencement. Qu'est-ce que tu vois d'abord ?", "그럼 처음부터 시작하자. 제일 먼저 뭐가 보여?"),
(L, "Un dessin de colline avec un vieux château. Et un nom écrit en lettres dorées : « Domaine des Roches Blanches ».", "성이 있는 언덕 그림이야. 그리고 금빛 글씨로 쓴 이름, '도멘 데 로슈 블랑슈'."),
(A, "Parfait. Ça, c'est le nom du producteur. En France, on commence souvent par là.", "좋아. 그게 생산자 이름이야. 프랑스에서는 보통 거기서부터 시작해."),
(L, "Et la typographie est très jolie. C'est un caractère à empattements, probablement un Garamond.", "그리고 서체가 아주 예뻐. 세리프체야, 아마 가라몽일 거야."),
(A, "Je ne sais pas ce que c'est, mais je te crois. C'est un vieux style, non ?", "그게 뭔지는 모르지만 믿을게. 오래된 스타일이지?"),
(L, "Du seizième siècle, oui. Claude Garamont, un graveur français. Voilà, tu vois, moi aussi j'ai de l'histoire à raconter.", "16세기 거야, 맞아. 프랑스 활자 조각가 클로드 가라몽. 봐, 나도 들려줄 역사가 있어."),
(A, "Et tu sais le dessiner, un Garamond ?", "그럼 가라몽체를 그릴 줄도 알아?"),
(L, "Je ne le dessine pas, je l'utilise. Mais je pourrais t'apprendre à distinguer un serif d'un sans serif en cinq minutes.", "그리는 건 아니고 써. 하지만 오 분 안에 세리프와 산세리프를 구분하는 법을 알려 줄 수 있어."),
(A, "Cinq minutes ? Moi, il m'a fallu dix ans pour distinguer un Chinon d'un Bourgueil.", "오 분이라고? 난 시농과 부르괴유를 구별하는 데 십 년 걸렸는데."),
(L, "Alors on échangera des leçons.", "그럼 우리 수업을 맞바꾸자."),
(A, "Ça me va. Une leçon de typographie contre une leçon d'étiquettes.", "좋아. 타이포그래피 수업과 라벨 수업을 교환하자."),
(A, "Impressionnant ! Bon, passons à la partie suivante. Là, en dessous : « Saumur-Champigny, Appellation d'Origine Contrôlée ».", "인상적이네! 자, 다음 부분으로 넘어가자. 여기 아래에 이렇게 있지. '소뮈르샹피니, 원산지 통제 명칭'."),
(L, "Appellation d'Origine Contrôlée... AOC. C'est comme un label de qualité ?", "원산지 통제 명칭... AOC. 품질 인증 같은 거야?"),
(A, "C'est mieux que ça. L'AOC garantit que le vin vient d'un endroit précis et qu'il a été fabriqué selon des règles strictes.", "그보다 더 나아. AOC는 와인이 정확한 지역에서 나왔고 엄격한 규칙에 따라 만들어졌음을 보증해."),
(L, "Quelles règles ?", "어떤 규칙?"),
(A, "Les cépages autorisés, le rendement maximum, la méthode de culture, le degré d'alcool minimum. Tout est écrit dans un cahier des charges.", "허용 품종, 최대 수확량, 재배 방법, 최소 알코올 도수. 모든 게 사양서에 적혀 있어."),
(L, "Un cahier des charges pour du vin ? Ça ressemble à un contrat commercial.", "와인에 사양서라니? 상업 계약서 같네."),
(A, "C'est exactement un contrat. Entre le vigneron et la terre, avec l'État comme témoin.", "정확히 계약이야. 와인 농부와 땅 사이의 계약이고 국가가 증인이지."),
(G, "Vous êtes en train de refaire mon cours, tous les deux ?", "둘이서 내 강의를 다시 하고 있는 거야?"),
(A, "Gaston, on commence à peine. Léa est une élève exceptionnelle.", "가스통, 이제 막 시작했어. 레아는 아주 뛰어난 학생이야."),
(G, "Alors continuez. Moi, je prépare les verres. Mais je vous écoute, je vous le garantis.", "그럼 계속해. 나는 잔을 준비할게. 하지만 다 듣고 있다고 장담하지."),
(L, "Et là, en bas : « 2019 ». C'est la date de naissance du vin ?", "그리고 아래에 '2019'가 있어. 와인의 생년월일이야?"),
(A, "À peu près. C'est le millésime, l'année de la récolte du raisin. Pas de la mise en bouteille.", "거의 그래. 포도를 수확한 해인 빈티지야. 병에 담은 해가 아니라."),
(L, "Donc un vin de 2019 a eu une année particulière, avec son climat et son soleil.", "그럼 2019년산 와인은 그해의 기후와 햇빛이 만든 특별한 해를 가졌다는 거네."),
(A, "Exactement. 2019, c'était une année chaude et sèche dans la Loire. Une très bonne année pour les rouges.", "맞아. 2019년은 루아르에서 덥고 건조한 해였어. 레드에는 아주 좋은 해였지."),
(L, "Tu t'en souviens ? Tu te rappelles le temps qu'il faisait il y a six ans ?", "기억나? 6년 전 날씨가 어땠는지 기억해?"),
(A, "Je m'en souviens très bien. Cet été-là, j'ai passé un mois chez mon père, à l'aider pour les vendanges.", "아주 잘 기억해. 그해 여름에 한 달 동안 아버지 집에서 수확을 도왔어."),
(L, "Tu as fait les vendanges ?", "수확을 했어?"),
(A, "Chaque année, de mes douze ans jusqu'à mes dix-huit ans. J'ai coupé du raisin du matin jusqu'au soir, avec un sécateur trop grand pour mes mains.", "열두 살부터 열여덟 살까지 매년. 내 손에 너무 큰 가위로 아침부터 저녁까지 포도를 땄어."),
(L, "Raconte-moi. Comment c'était ?", "얘기해 줘. 어땠어?"),
(A, "C'était dur. On se levait à cinq heures du matin. On travaillait jusqu'à la nuit. On avait mal au dos, aux mains, partout.", "힘들었어. 새벽 5시에 일어나서 밤까지 일했지. 등도 손도 온몸이 아팠어."),
(A, "Mais le soir, on mangeait tous ensemble, vingt personnes autour d'une grande table, dans la cour de la ferme. Et on chantait.", "하지만 저녁이면 모두 함께 먹었어. 농장 마당 큰 식탁에 스무 명이 둘러앉아서. 그리고 노래도 했지."),
(L, "Vous chantiez quoi ?", "무슨 노래를 불렀어?"),
(A, "De vieilles chansons que personne ne comprenait plus. Mon père commençait toujours, et tout le monde suivait.", "아무도 더 이상 뜻을 모르는 옛 노래들. 항상 아버지가 먼저 부르면 모두가 따라 불렀어."),
(L, "C'est beau. Moi, je n'ai jamais chanté à table. Chez nous, on parlait de la météo et du prix du pain.", "아름답다. 나는 식탁에서 노래해 본 적이 없어. 우리 집에선 날씨랑 빵값 얘기만 했거든."),
(A, "Le prix du pain, c'est un bon sujet aussi.", "빵값도 좋은 주제지."),
(L, "Au fait, ton père est venu dimanche, comme prévu ?", "그런데 아버님은 일요일에 예정대로 오셨어?"),
(A, "Oui. Il est resté deux jours. Il a dormi sur mon canapé et il a critiqué mon frigo.", "응. 이틀 머물렀어. 내 소파에서 자고 내 냉장고를 타박했지."),
(L, "Et il t'a demandé si tu allais reprendre le domaine ?", "그리고 농장을 물려받을 거냐고 물으셨어?"),
(A, "Évidemment. Trois fois. Et trois fois, j'ai répondu : « On verra. »", "당연하지. 세 번이나. 그리고 세 번 다 '두고 보자'고 대답했어."),
(L, "Revenons à l'étiquette. Qu'est-ce que c'est que : « Mis en bouteille au domaine » ?", "라벨로 돌아가자. '미 앙 부테유 오 도멘'이 뭐야?"),
(A, "Ça veut dire que le vigneron a mis le vin en bouteille lui-même, dans son propre domaine. Il n'a pas vendu son vin à un négociant.", "와인 농부가 자기 농장에서 직접 병에 담았다는 뜻이야. 유통업자에게 와인을 팔지 않았다는 거지."),
(L, "Ça change quelque chose ?", "그게 뭔가 달라져?"),
(A, "Beaucoup de choses. Le vigneron contrôle toute la chaîne, de la vigne jusqu'à la bouteille. Il est responsable de tout, y compris de ses erreurs.", "많이 달라. 와인 농부가 포도나무부터 병까지 전 과정을 통제해. 실수까지 포함해서 모든 걸 책임지는 거야."),
(L, "Comme un artiste qui signe son œuvre.", "작품에 서명하는 예술가처럼."),
(A, "Exactement comme ça.", "정확히 그런 거야."),
(L, "Et ces petites lignes, en bas, en tout petit ? « 13 % vol. », « 75 cl », « Contient des sulfites ».", "그리고 아래에 아주 작게 적힌 이 줄들은? '13 % vol.', '75 cl', '아황산염 함유'."),
(A, "Les mentions obligatoires. Le degré d'alcool, le volume de la bouteille, et l'avertissement sur les sulfites.", "필수 표시 사항이야. 알코올 도수, 병의 용량, 그리고 아황산염 경고."),
(L, "Les sulfites, ce sont les produits chimiques qui donnent mal à la tête ?", "아황산염은 머리를 아프게 하는 화학 물질 아니야?"),
(A, "C'est un malentendu courant. Les sulfites existent naturellement dans le raisin, et le vigneron en ajoute un peu pour conserver le vin.", "흔한 오해야. 아황산염은 포도에 자연적으로 있고 농부가 보존하려고 조금 더 넣는 거야."),
(A, "Le mal de tête vient plus souvent de l'alcool, de la déshydratation, ou de la troisième bouteille.", "두통은 대개 알코올, 탈수, 또는 세 번째 병 때문이야."),
(L, "(rit) La troisième bouteille. Je prends note.", "(웃음) 세 번째 병. 메모해 둘게."),
(G, "Je confirme. J'ai trente-quatre ans d'expérience sur le sujet.", "내가 확인해 줄게. 이 분야 경력이 34년이야."),
(L, "Au fait, Antoine, tu as dit le soir où on s'est rencontrés que le fils du vigneron était dans ta classe au collège.", "그나저나 앙투안, 우리가 처음 만난 날 그 와인 농부 아들이 중학교 때 네 반이었다고 했잖아."),
(A, "Julien. Julien Barbier. C'est lui qui a repris le domaine après son père.", "쥘리앵. 쥘리앵 바르비에. 아버지 뒤를 이어 농장을 맡은 친구야."),
(L, "Vous êtes toujours en contact ?", "아직도 연락해?"),
(A, "Pas assez. Je lui ai écrit deux fois cette année. Il m'a répondu une fois. C'est la vie.", "충분히는 아니야. 올해 두 번 편지를 썼고 한 번 답장이 왔어. 사는 게 그렇지."),
(L, "Qu'est-ce qu'il a changé, sur l'étiquette ?", "그 친구는 라벨에서 뭘 바꿨어?"),
(A, "Comment tu sais qu'il a changé quelque chose ?", "그가 뭔가 바꿨다는 걸 어떻게 알았어?"),
(L, "Parce que tu as regardé cette étiquette avec beaucoup de tendresse.", "네가 이 라벨을 아주 다정하게 쳐다봤거든."),
(A, "Tu es observatrice. Eh bien, oui. Avant, l'étiquette était plus classique, avec les armoiries. Julien a demandé à une illustratrice de dessiner la colline.", "관찰력이 좋네. 맞아. 예전엔 문장이 들어간 더 고전적인 라벨이었어. 쥘리앵이 일러스트레이터에게 언덕을 그려 달라고 했지."),
(L, "Elle a fait un beau travail. Le trait est délicat. Il y a de la texture, de la lumière.", "일러스트레이터가 일을 잘했네. 선이 섬세해. 질감도 있고 빛도 있어."),
(A, "Tu pourrais faire mieux ?", "넌 더 잘할 수 있어?"),
(L, "Je ne dis pas ça. Je dis qu'il y a un équilibre entre la tradition et la modernité. C'est difficile à trouver.", "그런 말이 아니야. 전통과 현대 사이에 균형이 있다는 거야. 찾기 어려운 거지."),
(G, "Léa, est-ce que je peux vous parler d'une chose ?", "레아 양, 한 가지 말해도 될까요?"),
(L, "Bien sûr, Gaston.", "물론이죠, 가스통."),
(G, "Depuis trente-quatre ans, ma boutique a la même enseigne, le même logo, la même vieille affiche. Elle date de 1991.", "34년째 우리 가게는 같은 간판, 같은 로고, 같은 낡은 포스터를 써요. 1991년 거예요."),
(G, "Un jour, quand vous aurez le temps... pourriez-vous me faire un croquis ? Juste une idée, pour voir.", "언젠가 시간이 나면... 스케치 하나 해 주실 수 있을까요? 아이디어만, 한번 보게요."),
(L, "Un nouveau logo pour La Cave des Abbesses ? Mais ce serait un honneur !", "라 카브 데 자베스의 새 로고요? 영광이죠!"),
(G, "Je ne peux pas vous payer en billets. Mais en bouteilles, oui.", "지폐로는 못 드려요. 하지만 와인 병으로는 드릴 수 있어요."),
(L, "Je préfère les bouteilles, de toute façon. Les billets, ça ne se boit pas.", "어차피 병이 더 좋아요. 지폐는 마실 수 없잖아요."),
(A, "Elle est vraiment très douée, Gaston. Je te le dis, tu ne vas pas le regretter.", "레아는 정말 재능이 뛰어나, 가스통. 후회 안 할 거야."),
(L, "Antoine, arrête de me flatter, je vais rougir.", "앙투안, 칭찬 그만해, 얼굴이 빨개지겠어."),
(A, "Je ne te flatte pas. Je constate.", "아부하는 게 아니야. 사실을 말하는 거지."),
(L, "Bon. Alors, pour revenir à notre bouteille : on la goûte ?", "그럼 우리 병으로 돌아가서, 맛볼까?"),
(G, "Mais c'est ce que je prépare depuis une demi-heure !", "내가 삼십 분 전부터 준비하고 있던 게 바로 그거야!"),
(None, "Gaston sert trois verres. Le vin est d'un rouge profond, presque violet.", "가스통이 잔 세 개를 따른다. 와인은 보라색에 가까운 짙은 붉은색이다."),
(L, "Il est très foncé. Presque noir sur les bords.", "아주 어두워. 가장자리는 거의 검은색이야."),
(A, "C'est le cabernet franc de la Loire. Regarde la robe : elle est dense et brillante.", "루아르의 카베르네 프랑이야. 색(로브)을 봐, 진하고 윤기가 나."),
(L, "La robe ? On parle de vêtements, maintenant ?", "로브요? 이제 옷 이야기를 하는 거야?"),
(A, "Dans le vocabulaire du vin, la robe, c'est la couleur. Je t'ai dit : le vin est une langue.", "와인 용어에서 로브는 색을 뜻해. 내가 말했잖아, 와인은 언어라고."),
(L, "Et le nez ? Je sens... des fruits noirs, de la terre humide, un peu de fumée.", "그럼 향은? 검은 과일, 젖은 흙, 약간의 연기가 느껴져."),
(A, "Impressionnant. Tu viens de décrire la tuffeau, le sol de Saumur. C'est exactement ça.", "인상적이야. 방금 소뮈르의 토양인 튀포(석회암)를 묘사했어. 바로 그거야."),
(L, "Je ne savais pas que c'était un mot si joli : tuffeau.", "튀포가 그렇게 예쁜 단어인 줄 몰랐어."),
(A, "C'est une pierre blanche, tendre, dans laquelle on creuse des caves. C'est comme ça que les Roches Blanches ont reçu leur nom.", "하얗고 무른 돌인데 그 안을 파서 저장고를 만들어. 로슈 블랑슈라는 이름도 거기서 나왔지."),
(L, "Alors cette étiquette raconte déjà une histoire entière.", "그럼 이 라벨은 벌써 한 편의 이야기를 통째로 들려주고 있네."),
(A, "Toutes les étiquettes racontent une histoire. Il suffit d'apprendre à les lire.", "모든 라벨은 이야기를 들려줘. 읽는 법만 배우면 돼."),
(L, "Merci pour la leçon, professeur.", "수업 고마워, 선생님."),
(A, "De rien, mademoiselle la graphiste. Et merci de m'avoir appris que Garamond était un homme.", "천만에, 디자이너 양. 그리고 가라몽이 사람 이름이라는 걸 알려 줘서 고마워."),
(G, "Moi, je vous remercie de me faire gagner du temps. Maintenant, vous pouvez finir ce que j'ai servi pendant que je m'occupe des vrais clients.", "나는 시간을 벌게 해 줘서 고맙고. 이제 내가 진짜 손님들 상대하는 동안 내가 따라 준 걸 마저 마셔요."),
(L, "Les vrais clients ? Nous, on est des faux clients ?", "진짜 손님이요? 우리는 가짜 손님이에요?"),
(G, "Vous, vous faites partie de la maison. C'est différent.", "당신들은 이 가게의 식구예요. 그건 달라요."),
(L, "(à Antoine) Il est toujours comme ça ?", "(앙투안에게) 항상 저러셔?"),
(A, "Toujours. C'est ce qui le rend impossible. Et irremplaçable.", "항상 저러지. 그래서 어쩔 수 없는 사람이고 대체할 수 없는 사람이기도 해."),
]

VOCAB = [
("A2","regarder / observer / voir","보다 / 관찰하다 / 보이다","« Je peux la regarder ? », « Tu es observatrice. », « Qu'est-ce que tu vois d'abord ? »"),
("A2","une sortie scolaire","현장 학습","scolaire = 학교의. « Les élèves sont partis en sortie scolaire. »"),
("A2","un dessin / une colline / un château","그림 / 언덕 / 성","라벨 묘사의 기본 어휘"),
("A2","des lettres dorées","금빛 글씨","dorer = 금빛으로 하다. dorée / doré 형용사"),
("A2","une étiquette","라벨","« Tu sais lire une étiquette de vin ? »"),
("A2","un croquis","스케치","« pourriez-vous me faire un croquis ? » 디자이너에게 요청할 때"),
("B1","un millésime / une récolte / les vendanges","빈티지 / 수확 / 포도 수확(작업)","vendanges는 항상 복수. « J'ai fait les vendanges. »"),
("B1","un sécateur","전정 가위","포도를 따거나 가지를 칠 때 쓰는 가위"),
("B1","mis en bouteille au domaine","도멘(농장)에서 병입한","생산자가 직접 병입한 와인임을 알리는 라벨 문구"),
("B1","un cépage","포도 품종","« les cépages autorisés » = 허용된 품종"),
("B1","le degré d'alcool / le volume","알코올 도수 / 용량","« 13 % vol. », « 75 cl »"),
("B1","une enseigne / un logo","간판 / 로고","가게의 시각 아이덴티티"),
("B1","c'est un malentendu courant","흔한 오해예요","malentendu = 오해, 생각의 엇갈림"),
("B2","Appellation d'Origine Contrôlée (AOC)","원산지 통제 명칭","프랑스의 법적 와인 품질·원산지 보증 제도"),
("B2","un cahier des charges","사양서, 규정집","« Tout est écrit dans un cahier des charges. »"),
("B2","un négociant","와인 유통업자(네고시앙)","포도나 와인을 사서 자기 이름으로 병입·판매하는 업자"),
("B2","les mentions obligatoires","필수 표시 사항","도수, 용량, 알레르겐 등 법적으로 표기해야 하는 정보"),
("B2","un sulfite","아황산염","« Contient des sulfites. » 보존제 역할을 하는 성분"),
("B2","la robe (d'un vin)","와인의 색","빛깔·농도·투명도를 말하는 시음 용어"),
("B2","une illustratrice / un graveur","일러스트레이터 / 활자 조각가","여성형 -trice, 남성형 -teur"),
("C1","avec les armoiries","문장(紋章)이 들어간","armoiries = 가문·도시의 방패 문장"),
("C1","un caractère à empattements","세리프체","타이포그래피 용어. 반대는 sans empattements(산세리프)"),
("C1","la tuffeau","튀포(소뮈르 지방의 하얀 석회암)","루아르 지방 건물·저장고를 만든 돌. 와인의 미네랄 풍미와 연결"),
("C1","irremplaçable","대체 불가능한","« impossible et irremplaçable » 애정 섞인 평가"),
]

GRAM = [
("A2","passé composé (조동사 avoir)",
 "« J'ai fini les cours plus tôt », « J'ai coupé du raisin », « Je lui ai écrit deux fois », « Il m'a répondu une fois ». avoir + 과거분사. 과거분사는 직접목적어가 앞에 오면 일치(상급)."),
("A2","passé composé (조동사 être)",
 "« Les élèves sont partis en sortie scolaire », « Elle est arrivée la première ». 이동·상태 변화 동사(aller, venir, partir, arriver, naître, mourir…)와 모든 대명동사는 être + 과거분사 + 주어 일치."),
("B1","의문사 qu'est-ce que / est-ce que / 도치",
 "« Qu'est-ce que tu vois d'abord ? » « Qu'est-ce que c'est que : « Mis en bouteille au domaine » ? » « Est-ce que je peux vous parler d'une chose ? » 구어에서는 억양만 올려서도 묻는다: « Tu as apporté une bouteille ? »"),
("B1","depuis / il y a / pendant",
 "« il y a trois semaines » = 2주 전 (과거 시점), « depuis trente-quatre ans » = 34년 전부터 지금까지 (계속), « pendant un mois » = 한 달 동안 (기간). « J'ai passé un mois chez mon père » 처럼 pendant 은 생략되기도 한다."),
("B1","중성대명사 en과 y (복습)",
 "« Il en ajoute un peu » (en = de sulfites), « Il suffit d'apprendre à les lire » (les = les étiquettes), « Tu t'en souviens ? » (se souvenir de → en). 대명사는 동사 앞에 위치."),
("B2","조건법으로 하는 정중한 요청",
 "« Pourriez-vous me faire un croquis ? » (pouvoir 조건법) / « Je voudrais… » / « Tu pourrais faire mieux ? ». 현재형보다 거리감을 두고 부드럽게 요청."),
("B2","직설법 미래 + quand: « quand vous aurez le temps »",
 "« Un jour, quand vous aurez le temps... » quand/lorsque/dès que 뒤에는 한국어와 달리 미래형을 쓴다(현재형 X). « Quand j'aurai fini, je t'appellerai. »"),
("C1","관계대명사 dans laquelle / dont",
 "« une pierre blanche dans laquelle on creuse des caves » (전치사 + laquelle: 장소·사물) / « les cépages dont on parle » (de + 선행사). 전치사가 붙는 관계절은 qui/que보다 한 단계 어렵다."),
]

CULTURE = [
("AOC와 라벨 읽기",
 "AOC는 프랑스의 와인 원산지 보증 제도다. 최근 EU 표기로 AOP(Appellation d'Origine Protégée)가 병기된다. 라벨의 순서는 생산자 → 명칭(AOC) → 빈티지 → 병입 정보 → 도수·용량 순이 일반적이다."),
("소뮈르샹피니와 튀포 저장고",
 "소뮈르샹피니(Saumur-Champigny)는 카베르네 프랑으로 만든 루아르의 레드다. 하얀 석회암(tuffeau)을 파서 만든 지하 저장고는 일정한 온도·습도를 유지해 와인 숙성에 이상적이다."),
("와인과 그래픽 디자인",
 "프랑스 와인 라벨은 전통적으로 샤토 일러스트와 세리프체를 쓰지만, 최근에는 젊은 생산자들이 일러스트레이터·디자이너와 협업해 대담한 디자인을 내놓는다. 레아의 직업이 이야기에 쓰이는 첫 장면이다."),
]

META = dict(part=1, ep=5, part_label="제1부 첫 잔 · Premier verre", title_fr="L'histoire d'une étiquette", title_ko="라벨 속의 이야기",
 place="La Cave des Abbesses · 4월 중순 목요일 18시 (시음회 전 한가한 가게)",
 chars="Léa · Antoine · Gaston",
 wine="Saumur-Champigny AOC (Domaine des Roches Blanches, 2019)",
 focus="복합과거(avoir/être), 의문문, depuis/il y a/pendant, 조건법 정중 요청, 라벨·와인 용어",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제6화 « Bourgogne contre Bordeaux » : 지역 대결 놀이. 레아가 보르도를 두둔하는 데는 이유가 있는 것 같다.")
