# -*- coding: utf-8 -*-
G, L, A = "Gaston", "Léa", "Antoine"
D = [
(None, "Lundi, 18 h 20, mi-mai. Une pluie battante tombe sur Montmartre depuis midi. Léa pousse la porte de la boutique, trempée de la tête aux pieds. La cloche de la porte tinte.", "5월 중순 월요일 오후 6시 20분. 낮부터 몽마르트르에 폭우가 쏟아진다. 레아가 머리부터 발끝까지 흠뻑 젖은 채 가게 문을 민다. 문의 종이 울린다."),
(G, "Léa ! Mon Dieu, vous êtes complètement trempée !", "레아! 세상에, 완전히 젖었잖아요!"),
(L, "Bonsoir, Gaston. Il pleut des cordes. Je n'ai plus de parapluie, alors je suis sortie comme ça.", "안녕하세요, 가스통. 억수같이 쏟아져요. 우산이 없어서 이렇게 나왔어요."),
(G, "Ah oui, votre parapluie. Vous l'avez oublié ici jeudi dernier.", "아, 맞아요, 우산이요. 지난 목요일에 여기에 두고 갔죠."),
(L, "Je sais. J'ai cherché partout dans mon appartement. Puis j'ai compris : je l'avais laissé chez vous.", "알아요. 집 안을 샅샅이 뒤졌어요. 그러다 깨달았죠. 여기에 두고 왔다는 걸."),
(G, "Eh bien, il n'est plus là.", "그런데 이젠 여기 없어요."),
(L, "Comment ça, il n'est plus là ? Quelqu'un l'a volé ?", "무슨 말씀이세요, 여기 없다니요? 누가 훔쳐 갔어요?"),
(G, "Quelqu'un l'a emporté, c'est vrai. Mais ce n'est pas un voleur. C'est un professeur d'histoire.", "누가 가져간 건 맞아요. 하지만 도둑은 아닙니다. 역사 선생님이에요."),
(L, "Antoine ?", "앙투안이요?"),
(G, "Antoine. Il a dit qu'il vous le rapporterait lui-même. Il habite dans votre rue, après tout.", "앙투안이요. 직접 돌려주겠다고 했어요. 어쨌든 같은 거리에 사니까."),
(L, "Il ne me l'a pas rapporté.", "돌려주지 않았어요."),
(G, "Alors c'est qu'il n'a pas eu l'occasion. Ou qu'il n'a pas eu le courage.", "그럼 기회가 없었던 거겠죠. 아니면 용기가 없었거나."),
(L, "Le courage ? Pour rapporter un parapluie ?", "용기요? 우산을 돌려주는 데요?"),
(G, "Pour sonner à la porte d'une jeune femme sans savoir si elle est de bonne humeur. C'est un acte héroïque.", "기분이 좋은지 모르는 젊은 여자 집 초인종을 누르는 건 영웅적인 행동이에요."),
(L, "Vous exagérez toujours, Gaston.", "가스통은 항상 과장하세요."),
(G, "À propos : depuis un mois, nous nous vouvoyons, et je trouve ça ridicule. Si on se tutoyait ?", "그런데 말이야, 한 달째 서로 존댓말을 쓰는데 우스꽝스럽지 않아? 우리 말 놓을까?"),
(L, "Avec plaisir. Tu... Je veux dire, tu as raison, Gaston.", "기꺼이요. 당신... 아니, 네 말이 맞아, 가스통."),
(G, "Voilà ! Tu vois que ce n'est pas difficile ? Je ne tutoie que les gens que j'aime bien, tu sais.", "봐! 어렵지 않지? 나는 마음에 드는 사람한테만 말을 놓거든."),
(L, "Je suis flattée. C'est un honneur, de la part d'un homme qui a trente-quatre ans de métier.", "영광이에요. 34년 경력의 분께서 그러시다니."),
(G, "Trente-cinq, depuis ce mois-ci. J'ai fêté mon anniversaire de boutique samedi dernier. Avec un gâteau.", "이번 달부터 35년이야. 지난 토요일에 가게 기념일을 케이크로 축하했지."),
(None, "La porte s'ouvre à la volée. Antoine entre, trempé comme une soupe, tenant à la main un parapluie fermé. Il ruisselle sur le paillasson.", "문이 확 열린다. 앙투안이 국물처럼 흠뻑 젖어 닫힌 우산을 손에 들고 들어온다. 현관 매트 위로 물이 뚝뚝 떨어진다."),
(A, "Bonsoir, Gaston ! Il tombe des cordes ! Oh... Léa ?", "안녕, 가스통! 억수같이 쏟아져! 오... 레아?"),
(L, "Antoine ! Tu es dans un état...", "앙투안! 몰골이..."),
(A, "J'allais te l'apporter, ton parapluie. Je voulais te le rendre ce soir, enfin, je ne sais plus quand...", "네 우산을 가져다주려던 참이었어. 오늘 저녁에 돌려주려고 했는데, 아니, 언제였는지 이젠 모르겠어..."),
(L, "Tu l'as dans la main. Pourquoi tu ne l'ouvres pas ?", "손에 들고 있잖아. 왜 안 펴?"),
(A, "Parce que ce n'est pas mon parapluie. Je ne l'ouvrirais jamais sans ta permission.", "내 우산이 아니니까. 네 허락 없이는 절대 안 펼 거야."),
(G, "Un gentleman. Ou un imbécile.", "신사야. 아니면 바보거나."),
(A, "Les deux, probablement.", "아마 둘 다일 거야."),
(L, "(rit) Tu es complètement trempé, Antoine. Je te donne la permission. Ouvre-le.", "(웃으며) 완전히 젖었어, 앙투안. 내가 허락할게. 펴."),
(A, "Maintenant, il est un peu tard.", "이젠 좀 늦었는데."),
(G, "Je vais chercher une serviette. Ne bougez pas, vous deux. Ne partez surtout pas.", "수건을 가져올게. 두 사람 움직이지 마. 절대 가지 말고."),
(None, "Gaston disparaît dans l'arrière-boutique. Antoine tend le parapluie à Léa, qui le prend en souriant.", "가스통이 안쪽 창고로 사라진다. 앙투안이 우산을 레아에게 건네자 그녀가 미소 지으며 받는다."),
(L, "Merci de l'avoir gardé. Alors raconte-moi : qu'est-ce que tu as fait de mon parapluie, pendant quatre jours ?", "우산을 보관해 줘서 고마워. 그래서 말해 봐. 나흘 동안 내 우산으로 뭘 했어?"),
(A, "Jeudi soir, je l'ai ramené chez moi. Il était encore tout mouillé. Je l'ai ouvert dans la cuisine pour le faire sécher.", "목요일 밤에 집으로 가져갔어. 아직 흠뻑 젖어 있었지. 말리려고 부엌에서 펴 놨어."),
(L, "Et il a séché ?", "그래서 말랐어?"),
(A, "Oui. Il est resté ouvert jusqu'à vendredi matin. Ma voisine a cru que je faisais de l'art contemporain.", "응. 금요일 아침까지 펼쳐져 있었어. 이웃이 내가 현대 미술을 하는 줄 알았대."),
(L, "(rit) Et après ?", "(웃음) 그다음엔?"),
(A, "Vendredi, après les cours, je suis allé chez toi. Je voulais sonner.", "금요일에 수업 끝나고 네 집에 갔어. 초인종을 누르려고 했지."),
(L, "Vendredi ? Je n'étais pas là. Je suis partie à Lyon vendredi à midi.", "금요일? 나 없었어. 금요일 낮에 리옹으로 떠났거든."),
(A, "Je l'ai compris. Il n'y avait aucune lumière, et la concierge m'a dit : « Mademoiselle Fontaine est partie avec une valise. »", "그걸 알아챘어. 불이 하나도 안 켜져 있었고 관리인이 말했어. '퐁텐 양은 여행 가방을 들고 나갔어요.'"),
(L, "Madame Roche. Elle sait tout sur tout le monde.", "로슈 부인이야. 모두에 대해 전부 알아."),
(A, "Elle m'a même demandé si j'étais ton fiancé.", "내가 네 약혼자냐고 묻기까지 했어."),
(L, "Et tu as répondu quoi ?", "그래서 뭐라고 대답했어?"),
(A, "Que j'étais seulement un voisin avec un parapluie.", "그냥 우산을 가진 이웃이라고."),
(L, "Un voisin avec un parapluie. C'est une excellente carte de visite.", "우산을 가진 이웃이라니. 훌륭한 명함이네."),
(A, "Et toi, ton week-end ? Tu étais à Lyon ?", "너는? 주말은 어땠어? 리옹에 있었어?"),
(L, "Oui, chez ma mère. Je rentre une fois par mois, en général.", "응, 어머니 집에. 보통 한 달에 한 번 가."),
(A, "Raconte.", "얘기해 줘."),
(L, "Quand je suis arrivée, vendredi soir, ma mère était dans la cuisine. Elle préparait un gratin dauphinois.", "금요일 저녁에 도착했을 때 어머니는 부엌에 계셨어. 그라탱 도피누아를 만드시고 있었지."),
(L, "Mon petit frère, Hugo, jouait de la guitare dans le salon, comme quand il avait quinze ans. Il a vingt-cinq ans maintenant, mais il joue toujours les mêmes trois accords.", "남동생 위고는 열다섯 살 때처럼 거실에서 기타를 치고 있었어. 지금은 스물다섯인데 여전히 같은 세 개의 코드만 쳐."),
(A, "Les mêmes trois accords ?", "같은 세 개 코드?"),
(L, "Do, sol, la mineur. Toute la famille chante par-dessus. Faux, mais avec beaucoup de conviction.", "도, 솔, 라 마이너. 온 가족이 그 위에 노래를 불러. 음정은 틀리지만 확신에 차서."),
(A, "Ça ressemble à mes dimanches chez mon père.", "우리 아버지 집 일요일이랑 비슷하네."),
(L, "Peut-être. Samedi, il pleuvait à Lyon aussi. On est restés à la maison. Ma mère m'a montré de vieilles photos.", "그럴지도. 토요일엔 리옹에서도 비가 왔어. 우리는 집에 있었고 어머니가 오래된 사진들을 보여 주셨어."),
(L, "Il y avait une photo de moi, à six ans, avec un grand parapluie jaune. J'avais l'air d'un champignon.", "여섯 살의 내가 큰 노란 우산을 들고 있는 사진이 있었어. 버섯 같았지."),
(A, "Un champignon, c'est adorable.", "버섯이라니 사랑스러운데."),
(L, "Tu ne l'as pas vue. Je ressemblais surtout à un petit pois en colère. Mais ce parapluie, je l'adorais.", "넌 못 봐서 그래. 나는 주로 화난 완두콩 같았어. 하지만 그 우산이 정말 좋았지."),
(L, "Je l'ai perdu à sept ans, dans le tramway. J'ai pleuré pendant trois jours.", "일곱 살에 전차에서 잃어버렸어. 사흘 동안 울었지."),
(A, "Et depuis, tu perds tous tes parapluies ?", "그래서 그 뒤로 우산을 다 잃어버렸어?"),
(L, "J'en ai perdu... je crois que huit. Neuf avec celui de jeudi, si tu ne l'avais pas retrouvé.", "아마... 여덟 개 잃어버렸을걸. 네가 찾아주지 않았다면 목요일 우산까지 아홉 개였겠지."),
(A, "Neuf parapluies ! Tu devrais t'acheter un parapluie avec ton nom brodé dessus.", "우산 아홉 개라니! 이름이 수놓인 우산을 사야겠다."),
(L, "Ou un parapluie avec un traceur GPS.", "아니면 GPS 추적기가 달린 우산."),
(A, "Ça existe, sans doute. Je me renseignerai.", "아마 있을 거야. 알아볼게."),
(L, "Et toi, ton week-end ? À part sécher mon parapluie ?", "그리고 너는? 내 우산 말린 것 말고 주말에 뭐 했어?"),
(A, "Samedi, je suis allé au marché, j'ai acheté des légumes. Dimanche, j'ai corrigé des copies toute la journée.", "토요일엔 장에 가서 채소를 샀어. 일요일엔 하루 종일 채점했고."),
(L, "Quelle vie passionnante.", "아주 흥미진진한 삶이네."),
(A, "J'en suis conscient. Mais il y a eu un moment, dimanche soir, où je corrigeais une copie sur Napoléon...", "나도 알아. 하지만 일요일 저녁에 나폴레옹에 대한 답안지를 채점하던 순간이 있었어..."),
(L, "Et alors ?", "그래서?"),
(A, "L'élève avait écrit : « Napoléon est mort à Sainte-Hélène parce qu'il n'avait pas de parapluie. » Je me suis dit : il faut que je raconte ça à Léa.", "학생이 이렇게 썼더라. '나폴레옹은 우산이 없어서 세인트헬레나에서 죽었다.' 속으로 생각했어. 레아한테 이 얘기를 해 줘야겠다고."),
(L, "(rit aux éclats) C'est vrai ? Il a écrit ça ?", "(크게 웃으며) 정말? 그렇게 썼어?"),
(A, "Mot pour mot. J'ai mis un zéro, mais j'ai gardé la copie.", "토씨 하나 안 틀리고. 0점을 줬지만 답안지는 간직했어."),
(L, "Tu me la montreras ?", "나한테 보여 줄 거야?"),
(A, "Je te la montrerai. Elle est encadrée sur mon frigo.", "보여 줄게. 냉장고 위에 액자에 넣어 놨어."),
(None, "Gaston revient avec une grande serviette et une bouteille ouverte.", "가스통이 큰 수건과 열린 병 하나를 들고 돌아온다."),
(G, "Tenez, séchez-vous. Et prenez un verre de ça, pour vous réchauffer. Un Vouvray moelleux, ce soir c'est la maison qui offre.", "자, 닦아. 그리고 몸 녹이게 이거 한 잔 마셔. 부브레 무알뢰, 오늘은 가게에서 대접하는 거야."),
(L, "Gaston, merci. Tu ne fais jamais ça.", "가스통, 고마워. 이런 건 절대 안 하잖아."),
(G, "Jamais, c'est vrai. Mais ce soir, j'ai l'impression que quelque chose se passe, et je ne veux pas que ça refroidisse.", "절대 안 하지, 맞아. 하지만 오늘 저녁엔 뭔가 일어나고 있는 것 같고, 그게 식는 걸 원치 않아."),
(A, "Gaston, tu as vraiment une imagination fertile.", "가스통, 넌 정말 상상력이 풍부해."),
(G, "J'ai surtout de bons yeux. Maintenant, buvez.", "눈이 좋을 뿐이야. 이제 마셔."),
(L, "(goûte) Oh, c'est doux comme du miel. Avec une fraîcheur incroyable à la fin.", "(맛본다) 오, 꿀처럼 달콤해. 그리고 끝에 놀라운 신선함이 있어."),
(A, "C'est du chenin blanc. Un cépage de ma région. Il peut être sec, moelleux ou pétillant, selon l'humeur du vigneron.", "슈냉 블랑이야. 우리 지방 품종이지. 와인 농부의 기분에 따라 드라이도, 달콤한 것도, 스파클링도 될 수 있어."),
(L, "Un cépage à humeur variable. Comme moi.", "기분이 변하는 품종이네. 나처럼."),
(A, "Je ne dirais pas que tu es à humeur variable. Je dirais que tu es... imprévisible.", "너를 기분이 변한다고는 안 하겠어. 예측 불가능하다고 하겠어."),
(L, "C'est la même chose, dite avec plus de politesse.", "같은 말을 더 정중하게 한 거네."),
(A, "Exactement.", "정확해."),
(G, "La pluie s'arrête, vous voyez ? C'est un signe.", "비가 그치네, 보여? 신호야."),
(L, "Un signe de quoi ?", "무슨 신호인데?"),
(G, "Que vous pouvez rentrer à pied ensemble, sans parapluie.", "우산 없이 같이 걸어서 돌아가도 된다는 신호."),
(A, "Mais Léa a son parapluie, maintenant.", "하지만 레아한텐 이제 우산이 있잖아."),
(L, "Et je ne l'ouvre pas, justement, si la pluie s'arrête.", "그리고 비가 그치면 일부러 안 펼 거야."),
(A, "Bonne logique.", "좋은 논리야."),
(G, "Rentrez bien. Et Léa, n'oublie pas ton parapluie, cette fois.", "조심히 들어가. 그리고 레아, 이번엔 우산 잊지 마."),
(L, "Je le tiens très fort, regarde. Même Antoine ne pourra pas me le prendre.", "아주 꽉 잡고 있어, 봐. 앙투안도 못 가져갈걸."),
(A, "Je ne prends rien qui ne m'appartient pas. Sauf des tasses de café, parfois.", "내 것이 아닌 건 아무것도 안 가져가. 가끔 커피잔 빼고는."),
(None, "Dehors, les nuages s'ouvrent. Une lumière dorée tombe sur les trottoirs mouillés. Léa et Antoine marchent côte à côte.", "밖에서 구름이 갈라진다. 금빛 햇살이 젖은 보도 위에 내려앉는다. 레아와 앙투안이 나란히 걷는다."),
(A, "Dis, Léa, dimanche après-midi, est-ce que tu es libre ?", "저, 레아, 일요일 오후에 시간 있어?"),
(L, "Dimanche ? Je crois que oui. Pourquoi ?", "일요일? 있을 것 같은데. 왜?"),
(A, "Il y a un café, en face de la boutique, que j'aime bien. Je pourrais t'inviter. Avant seize heures, bien sûr.", "가게 맞은편에 내가 좋아하는 카페가 있어. 널 초대할 수 있을 텐데. 물론 4시 전에."),
(L, "Tu t'es souvenu de mon histoire de café.", "내 커피 얘기를 기억했구나."),
(A, "Je me souviens de tout ce qui est étrange. C'est un défaut.", "이상한 건 다 기억해. 단점이지."),
(L, "(rit) Tu me copies, maintenant ! D'accord. Dimanche, quinze heures ?", "(웃음) 이젠 날 따라 하네! 좋아. 일요일 3시?"),
(A, "Quinze heures. Au Moulin Gris.", "3시. 물랭 그리에서."),
(L, "Au Moulin Gris. C'est promis. Et cette fois, je ne l'oublierai pas.", "물랭 그리. 약속해. 이번엔 안 잊을게."),
(A, "Tu ne peux pas oublier ton parapluie. Tu l'as à la main.", "우산은 못 잊을걸. 손에 들고 있잖아."),
(L, "Je parlais du rendez-vous.", "약속 얘기였어."),
]

VOCAB = [
("A2","il pleut des cordes / une pluie battante","비가 억수같이 쏟아진다","« Il pleut des cordes. » = Il pleut très fort. 영어의 raining cats and dogs에 해당"),
("A2","trempé(e) / mouillé(e) / sécher","흠뻑 젖은 / 젖은 / 말리다","« trempé de la tête aux pieds », « le faire sécher »"),
("A2","un parapluie / ouvrir / fermer","우산 / 펴다 / 접다","« Ouvre-le. », « un parapluie fermé »"),
("A2","une serviette","수건","« Je vais chercher une serviette. » 식당에서는 냅킨, 욕실에서는 수건"),
("A2","un gratin dauphinois","그라탱 도피누아","감자와 크림으로 만든 프랑스 가정식 그라탱"),
("B1","rapporter / emporter / ramener","다시 가져다주다 / 가지고 가다 / 데려오다·도로 가져오다","« Il vous le rapporterait. », « Quelqu'un l'a emporté. », « Je l'ai ramené chez moi. »"),
("B1","la concierge","(건물) 관리인","프랑스 아파트 관리인. 입주민 정보를 속속들이 아는 전형적 인물"),
("B1","un voisin / une voisine","이웃","« un voisin avec un parapluie »"),
("B1","un fiancé / une fiancée","약혼자","관리인이 쓴 말. 연인 사이를 한 단계 앞서 추측하는 농담"),
("B1","un petit pois","완두콩","« un petit pois en colère » = 화난 아이를 귀엽게 묘사"),
("B1","imprévisible","예측할 수 없는","« Je dirais que tu es imprévisible. »"),
("B1","moelleux","달콤하고 부드러운","와인에서 반건조·달콤한 타입. Vouvray moelleux"),
("B2","un acte héroïque","영웅적인 행동","« un acte héroïque » 과장된 농담"),
("B2","être flatté(e) / un honneur","우쭐하다 / 영광","« Je suis flattée. »"),
("B2","un paillasson","현관 매트","« Il ruisselle sur le paillasson. »"),
("B2","ruisseler","(물이) 흘러내리다","옷·머리에서 물이 뚝뚝 떨어지는 상태"),
("B2","un traceur GPS","GPS 추적기","분실 방지 장치"),
("B2","encadré(e)","액자에 넣은","« Elle est encadrée sur mon frigo. »"),
("B2","à humeur variable","기분이 변하는","humeur = 기분. « de bonne/mauvaise humeur »"),
("C1","trempé comme une soupe","국물처럼 흠뻑 젖은","관용 비유. 보통 'trempé comme une soupe'"),
("C1","rire aux éclats","폭소하다","« Elle rit aux éclats. » 소리 내어 크게 웃음"),
("C1","avoir une imagination fertile","상상력이 풍부하다","fertile = 풍부한. 약간의 핀잔도 담김"),
("C1","Je ne veux pas que ça refroidisse.","그게 식는 걸 원치 않아.","refroidir 접속법. 사랑·관계가 식는다는 은유"),
("C1","mot pour mot","한 글자도 틀리지 않고","인용을 정확히 전할 때"),
]

GRAM = [
("A2","passé composé — 일회성 사건",
 "« Jeudi soir, je l'ai ramené chez moi. » « Je suis allé chez toi. » « Je suis partie à Lyon. » 완결된 사건·특정 시점은 passé composé. aller/partir/venir는 être, 나머지는 avoir."),
("A2","imparfait — 배경·상태·습관",
 "« Il pleuvait à Lyon aussi. » « Elle préparait un gratin. » « Hugo jouait de la guitare. » « J'avais l'air d'un champignon. » 진행 중이던 동작·묘사·반복 습관은 imparfait: -ais, -ais, -ait, -ions, -iez, -aient."),
("B1","imparfait와 passé composé의 대비",
 "« Quand je suis arrivée, ma mère était dans la cuisine. Elle préparait un gratin. » → 도착(사건: passé composé) + 어머니의 상태·동작(배경: imparfait). « Il y a eu un moment où je corrigeais une copie. » 사건이 일어나던 때의 배경은 imparfait."),
("B1","aller + 동사원형 과거: j'allais",
 "« J'allais te l'apporter, ton parapluie. » 막 ~하려던 참이었다(반과거 + 동사원형). 의도했으나 하지 못한 일에 자주 쓴다."),
("B1","조건법: 간접화법 속 미래 « il vous le rapporterait »",
 "« Il a dit qu'il vous le rapporterait lui-même. » 주절이 과거이면 종속절의 미래는 조건법 현재(rapporterait). 직접 화법: « Je le lui rapporterai. »"),
("B2","대명동사 se souvenir de / se renseigner",
 "« Tu t'es souvenu de mon histoire de café. » « Je me renseignerai. » se souvenir de(기억해 내다), se renseigner(알아보다). 복합과거에서는 être + 과거분사로 성·수 일치: « Elle s'est souvenue. »"),
("B2","접속법: je ne veux pas que + 접속법",
 "« Je ne veux pas que ça refroidisse. » vouloir que + 접속법. « Il faut que je te raconte ça. » 의지·필요·감정 표현에는 접속법을 사용."),
("C1","강조 구문: C'est la même chose, dite avec plus de politesse",
 "« C'est la même chose, dite avec plus de politesse. » 과거분사 구문(dite)으로 간결한 설명을 덧붙임. 문어체·위트 있는 구어에서 자주 쓰인다."),
]

CULTURE = [
("부브레 무알뢰와 슈냉 블랑",
 "루아르 지방의 슈냉 블랑(chenin blanc)은 드라이(sec), 반건조(demi-sec), 달콤한(moelleux), 스파클링 등 다양한 스타일이 가능한 만능 품종이다. 부브레(Vouvray) 무알뢰는 꿀과 사과·배 향이 대표적이다."),
("프랑스 아파트의 관리인(concierge)",
 "과거 파리 건물에는 입주민 정보를 훤히 아는 관리인이 상주했다. 지금은 줄었지만 문학·영화에서는 '이웃의 비밀을 다 아는 인물'로 자주 등장한다."),
("이야기 속 습관: 가스통의 '무료 와인'",
 "와인숍 주인이 단골의 중요한 순간에 한 잔 건네는 것은 프랑스 가게에서 흔한 호의다. 가스통이 '절대 안 하던 일'을 한 것은 두 사람을 응원한다는 사인이다."),
]

META = dict(part=1, ep=8, part_label="제1부 첫 잔 · Premier verre", title_fr="Le parapluie oublié", title_ko="잊어버린 우산",
 place="La Cave des Abbesses → 몽마르트르 거리 · 5월 중순 월요일 18시 20분, 폭우 후 갬",
 chars="Léa · Antoine · Gaston",
 wine="Vouvray moelleux (루아르 슈냉 블랑)",
 focus="복합과거 vs 반과거, j'allais + 동사원형, 조건법(간접화법), 대명동사, 이야기하기",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제9화 « Un café en face » : 처음으로 가게 밖에서 보내는 일요일 오후. 직업과 가족 이야기, 그리고 ‘근접미래’로 그려 보는 앞으로의 계획.")
