# -*- coding: utf-8 -*-
G, L, A, S = "Gaston", "Léa", "Antoine", "Le serveur"
D = [
(None, "Dimanche, 15 h. Le café Le Moulin Gris, en face de la boutique, a installé quelques tables en terrasse. Le soleil est revenu après la pluie. Antoine est arrivé le premier et a choisi la table près de la fenêtre.", "일요일 오후 3시. 가게 맞은편 카페 '르 물랭 그리'가 테라스에 테이블 몇 개를 내놓았다. 비가 그치고 해가 돌아왔다. 앙투안이 먼저 도착해 창가 쪽 테이블을 골랐다."),
(A, "Léa ! Ici !", "레아! 여기야!"),
(L, "Bonjour, Antoine. Tu es déjà là ? Je suis pourtant à l'heure : quinze heures pile.", "안녕, 앙투안. 벌써 와 있었어? 나도 정각인데: 3시 정각."),
(A, "Je suis arrivé en avance. J'avais peur de ne pas trouver de place.", "일찍 왔어. 자리를 못 찾을까 봐 걱정이었거든."),
(L, "Le café est presque vide.", "카페가 거의 비어 있는데."),
(A, "Aujourd'hui, oui. Mais le dimanche d'avant, il n'y avait pas une seule chaise libre.", "오늘은 그렇지. 하지만 지난 일요일엔 빈 의자가 하나도 없었어."),
(L, "Tu es un habitué ?", "단골이야?"),
(A, "Pas vraiment. Je viens deux ou trois fois par mois, pour corriger mes copies avec un café.", "그렇진 않아. 한 달에 두세 번 와서 커피 마시며 채점해."),
(S, "Bonjour, madame, bonjour, monsieur. Qu'est-ce que je vous sers ?", "안녕하세요, 부인, 안녕하세요, 선생님. 뭘 드릴까요?"),
(L, "Bonjour. Je voudrais un thé, s'il vous plaît. Un thé à la menthe, si vous en avez.", "안녕하세요. 차 한 잔 주세요. 민트차 있으면요."),
(S, "Nous avons un très bon thé à la menthe fraîche. Et pour monsieur ?", "신선한 민트로 만든 아주 좋은 차가 있어요. 그리고 선생님은요?"),
(A, "Un café noisette, s'il vous plaît. Et un verre d'eau pour la table.", "카페 누아제트 하나 주세요. 그리고 테이블에 물 한 잔이요."),
(S, "Très bien. Je vous apporte ça tout de suite.", "알겠습니다. 바로 가져다 드릴게요."),
(L, "Un café noisette ? C'est un café avec des noisettes ?", "카페 누아제트? 개암이 들어간 커피야?"),
(A, "Non, c'est un espresso avec un tout petit peu de lait. Sa couleur ressemble à celle d'une noisette.", "아니, 우유를 아주 조금 넣은 에스프레소야. 색이 개암을 닮았어."),
(L, "Je vois. Les Français ont toujours un mot pour chaque nuance de café.", "알겠어. 프랑스 사람들은 커피 농도마다 이름이 있구나."),
(A, "Un café, un crème, un noisette, un allongé, un serré... On pourrait écrire un dictionnaire.", "카페, 크렘, 누아제트, 알롱제, 세레... 사전도 하나 쓸 수 있을 거야."),
(L, "Et toi, tu es le professeur du café aussi ?", "너는 커피 선생님이기도 해?"),
(A, "Non, de l'histoire. Mais j'ai passé beaucoup de temps dans les cafés.", "아니, 역사 선생님이야. 하지만 카페에서 많은 시간을 보냈지."),
(None, "Le serveur pose deux tasses et un verre d'eau sur la table. Léa respire l'odeur de la menthe.", "종업원이 잔 두 개와 물 한 잔을 테이블에 놓는다. 레아가 민트 향을 들이마신다."),
(L, "Hmm, ça sent bon. Je n'ai jamais pris le temps de m'asseoir dans un café le dimanche.", "음, 향이 좋다. 일요일에 카페에 앉아 있을 시간을 낸 적이 없어."),
(A, "Tu travailles le dimanche ?", "일요일에도 일해?"),
(L, "Souvent. Quand on est indépendant, le week-end n'existe pas vraiment. Je travaille quand j'ai des idées, ou quand j'ai peur de ne plus en avoir.", "자주. 프리랜서는 주말이 사실상 없어. 아이디어가 있을 때나, 더 이상 없을까 봐 무서울 때 일해."),
(A, "Et aujourd'hui ?", "그럼 오늘은?"),
(L, "Aujourd'hui, j'ai décidé de ne pas travailler. C'est un événement.", "오늘은 일하지 않기로 했어. 이건 하나의 사건이야."),
(A, "Je suis flatté d'être l'excuse.", "내가 핑계가 된 게 영광이야."),
(L, "Tu n'es pas l'excuse. Tu es la raison. C'est différent.", "넌 핑계가 아니라 이유야. 그건 달라."),
(A, "(un peu surpris) Alors je suis encore plus flatté.", "(조금 놀라며) 그럼 더 영광인데."),
(L, "Bon, raconte-moi : pourquoi tu as choisi d'être professeur d'histoire ?", "자, 말해 봐. 왜 역사 선생님이 되기로 했어?"),
(A, "À dix-huit ans, j'ai lu un livre sur la Révolution française. Je me suis dit : si je peux raconter ça à des élèves, je serai heureux.", "열여덟 살에 프랑스 혁명에 관한 책을 읽었어. 이걸 학생들에게 들려줄 수 있다면 행복하겠다고 생각했지."),
(L, "Et tu es heureux ?", "그래서 행복해?"),
(A, "La plupart du temps. Quand un élève lève la main et dit : « Monsieur, c'est incroyable ! », oui, je suis le plus heureux du monde.", "대부분은. 학생이 손을 들고 '선생님, 믿기지 않아요!'라고 할 때면 세상에서 가장 행복해."),
(L, "Et quand il dit : « Monsieur, est-ce qu'on a vraiment besoin de savoir ça ? »", "그럼 '선생님, 이런 걸 꼭 알아야 해요?'라고 할 때는?"),
(A, "Alors je prends une grande respiration et je lui raconte une anecdote plus drôle.", "그럴 땐 숨을 크게 쉬고 더 웃긴 일화를 들려줘."),
(L, "Tu es un conteur, au fond. Pas seulement un professeur.", "넌 본질적으로 이야기꾼이야. 단순한 교사가 아니고."),
(A, "C'est ce que disait ma mère.", "우리 어머니가 하신 말씀이야."),
(L, "Disait ?", "하셨다고?"),
(A, "Elle est morte quand j'avais quatorze ans. Un cancer. Elle était institutrice, elle aussi.", "내가 열네 살 때 돌아가셨어. 암이었지. 어머니도 초등학교 교사셨어."),
(L, "Je suis désolée, Antoine. Je ne savais pas.", "미안해, 앙투안. 몰랐어."),
(A, "Ne t'excuse pas. C'était il y a vingt ans. Mais je pense à elle chaque fois que je commence un cours.", "사과하지 마. 이십 년 전 일이야. 하지만 수업을 시작할 때마다 어머니 생각을 해."),
(L, "Elle serait fière de toi.", "어머니가 자랑스러워하셨을 거야."),
(A, "J'espère. Mon père dit qu'elle aurait voulu que je reprenne le domaine, mais je ne crois pas. Elle disait toujours : « Fais ce qui te rend vivant. »", "그러길 바라. 아버지는 어머니가 내가 농장을 물려받길 원하셨을 거라고 하시지만 난 그렇게 생각 안 해. 어머니는 늘 '널 살아 있게 하는 걸 해라'라고 하셨거든."),
(L, "C'est une belle phrase.", "아름다운 말이야."),
(A, "Oui. Et toi ? Ta famille, ta mère ?", "응. 너는? 가족은? 어머니는?"),
(L, "Ma mère s'appelle Nicole. Elle est infirmière à l'hôpital de la Croix-Rousse, à Lyon. Elle a pris sa retraite il y a deux ans, mais elle continue d'aller à l'hôpital comme bénévole.", "어머니 이름은 니콜이야. 리옹 크루아루스 병원 간호사였어. 2년 전에 은퇴했지만 자원봉사자로 계속 병원에 가셔."),
(A, "Une femme infatigable.", "지칠 줄 모르는 분이네."),
(L, "Oui. Mon père, Bernard, est ingénieur. Il est taciturne. Mais quand il rit, tout l'immeuble l'entend.", "응. 아버지 베르나르는 엔지니어야. 과묵하시지. 하지만 웃으실 땐 건물 전체가 들어."),
(A, "Et ton frère ? Hugo ?", "그리고 동생은? 위고?"),
(L, "Hugo, c'est le musicien. Il joue de la guitare dans un petit bar, le soir. Le jour, il livre des repas à vélo.", "위고는 음악가야. 밤에는 작은 바에서 기타를 쳐. 낮에는 자전거로 음식 배달을 하고."),
(A, "Un homme libre.", "자유로운 사람이네."),
(L, "Ou un homme fauché. Mais heureux.", "아니면 빈털터리거나. 하지만 행복해."),
(A, "Il y a des gens qui sont les deux.", "둘 다인 사람도 있지."),
(L, "Et moi ? Moi, je suis la raisonnable de la famille. Celle qui a un vrai métier.", "그럼 나는? 나는 집안의 이성적인 사람이야. 진짜 직업이 있는 사람."),
(A, "Mais graphiste, c'est un vrai métier ?", "그런데 그래픽 디자이너는 진짜 직업이야?"),
(L, "Pour mon père, non. « Dessiner pour gagner sa vie », ça ne lui paraît pas sérieux.", "아버지께는 아니야. '그림을 그려서 돈을 번다'는 게 진지해 보이지 않으시대."),
(A, "Mais tu gagnes bien ta vie, non ?", "하지만 너 생활비는 잘 벌잖아, 아니야?"),
(L, "Parfois. Cette année, c'est un peu mieux. J'ai eu de nouveaux clients, une marque de chocolat, une librairie, une agence de voyage.", "가끔은. 올해는 조금 나아졌어. 새 고객이 생겼거든. 초콜릿 브랜드, 서점, 여행사."),
(A, "Et cet appel, jeudi soir ? C'était un de ces clients ?", "그럼 목요일 저녁 그 전화는? 그 고객 중 하나였어?"),
(L, "(un temps) Euh... Pas exactement. Une proposition de travail. Quelque chose que je ne suis pas sûre de vouloir.", "(잠시 침묵) 음... 정확히는 아니야. 일 제안이었어. 내가 원하는지 확신이 안 서는 거."),
(A, "Une proposition ? Où ça ?", "제안? 어디서?"),
(L, "Je préfère ne pas en parler maintenant. C'est trop tôt. Je dois d'abord réfléchir.", "지금은 말하고 싶지 않아. 너무 일러. 먼저 생각해 봐야 해."),
(A, "D'accord. Je n'insiste pas. Mais sache que si tu veux en parler, je suis là.", "알겠어. 더 묻지 않을게. 하지만 얘기하고 싶으면 내가 여기 있다는 걸 알아 둬."),
(L, "Merci. C'est... Merci.", "고마워. 정말... 고마워."),
(None, "Un petit silence. Léa tourne sa cuillère dans son thé. Antoine regarde la rue par la fenêtre.", "짧은 침묵. 레아가 차를 숟가락으로 젓는다. 앙투안은 창밖의 거리를 바라본다."),
(A, "Regarde, en face. C'est Gaston qui nous observe depuis la boutique.", "봐, 맞은편. 가스통이 가게에서 우리를 지켜보고 있어."),
(L, "(se retourne) C'est vrai ! Il est derrière la vitrine, avec une bouteille à la main.", "(돌아본다) 정말! 진열창 뒤에서 병을 들고 있네."),
(A, "Il fait semblant de ranger. Mais il nous regarde.", "정리하는 척하고 있지만 우리를 보고 있어."),
(L, "Il agite la main. Je lui fais un signe ?", "손을 흔드네. 나도 손 흔들까?"),
(A, "Pas question. Sinon il va nous prendre pour un vieux couple.", "절대 안 돼. 안 그러면 우리를 오래된 부부로 볼 거야."),
(L, "Nous ne sommes pas un vieux couple.", "우리는 오래된 부부가 아니야."),
(A, "Non. Pas encore.", "아니지. 아직은."),
(L, "(rit) Antoine !", "(웃으며) 앙투안!"),
(A, "Je plaisante. Presque.", "농담이야. 거의."),
(L, "Bon, parlons d'avenir. Qu'est-ce que tu vas faire cette semaine ?", "자, 앞날 이야기를 하자. 이번 주에 뭐 할 거야?"),
(A, "Demain, je vais passer un conseil de classe de trois heures. Mardi, je vais corriger les copies. Mercredi... je vais peut-être aller au cinéma.", "내일은 세 시간짜리 학급 회의가 있어. 화요일엔 채점할 거고. 수요일엔... 영화관에 갈지도 몰라."),
(L, "Au cinéma ? Tu vas voir quoi ?", "영화관? 뭐 보러 가?"),
(A, "Un film sur la guerre de Cent Ans. Je sais, c'est un peu professionnel.", "백년 전쟁에 관한 영화. 알아, 좀 직업병 같지."),
(L, "Un peu ? Tu es incorrigible.", "조금? 넌 못 말려."),
(A, "Et toi ? Quels sont tes plans ?", "너는? 계획이 뭐야?"),
(L, "Je vais finir le logo du chocolatier cette semaine. Je vais aussi essayer de dessiner quelques idées pour la boutique de Gaston.", "이번 주에 초콜릿 가게 로고를 끝낼 거야. 그리고 가스통 가게를 위한 아이디어도 몇 개 그려 볼 거고."),
(A, "Il va être fou de joie.", "가스통이 기뻐서 날뛰겠다."),
(L, "Je vais lui faire trois propositions : une classique, une moderne, une... un peu folle.", "세 가지 제안을 할 거야. 고전적인 거, 현대적인 거, 그리고... 조금 미친 거."),
(A, "Je parie qu'il va choisir la folle.", "그는 미친 걸 고를 거라고 장담해."),
(L, "Moi aussi. C'est pour ça que je commence par celle-là.", "나도 그래. 그래서 그것부터 시작하는 거야."),
(S, "Pardon, mesdames-messieurs. Je peux vous débarrasser ?", "실례합니다. 치워 드려도 될까요?"),
(A, "Oui, merci. L'addition, s'il vous plaît.", "네, 감사합니다. 계산서 부탁합니다."),
(L, "Non, non. Cette fois, c'est moi. Tu m'as invitée, mais je paie le thé.", "아니, 아니야. 이번엔 내가 낼게. 네가 초대했지만 차는 내가 살게."),
(A, "Léa, je t'ai invitée. Ce n'est pas une discussion.", "레아, 내가 초대했어. 토론할 문제가 아니야."),
(L, "On fait moitié-moitié. C'est la règle des indépendants.", "반반으로 하자. 프리랜서의 규칙이야."),
(A, "Très bien. Moitié-moitié. Mais c'est moi qui laisse le pourboire.", "좋아. 반반. 하지만 팁은 내가 남길게."),
(S, "Cela fait sept euros quarante, monsieur.", "7유로 40센트입니다, 선생님."),
(None, "Ils paient. Antoine laisse une pièce sur la table. Ils sortent sur le trottoir, au soleil.", "두 사람이 계산한다. 앙투안이 테이블 위에 동전 하나를 남긴다. 둘은 햇살 아래 인도로 나온다."),
(A, "Léa, une dernière chose. Pour le parapluie... enfin, pour des raisons logistiques, est-ce que je peux avoir ton numéro de téléphone ?", "레아, 마지막으로 하나. 우산 때문에... 아니, 물류상의 이유로 네 전화번호를 알 수 있을까?"),
(L, "Pour des raisons logistiques ?", "물류상의 이유로?"),
(A, "Si tu oublies encore ton parapluie, je pourrai te prévenir directement.", "또 우산을 두고 가면 직접 알려 줄 수 있잖아."),
(L, "Très bien. Donne-moi ton téléphone, je vais écrire mon numéro.", "좋아. 전화기 줘, 내 번호를 적을게."),
(None, "Elle tape son numéro sur l'écran d'Antoine et lui rend le téléphone.", "그녀가 앙투안의 화면에 번호를 입력하고 전화기를 돌려준다."),
(L, "Voilà. Mais ne m'envoie pas de messages à trois heures du matin.", "자. 하지만 새벽 3시에 메시지는 보내지 마."),
(A, "Je dors à vingt-deux heures. Je suis un professeur sérieux.", "난 밤 10시에 자. 성실한 교사라서."),
(L, "Alors à bientôt, Antoine. Merci pour le thé... et pour le reste.", "그럼 또 봐, 앙투안. 차 고마워... 그리고 나머지도."),
(A, "Le reste ?", "나머지?"),
(L, "L'après-midi. L'histoire de ta mère. Les cafés qui ont des noms.", "오후 시간. 어머니 이야기. 이름이 있는 커피들."),
(A, "Merci à toi de m'avoir écouté. À bientôt, Léa.", "내 얘기를 들어줘서 고마워. 또 봐, 레아."),
(L, "Et ne raconte rien à Gaston. Il va inventer toute une histoire.", "그리고 가스통에게는 아무 얘기도 하지 마. 이야기를 통째로 지어낼 테니까."),
(A, "Trop tard. Regarde sa vitrine : il a déjà tout inventé.", "너무 늦었어. 저 진열창 좀 봐. 이미 다 지어냈다고."),
]

VOCAB = [
("A2","Qu'est-ce que je vous sers ?","뭘 드릴까요?","카페 종업원이 주문을 받는 표준 문장"),
("A2","un thé à la menthe / un verre d'eau","민트차 / 물 한 잔","카페에서 흔히 하는 주문"),
("A2","un café noisette / un crème / un allongé / un serré","에스프레소에 우유를 약간 / 우유 커피 / 물을 더 넣은 커피 / 진한 커피","프랑스 카페 메뉴 표현"),
("A2","L'addition, s'il vous plaît.","계산서 부탁합니다.","카페·식당에서 계산을 요청"),
("A2","un pourboire","팁","프랑스에서는 서비스료 포함이지만 잔돈을 남기는 관습이 있음"),
("A2","en avance / à l'heure / en retard","일찍 / 정시에 / 늦게","시간 약속의 3가지 표현"),
("B1","un habitué / un bénévole","단골 / 자원봉사자","« Tu es un habitué ? »"),
("B1","taciturne / infatigable / fauché","과묵한 / 지칠 줄 모르는 / 빈털터리인","사람 묘사의 형용사. fauché는 구어"),
("B1","un conteur / une anecdote","이야기꾼 / 일화","교사·작가에게 자주 쓰는 표현"),
("B1","une proposition (de travail)","(일) 제안","« Une proposition de travail. » 레아의 비밀 단서"),
("B1","pour des raisons logistiques","물류(실무)상의 이유로","핑계를 우아하게 포장하는 농담조 표현"),
("B1","moitié-moitié","반반","계산을 나눌 때. « On fait moitié-moitié. »"),
("B2","un conseil de classe","학급 회의(성적 회의)","프랑스 교사들이 학기마다 여는 회의"),
("B2","la guerre de Cent Ans","백년 전쟁","14~15세기 프랑스·영국 전쟁. 역사 교사의 관심사"),
("B2","débarrasser (la table)","(테이블을) 치우다","« Je peux vous débarrasser ? »"),
("B2","un vieux couple","오래된 부부","애정 섞인 놀림에 자주 사용"),
("B2","la raisonnable de la famille","집안의 이성적인 사람","la/le + 형용사로 역할을 지칭"),
("B2","parier","내기하다, 확신하다","« Je parie qu'il va choisir la folle. »"),
("B2","fou de joie","기뻐 날뛰는","« Il va être fou de joie. »"),
("C1","Ce n'est pas une discussion.","토론할 문제가 아니야.","상대의 반론을 일축하는 단호한 표현"),
("C1","Fais ce qui te rend vivant.","널 살아 있게 하는 것을 해라.","어머니의 말씀으로 이야기의 주제문"),
("C1","Tu n'es pas l'excuse. Tu es la raison.","넌 핑계가 아니라 이유야.","관계의 은근한 고백. excuse vs raison 대비"),
("C1","Pas encore.","아직은 (아니야).","암시적 호감 표현. '언젠가'의 가능성을 열어 둠"),
("C1","Je n'insiste pas.","더 묻지 않을게.","사생활을 존중하는 정중한 표현"),
]

GRAM = [
("A2","근접미래 aller + 동사원형",
 "« Qu'est-ce que tu vas faire cette semaine ? » « Je vais finir le logo. » « Il va être fou de joie. » 가까운 미래·확실한 계획을 나타낸다. 부정: « Je ne vais pas travailler. »"),
("A2","주문할 때의 조건법·현재",
 "« Je voudrais un thé, s'il vous plaît. » 조건법 vouloir로 정중하게 주문한다. « Je prendrais… », « Pourriez-vous… ? »도 가능."),
("B1","단순미래의 형태와 용법",
 "« Je te la montrerai. » « Je pourrai te prévenir. » « Je serai heureux. » 규칙 동사는 부정사 + ai, as, a, ons, ez, ont. être → serai, avoir → aurai, aller → irai, pouvoir → pourrai, voir → verrai."),
("B1","depuis / il y a / ça fait",
 "« Elle a pris sa retraite il y a deux ans. » « C'était il y a vingt ans. » il y a + 기간 = ~ 전에. 현재까지 이어지는 기간: « Il travaille ici depuis dix ans. » / « Ça fait dix ans qu'il travaille ici. »"),
("B1","의무·필요·금지의 부정: ne pas être obligé de",
 "« Ne m'envoie pas de messages. » 부정 명령법: ne + 동사 + pas. 단순 부정 명령은 « N'insiste pas. » (tu). « Ne vous excusez pas. » (vous)."),
("B2","tout / toute / tous / toutes",
 "« tout l'immeuble », « toute la journée », « tous mes élèves », « toutes les chaises ». tout는 명사의 성·수에 일치하는 형용사. 부사로도 쓰인다: « tout de suite », « tout petit ». tous의 발음: 형용사는 [tu], 대명사는 [tus]."),
("B2","접속법을 요구하는 구문 « j'espère que » 와 « sache que »",
 "« J'espère. » espérer que + 직설법 (접속법 아님). « Mais sache que si tu veux en parler, je suis là. » sache = savoir의 명령법(접속법 형태). 관용적으로 '알아 둬'."),
("C1","c'est + 이유/원인 vs excuse: 부정 대비 구문",
 "« Tu n'es pas l'excuse. Tu es la raison. » ne … pas A, mais B 구조의 변형: 부정 + 긍정을 병치해 강한 대비를 만든다. 고백·강조에 자주 쓰이는 수사 구조."),
]

CULTURE = [
("프랑스 카페 문화와 주문",
 "프랑스에서 'un café'는 에스프레소를 뜻한다. 'un noisette'(우유 약간), 'un crème'(우유 많이), 'un allongé'(물 많이)로 세분된다. 점심시간 이후 카푸치노는 흔치 않다. 테라스 자리에 앉는 것이 가장 인기 있고, 팁은 의무가 아니며 잔돈을 남기는 정도이다."),
("프랑스의 선생님들: instituteur vs professeur",
 "초등학교 교사는 예전에 'instituteur', 지금은 'professeur des écoles'라 부른다. 중·고등학교 교사는 'professeur'이며 CAPES·agrégation 시험을 통과해야 한다. 앙투안의 어머니가 institutrice(초등 교사)였다는 설정은 세대 감각을 반영한다."),
("프랑스 학교의 conseil de classe",
 "학기마다 열리는 '학급 회의'는 교사·학부모 대표·학생 대표가 학생들의 성적과 태도를 논의하는 공식 회의로, 교사 업무 부담 중 하나로 꼽힌다."),
]

META = dict(part=1, ep=9, part_label="제1부 첫 잔 · Premier verre", title_fr="Un café en face", title_ko="맞은편 카페에서",
 place="카페 Le Moulin Gris (La Cave des Abbesses 맞은편) · 5월 중순 일요일 15시",
 chars="Léa · Antoine · Le serveur (카페 종업원) · Gaston (창 너머 등장)",
 wine="(와인 없음) 카페 음료: thé à la menthe, café noisette",
 focus="카페 주문, 직업·가족 묘사, 근접미래 aller + 동사원형, 단순미래, il y a / depuis",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제10화 « Rendez-vous manqué » : 처음으로 약속을 잡은 토요일. 길이 엇갈리고 메시지가 꼬이는 하루.")
