# -*- coding: utf-8 -*-
G, L, A, T, M = "Gaston", "Léa", "Antoine", "Un touriste", "Un musicien"
SRV = "La serveuse"
D = [
(None, "Samedi, fin mai, 14 h 40. Trois jours plus tôt, Antoine et Léa ont décidé de faire une promenade jusqu'au Sacré-Cœur. Léa vérifie son téléphone dans la rue des Abbesses. Un message d'Antoine vient d'arriver.", "5월 말 토요일 오후 2시 40분. 사흘 전, 앙투안과 레아는 사크레쾨르까지 산책하기로 했다. 레아가 아베스 거리에서 휴대전화를 확인한다. 앙투안의 메시지가 막 도착했다."),
(A, "(SMS) Salut Léa ! On se retrouve à quinze heures devant les marches du Sacré-Cœur ? Je prends les devants, je serai là un peu avant.", "(문자) 안녕 레아! 3시에 사크레쾨르 계단 앞에서 만날까? 내가 먼저 가 있을게, 조금 일찍 도착할 거야."),
(L, "(SMS) Parfait ! Je suis en route. J'arrive dans un quart d'heure.", "(문자) 좋아! 가는 중이야. 십오 분 뒤에 도착해."),
(A, "(SMS) Super. Je t'attends en haut, près de la terrasse.", "(문자) 좋아. 위쪽 테라스 근처에서 기다릴게."),
(L, "(SMS) En haut ? Moi, je pensais au pied des marches, près du manège. Tu es où, exactement ?", "(문자) 위쪽? 난 계단 아래, 회전목마 근처인 줄 알았어. 정확히 어디야?"),
(A, "(SMS) Au sommet, devant la basilique. On voit tout Paris d'ici.", "(문자) 꼭대기, 대성당 앞이야. 여기서 파리 전체가 보여."),
(L, "(SMS) Mais « devant les marches », c'est en bas ! Les marches sont en bas !", "(문자) 하지만 '계단 앞'이면 아래잖아! 계단은 아래에 있잖아!"),
(A, "(SMS) Les marches du haut ! Celles qui mènent à la basilique !", "(문자) 위쪽 계단! 대성당으로 올라가는 계단 말이야!"),
(L, "(SMS) Il y a trois escaliers, Antoine. Lequel ?", "(문자) 계단이 세 개야, 앙투안. 어느 거?"),
(A, "(SMS) Celui avec le grand drapeau et les touristes qui prennent des photos.", "(문자) 큰 깃발이 있고 관광객들이 사진 찍는 곳."),
(L, "(SMS) Ça ne m'aide pas : il y a des touristes partout.", "(문자) 도움이 안 돼. 어디나 관광객이 있잖아."),
(None, "Léa lève les yeux vers la butte, où se dresse la basilique blanche. Elle soupire.", "레아가 하얀 대성당이 서 있는 언덕을 올려다본다. 한숨을 쉰다."),
(L, "(à elle-même) Allons-y, montons. Au pire, je ferai de l'exercice.", "(혼잣말로) 가자, 올라가자. 최악의 경우 운동이라도 하는 거지."),
(L, "(SMS) D'accord, je monte. Reste où tu es, ne bouge pas !", "(문자) 알겠어, 올라갈게. 거기 있어, 움직이지 마!"),
(A, "(SMS) Je ne bouge pas. Je suis à côté d'un musicien qui joue de l'accordéon.", "(문자) 안 움직여. 아코디언 켜는 음악가 옆에 있어."),
(None, "Elle monte les marches. Au bout de dix minutes, essoufflée, elle atteint le sommet. Un musicien joue de l'accordéon devant la basilique.", "그녀가 계단을 오른다. 십 분 뒤 숨을 헐떡이며 꼭대기에 닿는다. 대성당 앞에서 음악가가 아코디언을 켜고 있다."),
(L, "(au musicien) Pardon, monsieur, vous n'avez pas vu un grand brun avec un sac en toile ? Il est professeur d'histoire.", "(음악가에게) 실례합니다, 천 가방을 멘 키 큰 갈색 머리 남자 못 보셨어요? 역사 선생님이에요."),
(M, "Un professeur ? Non, mademoiselle. Ici, je ne vois que des touristes. Mais il y avait un monsieur, tout à l'heure, qui m'a demandé l'heure trois fois.", "선생님이요? 아뇨, 아가씨. 여기선 관광객만 보여요. 그런데 아까 어떤 분이 세 번이나 시간을 물어봤어요."),
(L, "C'est lui. Il est parti où ?", "그 사람이에요. 어디로 갔어요?"),
(M, "Je crois qu'il est descendu par l'autre côté, par l'escalier de gauche.", "다른 쪽, 왼쪽 계단으로 내려간 것 같아요."),
(L, "Il est descendu ? Mais il m'a dit de ne pas bouger !", "내려갔다고요? 하지만 움직이지 말라고 했는데!"),
(M, "Je crois qu'il a dit la même chose à son téléphone.", "그분도 전화기에다 똑같이 말한 것 같아요."),
(L, "(sort son téléphone) Antoine ? Où es-tu ?", "(전화기를 꺼내며) 앙투안? 어디야?"),
(None, "L'écran de Léa clignote et s'éteint. Elle appuie sur le bouton. Rien.", "레아의 화면이 깜박이더니 꺼진다. 버튼을 눌러 본다. 아무 반응이 없다."),
(L, "Non, non, non ! Plus de batterie ! Pas maintenant !", "안 돼, 안 돼, 안 돼! 배터리가 없어! 지금은 안 돼!"),
(M, "C'est la loi de Murphy, mademoiselle. Le téléphone s'éteint toujours au pire moment.", "머피의 법칙이죠, 아가씨. 전화기는 늘 최악의 순간에 꺼져요."),
(L, "Merci pour la leçon de philosophie, monsieur. Au revoir !", "철학 수업 고맙습니다, 선생님. 안녕히 계세요!"),
(None, "Pendant ce temps, Antoine est arrivé au pied de l'escalier. Il regarde autour de lui, inquiet.", "그 사이 앙투안은 계단 아래에 도착했다. 걱정스러운 얼굴로 주위를 둘러본다."),
(A, "(au téléphone) Léa ? Léa, tu m'entends ? Allô ?", "(전화로) 레아? 레아, 들려? 여보세요?"),
(None, "La messagerie vocale répond : « Le correspondant que vous essayez de joindre n'est pas disponible. »", "음성 사서함이 응답한다. '걸고 계신 번호는 현재 연결할 수 없습니다.'"),
(A, "Elle est partie où ? Elle est montée ? Elle est descendue ? Je ne comprends plus rien.", "어디로 갔지? 올라갔나? 내려갔나? 도무지 모르겠네."),
(T, "Excusez-moi, monsieur. Do you speak English ? Ah, pardon. Vous parlez français ?", "실례합니다, 선생님. 영어 하세요? 아, 죄송해요. 프랑스어 하세요?"),
(A, "Oui, bien sûr. Je peux vous aider ?", "네, 물론이죠. 도와드릴까요?"),
(T, "Nous cherchons le funiculaire. Pour monter à la basilique. Vous savez où il se trouve ?", "푸니쿨라를 찾고 있어요. 대성당으로 올라가는 거요. 어디 있는지 아세요?"),
(A, "Oui. Vous continuez tout droit, au bout de la place vous tournez à gauche, et vous le voyez.", "네. 곧장 가시다가 광장 끝에서 왼쪽으로 돌면 보여요."),
(T, "Merci beaucoup. Vous avez l'air triste. Vous avez perdu quelqu'un ?", "정말 감사합니다. 슬퍼 보이시네요. 누굴 잃어버리셨어요?"),
(A, "Oui. Une amie. Nous avions rendez-vous au Sacré-Cœur, mais nous nous sommes ratés.", "네. 친구요. 사크레쾨르에서 만나기로 했는데 엇갈렸어요."),
(T, "Vous voulez utiliser mon téléphone ? Pour l'appeler ?", "제 전화기를 쓰시겠어요? 그분께 전화하시게요?"),
(A, "C'est très gentil. Mais son téléphone est éteint, je crois.", "정말 친절하시네요. 하지만 그분 전화기는 꺼진 것 같아요."),
(T, "Alors envoyez-lui un message sur le vôtre. Si elle le rallume, elle le verra.", "그럼 본인 전화기로 메시지를 보내세요. 다시 켜면 볼 거예요."),
(A, "Bonne idée. Merci, monsieur.", "좋은 생각이네요. 감사합니다."),
(A, "(SMS) Léa, je suis en bas. Je redescends parce que je pensais que tu avais pris le funiculaire. Si tu lis ça, attends-moi au manège.", "(문자) 레아, 나 아래야. 네가 푸니쿨라를 탔을 줄 알고 내려왔어. 이 메시지를 보면 회전목마에서 기다려."),
(None, "Léa, au sommet, ne reçoit rien. Elle marche d'un pas pressé jusqu'à l'escalier de gauche.", "꼭대기에 있는 레아는 아무것도 받지 못한다. 그녀는 서둘러 왼쪽 계단으로 걸어간다."),
(L, "Il est descendu par là. Je descends aussi. Je vais le retrouver, j'en suis sûre.", "그가 이쪽으로 내려갔대. 나도 내려갈래. 꼭 찾을 거야."),
(None, "Elle descend, un étage, deux étages. Dans l'escalier voisin, Antoine monte en courant. Ils passent à dix mètres l'un de l'autre sans se voir, séparés par un mur de buissons.", "그녀가 한 층, 두 층 내려간다. 옆 계단에서는 앙투안이 뛰어 올라간다. 둘은 서로 십 미터 거리에서 덤불 벽에 가려 서로를 보지 못한 채 스쳐 지나간다."),
(A, "(à lui-même) Elle est peut-être montée à pied. Je vais voir.", "(혼잣말) 걸어서 올라갔을지도 몰라. 가 봐야겠다."),
(L, "(à elle-même) Il est peut-être redescendu avec le funiculaire. Je vais voir.", "(혼잣말) 푸니쿨라로 내려갔을지도 몰라. 가 봐야겠다."),
(None, "Au sommet, Antoine regarde à droite, à gauche. En bas, Léa attend devant le manège, essoufflée.", "꼭대기에서 앙투안이 좌우를 둘러본다. 아래에서는 레아가 숨을 헐떡이며 회전목마 앞에서 기다린다."),
(L, "Ça fait vingt minutes que je cours dans tout Montmartre. Mon téléphone est mort, ma patience aussi.", "이십 분째 몽마르트르 전체를 뛰어다니고 있어. 전화기도 죽었고 인내심도 죽었어."),
(None, "Un petit garçon sur le manège lui fait un grand signe de la main. Elle lui sourit tristement.", "회전목마를 탄 작은 남자아이가 크게 손을 흔든다. 그녀가 쓸쓸히 미소 짓는다."),
(L, "Bon. Il y a une cabine téléphonique quelque part. Non, il n'y en a plus. Il y a un café. Je vais leur demander de recharger mon téléphone.", "그래. 어딘가 공중전화 부스가 있을 텐데. 아니, 이젠 없지. 카페가 있네. 충전해 달라고 부탁해야겠다."),
(None, "Dans le café, le serveur branche son téléphone derrière le comptoir. Léa attend, les yeux fixés sur l'écran noir.", "카페에서 종업원이 계산대 뒤에서 그녀의 전화기를 충전기에 꽂는다. 레아는 검은 화면에 눈을 고정한 채 기다린다."),
(L, "Allez... allez, allume-toi...", "자... 자, 켜져라..."),
(None, "Le téléphone vibre. Quinze notifications. Le dernier message d'Antoine apparaît.", "전화기가 진동한다. 알림이 열다섯 개. 앙투안의 마지막 메시지가 나타난다."),
(L, "(lit) « Si tu lis ça, attends-moi au manège. » Au manège ! Mais j'y suis !", "(읽는다) '이 메시지를 보면 회전목마에서 기다려.' 회전목마! 난 여기 있는데!"),
(L, "(SMS) Antoine ! Je suis au manège ! Au café juste à côté. Viens !", "(문자) 앙투안! 나 회전목마에 있어! 바로 옆 카페에! 와!"),
(None, "Quelques minutes plus tard, Antoine arrive, rouge, essoufflé, les cheveux en désordre. Léa se lève.", "몇 분 뒤 앙투안이 얼굴이 붉어지고 숨이 찬 채 머리가 헝클어져 도착한다. 레아가 일어선다."),
(A, "Léa ! Dieu merci ! J'ai failli abandonner et rentrer chez moi.", "레아! 다행이다! 포기하고 집에 갈 뻔했어."),
(L, "Antoine ! Je te cherche depuis une heure !", "앙투안! 한 시간째 너를 찾고 있었어!"),
(A, "Moi aussi ! Tu as monté les marches ?", "나도야! 너 계단 올라갔어?"),
(L, "Oui ! Tu m'as dit de monter ! Et toi, tu es redescendu par l'autre côté !", "응! 네가 올라오라고 했잖아! 그런데 너는 반대쪽으로 내려갔고!"),
(A, "Parce que ton téléphone ne répondait pas ! J'ai cru que tu avais pris le funiculaire !", "네 전화기가 안 받아서! 푸니쿨라를 탄 줄 알았어!"),
(L, "Mon téléphone n'avait plus de batterie.", "내 전화기 배터리가 다 나갔었어."),
(A, "Et le mien n'avait plus de patience.", "내 전화기는 인내심이 다 나갔고."),
(L, "(éclate de rire) On est des idiots, Antoine.", "(웃음을 터뜨리며) 우리 바보야, 앙투안."),
(A, "Deux idiots, un malentendu et un funiculaire.", "바보 둘, 오해 하나, 푸니쿨라 하나."),
(L, "Ça ressemble au titre d'un film français.", "프랑스 영화 제목 같다."),
(A, "Un film français où il ne se passe rien, mais où tout le monde parle beaucoup.", "아무 일도 안 일어나지만 모두가 말을 많이 하는 프랑스 영화."),
(L, "Exactement. Avec un accordéoniste en fond sonore.", "정확해. 배경음악으로 아코디언 연주자가 나오고."),
(A, "J'ai demandé l'heure trois fois à ce monsieur. Il m'a regardé avec pitié.", "그 아저씨에게 시간을 세 번이나 물었어. 불쌍하다는 눈으로 쳐다보더라."),
(L, "Je l'ai rencontré aussi. Il a parlé de la loi de Murphy.", "나도 그 사람 만났어. 머피의 법칙 얘기를 하더라."),
(A, "Un philosophe du dimanche.", "일요일의 철학자네."),
(L, "Bon. Je propose qu'on recommence tout. De zéro.", "자. 우리 처음부터 다시 하자. 0에서부터."),
(A, "De zéro ? Mais il est déjà seize heures.", "0에서? 벌써 4시인데."),
(L, "On a toute la soirée. Et je connais un endroit où on ne peut pas se perdre : une crêperie, derrière le manège.", "저녁 내내 시간 있잖아. 그리고 절대 길을 잃을 수 없는 곳을 알아. 회전목마 뒤에 있는 크레프 가게."),
(A, "Une crêperie ?", "크레프 가게?"),
(L, "Oui. Des crêpes, du cidre. Je t'invite, pour me faire pardonner de ton escalade.", "응. 크레프랑 시드르. 네가 한 등반을 사과하는 뜻으로 내가 살게."),
(A, "Je n'ai pas fait d'escalade. J'ai fait un marathon.", "난 등반이 아니라 마라톤을 했어."),
(L, "Alors un marathon mérite un cidre doux.", "그럼 마라톤은 달콤한 시드르를 받을 자격이 있지."),
(A, "Je ne dirais pas non.", "마다하지 않을게."),
(None, "Ils marchent côte à côte vers la crêperie. Le soleil de fin d'après-midi dore les façades de Montmartre.", "둘은 나란히 크레프 가게로 걸어간다. 늦은 오후의 햇빛이 몽마르트르 건물 외벽을 금빛으로 물들인다."),
(L, "Au fait, la prochaine fois, on se donne un lieu précis. Avec une adresse. Ou une photo.", "그건 그렇고 다음에는 정확한 장소를 정하자. 주소랑 함께. 아니면 사진이랑."),
(A, "Ou on met la même application de localisation sur nos téléphones.", "아니면 우리 전화기에 같은 위치 공유 앱을 깔든지."),
(L, "Et si on ne se perdait pas, ça serait ennuyeux, non ?", "그런데 길을 안 잃으면 재미없지 않아?"),
(A, "Tu veux dire qu'il faut qu'on se perde pour mieux se retrouver ?", "잘 만나려면 길을 잃어야 한다는 거야?"),
(L, "Quelque chose comme ça.", "대충 그런 거지."),
(A, "C'est exactement ce que j'enseigne en histoire : les plus grandes rencontres sont souvent des malentendus.", "내가 역사 수업에서 가르치는 바로 그거야. 가장 위대한 만남은 종종 오해에서 시작해."),
(L, "Par exemple ?", "예를 들면?"),
(A, "Christophe Colomb. Il voulait aller en Inde. Il a découvert l'Amérique.", "크리스토퍼 콜럼버스. 인도에 가려 했는데 아메리카를 발견했지."),
(L, "Alors nous, on voulait aller au Sacré-Cœur et on a découvert une crêperie ?", "그럼 우린 사크레쾨르에 가려 했는데 크레프 가게를 발견한 거야?"),
(A, "C'est une très belle découverte.", "아주 멋진 발견이지."),
(L, "Je n'avais jamais comparé ma journée à un voyage de Christophe Colomb.", "내 하루를 콜럼버스의 항해에 견준 건 처음이야."),
(A, "Il y a un début à tout.", "뭐든 시작은 있는 법이지."),
(None, "À la crêperie « La Galette Bleue ». Ils s'installent à une petite table près de la vitre. Une serveuse leur apporte la carte.", "크레프 가게 '라 갈레트 블루'. 두 사람이 유리창 옆 작은 테이블에 앉는다. 종업원이 메뉴판을 가져다준다."),
(L, "Bonjour. Deux galettes complètes et deux bolées de cidre doux, s'il vous plaît.", "안녕하세요. 콩플레트 갈레트 두 개와 달콤한 시드르 두 잔 주세요."),
(SRV, "Très bien. Et pour le dessert, vous voulez déjà commander ?", "알겠습니다. 디저트는 벌써 주문하시겠어요?"),
(A, "Une crêpe au chocolat avec de la chantilly, pour deux.", "초콜릿 크레프에 생크림 얹어서, 둘이 먹을 걸로요."),
(SRV, "Une crêpe pour deux, parfait. Je vous apporte les galettes dans dix minutes.", "둘이 먹을 크레프 하나, 좋습니다. 십 분 뒤에 갈레트를 가져다 드릴게요."),
(L, "Une crêpe pour deux ? Tu partages ton dessert ?", "둘이 먹을 크레프라고? 디저트를 나눠 먹어?"),
(A, "Seulement avec les gens qui me font courir dans tout Montmartre.", "나를 몽마르트르 전체에서 뛰게 만든 사람하고만."),
(L, "Je prends ça pour un compliment.", "칭찬으로 받아들일게."),
(A, "C'en est un. Malgré tout, c'est la meilleure journée du mois.", "칭찬 맞아. 그래도 이번 달 최고의 하루야."),
(L, "Même avec le marathon ?", "마라톤을 했는데도?"),
(A, "Surtout avec le marathon. Sans lui, on n'aurait pas cette crêperie.", "마라톤 덕분에 더더욱. 마라톤이 없었다면 이 크레프 가게도 없었을 거야."),
(None, "Les galettes arrivent, fumantes, avec un œuf au plat au centre.", "갈레트가 김을 모락모락 내며 도착한다. 가운데에는 계란 프라이가 올려져 있다."),
(L, "Elle a l'air délicieuse. Jambon, œuf, fromage. Le comble du luxe.", "맛있어 보여. 햄, 계란, 치즈. 사치의 극치야."),
(A, "Chez moi, le dimanche, ma mère faisait des galettes. Elle disait que c'était le plat des gens heureux.", "우리 집에선 일요일마다 어머니가 갈레트를 만드셨어. 행복한 사람들의 음식이라고 하셨지."),
(L, "Alors mangeons-la avec bonheur.", "그럼 행복하게 먹자."),
(A, "Mangeons-la avec bonheur. (Il goûte.) Elle avait raison.", "행복하게 먹자. (맛본다.) 어머니 말씀이 맞았어."),
(L, "Antoine, tu as un peu de fromage sur le menton.", "앙투안, 턱에 치즈가 조금 묻었어."),
(A, "Où ça ? Ici ?", "어디? 여기?"),
(L, "Non, de l'autre côté. Attends. (Elle lui essuie le menton avec sa serviette.) Voilà.", "아니, 반대쪽. 기다려. (냅킨으로 그의 턱을 닦아 준다.) 됐어."),
(A, "Merci. Dis, samedi prochain, tu es libre ? Il y a le marché des Abbesses le matin. Je t'apprendrai à choisir un fromage.", "고마워. 저기, 다음 주 토요일에 시간 있어? 아침에 아베스 시장이 열려. 치즈 고르는 법을 가르쳐 줄게."),
(L, "Volontiers ! Mais cette fois, on se donne un lieu précis, avec une adresse et une heure.", "좋아! 하지만 이번엔 정확한 장소를 정하자, 주소랑 시간까지."),
(A, "Devant l'église Saint-Jean-l'Évangéliste, place des Abbesses, à neuf heures. Je note, je répète, et je t'envoie un plan par message.", "아베스 광장, 생장 레방젤리스트 성당 앞, 9시. 적어 두고, 다시 말하고, 지도도 메시지로 보내 줄게."),
(L, "Parfait. Et cette fois, je charge mon téléphone avant de partir !", "완벽해. 그리고 이번엔 출발 전에 전화기를 충전해 둘게!"),
(None, "Dehors, Gaston, qui passe par hasard avec son chat en laisse, les aperçoit à travers la vitre. Il s'arrête, sourit et ne dit rien.", "밖에서는 우연히 고양이를 목줄에 묶어 산책시키던 가스통이 유리창 너머로 그들을 발견한다. 걸음을 멈추고 미소만 지을 뿐 아무 말도 하지 않는다."),
]

VOCAB = [
("A2","retrouver / se retrouver","다시 만나다 / (약속하여) 만나다","« On se retrouve à quinze heures ? » 약속 잡을 때 가장 흔한 표현"),
("A2","les marches / un escalier","계단(디딤판) / 계단(전체)","les marches = 한 칸 한 칸, un escalier = 계단 구조 전체"),
("A2","en haut / en bas / au sommet / au pied","위쪽 / 아래쪽 / 정상 / 아래(발치)","« au pied des marches », « au sommet de la butte »"),
("A2","tout droit / à gauche / à droite","곧장 / 왼쪽 / 오른쪽","« Vous continuez tout droit, au bout de la place vous tournez à gauche. »"),
("A2","la batterie / un chargeur","배터리 / 충전기","« Plus de batterie ! » = 배터리 없음"),
("A2","un message / un SMS / appeler / répondre","메시지 / 문자 / 전화하다 / 대답하다","휴대전화 관련 기본 어휘"),
("B1","un manège / un funiculaire","회전목마 / 푸니쿨라(케이블 열차)","몽마르트르의 상징적 장소들"),
("B1","la messagerie vocale","음성 사서함","« Le correspondant … n'est pas disponible. » 자동 안내 멘트"),
("B1","se rater / rater un rendez-vous","서로 엇갈리다 / 약속을 놓치다","rater = (기회·열차 등을) 놓치다"),
("B1","un malentendu","오해, 의사 엇갈림","« Deux idiots, un malentendu et un funiculaire. »"),
("B1","prendre les devants","앞서 가다, 선수를 치다","« Je prends les devants. » 먼저 가서 자리 잡는다는 뜻"),
("B1","être essoufflé(e)","숨이 차다","뛰거나 계단을 오른 뒤 표현"),
("B2","clignoter / s'éteindre / s'allumer","깜박이다 / 꺼지다 / 켜지다","화면·전등에 쓰는 동사"),
("B2","une notification / un correspondant","알림 / 통화 상대","notification = 알림. correspondant = 통화 상대(공식 멘트)"),
("B2","un accordéoniste / un accordéon","아코디언 연주자 / 아코디언","파리 거리 음악의 상징"),
("B2","un buisson / un mur de buissons","덤불 / 덤불 벽","계단 사이의 시야 가림 묘사"),
("B2","l'escalade / un marathon","(암벽) 등반 / 마라톤","« Je n'ai pas fait d'escalade. J'ai fait un marathon. » 과장 유머"),
("B2","un cidre doux","달콤한 시드르(사과주)","브르타뉴 크레프 가게의 대표 음료"),
("C1","la loi de Murphy","머피의 법칙","« Le téléphone s'éteint toujours au pire moment. »"),
("C1","J'ai failli + 동사원형","~할 뻔했다","« J'ai failli abandonner. » 근접 사건을 막 피한 느낌"),
("C1","Il y a un début à tout.","뭐든 시작은 있는 법이다.","새로운 경험을 겸손하게 받아들이는 속담"),
("C1","un philosophe du dimanche","어설픈 철학자(취미로 철학하는 사람)","du dimanche = 아마추어의, 어설픈. peintre du dimanche 등"),
("C1","de zéro","처음부터","« Je propose qu'on recommence de zéro. »"),
("C1","se perdre pour mieux se retrouver","길을 잃어야 더 잘 만난다","중의적 표현. 물리적 길 잃음과 감정적 재발견"),
]

GRAM = [
("A2","의문사 où / quand / comment / pourquoi",
 "« Tu es où, exactement ? » « Elle est partie où ? » « Il est parti où ? » 구어에서는 의문사를 문장 끝에 붙인다. 정식: « Où es-tu ? » (도치) / « Où est-ce que tu es ? »"),
("A2","방향 표현과 현재형 명령",
 "« Continuez tout droit. Tournez à gauche. » « Reste où tu es. » 지시할 때 명령법. « Tu continues tout droit » 처럼 직설법 현재형으로 길을 안내하기도 한다."),
("B1","최근 과거: venir de / avoir failli",
 "« Un message d'Antoine vient d'arriver. » venir de = 방금 ~했다. « J'ai failli abandonner. » avoir failli + inf = 하마터면 ~할 뻔했다 (결과적으로 하지는 않음)."),
("B1","대과거 plus-que-parfait (입문)",
 "« Il m'a dit qu'il avait perdu son téléphone. » « Nous avions rendez-vous. » avoir/être의 반과거 + 과거분사. 과거의 과거(앞선 사건)를 나타낸다."),
("B1","대명동사의 복합과거와 상호 의미",
 "« Nous nous sommes ratés. » « On s'est perdus. » « Ils se sont retrouvés. » être + 과거분사, 주어에 성·수 일치. 이 구조는 '서로'를 뜻하는 상호적 용법."),
("B2","간접의문과 인용: ne pas bouger / ne rien comprendre",
 "« Je ne comprends plus rien. » « Reste où tu es, ne bouge pas ! » ne + 동사 + plus + rien: 더 이상 아무것도. 부정어 조합: ne … plus rien / ne … jamais rien."),
("B2","접속법: je propose que / il faut que",
 "« Je propose qu'on recommence de zéro. » « Il faut qu'on se perde pour mieux se retrouver. » 제안·필요 표현 뒤에는 접속법 현재. recommence, perde 모두 접속법."),
("C1","si의 가정(반과거 + 조건법)",
 "« Et si on ne se perdait pas, ça serait ennuyeux, non ? » si + 반과거, 조건법 현재. 현재 사실의 반대 가정. « Si je ne savais pas, je demanderais. »"),
]

CULTURE = [
("몽마르트르의 Sacré-Cœur와 푸니쿨라",
 "사크레쾨르 대성당은 몽마르트르 언덕 꼭대기에 있고, 아래의 square Louise-Michel에서 계단 또는 푸니쿨라로 오른다. 계단이 여러 개라 관광객이 길을 잃기 쉽다. 푸니쿨라는 파리 지하철 티켓으로 탈 수 있다."),
("프랑스 크레프(crêpe)와 시드르",
 "크레프는 브르타뉴 지방의 대표 음식이다. 짭짤한 메밀 갈레트(galette)와 달콤한 밀가루 크레프로 나뉘며, 사과로 만든 시드르(cidre)와 함께 먹는다. 파리 몽파르나스·몽마르트르에는 브르타뉴식 크레프 가게가 많다."),
("약속 장소를 정하는 법",
 "프랑스에서는 'devant les marches' 같은 모호한 표현 대신 '지하철역 출구', '카페 이름', '주소'로 약속을 잡는 것이 안전하다. 이 화의 오해는 이런 일상의 실수를 코믹하게 보여 준다."),
]

META = dict(part=1, ep=10, part_label="제1부 첫 잔 · Premier verre", title_fr="Rendez-vous manqué", title_ko="엇갈린 약속",
 place="몽마르트르 사크레쾨르 언덕과 계단 · 5월 말 토요일 14시 40분",
 chars="Léa · Antoine · Un musicien (아코디언 연주자) · Un touriste (관광객) · Gaston (마지막 장면 등장)",
 wine="(와인 없음) cidre doux (사과주)",
 focus="의문사, 길 안내, 근접과거 venir de/avoir failli, 대과거, 대명동사 복합과거, 문자·전화 표현",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제11화 « Le marché des Abbesses » : 둘이 함께 장을 보는 토요일 아침. 치즈와 와인의 페어링, 그리고 한 사람이 던진 뜻밖의 저녁 초대.")
