# -*- coding: utf-8 -*-
G, L, A = "Gaston", "Léa", "Antoine"
F, P = "La fromagère", "Le primeur"
AP = "L'apiculteur"
D = [
(None, "Samedi, début juin, 9 h. La place des Abbesses s'anime : les étals se remplissent de fruits, de fleurs et de fromages. Devant l'église Saint-Jean-l'Évangéliste, Léa attend, son téléphone chargé à cent pour cent à la main.", "6월 초 토요일 오전 9시. 아베스 광장이 활기를 띤다. 가판대에는 과일과 꽃과 치즈가 가득하다. 생장 레방젤리스트 성당 앞에서 레아가 100퍼센트 충전한 휴대전화를 손에 들고 기다린다."),
(A, "Bonjour, Léa ! Neuf heures pile. Tu as chargé ton téléphone, à ce que je vois.", "안녕, 레아! 9시 정각이네. 전화기는 충전했나 보네."),
(L, "Cent pour cent. Et j'ai même emporté un chargeur portable. Je suis devenue paranoïaque.", "100퍼센트야. 휴대용 충전기까지 챙겼어. 편집증 환자가 됐나 봐."),
(A, "Une paranoïaque heureuse, j'espère.", "행복한 편집증 환자이길 바라."),
(L, "Très. J'adore les marchés. À Lyon, j'allais chaque samedi à la Croix-Rousse avec ma mère.", "아주 행복해. 난 시장을 좋아해. 리옹에서는 토요일마다 어머니와 크루아루스 시장에 갔거든."),
(A, "Ici, c'est plus petit, mais il y a de très bons producteurs. Viens, on commence par le fromage.", "여기는 더 작지만 훌륭한 생산자들이 있어. 이리 와, 치즈부터 시작하자."),
(None, "Ils s'arrêtent devant un étal où s'alignent des dizaines de fromages sous des cloches de verre. La fromagère, une dame aux cheveux gris, les accueille avec un grand sourire.", "두 사람이 유리 덮개 아래 수십 종의 치즈가 놓인 가판대 앞에 선다. 회색 머리의 치즈 가게 주인이 환한 미소로 맞이한다."),
(F, "Bonjour, Antoine ! Ça faisait un moment. Et vous êtes... ?", "안녕, 앙투안! 오랜만이네. 그리고 이분은... ?"),
(A, "Madame Durand, je vous présente Léa. Léa, madame Durand, la reine du fromage depuis trente ans.", "뒤랑 부인, 레아를 소개할게요. 레아, 이쪽은 뒤랑 부인이야. 30년 동안 치즈의 여왕이지."),
(F, "Je suis surtout la reine de la patience. Bonjour, mademoiselle ! Alors, qu'est-ce qui vous ferait plaisir ?", "저는 인내심의 여왕일 뿐이죠. 안녕하세요, 아가씨! 그럼 무엇이 마음에 드시겠어요?"),
(L, "Je ne sais pas du tout. Je connais le camembert, le brie, le roquefort... et c'est tout.", "전혀 모르겠어요. 카망베르, 브리, 로크포르는 알아요... 그게 다예요."),
(F, "C'est déjà un bon début. Mais il y a plus de mille fromages en France.", "그것도 좋은 출발이죠. 하지만 프랑스에는 천 가지가 넘는 치즈가 있어요."),
(L, "Mille ? Comment on peut en choisir un seul ?", "천 가지요? 어떻게 하나만 고를 수 있죠?"),
(F, "On n'en choisit pas un seul. On en choisit trois ou quatre, de textures différentes. Un cru, un doux, un fort, un surprise.", "하나만 고르지 않아요. 질감이 다른 세 개나 네 개를 고르죠. 순한 것, 부드러운 것, 강한 것, 놀라운 것."),
(A, "C'est ma règle d'or : un chèvre, un pâte pressée, une croûte fleurie, un bleu.", "내 황금률이야. 염소 치즈, 압착 경질 치즈, 흰곰팡이 치즈, 푸른곰팡이 치즈."),
(L, "Une croûte fleurie ? Les fromages ont des fleurs ?", "크루트 플뢰리? 치즈에 꽃이 있어요?"),
(F, "Pas vraiment des fleurs, mais un duvet blanc : le camembert, le brie. On dit qu'il « fleurit » parce que la moisissure ressemble à du velours.", "정확히는 꽃이 아니라 하얀 솜털 같은 거예요. 카망베르, 브리 같은. 곰팡이가 벨벳 같아서 '꽃핀다'고 해요."),
(L, "Du velours de moisissure. C'est étonnamment poétique.", "곰팡이 벨벳이라니. 놀랍게도 시적이네요."),
(F, "Goûtez ce petit crottin de Chavignol. C'est un chèvre de la Loire, très sec, un peu noisette.", "이 작은 크로탱 드 샤비뇰을 맛보세요. 루아르의 염소 치즈인데 아주 단단하고 약간 헤이즐넛 맛이 나요."),
(L, "(goûte) Oh ! C'est très concentré. Il y a quelque chose de salé, et puis une sorte de douceur à la fin.", "(맛본다) 오! 아주 응축된 맛이에요. 짠맛이 있고, 끝에 일종의 부드러움이 있어요."),
(A, "Et avec quel vin ? Léa, devine.", "그럼 어떤 와인이랑? 레아, 맞혀 봐."),
(L, "Un vin blanc ? Sec, frais, minéral ?", "화이트 와인? 드라이하고 상큼하고 미네랄한?"),
(A, "Un Sancerre. Exactement. Le chèvre et le sancerre viennent du même village, et ils s'entendent parfaitement.", "상세르야. 정확해. 염소 치즈와 상세르는 같은 마을 출신이라 완벽하게 어울려."),
(L, "C'est comme deux voisins qui se connaissent depuis toujours.", "평생 서로 알고 지낸 이웃 같네."),
(A, "Exactement. Dans ce pays, les meilleurs mariages sont les mariages de terroir.", "맞아. 이 나라에서 가장 좋은 결혼은 테루아르끼리의 결혼이야."),
(F, "Maintenant, un comté de dix-huit mois. Une pâte pressée, un peu sucrée, avec des petits cristaux de sel.", "이제 18개월 숙성 콩테예요. 압착 경질 치즈이고 약간 달콤하고 작은 소금 결정이 있어요."),
(L, "(goûte) Hmm. Ça fond sur la langue, c'est presque... du caramel.", "(맛본다) 음. 혀 위에서 녹아요, 거의... 캐러멜이에요."),
(F, "Vous avez bon palais, mademoiselle.", "미각이 좋으세요, 아가씨."),
(A, "Elle a surtout bon cœur. Elle finit toujours par aimer tout ce qu'on lui fait goûter.", "마음이 좋은 거죠. 맛보게 해 주는 건 결국 다 좋아하거든요."),
(L, "Je n'aime pas tout. Je n'aime pas les huîtres, par exemple.", "다 좋아하는 건 아니야. 예를 들어 굴은 안 좋아해."),
(A, "Tu n'as jamais essayé.", "먹어 본 적도 없잖아."),
(L, "Justement. Je préfère les aimer en théorie.", "그러니까. 이론적으로만 좋아하는 게 좋아."),
(F, "Je vous mets un morceau de chaque ? Deux cents grammes de comté, un crottin, et un morceau de brie de Meaux ?", "하나씩 담아 드릴까요? 콩텍 200그램, 크로탱 하나, 그리고 브리 드 모 한 조각?"),
(L, "Oui, s'il vous plaît. Et... un bleu, pour compléter la règle d'or.", "네, 부탁해요. 그리고... 황금률을 채우게 푸른곰팡이 치즈도 하나요."),
(F, "Un bleu d'Auvergne ? Doux et crémeux, pour débuter.", "블뢰 도베르뉴는 어떠세요? 부드럽고 크리미해서 입문용이에요."),
(L, "Parfait. Cent cinquante grammes, s'il vous plaît.", "좋아요. 150그램 부탁합니다."),
(F, "Je vous les emballe séparément, pour que les odeurs ne se mélangent pas.", "냄새가 섞이지 않도록 따로 포장해 드릴게요."),
(A, "C'est un bon conseil. Une fois, j'ai mis un roquefort et un brie dans le même sac. Le frigo a senti le fromage pendant une semaine.", "좋은 조언이에요. 한번은 로크포르와 브리를 한 봉지에 넣었다가 냉장고에서 일주일 동안 치즈 냄새가 났어요."),
(L, "Tu es un génie du quotidien.", "넌 일상의 천재야."),
(F, "Voilà. Ça fait vingt-quatre euros cinquante. Pour vous, ce sera vingt-quatre.", "자, 24유로 50센트예요. 두 분께는 24유로로 할게요."),
(A, "Je paie. Léa, tu m'as invité au café. Maintenant, c'est mon tour.", "내가 낼게. 레아, 네가 카페를 샀잖아. 이번엔 내 차례야."),
(L, "D'accord. Mais pour le pain, c'est moi.", "알겠어. 하지만 빵은 내가 살게."),
(None, "En chemin, ils passent devant un petit stand de miel : des pots de toutes les couleurs, alignés comme des vitraux.", "가는 길에 작은 꿀 가판대 앞을 지난다. 갖가지 색깔의 꿀단지가 스테인드글라스처럼 줄지어 있다."),
(L, "Regarde, un stand de miel ! Lavande, acacia, châtaignier, sapin... Quelle variété !", "봐, 꿀 가판대야! 라벤더, 아카시아, 밤, 전나무... 종류가 정말 다양해!"),
(AP, "Bonjour ! Goûtez, c'est de ma production. Mes abeilles travaillent à Montmartre, sur les toits.", "안녕하세요! 맛보세요, 제가 직접 만든 거예요. 제 꿀벌들은 몽마르트르 지붕 위에서 일해요."),
(L, "Des abeilles à Montmartre ? Sur les toits de Paris ?", "몽마르트르에 꿀벌이요? 파리 지붕 위에서요?"),
(AP, "Bien sûr. Les abeilles de ville font un miel plus complexe que celles de la campagne : il y a plus de fleurs différentes.", "물론이죠. 도시 꿀벌은 시골 꿀벌보다 더 복합적인 꿀을 만들어요. 다양한 꽃이 더 많거든요."),
(A, "Je ne le savais pas. Une leçon d'histoire naturelle gratuite.", "몰랐어. 무료 자연사 수업이네."),
(L, "Quel miel est le meilleur avec le chèvre ?", "염소 치즈와 가장 잘 어울리는 꿀은 어떤 건가요?"),
(AP, "Le miel de châtaignier : puissant, un peu amer. Il adore le chèvre sec.", "밤꿀이요. 진하고 약간 쌉쌀해요. 단단한 염소 치즈와 아주 잘 어울려요."),
(L, "Le miel peut être amer ?", "꿀이 쓸 수도 있어요?"),
(AP, "Oui, c'est ce qui le rend intéressant. Comme les gens, mademoiselle.", "네, 그게 흥미롭게 만들죠. 사람처럼요, 아가씨."),
(A, "Une philosophie de marché.", "시장표 철학이네."),
(L, "Je prends un petit pot. C'est combien ?", "작은 병 하나 살게요. 얼마예요?"),
(AP, "Sept euros. Et la philosophie est offerte.", "7유로입니다. 철학은 서비스예요."),
(None, "Ils repartent avec leurs sachets. À quelques pas, une voix familière les interpelle.", "두 사람이 봉지를 들고 다시 걸음을 옮긴다. 몇 걸음 떨어진 곳에서 익숙한 목소리가 그들을 부른다."),
(G, "Ah, les amoureux du samedi matin !", "아, 토요일 아침의 연인들이네!"),
(A, "Gaston ! Qu'est-ce que tu fais là ?", "가스통! 여기서 뭐 해?"),
(G, "Je fais mon marché, comme tous les samedis, depuis trente-cinq ans. Je prends deux baguettes, une tarte aux pommes et six œufs frais.", "35년째 매주 토요일마다 하는 장보기야. 바게트 두 개, 사과 타르트, 그리고 신선한 계란 여섯 개를 사지."),
(L, "Bonjour, Gaston. Nous ne sommes pas des amoureux. Nous sommes... des voisins qui font leurs courses.", "안녕, 가스통. 우리는 연인이 아니야. 우리는... 장 보는 이웃일 뿐이야."),
(G, "Des voisins qui font leurs courses ensemble, à neuf heures du matin, un samedi. Je prends note.", "토요일 아침 9시에 같이 장을 보는 이웃들이라. 적어 둘게."),
(A, "Gaston, mange tes œufs et laisse-nous tranquilles.", "가스통, 계란이나 먹고 우릴 좀 내버려 둬."),
(G, "Je ne dis rien. Je regarde. À lundi ? Ou à jeudi, plutôt.", "난 아무 말 안 해. 그냥 볼 뿐이야. 월요일에 볼까? 아니, 목요일에."),
(None, "Gaston s'éloigne en riant, son sac plein de baguettes sous le bras.", "가스통이 겨드랑이에 바게트가 가득한 봉지를 끼고 웃으며 멀어진다."),
(L, "Il est incorrigible.", "정말 못 말려."),
(A, "Il est heureux. C'est différent. Viens, on va chez le primeur. J'ai besoin de légumes.", "행복한 거야. 다르지. 가자, 채소 가게로 가자. 채소가 필요해."),
(P, "Bonjour, Antoine ! Des fraises ? Elles viennent de Plougastel. Goûtez, goûtez !", "안녕, 앙투안! 딸기요? 플루가스텔 거예요. 맛보세요, 맛보세요!"),
(L, "(goûte une fraise) Oh. Elle est sucrée et parfumée. C'est la meilleure fraise que j'aie jamais mangée.", "(딸기를 맛본다) 오. 달콤하고 향이 좋아요. 제가 먹어 본 딸기 중 최고예요."),
(P, "Elle a été cueillie ce matin. Un kilo ?", "오늘 아침에 딴 거예요. 1킬로 드릴까요?"),
(L, "Euh... Je n'ai pas besoin d'un kilo. Cinq cents grammes, ça ira.", "음... 1킬로까지는 필요 없어요. 500그램이면 충분해요."),
(P, "Cinq cents grammes de fraises. Et avec ça ?", "딸기 500그램. 그리고 또 뭐 드릴까요?"),
(A, "Des pommes de terre nouvelles, un kilo. Des haricots verts, trois cents grammes. Et une botte de persil.", "햇감자 1킬로. 껍질콩 300그램. 그리고 파슬리 한 단."),
(L, "Tu fais des courses précises. Tu as déjà un menu en tête ?", "정확하게 장 보네. 이미 머릿속에 메뉴가 있어?"),
(A, "Non. Mais j'ai pensé qu'on pourrait préparer quelque chose ensemble. Un jour. Pas forcément aujourd'hui.", "아니. 하지만 언젠가 같이 뭔가 만들 수 있겠다고 생각했어. 꼭 오늘은 아니고."),
(L, "(un temps) Antoine, tu es libre, samedi soir prochain ?", "(잠시 후) 앙투안, 다음 주 토요일 저녁에 시간 있어?"),
(A, "Samedi soir ? Je crois que oui. Pourquoi ?", "토요일 저녁? 있을 것 같은데. 왜?"),
(L, "Je voudrais t'inviter à dîner. Chez moi. Rue Durantin, au numéro douze, troisième étage sans ascenseur.", "너를 저녁 식사에 초대하고 싶어. 우리 집에서. 뒤랑탱 거리 12번지, 엘리베이터 없는 4층."),
(A, "Je connais l'adresse. J'ai porté un parapluie jusqu'à cette porte, tu te souviens ?", "그 주소 알아. 그 문 앞까지 우산을 들고 간 적이 있잖아, 기억해?"),
(L, "Je m'en souviens très bien. Alors ? Tu acceptes ?", "아주 잘 기억해. 그래서? 받아들일래?"),
(A, "Avec grand plaisir. Mais tu cuisines ?", "정말 기쁘게. 그런데 요리해?"),
(L, "Je sais faire des pâtes et une omelette. Et le poulet rôti de ma mère. J'ai la recette, enfin, je crois.", "파스타랑 오믈렛은 할 줄 알아. 그리고 어머니의 로스트 치킨도. 레시피는 있어, 아마도."),
(A, "Tu crois ?", "아마도라고?"),
(L, "Elle me l'a donnée oralement. Au téléphone. Il y avait beaucoup de « un peu de » et de « à peu près ».", "구두로 알려 주셨어. 전화로. '조금'이랑 '대충' 같은 말이 아주 많았어."),
(A, "Les meilleures recettes sont toujours approximatives.", "최고의 레시피는 늘 대략적이지."),
(L, "Je t'avertis : si c'est raté, nous mangerons du fromage.", "미리 말해 두는데, 요리를 망치면 치즈를 먹자."),
(A, "J'adore ce plan B.", "그 플랜 B 마음에 들어."),
(L, "Et toi, tu apporteras le vin. C'est ta spécialité.", "그리고 너는 와인을 가져와. 그게 네 전문이니까."),
(A, "Je choisirai quelque chose de très spécial.", "아주 특별한 걸 고를게."),
(L, "Pas trop cher. Je te rappelle que je gagne ma vie en dessinant des étiquettes.", "너무 비싸지 않은 걸로. 난 라벨을 그려서 먹고산다는 걸 상기시켜 줄게."),
(A, "Promis. Un vin à moins de vingt euros. Mais mémorable.", "약속해. 20유로 이하의 와인. 하지만 기억에 남을 걸로."),
(P, "Voilà vos fraises et vos légumes. Ça fait quinze euros vingt.", "자, 딸기랑 채소예요. 15유로 20센트입니다."),
(A, "Tenez. Et gardez la monnaie pour le sourire.", "여기요. 잔돈은 미소 값으로 가지세요."),
(P, "Merci, Antoine ! Bonne dégustation à vous deux !", "고마워요, 앙투안! 두 분 맛있게 드세요!"),
(L, "Au pain, maintenant ? Pour le dîner de samedi prochain, il nous faudra des baguettes fraîches.", "이제 빵 사러 갈까? 다음 주 토요일 저녁 식사엔 신선한 바게트가 필요하겠어."),
(A, "Il nous faudra ? Tu as dit « nous ».", "필요하겠다고? '우리'라고 했네."),
(L, "J'ai dit « nous » parce que tu apporteras la baguette, évidemment.", "'우리'라고 한 건 당연히 네가 바게트를 가져와야 하니까."),
(A, "Évidemment. Un parapluie, un vin, une baguette. Je deviens un homme très utile.", "당연하지. 우산, 와인, 바게트. 나 꽤 쓸모 있는 남자가 되어 가네."),
(L, "Tu l'étais déjà.", "이미 그랬어."),
(None, "Elle tourne la tête, un peu gênée. Il sourit sans rien dire.", "그녀가 조금 쑥스러워 고개를 돌린다. 그는 아무 말 없이 미소 짓는다."),
(A, "Allez, viens. Il y a une boulangerie, au coin, qui fait la meilleure baguette tradition de Paris. Gaston dit qu'il ne le répétera à personne.", "자, 가자. 모퉁이에 파리 최고의 바게트 트라디시옹을 만드는 빵집이 있어. 가스통은 아무한테도 말하지 않겠다고 하지만."),
(L, "Gaston ne dit jamais rien à personne. Il dit tout à tout le monde.", "가스통은 누구에게도 아무 말 안 해. 모두에게 전부 말하지."),
(A, "C'est vrai. Alors on ne lui dira rien du tout.", "맞아. 그럼 아무 얘기도 안 하자."),
(L, "Du tout ?", "하나도?"),
(A, "Du tout. Samedi soir restera un secret.", "하나도. 토요일 저녁은 비밀로 남을 거야."),
(L, "Un secret entre voisins.", "이웃끼리의 비밀."),
(A, "Entre voisins. C'est le plus beau secret qui soit.", "이웃끼리의. 세상에서 가장 아름다운 비밀이지."),
]

VOCAB = [
("A2","un marché / un étal / un producteur","시장 / 가판대 / 생산자","« Les étals se remplissent de fruits. »"),
("A2","un fromage / un comté / un chèvre / un brie / un camembert","치즈 / 콩테 / 염소 치즈 / 브리 / 카망베르","프랑스 대표 치즈 이름"),
("A2","les fraises / les haricots verts / les pommes de terre","딸기 / 껍질콩 / 감자","시장에서 쓰는 채소·과일 이름"),
("A2","une baguette / une boulangerie","바게트 / 빵집","« la meilleure baguette tradition de Paris »"),
("A2","cent grammes / un kilo / un morceau de","100그램 / 1킬로 / ~ 한 조각","양을 말할 때 (de 뒤에 관사 없음)"),
("A2","goûter / un goûter","맛보다 / 간식","« Goûtez, goûtez ! » 시장에서 판매자가 권하는 표현"),
("B1","une cloche en verre","유리 덮개","치즈를 보호하는 덮개"),
("B1","une croûte fleurie","크루트 플뢰리(흰곰팡이 껍질)","카망베르·브리처럼 곰팡이가 하얗게 덮인 치즈의 껍질"),
("B1","une pâte pressée / un bleu","압착 경질 치즈 / 푸른곰팡이 치즈","치즈 분류 용어. bleu = 푸른곰팡이 치즈"),
("B1","la règle d'or","황금률","« un chèvre, un pâte pressée, une croûte fleurie, un bleu »"),
("B1","Ça fait + 금액","(합계가) ~입니다","« Ça fait vingt-quatre euros cinquante. »"),
("B1","et avec ça ?","그리고 또 필요한 건요?","상점 점원이 추가 주문을 물을 때"),
("B2","un duvet / de la moisissure","솜털 / 곰팡이","« un duvet blanc » = 치즈 껍질의 하얀 솜털"),
("B2","être paranoïaque","편집증적이다(지나치게 걱정하다)","« Je suis devenue paranoïaque. » 농담조"),
("B2","le palais","미각, 입천장","« Vous avez bon palais. » = 미각이 좋으세요"),
("B2","un plan B","플랜 B(대안)","« J'adore ce plan B. »"),
("B2","approximatif","대략적인","« Les meilleures recettes sont toujours approximatives. »"),
("B2","avertir quelqu'un","미리 알리다, 경고하다","« Je t'avertis : si c'est raté… »"),
("C1","la reine de la patience","인내심의 여왕","la reine de + 명사 = ~의 달인(농담)"),
("C1","un mariage de terroir","테루아르끼리의 결혼(같은 지역 음식과 와인의 조화)","미식에서 가장 중요한 페어링 원칙"),
("C1","Je prends note.","메모해 둘게(눈치챘어).","암시적으로 빈정거릴 때 자주 쓰는 구어"),
("C1","C'est le plus beau secret qui soit.","세상에서 가장 아름다운 비밀이다.","최상급 + qui soit (접속법): 한정적 최상급 표현"),
("C1","garder la monnaie pour le sourire","잔돈은 미소 값으로 가지세요","호의를 담은 위트 있는 표현"),
]

GRAM = [
("A2","양 표현과 de",
 "« deux cents grammes de comté », « un morceau de brie », « un kilo de pommes de terre », « beaucoup de fromages », « un peu de salé ». 양 표현 뒤에는 관사 없이 de + 명사."),
("A2","중성대명사 en (양을 대신함)",
 "« On en choisit trois ou quatre. » en = fromages. « Je n'en ai pas besoin. » 수량은 동사 뒤에 남는다: « J'en prends deux cents grammes. » « Comment on peut en choisir un seul ? »"),
("B1","명령법 + 대명사",
 "« Goûtez-en ! » (en 뒤로) « Donne-moi ça. » « Donne-m'en. » 긍정 명령에서는 대명사가 동사 뒤: -le/-la/-les, -moi/-toi, -en. 부정에서는 앞: « Ne m'en donne pas. »"),
("B1","의무·필요 표현 il faut / il nous faudra",
 "« Il nous faudra des baguettes fraîches. » il faut + 명사 = ~이 필요하다. « Il faut du pain. » 미래: il faudra, 조건법: il faudrait."),
("B1","최상급 + que + 접속법 과거 (경험)",
 "« C'est la meilleure fraise que j'aie jamais mangée. » 최상급 뒤 관계절에는 접속법을 쓰는 것이 원칙. j'aie mangé는 접속법 과거. 구어에서는 직설법 «que j'ai mangée»도 들린다."),
("B2","접속법 최상급 한정: « le plus beau secret qui soit »",
 "« C'est le plus beau secret qui soit. » 최상급 + qui + 접속법 현재: '존재할 수 있는 가장 ~한'. 문어체이자 격조 있는 구어 표현."),
("B2","미래 + 의무: tu apporteras le vin",
 "« Tu apporteras le vin. » 단순미래로 부탁·역할 분담을 부드럽게 말한다. 명령법보다 덜 직접적이다. « Tu choisiras le fromage. »"),
("C1","« ce qu'il y a de » 구문과 한정 부정: rien du tout",
 "« On ne lui dira rien du tout. » ne … rien du tout = 아무것도 전혀. du tout로 강조. « Pas du tout. » = 전혀 아니야."),
]

CULTURE = [
("프랑스 치즈의 4가지 분류와 황금률",
 "치즈는 pâte molle(연질: 카망베르), pâte pressée cuite/non cuite(경질: 콩테·칸탈), pâte persillée(블루: 로크포르), fromage de chèvre(염소: 크로탱)로 나뉜다. 와인과의 페어링은 'terroir with terroir'를 원칙으로 삼는다."),
("Marché des Abbesses",
 "아베스 광장의 시장은 토요일 오전에 열리는 동네 장터다. 단골이 되면 상인들이 이름을 기억해 주며, 시식을 권하는 것이 일반적이다. 시장에서 'goûtez'는 부담 없이 받아도 되는 호의다."),
("집으로 초대하기 invitation à dîner",
 "프랑스에서 집으로 저녁 초대는 관계가 한 단계 가까워졌다는 신호다. 초대받은 사람은 와인·꽃·디저트를 가져가는 것이 예의다. 요리 솜씨가 서툴러도 정성을 보여 주는 것이 중요하다."),
]

META = dict(part=1, ep=11, part_label="제1부 첫 잔 · Premier verre", title_fr="Le marché des Abbesses", title_ko="아베스 광장 시장",
 place="아베스 광장 시장(place des Abbesses) · 6월 초 토요일 오전 9시",
 chars="Léa · Antoine · Gaston · La fromagère (Mme Durand, 치즈 상인) · Le primeur (채소 가게 주인)",
 wine="(주제) chèvre + Sancerre, comté, bleu d'Auvergne 페어링",
 focus="양 표현, 중성대명사 en, 명령법+대명사, il faut, 최상급+접속법, 초대·승낙 표현",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제12화 « Premier dîner » : 레아의 서툰 로스트 치킨과 앙투안의 와인. 1부의 마지막 밤, 키스 직전에 레아가 꺼낸 ‘보르도’라는 단어.")
