# -*- coding: utf-8 -*-
G, L, A, H, P = "Gaston", "Léa", "Antoine", "Hugo", "Mme Pichon"
D = [
(None, "Samedi 21 juin, 19 h 30. C'est la Fête de la Musique. Dans toutes les rues de Montmartre, des groupes se sont installés sur les trottoirs. Devant La Cave des Abbesses, Gaston a posé une caisse de bois en guise de scène et branché deux petites enceintes.", "6월 21일 토요일 저녁 7시 30분. 음악 축제 날이다. 몽마르트르 거리 곳곳 인도에 밴드들이 자리를 잡았다. 라 카브 데 자베스 앞에서는 가스통이 나무 상자를 무대 삼아 놓고 작은 스피커 두 대를 연결했다."),
(G, "Un, deux... un, deux... Ça marche ! Mesdames et messieurs, la scène des Abbesses est ouverte !", "하나, 둘... 하나, 둘... 되네요! 신사 숙녀 여러분, 아베스 무대를 엽니다!"),
(P, "Gaston, vous êtes en train de brancher un fer à repasser, pas un micro.", "가스통, 지금 마이크가 아니라 다리미를 연결하고 있는 거예요."),
(G, "Madame Pichon, c'est un micro de collection. Il a vécu des choses.", "피숑 부인, 이건 수집가용 마이크예요. 겪은 일이 많죠."),
(L, "Gaston ! Bonsoir ! Tu as transformé le trottoir en salle de concert.", "가스통! 안녕! 인도를 콘서트홀로 만들었네."),
(G, "Léa ! Antoine ! Vous arrivez ensemble, bravo. Vous vous êtes retrouvés où ?", "레아! 앙투안! 같이 오다니, 훌륭해. 어디서 만났어?"),
(A, "Devant chez elle. Nous habitons dans la même rue, tu te souviens ?", "그녀 집 앞에서. 우리는 같은 거리에 살잖아, 기억해?"),
(G, "Je m'en souviens très bien. Je vous ai gardé deux chaises au premier rang.", "아주 잘 기억하지. 앞줄에 두 사람 의자를 잡아 놨어."),
(L, "Le premier rang d'un trottoir. Quel luxe.", "인도의 맨 앞줄이라니, 호사네."),
(A, "Léa, tu as l'air d'attendre quelqu'un depuis tout à l'heure. Tu regardes ton téléphone toutes les trois minutes.", "레아, 아까부터 누굴 기다리는 것 같아. 삼 분마다 전화기를 보고 있어."),
(L, "J'attends mon frère. Il arrive de Lyon par le train de dix-huit heures quarante. Il est en train de me chercher, je crois.", "남동생을 기다리는 중이야. 18시 40분 기차로 리옹에서 와. 지금 나를 찾고 있을 거야."),
(A, "Hugo ? Le musicien aux trois accords ?", "위고? 코드 세 개짜리 음악가?"),
(L, "Lui-même. Il a insisté pour venir jouer à la Fête de la Musique. Il dit que c'est son rêve depuis dix ans.", "바로 그 사람. 음악 축제에서 연주하고 싶다고 우겼어. 십 년 전부터 꿈이래."),
(A, "Je suis curieux de le rencontrer.", "만나 보고 싶네."),
(L, "Sois prudent. Il est protecteur. Il va te poser des questions pendant au moins une heure.", "조심해. 보호 본능이 강해. 최소 한 시간은 질문 공세를 펼칠 거야."),
(A, "Je suis professeur d'histoire. Les interrogatoires, c'est mon domaine.", "난 역사 교사야. 심문은 내 전문 분야지."),
(None, "Un grand garçon aux cheveux longs, un étui de guitare sur le dos, arrive en courant dans la rue. Il aperçoit Léa et lui saute dans les bras.", "머리가 긴 키 큰 청년이 등에 기타 케이스를 메고 거리를 뛰어 온다. 레아를 발견하고 품에 안긴다."),
(H, "Léa ! Ma petite sœur préférée !", "레아! 내가 제일 좋아하는 내 여동생!"),
(L, "Je suis ta seule sœur, Hugo.", "나는 네 하나뿐인 누나야, 위고."),
(H, "Raison de plus pour te préférer ! Alors c'est ça, Paris ? C'est plus petit que je pensais.", "더 선호할 이유네! 그럼 이게 파리야? 생각보다 작네."),
(L, "Hugo, je te présente Antoine. Antoine, voici mon frère Hugo.", "위고, 앙투안을 소개할게. 앙투안, 이쪽은 내 동생 위고야."),
(H, "(regarde Antoine de la tête aux pieds) Enchanté. Alors c'est vous, le professeur d'histoire avec le parapluie.", "(앙투안을 위아래로 훑어보며) 반갑습니다. 그래서 당신이 우산을 가진 역사 선생님이군요."),
(A, "Léa t'a parlé de moi ?", "레아가 네게 내 얘기를 했어?"),
(H, "Maman m'a parlé de vous. Et Léa a parlé à maman. Au téléphone. Pendant quarante minutes.", "엄마가 당신 얘기를 했어요. 그리고 레아가 엄마한테 말했죠. 전화로. 사십 분 동안."),
(L, "Hugo !", "위고!"),
(H, "Quoi ? Je dis les faits. « Antoine ci, Antoine ça, Antoine connaît tout sur le Morgon. »", "뭐? 사실을 말하는 건데. '앙투안은 이렇고 저렇고, 앙투안은 모르공에 대해 다 알아.'"),
(A, "Je ne connais pas tout sur le Morgon. Mais j'en connais un peu.", "모르공에 대해 다 알지는 않아. 하지만 조금은 알지."),
(H, "Voilà ce que ma sœur appelle de la modestie.", "그게 우리 누나가 말하는 겸손이에요."),
(G, "Jeune homme, tu es Hugo ? Le guitariste ? On m'a parlé de toi aussi.", "젊은이, 자네가 위고인가? 기타리스트? 나도 자네 얘기를 들었지."),
(H, "Tout le monde parle de moi sauf moi, on dirait.", "다들 나 얘기를 하는데 정작 나만 빼놓는 것 같네."),
(G, "Alors parle un peu. Là, sur ma scène. Il y a un micro, des enceintes, et une cliente qui a envie de t'entendre.", "그럼 이제 말해 봐. 저기 내 무대에서. 마이크도 있고 스피커도 있고, 자네 연주를 듣고 싶어 하는 손님도 있어."),
(P, "C'est moi, la cliente. Je vous préviens, jeune homme : je suis exigeante.", "그 손님이 저예요. 미리 말해 두는데 젊은이, 저는 까다로워요."),
(H, "J'aime ça. Je vais jouer mon meilleur répertoire. Trois accords et beaucoup d'émotion.", "그런 거 좋아요. 제 최고의 레퍼토리를 연주할게요. 코드 세 개와 엄청난 감정으로."),
(L, "(à Antoine) Prépare-toi à une grande performance.", "(앙투안에게) 대단한 공연에 대비해."),
(None, "Hugo monte sur la caisse. Il accorde sa guitare, tousse, et joue les premières notes d'une chanson que tout le monde connaît.", "위고가 나무 상자 위에 올라선다. 기타를 조율하고 헛기침을 한 뒤 모두가 아는 노래의 첫 음을 연주한다."),
(H, "Bonsoir Montmartre ! Cette chanson est pour ma sœur, qui a quitté Lyon pour devenir une grande parisienne !", "안녕하세요, 몽마르트르! 이 노래는 리옹을 떠나 대단한 파리지앵이 된 제 누나를 위한 곡이에요!"),
(L, "(rit, à Antoine) Il n'a jamais su rester modeste.", "(웃으며 앙투안에게) 얘는 겸손할 줄을 몰라."),
(A, "C'est de famille, non ?", "집안 내력이지, 아니야?"),
(None, "La chanson commence. Quelques passants s'arrêtent. Madame Pichon bat la mesure avec son pied. Bientôt, tout le monde chante en chœur.", "노래가 시작된다. 몇몇 행인이 멈춰 선다. 피숑 부인이 발로 박자를 맞춘다. 곧 모두가 합창한다."),
(A, "Tu chantes faux.", "너 음정 틀려."),
(L, "Je chante avec conviction. C'est dans les gènes, je te l'ai dit.", "확신을 갖고 부르는 거야. 유전자에 있다고 말했잖아."),
(A, "Alors je chante avec toi. On fera deux fois plus de bruit.", "그럼 나도 같이 부를래. 소음이 두 배가 되겠지."),
(None, "Ils chantent ensemble, mal et joyeusement. Léa se tourne vers lui, les yeux brillants. Antoine lui prend la main sans y penser. Elle ne la retire pas.", "두 사람이 함께 서툴고 즐겁게 노래한다. 레아가 눈을 반짝이며 그를 돌아본다. 앙투안이 생각 없이 그녀의 손을 잡는다. 그녀는 손을 빼지 않는다."),
(H, "(depuis la scène, du coin de l'œil) Hum.", "(무대에서 곁눈질로) 흠."),
(G, "(à voix basse, à Madame Pichon) Ça y est.", "(작은 소리로 피숑 부인에게) 드디어 됐네요."),
(P, "(à voix basse) Il était temps. J'avais parié avec Karim.", "(작은 소리로) 때가 됐죠. 카림이랑 내기까지 했는데."),
(G, "Vous aviez parié combien ?", "얼마 걸었어요?"),
(P, "Une bouteille de Sauternes. Je viens de gagner.", "소테른 한 병이에요. 방금 이겼어요."),
(None, "La chanson se termine. Applaudissements. Hugo s'incline plusieurs fois, un peu trop longtemps. Puis il descend de la caisse et s'approche d'Antoine.", "노래가 끝난다. 박수가 터진다. 위고가 여러 번, 조금 너무 길게 인사한다. 그러고는 상자에서 내려와 앙투안에게 다가간다."),
(H, "Bon. Antoine, je peux te dire un mot, rien que toi et moi ?", "자. 앙투안, 너랑 나 둘이서만 한마디 해도 될까요?"),
(L, "Hugo, ne commence pas.", "위고, 시작하지 마."),
(H, "Je ne commence rien. Je fais juste connaissance.", "시작하는 거 아니야. 알아 가려는 것뿐이야."),
(A, "Léa, ne t'inquiète pas. Viens, Hugo, on marche un peu.", "레아, 걱정 마. 가자, 위고, 좀 걷자."),
(None, "Les deux hommes s'éloignent de quelques mètres, près de la devanture de la boutique. Léa les observe, un peu inquiète.", "두 남자가 가게 쇼윈도 근처 몇 미터 떨어진 곳으로 간다. 레아가 조금 불안한 얼굴로 그들을 지켜본다."),
(H, "Écoute. Je ne te connais pas. Mais je connais ma sœur. Depuis qu'elle est à Paris, elle ne rit plus comme avant.", "들어요. 난 당신을 몰라요. 하지만 누나는 알아요. 파리에 온 뒤로 예전처럼 웃지 않았어요."),
(A, "Je comprends.", "알겠어요."),
(H, "Ce soir, pour la première fois depuis des années, elle rit. Ça veut dire quelque chose.", "오늘 저녁 몇 년 만에 처음으로 웃고 있어요. 그건 뭔가 의미가 있죠."),
(A, "Elle me fait rire aussi. Beaucoup.", "저도 그녀 덕분에 많이 웃어요."),
(H, "Elle t'a parlé de Bordeaux ?", "누나가 보르도 얘기를 했어요?"),
(A, "(un temps) Oui. Elle m'en a parlé il y a deux semaines.", "(잠시 후) 네. 이 주 전에 말해 줬어요."),
(H, "Elle ne l'a dit à personne, sauf à maman. Alors si elle te l'a dit, ça signifie que tu comptes pour elle.", "엄마 말고는 아무한테도 얘기 안 했어요. 그러니까 당신에게 말했다면 당신이 중요하다는 뜻이에요."),
(A, "Je ne sais pas ce qu'elle va décider. Mais je ne veux pas qu'elle décide à cause de moi.", "그녀가 뭘 결정할지 모르겠어요. 하지만 나 때문에 결정하길 원하지 않아요."),
(H, "C'est la première phrase intelligente que j'entends ce soir.", "오늘 저녁에 들은 첫 번째 현명한 말이네요."),
(A, "Merci. Je me sentais attaqué.", "고마워요. 공격당하는 기분이었거든요."),
(H, "Je suis son petit frère. C'est mon rôle. Si tu lui fais du mal, je viens jouer de la guitare sous ta fenêtre, toutes les nuits.", "난 동생이에요. 그게 내 역할이죠. 누나를 아프게 하면 매일 밤 당신 창문 아래서 기타를 칠 거예요."),
(A, "Les trois mêmes accords ?", "똑같은 세 개의 코드로?"),
(H, "Les trois mêmes accords. Pendant des heures.", "똑같은 세 개의 코드로. 몇 시간 동안."),
(A, "Je ne ferai jamais de mal à ta sœur. Mais cette menace me terrifie, c'est vrai.", "네 누나를 절대 아프게 하지 않을게. 하지만 그 협박은 정말 무섭네."),
(H, "(sourit enfin) D'accord. Tu es accepté. Mais je te surveille.", "(마침내 미소 지으며) 좋아요. 합격이에요. 하지만 지켜볼 거예요."),
(None, "Ils reviennent vers Léa. Hugo passe un bras sur les épaules d'Antoine, comme s'ils se connaissaient depuis toujours.", "둘이 레아에게 돌아온다. 위고가 마치 오래전부터 알던 사이처럼 앙투안의 어깨에 팔을 두른다."),
(L, "Alors ? Vous vous êtes bien entendus ?", "그래서? 이야기가 잘 통했어?"),
(H, "Très bien. Antoine est un homme sérieux. Il m'a promis de ne jamais t'ennuyer.", "아주 잘요. 앙투안은 진지한 사람이야. 누나를 절대 귀찮게 하지 않겠다고 약속했어."),
(L, "Et moi, qu'est-ce que tu lui as promis ?", "그럼 넌 앙투안한테 뭘 약속했어?"),
(H, "Rien. Les petits frères ne promettent jamais rien.", "아무것도. 동생들은 아무것도 약속하지 않아."),
(G, "La suite du programme ! Madame Pichon va nous chanter quelque chose.", "다음 순서입니다! 피숑 부인이 노래를 불러 주실 거예요."),
(P, "Moi ? Vous plaisantez, Gaston !", "저요? 농담하시네요, 가스통!"),
(H, "Qu'est-ce que vous voulez chanter, madame ?", "무슨 노래를 부르고 싶으세요, 부인?"),
(P, "« La Vie en rose ». Je la chante depuis soixante ans, mais jamais devant plus de dix personnes.", "'라 비 앙 로즈'요. 육십 년 동안 불러 왔지만 열 명 넘는 사람 앞에서는 한 번도 못 했어요."),
(H, "Aujourd'hui, vous en avez trente. Vous êtes prête ?", "오늘은 서른 명이에요. 준비되셨어요?"),
(P, "Je suis prête depuis 1974.", "1974년부터 준비돼 있었어요."),
(None, "Madame Pichon monte sur la caisse. Hugo joue les premières notes. Sa voix tremble, puis s'affermit. La rue entière se tait pour l'écouter.", "피숑 부인이 상자 위에 올라선다. 위고가 첫 음을 연주한다. 그녀의 목소리가 떨리다가 단단해진다. 거리 전체가 조용히 귀를 기울인다."),
(L, "(à voix basse) Elle chante magnifiquement.", "(작은 소리로) 정말 아름답게 부르셔."),
(A, "Elle chante pour son mari, j'en suis sûr.", "남편을 위해 부르시는 거야, 확신해."),
(L, "Tu crois ?", "그렇게 생각해?"),
(A, "Regarde ses yeux. Elle n'est plus ici. Elle est à Saint-Émilion, en 1974, sous la pluie.", "눈을 봐. 이제 여기 없어. 1974년 생테밀리옹 빗속에 있어."),
(L, "(émue) C'est beau, ce que tu dis.", "(감동하여) 네 말이 아름다워."),
(A, "C'est surtout vrai.", "그건 무엇보다 사실이야."),
(None, "La chanson se termine. Un silence, puis des applaudissements. Madame Pichon s'essuie les yeux et salue.", "노래가 끝난다. 침묵, 그리고 박수. 피숑 부인이 눈물을 닦고 인사한다."),
(None, "La nuit tombe. Sur toutes les places, des musiciens jouent. Une odeur de crêpes et de bière flotte dans l'air. Léa, Antoine et Hugo marchent côte à côte vers la place du Tertre.", "밤이 내린다. 모든 광장에서 음악가들이 연주한다. 크레프와 맥주 냄새가 공기 중에 떠다닌다. 레아, 앙투안, 위고가 나란히 테르트르 광장 쪽으로 걸어간다."),
(H, "C'est dingue, ce soir. Il y a de la musique partout. À Lyon, on n'a jamais ça.", "오늘 밤 미쳤네요. 어디나 음악이야. 리옹에는 이런 게 없어요."),
(L, "Si, mais pas au même point. Ici, Paris joue pour toi.", "있기는 한데 이 정도는 아니지. 여기서는 파리가 널 위해 연주해."),
(A, "Tu veux t'arrêter là ? Il y a un groupe de jazz, juste devant. Je crois qu'ils jouent du Django Reinhardt.", "저기 멈춰 볼래? 바로 앞에 재즈 밴드가 있어. 장고 라인하르트를 연주하는 것 같아."),
(L, "Allons-y ! J'adore le jazz manouche.", "가자! 난 마누슈 재즈를 좋아해."),
(H, "Moi, je vous laisse. Je vais voir si je peux jouer avec les musiciens du coin. On se retrouve plus tard ?", "저는 두 사람을 놔두고 갈게요. 근처 음악가들과 같이 연주할 수 있나 볼게요. 나중에 다시 만날까요?"),
(L, "À minuit, devant la boutique de Gaston. Ne te perds pas.", "자정에 가스통 가게 앞에서. 길 잃지 마."),
(H, "Je suis un homme libre, Léa. Je me perds quand je veux. Antoine ! Prends soin d'elle.", "난 자유인이야, 레아. 원할 때 길을 잃어. 앙투안! 누나를 잘 부탁해요."),
(A, "Promis.", "약속할게."),
(None, "Hugo s'éloigne en riant, sa guitare dans le dos. Antoine et Léa se retrouvent seuls devant le groupe de jazz.", "위고가 등에 기타를 멘 채 웃으며 멀어진다. 앙투안과 레아는 재즈 밴드 앞에 단둘이 남는다."),
(L, "Désolée pour mon frère. Il est... entier.", "내 동생 미안해. 좀... 직설적이야."),
(A, "Il t'aime. C'est tout ce qui compte.", "널 사랑해서 그래. 그게 가장 중요해."),
(L, "Il t'a dit quoi, au fond ?", "결국 너한테 뭐라고 했어?"),
(A, "Qu'il jouerait de la guitare sous ma fenêtre si je te faisais du mal.", "내가 널 아프게 하면 내 창문 아래서 기타를 칠 거라고."),
(L, "(rit) Il est capable de le faire.", "(웃으며) 정말 할 수 있는 애야."),
(A, "J'espère ne jamais le voir.", "그런 일은 보지 않길 바라."),
(None, "Le groupe de jazz entame un morceau lent. Quelques couples se mettent à danser sur le trottoir. Léa tend la main à Antoine.", "재즈 밴드가 느린 곡을 시작한다. 몇몇 커플이 인도에서 춤추기 시작한다. 레아가 앙투안에게 손을 내민다."),
(L, "Viens. On danse.", "와. 춤추자."),
(A, "Je ne sais pas danser.", "난 춤 못 춰."),
(L, "Moi non plus. Mais ce soir, on a le droit d'être mauvais.", "나도 못 춰. 하지만 오늘 밤은 서툴러도 되는 날이야."),
(A, "Alors dansons mal ensemble.", "그럼 같이 서툴게 춰 보자."),
(None, "Ils dansent, un peu gauchement, au milieu des autres. Au-dessus d'eux, quelques étoiles apparaissent entre les toits.", "두 사람이 다른 사람들 사이에서 조금 어색하게 춤춘다. 그들 위로 지붕 사이에 별 몇 개가 나타난다."),
(L, "Antoine ?", "앙투안?"),
(A, "Oui ?", "응?"),
(L, "Je suis contente d'être ici. Ce soir. Avec toi.", "나 여기 있어서 기뻐. 오늘 밤. 너와 함께."),
(A, "Moi aussi. Et si je pouvais arrêter le temps, je le ferais.", "나도. 시간을 멈출 수 있다면 그렇게 하겠어."),
]

VOCAB = [
("A2","la Fête de la Musique","음악 축제(6월 21일)","1982년 프랑스에서 시작된 하지(夏至) 축제. 거리마다 무료 공연이 열림"),
("A2","une scène / une caisse en bois / une enceinte","무대 / 나무 상자 / 스피커","« une caisse de bois en guise de scène »"),
("A2","un micro / un fer à repasser","마이크 / 다리미","피숑 부인의 농담. 연결 잘못한 장비"),
("A2","jouer de la guitare / chanter faux","기타를 치다 / 음정이 틀리게 노래하다","jouer de + 악기. chanter juste / faux"),
("A2","applaudir / les applaudissements","박수 치다 / 박수","« Applaudissements. »"),
("A2","un frère / une sœur / un petit frère","형제 / 자매 / 남동생","가족 호칭"),
("B1","être en train de + 동사원형","~하는 중이다","« Vous êtes en train de brancher un fer à repasser. »"),
("B1","se retrouver / se perdre / s'éloigner","만나다 / 길을 잃다 / 멀어지다","대명동사 사용. « On se retrouve à minuit. »"),
("B1","en guise de","~ 대신, ~ 삼아","« une caisse en guise de scène » 격식 있는 표현"),
("B1","un répertoire","레퍼토리","연주자가 연주할 수 있는 곡 목록"),
("B1","accorder (une guitare) / un accord","조율하다 / 코드","« trois accords » = 세 개의 코드"),
("B1","battre la mesure","박자를 맞추다","« Elle bat la mesure avec son pied. »"),
("B1","faire connaissance","서로 알아 가다","« Je fais juste connaissance. »"),
("B2","un interrogatoire","심문","« Les interrogatoires, c'est mon domaine. » 장난조"),
("B2","protecteur / entier","보호 본능이 강한 / 거침없는·직설적인","entier = 한결같고 타협 없는 성격(친근한 비판)"),
("B2","un jazz manouche","마누슈 재즈(집시 재즈)","장고 라인하르트의 스타일"),
("B2","gauchement","어색하게","gauche = 왼쪽 / 서투른"),
("B2","parier / une bouteille de Sauternes","내기하다 / 소테른 한 병","« J'avais parié avec Karim. »"),
("B2","compter pour quelqu'un","~에게 중요하다","« Tu comptes pour elle. »"),
("C1","Raison de plus.","그러니 더더욱.","« Raison de plus pour te préférer ! » 반어적 응수"),
("C1","du coin de l'œil","곁눈질로","살짝 보는 시선"),
("C1","C'est dingue.","믿기지 않아, 미쳤어.","구어. 놀라움·감탄 표현"),
("C1","Je me sentais attaqué.","공격받는 느낌이었어.","감정 표현에 sentir + 과거분사"),
("C1","si je pouvais arrêter le temps, je le ferais","시간을 멈출 수 있다면 그렇게 하겠어","si + 반과거 + 조건법 현재. 로맨틱한 가정"),
]

GRAM = [
("A2","être en train de + 동사원형",
 "« Vous êtes en train de brancher un fer à repasser. » « Il est en train de me chercher. » 지금 진행 중인 동작 강조. 일반 현재형으로도 가능하지만 진행의 느낌을 더하고 싶을 때."),
("A2","대명동사 현재: se retrouver / se perdre / se souvenir",
 "« Vous vous êtes retrouvés où ? » (복합과거) « On se retrouve plus tard ? » (현재) « Tu te souviens ? » 재귀대명사: me, te, se, nous, vous, se. 상호 의미 가능."),
("B1","명령법의 부정과 대명사",
 "« Ne commence pas. » « Ne t'inquiète pas. » « Prends soin d'elle. » 부정 명령은 ne + 동사 + pas. 대명동사 명령: 긍정 « Inquiète-toi », 부정 « Ne t'inquiète pas »."),
("B1","미래: aller 대신 단순미래",
 "« Il va te poser des questions. » (근접미래) « Je te surveillerai. » (단순미래) « Il jouerait de la guitare sous ma fenêtre. » (조건법 — 간접화법). 미래 표현의 세 층위를 구분."),
("B1","depuis + 현재 / il y a + 과거",
 "« Depuis qu'elle est à Paris, elle ne rit plus. » « Elle m'en a parlé il y a deux semaines. » depuis = 계속되는 지금까지, il y a = 과거의 한 시점."),
("B2","간접화법의 시제 일치",
 "« Il m'a promis de ne jamais t'ennuyer. » « Il a dit qu'il jouerait de la guitare. » 직접화법의 현재 → 과거 맥락에서는 반과거, 미래 → 조건법. promettre de + 동사원형."),
("B2","접속법: je ne veux pas que + 접속법",
 "« Je ne veux pas qu'elle décide à cause de moi. » vouloir que + 접속법 현재. decide → décide (접속법 현재형은 3인칭 단수에서 직설법과 같다)."),
("C1","si + 반과거, 조건법 현재 (비현실 가정)",
 "« Si je pouvais arrêter le temps, je le ferais. » 현재의 비현실적 가정. « Si tu lui faisais du mal, je viendrais jouer... » 협박·약속·소망을 부드럽게 표현할 때."),
]

CULTURE = [
("Fête de la Musique",
 "1982년 문화부 장관 자크 랑이 시작해 지금은 120여 개국으로 퍼진 하지 축제. 6월 21일 저녁, 프랑스 전역의 거리·광장·카페에서 아마추어와 프로가 무료로 공연한다. '누구든 연주하고 누구든 들을 수 있는 날'이 취지다."),
("« La Vie en rose » 와 에디트 피아프",
 "'라 비 앙 로즈'는 1946년 에디트 피아프가 부른 샹송이다. 프랑스 사람들에게 세대를 넘어 사랑받는 노래로 가족 모임에서도 자주 함께 부른다."),
("장고 라인하르트와 마누슈 재즈",
 "벨기에 태생 집시 기타리스트 장고 라인하르트가 1930년대 파리에서 창시한 재즈 스타일. 어쿠스틱 기타 중심의 빠른 스윙이 특징이며 몽마르트르 카페 거리에서 자주 연주된다."),
]

META = dict(part=2, ep=13, part_label="제2부 여름의 포도 · Les raisins de l'été", title_fr="Fête de la Musique", title_ko="음악 축제의 밤",
 place="몽마르트르 거리와 La Cave des Abbesses 앞 · 6월 21일 토요일 19시 30분",
 chars="Léa · Antoine · Gaston · Mme Pichon · Hugo (위고, 레아의 남동생, 25세 음악가)",
 wine="(와인 없음) 음악 축제의 밤",
 focus="être en train de, 대명동사, 간접화법 시제 일치, si + 반과거(비현실 가정), 접속법 입문",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제14화 « Pique-nique au canal » : 생마르탱 운하 변에서 맞이하는 여름. 서로의 과거를 처음으로 조심스레 묻는 시간.")
