# -*- coding: utf-8 -*-
G, L, A, P, K = "Gaston", "Léa", "Antoine", "Mme Pichon", "Karim"
D = [
(None, "Lundi 14 juillet, 21 h 30. Sur les marches du Sacré-Cœur, des milliers de personnes attendent le feu d'artifice qui sera tiré depuis la tour Eiffel. Léa et Antoine ont étendu une couverture au troisième rang, entre un groupe d'étudiants et une famille italienne.", "7월 14일 월요일 밤 9시 30분. 사크레쾨르 계단에서 수천 명이 에펠탑에서 쏘아 올릴 불꽃놀이를 기다린다. 레아와 앙투안이 대학생 무리와 이탈리아 가족 사이 세 번째 줄에 담요를 펼쳤다."),
(L, "Quelle foule ! Je n'ai jamais vu autant de monde sur ces marches.", "엄청난 인파야! 이 계단에서 이렇게 많은 사람은 처음 봐."),
(A, "C'est le 14 juillet. Tout Paris monte à Montmartre pour voir le feu d'artifice.", "7월 14일이잖아. 파리 사람들이 다 불꽃놀이를 보러 몽마르트르에 올라와."),
(L, "Et la tour Eiffel est loin, mais on la voit très bien d'ici.", "에펠탑은 멀지만 여기서도 아주 잘 보여."),
(A, "C'est ce qui fait le charme de cet endroit. Paris entière, à nos pieds.", "그게 이곳의 매력이야. 파리 전체가 발아래 있어."),
(L, "Tu es sûr qu'on a bien fait de venir si tôt ? On a deux heures d'attente.", "이렇게 일찍 오길 잘한 거 맞아? 두 시간이나 기다려야 하잖아."),
(A, "Si on était arrivés plus tard, on aurait dû rester debout au fond. Là, au moins, on est assis.", "더 늦게 왔다면 뒤에 서 있어야 했을 거야. 이렇게 하면 최소한 앉아 있잖아."),
(L, "Tu as toujours raison. C'est énervant.", "넌 항상 옳아. 짜증 나."),
(A, "Je n'ai pas toujours raison. Je suis seulement très bien organisé.", "항상 옳지는 않아. 아주 철저히 준비할 뿐이야."),
(None, "Gaston et Madame Pichon apparaissent au milieu de la foule, chacun portant un petit panier. Gaston fait de grands signes.", "가스통과 피숑 부인이 각자 작은 바구니를 들고 인파 속에서 나타난다. 가스통이 크게 손짓한다."),
(G, "Ah, les voilà ! Je savais que je vous trouverais ici !", "아, 여기 있었군! 여기서 찾을 줄 알았어!"),
(L, "Gaston ! Madame Pichon ! Quelle bonne surprise !", "가스통! 피숑 부인! 정말 반가운 일이에요!"),
(P, "Nous avons apporté des gougères, du saucisson, et une bouteille de crémant. On ne regarde pas un feu d'artifice le ventre vide.", "구제르랑 소시송이랑 크레망 한 병을 가져왔어요. 빈속으로 불꽃놀이를 보면 안 되죠."),
(A, "Madame Pichon, vous êtes un ange.", "피숑 부인, 천사세요."),
(P, "Un ange qui a le dos fragile. Gaston, assieds-toi avant que je tombe.", "허리가 약한 천사죠. 가스통, 내가 쓰러지기 전에 앉혀 줘요."),
(None, "Gaston déplie une petite chaise pliante et aide Madame Pichon à s'installer. Léa leur fait de la place sur la couverture.", "가스통이 작은 접이식 의자를 펴 피숑 부인이 앉도록 돕는다. 레아가 담요 위에 자리를 내준다."),
(G, "Léa, Antoine, savez-vous pourquoi on fête le quatorze juillet ?", "레아, 앙투안, 7월 14일을 왜 기념하는지 알아요?"),
(A, "Gaston, je suis professeur d'histoire.", "가스통, 난 역사 교사야."),
(G, "Je sais. Mais Léa n'en est pas un. Elle doit savoir.", "알아. 하지만 레아는 아니잖아. 알아야지."),
(L, "Je crois que c'est la prise de la Bastille. En 1789.", "바스티유 습격일 거예요. 1789년."),
(A, "Exactement. Le quatorze juillet 1789, des Parisiens ont pris d'assaut la prison de la Bastille, symbole du pouvoir royal.", "정확해. 1789년 7월 14일에 파리 시민들이 왕권의 상징인 바스티유 감옥을 습격했어."),
(L, "Il y avait beaucoup de prisonniers ?", "죄수가 많았어?"),
(A, "Seulement sept. Mais ce n'était pas le nombre qui comptait, c'était le symbole. Le peuple montrait qu'il n'avait plus peur.", "일곱 명뿐이었어. 하지만 중요한 건 숫자가 아니라 상징이었어. 민중이 더 이상 두렵지 않다는 걸 보여 준 거지."),
(G, "Mais on ne fête pas vraiment la prise de la Bastille, n'est-ce pas ?", "그런데 사실 바스티유 습격을 기념하는 건 아니죠, 그렇죠?"),
(A, "Non. On fête surtout la Fête de la Fédération, le quatorze juillet 1790. Un an après, toute la France s'est réunie pour célébrer l'unité nationale.", "맞아. 주로 1790년 7월 14일 연맹제를 기념해. 일 년 뒤에 프랑스 전역이 모여 국가의 통합을 축하했거든."),
(L, "Je ne le savais pas. On m'avait toujours dit que c'était la prise de la Bastille.", "몰랐어. 항상 바스티유 습격이라고만 들었는데."),
(A, "C'est un raccourci. Les raccourcis sont comme les clichés : pratiques, mais pas toujours exacts.", "그건 줄인 설명이야. 줄임말은 고정관념과 같아서 편리하지만 늘 정확하진 않지."),
(P, "Quel bon professeur ! Si j'avais eu un professeur d'histoire comme vous, j'aurais retenu quelque chose.", "훌륭한 선생님이네요! 이런 역사 선생님이 있었다면 저도 뭔가 기억했을 텐데."),
(A, "Vous en avez retenu beaucoup, Madame Pichon. Vous m'avez raconté Saint-Émilion en 1974 mieux que n'importe quel manuel.", "많이 기억하고 계세요, 피숑 부인. 생테밀리옹 1974년 얘기를 어떤 교과서보다 더 잘해 주셨잖아요."),
(P, "C'est de l'histoire personnelle. Elle est plus belle que l'autre.", "그건 개인의 역사죠. 다른 역사보다 아름답고요."),
(G, "Moi, mon meilleur souvenir du quatorze juillet, c'est celui de 1990. C'était mon premier quatorze juillet comme patron.", "내 제일 좋은 14일 추억은 1990년이야. 사장으로서 처음 맞은 14일이었지."),
(L, "Raconte-nous.", "얘기해 줘."),
(G, "J'avais ouvert la boutique en avril. Il n'y avait pas de clients. Aucun. Le quatorze juillet, j'ai fermé à midi et je suis monté ici avec une bouteille.", "4월에 가게를 열었어. 손님이 없었지. 하나도. 7월 14일에 정오에 닫고 와인 한 병을 들고 여기 올라왔어."),
(G, "J'ai regardé le feu d'artifice tout seul. Et à côté de moi, il y avait une dame. Elle m'a demandé ce que je buvais.", "혼자 불꽃놀이를 봤어. 그런데 옆에 어떤 부인이 있었지. 내가 뭘 마시는지 물었어."),
(P, "Et vous lui avez répondu ?", "그래서 뭐라고 대답하셨어요?"),
(G, "Que c'était un Beaujolais. Elle m'a dit qu'elle n'aimait que le Bordeaux. On s'est disputés pendant une heure.", "보졸레라고 했지. 그 부인은 보르도만 좋아한다고 했어. 한 시간 동안 다퉜어."),
(P, "Gaston ! Vous ne m'avez jamais raconté ça !", "가스통! 한 번도 말 안 했잖아요!"),
(G, "Parce que cette dame, c'était vous.", "그 부인이 바로 당신이었으니까요."),
(None, "Un silence stupéfait. Madame Pichon ouvre la bouche, puis la referme. Léa et Antoine échangent un regard.", "놀란 침묵이 흐른다. 피숑 부인이 입을 열었다 닫는다. 레아와 앙투안이 눈빛을 주고받는다."),
(P, "C'était... vous ? Ce jeune homme avec un Beaujolais ?", "그게... 당신이었어요? 보졸레를 든 그 청년이?"),
(G, "Vous aviez un chapeau à fleurs. Vous disiez que c'était le plus beau du quartier.", "꽃무늬 모자를 쓰고 계셨어요. 동네에서 제일 예쁜 모자라고 말씀하셨죠."),
(P, "Il l'était ! Mais je ne me rappelle pas vous avoir rencontré.", "예뻤죠! 하지만 당신을 만났던 기억은 안 나요."),
(G, "Vous m'avez rencontré. Et vous êtes venue à la boutique le lendemain. Depuis, vous n'avez jamais cessé d'acheter du Bordeaux.", "만났어요. 그리고 다음 날 가게에 오셨죠. 그 뒤로 보르도를 계속 사 가셨고요."),
(P, "C'est donc à cause de vous que mon mari a pris goût au vin !", "그러니까 우리 남편이 와인을 좋아하게 된 게 당신 때문이군요!"),
(G, "Je suis fier de cette responsabilité.", "그 책임이 자랑스럽습니다."),
(L, "(à Antoine, à voix basse) Quelle histoire ! Trente-cinq ans d'amitié avec une phrase d'ouverture.", "(앙투안에게 작은 소리로) 정말 대단한 이야기야! 첫마디 하나로 35년의 우정이라니."),
(A, "Et on se demande pourquoi je suis historien.", "내가 왜 역사학자인지 궁금해하는 사람들이 있지."),
(None, "Dans la nuit qui tombe, les premières fusées s'élèvent au-dessus de la tour Eiffel. Un « oh ! » monte de la foule.", "내려앉는 밤하늘 속에서 첫 불꽃이 에펠탑 위로 솟아오른다. 군중에게서 '오!' 하는 탄성이 터져 나온다."),
(L, "Oh ! Regarde ! Que c'est beau !", "오! 봐! 정말 아름다워!"),
(A, "Quel spectacle ! On dirait que le ciel est en feu.", "정말 장관이야! 하늘이 불타는 것 같아."),
(P, "Comme c'est joli ! Les couleurs, les lumières ! Ça me rappelle mon enfance.", "어쩜 이렇게 예쁠까! 색깔, 빛! 어린 시절이 떠오르네요."),
(G, "Ah ça alors ! Il y en a encore un en forme de cœur !", "세상에! 하트 모양도 있네!"),
(A, "Celui-là, il est pour toi.", "저건 너를 위한 거야."),
(L, "Tu es sentimental, ce soir.", "오늘 밤 감상적이네."),
(L, "Quel idiot, j'ai oublié mon téléphone pour filmer.", "정말 바보야, 촬영하려고 전화기를 챙긴다는 걸 잊었어."),
(A, "Tu l'as dans ta poche.", "주머니에 있잖아."),
(L, "(rit) Ah oui ! Mais je préfère regarder avec mes yeux.", "(웃으며) 아 맞다! 하지만 눈으로 보는 게 더 좋아."),
(A, "C'est la meilleure décision de la soirée.", "오늘 밤 최고의 결정이야."),
(P, "Chut, vous deux ! Vous bavardez pendant le plus beau moment !", "쉿, 두 사람! 제일 멋진 순간에 수다를 떨고 있잖아요!"),
(L, "Pardon, madame Pichon !", "죄송해요, 피숑 부인!"),
(None, "Le téléphone de Léa vibre dans sa poche. Elle le sort machinalement, regarde l'écran, et son sourire disparaît lentement.", "레아의 주머니에서 전화기가 진동한다. 그녀가 무심코 꺼내 화면을 보는데 미소가 서서히 사라진다."),
(A, "Qu'est-ce qu'il y a ?", "무슨 일이야?"),
(L, "Rien. Un e-mail. Je regarde plus tard.", "아무것도 아니야. 이메일이야. 나중에 볼게."),
(A, "Léa, tu as changé de visage. Ce n'est pas rien.", "레아, 표정이 바뀌었어. 아무것도 아닌 게 아니야."),
(L, "(un temps) C'est Bordeaux. Ils m'invitent à venir visiter l'agence. Le vingt-huit juillet. Deux jours, tous frais payés.", "(잠시 후) 보르도야. 회사 방문하러 오래. 7월 28일. 이틀, 모든 경비 부담이래."),
(A, "(sans bouger, les yeux sur le ciel) Je vois.", "(움직이지 않고 하늘을 바라보며) 그렇구나."),
(L, "Je ne sais pas quoi faire. Je suis venue ici ce soir en voulant oublier ça.", "어떻게 해야 할지 모르겠어. 오늘 밤 이걸 잊으려고 여기 왔는데."),
(A, "Tu devrais y aller.", "가 봐야 해."),
(L, "Quoi ?", "뭐?"),
(A, "Tu devrais y aller. Voir l'agence, rencontrer l'équipe. Tu ne peux pas décider sans savoir.", "가 봐야 해. 회사도 보고 팀도 만나. 모르고 결정할 수는 없잖아."),
(L, "Tu ne voudrais pas que je reste ?", "내가 남길 바라지 않아?"),
(A, "Si. Évidemment que si. Mais ce n'est pas la question.", "그래. 당연히 바라지. 하지만 그게 문제가 아니야."),
(L, "Et c'est quoi, la question ?", "그럼 문제가 뭔데?"),
(A, "La question, c'est ce que tu veux, toi. Pas ce que veulent les autres.", "문제는 네가 원하는 거야. 다른 사람들이 원하는 게 아니라."),
(None, "Une grande gerbe dorée éclate au-dessus de la tour Eiffel. Toute la foule pousse un cri d'admiration. Léa ne regarde plus le ciel.", "에펠탑 위로 커다란 금빛 불꽃 다발이 터진다. 군중이 감탄의 함성을 지른다. 레아는 더 이상 하늘을 보지 않는다."),
(L, "Tu es trop gentil.", "넌 너무 다정해."),
(A, "Je ne suis pas gentil. Je suis lucide. Et je suis un peu terrifié.", "다정한 게 아니야. 냉정한 거지. 그리고 조금 겁이 나."),
(L, "Terrifié ?", "겁이 난다고?"),
(A, "À l'idée que tu partes. Mais je préfère te voir partir en sachant pourquoi, plutôt que rester en le regrettant.", "네가 떠난다는 생각에. 하지만 후회하며 남는 것보다 이유를 알고 떠나는 모습을 보는 쪽이 낫다고 생각해."),
(L, "(prend sa main) Antoine...", "(그의 손을 잡으며) 앙투안..."),
(A, "Regarde le feu d'artifice. C'est le dernier bouquet.", "불꽃놀이 봐. 마지막 폭죽이야."),
(None, "Un bouquet final de feux éclate, immense, des centaines de fusées blanches, rouges et bleues. La foule applaudit et crie.", "마지막 불꽃이 거대하게 터진다. 수백 개의 흰색, 붉은색, 푸른색 불꽃이다. 군중이 박수와 함성을 보낸다."),
(P, "Magnifique ! Absolument magnifique ! Quelle merveille !", "대단해요! 정말 대단해! 얼마나 경이로운지!"),
(G, "Ça valait la peine de monter, hein ?", "올라올 만한 가치가 있었지, 그렇지?"),
(L, "Oui. Ça valait la peine.", "응. 그럴 만했어."),
(None, "La foule commence à se disperser. Madame Pichon est déjà endormie sur son petit fauteuil, un sourire aux lèvres.", "군중이 흩어지기 시작한다. 피숑 부인은 벌써 작은 의자에서 입가에 미소를 띤 채 잠들어 있다."),
(G, "(à voix basse) Elle ne se souviendra pas de ce que je lui ai dit.", "(작은 소리로) 내가 한 얘기를 기억 못 하겠지."),
(A, "Elle s'en souviendra. Elle fera semblant de ne pas s'en souvenir.", "기억하실 거야. 기억 못 하는 척하실 뿐이지."),
(G, "Tu es trop malin pour ton âge.", "네 나이치고는 너무 영리해."),
(A, "C'est le métier.", "직업병이지."),
(L, "Rentrons. Il est tard.", "돌아가자. 늦었어."),
(A, "Je te raccompagne jusqu'à ta porte ?", "문 앞까지 바래다줄까?"),
(L, "Tu habites à quinze numéros de chez moi.", "넌 우리 집에서 열다섯 번지밖에 안 떨어져 살잖아."),
(A, "Raison de plus : ce n'est pas un grand détour.", "그러니 더더욱. 크게 돌아가는 것도 아니지."),
(L, "(sourit) Alors allons-y.", "(미소 지으며) 그럼 가자."),
(None, "Ils descendent lentement les escaliers de Montmartre, au milieu de la foule joyeuse. Au-dessus d'eux, il reste encore quelques traînées de fumée blanche dans le ciel noir.", "두 사람이 즐거운 군중 속에서 몽마르트르 계단을 천천히 내려간다. 머리 위 검은 하늘에는 아직 흰 연기 자국이 몇 줄기 남아 있다."),
(L, "Antoine ? Merci d'être venu ce soir.", "앙투안? 오늘 밤 와 줘서 고마워."),
(A, "Merci de m'avoir invité.", "초대해 줘서 고마워."),
(L, "Je ne t'ai pas invité. On avait décidé ensemble.", "내가 초대한 게 아니라 같이 정한 거였잖아."),
(A, "C'est exactement ça. On a décidé ensemble. J'aime cette phrase.", "바로 그거야. 같이 정했지. 나 이 말 좋아해."),
(L, "Moi aussi.", "나도."),
(A, "Alors on décidera ensemble aussi pour Bordeaux ?", "그럼 보르도도 같이 결정할까?"),
(L, "Je ne sais pas encore. Mais je ne veux pas décider seule.", "아직 모르겠어. 하지만 혼자 결정하고 싶지는 않아."),
(A, "C'est la première fois que tu dis ça.", "그 말은 처음이야."),
(L, "C'est la première fois que je le pense.", "그렇게 생각한 건 처음이거든."),
(None, "Ils arrivent au pied de l'escalier. Un dernier pétard éclate quelque part, très loin. Léa sourit, serre sa main un peu plus fort, et ils continuent à marcher dans la nuit.", "두 사람이 계단 아래에 도착한다. 아주 먼 어딘가에서 마지막 폭죽이 터진다. 레아가 미소 지으며 그의 손을 조금 더 세게 쥐고, 둘은 밤길을 계속 걷는다."),
(A, "Dis-moi, avant que j'oublie : tu aimes la musique classique ?", "잊어버리기 전에 말해 줘. 클래식 음악 좋아해?"),
(L, "Pourquoi cette question ?", "왜 그런 걸 물어?"),
(A, "Parce que le week-end prochain, il y a un concert dans une petite église du Marais. Du Bach, pour dix euros.", "다음 주말에 마레 지구의 작은 성당에서 콘서트가 있어. 바흐인데 10유로야."),
(L, "Du Bach pour dix euros ? Tu connais mes goûts.", "바흐가 10유로? 내 취향을 잘 아네."),
(A, "J'ai fait des recherches sérieuses.", "진지하게 조사했거든."),
]
VOCAB = [
("A2","le quatorze juillet / un feu d'artifice","7월 14일(혁명 기념일) / 불꽃놀이","프랑스 국경일. 에펠탑 불꽃놀이가 대표 행사"),
("A2","une foule / une couverture","군중 / 담요","« Quelle foule ! »"),
("A2","un panier / une chaise pliante","바구니 / 접이식 의자","야외 관람 소품"),
("A2","un souvenir","추억, 기념품","« mon meilleur souvenir du quatorze juillet »"),
("A2","des gougères / du saucisson","구제르(치즈 슈) / 소시송(건조 소시지)","와인 안주로 흔한 음식"),
("B1","Quel spectacle ! / Que c'est beau ! / Comme c'est joli !","얼마나 장관인지! / 정말 아름다워! / 어쩜 이렇게 예쁠까!","감탄문 3종: quel + 명사, que/comme + 절"),
("B1","valoir la peine","~할 가치가 있다","« Ça valait la peine de monter. »"),
("B1","se disperser","흩어지다","군중이 해산하는 모습"),
("B1","faire semblant de","~하는 척하다","« Elle fera semblant de ne pas s'en souvenir. »"),
("B1","une fusée / un bouquet final","불꽃(폭죽) / 마지막 대형 불꽃","불꽃놀이 용어. 'le bouquet final'은 피날레"),
("B2","prendre d'assaut","습격하다, 급습하다","« prendre d'assaut la Bastille »"),
("B2","la Fête de la Fédération","연맹제(1790년 7월 14일)","프랑스 혁명 후 국가 통합을 기념한 축제"),
("B2","un raccourci","지름길, 간략화","« C'est un raccourci. » 역사 교육의 단순화를 비유"),
("B2","lucide / terrifié","냉정한 / 겁에 질린","감정 표현의 대조"),
("B2","tous frais payés","모든 비용 지급","« Deux jours, tous frais payés. » 출장 제안"),
("B2","se souvenir de / se rappeler","기억하다","se souvenir de + 명사, se rappeler + 직접목적어"),
("B2","un détour","우회","« ce n'est pas un grand détour »"),
("C1","Ah ça alors !","세상에! 이럴 수가!","놀람 감탄. 구어 관용구"),
("C1","Tout Paris monte à Montmartre.","파리 사람이 다 몽마르트르로 올라온다.","tout + 고유명사 = 그 도시의 모든 사람(환유 표현)"),
("C1","avoir le dos fragile","허리가 약하다","« Un ange qui a le dos fragile. » 농담조"),
("C1","raison de plus","더더욱","복습 표현. 반론에 대한 응수"),
("C1","trop malin pour son âge","나이에 비해 너무 영리한","약간 놀리는 칭찬"),
("C1","décider ensemble","함께 결정하다","관계의 전환점이 되는 핵심 표현"),
]
GRAM = [
("A2","감탄문 quel / que / comme",
 "« Quelle foule ! » « Quel spectacle ! » (quel + 명사, 성·수 일치) / « Que c'est beau ! » « Comme c'est joli ! » (que/comme + 절). « Qu'est-ce que c'est beau ! » 는 구어."),
("A2","si + 현재, 현재 / 미래",
 "« Si tu veux, on y va. » « Si j'ai le temps, je viendrai. » si 가정(현실적 가능성)은 현재형, 결과는 현재·미래·명령법."),
("B1","조건법 과거: Si on était arrivés plus tard, on aurait dû…",
 "« Si on était arrivés plus tard, on aurait dû rester debout. » si + 대과거, 조건법 과거 = 과거에 일어나지 않은 일의 가정. « Si j'avais eu un professeur comme vous, j'aurais retenu quelque chose. »"),
("B1","복합과거와 반과거(역사 서술)",
 "« Des Parisiens ont pris d'assaut la prison. » (사건) / « Il y avait seulement sept prisonniers. » (배경) / « Le peuple montrait qu'il n'avait plus peur. » (상황 설명). 역사 서술에서는 단순과거도 쓰이지만 구어에서는 복합과거."),
("B1","대과거 plus-que-parfait",
 "« J'avais ouvert la boutique en avril. » « On m'avait toujours dit que… » avoir/être의 반과거 + 과거분사. 과거의 어느 시점보다 앞선 일."),
("B2","직접·간접 목적어 대명사: je ne vous l'ai jamais raconté",
 "« Vous ne m'avez jamais raconté ça. » « Je lui ai dit. » « Il ne me l'a pas dit. » 복합과거에서 대명사는 조동사 앞."),
("B2","jusqu'à / plutôt que / en voulant",
 "« Je te raccompagne jusqu'à ta porte ? » « partir en sachant pourquoi, plutôt que rester en le regrettant » plutôt que + 동사원형. « Je suis venue en voulant oublier ça. » 제롱디프로 동시 동작."),
("C1","c'est la première fois que + 현재/복합과거",
 "« C'est la première fois que tu dis ça. » « C'est la première fois que je le pense. » 처음임을 강조하는 구문. 뒤에는 현재 또는 복합과거. 관계의 변화를 짚어 줄 때 유용."),
]
CULTURE = [
("프랑스의 7월 14일",
 "프랑스 혁명 기념일(Fête nationale)로 오전에는 샹젤리제 군사 퍼레이드, 저녁에는 에펠탑 불꽃놀이가 열린다. 전날 밤에는 소방서가 여는 'bal des pompiers' 무도회가 인기다. 많은 파리 시민이 몽마르트르 언덕, 트로카데로, 샹드마르스 공원에서 불꽃놀이를 본다."),
("바스티유 습격 vs 연맹제",
 "1789년 7월 14일의 바스티유 습격은 혁명의 상징이지만, 국경일로 제정된 것(1880년)은 1790년 7월 14일의 연맹제(Fête de la Fédération)를 기념하기 위해서다. 앙투안이 설명한 '줄임 이야기'가 바로 그 차이다."),
("크레망과 가벼운 안주",
 "야외 피크닉에서는 크레망·샴페인에 구제르(치즈 슈), 소시송, 올리브 같은 가벼운 안주를 곁들인다. 한여름 야외 행사에서는 병 마개를 일회용 마개로 다시 닫을 수 있는 크레망이 편리하다."),
]
META = dict(part=2, ep=15, part_label="제2부 여름의 포도 · Les raisins de l'été", title_fr="Le 14 juillet", title_ko="7월 14일의 불꽃",
 place="몽마르트르 사크레쾨르 계단 · 7월 14일 월요일 21시 30분",
 chars="Léa · Antoine · Gaston · Mme Pichon",
 wine="Crémant (피크닉용 스파클링)",
 focus="감탄문(quel/que/comme), 조건법 과거, 대과거, 역사 서술의 시제, c'est la première fois que",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제16화 « Leçon d'œnologie » : 보르도로 떠나기 전, 앙투안이 준비한 진짜 와인 수업. 조건법으로 말하는 정중한 말투와 레아의 엉뚱한 질문.")
