# -*- coding: utf-8 -*-
L, A = "Léa", "Antoine"
D = [
(None, "Dimanche 20 juillet, 15 h. Léa sonne à la porte d'Antoine, au 27 de la rue Durantin. Elle monte quatre étages en soufflant. Antoine ouvre, un tablier de cuisine autour de la taille.", "7월 20일 일요일 오후 3시. 레아가 뒤랑탱 거리 27번지 앙투안의 집 초인종을 누른다. 숨을 몰아쉬며 4층을 올라온다. 앙투안이 허리에 앞치마를 두른 채 문을 연다."),
(A, "Bonjour, Léa. Tu as trouvé facilement ?", "안녕, 레아. 쉽게 찾았어?"),
(L, "Quinze numéros plus loin que chez moi. Je ne pouvais pas me tromper. Par contre, quatre étages sans ascenseur, ça fait mal aux jambes.", "우리 집에서 열다섯 번지 더 가면 되잖아. 틀릴 수가 없지. 다만 엘리베이터 없는 4층은 다리가 아파."),
(A, "Entre. Pose ton sac où tu veux.", "들어와. 가방은 아무 데나 둬."),
(None, "Elle entre. L'appartement est petit mais lumineux : des étagères de livres du sol au plafond, une grande carte de France au mur, et dans un coin, un petit meuble en bois sombre avec des bouteilles couchées.", "그녀가 들어선다. 집은 작지만 환하다. 바닥에서 천장까지 책이 꽂힌 서가, 벽에 붙은 커다란 프랑스 지도, 그리고 한쪽 구석에는 병들이 눕혀진 어두운 목재 가구가 있다."),
(L, "Waouh. Tu as plus de livres que Gaston n'a de bouteilles.", "와우. 가스통의 병보다 책이 더 많네."),
(A, "C'est un exagération. Disons autant.", "과장이야. 비슷하다고 해 두자."),
(L, "Et ça, c'est ta cave ? Ce petit meuble ?", "그리고 이게 네 와인 저장고야? 이 작은 가구?"),
(A, "Une « cave » de douze bouteilles. C'est modeste, mais c'est ma fierté.", "열두 병짜리 '저장고'야. 소박하지만 내 자랑이지."),
(L, "Douze bouteilles, c'est suffisant pour une leçon ?", "열두 병이면 수업하기에 충분해?"),
(A, "Ça suffit pour une très bonne leçon. J'ai préparé quatre verres, quatre bouteilles, et un plan.", "아주 좋은 수업이 되기엔 충분해. 잔 네 개, 병 네 개, 그리고 계획을 준비했어."),
(L, "Un plan ? Tu as préparé un cours ?", "계획? 수업을 준비했다고?"),
(A, "C'est mon métier. Installe-toi sur le canapé. Je voudrais commencer par une question : comment fait-on le vin ?", "그게 내 직업이잖아. 소파에 앉아. 질문부터 하나 하고 싶어. 와인은 어떻게 만들까?"),
(L, "On presse du raisin et on attend ?", "포도를 짜고 기다리나?"),
(A, "C'est un début. Mais « attendre » se dit « fermenter ». Les levures mangent le sucre du jus et le transforment en alcool.", "시작은 맞아. 하지만 '기다린다'는 말은 '발효'라고 해. 효모가 주스의 당을 먹고 알코올로 바꿔."),
(L, "Les levures ? Ce sont des petits animaux ?", "효모? 작은 동물이야?"),
(A, "Des champignons microscopiques. Ils font tout le travail, le vigneron les surveille.", "현미경으로만 보이는 곰팡이야. 일은 다 걔네가 하고 와인 농부는 지켜보는 거지."),
(L, "Je rêve d'un métier où des champignons font tout le travail.", "버섯이 모든 일을 해 주는 직업이 꿈이야."),
(A, "Le vigneron est comme un chef d'orchestre : il ne joue d'aucun instrument, mais il décide du résultat.", "와인 농부는 지휘자 같아. 어떤 악기도 연주하지 않지만 결과를 결정하지."),
(L, "Une belle image. Et le vin rouge, le vin blanc, ils se font pareil ?", "아름다운 비유야. 그럼 레드와 화이트는 똑같이 만들어?"),
(A, "Non. Pour le rouge, on laisse le jus macérer avec les peaux. C'est dans la peau du raisin que se trouvent la couleur et les tanins.", "아니. 레드는 주스를 껍질과 함께 우려내. 색깔과 탄닌은 포도 껍질에 있거든."),
(L, "Et pour le blanc ?", "화이트는?"),
(A, "On presse directement le raisin, et on enlève les peaux avant la fermentation. Donc pas de couleur, très peu de tanins.", "포도를 바로 압착하고 발효 전에 껍질을 제거해. 그래서 색이 없고 탄닌도 아주 적어."),
(L, "Alors le vin blanc, c'est forcément du raisin blanc ?", "그럼 화이트 와인은 반드시 청포도로 만들어?"),
(A, "Pas forcément ! Le champagne contient souvent du pinot noir, un raisin noir, pressé tout de suite. Le jus d'un raisin noir est blanc.", "꼭 그렇진 않아! 샴페인에는 종종 검은 포도인 피노 누아가 들어가. 바로 짜면 검은 포도도 즙은 하얗거든."),
(L, "Quoi ? Le jus d'un raisin noir est blanc ? Je n'en savais rien !", "뭐? 검은 포도의 즙이 하얗다고? 전혀 몰랐어!"),
(A, "Moi non plus, à ton âge. Mon père m'a montré le jour de mes treize ans, en pressant une grappe de cabernet dans un verre.", "나도 네 나이엔 몰랐어. 열세 살 생일에 아버지가 카베르네 포도송이를 잔에 짜 보이셨지."),
(L, "Tu as treize ans à vie, quand tu parles de ton père.", "아버님 얘기를 할 때 너는 영원히 열세 살 같아."),
(A, "C'est possible. Je trouve ça assez touchant, finalement.", "그럴지도. 결국 꽤 뭉클한 일이라고 생각해."),
(L, "Et le rosé ? Un mélange de rouge et de blanc ?", "그럼 로제는? 레드랑 화이트를 섞은 거야?"),
(A, "Non, surtout pas ! C'est du raisin noir avec une courte macération, quelques heures seulement. Juste assez pour donner un peu de couleur.", "아니, 절대 아냐! 검은 포도를 몇 시간만 짧게 우려낸 거야. 색이 살짝 들 정도로만."),
(L, "Je croyais que c'était un mélange. J'ai vécu dans l'erreur pendant trente-et-un ans.", "섞은 건 줄 알았어. 서른한 해 동안 착각 속에 살았네."),
(A, "Trente-deux dans un mois, je crois ?", "한 달 뒤면 서른둘이지?"),
(L, "Dix-huit août. Tu t'en souviens ?", "8월 18일이야. 기억하고 있어?"),
(A, "Je m'en souviens. J'ai noté la date dans mon agenda, avec un point d'exclamation.", "기억해. 수첩에 느낌표까지 붙여서 적어 놨어."),
(L, "(rit) Bon. Revenons au cours.", "(웃으며) 좋아. 수업으로 돌아가자."),
(A, "Nous allons faire une expérience. Je vais te servir le même vin, un pinot noir de Bourgogne, à deux températures différentes.", "실험을 해 보자. 같은 와인, 부르고뉴 피노 누아를 두 가지 온도로 따라 줄게."),
(L, "Le même vin à deux températures ? Ce sera différent ?", "같은 와인을 두 가지 온도로? 달라질까?"),
(A, "Radicalement. Le premier verre est à quatorze degrés. J'ai mis la bouteille quinze minutes au frigo. Le deuxième est à vingt-deux degrés, la température de la pièce.", "완전히 달라. 첫 번째 잔은 14도야. 병을 냉장고에 15분 넣어 뒀어. 두 번째 잔은 22도, 방 온도지."),
(L, "(goûte le premier) C'est frais, un peu serré. Le fruit est très net, cerise acidulée.", "(첫 번째 잔을 맛본다) 시원하고 약간 조여. 과일 향이 아주 선명해, 새콤한 체리."),
(A, "Maintenant le deuxième.", "이제 두 번째."),
(L, "(goûte le second) Oh ! C'est plus mou. Moins frais. Et il y a plus d'alcool, je le sens dans la gorge.", "(두 번째 잔을 맛본다) 오! 더 흐물흐물해. 덜 시원하고. 알코올이 더 느껴져, 목에서 느껴져."),
(A, "Exactement. Trop chaud, le vin devient lourd. Trop froid, il se ferme. L'idéal pour un rouge, c'est entre quinze et dix-huit degrés.", "정확해. 너무 따뜻하면 무거워지고 너무 차가우면 닫혀 버려. 레드의 이상적인 온도는 15도에서 18도 사이야."),
(L, "Et on dit « chambrer » un vin. Ça veut dire quoi ?", "그리고 와인을 '샹브레'한다고들 하잖아. 무슨 뜻이야?"),
(A, "Littéralement : le mettre à la température de la chambre. Mais autrefois, les chambres étaient beaucoup plus fraîches qu'aujourd'hui. Aujourd'hui, il vaudrait mieux dire « tempérer ».", "문자 그대로는 방 온도에 맞추는 거야. 하지만 예전엔 방이 지금보다 훨씬 서늘했어. 요즘은 '템퍼링'이라고 하는 게 더 나을 거야."),
(L, "Tout le monde dit « chambrer ».", "다들 '샹브레'라고 해."),
(A, "Les mots ont plus de mémoire que les choses.", "말은 물건보다 기억이 길어."),
(L, "C'est ta phrase d'historien ?", "그게 역사학자 문장이야?"),
(A, "Une de mes préférées.", "내가 제일 좋아하는 문장 중 하나야."),
(L, "Dis, pourquoi tu couches les bouteilles dans ton petit meuble ?", "그런데 왜 작은 가구에 병들을 눕혀 놓아?"),
(A, "Pour que le bouchon reste humide. Un bouchon sec laisse entrer l'air, et le vin tourne au vinaigre.", "코르크가 젖어 있게 하려고. 코르크가 마르면 공기가 들어가서 와인이 식초가 돼."),
(L, "Au vinaigre ? Comme une vinaigrette ?", "식초로? 비네그레트처럼?"),
(A, "Exactement. D'ailleurs, « vinaigre » vient de « vin aigre ».", "정확해. 사실 '비네그르'는 '신 와인(vin aigre)'에서 나온 말이야."),
(L, "Tu vois, j'ai bien retenu : les mots ont de la mémoire.", "봐, 잘 기억했지. 말에는 기억이 있다는 거."),
(A, "Tu es une élève dangereuse.", "넌 위험한 학생이야."),
(L, "Et si le bouchon est en plastique ?", "그럼 코르크가 플라스틱이면?"),
(A, "Alors la bouteille peut rester debout. Mais pour un grand vin, je préfère le liège. C'est une question de respect.", "그럼 병을 세워 둬도 돼. 하지만 좋은 와인에는 코르크가 좋아. 존중의 문제야."),
(L, "Respect pour qui ? Pour les arbres ?", "누구에 대한 존중이야? 나무?"),
(None, "Antoine ouvre une troisième bouteille. Il la verse doucement dans une carafe en verre, devant la fenêtre.", "앙투안이 세 번째 병을 연다. 창가에서 유리 카라프에 조심스럽게 따른다."),
(L, "Pourquoi tu verses le vin dans la carafe ?", "왜 와인을 카라프에 따라?"),
(A, "Pour deux raisons. D'abord, pour séparer le vin des dépôts, ces petits cristaux au fond de la bouteille. Ensuite, pour l'aérer : au contact de l'oxygène, un vin jeune s'ouvre.", "두 가지 이유야. 먼저 병 바닥에 있는 작은 결정인 침전물을 와인과 분리하려고. 그다음엔 공기와 닿게 하려고. 산소와 만나면 어린 와인은 열려."),
(L, "Un vin qui s'ouvre ? Il a une porte ?", "와인이 열린다고? 문이라도 있어?"),
(A, "Il a des arômes cachés. L'oxygène les libère. Au début, ils sont timides. Après une heure, ils se mettent à parler.", "숨겨진 향이 있어. 산소가 그걸 풀어 줘. 처음엔 수줍어하다가 한 시간 뒤엔 말하기 시작하지."),
(L, "Comme moi, en soirée.", "파티 때의 나처럼."),
(A, "Exactement comme toi. Je dirais même que tu as besoin d'une carafe.", "정확히 너 같아. 너도 카라프가 필요하다고 말할 정도야."),
(L, "Je ne suis pas un vin !", "난 와인이 아니야!"),
(A, "Alors jouons à ça : si tu étais un vin, tu serais lequel ?", "그럼 그걸로 놀아 보자. 네가 와인이라면 어떤 와인일까?"),
(L, "Moi ? Je ne sais pas. Un vin qui a du caractère mais qui ne fait pas de bruit.", "나? 모르겠어. 개성은 있지만 소란스럽지 않은 와인."),
(A, "Un Chinon. Un Chinon de Cabernet franc, d'un vigneron qui travaille depuis vingt ans sans se faire remarquer.", "시농이야. 20년 동안 눈에 띄지 않고 일한 농부가 만든 카베르네 프랑 시농."),
(L, "Le Chinon « mélancolique », que j'ai trouvé triste ?", "내가 슬프다고 했던 그 '우수에 젖은' 시농?"),
(A, "Oui. Pas par tristesse, mais par profondeur. Tu es profonde, Léa.", "응. 슬퍼서가 아니라 깊이가 있어서. 넌 깊은 사람이야, 레아."),
(L, "(émue) Et toi, tu serais quoi ?", "(감동하여) 그럼 넌 뭐일 것 같아?"),
(A, "À ton avis ?", "네 생각엔?"),
(L, "Un Morgon. Simple en apparence, mais avec beaucoup de choses derrière. Un vin qu'on ne comprend vraiment qu'avec le temps.", "모르공. 겉보기엔 단순하지만 뒤에 많은 게 있어. 시간이 지나야 비로소 이해되는 와인."),
(A, "C'est la plus belle chose qu'on m'ait jamais dite.", "누가 내게 해 준 말 중 가장 아름다워."),
(L, "Ne dis pas ça, je vais pleurer dans ton canapé.", "그런 말 하지 마, 네 소파에서 울 것 같아."),
(A, "Pleure, si tu veux. J'ai des mouchoirs, et du chocolat.", "울고 싶으면 울어. 휴지도 있고 초콜릿도 있어."),
(L, "Du chocolat ? Je pourrais rester ici pour toujours.", "초콜릿이라고? 여기 영원히 있을 수도 있겠어."),
(A, "(un temps) Ce serait une très bonne décision.", "(잠시 후) 아주 좋은 결정일 텐데."),
(None, "Un petit silence. Léa baisse les yeux sur son verre. Antoine se racle la gorge.", "작은 침묵. 레아가 잔을 내려다본다. 앙투안이 헛기침을 한다."),
(A, "Excuse-moi. Je ne voulais pas te mettre la pression.", "미안해. 부담 주려던 건 아니야."),
(L, "Tu ne me mets pas la pression. Tu me dis la vérité. C'est différent.", "부담 주는 게 아니야. 진실을 말하는 거지. 그건 달라."),
(A, "Passons à la quatrième bouteille. Pour la quatrième, je voudrais que tu goûtes les yeux fermés.", "네 번째 병으로 넘어가자. 네 번째는 눈을 감고 맛봐 줬으면 해."),
(L, "Les yeux fermés ? Pourquoi ?", "눈을 감고? 왜?"),
(A, "Parce que quand on ferme les yeux, le goût prend toute la place. On n'est plus distrait par la couleur, par l'étiquette, par les préjugés.", "눈을 감으면 맛이 모든 자리를 차지하거든. 색, 라벨, 편견에 방해받지 않게 돼."),
(L, "D'accord. (Elle ferme les yeux.)", "알겠어. (눈을 감는다.)"),
(A, "(lui tend le verre) Sens d'abord. Ne dis rien. Prends ton temps.", "(잔을 건넨다) 먼저 향을 맡아. 아무 말 하지 마. 천천히 해."),
(L, "(sent, longuement) Hmm. Je sens... des fleurs. Des fleurs blanches. Du miel. Et quelque chose de... très doux. De chaud. Comme un souvenir.", "(오래 맡는다) 음. ...꽃 향이 나. 흰 꽃. 꿀. 그리고 뭔가... 아주 부드럽고 따뜻한 것. 추억 같은."),
(A, "Goûte.", "마셔 봐."),
(L, "(goûte) Oh. C'est liquoreux. Moelleux. Il y a de la pomme cuite, de la cannelle... et une petite note amère, à la fin, comme une écorce d'orange.", "(맛본다) 오. 달콤한 와인이야. 부드러워. 구운 사과, 시나몬이 느껴져... 그리고 끝에 오렌지 껍질 같은 쌉쌀한 맛이 조금."),
(A, "Ouvre les yeux.", "눈을 떠."),
(None, "Elle ouvre les yeux. Antoine tient devant elle la bouteille : un vieux Sauternes, à l'étiquette jaunie.", "그녀가 눈을 뜬다. 앙투안이 그녀 앞에 병을 든다. 라벨이 누렇게 바랜 오래된 소테른이다."),
(L, "Un Sauternes ! De quelle année ?", "소테른이야! 몇 년산이야?"),
(A, "Mille neuf cent quatre-vingt-onze. L'année de ma naissance. Mon père l'a achetée le jour où je suis né.", "1991년산이야. 내가 태어난 해지. 아버지가 내가 태어난 날 이 병을 사셨어."),
(L, "Ta propre année de naissance ? Et pourquoi tu l'ouvres aujourd'hui ?", "네가 태어난 해라고? 그런데 오늘 왜 여는 거야?"),
(A, "Parce qu'on n'ouvre pas un vin de 1991 pour n'importe quelle occasion. Mon père me l'avait donnée en disant : « Garde-la pour un moment qui compte. »", "1991년 와인은 아무 때나 따지 않으니까. 아버지가 이렇게 말씀하며 주셨어. '의미 있는 순간을 위해 간직해라.'"),
(L, "Et c'est un moment qui compte ?", "그리고 지금이 의미 있는 순간이야?"),
(A, "Tu pars pour Bordeaux dans une semaine. Alors oui. Je voulais que tu partes avec une bonne bouteille dans le cœur.", "일주일 뒤에 보르도로 가잖아. 그러니 그래. 네가 좋은 병 하나를 마음에 품고 떠났으면 했어."),
(L, "Antoine...", "앙투안..."),
(A, "Je ne dis pas ça pour te retenir. Je le dis parce que je voudrais que ce vin soit le tien, de maintenant à quand tu reviendras.", "널 붙잡으려고 하는 말이 아니야. 이 와인이 지금부터 네가 돌아올 때까지 네 것이 되길 바라서 하는 말이야."),
(L, "Et si je ne reviens pas ?", "돌아오지 않으면?"),
(A, "Alors ce sera une très belle bouteille pour un très beau souvenir.", "그럼 아주 멋진 추억을 위한 아주 아름다운 병이 되겠지."),
(L, "(prend sa main) Tu es insupportable.", "(그의 손을 잡으며) 넌 정말 못 말려."),
(A, "Pourquoi ?", "왜?"),
(L, "Parce que tu es parfait. Et que c'est insupportable.", "완벽하니까. 그게 견딜 수 없어."),
(None, "Elle se penche et l'embrasse doucement. Dans la carafe, le vin de la troisième bouteille commence à parler. Dans le verre de Léa, le Sauternes de 1991 brille comme de l'ambre.", "그녀가 몸을 숙여 부드럽게 입 맞춘다. 카라프 속에서는 세 번째 병의 와인이 말을 걸기 시작한다. 레아의 잔 속에서는 1991년 소테른이 호박빛으로 반짝인다."),
]
VOCAB = [
("A2","un tablier / une étagère / une carte","앞치마 / 선반 / 지도","집 안 장면에 쓰이는 기본 어휘"),
("A2","un canapé / un mouchoir / du chocolat","소파 / 휴지 / 초콜릿","일상 어휘"),
("A2","une bouteille couchée / une cave","눕혀진 병 / 지하 저장고","와인은 코르크가 젖도록 눕혀 보관"),
("A2","la température / un degré","온도 / 도(℃)","« quatorze degrés »"),
("A2","goûter / sentir / les yeux fermés","맛보다 / 향을 맡다 / 눈을 감고","블라인드 시음의 기본"),
("B1","fermenter / une levure","발효하다 / 효모","« Les levures mangent le sucre. »"),
("B1","presser du raisin / une grappe","포도를 압착하다 / 포도송이","« une grappe de cabernet »"),
("B1","macérer / une peau / un tanin","우려내다 / 껍질 / 탄닌","« macérer avec les peaux »"),
("B1","chambrer / tempérer","실온에 맞추다 / 온도를 맞추다","« chambrer » 는 옛 습관에서 온 말"),
("B1","une carafe / carafer / décanter","카라프 / 카라프에 옮기다 / 디캔팅하다","« verser le vin dans une carafe »"),
("B1","un mouchoir / pleurer","휴지 / 울다","« Pleure, si tu veux. »"),
("B2","un dépôt / un cristal","침전물 / 결정","« séparer le vin des dépôts »"),
("B2","aérer / l'oxygène","공기를 통하게 하다 / 산소","« Au contact de l'oxygène, un vin jeune s'ouvre. »"),
("B2","un chef d'orchestre","지휘자","« Le vigneron est comme un chef d'orchestre. »"),
("B2","un préjugé","편견","« la couleur, l'étiquette, les préjugés »"),
("B2","acidulé / serré / mou","새콤한 / 조여 드는 / 흐물한","온도에 따른 와인 질감 표현"),
("B2","liquoreux / moelleux / cannelle","달콤한 / 부드러운 / 시나몬","소테른 묘사"),
("B2","mettre la pression à quelqu'un","~에게 부담을 주다","« Je ne voulais pas te mettre la pression. »"),
("C1","Les mots ont plus de mémoire que les choses.","말은 사물보다 기억이 길다.","앙투안의 역사학자적 문장"),
("C1","avoir treize ans à vie","평생 열세 살이다","애정 섞인 놀림. 부모 앞에선 영원한 아이"),
("C1","Je n'en savais rien.","전혀 몰랐어.","savoir + en + rien. 구어 강조"),
("C1","une bonne bouteille dans le cœur","마음에 품은 좋은 병","시적 은유. 와인을 정서적 기억으로 비유"),
("C1","C'est la plus belle chose qu'on m'ait jamais dite.","내가 들은 가장 아름다운 말이야.","최상급 + qu'on m'ait dite (접속법 과거)"),
("C1","insupportable / parfait","견딜 수 없는 / 완벽한","« Tu es parfait. Et c'est insupportable. » 사랑의 역설"),
]
GRAM = [
("A2","조건법 현재: 정중한 요청과 희망",
 "« Je voudrais commencer par une question. » « Je voudrais que tu goûtes les yeux fermés. » « Je voulais que tu partes avec une bonne bouteille. » vouloir 조건법 = 정중한 요청. 형태: 미래 어간 + 반과거 어미 (-ais, -ais, -ait, -ions, -iez, -aient)."),
("A2","조건법: 가정의 결과",
 "« Si tu étais un vin, tu serais lequel ? » si + 반과거, 조건법 현재. « Tu serais un Chinon. » « Je pourrais rester ici pour toujours. » 현재의 가정."),
("B1","조건법: 충고 « il vaudrait mieux »",
 "« Il vaudrait mieux dire « tempérer ». » 'il vaut mieux' 의 조건법 = ~하는 편이 더 낫겠다. 완곡한 충고. 뒤에는 동사원형 또는 que + 접속법."),
("B1","c'est-à-dire / car / donc / alors (논리 연결어)",
 "« Pour deux raisons. D'abord… Ensuite… » « C'est un champignon, donc… » 이유·결과·순서를 나타내는 접속사로 설명을 구조화한다."),
("B1","pour + 동사원형 / pour que + 접속법",
 "« Pour séparer le vin des dépôts. » « Pour l'aérer. » 목적: pour + inf. 주어가 다를 때: « Je l'ouvre pour que tu goûtes. » (접속법)."),
("B2","접속법: je voudrais que + 접속법",
 "« Je voudrais que tu goûtes les yeux fermés. » « Je voudrais que ce vin soit le tien. » 소망 + que + 접속법 (goûtes, soit). 주어가 같으면 동사원형: « Je voudrais goûter »."),
("B2","최상급 + que + 접속법 과거",
 "« C'est la plus belle chose qu'on m'ait jamais dite. » 최상급(la plus belle chose) + que + 접속법 과거 (ait dit). 경험에 한정할 때 jamais와 함께 자주 쓰인다."),
("C1","강조: « ne … que / c'est … que »",
 "« On ne comprend vraiment qu'avec le temps. » ne … que = ~해야만 비로소. « C'est dans la peau que se trouvent la couleur et les tanins. » c'est … que 분열문으로 위치 강조."),
]
CULTURE = [
("포도주 만드는 법: 레드, 화이트, 로제",
 "레드는 껍질과 함께 우려내(macération)며 색과 탄닌을 얻고, 화이트는 즙만 발효한다. 로제는 검은 포도를 짧게 우려내는 방식이며 레드와 화이트를 섞은 게 아니다(샴페인 로제 제외). 샴페인의 블랑 드 누아는 검은 포도로 만든 화이트 스파클링이다."),
("서빙 온도와 카라프",
 "레드는 15~18도, 화이트는 8~12도가 적정이다. 'chambrer'는 옛 프랑스 집의 서늘한 방 온도에서 유래했다. 어린 와인은 카라프에 옮겨 산소를 접하게 하고, 오래된 와인은 침전물을 걸러 내는 용도로 디캔팅한다."),
("특별한 날을 위한 병 'une bouteille pour un moment qui compte'",
 "프랑스 가정에는 자녀 출생·결혼 같은 큰 사건을 기념해 와인을 사서 보관하는 전통이 있다. 아이의 출생 연도 빈티지를 간직했다 성인이 되었을 때 함께 여는 것은 흔한 선물이다."),
]
META = dict(part=2, ep=16, part_label="제2부 여름의 포도 · Les raisins de l'été", title_fr="Leçon d'œnologie", title_ko="와인 수업",
 place="앙투안의 집, 뒤랑탱 거리 27번지 4층 · 7월 20일 일요일 15시",
 chars="Léa · Antoine",
 wine="Pinot noir (온도 실험) · 카라프의 와인 · Sauternes 1991",
 focus="조건법(요청·충고·가정), 접속법(je voudrais que), 최상급 + 접속법 과거, 와인 제조 어휘",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제17화 « Au bout du fil » : 보르도 방문 전날 밤, 앙투안이 아버지에게 레아 이야기를 꺼낸다. 접속법과 간접화법으로 풀어 가는 부자의 전화 통화.")
