# -*- coding: utf-8 -*-
L, A, C, H = "Léa", "Antoine", "La guide", "Le réceptionniste"
D = [
(None, "Samedi 2 août, 8 h 20. Gare de l'Est. Léa et Antoine attendent sur le quai, chacun avec un petit sac. Un train pour Reims doit partir dans dix minutes. Léa est rentrée de Bordeaux depuis trois jours.", "8월 2일 토요일 아침 8시 20분. 파리 동역. 레아와 앙투안이 각자 작은 가방을 들고 승강장에서 기다린다. 랭스행 열차가 십 분 뒤 출발한다. 레아는 사흘 전 보르도에서 돌아왔다."),
(A, "Voie 7, voiture 12, places 41 et 42. Je crois que c'est ici.", "7번 승강장, 12호 차량, 41번과 42번 좌석. 여기가 맞는 것 같아."),
(L, "Tu as tout noté ? Tu es sûr que tu n'as pas oublié les billets ?", "다 적어 놨어? 표를 잊은 건 아니지?"),
(A, "Je les ai sur mon téléphone, et sur papier, et dans un deuxième téléphone.", "전화기에도 있고 종이에도 있고 두 번째 전화기에도 있어."),
(L, "Un deuxième téléphone ? Tu en as deux ?", "두 번째 전화기? 두 개 있어?"),
(A, "Non. C'est ton téléphone, que tu m'as confié ce matin.", "아니. 오늘 아침에 네가 맡긴 네 전화기야."),
(L, "(rit) Ah oui. Je suis très organisée, quand tu es là.", "(웃으며) 아 맞다. 네가 있으면 난 아주 철저해지지."),
(None, "Ils montent dans le train. Les places côte à côte sont près d'une grande fenêtre. Le train démarre doucement.", "두 사람이 열차에 오른다. 나란히 붙은 좌석이 커다란 창 옆이다. 열차가 천천히 출발한다."),
(A, "Quarante-cinq minutes, et on sera à Reims. C'est presque plus court que ton trajet jusqu'à chez moi.", "사십오 분이면 랭스에 도착해. 우리 집까지 오는 시간보다 짧을 정도야."),
(L, "J'ai tellement envie d'être déjà arrivée. J'ai besoin de penser à autre chose.", "빨리 도착했으면 좋겠어. 다른 생각을 해야 하거든."),
(A, "À Bordeaux ?", "보르도 일?"),
(L, "Oui. Je ne t'en ai presque pas parlé depuis mon retour.", "응. 돌아온 뒤로 거의 얘기를 안 했네."),
(A, "Tu n'as pas à t'excuser. Tu me raconteras quand tu seras prête.", "미안해할 필요 없어. 준비되면 얘기해 줘."),
(L, "Je suis prête, je crois. Je veux que tu saches.", "준비된 것 같아. 네가 알았으면 해."),
(A, "Je t'écoute.", "듣고 있어."),
(L, "L'agence est dans le quartier des Chartrons, au bord de la Garonne. Un grand entrepôt de pierre, rénové. Ils ont des murs en briques, de grandes baies vitrées, et un jardin intérieur.", "회사는 가론 강변의 샤르트롱 지구에 있어. 개조한 큰 석조 창고야. 벽돌 벽, 커다란 통유리창, 안뜰 정원까지 있어."),
(A, "Ça a l'air magnifique.", "멋있어 보이네."),
(L, "C'est magnifique. Et l'équipe est géniale. Douze personnes, jeunes, créatives, drôles. La directrice, Madame Lacoste, m'a emmenée déjeuner dans un vignoble à Pessac.", "정말 멋있어. 팀도 대단해. 열두 명, 젊고 창의적이고 유쾌해. 라코스트 대표님이 페삭의 포도원에 점심 먹으러 데려가 주셨어."),
(A, "Elle t'a fait une proposition précise ?", "구체적인 제안을 했어?"),
(L, "Oui. Un salaire qui représente presque le double de mon revenu actuel. Un bureau avec vue sur la rivière. Et un budget de création, pour développer ma propre vision.", "응. 지금 수입의 거의 두 배 되는 월급. 강이 보이는 사무실. 그리고 내 비전을 펼칠 창작 예산."),
(A, "C'est une offre extraordinaire.", "대단한 제안이네."),
(L, "Oui. Et c'est exactement ça, le problème.", "응. 그게 바로 문제야."),
(A, "Pourquoi un problème ?", "왜 문제야?"),
(L, "Parce que si l'offre était mauvaise, je dirais non sans hésiter. Mais elle est bonne. Alors je ne sais plus.", "제안이 나빴다면 망설이지 않고 거절했을 거야. 하지만 좋은 제안이야. 그래서 모르겠어."),
(A, "(un temps) Je comprends.", "(잠시 후) 이해해."),
(L, "Tu ne m'en veux pas de ne pas avoir décidé ?", "내가 결정하지 못해서 원망하지 않아?"),
(A, "Jamais. Je t'ai dit que je voulais que tu décides pour toi, pas pour moi.", "절대. 널 위해 결정하길 바란다고 했잖아, 나 때문이 아니라."),
(L, "Je sais. C'est ce qui rend les choses plus difficiles. Si tu m'avais demandé de rester, j'aurais pu te dire non. Je serais en colère. Ce serait plus simple.", "알아. 그래서 더 힘들어. 네가 남아 달라고 했다면 거절할 수 있었을 거야. 화가 났겠지. 그게 더 간단했을 텐데."),
(A, "Je préfère que ce soit difficile et honnête.", "어렵더라도 정직한 쪽이 좋아."),
(L, "(sourit) Tu es un homme impossible.", "(미소 지으며) 넌 정말 곤란한 사람이야."),
(None, "Le train file à travers les champs de blé et de maïs. À l'horizon, les premières collines de vignes apparaissent, d'un vert très intense.", "열차가 밀밭과 옥수수밭을 가로질러 달린다. 지평선에 첫 포도 언덕들이 아주 짙은 초록빛으로 나타난다."),
(A, "Regarde. Les vignes de Champagne. On entre dans le vignoble.", "봐. 샹파뉴 포도밭이야. 포도원 지대로 들어서는 거야."),
(L, "C'est beau. Plus ordonné que ce que je pensais : toutes ces lignes parfaites.", "아름답다. 생각보다 더 정돈돼 있어. 저 완벽한 줄들."),
(A, "En Champagne, les vignes sont taillées très bas, pour résister au froid. Et elles produisent le vin le plus célèbre du monde.", "샹파뉴에서는 추위를 견디도록 포도나무를 아주 낮게 가지치기해. 그리고 세계에서 가장 유명한 와인을 만들지."),
(L, "Tu seras mon guide, ce week-end ?", "이번 주말엔 네가 내 가이드가 되어 줄 거야?"),
(A, "Non. J'ai réservé une vraie guide, dans une maison de champagne. Je suis historien, pas guide.", "아니. 샴페인 하우스에 진짜 가이드를 예약했어. 난 역사학자지 가이드가 아니야."),
(L, "Tu es les deux. Mais d'accord, je laisserai la vraie guide faire son travail.", "넌 둘 다야. 하지만 좋아, 진짜 가이드가 일하게 놔둘게."),
(None, "Trois heures plus tard. Dans les sous-sols de la maison Vautrain, à vingt mètres de profondeur. Un long couloir de craie blanche, éclairé par de petites lampes. Une jeune guide marche devant eux.", "세 시간 뒤. 보트랭 샴페인 하우스의 지하 20미터. 작은 등으로 밝힌 하얀 백악질의 긴 복도. 젊은 가이드가 그들 앞에서 걷는다."),
(C, "Bienvenue dans les crayères de la maison Vautrain. Ici, il fait dix degrés toute l'année, hiver comme été. La craie conserve la fraîcheur et l'humidité.", "보트랭 하우스의 크레예르(백악 저장고)에 오신 것을 환영합니다. 여기는 겨울이나 여름이나 일 년 내내 10도입니다. 백악이 서늘함과 습기를 유지해 주죠."),
(L, "Il fait froid !", "춥네요!"),
(C, "C'est pour ça que je vous ai conseillé de prendre une veste, mademoiselle. Mais je vous promets que vous aimerez ce qui vous attend.", "그래서 재킷을 챙기라고 권해 드렸어요, 아가씨. 하지만 기다리는 것이 마음에 드실 거라고 약속드려요."),
(A, "Combien de bouteilles dorment ici ?", "여기에 몇 병이 잠들어 있나요?"),
(C, "Environ quatre millions. Certaines depuis dix ans, d'autres depuis vingt. Elles attendent patiemment.", "약 4백만 병이요. 어떤 병은 십 년, 어떤 병은 이십 년 동안. 인내심 있게 기다리고 있죠."),
(L, "Quatre millions de bouteilles qui attendent. C'est presque poétique.", "기다리는 병이 4백만 개라니. 거의 시적이네요."),
(C, "La patience est le principal ingrédient du champagne. Voulez-vous que je vous explique la méthode champenoise ?", "인내심이 샴페인의 주재료예요. 샹파뉴 방식을 설명해 드릴까요?"),
(A, "Avec plaisir.", "기꺼이요."),
(C, "Tout d'abord, on fait un premier vin, un vin blanc tranquille, sans bulles. C'est le vin de base.", "먼저 기포가 없는 첫 번째 화이트 와인, 기본 와인을 만들어요."),
(C, "Ensuite, on assemble plusieurs vins de plusieurs raisins, plusieurs villages, plusieurs années. C'est l'assemblage, l'art du maître de chai.", "그다음 여러 포도, 여러 마을, 여러 해의 와인을 블렌딩해요. 그게 아상블라주, 셀러 마스터의 예술이죠."),
(L, "Un art de mélanger. Comme les peintres avec les couleurs.", "섞는 예술이네요. 화가들이 색을 섞듯이."),
(C, "Exactement. Puis on met le vin en bouteille avec un peu de sucre et de levures. La seconde fermentation commence. Elle crée les bulles, en pleine bouteille.", "그다음 약간의 설탕과 효모를 넣어 병에 담아요. 두 번째 발효가 시작되죠. 병 속에서 기포가 만들어집니다."),
(L, "Les bulles se forment dans la bouteille ?", "기포가 병 속에서 만들어진다고요?"),
(C, "Oui. Le gaz carbonique ne peut pas s'échapper, il se dissout dans le vin. C'est pour ça que les bouteilles de champagne sont si épaisses et si lourdes.", "네. 이산화탄소가 빠져나가지 못하고 와인에 녹아들어요. 그래서 샴페인 병이 그렇게 두껍고 무겁죠."),
(A, "Ça explique pourquoi un bouchon de champagne peut aller jusqu'à cinquante kilomètres à l'heure.", "그래서 샴페인 코르크가 시속 50킬로미터까지 날아갈 수 있는 거군요."),
(C, "Vous êtes bien renseigné, monsieur. Je dirais même soixante, dans certaines conditions.", "잘 알고 계시네요, 선생님. 어떤 조건에서는 60킬로미터까지도 가요."),
(L, "Il m'a parlé du bouchon de champagne pendant tout le trajet. Je ne le croyais pas.", "기차에서 내내 샴페인 코르크 얘기를 했어요. 안 믿었는데."),
(A, "J'ai tendance à trop parler quand je suis nerveux.", "긴장하면 말이 많아지는 경향이 있어."),
(L, "Tu es nerveux ?", "너 긴장했어?"),
(A, "Un peu. J'espère que tu vas aimer.", "조금. 네가 좋아하길 바라거든."),
(L, "(sourit) J'aime déjà.", "(미소 지으며) 벌써 좋아."),
(C, "Passons au remuage. Les bouteilles sont placées sur des pupitres, la tête en bas. Chaque jour, un remueur les tourne d'un huitième de tour.", "르뮈아주로 넘어가죠. 병들은 병목이 아래로 가도록 푸피트르에 세워져요. 매일 작업자가 병을 8분의 1바퀴씩 돌립니다."),
(L, "Chaque jour ? Pendant combien de temps ?", "매일이요? 얼마 동안이요?"),
(C, "Pendant six à huit semaines. Autrefois, un bon remueur pouvait tourner quarante mille bouteilles par jour.", "6주에서 8주 동안이요. 예전에는 숙련된 작업자가 하루에 4만 병을 돌릴 수 있었어요."),
(L, "Quarante mille ! Il devait avoir des poignets d'acier.", "4만 병이요! 손목이 강철이었겠네요."),
(C, "Aujourd'hui, c'est surtout fait par des machines. Mais les remueurs d'autrefois, nous les respectons encore.", "오늘날에는 주로 기계가 해요. 하지만 예전의 작업자들을 우리는 지금도 존경해요."),
(A, "C'est un travail de patience et de précision.", "인내와 정밀함의 일이네요."),
(C, "Comme toute chose qui vaut la peine. Venez, je vous emmène à la salle de dégustation.", "가치 있는 모든 일이 그렇죠. 오세요, 시음실로 안내해 드릴게요."),
(None, "La salle de dégustation : une grande pièce voûtée, avec une table en pierre. Trois flûtes sont alignées devant chacun. La guide sert un premier champagne, d'un jaune pâle, parcouru de fines bulles.", "시음실은 아치형 천장의 큰 방이고 돌 탁자가 있다. 각자 앞에 샴페인 잔 세 개가 놓여 있다. 가이드가 연한 노란색에 가는 기포가 올라오는 첫 번째 샴페인을 따른다."),
(C, "Notre brut sans année. Vingt pour cent de pinot noir, soixante de chardonnay, vingt de pinot meunier. Observez le perlage : ces petites bulles qui montent sans arrêt.", "저희 브뤼 논빈티지입니다. 피노 누아 20퍼센트, 샤르도네 60퍼센트, 피노 뫼니에 20퍼센트예요. 기포의 흐름을 보세요. 쉬지 않고 올라오는 작은 기포들."),
(L, "Elles sont si fines... C'est hypnotique.", "정말 가늘다... 최면에 걸리는 것 같아요."),
(C, "Plus les bulles sont fines, plus le champagne est élégant. Goûtez.", "기포가 가늘수록 샴페인이 더 우아해요. 맛보세요."),
(L, "(goûte) Il y a de la brioche, du citron, des amandes grillées. Et la mousse est très crémeuse.", "(맛본다) 브리오슈, 레몬, 구운 아몬드 향이 나요. 그리고 거품이 아주 크리미해요."),
(C, "Excellent ! Vous avez un nez remarquable.", "훌륭해요! 코가 놀랍네요."),
(A, "C'est une élève douée. Elle apprend très vite.", "재능 있는 학생이에요. 아주 빨리 배워요."),
(C, "Alors voici le deuxième verre : notre blanc de blancs, cent pour cent chardonnay. Plus minéral, plus tendu.", "그럼 두 번째 잔입니다. 블랑 드 블랑, 샤르도네 100퍼센트예요. 더 미네랄하고 더 팽팽해요."),
(L, "(goûte) C'est frais. Presque salé. Comme une brise de mer.", "(맛본다) 시원해요. 거의 짠맛이 나요. 바닷바람 같아요."),
(C, "Et le troisième : notre cuvée spéciale, réservée aux grandes occasions. Un champagne de dix ans, qui a vieilli dans ces caves.", "그리고 세 번째는 큰 행사를 위한 특별 퀴베입니다. 이 저장고에서 십 년 숙성된 샴페인이에요."),
(None, "Elle sert le troisième verre. La robe est dorée, la mousse fine et persistante. Léa le sent longuement avant de boire.", "그녀가 세 번째 잔을 따른다. 색은 황금빛이고 거품은 가늘고 오래 지속된다. 레아가 마시기 전에 오래 향을 맡는다."),
(L, "Oh. C'est complètement différent. Des fruits secs, du caramel, du pain grillé... et une longueur infinie.", "오. 완전히 달라요. 말린 과일, 캐러멜, 구운 빵... 그리고 끝없는 여운."),
(A, "Ça fait combien de caudalies ?", "몇 코달리쯤 돼?"),
(L, "Je dirais vingt-cinq. Peut-être trente.", "스물다섯쯤. 어쩌면 서른."),
(C, "Vous connaissez les caudalies ? Je suis impressionnée. La plupart de nos visiteurs ne connaissent même pas le mot « brut ».", "코달리를 아세요? 인상 깊네요. 대부분의 방문객은 '브뤼'라는 단어조차 몰라요."),
(L, "J'ai un très bon professeur.", "아주 좋은 선생님이 있어서요."),
(A, "(un peu rouge) Elle exagère.", "(얼굴이 약간 붉어지며) 과장하는 거예요."),
(C, "Je vois. Bon, je vous laisse savourer. Quand vous aurez fini, passez à la boutique : nous proposons une offre de bienvenue pour les couples.", "알겠어요. 자, 마음껏 즐기세요. 끝나시면 매장에 들러 보세요. 커플을 위한 환영 이벤트가 있어요."),
(L, "(à Antoine, à voix basse) Elle a dit « les couples ».", "(앙투안에게 작은 소리로) 방금 '커플'이라고 했어."),
(A, "(à voix basse) J'ai entendu.", "(작은 소리로) 들었어."),
(L, "Tu ne l'as pas corrigée.", "고쳐 주지 않았네."),
(A, "Toi non plus.", "너도 안 그랬잖아."),
(None, "Ils échangent un regard. Léa lève son verre.", "둘이 눈빛을 주고받는다. 레아가 잔을 든다."),
(L, "À Reims. À la patience. Et aux bulles qui montent sans jamais s'arrêter.", "랭스를 위해. 인내를 위해. 그리고 멈추지 않고 올라가는 기포를 위해."),
(A, "À nous.", "우리를 위해."),
(L, "À nous.", "우리를 위해."),
(A, "Après ça, je t'emmène dîner près de la cathédrale. J'ai réservé.", "이거 끝나고 대성당 근처로 저녁 먹으러 데려갈게. 예약해 놨어."),
(None, "Le soir, à l'hôtel de la Cathédrale. Dans le hall, un réceptionniste consulte son écran avec une expression embarrassée.", "저녁, 대성당 호텔. 로비에서 접수 직원이 곤란한 표정으로 화면을 확인한다."),
(H, "Je suis vraiment désolé, monsieur. J'ai deux réservations à votre nom. Une pour une chambre double, et une pour une chambre simple. Il y a eu une erreur de système.", "정말 죄송합니다, 선생님. 성함으로 예약이 두 건 있습니다. 더블룸 하나와 싱글룸 하나요. 시스템 오류가 있었어요."),
(A, "J'avais réservé deux chambres simples. Une pour Léa, une pour moi.", "싱글룸 두 개를 예약했는데요. 레아 것 하나, 제 것 하나."),
(H, "C'est ce que j'ai compris. Mais le système n'en a enregistré qu'une, et une chambre double. Et ce soir, l'hôtel est complet à cause du festival de musique.", "그렇게 이해했습니다. 하지만 시스템에는 한 개만, 그것도 더블룸으로 등록돼 있어요. 오늘 밤은 음악 축제 때문에 호텔이 만실입니다."),
(L, "Il n'y a vraiment aucune autre chambre ?", "정말 다른 방이 하나도 없어요?"),
(H, "Aucune, mademoiselle. Je me suis permis d'appeler trois hôtels voisins : tous complets. La seule solution, c'est la chambre double.", "하나도요, 아가씨. 근처 호텔 세 군데에 전화해 봤는데 모두 만실입니다. 유일한 해결책은 더블룸이에요."),
(A, "Bon. Léa, je peux dormir sur le canapé s'il y en a un, ou dans le couloir.", "그렇군. 레아, 소파가 있으면 거기서 자거나 복도에서 잘게."),
(H, "La chambre a deux lits jumeaux, monsieur. Ils sont séparés par une table de nuit.", "객실에는 트윈 침대가 두 개 있습니다, 선생님. 협탁으로 분리되어 있고요."),
(A, "Deux lits jumeaux ?", "트윈 침대 두 개요?"),
(L, "(rit) Alors le problème est résolu. Je prends celui près de la fenêtre.", "(웃으며) 그럼 해결됐네. 난 창가 쪽 침대를 쓸게."),
(A, "(rougit) Tu es sûre ?", "(얼굴이 붉어지며) 확실해?"),
(L, "Oui. Je ne vois pas où est le problème. Nous sommes des adultes. Et je te fais confiance.", "응. 문제가 뭔지 모르겠어. 우린 어른이잖아. 그리고 널 믿어."),
(A, "Merci. Je te promets de ronfler très discrètement.", "고마워. 아주 조용히 코를 골겠다고 약속할게."),
(H, "Voici la clé, chambre 12, au deuxième étage. Je vous souhaite une excellente soirée à Reims.", "열쇠입니다, 12호실, 3층이에요. 랭스에서 즐거운 저녁 보내세요."),
(L, "Merci. Et ne vous excusez plus : c'est le plus beau malentendu de la semaine.", "감사합니다. 더는 사과하지 마세요. 이번 주 가장 아름다운 오해예요."),
(None, "Ils montent l'escalier ensemble. Dans le couloir, l'écho de leurs pas se mêle à la musique lointaine du festival.", "두 사람이 함께 계단을 오른다. 복도에서 발소리 메아리가 멀리서 들리는 축제 음악과 섞인다."),
]
VOCAB = [
("A2","un quai / une voie / une voiture / une place","승강장 / 선로·번호 / 객차 / 좌석","기차 관련 기본 어휘. « Voie 7, voiture 12, places 41 et 42. »"),
("A2","un billet / réserver / une réservation","표 / 예약하다 / 예약","« J'ai réservé deux chambres. »"),
("A2","une chambre double / simple / des lits jumeaux","더블룸 / 싱글룸 / 트윈 침대","호텔 객실 유형"),
("A2","une clé / un étage / un hall","열쇠 / 층 / 로비","« chambre 12, au deuxième étage »"),
("A2","frais / froid / une veste","시원한 / 차가운 / 재킷","« Il fait dix degrés toute l'année. »"),
("B1","une gare / un trajet / démarrer","역 / 이동 거리 / 출발하다","« Le train démarre doucement. »"),
("B1","un entrepôt / une baie vitrée","창고 / 통유리창","보르도 샤르트롱 지구의 사무실 묘사"),
("B1","un vignoble / une vigne / tailler","포도원 지대 / 포도나무 / 가지치기하다","« Les vignes sont taillées très bas. »"),
("B1","une guide / une visite / une boutique","여성 가이드 / 견학 / 매장","maison de champagne 방문의 기본 어휘"),
("B1","la craie / une crayère","백악 / 크레예르(백악 저장고)","랭스의 지하 석회암 채석장 저장고"),
("B1","le réceptionniste / complet","접수 직원 / 만실","« l'hôtel est complet »"),
("B2","la méthode champenoise / un assemblage","샹파뉴 방식 / 블렌딩","샴페인 제조의 핵심. « l'assemblage, l'art du maître de chai »"),
("B2","le remuage / un pupitre / un remueur","르뮈아주(병 돌리기) / 병꽂이 / 병 돌리는 작업자","침전물을 병목에 모으는 전통 공정"),
("B2","le perlage / la mousse / une flûte","기포의 흐름 / 거품 / 샴페인 잔","샴페인 시음 용어"),
("B2","brut / un blanc de blancs / une cuvée","브뤼(드라이) / 블랑 드 블랑 / 퀴베","샴페인 종류 표현"),
("B2","un maître de chai","셀러 마스터","블렌딩을 결정하는 책임자"),
("B2","embarrassé(e) / un malentendu","곤란한 / 오해","호텔 직원 표정 묘사"),
("B2","je me suis permis de","실례를 무릅쓰고 ~했습니다","정중한 사과성 표현"),
("C1","hypnotique / remarquable","최면 같은 / 놀라운","형용사 확장"),
("C1","une longueur infinie","끝없는 여운","와인 여운의 극찬 표현"),
("C1","avoir des poignets d'acier","손목이 강철이다","과장된 비유로 존경을 표현"),
("C1","le plus beau malentendu de la semaine","이번 주 가장 아름다운 오해","반어적 낭만 표현"),
("C1","À nous.","우리를 위해.","간결한 건배. 관계의 변화를 보여 줌"),
]
GRAM = [
("A2","장소 전치사: à / en / dans / chez / sous",
 "« à Reims », « en Champagne », « dans les sous-sols », « chez moi », « sous terre ». 도시: à, 프랑스 지방(여성): en, 건물·내부: dans. « un tunnel sous la ville »."),
("A2","단순미래: aller → irai, être → serai",
 "« Quarante-cinq minutes, et on sera à Reims. » « Tu me raconteras quand tu seras prête. » « J'espère que tu vas aimer. » (근접미래) 단순미래는 부정사 + ai, as, a, ons, ez, ont."),
("B1","si + 반과거, 조건법 현재",
 "« Si l'offre était mauvaise, je dirais non sans hésiter. » « Si tu m'avais demandé… » (과거 가정). 현재의 비현실적 가정은 반과거 + 조건법 현재."),
("B1","조건법 과거: si + 대과거, 조건법 과거",
 "« Si tu m'avais demandé de rester, j'aurais pu te dire non. » « Je serais en colère. » 과거에 일어나지 않은 일의 가정과 결과."),
("B1","plus … plus … 비례 구문",
 "« Plus les bulles sont fines, plus le champagne est élégant. » plus + 형용사, plus + 형용사: ~할수록 ~하다. « Plus on attend, plus c'est bon. »"),
("B2","수동·추상 설명: on / c'est pour ça que",
 "« On assemble plusieurs vins. » « C'est pour ça que les bouteilles sont si épaisses. » on은 일반적 주어. c'est pour ça que = 그래서 ~하다."),
("B2","접속법: je veux que tu saches / j'espère que",
 "« Je veux que tu saches. » (접속법: sache) « J'espère que tu vas aimer. » (직설법: espérer que + 직설법). 상반된 구조를 주의."),
("C1","대명동사 복합과거와 간접 요청",
 "« Je me suis permis d'appeler trois hôtels. » se permettre de + inf. = 실례를 무릅쓰고 ~하다. 접객·비즈니스 맥락에서 사과의 표현으로 자주 쓰인다."),
]
CULTURE = [
("샴페인 제조: méthode champenoise",
 "샴페인은 1차 발효 후 블렌딩(assemblage)하고, 병 속에서 2차 발효(prise de mousse)를 거치며 기포를 만든다. 병목에 모인 침전물을 르뮈아주로 모은 뒤 데고르주망(dégorgement)으로 제거한다. 최소 15개월(논빈티지)에서 36개월(빈티지) 숙성이 법적으로 요구된다."),
("랭스(Reims)의 crayères",
 "랭스의 지하에는 로마 시대부터 파낸 백악 채석장이 있어 샴페인 하우스들이 저장고로 사용한다. 지하 10~30m에 일정한 10~12℃ 온도가 유지된다. 일부는 유네스코 세계유산(샴페인 언덕·하우스·저장고)에 포함된다."),
("프랑스 호텔과 'lits jumeaux'",
 "chambre double은 더블베드, chambre twin은 lits jumeaux(트윈)를 뜻한다. 예약 시 침대 유형을 꼭 확인해야 하며, 축제 기간(여름)에는 시스템 오류나 만실이 흔하다."),
]
META = dict(part=2, ep=18, part_label="제2부 여름의 포도 · Les raisins de l'été", title_fr="Week-end en Champagne", title_ko="샹파뉴 주말",
 place="파리 동역 → 랭스(Reims), 샴페인 하우스 지하 저장고와 호텔 · 8월 2일 토요일",
 chars="Léa · Antoine · La guide (샴페인 하우스 가이드) · Le réceptionniste (호텔 직원)",
 wine="Champagne (brut sans année, blanc de blancs, cuvée spéciale)",
 focus="여행·호텔 어휘, 장소 전치사, 단순미래, 조건법 과거, plus…plus 구문, 샴페인 제조 용어",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제19화 « L'orage » : 일요일 포도밭 한가운데서 만난 폭풍우. 오두막에 갇혀 서로의 오래된 상처를 처음으로 털어놓는다.")
