# -*- coding: utf-8 -*-
L, A, V = "Léa", "Antoine", "Le vigneron"
D = [
(None, "Dimanche 3 août, 14 h. Dans les vignes de la Montagne de Reims, au-dessus du village de Verzenay. Léa et Antoine marchent sur un chemin de terre entre deux rangées de vignes. Le ciel, d'abord bleu, commence à se couvrir de gros nuages gris.", "8월 3일 일요일 오후 2시. 랭스 산지, 베르즈네 마을 위쪽 포도밭. 레아와 앙투안이 포도나무 두 줄 사이 흙길을 걷는다. 처음엔 파랗던 하늘이 서서히 두꺼운 회색 구름으로 덮이기 시작한다."),
(L, "Tu as vu ces nuages ? Ils sont arrivés très vite.", "저 구름 봤어? 아주 빨리 몰려왔어."),
(A, "Ils étaient déjà là ce matin, à l'horizon. J'aurais dû t'en parler.", "아침에 이미 지평선에 있었어. 말했어야 했는데."),
(L, "Tu aurais dû ? Tu pensais qu'il allait pleuvoir ?", "말했어야 한다고? 비가 올 거라고 생각했어?"),
(A, "Un orage, plutôt. Il faisait trop chaud, trop lourd. Dans le vignoble, on apprend à lire le ciel.", "비라기보다 뇌우일 것 같았어. 너무 덥고 습했거든. 포도원에서는 하늘 읽는 법을 배워."),
(L, "Et maintenant, qu'est-ce que le ciel te dit ?", "그럼 지금 하늘은 뭐라고 말해?"),
(A, "Qu'il faut vite trouver un abri.", "얼른 피할 곳을 찾으라고."),
(None, "Un premier coup de tonnerre éclate au loin. Les feuilles de vigne frémissent. Le vent se lève d'un seul coup.", "첫 천둥소리가 멀리서 터진다. 포도 잎이 떨린다. 바람이 갑자기 거세진다."),
(L, "Antoine ! Il y a une cabane là-bas, tout en haut de la colline !", "앙투안! 저기 언덕 꼭대기에 오두막이 있어!"),
(A, "Une cabane de vigne ! Cours, Léa, on n'a pas beaucoup de temps !", "포도밭 오두막이야! 뛰어, 레아, 시간이 많지 않아!"),
(None, "Ils courent sur le chemin, les sacs à l'épaule. Les premières grosses gouttes tombent, froides et lourdes. Au moment où ils atteignent la cabane, la pluie se met à tomber à verse.", "두 사람이 가방을 멘 채 길을 달린다. 첫 굵은 빗방울이 차갑고 무겁게 떨어진다. 오두막에 닿는 순간 비가 쏟아지기 시작한다."),
(L, "(essoufflée) On a réussi ! Je suis trempée jusqu'aux os.", "(숨을 헐떡이며) 해냈어! 뼛속까지 젖었어."),
(A, "Moi aussi. Heureusement, la cabane est solide.", "나도. 다행히 오두막이 튼튼하네."),
(None, "La cabane, en pierre sèche, ne contient qu'un banc de bois, une vieille table, et une lampe à pétrole. Sur le mur, un calendrier de 1987 est resté accroché.", "마른 돌로 지은 오두막 안에는 나무 의자, 낡은 탁자, 석유 등이 전부다. 벽에는 1987년 달력이 그대로 걸려 있다."),
(L, "Quelqu'un a oublié de changer le calendrier il y a trente-huit ans.", "누군가 38년 전에 달력 바꾸는 걸 잊었나 봐."),
(A, "Ou quelqu'un a voulu arrêter le temps. Je comprends l'idée.", "아니면 누군가 시간을 멈추고 싶었는지도. 그 마음 이해해."),
(None, "Léa sort de son sac une demi-bouteille enveloppée dans un torchon : le cadeau de bienvenue de la maison Vautrain.", "레아가 행주에 싼 하프 보틀 하나를 가방에서 꺼낸다. 보트랭 하우스에서 받은 환영 선물이다."),
(L, "J'ai une idée. La guide m'a donné une demi-bouteille hier soir. On l'ouvre ?", "생각이 있어. 어제 저녁 가이드가 하프 보틀을 줬거든. 열어 볼까?"),
(A, "Dans une cabane de vigne, pendant l'orage ? C'est la meilleure idée de la semaine.", "포도밭 오두막에서, 뇌우 속에서? 이번 주 최고의 생각이야."),
(L, "Mais on n'a pas de flûtes.", "하지만 샴페인 잔이 없잖아."),
(A, "J'ai deux gobelets en métal dans mon sac. Je les ai pris pour le café.", "가방에 금속 컵 두 개가 있어. 커피용으로 챙겼거든."),
(L, "Un champagne de dix ans dans un gobelet de camping. Les Champenois vont nous bannir.", "10년 된 샴페인을 캠핑용 컵에. 샹파뉴 사람들이 우릴 추방하겠어."),
(A, "Ils nous pardonneront. Les circonstances sont atténuantes.", "용서해 줄 거야. 정상 참작할 사정이 있잖아."),
(None, "Antoine fait sauter le bouchon avec précaution. Un « pop » discret résonne entre les pierres. Il verse deux gobelets.", "앙투안이 조심스럽게 코르크를 딴다. 작은 '퐁' 소리가 돌 사이에 울린다. 그가 컵 두 개에 따른다."),
(L, "À la patience.", "인내를 위해."),
(A, "Et à l'orage.", "그리고 뇌우를 위해."),
(None, "Un éclair illumine l'intérieur, suivi presque aussitôt d'un coup de tonnerre assourdissant. Léa sursaute.", "번개가 오두막 안을 환하게 비춘 뒤 곧바로 귀가 먹먹한 천둥이 친다. 레아가 깜짝 놀란다."),
(L, "(rit nerveusement) Pardon. J'ai toujours eu peur de l'orage.", "(긴장해서 웃으며) 미안. 난 늘 뇌우를 무서워했어."),
(A, "Il n'y a pas de honte. Viens t'asseoir près de moi.", "부끄러운 일 아니야. 내 옆에 앉아."),
(None, "Ils s'assoient sur le banc. Antoine retire sa veste mouillée et la pose sur les épaules de Léa.", "둘이 의자에 앉는다. 앙투안이 젖은 재킷을 벗어 레아의 어깨에 걸쳐 준다."),
(L, "Tu vas avoir froid.", "너 추울 거야."),
(A, "J'ai l'habitude. À treize ans, j'ai dormi une nuit entière dans une cabane comme celle-ci pendant les vendanges.", "난 익숙해. 열세 살 때 수확철에 이런 오두막에서 밤새 잔 적이 있어."),
(L, "Pourquoi ?", "왜?"),
(A, "J'avais fait une bêtise. Je m'étais disputé avec mon père, et j'avais disparu dans les vignes.", "사고를 쳤거든. 아버지와 다투고 포도밭으로 사라졌어."),
(L, "Tu t'étais disputé pour quoi ?", "무슨 일로 다퉜는데?"),
(A, "Pour ma mère. Elle était à l'hôpital depuis un mois. Il ne voulait pas que je lui rende visite parce qu'il disait que c'était trop dur pour un enfant.", "어머니 일 때문에. 어머니가 한 달째 병원에 계셨어. 아버지는 아이한테는 너무 힘들다며 내가 병문안 가는 걸 원치 않으셨어."),
(L, "(doucement) Et toi, tu voulais y aller.", "(부드럽게) 그리고 넌 가고 싶었고."),
(A, "J'avais besoin de la voir. J'avais l'impression que si je ne la voyais pas, elle disparaîtrait.", "어머니를 봐야만 했어. 못 보면 사라질 것 같았거든."),
(L, "Et alors ?", "그래서?"),
(A, "Il m'a retrouvé le lendemain matin, dans la cabane. Il ne m'a pas grondé. Il m'a pris dans ses bras et il m'a emmené à l'hôpital.", "다음 날 아침에 오두막에서 나를 찾으셨어. 야단치지 않으셨지. 안아 주시고 병원으로 데려가셨어."),
(L, "Et tu as pu la voir ?", "어머니를 볼 수 있었어?"),
(A, "Oui. Pendant vingt minutes. Elle dormait presque tout le temps. Mais elle a serré ma main une fois, très doucement. Elle est morte trois jours plus tard.", "응. 이십 분 동안. 대부분 주무셨어. 하지만 한 번 내 손을 아주 부드럽게 쥐셨지. 사흘 뒤에 돌아가셨어."),
(None, "Un long silence. Dehors, la pluie martèle le toit de la cabane. Léa pose sa main sur celle d'Antoine.", "긴 침묵이 흐른다. 밖에서는 빗줄기가 오두막 지붕을 두드린다. 레아가 앙투안의 손 위에 손을 얹는다."),
(L, "Merci de me l'avoir raconté.", "얘기해 줘서 고마워."),
(A, "Je ne l'ai jamais dit à personne. Même pas à Claire.", "누구에게도 한 적 없어. 클레르에게도."),
(L, "Pourquoi à moi ?", "왜 나한테는 말했어?"),
(A, "Parce que ce soir, dans cette cabane, j'ai senti que je pouvais.", "오늘 이 오두막에서 해도 되겠다고 느꼈거든."),
(L, "(émue) Alors à mon tour. Je vais te raconter quelque chose que personne ne sait. Pas même mon frère.", "(감동하여) 그럼 이제 내 차례야. 아무도 모르는 얘기를 해 줄게. 동생도 몰라."),
(A, "Tu n'es pas obligée.", "꼭 안 해도 돼."),
(L, "Je sais. Mais je veux.", "알아. 하지만 하고 싶어."),
(None, "Un nouvel éclair. Léa ferme les yeux jusqu'à ce que le tonnerre s'éloigne, puis commence à parler d'une voix basse.", "다시 번개가 친다. 레아가 천둥이 멀어질 때까지 눈을 감았다가 낮은 목소리로 이야기를 시작한다."),
(L, "Quand j'avais dix-sept ans, j'ai eu un accident de voiture. Mon père conduisait. Il pleuvait, comme aujourd'hui. Un orage terrible.", "열일곱 살 때 자동차 사고가 났어. 아버지가 운전하셨고. 오늘처럼 비가 왔어. 끔찍한 뇌우였지."),
(A, "Tu as été blessée ?", "다쳤어?"),
(L, "Gravement. Une jambe cassée, deux côtes fêlées, une commotion. Mais le plus grave, c'est que dans l'autre voiture, il y avait une jeune femme. Elle est morte sur le coup.", "심하게. 다리가 부러지고 갈비뼈 두 대에 금이 가고 뇌진탕. 하지만 가장 심각한 건 다른 차에 젊은 여자가 타고 있었다는 거야. 그 자리에서 숨졌어."),
(A, "(très doucement) Léa...", "(아주 부드럽게) 레아..."),
(L, "Mon père n'était pas en tort : l'autre voiture avait dérapé. La justice l'a reconnu. Mais lui, il ne s'est jamais pardonné. Il a arrêté de rire pendant des années.", "아버지 잘못이 아니었어. 다른 차가 미끄러졌거든. 법원도 그렇게 인정했고. 하지만 아버지는 스스로를 용서하지 못했어. 몇 년 동안 웃지 않으셨지."),
(A, "Et toi ?", "그리고 너는?"),
(L, "Moi, j'ai commencé à dessiner. Dans mon lit d'hôpital. Des petits dessins de tout ce que je voyais par la fenêtre. Un arbre. Un oiseau. Un morceau de ciel.", "나는 그림을 그리기 시작했어. 병원 침대에서. 창밖으로 보이는 모든 걸 작게 그렸어. 나무. 새. 하늘 한 조각."),
(A, "C'est comme ça que tu es devenue graphiste.", "그렇게 해서 디자이너가 된 거구나."),
(L, "Oui. Les dessins m'ont sauvée. C'est pour ça que quand Théo m'a dit que mon métier n'était pas sérieux, ça m'a fait si mal.", "응. 그림이 날 구했어. 그래서 테오가 내 직업은 진지하지 않다고 했을 때 그렇게 아팠던 거야."),
(A, "Je comprends maintenant.", "이제 이해돼."),
(L, "Il ne savait pas. Je ne lui avais jamais dit. Je ne l'ai dit à personne, depuis quinze ans.", "그는 몰랐어. 말한 적이 없으니까. 십오 년 동안 아무에게도 말하지 않았어."),
(A, "Pourquoi tu me le dis, à moi ?", "왜 나한테는 말해 주는 거야?"),
(L, "Pour la même raison que toi. Parce que ce soir, j'ai senti que je pouvais.", "너랑 같은 이유야. 오늘 밤 해도 되겠다고 느꼈어."),
(None, "Dehors, la pluie redouble. Le vent siffle entre les pierres. Dans la cabane, la lampe à pétrole jette une lumière tremblante sur leurs visages.", "밖에서는 비가 더 거세진다. 바람이 돌 사이로 휘파람 소리를 낸다. 오두막 안에서는 석유 등이 그들의 얼굴에 떨리는 빛을 던진다."),
(A, "Et c'est pour ça que tu as peur de l'orage.", "그래서 뇌우를 무서워하는 거구나."),
(L, "Oui. Et c'est aussi pour ça que je ne sais pas comment répondre à Bordeaux.", "응. 그리고 그래서 보르도에 어떻게 대답해야 할지 모르는 거야."),
(A, "Je ne comprends pas le lien.", "연결이 이해가 안 돼."),
(L, "Après l'accident, j'ai promis à ma mère que je resterais près d'eux. Pendant des années. Je suis partie à Lyon pour mes études, puis à Paris, mais j'ai toujours gardé cette promesse : être joignable, être disponible, être là si quelque chose arrivait.", "사고 후에 어머니께 부모님 곁에 있겠다고 약속했어. 몇 년 동안. 리옹으로 공부하러 가고 그다음엔 파리로 왔지만 그 약속은 늘 지켜 왔어. 연락이 닿고, 시간을 낼 수 있고, 무슨 일이 생기면 곁에 있는 것."),
(A, "Et Bordeaux, c'est à six heures de Lyon en voiture.", "그런데 보르도는 리옹에서 차로 여섯 시간이야."),
(L, "Cinq heures et demie, en train. Mais c'est une autre région. Une autre vie.", "기차로 다섯 시간 반. 하지만 다른 지방이야. 다른 삶이지."),
(A, "Léa. Tu n'as pas besoin d'être là pour qu'ils t'aiment.", "레아. 네가 곁에 없어도 부모님은 널 사랑해."),
(L, "Je le sais, avec ma tête. Mais mon cœur n'est pas toujours d'accord.", "머리로는 알아. 하지만 마음은 늘 동의하지 않아."),
(A, "Moi aussi, j'ai une promesse. Rester près de mon père, ne pas quitter la Loire, ne pas partir comme Claire, ne pas disparaître comme ma mère.", "나도 약속이 있어. 아버지 곁에 남는 것, 루아르를 떠나지 않는 것, 클레르처럼 떠나지 않는 것, 어머니처럼 사라지지 않는 것."),
(L, "Tu as raison. On a le même problème.", "맞아. 우린 같은 문제를 갖고 있어."),
(A, "On a fait la même promesse, chacun de notre côté, à deux endroits opposés de la France.", "각자 프랑스의 서로 다른 두 곳에서 같은 약속을 했네."),
(L, "Et on se retrouve dans une cabane, en pleine tempête, à Verzenay, au milieu de la Champagne.", "그런데 우린 샹파뉴 한복판 베르즈네에서 폭풍우 속 오두막에서 만났어."),
(A, "Il y a un signe, non ?", "신호가 있는 것 같지 않아?"),
(L, "(sourit) Je ne crois pas aux signes.", "(미소 지으며) 난 신호를 믿지 않아."),
(A, "Moi non plus. Mais ce soir, j'ai envie d'y croire.", "나도 안 믿어. 하지만 오늘 밤엔 믿고 싶어."),
(None, "La pluie diminue peu à peu. Le tonnerre devient un grondement lointain. Léa appuie sa tête contre l'épaule d'Antoine.", "비가 점점 잦아든다. 천둥이 멀리서 으르렁대는 소리로 바뀐다. 레아가 앙투안의 어깨에 머리를 기댄다."),
(L, "Antoine ?", "앙투안?"),
(A, "Oui ?", "응?"),
(L, "Je n'ai pas encore décidé. Mais quoi que je décide, je veux que tu saches une chose.", "아직 결정하지 못했어. 하지만 뭘 결정하든 네가 알았으면 하는 게 하나 있어."),
(A, "Dis-moi.", "말해 줘."),
(L, "Tu es la première personne, depuis quinze ans, à qui j'ai pu dire tout ça.", "십오 년 만에 이 모든 걸 말할 수 있었던 첫 사람이 너야."),
(A, "(ému) Et toi, la première à qui j'ai pu parler de ma mère.", "(감동하여) 그리고 너는 내가 어머니 이야기를 할 수 있었던 첫 사람이야."),
(L, "Alors on est quittes.", "그럼 비긴 거네."),
(A, "On est même mieux que ça.", "그보다 더 나은 사이지."),
(None, "La pluie s'arrête. Un rayon de soleil traverse la porte entrouverte de la cabane et dessine une ligne dorée sur le sol de pierre. Au loin, un arc-en-ciel apparaît au-dessus des vignes.", "비가 그친다. 햇살 한 줄기가 살짝 열린 오두막 문으로 들어와 돌바닥에 금빛 선을 그린다. 멀리 포도밭 위로 무지개가 나타난다."),
(L, "Regarde. Un arc-en-ciel.", "봐. 무지개야."),
(A, "Il vient toujours après la tempête.", "폭풍우 뒤에는 늘 오지."),
(L, "Tu as vraiment tout compris à la vie, toi.", "넌 정말 삶을 다 이해했구나."),
(A, "Pas du tout. Mais je crois que j'ai compris quelque chose ce soir.", "전혀. 하지만 오늘 밤 뭔가 이해한 것 같아."),
(L, "Quoi ?", "뭘?"),
(A, "Que les promesses qu'on fait aux gens qu'on aime ne sont pas faites pour nous enfermer. Elles sont faites pour qu'on se souvienne d'eux.", "사랑하는 사람들에게 한 약속은 우리를 가두려는 게 아니라는 것. 그들을 기억하게 하려는 거야."),
(L, "(un temps) C'est la plus belle phrase que j'aie entendue de ma vie.", "(잠시 후) 내 평생 들은 가장 아름다운 말이야."),
(A, "Elle n'est pas de moi. Je crois qu'elle est de ma mère.", "내 말이 아니야. 어머니 말씀일 거야."),
(L, "Ta mère avait raison. Elle devait être une femme remarquable.", "어머니 말씀이 맞아. 정말 대단한 분이셨을 거야."),
(A, "Elle l'était. Tu lui aurais plu.", "그러셨어. 넌 어머니 마음에 들었을 거야."),
(L, "Tu crois ?", "그렇게 생각해?"),
(A, "J'en suis certain. Elle aimait les gens qui dessinent le monde.", "확신해. 세상을 그리는 사람들을 좋아하셨거든."),
(L, "Et moi, j'aurais aimé la rencontrer.", "나도 어머니를 만나 보고 싶었어."),
(A, "Peut-être que tu la rencontreras. À travers moi, à travers mon père, à travers la Loire.", "어쩌면 만나게 될 거야. 나를 통해, 아버지를 통해, 루아르를 통해."),
(L, "(sourit) Alors j'irai à la Loire, un jour.", "(미소 지으며) 그럼 언젠가 루아르에 갈게."),
(None, "Un vigneron en ciré jaune apparaît dans l'embrasure, une pelle sur l'épaule. Il les regarde, surpris.", "노란 비옷을 입은 포도 농부가 삽을 어깨에 메고 문가에 나타난다. 놀란 얼굴로 그들을 바라본다."),
(V, "Ah, des visiteurs ! Je croyais que la cabane était vide. Vous n'avez pas eu trop peur de l'orage ?", "아, 방문객이네요! 오두막이 비어 있는 줄 알았어요. 뇌우에 너무 놀라진 않으셨어요?"),
(L, "Un peu. Mais nous avons survécu.", "조금요. 하지만 살아남았어요."),
(V, "C'est la cabane de mon grand-père. Elle a résisté à toutes les tempêtes depuis 1920. Vous êtes en sécurité ici.", "제 할아버지의 오두막이에요. 1920년부터 모든 폭풍을 견뎠죠. 여기 계시면 안전해요."),
(A, "Elle a un beau calendrier.", "달력이 멋지네요."),
(V, "Le calendrier de 1987 ? C'est l'année de la mort de mon grand-père. Mon père ne l'a jamais changé. Il dit que le temps s'est arrêté ce jour-là.", "1987년 달력이요? 할아버지가 돌아가신 해예요. 아버지가 한 번도 바꾸지 않으셨죠. 그날 시간이 멈췄다고 하세요."),
(L, "(à Antoine, à voix basse) Quelqu'un a voulu arrêter le temps.", "(앙투안에게 작은 소리로) 누군가 시간을 멈추고 싶었던 거야."),
(A, "(à voix basse) Oui. Et on le comprend.", "(작은 소리로) 응. 이해돼."),
(V, "Venez. Je vous offre un verre de notre cuvée. Il faut fêter les survivants de l'orage.", "오세요. 저희 퀴베 한 잔 대접할게요. 뇌우의 생존자들은 축하해야죠."),
(None, "Ils sortent. Le paysage est transfiguré : la lumière dorée, l'herbe mouillée, le parfum de la terre après la pluie. Au loin, l'arc-en-ciel se déploie au-dessus de la vallée de la Marne.", "세 사람이 밖으로 나선다. 풍경이 변모했다. 금빛 햇살, 젖은 풀, 비 온 뒤 흙냄새. 멀리 마른 계곡 위로 무지개가 펼쳐진다."),
]
VOCAB = [
("A2","un orage / le tonnerre / un éclair","뇌우 / 천둥 / 번개","« Un premier coup de tonnerre éclate. »"),
("A2","des nuages / pleuvoir à verse","구름 / 억수같이 쏟아지다","« la pluie se met à tomber à verse »"),
("A2","une cabane / un abri","오두막 / 피신처","« trouver un abri »"),
("A2","trempé jusqu'aux os","뼛속까지 젖은","관용 표현. 비·눈에 흠뻑 젖었을 때"),
("A2","avoir peur de l'orage","뇌우를 무서워하다","« J'ai toujours eu peur de l'orage. »"),
("B1","sursauter / frémir","깜짝 놀라다 / 떨다","« Léa sursaute. » « Les feuilles frémissent. »"),
("B1","une bêtise / se disputer","사고(장난)·실수 / 다투다","« J'avais fait une bêtise. »"),
("B1","gronder quelqu'un","야단치다","« Il ne m'a pas grondé. »"),
("B1","un accident de voiture / être blessé","자동차 사고 / 다치다","« gravement blessée »"),
("B1","une jambe cassée / une côte fêlée","부러진 다리 / 금이 간 갈비뼈","의학·사고 어휘"),
("B1","dériver / déraper","미끄러지다","« L'autre voiture avait dérapé. »"),
("B1","un arc-en-ciel","무지개","« Il vient toujours après la tempête. »"),
("B2","assourdissant(e)","귀가 먹먹한","« un coup de tonnerre assourdissant »"),
("B2","être en tort / avoir raison","잘못이 있다 / 옳다","« Mon père n'était pas en tort. »"),
("B2","mourir sur le coup","즉사하다","« Elle est morte sur le coup. »"),
("B2","une commotion","뇌진탕","« une jambe cassée, deux côtes fêlées, une commotion »"),
("B2","ne s'est jamais pardonné","스스로를 용서하지 못했다","재귀대명사 복합과거 부정"),
("B2","quitte à / on est quittes","~하더라도 / 비긴 사이다","être quitte = 빚이 없다, 비기다"),
("B2","un ciré / une embrasure","비옷 / 문틀(개구부)","농부의 복장과 문의 묘사"),
("C1","marteler","망치질하듯 두드리다","« la pluie martèle le toit » 은유적 동사"),
("C1","arrêter le temps","시간을 멈추다","오두막 달력의 상징. 애도의 은유"),
("C1","Elles sont faites pour qu'on se souvienne d'eux.","그것들은 그들을 기억하게 하려고 만들어진 것이다.","pour que + 접속법 (se souvienne)"),
("C1","transfiguré(e)","변모한","경치가 빛으로 완전히 달라진 모습"),
("C1","quoi que je décide","내가 무엇을 결정하든","quoi que + 접속법: 무엇을 ~하든"),
]
GRAM = [
("A2","대과거 plus-que-parfait: j'avais fait / je m'étais disputé",
 "« J'avais fait une bêtise. » « Je m'étais disputé avec mon père. » « Les nuages étaient déjà arrivés. » avoir/être의 반과거 + 과거분사. 이야기 속 과거 시점보다 앞선 일을 나타낸다."),
("A2","복합과거와 반과거의 서사 구성",
 "« Il pleuvait. Mon père conduisait. » (배경: 반과거) « Un accident est arrivé. » (사건: 복합과거) 묘사는 반과거, 사건은 복합과거. 사건의 연쇄는 복합과거를 이어서 쓴다."),
("B1","조건법 과거: j'aurais dû",
 "« J'aurais dû t'en parler. » devoir의 조건법 과거 = ~했어야 했는데 (하지 않았다). « J'aurais pu te dire non. » = 거절할 수도 있었다. 후회·비난의 표현."),
("B1","il faut que / il n'y a pas de honte à",
 "« Il faut vite trouver un abri. » (il faut + 동사원형) / « Il n'y a pas de honte à avoir peur. » à + 동사원형. 일반적 사실의 표현."),
("B2","접속법의 양보: quoi que + 접속법",
 "« Quoi que je décide, je veux que tu saches. » quoi que + 접속법 = 무엇을 ~하든. « Où que tu ailles. » (어디를 가든), « Qui que ce soit. » (누구든)."),
("B2","pour que + 접속법: 목적",
 "« Elles sont faites pour qu'on se souvienne d'eux. » pour que + 접속법 = ~하도록. « Je te le dis pour que tu comprennes. » 주어가 같으면 pour + 동사원형."),
("B2","간접의문과 접속법: je ne comprends pas le lien",
 "« Je ne comprends pas le lien. » « Il ne voulait pas que je lui rende visite. » vouloir (부정) + que + 접속법 (rende). 부정문과 의지 동사에서 접속법이 요구된다."),
("C1","관용: c'est la plus belle phrase que j'aie entendue",
 "최상급 + que + 접속법 과거. « C'est la plus belle phrase que j'aie entendue de ma vie. » 문장 끝에 de ma vie를 붙여 강조. 6화·16화 복습 포인트."),
]
CULTURE = [
("포도밭의 cabane와 폭풍우",
 "샹파뉴와 부르고뉴 포도밭에는 '카바 드 비뉴(cabane de vigne)'라 부르는 작은 돌 오두막이 많다. 농부가 비를 피하거나 도구를 두는 용도다. 우박·뇌우는 포도 농가에 치명적이어서 농부들은 하늘의 변화를 읽는 데 익숙하다."),
("모두의 상처: 자동차 사고와 애도",
 "이 에피소드는 두 인물의 트라우마를 처음 공개해 관계의 전환점이 된다. 프랑스어에서 'se confier'(속마음을 털어놓다)는 친밀감을 상징하는 행위다."),
("무지개와 'Après la pluie, le beau temps'",
 "프랑스 속담 'Après la pluie, le beau temps'(비 온 뒤에 맑은 날)은 시련 뒤에 좋은 일이 온다는 뜻이다. 에피소드 마지막 무지개 장면이 이 속담의 시각적 표현이다."),
]
META = dict(part=2, ep=19, part_label="제2부 여름의 포도 · Les raisins de l'été", title_fr="L'orage", title_ko="폭풍우",
 place="랭스 산지(Montagne de Reims) 베르즈네 마을 위 포도밭 오두막 · 8월 3일 일요일 오후",
 chars="Léa · Antoine · Le vigneron (포도 농부)",
 wine="(마지막 장면) 농부의 퀴베 한 잔",
 focus="대과거, 복합과거·반과거의 서사, 조건법 과거(j'aurais dû), quoi que/pour que + 접속법",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제20화 « Jalousie » : 파리로 돌아온 뒤, 레아의 전 연인 테오가 불쑥 가게 앞에 나타난다. 앙투안은 처음으로 ‘질투’라는 감정과 마주한다.")
