# -*- coding: utf-8 -*-
G, L, A, H, N, P, K = "Gaston", "Léa", "Antoine", "Hugo", "Nicole", "Mme Pichon", "Karim"
D = [
(None, "Lundi 18 août, 19 h 55. Léa remonte la rue des Abbesses d'un pas lent, un peu mélancolique. Elle a trente-deux ans aujourd'hui. Devant La Cave des Abbesses, le rideau de fer est à moitié baissé, et les lumières semblent éteintes.", "8월 18일 월요일 저녁 7시 55분. 레아가 약간 쓸쓸한 걸음으로 아베스 거리를 올라간다. 오늘 서른두 살이 되었다. 라 카브 데 자베스 앞 철제 셔터는 반쯤 내려와 있고 불은 꺼진 듯하다."),
(L, "(à elle-même) Fermé. Même Gaston a fermé le jour de mon anniversaire.", "(혼잣말) 닫았네. 가스통조차 내 생일날 문을 닫았어."),
(None, "Elle se retourne pour partir, quand la porte s'entrouvre. La voix de Gaston, étouffée, murmure.", "그녀가 돌아서 가려는 순간 문이 조금 열린다. 가스통의 억눌린 목소리가 속삭인다."),
(G, "Léa ! Psst ! Entre vite, j'ai un problème avec le rideau.", "레아! 쉿! 얼른 들어와, 셔터에 문제가 있어."),
(L, "Gaston ? Pourquoi tu chuchotes ?", "가스통? 왜 속삭여?"),
(G, "Parce que... il y a un rat dans la cave. Je ne veux pas l'effrayer.", "저기... 지하실에 쥐가 있어서. 놀라게 하고 싶지 않아."),
(L, "Un rat ? Tu as un rat dans ta cave de vins ?", "쥐? 와인 저장고에 쥐가 있어?"),
(G, "Un rat très poli. Entre.", "아주 예의 바른 쥐야. 들어와."),
(None, "Elle entre. L'obscurité est totale. Soudain, toutes les lumières s'allument en même temps, et une dizaine de voix hurlent « Surprise ! ».", "그녀가 들어선다. 깜깜하다. 갑자기 모든 불이 동시에 켜지고 열 명쯤이 '서프라이즈!'라고 외친다."),
(L, "(sursaute, la main sur le cœur) Oh ! Mon Dieu !", "(놀라 가슴에 손을 얹으며) 오! 세상에!"),
(None, "Dans la boutique, des guirlandes, des ballons dorés et une grande banderole peinte à la main : « BON ANNIVERSAIRE LÉA ». Autour d'elle : Gaston, Madame Pichon, Karim, Hugo... et une femme d'une soixantaine d'années, aux cheveux courts et aux yeux très clairs.", "가게 안에는 갈런드와 금빛 풍선, 손으로 그린 큰 현수막 '생일 축하해 레아'가 있다. 그녀 주위에는 가스통, 피숑 부인, 카림, 위고... 그리고 짧은 머리에 아주 맑은 눈을 한 예순 안팎의 여인이 있다."),
(L, "Maman ?! Maman, qu'est-ce que tu fais ici ?", "엄마?! 엄마, 여기서 뭐 하세요?"),
(N, "Je viens souhaiter un bon anniversaire à ma fille. Ce n'est pas autorisé ?", "딸에게 생일 축하하러 왔지. 허락 안 되니?"),
(L, "Mais... tu as pris le train ? Seule ?", "하지만... 기차를 타고 왔어요? 혼자서?"),
(N, "Avec Hugo. Il m'a dit que c'était urgent. J'ai cru qu'il y avait une catastrophe.", "위고랑. 급하다고 하더라. 난 재난이라도 난 줄 알았어."),
(H, "(sourit, une guitare dans le dos) C'était urgent. Une urgence sentimentale.", "(등에 기타를 멘 채 웃으며) 급했지. 감정적으로 급한 일이었어."),
(L, "(se jette dans les bras de sa mère) Maman ! Je suis tellement contente !", "(어머니 품에 안기며) 엄마! 너무 기뻐요!"),
(N, "Bon anniversaire, ma chérie. Trente-deux ans. Tu as toujours le même sourire que quand tu en avais six.", "생일 축하한다, 얘야. 서른둘이라니. 여섯 살 때와 똑같은 미소야."),
(L, "Et toi, tu n'as pas changé du tout.", "엄마도 하나도 안 변했어요."),
(N, "Menteuse. J'ai des rides, des cheveux gris, et un mal de dos terrible. Mais merci.", "거짓말쟁이. 주름도 있고 흰머리도 있고 허리가 끔찍하게 아프단다. 그래도 고맙구나."),
(P, "Léa, ma petite ! Bon anniversaire ! J'ai pleuré trois fois dans la cuisine en préparant ce gâteau.", "레아, 우리 아가씨! 생일 축하해요! 이 케이크 만들다가 부엌에서 세 번이나 울었어요."),
(L, "Madame Pichon ! Vous avez fait un gâteau ?", "피숑 부인! 케이크를 만드셨어요?"),
(P, "Un moelleux au chocolat. Gaston a tout goûté. Il dit que c'est le meilleur de sa vie.", "초콜릿 무알뢰예요. 가스통이 다 맛봤어요. 인생 최고래요."),
(G, "J'ai dit que c'était le meilleur depuis 1974. C'est différent.", "1974년 이후 최고라고 했어. 그건 달라."),
(K, "Bon anniversaire, Léa ! Je suis venu avec une bouteille de champagne et zéro arrière-pensée.", "생일 축하해요, 레아! 샴페인 한 병이랑 아무 속셈 없이 왔어요."),
(L, "Merci, Karim. Tu es adorable.", "고마워요, 카림. 다정하네요."),
(None, "Elle cherche des yeux une silhouette absente. Elle la trouve enfin : Antoine, debout près du comptoir, légèrement en retrait, un petit paquet dans les mains. Il n'ose pas s'approcher.", "그녀가 눈으로 보이지 않는 한 사람을 찾는다. 마침내 발견한다. 앙투안이 카운터 옆에 약간 물러서서 작은 꾸러미를 손에 든 채 서 있다. 다가오지 못한다."),
(L, "(traverse la pièce) Antoine.", "(방을 가로질러 가며) 앙투안."),
(A, "Joyeux anniversaire, Léa.", "생일 축하해, 레아."),
(L, "C'était ça, ton « quelque chose d'important à faire » ?", "'중요한 일이 있다'던 게 이거였어?"),
(A, "J'espère que ça valait le mystère.", "그만한 가치가 있기를 바라."),
(L, "Tu aurais pu me le dire ! Si j'avais su, je ne me serais pas tourmentée pendant vingt-quatre heures.", "말해 줄 수 있었잖아! 알았다면 스물네 시간 동안 괴로워하지 않았을 텐데."),
(A, "Si je te l'avais dit, ce n'aurait pas été une surprise.", "말해 줬다면 서프라이즈가 아니었을 거야."),
(L, "(sourit, les yeux brillants) Tu es impossible.", "(눈을 반짝이며 미소 지으며) 넌 정말 못 말려."),
(A, "J'ai eu du mal à tout organiser. Ta mère, ton frère, Gaston... Si j'avais dû le faire seul, j'aurais échoué.", "모든 걸 준비하느라 힘들었어. 어머니, 동생, 가스통... 혼자 해야 했다면 실패했을 거야."),
(L, "Alors tu as contacté ma mère ? Comment ?", "그럼 우리 어머니께 연락했어? 어떻게?"),
(A, "Par Hugo. Il m'a donné son numéro. Elle m'a répondu : « Je prends le premier train. »", "위고를 통해서. 번호를 알려 줬어. 어머니가 '첫 기차를 타겠어요'라고 하셨어."),
(N, "(s'approche, sourire en coin) Alors c'est vous, Antoine.", "(입가에 미소를 띠고 다가오며) 그럼 당신이 앙투안이군요."),
(A, "(se redresse, légèrement nerveux) Madame Fontaine. Je suis ravi de vous rencontrer.", "(몸을 곧게 펴며 약간 긴장해서) 퐁텐 부인. 만나 뵙게 되어 영광입니다."),
(N, "Appelez-moi Nicole. Mon mari dit « Madame Fontaine » quand il est en colère, et je ne veux pas qu'on me prenne pour lui.", "니콜이라고 불러요. 남편은 화났을 때 '퐁텐 부인'이라고 하는데 그 사람이랑 같게 보이고 싶지 않아서요."),
(A, "Nicole, alors. Ravi.", "그럼 니콜 씨. 반갑습니다."),
(N, "Léa m'a beaucoup parlé de vous. Quarante minutes au téléphone, la dernière fois.", "레아가 당신 얘기를 많이 했어요. 지난번엔 전화로 사십 분이나."),
(L, "Maman !", "엄마!"),
(N, "Quoi ? Je dis la vérité. Antoine, vous êtes professeur d'histoire, c'est bien ça ?", "뭐? 사실을 말하는 거야. 앙투안 씨, 역사 선생님 맞죠?"),
(A, "Oui. Dans un lycée du neuvième.", "네. 9구의 고등학교에서요."),
(N, "Quelle belle profession. Mon mari dit que les professeurs sont des gens qui n'ont jamais travaillé de leurs mains.", "멋진 직업이에요. 남편은 교사들이 손으로 일해 본 적이 없는 사람들이라고 하더군요."),
(A, "Il n'a pas tort. Mais j'ai fait les vendanges douze ans de suite. J'ai les mains plus abîmées que ce que vous croyez.", "틀린 말씀은 아니에요. 하지만 12년 연속 수확 일을 했어요. 생각하시는 것보다 손이 많이 거칠어요."),
(N, "(lui prend la main, la retourne, la regarde) Hmm. C'est vrai. Vous avez des cals, ici.", "(그의 손을 잡아 뒤집어 살펴보며) 흠. 맞네. 여기 굳은살이 있어요."),
(L, "Maman, tu n'es pas en train de lui lire les lignes de la main ?", "엄마, 지금 손금 보시는 거 아니죠?"),
(N, "Je lis ses cals. C'est plus fiable. Antoine, vous venez d'un domaine de vin ?", "굳은살을 읽는 거야. 그게 더 믿을 만해. 앙투안 씨, 와인 농가 출신이라고요?"),
(A, "Près de Saumur. Mon père cultive des vignes depuis quarante ans.", "소뮈르 근처예요. 아버지가 40년째 포도를 재배하세요."),
(N, "Alors vous connaissez la valeur d'une promesse tenue.", "그럼 지킨 약속의 가치를 아시겠네요."),
(A, "Je crois, oui.", "그렇다고 생각합니다."),
(N, "C'est tout ce que je voulais savoir.", "제가 알고 싶었던 건 그게 전부예요."),
(None, "Elle lui lâche la main, lui sourit, puis s'éloigne vers Madame Pichon. Léa regarde Antoine, puis sa mère, puis de nouveau Antoine.", "그녀가 그의 손을 놓고 미소 짓고는 피숑 부인 쪽으로 걸어간다. 레아가 앙투안을 보고 어머니를 보고 다시 앙투안을 본다."),
(L, "Qu'est-ce qu'elle t'a fait ?", "어머니가 너한테 무슨 일을 하신 거야?"),
(A, "Elle m'a fait passer un examen. Et je crois que je l'ai réussi.", "시험을 보게 하셨어. 그리고 통과한 것 같아."),
(L, "(rit) Elle fait toujours ça. Elle a fait pareil avec Théo.", "(웃으며) 엄마는 늘 그러셔. 테오한테도 똑같이 했어."),
(A, "Et Théo, il a réussi ?", "그럼 테오는 통과했어?"),
(L, "Elle lui a demandé son métier. Quand il a dit « CEO », elle a dit : « Ah. » Et c'est tout.", "직업을 물었어. '대표'라고 하자 '아.'라고만 하셨지. 그게 전부였어."),
(A, "Je comprends mieux la dynamique.", "역학 관계가 이해돼."),
(G, "Mesdames et messieurs, l'heure des cadeaux !", "신사 숙녀 여러분, 선물 시간입니다!"),
(None, "Tout le monde se rassemble autour du comptoir. Gaston sort un grand paquet de papier kraft de sous la caisse.", "모두가 카운터 주위에 모인다. 가스통이 계산대 아래에서 크라프트지로 싼 큰 꾸러미를 꺼낸다."),
(G, "Léa. Pour ton anniversaire, j'ai mis trente-cinq ans de métier dans cette bouteille.", "레아. 네 생일을 위해 35년 경력을 이 병에 담았어."),
(L, "(ouvre le paquet, retient son souffle) Un Banyuls ?", "(꾸러미를 열고 숨을 멈추며) 바뉠스?"),
(G, "Un Banyuls de 1993. Ton année de naissance. J'ai cherché pendant six mois dans toute la France. Je l'ai finalement trouvé chez un vieux vigneron de Collioure qui ne voulait pas le vendre.", "1993년산 바뉠스야. 네가 태어난 해지. 6개월 동안 프랑스 전역을 뒤졌어. 결국 팔기 싫어하던 콜리우르의 늙은 농부에게서 찾았지."),
(L, "Gaston... ce n'est pas possible.", "가스통... 말도 안 돼요."),
(G, "Les années 1993, ce n'est pas la plus grande pour le Bordeaux ou la Bourgogne. Mais pour le Banyuls, c'est une année magnifique. Comme toi : discrète, mais exceptionnelle.", "1993년은 보르도나 부르고뉴에는 최고의 해가 아니야. 하지만 바뉠스에는 아름다운 해였지. 너처럼. 조용하지만 특별한."),
(L, "(les larmes aux yeux) Merci. Merci, Gaston.", "(눈물이 고여) 고마워요. 고마워요, 가스통."),
(P, "À mon tour ! Voici un petit quelque chose pour toi, ma petite.", "내 차례예요! 아가씨를 위한 작은 선물이에요."),
(L, "(ouvre la boîte) Un chapeau ?", "(상자를 열며) 모자요?"),
(P, "Mon chapeau à fleurs. Celui de 1990. Celui du quatorze juillet.", "내 꽃무늬 모자예요. 1990년 거. 7월 14일의 그 모자."),
(L, "Madame Pichon, je ne peux pas accepter. C'est votre souvenir !", "피숑 부인, 받을 수 없어요. 부인의 추억인걸요!"),
(P, "Justement. Il est temps qu'il serve à quelqu'un qui en fera de nouveaux.", "그러니까요. 새로운 추억을 만들 사람에게 쓰일 때가 됐어요."),
(H, "Mon tour, mon tour ! J'ai écrit une chanson pour toi.", "내 차례, 내 차례! 누나를 위해 노래를 하나 썼어."),
(L, "Hugo, ne me dis pas que tu as inventé un quatrième accord.", "위고, 네 번째 코드를 만들어 냈다는 말은 하지 마."),
(H, "J'ai ajouté un si bémol. Prépare-toi.", "시 플랫을 추가했어. 각오해."),
(None, "Hugo prend sa guitare et joue une mélodie simple, douce, avec un nouvel accord qui sonne un peu faux, mais avec beaucoup de tendresse. Sa mère essuie discrètement une larme.", "위고가 기타를 들고 소박하고 부드러운 멜로디를 연주한다. 새 코드가 약간 어긋나게 들리지만 애정이 가득하다. 어머니가 조용히 눈물을 닦는다."),
(L, "(émue) Hugo, c'est magnifique.", "(감동하여) 위고, 정말 아름다워."),
(H, "Même le si bémol ?", "시 플랫도?"),
(L, "Surtout le si bémol.", "특히 시 플랫."),
(N, "(à voix basse, à Antoine) Les deux enfants ont toujours été comme ça. Elle fait semblant d'être forte. Lui fait semblant d'être idiot.", "(앙투안에게 작은 소리로) 두 아이는 늘 그랬어요. 딸은 강한 척하고 아들은 바보인 척하죠."),
(A, "Et vous, vous faites semblant de ne pas pleurer.", "그리고 어머니는 울지 않는 척하시고요."),
(N, "Vous êtes très perspicace, Antoine.", "아주 눈치가 빠르시네요, 앙투안 씨."),
(N, "Léa, viens un instant. Rien que nous deux.", "레아, 잠깐 이리 와. 우리 둘만."),
(L, "Qu'est-ce qu'il y a, maman ?", "무슨 일이에요, 엄마?"),
(N, "Hugo m'a parlé de Bordeaux.", "위고가 보르도 얘기를 했어."),
(L, "Je sais. Il ne sait pas se taire.", "알아요. 입을 다물 줄을 몰라요."),
(N, "Écoute-moi. Tu m'as fait une promesse, il y a quinze ans, celle de ne jamais t'éloigner. Je te délie de cette promesse.", "들어 봐. 십오 년 전에 절대 멀리 가지 않겠다고 나한테 약속했지. 그 약속에서 널 풀어 주마."),
(L, "(émue) Maman...", "(감동하여) 엄마..."),
(N, "Va où ton cœur te mène. Ton père et moi, nous irons mieux si tu es heureuse.", "마음이 이끄는 곳으로 가렴. 네 아빠와 나는 네가 행복하면 더 잘 지낼 수 있어."),
(L, "Merci, maman. Merci de me le dire.", "고마워요, 엄마. 말씀해 주셔서."),
(G, "Et maintenant, le dernier cadeau. Antoine ?", "그리고 이제 마지막 선물입니다. 앙투안?"),
(None, "Antoine s'avance, un grand tube de carton sous le bras. Il le tend à Léa. Elle l'ouvre : à l'intérieur, une grande feuille enroulée.", "앙투안이 커다란 종이 통을 팔에 끼고 앞으로 나선다. 레아에게 건넨다. 그녀가 열자 안에는 둘둘 만 큰 종이가 있다."),
(A, "Ce n'est pas aussi beau que tes dessins. Mais je l'ai fait de mes mains.", "네 그림만큼 아름답진 않아. 하지만 내 손으로 직접 했어."),
(None, "Elle déroule la feuille : une carte de Montmartre, dessinée à la main, avec des petits dessins maladroits et des annotations. Une croix pour la boutique de Gaston. Un parapluie au coin de la rue Durantin. Une fraise sur la place des Abbesses. Un petit canal.", "그녀가 종이를 펼친다. 손으로 그린 몽마르트르 지도다. 서툰 작은 그림과 주석이 곁들여져 있다. 가스통 가게에는 십자가 표시. 뒤랑탱 거리 모퉁이에는 우산. 아베스 광장에는 딸기. 작은 운하도."),
(L, "(à voix basse) Antoine...", "(작은 소리로) 앙투안..."),
(A, "C'est la carte de nos rencontres. Chaque lieu où il s'est passé quelque chose. J'ai passé trois semaines dessus.", "우리가 만난 곳들의 지도야. 무슨 일이 있었던 모든 장소를 담았어. 삼 주 동안 그렸지."),
(L, "Il y a même la cabane de Verzenay.", "베르즈네 오두막도 있네."),
(A, "J'ai pensé qu'on ne pouvait pas l'oublier.", "그걸 잊을 수는 없다고 생각했어."),
(L, "(montre un petit espace vide au centre) Et ça, là, au milieu ? Il n'y a rien.", "(중앙의 작은 빈 공간을 가리키며) 그리고 이건, 가운데 이거? 아무것도 없네."),
(A, "C'est la place du prochain lieu. Je n'ai pas voulu le dessiner à ta place.", "다음 장소를 위한 자리야. 네 대신 그리고 싶지 않았어."),
(L, "(les larmes aux yeux, souriant) Tu es vraiment... Je n'ai pas de mots.", "(눈물이 고인 채 미소 지으며) 넌 정말... 할 말이 없어."),
(A, "Alors ne dis rien.", "그럼 말하지 마."),
(None, "Léa pose la carte, s'approche d'Antoine et l'embrasse devant tout le monde. Un « ohhh » collectif s'élève dans la boutique.", "레아가 지도를 내려놓고 앙투안에게 다가가 모두가 보는 앞에서 키스한다. 가게 안에 '오오' 하는 합창이 터진다."),
(P, "Enfin !", "드디어!"),
(K, "J'ai perdu mon pari avec madame Pichon : j'avais dit dans deux mois.", "피숑 부인과의 내기에서 졌네요. 두 달 뒤라고 했는데."),
(P, "Karim, je te dois une bouteille de Sauternes. Non, c'est toi qui me la dois.", "카림, 소테른 한 병을 빚졌네. 아니, 오히려 자네가 내게 빚졌지."),
(H, "(à Antoine) Tu as réussi l'examen. Je retire mon projet de guitare sous ta fenêtre.", "(앙투안에게) 시험 통과했어요. 창문 아래서 기타 치는 계획은 철회할게요."),
(A, "Je suis soulagé.", "다행이네요."),
(None, "Gaston lève un verre de champagne. Tout le monde l'imite.", "가스통이 샴페인 잔을 든다. 모두가 따라 한다."),
(G, "À Léa ! Trente-deux ans, et toute la vie devant elle !", "레아를 위해! 서른두 살, 그리고 앞으로 펼쳐질 삶을 위해!"),
(None, "« À Léa ! » Les verres tintent. Dans un coin, le Banyuls de 1993 brille d'une couleur d'ambre rougeâtre, posé sur le comptoir à côté de la carte dessinée à la main.", "'레아를 위해!' 잔이 부딪친다. 한쪽 구석에서 1993년 바뉠스가 붉은 호박빛으로 반짝인다. 손으로 그린 지도 옆 카운터 위에 놓여 있다."),
]
VOCAB = [
("A2","un anniversaire / un gâteau / une bougie","생일 / 케이크 / 초","생일 파티 어휘"),
("A2","une surprise / Surprise !","서프라이즈","외침 « Surprise ! »"),
("A2","une guirlande / un ballon / une banderole","가렌드 / 풍선 / 현수막","파티 장식"),
("A2","un cadeau / un paquet","선물 / 꾸러미","« l'heure des cadeaux »"),
("A2","un rideau de fer","철제 셔터","상점 셔터 표현"),
("B1","chuchoter / murmurer","속삭이다 / 중얼거리다","« Pourquoi tu chuchotes ? »"),
("B1","tourmenter / se tourmenter","괴롭히다 / 괴로워하다","« je ne me serais pas tourmentée »"),
("B1","un mystère / un examen","수수께끼 / 시험","« passer un examen »"),
("B1","maladroit / un cal","서투른 / 굳은살","« des petits dessins maladroits », « des cals »"),
("B1","une carte dessinée à la main","손으로 그린 지도","앙투안의 선물"),
("B1","annoter / une annotation","주석을 달다 / 주석","« des annotations » 지도 위 작은 메모"),
("B2","arrière-pensée","속셈","« zéro arrière-pensée » = 다른 의도 없음"),
("B2","perspicace","통찰력 있는","« Vous êtes très perspicace. »"),
("B2","un vin doux naturel / Banyuls","주정강화 와인 / 바뉠스","루시용 지방의 와인"),
("B2","une promesse tenue","지켜진 약속","« la valeur d'une promesse tenue »"),
("B2","retirer / échouer","철회하다 / 실패하다","« Je retire mon projet. » « j'aurais échoué »"),
("B2","en retrait","물러서서","« légèrement en retrait »"),
("B2","un pari / parier","내기 / 내기하다","« J'ai perdu mon pari. »"),
("C1","le sourire en coin","입가의 미소(의미심장한)","« sourire en coin » = 슬그머니 짓는 미소"),
("C1","lire les lignes de la main","손금을 보다","« Tu n'es pas en train de lui lire les lignes de la main ? »"),
("C1","l'urgence sentimentale","감정적 급박함","위고의 재치 있는 표현"),
("C1","la place du prochain lieu","다음 장소를 위한 자리","지도의 빈 공간. 미래를 열어 두는 은유"),
("C1","tout le monde l'imite","모두가 따라 한다","imiter = 따라 하다"),
("C1","toute la vie devant soi","앞으로 인생이 창창하다","« toute la vie devant elle » 축하 덕담"),
]
GRAM = [
("A2","조건법 과거 (si + 대과거, 조건법 과거)",
 "« Si j'avais su, je ne me serais pas tourmentée. » « Si je te l'avais dit, ce n'aurait pas été une surprise. » « Si j'avais dû le faire seul, j'aurais échoué. » 과거에 일어나지 않은 일의 가정. avoir/être 조건법 + 과거분사."),
("A2","대명사 y와 en 복습: j'en suis ravi / j'y suis",
 "« Elle m'a répondu : « Je prends le premier train. » » « Je suis ravi de vous rencontrer. » « Il y a un rat dans la cave. » 비인칭 il y a와 y(장소)는 구분."),
("B1","현재진행: être en train de",
 "« Tu n'es pas en train de lui lire les lignes de la main ? » 지금 진행 중인 행동을 확인하거나 지적할 때. « Tu es en train de me taquiner ? »"),
("B1","복합과거와 대과거 호응",
 "« Elle m'a demandé son métier. » « J'avais dit dans deux mois. » « Il m'a donné son numéro. Elle m'a répondu… » 사건 순서를 정리할 때 대과거가 이전 사건."),
("B1","il est temps que + 접속법",
 "« Il est temps qu'il serve à quelqu'un. » « Il est temps que tu partes. » il est temps que + 접속법 = ~할 때가 됐다. « Il était temps. » = 때가 됐었다."),
("B2","c'est … qui / c'est … que (강조 분열문)",
 "« C'est moi qui te remercie. » « C'est toi qui me la dois. » « C'est ça que je voulais savoir. » 주어 강조는 qui, 목적어·부사 강조는 que."),
("B2","최상급 + que + 접속법 과거 (복습)",
 "« Le meilleur de sa vie. » « La plus belle description que j'aie jamais entendue. » 6화·15화·16화의 복습 포인트."),
("C1","si의 일반 용법과 시제 호응",
 "« Si j'avais dû le faire seul, j'aurais échoué. » (과거 가정) / « Si tu voulais, on pourrait… » (현재 가정) / « S'il vient, je partirai. » (현실 가능성). 3가지 si 구문을 비교."),
]
CULTURE = [
("Banyuls 와 vin doux naturel",
 "바뉠스(Banyuls)는 루시용 지방 콜리우르 인근에서 그르나슈로 만든 주정강화 와인으로 초콜릿 디저트와 최고의 궁합을 자랑한다. 오래 숙성되면 호박빛이 되며 건과일·커피·카카오 향이 난다. 출생연도 빈티지를 구하려면 이런 달콤한 와인이 선택지가 되는 경우가 많다."),
("프랑스의 생일 서프라이즈와 가족",
 "프랑스에서도 가까운 가족과 친구가 모여 열어 주는 서프라이즈 파티가 인기다. 'Surprise !'를 외치고 케이크와 샴페인을 나누는 것이 일반적이며, 어머니가 직접 딸의 연인을 시험(?)하는 장면은 영화적 클리셰다."),
("손으로 만든 선물",
 "프랑스에서는 비싼 선물보다 직접 그린 그림이나 손편지처럼 정성이 담긴 선물을 높이 평가한다. 앙투안이 직접 그린 'carte de nos rencontres'는 디자이너인 레아에게 가장 뜻깊은 선물이다."),
]
META = dict(part=2, ep=22, part_label="제2부 여름의 포도 · Les raisins de l'été", title_fr="Un cadeau d'anniversaire", title_ko="생일 선물",
 place="La Cave des Abbesses · 8월 18일 월요일 저녁 7시 55분 (레아의 32번째 생일)",
 chars="Léa · Antoine · Gaston · Mme Pichon · Karim · Hugo · Nicole (니콜, 레아의 어머니)",
 wine="Banyuls 1993 (레아의 출생연도 와인) · 샴페인",
 focus="조건법 과거(si + 대과거), il est temps que + 접속법, 감사·칭찬 표현, 강조 분열문",
 levelmix="A2 20% / B1 40% / B2 30% / C1 10% 목표",
 next="제23화 « Vacances séparées » : 생일이 지나고 맞이한 8월 말. 앙투안은 루아르로, 레아는 리옹으로. 거리를 둔 채 주고받는 메시지와 편지.")
