# -*- coding: utf-8 -*-
G, L, A, E, F = "Gaston", "Léa", "Antoine", "Un élève", "Une élève"
D = [
(None, "Jeudi 4 septembre, 18 h. Les derniers touristes de l'été ont quitté Montmartre. La Cave des Abbesses est silencieuse. Gaston a baissé le rideau de fer à moitié, retourné la pancarte « Fermé » et sorti trois verres. Il n'a rien dit depuis que Léa et Antoine sont entrés.", "9월 4일 목요일 오후 6시. 올여름 마지막 관광객들이 몽마르트르를 떠났다. 라 카브 데 자베스는 조용하다. 가스통이 철제 셔터를 반쯤 내리고 '휴업' 팻말을 뒤집고 잔 세 개를 꺼냈다. 레아와 앙투안이 들어온 뒤로 그는 아무 말도 하지 않았다."),
(L, "Gaston, tu m'inquiètes. Tu as fermé la boutique à dix-huit heures un jeudi, pour la première fois en trente-cinq ans.", "가스통, 걱정돼요. 35년 만에 처음으로 목요일 6시에 문을 닫았잖아요."),
(G, "Trente-cinq ans et cinq mois, pour être précis. Asseyez-vous, tous les deux. J'ai ouvert une bouteille, et je ne l'ai pas choisie au hasard.", "정확히 35년 5개월이야. 둘 다 앉아. 병을 하나 열었는데 아무렇게나 고른 게 아니야."),
(A, "(regarde l'étiquette) Un Morgon. Le même qu'au premier soir.", "(라벨을 보며) 모르공이네요. 첫날 저녁과 같은 거예요."),
(G, "Presque le même. C'est le millésime que j'avais mis de côté. Il y a un début à tout, et une fin à tout.", "거의 같지. 따로 챙겨 둔 빈티지야. 모든 일에는 시작이 있고 끝이 있지."),
(L, "Gaston, qu'est-ce que tu es en train de nous dire ?", "가스통, 지금 우리한테 무슨 말을 하려는 거예요?"),
(G, "Je suis en train d'essayer de vous le dire, mais les mots ne sortent pas. Pourtant, j'en ai passé, du temps, à vendre du vin avec des mots.", "말하려고 애쓰는 중인데 말이 안 나와. 말로 와인을 파느라 시간을 얼마나 보냈는데."),
(A, "Prends ton temps.", "천천히 해."),
(G, "Voilà. Il y a trois semaines, un homme est venu à la boutique. Un monsieur en costume, avec une mallette. Il représente un groupe qui possède déjà quarante magasins de vin en France.", "자. 삼 주 전에 한 남자가 가게에 왔어. 서류 가방을 든 정장 차림의 신사였지. 이미 프랑스에 와인 가게 마흔 개를 가진 그룹의 대리인이야."),
(L, "(se raidit) Un groupe ? Quel groupe ?", "(굳으며) 그룹? 무슨 그룹?"),
(G, "« Maison Vinum ». Vous avez peut-être vu leurs enseignes : du bois clair, des lettres blanches, des bouteilles alignées comme à la parade.", "'메종 비눔'이야. 간판을 봤을지도 몰라. 밝은 나무, 흰 글씨, 열병하듯 정렬된 병들."),
(A, "Je connais. Il y en a un rue de Rivoli. C'est propre, c'est efficace, c'est sans âme.", "알아요. 리볼리 거리에 하나 있어요. 깨끗하고 효율적이고 영혼이 없죠."),
(G, "Voilà. Ils m'ont fait une offre pour racheter le fonds de commerce. Et ce n'est pas une mauvaise offre, malheureusement.", "그래. 영업권을 사겠다고 제안했어. 그리고 불행하게도 나쁜 제안이 아니야."),
(L, "Combien ?", "얼마예요?"),
(G, "Cent quatre-vingt mille euros pour le fonds. Plus une prime de départ, plus une pension de conseil pendant deux ans. Une retraite confortable, ma petite.", "영업권에 18만 유로. 거기에 퇴직 위로금, 그리고 2년간 자문 수당이 더해져. 편안한 노후지, 아가씨."),
(A, "Et toi, tu veux vendre ?", "그럼 넌 팔고 싶어?"),
(G, "(un temps) Je ne sais pas. C'est justement le problème.", "(잠시 후) 모르겠어. 바로 그게 문제야."),
(L, "Tu ne peux pas vendre. Cette boutique, c'est toi. C'est... c'est nous.", "팔 수 없어요. 이 가게는 당신이잖아요. 이건... 우리예요."),
(G, "Léa, écoute-moi. J'ai soixante-huit ans. J'ai mal aux genoux. J'ai mal au dos. L'hiver dernier, j'ai soulevé un carton de vingt-quatre bouteilles et j'ai failli ne plus me relever.", "레아, 들어 봐. 난 예순여덟이야. 무릎도 아프고 허리도 아파. 지난겨울에 스물네 병짜리 상자를 들다가 일어나지 못할 뻔했어."),
(A, "Tu ne nous l'avais jamais dit.", "우리한테는 한 번도 말 안 했잖아."),
(G, "Parce que je ne voulais pas qu'on s'inquiète. Mais c'est une réalité : je ne pourrai pas tenir cette boutique éternellement.", "걱정시키고 싶지 않았으니까. 하지만 현실이야. 이 가게를 영원히 지킬 수는 없어."),
(L, "Tu pourrais prendre quelqu'un pour t'aider.", "누군가를 고용해서 도움을 받을 수 있잖아요."),
(G, "Avec quel argent ? La boutique gagne tout juste de quoi payer le loyer et mon salaire. Il n'y a rien pour embaucher.", "무슨 돈으로? 가게는 월세와 내 월급 낼 정도만 벌어. 직원 쓸 여유는 없어."),
(A, "Et tu n'as pas d'héritier à qui transmettre ?", "물려줄 상속자는 없어?"),
(G, "Aucun. Ni enfant, ni neveu, ni cousin. Mon chat est mon seul héritier, et il n'a jamais rien compris au commerce.", "아무도 없어. 아이도 조카도 사촌도. 고양이가 유일한 상속자인데 장사는 하나도 몰라."),
(A, "Pourquoi as-tu ouvert cette boutique, au départ ? Tu ne nous l'as jamais vraiment raconté.", "처음에 왜 이 가게를 열었어? 제대로 얘기해 준 적이 없잖아."),
(G, "J'étais ouvrier dans une imprimerie. À trente-deux ans, j'ai perdu mon travail quand elle a fermé.", "인쇄소 노동자였어. 서른두 살에 인쇄소가 문을 닫아 일자리를 잃었지."),
(L, "Et tu es devenu caviste du jour au lendemain ?", "그리고 하루아침에 와인 상인이 된 거예요?"),
(G, "Pas du jour au lendemain. J'ai passé un an à parcourir les vignobles de France, avec un sac à dos et trente mille francs d'indemnités.", "하루아침에는 아니지. 배낭 하나와 퇴직금 3만 프랑을 들고 일 년 동안 프랑스 포도원을 돌아다녔어."),
(A, "Trente mille francs.", "3만 프랑."),
(G, "J'ai appris à goûter chez les vignerons, dans les caves, sur les marchés. Chacun m'a donné une bouteille, un conseil, une histoire.", "와인 농가에서, 저장고에서, 시장에서 맛보는 법을 배웠어. 누구나 병 하나, 조언 하나, 이야기 하나를 줬지."),
(L, "Et la boutique ?", "그럼 가게는요?"),
(G, "J'ai trouvé ce local en avril 1990. L'ancien propriétaire vendait des chaussures. Il restait une odeur de cuir.", "1990년 4월에 이 가게를 찾았어. 전 주인은 신발을 팔았지. 가죽 냄새가 남아 있었어."),
(A, "Une odeur de cuir. Un cuir de bibliothèque, peut-être.", "가죽 냄새라. 어쩌면 서재 가죽 향이었겠네."),
(G, "(rit) Peut-être. La première bouteille que j'ai vendue, c'était un Beaujolais. Trois clients en trois mois, c'était déjà de la gloire.", "(웃으며) 어쩌면. 처음 판 병은 보졸레였어. 석 달에 손님 세 명이면 이미 영광이었지."),
(L, "(émue) Gaston...", "(감동하여) 가스통..."),
(G, "Ne me regarde pas comme ça. Je n'ai pas encore décidé. Ils m'ont donné jusqu'à la fin de l'année. Et c'est pour cela que je vous ai réunis ce soir.", "그런 눈으로 보지 마. 아직 결정 안 했어. 연말까지 시간을 줬어. 그래서 오늘 저녁 너희를 모은 거야."),
(A, "Pourquoi nous ?", "왜 우리를?"),
(G, "Parce que vous êtes les deux seules personnes auxquelles j'ai envie de dire la vérité. Mais surtout, parce que je veux vous demander quelque chose.", "진실을 말하고 싶은 사람이 너희 둘뿐이라서. 하지만 무엇보다 부탁할 게 있어서야."),
(L, "Tout ce que tu veux.", "뭐든지요."),
(G, "Ne dites rien à personne, pour l'instant. Ni à Madame Pichon, ni à Karim. Elle serait capable de faire une scène à l'acheteur et de me faire perdre l'offre.", "지금은 아무한테도 말하지 마. 피숑 부인에게도 카림에게도. 부인은 구매자에게 소란을 피워서 제안을 날릴 수도 있어."),
(A, "Tu as peur de perdre l'offre ?", "제안을 놓칠까 봐 걱정돼?"),
(G, "J'ai peur de ne pas savoir ce que je veux. Si je vends, je perds ma vie. Si je ne vends pas, je perds ma santé. Il faut bien que je choisisse la moins mauvaise perte.", "내가 뭘 원하는지 모르는 게 두려워. 팔면 삶을 잃고 안 팔면 건강을 잃어. 덜 나쁜 상실을 골라야 하겠지."),
(L, "Il y a peut-être une troisième voie.", "어쩌면 세 번째 길이 있을 거예요."),
(G, "Une troisième voie ? Léa, je suis un vieux caviste, pas un diplomate.", "세 번째 길? 레아, 난 늙은 와인 상인이지 외교관이 아니야."),
(L, "Je ne sais pas encore laquelle. Mais ce n'est pas une raison pour ne pas la chercher.", "아직 뭔지는 몰라요. 하지만 그게 찾지 않을 이유는 아니죠."),
(A, "On va t'aider, Gaston. Tu n'es pas seul.", "우리가 도울게, 가스통. 넌 혼자가 아니야."),
(G, "(sourit tristement) Je le sais. C'est pour ça que j'ai ouvert ce Morgon-là.", "(쓸쓸히 미소 지으며) 알아. 그래서 이 모르공을 연 거야."),
(None, "Il lève son verre. Léa et Antoine l'imitent. Personne ne parle pendant un long moment. Dehors, les cloches du Sacré-Cœur sonnent dix-neuf heures.", "그가 잔을 든다. 레아와 앙투안이 따라 한다. 한참 동안 아무도 말하지 않는다. 밖에서는 사크레쾨르의 종이 7시를 알린다."),
(None, "Plus tard, dans la rue Lepic. Léa et Antoine marchent vers la rue Durantin. La nuit est tombée, une brise tiède agite les feuilles des platanes.", "잠시 후 르픽 거리. 레아와 앙투안이 뒤랑탱 거리 쪽으로 걷는다. 밤이 내렸고 따뜻한 바람이 플라타너스 잎을 흔든다."),
(A, "Je n'arrive pas à y croire. La boutique, vendue à une chaîne.", "믿을 수가 없어. 가게가 체인점에 팔리다니."),
(L, "Elle n'est pas encore vendue. Il a dit qu'il n'avait pas décidé.", "아직 팔린 건 아니야. 결정 안 했다고 했잖아."),
(A, "Il a parlé de sa santé. Cette fois-ci, c'est sérieux.", "건강 얘기를 했어. 이번엔 진지해."),
(L, "Je sais. Et ça me fait peur, parce que... je ne peux pas imaginer cette rue sans lui.", "알아. 그래서 무서워. 이 거리가 그 사람 없는 모습은 상상할 수 없어."),
(A, "Moi non plus. Cette boutique, c'est là que tout a commencé.", "나도. 그 가게가 모든 게 시작된 곳이잖아."),
(L, "Il faudra trouver une solution. Étant donné que Gaston n'a pas d'héritier, il faut qu'on l'aide à en trouver un.", "해결책을 찾아야 해. 가스통에게 상속자가 없으니 우리가 도와서 찾아야지."),
(A, "Un héritier ? On ne trouve pas un héritier comme on trouve une baguette.", "상속자라니? 바게트 찾듯이 찾는 게 아니잖아."),
(L, "Je ne dis pas que c'est facile. Je dis que c'est possible.", "쉽다는 게 아니야. 가능하다는 거지."),
(A, "(un temps) Tu penses à quelqu'un ?", "(잠시 후) 누굴 생각하고 있어?"),
(L, "Peut-être. Je ne sais pas. Laisse-moi y réfléchir.", "아마도. 모르겠어. 생각 좀 해 볼게."),
(None, "Ils marchent en silence. Devant l'immeuble de Léa, au numéro douze, ils s'arrêtent.", "둘이 말없이 걷는다. 12번지 레아의 건물 앞에서 멈춘다."),
(L, "Antoine, je voulais te parler d'autre chose.", "앙투안, 다른 얘기를 하고 싶었어."),
(A, "Oui ?", "응?"),
(L, "Mon bail se termine en janvier. Mon propriétaire vend l'appartement. Je dois partir avant le trente et un janvier.", "내 임대 계약이 1월에 끝나. 집주인이 아파트를 팔아. 1월 31일 전에 나가야 해."),
(A, "Tu ne me l'avais pas dit.", "나한테는 말 안 했잖아."),
(L, "Je l'ai appris pendant mes vacances à Lyon. Je ne savais pas comment t'en parler, avec tout le reste, Bordeaux, Gaston...", "리옹 휴가 중에 알았어. 다른 것들, 보르도, 가스통 일 때문에 어떻게 말해야 할지 몰랐어."),
(A, "Léa. Tu peux venir chez moi.", "레아. 우리 집에 와도 돼."),
(L, "(surprise) Chez toi ?", "(놀라며) 너희 집에?"),
(A, "Mon appartement est petit, mais il y a une grande fenêtre qui donne sur la cour. Je pourrais libérer un coin pour ta table à dessin.", "집은 작지만 마당으로 난 큰 창이 있어. 네 작업대를 놓을 구석을 비워 줄 수 있어."),
(L, "Antoine, ce n'est pas une décision à prendre à la légère.", "앙투안, 가볍게 내릴 결정이 아니야."),
(A, "Je sais. Je ne te demande pas de répondre ce soir. Je te propose une idée, c'est tout.", "알아. 오늘 밤 대답하라는 게 아니야. 아이디어를 하나 제안하는 것뿐이야."),
(L, "(sourit) Une idée très belle.", "(미소 지으며) 아주 좋은 아이디어야."),
(A, "Mais je comprends que Bordeaux complique les choses.", "하지만 보르도 때문에 복잡해지는 건 이해해."),
(L, "Oui. Si je pars en janvier, la question ne se pose même plus.", "응. 1월에 떠나면 질문 자체가 의미가 없어."),
(A, "Alors on en reparle après le quinze novembre.", "그럼 11월 15일 이후에 다시 얘기하자."),
(L, "Après le quinze novembre. D'accord.", "11월 15일 이후에. 좋아."),
(None, "Elle l'embrasse et franchit la porte. Antoine reste un moment sur le trottoir, pensif, avant de remonter la rue.", "그녀가 그에게 입 맞추고 문을 넘어간다. 앙투안이 생각에 잠긴 채 잠시 인도에 서 있다가 거리를 올라간다."),
(None, "Le lendemain matin, vendredi 5 septembre, 8 h 05. Au lycée, dans une salle de classe du premier étage. Trente élèves de seconde sont assis, bruyants, au milieu des cartables.", "다음 날 아침 9월 5일 금요일 8시 5분. 고등학교 2층 교실. 1학년 학생 서른 명이 가방 사이에 앉아 소란스럽다."),
(A, "Silence, s'il vous plaît. Bonjour à tous. Je m'appelle Monsieur Delcourt, et je serai votre professeur d'histoire cette année.", "조용히 해 주세요. 모두 안녕하세요. 저는 델쿠르 선생님이고 올해 여러분의 역사 선생님입니다."),
(E, "Monsieur, c'est vrai qu'il faut tout apprendre par cœur ?", "선생님, 전부 외워야 하는 거 맞아요?"),
(A, "Non. Je ne veux pas que vous appreniez par cœur. Je veux que vous compreniez pourquoi les choses se sont passées comme elles se sont passées.", "아니요. 외우는 건 원하지 않아요. 일들이 왜 그렇게 일어났는지 이해하길 바랍니다."),
(F, "Pourquoi, Monsieur, c'est important ?", "선생님, 왜 중요한 건가요?"),
(A, "Parce que comprendre le passé permet d'éviter de répéter les mêmes erreurs. Du moins, c'est la théorie.", "과거를 이해하면 같은 실수를 반복하지 않을 수 있으니까요. 적어도 이론상으로는요."),
(E, "Et dans la pratique ?", "그럼 실제로는요?"),
(A, "Dans la pratique, on répète quand même. Mais on le fait avec un peu plus de conscience.", "실제로는 그래도 반복해요. 하지만 조금 더 자각하면서 반복하죠."),
(E, "Monsieur, est-ce que la Révolution française était vraiment nécessaire ?", "선생님, 프랑스 혁명이 정말 필요했나요?"),
(A, "C'est une excellente question. Qu'en pensez-vous, vous ?", "아주 좋은 질문이에요. 여러분은 어떻게 생각하죠?"),
(F, "Je pense que sans elle, on aurait encore un roi.", "저는 혁명이 없었다면 아직도 왕이 있었을 거라고 생각해요."),
(E, "Ce ne serait pas si mal.", "그것도 나쁘지 않을 텐데."),
(A, "Ah ! Voilà un débat. Levez la main si vous préférez avoir un roi.", "아! 토론이 시작됐네요. 왕이 있는 쪽이 좋은 사람은 손을 드세요."),
(F, "Deux mains levées, Monsieur. Mais l'une appartient à Hugo, qui dort.", "두 명이 들었어요, 선생님. 하지만 한 명은 자고 있는 위고예요."),
(A, "Hugo, réveillez-vous. Même les rois dorment moins en cours.", "위고, 일어나요. 왕들도 수업 중엔 덜 자요."),
(E, "(riant) Monsieur, vous êtes drôle quand vous êtes de bonne humeur.", "(웃으며) 선생님은 기분이 좋을 때 재밌어요."),
(F, "Monsieur, on a entendu dire que vous aviez une copine.", "선생님, 여자 친구가 있다고 들었어요."),
(A, "(un temps) Qui vous a dit ça ?", "(잠시 후) 누가 그런 말을 했어요?"),
(F, "La concierge de l'immeuble de ma tante. Elle connaît tout le monde dans le neuvième.", "이모 건물 관리인이요. 9구 사람들을 다 알아요."),
(A, "(soupire) Je vois que les concierges ont un meilleur réseau que les services de renseignement. Mais je ne répondrai pas à cette question.", "(한숨을 쉬며) 관리인들이 정보기관보다 더 좋은 네트워크를 갖고 있군요. 하지만 그 질문엔 대답하지 않겠습니다."),
(E, "Ça veut dire oui.", "그건 '네'라는 뜻이잖아요."),
(A, "Ça veut dire que nous allons étudier la Révolution française. Ouvrez vos manuels à la page douze.", "프랑스 혁명을 공부한다는 뜻이에요. 교과서 12쪽을 펴세요."),
(F, "Monsieur, elle est comment ?", "선생님, 어떤 분이세요?"),
(A, "Page douze. Tout de suite. Sinon, devoir surprise.", "12쪽. 지금 당장. 안 그러면 깜짝 숙제예요."),
(None, "Les élèves ouvrent leurs manuels en riant. Antoine, de dos, les oreilles un peu rouges, écrit « 1789 » au tableau.", "학생들이 웃으며 교과서를 편다. 뒤돌아선 앙투안이 귀가 약간 붉어진 채 칠판에 '1789'를 쓴다."),
(E, "(à voix basse, à sa voisine) Elle existe, c'est sûr.", "(옆자리에게 작은 소리로) 있는 게 확실해."),
(F, "(à voix basse) Il est amoureux. Regarde comme il écrit droit.", "(작은 소리로) 사랑에 빠졌네. 글씨 쓰는 거 똑바른 것 좀 봐."),
(A, "(sans se retourner) J'entends tout. Quatre pages d'exercices, pour demain.", "(돌아보지 않고) 다 들려요. 내일까지 4쪽 연습 문제예요."),
(E, "Quoi ? Pour demain ?", "뭐요? 내일까지요?"),
(A, "Pour demain. La vérité a un prix.", "내일까지. 진실에는 대가가 있죠."),
(None, "La cloche sonne. Les élèves se lèvent dans un tumulte joyeux. Antoine reste seul devant le tableau, un morceau de craie à la main, avec un sourire qu'il ne cherche plus à cacher.", "종이 울린다. 학생들이 즐거운 소란 속에서 일어난다. 앙투안이 분필 한 조각을 든 채 칠판 앞에 혼자 남아 더는 숨기지 않는 미소를 짓는다."),
]
VOCAB = [
("A2","la rentrée","개학·새 시즌의 시작","« Au lycée, c'est la rentrée. » 9월 초의 일상"),
("A2","un élève / une élève / un cartable","학생 / 가방","중학교·고등학교에서 쓰는 표현"),
("A2","une pancarte / retourner","팻말 / 뒤집다","« retourner la pancarte « Fermé » »"),
("A2","un chat / un héritier","고양이 / 상속자","« Mon chat est mon seul héritier. »"),
("A2","l'offre / une enseigne","제안 / 간판","« Maison Vinum » 의 간판 묘사"),
("B1","un fonds de commerce","영업권(상점 가치)","상점·사업체의 영업권을 매매할 때 쓰는 법률 용어"),
("B1","une prime de départ","퇴직 위로금","« une prime de départ, plus une pension de conseil »"),
("B1","embaucher / une mallette","고용하다 / 서류 가방","« Il n'y a rien pour embaucher. »"),
("B1","soulever / se relever","들어 올리다 / 다시 일어나다","건강 약화를 설명하는 장면의 동작"),
("B1","un bail / un propriétaire","임대 계약 / 집주인","« Mon bail se termine en janvier. »"),
("B1","libérer un coin","한 귀퉁이를 비우다","« libérer un coin pour ta table à dessin »"),
("B2","étant donné que / du fait que","~이므로","« Étant donné que Gaston n'a pas d'héritier… » 원인·이유 접속구"),
("B2","un acheteur / racheter","구매자 / 인수하다","« Ils m'ont fait une offre pour racheter le fonds. »"),
("B2","à la légère / à la parade","가볍게 / 열병식으로","« Ce n'est pas une décision à prendre à la légère. »"),
("B2","apprendre par cœur","암기하다","« Tout apprendre par cœur » 교육 장면"),
("B2","répéter les mêmes erreurs","같은 실수를 반복하다","역사 교육의 목적"),
("B2","une pension de conseil","자문 수당","경영에서 물러난 뒤의 컨설팅 계약"),
("B2","une chaîne (de magasins)","체인점","« une chaîne qui possède quarante magasins »"),
("C1","sans âme","영혼 없는","체인점을 비판하는 표현"),
("C1","une perte la moins mauvaise","덜 나쁜 상실","« choisir la moins mauvaise perte » 가스통의 딜레마"),
("C1","avoir un meilleur réseau que les services de renseignement","정보기관보다 더 좋은 네트워크를 갖다","관리인의 소문 능력을 풍자"),
("C1","La vérité a un prix.","진실에는 대가가 있다.","숙제를 내리는 농담조 격언"),
("C1","Il y a un début à tout, et une fin à tout.","모든 일에는 시작과 끝이 있다.","가스통의 시작 문장. 속담 변형"),
("C1","Elle serait capable de faire une scène.","그녀는 소란을 피울 수도 있을 것이다.","être capable de + inf: 가능성·성향"),
]
GRAM = [
("B1","원인 표현: parce que / puisque / car / comme",
 "« Parce que je ne voulais pas qu'on s'inquiète. » (이유 설명) « Puisque tu le dis… » (이미 알려진 이유) « Car il faut… » (문어체) « Comme il pleuvait, je suis resté. » 문장 맨 앞에서 이유를 먼저 말할 때는 comme."),
("B1","목적 표현: pour / afin de / pour que + 접속법",
 "« Je vous ai réunis pour vous demander quelque chose. » « Je ferai tout pour que tu restes. » 주어가 같으면 pour + 부정사, 다르면 pour que + 접속법. afin de/afin que는 더 격식."),
("B2","étant donné que / du fait que / puisque",
 "« Étant donné que Gaston n'a pas d'héritier, il faut qu'on l'aide. » 이유를 객관적 사실로 제시할 때. 뒤에는 직설법. 격식체와 논증문에서 자주 쓰인다."),
("B2","관계대명사 auquel / auxquels / duquel",
 "« Les deux seules personnes auxquelles j'ai envie de dire la vérité. » à + 관계대명사 = auquel(남성 단수), à laquelle, auxquels, auxquelles. 사람 선행사에는 à qui도 가능: « les gens à qui je parle »."),
("B2","접속법: Je ne veux pas que… / Je veux que…",
 "« Je ne veux pas que vous appreniez par cœur. » « Je veux que vous compreniez. » vouloir que + 접속법. 교사의 말투는 접속법으로 의도를 명확히 보여 준다."),
("B2","être en train de / venir de (복습)",
 "« Je suis en train d'essayer de vous le dire. » « Je viens de comprendre. » 진행과 방금의 시제 표현을 문장에서 구분."),
("C1","조건법 현재: 가능성과 추측",
 "« Elle serait capable de faire une scène. » « Une troisième voie ? » 조건법은 일어날 수 있는 일을 추측할 때 쓴다. 확실하지 않은 정보도 조건법으로 완곡하게."),
("C1","강조: Ne me regarde pas comme ça. / ce n'est pas une raison pour ne pas…",
 "« Ce n'est pas une raison pour ne pas la chercher. » ce n'est pas une raison pour + 부정 부정사: 논리적 반박. 토론에서 자주 쓰이는 구문이다."),
]
CULTURE = [
("프랑스의 소규모 와인 가게와 체인점",
 "프랑스에서도 독립 와인 가게(caviste indépendant)가 체인점(Nicolas, Maison Vinum 같은 가상 브랜드)에 밀리는 추세다. 소유주가 고령이 되어도 후계자가 없어 가게를 팔 경우 'fonds de commerce'(영업권)와 '임대권'을 함께 거래한다. 단골 문화와 개성은 독립 상점의 가장 큰 가치다."),
("프랑스의 개학과 고등학교",
 "프랑스 고등학교(lycée)는 seconde(1학년)·première(2학년)·terminale(3학년)로 구성된다. 9월 초 개학일에는 교사가 첫 수업에서 연간 학습 방침을 알려 준다. 학생들 사이에서 교사 사생활에 대한 소문이 도는 것은 흔한 풍경이다."),
("'fonds de commerce' 와 가게 인수",
 "영업권은 상호·단골·임대권·재고·장비를 포함하는 무형·유형 자산의 합이다. 프랑스에서는 가게를 사고팔 때 공증인·회계사가 평가를 하며, 이 에피소드의 제안 가격은 가상의 금액이다."),
]
META = dict(part=3, ep=25, part_label="제3부 늦수확 · Vendanges tardives", title_fr="La rentrée", title_ko="새 학기",
 place="La Cave des Abbesses → 르픽 거리 → 고등학교 교실 · 9월 4~5일",
 chars="Léa · Antoine · Gaston · Un élève · Une élève",
 wine="Morgon (첫날과 같은 도멘) — 가스통의 고백을 위한 와인",
 focus="원인·목적 접속어, étant donné que, auquel/auxquels, 접속법(vouloir que), 조건법 추측",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제26화 « L'offre de Bordeaux » : 정식 계약서가 도착한다. 레아는 장단점을 그림으로 그려 보고 두 사람은 처음으로 서로의 미래를 구체적으로 계산한다.")
