# -*- coding: utf-8 -*-
L, A, M = "Léa", "Antoine", "Mme Lacoste"
D = [
(None, "Samedi 20 septembre, 10 h. Dans le studio de Léa, rue Durantin. Sur la table à dessin, une grande enveloppe blanche, ouverte, d'où dépassent plusieurs feuilles agrafées. Antoine, assis sur le canapé avec un thé, observe Léa qui relit le premier paragraphe pour la troisième fois.", "9월 20일 토요일 오전 10시. 뒤랑탱 거리 레아의 원룸. 작업 책상 위에 열린 큰 흰 봉투에서 스테이플러로 철한 서류 몇 장이 삐져나와 있다. 소파에 앉아 차를 마시던 앙투안이 첫 단락을 세 번째 다시 읽는 레아를 지켜본다."),
(A, "Alors ? Ça fait vingt minutes que tu lis.", "그래서? 이십 분째 읽고 있잖아."),
(L, "C'est le contrat. Le vrai. Reçu ce matin, par coursier. Avec une plume en cadeau, une plume de calligraphie. Ils ont du style.", "계약서야. 진짜. 오늘 아침에 퀵서비스로 왔어. 선물로 깃펜도 같이. 센스가 있네."),
(A, "Lis-moi les points essentiels. Je suis professeur, je lis très bien les textes que d'autres ont mal écrits.", "핵심만 읽어 줘. 난 교사라서 남이 잘못 쓴 글을 아주 잘 읽어."),
(L, "(lit) « Article premier : La société Lacoste & Fils engage Madame Léa Fontaine en qualité de directrice artistique, à compter du cinq janvier prochain, dans le cadre d'un contrat à durée indéterminée. »", "(읽는다) '제1조 라코스트 앤 필스 사는 퐁텐 레아 씨를 오는 1월 5일부터 무기 계약으로 아트 디렉터로 채용한다.'"),
(A, "Un CDI. C'est rare dans le milieu créatif.", "무기 계약이라니. 창작 분야에선 드문데."),
(L, "(continue) « Article deux : La période d'essai est fixée à quatre mois, renouvelable une fois. »", "(이어서) '제2조 수습 기간은 4개월로 하며 1회 갱신할 수 있다.'"),
(A, "Quatre mois, c'est long. Mais normal pour un poste de cadre.", "4개월은 길어. 하지만 관리직으로선 정상이야."),
(L, "« Article trois : La rémunération brute annuelle est fixée à cinquante-deux mille euros, hors primes. »", "'제3조 연간 세전 보수는 상여금을 제외하고 5만 2천 유로로 한다.'"),
(A, "Cinquante-deux mille euros bruts. C'est... presque le double de ce que tu gagnes.", "세전 5만 2천 유로. 네가 버는 것의 거의 두 배야."),
(L, "Je sais. « Article quatre : La salariée dispose d'un bureau individuel au siège de la société, à Bordeaux, quartier des Chartrons. »", "알아. '제4조 직원은 보르도 샤르트롱 지구 본사에 개인 사무실을 갖는다.'"),
(A, "À Bordeaux. Donc pas de télétravail ?", "보르도라. 재택근무는 없다는 거야?"),
(L, "L'article cinq est là-dessus : « Le télétravail est autorisé un jour par semaine, sous réserve d'accord préalable de la direction. »", "제5조가 그에 관한 거야. '재택근무는 주 1일 허용하며 경영진의 사전 동의를 조건으로 한다.'"),
(A, "Un jour par semaine. Donc quatre jours à Bordeaux.", "주 1일. 그러니 나흘은 보르도에 있어야 하네."),
(L, "Exactement. Quatre jours à Bordeaux, un jour libre, et le week-end... pour prendre le TGV.", "맞아. 보르도에서 나흘, 하루는 자유, 그리고 주말은... TGV를 타고 오는 거지."),
(A, "Le TGV Paris-Bordeaux dure deux heures et quatorze minutes, maintenant.", "지금은 파리-보르도 TGV가 2시간 14분 걸려."),
(L, "Deux heures quatorze. À condition qu'il n'y ait ni grève, ni retard.", "2시간 14분. 파업도 지연도 없다는 조건에서."),
(A, "Les deux, ça arrive.", "둘 다 일어나는 일이지."),
(L, "(ironique) Le TGV, c'est comme la météo : on ne peut pas s'y fier.", "(비꼬며) TGV는 날씨 같아. 믿을 수가 없어."),
(None, "Elle repose les feuilles, se lève, prend une grande feuille blanche et un fusain. Elle trace une ligne verticale au milieu.", "그녀가 서류를 내려놓고 일어나 큰 흰 종이와 목탄을 든다. 가운데에 세로선을 긋는다."),
(A, "Qu'est-ce que tu fais ?", "뭐 하는 거야?"),
(L, "Un tableau. À gauche : ce que Bordeaux m'apporte. À droite : ce que Paris m'apporte. Je vais tout noter.", "표를 만들어. 왼쪽에는 보르도가 주는 것, 오른쪽에는 파리가 주는 것. 전부 적을 거야."),
(A, "Tu me demandes de t'aider ?", "내게 도와 달라는 거야?"),
(L, "Je te demande de ne pas t'inquiéter. Si je te le dis, c'est pour que tu voies mon raisonnement.", "걱정하지 말라는 거야. 너한테 말하는 건 내 사고 과정을 보여 주려는 거야."),
(A, "D'accord. Je me tais, je regarde.", "알았어. 입 다물고 보고 있을게."),
(L, "(écrit à gauche) Sécurité. Un vrai salaire. Une équipe de douze personnes. Un vrai budget de création.", "(왼쪽에 쓴다) 안정. 진짜 월급. 열두 명의 팀. 진짜 창작 예산."),
(A, "Ce sont de très bons arguments.", "아주 좋은 근거야."),
(L, "(écrit à droite) Toi. Gaston. Madame Pichon. Hugo, quand il passe. Ma liberté. Mes clients actuels. Le canal. Les marchés.", "(오른쪽에 쓴다) 너. 가스통. 피숑 부인. 위고가 올 때. 나의 자유. 지금의 고객들. 운하. 시장."),
(A, "(un temps, ému) Je suis le premier.", "(잠시 후 감동하여) 내가 맨 처음이네."),
(L, "Je les écris dans l'ordre où ils me viennent.", "떠오르는 순서대로 쓰는 거야."),
(A, "Alors je suis le premier qui te vient.", "그럼 내가 제일 먼저 떠오르는 거네."),
(L, "(rit) Concentre-toi, Antoine. C'est un exercice sérieux.", "(웃으며) 집중해, 앙투안. 진지한 연습이야."),
(A, "Je suis très concentré. Je suis ému et concentré.", "아주 집중하고 있어. 감동하고 집중하고 있지."),
(L, "(continue à gauche) Un risque : l'inconnu. Une ville où je ne connais personne, sauf Madame Lacoste.", "(왼쪽에 이어서) 위험: 미지. 라코스트 대표 말고는 아무도 모르는 도시."),
(A, "Tu as aussi mentionné l'accident, à Lyon.", "리옹에서의 사고도 얘기했었어."),
(L, "Oui. Mais je l'ai raconté à mon père. La promesse est levée. Ce n'est plus un frein.", "응. 하지만 아빠께 말씀드렸어. 약속은 풀렸고 더는 걸림돌이 아니야."),
(A, "C'est un énorme pas.", "엄청난 한 걸음이야."),
(L, "Oui. (Elle écrit.) Reste la question de toi.", "응. (쓴다.) 남은 건 너에 대한 질문이야."),
(A, "Moi ?", "나?"),
(L, "Si je pars, que devient-on ?", "내가 떠나면 우린 어떻게 돼?"),
(A, "Si tu pars, on devient deux personnes qui se voient les week-ends. Ce n'est pas une catastrophe, mais ce n'est pas la même vie.", "네가 떠나면 우린 주말에만 만나는 두 사람이 되겠지. 재앙은 아니지만 같은 삶은 아니야."),
(L, "Et si je reste ?", "내가 남으면?"),
(A, "Si tu restes, tu risques de te demander toute ta vie ce que tu as manqué.", "네가 남으면 평생 뭘 놓쳤는지 궁금해할 위험이 있어."),
(L, "Tu es honnête.", "정직하네."),
(A, "J'essaie. C'est plus facile que de mentir, quand on aime vraiment quelqu'un.", "노력해. 누군가를 정말 사랑할 때는 거짓말하는 것보다 쉬워."),
(L, "(émue) Je ne sais pas ce que je ferais sans toi.", "(감동하여) 네가 없으면 어떻게 할지 모르겠어."),
(A, "Tu ferais exactement ce que tu fais maintenant : tu réfléchirais, tu dessinerais, tu poserais les bonnes questions.", "지금 하는 그대로 하겠지. 생각하고 그리고 좋은 질문을 던질 거야."),
(None, "Le téléphone de Léa sonne sur la table. L'écran affiche : « Mme Lacoste ». Elle prend une grande inspiration.", "탁자 위에서 레아의 전화기가 울린다. 화면에 '라코스트 대표'라고 뜬다. 그녀가 크게 숨을 들이쉰다."),
(L, "(décroche, mettant le haut-parleur) Allô, Madame Lacoste ?", "(스피커폰으로 받으며) 여보세요, 라코스트 대표님?"),
(M, "Bonjour, Léa. Excusez-moi de vous appeler un samedi. J'ai pensé que vous auriez reçu le contrat ce matin.", "안녕하세요, 레아. 토요일에 전화드려서 죄송해요. 오늘 아침 계약서를 받으셨을 것 같아서요."),
(L, "Je l'ai reçu, oui. Merci pour la plume. Elle est superbe.", "네, 받았어요. 깃펜 감사합니다. 정말 멋져요."),
(M, "J'espère qu'elle servira un jour à signer quelque chose de beau. Avez-vous des questions ?", "언젠가 멋진 걸 서명하는 데 쓰였으면 좋겠네요. 질문이 있으세요?"),
(L, "Oui, quelques-unes. Tout d'abord, sur le télétravail. Un jour par semaine, c'est le maximum ?", "네, 몇 가지 있어요. 우선 재택근무요. 주 1일이 최대인가요?"),
(M, "Pour le moment, oui. C'est la politique de la maison. Une agence créative a besoin de présence, de conversations dans les couloirs, de spontanéité.", "지금은 그렇습니다. 회사 방침이에요. 창작 에이전시는 복도의 대화와 즉흥성, 곧 현장 존재감이 필요해요."),
(L, "Je comprends. Mais je me demandais s'il n'existerait pas une formule hybride pour les cadres seniors.", "이해해요. 하지만 시니어 관리자에게 하이브리드 방식이 있을 수 없을까 생각했어요."),
(M, "Une formule hybride. (Un silence.) Vous avez une raison particulière de poser cette question ?", "하이브리드 방식이라. (침묵) 이 질문을 하는 특별한 이유가 있나요?"),
(L, "Oui. J'ai quelqu'un à Paris. Quelqu'un d'important pour moi.", "네. 파리에 사람이 있어요. 제게 중요한 사람이에요."),
(M, "Je vois. Et c'est un obstacle ?", "알겠어요. 그게 장애물인가요?"),
(L, "Ce n'est pas un obstacle. C'est une donnée. Ce que je voudrais, c'est comprendre jusqu'où l'entreprise peut s'adapter.", "장애물이 아니라 변수예요. 제가 알고 싶은 건 회사가 어디까지 맞춰 줄 수 있느냐예요."),
(M, "Hum. Léa, je vais être franche : je ne suis pas contre la flexibilité. Mais je ne peux pas offrir un régime d'exception sans en parler à mon associé.", "음. 레아, 솔직히 말할게요. 유연성에 반대하지 않아요. 하지만 동업자와 상의하지 않고 예외 제도를 제안할 수는 없어요."),
(L, "Je comprends.", "이해해요."),
(M, "Mais si je lui présentais un projet précis, avec des objectifs, des déplacements réguliers à Bordeaux, et une présence ponctuelle pour les réunions importantes... Peut-être. Je dis bien peut-être.", "하지만 구체적인 계획, 정해진 목표, 정기적인 보르도 출장, 중요한 회의 때의 현장 참석을 제안해 본다면... 어쩌면요. 어쩌면이라고 말했어요."),
(L, "Vous seriez prête à étudier cette possibilité ?", "그 가능성을 검토해 주실 수 있으세요?"),
(M, "À condition que vous me remettiez un document structuré avant le trente octobre. Pas un coup de cœur : un plan.", "10월 30일 전에 체계적인 문서를 제출하시는 조건으로요. 충동이 아니라 계획이어야 해요."),
(L, "Je vous le ferai parvenir. Merci, Madame Lacoste.", "보내 드리겠습니다. 감사합니다, 라코스트 대표님."),
(M, "Ne me remerciez pas. C'est dans mon intérêt : je tiens à vous. Au revoir, Léa.", "감사하지 마세요. 제 이익을 위해서입니다. 당신이 필요하니까요. 안녕히 계세요, 레아."),
(None, "Elle raccroche. Un silence. Antoine, qui n'a pas dit un mot pendant tout l'appel, pose doucement sa tasse.", "그녀가 전화를 끊는다. 침묵. 통화 내내 한마디도 하지 않은 앙투안이 조심스럽게 잔을 내려놓는다."),
(A, "Tu as demandé une formule hybride. Pour moi.", "혼합 근무를 요청했네. 나를 위해."),
(L, "Pas seulement pour toi. Pour moi aussi. Je ne veux pas vivre dans une seule ville. Je ne suis pas faite pour ça.", "너만을 위해서가 아니야. 나를 위해서도. 한 도시에서만 사는 건 싫어. 그렇게 만들어지지 않았어."),
(A, "C'est la première fois que tu le dis.", "그렇게 말하는 건 처음이야."),
(L, "C'est la première fois que je le comprends.", "그렇게 이해한 것도 처음이야."),
(A, "Alors on a un plan.", "그럼 계획이 생겼네."),
(L, "On a un début de plan. Il faut le structurer, le chiffrer, le défendre. Tu m'aides ?", "계획의 시작이 있는 거지. 구조화하고 수치화하고 설득해야 해. 도와줄래?"),
(A, "À une condition.", "한 가지 조건으로."),
(L, "Laquelle ?", "어떤 조건?"),
(A, "Qu'on prenne un vrai petit-déjeuner, d'abord. Je n'ai rien mangé depuis hier soir.", "먼저 제대로 아침을 먹는 거야. 어젯밤 이후로 아무것도 안 먹었어."),
(L, "(rit) C'est la meilleure condition qu'on m'ait jamais posée.", "(웃으며) 내가 들어 본 최고의 조건이야."),
(A, "Je prépare des œufs brouillés. Toi, tu continues ton tableau.", "내가 스크램블 에그를 만들게. 넌 표를 계속 그려."),
(L, "Parfait.", "좋아."),
(None, "Il se lève et va dans la minuscule cuisine ouverte. Léa se rassoit devant sa feuille. À gauche, elle ajoute : « Madame Lacoste : une porte entrouverte. » À droite, elle écrit en capitales : « ANTOINE. » Elle entoure le mot.", "그가 일어나 작은 오픈 키친으로 간다. 레아가 다시 종이 앞에 앉는다. 왼쪽에 '라코스트 대표: 살짝 열린 문'이라 적는다. 오른쪽에는 대문자로 '앙투안'이라 쓰고 동그라미를 친다."),
(A, "(depuis la cuisine, en cassant des œufs) Au fait, ma proposition d'emménager ensemble tient toujours, tu sais.", "(부엌에서 계란을 깨며) 그런데 같이 살자는 내 제안은 아직 유효해."),
(L, "Je n'ai pas oublié.", "잊지 않았어."),
(A, "Je ne te presse pas. Je voulais juste que tu saches que ce n'est pas lié à Bordeaux.", "재촉하지 않아. 보르도와는 상관없다는 걸 알려 주고 싶었어."),
(L, "Je le sais. C'est pour ça que ça me touche autant.", "알아. 그래서 더 마음에 와닿아."),
(A, "Que ce soit à Paris, à Bordeaux ou à Saumur, je veux dire.", "파리든 보르도든 소뮈르든 말이야."),
(L, "(émue) Antoine. Tu m'as dit « Saumur ».", "(감동하여) 앙투안. '소뮈르'라고 말했어."),
(A, "Je l'ai dit en passant.", "지나가듯 말한 거야."),
(L, "Tu ne dis jamais rien en passant.", "넌 지나가듯 말하는 법이 없잖아."),
(A, "C'est vrai. J'y réfléchis depuis deux semaines. Julien m'a proposé un partenariat, tu t'en souviens ?", "맞아. 이 주째 생각하고 있어. 쥘리앵이 파트너십을 제안했던 거 기억해?"),
(L, "Bien sûr.", "물론이지."),
(A, "Je n'ai pas encore répondu. Mais si je dis oui, je passerai la moitié de l'année à Saumur et l'autre à Paris. Un peu comme toi, avec Bordeaux.", "아직 대답 안 했어. 하지만 승낙하면 일 년의 절반은 소뮈르에서, 나머지 절반은 파리에서 보내게 돼. 너와 보르도처럼."),
(L, "(se lève, s'approche de la cuisine) Alors on pourrait avoir deux vies à deux endroits. Un peu comme des vignerons nomades.", "(일어나 부엌으로 다가가며) 그럼 우린 두 곳에서 두 삶을 살 수도 있겠네. 유목하는 와인 농부처럼."),
(A, "Des vignerons nomades. Le vin voyage bien, après tout.", "유목하는 와인 농부라. 와인도 어쨌든 여행을 잘하니까."),
(L, "(rit) Tu inventes des métiers.", "(웃으며) 직업을 만들어 내고 있어."),
(A, "J'invente un avenir. C'est mon métier : je transforme le passé en leçon.", "미래를 만들고 있는 거야. 그게 내 직업이야. 과거를 교훈으로 바꾸는 거지."),
(L, "Et l'avenir, tu le transformes en quoi ?", "그럼 미래는 뭐로 바꾸는데?"),
(A, "En œufs brouillés, pour l'instant. Viens, c'est prêt.", "지금은 스크램블 에그로. 이리 와, 다 됐어."),
(None, "Ils s'installent à la petite table près de la fenêtre. La lumière d'automne tombe sur la feuille blanche, où la ligne verticale sépare deux colonnes encore inachevées.", "둘이 창가 작은 식탁에 앉는다. 가을 햇살이 하얀 종이 위에 내려앉는다. 세로선이 아직 미완성인 두 열을 가르고 있다."),
(L, "Antoine ? À propos de ce tableau.", "앙투안? 이 표 말인데."),
(A, "Oui ?", "응?"),
(L, "À la fin, il y aura peut-être une colonne de plus.", "마지막에는 열이 하나 더 생길지도 몰라."),
(A, "Laquelle ?", "어떤 열?"),
(L, "Celle du milieu. « Nous deux. »", "가운데 열. '우리 둘'."),
(A, "(sourit) J'aime bien celle-là.", "(미소 지으며) 그 열이 마음에 들어."),
(L, "Moi aussi.", "나도."),
(None, "Dehors, un orage lointain gronde sur les toits de Montmartre. Mais dans le petit studio, il fait chaud, et il sent le beurre fondu et le café.", "밖에서는 먼 뇌우가 몽마르트르 지붕 위에서 으르렁댄다. 하지만 작은 원룸 안은 따뜻하고 녹은 버터와 커피 냄새가 난다."),
(A, "Mange. Les contrats se lisent mieux le ventre plein.", "먹어. 계약서는 배가 부를 때 더 잘 읽혀."),
]
VOCAB = [
("A2","un contrat / un bureau / un salaire","계약 / 사무실 / 월급","직장 기본 어휘"),
("A2","une enveloppe / une plume","봉투 / 깃펜","« une plume de calligraphie »"),
("A2","un petit-déjeuner / des œufs brouillés","아침 식사 / 스크램블 에그","« Les contrats se lisent mieux le ventre plein. »"),
("A2","un tableau / une ligne verticale","표(그림) / 세로선","레아가 장단점을 표로 정리"),
("B1","engager quelqu'un en qualité de","~의 자격으로 채용하다","« engage Madame Léa Fontaine en qualité de directrice artistique »"),
("B1","à compter du / un CDI","~일부터 / 무기 계약","« à compter du cinq janvier prochain », CDI = contrat à durée indéterminée"),
("B1","la période d'essai","수습 기간","« fixée à quatre mois, renouvelable une fois »"),
("B1","la rémunération brute annuelle","연간 세전 보수","« cinquante-deux mille euros bruts »"),
("B1","le télétravail / un jour par semaine","재택근무 / 주 1일","현대 직장 어휘"),
("B1","un coursier","퀵서비스 배달원","« reçu par coursier »"),
("B2","un poste de cadre / hors primes","관리직 / 상여금 제외","계약서 어휘"),
("B2","sous réserve de / à condition que + 접속법","~을 조건으로","« sous réserve d'accord préalable », « à condition que vous me remettiez… »"),
("B2","une formule hybride / un régime d'exception","하이브리드 방식 / 예외 제도","근무 형태 협상에서 쓰는 표현"),
("B2","un associé / la politique de la maison","동업자 / 회사 방침","« je ne peux pas… sans en parler à mon associé »"),
("B2","structurer / chiffrer / défendre","구조화하다 / 수치화하다 / 변호하다","프로젝트 제안의 3단계"),
("B2","une donnée / un frein / un obstacle","변수·데이터 / 걸림돌 / 장애물","« Ce n'est pas un obstacle. C'est une donnée. »"),
("B2","un coup de cœur / une porte entrouverte","충동적인 끌림 / 살짝 열린 문","« Pas un coup de cœur : un plan. »"),
("B2","parvenir à / faire parvenir","도달하다 / ~에게 보내다","« Je vous le ferai parvenir. »"),
("C1","un régime d'exception","예외 제도","직장 내 특례. 격식 있는 표현"),
("C1","vignerons nomades","유목하는 와인 농부","앙투안의 위트 있는 신조어"),
("C1","tenir à quelqu'un","~를 아끼다, 놓치고 싶지 않다","« Je tiens à vous. » 업무상으로도 감정적으로도 사용"),
("C1","en passant","지나가면서","« Tu ne dis jamais rien en passant. »"),
("C1","Quelque chose comme un début de plan","계획의 시작 같은 것","un début de + 명사: 시작 단계의 …"),
("C1","Je transforme le passé en leçon.","나는 과거를 교훈으로 바꾼다.","앙투안의 직업 정의"),
]
GRAM = [
("B1","si 구문의 종류 3가지",
 "① si + 현재, 미래: « Si tu pars, on se verra le week-end. » ② si + 반과거, 조건법 현재: « Si je restais, je me demanderais toujours… » ③ si + 대과거, 조건법 과거: « Si j'avais accepté, je serais déjà à Bordeaux. » 가능성의 정도에 따라 시제 조합이 달라진다."),
("B1","조건 표현: à condition que / à moins que / pourvu que + 접속법",
 "« À condition que vous me remettiez un document. » « À moins que tout change. » « Pourvu qu'il n'y ait pas de grève. » 접속법을 요구하는 조건 접속사. à condition de + 부정사: « à condition de réfléchir »."),
("B2","sous réserve de / dans l'hypothèse où / au cas où",
 "« Sous réserve d'accord préalable. » « Dans l'hypothèse où elle accepterait. » « Au cas où il pleuvrait. » 격식 있는 가정·조건 표현. au cas où는 조건법, dans l'hypothèse où도 조건법."),
("B2","Qu'est-ce qu'il adviendrait si… / Que devient-on ?",
 "« Si je pars, que devient-on ? » devenir의 현재형 « Que devient-on ? » 같은 의문형은 구어체 철학적 질문을 만든다. 시제는 직설법 현재."),
("B2","c'est la première fois que + 현재/복합과거 (복습)",
 "« C'est la première fois que tu le dis. » « C'est la première fois que je le comprends. » 반복 구문으로 강조."),
("B2","접속법: Que ce soit à Paris, à Bordeaux ou à Saumur",
 "« Que ce soit à Paris, à Bordeaux ou à Saumur. » que ce soit A ou B = A든 B든. 양보의 접속법. 문장 맨 앞에서 쓰이는 일반 표현."),
("C1","부정어 조합: ne … rien dit pendant tout l'appel",
 "« Antoine, qui n'a pas dit un mot pendant tout l'appel. » ne pas dire un mot = 한마디도 하지 않다. 강조 표현: « sans dire un mot », « pas un mot ». 문어체에서 자주 쓰인다."),
("C1","공식 문서의 비인칭 수동 문체",
 "« La période d'essai est fixée à quatre mois. » « La salariée dispose d'un bureau. » 계약서는 수동·비인칭 구문으로 쓰인다. 구어체와 비교하면 문체의 차이를 알 수 있다."),
]
CULTURE = [
("프랑스 계약서: CDI와 période d'essai",
 "프랑스에서 CDI(무기 계약)는 가장 안정적인 고용 형태다. 관리직(cadre)의 수습 기간은 법적으로 4개월(1회 갱신 가능, 최대 8개월)이다. 급여는 연봉 세전(brut)으로 표시되는 것이 일반적이다."),
("télétravail 문화",
 "코로나 이후 프랑스는 재택근무를 도입했지만 창작 에이전시 등은 현장 소통을 중시한다. 주 1~2일 재택이 흔한 중간선이며, 하이브리드 협상은 직종·직급에 따라 달라진다."),
("TGV 파리-보르도",
 "2017년 개통한 LGV 노선으로 파리 몽파르나스-보르도 생장역이 약 2시간 5~15분 걸린다. 파업과 지연은 프랑스에서 흔한 변수이며, 'grève'는 일상 어휘다."),
]
META = dict(part=3, ep=26, part_label="제3부 늦수확 · Vendanges tardives", title_fr="L'offre de Bordeaux", title_ko="보르도의 제안",
 place="레아의 원룸, 뒤랑탱 거리 12번지 · 9월 20일 토요일 오전 10시",
 chars="Léa · Antoine · Mme Lacoste (라코스트 대표, 전화)",
 wine="(와인 없음) — 계약서와 아침 식사",
 focus="계약서 문체, si 구문 3종, 조건 접속사(à condition que, sous réserve de), 협상 표현",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제27화 « Le terroir, mythe ou réalité ? » : 와인 가게에서 벌어진 3자 토론. 테루아르를 두고 오가는 양보와 반박의 언어.")
