# -*- coding: utf-8 -*-
L, A, H, G, R, P, M, E, F = "Léa", "Antoine", "Hugo", "Gaston", "Mme Rousseau", "Mme Pichon", "Mme Lacoste", "Un élève", "Une élève"
D = [
(None, "Samedi 1er novembre. Il est cinq heures du matin. Dans un studio de la rue Durantin, une lampe de bureau éclaire une table à dessin couverte de feuilles blanches. Léa n'a pas dormi. Dans un autre appartement, à quinze numéros de là, Antoine non plus.", "11월 1일 토요일. 새벽 5시. 뒤랑탱 거리의 한 원룸에서 책상 램프가 흰 종이로 덮인 작업대를 비춘다. 레아는 잠을 이루지 못했다. 열다섯 번지 떨어진 다른 집에서 앙투안도 마찬가지다."),
(L, "(monologue) Cinq heures. Il fait encore nuit. Je dessine des lignes qui ne veulent rien dire, des cercles, des spirales. Mes mains savent ce que ma tête refuse d'avouer.", "(독백) 새벽 5시. 아직 밤이야. 아무 의미 없는 선, 원, 나선을 그려. 내 머리가 인정하길 거부하는 걸 손은 알고 있어."),
(A, "(monologue) Cinq heures. Le café a refroidi sur la table. Je n'ai pas allumé la lumière. J'ai peur de voir la pièce telle qu'elle est : un appartement où une femme a claqué la porte.", "(독백) 새벽 5시. 식탁 위 커피가 식었어. 불을 켜지 않았어. 있는 그대로의 방을 보는 게 두려워. 한 여자가 문을 쾅 닫고 나간 집."),
(L, "(monologue) « C'est ce que tu sais faire de mieux. » Il l'a dit. Il l'a vraiment dit. Et le pire, c'est que ce n'est pas faux.", "(독백) '그게 네가 제일 잘하는 일이잖아.' 그가 그렇게 말했어. 정말로 그렇게. 그리고 최악은 틀린 말이 아니라는 거야."),
(A, "(monologue) « Tu t'accroches à ta mère morte. » Elle l'a dit. Elle l'a vraiment dit. Et le pire, c'est que je n'ai pas su répondre.", "(독백) '넌 죽은 어머니에게 매달려 있어.' 그녀가 그렇게 말했어. 정말로 그렇게. 그리고 최악은 내가 대답하지 못했다는 거야."),
(L, "(monologue) Peut-être aurait-il fallu que je me taise. Peut-être aurait-il fallu qu'il parle. Ou l'inverse.", "(독백) 내가 입을 다물었어야 했을지도 몰라. 그가 말했어야 했을지도. 아니면 그 반대거나."),
(A, "(monologue) Que n'ai-je dit autre chose ? Que n'ai-je simplement dit : « Reste. Parlons-en. » Trois mots. Trois mots d'une simplicité insultante.", "(독백) 왜 다른 말을 하지 못했을까? 왜 그저 '남아. 얘기하자.'라고 하지 못했을까. 세 마디. 모욕적일 만큼 단순한 세 마디."),
(None, "Dimanche 2 novembre. La Toussaint, un jour de recueillement. Léa, assise sur un banc au cimetière de Montmartre, regarde des familles déposer des chrysanthèmes sur les tombes. Elle ne cherche personne en particulier.", "11월 2일 일요일. 위령의 날이다. 레아가 몽마르트르 묘지 벤치에 앉아 가족들이 무덤에 국화를 올려놓는 모습을 바라본다. 특별히 누군가를 찾는 건 아니다."),
(L, "(monologue) Je ne sais pas pourquoi je suis venue ici. Peut-être pour me rappeler que tout finit. Que les gens meurent, que les histoires finissent, que les mots qu'on n'a pas dits restent sur le seuil.", "(독백) 내가 왜 여기 왔는지 모르겠어. 모든 게 끝난다는 걸 떠올리려고일까. 사람은 죽고 이야기는 끝나고 하지 못한 말은 문턱에 남는다는 걸."),
(A, "(monologue) Je suis allé au Père-Lachaise. J'ai marché sans but entre les tombes. Je me suis assis devant celle d'un inconnu, un certain Édouard Mercier, mort en 1923. Il avait trente-quatre ans. Mon âge.", "(독백) 페르 라셰즈에 갔어. 무덤 사이를 목적 없이 걸었지. 모르는 사람 앞에 앉았어. 1923년에 죽은 에두아르 메르시에. 서른네 살이었어. 내 나이."),
(L, "(monologue) Maman dit toujours : « Les gens se querellent parce qu'ils s'aiment trop pour se séparer et pas assez pour se comprendre. » À l'époque, je trouvais ça stupide.", "(독백) 엄마는 늘 말씀하셨어. '사람들은 헤어지기엔 너무 사랑하고 이해하기엔 충분히 사랑하지 않아서 다툰다'고. 그땐 어리석은 말이라고 생각했어."),
(A, "(monologue) Papa dirait : « Si c'est fait pour revenir, ça revient. » Mais papa n'a pas eu à choisir entre deux régions, entre deux métiers, entre deux femmes.", "(독백) 아빠는 '돌아오기로 정해진 건 돌아온다'고 말씀하시겠지. 하지만 아빠는 두 지방 사이에서, 두 직업 사이에서, 두 여자 사이에서 선택할 필요가 없었어."),
(L, "(monologue) Entre deux femmes... Non. Je suis injuste. Il n'y a jamais eu d'autre femme. Il y a seulement eu la Loire, le domaine, la mémoire de sa mère. Et moi, qui voulais être la première chose qui compte, la seule.", "(독백) 두 여자 사이라니... 아냐. 내가 불공평해. 다른 여자는 없었어. 루아르, 농장, 어머니의 기억이 있었을 뿐이야. 그리고 가장 중요한 첫 번째, 유일한 존재가 되고 싶었던 나."),
(A, "(monologue) Elle n'est pas faible. Elle n'a jamais été faible. Elle a survécu à un accident, à Théo, à un monde qui ne voulait pas de son métier. Qui suis-je pour lui dire qu'elle fuit ?", "(독백) 그녀는 약하지 않아. 한 번도 약했던 적 없어. 사고에서, 테오에게서, 그녀의 직업을 받아들이지 않는 세상에서 살아남았어. 내가 누구라고 그녀에게 도망친다고 말했을까?"),
(None, "Lundi 3 novembre. Au lycée. La récréation vient de sonner. Antoine corrige des copies dans la salle des professeurs, mais son stylo rouge reste suspendu au-dessus de la même phrase depuis dix minutes. Une collègue, Madame Rousseau, s'approche avec un thé.", "11월 3일 월요일. 학교. 쉬는 시간 종이 방금 울렸다. 앙투안이 교무실에서 시험지를 채점하지만 빨간 펜이 십 분째 같은 문장 위에 멈춰 있다. 동료 교사 루소 선생님이 차를 들고 다가온다."),
(A, "(à sa collègue) Merci, Hélène. Je n'avais pas vu que tu étais là.", "(동료에게) 고마워요, 엘렌. 있는 줄 몰랐어요."),
(L, "(monologue) Les élèves m'ont posé une question aujourd'hui, au dessin : « Madame, pourquoi vous dessinez toujours des portes ? » Je n'avais pas réalisé que j'en dessinais.", "(독백) 오늘 학생들이 그림 시간에 질문했어. '선생님, 왜 늘 문을 그리세요?' 내가 문을 그리고 있다는 걸 몰랐어."),
(None, "Léa, depuis quelques jours, donne des cours de dessin à l'association de quartier. Elle enseigne le mercredi après-midi, à des enfants de dix ans.", "며칠 전부터 레아가 동네 협회에서 그림 수업을 한다. 수요일 오후마다 열 살 아이들을 가르친다."),
(A, "(monologue, à haute voix) Hélène, je peux te poser une question ?", "(독백, 소리 내어) 엘렌, 질문 하나 해도 될까요?"),
(R, "Bien sûr. Tu as une mine épouvantable, d'ailleurs.", "물론이죠. 그나저나 안색이 끔찍해요."),
(A, "Si on dit à quelqu'un qu'il fuit, alors qu'il est juste en train de chercher un chemin, est-ce que c'est un mensonge ou une vérité ?", "누군가에게 길을 찾는 중일 뿐인데 도망친다고 말한다면, 그건 거짓일까요, 진실일까요?"),
(R, "Ça dépend si tu le pensais ou si tu voulais faire mal.", "그렇게 생각했는지, 아프게 하려 했는지에 달렸죠."),
(A, "Je voulais lui faire mal.", "아프게 하려 했어요."),
(R, "Alors c'est un mensonge. Même si les faits étaient exacts.", "그럼 거짓말이에요. 사실이 맞았더라도."),
(A, "(un temps) Tu enseignes la philosophie, toi.", "(잠시 후) 선생님은 철학을 가르치시죠."),
(R, "Voilà pourquoi je suis célibataire.", "그래서 제가 독신이에요."),
(A, "(sourit enfin) Merci, Hélène. C'est la première fois que je souris en une semaine.", "(마침내 미소 지으며) 고마워요, 엘렌. 일주일 만에 처음 웃네요."),
(None, "Mardi 4 novembre. Dans la boutique de Gaston. Gaston range des bouteilles avec lenteur. La porte s'ouvre : Léa entre, enveloppée dans un grand manteau gris.", "11월 4일 화요일. 가스통의 가게. 가스통이 병을 천천히 정리하고 있다. 문이 열리고 커다란 회색 코트를 걸친 레아가 들어온다."),
(G, "Léa ! Tu n'es pas venue jeudi dernier.", "레아! 지난 목요일에 안 왔더구나."),
(L, "Non. J'étais... occupée.", "응. 바빴어."),
(G, "Antoine non plus n'est pas venu. Vous êtes occupés tous les deux, en même temps. C'est une coïncidence remarquable.", "앙투안도 안 왔어. 둘 다 동시에 바쁜 거지. 놀라운 우연이야."),
(L, "Gaston...", "가스통..."),
(G, "Je ne demande rien. Je constate. J'ai trente-cinq ans de métier, j'ai vu beaucoup de couples traverser ce genre d'orage. Certains sortent de la tempête plus forts, d'autres se brisent.", "아무것도 묻지 않아. 확인할 뿐이지. 35년 장사하면서 이런 폭풍을 지나는 많은 커플을 봤어. 더 강해져서 나오는 이들도 있고 부서지는 이들도 있지."),
(L, "Et lesquels reviennent, d'après toi ?", "그럼 네 생각엔 어떤 커플이 돌아와?"),
(G, "Ceux qui se parlent. Ceux qui acceptent de dire : « Je me suis trompé. » Trois mots, à nouveau, ma petite : « Je me suis trompé. » C'est le secret des couples qui durent.", "서로 말하는 커플. '내가 틀렸어.'라고 말할 수 있는 커플. 다시 세 마디야, 아가씨. '내가 틀렸어.' 오래가는 커플의 비밀이지."),
(L, "(un temps) Ça, c'est à lui de le dire.", "(잠시 후) 그건 그가 말해야 해."),
(G, "Et toi ? Tu n'as rien à dire ?", "그럼 너는? 할 말이 없어?"),
(L, "Je lui ai dit des choses terribles, Gaston. Sur sa mère. Sur son métier. Je ne sais pas comment on revient de ça.", "그에게 끔찍한 말을 했어, 가스통. 어머니 이야기, 직업 이야기. 거기서 어떻게 돌아가는지 모르겠어."),
(G, "On revient en marchant. Un pas après l'autre. Parfois à reculons.", "걸어서 돌아가는 거야. 한 걸음씩. 때로는 뒷걸음질로."),
(L, "(esquisse un sourire) Tu as une métaphore pour tout.", "(희미하게 미소 지으며) 넌 모든 것에 은유가 있어."),
(G, "Les métaphores, c'est tout ce qui me reste, quand on n'a plus de jambes.", "다리가 없어지면 은유만 남지."),
(None, "Mercredi 5 novembre. Chez Léa. Hugo appelle de Lyon par vidéo. Son visage, flou, apparaît sur l'écran du téléphone posé contre une pile de livres.", "11월 5일 수요일. 레아의 집. 위고가 리옹에서 영상 통화를 건다. 책 더미에 기대어 놓은 전화기 화면에 흐릿한 얼굴이 나타난다."),
(H, "Léa ! Tu as une tête de zombie.", "레아! 좀비 같은 얼굴이야."),
(L, "Bonjour à toi aussi.", "너도 안녕."),
(H, "Maman m'a dit que tu étais allée au cimetière. Tu vas bien ?", "엄마가 누나가 묘지에 갔다고 하셨어. 괜찮아?"),
(L, "Maman a de bons yeux. Même à quatre cents kilomètres.", "엄마는 눈이 좋으셔. 사백 킬로미터 떨어져 있어도."),
(H, "Tu t'es disputée avec Antoine.", "앙투안이랑 싸웠지."),
(L, "Qui te l'a dit ?", "누가 말했어?"),
(H, "Personne. Mais Antoine ne répond plus à mes messages, et toi, tu as la mine d'une lessive oubliée dans une machine pendant trois jours.", "아무도. 하지만 앙투안이 내 메시지에 답이 없고, 누나는 세탁기 안에 삼 일 동안 잊힌 빨래 같은 얼굴이야."),
(L, "Hugo, tu es poétique.", "위고, 시적이네."),
(H, "J'essaie. Écoute : tu veux que je prenne le train ?", "노력 중이야. 있잖아, 내가 기차 타고 갈까?"),
(L, "Non. Je dois régler ça seule. Et lui aussi.", "아니. 이건 나 혼자 해결해야 해. 그 사람도 마찬가지고."),
(H, "D'accord. Mais promets-moi une chose.", "알았어. 하지만 한 가지만 약속해."),
(L, "Laquelle ?", "뭔데?"),
(H, "Que tu ne prendras pas ta décision pour Bordeaux dans un moment de colère. Même si tu es en colère contre lui. Même si tu es en colère contre toi.", "보르도 결정을 화가 난 순간에 내리지 않겠다고. 그에게 화가 났더라도. 자신에게 화가 났더라도."),
(L, "(un temps) Je te le promets.", "(잠시 후) 약속할게."),
(H, "Bon. Maintenant, je te chante une chanson avec le si bémol.", "좋아. 이제 시 플랫이 들어간 노래 불러 줄게."),
(L, "Hugo, non...", "위고, 안 돼..."),
(None, "Il chante. Un peu faux, très tendrement. Léa pleure et rit à la fois, le visage dans ses mains.", "그가 노래한다. 약간 음정이 틀리지만 아주 다정하게. 레아가 손으로 얼굴을 가린 채 울며 웃는다."),
(None, "Mercredi soir, vingt heures. On frappe à la porte de Léa. Elle ouvre, surprise : Madame Pichon, un grand chapeau sur la tête, une assiette recouverte d'un torchon entre les mains.", "수요일 밤 8시. 레아의 문을 두드리는 소리가 난다. 레아가 놀라며 연다. 큰 모자를 쓴 피숑 부인이 행주로 덮은 접시를 두 손에 들고 서 있다."),
(P, "Ouvre, ma petite. C'est moi. Je sais que tu es là, j'ai vu la lumière.", "문 열어, 아가씨. 나야. 있는 거 알아. 불이 켜진 걸 봤어."),
(L, "Madame Pichon ? Comment avez-vous trouvé mon adresse ?", "피숑 부인? 제 주소를 어떻게 찾으셨어요?"),
(P, "J'ai une concierge qui connaît une concierge. Je t'ai apporté un clafoutis aux poires.", "나에겐 관리인을 아는 관리인이 있단다. 배 클라푸티를 가져왔어."),
(L, "Un clafoutis ? Un mercredi soir ?", "클라푸티요? 수요일 밤에요?"),
(P, "Un clafoutis est toujours de saison quand quelqu'un a le cœur lourd. Entre. Assieds-toi. Ne parle pas.", "마음이 무거운 사람 앞에서는 클라푸티가 늘 제철이란다. 들어가자. 앉아. 말하지 말고."),
(None, "Elle s'installe dans le fauteuil, pose l'assiette sur la table à dessin, retire son chapeau. Léa s'assoit en face d'elle, sans un mot.", "그녀가 안락의자에 자리를 잡고 작업대 위에 접시를 놓고 모자를 벗는다. 레아가 말없이 맞은편에 앉는다."),
(P, "À mon âge, je ne donne pas de conseils. Je raconte des histoires.", "내 나이에는 조언을 하지 않아. 이야기를 들려주지."),
(L, "Racontez, alors.", "그럼 들려주세요."),
(P, "Mon mari et moi, en mille neuf cent quatre-vingt-deux, nous nous sommes disputés pendant onze jours. Onze jours sans nous parler, dans le même appartement.", "남편과 나는 1982년에 열하루 동안 다퉜어. 같은 집에서 열하루 동안 말을 하지 않았지."),
(L, "Onze jours ? Comment avez-vous fait pour vivre ensemble ?", "열하루요? 어떻게 같이 지내셨어요?"),
(P, "Nous communiquions par des billets, laissés sur la table de la cuisine. Le onzième jour, il a écrit : « Le pain est dur. » J'ai répondu : « Comme nous. »", "부엌 식탁에 쪽지를 남겨 소통했지. 열하루째에 그가 '빵이 딱딱해.'라고 썼어. 나는 '우리처럼.'이라고 답했고."),
(L, "Et alors ?", "그래서요?"),
(P, "Alors nous avons éclaté de rire. Et nous nous sommes réconciliés. Le rire est un pont, ma petite. Plus solide que la raison, plus rapide que les excuses.", "그래서 우린 웃음을 터뜨렸어. 그리고 화해했지. 웃음은 다리란다, 아가씨. 이성보다 튼튼하고 사과보다 빠르지."),
(None, "Jeudi 6 novembre, 9 h. Le téléphone de Léa vibre sur sa table de travail. Elle reconnaît l'indicatif de Bordeaux.", "11월 6일 목요일 오전 9시. 레아의 전화기가 작업대 위에서 진동한다. 보르도 지역 번호임을 알아본다."),
(M, "Léa, bonjour. J'ai étudié votre plan. Mon associé est ouvert à la formule : trois jours par semaine à Bordeaux, deux jours à distance.", "레아, 안녕하세요. 계획서를 검토했어요. 동업자가 이 방식에 열려 있어요. 주 3일은 보르도, 이틀은 원격이에요."),
(L, "C'est plus que ce que j'espérais.", "기대했던 것보다 더 많네요."),
(M, "Mais il exige une réponse définitive le quinze, comme convenu.", "하지만 약속대로 15일에 최종 답을 요구해요."),
(L, "Je sais.", "알고 있어요."),
(M, "Vous avez la voix fatiguée, Léa.", "목소리가 피곤하시네요, 레아."),
(L, "Une semaine difficile.", "힘든 한 주였어요."),
(M, "Les décisions importantes se prennent souvent à la fin des semaines difficiles. Ne l'oubliez pas.", "중요한 결정은 종종 힘든 주의 끝에 내려져요. 잊지 마세요."),
(None, "Jeudi 6 novembre. Dix-huit heures. Antoine, pour la première fois depuis une semaine, pousse la porte de La Cave des Abbesses. La boutique est vide. Gaston, dans un fauteuil derrière le comptoir, lit un journal. Il lève les yeux.", "11월 6일 목요일. 저녁 6시. 일주일 만에 처음으로 앙투안이 라 카브 데 자베스 문을 연다. 가게는 비어 있다. 카운터 뒤 안락의자에서 가스통이 신문을 읽다가 눈을 든다."),
(G, "Tiens. L'homme au parapluie.", "여, 우산 든 사람이군."),
(A, "Bonsoir, Gaston.", "안녕, 가스통."),
(G, "Tu as une mine encore pire que la sienne.", "그 사람보다 안색이 더 안 좋네."),
(A, "Elle est venue ?", "그녀가 왔었어?"),
(G, "Mardi. Elle a pleuré dans mes bras, à moitié. Pas complètement. C'est une personne qui pleure avec retenue.", "화요일에. 내 품에서 반쯤 울었지. 완전히는 아니고. 절제하며 우는 사람이야."),
(A, "(la voix tremble) Elle va bien ?", "(목소리가 떨리며) 괜찮대?"),
(G, "Elle va comme quelqu'un qui est tombé et qui n'ose pas encore se relever.", "넘어졌는데 아직 일어날 엄두를 못 내는 사람처럼 지내."),
(A, "J'ai tout gâché, Gaston.", "내가 다 망쳤어, 가스통."),
(G, "Non. Tu as dit des choses que tu regrettes. Ce n'est pas tout gâcher. C'est se tromper. Il y a une différence de dimension.", "아니. 후회할 말을 했을 뿐이야. 다 망친 게 아니라 잘못한 거지. 규모가 달라."),
(A, "Elle ne répond plus. Je lui ai écrit trois fois, je n'ai pas envoyé.", "연락이 없어. 세 번이나 썼지만 보내지 않았어."),
(G, "Ne l'envoie pas encore. Écris-lui plutôt à la main. Une vraie lettre, avec ton vieux stylo.", "아직 보내지 마. 대신 손으로 써. 진짜 편지를, 네 낡은 만년필로."),
(A, "Une lettre ?", "편지?"),
(G, "Tu l'as déjà fait, cet été, non ? C'est ce qui l'a fait revenir. Les mots écrits ont le temps de mûrir avant d'être lus.", "올여름에 이미 했잖아? 그게 그녀를 돌아오게 했지. 쓴 글은 읽히기 전에 익을 시간이 있어."),
(A, "Je ne sais plus quoi dire.", "무슨 말을 해야 할지 모르겠어."),
(G, "Tu as trois mots. Je te les ai donnés tout à l'heure, à travers ma pauvre métaphore de couple. Je ne les répéterai pas.", "세 마디가 있잖아. 조금 전 서툰 커플 은유로 줬어. 다시 말하진 않을 거야."),
(A, "(un temps, puis un sourire douloureux) « Je me suis trompé. »", "(잠시 후 고통스러운 미소로) '내가 틀렸어.'"),
(G, "Tu vois. Tu les connais déjà.", "봐. 이미 알고 있잖아."),
(None, "Vendredi 7 novembre, 10 h. Retour à la salle de classe. Les élèves de seconde sont inhabituellement calmes. Antoine, derrière son bureau, regarde par la fenêtre.", "11월 7일 금요일 오전 10시. 다시 교실이다. 1학년 학생들이 평소와 달리 조용하다. 앙투안이 책상 뒤에서 창밖을 바라본다."),
(E, "Monsieur, vous avez pleuré ?", "선생님, 우셨어요?"),
(A, "Non. J'ai les yeux fatigués.", "아니요. 눈이 피곤할 뿐이에요."),
(F, "Ma tante dit que les gens qui ont les yeux fatigués ont le cœur fatigué.", "이모가 눈이 피곤한 사람은 마음이 피곤한 거라고 해요."),
(A, "Votre tante est une femme sage. Ouvrez vos manuels.", "이모님이 현명하시네요. 교과서 펴세요."),
(E, "Monsieur, vous pouvez nous raconter une histoire d'amour, à la place du cours ? Pour vous consoler ?", "선생님, 수업 대신 사랑 이야기를 들려주실 수 있어요? 위로받으시게요."),
(A, "Une histoire d'amour dans l'histoire de France ?", "프랑스 역사 속 사랑 이야기요?"),
(F, "Napoléon et Joséphine !", "나폴레옹과 조제핀!"),
(A, "Une histoire qui finit mal. Je préfère celle d'Aliénor d'Aquitaine, qui a changé trois fois de royaume et qui n'a jamais perdu sa liberté.", "나쁘게 끝나는 이야기예요. 저는 세 번이나 왕국을 바꿨지만 자유를 잃지 않은 아키텐의 알리에노르 이야기가 더 좋아요."),
(None, "Vendredi 7 novembre. Minuit. Antoine, assis à son bureau, écrit à la lueur d'une petite lampe. Au même instant, à quinze numéros de là, Léa, sur le rebord de sa fenêtre, serre un carnet contre elle. Les deux ne le savent pas.", "11월 7일 금요일. 자정. 앙투안이 책상에 앉아 작은 램프 불빛으로 글을 쓴다. 같은 시각 열다섯 번지 떨어진 곳에서 레아가 창틀에 앉아 노트를 가슴에 안고 있다. 둘은 서로 알지 못한다."),
(A, "(monologue, en écrivant) « Chère Léa. Je ne sais pas comment commencer, alors je commence par le début : je me suis trompé. »", "(쓰면서 독백) '사랑하는 레아. 어떻게 시작해야 할지 몰라 처음부터 시작할게. 내가 틀렸어.'"),
(L, "(monologue, en écrivant) « Antoine. Il y a des mots qu'on ne retire pas. Mais il y a des mots qu'on peut remplacer par d'autres. Je voudrais essayer. »", "(쓰면서 독백) '앙투안. 거두어들일 수 없는 말이 있어. 하지만 다른 말로 바꿀 수 있는 말도 있지. 해 보고 싶어.'"),
(A, "(monologue) « Je t'ai dit que tu fuyais. C'était faux. Tu ne fuis pas : tu cherches. Et moi, je n'ai pas eu le courage de chercher avec toi. »", "(독백) '네가 도망친다고 했지. 틀린 말이었어. 넌 도망치지 않고 찾고 있어. 나는 너와 함께 찾을 용기가 없었어.'"),
(L, "(monologue) « Je t'ai dit que tu t'accrochais à ta mère. C'était cruel. Tu ne t'accroches pas : tu honores. Et j'ai confondu ton amour avec une peur. »", "(독백) '네가 어머니에게 매달린다고 했지. 잔인했어. 넌 매달리는 게 아니라 기리는 거야. 그리고 난 네 사랑을 두려움과 혼동했어.'"),
(None, "Les deux lettres restent inachevées. À l'aube, l'un et l'autre s'endorment, la tête sur les bras, au milieu de leurs feuilles. Dehors, la pluie fine du matin commence à tomber sur Montmartre.", "두 편지는 미완성으로 남는다. 새벽에 둘 다 팔에 머리를 대고 종이 사이에서 잠든다. 밖에서는 아침의 가랑비가 몽마르트르 위로 내리기 시작한다."),
]
VOCAB = [
("A2","un cimetière / une tombe / un chrysanthème","묘지 / 무덤 / 국화","11월 초 프랑스 풍경"),
("A2","la Toussaint","만성절(11월 1일)","프랑스의 공휴일. 묘지를 찾아 국화를 올림"),
("A2","un manteau / une lampe / une mine épouvantable","코트 / 램프 / 끔찍한 안색","안색을 말하는 표현"),
("B1","se disputer / se quereller","다투다 / 말다툼하다","어머니의 말에서 인용된 동사"),
("B1","une récréation / la salle des professeurs","쉬는 시간 / 교무실","학교 장면"),
("B1","célibataire","독신인","« Voilà pourquoi je suis célibataire. »"),
("B1","retenue / avec retenue","절제 / 절제하며","« Elle pleure avec retenue. »"),
("B1","gâcher / se tromper","망치다 / 틀리다","« Tu n'as pas tout gâché. Tu t'es trompé. »"),
("B1","à reculons","뒷걸음질로","« On revient en marchant, parfois à reculons. »"),
("B2","recueillement","경건한 묵상","만성절의 분위기"),
("B2","à haute voix / un monologue","소리 내어 / 독백","« monologue, à haute voix »"),
("B2","honorer / s'accrocher à","기리다 / 매달리다","« Tu ne t'accroches pas : tu honores. »"),
("B2","un stylo rouge / corriger des copies","빨간 펜 / 시험지를 채점하다","교사의 일상"),
("B2","mûrir","익다, 숙성되다","« Les mots écrits ont le temps de mûrir. »"),
("B2","l'inverse / le contraire","반대","« Ou l'inverse. »"),
("B2","avouer / refuser d'avouer","인정하다 / 인정하기를 거부하다","« ce que ma tête refuse d'avouer »"),
("C1","Peut-être aurait-il fallu que…","~했어야 했을지도 모른다","도치 + 조건법 과거 + 접속법"),
("C1","Que n'ai-je dit autre chose ?","왜 다른 말을 하지 못했을까?","문어체 도치 의문. 후회를 표현"),
("C1","d'une simplicité insultante","모욕적일 만큼 단순한","형용사 + 부사 강조"),
("C1","le seuil / sur le seuil","문턱 / 문턱에서","« les mots qu'on n'a pas dits restent sur le seuil »"),
("C1","une différence de dimension","규모의 차이","가스통의 표현"),
("C1","à la lueur d'une lampe","램프 불빛에","문학적 표현"),
("C1","tout craché / tel quel","영락없이 / 있는 그대로","대화에서 자주 쓰는 구어체"),
("C1","retirer un mot / remplacer un mot","말을 거두다 / 말을 바꾸다","« Il y a des mots qu'on ne retire pas. »"),
]
GRAM = [
("B1","현재와 과거의 독백: 복합과거와 현재",
 "« Il l'a dit. Il l'a vraiment dit. » « Je ne sais pas pourquoi je suis venue ici. » 독백에서 복합과거는 최근 사건을, 현재형은 지금의 감정을 나타낸다."),
("B2","도치(Inversion): Peut-être aurait-il fallu… / Sans doute avait-il raison",
 "« Peut-être aurait-il fallu que je me taise. » peut-être / sans doute / aussi / ainsi 등 문두 부사 뒤에서는 주어-동사 도치가 가능하다. 문어체의 전형."),
("B2","il aurait fallu que + 접속법 대과거 / 접속법 현재",
 "« Il aurait fallu qu'il parle. » il aurait fallu que + 접속법 = ~했어야 했다. 후회의 문장은 « J'aurais dû parler. » 와 의미가 같지만 문체가 다르다."),
("B2","간접 인용: 어머니가 늘 하는 말",
 "« Maman dit toujours : « Les gens se querellent parce qu'ils s'aiment trop pour se séparer. » » 격언·훈계는 현재형으로 인용. trop pour + 부정사 = ~하기에는 너무 ~하다."),
("B2","의문 부정: N'a-t-il pas ? / Que n'ai-je dit ?",
 "« Que n'ai-je dit autre chose ? » que ne + 동사 + 주어 = 왜 ~하지 않았을까(후회·탄식). 문어체와 시적 어조에서 쓰인다."),
("C1","현재분사와 제롱디프의 차이",
 "« Elle dessine en pleurant. » (제롱디프, 동시 동작) « Une femme pleurant sur un banc. » (현재분사, 명사 수식) 주어가 같을 때 제롱디프, 명사를 꾸밀 때 현재분사."),
("C1","si의 비현실: Si c'est fait pour revenir, ça revient",
 "« Si c'est fait pour revenir, ça revient. » si + 현재, 현재(일반 진리). 속담·격언에서 가정 + 결과를 현재형으로 쓰는 구문."),
("C1","전치사 à force de / à mesure que",
 "« À mesure que le jour se lève, les doutes se dissipent. » à mesure que + 직설법 = ~함에 따라. 점진적 변화의 서술."),
]
CULTURE = [
("la Toussaint: 프랑스의 11월 1~2일",
 "만성절(Toussaint)은 11월 1일 공휴일이다. 프랑스 사람들은 이날 묘지를 찾아 가족 무덤에 국화(chrysanthème)를 놓는다. 국화는 죽은 이를 위한 꽃이라 연인에게 선물하면 안 된다는 속설이 있다."),
("몽마르트르 묘지와 페르 라셰즈",
 "파리의 대표 묘지로 몽마르트르 묘지(에밀 졸라, 드가, 트뤼포 등)와 페르 라셰즈(쇼팽, 오스카 와일드, 짐 모리슨 등)가 있다. 관광객이 산책하러 오기도 하는 열린 공간이다."),
("프랑스의 '편지의 힘'",
 "프랑스 문화에서는 큰 감정을 전할 때 손편지를 중시한다. 문어체의 도치·접속법 과거·조건법 과거가 풍부하게 쓰이며, 이 화는 구어와 문어의 차이를 학습하기 좋은 에피소드다."),
]
META = dict(part=3, ep=31, part_label="제3부 늦수확 · Vendanges tardives", title_fr="Le silence", title_ko="침묵",
 place="몽마르트르와 뒤랑탱 거리 · 11월 1일~7일 (일주일)",
 chars="Léa · Antoine · Hugo · Gaston · Hélène Rousseau (동료 교사)",
 wine="(주제) 와인 없는 한 주 — 기억과 후회",
 focus="문어체 도치, 조건법 과거와 접속법 과거, 독백체, 후회·반성 표현, 문학적 어휘",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제32화 « Margaux a son mot à dire » : 앙투안의 여동생 마르고가 파리에 도착한다. 직설적인 조언과 구어체 프랑스어가 쏟아진다.")
