# -*- coding: utf-8 -*-
A, M, L, G = "Antoine", "Margaux", "Léa", "Gaston"
D = [
(None, "Samedi 8 novembre, 11 h. Gare d'Austerlitz. Antoine, les mains dans les poches, attend sur le quai. Un train en provenance de Saumur entre en gare. Les portes s'ouvrent. Une jeune femme blonde, un sac de voyage sur l'épaule et une valise à roulettes, descend en regardant autour d'elle.", "11월 8일 토요일 오전 11시. 오스테를리츠역. 앙투안이 주머니에 손을 넣고 승강장에서 기다린다. 소뮈르발 열차가 역에 들어온다. 문이 열린다. 어깨에 여행 가방을 메고 바퀴 달린 가방을 끈 금발 여성이 주위를 둘러보며 내린다."),
(M, "Antoine ! Tu es là ! Je croyais que tu allais oublier.", "앙투안! 왔구나! 잊을 줄 알았어."),
(A, "Je n'oublie jamais. Bonjour, Margaux.", "난 절대 안 잊어. 안녕, 마르고."),
(M, "(l'embrasse) Salut, petit frère. Oh là là. Tu as une tête. Tu dors ?", "(그를 안으며) 안녕, 동생. 세상에. 얼굴이 말이 아니네. 잠은 자니?"),
(A, "Moyennement.", "그럭저럭."),
(M, "Moyennement, ça veut dire non. Papa m'a dit que tu étais bizarre au téléphone. Et que Léa ne répondait plus à Hugo. Donc je suis venue.", "그럭저럭이면 못 잔다는 뜻이지. 아빠가 전화 목소리가 이상하다고 하셨어. 그리고 레아가 위고에게 연락을 안 한다고. 그래서 왔어."),
(A, "Tu n'avais pas besoin de venir.", "올 필요 없었는데."),
(M, "Si. Quand mon petit frère déprime, j'ai besoin de venir. C'est écrit dans le règlement de la famille.", "있었어. 동생이 우울하면 와야 해. 가족 규칙에 쓰여 있거든."),
(A, "Il n'y a pas de règlement.", "그런 규칙은 없어."),
(M, "Il y en a un. Je l'ai écrit moi-même, à treize ans. Allez, prends ma valise, je te raconte tout en marchant.", "있어. 열세 살 때 내가 직접 썼어. 자, 내 가방 들어, 걸으면서 얘기해 줄게."),
(None, "Ils sortent de la gare et traversent la Seine par le pont d'Austerlitz. Le ciel est gris, la rivière brune, mais Margaux marche d'un pas rapide, le menton levé.", "두 사람이 역을 나와 오스테를리츠 다리를 건너 센강을 건넌다. 하늘은 회색이고 강물은 갈색이지만 마르고는 턱을 치켜들고 빠른 걸음으로 걷는다."),
(M, "Bon. Raconte-moi tout. Dans l'ordre. Sans enjoliver.", "자. 전부 얘기해 봐. 순서대로. 꾸미지 말고."),
(A, "Il n'y a pas grand-chose à dire. Nous nous sommes disputés. Elle est partie. C'était il y a neuf jours.", "할 얘기가 많지 않아. 다퉜어. 그녀가 떠났어. 구 일 전이야."),
(M, "Neuf jours sans un coup de fil ?", "구 일 동안 전화 한 통 없이?"),
(A, "Nous nous sommes dit des choses que... qu'on ne peut pas retirer.", "우린 되돌릴 수 없는 말들을 했어."),
(M, "Quelles choses ?", "어떤 말?"),
(A, "Elle a dit que je m'accrochais à maman. Que je vivais dans le passé.", "그녀가 내가 엄마에게 매달린다고 했어. 과거에 산다고."),
(M, "(s'arrête net) Elle a dit ça ?", "(딱 멈춰 서며) 그렇게 말했어?"),
(A, "Oui.", "응."),
(M, "Et tu as répondu quoi ?", "그래서 넌 뭐라고 대답했어?"),
(A, "Que... qu'elle fuyait. Que c'était ce qu'elle savait faire de mieux.", "그녀가 도망친다고. 그게 제일 잘하는 일이라고."),
(M, "(un temps, puis secoue la tête) Eh ben, vous ne vous êtes pas ratés.", "(잠시 후 고개를 저으며) 와, 둘 다 제대로 했네."),
(A, "Je sais.", "알아."),
(M, "Ce n'est pas un reproche. C'est un constat. Vous êtes aussi têtus l'un que l'autre, et aussi sensibles. Un cocktail explosif.", "탓하는 게 아니야. 확인하는 거지. 둘은 똑같이 고집 세고 똑같이 예민해. 폭발적인 조합이야."),
(A, "Merci pour ton soutien.", "응원 고마워."),
(M, "Je te soutiens. Je te dis juste que tu as été con.", "응원해. 그냥 네가 멍청했다고 말하는 거야."),
(A, "(un sourire involontaire) Merci, Margaux.", "(저도 모르게 미소 지으며) 고마워, 마르고."),
(M, "Elle aussi a été conne. Mais ce n'est pas elle que j'ai sous la main, alors je m'occupe de toi.", "그녀도 멍청했어. 하지만 내 손에 있는 건 그녀가 아니니까 너를 챙기는 거야."),
(None, "Ils arrivent à un café de la place d'Italie. Margaux choisit une table en terrasse, commande deux cafés et une tarte aux pommes.", "두 사람이 이탈리아 광장의 카페에 도착한다. 마르고가 테라스 테이블을 고르고 커피 두 잔과 사과 타르트를 주문한다."),
(M, "Alors voilà. Je vais te donner mon avis. Tu n'es pas obligé de le suivre, mais tu es obligé de l'écouter.", "자 그럼. 내 의견을 말해 줄게. 따를 필요는 없지만 들어야 해."),
(A, "J'ai le choix ?", "내게 선택권이 있어?"),
(M, "Non. Premièrement : tu es amoureux d'elle, point.", "없어. 첫째, 넌 그녀를 사랑해, 이상."),
(A, "Oui.", "응."),
(M, "Deuxièmement : elle est amoureuse de toi, point.", "둘째, 그녀도 너를 사랑해, 이상."),
(A, "Je pense que oui.", "그렇게 생각해."),
(M, "Troisièmement : vous avez peur tous les deux. Peur de perdre l'autre, peur de ne pas être à la hauteur, peur d'être un fardeau.", "셋째, 둘 다 두려워해. 상대를 잃을까 봐, 기대에 못 미칠까 봐, 짐이 될까 봐."),
(A, "(un temps) Oui.", "(잠시 후) 응."),
(M, "Quatrièmement, et c'est le plus important : la peur, ça ne se règle pas avec des mots, ça se règle avec des actes.", "넷째, 이게 가장 중요해. 두려움은 말로 해결되는 게 아니라 행동으로 해결돼."),
(A, "Quels actes ?", "어떤 행동?"),
(M, "Je ne sais pas. À toi de les trouver. Mais je sais ce qu'il ne faut pas faire : attendre qu'elle t'appelle.", "모르겠어. 네가 찾아야 해. 하지만 하지 말아야 할 건 알아. 그녀가 전화하기를 기다리지 마."),
(A, "Je lui ai écrit trois fois.", "세 번 썼어."),
(M, "Et envoyé ?", "그리고 보냈어?"),
(A, "Non.", "아니."),
(M, "Alors tu ne lui as pas écrit. Tu t'es écrit à toi-même.", "그럼 그녀에게 쓴 게 아니야. 너 자신에게 쓴 거지."),
(A, "Tu as raison.", "네 말이 맞아."),
(M, "J'ai toujours raison. C'est mon métier, je suis avocate.", "난 늘 맞아. 내 직업이야, 변호사니까."),
(A, "Tu défends les gens qui ont tort.", "넌 잘못한 사람들을 변호하잖아."),
(M, "Je défends les gens qui ont besoin d'être défendus. C'est différent. Toi, tu as besoin d'être défendu. Contre toi-même.", "변호가 필요한 사람들을 변호하는 거야. 달라. 너는 변호가 필요해. 너 자신에 맞서서."),
(A, "(sourit) Quelle avocate.", "(미소 지으며) 대단한 변호사네."),
(M, "Cinquièmement : papa.", "다섯째, 아빠."),
(A, "Papa ?", "아빠?"),
(M, "Papa a besoin de réponses. Sur le domaine. Sur Julien. Sur toi. Il tourne en rond dans la cuisine, il parle tout seul, il ressemble à un lion en cage.", "아빠는 대답이 필요하셔. 농장, 쥘리앵, 너에 대해. 부엌에서 빙빙 돌고 혼자 말씀하시고 우리에 갇힌 사자 같아."),
(A, "Je sais. Je dois lui répondre avant Noël.", "알아. 크리스마스 전에 대답해야 해."),
(M, "Non. Avant la fin du mois. Il m'a dit qu'il devait prévenir le notaire.", "아니. 이달 말 전에. 공증인에게 알려야 한다고 말씀하셨어."),
(A, "Avant la fin du mois ?", "이달 말 전에?"),
(M, "Il veut que tout soit réglé avant que la neige tombe sur la Loire. Tu connais papa.", "루아르에 눈이 오기 전에 모든 게 정리되길 원하셔. 아빠 알잖아."),
(A, "Je ne peux pas répondre avant de savoir ce que Léa décide.", "레아가 뭘 결정하는지 알기 전에는 대답할 수 없어."),
(M, "(pose sa fourchette) Antoine. Écoute-moi bien. C'est précisément cette phrase qui t'a mis dans le pétrin.", "(포크를 내려놓으며) 앙투안. 잘 들어. 바로 그 말이 널 곤경에 빠뜨렸어."),
(A, "Quoi ?", "뭐?"),
(M, "« Je ne peux pas répondre avant de savoir ce que Léa décide. » Tu mets ta vie entre ses mains. Elle fait pareil avec toi. Vous êtes deux personnes qui attendent que l'autre décide pour ne pas avoir à porter la responsabilité de sa propre décision.", "'레아가 뭘 결정하는지 알기 전에는 대답할 수 없어.' 넌 네 삶을 그녀 손에 맡기고 있어. 그녀도 너에게 똑같이 해. 둘 다 자기 결정의 책임을 지지 않으려고 상대가 먼저 결정하길 기다리고 있어."),
(A, "(un long silence) Je n'avais jamais vu ça comme ça.", "(긴 침묵) 그렇게 본 적이 없었어."),
(M, "Parce que tu es dedans. Moi, je suis dehors.", "네가 안에 있으니까. 난 밖에 있잖아."),
(A, "Et qu'est-ce que je dois faire, alors ?", "그럼 난 어떻게 해야 해?"),
(M, "Décide pour toi. D'abord. Sans elle, sans papa, sans Julien. Décide ce que tu veux. Ensuite seulement, tu lui dis.", "먼저 너를 위해 결정해. 그녀 없이, 아빠 없이, 쥘리앵 없이. 네가 원하는 걸 정해. 그다음에야 그녀에게 말해."),
(A, "Ça, c'est ce qu'elle me reproche : avoir décidé sans elle.", "그게 바로 그녀가 나를 탓하는 거야. 그녀 없이 결정했다고."),
(M, "Non. Elle te reproche de ne pas lui avoir dit. Il y a une différence. Décider seul, ce n'est pas un crime. Décider dans le dos de quelqu'un, si.", "아니야. 그녀는 말하지 않은 걸 탓해. 차이가 있어. 혼자 결정하는 건 죄가 아니야. 누군가의 등 뒤에서 결정하는 건 죄지."),
(A, "(lentement) Décider seul, puis le dire.", "(천천히) 혼자 결정하고, 그다음에 말하기."),
(M, "Décider seul, puis le dire. C'est ce qu'on appelle être adulte.", "혼자 결정하고, 그다음에 말하기. 그게 어른이 된다는 거야."),
(A, "Tu es sûre que tu n'es pas psychologue ?", "정말 심리학자가 아닌 거 맞아?"),
(M, "Je suis ta sœur. C'est pire.", "난 네 누나야. 더 심해."),
(A, "Elle va me haïr.", "그녀가 날 싫어하게 될 거야."),
(M, "Elle ne te haïra pas. Elle sera en colère. Ce sont deux choses différentes.", "싫어하지 않을 거야. 화는 나겠지. 둘은 다른 거야."),
(A, "Et si elle part à Bordeaux ?", "그리고 그녀가 보르도로 떠나면?"),
(M, "Alors tu iras à Bordeaux. Ou elle viendra à Saumur. Ou vous vous retrouverez à mi-chemin, à Poitiers, dans une chambre d'hôtel sinistre.", "그럼 네가 보르도에 가면 돼. 아니면 그녀가 소뮈르에 오거나. 아니면 중간 지점인 푸아티에의 음침한 호텔 방에서 만나든가."),
(A, "(rit) Poitiers.", "(웃으며) 푸아티에."),
(M, "Je plaisante. Mais ce n'est pas faux : il y a toujours une solution quand on se déplace tous les deux un peu.", "농담이야. 하지만 틀린 말도 아니야. 둘이 조금씩 움직이면 늘 해결책이 있지."),
(A, "À mi-chemin.", "중간 지점."),
(M, "Exactement. Les couples qui durent sont ceux qui apprennent à se retrouver à mi-chemin.", "맞아. 오래가는 커플은 중간에서 만나는 법을 배운 사람들이야."),
(None, "Le garçon pose deux cafés et une tarte aux pommes sur la table. Margaux coupe la tarte en deux parts égales et fait glisser l'une des assiettes devant son frère.", "종업원이 커피 두 잔과 사과 타르트를 테이블에 놓는다. 마르고가 타르트를 똑같은 크기로 둘로 자르고 접시 하나를 동생 앞으로 민다."),
(M, "Mange. Un homme qui a le ventre vide prend de mauvaises décisions.", "먹어. 배가 비면 나쁜 결정을 해."),
(A, "Gaston dit la même chose.", "가스통도 같은 말을 해."),
(M, "Gaston ? Le caviste ? C'est un homme sage.", "가스통? 와인 가게 주인? 현명한 분이야."),
(A, "Tu le connais ?", "그분을 알아?"),
(M, "Papa m'en a parlé. Il lui a envoyé une bouteille de Clos des Roches, l'année dernière, pour le remercier de m'avoir envoyé des clients. Papa n'oublie jamais ses amis.", "아빠가 얘기하셨어. 작년에 손님들을 보내 줘서 고맙다고 클로 데 로슈 한 병을 보냈대. 아빠는 친구를 절대 잊지 않으셔."),
(A, "Je ne le savais pas.", "몰랐어."),
(M, "Il y a plein de choses que tu ne sais pas, petit frère. Allez, finis ton café. Je veux voir Montmartre.", "모르는 게 많아, 동생. 자, 커피 마저 마셔. 몽마르트르를 보고 싶어."),
(None, "Plus tard, dans la rue des Abbesses. Margaux et Antoine remontent la rue, bras dessus bras dessous. La lumière d'un après-midi de novembre, basse et dorée, éclaire les façades de pierre.", "잠시 후 아베스 거리. 마르고와 앙투안이 팔짱을 끼고 거리를 올라간다. 낮고 금빛인 11월 오후의 햇살이 석조 건물 외벽을 비춘다."),
(M, "C'est joli, ici. Je comprends pourquoi tu n'es jamais parti.", "여기 예쁘네. 네가 왜 한 번도 안 떠났는지 이해돼."),
(A, "Tu comprends, toi ?", "넌 이해해?"),
(M, "Je comprends que tu aies envie de rester dans un endroit qui te ressemble. Mais je comprends aussi pourquoi Léa a besoin de partir : elle cherche un endroit qui lui ressemble encore.", "너와 닮은 곳에 머물고 싶어 하는 건 이해해. 하지만 레아가 떠나야 하는 이유도 이해해. 그녀는 자신과 닮은 곳을 아직 찾고 있는 거야."),
(A, "Tu parles comme papa.", "아빠처럼 말하네."),
(M, "Je parle comme maman. Elle disait toujours que les gens ne sont pas faits pour des lieux : ce sont les lieux qui sont faits pour les gens.", "엄마처럼 말하는 거야. 엄마는 늘 사람이 장소를 위해 만들어진 게 아니라 장소가 사람을 위해 만들어졌다고 하셨어."),
(A, "(un temps, ému) Elle disait ça ?", "(잠시 후 감동하여) 엄마가 그렇게 말씀하셨어?"),
(M, "Souvent. Tu étais trop petit pour t'en souvenir.", "자주. 넌 기억하기엔 너무 어렸어."),
(A, "Je me souviens de peu de choses d'elle. Surtout de sa voix.", "엄마에 대해 기억나는 게 적어. 특히 목소리가."),
(M, "Elle avait une voix magnifique. Rauque, un peu cassée. On l'entendait chanter à travers les murs.", "목소리가 정말 아름다웠지. 쉰 듯하고 약간 갈라진. 벽 너머로도 노래가 들렸어."),
(A, "Je l'ai entendue dans la cabane, une nuit. J'avais treize ans. Dans mon rêve, elle chantait.", "어느 밤 오두막에서 들었어. 열세 살이었는데 꿈속에서 엄마가 노래하고 계셨어."),
(M, "(lui serre le bras) C'était sûrement elle.", "(그의 팔을 꽉 잡으며) 분명히 엄마였을 거야."),
(None, "Ils arrivent devant La Cave des Abbesses. La vitrine est éclairée. Gaston, derrière le comptoir, lève les yeux et les voit. Il sourit et agite la main.", "라 카브 데 자베스 앞에 도착한다. 진열창에 불이 켜져 있다. 카운터 뒤 가스통이 눈을 들어 그들을 본다. 미소를 지으며 손을 흔든다."),
(A, "Il sait tout. Et il dit presque rien.", "모든 걸 알아. 그리고 거의 아무 말도 안 해."),
(M, "Alors allons lui parler. Je veux l'interroger sur la soirée où tu as rencontré Léa. Papa m'a dit qu'il y avait un Morgon.", "그럼 얘기하러 가자. 네가 레아를 만난 날 밤에 대해 물어보고 싶어. 아빠가 모르공이 있었다고 하셨어."),
(A, "Margaux...", "마르고..."),
(M, "Quoi ? C'est mon enquête. Je suis avocate. Je reconstitue les faits.", "뭐? 내 조사야. 변호사잖아. 사실을 재구성하는 거지."),
(None, "Elle ouvre la porte de la boutique. La cloche tinte. Gaston, les bras ouverts, s'avance vers eux.", "그녀가 가게 문을 연다. 종이 울린다. 가스통이 두 팔을 벌리고 그들에게 다가온다."),
(G, "Mademoiselle Delcourt, je présume ? Vous avez les yeux de votre père et le menton de votre frère. Entrez, entrez : on dit que vous êtes terrible.", "델쿠르 양 맞죠? 아버님 눈에 오라버니 턱이군요. 들어오세요. 무서운 분이라고들 하더군요."),
(M, "(rit) Qui l'a dit ?", "(웃으며) 누가 그래요?"),
(G, "Votre frère, par omission.", "남동생이요, 말하지 않음으로써."),
]
VOCAB = [
("A2","une valise à roulettes / un sac de voyage","바퀴 달린 가방 / 여행 가방","여행 어휘"),
("A2","un frère / une sœur / un petit frère","형제 / 자매 / 남동생","가족 호칭"),
("A2","une tarte aux pommes / un café","사과 타르트 / 커피","카페 주문"),
("B1","déprimer / être bizarre","우울하다 / 이상하다","« Quand mon petit frère déprime… »"),
("B1","moyennement","그럭저럭","« Moyennement, ça veut dire non. »"),
("B1","têtu / sensible","고집 센 / 예민한","두 사람의 성격"),
("B1","un règlement","규칙","농담조 « le règlement de la famille »"),
("B1","être con / être conne","멍청하다","속어. 가까운 사이에서 쓰는 거친 표현"),
("B1","tourner en rond","빙빙 돌다","30화 복습"),
("B2","enjoliver / sans enjoliver","꾸미다 / 꾸미지 않고","« Sans enjoliver. » 사실대로"),
("B2","un cocktail explosif","폭발적인 조합","비유 표현"),
("B2","le pétrin","곤경","« t'a mis dans le pétrin » 구어"),
("B2","à la hauteur / un fardeau","기대에 부합하는 / 짐","« ne pas être à la hauteur »"),
("B2","une avocate / un notaire","여자 변호사 / 공증인","직업 어휘"),
("B2","bras dessus bras dessous","팔짱을 끼고","친근한 걸음 묘사"),
("B2","mi-chemin / à mi-chemin","중간 / 중간 지점에서","« se retrouver à mi-chemin »"),
("B2","reconstituer les faits","사실을 재구성하다","변호사의 수사 용어"),
("C1","Il parle comme un lion en cage.","우리에 갇힌 사자처럼 말하다/행동하다","초조한 상태를 비유"),
("C1","mettre sa vie entre les mains de quelqu'un","자기 삶을 누군가의 손에 맡기다","의존의 은유"),
("C1","porter la responsabilité de sa propre décision","자기 결정의 책임을 지다","논증에서 쓰이는 문장"),
("C1","Je suis ta sœur. C'est pire.","난 네 누나야. 더 심해.","애정 섞인 직설. 가족 대화의 유머"),
("C1","par omission","생략을 통해","법률·일상에서 쓰는 표현"),
("C1","le menton de votre frère","오라버니의 턱","닮은 외모를 칭찬하는 말투"),
("C1","je présume","~일 것 같아요","추정을 정중하게 말할 때"),
]
GRAM = [
("B1","구어체 축약과 생략: ne의 탈락, c'est vs il est",
 "« Tu n'es pas obligé » → « T'es pas obligé » 구어에서는 ne를 생략한다. « Elle a été conne. » 속어 + 친근한 말투. 가족 사이의 대화는 문어체보다 짧고 직설적이다."),
("B1","서수 열거: premièrement / deuxièmement / enfin",
 "« Premièrement : tu es amoureux d'elle. Deuxièmement : elle est amoureuse de toi. » 논점을 정리할 때 쓰는 서수 부사. d'abord / ensuite / enfin도 흔히 쓰인다."),
("B2","접속법: j'ai besoin que / il faut que / avant que",
 "« Il veut que tout soit réglé avant que la neige tombe. » avant que + 접속법(tombe). « Il faut que tu décides. » 시간·필요 표현의 접속법."),
("B2","관계절과 선행사: ce qui / ce que / ce dont",
 "« Ce qui est important, c'est… » « Ce que je veux… » « Ce dont j'ai besoin… » 선행사가 문장 전체인 관계대명사. 문장 앞머리에서 주어를 만들 때 유용."),
("B2","명령법 + 대명사: Mange. / Laisse-moi finir.",
 "« Mange. » « Finis ton café. » « Prends ma valise. » 가족 사이의 짧은 명령. 친근한 명령법은 -s를 생략하는 -er 동사에 주의."),
("C1","ne ... pas ... mais ...: 대조 구조",
 "« Ce n'est pas un reproche. C'est un constat. » « Elle te reproche de ne pas lui avoir dit. » 부정으로 앞 가정을 부정하고 정정하는 구문. 31화 « Ce n'est pas de l'amabilité. C'est de l'expertise. » 복습."),
("C1","si의 일반 가정과 평서",
 "« Si je ne t'écris pas, je ne te le dis pas. » 구어에서 si 문장이 습관·일반 진리로 쓰인다. 문어체와 혼동하지 말 것."),
("C1","je présume / je suppose / il paraît",
 "« Mademoiselle Delcourt, je présume ? » présumer = 추정하다. 격식 있는 추측 표현. « Je suppose que… » « Il paraît que… » 소문·추정 표현과 비교."),
]
CULTURE = [
("프랑스에서의 'avocat'(변호사)",
 "프랑스 변호사는 법정 변호와 상담을 함께 하며 가족·상속·부동산 분쟁도 맡는다. 마르고가 가족 문제를 '변호'하듯 푸는 것은 직업적 말투를 일상에 옮긴 유머다."),
("프랑스의 가족 모임과 'règlement de la famille'",
 "프랑스 가족은 감정 표현이 직설적이다. 누나가 동생에게 'Tu as été con'이라고 말하는 건 친밀함의 표현이다. 속어 'con(ne)'은 가까운 사이에서만 쓰는 거친 말이니 학습자는 조심해야 한다."),
("파리의 오스테를리츠역과 이탈리아 광장",
 "오스테를리츠역은 파리 남동쪽 13구에 있으며 루아르 지방행 열차(오를레앙, 투르 방면)의 출발역이다. 이탈리아 광장(place d'Italie)은 13구 중심 광장으로 여러 카페가 모인 지역이다."),
]
META = dict(part=3, ep=32, part_label="제3부 늦수확 · Vendanges tardives", title_fr="Margaux a son mot à dire", title_ko="마르고의 한마디",
 place="파리 오스테를리츠역 → 이탈리아 광장 카페 → 아베스 거리 · 11월 8일 토요일 11시",
 chars="Antoine · Margaux (마르고, 앙투안의 여동생, 변호사) · Gaston",
 wine="(와인 없음) 카페와 타르트 — 가스통의 가게 앞에서 끝",
 focus="구어체 조언, 열거 표현, 접속법(avant que), 직설 화법, 가족 간 대화",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제33화 « Millésime 1998 » : 가스통이 가장 아끼던 1998년 와인을 연다. 한 병이 불러낸 지난날의 이야기와 대과거.")
