# -*- coding: utf-8 -*-
L, A, T = "Léa", "Antoine", "La lettre"
D = [
(None, "Jeudi 13 novembre, 9 h. Dans le studio de Léa. Une lumière pâle de fin d'automne entre par la fenêtre. Sur la table basse, deux tasses de café, un paquet de croissants vide. Antoine est venu tôt, avant d'aller au lycée. C'est la première fois qu'il revient chez elle depuis la dispute.", "11월 13일 목요일 오전 9시. 레아의 원룸. 늦가을의 옅은 빛이 창으로 들어온다. 탁자 위에는 커피 두 잔과 빈 크루아상 봉지. 앙투안이 학교 가기 전에 일찍 왔다. 말다툼 이후 처음 그녀의 집을 다시 찾았다."),
(A, "Je n'ai que vingt minutes. J'ai un cours de première à dix heures. Mais je voulais te voir avant.", "이십 분밖에 없어. 10시에 2학년 수업이 있어. 하지만 그 전에 널 보고 싶었어."),
(L, "Gaston m'a bouleversée, mardi.", "화요일에 가스통이 날 뒤흔들었어."),
(A, "Moi aussi. J'ai pensé à lui toute la nuit.", "나도. 밤새 그분 생각을 했어."),
(L, "Il a dit : « Ne gardez pas les mots pour demain. »", "'말을 내일로 아껴 두지 마'라고 했지."),
(A, "Et pourtant, aujourd'hui, nous avons du mal à les dire.", "그런데도 오늘 우린 그 말을 하기 힘들어해."),
(L, "On les dira. Doucement.", "말할 거야. 천천히."),
(A, "Tu as mangé quelque chose, ce matin ?", "오늘 아침에 뭐 먹었어?"),
(L, "Un demi-croissant. Je n'arrive plus à manger.", "크루아상 반 개. 더는 못 먹겠어."),
(A, "Moi non plus. Gaston dit qu'un homme à jeun prend de mauvaises décisions.", "나도. 가스통이 굶은 사람은 나쁜 결정을 한다고 하지."),
(L, "Gaston dit beaucoup de choses.", "가스통은 많은 말을 해."),
(A, "Presque toutes vraies.", "거의 다 맞는 말이야."),
(L, "C'est ça, le problème.", "그게 문제야."),
(L, "Tu aurais pu m'écrire.", "문자 보낼 수도 있었잖아."),
(A, "J'ai écrit. Trois fois. Je n'ai pas envoyé.", "썼어. 세 번. 보내지 않았어."),
(L, "Moi, j'ai écrit aussi. Plus de trois fois.", "나도 썼어. 세 번보다 많이."),
(A, "Elles sont où, tes lettres ?", "네 편지들은 어디 있어?"),
(L, "Dans la poubelle, pour la plupart. Une est restée sur mon bureau. Je ne sais pas pourquoi je ne l'ai pas jetée.", "대부분 쓰레기통에. 하나는 책상에 남았어. 왜 안 버렸는지 모르겠어."),
(A, "Je pourrais la lire ?", "읽어 봐도 될까?"),
(L, "(hésite, puis secoue la tête) Pas encore. Elle a été écrite dans un moment où je n'allais pas bien. Je préférerais que tu lises celle que je t'écrirai plus tard.", "(망설이다 고개를 저으며) 아직은 아니야. 내가 괜찮지 않을 때 쓴 거야. 나중에 쓸 편지를 네가 읽었으면 해."),
(A, "D'accord. Je ne veux rien forcer.", "알았어. 억지로 하고 싶지 않아."),
(L, "Merci. Je descends chercher du pain à la boulangerie. Tu veux que je rapporte quelque chose ?", "고마워. 빵집에 빵 사러 내려갈게. 뭐 사 올까?"),
(A, "Une baguette tradition, s'il te plaît.", "바게트 트라디시옹 하나."),
(L, "Je reviens dans dix minutes.", "십 분 뒤에 올게."),
(None, "Elle enfile son manteau, prend son sac, et sort. La porte se referme. Antoine reste seul dans le petit studio. Il se lève, marche jusqu'à la fenêtre, regarde la rue. Puis, malgré lui, son regard se pose sur le bureau.", "그녀가 코트를 입고 가방을 들고 나간다. 문이 닫힌다. 앙투안이 작은 원룸에 홀로 남는다. 그가 일어나 창가로 가서 거리를 내려다본다. 그러다 자기도 모르게 시선이 책상 쪽으로 향한다."),
(A, "(à lui-même) Ne regarde pas. Ne regarde pas.", "(혼잣말) 보지 마. 보지 마."),
(None, "Sur le bureau, parmi les feuilles de croquis, une enveloppe blanche, non cachetée, avec un seul mot écrit à l'encre bleue : « Antoine ». Il la regarde longtemps.", "책상 위 스케치 종이들 사이에 봉하지 않은 흰 봉투가 놓여 있다. 푸른 잉크로 쓴 한 단어, '앙투안'. 그가 한참 바라본다."),
(A, "(à lui-même) C'est pour moi. Elle l'a écrite pour moi. Je ne fais rien de mal, si je la lis.", "(혼잣말) 나한테 쓴 거야. 나를 위해 쓴 편지야. 읽는다고 해서 잘못은 아니야."),
(None, "Il ouvre l'enveloppe. Il en sort une feuille pliée en quatre. Il déplie le papier. La lettre est écrite d'une écriture ronde, fine, un peu tremblante.", "그가 봉투를 열어 네 겹으로 접은 종이를 꺼낸다. 종이를 편다. 편지는 둥글고 가는, 약간 떨리는 글씨로 쓰여 있다."),
(T, "« Antoine, c'est le 7 novembre, il est minuit. Je n'arrive pas à dormir. Je t'écris parce que je ne sais pas te parler. »", "'앙투안, 11월 7일 자정이야. 잠이 오지 않아. 너와 이야기할 줄 몰라서 편지를 쓰고 있어.'"),
(T, "« J'ai pris ma décision. Je vais accepter l'offre de Bordeaux. Je partirai le cinq janvier. Je crois que c'est ce qu'il y a de mieux, pour nous deux. »", "'결정했어. 보르도 제안을 받아들일 거야. 1월 5일에 떠날게. 우리 둘에게 가장 좋은 선택인 것 같아.'"),
(A, "(la voix sourde) Elle a décidé. Elle part.", "(탁한 목소리로) 결정했어. 그녀가 떠난다."),
(T, "« Je ne te demande pas de me suivre. Tu as ton domaine, ta Loire, ton père, ton passé. Je serai toujours une étrangère dans ces choses-là. »", "'따라와 달라고 하지 않아. 넌 농장, 루아르, 아버지, 너의 과거가 있어. 나는 그 안에서 늘 이방인일 거야.'"),
(A, "(un souffle) Une étrangère...", "(숨을 내쉬며) 이방인이라니..."),
(T, "« Je ne veux pas que tu me retiennes. Je ne veux pas que tu viennes. Je veux juste que tu saches que je t'ai aimé, vraiment, de tout ce que je peux aimer. »", "'붙잡지 말아 줘. 오지도 말아 줘. 그냥 내가 진심으로, 사랑할 수 있는 모든 걸로 널 사랑했다는 걸 알았으면 해.'"),
(A, "(les larmes aux yeux) « Aimé ». Passé composé.", "(눈물이 고여) '사랑했다'. 복합과거."),
(T, "« Je ne veux pas qu'on se fasse du mal. Alors je préfère partir en silence, plutôt que de te dire des choses que je regretterai. Je te souhaite d'être heureux. Léa. »", "'서로 상처 주고 싶지 않아. 그래서 후회할 말을 하느니 조용히 떠나는 걸 택할게. 네가 행복하길 바라. 레아.'"),
(None, "Il laisse retomber la feuille sur la table. Ses mains tremblent. Il s'assoit sur le bord du canapé, la tête dans ses mains. Quelques minutes passent. La porte s'ouvre.", "그가 종이를 탁자 위에 떨어뜨린다. 손이 떨린다. 소파 가장자리에 앉아 머리를 두 손으로 감싼다. 몇 분이 흐른다. 문이 열린다."),
(L, "(entre avec une baguette, un sourire hésitant) Voilà, la baguette est encore chaude. Antoine ?", "(바게트를 들고 머뭇거리는 미소로 들어오며) 자, 바게트가 아직 따뜻해. 앙투안?"),
(None, "Elle le voit, assis, pâle. Puis ses yeux tombent sur la feuille dépliée, sur la table. Son sourire s'efface. Le pain lui glisse des mains.", "그녀가 창백하게 앉아 있는 그를 본다. 그러다 시선이 탁자 위에 펼쳐진 종이로 떨어진다. 미소가 사라진다. 빵이 손에서 미끄러진다."),
(L, "(d'une voix blanche) Tu as lu.", "(힘없는 목소리로) 읽었구나."),
(A, "(sans la regarder) Oui.", "(그녀를 보지 않고) 응."),
(L, "Je t'avais dit que je ne voulais pas que tu la lises.", "네가 읽지 않았으면 한다고 말했잖아."),
(A, "Tu m'as dit « pas encore ». Elle portait mon nom. Je me suis dit que...", "'아직은 아니야'라고 했어. 내 이름이 적혀 있었고. 그래서 생각했어..."),
(L, "Tu t'es dit que tu avais le droit.", "읽을 권리가 있다고 생각했구나."),
(A, "Oui.", "응."),
(L, "(ramasse la baguette, la pose avec soin sur la table) Tu n'avais pas le droit.", "(바게트를 주워 조심스럽게 탁자 위에 놓으며) 권리 없었어."),
(A, "Je le sais maintenant.", "이제 알아."),
(L, "Tu as lu une lettre écrite dans un moment de désespoir. Une lettre que je n'ai pas envoyée, justement parce que je ne la pensais pas vraiment.", "절망의 순간에 쓴 편지를 읽었어. 진심이 아니었기 때문에 바로 보내지 않은 편지를."),
(A, "Ce n'est pas ce que dit la lettre.", "편지는 그렇게 말하지 않아."),
(L, "La lettre dit ce que j'ai cru penser à minuit, dans le noir.", "편지는 내가 자정에 어둠 속에서 생각했다고 믿은 걸 말해."),
(A, "« Je vais accepter l'offre de Bordeaux. Je partirai le cinq janvier. » C'est écrit noir sur blanc.", "'보르도 제안을 받아들일 거야. 1월 5일에 떠날게.' 흑백으로 분명히 써 있어."),
(L, "Je sais ce qui est écrit. C'est moi qui l'ai écrit.", "뭐가 적혀 있는지 알아. 내가 썼으니까."),
(A, "Alors c'est ta décision.", "그럼 네 결정이네."),
(L, "(après un silence) C'était ma décision à minuit le sept novembre. Ce n'est pas forcément ma décision aujourd'hui.", "(침묵 뒤) 11월 7일 자정에는 내 결정이었어. 오늘도 꼭 그렇다는 건 아니야."),
(A, "Et aujourd'hui, c'est quoi, ta décision ?", "그럼 오늘 네 결정은 뭐야?"),
(L, "Je ne sais pas. C'est ça, la vérité.", "모르겠어. 그게 사실이야."),
(A, "(se lève, marche vers la fenêtre) Tu m'as écrit que tu m'avais « aimé ». Au passé.", "(일어나 창가로 가며) 네가 날 '사랑했다'고 썼어. 과거로."),
(L, "(un temps, déconcertée) Je l'ai écrit comme ça parce que je croyais que c'était fini.", "(잠시 후 당황하여) 끝난 줄 알았기 때문에 그렇게 썼어."),
(A, "Et maintenant ?", "그럼 지금은?"),
(L, "Maintenant, je ne crois plus que ce soit fini.", "지금은 끝났다고 믿지 않아."),
(A, "(se retourne) Tu ne crois plus ?", "(돌아서며) 더는 믿지 않는다고?"),
(L, "Je ne crois plus que ce soit fini, Antoine. Je n'aurais pas dû t'écrire ça. Mais tu n'aurais pas dû le lire.", "끝났다고 더는 믿지 않아, 앙투안. 그런 편지를 쓰지 말았어야 했어. 하지만 너도 읽지 말았어야 했어."),
(A, "Nous avons chacun fait quelque chose que nous n'aurions pas dû faire.", "우린 둘 다 하지 말았어야 할 일을 했네."),
(L, "Oui.", "응."),
(A, "C'est un début de symétrie.", "대칭의 시작이네."),
(L, "(un petit rire nerveux) C'est ça, ton humour d'historien, dans un moment pareil ?", "(작은 신경질적 웃음) 이런 순간에도 그게 역사학자 유머야?"),
(A, "C'est le seul que j'aie. Il m'aide à ne pas pleurer.", "내가 가진 유일한 거야. 울지 않게 도와줘."),
(L, "Tu peux pleurer, tu sais.", "울어도 돼."),
(A, "Pas devant toi. Pas ce matin.", "너 앞에서는 안 돼. 오늘 아침엔."),
(L, "Pourquoi pas ?", "왜 안 돼?"),
(A, "Parce que j'ai besoin de te dire quelque chose de très clair, et que je ne veux pas le dire en larmes.", "아주 분명히 말해야 할 게 있는데 눈물을 흘리며 말하고 싶지 않아."),
(L, "Je t'écoute.", "듣고 있어."),
(A, "La lettre m'a fait comprendre une chose. Quand j'ai lu « Je ne te demande pas de me suivre », j'ai eu mal. Pas parce que tu partais. Parce que tu ne me demandais pas de te suivre.", "그 편지로 한 가지를 깨달았어. '따라와 달라고 하지 않아'를 읽을 때 아팠어. 네가 떠나서가 아니라 날 따라오게 하지 않아서."),
(L, "(émue) Antoine...", "(감동하여) 앙투안..."),
(A, "Je me suis dit : si elle m'avait demandé de la suivre, j'aurais réfléchi. Sérieusement. Parce que j'aime la Loire, mais je t'aime davantage.", "그녀가 따라오라고 했다면 진지하게 생각했을 거라고 스스로에게 말했어. 난 루아르를 사랑하지만 너를 더 사랑하니까."),
(L, "Tu ne peux pas dire ça. Tu as un domaine, une famille.", "그런 말 하면 안 돼. 넌 농장이 있고 가족이 있잖아."),
(A, "Je peux le dire parce que c'est vrai. Je ne dis pas que je le ferais. Je dis que je l'envisagerais. C'est la première fois que je l'envisage.", "사실이니까 말할 수 있어. 하겠다는 게 아니야. 고려하겠다는 거야. 처음으로 고려해 본 거야."),
(L, "(prend une inspiration tremblante) Et si, moi aussi, je l'envisageais ? Rester à Paris ? Renoncer à Bordeaux ?", "(떨리는 숨을 들이쉬며) 나도 고려해 본다면? 파리에 남는 걸? 보르도를 포기하는 걸?"),
(A, "Je ne te demanderais pas de le faire.", "네게 그렇게 해 달라고 부탁하지 않을 거야."),
(L, "Pourquoi ?", "왜?"),
(A, "Parce que tu finirais par me le reprocher. Pas aujourd'hui. Pas dans un an. Mais un jour.", "결국 날 탓하게 될 테니까. 오늘도, 일 년 뒤도 아니지만 언젠가는."),
(L, "(un temps, un petit rire douloureux) Tu as toujours raison. C'est insupportable.", "(잠시 후 아픈 작은 웃음) 넌 늘 옳아. 견딜 수 없어."),
(A, "J'ai tort assez souvent. La preuve : j'ai lu ta lettre.", "나도 자주 틀려. 증거: 네 편지를 읽었잖아."),
(L, "(sourit enfin) Oui. Voilà une bonne preuve.", "(마침내 미소 지으며) 응. 좋은 증거네."),
(None, "Un silence plus doux. Antoine s'approche et ramasse la lettre. Il la plie soigneusement, la remet dans son enveloppe, et la tend à Léa.", "더 부드러운 침묵이 흐른다. 앙투안이 다가가 편지를 집어 든다. 조심스럽게 접어 봉투에 넣고 레아에게 건넨다."),
(A, "Elle t'appartient. Garde-la.", "네 거야. 간직해."),
(L, "(la prend) Je vais la garder. Mais je l'ouvrirai dans un an, pour voir si je pensais ce que je disais.", "(받으며) 간직할게. 하지만 일 년 뒤에 열어서 내가 진심이었는지 볼 거야."),
(A, "Dans un an, je serai à côté de toi quand tu l'ouvriras.", "일 년 뒤 네가 열 때 나는 네 곁에 있을 거야."),
(L, "Tu en es sûr ?", "확신해?"),
(A, "Non. Mais je suis déterminé.", "아니. 하지만 결심은 했어."),
(L, "(émue) « Déterminé ». C'est un très joli mot pour quelqu'un qui n'est pas sûr.", "(감동하여) '결심'. 확신하지 않는 사람에겐 아주 예쁜 단어야."),
(A, "Je dois partir. Mon cours de première commence dans vingt-trois minutes.", "가야 해. 2학년 수업이 이십삼 분 뒤에 시작해."),
(L, "(prend sa main) Antoine. Ce soir. Rejoins-moi sur les marches du Sacré-Cœur. À dix-neuf heures.", "(그의 손을 잡으며) 앙투안. 오늘 저녁. 사크레쾨르 계단에서 만나. 7시에."),
(A, "Sur les marches ? Il fait un froid de loup.", "계단에서? 엄청 추운데."),
(L, "Raison de plus. On sera forcés de se rapprocher pour avoir chaud.", "그러니 더더욱. 따뜻해지려면 가까워질 수밖에 없을걸."),
(A, "(sourit) Le plan est ingénieux.", "(미소 지으며) 기발한 계획이네."),
(L, "Je suis graphiste. J'ai des idées visuelles.", "난 디자이너잖아. 시각적인 아이디어가 있지."),
(A, "À dix-neuf heures, alors. Et cette fois, précisons : en haut ou en bas des marches ?", "그럼 7시에. 그리고 이번엔 정확히 하자. 계단 위야, 아래야?"),
(L, "(rit) Au milieu. Exactement au milieu. Troisième palier en partant du bas.", "(웃으며) 한가운데. 정확히 한가운데. 아래에서 세 번째 층계참."),
(A, "J'y serai. Avec un parapluie.", "갈게. 우산을 들고."),
(L, "Il va pleuvoir ?", "비가 올까?"),
(A, "C'est Paris. Et c'est novembre.", "파리잖아. 그리고 11월이고."),
(None, "Il l'embrasse sur le front, doucement, puis prend sa veste. Sur le seuil, il se retourne.", "그가 그녀의 이마에 부드럽게 입 맞추고 재킷을 집어 든다. 문턱에서 돌아본다."),
(A, "Léa ?", "레아?"),
(L, "Oui ?", "응?"),
(A, "Je te le répète : je me suis trompé. Pas sur la lettre. Sur tout le reste.", "다시 말할게. 내가 틀렸어. 편지에 대해서가 아니라 나머지 전부에 대해서."),
(L, "Moi aussi. Sur tout le reste.", "나도. 나머지 전부에 대해서."),
(None, "Il sort. La porte se ferme doucement. Léa reste debout au milieu de la pièce, l'enveloppe à la main. Dehors, un premier nuage gris s'accroche au clocher de l'église voisine.", "그가 나간다. 문이 부드럽게 닫힌다. 레아가 봉투를 손에 든 채 방 한가운데 서 있다. 밖에서는 첫 회색 구름이 이웃 성당 종탑에 걸린다."),
]
VOCAB = [
("A2","une enveloppe / un croissant / une baguette","봉투 / 크루아상 / 바게트","일상 어휘"),
("A2","une fenêtre / un bureau / une lettre","창문 / 책상 / 편지","장면 구성 어휘"),
("A2","froid / un froid de loup","추운 / 몹시 추운","« Il fait un froid de loup. » 구어 관용"),
("B1","non cacheté / cacheter","봉하지 않은 / 봉하다","« une enveloppe non cachetée »"),
("B1","un seuil / tremblant","문턱 / 떨리는","« une écriture un peu tremblante »"),
("B1","plier / déplier","접다 / 펴다","« une feuille pliée en quatre »"),
("B1","retenir / suivre quelqu'un","붙잡다 / 따라가다","« Je ne veux pas que tu me retiennes. »"),
("B1","désespoir / désespéré","절망 / 절망한","« un moment de désespoir »"),
("B2","d'une voix blanche","힘없는 목소리로","« d'une voix blanche » 감정이 빠진 목소리"),
("B2","déconcerté / décontenancé","당황한","« un temps, déconcertée »"),
("B2","déterminé / déterminer","결심한 / 결정짓다","« Je suis déterminé. »"),
("B2","ingénieux / ingéniosité","기발한 / 재치","« Le plan est ingénieux. »"),
("B2","renoncer à","포기하다","« Renoncer à Bordeaux ? »"),
("B2","reprocher / un jour","탓하다 / 언젠가","« Tu finirais par me le reprocher. »"),
("B2","une étrangère","이방인(여성)","« Je serai toujours une étrangère dans ces choses-là. »"),
("B2","symétrie / un début de symétrie","대칭 / 대칭의 시작","앙투안의 지적인 유머"),
("C1","noir sur blanc","흑백으로, 분명히","« C'est écrit noir sur blanc. » 문서로 분명한 것"),
("C1","envisager","고려하다","« Je l'envisagerais. C'est la première fois que je l'envisage. »"),
("C1","préciser / préciser en haut ou en bas","명확히 하다","약속 장소를 분명히 정하기"),
("C1","on sera forcés de se rapprocher","우린 가까워질 수밖에 없을 것이다","수동적 의무 표현"),
("C1","pour voir si je pensais ce que je disais","내가 진심이었는지 보려고","si + 반과거 간접 의문"),
("C1","un nuage s'accroche au clocher","구름이 종탑에 걸린다","문학적 묘사"),
("C1","Dans un an, je serai à côté de toi quand tu l'ouvriras.","일 년 뒤 네가 열 때 나는 네 곁에 있을 거야.","quand + 단순미래: 미래의 시점을 약속"),
("C1","l'humour d'historien","역사학자 유머","직업을 이용한 자기 비하 유머"),
]
GRAM = [
("B1","조건법 과거: Je n'aurais pas dû / Tu n'aurais pas dû",
 "« Je n'aurais pas dû t'écrire ça. Mais tu n'aurais pas dû le lire. » devoir 조건법 과거: 후회와 비난. 이 구조는 30화·31화의 후회 표현을 이어 받는다."),
("B2","조건법 현재: Je ne te demanderais pas de le faire",
 "« Je ne te demanderais pas de le faire. » « Tu finirais par me le reprocher. » 조건법으로 가정의 결과를 담담하게 말하기. 감정이 격해질수록 조건법은 담담한 어조를 만든다."),
("B2","접속법: Je ne crois plus que ce soit fini",
 "« Je ne crois plus que ce soit fini. » croire que + 직설법, 하지만 부정·의문 croire que + 접속법. 믿음의 부정은 접속법을 부른다."),
("B2","간접 의문과 시제: pour voir si je pensais",
 "« Pour voir si je pensais ce que je disais. » si + 반과거(간접 의문, 과거 시점). 주절이 미래여도 종속절이 과거를 가리키면 반과거."),
("B2","복합과거와 대과거: elle a été écrite dans un moment où je n'allais pas bien",
 "« Elle a été écrite dans un moment où je n'allais pas bien. » 수동 복합과거와 반과거의 결합. 상황의 배경을 반과거로, 사건을 복합과거로."),
("C1","대명사 le + 추정 문장: je le sais / je le pense",
 "« Je le sais maintenant. » « Je ne la pensais pas vraiment. » 대명사 le가 앞 문장 전체를 받는다. 중성 대명사 le는 성·수가 없다."),
("C1","c'est la première fois que + 현재 / 복합과거 (복습)",
 "« C'est la première fois que je l'envisage. » 반복 구문. 변화의 순간을 짚을 때."),
("C1","편지 문체: C'est le 7 novembre, il est minuit.",
 "« Antoine, c'est le 7 novembre, il est minuit. » 편지 서두에서 날짜·시간을 밝히며 시작. 현재형으로 현장감을 준다. 문어체의 한 장치."),
]
CULTURE = [
("프랑스의 편지와 'lettre non envoyée'",
 "문학과 영화에서 '부치지 않은 편지'는 마음의 진실을 보여 주는 장치다. 프랑스에서는 사랑 편지(lettre d'amour)를 쓰는 전통이 강하며 문장 어조가 구어보다 훨씬 격식 있다."),
("사크레쾨르 계단과 약속 장소",
 "10화에서 두 사람이 엇갈렸던 곳이다. 이번에는 '세 번째 층계참'처럼 정확하게 약속하는 장면이 나온다. 반복 구조가 이야기의 성장을 보여 준다."),
("« les yeux dans les yeux »",
 "프랑스어에서 진지한 대화를 앞두고 눈을 맞춘다는 뜻이다. 앙투안이 눈물을 흘리며 말하길 거부하는 것은 감정을 통제하려는 태도를 보여 준다."),
]
META = dict(part=3, ep=34, part_label="제3부 늦수확 · Vendanges tardives", title_fr="La lettre jamais envoyée", title_ko="부치지 못한 편지",
 place="레아의 원룸 · 11월 13일 목요일 오전 9시",
 chars="Léa · Antoine · La lettre (레아의 편지글)",
 wine="(와인 없음) 아침 커피와 크루아상",
 focus="서한체, 조건법 과거, croire que + 접속법, envisager, 후회와 용서의 표현",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제35화 « Réconciliation sous la pluie » : 사크레쾨르 계단 세 번째 층계참에서 만난 두 사람. 쏟아지는 비 속에서 진짜 화해가 시작된다.")
