# -*- coding: utf-8 -*-
G, L, A, P, K, M, R = "Gaston", "Léa", "Antoine", "Mme Pichon", "Karim", "Mme Lacoste", "Gérard"
D = [
(None, "Vendredi 14 novembre, 18 h. La Cave des Abbesses est fermée au public. Sur le comptoir, un grand dossier de carton beige, une bouteille de Morgon, quatre verres. Gaston, madame Pichon et Karim sont assis en demi-cercle. Léa et Antoine, debout devant eux, se tiennent par la main comme deux élèves à l'oral.", "11월 14일 금요일 저녁 6시. 라 카브 데 자베스는 손님을 받지 않는다. 카운터 위에는 큰 베이지색 마분지 서류철, 모르공 한 병, 잔 네 개. 가스통, 피숑 부인, 카림이 반원으로 앉아 있다. 레아와 앙투안이 구술 시험을 보는 학생처럼 손을 맞잡고 그들 앞에 서 있다."),
(G, "Vous avez l'air de condamnés à mort. Parlez, avant que je ne meure de curiosité.", "사형수 같은 표정이네. 호기심에 죽기 전에 말해 봐."),
(L, "Gaston, nous avons une proposition à te faire. Une proposition sérieuse. On l'a préparée depuis hier soir, jusqu'à trois heures du matin.", "가스통, 제안이 있어요. 진지한 제안이에요. 어젯밤부터 새벽 3시까지 준비했어요."),
(A, "Elle tient en une phrase : nous voulons reprendre La Cave des Abbesses.", "한 문장으로 말할 수 있어요. 우리가 라 카브 데 자베스를 인수하고 싶습니다."),
(None, "Un silence de mort. Karim lâche un petit « oh ». Madame Pichon met la main devant sa bouche. Gaston, immobile, ne cille pas.", "죽음 같은 침묵. 카림이 작은 '오' 소리를 낸다. 피숑 부인이 입을 가린다. 가스통은 눈도 깜박이지 않고 꼼짝 않는다."),
(G, "(très lentement) Répétez.", "(아주 천천히) 다시 말해."),
(L, "Nous voulons reprendre la boutique. Antoine et moi. Avec l'aide de Julien Barbier pour les approvisionnements en Loire, de Margaux Delcourt pour l'aspect juridique, et de toi, si tu acceptes de rester comme conseiller.", "우리가 가게를 인수하고 싶어요. 앙투안과 저. 루아르 공급은 쥘리앵 바르비에, 법률은 마르고 델쿠르가 맡고, 당신이 고문으로 남아 주신다면."),
(G, "Vous êtes fous.", "너희 미쳤구나."),
(A, "Peut-être. Mais nous sommes des fous organisés.", "어쩌면요. 하지만 체계적인 미치광이예요."),
(G, "Antoine, tu es professeur d'histoire. Léa, tu es graphiste. Aucun de vous deux n'a jamais tenu un commerce.", "앙투안, 넌 역사 교사야. 레아, 넌 그래픽 디자이너고. 둘 중 누구도 장사를 해 본 적이 없어."),
(L, "Aucun de nous n'avait jamais eu de chat non plus, jusqu'à ce que tu nous apprennes à aimer le tien.", "우리 중 누구도 고양이를 키운 적이 없었지만 당신이 고양이를 사랑하는 법을 가르쳐 줬잖아요."),
(G, "Je n'ai pas de chat à la boutique.", "가게에 고양이 없어."),
(A, "Alors tu comprends le principe : on apprend en faisant.", "그럼 원리는 이해하겠네. 하면서 배우는 거예요."),
(K, "(se lève, enthousiaste) Moi, je suis pour ! Je peux m'occuper du site web, de la logistique, du stock !", "(열정적으로 일어나며) 저는 찬성이에요! 웹사이트, 물류, 재고는 제가 맡을 수 있어요!"),
(P, "Karim, assieds-toi. Tu nous fais de l'ombre.", "카림, 앉아. 그늘이 지잖아."),
(G, "Léa, Antoine. Vous avez réfléchi à l'argent ? Cent quatre-vingt mille euros pour le fonds de commerce. Plus les travaux, le stock, le loyer.", "레아, 앙투안. 돈에 대해 생각해 봤어? 영업권 18만 유로. 거기에 공사, 재고, 임대료까지."),
(L, "(ouvre le dossier) Voici le business plan. Dix pages, rédigées par Karim et moi. Un prêt bancaire de cent trente mille euros sur sept ans, un apport personnel de quarante mille, et dix mille d'un prêt familial, de Margaux et de mes parents.", "(서류철을 열며) 사업 계획서예요. 카림과 제가 쓴 열 장이에요. 7년 상환 은행 대출 13만 유로, 자기 자본 4만, 마르고와 제 부모님이 주시는 가족 대출 1만 유로."),
(G, "(feuillette, silencieux) Des projections de chiffre d'affaires. Des plans de communication. Des idées de collaboration avec des vignerons indépendants...", "(말없이 넘겨 보며) 매출 전망. 홍보 계획. 독립 농가들과의 협업 아이디어..."),
(A, "Tu verras, à la page sept, un projet de vente en ligne à partir de la boutique, avec les vins de Loire de mon père et de Julien. Et à la page neuf, la proposition de Léa : un atelier d'étiquettes pour les petits vignerons.", "7쪽에는 우리 아버지와 쥘리앵의 루아르 와인을 가게에서 온라인으로 파는 계획이 있어요. 9쪽에는 레아의 제안, 소규모 농가를 위한 라벨 공방이 있고요."),
(G, "Un atelier d'étiquettes ? Ici ?", "라벨 공방? 여기서?"),
(L, "Dans l'arrière-boutique. Un espace de création pour les vignerons qui n'ont pas les moyens de se payer une agence. Je les aide à raconter leur histoire. Comme Julien avec ses photos.", "안쪽 창고에요. 에이전시에 맡길 여유가 없는 농가들이 이야기를 풀어내도록 돕는 창작 공간이에요. 쥘리앵의 사진 이야기처럼요."),
(G, "(lève enfin les yeux du dossier) Et Maison Vinum ?", "(마침내 서류에서 눈을 들며) 그럼 메종 비눔은?"),
(A, "Il faut leur demander de prolonger la date de réponse jusqu'au trente et un janvier. Le temps pour nous d'obtenir le prêt.", "답변 기한을 1월 31일까지 연장해 달라고 부탁해야 해요. 우리가 대출을 받을 시간이 필요해요."),
(G, "Et s'ils refusent ?", "그리고 거절하면?"),
(L, "Alors tu signeras avec eux le vingt-huit, comme prévu. Nous n'aurons rien perdu, sinon un mois de sommeil.", "그럼 예정대로 28일에 서명하면 돼요. 우리는 한 달 치 잠 말고는 잃을 게 없어요."),
(G, "(un sourire involontaire) Vous avez tout prévu.", "(저도 모르게 미소 지으며) 전부 예상해 뒀구나."),
(A, "Non. Nous avons prévu le plan A, le plan B, et le plan C.", "아니요. 플랜 A, 플랜 B, 플랜 C를 준비했어요."),
(G, "C'est quoi, le plan C ?", "플랜 C가 뭐냐?"),
(L, "Que tu viennes chez moi vendre du vin sur un tabouret, dans mon studio, rue Durantin.", "당신이 뒤랑탱 거리 제 원룸에 와서 스툴에 앉아 와인을 파는 거예요."),
(P, "(éclate de rire) Voilà le seul plan qui ait un peu de charme !", "(웃음을 터뜨리며) 그게 유일하게 매력 있는 계획이네!"),
(G, "(se lève, marche vers la vitrine, dos tourné) Je vais vous dire quelque chose. Et je ne le dirai qu'une seule fois.", "(일어나 진열창 쪽으로 걸어가 등을 돌리고) 한마디 하마. 단 한 번만 말할 거야."),
(None, "Il reste un long moment immobile, les mains dans les poches, le regard dans la rue sombre. Quand il se retourne, ses yeux brillent.", "그가 주머니에 손을 넣고 어두운 거리를 바라본 채 한참 꼼짝 않는다. 돌아섰을 때 눈이 반짝이고 있다."),
(G, "J'ai passé trente-cinq ans à penser que cette boutique mourrait avec moi. J'étais presque en paix avec cette idée. Et vous arrivez, avec un dossier en carton beige, et vous me dites que cette boutique pourrait continuer.", "35년 동안 이 가게가 나와 함께 죽을 거라고 생각했어. 그 생각과 거의 화해했지. 그런데 너희가 베이지색 서류철을 들고 와서 이 가게가 계속될 수 있다고 말하는구나."),
(A, "Gaston...", "가스통..."),
(G, "Je ne dis pas oui. Je ne dis pas non. Je dis que... Je dis que c'est la plus belle chose qu'on m'ait jamais proposée. Et que j'ai peur d'y croire.", "예라고 하지 않아. 아니라고도 하지 않아. 다만... 내게 제안된 것 중 가장 아름다운 일이라고 말하는 거야. 그리고 믿기 두렵다고."),
(L, "(les larmes aux yeux) Tu peux y croire.", "(눈물이 고여) 믿어도 돼요."),
(G, "Je veux d'abord lire tout le dossier. Avec un stylo rouge. Je serai impitoyable.", "먼저 서류 전체를 읽고 싶어. 빨간 펜으로. 가차 없이 볼 거야."),
(A, "C'est exactement ce qu'on attendait.", "그게 바로 우리가 기대한 거예요."),
(G, "Et madame Pichon me dira ce qu'elle en pense.", "그리고 피숑 부인이 어떻게 생각하는지 말해 주실 거고."),
(P, "(se lève lentement, s'approche des deux jeunes) Gaston, je n'ai jamais voulu qu'on te sépare de cette boutique. Je voulais seulement qu'on ne la livre pas à n'importe qui. Eux, ce n'est pas n'importe qui.", "(천천히 일어나 두 젊은이에게 다가가며) 가스통, 난 네가 이 가게와 헤어지길 원한 적이 없어. 아무에게나 넘기지 않기를 바랐을 뿐이야. 이 아이들은 아무나가 아니야."),
(L, "Merci, madame Pichon.", "고마워요, 피숑 부인."),
(P, "Ne me remercie pas. Contente-toi de réussir. Sinon, je viendrai te hanter dans ton arrière-boutique.", "고마워하지 마. 성공이나 해. 안 그러면 네 창고에서 유령처럼 널 괴롭히러 올 거야."),
(None, "Le lendemain, samedi 15 novembre, 10 h. Léa, assise à la petite table de son studio, face à son ordinateur, un cahier ouvert à côté d'elle. L'écran affiche : « Appel entrant — Mme Lacoste ». Elle respire profondément et décroche.", "다음 날 11월 15일 토요일 오전 10시. 레아가 원룸의 작은 책상 앞에서 컴퓨터를 마주하고 옆에 노트를 펼쳐 놓았다. 화면에 '수신 전화 — 라코스트 대표'가 뜬다. 그녀가 숨을 깊이 쉬고 받는다."),
(L, "Bonjour, Madame Lacoste.", "안녕하세요, 라코스트 대표님."),
(M, "Bonjour, Léa. Nous sommes le quinze novembre. Je suppose que vous avez une réponse pour moi.", "안녕하세요, 레아. 11월 15일이네요. 답이 있을 것 같은데요."),
(L, "Oui. Je vous remercie d'avoir été patiente. Voici ma décision. Je ne peux pas accepter l'offre telle qu'elle est écrite.", "네. 기다려 주셔서 감사합니다. 제 결정입니다. 제안을 문서 그대로 받아들일 수는 없어요."),
(M, "(un silence) Je vois. Et c'est définitif ?", "(침묵) 알겠어요. 확정이에요?"),
(L, "Pas tout à fait. Voici ce que je propose. Je deviens directrice artistique associée de la maison Lacoste & Fils, à temps partiel : huit jours par mois à Bordeaux, regroupés par blocs de quatre jours, et le reste à distance depuis Paris.", "완전히는 아니에요. 제안은 이렇습니다. 라코스트 앤 필스의 비상근 공동 아트 디렉터가 되는 거예요. 한 달에 8일, 4일씩 묶어 보르도에 있고 나머지는 파리에서 원격으로 일합니다."),
(M, "À temps partiel. À soixante pour cent ?", "비상근이라. 60퍼센트요?"),
(L, "À soixante pour cent. Avec un CDI, un salaire proportionnel, et une clause de liberté : je garde mes clients indépendants, à condition qu'ils ne soient pas des concurrents directs.", "60퍼센트로요. 무기 계약, 비례 월급, 그리고 자유 조항이 있어요. 직접 경쟁사가 아닌 한 기존 독립 고객을 유지합니다."),
(M, "Vous me proposez de partager votre temps. Pourquoi ?", "시간을 나누겠다는 제안이군요. 왜죠?"),
(L, "Parce que je ne suis pas faite pour une seule ville, ni pour un seul projet. Et parce que j'ai un autre projet, à Paris, auquel je tiens autant qu'à Bordeaux.", "한 도시, 한 프로젝트에만 맞는 사람이 아니라서요. 그리고 파리에 보르도만큼 소중한 다른 프로젝트가 있어요."),
(M, "Je peux savoir lequel ?", "어떤 건지 물어도 될까요?"),
(L, "Le rachat d'une boutique de vin à Montmartre. Avec quelqu'un qui compte pour moi.", "몽마르트르의 와인 가게 인수예요. 저에게 소중한 사람과 함께요."),
(M, "(un petit rire, étonnée) Vous êtes une femme pleine de surprises, Léa.", "(놀라 작은 웃음) 레아는 놀라움이 가득한 사람이네요."),
(L, "On me le dit.", "그런 말을 들어요."),
(M, "Écoutez. Je dois en parler à mon associé. Mais je vous dis d'ores et déjà ce que je ressens : cette formule me convient. Elle me convient même mieux que l'ancienne. Un cadre qui a un pied dans la création indépendante nous rapportera plus qu'un cadre épuisé.", "들어 보세요. 동업자와 상의해야 해요. 하지만 지금 제 느낌을 말해 드릴게요. 이 방식이 마음에 들어요. 예전 방식보다 더 마음에 들어요. 독립 창작에 한 발을 걸친 관리자가 지친 관리자보다 우리에게 더 많은 걸 가져다줄 거예요."),
(L, "(un souffle) Vraiment ?", "(숨을 내쉬며) 정말요?"),
(M, "Vraiment. Je vous donne une réponse définitive lundi. Mais sachez que si mon associé a le moindre doute, je défendrai votre proposition.", "정말이에요. 월요일에 최종 답을 드릴게요. 하지만 동업자가 조금이라도 의심하면 제가 당신의 제안을 변호할 거라는 걸 알아 두세요."),
(L, "Je ne sais pas comment vous remercier.", "어떻게 감사해야 할지 모르겠어요."),
(M, "En faisant bien votre travail. Et en m'invitant à votre inauguration. Je suis une grande amatrice de vin de Loire, vous le savez.", "일을 잘해 주시는 걸로요. 그리고 개점식에 초대해 주세요. 제가 루아르 와인 애호가인 거 아시잖아요."),
(L, "Vous serez la première invitée.", "첫 번째 초대 손님이실 거예요."),
(M, "À lundi, Léa.", "월요일에 봐요, 레아."),
(None, "Elle raccroche. Léa pose le téléphone sur la table, se prend la tête entre les mains, éclate d'un rire nerveux, puis se met à pleurer de joie. Dans le couloir, quelqu'un frappe à la porte.", "그녀가 전화를 끊는다. 레아가 전화기를 탁자에 내려놓고 머리를 두 손으로 감싸고 신경질적으로 웃음을 터뜨리다가 기쁨의 눈물을 흘린다. 복도에서 누군가 문을 두드린다."),
(A, "(à travers la porte) Léa ? C'est moi. J'ai entendu un cri.", "(문 너머에서) 레아? 나야. 비명 소리가 들렸어."),
(L, "(ouvre, en larmes, riant) Elle a dit oui ! Presque oui ! Elle réfléchit, elle en parle à son associé, mais elle a dit que ça lui plaisait !", "(울며 웃으며 문을 열고) 승낙했어! 거의 승낙! 생각해 보고 동업자와 상의하겠다지만 마음에 든다고 했어!"),
(A, "(la prend dans ses bras, la soulève) C'est formidable ! Léa !", "(그녀를 안아 들어 올리며) 대단해! 레아!"),
(L, "(riant) Repose-moi ! Je ne suis pas un sac de farine !", "(웃으며) 내려놔! 밀가루 자루가 아니야!"),
(A, "(la repose) Pardon. Je me suis laissé emporter.", "(내려놓으며) 미안. 감정에 휩쓸렸어."),
(L, "Et toi ? Tu as déjà appelé ton père ?", "그리고 너는? 벌써 아버님께 전화했어?"),
(A, "Pas encore. J'ai tenu à venir d'abord. Mais je vais le faire maintenant. Tu veux être là ?", "아직. 먼저 오고 싶었어. 하지만 지금 할 거야. 네가 옆에 있어 줄래?"),
(L, "Bien sûr.", "물론이지."),
(None, "Il sort son téléphone, met le haut-parleur et compose le numéro. À Saint-Cyr-en-Bourg, on décroche presque aussitôt.", "그가 전화기를 꺼내 스피커폰으로 놓고 번호를 누른다. 생시르앙부르에서 거의 즉시 받는다."),
(R, "Allô ? Antoine ?", "여보세요? 앙투안?"),
(A, "Bonjour, papa. Je suis avec Léa. Elle t'entend.", "안녕하세요, 아빠. 레아와 함께 있어요. 듣고 있어요."),
(R, "Bonjour, mademoiselle. Je suppose que vous avez des nouvelles.", "안녕하세요, 아가씨. 소식이 있겠군요."),
(A, "Oui. Papa, j'ai pris ma décision. J'accepte le partenariat avec Julien. Mais à une condition.", "네. 아빠, 결정했어요. 쥘리앵과의 파트너십을 받아들일게요. 하지만 한 가지 조건이 있어요."),
(R, "Laquelle ?", "어떤 조건이냐?"),
(A, "Que je puisse passer environ la moitié de l'année à Paris. Léa et moi allons essayer de reprendre une boutique de vin à Montmartre. C'est un projet sérieux.", "일 년의 절반쯤은 파리에서 지낼 수 있어야 해요. 레아와 저는 몽마르트르의 와인 가게를 인수하려 해요. 진지한 프로젝트예요."),
(R, "(un long silence) Une boutique de vin. À Montmartre. Avec la graphiste.", "(긴 침묵) 와인 가게. 몽마르트르에서. 그래픽 디자이너와."),
(A, "Oui.", "네."),
(R, "Et tu penses que Julien acceptera que tu ne sois là que six mois par an ?", "그리고 쥘리앵이 네가 일 년에 여섯 달만 있는 걸 받아들일 거라고 생각하니?"),
(A, "Je lui en ai déjà parlé. Il dit que six mois d'un associé valent mieux que douze mois d'un employé fatigué.", "이미 말해 봤어요. 쥘리앵은 지친 직원의 열두 달보다 동업자의 여섯 달이 낫다고 해요."),
(R, "(un petit rire sec) Il a toujours été malin, ce garçon.", "(건조하고 작은 웃음) 쥘리앵은 늘 영리했지."),
(L, "Monsieur Delcourt, permettez-moi de vous dire une chose.", "델쿠르 씨, 한 가지 말씀드려도 될까요?"),
(R, "Je vous écoute, mademoiselle.", "말씀하세요, 아가씨."),
(L, "Je ne veux pas vous prendre votre fils. Je veux que son domaine, la Loire, votre travail, fassent partie de notre vie. Je ne veux pas qu'il choisisse entre vous et moi. Je veux qu'il ne choisisse pas.", "아드님을 빼앗고 싶지 않아요. 그의 농장, 루아르, 아버님의 일이 우리 삶의 일부가 되길 바라요. 아버님과 저 중에서 그가 선택하게 하고 싶지 않아요. 선택하지 않기를 바라요."),
(R, "(un silence, puis, d'une voix plus basse) Mademoiselle Fontaine... Léa. Je peux vous appeler Léa ?", "(침묵 뒤 더 낮은 목소리로) 퐁텐 양... 레아. 레아라고 불러도 될까요?"),
(L, "Bien sûr.", "물론이죠."),
(R, "Léa. Quand ma femme est morte, j'ai cru que la seule façon de tenir était de ne jamais bouger. De m'accrocher à la terre, au domaine, aux habitudes. Et j'ai demandé à mon fils de faire pareil. Je me suis trompé.", "레아. 아내가 죽었을 때 버티는 유일한 방법은 절대 움직이지 않는 거라고 생각했어요. 땅, 농장, 습관에 매달리는 거요. 그리고 아들에게도 똑같이 하라고 했죠. 내가 틀렸어요."),
(A, "(très ému) Papa...", "(깊이 감동하여) 아빠..."),
(R, "Je l'ai compris le jour où j'ai vu mon fils sourire à côté de vous, au salon. Il n'avait pas souri comme ça depuis quinze ans.", "박람회에서 아들이 당신 곁에서 웃는 걸 본 날 깨달았어요. 십오 년 동안 그렇게 웃은 적이 없었으니까."),
(L, "(les larmes aux yeux) Merci, monsieur.", "(눈물이 고여) 감사합니다, 선생님."),
(R, "Appelez-moi Gérard. Et dites à mon fils que si ce n'est pas six mois, ce sera sept. Ou cinq. L'important, c'est qu'il revienne chaque année pour les vendanges.", "제라르라고 불러요. 그리고 아들에게 여섯 달이 아니면 일곱 달이든 다섯 달이든 괜찮다고 전해요. 중요한 건 해마다 수확철에 돌아오는 거예요."),
(A, "Je serai là pour les vendanges, papa. Chaque année. Je te le promets.", "수확철엔 갈게요, 아빠. 해마다. 약속해요."),
(R, "Alors j'attends. Prenez soin de vous. Et... Léa ?", "그럼 기다리마. 몸조심하고. 그리고... 레아?"),
(L, "Oui, Gérard ?", "네, 제라르 씨?"),
(R, "Le Clos des Roches vous attend. Ouvrez-le avec lui, le jour où vous signerez chez le notaire.", "클로 데 로슈가 기다리고 있어요. 공증인 앞에서 서명하는 날 그 사람과 함께 따세요."),
(L, "Nous le ferons, Gérard. Je vous le promets.", "그렇게 할게요, 제라르 씨. 약속해요."),
(None, "Il raccroche. Dans le petit studio, un grand silence emplit l'air, léger et lumineux. Antoine et Léa se regardent, les yeux humides, un sourire immense sur le visage.", "그가 전화를 끊는다. 작은 원룸에 가볍고 환한 커다란 정적이 가득하다. 앙투안과 레아가 촉촉한 눈과 커다란 미소로 서로를 바라본다."),
(L, "Nous avons décidé.", "우리가 결정했어."),
(A, "Nous avons décidé. Ensemble. Cette fois.", "우리가 결정했어. 함께. 이번에는."),
(L, "Et toujours pas de bague, pas de grande déclaration.", "그리고 여전히 반지도 거창한 선언도 없네."),
(A, "(sourit) Ça viendra. Une chose à la fois.", "(미소 지으며) 올 거야. 한 번에 하나씩."),
(L, "(rit) Une chose à la fois. La boutique d'abord.", "(웃으며) 한 번에 하나씩. 가게가 먼저."),
(A, "La boutique d'abord. Le reste ensuite. À mi-chemin.", "가게가 먼저. 나머지는 그다음. 중간에서."),
(L, "À mi-chemin.", "중간에서."),
(None, "Dehors, un rayon de soleil traverse enfin les nuages et se pose sur le zinc des toits de Montmartre. Tout là-haut, la basilique, éblouissante, rayonne dans la lumière d'un début d'hiver.", "밖에서는 마침내 햇살 한 줄기가 구름을 뚫고 몽마르트르 지붕의 함석에 내려앉는다. 저 위 대성당이 초겨울 햇빛 속에서 눈부시게 빛난다."),
]
VOCAB = [
("A2","un dossier / un stylo rouge","서류철 / 빨간 펜","« un dossier de carton beige »"),
("A2","une décision / une réponse","결정 / 답변","핵심 어휘"),
("A2","un sourire / une larme","미소 / 눈물","감정 표현"),
("B1","un condamné à mort","사형수","표정이 굳어 있는 사람을 농담조로 비유"),
("B1","ciller / ne pas ciller","눈을 깜박이다 / 깜박이지 않다","« ne cille pas » 놀람으로 얼어붙음"),
("B1","un approvisionnement","(상품) 조달","와인 가게의 공급 어휘"),
("B1","un prêt bancaire / un apport personnel","은행 대출 / 자기 자본","창업 자금 어휘"),
("B1","prolonger / un délai","연장하다 / 기한","« prolonger la date de réponse »"),
("B2","un business plan / un chiffre d'affaires","사업 계획 / 매출","경영 용어"),
("B2","un prêt familial","가족 대출","« dix mille d'un prêt familial »"),
("B2","un atelier d'étiquettes","라벨 공방","레아의 제안"),
("B2","à temps partiel / un salaire proportionnel","비상근 / 비례 월급","근무 조건"),
("B2","une clause de liberté","자유 조항","계약서 조항"),
("B2","d'ores et déjà","이미, 지금 당장","« d'ores et déjà ce que je ressens »"),
("B2","un associé / une amatrice","동업자 / 애호가(여성)","amateur(e) de vin"),
("B2","hanter","(유령이) 출몰하다","« je viendrai te hanter »"),
("C1","un fou organisé","체계적인 미치광이","앙투안의 자기 소개"),
("C1","faire de l'ombre à quelqu'un","누군가에게 그늘을 드리우다","« Tu nous fais de l'ombre. »"),
("C1","cadre épuisé / cadre créatif","지친 관리자 / 창의적인 관리자","라코스트 대표의 논리"),
("C1","se laisser emporter","감정에 휩쓸리다","« Je me suis laissé emporter. »"),
("C1","livrer à n'importe qui","아무에게나 넘기다","« qu'on ne la livre pas à n'importe qui »"),
("C1","le zinc des toits","지붕의 함석","파리 지붕 특유의 소재"),
("C1","rayonner","빛나다, 광채를 발하다","« la basilique rayonne »"),
("C1","fonds de commerce / rachat","영업권 / 인수","25화 복습"),
]
GRAM = [
("B1","condition 표현: à condition que + 접속법 / sous réserve de",
 "« À condition qu'ils ne soient pas des concurrents directs. » « J'accepte, mais à une condition. » 조건 표현의 접속법(soient). 22화·26화 복습."),
("B1","미래와 확신: Je vais le faire / Je le ferai / Je veux le faire",
 "« Je vais le faire maintenant. » 근접미래, « Nous le ferons. » 단순미래, « Je veux le faire. » 의지. 약속에는 단순미래가 자연스럽다."),
("B2","최상급 + que + 접속법 과거 (복습)",
 "« C'est la plus belle chose qu'on m'ait jamais proposée. » 17화·22화·28화에서 반복된 구문. 이제 입에 붙을 정도로 반복 학습."),
("B2","aucun de nous / aucun de vous deux",
 "« Aucun de vous deux n'a jamais tenu un commerce. » « Aucun de nous n'avait jamais eu de chat. » aucun de + 대명사 + ne + 동사. 부정의 범위를 사람 집합에 적용."),
("B2","접속법: Je veux qu'il ne choisisse pas / pour que",
 "« Je veux qu'il ne choisisse pas. » vouloir que + 접속법 (부정문 포함). « Je ne veux pas qu'il choisisse entre vous et moi. » 같은 구조의 반복."),
("B2","valoir mieux que / mieux vaut",
 "« Six mois d'un associé valent mieux que douze mois d'un employé fatigué. » valoir mieux que = ~보다 낫다. « Il vaut mieux partir. » 판단의 비교."),
("C1","대명동사 se laisser + 부정사: se laisser emporter",
 "« Je me suis laissé emporter. » se laisser + inf = 어떤 힘에 몸을 맡기다(휩쓸리다). « se laisser convaincre » « se laisser aller »."),
("C1","직접화법에서 간접화법으로의 전환: Elle a dit que ça lui plaisait",
 "« Elle a dit que ça lui plaisait. » 직접: « Ça me plaît. » 주절이 복합과거이면 종속절의 현재는 반과거. 17화 간접화법 복습."),
]
CULTURE = [
("프랑스의 창업: 대출과 가족 자금",
 "프랑스에서 소규모 가게 인수는 은행 대출(prêt bancaire)과 자기 자본(apport personnel), 가족·친지의 대출(prêt familial)이 결합된다. 'business plan' 심사는 은행이 하며 영업권 평가는 회계사(expert-comptable)가 맡는다."),
("프랑스의 비상근 정규직(CDI à temps partiel)",
 "CDI는 무기 계약이며 시간제(temps partiel)로도 가능하다. 급여는 비례하며 자유 조항(clause de non-concurrence 또는 libre exercice)으로 다른 활동도 허용될 수 있다."),
("« Appelez-moi Gérard »",
 "프랑스에서 상대가 이름으로 부르라고 말하는 것은 관계가 가까워졌다는 신호다. 제라르가 레아에게 이름을 허락하는 장면은 앙투안 가족이 레아를 받아들였음을 뜻한다."),
]
META = dict(part=3, ep=36, part_label="제3부 늦수확 · Vendanges tardives", title_fr="La décision", title_ko="결정",
 place="La Cave des Abbesses → 레아의 원룸 · 11월 14일 금요일 저녁 6시 · 11월 15일 토요일 오전 10시",
 chars="Léa · Antoine · Gaston · Mme Pichon · Karim · Mme Lacoste (전화) · Gérard (전화)",
 wine="Morgon · Clos des Roches (공증인 앞 서명 날에 열기로 약속)",
 focus="협상·제안 표현, 조건 접속사, 접속법(vouloir que), 사업 어휘, 결단의 문체",
 levelmix="A2 10% / B1 25% / B2 40% / C1 25% 목표",
 next="제4부 제37화 « Marché de Noël » : 12월의 크리스마스 마켓. 가게 인수 준비가 한창인 가운데 두 사람은 뱅쇼 향기 속에서 새로운 계절을 맞는다.")
