# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H = "Inès", "Mathieu", "Hélène"
AG, JP, OD = "Agnès", "Joël", "Odette"

META = {
    "part": 3, "ep": 31,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Agora",
    "title_ko": "아고라",
    "place": "11구 오베르캉프 이네스의 아파트(집 겸 사무실) · 발몽쉬르루아르 나시오날 거리와 카페 데 알 · 루아르 강변 옛 벨랑제 방적 공장 · 아녜스 리비에르의 선거 사무소(옛 신발 가게) / 10월 1일 목요일",
    "chars": "이네스, 마티외, 엘렌 바쇠르(멘토), 아녜스 리비에르(52, 발몽쉬르루아르 시장 후보·시민 명부 « Valmont Ensemble »), 조엘 피카르(카페 데 알 주인), 오데트 샤리에(71, 옛 방적 공장 직공)",
    "work": "공공정책·선거 컨설팅사 Agora Stratégies 설립 — 회사 이름 짓기, SAS 정관·자본금·공동 지분 50:50과 교착 해소 조항, 세 가지 원칙(독립성·투명성·진실) 헌장, 선거 자금 규칙, 첫 고객 아녜스 리비에르 인터뷰와 계약, 발몽쉬르루아르 첫 방문과 '진짜 적은 기권'이라는 발견",
    "life": "마티외가 상자 스물세 개를 들고 이네스 집으로 이사 오는 날, 피가로의 영역 표시, 옷장 반쪽과 여벌 열쇠, 처음으로 '우리 집'이라고 말하는 이네스, 거실 화이트보드에 쓴 세 가지 질문",
    "focus": "창업 어휘(statuts, SAS, capital social, pacte d'associés, Kbis), 정치 기본 어휘(scrutin, liste, mandat, maire sortant, abstention), 동거 일상 표현, 문어 도치(encore faut-il que, sans doute... -t-il), quel que / quelle que + 접속법, 허사 ne, 명사화, 연설 수사(삼항·반복)",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "제32화 Écouter la ville — 발몽 근교 민박의 아침 식사, 여론조사 설계와 주민 인터뷰 50건, 그리고 일요일 장터에서 마주친 뜻밖의 얼굴.",
}

D = [
# ---------- 1. Ouverture : le déménagement ----------
(None, "Jeudi 1er octobre, 8 h. Rue Oberkampf, quatrième étage sans ascenseur. Mathieu monte le dernier carton, essoufflé. Dans l'entrée, une pile de cartons et, appuyé contre le mur, un grand tableau blanc.",
       "10월 1일 목요일, 오전 8시. 오베르캉프 거리, 엘리베이터 없는 건물 4층. 마티외가 숨을 헐떡이며 마지막 상자를 들고 올라온다. 현관에는 상자 더미가 쌓여 있고, 벽에는 커다란 화이트보드가 기대어 서 있다."),
(MA, "Le dernier ! Quatre étages, vingt-trois cartons... Rappelle-moi pourquoi tu as choisi un immeuble sans ascenseur ?", "마지막이다! 4층에, 상자 스물세 개... 왜 엘리베이터도 없는 건물을 골랐는지 다시 말해 줄래?"),
(I, "Parce qu'il y a six ans, je n'avais pas prévu qu'un Alsacien viendrait y installer toute sa bibliothèque. Tu as vraiment besoin de trois cartons de livres ?", "6년 전엔 웬 알자스 남자가 와서 서재를 통째로 들여놓을 줄 몰랐거든. 책 상자가 정말 세 개나 필요해?"),
(MA, "Ce ne sont pas des livres, ce sont des outils de travail. Il y a même un code électoral commenté, acheté d'occasion la semaine dernière.", "책이 아니라 업무 도구야. 지난주에 중고로 산 선거법 주석서도 있어."),
(I, "Tu lis le code électoral avant même d'avoir une société. C'est tellement toi.", "회사도 생기기 전에 선거법을 읽고 있다니. 정말 너답다."),
(None, "Figaro saute sur le carton marqué « FRAGILE — BUREAU » et s'y installe, l'air souverain.", "피가로가 '깨지기 쉬움 — 사무용품'이라고 적힌 상자 위로 뛰어올라 위풍당당하게 자리를 잡는다."),
(MA, "Figaro, descends de là. Il y a mes marqueurs là-dedans.", "피가로, 거기서 내려와. 그 안에 내 마커들이 있어."),
(I, "Laisse tomber. Il prend possession des lieux. Chez les chats, c'est comme ça qu'on signe un bail.", "포기해. 지금 자기 영역이라고 표시하는 중이야. 고양이 세계에선 그게 임대차 계약서에 서명하는 거야."),
(MA, "Alors il a signé avant moi. Bon, où est-ce que je range mes affaires ? Je ne voudrais pas empiéter sur ton territoire.", "그럼 나보다 먼저 서명했네. 자, 내 물건은 어디에 두지? 네 영역을 침범하고 싶진 않은데."),
(I, "J'ai vidé la moitié de la penderie et deux tiroirs de la commode. Et j'ai fait de la place dans la salle de bains : ton rasoir a droit à une étagère entière.", "옷장 절반이랑 서랍장 서랍 두 칸을 비웠어. 욕실에도 자리를 만들었고. 네 면도기는 선반 한 칸을 통째로 쓸 수 있어."),
(MA, "Une étagère entière ? À Saint-Étienne, chez toi, j'avais droit à un coin de lavabo.", "선반 한 칸 전부? 생테티엔 너희 집에선 세면대 한구석이 다였는데."),
(I, "À Saint-Étienne, on se cachait. Ici, on vit ensemble. Nuance.", "생테티엔에선 숨어 지냈잖아. 여기선 같이 사는 거고. 차이가 있지."),
(MA, "Et le tableau blanc, on le met où ? Il n'y a que le salon où il rentre.", "그럼 화이트보드는 어디에 둬? 들어갈 데가 거실밖에 없는데."),
(I, "Le salon sera aussi le bureau. La table devient la salle de réunion, le canapé l'espace d'accueil, et la cuisine... la cafétéria de l'entreprise.", "거실이 사무실도 되는 거지. 식탁은 회의실, 소파는 응접 공간, 그리고 부엌은... 회사 구내 카페."),
(MA, "Un siège social de quarante-deux mètres carrés, avec un chat à l'accueil. Les investisseurs vont adorer.", "42제곱미터짜리 본사에, 안내 데스크엔 고양이. 투자자들이 아주 좋아하겠어."),
(I, "On n'a pas d'investisseurs, c'est tout l'intérêt. Allez, Hélène arrive à dix heures avec les statuts et on n'a toujours pas de nom.", "우린 투자자가 없어. 그게 핵심이지. 자, 엘렌이 10시에 정관 들고 오는데 아직 회사 이름도 없어."),
(MA, "Un cabinet sans nom, un bureau sans bureau et un associé sans double des clés. On commence bien.", "이름 없는 회사, 책상 없는 사무실, 여벌 열쇠도 없는 공동 창업자라. 출발 좋네."),

# ---------- 2. Fonder : le nom, les statuts, les principes ----------
(None, "9 h 15. La table du salon, deux cafés, une feuille couverte de ratures.", "오전 9시 15분. 거실 식탁, 커피 두 잔, 줄이 잔뜩 그어진 종이 한 장."),
(I, "Bon. Les noms. « Kessler Marchetti Conseil » ?", "자, 이름. '케슬레르 마르케티 컨설팅'은?"),
(MA, "Pourquoi Kessler d'abord ?", "왜 케슬레르가 먼저야?"),
(I, "Ordre alphabétique, ne le prends pas personnellement. Mais c'est trop long, et ça sonne comme un cabinet d'avocats fiscalistes.", "알파벳 순서야, 개인적으로 받아들이지 마. 그런데 너무 길고, 세무 전문 로펌 이름 같아."),
(MA, "« Les Trois Questions » ?", "'세 가지 질문'은?"),
(I, "Joli, mais on dirait un jeu télévisé. Et le jour où un client trouvera une quatrième question, on change de nom ?", "예쁘긴 한데 TV 퀴즈 쇼 같아. 그리고 어느 고객이 네 번째 질문을 찾아내는 날엔 이름을 바꿀 거야?"),
(MA, "Alors il faut un nom qui dise ce qu'on fait. On ne vend pas des élections. On aide des gens à débattre et à décider, en public.", "그럼 우리가 하는 일을 말해 주는 이름이 필요해. 우린 선거를 파는 게 아니야. 사람들이 공개적으로 토론하고 결정하도록 돕는 거지."),
(I, "En public... sur la place publique. Comment les Grecs appelaient-ils ça, déjà ?", "공개적으로... 광장에서. 그리스 사람들은 그걸 뭐라고 불렀더라?"),
(MA, "L'agora. La place où les citoyens d'Athènes se réunissaient pour discuter, commercer et voter. Enfin, ceux qui avaient le droit de voter.", "아고라. 아테네 시민들이 모여서 토론하고, 장사하고, 투표하던 광장. 뭐, 투표권이 있던 사람들만이지만."),
(I, "Agora. Court, lisible dans toutes les langues, et ça ne promet la victoire à personne. « Agora Stratégies » ?", "아고라. 짧고, 어느 언어로도 읽히고, 누구에게도 승리를 약속하지 않아. '아고라 스트라테지'는 어때?"),
(MA, "Agora Stratégies. Adopté à l'unanimité des associés présents. Le chat s'abstient.", "아고라 스트라테지. 출석 주주 만장일치로 가결. 고양이는 기권."),
(None, "10 h. On sonne. Hélène entre avec une pochette cartonnée et un sachet de la boulangerie.", "오전 10시. 초인종이 울린다. 엘렌이 서류 봉투와 빵집 봉지를 들고 들어온다."),
(H, "Bonjour, mes enfants. Des chouquettes pour les fondateurs. Pas encore de Kbis, et déjà une cliente à onze heures et demie : vous mettez la charrue avant les bœufs. Remarquez, c'est souvent ainsi que commencent les meilleurs cabinets.", "안녕, 얘들아. 창업자들을 위한 슈케트야. 법인 등기부 등본도 없는데 11시 반에 벌써 고객이라니, 일의 순서가 뒤바뀌었구나. 하긴, 가장 좋은 회사들은 흔히 그렇게 시작하지."),
(I, "Le premier jour d'Agora Stratégies. Le nom a cinq minutes d'existence.", "아고라 스트라테지의 첫날이에요. 이름은 태어난 지 5분 됐고요."),
(H, "Agora... Ambitieux sans être prétentieux. J'approuve. Voyons les statuts : société par actions simplifiée, deux associés, capital social de dix mille euros, entièrement libéré ?", "아고라라... 야심 차지만 거만하진 않네. 마음에 들어. 정관을 보자. 단순주식회사, 주주 두 명, 자본금 1만 유로, 전액 납입했고?"),
(MA, "Cinq mille chacun, déposés lundi à la banque. Le certificat de dépôt des fonds est dans la pochette verte. Reste la question de la présidence.", "각자 5천 유로씩, 월요일에 은행에 예치했어요. 자본금 예치 증명서는 초록색 봉투에 있어요. 남은 건 대표를 누가 맡느냐죠."),
(I, "Moi, présidente. Mathieu, directeur général. Il a été le patron pendant un an ; c'est mon tour.", "제가 대표(président)요. 마티외는 대표이사(directeur général)고요. 1년 동안 마티외가 사장이었으니 이번엔 제 차례죠."),
(H, "Cinquante-cinquante, donc. C'est élégant, et c'est dangereux. Qu'avez-vous prévu pour le jour où vous ne serez pas d'accord ?", "그러니까 50 대 50이구나. 멋지지만 위험해. 둘의 의견이 갈리는 날을 위해 뭘 준비해 뒀니?"),
(I, "On en discute jusqu'à minuit. C'est notre règle.", "자정까지 토론하죠. 그게 우리 규칙이에요."),
(H, "Ma chérie, une règle de couple n'est pas une clause statutaire. Deux associés à parts égales qui se bloquent, c'est une société paralysée, quelle que soit la qualité de leurs sentiments.", "얘야, 커플의 규칙은 정관 조항이 아니야. 지분이 똑같은 주주 둘이 막히면 회사는 마비돼. 두 사람의 감정이 아무리 좋더라도."),
(MA, "Que nous conseilles-tu ?", "그럼 어떻게 하라고 조언해 줄래?"),
(H, "Un pacte d'associés, à côté des statuts. Une médiation obligatoire en cas de blocage, puis une clause de sortie : celui qui part cède ses actions à un prix fixé par un expert. Pas par l'autre. Et surtout pas par moi.", "정관과 별도로 주주 간 협약을 맺어. 교착 상태가 되면 조정을 의무화하고, 그다음엔 이탈 조항. 떠나는 사람은 전문가가 정한 가격에 지분을 넘기는 거야. 상대방이 정하는 게 아니라. 그리고 절대 내가 정하는 것도 아니고."),
(I, "Une clause de divorce avant même le mariage. Très romantique.", "결혼도 하기 전에 이혼 조항이라니. 아주 로맨틱하네요."),
(H, "C'est précisément parce que vous vous aimez qu'il faut l'écrire maintenant, à froid. Une fois la crise venue, on n'écrit plus rien de raisonnable.", "바로 너희가 서로 사랑하기 때문에 지금, 냉정할 때 써 둬야 하는 거야. 일단 위기가 오면 아무도 합리적인 건 못 써."),
(MA, "D'accord. Mais nous voulons aussi inscrire trois principes : indépendance, transparence, vérité.", "알겠어요. 그런데 저희는 원칙 세 가지도 넣고 싶어요. 독립성, 투명성, 진실."),
(H, "Expliquez-moi ce que vous mettez derrière chaque mot. En politique, les grands mots ne coûtent rien.", "단어마다 무슨 뜻을 담는지 설명해 봐. 정치에서 거창한 말은 공짜거든."),
(I, "Indépendance : nous choisissons nos clients, aucune exclusivité avec un parti ou un mouvement, et le droit de partir si l'on nous demande de franchir une ligne. Transparence : nous disons pour qui nous travaillons et combien nous sommes payés.", "독립성은 우리가 고객을 고르고, 어떤 정당이나 운동과도 독점 계약을 하지 않으며, 선을 넘으라는 요구를 받으면 떠날 권리가 있다는 거예요. 투명성은 누구를 위해 일하는지, 얼마를 받는지 밝히는 것이고요."),
(MA, "Et vérité : pas de fausse information, pas d'attaque sur la vie privée, et aucun engagement de campagne dont on ne sache pas comment le financer.", "그리고 진실은, 허위 정보 금지, 사생활 공격 금지, 재원 조달 방법을 모르는 공약은 하나도 내걸지 않는다는 거예요."),
(H, "Alors faites-en une charte, annexée à chaque contrat. Le client doit la signer avant de vous payer, pas la découvrir après. Encore faut-il que vous sachiez dire non, le jour venu.", "그럼 그걸 헌장으로 만들어서 모든 계약서에 첨부해. 고객은 돈을 내기 전에 서명해야지, 나중에 알게 되면 안 돼. 물론 그날이 오면 '아니요'라고 말할 줄 알아야 하겠지만."),
(H, "Deux mises en garde, enfin. Ne travaillez jamais gratuitement pour un candidat : une prestation offerte par une société, c'est un don d'une personne morale, et c'est interdit. Et vos honoraires passeront par le mandataire financier, dans un compte de campagne examiné ligne par ligne.", "마지막으로 주의할 점 두 가지. 후보를 위해 절대 공짜로 일하지 마. 회사가 무상으로 제공한 용역은 법인의 기부라서 금지야. 그리고 너희 보수는 회계 책임자를 거쳐서, 한 줄 한 줄 심사받는 선거 회계에 들어가."),
(MA, "Et un petit conseil entre amis, autour d'un café ?", "그럼 커피 마시면서 친구끼리 주는 작은 조언은요?"),
(H, "Un conseil entre amis, c'est un café. Une stratégie, c'est une prestation. Retenez ceci : dans ce métier, vous ne vendez pas des idées, vous engagez votre réputation. Et une réputation, ça ne se rachète pas.", "친구끼리의 조언은 커피 한 잔이지. 전략은 용역이고. 이것만 기억해. 이 일에서 너희는 아이디어를 파는 게 아니라 평판을 거는 거야. 그리고 평판은 돈 주고 다시 살 수 없어."),

# ---------- 3. La première cliente ----------
(None, "11 h 30. Agnès Rivière est assise sur le canapé. Figaro l'observe du haut de la bibliothèque. Hélène est repartie, les statuts sont signés.", "오전 11시 30분. 아녜스 리비에르가 소파에 앉아 있다. 피가로가 책장 꼭대기에서 그녀를 지켜본다. 엘렌은 돌아갔고, 정관은 서명을 마쳤다."),
(AG, "Alors c'est ici, le siège d'Agora Stratégies ? J'ai connu pire : mon père a créé son entreprise dans un garage.", "그러니까 여기가 아고라 스트라테지 본사군요? 더한 곳도 봤어요. 저희 아버지는 차고에서 회사를 차리셨거든요."),
(I, "Bienvenue, madame Rivière. Avant de parler contrat, nous aimerions vous poser quelques questions. Certaines vous paraîtront naïves.", "환영합니다, 리비에르 씨. 계약 얘기를 하기 전에 몇 가지 여쭤보고 싶어요. 어떤 건 순진해 보일 수도 있어요."),
(AG, "Ce sont les plus dangereuses. Allez-y.", "그런 질문이 제일 위험하죠. 하세요."),
(MA, "Pourquoi vous présentez-vous ? Vous avez vendu votre entreprise ; vous pourriez profiter de la vie.", "왜 출마하시나요? 회사를 파셨으니 인생을 즐기실 수도 있잖아요."),
(AG, "Profiter de quoi, dans une ville qui se vide ? J'ai dirigé la Robinetterie Rivière pendant vingt ans, cent quarante salariés. Je l'ai vendue l'an dernier à un groupe régional, à condition que les emplois restent à Valmont. Ils y sont restés. Mais autour de l'usine, tout ferme.",
     "텅 비어 가는 도시에서 뭘 즐겨요? 전 20년 동안 리비에르 밸브 회사를 경영했어요. 직원 140명이었죠. 작년에 일자리를 발몽에 남긴다는 조건으로 지역 그룹에 팔았어요. 일자리는 남았어요. 그런데 공장 주변은 다 문을 닫고 있어요."),
(I, "Qu'est-ce qui ferme, concrètement ?", "구체적으로 뭐가 문을 닫나요?"),
(AG, "Les commerces de la rue Nationale. L'antenne de l'hôpital, il y a quatre ans. La filature Bellanger, il y a quinze ans. Et les jeunes partent. Ma fille est médecin généraliste à Nantes ; elle ne reviendra pas, et je la comprends.",
     "나시오날 거리의 상점들이요. 병원 분원은 4년 전에, 벨랑제 방적 공장은 15년 전에 닫았어요. 그리고 젊은이들이 떠나요. 제 딸은 낭트에서 일반의로 일해요. 돌아오지 않을 거고, 전 그 애를 이해해요."),
(MA, "Supposons que vous soyez élue. Au bout de six ans, qu'aimeriez-vous avoir changé ?", "당선되셨다고 가정해 보죠. 6년 임기가 끝날 때, 무엇을 바꿔 놓았으면 좋겠어요?"),
(AG, "Je voudrais qu'on cesse de dire « à Valmont, il n'y a plus rien ». Je voudrais qu'un jeune de vingt ans puisse y trouver un travail, un médecin et une raison de rester.",
     "'발몽엔 이제 아무것도 없어'라는 말을 그만 듣고 싶어요. 스무 살 청년이 여기서 일자리와 의사, 그리고 남을 이유를 찾을 수 있으면 좋겠어요."),
(I, "Vous n'avez jamais exercé de mandat, pas même de conseillère municipale. Sans doute vos adversaires vous le reprocheront-ils dès la première semaine.", "선출직을 맡아 보신 적이 없죠. 시의원조차도요. 아마 상대 후보들이 첫 주부터 그 점을 지적할 거예요."),
(AG, "Je sais. Jean-Claude Mercier est maire depuis dix-huit ans ; il connaît chaque rond-point par son prénom. Yasmine Kaddour, qui conduit la liste « Valmont Durable », connaît toutes les associations de la ville. Moi, je connais les entreprises et les bilans.",
     "알아요. 장클로드 메르시에는 18년째 시장이에요. 로터리 하나하나를 이름으로 부를 정도로 잘 알죠. '발몽 뒤라블' 명부를 이끄는 야스민 카두르는 시내 모든 협회를 알고요. 저는 기업과 재무제표를 알죠."),
(I, "Et le bilan de M. Mercier, comment le jugez-vous ? Soyez juste : vos électeurs le seront.", "그럼 메르시에 시장의 시정 성과는 어떻게 평가하세요? 공정하게 말씀해 주세요. 유권자들은 공정할 테니까요."),
(AG, "Il a tenu une ville qui perdait ses usines, ce n'est pas rien. Mais la dette atteint cent vingt millions d'euros, et le centre-ville se meurt. On peut avoir bien géré et ne plus avoir de projet.", "공장을 잃어 가는 도시를 버텨 냈죠. 대단한 일이에요. 하지만 부채가 1억 2천만 유로에 이르고 도심은 죽어 가요. 관리를 잘했어도 더는 비전이 없을 수 있죠."),
(MA, "Et votre liste, où en est-elle ?", "그럼 후보님 명부는 어디까지 진행됐나요?"),
(AG, "« Valmont Ensemble ». Une liste citoyenne, sans étiquette. Il me faut cinquante-trois noms, en alternant une femme et un homme. J'en ai trente et un.", "'발몽 앙상블'이요. 정당 소속 없는 시민 명부예요. 여자와 남자를 번갈아 53명이 필요한데, 31명 모았어요."),
(I, "Trente et un sur cinquante-trois, à moins de six mois du scrutin. C'est un chantier à part entière.", "선거를 6개월도 안 남기고 53명 중 31명이라. 그것만으로도 큰 과제네요."),
(AG, "Je vais être directe : ce que j'attends de vous, c'est que vous m'aidiez à gagner.", "솔직하게 말할게요. 제가 두 분께 바라는 건 이기도록 도와주시는 거예요."),
(MA, "Cela, nous ne pouvons pas vous le promettre. Personne d'honnête ne le peut. Nous pouvons vous promettre une méthode, un diagnostic franc et une campagne dont vous n'aurez pas à rougir, quel qu'en soit le résultat.",
     "그건 약속드릴 수 없습니다. 정직한 사람이라면 아무도 못 하죠. 저희가 약속드릴 수 있는 건 방법론, 솔직한 진단, 그리고 결과가 어떻든 부끄럽지 않을 캠페인입니다."),
(AG, "Et si je vous demandais de fouiller un peu dans le passé de Mercier ? Tout le monde traîne des casseroles.", "그럼 메르시에의 과거를 좀 파 달라고 하면요? 누구나 구린 구석 하나쯤은 있잖아요."),
(I, "Alors nous refuserions. Son bilan, ses votes, ses budgets, ses déclarations publiques : tout cela se discute, et nous l'analyserons avec rigueur. Sa vie privée ne nous regarde pas, et elle ne regarde pas les électeurs.",
     "그럼 거절하겠습니다. 그의 시정 성과, 표결, 예산, 공개 발언은 모두 토론 대상이고, 저희가 엄밀하게 분석할 거예요. 하지만 사생활은 저희가 상관할 일이 아니고, 유권자가 상관할 일도 아닙니다."),
(AG, "Bonne réponse. C'était un test. Mon ancien banquier me faisait le même coup.", "좋은 대답이에요. 시험해 본 거예요. 예전 거래 은행 담당자가 저한테 똑같은 수를 쓰곤 했죠."),
(MA, "Voici notre charte : indépendance, transparence, vérité. Elle sera annexée au contrat. Si la campagne s'en écarte un jour, nous nous retirons.", "저희 헌장입니다. 독립성, 투명성, 진실. 계약서에 첨부될 거예요. 언젠가 캠페인이 여기서 벗어나면 저희는 물러납니다."),
(AG, "« Aucun engagement sans chiffrage ni financement identifié. » Vous allez me faire renoncer à la moitié de mes idées.", "'비용 산정과 재원이 확인되지 않은 공약은 내걸지 않는다.' 제 아이디어 절반은 포기하게 만드시겠네요."),
(I, "Peut-être à un tiers. Mais celles qui resteront, vous pourrez les défendre devant n'importe qui.", "아마 3분의 1 정도요. 하지만 남는 공약은 누구 앞에서든 지켜 내실 수 있을 거예요."),
(AG, "Alors je vous propose une chose : venez voir Valmont. Aujourd'hui. Ma voiture est en bas ; nous y serons vers quinze heures.", "그럼 제안 하나 할게요. 발몽을 보러 오세요. 오늘요. 차가 아래 있어요. 3시쯤이면 도착할 거예요."),
(None, "Agnès descend chercher sa voiture. Inès et Mathieu restent seuls, face au tableau blanc encore posé par terre.", "아녜스가 차를 가지러 내려간다. 이네스와 마티외만 남아, 아직 바닥에 놓인 화이트보드를 마주한다."),
(I, "Alors ? Franchement.", "그래서? 솔직하게."),
(MA, "Elle n'a pas prononcé le mot « pouvoir » une seule fois. Elle a parlé de sa fille, de ses salariés et d'une rue.", "그분은 '권력'이라는 말을 한 번도 안 했어. 딸 얘기, 직원 얘기, 그리고 거리 하나 얘기를 했지."),
(I, "Et elle a testé notre éthique au bout de vingt minutes, ce qui me plaît. Mais une liste incomplète, aucune expérience, un maire sortant installé depuis dix-huit ans... Sur le papier, c'est la campagne la plus difficile qui soit.",
    "그리고 20분 만에 우리 윤리를 시험했지. 그건 마음에 들어. 하지만 미완성 명부, 경험 전무, 18년째 자리 잡은 현직 시장... 서류상으로는 더없이 어려운 캠페인이야."),
(MA, "Sur le papier, Verdier était l'entreprise la plus difficile qui soit.", "서류상으로는 베르디에도 더없이 어려운 회사였지."),
(I, "Ne me ressors pas Verdier à chaque fois. On ne signe rien avant d'avoir vu la ville. Et on fixe notre prix ce soir, devant elle, pas dans la voiture.", "매번 베르디에 얘기 꺼내지 마. 도시를 보기 전엔 아무것도 서명 안 해. 그리고 가격은 차 안에서 말고, 오늘 저녁에 그분 앞에서 정해."),

# ---------- 4. Terrain : Valmont-sur-Loire ----------
(None, "15 h 10. Valmont-sur-Loire, la rue Nationale. Une rue piétonne, des vitrines blanchies, des panneaux « À louer ».", "오후 3시 10분. 발몽쉬르루아르, 나시오날 거리. 보행자 거리에 하얗게 칠한 진열창들, '임대' 팻말들."),
(MA, "Vingt-neuf... trente... trente et une vitrines vides depuis la place de la mairie.", "스물아홉... 서른... 시청 광장에서부터 빈 가게가 서른한 곳이야."),
(AG, "Sur cent vingt commerces environ. Quand j'étais petite, le samedi, on ne pouvait pas marcher sur ce trottoir tellement il y avait de monde.", "상점이 120곳 정도인데요. 제가 어릴 땐 토요일이면 이 보도를 걸을 수가 없을 정도로 사람이 많았어요."),
(I, "Où sont partis les clients ?", "손님들은 어디로 갔죠?"),
(AG, "Au centre commercial de la rocade, ouvert il y a douze ans. Et sur internet, comme partout.", "12년 전에 생긴 외곽 순환도로 쇼핑센터로요. 그리고 다른 데처럼 인터넷으로요."),
(JP, "Madame Rivière ! Vous nous amenez des Parisiens ? Méfiez-vous, ils vont me demander du lait d'avoine.", "리비에르 씨! 파리 사람들을 데려오셨어요? 조심하세요, 귀리 우유 달라고 할 거예요."),
(AG, "Joël Picard, le Café des Halles. Trente ans derrière ce comptoir, et autant d'avis sur tout.", "카페 데 알의 조엘 피카르예요. 이 카운터 뒤에서 30년, 모든 일에 대한 의견도 그만큼이죠."),
(I, "Bonjour, monsieur. Selon vous, qu'est-ce qui manque le plus, ici ?", "안녕하세요. 여기에 가장 부족한 게 뭐라고 보세요?"),
(JP, "Du monde, le midi. Avant, j'avais les ouvrières de la filature. Aujourd'hui, j'ai trois retraités et un livreur. Et plus de médecin : le mien est parti à la retraite, personne ne l'a remplacé.", "점심때 손님이요. 예전엔 방적 공장 여공들이 왔죠. 지금은 은퇴자 셋이랑 배달원 하나예요. 그리고 의사도 없어요. 제 주치의가 은퇴했는데 아무도 그 자리를 안 채웠어요."),
(MA, "Vous irez voter, en mars ?", "3월에 투표하러 가실 거예요?"),
(JP, "Ça dépendra de la météo et de mon humeur. Ils viennent tous serrer des mains en février, et on ne les revoit plus en avril.", "날씨랑 기분에 달렸죠. 다들 2월에 와서 악수하고, 4월이면 다시는 안 보여요."),
(AG, "Il a raison, Joël. Et je risque de faire exactement pareil, si personne ne m'en empêche.", "조엘 말이 맞아요. 그리고 아무도 말리지 않으면 저도 똑같이 할지 몰라요."),
(None, "16 h. Au bord de la Loire, la filature Bellanger : quatre étages de briques, des fenêtres murées, une haute cheminée. Une vieille dame promène son chien le long des grilles.", "오후 4시. 루아르 강가의 벨랑제 방적 공장. 4층짜리 벽돌 건물, 벽돌로 막은 창문들, 높은 굴뚝. 노부인 한 명이 철책을 따라 개를 산책시키고 있다."),
(AG, "La filature Bellanger. Mille quatre cents salariés en 1975, trois cent vingt à la fermeture, en 2011. Mon père y livrait des pièces.", "벨랑제 방적 공장이에요. 1975년엔 직원이 1,400명, 2011년 문 닫을 때는 320명이었어요. 저희 아버지가 여기에 부품을 납품했죠."),
(MA, "Le bâtiment est magnifique. À qui appartient-il aujourd'hui ?", "건물이 정말 멋지네요. 지금은 누구 소유예요?"),
(AG, "À la ville, depuis huit ans. Elle l'a racheté pour un euro symbolique. Depuis, chaque campagne promet d'en faire quelque chose.", "8년 전부터 시 소유예요. 상징적인 1유로에 사들였죠. 그 뒤로 선거 때마다 여길 어떻게 하겠다는 공약이 나와요."),
(OD, "Et chaque élu repart avec sa promesse sous le bras. Bonjour, Agnès.", "그리고 당선자마다 공약을 옆구리에 낀 채 떠나 버리지. 안녕, 아녜스."),
(AG, "Odette ! Odette Charrier a travaillé trente-huit ans ici. Odette, je vous présente Inès et Mathieu ; ils vont m'aider pour la campagne.", "오데트! 오데트 샤리에 씨는 여기서 38년을 일하셨어요. 오데트, 이네스와 마티외예요. 선거 캠페인을 도와줄 분들이에요."),
(OD, "Des conseillers de Paris ? Ma pauvre Agnès, tu as besoin de gens d'ici, pas de communicants.", "파리에서 온 컨설턴트라고? 딱하기도 하지, 아녜스. 너한테 필요한 건 이 동네 사람들이지, 홍보 전문가가 아니야."),
(MA, "Vous avez raison sur un point, madame : nous ne connaissons pas Valmont. C'est pour cela que nous venons écouter avant de dire quoi que ce soit.", "한 가지는 맞는 말씀이에요. 저희는 발몽을 몰라요. 그래서 무슨 말이든 하기 전에 들으러 온 거예요."),
(OD, "Écouter... Alors écoutez ça : aux dernières municipales, je ne suis pas allée voter. Pour la première fois de ma vie. Et dans mon immeuble, nous étions la majorité.", "듣는다라... 그럼 이거나 들어 봐요. 지난 시장 선거 때 난 투표하러 안 갔어. 평생 처음으로. 그리고 우리 건물에선 그런 사람이 대다수였지."),
(I, "Pourquoi ?", "왜요?"),
(OD, "Parce que ça ne change rien. La filature a fermé, le bâtiment s'abîme, et les affiches se ressemblent toutes. Remarquez, Mercier a sauvé la piscine et la maternelle du quartier ; je ne dis pas qu'il n'a rien fait. Je dis qu'on ne nous demande jamais rien.",
     "아무것도 안 바뀌니까. 공장은 닫았고, 건물은 망가져 가고, 포스터는 다 똑같아. 하긴 메르시에가 동네 수영장이랑 유치원은 지켰지. 아무것도 안 했다는 말은 아니야. 우리한테 뭘 물어본 적이 한 번도 없다는 거지."),
(I, "Je viens de vérifier. Participation aux dernières municipales : quarante-deux pour cent. Cinquante-huit pour cent d'abstention, Mathieu.", "방금 확인했어. 지난 시장 선거 투표율이 42%야. 기권율이 58%라고, 마티외."),
(MA, "Alors le vrai adversaire, ce n'est ni Mercier ni Kaddour. C'est l'abstention. Une campagne qui ne parle qu'à ceux qui votent déjà passe à côté de la majorité de la ville.", "그럼 진짜 상대는 메르시에도 카두르도 아니야. 기권이지. 이미 투표하는 사람들한테만 말하는 캠페인은 도시의 다수를 놓치게 돼."),
(OD, "Si vous arrivez à me faire retourner dans l'isoloir, jeune homme, je vous fais une tarte aux poires.", "젊은이, 나를 다시 기표소에 들어가게 만들면 서양배 타르트를 구워 주지."),
(MA, "Je ne vous demande pas de voter pour Mme Rivière, madame. Je vous demande de voter. Pour qui vous voudrez.", "리비에르 씨를 찍어 달라는 게 아니에요. 투표를 해 주셨으면 하는 거예요. 원하시는 누구에게든요."),

# ---------- 5. Décision : la permanence, le contrat, la déclaration ----------
(None, "18 h. Une ancienne boutique de chaussures, rue Nationale, qu'Agnès vient de louer pour sa permanence. Des chaises pliantes, une table sur tréteaux, une affiche encore roulée.", "오후 6시. 나시오날 거리의 옛 신발 가게. 아녜스가 선거 사무소로 쓰려고 막 빌린 곳이다. 접이식 의자, 받침대 위에 올린 탁자, 아직 말려 있는 포스터."),
(AG, "Ma future permanence. J'ai choisi une vitrine vide exprès. Bon, parlons argent, puisque vous y tenez.", "제 선거 사무소가 될 곳이에요. 일부러 빈 가게를 골랐어요. 자, 돈 얘기 하죠. 두 분이 그렇게 원하시니."),
(I, "Quel est votre budget de campagne ?", "선거 예산이 얼마인가요?"),
(AG, "Soixante-dix mille euros. Un apport personnel, un prêt bancaire et des dons, que j'espère nombreux.", "7만 유로요. 개인 출자금, 은행 대출, 그리고 많이 들어오길 바라는 후원금이요."),
(I, "Les dons sont plafonnés à quatre mille six cents euros par personne, et seules les personnes physiques peuvent donner. Ni votre ancienne entreprise, ni vos fournisseurs, ni Agora.", "후원금은 1인당 4,600유로가 상한이고, 개인만 기부할 수 있어요. 예전 회사도, 거래처도, 아고라도 안 돼요."),
(AG, "Mon mandataire financier me l'a déjà répété trois fois. Votre prix ?", "제 회계 책임자가 벌써 세 번이나 말했어요. 두 분 보수는요?"),
(MA, "Vingt-quatre mille euros hors taxes pour six mois, jusqu'au second tour. Diagnostic, programme, préparation des débats, organisation de la campagne de terrain.", "6개월간, 결선 투표까지 세전 2만 4천 유로입니다. 진단, 공약, 토론 준비, 현장 캠페인 조직까지요."),
(AG, "C'est moins que je ne le pensais. Je peux aller jusqu'à quarante mille, si cela vous permet d'y consacrer plus de temps.", "생각보다 적네요. 시간을 더 쏟을 수 있다면 4만까지 드릴 수 있어요."),
(I, "Non. Au-delà d'un tiers de votre budget, vous financeriez des consultants plutôt qu'une campagne. Gardez cet argent pour vos tracts, vos réunions publiques et vos bénévoles.", "아니요. 예산의 3분의 1을 넘으면 캠페인이 아니라 컨설턴트에게 돈을 대는 셈이 돼요. 그 돈은 전단, 공개 집회, 자원봉사자들을 위해 남겨 두세요."),
(AG, "Une consultante qui refuse de l'argent... Je savais que je ne m'étais pas trompée.", "돈을 거절하는 컨설턴트라니... 제 눈이 틀리지 않았네요."),
(MA, "En revanche, deux conditions. La charte est annexée au contrat. Et c'est vous qui parlez : nous écrivons avec vous, jamais à votre place.", "대신 조건이 두 가지 있습니다. 헌장을 계약서에 첨부할 것. 그리고 말하는 사람은 후보님이라는 것. 저희는 함께 쓰지, 절대 대신 쓰지 않습니다."),
(AG, "Accordé. Mais votre société n'existe pas encore, si je comprends bien ?", "좋아요. 그런데 내가 이해한 게 맞다면 두 분 회사는 아직 존재하지 않는 거죠?"),
(I, "Juridiquement, elle est en formation. Le dossier d'immatriculation a été déposé ce midi. Nous signons au nom d'Agora Stratégies en formation, et la société reprendra le contrat dès qu'elle aura été immatriculée. C'est prévu par la loi, et ce sera écrit noir sur blanc.",
    "법적으로는 설립 중인 회사예요. 등기 서류는 오늘 정오에 제출했어요. 설립 중인 아고라 스트라테지 명의로 서명하고, 회사는 등기가 끝나는 즉시 계약을 승계합니다. 법에 정해진 절차고, 계약서에 분명히 적어 둘 거예요."),
(AG, "Vous avez un client avant d'avoir un Kbis. Vous mettez la charrue avant les bœufs.", "법인 등기부 등본도 나오기 전에 고객부터 생겼네요. 일의 순서가 뒤바뀌었어요."),
(MA, "Hélène nous l'a dit ce matin, presque mot pour mot. Elle a ajouté que c'est souvent ainsi que commencent les meilleurs cabinets.", "엘렌이 오늘 아침에 거의 똑같은 말을 했어요. 그런데 가장 좋은 회사들은 흔히 그렇게 시작한다고 덧붙였죠."),
(AG, "Une dernière chose. J'ai écrit ma déclaration de candidature ; je dois la lire samedi prochain devant la presse locale. Vous voulez l'entendre ?", "마지막으로 하나 더요. 출마 선언문을 써 왔어요. 다음 주 토요일에 지역 언론 앞에서 읽어야 해요. 들어 보실래요?"),
(MA, "Avec plaisir.", "기꺼이요."),
(AG, "« Valmontaises, Valmontais. Je ne suis pas une professionnelle de la politique. Je suis une cheffe d'entreprise qui a su prendre des décisions difficiles. Je suis une femme qui aime cette ville. Je suis celle qui va redresser Valmont. »",
     "'발몽 시민 여러분. 저는 직업 정치인이 아닙니다. 저는 어려운 결정을 내릴 줄 알았던 기업인입니다. 저는 이 도시를 사랑하는 여성입니다. 저는 발몽을 다시 일으켜 세울 사람입니다.'"),
(I, "Quatre fois « je » en quatre phrases, et une promesse de redressement. Puis-je être franche ?", "네 문장에 '저는'이 네 번, 그리고 회생의 약속. 솔직하게 말씀드려도 될까요?"),
(AG, "C'est pour cela que je vous paie. Vingt-quatre mille euros, si j'ai bien compris.", "그러라고 돈을 드리는 거죠. 제가 이해한 게 맞다면 2만 4천 유로요."),
(I, "Vous parlez beaucoup de vous et très peu des habitants. Et « redresser » laisse entendre que vous seule savez ce qui ne va pas. Or vous n'avez encore interrogé personne.", "후보님 얘기는 많고 주민 얘기는 거의 없어요. 그리고 '다시 일으켜 세운다'는 말은 무엇이 잘못됐는지 후보님 혼자만 안다는 뜻으로 들려요. 그런데 아직 아무에게도 물어보지 않으셨잖아요."),
(MA, "Votre meilleure phrase, vous l'avez prononcée ce matin, chez nous : un travail, un médecin et une raison de rester. Ça, c'est une déclaration.", "후보님의 가장 좋은 문장은 오늘 아침 저희 집에서 하셨어요. 일자리, 의사, 그리고 남을 이유. 그게 바로 선언이에요."),
(AG, "C'est vrai que je l'ai dite... Et vous proposez quoi ?", "그 말을 하긴 했죠... 그래서 뭘 제안하시는데요?"),
(MA, "De commencer par écouter plutôt que par un programme. Pendant un mois, nous allons à la rencontre de la ville : un sondage, une cinquantaine d'entretiens, les marchés, les associations, les quartiers où l'on ne vote plus. Le programme viendra ensuite.",
     "공약보다 경청으로 시작하자는 거예요. 한 달 동안 도시를 만나러 다니는 거죠. 여론조사, 인터뷰 50건 정도, 시장, 협회, 그리고 더는 투표하지 않는 동네들. 공약은 그다음이에요."),
(I, "Et nous mesurons tout : votre point de départ, vos forces, vos faiblesses. Si le sondage dit que personne ne vous connaît, nous vous le dirons tel quel.", "그리고 모든 걸 측정할 거예요. 출발점, 강점, 약점. 여론조사에서 아무도 후보님을 모른다고 나오면, 그대로 말씀드릴 거예요."),
(AG, "« Avant de vous dire ce que je ferai, je viens vous demander ce que vous vivez. » Ça vous va, comme première phrase ?", "'제가 무엇을 할지 말씀드리기 전에, 여러분이 어떻게 살고 계신지 여쭈러 왔습니다.' 첫 문장으로 어때요?"),
(MA, "C'est bien meilleur que tout ce que nous aurions pu écrire.", "저희가 쓸 수 있었던 그 어떤 문장보다 훨씬 낫네요."),
(AG, "Alors c'est décidé. Je signe. ... Avec quel stylo ?", "그럼 결정됐어요. 서명할게요. ...어떤 펜으로 하죠?"),
(None, "Inès sort de son sac un stylo-plume bleu nuit, gravé d'une ancre et des lettres « TM ».", "이네스가 가방에서 닻과 « TM » 글자가 새겨진 남색 만년필을 꺼낸다."),
(I, "Avec celui-ci. Mon père dit qu'une signature doit coûter un peu d'encre et un peu de courage.", "이걸로요. 저희 아버지는 서명에는 잉크 조금과 용기 조금이 들어야 한다고 하세요."),
(AG, "Alors en voici un peu des deux. ... Voilà. Premier contrat d'Agora Stratégies.", "그럼 둘 다 조금씩 드리죠. ...됐어요. 아고라 스트라테지의 첫 계약이에요."),
(MA, "Et première cliente. Merci de nous avoir fait confiance avant même que nous ayons un bureau.", "그리고 첫 고객이시죠. 사무실도 생기기 전에 믿어 주셔서 감사합니다."),

# ---------- 6. Le soir : chez nous ----------
(None, "23 h 10. Oberkampf. Les cartons n'ont pas bougé. Figaro dort sur l'oreiller de Mathieu.", "밤 11시 10분. 오베르캉프. 상자들은 그대로다. 피가로가 마티외의 베개 위에서 자고 있다."),
(MA, "Il a passé la journée sur mon oreiller. Je suis officiellement le deuxième occupant de cet appartement.", "녀석이 하루 종일 내 베개 위에 있었네. 난 공식적으로 이 집의 두 번째 거주자야."),
(I, "Le troisième, après lui et moi. Tiens, avant que j'oublie.", "세 번째지. 녀석이랑 나 다음으로. 자, 잊어버리기 전에."),
(None, "Elle lui tend un trousseau : deux clés et un petit porte-clés en forme de bateau.", "그녀가 열쇠 꾸러미를 건넨다. 열쇠 두 개와 작은 배 모양 열쇠고리."),
(I, "Le double des clés. Le porte-clés vient de Marseille ; il traînait dans la boîte à souvenirs de mon père.", "여벌 열쇠야. 열쇠고리는 마르세유에서 온 거야. 아빠 추억 상자에 굴러다니던 거."),
(MA, "Un associé avec des clés. On progresse.", "열쇠 있는 공동 창업자라. 발전하고 있네."),
(I, "Un associé qui est chez lui. Ce n'est plus chez moi, Mathieu. C'est chez nous.", "자기 집에 사는 공동 창업자지. 이제 여긴 내 집이 아니야, 마티외. 우리 집이야."),
(MA, "Tu l'as dit sans y penser, ou tu l'avais préparé ?", "생각 없이 나온 말이야, 아니면 준비했던 거야?"),
(I, "Je l'ai répété dans la voiture d'Agnès pendant deux heures. Ne te moque pas.", "아녜스 차 안에서 두 시간 동안 연습했어. 놀리지 마."),
(MA, "Je ne me moque pas. Il reste juste une chose à faire avant de dormir.", "안 놀려. 자기 전에 딱 하나만 더 하면 돼."),
(None, "Il accroche le tableau blanc au-dessus de la table, entre la bibliothèque et la fenêtre, et sort de sa poche le vieux marqueur vert.", "그가 식탁 위, 책장과 창문 사이에 화이트보드를 건다. 그리고 주머니에서 낡은 초록 마커를 꺼낸다."),
(I, "Ton grand-père serait content. Son marqueur a déménagé plus souvent que toi.", "너희 할아버지가 좋아하시겠다. 그 마커는 너보다 이사를 더 많이 다녔어."),
(MA, "Première question. Quel est le vrai problème ?", "첫 번째 질문. 진짜 문제는 무엇인가?"),
(I, "Une ville où plus d'un électeur sur deux ne croit plus que voter serve à quelque chose.", "유권자 둘 중 한 명 이상이 투표가 무슨 소용이 있다고 더는 믿지 않는 도시."),
(MA, "Deuxième question. Qui décide ?", "두 번째 질문. 누가 결정하는가?"),
(I, "Agnès, pour sa campagne. Nous, pour nos principes. Et pour le reste...", "아녜스는 자기 캠페인을, 우리는 우리 원칙을. 그리고 나머지는..."),
(MA, "Les électeurs. Pas nous.", "유권자들이. 우리가 아니라."),
(I, "Écris-le. En gros. Pour les jours où on l'oubliera.", "그거 써. 크게. 우리가 그걸 잊어버릴 날들을 위해서."),
(None, "Il écrit en capitales, sous la question : « LES ÉLECTEURS. PAS NOUS. »", "그가 질문 아래에 대문자로 적는다. « 유권자들이. 우리가 아니라. »"),
(MA, "Et la troisième. Que fait-on lundi ?", "그리고 세 번째. 월요일엔 뭘 하지?"),
(I, "Lundi, on retourne à Valmont. On lance le sondage, on prépare cinquante entretiens, et on dort sur place : j'ai trouvé une chambre d'hôtes au bord de la Loire.", "월요일엔 발몽으로 돌아가. 여론조사를 시작하고, 인터뷰 50건을 준비하고, 거기서 자는 거야. 루아르 강가에 민박을 하나 찾았어."),
(MA, "Une chambre d'hôtes au bord de la Loire... Notre premier déplacement de couple officiel.", "루아르 강가의 민박이라... 공식 커플로서 첫 출장이네."),
(I, "Ne t'emballe pas, ce sera surtout des tableaux croisés. Viens te coucher, Strasbourg. Et récupère ton oreiller, si tu l'oses.", "들뜨지 마. 대부분 교차 분석표일 거야. 자러 와, 스트라스부르. 그리고 감히 할 수 있으면 네 베개 되찾아 와."),
(MA, "Figaro. Pousse-toi. Je suis chez moi.", "피가로. 비켜. 여긴 내 집이야."),
(None, "Figaro ouvre un œil et ne bouge pas. Inès éclate de rire et éteint le salon. Sur le tableau, en vert : « Les électeurs. Pas nous. »", "피가로는 한쪽 눈만 뜨고 꿈쩍도 하지 않는다. 이네스가 웃음을 터뜨리며 거실 불을 끈다. 화이트보드 위에 초록 글씨로, « 유권자들이. 우리가 아니라. »"),
]

VOCAB = [
("B2", "les statuts (d'une société)", "(회사의) 정관", "항상 복수. rédiger / signer / déposer les statuts. 회사의 '헌법'으로, 목적·자본·지배 구조를 정한다."),
("B2", "une SAS (société par actions simplifiée)", "단순주식회사", "프랑스 스타트업·컨설팅사에서 가장 흔한 법인 형태. 주주 1명이면 SASU. 대표는 président(e), 필요하면 directeur général을 둔다."),
("B2", "le capital social (entièrement libéré)", "자본금 (전액 납입된)", "libérer le capital = 약정한 출자금을 실제로 납입하다. le dépôt des fonds(자본금 예치) → certificat de dépôt."),
("C1", "un pacte d'associés", "주주 간 협약", "정관과 별도의 비공개 계약. 지분 양도·교착 해소·이탈 조건 등을 정한다. 정관(statuts)은 공개, 협약은 비공개라는 점이 핵심 차이."),
("C1", "une clause de sortie", "이탈(퇴장) 조항", "공동 주주 중 한 명이 떠날 때의 지분 처리 방식. céder ses actions à un prix fixé par un expert."),
("B2", "le Kbis / l'immatriculation", "법인 등기부 등본 / (법인) 등기", "extrait Kbis = 회사의 '신분증'. immatriculer une société au registre du commerce et des sociétés(RCS)."),
("C1", "une société en formation", "설립 중인 회사", "등기 전에 회사 이름으로 맺은 계약은 등기 후 회사가 승계(reprendre les engagements)할 수 있다."),
("B2", "noir sur blanc", "(문서로) 분명하게, 명시적으로", "C'est écrit noir sur blanc. 말이 아니라 서면으로 남긴다는 뉘앙스."),
("B2", "mettre la charrue avant les bœufs", "일의 순서를 뒤바꾸다", "직역 '소보다 쟁기를 앞에 두다'. 준비가 끝나기 전에 다음 단계를 시작할 때."),
("B2", "le scrutin", "투표, 선거", "à moins de six mois du scrutin. scrutin de liste(명부식 투표), scrutin à deux tours(2회 투표제). 뉴스·공문의 격식 어휘."),
("B2", "une liste (sans étiquette)", "(선거) 명부 (정당 소속 없는)", "conduire / mener une liste = 명부를 이끌다(1번 후보). étiquette = 정당 꼬리표."),
("B2", "un mandat / exercer un mandat", "(선출직) 임기, 직무 / 선출직을 맡다", "un mandat de six ans. 경영의 mandat(위임)와 같은 단어지만 정치에서는 '선출직 임기'."),
("B2", "le maire sortant", "현직 시장", "sortant = 임기를 마치고 재선에 나서는. le député sortant, le président sortant."),
("B2", "l'abstention / la participation", "기권(투표 불참) / 투표율", "58 % d'abstention = 투표율 42 %. 표결의 '기권'(s'abstenir)과 같은 단어(복습)."),
("B1", "l'isoloir", "기표소", "프랑스 투표소의 칸막이 부스. passer par l'isoloir는 비밀 투표의 상징."),
("C1", "le mandataire financier", "(선거) 회계 책임자", "후보 대신 모든 수입·지출을 관리하는 법정 대리인. 선거 자금은 반드시 이 사람을 거친다."),
("C1", "le compte de campagne", "선거 비용 회계 보고서", "선거 후 감독 기관(CNCCFP)이 심사. 컨설턴트 보수도 여기에 기재된다."),
("C1", "un don d'une personne morale", "법인 기부", "personne morale(법인) ↔ personne physique(자연인). 프랑스 선거에서 법인의 후원은 금지."),
("B2", "la permanence (électorale)", "선거 사무소", "후보·의원이 시민을 맞이하는 사무실. tenir une permanence = 정해진 시간에 민원을 받다."),
("B2", "traîner des casseroles", "약점·추문을 달고 다니다", "구어. 직역 '냄비를 끌고 다니다'. avoir des casseroles라고도 한다."),
("B2", "un chantier à part entière", "그 자체로 하나의 큰 과제", "à part entière = 완전한, 독립된 자격의. un membre à part entière(정식 회원)."),
("B2", "prendre possession des lieux", "(장소를) 차지하다, 입주하다", "공식적으로는 '인도받아 입주하다'. 여기선 고양이의 영역 표시를 익살스럽게."),
("B1", "faire de la place", "자리를 만들다, 공간을 비우다", "J'ai fait de la place dans la salle de bains. 동거·이사 필수 표현."),
("B1", "le double des clés", "여벌 열쇠", "faire faire un double = 열쇠를 복사하다. 함께 사는 사이의 상징적 선물."),
("B2", "Ne t'emballe pas.", "들뜨지 마, 앞서가지 마", "s'emballer = (말이) 날뛰다 → 흥분하다, 지나치게 열광하다."),
]

GRAM = [
("C1", "문어 도치: Encore faut-il que... / Sans doute... -t-il",
 "« Encore faut-il que vous sachiez dire non, le jour venu. » « Sans doute vos adversaires vous le reprocheront-ils dès la première semaine. » encore, sans doute, peut-être, aussi(그래서), ainsi 같은 부사가 문두에 오면 주어·동사를 도치하는 것이 격식체다. 명사 주어는 그대로 두고 대명사(-ils)를 덧붙이는 '복합 도치'를 쓴다. encore faut-il que는 '하지만 그러려면 ~해야 한다'는 단서를 달 때 쓰며 뒤에 접속법이 온다. 구어라면 « Mais il faut encore que... », « Vos adversaires vont sûrement vous le reprocher »."),
("C1", "quel(le) que soit / quel qu'en soit + 접속법",
 "« quelle que soit la qualité de leurs sentiments » « une campagne dont vous n'aurez pas à rougir, quel qu'en soit le résultat » quel que는 뒤에 오는 명사(주어)에 성·수를 일치시킨다(la qualité → quelle). en은 '그것의'(= de la campagne)를 받는다. quoique(비록 ~지만)와 quoi que(무엇을 ~하든), quel que(어떤 ~이든)를 구분하자."),
("B2", "접속법을 부르는 접속사: à condition que, avant que, pour que",
 "« Je l'ai vendue l'an dernier à un groupe régional, à condition que les emplois restent à Valmont. » « avant même que nous ayons un bureau » « Supposons que vous soyez élue. » 조건(à condition que, pourvu que), 시간의 선행(avant que), 가정(supposons que)은 아직 실현되지 않은 일이므로 접속법을 쓴다. 반면 après que는 원칙적으로 직설법이다."),
("C1", "최상급·유일성 뒤의 접속법: le plus... qui soit",
 "« Sur le papier, c'est la campagne la plus difficile qui soit. » « ne croit plus que voter serve à quelque chose » 최상급(le plus, le seul, le premier) 뒤 관계절에서는 주관적 평가를 나타내기 위해 접속법을 쓴다. qui soit는 '존재하는 것 가운데'라는 관용적 강조. 또 croire가 부정(ne... plus croire que)일 때도 의심을 나타내 접속법(serve)을 쓴다."),
("B2", "비교의 허사 ne: moins que je ne le pensais",
 "« C'est moins que je ne le pensais. » plus / moins / autre que 뒤의 비교절에 쓰이는 ne는 부정의 뜻이 없는 '허사 ne(ne explétif)'다. le는 앞 내용 전체를 받는 중성 대명사. 구어에서는 « C'est moins que ce que je pensais »가 흔하지만, 격식 있는 협상에서는 허사 ne가 품위를 더한다. 같은 허사 ne는 avant que, à moins que, craindre que 뒤에도 나타난다."),
("B2", "가정: si + 반과거 → 조건법 현재",
 "« Et si je vous demandais de fouiller un peu dans le passé de Mercier ? — Alors nous refuserions. » « Au-delà d'un tiers de votre budget, vous financeriez des consultants plutôt qu'une campagne. » 반과거 si절은 실현 가능성이 낮거나 가상인 조건이다. 두 번째 문장처럼 si절 대신 전치사구(au-delà de, sans, avec)가 조건을 대신할 수도 있다. 비교: « C'est bien meilleur que tout ce que nous aurions pu écrire »(조건법 과거 = 일어나지 않은 과거의 가능성)."),
("C1", "명사화와 행정·법률 문체",
 "« Le certificat de dépôt des fonds » « Le dossier d'immatriculation a été déposé ce midi. » « Aucun engagement sans chiffrage ni financement identifié. » 동사(déposer, immatriculer, chiffrer, financer)를 명사로 바꾸면 문장이 짧고 객관적·공식적으로 들린다. 헌장·계약·공약 문서의 기본 문체다. sans... ni...는 두 요소를 모두 부정한다(= 비용 산정도 재원도 없는)."),
("C1", "연설 수사: 반복(anaphore)과 삼항 구조",
 "« Je suis une cheffe d'entreprise... Je suis une femme qui aime cette ville. Je suis celle qui va redresser Valmont. » 같은 말로 문장을 시작하는 반복법은 힘이 있지만, 이네스의 지적처럼 주어가 '나'면 자기 자랑이 된다. 반면 « un travail, un médecin et une raison de rester »처럼 구체적인 명사 세 개를 점점 무게가 커지게 나열하는 삼항 구조(구체 → 구체 → 추상)는 프랑스 연설에서 가장 기억에 남는 형식이다. « Avant de vous dire ce que je ferai, je viens vous demander ce que vous vivez. »는 대구(dire / demander, ferai / vivez)로 청중을 주어로 만든다."),
]

CULTURE = [
("프랑스에서 SAS 회사 만들기",
 "SAS(société par actions simplifiée)는 자본금 최소액이 없고(1유로부터 가능) 정관으로 지배 구조를 자유롭게 정할 수 있어 프랑스 창업자들이 가장 많이 고르는 형태다. 절차는 대략 정관 작성·서명 → 자본금 예치(은행 등, 예치 증명서 발급) → 법정 공고 신문에 설립 공고(annonce légale) → 온라인 단일 창구(guichet unique)를 통한 등기 신청 → 상업·회사 등기부(RCS) 등록과 Kbis 발급 순서다. 등기 전에 '설립 중인 회사' 이름으로 맺은 계약은 등기 후 회사가 승계할 수 있으며, 공동 주주들은 정관과 별도로 비공개 주주 간 협약(pacte d'associés)을 맺어 교착 상태나 이탈에 대비하는 경우가 많다."),
("프랑스 시장 선거(municipales)의 구조",
 "시의원은 6년마다 선출되며, 일정 인구 이상의 코뮌에서는 남녀를 번갈아 배치한 명부에 투표하는 2회 투표제를 쓴다. 1차에서 과반을 얻으면(일정 투표율 조건 포함) 바로 끝나고, 그렇지 않으면 1차 득표 10% 이상의 명부가 결선에 나가며, 5% 이상을 얻은 명부는 결선 진출 명부와 합병할 수 있다. 1위 명부가 의석의 절반을 먼저 가져가는 '다수 프리미엄' 덕분에 시정이 안정적으로 꾸려지고, 시장은 주민이 직접 뽑는 것이 아니라 새로 구성된 시의회가 선출한다. 인구에 따라 시의원 수가 정해져 있어(인구 6만~8만 코뮌은 53명) 명부를 채우는 일 자체가 큰 과제다."),
("선거 자금 규칙과 컨설턴트",
 "프랑스는 선거 자금을 엄격하게 규제한다. 일정 규모 이상 선거의 후보는 회계 책임자(mandataire financier)를 지정해 모든 수입과 지출을 그를 통해 처리하고, 선거 뒤 선거 비용 회계(compte de campagne)를 제출하면 독립 기관인 선거비용·정치자금 국가위원회(CNCCFP)가 심사한다. 지출에는 인구에 비례한 상한이 있고, 개인 후원은 한 선거당 1인 4,600유로까지이며, 기업 등 법인의 후원은 현금이든 무상 용역이든 금지된다. 그래서 컨설팅사는 반드시 정상 가격으로 계약하고, 그 보수는 후보의 선거 비용으로 신고된다."),
]
