# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, B = "Inès", "Mathieu", "Baptiste"
SI, AL, AG, NO = "Simone", "Albert", "Agnès", "Noémie"
MY, MO, KE = "Maryse", "Moussa", "Kenza"

META = {
    "part": 3, "ep": 32,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Écouter la ville",
    "title_ko": "도시의 목소리 듣기",
    "place": "발몽쉬르루아르 근교 민박 « La Closerie des Saules » · 그랑뤼의 옛 잡화점을 개조한 리비에르 선거 사무실 · 일요일 장터 · 청소년 센터 « L'Escale » · 문 닫은 병원 분원 · 루아르 강둑 / 11월 중순, 금요일~일요일",
    "chars": "이네스, 마티외, 아녜스 리비에르(시민 명부 « Valmont Ensemble » 후보), 노에미 그랑제(자원봉사 코디네이터), 시몬·알베르 슈브리에(민박 주인 부부 — 전직 병원 분원 간호사, 전직 섬유 공장 반장), 마리즈(장터 치즈 상인), 무사(청소년 센터 활동가), 켄자(19세, 구직 중), 바티스트 모렐(메르시에 캠프 컨설턴트)",
    "work": "선거 여론조사 해석(600명, 메르시에 31%·리비에르 22%·카드두르 14%·미정 33%, 오차범위 약 ±4포인트, 리비에르 인지도 38%), 주민 심층 인터뷰 50건 분석(의료 공백·청년 실업·도심 공동화), 현장 검증, '공약' 이전의 '진단' 보고",
    "life": "민박 주인 부부와의 아침 식사, 벽난로 옆 밤샘 자료 읽기, 일요일 장터의 염소 치즈, 바티스트와의 재회, 루아르 강둑 산책 — 파리와 지방, 이네스의 마르세유, 마티외의 콜마르, 처음으로 말한 « chez nous »",
    "focus": "설문·통계 해석(échantillon, méthode des quotas, marge d'erreur, notoriété, indécis), 지역·공공정책 어휘(désert médical, centre de santé, rocade), 간접화법과 시제 일치, 문어 도치(encore faut-il que, sans doute... -t-il), 명사화, 접속법(pour peu que, à moins que, bien que), soit... soit, 분열문 ce dont / ce qui... c'est",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "제33화 Un programme qui tient — 설거지와 피가로 화장실을 둘러싼 집안일 분담 다툼, 발몽의 예산과 1억 2천만 유로 부채 앞에서 공약 12개를 7개로 줄이는 작업, 그리고 소피아의 합류.",
}

D = [
# ---------- 1. Ouverture : la chambre d'hôtes ----------
(None, "Vendredi, mi-novembre, 8 h. La Closerie des Saules, une chambre d'hôtes dans un hameau à huit kilomètres de Valmont-sur-Loire. Du brouillard sur les prés. Dans la cuisine, une table en chêne, des confitures maison et une cafetière qui siffle.",
       "11월 중순 금요일, 오전 8시. 발몽쉬르루아르에서 8킬로미터 떨어진 작은 마을의 민박 '라 클로즈리 데 솔'. 풀밭 위에 안개가 깔려 있다. 부엌에는 참나무 식탁, 집에서 만든 잼, 그리고 칙칙 소리를 내는 커피포트."),
(SI, "Bonjour ! Bien dormi ? Asseyez-vous, le café arrive. Les confitures, c'est coing et mirabelle, tout vient du jardin.", "안녕하세요! 잘 주무셨어요? 앉으세요, 커피 곧 나와요. 잼은 마르멜로랑 미라벨이에요. 전부 정원에서 난 거예요."),
(MA, "Comme un bébé. Le silence, ici, c'est presque inquiétant pour des Parisiens. On n'a entendu qu'une chouette de toute la nuit.", "아기처럼 잤어요. 여기 고요함은 파리 사람한테는 거의 불안할 정도네요. 밤새 부엉이 한 마리 소리밖에 못 들었어요."),
(AL, "C'est la hulotte du grand saule. Elle était là avant nous, elle sera là après. Vous venez pour les élections, c'est ça ? Ça se sait vite, au hameau.", "큰 버드나무에 사는 올빼미예요. 우리보다 먼저 있었고, 우리 뒤에도 있을 거요. 선거 때문에 오셨죠? 이 마을에선 소문이 금방 퍼져요."),
(I, "Pour la campagne de Mme Rivière, oui. Mais cette semaine, nous ne venons pas parler. Nous venons écouter.", "네, 리비에르 씨 캠페인 때문에요. 그런데 이번 주에는 말하러 온 게 아니에요. 들으러 왔어요."),
(AL, "Écouter ? Ça nous changera. D'habitude, les politiques arrivent avec leurs réponses avant d'avoir entendu les questions.", "듣는다고요? 별일이네. 보통 정치하는 사람들은 질문을 듣기도 전에 답부터 들고 오거든요."),
(SI, "Albert, laisse-les manger... Il a été contremaître à la filature pendant vingt-cinq ans. Depuis qu'elle a fermé, il a un avis sur tout.", "알베르, 식사 좀 하시게 둬요... 이 양반이 방적 공장에서 25년 동안 반장을 했어요. 공장이 문 닫은 뒤로는 모든 일에 할 말이 있죠."),
(AL, "J'avais déjà un avis sur tout avant. Simplement, maintenant, j'ai le temps de le donner.", "전에도 모든 일에 할 말은 있었지. 그냥 이제는 그 말을 할 시간이 생긴 것뿐이야."),
(MA, "Alors donnez-le-nous. Qu'est-ce qui a le plus changé à Valmont, depuis la fermeture ?", "그럼 저희한테 해 주세요. 공장이 문 닫은 뒤로 발몽에서 가장 많이 바뀐 게 뭔가요?"),
(AL, "Le samedi. Avant, le centre-ville était plein à craquer. Aujourd'hui, les jeunes partent à Tours ou à Nantes, et les autres font leurs courses au centre commercial, sur la rocade.", "토요일이요. 예전엔 시내가 터져 나갈 듯 붐볐지. 지금은 젊은 애들은 투르나 낭트로 떠나고, 나머지는 순환도로 옆 쇼핑센터에서 장을 봐요."),
(SI, "Et la santé. J'ai été infirmière trente ans à l'antenne de l'hôpital. Depuis qu'elle a fermé, il y a deux ans, pour accoucher ou pour une urgence la nuit, c'est quarante-cinq minutes de route.", "그리고 의료요. 제가 병원 분원에서 30년 동안 간호사로 일했어요. 2년 전에 문을 닫은 뒤로는 아이를 낳으려 해도, 밤에 응급 상황이 생겨도 차로 45분이에요."),
(I, "Quarante-cinq minutes... Accepteriez-vous qu'on en reparle plus longuement, madame Chevrier ? Pas pour la campagne : pour comprendre.", "45분이라니... 슈브리에 부인, 이 얘기를 좀 더 길게 나눠 주실 수 있을까요? 캠페인 때문이 아니라, 이해하고 싶어서요."),
(SI, "Pourvu que vous ne me mettiez pas sur une affiche, oui. Dimanche après-midi, je vous y emmène, si vous voulez.", "저를 포스터에 넣지만 않는다면요. 원하시면 일요일 오후에 거기 데려가 드릴게요."),
(None, "Simone retourne à ses fourneaux. Albert regarde Inès et Mathieu par-dessus ses lunettes.", "시몬이 다시 화덕 앞으로 간다. 알베르가 안경 너머로 이네스와 마티외를 바라본다."),
(AL, "Et vous deux, vous êtes mariés ? Simone a hésité à vous donner la chambre aux deux lits.", "그런데 두 분은 결혼했소? 시몬이 침대 두 개짜리 방을 드릴까 고민했거든."),
(MA, "Associés. Et... ensemble. Le grand lit était parfait, merci.", "동업자예요. 그리고... 함께 살아요. 큰 침대 방, 완벽했어요. 고맙습니다."),
(AL, "Associés et ensemble ? Méfiez-vous. Un mariage, ça se défait. Une association, il faut un notaire.", "동업자에 연인이라? 조심해요. 결혼은 풀 수 있어도, 동업은 공증인이 있어야 풀리거든."),

# ---------- 2. Le QG : le sondage ----------
(None, "10 h. Grand-Rue, à Valmont. Le QG de campagne d'Agnès Rivière occupe une ancienne mercerie. Sur la vitrine : « Valmont Ensemble ». Noémie Granger, vingt-huit ans, empile des questionnaires.",
       "오전 10시. 발몽의 그랑뤼. 아녜스 리비에르의 선거 사무실은 옛 잡화점 자리에 있다. 유리창에는 « Valmont Ensemble ». 스물여덟 살의 노에미 그랑제가 설문지를 쌓고 있다."),
(AG, "Bienvenue au QG. Une ancienne mercerie, oui, ne riez pas. C'était le local le moins cher de la Grand-Rue. Il y en a six autres à louer, dans la même rue.", "선거 사무실에 오신 걸 환영해요. 옛 잡화점이에요, 웃지 마세요. 그랑뤼에서 제일 싼 가게였어요. 같은 거리에 세놓은 가게가 여섯 곳이나 더 있어요."),
(MA, "Six vitrines vides dans une seule rue... C'est déjà un diagnostic.", "한 거리에 빈 진열창이 여섯 개라... 그것만으로도 이미 진단이네요."),
(AG, "Je vous présente Noémie Granger, qui coordonne nos bénévoles. C'est elle qui a organisé les entretiens avec Mathieu.", "노에미 그랑제를 소개할게요. 우리 자원봉사자들을 총괄하고 있어요. 마티외 씨와 함께 인터뷰를 조직한 사람이에요."),
(NO, "Bonjour. Trois semaines, huit bénévoles, cinquante entretiens complets d'une heure chacun. Et beaucoup de cafés refusés pour ne pas arriver en retard au suivant.", "안녕하세요. 3주 동안 자원봉사자 여덟 명이 한 시간짜리 인터뷰를 쉰 건 끝까지 했어요. 다음 집에 늦지 않으려고 커피도 엄청 사양했고요."),
(I, "Merci, Noémie. Commençons par le sondage, arrivé hier soir. Six cents personnes interrogées du 3 au 8 novembre, par téléphone et en ligne, selon la méthode des quotas : âge, sexe, profession, quartier.",
    "고마워요, 노에미. 어젯밤에 도착한 여론조사부터 보죠. 11월 3일부터 8일까지 전화와 온라인으로 600명을 조사했고, 할당 표본 방식이에요. 나이, 성별, 직업, 거주 지역별로요."),
(AG, "Allez-y franchement. À mon âge, on préfère les mauvaises nouvelles aux bonnes surprises.", "솔직하게 말해 주세요. 내 나이쯤 되면 기분 좋은 깜짝 소식보다 나쁜 소식이 나아요."),
(I, "Intentions de vote au premier tour : Jean-Claude Mercier, trente et un pour cent. Vous, vingt-deux. Yasmine Kaddour, quatorze. Et trente-trois pour cent d'indécis.", "1차 투표 지지 의향입니다. 장클로드 메르시에 31%. 리비에르 씨 22%. 야스민 카드두르 14%. 그리고 미정이 33%입니다."),
(AG, "Vingt-deux... Neuf points de retard. Je m'attendais à pire, et j'espérais mieux.", "22%라... 9포인트 뒤처졌네요. 더 나쁠 줄 알았는데, 더 좋기를 바랐어요."),
(NO, "Mais neuf points, c'est dans la marge d'erreur, non ? On peut dire que c'est serré.", "그래도 9포인트면 오차범위 안 아니에요? 박빙이라고 할 수 있잖아요."),
(I, "Malheureusement, non. Sur six cents personnes, la marge d'erreur est d'environ quatre points au maximum, plutôt trois pour un score autour de vingt pour cent. Même dans l'hypothèse la plus favorable pour vous, l'écart demeure.",
    "안타깝지만 아니에요. 600명 표본이면 오차범위는 최대 4포인트 정도고, 20%대 지지율이면 3포인트쯤이에요. 리비에르 씨에게 가장 유리한 가정을 해도 격차는 남아요."),
(MA, "Mais il est vrai aujourd'hui. Un sondage est une photographie, pas une prévision. Et celle-ci a été prise quatre mois avant le premier tour.", "하지만 그건 오늘의 사실이에요. 여론조사는 사진이지 예언이 아니거든요. 그리고 이 사진은 1차 투표 넉 달 전에 찍힌 거고요."),
(AG, "Mercier est maire depuis dix-huit ans. Trois mandats. Les gens le préfèrent à moi, voilà tout.", "메르시에는 18년째 시장이에요. 세 번 연임했죠. 사람들이 나보다 그 사람을 좋아하는 거예요. 그뿐이에요."),
(I, "Les gens ne vous connaissent pas, nuance. C'est le chiffre le plus important de l'étude : trente-huit pour cent des Valmontais savent qui vous êtes. Pour Mercier, quatre-vingt-quatorze.", "사람들이 리비에르 씨를 모르는 거예요. 미묘하지만 다르죠. 이 조사에서 가장 중요한 숫자예요. 발몽 시민의 38%만 리비에르 씨가 누군지 압니다. 메르시에는 94%고요."),
(I, "Et parmi ceux qui vous connaissent, six sur dix ont une opinion favorable de vous. Votre problème n'est pas l'image, c'est la notoriété.", "그리고 리비에르 씨를 아는 사람 가운데 열에 여섯은 호감을 갖고 있어요. 문제는 이미지가 아니라 인지도예요."),
(NO, "Mais c'est génial ! On le publie : « Six Valmontais sur dix qui connaissent Agnès Rivière l'apprécient. »", "그거 대단한데요! 이걸 공개해요. '아녜스 리비에르를 아는 발몽 시민 열 명 중 여섯이 그녀를 좋아한다.'"),
(MA, "Non. On ne publie pas un morceau de sondage parce qu'il nous arrange. Soit on publie tout, avec la notice complète, soit on ne publie rien.", "안 돼요. 우리한테 유리하다고 여론조사의 한 조각만 공개하진 않아요. 조사 고지 사항까지 전부 공개하든지, 아니면 아무것도 공개하지 않든지예요."),
(AG, "Ils ont raison, Noémie. Et Mercier aurait beau jeu de publier le reste.", "이분들 말이 맞아요, 노에미. 게다가 그러면 메르시에가 나머지를 공개하기 딱 좋겠죠."),
(AG, "Et les indécis ? Un tiers de la ville qui attend qu'on vienne le chercher, c'est une chance, non ?", "그럼 미정층은요? 누가 데리러 와 주기를 기다리는 도시의 3분의 1이라니, 기회 아닌가요?"),
(I, "C'est ce qu'on aimerait croire. Mais plus de la moitié d'entre eux déclarent qu'ils ne sont pas sûrs d'aller voter. Ce ne sont pas des hésitants, ce sont des découragés.", "그렇게 믿고 싶죠. 하지만 그중 절반 넘게 투표하러 갈지 확실하지 않다고 답했어요. 망설이는 사람들이 아니라 낙담한 사람들이에요."),
(MA, "Aux dernières municipales, quarante-six pour cent seulement des inscrits se sont déplacés ; chez les moins de vingt-cinq ans, à peine un sur quatre. Votre premier adversaire, ce n'est pas Mercier : c'est l'abstention. Et sur ce point, les entretiens en disent plus long que les chiffres.",
     "지난 지방선거 때 등록 유권자의 46%만 투표하러 나왔어요. 25세 미만은 겨우 넷에 하나였고요. 리비에르 씨의 첫 번째 상대는 메르시에가 아니라 기권이에요. 그리고 그 점에선 숫자보다 인터뷰가 훨씬 많은 걸 말해 줘요."),
(NO, "Les gens nous ouvraient la porte en soupirant : « Encore un tract ? » Et quand on répondait qu'on venait leur poser des questions, ils nous faisaient entrer.", "사람들이 한숨을 쉬면서 문을 열었어요. '또 전단지예요?' 그런데 질문하러 왔다고 하면 들어오라고 했어요."),
(I, "Côté sondage, la santé arrive en tête des priorités avec trente-quatre pour cent, devant l'emploi, vingt-sept, le centre-ville, quinze, et la sécurité, douze.", "여론조사에서 우선순위 1위는 의료로 34%예요. 그다음이 일자리 27%, 도심 15%, 치안 12%고요."),
(MA, "Et dans nos cinquante entretiens, le même ordre : dix-neuf personnes ont parlé d'abord de santé, quatorze d'emploi et des jeunes, onze du centre-ville, six d'autre chose.", "인터뷰 50건에서도 순서가 같아요. 열아홉 명은 먼저 의료 얘기를 했고, 열네 명은 일자리와 청년, 열한 명은 도심, 여섯 명은 다른 주제였어요."),
(AG, "La santé en premier... Moi qui comptais faire campagne sur l'emploi. C'est mon métier, l'entreprise.", "의료가 먼저라니... 난 일자리로 캠페인을 하려고 했는데. 기업이 내 전문이잖아요."),
(I, "C'est votre force, et nous la garderons. Mais un candidat qui parle de ce qu'il sait faire plutôt que de ce dont les gens souffrent, on l'écoute poliment, et on vote pour un autre.", "그건 리비에르 씨의 강점이고, 지켜 갈 거예요. 하지만 사람들이 겪는 고통보다 자기가 잘하는 것만 말하는 후보는, 다들 예의 바르게 들어 주고는 다른 사람을 찍죠."),
(AG, "Vous êtes dure, madame Marchetti.", "엄하시네요, 마르케티 씨."),
(I, "Vous m'avez demandé d'y aller franchement.", "솔직하게 말해 달라고 하셨잖아요."),
(AG, "Touché. Que proposez-vous ?", "한 방 먹었네요. 그럼 뭘 제안하시겠어요?"),
(MA, "Dimanche, nous retournons sur le terrain avec vous : le marché, l'espace jeunesse, l'ancienne antenne de l'hôpital. Dimanche soir, nous vous présentons un diagnostic. Pas encore un programme : un diagnostic.", "일요일에 리비에르 씨와 다시 현장에 나가요. 장터, 청소년 센터, 옛 병원 분원. 일요일 저녁에 진단을 보고드릴게요. 아직 공약이 아니라, 진단이요."),
(I, "Et dès ce soir, on relit les cinquante entretiens. Mot à mot.", "그리고 오늘 밤부터 인터뷰 50건을 다시 읽어요. 한 단어 한 단어씩."),

# ---------- 3. Analyse : cinquante voix ----------
(None, "22 h. Le petit salon de la chambre d'hôtes. Un feu dans la cheminée, deux infusions de tilleul, et cinquante comptes rendus d'entretien étalés sur le tapis.",
       "밤 10시. 민박의 작은 거실. 벽난로에 불이 타고, 보리수 꽃차 두 잔, 그리고 인터뷰 기록 쉰 개가 양탄자 위에 펼쳐져 있다."),
(I, "Je vais être honnête : cinquante entretiens, statistiquement, ça ne vaut rien. Ce n'est pas représentatif.", "솔직히 말할게. 인터뷰 50건은 통계적으로는 아무 가치가 없어. 대표성이 없잖아."),
(MA, "Ce n'est pas fait pour l'être. Le sondage te dit combien de gens pensent quelque chose. Les entretiens te disent pourquoi.", "대표성을 가지려고 한 게 아니야. 여론조사는 몇 명이 무엇을 생각하는지 알려 주고, 인터뷰는 왜 그렇게 생각하는지 알려 줘."),
(I, "Sans doute les chiffres ne disent-ils pas tout. Mais les anecdotes, elles, disent n'importe quoi si on les choisit bien.", "숫자가 모든 걸 말해 주지 않는 건 맞을 거야. 하지만 일화는 잘 골라내기만 하면 무슨 말이든 하게 만들 수 있어."),
(MA, "D'accord. Alors ne choisissons pas. On lit tout, et on compte. C'est ce que tu fais de mieux.", "좋아. 그럼 고르지 말자. 전부 읽고 세는 거야. 그게 네가 제일 잘하는 일이잖아."),
(I, "J'ai déjà commencé. Le mot « avant » revient soixante-trois fois. Le mot « demain », quatre.", "벌써 시작했어. '예전에'라는 말이 예순세 번 나와. '내일'은 네 번이고."),
(MA, "Soixante-trois contre quatre... Voilà une ville qui parle d'elle-même au passé.", "예순셋 대 넷이라... 자기 자신을 과거형으로 말하는 도시네."),
(I, "Lis-moi ceux que tu as faits toi-même. Pas tes conclusions : leurs phrases.", "네가 직접 한 인터뷰 읽어 줘. 네 결론 말고, 그 사람들이 한 말 그대로."),
(MA, "Une aide-soignante m'a dit qu'elle avait renoncé à se faire soigner les dents, parce que le seul dentiste qui restait ne prenait plus de nouveaux patients. Un retraité m'a demandé si quelqu'un, à Paris, savait encore où se trouvait Valmont. Et un lycéen m'a expliqué qu'il partirait dès qu'il aurait son bac, et qu'il ne reviendrait pas.", "한 요양보호사가 그러더라. 남은 치과 의사 한 명이 새 환자를 더는 안 받아서 치아 치료를 포기했다고. 한 은퇴자는 파리에 있는 누군가가 아직도 발몽이 어디 있는지 알기는 하냐고 묻더라. 그리고 한 고등학생은 바칼로레아 따자마자 떠날 거고 돌아오지 않을 거라고 했어."),
(I, "Ça, c'est la phrase que Noémie voudra mettre sur une affiche. Et c'est précisément pour ça qu'il ne faut pas.", "그건 노에미가 포스터에 넣고 싶어 할 문장이네. 그리고 바로 그래서 넣으면 안 되는 거고."),
(MA, "On est d'accord. Ces gens nous ont confié quelque chose, ils ne nous ont pas donné un slogan.", "동감이야. 이 사람들은 우리한테 뭔가를 털어놓은 거지, 구호를 준 게 아니야."),
(I, "Bon. Sur le fond, maintenant. Je pense qu'Agnès doit faire campagne sur l'emploi. C'est là qu'elle est crédible, et c'est là qu'un maire a de vrais leviers.", "좋아. 이제 본론. 난 아녜스가 일자리로 캠페인을 해야 한다고 생각해. 거기서 신뢰를 얻을 수 있고, 시장이 실제로 쓸 수 있는 수단도 거기 있어."),
(MA, "La santé arrive en tête partout : dans le sondage, dans les entretiens, au petit déjeuner chez Simone. Si on l'ignore, à quoi bon avoir écouté ?", "의료는 어디서나 1위야. 여론조사에서도, 인터뷰에서도, 시몬 씨네 아침 식탁에서도. 그걸 무시하면 들은 게 다 무슨 소용이야?"),
(I, "Parce que l'hôpital ne dépend pas de la mairie ! C'est l'agence régionale de santé qui décide. Promettre de rouvrir l'antenne, ce serait un mensonge, et tu le sais.", "병원은 시청 소관이 아니니까! 결정은 지역보건청이 해. 분원을 다시 열겠다고 약속하는 건 거짓말이야. 너도 알잖아."),
(MA, "Je n'ai jamais dit qu'il fallait promettre la réouverture. Je dis qu'il faut répondre.", "분원을 다시 연다고 약속하자는 말은 한 적 없어. 대답은 해야 한다는 거지."),
(I, "Répondre, ce n'est pas promettre ? Explique-moi la différence, devant une salle de deux cents personnes en colère.", "대답하는 거랑 약속하는 게 다르다고? 화난 사람 이백 명이 모인 강당 앞에서 그 차이를 설명해 봐."),
(MA, "Répondre, c'est dire ce qu'un maire peut faire, et aussi ce qu'il ne peut pas faire. Écouter, ce n'est pas obéir.", "대답한다는 건 시장이 할 수 있는 일과 함께 할 수 없는 일도 말하는 거야. 듣는다는 게 시키는 대로 한다는 뜻은 아니잖아."),
(I, "C'est exactement ce qui me fait peur dans ce métier. Écouter les gens pour leur dire ce qu'ils veulent entendre... il y a un mot pour ça.", "바로 그게 이 일에서 내가 무서워하는 거야. 사람들이 듣고 싶어 하는 말을 해 주려고 그들의 말을 듣는 거... 그걸 부르는 말이 있지."),
(MA, "Le clientélisme. Ou la démagogie, selon le budget. Et c'est pour ça qu'on a écrit « vérité » parmi nos trois principes.", "선심 정치. 예산 규모에 따라선 포퓰리즘이고. 그래서 우리가 세 가지 원칙에 '진실'을 넣은 거잖아."),
(I, "Alors soyons vrais jusqu'au bout. Une ville endettée à hauteur de cent vingt millions ne paiera pas des médecins comme on distribue des tracts.", "그럼 끝까지 진실하자. 부채가 1억 2천만 유로인 도시는 전단지 돌리듯 의사 월급을 줄 수 없어."),
(MA, "Je ne connais pas encore le coût. Toi non plus. Mais certaines villes salarient des médecins dans un centre de santé municipal. Ça mérite au moins d'être étudié.", "아직 비용은 몰라. 너도 모르고. 그런데 어떤 도시들은 시립 보건 센터에서 의사를 월급제로 고용해. 적어도 검토해 볼 가치는 있어."),
(I, "Étudié, oui. Pas promis avant que je l'aie chiffré.", "검토는 좋아. 내가 비용을 계산하기 전에 약속하는 건 안 돼."),
(MA, "Ça me va. Et l'emploi, je ne l'oublie pas. Quatorze entretiens sur cinquante, ce n'est pas rien.", "좋아. 그리고 일자리도 잊지 않았어. 50건 중 14건이면 적은 게 아니야."),
(I, "Ce qui m'intrigue, c'est que les jeunes ne parlent presque jamais de salaire. Ils parlent de bus, de permis, d'horaires.", "내가 궁금한 건, 청년들이 월급 얘기는 거의 안 한다는 거야. 버스, 운전면허, 시간표 얘기를 해."),
(MA, "Tu as raison... Trois entretiens mentionnent une zone d'activité, les Grands-Prés, à douze kilomètres. On n'a pas creusé.", "맞네... 인터뷰 세 건에서 12킬로미터 떨어진 '그랑프레' 산업단지 얘기가 나와. 우린 깊이 파고들지 않았어."),
(I, "Alors voilà trois hypothèses à vérifier dimanche. Un : le problème de santé, ce n'est pas seulement l'hôpital, ce sont les médecins de ville. Deux : le chômage des jeunes est aussi une affaire de transport.", "그럼 일요일에 검증할 가설 세 개야. 하나, 의료 문제는 병원만이 아니라 동네 의원 의사들 문제다. 둘, 청년 실업은 교통 문제이기도 하다."),
(MA, "Trois : le centre-ville ne meurt pas parce que les gens n'ont plus d'argent, mais parce qu'ils n'ont plus de raison d'y venir.", "셋, 도심이 죽어 가는 건 사람들이 돈이 없어서가 아니라, 거기 올 이유가 더는 없어서다."),
(I, "Encore faut-il qu'on puisse les vérifier en une journée. Tu as vu l'heure ?", "물론 그걸 하루 만에 검증할 수 있어야겠지. 몇 시인지 봤어?"),
(MA, "Minuit passé. Tes pieds sont gelés, je le sens d'ici. Viens sous le plaid.", "자정 넘었어. 네 발 얼음장인 거 여기서도 느껴져. 담요 속으로 와."),
(I, "Tu essaies de m'éloigner de mon tableur.", "날 내 스프레드시트에서 떼어 놓으려는 거지."),
(MA, "J'essaie de te rapprocher de moi. Le tableur peut venir aussi, s'il est sage.", "날 가까이 오게 하려는 거야. 스프레드시트도 얌전하면 같이 와도 돼."),

# ---------- 4. Terrain : marché, jeunes, hôpital ----------
(None, "Dimanche, 10 h. Le marché de la place des Halles. Odeur de châtaignes grillées. Agnès serre des mains ; Inès et Mathieu restent un pas en retrait.",
       "일요일 오전 10시. 알 광장 장터. 군밤 냄새가 난다. 아녜스가 악수를 하고 다니고, 이네스와 마티외는 한 걸음 뒤에 물러서 있다."),
(MY, "Goûtez-moi ce chèvre, il est cendré, affiné trois semaines. Vous êtes avec Mme Rivière ? Elle est gentille, mais elle ne vient pas au marché depuis vingt ans, elle.", "이 염소 치즈 맛 좀 봐요. 재를 입혀서 3주 숙성한 거예요. 리비에르 씨 쪽 사람들이에요? 좋은 사람이지만, 그 양반은 20년 동안 장터에 안 왔잖아요."),
(I, "Et Mercier, il vient ?", "메르시에는 와요?"),
(MY, "Tous les dimanches, depuis dix-huit ans. Il connaît le prénom de mes petits-enfants. Ça ne veut pas dire que je vote pour lui, remarquez.", "18년째 일요일마다요. 내 손주들 이름도 알아요. 그렇다고 내가 그 사람을 찍는다는 건 아니지만요."),
(None, "Derrière eux, une voix familière.", "그들 뒤에서 낯익은 목소리가 들린다."),
(B, "Il connaît aussi le prénom de son chien. Bonjour, Inès. Bonjour, Mathieu. On peut se tutoyer de nouveau, non ? Il n'y a plus de conseil d'administration entre nous.", "개 이름도 알아요. 안녕, 이네스. 안녕, 마티외. 다시 말 놓아도 되겠지? 이제 우리 사이에 이사회는 없으니까."),
(MA, "Baptiste. Alors c'est vrai, tu conseilles Valmont Avenir.", "바티스트. 그럼 사실이구나. 네가 '발몽 아브니르'를 돕는다는 거."),
(B, "Depuis trois semaines. J'ai quitté la finance pour la politique, comme vous. Apparemment, on n'arrive pas à se quitter, tous les trois.", "3주 됐어. 나도 너희처럼 금융을 떠나 정치로 왔지. 우리 셋은 아무래도 서로 떨어질 수가 없나 봐."),
(I, "On peut se tutoyer. Ça ne veut pas dire qu'on est du même côté.", "말은 놓아도 돼. 그렇다고 같은 편이라는 뜻은 아니야."),
(B, "Je n'en demande pas tant. Un conseil gratuit, quand même : ne sous-estimez pas Mercier. Il a soixante-sept ans, mais il écoute cette ville depuis plus longtemps que vous.", "그렇게까지 바라진 않아. 그래도 공짜 충고 하나. 메르시에를 얕보지 마. 예순일곱이지만 너희보다 훨씬 오래 이 도시의 말을 들어 왔어."),
(MA, "Merci du conseil. On l'a déjà entendu ce matin, de la bouche d'une fromagère.", "충고 고마워. 오늘 아침에 치즈 장수한테서 벌써 들었어."),
(B, "Alors elle est plus rapide que moi. À bientôt, Inès. Mathieu. On se reverra aux réunions publiques... et je vous écouterai, moi aussi.", "그럼 그분이 나보다 빠르네. 또 보자, 이네스. 마티외. 공개 토론회에서 다시 만나겠지... 나도 너희 말 들을게."),
(None, "Baptiste s'éloigne vers le stand du poissonnier, où Jean-Claude Mercier, soixante-sept ans, bavarde avec une file de clients qui l'appellent par son prénom.", "바티스트가 생선 좌판 쪽으로 멀어진다. 그곳에서는 예순일곱 살의 장클로드 메르시에가 그를 이름으로 부르는 손님들 줄과 수다를 떨고 있다."),
(None, "14 h. L'Escale, l'espace jeunesse du quartier nord. Un tournoi de futsal résonne dans le gymnase. Moussa, l'animateur, les accueille avec Kenza, dix-neuf ans.",
       "오후 2시. 북쪽 동네의 청소년 센터 '레스칼'. 체육관에서 풋살 대회 소리가 울린다. 활동가 무사가 열아홉 살 켄자와 함께 두 사람을 맞는다."),
(MO, "Ici, vous avez les jeunes que personne ne sonde. Ils ne répondent pas au téléphone fixe, et pas aux questionnaires non plus.", "여기 있는 애들은 아무도 여론조사 안 하는 청년들이에요. 집 전화도 안 받고, 설문지에도 답 안 해요."),
(MA, "Kenza, vous cherchez du travail en ce moment ?", "켄자 씨, 지금 일자리를 찾고 있어요?"),
(KE, "J'ai un CAP logistique. L'entrepôt des Grands-Prés recrute cent cinquante personnes, je les ai appelés trois fois. Le problème, c'est que l'équipe du matin commence à cinq heures.", "물류 직업 자격증이 있어요. 그랑프레 물류창고가 150명을 뽑는데, 세 번이나 전화했어요. 문제는 아침 조가 새벽 5시에 시작한다는 거예요."),
(I, "Et il n'y a pas de bus à cette heure-là.", "그 시간엔 버스가 없고요."),
(KE, "Le premier part à six heures vingt, et le dernier rentre à vingt heures quinze. Sans voiture et sans permis, les Grands-Prés, c'est la Lune. J'en connais dix dans mon cas.", "첫차가 6시 20분이고, 막차가 저녁 8시 15분에 들어와요. 차도 면허도 없으면 그랑프레는 달나라예요. 저 같은 처지인 애들을 열 명은 알아요."),
(MO, "Et l'entrepôt, de son côté, se plaint de ne trouver personne. Tout le monde a raison, et rien ne bouge.", "그런데 물류창고는 또 사람을 못 구한다고 불평하죠. 다들 옳은데, 아무것도 안 움직여요."),
(KE, "On n'est pas des fainéants, vous savez. On est juste du mauvais côté de la rocade.", "우리가 게으른 게 아니에요. 그냥 순환도로 반대편에 사는 거예요."),
(None, "16 h 30. Le jour baisse. Simone les attend devant la grille d'un bâtiment de briques couvert de lierre : l'ancienne antenne hospitalière.", "오후 4시 30분. 해가 기운다. 시몬이 담쟁이로 덮인 벽돌 건물의 철문 앞에서 그들을 기다리고 있다. 옛 병원 분원이다."),
(SI, "La maternité, c'était là, au premier étage. Trois cent quarante naissances par an, dans les bonnes années. À la fin, à peine cent quatre-vingts, et plus assez d'anesthésistes pour assurer les nuits.", "산부인과가 저기, 2층에 있었어요. 좋은 시절엔 1년에 340명이 태어났죠. 마지막엔 겨우 180명이었고, 밤 근무를 맡을 마취과 의사도 모자랐어요."),
(MA, "Le maire s'était opposé à la fermeture, je crois ?", "시장은 폐쇄에 반대했다고 들었는데요?"),
(SI, "Mercier s'est battu, il faut lui rendre justice. Il est monté à la préfecture avec une pétition de neuf mille signatures. Ça n'a rien changé : la décision ne lui appartenait pas.", "메르시에는 싸웠어요. 그건 인정해야죠. 서명 9천 장을 들고 도청까지 갔어요. 아무것도 바뀌지 않았어요. 결정권이 그 사람한테 있지 않았으니까."),
(I, "Et si vous étiez maire, madame Chevrier, que feriez-vous ?", "슈브리에 부인, 부인께서 시장이라면 어떻게 하시겠어요?"),
(SI, "Je n'essaierais pas de rouvrir la maternité. Elle ne reviendra pas, et ceux qui le promettent mentent. Ce qui nous manque tous les jours, ce n'est pas l'hôpital, ce sont les médecins généralistes. Il y en avait trente-huit il y a dix ans ; il en reste vingt-quatre, et neuf ont plus de soixante ans.", "산부인과를 다시 열려고 하지는 않을 거예요. 다시 안 돌아와요. 그렇게 약속하는 사람은 거짓말하는 거고요. 우리한테 매일 부족한 건 병원이 아니라 일반의예요. 10년 전엔 서른여덟 명이었는데, 지금은 스물네 명 남았고, 그중 아홉 명이 예순이 넘었어요."),
(MA, "Des jeunes médecins accepteraient de venir ?", "젊은 의사들이 오려고 할까요?"),
(SI, "J'en connais deux, un couple d'internes à Tours. Ils viendraient, pour peu qu'on leur offre un salaire, un logement et une équipe. Ce dont ils ont peur, ce n'est pas la campagne, c'est d'être seuls.", "두 명 알아요. 투르에서 인턴 하는 부부예요. 월급, 집, 함께 일할 팀만 준다면 올 거예요. 그들이 두려워하는 건 시골이 아니라, 혼자가 되는 거예요."),
(I, "Un salaire, un logement, une équipe... Mathieu, ton centre de santé.", "월급, 집, 팀이라... 마티외, 네가 말한 보건 센터네."),

# ---------- 5. Diagnostic et décision ----------
(None, "18 h. Le QG de la Grand-Rue. Une dizaine de bénévoles sont assis sur des chaises pliantes. Au mur, trois feuilles : « Santé », « Jeunes et emploi », « Centre-ville ».",
       "오후 6시. 그랑뤼의 선거 사무실. 자원봉사자 열 명 남짓이 접이식 의자에 앉아 있다. 벽에는 종이 세 장. '의료', '청년과 일자리', '도심'."),
(MA, "Madame Rivière, vous nous avez demandé un diagnostic. Le voici, en une phrase : les Valmontais ne nous ont pas parlé de trois problèmes, mais d'un seul. Le sentiment que leur ville se vide, et que personne ne s'en soucie.",
     "리비에르 씨, 진단을 요청하셨죠. 한 문장으로 말씀드리겠습니다. 발몽 시민들은 세 가지 문제가 아니라 한 가지 문제를 이야기했습니다. 자기 도시가 비어 가는데 아무도 신경 쓰지 않는다는 느낌입니다."),
(I, "Trois symptômes, un seul mal. La raréfaction des médecins, l'isolement des jeunes, la disparition des commerces. Et derrière, une abstention qui touche plus d'un électeur sur deux.", "증상은 셋, 병은 하나입니다. 의사의 감소, 청년의 고립, 상점의 소멸. 그리고 그 뒤에는 유권자 절반이 넘는 기권이 있습니다."),
(AG, "Et le remède ?", "그럼 처방은요?"),
(I, "D'abord, ce qu'il ne faut pas faire. Ne promettez pas la réouverture de la maternité. Cela ne relève pas de la mairie, et Simone Chevrier, qui y a travaillé trente ans, nous a dit elle-même que ce serait un mensonge.", "먼저, 하지 말아야 할 일부터요. 산부인과 재개원을 약속하지 마세요. 시청 소관이 아니고, 거기서 30년 일한 시몬 슈브리에 씨도 그건 거짓말이라고 직접 말했습니다."),
(NO, "Mais on pourrait au moins rappeler que Mercier n'a pas su l'empêcher. C'est arrivé sous son mandat, après tout.", "그래도 메르시에가 그걸 막지 못했다는 건 상기시킬 수 있잖아요. 어쨌든 그 사람 임기 중에 일어난 일이니까요."),
(MA, "Il s'y est opposé publiquement, avec neuf mille signatures. L'accuser de cette fermeture serait faux, et les Valmontais le savent mieux que nous.", "그는 서명 9천 장을 들고 공개적으로 반대했어요. 폐쇄를 그의 탓으로 돌리는 건 사실이 아니고, 그건 발몽 시민들이 우리보다 더 잘 알아요."),
(AG, "Je ne gagnerai pas en racontant des histoires sur mon adversaire. S'il faut perdre, je préfère perdre en ayant dit vrai.", "상대에 대해 지어낸 얘기로 이길 생각은 없어요. 져야 한다면, 진실을 말하고 지는 편이 나아요."),
(I, "Ensuite, la santé. Nous vous proposons d'étudier un centre de santé municipal : des médecins salariés, un logement pour les internes, une équipe autour d'eux. Étudier, pas promettre, tant que nous n'avons pas chiffré.", "다음은 의료입니다. 시립 보건 센터를 검토하시길 제안합니다. 월급제 의사, 인턴용 숙소, 그리고 그들을 둘러싼 팀. 비용을 계산하기 전까지는 약속이 아니라 검토입니다."),
(AG, "Avec cent vingt millions de dette, je vous vois venir, madame Marchetti.", "부채가 1억 2천만이니, 무슨 말씀 하실지 알겠네요, 마르케티 씨."),
(I, "Alors vous savez déjà que nous ne garderons que ce qui tient. Bien qu'il soit tentant de tout promettre, une promesse non financée est une dette de plus.", "그럼 저희가 실현 가능한 것만 남길 거라는 것도 아시겠네요. 다 약속하고 싶은 유혹이 있더라도, 재원 없는 약속은 또 하나의 빚일 뿐입니다."),
(MA, "Troisièmement, les jeunes. Le chômage des moins de vingt-cinq ans atteint vingt-quatre pour cent ici, alors qu'un entrepôt cherche cent cinquante personnes à douze kilomètres. Entre les deux, il manque un bus à cinq heures du matin.",
     "셋째, 청년입니다. 여기서 25세 미만 실업률은 24%인데, 12킬로미터 떨어진 물류창고는 150명을 구하고 있어요. 그 둘 사이에 빠진 건 새벽 5시 버스 한 대입니다."),
(AG, "Les transports, c'est l'agglomération, pas seulement la ville.", "교통은 광역 도시권 소관이에요. 시만의 일이 아니죠."),
(MA, "Raison de plus pour en faire un engagement de négociation : la ville porte le dossier auprès de l'agglomération et des employeurs. Et une aide au permis de conduire, à condition d'en évaluer le coût.", "그러니까 더더욱 협상 공약으로 삼아야죠. 시가 광역 도시권과 고용주들에게 이 안건을 밀고 가는 겁니다. 그리고 비용을 따져 본다는 조건으로 운전면허 지원도요."),
(NO, "Et le centre-ville ? Les six vitrines de la Grand-Rue ?", "도심은요? 그랑뤼의 빈 진열창 여섯 개는요?"),
(I, "Un local sur cinq est vide dans l'hypercentre. Nous n'avons pas encore de réponse solide, et nous préférons vous le dire plutôt que d'en inventer une.", "도심 한복판 상가 다섯 곳 중 한 곳이 비어 있어요. 아직 탄탄한 해법은 없습니다. 지어내느니 그렇다고 말씀드리는 편이 낫습니다."),
(AG, "Vous êtes les premiers consultants que je paie pour m'entendre dire « nous ne savons pas ».", "'모르겠다'는 말을 듣자고 돈을 내는 컨설턴트는 두 분이 처음이네요."),
(I, "Si cela peut vous rassurer, c'est aussi la première fois que nous le disons à un client.", "위안이 될지 모르겠지만, 저희도 고객에게 그 말을 하는 건 처음입니다."),
(MA, "Nous ne savons pas encore. Nuance. Et c'est notre dernière proposition : continuer d'écouter, mais en public. Douze réunions de quartier d'ici février, où vous parlerez moins que vous n'écouterez.",
     "'아직' 모르는 겁니다. 미묘하지만 다르죠. 그리고 그게 저희의 마지막 제안입니다. 계속 듣되, 공개적으로 듣는 겁니다. 2월까지 동네 모임 열두 번. 거기서 리비에르 씨는 말하는 것보다 더 많이 들으셔야 합니다."),
(NO, "Et les cinquante entretiens ? On pourrait en tirer une brochure, « Ce que Valmont nous a dit ».", "그럼 인터뷰 50건은요? 그걸로 '발몽이 우리에게 한 말'이라는 소책자를 만들 수 있을 것 같은데요."),
(I, "Bonne idée, à une condition : que chaque personne relise sa citation et donne son accord, sans que son nom apparaisse. Sinon, on trahit ceux qui nous ont ouvert leur porte.", "좋은 생각이에요. 단, 조건이 있어요. 한 사람 한 사람이 자기 인용문을 다시 읽고 동의해야 하고, 이름은 나오지 않아야 해요. 그러지 않으면 문을 열어 준 사람들을 배신하는 거예요."),
(NO, "Je m'en occupe. Je retournerai les voir un par un.", "제가 맡을게요. 한 분 한 분 다시 찾아갈게요."),
(AG, "Récapitulons. Pas de fausse promesse, pas d'attaque injuste, douze réunions, une brochure, et des chiffres avant les engagements. Combien de pistes en tout ?", "정리해 보죠. 거짓 약속은 없고, 부당한 공격도 없고, 동네 모임 열두 번, 소책자 하나, 그리고 공약 전에 숫자. 방안은 모두 몇 개죠?"),
(I, "Douze pistes, issues du terrain. Aucune n'est encore chiffrée. À moins que vous ne vouliez faire campagne sur des intentions, il faudra en abandonner certaines.", "현장에서 나온 방안이 열두 개입니다. 아직 하나도 비용 계산이 안 됐어요. 의도만 가지고 캠페인을 하실 게 아니라면, 그중 일부는 버려야 할 겁니다."),
(AG, "Alors c'est décidé. Nous partons sur ce diagnostic. Et je veux le dire moi-même aux bénévoles, maintenant.", "그럼 결정했어요. 이 진단으로 갑니다. 그리고 자원봉사자들에게는 지금 내가 직접 말하고 싶어요."),
(None, "Agnès se lève et se tourne vers la salle. Les conversations s'arrêtent.", "아녜스가 일어나 사람들 쪽으로 돌아선다. 대화가 멈춘다."),
(AG, "Mes amis, pendant trois semaines, vous avez frappé à des portes que plus personne n'ouvrait. Vous n'avez rien vendu, rien promis. Vous avez écouté. Et ce que vous avez entendu, ce n'est pas de la colère, c'est de la fatigue : celle d'une ville à qui l'on ne demande plus son avis.",
    "여러분, 3주 동안 여러분은 아무도 더는 열지 않던 문들을 두드렸습니다. 아무것도 팔지 않았고, 아무것도 약속하지 않았습니다. 여러분은 들었습니다. 그리고 여러분이 들은 것은 분노가 아니라 피로였습니다. 아무도 더는 의견을 묻지 않는 도시의 피로 말입니다."),
(AG, "Je ne vous promets pas de tout réparer. Je vous promets de ne rien promettre que nous ne puissions tenir. Si Valmont doit me choisir, qu'elle me choisisse en connaissant mes limites ; c'est ainsi qu'on bâtit la confiance.", "모든 걸 고치겠다고 약속하지는 않겠습니다. 지킬 수 없는 것은 아무것도 약속하지 않겠다고 약속합니다. 발몽이 저를 선택해야 한다면, 제 한계를 알고서 선택하기를 바랍니다. 신뢰는 그렇게 쌓는 것입니다."),
(NO, "Elle n'avait jamais parlé comme ça.", "저렇게 말씀하신 적은 한 번도 없었어요."),
(MA, "Elle n'avait jamais autant écouté.", "저렇게 많이 들어 본 적도 없으셨겠죠."),
(AG, "Alors ? J'ai parlé trop longtemps ?", "어때요? 내가 너무 길게 말했나요?"),
(I, "Deux minutes. Pour une candidate qui n'avait jamais fait de discours, c'est un record de sobriété. Gardez ce ton jusqu'en mars.", "2분이요. 연설을 한 번도 해 본 적 없는 후보치고는 절제의 기록이에요. 3월까지 이 어조를 유지하세요."),

# ---------- 6. Bords de Loire ----------
(None, "21 h. La levée, le long de la Loire. Il fait froid. Les lampadaires du vieux pont se reflètent dans l'eau sombre ; la brume monte des bancs de sable.",
       "밤 9시. 루아르 강을 따라 난 둑길. 날이 춥다. 옛 다리의 가로등이 어두운 물에 비치고, 모래톱에서 안개가 피어오른다."),
(I, "Tu sais ce qui m'a frappée, aujourd'hui ? À Paris, personne ne connaît le prénom de son maire. Ici, le maire connaît le prénom des petits-enfants de la fromagère.", "오늘 뭐가 인상 깊었는지 알아? 파리에선 아무도 시장 이름을 몰라. 여기선 시장이 치즈 장수 손주들 이름까지 알아."),
(MA, "Et toi, à Marseille, tu connaissais celui de ton maire, petite ?", "그럼 넌 마르세유에서 어릴 때 시장 이름 알았어?"),
(I, "Je connaissais surtout celui des banquiers de mon père. Je suis partie à Paris à dix-huit ans pour ne plus voir le port où il avait tout perdu. Paris, c'était l'anonymat. Personne ne savait qui était Marchetti.", "난 주로 아빠 은행가들 이름을 알았지. 아빠가 모든 걸 잃은 그 항구를 더는 안 보려고 열여덟 살에 파리로 떠났어. 파리는 익명성이었어. 아무도 마르케티가 누군지 몰랐으니까."),
(MA, "Moi, c'est l'inverse. À Colmar, tout le monde savait que le petit Kessler vivait chez ses grands-parents. Je détestais ça. Aujourd'hui, c'est ce qui me manque le plus.", "난 반대야. 콜마르에선 다들 케슬레르네 꼬마가 조부모 집에 산다는 걸 알았어. 그게 너무 싫었는데, 지금은 그게 제일 그리워."),
(I, "Qu'on sache qui tu es ?", "누군가 너를 알아봐 주는 게?"),
(MA, "Qu'on t'attende quelque part. Mon grand-père m'attendait devant l'école, tous les jours, même quand il pleuvait. Valmont me rappelle ça : une ville où les gens se connaissent, et qui a peur qu'on ne l'attende plus.", "어딘가에서 누가 기다려 주는 거. 할아버지는 비가 와도 매일 학교 앞에서 날 기다리셨어. 발몽을 보면 그게 떠올라. 다들 서로 아는데, 더는 아무도 자기를 기다리지 않을까 봐 두려워하는 도시."),
(I, "Tu ferais un bon maire, tu sais.", "너 좋은 시장 되겠다, 그거 알아?"),
(MA, "Jamais. Je ferais attendre tout le monde avant de décider. Toi, tu déciderais avant que la question soit posée.", "절대 안 해. 난 결정하기 전에 모두를 기다리게 할걸. 넌 질문이 나오기도 전에 결정할 거고."),
(I, "D'où l'intérêt d'être deux. Au fait, Baptiste m'a écrit cet après-midi. Je te le dis tout de suite, comme promis.", "그래서 둘이어야 하는 거지. 참, 오늘 오후에 바티스트가 문자를 보냈어. 약속한 대로 바로 말하는 거야."),
(MA, "Je t'écoute. Je n'ai pas fait mes valises, tu remarqueras.", "들을게. 보다시피 난 짐 안 쌌어."),
(I, "« Mercier a gagné trois fois parce qu'il écoute, lui aussi, à sa manière. Ne l'oubliez pas. » Rien d'autre. Pas de piège, je crois.", "'메르시에가 세 번 이긴 건 그 사람도 자기 방식으로 듣기 때문이야. 그걸 잊지 마.' 그게 다야. 함정은 없는 것 같아."),
(MA, "Il a raison, d'ailleurs. C'est agaçant, mais il a raison. Allez, il fait froid, rentrons. Demain soir, on sera chez nous, et Figaro va nous faire la tête pendant deux jours.", "게다가 맞는 말이야. 짜증 나지만, 맞는 말이야. 자, 춥다, 들어가자. 내일 밤이면 우리 집에 있겠네. 피가로가 이틀은 삐쳐 있을 거야."),
(I, "Tu as dit « chez nous ». C'est la première fois que tu le dis sans hésiter.", "너 방금 '우리 집'이라고 했어. 망설이지 않고 그렇게 말한 거 처음이야."),
(MA, "Ah bon ? Pourtant, ça fait un mois que je le pense. Depuis que ton chat dort sur mes chaussettes.", "그래? 한 달째 그렇게 생각하고 있었는데. 네 고양이가 내 양말 위에서 자기 시작한 뒤로."),
(None, "Inès s'arrête, glisse sa main dans la poche du manteau de Mathieu et en sort le vieux marqueur vert. Elle le lui tend.", "이네스가 걸음을 멈추고, 마티외의 외투 주머니에 손을 넣어 낡은 초록 마커를 꺼낸다. 그리고 그에게 내민다."),
(MA, "Trois questions, alors. Quel est le vrai problème ?", "그럼 세 가지 질문. 진짜 문제는 무엇인가?"),
(I, "Une ville qui se vide, et qui a peur qu'on ne l'attende plus. Ce sont tes mots, Strasbourg.", "비어 가는 도시. 그리고 더는 아무도 자기를 기다리지 않을까 봐 두려워하는 도시. 네가 한 말이야, 스트라스부르."),
(MA, "Qui décide ?", "누가 결정하는가?"),
(I, "Les électeurs, pas nous. Et que fait-on lundi ?", "유권자. 우리가 아니라. 그럼 월요일엔 뭘 하지?"),
(MA, "Lundi, on ouvre le budget de Valmont et on fait le tri dans douze pistes. Et pour ça, il nous faudrait quelqu'un qui aime les tableurs autant que toi.", "월요일엔 발몽 예산을 열어 보고 방안 열두 개를 추려 내는 거야. 그러려면 너만큼 스프레드시트를 좋아하는 사람이 하나 더 필요해."),
(I, "J'en connais une. Elle s'ennuie à mourir chez Vasseur, et elle sait garder un secret... à peu près.", "한 명 알아. 바쇠르에서 지루해 죽으려고 하고, 비밀도 지킬 줄 알아... 대충은."),
(None, "Ils remontent la levée vers la Closerie. Derrière eux, la Loire continue de couler, lente et sans bruit.", "두 사람은 둑길을 따라 클로즈리 쪽으로 걸어 올라간다. 그들 뒤로 루아르 강이 느리고 소리 없이 계속 흐른다."),
]

VOCAB = [
("B1", "une chambre d'hôtes", "민박(B&B)", "주인이 사는 집의 객실에 묵고 아침 식사를 함께 받는다. 주인과 저녁을 함께 먹는 식사는 la table d'hôtes."),
("B2", "Ça se sait vite.", "(소문이) 금방 퍼진다", "se savoir = 알려지다(대명동사 수동). 작은 마을·회사 분위기를 말할 때. Tout se sait ici."),
("B2", "plein à craquer", "터질 듯 꽉 찬", "Le centre-ville était plein à craquer. 사람·가방·방 등에 두루 씀."),
("B2", "la rocade", "(도시) 외곽 순환도로", "지방 도시 외곽을 도는 도로. 대형 쇼핑센터가 늘어서는 곳. Paris는 le périphérique."),
("C1", "la méthode des quotas", "할당 표본 추출법", "나이·성별·직업·지역 비율을 인구 구성에 맞춰 표본을 짜는 방식. 프랑스 여론조사의 표준. ↔ l'échantillon aléatoire(무작위 표본)."),
("B2", "les intentions de vote", "투표 의향, 지지율", "sondage d'intentions de vote. 결과는 « Mercier est crédité de 31 % »처럼도 말한다."),
("B2", "la marge d'erreur", "오차범위", "C'est dans la marge d'erreur(오차범위 안이다). 표본이 클수록 줄어든다."),
("B2", "un(e) indécis(e)", "부동층, 미정 응답자", "les indécis = 아직 마음을 정하지 못한 유권자. un électeur hésitant과 비슷."),
("C1", "le taux de notoriété", "인지도", "notoriété = 이름이 알려진 정도. 호감도(la cote de popularité, l'opinion favorable)와 구분한다."),
("B2", "Un sondage est une photographie, pas une prévision.", "여론조사는 사진이지 예측이 아니다", "프랑스 정치 해설의 단골 문장. 특정 시점의 상태일 뿐 결과를 예언하지 않는다는 뜻."),
("C1", "avoir beau jeu de + 부정사", "~하기 쉬운 유리한 처지다", "Mercier aurait beau jeu de publier le reste. avoir beau + 부정사(아무리 ~해도)와 혼동 주의."),
("B2", "se déplacer (aux urnes)", "투표하러 가다", "선거 기사에서 voter 대신 자주 씀. Seuls 46 % des inscrits se sont déplacés."),
("B2", "les inscrits", "등록 유권자", "inscrit sur les listes électorales. 투표율은 inscrits 대비로 계산한다(les votants / les inscrits)."),
("B2", "en dire long (sur qc)", "(~에 대해) 많은 것을 말해 주다", "Les entretiens en disent plus long que les chiffres. 침묵·표정에도 씀."),
("B2", "Touché.", "한 방 먹었네(인정한다)", "펜싱 용어에서 온 표현. 상대의 반박이 정확할 때 웃으며 인정하는 말."),
("B2", "renoncer à se faire soigner", "치료를 포기하다", "le renoncement aux soins = 비용·거리·대기 때문에 치료를 포기하는 현상. 보건 정책의 핵심 지표."),
("B2", "un désert médical", "의료 사막(의료 취약 지역)", "의사가 부족해 진료받기 어려운 지역. lutter contre les déserts médicaux."),
("C1", "un centre de santé (municipal)", "(시립) 보건 센터", "의사·간호사가 월급제로 일하는 공공 진료소. une maison de santé는 개업의들이 모인 공동 진료소."),
("B2", "un médecin généraliste / de ville", "일반의 / 동네 의원 의사", "médecin traitant(주치의)로 등록해 진료받는다. ↔ médecin hospitalier(병원 의사)."),
("C1", "le clientélisme", "선심 정치, 표를 사는 정치", "특정 집단에 혜택을 약속해 지지를 얻는 행태. la démagogie(대중 영합)와 함께 비판적으로 쓴다."),
("C1", "relever de (qn / qc)", "(누구의) 소관이다, ~에 속하다", "Cela ne relève pas de la mairie. 행정·법률 문체의 핵심 동사. être du ressort de와 비슷."),
("B2", "faire le tri (dans qc)", "추려 내다, 가려내다", "On fait le tri dans douze pistes. 원래 '분류하다'(le tri sélectif = 분리수거)."),
("B2", "une piste", "방안, 실마리", "직역 '길, 자국'. explorer une piste, une piste de réflexion. 아직 확정되지 않은 아이디어."),
("B1", "un fromage de chèvre cendré", "재를 입힌 염소 치즈", "루아르 지방의 명물. affiné trois semaines(3주 숙성)처럼 숙성 기간을 말한다."),
("B2", "faire la tête", "삐치다, 뾰로통하다", "Figaro va nous faire la tête. 사람·동물 모두. bouder와 비슷."),
]

GRAM = [
("B2", "간접화법과 시제 일치",
 "« Une aide-soignante m'a dit qu'elle avait renoncé à se faire soigner les dents, parce que le seul dentiste qui restait ne prenait plus de nouveaux patients. » « Un retraité m'a demandé si quelqu'un, à Paris, savait encore où se trouvait Valmont. » « Un lycéen m'a expliqué qu'il partirait dès qu'il aurait son bac. » 전달 동사가 과거(a dit, a demandé)이면 직접화법의 복합과거 → 대과거(avait renoncé), 현재 → 반과거(savait), 미래 → 조건법 현재(partirait, ne reviendrait pas)로 바뀐다. dès que 뒤의 미래(dès qu'il aura son bac)도 조건법(dès qu'il aurait son bac)이 된다. 예/아니요 질문은 si로 받는다(m'a demandé si...). 인터뷰 결과 보고에서 반드시 쓰는 구조."),
("C1", "문어 도치: Sans doute... / Encore faut-il que...",
 "« Sans doute les chiffres ne disent-ils pas tout. » « Encore faut-il qu'on puisse les vérifier en une journée. » sans doute, peut-être, aussi(그러므로), encore(그렇지만 ~해야 한다)가 문두에 오면 주어-동사 도치가 일어난다. 명사 주어는 그대로 두고 대명사(ils)로 다시 받는 복합 도치(les chiffres ne disent-ils...)를 쓴다. Encore faut-il que + 접속법은 '그러려면 우선 ~해야 하지만'이라는 단서 붙이기로, 토론·논설에서 아주 흔하다."),
("C1", "명사화: 동사 대신 명사로 압축하기",
 "« Trois symptômes, un seul mal. La raréfaction des médecins, l'isolement des jeunes, la disparition des commerces. » 「의사가 줄어들고, 청년이 고립되고, 상점이 사라진다」를 명사로 바꾸면(se raréfier → la raréfaction, s'isoler → l'isolement, disparaître → la disparition) 진단 보고서·연설 문체가 된다. « Ne promettez pas la réouverture de la maternité »(rouvrir → la réouverture)처럼 동사의 목적어로도 쓴다."),
("C1", "접속법을 부르는 접속사: pour peu que / à moins que / bien que / sans que",
 "« Ils viendraient, pour peu qu'on leur offre un salaire, un logement et une équipe. »(조금이라도 ~하기만 하면) « À moins que vous ne vouliez faire campagne sur des intentions... »(~하지 않는 한, 허사 ne) « Bien qu'il soit tentant de tout promettre... »(~이긴 하지만) « ...sans que son nom apparaisse »(~하지 않고). « Pourvu que vous ne me mettiez pas sur une affiche »(~하기만 한다면)도 같은 계열. 조건·양보 접속사 뒤에는 접속법이 온다."),
("B2", "통계 표현: sur, parmi, d'entre eux, un sur quatre",
 "« six cents personnes interrogées » « Sur six cents personnes, la marge d'erreur est d'environ quatre points » « parmi ceux qui vous connaissent, six sur dix ont une opinion favorable » « plus de la moitié d'entre eux » « à peine un sur quatre » « quatorze entretiens sur cinquante ». 비율 차이는 pour cent가 아니라 point(s)로 말한다: neuf points de retard(9포인트 뒤처짐). arriver en tête(1위를 차지하다), devant(~를 앞서)도 함께 익혀 두자."),
("B2", "분열문: ce dont / ce qui ..., c'est ...",
 "« Ce qui nous manque tous les jours, ce n'est pas l'hôpital, ce sont les médecins généralistes. » « Ce dont ils ont peur, ce n'est pas la campagne, c'est d'être seuls. » « ce dont les gens souffrent ». 동사가 de를 요구하면(avoir peur de, souffrir de) ce dont, 주어 자리면 ce qui, 직접목적어면 ce que. 뒤 명사가 복수면 c'est 대신 ce sont을 쓰는 것이 문어의 규범이다."),
("B2", "양자택일·제한: soit... soit / ne... que / ne... plus",
 "« Soit on publie tout, avec la notice complète, soit on ne publie rien. » « Nous ne garderons que ce qui tient. » « Je vous promets de ne rien promettre que nous ne puissions tenir. » soit A soit B는 '둘 중 하나'를 단호하게 제시한다. ne... que는 '오직 ~만'. 마지막 문장에서 부정 선행사(rien) 뒤 관계절은 접속법(puissions)을 쓴다."),
("B2", "tu / vous 재전환과 관계 표지",
 "« On peut se tutoyer de nouveau, non ? Il n'y a plus de conseil d'administration entre nous. » — « On peut se tutoyer. Ça ne veut pas dire qu'on est du même côté. » 바쇠르 시절 동료로서 tu였다가 2부의 공식 석상에서 vous로 바뀌었던 관계가 다시 tu로 돌아간다. se tutoyer / se vouvoyer는 친밀도뿐 아니라 '지금 어떤 자격으로 만나는가'를 보여 준다. 반면 이네스와 마티외는 고객 앞에서도 서로 tu, 고객에게는 vous를 쓴다."),
]

CULTURE = [
("프랑스의 선거 여론조사 규칙",
 "프랑스에서는 1977년 법률로 선거 관련 여론조사의 공표를 규율하며, 독립 기관인 여론조사위원회(Commission des sondages)가 이를 감독한다. 공표된 조사에는 의뢰인, 표본 수, 조사 기간과 방식, 질문 원문 등 고지 사항(notice)이 따라야 하고, 2016년 개정 이후에는 오차범위도 함께 밝혀야 한다. 투표 전날과 당일에는 새 여론조사 결과를 공표할 수 없다. 프랑스 조사기관은 주로 할당 표본 방식(méthode des quotas)을 쓰는데, 엄밀히 말해 오차범위 계산은 무작위 표본을 전제로 하므로 할당 표본에서는 '근사치'로 이해해야 한다. 캠페인 내부용 조사는 공표하지 않는 한 이런 공표 규칙의 대상이 아니지만, 일부만 골라 공개하면 공표가 되어 규칙이 적용된다."),
("의료 사막과 시립 보건 센터",
 "프랑스 지방 중소도시와 농촌에서는 일반의의 고령화와 은퇴로 '의료 사막(désert médical)'이 큰 정치 쟁점이다. 병원과 응급실·산부인과의 개설과 폐쇄는 국가 기관인 지역보건청(ARS, 2010년 출범)이 관장하므로 시장에게 결정권이 없다. 대신 시·군은 의사에게 진료실과 숙소를 제공하거나, 의사를 월급제로 고용하는 시립 보건 센터(centre de santé municipal)를 세우는 방식으로 대응해 왔다. 젊은 의사들이 혼자 개업하기보다 팀과 함께 일하는 진료 형태를 선호한다는 점도 이런 정책의 배경이다."),
("민박(chambre d'hôtes)과 루아르 계곡",
 "프랑스 법에서 chambre d'hôtes는 주인이 직접 사는 집의 객실을 빌려주는 숙박 형태로, 최대 5개 객실·15명까지로 제한되며 아침 식사가 숙박비에 포함된다. 주인과 한 식탁에서 같은 메뉴로 저녁을 먹는 것을 table d'hôtes라 한다. 루아르 강은 프랑스에서 가장 긴 강으로, 흔히 '유럽의 마지막 야생 강'이라 불린다. 쉴리쉬르루아르에서 샬론쉬르루아르에 이르는 루아르 계곡은 2000년 유네스코 세계유산에 등재되었으며, 강둑(levée)과 모래톱, 염소 치즈와 와인으로 유명하다."),
]
