# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, S = "Inès", "Mathieu", "Hélène", "Sofia"
AG, B, SO, RA = "Agnès", "Baptiste", "Solène", "Raphaël"

META = {
    "part": 3, "ep": 34,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Se préparer au débat",
    "title_ko": "토론 준비",
    "place": "11구 오베르캉프 아파트(집 겸 Agora 사무실) · 발몽쉬르루아르 그랑뤼의 « Valmont Ensemble » 선거 사무소 · 지역 방송국 Canal Valmont 스튜디오 / 1월",
    "chars": "이네스, 마티외, 소피아, 엘렌, 아녜스 리비에르(« Valmont Ensemble » 대표 후보), 솔렌 티보(Canal Valmont 토론 진행자), 라파엘(스튜디오 무대감독), 바티스트(메르시에 캠프 컨설턴트)",
    "work": "지역 방송 TV 토론 대비 — 예상 질문 40개, 정치 경험 부족이라는 약점 다루기, 발언 시간·시선·몸짓, '공격이냐 구체성이냐' 논쟁, 스튜디오 리허설과 모의 토론, 질문 사전 유출 요청 거절",
    "life": "아침 식탁에서 서로 상대 후보 역할을 하다 터진 웃음, 갈레트 데 루아와 페브, 토론 뒤 소파에서 크레망으로 축배, 여왕이 고른 왕",
    "focus": "토론·반박 표현(permettez-moi de, vous oubliez que, je vous rejoins), 수사 의문문, 강조 구문, quoi que·jusqu'à ce que + 접속법, 3인칭 명령 que + 접속법, 복합 도치, 대구·명사화 연설체, 부정의 강조",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "제35화 La rumeur — 새벽에 쏟아지는 알림, 리비에르의 회사가 불법 고용을 했다는 허위 정보와 '선거를 사는 파리 커플 컨설턴트'라는 게시물.",
}

D = [
# ---------- 1. Ouverture : le débat du petit-déjeuner ----------
(None, "Un mardi de janvier, 7 h 30. Oberkampf. Du givre sur les vitres. Sur la table du petit-déjeuner : deux bols de café, des fiches bristol, et Figaro qui surveille le beurre.",
       "1월의 어느 화요일, 오전 7시 30분. 오베르캉프. 유리창에 성에가 끼어 있다. 아침 식탁 위에는 커피 사발 두 개, 메모 카드, 그리고 버터를 노리는 피가로."),
(MA, "(d'une voix grave) « Madame Rivière, avec tout le respect que je vous dois, gérer une ville, ce n'est pas gérer une PME. Combien de conseils municipaux avez-vous présidés ? Aucun. »",
     "(굵은 목소리로) '리비에르 후보님, 실례지만 도시를 운영하는 건 중소기업을 운영하는 것과 다릅니다. 시의회를 몇 번이나 주재해 보셨습니까? 한 번도 없죠.'"),
(I, "« Monsieur le maire, vous oubliez que... » Attends. Pourquoi tu prends cette voix ? On dirait un notaire enrhumé.", "'시장님, 잊고 계신 게 있는데요...' 잠깐. 왜 그런 목소리를 내? 감기 걸린 공증인 같잖아."),
(MA, "C'est la voix de l'expérience. Dix-huit ans de mandat, ça vous use les cordes vocales. Reprends.", "경험의 목소리야. 18년 임기면 성대가 닳는다고. 다시 해."),
(I, "« Monsieur le maire, vous oubliez que... que... » Voilà, j'ai perdu le fil. Ta voix me déconcentre.", "'시장님, 잊고 계신 게... 그게...' 봐, 흐름을 놓쳤잖아. 네 목소리 때문에 집중이 안 돼."),
(MA, "Un vrai débatteur ne se laisse jamais déstabiliser. Ni par une voix, ni par un chat qui lèche le beurre.", "진짜 토론자는 절대 흔들리지 않아. 목소리에도, 버터를 핥는 고양이에도."),
(I, "Figaro ! Descends de là ! ... Bon, on échange les rôles. Je fais Mercier, tu fais Agnès. Tu vas voir ce que c'est.", "피가로! 거기서 내려와! ...좋아, 역할 바꾸자. 내가 메르시에, 네가 아녜스. 어떤 건지 맛 좀 봐."),
(None, "Figaro saute de la table ; le beurre est perdu. Inès se redresse et fronce les sourcils, l'air très municipal.", "피가로가 식탁에서 뛰어내린다. 버터는 이미 글렀다. 이네스가 몸을 곧추세우고 아주 '시장다운' 표정으로 미간을 찌푸린다."),
(I, "« Chère madame, promettre ne coûte rien. Gouverner, si. Où trouverez-vous l'argent ? »", "'후보님, 약속은 공짜입니다. 통치는 그렇지 않죠. 돈은 어디서 구하실 겁니까?'"),
(MA, "« Permettez-moi de vous répondre par un chiffre, monsieur le maire... » Euh... C'était quoi, le chiffre, déjà ?", "'시장님, 숫자 하나로 답해 드리겠습니다...' 어... 그 숫자가 뭐였더라?"),
(I, "Tu vois ! Trois secondes de silence à la télévision, c'est une éternité. Ton adversaire a déjà gagné.", "봤지! 텔레비전에서 3초 침묵은 영원이야. 상대는 이미 이겼어."),
(MA, "Objection : mon adversaire a de la confiture sur le nez.", "이의 있습니다. 제 상대는 코에 잼이 묻어 있습니다."),
(I, "Quoi ? Où ça ? ... Mathieu, arrête de rire, ce n'est pas professionnel !", "뭐? 어디? ...마티외, 웃지 마, 프로답지 못하잖아!"),
(MA, "Pardon... « Monsieur le maire... » Non, je ne peux plus. Tu es beaucoup trop crédible en Mercier, c'est inquiétant.", "미안... '시장님...' 아니, 더는 못 하겠어. 너 메르시에 역이 너무 그럴듯해. 걱정될 정도야."),
(I, "Si nous deux, on n'arrive pas à garder notre sérieux autour d'un bol de café, imagine Agnès devant trois caméras.", "우리 둘이 커피 한 사발 앞에서도 진지함을 못 지키는데, 카메라 세 대 앞의 아녜스를 상상해 봐."),
(MA, "Justement : elle doit être prête à tout, même au ridicule. Je note : « Règle numéro un : garder son calme. Même face à la confiture. »", "바로 그거야. 그분은 모든 것에, 우스꽝스러운 상황에도 대비해야 해. 적어 둘게. '규칙 1번: 평정을 유지할 것. 잼 앞에서도.'"),
(None, "On sonne. Sofia entre, les joues rouges de froid, une boîte de boulangerie à la main.", "초인종이 울린다. 추위에 볼이 빨개진 소피아가 빵집 상자를 들고 들어온다."),
(S, "Bonjour, les tourtereaux ! Galette des rois : en janvier, c'est obligatoire, même dans un cabinet sérieux. ... Pourquoi vous pleurez de rire, tous les deux ?",
    "안녕, 잉꼬 커플! 갈레트 데 루아야. 1월엔 의무지, 진지한 컨설팅 회사라도. ...둘이 왜 눈물 나게 웃고 있어?"),
(None, "Dix minutes plus tard, Inès croque une fève en porcelaine. Sofia lui pose d'autorité la couronne en carton sur la tête.", "10분 뒤, 이네스가 도자기 페브를 깨문다. 소피아가 다짜고짜 그녀 머리에 종이 왕관을 씌운다."),

# ---------- 2. Client : la permanence de la Grand-Rue ----------
(None, "Le lendemain, 10 h. Valmont-sur-Loire, permanence de campagne de « Valmont Ensemble », dans une ancienne mercerie de la Grand-Rue.",
       "다음 날 오전 10시. 발몽쉬르루아르. 그랑뤼(중심가)의 옛 잡화점 자리에 차린 « Valmont Ensemble » 선거 사무소."),
(AG, "Entrez, entrez, il fait un froid de canard. J'ai une nouvelle : Canal Valmont a confirmé le débat. Jeudi en huit, vingt heures trente, en direct. Les trois têtes de liste.",
     "들어오세요, 어서요, 얼어 죽을 추위네요. 소식이 있어요. Canal Valmont이 토론을 확정했어요. 다음 주 목요일 저녁 8시 30분, 생방송. 세 명부의 대표 후보 전원이요."),
(MA, "Excellent. Combien de temps, et quel format ?", "잘됐네요. 시간은 얼마나, 형식은 어떻게요?"),
(AG, "Quatre-vingt-dix minutes, quatre thèmes : l'emploi, le centre-ville, la santé et les finances de la ville. Deux minutes de présentation chacun, une minute trente de conclusion. C'est Solène Thibaut qui anime.",
     "90분에 주제는 네 가지예요. 일자리, 도심, 의료, 시 재정. 후보마다 소개 2분, 마무리 발언 1분 30초. 진행은 솔렌 티보가 맡고요."),
(I, "Et l'ordre de passage ?", "발언 순서는요?"),
(AG, "Tiré au sort hier soir. Je parle en deuxième au début, et je conclus en dernier.", "어젯밤 추첨했어요. 시작할 땐 두 번째, 마무리는 마지막이에요."),
(MA, "Conclure en dernier, c'est un cadeau. Ce sont vos mots que les téléspectateurs emporteront en se couchant.", "마지막 마무리는 선물이에요. 시청자들이 잠자리에 들며 가져갈 말이 후보님 말이니까요."),
(AG, "Un cadeau empoisonné, oui : je vais passer quatre-vingt-dix minutes à transpirer en attendant mon tour. Soyons honnêtes. Jean-Claude Mercier fait ça depuis dix-huit ans. Yasmine Kaddour parle chaque jour devant trente adolescents. Moi, j'ai parlé devant des conseils d'administration. Ce n'est pas la même salle.",
     "독이 든 선물이죠. 제 차례를 기다리며 90분 내내 땀을 흘릴 테니까요. 솔직해집시다. 장클로드 메르시에는 18년째 이걸 해 왔어요. 야스민 카두르는 매일 청소년 서른 명 앞에서 말하고요. 저는 이사회 앞에서 말해 봤죠. 같은 무대가 아니에요."),
(I, "Un conseil d'administration hostile, c'est parfois plus redoutable que trente adolescents.", "적대적인 이사회는 때로 청소년 서른 명보다 더 무서운걸요."),
(AG, "Vous n'avez jamais affronté une classe de troisième un vendredi après-midi... Bref. Par où commence-t-on ?", "금요일 오후의 중학교 3학년 교실을 상대해 본 적이 없으시군요... 아무튼. 어디서부터 시작하죠?"),
(MA, "Par ce qu'on vous demandera. Sofia a préparé la liste.", "후보님이 받게 될 질문부터요. 소피아가 목록을 준비했어요."),
(S, "Quarante questions probables, classées par thème. Je les ai tirées de nos cinquante entretiens, de la presse locale et des procès-verbaux du conseil municipal des deux dernières années.",
    "예상 질문 40개를 주제별로 분류했어요. 저희 인터뷰 50건, 지역 언론, 지난 2년간 시의회 회의록에서 뽑았어요."),
(AG, "Quarante ! On ne m'en posera jamais quarante en quatre-vingt-dix minutes.", "40개요! 90분 동안 40개를 물어볼 리가 없잖아요."),
(I, "Non, sans doute une douzaine. Mais on ignore lesquelles. Douze sur l'emploi, dix sur les finances, huit sur la santé, six sur le centre-ville, et quatre... plus personnelles.",
    "아니죠, 아마 열두 개쯤요. 하지만 어떤 건지는 모르니까요. 일자리 12개, 재정 10개, 의료 8개, 도심 6개, 그리고 4개는... 좀 더 개인적인 질문이에요."),
(AG, "Personnelles ? C'est-à-dire ?", "개인적인 질문이요? 어떤 거죠?"),
(I, "Celle-ci, d'abord : « Vous n'avez jamais exercé le moindre mandat. Pourquoi les Valmontais confieraient-ils leur ville à une débutante ? »",
    "우선 이런 거요. '후보님은 단 한 번도 선출직을 맡아 본 적이 없습니다. 발몽 시민들이 왜 초보자에게 도시를 맡겨야 합니까?'"),
(AG, "Je répondrais que j'ai dirigé une entreprise pendant vingt ans, et qu'une ville, au fond, se gère comme une entreprise.", "20년 동안 회사를 경영했고, 도시도 결국 기업처럼 운영하는 거라고 답하겠죠."),
(MA, "Voilà exactement la phrase qu'il ne faut pas prononcer.", "바로 그게 절대 해서는 안 되는 말이에요."),
(AG, "Pourquoi ? C'est ce que je pense.", "왜요? 제 생각이 그런데요."),
(MA, "Parce qu'une ville n'a pas de clients, elle a des habitants. Ceux qui ne paient pas, on ne s'en sépare pas : on les soigne, on les loge, on scolarise leurs enfants. Vos adversaires n'attendent que cette phrase pour vous la renvoyer pendant six semaines.",
     "도시에는 고객이 아니라 주민이 있으니까요. 돈을 못 내는 사람과 관계를 끊을 수는 없죠. 치료하고, 집을 마련해 주고, 아이들을 학교에 보내야 해요. 상대 후보들은 그 말 한마디만 기다리고 있어요. 6주 내내 후보님께 되돌려 주려고요."),
(AG, "... Vu comme ça. Alors, qu'est-ce que je réponds ?", "...그렇게 보면 그렇네요. 그럼 뭐라고 답하죠?"),
(MA, "La vérité, d'abord. Ne niez jamais un point faible : reconnaissez-le, puis retournez-le. Quelque chose comme : « C'est vrai, je n'ai jamais été élue. Mais pendant vingt ans, j'ai dû boucler les fins de mois et payer des salaires... »",
     "우선 진실을요. 약점은 절대 부정하지 마세요. 인정하고, 그다음 뒤집으세요. 이런 식으로요. '맞습니다, 저는 선출된 적이 없습니다. 하지만 20년 동안 매달 말 살림을 꾸리고 월급을 줘야 했습니다...'"),
(AG, "« ... et quand l'argent manquait, je ne pouvais pas emprunter à la place de mes salariés. » Comme ça ?", "'...그리고 돈이 모자랄 때 직원들 대신 빚을 낼 수는 없었습니다.' 이렇게요?"),
(I, "Exactement comme ça. La deuxième question personnelle sera plus rude : « Vous avez vendu votre entreprise l'an dernier. Qui nous dit que vous ne vendrez pas la ville ? »",
    "바로 그렇게요. 두 번째 개인 질문은 더 거칠 거예요. '후보님은 작년에 회사를 파셨습니다. 도시를 팔지 않으리라고 누가 보장합니까?'"),
(AG, "C'est odieux ! L'acheteur a gardé les quatre-vingt-cinq salariés, sans exception, et l'usine est restée à Valmont !", "그건 너무하잖아요! 인수자는 직원 85명을 한 명도 빠짐없이 고용 승계했고, 공장도 발몽에 그대로 있어요!"),
(I, "Alors dites-le avec ce calme-là, pas avec cette colère-là. Un candidat qui s'indigne a l'air de se défendre ; un candidat qui précise a l'air de savoir.",
    "그럼 그 화난 말투 말고 차분하게 말씀하세요. 분개하는 후보는 변명하는 것처럼 보이고, 정확히 말하는 후보는 아는 사람처럼 보이거든요."),
(AG, "Et si, de mon côté, je glissais une petite allusion à l'âge de Mercier ? Soixante-sept ans, trois mandats... Tout le monde y pense.", "그럼 저도 메르시에의 나이를 살짝 언급하면 어때요? 67세, 3선... 다들 그 생각은 하잖아요."),
(MA, "Non. Ni allusion à l'âge, ni attaque personnelle. C'est un principe d'Agora, et c'est aussi une erreur de stratégie : les gens peuvent y penser tout bas et vous reprocher de le dire tout haut.",
     "안 됩니다. 나이 언급도, 인신공격도 안 돼요. 그건 Agora의 원칙이고, 전략적으로도 실수예요. 사람들은 속으로는 그렇게 생각해도, 그걸 대놓고 말하는 후보는 탓하거든요."),
(AG, "Bien. Une dernière chose, alors... Solène Thibaut déjeune de temps en temps avec ma belle-sœur. Elle pourrait peut-être nous laisser entrevoir les questions...",
     "알겠어요. 그럼 마지막으로 하나만... 솔렌 티보가 가끔 제 시누이랑 점심을 먹거든요. 어쩌면 질문을 살짝 귀띔해 줄 수도..."),
(I, "Non, Agnès. Si vous connaissiez les questions à l'avance, ce ne serait plus un débat, ce serait une pièce de théâtre. Et le jour où ça se saurait, car ça finit toujours par se savoir, vous perdriez bien plus qu'un débat.",
    "안 돼요, 아녜스. 질문을 미리 안다면 그건 더 이상 토론이 아니라 연극이에요. 그리고 그게 알려지는 날엔, 결국 언제나 알려지게 마련이니까요, 토론 하나보다 훨씬 많은 걸 잃으실 거예요."),
(AG, "Vous avez raison. Je retire ma question, et j'ai honte de l'avoir posée. Au travail : quarante questions en huit jours.", "맞아요. 그 질문은 취소할게요. 그런 걸 물어본 게 부끄럽네요. 자, 일합시다. 8일 동안 질문 40개."),

# ---------- 3. Analyse : le vent et le bruit ----------
(None, "Samedi, 15 h. Oberkampf. Le salon est devenu une salle de guerre : quarante fiches épinglées au mur, un minuteur de cuisine, et Figaro endormi sur le dossier « Finances ».",
       "토요일 오후 3시. 오베르캉프. 거실은 작전실이 되었다. 벽에 핀으로 꽂은 질문 카드 40장, 주방용 타이머, 그리고 '재정' 파일 위에서 잠든 피가로."),
(I, "J'ai refait les calculs. Cent vingt millions de dette pour soixante-dix mille habitants : environ mille sept cents euros par Valmontais. C'est nettement au-dessus des villes de taille comparable. Agnès doit le dire, et le dire fort.",
    "계산을 다시 해 봤어. 인구 7만에 부채 1억 2천만 유로. 발몽 시민 1인당 약 1,700유로야. 비슷한 규모 도시들보다 확실히 높아. 아녜스가 그걸 말해야 해, 그것도 강하게."),
(MA, "Le dire, oui. Le dire fort, je n'en suis pas sûr.", "말하는 건 좋아. 강하게 말하는 건 잘 모르겠어."),
(I, "Mathieu, Mercier a eu dix-huit ans. Dix-huit ans pendant lesquels la dette a grimpé et le chômage est resté à onze pour cent. Si elle ne le met pas face à son bilan, qui le fera ?",
    "마티외, 메르시에는 18년이 있었어. 그동안 부채는 치솟았고 실업률은 11%에 머물렀지. 아녜스가 그의 성적표를 들이밀지 않으면 누가 하겠어?"),
(MA, "Yasmine Kaddour s'en chargera, crois-moi. Et pendant qu'on l'attaquera de deux côtés, il aura le beau rôle : le vieux capitaine pris pour cible au milieu de la tempête.",
     "야스민 카두르가 맡아서 할 거야, 믿어 봐. 그리고 양쪽에서 공격받는 동안 그는 좋은 역할을 차지하겠지. 폭풍 한가운데서 표적이 된 노선장 말이야."),
(S, "Pour être honnête, il a des arguments. J'ai relu ses discours : la dette a financé la rénovation des quatorze écoles et de la médiathèque. Et quand les filatures ont fermé, il a maintenu tous les services publics. Beaucoup d'habitants lui en sont reconnaissants.",
    "솔직히 말하면 그분도 근거가 있어. 연설문을 다시 읽어 봤는데, 그 부채로 학교 14곳과 미디어도서관을 리모델링했어. 방적 공장들이 문을 닫았을 때도 공공 서비스를 하나도 줄이지 않았고. 고마워하는 주민이 많아."),
(I, "Reconnaissants, peut-être. Mais il reste un tiers d'indécis. Ceux-là attendent autre chose.", "고마워할 수도 있지. 하지만 아직 3분의 1이 미정이야. 그 사람들은 다른 걸 기다리고 있어."),
(MA, "Justement : les indécis ne cherchent pas un procureur. Ils cherchent quelqu'un à qui confier les clés. On ne convainc pas un indécis en lui prouvant que l'autre a tort, mais en lui montrant ce qu'on fera lundi matin.",
     "바로 그거야. 미정층은 검사를 찾는 게 아니야. 열쇠를 맡길 사람을 찾는 거지. 미정층은 상대가 틀렸다고 증명해서가 아니라, 월요일 아침에 뭘 할지 보여 줘야 설득돼."),
(I, "Ton « concret » sans chiffres, c'est du vent.", "숫자 없는 네 '구체성'은 그냥 바람이야."),
(MA, "Et tes chiffres sans visages, c'est du bruit.", "그리고 얼굴 없는 네 숫자는 그냥 소음이고."),
(None, "On frappe. Hélène entre, manteau camel, un journal plié sous le bras.", "노크 소리. 낙타색 코트를 입은 엘렌이 신문을 접어 옆구리에 끼고 들어온다."),
(H, "Je vous entends depuis le palier. Le vent et le bruit... On dirait le titre d'une fable. Lequel l'emporte ?", "층계참에서부터 다 들리네. 바람과 소음이라... 우화 제목 같구나. 누가 이기고 있니?"),
(I, "Personne, pour l'instant. Hélène, toi qui as vu des dizaines de débats, qu'est-ce qui fait gagner ?", "아직 아무도요. 엘렌, 토론을 수십 번 보셨잖아요. 뭐가 승부를 가르나요?"),
(H, "On ne gagne presque jamais un débat, Inès : on évite de le perdre. Un débat se perd en une phrase, une colère, une hésitation, un mépris. Il se gagne rarement, et jamais par K.-O.",
    "토론은 거의 이기는 게 아니란다, 이네스. 지지 않는 거지. 토론은 한 문장, 한 번의 분노, 한 번의 머뭇거림, 한 번의 경멸로 진다. 이기는 일은 드물고, KO승은 결코 없어."),
(MA, "Donc on joue la défense ?", "그럼 수비를 하라는 건가요?"),
(H, "Non, on joue la constance. Et rappelez-vous ceci : dans un débat, on ne s'adresse jamais à son adversaire, mais à ceux qui regardent. Mercier ne votera pas pour Agnès, quoi qu'elle dise.",
    "아니, 꾸준함으로 가는 거야. 그리고 이걸 기억해. 토론에서는 절대 상대에게 말하는 게 아니라 지켜보는 사람들에게 말하는 거야. 아녜스가 무슨 말을 하든 메르시에가 그녀에게 투표하진 않을 테니까."),
(I, "Celle-là, je l'épingle au mur.", "그 말은 벽에 꽂아 둘게요."),
(H, "Épingle aussi celle-ci : le lendemain, au marché, les gens ne répètent ni un tableau ni une démonstration. Ils répètent une phrase, un chiffre, une image. Une seule de chaque, et encore.",
    "이것도 꽂아 두렴. 다음 날 장터에서 사람들은 표나 논증을 되풀이하지 않아. 한 문장, 한 숫자, 한 장면을 되풀이하지. 각각 딱 하나씩, 그나마도 운이 좋으면."),
(I, "Un chiffre ! Donc j'ai raison.", "숫자! 그러니까 내가 맞네요."),
(H, "Un chiffre qui parle de leur vie, pas de celle de Mercier. Mille sept cents euros de dette par habitant, c'est un reproche. Quarante-deux vitrines vides dans la Grand-Rue, c'est une image que chacun voit en allant chercher son pain.",
    "그들의 삶을 말하는 숫자여야지, 메르시에의 삶이 아니라. 주민 1인당 부채 1,700유로는 비난이야. 그랑뤼의 빈 상점 진열창 42개는 빵 사러 가는 길에 누구나 보는 장면이고."),
(MA, "Et l'expérience ? C'est son talon d'Achille. Sans doute Mercier appuiera-t-il dessus toute la soirée.", "그럼 경험은요? 그게 그분의 아킬레스건이에요. 메르시에는 아마 밤새 거기를 찌를 거예요."),
(H, "Qu'il appuie ! Que voulez-vous qu'elle réponde, qu'elle a été déléguée de classe en sixième ? Qu'elle l'assume plutôt : c'est au pied du mur qu'on voit le maçon. Elle a construit quelque chose ; qu'elle le montre.",
    "찌르라지! 아녜스가 뭐라고 답하길 바라니, 초등학교 6학년 때 반장이었다고? 차라리 당당히 인정하라고 해. 실력은 일을 맡겨 봐야 아는 법이라고. 그녀는 뭔가를 일궈 냈어. 그걸 보여 주면 돼."),
(MA, "C'est joli, mais un proverbe dans la bouche d'un candidat, ça sent la fiche préparée.", "멋지긴 한데, 후보 입에서 나오는 속담은 준비한 카드 냄새가 나요."),
(H, "Tout sent la fiche quand on la récite ; rien ne la sent quand on y croit. Bien, je ne reste pas. Un dernier conseil : faites-la répéter jusqu'à ce qu'elle s'ennuie. L'ennui, c'est le contraire du trac.",
    "외워서 읊으면 뭐든 카드 냄새가 나지. 진심으로 믿으면 아무 냄새도 안 나고. 자, 난 오래 못 있어. 마지막 조언 하나. 지루해질 때까지 연습시켜. 지루함은 무대 공포의 반대말이거든."),
(I, "Merci, Hélène. Tu ne prends pas un café ?", "고마워요, 엘렌. 커피 한 잔 안 하세요?"),
(H, "Pas le temps. Et puis vous avez une dispute à finir ; je ne voudrais pas vous en priver.", "시간이 없어. 게다가 너희는 끝내야 할 말다툼이 있잖니. 그걸 빼앗고 싶진 않구나."),
(None, "La porte se referme. Un silence.", "문이 닫힌다. 잠시 침묵."),
(I, "Bon. Je retire « c'est du vent ».", "좋아. '바람'이라고 한 건 취소할게."),
(MA, "Et moi « c'est du bruit ». Au fond, on dit la même chose : un chiffre, oui, mais un chiffre qu'on peut voir.", "나도 '소음'은 취소. 사실 우린 같은 말을 하고 있어. 숫자, 좋아. 단, 눈에 보이는 숫자."),
(I, "Alors faisons simple. Pour chaque thème : une phrase, un chiffre, une proposition. Sofia, tu peux nous préparer quatre fiches de ce format-là ?",
    "그럼 단순하게 가자. 주제마다 한 문장, 한 숫자, 한 제안. 소피아, 그 형식으로 카드 네 장 만들어 줄 수 있어?"),
(S, "Une phrase, un chiffre, une proposition... Pour lundi ? Vous savez qu'on est samedi ?", "한 문장, 한 숫자, 한 제안이라... 월요일까지? 오늘 토요일인 거 알지?"),
(MA, "On sait. Pour la peine, je t'invite à dîner : choucroute maison, recette de ma grand-mère.", "알지. 수고비로 저녁 살게. 홈메이드 슈크루트, 우리 할머니 레시피로."),
(S, "La choucroute de Mamie Odile ? Alors là, vous pouvez me demander six fiches.", "오딜 할머니 슈크루트? 그럼 카드 여섯 장도 해 줄 수 있지."),

# ---------- 4. Terrain : le plateau de Canal Valmont ----------
(None, "Le mardi suivant, 14 h. Studios de Canal Valmont, dans l'ancienne teinturerie du quai. Un plateau sombre, trois pupitres en demi-cercle, un écran avec trois chronomètres. Il fait chaud sous les projecteurs.",
       "그다음 화요일 오후 2시. 강둑의 옛 염색 공장에 자리한 Canal Valmont 스튜디오. 어두운 세트, 반원형으로 놓인 연단 세 개, 스톱워치 세 개가 뜨는 화면. 조명 아래는 덥다."),
(SO, "Bienvenue sur le plateau. Je vous rappelle les règles : chaque candidat dispose de vingt-cinq minutes de temps de parole au total, chronométrées. Les compteurs s'affichent ici, au-dessus de vous, et sur l'écran des téléspectateurs.",
     "스튜디오에 오신 걸 환영합니다. 규칙을 다시 말씀드리죠. 후보마다 발언 시간은 총 25분이고, 시간을 잽니다. 카운터는 여기 여러분 머리 위와 시청자 화면에 뜹니다."),
(AG, "Et si quelqu'un dépasse ?", "누가 시간을 넘기면요?"),
(SO, "Je l'interromps : poliment la première fois, moins poliment la deuxième. Et autant le dire tout de suite : je ne communique les questions à personne. Ni aux candidats, ni à leurs équipes, ni à ma propre mère.",
     "끊습니다. 처음엔 정중하게, 두 번째는 덜 정중하게요. 그리고 지금 바로 말씀드리는데, 질문은 아무에게도 알려 주지 않아요. 후보에게도, 캠프에도, 제 어머니에게도요."),
(I, "Nous n'en attendions pas moins, madame.", "당연히 그러셔야죠."),
(RA, "Madame Rivière, votre pupitre est celui du milieu. Je vous pose un micro-cravate. Évitez de le tapoter : chaque petit coup résonne comme un coup de tonnerre.",
     "리비에르 후보님, 가운데 연단입니다. 핀 마이크를 달아 드릴게요. 톡톡 두드리지 마세요. 살짝만 쳐도 천둥소리처럼 울립니다."),
(AG, "Je tapote quand je suis nerveuse. Ça va être un orage.", "저는 긴장하면 두드리는데요. 폭풍우가 치겠네요."),
(RA, "Alors posez les mains à plat sur le pupitre. Et repérez la lumière rouge : c'est la caméra qui vous filme.", "그럼 손을 연단 위에 평평하게 올려 두세요. 그리고 빨간 불을 찾으세요. 그게 후보님을 찍는 카메라예요."),
(MA, "Une précision, si vous permettez. Quand une question vient de Mme Thibaut, regardez Mme Thibaut. Quand vous vous adressez aux Valmontais, regardez la caméra. Jamais le plafond, jamais vos notes.",
     "한 가지만 덧붙일게요. 티보 씨가 질문하면 티보 씨를 보세요. 발몽 시민들에게 말할 땐 카메라를 보시고요. 천장도, 메모도 절대 보지 마세요."),
(SO, "On fait un essai ? Question test, sans enjeu. Madame Rivière, en trente secondes : pourquoi vous présentez-vous ?", "한번 해 볼까요? 부담 없는 테스트 질문입니다. 리비에르 후보님, 30초 안에. 왜 출마하셨습니까?"),
(None, "Les projecteurs montent. La lumière rouge s'allume. Agnès ouvre la bouche. Rien ne sort.", "조명이 밝아진다. 빨간 불이 켜진다. 아녜스가 입을 연다. 아무 소리도 나오지 않는다."),
(AG, "Je... Je me présente parce que... Pardon. Pardon, je ne vois plus rien avec ces projecteurs.", "저는... 제가 출마한 이유는... 죄송해요. 죄송해요, 조명 때문에 아무것도 안 보여요."),
(RA, "C'est normal, tout le monde est ébloui la première fois. Même le maire, il y a dix-huit ans.", "정상이에요. 처음엔 다들 눈이 부셔요. 18년 전엔 시장님도 그러셨어요."),
(MA, "Agnès, respirez. Oubliez la caméra une seconde. Pensez à quelqu'un de précis, une personne rencontrée pendant la campagne.", "아녜스, 숨 쉬세요. 잠깐 카메라는 잊으세요. 특정한 누군가를 떠올리세요. 선거운동 중에 만난 사람이요."),
(AG, "... La pharmacienne de la rue des Teinturiers. Elle m'a dit que les gens viennent la voir parce qu'ils n'ont plus de médecin.", "...테튀리에 거리의 약사요. 사람들이 더는 의사가 없어서 자기한테 온다고 했어요."),
(MA, "Alors parlez-lui, à elle. La caméra, c'est elle.", "그럼 그분에게 말하세요. 카메라가 곧 그분이에요."),
(SO, "On reprend. Madame Rivière, pourquoi vous présentez-vous ?", "다시 가겠습니다. 리비에르 후보님, 왜 출마하셨습니까?"),
(AG, "Parce qu'à Valmont, une pharmacienne fait aujourd'hui le travail de trois médecins partis à la retraite. Parce que quarante-deux vitrines sont vides dans la Grand-Rue. Et parce qu'une ville qui a habillé la France entière sait encore se relever. Je ne promets pas de miracles ; je promets des comptes, chaque année.",
     "오늘날 발몽에서는 약사 한 명이 은퇴한 의사 세 명의 몫을 하고 있기 때문입니다. 그랑뤼의 진열창 42개가 비어 있기 때문입니다. 그리고 프랑스 전체에 옷을 입혔던 도시라면 아직 다시 일어설 수 있기 때문입니다. 저는 기적을 약속하지 않습니다. 매년 결산 보고를 약속합니다."),
(SO, "Vingt-huit secondes. Vous voyez, vous n'avez pas besoin de moi.", "28초. 보세요, 제 도움은 필요 없으시네요."),
(I, "(à voix basse) Vingt-huit secondes, et pas un seul « euh ». J'aurais signé tout de suite.", "(낮은 목소리로) 28초에 '어'가 단 한 번도 없었어. 이 정도면 난 무조건 오케이야."),
(None, "Dans le couloir, ils croisent l'équipe du maire sortant, attendue pour la répétition suivante. Baptiste marche en tête, un gobelet de café à la main.", "복도에서 다음 리허설 차례인 현직 시장 캠프와 마주친다. 바티스트가 커피 컵을 들고 앞장서 걸어온다."),
(B, "Tiens, Agora au complet. Vous avez répété longtemps ? Notre candidat, lui, n'a pas besoin de répéter : il a dix-huit ans de répétitions derrière lui.", "어라, 아고라 전원 출동이네. 오래 연습했어? 우리 후보는 연습이 필요 없어. 18년치 리허설이 쌓여 있거든."),
(I, "C'est ce qu'on dit des pièces qu'on joue trop longtemps, Baptiste : le public finit par connaître la fin.", "너무 오래 공연한 연극에 대해서 다들 그렇게 말하지, 바티스트. 결국 관객이 결말을 다 알게 된다고."),
(B, "Touché. Un conseil entre anciens collègues : ne la laissez pas jouer à la cheffe d'entreprise. Valmont n'est pas une PME, et Mercier le rappellera à chaque réplique.", "한 방 먹었네. 옛 동료로서 충고 하나. 그분이 사장님 행세하게 두지 마. 발몽은 중소기업이 아니고, 메르시에는 대꾸할 때마다 그걸 상기시킬 거야."),
(MA, "Merci du conseil. On y avait pensé, figure-toi. Bonne répétition, Baptiste.", "충고 고마워. 우리도 그 생각은 했거든. 리허설 잘해, 바티스트."),
(B, "À jeudi. Que le meilleur gagne... ou, à défaut, que le moins mauvais ne perde pas.", "목요일에 봐. 최고가 이기길... 아니면 적어도 덜 나쁜 쪽이 지지 않길."),
(I, "Pardon. Je n'aurais pas dû lui répondre comme ça ; on venait de dire à Agnès : pas de pique.", "미안. 그렇게 받아치지 말았어야 했는데. 방금 아녜스한테 비꼬지 말라고 해 놓고."),
(MA, "Entre consultants, passe encore. Mais retiens surtout une chose : il vient de nous dire exactement où Mercier frappera.", "컨설턴트끼리는 뭐, 봐줄 만해. 그보다 중요한 건, 방금 바티스트가 메르시에가 어디를 칠지 정확히 알려 줬다는 거야."),

# ---------- 5. Décision : la répétition générale ----------
(None, "Mercredi, veille du débat, 20 h. La permanence de la Grand-Rue, vitrine couverte de papier kraft. Trois cartons en guise de pupitres. Inès tient le chronomètre, Mathieu joue Mercier, Sofia joue Yasmine Kaddour.",
       "수요일, 토론 전날 저녁 8시. 그랑뤼 선거 사무소, 진열창은 갈색 포장지로 가려져 있다. 상자 세 개로 만든 연단. 이네스는 스톱워치를, 마티외는 메르시에 역을, 소피아는 야스민 카두르 역을 맡았다."),
(I, "Dernière répétition générale. Je fais Solène Thibaut, en moins aimable. Premier thème : les finances. Monsieur le maire, vous avez la parole.", "마지막 총연습입니다. 제가 솔렌 티보 역을 하죠, 덜 친절하게. 첫 주제는 재정입니다. 시장님, 말씀하시죠."),
(MA, "Merci. Madame Rivière promet beaucoup : une maison de santé, des commerces, des apprentis... Faut-il rappeler qu'une mairie n'est pas un chéquier ? Où trouverez-vous l'argent, madame ?",
     "감사합니다. 리비에르 후보는 많은 걸 약속합니다. 의료센터, 상점, 견습생... 시청이 수표책이 아니라는 걸 굳이 상기시켜 드려야 합니까? 돈은 어디서 구하실 겁니까?"),
(AG, "La maison de santé coûtera trois millions huit cent mille euros. L'État et la région en financeront deux millions six cent mille ; la ville, un million deux cent mille, étalés sur trois ans, par redéploiement de crédits. Sans augmenter d'un centime la taxe foncière.",
     "의료센터에는 380만 유로가 듭니다. 국가와 지역권(레지옹)이 260만 유로를 대고, 시는 120만 유로를 3년에 걸쳐 예산 재배정으로 마련합니다. 재산세는 단 1상팀도 올리지 않습니다."),
(I, "Madame Kaddour ?", "카두르 후보님?"),
(S, "Des chiffres, toujours des chiffres... Madame Rivière parle comme un tableur, mais pas un mot du climat. Vous oubliez, madame, que nos écoles sont des passoires thermiques et que la Loire n'a jamais été aussi basse que l'été dernier !",
    "숫자, 또 숫자... 리비에르 후보는 스프레드시트처럼 말하지만 기후에 대해서는 한마디도 없군요. 후보님, 우리 학교들이 열이 줄줄 새는 건물이고, 지난여름 루아르강 수위가 사상 최저였다는 걸 잊고 계십니다!"),
(AG, "Je ne l'oublie pas, madame Kaddour, et sur ce point je vous rejoins. C'est d'ailleurs pourquoi la maison de santé sera installée dans l'ancienne annexe de l'hôpital, rénovée aux normes basse consommation, plutôt que construite à neuf.",
     "잊지 않았습니다, 카두르 후보님. 그 점에선 저도 같은 생각입니다. 그래서 의료센터도 새로 짓는 대신 옛 병원 분원을 저에너지 기준으로 리모델링해서 들어가는 겁니다."),
(MA, "Quel consensus touchant ! Mais quand on n'a jamais présidé un conseil municipal, madame, on promet tout à tout le monde. Moi, j'ai dix-huit ans de décisions derrière moi.",
     "참 감동적인 합의군요! 하지만 시의회를 한 번도 주재해 본 적 없는 사람은 모두에게 모든 걸 약속하기 마련이죠. 저는 18년의 결정을 등 뒤에 두고 있습니다."),
(AG, "Et vous avez raison de les rappeler, monsieur le maire. Mais c'est au pied du mur qu'on voit le maçon : pendant vingt ans, j'ai payé quatre-vingt-cinq salaires chaque mois, y compris les mois où je ne me suis pas payée moi-même. Je n'ai pas l'expérience d'un mandat ; j'ai l'expérience des fins de mois.",
     "그걸 상기시키시는 건 옳습니다, 시장님. 하지만 실력은 일을 맡겨 봐야 아는 법입니다. 20년 동안 저는 매달 85명의 월급을 줬습니다. 제 월급은 못 가져간 달에도요. 저는 임기의 경험은 없습니다. 대신 월말을 버텨 낸 경험이 있습니다."),
(I, "Très bien. Deuxième thème : l'emploi. Monsieur le maire.", "좋습니다. 두 번째 주제, 일자리. 시장님."),
(MA, "Le chômage à Valmont, c'est la mondialisation, pas la mairie. Qui peut sérieusement croire qu'un maire fait revenir des usines ?", "발몽의 실업은 세계화 탓이지 시청 탓이 아닙니다. 시장이 공장을 되돌려 놓을 수 있다고 진지하게 믿는 사람이 누가 있습니까?"),
(AG, "Et vous, monsieur le maire, vous avez laissé la dette monter à cent vingt millions ! Qui va la payer, cette dette ? Nos enfants !", "그러는 시장님은 부채를 1억 2천만 유로까지 불려 놓으셨잖아요! 그 빚은 누가 갚습니까? 우리 아이들이요!"),
(None, "Silence. Mathieu, toujours dans son rôle, sourit lentement.", "침묵. 마티외가 여전히 역할에 몰입한 채 천천히 미소 짓는다."),
(MA, "Cette dette, madame, a payé la rénovation des quatorze écoles où vont ces enfants. Lesquelles auriez-vous laissées tomber en ruine ? Donnez-nous des noms.", "후보님, 그 부채로 그 아이들이 다니는 학교 14곳을 고쳤습니다. 어느 학교를 무너지게 내버려 두셨겠습니까? 이름을 대 보시죠."),
(AG, "Je... Ce n'est pas ce que j'ai dit... Je voulais dire que...", "저는... 그런 말이 아니라... 제 말은..."),
(I, "Stop. On arrête le chrono.", "스톱. 스톱워치 멈춥니다."),
(AG, "Je sais. Je suis tombée dans le panneau, tête la première.", "알아요. 함정에 머리부터 빠져 버렸네요."),
(MA, "Ce n'est pas vous qui êtes tombée, c'est l'attaque. Une attaque, il peut la retourner contre vous. Une proposition, il ne peut que la discuter.", "후보님이 넘어진 게 아니라 공격이 넘어진 거예요. 공격은 상대가 되받아칠 수 있어요. 제안은 상대가 논의할 수밖에 없고요."),
(I, "Et c'est moi qui voulais qu'elle attaque sur la dette... Mathieu avait raison. Le chiffre est juste, mais dans sa bouche, il devient une arme, et une arme, ça se retourne.", "그리고 부채로 공격하자고 한 건 바로 나였죠... 마티외 말이 맞았어요. 숫자는 정확하지만 후보님 입에서는 무기가 되고, 무기는 되돌아오게 마련이에요."),
(AG, "Alors je ne dis plus rien sur la dette ?", "그럼 부채 얘기는 아예 하지 말아요?"),
(I, "Si, mais comme un fait, pas comme une accusation : « La dette est de cent vingt millions. Je ne la laisserai pas augmenter : sur l'ensemble du mandat, elle sera stabilisée. » Le fait, puis l'engagement. Jamais le coupable.",
    "하셔야죠. 다만 비난이 아니라 사실로요. '부채는 1억 2천만 유로입니다. 더 늘어나게 두지 않겠습니다. 임기 전체에 걸쳐 안정시키겠습니다.' 사실, 그다음 약속. 범인 지목은 절대 하지 않고요."),
(MA, "Voilà notre décision : pas d'attaque, du concret. À chaque critique, un fait ; à chaque fait, une proposition. Et trois chiffres à marteler : quarante-deux vitrines vides, trois millions huit cent mille euros pour la maison de santé, zéro euro de hausse de la taxe foncière.",
     "그럼 이게 우리 결정입니다. 공격 대신 구체성. 비판마다 사실 하나, 사실마다 제안 하나. 그리고 반복해서 박아 넣을 숫자 세 개. 빈 진열창 42개, 의료센터 380만 유로, 재산세 인상 0유로."),
(S, "Je peux sortir de mon rôle ? Je commençais à croire sérieusement à la Loire.", "이제 역할에서 나와도 돼? 루아르강 얘기를 진심으로 믿기 시작했거든."),
(AG, "Vous étiez très convaincante, Sofia. Yasmine Kaddour me fera peur demain, mais moins que vous ce soir.", "아주 설득력 있었어요, 소피아. 내일 야스민 카두르가 무섭겠지만 오늘 밤의 소피아만큼은 아닐 거예요."),
(I, "Et la question sur la vente de l'entreprise ? Une dernière fois.", "그럼 회사 매각 질문은요? 마지막으로 한 번 더."),
(MA, "Madame Rivière, vous avez vendu votre entreprise. Qu'est-ce qui garantit aux Valmontais que vous ne vendrez pas leur ville au plus offrant ?", "리비에르 후보님, 후보님은 회사를 파셨습니다. 후보님이 도시를 가장 높은 값을 부르는 사람에게 팔지 않으리라고 무엇이 보장합니까?"),
(AG, "Ce qui le garantit ? Les quatre-vingt-cinq salariés qui travaillent toujours dans la même usine, à deux kilomètres d'ici. Allez leur demander, monsieur le maire. Moi, j'y suis allée la semaine dernière.",
     "무엇이 보장하느냐고요? 여기서 2킬로미터 떨어진 같은 공장에서 지금도 일하고 있는 직원 85명입니다. 가서 물어보세요, 시장님. 저는 지난주에 다녀왔습니다."),
(I, "Parfait. Pas un adjectif, pas une once de colère. Un fait que n'importe qui peut vérifier.", "완벽해요. 형용사 하나 없이, 화도 조금도 안 내고. 누구나 확인할 수 있는 사실 하나."),
(AG, "Et la conclusion ? J'en ai écrit trois versions.", "그럼 마무리 발언은요? 세 가지 버전으로 써 놨어요."),
(MA, "Gardez la plus courte. Dites-la-nous.", "제일 짧은 걸로 하세요. 들려주세요."),
(AG, "« Je n'ai jamais été élue. Je ne vous demande donc pas de me faire confiance les yeux fermés ; je vous demande de me lire les yeux ouverts. Chaque engagement de notre programme a un coût, un financement et une date. Si je suis élue, vous aurez chaque année le droit de me demander des comptes. Et moi, le devoir de vous les rendre. »",
     "'저는 한 번도 선출된 적이 없습니다. 그러니 눈을 감고 저를 믿어 달라고 하지 않겠습니다. 눈을 뜨고 저를 읽어 달라고 부탁드립니다. 저희 공약 하나하나에는 비용과 재원과 날짜가 있습니다. 제가 당선되면, 여러분은 매년 저에게 결산을 요구할 권리를 갖게 됩니다. 그리고 저는 그것을 보고할 의무를 갖게 됩니다.'"),
(MA, "Une minute douze. Agnès, demain, vous serez seule sur ce plateau. Pas nous. Ce sera votre débat, votre voix, et la décision des Valmontais. Nous, nous serons devant un écran, à Paris, à nous ronger les ongles.",
     "1분 12초. 아녜스, 내일 그 무대엔 후보님 혼자예요. 저희는 없어요. 후보님의 토론, 후보님의 목소리, 그리고 발몽 시민들의 결정이죠. 저희는 파리에서 화면 앞에 앉아 손톱을 물어뜯고 있을 거예요."),

# ---------- 6. Le canapé : la reine choisit son roi ----------
(None, "Jeudi, 22 h 10. Oberkampf. Sur l'écran de l'ordinateur, le générique de fin de Canal Valmont. Sur le canapé : Inès, Mathieu, Sofia, et Figaro, qui n'a rien compris mais a tout regardé.",
       "목요일 밤 10시 10분. 오베르캉프. 노트북 화면에 Canal Valmont의 엔딩 크레디트가 흐른다. 소파에는 이네스, 마티외, 소피아, 그리고 아무것도 이해 못 했지만 전부 지켜본 피가로."),
(S, "C'est fini ! Quatre-vingt-dix minutes ! Je n'ai plus un seul ongle.", "끝났다! 90분! 손톱이 하나도 안 남았어."),
(I, "Bilan à chaud : elle n'a pas attaqué une seule fois. Mercier l'a attaquée deux fois sur l'expérience, et deux fois elle a répondu par un fait.", "따끈따끈한 총평. 아녜스는 한 번도 공격하지 않았어. 메르시에가 경험 문제로 두 번 공격했고, 두 번 다 사실로 답했지."),
(MA, "Et la phrase des fins de mois est passée. Mercier n'a pas su quoi répondre ; il a changé de sujet.", "그리고 '월말' 문장이 먹혔어. 메르시에는 뭐라고 받아쳐야 할지 몰라서 화제를 돌렸지."),
(S, "Je regarde les réactions... Le correspondant du quotidien régional écrit : « Débat de bonne tenue. Mercier solide sur son bilan, Kaddour combative sur la jeunesse et le climat, Rivière la plus précise sur le financement. »",
    "반응 보는 중... 지역 일간지 통신원이 이렇게 썼어. '수준 있는 토론. 메르시에는 자신의 성과에 대해 탄탄했고, 카두르는 청년과 기후 문제에서 투지가 넘쳤으며, 리비에르는 재원 문제에서 가장 정확했다.'"),
(I, "« La plus précise. » Pas « la plus brillante », mais c'est exactement ce qu'on cherchait.", "'가장 정확했다.' '가장 빛났다'는 아니지만, 딱 우리가 원하던 거야."),
(MA, "Le brillant se dément en une soirée ; le précis se vérifie pendant six semaines. Et soyons justes : Yasmine Kaddour a été remarquable sur l'emploi des jeunes.", "빛나는 건 하룻밤이면 반박당하지만, 정확한 건 6주 내내 검증받아. 그리고 공정하게 말하자. 야스민 카두르는 청년 일자리 문제에서 정말 뛰어났어."),
(I, "Remarquable. Et Mercier, quoi qu'on en pense, a défendu son bilan avec dignité. Ce n'était pas un match de boxe, c'était un débat. Ça fait du bien.", "뛰어났지. 그리고 메르시에도, 어떻게 생각하든 품위 있게 자기 성과를 변호했어. 권투 시합이 아니라 토론이었어. 기분 좋네."),
(None, "Le téléphone d'Inès vibre. Un message d'Agnès.", "이네스의 휴대폰이 진동한다. 아녜스의 메시지다."),
(I, "Elle écrit : « J'ai eu peur pendant quatre-vingt-dix minutes, et je ne l'ai montré que pendant trois. Merci. La pharmacienne m'a appelée. »", "이렇게 썼어. '90분 내내 무서웠는데, 티 난 건 3분뿐이었어요. 고마워요. 약사님이 전화하셨어요.'"),
(MA, "Alors il faut fêter ça. J'ai mis une bouteille de crémant de Loire au frais ce matin. Pour rester dans le thème.", "그럼 축하해야지. 아침에 루아르 크레망 한 병 냉장고에 넣어 뒀어. 주제에 맞게."),
(S, "À Agnès ! Et aux Valmontais, qui décideront.", "아녜스를 위해! 그리고 결정할 발몽 시민들을 위해."),
(I, "À la précision. Et au vent et au bruit, qui ont fini par s'entendre.", "정확함을 위해. 그리고 결국 서로 잘 통하게 된 바람과 소음을 위해."),
(S, "Bon, je vous laisse, les tourtereaux. Et n'oubliez pas : la semaine dernière, Inès a eu la fève. La reine n'a toujours pas choisi son roi. Bonne nuit !", "자, 난 갈게, 잉꼬 커플. 그리고 잊지 마. 지난주에 이네스가 페브를 뽑았잖아. 여왕님은 아직 왕을 안 골랐어. 잘 자!"),
(MA, "Elle n'a pas tort. Ça fait dix jours que la couronne en carton t'attend sur l'étagère, à côté de la Stéphanoise.", "틀린 말은 아니네. 종이 왕관이 열흘째 선반 위 스테파누아즈 옆에서 널 기다리고 있잖아."),
(I, "Une reine ne choisit pas à la légère. Monsieur Kessler, vous avez trente secondes pour me convaincre. Chrono.", "여왕은 가볍게 고르지 않아. 케슬레르 후보님, 저를 설득할 시간은 30초입니다. 시작."),
(MA, "Je ne vous promets pas de miracles, madame. Je vous promets des comptes : un café chaque matin, la vaisselle un soir sur deux, et la litière de Figaro... un soir sur trois.", "기적은 약속드리지 않겠습니다. 결산을 약속드리죠. 매일 아침 커피 한 잔, 이틀에 한 번 설거지, 그리고 피가로 화장실은... 사흘에 한 번."),
(I, "« Un soir sur trois » ? Vous oubliez, monsieur, que le programme a été chiffré en décembre. Un sur deux, ou je vote pour le chat.", "'사흘에 한 번'이요? 후보님, 그 공약은 12월에 이미 비용 산정이 끝났다는 걸 잊고 계시네요. 이틀에 한 번. 아니면 고양이한테 투표하겠어요."),
(MA, "Va pour un sur deux. Alors, le verdict ?", "이틀에 한 번으로 합의. 그래서, 판정은?"),
(I, "Élu. À l'unanimité, moins le chat. Tu sais pourquoi je ne gagnerai jamais un débat contre toi ? Parce que tu me fais rire au moment exact où je dois répondre.", "당선. 고양이 빼고 만장일치. 내가 왜 너를 상대로는 절대 토론에서 못 이기는지 알아? 내가 대답해야 하는 바로 그 순간에 네가 날 웃기거든."),
(None, "Elle pose la couronne sur la tête de Mathieu. Il prend le vieux marqueur vert et écrit sous les quarante fiches : « Que fait-on lundi ? »", "이네스가 마티외의 머리에 왕관을 씌운다. 마티외가 낡은 초록 마커를 들고 질문 카드 40장 아래에 쓴다. '월요일엔 뭘 하지?'"),
(MA, "Le débat, c'est fait. Que fait-on lundi ?", "토론은 끝났어. 월요일엔 뭘 하지?"),
(I, "Lundi, on retourne à Valmont, au marché, écouter ce que les gens ont retenu. Un débat se gagne le lendemain, au marché : c'est Hélène qui l'a dit.", "월요일엔 발몽에 다시 가. 장터에 가서 사람들이 뭘 기억하는지 들어야지. 토론은 다음 날 장터에서 이기는 거야. 엘렌이 그랬잖아."),
(None, "Ils éteignent la lumière. Sur la table basse, l'écran d'un téléphone s'allume en silence : une notification, puis une autre, puis dix. Personne ne la voit.", "두 사람이 불을 끈다. 낮은 탁자 위에서 휴대폰 화면 하나가 소리 없이 켜진다. 알림 하나, 또 하나, 그리고 열 개. 아무도 보지 못한다."),
]

VOCAB = [
("B2", "Vous oubliez que...", "~라는 걸 잊고 계시네요", "토론의 대표적 반박 도입구. 상대의 논리에서 빠진 사실을 지적한다. 공격적이므로 어조 조절이 중요."),
("B2", "perdre le fil", "(말·생각의) 흐름을 놓치다", "J'ai perdu le fil. ↔ reprendre le fil(다시 이어 가다). fil = 실."),
("B2", "les tourtereaux", "잉꼬 커플, 깨가 쏟아지는 연인", "원뜻은 '어린 멧비둘기'. 다정한 연인을 놀리듯 부를 때. Bonjour, les tourtereaux !"),
("B1", "la galette des rois / la fève", "갈레트 데 루아 / (그 안에 숨긴) 작은 도자기 인형", "1월 공현절 과자. 페브를 찾은 사람이 왕·여왕이 되어 종이 왕관(la couronne)을 쓴다."),
("B2", "il fait un froid de canard", "얼어 죽을 만큼 춥다", "구어 관용구. 오리 사냥을 하던 혹한기에서 유래했다는 설이 있다."),
("B2", "une tête de liste", "명부 대표 후보", "명부식 선거에서 명부 맨 위 인물. 지방선거에서는 사실상 '시장 후보'."),
("B2", "l'ordre de passage / tiré au sort", "발언(출연) 순서 / 추첨으로 정해진", "TV 토론·시험·공연에서. le tirage au sort = 추첨."),
("C1", "un cadeau empoisonné", "독이 든 선물, 달갑지 않은 혜택", "겉보기엔 이득이지만 실제로는 부담이 되는 것. 정치·경영 기사의 단골 표현."),
("C1", "retourner (un argument) contre qn", "(논거를) 상대에게 되돌리다, 역이용하다", "Une attaque, il peut la retourner contre vous. se retourner contre qn = 역풍이 불다."),
("B2", "boucler les fins de mois", "월말을 버텨 내다, 한 달 살림을 꾸리다", "avoir du mal à boucler ses fins de mois = 생활비가 빠듯하다. 서민 경제를 말할 때 핵심 표현."),
("C1", "penser tout bas / dire tout haut", "속으로 생각하다 / 대놓고 말하다", "Ce que tout le monde pense tout bas, il le dit tout haut. 정치 수사에서 자주 대비된다."),
("B2", "laisser entrevoir", "살짝 엿보게 하다, 넌지시 내비치다", "entrevoir = 어렴풋이 보다. Elle pourrait nous laisser entrevoir les questions."),
("C1", "un talon d'Achille", "아킬레스건, 치명적 약점", "그리스 신화에서 유래. son point faible보다 문어적이고 극적이다."),
("C1", "C'est au pied du mur qu'on voit le maçon.", "실력은 일을 맡겨 봐야 안다", "직역 '벽 앞에 서 봐야 미장이를 알아본다'. 경험이 아니라 실제 결과로 평가하자는 속담."),
("B2", "le temps de parole", "발언 시간", "TV 토론·의회에서 측정·배분되는 시간. dépasser son temps de parole = 발언 시간을 넘기다."),
("B1", "un micro-cravate", "핀 마이크(라발리에 마이크)", "넥타이(cravate)에 다는 작은 마이크. 방송 현장 어휘."),
("B2", "être ébloui(e)", "눈이 부시다, (비유) 매혹되다", "Tout le monde est ébloui la première fois. 조명·햇빛, 또는 감탄에 모두 쓴다."),
("B2", "Touché.", "한 방 먹었네, 인정", "펜싱에서 온 말. 상대의 재치 있는 반격을 인정할 때."),
("B2", "tomber dans le panneau", "함정(속임수)에 걸려들다", "panneau = 옛 사냥용 그물. Je suis tombée dans le panneau, tête la première."),
("C1", "marteler (un message, un chiffre)", "(메시지를) 반복해서 강하게 박아 넣다", "marteau(망치)에서 나온 동사. 선거 캠페인의 핵심 메시지 전략."),
("C1", "une passoire thermique", "단열이 엉망인 건물, 에너지 낭비 건물", "passoire = 체. 에너지 등급이 F·G인 주택을 가리키는 시사 용어."),
("B2", "rendre des comptes / demander des comptes", "(책임지고) 결산·해명하다 / 해명을 요구하다", "공직 윤리의 핵심. le droit de demander des comptes, le devoir de les rendre."),
("B2", "se ronger les ongles", "손톱을 물어뜯다, 초조해하다", "긴장·불안의 대표 표현. Je n'ai plus un seul ongle !"),
("B2", "à chaud / de bonne tenue", "즉석에서·직후에 / 수준 있는, 품격 있는", "un bilan à chaud(직후 평가) ↔ à froid(차분히 돌아보며). un débat de bonne tenue = 품격 있는 토론."),
]

GRAM = [
("B2", "토론의 발언·반박 표현",
 "« Permettez-moi de vous répondre par un chiffre, monsieur le maire. » « Vous oubliez, madame, que nos écoles sont des passoires thermiques. » « Je ne l'oublie pas, madame Kaddour, et sur ce point je vous rejoins. » « Une précision, si vous permettez. » Permettez-moi de + 부정사는 발언을 정중하게 시작할 때, vous oubliez que는 상대의 누락을 짚을 때 쓴다. 반대로 je vous rejoins(그 점은 동의합니다)처럼 부분 동의를 먼저 보이면 반박이 훨씬 설득력 있어진다."),
("C1", "수사 의문문: 대답을 기대하지 않는 질문",
 "« Faut-il rappeler qu'une mairie n'est pas un chéquier ? » « Qui peut sérieusement croire qu'un maire fait revenir des usines ? » « Lesquelles auriez-vous laissées tomber en ruine ? » « Que voulez-vous qu'elle réponde ? » 수사 의문문은 답을 구하지 않고 주장을 강하게 단정한다. Faut-il rappeler que(굳이 상기시켜야 합니까 = 당연히 아시죠), Qui peut croire que(누가 믿겠습니까 = 아무도 안 믿는다)가 대표적이다. 동사 croire 뒤 que절은 의문문이라도 사실로 여겨지는 내용이면 직설법(fait revenir)을 쓴다."),
("C1", "복합 도치: 명사 주어 + 동사-대명사",
 "« Pourquoi les Valmontais confieraient-ils leur ville à une débutante ? » « Sans doute Mercier appuiera-t-il dessus toute la soirée. » 명사 주어가 있는 의문문에서 문어체는 주어를 그대로 두고 동사 뒤에 대명사(-ils, -t-il)를 붙인다. sans doute, peut-être, aussi(그러므로), à peine 등이 문두에 오면 평서문에서도 같은 도치가 일어난다. 구어라면: Mercier va sans doute appuyer dessus."),
("C1", "접속법 ①: quoi que / jusqu'à ce que",
 "« Mercier ne votera pas pour Agnès, quoi qu'elle dise. » « Mercier, quoi qu'on en pense, a défendu son bilan avec dignité. » « Faites-la répéter jusqu'à ce qu'elle s'ennuie. » quoi que(무엇을 ~하든)는 양보, jusqu'à ce que(~할 때까지)는 시간의 한계로 둘 다 접속법을 요구한다. 붙여 쓰는 quoique(비록 ~지만)와 혼동하지 말 것."),
("C1", "접속법 ②: que + 접속법으로 3인칭 명령·소망",
 "« Qu'il appuie ! » « Qu'elle l'assume plutôt. » « Elle a construit quelque chose ; qu'elle le montre. » « Que le meilleur gagne... ou, à défaut, que le moins mauvais ne perde pas. » 명령법에는 3인칭 형태가 없으므로 que + 접속법으로 '그가 ~하라지/하기를'을 표현한다. 엘렌의 « Qu'il appuie ! »는 '찌르라지!'라는 도전적 허용, 바티스트의 « Que le meilleur gagne »는 관용적 소망이다."),
("B2", "강조 구문: c'est... que / ce n'est pas... c'est",
 "« C'est au pied du mur qu'on voit le maçon. » « Ce n'est pas vous qui êtes tombée, c'est l'attaque. » « Et c'est moi qui voulais qu'elle attaque sur la dette. » « C'est Hélène qui l'a dit. » c'est... que로 부사구를, c'est... qui로 주어를 강조한다. ce n'est pas A, c'est B는 초점을 옮겨 상대의 해석을 바로잡는 토론·코칭의 핵심 틀이다."),
("C1", "연설체: 대구(parallélisme)와 교차 대구(chiasme)",
 "« Je n'ai pas l'expérience d'un mandat ; j'ai l'expérience des fins de mois. » « Je ne promets pas de miracles ; je promets des comptes. » « À chaque critique, un fait ; à chaque fait, une proposition. » « le droit de me demander des comptes. Et moi, le devoir de vous les rendre. » 같은 구조를 반복하고 한 단어만 바꾸면 청중의 기억에 남는다. 앞 구절의 끝말(un fait)을 다음 구절의 첫머리로 받는 연쇄, droit/devoir처럼 짝을 이루는 명사 대비는 프랑스 연설문의 고전적 장치다. 명사화(rénovation, redéploiement, engagement)는 문장을 압축하고 격식을 높인다."),
("B2", "부정의 강조: pas un seul / ni... ni / d'un centime",
 "« pas un seul « euh » » « Pas un adjectif, pas une once de colère. » « Ni allusion à l'âge, ni attaque personnelle. » « Sans augmenter d'un centime la taxe foncière. » « Je n'ai plus un seul ongle. » pas un(e) (seul(e)) + 명사는 '단 하나도 없음'을 강조한다. ni... ni는 두 가지를 동시에 부정하며 명사 앞 관사가 흔히 생략된다. d'un centime, d'un iota, une once de처럼 아주 작은 단위를 부정해 '조금도 ~않다'를 표현한다."),
]

CULTURE = [
("프랑스의 TV 선거 토론",
 "프랑스에서 후보 간 TV 토론은 대통령 선거 결선 직전의 양자 토론이 가장 유명하지만, 지방선거에서도 지역 방송국·지역 일간지·지역 라디오가 주요 명부 대표 후보들을 초청해 토론을 연다. 방송 규제기관 Arcom(옛 CSA)은 선거 기간에 방송사가 후보와 명부에 발언 시간을 공정하게(équité) 배분하도록 권고하며, 방송사는 각 후보의 발언 시간을 측정해 기록한다. 그래서 토론 화면에 후보별 시간 카운터가 뜨는 경우가 많다. 진행자가 질문을 미리 알려 주지 않는 것은 언론 윤리의 기본이다."),
("갈레트 데 루아(galette des rois)",
 "1월 6일 공현절(Épiphanie)을 전후해 1월 내내 프랑스 빵집에서 파는 과자다. 북부와 파리에서는 아몬드 크림(frangipane)을 넣은 퍼프 페이스트리, 남부에서는 과일 설탕 절임을 올린 브리오슈 링(gâteau des rois)이 일반적이다. 안에 작은 인형(fève)을 숨기고, 가장 어린 사람이 식탁 밑에 들어가 조각을 누구에게 줄지 정한다. 페브를 찾은 사람은 종이 왕관을 쓰고 왕이나 여왕이 되며, 전통적으로 자신의 왕비나 왕을 고른다. 엘리제궁에서 열리는 갈레트 행사에서는 공화국에 왕이 없다는 이유로 페브를 넣지 않는 것이 관례다."),
("지방자치단체 예산의 '황금률'",
 "프랑스 코뮌의 예산은 운영(fonctionnement)과 투자(investissement) 두 부문으로 나뉘며, 법적으로 균형을 맞춰야 한다. 차입은 투자 지출을 위해서만 가능하고, 일상 운영비를 빚으로 메울 수는 없다. 이를 흔히 지방 재정의 règle d'or(황금률)라고 부른다. 따라서 시의 부채는 대개 학교·체육시설·도로 같은 투자 사업의 흔적이며, 선거 토론에서 부채는 '낭비'의 증거로도, '투자'의 증거로도 해석될 수 있다. 지방회계감사원(chambre régionale des comptes)이 지자체 재정을 감독한다."),
]
