# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, S, H = "Inès", "Mathieu", "Sofia", "Hélène"
AG, RO, CY = "Agnès", "Romain", "Aubanel"
GI, IN, PA, TX = "Gisèle", "Inaya", "M. Pagès", "Mme Texier"

META = {
    "part": 3, "ep": 36,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Campagne numérique",
    "title_ko": "디지털 캠페인",
    "place": "오베르캉프 아파트(Agora Stratégies) · 발몽쉬르루아르 아녜스 리비에르 선거 사무소(옛 신발 가게, 나시오날 거리) · 탄느리 지구 방문 유세 · 루아르 강변 자전거길과 근교 민박 / 2월, 1차 투표 4주 전",
    "chars": "이네스, 마티외, 소피아(Agora 데이터 담당), 엘렌(전화), 아녜스 리비에르(후보, « Valmont Ensemble »), 로맹 라콤(리비에르 캠프 선거대책본부장), 시릴 오바넬(데이터 업체 Sondelys 영업이사), 지젤 페로(자원봉사자, 옛 섬유 공장 직조공), 이나야(대학생 자원봉사자), 파제스 씨·텍시에 부인(탄느리 지구 주민)",
    "work": "데이터 업체가 '정치 성향 점수'를 붙인 유권자 3만 8천 명 파일과 문자 발송을 1만 8천 유로에 제안 — 마이크로타기팅의 효용과 위험, RGPD 제9조(민감 정보)와 동의, 선거법의 유료 정치 광고 금지, Agora 원칙에 따른 구매 거부, 대안으로 자원봉사자 85명의 방문 유세(1만 5천 가구)와 주민이 직접 말하는 지역 콘텐츠, 캠프의 '디지털 윤리 헌장' 공개",
    "life": "크루아상과 함께 온 소피아의 '딜레마', 비 오는 토요일의 초인종 누르기, 휴대폰을 끈 디지털 디톡스 주말 — 루아르 강변 자전거 여행과 민박의 장작불",
    "focus": "디지털·데이터 보호 어휘(données sensibles, consentement, ciblage), 찬반 논증(d'un côté... de l'autre, certes... il n'en reste pas moins que), 윤리 표현, 양보의 도치(si efficace soit-elle), 문어 도치(aussi + 도치, encore faut-il), quand bien même + 조건법, 접속법(il est exclu que, sans que), 명사화",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "제37화 Entre deux tours — 1차 투표 개표의 밤, 메르시에 33%·리비에르 29%·카드두르 16%, 그리고 일주일 안에 끝내야 하는 명부 합병 협상.",
}

D = [
# ---------- 1. Ouverture : des croissants et un dilemme ----------
(None, "Un mardi de février, 7 h 40. Oberkampf, l'appartement qui sert de bureau à Agora Stratégies. Il pleut. Figaro dort sur l'imprimante. On sonne.",
       "2월의 어느 화요일, 오전 7시 40분. 오베르캉프, Agora Stratégies의 사무실을 겸하는 아파트. 비가 온다. 피가로는 프린터 위에서 자고 있다. 초인종이 울린다."),
(MA, "C'est Sofia. Elle m'a écrit à six heures : « J'arrive avec des croissants et un dilemme. »", "소피아야. 6시에 문자 보냈더라. '크루아상이랑 딜레마 하나 들고 갈게요.'"),
(I, "Des croissants avant huit heures, c'est que le dilemme est sérieux. Pousse Figaro de l'imprimante, tu veux bien ?", "8시 전에 크루아상이면 딜레마가 심각하다는 거지. 피가로 좀 프린터에서 내려 줄래?"),
(S, "Salut, vous deux ! Pain au chocolat pour Inès, croissant pour Mathieu, et pour moi, le café le plus serré de la maison. J'ai dormi trois heures.", "안녕, 두 사람! 이네스는 팽오쇼콜라, 마티외는 크루아상, 그리고 나는 이 집에서 제일 진한 커피. 세 시간밖에 못 잤어."),
(MA, "Trois heures ? Ne me dis pas que tu as encore relu les commentaires sous la rumeur de la semaine dernière.", "세 시간? 설마 지난주 그 루머 밑에 달린 댓글을 또 읽은 건 아니지?"),
(S, "Non, ça, j'ai arrêté, promis. Cette nuit, c'est ce truc-là qui m'a tenue éveillée.", "아니, 그건 끊었어, 진짜야. 어젯밤엔 이게 날 잠 못 들게 했어."),
(None, "Elle pose sur la table une brochure glacée : « Sondelys — Le ciblage électoral de précision ». Mathieu la feuillette ; Inès lit par-dessus son épaule.",
       "소피아가 탁자 위에 광택지 브로슈어를 올려놓는다. 'Sondelys — 정밀 선거 타기팅'. 마티외가 넘겨 보고, 이네스는 그의 어깨 너머로 읽는다."),
(I, "« Le ciblage électoral de précision »... Ça commence mal. Qui t'a envoyé ça ?", "'정밀 선거 타기팅'이라... 시작부터 불길하네. 누가 이걸 보냈어?"),
(S, "Un certain Cyril Aubanel. Il a appelé l'équipe d'Agnès hier soir, et Romain Lacombe me l'a transféré avec un mot : « Notre arme secrète ? »", "시릴 오바넬이라는 사람. 어젯밤 아녜스 캠프에 전화했고, 로맹 라콤이 한마디 붙여서 나한테 넘겼어. '우리의 비밀 병기?'"),
(MA, "Romain... Notre directeur de campagne gagnerait le premier tour par pigeon voyageur s'il le pouvait.", "로맹이라... 우리 선대본부장은 할 수만 있다면 전서구로라도 1차 투표를 이기려 들걸."),
(S, "Ils proposent un fichier de trente-huit mille électeurs de Valmont, chacun avec un « score d'orientation probable ». Dix-huit mille euros, envoi de SMS compris.", "발몽 유권자 3만 8천 명 파일을 제안하는데, 사람마다 '예상 성향 점수'가 붙어 있어. 문자 발송까지 포함해서 1만 8천 유로."),
(I, "Dix-huit mille euros ? C'est près d'un cinquième de notre budget de campagne. Et ce score, il sort d'où ?", "1만 8천 유로? 우리 선거 예산의 거의 5분의 1이잖아. 그리고 그 점수는 어디서 나온 건데?"),
(S, "La brochure parle d'« habitudes de consommation » et de « données publiques enrichies ». Autrement dit, elle ne dit rien.", "브로슈어엔 '소비 습관'이니 '보강된 공개 데이터'니 하는 말만 있어. 다시 말해 아무 말도 안 하는 거지."),
(MA, "Quand une brochure est aussi vague sur l'origine de ses données, c'est rarement par modestie.", "브로슈어가 데이터 출처에 대해 이렇게 모호할 땐, 겸손해서 그런 경우는 드물지."),
(S, "Il fait sa démonstration jeudi, à onze heures, à la permanence d'Agnès.", "목요일 11시에 아녜스 선거 사무소에서 시연을 한대."),
(MA, "Jeudi ? Le jour où on devait enfin trier les factures de janvier. Tant pis pour les factures.", "목요일? 드디어 1월 영수증 정리하기로 한 날인데. 영수증은 어쩔 수 없지."),
(I, "Alors on y va tous les trois. D'ici là, personne ne signe rien. Figaro, ça vaut pour toi aussi : descends de cette brochure.", "그럼 셋 다 가자. 그때까진 아무도 아무것도 서명하지 않기. 피가로, 너도 마찬가지야. 그 브로슈어에서 내려와."),

# ---------- 2. La permanence : la démonstration ----------
(None, "Jeudi, 11 h. Valmont-sur-Loire, rue Nationale. La permanence d'Agnès Rivière occupe un ancien magasin de chaussures : affiches, cartons de tracts, une machine à café fatiguée.",
       "목요일 오전 11시. 발몽쉬르루아르, 나시오날 거리. 아녜스 리비에르의 선거 사무소는 옛 신발 가게 자리다. 포스터, 전단 상자, 지친 커피 머신."),
(AG, "Merci d'être venus tous les trois. Je vous préviens : Romain est très enthousiaste, et moi, je suis très perplexe.", "세 분 모두 와 주셔서 고마워요. 미리 말해 두죠. 로맹은 아주 신이 나 있고, 저는 아주 당혹스러워요."),
(RO, "Enthousiaste, oui. À quatre semaines du premier tour, nous sommes à vingt-six pour cent dans le dernier sondage, et Mercier à trente-deux. Il nous faut un accélérateur.", "신이 났죠. 1차 투표 4주 전인데 최근 여론조사에서 우리는 26%, 메르시에는 32%예요. 가속 장치가 필요합니다."),
(MA, "Un accélérateur, soit. Encore faut-il savoir ce qu'on met dans le moteur. Écoutons d'abord M. Aubanel.", "가속 장치, 좋아요. 다만 엔진에 뭘 넣는지는 알아야겠죠. 먼저 오바넬 씨 말을 들어 봅시다."),
(CY, "Bonjour à tous. Sondelys aide les candidats à parler aux bons électeurs, au bon moment, avec le bon message. Nous ne vendons pas des fichiers : nous vendons de l'efficacité.", "안녕하십니까. Sondelys는 후보들이 적절한 유권자에게, 적절한 때에, 적절한 메시지로 말하도록 돕습니다. 저희는 파일을 파는 게 아니라 효율을 팝니다."),
(I, "D'après votre devis, vous vendez tout de même un fichier. Trente-huit mille noms, avec des numéros de téléphone ?", "견적서를 보면 그래도 파일을 파시는 건데요. 이름 3만 8천 개, 전화번호도 포함인가요?"),
(CY, "Trente-huit mille profils, dont vingt-neuf mille avec un numéro de portable. Chaque profil est classé : sympathisant, indécis ou peu réceptif.", "프로필 3만 8천 개, 그중 2만 9천 개는 휴대폰 번호가 있습니다. 프로필마다 지지층, 부동층, 비우호층으로 분류돼 있고요."),
(MA, "Valmont compte environ quarante-six mille électeurs inscrits. Vous auriez donc un profil pour plus de quatre électeurs sur cinq ?", "발몽의 등록 유권자는 4만 6천 명 정도예요. 그러면 유권자 다섯 명 중 네 명 넘게 프로필을 갖고 계신 셈인가요?"),
(CY, "Plus de quatre sur cinq, oui. C'est ce qui fait notre force.", "다섯 중 넷 이상, 맞습니다. 그게 저희의 강점이죠."),
(I, "Classé selon quels critères, exactement ? Votre brochure évoque des habitudes de consommation.", "정확히 어떤 기준으로 분류하나요? 브로슈어에는 소비 습관이 언급돼 있던데요."),
(CY, "Nous croisons plusieurs sources que nos partenaires nous fournissent. Notre méthode est propriétaire ; vous comprendrez que je n'entre pas dans le détail.", "협력사들이 제공하는 여러 출처를 교차합니다. 저희 고유의 방법이라 세부 사항은 말씀드릴 수 없다는 점, 이해해 주시죠."),
(MA, "Ce que je comprends surtout, c'est que les habitants de Valmont, eux, n'en savent rien. Ont-ils accepté qu'on devine leurs opinions politiques ?", "제가 가장 잘 이해하는 건, 발몽 주민들은 그걸 전혀 모른다는 거예요. 그분들이 자기 정치 성향을 추측당하는 데 동의했나요?"),
(CY, "Ils ont accepté les conditions générales de nos partenaires. Tout est conforme ; nous avons un service juridique.", "협력사들의 이용 약관에 동의했습니다. 모두 적법합니다. 저희도 법무팀이 있어요."),
(I, "Les conditions générales d'une carte de fidélité ? Monsieur Aubanel, les opinions politiques sont des données sensibles au sens de l'article 9 du RGPD. Leur traitement est interdit, sauf exceptions strictement encadrées, comme le consentement explicite.",
    "포인트 카드 이용 약관 말인가요? 오바넬 씨, 정치적 견해는 RGPD 제9조가 말하는 민감 정보예요. 명시적 동의처럼 엄격하게 정해진 예외가 아니면 처리 자체가 금지돼 있어요."),
(CY, "Nous ne traitons pas des opinions, madame ; nous calculons des probabilités. La nuance est de taille.", "저희는 견해를 처리하지 않습니다, 부인. 확률을 계산하죠. 그 차이가 큽니다."),
(S, "Une probabilité d'opinion politique accolée à un nom et à un numéro, ça reste une donnée sur une opinion politique. Je doute fort que la CNIL voie la nuance.", "이름과 번호에 붙은 정치 성향 확률도 결국 정치적 견해에 관한 정보예요. CNIL이 그 차이를 알아줄지는 정말 의문이네요."),
(RO, "Attendez. Mercier tient cette ville depuis dix-huit ans ; il connaît chaque famille, chaque association. Nous, nous partons de zéro. Ce fichier, c'est juste une façon de rattraper notre retard.",
     "잠깐만요. 메르시에는 18년째 이 도시를 쥐고 있어요. 집집마다, 단체마다 다 알죠. 우린 맨땅에서 시작해요. 이 파일은 뒤처진 걸 따라잡는 방법일 뿐이에요."),
(AG, "Sur ce point, Romain n'a pas tort. M. Mercier a ses réseaux ; nous, nous avons quatre semaines.", "그 점에선 로맹 말이 틀리지 않아요. 메르시에 씨에겐 인맥이 있고, 우리에겐 4주가 있죠."),
(MA, "C'est vrai, et il faut le prendre au sérieux. Mais le réseau de M. Mercier, ce sont des gens qui le connaissent. Ce fichier, ce sont des gens qui ignorent jusqu'à leur présence dedans.",
     "맞아요, 그건 진지하게 받아들여야 해요. 하지만 메르시에 씨의 인맥은 그를 아는 사람들이에요. 이 파일은 자기가 거기 들어 있다는 사실조차 모르는 사람들이고요."),
(CY, "Si vous ne l'achetez pas, d'autres le feront. Je ne citerai personne, mais tout le monde n'a pas vos scrupules.", "여러분이 안 사면 다른 누군가가 삽니다. 누구라고는 말하지 않겠지만, 모두가 여러분처럼 양심의 가책을 느끼지는 않아요."),
(I, "Cet argument, je l'ai entendu dans toutes les salles de conseil où j'ai mis les pieds. Il n'a jamais rendu une pratique légale.", "그 논리는 제가 들어가 본 모든 이사회실에서 들었어요. 그 말 덕분에 어떤 관행이 합법이 된 적은 한 번도 없죠."),
(AG, "Et ces SMS, les gens les recevraient de la part de qui ?", "그 문자들은 사람들이 누구 이름으로 받게 되나요?"),
(CY, "De votre liste, naturellement, avec votre nom et une formule personnalisée : « Bonjour Madame Untel, Agnès Rivière pense à votre quartier. »", "당연히 후보님 명부 이름으로, 후보님 성함과 개인 맞춤 문구를 넣어서요. '아무개 님 안녕하세요, 아녜스 리비에르가 당신의 동네를 생각합니다.'"),
(AG, "Si je recevais ce message d'une candidate à qui je n'ai jamais donné mon numéro, je me demanderais d'abord comment elle l'a eu.", "제가 번호를 준 적도 없는 후보한테서 그런 문자를 받으면, 저는 먼저 그 사람이 내 번호를 어떻게 구했는지부터 궁금할 거예요."),
(I, "C'est la première question que les gens posent. Et après la rumeur du début du mois, il est exclu qu'on donne à qui que ce soit une raison de se la poser.", "사람들이 제일 먼저 묻는 게 바로 그거예요. 그리고 이달 초 루머 이후로, 누구에게든 그런 질문을 할 이유를 주는 건 있을 수 없는 일이에요."),
(RO, "Pardon, mais vous êtes des consultants ou des professeurs de morale ? Je pose la question franchement.", "실례지만 여러분은 컨설턴트입니까, 도덕 선생님입니까? 솔직하게 묻는 겁니다."),
(MA, "Franchement, alors : l'un n'empêche pas l'autre. On nous paie pour vous faire gagner, pas pour vous faire gagner à n'importe quel prix.", "그럼 솔직하게 답하죠. 둘 중 하나가 다른 하나를 막진 않아요. 우리는 후보님을 이기게 하라고 돈을 받지, 무슨 대가를 치르든 이기게 하라고 받는 게 아니에요."),
(CY, "Je vous laisse le devis. L'offre est valable jusqu'à lundi ; après, nos créneaux d'envoi seront pris.", "견적서는 두고 가겠습니다. 제안은 월요일까지 유효합니다. 그 뒤엔 발송 일정이 다 찹니다."),
(I, "Merci, monsieur Aubanel. Vous aurez notre réponse avant lundi. Agnès, nous vous remettrons demain une analyse complète, avec une alternative chiffrée.", "고맙습니다, 오바넬 씨. 월요일 전에 답을 드리죠. 아녜스, 내일 비용까지 계산한 대안과 함께 전체 분석을 드릴게요."),
(AG, "Ce que je veux, c'est une analyse honnête, pas un sermon. Montrez-moi les deux côtés, et laissez-moi décider.", "제가 원하는 건 설교가 아니라 정직한 분석이에요. 양쪽을 다 보여 주고 결정은 제게 맡겨 주세요."),
(MA, "C'est exactement ce que nous ferons. La décision vous appartient : c'est votre nom qui sera sur les bulletins.", "정확히 그렇게 할게요. 결정은 후보님 몫이에요. 투표용지에 오를 건 후보님 이름이니까요."),

# ---------- 3. Analyse : les deux côtés de la balance ----------
(None, "15 h. L'arrière-boutique de la permanence. Sofia a branché son ordinateur sur un vieux téléviseur. Mathieu tient le marqueur vert ; sur le paperboard, deux colonnes : « Pour » et « Contre ».",
       "오후 3시. 선거 사무소 뒷방. 소피아가 노트북을 낡은 텔레비전에 연결했다. 마티외가 초록 마커를 들고 있고, 플립차트에는 '찬성'과 '반대' 두 칸이 있다."),
(MA, "Agnès veut les deux côtés, elle les aura. Je commence par l'avocat du diable, puisque personne d'autre ne veut le rôle.", "아녜스는 양쪽을 원하니까 보여 드려야지. 아무도 그 역할을 안 하려 하니 내가 악마의 변호인부터 할게."),
(I, "Tu te portes volontaire ? Toi qui détestes les conflits ?", "자원하는 거야? 갈등이라면 질색하는 네가?"),
(MA, "Justement : c'est un conflit avec un paperboard, c'est le seul genre que j'aime. Bon. D'un côté, le ciblage permet de ne pas gaspiller d'énergie : on parle aux indécis plutôt qu'aux convaincus.",
     "그러니까. 플립차트랑 하는 갈등이잖아. 내가 좋아하는 유일한 종류지. 자, 한편으로 타기팅을 하면 힘을 낭비하지 않아. 이미 설득된 사람 말고 부동층에게 말을 걸 수 있으니까."),
(S, "Et j'avoue que, techniquement, ça me fascine. C'est mon métier, les données. Si on ne s'y intéresse pas, on laisse le terrain à ceux qui ont moins de scrupules.", "솔직히 기술적으로는 매혹적이야. 데이터가 내 일이니까. 우리가 관심을 끊으면 양심 없는 사람들한테 판을 넘겨주는 셈이고."),
(MA, "Deuxième argument pour : la jeunesse de Valmont ne lit pas les tracts. Elle vit sur son téléphone. Renoncer au numérique, ce serait renoncer à une génération.", "찬성 두 번째 논거. 발몽 젊은이들은 전단을 안 읽어. 휴대폰 안에서 살지. 디지털을 포기하면 한 세대를 포기하는 셈이야."),
(I, "Là, je te suis. Mais attention à ne pas tout mélanger : refuser d'acheter un fichier, ce n'est pas renoncer au numérique.", "그건 동의해. 하지만 다 뒤섞으면 안 돼. 파일 구매를 거절하는 게 디지털을 포기하는 건 아니야."),
(MA, "D'accord. Je passe de l'autre côté. Le contre, c'est toi qui le dresses ?", "좋아. 반대편으로 넘어갈게. 반대 칸은 네가 채울래?"),
(I, "Avec plaisir. Premièrement, le droit. Certes, M. Aubanel jure que tout est conforme, mais il ne nous montre ni ses sources ni les consentements. Nous ne pouvons pas nous porter garants d'un traitement dont nous ignorons tout.",
    "기꺼이. 첫째, 법. 오바넬 씨는 모든 게 적법하다고 맹세하지만, 출처도 동의서도 보여 주지 않아. 우리가 하나도 모르는 데이터 처리를 보증할 수는 없어."),
(MA, "Et le risque n'est pas théorique. Une sanction de la CNIL peut aller jusqu'à vingt millions d'euros ou quatre pour cent du chiffre d'affaires mondial. Pour Sondelys, pas pour nous, mais la plainte, elle, viserait aussi la liste.",
    "그리고 위험은 이론에 그치지 않아. CNIL 제재는 최대 2천만 유로 또는 전 세계 매출의 4%까지 갈 수 있어. 그건 Sondelys 얘기지만, 신고가 들어오면 우리 명부도 같이 겨냥될 거야."),
(I, "Deuxièmement, le code électoral. Dans les six mois qui précèdent le mois du scrutin, la publicité commerciale à des fins de propagande électorale est interdite par voie de presse ou de communication audiovisuelle. Les publications sponsorisées sur les réseaux sociaux en font partie.",
    "둘째, 선거법. 선거가 있는 달 이전 6개월 동안은 언론이나 시청각 통신 수단을 통한 선거 선전용 상업 광고가 금지돼. SNS 유료 홍보 게시물도 여기에 들어가."),
(MA, "Donc, même si on le voulait, on ne pourrait pas acheter de pub ciblée sur les réseaux en ce moment.", "그러니까 우리가 원한다 해도 지금은 SNS에 타깃 광고를 살 수 없다는 거네."),
(I, "Exactement. Troisièmement, les comptes de campagne. Ces dix-huit mille euros iraient dans le compte de campagne d'Agnès, ligne par ligne, et un adversaire pourrait les contester devant le juge.", "바로 그거야. 셋째, 선거 회계. 그 1만 8천 유로는 아녜스의 선거 회계에 한 줄 한 줄 들어가고, 상대 진영이 판사 앞에서 이의를 제기할 수도 있어."),
(S, "Quatrièmement, l'efficacité elle-même. Les études sur le ciblage sont beaucoup plus partagées que les brochures. Un SMS non sollicité, ça agace souvent plus que ça ne convainc.", "넷째, 효과 그 자체. 타기팅에 관한 연구들은 브로슈어보다 훨씬 의견이 갈려. 원치 않은 문자는 설득하기보다 짜증 나게 하는 경우가 많고."),
(MA, "Et cinquièmement, le plus simple : la confiance. Si un seul habitant découvre qu'on a acheté son profil, tout le discours d'Agnès sur la transparence s'effondre.", "그리고 다섯째, 가장 단순한 것. 신뢰. 주민 한 명이라도 우리가 자기 프로필을 샀다는 걸 알게 되면, 투명성에 관한 아녜스의 말은 다 무너져."),
(I, "Sans compter nos propres principes. Indépendance, transparence, vérité. On les a écrits sur ce même paperboard en octobre, Mathieu.", "우리 원칙은 말할 것도 없고. 독립성, 투명성, 진실. 10월에 바로 이 플립차트에 우리가 썼잖아, 마티외."),
(MA, "Attendez, c'est Hélène. Je mets le haut-parleur.", "잠깐, 엘렌이야. 스피커폰으로 할게."),
(H, "Bonjour, mes trois stratèges. Sofia m'a envoyé la brochure. Je l'ai lue dans le métro, et j'ai failli rater ma station.", "안녕, 나의 전략가 셋. 소피아가 브로슈어를 보내 줬어. 메트로에서 읽다가 내릴 역을 놓칠 뻔했지."),
(MA, "Alors, Hélène, ton avis ? Tu as été notre patronne assez longtemps pour nous dire quand on s'égare.", "그래서 엘렌, 의견은? 우리가 길을 잃을 때 말해 줄 만큼 오래 우리 상사였잖아."),
(H, "Mon avis tient en un proverbe : bien mal acquis ne profite jamais. Une victoire achetée avec des données volées, on la paie pendant tout le mandat.", "내 의견은 속담 하나로 충분해. 부정하게 얻은 것은 결코 이롭지 않다. 훔친 데이터로 산 승리는 임기 내내 값을 치르게 돼."),
(MA, "Romain, lui, répondrait qu'on ne fait pas d'omelette sans casser des œufs.", "로맹이라면 달걀을 깨지 않고는 오믈렛을 만들 수 없다고 대답하겠죠."),
(H, "Romain confond les œufs et les électeurs. Mais ne lui faites pas la leçon : apportez-lui une meilleure omelette. Un refus sans alternative, c'est un sermon.", "로맹은 달걀이랑 유권자를 헷갈리는 거야. 하지만 그에게 훈계하진 마. 더 나은 오믈렛을 가져가. 대안 없는 거절은 설교일 뿐이니까."),
(I, "On y travaille. Merci, Hélène.", "지금 그걸 만들고 있어요. 고마워요, 엘렌."),
(MA, "Alors, l'omelette. Ce qu'on a et que Mercier n'a pas, ce sont des bénévoles motivés. Combien en avons-nous, Sofia ?", "그럼 오믈렛. 메르시에에겐 없고 우리에겐 있는 것, 그건 의욕 넘치는 자원봉사자야. 몇 명이지, 소피아?"),
(S, "Quatre-vingt-cinq inscrits, dont une soixantaine vraiment actifs. Si chacun fait deux sorties par semaine, on peut frapper à quinze mille portes avant le premier tour.", "등록자 85명, 그중 실제로 활발한 사람은 60명쯤. 한 사람이 일주일에 두 번씩 나가면, 1차 투표 전에 1만 5천 가구의 문을 두드릴 수 있어."),
(I, "Coût : les tracts, le café et les chaussures. Quatre mille cinq cents euros, à peu près. Le quart de l'offre de Sondelys.", "비용은 전단, 커피, 그리고 신발값. 대략 4,500유로. Sondelys 제안의 4분의 1이야."),
(MA, "Et pour le numérique, du contenu local, sans un centime de publicité : des habitants qui parlent de leur quartier, filmés avec leur accord. On pourrait appeler ça « Valmont en vrai ».", "그리고 디지털은 광고비 한 푼 없이 지역 콘텐츠로. 주민들이 동의하에 촬영해서 자기 동네 이야기를 하는 거야. '진짜 발몽'이라고 부르면 어때."),
(I, "Plus une lettre d'information à laquelle on s'inscrit soi-même. Pas de fichier acheté : seulement des gens qui ont dit oui.", "거기에 각자 직접 신청하는 뉴스레터. 산 파일은 없고, '예'라고 말한 사람들만."),
(MA, "Il reste une inconnue : est-ce que le porte-à-porte marche encore, ici ? Les gens ouvrent-ils leur porte en février, sous la pluie ?", "아직 모르는 게 하나 있어. 여기서 방문 유세가 아직도 통할까? 2월에 비 오는데 사람들이 문을 열어 줄까?"),
(I, "Il n'y a qu'une façon de le savoir. Samedi, on frappe nous-mêmes.", "알아낼 방법은 하나뿐이야. 토요일에 우리가 직접 두드리는 거지."),
(MA, "Va pour samedi. Je sors mes bottes : à Valmont, la pluie n'a pas lu le programme.", "토요일로 하자. 장화 꺼내 둘게. 발몽의 비는 공약집을 안 읽었거든."),

# ---------- 4. Terrain : le porte-à-porte aux Tanneries ----------
(None, "Samedi, 10 h. Le quartier des Tanneries, des maisons ouvrières en briques au pied de l'ancienne filature. Une bruine fine. Douze bénévoles se répartissent les rues.",
       "토요일 오전 10시. 탄느리 지구, 옛 방적 공장 아래의 벽돌 노동자 주택가. 가는 이슬비. 자원봉사자 열두 명이 거리를 나눠 맡는다."),
(GI, "Je m'appelle Gisèle Perrot. J'ai été tisserande à la filature pendant trente et un ans. Ces rues-là, je les connais par cœur, alors suivez-moi, les Parisiens.", "지젤 페로예요. 방적 공장에서 31년 동안 직조공으로 일했죠. 이 거리들은 훤히 알아요. 그러니 따라오세요, 파리 양반들."),
(IN, "Et moi, c'est Inaya, je suis en deuxième année de droit à Tours. Gisèle m'a appris la règle numéro un : on ne parle jamais plus longtemps que la personne en face.", "저는 이나야예요. 투르에서 법학 2학년이에요. 지젤 할머니가 제1원칙을 가르쳐 주셨어요. 절대 상대보다 오래 말하지 않기."),
(I, "Excellente règle. Je connais des ministres qui devraient l'apprendre.", "훌륭한 원칙이네요. 그걸 배워야 할 장관들을 몇 명 알아요."),
(MA, "Alors je me tais et je prends des notes. Inès, tu sonnes ?", "그럼 난 입 다물고 메모할게. 이네스, 네가 초인종 누를래?"),
(I, "Je sonne. Sourire, carnet, et surtout pas de jargon de consultant.", "내가 누를게. 미소, 수첩, 그리고 컨설턴트 전문 용어는 절대 금지."),
(None, "Première porte. Un homme d'une soixantaine d'années ouvre, méfiant, un torchon à la main.", "첫 번째 문. 예순쯤 된 남자가 행주를 손에 든 채 경계하며 문을 연다."),
(PA, "C'est pour quoi ? Si c'est pour les élections, vous êtes tous pareils. Vous venez tous les six ans et après, on ne vous voit plus.", "무슨 일이오? 선거 때문이면 당신들은 다 똑같아. 6년마다 왔다가 그 뒤론 코빼기도 안 보이지."),
(GI, "Bonjour, monsieur Pagès. Vous ne me reconnaissez pas ? Gisèle, de l'atelier de tissage. On a fait la grève de 2009 ensemble.", "안녕하세요, 파제스 씨. 저 몰라보시겠어요? 직조 작업장의 지젤이요. 2009년 파업도 같이 했잖아요."),
(PA, "Gisèle ! Ça alors... Tu fais de la politique, maintenant ?", "지젤! 이런... 이제 정치를 하는 거야?"),
(GI, "Je fais du porte-à-porte pour Agnès Rivière. Elle veut transformer la filature en lieu pour les jeunes qui créent leur entreprise. Mathieu, expliquez-lui, vous.", "아녜스 리비에르를 위해 집집마다 다니는 거예요. 그분은 방적 공장을 창업하는 젊은이들을 위한 공간으로 바꾸고 싶어 해요. 마티외, 당신이 설명해 드려요."),
(MA, "Je préfère vous écouter d'abord, monsieur. Qu'est-ce qui vous ferait dire, dans six ans, que ce mandat a servi à quelque chose ?", "저는 먼저 말씀을 듣고 싶습니다. 6년 뒤에 이 임기가 쓸모 있었다고 말씀하시려면 무엇이 필요할까요?"),
(PA, "Que mon petit-fils trouve du travail ici, sans partir à Tours ou à Paris. C'est tout. Le reste, c'est du vent.", "내 손자가 투르나 파리로 떠나지 않고 여기서 일자리를 구하는 거지. 그게 다요. 나머진 다 허풍이고."),
(MA, "C'est noté, mot pour mot. Et si vous le voulez bien, Agnès viendra vous le dire en face : ce qu'elle peut promettre et ce qu'elle ne peut pas.", "한 마디도 빠짐없이 적었습니다. 괜찮으시다면 아녜스가 직접 와서 말씀드릴 거예요. 약속할 수 있는 것과 없는 것을요."),
(PA, "Qu'elle vienne. Je lui ferai un café. Mais je ne promets pas de voter pour elle.", "오라고 하쇼. 커피는 내주지. 하지만 표를 준다고 약속은 안 해."),
(I, "Personne ne vous le demande, monsieur. Elle viendra sans tract, juste avec ses réponses.", "아무도 그걸 요구하지 않아요. 그분은 전단 없이, 답만 들고 올 거예요."),
(None, "Trois maisons plus loin. Une femme d'une quarantaine d'années tient son téléphone à la main avant même que la sonnette ait fini de retentir.", "세 집 건너. 초인종 소리가 채 끝나기도 전에 마흔쯤 된 여자가 휴대폰을 손에 들고 나온다."),
(TX, "Vous êtes de quelle liste ? Parce que j'ai reçu ça hier soir, et je voudrais bien savoir qui l'a envoyé.", "어느 명부에서 오셨어요? 어젯밤에 이걸 받았는데, 누가 보냈는지 꼭 알고 싶어서요."),
(None, "Elle tend l'écran : « Bonjour Mme Texier, vous qui êtes attachée à la sécurité de votre quartier, ne restez pas indécise. » Aucune signature.", "그녀가 화면을 내민다. '텍시에 님 안녕하세요, 동네 안전을 중시하시는 분이시니 망설이지 마세요.' 서명은 없다."),
(TX, "Je n'ai jamais donné mon numéro à personne. Et « indécise », qui leur a dit que j'étais indécise ? Je me sens fichée, voilà.", "제 번호를 아무한테도 준 적 없어요. 그리고 '망설이는'이라니, 내가 마음을 못 정했다고 누가 그래요? 감시 대상 명단에 오른 기분이에요, 정말."),
(I, "Nous n'en savons rien, madame, et nous ne voulons accuser personne sans preuve. Mais je peux vous dire une chose : notre liste n'achète pas de fichiers.", "저희도 전혀 모릅니다, 부인. 증거 없이 누구도 탓하고 싶지 않고요. 다만 이것만은 말씀드릴 수 있어요. 저희 명부는 파일을 사지 않습니다."),
(IN, "Et vous avez des droits : vous pouvez demander à l'expéditeur d'où vient votre numéro, et faire un signalement à la CNIL. Je peux vous noter l'adresse du site.", "그리고 부인께는 권리가 있어요. 발신자에게 번호를 어디서 얻었는지 물을 수 있고, CNIL에 신고할 수도 있어요. 사이트 주소를 적어 드릴게요."),
(TX, "Merci, mademoiselle. Vous savez, c'est la première fois que quelqu'un frappe chez moi pour m'expliquer quelque chose au lieu de me vendre quelque chose.", "고마워요, 아가씨. 그거 알아요? 누가 우리 집 문을 두드려서 뭘 팔지 않고 뭔가를 설명해 준 건 이번이 처음이에요."),
(MA, "Si un jour vous voulez raconter ça devant une caméra, madame, ce ne serait pas pour nous faire de la publicité. Ce serait pour que vos voisins sachent qu'ils ont des droits.", "언젠가 이 이야기를 카메라 앞에서 해 주실 생각이 있으시면요, 부인, 저희 홍보를 위해서가 아니에요. 이웃분들도 자기 권리가 있다는 걸 알게 하려는 거죠."),
(TX, "Pourquoi pas... Laissez-moi y réfléchir. Repassez la semaine prochaine.", "그럴 수도 있겠네요... 생각해 볼게요. 다음 주에 다시 들러 줘요."),
(I, "Cinq heures, retour au QG. Mes chaussures sont deux éponges. Sofia, le bilan ?", "5시, 본부 복귀. 내 신발은 스펀지 두 짝이 됐어. 소피아, 결산은?"),
(S, "Bilan de la journée : trois cent quatre-vingts portes, cent soixante ouvertes, quatre-vingt-quinze vraies conversations. Et vingt-deux inscriptions à la lettre d'information, volontaires.", "오늘 결산. 380가구 방문, 160가구가 문을 열었고, 제대로 된 대화가 95건. 그리고 뉴스레터 자발적 신청이 22건."),
(I, "Quarante-deux pour cent d'ouverture, sous la pluie, en février. Aucune brochure glacée ne m'avait promis ça.", "2월에 비까지 오는데 문을 연 비율이 42%. 어떤 광택지 브로슈어도 이런 건 약속하지 않았는데."),
(MA, "Et Mme Texier nous a donné notre meilleur argument. Ce n'est pas nous qui le dirons à Agnès : c'est elle, dans « Valmont en vrai », si elle accepte d'être filmée.", "그리고 텍시에 부인이 우리에게 최고의 논거를 줬어. 아녜스에게 그걸 말하는 건 우리가 아니라 그분이 될 거야. 촬영에 동의하신다면 '진짜 발몽'에서."),

# ---------- 5. Décision : la charte ----------
(None, "Lundi, 9 h. La permanence. Agnès, Romain, les trois d'Agora. Sur la table, le devis de Sondelys et une note de six pages intitulée « Deux voies ».",
       "월요일 오전 9시. 선거 사무소. 아녜스, 로맹, 그리고 Agora의 세 사람. 탁자 위에 Sondelys 견적서와 '두 갈래 길'이라는 제목의 6쪽짜리 메모."),
(AG, "J'ai lu votre note deux fois, dont une à trois heures du matin. Allez-y, je vous écoute.", "메모를 두 번 읽었어요. 한 번은 새벽 3시에요. 시작하세요, 듣고 있어요."),
(MA, "Nous vous présentons les deux voies avec la même honnêteté. D'un côté, le fichier : un gain de temps réel, peut-être, et la possibilité de joindre vingt-neuf mille personnes en une soirée.", "두 갈래 길을 똑같이 정직하게 보여 드리겠습니다. 한쪽은 파일입니다. 어쩌면 실제로 시간을 아낄 수 있고, 하룻저녁에 2만 9천 명에게 연락할 수 있죠."),
(I, "De l'autre, un risque juridique que nous ne pouvons pas mesurer, faute de connaître l'origine des données, et un risque de réputation que nous mesurons très bien, depuis la rumeur.", "다른 쪽은 데이터 출처를 모르니 가늠할 수조차 없는 법적 위험, 그리고 루머 이후 우리가 아주 잘 가늠하고 있는 평판 위험이에요."),
(RO, "Vous parlez de risques. Moi, je parle de six points de retard. Si efficace soit votre porte-à-porte, il ne touchera jamais vingt-neuf mille personnes en quatre semaines.", "위험 얘기를 하시는데, 저는 6%포인트 뒤처진 얘기를 하는 겁니다. 방문 유세가 아무리 효과적이어도 4주 안에 2만 9천 명을 만날 수는 없어요."),
(I, "Non, il en touchera quinze mille. Mais toucher, ce n'est pas convaincre. Samedi, quatre-vingt-quinze conversations en une seule journée, avec douze bénévoles. Un SMS ne demande jamais : « Qu'est-ce qui compte pour vous ? »",
    "맞아요, 1만 5천 명을 만날 거예요. 하지만 만나는 것과 설득하는 건 달라요. 토요일 하루에 자원봉사자 열두 명이 95건의 대화를 했어요. 문자는 절대 '당신에게 중요한 게 뭔가요?'라고 묻지 않죠."),
(RO, "Et le jour où Mercier, lui, l'achète, ce fichier ? On aura l'air de quoi, avec nos principes et nos chaussures mouillées ?", "그런데 메르시에 쪽에서 그 파일을 사는 날이 오면요? 원칙이랑 젖은 신발만 가진 우리 꼴은 어떻게 되겠어요?"),
(MA, "Nous n'avons aucune information là-dessus, et nous ne lancerons aucune accusation. Mais quand bien même un adversaire le ferait, ce ne serait pas une raison pour l'imiter. Ce serait une raison de se distinguer.",
     "그에 대해 우리가 가진 정보는 전혀 없고, 어떤 비난도 하지 않을 겁니다. 하지만 설령 상대 진영이 그렇게 한다 해도 그걸 따라 할 이유는 되지 않아요. 오히려 차별화할 이유가 되죠."),
(I, "Il y a d'ailleurs une chose qu'Agnès peut faire et qu'aucun fichier ne permet : prendre un engagement public. Une charte numérique, publiée, que tous les candidats sont invités à signer.", "게다가 아녜스가 할 수 있지만 어떤 파일로도 할 수 없는 게 하나 있어요. 공개 약속이요. 공개된 디지털 헌장에, 모든 후보에게 서명하자고 제안하는 거죠."),
(AG, "Une charte... Qu'est-ce qu'il y aurait dedans, concrètement ?", "헌장이라... 구체적으로 뭐가 들어가나요?"),
(I, "Quatre engagements. Aucun achat de données personnelles. Aucun message envoyé sans consentement. Aucun contenu publié sans source vérifiable. Et un droit d'accès simple pour tout habitant qui demande ce que la campagne sait de lui.",
    "네 가지 약속이요. 개인정보 구매 없음. 동의 없는 메시지 발송 없음. 검증 가능한 출처 없는 콘텐츠 게시 없음. 그리고 캠프가 자기에 대해 무엇을 아는지 묻는 모든 주민에게 간단한 열람권 보장."),
(RO, "Et si les autres ne signent pas, on aura offert à nos adversaires une contrainte gratuite.", "그런데 다른 쪽이 서명하지 않으면 우리만 공짜로 족쇄를 차는 셈이잖아요."),
(AG, "Ou bien on aura offert aux électeurs une raison de nous croire. Romain, vous m'avez recrutée parce que j'étais une cheffe d'entreprise, pas une professionnelle de la politique. Dans mon entreprise, je n'ai jamais acheté un fichier client dont j'ignorais l'origine.",
     "아니면 유권자들에게 우리를 믿을 이유를 주는 셈이죠. 로맹, 당신이 나를 데려온 건 내가 정치 전문가가 아니라 기업가였기 때문이에요. 내 회사에서도 출처를 모르는 고객 파일은 한 번도 산 적이 없어요."),
(RO, "Je sais. Je voulais juste être sûr qu'on avait regardé la question en face. Je n'aurais pas voulu qu'on la balaie sans l'avoir examinée.", "알아요. 우리가 이 문제를 정면으로 봤다는 확신을 갖고 싶었을 뿐이에요. 따져 보지도 않고 쓸어 버리는 건 원치 않았거든요."),
(MA, "Et vous avez bien fait, Romain. Votre rôle, c'est de pousser ; le nôtre, de vérifier. Sans vous, cette note n'aurait pas été aussi solide.", "잘하신 거예요, 로맹. 당신의 역할은 밀어붙이는 거고, 우리 역할은 확인하는 거죠. 당신이 없었으면 이 메모가 이만큼 탄탄하지 않았을 거예요."),
(AG, "Bien. Alors voici ma décision. Nous n'achetons pas le fichier. Nous publions la charte jeudi. Et nous mettons toutes nos forces dans le porte-à-porte et dans « Valmont en vrai ».", "좋아요. 그럼 제 결정을 말하죠. 파일은 사지 않습니다. 헌장은 목요일에 공개해요. 그리고 모든 힘을 방문 유세와 '진짜 발몽'에 쏟습니다."),
(I, "Nous préparons le texte de la charte pour mercredi soir, avec une version juridique relue et une version que tout le monde comprend.", "헌장 문안은 수요일 저녁까지 준비할게요. 법률 검토를 거친 버전과 누구나 이해할 수 있는 버전 두 가지로요."),
(MA, "Nous en prenons acte. Permettez-moi d'ajouter une chose : c'est une décision qui vous coûte, et c'est précisément pour cela qu'elle compte.", "알겠습니다. 한 가지만 덧붙이죠. 이건 후보님께 대가가 따르는 결정이고, 바로 그래서 의미가 있습니다."),
(AG, "Et c'est moi qui appelle M. Aubanel. Je préfère qu'il l'entende de ma bouche.", "그리고 오바넬 씨에게는 제가 전화할게요. 제 입으로 직접 듣는 게 낫겠어요."),
(AG, "Allô ? Monsieur Aubanel, Agnès Rivière. Je vous remercie de votre proposition. Nous ne donnerons pas suite. Ce n'est pas une question de prix.", "여보세요? 오바넬 씨, 아녜스 리비에르입니다. 제안해 주셔서 감사합니다. 진행하지 않겠습니다. 가격 문제가 아니에요."),
(CY, "Je vois. Vous faites une erreur, madame, mais c'est votre droit. Bonne campagne quand même.", "알겠습니다. 실수하시는 거지만 그건 후보님 권리죠. 그래도 좋은 선거 되세요."),
(AG, "Merci. Et si un jour vous pouvez montrer d'où viennent vos données, rappelez-moi. Je serai curieuse de les voir.", "고마워요. 언젠가 데이터 출처를 보여 줄 수 있게 되면 다시 연락 주세요. 그땐 궁금해서라도 보고 싶네요."),
(I, "Voilà un appel que vous auriez pu nous déléguer. Vous avez bien fait de ne pas le faire.", "저희한테 맡기셔도 됐을 전화였어요. 그러지 않으신 게 잘하신 거예요."),
(None, "Le soir, 19 h. La salle des fêtes des Tanneries. Une soixantaine de bénévoles, des thermos de café, Gisèle au premier rang. Agnès monte sur une chaise.",
       "그날 저녁 7시. 탄느리 지구 마을 회관. 자원봉사자 60여 명, 커피 보온병들, 맨 앞줄의 지젤. 아녜스가 의자 위로 올라선다."),
(AG, "Mes amis, on nous a proposé ce matin de connaître vos voisins sans jamais leur parler. Nous avons dit non. Aussi aurons-nous besoin de vous tous, pendant quatre semaines, pour faire ce qu'aucun algorithme ne sait faire : écouter.",
     "여러분, 오늘 아침 우리는 이웃들과 한마디도 나누지 않고 그들을 알 수 있다는 제안을 받았습니다. 우리는 거절했습니다. 그러니 앞으로 4주 동안 여러분 모두가 필요합니다. 어떤 알고리즘도 할 줄 모르는 일, 바로 듣는 일을 하기 위해서요."),
(AG, "Quinze mille portes. Ce n'est pas un chiffre : ce sont quinze mille personnes à qui l'on doit au moins la vérité. Je compte sur vous.", "1만 5천 개의 문. 그건 숫자가 아닙니다. 최소한 진실은 들어야 할 1만 5천 명의 사람들이에요. 여러분을 믿습니다."),
(MA, "Rendez-vous samedi, huit heures et demie, devant la filature. Gisèle a déjà fait les équipes, et elle ne pardonne pas les retards.", "토요일 8시 반, 방적 공장 앞에서 만나요. 지젤 씨가 벌써 팀을 짰고, 지각은 용서하지 않으십니다."),
(S, "Inès, Mathieu... Agnès vient de me dire autre chose. Vous deux, ce week-end, vous êtes interdits de permanence. Ordre de la candidate.", "이네스, 마티외... 아녜스가 방금 다른 얘기도 했어. 두 사람은 이번 주말 선거 사무소 출입 금지래. 후보 명령이야."),
(MA, "Interdits ? Et qui tient la boutique ?", "출입 금지? 그럼 가게는 누가 지키고?"),
(S, "Moi. J'ai mes sources de données, figurez-vous. Toutes avec consentement. Allez, filez.", "내가. 나도 데이터 출처가 있거든요. 전부 동의받은 거로. 자, 얼른 가."),
(MA, "Tu as entendu, Inès ? Qui décide ? La candidate. Pas nous.", "들었어, 이네스? 누가 결정하는가? 후보야. 우리가 아니라."),
(I, "Pour une fois, je ne ferai pas appel de la décision.", "이번만큼은 그 결정에 항소하지 않을게."),

# ---------- 6. Week-end sans écran ----------
(None, "Samedi suivant, 9 h. Sur la Loire à vélo, à vingt kilomètres en aval de Valmont. Ciel blanc, vent froid. Deux vélos de location, deux téléphones éteints au fond d'une sacoche.",
       "다음 주 토요일 오전 9시. 루아르 강변 자전거길, 발몽에서 하류로 20킬로미터. 하얀 하늘, 찬 바람. 빌린 자전거 두 대, 짐 가방 깊숙이 꺼 둔 휴대폰 두 대."),
(I, "Ça fait quarante minutes que mon téléphone est éteint, et ma main droite le cherche toute seule. C'est grave, docteur ?", "휴대폰 끈 지 40분 됐는데, 오른손이 저절로 그걸 찾아. 심각한가요, 선생님?"),
(MA, "Syndrome classique de la consultante en sevrage. Traitement : deux jours de Loire, une soupe chaude et zéro notification.", "금단 증상에 시달리는 컨설턴트의 전형적인 증후군입니다. 처방은 루아르 이틀, 따뜻한 수프, 그리고 알림 제로."),
(I, "Tu te rends compte qu'on n'a pas eu un seul week-end sans travail depuis octobre ? Depuis Agora, en fait.", "10월 이후로 일 없는 주말이 단 한 번도 없었다는 거 알아? 사실 Agora 시작한 뒤로 쭉."),
(MA, "Je m'en rends compte. Et j'ai remarqué autre chose : on ne se parle plus que de Valmont. Même au lit, tu m'as demandé l'autre soir le taux d'abstention des dernières municipales.", "알지. 그리고 다른 것도 눈치챘어. 우린 이제 발몽 얘기밖에 안 해. 침대에서도 며칠 전 밤에 네가 지난 지방선거 기권율을 물어봤잖아."),
(I, "C'était une question légitime ! Bon... d'accord, c'était une question de trop.", "정당한 질문이었다고! 음... 그래, 하나 더 할 필요는 없는 질문이었어."),
(None, "Ils s'arrêtent devant une guinguette fermée pour l'hiver, chaises empilées, vue sur un banc de sable. Mathieu sort un thermos.", "두 사람은 겨울이라 문 닫은 강변 선술집 앞에 멈춘다. 의자는 쌓여 있고, 모래톱이 보인다. 마티외가 보온병을 꺼낸다."),
(MA, "Cette semaine, quand Aubanel parlait de « score d'orientation », je me suis demandé quel score un algorithme m'aurait donné, à moi.", "이번 주에 오바넬이 '성향 점수' 얘기를 할 때, 알고리즘이 나한테는 어떤 점수를 줬을까 궁금하더라."),
(I, "Facile. « Homme, la trentaine, Alsacien, achète des kilos de chou et des marqueurs verts. Profil : indécis chronique. »", "쉽지. '30대 남성, 알자스 출신, 양배추를 킬로 단위로, 초록 마커를 산다. 프로필: 만성 부동층.'"),
(MA, "Indécis ? Sur tout, peut-être. Sur toi, jamais. Je suis un sympathisant déclaré, et je n'ai pas besoin qu'on me devine.", "부동층? 다른 건 몰라도 너에 대해선 절대 아니야. 난 공개적으로 선언한 지지자고, 누가 추측해 줄 필요도 없어."),
(I, "Sympathisant déclaré... Attention, c'est une donnée sensible, ça.", "공개 선언한 지지자라... 조심해, 그거 민감 정보야."),
(MA, "Je t'autorise à la traiter. Consentement explicite, signé, irrévocable.", "그 정보를 처리하도록 허락할게. 명시적 동의, 서명 완료, 철회 불가."),
(I, "Alors je te fais une proposition, sans fichier et avec consentement. Un dimanche par mois, quoi qu'il arrive, pas de téléphone, pas de Valmont, pas de clients. Juste nous.", "그럼 제안 하나 할게. 파일 없이, 동의를 받아서. 한 달에 한 번 일요일은 무슨 일이 있어도 휴대폰도, 발몽도, 고객도 없이. 그냥 우리 둘만."),
(MA, "Même pendant les campagnes ?", "선거 기간에도?"),
(I, "Surtout pendant les campagnes. Agora, c'est notre cabinet. Je ne veux pas qu'il devienne notre seule maison.", "선거 기간엔 더더욱. Agora는 우리 회사야. 그게 우리의 유일한 집이 되는 건 싫어."),
(MA, "Accepté. Je signe la charte. Tu as un stylo ?", "수락. 헌장에 서명할게. 펜 있어?"),
(None, "« J'ai mieux », dit-elle. Elle tire de sa poche le vieux marqueur vert et écrit sur la serviette en papier qui enveloppait leurs sandwiches : « Un dimanche par mois. » Puis, en dessous, les trois questions.",
       "'더 좋은 게 있지.' 이네스가 주머니에서 낡은 초록 마커를 꺼내, 샌드위치를 쌌던 종이 냅킨에 쓴다. '한 달에 한 번 일요일.' 그리고 그 아래에 세 가지 질문."),
(MA, "Tu m'as volé mon marqueur. Bon. Quel est le vrai problème ?", "내 마커를 훔쳤네. 좋아. 진짜 문제는 무엇인가?"),
(I, "Qu'on travaille trop bien ensemble pour penser à vivre ensemble. Qui décide ? Nous deux, une fois par mois, et sans algorithme.", "우리가 같이 일을 너무 잘해서 같이 사는 걸 생각할 틈이 없다는 거. 누가 결정하는가? 우리 둘이, 한 달에 한 번, 알고리즘 없이."),
(None, "Dimanche, 18 h. Sur le quai de la gare de Valmont, ils rallument leurs téléphones. Quarante-sept notifications. En haut de l'écran, un message de Sofia.", "일요일 오후 6시. 발몽역 플랫폼에서 두 사람은 휴대폰을 다시 켠다. 알림 47개. 화면 맨 위에 소피아의 메시지."),
(MA, "Sofia : « Trois mille cent portes ce week-end. Mme Texier a accepté d'être filmée. Et Romain a signé la charte en premier. Revenez, on a un premier tour à gagner. »", "소피아야. '이번 주말 3,100가구 방문. 텍시에 부인이 촬영에 동의했어. 그리고 로맹이 제일 먼저 헌장에 서명했어. 돌아와, 이겨야 할 1차 투표가 있잖아.'"),
(I, "Romain, en premier ? Hélène avait raison : il fallait lui apporter une meilleure omelette.", "로맹이 제일 먼저? 엘렌 말이 맞았네. 더 나은 오믈렛을 가져가야 했던 거야."),
(MA, "Alors, troisième question. Que fait-on lundi ?", "그럼 세 번째 질문. 월요일엔 뭘 하지?"),
(I, "Lundi, il reste trois semaines avant le premier tour. On frappe aux portes, et on prépare le soir du résultat, quel qu'il soit.", "월요일이면 1차 투표까지 3주 남아. 문을 두드리고, 결과가 어떻든 개표의 밤을 준비하는 거지."),
]

VOCAB = [
("B2", "le ciblage / cibler", "타기팅, 겨냥 / 겨냥하다", "le ciblage électoral. une cible = 과녁·대상. microciblage는 아주 잘게 나눈 대상별 맞춤 메시지."),
("C1", "les données sensibles", "민감 정보", "RGPD 제9조: 정치적 견해, 종교, 건강, 출신 인종 등. 원칙적으로 처리 금지, 명시적 동의 등 예외만 허용."),
("B2", "le consentement (explicite)", "(명시적) 동의", "donner / recueillir son consentement. sans consentement = 동의 없이."),
("C1", "le traitement (de données)", "(데이터) 처리", "법률 용어로 수집·저장·분석·전송 등 모든 작업을 포괄. un responsable de traitement = 처리 책임자."),
("B2", "les conditions générales", "이용 약관", "conditions générales d'utilisation(CGU) / de vente(CGV). 아무도 끝까지 안 읽는 바로 그 문서."),
("B2", "un fichier (d'électeurs, de clients)", "명단 파일, 명부", "être fiché = 명단·감시 대상에 오르다. « Je me sens fichée. »"),
("B2", "une permanence (de campagne)", "선거 사무소, 상설 사무실", "후보·의원이 주민을 만나는 사무실. tenir une permanence = 정해진 시간에 자리를 지키다."),
("B2", "le porte-à-porte", "가가호호 방문 (유세)", "faire du porte-à-porte. 영업에서도 '방문 판매'로 쓴다."),
("B2", "un(e) bénévole", "자원봉사자", "le bénévolat = 자원봉사. volontaire보다 '무보수'에 초점."),
("B2", "un tract", "전단, 유인물", "distribuer des tracts. 정치·노조 활동의 기본 도구."),
("C1", "la propagande électorale", "선거 운동(선전)", "프랑스 선거법의 공식 용어로 부정적 뉘앙스 없이 '선거 홍보물·선거 운동'을 뜻함."),
("C1", "un compte de campagne", "선거 비용 회계", "후보는 지출·수입을 신고해야 하며 CNCCFP가 심사한다."),
("B2", "une publication sponsorisée", "유료 홍보 게시물", "SNS의 광고 게시물. contenu sponsorisé."),
("B2", "l'avocat du diable", "악마의 변호인, 일부러 반론을 펴는 사람", "se faire l'avocat du diable / jouer l'avocat du diable."),
("C1", "se porter garant(e) de qc (복습)", "~을 보증하다", "« Nous ne pouvons pas nous porter garants d'un traitement dont nous ignorons tout. »"),
("C1", "ne pas donner suite (à qc)", "(제안 등을) 진행하지 않다, 거절하다", "편지·통화에서 쓰는 정중한 거절 표현. Nous ne donnerons pas suite à votre offre."),
("B2", "faire la leçon à qn", "~에게 훈계하다", "un sermon = 설교·잔소리. « Ne lui faites pas la leçon. »"),
("C1", "Bien mal acquis ne profite jamais.", "부정하게 얻은 것은 결코 이롭지 않다", "속담. 부당 이득은 결국 화가 된다는 뜻."),
("B2", "On ne fait pas d'omelette sans casser des œufs.", "달걀을 깨지 않고는 오믈렛을 못 만든다", "목적을 위해선 희생이 불가피하다는 속담. 이번 화에서는 반박의 대상."),
("C1", "le scrupule / sans scrupules", "양심의 가책 / 파렴치한", "avoir des scrupules à faire qc = ~하기를 꺼리다. tout le monde n'a pas vos scrupules."),
("B2", "être en sevrage", "금단 상태다, (중독을) 끊는 중이다", "le sevrage tabagique. 농담으로 휴대폰·커피에도 쓴다."),
("B1", "une guinguette", "강변 선술집·무도장", "센강·마른강·루아르강 변의 야외 카페. 여름에만 여는 곳이 많다."),
("B1", "une sacoche", "(자전거) 짐 가방, 가방", "les sacoches de vélo. 노트북 가방도 sacoche."),
("B2", "tenir la boutique", "가게를 지키다, 자리를 맡다", "구어. 누군가 없을 때 일을 대신 맡는다는 뜻."),
]

GRAM = [
("B2", "찬반 논증의 틀: d'un côté... de l'autre / certes... mais",
 "« D'un côté, le ciblage permet de ne pas gaspiller d'énergie. » « D'un côté, le fichier : un gain de temps réel... » « De l'autre, un risque juridique que nous ne pouvons pas mesurer. » « Certes, M. Aubanel jure que tout est conforme, mais il ne nous montre ni ses sources ni les consentements. » 양쪽 논거를 나란히 놓을 때는 d'un côté / de l'autre (côté), 상대 논거를 일단 인정하고 뒤집을 때는 certes... mais를 쓴다. 나열은 premièrement, deuxièmement... 처럼 서수 부사로 구조를 보여 준다."),
("C1", "양보의 도치: si + 형용사 + 접속법 + 주어",
 "« Si efficace soit votre porte-à-porte, il ne touchera jamais vingt-neuf mille personnes. » = Aussi efficace que soit... / Bien que votre porte-à-porte soit efficace... '아무리 ~하더라도'라는 뜻의 문어적 구문. si 뒤에 형용사, 그다음 접속법 동사와 주어를 도치한다. 명사 주어는 동사 뒤에 그대로 두고, 대명사 주어는 하이픈으로 붙인다: si brillants soient-ils."),
("C1", "quand bien même + 조건법",
 "« Quand bien même un adversaire le ferait, ce ne serait pas une raison pour l'imiter. » '설령 ~한다 해도'. même si보다 강하고 격식 있는 양보 표현으로, 두 절 모두 조건법을 쓴다(même si 뒤에는 조건법을 쓰지 않는 것과 대조). 30화의 quand bien même 복습."),
("C1", "문두의 aussi와 encore + 주어 도치",
 "« Aussi aurons-nous besoin de vous tous, pendant quatre semaines... » 문두 aussi는 '그러므로(donc)'의 뜻이며 주어-동사 도치를 동반한다(문장 중간의 aussi '또한'과 구별). « Encore faut-il savoir ce qu'on met dans le moteur. » encore faut-il... = '다만 ~해야 한다', 앞말에 조건을 다는 연설·논증 표현."),
("B2", "il est exclu que / sans que + 접속법, 그리고 qui que ce soit",
 "« Il est exclu qu'on donne à qui que ce soit une raison de se la poser. » il est exclu que(~은 있을 수 없다)는 배제·불가능을 나타내 접속법을 요구한다. qui que ce soit = '누구든', 부정·배제 문맥에서 '아무에게도'. « Je n'aurais pas voulu qu'on la balaie sans l'avoir examinée. » sans que + 접속법은 주어가 다를 때, 같으면 sans + 부정사(sans l'avoir examinée, 완료 부정사)."),
("B2", "faute de + 명사/부정사: 원인의 결여",
 "« un risque juridique que nous ne pouvons pas mesurer, faute de connaître l'origine des données » '~이 없어서, ~하지 못하므로'. faute de temps, faute de preuves. 비슷한 구문 « sans compter nos propres principes »(~은 말할 것도 없고)도 논거를 덧붙일 때 유용하다."),
("C1", "명사화(nominalisation)와 ne... que",
 "« Refuser d'acheter un fichier, ce n'est pas renoncer au numérique. » → 명사화하면 le refus de l'achat d'un fichier n'est pas un renoncement au numérique. 정책 문서·헌장은 이렇게 동사를 명사로 바꿔 압축한다: « Aucun achat de données personnelles. Aucun message envoyé sans consentement. » 한편 « on ne se parle plus que de Valmont »에서 ne... plus que는 '이제 ~만'이라는 제한(ne... que)에 '더 이상'(plus)이 겹친 것."),
("B2", "강조의 c'est... qui / ce n'est pas... c'est",
 "« C'est moi qui appelle M. Aubanel. » « Ce n'est pas nous qui le dirons à Agnès : c'est elle. » « Ce n'est pas une question de prix. » 대조 강조(ce n'est pas A, c'est B)는 연설과 협상에서 논점을 바로잡는 데 자주 쓰인다. 동사는 강조된 주어에 일치한다(c'est moi qui appelle)."),
]

CULTURE = [
("RGPD와 CNIL: 정치적 견해는 '민감 정보'",
 "유럽연합 일반개인정보보호규정(RGPD, 영어 GDPR)은 2018년부터 적용되었다. 제9조는 정치적 견해·종교·건강 등을 '특수 범주의 정보'로 정하고, 명시적 동의 등 제한된 예외가 아니면 처리를 금지한다. 위반 시 과징금은 최대 2천만 유로 또는 전 세계 연 매출의 4%다. 프랑스의 감독 기관 CNIL(국가정보자유위원회)은 선거 때마다 후보와 정당을 위한 정치 커뮤니케이션 지침을 내고, 유권자의 신고를 받는다. 누구든 자신에 관한 정보를 누가, 어디서 얻었는지 물을 수 있는 열람권(droit d'accès)을 가진다."),
("프랑스 선거법과 디지털 선거 운동",
 "선거법(Code électoral) L.52-1조는 선거가 있는 달의 첫날 이전 6개월 동안 언론이나 시청각 통신 수단을 통한 상업 광고를 선거 선전에 쓰는 것을 금지하며, SNS 유료 홍보 게시물도 이 금지에 해당하는 것으로 해석된다. 후보의 모든 선거 비용은 선거 회계(compte de campagne)에 기록되어 국가선거회계·정치자금위원회(CNCCFP)의 심사를 받고, 일정 규모 이상의 지자체 선거에는 지출 상한이 있다. 반면 무료 SNS 게시, 뉴스레터(동의 기반), 집회와 방문 유세는 널리 허용된 선거 운동 방식이다."),
("Porte-à-porte, 프랑스 선거의 오래된 기술",
 "프랑스 지방선거에서 방문 유세(porte-à-porte)와 장터 전단 배포(tractage)는 지금도 핵심적인 선거 운동이다. 자원봉사자들은 보통 두 명씩 짝을 지어 동네를 나눠 돌며, 짧은 대화와 주민의 관심사 기록에 집중한다. 유권자 명부(liste électorale)는 선거 목적에 한해 유권자·후보·정당이 열람하고 사본을 받을 수 있지만, 상업적 이용은 금지된다. 선거 전날 자정부터는 선거 운동 자체가 금지되는 '선거 침묵' 기간이 시작된다."),
]
