# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, S = "Inès", "Mathieu", "Sofia"
LU, AN, DA = "Lucas", "Antoine", "Danielle"
OC, SB = "Castelli", "Samir"
FA, GI, MR = "Fanfan", "Giordano", "Maëlle"

META = {
    "part": 3, "ep": 42,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Une région qui attire",
    "title_ko": "끌어당기는 지역",
    "place": "마르세유 르 파니에, 뤼카의 식당 « Le Fanal » · 라 졸리에트의 Provence Attractivité 본부 회의실 « Frioul » · 마르세유 항구 동쪽 부두와 선박 수리 조선소 · 옛 설탕 창고를 개조한 스타트업 캠퍼스 « La Fabrique du Large » · 레스타크의 작은 항구 / 이듬해 봄, 4월의 2주",
    "chars": "이네스, 마티외, 소피아(화상), 뤼카 마르케티(이네스의 남동생, 요리사), 앙투안·다니엘 마르케티(이네스의 부모), 오리안 카스텔리(Provence Attractivité 사무총장), 사미르 부지드(부사무총장, 관광·디지털 담당), 팡팡(프랑수아 오르시니, 항만 하역반장), 조르다노(선박 수리 조선소 사장), 마엘 리날디(스타트업 Quaivolt 창업자)",
    "work": "마르세유 권역의 가상 투자유치 기관 « Provence Attractivité »(직원 38명, 연 예산 1,400만 유로)의 5개년 전략 — 관광·행사 60% 편중 예산, 발표 일자리 1,900개 중 남은 1,200개, 지속 일자리당 비용 비교, 떠나는 젊은 엔지니어와 주거 문제, 유휴 산업 부지 80헥타르. 결론: 산업·항만 중심 전략 « Produire, retenir, accueillir »",
    "life": "뤼카의 첫 식당 개업식과 가족 총출동, 앙투안의 서툰 건배사, 항구에서 드러난 아버지의 옛 이야기, 토요일 아침 레스타크 항구에서 나눈 부녀의 대화, 마침내 마티외에게 tu를 허락한 앙투안",
    "focus": "전략 문서 문체(제안의 조건법), 비교·종합 표현(moins... que, contre, soit, plutôt que), Encore faut-il que + 접속법 도치, n'en... pas moins, ce + 전치사 + quoi / sans quoi, 명사화 구문, 지역 개발·항만 어휘",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "제43화 Conflit d'intérêts — 파리로 돌아온 아침, 르 쿠리에 드 파리 기자의 전화: 뤼카의 식당이 « Provence Attractivité » 지원금을 받았다는 기사가 곧 나간다.",
}

D = [
# ---------- 1. Ouverture : l'inauguration du Fanal ----------
(None, "Un vendredi soir d'avril, à Marseille. Dans une ruelle du Panier, un petit restaurant aux volets bleus : « Le Fanal ». Des guirlandes, des voisins sur le trottoir, une odeur de fenouil grillé.",
       "4월의 어느 금요일 저녁, 마르세유. 르 파니에의 골목에 파란 덧창을 단 작은 식당 « Le Fanal »이 있다. 꼬마전구 장식, 길가에 나온 이웃들, 회향 굽는 냄새."),
(LU, "Grande sœur ! Tu es venue ! Et toi, Mathieu, attrape ce tablier, j'ai besoin de bras.", "누나! 왔구나! 그리고 마티외, 이 앞치마 받아. 일손이 필요해."),
(I, "Tu plaisantes ? On a pris le train de six heures pour ton inauguration. Montre-moi tout. « Le Fanal »... C'est toi qui as trouvé le nom ?",
    "농담하니? 네 개업식 때문에 6시 기차 타고 왔어. 전부 보여 줘. « Le Fanal »이라... 이름은 네가 지은 거야?"),
(LU, "Un fanal, c'est la lanterne qu'on accroche aux bateaux. Papa disait toujours qu'il en fallait un pour retrouver le chemin du port.",
     "fanal은 배에 매다는 등불이야. 아빠가 늘 그랬잖아, 항구로 돌아오는 길을 찾으려면 그게 하나 있어야 한다고."),
(MA, "Trente-deux couverts, une cuisine ouverte, les toits du Panier par la fenêtre... Lucas, c'est magnifique. Dix ans dans les cuisines des autres, et enfin la tienne.",
     "서른두 석, 오픈 키친, 창밖으로 보이는 파니에의 지붕들... 뤼카, 정말 멋지다. 10년을 남의 주방에서 일하다가 드디어 네 주방이네."),
(LU, "Et une terrasse de douze places ! Celle-là, je ne l'aurais jamais eue sans un sacré coup de pouce. Des mois de paperasse à n'en plus finir... Je te raconterai.",
     "그리고 열두 자리짜리 테라스! 이건 엄청난 도움이 없었으면 절대 못 가졌을 거야. 몇 달 동안 끝도 없는 서류 작업이었지... 나중에 얘기해 줄게."),
(I, "Pardon, ça vibre... C'est Mme Castelli, ma cliente. ... Oui, madame, lundi neuf heures, c'est noté. ... Excuse-moi, Lucas. Tu disais ? De la paperasse ?",
    "미안, 전화가... 내 고객 카스텔리 씨야. ...네, 월요일 9시, 알겠습니다. ...미안, 뤼카. 뭐라고 했어? 서류 작업?"),
(LU, "Rien, rien. Ce soir, on ne parle pas boulot. Va plutôt embrasser maman : elle pleure depuis cinq heures de l'après-midi.",
     "아무것도 아냐. 오늘 밤은 일 얘기 금지야. 그보다 엄마한테 가서 인사나 해. 오후 5시부터 울고 계셔."),
(None, "Sur le comptoir, sous une pile de menus, dépasse une brochure bleue frappée d'un logo : « Provence Attractivité ». Personne n'y prête attention.",
       "카운터 위, 메뉴판 더미 아래로 로고가 찍힌 파란 안내 책자가 삐져나와 있다. « Provence Attractivité ». 아무도 눈여겨보지 않는다."),
(None, "Sur la vitrine, juste à côté de la chaise d'Inès, un petit autocollant vert. Elle y jette un coup d'œil distrait — un label bio, sans doute — et se retourne vers la salle.",
       "유리창에, 이네스의 의자 바로 옆에 작은 초록색 스티커가 붙어 있다. 이네스는 무심코 힐끗 본다. 유기농 인증 마크겠지. 그리고 다시 홀 쪽으로 몸을 돌린다."),
(DA, "Ma chérie ! Tu as vu ton frère, en veste blanche ? ... Mathieu, vous avez maigri. Elle ne vous nourrit pas, à Paris ?",
     "우리 딸! 하얀 조리복 입은 네 동생 봤니? ...마티외, 살이 빠졌네요. 파리에서 얘가 밥을 안 해 줘요?"),
(MA, "C'est moi qui cuisine, madame Marchetti. Elle, elle fait les tableaux.", "요리는 제가 해요, 마르케티 부인. 이네스는 표를 만들고요."),
(I, "Et les courses, et le budget du ménage. Maman, ne l'encourage pas, il va prendre la grosse tête.", "장보기랑 가계부도 내가 하지. 엄마, 맞장구치지 마. 저 사람 우쭐해진단 말이야."),
(None, "Antoine tape sur son verre avec une fourchette. Le silence se fait.", "앙투안이 포크로 잔을 두드린다. 조용해진다."),
(AN, "Un mot, un seul : je ne suis pas un homme de discours. Il y a dix-sept ans, un Marchetti a fermé une entreprise. Ce soir, un Marchetti en ouvre une. ... Voilà. À Lucas. Santé !",
     "한마디만 하겠소. 딱 한마디. 난 연설하는 사람이 아니라서. 17년 전, 마르케티 한 사람이 회사를 닫았지. 오늘 밤, 마르케티 한 사람이 회사를 연다. ...이상이오. 뤼카를 위하여. 건배!"),
(LU, "Merci, papa. Et à ceux qui m'ont donné un coup de pouce ! Ils se reconnaîtront.", "고마워, 아빠. 그리고 나를 밀어 준 분들을 위하여! 누군지는 본인들이 알 거야."),
(I, "Le coup de pouce, c'est papa : il s'est porté caution auprès de la banque. Et ce discours, il l'a répété toute la semaine, j'en mettrais ma main au feu.",
    "그 '밀어 준 사람'은 아빠야. 은행에 보증을 서 줬거든. 그리고 저 건배사, 일주일 내내 연습했을 거야. 장담해."),
(MA, "Ton père et toi, vous avez le même défaut : vous préparez tout, même l'improvisation.", "너랑 너희 아버지는 똑같은 단점이 있어. 뭐든 준비해. 즉흥 연설까지도."),
(I, "Ce n'est pas un défaut, c'est une méthode. Et lundi, la méthode reprend du service : trois mois de chiffres épluchés depuis Paris, et enfin le terrain.", "그건 단점이 아니라 방법론이야. 그리고 월요일엔 그 방법론이 다시 일하러 가. 석 달 동안 파리에서 숫자를 파헤쳤으니, 드디어 현장이야."),

# ---------- 2. Le client : une agence qui fait beaucoup et change peu ----------
(None, "Lundi, 9 h. Le siège de Provence Attractivité, dans un immeuble de verre de La Joliette, face aux bassins. Salle « Frioul ». Après trois mois d'analyses menées depuis Paris, première séance de travail sur place.",
       "월요일 오전 9시. 라 졸리에트의 유리 건물에 있는 Provence Attractivité 본부, 부두가 내려다보인다. 회의실 « Frioul ». 석 달간 파리에서 분석을 진행한 뒤 처음 갖는 현지 작업 회의다."),
(OC, "Madame Marchetti, monsieur Kessler, enfin en chair et en os ! Je vous présente Samir Bouzid, mon directeur adjoint, chargé du tourisme et du numérique. Il ne partage pas toutes mes inquiétudes, autant vous prévenir.",
     "마르케티 씨, 케슬레르 씨, 드디어 직접 뵙네요! 부사무총장이자 관광·디지털 담당인 사미르 부지드를 소개합니다. 이 사람은 제 걱정을 전부 공유하지는 않아요. 미리 말씀드리는 게 좋겠네요."),
(MA, "Bonjour, monsieur Bouzid. Tant mieux. On travaille toujours mieux quand on nous présente plus d'une version de l'histoire.", "안녕하세요, 부지드 씨. 잘됐네요. 이야기가 한 가지 버전만 있지 않을 때 일이 늘 더 잘되거든요."),
(I, "Madame Castelli, en janvier, vous nous avez parlé d'une agence qui « fait beaucoup et change peu ». Avant d'aller sur le terrain, nous aimerions l'entendre de votre bouche, devant M. Bouzid.",
    "카스텔리 씨, 1월에 '많이 하는데 바뀌는 건 별로 없는' 기관이라고 하셨죠. 현장에 나가기 전에 부지드 씨 앞에서 직접 한 번 더 듣고 싶습니다."),
(OC, "Provence Attractivité a été créée il y a quinze ans par la métropole, la région, la chambre de commerce et le port. Trente-huit salariés, quatorze millions d'euros de budget annuel. Notre mission : faire venir des entreprises, des talents et des visiteurs.",
     "Provence Attractivité는 15년 전 광역도시권, 레지옹, 상공회의소, 항만이 함께 세웠습니다. 직원 38명, 연 예산 1,400만 유로. 우리 임무는 기업과 인재와 방문객을 끌어오는 거예요."),
(I, "Votre rapport annuel affiche cent douze implantations d'entreprises en trois ans et mille neuf cents emplois annoncés. Mais votre note interne, elle, n'en compte plus que mille deux cents.",
    "연차 보고서에는 3년간 기업 입지 112건, 발표된 일자리 1,900개라고 나와 있죠. 그런데 내부 메모에는 1,200개밖에 남아 있지 않다고 되어 있어요."),
(MA, "Soit un taux de concrétisation d'à peine soixante-trois pour cent. Et comment se répartit votre budget ?", "그러니까 실현율이 겨우 63%라는 거군요. 예산은 어떻게 배분되어 있나요?"),
(OC, "Exactement. Le chiffre est beau, la réalité l'est moins. Quant au budget : soixante pour cent pour la promotion touristique et les grands événements, vingt-cinq pour les start-up, quinze pour l'industrie et la logistique.",
     "맞아요. 숫자는 근사한데 현실은 덜 그렇죠. 예산은 60%가 관광 홍보와 대형 행사, 25%는 스타트업, 15%는 산업과 물류입니다."),
(MA, "Quinze pour cent pour l'industrie, dans une métropole qui possède l'un des plus grands ports de Méditerranée ?", "지중해에서 손꼽히는 큰 항구를 가진 도시권에서 산업에 15%라고요?"),
(SB, "Je vous arrête tout de suite : ce choix n'a rien d'absurde. Le tourisme fait vivre des milliers de familles ici, et ce sont les grands événements qui mettent la région sur la carte du monde. Une usine, personne ne la photographie.",
     "바로 말씀드리죠. 그 선택은 전혀 터무니없지 않습니다. 이곳에선 관광으로 먹고사는 가족이 수천이고, 이 지역을 세계 지도에 올려놓는 건 대형 행사예요. 공장 사진을 찍는 사람은 아무도 없잖아요."),
(I, "Personne ne la photographie, mais elle verse des salaires douze mois sur douze. Cela dit, je ne demande qu'à être convaincue. Vous avez des chiffres sur la saisonnalité ?",
    "사진은 아무도 안 찍지만, 공장은 열두 달 내내 월급을 줍니다. 그렇긴 해도 저는 설득당할 준비가 되어 있어요. 계절성에 관한 수치가 있나요?"),
(SB, "Nous en avons. Ils ne sont pas tous flatteurs, je l'admets.", "있습니다. 전부 듣기 좋은 숫자는 아니라는 건 인정하죠."),
(MA, "Nous les regarderons ensemble, monsieur Bouzid. Sans procès d'intention.", "함께 보죠, 부지드 씨. 의도를 의심하지 않고요."),
(OC, "Voilà le cœur du problème. Notre conseil d'administration est coupé en deux : une moitié veut miser sur le tourisme et le numérique, l'autre sur le port et l'industrie. Le plan stratégique à cinq ans doit être voté en juin. Il me faut un document qui tranche.",
     "바로 그게 문제의 핵심이에요. 우리 이사회가 둘로 갈라져 있어요. 절반은 관광과 디지털에, 나머지 절반은 항만과 산업에 걸고 싶어 하죠. 5개년 전략 계획은 6월에 표결해야 합니다. 저는 결론을 내 주는 문서가 필요해요."),
(MA, "Permettez-moi une précision de méthode. Nous ne trancherons pas à la place de votre conseil. Nous lui présenterons des options chiffrées, avec leurs coûts et leurs risques, et une recommandation argumentée.",
     "방법론에 대해 한 가지만 짚고 가겠습니다. 저희가 이사회 대신 결정하지는 않습니다. 비용과 위험을 담은 수치화된 선택지들과 근거를 갖춘 권고안을 이사회에 제시할 겁니다."),
(OC, "Une recommandation, c'est exactement ce que je demande. Mais qu'elle soit claire. Les rapports qui concluent qu'« il faut tout faire à la fois », j'en ai un tiroir plein.",
     "권고안, 제가 원하는 게 바로 그거예요. 다만 분명해야 해요. '모든 걸 동시에 해야 한다'로 끝나는 보고서는 서랍 하나 가득 있거든요."),
(I, "Vous n'en aurez pas un de plus. Une stratégie qui ne renonce à rien n'est pas une stratégie : c'est un catalogue.", "하나 더 늘어나는 일은 없을 겁니다. 아무것도 포기하지 않는 전략은 전략이 아니라 카탈로그니까요."),
(MA, "Elle a peaufiné cette phrase dans le train de six heures. Je l'ai entendue la répéter entre Lyon et Avignon.", "저 문장은 6시 기차에서 다듬은 거예요. 리옹과 아비뇽 사이에서 연습하는 걸 들었거든요."),
(I, "Ce qui ne la rend pas moins vraie.", "그렇다고 덜 맞는 말이 되는 건 아니지."),
(MA, "Monsieur Bouzid, selon vous, quels sont les angles morts de ce dossier ?", "부지드 씨, 보시기에 이 사안의 사각지대는 뭡니까?"),
(SB, "Les talents. Nous formons d'excellents ingénieurs ici. Deux ans après leur diplôme, plus d'un tiers sont partis à Paris, à Lyon ou à l'étranger. Tant qu'on n'aura pas réglé ça, on pourra faire venir toutes les entreprises qu'on voudra, elles ne trouveront personne.",
     "인재입니다. 여기서 훌륭한 엔지니어를 길러 내요. 그런데 졸업하고 2년이 지나면 3분의 1 넘게 파리나 리옹이나 해외로 떠나 있어요. 그걸 해결하지 않는 한, 기업을 아무리 많이 데려와도 일할 사람을 못 구할 겁니다."),
(I, "Pourquoi partent-ils ? Les salaires ?", "왜 떠나는 거죠? 급여 때문인가요?"),
(SB, "Les salaires, et le logement. Un jeune ingénieur qui cherche un deux-pièces près du centre est en concurrence avec les meublés touristiques. Je suis le premier à défendre le tourisme, mais je ne suis pas aveugle.",
     "급여, 그리고 주거죠. 도심 근처에서 방 두 개짜리 집을 찾는 젊은 엔지니어는 관광객용 단기 임대와 경쟁해야 해요. 저는 누구보다 관광을 옹호하지만, 눈이 먼 건 아닙니다."),
(MA, "Voilà qui est honnête. Vous voyez, madame Castelli, vos positions sont moins éloignées qu'il n'y paraît.", "솔직하시네요. 보세요, 카스텔리 씨. 두 분 입장은 보기보다 그렇게 멀지 않습니다."),
(OC, "Une dernière chose. Dans nos annexes, il y a le dispositif « Jeunes Pousses de Provence » : six cent mille euros par an pour aider les jeunes commerces et restaurants. Les dossiers sont notés par un jury indépendant.",
     "마지막으로 하나 더. 부록에 « Jeunes Pousses de Provence »라는 지원 제도가 있어요. 신생 상점과 식당을 돕는 데 연 60만 유로가 들어가고, 서류는 독립 심사위원단이 채점합니다."),
(I, "Ce dispositif entre-t-il dans notre périmètre ?", "그 제도도 저희 업무 범위에 들어가나요?"),
(OC, "Son enveloppe globale, oui, comme toutes nos lignes budgétaires. Les attributions individuelles, non : elles relèvent du jury et d'un autre calendrier.",
     "전체 예산 규모는 다른 예산 항목들과 마찬가지로 들어갑니다. 개별 지원 결정은 아니고요. 그건 심사위원단 소관이고 일정도 따로예요."),
(I, "Très bien : l'enveloppe nous regarde, les dossiers non. Pour le calendrier, nous vous présenterons le rapport de phase un mardi prochain, et la version finale partira au conseil de juin.",
    "알겠습니다. 예산 규모는 저희 일이고, 개별 서류는 아니군요. 일정은, 다음 주 화요일에 1단계 보고서를 발표하고 최종본은 6월 이사회로 넘기겠습니다."),
(OC, "Parfait. Et je veux que vous alliez sur le terrain. Pas seulement dans nos bureaux climatisés.", "좋아요. 그리고 현장에 가 보셨으면 해요. 에어컨 나오는 우리 사무실에만 있지 말고요."),
(MA, "C'était prévu : le port, un campus de start-up, les ateliers. Et Inès connaît la ville mieux que nous tous.", "그럴 계획이었습니다. 항구, 스타트업 캠퍼스, 작업장들. 그리고 이네스는 이 도시를 우리 누구보다 잘 알아요."),
(I, "Je connais la ville de mon enfance. Elle a changé. C'est justement pour ça qu'il faut aller voir.", "저는 어린 시절의 도시를 알 뿐이에요. 도시는 변했죠. 그러니까 더더욱 가서 봐야 해요."),

# ---------- 3. Analyse : le coût d'un emploi qui dure ----------
(None, "Mercredi. Salle « Frioul ». Mathieu est au tableau blanc, le vieux marqueur vert à la main. Sur l'écran, Sofia, depuis le bureau de la rue de Courcelles.",
       "수요일. 회의실 « Frioul ». 마티외가 낡은 초록 마커를 들고 화이트보드 앞에 서 있다. 화면에는 쿠르셀 거리 사무실의 소피아."),
(S, "Bonjour la Provence ! J'ai fini de croiser les données de l'agence avec les statistiques régionales. Vous allez adorer... ou pas.", "안녕, 프로방스! 기관 데이터와 지역 통계를 교차 분석해 봤어요. 아주 좋아하시거나... 아니면 아니거나."),
(I, "Commence par le coût par emploi. Le coût réel, pas celui des communiqués de presse.", "일자리당 비용부터 시작해. 보도자료에 나온 거 말고 진짜 비용."),
(S, "Alors. Pour le tourisme et les événements, l'agence dépense environ onze mille euros par emploi annoncé. Pour l'industrie, dix-huit mille. Pour les start-up, vingt-cinq mille.",
    "자. 관광과 행사는 발표된 일자리 하나당 약 1만 1천 유로를 써요. 산업은 1만 8천, 스타트업은 2만 5천."),
(SB, "Vous voyez ! Le tourisme est de loin le plus efficace.", "보세요! 관광이 압도적으로 효율적이잖아요."),
(I, "Attendez. Ce sont des emplois annoncés. Sofia, combien existent encore trois ans plus tard ?", "잠깐만요. 그건 발표된 일자리예요. 소피아, 3년 뒤에도 남아 있는 건 몇 퍼센트야?"),
(S, "Quarante pour cent pour le tourisme, quatre-vingt-cinq pour l'industrie, soixante pour les start-up.", "관광 40%, 산업 85%, 스타트업 60%요."),
(I, "Donc, rapporté aux emplois durables, le tourisme revient à environ vingt-sept mille cinq cents euros par emploi, l'industrie à vingt et un mille, et les start-up à près de quarante-deux mille. Le classement s'inverse.",
    "그러니까 지속되는 일자리 기준으로 환산하면, 관광은 일자리당 약 2만 7,500유로, 산업은 2만 1천, 스타트업은 4만 2천 가까이 돼요. 순위가 뒤집히죠."),
(SB, "Soit. Votre calcul est juste, mais il est incomplet. Un emploi saisonnier n'est pas un emploi raté. Pour un étudiant ou une mère de famille qui cherche un complément l'été, c'est précieux.",
     "좋습니다. 계산은 맞지만 불완전해요. 계절 일자리는 실패한 일자리가 아닙니다. 여름에 부수입이 필요한 학생이나 아이 엄마에게는 소중한 일이에요."),
(I, "C'est un argument sérieux, et il figurera dans le document. Le but n'est pas d'opposer les bons emplois aux mauvais.", "중요한 논거고, 문서에 반드시 넣겠습니다. 좋은 일자리와 나쁜 일자리를 맞세우려는 게 목적이 아니에요."),
(MA, "Et il faut porter au crédit du tourisme ses retombées : un croisiériste qui descend à terre dépense dans les commerces, les restaurants, les musées...", "그리고 관광의 파급 효과도 공정하게 쳐 줘야 해요. 크루즈 승객이 뭍에 내리면 상점과 식당과 박물관에서 돈을 쓰잖아요..."),
(I, "Certes. Mais d'après l'étude de votre propre agence, il dépense en moyenne une soixantaine d'euros par escale, contre plus de cent cinquante pour un touriste qui dort sur place.",
    "그렇긴 하죠. 그런데 귀 기관의 자체 연구에 따르면, 크루즈 승객은 기항 한 번에 평균 60유로 정도를 써요. 현지에서 숙박하는 관광객은 150유로가 넘는데 말이죠."),
(MA, "Inès, multiplie quand même par le nombre de passagers. Ça finit par faire beaucoup de fois soixante euros.", "이네스, 그래도 승객 수를 곱해 봐. 60유로가 수없이 모이면 큰돈이야."),
(I, "Et retranche ce que coûtent aux quartiers voisins les fumées des navires à quai, et la pression sur les loyers. Je ne dis pas que le solde est négatif. Je dis que personne ne l'a jamais calculé.",
    "그리고 부두에 정박한 배의 매연이 인근 동네에 끼치는 비용, 임대료 압박도 빼야지. 결산이 마이너스라는 말이 아니야. 아무도 그걸 계산해 본 적이 없다는 거지."),
(MA, "Prenons le problème autrement. Quel est le vrai problème ? Ce n'est pas « tourisme contre industrie ». C'est : quels emplois voulons-nous que la région produise dans dix ans, et pour qui ?",
     "문제를 다르게 봅시다. 진짜 문제가 뭘까요? '관광 대 산업'이 아닙니다. 10년 뒤 이 지역이 어떤 일자리를, 누구를 위해 만들어 내길 바라느냐는 거죠."),
(SB, "Vu sous cet angle, je ne peux pas vous donner tort. Mais l'industrie a ses limites, elle aussi : le foncier est rare, les camions saturent les routes, et les riverains ne veulent pas d'entrepôts sous leurs fenêtres.",
     "그렇게 보면 틀렸다고 할 수는 없네요. 하지만 산업에도 한계가 있어요. 땅은 부족하고, 트럭은 도로를 꽉 메우고, 주민들은 창밖에 물류 창고가 들어서는 걸 원치 않죠."),
(I, "C'est vrai, et ce sera écrit noir sur blanc. Sofia, le foncier disponible ?", "맞아요. 그것도 분명히 적을 겁니다. 소피아, 쓸 수 있는 땅은?"),
(S, "D'après les plans d'urbanisme, environ cent vingt hectares de friches industrielles dans la métropole, dont quatre-vingts seraient reconvertibles d'ici cinq ans, sous réserve de dépollution.",
    "도시계획 자료에 따르면 도시권 안에 유휴 산업 부지가 약 120헥타르 있고, 그중 80헥타르는 오염 정화를 전제로 5년 안에 전환할 수 있을 것 같아요."),
(MA, "Quatre-vingts hectares, c'est un argument de poids. Encore faut-il que quelqu'un coordonne les propriétaires, les communes et le port.", "80헥타르면 무게 있는 논거죠. 다만 누군가 소유주들과 시·읍·면과 항만을 조율해야 한다는 전제가 붙어요."),
(SB, "C'est précisément ce que personne ne fait. Chacun garde ses terrains comme un trésor.", "바로 그걸 아무도 안 해요. 다들 자기 땅을 보물처럼 끌어안고 있죠."),
(I, "Alors c'est peut-être là le rôle de l'agence. Non pas organiser un salon de plus, mais devenir le guichet unique de l'industriel qui veut s'installer.",
    "그렇다면 그게 바로 기관의 역할일지도 몰라요. 박람회를 하나 더 여는 게 아니라, 입주하려는 제조업체를 위한 원스톱 창구가 되는 거죠."),
(S, "Dernier chiffre, sur les talents : trente-cinq pour cent des jeunes ingénieurs quittent la région dans les deux ans. Et la première raison citée dans l'enquête, c'est le logement, devant les salaires.",
    "인재에 관한 마지막 수치예요. 젊은 엔지니어의 35%가 2년 안에 지역을 떠나요. 그리고 설문에서 꼽은 첫 번째 이유는 급여보다 주거예요."),
(MA, "Monsieur Bouzid l'avait dit lundi.", "부지드 씨가 월요일에 말씀하신 그대로네요."),
(I, "Il l'avait dit, et il avait raison. Dans ce cas, un axe « talents » sans volet logement ne serait que de la communication.", "말씀하셨고, 옳으셨어요. 그렇다면 주거 대책이 빠진 '인재' 축은 홍보에 불과할 거예요."),
(MA, "Bon. On a des chiffres, il nous manque des visages. J'aimerais voir le port de l'intérieur. Pas la visite officielle : les quais, les équipes, les ateliers.",
     "좋아요. 숫자는 있는데 얼굴이 없네요. 항구를 안에서 보고 싶어요. 공식 견학 말고, 부두와 작업반과 작업장을요."),
(I, "Le port est un monde fermé, Mathieu. Pour y entrer, il faut y connaître quelqu'un.", "항구는 닫힌 세계야, 마티외. 들어가려면 안에 아는 사람이 있어야 해."),
(MA, "Justement. Ton père y travaille depuis quinze ans.", "그러니까. 너희 아버지가 거기서 15년째 일하시잖아."),
(I, "Mathieu... Je ne mélange pas ma famille et mes clients. C'est un principe.", "마티외... 난 가족이랑 고객을 섞지 않아. 원칙이야."),
(MA, "Il ne sera ni payé ni consulté sur la stratégie. Il nous ouvre des portes, c'est tout. Et nous le déclarerons à Mme Castelli.", "보수도 안 받으시고 전략에 대해 자문하시는 것도 아니야. 문만 열어 주시는 거지. 그리고 카스텔리 씨한테 신고하면 돼."),
(I, "... Bon. D'accord. J'appelle mon père ce soir. Mais Mme Castelli sera prévenue par écrit avant la visite.",
    "...그래. 좋아. 오늘 저녁에 아빠한테 전화할게. 하지만 견학 전에 카스텔리 씨에게 서면으로 알릴 거야."),
(MA, "Parfait. Et je te préviens : si ton père nous donne rendez-vous à six heures du matin, c'est toi qui mets le réveil.", "좋아. 그리고 미리 말해 두는데, 너희 아버지가 새벽 6시에 만나자고 하시면 알람은 네가 맞추는 거야."),

# ---------- 4. Terrain : le port, le chantier, le campus ----------
(None, "Jeudi, 6 h. Le port, côté bassins est. Le jour se lève derrière les grues. Antoine attend devant une grille, deux gobelets de café à la main.",
       "목요일 오전 6시. 항구 동쪽 부두. 크레인 너머로 날이 밝아 온다. 앙투안이 철문 앞에서 커피 두 잔을 들고 기다리고 있다."),
(AN, "Deux minutes de retard. Sur le port, deux minutes, c'est un bateau qui attend. Tenez, le café.", "2분 늦었다. 항구에서 2분이면 배 한 척이 기다리는 거야. 자, 커피."),
(I, "Bonjour, papa. Tu sais que j'ai dû déclarer à ma cliente que tu nous accompagnais ?", "안녕, 아빠. 아빠가 우리랑 같이 다닌다는 걸 고객에게 신고해야 했다는 거 알아?"),
(AN, "Déclare, ma fille, déclare. Je n'ai rien à cacher. Plus maintenant. ... Ah, voilà Fanfan.", "신고해라, 신고해. 난 숨길 게 없다. 이제는. ...아, 팡팡 왔네."),
(FA, "Antoine ! Et c'est la petite ? La dernière fois que je l'ai vue, elle me demandait pourquoi les grues ressemblaient à des girafes.", "앙투안! 이게 그 꼬마야? 마지막으로 봤을 때 크레인이 왜 기린처럼 생겼냐고 묻던 앤데."),
(I, "Et vous m'aviez répondu qu'elles mangeaient des conteneurs. Bonjour, monsieur Orsini.", "그리고 아저씨는 기린이 컨테이너를 먹어서 그렇다고 하셨죠. 안녕하세요, 오르시니 씨."),
(FA, "Fanfan, comme tout le monde. Alors, les Parisiens, vous voulez savoir ce qui ne va pas sur le port ?", "다들 부르는 대로 팡팡이라고 해. 그래, 파리 양반들, 항구에서 뭐가 잘못 돌아가는지 알고 싶다고?"),
(MA, "Ce qui va et ce qui ne va pas. On nous a beaucoup parlé des croisières. On voudrait comprendre le reste.", "잘 돌아가는 것과 안 돌아가는 것 둘 다요. 크루즈 얘기는 많이 들었어요. 나머지를 알고 싶습니다."),
(FA, "Le reste, c'est tout ce que vous voyez : les conteneurs, les ferries pour la Corse et le Maghreb, le vrac. Les croisières, c'est la vitrine. Mais la boutique, c'est ici.",
     "나머지는 여기 보이는 전부야. 컨테이너, 코르시카와 마그레브로 가는 페리, 벌크 화물. 크루즈는 진열장이지. 하지만 진짜 가게는 여기야."),
(I, "Et l'emploi ? On dit que les métiers du port n'attirent plus les jeunes.", "일자리는요? 항만 일이 더는 젊은 사람들을 끌지 못한다던데요."),
(FA, "Pour les postes de docker, il y a la queue. Ce qui manque, ce sont les métiers d'à côté : mécaniciens, électriciens, soudeurs. Va voir Giordano, au chantier de réparation, il te dira.",
     "하역 일자리는 줄을 서. 모자라는 건 그 주변 직종이야. 정비공, 전기공, 용접공. 수리 조선소의 조르다노한테 가 봐. 그 사람이 말해 줄 거다."),
(None, "Un peu plus loin, un cargo repose dans une forme de radoub. Des gerbes d'étincelles jaillissent sous la coque.", "조금 더 가자 화물선 한 척이 건선거에 올라앉아 있다. 선체 아래로 불꽃이 쏟아진다."),
(GI, "Quarante postes ouverts, mademoiselle. Quarante ! Des soudeurs, des chaudronniers. Je paie correctement, je forme, et personne ne vient.", "빈자리가 마흔 개요, 아가씨. 마흔! 용접공, 판금공. 급여도 괜찮게 주고 교육도 시키는데 아무도 안 와요."),
(MA, "Pourquoi, d'après vous ?", "왜 그렇다고 보세요?"),
(GI, "Parce qu'à l'école, on leur répète que l'industrie, c'est sale et que c'est fini. Alors qu'un bon soudeur, ici, gagne mieux qu'un jeune diplômé d'école de commerce.",
     "학교에서 산업은 지저분하고 끝난 분야라고 귀에 못이 박히게 말하니까요. 여기서 실력 있는 용접공은 경영대학 갓 나온 친구보다 더 버는데 말이죠."),
(I, "Si une école de soudure ouvrait à côté du chantier, vous prendriez des apprentis ?", "조선소 옆에 용접 학교가 생긴다면 견습생을 받으시겠어요?"),
(GI, "Vingt par an, dès demain matin. Et je ne suis pas le seul.", "1년에 스무 명, 당장 내일 아침부터라도. 그리고 나만 그런 게 아니오."),
(FA, "Dis, Antoine, tu leur as raconté, pour tes camions ?", "어이, 앙투안, 자네 트럭 얘기는 해 줬나?"),
(None, "Antoine secoue la tête, gêné.", "앙투안이 난처한 듯 고개를 젓는다."),
(I, "Raconté quoi, Fanfan ?", "무슨 얘기요, 팡팡?"),
(FA, "Quand Transports Marchetti a fermé, ton père a vendu sa propre voiture pour payer les derniers salaires. Les douze. Jusqu'au dernier centime. Sur le port, personne ne l'a oublié.",
     "트랑스포르 마르케티가 문을 닫을 때, 네 아버지는 마지막 월급을 주려고 자기 차를 팔았어. 열두 명 전부. 한 푼도 빠짐없이. 항구에선 아무도 그걸 잊지 않았다."),
(None, "Inès se tourne vers son père. Il regarde la mer.", "이네스가 아버지를 돌아본다. 그는 바다를 보고 있다."),
(I, "Tu ne me l'as jamais dit.", "나한테 한 번도 말 안 했잖아."),
(AN, "Il n'y avait pas de quoi s'en vanter. Allez, on vous attend au campus. La jeunesse, c'est de l'autre côté du bassin.", "자랑할 일도 아니었으니까. 자, 캠퍼스에서 기다린다. 젊은이들은 부두 건너편에 있어."),
(None, "Fin de matinée. Un ancien entrepôt à sucre reconverti en campus de start-up : « La Fabrique du Large ».", "오전 늦게. 옛 설탕 창고를 개조한 스타트업 캠퍼스 « La Fabrique du Large »."),
(MR, "Bienvenue ! Maëlle Rinaldi, fondatrice de Quaivolt. Nous concevons des bornes pour brancher les navires à quai sur le réseau électrique, pour qu'ils puissent couper leurs moteurs.",
     "어서 오세요! Quaivolt 창업자 마엘 리날디입니다. 정박한 배를 전력망에 연결해서 엔진을 끌 수 있게 해 주는 충전 설비를 설계해요."),
(MA, "Voilà exactement le pont qui manquait entre les start-up et le port. Vous recrutez ?", "스타트업과 항구 사이에 빠져 있던 다리가 바로 이거네요. 채용하세요?"),
(MR, "Huit ingénieurs cette année. Ils viennent pour la mer et le soleil, et au bout de dix-huit mois, ils repartent : impossible de trouver un deux-pièces à moins de mille cinq cents euros.",
     "올해 엔지니어 여덟 명이요. 바다와 햇빛 때문에 왔다가 18개월쯤 지나면 떠나요. 방 두 개짜리 집을 1,500유로 아래로는 구할 수가 없거든요."),
(I, "Le même constat au port, au chantier et ici. Le problème n'est pas d'attirer. C'est de retenir.", "항구에서도, 조선소에서도, 여기서도 같은 진단이네. 문제는 끌어오는 게 아니야. 붙잡아 두는 거지."),
(MA, "Tu viens de résumer en une phrase ce autour de quoi tout le monde tourne depuis dix ans.", "다들 10년째 빙빙 돌기만 하던 걸 방금 한 문장으로 정리했어."),

# ---------- 5. Décision : « Produire, retenir, accueillir » ----------
(None, "Le mardi suivant. Siège de Provence Attractivité. La direction et le bureau du conseil d'administration sont réunis pour le rapport de phase un. Inès se lève.",
       "다음 주 화요일. Provence Attractivité 본부. 경영진과 이사회 상임위원들이 1단계 보고를 듣기 위해 모였다. 이네스가 일어선다."),
(I, "Madame la directrice générale, mesdames et messieurs les membres du bureau, notre recommandation tient en une phrase : faire de Provence Attractivité moins une agence de promotion qu'une agence de production.",
    "사무총장님, 그리고 상임위원 여러분. 저희 권고는 한 문장으로 요약됩니다. Provence Attractivité를 홍보 기관이라기보다 생산 기관으로 만드는 것입니다."),
(I, "Nous l'avons intitulée « Produire, retenir, accueillir ». L'ordre des mots n'est pas un hasard.", "저희는 이 전략에 '생산하고, 붙잡고, 맞이하라'라는 제목을 붙였습니다. 단어의 순서는 우연이 아닙니다."),
(MA, "Premier axe : produire. Quarante-cinq pour cent du budget iraient à l'industrie et au port, contre quinze aujourd'hui. Concrètement, un guichet unique pour les industriels et la coordination de la reconversion de quatre-vingts hectares de friches en cinq ans.",
     "첫 번째 축, 생산. 예산의 45%를 산업과 항만에 배정합니다. 지금은 15%입니다. 구체적으로는 제조업체를 위한 원스톱 창구, 그리고 5년에 걸친 유휴 부지 80헥타르 전환의 조율입니다."),
(OC, "Quatre-vingts hectares... La moitié de ces terrains appartiennent à des acteurs qui ne se parlent pas.", "80헥타르라... 그 땅의 절반은 서로 말도 안 하는 주체들 소유예요."),
(I, "C'est précisément pourquoi l'agence doit s'en charger. Elle seule réunit autour de la même table la métropole, la région, la chambre de commerce et le port.",
    "바로 그래서 기관이 맡아야 합니다. 광역도시권, 레지옹, 상공회의소, 항만을 한 테이블에 모을 수 있는 건 이 기관뿐이니까요."),
(MA, "Deuxième axe : retenir. Vingt-cinq pour cent du budget. Une école de soudure et de maintenance navale adossée aux chantiers, deux cents places par an, et un programme de logements pour apprentis et jeunes salariés, cofinancé avec les bailleurs sociaux et les entreprises. Pour le financer, entre autres, l'enveloppe du dispositif Jeunes Pousses serait réduite de moitié.",
     "두 번째 축, 붙잡기. 예산의 25%. 조선소와 연계한 용접·선박 정비 학교를 연 200명 규모로 세우고, 견습생과 젊은 직장인을 위한 주거 프로그램을 공공임대 사업자 및 기업들과 공동 출자로 추진합니다. 그 재원의 일부로 Jeunes Pousses 지원 제도의 예산을 절반으로 줄입니다."),
(SB, "Le logement n'est pas notre métier.", "주거는 우리 일이 아닙니다."),
(I, "Construire n'est pas votre métier, en effet. Mais si l'on en croit votre propre enquête, c'est la première raison pour laquelle les talents s'en vont. Une agence d'attractivité qui ignore le logement, c'est un seau percé : on le remplit d'un côté, il se vide de l'autre.",
    "짓는 건 귀 기관의 일이 아니죠, 맞습니다. 하지만 귀 기관의 설문을 믿는다면, 그게 인재가 떠나는 첫 번째 이유입니다. 주거를 외면하는 투자유치 기관은 구멍 난 양동이예요. 한쪽으로 채우면 다른 쪽으로 새어 나가죠."),
(MA, "Troisième axe : quinze pour cent pour les start-up, mais orientées vers les défis du port et de l'industrie. Des entreprises comme Quaivolt, qui électrifient les quais, plutôt qu'une application de plus.",
     "세 번째 축, 스타트업에 15%. 다만 항만과 산업의 과제를 푸는 쪽으로 방향을 잡습니다. 앱을 하나 더 만드는 곳보다, 부두를 전기화하는 Quaivolt 같은 기업이죠."),
(SB, "Et le tourisme ? Quinze pour cent au lieu de soixante. Vous rendez-vous compte du signal envoyé aux hôteliers, aux restaurateurs ?", "그럼 관광은요? 60%에서 15%라니. 호텔 업주들, 식당 주인들에게 어떤 신호가 갈지 아십니까?"),
(I, "Nous nous en rendons compte, et c'est pourquoi nous ne proposons pas de rupture brutale. La part du tourisme baisserait par paliers : trente-cinq pour cent la première année, vingt-cinq la deuxième, quinze à partir de la troisième.",
    "알고 있습니다. 그래서 급격한 단절을 제안하지 않는 겁니다. 관광 비중은 단계적으로 줄어듭니다. 첫해 35%, 둘째 해 25%, 셋째 해부터 15%입니다."),
(MA, "Et ce budget serait réorienté : tourisme d'affaires, congrès, arrière-saison. Moins de promotion en juillet, quand les hôtels sont pleins ; davantage en novembre, quand ils sont vides.",
     "그리고 그 예산의 방향도 바꿉니다. 비즈니스 관광, 컨벤션, 비수기. 호텔이 꽉 차는 7월엔 홍보를 줄이고, 텅 비는 11월엔 늘리는 거죠."),
(SB, "... L'arrière-saison. Voilà trois ans que je la réclame sans que personne m'écoute.", "...비수기라. 3년째 요구했는데 아무도 들어 주지 않았던 거예요."),
(MA, "Vous voyez, monsieur Bouzid : sur ce point, nous sommes d'accord depuis lundi.", "보세요, 부지드 씨. 이 점에선 우리가 월요일부터 같은 생각이었습니다."),
(I, "Quant aux objectifs : quatre mille emplois industriels et portuaires durables en cinq ans, mesurés trois ans après l'implantation et non au jour de l'annonce. Un taux de départ des jeunes ingénieurs ramené de trente-cinq à vingt-cinq pour cent. Et un coût par emploi durable publié chaque année.",
    "목표를 말씀드리면, 5년간 지속되는 산업·항만 일자리 4,000개. 발표하는 날이 아니라 입주 3년 뒤에 측정합니다. 젊은 엔지니어 유출률은 35%에서 25%로. 그리고 지속 일자리당 비용을 매년 공개합니다."),
(OC, "Publié ? Vous voulez que nous publiions nos échecs ?", "공개요? 우리 실패를 공개하라는 건가요?"),
(MA, "Nous voulons que vous publiiez vos résultats ; les échecs en font partie. Une agence financée par l'argent public doit rendre des comptes, et c'est généralement ce qui la protège le mieux.",
     "결과를 공개하시라는 겁니다. 실패도 그 일부고요. 공적 자금으로 운영되는 기관은 책임 있게 설명해야 하고, 대개는 그게 기관을 가장 잘 지켜 줍니다."),
(I, "Personne n'aime être jugé sur ses chiffres. Mais un indicateur qu'on publie soi-même vaut mieux qu'un chiffre qu'un journaliste découvrira seul.", "자기 숫자로 평가받는 걸 좋아하는 사람은 없죠. 하지만 스스로 공개하는 지표가 기자가 혼자 찾아낼 숫자보다 낫습니다."),
(OC, "Les risques, maintenant. Je veux les entendre de votre bouche, pas les découvrir en juin.", "이제 위험 요인이요. 6월에 알게 되기보다 지금 두 분 입으로 듣고 싶어요."),
(MA, "Trois risques. Un : la dépollution des friches peut prendre plus de temps que prévu. Deux : les riverains peuvent s'opposer à de nouvelles activités logistiques. Trois : les professionnels du tourisme peuvent se sentir abandonnés.",
     "세 가지입니다. 첫째, 유휴 부지 정화가 예상보다 오래 걸릴 수 있습니다. 둘째, 주민들이 새 물류 시설에 반대할 수 있습니다. 셋째, 관광업계가 버림받았다고 느낄 수 있습니다."),
(I, "Pour chacun, une parade : un calendrier site par site, une concertation avec les habitants avant chaque projet, et un comité de suivi où le secteur touristique aura un siège.",
    "각각에 대한 대비책이 있습니다. 부지별 일정표, 사업마다 사전 주민 협의, 그리고 관광업계가 한 자리를 갖는 이행 점검 위원회입니다."),
(SB, "Un siège, et une voix ?", "자리만요, 아니면 의결권도요?"),
(MA, "Une voix. Sans quoi le siège ne servirait à rien.", "의결권도요. 그게 없으면 자리는 아무 소용이 없으니까요."),
(SB, "Alors... je ne m'opposerai pas. Je défendrai même l'arrière-saison devant le conseil. Mais je rédigerai une note de réserve sur le rythme de la baisse.",
     "그렇다면... 반대하지 않겠습니다. 이사회에서 비수기 전략은 오히려 옹호하죠. 다만 감축 속도에 대해선 유보 의견서를 쓰겠습니다."),
(I, "C'est votre droit, et ce sera utile au conseil. Une décision prise en connaissance des désaccords est plus solide qu'une unanimité de façade.", "당연한 권리시고, 이사회에도 도움이 될 겁니다. 이견을 알고 내린 결정이 겉치레 만장일치보다 튼튼하니까요."),
(OC, "Bien. Je transmets la version finale au conseil d'administration de juin, avec la note de Samir en annexe. C'est au conseil de voter, pas à moi.", "좋아요. 최종본을 6월 이사회에 넘기고, 사미르의 의견서는 부록으로 붙이겠습니다. 표결은 이사회가 하는 거지, 제가 하는 게 아니니까요."),
(MA, "Ni à nous. Notre mission s'arrête là où commence sa décision.", "저희도 아니고요. 저희 임무는 이사회의 결정이 시작되는 곳에서 끝납니다."),
(OC, "Vous êtes des consultants étranges. D'habitude, on me vend des certitudes.", "두 분은 이상한 컨설턴트네요. 보통은 다들 저한테 확신을 팔거든요."),
(I, "Nous préférons vous vendre des chiffres. Les certitudes, on les laisse aux brochures.", "저희는 숫자를 파는 쪽이 좋습니다. 확신은 안내 책자에 맡겨 두죠."),
(MA, "Et si votre conseil l'adopte, la phase deux, la mise en œuvre, pourra commencer cet été. Mais le vote, lui, appartient à Marseille.", "그리고 이사회가 채택하면 2단계, 즉 실행 단계를 올여름에 시작할 수 있습니다. 하지만 표결만큼은 마르세유의 몫입니다."),

# ---------- 6. Le samedi : le petit port de L'Estaque ----------
(None, "Samedi, 7 h. Le petit port de L'Estaque. Comme autrefois, Inès et son père marchent le long des barques.", "토요일 오전 7시. 레스타크의 작은 항구. 예전처럼 이네스와 아버지가 작은 배들을 따라 걷는다."),
(AN, "Tu te souviens ? Chaque samedi, tu portais mon cahier de comptes, et moi, je chantais du Mozart. Faux.", "기억나니? 토요일마다 넌 내 장부를 들고 다녔고, 난 모차르트를 불렀지. 음정은 엉망이었고."),
(I, "Tu chantais faux, mais tes comptes étaient justes. Jusqu'au jour où tu as arrêté de les ouvrir.", "노래는 엉망이었어도 장부는 정확했지. 아빠가 장부를 펴 보지 않게 된 날까지는."),
(AN, "« Les chiffres étaient là, et je ne les ai pas lus. » Je te l'ai dit cent fois. Ce que je ne t'ai jamais dit, c'est pourquoi.", "'숫자는 거기 있었는데, 난 읽지 않았다.' 백 번은 말했지. 하지만 왜 그랬는지는 한 번도 말 안 했다."),
(I, "Pourquoi, papa ?", "왜 그랬어, 아빠?"),
(AN, "Parce que j'avais peur de ce qu'ils allaient me dire. Et parce que j'avais honte devant toi. Tu avais seize ans, tu lisais tout, tu comprenais tout.", "숫자가 뭐라고 할지 무서웠으니까. 그리고 네 앞에서 부끄러웠으니까. 넌 열여섯 살이었고, 뭐든 읽고 뭐든 이해했지."),
(I, "J'ai trouvé les lettres de la banque dans le tiroir, tu sais. Je n'ai jamais osé t'en parler.", "나 그 은행 편지들 서랍에서 찾았었어, 알지? 한 번도 아빠한테 말 못 했어."),
(AN, "Je le sais. Tu les avais remises dans le désordre. ... Moi non plus, je n'ai pas osé.", "알고 있었다. 순서를 뒤죽박죽으로 다시 넣어 놨더구나. ...나도 말할 용기가 없었고."),
(I, "Dix-sept ans qu'on se tait, tous les deux. On est vraiment des Marchetti.", "17년 동안 둘 다 입을 다물고 있었네. 우린 정말 마르케티 집안 사람들이야."),
(AN, "Fanfan a bien fait de parler, jeudi. Quand je t'ai entendue devant tous ces gens, j'ai compris une chose : tu as fait de ma faillite un métier. Tu apprends aux autres à lire les chiffres que je n'ai pas lus.",
     "목요일에 팡팡이 말하길 잘했어. 그 사람들 앞에서 네 말을 듣다가 하나 깨달았다. 넌 내 파산을 직업으로 만들었구나. 내가 읽지 않은 숫자를 남들에게 읽는 법을 가르치고 있으니."),
(I, "Ce n'était pas « ta » faillite, papa. C'était un client qui ne payait pas et une banque qui a coupé le crédit. Et toi, tu as vendu ta voiture pour payer tes gars.",
    "그건 '아빠의' 파산이 아니었어. 돈을 안 준 거래처와 대출을 끊은 은행이 있었지. 그리고 아빠는 직원들 월급 주려고 차를 팔았고."),
(AN, "... Ta mère dit que je devrais en parler davantage. Un de ces soirs, au restaurant de ton frère, je raconterai peut-être toute l'histoire.", "...네 엄마는 내가 그 얘기를 좀 더 해야 한다더라. 언젠가 저녁에 네 동생 식당에서 처음부터 끝까지 얘기할지도 모르겠다."),
(I, "Lucas serait ravi. Il dit toujours que tu ne racontes jamais rien.", "뤼카가 좋아하겠다. 아빠는 아무 얘기도 안 한다고 늘 그러거든."),
(AN, "Lucas parle pour deux. D'ailleurs, ces temps-ci, il est plongé dans ses papiers jusqu'au cou. Bon. Voilà ton Strasbourgeois, avec des croissants.", "뤼카는 두 사람 몫을 떠들잖니. 그나저나 요즘 걔는 서류 더미에 목까지 파묻혀 있더라. 자. 네 스트라스부르 남자가 크루아상 들고 오는구나."),
(None, "Mathieu arrive, un sac de boulangerie à la main.", "마티외가 빵집 봉투를 들고 다가온다."),
(MA, "Bonjour, monsieur Marchetti. J'ai pris des croissants... et une fougasse, pour faire couleur locale.", "안녕하세요, 마르케티 씨. 크루아상을 사 왔어요... 그리고 현지 분위기 좀 내려고 푸가스도요."),
(AN, "Antoine. Depuis le temps, appelle-moi Antoine. Et tutoie-moi. ... Je vous laisse, j'ai des barques à regarder.", "앙투안. 이만큼 지났으면 앙투안이라고 불러. 말도 놓고. ...난 이만 가 보마. 배들 좀 봐야 해서."),
(I, "Il t'a tutoyé. Après trois ans. Tu mesures l'exploit ?", "아빠가 너한테 말을 놨어. 3년 만에. 이게 얼마나 대단한 일인지 알아?"),
(MA, "Je mesure. Ma plus belle victoire depuis Saint-Étienne. ... Ça va, toi ? Tu as les yeux rouges.", "알지. 생테티엔 이후 최고의 승리야. ...너 괜찮아? 눈이 빨개."),
(I, "Ça va très bien. Mieux que depuis longtemps. ... Allez, les trois questions, Strasbourg. La dernière, surtout.", "아주 괜찮아. 오랜만에 제일 좋아. ...자, 세 가지 질문, 스트라스부르. 특히 마지막 거."),
(MA, "Que fait-on lundi ?", "월요일엔 뭘 하지?"),
(I, "Lundi, on rentre à Paris et on boucle la version finale pour le conseil de juin. Et ce soir, on dîne au Fanal. Sans parler boulot.", "월요일엔 파리로 돌아가서 6월 이사회에 낼 최종본을 마무리하지. 그리고 오늘 저녁엔 Le Fanal에서 밥 먹자. 일 얘기는 빼고."),
(None, "Sur le banc, le téléphone d'Inès vibre : un numéro parisien inconnu. Elle le retourne, écran contre le bois, et prend un croissant.",
       "벤치 위에서 이네스의 휴대폰이 진동한다. 모르는 파리 번호다. 그녀는 화면을 나무 쪽으로 뒤집어 놓고 크루아상을 집어 든다."),
]

VOCAB = [
("B1", "une inauguration / inaugurer", "개업식, 개관식 / 개업하다, 개관하다", "식당·가게·건물 등의 공식 개시. couper le ruban(테이프 커팅)과 함께 쓰임."),
("B1", "un couvert", "(식당의) 좌석, 1인분 식기 세트", "un restaurant de trente-deux couverts = 32석 식당. mettre le couvert = 상을 차리다."),
("B2", "la paperasse", "(귀찮은) 서류 작업", "구어·약간 경멸조. de la paperasse à n'en plus finir = 끝도 없는 서류."),
("B2", "prendre la grosse tête", "우쭐해지다, 거만해지다", "구어. avoir la grosse tête = 잘난 척하다."),
("B2", "j'en mettrais ma main au feu", "장담한다, 확신한다", "직역 '그 일에 손을 불에 넣겠다'. 중세 시죄법에서 유래한 관용구."),
("C1", "l'attractivité (d'un territoire)", "(지역의) 매력도, 투자·인재 유치력", "une agence d'attractivité = 투자유치 기관. attirer → attractif → attractivité."),
("B2", "une implantation (d'entreprise)", "(기업의) 입지, 신규 진출", "s'implanter dans une région = 어떤 지역에 자리를 잡다."),
("C1", "le taux de concrétisation", "실현율, 성사율", "발표·계획 가운데 실제로 이루어진 비율. concrétiser un projet = 사업을 구체화하다."),
("B2", "un angle mort", "사각지대", "운전 용어에서 비유로. les angles morts d'un dossier = 사안에서 놓치고 있는 부분."),
("C1", "un procès d'intention", "의도에 대한 억측, 선입견에 찬 비난", "faire un procès d'intention à qn = 상대의 속셈을 미리 단정하고 비난하다."),
("B2", "la saisonnalité / l'arrière-saison", "계절성 / (성수기 뒤) 비수기, 늦가을", "l'arrière-saison은 9~11월의 늦은 시즌. hors saison(비수기)과 함께 쓰임."),
("B2", "les retombées (économiques)", "(경제적) 파급 효과", "retomber = 다시 떨어지다. 긍정·부정 결과 모두에 씀."),
("B2", "un croisiériste", "크루즈 승객", "la croisière = 크루즈 여행. descendre à terre = 뭍에 내리다."),
("C1", "le foncier", "토지, 부동산(용지)", "le foncier industriel = 산업 용지. la taxe foncière(재산세)와 같은 어원."),
("B2", "une friche industrielle", "유휴 산업 부지, 버려진 공장 터", "en friche = 경작하지 않은, 방치된. reconvertir une friche = 유휴지를 다른 용도로 전환하다."),
("C1", "la dépollution", "오염 정화", "dépolluer un site. sous réserve de dépollution = 오염 정화를 전제로."),
("C1", "un guichet unique", "원스톱 창구", "여러 기관 절차를 한 곳에서 처리하는 창구. 행정 개혁의 단골 표현."),
("B2", "un riverain", "인근 주민, 연도 주민", "강가(rive)에서 유래. 도로·공장·공항 주변 주민에게 두루 씀."),
("B2", "une forme de radoub", "건선거(乾船渠)", "배를 물 밖으로 올려 수리하는 독. 마르세유 항구의 대형 수리 시설."),
("B2", "un chaudronnier", "판금공, 보일러공", "금속판을 자르고 굽혀 용접하는 기술자. 조선·에너지 산업의 핵심 직종."),
("B2", "par paliers", "단계적으로", "palier = 층계참. baisser par paliers = 계단식으로 줄이다. ↔ brutalement."),
("C1", "une note de réserve", "유보 의견서", "결정에 반대하진 않지만 조건·우려를 기록으로 남기는 문서. émettre des réserves."),
("C1", "une unanimité de façade", "겉치레 만장일치", "de façade = 겉으로만, 보여 주기식. un sourire de façade."),
("B2", "se vanter de qc", "~을 자랑하다", "Il n'y a pas de quoi se vanter. = 자랑할 일이 못 된다."),
("B2", "faire couleur locale", "현지 분위기를 내다", "la couleur locale = 지방색. 마르세유에선 푸가스(올리브유 납작빵)가 대표적."),
]

GRAM = [
("C1", "전략 문서의 조건법: 제안을 단정하지 않기",
 "« Quarante-cinq pour cent du budget iraient à l'industrie et au port. » « La part du tourisme baisserait par paliers. » « Et ce budget serait réorienté. » 권고안에서는 아직 결정되지 않은 내용을 조건법으로 제시한다. 결정권이 이사회에 있다는 태도를 문법으로 보여 주는 셈이다. 불확실한 데이터도 조건법으로 말한다: « dont quatre-vingts seraient reconvertibles d'ici cinq ans »."),
("B2", "비교 표현: moins... que / contre / plutôt que / au lieu de",
 "« faire de Provence Attractivité moins une agence de promotion qu'une agence de production »(A라기보다 B로) « Quarante-cinq pour cent du budget iraient à l'industrie, contre quinze aujourd'hui »(지금의 15%에 비해) « plutôt qu'une application de plus »(~보다는 차라리) « Quinze pour cent au lieu de soixante »(~대신에). contre는 수치를 나란히 대비할 때 보고서·기사에서 특히 자주 쓴다."),
("C1", "종합·환산의 soit, 양보의 Soit.",
 "« Soit un taux de concrétisation d'à peine soixante-trois pour cent. » 숫자 앞의 soit [swa]는 '즉, 다시 말해'로, 앞의 데이터를 종합해 결론 수치를 낸다. 반면 문장 첫머리에서 단독으로 쓰인 « Soit. Votre calcul est juste, mais il est incomplet. »의 soit [swat]는 '좋다, 인정한다'는 양보 표현이다. 발음도 다르다. 환산은 rapporté à로: « rapporté aux emplois durables »."),
("C1", "Encore faut-il que + 접속법: 도치로 조건 달기",
 "« Quatre-vingts hectares, c'est un argument de poids. Encore faut-il que quelqu'un coordonne les propriétaires, les communes et le port. » 문두의 encore는 주어-동사 도치를 일으키며 '그러려면 우선 ~해야 한다'는 단서를 단다. il faut que 뒤이므로 접속법(coordonne). 같은 유형: Encore faudrait-il qu'ils acceptent. / Aussi avons-nous décidé de...(그래서 ~하기로 했다)."),
("C1", "n'en... pas moins / ne... que: 양보와 제한",
 "« Ce qui ne la rend pas moins vraie. » '그렇다고 덜 ~한 것은 아니다'라는 구조로, 앞서 인정한 사실에도 불구하고 주장을 유지한다. 문어에서는 Elle n'en est pas moins vraie / Il n'en demeure pas moins que...로 쓴다. 제한의 ne... que와 구별: « un axe « talents » sans volet logement ne serait que de la communication »(홍보에 불과할 것이다)."),
("B2", "vouloir que + 접속법: -ions / -iiez 형태 주의",
 "« Je veux que vous alliez sur le terrain. » « Vous voulez que nous publiions nos échecs ? » « Nous voulons que vous publiiez vos résultats. » « quels emplois voulons-nous que la région produise ». publier의 접속법 nous/vous형은 어간 publi- + -ions/-iez라서 i가 두 번 겹친다(publiions, publiiez). étudier, oublier, crier도 마찬가지: que nous oubliions."),
("C1", "ce + 전치사 + quoi / sans quoi",
 "« ce autour de quoi tout le monde tourne depuis dix ans » 전치사를 동반한 관계절의 선행사가 막연한 '것'(ce)일 때는 quoi를 쓴다: ce à quoi je pense, ce sur quoi nous travaillons. « Une voix. Sans quoi le siège ne servirait à rien. »의 sans quoi는 '그렇지 않으면'이라는 연결어로, 뒤에 조건법이 자주 온다(= sinon)."),
("C1", "명사화 구문: 행정·전략 문서 문체",
 "« la coordination de la reconversion de quatre-vingts hectares de friches », « la dépollution des friches », « une concertation avec les habitants avant chaque projet », « un taux de départ des jeunes ingénieurs ». 동사(coordonner, reconvertir, dépolluer, partir)를 명사로 바꿔 de로 연결하면 문장이 짧고 객관적인 보고서 문체가 된다. 다만 de... de... de가 너무 겹치면 읽기 어려우니 두세 단계에서 끊는 것이 좋다."),
]

CULTURE = [
("프랑스의 지역 투자유치 기관",
 "프랑스에서는 레지옹(région)이 경제 개발의 핵심 권한을 갖고 있으며, 2015년 NOTRe법은 그 역할을 한층 강화했다. 레지옹과 광역도시권(métropole)은 흔히 '투자유치 기관'(agence d'attractivité, agence de développement économique)을 두고 기업 유치, 지역 브랜드(marque territoriale) 홍보, 인재 유치를 맡긴다. 국가 차원에서는 Business France가 해외 투자 유치를 담당한다. 이런 기관의 성과를 '발표된 일자리 수'로 잴지 '실제로 유지된 일자리 수'로 잴지는 프랑스 지방 정책에서 자주 벌어지는 논쟁이다."),
("마르세유 항구",
 "마르세유 항구는 프랑스 최대 규모의 항구 가운데 하나로, 도심의 '동쪽 부두'(bassins Est)와 서쪽 포스쉬르메르 일대의 '서쪽 부두'(bassins Ouest)로 나뉜다. 동쪽 부두에는 코르시카·마그레브행 페리, 크루즈선, 선박 수리 시설이 있고, 서쪽 부두는 컨테이너·에너지·산업 물류의 중심이다. 정박한 선박이 엔진을 끄고 육상 전력을 쓰게 하는 '부두 전기화'(électrification des quais)는 인근 주민의 대기질 문제 때문에 지역의 주요 과제가 되었다."),
("르 파니에와 레스타크",
 "르 파니에(Le Panier)는 기원전 600년경 포카이아 출신 그리스인들이 세운 마살리아(Massalia)의 터로, 마르세유에서 가장 오래된 동네다. 좁은 언덕길과 알록달록한 덧창, 작은 식당과 공방이 많다. 도시 서쪽 끝의 옛 어촌 레스타크(L'Estaque)는 세잔이 여러 차례 그렸고, 1908년 브라크가 이곳에서 그린 풍경화들은 입체파의 출발점 가운데 하나로 꼽힌다. 바삭한 병아리콩 튀김 파니스(panisse)가 이 동네의 명물이다."),
]
