# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, S = "Inès", "Mathieu", "Hélène", "Sofia"
RA, PM, L = "Rachid", "Ménard", "Lucas"
LV, AC = "Lavigne", "Mme Achour"

META = {
    "part": 3, "ep": 43,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Conflit d'intérêts",
    "title_ko": "이해충돌",
    "place": "8구 쿠르셀 거리 Agora Stratégies 사무실과 아래층 카페 Le Petit Monceau · 마르세유 뤼카의 식당 · Provence Attractivité 본사 윤리위원회 회의실 · 11구 오베르캉프 아파트 / 5월 초, 화요일부터 목요일까지",
    "chars": "이네스, 마티외, 소피아, 엘렌(멘토), 라시드(카페 종업원), 폴 메나르(Le Courrier de Paris 탐사기자), 뤼카 마르케티(이네스의 남동생, 요리사), 앙리 라비뉴(Provence Attractivité 윤리위원회 위원장), 나디라 아슈르(같은 기관 윤리 담당관)",
    "work": "고객 기관 Provence Attractivité가 이네스의 남동생 뤼카의 식당에 지원금 3만 유로를 지급한 사실이 보도될 위기 — 이해충돌 의혹의 사실관계 확인, 대응 전략(침묵·해명·선제 공개) 토론, 윤리위원회 출석, 2단계 계약 철회와 지원금 반납, Agora 윤리 강령(가족 이해관계 사전 신고) 공개",
    "life": "몰랐던 동생의 지원금, 마티외가 1초 동안 내비친 의심과 그로 인한 신뢰의 균열, 남매의 자존심 대결, 목요일 밤 오베르캉프 아파트에서의 사과와 화해",
    "focus": "윤리·법 어휘(déontologie, déclaration d'intérêts, se déporter, de bonne foi), 변론·해명 표현(il n'en demeure pas moins que, loin de moi l'idée de), 접속법 과거, 양보(si... que, tout... que), 문어 도치(à peine... que, sans doute), 명사화, 성명서 문체",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "제44화 La campagne nationale — 소피아의 파트너 승격을 축하하는 아침, 그리고 신생 전국 운동의 대선 후보가 내민 독점 계약이 두 사람을 다시 갈림길에 세운다.",
}

D = [
# ---------- 1. Ouverture : l'appel du journaliste ----------
(None, "Mardi, début mai, 8 h 20. Le Petit Monceau, rue de Courcelles, juste sous les bureaux d'Agora Stratégies. Rachid pose deux grands crèmes sur le comptoir.",
       "5월 초 화요일, 오전 8시 20분. 쿠르셀 거리의 Le Petit Monceau, Agora Stratégies 사무실 바로 아래층. 라시드가 그랑 크렘 두 잔을 카운터에 내려놓는다."),
(RA, "Deux grands crèmes, comme d'habitude. Vous avez des têtes de gens qui ont bien dormi, pour une fois.", "늘 마시던 그랑 크렘 두 잔. 웬일로 두 사람 다 푹 잔 얼굴이네."),
(I, "Ne dis pas ça trop fort, Rachid. Chaque fois qu'on a l'air reposés, il nous tombe une catastrophe sur la tête.", "너무 크게 말하지 마, 라시드. 우리가 좀 쉬어 보인다 싶으면 꼭 날벼락이 떨어지거든."),
(MA, "Superstition marseillaise. Le rapport pour Provence Attractivité est livré, le client est content, et le soleil se lève sur le parc Monceau. Que veux-tu qu'il arrive ?",
     "마르세유식 미신이야. Provence Attractivité 보고서는 납품했고, 고객은 만족하고, 몽소 공원엔 해가 뜨고 있어. 무슨 일이 일어나겠어?"),
(I, "Tu viens de signer notre arrêt de mort, Strasbourg. On ne pose jamais cette question à voix haute.", "방금 우리 사형 선고에 서명했어, 스트라스부르. 그런 질문은 절대 소리 내서 하는 게 아니야."),
(None, "Le téléphone d'Inès vibre sur le comptoir. Numéro inconnu, indicatif parisien.", "카운터 위에서 이네스의 휴대폰이 진동한다. 모르는 번호, 파리 지역 번호다."),
(I, "Inès Marchetti, j'écoute.", "이네스 마르케티입니다."),
(PM, "Madame Marchetti ? Paul Ménard, du Courrier de Paris. Nous nous sommes croisés il y a quelques années, quand vous conseilliez le journal. Je ne vous dérange pas trop tôt ?",
     "마르케티 씨? Le Courrier de Paris의 폴 메나르입니다. 몇 년 전 저희 신문사를 컨설팅하실 때 뵌 적이 있죠. 너무 이른 시간에 방해가 된 건 아니길 바랍니다."),
(I, "Monsieur Ménard ! Bien sûr que je me souviens. Le journaliste dernier du classement des clics, et premier au classement des abonnés.", "메나르 씨! 물론 기억하죠. 클릭 순위는 꼴찌, 구독자 순위는 1등이던 기자님."),
(PM, "C'est toujours vrai, hélas pour mon ego. Je vous appelle pour une raison moins agréable. Nous publions jeudi matin un article sur les aides versées par Provence Attractivité.",
     "안타깝게도 아직 그래요, 제 자존심엔 슬픈 일이지만. 그런데 덜 반가운 일로 전화드렸습니다. 목요일 아침에 Provence Attractivité가 지급한 지원금에 관한 기사를 냅니다."),
(PM, "Parmi les bénéficiaires figure un restaurant ouvert il y a quelques semaines à Marseille, celui de Lucas Marchetti. Trente mille euros. Votre frère, si je ne m'abuse, alors que votre cabinet conseille l'agence.",
     "수혜자 중에 몇 주 전 마르세유에서 문을 연 식당이 있더군요. 뤼카 마르케티의 식당입니다. 3만 유로. 제가 잘못 안 게 아니라면 동생분이시죠. 그리고 당신 회사는 그 기관을 컨설팅하고 있고요."),
(I, "... Trente mille euros ? Je... Je n'en savais rien, monsieur Ménard.", "...3만 유로요? 저는... 전혀 몰랐어요, 메나르 씨."),
(PM, "Je vous crois volontiers, mais mon métier est de vérifier. Je vous envoie les pièces que j'ai en main. Vous avez jusqu'à mercredi dix-huit heures pour me répondre. Le contradictoire, vous savez ce que c'est.",
     "기꺼이 믿고 싶습니다만, 확인하는 게 제 일이라서요. 제가 가진 자료를 보내 드리겠습니다. 수요일 오후 6시까지 답변 주시면 됩니다. 반론 기회라는 게 어떤 건지 아시잖아요."),
(I, "Je vous rappelle. Merci de m'avoir prévenue avant, et pas après.", "다시 전화드릴게요. 나중이 아니라 미리 알려 주셔서 감사해요."),
(None, "Elle raccroche. Le café refroidit. Mathieu la regarde sans un mot.", "그녀가 전화를 끊는다. 커피가 식어 간다. 마티외는 말없이 그녀를 바라본다."),
(MA, "Inès ? Qu'est-ce qu'il y a ? Tu es toute pâle.", "이네스? 무슨 일이야? 얼굴이 하얗게 질렸어."),
(I, "Lucas a reçu trente mille euros de notre client. Et je l'apprends par un journaliste.", "뤼카가 우리 고객한테서 3만 유로를 받았대. 그걸 기자한테 듣고 있어."),
(RA, "Je retire ce que j'ai dit sur vos têtes. Je vous les monte, les cafés ?", "얼굴 얘기한 거 취소할게. 커피는 위로 올려다 줄까?"),

# ---------- 2. Le dossier : les pièces et le doute ----------
(None, "8 h 45. Les bureaux d'Agora Stratégies, au-dessus du café. Sofia arrive, casque sur les oreilles, et comprend tout de suite.", "오전 8시 45분. 카페 위층 Agora Stratégies 사무실. 헤드폰을 낀 소피아가 들어오다가 곧바로 분위기를 알아챈다."),
(S, "Qui est mort ? Non, attendez, je ne veux pas savoir avant mon premier café.", "누가 죽었어요? 아니, 잠깐만요. 첫 커피 마시기 전엔 알고 싶지 않아요."),
(MA, "Personne. Le Courrier de Paris va écrire que le restaurant de Lucas a reçu trente mille euros de Provence Attractivité, pendant notre mission.", "아무도. Le Courrier de Paris가 뤼카 식당이 우리가 일하는 동안 Provence Attractivité에서 3만 유로를 받았다고 쓸 거야."),
(S, "Aïe. Le frère de la consultante subventionné par le client de la consultante. Le titre s'écrit tout seul.", "아이고. 컨설턴트의 고객이 컨설턴트의 동생에게 지원금을. 제목이 저절로 써지네요."),
(I, "Ménard vient d'envoyer les pièces. Je les projette. Sofia, prends des notes, tout ce qu'on dira aujourd'hui pourra être retenu contre nous.", "메나르가 방금 자료를 보냈어. 화면에 띄울게. 소피아, 메모해. 오늘 우리가 하는 말은 전부 우리에게 불리하게 쓰일 수 있어."),
(None, "Sur l'écran : la décision d'attribution, un tableau de notation, et une lettre de motivation à l'en-tête du restaurant.", "화면에는 지원금 지급 결정서, 심사 점수표, 그리고 식당 이름이 찍힌 지원 동기서가 떠 있다."),
(S, "Alors. Dispositif « Jeunes Pousses de Provence ». Dossier déposé le 12 décembre. Jury le 4 mars. Soixante-quatre candidatures, dix-neuf lauréats. Lucas est classé septième.",
    "자, 보자. « 프로방스 새싹 기업 » 지원 사업. 서류 접수 12월 12일. 심사 3월 4일. 지원 64건, 선정 19곳. 뤼카는 7위예요."),
(MA, "Le 12 décembre... Et notre contrat avec l'agence a été signé le 15 janvier. Le dossier est donc antérieur à notre mission.", "12월 12일이라... 우리랑 기관의 계약은 1월 15일에 서명됐어. 그러니까 서류가 우리 업무보다 먼저야."),
(I, "C'est déjà ça. Et le jury ? Qui siégeait ?", "그건 다행이네. 심사위원은? 누가 들어갔어?"),
(S, "Cinq personnes : deux chefs d'entreprise, une banquière, un représentant de la chambre de commerce et une enseignante d'école hôtelière. Personne de chez nous, personne de la direction de l'agence.",
    "다섯 명이요. 기업 대표 두 명, 은행원 한 명, 상공회의소 대표 한 명, 호텔 학교 교사 한 명. 우리 쪽 사람도, 기관 경영진도 없어요."),
(MA, "Attends, il y a une troisième pièce. Un « complément de dossier » daté du 20 janvier. Lis le dernier paragraphe, Sofia.", "잠깐, 세 번째 자료가 있어. 1월 20일자 « 서류 보완 ». 마지막 문단 읽어 봐, 소피아."),
(S, "« Je précise enfin que ma sœur, Inès Marchetti, accompagne désormais Provence Attractivité dans l'élaboration de sa nouvelle stratégie. » ... Oh.",
    "« 끝으로, 제 누나 이네스 마르케티가 현재 Provence Attractivité의 새 전략 수립을 돕고 있음을 밝힙니다. » ...아."),
(None, "Un silence. Mathieu se tourne vers Inès. Une seconde, pas plus.", "침묵. 마티외가 이네스 쪽으로 돌아선다. 단 1초, 그 이상은 아니다."),
(MA, "Tu... Tu savais qu'il allait écrire ça ?", "너... 걔가 이걸 쓸 거라는 거 알고 있었어?"),
(I, "Pardon ?", "뭐라고?"),
(MA, "Non, je veux dire... Je pose la question parce que Ménard va la poser.", "아니, 내 말은... 메나르가 물어볼 테니까 묻는 거야."),
(I, "Non, Mathieu. Ce n'est pas parce que Ménard va la poser. C'est parce que, pendant une seconde, tu t'es demandé si je t'avais menti.",
    "아니, 마티외. 메나르가 물을 거라서가 아니야. 1초 동안 네가 내가 너한테 거짓말을 했는지 궁금했던 거야."),
(S, "Euh... je vais chercher les cafés chez Rachid. Il y en a pour cinq bonnes minutes. Peut-être dix.", "어... 라시드한테 커피 가지러 갈게요. 족히 5분은 걸릴 거예요. 10분일 수도 있고요."),
(I, "Je n'ai jamais rien su de ce dossier. Ni la candidature, ni la lettre, ni l'argent. Je l'apprends en même temps que toi, et devant toi.", "난 이 서류에 대해 아무것도 몰랐어. 지원도, 편지도, 돈도. 너랑 동시에, 네 앞에서 알게 된 거야."),
(MA, "Je te crois. Évidemment que je te crois.", "믿어. 당연히 믿지."),
(I, "« Évidemment », c'est le mot qu'on emploie quand ça ne l'était pas tout à fait. On en reparlera. Pour l'instant, j'appelle mon frère.", "« 당연히 »라는 건, 완전히 당연하지는 않았을 때 쓰는 말이야. 이 얘긴 나중에 하자. 지금은 동생한테 전화할래."),
(None, "Haut-parleur. Bruit de casseroles, une hotte qui ronfle.", "스피커폰. 냄비 부딪치는 소리, 후드 돌아가는 소리."),
(L, "Inès ? Fais vite, j'ai quarante couverts à midi et mon commis s'est coupé le pouce.", "누나? 빨리 말해. 점심 예약 40명인데 보조 요리사가 엄지를 베었어."),
(I, "Lucas, est-ce que tu as reçu trente mille euros de Provence Attractivité ?", "뤼카, 너 Provence Attractivité에서 3만 유로 받았어?"),
(L, "Ah. Les Jeunes Pousses ? Oui, en mars. C'était censé être une surprise. Je te l'ai même dit, le soir de l'ouverture : j'ai trinqué « à ceux qui m'ont donné un coup de pouce ».",
    "아. 새싹 기업 지원금? 응, 3월에. 깜짝 소식으로 하려고 했지. 개업식 날 밤에 말하기까지 했잖아. « 나를 밀어 준 사람들을 위하여 » 하고 건배했다고."),
(I, "J'ai cru que tu parlais de papa et de sa banque ! Et la phrase sur moi, dans ta lettre du 20 janvier, c'était aussi une surprise ?", "난 아빠랑 아빠 은행 얘기인 줄 알았지! 그럼 1월 20일 편지에 쓴 내 얘기도 깜짝 선물이었어?"),
(L, "Quelle phrase ? ... Ah, celle-là. Le conseiller de la chambre de commerce m'avait dit de « mettre en valeur mon réseau ». Mon réseau, c'est maman, papa et toi. J'étais fier de toi, c'est tout.",
    "무슨 문장? ...아, 그거. 상공회의소 상담원이 « 인맥을 부각하라 »고 했거든. 내 인맥이라고 해 봐야 엄마, 아빠, 누나가 전부야. 누나가 자랑스러웠을 뿐이야."),
(I, "Lucas, un journaliste publie jeudi que tu as été aidé grâce à moi. Ne parle à personne. Je descends à Marseille demain matin.", "뤼카, 목요일에 어떤 기자가 네가 나 덕분에 지원금을 받았다고 기사를 써. 아무한테도 말하지 마. 내일 아침에 마르세유로 내려갈게."),
(L, "Grâce à toi ? J'ai bossé quatre mois sur ce dossier ! ... Bon. D'accord. Je te garde une table. Mais je te préviens, je suis furieux.", "누나 덕분에? 나 그 서류에 넉 달을 매달렸다고! ...알았어. 자리 하나 맡아 둘게. 근데 미리 말하는데, 나 엄청 화났어."),
(I, "Quatre mois sur un dossier, et il ne m'en a jamais parlé. Je ne sais pas si je dois être fière ou vexée.", "넉 달이나 서류를 붙잡고 있었는데 나한텐 한 번도 말을 안 했네. 자랑스러워해야 할지 서운해해야 할지 모르겠어."),
(MA, "Les deux, je pense. Il voulait sans doute te prouver qu'il pouvait y arriver sans sa grande sœur.", "둘 다겠지. 아마 누나 없이도 해낼 수 있다는 걸 보여 주고 싶었을 거야."),
(I, "Sans sa grande sœur, sauf dans le dernier paragraphe. Il faudrait appeler Hélène, mais je n'ai pas la force d'entendre ses proverbes avant midi.", "누나 없이, 마지막 문단만 빼고. 엘렌한테 전화해야 하는데, 정오 전에 그 격언들을 들을 기운이 없어."),
(MA, "Sofia l'a déjà fait, je parie. Elle n'est pas allée chercher des cafés, elle est allée chercher des renforts.", "소피아가 벌써 했을걸. 커피 가지러 간 게 아니라 지원군 부르러 간 거야."),
(S, "Les cafés sont là. Et Hélène monte à onze heures. Ne me regardez pas comme ça, c'était une urgence.", "커피 왔어요. 그리고 엘렌이 11시에 올라오신대요. 그렇게 보지 마세요, 비상 상황이었잖아요."),

# ---------- 3. Analyse : être honnête et le paraître ----------
(None, "11 h. Hélène est montée du café, comme chaque fois que Sofia l'appelle « juste pour un conseil ».", "오전 11시. 소피아가 « 조언 하나만 » 구하려고 전화할 때마다 그렇듯, 엘렌이 카페에서 올라왔다."),
(H, "Bien. Résumez-moi la situation en trois phrases. Pas une de plus, je vous connais.", "좋아. 상황을 세 문장으로 요약해 봐. 한 문장도 더 말고. 너희를 잘 아니까."),
(I, "Mon frère a obtenu une aide publique de notre client. Je ne le savais pas. Mais il a cité mon nom dans son dossier, et un journaliste le publie jeudi.", "제 동생이 우리 고객에게서 공적 지원금을 받았어요. 저는 몰랐어요. 그런데 동생이 서류에 제 이름을 적었고, 기자가 목요일에 그걸 보도해요."),
(H, "Parfait. Maintenant, la question qui fâche : y a-t-il eu conflit d'intérêts ?", "완벽해. 이제 불편한 질문. 이해충돌이 있었나?"),
(MA, "Juridiquement, je ne le pense pas. Inès n'a ni instruit le dossier, ni siégé au jury, ni même connu son existence. Elle n'a exercé aucune influence.", "법적으로는 아니라고 봐요. 이네스는 서류를 검토하지도, 심사위원도 아니었고, 그 존재조차 몰랐어요. 아무 영향력도 행사하지 않았어요."),
(H, "Tu réponds à la question « y a-t-il eu faute ? ». Ce n'est pas la même. Un conflit d'intérêts, c'est une situation de nature à influencer, ou à paraître influencer, une décision. Le verbe important, c'est « paraître ».",
    "넌 « 잘못이 있었나? »에 답하고 있어. 그건 다른 질문이야. 이해충돌이란 결정에 영향을 줄 수 있는, 또는 영향을 주는 것처럼 보일 수 있는 상황이야. 중요한 동사는 « 보이다 »지."),
(I, "Autrement dit, il ne suffit pas d'être honnête, il faut le paraître.", "다시 말해, 정직한 것만으로는 부족하고 정직해 보여야 한다는 거죠."),
(H, "La femme de César, ma chérie. Elle ne devait pas même être soupçonnée. Et vous, depuis Valmont, vous êtes un peu la femme de César du conseil politique.",
    "카이사르의 아내지. 의심조차 받아선 안 됐던 사람. 그리고 너희는 발몽 이후로 정치 컨설팅 업계의 카이사르의 아내 같은 존재야."),
(S, "Bon, je regarde les dates. Le dossier déposé avant notre contrat, un jury indépendant, et la phrase de Lucas n'apparaît dans aucune grille de notation. Les faits sont plutôt de notre côté.",
    "자, 날짜를 보면요. 서류는 우리 계약 전에 접수됐고, 심사위원은 독립적이고, 뤼카의 그 문장은 어떤 채점표에도 없어요. 사실관계는 대체로 우리 편이에요."),
(MA, "Et il y a mieux. Relisez notre propre rapport. Nous avons recommandé de recentrer les aides sur l'industrie et le port, et de réduire de moitié l'enveloppe du dispositif Jeunes Pousses.",
     "더 좋은 게 있어. 우리 보고서를 다시 읽어 봐. 우리는 지원을 산업과 항만에 집중하고, 새싹 기업 지원 사업 예산을 절반으로 줄이라고 권고했어."),
(I, "Autrement dit, si j'avais voulu favoriser mon frère, je m'y serais très mal prise. J'ai proposé de couper le robinet dont il a bu.", "다시 말해, 내가 동생을 밀어주려 했다면 아주 서툴게 한 셈이지. 동생이 물 마신 그 수도꼭지를 잠그자고 제안했으니까."),
(H, "Argument excellent. Gardez-le pour la fin. Un argument qui sonne trop bien au début ressemble à une excuse préparée.", "훌륭한 논거야. 마지막을 위해 아껴 둬. 처음부터 너무 그럴듯하게 들리는 논거는 준비된 변명처럼 보여."),
(MA, "Alors, trois options. Un : le silence, on laisse passer l'article. Deux : une réponse juridique, courte, par notre avocat. Trois : on prend les devants et on publie tout avant jeudi.",
     "그럼 선택지는 셋이야. 첫째, 침묵. 기사가 지나가게 둔다. 둘째, 변호사를 통한 짧은 법적 답변. 셋째, 선수를 쳐서 목요일 전에 전부 공개한다."),
(S, "Le silence, c'est exactement ce qu'on a déconseillé à Agnès Rivière pendant la rumeur. On ne peut pas prescrire un médicament et refuser de l'avaler.", "침묵은 루머 때 우리가 아녜스 리비에르에게 하지 말라고 했던 바로 그거예요. 약을 처방해 놓고 우리가 삼키길 거부할 순 없죠."),
(MA, "D'accord pour la transparence. Mais je ne veux pas qu'on s'accuse de ce qu'on n'a pas fait. Si on se retire du contrat, tout le monde dira : « Ils avouent. »",
     "투명 공개엔 찬성이야. 하지만 하지도 않은 일로 스스로를 고발하고 싶진 않아. 우리가 계약에서 빠지면 다들 « 자백하는 거다 »라고 할 거야."),
(I, "Et si on reste, on dira : « Ils s'accrochent. » Mathieu, il reste la phase deux : soixante mille euros pour la mise en œuvre de la stratégie, avec les mêmes équipes qui ont versé l'aide à mon frère.",
    "그리고 남으면 « 버틴다 »고 하겠지. 마티외, 2단계가 남아 있어. 전략 실행에 6만 유로, 그것도 내 동생에게 지원금을 준 바로 그 팀들이랑 같이."),
(MA, "La phase un est livrée et payée, quatre-vingt mille euros. On peut terminer proprement ce qui est fait et renoncer à ce qui reste. C'est un retrait, pas un aveu.",
     "1단계는 납품했고 8만 유로 받았어. 끝난 건 깔끔하게 마무리하고 남은 건 포기할 수 있어. 그건 철수지, 자백이 아니야."),
(I, "Voilà. Merci. On se déporte de la suite, on ne se dénonce pas.", "그거야. 고마워. 남은 일에서 물러나는 거지, 우리를 고발하는 게 아니야."),
(H, "Et Lucas ? Il a obtenu cette aide régulièrement. Vous ne pouvez pas décider à sa place.", "그럼 뤼카는? 그 지원금은 정당하게 받은 거야. 너희가 대신 결정할 순 없어."),
(I, "Je sais. C'est son restaurant, son dossier, son argent. Je peux lui expliquer ce que la phrase lui coûtera. Le reste lui appartient.", "알아요. 그 애 식당이고, 그 애 서류고, 그 애 돈이에요. 그 문장이 그 애한테 무슨 대가를 치르게 할지 설명할 수는 있어요. 나머지는 그 애 몫이에요."),
(S, "Je prépare une chronologie complète, pièce par pièce. Date, document, qui savait quoi, et quand. Si une seule date est fausse, on est morts.", "제가 서류별로 전체 연표를 만들게요. 날짜, 문서, 누가 무엇을 언제 알았는지. 날짜 하나만 틀려도 우린 끝이에요."),
(MA, "Et j'appelle la directrice de cabinet de l'agence pour demander à être entendus par leur comité de déontologie. Demain, si possible, avant que l'article ne sorte.",
     "그리고 나는 기관 비서실장에게 전화해서 그쪽 윤리위원회에 출석하겠다고 요청할게. 가능하면 내일, 기사가 나오기 전에."),
(H, "Bien. Une dernière chose. Il manque quelque chose à votre cabinet, et cette affaire vient de le révéler.", "좋아. 마지막으로 하나. 너희 회사에 뭔가 빠진 게 있고, 이번 일이 그걸 드러냈어."),
(I, "Une règle écrite. On a trois principes au mur, mais aucune procédure. Personne chez nous n'a jamais déclaré les intérêts de sa famille.", "성문화된 규칙이요. 벽에 원칙 세 개는 붙어 있지만 절차는 하나도 없어요. 우리 중 누구도 가족의 이해관계를 신고한 적이 없어요."),
(H, "Exactement. Les principes, c'est ce qu'on affiche. La déontologie, c'est ce qu'on fait le mardi matin quand le téléphone sonne.", "바로 그거야. 원칙은 내거는 거고, 직업윤리는 화요일 아침 전화가 울릴 때 하는 거야."),
(S, "Je note pour plus tard : « Hélène, tasse de citations ». On pourrait les imprimer sur des mugs.", "나중을 위해 적어 둘게요. « 엘렌, 명언 머그컵 ». 머그컵에 인쇄해도 되겠어요."),
(H, "Ne te moque pas, Sofia. Ces mugs-là, j'en ai payé chaque phrase.", "놀리지 마, 소피아. 그 머그컵의 문장 하나하나 내가 값을 치르고 얻은 거야."),
(MA, "Inès... Tu veux bien qu'on fasse la route ensemble demain ?", "이네스... 내일 같이 내려가도 될까?"),
(I, "C'est notre cabinet et notre signature. Évidemment. ... Tu vois, moi, quand je dis « évidemment », c'est que ça l'est.", "우리 회사고 우리 서명이야. 당연하지. ...봐, 난 « 당연하지 »라고 하면 정말 당연한 거야."),
(MA, "Message reçu.", "잘 알아들었어."),
(None, "17 h 40. Inès rappelle Paul Ménard et lui annonce qu'Agora publiera l'intégralité des pièces mercredi soir, avant son article.", "오후 5시 40분. 이네스가 폴 메나르에게 다시 전화해, Agora가 기사보다 먼저 수요일 저녁에 모든 자료를 공개할 거라고 알린다."),
(PM, "Vous publiez avant moi ? C'est la première fois qu'on me grille la politesse avec mes propres documents. J'avoue que j'apprécie le procédé.", "저보다 먼저 공개하시겠다고요? 제 자료로 저를 앞질러 가는 사람은 처음이군요. 솔직히 그 방식이 마음에 듭니다."),

# ---------- 4. Terrain : Marseille, le restaurant et le comité ----------
(None, "Mercredi, 11 h. Marseille. Le restaurant de Lucas, encore vide avant le service. Sur la vitrine, un petit autocollant vert : « Lauréat Jeunes Pousses de Provence ».",
       "수요일 오전 11시. 마르세유. 영업 전이라 아직 텅 빈 뤼카의 식당. 유리창에 작은 초록색 스티커가 붙어 있다. « 프로방스 새싹 기업 선정 »."),
(MA, "Bonjour, Lucas. Ça sent drôlement bon, ici. Des panisses ?", "안녕, 뤼카. 여기 냄새 정말 좋다. 파니스야?"),
(L, "Panisses, supions, et un loup grillé. On ne change pas une équipe qui gagne. Bonjour, Mathieu. Toi, au moins, tu n'as pas l'air d'un avocat.", "파니스, 꼴뚜기, 농어구이. 이기는 팀은 바꾸는 게 아니지. 안녕, 마티외. 형은 적어도 변호사처럼 보이진 않네."),
(I, "Il était là, l'autocollant, le soir de l'ouverture ?", "개업식 날 밤에도 이 스티커 있었어?"),
(L, "Juste à côté de ta chaise. Tu l'as regardé trois fois. Tu croyais que c'était un label bio.", "누나 의자 바로 옆에. 세 번이나 봤어. 유기농 인증 마크인 줄 알더라."),
(L, "Je vais te dire ce qui me rend fou. J'ai fait les comptes, le business plan, les devis du four, quatre mois de paperasse. Et demain, toute la France va lire que c'est ma sœur qui m'a obtenu l'argent.",
    "뭐가 날 미치게 하는지 말해 줄게. 손익 계산, 사업 계획서, 오븐 견적서, 넉 달 동안 서류 작업을 내가 했어. 그런데 내일 프랑스 전체가 누나가 나한테 돈을 받아 줬다고 읽게 되겠지."),
(MA, "Personne ne conteste ton travail, Lucas. Ton dossier a été classé septième par un jury qui ne connaissait ni Inès ni Agora. C'est la phrase qui pose problème, pas le restaurant.",
     "아무도 네 노력을 부정하지 않아, 뤼카. 네 서류는 이네스도 Agora도 모르는 심사위원들이 7위로 뽑았어. 문제는 그 문장이지, 식당이 아니야."),
(L, "Une phrase ! J'ai écrit une phrase de fierté, et c'est elle qui va tout salir.", "문장 하나! 자랑스러워서 문장 하나 썼는데, 그게 다 더럽히게 생겼네."),
(I, "Lucas, écoute-moi. Je ne te demande rien. Je t'explique seulement ce qui se passera. Si tu gardes l'aide, chaque client qui lira l'article se demandera si ton assiette a été payée par piston.",
    "뤼카, 내 말 들어. 너한테 아무것도 요구하지 않아. 무슨 일이 생길지 설명만 하는 거야. 지원금을 가지고 있으면, 기사를 읽은 손님마다 네 접시가 연줄로 산 건지 의심할 거야."),
(L, "Et si je la rends ?", "그럼 돌려주면?"),
(I, "Alors l'article parlera d'un jeune chef qui a rendu trente mille euros qu'il avait obtenus régulièrement. Ce n'est pas tout à fait le même titre.", "그럼 기사는 정당하게 받은 3만 유로를 돌려준 젊은 셰프 이야기가 되겠지. 제목이 꽤 달라지잖아."),
(L, "... Papa m'a dit exactement la même chose hier soir. Avec moins de mots et plus de Mozart. Je la rends. Mais c'est moi qui écris la lettre. Pas toi, pas ton cabinet.",
    "...어젯밤에 아빠도 똑같은 말을 했어. 말은 더 적게, 모차르트는 더 크게 틀어 놓고. 돌려줄게. 근데 편지는 내가 써. 누나도, 누나 회사도 아니고."),
(I, "C'est la seule condition que j'aurais posée moi-même.", "그게 바로 내가 걸었을 유일한 조건이야."),
(MA, "Tu veux un coup de main pour la formulation, au moins ? Une lettre de restitution, ça a ses codes.", "표현이라도 좀 도와줄까? 반납 편지에도 나름의 격식이 있거든."),
(L, "Non. J'écrirai : « Je rends cet argent parce que je veux que mon restaurant soit jugé dans l'assiette. » C'est assez codé pour vous ?", "아니. 이렇게 쓸 거야. « 제 식당이 접시로 평가받기를 원하기에 이 돈을 돌려드립니다. » 이 정도면 격식 있어?"),
(I, "C'est le meilleur code que je connaisse.", "내가 아는 최고의 격식이야."),
(None, "14 h 30. Siège de Provence Attractivité, salle du comité de déontologie. Autour de la table : Henri Lavigne, ancien magistrat, qui préside le comité, et Nadira Achour, déontologue de l'agence.",
       "오후 2시 30분. Provence Attractivité 본사, 윤리위원회 회의실. 테이블에는 전직 판사로 위원회를 이끄는 앙리 라비뉴와 기관의 윤리 담당관 나디라 아슈르가 앉아 있다."),
(LV, "Madame Marchetti, monsieur Kessler, c'est vous qui avez demandé à être entendus. C'est assez rare pour que je le souligne. La plupart des gens attendent qu'on les convoque.",
     "마르케티 씨, 케슬레르 씨, 출석을 요청한 건 두 분이십니다. 짚고 넘어갈 만큼 드문 일이에요. 대부분은 소환될 때까지 기다리거든요."),
(MA, "Nous préférons expliquer les faits avant qu'on ne les commente, monsieur le président.", "논평이 나오기 전에 사실을 먼저 설명드리는 쪽을 택했습니다, 위원장님."),
(AC, "J'ai étudié votre chronologie. Elle concorde avec nos propres registres. Une question, cependant : à quelle date avez-vous eu connaissance de la candidature de votre frère ?",
     "보내 주신 연표를 검토했습니다. 저희 기록과 일치합니다. 다만 질문이 하나 있습니다. 동생분의 지원 사실을 언제 아셨습니까?"),
(I, "Hier matin, à huit heures vingt-cinq, par un appel du Courrier de Paris. Je ne vous demande pas de me croire sur parole : mes messages avec mon frère depuis décembre sont à votre disposition.",
    "어제 오전 8시 25분, Le Courrier de Paris의 전화로 알았습니다. 제 말만 믿어 달라는 게 아닙니다. 12월 이후 동생과 주고받은 메시지를 모두 제공하겠습니다."),
(AC, "Vous avez pourtant présenté votre rapport à notre direction en avril, quelques jours après l'ouverture du restaurant. Le sujet n'a jamais été évoqué ?", "그런데 4월, 식당 개업 며칠 뒤에 저희 경영진에게 보고서를 발표하셨죠. 그 얘기가 한 번도 나오지 않았나요?"),
(I, "Jamais, madame. Personne autour de cette table ne savait, moi la première. Vos procès-verbaux de réunion le confirmeront : on y parle de port, d'industrie et de budget, pas de mon frère.",
    "한 번도요. 그 자리의 누구도 몰랐고, 저부터가 몰랐습니다. 회의록을 보시면 확인될 겁니다. 항만, 산업, 예산 얘기뿐이고 제 동생 얘기는 없어요."),
(AC, "C'est noté. Je préférais vous le demander moi-même plutôt que de le lire jeudi.", "기록해 두겠습니다. 목요일에 기사로 읽느니 직접 여쭤보는 게 낫겠다 싶었어요."),
(MA, "Posez-nous toutes les questions qui vous viennent, madame. Nous préférons vos soupçons aujourd'hui à ceux des lecteurs demain.", "떠오르는 질문은 전부 해 주십시오. 내일 독자들의 의심보다 오늘 담당관님의 의심이 낫습니다."),
(LV, "Le comité ne relève, à ce stade, aucun élément laissant penser que vous ayez influencé la décision du jury. Il n'en demeure pas moins que la situation, telle qu'elle se présente, est de nature à jeter le doute.",
     "위원회는 현 단계에서 두 분이 심사위원의 결정에 영향을 미쳤다고 볼 만한 요소를 전혀 찾지 못했습니다. 그렇다 하더라도, 지금 드러난 상황은 의심을 불러일으킬 만한 것입니다."),
(MA, "Nous en sommes conscients. C'est pourquoi nous venons vous proposer deux mesures, et vous annoncer une troisième qui ne dépend pas de nous.", "저희도 그 점을 알고 있습니다. 그래서 두 가지 조치를 제안드리고, 저희 소관이 아닌 세 번째 조치를 알려 드리러 왔습니다."),

# ---------- 5. Décision : le retrait, la restitution, la charte ----------
(I, "Première mesure : Agora Stratégies renonce à la phase deux de sa mission, soit soixante mille euros. La phase un, livrée en avril, reste à votre disposition, et nous vous aiderons à choisir un autre cabinet pour la suite.",
    "첫째, Agora Stratégies는 2단계 업무, 즉 6만 유로를 포기합니다. 4월에 납품한 1단계 결과물은 계속 쓰실 수 있고, 후속 업무를 맡을 다른 회사 선정을 돕겠습니다."),
(LV, "Vous renoncez à soixante mille euros alors que le comité ne vous reproche rien. Permettez-moi de vous demander pourquoi.", "위원회가 아무 잘못도 지적하지 않았는데 6만 유로를 포기하신다고요. 이유를 여쭤봐도 되겠습니까?"),
(I, "Parce que la phase deux consiste à mettre en œuvre la réorientation des aides, y compris du dispositif dont mon frère a bénéficié. Si honnête que je sois, je serais juge et partie.",
    "2단계는 지원금 재편을 실행하는 일인데, 거기엔 제 동생이 혜택을 받은 사업도 포함되기 때문입니다. 제가 아무리 정직하다 해도, 심판이자 당사자가 되는 셈이죠."),
(MA, "Deuxième mesure : nous publions ce soir, sur notre site, la totalité des pièces : contrat, chronologie, rapport de phase un et lettre de mon associée au comité. Rien ne sera expurgé, hormis les données personnelles des autres candidats.",
     "둘째, 오늘 저녁 저희 웹사이트에 모든 자료를 공개합니다. 계약서, 연표, 1단계 보고서, 그리고 제 공동 대표가 위원회에 보낸 편지까지요. 다른 지원자의 개인정보 말고는 아무것도 지우지 않겠습니다."),
(AC, "Et la troisième, celle qui ne dépend pas de vous ?", "그리고 두 분 소관이 아니라는 세 번째는요?"),
(I, "Mon frère a décidé, seul, de restituer l'intégralité de l'aide. Sa lettre vous parviendra demain. Je tiens à préciser qu'il l'avait obtenue de bonne foi et selon les règles.",
    "제 동생이 스스로 지원금 전액을 반납하기로 결정했습니다. 편지는 내일 도착할 겁니다. 동생은 선의로, 규정에 따라 그 돈을 받았다는 점을 분명히 말씀드리고 싶습니다."),
(LV, "C'est un geste fort. Peut-être même excessif. Le comité en prendra acte, et le précisera dans son avis.", "강한 결단이군요. 어쩌면 지나칠 정도로요. 위원회는 이를 확인하고 의견서에 명시하겠습니다."),
(AC, "Je me permets une remarque. Votre rapport de phase un recommande de réduire de moitié l'enveloppe des Jeunes Pousses. Vous ne l'avez pas mentionné une seule fois.",
     "한 말씀 드리죠. 1단계 보고서는 새싹 기업 지원 예산을 절반으로 줄이라고 권고하던데요. 그 얘긴 한 번도 안 하셨네요."),
(I, "Loin de moi l'idée de m'en servir comme d'un bouclier, madame. Ce n'est pas parce qu'une recommandation me dessert qu'elle me disculpe.",
    "그걸 방패로 쓸 생각은 전혀 없습니다. 어떤 권고가 저에게 불리하다고 해서 그게 저를 결백하게 만들어 주지는 않으니까요."),
(LV, "C'est pourtant l'élément qui m'a le plus convaincu. On défend rarement sa famille en lui coupant les vivres.", "그런데 그게 저를 가장 설득한 요소입니다. 가족의 생계를 끊으면서 가족을 감싸는 사람은 드물죠."),
(LV, "Le comité rendra demain un avis public. Il conclura à l'absence de conflit d'intérêts avéré, prendra acte de votre retrait et recommandera à l'agence d'exiger désormais de ses prestataires une déclaration d'intérêts.",
     "위원회는 내일 공개 의견서를 내겠습니다. 실제 이해충돌은 없었다고 결론짓고, 두 분의 철수를 확인하며, 앞으로 기관이 용역업체에 이해관계 신고서를 요구하도록 권고할 겁니다."),
(MA, "Sur ce dernier point, monsieur le président, nous aimerions ne pas attendre qu'on nous l'impose.", "그 마지막 부분에 대해서는, 위원장님, 저희는 강제되기 전에 먼저 하고 싶습니다."),
(I, "Nous rédigerons cette nuit une charte de déontologie, et nous la publierons avec nos propres déclarations. Vous serez les premiers à la recevoir.", "오늘 밤 윤리 강령을 작성해서 저희 자신의 신고서와 함께 공개하겠습니다. 가장 먼저 받아 보실 겁니다."),
(None, "Jeudi, 7 h. Paris. Les bureaux d'Agora. L'article de Paul Ménard est en ligne depuis une heure. Sofia le lit à voix haute, Hélène écoute, tasse à la main.",
       "목요일 오전 7시. 파리, Agora 사무실. 폴 메나르의 기사가 한 시간 전부터 온라인에 올라와 있다. 소피아가 소리 내어 읽고, 엘렌은 찻잔을 든 채 듣는다."),
(S, "Titre : « Aides publiques en Provence : un chef rend trente mille euros, ses consultants se retirent ». Pas de « scandale », pas de point d'exclamation. Troisième paragraphe : « Fait rare, le cabinet avait rendu publiques les pièces la veille. »",
    "제목: « 프로방스 공적 지원금: 셰프는 3만 유로를 반납하고, 컨설턴트들은 물러났다 ». « 스캔들 »도 없고 느낌표도 없어요. 세 번째 문단: « 이례적으로, 해당 회사는 전날 자료를 공개했다. »"),
(H, "Ménard a été juste. C'est tout ce qu'on peut demander à un journaliste. Et c'est beaucoup.", "메나르가 공정했네. 기자한테 바랄 수 있는 건 그게 전부야. 그리고 그건 대단한 거지."),
(S, "Et la chambre régionale de commerce vient de partager notre chronologie. Deux élus de Valmont aussi. Agnès Rivière a écrit : « Je les ai vus faire, ils font ce qu'ils disent. »",
    "그리고 지역 상공회의소가 방금 우리 연표를 공유했어요. 발몽 시의원 두 명도요. 아녜스 리비에르는 « 제가 직접 봤어요, 이 사람들은 말한 대로 합니다 »라고 썼고요."),
(I, "Bien. Reste le plus important. Sofia, tu peux afficher le projet de charte ?", "좋아. 가장 중요한 게 남았어. 소피아, 강령 초안 띄워 줄래?"),
(S, "« Charte de déontologie d'Agora Stratégies, article premier. » Je vous laisse le lire, c'est vous qui l'avez écrit à deux heures du matin.", "« Agora Stratégies 윤리 강령, 제1조. » 두 분이 읽으세요. 새벽 2시에 두 분이 쓰신 거니까."),
(I, "« Avant toute mission, chaque associé et chaque collaborateur déclare par écrit les intérêts, directs ou indirects, de ses proches : conjoint, parents, frères et sœurs, enfants, susceptibles d'interférer avec le client ou ses décisions. »",
    "« 모든 업무에 앞서 각 공동 대표와 직원은 배우자, 부모, 형제자매, 자녀 등 가까운 사람의 직간접적 이해관계 가운데 고객이나 고객의 결정과 얽힐 수 있는 것을 서면으로 신고한다. »"),
(MA, "« Article deux. Toute déclaration est transmise au client avant la signature du contrat. En cas de doute, l'associé concerné se déporte. Le doute profite toujours au client, jamais au cabinet. »",
     "« 제2조. 모든 신고서는 계약 서명 전에 고객에게 전달한다. 의심스러운 경우 해당 공동 대표는 업무에서 물러난다. 의심의 이익은 언제나 고객에게 돌아가며, 회사에 돌아가지 않는다. »"),
(H, "« Le doute profite au client. » Vous avez renversé un principe de droit pénal. C'est audacieux, mais ça vous ressemble.", "« 의심의 이익은 고객에게. » 형법 원칙 하나를 뒤집었네. 대담하지만, 너희답구나."),
(S, "Article trois, j'ai ajouté le mien : « La déclaration est mise à jour chaque fois qu'un frère ouvre un restaurant. » Je plaisante. Presque.", "제3조는 제가 넣었어요. « 남동생이 식당을 열 때마다 신고서를 갱신한다. » 농담이에요. 거의요."),
(I, "Garde-le. En version sérieuse : « mise à jour au moins une fois par an, et à chaque changement de situation ». Mon frère sera ravi d'avoir inspiré un article de loi interne.",
    "남겨 둬. 진지한 버전으로: « 최소 연 1회, 그리고 상황이 바뀔 때마다 갱신한다 ». 내 동생은 사내 법 조항에 영감을 줬다고 좋아하겠네."),
(MA, "Et on commence par nous. Je déclare : ma grand-mère, Odile Kessler, Colmar... aucun intérêt économique connu, sauf dans le commerce des bredeles à Noël.",
     "그리고 우리부터 시작하자. 신고합니다. 할머니 오딜 케슬레르, 콜마르 거주... 알려진 경제적 이해관계 없음. 크리스마스 브레델레 거래만 빼고요."),
(H, "Riez, riez. Mais publiez-la aujourd'hui, avec vos deux déclarations signées. Une charte qui n'engage que l'avenir n'engage personne.", "웃어, 웃어. 하지만 오늘 너희 두 사람 서명한 신고서와 함께 공개해. 미래만 구속하는 강령은 아무도 구속하지 않아."),
(I, "C'est fait à midi. Et Mathieu, tu envoies le lien à Lavigne et à Mme Achour, avec nos remerciements.", "정오에 할게요. 그리고 마티외, 라비뉴 위원장님과 아슈르 담당관님께 감사 인사와 함께 링크 보내 줘."),
(MA, "Je m'en occupe. Et à Ménard aussi. Il a l'habitude de vérifier que les gens tiennent leurs promesses.", "내가 할게. 메나르에게도. 그 사람은 사람들이 약속을 지키는지 확인하는 게 습관이니까."),
(None, "Le téléphone de Sofia vibre. Elle lit, sourit, tourne l'écran vers eux : un message de Lucas.", "소피아의 휴대폰이 울린다. 그녀가 읽고는 웃으며 화면을 두 사람 쪽으로 돌린다. 뤼카의 메시지다."),
(S, "« Trois réservations de journalistes pour ce midi. Dites à ma sœur que la transparence, ça remplit les salles. Et que je suis toujours furieux. »", "« 오늘 점심에 기자들 예약이 세 건. 누나한테 전해 줘요, 투명성이 손님을 채운다고. 그리고 나 아직 화나 있다고. »"),
(I, "Furieux et complet. C'est tout à fait lui.", "화났는데 만석. 딱 걔답네."),
(MA, "Il tient de sa sœur. Toi aussi, quand tu es furieuse, tu fais salle comble.", "누나를 닮았네. 너도 화나면 사람이 꽉 차잖아."),

# ---------- 6. Le soir : la seconde de trop ----------
(None, "Jeudi, 22 h. L'appartement d'Oberkampf. Figaro dort sur la pile des pièces imprimées. Mathieu a préparé une tarte à l'oignon ; Inès n'y a presque pas touché.",
       "목요일 밤 10시. 오베르캉프 아파트. 피가로는 출력해 둔 자료 더미 위에서 자고 있다. 마티외가 양파 타르트를 만들었지만 이네스는 거의 손대지 않았다."),
(MA, "Tu as à peine mangé. Ma tarte est ratée, ou c'est moi ?", "거의 안 먹었네. 내 타르트가 실패작이야, 아니면 나 때문이야?"),
(I, "Ta tarte est parfaite. C'est mardi matin qui ne passe pas.", "타르트는 완벽해. 넘어가지 않는 건 화요일 아침이야."),
(MA, "Je sais. J'ai tourné ça dans ma tête toute la journée, entre Lavigne et la charte. Laisse-moi le dire jusqu'au bout, sans m'interrompre, d'accord ?", "알아. 라비뉴 만나고 강령 쓰는 내내 하루 종일 그 생각만 했어. 끝까지 말하게 해 줘, 끊지 말고. 알았지?"),
(I, "D'accord. Jusqu'au bout.", "알았어. 끝까지."),
(MA, "Mardi, quand Sofia a lu la phrase de Lucas, j'ai douté. Pas longtemps. Une seconde. Mais j'ai douté de toi, et tu l'as vu.", "화요일에 소피아가 뤼카의 문장을 읽었을 때, 나 의심했어. 오래는 아니야. 1초. 그래도 너를 의심했고, 넌 그걸 봤지."),
(MA, "Et je me suis caché derrière Ménard pour ne pas l'admettre. C'était lâche. J'ai douté une seconde. C'est une seconde de trop.", "그리고 인정하지 않으려고 메나르 뒤에 숨었어. 비겁했어. 1초 의심했어. 그 1초가 너무 많은 거야."),
(I, "Tu sais pourquoi ça m'a fait si mal ? Parce que tout le monde allait douter de moi jeudi : le journal, l'agence, peut-être nos clients. Je m'y étais préparée. Mais pas à toi.",
    "그게 왜 그렇게 아팠는지 알아? 목요일엔 모두가 날 의심할 거였거든. 신문, 기관, 어쩌면 우리 고객들까지. 그건 각오하고 있었어. 근데 너는 아니었어."),
(MA, "Je sais. Pour eux, tu es une consultante. Pour moi, tu es la personne qui a refusé de me laisser finir une phrase à Saint-Étienne, et qui est revenue sur un quai de gare. Je n'ai aucune excuse.",
     "알아. 그 사람들한테 넌 컨설턴트지. 나한테 넌 생테티엔에서 내가 말을 끝내게 두지 않았다가 기차역 플랫폼으로 돌아온 사람이야. 변명의 여지가 없어."),
(I, "Il y a deux ans, j'ai fait mes valises sans t'écouter. Mardi, tu as eu une seconde de doute et tu viens me l'avouer avec une tarte. On progresse, non ?", "2년 전엔 내가 네 말도 안 듣고 짐을 쌌지. 화요일엔 네가 1초 의심했고, 지금 타르트 들고 와서 고백하고 있고. 우리 나아지고 있는 거 아니야?"),
(MA, "Tu veux dire que tu me pardonnes ?", "용서해 준다는 거야?"),
(I, "Je veux dire que je t'aime, et que je te ferai payer cette seconde pendant très longtemps. Une tarte à l'oignon par mois, minimum.", "사랑한다는 거고, 그 1초는 아주 오랫동안 갚게 할 거라는 거야. 양파 타르트 한 달에 하나, 최소한."),
(MA, "C'est cher, mais je signe. Avec déclaration d'intérêts : je suis amoureux de mon associée.", "비싸지만 서명할게. 이해관계 신고서 첨부해서. 저는 제 공동 대표를 사랑합니다."),
(I, "Conflit d'intérêts avéré. Le comité prend acte, et ne te demande pas de te déporter.", "이해충돌 확인. 위원회는 이를 인정하며, 업무에서 물러날 것을 요구하지 않음."),
(MA, "Et Lucas ? Il m'en veut, tu crois ? Je l'ai trouvé froid, hier.", "뤼카는? 나한테 화났을까? 어제 좀 차갑던데."),
(I, "C'est à moi qu'il en veut, ce qui est beaucoup plus sain. Il a appelé papa trois fois aujourd'hui. Papa a mis Les Noces de Figaro à fond. Bon signe.", "화난 건 나한테야. 그게 훨씬 건강하지. 오늘 아빠한테 세 번 전화했대. 아빠가 「피가로의 결혼」을 크게 틀었다니까, 좋은 신호야."),
(None, "Mathieu se lève, prend le vieux marqueur vert sur l'étagère, à côté de la Stéphanoise, et écrit sur le tableau blanc du salon.", "마티외가 일어나 선반 위 스테파누아즈 옆에 놓인 낡은 초록 마커를 집어 들고 거실 화이트보드에 적는다."),
(MA, "Quel est le vrai problème ? Ce n'était pas l'article. C'était la seconde. Qui décide ? Toi, de me la pardonner. Que fait-on lundi ?", "진짜 문제는 뭔가? 기사가 아니었어. 그 1초였지. 누가 결정하나? 너야, 용서할지 말지. 월요일엔 뭘 하나?"),
(I, "Lundi, on fait signer la charte à Sofia. Et on lui propose autre chose qu'une signature de collaboratrice. Elle a tenu la maison toute la semaine.",
    "월요일엔 소피아한테 강령에 서명하게 하고, 직원 서명 말고 다른 것도 제안하자. 이번 주 내내 회사를 지탱한 건 그 애야."),
(MA, "Associée ? Tu es sûre ? Une troisième signature, ce sont des voix de plus quand il faudra choisir. Et un jour, on ne sera peut-être pas d'accord sur un gros contrat.",
     "공동 대표? 확실해? 서명이 셋이 되면 결정할 때 목소리가 하나 더 느는 거야. 그리고 언젠가 큰 계약을 두고 우리 의견이 갈릴 수도 있고."),
(I, "C'est justement pour ça, Strasbourg. Le jour où toi et moi ne serons pas d'accord, j'aimerais qu'il y ait quelqu'un pour nous poser les trois questions.",
    "바로 그래서야, 스트라스부르. 너랑 내 의견이 갈리는 날, 우리한테 세 가지 질문을 던져 줄 사람이 있었으면 좋겠어."),
(MA, "Alors lundi, on le lui propose. Et quoi qu'il arrive ensuite, on se dit tout le soir même. C'est la règle.", "그럼 월요일에 제안하자. 그리고 그다음에 무슨 일이 생기든, 그날 저녁에 다 말하는 거야. 그게 규칙이야."),
(None, "Figaro s'étire sur la pile de documents, fait tomber la charte imprimée, et se rendort dessus.", "피가로가 서류 더미 위에서 기지개를 켜다 출력한 강령을 떨어뜨리고는 그 위에서 다시 잠든다."),
]

VOCAB = [
("C1", "la déontologie", "직업윤리, 직무 윤리 규범", "éthique(일반 윤리)보다 구체적인 직업상의 의무. un comité de déontologie, un(e) déontologue(윤리 담당관)."),
("C1", "une déclaration d'intérêts", "이해관계 신고(서)", "공직자·자문위원이 자신과 가족의 이해관계를 신고하는 문서. déclarer ses intérêts."),
("C1", "se déporter", "(이해관계 때문에) 심의·업무에서 물러나다", "법률 용어. 판사·위원이 스스로 사건에서 빠지는 것. On se déporte de la suite."),
("C1", "être juge et partie", "심판이자 당사자이다", "이해충돌의 고전적 표현. Si honnête que je sois, je serais juge et partie."),
("B2", "le contradictoire", "반론권, 상대방의 해명을 듣는 절차", "법정·언론 윤리 용어. 기자가 보도 전 당사자에게 반론 기회를 주는 것."),
("B2", "une subvention / une aide publique", "보조금 / 공적 지원금", "verser, attribuer, obtenir une aide. 수혜자는 le bénéficiaire, 선정자는 le lauréat."),
("B2", "un lauréat", "수상자, (공모) 선정자", "lauréat d'un concours, d'un appel à projets. 여성형 lauréate."),
("B2", "restituer (une somme)", "(금액을) 반환하다, 돌려주다", "rendre보다 격식체. la restitution de l'aide."),
("B2", "de bonne foi", "선의로, 악의 없이", "↔ de mauvaise foi. 법률에서 '선의'는 사정을 모르고 했다는 뜻."),
("C1", "il n'en demeure pas moins que", "그렇다 하더라도 ~임에는 변함없다", "앞 내용을 인정한 뒤 반론을 펴는 문어체 연결어. = il n'empêche que."),
("C1", "loin de moi l'idée de + 부정사", "~할 생각은 전혀 없다", "해명·변론에서 오해를 미리 막는 정중한 표현."),
("C1", "disculper qn", "~의 혐의를 벗기다, 결백을 증명하다", "se disculper = 해명하다. ↔ inculper(기소하다)."),
("B2", "prendre les devants", "선수를 치다, 먼저 손을 쓰다", "위기 커뮤니케이션의 핵심. On prend les devants et on publie tout."),
("C1", "griller la politesse à qn", "(구어) ~를 앞질러 가다, 새치기하다", "원래 '인사도 없이 먼저 가 버리다'. 기자가 특종을 빼앗길 때 즐겨 씀."),
("B2", "par piston", "연줄로, 빽으로", "구어. avoir du piston = 연줄이 있다. pistonner qn = 밀어 주다."),
("B2", "un coup de pouce", "작은 도움, 밀어 주기", "직역 '엄지손가락으로 한 번 밀기'. donner un coup de pouce à qn."),
("C1", "couper les vivres à qn", "~의 돈줄을 끊다", "vivres = 식량. 가족 간 경제적 지원을 끊을 때 자주 씀."),
("B2", "prendre acte de qc", "~을 정식으로 확인하다, 인지하다", "회의·위원회 공식 표현. Le comité en prendra acte."),
("C1", "avéré(e)", "사실로 확인된", "un conflit d'intérêts avéré ↔ potentiel/apparent. un risque avéré."),
("B2", "concorder avec", "~와 일치하다", "Votre chronologie concorde avec nos registres. 증언·자료 대조에 씀."),
("B2", "les couverts (au restaurant)", "(식당의) 손님 수, 좌석 수", "J'ai quarante couverts à midi = 점심 예약 40명. 원래는 식기 한 벌."),
("B1", "un commis (de cuisine)", "주방 보조, 견습 요리사", "식당 주방 위계: chef, second, chef de partie, commis."),
("B2", "trinquer à qn / qc", "~를 위해 건배하다", "On trinque à ceux qui m'ont donné un coup de pouce."),
("B2", "Ça ne passe pas.", "(마음에) 걸려서 넘어가지 않는다", "음식이 안 넘어가다 → 일·말이 용서되지 않다. C'est mardi matin qui ne passe pas."),
]

GRAM = [
("C1", "si / tout... que + 접속법·직설법: 양보",
 "« Si honnête que je sois, je serais juge et partie. » si(aussi) + 형용사 + que 뒤에는 접속법을 써서 '아무리 ~할지라도'를 나타낸다. 같은 뜻의 tout + 형용사 + que는 원래 직설법(tout honnête que je suis)을 쓰지만 현대 문어에서는 접속법도 쓰인다. quelque + 형용사 + que(Quelque honnête qu'il soit)는 더 문어적이다."),
("C1", "il n'en demeure pas moins que / il n'empêche que: 인정 후 반박",
 "« Le comité ne relève aucun élément... Il n'en demeure pas moins que la situation est de nature à jeter le doute. » 앞 문장의 내용을 인정하면서도 결론을 뒤집는 변론·판결문 문체. 뒤에는 직설법. 구어에서는 n'empêche que, quand même로 바꿀 수 있다."),
("C1", "부정 판단 뒤의 접속법(과거)",
 "« aucun élément laissant penser que vous ayez influencé la décision » « Je ne le pense pas. » 사실이 아니라고 판단하는 내용(aucun élément ne laisse penser que, je ne pense pas que, rien n'indique que)은 접속법으로 쓴다. 이미 지난 일이므로 접속법 과거(avoir/être의 접속법 + 과거분사): que vous ayez influencé."),
("B2", "avant que + (ne) + 접속법",
 "« avant que l'article ne sorte » « Nous préférons expliquer les faits avant qu'on ne les commente. » avant que 뒤에는 항상 접속법을 쓰고, 문어에서는 부정의 의미가 없는 허사 ne(ne explétif)를 붙이곤 한다. 주어가 같으면 avant de + 부정사: avant de faire tes valises."),
("C1", "조건법 과거로 가정·반사실 말하기",
 "« Si j'avais voulu favoriser mon frère, je m'y serais très mal prise. » « C'est la seule condition que j'aurais posée moi-même. » 과거 사실에 반대되는 가정은 si + 대과거, 주절은 조건법 과거. 두 번째 문장처럼 si절 없이 '(내가 그 입장이었다면) ~했을 것'이라는 뜻으로도 쓴다. se prendre mal = 서툴게 하다(재귀동사이므로 être 조동사, 주어 일치 prise)."),
("B2", "ce n'est pas parce que... que...: 인과 부정",
 "« Ce n'est pas parce qu'une recommandation me dessert qu'elle me disculpe. » « Ce n'est pas parce que Ménard va la poser. » '~라고 해서 ~인 것은 아니다'. 원인과 결과의 연결 자체를 부정하는 논증 구문으로, 토론·해명에서 상대 논리를 끊을 때 유용하다."),
("C1", "명사화와 공식 문체",
 "« la restitution de l'aide » « la réorientation des aides » « la mise en œuvre de la stratégie » « l'absence de conflit d'intérêts avéré » 동사(restituer, réorienter, mettre en œuvre, ne pas exister)를 명사로 바꾸면 성명서·의견서 특유의 객관적이고 압축된 문체가 된다. 구어 « Il n'y a pas eu de conflit » ↔ 문어 « Le comité conclut à l'absence de conflit »."),
("B2", "강조 구문과 c'est... qui로 책임 돌리기",
 "« C'est la phrase qui pose problème, pas le restaurant. » « C'est moi qui écris la lettre. » « C'est mardi matin qui ne passe pas. » 문제·책임의 주체를 정확히 지목할 때 c'est... qui를 쓴다. 대조 요소는 뒤에 pas + 명사로 덧붙인다."),
]

CULTURE = [
("프랑스의 이해충돌 규정과 HATVP",
 "프랑스는 2013년 공직 투명성법(lois relatives à la transparence de la vie publique)을 제정해 이해충돌을 '공적 직무의 독립적·공정·객관적 수행에 영향을 미치거나 미치는 것처럼 보일 수 있는 공적·사적 이해의 간섭 상황'으로 정의했다. 같은 법으로 세워진 독립기관 HATVP(Haute Autorité pour la transparence de la vie publique)는 장관·의원·지방자치단체장 등 고위 공직자의 재산 및 이해관계 신고서를 받아 검토하고 일부를 공개한다. 정의에 '보일 수 있는(paraître)'이 들어 있다는 점이 핵심으로, 실제 영향이 없어도 외관만으로 이해충돌이 성립할 수 있다. 공직자가 자신이 관리하는 사업에서 이익을 취하면 형법상 prise illégale d'intérêts(불법 이익 취득)로 처벌될 수도 있다."),
("기관의 윤리 담당관(déontologue)과 사퇴(déport)",
 "2016년 공무원 윤리법 이후 프랑스의 행정기관·공공기관에는 윤리 담당관(référent déontologue)을 두는 것이 일반화되었다. 이들은 직원과 기관에 이해충돌 여부에 대해 조언한다. 이해충돌 위험이 있을 때 가장 흔한 처방은 해당 인물이 심의·결정에서 스스로 빠지는 déport다. 지방의회에서도 안건과 이해관계가 있는 의원은 토론과 표결에 참여하지 않는 것이 원칙이며, 이를 어기면 의결이 무효가 될 수 있다."),
("언론 윤리: 반론권(contradictoire)과 정정·반론 보도",
 "프랑스 기자들의 직업윤리는 1918년 기자 윤리 헌장과 1971년 뮌헨 선언 등에 근거하며, 비판 기사를 내기 전 당사자에게 해명할 기회를 주는 contradictoire가 중요한 관행으로 여겨진다. 또한 1881년 언론자유법은 기사에서 언급된 사람에게 같은 매체를 통해 반론을 게재할 권리(droit de réponse)를 보장한다. 그래서 위기 커뮤니케이션에서는 기자의 질의에 기한 안에 사실과 자료로 답하는 것이 침묵보다 나은 전략으로 꼽힌다."),
]
