# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, B, S = "Inès", "Mathieu", "Hélène", "Baptiste", "Sofia"
R, PA, AG, K, G = "Rachid", "Ancel", "Agnès", "Kenza", "Gisèle"

META = {
    "part": 3, "ep": 45,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Les trois questions",
    "title_ko": "세 가지 질문",
    "place": "8구 쿠르셀 거리 카페 Le Petit Monceau와 위층 Agora Stratégies 사무실 · 발몽쉬르루아르 옛 방직 공장 « La Navette » · Vasseur & Associés 회의실 « Monceau » / 12월 첫 월요일 ~ 1월 초 ~ 3월 말",
    "chars": "이네스, 마티외, 소피아(Agora 파트너), 라시드(카페 Le Petit Monceau), 폴 앙셀(전국 운동의 대선 후보), 바티스트(앙셀 캠프 컨설턴트), 엘렌 바쇠르, 아녜스 리비에르(발몽쉬르루아르 시장), 켄자 페라(청년 창업가), 지젤(옛 방직 공장 직조공)",
    "work": "앙셀의 독점 계약(18개월, 140만 유로) 거절과 Agora 원칙 유지 · 모든 후보에게 공개하는 « Guide de la campagne loyale »(약속 10개) 설계와 발간 · 발몽 옛 방직 공장의 청년 창업 공간 개관과 리비에르 시장의 중간 성과 보고 · 엘렌의 은퇴 송별회 연설",
    "life": "1화처럼 뒤바뀐 그랑 크렘으로 시작하는 화해, 갈레트 데 루아와 페브, 엘렌이 눈치챈 재킷 주머니 속 반지, 사무실 화이트보드 앞 초록 마커와 청혼",
    "focus": "연설체(삼항 구조·반복법), 양보 구문(quel que soit, que... ou non), 문어 도치(à peine, sans doute, aussi), 명사화, 최상급 뒤 접속법, 조건법 과거로 돌아보는 과거, avant que + ne 허사, 세 가지 질문의 의문문 구조 총정리",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "없음 — 《Conseil de Paris》 완결. 45화의 월요일을 함께해 주셔서 고맙습니다. Que fait-on lundi ? 이제 여러분이 답할 차례입니다.",
}

D = [
# ---------- 1. Ouverture : deux grands crèmes ----------
(None, "Le premier lundi de décembre, 8 h 40. Rue de Courcelles. Le Petit Monceau, juste sous les bureaux d'Agora. Buée sur les vitres. Depuis trois nuits, Inès et Mathieu dorment chacun dans une pièce.",
       "12월 첫 월요일, 오전 8시 40분. 쿠르셀 거리. Agora 사무실 바로 아래층의 르 프티 몽소. 유리창에 김이 서려 있다. 사흘 밤째 이네스와 마티외는 각자 다른 방에서 자고 있다."),
(None, "Inès entre. Sur le comptoir, deux grands crèmes. Au bout du comptoir, Mathieu, en tenue de course, prend l'une des deux tasses.",
       "이네스가 들어온다. 카운터 위에 그랑 크렘 두 잔. 카운터 끝에서 운동복 차림의 마티외가 그중 한 잔을 집어 든다."),
(R, "Salut Inès. Deux grands crèmes, comme d'habitude. Il est là depuis dix minutes, et il n'a rien voulu boire sans toi.", "안녕, 이네스. 늘 마시던 그랑 크렘 두 잔. 저 친구 10분 전부터 와 있었는데, 너 없이는 아무것도 안 마시겠대."),
(I, "Excusez-moi... je crois que vous buvez mon café.", "실례지만... 지금 제 커피를 드시는 것 같은데요."),
(MA, "Votre café ? Ah non, c'est le mien. J'ai commandé un grand crème. ... Tu t'en souviens mot pour mot.", "당신 커피요? 아니에요, 제 거예요. 저 그랑 크렘 시켰거든요. ...너 그걸 토씨 하나 안 틀리고 기억하네."),
(I, "Je me souviens de tout, c'est mon défaut. Par exemple, je me souviens qu'on dort dans deux pièces différentes depuis trois nuits.", "난 다 기억해. 그게 내 결점이야. 예를 들면 우리가 사흘 밤째 다른 방에서 자고 있다는 것도 기억하지."),
(R, "Je vous laisse. Enfin, je reste derrière mon comptoir, mais je n'écoute pas. Comme il y a quatre ans.", "자리 비켜 줄게. 그러니까, 카운터 뒤에 있긴 하겠지만 안 들을게. 4년 전처럼."),
(MA, "Rachid, il y a quatre ans, tu écoutais tout.", "라시드, 4년 전에 너 다 듣고 있었잖아."),
(R, "Il y a quatre ans, vous vous vouvoyiez. J'ai suivi toute l'histoire depuis ce comptoir : ne m'en gâchez pas la fin.", "4년 전엔 둘이 존댓말을 썼지. 난 이 카운터에서 이야기를 처음부터 다 지켜봤어. 결말을 망치지 마."),
(MA, "Inès, je n'ai pas dormi. À cinq heures, je suis monté au bureau et j'ai écrit quelque chose au tableau. On s'était promis de dire les grandes décisions le soir même ; il est neuf heures moins le quart, mais j'en ai une.",
     "이네스, 나 한숨도 못 잤어. 다섯 시에 사무실에 올라가서 화이트보드에 뭘 좀 썼어. 큰 결정은 그날 저녁에 바로 말하기로 약속했잖아. 지금은 아침 9시 15분 전이지만, 결정이 하나 있어."),
(I, "Avant que tu ne parles, lis ça. Je l'ai écrit à trois heures du matin, avec le stylo TM.", "네가 말하기 전에 이것부터 읽어. 새벽 세 시에 TM 만년필로 쓴 거야."),
(MA, "« Non à l'exclusivité. Oui à quelque chose de plus grand. » ... C'est presque ce que j'ai écrit là-haut. J'ai écrit : « Non à Ancel. Oui à tout le monde. »",
     "'독점 계약엔 노. 더 큰 무언가엔 예스.' ...내가 위층에 쓴 거랑 거의 똑같아. 난 이렇게 썼어. '앙셀에겐 노. 모두에게 예스.'"),
(I, "Tu avais raison sur une chose, Mathieu : rester dans notre coin, les mains propres, ça ne change rien. Tu voulais changer une campagne de l'intérieur...",
    "한 가지는 네 말이 맞았어, 마티외. 손 깨끗하게 우리 구석에만 있으면 아무것도 안 바뀌어. 넌 캠페인 하나를 안에서 바꾸고 싶어 했지..."),
(MA, "... et toi, tu avais raison sur l'exclusivité. Alors changeons les règles pour toutes les campagnes, de l'extérieur. Monte, je t'explique au tableau.",
     "...그리고 넌 독점 계약에 대해 옳았어. 그러니까 바깥에서, 모든 캠페인의 규칙을 바꾸자. 올라가자, 화이트보드 앞에서 설명할게."),
(R, "Hé ! Vos grands crèmes ! Vous n'allez pas me refaire le coup de partir sans les boire, quatre ans après ?", "어이! 그랑 크렘! 4년이 지났는데 또 안 마시고 가 버리는 거야?"),
(I, "On les emporte, Rachid. Et cette fois, chacun a le sien.", "가져갈게, 라시드. 그리고 이번엔 각자 자기 걸로."),

# ---------- 2. La réponse à Paul Ancel ----------
(None, "9 h. Au-dessus du café, les bureaux d'Agora Stratégies. Sofia attend, un sachet de croissants à la main, devant le tableau blanc.",
       "오전 9시. 카페 위층 Agora Stratégies 사무실. 소피아가 크루아상 봉지를 들고 화이트보드 앞에서 기다리고 있다."),
(S, "Vous montez ensemble, avec deux cafés ? Ça veut dire que la guerre froide est finie ? Trois jours que je travaille entre deux silences, j'allais demander une prime de risque.",
    "둘이 커피 두 잔 들고 같이 올라오네? 냉전이 끝났다는 뜻이야? 사흘 동안 두 침묵 사이에서 일했어. 위험 수당 달라고 하려던 참이었다고."),
(MA, "Elle est finie. Et on a une décision. Enfin, une décision et demie.", "끝났어. 그리고 결정도 내렸어. 그러니까, 결정 하나 반."),
(S, "« Non à Ancel. Oui à tout le monde. » C'est un slogan ou une stratégie ?", "'앙셀에겐 노. 모두에게 예스.' 이거 슬로건이야, 전략이야?"),
(I, "Les deux, si on le fait bien. Premier point : nous refusons le contrat d'exclusivité de Paul Ancel. Un million quatre cent mille euros d'honoraires sur dix-huit mois, à condition de ne conseiller personne d'autre jusqu'au scrutin.",
    "제대로 하면 둘 다지. 첫째, 폴 앙셀의 독점 계약을 거절해. 18개월에 수임료 140만 유로, 대신 선거 때까지 다른 누구에게도 자문하지 않는다는 조건이지."),
(MA, "C'est presque notre chiffre d'affaires d'une année entière. Et c'est justement le problème : un client qui pèse autant que tous les autres réunis, ce n'est plus un client, c'est un propriétaire.",
     "우리 1년 치 매출과 거의 맞먹어. 그리고 바로 그게 문제야. 다른 고객을 다 합친 만큼 무게가 나가는 고객은 더 이상 고객이 아니라 주인이야."),
(I, "Sans compter leur stratégie de données. Acheter des fichiers d'électeurs, cibler chacun selon ses peurs : c'est exactement ce que nous avons refusé à Valmont.",
    "그들의 데이터 전략은 말할 것도 없고. 유권자 명부를 사들이고, 각자의 두려움에 맞춰 겨냥하는 것. 우리가 발몽에서 거부했던 바로 그거야."),
(S, "D'accord pour le non. Et le « oui à tout le monde » ?", "노는 알겠어. 그럼 '모두에게 예스'는?"),
(MA, "Un guide. Public, gratuit, ouvert à tous les candidats, quel que soit leur camp : comment mener une campagne loyale. Nos principes, nos refus, nos méthodes, tout ce qu'on a appris à Valmont.",
     "가이드야. 공개, 무료, 진영과 상관없이 모든 후보에게 열려 있는 거. 공정한 캠페인을 어떻게 하는가. 우리 원칙, 우리가 거절한 것들, 우리 방법론, 발몽에서 배운 전부."),
(S, "Attends... Tu veux donner gratuitement ce qu'Ancel voulait acheter un million et demi ?", "잠깐... 앙셀이 150만 가까이 주고 사려던 걸 공짜로 주겠다고?"),
(I, "Non. Ancel voulait acheter notre silence auprès des autres. Ce que nous donnons, c'est exactement le contraire.", "아니. 앙셀이 사려던 건 다른 사람들에 대한 우리의 침묵이었어. 우리가 주는 건 정확히 그 반대야."),
(S, "Financièrement, je suis contre. Humainement, j'adore. Il arrive à onze heures, avec Baptiste.", "재무적으론 반대. 인간적으론 너무 좋아. 그 사람 11시에 와, 바티스트랑."),
(None, "11 h. La petite salle de réunion d'Agora. Paul Ancel, manteau sombre, s'assoit sans l'enlever. Baptiste Morel reste debout derrière lui, un dossier sous le bras.",
       "오전 11시. Agora의 작은 회의실. 짙은 색 코트를 입은 폴 앙셀이 코트도 벗지 않고 앉는다. 바티스트 모렐은 서류철을 옆구리에 끼고 그 뒤에 서 있다."),
(PA, "Madame Marchetti, monsieur Kessler. Je vous ai laissé trois jours de réflexion. J'espère que vous m'apportez une signature.", "마르케티 씨, 케슬레르 씨. 사흘 동안 생각할 시간을 드렸습니다. 서명을 가져오셨기를 바랍니다."),
(MA, "Nous vous apportons une réponse, monsieur Ancel, et nous tenions à vous la donner en face : nous n'accepterons pas le contrat d'exclusivité.", "답을 가져왔습니다, 앙셀 씨. 그리고 직접 뵙고 말씀드리고 싶었습니다. 저희는 독점 계약을 받아들이지 않겠습니다."),
(PA, "Puis-je savoir pourquoi ? La semaine dernière, vous m'avez dit vous-même que vous rêviez de changer une campagne de l'intérieur.", "이유를 여쭤봐도 될까요? 지난주에 캠페인 하나를 안에서 바꾸는 게 꿈이라고 직접 말씀하셨잖습니까."),
(MA, "Je l'ai dit, et je le pensais. Mais à la réflexion, si nous devenions vos conseillers exclusifs, ce n'est pas nous qui changerions votre campagne : c'est votre campagne qui nous changerait.",
     "그렇게 말했고, 진심이었습니다. 하지만 곰곰이 생각해 보니, 저희가 후보님의 전속 자문이 된다면 저희가 캠페인을 바꾸는 게 아니라 캠페인이 저희를 바꿀 겁니다."),
(I, "Notre cabinet repose sur trois principes : l'indépendance, la transparence et la vérité. Une exclusivité de dix-huit mois et l'achat de données sur les électeurs, ce serait renoncer aux deux premiers dès le premier jour.",
    "저희 회사는 세 가지 원칙 위에 서 있습니다. 독립성, 투명성, 진실. 18개월 독점 계약과 유권자 데이터 구매는 첫날부터 앞의 두 가지를 포기하는 일입니다."),
(PA, "Vous êtes bien sévères. Tout le monde achète des données. Si je ne le fais pas, mes adversaires le feront.", "꽤 엄격하시군요. 다들 데이터를 삽니다. 내가 안 하면 상대들이 할 겁니다."),
(I, "C'est possible. Mais qu'ils le fassent ou non, nous ne le ferons pas. Et nous sommes convaincus qu'on peut gagner sans le faire.", "그럴 수도 있죠. 하지만 그들이 하든 안 하든 저희는 하지 않겠습니다. 그리고 그러지 않고도 이길 수 있다고 확신합니다."),
(PA, "Convaincus... À Valmont, peut-être. Valmont, c'est soixante-dix mille habitants. Le pays, c'est soixante-huit millions.", "확신이라... 발몽에선 그랬겠죠. 발몽은 인구 7만이고, 이 나라는 6,800만입니다."),
(MA, "À Valmont, notre candidate était à vingt-deux pour cent dans le premier sondage. Pas de fichiers achetés, du porte-à-porte et des chiffres vérifiés. Elle a été élue avec cinquante et un virgule huit.",
     "발몽에서 저희 후보는 첫 여론조사에서 22%였습니다. 사들인 명부 없이, 호별 방문과 검증된 숫자로 했습니다. 그리고 51.8%로 당선됐습니다."),
(B, "Paul, je peux dire quelque chose ?", "폴, 한마디 해도 될까요?"),
(PA, "Vous allez me dire qu'ils ont raison, je suppose.", "저 사람들 말이 맞다고 하려는 거겠죠."),
(B, "Je vais vous redire ce que je vous ai dit en octobre. Si l'on apprend que votre campagne achète des profils d'électeurs, c'est ça qui fera la une, pas votre programme. Et on l'apprendra : ces choses-là finissent toujours par se savoir.",
    "10월에 드린 말씀을 다시 드리려는 겁니다. 후보님 캠페인이 유권자 프로필을 산다는 게 알려지면, 신문 1면에 실리는 건 공약이 아니라 그 얘기일 겁니다. 그리고 알려질 겁니다. 그런 일은 결국 다 드러나게 마련이니까요."),
(PA, "C'est moi qui vous paie, Morel, pas eux.", "당신 월급은 내가 줍니다, 모렐. 저 사람들이 아니라."),
(B, "Justement : vous me payez pour vous dire ce que les autres n'osent pas vous dire. Il fut un temps où j'aurais vendu n'importe quoi à n'importe qui. J'ai appris à mes dépens que ça ne mène nulle part.",
    "바로 그래서죠. 다른 사람들이 감히 못 하는 말을 하라고 저한테 돈을 주시는 겁니다. 저도 한때는 아무에게나 아무거나 팔았을 사람입니다. 그게 아무 데도 이르지 못한다는 걸 대가를 치르고 배웠죠."),
(I, "Monsieur Ancel, nous ne sommes pas venus seulement vous dire non. Nous avons une proposition, et elle ne vous coûtera rien.", "앙셀 씨, 저희는 거절만 하러 온 게 아닙니다. 제안이 하나 있고, 비용은 전혀 들지 않습니다."),
(PA, "Rien ? Voilà qui m'inquiète davantage.", "공짜라고요? 그게 더 불안하군요."),
(MA, "En janvier, nous publierons un guide de la campagne loyale : dix engagements vérifiables sur les données, la vérité des chiffres, le financement et le respect des adversaires. Nous l'enverrons le même jour, avec la même lettre, à tous les candidats. Vous y compris.",
     "1월에 공정한 캠페인 가이드를 발간할 겁니다. 데이터, 숫자의 진실성, 자금, 상대에 대한 존중에 관한 검증 가능한 약속 열 가지입니다. 같은 날, 같은 편지로 모든 후보에게 보낼 겁니다. 후보님도 포함해서요."),
(PA, "Vous refusez de travailler pour moi et vous me demandez de signer votre charte devant tout le monde. Vous ne manquez pas de culot. ... Envoyez-le-moi. Je ne promets rien.",
     "나를 위해 일하는 건 거절하면서 모두가 보는 앞에서 당신들 헌장에 서명하라는 거군요. 배짱 한번 좋네요. ...보내 주세요. 약속은 못 합니다."),

# ---------- 3. Écrire le guide ----------
(None, "Début janvier. Le tableau blanc d'Agora est couvert de flèches vertes et de chiffres bleus. En haut, en lettres capitales : « GUIDE DE LA CAMPAGNE LOYALE — 10 ENGAGEMENTS ».",
       "1월 초. Agora의 화이트보드가 초록 화살표와 파란 숫자로 뒤덮여 있다. 맨 위엔 대문자로 '공정한 캠페인 가이드 — 약속 10가지'."),
(I, "Engagement numéro un : « Ne jamais acheter de données personnelles sur les électeurs. » Comment un candidat prouve-t-il qu'il le respecte ? Un engagement sans indicateur, c'est un vœu pieux.",
    "약속 1번. '유권자 개인 데이터를 절대 구매하지 않는다.' 후보가 이걸 지킨다는 걸 어떻게 증명하지? 지표 없는 약속은 공허한 다짐일 뿐이야."),
(MA, "Et un guide de deux cents pages avec un indicateur à chaque ligne, c'est un presse-papier. Personne ne le lira, surtout pas un candidat à six semaines du scrutin.",
     "그리고 줄마다 지표가 달린 200쪽짜리 가이드는 문진이야. 아무도 안 읽어. 투표 6주 전의 후보는 더더욱."),
(I, "Donc tu préfères des belles phrases que personne ne peut vérifier ?", "그러니까 아무도 검증할 수 없는 멋진 문장이 더 좋다는 거야?"),
(MA, "Je préfère une page que tout le monde comprend. Dix engagements, une phrase chacun, sur une seule page. Ton indicateur, mets-le juste en dessous, en une ligne.",
     "누구나 이해하는 한 페이지가 좋다는 거야. 약속 열 개, 하나에 한 문장, 한 페이지에. 네 지표는 바로 밑에 한 줄로 넣어."),
(I, "Une page pour les engagements, et derrière, soixante pages de méthode pour ceux qui veulent vraiment les appliquer. D'accord. À peine avions-nous commencé que nous étions déjà d'accord : ça doit être un record.",
    "약속은 한 페이지, 그 뒤에 진짜 실천하려는 사람들을 위한 방법론 60쪽. 좋아. 시작하자마자 벌써 합의했네. 신기록이겠다."),
(S, "Je peux jouer les rabat-joie ? Si un seul camp signe, tout le monde dira que notre guide est partisan.", "초 좀 쳐도 돼? 한쪽 진영만 서명하면 다들 우리 가이드가 편파적이라고 할 거야."),
(MA, "C'est pour ça que la méthode d'envoi compte autant que le contenu. Même jour, même heure, même lettre, candidats classés par ordre alphabétique.", "그래서 보내는 방식이 내용만큼 중요한 거야. 같은 날, 같은 시각, 같은 편지, 후보는 가나다순으로."),
(S, "Et ceux qui ne signent pas ? On publie leur nom ?", "서명 안 하는 사람들은? 이름을 공개해?"),
(I, "Non. Nous publions la liste des signataires, point. Nous ne sommes ni juges ni arbitres. Ce n'est pas à nous de distribuer les bons et les mauvais points.", "아니. 서명자 명단만 공개해, 끝. 우린 판사도 심판도 아니야. 잘했다, 못했다 점수를 매기는 건 우리 몫이 아니야."),
(MA, "Sans doute aurais-je voulu, il y a un an, épingler les tricheurs. Mais l'épinglage, c'est déjà de la campagne. Notre rôle, c'est de fixer la barre, pas de juger qui saute.",
     "1년 전이었다면 반칙하는 사람들을 콕 집어내고 싶었을지도 몰라. 하지만 콕 집는 것 자체가 이미 선거운동이야. 우리 역할은 기준을 정하는 거지, 누가 넘는지 판정하는 게 아니야."),
(S, "Alors qui vérifie ? Si personne ne contrôle, le guide ne sert à rien.", "그럼 누가 확인해? 아무도 안 보면 가이드가 무슨 소용이야."),
(I, "Les signataires eux-mêmes. Chaque signataire publie un bilan à la fin de sa campagne : ses dépenses, ses corrections, ses sources. Ce sont les électeurs et les journalistes qui jugeront.",
    "서명자 자신이. 각 서명자가 캠페인이 끝나면 결산을 공개하는 거야. 지출, 정정 내역, 출처. 판단은 유권자와 기자들이 할 거고."),
(MA, "Engagement numéro trois : « Corriger publiquement toute erreur factuelle dans les quarante-huit heures. » Celui-là, je l'aime. Personne n'aime avouer qu'il s'est trompé.",
     "약속 3번. '사실관계 오류는 48시간 안에 공개적으로 정정한다.' 난 이게 좋아. 틀렸다고 인정하는 걸 좋아하는 사람은 아무도 없거든."),
(I, "Toi, en tout cas, tu as mis trois nuits à l'avouer.", "적어도 너는 그걸 인정하는 데 사흘 밤이 걸렸지."),
(MA, "Trois nuits pour une erreur de cette taille, c'est une performance. Mon grand-père aurait mis un trait vert : « pas encore, mais tu vas y arriver ».", "이 정도 크기의 실수에 사흘이면 대단한 기록이야. 할아버지라면 초록 줄을 그어 주셨을 거야. '아직은 아니지만, 해낼 거다.'"),
(S, "Engagement numéro six : « Publication de l'origine de chaque don et de chaque dépense de communication. » C'est déjà en partie la loi, non ?", "약속 6번. '모든 기부금과 모든 홍보 지출의 출처 공개.' 이건 이미 부분적으로 법이잖아?"),
(I, "En partie : les comptes de campagne sont contrôlés après l'élection, et le plafond des dépenses est fixé par la loi. Nous demandons simplement de le faire pendant la campagne, pas six mois après.",
    "부분적으로는. 선거 회계는 선거 후에 감사받고, 지출 상한은 법으로 정해져 있어. 우린 그걸 6개월 뒤가 아니라 캠페인 도중에 하자고 요구하는 것뿐이야."),
(MA, "Et le dernier, le dixième. Je l'ai écrit cette nuit : « Reconnaître le résultat du scrutin, quel qu'il soit, et féliciter le vainqueur. »", "그리고 마지막 열 번째. 어젯밤에 썼어. '결과가 어떻든 선거 결과를 인정하고 승자를 축하한다.'"),
(S, "Celui-là, il est court, mais c'est le plus difficile à tenir.", "그건 짧은데, 지키기는 제일 어렵겠다."),
(I, "C'est le plus important. Sans lui, les neuf autres ne valent rien. On publie le quinze janvier ?", "그게 제일 중요해. 그게 없으면 나머지 아홉 개는 아무 가치도 없어. 1월 15일에 발간할까?"),
(None, "On frappe. Hélène Vasseur entre, une boîte de pâtissier dans les mains.", "노크 소리. 엘렌 바쇠르가 제과점 상자를 들고 들어온다."),
