# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
I, MA, H, B, S = "Inès", "Mathieu", "Hélène", "Baptiste", "Sofia"
R, PA, AG, K, G = "Rachid", "Ancel", "Agnès", "Kenza", "Gisèle"

META = {
    "part": 3, "ep": 45,
    "part_label": "제3부 · 정치 컨설턴트 Stratèges",
    "title_fr": "Les trois questions",
    "title_ko": "세 가지 질문",
    "place": "8구 쿠르셀 거리 카페 Le Petit Monceau와 위층 Agora Stratégies 사무실 · 발몽쉬르루아르 옛 방직 공장 « La Navette » · Vasseur & Associés 회의실 « Monceau » / 44화 다음 월요일(10월 말) ~ 1월 초 주현절 ~ 3월 21일 토요일 ~ 3월 마지막 금요일 밤",
    "chars": "이네스, 마티외, 소피아(Agora 파트너), 라시드(카페 Le Petit Monceau), 폴 앙셀(전국 운동 « Passerelles »의 대선 후보), 바티스트(« Passerelles » 여론조사 책임자), 엘렌 바쇠르, 아녜스 리비에르(발몽쉬르루아르 시장), 켄자 페라(청년 창업가), 지젤(옛 방직 공장 직조공)",
    "work": "앙셀의 독점 계약(7개월 140만 유로 + 선거 후 12개월 독점, 데이터 '부록 3') 거절과 Agora 원칙 유지 · 모든 후보에게 공개하는 « Guide de la campagne loyale »(약속 10개) 설계와 발간 · 발몽 옛 방직 공장의 청년 창업 공간 개관과 리비에르 시장의 중간 성과 보고 · 엘렌의 은퇴 송별회 연설",
    "life": "1화처럼 뒤바뀐 그랑 크렘으로 시작하는 화해, 갈레트 데 루아와 페브, 엘렌이 눈치챈 재킷 주머니 속 반지, 사무실 화이트보드 앞 초록 마커와 청혼",
    "focus": "연설체(삼항 구조·반복법), 양보 구문(quel que soit, que... ou non), 문어 도치(à peine, sans doute, aussi), 명사화, 최상급 뒤 접속법, 조건법 과거로 돌아보는 과거, avant que + ne 허사, 세 가지 질문의 의문문 구조 총정리",
    "levelmix": "B1 5% · B2 50% · C1 45%",
    "next": "없음 — 《Conseil de Paris》 완결. 45화의 월요일을 함께해 주셔서 고맙습니다. Que fait-on lundi ? 이제 여러분이 답할 차례입니다.",
}

D = [
# ---------- 1. Ouverture : deux grands crèmes ----------
(None, "Le lundi suivant, 8 h 40. Le Petit Monceau, juste sous les bureaux d'Agora. Depuis trois nuits, Inès et Mathieu dorment chacun dans une pièce. Ils entrent ensemble, sans un mot. Sur le comptoir, deux grands crèmes ; Mathieu, distrait, prend la tasse la plus proche.",
       "그다음 월요일, 오전 8시 40분. Agora 사무실 바로 아래층의 르 프티 몽소. 사흘 밤째 이네스와 마티외는 각자 다른 방에서 자고 있다. 두 사람이 말없이 함께 들어온다. 카운터 위엔 그랑 크렘 두 잔. 마티외가 멍하니 가까운 잔을 집어 든다."),
(R, "Salut tous les deux. Deux grands crèmes, comme d'habitude. Et la table du fond est libre : vous avez une tête à avoir besoin de la table du fond.", "안녕, 둘 다. 늘 마시던 그랑 크렘 두 잔. 안쪽 테이블 비어 있어. 둘 다 안쪽 테이블이 필요한 얼굴이네."),
(I, "Excusez-moi... je crois que vous buvez mon café.", "실례지만... 지금 제 커피를 드시는 것 같은데요."),
(MA, "Votre café ? Ah non, c'est le mien. J'ai commandé un grand crème. ... Tu t'en souviens mot pour mot.", "당신 커피요? 아니에요, 제 거예요. 저 그랑 크렘 시켰거든요. ...너 그걸 토씨 하나 안 틀리고 기억하네."),
(I, "Je me souviens de tout, c'est mon défaut. Par exemple, je me souviens qu'on dort dans deux pièces différentes depuis trois nuits.", "난 다 기억해. 그게 내 결점이야. 예를 들면 우리가 사흘 밤째 다른 방에서 자고 있다는 것도 기억하지."),
(R, "Je vous laisse. Enfin, je reste derrière mon comptoir, mais je n'écoute pas. Comme il y a quatre ans.", "자리 비켜 줄게. 그러니까, 카운터 뒤에 있긴 하겠지만 안 들을게. 4년 전처럼."),
(MA, "Rachid, il y a quatre ans, tu écoutais tout.", "라시드, 4년 전에 너 다 듣고 있었잖아."),
(R, "Il y a quatre ans, vous vous vouvoyiez. J'ai suivi toute l'histoire depuis ce comptoir : ne m'en gâchez pas la fin.", "4년 전엔 둘이 존댓말을 썼지. 난 이 카운터에서 이야기를 처음부터 다 지켜봤어. 결말을 망치지 마."),
(I, "Il n'y aura pas de mauvaise fin, Rachid. Seulement un mauvais milieu de semaine.", "나쁜 결말은 없을 거야, 라시드. 좀 나빴던 한 주의 중간이 있었을 뿐이지."),
(MA, "Inès, ce matin à six heures, j'ai vu ce que tu as écrit sous la deuxième question : « Nous deux. » Alors, sous la troisième, j'ai écrit quelque chose. On s'était promis de ne rien décider avant ce café. Le voilà, ce café.",
     "이네스, 오늘 아침 여섯 시에 네가 두 번째 질문 아래에 쓴 걸 봤어. '우리 둘.' 그래서 세 번째 질문 아래에 나도 뭘 좀 썼어. 이 커피 전엔 아무것도 결정하지 않기로 약속했잖아. 자, 그 커피야."),
(I, "Avant que tu ne parles, lis ça. Je l'ai écrit cette nuit, avec le stylo TM, pendant que tu dormais assis sur le canapé.", "네가 말하기 전에 이것부터 읽어. 어젯밤 네가 소파에 앉은 채 잠든 동안 TM 만년필로 쓴 거야."),
(MA, "« Non à l'exclusivité. Oui à quelque chose de plus grand. » ... C'est presque ce que j'ai écrit sous la troisième question. J'ai écrit : « Non à Ancel. Oui à tout le monde. »",
     "'독점 계약엔 노. 더 큰 무언가엔 예스.' ...내가 세 번째 질문 아래에 쓴 거랑 거의 똑같아. 난 이렇게 썼어. '앙셀에겐 노. 모두에게 예스.'"),
(I, "Tu avais raison sur une chose, Mathieu : rester dans notre coin, les mains propres, ça ne change rien. Tu voulais changer une campagne de l'intérieur...",
    "한 가지는 네 말이 맞았어, 마티외. 손 깨끗하게 우리 구석에만 있으면 아무것도 안 바뀌어. 넌 캠페인 하나를 안에서 바꾸고 싶어 했지..."),
(MA, "... et toi, tu avais raison sur l'exclusivité. Alors changeons les règles pour toutes les campagnes, de l'extérieur. Monte, je te le réécris au tableau du bureau.",
     "...그리고 넌 독점 계약에 대해 옳았어. 그러니까 바깥에서, 모든 캠페인의 규칙을 바꾸자. 올라가자, 사무실 화이트보드에 다시 써 줄게."),
(R, "Hé ! Vos grands crèmes ! Vous n'allez pas me refaire le coup de partir sans les boire, quatre ans après ?", "어이! 그랑 크렘! 4년이 지났는데 또 안 마시고 가 버리는 거야?"),
(I, "On les emporte, Rachid. Et cette fois, chacun a le sien.", "가져갈게, 라시드. 그리고 이번엔 각자 자기 걸로."),

# ---------- 2. La réponse à Paul Ancel ----------
(None, "9 h. Au-dessus du café, les bureaux d'Agora Stratégies. Sofia attend, un sachet de croissants à la main. Mathieu recopie aussitôt au tableau sa phrase de la nuit.",
       "오전 9시. 카페 위층 Agora Stratégies 사무실. 소피아가 크루아상 봉지를 들고 기다리고 있다. 마티외는 곧바로 간밤에 쓴 문장을 화이트보드에 옮겨 적는다."),
(S, "Vous montez ensemble, avec deux cafés ? Ça veut dire que la guerre froide est finie ? Trois jours que je travaille entre deux silences, j'allais demander une prime de risque.",
    "둘이 커피 두 잔 들고 같이 올라오네? 냉전이 끝났다는 뜻이야? 사흘 동안 두 침묵 사이에서 일했어. 위험 수당 달라고 하려던 참이었다고."),
(MA, "Elle est finie. Et on a une décision. Enfin, une décision et demie.", "끝났어. 그리고 결정도 내렸어. 그러니까, 결정 하나 반."),
(S, "« Non à Ancel. Oui à tout le monde. » C'est un slogan ou une stratégie ?", "'앙셀에겐 노. 모두에게 예스.' 이거 슬로건이야, 전략이야?"),
(I, "Les deux, si on le fait bien. Premier point : nous refusons le contrat d'exclusivité de Paul Ancel. Un million quatre cent mille euros d'honoraires sur sept mois, à condition de ne conseiller aucun autre client politique ou public jusqu'au scrutin, et pendant les douze mois qui suivent.",
    "제대로 하면 둘 다지. 첫째, 폴 앙셀의 독점 계약을 거절해. 7개월에 수임료 140만 유로, 대신 선거 때까지, 그리고 그 뒤 12개월 동안 다른 정치·공공 고객은 아무도 받지 않는다는 조건이지."),
(MA, "C'est plus que tout notre chiffre d'affaires de l'an dernier. Et c'est justement le problème : un client qui pèse autant que tous les autres réunis, ce n'est plus un client, c'est un propriétaire.",
     "작년 우리 매출 전체보다 많아. 그리고 바로 그게 문제야. 다른 고객을 다 합친 만큼 무게가 나가는 고객은 더 이상 고객이 아니라 주인이야."),
(I, "Sans compter leur stratégie de données. Acheter des fichiers d'électeurs, cibler chacun selon ses peurs : c'est exactement ce que nous avons refusé à Valmont.",
    "그들의 데이터 전략은 말할 것도 없고. 유권자 명부를 사들이고, 각자의 두려움에 맞춰 겨냥하는 것. 우리가 발몽에서 거부했던 바로 그거야."),
(S, "D'accord pour le non. Et le « oui à tout le monde » ?", "노는 알겠어. 그럼 '모두에게 예스'는?"),
(MA, "Un guide. Public, gratuit, ouvert à tous les candidats, quel que soit leur camp : comment mener une campagne loyale. Nos principes, nos refus, nos méthodes, tout ce qu'on a appris à Valmont.",
     "가이드야. 공개, 무료, 진영과 상관없이 모든 후보에게 열려 있는 거. 공정한 캠페인을 어떻게 하는가. 우리 원칙, 우리가 거절한 것들, 우리 방법론, 발몽에서 배운 전부."),
(S, "Attends... Tu veux donner gratuitement ce qu'Ancel voulait nous payer un million quatre ?", "잠깐... 앙셀이 140만 유로를 주고 사려던 걸 공짜로 주겠다고?"),
(I, "Non. Ancel voulait acheter notre silence auprès des autres. Ce que nous donnons, c'est exactement le contraire.", "아니. 앙셀이 사려던 건 다른 사람들에 대한 우리의 침묵이었어. 우리가 주는 건 정확히 그 반대야."),
(S, "Financièrement, je suis contre. Humainement, j'adore. Il arrive à onze heures, avec Baptiste.", "재무적으론 반대. 인간적으론 너무 좋아. 그 사람 11시에 와, 바티스트랑."),
(MA, "Alors on fait comme d'habitude : toi, Inès, tu tiens les chiffres ; moi, je tiens les mots. Et devant lui, on parle d'une seule voix.", "그럼 늘 하던 대로 하자. 이네스, 넌 숫자를 맡고 난 말을 맡을게. 그리고 그 사람 앞에선 한목소리로 말하는 거야."),
(None, "11 h. La petite salle de réunion d'Agora. Paul Ancel, manteau sombre, s'assoit sans l'enlever. Baptiste Morel reste debout derrière lui, un dossier sous le bras.",
       "오전 11시. Agora의 작은 회의실. 짙은 색 코트를 입은 폴 앙셀이 코트도 벗지 않고 앉는다. 바티스트 모렐은 서류철을 옆구리에 끼고 그 뒤에 서 있다."),
(PA, "Madame Marchetti, monsieur Kessler. Je vous ai laissé le week-end pour réfléchir. J'espère que vous m'apportez une signature.", "마르케티 씨, 케슬레르 씨. 주말 동안 생각할 시간을 드렸습니다. 서명을 가져오셨기를 바랍니다."),
(MA, "Nous vous apportons une réponse, monsieur Ancel, et nous tenions à vous la donner en face : nous n'accepterons pas le contrat d'exclusivité.", "답을 가져왔습니다, 앙셀 씨. 그리고 직접 뵙고 말씀드리고 싶었습니다. 저희는 독점 계약을 받아들이지 않겠습니다."),
(PA, "Puis-je savoir pourquoi ? La semaine dernière, vous m'avez dit vous-même que vous rêviez de changer une campagne de l'intérieur.", "이유를 여쭤봐도 될까요? 지난주에 캠페인 하나를 안에서 바꾸는 게 꿈이라고 직접 말씀하셨잖습니까."),
(MA, "Je l'ai dit, et je le pensais. Mais à la réflexion, si nous devenions vos conseillers exclusifs, ce n'est pas nous qui changerions votre campagne : c'est votre campagne qui nous changerait.",
     "그렇게 말했고, 진심이었습니다. 하지만 곰곰이 생각해 보니, 저희가 후보님의 전속 자문이 된다면 저희가 캠페인을 바꾸는 게 아니라 캠페인이 저희를 바꿀 겁니다."),
(I, "Notre cabinet repose sur trois principes : l'indépendance, la transparence et la vérité. Une exclusivité jusqu'à un an après le scrutin et l'achat de données sur les électeurs, ce serait renoncer aux deux premiers dès le premier jour.",
    "저희 회사는 세 가지 원칙 위에 서 있습니다. 독립성, 투명성, 진실. 선거 후 1년까지 이어지는 독점 계약과 유권자 데이터 구매는 첫날부터 앞의 두 가지를 포기하는 일입니다."),
(PA, "Vous êtes bien sévères. Tout le monde achète des données. Si je ne le fais pas, mes adversaires le feront.", "꽤 엄격하시군요. 다들 데이터를 삽니다. 내가 안 하면 상대들이 할 겁니다."),
(I, "C'est possible. Mais qu'ils le fassent ou non, nous ne le ferons pas. Et nous sommes convaincus qu'on peut gagner sans le faire.", "그럴 수도 있죠. 하지만 그들이 하든 안 하든 저희는 하지 않겠습니다. 그리고 그러지 않고도 이길 수 있다고 확신합니다."),
(PA, "Convaincus... À Valmont, peut-être. Valmont, c'est soixante-dix mille habitants. Le pays, c'est soixante-huit millions.", "확신이라... 발몽에선 그랬겠죠. 발몽은 인구 7만이고, 이 나라는 6,800만입니다."),
(MA, "À Valmont, notre candidate était à vingt-deux pour cent dans le premier sondage. Pas de fichiers achetés, du porte-à-porte et des chiffres vérifiés. Elle a été élue avec cinquante et un virgule huit.",
     "발몽에서 저희 후보는 첫 여론조사에서 22%였습니다. 사들인 명부 없이, 호별 방문과 검증된 숫자로 했습니다. 그리고 51.8%로 당선됐습니다."),
(B, "Paul, je peux dire quelque chose ?", "폴, 한마디 해도 될까요?"),
(PA, "Vous allez me dire qu'ils ont raison, je suppose.", "저 사람들 말이 맞다고 하려는 거겠죠."),
(B, "Je vais vous redire ce que je vous ai dit la semaine dernière. Si l'on apprend que votre campagne achète des profils d'électeurs, c'est ça qui fera la une, pas votre programme. Et on l'apprendra : ces choses-là finissent toujours par se savoir.",
    "지난주에 드린 말씀을 다시 드리려는 겁니다. 후보님 캠페인이 유권자 프로필을 산다는 게 알려지면, 신문 1면에 실리는 건 공약이 아니라 그 얘기일 겁니다. 그리고 알려질 겁니다. 그런 일은 결국 다 드러나게 마련이니까요."),
(PA, "C'est moi qui vous paie, Morel, pas eux.", "당신 월급은 내가 줍니다, 모렐. 저 사람들이 아니라."),
(B, "Justement : vous me payez pour vous dire ce que les autres n'osent pas vous dire. Il fut un temps où j'aurais vendu n'importe quoi à n'importe qui. J'ai appris à mes dépens que ça ne mène nulle part.",
    "바로 그래서죠. 다른 사람들이 감히 못 하는 말을 하라고 저한테 돈을 주시는 겁니다. 저도 한때는 아무에게나 아무거나 팔았을 사람입니다. 그게 아무 데도 이르지 못한다는 걸 대가를 치르고 배웠죠."),
(I, "Monsieur Ancel, nous ne sommes pas venus seulement vous dire non. Nous avons une proposition, et elle ne vous coûtera rien.", "앙셀 씨, 저희는 거절만 하러 온 게 아닙니다. 제안이 하나 있고, 비용은 전혀 들지 않습니다."),
(PA, "Rien ? Voilà qui m'inquiète davantage.", "공짜라고요? 그게 더 불안하군요."),
(MA, "En janvier, nous publierons un guide de la campagne loyale : dix engagements vérifiables sur les données, la vérité des chiffres, le financement et le respect des adversaires. Nous l'enverrons le même jour, avec la même lettre, à tous les candidats. Vous y compris.",
     "1월에 공정한 캠페인 가이드를 발간할 겁니다. 데이터, 숫자의 진실성, 자금, 상대에 대한 존중에 관한 검증 가능한 약속 열 가지입니다. 같은 날, 같은 편지로 모든 후보에게 보낼 겁니다. 후보님도 포함해서요."),
(PA, "Vous refusez de travailler pour moi et vous me demandez de signer votre charte devant tout le monde. Vous ne manquez pas de culot. ... Envoyez-le-moi. Je ne promets rien.",
     "나를 위해 일하는 건 거절하면서 모두가 보는 앞에서 당신들 헌장에 서명하라는 거군요. 배짱 한번 좋네요. ...보내 주세요. 약속은 못 합니다."),

# ---------- 3. Écrire le guide ----------
(None, "Début janvier. Le tableau blanc d'Agora est couvert de flèches vertes et de chiffres bleus. En haut, en lettres capitales : « GUIDE DE LA CAMPAGNE LOYALE — 10 ENGAGEMENTS ».",
       "1월 초. Agora의 화이트보드가 초록 화살표와 파란 숫자로 뒤덮여 있다. 맨 위엔 대문자로 '공정한 캠페인 가이드 — 약속 10가지'."),
(I, "Engagement numéro un : « Ne jamais acheter de données personnelles sur les électeurs. » Comment un candidat prouve-t-il qu'il le respecte ? Un engagement sans indicateur, c'est un vœu pieux.",
    "약속 1번. '유권자 개인 데이터를 절대 구매하지 않는다.' 후보가 이걸 지킨다는 걸 어떻게 증명하지? 지표 없는 약속은 공허한 다짐일 뿐이야."),
(MA, "Et un guide de deux cents pages avec un indicateur à chaque ligne, c'est un presse-papier. Personne ne le lira, surtout pas un candidat à six semaines du scrutin.",
     "그리고 줄마다 지표가 달린 200쪽짜리 가이드는 문진이야. 아무도 안 읽어. 투표 6주 전의 후보는 더더욱."),
(I, "Donc tu préfères des belles phrases que personne ne peut vérifier ?", "그러니까 아무도 검증할 수 없는 멋진 문장이 더 좋다는 거야?"),
(MA, "Je préfère une page que tout le monde comprend. Dix engagements, une phrase chacun, sur une seule page. Ton indicateur, mets-le juste en dessous, en une ligne.",
     "누구나 이해하는 한 페이지가 좋다는 거야. 약속 열 개, 하나에 한 문장, 한 페이지에. 네 지표는 바로 밑에 한 줄로 넣어."),
(I, "Une page pour les engagements, et derrière, soixante pages de méthode pour ceux qui veulent vraiment les appliquer. D'accord. À peine avions-nous commencé que nous étions déjà d'accord. Ça doit être un record.",
    "약속은 한 페이지, 그 뒤에 진짜 실천하려는 사람들을 위한 방법론 60쪽. 좋아. 시작하자마자 벌써 합의했네. 신기록이겠다."),
(S, "Je peux jouer les rabat-joie ? Si un seul camp signe, tout le monde dira que notre guide est partisan.", "초 좀 쳐도 돼? 한쪽 진영만 서명하면 다들 우리 가이드가 편파적이라고 할 거야."),
(MA, "C'est pour ça que la méthode d'envoi compte autant que le contenu. Même jour, même heure, même lettre, candidats classés par ordre alphabétique.", "그래서 보내는 방식이 내용만큼 중요한 거야. 같은 날, 같은 시각, 같은 편지, 후보는 가나다순으로."),
(S, "Et ceux qui ne signent pas ? On publie leur nom ?", "서명 안 하는 사람들은? 이름을 공개해?"),
(I, "Non. Nous publions la liste des signataires, point. Nous ne sommes ni juges ni arbitres. Ce n'est pas à nous de distribuer les bons et les mauvais points.", "아니. 서명자 명단만 공개해, 끝. 우린 판사도 심판도 아니야. 잘했다, 못했다 점수를 매기는 건 우리 몫이 아니야."),
(MA, "Sans doute aurais-je voulu, il y a un an, épingler les tricheurs. Mais l'épinglage, c'est déjà de la campagne. Notre rôle, c'est de fixer la barre, pas de juger qui saute.",
     "1년 전이었다면 반칙하는 사람들을 콕 집어내고 싶었을지도 몰라. 하지만 콕 집는 것 자체가 이미 선거운동이야. 우리 역할은 기준을 정하는 거지, 누가 넘는지 판정하는 게 아니야."),
(S, "Alors qui vérifie ? Si personne ne contrôle, le guide ne sert à rien.", "그럼 누가 확인해? 아무도 안 보면 가이드가 무슨 소용이야."),
(I, "Les signataires eux-mêmes. Chaque signataire publie un bilan à la fin de sa campagne : ses dépenses, ses corrections, ses sources. Ce sont les électeurs et les journalistes qui jugeront.",
    "서명자 자신이. 각 서명자가 캠페인이 끝나면 결산을 공개하는 거야. 지출, 정정 내역, 출처. 판단은 유권자와 기자들이 할 거고."),
(MA, "Engagement numéro trois : « Corriger publiquement toute erreur factuelle dans les quarante-huit heures. » Celui-là, je l'aime. Personne n'aime avouer qu'il s'est trompé.",
     "약속 3번. '사실관계 오류는 48시간 안에 공개적으로 정정한다.' 난 이게 좋아. 틀렸다고 인정하는 걸 좋아하는 사람은 아무도 없거든."),
(I, "Toi, en tout cas, tu as mis trois nuits à l'avouer.", "적어도 너는 그걸 인정하는 데 사흘 밤이 걸렸지."),
(MA, "Trois nuits pour une erreur de cette taille, c'est une performance. Mon grand-père aurait mis un trait vert : « pas encore, mais tu vas y arriver ».", "이 정도 크기의 실수에 사흘이면 대단한 기록이야. 할아버지라면 초록 줄을 그어 주셨을 거야. '아직은 아니지만, 해낼 거다.'"),
(S, "Engagement numéro six : « Publication de l'origine de chaque don et de chaque dépense de communication. » C'est déjà en partie la loi, non ?", "약속 6번. '모든 기부금과 모든 홍보 지출의 출처 공개.' 이건 이미 부분적으로 법이잖아?"),
(I, "En partie : les comptes de campagne sont contrôlés après l'élection, et le plafond des dépenses est fixé par la loi. Nous demandons simplement de le faire pendant la campagne, pas six mois après.",
    "부분적으로는. 선거 회계는 선거 후에 감사받고, 지출 상한은 법으로 정해져 있어. 우린 그걸 6개월 뒤가 아니라 캠페인 도중에 하자고 요구하는 것뿐이야."),
(MA, "Et le dernier, le dixième. Je l'ai écrit cette nuit : « Reconnaître le résultat du scrutin, quel qu'il soit, et féliciter le vainqueur. »", "그리고 마지막 열 번째. 어젯밤에 썼어. '결과가 어떻든 선거 결과를 인정하고 승자를 축하한다.'"),
(S, "Celui-là, il est court, mais c'est le plus difficile à tenir.", "그건 짧은데, 지키기는 제일 어렵겠다."),
(I, "C'est le plus important. Sans lui, les neuf autres ne valent rien. On publie le quinze janvier ?", "그게 제일 중요해. 그게 없으면 나머지 아홉 개는 아무 가치도 없어. 1월 15일에 발간할까?"),
(H, "On peut entrer ? Bonjour, les stratèges ! C'est l'Épiphanie : j'ai apporté une galette des rois, à la frangipane, évidemment. Sofia, c'est toi la plus jeune. Sous la table, et tu désignes les parts.",
    "들어가도 돼? 안녕, 전략가들! 주현절이라 갈레트 데 루아를 가져왔어. 당연히 프랑지판으로. 소피아, 네가 제일 어리지. 테이블 밑으로 들어가서 누가 어느 조각을 먹을지 정해."),
(S, "Celle-ci pour Hélène, celle-là pour Inès, celle-ci pour moi... et la dernière pour Mathieu.", "이건 엘렌, 저건 이네스, 이건 나... 그리고 마지막은 마티외."),
(None, "Mathieu mord dans sa part, s'arrête, et sort de sa bouche une minuscule fève de porcelaine en forme de cœur.", "마티외가 한 입 베어 물다 멈추더니, 입에서 하트 모양의 아주 작은 도자기 페브를 꺼낸다."),
(MA, "J'ai la fève. Un petit cœur... Sofia, tu as triché.", "페브 나왔다. 작은 하트네... 소피아, 너 반칙했지."),
(H, "Le roi ! Mathieu, tu dois choisir ta reine. Et réfléchis bien : la question est plus sérieuse qu'elle n'en a l'air.", "왕이다! 마티외, 왕비를 골라야지. 잘 생각해. 보기보다 진지한 질문이야."),
(MA, "Je n'ai pas besoin de réfléchir. Pour une fois.", "생각할 필요 없어. 이번만큼은."),
(I, "Je suis la reine depuis le premier jour, Strasbourg. La couronne en carton, c'est une formalité administrative.", "난 첫날부터 여왕이었어, 스트라스부르. 종이 왕관은 행정 절차일 뿐이야."),
(H, "Je ne suis pas venue que pour la galette. Fin mars, je tire ma révérence. Vingt-huit ans à la tête du cabinet, ça suffit. Pot de départ le dernier vendredi du mois, salle Monceau. Vous venez tous les trois : c'est un ordre. Mon dernier.",
    "갈레트 때문에만 온 건 아니야. 3월 말에 나 은퇴해. 회사를 이끈 지 28년, 이만하면 됐어. 그달 마지막 금요일에 몽소 회의실에서 송별회야. 셋 다 와. 명령이야. 내 마지막 명령."),
(I, "Toi, à la retraite ? Je ne t'imagine pas une seule journée sans un dossier sous le bras.", "엘렌이 은퇴를? 서류철 없는 엘렌은 단 하루도 상상이 안 돼."),
(H, "Moi non plus, c'est bien pour ça qu'il faut le faire. Et votre guide... oui, je l'ai lu, Sofia est une tombe qui parle beaucoup. C'est le plus beau travail que vous ayez jamais fait.",
    "나도 상상이 안 돼. 그러니까 해야 하는 거야. 그리고 너희 가이드... 그래, 읽었어. 소피아는 말 많은 무덤이거든. 너희가 해낸 일 중에 제일 훌륭한 작업이야."),
(MA, "Le vingt et un mars, Agnès Rivière inaugure l'ancienne filature à Valmont. Le vendredi suivant, ton pot de départ. Mars va être un grand mois.", "3월 21일엔 아녜스 리비에르가 발몽에서 옛 방직 공장 개관식을 열어. 그다음 금요일엔 엘렌 송별회. 3월은 대단한 달이 되겠어."),

# ---------- 4. Terrain : La Navette ----------
(None, "Le samedi 21 mars, 10 h. Valmont-sur-Loire. L'ancienne filature, au bord du fleuve. Sur la façade de brique, une enseigne neuve : « La Navette — espace de jeunes entreprises ». Un ruban tricolore, une petite foule, un pupitre.",
       "3월 21일 토요일, 오전 10시. 발몽쉬르루아르. 강가의 옛 방직 공장. 벽돌 외벽에 새 간판이 걸려 있다. '라 나베트 — 청년 기업 공간'. 삼색 리본, 작은 인파, 연설대."),
(AG, "Madame Marchetti, monsieur Kessler ! Vous êtes venus. Sans vous, je ne serais pas derrière ce pupitre ce matin, au sens propre comme au figuré.", "마르케티 씨, 케슬레르 씨! 와 주셨군요. 두 분이 아니었으면 오늘 아침 제가 이 연설대 뒤에 서 있지 못했을 거예요. 말 그대로든 비유적으로든요."),
(I, "Madame la Maire, nous n'aurions manqué ça pour rien au monde. La dernière fois que nous sommes entrés ici, il pleuvait à travers le toit.", "시장님, 세상없어도 이건 놓칠 수 없었죠. 저희가 마지막으로 여기 들어왔을 땐 지붕에서 비가 샜었는데요."),
(AG, "Le toit, à lui seul, a coûté un million huit cent mille euros. Rassurez-vous, la région en a payé la moitié, et nous n'avons pas touché à la taxe foncière.", "지붕 하나에만 180만 유로가 들었어요. 걱정 마세요, 절반은 레지옹(광역 지방자치단체)이 냈고, 재산세는 건드리지 않았어요."),
(MA, "Vous tenez vos promesses jusque dans les gouttières.", "약속을 빗물받이까지 지키시네요."),
(AG, "J'ai été à bonne école. Venez, je veux vous présenter quelqu'un avant les discours.", "좋은 선생님들한테 배웠으니까요. 오세요, 연설 전에 소개해 드리고 싶은 사람이 있어요."),
(None, "Dans l'ancienne salle des métiers, une jeune femme en salopette coud à la machine. À côté d'elle, une dame aux cheveux blancs lui montre un geste, lentement.",
       "옛 직기실. 멜빵바지를 입은 젊은 여성이 재봉틀을 돌린다. 그 옆에서 백발의 부인이 천천히 손동작을 보여 준다."),
(K, "Bonjour ! Kenza Ferrat, atelier « Reprise ». On répare et on transforme les vêtements usés au lieu de les jeter. On est six, et en septembre, on sera dix.", "안녕하세요! 켄자 페라, '르프리즈' 공방이에요. 헌 옷을 버리는 대신 수선하고 다시 만들어요. 지금 여섯 명인데 9월엔 열 명이 될 거예요."),
(MA, "« Reprise »... comme repriser une chaussette, ou comme la reprise économique ?", "'르프리즈'라... 양말을 깁는다는 뜻이에요, 경기 회복이라는 뜻이에요?"),
(K, "Les deux ! Et voici Gisèle, notre formatrice. Sans elle, on ne saurait même pas reconnaître une navette.", "둘 다요! 그리고 이분은 우리 강사 지젤이에요. 이분이 없었으면 우린 북(navette)이 뭔지도 몰랐을 거예요."),
(G, "J'ai travaillé trente-quatre ans dans cette salle. Tisserande, dès dix-sept ans. Le jour de la fermeture, j'ai cru que je n'y remettrais jamais les pieds.", "난 이 방에서 34년을 일했어요. 열일곱 살부터 직조공이었죠. 공장이 문 닫던 날, 다시는 여기 발을 들이지 못할 줄 알았어요."),
(I, "Et qu'est-ce que ça vous fait, d'y revenir ?", "다시 오시니 어떠세요?"),
(G, "Ça me fait drôle. Avant, il y avait deux cents métiers à tisser et un bruit à vous rendre sourd. Aujourd'hui, des ordinateurs, des machines à coudre, et des jeunes qui rient. Le bruit a changé, mais la maison est vivante.",
    "기분이 묘해요. 예전엔 직기가 이백 대 있었고 귀가 먹을 만큼 시끄러웠죠. 지금은 컴퓨터, 재봉틀, 그리고 웃는 젊은이들이 있어요. 소리는 바뀌었지만 이 집은 살아 있어요."),
(K, "Gisèle nous apprend des points qu'on n'enseigne plus nulle part. En échange, on lui apprend à vendre en ligne.", "지젤은 이제 어디서도 안 가르치는 바느질법을 가르쳐 주세요. 그 대신 우린 온라인 판매를 가르쳐 드리고요."),
(G, "À soixante-quatorze ans, j'ai une boutique sur Internet. Mon pauvre mari n'en reviendrait pas.", "일흔넷에 인터넷 가게가 생겼다니까요. 돌아가신 우리 남편이 알면 기가 막혀 할 거예요."),
(MA, "Kenza, pourquoi avoir choisi Valmont plutôt que Paris ou Nantes ?", "켄자 씨, 왜 파리나 낭트가 아니라 발몽을 택했어요?"),
(K, "Parce qu'ici, le loyer est six fois moins cher et que la mairie a répondu à mon mail en deux jours. Et parce que je suis née ici : on m'a toujours dit qu'il fallait partir pour réussir. J'avais envie de prouver le contraire.",
    "여기는 임대료가 여섯 배나 싸고, 시청이 제 메일에 이틀 만에 답했거든요. 그리고 여기서 태어났으니까요. 성공하려면 떠나야 한다는 말만 듣고 자랐어요. 그 반대를 증명하고 싶었어요."),
(AG, "Mesdames et messieurs. Pendant un siècle, on a tissé ici du lin et du coton. Pendant quinze ans, on n'y a plus rien tissé du tout. À partir d'aujourd'hui, on y tissera des projets. Je ne vous dirai pas que tout va bien : ce serait faux, et je me suis engagée à ne jamais vous mentir sur les chiffres.",
     "신사 숙녀 여러분. 한 세기 동안 이곳에서는 아마와 면을 짰습니다. 15년 동안은 아무것도 짜지 못했습니다. 오늘부터 이곳에서는 꿈과 계획을 짤 것입니다. 모든 게 잘되고 있다고 말씀드리지는 않겠습니다. 그건 거짓말이고, 저는 숫자에 관해 결코 거짓말하지 않겠다고 약속했으니까요."),
(AG, "Alors voici les chiffres. Le chômage est passé de onze à dix virgule trois pour cent : c'est un début, pas une victoire, et je ne m'en attribue pas le mérite. La dette de la ville est passée de cent vingt à cent quatorze millions, sans hausse de la taxe foncière. Le centre de santé a ouvert en janvier avec quatre médecins. Et ce matin, vingt-huit jeunes entreprises s'installent ici.",
     "그러니 숫자를 말씀드리겠습니다. 실업률은 11%에서 10.3%가 됐습니다. 시작일 뿐 승리가 아니며, 그 공을 제 것으로 돌리지도 않겠습니다. 시 부채는 재산세 인상 없이 1억 2천만 유로에서 1억 1,400만 유로로 줄었습니다. 보건센터는 1월에 의사 네 명과 함께 문을 열었습니다. 그리고 오늘 아침, 스물여덟 개의 청년 기업이 이곳에 입주합니다."),
(AG, "Ce bilan d'étape, je le dois aux agents de la ville, aux élus de la majorité comme de l'opposition, aux habitants qui sont venus nous dire leurs colères. Et à deux personnes venues de Paris, qui m'ont appris à poser trois questions avant de décider quoi que ce soit.",
     "이 중간 성과는 시청 직원들, 여당과 야당 의원 모두, 그리고 찾아와 분노를 털어놓은 주민들 덕분입니다. 그리고 무엇을 결정하든 그 전에 세 가지 질문을 던지라고 가르쳐 준, 파리에서 온 두 분 덕분입니다."),
(None, "Applaudissements. Ruban coupé. Un peu plus tard, Agnès sort de son sac un petit cadre : une fiche cartonnée, trois questions écrites au marqueur vert.",
       "박수. 리본 커팅. 잠시 후 아녜스가 가방에서 작은 액자 하나를 꺼낸다. 초록 마커로 세 가지 질문을 적은 카드 한 장이 들어 있다."),
(AG, "Le soir de mon élection, j'ai recopié vos trois questions sur une fiche. Au marqueur vert, bien sûr : j'en ai acheté une boîte entière. Elle est posée sur mon bureau, à la mairie. Je l'ai apportée pour vous la montrer.",
     "당선된 날 밤에 두 분의 세 가지 질문을 카드에 옮겨 적었어요. 물론 초록 마커로요. 한 상자를 통째로 샀다니까요. 시청 제 책상 위에 두고 있어요. 보여 드리려고 가져왔어요."),
(MA, "Mon grand-père disait : « Quand tu ne sais pas quoi dire, écris une question. » Il aurait été fier de voir ses questions dans un bureau de maire.", "할아버지가 그러셨어요. '무슨 말을 해야 할지 모를 땐 질문을 써라.' 자기 질문이 시장 집무실에 있는 걸 보셨으면 자랑스러워하셨을 거예요."),
(AG, "Chaque lundi matin, je relis la troisième. « Que fait-on lundi ? » C'est la plus redoutable : elle ne laisse aucune excuse.", "매주 월요일 아침 세 번째 질문을 다시 읽어요. '월요일엔 무엇을 하는가?' 그게 제일 무서운 질문이에요. 어떤 핑계도 허락하지 않으니까요."),
(I, "C'est la préférée de Mathieu. Il la pose à tout le monde, même au chat.", "마티외가 제일 좋아하는 질문이에요. 아무한테나 다 물어요. 고양이한테도요."),
(AG, "Et vous deux, alors ? Que faites-vous lundi ?", "그럼 두 분은요? 월요일엔 뭘 하세요?"),
(None, "Mathieu porte machinalement la main à la poche intérieure de sa veste. Inès ne le remarque pas.", "마티외가 무심코 재킷 안주머니에 손을 갖다 댄다. 이네스는 눈치채지 못한다."),
(MA, "Lundi ? ... Lundi, on rentre à Paris. Hélène fête son départ à la fin de la semaine.", "월요일요? ...월요일엔 파리로 돌아가요. 이번 주말에 엘렌 송별회가 있거든요."),
(I, "Tu as hésité, là. Toi qui as toujours une réponse toute prête à la troisième question.", "너 방금 망설였지. 세 번째 질문엔 늘 답이 준비돼 있는 사람이."),

# ---------- 5. Le pot de départ d'Hélène ----------
(None, "Le vendredi suivant, 19 h. Vasseur & Associés, salle Monceau. Champagne, petits fours, une cinquantaine de consultants d'hier et d'aujourd'hui. Sur la table, une pile de guides imprimés.",
       "그다음 금요일 오후 7시. 바쇠르 & 어소시에이츠, 몽소 회의실. 샴페인과 프티푸르, 전·현직 컨설턴트 쉰 명 남짓. 테이블 위엔 인쇄된 가이드가 쌓여 있다."),
(S, "Les chiffres, puisque Inès va les réclamer : cinquante-deux mille téléchargements du guide en dix semaines. Six candidats à l'élection nationale l'ont signé, et plus de deux cent quarante élus locaux, de tous bords.",
    "숫자부터, 어차피 이네스가 물어볼 테니까. 가이드 다운로드 10주 만에 5만 2천 건. 전국 선거 후보 여섯 명이 서명했고, 모든 진영의 지방 선출직이 240명 넘게 서명했어."),
(I, "Six candidats... dont Paul Ancel ?", "후보 여섯 명... 폴 앙셀도?"),
(B, "Dont Paul Ancel. Il a signé le premier, avant même que ses adversaires n'aient ouvert l'enveloppe. Il n'allait pas laisser quelqu'un d'autre passer pour le plus vertueux.",
    "폴 앙셀도. 상대들이 봉투를 열기도 전에 제일 먼저 서명했어. 다른 사람이 제일 도덕적인 사람처럼 보이게 놔둘 사람이 아니거든."),
(MA, "C'est de bonne guerre. Merci, Baptiste. Sans ta franchise, notre lettre aurait fini à la poubelle.", "그건 정당한 수지. 고마워, 바티스트. 네가 솔직하게 말해 주지 않았으면 우리 편지는 쓰레기통에 들어갔을 거야."),
(B, "Je l'en ai sortie deux fois, je te l'avoue. Il y a quatre ans et demi, dans ces murs, je vous appelais « les amoureux des tableurs ». Je ne savais pas à quel point j'avais raison.",
    "솔직히 두 번이나 꺼냈어. 4년 반 전, 바로 이 사무실에서 내가 너희를 '스프레드시트 연인들'이라고 불렀지. 내가 얼마나 정확했는지 그땐 몰랐어."),
(I, "Tu avais raison pour les tableurs. Pour le reste, tu as mis un peu plus longtemps que nous à comprendre.", "스프레드시트는 맞았어. 나머지는 네가 우리보다 이해하는 데 조금 더 오래 걸렸고."),
(H, "Mes amis, je serai brève. Je n'ai jamais su l'être : c'est donc le moment ou jamais d'essayer. Il y a vingt-huit ans, j'ai fondé ce cabinet avec deux convictions. La première : un bon conseil ne se mesure pas au nombre de pages, mais au nombre de décisions qu'il rend possibles. La seconde : on ne peut aider ni une entreprise, ni une ville, ni un pays sans aimer un peu les gens qui les font vivre. Les chiffres disent ce qui se passe ; les gens disent pourquoi.",
    "여러분, 짧게 하겠습니다. 한 번도 짧게 말해 본 적이 없으니, 시도해 볼 기회는 지금뿐이죠. 28년 전 저는 두 가지 신념으로 이 회사를 세웠습니다. 첫째, 좋은 조언은 페이지 수가 아니라 그것이 가능하게 하는 결정의 수로 평가된다. 둘째, 기업이든 도시든 나라든, 그것을 살아 움직이게 하는 사람들을 조금이라도 사랑하지 않고는 도울 수 없다. 숫자는 무슨 일이 일어나는지 말해 주고, 사람은 왜 그런지 말해 줍니다."),
(H, "On m'a souvent demandé quel avait été mon plus beau dossier. J'ai longtemps hésité entre un laboratoire, un palace et un journal. Ce soir, je peux le dire : ce n'était pas un dossier. C'était un binôme.",
    "제 최고의 프로젝트가 뭐였냐는 질문을 자주 받았습니다. 오랫동안 제약회사, 팔라스 호텔, 신문사 사이에서 망설였죠. 오늘 밤엔 말할 수 있습니다. 그건 프로젝트가 아니었습니다. 한 팀이었습니다."),
(H, "Un matin de septembre, j'ai mis dans la même salle une Marseillaise qui ne lâchait rien et un Alsacien qui doutait de tout. Je me suis dit : ou bien ils s'entretuent en trois semaines, ou bien ils iront très loin. Ils sont allés plus loin que moi.",
    "9월의 어느 아침, 저는 한 치도 물러서지 않는 마르세유 여자와 모든 걸 의심하는 알자스 남자를 한 방에 넣었습니다. 생각했죠. 3주 안에 서로 죽이든가, 아주 멀리 가든가. 그들은 저보다 더 멀리 갔습니다."),
(H, "Je tire donc ma révérence, et je passe le flambeau à mes associés, qui le porteront mieux que moi. À vous tous, merci. Et à ces deux-là : que votre guide soit lu, que vos clients vous écoutent, et que vous ne vous disputiez jamais après minuit.",
    "그러니 이제 물러나며, 저보다 더 잘해 낼 제 파트너들에게 횃불을 넘깁니다. 여러분 모두 고맙습니다. 그리고 저 두 사람에게. 당신들의 가이드가 읽히기를, 고객들이 당신들 말에 귀 기울이기를, 그리고 자정 넘어서는 절대 싸우지 않기를."),
(I, "Elle va me faire pleurer devant cinquante consultants. Je ne le lui pardonnerai jamais.", "쉰 명이나 되는 컨설턴트 앞에서 날 울리려나 봐. 절대 용서 안 할 거야."),
(S, "Un discours ! Agora, un discours !", "연설! 아고라, 연설!"),
(I, "Hélène, tu nous as appris à compter... et surtout à compter sur les autres. Tu m'as même appris à déléguer, ce qui, tout le monde ici le sait, relevait du miracle.", "엘렌, 당신은 우리에게 셈하는 법을... 그리고 무엇보다 남을 믿고 기대는 법을 가르쳐 줬어. 나한테 위임하는 법까지 가르쳤지. 여기 모두 알다시피, 그건 기적에 가까운 일이었어."),
(MA, "Et à moi, tu as appris à trancher. Le premier jour, tu m'as dit : « Ici, on se tutoie, on n'a pas le temps pour les vous. » Ce jour-là, j'ai compris que je n'avais plus le temps d'hésiter non plus.",
     "그리고 나한텐 결단하는 법을 가르쳐 줬어. 첫날 이렇게 말했지. '여기선 말 놓는 거야, vous 할 시간 없어.' 그날 난 이제 망설일 시간도 없다는 걸 깨달았어."),
(I, "Alors, à Hélène : à celle qui a vu avant nous ce que nous ne voyions pas encore.", "그럼, 엘렌을 위하여. 우리가 아직 보지 못한 걸 우리보다 먼저 본 사람을 위하여."),
(None, "Tous lèvent leur verre : « À Hélène ! » Plus tard, sur le balcon qui domine le parc Monceau, Hélène rejoint Mathieu, seul.", "모두 잔을 든다. '엘렌을 위하여!' 잠시 후, 몽소 공원이 내려다보이는 발코니. 엘렌이 혼자 있는 마티외에게 다가간다."),
(H, "Tu as touché la poche intérieure de ta veste onze fois depuis le début de la soirée. Je les ai comptées. Déformation professionnelle.", "저녁 내내 재킷 안주머니를 열한 번 만졌어. 세어 봤지. 직업병이야."),
(MA, "Tu as toujours tout vu avant tout le monde.", "엘렌은 늘 누구보다 먼저 다 봤지."),
(H, "J'ai des yeux, je te l'ai déjà dit. Montre-moi.", "나도 눈이 있다고 전에 말했잖아. 보여 줘."),
(MA, "Regarde. C'est la bague de Mamie Odile. Mon grand-père la lui a offerte en 1962. Elle me l'a envoyée la semaine dernière, en recommandé, avec un mot : « Il était temps. »",
     "봐. 오딜 할머니 반지야. 할아버지가 1962년에 할머니께 준 거래. 지난주에 등기로 보내셨어. 쪽지 한 장이랑. '때가 됐다.'"),
(H, "Une émeraude. Verte, évidemment. Dans ta famille, on a de la suite dans les idées.", "에메랄드네. 당연히 초록이고. 너희 집안은 참 일관성이 있어."),
(MA, "Je la porte sur moi depuis neuf jours. À Valmont, j'ai failli... et puis je me suis dit que ce n'était pas le bon moment. Je voudrais que tout soit parfait.", "아흐레째 갖고 다녀. 발몽에서 하마터면... 그러다 지금은 때가 아니라고 생각했어. 모든 게 완벽했으면 해서."),
(H, "Mathieu. Ton seul défaut, depuis le premier jour : tu attends que le moment soit parfait pour décider. Le moment parfait n'existe pas. Il n'y a que le moment où l'on se décide.",
    "마티외. 첫날부터 네 유일한 결점이 그거야. 결정하려고 완벽한 순간을 기다리는 거. 완벽한 순간 같은 건 없어. 마음먹는 순간이 있을 뿐이야."),
(MA, "Tu parles comme la troisième question de mon grand-père.", "꼭 할아버지의 세 번째 질문처럼 말하네."),
(H, "Ton grand-père et moi, nous aurions fait un excellent binôme. Ne remets pas à lundi ce que tu peux demander ce soir.", "네 할아버지와 나라면 훌륭한 팀이 됐을 거야. 오늘 밤 물어볼 수 있는 걸 월요일로 미루지 마."),
(None, "Inès apparaît à la porte-fenêtre. Mathieu glisse l'écrin dans sa poche.", "이네스가 발코니 문가에 나타난다. 마티외가 상자를 주머니에 쓱 넣는다."),
(I, "Qu'est-ce que vous complotez, tous les deux ? Hélène, tu as ta tête des jours où tu sais quelque chose que personne ne sait.", "둘이 무슨 음모를 꾸미는 거야? 엘렌, 아무도 모르는 걸 혼자 알고 있는 날의 그 표정이네."),
(H, "Moi ? Je suis à la retraite depuis une heure, ma chérie. Je ne sais plus rien. Je donnais un dernier conseil, gratuit, ce qui est très mauvais pour les affaires.", "내가? 난 한 시간 전부터 은퇴한 몸이야, 얘. 이제 아무것도 몰라. 마지막 조언을 하나 했을 뿐이야. 공짜로. 장사에는 아주 안 좋은 일이지."),
(I, "Les conseils gratuits, c'est notre spécialité, maintenant. Demande à Sofia : financièrement, elle est contre.", "공짜 조언은 이제 우리 전문이야. 소피아한테 물어봐. 재무적으론 반대래."),
(MA, "Il est presque onze heures. J'ai... j'ai oublié un dossier au bureau. On passe par la rue de Courcelles avant de rentrer ?", "벌써 11시가 다 됐네. 나... 사무실에 서류를 두고 왔어. 집에 가기 전에 쿠르셀 거리에 들를까?"),
(I, "Un dossier, un vendredi soir, après le champagne ? Ma parole, tu deviens moi.", "금요일 밤에, 샴페인 마시고, 서류를? 세상에, 너 나처럼 돼 가는구나."),
(None, "En l'embrassant pour lui dire au revoir, Hélène glisse quelques mots à l'oreille de Mathieu.", "작별 인사로 볼을 맞대며 엘렌이 마티외의 귀에 몇 마디를 속삭인다."),
(H, "Pas lundi, Mathieu. Ce soir.", "월요일 말고, 마티외. 오늘 밤."),

# ---------- 6. Le tableau blanc ----------
(None, "23 h. Rue de Courcelles. Le Petit Monceau baisse son rideau ; derrière la vitre, Rachid empile les chaises. Au premier étage, Mathieu allume la lumière du bureau.",
       "밤 11시. 쿠르셀 거리. 르 프티 몽소가 셔터를 내린다. 유리창 너머로 라시드가 의자를 쌓고 있다. 2층에서 마티외가 사무실 불을 켠다."),
(I, "Alors, ce fameux dossier ?", "그래서, 그 문제의 서류는?"),
(MA, "Il n'y a pas de dossier. Assieds-toi, s'il te plaît. Là, devant le tableau.", "서류 같은 건 없어. 앉아 줘. 거기, 화이트보드 앞에."),
(I, "Tu me fais peur. La dernière fois que tu as sorti ce marqueur dans un moment pareil, c'était dans un train, et on a créé une entreprise.", "무섭게 왜 그래. 지난번에 이런 순간에 그 마커를 꺼냈을 땐 기차 안이었고, 우린 회사를 차렸지."),
(None, "Mathieu efface le tableau. Il débouche le vieux marqueur vert de son grand-père et écrit, en haut : « Quel est le vrai problème ? »", "마티외가 화이트보드를 지운다. 할아버지의 낡은 초록 마커 뚜껑을 열고 맨 위에 쓴다. '진짜 문제는 무엇인가?'"),
(MA, "Quatre ans et demi que je te pose ces trois questions. Ce soir, c'est la dernière fois... sous cette forme-là. Première question : quel est le vrai problème ?", "4년 반 동안 너한테 이 세 가지 질문을 던졌어. 오늘 밤이 마지막이야... 이런 식으로는. 첫 번째 질문. 진짜 문제는 무엇인가?"),
(I, "Le vrai problème ? On en a eu des dizaines. Les stocks de Fauvel, le beurre des Lebrun, la dette de Verdier, les rumeurs de Valmont...", "진짜 문제? 수십 개는 있었지. 포벨의 재고, 르브룅의 버터, 베르디에의 부채, 발몽의 소문..."),
(MA, "Non. Le vrai problème, je l'ai cherché pendant trois nuits, en octobre, dans une pièce sans toi. Et je l'ai trouvé. « Je ne peux pas vivre sans toi. »", "아니. 진짜 문제는 10월에 사흘 밤 동안 너 없는 방에서 찾았어. 그리고 찾아냈어. '나는 너 없이 살 수 없다.'"),
(I, "... Mathieu.", "...마티외."),
(MA, "Pendant ces trois nuits, j'ai cru que je défendais une idée. En réalité, je défendais ma peur d'avoir tort devant toi. Et j'ai compris que je préférais avoir tort avec toi qu'avoir raison sans toi.",
     "그 사흘 밤 동안 난 내가 어떤 생각을 지키고 있다고 믿었어. 사실은 네 앞에서 틀리는 게 두려웠던 거야. 그리고 깨달았어. 너 없이 옳은 것보다 너와 함께 틀리는 게 낫다는 걸."),
(MA, "Deuxième question. Qui décide ? ... « Toi. »", "두 번째 질문. 누가 결정하는가? ...'너.'"),
(I, "Moi ? Depuis quand est-ce que tu me laisses décider ?", "내가? 언제부터 나한테 결정을 맡겼는데?"),
(MA, "Depuis le premier jour, à vrai dire. C'est toi qui as décidé que je te devais un café. C'est toi qui as décidé quand il fallait attendre, et quand il fallait se dire « je t'aime ». Moi, j'ai seulement suivi la bonne personne.",
     "사실 첫날부터야. 내가 커피 한 잔 빚졌다고 정한 것도 너였고, 언제 기다려야 하고 언제 '사랑해'라고 말해야 하는지 정한 것도 너였어. 난 그저 맞는 사람을 따라갔을 뿐이야."),
(I, "Tu es en train de me dire que tu m'as laissée gagner pendant quatre ans et demi ?", "지금 4년 반 동안 나한테 져 줬다는 얘기를 하는 거야?"),
(MA, "Je suis en train de te dire que je n'ai jamais voulu gagner contre toi.", "너를 상대로 이기고 싶었던 적은 한 번도 없었다는 얘기를 하는 거야."),
(None, "Il écrit la troisième question et, juste en dessous, trois mots suivis d'un point d'interrogation. Puis il pose un genou à terre et sort l'écrin de sa poche.", "그가 세 번째 질문을 쓰고, 바로 아래에 물음표가 붙은 짧은 한 줄을 쓴다. 그리고 한쪽 무릎을 꿇고 주머니에서 반지 상자를 꺼낸다."),
(MA, "Troisième question. Ta préférée, parce qu'elle est concrète. Que fait-on lundi ?", "세 번째 질문. 네가 제일 좋아하는 거지, 구체적이니까. 월요일엔 무엇을 하는가?"),
(MA, "On se marie ? ... C'est la bague de ma grand-mère. Elle dit qu'il était temps. Hélène dit que le moment parfait n'existe pas. Et moi, je ne veux plus attendre le lundi d'après.",
     "우리 결혼할까? ...우리 할머니 반지야. 할머니는 때가 됐다고 하셔. 엘렌은 완벽한 순간 같은 건 없다고 하고. 그리고 난 더는 다음 월요일을 기다리고 싶지 않아."),
(I, "Il t'a fallu quatre ans et demi, deux entreprises, une ville et une galette des rois pour en arriver là.", "여기까지 오는 데 4년 반, 회사 두 개, 도시 하나, 그리고 갈레트 데 루아 하나가 걸렸네."),
(MA, "Je suis alsacien : on prend le temps de bien faire les choses.", "난 알자스 사람이잖아. 일을 제대로 하려면 시간이 걸려."),
(None, "Inès sort de son sac un autre marqueur vert, celui que Mamie Odile lui a donné à Colmar. Elle se lève et, sous « On se marie ? », trace un long trait vert.",
       "이네스가 가방에서 또 다른 초록 마커를 꺼낸다. 콜마르에서 오딜 할머니가 준 마커다. 그녀는 일어나 '우리 결혼할까?' 아래에 길게 초록 줄을 긋는다."),
(I, "Un trait vert. Tu sais ce que ça veut dire, chez les Kessler : « Pas encore, mais tu vas y arriver. » ... Tu y es arrivé.", "초록 줄. 케슬레르 집안에서 이게 무슨 뜻인지 알지. '아직은 아니지만, 해낼 거다.' ...넌 해냈어."),
(MA, "Inès... c'est un oui ?", "이네스... 그거 예스야?"),
(I, "Oui, Strasbourg.", "응, 스트라스부르."),
(None, "Elle lui tend la main ; il y glisse la bague. En bas, Rachid a vu la lumière s'allumer au premier étage. Il remonte l'escalier, deux grands crèmes à la main.",
       "그녀가 손을 내밀고, 그가 반지를 끼워 준다. 아래층에서 라시드가 2층에 불이 켜진 것을 보았다. 그가 그랑 크렘 두 잔을 들고 계단을 올라온다."),
]

VOCAB = [
("B2", "un contrat d'exclusivité", "독점 계약", "다른 고객(후보)을 받지 않는 조건의 계약. une clause d'exclusivité = 독점 조항."),
("B2", "les honoraires (m. pl.)", "(전문직의) 보수, 수임료", "컨설턴트·변호사·의사의 보수는 salaire가 아니라 honoraires. 항상 복수."),
("C1", "un fichier (d'électeurs) / ficher qn", "(유권자) 명부·데이터베이스 / 신상을 파일로 관리하다", "ficher qn은 '몰래 신상을 기록하다'는 부정적 뉘앙스. 개인정보 논쟁의 핵심 어휘."),
("C1", "quel que soit leur camp / de tous bords", "진영과 상관없이 / 모든 진영의", "quel que soit + 명사(성·수 일치: quelle que soit la décision). bord = 정치적 진영."),
("C1", "un vœu pieux", "공허한 다짐, 실현될 리 없는 바람", "직역 '경건한 소원'. Un engagement sans indicateur, c'est un vœu pieux."),
("B2", "un presse-papier(s)", "문진(서진)", "아무도 안 읽는 두꺼운 보고서를 비꼴 때. 컴퓨터의 '클립보드'도 presse-papiers."),
("B2", "jouer les rabat-joie", "초를 치다, 흥을 깨다", "rabat-joie = 남의 흥을 깨는 사람(불변). Je peux jouer les rabat-joie ?"),
("C1", "épingler qn", "(잘못을) 콕 집어 지적하다, 공개 비판하다", "원뜻 '핀으로 꽂다'. 언론에서 자주: Le rapport épingle la gestion de la ville."),
("B2", "fixer la barre (haut)", "기준을 정하다(높게 잡다)", "높이뛰기 막대에서. placer la barre haut, mettre la barre trop haut."),
("C1", "les comptes de campagne / le plafond des dépenses", "선거 회계 / 선거 비용 상한", "후보는 법정 상한 안에서 지출하고 회계를 제출해 검증받아야 한다(문화 메모 참조)."),
("B2", "ne pas manquer de culot", "배짱이 좋다, 뻔뻔하다", "culot = 대담함·뻔뻔함. Quel culot ! 문맥에 따라 칭찬도 비난도 된다."),
("B2", "finir par se savoir", "결국 알려지다", "finir par + 부정사 = 결국 ~하게 되다. Ces choses-là finissent toujours par se savoir."),
("C1", "à ses dépens", "자기 비용(손해)으로, 대가를 치르고", "apprendre à ses dépens = 쓴맛을 보고 배우다. rire aux dépens de qn = 누구를 놀려 먹다."),
("C1", "C'est de bonne guerre.", "그건 정당한 수다, 그럴 만하다", "상대의 수가 얄밉지만 규칙 안에서 공정할 때 인정하는 표현."),
("B1", "la galette des rois / la fève / tirer les rois", "갈레트 데 루아 / 페브(작은 도자기 인형) / 왕 뽑기를 하다", "1월 공현절 풍습. 페브가 나온 사람이 왕(왕비)이 되어 종이 왕관을 쓴다."),
("B2", "tirer sa révérence", "물러나다, 은퇴하다, 작별하다", "직역 '절을 하고 퇴장하다'. 은퇴·사임 연설의 단골 표현."),
("B2", "passer le flambeau (à qn)", "(후임에게) 횃불을 넘기다, 바통을 넘기다", "passer la main(30화)보다 엄숙하고 연설에 어울린다."),
("B1", "un pot de départ", "송별회", "회사에서 퇴직·이직하는 사람이 여는 간단한 술자리. pot = 한잔하는 모임."),
("B2", "une filature / un métier à tisser / une navette", "방적·방직 공장 / 직기 / (베틀의) 북", "navette는 '셔틀버스', 국회의 법안 왕복(navette parlementaire)에도 쓰인다."),
("B2", "repriser / une reprise", "(옷·양말을) 깁다 / 기운 자리, 회복, 재개", "la reprise économique(경기 회복), la reprise d'une entreprise(기업 인수)와 동형이의어."),
("C1", "s'attribuer le mérite de qc", "~의 공을 자기 것으로 돌리다", "정치 연설의 겸손 표현: je ne m'en attribue pas le mérite."),
("B2", "un bilan d'étape", "중간 결산, 중간 성과 보고", "임기 도중의 점검. bilan de mi-mandat(임기 중반 결산)도 쓴다."),
("B2", "avoir de la suite dans les idées", "한번 정한 생각을 끝까지 밀고 나가다, 일관성이 있다", "칭찬이나 가벼운 놀림 둘 다 가능."),
("B2", "en recommandé (avec accusé de réception)", "등기로 (배달 증명 포함)", "lettre recommandée avec AR = LRAR. 계약 해지·공식 통지의 표준 방식."),
("B1", "se marier (avec qn) / On se marie ?", "(~와) 결혼하다 / 우리 결혼할까?", "épouser qn(타동사)과 구분. demander qn en mariage = 청혼하다, la bague de fiançailles = 약혼반지."),
]

GRAM = [
("C1", "연설체: 삼항 구조·대구·반복법",
 "엘렌과 아녜스의 연설은 프랑스 연설문의 기본 장치를 보여 준다. ① 삼항 구조: « Nos principes, nos refus, nos méthodes », « que votre guide soit lu, que vos clients vous écoutent, et que vous ne vous disputiez jamais après minuit ». ② 시간축 반복(anaphore): « Pendant un siècle, on a tissé ici du lin et du coton. Pendant quinze ans, on n'y a plus rien tissé du tout. À partir d'aujourd'hui, on y tissera des projets. »(과거→부정→미래). ③ 대구(antithèse): « Les chiffres disent ce qui se passe ; les gens disent pourquoi. » 마지막 축원의 que + 접속법은 독립절에서 바람을 나타낸다(Que la fête commence !)."),
("C1", "양보 구문: quel que soit / que... ou non / quoi que",
 "« ouvert à tous les candidats, quel que soit leur camp » « Reconnaître le résultat du scrutin, quel qu'il soit » — quel que + être(접속법) + 주어, quel은 주어에 성·수 일치(quelle que soit l'issue). « qu'ils le fassent ou non, nous ne le ferons pas » — que + 접속법 + ou non = '~하든 안 하든'. « avant de décider quoi que ce soit » — quoi que ce soit = 무엇이든(부정·조건 문맥). 한 단어 quoique(비록 ~지만)와 혼동하지 말 것."),
("C1", "문어 도치: à peine, sans doute / Puis-je ? / Il fut un temps où",
 "« À peine avions-nous commencé que nous étions déjà d'accord. » « Sans doute aurais-je voulu, il y a un an, épingler les tricheurs. » à peine, sans doute, aussi(그러므로), peut-être가 문두에 오면 주어-동사 도치가 격식체의 규칙이다(구어: Sans doute que j'aurais voulu...). « Puis-je savoir pourquoi ? » — je 도치에서는 peux 대신 puis를 쓴다. 바티스트의 « Il fut un temps où j'aurais vendu n'importe quoi » 는 단순과거(fut)를 관용적으로 쓴 문어 표현."),
("C1", "명사화: 행동을 명사로 압축하기",
 "헌장·법률·슬로건은 동사보다 명사를 선호한다. « Non à l'exclusivité. » « l'achat de données sur les électeurs »(= acheter des données) « Publication de l'origine de chaque don et de chaque dépense de communication »(= publier l'origine...). 명사화하면 주어와 시제가 사라져 원칙처럼 들린다. 반대로 마티외의 열 번째 약속 « Reconnaître le résultat du scrutin, quel qu'il soit, et féliciter le vainqueur »는 부정사형으로, 행동을 지시하는 느낌이 더 강하다. 같은 문서 안에서 한 형식으로 통일하는 것이 좋은 문체다."),
("C1", "최상급·감정·기다림 뒤의 접속법",
 "« C'est le plus beau travail que vous ayez jamais fait. » 최상급(le plus, le seul, le premier)이 이끄는 관계절은 주관적 판단이므로 접속법(ayez fait, 접속법 과거)을 쓴다. 사실 확인이면 직설법도 가능: C'est le plus long discours qu'elle a fait. 또한 « Je voudrais que tout soit parfait. » « tu attends que le moment soit parfait » — vouloir que, attendre que 뒤에도 접속법."),
("B2", "sans + 명사 = 숨은 조건절, 조건법 과거로 돌아보기",
 "« Sans vous, je ne serais pas derrière ce pupitre ce matin »(= Si vous n'aviez pas été là... 결과는 현재 → 조건법 현재) « Sans ta franchise, notre lettre aurait fini à la poubelle. »(결과도 과거 → 조건법 과거) « Mon grand-père aurait mis un trait vert » « Ton grand-père et moi, nous aurions fait un excellent binôme. » « Mon pauvre mari n'en reviendrait pas. » — 실현되지 않은 과거·상상을 말할 때 조건법이 핵심이다."),
("B2", "avant que + (ne 허사) + 접속법 / avant de + 부정사",
 "« Avant que tu ne parles, lis ça. » « Il a signé le premier, avant même que ses adversaires n'aient ouvert l'enveloppe. » avant que 뒤에는 접속법(완료면 접속법 과거 aient ouvert)을 쓰고, 격식체에서는 부정의 뜻이 없는 ne(ne explétif, 1화 복습)를 덧붙인다. 두 절의 주어가 같으면 avant de + 부정사: « avant de décider quoi que ce soit »."),
("B2", "총정리: 세 가지 질문의 의문문 구조",
 "« Quel est le vrai problème ? » — 의문형용사 quel + être + 명사 주어(도치). « Qui décide ? » — qui가 주어이므로 도치 없음. « Que fait-on lundi ? » — que가 목적어이므로 동사-주어 도치가 필수, 발음을 위해 -t- 없이 fait-on(모음 충돌 없음; 비교: Que pense-t-on ?). 구어로는 On fait quoi lundi ? / Qu'est-ce qu'on fait lundi ? 마지막 « On se marie ? »는 평서문 + 올림 억양만으로 만든 가장 구어적인 의문문 — 45화의 마지막 질문이 가장 단순한 문장이라는 점이 이 시리즈의 수미상관이다."),
]

CULTURE = [
("프랑스의 선거 자금 규제와 '공정한 캠페인'",
 "프랑스에서는 선거마다 법으로 정한 선거 비용 상한(plafond des dépenses)이 있고, 후보는 선거 회계(compte de campagne)를 제출해 독립 기관인 국가선거회계·정치자금위원회(CNCCFP)의 검증을 받는다. 1995년부터 법인(기업·단체)의 정치 기부는 금지되었고, 개인 기부에도 상한이 있다. 선거 전 일정 기간에는 언론·방송을 통한 유료 정치 광고가 금지되며, 투표 전날 0시부터는 선거운동 자체가 끝난다. 유권자 개인정보를 이용한 정치 홍보는 RGPD와 CNIL의 지침을 따라야 한다. 에피소드 속 '공정한 캠페인 가이드'는 이런 법적 최소 기준 위에 자발적 약속을 더하는 시민 헌장 형식이다."),
("갈레트 데 루아와 주현절",
 "1월 6일 주현절(Épiphanie, 동방박사의 방문)을 전후해 프랑스에서는 갈레트 데 루아를 나눠 먹는다. 북부와 파리에서는 아몬드 크림(frangipane)을 넣은 파이, 남부(프로방스 등)에서는 과일 설탕 절임을 올린 왕관 모양 브리오슈(gâteau des rois)가 흔하다. 가장 어린 사람이 테이블 밑에 들어가 조각마다 누구 몫인지 정하는 것이 전통이며, 페브(fève)가 든 조각을 받은 사람이 종이 왕관을 쓰고 왕(왕비)을 고른다. 1월 내내 회사·학교에서도 흔히 하는 행사다."),
("프랑스의 청혼과 결혼: 시청의 민사혼",
 "프랑스에서 법적 효력이 있는 결혼은 시청에서 하는 민사혼(mariage civil)뿐이다. 시장이나 부시장(adjoint) 등이 주례를 맡고, 증인 2~4명이 필요하며, 결혼 전에 시청에 결혼 공고(publication des bans)를 10일간 게시한다. 종교 예식은 원하면 민사혼 뒤에 따로 올린다(그 전에 올리는 것은 금지). 1999년에 도입된 PACS(시민연대계약)도 동거 커플의 대안으로 널리 쓰인다. 약혼반지(bague de fiançailles)를 가족 대대로 물려주는 전통도 흔하다."),
]
