# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, R = "Hélène", "Julien", "Chloé", "M. Roussel"
D = [
(None, "Vendredi 17 avril, 11 h 30. Le lendemain de la soirée de la table quatre. Julien et Chloé poussent des tables ; Hélène écrit la formule sur l'ardoise.",
 "4월 17일 금요일 오전 11시 30분. 4번 테이블 손님이 왔던 다음 날. 쥘리앙과 클로에는 테이블을 밀어 붙이고, 엘렌은 칠판에 포뮬을 적는다."),
(J, "Alors, Chloé ? Tu as bien dormi après ton premier soir ?", "그래, 클로에? 첫 저녁 근무 끝나고 잘 잤어?"),
(C, "Pas vraiment. J'ai rêvé de noix et de gluten toute la nuit.", "별로요. 밤새 호두랑 글루텐 꿈을 꿨어요."),
(J, "Ha ha ! Bon, aujourd'hui, c'est la formule. Regarde l'ardoise.", "하하! 자, 오늘은 포뮬이야. 칠판 봐."),
(C, "Seize, dix-neuf, vingt-quatre... Je comprends pas bien la différence.", "16, 19, 24... 차이를 잘 모르겠어요."),
(J, "Écoute. Le plat du jour seul, c'est seize euros.", "잘 들어. 오늘의 요리만 먹으면 16유로야."),
(C, "Seize euros, d'accord. Et si on veut plus ?", "16유로, 알겠어요. 더 먹고 싶으면요?"),
(J, "Entrée plus plat, ou plat plus dessert : dix-neuf euros.", "앙트레 더하기 메인, 아니면 메인 더하기 디저트는 19유로."),
(C, "Dix-neuf euros, que ce soit l'entrée ou le dessert ?", "앙트레든 디저트든 똑같이 19유로예요?"),
(J, "Exactement. Et entrée, plat, dessert : vingt-quatre euros.", "맞아. 그리고 앙트레, 메인, 디저트 다 하면 24유로."),
(C, "Donc le dessert coûte cinq euros de plus quand on a déjà entrée plus plat.", "그러니까 앙트레랑 메인이 있으면 디저트는 5유로만 더 내는 거네요."),
(J, "Bravo, t'as compris. Par contre, entrée plus dessert, sans plat, c'est non.", "잘했어, 이해했네. 대신 메인 없이 앙트레 더하기 디저트는 안 돼."),
(C, "Pourquoi ? Y en a qui n'ont pas très faim, non ?", "왜요? 배가 별로 안 고픈 사람도 있잖아요."),
(J, "Dans une formule, le plat est obligatoire. C'est la règle de la maison.", "포뮬에서는 메인이 필수야. 우리 집 규칙이지."),
(H, "Julien, on est combien à midi, au juste ?", "쥘리앙, 점심에 정확히 몇 명이지?"),
(J, "Douze, avec un groupe au nom de Roussel. Je pousse trois tables au fond.", "열두 명이야, 루셀 씨 이름으로 온 단체. 안쪽에 테이블 세 개를 붙이고 있어."),
(H, "Douze couverts d'un coup. Je veux que tout sorte en même temps.", "열두 명분이 한꺼번에. 모든 접시가 동시에 나가야 해."),
(C, "Les douze plats ensemble ? Sur la même table ?", "열두 접시를 동시에요? 한 테이블에?"),
(H, "Entrées ensemble, plats ensemble. Sinon, c'est le chaos.", "앙트레는 같이, 메인도 같이. 안 그러면 난장판이야."),
(J, "Chloé, tu comptes tout, et tu répètes les nombres avant d'envoyer en cuisine.", "클로에, 전부 세고, 주방에 넘기기 전에 숫자를 다시 말해."),
(C, "Compris. Je répète toujours les nombres.", "알겠어요. 숫자는 항상 다시 말할게요."),
(H, "Et au moindre doute, tu me demandes. Comme hier soir.", "그리고 조금이라도 헷갈리면 나한테 물어봐. 어제 저녁처럼."),
(None, "12 h 15. Le groupe arrive. M. Roussel, un homme chaleureux, serre la main de Julien.",
 "12시 15분. 단체 손님이 도착한다. 사람 좋아 보이는 루셀 씨가 쥘리앙과 악수한다."),
(R, "Bonjour ! Roussel, j'ai réservé pour douze. On est un peu bruyants, je préviens !", "안녕하세요! 루셀입니다, 열두 명 예약했어요. 좀 시끄러울 수 있어서 미리 말씀드려요!"),
(J, "Bonjour, monsieur Roussel. Bruyants, c'est parfait : ça fait de l'ambiance. Par ici, je vous prie.", "안녕하세요, 루셀 씨. 시끄러운 거 좋죠, 분위기가 사니까요. 이쪽으로 오세요."),
(R, "Ah, ça sent bon ! C'est une blanquette, ça ?", "아, 냄새 좋네요! 블랑케트인가요?"),
(J, "Bien vu. C'est notre plat du jour. Ma collègue Chloé va vous expliquer la formule.", "정확해요. 오늘의 요리예요. 동료 클로에가 포뮬을 설명해 드릴 거예요."),
(C, "Bonjour à tous. Vous voulez un apéritif, ou vous préférez regarder la carte d'abord ?", "안녕하세요, 여러분. 식전주를 드릴까요, 아니면 먼저 메뉴를 보시겠어요?"),
(R, "On va prendre trois pichets de vin de la maison, et de l'eau.", "하우스 와인 피처 세 개랑 물 주세요."),
(C, "Trois pichets de vin de la maison. Je note. Je vous explique la formule ?", "하우스 와인 피처 세 개요. 적을게요. 포뮬을 설명해 드릴까요?"),
(R, "Oui, allez-y. On est tous affamés.", "네, 해 주세요. 다들 배가 고파요."),
(C, "Il y a trois possibilités. Le plat du jour seul, seize euros.", "세 가지가 있어요. 오늘의 요리만은 16유로예요."),
(R, "Seize euros, la blanquette. Bien.", "16유로, 블랑케트군요. 좋아요."),
(C, "Ensuite, entrée plus plat, ou plat plus dessert : dix-neuf euros. Et le menu complet : vingt-quatre euros.", "그다음 앙트레 더하기 메인, 또는 메인 더하기 디저트는 19유로. 풀코스는 24유로예요."),
(R, "Parfait. Chacun choisit sa formule, c'est ça ?", "좋아요. 각자 포뮬을 고르는 거죠?"),
(C, "C'est ça. Je peux prendre les commandes une par une, si vous voulez.", "맞아요. 원하시면 한 분씩 주문 받을게요."),
(R, "Allez-y. Je commence : moi, je prends l'entrée plus plat, dix-neuf euros.", "해 주세요. 제가 먼저 할게요. 저는 앙트레 더하기 메인, 19유로로요."),
(C, "Très bien. Quelle entrée, monsieur ?", "좋아요. 앙트레는 뭘로 하시겠어요?"),
(R, "L'œuf mayonnaise. Comme chez ma grand-mère !", "달걀 마요네즈요. 우리 할머니 집처럼!"),
(C, "Et comme plat ?", "메인은요?"),
(R, "Le steak-frites. Saignant.", "스테이크 프리트요. 레어로."),
(C, "Un steak saignant. Merci. Ensuite ?", "레어 스테이크 하나요. 감사합니다. 다음 분은요?"),
(R, "Ensuite, Sophie. Elle est végétarienne. Elle voudrait un plat sans viande.", "다음은 소피. 채식주의자예요. 고기 없는 메인을 원하세요."),
(C, "Je demande au chef ce qu'elle peut avoir. Je reviens.", "셰프께 뭐가 가능한지 여쭤볼게요. 금방 올게요."),
(None, "En cuisine. Hélène goûte une sauce.", "주방. 엘렌이 소스를 맛보고 있다."),
(C, "Chef, une cliente végétarienne dans le groupe. Qu'est-ce qu'elle peut manger ?", "셰프, 단체 손님 중에 채식주의자가 한 분 계세요. 뭘 드실 수 있어요?"),
(H, "Velouté de petits pois en entrée. En plat, une assiette de légumes rôtis, avec un œuf.", "앙트레는 완두콩 수프. 메인은 구운 채소 접시에 달걀 하나."),
(C, "C'est dans la formule ? À dix-neuf euros ?", "그게 포뮬에 들어가요? 19유로로요?"),
(H, "Oui, même prix. C'est une assiette du jour, pas une punition.", "응, 같은 가격이야. 오늘의 접시지, 벌이 아니라."),
(C, "Je peux lui dire ça comme ça, mot pour mot ?", "그대로 말해도 돼요? 한 글자도 안 바꾸고요?"),
(H, "Mot pour mot. Elle va rire.", "한 글자도 안 바꾸고. 웃을 거야."),
(C, "Pour Sophie : velouté de petits pois, puis une assiette de légumes rôtis avec un œuf.", "소피 씨께는요, 완두콩 수프, 그다음 달걀을 곁들인 구운 채소 접시예요."),
(R, "Voilà une bonne nouvelle. Sophie dit merci, c'est parfait.", "좋은 소식이네요. 소피가 고맙대요, 완벽하대요."),
(R, "Ensuite, Marc prend le plat du jour seul. Il fait un régime depuis lundi.", "다음, 마르크는 오늘의 요리만요. 월요일부터 다이어트 중이거든요."),
(C, "Un plat du jour, seize euros. Si Marc veut un dessert, ça passe à dix-neuf.", "오늘의 요리 하나, 16유로요. 마르크 씨가 디저트를 원하시면 19유로가 돼요."),
(R, "Tu as entendu, Marc ? Pour les autres, je vous donne ça en vrac.", "마르크, 들었지? 나머지는 한꺼번에 말씀드릴게요."),
(R, "Trois entrée-plat, trois menus complets, deux plat-dessert, et un plat du jour.", "앙트레-메인 세 명, 풀코스 세 명, 메인-디저트 두 명, 오늘의 요리 한 명이에요."),
(C, "Doucement ! Trois entrée-plat, trois complets, deux plat-dessert, un plat du jour. C'est ça ?", "천천히요! 앙트레-메인 셋, 풀코스 셋, 메인-디저트 둘, 오늘의 요리 하나. 맞죠?"),
(R, "C'est ça, plus ceux qu'on vient de dire. Vous me suivez ?", "맞아요, 방금 말한 분들 말고요. 따라오고 계시죠?"),
(C, "J'essaie ! Alors les entrées : combien de veloutés ?", "노력 중이에요! 그럼 앙트레부터요. 완두콩 수프는 몇 개예요?"),
(R, "Trois veloutés, dont celui de Sophie. Trois œufs mayonnaise. Deux terrines.", "수프 세 개, 소피 것 포함이에요. 달걀 마요네즈 세 개. 테린 두 개."),
(C, "Trois veloutés, trois œufs mayo, deux terrines. Ça fait huit entrées.", "수프 셋, 달걀 마요네즈 셋, 테린 둘. 앙트레가 여덟 개네요."),
(R, "Huit, oui. Pour les plats, on est douze, bien sûr.", "여덟, 맞아요. 메인은 당연히 열두 개고요."),
(C, "Combien de blanquettes ?", "블랑케트는 몇 개예요?"),
(R, "Quatre blanquettes et trois cabillauds. Plus quatre steaks-frites.", "블랑케트 넷, 대구 셋. 그리고 스테이크 프리트 넷이요."),
(C, "Quatre, trois, quatre, plus l'assiette de légumes : douze plats. Et les cuissons ?", "넷, 셋, 넷, 거기에 채소 접시까지 열두 개. 굽기는요?"),
(R, "Un saignant, c'est moi. Deux à point, et un bien cuit.", "레어가 하나, 저예요. 미디엄이 둘, 웰던이 하나."),
(C, "Un saignant, deux à point, un bien cuit. Merci.", "레어 하나, 미디엄 둘, 웰던 하나. 감사합니다."),
(R, "Pour les desserts, on décidera plus tard. On garde de la place !", "디저트는 나중에 정할게요. 배 안 채우고 아껴 둬야죠!"),
(C, "Parfait. Je vous apporte l'eau et les pichets, et les entrées arrivent dans dix minutes.", "알겠습니다. 물이랑 피처를 가져다드릴게요, 앙트레는 10분 뒤에 나와요."),
(J, "Voilà vos trois pichets, et l'eau. Un pichet pour quatre, plus ou moins.", "피처 세 개랑 물 나왔습니다. 피처 하나에 네 분 정도예요."),
(R, "Plus ou moins, c'est bien dit ! On va s'arranger.", "대충 그 정도라, 말 잘하시네요! 알아서 나눠 마실게요."),
(None, "Au bar. Chloé montre son carnet à Julien.", "바 앞. 클로에가 쥘리앙에게 수첩을 보여 준다."),
(C, "Julien, regarde. J'ai tout noté, mais je me perds dans les nombres.", "쥘리앙, 봐요. 다 적긴 했는데 숫자에서 길을 잃겠어요."),
(J, "Montre. Huit entrées, douze plats... et les desserts ?", "어디 보자. 앙트레 여덟, 메인 열두... 디저트는?"),
(C, "Ils n'ont pas encore choisi. Mais je sais pas combien.", "아직 안 골랐어요. 근데 몇 개인지도 모르겠고요."),
(J, "Si, tu le sais : trois menus complets, plus deux plat-dessert.", "아니, 알아. 풀코스 셋 더하기 메인-디저트 둘."),
(C, "Cinq desserts ! C'est logique. Et le prix total ?", "디저트 다섯 개! 논리적이네요. 그럼 총액은요?"),
(J, "Calcule. Cinq entrée-plat à dix-neuf euros ?", "계산해 봐. 앙트레-메인 다섯 개에 19유로씩이면?"),
(C, "Cinq fois dix-neuf... quatre-vingt-quinze euros.", "5 곱하기 19는... 95유로요."),
(J, "Bien. Trois menus complets à vingt-quatre euros ?", "좋아. 풀코스 셋에 24유로씩이면?"),
(C, "Soixante-douze. Et deux plat-dessert à dix-neuf : trente-huit.", "72요. 그리고 메인-디저트 둘에 19유로씩이면 38이고요."),
(J, "Il reste les deux plats du jour à seize euros.", "오늘의 요리 둘이 남았지, 16유로씩."),
(C, "Trente-deux. Donc quatre-vingt-quinze plus soixante-douze, cent soixante-sept.", "32요. 그러니까 95 더하기 72는 167이고요."),
(C, "Plus trente-huit, deux cent cinq. Plus trente-deux : deux cent trente-sept euros !", "38을 더하면 205. 32를 더하면 237유로예요!"),
(J, "Deux cent trente-sept. Et les trois pichets ?", "237. 피처 세 개는?"),
(C, "Trois fois neuf, vingt-sept. Donc deux cent soixante-quatre euros en tout.", "3 곱하기 9는 27. 그러니까 전부 264유로예요."),
(J, "Impeccable. T'as même pas besoin de calculette.", "완벽해. 계산기도 필요 없네."),
(C, "J'ai compté sur mes doigts, en secret !", "몰래 손가락으로 셌어요!"),
(None, "12 h 40. Chloé passe le bon à Hélène.", "12시 40분. 클로에가 주문서를 엘렌에게 넘긴다."),
(C, "Chef, huit entrées : trois veloutés, trois œufs mayo, deux terrines.", "셰프, 앙트레 여덟 개요. 수프 셋, 달걀 마요네즈 셋, 테린 둘."),
(H, "Huit entrées, départ ! Les plats dans quinze minutes.", "앙트레 여덟 개, 출발! 메인은 15분 뒤에."),
(C, "Je préviens le groupe que les plats arrivent dans quinze minutes ?", "단체 손님께 메인이 15분 뒤에 나온다고 말해 둘까요?"),
(H, "Oui. Et dis-leur que ce sera chaud et bon.", "응. 뜨겁고 맛있게 나온다고 말해 줘."),
(C, "Et les steaks : un saignant, deux à point, un bien cuit.", "스테이크는 레어 하나, 미디엄 둘, 웰던 하나예요."),
(H, "Je note. Et l'assiette végétarienne, c'est moi qui la fais.", "적어 뒀어. 채식 접시는 내가 직접 만들게."),
(None, "Dans la salle, Julien et Chloé servent les entrées.", "홀에서 쥘리앙과 클로에가 앙트레를 서빙한다."),
(J, "Le velouté de petits pois, c'est pour qui ?", "완두콩 수프는 어느 분이시죠?"),
(R, "Ici ! Les veloutés, c'est Sophie et ses deux voisins.", "여기요! 수프는 소피랑 양옆 두 사람이에요."),
(C, "Et l'œuf mayonnaise pour monsieur Roussel. Bon appétit !", "달걀 마요네즈는 루셀 씨 거예요. 맛있게 드세요!"),
(R, "Oh là là, la vraie mayonnaise, comme chez ma grand-mère ! Bravo.", "와, 진짜 마요네즈네요, 우리 할머니 집처럼! 훌륭해요."),
(J, "Merci, monsieur. Je transmettrai à la patronne.", "감사합니다, 손님. 사장님께 전할게요."),
(None, "13 h 20. Les plats sortent. Hélène les aligne sur le passe.", "13시 20분. 메인 요리가 나온다. 엘렌이 패스대에 줄지어 놓는다."),
(H, "Quatre blanquettes, trois cabillauds, quatre steaks, une assiette de légumes. Douze !", "블랑케트 넷, 대구 셋, 스테이크 넷, 채소 접시 하나. 열두 개!"),
(C, "Douze, oui. On y va ensemble, Julien ?", "열두 개 맞아요. 같이 가요, 쥘리앙?"),
(J, "Ensemble. Six chacun. Attention, les assiettes sont très chaudes.", "같이. 각자 여섯 개씩. 조심해, 접시 아주 뜨거워."),
(R, "Ah, voilà ! Dites, Marc change d'avis : il veut un dessert.", "아, 왔네요! 저기, 마르크가 마음을 바꿨어요. 디저트 먹겠대요."),
(C, "Pas de problème. Marc passe à dix-neuf euros : plat plus dessert.", "문제없어요. 마르크 씨는 메인 더하기 디저트로 19유로가 됩니다."),
(J, "Tu vois, Chloé ? Les nombres changent. Il faut refaire le total.", "봤지, 클로에? 숫자는 바뀌어. 총액을 다시 계산해야 해."),
(C, "Alors : il y a un plat du jour en moins et un plat-dessert en plus.", "그럼 오늘의 요리가 하나 줄고 메인-디저트가 하나 늘었네요."),
(J, "Donc trois euros de plus. Combien ?", "그러면 3유로가 더해지지. 얼마지?"),
(C, "Deux cent quarante euros de formules. Et vingt-sept de vin : deux cent soixante-sept.", "포뮬이 240유로예요. 와인이 27이니까 267유로요."),
(None, "14 h 05. Chloé débarrasse et revient avec la carte des desserts.", "14시 5분. 클로에가 테이블을 치우고 디저트 메뉴를 들고 돌아온다."),
(C, "Pour les desserts : mousse au chocolat, crème brûlée, île flottante et tarte Tatin.", "디저트는 초콜릿 무스, 크렘 브륄레, 일 플로탕트, 타르트 타탱이 있어요."),
(R, "Alors : deux mousses, deux crèmes brûlées, une Tatin et une île flottante.", "그럼, 무스 둘, 크렘 브륄레 둘, 타탱 하나, 일 플로탕트 하나요."),
(C, "Deux, deux, un, un. Ça fait six desserts, avec Marc.", "둘, 둘, 하나, 하나. 마르크 씨 포함해서 디저트 여섯 개예요."),
(R, "Six, oui. Et huit cafés, s'il vous plaît.", "여섯, 맞아요. 그리고 커피 여덟 잔 부탁해요."),
(C, "Huit cafés. Je vous apporte tout ça.", "커피 여덟 잔요. 바로 가져올게요."),
(R, "Dites, vos formules à vingt-quatre euros, c'est le meilleur rapport qualité-prix du quartier !", "있잖아요, 24유로짜리 포뮬이 이 동네에서 가성비가 제일 좋아요!"),
(J, "Vous êtes gentil. Dans le onzième, on fait ce qu'on peut.", "친절하시네요. 11구에서 저희는 최선을 다할 뿐이에요."),
(None, "14 h 50. Le groupe est parti. La salle se vide.", "14시 50분. 단체 손님이 떠났다. 홀이 비어 간다."),
(C, "Ils ont tout fini ! Même les frites des autres tables.", "다 드셨어요! 다른 테이블 감자튀김까지요."),
(H, "Huit entrées, douze plats, six desserts. Pas une erreur. Bien.", "앙트레 여덟, 메인 열두, 디저트 여섯. 실수 하나 없었어. 좋아."),
(C, "Merci, chef. Mais Julien m'a aidée pour les nombres.", "감사합니다, 셰프. 근데 숫자는 쥘리앙이 도와줬어요."),
(J, "Elle a tout calculé seule, patronne. Moi, j'ai juste regardé.", "혼자 다 계산했어요, 사장님. 전 보기만 했고요."),
(J, "Et M. Roussel a laissé un joli pourboire pour Chloé.", "그리고 루셀 씨가 클로에한테 팁을 후하게 남겼어."),
(C, "Pour moi ? Vraiment ? Je suis toute rouge.", "저한테요? 정말요? 얼굴이 빨개졌어요."),
(H, "Mange quelque chose. Demain, on est complets, midi et soir.", "뭐 좀 먹어. 내일은 점심, 저녁 다 만석이야."),
(C, "Alors je prends la formule à seize euros. Le plat du jour, avec plaisir !", "그럼 16유로 포뮬 먹을게요. 오늘의 요리, 기꺼이요!"),
]

VOCAB = [
("A2", "la formule", "세트 메뉴(포뮬)", "점심 한정 세트. 이 가게는 plat du jour seize euros / entrée+plat 또는 plat+dessert dix-neuf euros / entrée+plat+dessert vingt-quatre euros."),
("A2", "le plat du jour", "오늘의 요리", "칠판에 적힌 그날의 메인. 이 화에서는 la blanquette."),
("A2", "l'entrée / le plat / le dessert", "앙트레 / 메인 / 디저트", "프랑스어 entrée 는 '전채', 영어의 entrée(메인)와 뜻이 다르다."),
("A2", "un menu complet", "풀코스 (앙트레+메인+디저트)", "구어에서는 « le menu complet » 또는 « la formule complète »."),
("A2", "Combien de ... ?", "몇 개의 ...?", "수량 질문: Combien de blanquettes ? 대답: Quatre."),
("A2", "Ça fait + 합계", "합쳐서 ~입니다", "Ça fait huit entrées. Ça fait six desserts. 계산 결과를 말할 때."),
("A2", "Je note. / Je répète.", "적을게요. / 다시 말할게요.", "주문 확인 때 쓰는 짧은 동사. 숫자는 꼭 다시 말하는 것이 홀의 습관."),
("A2", "seul(e)", "혼자의, ~만", "le plat du jour seul = 오늘의 요리만(앙트레·디저트 없이)."),
("A2", "en même temps", "동시에", "Je veux que tout sorte en même temps. 한꺼번에 나가는 요리."),
("B1", "un couvert", "1인분 식기 세트, 손님 한 명분", "douze couverts = 열두 명분. 식당에서 인원수를 셀 때 쓴다."),
("B1", "en vrac", "한꺼번에, 뒤죽박죽으로", "[구어] Je vous donne ça en vrac. ↔ 정중: Je vous l'indique en une seule fois."),
("B1", "ça passe à + 금액", "~가 된다(금액이 바뀐다)", "Si Marc veut un dessert, ça passe à dix-neuf. 포뮬이 바뀔 때."),
("B1", "obligatoire", "필수의", "Le plat est obligatoire. 포뮬의 규칙을 설명할 때."),
("B1", "végétarien(ne)", "채식주의자(의)", "Elle est végétarienne. 주방에는 « sans viande » 로 전달."),
("B1", "affamé(e)", "몹시 배고픈", "On est tous affamés. 단체 손님의 흔한 한마디."),
("B1", "saignant / à point / bien cuit", "레어 / 미디엄 / 웰던", "스테이크 굽기. 여기서는 숫자와 함께 « Un saignant, deux à point, un bien cuit »."),
("B2", "un bon pourboire", "후한 팁", "프랑스에서는 의무가 아니지만 좋은 서비스에 대한 감사의 표시. 9화에서 자세히."),
("B2", "le rapport qualité-prix", "가성비", "C'est le meilleur rapport qualité-prix du quartier. 칭찬의 표현."),
("B2", "Ils ont tout fini.", "다 드셨어요(접시를 비웠어요).", "[구어] finir 는 '다 먹다'. ↔ 정중: Ils ont tout terminé."),
("B2", "faire un régime", "다이어트하다", "Il fait un régime depuis lundi. depuis + 시점."),
("C1", "C'est le chaos.", "난장판이다.", "[구어] 동시에 몰려드는 주문을 말할 때. ↔ 정중: Ce serait très désorganisé."),
("C1", "ce n'est pas une punition", "벌이 아니다", "Hélène 의 건조한 유머. 채식 메뉴를 얕보는 시선을 가볍게 되받는다."),
]

GRAM = [
("A2", "수량 묻고 답하기: combien de + 복수명사",
 "« Combien de blanquettes ? — Quatre blanquettes. » 질문에서는 de 뒤에 관사가 없고, 대답은 수 + 명사. « Trois veloutés, trois œufs mayo, deux terrines. » 처럼 목록으로 말한다."),
("A2", "숫자 읽기 — 가격과 수량",
 "seize(16), dix-neuf(19), vingt-quatre(24), soixante-douze(72), quatre-vingt-quinze(95), deux cent trente-sept(237). 이 화에서는 가격을 모두 단어로 쓴다. 70·90대는 60+10, 80+15 로 센다."),
("A2", "formule 선택 — entrée + plat / plat + dessert",
 "« Entrée plus plat, ou plat plus dessert : dix-neuf euros. » plus 는 [plys] 로 읽는 '더하기'. 선택지는 'ou' 로 연결하고, 가격은 콜론 뒤에 붙인다."),
("B1", "단체 주문 정리하기",
 "« Trois entrée-plat, trois menus complets, deux plat-dessert, et un plat du jour. » 명사만 나열하는 구어 형태. 이어서 « Doucement ! ... C'est ça ? » 처럼 되묻는 확인 문장으로 오류를 막는다."),
("B1", "si + 현재, 현재 (조건과 결과)",
 "« Si Marc veut un dessert, ça passe à dix-neuf. » 조건은 si + 현재, 결과도 현재(또는 미래). 포뮬이 바뀌는 상황 설명에 쓸모가 크다."),
("B1", "비교와 수량 변화: un ... en moins / en plus",
 "« Il y a un plat du jour en moins et un plat-dessert en plus. » 줄거나 늘어난 수를 말할 때. « trois euros de plus » 처럼 de plus 는 '~만큼 더'."),
("B2", "dont / même 로 정보 덧붙이기",
 "« Trois veloutés, dont celui de Sophie. » dont 은 '그중'. « Ils ont tout fini, même les frites. » 처럼 même 로 강조도 가능. 목록에 정보를 덧붙일 때 자주 쓴다."),
]

READ = [
("숫자 사이의 리에종 — quatre-vingt-quinze",
 "« Quatre-vingt-quinze euros » 는 « 까트르 / 뱅 / 깽즈 / 외로 » 처럼 네 덩어리. vingt 의 t 는 안 읽고, quinze 와 euros 사이는 « quinze_euros » 로 z 를 이어 읽는다. 가격을 낭독할 때는 숫자와 euros 를 한 호흡으로."),
("dix-neuf, vingt-quatre, soixante-douze",
 "« dix-neuf » 는 [diz.nœf], 뒤에 모음이 오면 « dix-neuf_euros » 에서 f 를 [v] 로 이어 « 디즈뇌 뵈 외로 » 처럼. « soixante-douze » 는 « 수아상트 두즈 », x 는 [s]. 숫자마다 호흡을 짧게 끊는다."),
("의문과 확인의 억양 — C'est ça ?",
 "« C'est ça ? » 는 끝이 올라간다. « Trois entrée-plat, / trois menus complets, / deux plat-dessert, / et un plat du jour. » 처럼 쉼표마다 쉬고 마지막에 억양이 내려가는 평서 억양으로 목록을 읽은 뒤, « C'est ça ? » 는 올려 읽어 대비를 만든다."),
("r 연습 — rapport qualité-prix, rôti, répète",
 "« Je répète toujours les nombres. » 에서 répète 의 r 은 목젖에서 가볍게. « le rapport qualité-prix » 에서는 rapport 의 두 r 사이 모음을 흐리지 말고 « 라포르 » 로 또렷하게."),
("엘리종 — l'assiette, j'ai, qu'est-ce",
 "« L'assiette est chaude » 는 « 라시에트 에 쇼드 ». « Qu'est-ce qu'elle peut manger ? » 는 « 께스 껠 뾔 망제 » 로 이어진다. 모음 충돌을 줄여 부드럽게 읽는 연습."),
("긴 문장 호흡 — 포뮬 설명",
 "« Ensuite, / entrée plus plat, / ou plat plus dessert : / dix-neuf euros. / Et le menu complet : / vingt-quatre euros. » 처럼 콜론 뒤에서 한 번 숨을 고르고 가격을 또렷하게 읽는다."),
("비음 — dix-neuf et cinq, quatre-vingt, cent",
 "« cinq » [sɛ̃k], « vingt » [vɛ̃], « cent » [sɑ̃] 는 코로 울려서 읽는다. « cent soixante-sept » 는 « 상 수아상트 세트 », t 는 [t] 로 소리 난다. 비음 숫자를 반복해서 소리 내 보자."),
]

CULTURE = [
("Formule — 프랑스 점심의 합리적 약속",
 "프랑스 비스트로의 점심 formule 은 평일 직장인을 위한 합리적 세트다. plat du jour 단품 → entrée+plat 또는 plat+dessert → 풀코스 순으로 가격이 오르고, 이 가게에서는 16 / 19 / 24 유로. 정해진 범위 안에서 고를 수 있어 빠르고 예측 가능하다. 단체 손님도 formule 을 고르면 계산이 간단해진다."),
("단체 예약과 동시 서빙",
 "열 명 이상의 단체는 앙트레끼리, 메인끼리 한꺼번에 내는 것이 예의다. 서버는 « Qui a pris le velouté ? » 하고 묻지 않고 요리 이름을 부르며 놓는다. 한 사람이 대표로 주문하면 정확성을 위해 서버는 숫자를 반복해서 확인한다."),
]

META = dict(part=1, ep=5, part_label="제1부 Mise en place · 봄", title_fr="Entrée, plat, dessert", title_ko="앙트레, 메인, 디저트",
 place="Le Comptoir de Marthe, 4월 17일 금요일 점심 (11시 30분 ~ 15시경)", chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · M. Roussel (열두 명 단체 대표)",
 wine="열두 명 단체의 포뮬 주문과 가격 계산",
 focus="수량 묻기(Combien de ... ?), 숫자와 가격 읽기, formule 선택(entrée+plat / plat+dessert), 주문 변경과 합계 다시 계산",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제6화 « Le steak trop cuit » : 4월 25일 토요일 저녁, 고기가 너무 익었다는 손님의 불만과 사과·해결")
