# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, P = "Hélène", "Julien", "Chloé", "M. Perrin"
D = [
(None, "Samedi 25 avril, 20 h 35. Huit jours après le déjeuner du groupe Roussel. Le service du soir bat son plein. Chloé revient de la table neuf, l'air inquiet.",
 "4월 25일 토요일 저녁 8시 35분. 루셀 단체 점심 후 8일이 지났다. 저녁 영업이 한창이다. 클로에가 걱정스러운 얼굴로 9번 테이블에서 돌아온다."),
(C, "Julien, j'ai un petit problème à la table neuf.", "쥘리앙, 9번 테이블에 작은 문제가 생겼어요."),
(J, "Dis-moi. Respire, et dis-moi.", "말해 봐. 숨 쉬고, 말해 봐."),
(C, "Le monsieur dit que son steak est trop cuit.", "손님이 스테이크가 너무 익었대요."),
(J, "Il l'avait demandé comment ?", "어떻게 익혀 달라고 했었지?"),
(C, "Saignant. Je suis sûre de l'avoir écrit sur le bon.", "레어요. 주문서에 분명히 적었어요."),
(J, "Montre. Saignant, c'est écrit en gros. Alors, ce n'est pas toi.", "보여 줘. 레어, 크게 적혀 있네. 그럼 네 잘못이 아니야."),
(C, "Ouf. Mais je me sens mal quand même.", "휴. 그래도 마음이 안 좋아요."),
(J, "Tu as bien fait de venir me voir tout de suite.", "바로 나한테 와서 잘했어."),
(C, "C'est ce que la patronne a dit hier : au moindre doute, on demande.", "사장님이 어제 말씀하셨잖아요. 조금이라도 의심스러우면 물어보라고요."),
(J, "Normal. Mais devant le client, on ne cherche jamais de coupable.", "당연하지. 하지만 손님 앞에서는 절대 누구 탓인지 따지지 않아."),
(C, "Alors qu'est-ce qu'on fait, concrètement ?", "그럼 구체적으로 어떻게 해요?"),
(J, "Quatre étapes. Un : on écoute. Deux : on s'excuse.", "네 단계야. 하나, 듣는다. 둘, 사과한다."),
(C, "Et trois ?", "셋은요?"),
(J, "On propose une solution. Et quatre : on remercie le client de sa patience.", "해결책을 제안한다. 그리고 넷, 기다려 준 손님에게 감사한다."),
(C, "Écouter, s'excuser, proposer, remercier. Je le note.", "듣기, 사과하기, 제안하기, 감사하기. 적어 둘게요."),
(J, "Viens avec moi. Aujourd'hui, tu regardes. La prochaine fois, c'est toi.", "나랑 같이 가. 오늘은 보기만 해. 다음번엔 네 차례야."),
(None, "À la table neuf. M. Perrin, un homme d'allure soignée, regarde son assiette sans un mot. Sa femme boit son vin.",
 "9번 테이블. 단정한 차림의 페랭 씨가 말없이 접시를 내려다본다. 그의 아내는 와인을 마시고 있다."),
(J, "Bonsoir, monsieur. Il paraît qu'il y a un souci avec votre viande ?", "안녕하세요, 손님. 고기에 문제가 있다고 들었는데요?"),
(P, "Bonsoir. Oui, un petit souci. J'avais demandé un steak saignant. Regardez.", "안녕하세요. 네, 작은 문제가 있어요. 저는 스테이크를 레어로 주문했어요. 보세요."),
(J, "Vous permettez ? Je jette un œil.", "괜찮으시면 제가 한번 볼게요."),
(P, "Il est gris jusqu'au milieu. C'est bien cuit, ça, pas saignant.", "한가운데까지 회색이에요. 이건 웰던이지 레어가 아니죠."),
(J, "Effectivement. Il est beaucoup trop cuit. Je suis vraiment désolé, monsieur.", "그렇네요. 너무 많이 익었습니다. 정말 죄송합니다, 손님."),
(P, "Vingt et un euros pour une semelle, c'est un peu cher, non ?", "21유로에 구두 밑창이라니, 좀 비싸지 않나요?"),
(J, "Vous avez raison. Je comprends tout à fait votre déception.", "맞는 말씀이세요. 실망하신 마음 충분히 이해합니다."),
(P, "Ne vous excusez pas trop, ça arrive. Mais j'avais très envie d'un vrai saignant.", "너무 사과하지는 마세요, 그럴 수도 있죠. 다만 진짜 레어가 정말 먹고 싶었거든요."),
(J, "Je vous emmène cette assiette en cuisine. Le chef vous en refait un tout de suite.", "이 접시는 주방으로 가져가겠습니다. 셰프가 바로 새로 만들어 드릴 거예요."),
(P, "Maintenant ? Ma femme aura fini son plat avant moi !", "지금요? 제 아내는 저보다 먼저 다 먹을 텐데요!"),
(J, "Madame, toutes mes excuses. Je vous apporte un verre de Brouilly en attendant, offert par la maison.", "부인, 정말 죄송합니다. 기다리시는 동안 브루이 한 잔 가져다드릴게요, 가게에서 드리는 겁니다."),
(P, "Offert ? C'est gentil. Mais on a un spectacle à vingt-deux heures.", "무료로요? 고맙네요. 근데 저희 밤 10시에 공연이 있어요."),
(J, "Pas de souci. Le steak sera là dans dix minutes, je vous le garantis.", "걱정 마세요. 스테이크는 10분 안에 나올 겁니다, 장담합니다."),
(P, "Dix minutes ? Vous êtes sûr ?", "10분이요? 확실해요?"),
(J, "Sûr. Et si vous êtes en retard, je l'enlève de l'addition.", "확실합니다. 그리고 늦으시면 계산서에서 빼 드릴게요."),
(P, "Vendu ! Allez, on vous attend.", "좋아요! 자, 기다리겠습니다."),
(None, "Julien prend l'assiette. Chloé le suit vers la cuisine.", "쥘리앙이 접시를 든다. 클로에가 뒤따라 주방으로 간다."),
(C, "Tu lui as promis dix minutes. Le chef peut vraiment le faire ?", "10분이라고 약속했잖아요. 셰프가 정말 할 수 있어요?"),
(J, "On va voir. Quand on s'engage, il faut tenir. Viens.", "두고 보자. 약속했으면 지켜야지. 가자."),
(None, "En cuisine. Hélène est aux sauces, Karim au gril, concentré.", "주방. 엘렌은 소스 담당이고, 카림은 집중한 채 그릴 앞에 있다."),
(J, "Chef, table neuf. Le steak est trop cuit. Le monsieur voulait un saignant.", "셰프, 9번 테이블이에요. 스테이크가 너무 익었어요. 손님은 레어를 원했고요."),
(H, "Merde. Gris jusqu'au centre. C'est même plus que bien cuit.", "젠장. 한가운데까지 회색이네. 웰던보다 더 익었어."),
(C, "Chef, j'avais écrit « saignant » sur le bon.", "셰프, 주문서에 « 레어 » 라고 적었어요."),
(H, "Je sais, je l'ai lu. Le problème est au gril, pas en salle.", "알아, 읽었어. 문제는 홀이 아니라 그릴이야."),
(None, "Au gril, Karim baisse la tête sans rien dire.", "그릴 앞에서 카림이 아무 말 없이 고개를 숙인다."),
(H, "Je refais celui-là moi-même. Julien, combien de temps ?", "이건 내가 직접 다시 할게. 쥘리앙, 시간이 얼마나 있지?"),
(J, "Le monsieur a un spectacle à vingt-deux heures. Je lui ai promis dix minutes.", "손님이 밤 10시에 공연이 있어요. 10분이라고 약속했고요."),
(H, "Dix minutes. Bien. Il m'en faut sept.", "10분. 좋아. 난 7분이면 돼."),
(C, "Sept minutes ? Comment vous faites pour aller si vite ?", "7분이요? 어떻게 그렇게 빨리 하세요?"),
(H, "Plaque déjà chaude, viande à température ambiante. Pas de miracle.", "철판은 이미 달궈져 있고, 고기는 실온 상태야. 기적은 없어."),
(C, "Chef, je peux regarder ? Je voudrais comprendre les cuissons.", "셰프, 옆에서 봐도 돼요? 굽기를 이해하고 싶어요."),
(H, "Regarde. D'abord les mots. Bleu : saisi dehors, presque cru dedans.", "봐. 먼저 용어부터. 블뢰는 겉만 살짝 익히고 속은 거의 날것이야."),
(C, "Bleu, c'est le moins cuit de tous ?", "블뢰가 제일 덜 익힌 거예요?"),
(H, "Oui. Ensuite, saignant : rouge et chaud au cœur.", "응. 그다음 세냥은 속이 붉고 한가운데가 따뜻한 상태."),
(C, "Saignant, c'est ce que voulait le monsieur.", "세냥, 그게 그 손님이 원한 거네요."),
(H, "Exactement. À point : rose au centre. Bien cuit : plus de rose du tout.", "맞아. 아 푸앵은 가운데가 분홍색. 비앙 퀴는 분홍색이 전혀 없어."),
(C, "Bleu, saignant, à point, bien cuit. C'est comme une échelle.", "블뢰, 세냥, 아 푸앵, 비앙 퀴. 사다리 같네요."),
(H, "Voilà. Donne-moi ta main. Touche le bas du pouce : c'est mou.", "맞아. 손 줘 봐. 엄지 밑동을 만져 봐. 말랑하지."),
(C, "Oui, c'est mou. Comme un steak cru, non ?", "네, 말랑해요. 날고기처럼요?"),
(H, "Pouce contre index, c'est saignant. Contre majeur, à point. Contre annulaire, bien cuit.", "엄지와 검지를 붙이면 레어. 중지는 미디엄. 약지는 웰던."),
(C, "Ça devient de plus en plus dur ! Quelle astuce !", "점점 더 단단해져요! 대단한 요령이네요!"),
(H, "Ça aide, mais ça ne remplace pas l'œil. Écoute le bruit dans la poêle.", "도움은 되지만 눈을 대신하진 못해. 팬 소리도 들어 봐."),
(None, "Hélène pose un nouveau steak sur la plaque. Ça grésille.", "엘렌이 새 스테이크를 철판에 올린다. 지글지글 소리가 난다."),
(H, "Deux minutes d'un côté, deux de l'autre. Après, il repose une minute.", "한쪽 2분, 다른 쪽 2분. 그다음 1분 쉬게 해."),
(C, "Pourquoi il repose ? Il ne va pas refroidir ?", "왜 쉬게 해요? 식지 않나요?"),
(H, "Non. Le jus se répartit dedans. Sinon, tout coule dans l'assiette.", "안 식어. 육즙이 고기 속에 퍼지는 거야. 안 그러면 전부 접시로 흘러."),
(J, "Je retourne en salle avec les verres de Brouilly. Chloé, tu apportes le steak.", "난 브루이 잔들 들고 홀로 돌아갈게. 클로에, 스테이크는 네가 가져가."),
(C, "Moi ? Je ne suis pas prête !", "저요? 아직 준비 안 됐어요!"),
(J, "Si. Tu connais les quatre étapes : écouter, s'excuser, proposer, remercier.", "아니, 됐어. 네 단계 알잖아. 듣고, 사과하고, 제안하고, 감사하는 거."),
(H, "Frites chaudes, steak saignant, assiette propre. Vas-y. Ne cours pas, souris.", "감자튀김은 뜨겁고, 스테이크는 레어, 접시도 깨끗해. 가. 뛰지 말고 웃어."),
(None, "Retour à la table neuf. Julien pose les verres de Brouilly ; Chloé arrive derrière lui avec l'assiette.", "다시 9번 테이블. 쥘리앙이 브루이 잔을 내려놓고, 클로에가 접시를 들고 뒤따라온다."),
(J, "Voilà deux verres de Brouilly. Ça vous aide à patienter ?", "브루이 두 잔 나왔습니다. 기다리시는 데 도움이 될까요?"),
(P, "Un peu ! Et ma femme a déjà fini ses frites, la pauvre.", "조금은요! 그런데 아내는 이미 감자튀김을 다 먹었네요, 불쌍하게도."),
(C, "Voici votre steak, monsieur. Saignant, avec des frites toutes chaudes.", "스테이크 나왔습니다, 손님. 레어로, 갓 튀긴 뜨거운 감자튀김과 함께요."),
(P, "Merci, mademoiselle. Voyons voir.", "고마워요, 아가씨. 어디 봅시다."),
(None, "M. Perrin coupe la viande. Le centre est rouge et brillant.", "페랭 씨가 고기를 자른다. 한가운데가 붉고 윤기가 난다."),
(P, "Ah ! Voilà. Rouge au centre, chaud, juste ce qu'il faut. Parfait.", "아! 바로 이거예요. 가운데는 붉고 따뜻하고, 딱 알맞아요. 완벽해요."),
(C, "Je suis vraiment désolée pour l'attente. Merci pour votre patience, monsieur.", "기다리시게 해서 정말 죄송합니다. 참아 주셔서 감사합니다, 손님."),
(P, "Vous avez bien fait. C'est vous qui avez pris la commande ?", "잘했어요. 주문 받은 사람이 아가씨인가요?"),
(C, "Oui, et j'avais écrit « saignant » sur mon bon.", "네, 그리고 주문서에 « 레어 » 라고 적어 뒀어요."),
(P, "Je vous crois. Dites-moi, c'est qui, la cheffe ? Je voudrais la féliciter.", "믿어요. 근데 셰프가 누구죠? 칭찬해 주고 싶은데."),
(None, "Hélène sort de la cuisine en essuyant ses mains sur son tablier.", "엘렌이 앞치마에 손을 닦으며 주방에서 나온다."),
(H, "C'est moi, monsieur. Je suis désolée pour ce steak. Ça n'aurait pas dû arriver.", "접니다, 손님. 스테이크 건은 죄송합니다. 이런 일이 없었어야 했어요."),
(P, "Madame, j'ai été boucher pendant quarante ans. J'en ai vu, des steaks !", "셰프님, 저는 40년 동안 정육점을 했어요. 스테이크는 질리도록 봤죠!"),
(H, "Alors vous êtes mon juge le plus sévère.", "그럼 가장 엄격한 심사위원이시네요."),
(P, "Celui-là est parfait. Et la réparation a été rapide. C'est le plus important.", "이건 완벽해요. 그리고 바로잡는 것도 빨랐고요. 그게 제일 중요해요."),
(P, "Une erreur, ça arrive. Ce qui compte, c'est comment on la répare.", "실수는 있을 수 있어요. 중요한 건 어떻게 바로잡느냐죠."),
(H, "C'est exactement ce que dit toujours mon père.", "우리 아버지가 늘 하시는 말씀이에요."),
(P, "Il a raison. Un conseil de boucher : sortez la viande une demi-heure avant.", "아버님 말씀이 맞아요. 정육점 주인으로서 조언 하나, 고기는 30분 전에 꺼내 두세요."),
(H, "On le fait, d'habitude. Ce soir, on était pressés. Ce n'est pas une excuse.", "보통은 그렇게 해요. 오늘 저녁은 시간에 쫓겼어요. 변명은 아니고요."),
(P, "Je vous crois. Le samedi soir, c'est le coup de feu, je sais.", "믿어요. 토요일 저녁은 전쟁터죠, 알아요."),
(J, "Monsieur, madame, pour finir, un dessert offert par la maison ?", "손님, 부인, 마무리로 가게에서 드리는 디저트는 어떠세요?"),
(P, "Avec plaisir, mais on n'a plus le temps. Le spectacle commence dans vingt minutes.", "기꺼이요, 하지만 시간이 없어요. 공연이 20분 뒤에 시작해요."),
(H, "Alors je vous prépare deux madeleines pour la route. Elles sont encore chaudes.", "그럼 가시는 길에 드시라고 마들렌 두 개 준비해 드릴게요. 아직 따뜻해요."),
(P, "Deux madeleines ! Vous gardez vos clients comme ça. On reviendra samedi prochain.", "마들렌 두 개라니! 이렇게 단골을 만드시는군요. 다음 주 토요일에 또 올게요."),
(C, "On vous attend avec plaisir. Bonne soirée et bon spectacle !", "기다리겠습니다. 즐거운 저녁 보내시고 공연 잘 보세요!"),
(None, "23 h 15. La salle est vide. Julien, Chloé et Hélène sont accoudés au comptoir.", "밤 11시 15분. 홀이 비었다. 쥘리앙, 클로에, 엘렌이 카운터에 팔꿈치를 괴고 있다."),
(C, "Julien, et si un client crie ? S'il est vraiment en colère ?", "쥘리앙, 손님이 소리를 지르면요? 정말 화가 났으면요?"),
(J, "On fait un jeu de rôle. Je suis un client grincheux, tu réponds. Prête ?", "역할극을 하자. 내가 까다로운 손님이고 네가 대답해. 준비됐어?"),
(J, "« Cette soupe est froide ! C'est inadmissible ! »", "« 이 수프 식었잖아요! 말도 안 돼요! »"),
(C, "Je suis désolée, monsieur. Je vous la réchauffe tout de suite.", "죄송합니다, 손님. 바로 데워 드리겠습니다."),
(J, "« Ça fait vingt minutes que j'attends ! »", "« 20분째 기다리고 있다고요! »"),
(C, "Vous avez raison, c'est trop long. Je m'en occupe immédiatement.", "맞는 말씀이세요, 너무 오래 걸렸어요. 즉시 처리하겠습니다."),
(J, "« Et ce n'est pas ce que j'ai commandé ! »", "« 게다가 제가 주문한 게 이게 아니에요! »"),
(C, "Pardon, je vérifie avec la cuisine. Un instant, je vous prie.", "죄송합니다, 주방에 확인하겠습니다. 잠시만 기다려 주세요."),
(J, "Très bien. Et si le client reste fâché ?", "좋아. 그래도 손님이 계속 화가 나 있으면?"),
(C, "Je vais chercher mon responsable. Je ne règle pas tout seule.", "책임자를 불러올게요. 혼자 다 해결하려 하지 않고요."),
(J, "Exactement. Et pour s'excuser, on varie. « Je suis désolé », « toutes mes excuses », « je suis navré ».", "맞아. 사과할 때는 표현을 바꿔. « 죄송합니다 », « 진심으로 사과드립니다 », « 유감입니다 »."),
(C, "« Navré », j'aime bien. C'est plus chic. Je le note !", "« Navré » 마음에 들어요. 더 세련됐어요. 적어 둘게요!"),
(C, "Julien, pourquoi le monsieur a dit « une semelle » ?", "쥘리앙, 그 손님은 왜 « 구두 밑창 » 이라고 했어요?"),
(J, "C'est une expression : une viande dure comme la semelle d'une chaussure.", "표현이야. 구두 밑창처럼 질긴 고기라는 뜻이지."),
(C, "Je peux l'utiliser ?", "저도 써도 돼요?"),
(J, "Jamais devant un client. Seulement entre nous, en cuisine.", "손님 앞에서는 절대 안 돼. 우리끼리, 주방에서만."),
(H, "Julien, merci d'avoir géré la table neuf.", "쥘리앙, 9번 테이블 잘 처리해 줘서 고마워."),
(J, "C'est mon boulot, patronne. Et ce n'était pas dramatique.", "제 일이잖아요, 사장님. 그리고 심각한 것도 아니었고요."),
(H, "Pour moi, si. Un steak gris, c'est une faute. Je parle à Karim demain matin, pas ce soir.", "나한테는 심각해. 회색 스테이크는 잘못이야. 카림이랑은 오늘 밤이 아니라 내일 아침에 얘기할 거야."),
(J, "Ton père va l'apprendre demain. Il a ses espions, non ?", "아버님이 내일 아시게 될 텐데요. 첩자가 있잖아요?"),
(H, "Évidemment. Il a même un espion au coin de la rue.", "당연하지. 길모퉁이에도 첩자가 있어."),
(C, "Il va prendre un savon ?", "혼나는 거예요?"),
(H, "Pas un savon. Une discussion. Il est bon, il lui faut juste une méthode.", "혼내는 게 아니라 대화야. 실력은 좋은데 방법이 필요한 거지."),
(H, "Dès mardi, on utilise une sonde. Cinquante degrés au cœur pour un saignant, cinquante-cinq pour un à point.", "화요일부터 탐침 온도계를 쓸 거야. 심부 50도면 레어, 55도면 미디엄."),
(C, "Cinquante et cinquante-cinq. Je le note aussi. J'ai déjà trois pages !", "50이랑 55. 이것도 적을게요. 벌써 세 쪽이에요!"),
(C, "Et si un client demande « bien cuit », c'est un crime ?", "손님이 « 웰던 » 을 주문하면 그건 범죄예요?"),
(H, "Non. Un steak bien cuit reste un steak. Pas une semelle !", "아니. 웰던도 스테이크는 스테이크야. 구두 밑창은 아니고!"),
(J, "Ton carnet a un nouveau chapitre : la cuisson.", "네 수첩에 새 장이 생겼네. 굽기."),
(H, "Tu as bien fait ce soir. Tu es restée calme, tu as regardé, tu as appris.", "오늘 잘했어. 침착했고, 지켜봤고, 배웠어."),
(C, "Merci, chef. Mais j'ai eu peur en portant l'assiette.", "감사합니다, 셰프. 그래도 접시를 나를 때 무서웠어요."),
(H, "Tout le monde a peur la première fois. Moi aussi, à ton âge, j'ai fait tomber trois assiettes de suite.", "누구나 처음엔 무서워해. 나도 네 나이 때 접시를 세 개 연달아 떨어뜨렸어."),
(J, "Quoi ? Toi ? Je ne te crois pas.", "뭐라고요? 사장님이요? 못 믿겠는데요."),
(H, "Ne le répétez à personne. Allez, on range. Il est minuit moins le quart.", "아무한테도 말하지 마. 자, 정리하자. 자정 15분 전이야."),
(J, "Dernier test avant de partir, Chloé. Un client veut une viande rose au centre. C'est quoi ?", "가기 전에 마지막 테스트야, 클로에. 손님이 가운데가 분홍색인 고기를 원해. 뭐지?"),
(C, "À point ! Et très rouge, presque crue, c'est bleu. Bonne nuit, tout le monde !", "아 푸앵이요! 아주 붉고 거의 날것이면 블뢰고요. 다들 안녕히 주무세요!"),
]

VOCAB = [
("A2", "Je suis désolé(e).", "죄송합니다.", "가장 기본적인 사과. 남성 désolé, 여성 désolée 모두 발음은 같다. 사과 뒤에 해결책을 붙인다."),
("A2", "trop cuit", "너무 익은", "trop + 형용사: 과함. ↔ pas assez cuit(덜 익은). Le steak est trop cuit."),
("A2", "saignant / à point / bien cuit", "레어 / 미디엄 / 웰던", "주문 시 « Quelle cuisson ? » 에 대한 대답. 중간 정도는 à point."),
("A2", "Vous avez raison.", "맞는 말씀이세요.", "손님의 불만을 인정하는 가장 쉬운 문장. ↔ 반대는 Vous vous trompez (피하기)."),
("A2", "offert par la maison", "가게에서 제공하는 (무료)", "[구어] « C'est pour la maison ». ↔ 정중: gracieusement offert par l'établissement."),
("A2", "tout de suite", "바로, 즉시", "해결책을 제안할 때의 단골 부사. = immédiatement."),
("A2", "Un instant, je vous prie.", "잠시만 기다려 주세요.", "손님을 기다리게 할 때. [구어] Une seconde ! ↔ 정중: Un instant, je vous prie."),
("A2", "Je vérifie avec la cuisine.", "주방에 확인해 볼게요.", "홀 직원이 즉답하지 않고 확인하겠다는 안전한 말."),
("A2", "des frites toutes chaudes", "갓 튀긴 뜨거운 감자튀김", "tout(e) 는 형용사 앞에서 강조 부사. toutes chaudes 처럼 여성 복수 앞에서는 일치."),
("B1", "bleu", "블뢰(거의 날것)", "스테이크 굽기에서 가장 덜 익힌 단계. 색의 bleu 와 철자가 같다."),
("B1", "Il paraît que...", "~라고 하던데요", "간접적으로 들은 정보를 말할 때. Il paraît qu'il y a un souci ?"),
("B1", "Je m'en occupe.", "제가 처리할게요.", "s'occuper de → en. 불만 접수 후 해결하겠다는 약속."),
("B1", "Le chef vous en refait un.", "셰프가 새로 만들어 드릴 거예요.", "refaire 는 '다시 만들다'. en = un steak 를 가리키는 대명사."),
("B1", "Ça arrive.", "그럴 수 있죠.", "[구어] 실수를 너그럽게 넘길 때. ↔ 정중: Cela peut arriver."),
("B1", "Merde.", "젠장.", "[속어] 놀랐거나 실수를 발견했을 때. 쓸 수 있음: 가까운 주방 동료 사이 / 금지: 손님·상사·외부인 앞. 이 화에서는 주방 안에서 엘렌만 한 번 사용."),
("B2", "Toutes mes excuses. / Je suis navré(e).", "진심으로 사과드립니다. / 유감입니다.", "désolé 보다 격식 있는 사과. 불만이 큰 손님에게 쓰면 효과적."),
("B2", "Ça n'aurait pas dû arriver.", "이런 일은 없었어야 했어요.", "조건법 과거: 책임을 인정하는 정중한 문장. devoir + 과거분사."),
("B2", "jeter un œil", "한번 살펴보다", "[구어] Je jette un œil. ↔ 정중: Je vais examiner cela."),
("B2", "une semelle", "구두 밑창 (질긴 고기)", "[구어] 질기고 맛없는 고기를 농담처럼. 손님이 먼저 말하면 웃어넘기고 공감한다."),
("B2", "le coup de feu", "가장 바쁜 시간(러시)", "주방과 홀이 몰리는 시간. 8화의 주제."),
("C1", "Ce qui compte, c'est comment on la répare.", "중요한 건 어떻게 바로잡느냐예요.", "강조 구문 ce qui ..., c'est ... 로 핵심을 짚는 속담 같은 말."),
("C1", "prendre un savon", "호되게 혼나다", "[구어] Il va prendre un savon ? ↔ 정중: Il va se faire réprimander ?"),
]

GRAM = [
("A2", "trop + 형용사 / pas assez + 형용사",
 "« Il est beaucoup trop cuit. » trop 는 '지나치게', « pas assez cuit » 는 '덜 익은'. beaucoup 를 앞에 붙이면 정도가 강해진다. 불만을 정확히 전달하는 가장 쉬운 틀이다."),
("A2", "굽기 어휘와 명령형",
 "bleu < saignant < à point < bien cuit. 대화 속 « Regarde. », « Donne-moi ta main. », « Touche le bas du pouce. », « Écoute le bruit », « Ne cours pas, souris. » 는 tu 에게 하는 명령형. vous 에게는 « Sortez la viande » 처럼 -ez."),
("A2", "사과 + 해결 제안의 3단 구조",
 "① 인정: « Vous avez raison. » ② 사과: « Je suis vraiment désolé. » ③ 해결: « Le chef vous en refait un. », « Je vous apporte un verre. » 불평을 받으면 이 순서로 말한다."),
("B1", "대명사 en — 수량·반복",
 "« Le chef vous en refait un. » en 은 앞에 나온 'un steak' 를 대신한다. 수량이 남을 때는 « un » 를 문장 끝에 둔다: « Il m'en faut sept. » (7분이 필요하다). 8화에서 대명사를 더 연습한다."),
("B1", "plus-que-parfait (대과거) — 이전의 일",
 "« Il l'avait demandé comment ? » « J'avais demandé un steak saignant. » « J'avais écrit saignant. » 문제가 생기기 전에 이미 말했거나 한 일을 이야기할 때. avoir/être 의 imparfait + 과거분사."),
("B1", "Il paraît que + 직설법",
 "« Il paraît qu'il y a un souci avec votre viande ? » 들은 것을 부드럽게 확인하는 방법. 직접적으로 « Vous avez un problème ? » 라고 묻는 것보다 덜 날카롭다."),
("B2", "조건법 과거 — 책임 인정",
 "« Ça n'aurait pas dû arriver. » devoir 조건법 과거는 '~했어야 했는데'. 진지한 사과 때 쓰고, 단순히 « Désolée » 라고만 하는 것보다 책임감을 더 보여 준다."),
]

READ = [
("é 와 ée — désolé / désolée",
 "« désolé » 와 « désolée » 는 발음이 같다 [de.zɔ.le]. 끝의 e 는 소리 나지 않고, 마지막 é 를 입꼬리를 올려 또렷하게. « Je suis vraiment désolée. » 는 « 주 쉬 브레망 데졸레 » 로, vraiment 의 r 를 목에서 가볍게."),
("gn — saignant, signe",
 "« saignant » 은 [sɛ.ɲɑ̃]. gn 은 '냐' 와 비슷한 구개음으로, 한 번에 붙여 읽는다. « Un saignant, deux à point, un bien cuit. » 처럼 세 덩어리로 끊어 연습."),
("u / ou — cuit, jus, rouge",
 "« cuit » 의 u 는 입술을 오므린 '위' 소리 + [i] 로 이어져 [kɥi]. « jus » [ʒy], « rouge » [ʁuʒ] 의 ou 는 '우'. « bien cuit » 와 « Où est le jus ? » 를 비교해 보자. u 와 ou 를 섞으면 뜻이 달라진다(dessus / dessous)."),
("리에종 — Toutes_mes_excuses",
 "« Toutes mes excuses. » 에서 mes_excuses 의 s 는 [z] 로 이어 읽어 « 뚜트 메제크스뀨즈 » 처럼. 사과 문장은 끝 억양을 부드럽게 내려 진심이 전해지게 한다."),
("호흡 구간 — 네 단계",
 "« Un : / on écoute. / Deux : / on s'excuse. / Trois : / on propose une solution. / Et quatre : / on remercie le client / de sa patience. » 번호 뒤에서 짧게 쉬고 마지막 구에서 천천히."),
("숫자 읽기 — cinquante, cinquante-cinq, vingt et un",
 "« Vingt et un euros » 는 « 벵 테 앵 외로 » 로 vingt 의 t 가 et 와 이어진다. « Cinquante degrés au cœur » 는 « 쎙깡트 드그레 조 뢰르 », 모음 앞에서 degrés_au 의 s 가 [z] 로 이어지는지 확인."),
("리듬과 감정 — 사과와 불평의 억양",
 "불평하는 손님: « Il est gris jusqu'au milieu. » 는 끝이 평평하거나 살짝 내려간다. 사과하는 직원: « Je suis vraiment désolé, monsieur. » 는 천천히, 낮은 목소리로. 감정에 따라 속도를 바꿔 읽으면 장면이 살아난다."),
]

CULTURE = [
("cuisson — 프랑스 사람들의 고기 굽기",
 "프랑스에서는 스테이크를 시킬 때 « Quelle cuisson ? » 라고 물어보는 것이 기본이고, 가장 흔한 주문은 saignant 와 à point 다. bleu 는 겉만 빠르게 지진 것으로 취향이 갈린다. « bien cuit » 도 정상적인 주문이므로 서버는 표정을 바꾸지 않는다. 안 물어보면 « À point » 로 나오는 경우가 많다."),
("불만을 풀어 주는 법 — 제스처",
 "프랑스 식당에서 불만이 생기면 서버는 변명하기보다 « Vous avez raison » 로 인정하고 새로 만들어 주는 것이 예의다. 시간이 걸리면 un verre offert 이나 작은 선물(un petit geste) 로 마음을 푼다. 손님도 « Ça arrive » 라고 받아 주면 서로 체면을 지킬 수 있다."),
]

META = dict(part=1, ep=6, part_label="제1부 Mise en place · 봄", title_fr="Le steak trop cuit", title_ko="너무 익은 스테이크",
 place="Le Comptoir de Marthe, 4월 25일 토요일 저녁 8시 35분 ~ 밤 11시 45분", chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · M. Perrin (9번 테이블, 은퇴한 정육점 주인)",
 wine="굽기를 잘못한 스테이크 불만과 사과·해결",
 focus="cuisson 어휘(bleu / saignant / à point / bien cuit), trop·pas assez, 사과와 해결 표현, 대명사 en 입문",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제7화 « Livraison du matin » : 아침 납품업자 바스티드가 가져온 재료를 검수하며 무게·가격을 비교한다")
