# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, K = "Hélène", "Julien", "Chloé", "Karim"
D = [
(None, "Jeudi, mi-mai, 12 h 05. Dans la cuisine, tout le monde est à son poste. Le premier ticket tombe.", "5월 중순 목요일 낮 12시 5분. 주방에서 모두 제 자리에 서 있다. 첫 주문서가 나온다."),
(H, "Bon, on y va. Karim, t'as tout ? Le cabillaud, les frites, la sauce ?", "자, 시작하자. 카림, 다 준비됐어? 대구, 감자튀김, 소스?"),
(K, "Oui, chef. Tout est prêt. La sauce est au chaud.", "네, 셰프. 다 준비됐어요. 소스도 따뜻하게 두었어요."),
(J, "Salle presque pleine ! Quatre tables déjà, et ça arrive encore.", "홀이 거의 찼어요! 벌써 네 테이블이고, 계속 들어오고 있어요."),
(H, "Parfait. Chloé, tu restes avec Julien en salle. Écoute-le bien.", "좋아. 클로에, 넌 홀에서 쥘리앵이랑 있어. 잘 들어."),
(C, "D'accord, chef. Je prends les assiettes au passe ?", "알겠어요, 셰프. 패스에서 접시를 가져가면 되나요?"),
(H, "Oui. Mais pas avant que je dise « envoyez ».", "응. 하지만 내가 '내보내'라고 하기 전에는 안 돼."),
(J, "Table sept, deux œufs mayo. Table neuf, un velouté, une salade de chèvre.", "7번 테이블, 달걀 마요 둘. 9번 테이블, 벨루테 하나, 염소 치즈 샐러드 하나."),
(H, "Deux œufs mayo, un velouté, une salade. Karim, tu les fais ?", "달걀 마요 둘, 벨루테 하나, 샐러드 하나. 카림, 네가 해?"),
(K, "Je prends les œufs. Le velouté, je te le passe.", "달걀은 제가 맡을게요. 벨루테는 셰프에게 넘길게요."),
(H, "Donne-le-moi. Et la salade, c'est Chloé qui la dresse.", "나한테 줘. 그리고 샐러드는 클로에가 담을 거야."),
(C, "Moi ? Mais je n'ai jamais...", "저요? 하지만 저는 한 번도..."),
(H, "Si, tu l'as déjà fait. Prends le pain, mets le fromage dessus, et passe-le au four.", "아니, 해 봤잖아. 빵 가져다 치즈를 올리고 오븐에 넣어."),
(C, "Le pain, le chèvre, le four. D'accord, j'y vais.", "빵, 염소 치즈, 오븐. 알겠어요, 갑니다."),
(K, "Attention, derrière toi ! Chaud, chaud !", "조심해, 네 뒤야! 뜨거워, 뜨거워!"),
(C, "Pardon ! Je n'ai pas vu.", "죄송해요! 못 봤어요."),
(H, "Ne reste pas au milieu. Mets-toi à gauche.", "가운데 서 있지 마. 왼쪽으로 가."),
(J, "Table douze : un steak-frites saignant, un à point, une blanquette.", "12번 테이블, 스테이크 프리트 레어 하나, 미디엄 하나, 블랑케트 하나."),
(H, "Reçu. Un saignant, un à point, une blanquette. Karim, la viande !", "접수. 레어 하나, 미디엄 하나, 블랑케트 하나. 카림, 고기!"),
(K, "Ça marche. Les steaks sont sur le feu.", "알겠습니다. 스테이크 올라갔어요."),
(H, "Dis-moi quand tu les retournes.", "뒤집을 때 말해."),
(K, "Je les retourne... maintenant.", "뒤집어요... 지금."),
(J, "Chef, la table trois demande si la blanquette est faite avec de la crème.", "셰프, 3번 테이블 손님이 블랑케트에 크림이 들어가는지 물어요."),
(H, "Oui, un peu. Mais dis-leur qu'on peut la faire sans.", "네, 조금요. 하지만 빼고도 만들 수 있다고 말해 드려."),
(J, "Je leur dis. Merci, chef.", "말씀드릴게요. 감사합니다, 셰프."),
(None, "Julien sort en salle et s'approche d'une table, tout sourire.", "쥘리앵이 홀로 나가 활짝 웃으며 한 테이블에 다가간다."),
(J, "Madame, monsieur, la blanquette est préparée avec un peu de crème. Mais nous pouvons la faire sans, bien sûr.", "손님, 블랑케트에는 크림이 조금 들어갑니다. 하지만 빼고도 해 드릴 수 있어요, 물론."),
(J, "Très bien, madame. Je préviens la cuisine. Un instant, je vous prie.", "알겠습니다, 손님. 주방에 알리겠습니다. 잠시만 기다려 주세요."),
(None, "Il revient en cuisine d'un pas rapide, le sourire disparu.", "그는 미소가 사라진 채 빠른 걸음으로 주방에 돌아온다."),
(J, "Blanquette sans crème, table trois. Merde, y a déjà vingt minutes d'attente sur la sept !", "3번 테이블 크림 뺀 블랑케트요. 젠장, 7번은 벌써 20분이나 기다렸어요!"),
(H, "J'ai les œufs mayo ! Karim, envoie-les !", "달걀 마요 나왔어! 카림, 내보내!"),
(K, "Envoyés ! Chloé, prends-les et porte-les à la sept.", "나갔어! 클로에, 가져가서 7번에 가져다줘."),
(C, "Les œufs... table sept. J'y vais !", "달걀... 7번 테이블. 갑니다!"),
(J, "Attends, Chloé. Les deux assiettes, tu les tiens bien ? Ne cours pas.", "잠깐, 클로에. 접시 둘 제대로 잡았어? 뛰지 마."),
(C, "Oui, oui. Je marche vite, c'est tout.", "네, 네. 빨리 걷는 것뿐이에요."),
(H, "Putain, Karim, le jus ! Il bout !", "젠장, 카림, 소스! 끓어 넘쳐!"),
(K, "Merde ! Je le baisse ! Je le baisse !", "젠장! 줄여요! 줄여요!"),
(H, "Goûte. Il n'est pas brûlé ?", "맛봐. 타지 않았어?"),
(K, "Non, ça va. Il est juste un peu plus réduit.", "아니요, 괜찮아요. 조금 더 졸여졌을 뿐이에요."),
(H, "OK. Ajoute un peu d'eau. Pas trop.", "알았어. 물을 조금 넣어. 너무 많이는 말고."),
(K, "J'en mets deux cuillères. Voilà.", "두 숟가락 넣을게요. 됐어요."),
(J, "Cuisine ! Nouvelle table de six qui n'a pas réservé. Je les prends ?", "주방! 예약 안 한 여섯 명 손님이 새로 왔어요. 받을까요?"),
(H, "Six ? Maintenant ? Où tu vas les mettre ?", "여섯이요? 지금? 어디에 앉히려고?"),
(J, "Sur la terrasse. Il fait beau, ils sont d'accord.", "테라스에요. 날씨가 좋아서 손님들도 괜찮대요."),
(H, "OK, prends-les. Mais dis-leur que le steak, c'est vingt minutes.", "알았어, 받아. 하지만 스테이크는 20분 걸린다고 말해."),
(J, "Je leur dis. Et je leur apporte du pain tout de suite.", "그렇게 말할게요. 그리고 빵을 바로 가져다드릴게요."),
(H, "Bonne idée. Donne-leur aussi un pichet d'eau.", "좋은 생각이야. 물 한 주전자도 드려."),
(H, "Table neuf, la salade. Chloé, tu l'as ?", "9번 테이블, 샐러드. 클로에, 네가 갖고 있어?"),
(C, "Le fromage est dans le four. Il est pas encore doré.", "치즈는 오븐에 있어요. 아직 노릇하지 않아요."),
(H, "Attends. Ne le sors pas trop tôt, ne le laisse pas non plus trop longtemps.", "기다려. 너무 일찍 꺼내지도, 너무 오래 두지도 마."),
(C, "Trente secondes encore ?", "30초만 더요?"),
(H, "Oui. Regarde-le, il doit être doré. Pas brun, doré.", "응. 잘 봐, 노릇해야 해. 갈색 말고 노릇하게."),
(C, "Il est doré ! Je le sors !", "노릇해졌어요! 꺼낼게요!"),
(H, "Pose-le sur la salade. Verse un peu de miel. Pas beaucoup !", "샐러드 위에 올려. 꿀을 조금 뿌려. 많이는 말고!"),
(C, "Voilà. Comme ça ?", "자요. 이렇게요?"),
(H, "Parfait. Passe-moi un chiffon pour le bord de l'assiette.", "완벽해. 접시 가장자리 닦게 행주 줘."),
(C, "Tenez, chef. Un chiffon propre.", "여기요, 셰프. 깨끗한 행주예요."),
(H, "Merci. Une assiette sale, ça ne sort jamais. Retiens ça.", "고마워. 더러운 접시는 절대 내보내지 않아. 기억해."),
(C, "Je m'en souviendrai. Je la donne à Julien ?", "기억할게요. 쥘리앵에게 줄까요?"),
(H, "Oui, apporte-la-lui. Il l'attend au passe.", "응, 그에게 가져다줘. 패스에서 기다리고 있어."),
(J, "Table neuf, la salade. Merci, Chloé. T'es rapide, finalement !", "9번 테이블 샐러드. 고마워, 클로에. 너 빠르네, 의외로!"),
(C, "Merci, Julien. Mais j'ai les mains qui tremblent.", "고마워요, 쥘리앵. 근데 손이 떨려요."),
(J, "Respire. Ça va aller. Ce n'est qu'un déjeuner.", "숨 쉬어. 괜찮을 거야. 그냥 점심일 뿐이야."),
(K, "Chef, les frites sont presque finies. J'en refais ?", "셰프, 감자튀김이 거의 다 떨어졌어요. 더 만들까요?"),
(H, "Oui, refais-en. Mets-en deux grandes poignées.", "응, 더 만들어. 두 움큼 가득."),
(K, "Je les lance. Trois minutes.", "넣을게요. 3분이요."),
(J, "Cuisine, le steak de la douze ! Ils attendent depuis vingt minutes !", "주방, 12번 스테이크요! 20분째 기다리고 계세요!"),
(H, "Il est là. Un saignant, un à point. Goûte la sauce, Julien.", "여기 있어. 레어 하나, 미디엄 하나. 소스 맛봐, 쥘리앵."),
(J, "Pas le temps, chef. Je vous fais confiance.", "시간 없어요, 셰프. 믿습니다."),
(H, "Alors vérifie la cuisson. Coupe-le un peu et regarde.", "그럼 익힘을 확인해. 조금 잘라서 봐."),
(J, "Rose à l'intérieur. C'est bon pour le saignant. Et l'autre, à point.", "안쪽이 분홍색이에요. 레어로 좋아요. 다른 건 미디엄이고요."),
(H, "Alors envoie-les. Dépêche-toi.", "그럼 내보내. 서둘러."),
(J, "Voilà, messieurs-dames. Un steak saignant, un à point. Bon appétit.", "자, 손님들. 레어 스테이크 하나, 미디엄 하나입니다. 맛있게 드세요."),
(J, "Excusez-nous pour l'attente. Nous avons beaucoup de monde aujourd'hui.", "기다리게 해서 죄송합니다. 오늘은 손님이 많으세요."),
(K, "Chef, il me manque un œuf mayo ! La sept en a demandé trois, pas deux !", "셰프, 달걀 마요 하나가 모자라요! 7번 테이블은 둘이 아니라 셋을 시켰어요!"),
(H, "Quoi ? Julien a dit deux.", "뭐? 쥘리앵은 둘이라고 했는데."),
(C, "Pardon, c'est moi. J'ai mal compris. Le monsieur a dit trois, pas deux.", "죄송해요, 제 잘못이에요. 잘못 들었어요. 손님이 둘이 아니라 셋이라고 하셨어요."),
(H, "OK. On corrige. Karim, fais-en un autre.", "알았어. 고치자. 카림, 하나 더 만들어."),
(K, "Un œuf mayo, vite fait. Je te le passe dans deux minutes.", "달걀 마요 하나, 후딱 할게요. 2분 뒤에 넘길게요."),
(C, "Je vais m'excuser auprès du client.", "손님께 사과드리러 갈게요."),
(H, "Non. D'abord, tu me regardes. Pas de panique, c'est une petite erreur.", "아니. 먼저 나를 봐. 당황하지 마, 작은 실수야."),
(H, "Retiens la phrase : « Vous me répétez la commande, s'il vous plaît ? ». Tu la dis à chaque fois.", "이 문장을 기억해. '주문을 다시 말씀해 주시겠어요?' 매번 말하는 거야."),
(C, "« Vous me répétez la commande, s'il vous plaît ? » D'accord. Je la note.", "'주문을 다시 말씀해 주시겠어요?' 알겠어요. 적어 둘게요."),
(H, "Plus tard. Là, tu portes le plateau de la quatre.", "나중에. 지금은 4번 테이블 쟁반을 날라."),
(C, "Les deux plats du jour et le velouté. J'y vais.", "오늘의 요리 둘이랑 벨루테요. 갑니다."),
(K, "Ne cours pas ! Le sol est mouillé devant l'évier !", "뛰지 마! 싱크대 앞 바닥이 젖었어!"),
(C, "Merci, je vois ! J'évite !", "고마워요, 보여요! 피할게요!"),
(H, "Putain, les gars, on est dans la galère aujourd'hui.", "젠장, 얘들아, 오늘 진짜 정신없다."),
(K, "Ouais, c'est chaud. Mais ça passe.", "네, 후끈하네요. 그래도 돌아가요."),
(H, "Ça passe parce qu'on se parle. Continuez à crier, c'est bien.", "서로 말하니까 돌아가는 거야. 계속 외쳐, 좋아."),
(J, "Chef, la table trois est contente ! La blanquette sans crème leur plaît.", "셰프, 3번 테이블 손님이 만족해요! 크림 뺀 블랑케트가 마음에 든대요."),
(H, "Bien. Dis-leur merci de ma part.", "좋아. 내 대신 고맙다고 전해 줘."),
(J, "Je leur dirai. Ah, table huit, un dessert : une mousse au chocolat et une crème brûlée.", "전할게요. 아, 8번 테이블 디저트요. 초콜릿 무스 하나, 크렘 브륄레 하나."),
(H, "Karim, la crème brûlée, c'est toi. Passe-moi le chalumeau.", "카림, 크렘 브륄레는 네 거야. 토치 줘."),
(K, "Le voilà. Fais attention, il est chaud.", "여기 있어요. 조심하세요, 뜨거워요."),
(H, "Je sais. Merci, ça fait quinze ans que je m'en sers.", "알아. 고마워, 15년 동안 써 왔어."),
(None, "Le bruit baisse peu à peu. Il est 13 h 50.", "소음이 조금씩 줄어든다. 오후 1시 50분."),
(J, "Cuisine ! Dernier ticket. Table onze, deux cafés et une tarte Tatin.", "주방! 마지막 주문서요. 11번 테이블, 커피 둘, 타르트 타탱 하나."),
(H, "Tatin, c'est moi. Karim, les cafés ?", "타탱은 내가 할게. 카림, 커피는?"),
(K, "Les cafés, c'est Julien qui les fait.", "커피는 쥘리앵이 해요."),
(J, "Oui, je m'en occupe. Chloé, tu viens avec moi ?", "네, 제가 맡을게요. 클로에, 같이 갈래?"),
(C, "J'arrive ! Je prends les petites cuillères.", "갈게요! 티스푼 가져갈게요."),
(None, "14 h 20. La cuisine se vide. Hélène éteint le feu.", "오후 2시 20분. 주방이 비어 간다. 엘렌이 불을 끈다."),
(H, "Bon. C'est fini pour ce midi. Quatre-vingt-douze couverts. C'est bien.", "자. 오늘 점심은 끝이야. 92명이 왔어. 잘했어."),
(K, "Quatre-vingt-douze ! Et j'ai pas mangé depuis ce matin.", "92명이라니! 저는 오늘 아침부터 아무것도 못 먹었어요."),
(J, "Moi non plus. J'ai la tête qui tourne.", "저도요. 머리가 빙빙 돌아요."),
(C, "Moi, j'ai les jambes en coton. Mais c'était incroyable.", "저는 다리가 솜 같아요. 하지만 정말 놀라웠어요."),
(H, "Asseyez-vous. Karim, sers-leur de l'eau. Je prépare le repas du personnel.", "앉아. 카림, 물을 따라 줘. 직원 식사는 내가 준비할게."),
(K, "Chef, laissez-moi faire. Vous avez assez travaillé.", "셰프, 제가 할게요. 충분히 일하셨어요."),
(H, "Non, assieds-toi. Et dis-moi ce qu'on peut améliorer.", "아니, 앉아. 그리고 뭘 개선할 수 있을지 말해 봐."),
(K, "Franchement ? Moins de frites dans la panique. On en a refait deux fois.", "솔직히요? 정신없을 때 감자튀김을 줄이는 거요. 두 번이나 다시 했어요."),
(J, "Et il faut mieux noter les commandes en salle. Chloé a mal compris pour la sept.", "그리고 홀에서 주문을 더 잘 적어야 해요. 클로에가 7번을 잘못 들었잖아요."),
(C, "Je sais. Je m'excuse encore, chef.", "알아요. 다시 한 번 죄송해요, 셰프."),
(H, "Arrête de t'excuser, Chloé. Tu as fait ton premier vrai coup de feu.", "그만 사과해, 클로에. 넌 첫 진짜 피크를 해냈어."),
(C, "Et ça va toujours être comme ça ?", "그런데 항상 이런가요?"),
(H, "Oui, deux fois par jour. Tu vas vite t'y habituer.", "응, 하루에 두 번. 금방 익숙해질 거야."),
(K, "Au début, j'avais peur, moi aussi. Maintenant, j'aime ça.", "처음엔 저도 무서웠어요. 지금은 좋아해요."),
(J, "Tu adores ça, oui. T'es un adrénaline-addict.", "너 이거 엄청 좋아하잖아. 아드레날린 중독자야."),
(C, "Ça m'étonnerait que j'aime ça un jour !", "내가 언젠가 이걸 좋아하게 될 거라곤 상상이 안 돼요!"),
(H, "Tu verras. Allez, mangez. On a une heure avant de refaire la salle pour ce soir.", "두고 봐. 자, 먹어. 저녁 홀 세팅까지 한 시간 있어."),
(K, "Merci, chef. Tout le monde a bien bossé aujourd'hui.", "고마워요, 셰프. 오늘 다들 정말 열심히 했어요."),
(H, "Oui. Et demain, on recommence. Passez-moi le pain.", "응. 그리고 내일 또 시작이야. 빵 좀 줘."),
(J, "Chef, un dernier truc : la table trois a laissé un petit mot sur l'addition.", "셰프, 마지막으로 하나요. 3번 테이블이 계산서에 쪽지를 남겼어요."),
(H, "Lis-le-moi.", "읽어 줘."),
(J, "« Merci pour la blanquette sans crème. On reviendra. » Et ils ont signé.", "'크림 뺀 블랑케트 고맙습니다. 또 올게요.' 서명도 했어요."),
]

VOCAB = [
("A2", "Le coup de feu.", "점심·저녁 피크 타임", "주방 용어. 직역하면 '총소리'. 손님이 몰려 가장 바쁜 시간대를 가리킨다. « Il est midi, c'est le coup de feu. »"),
("A2", "Ça marche. / Reçu. / Oui, chef !", "알겠습니다. / 접수했습니다. / 네, 셰프!", "주방에서 지시를 받았다는 확인. Oui, chef!는 상하 관계가 분명한 주방의 인사."),
("A2", "un ticket / le passe / la salle", "주문서 / 패스(요리 내보내는 선반) / 홀", "주방-홀을 잇는 기본 어휘. le passe 위에 접시를 올려 홀 직원이 가져간다."),
("A2", "saignant / à point / bien cuit", "레어 / 미디엄 / 웰던", "고기 익힘. 6화에서 배운 어휘를 여기서 다시 사용. 홀에서 주문받을 때 반드시 확인한다."),
("A2", "Attention, derrière toi ! Chaud !", "조심, 네 뒤야! 뜨거워!", "주방 안전 외침. 뜨거운 것이나 칼을 들고 지나갈 때 큰 소리로 알린다."),
("A2", "Envoie-les ! / Prends-les ! / Porte-les à la sept.", "내보내! / 가져가! / 7번에 가져다줘.", "tu 명령법 + 대명사 (동사 뒤 하이픈). 긍정 명령에서는 대명사가 뒤에 온다."),
("A2", "Dépêche-toi. / Vite ! / Ne cours pas !", "서둘러. / 빨리! / 뛰지 마!", "se dépêcher의 명령형은 dépêche-toi. 부정 명령은 ne ... pas로 동사를 감싼다."),
("A2", "Donne-le-moi. / Passe-moi le chiffon.", "그거 나한테 줘. / 행주 줘.", "« Donne-le-moi » 처럼 직접 대명사(le) 다음에 간접 대명사(moi). passer à qn = 건네주다."),
("B1", "J'en mets deux cuillères. / Mets-en un peu.", "그걸 두 숟가락 넣을게. / 조금 넣어.", "대명사 en = 부분(양)을 가리킴. 명령형에서는 « Mets-en » 처럼 s가 다시 붙는다. (en 앞에서 liaison)"),
("B1", "[구어] Ça passe. ↔ 정중: Cela se déroule bien.", "그럭저럭 돌아가요.", "일이 문제없이 진행될 때. « Ça passe parce qu'on se parle. »"),
("B1", "un couvert", "(식당에서) 한 사람분의 자리·손님 한 명", "« Quatre-vingt-douze couverts » = 손님 92명분. 식당 업계의 인원 세는 단위."),
("B1", "[구어] Je m'en occupe. ↔ 정중: Je prends cela en charge.", "제가 맡을게요.", "s'occuper de qc + en 대명사. 일을 떠맡을 때 간단히."),
("B1", "[구어] J'ai les jambes en coton. ↔ 정중: Je suis très fatigué.", "다리가 풀려요.", "피곤해서 다리에 힘이 없을 때. avoir les jambes en coton = 다리가 솜 같다."),
("B1", "Vous me répétez la commande, s'il vous plaît ?", "주문을 다시 말씀해 주시겠어요?", "손님 앞에서 확인할 때의 정중한 표현. 현재형 의문문으로 정중하게 요청하는 구어체 형태."),
("B2", "[속어] Putain ! / Merde !", "젠장! / 제길!", "[속어] 놀라거나 당황했을 때 나오는 가벼운 욕. 쓸 수 있음: 가까운 주방 동료 사이 / 금지: 손님·상사·외부인 앞. 홀에서 손님 앞에서는 절대 쓰지 않는다."),
("B2", "[속어] C'est chaud.", "상황이 뜨거워, 정신없다.", "[속어] 뜨거운 주방과 바쁜 상황을 겹쳐 쓰는 말. 쓸 수 있음: 동료 사이 / 금지: 손님 앞. 정중: C'est très animé."),
("B2", "On est dans la galère.", "엉망진창이다, 힘든 상황이다.", "[속어] une galère = 고생스러운 상황. 쓸 수 있음: 직원끼리 / 금지: 손님 앞. 정중: La situation est difficile."),
("B2", "Tu es un adrénaline-addict.", "너는 아드레날린 중독자야.", "[구어] 영어 차용어 addict. 일상에서 '~에 푹 빠진 사람'을 뜻하는 유행어."),
("B1", "Je vous fais confiance.", "믿습니다, 맡길게요.", "faire confiance à qn = ~를 신뢰하다. 상급자가 부하에게, 혹은 동료끼리 책임을 넘길 때. 낭독 시 [페 콩피양스]."),
("C1", "Ça m'étonnerait que j'aime ça un jour.", "내가 언젠가 이걸 좋아하게 될 거라곤 생각 못 해.", "Ça m'étonnerait que + 접속법 = ~일 것 같지 않다. 구어에서 확신 없을 때 부드럽게 반박."),
]

GRAM = [
("A2", "긍정 명령형 (tu)", "« Prends les assiettes. » « Écoute-le bien. » « Dépêche-toi. » 주방에서 가장 많이 쓰는 문형. -er 동사는 s가 없다 (Pose, Goûte, Donne). être, avoir 같은 불규칙: Sois calme."),
("A2", "부정 명령형 ne ... pas", "« Ne cours pas ! » « Ne reste pas au milieu. » « Ne le sors pas trop tôt. » 동사 앞뒤를 ne/pas로 감싼다. 대명사는 부정 명령에서는 동사 앞으로 돌아간다: Ne le sors pas."),
("B1", "대명사와 명령형 (긍정: 동사 뒤)", "« Donne-le-moi. » « Apporte-la-lui. » « Passe-moi un chiffon. » 긍정 명령에서는 동사-대명사 순서, 하이픈으로 연결. 직접(le/la/les)이 먼저, 간접(moi/lui/leur)이 나중. moi는 대명사가 하나뿐일 때 me가 아닌 moi를 쓴다."),
("B1", "직접 대명사 le / la / les", "« Envoie-les ! » « Prends-les et porte-les à la sept. » « Je les retourne... maintenant. » 앞에 나온 명사를 되풀이하지 않기 위한 대체어. 문장 안에서는 동사 앞, 명령형에서는 동사 뒤."),
("B1", "간접 대명사 lui / leur", "« Dis-leur que le steak, c'est vingt minutes. » « Donne-leur de l'eau. » à + 사람을 대체한다. lui = 한 사람(그에게/그녀에게), leur = 여러 사람(그들에게). « Je leur dis. »"),
("B1", "대명사 en", "« J'en mets deux cuillères. » « Mets-en un peu. » « Refais-en. » 〈de + 명사〉 부분을 대신한다. 수량(deux, un peu)을 남기고 명사만 대체. 명령형에서는 « Mets-en » 처럼 s가 붙고 liaison이 생긴다."),
("B1", "단문 지시와 확인 (Reçu, Ça marche)", "주방에서는 길게 말하지 않는다. 지시: « Karim, la viande ! » 확인: « Reçu. » « Ça marche. » « Envoyés ! » 동사를 생략한 명사문이 자연스럽다. 홀에서는 « Bien sûr, madame » 로 정중하게 전환."),
]

READ = [
("호흡 구간 — 주문 읽기", "« Table sept, / deux œufs mayo. » « Table neuf, / un velouté, / une salade de chèvre. » 쉼표마다 짧게 끊고 숫자는 또렷하게. 주방에서는 숨을 쉬지 않고 읽는 느낌으로 속도감을 낸다."),
("명령형 억양 — 짧고 단호하게", "« Envoie-les ! » [앙브와-레] / « Dépêche-toi. » 문장 끝을 내리고 힘을 뺀다. 명령은 끝을 올리지 않는다. 반대로 확인 질문 « Tu les fais ? » 는 끝을 올린다."),
("리에종 — mets-en, refais-en", "« Mets-en deux grandes poignées. » 에서는 en 앞에서 [z] 소리가 생긴다: 「메-장」. « Refais-en. » 는 「르페장」으로 똑같이 이어 읽는다. « Donne-leur de l'eau. » 는 이어 읽지 않는다. « Allez, mangez » 는 [알레 몽제]."),
("엘리종 — j'en, t'es, y a", "« J'en mets deux cuillères. » « T'es rapide, finalement ! » « y a déjà vingt minutes d'attente » 구어에서 je/tu/il y a의 모음이 줄어든다. 작은 소리를 놓치지 말고 한 덩어리로."),
("r 소리 — rapide, refais, retourne", "« T'es rapide. » « Refais-en. » « Je les retourne. » 혀끝을 아래 이빨 뒤에 두고 목 안쪽에서 r 소리. 빠르게 말할 때 r이 약해지지 않게 연습."),
("u / ou — dessus, tourne, tout", "« Mets le fromage dessus. » « J'ai la tête qui tourne. » « Tout est prêt. » dessus [드쉬] 의 u는 입술을 둥글게, tourne/tout의 ou [우]와 구분. 연속해서 읽어 보면 차이가 드러난다."),
("비음 — attendre, bien, maintenant", "« Attends. » 「아땅」 / « Bien sûr » 「비앵 쉬르」 / « Maintenant » 「맹뜨낭」. an/en [앙], in/ain [앵], on [옹] 을 입으로 하지 않고 코로 울려서 구분한다. 빠르게 말해도 비음이 사라지지 않도록."),
]

CULTURE = [
("la brigade — 주방의 위계", "프랑스 레스토랑 주방은 chef (셰프), sous-chef (부주방장), commis (보조) 로 이루어진 brigade (조) 로 일한다. 지시를 받으면 « Oui, chef ! » 로 답하는 것이 관행이다. 짧고 군대식인 말투는 불친절해서가 아니라, 바쁜 시간에 오해를 줄이기 위한 약속이다. 이 화의 속어는 주방 동료 사이에서만 쓰이고, 홀에 나가면 곧바로 정중한 말투로 전환한다."),
("le service continu와 les couverts", "프랑스에서는 점심 피크가 12시~14시경 몰리고, 손님 수를 les couverts 로 센다. 바쁜 날 주방의 속도는 하루 두 번의 coup de feu (점심, 저녁) 로 결정되며, 홀 직원은 주문을 정확히 주방에 전달하는 것이 가장 중요한 임무다."),
]

META = dict(part=1, ep=8, part_label="제1부 Mise en place · 봄", title_fr="Le coup de feu", title_ko="점심 피크 타임",
 place="Le Comptoir de Marthe, 주방과 홀 · 5월 중순 목요일 낮 12시 5분 ~ 14시 20분",
 chars="Hélène Marchand (셰프·주인) · Karim Haddad (부주방장) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버)",
 wine="점심 피크 타임: 주방과 홀 사이의 빠른 단문 지시",
 focus="tu 명령형(긍정·부정) · 목적대명사 le/la/les · lui/leur · en · 단문 확인(Reçu, Ça marche)",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제9화 « L'addition, s'il vous plaît » : 계산 장면, 더치페이와 결제 오류, 팁 문화")
