# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
J, C, G, P = "Julien", "Chloé", "M. Garnier", "Mme Perrin"
D = [
(None, "Samedi, début juin, 14 h 05. Le service du midi se termine. Derrière le comptoir, Julien montre la caisse à Chloé.", "6월 초 토요일 오후 2시 5분. 점심 영업이 끝나 간다. 카운터 뒤에서 쥘리앵이 클로에에게 계산대를 보여 준다."),
(J, "Regarde, Chloé. Table cinq, ils lèvent la main. Ils veulent l'addition.", "봐, 클로에. 5번 테이블이 손을 들었어. 계산서를 달라는 거야."),
(C, "Moi, j'y vais ? C'est la première fois que j'encaisse.", "제가 가요? 계산받는 건 이번이 처음인데요."),
(J, "Oui. Je suis juste derrière toi. D'abord, tu imprimes la note.", "응. 바로 뒤에 있을게. 먼저 계산서를 뽑아."),
(C, "Table cinq... voilà. Cent vingt-quatre euros, c'est ça ?", "5번 테이블... 됐어요. 124유로, 맞나요?"),
(J, "Oui. Quatre formules, deux pichets, quatre cafés. Va leur apporter.", "응. 포뮬 네 개, 피처 두 개, 커피 넷. 가져다드려."),
(C, "Je la pose comment ? Dans une petite assiette ?", "어떻게 놓아요? 작은 접시에요?"),
(J, "Dans le petit carnet noir, face cachée. Et tu dis : « Voilà l'addition. »", "작은 검은 수첩에 뒷면이 보이게. 그리고 '계산서 여기 있습니다'라고 해."),
(C, "Face cachée ? Pourquoi ?", "뒷면이 보이게요? 왜요?"),
(J, "Par discrétion. Les autres tables n'ont pas besoin de voir le prix.", "배려야. 다른 테이블이 가격을 볼 필요는 없잖아."),
(None, "Chloé apporte le carnet à la table cinq.", "클로에가 5번 테이블에 수첩을 가져간다."),
(C, "Voilà l'addition, messieurs-dames. Cent vingt-quatre euros.", "계산서 여기 있습니다, 손님들. 124유로입니다."),
(G, "Merci, mademoiselle. Dites-moi, on peut payer séparément ?", "고마워요, 아가씨. 근데 따로 계산해도 되나요?"),
(C, "Séparément ? Euh... oui, bien sûr. Je pense.", "따로요? 어... 네, 물론이죠. 아마도요."),
(P, "Non, non, on partage en quatre, c'est plus simple. Trente et un euros chacun.", "아니, 아니, 넷이 나누는 게 더 간단해요. 한 사람당 31유로예요."),
(G, "Moi, je préfère payer ce que j'ai pris. J'ai bu deux verres de vin, ils n'ont bu que de l'eau.", "저는 제가 먹은 것만 내고 싶은데요. 저는 와인을 두 잔 마셨고, 저 사람들은 물만 마셨어요."),
(P, "Ça fait quand même trois euros de différence, Hervé !", "그래봤자 차이는 3유로예요, 에르베!"),
(C, "Je vais demander à mon collègue. Un instant, s'il vous plaît.", "동료에게 물어볼게요. 잠시만 기다려 주세요."),
(None, "Chloé revient au comptoir en courant.", "클로에가 카운터로 뛰어 돌아온다."),
(C, "Julien ! Ils veulent payer séparément. Enfin, pas tous. Je ne comprends plus rien.", "쥘리앵! 따로 내고 싶대요. 아니, 전부는 아니고요. 이제 하나도 모르겠어요."),
(J, "Calme-toi. On fait simple : deux tickets. Un pour monsieur Garnier, un pour les trois autres.", "진정해. 간단하게 하자. 계산서 두 장. 한 장은 가르니에 씨, 한 장은 나머지 셋."),
(C, "D'accord. Je retire le vin de la note de monsieur Garnier ?", "알겠어요. 가르니에 씨 계산서에서 와인을 빼요?"),
(J, "Non, l'inverse. Tu mets son vin sur son ticket. Le reste est partagé en trois.", "아니, 반대야. 그분의 와인은 그분 계산서에 넣어. 나머지는 셋이 나누고."),
(C, "Et ça fait combien pour chacun ?", "그럼 각자 얼마예요?"),
(J, "Prends la calculatrice. Cent vingt-quatre moins dix-huit pour le vin, ça fait cent six.", "계산기 써. 124에서 와인 18을 빼면 106이야."),
(C, "Cent six divisé par quatre... vingt-six euros cinquante. Plus le vin pour lui : trente-cinq cinquante.", "106을 넷으로 나누면... 26유로 50이에요. 그분은 와인값을 더해서 35유로 50이고요."),
(J, "Presque. Le vin, c'était dix-huit euros pour les deux pichets. Il en a bu la moitié, donc neuf.", "거의 맞아. 와인은 피처 두 개에 18유로였어. 반 마셨으니까 9유로야."),
(C, "Ah oui ! Donc vingt-six cinquante plus neuf : trente-cinq cinquante. C'est ce que j'ai dit.", "아, 맞네요! 26유로 50 더하기 9유로는 35유로 50. 제가 말한 대로예요."),
(J, "Bravo. Tu avais raison, c'est moi qui me suis trompé. Va le leur dire.", "잘했어. 네 말이 맞았어, 내가 틀렸네. 가서 말씀드려."),
(None, "Chloé retourne à la table.", "클로에가 테이블로 돌아간다."),
(C, "C'est possible, monsieur. Vous payez trente-cinq euros cinquante, les autres vingt-six cinquante.", "가능합니다, 손님. 35유로 50 내시고, 나머지 분들은 26유로 50씩입니다."),
(G, "Parfait. Je commence. Je peux payer par carte ?", "좋아요. 제가 먼저 낼게요. 카드로 되나요?"),
(C, "Oui, bien sûr. Je vous apporte le terminal.", "네, 물론이죠. 단말기를 가져다 드릴게요."),
(None, "Elle revient avec le terminal de paiement et tape le montant.", "그녀가 결제 단말기를 가져와 금액을 입력한다."),
(C, "Voilà, monsieur. Vous pouvez insérer votre carte.", "자, 손님. 카드를 꽂아 주세요."),
(G, "Attendez... Euh, mademoiselle, il y a écrit « trois cent cinquante euros ».", "잠깐만... 어, 아가씨, 여기 '350유로'라고 적혀 있는데요."),
(C, "Quoi ?! Oh non. J'ai oublié la virgule. Pardon, pardon !", "뭐라고요?! 아 이런. 소수점을 빼먹었어요. 죄송해요, 죄송해요!"),
(G, "Pas de problème, je n'ai rien tapé encore. On annule ?", "괜찮아요, 아직 아무것도 안 눌렀어요. 취소할까요?"),
(C, "Oui, oui, j'appuie sur « annulation ». Voilà, la transaction a été annulée.", "네, 네, '취소'를 누를게요. 됐어요, 거래가 취소되었습니다."),
(C, "Je recommence. Trente-cinq euros cinquante, avec la virgule cette fois.", "다시 할게요. 35유로 50, 이번엔 소수점 포함해서요."),
(G, "Cette fois, c'est bon. Je tape mon code.", "이번엔 맞아요. 비밀번호를 누를게요."),
(None, "Le terminal bipe. L'écran affiche « Paiement accepté ». Le ticket sort.", "단말기가 삑 소리를 낸다. 화면에 '결제 승인'이 뜨고 영수증이 나온다."),
(G, "Voilà, c'est réglé. Gardez la monnaie.", "자, 계산 끝났어요. 거스름돈은 가지세요."),
(C, "Il n'y a pas de monnaie, monsieur. Vous avez payé par carte.", "거스름돈은 없어요, 손님. 카드로 결제하셨잖아요."),
(G, "Ha ha, c'est vrai ! Alors je laisse un petit pourboire en espèces. Tenez, deux euros.", "하하, 맞네요! 그럼 현금으로 팁을 조금 남길게요. 여기, 2유로."),
(C, "Merci beaucoup, monsieur. C'est très gentil.", "정말 감사합니다, 손님. 친절하시네요."),
(P, "À mon tour. Je paie par carte, moi aussi. Vingt-six euros cinquante.", "이제 제 차례예요. 저도 카드로 낼게요. 26유로 50."),
(None, "Mme Perrin insère sa carte. Le terminal affiche un message d'erreur.", "페렝 부인이 카드를 꽂는다. 단말기에 오류 메시지가 뜬다."),
(C, "Hmm. Il y a marqué « Paiement refusé ». Vous pouvez réessayer ?", "음. '결제 거절'이라고 떠요. 다시 해 보시겠어요?"),
(P, "Refusé ? C'est impossible. Il y a de l'argent sur mon compte !", "거절이라고요? 말도 안 돼요. 제 계좌에 돈이 있는데요!"),
(P, "Je retape mon code. Quatre, un, sept, deux... voilà.", "비밀번호를 다시 누를게요. 4, 1, 7, 2... 됐어요."),
(C, "Toujours refusé, madame. Peut-être un problème de plafond ?", "또 거절이에요, 부인. 한도 문제일까요?"),
(P, "Mon plafond est assez haut. Essayez en sans contact.", "한도는 충분히 높은데요. 비접촉으로 해 보세요."),
(C, "Le sans contact est limité à cinquante euros par paiement, mais ça devrait passer pour vingt-six.", "비접촉은 한 번에 50유로까지인데, 26유로면 될 거예요."),
(None, "Elle approche la carte. Le terminal bipe trois fois.", "카드를 가까이 댄다. 단말기가 세 번 삑 소리를 낸다."),
(C, "Encore refusé... Madame, je ne comprends pas.", "또 거절이에요... 부인, 이해가 안 되네요."),
(P, "Ah, je crois que j'ai cassé la puce. J'ai laissé la carte dans la poche de mon jean, dans la machine à laver !", "아, 칩이 망가졌나 봐요. 카드를 청바지 주머니에 넣고 세탁기에 돌렸거든요!"),
(J, "Madame, excusez-moi d'intervenir. Votre carte est peut-être abîmée. Vous avez un autre moyen de paiement ?", "부인, 끼어들어서 죄송합니다. 카드가 손상되었을 수도 있어요. 다른 결제 수단이 있으신가요?"),
(P, "J'ai l'application sur mon téléphone. Ça marche aussi ?", "휴대폰에 앱이 있어요. 그걸로도 되나요?"),
(J, "Oui, bien sûr. Posez le téléphone sur le terminal, comme pour une carte.", "네, 물론이죠. 카드처럼 단말기에 휴대폰을 대 주세요."),
(None, "Mme Perrin pose son téléphone. Le terminal clignote en vert.", "페렝 부인이 휴대폰을 올린다. 단말기가 초록색으로 깜박인다."),
(J, "Ça y est, c'est accepté. Le ticket arrive.", "됐습니다, 승인됐어요. 영수증이 나옵니다."),
(P, "Ouf ! J'ai eu peur. Merci, jeune homme. Quelle honte, quand même.", "휴! 놀랐어요. 고마워요, 젊은이. 그래도 창피하네요."),
(J, "Ça arrive, madame. Hier, c'est le terminal qui est tombé en panne pendant tout le service.", "있을 수 있는 일이에요, 부인. 어제는 단말기가 서비스 내내 고장이었어요."),
(P, "Et là, vous faisiez comment ?", "그럼 그때는 어떻게 하셨어요?"),
(J, "On a pris les espèces, ou les gens revenaient le lendemain. Les chèques, on ne les accepte plus.", "현금을 받거나, 손님들이 다음 날 오셨어요. 수표는 이제 안 받아요."),
(C, "Julien, les deux autres personnes à la table cinq veulent payer ensemble. Ils ont des tickets-restaurant.", "쥘리앵, 5번 테이블의 나머지 두 분은 같이 내고 싶대요. 식권을 갖고 계세요."),
(J, "D'accord. Qui a les tickets ? Ils sont valables jusqu'à vingt-cinq euros par jour, tu le sais ?", "알았어. 누가 식권을 갖고 있어? 하루 25유로까지만 유효해, 알고 있지?"),
(C, "Non, je ne savais pas. Et on ne rend pas la monnaie, c'est ça ?", "아니요, 몰랐어요. 그리고 거스름돈은 안 돌려주죠, 맞죠?"),
(J, "Exactement. Si la note fait vingt-six cinquante, ils complètent avec une carte ou des espèces.", "맞아. 계산이 26유로 50이면 카드나 현금으로 보태시면 돼."),
(None, "Chloé retourne voir les deux derniers clients.", "클로에가 마지막 두 손님에게 돌아간다."),
(C, "Pardon de vous avoir fait attendre. Combien de tickets-restaurant avez-vous ?", "기다리게 해서 죄송합니다. 식권이 몇 장 있으세요?"),
(G, "Moi, j'en ai deux. Mon ami en a un. Chacun vaut onze euros.", "저는 두 장이요. 제 친구는 한 장이요. 한 장에 11유로예요."),
(C, "Ça fait trente-trois euros en tout. Mais la note est de vingt-six cinquante pour vous deux ?", "합쳐서 33유로네요. 그런데 두 분 계산서는 26유로 50이죠?"),
(G, "Oui. Donc je n'ai pas à compléter, c'est ça ?", "네. 그럼 더 낼 필요는 없는 거죠?"),
(C, "Si, il y a un problème : on ne peut pas rendre de monnaie. Il faut donc donner exactement le bon montant.", "아니요, 문제가 있어요. 거스름돈을 줄 수 없거든요. 그래서 정확한 금액을 내셔야 해요."),
(G, "Alors deux tickets font vingt-deux euros, et je complète avec quatre euros cinquante en espèces.", "그럼 식권 두 장이 22유로고, 나머지 4유로 50은 현금으로 낼게요."),
(C, "C'est parfait. Je vous apporte un reçu.", "완벽해요. 영수증을 가져다드릴게요."),
(None, "Elle revient au comptoir.", "그녀가 카운터로 돌아온다."),
(C, "Julien, ils ont tous payé. Et monsieur Garnier a laissé deux euros de pourboire.", "쥘리앵, 모두 계산했어요. 그리고 가르니에 씨가 팁으로 2유로를 두고 가셨어요."),
(J, "Très bien. Tu les mets dans le pot, là, à côté de la caisse.", "좋아. 저기 계산대 옆 통에 넣어."),
(C, "Le pot ? Ce n'est pas pour moi ?", "통이요? 제 건 아니에요?"),
(J, "C'est pour toute l'équipe. À la fin du mois, Hélène le partage entre tout le monde, la cuisine aussi.", "팀 전체의 거야. 월말에 엘렌이 주방 직원까지 모두에게 나눠 줘."),
(C, "C'est juste. Mais en France, on doit laisser un pourboire ?", "공평하네요. 근데 프랑스에서는 팁을 꼭 줘야 해요?"),
(J, "Non. Le service est compris dans le prix, c'est la loi depuis longtemps. Le pourboire, c'est un petit plus.", "아니. 서비스료는 가격에 포함되어 있어, 오래전부터 법이야. 팁은 작은 덤이지."),
(C, "Et combien on laisse, d'habitude ?", "보통은 얼마를 남겨요?"),
(J, "Une ou deux pièces, parfois cinq ou dix pour cent si on a été très content. Ce n'est jamais obligatoire.", "동전 한두 개, 아주 만족하면 5~10퍼센트 정도. 의무는 절대 아니야."),
(C, "Chez moi, les Américains laissent beaucoup plus, non ?", "미국 사람들은 훨씬 더 많이 남기잖아요, 아니에요?"),
(J, "Oui, les touristes surtout. Quinze, vingt pour cent. Chez nous, on laisse moins.", "응, 특히 관광객들이. 15, 20퍼센트. 우리는 덜 남겨."),
(C, "Et si on ne laisse rien, c'est impoli ?", "그럼 아무것도 안 남기면 실례예요?"),
(J, "Pas du tout. Le plus important, c'est de dire merci avec le sourire. Ça, ça vaut déjà beaucoup.", "전혀. 가장 중요한 건 미소를 짓고 고맙다고 말하는 거야. 그것만으로도 크지."),
(None, "La table cinq se lève. Mme Perrin s'approche du comptoir.", "5번 테이블이 일어선다. 페렝 부인이 카운터로 다가온다."),
(P, "Merci pour tout, jeune homme. Le repas était délicieux.", "모든 것에 감사해요, 젊은이. 식사가 정말 맛있었어요."),
(J, "Merci à vous, madame. Et ne mettez plus vos cartes dans la machine à laver !", "저희가 감사하죠, 부인. 그리고 이제 카드는 세탁기에 넣지 마세요!"),
(P, "Ha ha, promis ! Au revoir. Bonne fin de journée à tous les deux.", "하하, 약속해요! 안녕히 계세요. 두 분도 좋은 하루 보내요."),
(C, "Bonne fin de journée, madame. À bientôt, messieurs.", "좋은 하루 보내세요, 부인. 곧 또 뵙겠습니다, 손님들."),
(G, "Au revoir, mademoiselle. N'oubliez pas la virgule, la prochaine fois !", "안녕히 계세요, 아가씨. 다음엔 소수점 잊지 마세요!"),
(C, "Promis, je ne l'oublierai plus. Merci beaucoup !", "약속해요, 다시는 안 잊을게요. 정말 감사합니다!"),
(None, "La porte se referme. La salle est enfin vide.", "문이 닫힌다. 홀이 마침내 비었다."),
(C, "Ouf. J'ai cru que j'allais pleurer quand le terminal a dit « refusé ».", "휴. 단말기가 '거절'이라고 했을 때 울 뻔했어요."),
(J, "Mais tu t'en es bien sortie. Tu as gardé ton sourire. C'est ce qui compte.", "하지만 잘 해냈어. 미소를 잃지 않았잖아. 그게 중요해."),
(C, "Trois cent cinquante euros ! J'ai failli leur prendre une fortune.", "350유로라니! 하마터면 큰돈을 받을 뻔했어요."),
(J, "Ça m'est arrivé aussi, ma première semaine. J'ai facturé un café à vingt euros.", "나도 첫 주에 그랬어. 커피 한 잔을 20유로로 계산한 적이 있어."),
(C, "Sérieux ? Et le client a dit quoi ?", "진짜요? 손님은 뭐라고 했어요?"),
(J, "Il a demandé s'il avait bu un café ou une bouteille de champagne. On a bien ri.", "커피를 마신 건지 샴페인 한 병을 마신 건지 물었어. 우리 다 크게 웃었지."),
(C, "Bon. Alors tout le monde fait des erreurs.", "그럼 누구나 실수를 하는군요."),
(J, "Oui. L'important, c'est de les corriger vite et avec le sourire. Comme tu l'as fait.", "응. 중요한 건 빨리, 미소를 띠고 바로잡는 거야. 네가 그랬듯이."),
(C, "Je note dans mon carnet : « virgule », « annulation », « pourboire ». Et « plafond », ça s'écrit comment ?", "수첩에 적어 둘게요. '소수점', '취소', '팁'. 그리고 '한도'는 철자가 어떻게 돼요?"),
(J, "P, L, A, F, O, N, D. Comme le plafond d'une pièce. Le mot est le même.", "P, L, A, F, O, N, D. 방 천장과 같은 단어야."),
(C, "Ah, donc la carte a un plafond comme une maison ! Je comprends mieux.", "아, 그럼 카드에도 집처럼 천장이 있는 거네요! 이제 이해가 가요."),
(J, "Voilà. Allez, on débarrasse la table cinq. Prends le plateau.", "그렇지. 자, 5번 테이블 치우자. 쟁반 가져와."),
(C, "Et la note de monsieur Garnier ? Je la garde pour la comptabilité ?", "가르니에 씨 계산서는요? 회계용으로 보관할까요?"),
(J, "Oui, tu la mets dans la boîte à côté de la caisse. Hélène la regardera ce soir.", "응, 계산대 옆 상자에 넣어. 엘렌이 저녁에 볼 거야."),
(C, "Et les tickets-restaurant ?", "식권은요?"),
(J, "Dans l'enveloppe bleue. On les envoie à la banque tous les quinze jours.", "파란 봉투에. 2주에 한 번 은행으로 보내."),
(C, "Compris. Il y a beaucoup de choses à retenir quand on encaisse !", "알겠어요. 계산할 때 기억할 게 정말 많네요!"),
(J, "Tu t'y habitueras. Dans un mois, tu feras ça les yeux fermés.", "익숙해질 거야. 한 달 뒤엔 눈 감고도 할걸."),
(C, "Les yeux fermés, mais avec la virgule !", "눈을 감고도, 소수점은 잊지 않고요!"),
(J, "Ha ha ! Voilà. Allez, un café pour la route, on l'a bien mérité.", "하하! 그렇지. 자, 한 잔 하자, 우리 그럴 자격 있어."),
(C, "Offert par la maison ?", "가게에서 쏘는 거예요?"),
(J, "Offert par la maison. Mais ne le note pas sur l'addition !", "가게에서 쏘는 거야. 하지만 계산서에는 적지 마!"),
]

VOCAB = [
("A2", "L'addition, s'il vous plaît.", "계산서 주세요.", "손님이 계산을 요청할 때. 직원은 « Je vous apporte l'addition. » 프랑스에서는 먼저 가져오지 않고 손님이 요청할 때 가져온다. la note = 계산서(일상 구어)."),
("A2", "payer par carte / en espèces / par chèque", "카드로 / 현금으로 / 수표로 계산하다", "결제 수단. espèces = 현금(복수). « Je paie par carte. » 낭독 시 espèces 의 s 는 [s]."),
("A2", "Vous pouvez insérer votre carte.", "카드를 꽂아 주세요.", "단말기 안내. insérer = 꽂다, taper son code = 비밀번호를 누르다."),
("A2", "le pourboire / la monnaie", "팁 / 거스름돈", "Gardez la monnaie. = 거스름돈은 가지세요(팁). le pourboire 는 직역하면 '마시라고 주는 돈'."),
("A2", "Séparément / ensemble", "따로 / 함께", "« On peut payer séparément ? » 계산을 나누는 가장 기본 질문."),
("A2", "Trente et un euros chacun.", "한 사람당 31유로", "chacun = 각자. « euros » 앞 숫자와 리에종. 31은 trente et un (et 앞뒤 하이픈 없음)."),
("A2", "C'est réglé. / Voilà, c'est réglé.", "계산 끝났어요.", "régler = 결제하다(한자어 '정산'과 비슷). 격식 있게 payer 대신 쓴다."),
("A2", "Un instant, s'il vous plaît.", "잠시만 기다려 주세요.", "손님을 기다리게 할 때의 정중한 표현. « Un moment » 도 가능."),
("B1", "Paiement refusé / accepté", "결제 거절 / 승인", "단말기 메시지. 수동 표현: « La transaction a été annulée. » 〈être + 과거분사〉 로 행위자 없이 상황을 말한다."),
("B1", "Le sans contact est limité à cinquante euros.", "비접촉은 50유로로 제한돼요.", "plafond = 한도. 비접촉 한도를 넘으면 비밀번호가 필요하다."),
("B1", "[구어] Ça y est. ↔ 정중: C'est terminé.", "됐어요, 끝났어요.", "일이 막 성공했을 때. « Ça y est, c'est accepté. »"),
("B1", "[구어] Ouf ! J'ai eu peur. ↔ 정중: Quel soulagement.", "휴! 놀랐어요.", "안도의 감탄사 ouf. 어려움이 지나갔을 때."),
("B1", "les tickets-restaurant", "식권", "점심 때 직장인이 쓰는 식대 쿠폰. 하루 한도와 거스름돈 불가 규칙이 있어 정확한 금액을 맞춰야 한다."),
("B1", "[구어] Gardez la monnaie. ↔ 정중: Veuillez conserver la différence.", "거스름돈은 가지세요.", "팁을 건넬 때 가장 흔한 말. 소액일 때 « C'est pour vous. » 도 쓴다."),
("B1", "Le service est compris.", "서비스료가 포함되어 있다.", "프랑스 메뉴판에 « Service compris » 라고 쓰는 경우가 많다. 팁은 의무가 아닌 감사의 표시."),
("B2", "Je me suis trompé. / J'ai oublié la virgule.", "제가 틀렸어요. / 소수점을 빼먹었어요.", "se tromper = 실수하다. 사과는 « Pardon, pardon ! » 로 가볍게. 숫자 오류에 쓰는 어휘: une virgule(소수점), un montant(금액)."),
("B2", "On a bien ri.", "우리는 크게 웃었어요.", "[구어] bien + 동사 = 실컷, 제대로. « On a bien mangé. » 도 같은 형태."),
("B2", "Tu t'en es bien sortie.", "너 잘 헤쳐 나갔어.", "s'en sortir = 어려움을 이겨내다. 구어에서 격려할 때 흔함."),
("B2", "Offert par la maison.", "가게 서비스입니다.", "무료 제공 표현. Le café est offert. = 수동 표현. 계산서에는 올리지 않는다."),
("C1", "J'ai failli leur prendre une fortune.", "하마터면 큰돈을 받을 뻔했어요.", "faillir + 동사원형 = 하마터면 ~할 뻔하다(j'ai failli tomber). prendre une fortune 은 과장 표현."),
("C1", "Il a demandé s'il avait bu un café ou une bouteille de champagne.", "커피를 마신 건지 샴페인 한 병을 마신 건지 물었다.", "간접 의문문과 대과거(avait bu). 유머로 가격 실수를 지적하는 방식. 세련된 에스프리."),
]

GRAM = [
("A2", "수 읽기와 가격 말하기", "« Cent vingt-quatre euros. » « Trente-cinq euros cinquante. » « Vingt-six cinquante. » 100 이상은 cent + 숫자, 소수점 이하는 euros 뒤에 숫자만 말한다. 31은 trente et un, 70대는 soixante-dix 식으로 말한다. 이 화는 모든 가격을 단어로 표기했다."),
("A2", "수동적 표현 〈être + 과거분사〉", "« La transaction a été annulée. » « Le café est offert. » « Votre paiement est refusé. » 행위자를 말하지 않고 결과를 알리는 형태. 직원이 손님에게 상황을 객관적으로 설명할 때 쓴다."),
("B1", "수동적 의미의 ça se / on", "« Ça se règle à la caisse. » « Les chèques, on ne les accepte plus. » 구어에서는 on 이 '사람들·가게'를 뭉뚱그려 말하면서 수동 같은 뜻을 낸다. 공식 안내문은 passive."),
("B1", "chacun / chacune, partager en quatre", "« Trente et un euros chacun. » « On partage en quatre. » partager en + 수 = ~등분하다. chacun 은 문장 끝에 붙여 각자 몫을 말한다."),
("B1", "대명사 en / y (결제 장면)", "« Tu t'en es bien sortie. » « Il en a bu la moitié. » « Je suis juste derrière toi. » en = de + 명사, 수량은 남기고 명사만 대체. s'en sortir, en avoir 는 통째로 익혀 두면 좋다."),
("B1", "정중한 요청 — pouvoir / vouloir 의 vous 형", "« Vous pouvez insérer votre carte. » « Vous pouvez réessayer ? » « Vous avez un autre moyen de paiement ? » 의문 억양만으로 정중하게 요청할 수 있다. 4화에서 배운 vouloir/pouvoir를 결제 장면에서 반복."),
("B2", "faillir + 동사원형 / 대과거로 간접 화법", "« J'ai failli leur prendre une fortune. » → 하마터면 ~할 뻔했다. « Il a demandé s'il avait bu un café. » → 질문의 시점이 과거이므로 avait bu(대과거)를 쓴다. 구어에서도 사용하지만 B2 이상의 문장."),
]

READ = [
("숫자 읽기 — cent vingt-quatre, trente et un", "« Cent vingt-quatre euros » / 「상 뱅-까트르 으로」. quatre의 r은 euros 앞에서 이어져 [까트르 으로]. « Trente et un euros » 에서 et un 은 [에엉]처럼 끊김 없이 말한다. « Vingt-six cinquante » 는 / vingt-six / cinquante / 로 두 덩어리."),
("리에종 — vingt_euros, trois_euros, un_instant", "« Un instant, s'il vous plaît. » → 「엉 냉스땅」. « Deux euros » → 「되 즈 으로」: deux 의 x 가 [z]. « Trois euros » 도 [트루아 즈 으로]. 숫자 + euros 는 대부분 리에종이 생긴다."),
("비음 — pourboire 가 아니라 monnaie, encaisser", "« Gardez la monnaie. » 「몽네」의 on 은 코로. « J'encaisse » 의 en 은 [앙]. « Vingt » 의 in 은 [앵]. 비음 세 가지가 나란히 나오는 문장: « Vingt-cinq euros par jour ». 끝을 올리지 말고 단정하게."),
("억양 — 놀람과 안심", "« Refusé ? C'est impossible ! » 끝을 올려 놀람. « Ouf ! J'ai eu peur. » 한숨 섞어 길게. « Ça y est, c'est accepté. » 마지막 accepté 에서 톤을 내려 안심을 표현. 감정에 따라 호흡 구간을 다르게."),
("r 소리 — terminal, paiement, carte", "« Le terminal » 의 r은 입안 뒤쪽에서 살짝 마찰. « Votre carte » 같이 r이 둘 있는 구간은 앞의 r을 약하게, 뒤를 또렷하게. « Vous pouvez réessayer ? » 는 / Vous pouvez / réessayer ? / 로 끊어 읽는다."),
("u / ou — plafond가 아니라 puce, pourboire", "« La puce est cassée. » u [위]: 입술을 앞으로 모으고 혀는 앞쪽. « Pourboire » 의 ou [우]: 입술은 둥글지만 혀는 뒤쪽. puce / pouce, rue / roue 짝을 읽어 비교."),
("엘리종과 축약 — j'ai, l'addition, t'as", "« J'ai failli » 「줴 파이이」. « L'addition » 「라디시옹」. « Tu t'en es bien sortie » 는 / Tu t'en es / bien sortie / 로. 구어에서는 모음이 겹치는 곳에서 소리가 줄어든다."),
]

CULTURE = [
("프랑스의 팁 — le pourboire와 service compris", "프랑스에서는 1987년부터 메뉴 가격에 서비스료 15%가 포함되어 있다(service compris). 그래서 팁은 의무가 아니고 감사의 표시다. 보통 계산서를 반올림하거나 잔돈을 남기는 정도이며, 매우 만족했을 때 5~10%를 남기기도 한다. 카드 결제 시에는 단말기에 팁 항목이 없는 경우가 많아 현금으로 건네는 일이 흔하다. 이 가게에서는 팁을 통(pot)에 모아 월말에 팀 전체가 나눈다."),
("더치페이와 식권 — payer séparément, titres-restaurant", "프랑스에서는 친구끼리 계산서를 나누는 일이 흔하고, 직원에게 « On peut payer séparément ? » 라고 물으면 대개 계산서를 따로 뽑아 준다. 점심때는 직장인이 titres-restaurant (식권) 를 쓰는데, 하루 사용 한도(25유로)와 거스름돈 불가 규칙이 있어 부족분은 카드나 현금으로 보탠다. 단말기가 고장나거나 카드가 거절될 때를 대비해 현금과 모바일 결제를 안내할 수 있어야 한다."),
]

META = dict(part=1, ep=9, part_label="제1부 Mise en place · 봄", title_fr="L'addition, s'il vous plaît", title_ko="계산서 부탁합니다",
 place="Le Comptoir de Marthe, 홀과 카운터 · 6월 초 토요일 오후 2시 5분",
 chars="Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · M. Garnier (손님) · Mme Perrin (손님)",
 wine="계산과 더치페이, 카드 거절, 팁 문화",
 focus="결제 어휘 · 가격과 숫자 읽기 · 수동적 표현(été annulée, est offert) · 정중한 요청(Vous pouvez...)",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제10화 « Mme Vasseur et sa table » : 단골 불평쟁이 바세르 부인의 7번 테이블, 과거 습관(imparfait)과 완곡한 거절")
