# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, P = "Hélène", "Julien", "Chloé", "M. Parker"
D = [
(None, "Samedi de mai, 13 h 20. Il fait beau. Chloé débarrasse une table sur la terrasse. Un homme s'approche avec un plan froissé.", "5월의 토요일, 13시 20분. 날씨가 좋다. 클로에가 테라스 테이블을 치우고 있다. 구겨진 지도를 든 남자가 다가온다."),
(P, "Excusez-moi, madame. Vous... parlez anglais ?", "실례합니다, 아가씨. 영어... 하세요?"),
(C, "Un petit peu. Mais on peut essayer en français, si vous voulez.", "조금요. 그래도 괜찮으시면 프랑스어로 해 볼까요?"),
(P, "Oui, oui. Mon français est... pas très bon. Sorry.", "네, 네. 제 프랑스어는... 별로예요. 미안해요."),
(C, "Pas de souci. Je parle lentement, d'accord ?", "괜찮아요. 천천히 말할게요, 알겠죠?"),
(P, "Merci. Je cherche... l'hôtel Voltaire. Je suis perdu.", "고마워요. 저는... 볼테르 호텔을 찾고 있어요. 길을 잃었어요."),
(C, "L'hôtel Voltaire ? C'est assez loin d'ici, monsieur.", "볼테르 호텔이요? 여기서 꽤 멀어요, 손님."),
(P, "My phone is dead. Plus de batterie. Et j'ai très faim.", "휴대폰이 꺼졌어요. 배터리가 없어요. 그리고 배가 너무 고파요."),
(C, "Alors, mangez d'abord. Après, je vous montre le chemin.", "그럼 먼저 드세요. 그다음에 길을 알려 드릴게요."),
(P, "Vous êtes très gentille. Il y a une table libre ?", "정말 친절하시네요. 빈 테이블 있나요?"),
(C, "Oui, une table au soleil. Je vous apporte la carte.", "네, 햇볕 드는 자리가 있어요. 메뉴판을 가져다 드릴게요."),
(P, "La carte... c'est le menu, oui ? En anglais, « menu ».", "라 카르트... 메뉴 말이죠? 영어로 'menu'."),
(C, "Oui, mais ici « le menu », c'est la formule à prix fixe. La carte, c'est la liste.", "맞아요, 그런데 여기서 『le menu』는 정해진 가격의 세트예요. 『la carte』는 목록이고요."),
(P, "Ah, intéressant ! Deux mots différents. Je note.", "아, 재미있네요! 두 단어가 달라요. 적어 둘게요."),
(C, "Julien, j'ai un monsieur américain, tout seul. Il est perdu.", "줄리앙, 미국인 남자 손님이 혼자 계신데 길을 잃었대요."),
(J, "Il parle français ?", "프랑스어 하셔?"),
(C, "Un peu. Mais il mélange avec l'anglais.", "조금요. 그런데 영어를 섞어서 말해요."),
(J, "Pas de panique. Parle lentement, avec des mots simples.", "당황하지 마. 천천히, 쉬운 단어로 말해."),
(C, "C'est ce que je fais. Mais les mots du menu, c'est difficile.", "그렇게 하고 있어요. 그런데 메뉴 단어들이 어려워요."),
(J, "Tu peux mimer, ou montrer sur l'ardoise. Ça marche très bien.", "몸짓으로 설명하거나 칠판을 가리켜. 아주 잘 통해."),
(C, "Vous venez avec moi ? Ce serait plus rassurant.", "같이 가 주실래요? 그러면 더 안심이 될 것 같아요."),
(J, "D'accord. Je viens écouter, mais c'est toi qui parles.", "좋아. 들으러 갈게. 하지만 말하는 건 네가 해."),
(None, "Sur la terrasse, M. Parker lit la carte du bout des doigts, le front plissé.", "테라스에서 파커 씨가 손가락으로 메뉴를 짚어 가며 이마를 찌푸리고 읽는다."),
(P, "Pardon... Qu'est-ce que c'est, « une terrine de campagne » ?", "저기... 『une terrine de campagne』이 뭔가요?"),
(C, "C'est de la viande de porc, cuite au four, froide, avec du pain.", "돼지고기를 오븐에 익혀서 차갑게 해 빵과 먹는 거예요."),
(P, "Ah, du porc. Moi, je ne mange pas de viande.", "아, 돼지고기. 저는 고기를 안 먹어요."),
(C, "Pas de viande du tout ? Même pas de poisson ?", "고기를 전혀 안 드세요? 생선도요?"),
(P, "Le poisson, oui. Mais pas la viande. Vegetarian, presque.", "생선은 먹어요. 하지만 고기는 안 먹어요. 거의 채식주의자예요."),
(J, "Bonjour, monsieur. Je suis Julien, le responsable. Tout va bien ?", "안녕하세요, 손님. 매니저 줄리앙입니다. 다 괜찮으신가요?"),
(P, "Bonjour. Oui, la jeune fille est très patiente. Thank you.", "안녕하세요. 네, 아가씨가 아주 참을성이 많아요. 고마워요."),
(J, "Elle va vous expliquer. Je reste à côté, au cas où.", "저 친구가 설명해 드릴 거예요. 만일을 대비해 옆에 있겠습니다."),
(C, "Alors, pour vous, je conseille l'œuf mayonnaise. C'est un œuf dur avec une sauce froide.", "그럼 손님께는 달걀 마요네즈를 권해요. 삶은 달걀에 차가운 소스를 올린 거예요."),
(P, "Un œuf avec de la mayonnaise. C'est simple !", "달걀에 마요네즈. 간단하네요!"),
(C, "Oui, mais c'est très français. Tout le monde l'aime.", "네, 그런데 아주 프랑스적이에요. 다들 좋아해요."),
(P, "Et « velouté de petits pois » ? Velouté, c'est quoi ?", "그럼 『velouté de petits pois』는요? velouté가 뭐죠?"),
(C, "C'est une soupe très douce, très lisse. Avec des petits pois verts.", "아주 부드럽고 매끈한 수프예요. 푸른 완두콩으로 만들어요."),
(P, "Pea soup ! Oh, I love it. Mais il y a du jambon ?", "완두콩 수프! 아, 좋아해요. 그런데 햄이 들어 있나요?"),
(C, "Je demande à la cuisine. Un instant, s'il vous plaît.", "주방에 물어볼게요. 잠시만요."),
(J, "Bonne idée, Chloé. Toujours demander, jamais deviner.", "좋은 생각이야, 클로에. 늘 물어보고, 절대 짐작하지 마."),
(None, "Chloé passe la tête dans la cuisine. Hélène remue une casserole.", "클로에가 주방에 고개를 들이민다. 엘렌이 냄비를 젓고 있다."),
(C, "Hélène, il y a du jambon dans le velouté de petits pois ?", "엘렌, 완두콩 벨루테에 햄이 들어가요?"),
(H, "Non. Juste des oignons, du bouillon de légumes et un peu de crème.", "아니. 양파, 채소 육수, 크림 조금뿐이야."),
(C, "Le bouillon, il est fait avec de la viande ?", "육수는 고기로 낸 건가요?"),
(H, "Non, c'est un bouillon de légumes. Pourquoi ?", "아니, 채소 육수야. 왜?"),
(C, "J'ai un client qui ne mange pas de viande. Il est américain, il est perdu.", "고기를 안 드시는 손님이 있어요. 미국인이고, 길을 잃었대요."),
(H, "Perdu ? Dans le quartier ? Le pauvre.", "길을 잃어? 이 동네에서? 가엾네."),
(C, "Oui. Il cherche l'hôtel Voltaire. Et il a faim.", "네. 볼테르 호텔을 찾아요. 그리고 배가 고프대요."),
(H, "Donne-lui le velouté. Et pour le plat, fais-lui une salade de chèvre chaud.", "벨루테를 드려. 메인으로는 따뜻한 염소 치즈 샐러드를 해 줘."),
(C, "Et s'il veut quelque chose de plus gros ?", "더 든든한 걸 원하시면요?"),
(H, "Je peux faire une omelette aux champignons. Ce n'est pas sur l'ardoise, mais ça existe.", "버섯 오믈렛을 해 줄 수 있어. 칠판에는 없지만 가능해."),
(C, "Merci, Hélène. Je lui propose les deux.", "고마워요, 엘렌. 두 가지 다 권해 볼게요."),
(H, "Dis-lui que ça arrive vite. Il doit être fatigué.", "금방 나온다고 말해 줘. 피곤하실 테니까."),
(C, "Monsieur, bonne nouvelle. Le velouté est sans viande et sans jambon.", "손님, 좋은 소식이에요. 벨루테에는 고기도 햄도 안 들어가요."),
(P, "Wonderful. Je prends le velouté, alors.", "훌륭해요. 그럼 벨루테로 할게요."),
(C, "Très bien. Ensuite, vous avez le choix entre deux plats.", "좋아요. 그다음 메인은 두 가지 중에서 고르실 수 있어요."),
(P, "Deux ? Lesquels ?", "두 가지요? 어떤 거죠?"),
(C, "Une salade de chèvre chaud, ou une omelette aux champignons.", "따뜻한 염소 치즈 샐러드, 아니면 버섯 오믈렛이요."),
(P, "Chèvre chaud... C'est du fromage, non ? Du fromage de chèvre ?", "『chèvre chaud』... 치즈죠, 맞죠? 염소 치즈?"),
(C, "Oui. Il est chaud, sur du pain grillé, avec de la salade et du miel.", "네. 따뜻한 상태로 구운 빵 위에 올리고 샐러드와 꿀을 곁들여요."),
(P, "Du miel avec du fromage ? C'est bizarre, non ?", "치즈에 꿀이요? 이상하지 않나요?"),
(C, "Pas du tout, c'est délicieux. Le salé et le sucré, ça va bien ensemble.", "전혀요, 맛있어요. 짠맛과 단맛이 잘 어울려요."),
(P, "OK, I trust you. Je prends la salade.", "알겠어요, 믿을게요. 샐러드로 할게요."),
(C, "Parfait. Et comme boisson ? Un verre de vin, une eau, un café ?", "좋아요. 음료는요? 와인 한 잔, 물, 커피?"),
(P, "Un verre de vin blanc, s'il vous plaît. Quelque chose de léger.", "화이트 와인 한 잔 주세요. 가벼운 걸로요."),
(J, "Je vous conseille un Sancerre, monsieur. Il est frais et très léger.", "상세르를 권해 드립니다, 손님. 시원하고 아주 가벼워요."),
(P, "San... Sancerre. Ça se prononce comment ?", "상... 상세르. 어떻게 발음하죠?"),
(J, "Sancerre. « Sans », comme « sans viande », et « serre ».", "상세르요. 『sans viande』의 sans, 그리고 『serre』."),
(P, "Sans-serre. Oui ! Sans viande, sans problème.", "상세르. 네! 고기 없이, 문제없이."),
(J, "Très bien ! Vous parlez déjà comme un Parisien.", "훌륭하세요! 벌써 파리 사람처럼 말씀하시네요."),
(P, "Ha ha, vous êtes drôle. Mais j'ai un autre problème.", "하하, 재미있으시네요. 그런데 다른 문제가 하나 있어요."),
(J, "Dites-moi, monsieur.", "말씀하세요, 손님."),
(P, "Mon téléphone n'a plus de batterie. Je peux le charger ici ?", "휴대폰 배터리가 없어요. 여기서 충전해도 될까요?"),
(J, "Bien sûr. Il y a une prise derrière le bar. Je le branche pour vous.", "물론이죠. 바 뒤에 콘센트가 있어요. 제가 꽂아 드릴게요."),
(P, "Thank you so much. Vous sauvez ma journée.", "정말 고마워요. 제 하루를 구해 주시네요."),
(None, "Quelques minutes plus tard. Chloé apporte le velouté. M. Parker goûte et ferme les yeux.", "몇 분 뒤. 클로에가 벨루테를 가져온다. 파커 씨가 맛을 보고 눈을 감는다."),
(P, "Oh... c'est très bon. C'est comme une crème verte.", "오... 정말 맛있네요. 초록색 크림 같아요."),
(C, "C'est Hélène, la cheffe, qui l'a faite ce matin.", "오늘 아침에 셰프 엘렌이 만들었어요."),
(P, "Dites-lui : « Compliments à la cheffe ». C'est la bonne phrase ?", "『Compliments à la cheffe』라고 전해 주세요. 맞는 표현이죠?"),
(C, "Oui, parfait ! Je le lui dis tout à l'heure.", "네, 완벽해요! 이따가 전해 드릴게요."),
(P, "Vous êtes tous très gentils. À New York, ce n'est pas pareil.", "여기 분들은 다 정말 친절하네요. 뉴욕은 달라요."),
(C, "Vous venez de New York ? Qu'est-ce que vous faites à Paris ?", "뉴욕에서 오셨어요? 파리에는 무슨 일로 오셨어요?"),
(P, "Je suis en vacances avec ma femme. Elle est restée à l'hôtel.", "아내와 휴가 중이에요. 아내는 호텔에 남아 있어요."),
(C, "Ah, et elle ne vous attend pas ? Elle va s'inquiéter.", "아, 부인께서 기다리고 계시지 않나요? 걱정하실 텐데요."),
(P, "Oui, c'est un problème. Mon téléphone, il est mort !", "맞아요, 그게 문제예요. 제 폰이 죽었어요!"),
(J, "Elle a le numéro du restaurant ? Vous pouvez l'appeler d'ici.", "부인께서 이 가게 번호를 아세요? 여기서 전화하실 수 있어요."),
(P, "Non, mais je me souviens de la chambre. Numéro 24, hôtel Voltaire.", "아니요, 하지만 객실 번호는 기억해요. 볼테르 호텔 24호요."),
(J, "Parfait. Je trouve le numéro de l'hôtel et j'appelle de mon portable.", "좋습니다. 호텔 번호를 찾아서 제 휴대폰으로 걸어 볼게요."),
(P, "Vraiment ? Ce serait formidable. Merci !", "정말요? 그럼 정말 좋겠네요. 고마워요!"),
(C, "Voilà votre salade. Attention, le pain est chaud.", "샐러드 나왔습니다. 조심하세요, 빵이 뜨거워요."),
(P, "Ça sent bon. Et le miel... Oh, c'est vrai, c'est délicieux !", "냄새 좋아요. 그리고 꿀... 오, 정말이네요, 맛있어요!"),
(C, "Vous voyez ? Je vous l'avais dit.", "보세요? 제가 말씀드렸죠."),
(P, "Vous avez raison. Pardon d'avoir douté.", "맞아요. 의심해서 미안해요."),
(C, "Pas de problème. Les Français aussi, ils doutent souvent.", "괜찮아요. 프랑스 사람들도 자주 의심해요."),
(J, "Monsieur Parker ? Bonne nouvelle. Votre femme est au téléphone.", "파커 씨? 좋은 소식이에요. 부인께서 전화를 받으셨어요."),
(P, "Ah ! Elle est inquiète ? Elle va être furieuse.", "아! 걱정하고 있나요? 화가 많이 났겠죠."),
(J, "Non, elle riait. Elle dit que vous avez toujours perdu les clés aussi.", "아니요, 웃고 계셨어요. 열쇠도 늘 잃어버리신다고 하시던데요."),
(P, "Ha ha ! C'est vrai. Elle me connaît trop bien.", "하하! 맞아요. 아내가 저를 너무 잘 알죠."),
(J, "Je lui ai dit que vous déjeunez ici et que vous arriverez vers quinze heures.", "여기서 점심 중이시고 3시쯤 도착하실 거라고 말씀드렸어요."),
(P, "Merci, Julien. Vous êtes un ange.", "고마워요, 줄리앙. 천사 같으세요."),
(J, "Pas du tout. Mais je vous dessine le chemin sur un papier.", "천만에요. 대신 가는 길을 종이에 그려 드릴게요."),
(None, "Julien prend un bloc-notes et dessine un plan simple. Chloé regarde par-dessus son épaule.", "줄리앙이 메모지를 꺼내 간단한 약도를 그린다. 클로에가 어깨 너머로 본다."),
(J, "Alors, vous sortez d'ici, vous tournez à gauche. Tout droit, deux cents mètres.", "자, 여기서 나가서 왼쪽으로 도세요. 200미터 직진하세요."),
(P, "Tout droit, deux cents mètres. D'accord.", "직진 200미터. 알겠어요."),
(J, "Ensuite, vous prenez la deuxième rue à droite. L'hôtel est en face de la boulangerie.", "그다음 두 번째 길에서 오른쪽으로 가세요. 호텔은 빵집 맞은편에 있어요."),
(P, "La deuxième à droite. Boulangerie. Facile !", "두 번째 길 오른쪽. 빵집. 쉽네요!"),
(C, "Si vous vous perdez encore, demandez à quelqu'un : « Pardon, l'hôtel Voltaire ? »", "또 길을 잃으면 누구에게든 물어보세요. 『Pardon, l'hôtel Voltaire ?』"),
(P, "« Pardon, l'hôtel Voltaire ? » Je répète : Pardon, l'hôtel Voltaire.", "『Pardon, l'hôtel Voltaire ?』 따라 해 볼게요. Pardon, l'hôtel Voltaire."),
(C, "C'est très bien. Votre accent est excellent.", "아주 좋아요. 발음이 훌륭하세요."),
(P, "Vous êtes gentille. Un dessert, peut-être ? Quelque chose de local.", "친절하시네요. 디저트도 먹을까요? 이 지역다운 걸로요."),
(C, "Je vous recommande la tarte Tatin. C'est une tarte aux pommes, à l'envers.", "타르트 타탱을 추천해요. 사과 타르트를 뒤집은 거예요."),
(P, "À l'envers ? Upside down ? Pourquoi ?", "뒤집어서요? 거꾸로? 왜요?"),
(C, "On cuit les pommes dessous, puis on retourne la tarte. Voilà.", "사과를 아래에 깔고 구운 다음 타르트를 뒤집는 거예요. 그게 다예요."),
(P, "Une tarte Tatin, un café. Et l'addition, s'il vous plaît.", "타르트 타탱 하나, 커피 한 잔. 그리고 계산서 부탁해요."),
(None, "Après le café. M. Parker se lève, plan en main, et croise Hélène qui sort de la cuisine.", "커피 후에. 파커 씨가 약도를 들고 일어나다가 주방에서 나오는 엘렌과 마주친다."),
(H, "Bonjour, monsieur. J'espère que le déjeuner vous a plu.", "안녕하세요, 손님. 점심이 마음에 드셨기를 바랍니다."),
(P, "Compliments à la cheffe ! Le velouté, c'était magnifique.", "셰프님께 찬사를! 벨루테가 훌륭했어요."),
(H, "Merci beaucoup. Revenez nous voir avec votre femme.", "정말 감사합니다. 부인과 함께 또 오세요."),
(P, "Promis ! Au revoir, et merci pour tout. Merci, Chloé, merci, Julien !", "약속해요! 안녕히 계세요, 모든 게 감사해요. 고마워요, 클로에, 줄리앙!"),
(J, "Voilà, il est parti. Tu as bien géré, Chloé.", "자, 가셨네. 클로에, 잘 해냈어."),
(C, "Vraiment ? J'ai mélangé des mots et j'ai mimé le pain grillé.", "정말요? 단어도 섞고 구운 빵은 몸짓으로 흉내 냈는데요."),
(H, "Il a tout mangé, jusqu'à la dernière feuille. C'est le meilleur compliment.", "마지막 잎 하나까지 다 드셨어. 그게 최고의 칭찬이야."),
(C, "Et il a dit « Compliments à la cheffe » en français !", "게다가 프랑스어로 『셰프님께 찬사를』이라고 했어요!"),
(H, "Merci. Mais ne le dis pas à mon père, il va vouloir une photo.", "고마워. 그래도 아버지께는 말하지 마, 사진을 찍자고 하실 테니까."),
(J, "Note ça dans ton carnet, Chloé : « se débrouiller ».", "클로에, 수첩에 적어 둬. 『se débrouiller』."),
(C, "Se débrouiller ? Ça veut dire quoi ?", "se débrouiller? 무슨 뜻이에요?"),
(J, "Trouver une solution toute seule. Exactement ce que tu as fait.", "혼자서 해결책을 찾는 거야. 방금 네가 한 그대로."),
]

VOCAB = [
("A2", "Excusez-moi, vous parlez anglais ?", "실례합니다, 영어 하세요?", "외국인이 처음 건네는 말. 대답 « un petit peu » (조금) 로 시작하면 부드럽게 프랑스어로 전환 가능."),
("A2", "Je suis perdu.", "길을 잃었어요.", "perdu 는 남성형, 여성이 말하면 perdue (발음은 같음). se perdre 의 상태 표현."),
("A2", "Je parle lentement, d'accord ?", "천천히 말할게요, 괜찮죠?", "외국인 응대의 기본. « d'accord ? » 로 확인을 구한다."),
("A2", "C'est loin d'ici ?", "여기서 멀어요?", "길 안내의 기본 질문. « assez loin » (꽤 멀다), « tout près » (바로 가깝다) 와 함께 익힌다."),
("A2", "Tout droit, deux cents mètres.", "직진 200미터.", "길 안내: tout droit, à gauche, à droite, la deuxième rue. 숫자는 낭독 시 단어로."),
("A2", "Je prends le velouté, alors.", "그럼 벨루테로 할게요.", "주문 확정 표현. prendre = 주문하다. alors 는 '그러면'."),
("A2", "Un verre de vin blanc, s'il vous plaît.", "화이트 와인 한 잔 주세요.", "주문 + s'il vous plaît. 와인 색: blanc, rouge, rosé."),
("A2", "Je ne mange pas de viande.", "저는 고기를 먹지 않아요.", "부정 뒤에는 de/d' + 무관사 명사. 식습관을 말할 때 필수 문형."),
("A2", "Un instant, s'il vous plaît.", "잠시만요.", "손님을 기다리게 할 때. [구어] « une minute » ↔ 정중: Un instant, s'il vous plaît."),
("B1", "C'est de la viande de porc, cuite au four.", "돼지고기를 오븐에 익힌 거예요.", "« C'est + 부분관사 + 재료 » 로 음식 정체를 설명하는 기본 틀. 뒤에 과거분사(cuite)로 조리법 추가."),
("B1", "Je vous conseille l'œuf mayonnaise.", "달걀 마요네즈를 권해요.", "conseiller = 권하다. 추천 표현: « je vous conseille / je vous recommande ». 구어: « prenez plutôt... »."),
("B1", "Ça ressemble à une soupe très lisse.", "아주 매끈한 수프 같은 거예요.", "ressembler à = ~를 닮다. 모르는 단어를 이미 아는 것에 비유해 설명할 때. 이 화에서는 « c'est comme... » 도 사용."),
("B1", "Je demande à la cuisine.", "주방에 물어볼게요.", "홀과 주방의 소통. demander à + 장소. 확신이 없으면 추측하지 않고 확인한다."),
("B1", "à la place de / sinon", "~ 대신에 / 그렇지 않으면 (그게 아니면)", "대안 제시의 필수 연결어. « Sinon, vous pouvez prendre l'omelette. » 처럼 쓴다."),
("B1", "Compliments à la cheffe.", "셰프님께 찬사를 전해 주세요.", "식사 후 셰프에게 전하는 정중한 인사. cheffe 는 여성형(요즘 쓰임이 늘어남)."),
("B1", "C'est quoi, ... ?", "~가 뭐예요?", "[구어] 모르는 말을 물을 때. ↔ 정중: Qu'est-ce que c'est que... ? / Pouvez-vous m'expliquer... ?"),
("B2", "Pas de souci.", "문제 없어요.", "[구어] 가벼운 안심 표현. ↔ 정중: Il n'y a pas de problème. 손님에게는 Je vous en prie 가 더 안전."),
("B2", "Toujours demander, jamais deviner.", "항상 묻고, 짐작하지 말 것.", "알레르기·식이 제한이 있는 손님 응대의 원칙. 두 부정사(infinitif) 로 간단히 만든 구호."),
("B2", "Vous sauvez ma journée.", "제 하루를 구해 주시네요.", "과장된 감사 표현. sauver = 구하다. 영어 'you made my day' 와 비슷."),
("B2", "se débrouiller", "혼자 힘으로 해결하다", "« Se débrouiller » 는 도움 없이 방법을 찾는 것. 구어에서 « Je me débrouille en français » (프랑스어를 그럭저럭 해요) 로 쓴다."),
("B2", "au cas où", "만일을 대비해", "« Je reste à côté, au cas où. » au cas où + 조건법 / 단독 사용 가능. 구어에서 자주 등장."),
("C1", "à l'envers", "거꾸로, 뒤집어서", "« une tarte à l'envers » = 타르트 타탱의 유래. 관용구: tout est à l'envers (모든 게 엉망이다)."),
("C1", "Je vous le dis tout à l'heure.", "이따가 말씀드릴게요.", "tout à l'heure 는 '조금 전' 과 '조금 후' 모두 가능, 시제로 구분. 문맥에서 미래를 가리킴."),
]

GRAM = [
("A2", "부정 뒤에는 de: ne ... pas de + 명사", "« Moi, je ne mange pas de viande. » « Pas de viande du tout ? » 긍정문의 du/de la/des 는 부정에서 de/d' 로 바뀐다. 식습관이나 알레르기를 말할 때 반복해서 쓴다."),
("B1", "설명하는 문형: C'est + 부분관사 + 재료", "« C'est de la viande de porc, cuite au four. » « C'est une soupe très douce. » « C'est un œuf dur avec une sauce froide. » 음식 이름을 모를 때 '무엇으로 만든 것인가' 를 말하는 틀. 이 화에서는 « sans viande » (고기 없이), « avec du miel » (꿀과 함께) 도 함께 쓴다."),
("B1", "대안 제시: ou, sinon, à la place", "« Une salade de chèvre chaud, ou une omelette aux champignons. » « Sinon, vous pouvez prendre... » 선택지는 ou 로 나열하고, 안 되는 경우에는 sinon 으로 돌려서 다른 길을 연다. 이 화의 Hélène 은 « Je peux faire une omelette » 로 칠판에 없는 대안을 낸다."),
("A2", "길 안내 명령형", "« Vous sortez d'ici, vous tournez à gauche. Tout droit, deux cents mètres. » 길 안내는 vous + 현재형으로 말해도 명령처럼 들린다. 순서는 d'abord, ensuite, puis 로 이어 붙인다."),
("B1", "외국인과 말할 때의 전략", "« Je parle lentement, d'accord ? » « Tu peux mimer, ou montrer sur l'ardoise. » 천천히, 쉬운 단어, 몸짓, 그림, 되묻기. 영어 단어가 섞여도 프랑스어로 돌아가 계속 이어 간다."),
("B2", "부정 강조: Même pas / Pas du tout", "« Même pas de poisson ? » « Pas du tout, c'est délicieux. » 부정 강조의 구어 표현. 단답으로 쓰기 쉬워 외국인 응대에서 유용하다."),
("B1", "대과거로 장난스럽게 확인하기: Je vous l'avais dit", "« Vous voyez ? Je vous l'avais dit. » plus-que-parfait (대과거) 는 '이미 말했던 일' 을 강조할 때 쓴다. 장난스러운 어조로 상대를 안심시키는 표현."),
]

READ = [
("리에종 — vous_avez, c'est_un", "« Vous avez / un problème ? » 에서 vous 의 s 가 z 로 변해 avez 와 이어져 [vu-za-ve] 처럼 읽는다. « C'est un œuf dur » 는 [sɛ-tœ̃-nœf]. 외국인 손님 앞에서는 박자를 또박또박, 단어 경계는 이어서."),
("비음 — pain, vin, soupe", "« Du pain grillé, un verre de vin. » pain [pɛ̃], vin [vɛ̃] 는 같은 비음 [ɛ̃]. 입은 반쯤 열고 코로 소리를 보내되 n 은 발음하지 않는다. « un instant » 의 un [œ̃] 도 비음."),
("r 발음 — Parker, Paris, rue", "« Pardon, l'hôtel Voltaire ? » 에서 pardon 의 r 은 목구멍 뒤를 가볍게 마찰시킨다. « la deuxième rue à droite » 의 rue, droite 의 r 도 같은 소리. 천천히 말할 때 특히 또렷하게."),
("u / ou — sous, tout, rue", "« Tout droit » 의 tout [tu] 는 입술을 모아 '우', « rue » [ʁy] 의 u 는 입술은 모으고 혀는 '이' 자리에. « sans viande » 와 « rue » 에서 모음 대비를 연습한다."),
("억양 — 질문과 안내", "« Vous parlez anglais ? » 는 끝을 올리고, « Tout droit, / deux cents mètres. » 처럼 길 안내는 구간마다 내려서 단호하게 끝낸다. 외국인에게는 억양을 확실히 할수록 이해가 쉽다."),
("호흡 구간 — 긴 안내 문장", "« Vous sortez d'ici, / vous tournez à gauche. / Tout droit, / deux cents mètres. » 처럼 짧게 끊어 읽는다. « Ensuite, / vous prenez la deuxième rue à droite. / L'hôtel est en face de la boulangerie. » 도 세 덩어리."),
("낭독 포인트 — 숫자 읽기", "이 화에서는 숫자를 단어로 쓴다. « deux cents mètres » 에서 cents 의 s 는 뒤에 mètres 가 오면 소리 나지 않는다. « vingt-quatre » 는 [vɛ̃t-katʁ], « quinze heures » 는 [kɛ̃-zœʁ] 로 이어진다."),
]

CULTURE = [
("« menu » 와 « carte » — 영어 화자가 헷갈리는 두 단어", "프랑스에서 la carte 는 전체 메뉴판, le menu 는 정해진 가격의 세트(formule) 를 뜻한다. 영어의 'menu' 와 달라서 외국인 손님이 자주 혼동한다. 응대 직원은 이 차이를 짧게 설명해 주는 것이 좋다."),
("채식과 파리의 비스트로", "전통 비스트로의 메뉴는 고기 중심이라 채식 손님이 선택지를 찾기 어렵다. 그래서 주방에 직접 물어 칠판에 없는 오믈렛이나 샐러드를 부탁하는 일이 흔하다. 육수 같은 숨은 재료 확인이 중요하다."),
]

META = dict(part=1, ep=11, part_label="제1부 Mise en place · 봄", title_fr="Un touriste perdu", title_ko="길 잃은 여행자",
 place="Le Comptoir de Marthe · 5월 토요일 점심 테라스(13 h 20 ~ 15 h)", chars="Chloé Dubois (22, 견습 서버) · Julien Benali (33, 홀 매니저) · Hélène Marchand (42, 주인 셰프) · M. Parker (미국인 여행자)", wine="길을 잃은 미국인에게 메뉴를 설명하고 대안을 제시하며 길까지 안내한다",
 focus="음식 설명 문형(C'est ...) · 대안 제시(ou/sinon) · 외국인 응대 전략 · 길 안내 표현",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제12화 « Anniversaire surprise » : 클로에를 위한 깜짝 생일 케이크 작전")
