# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, K = "Hélène", "Julien", "Chloé", "Karim"
D = [
(None, "Vendredi de fin mai, 14 h 50. Le service du midi est fini. Chloé vient de partir acheter des citrons. Julien, Karim et Hélène sont seuls dans la cuisine.", "5월 말 금요일, 14시 50분. 점심 영업이 끝났다. 클로에는 막 레몬을 사러 나갔다. 줄리앙, 카림, 엘렌만 주방에 남아 있다."),
(J, "Vite, vite, elle revient dans vingt minutes. J'ai un truc à vous dire.", "빨리, 빨리, 20분 뒤면 돌아와요. 할 말이 있어요."),
(H, "Quoi encore ? J'ai la caisse à faire.", "또 뭐예요? 정산해야 하는데."),
(J, "Aujourd'hui, c'est l'anniversaire de Chloé. Elle a vingt-trois ans.", "오늘이 클로에 생일이에요. 스물세 살이 돼요."),
(K, "Sérieux ? Elle n'a rien dit.", "진짜요? 아무 말도 안 했는데."),
(J, "Elle ne dit jamais rien. Mais j'ai vu sa fiche de personnel.", "원래 아무 말 안 하죠. 그런데 직원 서류에서 봤어요."),
(H, "Et alors ? Tu veux qu'on fasse quoi ?", "그래서요? 우리가 뭘 하길 바라는데요?"),
(J, "Une surprise, Hélène. Un gâteau, des bougies, la totale.", "깜짝 파티요, 엘렌. 케이크, 초, 풀코스로요."),
(H, "Un gâteau pendant le service ? On n'a pas le temps.", "영업 중에 케이크라니요? 시간이 없어요."),
(K, "Moi, je peux le faire. Je vais le préparer cet après-midi.", "제가 할 수 있어요. 오늘 오후에 만들게요."),
(H, "Tu vas préparer quoi, exactement ?", "정확히 뭘 만들 건데요?"),
(K, "Un fraisier. Les gariguettes sont arrivées ce matin. Elles sont magnifiques.", "프레지에요. 가리게트 딸기가 오늘 아침에 들어왔는데 아주 훌륭해요."),
(H, "Un fraisier, c'est une génoise, une crème mousseline... Ça prend trois heures.", "프레지에는 제누아즈에 무슬린 크림이... 세 시간 걸려요."),
(K, "Je sais. Je vais commencer tout de suite, et je vais le finir avant dix-huit heures.", "알아요. 지금 바로 시작해서 6시 전에 끝낼게요."),
(J, "Parfait. Moi, je vais occuper Chloé pendant ce temps.", "좋아요. 저는 그동안 클로에를 붙잡아 둘게요."),
(H, "Tu vas l'occuper comment ? Elle n'est pas bête.", "어떻게 붙잡아 둘 건데요? 바보 아니에요, 그 애."),
(J, "Je vais lui demander de redresser toute la cave. Elle va y passer une heure.", "지하 창고를 전부 정리해 달라고 할 거예요. 한 시간은 걸릴 테니까요."),
(K, "Pauvre Chloé. Le jour de son anniversaire, la cave !", "불쌍한 클로에. 생일에 창고라니!"),
(J, "C'est pour la bonne cause, Karim. Après, elle va avoir une belle surprise.", "좋은 일을 위해서야, 카림. 그 뒤에 멋진 깜짝 선물이 있을 테니까."),
(H, "D'accord. Mais je pose mes conditions. Pas de chantilly partout.", "좋아요. 하지만 조건이 있어요. 휘핑크림을 사방에 묻히지 마요."),
(K, "Promis, patronne. Je vais faire attention.", "약속해요, 사장님. 조심할게요."),
(H, "Et pas de bougies sur le plan de travail. Je vais te surveiller.", "그리고 작업대 위에 초는 안 돼요. 내가 지켜볼 거예요."),
(K, "Compris. Elle va adorer, vous allez voir.", "알겠어요. 그 친구 아주 좋아할 거예요, 두고 보세요."),
(J, "On va faire ça à vingt et une heures, au moment du dessert.", "9시에, 디저트 시간에 하죠."),
(H, "Pourquoi pas plus tôt ? Il y a du monde à vingt et une heures.", "왜 더 일찍 안 하고요? 9시에는 손님이 많은데요."),
(J, "Justement. Les clients vont chanter avec nous. Ce sera plus joyeux.", "바로 그래서요. 손님들도 같이 노래해 줄 거예요. 더 즐거울 거예요."),
(K, "Moi, je viens avec le gâteau. Julien, tu éteins les lumières.", "저는 케이크를 들고 갈게요. 줄리앙은 불을 꺼요."),
(J, "Et toi, Hélène, tu vas chanter ?", "그럼 엘렌은요? 노래 부를 거예요?"),
(H, "Moi ? Jamais. Je vais applaudir, c'est déjà beaucoup.", "나요? 절대로. 박수 칠 거예요, 그것도 대단한 거죠."),
(K, "Allez, Hélène. Un petit « joyeux anniversaire » ne va pas te tuer.", "에이, 엘렌. 『생일 축하해』 한 번 한다고 죽지 않아요."),
(H, "On verra. Bon, au travail. Karim, la farine est sous l'étagère.", "두고 봅시다. 자, 일해요. 카림, 밀가루는 선반 밑에 있어요."),
(J, "Et pour le cadeau, j'ai déjà acheté un carnet bleu hier.", "선물은 제가 어제 파란 수첩을 이미 사 뒀어요."),
(H, "Un carnet ? Bonne idée. Elle écrit tout dans son petit carnet.", "수첩이라고요? 좋은 생각이에요. 그 애는 작은 수첩에 다 적으니까."),
(K, "Et si elle demande pourquoi on est bizarres ?", "그런데 우리가 왜 이상하냐고 물으면요?"),
(J, "On va dire qu'on prépare la carte d'été.", "여름 메뉴를 준비한다고 하죠."),
(H, "Moi, je ne dirai rien. C'est ma spécialité.", "나는 아무 말도 안 할 거예요. 그게 내 특기니까."),
(K, "Ça, c'est vrai. Tout le monde le sait.", "그건 맞아요. 다들 아는 사실이죠."),
(J, "Bon, ce n'est pas tout. Elle revient vite, on se met au travail.", "자, 이게 다가 아니에요. 곧 돌아오니까 일을 시작해요."),
(H, "Allez. Et que personne ne parle de gâteau devant elle.", "그럼 시작해요. 그리고 아무도 그 애 앞에서 케이크 얘기는 하지 마요."),
(None, "Plus tard. Chloé revient, essoufflée, avec un sachet de citrons. Karim cache vite un saladier derrière son dos.", "얼마 뒤. 클로에가 숨을 헐떡이며 레몬 봉지를 들고 돌아온다. 카림이 재빨리 믹싱볼을 등 뒤로 숨긴다."),
(C, "Me voilà ! J'ai trouvé des citrons. Mais ils sont chers aujourd'hui.", "다녀왔어요! 레몬을 구했는데 오늘은 비싸더라고요."),
(J, "Merci, Chloé. Tu vas les mettre au frigo. Ensuite, direction la cave.", "고마워, 클로에. 냉장고에 넣어 줘. 그다음엔 지하 창고로 가."),
(C, "La cave ? Maintenant ? Mais on a la mise en place pour ce soir.", "창고요? 지금요? 저녁 준비해야 하는데요."),
(J, "La mise en place, c'est moi. Là-bas, les bouteilles sont en désordre.", "준비는 내가 할게. 거기 아래 병들이 엉망이거든."),
(C, "D'accord. Mais pourquoi Karim est tout rouge ?", "알겠어요. 그런데 카림은 왜 얼굴이 빨개요?"),
(K, "Moi ? Rien. C'est la chaleur. Je suis en train de faire... du pain.", "나? 아무것도. 더워서 그래. 지금... 빵 만드는 중이야."),
(C, "Du pain ? Mais Karim, tu as de la farine sur le nez.", "빵이요? 그런데 카림, 코에 밀가루가 묻었어요."),
(K, "Ah ? Merci. Je vais m'essuyer.", "아, 그래? 고마워. 닦을게."),
(C, "Et ça sent la fraise, ici. Pourquoi ça sent la fraise ?", "그리고 여기서 딸기 냄새가 나요. 왜 딸기 냄새가 나죠?"),
(H, "Les fraises sont arrivées ce matin, Chloé. Va à la cave.", "딸기가 오늘 아침에 들어왔어, 클로에. 지하 창고로 가."),
(C, "Bon, bon, j'y vais. Vous êtes bizarres aujourd'hui.", "알았어요, 갈게요. 오늘 다들 이상해요."),
(K, "Ouf. Elle va tout deviner, je te dis.", "휴. 분명 다 눈치챌 거예요."),
(J, "Mais non. Elle est jeune, elle pense à autre chose.", "아니에요. 어리니까 다른 생각 중일 거예요."),
(H, "Karim, ton nez. Il y a encore de la farine.", "카림, 코에 아직 밀가루가 있어요."),
(K, "Putain, je suis nul pour mentir. Je n'ai jamais su faire.", "젠장, 나는 거짓말에 소질이 없어. 한 번도 잘한 적이 없다니까."),
(J, "Ne t'inquiète pas. Le gâteau va sauver la situation.", "걱정 마. 케이크가 상황을 구해 줄 거야."),
(None, "Vers dix-huit heures. Chloé remonte de la cave, un peu triste. Julien range les verres au bar.", "저녁 6시쯤. 클로에가 조금 시무룩한 얼굴로 지하에서 올라온다. 줄리앙이 바에서 유리잔을 정리하고 있다."),
(C, "C'est fini, la cave est rangée. Il y avait beaucoup de poussière.", "끝났어요, 창고 정리했어요. 먼지가 엄청 많았어요."),
(J, "Merci, Chloé. Tu as fait du bon travail.", "고마워, 클로에. 일 잘했어."),
(C, "Julien, tu sais quel jour on est aujourd'hui ?", "줄리앙, 오늘이 무슨 날인지 알아요?"),
(J, "Vendredi. Pourquoi ? Tu as un rendez-vous ?", "금요일이지. 왜? 약속 있어?"),
(C, "Non. C'est mon anniversaire, en fait. Mais ce n'est pas grave.", "아니요. 사실 오늘 제 생일이에요. 하지만 별일 아니에요."),
(J, "Ah bon ? C'est ton anniversaire ? Mais pourquoi tu n'as rien dit ?", "그래? 오늘이 생일이야? 왜 아무 말도 안 했어?"),
(C, "Je n'aime pas faire des histoires. Et ici, tout le monde travaille.", "법석 떠는 거 안 좋아해요. 그리고 여기선 다들 일하잖아요."),
(J, "Quel âge tu as ?", "몇 살이야?"),
(C, "Vingt-trois ans. Ma mère m'a appelée ce matin, c'est déjà bien.", "스물세 살이요. 어머니가 아침에 전화하셨어요, 그것만으로도 좋아요."),
(J, "Tu vas fêter ça ce soir, au moins ? Avec des amis ?", "그래도 오늘 밤에 파티는 하겠지? 친구들이랑?"),
(C, "Non, je vais rentrer directement. Je suis fatiguée après la cave.", "아니요, 바로 집에 갈 거예요. 창고 때문에 피곤해서요."),
(J, "Dommage. Tu aurais mérité une belle soirée.", "아쉽네. 멋진 저녁을 보낼 자격이 있는데."),
(C, "Ce n'est pas grave, vraiment. Je vais mettre ma chemise propre.", "정말 괜찮아요. 깨끗한 셔츠로 갈아입을게요."),
(K, "Pauvre petite. On va se rattraper ce soir.", "가엾은 아이. 오늘 밤에 만회하자."),
(H, "Concentre-toi sur les fraises. Elles doivent être bien droites.", "딸기에 집중해요. 똑바로 세워야 해요."),
(K, "Elles sont droites. Regarde, c'est parfait.", "똑바로 섰어요. 봐요, 완벽해요."),
(H, "Pas mal. Tu as bien travaillé, Karim.", "나쁘지 않네요. 잘했어요, 카림."),
(K, "Merci, Chef. Je vais le mettre au frigo jusqu'à vingt et une heures.", "고마워요, 셰프. 9시까지 냉장고에 넣어 둘게요."),
(H, "Et les bougies ? Tu les as achetées ?", "초는요? 샀어요?"),
(K, "Oui, vingt-trois petites bougies rouges. Elles vont faire un beau feu d'artifice.", "네, 작은 빨간 초 스물세 개요. 멋진 불꽃놀이가 될 거예요."),
(H, "Pas trop près du rideau, hein. Je ne veux pas d'incendie.", "커튼 너무 가까이엔 놓지 말아요. 불나는 건 싫으니까."),
(None, "Vingt et une heures. La salle est pleine. Julien fait signe à Karim depuis le bar.", "밤 9시. 홀이 가득 찼다. 줄리앙이 바에서 카림에게 신호를 보낸다."),
(J, "Chloé, viens m'aider à servir les cafés de la douze, s'il te plaît.", "클로에, 12번 테이블 커피 서빙 좀 도와줘."),
(C, "J'arrive. Ils sont combien, à la douze ?", "갈게요. 12번에 몇 분이에요?"),
(J, "Six. Prends le grand plateau. Va devant, je te suis.", "여섯 명. 큰 쟁반 가져가. 먼저 가, 따라갈게."),
(C, "Pourquoi tout est éteint, tout à coup ? Il y a une panne ?", "왜 갑자기 다 꺼졌죠? 정전이에요?"),
(K, "Pas de panne, Chloé. Regarde derrière toi.", "정전 아니야, 클로에. 뒤를 봐."),
(C, "Quoi ? Oh... Oh, non !", "뭐요? 오... 오, 세상에!"),
(None, "Karim arrive avec le fraisier, vingt-trois bougies allumées. Les clients chantent « Joyeux anniversaire ». Hélène applaudit sur le seuil de la cuisine.", "카림이 스물세 개의 촛불을 켠 프레지에를 들고 나타난다. 손님들이 『생일 축하합니다』를 부른다. 엘렌은 주방 입구에서 박수를 친다."),
(J, "Joyeux anniversaire, Chloé !", "생일 축하해, 클로에!"),
(K, "Bon anniversaire ! Fais un vœu avant de souffler.", "생일 축하해! 불기 전에 소원 빌어."),
(C, "Mais... c'est pour moi ? Vous avez fait un gâteau ?", "그런데... 저를 위한 거예요? 케이크를 만든 거예요?"),
(J, "C'est Karim qui l'a fait. Un fraisier, spécialement pour toi.", "카림이 만들었어. 너를 위한 특별한 프레지에야."),
(C, "Je suis tellement émue. Je ne sais pas quoi dire.", "너무 감동했어요. 무슨 말을 해야 할지 모르겠어요."),
(K, "Dis merci, et souffle vite. La cire coule sur les fraises.", "고맙다고 하고 빨리 불어. 촛농이 딸기 위에 떨어지고 있어."),
(C, "J'ai fait mon vœu. Maintenant, je vais souffler.", "소원 빌었어요. 이제 불게요."),
(None, "Chloé souffle. Il reste trois bougies allumées. Tout le monde rit.", "클로에가 숨을 분다. 초 세 개가 아직 켜져 있다. 모두 웃는다."),
(J, "Trois bougies encore. Tu vas devoir faire un deuxième vœu.", "아직 세 개 남았네. 두 번째 소원을 빌어야겠어."),
(C, "Alors, je vais en faire un autre. Plus petit, plus modeste.", "그럼 하나 더 빌게요. 더 작고 소박한 걸로."),
(H, "Joyeux anniversaire, Chloé. Tous mes vœux de bonheur.", "생일 축하해, 클로에. 행복을 기원해."),
(C, "Hélène... merci. Tu as même applaudi !", "엘렌... 고마워요. 박수까지 쳐 줬네요!"),
(H, "Un peu. On est une équipe, ici. Une petite famille.", "조금. 여기선 우리 모두 한 팀이야. 작은 가족이지."),
(C, "Merci, Hélène. Je ne vais pas oublier ce jour.", "고마워요, 엘렌. 오늘을 잊지 않을게요."),
(K, "Attends, ce n'est pas fini. Julien, le cadeau.", "잠깐, 아직 끝이 아니야. 줄리앙, 선물."),
(J, "Voilà. C'est de la part de nous tous. Ouvre-le.", "자. 우리 모두가 주는 거야. 열어 봐."),
(C, "Un carnet ! Avec une couverture bleue. Il est magnifique.", "수첩이네요! 파란 표지로. 정말 멋져요."),
(J, "Pour tes mots nouveaux. Il y a de la place pour tout un livre.", "새로운 표현을 적으라고. 책 한 권은 쓸 수 있을 만큼 공간이 있어."),
(C, "J'ai une idée. Je vais écrire la première page tout de suite.", "아이디어가 있어요. 첫 페이지를 지금 바로 쓸게요."),
(K, "Écris quoi ? « Karim fait des gâteaux incroyables » ?", "뭐라고 쓸 거야? 『카림은 대단한 케이크를 만든다』?"),
(C, "Non. J'écris : « Anniversaire surprise : le plus beau cadeau, c'est la famille. »", "아니요. 이렇게 쓸 거예요. 『깜짝 생일: 가장 멋진 선물은 가족이다』."),
(H, "Elle est poétique, la petite. Bon, qui coupe le gâteau ?", "시적이네, 이 아이. 자, 누가 케이크를 자를까?"),
(C, "C'est moi qui coupe, c'est la tradition. Qui veut une part ?", "제가 자를게요, 전통이잖아요. 한 조각 드실 분?"),
(J, "Une minute, un toast d'abord. Karim, les coupes.", "잠깐, 먼저 건배해요. 카림, 잔 좀."),
(K, "Voilà, du crémant pour tout le monde. Un doigt chacun.", "여기, 모두에게 크레망이에요. 한 모금씩만."),
(J, "À Chloé ! Qu'elle reste longtemps avec nous.", "클로에를 위하여! 오래오래 우리와 함께하길."),
(H, "À Chloé ! Et qu'elle apprenne à dire non à Julien.", "클로에를 위하여! 그리고 줄리앙에게 싫다고 말하는 법도 배우길."),
(C, "Santé à vous tous ! Mais un petit peu seulement, je sers encore.", "모두를 위하여, 건배! 하지만 조금만요, 아직 서빙해야 하니까요."),
(K, "Un doigt, ça suffit. Santé !", "한 모금이면 충분해. 건배!"),
(J, "Santé ! À la famille du Comptoir.", "건배! 콩투아르 가족을 위하여."),
(J, "Tout le monde ! Et pour la table douze aussi.", "모두요! 12번 테이블에도 한 조각씩."),
(K, "Je vais en apporter à tous les clients. Ils ont chanté, ils le méritent.", "손님 모두에게 가져다드릴게요. 노래해 주셨으니 그럴 자격이 있어요."),
(C, "Karim, il est délicieux. Les fraises sont incroyables.", "카림, 정말 맛있어요. 딸기가 굉장해요."),
(K, "C'est grâce aux gariguettes. Mais merci, ça me fait plaisir.", "가리게트 딸기 덕분이야. 그래도 고마워, 기분 좋네."),
(H, "Bon, les enfants. Il est vingt-deux heures. Demain, on se lève tôt.", "자, 얘들아. 밤 10시야. 내일은 일찍 일어나야 해."),
(C, "Oui, Chef. Mais ce soir, je vais bien dormir.", "네, 셰프. 하지만 오늘 밤은 잘 잘 것 같아요."),
(J, "Tu vas rêver de fraises, c'est sûr.", "딸기 꿈을 꿀 게 확실해."),
(C, "Et de cave, aussi. Merci pour l'anniversaire, vraiment. Je vais le raconter à ma mère.", "그리고 창고 꿈도요. 생일 파티 정말 고마워요. 어머니께 이야기해 드릴 거예요."),
(K, "Dis-lui que le fraisier est une recette de Karim.", "어머니께 프레지에는 카림의 레시피라고 말씀드려."),
(H, "Allez, au rangement. Et Chloé... bon anniversaire.", "자, 정리하러 가요. 그리고 클로에... 생일 축하해."),
]

VOCAB = [
("A2", "Joyeux anniversaire !", "생일 축하해요!", "가장 기본적인 생일 인사. « Bon anniversaire ! » 도 같은 뜻으로 구어에서 더 자주 씀."),
("A2", "Tu as quel âge ?", "몇 살이야?", "친한 사이의 질문. ↔ 정중: Quel âge avez-vous ? 나이는 « J'ai vingt-trois ans. » 로 답한다."),
("A2", "Fais un vœu.", "소원을 빌어.", "faire un vœu = 소원을 빌다. 초를 끄기 전에 빈다. 명령형 fais(tu), faites(vous)."),
("A2", "Souffle les bougies.", "초를 불어.", "souffler = 불다. une bougie = 초. 생일 케이크 장면의 필수 어휘."),
("A2", "C'est pour toi.", "너를 위한 거야.", "선물을 줄 때의 가장 쉬운 표현. 앞 대화의 « spécialement pour toi » 와 함께."),
("A2", "Qui veut une part ?", "한 조각 드실 분?", "une part de gâteau = 케이크 한 조각. une tranche, un morceau 도 비슷하지만 케이크는 part 가 가장 자연스럽다."),
("A2", "Vingt et une heures", "밤 9시", "24시간제 읽기. 구어에서는 neuf heures du soir. 이 화에서 시간은 단어로 읽는다."),
("A2", "Ça sent la fraise.", "딸기 냄새가 나요.", "sentir + 관사 + 명사 = ~의 냄새가 나다. 이야기 속에서 비밀이 새는 단서가 된다."),
("A2", "Pas mal.", "나쁘지 않네요.", "[구어] 완곡한 칭찬. ↔ 정중: C'est assez bien. 엘렌의 무뚝뚝한 칭찬 스타일."),
("B1", "Tous mes vœux de bonheur.", "행복을 기원합니다.", "격식 있는 축하 인사. « tous mes vœux » 는 생일, 새해, 결혼 등에 폭넓게 쓰인다."),
("B1", "Je vais le préparer cet après-midi.", "오늘 오후에 준비할게요.", "futur proche: aller + 동사 원형. 곧 일어날 일이나 확실한 계획을 나타냄."),
("B1", "C'est pour la bonne cause.", "좋은 일을 위한 거예요.", "pour la bonne cause = 좋은 목적을 위해. 약간 힘든 일을 시킬 때 쓰는 변명이자 농담."),
("B1", "Je n'aime pas faire des histoires.", "법석 떠는 거 안 좋아해요.", "faire des histoires = 문제를 크게 만들다, 소란 피우다. 겸손한 성격을 표현."),
("B1", "On va se rattraper ce soir.", "오늘 밤에 만회하자.", "se rattraper = 만회하다, 보충하다. 잘못이나 부족함을 나중에 채울 때."),
("B1", "Ce n'est pas grave.", "별일 아니에요.", "[구어] « c'est pas grave » 로 줄어듦. ↔ 정중: Cela n'a pas d'importance. 속상함을 감출 때도 쓴다."),
("B2", "Je suis tellement émue.", "너무 감동했어요.", "ému(e) = 감동한. tellement 은 '너무'. 여자이므로 émue. 감정을 말로 표현하는 B2 표현."),
("B2", "Le gâteau va sauver la situation.", "케이크가 상황을 수습해 줄 거예요.", "sauver la situation = 상황을 수습하다. 구어로 « ça va le faire » (잘 될 거야)."),
("B2", "Tu aurais mérité une belle soirée.", "너는 멋진 저녁을 누릴 자격이 있었는데.", "조건법 과거 + mériter. 아쉬움과 공감을 담은 표현. 실제 대화에서는 « tu méritais mieux » 도 가능."),
("B2", "Je suis nul pour mentir.", "나는 거짓말에 소질이 없어.", "[속어] « Putain, je suis nul pour mentir » 의 putain. 쓸 수 있음: 가까운 주방 동료 사이 / 금지: 손님·상사·외부인 앞. [구어] être nul pour/en = 잘 못 하다 ↔ 정중: Je ne suis pas doué pour mentir."),
("B2", "Elle n'est pas bête.", "그 애 바보 아니에요.", "bête = 어리석은. 구어에서 « pas bête » 는 '똑똑하다' 는 칭찬. « Pas bête, l'idée ! » 와 같이도 쓴다."),
("C1", "la totale", "풀코스, 전부 다", "[구어] « On fait la totale » = 있는 것 전부 해 보자. 음식점에서는 풀 세트, 일상에서는 '모든 것'."),
("C1", "C'est grâce à ...", "~ 덕분이에요", "원인이 긍정적일 때 grâce à, 부정적이면 à cause de. 칭찬받았을 때 겸손하게 돌리는 표현."),
]

GRAM = [
("B1", "futur proche: aller + 동사 원형", "« Je vais le préparer cet après-midi. » « Elle va y passer une heure. » « Tu vas chanter ? » 가까운 미래·계획·확신은 aller 현재형 + 원형. 부정은 « Je ne vais pas oublier. » (구어: « Je vais pas oublier »). 이 화에서 가장 많이 반복되는 문형."),
("A2", "축하·바람 표현", "« Joyeux anniversaire ! » « Bon anniversaire ! » « Tous mes vœux de bonheur. » « Fais un vœu. » 생일은 joyeux/bon, 새해·결혼 등에는 « Tous mes vœux ». 소원은 faire un vœu."),
("B1", "명령형 tu: -er 동사의 -s 탈락", "« Souffle les bougies. » « Dis merci. » « Attends. » « Fais un vœu. » -er 동사의 tu 명령형은 -es 가 아니라 -e (souffle). 불규칙 dire → dis, faire → fais, attendre → attends. 부정은 « Ne t'inquiète pas. »."),
("B1", "장소 대명사 y", "« Elle va y passer une heure. » (y = à la cave) « Je vais y aller. » 장소를 대신하는 y 는 동사 바로 앞. « Bon, bon, j'y vais. » 처럼 반복되는 형태를 익힌다."),
("A2", "시간 표현: 분·시 읽기", "« Vingt et une heures. » « Dix-huit heures. » « Dans vingt minutes. » 24시간제는 공공 안내와 영업시간에, 구어에서는 neuf heures du soir 로 바꾼다. 21 = vingt et une 에서 et 와 heures 의 이어짐 주의."),
("B2", "조건법 과거: aurais mérité", "« Tu aurais mérité une belle soirée. » 실제로는 이루어지지 않은 일에 대한 아쉬움. 조건법 현재 « tu mériterais » 보다 과거 사실에 초점. 구어에서는 imparfait 로 대신하기도 한다."),
("B1", "c'est + 사람 + qui (강조 구문)", "« C'est Karim qui l'a fait. » « C'est moi qui coupe. » 주어를 강조할 때. 일반 문장 « Karim l'a fait. » 보다 책임과 공을 분명히 드러낸다."),
]

READ = [
("리에종 — vingt_et_une_heures", "« Vingt et une heures » 는 [vɛ̃-te-yn-œʁ] 로 거의 한 덩어리처럼 이어 읽는다. 앞의 vingt 의 t 는 et 앞에서는 소리 나지 않는다. 낭독에서는 숫자를 또렷하게, 이어 읽는 연습을 한다."),
("비음 — anniversaire, vingt, fraise", "« Joyeux anniversaire ! » 에서 an [ɑ̃] 이 나오지 않는 점에 주의. anniversaire 는 [a-ni-vɛʁ-sɛʁ]. 반면 « Vingt-trois ans » 의 vin 과 an 은 각각 [ɛ̃], [ɑ̃] 비음. 코로 소리를 보내는 감각을 연습."),
("r 발음 — Karim, cire, parfait", "« Karim fait un fraisier. » 에서 Karim 의 r 은 가볍게 긁는 소리. « C'est parfait » 의 parfait [paʁ-fɛ] 도 마찬가지. 억양을 올릴 때 r 이 강해지지 않게 부드럽게."),
("u / ou — surprise, vous, bougie", "« Une surprise pour vous. » 에서 surprise 의 u [y] 와 vous 의 ou [u] 를 구분한다. u 는 입술을 모으고 혀를 앞에, ou 는 입술을 모으고 혀를 뒤에. « La bougie » 의 ou 는 [u]."),
("억양 — 놀람과 감동", "« Mais... c'est pour moi ? » 는 끝을 올리며 믿기지 않는 억양, « Oh... Oh, non ! » 은 길게 끌며 떨림을 담는다. « Je suis tellement émue. » 는 낮게 시작해 천천히 내려오는 억양."),
("호흡 구간 — 계획 말하기", "« Je vais commencer tout de suite, / et je vais le finir / avant dix-huit heures. » 처럼 세 덩어리로. « Tu vas les mettre au frigo. / Ensuite, / direction la cave. » 도 짧게 끊어 읽으면 명령의 리듬이 산다."),
("노래 — Joyeux anniversaire", "노래 가사 « Joyeux anniversaire » 는 모든 음절을 길게 늘이고 « joyeux » 의 eux [ø] 에 입술을 둥글게 모아 소리를 낸다. 낭독에서는 음정 없이 박자만 살려 천천히 발음한다."),
]

CULTURE = [
("프랑스의 생일 문화 — 케이크와 « Joyeux anniversaire »", "프랑스에서도 생일에는 케이크와 초를 준비하고 « Joyeux anniversaire » 를 부른다. 주인공은 소원을 빌고 초를 불며, 한 번에 다 끄지 못하면 소원이 이루어지지 않는다고 농담한다. 레스토랑에서는 손님과 직원이 함께 노래하는 경우도 흔하다."),
("프레지에 — 5월의 딸기 케이크", "fraisier 는 제누아즈와 무슬린 크림, 딸기를 층층이 쌓은 프랑스 대표 케이크로, 가리게트(gariguette) 딸기가 나오는 5월 무렵에 특히 인기가 많다. 제철 재료를 존중하는 프랑스 요리의 태도를 보여 준다."),
]

META = dict(part=1, ep=12, part_label="제1부 Mise en place · 봄", title_fr="Anniversaire surprise", title_ko="깜짝 생일 파티",
 place="Le Comptoir de Marthe · 5월 말 금요일(14 h 50 ~ 22 h)", chars="Hélène Marchand (42, 주인 셰프) · Julien Benali (33, 홀 매니저) · Karim Haddad (27, 부주방장) · Chloé Dubois (22, 견습 서버, 오늘 23세가 됨)", wine="클로에의 생일을 모르는 척 준비하는 직원들의 깜짝 케이크 작전",
 focus="futur proche(aller + 동사 원형) · 축하 표현 · 명령형(tu) · 생일 어휘",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제13화 « Dimanche en famille » : 일요일 브런치에 온 가족 손님과 아이들, 취향을 묻는 표현")
