# -*- coding: utf-8 -*-
# (speaker, french, korean); speaker None => stage direction (not a turn)
H, J, C, K = "Hélène", "Julien", "Chloé", "Karim"
D = [
(None, "Samedi 13 juin, 23 h 10. Le dernier client vient de partir. Les chaises de la terrasse sont empilées, la salle est silencieuse.", "6월 13일 토요일 밤 11시 10분. 마지막 손님이 막 떠났다. 테라스 의자는 포개져 있고 홀은 조용하다."),
(J, "Voilà, la dernière table vient de partir. Je ferme à clé ?", "자, 마지막 테이블이 막 나갔어. 문 잠글까?"),
(H, "Oui, ferme. Et on fait le bilan avant de partir.", "응, 잠가. 그리고 가기 전에 정산부터 하자."),
(C, "Je range les menus. Mes jambes ne répondent plus.", "메뉴판 정리할게요. 다리가 말을 안 들어요."),
(H, "C'est normal, un samedi de juin. Ça a donné combien de couverts ?", "6월 토요일이니 당연하지. 손님이 몇 명이었어?"),
(J, "Je regarde. Midi, 46 couverts. Ce soir, 58.", "볼게. 점심 46명, 저녁 58명이야."),
(K, "Cent quatre couverts ! Mon dos le sait très bien.", "104명이라니! 제 허리가 아주 잘 알고 있어요."),
(H, "Cent quatre. Et le total de la journée ?", "104명. 그럼 하루 총액은?"),
(J, "J'imprime le ticket Z... Voilà : 3 100 € pour la journée.", "Z 영수증 뽑을게... 자, 하루 3,100유로야."),
(C, "Trois mille cent euros ! C'est un record ?", "3천백 유로요! 신기록이에요?"),
(J, "Pas encore. Mais c'est notre meilleur samedi depuis mars.", "아직은 아니야. 하지만 3월 이후 최고의 토요일이야."),
(H, "Samedi dernier, on avait fait combien ?", "지난 토요일엔 얼마였지?"),
(J, "2 840 €. Donc 260 € de plus cette semaine.", "2,840유로였어. 그러니까 이번 주가 260유로 더 많아."),
(H, "Dix pour cent de 2 840, c'est 284. Donc un peu moins de dix pour cent.", "2,840의 10퍼센트는 284야. 그러니까 10퍼센트보다 조금 적게 늘었네."),
(C, "Comment tu calcules ça si vite ? Moi, je prends mon téléphone.", "어떻게 그렇게 빨리 계산해? 나는 전화기를 꺼내는데."),
(H, "Vingt ans de cuisine. Au bout d'un moment, les chiffres, on les connaît.", "요리 20년이야. 시간이 지나면 숫자는 몸에 배."),
(K, "Et il a fait beau. Les gens adorent la terrasse en juin.", "그리고 날씨도 좋았죠. 6월엔 다들 테라스를 좋아하니까요."),
(J, "Ce soir, on a vendu vingt-sept îles flottantes. Un record, ça aussi.", "오늘 저녁엔 일 플로탕트를 스물일곱 개나 팔았어. 이것도 신기록이야."),
(H, "Vingt-sept ? Il me reste six œufs. Il faudra en racheter lundi.", "스물일곱? 달걀이 여섯 개 남았네. 월요일에 사야겠다."),
(K, "Lundi, c'est fermé. Tu feras les courses mardi à l'ouverture.", "월요일은 휴무예요. 화요일 오픈 전에 장 보시면 되죠."),
(H, "Tu as raison. Bon, passons à la caisse.", "맞아. 자, 계산대로 가자."),
(J, "D'abord, la répartition. Carte bancaire : 2 140 €. Espèces : 610 €.", "먼저 결제 수단별로. 카드 2,140유로. 현금 610유로."),
(J, "Et les tickets-restaurant : 350 €. Trente-cinq titres de 10 €.", "그리고 식권이 350유로. 10유로짜리 서른다섯 장."),
(C, "Je fais l'addition : 2 140 plus 610, ça fait 2 750.", "제가 더해 볼게요. 2,140 더하기 610은 2,750이에요."),
(C, "Et 2 750 plus 350, ça fait 3 100. Ça tombe juste !", "그리고 2,750 더하기 350은 3,100. 딱 맞아요!"),
(H, "Parfait. Maintenant, on compte le tiroir. Le fond de caisse, ce matin ?", "좋아. 이제 서랍을 세자. 아침 시재는 얼마였지?"),
(J, "150 €, comme tous les jours. Donc il doit y avoir 760 €.", "매일 그렇듯 150유로야. 그러니까 760유로가 있어야 해."),
(C, "Je peux compter ? J'adore compter les billets.", "제가 세 봐도 돼요? 지폐 세는 거 좋아해요."),
(H, "Vas-y. À voix haute, pour qu'on t'entende.", "해 봐. 우리가 들을 수 있게 소리 내서."),
(C, "Six billets de cinquante : trois cents euros.", "50유로 지폐 여섯 장. 300유로."),
(C, "Douze billets de vingt : deux cent quarante. Ça fait cinq cent quarante.", "20유로 지폐 열두 장. 240. 그러면 540."),
(C, "Dix billets de dix : cent. Donc six cent quarante.", "10유로 지폐 열 장. 100. 그러니까 640."),
(C, "Quatre billets de cinq : vingt. Six cent soixante.", "5유로 지폐 네 장. 20. 660."),
(C, "Et les pièces : trente de deux euros, soixante. Quarante d'un euro, quarante.", "그리고 동전. 2유로 서른 개, 60. 1유로 마흔 개, 40."),
(C, "Six cent soixante, plus cent de pièces : sept cent soixante !", "660에 동전 100을 더하면, 760!"),
(J, "Sept cent soixante, moins cent cinquante de fond de caisse : 610 €.", "760에서 시재 150을 빼면 610유로."),
(H, "Ça correspond aux espèces du ticket Z. La caisse est juste.", "Z 영수증의 현금과 일치해. 계산대가 정확해."),
(K, "Bravo, Chloé. Il y a six mois, tu comptais sur tes doigts.", "잘했어, 클로에. 반년 전엔 손가락으로 세던 애가."),
(C, "Six mois ? Je suis arrivée en avril ! Ça fait deux mois et demi.", "반년이요? 저 4월에 왔는데요! 두 달 반밖에 안 됐어요."),
(K, "Ça fait longtemps, quand on est dans un coup de feu.", "정신없이 바쁘면 오래된 것 같거든."),
(H, "Passons aux pourboires. Julien ?", "팁으로 넘어가자. 쥘리앵?"),
(J, "En carte, 85 €. Dans le pot en espèces, 63 €. Donc 148 € en tout.", "카드로 85유로. 현금 통에는 63유로. 합계 148유로."),
(C, "Cent quarante-huit. On partage comment ?", "148유로. 어떻게 나눠요?"),
(H, "En quatre parts égales : Julien, Karim, toi et Moussa à la plonge.", "네 몫으로 똑같이. 쥘리앵, 카림, 너, 그리고 설거지 담당 무사."),
(C, "Et toi, Hélène ? Tu ne prends rien ?", "엘렌은요? 아무것도 안 가져가요?"),
(H, "Moi, je suis la patronne. Les pourboires sont pour l'équipe.", "나는 사장이잖아. 팁은 팀 몫이야."),
(J, "148 divisé par quatre, ça fait 37 € chacun.", "148을 넷으로 나누면 한 사람당 37유로야."),
(C, "Trente-sept euros ! C'est mon meilleur samedi !", "37유로! 제 최고의 토요일이에요!"),
(K, "Qu'est-ce que tu vas faire de ton argent ?", "그 돈으로 뭐 할 거야?"),
(C, "Je vais m'acheter un vrai dictionnaire. Mon carnet est presque plein.", "진짜 사전을 하나 살 거예요. 수첩이 거의 다 찼거든요."),
(J, "Un dictionnaire ! À vingt-deux ans, tu es sérieuse.", "사전이라니! 스물두 살에 참 진지하네."),
(C, "Et peut-être des chaussures. Je ne sens plus mes pieds.", "그리고 신발도 살지 몰라요. 발이 감각이 없어요."),
(H, "Les chaussures d'abord. Le dictionnaire peut attendre.", "신발이 먼저야. 사전은 기다려도 돼."),
(J, "Allez, un dernier chiffre : la semaine. Mardi, 1 980 €.", "자, 마지막 숫자. 이번 주. 화요일 1,980유로."),
(J, "Mercredi, 2 150 €. Jeudi, 2 240 €. Vendredi, 2 910 €.", "수요일 2,150유로. 목요일 2,240유로. 금요일 2,910유로."),
(C, "Plus le samedi, 3 100 €. Je calcule... Ça fait 12 380 € !", "거기에 토요일 3,100유로. 계산해 보면... 12,380유로예요!"),
(H, "Douze mille trois cent quatre-vingts. Tu vois, tu es plus forte que moi.", "만 이천삼백팔십. 봐, 너 나보다 잘하네."),
(C, "Pas du tout, j'ai posé les chiffres sur un papier. Dans la poche, cette fois !", "전혀요, 종이에 써서 계산했어요. 이번엔 주머니 안에서요!"),
(K, "Ha ha ! Dans ta poche, mais avec le chiffre.", "하하! 주머니 속이지만 숫자는 맞았네."),
(H, "Chloé, on ne reparle plus de ça. Tu as très bien progressé.", "클로에, 그 얘긴 이제 그만하자. 너 정말 많이 늘었어."),
(C, "Vraiment ? Je me souviens du premier jour. Je ne savais même pas dire « une table pour deux ».", "정말요? 첫날이 기억나요. « 두 명 자리 »도 말 못 했는데."),
(J, "Tu disais « une table pour deux, s'il vous plaît » en tremblant.", "너 떨면서 « 두 명 자리 부탁합니다 »라고 했었지."),
(C, "Et maintenant, je sais même dire « gérer un coup de feu ».", "지금은 « 정신없는 피크를 잘 넘기다 »라는 말도 할 수 있죠."),
(K, "Tu gères le coup de feu ? Alors tu peux gérer la plonge demain.", "피크를 잘 넘긴다고? 그럼 내일 설거지도 맡을 수 있겠네."),
(C, "Non, pas la plonge ! Moussa va se fâcher.", "아니, 설거지는 안 돼요! 무사가 화낼 거예요."),
(J, "Moussa te pardonnera. Et Mme Vasseur demande toujours « la petite ».", "무사는 널 용서할 거야. 그리고 바쉐 부인은 늘 « 그 아이 »를 찾으셔."),
(C, "Elle m'appelle « la petite » ? Je trouve ça plutôt gentil.", "저를 « 그 아이 »라고 부른다고요? 꽤 다정한 말 같은데요."),
(H, "Bon. Demain, on a le brunch. Combien de réservations, Julien ?", "자. 내일은 브런치가 있어. 예약이 몇 개야, 쥘리앵?"),
(J, "Trente-huit couverts réservés. Ça va être plein.", "38명 예약됐어. 만석이 될 거야."),
(H, "Alors on ouvre à dix heures. Je serai là à huit heures.", "그럼 10시에 연다. 나는 8시에 올게."),
(K, "Moi, j'arriverai à huit heures et demie, avec les brioches de la boulangerie.", "저는 8시 반에 올게요, 빵집 브리오슈 들고요."),
(C, "Moi, je serai là à neuf heures. J'installerai les tables du brunch.", "저는 9시에 올게요. 브런치 테이블을 세팅할게요."),
(J, "Je viendrai avant toi. Quelqu'un doit faire le café, non ?", "나는 너보다 먼저 올게. 누군가는 커피를 내려야 하잖아."),
(H, "Lucien passera sûrement, comme tous les dimanches.", "아버지도 분명 오실 거야, 일요일마다 그러시듯."),
(K, "Il apportera ses proverbes et ses croissants.", "속담이랑 크루아상을 들고 오시겠죠."),
(C, "Et lundi ? On sera tous en vacances ?", "그럼 월요일은요? 다들 쉬는 거죠?"),
(H, "Lundi, le restaurant est fermé. Je dormirai jusqu'à midi, si je peux.", "월요일은 휴무야. 가능하면 점심때까지 잘 거야."),
(J, "Moi, je ferai les papiers de fin de mois. Rien d'excitant.", "나는 월말 서류를 처리할 거야. 신나는 건 하나도 없어."),
(C, "Moi, j'aurai cours à l'école. Un examen de service en salle.", "저는 학교 수업이 있어요. 홀 서비스 시험이요."),
(K, "Tu réussiras. Tu as eu le meilleur professeur de salle de Paris.", "붙을 거야. 파리 최고의 홀 선생님한테 배웠잖아."),
(J, "Merci, Karim. Je note que tu m'as complimenté devant témoins.", "고마워, 카림. 증인 앞에서 날 칭찬한 거 기억해 둘게."),
(K, "Ne t'habitue pas. Je ne le referai pas.", "버릇 들이지 마. 다시는 안 할 거니까."),
(H, "Bon. Tout est prêt ? Le frigo, le gaz, les lumières ?", "자. 다 준비됐어? 냉장고, 가스, 불은?"),
(K, "Frigo fermé, gaz coupé, four éteint. La cuisine est nickel.", "냉장고 닫았고, 가스 잠갔고, 오븐 껐어요. 주방은 깨끗해요."),
(J, "La salle aussi. Les nappes sont changées, les verres sont rangés.", "홀도 그래. 식탁보 갈았고 잔도 정리했어."),
(C, "Je peux y aller, alors ? Mon dernier métro est à minuit.", "그럼 저 가도 돼요? 막차가 자정이에요."),
(H, "Vas-y. Bonne nuit, Chloé. Et merci pour ce soir.", "가 봐. 잘 자, 클로에. 오늘 저녁 고마워."),
(C, "Merci à toi, Hélène. À demain, tout le monde !", "고마워요, 엘렌. 내일 봐요, 모두!"),
(K, "Je pars avec toi, Chloé. On prend le même métro.", "나도 같이 갈게, 클로에. 같은 지하철이잖아."),
(H, "Karim, attends. Les clés de la réserve.", "카림, 잠깐. 창고 열쇠."),
(K, "Les voilà, Chef. Bonne nuit à vous deux.", "여기요, 셰프. 두 분 잘 자요."),
(None, "Karim et Chloé sortent. La porte se referme. Hélène et Julien restent seuls dans la salle.", "카림과 클로에가 나간다. 문이 닫힌다. 엘렌과 쥘리앵만 홀에 남는다."),
(J, "Tu as l'air fatiguée, Hélène. Ou autre chose ?", "피곤해 보여, 엘렌. 아니면 다른 일이야?"),
(H, "Un peu inquiète, en fait. Je ne sais pas pourquoi.", "사실은 조금 불안해. 왜 그런지는 모르겠어."),
(J, "Inquiète ? Après un samedi à 3 100 € ?", "불안하다고? 3,100유로 찍은 토요일 뒤에?"),
(H, "Justement. Quand tout va bien, je me demande ce qui va arriver.", "그러니까 말이야. 다 잘 풀릴수록 무슨 일이 생길지 걱정돼."),
(J, "Tu te fais du souci pour rien. C'est ton caractère.", "괜히 걱정하는 거야. 네 성격이지."),
(H, "Peut-être. Les charges, les fournisseurs, le loyer... Ça pèse toujours.", "그럴지도. 각종 비용, 납품업체, 임대료... 늘 부담이잖아."),
(J, "Le loyer, ça va. Delmas a toujours été correct avec nous.", "임대료는 괜찮아. 델마스 씨는 늘 우리한테 정직했잖아."),
(J, "D'ailleurs, il a téléphoné hier. Il a dit de relever ton courrier.", "참, 어제 전화했어. 네 우편물 확인하라고 하더라."),
(H, "Il veut sûrement parler de la peinture de la façade. Il en parle depuis deux ans.", "분명 건물 외벽 페인트 얘기겠지. 2년째 말하고 있잖아."),
(J, "Sûrement. Allez, je sors les poubelles. Tu éteins la salle ?", "분명 그럴 거야. 자, 쓰레기 내놓고 올게. 홀 불 끌래?"),
(H, "Oui. Je fais le tour. Et je prends le courrier en sortant.", "응. 한 바퀴 돌아볼게. 나갈 때 우편물도 챙길게."),
(None, "23 h 50. Hélène éteint les lumières, ouvre la porte. Dans la boîte aux lettres, une enveloppe épaisse l'attend.", "밤 11시 50분. 엘렌이 불을 끄고 문을 연다. 우편함에 두툼한 봉투가 기다리고 있다."),
(H, "Tiens... Un recommandé. Julien, tu as vu passer le facteur ?", "어... 등기우편이네. 쥘리앵, 우체부 오는 거 봤어?"),
(J, "(de dehors) Non, il est passé pendant le service. Il a dû le laisser dans la boîte.", "(밖에서) 아니, 서비스 중에 왔나 봐. 우편함에 두고 갔나 보다."),
(H, "« Lettre recommandée avec accusé de réception ». Expéditeur : M. Delmas.", "« 수신 확인 등기우편 ». 발신인은 델마스 씨."),
(J, "Ah, tu vois ? La peinture de la façade. Ouvre-la, qu'on en finisse.", "봐, 외벽 페인트 얘기라니까. 열어 봐, 빨리 끝내자."),
(H, "Oui, oui. Je l'ouvre... Il y a trois pages.", "응, 응. 열어 볼게... 세 장이나 되네."),
(J, "Trois pages pour de la peinture ? Il est bavard, notre Delmas.", "페인트에 세 장이나? 델마스 씨 말 많네."),
(H, "« Madame Marchand, par la présente, je vous informe que... »", "« 마르샹 부인, 본 서신으로 알려드립니다... »"),
(J, "Eh bien, continue. Qu'est-ce qu'il dit ?", "그래서, 계속 읽어. 뭐라고 쓰여 있어?"),
(H, "Attends. Je lis la deuxième ligne.", "잠깐만. 두 번째 줄을 읽는 중이야."),
(J, "Hélène ? Tu es toute pâle. Qu'est-ce qu'il y a ?", "엘렌? 얼굴이 하얘졌어. 무슨 일이야?"),
(H, "Non. Non, ce n'est pas possible.", "아니. 아니야, 말도 안 돼."),
(J, "Donne-moi ça. Ou dis-moi au moins ce que tu lis.", "그거 줘 봐. 아니면 뭐가 쓰여 있는지만이라도 말해 줘."),
(H, "Julien... je dois relire. Laisse-moi relire.", "쥘리앵... 다시 읽어야 해. 다시 읽게 해 줘."),
(J, "Hélène, tu me fais peur. C'est grave ?", "엘렌, 무서워. 심각한 거야?"),
(None, "Hélène ne répond pas. Sous la lumière du réverbère, ses doigts serrent la feuille et ses yeux relisent la première phrase.", "엘렌은 대답하지 않는다. 가로등 불빛 아래에서 손가락이 종이를 꽉 쥐고, 눈은 첫 문장을 다시 읽는다."),
(J, "Hélène ? Réponds-moi, s'il te plaît.", "엘렌? 제발 대답해 줘."),
(H, "Ferme la porte, Julien. On rentre. J'ai besoin de m'asseoir.", "문 닫아, 쥘리앵. 안으로 들어가자. 앉아야겠어."),
(J, "D'accord, d'accord. Viens, assieds-toi à la table sept.", "알았어, 알았어. 와, 7번 테이블에 앉아."),
(H, "Merci. Ne dis rien à personne. Pas encore.", "고마워. 아무한테도 말하지 마. 아직은."),
(J, "Je ne dirai rien. Mais tu me racontes demain, promis ?", "아무 말 안 할게. 하지만 내일 얘기해 줄 거지, 약속?"),
]

VOCAB = [
("A2", "Un couvert / cent quatre couverts", "식사 인원 한 명 / 104명 손님", "식당에서 손님 수를 세는 단위. « Midi, 46 couverts. » = quarante-six couverts."),
("A2", "Faire la caisse", "정산하다 (계산대 마감)", "하루 매출과 서랍 속 현금을 맞추는 일. « On fait la caisse avant de partir. »"),
("A2", "Un billet / une pièce", "지폐 / 동전", "« Six billets de cinquante. » « Trente pièces de deux euros. »"),
("A2", "Un pourboire", "팁", "« Les pourboires sont pour l'équipe. » 프랑스에서는 의무가 아니고 팀이 나누는 경우가 많다."),
("A2", "En tout / au total", "합쳐서 / 총", "« 148 € en tout. » 합계를 말할 때."),
("A2", "Ça tombe juste !", "딱 맞아요!", "[구어] 계산이 정확히 맞아떨어질 때. ↔ 정중: Le compte est exact."),
("A2", "À demain !", "내일 봐요!", "퇴근 인사. 밤에는 « Bonne nuit », 가볍게는 « À demain ! »"),
("A2", "Ouvrir / fermer à clé", "열쇠로 열다 / 잠그다", "« Je ferme à clé ? » 마감 때 쓰는 일상 표현."),
("B1", "Tirer le ticket Z", "Z 영수증을 뽑다", "하루 마감 합계를 출력하는 일. « Le ticket Z » 는 영업 마감 합계표."),
("B1", "Le fond de caisse", "시재 (잔돈용 준비금)", "매일 아침 서랍에 넣어 두는 현금. 마감 때 이 금액을 빼야 실제 현금 매출이 나온다."),
("B1", "Un ticket-restaurant", "식권", "회사가 직원에게 주는 점심 식권. 파리 비스트로에서 자주 쓴다. 약칭 « un ticket resto »."),
("B1", "Se faire du souci", "걱정하다", "« Tu te fais du souci pour rien. » ↔ 정중: s'inquiéter. 불안한 마음을 말할 때 가장 일상적이다."),
("B1", "Ça pèse toujours.", "늘 부담이 돼요.", "[구어] 임대료·비용이 마음의 짐이 된다는 뜻. 비유적 peser."),
("B1", "Je serai là à huit heures.", "8시에 올게요.", "미래 약속. 단순미래 être → serai. « Je viendrai avant toi. »"),
("B1", "Nickel", "깨끗한, 완벽한", "[구어] « La cuisine est nickel. » ↔ 정중: très propre / impeccable. 청결·완성도를 칭찬할 때."),
("B2", "Un coup de feu", "피크 타임의 정신없음", "« Tu gères le coup de feu. » 주방에서 가장 바쁜 시간을 가리킨다."),
("B2", "Avoir un mauvais pressentiment / être inquiet", "불길한 예감이 들다 / 불안하다", "« Un peu inquiète, en fait. » 엘렌의 불안을 직접 말하는 장면. 추상적이므로 B2."),
("B2", "Par la présente, je vous informe que...", "이 서신으로 알려드립니다", "공식 서신의 시작 문구. 일상 대화에는 쓰지 않는다. 읽는 법을 알아 두면 법적 서류에 유용하다."),
("B2", "Une lettre recommandée avec accusé de réception", "수신 확인 등기우편", "서명으로 수령을 증명하는 우편. 임대료 변경·해지 통보 같은 중요 서류에 쓴다."),
("C1", "Par la présente / L'expéditeur", "본 서신으로 / 발신인", "공식 문서 어휘. 편지 속 « Expéditeur : M. Delmas » 처럼 발신인을 확인한다."),
("C1", "Sous la lumière du réverbère", "가로등 불빛 아래에서", "지문에 쓰이는 문학적 표현. 장면의 긴장을 시각적으로 돋운다."),
]

GRAM = [
("A2", "현재형으로 하루 정리하기", "« La caisse est juste. » « Midi, 46 couverts. » « Il y a six œufs. » 마감 정산은 현재형과 숫자로 사실을 나열한다. 간단한 문장을 쌓아 가는 것이 핵심이다."),
("A2", "venir de + 부정사 — 방금 한 일", "« La dernière table vient de partir. » 방금 끝난 일을 말한다. venir 를 현재형으로 활용하고 de 뒤에 동사원형. « Il vient de téléphoner. »"),
("B1", "단순미래 — 내일의 계획", "« Je serai là à huit heures. » « Je dormirai jusqu'à midi. » « Il apportera ses proverbes. » 어간 + -ai, -as, -a, -ons, -ez, -ont. 불규칙: être→ser-, aller→ir-, avoir→aur-, faire→fer-, venir→viendr-."),
("B1", "수량·비율 표현 — plus de, moins, divisé par", "« 260 € de plus. » « 148 divisé par quatre. » « Dix pour cent de 2 840. » 숫자 계산을 말로 풀 때는 plus / moins / divisé par / fois. 비교는 « un peu moins de dix pour cent »."),
("B1", "se faire du souci / s'inquiéter — 불안의 표현", "« Tu te fais du souci pour rien. » « Un peu inquiète, en fait. » « Tu me fais peur. » 불안의 정도: inquiet < angoissé < paniqué. 상대에게 걱정을 전할 때는 « Ne t'en fais pas. »"),
("B2", "ne ... plus / ne ... jamais — 변화의 부정", "« Mes jambes ne répondent plus. » « On ne reparle plus de ça. » « Je ne le referai pas. » plus = 이제 더 이상, jamais = 한 번도. 구어에서 ne 가 빠진다: « Je sens plus mes pieds. »"),
("B2", "현재완료로 지난 두 달 돌아보기", "« Tu as très bien progressé. » « Il a téléphoné hier. » passé composé 는 시점이 분명한 완료. 앞 화들에서 배운 서사 표현을 요약할 때 쓴다: 지난 일(passé composé) + 지금(présent) + 내일(futur)."),
]

READ = [
("리에종 — cent_euros / trois_mille", "« 104 couverts » 는 cent quatre couverts. 숫자 뒤에 모음이 오면 연음한다: « trois_euros », « cent_euros ». 단 « cent un » 은 /sɑ̃.œ̃/ 로 t 를 읽지 않는다. « Quatre-vingt-un » 은 /katʁ.vɛ̃.œ̃/."),
("엘리종 — c'est / j'ai / qu'est-ce", "« Qu'est-ce qu'il dit ? » 는 /kɛs.kil.di/ 로 한 숨에. 구어에서는 ne 가 사라져 « Je sens plus mes pieds » 가 /ʒə.sɑ̃.ply.mɛ.pje/ 처럼 들린다."),
("숫자 읽기 — 큰 금액", "« 3 100 € » = trois mille cent euros, « 2 840 € » = deux mille huit cent quarante euros, « 12 380 € » = douze mille trois cent quatre-vingts euros. 낭독할 때는 mille 이후를 숨을 끊어 읽는다: deux mille / huit cent quarante."),
("호흡 구간 — 계산하는 말", "« Six billets de cinquante : / trois cents euros. » 앞부분은 올리고 뒷부분은 내려 마무리한다. « Cent quarante-huit / divisé par quatre, / ça fait trente-sept euros. » 세 구간으로 끊는다."),
("u / ou — pourboire, rouge, juste", "« pourboire » 의 ou 는 /u/, « juste » 의 u 는 /y/. « Ça tombe juste » 의 juste 는 입술을 앞으로 모아 /ʒyst/. ou 와 u 를 바꿔 읽으면 뜻이 달라질 수 있다 (dessous / dessus)."),
("비음 — inquiète, bien, cent", "« inquiète » 의 in 은 /ɛ̃/, « cent » 의 en 은 /ɑ̃/, « bien » 은 /bjɛ̃/. « Un peu inquiète, en fait. » 는 비음이 연달아 나오니 모음마다 입 모양을 분명히 한다."),
("억양 — 클리프행어 대사", "« Non. Non, ce n'est pas possible. » 는 두 번째 « Non » 에서 목소리가 약하게 떨리고 끝은 낮게 가라앉는다. 쥘리앵의 « Hélène ? » 는 끝을 올려 불안을 전한다. 대사 사이에 쉼표 두 박자를 두자."),
]

CULTURE = [
("프랑스 식당의 하루 마감 — la caisse 와 pourboire", "프랑스의 비스트로는 마감 때 계산대(caisse)에서 Z 합계를 뽑고, 현금·카드·티켓 레스토랑을 항목별로 맞춘다. 팁(pourboire)은 법적으로 의무가 아니지만, 모아서 홀·주방 직원이 나눠 갖는 경우가 많다. 이 장면의 « 4등분 » 처럼 투명하게 나누는 것이 팀 분위기를 지킨다."),
("lettre recommandée — 공식 통보의 무게", "프랑스에서 중요한 통지(임대차 변경, 해지, 최고 등)는 보통 « lettre recommandée avec accusé de réception (LRAR) » 로 보낸다. 받은 날짜가 법적 효력의 기준이 되므로, 우편함에서 발견하는 순간 곧 시한이 시작된다. 소상공인에게 건물주의 등기우편은 가볍게 넘길 수 없는 사건이다."),
]

META = dict(part=1, ep=15, part_label="제1부 Mise en place · 봄", title_fr="Fermeture et bilan", title_ko="마감과 정산",
 place="Le Comptoir de Marthe, 6월 13일 토요일 밤 (23시 10분 ~ 자정 무렵)",
 chars="Hélène Marchand (주인 셰프) · Julien Benali (홀 매니저) · Chloé Dubois (견습 서버) · Karim Haddad (부주방장)",
 wine="3,100유로 토요일의 마감 정산 뒤, 우편함에서 발견한 건물주의 등기우편.",
 focus="하루 정리(현재), 내일 계획(단순미래), 숫자·금액 읽기, 불안 표현, 1부 마무리",
 levelmix="A2 45% / B1 35% / B2 15% / C1 5% 목표",
 next="제2부 제16화 « Le courrier du propriétaire » : 엘렌이 읽은 편지의 내용이 공개되고, 가족과 팀은 가게의 다음 계절을 맞는다.")
